### ISSUE TITLE
No Products found in backend Product tab after update of WP 4.4 and Woocommerce  2.4.12

### ISSUE THREAD

**Issue by Turnouts** [woothemes/woocommerce#10007]
Hi and happy new year...

Problem: Since I updated to WP 4.4 and Woocommerce 2.4.12 last month, when I click on the product tab in the WP backend, the list is empty, even though it clearly shows that there are 6 products and no filters are selected.

I am using the Divi theme with Divi child theme plugin and not sure what has happened. When I tried to revert to a backed up version of the site, as I was not able to roll back the WP update, it still didn't work.

Help please...

![image](https://cloud.githubusercontent.com/assets/16579504/12148671/afe4bef6-b497-11e5-8db8-48c1a2ddeef1.png)

**Comment by mikejolley** [comment]
This is not necessarily the theme - you need to rule out other plugins, because this is not reproducible or reported by any other users. Disable plugins to find the cause.
