### ISSUE TITLE
CSS class "related products" is missing a clear:both

### ISSUE THREAD

**Issue by elbsurfer** [woothemes/woocommerce#10016]
Hi,
i have several websites where I use WooCommerce. Since a certain amount of time (I do not know exactly) the display of the related products on the single product detail page looks weird. It is shifted and the headline "related products" comes directly after the cart icon.

When I add a "clear:both;" to the CSS class(es) "related products" everything works fine. Is this a missing CSS selector?

**Comment by mikejolley** [comment]
The default themes/styling doesn't require a clear as pictured https://dl.dropboxusercontent.com/s/yrubdrrjwirow0i/2016-01-07%20at%2010.59.png?dl=0

In some theme layouts, a clear may be needed, but it would be down to the theme to add it (or yourself). On the flip side, adding a clear in all cases could break some layouts which use floats so its best left as is.
