### ISSUE TITLE
Scripts not loaded properly on checkout page if not set as checkout page

### ISSUE THREAD

**Issue by tomslominski** [woothemes/woocommerce#10018]
Hi. I've recently come across an issue in WooCommerce where if a page is not set as the WooCommerce checkout page in the plugin settings, but contains the `[woocommerce_checkout]` shortcode, the checkout page itself will be displayed correctly, but the `checkout.min.js` script will not be enqueued. This causes the payment method information boxes and coupon link to just take the user to the top of the page. It's not a crucial bug, I know, but it stumped me for quite a while as to why the scripts on that page weren't loading.

I assume this happens because [line 191 in class-wc-frontend-scripts.php](https://github.com/woothemes/woocommerce/blob/6a41f4d5b8fc06e02e789e994e2d643c14f56a0d/includes/class-wc-frontend-scripts.php#L191-L193) specifies that script should only be loaded if is_checkout() is true, and I guess is_checkout() is only true on pages that are set as the checkout page in WooCommerce → Settings → Checkout → Checkout Options, rather than those that include the `[woocommerce_checkout]` shortcode.

Is it worth even displaying content from `[woocommerce_checkout]` if the scripts won't be loaded? Maybe a note should be added somewhere in the documentation to reflect this, since I couldn't find anything on this when researching the issue (although now that I've written this, it might be enough :stuck_out_tongue:)?

**Comment by shadyshrif** [comment]
Thank you very much. I'm using not updated version which has this issue and I got the solution from the commit 😀 
This issue appeared on the translation pages which contains the [woocommerce_checkout]

**Comment by joelkarunungan** [comment]
This issue is happening  in 2020 :D version 4.1.0

**Comment by kumarchandang** [comment]
Set this page to woocommerce_checkout page by woocommerce's filter

`add_action('init', function(){
  add_filter( 'woocommerce_is_checkout', '__return_true');
});`

**Comment by joelkarunungan** [comment]
This is a regression and this issue should be reopened
