### ISSUE TITLE
After Upgrading to 2.4.12 Website Stopped Working

### ISSUE THREAD

**Issue by georgegijo** [woothemes/woocommerce#10024]
I made a woocommerce plugin update update from an older version to the latest version 2.4.12. After the upgrade the complete website stopped working. Please let me know where I have to begin debugging.

**Comment by mikejolley** [comment]
I think you may have skipped over https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md#reporting-issues

This is not a support area, and what you've provided is not enough info anyway.

https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1 covers what to do.
