### ISSUE TITLE
How to validate coupon using checkout fields changes

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10039]
How can we grab the changes on billing and shipping checkout fields and validate the coupon using proper filter hook `woocommerce_coupon_is_valid` :)

**Comment by mikejolley** [comment]
wut?

**Comment by shivapoudel** [comment]
@mikejolley  I mean to say can we grab the checkout page billing and shipping address details value to validate the coupons :p

**Comment by shivapoudel** [comment]
Oh! changes on customer billing and shipping checkout fields can be grabbed using `WC_Customer` :p
