### ISSUE TITLE
Grouped products should have the SKU field on the edit product page

### ISSUE THREAD

**Issue by forsvunnet** [woothemes/woocommerce#10034]
On the quick edit page it's possible to edit the SKU for grouped products:
![image](https://cloud.githubusercontent.com/assets/799281/12194650/e63cdb9a-b5f1-11e5-9cbe-7973ff91b378.png)

On the edit product page the SKU field has disappeared:
![image](https://cloud.githubusercontent.com/assets/799281/12194724/543ea77c-b5f2-11e5-83b0-9d489e3b787c.png)

I don't see why the SKU field should be dropped even for a grouped product. It's useful for identifying the collection of products even if it will not used in the order data.

**Comment by mikejolley** [comment]
A SKU is a stock keeping unit. Grouped products are not sold, and have no stock.

**Comment by forsvunnet** [comment]
True, but you could also look at a grouped product as a bundle of components. Much like a variable product. It's the variant that is sold, not the parent product.

**Comment by forsvunnet** [comment]
This might be heresy, but Magento uses SKU for grouped products.
![image](https://cloud.githubusercontent.com/assets/799281/12195445/811e2902-b5f7-11e5-9f2d-b4e16452362e.png)
