### ISSUE TITLE
Displaying dropdown categories without count not possible because array is treated as scalar value

### ISSUE THREAD

**Issue by dogrescuer** [woothemes/woocommerce#10030]
Widget product categories displaying categories as a dropdown ignores the "don't show product count" admin checkbox. This appears to be because 

 includes/wc-term-functions.php line 135 

is an array but is assigned to the local variable as if it were a singular value.

$args['show_count'] = $args;

$args['show_count'] is expecting $args to contain a value (0 or 1) but it contains an array. In fact, it's assigning itself to a member of itself, clearly not what the author intended.

If this line were eliminated, $args['show_count'] would contain a 0 or 1 as read from the admin settings.

**Comment by reigelgallarde** [comment]
it's inside `if ( ! is_array( $args ) ) {}` so in that line, `$args` is not an array.

**Comment by dogrescuer** [comment]
You're right but look at how it's cast:
function wc_product_dropdown_categories( **$args = array()**, $deprecated_hierarchical = 1, $deprecated_show_uncategorized = 1, $deprecated_orderby = '' ) {

The is_array test is failing here as $args is both sent and is received as an array.

Put this line above **if (!is_array($args))**

if (is_array($args)) { echo "is array";}else{echo "not array";}

It returns **is array**



and then it's assigning itself to a member of itself:
$args['show_count']         = $args;

**Comment by dogrescuer** [comment]
You are correct the problem is further down.

Before **$args = wp_parse_args( $args, $defaults );**

Array ( **[show_counts] => 0** [hierarchical] => 1 [show_uncategorized] => 0 [orderby] => name [selected] => [hide_empty] => ) 

After  **$args = wp_parse_args( $args, $defaults );**

Array ( [pad_counts] => 1 **[show_count] => 1** [hierarchical] => 1 [hide_empty] => [show_uncategorized] => 0 [orderby] => name [selected] => [menu_order] => **[show_counts] => 0** ) 

show_count and show_counts.

**Comment by mikejolley** [comment]
'show_count' is only set the $args when you fail to set an array. 

`
_deprecated_argument( 'wc_product_dropdown_categories()', '2.1', 'show_counts, hierarchical, show_uncategorized and orderby arguments are invalid - pass a single array of values instead.' );
`

This is deprecated and no longer used (you used to pass in true/false rather than an array). There is also no 'show_counts' in master.
