### ISSUE TITLE
New Customer Email: Should there be a link to account area?

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/woocommerce#10036]
"You can access your account area to view your orders and change your password here mysite.com/my-account"

Should there be a link to the url in html and multipart emails?

**Comment by mikejolley** [comment]
Most email clients make links clickable. Some, however can strip links you add yourself which can stop users clicking them.

**Comment by ChangePlaces** [comment]
I added a link to the footer of the email, and it didn't strip that. So, for non-webmail clients, maybe it's worth being explicit and adding the link?

**Comment by mikejolley** [comment]
> So, for non-webmail clients, maybe it's worth being explicit and adding the link?

We don't know what client the email will open in.
