### ISSUE TITLE
Why there is no title attribute for product thumbnails on archive pages?

### ISSUE THREAD

**Issue by gthapar** [woothemes/woocommerce#10042]
Hello,

I stumbled on a fairly small SEO issue today. The issue is that there is no title tag present for product thumbnails on archive pages. I cross checked with storefront theme demo and I can't see the  I was able to sort it out by editing the core which is not a good practise I know. But for time being it seems to be the only solution. So my question is why there is no support for title tag?

File: /includes/wc-template-functions.php
Line: 655
Code:

    return get_the_post_thumbnail( $post->ID, $size );

I modified it to

    $image_title = esc_attr( get_the_title( get_post_thumbnail_id() ) );
    return get_the_post_thumbnail( $post->ID, $size, array(
    'title'	=> $image_title,
    'alt'	=> $image_title
    ) );

Any other better way to get the title tag attribute for product thumbnail image markup?

Best Regards,
Gautam Thapar

**Comment by mikejolley** [comment]
ALT is set by WP by default. Title is not, however, doesn't look to be much benefit really: http://www.webnetism.com/shouts/image-alt-tags-and-title-tags-for-seo.aspx

The function is pluggable if you want to change it on your store.
