### ISSUE TITLE
Documentation: Please update the plugin naming example

### ISSUE THREAD

**Issue by Ipstenu** [woothemes/woocommerce#10044]
From https://docs.woothemes.com/document/create-a-plugin/

Since (on pretty much your behest) the Plugin Repo stopped accepting plugins with 'woocommerce' (or any other trademarked term) as the first term of a plugin slug, your example here is causing people to complain to us when we reject 'woocommerce-some-plugin'

> The main plugin file should take the name of the plugin directly. E.g. a plugin with the directory name of woocommerce-some-plugin would have it’s main file named woocommerce-some-plugin.php.

May I recommend you change it to `woo-some-plugin` ?

**Comment by Otto42** [comment]
May I recommend you change it to their-brand-some-plugin instead? Having other people using your brand as their prefix is problematic even when you shorten it. It would be better to recommend people not use that brand in their plugin names at all, but to use their own brand. It's their plugin, not yours.

**Comment by claudiosmweb** [comment]
Updated.
Thanks :smile:
