### ISSUE TITLE
Fatal error: Call to a member function add_product() at Checkout

### ISSUE THREAD

**Issue by oudin** [woothemes/woocommerce#10047]
Hi 

I'm getting the following error when Attempting to checkout on sub-sites of multisite install.

Notice: Trying to get property of non-object in \wp-content\plugins\woocommerce\includes\class-wc-checkout.php on line 215

Fatal error: Call to a member function add_product() on a non-object in \wp-content\plugins\woocommerce\includes\class-wc-checkout.php on line 222

A simple Google search for the error shows many people who are experiencing this issue however no solid solution.

Also note the main site of the multisite install is not affected by this issue. Checkout works as normal.

------
WC Version: 	[?] 	2.4.12
WP Version: 	[?] 	4.4.1

How can I solve this?

**Comment by mikejolley** [comment]
This will mean the order is not being returned after creation. With MULTISITE WooCommerce must be activated PER SITE. It will not function correctly if network activated as some tables will be missing per site. Adding error handling to prevent the fatal.

**Comment by oudin** [comment]
WooCommerce is activated per-site however the error still occurs.

**Comment by mikejolley** [comment]
Read the comments here as it may be related https://github.com/woothemes/woocommerce/issues/9279
