### ISSUE TITLE
Drodpwon categories show count will not turn off

### ISSUE THREAD

**Issue by dogrescuer** [woothemes/woocommerce#10043]
Add the widget product categories to your store; set it to Show Dropdown and Show Heirarchy, but leave showing the count of products within the categories **unchecked**. Display the widget in the store. The product category counts show in parentheses next to the category names despite the widget being instructed not to show counts.

**Comment by mslinnea** [comment]
I've identified the issue and will be submitting a pull request shortly.

**Comment by mslinnea** [comment]
I went to fix the issue but when I forked the master it appeared that it has already been fixed.  I'm guessing that the changes just haven't been released as an official update yet.

**Comment by mikejolley** [comment]
^ will be 2.5 if fixed in master
