### ISSUE TITLE
Review snippet required

### ISSUE THREAD

**Issue by jcastro91** [woothemes/woocommerce#10055]
Although you changed the `itemprop="reviews"`to `itemprop="review"` the issue is still there. The structured data testing tool is still showing the error: http://prntscr.com/9ouo38

**Comment by mikejolley** [comment]
All valid with a default theme - https://dl.dropboxusercontent.com/s/vl8p47bfq9sz9lu/2016-01-12%20at%2009.51.png?dl=0
