### ISSUE TITLE
Export sales by product on WooCommerce

### ISSUE THREAD

**Issue by AurelieClarity** [woothemes/woocommerce#10053]
Hi all, I am trying to optimise my Woocommerce website, and would like to export a CSV report of the sales by products. I managed to get it for Categories, but it's not downloading for products.
When I hit the "export CSV" button, nothing happens. 
I can get an extract of sales for each of the products, but I'd like a cumulated one.
Anyone knows how to do that, or if it's a bug?
Thanks a lot!

**Comment by mikejolley** [comment]
There is no combined report by product. You need to select one: https://dl.dropboxusercontent.com/s/e44pcd1tgp1c67h/2016-01-11%20at%2015.45.png?dl=0

Tested and working example: https://cloudup.com/cpn566QGC4Q
