### ISSUE TITLE
Report->Sales by category not taking into account of the manually added order

### ISSUE THREAD

**Issue by nsoonhui** [woothemes/woocommerce#10057]
It seems that **Sales by Category** ("/wp-admin/admin.php?page=wc-reports&tab=orders&report=sales_by_category") does not take into account of the orders that are added manually.

I discover this when I found that my [kindlemalaysia.com](http://kindlemalaysia.com) store gives different sales figure between **Sales by Date** and **Sales by Category**. I can further pinpoint that the difference is because Sales by Category doesn't take into account of the orders that are added manually.

Let me know if the information I provided is sufficient for you to reproduce the problem, if not, you can log into my test instance to have a look

This is my system information

### WordPress Environment ###

Home URL: http://kindlemalaysia.com
Site URL: http://kindlemalaysia.com
WC Version: 2.4.13
Log Directory Writable: ✔  /nas/content/live/kindlemalaysia/wp-content/uploads/wc-logs/
WP Version: 4.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.13
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (25) ###

Akismet: by Automattic – 3.1.7
Better WordPress Google XML Sitemaps: by Khang Minh – 1.3.1
Elegant Themes Updater: by Elegant Themes – 1.0
Facebook Comments for WordPress: by we8u – 3.1.3
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.1.2
Open Graph: by Will Norris – 1.6
Outbound Link Manager: by Morris Bryant
Ruben Sargsyan – 1.2

WooCommerce PayDollar Payment Gateway: by APPH – 1.2
Post Type Converter: by Voce Communications - Kevin Langley – 0.6
SEO Redirection: by Fakhri Alsadi – 3.4
SEO Ultimate: by SEO Design Solutions – 7.6.5.8
ShareThis: by The ShareThis Team – 7.1
SumoMe: by SumoMe – 1.10
Tiny URL: by Prasanna SP – 1.3.4
WooCommerce Cart Tab: by jameskoster – 0.3.1
WooCommerce iPay88 Payment Gateway: by VanboDevelops – 1.2.7
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce PDF Invoice: by RightPress – 2.1.6
WooCommerce ShareThis Integration: by WooThemes – 1.0
WooCommerce Simply Order Export: by Ankit Gade – 2.0.3
WooCommerce: by WooThemes – 2.4.13
WooThemes Helper: by WooThemes – 1.5.9
WordPress Importer: by wordpressdotorg – 0.6.1
WP Google Plus: by Garman Technical Services – 1.0.1
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #3815 - /shop/
Cart: #3816 - /cart/
Checkout: #3817 - /checkout/
My Account: #3818 - /your-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Divi
Version: 2.5.9
Author URL: http://www.elegantthemes.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Maybe its your status, or the order has no calculated totals. I just did a test and as soon as I set it to 'processing' it appeared in my report. Tested with 2.5 master.

**Comment by nsoonhui** [comment]
Strange. My main point is that I would expect that no matter what, the
sales by category and sales by product figure should tally, but this is not
the case.

**Comment by mikejolley** [comment]
If your manual order has no totals (which sales by date is based on) it won't tally. Generated orders will add up correctly, as will manual orders which were created correctly.

**Comment by nsoonhui** [comment]
# My manual order does have totals.
# My manual order status is set to complete

And yet the sales by category and sales by order are still different.

I am using 2.4.13 woocommerce, Where can I the 2.5 version?

**Comment by mikejolley** [comment]
There are some report fixes in 2.5, however, I retested 2.4 and had the same correct result after adding an order.
