### ISSUE TITLE
wocommerce custom filters

### ISSUE THREAD

**Issue by naqvisyed** [woothemes/woocommerce#10056]
I need to apply custom taxonomy/filters  through wc-rest api like products by location or products by vendors.

Any help would be appreciated.

**Comment by claudiosmweb** [comment]
You can use the filter `woocommerce_api_query_args` to add custom args to your query.
https://github.com/woothemes/woocommerce/blob/f6526d72a72e3e2b110ed6c0f7b18329239c6667/includes/api/class-wc-api-resource.php#L217
