### ISSUE TITLE
Order confirmation emails not sent for new customers from PayPal callback in 2.4.13

### ISSUE THREAD

**Issue by jonrules** [woothemes/woocommerce#10066]
Order confirmation emails are not being sent for a specific case:
1. New customer (no previous user record)
2. PayPal payment gateway

My guess is that the WooCommerce email hooks are no longer being initialized before the 'wc_api_' action. The IPN callback and payment works fine except for the missing emails.

**Comment by mikejolley** [comment]
@jonrules can you double check client error? Because the same system is used regardless of user account.

**Comment by mikejolley** [comment]
Confirmed; the classes load in the same order regardless of user. I suspect your emails are going to spam - was a user with this same issue last week.
