### ISSUE TITLE
Subscriptions module suspension uses == instead of === causing suspend not to show up for admin in frontend

### ISSUE THREAD

**Issue by tedtieken** [woothemes/woocommerce#10061]
module: woocommerce-subscriptions
file: includes\wc-user-functions.php
line 230

    $admin_with_suspension_disallowed = ( current_user_can( 'manage_woocommerce' ) && 0 == get_option( WC_Subscriptions_Admin::$option_prefix . '_max_customer_suspensions', 0 ) ) ? true : false;

Should be

    $admin_with_suspension_disallowed = ( current_user_can( 'manage_woocommerce' ) && 0 === get_option( WC_Subscriptions_Admin::$option_prefix . '_max_customer_suspensions', 0 ) ) ? true : false;

Difference being === vs == the key "unlimited" has a loose equality with int 0.

**Comment by claudiosmweb** [comment]
Subscriptions issues need to reported in http://support.woothemes.com/

**Comment by greguly** [comment]
Sorry, but I think 0 == 0  and 0 === 0 yeld the same results (i.e., true). 

So there is nothing wrong or to be changed here.

**Comment by tedtieken** [comment]
@greguly

0 == 'unlimited' and 0 === 'unlimited" do not evaluate the same
