### ISSUE TITLE
Bulk Product Edit is missing

### ISSUE THREAD

**Issue by hgflags18** [woothemes/woocommerce#10067]
Today after updating Woocommerce to 2.4.13 I am no longer able to edit my products in bulk, such as turning them on or off, price, catagory, attribute, etc. This was available last night before updating to 2.4.13.

the only product Bulk edits now available are:
Move to Trash  or Enable/Disable Shipping Address.

I rechecked the Plugin update Changelog info and neither of the two changes should have created this issue:

    Fix - Potential redirect loop when using 'unforce ssl' setting and a https home URL.
    Fix - Escape option names when cleaning up sessions.

My online conclusion is that it's a bug in the Woocommerce  2.4.13 update.

I am running Wordpress 4.4.1, which I updated a few days ago. I still had the above option to edit products in bulk after that update.

Please let me know if you need any other info.

Thank you for your assistance.
Liz Kassler
973-697-8262
![bulkproductedit-2413](https://cloud.githubusercontent.com/assets/16343031/12306081/fbef980c-ba05-11e5-8e50-8f4c0f9c5bc6.jpg)

**Comment by mountainviper** [comment]
I am running the latest version and I can see Bulk Edit option. Perhaps some conflict?

**Comment by hgflags18** [comment]
I don't think so, doesn't look like that. Same plugins I've had all along. It's no called Bulk Options instead of Bulk edit.

**Comment by hgflags18** [comment]
Just found it! Not a conflict, but the other plugin I updated today was PayPal for Woocommerce byAngeleyes:
Feature - Adds a bulk edit tool to enable/disable shipping at the product level for multiple products at once. (#175)

I'll contact him to let him know of the issue. Thank you!
Liz

**Comment by claudiosmweb** [comment]
Tested and works fine. We don't have anything to remove Bulk Edit for products.
Test your plugins for conflicts.
