### ISSUE TITLE
Disabling COD Gateway breaks shipping settings update

### ISSUE THREAD

**Issue by labmonkey** [woothemes/woocommerce#10072]
In my case I wanted to disable all default payment gateways and leave only one which is 3rd party (stripe gateway plugin). As a result it turned out that my shipping settings couldn't be changed anymore. After some research I noticed that settings are updated only for loaded shippings and none were loaded because the code that loads them is placed inside COD Gateway. In other words disabling COD gateway breaks shipping settings updates.

**Comment by mikejolley** [comment]
Shipping is independent from gateways. I don't have an issue with COD enabled or disabled. Post the steps to reproduce this, as your description is not very clear..

**Comment by labmonkey** [comment]
```
// remove COD gateway
add_filter( 'woocommerce_payment_gateways', function ( $defaults ) {
	$gateways = array_flip( $defaults );
	unset( $gateways['WC_Gateway_COD'] );
	$result = array_values( array_flip( $gateways ) );

	return $result;
} );
```
Now for example go to free shipping settings and change some values. They won't update. The problem is that foreach loop below doesn't trigger because shipping methods are empty.
```

			foreach ( $wc_shipping->get_shipping_methods() as $method_id => $method ) {
				if ( $current_section === sanitize_title( get_class( $method ) ) ) {
					do_action( 'woocommerce_update_options_' . $this->id . '_' . $method->id );
				}
			}
```
in file `woocommerce/includes/admin/settings/class-wc-settings-shipping.php` function `save()`
