### ISSUE TITLE
Woocommerce Forte

### ISSUE THREAD

**Issue by M1ckael** [woothemes/woocommerce#10075]
down vote
favorite
	

Sorry for my english !

I have created a plugin for Mondial Relay, how to work my plugin ? The client check shipping method Mondial Relay, a popup display width all store. Onclick the address store is send in the custom field.

The orders are correctly saved width my custom field, but i want replace the shipping address by my custom field in the mail and admin order. For this i have created a function but it don't work

I have tried this function for display shipping address if exist custom field

    if (!empty(get_post_meta( $wc_order->id, '_field_mondial_relay', true )){
     add_filter( 'woocommerce_order_formatted_shipping_address' , 'woo_custom_order_formatted_shipping_address',10,2 );

     function woo_custom_order_formatted_shipping_address($address, $wc_order) {
    $address = array(
            'first_name'     => get_post_meta( $wc_order->id, '_field_mondial_relay', true ),             );
    return $address; }
    }

I have try another code :

    add_action( 'woocommerce_order_formatted_shipping_address' , 'woo_custom_order_formatted_shipping_address',10,2 );
    function woo_custom_order_formatted_shipping_address($address, $wc_order) {
    $address_mr =  get_post_meta( $wc_order->id, '_field_mondial_relay');
    $address = array('first_name'=> get_post_meta( $wc_order->id, '_field_mondial_relay', true ),);
    if(!empty($address_mr)){
    return $address;
    }
    else{return $shipping_address;}
    }

With this code the shipping address are replace with my custom field, but if i don't have custome field the default shipping address is not displaying.

And another code don't work Pfff

    add_filter( 'woocommerce_order_formatted_shipping_address' , 'woo_custom_order_formatted_shipping_address',10,2 );

    function woo_custom_order_formatted_shipping_address($address, $wc_order) {
	
		$address_mr =  get_post_meta( $wc_order->id, '_field_mondial_relay');
		if($adresse_mr = true){
			$address = array('first_name'=> get_post_meta( $wc_order->id, '_field_mondial_relay', true ),);
			return $address;
		}
		else{
			return false;
		}
	}

Thank you for your response ! Mike :)

**Comment by mikejolley** [comment]
Code like this is not right..

```
if($adresse_mr = true){
```

You're setting it to true, not checking it.

We don't provide support here - its for bug reports, so I need to close this issue. I'm also not 100% sure what you're doing, but definitely check your PHP syntax.

**Comment by M1ckael** [comment]
I Mike, thank's for your repply
I have change my condition with

    if(!empty($adresse_mr))
but not work! I want change the shipping address by a custom field.
Why my condition don't work?

**Comment by mikejolley** [comment]
woocommerce_order_formatted_shipping_address is only used to display addresses in places such as backend. I'm not really sure what you're doing as I said.

**Comment by M1ckael** [comment]
I have add shipping method Mondial Relay with your exmple here : https://docs.woothemes.com/document/shipping-method-api/ 

If the user select shipping methode "Mondial Relay" , they have a box displaying for select the shop.
OnClick the address shop is add in my extra field.
After checkout my extra field is save. it's ok for that.

I want replace shipping address by my extra field in the mail and admin order.

Very thank's for your help and sorry for my english :)

**Comment by mikejolley** [comment]
This hook is not suitable because it's passed through the 'locale'. Requires more changes.

Instead for an easier solution you could use https://docs.woothemes.com/document/add-a-custom-field-in-an-order-to-the-emails/

**Comment by M1ckael** [comment]
I have try this solution and that work fine, But it's not a good solution because in the user mail they have shipping addrress Mondial relay and in the footer the default shippind address. The customer are disturb.

They have a plugin Mondial Relay here http://demo.mondialrelay-woocommerce.com/ and the address work. Hummm i will found !!!

If i find the solution i post  here.
Thnak's so much Mike !

**Comment by M1ckael** [comment]
Hi Mike, 
I have posted my question on the website Wordpres FR and it's perfect ! look

    add_filter( 'woocommerce_order_formatted_shipping_address' , function ($address, $wc_order) {
     $_field_mondial_relay_nom = get_post_meta( $wc_order->id, '_field_mondial_relay_nom', true );
     if ("" !== $_field_mondial_relay) {
	    $address["company"] = $_field_mondial_relay_nom;	
     }
    return $address;
    },10, 2);

Just do it !
My shipping address is replace if i have select the shipping methoe "Mondial Relay" !
Thank's
