### ISSUE TITLE
Stock reduces to "out of stock"  out of 20 after 1 purchase.

### ISSUE THREAD

**Issue by hairygael** [woothemes/woocommerce#10083]
Hello, I have a recent issue with Woocommerce version  2.4.12. WP version 4.1.9.

Example of the behaviour:

   -Product set as stock of 20 so shows 20 out of 20 available.
   -Someone purchase 1 product and complete checkout.
   -Now stock shows on product page "out of stock".
   -Dashboard also shows product "out of stock" instead of what it should show: 19 out of 20 (so stock reduced by 1)

Thanks for your help.

**Comment by mikejolley** [comment]
I could not replicate this locally. Check extensions, the product type (test a new product) particularly if imported, and also the value of this setting which can affect this behaviour:

https://dl.dropboxusercontent.com/s/lzz5vesjlw2fi04/2016-01-18%20at%2010.28.png?dl=0

**Comment by hairygael** [comment]
Thanks Mike for your response.
The threshold setting is not the reason of the issue to my point of understanding.
Not sure what extensions you mean...
The site and the woocommerce products have been imported from my old site, that could be the reason.
I will make a new product to test and let you know.

Thanks

**Comment by mikejolley** [comment]
> extensions 

Plugins which can affect setting and functionality.

**Comment by hairygael** [comment]
Thanks very much.
We got it to work!
Apparently we had to rewrite the math in the plugin to get it to work. I didn't do it myself, I just wouldn't know how to.
Though I think it is strange that we had to do such arrangement.
Crossing my fingers and hoping it didn't affect something else.
Thanks again for your help.
