### ISSUE TITLE
woocommerce show product categories on email

### ISSUE THREAD

**Issue by emin58** [woothemes/woocommerce#10086]
Hi

I need your help.
I installed woommerce and i tested it. so i get a order mail, but in the admin order mail i cant see the Product Category. So how can i add the Product Category to the admin order mail?
And my second Problem ist, i created two different custom fields in my chackout and i dont see it in my order mail too, so how can i add it to mail order mail?

Thanks for your support

**Comment by mikejolley** [comment]
You would need to add it to your email template https://docs.woothemes.com/document/template-structure/

Please note, github is not a support area. Bug reports only please.
