### ISSUE TITLE
Fatal Error Message after checkout

### ISSUE THREAD

**Issue by marvelmurphy** [woothemes/woocommerce#10081]
After paying with credit card, my customers are receiving the following message: 
Fatal error: Call to a member function add() on a non-object in /home/smokyadmin/public_html/wp-content/plugins/woocommerce-gateway-paypal-advanced/class-wc-paypal-advanced.php on line 350

I am using the most up to date version of WooCommerce. The order is still being placed and Paypal is still taking the payment. The message is just freaking out the customers.

**Comment by claudiosmweb** [comment]
Seems like that need to be fixed on `woocommerce-gateway-paypal-advanced` and not an issue on WooCommerce core.
If is a WooThemes plugin, please contact us https://woothemes.com/my-account/create-a-ticket/
