### ISSUE TITLE
Setting image featured api product

### ISSUE THREAD

**Issue by pereiradiogo** [woothemes/woocommerce#10082]
Hi,

After the last update of woocommerce the api of product stop work for update or insert image featured (position 0), always apply the placeholder image.

What happen?

Regards

**Comment by mikejolley** [comment]
Looking at the docs, you need to set featured_src property

https://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product

**Comment by rogerdcarvalho** [comment]
The link [](https://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product )doesn't work. The docs at [](http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) don't mention featured_src at all.

Sending a string as 'featured_src' doesn't create a featured image, and neither does inserting an image with position 0. Could you please reopen this issue and advise?

**Comment by mikejolley** [comment]
This is a year old issue so links are outdated. The new API has different keys - images. Read http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties again, this does not need to be reopened.

**Comment by rogerdcarvalho** [comment]
I read the documentation multiple times. The documentation states: 

`position`	integer	Image position. 0 means that the image is featured.

When I do this, the image posts to WooCommerce but is not set as featured. I performed a search in your issues to see if others had come across this and found this one. I can open a new ticket, but it will literally be the same as what @pereiradiogo put here on Jan 15, 2016. 

Please advise if you'd like me to open a new issue or if you can provide support for this issue here...

**Comment by mikejolley** [comment]
You can reply here, you don't need to log the same thing twice. Did you confirm the image was valid/uploaded to the product? If it's invalid it cannot be applied as featured image. See if it's in the gallery.

**Comment by rogerdcarvalho** [comment]
Yes, the image is valid and uploaded to the product. When viewing the product on the wordpress site, the featured image is the default placeholder image, while the uploaded image appears below it as a small square.

**Comment by mikejolley** [comment]
And to confirm, manually setting featured image in backend works?

**Comment by rogerdcarvalho** [comment]
Yes. When I view the imported product in WooCommerce, I can click 'set product image'. When I do this, I can select the image that was uploaded with the import, and if I do, the same image does replace the placeholder image when viewing the product on the site.

**Comment by mikejolley** [comment]
Ok, I think it's best you share your request then so we can look at what you're sending and to where.

**Comment by brakon** [comment]
@rogerdcarvalho I had the same issue, but once I added position: 0 to my  POST to create a product, it showed the image as featured.

If you just send the images without position it will automatically assign it a position 0 but wont add it to the featured_src, so you need to pass the position yourself.

e.g:
`
 "images": [
            {
                "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg",
                "position": 0
            },
            {
                "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg"
            }
        ]
`

**Comment by danztensai** [comment]
Does anyone find the solution for this? I've encountered the same issue using dropbox as src, but then after I checked woocommerce its showed white small square, I"m using python API to create a product 

`{'status': 'draft', 'name': 'Air Necklace Beans Gray', 'type': 'simple', 'regular_price': '0.0', 'sale_price': '39.9', 'description': 'simple desc ', 'sku': None, 'images': [{'src': 'https://www.dropbox.com/s/vkl7ln5g7i4fvtg/AirNecklaceBeansGray.jpeg'}]}
`
its really frustrating as I cant directly image upload to woocommerce :(

**Comment by simonegosetto** [comment]
> @rogerdcarvalho I had the same issue, but once I added position: 0 to my POST to create a product, it showed the image as featured.
> 
> If you just send the images without position it will automatically assign it a position 0 but wont add it to the featured_src, so you need to pass the position yourself.
> 
> e.g: `"images": [ { "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg", "position": 0 }, { "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg" } ]`

it works ! thanks man

**Comment by MaximG1234** [comment]
It's interesting the inconsistencies people are reporting. I just ran into the same issue and setting position did not work for me, however I was able to resolve the problem by ordering the images array in the order I wish to display the images. 

This successfully resolved the issue in my case.

**Comment by bourbe** [comment]
Position doen't work here 
Just include the id like here under

`    "images": [
        {   "id": 2133,
            "src": "https://ecfr.techubshop.com/wp-content/uploads/2024/02/02.Meilleur-Best-Sac-Bag-a-dos-back-Cabine-Cabin_0037-scaled.webp",
            "alt": "example-image"
            
        },
        {
            "id": 2130,
            "src": "hhttps://ecfr.techubshop.com/wp-content/uploads/2024/02/02.Meilleur-Best-Sac-Bag-a-dos-back-Cabine-Cabin_0040-scaled.webp",
            "alt": "example-image"
        }        
    ]`
