### ISSUE TITLE
Attribute values on checkout: dashes (hyphens) replaced with whitespace

### ISSUE THREAD

**Issue by straightvisions** [woothemes/woocommerce#10093]
Situation: The order review on checkout shows attribute details.

Bug:
If attribute value has a dash/hyphen, like

`22.-23.02.2016`

it will be converted to

`22. 23.02.2016`

**Comment by mikejolley** [comment]
Not happening on my site - this is on the checkout order review section:

https://dl.dropboxusercontent.com/s/e0qnzjv0dmtvks1/2016-01-18%20at%2017.54.png?dl=0

**Comment by mikejolley** [comment]
Confirmed working with 2.5, global and product level attributes, on cart, checkout and view order screens.
