### ISSUE TITLE
Variable meta not clearing

### ISSUE THREAD

**Issue by nbdamian** [woothemes/woocommerce#10096]
When converting from a variable to a simple product. the meta does not clear. This causes issues with the wc_get_product_ids_on_sale() function, which treats the product as if it was on sale. Although when running is_on_sale() on the product, it returns false.

**Comment by claudiosmweb** [comment]
If you need convert to variable to simple product you need to exclude your variations first... Can't be automatic, since people can lose variations by accident.

**Comment by nbdamian** [comment]
Even when you delete the variation, it doesn't clear it.

**Comment by claudiosmweb** [comment]
Need to delete and maybe still click in "update" before change to single.

**Comment by nbdamian** [comment]
Even deleting the variant, updating, changing to simple, updating, it still does not work.

**Comment by claudiosmweb** [comment]
Need to clear your transients then, since `wc_get_product_ids_on_sale()` save transients for it.

**Comment by nbdamian** [comment]
wc_delete_product_transients() did not work.

**Comment by claudiosmweb** [comment]
Nop, need to use `delete_transient( 'wc_products_onsale' )`

**Comment by nbdamian** [comment]
Nope. Still there.
