### ISSUE TITLE
Endless spinning wheel on checkout

### ISSUE THREAD

**Issue by aaronsmulktis** [woothemes/woocommerce#10095]
I've read through countless other related issues, still without success.

Any help would be _greatly appreciated_.

### Details:
* https://mombucha.com
* Valid signed cert issued by GeoTrust
* using NGINX on a Joyent SmartOS box, config seen [here](https://codeshare.io/7cCpo)
* php 5.5.26
* Stripe or PayPal gateways

#### Other conditions:
* no browser errors
* no WooCommerce System Status errors
* XMLRPC.php reads "XML-RPC server accepts POST requests only."
* I've cleared _and_ disabled all caches/CDNs
* I've emptied browser cache and used private browsing windows
* I've disabled all plugins, except WooCommerce
* WP URL settings match, and are consistent throughout DB

I'm building this site pro-bono, and the owner of this business is doing a huge PR push right now and just got some kinda crowdfunded loan, so we're getting desperate.

I'm basically beside myself looking at myself in disgust, I've built multiple WooCommerce sites before, and I'm a pretty experienced fronted dev w/ some sysadmin chops, and I'm still unable to get this working...

# Who wants to be a hero??

**Comment by mikejolley** [comment]
This is not a support forum, I was happy to reply in the comment but a new issue is not needed as this is not a core bug.

You should see a -1 on this page if it were working:

https://mombucha.com/checkout/?wc-ajax=update_order_review

As you don't this is likely permalink related. Settings > Permalinks save. If that doesn't fix, it will likely be the permalink setup you're using in nginx. Ensure it doesn't ignore query strings.

https://codex.wordpress.org/Nginx#General_WordPress_rules
