### ISSUE TITLE
woocommerce_order_status_* is being ignored

### ISSUE THREAD

**Issue by BuggeringHell** [woothemes/woocommerce#10098]
When setting order item meta data via. woocommerce_order_status_on-hold before 2.5.0, the meta data was included in the order email (both admin and customer), but is no longer present. Was this intended?

**Comment by mikejolley** [comment]
The email triggers and status actions did not change in 2.5. You'd need to share the code for me to check, however, you may want to actual check that status is hit. When the email is triggered, a new order object is retrieved along with any changes made before hand.

https://github.com/woothemes/woocommerce/blob/81cfc5030fb328f3fa962cfb2e6fc91893757fc4/includes/emails/class-wc-email-customer-processing-order.php#L51

**Comment by BuggeringHell** [comment]
Here is a similar issue - the function below is not triggered when an order is created using a manual payment method (e.g. Cheque or BACs) which goes from *pending* to *on-hold* immediately upon an order being created. Changing the order back to *pending* and then *on-hold* manually triggers this successfully.

```php

// Add 'unassigned' order post meta if virtual gift cards exist in order
add_action( 'woocommerce_order_status_pending_to_on-hold', 'gift_card_order_meta' );
add_action( 'woocommerce_order_status_pending_to_processing', 'gift_card_order_meta' );

function gift_card_order_meta( $order_id ) {
	
	$gift_card_codes = get_post_meta( $order_id, 'gift_card_codes', true ); 

	if( empty( $gift_card_codes ) ) {
		$order = wc_get_order( $order_id );

		$order_items = $order->get_items();
		foreach ( $order_items as $order_item_id => $order_item ) {
			
			$product_id = $order_item['product_id'];
			$product = wc_get_product( $product_id );
			if( $product ) {
				
				// Make sure order product is a virtual gift card
				if( has_term( 'gift-cards', 'product_cat', $product_id ) && $product->is_virtual() ) {
					add_post_meta( $order_id, 'gift_card_codes', 'unassigned' );
					break;
				}
			}
		}
	}
}
```

**Comment by mikejolley** [comment]
Use woocommerce_order_status_on-hold instead? This would happen without a transition.

**Comment by BuggeringHell** [comment]
Adding `add_action( 'woocommerce_order_status_on-hold', 'gift_card_order_meta' );` gives the same behavior (not being triggered when the order is created, but triggered when manually set back and forth)

I've attached a stripped down plugin zip archive that I'm using to test
[woocommerce-gift-card-manager.zip](https://github.com/woothemes/woocommerce/files/95746/woocommerce-gift-card-manager.zip)

**Comment by mikejolley** [comment]
:p why do this

`
// check for woocommerce and admin
if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) || ! is_admin() )
	return;
`

It's disabled on the frontend!

**Comment by BuggeringHell** [comment]
This is what happens when I pull all nighters

**Comment by mikejolley** [comment]
:D
