### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by Pgrzesiek** [woothemes/woocommerce#10099]
Hello guys

I am from MPC and we are developing premium themes and plugins over Envato Marketplace.

Recently update (2.5) introduced an issue to variation display in one of our product. After a more deep testing we discovered that this issue can be related to Global Attributes imported with XML.

The problems:
- empty $attributes var inside single-product/add-to-cart/variable.php - no variation select
- automatic creation of variations (based on global attributes) inside Product edit is not working, manual adding is fine but variations are also not working

We are testing on a database that we are using at theme preview. It was created 2 years ago on older version of WooCommerce (2.1.x). 

This problem does not occurs with newly created global attributes. We suppose that this problem can be related with the database update. Can anyone reproduce this with old WC data? I think that we can even share the XML with you if needed.

Cheers

**Comment by mikejolley** [comment]
2.1 data may not work in 2.5 without updates. See https://github.com/woothemes/woocommerce/blob/2.4.0/includes/updates/woocommerce-update-2.2.php#L132

That, or the data you're importing for the variable product itself is malformed. This is where it gets retrieved https://github.com/woothemes/woocommerce/blob/35e45e60756b4604095d879402d9f4715fdf6af4/includes/class-wc-product-variable.php#L377

I'd start there and debug what this function gets, if it gets the children (children must have prices). Then you can correct your XML as required.

Alternatively, fix the product manually by setting it up again, export XML and compare your files.
