### ISSUE TITLE
REST API coupon_lines not factoring into total

### ISSUE THREAD

**Issue by tilersmyth** [woothemes/woocommerce#10092]
It seems that the 'amount' field in coupon_lines is not factoring into the order total. Per the screenshot, I am currently using fee_lines as a workaround, which is summing into the the order total, but creating issues in other areas (like email confirmations where fee's are factored in differently). 

I believe total_discount should be updated to reflect coupon_lines, but it is not working. 

FYI, order total in screenshot below is calculated by: [subtotal] + [fee_lines.total] + [total_shipping] + [total_tax] 

![screen-shot-2016-01-18-at-12 21 18-pm](https://cloud.githubusercontent.com/assets/8736328/12398012/e814bff6-bdde-11e5-97df-02a13c25ba73.jpg)

![screen-shot-2016-01-18-at-12 24 12-pm](https://cloud.githubusercontent.com/assets/8736328/12398013/ec06a0ca-bdde-11e5-8cf2-1dd8ea608501.jpg)

**Comment by mikejolley** [comment]
Coupons are only stored there for future reference. The actual discounts need to be applied to the product lines themselves. There is no separate discount total.

**Comment by mikejolley** [comment]
cc @claudiosmweb might want to document this

**Comment by claudiosmweb** [comment]
Calculate discounts only on the cart, that's where is the whole logic of it.
Perhaps in the future we'll use this in the Order object will be possible calculate via API and also in the admin interface.
