### ISSUE TITLE
Mattermost-compatible Webhook

### ISSUE THREAD

**Issue by Aspectek** [woothemes/woocommerce#10094]
**Webhook** does not return values in _'payload={"text":_ style parameter, therefore **Webhooks** cannot be used for **Mattermost** systems (Open-source **Slack** alternative).

**Comment by claudiosmweb** [comment]
In another works... You need "JSONP", right?

**Comment by mikejolley** [comment]
https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md

@claudiosmweb if there is no 'standard' for webhook payloads, I don't think we should be changing how the current payloads are delivered unless bw compatible.

**Comment by claudiosmweb** [comment]
@mikejolley Frankly I don't think we should change it. Should remain as JSON.

**Comment by maxrice** [comment]
I wouldn't change the payload format. @Aspectek you'll want to use some middleware to translate the webhook into the format you need, try [webscript](https://www.webscript.io/) or Zapier.
