### ISSUE TITLE
<form role="search"> doesn't validate.

### ISSUE THREAD

**Issue by reitermarkus** [woothemes/woocommerce#10090]
Also the `label` with `for="s"` has to point to the `input` with **`id="s"`**, not `name="s"`.

**Comment by reitermarkus** [comment]
Thanks for the quick fix, but actually this doesn't work in all cases. The search form could be called from a widget on the same page as the main search form, producing the same `id` twice, which is also invalid.

**Comment by mikejolley** [comment]
The WordPress search widget does the same with 's' it seems.

**Comment by reitermarkus** [comment]
It looks like WordPress has had a [HTML 5 search form](https://codex.wordpress.org/Function_Reference/get_search_form#Default_HTML5_Form) for a while which uses a `span` tag instead of `label` but which still doesn't validate because of `role="search"`. So maybe just use a `span` tag instead or add a check similar to the one found in WordPress?

**Comment by mikejolley** [comment]
I see id="s" on the form - this is in twenty twelve.

**Comment by reitermarkus** [comment]
Well, it's 2016 after all.
