### ISSUE TITLE
Cannot redeclare woocommerce_template_loop_category_title

### ISSUE THREAD

**Issue by toleabivol** [woothemes/woocommerce#10100]
There is a typo in `/includes/wc-template-functions.php on line 532` that throws the error 

    Fatal error: Cannot redeclare woocommerce_template_loop_category_title() (previously declared in /var/www/zeon/functions.php:606) in /var/www/zeon/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 532

**Comment by mikejolley** [comment]
Got it. Avoid overriding this function for now, and will be fixed in 2.5.1

**Comment by hopetawiah** [comment]
Fatal error: Cannot redeclare woocommerce_template_loop_product_title() (previously declared in C:\xampp\htdocs\wema\wp-content\plugins\woocommerce\includes\wc-template-
