### ISSUE TITLE
Hungarian PayPal popup link does not work

### ISSUE THREAD

**Issue by passatgt** [woothemes/woocommerce#10102]
https://www.paypal.com/hu/webapps/mpp/paypal-popup

This is the URL for "What is PayPal?" for hungarian customers, which is 404 on PayPal. I tested with other country codes, only this one is not working i guess. 

Removing HU from the $countries array in line 109 in class-wc-gateway-paypal.php solves the issue.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/10084
