### ISSUE TITLE
Cart ajax doesn't work after upgrade

### ISSUE THREAD

**Issue by Tusko** [woothemes/woocommerce#10101]
Hi!
I have using custom loop and get cart with `<?php do_action( 'woocommerce_after_shop_loop_item' ); ?>`. All worked fine before update.

Now I need to add jQuery code: 

    $('.add_to_cart_button').addClass('ajax_add_to_cart');

After that's all works fine. But I think this is not the right solution

**Comment by mikejolley** [comment]
Add the ajax_add_to_cart to your custom template file or update your template file based on the new version 

https://github.com/woothemes/woocommerce/blob/master/templates/loop/add-to-cart.php

**Comment by Tusko** [comment]
@mikejolley still doen't work.
In shop archive not work too.

**Comment by mikejolley** [comment]
If you switch themes and it works, you will know it's your template file. We added the class because its easier to customise than hardcoding in product types.
