### ISSUE TITLE
Missing quantity in wc_add_to_cart_message function

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce#10114]
It might be good to pass quantity arg to [wc_add_to_cart_message](https://github.com/woothemes/woocommerce/blob/master/includes/wc-cart-functions.php#L66). Also, to its [filter](https://github.com/woothemes/woocommerce/blob/master/includes/wc-cart-functions.php#L88).

When customer bought a product with more than one quantity, the cart message is:

> “Product title” has been added to your cart.

It should be plural:

> “Product title” have been added to your cart.

or better with quantity indicator like:

> 2x “Product title” have been added to your cart.

This is reported by @bryceadams on one of WC extension. As a workaround, I hooked to `wc_add_to_cart_message` and copy part of `wc_add_to_cart_message` function but also checking `$_POST['quantity']`

**Comment by mikejolley** [comment]
This function handles arrays of item IDs too, so it is not straightforward to make this fully qty aware. But we can trigger the plural case.

**Comment by gedex** [comment]
> But we can trigger the plural case.

Sounds good.
