### ISSUE TITLE
REST API Product categories - documentation

### ISSUE THREAD

**Issue by scudai** [woothemes/woocommerce#10113]
Hi,
I want to report just a small typo in documentation of product category attributes:

```count	boolean	Shows the quantity of products in this category```

I guess, it should be integer. I know it is just an typo but still, let's have it consistent :)

Thank you

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce-rest-api-docs/commit/a23d51971e939367aa8c193601188b20df214d46
