### ISSUE TITLE
Incorrect tax rounding on line items

### ISSUE THREAD

**Issue by joewebber** [woothemes/woocommerce#10121]
The tax that is displayed on an order when viewing through the admin area is incorrect. This only occurs for line items, total tax for the order is correct.

See the attached example.
The actual tax value for the line item is 2.875, which should be rounded up to 2.88.
The total tax for the order confirms this.

![screen shot 2016-01-18 at 12 21 25](https://cloud.githubusercontent.com/assets/8928703/12456388/7a99f346-bf97-11e5-8eca-633f32859034.png)

**Comment by mikejolley** [comment]
When we have prices inclusive of tax, tax rounds half down, product prices half up.

This is so you don't get into a situation where you have, for example a 9.99 product, with 8.325 ex tax and a tax amount of 1.665 making the sum £10 instead of 9.99.

**Comment by joewebber** [comment]
Ok, but I discovered the issue when using the API to get order data.
In this case, the returned value for that line item was returned as 2.88 - meaning the API is returning a different value to the website

**Comment by joewebber** [comment]
It also means that the order display is wrong - see the screenshot.

£2.87 + £2.56 != £5.44

**Comment by mikejolley** [comment]
@claudiosmweb can you check that the API round function rounds with the tax class?

@joewebber I can't tell from your screenshot where the rounded 1p is coming from. Nor have you provided a system status report so I can see if you're using core tax calculations or a plugin.

**Comment by joewebber** [comment]
Sorry...


### WordPress Environment ###

Home URL: https://www.dirtpunk.co.uk
Site URL: https://www.dirtpunk.co.uk
WC Version: 2.4.10
Log Directory Writable: ✔  /var/www/vhosts/dirtpunk.co.uk/httpdocs/wp-content/uploads/wc-logs/
WP Version: 4.3.2
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.43
PHP Post Max Size: 2 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SOAP Client class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.10
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (20) ###

AddThis Sharing Buttons: by The AddThis Team – 5.2.0
Advanced Custom Fields Pro: by elliot condon – 5.3.2.2
Akismet: by Automattic – 3.1.5
WooCommerce Back In Stock Notifier: by Fantastic Plugins – 7.9
Homepage Control: by WooThemes – 2.0.1
Newsletter Sign-Up: by Danny van Kooten – 2.0.5
Regenerate Thumbnails: by Viper007Bond – 2.2.4
Simple Lightbox: by Archetyped – 2.5.2
Smart Manager: by Store Apps – 3.9.10
Storefront Blog Customiser: by WooThemes – 1.1.2
Storefront Site Logo: by WooAssist – 1.1.2
Storefront WooCommerce Customiser: by WooThemes – 1.6.0 – 1.8.0 is available
Woocommerce Variations Table - Grid: by Spyros Vlachopoulos – 1.1.9
WooCommerce Customer/Order CSV Import Suite: by WooThemes / SkyVerge – 2.8.0 – 2.9.0 is available
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Royal Mail: by WooThemes / Mike Jolley – 2.3.0 – 2.3.1 is available
WooCommerce: by WooThemes – 2.4.10
WooThemes Helper: by WooThemes – 1.5.9
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.1.7
YouTube: by EmbedPlus Team – 10.9

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://designamite.co.uk
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 1.5.1
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme/woocommerce/emails/email-footer.php
storefront-child-theme/woocommerce/emails/email-header.php
storefront-child-theme/woocommerce/emails/email-styles.php
storefront-child-theme/woocommerce/single-product/product-attributes.php

**Comment by mikejolley** [comment]
Is shipping tax in your example  2.565 by any chance?

**Comment by joewebber** [comment]
No. 2.5645

**Comment by mikejolley** [comment]
Right. So at line item, the product is displayed rounded half down - 2.87

But when calculating totals, its 2.875 + 2.5645 = 5.4395 which is where the 5.44 comes from.

**Comment by joewebber** [comment]
Ok, that makes sense.

My only remaining question, why does the API return 2.88? Surely it would be better if it returned the actual value (2.875)?

**Comment by mikejolley** [comment]
@claudiosmweb will look at that.

**Comment by joewebber** [comment]
I've just discovered that the api has a filter option that allows the decimal places to be specified.
Adding the 'dp' filter and setting the value to 4 produces the result I was expecting.

**Comment by claudiosmweb** [comment]
Yep, default are `2` but can be changed by `dp` filter.
I'll add it to the docs.
Thanks,

**Comment by melbwebdesign** [comment]
@joewebber I'm having the same issue, 1 x line items reporting line total is $26.95 and order total is $26.96.  Where do you set the dp filter?
