### ISSUE TITLE
No more call to rest API web hook since last WC update to 2.5.0

### ISSUE THREAD

**Issue by martinlef** [woothemes/woocommerce#10125]
Hi,

I have defined a web hook triggered upon order.created event and this seemed to be working until I updated WC to version 2.5.0. Now it does not call the url any more when event occurs (order.created).

![rest-api](https://cloud.githubusercontent.com/assets/16806176/12462339/0954bd0c-bfbe-11e5-8194-81e6e60668ed.png)

Can anybody help?

**Comment by claudiosmweb** [comment]
Tested and works fine, not a 2.5.0 issue.
