### ISSUE TITLE
Provide git diffs/patches for template changes and possibly also a template update script

### ISSUE THREAD

**Issue by pelmered** [woothemes/woocommerce#10139]
It would be very nice if you could provide git diffs/patches that you can just apply(with `git apply file.patch`) on your templates to apply the latest template changes whenever there is a template change in WooCommerce. 

A big bonus if you also could provide some kind of script to apply all the patches for the templates you have in your theme. The script would check what templates the theme is overriding and then try to apply the patches if they are outdated. Maybe a WP CLI command?

This would help a lot for everyone who you maintain a WooCommerce theme(and a
has a basic knowledge about Git). 

What do you think? Some more more input on this would be great.

**Comment by mikejolley** [comment]
The only case a template override should be made is to do a major customisation of it - if thats happened then it's very unlikely a patch will cleanly merge. And that could also have unforeseen consequences, if the customisation is not compatible with the changes made.

If a theme doesn't change a template file, it should not bundle it.

By the way, how many template overrides does storefront have? https://github.com/woothemes/storefront None :)

**Comment by pelmered** [comment]
If the patch does not cleanly merge you will get a merge conflict which is a good starting point for updating the template. The diff is also useful to see exactly what has been changed. You get very limited information about this by reading the change log of the update announcement on the WooCommerce blog. It would be nice to have the diffs provided for you, but sure, you can make the diff yourself if you need it. 

I know you can do almost anything with the hooks but sometimes you have to override the templates to accomplish what you want or it is just the cleaner solution to just override the template instead of adding 30 hooks and a lot of callbacks too move everything around. However, I feel that is another discussion that is not really relevant here. Many people override templates, that's a fact.

**Comment by mikejolley** [comment]
You can view commits per template via github. I cannot see a good way to automate it all though.

**Comment by claudiosmweb** [comment]
@pelmered here, take this:

```bash
#!/bin/sh

read -p "FROM: " FROM
read -p "TO: " TO

wget -r -np -k http://plugins.svn.wordpress.org/woocommerce/tags/$FROM/templates/
wget -r -np -k http://plugins.svn.wordpress.org/woocommerce/tags/$TO/templates/

cd plugins.svn.wordpress.org/woocommerce/tags/

diff -bur $FROM/templates/ $TO/templates/ > ../../../templates-from-$FROM-to-$TO.patch

exit;
```

Good luck.

**Comment by pelmered** [comment]
I understand your reasoning for not providing this. 
Thanks a lot @claudiosmweb! Looks like a great starting point. I will test this tomorrow.
