### ISSUE TITLE
image title set via api

### ISSUE THREAD

**Issue by qschneider** [woothemes/woocommerce#10131]
Hi, setting image titles via api was introduced in woocommerce 2.5 and it seems to me that this is only working for the first image title.
At least for me, setting titles of multiple images of a product in a single api call just sets the first image title. All others stay blank.

**Comment by claudiosmweb** [comment]
Show me your JSON.

**Comment by qschneider** [comment]
Hi, this is the 1. actual request send (for an existing product), 2. data send and 3. response i got back.
Hope it helps.


1. request 
$response = $apiProducts->edit_product($id_to_edit, $data);


2. json_encode($data) gives
{
    "product": {
      "title": "type 61 DJI 3",
      "categories": [30],
      "images": [{
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-with-drone.jpg",
        "position": 0,
        "title": "type 61 DJI 3-1"
      }, {
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-open.jpg",
        "position": 1,
        "title": "type 61 DJI 3-2"
      }, {
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3.jpg",
        "position": 2,
        "title": "type 61 DJI 3-3"
      }, {
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3-with-drone.jpg",
        "position": 3,
        "title": "type 61 DJI 3-4"
      }, {
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3-open.jpg",
        "position": 4,
        "title": "type 61 DJI 3-5"
      }, {
        "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3.jpg",
        "position": 5,
        "title": "type 61 DJI 3-6"
      }]
    }
}


3. json_encode($response_product) gives
{
    "title": "type 61 DJI 3",
    "id": 30548,
    "created_at": "2016-01-07T16:33:42Z",
    "updated_at": "2016-01-22T09:50:28Z",
    "type": "simple",
    "status": "publish",
    "downloadable": false,
    "virtual": false,
    "permalink": "http:\/\/devwebsite.gtpm.intra\/product\/typ-61-dji-3\/",
    "sku": "",
    "price": "",
    "regular_price": "",
    "sale_price": null,
    "price_html": "",
    "taxable": false,
    "tax_status": "taxable",
    "tax_class": "",
    "managing_stock": false,
    "stock_quantity": null,
    "in_stock": true,
    "backorders_allowed": false,
    "backordered": false,
    "sold_individually": false,
    "purchaseable": false,
    "featured": false,
    "visible": true,
    "catalog_visibility": "visible",
    "on_sale": false,
    "product_url": "",
    "button_text": "",
    "weight": null,
    "dimensions": {
      "length": "",
      "width": "",
      "height": "",
      "unit": "mm"
    },
    "shipping_required": true,
    "shipping_taxable": true,
    "shipping_class": "",
    "shipping_class_id": null,
    "description": "",
    "short_description": "",
    "reviews_allowed": true,
    "average_rating": "0.00",
    "rating_count": 0,
    "related_ids": [7194, 7390, 7230, 7086, 7450],
    "upsell_ids": [],
    "cross_sell_ids": [],
    "parent_id": 0,
    "categories": ["OUTDOOR.CASES"],
    "tags": [],
    "images": [{
      "id": 33639,
      "created_at": "2016-01-22T09:50:28Z",
      "updated_at": "2016-01-22T09:50:29Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-with-drone-5.jpg",
      "title": "type 61 DJI 3-1",
      "alt": "",
      "position": 0
    }, {
      "id": 33641,
      "created_at": "2016-01-22T09:50:29Z",
      "updated_at": "2016-01-22T09:50:29Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-open-5.jpg",
      "title": "",
      "alt": "",
      "position": 1
    }, {
      "id": 33643,
      "created_at": "2016-01-22T09:50:29Z",
      "updated_at": "2016-01-22T09:50:29Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-5.jpg",
      "title": "",
      "alt": "",
      "position": 2
    }, {
      "id": 33645,
      "created_at": "2016-01-22T09:50:30Z",
      "updated_at": "2016-01-22T09:50:30Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3-with-drone-5.jpg",
      "title": "",
      "alt": "",
      "position": 3
    }, {
      "id": 33647,
      "created_at": "2016-01-22T09:50:30Z",
      "updated_at": "2016-01-22T09:50:30Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3-open-5.jpg",
      "title": "",
      "alt": "",
      "position": 4
    }, {
      "id": 33649,
      "created_at": "2016-01-22T09:50:31Z",
      "updated_at": "2016-01-22T09:50:31Z",
      "src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-O-DJI3-5.jpg",
      "title": "",
      "alt": "",
      "position": 5
    }],
    "featured_src": "http:\/\/devwebsite.gtpm.intra\/wp-content\/uploads\/2016\/01\/61-B-DJI3-with-drone-5.jpg",
    "attributes": [],
    "downloads": [],
    "download_limit": 0,
    "download_expiry": 0,
    "download_type": "",
    "purchase_note": "",
    "total_sales": 0,
    "variations": [],
    "parent": [],
    "grouped_products": [],
    "menu_order": 1
}
