### ISSUE TITLE
Sale by Date with partial and fully refund problem.

### ISSUE THREAD

**Issue by telilbo** [woothemes/woocommerce#10138]
Hello. I'm Alan.

today, i found report sale by date(current day) problem with refund.

try this. 

1) in 2015-01-01, customer buy item and create order (price 100$).
at this time, sale by date show correct price in report.

2) in 2015-01-02, and then, partial refund in order edit (partial refund price -50$)
at this time, sale by date report not show partial refund price. and order status not changed.

3) in 2015-01-03, and then, left amount price fully refund in order edit 
(fully refund price -50$, order total : 0$)
and order status change to refunded. at this time, sale by date report show refund price about total refund price in order(-100$)

so, in 2015-01-03, sale by date report says refund price is -100$. is it right? 
why, refund price amount is different? 
i refund just -50$ in 2015-01-03 day, but showing fully refund price. 
and in 2015-01-02, sale by date report not says partial refund price(-50$). 

i think, sale by date report will do, partial and fully refund is check each prcess day. 
please, someone check this. 

ps. if you don't understand i will upload screen capture movie.

Thanks

**Comment by mikejolley** [comment]
@claudiosmweb this was part of the reports PR https://github.com/woothemes/woocommerce/commit/6cc700a49751eda373db60aad2e1431f615ad1b6. That one is safe for 2.5 but needs some more testing.
