### ISSUE TITLE
Checkout infinite reloading

### ISSUE THREAD

**Issue by kimmenbert** [woothemes/woocommerce#10134]
Experienced this on a project and thought it was something with my code.
Now I´ve tried with a fresh WP install with a fresh WooCommerce 2.5.0 and the issue is the same. Follow these steps to check for issue:

1. Complete one purchase, register as user (don´t use existing account).
2. When purchase is complete, go to shop and add product to cart, while logged in as the newly created customer
3. Go to checkout, the reloading starts

Tried with storefront theme as well

Is this happening to anybody else?

**Comment by mikejolley** [comment]
View > Developer > Javascript console in chrome, look for an error.

**Comment by kimmenbert** [comment]
No errors, screencast:
http://det.maksimer.es/15An3/44HLbTZ0

**Comment by mikejolley** [comment]
Can you look at the network tab as outlined here http://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/ See what is happening.

**Comment by mikejolley** [comment]
Nevermind, I've got it happening too. Investigating.

**Comment by mikejolley** [comment]
@kimmenbert can you confirm that works?

**Comment by kimmenbert** [comment]
@mikejolley Tested and confirming that it´s working, great!
