### ISSUE TITLE
Storefront Sticky Add to Cart looks transparent

### ISSUE THREAD

**Issue by Belzun** [woothemes/woocommerce#10136]
The plugin Storefront Sticky Add to Cart looks transparent, not opaque as it should look.

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)
