### ISSUE TITLE
Woocommerce 2.5 issue

### ISSUE THREAD

**Issue by whealy** [woothemes/woocommerce#10146]
Since I upgraded to 2.5 some products are displaying gallery images as well as the product image on the shop and category pages. Is this a known issue and how do I fix this? 
![shop screenshot](https://cloud.githubusercontent.com/assets/16843191/12521326/f57d884c-c141-11e5-9c45-8919b442f9cd.PNG)

**Comment by mikejolley** [comment]
This is something the theme author will need to look at. WC core doesn't output gallery images here. Look for an update.

**Comment by whealy** [comment]
Thank you for the info.
