### ISSUE TITLE
Tax calculation text on tax incl setting displays shop base country instead of billing country

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#10148]
Tax included calculations are incorrect when there is no tax rate for all countries.

To reproduce the issue:

* I have my shop base set in the US
* I have my tax settings as such: https://cloudup.com/cP3H7IKjxNH
* I have a 50% tax for the country `GB`
* I have no other taxes in the standard rate
* I have a product that I specified the price as $20
* I add that product to the cart, with my delivery and billing address in the UK, and this is the display:

![](https://cldup.com/igSOPBlSMr.png)

The problems I have with this:

* I am shipping and billing to the UK. WooCommerce knows this, why isn't it giving me tax calculation for that country?
* For US, there shouldn't be tax at all

If I then change the delivery and billing address to be in Germany (nor the base address, nor have a line for tax), this is what I get:

![](https://cldup.com/ko-g54LTEW.png)

It seems the calculation itself is correct, but the text shows the shop base country instead of the actual billing country.

I tried setting the countries to US: calculation is correct that there's no tax.

I added a 100% tax rate for Germany. Calculation is correct, but display still shows US.

I changed shop base to India, the text changed to India as well.

**Comment by mikejolley** [comment]
`has_calculated_shipping()` is returning false in your case. Seems this is only true after 'calculating totals' on the cart page.
