### ISSUE TITLE
Excel-like Product manager

### ISSUE THREAD

**Issue by JosefJezek** [woothemes/woocommerce#10155]
Could you create Excel-like Product manager?

Like this plugin...
https://wordpress.org/plugins/excel-like-price-change-for-woocommerce-and-wp-e-commerce-light/
http://holest.com/index.php/holest-outsourcing/joomla-wordpress/excel-like-manager-for-woocommerce-and-wp-e-commerce.html

Library
https://handsontable.com

![image](https://cloud.githubusercontent.com/assets/2110319/12533437/f5e91dca-c22f-11e5-8c99-d1c80a3ee03b.png)

**Comment by claudiosmweb** [comment]
Please use our issue tracker for core WooCommerce issues only.
You can suggest new plugins here: http://ideas.woothemes.com/forums/133476-woocommerce

**Comment by claudiosmweb** [comment]
And you can create spreadsheets and import using: https://www.woothemes.com/products/product-csv-import-suite/
