### ISSUE TITLE
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by nishitlangaliya** [woothemes/woocommerce#10159]
Hello Team,

I am using woocommerce subscription plugin for my store and using standard paypal payment getway.but since last 7 to 8 days I am getting this 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'  while doing payment through paypal so can you please let me know how can I sort it.

I have attached the screenshot here.
![ssl_routines_erro](https://cloud.githubusercontent.com/assets/11435772/12547167/c4d09650-c374-11e5-8170-b7501695d74e.png)

**Comment by mikejolley** [comment]
Caused by outdated server CURL/OpenSSL http://ocportal.com/forum/topicview/misc/deploying/error-14077410-ssl.htm Your server is trying to communicate using an old insecure protocol.

**Comment by nishitlangaliya** [comment]
@mikejolley 

Thank you so much for you reply. It's working fine in WooCommerce version 2.2.2 with same server. But in my other site, I am using WooCommerce 2.4.10 and It's give error. Is it solve issue if I upgrade WooCommerce to latest version?

Below are my server details:
SSL Version:  OpenSSL/0.9.8k
PHP Version: 5.3.6

Can you please suggest any steps to solve this issue?

Thanks in advance.
