### ISSUE TITLE
Save Coupon ID as order item meta

### ISSUE THREAD

**Issue by bekarice** [woothemes/woocommerce#10158]
Proposing that coupon IDs (or slugs) are stored in `woocommerce_order_itemmeta` for a coupon line item. Currently only the coupon post_title is stored as part of an order, but the coupon's post ID is never stored within the order record.

This poses a challenge if you want to filter your orders by coupon used, as if the coupon's code (post_title) ever changes (ie fixing a typo, changing the year in the code), then you can't properly get a list of orders that have used the coupon by using the ID instead of the coupon code.

Adding this would also open up the ability to fix / improve the way coupon usage can be viewed by implementing proper filtering by coupon usage. When clicking the coupon usage count, it simply searches for coupon code, which is problematic if the coupon title is also used in a product name, matches a customer name, etc, as extra (incorrect) results are returned, rendering this view useless for some sites.

Could be implemented as part of #10071, but seems like adding this meta to orders before those changes has no real downside imo.

**Comment by mikejolley** [comment]
I don't agree with this one. If coupons were not a custom post type, CODE would be the unique identifier here. The coupon code itself is what should be reported on.

Your example of year for example. If I had DISCOUNT2015 and renamed to DISCOUNT2016, technically these are completely different coupon code and thus should be reported separately IMHO.

> When clicking the coupon usage count, it simply searches for coupon code, which is problematic if the coupon title is also used in a product name, matches a customer name, etc, as extra (incorrect) results are returned, rendering this view useless for some sites.

This reporting can/will be improved with #10071 hopefully, when the queries are easier to generate. We can rethink how coupons are associated with orders when working on that.

cc @claudiosmweb
