### ISSUE TITLE
Sales tax not collected on shipping

### ISSUE THREAD

**Issue by LPCBooks** [woothemes/woocommerce#10157]
In the settings area there is the option to add tax to shipping. I've checked this (some months ago) but now realize WooCommerce isn't actually collecting tax on shipping. Checked or unchecked, it doesn't matter. 

Let me know when you get this one resolved since we're responsible for sending the tax on shipping to NC - even when it's not collected from our customers.

**Comment by mikejolley** [comment]
- Tax rates need to have the 'Shipping' checkbox set or they only apply to products
- If the shipping method has a 'taxable' option it needs to be enabled
- If its a custom shipping method which doesn't handle taxes, that is outside of core's hands

There is no core bug. It's a configuration issue.

**Comment by mikejolley** [comment]
Also the "Shipping Tax Class" option can affect which rates apply.

**Comment by LPCBooks** [comment]
If the shipping method has a 'taxable' option it needs to be enabled

This was the missing information. Thanks.
	
Eddie Jones  | Founder, CEO 
Lighthouse Publishing of the Carolinas | Raleigh, NC, United States
lighthousepublishingofthecarolinas.com
lighthousepublishingcarolinas@gmail.com
