### ISSUE TITLE
Why 'Shipping Display Mode' option removed in 2.5 ?

### ISSUE THREAD

**Issue by nishitlangaliya** [woothemes/woocommerce#10152]
Hello Team
cc @mikejolley 
I have just updated my woocommerce to 2.5 and I see that in woocommerce settings page shipping options ' Shipping Display Mode' option has removed.

So This is causing issue to many users that they had so many shipping method in their site current radio button functionality makes their shipping page huge in length.

I think  'Shipping Display Mode' option should be there isn't it ? Can you please share your thoughts why this is removed ? so that I can improve my knowledge into this :)

Please let us know your thoughts for the same.

Thanks,
Nishit Langaliya

**Comment by Carclod** [comment]
I completely agree. The radio buttons look awful on my site and I would rather have the drop down list restored.

**Comment by mikejolley** [comment]
I'll justify it again..

1. You cannot add additional content 'around' each shipping method in a dropdown. Radios you can.
2. If shipping methods change after recalculation *they are hidden from the user in a dropdown*. Radios improve usability.
3. Maintaining 2 separate views in core is a burden for us, and an extra thing that needs styling for theme devs.

Unstyled radio buttons does not justify switching to a dropdown. Fix the CSS styles in your theme.

> makes their shipping page huge in length.

Maybe you should rethink why exactly you're presenting so many options to the user - this cannot be great for conversions!!

p.s. in future raise questions/discussions like this **before** release. This change was announced on the dev blog well in advance of release.

**Comment by Carclod** [comment]
I really don't think there is any need to be so discourteous. Not all of us
are techies who read your Dev blog so I'm not sure how we were meant to
know this.

It's the last time I ever raise an issue here, I quite like the idea of
keeping my head

**Comment by nishitlangaliya** [comment]
@mikejolley,

Thanks for reply . Sure I will update my self for upcoming features by reading dev blog :)

**Comment by mikejolley** [comment]
@carclod sorry, I've just had to post that several times :) so far there have been no valid arguments for the drop downs - just people being anti-change. I think it's for the best. If you have an example site where the styling is odd, post a link so we can see if it's our fault or the theme.

**Comment by claudiosmweb** [comment]
@nishitlangaliya @Carclod here what plugin developers can do now with it:

![f5fdd4c0-9e5a-11e5-85f1-bf237ad8adfa](https://cloud.githubusercontent.com/assets/1264099/12531127/8309ee9c-c1da-11e5-8650-d0607b67b962.png)

**Comment by Carclod** [comment]
@mikejolley No worries :+1:  I understand, I'll get my CSS styles fixed

**Comment by extrapixel** [comment]
@claudiosanches regarding that screenshots you posted - how would you implement such functionality (e.g. "sub-options" for shipping methods)? I can't seem to find the right hooks to implement this.
