### ISSUE TITLE
Redirect Loop in Checkout after cancelling/going back from payment. (NEW USERS)

### ISSUE THREAD

**Issue by dabodude** [woothemes/woocommerce#10151]
Hi!

Just noticed a new bug for WooCommerce 2.5 when a new customer creates an account and then cancels his order.

You can replicate this bug by creating an order, go through paypal and then cancel the payment to be taken to the cart again. Then if you go to the checkout you'll get the redirect loop.

BTW: user and password auto generated.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/a26af7b801e1eca3d47279ccc99b16f1c340d7c8
