### ISSUE TITLE
missing translation bug & location

### ISSUE THREAD

**Issue by bourdet** [woothemes/woocommerce#10154]
hello, since the update WooCommerce 2.5, two problems arise:
the line "shippings Will Be Calculated ounce Provided you-have your address" is not translated and impossible to find in  files "languages" searching "Poedit" tells me that everything is translated .... but what that he or she does not appear in any file? Is it an oversight ?
The second problem is related to this one since this sentence appears in the Delivery tab of the control page ... which prevents finalizing an order: each time I try the page tells me "delivery method invalid "I then turning around .... I hope not to end up in whirling dervish.
joking aside, if you can refer me it will be a real pleasure
This further said two points:
a big thank you for your work and my apologies for possible syntax errors and / or vocabulary ... sorry but I do not speak English ....

**Comment by bourdet** [comment]
if necessary I can maybe join an image capture or some thing like that ... finally ... what will be needed if I can ...
Thank you.

**Comment by claudiosmweb** [comment]
Not is missing and don't have any bug.
Everything is 100% translatable... I already translated to pt_BR and is not missing any string.
Perhaps the strings part of another plugin or theme.

Consider help the translation for your language in: https://translate.wordpress.org/projects/wp-plugins/woocommerce

**Comment by bourdet** [comment]
Good evening, thank you for your response.
It is quite possible that it does not come from the translation for indeed
everything seems perfectly translated, this does not prevent this little
problem ... but I end up finding much or that comes and I would keep you
informed. ... if I'm not lost in the lines of code ...
Best regards.

2016-01-23 21:40 GMT+01:00 Claudio Sanches <notifications@github.com>:
