### ISSUE TITLE
Cross domain cart for subblog path and a mapped domain

### ISSUE THREAD

**Issue by mrbm** [woothemes/woocommerce#10169]
I have a single woocommerce installed on a blog instance in a multi-site relm with a mapped domain.

 - blog1mappeddomain.com
 - networkname.com/blog1/

When NOT logged in and when added products on blog1mappeddomain.com I can see the products inblog1mappeddomain.com/cart/ but will not be able to see the products I had added in blog1mappeddomain.com in the networkname.com/blog1/cart/

I would like to be able to see those products so that I can use the ssl I have set up on networkname.com

I have control of the server.

Can you suggest a method of having the cart cookies be shared and work cross domain for both these domains:

 - blog1mappeddomain.com 
 - networkname.com/blog1/

I've tried modifying the wc_setcookie function to set a cookie for the respective paths and domains, however there must be something else needed as when going to the alternate domain the cookies aren't set.

Thanks for the help!

**Comment by mikejolley** [comment]
WooCommerce uses the same cookie settings as WordPress (e.g WordPress login cookie). To change the cookie domain you need to use a constant:

https://codex.wordpress.org/Editing_wp-config.php#Set_Cookie_Domain

I don't think cookies can work across different domain names like your example. You should choose 1 domain and redirect to it from all other domains.
