### ISSUE TITLE
After last update Continue Shopping redirects to product instead to shop page

### ISSUE THREAD

**Issue by lonerunner** [woothemes/woocommerce#10164]
When you add a product to the cart it normally redirects you to the cart and display a notice “Product” has been added to your cart. With Continue Shopping button.

After last update of WooCommerce, Continue Shopping button doesn't redirect to Shop page like before, instead it redirects to product page of product that is last added to the cart.

**Comment by mikejolley** [comment]
Continue shopping redirects to the referring page.

`
$return_to = apply_filters( 'woocommerce_continue_shopping_redirect', wp_get_referer() ? wp_get_referer() : home_url() );
`
