### ISSUE TITLE
WooCommerce Reports errors when refunds are involved

### ISSUE THREAD

**Issue by AFS-GW** [woothemes/woocommerce#10160]
Although the WooCommerce Reports work fine for sales, there appear to be several errors when full and/or partial refunds are involved. Please see attached Word document. Thanks.
[REPORTS TEST.docx](https://github.com/woothemes/woocommerce/files/103038/REPORTS.TEST.docx)

**Comment by SiR-DanieL** [comment]
I also see an issue with refunds Reports.

![](http://cld.wthms.co/1dT03/5JBComef+)

This is one order only in the report.

And the order:

![](http://cld.wthms.co/106cU/3FNPshpm+)

I used the Refund value field with manual refunds. The amount is not reflected at all in the report.

**Comment by mikejolley** [comment]
This commit clears up double reporting when combining partial and full refunds https://github.com/woothemes/woocommerce/commit/f5140af918ec28aff8034a835379d6d7ec9abcc5
