### ISSUE TITLE
WooCommerce not updating completed orders to Complete with Tracking number from ShipStation

### ISSUE THREAD

**Issue by broitzman** [woothemes/woocommerce#10168]
Hi!  Please help!

WooCommerce is not updating our completed orders to "Complete" status with the tracking number attached.  We use ShipStation and contacted them today.  They told us they are sending the info to WooCommerce and it is being received by WooCommerce, but WooCommerce is not updating when the info is received.  Attached is the email from ShipStation and our System Status.

Thanks for your help!
QT

	
Joe Samondo (ShipStation)
Jan 25, 11:03 AM

Hey Troy,

Attached are two feeds examples for the tracking information being sent from ShipStation to WooCommerce.
One on the date of 1/23 and the order I just resent the tracking info again on 1/25. This is for order number WF-92337

Please let me know if you need anything else.

Thanks for working with us,

Joe Samondo
User Success Specialist
2815 Exposition Blvd
Austin, TX 78703

Attachment(s)
TrackingFeeds-107055-145802300-20160125-2016-01-25-06-50-42 (1).txt
TrackingFeeds-107055-145802300-20160123-2016-01-23-09-02-24.txt
[TrackingFeeds-107055-145802300-20160123-2016-01-23-09-02-24.txt](https://github.com/woothemes/woocommerce/files/103694/TrackingFeeds-107055-145802300-20160123-2016-01-23-09-02-24.txt)
[TrackingFeeds-107055-145802300-20160125-2016-01-25-06-50-42 (1).txt](https://github.com/woothemes/woocommerce/files/103695/TrackingFeeds-107055-145802300-20160125-2016-01-25-06-50-42.1.txt)

Troy Broit	
Troy Broitzman
Jan 25, 9:47 AM

I have tried on numerous orders to send notification to marketplace and it does not fix the issue.

This has been an ongoing issue with SS & Woo since November of 15.

Please feel free to call me directly if you want me to walk you through this faster.

Troy
239-290-5007

### WordPress Environment ###

Home URL: https://washerfan.com
Site URL: https://washerfan.com
WC Version: 2.5.1
Log Directory Writable: ✔  /var/www/html/wp-content/uploads/wc-logs/
WP Version: 4.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Amazon) OpenSSL/1.0.1k-fips PHP/5.4.45
PHP Version: 5.4.45
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 2120
SUHOSIN Installed: –
MySQL Version: 5.6.19
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (32) ###

LayerSlider WP: by Kreatura Media – 5.6.2
Amazon Web Services: by Delicious Brains – 0.3.4
Async JS and CSS: by elCHAVALdelaWEB – 1.7.13
bbPress: by The bbPress Community – 2.5.8
CMS Tree Page View: by Pär Thernström – 1.2.34
Contact Form 7: by Takayuki Miyoshi – 4.3.1
Crazyegg-Heatmap-Tracking: by Crazyegg – 1.1
Custom CSS Manager: by MyWebsiteAdvisor – 1.5.2
downML - Download Media Library: by aneeskA
contact@aneeska.com – 0.4.6

Duplicator: by LifeInTheGrid – 1.1.0
Fusion Core: by ThemeFusion – 1.7.7
Media File Renamer: by Jordy Meow – 2.6.6
PayPal for WooCommerce: by Angell EYE – 1.1.9.1
Post Duplicator: by Metaphor Creations – 2.14
Remove query strings from static resources: by Your WP Expert – 1.3
Reviews: by Dilip – 1.0.0
Revolution Slider: by ThemePunch – 5.0.9
Search & Replace: by Frank Bültge – 2.7.1
SEO Redirection Premium: by Fakhri Alsadi – 2.5
SSH SFTP Updater Support: by TerraFrost – 0.7.1
The Events Calendar: by Modern Tribe
Inc. – 4.0.5

W3 Total Cache: by Frederick Townes – 0.9.4.1
Booster for WooCommerce: by Algoritmika Ltd – 2.3.11
WooCommerce - ShipStation Integration: by WooThemes – 4.1.3
WooCommerce: by WooThemes – 2.5.1
WooThemes Helper: by WooThemes – 1.5.9
Wordfence Security: by Wordfence – 6.0.23
WordPress Importer: by wordpressdotorg – 0.6.1
Yoast SEO: by Team Yoast – 3.0.7
WordPress SEO For Image: by wpblogtuts – 1.1.2
WP User Avatar: by flippercode – 2.0.4
Clef: by Clef – 2.3.3

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #2190 - /shop/
Cart: #2191 - /cart/
Checkout: #2192 - /checkout/
My Account: #2193 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Avada Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 3.8.8
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/cart/shipping-calculator.php
Avada/woocommerce/checkout/form-checkout.php
Avada/woocommerce/checkout/form-pay.php version 2.4.7 is out of date. The core version is 2.5.0
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 2.5.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/loop/pagination.php
Avada/woocommerce/myaccount/form-edit-address.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 2.5.0
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php

: Learn how to update outdated templates

API Version: 3.1.0

### WC Pages ###

Shop Base: #2190 - /shop/
Cart: #2191 - /cart/
Checkout: #2192 - /checkout/
My Account: #2193 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Avada Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 3.8.8
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/cart/shipping-calculator.php
Avada/woocommerce/checkout/form-checkout.php
Avada/woocommerce/checkout/form-pay.php version 2.4.7 is out of date. The core version is 2.5.0
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 2.5.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/loop/pagination.php
Avada/woocommerce/myaccount/form-edit-address.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 2.5.0
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php

: Learn how to update outdated templates

**Comment by mikejolley** [comment]
have you posted this on support.woothemes.com?

**Comment by mikejolley** [comment]
^

**Comment by broitzman** [comment]
no. I will now.  thanks!

**Comment by csfriedman** [comment]
We are having the same issue... Did you ever find a solution/ the cause?

Thanks!

**Comment by broitzman** [comment]
We updated to a newer version of both Woo Com and Woo Com ShipStation and it started working again after about 6 weeks of it not working correctly. We have updated to each newer version since then and everything seems to work ok still. Contact Woo Com and ShipStation supports directly if not they were helpful.
