### ISSUE TITLE
Use of function deprecated in WP 4.5

### ISSUE THREAD

**Issue by hareesh-pillai** [woothemes/woocommerce#10163]
The function [`get_currentuserinfo()`](https://codex.wordpress.org/Function_Reference/get_currentuserinfo) is deprecated in WordPress 4.5. See [#36311](https://core.trac.wordpress.org/changeset/36311) on WordPress Trac.
It is advised to use [`wp_get_current_user()`](https://codex.wordpress.org/Function_Reference/wp_get_current_user) instead.

**Comment by shivapoudel** [comment]
@hareesh-pillai It's been fixed [see here](https://github.com/woothemes/woocommerce/commit/0049415797c05ec11baa57e2a91fddcc19975525) :)

**Comment by mikejolley** [comment]
Please search before raising issues.
