### ISSUE TITLE
Discount Cupon Help

### ISSUE THREAD

**Issue by velicuicristian** [woothemes/woocommerce#10166]
Hello.

I have a problem with discount coupons .
In the store we have discount products and products with normal price .

I like when in the cart is a sale product and one or more products with normal price . Discount coupon to count only products with normal price .

Do you think you can ?

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)
