### ISSUE TITLE
Clearing scheduled jobs on deactivating plugin

### ISSUE THREAD

**Issue by ernilambar** [woothemes/woocommerce#10161]
Plugin uses several cron jobs and those are registered while plugin activation. But I noticed that when plugin is deactivated those registered schedule jobs are not cleared. Is this intentional and expected behavior? If this issue is already discussed can someone please share that ticket?

 Thanks

**Comment by ernilambar** [comment]
I have one question. Should we clean schedule on `Uninstall` or `Deactivation`?

**Comment by mikejolley** [comment]
Uninstall is where we remove traces of WC.
