### ISSUE TITLE
1 item + tax, refunded, showing a rounding error

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#10162]
An order with a single item, plus VAT (no shipping), when refunded with a line-item refund, is showing a net VAT of -0.01 in the order dashboard.

Screenshot:
![2](https://cloud.githubusercontent.com/assets/1962275/12548916/81af1734-c351-11e5-9f92-570899c1467c.png)

This is with WC 2.5.0.

**Comment by mikejolley** [comment]
Edit line items? I don't get a rounding error here, but my lines are not to 2dp due to prices including tax

**Comment by mikejolley** [comment]
@DavidAnderson684

**Comment by DavidAnderson684** [comment]
Sorry - I need the "Edit line items?" question interpreting a bit... what is it you're asking?

**Comment by mikejolley** [comment]
Edit the items so I can see what the actual totals are. Your screenshot just shows rounded values.

**Comment by DavidAnderson684** [comment]
Here you go...

![2](https://cloud.githubusercontent.com/assets/1962275/12549895/52e31584-c358-11e5-932c-5bc81b6477c8.png)

**Comment by mikejolley** [comment]
@DavidAnderson684 so with the above, If I refund 1 item, it tries to refund 9.07. 

Thats 7.5 and 1.575 in the top boxes, and 9.07 in the total.

If I manually correct the total to 9.08 and leave the lines as is, I get the correct totals regardless and no 1p error on the tax.

So how exactly did you end up with the above totals?

**Comment by DavidAnderson684** [comment]
> So how exactly did you end up with the above totals?

1) A customer bought the product, then requested a refund through a support channel.

2) The support agent made the refund by pressing "Refund", pressing the quantity-up button to refund the line item, entered "HS#4029" into the description box, and pressed "Refund" to complete the refund.

**Comment by DavidAnderson684** [comment]
OK - I see what you're saying now. If I delete the refund, and manually refund it again, I see this:

![2](https://cloud.githubusercontent.com/assets/1962275/12552026/db6fc254-c366-11e5-8697-ea0bcd7e2eb9.png)

I'm guessing that our support agent spotted the discrepancy between "9.07" and "9.08", and corrected that manually - but didn't realise the implications of not also correcting 1.575 to 1.58.

**Comment by DavidAnderson684** [comment]
PayPal (when I look-up via logging in at PayPal) shows the transaction as 9.08.

All the permutations of things that could be done when rounding or not-rounding taxes gets complex, as you'll know better than me. (I have some experience from being the developer of an EU VAT compliance plugin). But, it seems like, on an order with only a single line item, refunding that line item resulting in a 1 cent discrepancy in the suggested refund total, and needing to manually correct two things to make things reconcile, can't be the right outcome.

**Comment by DavidAnderson684** [comment]
Further experimentation shows that I actually get this result when I manually correct both boxes.

i.e. manually changing 1.575 to 1.58 VAT for the line item, which then automatically changes 9.07 to 9.08 in the total (i.e. I don't actually need to change that second one manually), leaves the result shown in the original screenshot, of a minus 0.01 VAT balance.

So, I guess that's what the support rep originally did. i.e.:

1) He pressed the "up" arrow to indicate to refund the line item

2) He noticed a total of 9.07, instead of 9.08. To fix that, he looked at the VAT line, spotted 1.575, and he surmised that this was the cause. So, he changed it to 1.58, to match the shown line item. Then he refunded.

Reproducing that sequence reproduces the issue for me.
