### ISSUE TITLE
Import tax rates only works with "Standard"

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#10174]
If you create a new tax class or use one that is not the "Standard", when you try to Import the CSV, all the rates are imported for the Standard class and not the class you were editing.

To reproduce, go to Settings > Tax > Zero Rate Rates and click on Import CSV.
Import a CSV with tax rates and then check again the Zero Rate table. It will be empty, and all the imported rates will show in the Standard rate table instead.

Reported in ticket #377681

**Comment by mikejolley** [comment]
@SiR-DanieL the import link is the same for all tax sections - you are aware you need a column for tax class in your CSV?
