### ISSUE TITLE
Woocommerce is not working with large number of variations

### ISSUE THREAD

**Issue by ddeath** [woothemes/woocommerce#10176]
Hi there,

I would like to ask why everybody keep saying that 500 variations is a huge number? Why we can not to optimize the woocommerce in the way that it will be able to handle 10 000 variations... ?

I have a product with a 12 000 variations and it even does not load single-product page.

So for example [https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L395-L409](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L395-L409):

	foreach ( $this->get_children() as $child_id ) {
		$variation = $this->get_child( $child_id );
		if ( ! empty( $variation->variation_id ) ) {
			if ( ! $variation->variation_is_visible() ) {
				continue; // Disabled or hidden
			}
			$child_variation_attributes = $variation->get_variation_attributes();
			if ( isset( $child_variation_attributes[ $attribute_field_name ] ) ) {
				$values[] = $child_variation_attributes[ $attribute_field_name ];
			}
		}
	}

Creates 54 000 queries to DB. If we would replace it with raw queries:

	$query_string = "SELECT DISTINCT `meta_value` FROM $wpdb->postmeta WHERE `meta_key` = %s AND `post_id` IN (SELECT `id` as `post_id` FROM $wpdb->posts as main_table WHERE `post_parent` = %d AND `post_type` = 'product_variation' AND `post_status` = 'publish' )";
	$attrs = [$attribute_field_name, $this->id];
	$attr_values = $wpdb->get_results($wpdb->prepare($query_string, $attrs), ARRAY_N);

	foreach ($attr_values as $item){
		$values[] = $item[0];
	}

Then it is only 134 queries

**Comment by mikejolley** [comment]
This is a large number - you need to bare in mind, you're displaying these within a single product, it needs to calculate whats available, what options to show, min/max prices etc etc. This can take a long time to process if you have this many variations. Not to mention it must be near impossible to manage via backend.

What are you doing? There are alternatives to variations.

e.g. large number of skus as simple products, browsable with layered nav.

or not linking all variations and having 1 with 1 price and no stock management, set to   'all attributes' so you still get customer choices but no overhead.

**Comment by ddeath** [comment]
I have thousands of variations, each with unique price.

**Comment by mikejolley** [comment]
How is your example code a replacement? There is no check to see if enabled and it returns different data?

If you have ideas for optimisations that are backwards compatible and don't break other usages please raise a PR

**Comment by mikejolley** [comment]
For reference https://github.com/woothemes/woocommerce/blob/bd6d7412447428ec39baaac2f20842df2f9dc197/includes/class-wc-product-variation.php#L210-L224

If queries can account for this, and you can prove a speed in processing I'd be happy to include. Raw queries can also be cached using wp_cache to further improve performance.

Please raise a PR though - that would be a better place to discuss each change.

**Comment by mikejolley** [comment]
cc @claudiosmweb
