### ISSUE TITLE
PROBLEM on images

### ISSUE THREAD

**Issue by tazotodua** [woothemes/woocommerce#10171]
there is problem in Woocommerce Plugin:

when you mouseover on the another (product gallery) image, it is not clickable:
http://i.imgur.com/XxMQQte.png

because in the code block:
<div class="summary entry-summary">

the last element of it, there should be <div style="clear:both;"></div>

or: the elelemt : 
<div class="after-product-summary"> should have "clear:both;" parameter.

**Comment by claudiosmweb** [comment]
> there is problem in Woocommerce Plugin:

Nop, problem in your theme, since it works fine on WordPress default themes.
