### ISSUE TITLE
Manually add reviews

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#10175]
I can manually add reviews to a product from the admin, but I can't add the rating to it.

Also the box title is"Reviews" but the buttons and other text say "Comment":

![](http://cld.wthms.co/smlD/4HNDttmw+)

**Comment by mikejolley** [comment]
I don't think having this meta box visible is necessary when editing products. Let's scrap it verses making a custom box - reviews can be moderated elsewhere.

**Comment by vladimirlukyanov** [comment]
Bad solution – 2017 year here, nothing changed

**Comment by szyam** [comment]
I'm setting up a new WP store for a client that has past reviews from older site that I'd like to add to the new store. However, when I add them in the content box on the product page, it says the review is from me. Anyway to leave reviews from others here? I'd think an admin would have that control? Thanks!
