### ISSUE TITLE
Woocommerce 2.5.1 with Paypal Sandbox environment

### ISSUE THREAD

**Issue by DaveWP** [woothemes/woocommerce#10178]
Hi

Paypal have recently switched off their http: interface on the Sandbox and I have recently installed the required SSL certificate.  When I examine the Woocommerce debug log, the status of the IPN response code is

01-26-2016 @ 16:35:39 - IPN Response: WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
                )

        )

    [error_data] => Array
        (
        )

)

I have approached by ISP, who says the problem is the requests should be made using TLSv1.2

**Comment by claudiosmweb** [comment]
Error on your server:

> error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

And not related with:

>  I have recently installed the required SSL certificate

This error is because your server is not able to verify the PayPal SSL.
This happens when using an old version of OpenSSL. Try update or re-install OpenSSL in your server.

But this is not an issue on WooCommerce.
