### ISSUE TITLE
update and problems with the non user order link and general condition check box

### ISSUE THREAD

**Issue by elodieg14** [woothemes/woocommerce#10181]
Hello, 

I have updated wordpress and woocommerce this weekend and since I have noticed that it's not possible to click on the link to order as a guest. My customers have to create an account and I want to let theme choose to order with as user account or as non-user account.

Also, I don't see anymore the checkbox for the general conditions. This box is important to proceed the order.

Even if all the field are complete, it says that I have to fll out the name, adress...and accept the general conditions but I can't the them. And my customer can't order now.

Everything is updated. Here are my info:

### WordPress Environment ###

Home URL: http://www.lovely-choses.com
Site URL: http://www.lovely-choses.com
WC Version: 2.5.1
Log Directory Writable: ✔  /homepages/11/d305614879/htdocs/wp-content/uploads/wc-logs/
WP Version: 4.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.30
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.1.73
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (17) ###

Analytics WP: par Sonicity – 1.0.0
WP Backup Plugin: par Umar – 1.2
Contact Form 7: par Takayuki Miyoshi – 4.3.1
Instagram Feed: par Smash Balloon – 1.3.11
Shortcode Widget: par Gagan Deep Singh – 1.2
uSquare: par br0 – 1.0
WooCommerce Cart Based Shipping: par Bolder Elements – 3.0
WooCommerce: par WooThemes – 2.5.1
Yoast SEO: par L'équipe Yoast – 3.0.7
WP deferred javaScript: par Willy Bahuaud
Daniel Roch
Grégory Viguier – 2.0.2

YITH WooCommerce Ajax Product Filter: par yithemes – 2.7.3
YITH WooCommerce Compare: par Yithemes – 2.0.6
YITH WooCommerce Order Tracking Premium: par Yithemes – 1.2.5
YITH WooCommerce Quick View: par Yithemes – 1.1.0
YITH WooCommerce Waiting List: par Yithemes – 1.0.4
YITH WooCommerce Wishlist: par Yithemes – 2.0.13
YITH WooCommerce Zoom Magnifier: par Yithemes – 1.2.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Base Boutique: #579 - /boutique/
Panier: #43 - /panier/
Commande: #44 - /commande/
Mon Compte: #45 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Bazar
Version: 2.6.6
Author URL: http://yithemes.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: bazar/woocommerce/archive-product.php
bazar/woocommerce/cart/cart-empty.php
bazar/woocommerce/cart/cart-shipping.php
bazar/woocommerce/cart/cart-totals.php
bazar/woocommerce/cart/cart.php
bazar/woocommerce/cart/cross-sells.php
bazar/woocommerce/cart/mini-cart.php
bazar/woocommerce/cart/shipping-calculator.php
bazar/woocommerce/checkout/cart-errors.php
bazar/woocommerce/checkout/form-billing.php
bazar/woocommerce/checkout/form-checkout.php
bazar/woocommerce/checkout/form-coupon.php
bazar/woocommerce/checkout/form-login.php
bazar/woocommerce/checkout/form-pay.php version 1.6.4 est obsolète. La version du core est 2.5.0
bazar/woocommerce/checkout/form-shipping.php
bazar/woocommerce/checkout/review-order.php
bazar/woocommerce/checkout/thankyou.php
bazar/woocommerce/content-product.php
bazar/woocommerce/content-product_cat.php
bazar/woocommerce/content-single-product.php
bazar/woocommerce/global/breadcrumb.php
bazar/woocommerce/global/form-login.php
bazar/woocommerce/global/sidebar.php
bazar/woocommerce/global/wrapper-end.php
bazar/woocommerce/global/wrapper-start.php
bazar/woocommerce/loop/add-to-cart.php
bazar/woocommerce/loop/no-products-found.php
bazar/woocommerce/loop/pagination.php
bazar/woocommerce/loop/price.php
bazar/woocommerce/loop/sale-flash.php
bazar/woocommerce/myaccount/form-login.php
bazar/woocommerce/myaccount/my-account.php
bazar/woocommerce/order/order-details.php version 2.3.0 est obsolète. La version du core est 2.5.0
bazar/woocommerce/single-product/add-to-cart/external.php
bazar/woocommerce/single-product/add-to-cart/grouped.php
bazar/woocommerce/single-product/add-to-cart/simple.php
bazar/woocommerce/single-product/add-to-cart/variable.php
bazar/woocommerce/single-product/price.php
bazar/woocommerce/single-product/product-image.php
bazar/woocommerce/single-product/product-thumbnails.php
bazar/woocommerce/single-product/rating.php
bazar/woocommerce/single-product/related.php
bazar/woocommerce/single-product/review.php
bazar/woocommerce/single-product/sale-flash.php
bazar/woocommerce/single-product/short-description.php
bazar/woocommerce/single-product/tabs/description.php
bazar/woocommerce/single-product/tabs/tabs.php
bazar/woocommerce/single-product/title.php
bazar/woocommerce/single-product/up-sells.php
bazar/woocommerce/single-product-reviews.php
bazar/woocommerce/single-product.php

Thank you very much for your help.

**Comment by mikejolley** [comment]
You should check with the theme author that it is compatible with 2.5.0, and see if they have updates. This theme appears to have a custom checkout process (step based) which core doesn't use.
