### ISSUE TITLE
Woocommerce 2.5.1 shopping cart doesn't work properly for non-login users 

### ISSUE THREAD

**Issue by Victorwooc** [woothemes/woocommerce#10180]
Hi
Woocommerce had been working fine on my website and I really appreciate your excellent jobs.  However, the shopping cart doesn't work properly for non-login customers after it was updated to Woocommerce 2.5.1.  There are problems adding and deleting items from the cart.

**Comment by mikejolley** [comment]
I'm not seeing such a problem our side. Check caching plugins and theme template changes - system status report can help with that. Also, if you post back or in future, please provide more details + status reports.
