### ISSUE TITLE
Order By Price not working correctly

### ISSUE THREAD

**Issue by shawn-northrop** [woothemes/woocommerce#10182]
I am trying to retrieve products from the API and order by price but I am seeing some strange behavior.
An example result set of product prices in order:

$1.00
$10.00
$110.00
$2.00
$200.00
$2.50

It seems like its comparing these values as strings rather than floats (or something of the sorts). therefore 110.00 comes before 2.00

**Comment by mikejolley** [comment]
Rather than using meta_value for orderby, you'd use meta_value_num

**Comment by shawn-northrop** [comment]
Great, that works! I guess the real issue is with the documentation: http://woothemes.github.io/woocommerce-rest-api-docs/#parameters

Under OrderBy, meta_value_num is never referenced and the example for ordering by price is incorrect:

"the meta key to order returned resources by when using orderby=meta_value. For example, you could order products by price using GET /products?filter[orderby]=meta_value&filter[orderby_meta_key]=_price"

**Comment by rahuladams** [comment]
The issue still exists.

**Comment by creativefold** [comment]
I have an issue whereby i'd like variation products to use the lowest price rather than appear incorrect when using the filter 'Sort by Price: High to low' - how can I achieve this?

**Comment by AhmadStar922** [comment]
i have the same problem order by price 'asc' or 'desc' don't work
