### ISSUE TITLE
Using a country name for product category in a non-English install triggers its translation

### ISSUE THREAD

**Issue by jfarsen** [woothemes/woocommerce#10183]
I have opened two tickets (#362668, #376980) with Woo support, but since this is for WooCommerce itself, might be better to submit here.

When adding a product-category called "Granada" on a site in French (native, no translation plugins), the category name gets automatically translated for display to "Grenade". The product category name should remain "Granada", there is no reason for translation to be trigerred...

To make sure it wasn't the client's specific site build, I used another test site, also in French, which uses TwentySixteen, and created a Product Category called "Granada" and you can clearly see in the WC Category widget that the "Granada" has been converted to "Grenade"

Other test site : http://www.webintegrateur.com/boutique

What I did notice is that the woocommerce-fr_FR.po/mo includes the translation pair Granada/Grenada (line 14,998), but why it's getting called by your code for categories is beyond me...

**Comment by mikejolley** [comment]
Category names when output get wrapped with translation functions. This is for compatibility with plugins such as WPML which need to do translation of terms dynamically.
