### ISSUE TITLE
[API] [V2] class-wc-api-products.php allow tags to be pushed as string.

### ISSUE THREAD

**Issue by sim1camporeale** [woothemes/woocommerce#10197]
In this commit  https://github.com/woothemes/woocommerce/commit/88003436a6a9a3dbac48d8e30d5bf64939ca401d  @claudiosmweb added properly sanitisation for categories and tags in products.

As I commented on  Aug 18, 2015 I suggest to relax this constraint only for tags.

I read Wordpress documentation at http://codex.wordpress.org/Function_Reference/wp_set_object_terms#Adding_Categories_to_a_Post
 
I agree that categories must be handled in this way. I think that we have to consider to relax this constraint only for tags (that are non-hierarchical by definition).

For example wp_set_post_terms accepts "term slug" for tags and "term id" for categories. http://codex.wordpress.org/Function_Reference/wp_set_post_terms

>$terms
>(string,array) (optional) List of terms. Can be an array or a comma separated string. If you want to enter >terms of a hierarchical taxonomy like categories, then use IDs. If you want to add non-hierarchical terms >like tags, then use names.
>Default: array

**Comment by claudiosmweb** [comment]
We have already adopted as a standard now and we'll keep it.
Beyond that already exists endpoint for tags and categories, so makes it simple to retrieve IDs.
