### ISSUE TITLE
Woocommerce 2.5.1 Slows Wordpress on WebhostingNZ

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#10193]
I don't know what to say here, but it is extremely frustrating when you're trying to do your work on the site, when all of a sudden it hangs.

**Comment by mikejolley** [comment]
This is not a valid bug report, nor is it actionable seeing as there are no details, and you have no narrowed down the problem yourself.

Some general things to try;

- Clear all transients (there are plugins for this)
- Optimise mysql tables via PHPMyAdmin
- Rule out WooCommerce plugins you may or may not be running
- Optimise the server, e.g. using a newer version of PHP and MySQL or increasing resources.
