### ISSUE TITLE
WooCommerce Shortcodes is sending request to cloudfront

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10191]
Since this plugin is on WP.ORG but its looking for changelog in system status http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-shortcodes/changelog.txt

**Comment by claudiosmweb** [comment]
Where?

**Comment by mikejolley** [comment]
The only metric we can use now is author and plugin name so we cannot fix this just yet. Will need https://core.trac.wordpress.org/ticket/32101

**Comment by shivapoudel** [comment]
@claudiosmweb In System Status using Query Monitor -> HTTP Request :)
