### ISSUE TITLE
WooCommerce not putting any javascript in the footer?

### ISSUE THREAD

**Issue by manifestcomms** [woothemes/woocommerce#10198]
Can anyone shed any light on why woocommerce isnt pulling any of its javascript files into the footer?

- the only plugins i've got running are woocommerce and advanced custom fields
- my theme has add_theme_support( 'woocommerce' ); is in my functions.
- i have a woocommerce.php in my theme folder
- I have the copied directory in 'woocommerce' in my theme to override the plugin files but have not edited them.

**Comment by mikejolley** [comment]
The only reason would be missing https://codex.wordpress.org/Function_Reference/wp_footer in the theme itself.

**Comment by manifestcomms** [comment]
wp_footer();  is in the footer.

:(

**Comment by mikejolley** [comment]
Don't reopen new issues (https://github.com/woothemes/woocommerce/issues/10199). You can comment here. Please also be aware this is a bug tracker, not a support area.

WooCommerce scripts only load when needed, and are output with wp_footer. Why don't you try another theme and see if its the same?
