### ISSUE TITLE
Consider not having the option to enter prices including taxes

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#10203]
The setting for specifying prices with tax included creates a lot of problems / confusions around tax / coupon calculations, and with shops that have many tax rates with no all-encompassing rate, it works as tax excluded price anyways.

For example if I have tax included setting, and we say a product costs $30, it can mean a lot of things:

* if there's a 50% tax rate for every zone, the base price is $20, and $10 is on top of it
* if a zone is 25% tax rate, the price ends up being $25 ($20 base rate + $5 tax)
* if however there is no tax rate for all zones, the base price is going to be $30, which means that
* if a zone has 50% tax rate, in that zone the product is going to cost $45

Further a tax included price also affects coupons. A $10 off coupon with a 10% tax rate ends up being a $9.09 + $0.89 tax coupon, which can cause unintended consequences. Again the value of the coupon will depend on the tax rate settings.

From what we can see after having done a few days' worth of testing and trial and error around taxes, price enter settings, discounts, the calculations are actually correct, but there's very little or no documentation on the nuances in these calculations, and customers are being tripped up by it.

Effectively if there is no tax rate for every zone, the prices on the product page work the same as if the setting was "No, I will enter prices exclusive of tax".

Prices can still be displayed including taxes for the countries that require it, it just makes the whole calculation straightforward, as the prices are always going to be void of taxes.

This would also mean a simplification of all calculations when it comes to discounts, taxes.

I understand this is not a straightforward change, but as with the coupon changes in 2.3 (after tax option removed), I think this is doable.

I'd like to open this up for broader discussion.

**Comment by mikejolley** [comment]
Real world usage scenario.

I'm in the UK. I want to charge people in the UK £9.99 for a product. So I enter the cost as £9.99. No confusion.

People outside of the UK don't pay UK taxes, so the 9.99 is reduced for those users. (there is an argument to keep 9.99 price point for everywhere - there is a hidden option for this we're testing).

Now look at the alternative. Needing to enter prices exclude tax. I have to work out what the price 'would' be. So 8.32 or 8.33 depending on rounding (8.325 to get 9.99 after tax which adds extra complexity for these users).

Added to that, if the tax rate changes I would need to manually update all prices if I wanted to keep the same price points. Another ball ache.

US folks don't need to worry about everything above. It's normal to show prices excluding tax in the US. In the UK (and probably other EU countries) this is not common practice. We always show prices including taxes.

**Comment by javorszky** [comment]
That scenario only works if the shop base and the only tax rate specified are in the same country. In every other case the price of the product will behave as if it's entered excluding tax.

**Comment by mikejolley** [comment]
You enter prices including tax based on your base country though. If you're selling from the UK, your base country is UK, and no doubt you define UK taxes.

**Comment by mikejolley** [comment]
Perhaps it would be understood more clearly if the option stated "Yes, I will define prices including UK taxes" or whatever. This option does have uses, and is present in other platforms too.

**Comment by mikejolley** [comment]
@javorszky I guess one other thing we could do; have @kloon dig into the tracker and see how popular the option is. I have a feeling we'd be murdered if we removed the option.

**Comment by mikejolley** [comment]
Hopefully my post cleared this up. Tis a popular option among EU folk so I don't think its feasible to remove at this point.

**Comment by javorszky** [comment]
Yes, it did. Taxes aren't the easiest things to deal with. I think as long as there is good documentation about the nuances as well, it should be all right. Thanks again :)
