### ISSUE TITLE
woocommerce_show_variation_price boolean logic incorrect

### ISSUE THREAD

**Issue by treyrich** [woothemes/woocommerce#10207]
`woocommerce_show_variation_price` filter's value is incorrect I believe. The current boolean logic says:
```php
$variation->get_price() === "" || $this->get_variation_price( 'min' ) !== $this->get_variation_price( 'max' )
```
However it doesn't make sense to me why we would show the price if it is an empty string? Shouldn't the logic be corrected to:
```php
$variation->get_price() !== "" || $this->get_variation_price( 'min' ) !== $this->get_variation_price( 'max' )
```

I'm happy to issue a pull request if desired, but I wanted to confirm there wasn't some reason for doing this.

Also, as a matter of discussion, I'm confused about why the min variation price being equal to the max variation price should affect whether a price is shown for the variation? How will the user know what the price is if the min and max prices are the same?

**Comment by mikejolley** [comment]
We want to show the variation price per-variation only when:

- The variations have different prices
- A variation has no price

Otherwise we just show the price once, under the product title.

Switching to !== "" would mean the variation prices are shown at all times. Thats not intended.
