### ISSUE TITLE
Force message in class-wc-shortcode-my-account.php line 358

### ISSUE THREAD

**Issue by Horrower** [woothemes/woocommerce#10209]
<code>
private static function add_payment_method() {
....
			do_action( 'before_woocommerce_add_payment_method' );

			wc_add_notice( __( 'Add a new payment method.', 'woocommerce' ), 'notice'  );

			wc_print_notices();
.....
}
</code>

What the hell is that? How can I hide that message in my payments form?

**Comment by mikejolley** [comment]
Nice tone there.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/64dfcdbea49afe02f9401e16a2831a1d2f6d557d
