### ISSUE TITLE
Cannot disable product variation's 'manage stock' option

### ISSUE THREAD

**Issue by smarterdigitalltd** [woothemes/woocommerce#10200]
Hi, 

Just an observation on WooCommerce 2.5.1 - tested on 2 completely separate sites.

1) Create new product
2) Set it to 'Variable Product'
3) Add custom attributes and select the 'used for variations' option
4) Variations -> Create variations from attributes
5) Set price on variation + untick 'Manage stock' (the quantity field then hides from view)
6) Variations -> Save changes
7) Open a variation again, 'Manage stock' is now reticked (stock status at this stage is 'In Stock' with a quantity of 0)

If I do this with a Variable Subscription product type, it's the same behaviour, but after saving the product, all variations stock status will turn to 'Out of Stock'.

On 2.5 this doesn't seem to happen.

I can work around this by setting a quantity on the variations.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/a550c77dbadfea6d9766878846d7577f46b96382

**Comment by webgalactica** [comment]
same issue here 
any fixing?
