### ISSUE TITLE
Option to disable password strength meter

### ISSUE THREAD

**Issue by lordgiotto** [woothemes/woocommerce#10201]
It would be great an option under settings/account to disable the new password strength meter: the site owners should decide if they want enable that feature or not, in my opinion.

**Comment by mikejolley** [comment]
I'd rather avoid new options. We are adding notices/feedback to improve the usability of password strength in 2.5.2, and those really hating it can disable with a quick de-enqueue https://nicolamustone.com/2016/01/27/remove-the-password-strength-meter-on-the-checkout-page/

Plus this option is pretty much "let users use dumb passwords" :p I think we should enforce like WordPress does for their own sakes.

**Comment by lordgiotto** [comment]
Ok, i'll keep using the hook to de-enqueue it; I thought that option could be useful for other non-dev users. But I understand your point, thanks for the feedback :)

**Comment by jsciabica** [comment]
I agree.  Some options would be nice.  I'm sure many would like to choose the minimum strength.

For me, it's just not necessary, I don't store any secure material.  Now that 2.5.1 disabled the restriction, it's easy to hide with CSS

.woocommerce-password-strength {
    display: none;
}

**Comment by yeganehaym** [comment]
yeah i'm sure with disable password strength
for me, if a site tell me how to st password , i've never register there and close the tab of browser

**Comment by claudiosmweb** [comment]
@yeganehaym WordPress does it on install and while you create new users...

**Comment by lkraav** [comment]
I have to admit, after seeing a screen recording of what my user had to go through working with the password meter, my conclusion is the password strength meter as of 2.5.x is a bad implementation from a number of aspects. Will be posting a separate issue about this, have to break down the problems clearly visible from the screen recording, and see if I can share non-sensitive parts of the recording.

WP 4.3 introduced the password strength upgrade logic https://make.wordpress.org/core/2015/07/28/passwords-strong-by-default/ Made me wonder why WC felt the need to come up with its own strength logic.

**Comment by mikejolley** [comment]
@lkraav what are you talking about? it's not custom strength logic..

**Comment by lkraav** [comment]
Oh, you're saying `https://github.com/woothemes/woocommerce/blob/release/2.5/assets/js/frontend/password-strength-meter.js` integrates with WP builtin `var strength = wp.passwordStrength.meter( field.val(), wp.passwordStrength.userInputBlacklist() );` correct?

Sorry, I shouldn't have just surface-skimmed the source. :)

OK, so the right thing to do is to talk to WP core about the above, correct?

**Comment by rtemery** [comment]
The password strength requirements are definitely too high -- a newly registered user of WooCommerce should be allowed to use a password like: Testing_1!  (as it includes an uppercase, lowercase, number and special character.  Yet, this password is rejected.  Even Chase, Wells Fargo, and Citibank, Authorize-net all accept this. 

Is this a WordPress Core issue or WooCommerce?

**Comment by mikejolley** [comment]
@rtemery We piggy back on WordPress core's implementation.

**Comment by muzicmethod** [comment]
We are having the same complaints from our customers. I have to agree with rtemery, in fact, to register for this very site all I needed was "Use at least one lowercase letter, one numeral, and seven characters." and that was simple and easy. What constitutes a strong password is relative, obviously adding special characters and upper lowercase will be helpful but when it's too strong, it renders the site useless as people become frustrated and end up calling for tech help.  Is there a current work-around? Thanks!

**Comment by rtemery** [comment]
@muzicmethod I completely agree, and have been handling customer complaints on this even since. There needs to be a better balance between security and usability. @mikejolley do you have any influence with WordPress core on this by chance? Would love to know your thoughts.

**Comment by muzicmethod** [comment]
@rtemery I found a piece of code online to allow weaker passwords for woocommerce that I've turned  into a plug-in. It seems to be working, feel free to use it and try it out. I had to upload this as a text file instead of php so change the extension on it to be php instead of txt. Create a folder under plug-ins with this name nc-woo-commerce-pw  and put the php file in there. Go into wordpress admin panel under plugins and activate.   
[nc-woo-commerce-pw.txt](https://github.com/woocommerce/woocommerce/files/688273/nc-woo-commerce-pw.txt)

It would be nice if this functionality was simply built into the options panel of Woo Commerce, seeing it's only a couple lines of code. Please NOTE that this code is in fact set at WEAK for password. You can  change it to MEDIUM or STRONG by changing the number in the text file and re-saving it as a php file. A weaker password setting happens to work for our particular business.

**Comment by mikejolley** [comment]
@rtemery no and I would not be in favour of weakening passwords tbh. 

Adding options to 'enable weak passwords' does not sound like the type of example eCommerce software should be setting. 

The password meter gives clues and shows strength, and additionally tools are getting better - I know safari for instance can generate a strong password for you automatically. If you feel the meter is not balanced, you should take it up with WordPress trac ideally.

**Comment by rtemery** [comment]
@mikejolley I understand your perspective for sure. However, I think we are talking semantics (and not security itself). It's really not a secure vs insecure issue -- rather it's finding the balance between usability and security. 

If very highest level of security is the genuine consideration of WordPress, then they should require 2-factor authentication. Any created manually created password can be hacked after all, which is why usability (should also) be a consideration for eCommerce.  And when enough businesses are affected with customer complaints, then you'll see a movement towards end-to-end solutions like BigCommerce (rather than Woocommerce).

**Comment by rtemery** [comment]
@muzicmethod -- thank you, I'll test that out.

**Comment by Shavelkins** [comment]
Hello everyone! Does anybody have an idea on how to COMPLETELY REMOVE the WOOCOMMERCE PASSWORD STRENGTH HINT TEXT that sits right after the password field? Or change it to my own one? I've been digging the files and folders for 2 days and still no result. I cannot find where this text is located! Thanx in advance!

**Comment by nam1962** [comment]
I also have this hint text issue.
Tried to add css : 
`.woocommerce-password-strength {
display: none;
}
`
But text stays there...

**Comment by jsciabica** [comment]
@nam1962 please provide a link to your site

**Comment by nam1962** [comment]
Thank you for your reply, we're really concerned by our clients UX.
https://goudronblanc.com

**Comment by jsciabica** [comment]
@nam1962 I can see that you are hiding the strength meter with the CSS you added.  There is an additional section for "Password Hint".  Is that what you want to hide?

If so, you'll need to use:
.woocommerce-password-hint, .woocommerce-password-strength {
display: none;
}

**Comment by nam1962** [comment]
Yess ! That's it ! Thank you.
I know that strong password is better, but here, enforcement and hint where bad & confusing for the customers UX.
I obviously lost some prospects along the way. I agree with @rtemery on this issue ;)

**Comment by Shavelkins** [comment]
**jsciabica**, thank you so much!

**Comment by rtemery** [comment]
@muzicmethod I've successfully implemented your solution with 0 as the setting. Attempting 1 and 2 strength settings didn't work for me. Just thought I'd pass this along to other users. As far the password hint label, I like it as-is for disclosure/reminder. But I'm happy to remove the friction that previously existed for password selection. Thanks for the help!

**Comment by txlife** [comment]
Don't who implemented this dumb meter. But can't you see how this meter is making registration process frustrating?! Worst customer experience comes from this meter.

Do something good for human, stop using this sort of programmer's thinking to judge users.

**Comment by ApplicationError** [comment]
I tend to agree. The password strength is set too high, it's really frustrating when setting a new password. This feels like a "something gone wrong" feature. I'll try to disable it with the snippet, but it would be much nicer if we could set the desired strength somewhere.

**Comment by mikejolley** [comment]
If you don't want to kill conversions at all, check the auto-password option:

![2017-04-03 at 12 34](https://cloud.githubusercontent.com/assets/90977/24607481/f17d112e-1869-11e7-830b-5053729dd611.png)

This conversation is not really going anywhere. There are various options, snippets, and solutions available. 

We'll review again when we redo the checkout flow from scratch.
