### ISSUE TITLE
Grouped products do not calculate the sale price for child products in product lists

### ISSUE THREAD

**Issue by forsvunnet** [woothemes/woocommerce#10217]
In the `get_price_html` method the price for child products are compared using the original price, not the sales price. https://github.com/woothemes/woocommerce/blob/f1920cb882f2c858b7963bef269f8aa44d372bf7/includes/class-wc-product-grouped.php#L137
```
foreach ( $this->get_children() as $child_id )
			$child_prices[] = get_post_meta( $child_id, '_price', true );
```

It should ideally collect the prices using the `get_price` method of the child.

```
foreach ( $this->get_children() as $child_id ) {
  $child = wc_get_product( $child_id );
  $child_prices[] = $child->get_price();
}
```

**Comment by mikejolley** [comment]
Incorrect - _price is the active price (could be sale price). _regular_price is the non sale price.

**Comment by forsvunnet** [comment]
Ah, correct. But it ignores filters run in the get_price method

**Comment by mikejolley** [comment]
Right. It would be significantly slower to load each sub-product though, and I'm not sure we want 'altered' prices here?

**Comment by forsvunnet** [comment]
I'm using the `woocommerce_get_price` and `woocommerce_get_sale_price` to apply some custom discount logic to products for a client that has a very specific type of discounts pulled in from an ERP system. Not showing the correct price in the list views would be a huge issue for us.

Do you have suggestions for an alternative method for altering the price in the list view other than doing low-level hacking in a `get_post_meta` filter hook?

**Comment by forsvunnet** [comment]
It would perhaps be worth investigating how [dynamic pricing](https://www.woothemes.com/products/dynamic-pricing/) and [bundle products](https://www.woothemes.com/products/product-bundles/) work around this issue?
