### ISSUE TITLE
Manage Inventory on Variable product always checked

### ISSUE THREAD

**Issue by littlepackage** [woothemes/woocommerce#10219]
If global option "Manage Stock" is checked, variation products will show as Manage Inventory = checked whether wanted or not. Irregardless of whether "Enable stock management at product level" is on or off for the parent, settings do not save. The only way to save the option unchecked is by database command, and then the box still shows checked.

woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php

**Comment by mikejolley** [comment]
Fixed in master, 2.5.2 monday.
