### ISSUE TITLE
Add function_exists('wc_product_post_class') to allow themes to override the function?

### ISSUE THREAD

**Issue by theshaune** [woothemes/woocommerce#10211]
I'm not sure if there is a reason that `wc_product_post_class()` isn't wrapped in a `function_exists()` but I do modify it slightly for different classes. 
_Is this something that could be added?_

file: **includes//wc-template-functions.php**

```php
if ( ! function_exists( 'wc_product_post_class' ) ) {
  function wc_product_post_class( $classes, $class = '', $post_id = '' ) { ...
```

Thanks

**Comment by mikejolley** [comment]
No need - use the post_class filter.

**Comment by rezehnde** [comment]
Or use woocommerce_post_class filter:

```
function e2u_woocommerce_post_class($classes, $product)
{
    $classes[] = 'row';
    return $classes;
}
add_filter('woocommerce_post_class', 'e2u_woocommerce_post_class', 10, 2);
```

**Comment by wpexplorer** [comment]
The problem with the "woocommerce_post_class" filter is that it get's added for entries and as a wrapper around the single product. So lets say you wanted to add utility classes for columns to the entries only, it's currently not possible with woocommerce_post_class as there is no way to differentiate an entry from the singular product - both entries and single product return "' for wc_get_loop_prop( 'name' ).

Perhaps entries on the main shop should have context such as wc_set_loop_prop( 'archive' ) and the single product should have a context as well wc_set_loop_prop( 'singular' ) so it's easy to differentiate the two?

- AJ
