### ISSUE TITLE
lost password link in email not working

### ISSUE THREAD

**Issue by bharat12312** [woothemes/woocommerce#10212]
Every time I use lost password option, I get an email containing the link to reset the password for user, when I click on link it take me to same page to enter my username.
it just don't reset the password.

**Comment by bharat12312** [comment]
I tried several solution on wordpress post and woo but dosent seems to work.

**Comment by bharat12312** [comment]
found the solution, disabled all plugins and enabled them all one by one, and none of them seems to be an issue. not sure about this behavior as I am not an expert, but eventually issue is resolved.

**Comment by bharat12312** [comment]
i ran in to this issue again today, this time disabling all plugins did not work....when I click on reset password link in email, it redirects me to lost password page and ask me to put my user name to send reset link again and again. it never prompt for new password.

Experts please help me as my users are affected badly and complaining.

**Comment by mikejolley** [comment]
Check with default WP theme.. This works for me, so I don't see how it can be WC core.

**Comment by mikejolley** [comment]
You can comment back if with the default theme the issue occurs, however, I've just retested and found no problem.
