### ISSUE TITLE
Make use of WP API scaffolding

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10210]
- Work out how to support authentication
- v4 endpoints
- Convert/Refactor API code over to register_rest_route etc
- Find a way to support auth endpoint since the flow is IMO superior

@claudiosmweb notes to add?

**Comment by thenbrent** [comment]
> Find a way to support auth endpoint since the flow is IMO superior

Agreed.

I'd love to help out with this. @claudiosmweb @mikejolley let me know what I can do. :smile:

**Comment by mikejolley** [comment]
Closing in favour of #10435
