### ISSUE TITLE
Invalid argument supplied for foreach() in /wp-content/plugins/woocommerce/includes/class-wc-countries.php on line 165

### ISSUE THREAD

**Issue by indietravel** [woothemes/woocommerce#10220]
With debug on, I'm seeing `Invalid argument supplied for foreach() in /wp-content/plugins/woocommerce/includes/class-wc-countries.php on line 165` on every page with a country dropdown box, e.g. `/wp-admin/admin.php?page=wc-settings`

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/8d0591d7c6725d6c762c3bb34c7f4d26b54275ba
