### ISSUE TITLE
Stock Availability

### ISSUE THREAD

**Issue by webadmin** [woothemes/woocommerce#10227]
WooCommerce Products Management is not allowing products to be changed from "Out of Stock" to "In Stock". I've attempted multiple times via edit and quick edit. I select in stock, then click update. It goes through the processing then once complete it has not changed from "out of stock" to "in stock". 

How can this be resolved?

**Comment by tomedme** [comment]
I'm seeing problems with stock management on variable products. Our product variations do not require us to manage the stock - yet it is not currently possible to uncheck that box for the individual variations.

If I save the variations, the "Manage stock" checkbox is checked automatically after saving and the products are "In stock". If I save the product after updating other data, the variations are set to "Out of stock".

Ideally the checkbox for "Manage stock" should be respected in the variations.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/a550c77dbadfea6d9766878846d7577f46b96382
