### ISSUE TITLE
Images in dummy-data.xml import file are all 404

### ISSUE THREAD

**Issue by slobodan** [woothemes/woocommerce#10229]
http://demo2.woothemes.com/woocommerce/files/2013/06/T_1_back.jpg
http://demo2.woothemes.com/woocommerce/files/2013/06/T_1_front.jpg

etc.

**Comment by lholdsworth** [comment]
For now if you need to be able to import the data, do a find/replace for:

http://demo2.woothemes.com/woocommerce/files/2013/06/

to

http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/

...in the xml file, and it should work
