### ISSUE TITLE
Product Page not loading properly

### ISSUE THREAD

**Issue by adzuk** [woothemes/woocommerce#10225]
I recently updated the woocommerce template files, which has now caused the product page on my website to not load properly.

Initially 3 products per row were displayed on my website. But now since the woocommerce template has been updated only one item per row is dispayed along with the product view which app appears next to it.

Secondly, the sale items listed on the product page no longer have the sale icon above the sale item.

Pls see attached

**Comment by adzuk** [comment]
/Users/Adeola/Desktop/Picture 8.png
/Users/Adeola/Desktop/Picture 7.png

**Comment by mikejolley** [comment]
No attachment, or link. Core shows sale badges correctly with the default theme, so I don't think it's core.

Check your CSS/the theme supports 2.5 styles.
