### ISSUE TITLE
Inconsistent Breadcrumb on Single Product

### ISSUE THREAD

**Issue by addedlovely** [woothemes/woocommerce#10224]
When a product exists in multiple categories, what defines which parent category is shown? Changing the order of categories in the backend doesn't seem to make a difference. I can see the terms are ordered by 'Parent' but not sure how that logic is working?

As an enhancement would if possible to show multiple breadcrumbs, showing each route to the product? From an end user point of view we are experiencing issues with users feeling lost, after navigating from one category to the product, then being shown a breadcrumb that shows the other product's categories, which doesn't correlate with their journey. 

Checking the breadcrumb from referral URL and building the correct crumb would be awesome, but one assumes not caching friendly.

**Comment by mikejolley** [comment]
Tracking a user's path through a site would be slow + cumbersome, and of little value.  The first category found (I think its the parent category with the lowest ID number) is used in the crumb.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-breadcrumb.php#L147-L148

it's filterable so feel free to customise it.

**Comment by jorisw** [comment]
I for one disagree that it would be slow or cumbersome, for if you just snoop the referer URL once when viewing a single product, you can take an educated guess at which of the several possible paths should form the breadcrumb.

For others looking for a solution, see:

http://www.cryoutcreations.eu/forums/t/wrong-breadcrumbs-displayed

and

http://pastebin.com/0PtSbjFT

**Comment by mikejolley** [comment]
@jorisw snooping the referrer only gets you one level higher. You still don't know the full path the user took, and what's more, referring URLs won't be consistent across sites. Everyone has different structures.

> it's filterable so feel free to customise it.
