### ISSUE TITLE
Variable Product attribute values not pulling through to product admin page after upgrade to 2.5.1

### ISSUE THREAD

**Issue by bluubanana** [woothemes/woocommerce#10226]
I have setup the attribute as before, but when setting up the product its not pulling the list of values.  I have checked its set to select list in the attribute.

Also issues with stock levels etc

Is there a patch on the way?

**Comment by mikejolley** [comment]
No known issues with attributes. Manage stock is being patched in 2.5.2

**Comment by bluubanana** [comment]
Thanks for fast response.

Do you have a date?

Thanks

**Comment by mikejolley** [comment]
Today.
