### ISSUE TITLE
Layered Nav missing for attributes (partial and total)

### ISSUE THREAD

**Issue by BuggeringHell** [woothemes/woocommerce#10234]
I have a category with 13,000 products, each product with 3 sets of attributes. Not all of these attributes show on the layered nav widget on of the category page (one of the widgets are not showing at all) when the attributes section of the wp-admin shows the contrary. Is this a cache issue?

**Comment by mikejolley** [comment]
The products need to be available within said attribute or it won't show up. In stock and visible.

**Comment by BuggeringHell** [comment]
These  products were imported using WP All Import, and have the stock status and visibility statically set. Manually changing the URL to filter out attributes also displays the correct amount of products but the widget shows 0 count, disappearing if you navigate away from the filter.

It is worth mentioning that WP All Import was used to add and update these products, with '**Increase speed by disabling do_action calls in wp_insert_post during import.**' being enabled to help with import/update times. I presume this isn't calling the necessary functions to update transients? I hoped 'Recount terms' in the tool page would fix it, but obviously not.

Currently running a new import with the setting disabled to see if it resolves the issue.

**Comment by mikejolley** [comment]
Saving a product manually will clear catalog transients which are used here, however, the term count ones are only updated at specific times.

https://github.com/woothemes/woocommerce/blob/a4d982b1b9ada58f6733ea1b4ae500c1333e80cd/includes/wc-term-functions.php#L648
