### ISSUE TITLE
billing_city placeholder is missing in Version 2.5.1

### ISSUE THREAD

**Issue by nikzanta** [woothemes/woocommerce#10230]
Hello there,

The billing_city placeholder is missing from checkout page in Version 2.5.1.

Thank you!
Nikolas

**Comment by mikejolley** [comment]
These are no longer included since they just repeat the label.

**Comment by nikzanta** [comment]
Please, allow me to note that this issue is not resolved for 2 reasons:

1. Some themes only use the placeholder and not the label. An example can be seen here, if you add any product in the cart and go to checkout page: http://www.philanthropy.gr/eshop/checkout/
Consequently, the placeholder seems necessary.
2. All fields in the checkout do have a placeholder, for example: placeholder="First name", and only one placeholder is missing, the billing_city placeholder. In the above mentioned example, the 10 fields have no consistency, since the 9 fields do have a placeholder and only one field does not have a placeholder.

Thank you again,
Nikolas

**Comment by mikejolley** [comment]
Actually, only address_1 has a placeholder by default in 2.5. Placeholders were inconsistent. If a theme hides labels, it can also set placeholders. Showing both is counter intuitive by default where labels are shown.
