### ISSUE TITLE
[REST API] Disappearing categories

### ISSUE THREAD

**Issue by kallewallin** [woothemes/woocommerce#10238]
The following bug has been found in 2.4.x and 2.5.x but not in 2.3.5

1. When creating products using the REST API, categories is not registered

Category "Testcategory" exist in woo.

POST [path]/products

`{"product":{"sku":"test","categories":["Testcategory"], ... }}`

Response:

`{"product":{"sku":"test","categories":[], ... }}`

2. When updating products using the REST API and providing categories, they disappear 

The result below is the same no mater if  the product have "Testcategory" or not. So if it doesn't have it before then it will still don't have it after the update and if the product have the category before then it is removed

Product "test" before update:

`{"product":{"sku":"test","categories":["Testcategory"], ... }}`

PUT [path]/products/[ID]

`{"product":{"sku":"test","categories":["Testcategory"], ... }}`

Response:

`{"product":{"sku":"test","categories":[], ... }}`

**Comment by claudiosmweb** [comment]
Because since 2.4 you need to submit the category ID.

http://woothemes.github.io/woocommerce-rest-api-docs/#products

![screenshot from 2016-02-02 14-28-18](https://cloud.githubusercontent.com/assets/1264099/12756078/3a4de870-c9b9-11e5-86bb-81eaa0d4d90c.png)

**Comment by kallewallin** [comment]
Ok, thanks.

Any reason why the id is not included in "categories" on the product? would have been convinient:D

Also, it's a little dangerous when the default behaviour is to clear categories when using the previous functionality. Maybe an error when invalid category id's are sent in instead of clearing existing categories
