### ISSUE TITLE
Breadcrumbs term value empty in a custom search

### ISSUE THREAD

**Issue by pacocastillo** [woothemes/woocommerce#10239]
When you search in WC search form, the breadcrumbs don't show the value of `$_GET['s']`

Changing the function `search_trail()` in breadcrumb class would solved it:

`get_search_query()` to
`(!get_search_query() ? sanitize_text_field($_GET['s']) : get_search_query())`

**Comment by claudiosmweb** [comment]
`get_search_query()` is enough: https://developer.wordpress.org/reference/functions/get_search_query/
