### ISSUE TITLE
Account creation at checkout does not fully vailidate passwords.

### ISSUE THREAD

**Issue by gthayer** [woothemes/woocommerce#10233]
When creating an account on the /my-account/ page, users are unable to create accounts with passwords weaker than medium.

However, when going through the checkout and creating an account, even though the validator appears the system still accepts weak passwords including single character passwords.

**Comment by DavidAnderson684** [comment]
Is that a bug, or a feature?

Do shops want to lose customers at the checkout because Big Brother WooCommerce dislike their password? Whereas, if they're not buying anything. then defaulting to requiring a reasonable password isn't so costly an action.

**Comment by gthayer** [comment]
From our standpoint, we'd rather see users create secure accounts. Perhaps the greying out of the submit button wouldn't be best idea on the checkout page due to lack of info, however a validation notice upon submit would be explanatory enough.

**Comment by DavidAnderson684** [comment]
Personally, I lose sales from people who don't even spot the validation notice telling them that their credit card number was entered wrongly... (some of them do manage to raise support requests a few days later, asking them where their product is, which is how I get to know about that)...

**Comment by mikejolley** [comment]
We did this to prevent killing people's conversions. There were lots of reports of customers not noticing the pw requirement. Therefore we made it more of a guide - it tells you strength and gives you advice. 

Note that with either, it's just JavaScript. Easy to work around if you know how to open console.
