### ISSUE TITLE
missing "new customer order" email to admin 

### ISSUE THREAD

**Issue by chilternpc** [woothemes/woocommerce#10236]
I have have had 3 orders in.  I have received 3 emails from PayPal saying I recieved payment, but only 2 "new customer order" emails from my site.
Check the Orders I have 3 orders. and everything looks good.  just the missing email for the last order.

**Comment by mikejolley** [comment]
Ensure all orders are 'processing', and check spam. Emails can be marked as spam/delayed. Use a logging plugin if you're worried they are not sending.

**Comment by chilternpc** [comment]
thanks for that - yes _ having worked in website development for over 15 years  I have checked the  status of all orders (all processing)  and yes I have checked the spam folder.
I will monitor/log the orders and let you know if it happened again.

**Comment by mikejolley** [comment]
If thats the case you should know the original issue didn't contain enough information anyway :) No system status report, no mention of versions, no mention of what you're done to find the problem so far. Please be more detailed if you log future bugs.
