### ISSUE TITLE
The coupons at wooComerce plugin are not working

### ISSUE THREAD

**Issue by Alexgambit1113** [woothemes/woocommerce#10247]
The coupons at WooComerce plugin are not working.

The coupons at WooComers are not working, i have an internet store on wordpress, and if I try to add an enter the coupon code it does not work. Could you please help me solve this issue.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Without more details + system reports + **instructions on how to reproduce the issue** we cannot help. Core has no problem with coupons, they work fine and no one else has reported problems. That means you're either using an invalid coupon code, or you have a plugin breaking the functionality. Rule that out by deactivating things.

Please also note Github is not for general support queries.
