### ISSUE TITLE
White page and fragments error

### ISSUE THREAD

**Issue by tomob7** [woothemes/woocommerce#10240]
Hi,

We have a website built on woocommerce and we have customers reporting that they are getting a white page with just the below text, can you think what this might be?

{"fragments":{"div.widget_shopping_cart_content":"
\n\n
\n\n\t\n\t\t
No products in the basket.<\/li>\n\n\t\n<\/ul>\n\n\n<\/div>"},"cart_hash":""}

**Comment by mikejolley** [comment]
As you've provided limited information, and this is also not a support area, I am closing this issue. https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

I'd suggest you first reproduce the problem yourself, then rule out plugin and theme conflicts. This has not been reported by anyone else so it's likely something unique to your own setup. I cannot think of anything off the top of my head what would cause this, as what you've pasted is the response from an ajax request.

**Comment by tomob7** [comment]
Oh...in that contributing page it mentions reporting issues...

What kind of information might you need?

When I do a google search I can see other sites have been effected by this because it is appearing in their SEO

https://www.google.co.uk/search?q=%22fragments%22:{&ie=utf-8&oe=utf-8&gws_rd=cr&ei=bbmwVpDhDsj8Ut7xv8gI#q={%22fragments%22:{%22div.widget_shopping_cart_content%22:%22

**Comment by mikejolley** [comment]
System status report etc, but you should do what I said first. Reproduce + rule out conflicts.
