### ISSUE TITLE
Cannot read property 'model' of undefined in meta-boxes-product-variation.min.js?ver=2.3.11:359

### ISSUE THREAD

**Issue by megasqrt** [woothemes/woocommerce#10249]
![123](https://cloud.githubusercontent.com/assets/5495527/12768667/639c7764-ca22-11e5-8a52-0a27ccef091c.png)
flies this error and js in the admin panel, stops working. only helps roll back the database stay on the option on or off woocommerce

**Comment by megasqrt** [comment]
![123](https://cloud.githubusercontent.com/assets/5495527/12847376/ea866818-cc23-11e5-8446-c11bc0f8dd57.png)
still not working

### WordPress Environment ###

Home URL: http://109.120.156.16
Site URL: http://109.120.156.16
WC Version: 2.5.2
Log Directory Writable: ✔  /home/kan/local/html/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: ru_RU

### Server Environment ###

Server Info: nginx/1.6.2
PHP Version: 5.6.14-0+deb8u1
PHP Post Max Size: 25 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
SUHOSIN Installed: –
MySQL Version: 5.5.46
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (13) ###

Contact Form 7: от Takayuki Miyoshi – 4.3.1
IG PageBuilder PT MOD: от InnoGears Team  – 1.0
Cyr to Lat enhanced: от Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Debug Bar: от wordpressdotorg – 0.8.2
jQuery Vertical Accordion Menu: от Lee Chestnutt – 3.1.2
Meteor Slides: от Josh Leuze – 1.5.6
Sber: от kan – 0.0.1
Revolution Slider: от ThemePunch – 4.6.93
Search By SKU - for Woocommerce: от Matthew Lawson – 0.6.1
.Suppamenu Pro: от Sabri Taieb – 2.5.9
WooCommerce: от WooThemes – 2.5.2
WP-Mail-SMTP: от Callum Macdonald – 0.9.5
WP Super Cache: от Automattic – 1.4.7

### Settings ###

Force SSL: –
Currency: RUB (₽)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Ссылка магазина: #4 - /shop/
Корзина: #5 - /cart/
Оформление заказа: #6 - /checkout/
Мой аккаунт: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
simple_kan (simple_kan)
variable (variable)


### Theme ###

Name: HandyStore Theme
Version: 2.1 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ✕ – Если вы модифицируете элементы WooCommerce в теме WordPress
которую вы не разрабатывали самостоятельно
рекомендуется использовать дочернюю тему. Читайте: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/archive-product.php
handystore/woocommerce/cart/cart-shipping.php версия 2.3.0 устарела. Версия ядра 2.5.0
handystore/woocommerce/cart/cart.php
handystore/woocommerce/cart/cross-sells.php
handystore/woocommerce/cart/proceed-to-checkout-button.php
handystore/woocommerce/cart/shipping-calculator.php
handystore/woocommerce/checkout/form-billing.php
handystore/woocommerce/checkout/form-checkout.php
handystore/woocommerce/checkout/form-login.php
handystore/woocommerce/checkout/form-pay.php версия 2.4.7 устарела. Версия ядра 2.5.0
handystore/woocommerce/checkout/form-shipping.php
handystore/woocommerce/checkout/payment-method.php
handystore/woocommerce/checkout/payment.php версия 2.3.0 устарела. Версия ядра 2.5.0
handystore/woocommerce/checkout/review-order.php
handystore/woocommerce/checkout/thankyou.php
handystore/woocommerce/content-product.php версия 2.4.0 устарела. Версия ядра 2.5.0
handystore/woocommerce/content-product_cat.php версия 2.4.0 устарела. Версия ядра 2.5.2
handystore/woocommerce/content-widget-product.php версия - устарела. Версия ядра 2.5.0
handystore/woocommerce/global/form-login.php
handystore/woocommerce/loop/add-to-cart.php версия 2.1.0 устарела. Версия ядра 2.5.0
handystore/woocommerce/loop/loop-start.php
handystore/woocommerce/loop/pagination.php
handystore/woocommerce/myaccount/form-login.php
handystore/woocommerce/single-product/meta.php
handystore/woocommerce/single-product/product-image.php
handystore/woocommerce/single-product/rating.php
handystore/woocommerce/single-product/related.php
handystore/woocommerce/single-product/tabs/additional-information.php
handystore/woocommerce/single-product/tabs/description.php
handystore/woocommerce/single-product/tabs/tabs.php
handystore/woocommerce/single-product/title.php
handystore/woocommerce/single-product.php

**Comment by mikejolley** [comment]
I'd suggest you look into plugin conflicts, because that wp.model is a global WordPress sets on post screens.
