### ISSUE TITLE
Stock not re-adding items from Cancelled Orders

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#10246]
Hey guys,

I tested the following scenario for items paid by Cheque (put "On Hold") and Cash on Delivery ("Processing") with the same results:

1. Product A is added to the cart, and paid for by Cheque/COD.
2. I then cancelled the On Hold/Processing order through the Admin section.
3. Stock was not re-added to the pool, so where I started with 2 in stock, I now only have 1 (though it should be 2).

![http://cld.wthms.co/14uEB/1qq2X5o8](http://cld.wthms.co/14uEB/1qq2X5o8+) 

I know from [here](https://github.com/woothemes/woocommerce/issues/10189) and general experience item stock _should_ be restored, so could this be a bug introduced in the latest release?

-----

Related ticket: https://woothemes.zendesk.com/agent/tickets/376922

**Comment by claudiosmweb** [comment]
Not caused by the payment gateway... but since you are putting it as canceled (manual action), you should update the stock too.

**Comment by DanielSantoro** [comment]
@claudiosmweb In the past I thought if orders were cancelled, the stock returned to what it was before? I can see this being problematic (especially if you have a composite product with multiple SKUs), but if it's intended to be manually updating the stock then I can let the customer know.

**Comment by claudiosmweb** [comment]
> In the past I thought if orders were cancelled, the stock returned to what it was before?

Nop, never happened... That's why @kloon created this plugin: https://wordpress.org/plugins/woocommerce-auto-restore-stock/
