### ISSUE TITLE
Order emails doesn't sends on multilingual site

### ISSUE THREAD

**Issue by dmitryvasilev** [woothemes/woocommerce#10243]
Email notifications stop working if "yes" string is translated. 
It happens because "enabled" option is automatically translated too, but Woopress expects exactly "yes" string to define if email is enabled.

**Comment by mikejolley** [comment]
'yes' is not translated. It's used internally only.

**Comment by dmitryvasilev** [comment]
Mike, thank you for the fix.
But the problem laid deeper (in my case): inside WPML plugin and icl_st_translate_admin_string hook, which translates all strings, including plugin configuration options. It's not a problem of Woocommerce, but I think I should warn about this behaviour.
