### ISSUE TITLE
Strip add-to-cart=xxx from URL links after adding an item

### ISSUE THREAD

**Issue by MattyLB** [woothemes/woocommerce#10255]
I understand that issue #10231 is supposed to remove the ?add-to-cart=xxx from pagination in WC v2.5.2, however, we still have this issue in our URLs after adding a product to the cart after the update - and it causes the item to be added again if: 1) the page is refreshed, 2) the browser's "back" button is used after moving away from a page where a product was added, or - more importantly - 3) the page is shared after adding an item to the cart. The last scenario basically force-adds the item to an unsuspecting person's cart when they click a shared link - and can give the impression that the store owner is engaging in deceptive practices.

This never happened prior to 2.5 release and I hope this can be addressed soon. If I'm overlooking a new setting that needs to be disabled in WC settings, please point me to it.

Thank you!

![add-to-cart-url-query-still-happens-after-wc-2 5 2-update_b](https://cloud.githubusercontent.com/assets/7232000/12781631/32ab40ae-ca3b-11e5-8952-6f11f3d32e13.jpg)

**Comment by mikejolley** [comment]
No plans on doing this; it would cause significant slow down for the user since you'd need to post the add-to-cart form, perform the add to cart, then redirect back. Thats essentially 2 page loads instead of 1, for something trivial IMO. 

I don't see how you could 'fall for' 3 - it's clearly in the URL so shouldn't be a surprise.

**Comment by MattyLB** [comment]
@mikejolley - with all due respect, I'm not talking about redoing the "process" of how add-to-cart works:
> you'd need to post the add-to-cart form, perform the add to cart, then redirect back.

my concern is simply this: Why is ?add-to-cart=xxx all of sudden showing up in our URLs when this has obvious adverse user experience impacts and it was never an issue prior to 2.5 release of WC? More simply, can we have the option to remove it if we feel like it's causing our users any issues? This is something I did not sign up for when I "chose" to go with WooCommerce and it is not acceptable IMO.

Thanks.

**Comment by mikejolley** [comment]
@MattyLB In past versions it redirected back to the URL without the querystring. 2 page loads = slower. A slower page is more annoying for customers than a querystring.

Go ahead and slow down your site if you want, using this filter: 

https://github.com/woothemes/woocommerce/blob/6050b204fc7774f46bbec2b9ced317a0b60fb641/includes/class-wc-form-handler.php#L630

And this function:

https://codex.wordpress.org/Function_Reference/wp_get_referer

**Comment by MattyLB** [comment]
One last point in regards to:
> I don't see how you could 'fall for' 3 - it's clearly in the URL so shouldn't be a surprise.

Several sharing tools, especially twitter, use shortened URLs such as bit.ly, etc. This clearly enables a surprise and could confuse users.

I understand the 2 page load slow-down situation - what I'm asking is why it simply can't be "hidden" from the url without impacting the overall add-to-cart process.

Thanks for the information, btw. :)

**Comment by mikejolley** [comment]
Do your buttons have the class 'ajax_add_to_cart'? Maybe you're missing that.

**Comment by mikejolley** [comment]
@MattyLB if so check your version of https://github.com/woothemes/woocommerce/blob/master/templates/loop/add-to-cart.php

**Comment by MattyLB** [comment]
After checking with theme.co (X theme), they've apparently lost the
ajax_add_to_cart functionality on these buttons after the WC 2.5 release
and they're working on it. It seems this is causing the issue and I
apologize for opening this ticket without verifying that first.

Great work on all of your WC improvements.

Matt
