### ISSUE TITLE
woocommerce body class always?

### ISSUE THREAD

**Issue by montalvomiguelo** [woothemes/woocommerce#10250]
Last update WooCommerce 2.5.2 has always the class `woocommerce` in the body even you are not viewing a WooCommerce template... _front-page, page, single, search, 404, etc_ templates have the `woocommerce` body class and they are not WooCommerce templates 

````
<body class="error404 woocommerce">
```

**Comment by reigelgallarde** [comment]
I'm using Version 2.5.2 and mine is not like that... only on woocommerce templates has `woocommerce` in the body class.

**Comment by montalvomiguelo** [comment]
Yes the issue in my instance is produced when Sensei 1.9 Just updated is active .... If I disable Sensei then WooCommerce puts the woocommerce body class properly

**Comment by reigelgallarde** [comment]
then it's a sensei issue... not WooCommerce...

by the way, I can see this in their code... it adds `woocommerce` to all pages as what you had described.

````
// @since 1.9.0
// add  woocommerce class to the the no permission body class to ensure WooCommerce elements are styled
add_filter( 'body_class', array( 'Sensei_WC', 'add_woocommerce_body_class' ), 20, 1);
````

I think this should not be an issue... it's just for formatting styles... maybe we need to ask @dwainm  :)

**Comment by dwainm** [comment]
@montalvomiguelo @reigelgallarde This is a Sensei issue yes. The body class adding should do some more checks before adding woocommerce. I've logged an issue here: https://github.com/woothemes/sensei/issues/1271
