### ISSUE TITLE
Password strength meter - Custom position

### ISSUE THREAD

**Issue by Ninos** [woothemes/woocommerce#10257]
Hey there,
we want to place the strength meter after the parent of the field, because we're using the bootstrap input-group styling:
http://getbootstrap.com/components/#input-groups-basic

Is it possible to add a filter or hook to following function, so we can define a custom placement?:
https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/password-strength-meter.js#L50

**Comment by claudiosmweb** [comment]
Use CSS.

**Comment by Ninos** [comment]
I'm not as stupid as I'm looking :D It's not possible, just with position absolute, but then I still don't know the height of the strength-meter-boxes for adding margin to the bottom (spacement for absolute boxes, otherwise submit button would be over the boxes)...

So with CSS it would be a very dirty CSS-JS hack. Here's a screenshot of my current field:
![screenshot-field-strength-meter](https://cloud.githubusercontent.com/assets/1012403/12785518/2e7a6c38-ca8d-11e5-924f-8f3b74836c02.png)

**Comment by claudiosmweb** [comment]
> So with CSS it would be a very dirty CSS-JS hack

Not true, it depends on your talent with CSS and JS.

**Comment by claudiosmweb** [comment]
@Ninos this should be enough ^

**Comment by Ninos** [comment]
Huh, I hope you know that the width and height of every input-group element is variable and here I need to work with position: absolute..

Thanks did not wanted anything more :D

**Comment by Ninos** [comment]
BTW: as small enhancement you could also add the wrapper and field to the trigger, e.g.
`$( document.body ).trigger( 'wc-password-strength-added', [ wrapper, field ] );`

:-)

**Comment by Ninos** [comment]
If others have the same problem, here's a small code snippet:
```
jQuery( 'body' ).on( 'wc-password-strength-added', function () {
	var meter = jQuery( this ).find( '.woocommerce-password-strength' );

	meter.parent().after( meter.clone() );
	meter.remove();
} );
```
