### ISSUE TITLE
Order with non-catalogue products auto completing after payment

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#10252]
When an order with non-catalogue products (i.e. `$this->get_product_from_item( $item ) === false`) is set to payment_complete in WC2.4.7+ (including 2.5), [it skips processing]($this->get_product_from_item( $item )).
In WC2.4.6 this requirement was different: Only existing products that were virtual & downloadable [could skip processing](https://github.com/woothemes/woocommerce/blob/2.4.6/includes/abstracts/abstract-wc-order.php#L2302-L2321).

I couldn't find anything in the 2.4.7 changelog, just the 0164584aaf6fc8f6e753fd2f3e661177b515ddb9 commit. Is there any rationale behind this?

**Comment by mikejolley** [comment]
If its not a 'product' you're adding it programmatically or through a plugin, in which case the woocommerce_order_item_needs_processing filter should be used to tell WC what to do.

**Comment by Spreeuw** [comment]
@mikejolley that's not possible, because that filter is never executed then the product doesn't exist!

**Comment by mikejolley** [comment]
Might be tricky to change that filter if plugins expect a product object. woocommerce_payment_complete_order_status is also available for use and thats not wrapped in anything.

**Comment by Spreeuw** [comment]
Which is why the 2.4.6 method of not autocompleting when the product didn't exist worked quite nicely. I can make a PR if you like.

**Comment by mikejolley** [comment]
Ill take a look if you send PR
