### ISSUE TITLE
Bug in the file: ..\woocommerce\templates\emails\plain\email-addresses.php

### ISSUE THREAD

**Issue by alfkoblischke** [woothemes/woocommerce#10253]
You have a tab in the echo code. The adress looks very strange in the emails.
See the code below. **The \t must be deleted**, then everything is perfect again...

if ( ! defined( 'ABSPATH' ) ) {
exit;
}

echo "\n" . strtoupper( __( 'Billing address', 'woocommerce' ) ) . "\n\n";
echo preg_replace( '##i', "\n", $order->get_formatted_billing_address() ) . "\n";

if ( ! wc_ship_to_billing_address_only() && $order->needs_shipping_address() && ( $shipping = $order->get_formatted_shipping_address() ) ) {
echo "\n" . strtoupper( __( 'Shipping address', 'woocommerce' ) ) . "\n\n";
echo preg_replace( '##i', "\n\t", $shipping ) . "\n";
}

This is the correct code:

if ( ! defined( 'ABSPATH' ) ) {
exit;
}

echo "\n" . strtoupper( __( 'Billing address', 'woocommerce' ) ) . "\n\n";
echo preg_replace( '##i', "\n", $order->get_formatted_billing_address() ) . "\n";

if ( ! wc_ship_to_billing_address_only() && $order->needs_shipping_address() && ( $shipping = $order->get_formatted_shipping_address() ) ) {
echo "\n" . strtoupper( __( 'Shipping address', 'woocommerce' ) ) . "\n\n";
echo preg_replace( '##i', "\n", $shipping ) . "\n";

**Comment by mikejolley** [comment]
Can you screenshot what you're seeing instead of the indent?

**Comment by claudiosmweb** [comment]
Missing a lot of information here... But this is the "issue":

![screenshot from 2016-02-03 15-15-08](https://cloud.githubusercontent.com/assets/1264099/12790398/370e981e-ca89-11e5-8439-08ba8eefef58.png)
