### ISSUE TITLE
Hook in API when Variation is created

### ISSUE THREAD

**Issue by iamswain** [woothemes/woocommerce#10258]
Currently there is a hook that's fired after a product has been created by the API (`/includes/api/class-wc-api-products.php:331`).

```
do_action( 'woocommerce_api_create_product', $id, $data );
```

This allows to create custom meta fields that can be filled over the API, which is excellent! However, this isn't possible for variations, but by adding a hook like this to the API function `save_variations()` (can be found on `/includes/api/class-wc-api-products.php:1692`) that might look something like this?

```
do_action( 'woocommerce_api_create_variation', $id, $data );
```

The importance here is that the variable `$data` is included in the hook. I'd like to resolve this myself, and submit a pull request but I'm not too confident with this yet.

_P.S. Any help regarding this confidence is welcome._

**Comment by claudiosmweb** [comment]
You can use the `woocommerce_api_create_product` for it too.
And you can use `woocommerce_api_save_product_variation` to save variation data.

**Comment by iamswain** [comment]
@claudiosmweb Thanks for your quick response, means a lot! However, I fail to see how to use these two hooks to assign specific data to specific variations.

`woocommerce_api_create_products` gives me just the variations data I sent along, which I can loop through but without the variation ID I can't assign any data.

`woocommerce_api_save_product_variation` gives me the variation ID, but doesn't give me the data I sent over the API.

I hope you understand my point, or could help me point out the mistake I'm making here.

**Comment by iamswain** [comment]
Hi @claudiosmweb, would love it when you could elaborate a bit further on my last comment. :)
