### ISSUE TITLE
Order Pay Enpoint: Payment Slider not working due to missing class on form

### ISSUE THREAD

**Issue by clubdesign** [woothemes/woocommerce#10261]
Hey,

after a while of debugging we found the following:

If a user cancels a payment, then he is redirected to the order-pay page where the order can be paid. On this page the checkout.min.js is loaded and initiated. BUT: The Listener for the click event on the payment selector labels if attached to a form with the class .checkout which doesn`t exist in this page as the form #order_review in form-pay.php doesn`t have any classes. So the event is nevver attached and though never triggered.

I suggest adding the checkout class to order-pay.php or to go the hard way and attach the event differently.

This might be an urgent bug, because if i am right, no order-pay form out there in world is working correctly.

Greets Marcus

**Comment by claudiosmweb** [comment]
> If a user cancels a payment, then he is redirected to the order-pay page where the order can be paid. 

When a user cancel a payment by "My Account", will be redirected back to "My Account" page.

**Comment by clubdesign** [comment]
No, i don't mean cancelling within the my account page. i mean cancelling within a payment cycle.

But even, that isn't the point. The point is that the payment selector dosen't work on the order-pay endpoint, as described extensively above. It can`t work correctly as the class the JS binds the click event to is NOT present.

Greets

**Comment by clubdesign** [comment]
I have just seen, that this has been circumvented in this line

https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/checkout.js#L24

but i my case, the body didn`?t have classes, so it didn`t trigger the desired action.

Greets Marcus

**Comment by claudiosmweb** [comment]
> The point is that the payment selector dosen't work on the order-pay endpoint, as described extensively above.

Tested and works fine in `order-pay`.
