### ISSUE TITLE
Restore row actions for shop orders

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#10263]
Currently there are no row actions for orders:

![image](https://cloud.githubusercontent.com/assets/507025/12789924/dc7144f8-ca6d-11e5-9e5d-3db1c146f834.png)

And the order number is the only link to edit the order. I'd like to suggest restoring the row actions [here](https://github.com/woothemes/woocommerce/blob/f8df682f34b7627d89954d92740e514127a6582c/includes/admin/class-wc-admin-post-types.php#L907), like every other default post type. 

![image](https://cloud.githubusercontent.com/assets/507025/12790074/a2362230-ca6e-11e5-87c9-30f81544b20a.png)

At a bare minimum, the "edit" link. Though if you can "trash" an item in the bulk actions, you may as well have trash in the row actions.

**Comment by claudiosmweb** [comment]
@mikejolley not bad idea, what you think?
