### ISSUE TITLE
Filter widget problem due to incorrect use of the MySql prepare

### ISSUE THREAD

**Issue by MBerkhout** [woothemes/woocommerce#10266]
**The problem**
When using the WooCommerce pricefilter widget it is not possible to filter with decimals. All the decimals will be replaced by whole numbers. 

**The solution**
The solution is really simple and already done in a part of the code. In the file "includes/class-wc-query.php" on line 874 there is stated `AND pm1.meta_value BETWEEN %f AND %f` by replacing the %f to a %d the code is ready for decimals. This is already done on rule 897 (same filter option but without tax-enabled). There is realy no extra use for using the %f instead of %d.

As it is a small changes (changing two letters from f to d), I've chosen to not create a pull request by myself. Please fix the bug in future updates.

**Comment by mikejolley** [comment]
You're backwards. %d is integer. %f is float. Float = decimals.
