### ISSUE TITLE
REST API: signature verification issue

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#10273]
Hello,
I am developing Android Application and I am using WooCommerce REST API in order to access data from WordPress Woocommerce store.But i am getting error.

"{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}"

Though in my website REST API is enabled, keys are properly generated and generated keys many times for confirmation.
I have Woocommerce version as 2.5.2.

Could it be anything related to server?
If it is related to server then what could cause this issue?

**Comment by mikejolley** [comment]
Do not reopen the same issue twice.
