### ISSUE TITLE
"Coupon(s) Used" should test if it's a fixed discount or a cart percentage discount

### ISSUE THREAD

**Issue by crissoca** [woothemes/woocommerce#10277]
When you are in the edit order screen there is a "Coupon(s) Used" section in this section it shows which coupon was used and if you hover over it it shows the value of the coupon, the problem is that this value is always displaying the price and it doesn't compare if it's a percentage coupon or a fixed amount.

Here is an example: http://d.pr/i/XK3Q/ZVtGFfP5 in this case the coupon gives a 100% discount however it's showing "$100" as the value where the actual value is not $100.

This is in the file `includes/admin/views/html-order-items.php` around line 131.

**Comment by mikejolley** [comment]
Not sure what you mean - the price displayed is how much discount it granted for the user when used. It is not reflective of the original coupons 'value'.

**Comment by crissoca** [comment]
Sorry about that, after a couple of tests I found that the problem is related to another plugin and it affects WooCommerce, thanks.
