### ISSUE TITLE
SyntaxError: JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by aneeshjajodia** [woothemes/woocommerce#10274]
Hello,

Been trying to figure out the reason for this.

Having this error on the checkout page. Tried changing themes, disabling plugins and everything.

I have no clue for the error.

**Comment by mikejolley** [comment]
All I can say is, you didn't search very far :) http://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

**Comment by tsanwie** [comment]
tried but not working, my site [lampu sorot](http://www.sistematik-energi.com)

**Comment by tsanwie** [comment]
please assist

**Comment by mikejolley** [comment]
Follow the instructions given - they do 'work' if you look in the right place.

**Comment by Kitloo** [comment]
@tsanwie Are you trying to promote yourself in this site??
