### ISSUE TITLE
 woocommerce api authentication error REST API Error.

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#10271]
Hello,
    I am developing Android Application and  I am using WooCommerce REST API in order to access data from WordPress Woocommerce store.But i am getting error.

"{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}"

Though in my website REST API is enabled, keys are properly generated and generated keys many times for confirmation.
I have Woocommerce version as 2.5.2.

**Comment by claudiosmweb** [comment]
> keys are properly generated and generated keys many times for confirmation.

Not properly generated yet, if not will work.

Here have instructions for it: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

**Comment by pkhutal** [comment]
Thanks for your reply...i have gone through this documentation.

But  authentication algorithm that i have written using  "http://woothemes.github.io/woocommerce-rest-api-docs/#authentication" 
is working on my one of my WooCommerce store but same thing is not working on another.

Both stores are hosted on different servers.Could it be anything related to server?
If it is related to server then what could cause this issue?

Thank you for your cooperation.

**Comment by claudiosmweb** [comment]
> Could it be anything related to server?
>If it is related to server then what could cause this issue?

No, never seen errors caused by being on different servers.
Probably something you still doing wrong... You can test one of our wrappers:

http://woothemes.github.io/woocommerce-rest-api-docs/#official-libraries

**Comment by pkhutal** [comment]
thanks for your support ...i will check again.

**Comment by pkhutal** [comment]
Hello i have checked it again....but not getting please help me..

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)

**Comment by mikejolley** [comment]
Just an additional note, the error would have to be on your part and not a bug in core, because if it were a bug in core our IOS app would not work. And it does.

**Comment by claudiosmweb** [comment]
@mikejolley as I said to him, to test with our wrappers...

**Comment by pkhutal** [comment]
Thanks...i will check and get back .
