### ISSUE TITLE
State/Province Dropdown does not update on Country selection

### ISSUE THREAD

**Issue by iansvo** [woothemes/woocommerce#10283]
I've verified this issue is occurring on three separate installations.

Replication Steps:

1. Add product to the cart
2. Proceed to checkout page
3. Choose a new country (e.g. not the default that shows on page load)
4. Note the available choices in the state dropdown

Since each of these installations has a different set of plugins, I'm pretty sure that the plugins in use on each site would not be conflicting. 

Each installation also has its own active theme, although they are based on the same parent.

Example site: davidhearn.ca/shop

If additional information is needed, please advise and I'll provide it.

**Comment by reigelgallarde** [comment]
#8255 this discussion..

**Comment by mikejolley** [comment]
Caused by the theme changing how form fields are output/wrapped. See #8255
