### ISSUE TITLE
Alert/notice on disabled variation button click event

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10281]

**Comment by frankug** [comment]
This is a HUGE improvement guys! Thanks - May I suggest that the product addon's plugin now need to behave the same way as variations when someone clicks the add to car without making a selection and they are made mandatory. This not only would improve customer experience but also give consistency.

**Comment by frankug** [comment]
Hi Mike, we have been dong a lot of testing - this is a bug improvement on having no error however conversions seem to be down still from not having the button disabled.

We believe it is highly likely that the call to action being "Add to Cart" is not standing out - causing less clicks to the add to cart button.

Is there an easy way to set the opacity to normal even when the add to cart button is disabled - that way - they will still get the error window if they do not make a selection and they will still be encouraged to hit the add to cart button as it is not disabled?

Can this be done by custom css ? what would you suggest - happy to do the testing and come back to you if we are correct.
