### ISSUE TITLE
Missing api tab in settings (v 2.3.13)

### ISSUE THREAD

**Issue by DardanMu** [woothemes/woocommerce#10289]
The documentation for setting up the ios app states that I need a woocommerce version of 2.1+, but I dont see the api tab in woocommerce > settings in my woocommerce version (2.3.13). Must I update, or is there something I am missing? The 'Enable REST api' checkbox is ticked.

**Comment by claudiosmweb** [comment]
We don't have any API tab in 2.3.13.

**Comment by redpist** [comment]
Hi, I have exactly the same issue : 
I fulfill the documentation requirements (WooCommerce 2.3.11  >= v2.1), the Wordpress permalink is enabled and the WooCommerce>Settings>'Enable REST api' is checked, but I don't have an API tab in WooCommerce.

**What should I do to manage my API keys please ?**

**Comment by DardanMu** [comment]
Go to the WordPress user account management. The api keys are in there.

**Comment by redpist** [comment]
Thanks a lot!
