### ISSUE TITLE
Plugin causing woocommerce api authentication error REST API Error

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#10287]
Hello,

I am using WooCommerce REST API in order to access data from WordPress Woocommerce store.But i am getting error.

"{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}"

After a long reasearch i came to know that I have installed and activated

"WordApp Mobile App Plugin iPhone & Android WooCommerce BuddyPress FREE" 

plugin in my wordpress  website and this is causing issue

because after deactivating the "WordApp" plugin everything is working fine.

so please suggest me something so that i can detect why api authentication is not working using REST API.

**Comment by claudiosmweb** [comment]
Contact the author of "WordApp Mobile App Plugin iPhone & Android WooCommerce BuddyPress FREE" to debug it.
