### ISSUE TITLE
Price rounding calculation failure

### ISSUE THREAD

**Issue by hanisnl** [woothemes/woocommerce#10292]
Hello there .

In my Woocommerce (ver 2.5.2) powered by wordpress (4.4.2) ... I have the following issue, in the cart, when Woo calculates the total price :

22 items x 121.27 = 2667.96 - INCORRECT ! it should be 2667.94 (correct value)

Where and how does the price calculation fail ? why does it do this weird rounding and how do I fix it ?!
![price_error](https://cloud.githubusercontent.com/assets/9942056/12876554/ae8f94c2-ce0a-11e5-9139-5356a191fd14.png)

**Comment by mikejolley** [comment]
Have you defined prices with more than 2 decimals? Or are you using prices inc taxes?

Tested with a 20% tax rate, prices excl. tax, no issue:

https://dl.dropboxusercontent.com/s/pt0vumene871rt9/2016-02-08%20at%2009.52.png?dl=0

**Comment by hanisnl** [comment]
I don't know what you did there, seems correct in your attached photo .. BUT ! 

I did this : new wordpress install + woocommerce . no other plugins .

1. I added a product with the price : 145.53
2. I added as Standard tax 20% VAT
3. Settings/tax : Display Prices in the Shop: without tax
    Settings/tx : Display Prices During Basket and Checkout: : without tax
4. Woocommerce calculated the price WITHOUT vat to : 121.28

NOW ! 
I added 22 x 121.28 to cart . woo calculated this to : 2,668.05 - this is INCORRECT ! it should be : 2668.16 !

![cart_error](https://cloud.githubusercontent.com/assets/9942056/12892419/b83cc640-ce94-11e5-8f87-f0dc349f8307.png)

**Comment by mikejolley** [comment]
Nope.

145.53 is your tax inclusive price. So 22 of them is including tax is 3,201.66

The tax itself is 533.61

3201.66 - 533.61 = 2668.05

You're thinking its rounded per item. it's not. It's rounded per line.

**Comment by mikejolley** [comment]
> Now .. I understand where the problem is .. the price should be 121.275 .. and x 22 items it does equal to 2668.05 .. BUT from a perspective of accounting .. an invoice with "121.28 x 22 = 2668.05" is just not correct .

It is correct based on your settings. If you don't like it displaying like this, either:

a) Show cart prices including tax
b) use tax excl. prices for products

The logic is correct that we have now.

**Comment by hanisnl** [comment]
we just don't see eye to eye on this ...

The invoice has 22 items x 121.28 it should equal 2668.16 (not 2668.05) .. and plus 20% VAT = 3201.79 (not 3201.66)  .. it is true that the whole price 145.53 x 22 = 3201.66 ... but the invoice is just incorrect .

An invoice like this is NOT correct .. we can not calculate backwards .
**An invoice with  22 x 121.28 = 2,668.05 is just not correct !**

Maybe I'm not expressing myself very well .. but math should be an exact science .

**Comment by hanisnl** [comment]
The problem is that in my country I have to show prices **without vat** and calculate vat at the end .
Any invoice that shows fake data is just fake .. even if the price has very a little difference, up or down, the issue remains .

**Comment by mikejolley** [comment]
**So enter prices excluding tax, then it won't do this type of rounding or backwards calculation**

**Comment by mikejolley** [comment]
![2016-02-08 at 17 13](https://cloud.githubusercontent.com/assets/90977/12893126/50a4aa46-ce87-11e5-8c32-3f711af5b9e8.png)

**Comment by hanisnl** [comment]
While the way you suggest it does work : adding prices without tax, showing prices without tax, and in the CART showing the prices without tax,

I still have a woocommerce with 1800 products with the prices that do contain VAT already .. that is the problem .. thanks anyway ...

**Comment by mikejolley** [comment]
You can bulk update with a csv importer for example. We cannot change the rounding for all users

**Comment by hanisnl** [comment]
Yes, true .Thank you for your help .
anyway ... somehow this feels like woocommerce could get better around this issue ... giving the user the ability to add products with VAT is almost useless in situations like this .

**Comment by mikejolley** [comment]
It's not. As I said, we round per line. Not per item. This is perfectly valid in the UK anyway. 

Rounding per item would mean charging customers too much.
