### ISSUE TITLE
(Includes XY tax) doesn't translate due to uppercase letter

### ISSUE THREAD

**Issue by Fyod** [woothemes/woocommerce#10291]
/includes/class-wc-order.php line 46
`$tax_string = ' ' . sprintf( _e( '(Includes %s)', 'woocommerce' ), implode( ', ', $tax_string_array ) );`

and /includes/wc-cart-functions.php line 265
`$value .= '<small class="includes_tax">' . sprintf( __( '(Includes %s)', 'woocommerce' ), implode( ', ', $tax_string_array ) . $estimated_text ) . '</small>';`

.pot files have a small 'i' in includes %s.

**Comment by mikejolley** [comment]
The POT reflects the stable release, not dev. You only need to worry about the strings on https://translate.wordpress.org/projects/wp-plugins/woocommerce which are current.
