### ISSUE TITLE
Cart NOT showing correct price - still not resolved !

### ISSUE THREAD

**Issue by hanisnl** [woothemes/woocommerce#10298]
Just like in my other ticket : https://github.com/woothemes/woocommerce/issues/10292

I did this : new wordpress install + woocommerce . no other plugins .

I added a product with the price : 145.53
I added as Standard tax 20% VAT

Settings/tax : Display Prices in the Shop: without tax 
Settings/tx : Display Prices During Basket and Checkout: : without tax

Woocommerce calculated the price WITHOUT VAT to : 121.28
I added 22 x 121.28 to cart . woo calculated this to : 2,668.05 - this is INCORRECT ! it should be : 2668.16 !

Now .. I understand where the problem is .. the price should be 121.275 .. and x 22 items it does equal to 2668.05 .. BUT from a perspective of accounting .. an invoice with "121.28 x 22 = 2668.05" is just not correct .

![cart_error](https://cloud.githubusercontent.com/assets/9942056/12892520/4705992e-ce95-11e5-90fd-9eab16fff39f.png)

**Comment by mikejolley** [comment]
Do not reopen "issues" like this. a) it's not a bug and b) you can comment on the other one.
