### ISSUE TITLE
Admin screen heading tags with WordPress 4.4

### ISSUE THREAD

**Issue by lutrov** [woothemes/woocommerce#10300]
Woocommerce uses incorrect headings in admin screens. See https://make.wordpress.org/core/2015/10/28/headings-hierarchy-changes-in-the-admin-screens/ for more.

**Comment by justinshreve** [comment]
Core screens to look over, to see which to fix:

- [ ] Orders
- [ ] Coupons
- [ ] Reports
- [ ] Settings > General
- [ ] Settings > Products > General
- [ ] Settings > Products > Display
- [ ] Settings > Products > Inventory
- [ ] Settings > Products > Downloadable Products
- [ ] Settings > Tax > Tax Options
- [ ] Settings > Tax > Rates Tabs (Standard Rates, Reduced Rate Rates, Zero Rate Rates)
- [ ] Settings > Shipping > Shipping Zones
- [ ] Settings > Shipping > Shipping Options
- [ ] Settings > Shipping > Shipping Classes
- [ ] Settings > Shipping > Flat Rate (Legacy)
- [ ] Settings > Checkout > Checkout Options
- [ ] Settings > Checkout > Options Tabs (Cheque, BACS, etc...)
- [ ] Settings > Accounts
- [ ] Settings > Emails
- [ ] Settings > Emails > Each Individual Email
- [ ] Settings > Integrations
- [ ] Settings > API > General Options
- [ ] Settings > API > Keys/Apps
- [ ] Settings > API > Webhooks
- [ ] System Status
- [ ] System Status > Tools
- [ ] System Status > Logs
- [ ] Add-ons Screens
- [ ] Products
- [ ] Add Product
- [ ] Categories
- [ ] Edit Category
- [ ] Tags
- [ ] Edit Tag
- [ ] Attributes
- [ ] Edit Attributes
