### ISSUE TITLE
Access enabled payment and shipping methods via the API

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#10305]
It would be useful to be able to access a list of the enabled payment and shipping methods via the API.

An example use case would be to pre-map payment methods to financial accounts in an accounting system (for example, all PayPal payments are sent to account X, and all 'example payment gateway' payments are sent to account Y).

I'd say the `method_id` and `method_title` would be all that's necessary for this endpoint.

**Comment by claudiosmweb** [comment]
TODO:

Add new endpoints:

- GET /shipping_methods
- GET /payment_methods

**Comment by Storebuddy** [comment]
I fully agree with mattyza that these endpoints could be very useful. In addition to `method_id` and `method_title`, for the shipping methods, `taxable` information could be very useful.

**Comment by mikejolley** [comment]
GET /shipping_zones

**Comment by mikejolley** [comment]
See #11608 and #11607

**Comment by umarcpt** [comment]
How can I use this method shipping_method, shipping_zones?
[this my api url](http://www.kaj-tek.com/andi/wp-json/wc/v1/)

i test both but shows 404

**Comment by justinshreve** [comment]
@umarcpt These endpoints are not implemented yet. See the above links.

**Comment by umarcpt** [comment]
now I use GitHub WC API code and access both endpoints. Now I have questions about payment gateways that I only want to get those payments gateways which is enabled for method flat_rate or free_shipping, how can I do this?

**Comment by claudiosmweb** [comment]
@umarcpt here is not a support channel and this method is not implemented it, when it's all done we'll write docs for it. But for now we don't have even a beta version of this endpoint, so you need to wait.
