### ISSUE TITLE
Tax types and order line items in the API

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#10308]
When viewing order line items, while there is a `total_tax` line item, there is no way of seeing which tax types were applied to each line item.

An example use case for this would be attributing taxes appropriately within an accounting system, connected to the WooCommerce API.

**Comment by mikejolley** [comment]
Improving this as part of CRUD branch. Line Item Spec: https://dl.dropboxusercontent.com/s/70o6bi97dmuy0k1/2016-02-23%20at%2011.15.png?dl=0

#10259
