### ISSUE TITLE
Wrong text in the inside attributes terms

### ISSUE THREAD

**Issue by andreas-pa** [woothemes/woocommerce#10304]
If you create an attribute and the attributes has no terms, there is a wrong message in the admin screen : 

> No categories found.

Steps for seeing the problem : 
- Go in the wp backend
- Go to Products -> Attriutes
- Create an attribute
- Click on the gear icon
- " No categories found."

I believe the phrase is wrong and It can confuse because the same phrase appears in the Product Category section.

**Comment by claudiosmweb** [comment]
The "No categories found" it's a default when you register new taxonomies, but you can change it... Now will shows like `No "Color" found`.
