### ISSUE TITLE
Product: rich snipptes

### ISSUE THREAD

**Issue by Tobias-Conrad** [woothemes/woocommerce#10314]
HI,

litle adjustments will make google more happy and google search results with stars more possible.
![detox santegra google suche](https://cloud.githubusercontent.com/assets/7352673/12946212/096c8154-cff3-11e5-93a6-5523ca2385b4.png)

tested with: https://developers.google.com/structured-data/testing-tool/

Only one total rating amount must be provided with markups.
Nur eine Gesamtbewertung darf mit Markups versehen sein.

You must specify review count either ratingCount or reviewCount.
Sie müssen entweder ratingCount oder reviewCount angeben.

Product:	https://www.santegra-international.com/produkt/detox-deluxe-paket-cleansing-pack-liverpro-burdock-hydrangea/product-3076
image:	https://www.santegra-international.com/wp-content/uploads/59_Santegra-Detox-Deluxe-Paket_Santegra-Infothek-original-kur-web4.jpg
name:	Detox Deluxe Paket (Cleansing Pack + LiverPro + Burdock + Hydrangea)
description:	Detox Deluxe Paket für eine Person 1x Elmigone, 2x SaniTea, 3x FortiFi, 1x LiverPro, 1x Burdock, 1x Hydrangea
offers [Offer]:
price:	145.75
priceCurrency:	EUR
availability:	http://schema.org/InStock
aggregateRating [AggregateRating]:
ratingValue:	5
bestRating:	5
reviewCount:	1
**Nur eine Gesamtbewertung darf mit Markups versehen sein.**
review [Review]:	https://www.santegra-international.com/produkt/detox-deluxe-paket-cleansing-pack-liverpro-burdock-hydrangea/li-comment-1720
datePublished:	2015-09-11T14:48:03+00:00
description:	lin, Beruf: Ökonomist, Czech Republic, Tschechien Unglaublich. 5 wochen verlassen meinen Körper ingesamt grosse Parasiten. Ich denke, dass in 5 Wochen war ungefähr 0,5-3/4 l Tasse “Fleischabfall”. Jedem nur empfehlen. Ich weiss jetzt, dass diese Kur (detox delux paket) werde ich jedes Jahr wiederholen. (0)
reviewRating [Rating]:
ratingValue:	5
author [Thing]:
name:	Tobias-Conrad
aggregateRating [AggregateRating]:
ratingValue:	5.00
**Sie müssen entweder ratingCount oder reviewCount angeben.
Nur eine Gesamtbewertung darf mit Markups versehen sein.**
aggregateRating [AggregateRating]:
ratingValue:	5.00
**Sie müssen entweder ratingCount oder reviewCount angeben.
Nur eine Gesamtbewertung darf mit Markups versehen sein.**

**Comment by claudiosmweb** [comment]
Seems to be issues in your theme... I tested it using Storefront and I don't get any error.

Check with: http://wc.claudiosanches.com/product/woo-single-2/

![screenshot from 2016-02-10 17-08-14](https://cloud.githubusercontent.com/assets/1264099/12958443/e315a780-d018-11e5-884d-bf24d2de5abd.png)

Try another theme (or talk with the theme author) or patch your theme.
