### ISSUE TITLE
UI/UX Enhancement: Back buttons for email settings

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10317]
Right now, there is no "back button" after clicking into editing an email's settings: http://cld.wthms.co/1dkIk/15XeaTjj

Of course you can click on the tab to return, but it feels a little awkward, at least to me. In all of the other settings panels, users know they can click on the top menu links to navigate around that tab's settings.

So what if we just added in something like this: 

![](http://cld.wthms.co/15QPN/2cW87ebj+)

I think this would feel more natural, and go along with all of the other settings pages a bit better.

**Comment by claudiosmweb** [comment]
No, no breadcrumbs :stuck_out_tongue_winking_eye:

Let's use our new "turn back" button, from our new "Shipping Zones" screens.

![screenshot from 2016-02-10 13-46-47](https://cloud.githubusercontent.com/assets/1264099/12952200/c55329f0-cffc-11e5-89d8-0c9c5b4b9e61.png)

**Comment by WPprodigy** [comment]
"Turn back" could work :)

Thoughts @jameskoster?

**Comment by jameskoster** [comment]
Turn back seems appropriate to me. Consistency ftw.
