### ISSUE TITLE
Price now showing on product pages

### ISSUE THREAD

**Issue by mobilitypitstop** [woothemes/woocommerce#10325]
Hi, since I did a product merge import the prices are not showing on the woo commerce product pages. However, when you click on update the price shows and the product is marked as visible/available on the front end.

**Comment by mikejolley** [comment]
Look at the data you're importing. Remember you need to set _regular_price, not price, and use a valid 'visibility' setting. If the above happens, export and compare to a working product to find your mistake.

This is not a core bug.

**Comment by mobilitypitstop** [comment]
Hi Mike
Thanks – The import is a direct import from an export? Do you know why the _regular_price is not being exported?

**Comment by mikejolley** [comment]
You'd need to look at your export to see if that really is the reason. When prices are set, _price would also need to be set to the same value.

**Comment by mobilitypitstop** [comment]
Hi Mike,

I think it may be because the product merge import has a regular_price for Variable products so it may be conflicting with the regular_price
merge from the variation import.

I guess if I remove these it will update correctly from the regular_price from the variation import merge.

**Comment by mikejolley** [comment]
Variation merge is more tricky because it needs to sync with the parent product. I'm not sure the WP importer will trigger this event.
