### ISSUE TITLE
Shipping zones - Undefined index error when adding flat rate

### ISSUE THREAD

**Issue by daigo75** [woothemes/woocommerce#10320]
Clean WC 2.6 setup, freshly installed (nothing else). I tried to add flat rate to Europe, the Ajax call fails. The error is `( ! ) Notice: Undefined index: flat_rate in C:\tmp\woocommerce\includes\class-wc-shipping-zone.php on line 228`.

Trying again returns the same error, which appears twice in the shipping zones page.

**Comment by daigo75** [comment]
Additional note: the error comes and goes, I can't figure out why.

**Comment by daigo75** [comment]
Found the issue. It's actually due to a breaking change in the `woocommerce_shipping_methods` filter, and a conflict caused by the theme I had installed. I forgot that the `functions.php` contained a small customisation, but it's good that I spotted this issue, as it could have a significant impact.

Key difference
--
* In WC 2.5 and earlier, filter `woocommerce_shipping_methods` returned a simple array of classes or objects.
* In WC 2.6, the same filter returns an array with meaningful IDs used as keys, which must be preserved.

A filter that doesn't preserve the keys (quite possible, since they were irrelevant until now) could cause a conflict. It's worth highlighting this change in the development log (new section "**Breaking changes**"). :smile:

**Comment by mikejolley** [comment]
Can you post the snippet?

**Comment by daigo75** [comment]
If you mean the code snippet from the core, here they are.

WC 2.5 and earlier
--
A filter for `woocommerce_shipping_methods` has to return a simple array (keys are numeric, and irrelevant).
~~~
// Register methods through a filter
$shipping_methods_to_load = apply_filters( 'woocommerce_shipping_methods', array(
	'WC_Shipping_Flat_Rate',
	'WC_Shipping_Free_Shipping',
	'WC_Shipping_International_Delivery',
	'WC_Shipping_Local_Delivery',
	'WC_Shipping_Local_Pickup'
) );
~~~

WC 2.6
--
A filter for `woocommerce_shipping_methods` must return an array preserving the keys. Furthermore, the filter is called too early (see comment below).
~~~
$shipping_methods = apply_filters( 'woocommerce_shipping_methods', array(
	'flat_rate'     => 'WC_Shipping_Flat_Rate',
	'free_shipping' => 'WC_Shipping_Free_Shipping',
	'local_pickup'  => 'WC_Shipping_Local_Pickup',
) );

// For backwards compatibility with 2.5.x we load any ENABLED legacy shipping methods here
$maybe_load_legacy_methods = array( 'flat_rate', 'free_shipping', 'international_delivery', 'local_delivery', 'local_pickup' );

foreach ( $maybe_load_legacy_methods as $method ) {
	$options = get_option( 'woocommerce_' . $method . '_settings' );
	if ( $options && isset( $options['enabled'] ) && 'yes' === $options['enabled'] ) {
		$shipping_methods[ 'legacy_' . $method ] = 'WC_Shipping_Legacy_' . $method;
	}
}

// The filter should be called here, passing an array that includes the legacy methods
~~

**Comment by daigo75** [comment]
[I created a PR to postpone the filter call](https://github.com/woothemes/woocommerce/pull/10323), so that all methods can be processed by filters attached to the `woocommerce_shipping_methods` hook.

**Comment by mikejolley** [comment]
I'll review this in the morning.

**Comment by mikejolley** [comment]
I meant the code in your theme you found.

**Comment by daigo75** [comment]
The filter code boils down to the following (still enough to reproduce the issue):

~~~
add_filter('woocommerce_shipping_methods', function($shipping_methods_to_load) {
	$shipping_methods = array();
	foreach($shipping_methods_to_load as $method) {
		if(!is_object($method)) {
			// Initialising the method here triggers all the functions related to
			// multi-currency support
			$method = new $method();
		}
		// Other stuff with the new shipping instance

		// This adds the method back to the SIMPLE array. The key, in this
		// case, is lost (it was not used anyway, before WC 2.6)
		$shipping_methods[] = $method;
	}
	return $shipping_methods;
}, 10);
~~~

Fixing it is easy enough, it's sufficient to preserve the keys. However, it's vital that this type of changes is documented thoroughly. Breaking changes should be a rare exception, when they happen it's good to know where and when.

**Comment by reformdesigns** [comment]
I noticed weird issues with 'flat rate' showing up on mobile devices even though we have it disabled.

**Comment by sherifsaleh** [comment]
file: class-wc-shipping.php on line 300: 
/*----------------------- replace ------------------------*/
						$rate = $package['rates'][ $chosen_method ];
						// Merge cost and taxes - label and ID will be the same
						$this->shipping_total += $rate->cost;

/*----------------------- by ------------------------*/

					// check if chose method is defined in the country
					if( ! empty( $package['rates'][ $chosen_method ] ) ) {
						$rate = $package['rates'][ $chosen_method ];
						// Merge cost and taxes - label and ID will be the same
						$this->shipping_total += $rate->cost;

					}else {
						// if not get the first rate in the conunty
						$rate =  array_values($package['rates'])[0];
						// Merge cost and taxes - label and ID will be the same
						$this->shipping_total += $rate->cost;

					}
