### ISSUE TITLE
email-styles.php : <a> tag color style will not update in emails

### ISSUE THREAD

**Issue by swmcgithub** [woothemes/woocommerce#10322]
I've copied the email-styles.php file to yourtheme/woocommerce/emails/email-styles.php because I needed to update how the emails look. All style updates that I've made work fine except for the a tag color style. It naturally looks like this:

`a {
    color: <?php echo esc_attr( $base ); ?>;
    font-weight: normal;
    text-decoration: underline;
}`

However, if I update it to do this instead:

`a {
    color: #015138;
    font-weight: bold;
    text-decoration: underline;
}`

The font weight is changed to bold, but the color remains as the base color from before. (In this case, white.)

**Comment by claudiosmweb** [comment]
Tested and works great...

But gmail or some email clients can create links, like for email address and it will lose the styles, since all styles are inline.
