### ISSUE TITLE
Single product page - wrong content in alt-tag of main image 

### ISSUE THREAD

**Issue by KristoferN** [woothemes/woocommerce#10327]
The alt-tag of the main product image is showing the images title content, not its alt-text.

**Comment by 2ndkauboy** [comment]
Why has this been closed without a comment? I also experienced the same issue today. For me, the solution in #8164 looks perfectly fine. WooCommerce (just as WordPress) should always use the correct values form the media library: "Title" for the title attribute and "Alt Text" for the alt attribute.

I even don't see why the mentioned prettyPhoto would be an issue as a user is free to set the exact same text for both values.

If you still insist on leaving it as is, you should introduce a filter to enable developers to set the correct alt attribute value from the media library.

**Comment by mikejolley** [comment]
Because a PR was also raised https://github.com/woothemes/woocommerce/pull/10328

**Comment by 2ndkauboy** [comment]
But that does not change the HTML code of the single page or on a archive. Or does it?

**Comment by mikejolley** [comment]
This issue was about the single page for variations.

**Comment by 2ndkauboy** [comment]
Could we than reopen #8164 as this issue is still not fixed?
