### ISSUE TITLE
WooCommerce Shipping Option Not Always Processed by Payment

### ISSUE THREAD

**Issue by wilburlikesmith** [woothemes/woocommerce#10332]
Every now and again the shipping amount doesn't get processed in WooCommerce. As if it's loosing the values when you switch to often or don't switch the shipping method. Kinda random too...

Have investigated (a million things) radio buttons and dropdown selection... Could possibly be an AJAX problem...

Totals are correct, clicking process payment sometimes only process the product value and looses the shipping amount.

**Comment by mikejolley** [comment]
Would need steps to reproduce or more details here. Submitted orders for instance; do they have shipping rows or not? Is this gateway specific?

**Comment by wilburlikesmith** [comment]
Hi Mike, we're using PayFast from you guys :) Users have to be registered (for business reasons). I have a pretty much clean setup here: 

`[(http://monsterplumbing.co.uk/store_dev/)]`

Since it's a dev and clean setup I don't have a problem posting the login details here: 

`Admin: store_admin
Pass: store_demo`

`User: store_shopper
Pass: store_demo`

**Comment by mikejolley** [comment]
I think your shipping method is causing this.

It filters on shipping packages, but `return false;` on certain conditions. if this happens, there is nothing to ship, so no shipping is added and no method recorded.
