### ISSUE TITLE
Be the first to review translation

### ISSUE THREAD

**Issue by rejcord** [woothemes/woocommerce#10334]
In the file "single-product-reviews.php" the translateable string "Be the first to review %s" doesn't match the string in the *.pot translation template file, therefore it won't be translated.

Even if I adjust the *.port / *.po / *.mo translation files, these will get overwritten and my translation will be discarded.

**Comment by claudiosmweb** [comment]
I could find it on translate.wordpress.org:

![screenshot from 2016-02-11 17-32-54](https://cloud.githubusercontent.com/assets/1264099/12987944/8c9d36de-d0e5-11e5-8315-3ee68a8cf576.png)

Don't seems to have any issue.

**Comment by rejcord** [comment]
Found it! The issue was in the single-product-reviews.php of the
    template! The template's file overwrites the original woocommerce
    file!
    
    Am 11.02.2016 um 20:33 schrieb Claudio
      Sanches:
    
    
      I could find it on translate.wordpress.org:
      
      Don't seems to have any issue.
      —
        Reply to this email directly or view
          it on GitHub.
