### ISSUE TITLE
Make the review template more editable

### ISSUE THREAD

**Issue by jameskoster** [woothemes/woocommerce#10339]
Currently the only way to re-arrange components is to overwrite the template file.

**Comment by mikejolley** [comment]
Can you add client side validation too :) html5 required attribute will suffice, if ratings are required.

**Comment by jameskoster** [comment]
I'm talking about the actual review template, not the form. But yeah, can do that.

**Comment by jameskoster** [comment]
@maxrice @justinstern You guy might want to give that a check with your reviews extension. Hopefully it'll work just fine though.

**Comment by bekarice** [comment]
@jameskoster thanks for the heads up :smile_cat: have a note to test this with the next Product Reviews Pro update to confirm.
