### ISSUE TITLE
Shipping select box option removed

### ISSUE THREAD

**Issue by nicoworq** [woothemes/woocommerce#10330]
Good afternoon ! 

Why did you removed the shipping select box option ? 
[https://github.com/woothemes/woocommerce/commit/8aec02f6259191827876782eedddb3258953cb8c]

Is there any other way to achieve this in the config ? 

Thanks !

**Comment by mikejolley** [comment]
Please search before logging issues, especially non-bug reports. Please read this: https://github.com/woothemes/woocommerce/issues/10152
