### ISSUE TITLE
Amazon Payment Gateway Issue

### ISSUE THREAD

**Issue by innomindtech-geeks** [woothemes/woocommerce#10348]
I have installed "Woo Commerce Amazon Payments Advanced Gateway" for the payment of our products using the amazon payment method and we have successfully completed the installation and after clicking the 'Amazon Payments Advanced' button from Payments Gateways(Woo Commerce>settings->Payments Gateways->Amazon Payments Advanced) we are getting a blank page .

I have checked the above issue by deactivating all non-Woo plugins and also switch back to a default WordPress theme like Twenty Twelve etc and still the issue is there.

Could you please help me to resolve the issue

**Comment by MattyLB** [comment]
Amazon Payments works fine last I checked. You should try this on their support forum for the Amazon plugin as the issue you're describing can happen if you're using the wrong credentials, something isn't completed on Amazon's side, or possibly a theme issue (based on my own experience with a similar issue).

Either way, I don't believe it's a WooCommerce issue and this is their development site, not a support site. ;)

**Comment by mikejolley** [comment]
^ This. Debug white screens with this method https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1

**Comment by innomindtech-geeks** [comment]
I have tried all the methods which you mentioned and still i am facing the same issue.Here i am attaching a screenshot of 'Amazon Payments Advanced' page.

![capture](https://cloud.githubusercontent.com/assets/6593168/13101592/f0c2732c-d56d-11e5-92ad-652bb702d428.JPG)

**Comment by mikejolley** [comment]
I highly doubt it will run on old versions of WP and WC due to API changes.
