### ISSUE TITLE
API returns 403 when providing BOTH short_description and description as HTML.

### ISSUE THREAD

**Issue by MichaelScottCode** [woothemes/woocommerce#10349]
The following returns 403 when trying to update a product:

	$newData['product']['description'] = "<p>Test</p>";
	$newData['product']['enable_html_description'] = true;
	$newData['product']['short_description'] = "<p>Test</p>";
	$newData['product']['enable_html_short_description'] = 'true';

I'm aware of the switch between bool and string for the enable parameters. This is as per the docs... i've also tried this with both bool and string values and nothing seems to resolve it. Had to split my update into two separate calls to work around it for now.

**Comment by justinshreve** [comment]
Hi @MichaelScottCode 

I can't seem to reproduce this. Is this using WC 2.5.2? I've tried calling the API via CURL as well as with the official PHP wrapper. Are you using the official PHP wrapper or something else to update products? It might help to see the full call you are making. Is there anything in your error logs?

**Comment by MichaelScottCode** [comment]
Turns out I wasn't using the official wrapper. I was using [kloon's](https://github.com/kloon/WooCommerce-REST-API-Client-Library) wrapper which I had updated with v3 endpoints.

I've switched it out now and the problem doesn't exist. Thanks for the heads up.

**Comment by claudiosmweb** [comment]
@MichaelScottCode for v1, v2 or v3 you can use: https://packagist.org/packages/automattic/woocommerce
