### ISSUE TITLE
Include Portugal on country codes list

### ISSUE THREAD

**Issue by bemvestir** [woothemes/woocommerce#10346]
Hi,

Portugal is not on https://github.com/woothemes/woocommerce/tree/master/i18n/states list.
So I would to kindly ask you to include Portugal on that list.

Kind Regards

**Comment by claudiosmweb** [comment]
@bemvestir trhis districts https://en.wikipedia.org/wiki/Districts_of_Portugal#List?

@tiagonoronha can you confirm it for me too? People use this districts on e-commerces?

**Comment by bemvestir** [comment]
Hi Claudio,

 

Thanks for your answer.

Yes Portugal is divided in 20 districts:

 

·         Açores (not Azores)

·         Aveiro

·         Beja

·         Braga

·         Bragança

·         Castelo Branco

·         Coimbra

·         Évora

·         Faro

·         Guarda

·         Leiria

·         Lisboa (not Lisbon)

·         Madeira

·         Portalegre

·         Porto 

·         Santarém

·         Setúbal

·         Viana do Castelo

·         Vila Real

·         Viseu

 

Have a great day.

 

Kind Regards

 

Elsa Soares

**Comment by tiagonoronha** [comment]
@claudiosmweb I've seen them being used on a few sites, but quite honestly, they are not necessary. 

All you really need is the post code and the city.

Is there a specific reason why you want this to be added, @bemvestir?

**Comment by mikejolley** [comment]
Thanks @tiagonoronha

**Comment by claudiosmweb** [comment]
@tiagonoronha thanks :)

**Comment by bemvestir** [comment]
Hi

 

Thanks for your answer.

 

I noticed that Portugal is not on the list -  <https://github.com/woothemes/woocommerce/tree/master/i18n/states> https://github.com/woothemes/woocommerce/tree/master/i18n/states and all countries presented have included several cities.


Does wocommerce table rate shipping works to Portugal without being on that list?

 

Kind Regards

**Comment by bemvestir** [comment]
Districts exist, this is how Portugal is structured.
Shouldn't WooThemes structure their data to match how Portugal is structured for maximum third party plugin compatibility, extendability, and usefulness, similar to what it does for other countries?

**Comment by mikejolley** [comment]
@bemvestir it should be based on what the customers of said country expect. We have counties in the UK, but I would never expect to see a dropdown of counties on the checkout - it's not important.

**Comment by silicondales** [comment]
Some UK checkouts do have counties in them. They are often wrong when they do. Yorkshire != North Yorkshire. Makes it harder to get through checkout for customer when faced with a list which does not contain their county (district / region / state) where they expect it = potential cart abandonment.

Only an issue for table rate shipping where this cannot be determined by a list of postcodes. In the UK example, this is not the case.

To provide an example: With certain carriers, it is more expensive to ship to certain "UK" postcodes, places like the highlands and islands** from within the UK**. In such cases, this is always determined by postcode + table rate with postcodes either in a big list, or with suitable wildcards (all postcodes starting X...).

With Portugal? Is shipping internally in Portugal more/less expensive based on region?

Your question: does shipping work ** to ** Portugal without being on that list? The answer is going to be yes. Shipping **internally ** _within _Portugal is clearly something else entirely. Is this based on district?

**Comment by bemvestir** [comment]
Hi,

Thanks for your reply.

I'm no wordpress, php, ...expert, far from it.
I'm just a fashion blogger, and all I want is to have the shipping functionality to work full and perfect also for Portugal.

So I see that there are two aspects to be considered, namely:

1 - Portugal is not yet included on that list, so I wonder if the shipping plugins work for our country, and if not, when you think that can be possible?

2 - For regular mail (letters) we can consider that there is only one rate for the main land and islands (the Azores and Madeira) and it varies of course depending on the weight. But the point is a eccommerce store do not send regular mail but packages with different types of orders and so there's different type of pricing, according to the local. Tiago Noronha as a Portuguese native easily understand the pricing of our main carrier in Portugal - CTT, if he checks these pages - http://www.ctt.pt/correio-e-encomendas/enviar-correio/opcoes-de-envio/encomendas.html#panel2-1 and http://www.ctt.pt/correio-e-encomendas/ajuda/zonas-encomendas.html. 

So I understand that localities, mean districts, are necessary for the proper functioning and track different prices, depending on the zone of Portugal we are shipping to and from.

I hope I have clarified a little better this question.

Kind Regards

**Comment by mikejolley** [comment]
Does Portugal have an equivalent to zip codes, to use instead of states?

> 1 - Portugal is not yet included on that list, so I wonder if the shipping plugins work for our country, and if not, when you think that can be possible?

It doesn't need to be 'on the list' unless we want to include states in core. It will be open text field instead on checkout.

**Comment by bemvestir** [comment]
Yes. As Tiago Noronha mentioned you have post codes.
examples: 
1100-249 Lisboa
4000-996 Porto
9370-522 Madeira

**Comment by mikejolley** [comment]
Then there is no real value to including the list of states in core.

**Comment by bemvestir** [comment]
As long as this works for Portugal is ok.
Can you give an estimate of when I can use wocommerce table rate shipping for Portugal?

**Comment by tiagonoronha** [comment]
@bemvestir if you really need Districts, just use this plugin: https://pt.wordpress.org/plugins/portugal-states-distritos-for-woocommerce/

**Comment by bemvestir** [comment]
Hi Tiago,

Thanks for the share.
All I want is to use table rate shipping here in Portugal.

Can you give an estimate of when I can use wocommerce table rate shipping for Portugal?

**Comment by mikejolley** [comment]
Table rate shipping works with zip codes, so you can use it now.

**Comment by LyonBeton** [comment]
Hello,
I've issue with assigning specific areas of portugal to specific shipping zone in Woocommerce.
I tried to use postcodes as there is no district management.
It's not working but it may come from me.
Let me explain what I've tried so far.

For Islands from France ant Italy I use the postcodes to include or exclude them of shipping zones like this: 
![image](https://cloud.githubusercontent.com/assets/20840018/23654836/e43d09f2-0332-11e7-8b5a-91e8e13827b9.png)
It works well.

For portugal as I understood, there is only 4 digits for the postcodes.
So I tried to apply the same pattern: 
![image](https://cloud.githubusercontent.com/assets/20840018/23654898/1e2df7f2-0333-11e7-81cb-404c5b66cf48.png)
But It ain't working.
I've also tried a "wildcards" pattern like this:
00*
01*
02*
03*
04*
05*
06*
But it's not working too.

Did I made a mistake or is there an issue with Portugal in woocommerce ?
Thanks.

**Comment by ricardoaraujo330** [comment]
Hi!
I have an online shop in Portugal and I believe that adding 20 Portuguese districts in Woocommerce would be something that won't take you much time and will make a lot of woocommerce users happy for sure. I would love to avoid an extra plugin in order to have the Portuguese districts.

For other purposes like creating carrier labels, having the district make things easier.
Please consider adding this in the future.
Thank you

**Comment by claudiosanches** [comment]
@ricardoaraujo330 please start a new issue, and also if you could give us some examples we can revisit and it and maybe include the list of districts.

**Comment by estudioweblennyleon** [comment]
function wc_add_portugal_states( $states ) {

    $states['PT'] = array(
	    'AV' => 'Aveiro',
		'BJ' => 'Beja',
		'BR' => 'Braga',
		'BG' => 'Bragança',
		'CB' => 'Castelo Branco',
		'CI' => 'Coimbra',
		'EV' => 'Évora',
		'FR' => 'Faro',
		'GD' => 'Guarda',
		'LR' => 'Leiria',
		'LB' => 'Lisbon',
		'PT' => 'Portalegre',
		'PR' => 'Porto',
		'ST' => 'Santarém',
		'SB' => 'Setúbal',
		'VC' => 'Viana do Castelo',
		'VR' => 'Vila Real',
		'VU' => 'Viseu',
	);

    return $states;

}

add_filter( 'woocommerce_states', 'wc_add_portugal_states' );
