### ISSUE TITLE
When filtering by an attribute that is used as a variable, change variation defaults

### ISSUE THREAD

**Issue by BuggeringHell** [woothemes/woocommerce#10340]
It would be useful for quick browsing to select the default variations to what is filtered when browsing products. If the filtered attributes match all the variations, change the 'View Options' button to 'Add to Cart'

**Comment by mikejolley** [comment]
This wouldn't work for all users. It would force only one variation to be purchased from archives, without the ability to change options. If you want this tbh you're better off using a simple product.
