### ISSUE TITLE
Orders Screen - Hide Ship To address if same as Billing

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#10344]
It is good practice to verify orders that have different billing and shipping addresses to prevent fraud.

I think the Ship To column should say "Same as Billing" for orders where the shipping and billing addresses are the same. This makes it easier to visually scan for orders one must verify.

**Comment by WPprodigy** [comment]
Would this help? 

![](http://cld.wthms.co/12YxE/1eWDFhze+)

**Comment by lawkwok** [comment]
The goal would be to easily see if the shipping address is different from the billing. Hiding the billing address wouldn't accomplish that.

**Comment by WPprodigy** [comment]
Oh, I wasn't inferring you should hide it. Just asking if you have that enabled so you can compare if they are the same or not.

It wouldn't be too tough to do this, could just compare here: https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L682-L694. That whole page is going to change eventually though when orders are moved away from being CPT's

**Comment by mikejolley** [comment]
^ that. The address cannot be hidden, its needed. if you're concerned about fraud you can actually force shipping to billing address.

**Comment by lawkwok** [comment]
Sorry, I misunderstood your post @WPprodigy. I do have Billing checked in screen options. I didn't know only shipping is shown by default. In that case my suggestion is not as elegant.

I do think the in many cases the risk of fraud is low enough that preventing legitimate customers from shipping to a different address is off-putting. For stores with many orders a day, having the ability to easily identify "fraud cues" like inconsistent billing/shipping addresses would be helpful. However, since the order screen is being changed sometime down the road, we will see what happens :)

**Comment by WPprodigy** [comment]
You could also maybe give this extension a try: https://www.woothemes.com/products/woocommerce-anti-fraud/
