### ISSUE TITLE
Negative discounts not shown in order totals

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#10355]
Some people edit the prices to make them higher rather than lower (people selling meat/vegetables). This results in a negative discount in the backend, but this is not reflected in the order totals shown in the customer emails, because it only lists actual discounts ( $order->get_total_discount() > 0):
https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1855-L1860

changing this from > 0 to != 0 fixes the issue.

**Comment by mikejolley** [comment]
Negative discounts are not supported. Using the wording 'discount' would also be misleading if this was done by someone.. I feel there are more area where a -ve discount would break output.
