### ISSUE TITLE
Login and register from duplication

### ISSUE THREAD

**Issue by pacmandv** [woothemes/woocommerce#10358]
If add to my-courses page a few shortcodes register and login form duplicated.

I my case if I add in admin panel to my-courses page

```
[dt_sc_h2]Your active courses[/dt_sc_h2]

[sensei_user_courses orderby="name" order="asc" status="active"]


[dt_sc_h2]Your completed courses[/dt_sc_h2]

[sensei_user_courses orderby="name" order="asc" status="completed"]

```

I got login/register from twice.

**Comment by mikejolley** [comment]
This is the issue tracker for WooCommerce, not a support area for Sensei.
