### ISSUE TITLE
Filtering by atributes doesn't show reality

### ISSUE THREAD

**Issue by vivilopes** [woothemes/woocommerce#10351]
When using the widget to filter by atributes (color/size, etc), these atributes (which are part of a variable product) are going into count even if it are out of stock. 

The case is that when a product goes to out of stock (a variable one), the atribute keeps in there, on the variable product with ZERO stock. So, the filter keeps showing that product in the count. 
The only way to show the correct counts is deleting manually each atribute from each variable product. Which means that this would be impossible for even a little store. 

As it is a native solution from Woo I think it is an important thing to fix. Since I saw lots of places talking about this. 

Example: 
If we have a variable product with 2 sizes: P and M 
The size P are in stock, fine. It will show up in the filter count. 
The size M are not longer in stock. It will show up in the filter count. But if you click on this specific filter line, the product will be listed, but when its time to choose the size of the product to buy, it will only show you the size P. 
It means that the customer will have the hope to find that product in that respective size and will get frustrated because is no longer in stock. 

Hope there is a solution coming, would be REALLY nice! 
Thank you !

**Comment by mikejolley** [comment]
Will be fixed in 2.6 - we've made some optimisations to layered nav which also resolve this.

**Comment by vivilopes** [comment]
Thank you Mike!

**Comment by vivilopes** [comment]
Hello Mike, do you know when the 2.6 version will be available?

Thanks a bunch

**Comment by vivilopes** [comment]
NOTE: It wasn't fixed so far :(
