### ISSUE TITLE
Download links in emails broken after some days?

### ISSUE THREAD

**Issue by waschhausmedia** [woothemes/woocommerce#10353]
I just came across a weird issue with a WooCommerce installation of ours concerning downloadable goods.
For our customers the **download links** in their emails are broken after some time... The download_id in the URL provided in their emails are different than the one the in the database.
Although the links on their account page in the shop itself are working the ones in the mail are broken and just gives them a "invalid download" error message.
This actually seems to happen only to older orders (which are at least one day old). For now I can't tell if this happen over time ore *something* changed the download_ids for older orders.

Any idea what could cause this?

**Comment by mikejolley** [comment]
download_id is an MD5 hash of the file path. This remains the same unless you change the download file path by editing the product.

If the file path changes, old links in emails will break. Current links (on account pages) will function.

Hope this makes sense.

**Comment by waschhausmedia** [comment]
Makes perfect sense! Thank you very much!
