### ISSUE TITLE
Pass order object on payment completed

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#10357]
With the webhook **Order created** we pass the order object to the delivery URI, it is not the same if I use the custom webhook `woocommerce_payment_complete`. In some cases I need to use this webhook instead of Order created.

Can we add the order object there as well?

**Comment by claudiosmweb** [comment]
If it's a custom webhook, will send just the hook parameters and you can use the API to get more details.
And we can't include it into Order Updated, since it happens several times together and it's better control just when the payment is complete...
