### ISSUE TITLE
Variations js error

### ISSUE THREAD

**Issue by commercegurus** [woothemes/woocommerce#10367]
Hi folks,
This seems like a fairly basic use case so apologies if I've missed some elementary here.

Test case details:

Variable Product - 2 custom product attributes as follows:
http://i.imgur.com/zPtw3Ir.jpg

Variations configured as follows:
http://i.imgur.com/rhIzX4S.jpg

Frontend experiences a js console error when selecting a variation that doesn't exist:
e.g.
http://i.imgur.com/ENtWGcQ.jpg

For ease of copying: 
Console output is:
Uncaught TypeError: o.replace is not a function

I've recreated the issue in 2 separate WC2.5.2 installs just now. Here is a temporary example
http://factorytutorial.commercegurus.com/?product=variation-test-case

System Report

### WordPress Environment ###

Home URL: http://commercegurus.dev
Site URL: http://commercegurus.dev
WC Version: 2.5.2
Log Directory Writable: ✔  /srv/www/commercegurus/htdocs/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.7.10
PHP Version: 5.5.9-1ubuntu4.6
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.41
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.2

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /?page_id=7
Cart: #8 - /?page_id=8
Checkout: #9 - /?page_id=9
My Account: #10 - /?page_id=10

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Fifteen
Version: 1.0 – 1.4 is available
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Temp example works...

Variations need to be published and have prices, otherwise they won't show up.

**Comment by commercegurus** [comment]
Hey @mikejolley 

The js error is definitely happening on the temp example for me (Ubuntu 14.04 - Chrome 46.

Open your js console.
Go here:
http://factorytutorial.commercegurus.com/?product=variation-test-case

Size: Medium
Memory: 32GB
js error in the original report is thrown.

That variation exists (it was auto created per the original test case report) but I've not touched it yet.

Is the issue here that this variation is enabled by default when it is created but it is yet to be given a price/stock etc? If so, perhaps even if those records are auto created they should be not enabled by default?

I would think that a js error should be avoided?

**Comment by silicondales** [comment]
The Variation does not exist, yet - it doesn't have a price, nor stock?

**Comment by commercegurus** [comment]
@silicondales - it does exist but it doesn't have a price or stock. It wasn't manually created. It was created automatically by the "Create variations from all attributes" action after initially populating the attributes. I haven't touched that specific variation since that event. But it does indeed exist. So I can see I can simply uncheck "Enabled" which will remove the variation from the frontend completely and which then resolves the js issue. 

My point is that I believe these auto created variations shouldn't be "Enabled" by default which is what is triggering the knock on js error on the frontend - I've a customer with some items with 50-70 variations at the moment and this is causing a ton of confusion.

**Comment by mikejolley** [comment]
My console was clean.

Variations without prices are never loaded - its a required field.

**Comment by commercegurus** [comment]
Trust me - there's a console error there. And this Variation is 100% being displayed without a price. 
I've checked it from 3 machines here - Ubuntu, OSX and a Windows VM.

All checked logged out of WP and also in incognito windows to ensure no residual caches/sessions etc.
Again for clarity:
http://factorytutorial.commercegurus.com/?product=variation-test-case
Size: Medium
Memory: 32GB

**Comment by commercegurus** [comment]
Another example here
http://factorytutorial.commercegurus.com/?product=larger-variation
Color combo: Mocha earth / Black
Men's Size: 5

**Comment by mikejolley** [comment]
Can you turn on SCRIPT_DEBUG so its clear where it comes from.

**Comment by commercegurus** [comment]
Yip sure thing. Here you go

From here:
http://factorytutorial.commercegurus.com/?product=variation-test-case

Uncaught TypeError: $template_html.replace is not a function

http://i.imgur.com/JW2I2wN.jpg
http://i.imgur.com/bly4ycz.jpg

Let me know if you need something else / direct access etc.

**Comment by justinshreve** [comment]
@mikejolley It looks like `$template_html = unavailable_template;` needs to become `$template_html = unavailable_template();`. wp.template returns an executable function that returns the template. I can submit a PR for that if you want.
