### ISSUE TITLE
Discount issues with line_items - API

### ISSUE THREAD

**Issue by JaggedJax** [woothemes/woocommerce#10365]
The Order line_items in the API contain no field referencing any discounts. Despite this, the line_items.subtotal contains the price before any discounts and the line_items.total contains the price after the discount. This leaves no way to make these numbers add up.

There is a total_discount field on the order level, but just dividing that by the number of products doesn't make sense. Also it's not clear if the total_discount field is a summary of order_line discounts or if there could be additional order level discounts included as well.

Example from a real order:
```
  'line_items' =>
  array (
    0 =>
    array (
      'id' => 48,
      'subtotal' => '209.00',
      'subtotal_tax' => '0.00',
      'total' => '98.00',
      'total_tax' => '0.00',
      'price' => '9.80',
      'quantity' => 10,
      'tax_class' => NULL,
      'name' => 'Parent Kit with DVD',
      'product_id' => 1823,
      'sku' => 'THB505',
      'meta' =>
      array (
      ),
    ),
  )
```

They way it is now makes it impossible to audit the pricing information without making guesses and assumptions about the internals of WooCommerce. I realize WooCommerce is open source, but it's an unrealistic expectation when using an API to have to know all the internal calculations.

The best solutions seems to be either:
* add a discount field to the order_line
* never include discounts on order line level and always on the order total
* Clarify what makes up total_discount and split it into order level and item level discounts.

**Comment by mikejolley** [comment]
@JaggedJax 

> add a discount field to the order_line

Not required, subtract subtotal from total to get the discount per line

> never include discounts on order line level and always on the order total

Would make it impossible to show pre-discount prices when viewing orders

> Clarify what makes up total_discount and split it into order level and item level discounts.

Total is the total discount contained within the order. Splitting it is not necessary; the discounts over line items (remember, sub - total) will add up to this figure.

> There is a total_discount field on the order level, but just dividing that by the number of products doesn't make sense. Also it's not clear if the total_discount field is a summary of order_line discounts or if there could be additional order level discounts included as well.

@claudiosmweb can clarify this in the docs. It's just a sum of line item discounts.

FYI discounts have to be done at line item level for taxes to be calculated correctly. 

Let me know if any of that is unclear.

**Comment by JaggedJax** [comment]
Thank you for the clarification. I think it would be helpful to mention in the docs how to calculate the line  item discount amount as well as that the total is just a sum of them.

It is a simple calculation here, but I've made assumptions with other carts in the past and been bitten when there's some not well documented edge cases. I'm always wary of calculating price fields that aren't explicitly documented now.

**Comment by JaggedJax** [comment]
I have another example from a real order which is very confusing. I am able to calculate everything I need, but you have to work backwards from the total because none of the discount fields add up from what I can tell.

I guess my question here is what can be done to make sense of this information? Note the total, sub_total, total_discount, and fee_lines. How can this order have $0 total_discount and no order level discount if the negative fees don't come close to making up the difference.

Customer information removed from this order:
```
array (
  'id' => 102875,
  'order_number' => 102875,
  'created_at' => '2016-02-19T15:22:09Z',
  'updated_at' => '2016-02-19T15:22:09Z',
  'completed_at' => '2016-02-19T15:22:09Z',
  'status' => 'processing',
  'currency' => 'USD',
  'total' => '3.46',
  'subtotal' => '64.80',
  'total_line_items_quantity' => 2,
  'total_tax' => '0.00',
  'total_shipping' => '6.44',
  'cart_tax' => '0.00',
  'shipping_tax' => '0.00',
  'total_discount' => '0.00',
  'shipping_methods' => 'Standard (7-14 business days)',
  'payment_details' => 
  array (
    'method_id' => 'stripe',
    'method_title' => 'Credit',
    'paid' => true,
  ),
  'billing_address' => 
  array (
    'first_name' => 'XXX',
    'last_name' => 'XXX',
    'company' => '',
    'address_1' => 'XXX',
    'address_2' => '',
    'city' => 'XXX',
    'state' => 'XX',
    'postcode' => 'XXXXX',
    'country' => 'US',
    'email' => 'XXX',
    'phone' => 'XXX',
  ),
  'shipping_address' => 
  array (
    'first_name' => 'XXX',
    'last_name' => 'XXX',
    'company' => '',
    'address_1' => 'XXX',
    'address_2' => '',
    'city' => 'XXX',
    'state' => 'XX',
    'postcode' => 'XXXXX',
    'country' => 'US',
  ),
  'note' => '',
  'customer_ip' => 'XXXXX',
  'customer_user_agent' => 'XXX',
  'customer_id' => 0,
  'view_order_url' => 'XXXXX',
  'line_items' => 
  array (
    0 => 
    array (
      'id' => 392699,
      'subtotal' => '14.95',
      'subtotal_tax' => '0.00',
      'total' => '0.00',
      'total_tax' => '0.00',
      'price' => '0.00',
      'quantity' => 1,
      'tax_class' => NULL,
      'name' => 'XX1',
      'product_id' => 64,
      'sku' => 'XX1',
      'meta' => 
      array (
      ),
    ),
    1 => 
    array (
      'id' => 392700,
      'subtotal' => '49.85',
      'subtotal_tax' => '0.00',
      'total' => '9.95',
      'total_tax' => '0.00',
      'price' => '9.95',
      'quantity' => 1,
      'tax_class' => NULL,
      'name' => 'XX2',
      'product_id' => 23958,
      'sku' => 'XX2',
      'meta' => 
      array (
        0 => 
        array (
          'key' => 'upgrades',
          'label' => 'Upgrades',
          'value' => 'Double the power',
        ),
      ),
    ),
  ),
  'shipping_lines' => 
  array (
    0 => 
    array (
      'id' => 392703,
      'method_id' => '24163',
      'method_title' => 'Standard (7-14 business days)',
      'total' => '6.44',
    ),
  ),
  'tax_lines' => 
  array (
  ),
  'fee_lines' => 
  array (
    0 => 
    array (
      'id' => 392701,
      'title' => 'Campaign credit:
XXX',
      'tax_class' => NULL,
      'total' => '-7.95',
      'total_tax' => '0.00',
    ),
    1 => 
    array (
      'id' => 392702,
      'title' => 'Upgrade &amp; Rebate:
		XXX. This rebate gives you credit for that.
',
      'tax_class' => NULL,
      'total' => '-4.98',
      'total_tax' => '0.00',
    ),
  ),
  'coupon_lines' => 
  array (
  ),
  'customer' => 
  array (
    'id' => 0,
    'email' => 'XXX',
    'first_name' => 'XXX',
    'last_name' => 'XXX',
    'billing_address' => 
    array (
      'first_name' => 'XXX',
      'last_name' => 'XXX',
      'company' => '',
      'address_1' => 'XXX',
      'address_2' => '',
      'city' => 'XXX',
      'state' => 'XX',
      'postcode' => 'XXXXX',
      'country' => 'US',
      'email' => 'XXX',
      'phone' => 'XXX',
    ),
    'shipping_address' => 
    array (
      'first_name' => 'XXX',
      'last_name' => 'XXX',
      'company' => '',
      'address_1' => 'XX',
      'address_2' => '',
      'city' => 'XXX',
      'state' => 'XX',
      'postcode' => 'XXXXX',
      'country' => 'US',
    ),
  ),
)
```

This order was pulled from a 2.4.7 install that we only have API access to, not direct access.

**Comment by tahirhameed** [comment]
hello 

i am facing some problem in woocommerce order create api can you guide to fix my issue 

when i post 
line_items array  


                                    

@"line_items": @[ @{ @"product_id": @380, @"quantity": @1, @"meta_data": @[ @{ @"key": @"Booking Date", @"value": @"July 05, 2017" }, @{ @"key": @"Booking Time", @"value": @"4:30 pm" }, @{ @"key": @"Duration", @"value": @"45 minutes"} ] } ],

{

    "code": "woocommerce_rest_authentication_error",

    "message": "Invalid signature - provided signature does not match.",

    "data": {

        "status": 401

    }


}



this error returing from woocommerce server but when i post without line_items array its working fine 



waiting for positive response
