### ISSUE TITLE
Issue with authentication consumer key or consumer secret invalid

### ISSUE THREAD

**Issue by assislucas** [woothemes/woocommerce#10362]
I'm creating credentials using the endpoint **_/wc-auth/v1/authorize_** with **_scope=read_write_** most times the consumer key and secret that I get are valid, but a couple of times I get consumer key or consumer secrets that are invalid when I try to use them later.

Is there an issue with the key generation through this endpoint?

The credentials that I get from the authorize endpoint I'm using with the [python wrapper](https://github.com/woothemes/wc-api-python) is code like this:
```python
wcapi = API(
    url=  shop_url,
    consumer_key= key,
    consumer_secret= secret
)
response = wcapi.get("orders?page=1")
# Then response.text is {"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Secret is invalid"}]}
#  or {"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Key is invalid"}]}
```

**Comment by claudiosmweb** [comment]
Closing in favor of https://github.com/woothemes/wc-api-python/issues/11
