### ISSUE TITLE
Price Filter + Tax Rates - displaying incorrect products.

### ISSUE THREAD

**Issue by SS88UK** [woothemes/woocommerce#10371]
Hello.

I am using the price filter.

I currently have VAT @ 20% for GB. All products in the shop are displayed inc. VAT.

Min price: 10
Max price: 11

The SQL query produced is:

```
SELECT DISTINCT ID, post_parent, post_type
FROM wp_posts 
INNER JOIN wp_postmeta pm1
ON ID = pm1.post_id 
INNER JOIN wp_postmeta pm2
ON ID = pm2.post_id 
WHERE post_type IN ( 'product', 'product_variation' ) 
AND post_status = 'publish' 
AND pm1.meta_key IN ('_price') 
AND pm1.meta_value BETWEEN 8.333300
AND 9.166700 
AND pm2.meta_key = '_tax_class' 
AND pm2.meta_value = ''
```

**This produces 0 results.**

When I **turn off** VAT in the shop i.e. "Display Prices in the Shop: Excluding tax"

The SQL query produced is:

```
SELECT DISTINCT ID, post_parent, post_type
FROM wp_posts 
INNER JOIN wp_postmeta pm1
ON ID = pm1.post_id 
WHERE post_type IN ( 'product', 'product_variation' ) 
AND post_status = 'publish' 
AND pm1.meta_key IN ('_price') 
AND pm1.meta_value BETWEEN 10
AND 11
```

This produces the correct products.

Is this a bug or am I doing something wrong?

**Comment by mikejolley** [comment]
Are the prices defined including or excl. vat?

**Comment by SS88UK** [comment]
The prices have been inserted into WooCommerce ex. VAT.

**Comment by mikejolley** [comment]
Ok. This search works on the stored price. So say you've input a price of £10 and you're showing prices inc tax. It will be shown as £12.

User wants to filter that price, so they input a min of 12. They should expect this item to show up, but as you know 12 > actual 10 price.

So it takes 20% off the 12, searching for 9.6. I think thats the problem - the removal of tax is using the wrong calc. Checking now.

**Comment by SS88UK** [comment]
Yes that is correct. Some queries (we have 2k+ products) return a handful of results but not ALL that should show. When we turn OFF displaying of tax all the products that we expected to show, do show.

**Comment by mikejolley** [comment]
Just checked master and 2.5 and it worked as expected https://dl.dropboxusercontent.com/s/d28l7hqoh9s1qvj/2016-02-18%20at%2013.19.png?dl=0

Product price to try?

**Comment by SS88UK** [comment]
I have a product:

Price: 83.03 (ex vat)
Inc VAT: 99.64 (20%)

**Slider ex VAT**

min: 81
max: 84 (largest it goes)

1 result

**Slider inc. VAT**
min 81:
max: 101 (largest it goes)

no results.

**Slider inc. VAT**
min 10:
max: 101 (largest it goes)

no results.

**Slider inc. VAT**
no min / max

all results.

How do I debug more?

**Comment by mikejolley** [comment]
Looks improved in master since layered nav rewrite, but there are still oddities we cannot really work around. 

When you do the filter, you're filtering price. The query does not know the 'inc vat' price and can only guess based on POTENTIAL min and max, which could vary based on 'taxable' and tax class settings per product. This is a limitation when displaying prices differently to how they are stored.

**Comment by SS88UK** [comment]
I think this can be closed as it might be our fault.

We have used an import script which has imported all the products correctly but may be missing 'tax class'?

This part of the SQL makes it look like we have no products:

AND pm2.meta_key = '_tax_class' 
AND pm2.meta_value = ''

However when we update a few products manually i.e. just press the update button it's placing the meta key value '_tax_class' into the database therefore producing the correct display of results.

**Comment by mikejolley** [comment]
Possibly related. Above still applies, but I cannot find an efficient way to work around.

**Comment by SS88UK** [comment]
OK - well I'm happy bulk editing the products to set it's tax class etc and this seems to be producing near enough good results for us! :)
