### ISSUE TITLE
Callback for JSOP XHR

### ISSUE THREAD

**Issue by lenivene** [woothemes/woocommerce#10376]
Because not there "callback" in api?

Example: `myCallBack({"products":[]});`

**Comment by lenivene** [comment]
It is written -> https://woothemes.github.io/woocommerce-rest-api-docs/?shell#jsonp-support

Example for use:
```javascript
$.ajax({
    url: "https://YOURDOMAIN.COM/wc-api/v3/products/?_jsonp=products",
    dataType: "jsonp",
    jsonpCallback:"products"
})
```

Congratulations for me xD! Yeh, I'm stupid!

**Comment by claudiosmweb** [comment]
:stuck_out_tongue_winking_eye:
