### ISSUE TITLE
 Include Portugal on country codes list #10346 

### ISSUE THREAD

**Issue by bemvestir** [woothemes/woocommerce#10380]
Hi,

Since issue #10346 was closed and I did not get any comments to my answer two days ago, I'm reopening a new one:

Thanks for your reply.

I'm no wordpress, php, ...expert, far from it.
I'm just a fashion blogger, and all I want is to have the shipping functionality to work full and perfect also for Portugal.

So I see that there are two aspects to be considered, namely:

1 - Portugal is not yet included on that list, so I wonder if the shipping plugins work for our country, and if not, when you think that can be possible?

2 - For regular mail (letters) we can consider that there is only one rate for the main land and islands (the Azores and Madeira) and it varies of course depending on the weight. But the point is a eccommerce store do not send regular mail but packages with different types of orders and so there's different type of pricing, according to the local. Tiago Noronha as a Portuguese native easily understand the pricing of our main carrier in Portugal - CTT, if he checks these pages - http://www.ctt.pt/correio-e-encomendas/enviar-correio/opcoes-de-envio/encomendas.html#panel2-1 and http://www.ctt.pt/correio-e-encomendas/ajuda/zonas-encomendas.html.

So I understand that localities, mean districts, are necessary for the proper functioning and track different prices, depending on the zone of Portugal we are shipping to and from.

I hope I have clarified a little better this question.

Kind Regards

**Comment by mikejolley** [comment]
Do not reopen duplicate issues.
