### ISSUE TITLE
Checkout Form Is Validating Country and State Select On Page Load

### ISSUE THREAD

**Issue by Bo-FT** [woothemes/woocommerce#10383]
EXPLANATION OF THE ISSUE

The checkout form is validating Country and State selects on page load. This is causing the State to show as invalid with a red error label on page load. The Country select may also show a green box around it/green label if a theme other than the default is used. All other fields do not validate until focus out. State is still marked invalid even when a single country is used.

After further investigation this issue is being caused by a call to the select change in checkout.js on line 106:

init_checkout: function() {
        **$( '#billing_country, #shipping_country, .country_to_state' ).change();**
        $( document.body ).trigger( 'update_checkout' );
}

And a call to the select change in country-select.js on line 150:

$(function() {
        **$( ':input.country_to_state' ).change();**
});

commenting out these two lines corrects the issue without breaking the form.

STEPS TO REPRODUCE THE ISSUE

Issue occurs on clean WooCommerce/WP install. Latest versions with default theme.

SYSTEM STATUS REPORT

WordPress Environment
Home URL:		http://localhost/wpbase
Site URL:		http://localhost/wpbase
WC Version:		2.5.2
Log Directory Writable:		✔ /Applications/MAMP/htdocs/wpbase/wp-content/uploads/wc-logs/
WP Version:		4.4.2
WP Multisite:		–
WP Memory Limit:		256 MB
WP Debug Mode:		–
Language:		en_US
Server Environment
Server Info:		Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:		5.6.10
PHP Post Max Size:		128 MB
PHP Time Limit:		180
PHP Max Input Vars:		1000
SUHOSIN Installed:		–
MySQL Version:		5.5.42
Max Upload Size:		128 MB
Default Timezone is UTC:		✔
fsockopen/cURL:		 ✔
SoapClient:		 ✔
DOMDocument:		 ✔
GZip:		 ✔
Multibyte String:		 ✔
Remote Post:		 ✔
Remote Get:		 ✔
Database
WC Database Version:		2.5.2
woocommerce_sessions	 	✔
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (1)
WooCommerce	 	by WooThemes – 2.5.2
Settings
Force SSL:		–
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		✔
API Version:		3.1.0
WC Pages
Shop Base:		#5 - /shop/
Cart:		#6 - /cart/
Checkout:		#7 - /checkout/
My Account:		#8 - /my-account/
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Twenty Sixteen
Version:		1.1
Author URL:		https://wordpress.org/
Child Theme:		✕ – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		✔
Templates
Overrides:	 	–

**Comment by mikejolley** [comment]
Appears fine in latest. To test, I forced Gelocation result to CL (chile) which has a required state input.

The box did not have a red border until I clicked inside and clicked out.

The change() events are required to setup the form's correct initial state based on the default selected country.

**Comment by Bo-FT** [comment]
The box isn't showing red, the label above the State select is showing red.
I've tried multiple installs on multiple machines here in the office and
always get the same result. Even setting the address to the default shop
location still results in a red label for the state select.

On Tue, Feb 23, 2016 at 3:24 AM, Mike Jolley <notifications@github.com>
wrote:

> Appears fine in latest. To test, I forced Gelocation result to CL (chile)
> which has a required state input.
>
> The box did not have a red border until I clicked inside and clicked out.
>
> The change() events are required to setup the form's correct initial state
> based on the default selected country.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/10383#issuecomment-187659879>
> .
>



-- 
*Bo Carlson*
Interactive Developer
The Fiction Tribe

bo@thefictiontribe.com

**Comment by mikejolley** [comment]
Neither for me. Is it a particular browser?

**Comment by Bo-FT** [comment]
I'm on OSX El Capitan. Happens in Firefox, Chrome, and Safari. The
following classes are being applied to the label for select#billing_state:

form-row form-row form-row-first address-field validate-state
woocommerce-invalid woocommerce-invalid-required-field validate-required

It's not adding the red box around the input, just changing the label
color. It's the only required field on my installs that is doing this. When
I kill that initial change function the page loads and everything works
correctly.

I'm not sure why that change is really being fired since by default if your
country is USA then the state box does not have a default value selected on
page load. There's really no reason to fire this change event unless both
the country and state have values. It seems odd that other parts of the
program would rely on data that may not be set on page load. Really it
should check and only fire on page load if both country and state have a
value if country and state are required.

I can send screenshots if you need them.

Thanks,
Bo

On Tue, Feb 23, 2016 at 10:55 AM, Mike Jolley <notifications@github.com>
wrote:

> Neither for me. Is it a particular browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/10383#issuecomment-187840706>
> .
>



-- 
*Bo Carlson*
Interactive Developer
The Fiction Tribe

bo@thefictiontribe.com

**Comment by Bo-FT** [comment]
Sorry the classes are being applied to the form-row for select#billing.

Bo

On Tue, Feb 23, 2016 at 11:08 AM, Bo Carlson <bo@fictiontribe.com> wrote:

> I'm on OSX El Capitan. Happens in Firefox, Chrome, and Safari. The
> following classes are being applied to the label for select#billing_state:
>
> form-row form-row form-row-first address-field validate-state
> woocommerce-invalid woocommerce-invalid-required-field validate-required
>
> It's not adding the red box around the input, just changing the label
> color. It's the only required field on my installs that is doing this. When
> I kill that initial change function the page loads and everything works
> correctly.
>
> I'm not sure why that change is really being fired since by default if
> your country is USA then the state box does not have a default value
> selected on page load. There's really no reason to fire this change event
> unless both the country and state have values. It seems odd that other
> parts of the program would rely on data that may not be set on page load.
> Really it should check and only fire on page load if both country and state
> have a value if country and state are required.
>
> I can send screenshots if you need them.
>
> Thanks,
> Bo
>
> On Tue, Feb 23, 2016 at 10:55 AM, Mike Jolley <notifications@github.com>
> wrote:
>
>> Neither for me. Is it a particular browser?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/woothemes/woocommerce/issues/10383#issuecomment-187840706>
>> .
>>
>
>
>
> --
> *Bo Carlson*
> Interactive Developer
> The Fiction Tribe
>
> bo@thefictiontribe.com
>



-- 
*Bo Carlson*
Interactive Developer
The Fiction Tribe

bo@thefictiontribe.com

**Comment by mikejolley** [comment]
yeah not seeing it. If you have a live example I'll check.

**Comment by jamesinglis** [comment]
I am experiencing a similar problem on a site currently in development.

I have coded around this by adding the following into a custom JS file:

`$(document.body).on('init_checkout', function (event) {
        setTimeout(function () {
            $('#billing_state_field').removeClass('woocommerce-invalid');
        }, 2000);
    });`

It's hacky and the State field still flashes red until the custom code kicks in 2 seconds after the 'init_checkout' event fires, but it puts a band-aid on the problem!

I hope this can be fixed properly in a future release.

**Comment by ksere** [comment]
Hi,
I have come accross the same issue described here.
Using WP 4.5.3, WC 2.6.1

To reproduce try this: set _Default Customer Location_  to _No location by default_
Visit the shop using a clean browser (no cache/cookies), add products to cart and visit checkout. You should see the Country field with 'Select a country...' in it.
At this point the 'woocommerce-invalid woocommerce-invalid-required-field' classes are applied to the Country's parent .form-row.

This happens also with Storefront, but it has no special style for an invalid select field.

**Comment by nigel-wells** [comment]
I also have the same issue in the current version (2.6.4). As a work around I followed a similar vein as described above but instead it runs every millisecond and has a timeout:
```
jQuery(document.body).on('init_checkout', function (event) {
    // Set an automatic timmer to run every millisecond until it's fixed
    var regionTimer = setInterval(function() {
        // Check if the invalid field has been triggered yet
        if(jQuery('#billing_state_field,#shipping_state_field').hasClass('woocommerce-invalid')) {
            // Reset the required classes - remove some and add one
            jQuery('#billing_state_field,#shipping_state_field')
                .removeClass('woocommerce-invalid')
                .removeClass('validate-state')
                .removeClass('woocommerce-invalid-require-field')
                .addClass('validate-required')
            ;
            clearInterval(regionTimer);
        }
    }, 1);
    // Set a timeout on this just in case the above is never triggered depending on the setup
    setTimeout(function() {
        clearInterval(regionTimer);
    }, 5000);
});
```
There is a slight flicker of the red if you happen to be down that far on the page but it works reasonably well.

**Comment by snowbreeze** [comment]
The disabled goes away but still dropdown doesnt open, happens only in iphones

**Comment by nathanegraham** [comment]
I'm also seeing this on Country and State on WP 4.6.1 and current version of Woocommerce on the checkout page. Country and State labels are red.

**Comment by retroriff** [comment]
I have the same issue since I added a default blank value:

```
add_filter( 'default_checkout_state', 'default_checkout_state' );
function default_checkout_state() {
  return null;
}
```

**Comment by PetrusHenrique** [comment]
I'm having the same problem It only happens in SAFARI and IOS in Safari and Chorme. Even after selecting the state it remains unvalidated.

**Comment by bluantinoo** [comment]
Same here, as @retroriff I used the default_checkout_state filter not to have a default state in the dropdown as page loads (cause some users just don't change it). live example: fortunatiantonio.it

**Comment by sethwhitaker** [comment]
same issue, state fields are validating by default on checkout page load

**Comment by ksere** [comment]
I am not sure if notifications are sent to participants on a closed topic..

**Comment by retroriff** [comment]
@ksere Yes, we receive them.

**Comment by FreeRiderNSK** [comment]
Solved this problem? Help me, please.

**Comment by SoLoGHoST** [comment]
I'm having the same problem but this is happening on a custom field that I created, since I need multiple fields to be sent with an array and do not EVER want to use the multiselect select element, simply because it looks terrible and people are not used to using it.  So I setup a multicheck field, but even though it is properly handled in php and validating it, the javascript is setting invalid on the parent everytime I try to submit a checkout (if there are other fields that are empty that are required).

Can confirm this problem with the following code:
`add_filter('woocommerce_form_field_multicheck', 'infraexchange_multicheck_handler', 10, 4);
function infraexchange_multicheck_handler($field, $key, $args, $value)
{
	$options = '';

    if (!empty($args['options']))
    {
        foreach ($args['options'] as $option_key => $option_text)
        {
            $options .= '<label><input name="' . $key . '[]" type="checkbox" value="' . $option_key . '" ' . checked(!empty($value) && in_array($option_key, $value), true, false) . ' /> ' . $option_text . '</label>';
        }

        $required = !empty($args['required']) ? ' <abbr class="required" title="required">*</abbr>' : '';

        $field = '<p class="form-row ' . implode( ' ', $args['class'] ) .'" id="' . $key . '_field">
            <label for="' . $key . '" class="' . implode( ' ', $args['label_class'] ) .'">' . $args['label'] . $required . '</label>
            ' . $options . '
        </p>';
    }

    return $field;
}


add_action('woocommerce_before_order_notes', 'infraexchange_before_order_notes', 10, 1);

function infraexchange_before_order_notes($checkout)
{

	echo '
		<h3>', __( 'Account Details', 'infraexchange' ), '</h3>';

	$fields = $checkout->get_checkout_fields('profile');

	if (!empty($fields))
	{
		foreach ( $fields as $key => $field ) {
			woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
		}
	}

}

add_filter('woocommerce_checkout_fields' , 'infraexchange_checkout_fields', 10, 1);

function infraexchange_checkout_fields($fields)
{
	$fields['profile'] = array(
		'companytype' => array(
			'type' => 'select',
			'label' => __('Company Type', 'woocommerce'),
			'required' => true,
			'placeholder' => __('Select a Company Type', 'woocommerce'),
			'clear' => false,
			'options' => array(
				'architectural_engineering' => 'Architectural & Engineering',
				'construction_general' => 'Construction – General',
				'construction_subcontracting' => 'Construction – Sub Contracting',
				'professional_services' => 'Professional Services',
				'turnkey_services_construction' => 'Turnkey Services & Construction',
				'equipment_sales_rental' => 'Equipment Sales & Rental',
				'transportation_shipping' => 'Transportation & Shipping',
				'manufacturing_raw_materials' => 'Manufacturing – Raw Materials',
				'manufacturing_finished_products' => 'Manufacturing – Finished Products',
				'value_added_reseller' => 'Value Added Reseller',
				'manufacturers_representatives' => 'Manufacturers&rsquo; Representatives',
				'supplier_distributor_wholesaler' => 'Supplier, Distributor or Wholesaler',
				'investor_financing' => 'Investor or Financing'
			),
			'class' => array('form-row-first')
		),
		'industry' => array(
			'type' => 'multicheck',
			'label' => __('Industry', 'infraexchange'),
			'required' => true,
			'clear' => true,
			'options' => array(
				'oil_gas' => 'Oil & Gas',
				'regulated_municipal_utility' => 'Regulated or Municipal Utility',
				'renewable_energy' => 'Renewable Energy',
				'wireless_telecommunications' => 'Wireless Telecommunications',
				'fiber_data_telecommunications' => 'Fiber and Data Telecommunications',
				'industrial_commercial_residential_construction' => 'Industrial, Commercial and Residential Construction',
				'other' => 'Other'
			),
			'class' => array('form-row-last')
		)
	);

	return $fields;
}`

**Comment by shaunjc** [comment]
I'm encountering the issue myself. It seems to occur for specific countries (I'm able to easily replicate it for Australia) when no state is selected by default, i.e. new customer or guest checkout.

To get around the issue, I added a listener to remove the validation classes each time the state fields are populated.

    $( document.body ).on( 'country_to_state_changed', function( e, country, $wrapper ){
        $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' )
            .closest('p.form-row')
                .removeClass('woocommerce-invalid woocommerce-invalid-required-field');
    } );

**Comment by ksere** [comment]
Fixed with #20655

**Comment by retroriff** [comment]
@ksere Sorry, I get the same validation. My error occurs when province value is left blank in WC settings and country = Spain:

![image](https://user-images.githubusercontent.com/2946239/46932842-2c14e100-d05a-11e8-9c70-8608f5eec888.png)

**Comment by retroriff** [comment]
@ksere You are right. Sorry, I didn't updated it. Now I checked it with 3.5.0-rc1 and it works as expected. However if you switch to a different country, and switch back to Spain, the Province field is validated, and a "woocommerce-validated" class is added. I think that it should not be validated before there's a "focus out" or submit action.

![image](https://user-images.githubusercontent.com/2946239/46950139-69926200-d08c-11e8-8c40-79bc80dd33cc.png)
