### ISSUE TITLE
My downloads on My Account page

### ISSUE THREAD

**Issue by dare-devil-arrives** [woothemes/woocommerce#10388]
If you have bought same downloadable product in different orders, then on my account page you can see only one same download link for all the orders.
Ideally, even if same product is purchased, the download link visible should be different for different orders, if possible with Order numbers mentioned.

**Comment by mikejolley** [comment]
If its the same file, why would you need this? When the link expires, the next order's link will show.

**Comment by dare-devil-arrives** [comment]
Ya I agree with you. But I have a custom plugin that shows license keys for available downloads. Since, woocommerce shows only one download link for multiple orders having same product, I had to custom code to show all the available downloads and then their corresponding license keys.

Just thought this should be available in core :)

**Comment by dare-devil-arrives** [comment]
Thanks Mike +1:
