### ISSUE TITLE
Show pagination on My Account for orders.

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10387]
The new my account tabs for orders should paginate results.

What do you think @claudiosmweb ?

**Comment by claudiosmweb** [comment]
@mikejolley I think that it's done already and even we've talked about it too :stuck_out_tongue_winking_eye:

![screenshot from 2016-02-20 00-31-56](https://cloud.githubusercontent.com/assets/1264099/13193954/5d7906f0-d769-11e5-82ab-f321d3061071.png)

I keep the number of items from the old "My Last Orders":
https://github.com/woothemes/woocommerce/blob/master/includes/wc-account-functions.php#L162

**Comment by mikejolley** [comment]
:+1:

**Comment by PareshRadadiya** [comment]
Pagination under My Account > Orders not working properly. It keeps showing me the same ten orders no matter how I try to page through them. don't know what is going wrong.

**Comment by mrmu** [comment]
@PareshRadadiya I thought that is a new issue and I've open a new issue. 
You can add the below code in functions.php to correct the issue until the problem fixed, hope it can help you: 

add_filter( 'woocommerce_my_account_my_orders_query', 'fix_wp_get_orders_pag_issue', 10, 1 ); 
function fix_wp_get_orders_pag_issue( $args ) { 
  if (isset($args['page'])) {
    $args['paged'] = $args['page'];
  }
  return $args; 
};

**Comment by PareshRadadiya** [comment]
Excellent. Thanks for sharing your solution. 🙂
