### ISSUE TITLE
WC_Product->get_related( $limit ) is incompatible with $posts_per_page -1 concept

### ISSUE THREAD

**Issue by lkraav** [woothemes/woocommerce#10398]
2.5.2

I have a store where querying related products is known not to cause performance issues with `-1`, but I'd rather avoid magic numbers like `99`.

`array_slice()` call at the bottom of `WC_Product::get_related()` with `posts_per_page => -1` is doomed to return weirdness, because "If length is specified and is negative then the end of the removed portion will be that many elements from the end of the array." [1]

Thoughts on how to improve?

PS the whole magic shuffling, randomizing etc inside `get_related()` feels like overdoing it in general, but that's another topic. I'll plug my own if need be. 

[1]: http://php.net/array_splice

**Comment by mikejolley** [comment]
The whole magic shuffling etc is to allow the related query to be cached for performance. 

Will add comment to state > 0 is required. The assumption that this function should be compatible with $posts_per_page is false.
