### ISSUE TITLE
Layered Filters Count incoorect

### ISSUE THREAD

**Issue by fused7** [woothemes/woocommerce#10395]
I have an issue with my site where the number of products listed does not match the count shown in the woocommerce layered filters widget. For instance, I have over 500 items in department "Boys" but it only shows 12 count on the widget. This has been stuck on 12 for a while now. This is the same case with all my attribute filters. 

This issue has been in place since the previous version of woocommerce and is still present post update. 

I have been looking for a solution for some time now and tried the following several times already. 
I have gone to Woocommerce -> System Status -> Tools and recounted terms and cleared transients.  
I have added products with all terms to trigger a recount, but no luck. 
I have tried commenting out the following in the wc-terms-functions.php
function wc_change_term_counts( $terms, $taxonomies ) {
	if (/* is_admin() || */ is_ajax() ) {
		return $terms;
	}

Nothing works. 

I have tries YITH ajax filter and it seems to pull the correct count in the widget no problem. Its a slow filter option for me so I don't want to use that one really. 

Any ideas on how to get this to show the correct count?

site is kidsfashionbrands.com -> click on Shop Kids Fashion to see this issue

**Comment by mikejolley** [comment]
WooCommerce > System Status > Tools > Recount terms.

Note that this can also be cached. This is also improved in master so 2.6 will include improved/more reliable counts.
