### ISSUE TITLE
[Feature Request] Filter to change email introductory phrase

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#10394]
In WooCommerce there is are hooks for everything which is great because I don't need to override templates (making updates safe and easy).

Now I would just like to override the text in customer processing order emails _depending_ on what the customer has actually ordered. This is [just 2 sentences](https://github.com/woothemes/woocommerce/blob/master/templates/emails/customer-processing-order.php#L28):
```
<p><?php _e( "Your order has been received and is now being processed. Your order details are shown below for your reference:", 'woocommerce' ); ?></p>
```

But while there are email filters for everything like  `woocommerce_email_subject_customer_completed_order` or `woocommerce_email_heading_customer_completed_order` there is none for this task.

There is this simply 2-sentences text in every email below the heading. Could please a filter be added to easily customize this easily from a child theme? I do not want to override the whole email template just because I need to change a sentence ;)

Maybe `woocommerce_email_introductory_phrase_customer_completed_order` or just `woocommerce_email_phrase_customer_completed_order` would do...

**Comment by mikejolley** [comment]
Wrapping all strings in WC with filters could quite easily get out of control. Use gettext filter instead - this executes for all strings that are localised.
