### ISSUE TITLE
Permalink issue with "My Account" page shortcode

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10390]
@claudiosmweb If the permalink common settings is set to plain then My Account page shortcode is not working. Additionally, I have test others WC Pages and they works perfectly.

**Comment by mikejolley** [comment]
Version?

**Comment by mikejolley** [comment]
Master. Please include version info in future (there is a new issue template!)

**Comment by shivapoudel** [comment]
Okies :)
