### ISSUE TITLE
[API doc] Looking up hooks is hindered by truncated hook names

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#10393]
I regularly use the [hooks API reference](https://docs.woothemes.com/wc-apidocs/hook-docs.html) to look up or search. Certain hooks are truncated in the API: `woocommerce_email_enabled_`, or `woocommerce_email_heading_' (basically all that end with an underscore on that page). 

Technically, this is because in [code](https://docs.woothemes.com/wc-apidocs/source-class-WC_Email.html#261) it is like:
`return apply_filters( 'woocommerce_email_heading_' . $this->id,  ...);`

Anyway, when trying to look up all filters/actions available for "completed_orders" emails then this is really annoying. Is there a way to fix the automatic generated API docs? Maybe some kind of API doc annotations that could be done in code?

**Comment by jnachtigall** [comment]
@mikejolley I think there is more missing, e.g. `woocommerce_order_status_completed_notification`  (https://docs.woothemes.com/wc-apidocs/source-class-WC_Email_Customer_Completed_Order.html#39) action is also not at https://docs.woothemes.com/wc-apidocs/hook-docs.html Same goes for all the other actions in the other email classes (`woocommerce_order_status_pending_to_cancelled_notification`)

**Comment by mikejolley** [comment]
The docs have not been updated yet with the new code.

**Comment by shivapoudel** [comment]
@mikejolley can you also allow the download link for the API Docs through `apigen.neon` :)
