### ISSUE TITLE
'woocommerce_api_save_product_variation' doesn't return $variation

### ISSUE THREAD

**Issue by iamswain** [woothemes/woocommerce#10407]
Hi,

I might be doing something wrong, but to me it seems that the hook `woocommerce_api_save_product_variation` doesn't returned the $variation variable correctly.

I have the following code:

```
function custom_fields_product_variation_api( $variation_id, $menu_order, $variation ) {
  if ( isset( $variation ) ) {
    update_post_meta( $variation_id, 'gtin_variable', 'set' );
  } else {
    update_post_meta( $variation_id, 'gtin_variable', 'not set' );
  }
}
add_action( 'woocommerce_api_save_product_variation', 'custom_fields_product_variation_api', 10, 2 );
```

$variation_id is working as intended, so is the $menu_order, only $variation isn't being set. Is this a mistake by me or did I just discover a bug?

**Comment by mikejolley** [comment]
It's a derp by you :) You're passing 2 args via your action, but it needs to be 3.

`
add_action( 'woocommerce_api_save_product_variation', 'custom_fields_product_variation_api', 10, 3 );
`

**Comment by iamswain** [comment]
Thank you @mikejolley. I go hide in a corner now.
