### ISSUE TITLE
REST API : Variation ID in order line items

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#10403]
When a variable product is in order line items, the `variation_id` is missing in the detail. (Whe can see product id, variation meta, but the variation id is missing).

**Comment by mikejolley** [comment]
I see its missing in current line item spec @claudiosmweb, but I'm including it in my new spec in https://github.com/woothemes/woocommerce/pull/10259 branch so it will be there in the next major API update.
