### ISSUE TITLE
State input box does not work correctly after ajax reload

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10408]
Steps to reproduce:

1. Set your country to "Germany" in the calculator
2. Reload cart page.
3. Switch the shipping method to cause an ajax reload of the shipping/totals area.
4. Open calculator and select "United Kingdom".

Result: No state box appears.

**Comment by coderkevin** [comment]
Note: Clicking the "Update Totals" button is a workaround, as it shows the state/county selection afterwards.
