### ISSUE TITLE
CSS button conflict

### ISSUE THREAD

**Issue by turtlepod** [woothemes/woocommerce#10401]
- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [x] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

woocommerce CSS for button is like this:
```css
.woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button
```

this will target **all buttons** elements in woocommerce page (.woocommerce is in body tag). I think it's better to add class to all "woocommerce buttons" and "input" element.
so it will not effect all buttons and input such as search form etc.

so, for better theme compat the css (something like this):

```css
#input#submit.woocommerce-input, a.button.woocommerce-button, button.button.woocommerce-button, input.button.woocommerce-button
```

make sense?

STEPS TO REPRODUCE THE ISSUE

1. install and activate woocommerce
2. go to any product page/wooc page.

SYSTEM STATUS REPORT

```

### WordPress Environment ###

Home URL: http://dev.play
Site URL: http://dev.play
WC Version: 2.5.2
Log Directory Writable: ✔  C:\xampp\htdocs\_play\dev.play/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14
PHP Version: 5.6.14
PHP Post Max Size: 750 MB
PHP Time Limit: 5000
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.5
Max Upload Size: 750 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.2

### Settings ###

Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #1833 - /shop/
Cart: #1834 - /cart/
Checkout: #1835 - /checkout/
My Account: #1836 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: NokoNoko
Version: 1.0.0
Author URL: http://shellcreeper.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: Not Declared

### Templates ###

Overrides: –

```

**Comment by mikejolley** [comment]
Removing button styles will cause breakage for themes using those classes. Template files in WC would also need changing to add the new class.

Prefixing class names is the best way, however, this should be done as part of https://github.com/woothemes/woocommerce/issues/9055 due to the breaking nature of the change.

**Comment by turtlepod** [comment]
I don't think it cause breakage (all will probably still works), all theme have default input design, it will just fallback to that. but it's not going to be a pretty update :(
I understand, it is risky. specially when involving tons of ecommerce sites.
I guess i'll wait :)

thank you for your fast reply.
