### ISSUE TITLE
Product Add-Ons: woocommerce_order_item_display_meta_value  returns empty value .

### ISSUE THREAD

**Issue by sanjugem** [woothemes/woocommerce#10418]
- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [ ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.

EXPLANATION OF THE ISSUE

The attributes added by [Product Add-Ons plugin](https://www.woothemes.com/products/product-add-ons/) failed to show in front view order detail list. Keys are displayed but values remains empty . Problems seems in class-wc-order-item-meta.php in line with 
$formatted_meta[ $meta_id ] = array(
					'key'   => $meta->key,
					'label' => wc_attribute_label( $attribute_key, $this->product ),
					'value' =>apply_filters( 'woocommerce_order_item_display_meta_value', $meta->value ),_
				);

STEPS TO REPRODUCE THE ISSUE

1. Install Add Ons plugin
2. Add multiplier through addon 
3. Order that product in front end
4. Check the order detail and multiplier value keeps missing in front end order detail but not in order view in admin area.

I hope i have informed correctly . doing for first time :)

**Comment by mikejolley** [comment]
The new ticket template tells you that this are is _not_ for premium plugin support. This is a core issue tracker.

Anyhow, I tested the latest release and its fine: https://dl.dropboxusercontent.com/s/1fdm48c5kid89ao/2016-02-26%20at%2013.29.png?dl=0
