### ISSUE TITLE
Woo not sending e-mails for Payments with PagSeguro

### ISSUE THREAD

**Issue by vivilopes** [woothemes/woocommerce#10413]
Hello, 

When a checkout is made and the method of payment is the PagSeguro, the notifications e-mail is not being sent. This is terrible because not even the confirmation of the purchase is sent to the customer. The payment approval is not sent to the admin. 

If we go in the woo panel, we can see the order, and we can 'resend' the email. 
This is generated correctly. The problem is that we can't stay connect the whole day waiting for a new order and send out the mails manually. 
The store will lose credibility as soon as the first mail was missed/ not sent.

This is not happening with other method of payments.

**Comment by shivapoudel** [comment]
@vivilopes seems like Payment Gateway issue. Can you please attach the System Status report :)

**Comment by vivilopes** [comment]
### WordPress Environment ###

Home URL: http://voaborboleta.com.br
Site URL: http://voaborboleta.com.br
WC Version: 2.5.2
Log Directory Writable: ✕ Para permitir logs/registros
configure permissões de escrita em /home/voaborboleta/www/wp-content/uploads/wc-logs/ ou defina um diretório personalizado com WC_LOG_DIR.

WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: pt_BR

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.30
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.5.43
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Post Remoto: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (18) ###

All In One WP Security: por Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.0.6

BackWPup: por Inpsyde GmbH – 3.2.4
Cielo Voa Borboleta - Solução Webservice: por Gabriel Reguly
Claudio Sanches
Paulo Vieira – 4.0.10

Formulário de contato 7: por Takayuki Miyoshi – 4.4
WPBakery Visual Composer: por Michael M - WPBakery.com – 4.9.2
Revolution Slider: por ThemePunch – 4.6.93
WooCommerce Auto Restore Stock: por Gerhard Potgieter – 1.0.1
Voa Borboleta Boleto: por Claudio Sanches – 1.5.3
WooCommerce Branding: por Dreams Online Themes – 1.0.1
Voa Borboleta Checkout Manager: por Ephrain Marchan – 4.0
Voa Borboleta Correios: por Claudio Sanches – 2.3.0
Voa Borboleta Extra Checkout Fields for Brazil: por Claudio Sanches – 3.4.2
Woocommerce Lembrete Boleto: por agenciamagma – 1.0.3
Voa Borboleta PagSeguro: por Claudio Sanches – 2.11.2
Voa Borboleta Descontos por Método de Pagamento: por Claudio Sanches – 2.2.1
Voa Borboleta: por WooThemes – 2.5.2
wpMandrill: por Mandrill – 1.33
YITH Voa Borboleta Ajax Product Filter: por yithemes – 2.7.7

### Settings ###

Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Base da loja: #15 - /loja/
Carrinho: #16 - /carrinho/
Finalizar compra: #17 - /finalizar-compra/
Minha conta: #18 - /minha-conta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Voa Borboleta
Version: 2.9
Author URL: http://fb.com/vivii.lopess
Child Theme: ✔
Parent Theme Name: LEGENDA - 8theme WordPress theme
Parent Theme Version: 2.11
Parent Theme Author URL: http://themeforest.net/user/8theme
WooCommerce Support: ✔

### Templates ###

Overrides: voaborboleta/woocommerce/archive-product.php
voaborboleta/woocommerce/cart/cart-empty.php
voaborboleta/woocommerce/cart/cart-shipping.php
voaborboleta/woocommerce/cart/cart.php
voaborboleta/woocommerce/cart/cross-sells.php
voaborboleta/woocommerce/checkout/form-billing.php
voaborboleta/woocommerce/checkout/form-checkout.php
voaborboleta/woocommerce/checkout/form-coupon.php
voaborboleta/woocommerce/checkout/form-login.php
voaborboleta/woocommerce/checkout/form-shipping.php
voaborboleta/woocommerce/checkout/review-order.php
voaborboleta/woocommerce/content-product.php
voaborboleta/woocommerce/content-product_cat.php versão 2.5.0 esta desatualizado. A versão do core é 2.5.2
voaborboleta/woocommerce/content-single-product.php
voaborboleta/woocommerce/content-widget-product.php
voaborboleta/woocommerce/global/form-login.php
voaborboleta/woocommerce/global/quantity-input.php
voaborboleta/woocommerce/loop/add-to-cart.php
voaborboleta/woocommerce/loop/loop-end.php
voaborboleta/woocommerce/loop/loop-start.php
voaborboleta/woocommerce/loop/no-products-found.php
voaborboleta/woocommerce/loop/pagination.php
voaborboleta/woocommerce/loop/rating.php
voaborboleta/woocommerce/myaccount/form-edit-address.php
voaborboleta/woocommerce/myaccount/form-login.php
voaborboleta/woocommerce/myaccount/my-account.php
voaborboleta/woocommerce/myaccount/my-downloads.php
voaborboleta/woocommerce/single-product/add-to-cart/external.php
voaborboleta/woocommerce/single-product/add-to-cart/simple.php
voaborboleta/woocommerce/single-product/meta.php
voaborboleta/woocommerce/single-product/product-image.php
voaborboleta/woocommerce/single-product/product-thumbnails.php
voaborboleta/woocommerce/single-product/related.php
voaborboleta/woocommerce/single-product/short-description.php
voaborboleta/woocommerce/single-product/tabs/tabs.php
voaborboleta/woocommerce/single-product/title.php
voaborboleta/woocommerce/single-product/up-sells.php
voaborboleta/woocommerce/single-product-reviews.php
voaborboleta/woocommerce/single-product.php

: Aprenda como atualizar templates desatualizados

**Comment by claudiosmweb** [comment]
WooCommerce will send emails when the order status is changed, it isn't an issue on WooCommerce.

**Comment by vivilopes** [comment]
But what about the e-mail notification about the order placed?
This is not related to the order status.. Correct?

And, if the customer is also not registered. He will do the registration at the time of checkout. 
That email will also not be sent? Maybe I am not explaining very well... 
But even if the status changes (payment approved), the system still don't send out the emails.. 

The only way to know that a new order has arrived is through PagSeguro notification to the admin.
With that, will be possible to locate the order. But what about the customer? He will not receive any email until a manual intervention triggers it.

**Comment by claudiosmweb** [comment]
> But what about the e-mail notification about the order placed?
> This is not related to the order status.. Correct?

WooCommerce does not control it, only make available methods so that you can change the status and then send the emails.
If email is not being sent, it's because the status is not being changed, however if the status is being changed and no email is not sent, then the problem is in the server unable to send.

> And, if the customer is also not registered. He will do the registration at the time of checkout.
> That email will also not be sent? Maybe I am not explaining very well...
> But even if the status changes (payment approved), the system still don't send out the emails.. 

As I said, maybe a problem in your server, unable to send emails.

**Comment by vivilopes** [comment]
Got it, I will check internally just in case... 
But if I go to the order details and select to 're-send' the emails, the emails are sent normally.
And, it is not a server problem since other method of payment orders are being sent as usual. 

p.s.: Already saw some posts at the Woocomerce Page (from Facebook) a few comments about this problem since version 2.3;    ;(  I don't know what I can do anymore. Already hired a person to fix this problem and seems to be something untraceable.

Thank you anyway, Claudio.

**Comment by claudiosmweb** [comment]
So not a problem on WooCommerce too.
Can be a problem on the Payment Gateway.
