### ISSUE TITLE
Simple product not loading in Ajax

### ISSUE THREAD

**Issue by vivilopes** [woothemes/woocommerce#10414]
Hello, 

In case of a Simple Product, if we choose to 'buy' direct from the listed items (without accessing the product page), the Ajax starts loading and never stops. If we reload the page, the product goes to the cart. But the customer does not knows that, he simply wait until the 'loading' finishes and nothing happens. 

If we go direct to the product page (the individual one), we are able to buy. The pop up opens at the screen saying that the product was added successfully.

**Comment by mikejolley** [comment]
Your theme has custom ajax events in place. It is not using WooCommerce add to cart buttons + ajax code.

**Comment by vivilopes** [comment]
That's weird, I disabled the two plugins I have containing Ajax and tried, but the problem is still there.

**Comment by mikejolley** [comment]
I said theme, not plugins. 

All of your cart buttons link to the product pages as they don't have our ajax class name.

**Comment by vivilopes** [comment]
Oh.. okay. Got it !
Will request they support then.

Appreciate your time.  Thank you very much!
