### ISSUE TITLE
On fresh install it ignore the language of the wordpress instalation

### ISSUE THREAD

**Issue by a1ur3l** [woothemes/woocommerce#10416]
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [x] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

Installing a fresh version of WC 2.5.2 is ignoring the language of the website.
i have tried also to manually change the language from Settings to US and after change back to RO, but WC is still resting in US.

STEPS TO REPRODUCE THE ISSUE

1. Install a clean wordpress and make the basic settings (including change lang to RO)
2. Install storefront, create a child theme and activate it
3. Install WC and follow the tutorial and skip the tax steps.
4. Observe that WC is installed in EN.
5. Try to change the language of the website from settings to English and after back to RO and observe that WC is still in EN.

*RO = Romanian

SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.

### WordPress Environment ###

Home URL: http://new.cauciucurijante.ro
Site URL: http://new.cauciucurijante.ro
WC Version: 2.5.2
Log Directory Writable: ✔  /var/www/*****/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: ro_RO

### Server Environment ###

Server Info: nginx/1.9.9
PHP Version: 5.6.17-1~dotdeb+7.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (5) ###

Advanced Custom Fields: by Elliot Condon – 4.4.5
Contact Form 7: by Takayuki Miyoshi – 4.4
Easing Slider: by Matthew Ruddy – 2.2.1.1
WooCommerce: by WooThemes – 2.5.2
Yoast SEO: by Echipa Yoast – 3.0.7

### Settings ###

Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My Account: #8 - /?page_id=8

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront Child Theme for cauciucurijante.ro
Version: 1.6.1
Author URL: https://www.pixelair.ro
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 1.6.1
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Romanian is not complete. You can contribute here: https://translate.wordpress.org/locale/ro/default/wp-plugins/woocommerce

For now you can install the non-complete MO file manually https://docs.woothemes.com/document/woocommerce-localization/

**Comment by a1ur3l** [comment]
@mikejolley : just a quick question: which one of the 4 set need to be 100%, to download it?
Thanks a lot

**Comment by claudiosmweb** [comment]
@a1ur3l the "Stable (latest release)"
