### ISSUE TITLE
Implications of adding a hook to html-product-attribute.php

### ISSUE THREAD

**Issue by VesterDe** [woothemes/woocommerce#10429]
The file, located under `\includes\admin\meta-boxes\views\html-product-attribute.php` would serve me a lot better if it had a hook after the last `</tr>`, line 75.

Something like this let's say:
`<?php do_action("woocommerce_after_product_attribute_rows", $attribute); ?>`

I searched if anyone had asked this before but didn't manage to find anything.

What this would allow me to do is to easily add additional fields to attributes, which I find quite difficult at the moment.

However, I probably don't understand fully what this would mean for other parts of WC. I'm eager to hear an explanation.

**Comment by mikejolley** [comment]
You're welcome to submit a PR if you can justify why its needed.
