### ISSUE TITLE
Wrong link adress by multi language

### ISSUE THREAD

**Issue by erikwagner1978** [woothemes/woocommerce#10421]
Wrong Link adres by multi language site:

When a person i watching the site in Dutch al thinks works fine.
When the german site is choosen there is a problem with the product catagory.

Original site:
http://www.racehelm.eu/product-categorie/mibenco/standaard-ral-kleuren/
All works fine

When German language is choosen on front page the link looks like this:
http://www.racehelm.eu/de/product-category/mibenco/standaard-ral-kleuren/
 

> 
Oops! That page can’t be found.

It looks like nothing was found at this location. Perhaps you can return back to the site's homepage and see if you can find what you are looking for. Or, you can try finding it by using the search form 
 below.

> 

When product catagory page is selected on Dutch and the switch to German all works fine:
http://www.racehelm.eu/de/product-categorie/mibenco/standaard-ral-kleuren/

The problem is the translation: product-catagorie to product-category

How can i solve this....

### WordPress Environment ###

Home URL: http://www.racehelm.eu
Site URL: http://www.racehelm.eu
WC Version: 2.5.2
Log Directory Writable: ✔  /home/karthelm.eu/public_html/racehelm.eu/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.36-1~dotdeb.1
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.46
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (10) ###

Custom Facebook Feed: door Smash Balloon – 2.3.10
Mollie Payments for WooCommerce: door Mollie – 2.1.1
qTranslate-X: door qTranslate Team – 3.4.6.4
Woocommerce Catalog Enquiry: door Prabhakar Kumar Shaw
Dualcube – 2.3.0

WooCommerce MyParcel: door Ewout Fernhout – 1.5.3
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.5.28
WooCommerce & qTranslate-X: door qTranslate Team – 1.3
WooCommerce: door WooThemes – 2.5.2
Yoast SEO: door Team Yoast – 3.0.7
Yoast SEO & qTranslate-X: door qTranslate Team – 1.1

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Winkelbasis: #111 - /webshop/
Winkelmand: #112 - /winkelmand/
Afrekenen: #113 - /afrekenen/
Mijn account: #114 - /mijn-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Helm@
Version: 0.1.4
Author URL: http://www.sumowebsite.com
Child Theme: ✔
Parent Theme Name: Omega
Parent Theme Version: 1.2.8
Parent Theme Author URL: https://themehall.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
This is because the category base etc gets translated too. Your translation plugin (qTranslate?) would need to work around this. Thats something I believe WPML does their side too. WC cannot work around translation plugins like this.

You can try going to Settings > Permalinks and saving, but I suspect it won't help if dealing with permalink translations.
