### ISSUE TITLE
Webhooks scalar arguments?

### ISSUE THREAD

**Issue by Horrower** [woothemes/woocommerce#10424]
Before submitting your issue, please go through the following checklist. Thanks!

- [ X ] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [ X ] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [ X ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ X ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [ X ] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

Version 2.5.2.
WebHooks. 

Your Code at line 117 in file includes/class-wc-webhook.php
```php
wp_schedule_single_event( time(), 'woocommerce_deliver_webhook_async', array( $this->id, is_scalar( $arg ) ? $arg : 0 ) );
```
Why you are using is_scalar? It's not passing arrays. 
Is there is no way for custom actions save arrays for async delivery ?

The Story.
I'v registered custom actions in my webhooks in admin panel.
Now I'm fire it:
```php
do_action('woocommerce_my_custom_async_action',['var1'=>'val1']);
```
Result when Im starting CRON by url (wp-cron.php): 
```
array (size=2)
  'action' => string 'woocommerce_my_custom_async_action' 
  'arg' => int 0
```

Workaround is to save json_encoded data.
```php
do_action('woocommerce_my_custom_async_action',json_encode(['var1'=>'val1']));
```
But still having not expected result at webhook's endpoint:
```
{"action":"woocommerce_transmit_bid_to_r1","arg":"{\"var1\":\"val1\"}"}
```

Workaround to pass normal decoded json args to webhook's endpoint is to add filter for payload process:

```php
add_filter("woocommerce_webhook_payload", function  ($payload, $resource, $resource_id, $hook_id)) {  
  if ($resource_id == 0) {
            $mData = $payload['arg'];
            if (false !== ($sJson = @json_decode($mData))) {
                $aRet = $sJson;
            }
            else
                $aRet = $mData;
            return $aRet;
        }
        else {
            return $payload;
        }
  }
], 1, 4);
```

Please explain how it should works or fix that issue. Thank you.

**Comment by Horrower** [comment]
This row have more bug: "wp_schedule_single_event( time(),"

TIME() - is wrong because wp_cron works with gmt_time.
must be current_time('timestamp',true)

**Comment by claudiosmweb** [comment]
@Horrower I'm checking it with @maxrice which was the author of our webhooks.

**Comment by maxrice** [comment]
no particular reason for forcing scalar values IIRC, just made it a bit simpler to implement. I think that we could pass the 1st arg of the hook directly to `wp_schedule_single_event()` and then `json_encode()` it in the delivery request body.

@Horrower using `time()` is correct and should be the same exact value as `current_time( 'timestamp', true );` -- if you have different values, your server's timezone is set incorrect as `time()` should always return a UTC timestamp. see more on [`wp_schedule_single_event()`](https://codex.wordpress.org/Function_Reference/wp_schedule_single_event) :smile:

**Comment by claudiosmweb** [comment]
Only had to remove the `is_scalar()`, since we use `json_encode()` for the body:
https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L196

**Comment by Horrower** [comment]
`time()` and `current_time( 'timestamp', true );` are different values of you installed wordpress on some very far server.
IMO Its better to allow wordpress to decide which are UTC or not.

**Comment by mikejolley** [comment]
@Horrower the codex docs for cron state you should use time(). Your suggestion is not supported.

**Comment by Horrower** [comment]
Yes, sorry, my fault. There is misunderstanding in WP Codebase.
in wp-cron.php you can see that `$gmt_time = microtime( true );` and it is not actually valid. 
Anyway, seems its a WP bug, not Woocommerce. 
Thank you

**Comment by Horrower** [comment]
Can you fix this line too:
`if ( apply_filters( 'woocommerce_webhook_deliver_async', true, $this ) ) {`
in class-wc-webhook.php at line 114. 
to `if ( apply_filters( 'woocommerce_webhook_deliver_async', true, $this, $arg ) ) {`.
We need to intercept your request and put messages to queue before cron process.

**Comment by claudiosmweb** [comment]
> Actually the main problem is w3total cache object cache not working well with woocommerce cron. Webhooks are missing and never fire's. 

Easy to fix, disable WP Cron and put it into crontab.
https://developer.wordpress.org/plugins/cron/hooking-into-the-system-task-scheduler/

**Comment by Horrower** [comment]
Its already there, still have some strange bug with cron's which are saved in DB, but when wp-cron starts - its not fired and erased from wp_option 'cron'.
I'v spent 2 days for that bug.. find some article's (for example https://wordpress.org/support/topic/self-diagnosed-and-fixed-w3-total-cache-bug-in-faulty-object-caching) but it didn't help too...

**Comment by claudiosmweb** [comment]
Still don't seems to be an error on WooCommerce.
