### ISSUE TITLE
Replacement Hook for 'woocommerce_update_options_shipping'

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#10427]
I've been testing on a pull from this repository to try out the new shipping zones and instances. In earlier versions of WooCommerce, I could save custom settings fields by creating my own functions and passing them through the following hook:

add_action( 'woocommerce_update_options_shipping_' . $this->id, array( $this, 'process_admin_options' ) );

This doesn't seem to work anymore, and when I look up the save function, there is a filter for single values but no general action hook. Is it possible to add this back in and have it save to the appropriate instance?

**Comment by mikejolley** [comment]
This hook was/is used on the main shipping settings screen. Firing this same hook on all instances could have...implications. 

There is a regular process_x hook for saving instances and methods. What you trying to do?

**Comment by bolderelements** [comment]
Thanks for the response!

I have some groups of settings that don't fit into the usual settings types (text, select, radio, etc...). When my shipping method saved, I would just hook into that filter and save the data as a multi-dimensional array in the wp_options table. I can modify my own script to include the instance ID, but I don't know how to hook the save function anymore.

**Comment by mikejolley** [comment]
I think regardless of whether or not your method supports new zones, you want a hook like this:

https://gist.github.com/mikejolley/3b37b9cc19a774665f31#file-gistfile1-txt-L41

Threw this together yesterday https://github.com/woothemes/woocommerce/wiki/Shipping-Method-API-(2.6)

I know you folks have a table rate shipping extension like us so let us know your thoughts on new zones.

**Comment by bolderelements** [comment]
I've tried using that hook but it never seems to fire. I search the repository for the 'do_action' but couldn't find it. It looked like it directly called the method's 'process_admin_options' function and that was it. 

Thanks for the guide! I've been learning as I go, writing a new shipping method to play around with the various features. So far I'm loving it, very easy to implement, next I hope to try expanding upon the zone options. My only disappointment is that it's a tab under WooCommerce settings. A popular request in vendor markets is to give the vendor the ability to setup their own shipping, which is a challenge to do without giving access to the rest of the settings but I enjoy a good challenge :)

**Comment by mikejolley** [comment]
O you may be right. Hmm, maybe the old way was via the hook.

I'll have to investigate some more. Are you adding extra settings to each instance? How?

**Comment by bolderelements** [comment]
At the moment I've had to override the admin_options function. It still cycles through the instance_form_fields array, but then at the end I call some additional functions from the class. I may change that to run on a hook eventually so others can add to the page. Like you I wasn't sure if it would have any implications with the new instances but we shall see. It seems doable if you pass enough through about the particular method and instance that is running.

**Comment by mikejolley** [comment]
Ok, if you're adding options in this way by overriding the method, I think you can do the same for process_admin_options by overriding that method too, and calling parent:: process_admin_options() when you're done,
