### ISSUE TITLE
Changing variation Regular Price, Sale Price or Weight doesn't cause "Save changes" & "Cancel" buttons to activate.

### ISSUE THREAD

**Issue by VesterDe** [woothemes/woocommerce#10422]
As the title says, while editing a single variation changing any field except those mentioned triggers the Save and Cancel buttons to become enabled.

Why not those three fields? Is it a feature? I find it slightly bothersome because it forces me to change stock or some other property of a variation and then change it back, just to get the buttons to activate.

WP: 4.4.2
WC: 2.5.2
Notable plugins:
Woocommerce composite products
WC Variations Radio Buttons

Can provide more context, if someone tells me what.

Thank you for any assistance.

UPDATE: I just noticed that the issue is a bit more complex. Changing some random field to trigger the buttons activating works, but variations that did not trigger the event will not save. This means I must cause a fake change in each variation I wish would get saved.

**Comment by mikejolley** [comment]
Does not seem like a core issue - I did what you said on 2.5.2 and it changed as soon as the input was changed.

![variation](https://cloud.githubusercontent.com/assets/90977/13324976/dd9a82b0-dbd7-11e5-8301-d3d019c39739.gif)

If you'd used our issue template you'd know to rule out plugin conflicts before reporting ;)
