### ISSUE TITLE
related.php contains class name with spaces

### ISSUE THREAD

**Issue by sofar** [woothemes/woocommerce#10438]
https://github.com/woothemes/woocommerce/blob/58b185e7a6dfa0359ca86f6190854eb536409422/templates/single-product/related.php#L49

```
        <div class="related products">
```

Class names can not contain spaces. This makes it impossible to adjust style of this div, because one cannot select a class with spaces.

**Comment by Kenshino** [comment]
Are you sure it's not simply 2 different classes? :)

**Comment by sofar** [comment]
the space makes no sense to me here, shrug.
