### ISSUE TITLE
Restrict Specific Countries

### ISSUE THREAD

**Issue by SolutionsDEV** [woothemes/woocommerce#10436]
Under General Options tab, Selling Locations, there are 2 choices, all countries or selected countries, but what if I want to ship or bill to all countries except a few, this means that I will have to enter every country other than those to be restricted.

Wouldn't it be a better idea to add another selection that says "sell to all countries except those selected", and therefor to enable selecting those unneeded countries only.

Appreciate a quick action.

Thanks a lot

**Comment by claudiosmweb** [comment]
Related: https://wordpress.org/support/topic/suggestion-excluding-contries-to-sell?replies=2#post-8257309

**Comment by SolutionsDEV** [comment]
Thanks a lot, will be waiting for it.
