### ISSUE TITLE
WooCommerce Matkahuolto plugin mixes woocommerce settings

### ISSUE THREAD

**Issue by noppeshop** [woothemes/woocommerce#10431]
WooCommerce Matkahuolto
Poista käytöstä | Muokkaa | Settings
Matkahuolto lisäosa WooCommercelle.

Versio 1.4 | Tekijä Webbisivut.org | Näytä lisäosan sivusto | Check for updates

Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [ ] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [ ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [ ] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.
WooCommerce Matkahuolto
Poista käytöstä | Muokkaa | Settings
Matkahuolto lisäosa WooCommercelle.

Versio 1.4 | Tekijä Webbisivut.org | Näytä lisäosan sivusto | Check for updates

Notice: Undefined index: jp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-jakopaketti-shipment-methods.php on line 164

Notice: Undefined index: pp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-pikapaketti-shipment-methods.php on line 164

Notice: Undefined index: be_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-bussiennakko-shipment-methods.php on line 167

Notice: Undefined index: jp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-jakopaketti-shipment-methods.php on line 164

Notice: Undefined index: pp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-pikapaketti-shipment-methods.php on line 164

Notice: Undefined index: be_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-bussiennakko-shipment-methods.php on line 167

Notice: Undefined index: jp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-jakopaketti-shipment-methods.php on line 164

Notice: Undefined index: pp_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-pikapaketti-shipment-methods.php on line 164

Notice: Undefined index: be_kuponki in /home/vinpakf/public_html/noppeshop.com/wp-content/plugins/wb-matkahuolto/includes/class-wb-bussiennakko-shipment-methods.php on line 167
![image](https://cloud.githubusercontent.com/assets/17499528/13358416/e27c0282-dcb7-11e5-92e9-259e8626a4cf.png)

Scandinavic letters doesn't work ä ö 
kÃ¤ytetÃ¤Ã¤n  should be käytetään
STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

If I uninstall plugin, things are OK
installing plugin...still OK
Updating plugin...problems are here again :(

That plugin is Finnish posting-plugin, so can't really run shop without.

SYSTEM STATUS REPORT

```

### WordPress Environment ###

Home URL: http://noppeshop.com
Site URL: http://noppeshop.com
WC Version: 2.5.2
Log Directory Writable: ✔  /home/vinpakf/public_html/noppeshop.com/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: fi

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.4.42
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.48
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Palvelimella ei ole käytössä "SoapClient-luokkaa – ne lisäosat jotka käyttävät SOAP eivät ehkä toimi odotetulla tavalla.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Etälähetys/ Remote Post -toiminto: ✔
Etänouto/ Remote Get -toiminto: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (13) ###

AddToAny Share Buttons: -- AddToAny – 1.6.13
Jetpack by WordPress.com: -- Automattic – 3.9.2
WB Checkout Maksutavat: -- Webbisivut.org – 1.2.9.1
WooCommerce Matkahuolto: -- Webbisivut.org – 1.4
Woocommerce CSV import attributes: -- Allaerd Mensonides – 3.1.0
Woocommerce CSV import custom fields: -- Allaerd Mensonides – 3.0.1
Woocommerce CSV import downloadable, external, grouped products: -- Allaerd Mensonides – 3.0.1
Woocommerce CSV import variable products: -- Allaerd Mensonides – 3.1.0
Woocommerce CSV Import: -- Allaerd Mensonides – 3.1.4
WooCommerce Google Analytics -liitos: -- WooThemes – 1.4.0
Woocommerce Image Zoom: -- wpbean – 1.0
WooCommerce: -- WooThemes – 2.5.2
YITH WooCommerce Ajax Search: -- Yithemes – 1.3.9

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Kaupan polkutunnus: #4 - /
Ostoskori: #5 - /ostoskori/
Kassa: #6 - /kassa/
Oma tili: #7 - /oma-tili/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 1.6.1
Author URL: http://www.woothemes.com
Child Theme: ✕ – Suositus: jos muokkaat WooCommerce tai isäntäteemaa jota et itse ole tehnyt
käytä lapsiteemaa. Katso: Kuinka luodaan lapsiteema

WooCommerce Support: ✔

### Templates ###

Overrides: –

```

**Comment by mikejolley** [comment]
You need to report this to the author of "WooCommerce Matkahuolto". We handle core issues only here.

**Comment by noppeshop** [comment]
Problem solved ... My mistake to have debug switched on
29.2.2016 14.30 "Mike Jolley" <notifications@github.com> kirjoitti:
