### ISSUE TITLE
Strong Passwords Required on My Accounts but not Checkout in 2.5

### ISSUE THREAD

**Issue by mashmac2** [woothemes/woocommerce#10430]
- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

EXPLANATION OF THE ISSUE

In WooCommerce 2.5, a visitor creating an account on the Checkout page is not required to have a strong password, but is required to set a strong password on the My Accounts page. 

Can we remove the requirement for a strong password on the My Accounts page, like we have done for the Checkout page? Perhaps we could even offer an option in settings for both pages - 'Strong passwords required' or similar.

STEPS TO REPRODUCE THE ISSUE

1. Create account on the Checkout page, setting a weak password.
2. Try to change the password to a weak password on the My Accounts page.

**Comment by mikejolley** [comment]
There are filters/snippets to lessen the strength or remove the meters completely. On checkout we made them non-blocking to avoid losing conversions, but this is not important on account pages so strength should be enforced.
