### ISSUE TITLE
Security Critical: Google Analytics capturing user Checkout pages, publishing shipping and ordering data to the web

### ISSUE THREAD

**Issue by puresilk** [woothemes/woocommerce#10433]
- [X] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [X] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce. (v2.5.2)
- [ ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
No I have not - there are several 
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
I am using the Avada Theme.

- [X] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

A customer notified me that when they searched for their name, the checkout page was visible on Google.

The checkout page, with an URL like the following (URL slightly modified to protect the innocent):
https://example.com/checkout/order-received/2233/?key=wc_order_555e33fa777a1

will show the customer's address, phone number, e-mail, and their order.

I am unsure where Google gets the data. Maybe through Google Analytics / Conversion / Adwords Tracking? 

This is, as can be seen in the screenshot - not a single case, many customers are concerned. Many, but not all. I suspect that only guest checkouts are concerned, but again - not all guest checkouts. Also I have NOT tested this suspicion.

We have extensive caching, a multilanguage plugin, and several tracking plugins which could have caused the data leak to Google. 

BUT:
No matter how Google gets the data - Woocommerce should protect it at all cost and never allow the Google bot, or other search bots to index the checkout pages which can be accessed publicly using the key.

STEPS TO REPRODUCE THE ISSUE

1. search in Google for the sitename of the woocommerce shop and "Billing Address"
2. click on entries and see that they take you to confidential customer data

SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://example.com (URL changed for security reasons)
Site URL: https://example.com (URL changed for security reasons)
WC Version: 2.5.2
Log Directory Writable: ✔  /var/www/html/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.6.2
PHP Version: 5.6.14-0+deb8u1
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
SUHOSIN Installed: –
MySQL Version: 5.5.5
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (30) ###

LayerSlider WP: by Kreatura Media – 5.3.2
Actionable Google Analytics: by Tatvic – CC-V3-1.2
AffiliateWP: by Pippin Williamson and Andrew Munro – 1.7.14
Formidable: by Strategy11 – 2.0.22
Fusion Core: by ThemeFusion – 1.8.3
Groups: by itthinx – 1.10.1
Instant Search + for WooCommerce Search: by Fast Simon Inc – 1.4.6
PayPal for WooCommerce: by Angell EYE – 1.1.9.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Revolution Slider: by ThemePunch – 4.6.92
WPML Multilingual CMS: by OnTheGoSystems – 3.3.3
Cookie Consent: by Catapult_Themes – 2.0.7
W3 Total Cache: by Frederick Townes – 0.9.4.1
Woocommerce Exclude Categories PRO: by Alvaro Neto – 2.0
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.1.1
WooCommerce German Market: by Inpsyde GmbH – 2.6.6
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.1
WooCommerce Multilingual: by OnTheGoSystems – 3.7.9
WooCommerce One Page Checkout: by Prospress Inc. – 1.2.5 – 1.2.6 is available
WooCommerce Product Add-ons: by WooThemes – 2.7.15
WooCommerce Quick Export Plugin: by MB Création – 2.4
WooCommerce Role Based Methods: by WPBackOffice – 2.0.8
WooCommerce Sequential Order Numbers: by SkyVerge – 1.6.1
WooCommerce Smart Coupons: by WooThemes – 3.0.10
WooCommerce: by WooThemes – 2.5.2
WooThemes Helper: by WooThemes – 1.5.9
WP-Optimize: by Ruhani Rabin – 1.8.9.10
WPML Media: by OnTheGoSystems – 2.1.17
WPML String Translation: by OnTheGoSystems – 2.3.4
WPML Translation Management: by OnTheGoSystems – 2.1.3

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #8 - /
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My Account: #11 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Avada
Version: 3.9.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/content-product.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/myaccount/form-edit-address.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php
Avada/woocommerce/single-product-reviews.php
```

Please see this screenshot for the leak:

![woocommerce-security-break](https://cloud.githubusercontent.com/assets/4606111/13360071/95987edc-dcb7-11e5-8165-f1bfe24e4824.png)

**Comment by puresilk** [comment]
workaround suggestion for NGINX:

create a new page "thank-you-for-the-order", and put a generic thank you text with your contact data.
then put this in your server stanza:

       rewrite ^/.*/order-received/.*$  https://example.com/thank-you-for-the-order? permanent;

The question mark at the end drops the query string.

**Comment by mikejolley** [comment]
Have you excluded checkout from w3 total cache?

Does you analytics plugin ping Google or generate a site map?

I'm not sure why this would happen because Google indexes links it can reach - a user is redirected to the thanks page, it's never linked to directly. 

The 'key' portion of the URL is needed to view the data so it works for guest etc. Without order ID and key it's hidden. You should see if you can find what Is telling Google about these links. 

We could look into extra cookie protection but this won't work for things like order tracking if those are also indexed somehow.

**Comment by claudiosmweb** [comment]
This should be accessed by non-registered users, since it is possible to checkout without registering. Maybe we can show less information when the user is not registered... At least we can maybe hide name and address...

We can add to the head:

```html
<meta name="googlebot" content="noindex" />`
```

**Comment by mikejolley** [comment]
That could work.

**Comment by puresilk** [comment]
maybe just showing the order items, without reference to the person who ordered them?
right now I can't debug the site - I have some urgent deadlines, will only be able to dedicate more time to this Mid-March.
