### ISSUE TITLE
Duplicated products show original rating/review counts

### ISSUE THREAD

**Issue by saulfautley** [woothemes/woocommerce#10440]
EXPLANATION OF THE ISSUE

When duplicating a product that has ratings/reviews, the duplicated product displays rating/review counts from the original product. The actual reviews however are not displayed.

STEPS TO REPRODUCE THE ISSUE

1. Duplicate a product that has ratings/reviews.
2. Save and view the duplicated product.
3. The rating and review counts from the original product are displayed.

Running WooCommerce v2.5.2.

**Comment by xpafiolis** [comment]
i know this was marked as closed as it seems to have been corrected when duplicating products, HOWEVER, is there a fix for existing products that have already been duplicated? i have 200+ products that have this issue hit or miss. 

Is there a reset button i can hit for those products with this issue?
