### ISSUE TITLE
Template for price filter widget

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#10448]
I'd like to suggest that [this](https://github.com/woothemes/woocommerce/blob/master/includes/widgets/class-wc-widget-price-filter.php#L145-L159) be put in a template file to make the price filter widget more customizable.

**Comment by mikejolley** [comment]
Since all of that HTML is replaced by a slider (jquery slider) I don't see much point in allowing theme devs to change this markup.

Use a custom widget or code within the sidebar. If you use same option names, the filter will work regardless of using our widget or not.
