### ISSUE TITLE
hook for payment gateways to make refund doesn't fire when change status to refund

### ISSUE THREAD

**Issue by vphat28** [woothemes/woocommerce#10446]
Hi

I can click on the button near "Order Items" (in order detail) > Enter an amount to refund and a reason as optional.

- and the function process_refund will be called in payment gateway class

but when I tried to change status to refund, I see there is a record in order detail page that say "it's refunded" but the function process_refund isn't called.

anyone notice this? 

Xavi

**Comment by mikejolley** [comment]
Changing the order status should be considered a manual refund - gateway refund code is not called.

Gateway process_refund is only called if you use the buttons and refund via the gateway. This is intentional to prevent user error.

**Comment by vphat28** [comment]
Thanks Mike :)
