### ISSUE TITLE
'show_image' is hardcoded to false in email-order-details.php

### ISSUE THREAD

**Issue by martin-denizet** [woothemes/woocommerce#10449]
Hi there,

Maybe I'm missing something but I don't see why 'show_image' is hardcoded to false in _email-order-details.php_:
```php
		<?php echo $order->email_order_items_table( array(
			'show_sku'      => $sent_to_admin,
			'show_image'    => false,
			'image_size'    => array( 32, 32 ),
			'plain_text'    => $plain_text,
			'sent_to_admin' => $sent_to_admin
		) ); ?>
```
Moreover, the default is already set to false in function _email_order_items_table()_ in _abstract-wc-order.php_ line 1950:
```php
		$defaults = array(
			'show_sku'      => false,
			'show_image'    => false,
			'image_size'    => array( 32, 32 ),
			'plain_text'    => false,
			'sent_to_admin' => false
		);
```

I suggest not to specify _show_image_  in _email-order-details.php_ and to let it default to false in _email_order_items_table()_.

If it was not hardcoded it would be possible to re-use this template and show the product thumbnails with `'show_image'    => true` in a custom email.

Thank you for your time!

**Comment by claudiosmweb** [comment]
You can override it in your template: https://docs.woothemes.com/document/template-structure/

> I suggest not to specify show_image in email-order-details.php and to let it default to false in email_order_items_table().

This will not really change anything. You still need to override `email-order-details.php` to do it.

> If it was not hardcoded it would be possible to re-use this template and show the product thumbnails with 'show_image' => true in a custom email.

You can do it by overriding this template...
