### ISSUE TITLE
Upload @local image files using API

### ISSUE THREAD

**Issue by JohnDase** [woothemes/woocommerce#10443]
Hi I have my images server in my internal network, and woocommerce in a public internet server.
I trying to upload, through the API, images using like multipart post commands but I couldn't find how to do it using /wc-api/v3/products because it only accept uploading images urls in images": [{"src":"URL"}] JSON.
Thanks

**Comment by claudiosmweb** [comment]
You need to use a public link for it.
Maybe we'll change it in the future.

**Comment by JohnDase** [comment]
ok, thanks :(
