### ISSUE TITLE
Duplicate orders through WooCommerce

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#10453]
Hi there,

I'm having an issue with our site where under heavy load orders are getting duplicated.

A user has posted a similar issue here - https://wordpress.org/support/topic/duplicate-order-with-same-transaction-id

Basically we have established that on some occasions, especially under heavy server load, both PayPal Express and Stripe orders are getting duplicated. If it happens with a Stripe payment then we will actually receive two payments, however seeing it happen with stripe is more rare. If it is with PayPal then it is almost exclusively with PayPal express (using the woothemes plugin) and has actually on occasion led to three or four copies of an order. When it happens with PayPal express there will be two identical orders showing in the WooCommerce orders list with different order numbers but the PayPal transaction ID will be listed as the same for both and there will be only one payment in PayPal.

This has happened a few times when the server was not under heavy load at all. In all cases the customers have not intended to make these duplicate orders at all.

We have also had the odd few orders where they have been successfully paid on PayPal Express but on the website are still showing as "Pending".

It seems there is a problem with either WooCommerce or your PayPal express plugin... Or perhaps with both. Maybe some checks or blocks could be implemented somewhere in the system to avoid this happening?

Any ideas?

**Comment by mikejolley** [comment]
@shawaj do you have master/save db setup?

**Comment by shawaj** [comment]
@mikejolley - nope we only have a single database. The vast majority of these problems (95%+) are with the PayPal Express plugin although it has happened (rarely) with Stripe plugin as well (both of these are the official plugins from woothemes).

I have never seen it happen with the PayPal standard integration or Bitcoin.

It happened drastically under heavy load, with around 5% to 10% of orders falling victim to this, however under normal operation we do see this error as well.

We have also had a number of orders which are successfully processed on PayPal express but are left as "pending payment" or "failed" on WooCommerce.

Is there a way to build in some protections to the system in order to avoid these things in future?

Thanks

**Comment by mikejolley** [comment]
The reason I asked about master/slave is some issues we found last week about using 2 wp_update_post in quick succession. @kloon  This was fixed in last release, so please update and monitor.

**Comment by shawaj** [comment]
@mikejolley - Do you think this is something specifically WooCommerce related or down to some quirk of PayPal express or the plugin for it?

Thanks

**Comment by mikejolley** [comment]
I think its more likely the above fix causing a payment glitch. We have dupe payments too until the fix was added, now we're fine.

Update to 2.5.3 and monitor please. If it happens again perhaps we can add more logging etc. Comment here if you find anything else.

**Comment by shawaj** [comment]
@mikejolley - apologies, misunderstood your last comment where you tagged @kloon. Will update and monitor. Thanks for your input

**Comment by aeadvertising** [comment]
we're having the same issue with duplicate orders after the 3.0 update.. anyone have an idea on how to fix this?

**Comment by muthuprabhu-kp** [comment]
I am also facing this issue recently.

**Comment by binkeroni** [comment]
Having the same issue for some reason, running redis with caching plugins

**Comment by FuFeiFluff** [comment]
So how did you guys solve this issue?

**Comment by astimary** [comment]
I am having this issue now. Was there ever a resolution?

**Comment by lkraav** [comment]
I recommend everybody follow #14541 instead. If you're not on WC 8.3 yet, you might want to try patching your copy as shown at https://github.com/woocommerce/woocommerce/issues/14541#issuecomment-1807537262

**Comment by noman-work** [comment]
I am having this issue now. Was there ever a resolution?

**Comment by Magnetide** [comment]
2025; having this issue as well (including double payments...)

**Comment by planet756** [comment]
2025; having this issue as well (including double payments...)
