### ISSUE TITLE
Copy to clipboard buttons do not work in Safari

### ISSUE THREAD

**Issue by douglsmith** [woothemes/woocommerce#10450]
There are two places in WooCommerce that have buttons to copy content to the clipboard:

On the WooCommerce --> Settings --> API --> Keys/Apps screen there are "Copy" buttons to copy the generated consumer key and secret key.
On the WooCommerce --> System Status screen there is a "Copy for Support" button to copy the system status report.

Safari for Mac and iOS does not support copying form the clipboard so these button fail to copy. However, clicking the button displays an incorrect notice that it did copy.

I would suggest either hiding the buttons for Safari or using https://clipboardjs.com, which displays appropriate instructions for browsers without support.

**Comment by mikejolley** [comment]
##10462

**Comment by justinshreve** [comment]
Some good news for Safari: http://techcrunch.com/2016/03/30/apple-launches-safari-technology-preview-a-new-browser-aimed-at-web-developers/

> Support for programmatic cut and copy to the clipboard and Content Security Policy Level 2.

Meaning that should make its way to normal Safari at some point.
