### ISSUE TITLE
Sale price still persist on admin after sale period expire

### ISSUE THREAD

**Issue by a1ur3l** [woothemes/woocommerce#10454]
Before submitting your issue, please go through the following checklist. Thanks!

- [ x ] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [ x ] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [ ] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

Hello, i don't know if this is a bug or not, but i have the next problem: a product set on sale for a specific period. If after the period expire i`m going to edit it i see the sale price & sale period field filled up. If i press update without touch / change them then the sale dates are cleared (because WC check for them to be valid which is ok) and the sale price is still there and the product is not displayed to be in sale.
This is observed on 2.5.3 and 2.5.2

EXPECTED BEHAVIOR

So from my point of view i think that the correct behavior on this situation is: to  clear also the sale price (since it will be the price for that period in 99% of the cases) if the dates are older.

Or if you want to kept the current behavior just set the product on sale.

**Anyway you should block the user to select / input a date less then today + 1 day for sale end date**

STEPS TO REPRODUCE THE ISSUE

1. set a promotion for a simple product for a period.
2. wait to expire the period.
3. go to edit it.
4. observe that the sale period and prices are there
5. don`t touch / change anything just press update
6. observe that the sale period is cleared (start date and end date) -> Which is right.
7. observe that the sale price is still there and the product is not displayed as being on sale (check the price by accessing "view product" link preferably open it in a new tab in order to kept the edit page opened).
8. don`t touch / change anything and press update
9. observe that the product is on sale now.

SYSTEM STATUS REPORT

i don`t think is relevant in this situation.

**Comment by moffzar7** [comment]
I am facing the same issue, other than the fact that the Sale expiry date are supposed to be finish, my client reported to me that one of their product is still on sale but no indication at the front end that it is on sale. Secondly, other products which are on sale with same expiry date already not in sale which is expected.
