### ISSUE TITLE
Add extra fee by selected payment method on order page

### ISSUE THREAD

**Issue by sakarya** [woothemes/woocommerce#10457]
Hello..

Using bacs and cod for payment method and flat rate and free shipping for shipping.

I've added an extra fee option to cart. But I want to show it when selected payment method is cod, not bacs. Is it possible?

`add_action( 'woocommerce_cart_calculate_fees', 'woo_add_extra_fee' );
function woo_add_extra_fee() {
	global $woocommerce;

	$extra_fee_option_label		= 'Extra Fee:';
	$extra_fee_option_cost		= '5';
	$extra_fee_option_taxable	= false;

	//round the cost to 2 decimal points - fixed Paypal problem raised by Robbo870
	$extra_fee_option_cost = round($extra_fee_option_cost, 2);
	
	//if cart total less or equal than $min_order, add extra fee
	$woocommerce->cart->add_fee( __($extra_fee_option_label, 'woocommerce'), $extra_fee_option_cost, $extra_fee_option_taxable );
}`

**Comment by mikejolley** [comment]
You can get selected gateway ID from the current session. There are some 'fee based on gateway' extensions out there too if you don't want to code it.

Closing as this isn't a support forum. Please use Github for bug reports only in future.
