### ISSUE TITLE
Uncaught TypeError in cart.min.js when updating cart data

### ISSUE THREAD

**Issue by thorge** [woothemes/woocommerce#10459]
Updating cart data (deleting items or changing quantity) results in endless spinner.

Console error:
cart.min.js?ver=2.6.0:1 Uncaught TypeError: a.parseHTML is not a function

**Comment by mikejolley** [comment]
Missing or old version of jquery on your page. Likely not using the WordPress core supplied version of jquery.

https://api.jquery.com/jquery.parsehtml/

**Comment by mikaelz** [comment]
Had the same error. It was due conflict with jquery.tools.js

**Comment by hudjoubert** [comment]
I had the same problem! How did you do to resolve this?

**Comment by mikaelz** [comment]
Oh, checked again, as I can remember, I polished the footer javascript enqueue, reordered (my own customs moved to the end). My colleague didn't use `wp_enqueue_script` https://developer.wordpress.org/reference/functions/wp_enqueue_script/ and his code conflicted with WPs He overwrote the WPs jquery with his own one (he used jquerytools.min.js with jQuery)

**Comment by thorge** [comment]
I experienced this error when I was using an old version of jquery.
Maybe upgrade jquery to actual stable version and recheck how you integrate
it in wordpress.

Am 26.10.2016 6:09 vorm. schrieb "Michal Zuber" <notifications@github.com>:
