### ISSUE TITLE
Product Variation Prices - Wrong position of the last filter

### ISSUE THREAD

**Issue by dasllama** [woothemes/woocommerce#10464]
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [ ] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

*EXPLANATION OF THE ISSUE*

In class-wc-product-variable.php there is a filter to change the prices for the variations. It's called 'woocommerce_variation_prices' and is located here: https://github.com/woothemes/woocommerce/blob/c469ab920bb930a747d1b4926c2805f99fa0d31b/includes/class-wc-product-variable.php#L331

In the description of the filter reads that plugins will get a last chance. But if you have the prices stored in the stack, no plugin can actually affect the prices. It's because of this https://github.com/woothemes/woocommerce/blob/c469ab920bb930a747d1b4926c2805f99fa0d31b/includes/class-wc-product-variable.php#L279

The solution is easy: Just move the filter down right before the return.

**Comment by mikejolley** [comment]
Why would prices change in the same request?

Your changes are applied, and then the prices are stored in the class property to prevent re-running logic in the same request. Just ensure your filter kicks in when the function is first ran. 

The value/change is **not **stored in transient cache.

**Comment by dasllama** [comment]
Because it doesn't work. For several requests I get different prices. Sometimes I get the prices I changed, sometimes there are all prices. I dunno why. Would it be such a problem to move the outside of the control structure?

**Comment by mikejolley** [comment]
As I said, doing so would mean your (and anyone else's!) code would run every single time the prices are retrieved.

If your code doesn't work, its likely just being enqueued too late. Should be easy to debug - just stick a var dump in both your function and the get_variation_prices function. If one runs without the other, you're too late.
