### ISSUE TITLE
WooCommerce Plugin & Google Chrome 

### ISSUE THREAD

**Issue by LiAndasan** [woothemes/woocommerce#10466]
Hi,

I am using the WooCommerce plugin but I can not view any of the pages through Google Chrome. They load fine through any other browser.

Is this a common issue? How can I correct this?

**Comment by mikejolley** [comment]
Well for a start you can actually follow the instructions in our new issue template :) 

I use chrome and it works no different to any other browser with WooCommerce. No known issues.

There is not enough detail here so this issue is being closed.
