### ISSUE TITLE
On hold emails for orders created via wp-admin do not include BACS details

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#10461]
If an order is created on the backend (by the shop owner at /wp-admin/post-new.php?post_type=shop_order) and the Bank Transfer payment method (BACS) is chosen, the "on-hold" email (which actually uses the same template as "processing") does not include the Bank Transfer details, as an order created via the frontend (by the customer).

It's like the "woocommerce_email_before_order_table" is never called. I'm guessing the payment gateway classes are maybe not being loaded and so their `add_action('woocommerce_email_before_order_table', whatever);` are not triggered.

I'm not sure exactly when this started but I'm guessing 2.5

I'm giving BACS as an example, because it's on the WooCommerce core, but actually I found this problem because of a support ticket my own payment gateway "[Multibanco (IfthenPay gateway) for WooCommerce](https://wordpress.org/plugins/multibanco-ifthen-software-gateway-for-woocommerce/)" that uses the same basics as BACS (offline payment).

```
`
### WordPress Environment ###

Home URL: ...
Site URL: ...
WC Version: 2.5.3
Log Directory Writable: ✔  ...
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: pt_PT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Post Remoto: ✔
Get Remoto: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (3) ###

Flat Rate per State/Country/Region for WooCommerce: por Webdados – 2.4.5.2
Multibanco (IfthenPay gateway) for WooCommerce: por Webdados – 1.7.9.1
WooCommerce: por WooThemes – 2.5.3

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Loja base: #8 - /loja/
Carrinho: #9 - /carrinho/
Finalizar compras: #10 - /finalizar-compra/
Minha conta: #11 - /minha-conta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Twenty Sixteen
Version: 1.1
Author URL: https://pt.wordpress.org/
Child Theme: ✕ – Se estiver a modificar o tema do WooCommerce ou um tema pai que não construiu pessoalmente
recomendamos o uso de um tema filho. Veja: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by webdados** [comment]
Hi there @mikejolley,

I see that you've forced a "old" status so that actions are triggered when a new order is created, but even if you create the order as "pending" and then (after saving it the first time) change it to "on-hold" the email is triggered but **the actions of payment gateways (like BACS) are not**. The email will not include the payment instructions as it should. It seems like the payment gateway class hasn't been initiated at all, so the `add_action( 'woocommerce_email_before_order_table', array( $this, 'email_instructions' ), 10, 3 );` is never considered.

I don't think fab1f22 commit will fix this problem. Do correct me if I'm wrong, please.

**Comment by mikejolley** [comment]
I tested and it worked. Gateways are loaded before send.

**Comment by webdados** [comment]
Hi there again,

Sorry to bother again.
Just made a fresh install with last WooCommerce version (2.5.3) + your patch that closed this ticket + Twenty Sixteen + nothing else, and made the following tests:

1)
WooCommerce > Orders > Add Order > Change status to "On Hold" > Add items > Calculate Totals > Fill in client details and Choose BACS > Save Order
The client gets the email WITH the BACS details
(Your patch is definitely working because the status now "changes" from pending to on-hold and the email is triggered, along with the gateways actions)

2)
WooCommerce > Orders > Add order > Leave status as "Pending Payment" > Add items > Calculate Totals > Fill in client details and Choose BACS > Save Order
No email (as it should because there's no email for "Pending Payment").
Change the order status to "On Hold" > Save Order
The client gets the email WITHOUT the BACS details
(This is not related to your patch, because it's a "normal" change from pending to on-hold and the email is triggered, but it seems like gateways are not loaded)

Cheers

**Comment by SilverNodashi** [comment]
I have to say, after spending 4 days trying to figure out why new orders, generated from Wordpress admin, doesn't send the bank account details. Until I found this. 

Could the code perhaps be changed, so that even if an order gets saved, without first selecting "On hold", to send the BACS account details? I mean, when a client is on the phone, and I add an order manually, the order isn't "on hold" in his mind, or mine. Instead, it's being processed.
