### ISSUE TITLE
Secure api request

### ISSUE THREAD

**Issue by brokleen** [woothemes/woocommerce#10475]
Hi, i would like to use the woocommerce rest api with my mobile app but i have a security problem. 

I have created a login route with the wordpress rest api, if the login is correct the function return an token.
This token is validated in the authenticate function (class-wc-api-authentication.php) for each woocommerce api requests. 

To make requests, i need to send the consumer key, the secret key and the token. 

Imagine that case 
I have 2 users, and the first user try to hack my app and get all this keys. 
Now he just need to send
DELETE www.mydomain.com/wc-api/v3/customers/2?consumer_key=123&consumer_secret=123&token=123 

for delete the second user.

**Comment by mikejolley** [comment]
You need to understand that the keys granted by the API, when write permission is given, allow full write access, not conditional access to only certain parts of the API. API access should be granted to trusted users only. Keys should not be shared between users. If someone gains access to somebody else's access key, yes of course thats an issue, but not something the REST API itself can do anything about?

**Comment by brokleen** [comment]
Yeah it's clear for me. 
But what is the solution ? In the mobile app, the users do requests, view products, update profile.. etc.
For all this requests, the consumer and secret keys need to be send in each requests.

**Comment by mikejolley** [comment]
You'd either need to keep the keys secured on your middleware and auth the user with your service, or keep the user's keys local on their device and make requests from that to the API I assume. Not 100% sure - the rest API doesn't handle 'logins', only data manipulation with valid keys.
