### ISSUE TITLE
wc_site_is_https fatal error WC 2.5.3 WP 4.4.2

### ISSUE THREAD

**Issue by markkimsal** [woothemes/woocommerce#10477]
EXPLANATION OF THE ISSUE

Installation fails on WP 4.4.2 with 

`Fatal error: Call to undefined function wc_site_is_https() in /app/agwp/wp/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-checkout.php on line 228`

STEPS TO REPRODUCE THE ISSUE

Install on fresh system, activate WC plugin.

WORKAROUND
Comment out the check for wc_site_is_https()

```
/*
        if ( wc_site_is_https() ) {
            unset( $settings['unforce_ssl_checkout'] );
        }
        */
```

**Comment by mikejolley** [comment]
Do you have all latest files? Because this function definitely exists. Bottom of wc-conditional-functions.php

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/2.5.3/includes/wc-conditional-functions.php#L382

https://github.com/woothemes/woocommerce/blob/2.5.3/includes/wc-conditional-functions.php#L392

Both functions exist during admin requests. Seems like an issue specific to your install with outdated files.

**Comment by mikejolley** [comment]
I'll check a clean install to see how the install function handles it.

**Comment by mikejolley** [comment]
Confirmed its working fine.
