### ISSUE TITLE
Images cannot be displayed, 4.4.2_wp

### ISSUE THREAD

**Issue by EuYoga** [woothemes/woocommerce#10474]
All images cannot be displayed.
Am I setting anything wrong?

![page-shop](https://cloud.githubusercontent.com/assets/17629904/13523448/7dd9c584-e230-11e5-98ba-e11682258b78.JPG)

![image](https://cloud.githubusercontent.com/assets/17629904/13523475/a650dd40-e230-11e5-9ff5-ec1710d5c249.png)

`
### WordPress Environment ###

Home URL: http://www.eupeakmall.com
Site URL: http://www.eupeakmall.com
WC Version: 2.5.3
Log Directory Writable: ✔  /home1/eupeakma/public_html/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: zh_TW

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.17
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
遠端發佈: ✔
遠端接收: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (7) ###

Divi Builder: 由 Elegant Themes – 1.2.4.4
Elegant Themes Updater: 由 Elegant Themes – 1.2
PayPal for WooCommerce: 由 Angell EYE – 1.1.9.2
SVG Support: 由 Benbodhi – 2.2.2
Typekit Fonts for WordPress: 由 OM4 – 1.8.1
WooCommerce Customizer: 由 SkyVerge – 2.2.0
WooCommerce: 由 WooThemes – 2.5.3

### Settings ###

Force SSL: –
Currency: TWD (NT$)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

商店起點: #823 - /shop/
購物車: #824 - /cart/
結帳: #825 - /checkout/
帳號設定: #826 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Child Theme for Divi
Version: 1.0
Author URL: http://wordpress-style.net
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.6.4.4
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by reigelgallarde** [comment]
I can see your images working... you might have fixed it already...

**Comment by mikejolley** [comment]
Same.

**Comment by EuYoga** [comment]
Only the Shop pages.
But yes, I found the solution. It's solved.
Thank you all.

Share the solution here:
https://wordpress.org/support/topic/responsive-images-src-url-is-https-srcset-url-is-http-no-images-loaded?replies=19
