### ISSUE TITLE
WC_Product::get_image() returning http

### ISSUE THREAD

**Issue by sybrew** [woothemes/woocommerce#10486]
Hi,

The dashboard Product Images contain HTTP `<img>` thumbnails rather than HTTPS when `is_ssl()` is true.

This affects `WC_Admin_Post_Types::render_product_columns()` directly (case 'thumb').

I hope this helps!

Related?: https://core.trac.wordpress.org/ticket/15928

**Comment by mikejolley** [comment]
Yes the trac ticket is related, and it is a WP issue. The featured post image meta box when editing products is also affected, and if you do the same for regular posts you get the same. WC does not control this portion. Running the site over HTTPS works.
