### ISSUE TITLE
Trying to connect http://api2.nalpac.com/Help/PHP

### ISSUE THREAD

**Issue by aamong** [woothemes/woocommerce#10481]
Hi,
 i am trying to connect woocommerce with ttp://api2.nalpac.com REST API , but i cannot either connect is or authenticate is , can you please help.

Thank You

**Comment by claudiosmweb** [comment]
I don't see how it can be an issue on WooCommerce.

Please read it before open issues: https://github.com/woothemes/woocommerce/blob/master/.github/ISSUE_TEMPLATE.md
