### ISSUE TITLE
Ensure autocomplete is actually off on credit card form

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#10484]
While we are setting the `autocomplete` attribute to off on each of the credit card form's fields, it won't necessarily work in some browers (eg. latest version of Chrome ignores it).

[Here](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) it recommends setting the value to one that isn't in the scope of [possible values](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete), such as `none`. I've tested this and can confirm it does force autocomplete to be off.

I'm not sure how you feel about this, as it does feel a bit hacky, but considering Mozilla is suggesting it I thought it would be okay. Feel free to merge the attached PR if so.

**Comment by bryceadams** [comment]
My PR also covers the echeck form.

**Comment by mikejolley** [comment]
#10485
