### ISSUE TITLE
Add to cart and Add to Wishlist Button not showing in Variable products section

### ISSUE THREAD

**Issue by geekysihag** [woothemes/woocommerce#10491]
Hey i have searched everywhere on internet but could not find a solution to this issue, my Add to cart and Add to Wishlist Button's are not showing in Variable products section. I have searched everywhere on the internet, all the posts were 2-3 years old and they did not fixed my issue..

I have tried every code to fix this issue, also tried the Js fixing plugin and all the fields are filled in my variable prroducts section, still no luck !

this is the link to my variable products http://www.groot.in/shop/taktik-360-extreme-iphone-6-plus/

can anyone please help me ? It's really very urgent

**Comment by claudiosmweb** [comment]
We don't have any "Wishlist Button" on WooCommerce.
Seems like you are reporting it to the wrong plugin...

**Comment by geekysihag** [comment]
Hey man ? Did you not read the post ? Did you not see i also mentioned "Add to Cart" button ??? How can you close this thread ? Without giving me appropriate answer ? What's wrong with you dude ? I'm gonna start another issue now.

**Comment by geekysihag** [comment]
And i using Woocommerce Wishlist extension plugin for Add to Wishlist .... Can you just focus on the Add to Cart button ?

**Comment by reigelgallarde** [comment]
@geekysihag you don't have to open a new issue you can continue discussing here if needed even if it's close... also, this site is not for support issue... this site is for plugin core bugs, you should know better. And try to be nicer.

Your link given is showing error 404. As for your problem, there could be a lot of reason for this. Try changing theme, deactivate all plugins except woocommerce. See if the problem still occurs.

Again, this site is not for support issue... This is for plugin core bugs. Try asking [here](https://wordpress.org/support/plugin/woocommerce) next time. And [read this](https://wordpress.org/support/topic/before-posting-gather-the-following-details).

**Comment by BurlesonBrad** [comment]
@claudiosmweb "Lock and Limit" please? 
I've been learning a **TON** by starring and watching **A LOT** of git repos by you, Mike, Matt, Patrick, Caleb, Taylor, Max, Beka, and Brent. 
Getting notifications for things like this are totally excessive, not helpful, and a waste of everyone's time.
