### ISSUE TITLE
Sort by Newness causes duplicate products to display

### ISSUE THREAD

**Issue by techlogicalconsulting** [woothemes/woocommerce#10493]
I have adhered to all of your pre-requisites. `The problem occurs when all plugins but WooCommerce are disabled and on the Twenty-Twenty Theme.  I have found a few other posts on other sites by others having the same problem.

I have 335 products on my site.
I created them via a CSV upload.

When I select 'Sort by newness' on my shop page, repeating products are appearing on different pages.  Example:  Product A shows on page 9 and then I click on Page 10 via arrow or page number and the same Product A appears again.  Always repeating on the top row, but randomly occurring.

I do not have duplicate products, and more importantly, this issue DOES NOT happen if the sort is default or any other sort option, only by newness.

My question are:

- is this a known issue, and if so, fix coming?
- how is newness determined?  By post id, or date/time?  As I updated via CSV the post date is all the same.  This may help.

For now, I have the default sorting on, but ideally, I'd love my customers to see what is NEW first without confusing them.

I appreciate your assistance.
Kurt

### WordPress Environment ###

Home URL: http://sixdivas.com
Site URL: http://sixdivas.com
WC Version: 2.5.3
Log Directory Writable: ✔  /home/sixdivas/public_html/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (14) ###

Menu Icons: by Dzikri Aziz – 0.9.2
Ninja Forms: by The WP Ninjas – 2.9.33
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

WooCommerce Checkout Field Editor: by WooThemes – 1.4.10
WooCommerce - Store Exporter: by Visser Labs – 1.8.5
WooCommerce Stripe Gateway: by Mike Jolley – 2.6.8 – 2.6.9 is available
WooCommerce Points and Rewards: by WooThemes – 1.5.6
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.8
WooCommerce Social Login: by WooThemes / SkyVerge – 1.7.2
WooCommerce: by WooThemes – 2.5.3
WooSidebars: by WooThemes – 1.4.3
YITH WooCommerce Ajax Search: by Yithemes – 1.3.9
YITH WooCommerce Wishlist: by Yithemes – 2.0.13

### Settings ###

Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome
Version: 2.8.5
Author URL: http://www.uxthemes.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
The sorting is on post_date (date). This is a standard WordPress orderby parameter. See https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters

If all dates are identical, yes they may appear 'random'.
