### ISSUE TITLE
Coupon section on checkout breaks when coupon label contains html via woocommerce_cart_totals_coupon_label filter

### ISSUE THREAD

**Issue by apprique** [woothemes/woocommerce#10490]
EXPLANATION OF THE ISSUE

woocommerce\templates\cart\cart-totals.php contains the following code on line 38/39:
```
<th><?php wc_cart_totals_coupon_label( $coupon ); ?></th>
<td data-title="<?php wc_cart_totals_coupon_label( $coupon ); ?>"><?php wc_cart_totals_coupon_html( $coupon ); ?></td>  
```

Using the `woocommerce_cart_totals_coupon_label` filter hook it is possible to add html tags to the coupon label, which is not an unlikely scenario. However, since this label text is also reused in the data-title in line 39 using html tags will break the html code there. The solution would be to `htmlspecialchars (wc_cart_totals_coupon_label( $coupon ))` or something better for the data-title.

**Comment by claudiosmweb** [comment]
We use `esc_html()` https://github.com/woothemes/woocommerce/blob/f95ffe16d034a8019f8fe0355d41998b84560182/includes/wc-cart-functions.php#L214
People should not try to include more HTML...

But really too early to escape anything.

**Comment by mikejolley** [comment]
Missing esc_attr on the data-title
