### ISSUE TITLE
woocommerce_api_authentication_error in POST

### ISSUE THREAD

**Issue by tushpremal** [woothemes/woocommerce#10502]
I am struggling with an issue on OAUTH 1.0 authentication error.
It works fine for GET request but for the POST every time I get an error "oauth_consumer_key parameter is missing". 
Please help me with this issue it will save my lot of time and effort.

**Comment by mikejolley** [comment]
oauth_consumer_key etc cannot be POSTed. It needs to be appended to the endpoint URL regardless afaik. Use the wrappers listed on https://woothemes.github.io/woocommerce-rest-api-docs/ to avoid needing to handle it yourself.

**Comment by tushpremal** [comment]
@mikejolley  I have tried it and it worked but now i'm getting another issue invalid signature any idea about this
