### ISSUE TITLE
[2.5] Removing attributes from a product does not delete associations

### ISSUE THREAD

**Issue by franticpsyx** [woothemes/woocommerce#10506]
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.

EXPLANATION OF THE ISSUE

When deleting attributes previously added to a product, the product remains associated with the attribute terms and is listed when visiting the attribute term page, for instance: `/wp-admin/edit.php?taxonomy=pa_test-attribute&term=test-attribute-value&post_type=product`

STEPS TO REPRODUCE THE ISSUE

1. Create an attribute, "Test Attribute" and add some values, such as "Test Attribute Value".
2. Create a product, go to the **Product Data > Attributes** tab and add the created "Test Attribute / Test Attribute Value" attribute. Publish.
3. Remove the entire attribute from the product, update, and go to `/wp-admin/edit.php?taxonomy=pa_test-attribute&term=test-attribute-value&post_type=product`. You will find the product is still listed there, although it doesn't seem to contain any attributes under **Product Data > Attributes**.

**Comment by mikejolley** [comment]
No luck reproducing this on master.

If I assign the attribute/terms than save, it's listed on edit.php?taxonomy=pa_test-attribute&term=value-1&post_type=product

If I remove the attribute group and save again, its removed from the list. Seems to be as it should.

**Comment by franticpsyx** [comment]
>No luck reproducing this on master.

@mikejolley I'm on latest, downloaded from .org. Fresh install. 

Watch this: http://cl.ly/3G3U101v2I2h

**Comment by mikejolley** [comment]
@claudiosmweb hmm this one actually looks familiar. Did you patch in master/have link to commit?

**Comment by claudiosmweb** [comment]
@mikejolley @franticpsyx confirmed.
Broken on 2.5.3 and master.

But have a "secret" to make it works :P

Mike was not able to observe the error because he clicked the "Save Attributes" button before click in the "Update" button.
If you do it, will works fine, but if you don't click in "Save Attributes" and just update the products you'll be able to reproduce the issue.
And Need to add the attribute again, then remove and save your attributes and of course, update the product again to remove.

**Comment by franticpsyx** [comment]
>Mike was not able to observe the error because he clicked the "Save Attributes" button before click in the "Update" button.

:+1: Figured it must have been something in the procedure we followed that wasn't identical. Videos/screen grabs always help!
