### ISSUE TITLE
Customer update webhook not firing when customer changes billing or shipping address

### ISSUE THREAD

**Issue by teckel12** [woothemes/woocommerce#10505]
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [x] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [x] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

The customer update API webhook fires when customer information changes in the Wordpress back-end.  Also, it fires when a customer edits their password and account details.  However, when a customer edits their billing or shipping address from the My Account page, the customer updated API webhook doesn't fire.

STEPS TO REPRODUCE THE ISSUE

1. Create a new customer from the website front-end.
2. Visit the My Account page with the new customer (should automatically go here).
3. Click "Edit" for either Billing Address or Shipping Address.
4. Make changes to customer information.
5. Click "Save Address" button.
6. No customer.updated webhook fires even though the customer information was updated.

SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: /medicaltech
Site URL: /medicaltech
WC Version: 2.5.3
Log Directory Writable: ✔ /var/www/bionix/main/wp-content/uploads/sites/2/wc-logs/
WP Version: 4.4.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.1.63
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (9) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.4.7
Authorize.Net WooCommerce Addon: by Syed Nazrul Hassan – 1.0.4
Meta Box: by Rilwis – 4.8.2
Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
Unique Headers: by Ryan Hellyer – 999.999.999 (CUSTOMIZED v1.5.1)
Woocommerce Custom Tabs: by WebshopLogic – 999.999.999 (TO AVOID UPGRADE TO LITE VERSION - 1.0.18 PRO)
WooCommerce Dynamic Pricing: by Lucas Stark – 2.10.11
WooCommerce Purchase Order Payment Gateway: by WooThemes – 1.0.0 – 1.1.3 is available
WooCommerce: by WooThemes – 2.5.3
Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
Gravity Forms Placeholder Add-On: by Able Engine
William Wilkerson – 1.1.0

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Rich Text Tags, Categories, and Taxonomies: by Katz Web Services
Inc. – 1.7.3

Force SSL: by Trevor Turk
BestWebLayout – 1.3

Multisite User Management: by Brent Shepherd – 1.1
Gravity Forms: by rocketgenius – 1.9.16
WooThemes Helper: by WooThemes – 1.5.9
Yoast SEO: by Team Yoast – 3.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #2 - /
Cart: #60 - /cart/
Checkout: #61 - /checkout/
My Account: #62 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Bionix
Version: 1.0
Author URL: http://www.threadgroup.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: bionix/woocommerce/archive-product.php
bionix/woocommerce/auth/footer.php
bionix/woocommerce/auth/form-grant-access.php
bionix/woocommerce/auth/form-login.php
bionix/woocommerce/auth/header.php
bionix/woocommerce/cart/cart-empty.php
bionix/woocommerce/cart/cart-item-data.php
bionix/woocommerce/cart/cart-shipping.php
bionix/woocommerce/cart/cart-totals.php
bionix/woocommerce/cart/cart.php
bionix/woocommerce/cart/cross-sells.php
bionix/woocommerce/cart/mini-cart.php
bionix/woocommerce/cart/proceed-to-checkout-button.php
bionix/woocommerce/cart/shipping-calculator.php
bionix/woocommerce/checkout/cart-errors.php
bionix/woocommerce/checkout/form-billing.php
bionix/woocommerce/checkout/form-checkout.php
bionix/woocommerce/checkout/form-coupon.php
bionix/woocommerce/checkout/form-login.php
bionix/woocommerce/checkout/form-pay.php
bionix/woocommerce/checkout/form-shipping.php
bionix/woocommerce/checkout/payment-method.php
bionix/woocommerce/checkout/payment.php
bionix/woocommerce/checkout/review-order.php
bionix/woocommerce/checkout/thankyou.php
bionix/woocommerce/content-product.php
bionix/woocommerce/content-product_cat.php
bionix/woocommerce/content-single-product.php
bionix/woocommerce/content-widget-product.php
bionix/woocommerce/emails/admin-cancelled-order.php
bionix/woocommerce/emails/admin-failed-order.php
bionix/woocommerce/emails/admin-new-order.php
bionix/woocommerce/emails/customer-completed-order.php
bionix/woocommerce/emails/customer-invoice.php
bionix/woocommerce/emails/customer-new-account.php
bionix/woocommerce/emails/customer-note.php
bionix/woocommerce/emails/customer-processing-order.php
bionix/woocommerce/emails/customer-refunded-order.php
bionix/woocommerce/emails/customer-reset-password.php
bionix/woocommerce/emails/email-addresses.php
bionix/woocommerce/emails/email-customer-details.php
bionix/woocommerce/emails/email-footer.php
bionix/woocommerce/emails/email-header.php
bionix/woocommerce/emails/email-order-details.php
bionix/woocommerce/emails/email-order-items.php
bionix/woocommerce/emails/email-styles.php
bionix/woocommerce/emails/plain/admin-cancelled-order.php
bionix/woocommerce/emails/plain/admin-failed-order.php
bionix/woocommerce/emails/plain/admin-new-order.php
bionix/woocommerce/emails/plain/customer-completed-order.php
bionix/woocommerce/emails/plain/customer-invoice.php
bionix/woocommerce/emails/plain/customer-new-account.php
bionix/woocommerce/emails/plain/customer-note.php
bionix/woocommerce/emails/plain/customer-processing-order.php
bionix/woocommerce/emails/plain/customer-refunded-order.php
bionix/woocommerce/emails/plain/customer-reset-password.php
bionix/woocommerce/emails/plain/email-addresses.php
bionix/woocommerce/emails/plain/email-customer-details.php
bionix/woocommerce/emails/plain/email-order-details.php
bionix/woocommerce/emails/plain/email-order-items.php
bionix/woocommerce/global/breadcrumb.php
bionix/woocommerce/global/form-login.php
bionix/woocommerce/global/quantity-input.php
bionix/woocommerce/global/sidebar.php
bionix/woocommerce/global/wrapper-end.php
bionix/woocommerce/global/wrapper-start.php
bionix/woocommerce/loop/add-to-cart.php
bionix/woocommerce/loop/loop-end.php
bionix/woocommerce/loop/loop-start.php
bionix/woocommerce/loop/no-products-found.php
bionix/woocommerce/loop/orderby.php
bionix/woocommerce/loop/pagination.php
bionix/woocommerce/loop/price.php
bionix/woocommerce/loop/rating.php
bionix/woocommerce/loop/result-count.php
bionix/woocommerce/loop/sale-flash.php
bionix/woocommerce/myaccount/form-add-payment-method.php
bionix/woocommerce/myaccount/form-edit-account.php
bionix/woocommerce/myaccount/form-edit-address.php
bionix/woocommerce/myaccount/form-login.php
bionix/woocommerce/myaccount/form-lost-password.php
bionix/woocommerce/myaccount/my-account.php
bionix/woocommerce/myaccount/my-address.php
bionix/woocommerce/myaccount/my-downloads.php
bionix/woocommerce/myaccount/my-orders.php
bionix/woocommerce/myaccount/view-order.php
bionix/woocommerce/notices/error.php
bionix/woocommerce/notices/notice.php
bionix/woocommerce/notices/success.php
bionix/woocommerce/order/form-tracking.php
bionix/woocommerce/order/order-again.php
bionix/woocommerce/order/order-details-customer.php
bionix/woocommerce/order/order-details-item.php
bionix/woocommerce/order/order-details.php
bionix/woocommerce/order/tracking.php
bionix/woocommerce/product-searchform.php
bionix/woocommerce/single-product/add-to-cart/external.php
bionix/woocommerce/single-product/add-to-cart/grouped.php
bionix/woocommerce/single-product/add-to-cart/simple.php
bionix/woocommerce/single-product/add-to-cart/variable.php
bionix/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
bionix/woocommerce/single-product/add-to-cart/variation.php
bionix/woocommerce/single-product/meta.php
bionix/woocommerce/single-product/price.php
bionix/woocommerce/single-product/product-attributes.php
bionix/woocommerce/single-product/product-image.php
bionix/woocommerce/single-product/product-thumbnails.php
bionix/woocommerce/single-product/rating.php
bionix/woocommerce/single-product/related.php
bionix/woocommerce/single-product/review.php
bionix/woocommerce/single-product/sale-flash.php
bionix/woocommerce/single-product/share.php
bionix/woocommerce/single-product/short-description.php
bionix/woocommerce/single-product/tabs/additional-information.php
bionix/woocommerce/single-product/tabs/description.php
bionix/woocommerce/single-product/tabs/tabs.php
bionix/woocommerce/single-product/title.php
bionix/woocommerce/single-product/up-sells.php
bionix/woocommerce/single-product-reviews.php
bionix/woocommerce/single-product.php
bionix/woocommerce/taxonomy-product_cat.php
bionix/woocommerce/taxonomy-product_tag.php

`

**Comment by teckel12** [comment]
I made the changes and it still doesn't trigger for me.

**Comment by mikejolley** [comment]
@claudiosmweb can you confirm this works after making your change? Is there a way to test to put minds at ease?

**Comment by claudiosmweb** [comment]
@teckel12 @mikejolley I just tested it again and works fine for billing and shipping.

But I just see that we save the topics here: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L522-L523

So @teckel12 you need to delete your webhook and create again.

**Comment by teckel12** [comment]
Got it!  Re-created webhook and I can confirm it now triggers.  Thanks and sorry for the confusion.

**Comment by claudiosmweb** [comment]
@teckel12 please, don't reopen issues, we can receive notifications from closed issues and opening a new issue will not do anything faster.

**Comment by jameel789** [comment]
Hi Claudio , the customer addresses when changed on the checkout page does not trigger the customer update webhook, thanks to your solution i got it working on the my account page but how can i get to trigger customer update on checkout?

**Comment by nerdy-kronos** [comment]
Hi,
I am facing the same issue and even checked the class-wc-webhook.php and patch done by @claudiosanches already exists.
I am newbie to github and please excuse for mistakes/noobiness.
Please help

**Comment by partounian** [comment]
@jameel789 Were you able to solve this issue?

**Comment by nerdy-kronos** [comment]
@partounian see this thread [https://wordpress.org/support/topic/checkout-billing-address-does-reflect-the-saved-billing-address/](url).

**Comment by ondigusho** [comment]
Hello . Is there a solution to this? I see this ticket last was updated in 2017. When I upgrade from Version 3.5.2 woocomerce to Version 3.7.1 billing and shipping address on user's profile do not save anymore. I did ty the code changes suggested above. Any suggestion really appreciated. Thank You.
