### ISSUE TITLE
[Ajax] Checkout: Payment method doesn't switch

### ISSUE THREAD

**Issue by panigrc** [woothemes/woocommerce#10509]
- [x] I am using the latest stable release of WooCommerce (v. 2.5.3).
- [ ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [ ] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

When clicking on different payment method radio, when returning from the Ajax call, it returns to the default payment method.

The issue is that the value of 'checked' radio isn't being respected.

In file /wp-content/plugins/woocommerce/includes/class-wc-ajax.php line 288 you set the session variable 'chosen_payment_method' to $_POST['payment_method']
But in my ajax response the 'payment_method' is included in a sting like the following:

`post_data: billing_first_name=xxx&billing_last_name=xxx&billing_company=&billing_email=xxx@xxx.xxx&billing_phone=xxxxxxxx&billing_country=XX&billing_address_1=xxxxxxx&billing_address_2=&billing_city=xxxx&billing_state=E&billing_postcode=xxxxx&shipping_first_name=xxxxx&shipping_last_name=xxxxxxx&shipping_company=&shipping_country=XX&shipping_address_1=xxxxxxxxx&shipping_address_2=&shipping_city=xxxx&shipping_state=E&shipping_postcode=xxxxx&order_comments=&shipping_method%5B0%5D=flat_rate%3Aacs-%CE%B5%CE%BB%CF%84%CE%AC-courier&payment_method=cod&terms-field=1&_wpnonce=b08cc68520&_wp_http_referer=%2Fcheckout%2F%3Fwc-ajax%3Dupdate_order_review `

So eventually  payment_method variable is included in the post_data string so I did this solution:

before line 288 I added:

`parse_str($_POST['post_data']);`

and changed line 288 to:

`WC()->session->set( 'chosen_payment_method', empty( $payment_method ) ? '' : $payment_method );`

And works perfectly.

My question is, why does it do this? Probably it's an issue of Ajax call not sending as $_POST data the payment_method variable.

**Comment by mikejolley** [comment]
It's included here: https://dl.dropboxusercontent.com/s/k14vco9b9dole2h/2016-03-09%20at%2011.13.png?dl=0 This is part of the post data.

method is retrieved using:

return wc_checkout_form.$order_review.find( 'input[name="payment_method"]:checked' ).val();

There is nothing wrong with this, and no workaround is needed. If the data is not posting correctly, no doubt the theme is renaming or moving around the payment methods in a way that is not supported. Do the steps outlined in the new issue form to confirm this.

You can comment back here once you've found the cause, but this is not a core issue.
