### ISSUE TITLE
WooCommerce is Breaking Ninja Forms

### ISSUE THREAD

**Issue by nickwiebe** [woothemes/woocommerce#10512]
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [ ] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [x] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [x] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

I have version 2.5.3 of WooCommerce and I think the latest update may have broke my forms.  I'm using Ninja forms and the forms work fine when I'm logged into my wordpress, they send emails and show the proper success messages, but if I'm not logged into wordpress, then they forms do nothing, submit nothing, and send nothing.

After 4+ hours of searching reading and trying steps to fix this, I started disabling plugins one at a time and found that when I disabled WooCommerce, my Ninja forms would once again work without being logged into Wordpress.  I need both WooCommerce to be active and for my customer request to be submitted from my site forms without being logged in.

STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

Try filling out the form on my site at http://www.edic-usa.com/contact/ without being logged in and you will see that the form just clears, you get no success message and no data is emailed or added to the database.

Disable WooCommerce plugin and log out of wordpress.  go back to http://www.edic-usa.com/contact/ and try the form and you will see that it works, you will get the success message and an email and there will be a database record.

SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
`
### WordPress Environment ###

Home URL: http://www.edic-usa.com
Site URL: http://www.edic-usa.com
WC Version: 2.5.3
Log Directory Writable: ✔  /home/edicusa0/public_html/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (15) ###

Features: by WooThemes – 1.5.0
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Loco Translate: by Tim Whitlock – 1.5.5
Ninja Forms: by The WP Ninjas – 2.9.33
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Safe Search Replace: by Benjamin Sommer – 2.0.1
SG CachePress: by SiteGround – 2.3.3
Simple 301 Redirects: by Scott Nellé – 1.07
Testimonials: by WooThemes – 1.5.4
TinyMCE Advanced: by Andrew Ozz – 4.2.8
WooCommerce Catalog Visibility Options: by Lucas Stark – 2.7.0
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.5.1
WooCommerce: by WooThemes – 2.5.3
WooThemes Helper: by WooThemes – 1.5.9
Yoast SEO: by Team Yoast – 3.1.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /products/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: For The Cause
Version: 1.1.11
Author URL: http://www.woothemes.com
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Tested default Ninja Form with WooCommerce 2.5.3 locally without issue:

https://dl.dropboxusercontent.com/s/ukx0sg47y0190ep/2016-03-09%20at%2011.28.png?dl=0

This form used regular POST submission, not AJAX. TBH I think its more likely cache - I noticed X-Cache headers on your page for example, and I see you use SG CachePress. Try the "Exclude URLs From Dynamic Caching" setting. There may be some WC specific caching rules in affect at host level.

Closing as this is not reproducible and works as expected in testing.

**Comment by nickwiebe** [comment]
Mike,

I have tried the exclude function in the cache plugin and I have tried
deactivating the Cache plugin and neither of these options has worked.  The
only thing that has worked is deactivating woocommerce.  The form works
when you are logged in to wordpress but doesn't work when you are not.

Nick Wiebe
509.435.3284
www.wiebemarketing.com

<http://www.wiebemarketing.com/contact.html>

**Comment by mikejolley** [comment]
Regardless of WooCommerce being active, this worked perfectly on my local install. Thats why I suggested caching. I have no cache locally and no issue. On your site there are caching headers being set (X-Cache ).

**Comment by mikejolley** [comment]
Before post https://dl.dropboxusercontent.com/s/zuwwp6yf5hw8oo9/2016-03-09%20at%2016.38.png?dl=0

After post https://dl.dropboxusercontent.com/s/3m63k352i1qjx5j/2016-03-09%20at%2016.37.png?dl=0

**Comment by nickwiebe** [comment]
Yes, but I did flush all the cache on the server and site and then turned
it off completely on the server and the plugin in wordpress and then tried
the forms without being logged into the site and they still didn't work.

The forms work perfectly when I'm logged into wordpress but for some reason
or setting, woocommerce won't allow the forms to work if you are not logged
into wordpress.  When I disable woocommerce, then the forms work when you
are not logged into wordpress or you are logged into wordpress.

I turned off every plugin I have installed to test and see what was causing
the problem and the only one that effected the problem was
woocommerce...I'm really in a panic here as my customers can't register
warranty or contact support from my site and I don't know what else to do.

Nick Wiebe
509.435.3284
www.wiebemarketing.com

<http://www.wiebemarketing.com/contact.html>

**Comment by BurlesonBrad** [comment]
Mike: Ya think Job or Joel would hire me to be the Ban Hammer? I mean ....obviously it would need to be a secret.  Not listed on the */about/meet-the-team/* page or anything fancy and official.:wink:

My only job would be to help people like @nickwiebe understand that you are a programming rocket ninja genius who is in charge of a platform that transacts **BILLIONS** of dollars across the **WHOLE FRIGGIN' WORLD**, and that while you are indeed very cordial in handling support issues on Github...

# TIME IS NOT INFINITE!!

and while in the midst of hashing out pulls and merges, stopping and having to bounce back and forth after you've clearly **closed the thread already** is a total break in concentration :facepunch:

> ...I'm really in a panic here

We've all been there bro.  Some of us more than others :disappointed: But, please understand that you are sending of a ding, a ping, a ring, a chirp, and a chime on everyone's device, tablet, laptop, cell phone, office computer, **_laptop by the 'dad' chair_** who is watching the WooCommerce Repo.  **Yes, that's around 344 people** 
![woo-git-watchers](https://cloud.githubusercontent.com/assets/6208757/13647811/6e6e2bca-e5fb-11e5-9556-91792d093600.png) ....and, again, they're not on Github to give support.

I will **HAPPILY** make sure that you specifically get your question answered if you'll swing by [**HERE**](https://facebook.com/groups/woohelp)  _I can almost bet that I know **exactly** who will chime in with the **answer** to your issue and I'll even be sure to tag him in your post @nickwiebe_ :+1:   

If you'd like to see the **EXACT** sam thing that Mike Jolley is looking at, then I would like to kindly suggest
# [**THIS LINK TO SERVERPRESS**](https://serverpress.com/checkout/?edd_action=add_to_cart&download_id=9183&utm_source=AndrewWikel&utm_medium=SexyBeast&utm_term=FamilyMan&utm_content=BOWTIES&utm_campaign=HaveGotToGO) 
**_yup, it's FREE_**

**_LOCK AND LIMIT_**

**Comment by mikejolley** [comment]
@BurlesonBrad no comment :)

@nickwiebe many cache plugins/solutions treat logged out vs logged in users differently thats why I'm still swaying towards that. Whilst you're debugging this conflict/checking logs/sorting out cache, enable the '**ajax submission method**' on your ninja form. It won't need to POST then and will work regardless of caching!

**Comment by nickwiebe** [comment]
Mike,

Apparently I'm interrupting Brad's day so sorry about that...didn't realize
I was speaking to the group rather than just you when replying to your
email, and I'm sorry in advance for doing it one more time.

I did try using the ajax submission method from the ninja form, but when
you click submit it just changes the button to processing and never goes
anywhere.

I have loaded up several other form creation plugins and they have all
worked in my testing so rather than incur the wrath of Brad again, I'm
going to chalk it up as a Ninja form problem and use a different plugin
that works.  I do appreciate you taking the time to respond to me in a
professional manner.

Best,

Nick Wiebe
509.435.3284
www.wiebemarketing.com

<http://www.wiebemarketing.com/contact.html>

**Comment by rgaynor72** [comment]
I know this issue has been closed on here and I know that Brad is annoyed by the topic, and I know that Nick has chosen to scrap Ninja Forms for an alternative.  That being said, I have paid for add-ons to Ninja that don't allow me to scrap it.  I have the same exact issue and I am not running a caching plugin.  I am hosted on GoDaddy which won't allow me to change any server side cache settings.  I have spoken to Ninja support and they said they tried to work with Woocommerce to support to troubleshoot and fix but received no response.  Would love to see if someone could find a solution to this other than deactivating WooCommerce.

**Comment by mikejolley** [comment]
@rgaynor72 no one from our side has ever been able to replicate this bug, and I think the same from ninja forms.

**Comment by rgaynor72** [comment]
I understand that which makes it very difficult to fix, but multiple people are having the issue.  I would be willing to pay a reasonable fee to have you troubleshoot with me on my site and potentially find a solution.

**Comment by mikejolley** [comment]
You know you can turn on ajax submission to work around it?

**Comment by rgaynor72** [comment]
I wish that were true, but like Nick when I turn on AJAX submissions the submit button turns to Processing and nothing ever happens.

**Comment by mikejolley** [comment]
With WC on and off? Did you check browser JS console?

**Comment by rgaynor72** [comment]
Only with WC on. I am not a developer so I am sorry but I don't know what you mean by browser JS console.

**Comment by mikejolley** [comment]
Have you tested with it off for same thing?

In Chrome, View > Developer > Javascript Console

**Comment by rgaynor72** [comment]
Yes I have tested with it off using both AJAX and not using AJAX and the form works fine.  It only stops working when I activate WC.

**Comment by mikejolley** [comment]
And the console?

**Comment by BurlesonBrad** [comment]
Robert:
- [ ] **open site in google chrome**
- [ ] **right click until you see this** 
![robert](https://cloud.githubusercontent.com/assets/6208757/14729296/3b6d7036-0802-11e6-8ef0-6361c4dd349b.png)
- [ ] **click Inspect**
- [ ] **click Console** 
![robert2](https://cloud.githubusercontent.com/assets/6208757/14729328/827645de-0802-11e6-9b9c-a94f48b87346.png)
- [ ] [download this ](https://app.prntscr.com/en/index.html) <-- CLICK!
- [ ] **take screenshot**
- [ ] **save image**
- [ ] **paste image in github** _(which is still not for support)_

**Comment by BurlesonBrad** [comment]
Robert and Nick please understand that your public display of competency isn't a "bother" to me at all :+1: I do this all the time in the .org/ repo area for Woo and for Storefront and anywhere else I can when I've got time. So does @mikejolley and dozens of other ninjas! Plenty of people are dedicated to giving support, and Automattic even pays people very nicely to do nothing but give support :stuck_out_tongue_winking_eye: Github is built, made and used for code merges, bug fixes, build checks, and version control. 

Your capacity to understand that concept is not in the least bit a bother to me at all.
