### ISSUE TITLE
Brands-Plugin with WooCommerce REST-API

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10517]
Is there a method how use the woocommerce-brands plugin with the woocommerce REST-API?

**Comment by mikejolley** [comment]
Brands taxonomy is not included in the REST API at present. This may be added after we move to the WP API (#10435), but not in v3.

**Comment by mikejolley** [comment]
cc @claudiosmweb

**Comment by claudiosmweb** [comment]
@mikejolley brands taxonomy is not part of the core WooCommerce, of course... So I see that should not be part of the API too. The same happens for things like subscriptions... It's need to be done in WooCommerce Brands.

**Comment by ad-on-is** [comment]
Makes sense, not to implement it in the API.

Since it's a functionality I need within the next 2-3 weeks, I'd like to ask you if there're some coding guidelines how to implement the API in other plugins? Something that it's future-proof when you guys switch to the WP-API?

I could make a pull-request then.

**Comment by claudiosmweb** [comment]
> I'd like to ask you if there're some coding guidelines how to implement the API in other plugins

We don't have docs for it I think, but it's not hard.

First you need to create a class for your API, for example:

```php
class My_WC_API_Stuffs extends WC_API_Resource {

	protected $base = '/stuffs';

	public function register_routes( $routes ) {

		# GET /stuffs
		$routes[ $this->base ] = array(
			array( array( $this, 'get_stuffs' ), WC_API_Server::READABLE ),
		);

		return $routes;
	}

	public function get_stuffs( $fields = null, $filter = array(), $page = 1 ) {
		$stuffs = array( 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 );

		return array( 'stuffs' => $stuffs );
	}
}
```

See or another API class to understand how it works for POST, GET, PUT and DELETE. It's easy.

Then you must include your API class within `woocommerce_api_loaded`.

```php
function my_include_api_class() {
    include_once( PATH_TO_YOUR_API_CLASS );
}

add_action( 'woocommerce_api_loaded', 'my_include_api_class' );
```

Then you can register your class using the `woocommerce_api_classes` filter.

```php
function my_register_api_class( $classes ) {
    $classes[] = 'My_WC_API_Stuffs';

    return $classes;
}

add_filter( 'woocommerce_api_classes', 'my_register_api_class' );
```

And it's done, you have a new endpoint now.

> Something that it's future-proof when you guys switch to the WP-API?

No, you will need write again using WP-API, which is what we are doing right now in #10435

**Comment by ad-on-is** [comment]
Thank you for such an detailed answer, thats definitely a huge help for me ;-)


> No, you will need write again using WP-API, which is what we are doing right now in #10435

Another problem that bothers me right now:
We are currently using a more complicated and error-prone method to import products from one system to woocommerce. 
Now, that the project is getting larger and nearly unmaintainable, and thanks to your fully functional API, we've made the decision to integrate our import-process with the API. 
So building it with the WooCommerce REST-API and telling the customer that I'll have to rewrite it again isn't going to be very funny :-)

Is there any rough date, when you are going to finish the move to WP-API?
Will the WooCommerce REST API still exist? If yes, will it also be maintained?

**Comment by claudiosmweb** [comment]
> Is there any rough date, when you are going to finish the move to WP-API?

WooCommerce 2.6.

>  Will the WooCommerce REST API still exist? If yes, will it also be maintained?

Yes, at least until WooCommerce 3.0.

**Comment by ad-on-is** [comment]
That's great news, thank you so much ;-)

**Comment by ad-on-is** [comment]
Is there any approximate release date when 2.6 will be published? 
We'd like to know if we should start implementing WooCommerce REST API right now, or wait until 2.6 is out, and start right away with WP REST API.

**Comment by claudiosmweb** [comment]
Q2 2016

**Comment by ad-on-is** [comment]
Thanks!
