### ISSUE TITLE
Remove colons from field labels on settings pages

### ISSUE THREAD

**Issue by lutrov** [woothemes/woocommerce#10524]
Wordpress doesn't use trailing colons (:) for field labels. Woocommerce doesn't either in most of its admin screens, but it does in some. Please clean up the code to have a consistent user interface.

For instance, the Tax Options screen has "Calculate Tax Based On:" and "Additional Tax Classes". One has a colon, one doesn't.

From what I can see, the following files need to be changed:

* includes/admin/meta-boxes/class-wc-meta-box-product-data.php
* includes/admin/meta-boxes/views/html-order-download-permission.php
* includes/admin/meta-boxes/views/html-order-download-permission.php
* includes/admin/meta-boxes/views/html-order-items.php
* includes/admin/meta-boxes/views/html-order-items.php
* includes/admin/meta-boxes/views/html-order-items.php
* includes/admin/meta-boxes/views/html-product-attribute.php
* includes/admin/meta-boxes/views/html-product-attribute.php
* includes/admin/meta-boxes/views/html-variation-admin.php

**Comment by mikejolley** [comment]
Useful on some pages, like in attributes where there is no field, just a name: value pair. Settings can be made consistent however.
