### ISSUE TITLE
Prettyphotos youtube embed issues

### ISSUE THREAD

**Issue by nickdollahz** [woothemes/woocommerce#10521]
## EXPLANATION OF THE ISSUE

Using Woocommerce 2.5.3 included version of prettyphotos.

Embedding youtube videos on https website doesn't work.

## STEPS TO REPRODUCE THE ISSUE

1. Add the following html to product page:
<a  href="https://www.youtube.com/watch?v=sUH1WUe5hCQ" data-rel="prettyPhoto">Click ME</a>
2. Video doesnt embed on google chrome. Error on Google Chrome console unable to load unsecure content on secure page

Work around:
Modify jquery.prettyPhoto.init.js and change the http to https
movie="http**s**://www.youtube.com/embed/"+

Although every time I update woocommerce I have to change it again. It would be nice if support for https could be added without modification. Especially on client websites where they may update the plugin without knowing. 

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://erilocs.com.mx
Site URL: https://erilocs.com.mx
WC Version: 2.5.3
Log Directory Writable: ✔  / Home / content / p3pnexwpnas08_data02 / 45/2690845 / html / wp-content / uploads / wc-logs /
WP Version: 4.4.2
WP Multisite: -
WP Memory Limit: 256 MB
WP Debug Mode: -
Language: es_MX

### Server Environment ###

Server Info: Apache
PHP Version: 05/04/42
PHP Post Max Size: 65MB
PHP Time Limit: 30
PHP Max Input Vars: 10:00
SUHOSIN Installed: -
MySQL Version: 05/05/43
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (11) ###

Chimpy Lite - MailChimp WordPress Plugin: by RightPress - 1.0.3
display Widgets: by Strategy11 - 2.05
EWWW Image Optimizer: by Shane Bishop - 2.5.9
Google Analytics by Yoast: by Team Yoast - 5.4.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) - 2.2.6
WooCommerce - APG Weight and Postcode / State / Country Shipping: by Art Project Group - 1.9.0.6
WooCommerce Offline Credit Card Processing: by WP Lab - 1.7.3
WooCommerce Variation Swatches and Photos: by Lucas Stark - 2.1.0 - 2.1.3 is available
WooCommerce: by WooThemes - 2.5.3
Yoast SEO: by Team Yoast - 3.1.1
wpMandrill: by Mandrill - 1.33

### Settings ###

Force SSL: ✔
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Tienda Base: # 7 - / shop /
Carro: # 8 - / shopping /
Pago: # 9 - / box /
Mi cuenta: # 10 - / my-account /

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: pinkhair
Version: 1.0.0
Author URL: http://underscores.me/
Child Theme: ✕ - If you are modifying or theme WooCommerce you did not do your recommend using a child theme (child theme). See How to create a theme child (child theme)
WooCommerce Support: ✔

### Templates ###

Overrides: pinkhair/woocommerce/content-single-product.php 
pinkhair/woocommerce/emails/customer-processing-order.php 
pinkhair/woocommerce/single-product/product-image.php

`

**Comment by asteriskmmt** [comment]
The solution to this problem is very simple and could easily be implemented in future releases, but in the time being, here is the fix for anyone who cares.

Open /wp-content/plugins/woocommerce/assets/js/prettyPhoto/jquery.prettyPhoto.min.js

Find and replace 'http://' with '//'

Save.

Upload.

Ctrl + f5 to refresh and now your videos will load over https with no problem.
