### ISSUE TITLE
Woocommerce through my site into a redirect loop

### ISSUE THREAD

**Issue by partounian** [woothemes/woocommerce#10527]
I'm currently running a server with the latest version of nginx, php7, and mariadb. I was installing https and everything was working perfectly, until it randomly through itself into a redirect loop, I've removed the redirect to https from the nginx config and set force ssl to false in the wp-config but I believe enabling force ssl in woocommerce settings broke the site. How could I remove that the redirect from the config? I believe it's in the database and looked but couldn't find it. Any help would greatly be appreciated. I have no access to anything on the site at all, so no report and can't disable it from the backend.

**Comment by mikejolley** [comment]
We cannot really help you with server technical support here - we deal with bugs only on github. Force SSL only affects checkout, not the entire site. So unless you changed the site/home URLs of WordPress to HTTPS its not that.

Ask the host if you're stuck.
