### ISSUE TITLE
the problem with the transition to the settings section

### ISSUE THREAD

**Issue by bessarabkin** [woothemes/woocommerce#10525]
Woocommerce 2.5.3

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

I can not go to the Settings section

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

Fatal error: Class 'WC_Gateway_Paypal' not found in /home/vodanaso/vodanasos.com.ua/www/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 104

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
You are missing files. Reinstall/reupload WooCommerce.

**Comment by bessarabkin** [comment]
Thanks for the answer. And what is the probability of losing the goods and categories?

**Comment by mikejolley** [comment]
If you just re-upload the plugin via FTP, no data will be lost.

**Comment by bessarabkin** [comment]
If I understood correctly: you need to copy the installer folder woocommerce via ftp to a folder with plagins. Do not copy the replacement, and the growth of the missing copy?

**Comment by mikejolley** [comment]
what? 

Download from https://wordpress.org/plugins/woocommerce/
Upload to wp-content/plugins/ overwriting what is already there.

Job done :)

**Comment by bessarabkin** [comment]
Thank you

**Comment by bessarabkin** [comment]
I'm going to try now

**Comment by bessarabkin** [comment]
friend, thank you very much, rescued
