### ISSUE TITLE
class-wc-gateway-paypal-ipn-handler.php disable emails

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10528]
## EXPLANATION OF THE ISSUE
File: class-wc-gateway-paypal-ipn-handler.php
Currently WC sends email to customers by default after actions in paypal. On order, on payment, on cancel etc...

## STEPS TO REPRODUCE THE ISSUE

1. any action that will activate (payment, cancel of payment) IPN will run the handler file

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

My request is to add to DashBaord the option to disable these emails.
Some merchants prefer to send emails on their own rather than something automatic.

**Comment by mikejolley** [comment]
These are _not_ customer emails, they send to admin only to inform them about IPN related status changes.

**Comment by test101test101** [comment]
How can you tell to whom they are sending? Comments doesn't explain it and users (like me) might think that it takes the receipent from dashboard email setting, where you can define client as recipient.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php#L319
