### ISSUE TITLE
Variations -> Don't require ID for update, match on SKU

### ISSUE THREAD

**Issue by torrelasley** [woothemes/woocommerce#10523]
In the REST API, if you do not pass a Product ID during the products/bulk request then it will look it up based on SKU. This is handy for bulk loads so you don't have to look up the ID for each record.

However, for Variations if you don't pass the ID then it will not look it up and instead attempt to create a new Variation. If you have an existing Variation with that SKU then it will fail with 'woocommerce_api_product_sku_already_exists'

**Comment by mikejolley** [comment]
Turn that into a PR and we'll get it merged :+1:

**Comment by torrelasley** [comment]
I created the Pull Request, let me know if I missed a step, thanks!

**Comment by mikejolley** [comment]
I don't think you did as its not here https://github.com/woothemes/woocommerce/pulls

**Comment by torrelasley** [comment]
Sorry about that, it should be there now!
