### ISSUE TITLE
Adding number 5 at beginning of page title makes it the Shop page

### ISSUE THREAD

**Issue by ghostpool** [woothemes/woocommerce#10532]
Really odd bug. If you create a new page and add the number 5 at the beginning of the page title e.g. "5 column page" it turns the page into a WooCommerce shop page. This only happens with the number 5, any other number is fine. This occurs in the Twenty Sixteen theme, no plugins except WooCommerce enabled and only happens in the latest WooCommerce update - it does not occur in v2.5.2.

`
### WordPress Environment ###

Home URL: http://habitatdemo.wpengine.com
Site URL: http://habitatdemo.wpengine.com
WC Version: 2.5.3
Log Directory Writable: ✔  /nas/content/staging/habitatdemo/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.3

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
See https://core.trac.wordpress.org/ticket/35902
