### ISSUE TITLE
Woocommerce API  getting products from a category in random order

### ISSUE THREAD

**Issue by ahsanalishahid** [woothemes/woocommerce#10539]
Hi There,

I am working with an Android app and using WooCommerce REST api for getting products from the WP site. I have multiple issues that I am looking answers for.
1. How can I get products from a category in random order.
2. How can I get products from multiple categories using a single query.

Thanks,
Ahsan

**Comment by claudiosmweb** [comment]
Please read our documentation: http://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-products

![screenshot from 2016-03-12 05-36-21](https://cloud.githubusercontent.com/assets/1264099/13721954/5db6eee6-e814-11e5-8625-533937debbd4.png)

About sort results:

http://woothemes.github.io/woocommerce-rest-api-docs/#parameters

![screenshot from 2016-03-12 05-37-40](https://cloud.githubusercontent.com/assets/1264099/13721960/8e1d0048-e814-11e5-9a49-6e9b26da672b.png)
