### ISSUE TITLE
Update does not complete

### ISSUE THREAD

**Issue by vveeger** [woothemes/woocommerce#10538]
## EXPLANATION OF THE ISSUE

Trying to update Woocommerce 2.5.4 to 2.5.5 within latest Wordpress but the process does not complete
After waiting for some 30 minutes I closed the screen.
After Re-login the update towards 2.5.5 seems completed.
The same problem was visible from 2.5.3 to 2.5.4
 
## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: https://www.kralenenmineralen.nl
Site URL: https://www.kralenenmineralen.nl
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.16
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.47
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (14) ###

AddToAny Share Buttons: door AddToAny – 1.6.14
Alles-in-één SEO Pakket: door Michael Torbert – 2.3.2.3
BackUpWordPress: door Human Made Limited – 3.5
CodeStyling Localization: door Heiko Rabe – 1.99.30
Gallery by BestWebSoft: door BestWebSoft – 4.3.8
Horizontal scrolling announcement: door Gopi Ramasamy – 8.3
Mollie Payments for WooCommerce: door Mollie – 2.1.1
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Simple Contact Info: door LehaMotovilov – 1.1.9
W3 Total Cache: door Frederick Townes – 0.9.4.1
Widget Logic: door Alan Trewartha – 0.57
WooCommerce: door WooThemes – 2.5.5
WOW Slider: door WOWSlider.com – 8.6
YITH WooCommerce Zoom Magnifier: door Yithemes – 1.2.17

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Winkelbasis: #611 - /winkel/
Winkelmand: #612 - /winkel/winkelmand/
Afrekenen: #613 - /winkel/afrekenen/
Mijn account: #614 - /winkel/mijn-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twentyeleven Child
Version: – 0 is beschikbaar
Author URL: 
Child Theme: ✔
Parent Theme Name: Twenty Eleven
Parent Theme Version: 2.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: child_theme/woocommerce/single-product/title.php
`

**Comment by claudiosmweb** [comment]
>  After waiting for some 30 minutes I closed the screen.

That's a problem, you should not have closed.

**Comment by vveeger** [comment]
ok, what would be an acceptable waiting time before concluding something is wrong?

**Comment by mikejolley** [comment]
What about other plugins? Check error logs - might be more info in there.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/5e88adc02a1142e70a75b4ef6e36b6fbfb750802
