### ISSUE TITLE
Keep shop page when uninstalling WooCommerce

### ISSUE THREAD

**Issue by klihelp** [woothemes/woocommerce#10548]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.
Uninstalling WooCommerce automatically trashing the connected shop page.
In my cases the shop page was holding the shop page description, which is still accurate and usable without WooCommerce, so I wouldn't take this page down when uninstalling WooCommerce.

In the settings the plugin promises:
> This sets the base page of your shop - this is where your product archive will be

After uninstalling WooCommerce should promise that
> The page status remain as it is, but no longer will be the base of the shop for product archive

I think WooCommerce should not delete the page i
1. If it was there before. 
2. and because the page description still can be displayed on the website
3. together with it's custom fields 
3. and not trigger an unexpected page trash actions for plugins to use

```
				array(
					'title'    => __( 'Shop Page', 'woocommerce' ),
					'desc'     => '<br/>' . sprintf( __( 'The base page can also be used in your <a href="%s">product permalinks</a>.', 'woocommerce' ), admin_url( 'options-permalink.php' ) ),
					'id'       => 'woocommerce_shop_page_id',
					'type'     => 'single_select_page',
					'default'  => '',
					'class'    => 'wc-enhanced-select-nostd',
					'css'      => 'min-width:300px;',
					'desc_tip' => __( 'This sets the base page of your shop - this is where your product archive will be.', 'woocommerce' ),
				),

```

```
// In uninstall.php the plugin do:
wp_trash_post( get_option( 'woocommerce_shop_page_id' ) );
```

## STEPS TO REPRODUCE THE ISSUE
- Create Shop page, add content text for describing your shop.
- Attach this page as WooCommerce Shop front page.
- Uninstall WooCommerce.
- Website link not even showing the page with the concent, becasue Shop page trashed.

**Comment by mikejolley** [comment]
in 99% of cases, this page is **created** by WooCommerce, so it makes sense to cleanup when WooCommerce is removed. Same as cart, checkout etc. This same argument could be used there.

The page is trashed - not permanently deleted, so your content is not truly lost/deleted instantly. It can be restored.

More importantly, this data is **only removed if you tell woocommerce to remove data in WC > System Status > Tools.** If you don't check that box, the page is left alone.

So with 2 safeguards in place, this is a non issue.

**Comment by klihelp** [comment]
Thanks for your calculations:) Looks like I am in the 1%.
Some % should go to those where the Frontpage is associated with the Shop page.
> in 99% of cases, this page is created by WooCommerce, so it makes sense to cleanup when WooCommerce is removed

Some thought about your %es:
WooCommerce website today, 14 March 2016, show this information:
> With 13,417,300 downloads WooCommerce powers over 30% of all online stores.

1% of 13,417,300 = 134173 website/admins and their visitors could be affected with non-intentianal page remove, which can be a woorprise (woo-surprise) for them.

**Comment by mikejolley** [comment]
That option is called 'REMOVE ALL DATA'. That should be clear/not a surprize :)
