### ISSUE TITLE
Save PayPal transaction fee on PDT payments

### ISSUE THREAD

**Issue by Babelfisch** [woothemes/woocommerce#10546]
With commit 7c074c7 you added the code to save transaction fee for IPN payments. But most payments are proceed as PDT (Payment Data Transfer) and than the transaction fee is not stored in meta data. Could you please add this to store all PayPal payments fees in the meta data?

**Comment by mikejolley** [comment]
Already handled, if passed back https://github.com/woothemes/woocommerce/search?utf8=%E2%9C%93&q=mc_fee

**Comment by Babelfisch** [comment]
But is doesn't work. All PDT payments have no transaction meta data.

**Comment by mikejolley** [comment]
@Babelfisch pretty sure there is an option in PayPal somewhere to choose what data is sent back with PDT. If its not sent, it cannot be stored. The code is in place our side.

**Comment by Babelfisch** [comment]
No, there is a incorrect handling of data in the `WC_Gateway_Paypal_PDT_Handler` class. You look for `mc_fee` in the `check_response` method and the `$_REQUEST` array. But `$_REQUEST` could not have this data, because it's only the first initial request by Paypal prior the transaction. The real transaction data are in the `$response` array returned by `wp_safe_remote_post`. But in this method you check only if the first line of the BODY is SUCCESS and not the following key value data block.

You get the `mc_fee` with this code:

```php
protected function validate_transaction( $transaction ) {
…
  if ( is_wp_error( $response ) || ! strpos( $response['body'], "SUCCESS" ) === 0 ) {
    return false;
  }

  // now check $response['body'] for more data
  if (preg_match('/^mc_fee=(.+)$/m', $response['body'], $matches))
  {
    // $matches[1] contains the mc_fee value
    // you have to pass $order_id on validate_transaction to save the mc_fee
  }
…
}
```

There is another problem in `check_response` method: You call first `$this->validate_transaction` and thereafter if `$status` is 'completed'. This is the wrong order: if $status is not completed, you must not call the validation request.

**Comment by mikejolley** [comment]
Validation returns "success", not additional order data. At least it did last time I checked :) The mc_fee etc should be POSTed to your page from PayPal as you return to the site, this is also specified in the documentation PayPal provide. 

I'll have to get a new testing environment up and running to check this which will take some time, so if appreciate if you checked this for certain before I do this... Var_dump the result of validation and $_request and share it here to back this up.

**Comment by Babelfisch** [comment]
Take a look of this schema: [Payment Data Transfer](https://developer.paypal.com/docs/classic/products/payment-data-transfer/)

The request in `check_response()` is step 2 and it send only the [PDT-specific variables](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/#id092BE0U605Z). The real transaction data comes in step 4 as return of your request in `validate_transaction()` with the `wp_safe_remote_post` call. The Paypal doc says:

> 4 PayPal replies with a message indicating SUCCESS or FAIL. The SUCCESS message includes transaction details, one per line, in the <Key>=<Value> format. This key-value pair string is URL encoded.

I have checked it with var_dump. $_REQUEST in `check_response` contains only:

```
array (
  'key' => 'wc_order_…',
  'utm_nooverride' => '1',
  'tx' => '…',
  'st' => 'Completed',
  'amt' => '10.00',
  'cc' => 'EUR',
  'cm' => '{\\"order_id\\":1234,\\"order_key\\":\\"wc_order_…\\"}',
  'item_number' => '',
)
```

The `$response` data of `wp_safe_remote_post` contains all necessary data known from IPN requests as key value pairs:

```
array (
  'headers' => 
  array (
    'server' => 'Apache',
    'x-frame-options' => 'SAMEORIGIN',
  …
  ),
  'body' => 'SUCCESS
mc_gross=10.00
invoice=1234
protection_eligibility=Ineligible
item_number1=1235
tax=0.00
item_number2=
payer_id=…
ebay_txn_id1=
ebay_txn_id2=
payment_date=15%3A31%3A13+Mar+14%2C+2016+PDT
payment_status=Completed
charset=windows-1252
mc_shipping=0.00
mc_handling=0.00
first_name=…
mc_fee=0.54
…
)
```
