### ISSUE TITLE
INCORRECT TAX CALCULATION

### ISSUE THREAD

**Issue by audioswiss** [woothemes/woocommerce#10545]
## EXPLANATION OF THE ISSUE

On standard rate in TAX I have entered 8% but on the shop it calculates 7.4%. Can somebody please help with this?
 

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://clientes.uvxz.com.br/audioleman
Site URL: http://clientes.uvxz.com.br/audioleman
WC Version: 2.5.3
Log Directory Writable: ✔  /home/storage/4/33/62/uvxz/public_html/clientes/audioleman/wp-content/uploads/wc-logs/
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.31
PHP Post Max Size: 50 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.6.21
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (10) ###

Polylang: by Frédéric Demarle – 1.8.4
Black Studio TinyMCE Widget: by Black Studio – 2.2.8
Contact Form 7: by Takayuki Miyoshi – 4.4
Kwayy HTML Sitemap: by Kwayy Infotech – 3.1
Lingotek Translation: by Lingotek and Frédéric Demarle – 1.1.11
Post Duplicator: by Metaphor Creations – 2.14
NextScripts: Social Networks Auto-Poster: by Next Scripts – 3.5.0
WooCommerce Subcategories widget: by Pavel Burov (Dark Delphin) – 1.4.1
WooCommerce: by WooThemes – 2.5.3
Yoast SEO: by Team Yoast – 3.1

### Settings ###

Force SSL: –
Currency: CHF (CHF)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #42 - /en/shop/
Cart: #43 - /en/cart/
Checkout: #44 - /en/checkout/
My Account: #45 - /en/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Audioleman
Version: 1.0
Author URL: http://uvxz.com.br/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: audioleman/woocommerce/archive-product.php
audioleman/woocommerce/auth/footer.php
audioleman/woocommerce/auth/form-grant-access.php
audioleman/woocommerce/auth/form-login.php
audioleman/woocommerce/auth/header.php
audioleman/woocommerce/cart/cart-empty.php
audioleman/woocommerce/cart/cart-item-data.php
audioleman/woocommerce/cart/cart-shipping.php
audioleman/woocommerce/cart/cart-totals.php
audioleman/woocommerce/cart/cart.php
audioleman/woocommerce/cart/cross-sells.php
audioleman/woocommerce/cart/mini-cart.php
audioleman/woocommerce/cart/proceed-to-checkout-button.php
audioleman/woocommerce/cart/shipping-calculator.php
audioleman/woocommerce/checkout/cart-errors.php
audioleman/woocommerce/checkout/form-billing.php
audioleman/woocommerce/checkout/form-checkout.php
audioleman/woocommerce/checkout/form-coupon.php
audioleman/woocommerce/checkout/form-login.php
audioleman/woocommerce/checkout/form-pay.php
audioleman/woocommerce/checkout/form-shipping.php
audioleman/woocommerce/checkout/payment-method.php
audioleman/woocommerce/checkout/payment.php
audioleman/woocommerce/checkout/review-order.php
audioleman/woocommerce/checkout/terms.php
audioleman/woocommerce/checkout/thankyou.php
audioleman/woocommerce/content-product.php
audioleman/woocommerce/content-product_cat.php
audioleman/woocommerce/content-single-product.php
audioleman/woocommerce/content-widget-product.php
audioleman/woocommerce/emails/admin-cancelled-order.php
audioleman/woocommerce/emails/admin-failed-order.php
audioleman/woocommerce/emails/admin-new-order.php
audioleman/woocommerce/emails/customer-completed-order.php
audioleman/woocommerce/emails/customer-invoice.php
audioleman/woocommerce/emails/customer-new-account.php
audioleman/woocommerce/emails/customer-note.php
audioleman/woocommerce/emails/customer-processing-order.php
audioleman/woocommerce/emails/customer-refunded-order.php
audioleman/woocommerce/emails/customer-reset-password.php
audioleman/woocommerce/emails/email-addresses.php
audioleman/woocommerce/emails/email-customer-details.php
audioleman/woocommerce/emails/email-footer.php
audioleman/woocommerce/emails/email-header.php
audioleman/woocommerce/emails/email-order-details.php
audioleman/woocommerce/emails/email-order-items.php
audioleman/woocommerce/emails/email-styles.php
audioleman/woocommerce/emails/plain/admin-cancelled-order.php
audioleman/woocommerce/emails/plain/admin-failed-order.php
audioleman/woocommerce/emails/plain/admin-new-order.php
audioleman/woocommerce/emails/plain/customer-completed-order.php
audioleman/woocommerce/emails/plain/customer-invoice.php
audioleman/woocommerce/emails/plain/customer-new-account.php
audioleman/woocommerce/emails/plain/customer-note.php
audioleman/woocommerce/emails/plain/customer-processing-order.php
audioleman/woocommerce/emails/plain/customer-refunded-order.php
audioleman/woocommerce/emails/plain/customer-reset-password.php
audioleman/woocommerce/emails/plain/email-addresses.php
audioleman/woocommerce/emails/plain/email-customer-details.php
audioleman/woocommerce/emails/plain/email-order-details.php
audioleman/woocommerce/emails/plain/email-order-items.php
audioleman/woocommerce/global/breadcrumb.php
audioleman/woocommerce/global/form-login.php
audioleman/woocommerce/global/quantity-input.php
audioleman/woocommerce/global/sidebar.php
audioleman/woocommerce/global/wrapper-end.php
audioleman/woocommerce/global/wrapper-start.php
audioleman/woocommerce/loop/add-to-cart.php
audioleman/woocommerce/loop/loop-end.php
audioleman/woocommerce/loop/loop-start.php
audioleman/woocommerce/loop/no-products-found.php
audioleman/woocommerce/loop/orderby.php
audioleman/woocommerce/loop/pagination.php
audioleman/woocommerce/loop/price.php
audioleman/woocommerce/loop/rating.php
audioleman/woocommerce/loop/result-count.php
audioleman/woocommerce/loop/sale-flash.php
audioleman/woocommerce/myaccount/form-add-payment-method.php
audioleman/woocommerce/myaccount/form-edit-account.php
audioleman/woocommerce/myaccount/form-edit-address.php
audioleman/woocommerce/myaccount/form-login.php
audioleman/woocommerce/myaccount/form-lost-password.php
audioleman/woocommerce/myaccount/my-account.php
audioleman/woocommerce/myaccount/my-address.php
audioleman/woocommerce/myaccount/my-downloads.php
audioleman/woocommerce/myaccount/my-orders.php
audioleman/woocommerce/myaccount/view-order.php
audioleman/woocommerce/notices/error.php
audioleman/woocommerce/notices/notice.php
audioleman/woocommerce/notices/success.php
audioleman/woocommerce/order/form-tracking.php
audioleman/woocommerce/order/order-again.php
audioleman/woocommerce/order/order-details-customer.php
audioleman/woocommerce/order/order-details-item.php
audioleman/woocommerce/order/order-details.php version 2.5.0 is out of date. The core version is 2.5.3
audioleman/woocommerce/order/tracking.php
audioleman/woocommerce/product-searchform.php
audioleman/woocommerce/single-product/add-to-cart/external.php
audioleman/woocommerce/single-product/add-to-cart/grouped.php
audioleman/woocommerce/single-product/add-to-cart/simple.php
audioleman/woocommerce/single-product/add-to-cart/variable.php
audioleman/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
audioleman/woocommerce/single-product/add-to-cart/variation.php
audioleman/woocommerce/single-product/meta.php
audioleman/woocommerce/single-product/price.php
audioleman/woocommerce/single-product/product-attributes.php
audioleman/woocommerce/single-product/product-image.php
audioleman/woocommerce/single-product/product-thumbnails.php
audioleman/woocommerce/single-product/rating.php
audioleman/woocommerce/single-product/related.php
audioleman/woocommerce/single-product/review.php
audioleman/woocommerce/single-product/sale-flash.php
audioleman/woocommerce/single-product/share.php
audioleman/woocommerce/single-product/short-description.php
audioleman/woocommerce/single-product/tabs/additional-information.php
audioleman/woocommerce/single-product/tabs/description.php
audioleman/woocommerce/single-product/tabs/tabs.php
audioleman/woocommerce/single-product/title.php
audioleman/woocommerce/single-product/up-sells.php
audioleman/woocommerce/single-product-reviews.php
audioleman/woocommerce/single-product.php
audioleman/woocommerce/taxonomy-product_cat.php
audioleman/woocommerce/taxonomy-product_tag.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
Please read https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce to understand the calculations involved.
