### ISSUE TITLE
Version 2.5.5 took site down

### ISSUE THREAD

**Issue by serveds** [woothemes/woocommerce#10544]
Hi,

Got a message from my host informing me of my site going down and had to revert back to 2.5.4. They also mention they had a similar issue with another site.

Message from host:

"The site should be back up & working, but just wanted to give a heads up we got alerted to the site being down.

Looking at the queries being made, we were seeing:

Query |1 | altering table                  | ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key(191))
Query |2 | Waiting for table metadata lock | ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key(191))
Query |2 | Waiting for table metadata lock | ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key(191))
Query |2 | Waiting for table metadata lock | ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key(191))
Query |2 | Waiting for table metadata lock | ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key(191))
Query |0 | init                 | ALTER TABLE wp_woocommerce_tax_rate_locations DROP INDEX `location_type_code`
Query |0 | setup                | ALTER TABLE wp_woocommerce_tax_rate_locations DROP INDEX `location_type_code`

We had another case of a site being down due to the update, so a force downgrade to version Woocomerce 2.5.4 was done."

`
### WordPress Environment ###

WC Version: 2.5.4
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.7.10
PHP Version: 5.6.99-hhvm
PHP Post Max Size: 
PHP Time Limit: 0
PHP Max Input Vars: 
SUHOSIN Installed: –
MySQL Version: 5.6.10
Max Upload Size: 
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (42) ###

Gravity Forms: by rocketgenius – 1.9.17.5
Advanced Custom Fields: by Elliot Condon – 4.4.5
adwords thankyoupage: by Justin – 1.0
Akismet: by Automattic – 3.1.8
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 1.7.5
BCF Custom: by BCF – 1.0
Better WordPress Google XML Sitemaps: by Khang Minh – 1.4.1
Embed PDF: by Pat Hawks – 1.0.6
ElasticPress: by Aaron Holbrook
Taylor Lovett
Matt Gross
10up – 2.6.2

Kraken Image Optimizer: by Karim Salman – 2.5.1
OptinMonster API: by Thomas Griffin – 1.1.4.4
WooCommerce Product Filter: by Mihajlovic Nenad – 5.3.6
Simple 301 Redirects - Addon - Bulk CSV Uploader: by Ash Durham – 1.0.12
Simple 301 Redirects: by Scott Nellé – 1.07
TinyMCE Advanced: by Andrew Ozz – 4.2.8
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.1.1

WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce AWeber Newsletter Subscription: by Gerhard Potgieter – 1.0.10
WooCommerce Chained Products: by Store Apps – 2.3.8
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.4.0
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Dynamic Pricing: by Lucas Stark – 2.10.11
WooCommerce Moneris Gateway: by WooThemes / SkyVerge – 2.4.0
WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.6.1
WooCommerce Gateways Country Limiter: by OnTheGoSystems – 1.0.3
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce AdWords Dynamic Remarketing: by Wolf + Bär GmbH – 1.1.2
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.5
WooCommerce Minimum Advertised Price: by WooThemes / SkyVerge – 1.6.0
WooCommerce Order Status Manager: by WooThemes / SkyVerge – 1.4.1
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.8
WooCommerce Quick Export Plugin: by MB Création – 2.2
WooCommerce Local Pickup Plus: by WooThemes / SkyVerge – 1.12.0
WooCommerce Smart Coupons: by WooThemes – 3.0.11
WooCommerce Smart Sale Badge: by Hugh Lashbrooke – 1.1
WooCommerce Table Rate Shipping: by Mike Jolley – 2.9.2
WooCommerce: by WooThemes – 5.5.5
Yoast SEO: by Team Yoast – 3.1.1
WP Google Maps: by WP Google Maps – 6.3.05
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
WP Security Audit Log: by WP White Security – 2.3.3
Zopim Widget: by Zopim – 1.4.2

### Settings ###

Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4336 - /shop/
Cart: #4337 - /cart/
Checkout: #4338 - /checkout/
My Account: #4339 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: mytheme
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Canvas
Parent Theme Version: 5.9.16 – 5.9.19 is available
Parent Theme Author URL: http://www.woothemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mytheme/woocommerce/archive-product.php
mytheme/woocommerce/cart/cart-totals.php
mytheme/woocommerce/cart/cart.php
mytheme/woocommerce/checkout/review-order.php
mytheme/woocommerce/checkout/thankyou.php
mytheme/woocommerce/emails/customer-completed-order.php
mytheme/woocommerce/emails/customer-processing-order.php
mytheme/woocommerce/loop/add-to-cart.php version - is out of date. The core version is 2.5.0

: Learn how to update outdated templates
`

Regards,
Justin

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/5e88adc02a1142e70a75b4ef6e36b6fbfb750802
