### ISSUE TITLE
refund hangs/crashes on deleted products

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#10556]
When trying to create a refund for items from products that were deleted, WooCommerce hangs (and does not succeed in adding these items to the refund). Upon further investigation, it appears that this happens because the refund is created by re-adding the items via `$refund->add_product()`, which requires a $product object and therefor gets a fatal error when trying $product->get_title() (several other $product methods are called later too).

**Comment by Spreeuw** [comment]
Fixes this error, but then returns 'invalid refund amount'.

**Comment by mikejolley** [comment]
Don't think so - that comes way before refund creation which was patched.

**Comment by Spreeuw** [comment]
Apologies, you're right. I can't reproduce now either when I try again (on the same order). Thanks for fixing so quickly!

**Comment by Spreeuw** [comment]
This only adds the total refunded though and doesn't take the tax amounts into the refund order (all 0). Maybe use `wc_add_order_item()` instead? All the data required for the line item are already available from the original order.

**Comment by mikejolley** [comment]
Will try that in https://github.com/woothemes/woocommerce/pull/10259 since this replaces a lot of this logic with new classes.
