### ISSUE TITLE
Variable Stock Quantity is not updating after sale. Manage stock options set.

### ISSUE THREAD

**Issue by YaberaClothing** [woothemes/woocommerce#10554]
## EXPLANATION OF THE ISSUE

I have been searching, researching, and testing for MONTHS. Nothing I do works, I have followed all guidelines in regard to this. Please Help. 

I sell mens button up shirts, I carry different sizes which we will refer to as VARIATIONS to the PRODUCT. 

Under PRODUCT DATA - Variable Product 
Inventory Tab - Manage stock at product level UNCHECKED
My ATTRIBUTES and VARIABLES are setup with SIZE options (M, L, XL, XXL, etc.)
Variable tab ENABLED CHECKED and MANAGE STOCK CHECKED and STOCK QTY number entered (ie: 2 mediums)

When that MEDIUM sells, it does not remove the MEDIUM from stock. So, when I have a VARIABLE with 2 in stock, the shop will allow more than 2 to sell. IT DOES NOT UPDATE STOCK QTY WHEN THAT VARIABLE SELLS. 

WooCommerce 2.4.4
IDSTORE Version 4.0
WordPress 4.1.4

![untitled-1](https://cloud.githubusercontent.com/assets/17828739/13746368/8056a48a-e9c9-11e5-91ca-b30babe03a3f.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/17828739/13746370/8064b75a-e9c9-11e5-80b9-a10f5016b192.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/17828739/13746434/d5aeb864-e9c9-11e5-8324-130012b0a781.jpg)

![untitled-4](https://cloud.githubusercontent.com/assets/17828739/13746367/8054c476-e9c9-11e5-91c6-66df295c8fd6.jpg)

WOOCOMMERCE SYSTEM STATUS
WordPress Environment
Home URL:	[?]	http://yaberaclothing.com
Site URL:	[?]	http://yaberaclothing.com
WC Version:	[?]	2.4.4
Log Directory Writable:	[?]	✔ /home/whiter35gtrz/public_html/yaberaclothing.com/wp-content/uploads/wc-logs/
WP Version:	[?]	4.1.4
WP Multisite:	[?]	–
WP Memory Limit:	[?]	40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode:	[?]	–
Language:	[?]	en_US
Server Environment
Server Info:	[?]	Apache/2.4.12
PHP Version:	[?]	5.4.43
PHP Post Max Size:	[?]	256 MB
PHP Time Limit:	[?]	180
PHP Max Input Vars:	[?]	10000
SUHOSIN Installed:	[?]	–
MySQL Version:	[?]	5.5.45
Max Upload Size:	[?]	256 MB
Default Timezone is UTC:	[?]	✔
fsockopen/cURL:	[?]	✔
SoapClient:	[?]	✔
DOMDocument:	[?]	✔
GZip:	[?]	✔
Remote Post:	[?]	✔
Remote Get:	[?]	✔
Database
WC Database Version:	[?]	2.4.4
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (22)
LayerSlider WP	 	by Kreatura Media – 4.6.3
Autoptimize	 	by Frank Goossens (futtta) – 1.9.4
Contact Form by BestWebSoft	 	by BestWebSoft – 3.96
Google Tag Manager for Wordpress	 	by Thomas Geiger – 1.1.1
WooCommerce shop to Facebook	 	by StoreYa – 2.4
Leverage Browser Caching Ninja	 	by CustomWPNinjas – 2.1
Limit Login Attempts	 	by Johan Eenfeldt – 1.7.1
MailPoet WooCommerce Add-on	 	by Sebs Studio – 2.0.2
Meta Slider	 	by Matcha Labs – 3.3.4.1
MNKY Vector Icons Plugin	 	by MNKY Studio – 1.2
Mobile Assistant Connector	 	by eMagicOne – 1.0.7
NextGEN Gallery by Photocrati	 	by Photocrati Media – 2.1.7
Remove query strings from static resources	 	by Your WP Expert – 1.3
Revolution Slider	 	by ThemePunch – 4.3.6
Schema Creator by Raven	 	by Raven Internet Marketing Tools – 1.1.1
UpdraftPlus - Backup/Restore	 	by UpdraftPlus.Com, DavidAnderson – 1.11.28
WooCommerce Product Details Customiser	 	by jameskoster – 0.2.0
WOOF - WooCommerce Products Filter	 	by realmag777 – 1.1.2
WooCommerce	 	by WooThemes – 2.4.4
Yoast SEO	 	by Team Yoast – 2.3.4
WP Fastest Cache	 	by Emre Vona – 0.8.5.5
WP Google Fonts	 	by Noah Kagan – v3.1.3
Settings
Force SSL:	[?]	–
Currency	[?]	USD ($)
Currency Position	[?]	left
Thousand Separator	[?]	,
Decimal Separator	[?]	.
Number of Decimals	[?]	2
API
API Enabled:	[?]	✔
API Version:	[?]	3.0.0
WC Pages
Shop Base:	[?]	#48 - /shop/
Cart:	[?]	#77 - /cart/
Checkout:	[?]	#78 - /checkout/
My Account:	[?]	#79 - /my-account/
Taxonomies [?]
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:	[?]	IDStore - Responsive WordPress Theme
Version:	[?]	4.0
Author URL:	[?]	http://themeforest.net/user/8theme
Child Theme:	[?]	✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support:	[?]	✔
Templates [?]
Overrides (WooCommerce):	 	idstore/woocommerce/archive-product.php, 
idstore/woocommerce/cart/cart-empty.php, 
idstore/woocommerce/cart/cart.php, 
idstore/woocommerce/cart/cross-sells.php, 
idstore/woocommerce/checkout/form-billing.php, 
idstore/woocommerce/checkout/form-checkout.php, 
idstore/woocommerce/checkout/form-login.php, 
idstore/woocommerce/checkout/form-pay.php, 
idstore/woocommerce/checkout/review-order.php, 
idstore/woocommerce/content-product.php, 
idstore/woocommerce/content-product_cat.php, 
idstore/woocommerce/content-single-product.php, 
idstore/woocommerce/content-widget-product.php, 
idstore/woocommerce/global/quantity-input.php, 
idstore/woocommerce/global/wrapper-end.php, 
idstore/woocommerce/global/wrapper-start.php, 
idstore/woocommerce/loop/add-to-cart.php, 
idstore/woocommerce/loop/pagination.php, 
idstore/woocommerce/loop/result-count.php, 
idstore/woocommerce/loop/sale-flash.php, 
idstore/woocommerce/myaccount/form-edit-address.php, 
idstore/woocommerce/myaccount/form-login.php, 
idstore/woocommerce/myaccount/my-account.php, 
idstore/woocommerce/myaccount/my-address.php, 
idstore/woocommerce/myaccount/my-orders.php, 
idstore/woocommerce/order/form-tracking.php, 
idstore/woocommerce/order/tracking.php, 
idstore/woocommerce/single-product/add-to-cart/external.php, 
idstore/woocommerce/single-product/add-to-cart/simple.php, 
idstore/woocommerce/single-product/meta.php, 
idstore/woocommerce/single-product/price.php, 
idstore/woocommerce/single-product/product-image.php, 
idstore/woocommerce/single-product/product-thumbnails.php, 
idstore/woocommerce/single-product/related.php, 
idstore/woocommerce/single-product/sale-flash.php, 
idstore/woocommerce/single-product/short-description.php, 
idstore/woocommerce/single-product/tabs/additional-information.php, 
idstore/woocommerce/single-product/tabs/description.php, 
idstore/woocommerce/single-product/tabs/tabs.php, 
idstore/woocommerce/single-product/title.php, 
idstore/woocommerce/single-product/up-sells.php, 
idstore/woocommerce/single-product-reviews.php, 
idstore/woocommerce/single-product.php

**Comment by mikejolley** [comment]
>  I have followed all guidelines in regard to this

If you're read the issue submission form you'd see that _this is not a support area_. You'd also know we only support/look into bugs with latest versions, and you are not on latest WC or WP.

Since there are no other reports, this would have to be something specific to your install. Support forum for future reference is here: https://wordpress.org/support/plugin/woocommerce

I'd at least need to see a screenshot of all the variations present to see what combinations are available.

You also need to look at some orders that have come in, see what status they have, and see what order notes were logged (stock reductions are logged). **The order notes will tell you if stock was reduced or not**.

You also said stock management was disabled at product level, but that is not true. The checkbox is checked so you have both variation and product level stock management enabled at present.

Check the above first. You can comment back here if you like, but I will be closing this as its not a real bug report.

**Comment by YaberaClothing** [comment]
Thank you for the reply Mike Jolley, sorry for the wrong forum post.
