### ISSUE TITLE
Refill of Stock.

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10559]
Some times products are out of stock.
This require users to enter the site daily to check if stock was refilled.

It would be nice if users will be notify once product is back to stock.
For example:
if product marked with stock 0, let users (and guests) leave their email. and when stock is back again the system will send them notification about it.

This feature exists in many store sites.

**Comment by mikejolley** [comment]
https://www.woothemes.com/products/woocommerce-waitlist/
