### ISSUE TITLE
Documentation for product properties incomplete

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10569]
In the file class-wc-api-products.php there's this code at line 330
```php
// Product name (slug).
if ( isset( $data['name'] ) ) {
	wp_update_post( array( 'ID' => $id, 'post_name' => sanitize_title( $data['name'] ) ) );
}
```

It's nowhere in the official documentation that 'name' is a property for a product and that it can be used to set the post_name, that's responsible for the product's url.

IMHO it's definitely worth mentioning in the docs, since modifying the post_name is an urgent feature, and I accidentally found it in the code.

**Comment by claudiosmweb** [comment]
For issues with the API docs, use: https://github.com/woothemes/woocommerce-rest-api-docs
