### ISSUE TITLE
"product" fold mistype, google webmaster show 404 err.

### ISSUE THREAD

**Issue by EuYoga** [woothemes/woocommerce#10566]
There is a weird mistyping in my woocommerce tag and category, that I have no way to fix it.

![image](https://cloud.githubusercontent.com/assets/17629904/13798957/20485bd6-eb56-11e5-913b-2a43661ce348.png)

All "product" are mistyped into "prodcut", is it the reason google webmaster show me some 404 err?

![image](https://cloud.githubusercontent.com/assets/17629904/13799007/8f11cfb6-eb56-11e5-9ac9-25d9c8634a45.png)

How can I fix it?

**Comment by mikejolley** [comment]
Yes. Fix you translation file, or set the correct string in Settings > Permalinks, then save permalinks. That should correct it.

**Comment by EuYoga** [comment]
TKS!
