### ISSUE TITLE
Price dont update when we use variation in Woocommerce and garvity form add-on

### ISSUE THREAD

**Issue by shubhamkhandel** [woothemes/woocommerce#10567]
Hello there can anybody help me solve  issue with  Woocommerce and garvity form add-on what is happening here is when i use variation so price should be update.but it's not happening and  on other hand in Preview option its working correctly.please solve  this issue.
Thank you

**Comment by mikejolley** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support

Please use support.woothemes.com for gravity form addons issues.
