### ISSUE TITLE
Hidden Products in Related Products Issue

### ISSUE THREAD

**Issue by AllDayRuckoff** [woothemes/woocommerce#10568]
## EXPLANATION OF THE ISSUE

Under the current version of WooCommerce and WordPress the related products pulls products that are in the draft and private stage as well as products that have a catalog visibility of hidden. WooCommerce does not display these products and instead displays less than the ideal number of related products. If the number of related products is set to 4 and there are hidden/draft/private products in a WooCommerce store then the individual product pages will show 0 - 4 related products. If there are no hidden/draft/private products then WooCommerce will always show 4.

## STEPS TO REPRODUCE THE ISSUE

1. Add 5 products to a WooCommerce store.
2. Mark 2 of the 5 products as hidden.
3. Set number of related products to 2
4. Refresh on a non-hidden product and check the number of related products.
5. Output varies between 0 and 2 when it should always be 2 as there are two non-hidden products that can be shown.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://alldayruckoff.com
Site URL: https://alldayruckoff.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 9000
SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (45) ###

Redux Framework: by Team Redux – 3.5.9
AffiliateWP: by Pippin Williamson and Andrew Munro – 1.7.16
AfterShip - WooCommerce Tracking: by AfterShip – 1.4.8
Akismet: by Automattic – 3.1.8
Autoptimize: by Frank Goossens (futtta) – 2.0.1
WooCommerce Back In Stock Notifier: by Fantastic Plugins – 7.9
Category pagination fix: by rahnas – 3.2.2
Google Analytics by Yoast eCommerce tracking addon: by Team Yoast – 3.0.5
Genesis Connect for WooCommerce: by StudioPress – 0.9.8
Genesis Simple Edits: by Nathan Rice – 2.1.4
Genesis Simple Sidebars: by Nathan Rice – 2.0.2
Genesis Widgetized Not Found & 404: by David Decker - DECKERWEB – 1.5.0
Google Analytics by Yoast: by Team Yoast – 5.4.6
WooThumbs - Awesome Product Imagery: by James Kemp – 4.4.11
Jetpack by WordPress.com: by Automattic – 3.9.4
MailChimp for WordPress: by ibericode – 3.1.4
myCRED: by Gabriel S Merovingi – 1.6.9
Ninja Forms: by The WP Ninjas – 2.9.36
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Responsive Lightbox: by dFactory – 1.6.7
Restrict Usernames: by Scott Reilly – 3.5.1
Slider Revolution: by ThemePunch – 5.2.2
Safe Redirect Manager: by Taylor Lovett (10up) – 1.7.8
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.4.0.1

Shortcode Exec PHP: by Marcel Bokhorst – 1.52
Subscribe to Comments Reloaded: by reedyseth
Raam Dev
camu – 160115

UberMenu Conditionals: by Chris Mavricos
SevenSpark – 3.0

UberMenu - Sticky Menu Extension: by Chris Mavricos
SevenSpark – 3.1.1

UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.4

User Role Editor: by Vladimir Garagulya – 4.23.2
Username Changer: by Daniel J Griffiths – 2.0.5
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.0.18
Woocomerce Brands Pro: by Proword – 3.7
Woo Stickers by Webline: by Weblineindia – 1.0.4
Woocommerce Advanced Bulk Edit: by George Iron – 3.7
WooCommerce Advanced Notifications: by WooThemes – 1.1.19
WooCommerce Email Validation: by Hugh Lashbrooke – 1.2.8
Follow-Up Emails: by 75nineteen Media LLC – 4.4.11
WooCommerce Table Rate Shipping: by Bolder Elements – 3.6.5
WooCommerce: by WooThemes – 2.5.5
WooThemes Helper: by WooThemes – 1.6.0
Yoast SEO: by Team Yoast – 3.1.1
WP Review: by MyThemesShop – 4.0.6
WP Smush: by WPMU DEV – 2.1.5
Yoast WooCommerce SEO: by Team Yoast – 3.1.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #1680 - /store/
Cart: #1681 - /cart/
Checkout: #1682 - /checkout/
My Account: #1683 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: All Day Ruckoff Genesis Theme
Version: 2.0.1
Author URL: https://www.alldayruckoff.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.2.7
Parent Theme Author URL: http://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: genesis-sample/woocommerce/archive-product.php version 0.9.5 is out of date. The core version is 2.0.0
genesis-sample/woocommerce/loop/rating.php
genesis-sample/woocommerce/myaccount/my-account.php
genesis-sample/woocommerce/single-product-reviews.php
genesis-sample/woocommerce/single-product.php version 0.9.5 is out of date. The core version is 1.6.4

: Learn how to update outdated templates
`

**Comment by AllDayRuckoff** [comment]
I believe the fix is as simple as adding the following to the apply_filters in related.php

'post_status'          => 'publish',
'meta_query' => array(array(
		'key' => '_visibility',
		'value' => array( 'visible' ),
		'compare' => 'IN'))

That should restrict related outputs to only published posts that are marked visible.

**Comment by mikejolley** [comment]
![2016-03-17 at 11 38](https://cloud.githubusercontent.com/assets/90977/13844949/d7c9d896-ec34-11e5-948b-76d841c9314a.png)

Based on the code being present, it sounds like you either have a custom related query, or something you're editing products with (bulk editor?) is not clearing the cache/transient called wc_related_ID

**Comment by AllDayRuckoff** [comment]
Hey Mike,

I think I found the issue and it's with the OR when joining tags:
![image](https://cloud.githubusercontent.com/assets/6185954/13850669/2cf91ea2-ec18-11e5-971b-85a1878f3406.png)
I logged the query which you can find below:
SELECT DISTINCT ID FROM wp_posts p
INNER JOIN wp_postmeta pm ON ( pm.post_id = p.ID AND pm.meta_key='_visibility' ) 
INNER JOIN wp_term_relationships tr ON (p.ID = tr.object_id) 
INNER JOIN wp_term_taxonomy tt ON (tr.term_taxonomy_id = tt.term_taxonomy_id) 
INNER JOIN wp_terms t ON (t.term_id = tt.term_id)
WHERE 1=1 AND p.post_status = 'publish' 
AND p.post_type = 'product' 
AND p.ID NOT IN ( 0,9978 ) 
AND pm.meta_value IN ( 'visible', 'catalog' ) 
AND ( tt.taxonomy = 'product_cat' AND t.term_id IN ( 0,109 ) ) 
OR ( ( tt.taxonomy = 'product_tag' AND t.term_id IN ( 0,118,249,306 ) ) AND p.ID NOT IN ( 0,9978 ) )
LIMIT 14

That OR statement above does not specify that the pm_meta_value is visible or catalog. I believe the proper way to do this would be to remove one closing parenthesis on the relate_by_category WHERE statement and add an extra closing parenthesis on the relate_by_category IF $andor = 'OR'.

Running the query above against my database produces a number of hidden products:
![image](https://cloud.githubusercontent.com/assets/6185954/13850830/e1923aec-ec18-11e5-8b23-bf52fb31e532.png)

Modifying the query to put the OR statement within the category criteria produces the following:
![image](https://cloud.githubusercontent.com/assets/6185954/13850880/2053a7e8-ec19-11e5-8fce-2d5efc48e171.png)

**Comment by mikejolley** [comment]
Try the above commit.

**Comment by AllDayRuckoff** [comment]
Hey @mikejolley 

I checked it and there's the potential for a double AND (AND AND) within the SQL if $andor === 'AND'. I made a modification to my file and made this commit with it: https://github.com/woothemes/woocommerce/commit/6885b0c2aa21f562246fd07e7145c295b95e8577

**Comment by mikejolley** [comment]
I don't follow you @AllDayRuckoff  - the outer AND () does not affect the inner AND/OR

**Comment by AllDayRuckoff** [comment]
@mikejolley Related to your commit if we're running through where $relate_by_category is false and $relate_by_tag is true I believe the following will happen.

Line 1623 will add 'AND ('
Line 1625 will be false so we'll set $andor = 'AND'
Line 1632 will be true so we'll append  {$andor} ( tt.taxonomy = 'product_tag' AND t.term_id IN ( " . implode( ',', $tags_array ) . " ) ) ";

On line 1632 appending that $andor will result in the where query looking like: AND ( AND ( tt.taxonomy = 'product_tag' AND t.term_id IN ( " . implode( ',', $tags_array ) . " ) )' which will fail.

**Comment by AllDayRuckoff** [comment]
Newest commit 10568 looks good. Copied it over, ran the SQL, should be perfect. Thanks for not giving up on this @mikejolley!

**Comment by leecollings-sb** [comment]
Hello guys, as this is now from a few years ago and is also closed, the issue is still present and has been raised as an another issue which has also been closed but without good reason from what I can see.

I'd just like to kindly ask why these have been closed if the issue is still present?

**Comment by AllDayRuckoff** [comment]
@leecollings-sb It was definitely working on March 17th, 2016 so my guess is that it must have been re-introduced at some point. This issue was closed because it was fixed during this commit: https://github.com/woocommerce/woocommerce/commit/c25ef5e55a782d6224e800ef5ffc3eb240dc663b
