### ISSUE TITLE
Adding fee based on the cart total

### ISSUE THREAD

**Issue by hemnathmouli** [woothemes/woocommerce#10571]
I am trying to add fee based on the cart total. But the fee adds on `woocommerce_cart_calculate_fees`. Where the calculation is not calculated yet. But I don't know how to make it based on cart total. When the updated or deleted, the total change, so I am unable to get proper total and add fee. This is my code. 

```
function woo_add_cart_fee() {
    $cart_total = ;
    $fee = (int)$cart_total*5/100;
    WC()->cart->add_fee( 'Credits :', $fee, false, '' );
        }
    }
}
add_action( 'woocommerce_cart_calculate_fees', 'woo_add_cart_fee' );
```
I am unable to find the way. Can anyone help.? Thanks in advance.

**Comment by claudiosmweb** [comment]
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support
