### ISSUE TITLE
Store package/item info in shipping meta

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10574]
Store a list of items/products for each shipped package in the new shipping meta, when using multiple packages.

**Comment by franticpsyx** [comment]
As a generalization, it might be a good idea to store item weights, dimensions and values (from packages) inside an order.

This will make it possible to have shipping package data transferred intact from the cart into an order without "losing" any modifications made to shipping packages or their contents in the cart.

External shipping fulfilment services that now get exported order line items (such as Shipstation) could then use this data to get accurate shipping info. Right now all modifications made to shipping packages in the cart are "lost" when a store relies on shipping via an external fulfilment service.

Using a filter such as `get_product_from_item` to repopulate this data is not always a good idea. Here's a reason:

Some services may support Inventory Management + Shipping Fulfilment at the same time. In these cases we need a separation between exported order data that describes "what's in an order" vs data that describes "what is shipped". For instance, we may need to include a virtual order item in exported data for Inventory Management, but not include it for Shipping Fulfilment.

**Comment by jeffstieler** [comment]
> Store a list of items/products for each shipped package in the new shipping meta, when using multiple packages.

I think this is a great idea - but doesn't WC core currently push the box packing responsibility onto each shipping method?

How do you propose WC core gets the packaging (which items in which boxes) info?

Is there some other place to add shipping meta other than here: https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L220 ?

**Comment by mikejolley** [comment]
There are 2 levels to this. 

1. Packages (where you can split items and ship each package, or group, or items with different methods.
2. What @allendav and @kellychoffman suggested where you group items by a subset of a shipping method

I don't know how 2. would work. @allendav any thoughts how you're going to store this data?

**Comment by mikejolley** [comment]
> Is there some other place to add shipping meta other than here: https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L220 ?

No, and thats new to store meta data specific to the rate being added,

**Comment by mikejolley** [comment]
By passing in $package, core can store shipping item meta like this to have some kind of record:

![2016-03-22 at 15 27](https://cloud.githubusercontent.com/assets/90977/13956989/bc62832a-f042-11e5-83a4-d978843c3de2.png)

This would work for $packages and at least give the user an indication of what was shipped when multiple packages are recorded.

As for the other problem, this data would need to also be meta added by the extension. There a several gotchas which prevent me implementing this in core right now. These include:

- Shipping is not strictly per item, it is per cart (or package)
- Shipping calculations are done independently in their own class
- What an extension does to calculate shipping is not 'visible' to WC core.
- If an extension for example wanted to split shipping by item, what would happen if you had 1 line item, but 2 qty as one example. That line item would need to be split somehow which is not currently possible within the API.

With that in mind, I don't think @kellychoffman's mockup is viable in 2.6. Related to that, only one shipping line is added per method: https://github.com/woothemes/woocommerce/blob/ac122f13b983973085692e73d6f9945d0987527f/includes/class-wc-checkout.php#L266 So again, thats not something I think can be handled in core at present when you are adding 1 'rate', which is a combination of rates via the same provider.

We could experiment with supporting sub-arrays of rates but we should do said experimentation with a new branch whilst building the extension to see if it works out. That should be handled separately.

cc @mattyza @allendav @claudiosmweb 

PR to follow with the package meta handling (as screenshot above) and some item box reworking I did.

**Comment by allendav** [comment]
Hmmm.   I see what you mean re #2 (especially the quantity > 1 problem) and I think https://github.com/woothemes/woocommerce/pull/10592 will have to do for now.  We may come back to the interleaved concept at a later date when we have more time.

cc @kellychoffman @mattyza
