### ISSUE TITLE
Coupons rounding issue on line items

### ISSUE THREAD

**Issue by melbwebdesign** [woothemes/woocommerce#10573]
Ive found an issue with the coupons where the rounding at 2 decimals is causing problems.  I have found items that are $19.955 become $19.55 for example where they should be $19.56

Same issue as https://github.com/woothemes/woocommerce/issues/8291 however after upgrading to v2.5 the issue doesn't seem to have been resolved.

The line total in the attached screenshot should be $24.51 not $24.50

![gtx50_coupon_rounding_issue](https://cloud.githubusercontent.com/assets/6956381/13835176/7cb0cc7a-ec49-11e5-8013-e7ad1d4aa9a1.jpg)

The main reason I am logging this issue as I use line items totals when inserting into MYOB, as this doesn't match the order total there is a credit applied automatically in MYOB software.

**Comment by mikejolley** [comment]
Define constant WC_DISCOUNT_ROUNDING_MODE to 1 to prevent this.

```
define( 'WC_DISCOUNT_ROUNDING_MODE', 1 );
```

However, this will cause you other issues - we round half down for a reason. Namely, if you have half values the displayed amounts won't 'add up'.

e.g.

```
Product $20 Discount 19.955 = 0.045
```

Round both up:

```
Discount 19.96
Product 0.05
Total = 20.01 (1 too much)
```

Round discount half down:

```
Discount 19.95
Product 0.05
Total = 20.00 (correct)
```

Sending the rounded values to MYOB should be the solution.

I'm guessing you edited your order manually since I did a 10% tax, 10% discount and got the following:

![2016-03-17 at 11 50](https://cloud.githubusercontent.com/assets/90977/13845245/92920242-ec36-11e5-91ac-1c9500e1cfc9.png)

**Comment by melbwebdesign** [comment]
Hi @mikejolley thanks for the info you've provided here.  It all makes sense, Ill try adding this constant and will see how it all goes.

The order wasn't manually edited, this is how it came through from order front end.  Thanks again

**Comment by melbwebdesign** [comment]
Hi @mikejolley I have set the define( 'WC_DISCOUNT_ROUNDING_MODE', 1 ); in my theme's functions.php to no avail.  The issue persists.
![gtx50_issue2](https://cloud.githubusercontent.com/assets/6956381/13939106/de5281d2-f025-11e5-9c68-2d3421e569df.jpg)

**Comment by mikejolley** [comment]
It only affects new orders.

**Comment by melbwebdesign** [comment]
Yes, this was a new order

**Comment by melbwebdesign** [comment]
Actually I completed several new orders, all were the same

**Comment by melbwebdesign** [comment]
If you check the line totals $24.50 + 2.45 = 26.95
The order total is actually $26.96

There is definitely an issue with the way the rounding is handled on the line items, it doesnt even agree with the order total which WooCommerce has calculated correctly

**Comment by mikejolley** [comment]
The rounding is actually correct **with the test case you are presenting.**

Your price is 27.23.

10% discount is 2.723. So in this case, the .5 rounding issue does not apply. Regardless of the way you round the number, the discount is 2.72.

`
27.23 - 2.72 = 24.51
`

So by editing the amount to 24.50, your maths is completely wrong. _Not a bug._

> I have found items that are $19.955 become $19.55 for example where they should be $19.56

This statement is true, and that case can be adjusted using the rounding constant which I will confirm works.

**Comment by melbwebdesign** [comment]
This is what Im saying, WooCommerce is calculating the line item prices incorrectly.  The example I have showed you comes directly from WooCommerce I haven't edited anything

**Comment by melbwebdesign** [comment]
Would it help if I gave you my WordPress admin logins to see the issue first hand?

**Comment by mikejolley** [comment]
It would help to see your status report; I'd be able to replicate it if it were a core rounding bug.

**Comment by melbwebdesign** [comment]
`
### WordPress Environment ###

Home URL: http://gtx50.holdingsite.com.au
Site URL: http://gtx50.holdingsite.com.au
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.18
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
SUHOSIN Installed: ✔
MySQL Version: 5.5.5
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Fifteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Give me your base country setting, product price (as entered), and tax rate %?

**Comment by melbwebdesign** [comment]
Base country = Australia, Queensland
Product price = $29.95
Tax rate = 10%
Products entered inclusive of tax

Thank you for looking into this

**Comment by mikejolley** [comment]
I was using ex. tax. Will test with the above.

**Comment by mikejolley** [comment]
Works in master, broken in 2.5. Can you apply this change to see if its that:

https://github.com/woothemes/woocommerce/commit/534cd2a38445afc577e0b129e6a5a638f37bc9ab

**Comment by mikejolley** [comment]
^ Confirmed the above fixed the issue.

**Comment by melbwebdesign** [comment]
The line totals haven't changed however the overall total has I don't think this is correct yet.  

The line totals should be as you pointed out:

$27.23 - $2.72 = $24.51

The tax would then be
$2.45

Total would be $26.96

![gtx50_error](https://cloud.githubusercontent.com/assets/6956381/14016228/e0ac9c44-f212-11e5-8149-9cfcb835eea7.png)

**Comment by mikejolley** [comment]
Remove the earlier modification is still present. With the above code I get 24.51 line. Without I get 24.50

**Comment by melbwebdesign** [comment]
The only modification I have in place is 534cd2a, but still cant get it to work.  Ill try again tomorrow, hopefully I'm just doing something wrong

**Comment by melbwebdesign** [comment]
Hi Mike, I can confirm this has fixed the issue

**Comment by mikejolley** [comment]
This fixed has caused some regression (https://github.com/woothemes/woocommerce/issues/10963). Working on a compromise.
