### ISSUE TITLE
Wrong images on the dummy data

### ISSUE THREAD

**Issue by sodbileg** [woothemes/woocommerce#10578]
After importing the dummy data, some of the products have wrong thumbnails.
Version 2.5.5

![image](https://cloud.githubusercontent.com/assets/1418797/13866276/b1c267f2-ecee-11e5-8771-0c64f4172098.jpeg)

**Comment by mikejolley** [comment]
Oh dear!

**Comment by mikejolley** [comment]
Data is fine. Links to http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_5_back.jpg

**Comment by mikejolley** [comment]
Ah CSV is not
