### ISSUE TITLE
Order creation via WP-CLI doesn't trigger order creation webhook 

### ISSUE THREAD

**Issue by mgatten** [woothemes/woocommerce#10583]
## EXPLANATION OF THE ISSUE

When you use "wp wc order create" to create an order, the order creation webhook does not fire. 

## STEPS TO REPRODUCE THE ISSUE

1. Create a webhook for order creation

2. Create an order with wp-cli. Here's a sample order I've created successfully:

`wp wc order create --path=/home/mqwr/public_html/wordpress --status='processing' --customer_id=324 --billing_address.first_name='Chester' --billing_address.last_name='Tester' --billing_address.address_1='123 Testing Lane' --billing_address.city='Testville' --billing_address.state='TN' --billing_address.postcode='12345' --billing_address.country='US' --billing_address.email='chester@tester.com' --billing_address.phone='8002345678' --shipping_address.first_name='Chester' --shipping_address.last_name='Tester' --shipping_address.address_1='123 Testing Lane' --shipping_address.city='Testville' --shipping_address.state='TN' --shipping_address.postcode='12345' --shipping_address.country='US' --note='Ship Via: FedEx Ground' --line_items.0.product_id=119 --line_items.0.quantity=1 --line_items.1.product_id=130 --line_items.1.quantity=2`

3. Check the log of the webhook you created and discover that your webhook didn't fire.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://<redacted>
Site URL: http://<redacted>
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.45
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.48
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (3) ###

Woocommerce CSV Import: by Allaerd Mensonides – 3.1.4
WooCommerce: by WooThemes – 2.5.5
WP All Import: by Soflyy – 3.3.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mgatten** [comment]
I  should mention that using `wp wc order update...` doesn't fire the Order Edited webhook either...

**Comment by claudiosmweb** [comment]
WP-CLI don't trigger any webhook for now.

**Comment by mgatten** [comment]
That's pretty much the point of this report. WP-CLI is needlessly crippled.

**Comment by mikejolley** [comment]
This will be resolved when CLI uses CRUD classes https://github.com/woothemes/woocommerce/pull/11208
