### ISSUE TITLE
API connect properly but I get an HTTP 200 "error"

### ISSUE THREAD

**Issue by LucaQapla** [woothemes/woocommerce#10585]
Hello,

WooCommerce version 2.5.4 
Using thi library:
https://github.com/helpforfitness/WooCommerce-REST-API-Client-Library-v2

Connection to api is ok but when I try to do anything I get this:

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => 200 [message] => cURL HTTP error 200 ) ) )

**Comment by LucaQapla** [comment]
fixed using this

https://github.com/kloon/WooCommerce-REST-API-Client-Library

**Comment by claudiosmweb** [comment]
Would best use of these: http://woothemes.github.io/woocommerce-rest-api-docs/#official-libraries
