### ISSUE TITLE
Store Products Overlaps 

### ISSUE THREAD

**Issue by UGNetworkMCN** [woothemes/woocommerce#10589]
Can anyone please help me with the problem, I am having. My store, through WordPress, is overlapping products. None of my customers can see my products clearly. Does anyone know exactly how to fix this problem? 

Here go the website link: http://www.ultimategamingnetwork.com/shop

**Comment by mikejolley** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support

Use CSS to style your products.
