### ISSUE TITLE
Site speed issues

### ISSUE THREAD

**Issue by JakWalker** [woothemes/woocommerce#10594]
Hey everyone. 

Ok so what's happening is that if im logged out of my wordpress with the Woocommerce plugin running on my site, it is lagging quite a bit, especially when first loading any pages. 

Now if I log in to wordpress it speeds up dramatically straight away! 

If I uninstall woocommerce and try again logged out the site is fine and running fast and smoothly. 

Basically Iv had this issue since using 2.5.0 and above, and if I downgrade to 2.4.13 there is no issues with the speed with Woocommerce. 

I have tried running with only woocommerce installed and a default theme and still Laggs really bad but only when logged out! 

Any help or advice would be much appreciated. 

Thanks

Jak

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support

This is not a valid bug report. You issue could be geolocation, could be missing sessions tables, missing files (see error console in browser) could be a conflict with a caching system. Lots of possibilities for you to look into, but not a bug, and certainly not enough info for anyone here to look into.
