### ISSUE TITLE
product created using REST API is not associated to vendor

### ISSUE THREAD

**Issue by jcampos73** [woothemes/woocommerce#10598]
## EXPLANATION OF THE ISSUE

When I create a product using REST API and vendor key (key is associated with a Vendor), created product is not associated to that vendor.

## STEPS TO REPRODUCE THE ISSUE

1. Generate a key/secret for a vendor.
2. Create a product via REST API using that key/secret

**Comment by claudiosmweb** [comment]
Don't seems to be an issue with WooCommerce, since WooCommerce don't have any method to Vendor. Please contact the support of your "Vendor" plugin for help with this.

**Comment by jcampos73** [comment]
Ok thx a lot for the fast answer
Regards
