### ISSUE TITLE
Default 'different shipping address'.

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10606]
When a guest ships to a different address, ensure the default country matches billing country (more likely scenario).

**Comment by Writecodeng** [comment]
Please I have been trying to fix an issue with woocommerce 2.6.9 since four days now. I cant display showing shipping options such as Local Pick-up, Flat rate and free shipping on the cart page and the checkbox to view ship to different address is not showing, please I need help pls
