### ISSUE TITLE
Product Delayed for ship in order of multipal products.

### ISSUE THREAD

**Issue by Ukboy** [woothemes/woocommerce#10608]
## EXPLANATION OF THE ISSUE
	
I have a woocommece medical store some time my client order 10 products and one product is missing in our stock. So i need to configure WC shows on order page that is product is delayed and ship you in next order. And also remind admin that product is also need to ship you to respective client.

**Comment by mikejolley** [comment]
You can notify the user with a 'customer note' - these are emailed.

The order would need to remain processing - again, using notes to track whats happening.
