### ISSUE TITLE
Simplify Commerce ZIP Code limits to 9 Characters - should sanitize

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#10604]
When using Simplify Commerce, users can enter in a nine-digit ZIP code address (which is valid), but it doesn't want to accept it.

As an example, this ZIP code is valid for Cincinnati, OH: `45220-2351`. It's the same as `45220`, though more precise. The `-` is pushing it past the 9 character limit, though, so could we look into modifying the character limit to 10 so it works?

Looks like the code is here: https://github.com/woothemes/woocommerce/blob/1512d448c158e47a6a59ca84da5740975f2c46ab/includes/gateways/simplify-commerce/assets/js/simplify-commerce.js#L28

Related ticket: https://woothemes.zendesk.com/agent/tickets/399297

**Comment by DanielSantoro** [comment]
Alternatively, that may not do the trick. It could be that we need to sanitize the string and remove the `-` so the nine-digit ZIP goes through correctly.

**Comment by DanielSantoro** [comment]
Hey all,

Here's a customer response to the fix:

> I saw on GitHub this was recorded a bug and the following edit has been made to: includes/gateways/simplify-commerce/assets/js/simplify-commerce.js
> 
> 30 + addressZip = addressZip.replace( /-/g, '' );
> 
> I have edited that file on y site to see if it solves the problem but I still get the following error when pressing place order button
> 
> a.. “undefined is invalid - Maximum length of addressZip is 9.” 
> a.. So I am not sure if there is some other file that needs to be edited or if this is dependent on some other change but this one change doesn’t seem to fix the issue when a 9-digit ZIP with format 5-4 is entered in the billing ZIP code field.

**Comment by justinshreve** [comment]
I just tested and I don't get the "Maximum length" error. I only get it if I comment out the fix.

From the way that was posted.... is the "30 +" somehow getting included in the change since they made a copy and paste? (That would return a different error/syntax error, though). 

That line is definitely the ZIP code that is passed back to Simplify.

**Comment by justinshreve** [comment]
I just tested and I don't get the "Maximum length" error. I only get it if I comment out the fix.

Deleted my last reply. Realized what it was after posting. They just updated the development version. `simplify-commerce.min.js` is loaded in production. https://github.com/woothemes/woocommerce/blob/master/includes/gateways/simplify-commerce/assets/js/simplify-commerce.min.js
