### ISSUE TITLE
WooThemes ShipStation Plugin - No Payment Method

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#10601]
Hi,

I am seeking a coding change to the WooCommerce ShipStation plugin. If this is the wrong place to ask, let me know.

In your WooCommerce ShipStation plugin, can you send the order payment method? Here is their response

> At this time, we do not receive the "Payment Method" field from the ShipStation for WooCommerce plugin we use to import orders from WooCommerce. If WooThemes includes that field in future updates to that plugin, ShipStation will adjust accordingly to make that field available for our API users as well. At this time, we do not have an ETA on if this feature will be made available by WooThemes.

**Comment by claudiosmweb** [comment]
> If this is the wrong place to ask, let me know.

Yes, contact woothemes support.
