### ISSUE TITLE
Stock is not reduced when an item is added to the cart #5966

### ISSUE THREAD

**Issue by bouviere** [woothemes/woocommerce#10600]
I refer to "Stock is not reduced when an item is added to the cart #5966"..... but here as the discussion is locked.

2 years and no viable solution, really...Jet so simple, it naturally needs to work just like in the real world, like when you go to the supermarket!

And that means:
1.	Timer reserving items in basket - here you naturally want short lead because customer made no effort to buy going to checkout. You want to serve the customer so they get the product in the basket, on other hand you also want to make it avail for others if customer don't check out.

- After lead time it is no longer reserved and may be sold out.

2.	Timer reserving items on orders PLACED via Checkout but not jet confirmed paid (whichever WC statuses that translates into), e.g. Bank Transfer option. Naturally you want to give such customer longer lead time - they made the effort to checkout and it may take some time to go to the bank etc.

- After lead time order is cancelled, user must then make new order or call us to re-activate e.g. if customer paid in meantime.

So trivial jet so many vendors using WC suffer from WC lack of action. Please, WC up your game.

And please hire a business person that understand consumer behavior. It fact that person should be the CTO of WC. All IT is subject to business.... no business money to make no need for IT.

/MARC

**Comment by mikejolley** [comment]
The other issue was locked for a reason. Put your vote on https://trello.com/c/VGIXzv5s/65-cart-stock-reducer if you'd like it in core. With only 4 votes, it doesn't appear very popular. I don't see anything related on http://ideas.woothemes.com/ either.

This feature would have implications - users could in theory completely _block real customers from purchasing anything by filling up their carts and staying active on the site_. Thats obviously not a scenario we'd like to see. Thats also one reason why its not simple as you suggest.

Some plugins seem to cover this anyhow so the feature is available if you need it:
https://wisdmlabs.com/empty-cart-timer-woocommerce-plugin/
https://wordpress.org/plugins/woocommerce-cart-stock-reducer/

Just to add, if someone places an order on something like PayPal, between order + payment confirmation, **the stock is held**. This is already in core.

For BACS, those orders are on-hold, so again, this stock is held. Again already in core.

Closing as plugin solutions already exist + this has been discussed before. cc @BFTrick @mattyza 

To end on a quote from the other issue:

> I just processed a survey from 1,700+ users (including store owners, freelancers, and developers from larger firms) last week and not a single one mentioned this as a problem. Based on that data alone I can say that it is an edge case.
>
> In fact only 10 of them even mentioned the word inventory and it wasn't related to this issue. I'd say our inventory system is pretty solid for right now.
>
> The vocal minority does not outweigh the voice of 1,700+ users. When our users start complaining about this we'll be happy to reinvestigate.

**Comment by bouviere** [comment]
Dear Mike,

 

I really appreciate that you reply. Thanks.

 

First why do you close my publications, that prevent other from making input, and you might discover there is a need. I didn’t know WC exercised censorship.

 

Second on group is your survey based. USA? In USA most have credit card so they pay during checkout. In Eastern Europe, Africa and some parts of Asia people do follow up payment by bank etc. so there the need in much in demand, if you want to be WWW (world Wide Web) you cannot stay in a focus on your home base – if you want to remain the leader.

Point: The real growth is outside the USA now.

A survey is good, but it need intelligent evaluation, not face value. If Steve Job had relied only on survey, we would never have had the IPhone, luckily for us all he did not – we would be stocked with Nokia.

 

If there as you say is no demand for this time out (and separate on basket and unpaid orders) why have leading retailer implemented it, I remember clearly they did not have it 3-4 years ago - like Shoedazzle (21 million customers), JustFab (11 million) or Amazon UK/Europe (+50 million)?

I think there is a reason they did it and it is the same I see in my business – without it there is far too much follow up administration (read: Cost).

 

This feature would have implications - users could in theory completely block real customers from purchasing anything by filling up their carts and staying active on the site. Thats obviously not a scenario we'd like to see. Thats also one reason why its not simple as you suggest.

·         Naturally the timer should starts from first item in basket.

·         It has no merit to say it would have implications. With such mind-set we would all be driving black cars (Ford: you can get it in any colour as long as you take it in black, we all know what happened J).

·         Issue is that another user can grab what first customer have in basket. You can’t do that in a real supermarket.

 

Some plugins seem to cover this anyhow so the feature is available if you need it:

If it has implications why and how can it then exist as features, that is contradicting statements. It would mean someone solved the implications or it does not work.

For BACS, those orders are on-hold, so again, this stock is held. Again already in core.
Yes, but as I understand it is same timer as basket or are you saying it is held until order is paid.

Issues are that:

-          Timer does not mean it is reserved in your basket, others can grab it if they check out first?

-          The timer acts for basket and orders on hold ?

Am I right or did I get it all wrong how it works.

Maybe I got it wrong how it works.

 

Basket and Order On-hold are really 2 different situations, they should have separate timers.

 

At risk of getting rejection I actually have a few other suggestions that would make life so much easier for content administrators – I am referring to situation of Variable Products and under Product Data:

-          Attributes: “Used for variation” default checked or one check box in top “Use all for variation” – so admins don’t need to mark-off all 30 variations very time, very time consuming.

-          Variations: “Manage Stock” default checked or a checkbox in top “All variations manage stock on variation level”. Save time that doing it 30 times.

-          Like the simple product have Regular price & Sales price field under General, it could be good to have same for variable products and is filled in that price apply for all variations. Often like in fashion it is same price for all variation. Having to insert same price 30 times is tedious. If field is blank it could take the default price.

-          Stock QTY, is important, but an Admin have to expand and then scoll and scoll…. Now if that field was visible in closed state next to the attributes, an admin could finish 30 variations in 30 seconds right now it takes minutes and many mistakes – time is money and with 200 products per day it is costly. (naturally item point only work if the other above are in place so Admin don’t need to expand).

Actually if you leave the weight blank under variations, it takes the default from Shipping section, why not have the same for above, would save so much time. Very simple to implement, big effect for content administrators.

You will not find a survey on these suggestions but running online business I hear it very week from my content managers.

 

 

Yours sincerely / Kwa dhati / Cordialement / Un cordial saludo

 

Smart ⦿ Duka

. . . Everyone wins

 

Office: (+254) 750-700-700

 

Marc Bouviere

mb@smartduka.com

Skype: mbouviere

**Comment by mikejolley** [comment]
> First why do you close my publications, that prevent other from making input, and you might discover there is a need. I didn’t know WC exercised censorship.

This thread is public, not censored. I directed you to 2 outlets to add feedback, and 2 solutions that already exist.

> Second on group is your survey based. USA? In USA most have credit card so they pay during checkout. In Eastern Europe, Africa and some parts of Asia people do follow up payment by bank etc. so there the need in much in demand, if you want to be WWW (world Wide Web) you cannot stay in a focus on your home base – if you want to remain the leader.

No country in particular. My home base is not the US either.

> Yes, but as I understand it is same timer as basket or are you saying it is held until order is paid.

Held until you change the order status.

Please reply on github in future; we don't need to read your email signature or the past comments.

**Comment by claudiosmweb** [comment]
> Second on group is your survey based. USA? In USA most have credit card so they pay during checkout. In Eastern Europe, Africa and some parts of Asia people do follow up payment by bank etc. so there the need in much in demand, if you want to be WWW (world Wide Web) you cannot stay in a focus on your home base – if you want to remain the leader.

I'm from Brazil, people here "do follow up payment by bank etc" too and the stock works well for them.
