### ISSUE TITLE
How to insert grouped product into database?

### ISSUE THREAD

**Issue by custard-apple** [woothemes/woocommerce#10607]
`
            [Item] => SimpleXMLElement Object
           (
                   
                    [ItemId] => 1
                    [MenuItemId] => 15000
                    [Name] => 12" PIZZA

                    [SubItems] => SimpleXMLElement Object
                        (
                            
                                [Item] => Array
                                (
                                  
                                         [0] => SimpleXMLElement Object
                                        
                                          (
                                            [ItemId] => 2
                                            [MenuItemId] => 17000
                                            [Name] => Margrita
                                            [Quantity] => 1
                                         )

                                    [1] => SimpleXMLElement Object
                                        (
                                            [ItemId] => 3
                                            [MenuItemId] => 16000
                                            [Name] => Capsicum
                                            [Quantity] => 1
                                         )
                               )

                        )
          )`

This is grouped product data.I searched a lot on net but couldn't find any solution.please tell me how to insert it into database?

**Comment by mikejolley** [comment]
A grouped product in WooCommerce is just a product with type 'grouped'. The child of said group link via post_parent ID. Create one manually to see how they work.

**Comment by custard-apple** [comment]
I want to create it programmatically.

**Comment by custard-apple** [comment]
I'm trying so hard to solve this plz reopen the issue.when I wantr to store the group product its storing only simple product.
`wp_set_object_terms( $product_id, 'grouped', 'product_type', false);`
when I adding it its storing `[product_type] => simple` into the database. #10607
