### ISSUE TITLE
Woocommerce API : Coupon lines properties not returning correct coupon ID

### ISSUE THREAD

**Issue by maryglo** [woothemes/woocommerce#10616]
Good Day,

I used the woocommerce REST API on my admin portal to view and manage products and orders. When I checked the properties returned when I tried to get the properties of an order by id, the data for coupon_lines are is missing. The value of coupon line ID is returning a 0 value.

Kindly refer to the attached screenshot.

Thanks!
![order_dump](https://cloud.githubusercontent.com/assets/7532071/14104927/da8e458a-f5da-11e5-950f-38b08a5e607a.PNG)

**Comment by mikejolley** [comment]
This is the 'line item ID', not the coupon ID. If you want the coupon ID and data, expand the coupon object - see https://woothemes.github.io/woocommerce-rest-api-docs/#view-an-order

**Comment by maryglo** [comment]
Hi Mike,

                    I highlighted the coupon lines data on the dumped order data on my screenshot. Why is it the value is 0? Even if it is the line item ID, it should not return a 0 value right?

Thanks.

**Comment by maryglo** [comment]
Hi,

               Is there any reason why is this happening? I badly needed a fix regarding this. I hope someone can provide an answer.
