### ISSUE TITLE
Permalinks: Shop base w/ categories issue

### ISSUE THREAD

**Issue by joelwills** [woothemes/woocommerce#10619]
**The issue**

When using "Shop base with category" as the Product Permalink, when viewing a single product page, the category name in the permalink can be set to anything and still shows the single product.

**To reproduce**

- Under Settings > Permalinks set your Product Permalinks to be "Shop base with category"
- This sets it  as `/shop/%product_cat%`
- Visit any product page e.g:

https://XXXXXX/shop/clothing/my-single-product/

Replace the category slug in the URL with anything, e.g:

https://XXXXXX/shop/whatever-you-want-here/my-single-product/

The single product page still appears whatever the category slug part of the permalink it.

This is an SEO issue, for example when changing the category of a product, the old URL still works (as any category name works), duplicating the product page.

Would expect only the correct category name will show the single product page. Entering anything else should result in a 404. If a category is changed for a product, then a 301 redirect to the new URL would be ideal.

Tested with only WooCommerce and default theme enabled. Replicated on test site.

**Comment by mikejolley** [comment]
The hierarchy in the URL is only there for show - its not a true hierarchy. If you want redirects you'll need to set them up via plugin or htaccess rules.

**Comment by mikejolley** [comment]
Also, the same occurs for all post types.

**Comment by joelwills** [comment]
> Also, the same occurs for all post types.

It doesn't do that for posts.

e.g Custom permalink for posts set to `topics/%category%/%postname%/`

URL of a post looks like:

https://XXXXX/topics/category/post-name/

If you enter

https://XXXXX/topics/whatever-you-want-here/post-name/

It redirects to the correct URL, it doesn't just show the post at the incorrect URL. 

If I change category to a different one, the old URL redirects to the new correct one and doesn't just show the post at the incorrect old URL.

I'd expect the same of products, wouldn't you?

**Comment by mikejolley** [comment]
I see. I just did some research into this. WordPress has some special %category% handling to handle those canonical redirects. Unfortunately, WP exits early so we cannot filter the redirect to add our own special handling for products. Issue:

https://core.trac.wordpress.org/ticket/31300#comment:3

Although we could replicate it for %product_cat% via another hook such as template_redirect, there are many 'gotchas' with URLs and redirects and I'm worried we will cause redirect loops for some users. redirect_canonical takes care these but as I said, that function is off limits. The main difficulty would be accurately getting the current URL consistently across all installs, accounting for server environment and any locale specific things. Any mishandling would cause an endless redirect loop.

I'll monitor that trac ticket; when it gets merged into core, I'll put in a patch. Until then it can be handled in custom code;

- hook into template redirect
- if is_singular( 'product' ) is true, 
- get the global $post ID, 
- get the permalink, 
- compare to current URL
- redirect

Marking as won't fix for now.

**Comment by joelwills** [comment]
Thanks Mike!

**Comment by mainlyer** [comment]
Hi all, everybody have the same issue and I found a solution rewriting the rules of each category and its pagination. Then I have:

- Shop page: products
- Product category base: products
- Product tag base: products/tags

The code is the following (you can paste it in your **functions.php** file):

```
add_filter("rewrite_rules_array", function ($rules) {
  global $wp_rewrite;

  $option = get_option("woocommerce_permalinks");
  if (!$option) {
    return $rules;
  }

  $category_base = $option["category_base"];
  $pagination_base = $wp_rewrite->pagination_base;

  $terms = array_map(function ($term) {
    return (object)array("term_id"   => $term->term_id,
                         "parent_id" => $term->parent,
                         "parent"    => NULL,
                         "slug"      => $term->slug,
                         "path"      => NULL);
  }, get_terms("product_cat", array("hide_empty" => 0)));
  
  foreach ($terms as $term) {
    $term->parent = array_pop(array_filter($terms, function ($parent) use ($term) {
      return ($term->parent_id == $parent->term_id);
    }));
  }

  foreach ($terms as $term) {
    $slugs = array();
    $current_term = $term;
    while ($current_term) {
      array_unshift($slugs, $current_term->slug);
      $current_term = $current_term->parent;
    }
    $term->path = implode("/", $slugs);
  }
  
  usort($terms, function ($temr1, $temr2) {
    return (substr_count($temr1->path, "/") > substr_count($temr2->path, "/")) ? -1 : 1;
  });
  
  $new_rules = array();
  
  foreach ($terms as $term) {
    $new_rules["$category_base/$term->path/$pagination_base/([0-9]{1,})/?$"] = "index.php?product_cat=$term->slug&paged=\$matches[1]";
    $new_rules["$category_base/$term->path/?$"] = "index.php?product_cat=$term->slug";
  }

  return array_merge($new_rules, $rules);
});

add_action("edited_product_cat", function ($term_id, $taxonomy) {
  flush_rewrite_rules();
}, 10, 2);
```

Remember to save your permalinks options after inserting the code in order to generate the rewrite rules.

No more SEO issues.

Best regards,
Miguel.

**Comment by dk9** [comment]
@mainlyer Hello! Thanks for your snippet.
I used it just now and noticed that also all of my 'normal' categories (like for post) have now a "category" before. IE: www.site.com/category/category
Is there a way to change it?
Also, how do I reverse your snippet? I removed it from functions, refreshed permalinks but it is still affected.
Thanks so much :)

**Comment by mainlyer** [comment]
Hi @dk9, if you change your **product category base** to be like your **shop base** you should get it.

To revert it simply remove the code and save permalink options or just call once flush_rewrite_rules().

Best regards,
Miguel.

**Comment by mainlyer** [comment]
Hello @eljkmw, the snipet is intended for change the **product category permalinks**. I supose you want to change the **product permalinks**, based on its categories, Isn't it?

Regards,
Miguel.

**Comment by eljkmw** [comment]
You're right @mainlyer
I want to change the <b>product permalinks</b> that still keeps the <b>product category base</b>.

**Comment by mainlyer** [comment]
Ok @eljkmw, there is an important concept about woocommerce product categories. A product can have none, one or more categories. Then, to do what you want, at least, you need the ability to select a primary category for a product. All right?

I don't know if you have installed **Yoast SEO** plugin, but if you install it, you will can select a primary category for each product, editing it as usual.

At this point I can try to get a solution for your requirement, because I find it an interesting request.

Let me know when you solve that to continue, or if you don't understand something.

Regards,
Miguel.

**Comment by eljkmw** [comment]
Yes, Miguel. I've Yoast SEO plugin installed.
However, I'm deciding to uninstall it by end of this month.  I find its Primary Category feature somewhat a nuisance.

What are your thoughts?

**Comment by mainlyer** [comment]
Perfect @eljkmw, then, without the ability to select a primary category, the only solution I can see is keeping all products only in one category (and subcategories) at the same time. For example, if you have the following category tree:

- Cat 1
- Cat 2
  - SubCat 2.1
    - SubSub Cat 2.1.1
  - SubCat 2.2
- Cat 3

You only had the ability to select one combination of the following:

- Cat 1
- Cat 2
- Cat 2 and SubCat 2.1
- Cat 2 and SubCat 2.1 and SubSubCat 2.1.1
- Cat 2 and SubCat 2.2
- Cat 3

In that way, although you dont have the ability to select a primary category, as only one branch of the tree is selected, you have a unique category context for each product.

Is suitable for you?

Regards,
Miguel.

**Comment by eljkmw** [comment]
You've read my mind well, Miguel.

**Comment by mainlyer** [comment]
Perfect @eljkmw, then I think there is a solution for that. Give me a moment to find it out.

**Comment by eljkmw** [comment]
Cheers, Miguel.  Please take your time.
I truly appreciate your kind gesture.  Thank you very much.

**Comment by mainlyer** [comment]
Hi again @eljkmw, test the following code:

`add_filter("post_type_link", function ($url, $post) {
    $option = get_option("woocommerce_permalinks");
    if (!$option) {
        return $url;
    }

    if (get_post_type($post) === "product") {
        $terms = get_the_terms($post, "product_cat");
        if ($terms) {
            $url = get_site_url() . "/" . $option["category_base"];
            
            usort($terms, function($term1, $term2) {
                return ($term1->parent < $term2->parent) ? -1 : 1;
            });

            $terms = array_map(function ($term) {
                return $term->slug;
            }, $terms);

            $url .= "/" . implode("/", $terms) . "/";

            if (is_admin()) {
                return $url . "%product%/";
            }

            return $url . $post->post_name . "/";
        }
    }
    
    return $url;
}, 10, 2);
`

Remember the category selection constraint, if you don't follow it you will get wrong permalinks.

Regards,
Miguel.

**Comment by eljkmw** [comment]
Understood, and thanks.
I'll test it out over this weekend.

**Comment by eljkmw** [comment]
@mainlyer I just tested your new snippet.  And there are a couple of issues.
The product permalink shows **only one category**, and strangely **%product%/** appears
e.g., https://testsite/shop/pants/%product%/

I was hoping that it'll be like, e.g., https://testsite/shop/clothing/pants/single-product/

**Comment by mainlyer** [comment]
Did you selected both category and subcategory?
Are you using lastest versions of woocommerce and wordpress?

**Comment by eljkmw** [comment]
Yes.  Both category and subcategory are selected.
However, I'm using WooCommerce 3.2.6, and WordPress 4.9.2.

**Comment by mainlyer** [comment]
Ok @eljkmw, then I don't think versions have the problem. I'm using WordPress 4.9.4 and WooCommerce 3.3.3. Is your site public?

**Comment by eljkmw** [comment]
Well, Miguel.  Sorry for the inconvenience.  If both versions aren't the problem, perhaps it's best that I get <a href="https://masterns-studio.com/code-factory/wordpress-plugin/woo-category-base/" target="_blank">this plugin</a>.  Please let me know your thoughts.  Thanks.

Regards,
Jason

**Comment by mainlyer** [comment]
Is strange because %product% only should show on admin pages (e.g editing the product), is for that the using of is_admin() function. You can try the plugin, but if the snipet didn't work, I don't know if you are going to be lucky with it.

If you see %product% in your frontend there is something wrong with your WordPress installation.

Let me know your experience.

Regards,
Miguel.

**Comment by eljkmw** [comment]
I'm definitely seeing %product% in my frontend, which is rather strange.
Anyway, I decided to give the plugin a shot at a minimal donation of USD 5.

So far it appears to be doing exactly as your <b>first snippet</b> for the <b>product category permalinks</b>.  However, it's suppose to generate a <b>pretty permalink</b> to a 3rd level category, but I still see only one category.  I'm unsure why this is the case, which I'm guessing it may be conflicting with the Yoast SEO plugin.  Will drop the developer(s) a message about this issue soon.

**Comment by eljkmw** [comment]
I tested your 2nd snippet on my demo website, and found the same order.
Apparently, there is a tiny mistake to the following lines of code.
```
            if (is_admin()) {
                return $url . "%product%/";
            }
```
It should be instead
```
            if (!is_admin()) {
                return $url . "%product%/";
            }
```
You've missed out an exclamation mark ! before **is_admin()**

**Comment by eljkmw** [comment]
I tested your 2nd snippet on my demo website, and it appears to be working fine.
I can only guess Yoast SEO is messing with your snippet.

**Comment by mainlyer** [comment]
I supposed that, because of the behaviour of your WordPress installation. is_admin() only is true when you are in the backend. Something is wrong, I encourage you to tests only with woocommerce plugin enabled.

What theme you are using? Tried with sorefront?

Regards,
Miguel.

**Comment by eljkmw** [comment]
The theme I've been using is <a href="https://themeforest.net/item/alto-awesome-ajax-woocommerce-theme/15755911">Alto Theme</a>, and it's been terribly and badly coded theme.  Although it's a pretty theme, I had to implement lots of fixes to get it working properly.

Anyway, the select below creates an [Edit] button in the admin of Edit product.
```
            if (is_admin()) {
                return $url . "%product%/";
            }
```
The funny thing is that the permalink shows the suffix of **%product%/**  Strange indeed.

**Comment by mainlyer** [comment]
Is for that only should run on backend. In frontend needs the product slug. If you comment that you will see you can't change the product slug in the edit page.

**Comment by mainlyer** [comment]
A weird workarround could be to check $_SERVER["REQUEST_URI"] to start with wp-admin.

But is strange is_admin() returns false in backend, I don't know how your site is working fine.

**Comment by eljkmw** [comment]
It's alright now.  I guess it must've been my web browser's cache.

**Comment by mainlyer** [comment]
Then perfect!! it was very strange.

Regards,
Miguel.

**Comment by eljkmw** [comment]
Hi Miguel,
With your snippet, I manage to find a couple of hidden bugs from the <a href="https://themeforest.net/item/alto-awesome-ajax-woocommerce-theme/15755911">Alto Theme</a>, which I failed to spot before.

Anyway, how to get **%product%/** in the admin Product edit page to save the product slug into a complete URL that I can click on to view the product on the frontend?  Please advise.  Thank you.

Regards,
Jason

**Comment by mainlyer** [comment]
The original snippet do it. is_admin() is working for you right now or stills return false in backend?

**Comment by eljkmw** [comment]
is_admin() is working fine.  Although the Permalink in Product edit shows:
https://testsite/shop/clothing/pants/product-slug/
the link is actually:
https://testsite/shop/clothing/pants/%product%/

Any way to resolve this?

**Comment by mainlyer** [comment]
Did you remove th negation !is_admin() from the snippet?

**Comment by eljkmw** [comment]
I'm using the original 2nd snippet you added way above.

**Comment by mainlyer** [comment]
Then, to figure out:

- In your frontend the product permalink is **/testsite/shop/clothing/pants/%product%/**
- In your backend the product permalink is **/testsite/shop/clothing/pants/product-slug/**

Is this correct?

**Comment by eljkmw** [comment]
Nope.  It's the opposite.
The frontend is working fine, with the product permalink as **/testsite/shop/clothing/pants/product-slug/**

On the backend, the product permalink is **/testsite/shop/clothing/pants/%product%/**
Surely, this URL will lead to a 404 page.

**Comment by mainlyer** [comment]
OK, and in the product edit page, do you see de **Edit** button in the product slug?

**Comment by eljkmw** [comment]
Yes.

**Comment by mainlyer** [comment]
Then, where do you see **%product%** in your backend?

**Comment by eljkmw** [comment]
![screen shot 2018-02-24 at 4 32 21 am](https://user-images.githubusercontent.com/33481926/36615665-0851cae4-191c-11e8-9407-3cb522f0f06b.png)
When I bring the mouse cursor over the Permalink URL, it doesn't match up.

**Comment by mainlyer** [comment]
OK, I found it, I'm gonna to check the snippet.

**Comment by mainlyer** [comment]
Test the  snippet:

```
add_filter("post_type_link", function ($url, $post) {
    $option = get_option("woocommerce_permalinks");
    if (!$option) {
        return $url;
    }

    if (get_post_type($post) === "product") {
        $terms = get_the_terms($post, "product_cat");
        if ($terms) {
            $is_editing = stripos($url, "%product%") > 0;
            $url = get_site_url() . "/" . $option["category_base"];
            
            usort($terms, function($term1, $term2) {
                return ($term1->parent < $term2->parent) ? -1 : 1;
            });

            $terms = array_map(function ($term) {
                return $term->slug;
            }, $terms);

            $url .= "/" . implode("/", $terms) . "/";

            if ($is_editing) {
                return $url . "%product%/";
            }

            return $url . $post->post_name . "/";
        }
    }
    
    return $url;
}, 10, 2);
```

**Comment by eljkmw** [comment]
Awesome!  It's working perfectly.  Many thanks, Miguel.

**Comment by mainlyer** [comment]
Hi @eljkmw, you are welcome! I'm glad to helped you.

P.S.: I removed them. We can remove is_admin() issue too because I remove the first versión of the last snippet.

Best regards,
Miguel.

**Comment by eljkmw** [comment]
Hi Miguel,
For helping me, I wanna give you a treat.
Kindly drop me an email message at:
ELJKMW@YAHOO.COM

Cheers,
Jason

**Comment by mainlyer** [comment]
Hi @eljkmw, the following snippet will set your product permalink according the selected Yoast SEO primary category.

```
add_filter("post_type_link", function ($url, $post) {
    $option = get_option("woocommerce_permalinks");
    if (!$option || get_post_type($post) != "product") {
        return $url;
    }

    $primary_category_id = get_post_meta($post->ID, "_yoast_wpseo_primary_product_cat", true);
    if (!$primary_category_id) {
        return $url;
    }

    $category = get_term($primary_category_id);
    $slugs = array($category->slug);
    while ($category->parent) {
        $category = get_term($category->parent);
        $slugs[] = $category->slug;
    }
    $slugs = array_reverse($slugs);
    
    $is_editing = stripos($url, "%product%") > 0;
    $url = get_site_url() . "/" . $option["category_base"] . "/" . implode("/", $slugs) . "/";

    if ($is_editing) {
        return $url . "%product%/";
    }

    return $url . $post->post_name . "/";
}, 10, 2);
```

And remember, each product has an unique permalink although it has several categories.

Please, read [https://docs.woocommerce.com/document/permalinks/](url)

Regards,
Miguel.

**Comment by eljkmw** [comment]
Hi Miguel @mainlyer , it's been a while since we corresponded, and I was wondering how do I remove the WooCommerce category_base of either "Shop" or "Product" from your snippet above?

Please advise.  Thanks in advance.

**Comment by eljkmw** [comment]
Hi Miguel @mainlyer , it's been a while since we corresponded, and I was wondering how do I remove the WooCommerce category_base of either "Shop" or "Product" from your snippet above?

Please advise. Thanks in advance.

**Comment by eljkmw** [comment]
Hi Miguel @mainlyer , it's been a while since we last corresponded, and I was wondering how do I remove the WooCommerce category_base of either "Shop" or "Product" from your snippet above?

e.g., http://testsite.dev/clothing/pants/single-product/  ... where there is no "/shop/" between "testsite.dev" and "clothing/pants/single-product/"

Please advise. Thanks in advance.

**Comment by eljkmw** [comment]
Hi @mainlyer 

How do I modify your previous code above without the **shop base**?
I want to re-use your modified code for 2 different page categories.

Please advise.  Thank you.

**Comment by moscatovida** [comment]
@mainlyer 

Hi Miguel, Thanks for your script! It seems to work, but for some reason it throws this error in the log file:

**"Only variables should be passed by reference"**

The error relates to this section here:

```
  foreach ($terms as $term) {
    $term->parent = array_pop(array_filter($terms, function($parent) use ($term) {
      return ($term->parent_id == $parent->term_id);
    }));
```

Hope you can help!

Thank you!

**Comment by mainlyer** [comment]
Hi @moscatovida, array_pop needs to pass a variable:

```php
foreach ($terms as $term) {
    $parents = array_filter($terms, function ($parent) use ($term) {
        return $term->parent_id == $parent->term_id;
    });

    $term->parent = array_pop($parents);
}
```

Hope this helps!

Regards,
Miguel.

**Comment by moscatovida** [comment]
@mainlyer you're a lifesaver! That was it – works like a charm now :) **Thank you so much!**

Maybe helpful for others to know: The error message appeared when saving a product term, for instance: /wp-admin/term.php?taxonomy=product_cat&tag_ID=14&post_type=product
