### ISSUE TITLE
Make dimension and weight optional for variable products (and still show child values)

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10621]
One idea was to get the min or max value and show a range or 'from' value.

**Comment by douglsmith** [comment]
One use scenario I run into is selling a book as a variable product with variations for a physical and e-book formats. The printed book would have dimensions and weight. A PDF e-book might have dimensions but a Kindle version would not. And neither e-book format would have weight.

**Comment by suncat3** [comment]
It would be great if the weight and dimension could be changed with each variation. We have a client that has a kite design that comes in different sizes so each variation is a different weight and sometimes is a different dimension too. This requested feature is critical for accurate product shipping calculations.
