### ISSUE TITLE
is_shop() causes PHP notices on pre_get_posts hook when loading static homepage

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#10625]
Found an interesting issue where using is_shop() inside the pre_get_posts hook will cause numerous PHP notices when loading a site with a static homepage.

To reproduce:

1. Spin up a fresh WP + WooCommerce
2. Create a standard page and set it as the static homepage under Settings->Reading
3. Import dummy data (just so we can see something on the shop page)
4. Turn WP_DEBUG on
5. Add the following function to your functions.php file (just some sample code to demo the problem)

```
add_action( 'pre_get_posts', 'do_something_awesome', 1 );

function do_something_awesome() {
	if (is_shop()) {
		error_log( 'hello shop :)' );
	}
}
```

Note the PHP notices showing:

Notice: Trying to get property of non-object in /xxxx/wp-includes/query.php on line 4529
Notice: Trying to get property of non-object in /xxxx/wp-includes/query.php on line 4531
Notice: Trying to get property of non-object in /xxxx/wp-includes/query.php on line 4533

This problem occurs with older Woo versions and on any theme in my testing, but the above was tested on fresh WP install with stock WooCommerce and default theme.

For the record, the is_shop function actually does work fine in pre_get_posts (visit the actual shop page and you'll see my error_log from the function above), but just not when you have a static homepage set.

I've tried several workarounds for not using is_shop, but it's incredibly hacky and I'd just prefer to use the proper function which should work without sending out a bunch of notices.

**Comment by mikejolley** [comment]
Caused by `is_page`

https://core.trac.wordpress.org/ticket/21790

**Comment by jkohlbach** [comment]
Hey Mike, are you able to weigh in on that ticket? It's effecting WooCommerce just as much as it's effecting other plugin devs too and I think your word would go a bit further than mine.

Looks like it already has a patch and unit test ready to go via this ticket:
https://core.trac.wordpress.org/ticket/27015

Just hasn't made it into a release for some reason?? Very odd.

**Comment by claudiosmweb** [comment]
Maybe it can work:

```php
add_action( 'pre_get_posts', 'do_something_awesome', 1 );

function do_something_awesome( $query ) {
    if ( $query->is_post_type_archive( 'product' ) || $query->is_page( wc_get_page_id( 'shop' ) ) ) {
        error_log( 'hello shop :)' );
    }
}
```

**Comment by jkohlbach** [comment]
Actually @claudiosmweb the workaround is a bit more involved. We've tested this pretty thoroughly:

add_action( 'pre_get_posts', 'is_shop_workaround_demo', 1 );

function is_shop_workaround_demo( $query ) {
	$front_page_id        = get_option( 'page_on_front' );
    $current_page_id      = $query->get( 'page_id' );
    $shop_page_id         = apply_filters( 'woocommerce_get_shop_page_id' , get_option( 'woocommerce_shop_page_id' ) );
    $is_static_front_page = 'page' == get_option( 'show_on_front' );

	// Detect if it's a static front page and the current page is the front page, then use our work around
	// Otherwise, just use is_shop since it works fine on other pages
    if ( $is_static_front_page && $front_page_id == $current_page_id  ) {
		error_log( 'is static front page and current page is front page' );
		$is_shop_page = ( $current_page_id == $shop_page_id ) ? true : false;
	} else {
		error_log( 'is not static front page, can use is_shop instead' );
        $is_shop_page = is_shop();
	}

	// Now we can use it in a conditional like so:
	if ($is_shop_page) {
		error_log( 'this is the shop page' );
	}
}

If anyone comes along here looking for a solution, please feel free to use the above workaround code in the meantime until WP core gets this fixed.

**Comment by TimbreDesign** [comment]
Seems like this still has not been fixed?
I'm running into this on the front page:
Trying to get property of non-object ~> wp-includes/class-wp-query.php:3750 (& 3752/3754)
WP_Query->is_page() ~> wp-includes/class-wp-query.php:3688

**Comment by brunompbarbosa** [comment]
Just as FYI, on October 2018 this core issue is still unresolved and this code saved me!

**Comment by kLOsk** [comment]
I see also different very strange behaviour here.
error_log($query->get( 'page_id' ));
This, within 'pre_get_posts' returns 0 for every WC page? Has anyone seen this and might have an idea why this happens? pre_get_posts being called in functions.php of a theme.

**Comment by kLOsk** [comment]
Here's an example query dump from wc_archive page

<pre><code>[25-Oct-2018 07:03:17 UTC] WP_Query Object
(
    [query] => Array
        (
            [post_type] => product
        )

    [query_vars] => Array
        (
            [post_type] => product
            [error] => 
            [m] => 
            [p] => 0
            [post_parent] => 
            [subpost] => 
            [subpost_id] => 
            [attachment] => 
            [attachment_id] => 0
            [name] => 
            [static] => 
            [pagename] => 
            [page_id] => 0
            [second] => 
            [minute] => 
            [hour] => 
            [day] => 0
            [monthnum] => 0
            [year] => 0
            [w] => 0
            [category_name] => 
            [tag] => 
            [cat] => 
            [tag_id] => 
            [author] => 
            [author_name] => 
            [feed] => 
            [tb] => 
            [paged] => 0
            [meta_key] => 
            [meta_value] => 
            [preview] => 
            [s] => 
            [sentence] => 
            [title] => 
            [fields] => 
            [menu_order] => 
            [embed] => 
            [category__in] => Array
                (
                )

            [category__not_in] => Array
                (
                )

            [category__and] => Array
                (
                )

            [post__in] => Array
                (
                )

            [post__not_in] => Array
                (
                )

            [post_name__in] => Array
                (
                )

            [tag__in] => Array
                (
                )

            [tag__not_in] => Array
                (
                )

            [tag__and] => Array
                (
                )

            [tag_slug__in] => Array
                (
                )

            [tag_slug__and] => Array
                (
                )

            [post_parent__in] => Array
                (
                )

            [post_parent__not_in] => Array
                (
                )

            [author__in] => Array
                (
                )

            [author__not_in] => Array
                (
                )

        )

    [tax_query] => WP_Tax_Query Object
        (
            [queries] => Array
                (
                )

            [relation] => AND
            [table_aliases:protected] => Array
                (
                )

            [queried_terms] => Array
                (
                )

            [primary_table] => 
            [primary_id_column] => 
        )

    [meta_query] => 
    [date_query] => 
    [post_count] => 0
    [current_post] => -1
    [in_the_loop] => 
    [comment_count] => 0
    [current_comment] => -1
    [found_posts] => 0
    [max_num_pages] => 0
    [max_num_comment_pages] => 0
    [is_single] => 
    [is_preview] => 
    [is_page] => 
    [is_archive] => 1
    [is_date] => 
    [is_year] => 
    [is_month] => 
    [is_day] => 
    [is_time] => 
    [is_author] => 
    [is_category] => 
    [is_tag] => 
    [is_tax] => 
    [is_search] => 
    [is_feed] => 
    [is_comment_feed] => 
    [is_trackback] => 
    [is_home] => 
    [is_404] => 
    [is_embed] => 
    [is_paged] => 
    [is_admin] => 
    [is_attachment] => 
    [is_singular] => 
    [is_robots] => 
    [is_posts_page] => 
    [is_post_type_archive] => 1
    [query_vars_hash:WP_Query:private] => 78974a905bc38b015abf05486ce539e1
    [query_vars_changed:WP_Query:private] => 
    [thumbnails_cached] => 
    [stopwords:WP_Query:private] => 
    [compat_fields:WP_Query:private] => Array
        (
            [0] => query_vars_hash
            [1] => query_vars_changed
        )

    [compat_methods:WP_Query:private] => Array
        (
            [0] => init_query_flags
            [1] => parse_tax_query
        )

)
</code></pre>
