### ISSUE TITLE
Geolocation and VAT override for google adwords shopping

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#10626]
Is there a way we can override the geolocation with a query string at the end of the domain and have the user redirected to a landing page which shows the VAT amount for the base country?

We are using geolocation so it displays pricing correctly for all customers based on their location however apparently google need to have a specific landing page which, when accessed from anywhere in the world, displays the UK pricing and UK VAT for the UK feed.

Is there a way to force this with a query string?

Or alternatively, is there a way to force this by extracting the "AdsBot-Google" from the user-agent field and overriding the tax functionality?

The first way would be preferable, as the landing pages in the first instance are checked by a human, and then subsequently by a robot.

Thanks

**Comment by mikejolley** [comment]
No way to force it, but it may be good to do some kind of exclusion for bots because geolocating crawlers is also not ideal/slower

**Comment by mikejolley** [comment]
O, you can also use woocommerce_customer_default_location_array filter to set the default location to something of your choosing.

**Comment by shawaj** [comment]
So would something like this work:

function set_country_programmatically() {
  if(!is_admin() || defined('DOING_AJAX')) {
        if(isset($_GET['country']])) {
            $_POST['woocommerce_customer_default_location_array'] = $_GET['country'];
        }
  }
}
add_action('woocommerce_init', 'set_country_programmatically', 0);

Or would that mess with the geolocation?
