### ISSUE TITLE
Bug: List Coupons Is Only Returning 9

### ISSUE THREAD

**Issue by jbcoder** [woothemes/woocommerce#10623]
## EXPLANATION OF THE ISSUE

I have a large number of coupons. However, when I call for the list of my coupons, only nine are returned. I was expecting many more. Furthermore, the nine don't indicate whether they have been applied or how many times they've been applied.

**Comment by mikejolley** [comment]
Not much detail here. I assume you mean via API?

https://woothemes.github.io/woocommerce-rest-api-docs/#parameters

```
Requests that return multiple items will be paginated to 10 items by default. This default can be changed by the site administrator by changing the posts_per_page option. Alternatively the items per page can be specified with the ?filter[limit] parameter:
```

Coupon endpoint does not return usage stats, just details on said coupon.

**Comment by jbcoder** [comment]
Gotcha. Thanks. It wasn't indicated anywhere in the multiples coupon section. However, I'm still just getting "undefined" if I limit it to the total number of coupons. Thanks for the help.
