### ISSUE TITLE
Page for change password in woocommerce 2.5.5

### ISSUE THREAD

**Issue by chetan-naik** [woothemes/woocommerce#10635]
## EXPLANATION OF THE ISSUE

I need to create change password page for members after they login, but i can't find any resource for that, i'm using woo commerce version 2.5.5.

**Comment by claudiosmweb** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>   - https://wordpress.org/support/plugin/woocommerce for general support
>   - https://support.woothemes.com for premium plugin support
