### ISSUE TITLE
API - SKU already exist but getting error when filtering list of products by the SKU

### ISSUE THREAD

**Issue by scudai** [woothemes/woocommerce#10638]
Hi,

I am working on the Java application - it is stand alone store manager. I am fighting several days with an interesting issue and I guess it is probably a bug.

All is tested with WooCommerce 2.5.5 

**1. Issue**

I tried to create a product ABC with its variants. I checked that product and its variatns SKUs are not in the eshop and are not in the trash! But still I get error message: _"woocommerce_api_product_sku_already_exists"._
I read that this can happen because product data are not cleared from database table _wp_postmeta_ event after it was deleted. Either this is a bug or it has some specific reason that data which is no more needed stay in the table. I am not WordPress developer so may be I something misunderstood, so if everything is okay could you please direct me to the source of information where I can get knowledge about it.

**2. Issue**
Let's say that WordPress, for any reason, has to keep some data in wp_postmeta (I mean table row with old SKU). 
Okay no problem, so I have changed the way how are products synchronized with eshop. If my product ABC is in store manager new and was never uploaded to eshop, I will try to create it. If this failed because of existing SKU error, I ask WooCommerce to get list of product IDs with the ABC product SKU and also all product IDs with the ABC product variations SKU. I do that by using filter parameter in query like this "_filter[sku]=ABC_PRODUCT_SKU_" and later "_filter[sku]=ABC_PRODUCT_VARIATION_SKU_".
And here we come to the problem. When I filter SKU  by _ABC_PRODUCT_VARIATION_SKU_ I get response code 200, but with the error message:

**GET**  `http://www.example.com/wc-api/v3/products?fields=id&filter%5Bsku%5D=kx0631_7&............
`

```
<br />
<b>Notice</b>:Trying to get property of non-object in <b>wp-content/plugins/woocommerce/includes/api/class-wc-api-products.php</b> on line <b>1093</b><br />
<br />
<b>Notice</b>:Trying to get property of non-object in <b>wp-content/plugins/woocommerce/includes/api/class-wc-api-products.php</b> on line <b>1094</b><br />
<br />
<b>Notice</b>:Trying to get property of non-object in <b>wp-content/plugins/woocommerce/includes/api/class-wc-api-products.php</b> on line <b>1096</b><br />
<br />
<b>Fatal error</b>:Call to a member function get_tax_status() on a non-object in <b>wp-content/plugins/woocommerce/includes/class-wc-product-variation.php</b> on line <b>397</b><br />
```

I guess I can see the error message because WP_DEBUG is TRUE, but still I think error messages are saying there is something wrong.

So I am now in the situation that I can't create the product with the given SKUs because I am not able to delete them.

Thank you for checking this issues.

**Comment by justinshreve** [comment]
How was the product and its variations deleted? The API or via wp-admin? Both use `wp_delete_post` which deletes postmeta.

**Comment by mikejolley** [comment]
^ that. Not sure how they were deleted by you have orphan meta. 

This should clear it up for you :) https://wordpress.org/plugins/wp-clean-up/
