### ISSUE TITLE
Return 10 porducts and users?

### ISSUE THREAD

**Issue by irfanwv** [woothemes/woocommerce#10636]
I want to return all list of products and users by Woocommerce rest API. But it return only 10 products and also same no. of users

**Comment by claudiosmweb** [comment]
Please read the REST API docs before open issues: https://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by irfanwv** [comment]
I have already read this doc and use all api's according to doc.

**Comment by claudiosmweb** [comment]
What you do not understand exactly?

> The total number of resources and pages are always included in the `X-WC-Total` and '`X-WC-TotalPages` HTTP headers.

How do you get HTTP headers from a request?
