### ISSUE TITLE
Custom order properties

### ISSUE THREAD

**Issue by zamoldar** [woothemes/woocommerce#10648]
is it posible to define some custom metada to the orders for rest api?

meta property
 order_type:
-online(default)
-dine-in
-delivery
-to_go
-catering

ie..

**Comment by mikejolley** [comment]
There are filters to add data. See https://github.com/woothemes/woocommerce/blob/cb0f70308643f9d6bcdc11928ae6eb90d3020028/includes/api/class-wc-api-orders.php#L335
