### ISSUE TITLE
Paypal - It is possible to create two orders with the same id and paying for the first one won't validate the order in woocommerce

### ISSUE THREAD

**Issue by yoancutillas** [woothemes/woocommerce#10640]
## EXPLANATION OF THE ISSUE

Wordpress: 4.4.2, Woocommerce : 2.5.5, theme : Twenty Sixteen, No other plugins. Tests made with paypal sandbox.

When you add product to your cart and then place an order with paypal, it opens a paypal window. Now if you go back to the website, modify the cart and place a new order, the order will keep its old id, but its content will change in woocommerce. As a result, if you pay the order in the first paypal window opened, the payment is validated by Paypal, but not in woocommerce. The payment is made but the paypal log file says : 

04-04-2016 @ 16:58:13 - Received valid response from PayPal
04-04-2016 @ 16:58:13 - Found order #124
04-04-2016 @ 16:58:13 - Payment status: completed
04-04-2016 @ 16:58:13 - Payment error: Amounts do not match (gross 105.00)

## STEPS TO REPRODUCE THE ISSUE

1. Add products to cart
2. Proceed to checkout
3. Select Paypal and proceed to Paypal
4. In a new window, go back to the store and add a new product to cart.
5. Proceed to checkout (notice in the back-end that the order has been updated)
6. Select Paypal and proceed to Paypal 
7. Go back to the first Paypal window and pay
8. There you got the error, woocommerce doesn't validate the order but Paypal has charged you.

I suggest to create a new order instead of updating the old one.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: ***
Site URL: ***
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.31
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
SUHOSIN Installed: ✔
MySQL Version: 5.6.23
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: par WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Base Boutique: #4 - /boutique/
Panier: #5 - /panier/
Commande: #6 - /commande/
Mon Compte: #7 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ✕ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This is already fixed and resolved in master/2.6 using order hashes.
