### ISSUE TITLE
Payment with PayPal - How does it work?

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10643]
Hello,
Customers order from my WC stores and pay with PayPal.
Everything works smoothly regarding payment.

My orders are not maintained at WC, I maintain them in a local data base.
Currently I copy data manually from PayPal to my data base.

I want to write a script to export data from PayPal to my data base.
Normally IPN is ideal for that however It's impossible to use one paypal account with multipule IPNs.

I decided that I want to write a script which I will run once a day and it will export data from PayPal to my database. However the [PayPalRestSDK ](https://github.com/paypal/PayPal-Python-SDK)  can only export payments which were paid with the Rest Api. meaning that it has to be with the Client ID and Secret ID of the Rest Api.

Currently, I'm stuck as I have no idea in what way WC process payment to paypal. 

Do you have any input on the matter?

**Comment by mikejolley** [comment]
This isn't the correct place for these types of support requests, but I'd recommend you look into both the WooCommerce API and our webhooks and transfer data from WC -> your DB rather than PayPal -> your DB.

**Comment by test101test101** [comment]
@mikejolley  it's ilogical to draw data from WC. I have one WC store and 4 other stores. All payments and orders are passed to paypal...

I am trying to understand why WC transactions appear in PayPal but does not appear in PayPal Rest API. This is a question for WC support which is here.

**Comment by mikejolley** [comment]
No it's not a question for WC support - PayPal Rest API is not something we maintain. 

> it's ilogical to draw data from WC. I have one WC store and 4 other stores. All payments and orders are passed to paypal...

How so? Orders are still stored in each WC store - you just need to look at completed ones?

> Currently, I'm stuck as I have no idea in what way WC process payment to paypal.

By all means look at the code to see how data is transferred https://github.com/woothemes/woocommerce/tree/master/includes/gateways/paypal WC sends the order details + amounts to PayPal which then handles all payment etc. What happens with that data is out of our hands.

**Comment by mikejolley** [comment]
And this is what this gateway uses https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/wp_standard_overview/

**Comment by test101test101** [comment]
@mikejolley  Only 1 of my stores is WC, So i'm not about to write different scripts for each one, Moreover the paypal transaction identifier is important to me and this information is not available in WC. 

I know what information is passed to PayPal. But the method is unclear.  PayPal supports Rest SDK, Soap SDK. Which one WC interated to its code?
This is no a question of what PayPal does with the data, this is a question of how WC connects to PayPal. Basicly PayPal allows serveral connections methods... a link to the one that WC implements will be usefull.

**Comment by mikejolley** [comment]
PayPal standard is NVP based https://developer.paypal.com/webapps/developer/docs/classic/products/#wps Doesn't use REST or SOAP.

> Moreover the paypal transaction identifier is important to me and this information is not available in WC.

yes it is, its stored to the order after IPN comes back.

**Comment by test101test101** [comment]
@mikejolley  can you refer me to the table names where order data is saved?

**Comment by BurlesonBrad** [comment]
Orders are stored in the post table, postmeta table, woocommerce_order_items, and woocommerce_order_itemmeta tables
https://docs.woothemes.com/wc-apidocs/

Lock and Limit and **Go Eat BBQ**  @mikejolley

**Comment by test101test101** [comment]
@BurlesonBrad The link that you specified shows classes not tables.
Where can I read about what each column means in each table?
