### ISSUE TITLE
Stock reduced to zero

### ISSUE THREAD

**Issue by chetansatasiya** [woothemes/woocommerce#10649]
@mikejolley , @claudiosmweb 

Hi Team,

I am a facing the issue after the update the 2.5.5 latest version of the plugin.

Now the issue is Suddenly all available products inventory stock reduced to zero. After adding new products this happened again with several products.

I hope you can resolve my issue ASAP.

Thanks in advance.

**Comment by mikejolley** [comment]
You missed a whole bunch of questions when submitting this issue.. Nor did you state what you updated from.

Updates don't change product data. If anything, its a plugin or data you've imported previously. Comment back with more details if you think its a bug, but as there are no other reports I don't see this being the case.

Thanks
