### ISSUE TITLE
Force translation Upgrade Button missing on v.2.5.5

### ISSUE THREAD

**Issue by shadyueh** [woothemes/woocommerce#10647]
I have the wordpress on my language and can't find woo commerce "Force Translations Upgrade" button that usually stays after "reset usage tracking settings". So, even it has translation for my language, seems I need translate it manually.
![missing_buttton](https://cloud.githubusercontent.com/assets/325680/14304194/dab15aee-fb7e-11e5-98b9-7db121b042dd.png)
Then I noticed something strange, when got the system status:
![missing_buttton2](https://cloud.githubusercontent.com/assets/325680/14304358/2ead2e06-fb80-11e5-9350-7d827a1b6f94.png)
By some reason it seems recognizing the language default as English  even it is set to pt BR? Or it's just the hint? Anyway, the button isn't there. Does this feature removed?

**Comment by mikejolley** [comment]
Yes its removed. Please have a read of https://docs.woothemes.com/document/woocommerce-localization/
