### ISSUE TITLE
Exclude Sale Items - Coupon Issue

### ISSUE THREAD

**Issue by AntBentinck** [woothemes/woocommerce#10646]
Running the latest version of WooCommerce 2.5.5 on 5th April 2016.

When running a store with products on sale it is normal for a customer to select a few sale items and then want to apply a coupon (Basket % Coupon) to take say 5-10% off other items in their cart that were not on sale.

Obviously we do not want to discount sale items even further otherwise it defeats the purpose of them being on sale so for that reason we select "Exclude Sale Items" in the coupon settings.

By doing this when the customer goes to their cart to apply the coupon it is instantly disallowed because there is a sale item in the cart. This dosent seem right. The customer should still receive the coupon basket % discount on the items not on sale.

**Comment by mikejolley** [comment]
Change the type from 'cart' percent coupon to 'product' percent coupon to do this.
