### ISSUE TITLE
question about wp_posts table.

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10656]
Why does it has `_shipping_address_1`,`_shipping_address_2` ,`_billing_address_1`,`_billing_address_2` ?

I'm writing a query which takes order information and export it from WC to other data base..
I don't understand why it has two fields? Where is the logic in having two shipping addresses?

Another question is, where does WC saves the payment date?
i see order date but this isn't payment date.. there could be a gap between them.

May I also point that the information here is very useful
https://woothemes.github.io/woocommerce-rest-api-docs/#orders
it could have been more useful if near each filed it would have also said in which table it is saved.

**Comment by mikejolley** [comment]
I'm sorry but that is 3 in a row now. When you submit a new issue it makes it clear this area is for bug reports - not general support. Please use the forums.

Create an order and look at the data in those fields (post meta and posts table for dates). It's not '2 addresses', its 2 address lines which is common place in eCommerce.

Closing and locking as this is not a valid ticket.
