### ISSUE TITLE
Fatal error: Call to a member function get_order() on a non-object in  /../wc-order-functions.php on line 58

### ISSUE THREAD

**Issue by custard-apple** [woothemes/woocommerce#10657]
I got the code from given link to create order but It's showing an error.

http://stackoverflow.com/questions/26581467/creating-woocommerce-order-with-line-item-programatically

**Comment by mikejolley** [comment]
We didn't provide that example so it may not be accurate. See the https://docs.woothemes.com/wc-apidocs/function-wc_create_order.html function.

This is not a support area for future reference; please use the forums.
