### ISSUE TITLE
fsockopen/cURL

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10650]
[PayPal standard plugin](https://docs.woothemes.com/document/paypal-standard/) says:

> PayPal Standard in WooCommerce core uses Instant Payment Notification (IPN) and has been updated with PayPal’s announcement to https for added security.
> 
> What Do You Do? Ensure that your host supports HTTPS connections through CURL/fsockopen using TLS 1.2 or newer certificates. Your system status page in WooCommerce will tell you if there are any problems connecting. Contact your host to fix that if needed.

When I look in system status page I have a V in CURL/fsockopen so according to this message it means it's ok.

However if I look at:
https://github.com/paypal/tls-update

and do thier check:
`php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));'`
It returns:
`bool(false)`

So it means that there is no support and I should upgrade the TLS to 1.2

So I don't know what is true... Do I need upgrades or not?
This is very confusing.

**Comment by mikejolley** [comment]
The check doesn't currently check TLS version on system status. It will in the next update, You'll need TLS 1.2 support for PayPal IPN to work going forward.

**Comment by test101test101** [comment]
@mikejolley  if that is the case the documentation in the plugin is extremely misleading...

**Comment by mikejolley** [comment]
How so? And where?

**Comment by test101test101** [comment]
@mikejolley 
As I said:
https://docs.woothemes.com/document/paypal-standard/

> Your system status page in WooCommerce will tell you if there are any problems connecting.

In my case it didn't tell there is a problem, so I could think eveything is ok.
You told me here that this MSG does not check for TLS 1.2 and therefor this MSG is misleading!
This whole MSG is about PayPal so the whole idea is to specific check for TLS 1.2

**Comment by mikejolley** [comment]
And I said this text/check was being updated in the next version.
