### ISSUE TITLE
Products on sale query bug (simple/variable products)

### ISSUE THREAD

**Issue by rbsmidt** [woothemes/woocommerce#10651]
I've discovered an unexpected result when fetching products on sale. I can reproduce the bug both with `wc_get_product_ids_on_sale()` and a custom query like this:

    $args = array(
        'post_type' => 'product',
        'posts_per_page' => -1,
        'meta_query' => array(
            'relation' => 'OR',
            array(
                'key' => '_sale_price',
                'value' => 0,
                'compare' => '>',
                'type' => 'numeric',
            ),
            array(
                'key' => '_min_variation_sale_price',
                'value' => 0,
                'compare' => '>',
                'type' => 'numeric'
            )
        )
    );

When running either of the above the result includes simple products, that has been saved as variable products and had a sale price defined earlier. Then later edited to be simple product without a sale price.
I've pinned down the issue to the `_min_variation_sale_price` in `wp_postmeta` db table. The meta_value is still set with a variation sale price after the product is edited, hence it returns true in the above queries. I've managed to work around this by including product_type as tax_query in the query, and only including the relevant meta_query. But this way i have to perform a query per product type and then merge the results afterwards.

I know that it's a minor bug, and that this way of editing a product provoking the issue happens rarely for e-commerce owners/users. However i still find the output unexpected thus reporting it here.

**Comment by mikejolley** [comment]
_min_variation_sale_price is no longer used; the values stored there are out of date. Please see the latest version of wc_get_product_ids_on_sale - it uses a WPDB query.
