### ISSUE TITLE
Custom attribute on checkout form gets lost when billing_state or shipping_state fields changes from select to input (or viceversa)

### ISSUE THREAD

**Issue by elvismdev** [woothemes/woocommerce#10658]
## EXPLANATION OF THE ISSUE

While adding a custom attribute (in my case an `ng-model` attribute) to the fields on the checkout form, noted that it get's lost when the `billing_state` or `shipping_state` field changes from a \<select> field type to a \<input> text type (or viceversa) when changing the country above.

Below my code in `functions.php` to add this custom attribute:

```php
add_filter( 'woocommerce_checkout_fields', 'add_field_custom_attr' );
function add_field_custom_attr( $fields ) {

		// Adding ng-model attribute to shipping fields.
		$fields['shipping']['shipping_first_name']['custom_attributes'] = array(
			'ng-model' => 'shipping_first_name'
			);
		$fields['shipping']['shipping_last_name']['custom_attributes'] = array(
			'ng-model' => 'shipping_last_name'
			);
		$fields['shipping']['shipping_company']['custom_attributes'] = array(
			'ng-model' => 'shipping_company'
			);
		$fields['shipping']['shipping_country']['custom_attributes'] = array(
			'ng-model' => 'shipping_country'
			);
		$fields['shipping']['shipping_address_1']['custom_attributes'] = array(
			'ng-model' => 'shipping_address_1'
			);
		$fields['shipping']['shipping_address_2']['custom_attributes'] = array(
			'ng-model' => 'shipping_address_2'
			);
		$fields['shipping']['shipping_city']['custom_attributes'] = array(
			'ng-model' => 'shipping_city'
			);
		$fields['shipping']['shipping_state']['custom_attributes'] = array(
			'ng-model' => 'shipping_state'
			);
		$fields['shipping']['shipping_postcode']['custom_attributes'] = array(
			'ng-model' => 'shipping_postcode'
			);

		// Adding ng-model attribute to billing fields.
		$fields['billing']['billing_first_name']['custom_attributes'] = array(
			'ng-model' => 'billing_first_name'
			);
		$fields['billing']['billing_last_name']['custom_attributes'] = array(
			'ng-model' => 'billing_last_name'
			);
		$fields['billing']['billing_company']['custom_attributes'] = array(
			'ng-model' => 'billing_company'
			);
		$fields['billing']['billing_country']['custom_attributes'] = array(
			'ng-model' => 'billing_country'
			);
		$fields['billing']['billing_address_1']['custom_attributes'] = array(
			'ng-model' => 'billing_address_1'
			);
		$fields['billing']['billing_address_2']['custom_attributes'] = array(
			'ng-model' => 'billing_address_2'
			);
		$fields['billing']['billing_city']['custom_attributes'] = array(
			'ng-model' => 'billing_city'
			);
		$fields['billing']['billing_state']['custom_attributes'] = array(
			'ng-model' => 'billing_state'
			);
		$fields['billing']['billing_postcode']['custom_attributes'] = array(
			'ng-model' => 'billing_postcode'
			);

	return $fields;

}
```

Is there a work around to keep the custom attribute on this field (input or select) when the field type changes? Or probably this might be an issue that must be enhanced for better handling when this field type dynamically changes to keep the custom attribute on it?

## STEPS TO REPRODUCE THE ISSUE

1 - Add the code above  to `functions.php` and define any kind of additional attribute you'll like to add to the form fields on the checkout form.

2 - Go to checkout and inspect the element with developer tools keeping the eye on the \<select> or \<input> field for `billing_state` or `shipping_state`. Change the country on the above dropdown from US to Uganda for example, this will change the `*_state` field from \<select> to \<input> and your added attribute via the `woocommerce_checkout_fields` filter will be lost.

![](http://i.imgur.com/WZIwC2Q.gif)

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://woocommerce-env.us-east-1.elasticbeanstalk.com
Site URL: http://woocommerce-env.us-east-1.elasticbeanstalk.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.17
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
When the checkout is updated based on country, the form is POSTed to the server. So just populate your custom fields 'value' if posted in your code.

**Comment by elvismdev** [comment]
Sorry @mikejolley  but is not too clear for me yet, how can I keep my custom attribute to persist on the `billing_state` and `shipping_state` fields when those are updated based on country? 

Regardless if it changes to `<input>` or `<select>` type fields, all I want is my custom attribute don't get lost from there when this field is updated because of the country. All the rest of the fields works as I need, `billing_state` and `shipping_state` are the only ones bugging me from this custom functionality I'm trying to accomplish.

**Comment by mikejolley** [comment]
Ok, so when you change country, the state box changes from select to input to hidden etc via this file:

https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/country-select.js#L104

This doesn't copy across all attributes - only the ones core uses. So I presume you'll need some JS on there to copy your model attribute.

**Comment by elvismdev** [comment]
Ok so there my point for reporting this as an issue that I think might need to be enhanced. 

Think about this, if have the possibility to add custom attributes (and another tweaks) via the [`woocommerce_checkout_fields`](https://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) filter, doesn't makes sense that [`country-select.js`](https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/country-select.js) shall be also capable to carry over this custom attributes I defined beforehand via the filter?

**Comment by mikejolley** [comment]
Possibly, however this could lead to other issues if said attribute was not supported by a certain input type.

If you want to submit a PR to copy those across cleanly, I'd be happy to review so long as it does not break other functionality.

**Comment by elvismdev** [comment]
Valid point as well, I'll see if I can work on something from my end and hopefully send a working PR.
