### ISSUE TITLE
Process Payment and redirect using POST on process_payment

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10653]
I have to submit the POST form rather than query args to redirect to the page of payment process.  I cannot supply query args for this npay gateway. For e.g this is the PHP implementation:

```
<form action="https://gateway.sandbox.npay.com.np/pay.aspx" method="post">
	<input type="hidden" value="CB47465D_C064_4020_96A0_9F0A2B8352A3" name="ProcessID">
	<input type="hidden" value="2001>" name="MerchantID">
	<input type="hidden" value="11240120979" name="MerchantTxnID">
	<input type="hidden" value="100.00" name="PayAmount">
	<input type="hidden" value="merchant_user_name" name="MerchantUsername">
	<input type="hidden" value="Payment for the month of Jan 2014" name="Description">
</form>
```

How can I redirect to the nPay site with above POST information :)

CC @claudiosmweb, @mikejolley

**Comment by mikejolley** [comment]
You need to redirect to the 'thanks' page, or another intermediate page, and have your form auto-post from there.

**Comment by shivapoudel** [comment]
Can you please link some reference for this type of gateway. Whole day I have look around and couldn't find any guidelines about.

**Comment by mikejolley** [comment]
Authorize.net DPM does it, and the 'old' version of paypal standard did. You need to output the form on a page AFTER checkout, and use javascript to submit it.
