### ISSUE TITLE
Why aren't address fields sanitized?

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#10659]
See https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L202. As far as I can tell there's no sanitation going on.

**Comment by mikejolley** [comment]
https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/meta.php#L167 and also by the classes which use the set function.

**Comment by EmilEriksen** [comment]
sanitize_meta() doesn't actually do any sanitation by itself. It just applies a filter to be used for sanitation and I don't think WooCommerce hooks into this filter anywhere? I was looking at WC_Checkout and it get's the address data [here](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L292-L307). [get_posted_address_data()](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L743-L756) gets the address from $posted and as far as I can tell the values in $posted aren't sanitized.
