### ISSUE TITLE
ZIP Code with 5 digits + 4 additional digits

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/woocommerce#10668]
When someone adds the extra 4 digits of a postal code, the defined shipping method doesn't trigger.

Standard postal code:
<img width="709" alt="screen shot 2016-04-11 at 10 23 21 am" src="https://cloud.githubusercontent.com/assets/2293077/14432478/fd97d4ca-ffcf-11e5-8067-2b51b7269aad.png">

With 4 additional characters:
<img width="732" alt="screen shot 2016-04-11 at 10 23 50 am" src="https://cloud.githubusercontent.com/assets/2293077/14432498/0ec51b90-ffd0-11e5-9c3a-d32fc5b1eab4.png">

**Comment by mikejolley** [comment]
It's down to the shipping method to account for this. If you want to support these, you'll need to expand the zip codes you've entered in local pickup settings.
