### ISSUE TITLE
WooCommerce wrongly requires postcode for Republic of Ireland

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#10663]
Hi,

Republic of Ireland do not require postcodes, so this should not be a required field for Ireland. In fact, it could be blanked out altogether as a lot of postal services (royal mail, DPD and others) do not allow a postcode at all when posting to ireland.

Thanks

**Comment by mikejolley** [comment]
@shawaj We read that Ireland introduced postcodes recently?

**Comment by shawaj** [comment]
There is a new system called Eircode (www.eircode.ie) but unfortunately most courier services (including Royal Mail) do not recognise these yet and a lot of customers from Ireland do not even know they exist (only came in under a year ago), so perhaps it should be optional at this point?

**Comment by shawaj** [comment]
Thanks Mike for fixing this. Are there ways to override the country and postcode options using filters? Or to add/remove/change country options?

Thanks

**Comment by mikejolley** [comment]
Yeah, look at the method I committed too. Its filterable.

**Comment by shawaj** [comment]
So we can add countries from functions.php that way too?

Just have a few countries we need to map to our couriers that don't exist in WC (they are not normal ones we ship to but keen to have the integration with our couriers working correctly).

Thanks again

**Comment by mikejolley** [comment]
https://docs.woothemes.com/document/add-a-new-country-to-countries-list/

**Comment by shawaj** [comment]
Thanks very much :-)

**Comment by shawaj** [comment]
Actually, just had a thought - what happens if we want to handle locale info, address formatting, postcode formatting, specific cities/postcodes/states within a country? Is it possible to to add all this stuff with one filter?

Will geolocation work on these added countries? 

And lastly where does WooCommerce get its country list from?

**Comment by shawaj** [comment]
Did this get reversed in later versions of WooCommerce so that ireland now requires a postcode again?
