### ISSUE TITLE
PUT /orders response is 404 instead of 405

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#10661]
WC Version 2.5.5
During an API workshop, I tried to create an order. What I used was

```
PUT /wc-api/v3/orders
```

And the response was a 404 not found. The correct would be

```
POST /wc-api/v3/orders
```

which worked.

However, the response for the PUT is a 404 Not Found. That one should be a 405 I think.

**Comment by claudiosmweb** [comment]
It depends, we return 404 since the route for your method could not be found.

WP-API returns the same, for example:

```json
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
```

So let's keep it this way, especially because we are now migrating to the WP-API.

**Comment by javorszky** [comment]
Hm, I still maintain that the route is there, it's just expecting a POST instead of a PUT.
