### ISSUE TITLE
Twenty Eleven Theme, sidebar on left, sidebar in the product display

### ISSUE THREAD

**Issue by d3adventures** [woothemes/woocommerce#10665]
## Twenty Eleven Theme, sidebar on left, sidebar in the product display

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE
WordPress 4.4.2 running Twenty Eleven theme.

1. View product (it's a free download so far)
https://d3adventures.com/product/extras-the-unique-shopkeeper/
2. The theme Twenty Eleven has the sidebar on the left.  This is how we want it.  See how the widgets and product page clash.

If I put the theme with the sidebar on the right, the sidebar goes under the product instead of next to it.  We chose Twenty Eleven theme because of it's built into the program.

Plugins Jetpack by WordPress.com	
Akismet
Custom 404 Pro
WooCommerce

All up to date
Same response in Google Chrome and Firefox.
Thank you for your assistance.

**Comment by d3adventures** [comment]
Hello James.  I'm just checking in.  I need to get going on this, one way or another.  Let me know if I can provide any further information

**Comment by jameskoster** [comment]
I'm looking into this now. The fix won't be available until the next release of WooCommerce though. If you're in urgent need of a theme, I highly recommend checking out [Storefront](https://wordpress.org/themes/storefront/).

**Comment by d3adventures** [comment]
Is it possible I can edit the file to make it workable with your information?


-------- Original Message --------
Subject: Re: [woothemes/woocommerce] Twenty Eleven Theme, sidebar on
left, sidebar in the product display (#10665)

**Comment by jameskoster** [comment]
Yup, copy woocommerce-layout.css and wrapper-end.php to your version of WooCommerce.
