### ISSUE TITLE
Application authorization problems on strictly configured hostings

### ISSUE THREAD

**Issue by briedis** [woothemes/woocommerce#10678]
We develop an app (Printful), and pretty often we get contacted with customers that have problems authorizing with our app.

And turns out that some hostings block requests that contain URLs within URLs.  This is not a Woo bug, rather than bad hosting configuration.

Requests get blocked because they contain callback urls in parameters.

For example: `http://some-domain.com/wc-auth/v1/login?app_name=OurApp&user_id=1&return_url=https%3A%2F%2Fwww.other-domain.com&callback_url=https%3A%2F%2Fwww.other-domain.com%2F%2Fcallback&scope=read_write`

This will get blocked on some hosting, for example, Hostgator.

## STEPS TO REPRODUCE THE ISSUE

You can see this blocking in action by simple visiting this stores URL hosted on Hostgator: `http://deanturnerart.com/wc-auth/v1/login?test=http://google.com`
Request gets 403 blocked.

## POSSIBLE SOLUTIONS

Optional parameter to pass callback URLs as base64 encoded. This would guarantee backward compatability. Drawbacks would be that the URLs get even longer due to base64 overhead. I know this is a hacky solution and the whole issue is just stupid, but we could save huge amount of time spent contacting with customers, their hostings, etc. 

Cheers,
Printful dev

**Comment by mikejolley** [comment]
http://forums.hostgator.com/mod-security-and-403-errors-t71394.html
http://stackoverflow.com/questions/14215419/mod-security-exception-rule-for-url-as-parameter
https://core.trac.wordpress.org/attachment/ticket/16940/16940.diff

The other alternative would be to leave our the http/https portion and add that back when used.

**Comment by briedis** [comment]
@mikejolley awesome!

I don't remember - the auth did not support non-secure connections, right? Because in the code I see you use only https.

**Comment by mikejolley** [comment]
@briedis The callback needs HTTPS. Return was flexible, but I feel if you want to take advantage of this you can have a secure return URL too :)

**Comment by briedis** [comment]
@mikejolley got it! Thanks for the quick fix! Looking forward to 2.6 :)
