### ISSUE TITLE
Error: Missing parameter app_name

### ISSUE THREAD

**Issue by mirabaiapplegate** [woothemes/woocommerce#10673]
## EXPLANATION OF THE ISSUE

Our authentication process works for all users except this one. Newest version of Woo being used. 
Why is the app_name not being recognized in this case?

## STEPS TO REPRODUCE THE ISSUE

1. Click this: http://piercefootwear.com/wc-auth/v1/authorize?app_name=Shippo&scope=read_write&user_id=undefined6a91751c7http%3A%2F%2Fpiercefootwear.com6a91751c7Pierce%20Footwear&return_url=https://goshippo.com/woocommerce/return/&callback_url=https://goshippo.com/woocommerce/callback/

## SYSTEM STATUS REPORT

The user reported that no errors were shown here. I don't have access to the user's account.

**Comment by claudiosmweb** [comment]
I tried to reproduce the error in a test environment and works fine.
Check if you are caching this page using varnish or in the FastCGI in Nginx. But not an issue on WooCommerce core.

**Comment by dheerajsingla** [comment]
Hi

On of our customer is facing the issue "Error: Missing parameter app_name" on the link. (wordpress 4.5.3, woocommerce 2.6.4)

https://golosiy.com/wc-auth/v1/authorize?app_name=orangetwig&scope=read_write&user_id=AAAiOAv&return_url=https://orangetwig.com/platforms/woocommerce/returnurl?domain=https://golosiy.com&callback_url=https://orangetwig.com/platforms/woocommerce/accessCallback?data={"email":"test@test.com","domain":"https://golosiy.com","referCode":"orangetwig"}

Can somebody check?

**Comment by penmetsa55** [comment]
I also got this Missing parameter app_name error. Issue is NGINX server configuration was not proper. NGINX server ignoring the parameters. 

After added the $args to index.php solved the issue like below.

location / {
    try_files $uri /index.php$args;
}
