### ISSUE TITLE
Faster checkouts?

### ISSUE THREAD

**Issue by rahilwazir** [woothemes/woocommerce#10680]
Does WooCommerce 2.5x currently supports storing CC tokens for faster checkout? Or do I have to wait for [2.6 milestone](https://github.com/woothemes/woocommerce/pull/10260)?

**Comment by shivapoudel** [comment]
@rahilwazir Payment Token API is now part of WooCommerce 2.6 shipping in May.

**Comment by rahilwazir** [comment]
@shivapoudel So it means WC 2.5x don't have the API and it has no support for faster checkout?

**Comment by shivapoudel** [comment]
Yep, WC 2.5.x will not index Payment Token API as its the part of WC 2.6 :)
