### ISSUE TITLE
Product Price Warning

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#10691]
When entering a product price there's a red notice that provides details on what to enter in the field. It works fine, but when you enter a value that needs a combination of key (for example to enter the euro symbol you need to press two keys on an AZERTY keyboard), then the notice is briefly shown and disappears too quickly as you can see in the animation below. For $ it works fine because it's just one key:

![](http://cld.wthms.co/1gaSX/3qOrJrOZ+)

**Comment by mikejolley** [comment]
@corsonr these are price inputs - only numeric values are allowed FYI, not even $.

**Comment by corsonr** [comment]
Yes I know @mikejolley ;-) it's just that *if* someone enter another non numeric value that needs to keys the message doesn't show enough time
