### ISSUE TITLE
Shop Page Display: show categories & subcategories setting only displaying parent categories and not subcatoegories

### ISSUE THREAD

**Issue by stuartduff** [woothemes/woocommerce#10699]
## EXPLANATION OF THE ISSUE

When the Show categories & subcategories is selected on the Shop Page Display setting only the parent categories display when subcats are present and populated with products.

I have tested this with v2.5.5 and various themes activated like Twenty Twelve, Twenty Sixteen etc.

Screenshot: http://cld.wthms.co/11Q7R/3Rx6CfEk

## STEPS TO REPRODUCE THE ISSUE

1. Change the Shop Page Display setting

**Comment by mikejolley** [comment]
@stuartduff This is how it should be. It shows the first level, then when you click one it shows the next level and so on.

How can this be worded better?
