### ISSUE TITLE
Change cart item thumbnail link hook

### ISSUE THREAD

**Issue by radykal** [woothemes/woocommerce#10690]
Hi,

it would be nice if you can add a filter hook for the cart item thumbnail link. Currently its possible to hook into the image source, but not in the link. Current code in cart.php:

``` php
<td class="product-thumbnail">
	<?php
		$thumbnail = apply_filters( 'woocommerce_cart_item_thumbnail', $_product->get_image(), $cart_item, $cart_item_key );

		if ( ! $_product->is_visible() ) {
			echo $thumbnail;
		} else {
			printf( '<a href="%s">%s</a>', esc_url( $_product->get_permalink( $cart_item ) ), $thumbnail );
		}
	?>
</td>
```

Something like this:

``` php
<td class="product-thumbnail">
	<?php
		$thumbnail = apply_filters( 'woocommerce_cart_item_thumbnail', $_product->get_image(), $cart_item, $cart_item_key );

		if ( ! $_product->is_visible() ) {
			echo $thumbnail;
		} else {
            $thumbnail_url = apply_filters( 'woocommerce_cart_item_thumbnail_link', esc_url( $_product->get_permalink( $cart_item ) ), $cart_item, $cart_item_key );
			printf( '<a href="%s">%s</a>', $thumbnail_url , $thumbnail );
		}
	?>
</td>
```

**Comment by mikejolley** [comment]
For what purpose? Why not filter the permalink if on the cart page instead?

**Comment by radykal** [comment]
Yes thats possible to use the standard wp filter like `post_type_link`. But in this filter hook I can not access the $cart_item and $cart_item_key variable like you provide in the woocommerce filter hooks.

**Comment by mikejolley** [comment]
So what is the use case?

**Comment by radykal** [comment]
I am already resetting the product name link, thats possible via `woocommerce_cart_item_name` filter. In this filter I can access the unique cart item key which will be appended at the end of the product url.

My plugin is loading some custom data in the product page from the session if the cart item key is added as URL parameter. Some users click on the product thumbnail in cart to return to the product page, but then the custom data from the session is not loaded. Thats why I need the filter hook for the cart item thumbnail link.

I hope you understand what I mean.

**Comment by radykal** [comment]
Thanks dude
