### ISSUE TITLE
WC-API attribute-value not assigned to variation if it is attribute is of type selectbox and if the value already exist

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10698]
Let's say I have an attribute color which is of type selectbox and has some predefined values.
![image](https://cloud.githubusercontent.com/assets/9553253/14530713/72f6e83c-025a-11e6-97f2-a79538c0c79c.png)

Now I'd like to create two variations of a product. The variation should be defined by the attribute attr_var_mattress_hardness. One variation should be created with an existing attribute-value ("hart") the other one should get a new one ("somethingnew")

     $np = array(
			'products' => array(
				array(
					'title' => 'mytest'.time(),
					'sku' => time(),
					'type' => 'variable',
					'attributes' => array(
						array(
							'name' => 'Härtegrad',
							'slug' => 'attr_var_mattress_hardness',
							'visible' => true,
							'variation' => true,
							'options' => array(
								'weich', 'hart', 'mittel'
							)
						)
					),
					'variations' => array(
						array(
							'sku' => 'VA'.time(),
							'attributes' => array(
								array(
									'slug' => 'attr_var_mattress_hardness',
									'option' => 'hart'
								)
							)
						),
						array(
							'sku' => 'VB'.time(),
							'attributes' => array(
								array(
									'slug' => 'attr_var_mattress_hardness',
									'option' => 'somethingnew'
								)
							)
						)
					)
				)
			)
		);

Expectation:
Two variations. One pre-selected with "hart" and the other one pre-selected with "somethingnew"

Reality:
Two variations. One pre-selected with "somethingnew" the other one is not pre-selected. Insted the default option ("Every Härtegrad") is selected.

![image](https://cloud.githubusercontent.com/assets/9553253/14530892/48c4a2ce-025b-11e6-808c-90c4325cad0d.png)

**Comment by ad-on-is** [comment]
Solved! I found out that I had to use the terms-slug in the option-field, not it's name.

    array(
        'sku' => 'VB'.time(),
        'attributes' => array(
            array(
                'slug' => 'attr_var_mattress_hardness',
                'option' => 'attr_var_mattress_hardness_hard'
             )
         )
    )

**Comment by mikejolley** [comment]
👍
