### ISSUE TITLE
SPRINTF Error on Cart Page - Portuguese Language

### ISSUE THREAD

**Issue by haxkep** [woothemes/woocommerce#10702]
When we have a WordPress installation in Portuguese (Portugal), the Cart page displays the following error:

_WARNING: SPRINTF(): TOO FEW ARGUMENTS IN /WP-CONTENT/PLUGINS/WOOCOMMERCE/INCLUDES/WC-CART-FUNCTIONS.PHP ON LINE 265_

I've read this is an issue with the translations, but we didn't change anything on the code, if I change to English, everything works as expected.

This problem shows up on the Total cart price.

**Comment by mikejolley** [comment]
There will be missing `%s` in the string on https://translate.wordpress.org/projects/wp-plugins/woocommerce - can you contribute there? I don't want to attempt this since I don't speak Portuguese :)

The string: https://github.com/woothemes/woocommerce/blob/2.5.5/includes/wc-cart-functions.php#L265

**Comment by haxkep** [comment]
Went there, but seems someone fixed already. Thanks, next time I'll go straight there.
