### ISSUE TITLE
Sorting and Filtering not working in V3 for products

### ISSUE THREAD

**Issue by ipragmatechadmin** [woothemes/woocommerce#10703]
## EXPLANATION OF THE ISSUE

We are using WooCommerce 2.5.5 and Filter parameter is not working in v3. We try to sort the list using filter[orderby]=name and filter[order]=desc but it's not working.

## STEPS TO REPRODUCE THE ISSUE

1. Make a call to products with filter parameters and finalize URL
 http://xyz.com/wc-api/v3/products?filter%255Border%255D=ASC&filter%255Borderby%255D=name&oauth_consumer_key=ck_c8e73e7a7b449a531a835a033e2d9a8f24387ff8&oauth_nonce=2.7919134414106183E7&oauth_signature=vJFg9kAeqbQZCG8OCzXSx8SdQUQ%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1460720211
2. No changes in the list

**Comment by mikejolley** [comment]
Looks like an encoding issue - I'm testing it using this URL and it definitely changes sort order.

https://dl.dropboxusercontent.com/s/328w45agsbr7m9v/2016-04-18%20at%2015.25.png?dl=0
