### ISSUE TITLE
Hook to alter product variation title

### ISSUE THREAD

**Issue by Muffinman** [woothemes/woocommerce#10709]
Hi,

I'm wondering if it would be possible get a hook added into the code which saves the product variation title? At the moment this is hard coded to save variations with the title `Variation #12345 of Product X`.

https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L1305

For my use case I've set up each product variation to have their own pages and templates (so that Google Shopping can link back to the product variations correctly). I've got this all working but the product pages look messy with this title structure (and of course my Google feed would be a little odd with these titles in).

I'd much prefer something like `Product X - Large - Blue` but at the moment there seems to be no facility to do this other than rewriting the variation titles manually after being saved to the DB.

**Comment by mikejolley** [comment]
Since you'll need to add a function anyway why can't you use the action calls a few lines down from where you linked?

**Comment by Muffinman** [comment]
It just seems messy to have to rewrite the product details right after it gets written to the DB.

**Comment by mikejolley** [comment]
For now that will suffice. We're revamping these classes in 2.7 (implementing a CRUD system) so rather than introduce 4x filters now in this class, API, CLI and anywhere else, lets leave it as is. When CRUD is implemented there will be a filter before save from all APIs.
