### ISSUE TITLE
Categories dissapeared

### ISSUE THREAD

**Issue by Xoanlc** [woothemes/woocommerce#10700]
## EXPLANATION OF THE ISSUE

The categories dissapeared. When I go to to Products/categories only 2 categories appears. But under the box "search categories" appears 41 ítems and 2 pages. But This categories are not show.

I was checking in the phpmyadmin and I can see there all the categories, only 3 of them were removed (I don´t know why) and were the parents. And other 2 parents are the only ones that I can see.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.
Go to : products/categories

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://subandcast.es
Site URL: http://subandcast.es
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.34
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
SUHOSIN Installed: –
MySQL Version: 5.1.73
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicar remoto: ✔
Obtén remoto: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (26) ###

Redux Framework: por Team Redux – 3.5.9
4k Icons for Visual Composer - Free: por Benjamin Intal
Gambit – 1.0

LayerSlider WP: por Kreatura Media – 5.5.1
Advanced Custom Fields: por Elliot Condon – 4.4.7
Advanced Sidebar Menu: por Mat Lipe – 5.1.4
CommerceGurus Toolkit: por CommerceGurus – 1.2.8
Contact Form 7: por Takayuki Miyoshi – 4.4.1
Envato WordPress Toolkit: por Envato – 1.7.3
Envato WordPress Toolkit: por Envato – 1.7.3
WPBakery Visual Composer: por Michael M - WPBakery.com – 4.11.2
MailChimp para WordPress: por ibericode – 3.1.6
MailChimp: por MailChimp and Crowd Favorite – 1.4.5
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
WooCommerce Table Rate Shipping by Mangohour: por mangohour – 1.2.1
Social Media and Share Icons (Ultimate Social Media): por UltimatelySocial – 1.4.7
W3 Total Cache: por Frederick Townes – 0.9.4.1
WooCommerce - Store Exporter: por Visser Labs – 1.8.6
WooCommerce Quantity Increment: por WooThemes
Bryce Adams – 1.0.0

WooCommerce Social Media Share Buttons: por Toastie Studio – 1.3.0
WooCommerce: por WooThemes – 2.5.5
WooSidebars: por WooThemes – 1.4.3
Yoast SEO: por Equipo Yoast – 3.1.2
WP Retina 2x: por Jordy Meow – 4.4.4
YITH WooCommerce Ajax Product Filter: por YITHEMES – 2.8.1
YITH WooCommerce Ajax Search: por Yithemes – 1.3.9
YITH WooCommerce Wishlist: por YITHEMES – 2.0.15

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Base de la tienda: #66191 - /shop-2/
Carrito: #7 - /cart/
Finalizar compra: #8 - /checkout/
Mi cuenta: #9 - /my-account/

### Taxonomies ###

Product Types: simple (simple)
variable (variable)


### Theme ###

Name: Adrenalin
Version: 1.9.3
Author URL: http://www.commercegurus.com
Child Theme: ✕ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: adrenalin/woocommerce/archive-product.php
adrenalin/woocommerce/cart/cart.php
adrenalin/woocommerce/checkout/form-checkout.php
adrenalin/woocommerce/checkout/review-order.php
adrenalin/woocommerce/checkout/thankyou.php
adrenalin/woocommerce/content-product.php
adrenalin/woocommerce/content-product_cat.php
adrenalin/woocommerce/content-single-product.php
adrenalin/woocommerce/global/wrapper-end.php
adrenalin/woocommerce/global/wrapper-start.php
adrenalin/woocommerce/loop/loop-end.php
adrenalin/woocommerce/loop/loop-start.php
adrenalin/woocommerce/loop/orderby.php
adrenalin/woocommerce/loop/pagination.php
adrenalin/woocommerce/loop/result-count.php
adrenalin/woocommerce/loop/sale-flash.php
adrenalin/woocommerce/single-product/meta.php
adrenalin/woocommerce/single-product/price.php
adrenalin/woocommerce/single-product/product-image.php
adrenalin/woocommerce/single-product/product-thumbnails.php
adrenalin/woocommerce/single-product/related.php
adrenalin/woocommerce/single-product/sale-flash.php
adrenalin/woocommerce/single-product/share.php
adrenalin/woocommerce/single-product/tabs/tabs.php
adrenalin/woocommerce/single-product/up-sells.php
adrenalin/woocommerce/single-product-reviews.php
adrenalin/woocommerce/single-product.php

````

**Comment by mikejolley** [comment]
As stated in the new issue submission form, you need to rule out conflicts with themes + plugin before submitting a bug report. As I don't have the issue myself it would be near impossible to debug.

If after doing that it doesn't resolve, comment back. It might be missing term meta data.

**Comment by Xoanlc** [comment]
I tried that and still not working. I have a similar web (the same in other language and Works perfectly) and it´s not problem with plugins or theme.

In the categories page said that there are 41 ítems, but don´t show it. And in the database (phpmyadmin) I can see most of the categories, but in woocommerce cant see them. Even when i see in products I can see them, and in the sidebar I can see the categories. But don´t in the options

I don´t know how can I solve it.

**Comment by mikejolley** [comment]
Did you check for the existence of the woocommerce_term_meta table and seen if it has entries?

**Comment by Xoanlc** [comment]
Hi!
Yes, wp_woocommerce_termmeta exists and has entries

**Comment by mikejolley** [comment]
I think its missing data. Can you add a few new ones and drag/drop to sort them? See if the rest appear then.

**Comment by Xoanlc** [comment]
How could i do it? i don´t understand.

Create a new categories? I created new categories and they appear. And even in the database I can see the old ones. But hte old ones never appear in woocommerce

**Comment by mikejolley** [comment]
In admin, drag and drop to sort the new ones which have appeared.

**Comment by Xoanlc** [comment]
The new categories appears in wp_terms

I don´t understand what you mean when you say drag/drop. From where and to where'

Sorry, my english is not very good

**Comment by mikejolley** [comment]
Products > Categories. The list of categories is sortable.

**Comment by Xoanlc** [comment]
Yes, but in this list do not appear the categories. Attached is an image
![imagen-categorias](https://cloud.githubusercontent.com/assets/18469505/14610104/56580378-0584-11e6-8252-60dab5e30c68.jpg)

**Comment by mikejolley** [comment]
What I'm saying is, sort those 3. It should trigger an update on the hidden ones too.

**Comment by Xoanlc** [comment]
Ahh OK, understood! But no, nothing happens. I created new ones, drag and drop... but nothing changed. Still say that there are 41 categories but don´t show them.

When I edit a prodcut, there I can see the categories. But Three of them semm dissapeared (in the database too) and were the parents of the other ones. 
![imagen-categorias](https://cloud.githubusercontent.com/assets/18469505/14611186/e20cd6ec-0588-11e6-9299-13cb33d48181.jpg)

**Comment by mikejolley** [comment]
Last thing; if on the page where you drag dropped, if you sort by slug, do they display?

**Comment by Xoanlc** [comment]
Ohh!! Appeared! There are 3 missed but the other ones has appeared!

Thank you very much!

What do you think what happened?

I will créate the lost ones and order them again. But it´s not too much work compared if I had to créate all the categories and put them again in the products

**Comment by Xoanlc** [comment]
Hi! i´m having more problems with that. Now I can see the categories. I created ones that were removed. But In the shop (in the page shop where must be all the categories) only show 3 categories, not the 5 I have. In the left sidebar you can see them.
