### ISSUE TITLE
Free Shipping Incorrect

### ISSUE THREAD

**Issue by leesimple** [woothemes/woocommerce#10711]
## EXPLANATION OF THE ISSUE

Free shipping coupon set to $100 minimum spend is including the tax as the total spend.

## STEPS TO REPRODUCE THE ISSUE

1 - Create coupon for Free Shipping if spend is $100 

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://alpha.leesfavorites.com
Site URL: http://alpha.leesfavorites.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.3.29 - We recommend a minimum PHP version of 5.4. See: How to update your PHP version
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.45
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (8) ###

LayerSlider WP: by Kreatura Media – 5.6.2
Fusion Core: by ThemeFusion – 1.8.4
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Slider Revolution: by ThemePunch – 5.1.6
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
INC – 1.7.17

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.5.22

WooCommerce Profit of Sales Report: by IndoWebKreasi – 1.2.1
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #6 - /
Cart: #7 - /index.php/cart/
Checkout: #8 - /index.php/checkout/
My Account: #9 - /index.php/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Avada
Version: 3.9.4
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/content-product.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/myaccount/form-edit-address.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php
Avada/woocommerce/single-product-reviews.php
```

**Comment by mikejolley** [comment]
If prices include tax then thats correct.. As a customer, even if its tax its still part of your 'spend'.

**Comment by leesimple** [comment]
That would, indeed, make sense if our prices included tax.  However, ours do not.

**Comment by mikejolley** [comment]
How are you setup then?

Code is here https://github.com/woothemes/woocommerce/blob/master/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L115-L118

Prices inc tax uses cart contents total + taxes.

Prices ex tax uses cart contents total only.

**Comment by leesimple** [comment]
We are set to prices exclusive of tax and to display all items without tax.  Tax is calculated in the cart only.

**Comment by mikejolley** [comment]
Actually I think in this case I'm going to tweak the coupon logic (what you're referring to) and the free shipping class logic (what I was referring to) to include item taxes. The subtotal should be considered the spend - i.e the amount being handed over for the goods.

I'll see if this can be filterable for the edge cases, but there will be arguments for both sides.

**Comment by n9yty** [comment]
@mikejolley It seems no work was ever done on this to add a filter. It does seem odd that a setting as to how things are displayed to the user should affect how things are calculated behind the scenes.

Might it work to filter it here:
https://github.com/woothemes/woocommerce/blob/master/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L154-156

And maybe here:
https://github.com/woothemes/woocommerce/blob/master/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L202

So that the filter could determine whether or not tax was to be included in the value for shipping? I haven't looked at this in-depth, but trying to see if this can be raised and addressed however it needs to be done. In our case, we are using the base free shipping methods and also using table rate shipping plugin, which does calculate using taxes, and the two are coming up with different values for the basis of their rate calculation, and we don't want to change the display of line items to include taxes.
