### ISSUE TITLE
Digital product won't download

### ISSUE THREAD

**Issue by Steven-Peterson** [woothemes/woocommerce#10717]
Sir:
I have a digital product that used to work well but now will not open properly (or not at all) from the email "Order complete--download your files". 
However from the settings info (below), one of the lines state:
My Account: Page does not contain the shortcode: [woocommerce_my_account]
### WordPress Environment ###
This may be the problem? I have tried resetting the woocommerce plug in but doesn't help. What else can I do? 
Thanks, 
Steven

Home URL: http://www.esconsultantonline.com
Site URL: http://www.esconsultantonline.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.43
PHP Post Max Size: 50 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (12) ###

All In One SEO Pack: by Michael Torbert – 2.3.4
BackUpWordPress: by Human Made Limited – 3.6.0
Formidable: by Strategy11 – 2.0.25
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3
Google AdSense: by Google – 1.2.1
Hello Dolly: by Matt Mullenweg – 1.6
Jetpack by WordPress.com: by Automattic – 3.9.6
NextGEN Facebook (NGFB): by JS Morisset – 8.29.5-1
Theme Check: by Otto42
pross – 20151211.1

WooCommerce: by WooThemes – 2.5.5
WordPress Importer: by wordpressdotorg – 0.6.1
Storeya Products Feed for WP e-Commerce: by StoreYa – 1.0

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #147 - /?page_id=147
Cart: #149 - /?page_id=149
Checkout: #151 - /?page_id=151
My Account: Page does not contain the shortcode: [woocommerce_my_account]

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Three
Version: 1.3.7
Author URL: http://firegoby.jp/
Child Theme: ✔
Parent Theme Name: Twenty Thirteen
Parent Theme Version: 1.9
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
PLEASE NOTE:
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

And before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
-->

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
You need to set the correct page in https://dl.dropboxusercontent.com/s/kai5r6bxiivyoyj/2016-04-18%20at%2010.49.png?dl=0

As for download links, use the account page links. Email links may expire if a product is ever edited.
