### ISSUE TITLE
[API] Reports

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#10710]
I'm building an iOS / Windows app that is integrated with WooCommerce. 

Is it possible to retrieve **Sales by product & Sales by category** reports via the REST API v3? I have tried the sales by date and top sellers and it works fine but I'm not sure if there is a filter for product and category based reports. I could not find it in the documentation either. 

I'm using the latest version of WooCommerce. Is this something that's being worked on for future versions?

**Comment by mikejolley** [comment]
Available reports are covered in https://woothemes.github.io/woocommerce-rest-api-docs/#reports so the answer is not currently.

**Comment by amjad0** [comment]
@mikejolley Will this ever be implemented?
