### ISSUE TITLE
Incorrect taxes calculation in cart page

### ISSUE THREAD

**Issue by Aerendir** [woothemes/woocommerce#10715]
If I set a product with price of 1,00 Euro, the tax amount calculated is of 0,18 Euro (a tax rate of 18% is applied) while I have set a tax rate amount of 22% (for Italy).

These are the screenshots:

![schermata 2016-04-17 alle 11 51 29](https://cloud.githubusercontent.com/assets/1968622/14586258/d12d5320-0492-11e6-8231-97f2ae956365.png)
![schermata 2016-04-17 alle 11 51 04](https://cloud.githubusercontent.com/assets/1968622/14586259/d1346dae-0492-11e6-8740-1066da061fdb.png)

This is my configuration of taxes:

![schermata 2016-04-17 alle 11 49 57](https://cloud.githubusercontent.com/assets/1968622/14586252/9b5aac2a-0492-11e6-81cc-7f1f9b072ddb.png)
![schermata 2016-04-17 alle 11 50 10](https://cloud.githubusercontent.com/assets/1968622/14586253/9b60a74c-0492-11e6-8c29-86de19c86b72.png)

Is a fault of mine or not?

I think there is something wrong with calculations as the tax rate is simply ignored and I don't understand from where this tax rate comes.

**Comment by mikejolley** [comment]
Your prices include tax. See https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

**Comment by Aerendir** [comment]
Hi @mikejolley , I've undesrtood how taxes work on WooCommerce.
But I'm pointing out a bug in the calculations.

The problem is that if I set the prices to be set as "tax incl." and set to show in the checkout the amount of taxes applied, this amount is calculated with a tax rate of 18% (EVER of 18%).

This is a wrong behavior, like the use case should be this:

1) The merchant sets the prices as tax included (say 1.00 Euro);
2) The merchant set the checkout to show the amount of taxes applied: so (s)he sets the tax rate in taxes (I set the italian tax rate of 22%);
3) In the checkout, WooCommerce should take the price taxes included (1.00 Euro) and calculate the amount of taxes applied (100[the price taxes included] - 100[the price taxes included]/0.22[the tax rate set in taxes]).

This is the correct behavior.

In this moment, instead, WooCommerce applies a default tax rate of 18% and this is a wrong behavior.

As you can see from the screenshots, also the the review page (the one shown after order is completed) shows a string like "Totale: 1,00 Euro (include 0,18 Euro IVA IT).

Translated: "Total: 1,00 Eur (includes 0,18 Euro IVA IT).

Now, "IVA IT" is the tax I set in tax rates but WooCommerce takes the name of the tax but not applies correctly the tax rate set (that is 22%).

The correct string should be: "Total: 1,00 Eur (includes 0,22 Euro IVA IT)" (0,22 EURO IS THE CORRECT AMOUNT OF TAXES APPLIED AND THEY ARE SET IN THE PRICE BY THE MERCHANT WHEN THE PRODUCT'S PRICE IS SET).

I hope now is more clear where the bug is. If not, please tell me and I'll try to be more clear...

Thank you for your reply! :)

**Comment by mikejolley** [comment]
**Thanks for all the bold but you're wrong :)**

The price already includes tax.

1 EUR excluding tax would mean you get 1 * 0.22 = .22 tax.

1 EUR already including tax would give you 1 - ( 1 / 1.22 ) = 0.18 tax.

**Read the doc again.** If you do 1 * 0.22 on a tax inclusive price, you're taxing the tax which is wrong.

**Comment by Aerendir** [comment]
Sorry... You are right... -.-'

**Comment by Aerendir** [comment]
Yes, you are right -.-' Excuse me :)
