### ISSUE TITLE
Register all guests as Users

### ISSUE THREAD

**Issue by aneeshjajodia** [woothemes/woocommerce#10712]
Hello there,

I have been using WC for a long while now since i've started my ecommerce website. I have a doubt, rather an issue which i've been facing and looking forward for someone in this community (after many attempts) to help me through this.

Okay, so basically, i've opted for the payment gateway by amazon in my country, where in the their payment gateway allows the complete checkout and shipping from their end.

So, every user is checking out to their website, and so all the details pulled are going as guest at my wc end. Since it is going as guest, my users are not getting the mails from my end, and the customer number isn't increasing since they aren't getting registered.
<img width="545" alt="capture" src="https://cloud.githubusercontent.com/assets/1062704/14579974/db926d6c-03db-11e6-9af8-300bfc270f65.PNG">

I would request someone to help me figure out the way to allow every user to get registered at my end as well, also the existing ones.

Expecting a prompt reply.

**Comment by mikejolley** [comment]
You can disable guest checkout in Settings > Checkout.

**Comment by aneeshjajodia** [comment]
I don't want to disable. I want every user as a guest to get registered to the website. 

Aneesh Jajodia.

**Comment by mikejolley** [comment]
If it's disabled, and registration is forced (again in settings), that will happen.

**Comment by aneeshjajodia** [comment]
Even if we do it from backend?

Aneesh Jajodia.
