### ISSUE TITLE
Store Options Stopped Working

### ISSUE THREAD

**Issue by mulligan101** [woothemes/woocommerce#10728]
## EXPLANATION OF THE ISSUE

2.5.5 version.
I recently updated to 4.5 (last night) and I woke up today with messages from potential customers saying my store isn't working.

I can choose an item and then choose a quantity but when I click "add to cart" and then it says "Please choose product options…" No matter what I choose and what option it says to choose an option and my cart is empty =(

Please try for yourself, http://www.charitycollective.org
Any help is appreciated!
Thanks guys!

## STEPS TO REPRODUCE THE ISSUE
goto www.charitycollective.org
click shop here or place an order. 
Click any item in the menu.
Click any option for quantity and then click checkout.
It will say you still need to pick and option (quantity)

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://charitycollective.org/store
Site URL: http://charitycollective.org/store
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.17
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (6) ###

ShareThis: by The ShareThis Team – 7.4
Theme My Login: by Jeff Farthing – 6.4.4
Woocommerce Poor Guys Swiss Knife: by Uli Hake – 2.2.4
WooCommerce: by WooThemes – 2.5.5
Yoast SEO: by Team Yoast – 3.1.2
WP User Registration: by 偶爱偶家 – 2.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #45 - /shop/
Cart: #46 - /cart/
Checkout: #47 - /checkout/
My Account: #48 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Enfold
Version: 3.0.4
Author URL: http://www.kriesi.at
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by BurlesonBrad** [comment]
crazy idea: try updating :+1:
 ![high-on-themes](https://cloud.githubusercontent.com/assets/6208757/14628894/ac9d8b8e-05c7-11e6-803d-c8b5acb76cbe.png)
#### Git is for bugs, not outdated & non updated themes.
Lock & Limit? @claudiosmweb

**Comment by mulligan101** [comment]
I updated and it still is a problem.

On Mon, Apr 18, 2016 at 10:47 PM, Brad Griffin <notifications@github.com>
wrote:

> crazy idea: try updating [image: :+1:]
> [image: high-on-themes]
> <https://cloud.githubusercontent.com/assets/6208757/14628894/ac9d8b8e-05c7-11e6-803d-c8b5acb76cbe.png>
> Git is for bugs, not outdated & non updated themes.
>
> Lock & Limit? @claudiosmweb <https://github.com/claudiosmweb>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/10728#issuecomment-211739496>
>



-- 
-Rob M. aka Mulligan
213-278-8103
www.Mulligan3.com
www.CapacityProductions.com
The information contained in this email may be privileged, confidential,
exempt from disclosure under applicable law, and intended solely for the
use of the individual or entity named above. If the reader of the message
is not the intended recipient, or the agent responsible for delivery to the
intended recipient, you are hereby notified that any dissemination,
distribution, or copying of the message is strictly prohibited.
Unauthorized or improper use of this information may subject the reader to
prosecution to the fullest extent of the law. If you have received this
communication in error, please notify the sender immediately and destroy
the material in its entirety, whether electronic or hard copy. Because
Internet e-mail and attachments can be altered electronically, the
integrity of this communication cannot be guaranteed.

**Comment by mulligan101** [comment]
I got it to work!
