### ISSUE TITLE
Make shop order post statuses filterable during registration

### ISSUE THREAD

**Issue by unfulvio** [woothemes/woocommerce#10738]
In class-wc-post-types.php while registering post types and taxonomies many core elements are filterable, however [shop order post statuses are not](https://github.com/woothemes/woocommerce/blob/release/2.5/includes/class-wc-post-types.php#L425-L480). (There's a tiny bit of code repetition too).

I ran in a problem while working at Order Status Manager where if a user has renamed labels for core order statuses these won't be filterable in some parts of the admin UI, mainly at the top of the orders edit screen: http://cloud.skyver.ge/1L3A3T0r3b2e and the default labels will be shown instead.

Currently I have a js workaround in place but of course it's not best practice.  Passing those shop orders statuses as an array into `apply_filters()` would do the trick.

PR in #10739

**Comment by claudiosmweb** [comment]
I don't think that needs a filter for something that you can add new status just using a global WP function.

Easy to hook into `add_action( 'init', 'your_function_name', 9 );` and include your own status.

**Comment by unfulvio** [comment]
Ok, I'm not adding new statuses. I'm filtering labels of the statuses WooCommerce registers in $args, not status key. Even if I could overwrite those maybe it's not as solid or portable and it would do a lot of code duplication just to register the same statuses as WC does.

**Comment by bekarice** [comment]
> I don't think that needs a filter for something that you can add new status just using a global WP function.

We're not talking about new ones, as @unfulvio mentioned above :) We're modifying the names of the core ones. While Order Status Manager lets you add new statuses, a popular features is that it lets you **rename** the core statuses (keeping the slug / key intact of course). 

So if you want "Processing" to become "Payment received", you can rename it, and while the slug is still `wc-processing`, it should show as "Payment received" throughout the admin. Without a filter, we're left with modifying the status name via js when the orders list is viewed, so filtering the status names would be cleaner / more portable throughout the admin.

See stuff like [ZD ticket 405089](http://woothemes.zendesk.com/agent/tickets/405089)

**Comment by claudiosmweb** [comment]
Still it's possible manipulate it using the global `$wp_post_statuses`.
https://core.trac.wordpress.org/browser/tags/4.5/src/wp-includes/post.php#L675

**Comment by unfulvio** [comment]
mmm but I'm sure you know that altering globals is quite a bad practice that WordPress has encouraged for some time... hard to support or debug or test... We try not to do that in our code and I think WC doesn't as well

what's the best argument for __not__ adding a filter there? performance?

**Comment by claudiosmweb** [comment]
@unfulvio simply because you did not give me any good reason for it.
You talk about "repeat code", I see code being repeated within an array and adding a new filter for something that you can change by a global variable.

**Comment by claudiosmweb** [comment]
Besides a filter can encourage people to use it incorrectly.
I understand for what you want to use, still open opportunities for people broke things too.

**Comment by maxrice** [comment]
@claudiosmweb would you be willing to look at PR with the proposed changes for this? We're happy to put one together 😸

**Comment by unfulvio** [comment]
well the repeating of `register_post_type` hasn't really to do with the filterability issue - you can still loop an array as I did in PR without the filter, that's really a minor nicety which I just thrown while editing code

my main focus here was the ability to filter the order statuses labels as they appear on top of the orders screen page - I could not find another suitable filter and I was left with two poor options, js hack or editing globals , I don't know which sounds worse

things are already broken for people who intend to use a WooThemes product as advertised (customise core order status labels)

**Comment by maxrice** [comment]
edit: I see that we have a PR already -- @claudiosmweb is there a specific reason you're against that filter? I agree with @unfulvio that modifying via the global feels pretty hacky vs. having a dedicated filter in WC core.

**Comment by claudiosmweb** [comment]
@maxrice @unfulvio 

> modifying via the global feels pretty hacky

I agree. I totally agree.

But a filter there can influence people to do hacks as well. Perhaps even worse, because once we put a filter, we are telling the world that we support it.

**Comment by claudiosmweb** [comment]
I understand that you are unhappy with the options available to solve this today, so I'll merge that PR.
But I'll troll everyone when see someone using this filter incorrectly and removing our status  :stuck_out_tongue_winking_eye:

**Comment by maxrice** [comment]
thank you, it's much appreciated and I think it'll make users of the  Order Status Manager extension very happy too 😎

**Comment by claudiosmweb** [comment]
:stuck_out_tongue_winking_eye:

**Comment by unfulvio** [comment]
you can always add a comment above that filter:

`// SkyVerge made me do it`

:smile:

**Comment by claudiosmweb** [comment]
@unfulvio that's the idea!
