### ISSUE TITLE
Consider supporting variable products when JS is disabled

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#10737]
## EXPLANATION OF THE ISSUE

I realize that most users have javascript enabled, but it would be nice to not give those that disable it a totally broken experience.

I haven't had time to really dig into what it would take to get it working, but with the changes in 2.5, it seems like most of the pieces are in place (e.g. the Add to Cart button is now always visible).

## STEPS TO REPRODUCE THE ISSUE

1. Visit a variable product page with JS disabled (main product image may not show)
2. Select a variation and click Add to Cart
3. Receive error: "Please choose product options…"

**Comment by mikejolley** [comment]
Would be possible to potentially use the same code as in the AJAX handling for variations, however, it would need to just throw errors if variations did not match. Still a poor experience at any rate..

**Comment by dominic-p** [comment]
That seems like a good idea to me.

From my perspective, a poor experience when errors occur is worth it to allow basic functionality. I would think If you're browsing with JS disabled, you have to expect a sub par user experience.

**Comment by mikejolley** [comment]
Things like add-ons and other extensions would still be broken though. TBH it might be better to encourage users to enable JS rather than give a sub-par experience and annoy them during said process?

I mean, if you fill out the variations form without JS and it's hit or miss to whether its available or not, that would be pretty annoying :)

**Comment by dominic-p** [comment]
Yeah, I see your point there. The process could get very frustrating for shops where individual variations are inventoried. I still feel like this is to be expected by a user who has disabled JS (if they cared about ease of use, they would probably leave JS on).

As I think about it more though, shouldn't it be possible to refresh the page whenever a variation is selected? That way, invalid combinations could be removed. It would definitely add some complexity to the code base though.

**Comment by dominic-p** [comment]
Wow, 2 lines of code and a working solution! Impressive. Thanks for doing that.
