### ISSUE TITLE
Problems with translation

### ISSUE THREAD

**Issue by zefisio** [woothemes/woocommerce#10743]
Hello,

There is a bug with the shop page of woocommerce when I change the language to Brazilian Portuguese.
It displays my products, but when I click on the product it shows an error page (product not found).
When I change back to English everything is ok.
I tried to use the Twenty Twelve to see if it is a theme problem, but it is not. I deactivated all the plugins too. Still the same thing.

Thanks in advance

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Settings > Permalinks > Save
