### ISSUE TITLE
?product_cat=category on a product category permalink

### ISSUE THREAD

**Issue by dzeriho** [woothemes/woocommerce#10748]
Hi,

When I do this mywordpresssite.com/category/my-cat-1/?cat=my-cat-2 everything works as expected, that is when the posts are in question, and the posts that have both categories are shown. But if I do this, using the products,  mywordpresssite.com/product-category/my-cat-1/?product_cat=my-cat-2 the page redirects itself to mywordpresssite.com/product-category/my-cat-2/ Why did this happen? This is definitely not standard?

Thanks!

**Comment by mikejolley** [comment]
You can use for example:

`
/category/accessories+action-figures/
`

To get around canonical redirects.

**Comment by dzeriho** [comment]
Actually it doesn't works with the native posts either, meaning the posts that should be shown are not shown, but the redirect just doesn't happen. Thanks for your answer!

**Comment by mikejolley** [comment]
I tested the above URL and it showed products in both categories (it's an 'and' query).

**Comment by dzeriho** [comment]
If I may, the problem is in the redirect and not the URL to achieve this, because I cannot use the suggested `/category/accessories+action-figures/`, and that is because I want to have both values separately, meaning that I also want compatibility with this too `/category/accessories+action-figures/?product_cat=third_cat`. I have functions which to put it all in the tax_query to support this and everything works fine, but the redirect is messing it up. If the redirect wouldn't happen everything would be good, as both values would still be there, now it just redirects and returns the permalink value. So, I thought you had some redirect going on if this behavior is detected. Correct me if this is not on the WooCommerce side. Thanks for all your effort! I really appreciate it.

**Comment by mikejolley** [comment]
I think the redirect is canonical. You may be able to disable it with:

`
add_filter( 'redirect_canonical', '__return_false' );
`

**Comment by dzeriho** [comment]
That's just amazing. I'll dig into it right now! Thanks a lot! ;)
