### ISSUE TITLE
Add a warning when using woocommerce.php and woocommerce/product-archive.php

### ISSUE THREAD

**Issue by revxx14** [woothemes/woocommerce#10741]
I just spent about an hour trying to figure out why my changes to `woocommerce/archive-product.php` weren't taking. I thought I was going crazy, but after skimming through the documentation I came across [the last paragraph on this page](https://docs.woothemes.com/document/template-structure/).

Because I had a `woocommerce.php` in my template, it was ignoring the `woocommerce/archive-product.php`. I understand that's intended behavior, but I have a suggestion on how to prevent future devs from pulling their hair out.

As there's obviously already a check to ignore `woocommerce/archive-product.php` if `woocommerce.php` exists, an warning message should be shown somewhere as well. It could be something like:

```
if ( $woocommerce_and_product_archive && is_admin() ) {
    echo "<p><strong>NOTICE:</strong> When creating woocommerce.php in your theme’s folder, you will be unable to override the woocommerce/archive-product.php custom template in your theme, as woocommerce.php has priority over all other template files. This is intended to prevent display issues.</p>";
} 
```

Obviously that's a rough example, but it'd definitely help to have a warning like this.

**Comment by mikejolley** [comment]
This is covered in both: https://docs.woothemes.com/document/third-party-custom-theme-compatibility/ and https://docs.woothemes.com/document/template-structure/ - if you're making woocommerce.php you should see this. I can add a note to system status but nothing more prominent is needed.

**Comment by revxx14** [comment]
Yea, you're right. A message in System Status probably makes the most sense; currently if you have a woocommerce.php and a woocommerce/archive-product.php, it says that archive-product.php is being detected just fine. That's part of why I was so confused. I think making a note next to it would solve the issue.
