### ISSUE TITLE
2 digits code for countries.

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10745]
The list of 2 digits code is not up to date.
https://github.com/woothemes/woocommerce/blob/fa30a38c58373d9c3706cc0b7ae22032de3a2985/i18n/continents.php

Where is 'SS' - South Sudan?
http://www.iso.org/iso/home/news_index/news_archive/news.htm?refid=Ref1456

Also, do you update countries name ?
do you update countries name base on offical name?
Not long ago Czech Republic changed its name to Czechia.
http://www.theguardian.com/world/2016/apr/15/czech-republic-czechia-new-name

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/i18n/countries.php#L225

**Comment by mikejolley** [comment]
https://en.wikipedia.org/wiki/Czech_Republic AKA Czechia. Translate if its more relevant to your market.
