### ISSUE TITLE
Enhanced URL based add to cart functionality

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#10749]
This is more of a feature request / enhancement than anything.

The ?add-to-cart=xxxx feature to add order items to the cart using the URL is great, however it would be amazing if we could put this in as a comma separated list such as ?add-to-cart=xxx,xxx,xxx to add more than one product to the cart at once. 

If the quantity string could also work in the same way, tying into the add to cart ones, this would also be great. I.e. ?add-to-cart=151,164,189&quantity=1,2,3

This would add to cart:

1 x ID 151
2 x ID 164
3 x ID 189

Happy to try and hack something together, if you can point me in the right direction? Think this would be a pretty cool feature!

**Comment by mikejolley** [comment]
This wouldn't be ideal for collecting other data such as from addons..

**Comment by shawaj** [comment]
In what sense?

**Comment by mikejolley** [comment]
In the sense it wouldn't let you associate data with each ID, and if it fails it cannot redirect to one failing product.

**Comment by mikejolley** [comment]
Since core won't make use of this, I don't want to further complicate the add to cart methods. It would be fairly simple to build a custom query var which takes an array of IDs and call add_to_cart on each if needed in your implementation.
