### ISSUE TITLE
[API] Attribute options not fetched if attribute is a taxonomy

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10747]
The function `get_attributes()` in abstract-wc-product.php seems to produce wrong indexes for it's outputting array. 
The indeces that should represent the attrbitue-names contain dashes '-' insted of underlines '_'

WordPress: 4.4.2
WooCommerce: 2.5.5

example:

    [pa-attr-all-board-material] => Array
        (
            [name] => pa_attr_all_board_material
            [value] => 
            [position] => 1
            [is_visible] => 1
            [is_variation] => 0
            [is_taxonomy] => 1
        )

This has a huge impact on fetching options for a taxonomy like in 
In class-wc-api-products.php on line 2519 is a call 
`$options = explode( ',', $product->get_attribute( $attribute['name'] ) );` 
which gets compared in abstract-wc-product.php on line 1345 with this statement 
`if ( isset( $attributes[ $attr ] ) || isset( $attributes[ 'pa_' . $attr ] ) )`

Since the index of the $attributes array is `pa-attr-all-board-material`and the var $attr is `pa_attr_all_board_material` it will always return false

A dirty quickfix is to rewrite class-wc-api-products.php on line 2519 from
`$options = explode( ',', $product->get_attribute( $attribute['name'] ) );`
to
`$options = explode( ',', $product->get_attribute( str_replace('_','-', $attribute['name']) ) );`

**Comment by mikejolley** [comment]
Not sure what you're looking at here:

https://dl.dropboxusercontent.com/s/9eux0sjzy9nmwcz/2016-04-20%20at%2010.46.png?dl=0

All global attribute keys have pa_, everything else is dashed.

In the function you found:

`
if ( isset( $attributes[ $attr ] ) || isset( $attributes[ 'pa_' . $attr ] ) )
`

`$attr` doesn't contain 'pa_' and is also ran through `sanitize_title` which converts underscores to dashes.

I see no discrepancy here. I think your 'pa-' attribute is not global.

**Comment by ad-on-is** [comment]
Nevermind, something was wrong with our database.
Sorry!
