### ISSUE TITLE
[2.6] Adding a new shipping zone w/ intro button

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10757]
When using the "add shipping zone" button, the introductory text doesn't go away. And on a smaller screen, this can be quite confusing: http://cld.wthms.co/v9cQ/1i7dWQWn

Should we make that section disappear right away after adding a zone?

**Comment by mikejolley** [comment]
Actually this notice will go away as soon as you add a shipping method to a zone. It doesn't check for just zones.

**Comment by WPprodigy** [comment]
I think it works correctly the very first time you visit the page and click the button / add a zone and method.

But if you've had shipping zones in the past and just delete them all - then you run into the above scenario. http://cld.wthms.co/1i1sV/15fa03Dh

And I don't think it will ever go away if you are only using "Rest of the World"?

**Comment by mikejolley** [comment]
It checks the count of methods. Not zones

**Comment by WPprodigy** [comment]
Right, but shouldn't it be hidden if you have methods set up in the "rest of the world" zone? I can imagine this will be a pretty common set-up, for those not having the need for zones.

![](http://cld.wthms.co/ry9o/1bFTaQpI+)

**Comment by mikejolley** [comment]
O that - I thought you meant the admin notices in your video first frame..

**Comment by WPprodigy** [comment]
Ahh, my bad! I knew there was mis-communication somewhere because this definiltey didn't feel right haha.
