### ISSUE TITLE
SKU is no longer exclusive

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#10751]
Hey-o,

It appears that SKU values for WooCommerce products are no longer exclusive. Here's a screenshot of a product I've duplicated and saved:

![http://cld.wthms.co/134Rs/3k8nvBEO](http://cld.wthms.co/134Rs/3k8nvBEO+) 

Was this intentionally removed? I couldn't find anything on the changelog.

411718

**Comment by claudiosmweb** [comment]
How you did it?
Missing the steps to reproduce...
