### ISSUE TITLE
Check for edit_themes capability fails

### ISSUE THREAD

**Issue by misulicus** [woothemes/woocommerce#10753]
## EXPLANATION OF THE ISSUE

With DISALLOW_FILE_EDIT enabled the options to copy and override the email templates when viewing an email template and edit it are not visible.

## STEPS TO REPRODUCE THE ISSUE

Edit wp-config.php and set DISALLOW_FILE_EDIT to true

**Comment by mikejolley** [comment]
This creates a new file in the theme - so technically this is editing and should be prohibited if disabled.
