### ISSUE TITLE
Issue with WP 4.5 - Can´t add product variant to cart

### ISSUE THREAD

**Issue by basjonne** [woothemes/woocommerce#10756]
Upgraded to WP 4.5 and the user can´t add a product variant to the cart. The following error message shows up after hitting add to cart-button (translated to english): "Select product variant...". 

![image](https://cloud.githubusercontent.com/assets/78029/14700372/58299a50-079f-11e6-8f63-c2d527acfa56.png)

Downgraded to WP 4.4.2 and it works fine again. 

Br, 
Erik 

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by martinkarls** [comment]
Same problem for me (also in Swedish):

![skarmavbild 2016-04-21 kl 10 05 59](https://cloud.githubusercontent.com/assets/11160218/14701993/6c42bac2-07a8-11e6-9065-aab8b5cdb4a1.png)

**Comment by mikejolley** [comment]
Theme/plugin jquery issues - https://wordpress.org/support/topic/wp-45-javascript-errors-please-choose-product-options-etc?replies=1
