### ISSUE TITLE
Remove all data does not remove everything

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#10759]
If I select the option to remove all data when deleting WooCommerce it seems that it does not remove all the data.

After doing so, and deleting WooCommerce, I'd expect the wizard to run again when installing WooCommerce. It does not instead.

I tested reinstalling WC 2.5.5 and WC 2.6.

**Comment by mikejolley** [comment]
Tested. After re-adding the plugin files and re-activating, wizard was shown.

**Comment by SiR-DanieL** [comment]
I tested it again, still not working for me.

I was on the master of WC 2.6. I selected the option, disabled and deleted WooCommerce. Then I installed it again from Plugins > Add New > Search and Install.

I get the version 2.5.5 installed, the DB still says that it's 2.6.0 though. The Wizard does not run.

**Comment by mikejolley** [comment]
@SiR-DanieL maybe it's caching the options table?

`
	$wpdb->query("DELETE FROM $wpdb->options WHERE option_name LIKE 'woocommerce\_%';");
`

We just delete from DB.

**Comment by SiR-DanieL** [comment]
Mmm I don't know if there's any cache on Pressable. I don't have any plugin for that or configured it.

@seanosh do you know?

**Comment by seanosh** [comment]
Yes, there'd be object caching via memcached. If that's not cleared and this is just straight deleting the records from the table, then yes, it's probably why it's not working since the get_option will pull results from memcache if present. Looks like @mikejolley just addressed this.
