### ISSUE TITLE
Apply coupon to rest of order when there is an excluded product in cart

### ISSUE THREAD

**Issue by mahdiyazdani** [woothemes/woocommerce#10763]
I've a issue with coupon in woocommerce.
customer try to order some products and in the basket (cart) there is another product that excluded from coupon section in woocommerce, so client tries to apply coupon but it doesn't work, eventually client tries to create two separated order to handle this issue
its obviously a bit inconvenient for client, and it means client could maybe get two postage charges so its just a bit messy
Any idea about this?

**Comment by mikejolley** [comment]
Change it to a product coupon rather than cart coupon.
