### ISSUE TITLE
The products image does not update using rest api

### ISSUE THREAD

**Issue by fagworio** [woothemes/woocommerce#10768]
## EXPLANATION OF THE ISSUE

I have a problem to update the products images.
The images doesn't been updated

## STEPS TO REPRODUCE THE ISSUE

1. I am using the rest api like the sample to update the product.

```
$data = [
    'product' => [
        'title' => 'Update a product',
        'regular_price' => '24.54'
    ],
        'image' => [
                [
                'id' => 14931,
                'src' => 'http://192.168.122.37/integracao/wp-content/uploads/2016/04/premium-quality-front.jpg',
                'position' => 1
        
               ],
]

];

print_r($woocommerce->put('products/14930', $data));

```

**Comment by claudiosmweb** [comment]
@fagworio or you send the image `id` or the `src`. Since if you send the `id` will be always used instead the `src`.

**Comment by fagworio** [comment]
Thanks for replay.

I am sending the id of the old image and send url of the new image

**Comment by claudiosmweb** [comment]
:stuck_out_tongue_winking_eye:

**Comment by fagworio** [comment]
Do you have any Idea how to update correctly the products images?

**Comment by claudiosmweb** [comment]
@faqworio just submit the new image SRC **or** ID.

**Comment by fagworio** [comment]
I will try, tanks
