### ISSUE TITLE
display error message on checkout page, custom payment gateway

### ISSUE THREAD

**Issue by sandrodz** [woothemes/woocommerce#10762]
Hi,

I'm working on payment gateway using WOO API, and I noticed following...  

in the `process_payment` method, on checkout page, there is no way to display error to user!

`wc_add_notice` won't work, because buy button calls are ajaxified. 

```php
try {
	throw new Exception( __( 'not responding, please try again later', 'woo' ) );
} catch ( Exception $e ) {
	wc_add_notice( $e->getMessage(), 'error' );
	$order->update_status( 'failed', $e->getMessage() );
}
```

is there a way to display error message on checkout page when payment fails?

**Comment by sandrodz** [comment]
Looked into this further, so apparently I've to return an array. But message is still being ignored!
```php
return array(
	'result'   => 'failure',
	'messages' => $order_note
);
```
I'm returning this inside `process_payment` method

**Comment by mikejolley** [comment]
wc_add_notice works during process_payment(). Notices will be collected and displayed for you after loading.
