### ISSUE TITLE
WooCommerce Embeds

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/woocommerce#10772]
## EXPLANATION OF THE ISSUE

In WordPress 4.4, WordPress released the ability to have a single WordPress post be embeddable via the oembed protocol. WooCommerce promptly added support for this in release 2.4.11 (https://woocommerce.wordpress.com/2015/12/07/woocommerce-2-4-11-fix-release-4-4-compatible/). However, with the recent upgrade to Wordpress 4.5, the ability to embed products via oembed is no longer working. I thought it was a storefront issue, however I tested it on a few other woo demo sites for different themes, and it appears to be a WooCommerce core issue.

## STEPS TO REPRODUCE THE ISSUE

1. Paste a link to a WooCommerce product on a WordPress 4.4 site and see an embedded image:
<img width="549" alt="screen shot 2016-04-22 at 1 57 11 pm" src="https://cloud.githubusercontent.com/assets/2293077/14750322/3266b962-0892-11e6-9c26-5afb1ba0dd48.png">

2. Paste a link to a WooCommerce product on a WordPress 4.5 site and see a link in a block quote:
<img width="308" alt="screen shot 2016-04-22 at 1 48 46 pm" src="https://cloud.githubusercontent.com/assets/2293077/14750318/2ed6643c-0892-11e6-842e-665d03f267c0.png">

For this example I used the product here: 
https://www.tethertools.com/product/rock-solid-lopro-phone-mount/

**Comment by WPprodigy** [comment]
May have something to do with one of these changes: https://make.wordpress.org/core/2016/03/11/embeds-changes-in-wordpress-4-5/

As a side note, what if we added a template for this? Something like embed-{post-type}.php that is used unless the theme calls it first.

**Comment by todorchrisov** [comment]
I have absolutely the same problem. 

After upgrade to WordPress 4.5 of our WooCommerce site all embeds from this site to a normal WordPress blog are shown as a URL in a block quote.

If I embed a normal WordPress page from one blog to another blog, then it works fine. But the pages from our WooCommerce site do not embed properly.

How can I fix this?

**Comment by BurlesonBrad** [comment]
@swissspidy

**Comment by swissspidy** [comment]
I am not familiar with how WooCommerce implements embeds, but it looks like `	WC_Embed` simply adds some filters and custom CSS. No point of conflict there.

But, WooCommerce filters `template_include` to display the single product template when being requested, overriding the WordPress default (`/wp-includes/theme-compat/embed.php`). This shouldn't be done.

Either it should not override the template when `is_embed()` is true, or provide a custom embed template in the WooCommerce templates directory.

The notable changeset in WordPress core is https://core.trac.wordpress.org/changeset/36876, where embeds were properly added to the template hierarchy. Previously, the embed template needed to be filtered separately, and the `template_include` filter wasn't triggered.

**Comment by swissspidy** [comment]
Just submitted a PR to restore previous behaviour, see #10784. This is something for a minor or patch release, whereas adding a custom embed template to WooCommerce would be something for a major / minor release.
