### ISSUE TITLE
Attribute Title length limit

### ISSUE THREAD

**Issue by joelnewcomer** [woothemes/woocommerce#10770]
When attributes titles are longer than 32 characters (more than the limit for a taxonomy term name) WooCommerce variations won't save. Please add a note to attribute fields indicating that the attributes are limited to 32 characters and automatically trim them when they are longer. Thanks for your continued work on the best eCommerce platform on the planet.

**Comment by mikejolley** [comment]
Not sure how you managed this one - we have validation when creating global attributes:

https://dl.dropboxusercontent.com/s/pcejzl8bpvpedy1/2016-04-25%20at%2014.32.png?dl=0

Let me know if thats not clear.

**Comment by joelnewcomer** [comment]
A client discovered it and it took me 4 hours to figure out why their variations weren't saving. I apologize for being unclear. The issue is on the product page on the Attributes tab:

https://cloudup.com/cM9ISLsRAon

Thanks Mike!

**Comment by mikejolley** [comment]
@joelnewcomer These are not terms. What you have there is a custom attribute, so these values are stored in post meta. There is no limit on this. 

Products > Attributes are terms.

**Comment by joelnewcomer** [comment]
That is really weird. Last week I couldn't save a variation that had a custom attribute name that was longer than 32 chars. But I tested it today and it saved. I don't know what was happening last week. Mind blown. Thanks for your help!
