### ISSUE TITLE
Check instead cheque for American English

### ISSUE THREAD

**Issue by emiluzelac** [woothemes/woocommerce#10779]
This is very minor, but it would be nice to change for American users:

Check vs. cheque. In American English, check is the standard spelling of the noun referring to a written order for a bank to pay a specified amount from deposited funds. Outside the U.S., the word is spelled cheque.

https://github.com/woothemes/woocommerce/search?utf8=%E2%9C%93&q=Cheque+Payments

![screen shot on 2016-04-23 at 19-29-48](https://cloud.githubusercontent.com/assets/1784526/14764759/fdfa387c-0989-11e6-99bb-92e95c876f8b.png)

This could possible change once the U.S. state is selected.

**Comment by Kenshino** [comment]
Is it not in the American translations?

**Comment by emiluzelac** [comment]
This was specifically for the setup screen 🙂
