### ISSUE TITLE
WP Notice in the Comments Dashboard

### ISSUE THREAD

**Issue by kcppdevelopers** [woothemes/woocommerce#10777]
## EXPLANATION OF THE ISSUE

I am getting this WP notice after I deactivate WooCommerce in the Comments Dashboard.

Notice: map_meta_cap was called <strong>incorrectly</strong>. The post type shop_order is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.4.0.) in E:\wordpress\wp-includes\functions.php on line 3901

## STEPS TO REPRODUCE THE ISSUE

1. deactivated WooCommerce  plugin.

**Comment by kcppdevelopers** [comment]
![woo](https://cloud.githubusercontent.com/assets/13145461/14759325/f1a85cb8-093c-11e6-9fed-37a9cfa2c4d1.png)

**Comment by mikejolley** [comment]
https://core.trac.wordpress.org/ticket/34918
