### ISSUE TITLE
Checkout Settings Proposal

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10774]
The shipping settings start off with a table of the the shipping methods / zones. And then there is a secondary page for configuring the shipping options : http://cld.wthms.co/1b13D/2IWZ5HSJ

The email settings also start off with a table of the emails: http://cld.wthms.co/19SV3/4TjCLVkw

When you go to the checkout settings though, you don't find the actual checkout methods until scrolling to the very bottom of the page. Or, you can click the breadcrumbs to view the checkout methods individually.

Instead of having sub pages for each checkout method, what if it was changed to work/look similar to how shipping and emails are now. The first page would be a table of the checkout methods, and then a second page could be for checkout options.

Benefits:

- Less overall settings pages that the user can see.
- Similar flow to how shipping and emails work.
- Remove a lot of breadcrumbs pages, as neither shipping nor email have them for "methods" anymore.
- This will leave more room for extensions to use that breadcrumb space for non-gateway plugin options.

On the negative side of things though, I'm not sure if this could be done without breaking current gateway extensions as they currently use the gateway api to create a new settings page for their method.

**Comment by mikejolley** [comment]
Looking at this in s9n.
