### ISSUE TITLE
2.6 beta 1 introduces new strings with non-positional placeholders

### ISSUE THREAD

**Issue by webaware** [woothemes/woocommerce#10775]
## EXPLANATION OF THE ISSUE

WooCommerce 2.6 beta 1 introduces lots of new strings. Quite a few of the new strings have non-positional placeholders, like `%d` and `%s`. This can cause problems when translating into languages that need to rearrange the order of placeholders in a string.

For example, in the following string there are three placeholders. Because they have no position stated, rearranging the order of the placeholders in the string will change which `sprintf()` parameter is inserted for `%s`, and the from and to parameters.

`%s must be between %d (inclusive) and %d (inclusive)`

Using positional placeholders allows translators to rearrange where the placeholders go while preserving the correct placement of `sprintf()` parameters:

`%1$s must be between %2$d (inclusive) and %3$d (inclusive)`

Ref: "argument numbering/swapping" in [the PHP manual](http://php.net/manual/en/function.sprintf.php)

### Numeric placeholders

Additionally, quite a few placeholders are numeric integer placeholders `%d`. It might be worthwhile assessing whether that is appropriate when revisiting these placeholders, or whether they'd be better as string placeholders `%s` and fed a formatted number:

```
sprintf( __( '%1$s must be between %2$s (inclusive) and %3$s (inclusive)', 'woocommerce' ), 
    $param, 
    number_format_i18n( $args['minimum'] ),
    number_format_i18n( $args['maximum'] ) )
```

**Comment by mikejolley** [comment]
Will see what I can find (with regex `\_\_\((.*)\%s(.*)\%s(.*)\)`)

**Comment by webaware** [comment]
Sorry, should have thought; [start here](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-gb/default?filters[term]=%25&filters[user_login]=&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&sort[by]=original_date_added&sort[how]=desc&sorts=Sort) and you'll see some of these strings:

**Comment by mikejolley** [comment]
Some of these are fine, I'll just change the ones I see as problematic.
