### ISSUE TITLE
Shipping tax calculation based on base currency instead of current currency.

### ISSUE THREAD

**Issue by vretareh** [woothemes/woocommerce#10778]
## EXPLANATION OF THE ISSUE

When third party plugin is used for multi currency, the shipping taxes are not calculated correctly for any other currency than WooCommerce base currency. This is not the case for regular product taxes. Note that this it NOT caused by third party plugin (other than Woo)

## STEPS TO REPRODUCE THE ISSUE

To reproduce this issue, you need to have some kind of multi currency plugin or hard coding that makes the current currency differ from WooCommerce base currency.

Let's say the base currency is SEK (Swedish crowns) and the current currency is $ and let's say the conversion rate is 10:1. Let's say the tax rate is 25%

Tax for a regular product that costs $10 is calculated as 10 * 0.25 = $2.5, but
Tax for shipping (no matter what kind) that costs $10 is calculated as 100 * 0.25 = $25. reason for this is that the base currency SEK (wich is $ *10) is used for shipping tax calculation

I Changed line 131 in abstract-wc-shipping-method.php from
`$taxes = WC_Tax::calc_shipping_tax( $total_cost, WC_Tax::get_shipping_tax_rates() );`
to
  `$taxes = WC_Tax::calc_shipping_tax( apply_filters( 'woocommerce_get_price', $total_cost ), WC_Tax::get_shipping_tax_rates() );`

Which seems to solve the problem when a not "per item" tax is applied. However this is just to point out the error and is not claiming to be a solution to the problem.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: sv_SE

### Server Environment ###

Server Info: Microsoft-IIS/8.5
PHP Version: 5.5.6
PHP Post Max Size: 384 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.30
Max Upload Size: 384 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (14) ###

Polylang: av Frédéric Demarle – 1.8.5
CMB2: av WebDevStudios – 2.1.2
Kirki Toolkit: av Aristeides Stathopoulos – 2.0.7
Loco Translate: av Tim Whitlock – 1.5.5
Note - A live edit text widget: av Slocum Studio – 1.3.1
oik Weight/Country Shipping: av bobbingwide – 1.3.2
Plugins Language Switcher: av Vladimir Garagulya – 1.4.4
One-Click Child Themes for Slocum Themes: av Slocum Studio – 1.0.2
Hyyan WooCommerce Polylang Integration: av Hyyan Abo Fakher – 0.25
WooCommerce Currency Switcher: av realmag777 – 1.1.5.4
Woocommerce osCommerce Import: av David Barnes – 1.2.1
WooCommerce: av WooThemes – 2.5.5
WP-Mail-SMTP: av Callum Macdonald – 0.9.5
XO10 - WooCommerce Categories widget: av Walter Lee – 2.0

### Settings ###

Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –
API Version: 3.1.0

### WC Pages ###

Butikbas: #4 - /
Varukorg: #5 - /en/varukorg/
Kassan: #6 - /en/kassan/
Mitt konto: #7 - /en/mitt-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: MaxStore
Version: 1.1.2 – 1.2.0 finns tillgänglig
Author URL: http://themes4wp.com
Child Theme: ✕ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
> Note that this it NOT caused by third party plugin.

How can this even be the case - WC core has no support for multicurrency, so if they lack the handling for this it's not a core issue?

**Comment by vretareh** [comment]
Sorry, I meant no other third party plugin than WooCommerce

**Comment by mikejolley** [comment]
Just adding a filter here is not a solution, sounds more like a workaround for the handling of multi-currency in the other plugin. Core should **not** work around issues introduced in plugins extending core.

In this case the 'costs' should already be converted to X currency. Taxes should always be based on the actual costs given, not a filtered amount. 

If the multi-currency plugin needs extra hooks they can request them or send a PR.
