### ISSUE TITLE
Post Product review and rate product using API

### ISSUE THREAD

**Issue by ahsanalishahid** [woothemes/woocommerce#10788]
Hi There,

I am working on a mobile app that integrates with Woocommerce API.  I have seen the API Documentation but I am unable to find any information regarding any endpoint which I can use to allow user to post product review and product rating. 

Can you please point me in the right direction to accomplish this?

Thanks in advance,
Ahsan

**Comment by claudiosmweb** [comment]
We don't have any endpoint yet for reviews. Maybe coming in a future version.
Logged in your roadmap: https://trello.com/c/Mr85CbCM/86-rest-api-post-edit-delete-products-id-reviews

**Comment by KobyQ** [comment]
Hi
Is this available now? Noticed the issue is closed but posting to the reviews endpoint does not work

**Comment by KobyQ** [comment]
It seems this works with the new version of the API.

```
[REST API] POST/EDIT/DELETE /wp-json/wc/v2/products/<id>/reviews

​Required fields:
{
    "review": "",
    "name": "",
    "email": ""
}
```
Thanks

**Comment by bar2** [comment]
as @KobyQ noted it is indeed available on the new version of the API but it is not available in the docs. Would be nice if this was on the docs.

**Comment by peeyooshk** [comment]
We are still getting for Reviews and Variable products.  
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by ManigandanRaamanathan** [comment]
Is it working now?? Can use the similar way of existing rest api endpoints??

**Comment by nickampro** [comment]
@ManigandanRaamanathan 
Yes, adding reviews work now (2018-08-08).

for a PHP script, it could look something like this... need to have values for variables.

`$attdata = array (
		'id' => $product-id,
		'name' => $name-of-reviewer,
		'rating' => $rating-number,
		'email' => $customer-email,
		'date_created' => $date,
		'review' => $review-comment,
	); 
$woocommerce->post('products/'.$product-id.'/reviews', $attdata);`


documentation isn't clear on creating/adding new reviews via a script, but [http://woocommerce.github.io/woocommerce-rest-api-docs/?php#product-review-properties](url)

**Comment by ManigandanRaamanathan** [comment]
@nickampro I wanted to create new order item reviews together with the order id fields. I wanted it to return back the order id field for each reviews together with the review list. So that in the future I can filter the reviews based on the order id. How to accomplish this?

Or is there a way to add the review id field for the products within the line_item rest output of the get_order list?

**Comment by claudiosanches** [comment]
There is already a reviews endpoint in v2, and will be a better reviews endpoints for v3, so all solved.
