### ISSUE TITLE
Customer Message

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10780]
In order menu there is a column called Customer Message, if you will pass over with the mouse on the column you will a comment if the customer left one.

Where in the database this comment is saved?
i don't see it in wp_postmeta table.

**Comment by WPprodigy** [comment]
It is saved in the posts table as the `post_excerpt`.

**Comment by test101test101** [comment]
How do I connect it to a specific order?
Suppose the Order # is 53344

It's very hard to understand the database code, there is no guide of what is saved where, no foreign keys, database is not normalized.

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Database_Description

Order ID = Post ID

**Comment by test101test101** [comment]
Post table (wp_posts) doesn't have Order ID nor Post ID, just ID.
When I do: `select post_excerpt from wp_posts where  id=xxx`
the field is empty. but when I go to the order in Order panel I see the user comment.

How is that possible?

**Comment by mikejolley** [comment]
ID is in caps.

**Comment by test101test101** [comment]
I get all the information from the record  if i do `select * from wp_posts where id=xxx`
the post_excerpt just has no data.

whether i do 
`select post_excerpt from wp_posts where id=xxx`
or
`select post_excerpt from wp_posts where ID=xxx`

**Comment by mikejolley** [comment]
So is your ID wrong?

**Comment by mikejolley** [comment]
Either that or you're confusing order notes with customer note field.

**Comment by test101test101** [comment]
mike, the ID isn't wrong. I'm looking to get Customer Message just as I wrote.
See images:
[image](http://i.imgur.com/T8dpC2d.png)
[image2](http://i.imgur.com/iBMeapm.png)

**Comment by WPprodigy** [comment]
Use this: https://developer.wordpress.org/reference/functions/get_post_field/

`get_post_field( 'post_excerpt', $post_id )`
