### ISSUE TITLE
Method for re-calculating all taxes on the order

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#10786]
Earlier today I had to write some code to adjust an order that was manually created by another extension. (I needed to add a discount, in order to fulfil a special offer).

This involved re-calculating the taxes on the order. To guide me in doing this, I manually adapted the reasonably lengthy section of code in WC_AJAX::calc_line_taxes().

Well, that all worked. But, it would be good if there was method on the order object to do it ... especially since, because that section was quite lengthy and involved deep knowledge, it feels highly likely to be the sort of thing that'll need re-writing in future if/when WC internals change.

e.g. perhaps a method
WC_Order::recalculate_taxes($location_info)
where $location_info is an array with keys country/state/postcode/city.

**Comment by mikejolley** [comment]
It is coming my friend :) https://github.com/woothemes/woocommerce/pull/10259
