### ISSUE TITLE
Missing shipping subtotal in emails when resending invoice

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/woocommerce#10782]
Ticket: 412895-zd-woothemes

**Summary**

When a completed order is edited by adding a shipping cost, resending of the invoice (generated by WC) does not include the "Shipping" subtotal.

**Steps to Reproduce**

1. In WP backend, open completed order and mark as "On Hold"
2. Click **Add Line Items > Add Shipping Cost**
3. Edit the shipping cost amount
4. Mark order as "Complete"
5. Under **Order Actions**, select *Custom Invoice* to send new email
6. Inspect the new email sent out (I used [Email Log](https://wordpress.org/plugins/email-log/) to keep a log of all email sent)

**Screenshots**

* Screenshot of new invoice (notice the difference between subtotal, total and the missing shipping cost of $10): http://cld.wthms.co/Ao40/52ZsXzAa

**Comment by mikejolley** [comment]
User did not set shipping line name field.
