### ISSUE TITLE
The problem user login theme

### ISSUE THREAD

**Issue by Infolu** [woothemes/woocommerce#10799]
Hello I am with the following problem.
My structure is Next
Wordpress 4.5
Woocommerce 2.5
Theme / woocommer (Updated files with Core)

The problem is the Next, the woocommerce assumes the theme / woocommerce the User whether the system administrator or a customer is logged in, if I log off oh yes he takes on the theme / woocommerce. Has anyone ever experienced this?

**Comment by mikejolley** [comment]
You posted this on .org - don't abuse our bug tracker.
