### ISSUE TITLE
[2.6] - suggestion for additional method in shipping zones API

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#10790]
Looking through the code for shipping zones, it looks like, given a shipping zone, I can list the available methods. I have a need to do the reverse: given a shipping method, get the zones that that method is active in.

Of course, I can just enumerate all the zones, and enumerate their methods, and build the result from that. But, I wonder if I’m going to be the only person who wants to do this, and if adding an API method for it wouldn’t be useful for devs?

**Comment by mikejolley** [comment]
I don't like introducing functions such as this which have no use in core - we don't need to work backwards in WC core right now (unless you can see somewhere which can benefit)?

You'd probably be able to do this with 1 SQL query, woocommerce_shipping_zone_methods, query by method_id and get distinct zone_ids.
