### ISSUE TITLE
[WC 2.6] System Status + MariaDB

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#10793]
In the System Status you get this when using MariaDB:

![](http://cld.wthms.co/12Evo/3lycM90V+)

I'm on Pressable and it uses MariaDB, `$wpdb->db_version()` seems to work only with MySQL though.

I propose to change the row name to "Database version" and the value to be "MySQL X.X.X - Any error message" or "MariaDB X.X.X - Any error message"

**Comment by mikejolley** [comment]
It seems database dropins should be setting is_mysql https://core.trac.wordpress.org/changeset/34655

I'll add a check for this and then its down to the hosting to define this in their drop in code.
