### ISSUE TITLE
If a refund amount is directly entered the full tax amount still shows by order total

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#10792]
If you only enter the amount to refund and not the line items like so:
<img width="951" alt="screen shot 2016-04-26 at 12 28 42" src="https://cloud.githubusercontent.com/assets/6464323/14815352/28a918fe-0bab-11e6-8181-48b107264bf3.png">

The total tax is shown for the non-refunded order total:
<img width="509" alt="screen shot 2016-04-26 at 12 31 51" src="https://cloud.githubusercontent.com/assets/6464323/14815378/5c2985d8-0bab-11e6-9e13-fcec18257e44.png">

It doesn't really make sense that 0,00 DKK includes 14,00 DKK VAT.

**Comment by mikejolley** [comment]
@EmilEriksen it cannot accurately guess what items/taxes are refunded if you just enter a single amount. You need to use the qty inputs on the lines to refund those values.

**Comment by EmilEriksen** [comment]
@mikejolley I realize that but why even give the option to input a single amount if it's just going to mess the totals up?

**Comment by mikejolley** [comment]
Flexibility? Maybe a refund or amount needs returning without affecting line totals? We could make it readonly, but I think there may be push back.
