### ISSUE TITLE
Tax display is off by one, though calculation of tax and total amount is correct

### ISSUE THREAD

**Issue by conschneider** [woothemes/woocommerce#10796]
## issue description

The display of the calculated tax is off by one penny. 
At the end of the screencast the Tax amounts are 1.50 (product tax) + 1.50 (product tax) + 0.50 (shipping tax) = 3.50

The amount displayed is 3.49

The total order amount is correct. 

## steps to reproduce

Screencast: 
![tax-calculation-off-by-one-penny](https://cloud.githubusercontent.com/assets/271725/14823214/519205dc-0b97-11e6-9ab0-473a018143ea.gif)

Tested local and remote. 
Tested with Disable comments on and off

## system report

`
### WordPress Environment ###

Home URL: http://wcdemo.com/csv-rounding-412040
Site URL: http://wcdemo.com/csv-rounding-412040
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10
PHP Version: 5.5.28
PHP Post Max Size: 8 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.19
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.5
Disable Comments: by Samir Shah – 1.4.2

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@conschneider This is why I hate taxes :)

This is to be expected in this case. If you edit the line items you can see the true amounts:

```
1.4983
1.4983
0.498
```

Yes if you round them first, you'd get 3.50, however if you add the unrounded values you get:

```
1.4983 + 1.4983 + 0.498 = 3.4946
```

3.4946 rounded is not 3.50, it's 3.49. Therefore "fixing" this would a) be anti-maths, and b) cause the end total to be miscalculated.

This is the reason we offer the ability to show "tax inclusive" prices "tax inclusive" on the cart too, so the user never sees abnormalities like this :)

Marking as won't fix.
