### ISSUE TITLE
Quoted search terms broken in layered nav widget

### ISSUE THREAD

**Issue by jonathanww** [woothemes/woocommerce#10795]
Whenever you search on WooCommerce (front end) using two or more terms wrapped in quotes, the "s" query string within all links of the Layered Nav widget are broken. An example URL:

[http://website.com/products/?filter_manufacturer=1&s%22term1%20term2%22](http://website.com/products/?filter_manufacturer=1&s%22term1%20term2%22)

To temporarily fix this, line 353 can be modified in woocommerce\includes\widgets\class-wc-widget-layered-nav.php from:

`$link = add_query_arg( 's', get_search_query(), $link );`

to:

`$link = add_query_arg( 's', urlencode( get_search_query( false ) ), $link );`

This changes the example URL to:

[http://website.com/products/?filter_manufacturer=1&s=%22term1+term2%22](http://website.com/products/?filter_manufacturer=1&s=%22term1+term2%22)

Thanks,

Jonathan

**Comment by mikejolley** [comment]
As soon as it's encoded search breaks.
