### ISSUE TITLE
button  “Force Translation Upgrade” is absent

### ISSUE THREAD

**Issue by natalka456** [woothemes/woocommerce#10798]
## EXPLANATION OF THE ISSUE
Dear Sirs,
After installing WP Version:2.5.5, WC Version:2.5.5, there was no translation to Russian, no button “Force Translation Upgrade” in System Status - Tools.

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.
I removed all data and installed WC again. But nothing changed. What should I do to translate my internet-shop to Russian?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
WordPress Environment
Home URL:		http://zakladka.kiev.ua
Site URL:		http://zakladka.kiev.ua
WC Version:		2.5.5
Log Directory Writable:		✔ /home/zakladka/public_html/wp-content/uploads/wc-logs/
WP Version:		4.5
WP Multisite:		–
WP Memory Limit:		256 MB
WP Debug Mode:		–
Language:		uk
Server Environment
Server Info:		Protected by COMODO WAF
PHP Version:		5.6.18
PHP Post Max Size:		8 MB
PHP Time Limit:		30
PHP Max Input Vars:		1000
SUHOSIN Installed:		–
MySQL Version:		5.5.44
Max Upload Size:		2 MB
Default Timezone is UTC:		✔
fsockopen/cURL:		 ✔
SoapClient:		 ✔
DOMDocument:		 ✔
GZip:		 ✔
Multibyte String:		 ✔
Remote Post:		 ✔
Remote Get:		 ✔
Database
WC Database Version:		2.5.5
woocommerce_sessions	 	✔
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (9)
All In One SEO Pack	 	by Michael Torbert – 2.3.4.1
iThemes Security	 	by iThemes – 5.3.6
Cyr to Lat enhanced	 	by Sol, Sergey Biryukov, Nikolay Karev, Dmitri Gogelia – 3.5
Duplicator	 	by LifeInTheGrid – 1.1.6
Google XML Sitemaps	 	by Arne Brachhold – 4.0.8
Saphali Woocommerce Russian	 	by Saphali – 1.6.2
Page Builder by SiteOrigin	 	by SiteOrigin – 2.4.6
WooCommerce Multilingual	 	by OnTheGoSystems – 3.7.12
WooCommerce	 	by WooThemes – 2.5.5
Settings
Force SSL:		–
Currency		UAH (грн.)
Currency Position		right_space
Thousand Separator		,
Decimal Separator		.
Number of Decimals		0
API
API Enabled:		✔
API Version:		3.1.0
WC Pages
Shop Base:		#26 - /shop/
Cart:		#27 - /cart/
Checkout:		Page does not contain the shortcode: [woocommerce_checkout]
My Account:		Page visibility should be public
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Vantage
Version:		1.4.4
Author URL:		http://siteorigin.com/
Child Theme:		✕ – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		✔
Templates
Overrides:

**Comment by claudiosmweb** [comment]
Yes its removed. Please have a read of https://docs.woothemes.com/document/woocommerce-localization/
