### ISSUE TITLE
Linking woocommerce to a backend database

### ISSUE THREAD

**Issue by Creativeminds-chris** [woothemes/woocommerce#10803]
At the moment I am creating a online store that is using woocommerce. I am then linking it into a backend Database that requires there to be no decimal point. e.g. $45.00 to $4500

Is there a way to do this?

**Comment by mikejolley** [comment]
Why is this being requested here?

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support

You need to create a bridge between the two. Linking to a custom DB is not a feature provided in core.
