### ISSUE TITLE
Shipping Zones: Support postal codes with and without spaces for Canada

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/woocommerce#10808]
Example:
- Set up a shipping zone for just British Columbia
- Limiting postal codes works using spaces like `V0E 1B2` but it doesn't work without spaces `V0E1B2`
- It also doesn't work when you add both with and without spaces

Stores usually either require you to have a space, or to not have a space, which is annoying.  It would be great if WooCommerce could support both! 😄

**Comment by claudiosmweb** [comment]
Theoretically we support both, but seems to have a bug on it.

**Comment by claudiosmweb** [comment]
Yep, we force to have an space: https://github.com/woothemes/woocommerce/blob/fa30a38c58373d9c3706cc0b7ae22032de3a2985/includes/wc-formatting-functions.php#L622-L638

But we let people save without an space in the admin.

**Comment by mikejolley** [comment]
Zone should strip all formatting before running comparisons.

**Comment by claudiosmweb** [comment]
@mikejolley I tested and don't works.

**Comment by mikejolley** [comment]
I know :p just saying what it needs to do.
