### ISSUE TITLE
Error codes on Woo Stripe payment gateway only generate Zip Code error for any error

### ISSUE THREAD

**Issue by steveneden** [woothemes/woocommerce#10801]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

WOO STRIPE PAYMENT GATEWAY
When testing with Stripe fail test cards available here: https://stripe.com/docs/testing
the only error message generated is: Error: "The zip code you supplied failed validation."
and not the error it is failing for eg expired_card, incorrect_cvc.

Some of the test cards used and the same Zip error message http://imgur.com/a/BWXVr

Expected correct error message to be generated from the code returned by Stripe.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

Use the test payment cards that fail for different reasons at: https://stripe.com/docs/testing

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://www.vegpeople.org.uk
Site URL: https://www.vegpeople.org.uk
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18 (Unix)
PHP Version: 5.3.28 - We recommend a minimum PHP version of 5.4. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.47
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ 
						
							 No
Subscriptions Mode: ✔ 
						
							 Live

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (18) ###

Better Search Replace: by Expanded Fronts – 1.2.9
Child Theme Configurator: by Lilaea Media – 2.0.2
Code Snippets: by Shea Bunge – 2.6.1
Easy Twitter Feed Widget: by DesignOrbital.com – 0.5
Elegant Themes Updater: by Elegant Themes – 1.2
MailChimp for WordPress: by ibericode – 3.1.6
Post Snippets: by Johan Steen – 2.5.3
Really Simple SSL: by Rogier Lankhorst – 2.3.3
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
TinyMCE Advanced: by Andrew Ozz – 4.3.8
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.4

WooCommerce Stripe Gateway: by WooThemes – 2.6.12
WooCommerce Memberships: by WooThemes / SkyVerge – 1.5.4
WooCommerce Subscriptions: by Prospress Inc. – 2.0.13
WooCommerce: by WooThemes – 2.5.5
Wordfence Security: by Wordfence – 6.1.4
WP All Export Pro: by Soflyy – 1.2.3
WP Crontrol: by John Blackbourn & Edward Dale – 1.3

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Divi Child
Version: 2.7.1.1461660715
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.7.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/checkout/thankyou.php
`

**Comment by claudiosmweb** [comment]
Not the right place to talk about the "WOO STRIPE PAYMENT GATEWAY", since here is for WooCommerce core issues only.

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

**Comment by mikejolley** [comment]
Also, the stripe error codes are not hardcoded in the plugin - they come directly from stripe. So if thats the error, thats the error they are giving you back.

**Comment by teammartinmiller** [comment]
I recently moved a Woocommerce site from one server to another by cloning it. Everything works great except I get this error too. So it's not necessarily a Stripe issue.
