### ISSUE TITLE
Variable Product Stopped Working

### ISSUE THREAD

**Issue by Barry1967** [woothemes/woocommerce#10802]
I have disabled all plugins and changed the theme. After logging in my first product as a Simple Product and adding the price I needed to add sizes. Changed it to a variable product. This now displays fine. I then added two new products. If I add a Variable Product then the price will not display nor will the attributes. It just loads 'choose an option' but does not allow selection.
On the inside of the backend if I have a variable product there is nowhere to add a price. Even on the first product I added, the price does not display unless I change it to a simple product. If I then switch back to variable product it just shows the SKU?? Not sure what's going on and why one product loads fine and then the rest don't. I've added an image so you can see the Variable Product general tab.

Thanks
Barry

![price](https://cloud.githubusercontent.com/assets/18698052/14848847/ab59c552-0c67-11e6-8f68-8900fc40d21f.png)

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/wp-45-javascript-errors-please-choose-product-options-etc?replies=1
