### ISSUE TITLE
[API] Filter by multiple IDs or SKUs

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10804]
Hi,
is it possible to get products filtered by multiple IDs or SKUs?

i.e: `'filter[sku]' => 'sku1,sku2,sku3' ` or `'filter[id]' => '123,456,789' `

Cheers,
Adis

**Comment by mikejolley** [comment]
No, this currently supports 1 sku only. v3 API won't be enhanced to cover this since we're working on the new rest API here https://woocommerce.wordpress.com/2016/04/22/new-rest-api-based-on-the-wp-rest-api-in-2-6/

**Comment by dipeshparashar** [comment]
By any chance is it possible now ?

**Comment by jpkleemans** [comment]
Looks like you can filter by multiple SKUs using comma-separated values: `/products?sku=SKU01,SKU02`

**Comment by claudiosanches** [comment]
We started to support it into your new REST API v2: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by ad-on-is** [comment]
![image](https://user-images.githubusercontent.com/9553253/36526185-813be540-17ad-11e8-827e-82ad71d4ee5d.png)
Maybe you should update the docs to something like:

Limit result set to products with specific SKUs (Comma separated).

**Comment by fahmifan** [comment]
Is it possible to filter using product id? 
i tried with /products?id=1,3,5 not working. It list all the products available
