### ISSUE TITLE
[2.6] Cart AJAX - nothing happens when clicking the apply coupon button in Safari

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#10813]
In Safari document.activeElement which is used by [cart.js](https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/cart.js#L272) returns body when clicking the apply coupon button. Therefore no action is taken. The simplest solution seems to be adding a click handler to the button.

**Comment by coderkevin** [comment]
Created fix for this issue. Thanks for the submission!
