### ISSUE TITLE
API Woocommerce email not sending after create order by API

### ISSUE THREAD

**Issue by divyasevenstar** [woothemes/woocommerce#10817]
Hello, 

   I have used woocommerce API for create order. But I have face one problem of email sending to customer and admin when create order in woocommerce v3 API. 

   Can you please help me? email is integrate in woocommerce v3 API?

   I have use Woocommerce = 2.5.3 version 
                    woocommerce API = 3.1.0 version 

 If email not integrate, then how can i send website email template when create order by API.

  please help me, I have appreciate with your help.

Thanks
 Divya

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/email-not-send-to-admin-customer-when-create-order-by-woocommerce-api-v3?replies=1
