### ISSUE TITLE
No undo option once item has been removed from the cart if there was only 1 item

### ISSUE THREAD

**Issue by seb86** [woothemes/woocommerce#10816]
## EXPLANATION OF THE ISSUE

Tested on 2.6.0 Beta 1 on a local install. If you only have 1 item in the cart and you remove it, there is no undo option.

## STEPS TO REPRODUCE THE ISSUE

1. Add any item to the cart
2. Go to the cart page
3. Remove the item

You should then see your cart empty but there is no notification to ask the customer if they wish to undo this action. This should be working no matter how many items are in you cart.

It works fine with 2 or more but once there is only 1 item left it doesn't do it.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://localhost/dev
Site URL: http://localhost/dev
WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2-alpha-37312
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7
PHP Version: ❌ 5.4.7 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 256 MB
PHP Time Limit: 6000
PHP Max Input Vars: 1000
CURL Version: 7.24.0
OpenSSL/1.0.1c

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.27 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
PHP Post Max Size: ✔

### Active Plugins (36) ###

Query Monitor: by John Blackbourn – 2.10.0
AffiliateWP: by Pippin Williamson and Andrew Munro – 1.7.14
AffiliateWP - Affiliate Product Rates: by Pippin Williamson and Andrew Munro – 1.0.4
AffiliateWP - Affiliate Product Tags: by Sébastien Dumont – 1.0.1
Airplane Mode: by Andrew Norcross – 0.0.6
Debug Bar Extender: by Thorsten Ott
Automattic – 0.5

Debug Bar: by wordpressdotorg – 0.8.4
Postmatic - WordPress Subscriptions & Commenting by Email: by Postmatic – 1.4.13
Rewrite Rule Testing: by Matthew Boynes – 0.1.1
Simply Show Hooks: by  – 1.1.1
Storefront Beta Tester: by Sébastien Dumont – 1.0.2
Vulnerable Plugin Checker: by Storm Rockwell – 0.2.2
What The File: by Never5 – 1.5.2
WooCommerce Beta Tester: by Mike Jolley – 1.0.1
WooCommerce Bookings: by WooThemes – 1.9.1 – 1.9.7 is available
WooCommerce Chained Products: by Store Apps – 2.3.5 – 2.4 is available
WooCommerce Composite Products: by WooThemes – 3.4.3 – 3.6.4 is available
WooCommerce Dev Helper: by SkyVerge – 0.3.0
WooCommerce Mix and Match: by WooThemes – 1.0.9 – 1.1.3 is available
WooCommerce One Page Checkout: by Prospress Inc. – 1.2.4 – 1.2.6 is available
WooCommerce Product Bundles - Min/Max Items: by SomewhereWarm – 1.0.1
WooCommerce Product Bundles - Tabular Layout: by SomewhereWarm – 1.0.1
WooCommerce Product Bundles: by WooThemes – 4.11.5 – 4.14.2 is available
WooCommerce Skip One: by Sébastien Dumont – 1.0.0
WooCommerce Software Add-On: by WooThemes – 1.6.1 – 1.6.2 is available
WooCommerce Stellar Gateway: by Prospress
Inc. – 1.0.2

WooCommerce Subscribe to All the Things: by Prospress – 1.0.4
WooCommerce Subscriptions: by Prospress Inc. – 2.0.12 – 2.0.13 is available
WooCommerce Variation Swatches and Photos: by Lucas Stark – 2.1.4
WooCommerce: by WooThemes – 2.6.0-beta-1
WordPress Beta Tester: by Peter Westwood – 1.0.1
WordPress Importer: by wordpressdotorg – 0.6.1
WP Job Manager: by Automattic – 1.25.0
WP Notification Center: by Never5 – 1.0.1
WP Rollback: by WordImpress – 1.3
WPForms Lite: by WPForms – 1.1.7

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: 7 - /shop/
Cart: 8 - /cart/
Checkout: 9 - /checkout/
My Account: 10 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Storefront
Version: 2.0.0
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@jameskoster why are notices in storefront wrapped in a separate .woocommerce div?
