### ISSUE TITLE
Adding product variation to cart with Ajax also adds the parent product

### ISSUE THREAD

**Issue by borisdiakur** [woothemes/woocommerce#10810]
My code below works (with no changes in the backend) except that it not only adds the product variation to the cart, but it additionally adds the same quantity of the parent (variable) product as if it was a simple product.

    element.on('click', 'button[type="submit"]', event => {
        event.preventDefault();

        const quantity = parseInt(element.find('input[name="quantity"]').val(), 10) || 1;
        const addToCartUrl = '/shopping-basket/?wc-ajax=add_to_cart';
        let xWWWFormUrlencodedData = `quantity=${quantity}`;

        switch (scope.singleCopy.type) {
            case 'variable': {
                if (scope.selectedVariation) {
                    for (const attr of scope.selectedVariation.attributes) {
                        xWWWFormUrlencodedData += `&attribute_pa_${attr.slug}=${attr.option}`;
                    }
                    xWWWFormUrlencodedData += `&add-to-cart=${scope.singleCopy.id}`;
                    xWWWFormUrlencodedData += `&product_id=${scope.singleCopy.id}`;
                    xWWWFormUrlencodedData += `&variation_id=${scope.selectedVariation.id}`;
                }
                break;
            }
            case 'simple': {
                xWWWFormUrlencodedData += `&product_id=${scope.singleCopy.id}`;
                break;
            }
            default: {
                console.error(`Unknown product type ${scope.singleCopy.type}.`); //eslint-disable-line no-console
            }
        }

        $http.post(addToCartUrl, xWWWFormUrlencodedData, {
            withCredentials: true,
            headers: {
                'Cache-Control': 'no-cache',
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                Pragma: 'no-cache'
            }
        }).success(result => {
            if (result.error) {
                console.warn('The product has been added to the cart despite that the result object indicates an error!');
                // TODO: handle error
                return;
            }
            console.log('Success.', result);
            $rootScope.$broadcast('/cart/update/add');
        }).catch(data => {
            console.error(data);
            // TODO: handle error
        });

    });

If I do not send the `product_id`, only the variable product with the selected variation is added to the cart (great!), BUT the result object indicates an error (with no description). If I then navigate to the cart page I get another error message in the ui: “Sorry, this product cannot be purchased.” Must be due to the parent product not having a price.

**Comment by mikejolley** [comment]
The built in ajax add to cart endpoint only handles simple products. It does not pass full variation data and thus won't add to cart correctly. You'll need your own ajax endpoint to facilitate this.

Note, variations cannot be added to cart without the attribute data being set, and a matching variation ID.

**Comment by borisdiakur** [comment]
@mikejolley In my cart I see the variation added and I can checkout and see the order correctly. So it works for me, although not officially supported or intended. The only side-effect that bothers me is the error message and the fact, that the endpoint does not support variable products officially. Seems to me that this officially missing feature is not too hard to implement. So, would you consider this issue as a feature request?

**Comment by mikejolley** [comment]
No since it's not supported for a reason right now - you cannot have variation add to cart link sin archives (where ajax add to cart is found) because a) you don't have the full variations form, and b) variations are not listed, variable products are

**Comment by borisdiakur** [comment]
Thanks @mikejolley for your feedback so far.
I understand the reason though a) and b) don’t count for me because I have a custom single page theme which performs the ajax calls. What's missing is a simple ajax endpoint for adding variations to the cart. The one you said I could build by myself. If you think my feature request is out of scope, can you please give me an advise on how to implement that custom endpoint in an upgrade safe way? And I promise I will let this issue rest in peace.

**Comment by mikejolley** [comment]
The AJAX endpoints can be added from anywhere; plugin, theme functions. It's just a function hooked into an action - no need to edit core.

**Comment by borisdiakur** [comment]
I've managed to accomplish what I wanted using a custom endpoint derived from http://stackoverflow.com/a/27278035/601466
@mikejolley Again thanks a lot!

**Comment by isaaclubow** [comment]
@borisdiakur what is the `get_variation_data_from_variation_id` function referring to?
