### ISSUE TITLE
Filter on $show_sku in email order items or not be dependent on $sent_to_admin

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#10812]
On email-order-details.php the $order->email_order_items_table function is called with 'show_sku' = $sent_to_admin on the arguments array.

This ties showing up the SKU on emails to the fact that the email is sent to the admin.

There might be stores where it's important to show the SKU on customer emails.

So I propose that either this is completely untied from $sent_to_admin or that a filter is applied to $show_sku on email-order-items.php so that the "false" (from $sent_to_admin) can be overridden at a plugin or theme level and the SKU shown on customer emails.

**Comment by mikejolley** [comment]
In what situation would the SKU (stock keeping unit) be relevant to the customer?

**Comment by webdados** [comment]
Why shouldn't it be relevant? I can think on a lot of areas where the SKU / Reference is very important, like electronics.

If you google "woocommerce show sku" you'll find A LOT of people wanting to include SKU on catalog or product pages, so why not on emails?

Here's an example of a massive retailer that shows SKU to the customer: https://www.velleman.eu/
Even Amazon shows it's ASIN code.

**Comment by tedventures** [comment]
Situations where SKU (or as some say 'part number') is relevant to the customer:

When the customer is channel partner (dealer, distributor, etc), they often order multiple items on a single sales order.  The channel partner may have an internal accounting/ERP system for tracking their own inventory and generating purchase orders they may wish to send to the WooCommerce store (by fax, email, or via API). SKUs (or part numbers) are mandatory.
 
If the product is highly configurable or variable, distinct SKUs help disambiguate line items in the sales order and fulfillment process. Without the SKU, you may be forced to create overly complex or lengthy product descriptions which clutter up emails, sales orders, acknowledgements, etc. and increase error rates.

I suspect most retail customers who see simple products offered on WooCommerce stores don't care about SKUs, so your skepticism is warranted.  However, we too need access to the SKU field for 'customer' emails, etc.

Thanks.

**Comment by webdados** [comment]
Any developments / decision on this?

**Comment by mikejolley** [comment]
The issue is logged, please don't bump it.
