### ISSUE TITLE
Using figure instead of div

### ISSUE THREAD

**Issue by craigralston** [woothemes/woocommerce#10824]
Shouldn't the primary product image container be a `figure` (a semantic element) instead of a `div`? While writing a custom variation product template, I had changed `<div class="images">` to `<figure class="col1 images">` as I believe this is the correct way to mark up images in a semantic-friendly way.

This caused some issues as WC is very specific when using selectors in add-to-cart-variation.js. 
Example: `$product_img      = $product.find( 'div.images img:eq(0)' ),`

I have since reverted it back to a `div` instead of trying to track down all the core files depending on that and loading in my own.

**Comment by WPprodigy** [comment]
A change like this will likely break a lot of extensions that have anything to do with the images. Additional Variation Images, Cloud Zoom, tons of themes, etc.

I'm not against semantic markup, but not sure it is worth the breakage. Maybe 3.0?

**Comment by jameskoster** [comment]
@WPprodigy it would only break if they target `div.images` specifically. Most would just use `.images`, no?

**Comment by WPprodigy** [comment]
Yes, assuming that most do just use .images. Looking at one of our extensions though, that doesn't seem to be the case: https://github.com/woothemes/woocommerce-image-zoom/blob/b96e93cbad3da64abddc4ccc2ea35c3eb15477f2/lib/woocomm-professor-cloud-script-two.js#L522

I'm thinking Javascript will be the biggest break, followed by CSS problems in themes.

**Comment by WPprodigy** [comment]
Since https://github.com/woothemes/woocommerce/issues/10721 will likely require these plugins/themes to make some changes, maybe this could be bundled with that big change?

**Comment by jameskoster** [comment]
Yup, would make sense to do that at the same time. Don't think it needs to be 3.0 though. 2.7 should be fine.

**Comment by juanfra** [comment]
In addition, I assume adding a `<figure>` wrapper to the images in `product-thumbnails.php` and `woocommerce_get_product_thumbnail()` would be the right thing to do.

**Comment by jameskoster** [comment]
Yup, we should review anywhere we display images.

**Comment by jameskoster** [comment]
Closing this in favour of https://github.com/woothemes/woocommerce/issues/10721
