### ISSUE TITLE
Out of Stock dashboard notification

### ISSUE THREAD

**Issue by sandrahe** [woothemes/woocommerce#10826]
Hey there,

trying to resolve an issue with permanently deleted out of stock products. Replicated this issue on a live site as well local hosted development environment. 
The issue is not at all connected to a plugin or theme - deactivated everything to test.
Deleting WooCommerce along with data & reinstalling doesn't fix anything.

## EXPLANATION OF THE ISSUE

Woocommerce version: 2.5.5
WordPress version: 4.5.1

Permanently deleted products which were out of stock show:

- as a notification in out of stock field in dashboard Woocommerce status

- if you click on out of stock a list would show with no product item on it, preventing to manage stock or do anything at all with the stock issue

## STEPS TO REPRODUCE THE ISSUE

1. Set a product and make it out of stock
Enable stock management at product level - checked
Stock Qty
0
Allow Backorders > Do not allow
Stock status > Out of stock
2. Permanently delete the out of stock product
3. Notification will remain in the Dashboard > Woocommerce status that there still is an out of stock product. If you click on the amount of stock to be managed you'll be lead to Reports > Out of Stock. 

## SYSTEM STATUS REPORT

WordPress Environment
Home URL:		http://localhost
Site URL:		http://localhost
WC Version:		2.5.5
Log Directory Writable:		✔ D:\projects\genesis/wp-content/uploads/wc-logs/
WP Version:		4.5.1
WP Multisite:		–
WP Memory Limit:		256 MB
WP Debug Mode:		–
Language:		en_US
Server Environment
Server Info:		Microsoft-IIS/10.0
PHP Version:		7.0.3
PHP Post Max Size:		8 MB
PHP Time Limit:		30
PHP Max Input Vars:		1000
SUHOSIN Installed:		–
MySQL Version:		5.7.12
Max Upload Size:		2 MB
Default Timezone is UTC:		✔
fsockopen/cURL:		 ✔
SoapClient:		 ✔
DOMDocument:		 ✔
GZip:		 ✔
Multibyte String:		 ✔
Remote Post:		 ✔
Remote Get:		 ✔
Database
WC Database Version:		2.5.5
woocommerce_sessions	 	✔
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (9)
Contact Form 7	 	by Takayuki Miyoshi – 4.4.1
Genesis Connect for WooCommerce	 	by StudioPress – 0.9.8
WPBakery Visual Composer	 	by Michael M - WPBakery.com – 4.11.2.1
Revolution Slider	 	by ThemePunch – 5.1
WOOF - WooCommerce Products Filter	 	by realmag777 – 1.1.4.1
WooCommerce	 	by WooThemes – 2.5.5
YITH WooCommerce Quick View	 	by YITHEMES – 1.1.1
YITH WooCommerce Wishlist	 	by YITHEMES – 2.0.15
Settings
Force SSL:		–
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		✔
API Version:		3.1.0
WC Pages
Shop Base:		#266 - /index.php/shop-2/
Cart:		#5 - /index.php/cart/
Checkout:		#270 - /index.php/checkout-2/
My Account:		#272 - /index.php/my-account-2/
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Divine Theme
Version:		1.0.4
Author URL:		http://www.restored316designs.com/
Child Theme:		✔
Parent Theme Name:		Genesis
Parent Theme Version:		2.2.7
Parent Theme Author URL:		http://www.studiopress.com/
WooCommerce Support:		✔

**Comment by mikejolley** [comment]
This appears fixed in master. 

Steps I took:

- Created new out of stock product
- Checked dashboard - it was included in count
- Trashed and deleted product
- Checked dashboard - count was reduced by one.

Seems it may have been transient related but should be fixed in 2.6.

**Comment by enyoneugenius** [comment]
We still have 8 deleted products showing up in Out of stock items. It there any way to remove those?

**Comment by phippselectronics** [comment]
Currently have the same issue too. items don't exist in the database nor do the product pages exist, but under out of stock it lists 9 blank items which can't be removed or edited.
