### ISSUE TITLE
Re-funds are handled incorrectly (issue with proper book keeping)

### ISSUE THREAD

**Issue by cordvision** [woothemes/woocommerce#10820]
If a partial refund is made, the original order total get's crossed out and a new order total with the refund amount deducted from it gets displayed. This is just wrong in terms of book keeping and can lead to issues. 
Here's an example: Let's say the original order was $40 for product A and $10 for shipping. The order total is $50. If I now decided to reduce the shipping to $5 and give the customer a $5 refund, it calculates the order total as follows: Product A $50 plus shipping $5 - re-fund $5 = $40 (order total). This is obviously wrong, the order total should be $45. Hope this makes sense. If done correctly, re-funds should not have any influence on the order total. The correct way would be as follows: If a payment is made, it should just show up right underneath the order total (without influencing it) and you could have another line that reads "balance" which is calculated by subtracting the payment from the order total. If a refund is made, a line gets added that lists the refund (again, it has no influence on the "order total"). However, it affects the balance. This would ensure that everything gets displayed correctly in the case I made in the beginning. Since I reduced the shipping by $5, the order total would read $45, which is correct, and the outstanding balance would still read $0 since I also adjusted the amount paid. Hope this makes sense.

**Comment by mikejolley** [comment]
If you REDUCE the shipping by 5, you're not refunding, your changing the values of an existing order.

Correct way: https://dl.dropboxusercontent.com/s/nu74rda8lmf5w7s/2016-04-29%20at%2011.29.png?dl=0

Result: https://dl.dropboxusercontent.com/s/7yr3697of43r3lw/2016-04-29%20at%2011.44.png?dl=0

**Comment by cordvision** [comment]
Ok, that works in this specific case. However, how would it work in this case:
If you add a discount (not by product, but just as a specific amount) as the order is already processing. I usually just add the discount as another product item that I name "Discount" and use a negative value like -10. If I do that, I run into the issue described above. How would you add a $10 discount and process a re-fund without messing up the order?

**Comment by mikejolley** [comment]
If you're doing it after the fact, just leave the totals as is and issue the refund.

**Comment by cordvision** [comment]
But that creates an accounting problem. You have an invoice and the total of the items listed don't match the money you have in your bank account. For the accounting, you need to be able to connect the re-fund amount with a line item that reads "discount". This is needed to do accounting properly. It's also important if you get audited. The proper way would be to have all the payments listed, as well as the re-funds, and a "outstanding balance" line that takes the order total minus payments plus re-funds.

**Comment by cordvision** [comment]
One more thing: Also, by just looking at the invoice, you don't know what the re-fund was for. You won't know if it was a partial shipping re-fund, a reduction because of defective product etc. Sure, you could make a note, but if the customer just looks at the print out of the invoice at a later point in time he has no idea what the re-fund was for.

**Comment by mikejolley** [comment]
If the user paid and you discount after that, you refund the difference. The money in your bank account matches this fine. I don't understand your problem with this.
