### ISSUE TITLE
New Customer Order Treated As Guest via REST API

### ISSUE THREAD

**Issue by putuyoga** [woothemes/woocommerce#10829]
## EXPLANATION OF THE ISSUE
Customer's Order creation from REST API treated as guest not as customer. I already assign the customer_id and what the results? 

the JSON return order data with customer_id = 0, and customer object = null, Also i look at WP Dashboard, that order created by Guest (on customer field) not the customer who created it.

Version: 2.5.5

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. Just create normally like this:_ http://woothemes.github.io/woocommerce-rest-api-docs/?shell#create-an-order_, with customer_id isn't 0.
2. And look at json result, the customer_id = 0, and the customer object = null. 
3. Also look at Wordpress Dashboard at the newly created order, look at field Customer, it say "guest".

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://frenzshop.com
Site URL: http://frenzshop.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 55 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.46
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✕ Your server does not support the gzopen function - this is required to use the GeoIP database from MaxMind. The API fallback will be used instead for geolocation.
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (18) ###

Akismet: by Automattic – 3.1.9
Contact Form 7 Datepicker: by Aurel Canciu – 2.5.2
Contact Form 7: by Takayuki Miyoshi – 4.4.1
JSON API User: by Ali Qureshi – 2.2
JSON API: by Dan Phiffer – 1.1.1
MyOngkir: by eezhal – 1.0.1
WP REST API: by WP REST API Team – 2.0-beta13
s2Member Framework: by s2Member / WebSharks
Inc. – 160303

Page Builder by SiteOrigin: by SiteOrigin – 2.3.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.5.9
W3 Total Cache: by Frederick Townes – 0.9.4.1
WooCommerce: by WooThemes – 2.5.5
WordPress Social Login: by Miled – 2.3.0
WP Live Chat Support: by WP-LiveChat – 6.1.00
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
YITH WooCommerce Ajax Search: by Yithemes – 1.3.9
YITH WooCommerce Compare: by Yithemes – 2.0.6
YITH WooCommerce Wishlist: by Yithemes – 2.0.14

### Settings ###

Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: StyleShop
Version: 1.6
Author URL: http://www.elegantthemes.com
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: StyleShop/woocommerce/archive-product.php
StyleShop/woocommerce/auth/footer.php
StyleShop/woocommerce/auth/form-grant-access.php
StyleShop/woocommerce/auth/form-login.php
StyleShop/woocommerce/auth/header.php
StyleShop/woocommerce/cart/cart-empty.php
StyleShop/woocommerce/cart/cart-item-data.php
StyleShop/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/cart/cart-totals.php
StyleShop/woocommerce/cart/cart.php
StyleShop/woocommerce/cart/cross-sells.php
StyleShop/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/cart/proceed-to-checkout-button.php
StyleShop/woocommerce/cart/shipping-calculator.php
StyleShop/woocommerce/checkout/cart-errors.php
StyleShop/woocommerce/checkout/form-billing.php
StyleShop/woocommerce/checkout/form-checkout.php
StyleShop/woocommerce/checkout/form-coupon.php
StyleShop/woocommerce/checkout/form-login.php
StyleShop/woocommerce/checkout/form-pay.php version 1.6.4 is out of date. The core version is 2.5.0
StyleShop/woocommerce/checkout/form-shipping.php
StyleShop/woocommerce/checkout/payment-method.php
StyleShop/woocommerce/checkout/payment.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/checkout/review-order.php
StyleShop/woocommerce/checkout/thankyou.php
StyleShop/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/content-product_cat.php version 2.4.0 is out of date. The core version is 2.5.2
StyleShop/woocommerce/content-single-product.php
StyleShop/woocommerce/content-widget-product.php version - is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/admin-cancelled-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-invoice.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-new-account.php
StyleShop/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-processing-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-refunded-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/customer-reset-password.php
StyleShop/woocommerce/emails/email-addresses.php
StyleShop/woocommerce/emails/email-footer.php
StyleShop/woocommerce/emails/email-header.php
StyleShop/woocommerce/emails/email-order-items.php
StyleShop/woocommerce/emails/email-styles.php
StyleShop/woocommerce/emails/plain/admin-cancelled-order.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/admin-new-order.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-completed-order.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-invoice.php version 2.2.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-new-account.php
StyleShop/woocommerce/emails/plain/customer-note.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-processing-order.php version 2.3.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-refunded-order.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/emails/plain/customer-reset-password.php
StyleShop/woocommerce/emails/plain/email-addresses.php
StyleShop/woocommerce/emails/plain/email-order-items.php
StyleShop/woocommerce/global/breadcrumb.php
StyleShop/woocommerce/global/form-login.php
StyleShop/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/global/sidebar.php
StyleShop/woocommerce/global/wrapper-end.php
StyleShop/woocommerce/global/wrapper-start.php
StyleShop/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/loop/loop-end.php
StyleShop/woocommerce/loop/loop-start.php
StyleShop/woocommerce/loop/no-products-found.php
StyleShop/woocommerce/loop/orderby.php
StyleShop/woocommerce/loop/pagination.php
StyleShop/woocommerce/loop/price.php
StyleShop/woocommerce/loop/rating.php
StyleShop/woocommerce/loop/result-count.php
StyleShop/woocommerce/loop/sale-flash.php
StyleShop/woocommerce/myaccount/form-add-payment-method.php
StyleShop/woocommerce/myaccount/form-edit-account.php version 2.2.7 is out of date. The core version is 2.5.1
StyleShop/woocommerce/myaccount/form-edit-address.php
StyleShop/woocommerce/myaccount/form-login.php
StyleShop/woocommerce/myaccount/form-lost-password.php
StyleShop/woocommerce/myaccount/my-account.php
StyleShop/woocommerce/myaccount/my-address.php
StyleShop/woocommerce/myaccount/my-downloads.php
StyleShop/woocommerce/myaccount/my-orders.php version 2.3.10 is out of date. The core version is 2.5.0
StyleShop/woocommerce/myaccount/view-order.php
StyleShop/woocommerce/notices/error.php
StyleShop/woocommerce/notices/notice.php
StyleShop/woocommerce/notices/success.php
StyleShop/woocommerce/order/form-tracking.php
StyleShop/woocommerce/order/order-again.php
StyleShop/woocommerce/order/order-details-customer.php
StyleShop/woocommerce/order/order-details-item.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/order/order-details.php version 2.4.0 is out of date. The core version is 2.5.3
StyleShop/woocommerce/order/tracking.php
StyleShop/woocommerce/product-searchform.php version - is out of date. The core version is 2.5.0
StyleShop/woocommerce/single-product/add-to-cart/external.php
StyleShop/woocommerce/single-product/add-to-cart/grouped.php
StyleShop/woocommerce/single-product/add-to-cart/simple.php
StyleShop/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/single-product/meta.php
StyleShop/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 2.4.9
StyleShop/woocommerce/single-product/product-attributes.php
StyleShop/woocommerce/single-product/product-image.php
StyleShop/woocommerce/single-product/product-thumbnails.php
StyleShop/woocommerce/single-product/rating.php
StyleShop/woocommerce/single-product/related.php
StyleShop/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.5.0
StyleShop/woocommerce/single-product/sale-flash.php
StyleShop/woocommerce/single-product/share.php
StyleShop/woocommerce/single-product/short-description.php
StyleShop/woocommerce/single-product/tabs/additional-information.php
StyleShop/woocommerce/single-product/tabs/description.php
StyleShop/woocommerce/single-product/tabs/tabs.php
StyleShop/woocommerce/single-product/title.php
StyleShop/woocommerce/single-product/up-sells.php
StyleShop/woocommerce/single-product-reviews.php
StyleShop/woocommerce/single-product.php
StyleShop/woocommerce/taxonomy-product_cat.php
StyleShop/woocommerce/taxonomy-product_tag.php

: Learn how to update outdated templates
`
```

**Comment by putuyoga** [comment]
**temporary solution:**
after create new order, i make an update order api call with the specified customer ID. And the order's customer will be correct.

**Comment by claudiosmweb** [comment]
@putuyoga I just tested API v3 in WooCommerce 2.5.5 and works fine.

In the API we just validate the user ID: https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-orders.php#L435-L446

Then we pass to create a new order using `wc_order_create()`:
https://github.com/woothemes/woocommerce/blob/master/includes/wc-core-functions.php#L51-L127

Try do some tests with your plugins and search for filters removing data when creating an order, because it is working as it should on a clean installation.

**Comment by tafint** [comment]
@claudiosmweb i use api POST order in v3 for create new order but the server only get payment_method,payment_method_title and set_paid, it not get billing,shipping,line_items,shipping_lines info.
data request:
{
          payment_method: "bacs",
          payment_method_title: "Direct Bank Transfer",
          set_paid: true,
          billing: {
            first_name: "John",
            last_name: "Doe",
            address_1: "969 Market",
            address_2: "",
            city: "San Francisco",
            state: "CA",
            postcode: "94103",
            country: "US",
            email: "john.doe@example.com",
            phone: "(555) 555-5555"
          },
          shipping: {
            first_name: "John",
            last_name: "Doe",
            address_1: "969 Market",
            address_2: "",
            city: "San Francisco",
            state: "CA",
            postcode: "94103",
            country: "US"
          },
          line_items: [
            {
              product_id: 427,
              quantity: 2
            }
          ],
          shipping_lines: [
            {
              method_id: "flat_rate",
              method_title: "Flat Rate",
              total: 10
            }
          ]
        }
data response:
{
  "id": 2778,
  "parent_id": 0,
  "status": "pending",
  "order_key": "wc_order_57a1be045d4d1",
  "number": 2778,
  "currency": "VND",
  "version": "2.6.3",
  "prices_include_tax": false,
  "date_created": "2016-08-03T09:48:52",
  "date_modified": "2016-08-03T09:48:52",
  "customer_id": 0,
  "discount_total": "0",
  "discount_tax": "0",
  "shipping_total": "0",
  "shipping_tax": "0",
  "cart_tax": "0",
  "total": "0",
  "total_tax": "0",
  "billing": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": "",
    "email": "",
    "phone": ""
  },
  "shipping": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": ""
  },
  "payment_method": "\"bacs\",",
  "payment_method_title": "\"Direct Bank Transfer\",",
  "transaction_id": "",
  "customer_ip_address": "14.161.38.217",
  "customer_user_agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
  "created_via": "rest-api",
  "customer_note": "",
  "date_completed": "2016-08-03T09:48:52",
  "date_paid": "",
  "cart_hash": "",
  "line_items": [],
  "tax_lines": [],
  "shipping_lines": [],
  "fee_lines": [],
  "coupon_lines": [],
  "refunds": [],
  "_links": {
    "self": [
      {
        "href": "https://mart-tutula1.c9users.io/wp-json/wc/v1/orders/2778"
      }
    ],
    "collection": [
      {
        "href": "https://mart-tutula1.c9users.io/wp-json/wc/v1/orders"
      }
    ]
  }

**Comment by nabaasa** [comment]
Through the REST API for woocommerce, the default order created will be for the guest. This means that the customer ID is 0.
To attach the created order to a customer, please as customer_id field to your order paramters.
data request:
Example using customer ID as 13. Now you can retrieve the orders made for a particular customer using the REST API

{
customer_id=13,
payment_method: "bacs",
payment_method_title: "Direct Bank Transfer",
set_paid: true,
billing: {
first_name: "John",
last_name: "Doe",
address_1: "969 Market",
address_2: "",
city: "San Francisco",
state: "CA",
postcode: "94103",
country: "US",
email: "john.doe@example.com",
phone: "(555) 555-5555"
},
shipping: {
first_name: "John",
last_name: "Doe",
address_1: "969 Market",
address_2: "",
city: "San Francisco",
state: "CA",
postcode: "94103",
country: "US"
},
line_items: [
{
product_id: 427,
quantity: 2
}
],
shipping_lines: [
{
method_id: "flat_rate",
method_title: "Flat Rate",
total: 10
}
]
}

**Comment by AndroPlus** [comment]
> Through the REST API for woocommerce, the default order created will be for the guest. This means that the customer ID is 0.
> To attach the created order to a customer, please as customer_id field to your order paramters.
> data request:
> Example using customer ID as 13. Now you can retrieve the orders made for a particular customer using the REST API
> 
> {
> customer_id=13,
> payment_method: "bacs",
> payment_method_title: "Direct Bank Transfer",
> set_paid: true,
> billing: {
> first_name: "John",
> last_name: "Doe",
> address_1: "969 Market",
> address_2: "",
> city: "San Francisco",
> state: "CA",
> postcode: "94103",
> country: "US",
> email: "[john.doe@example.com](mailto:john.doe@example.com)",
> phone: "(555) 555-5555"
> },
> shipping: {
> first_name: "John",
> last_name: "Doe",
> address_1: "969 Market",
> address_2: "",
> city: "San Francisco",
> state: "CA",
> postcode: "94103",
> country: "US"
> },
> line_items: [
> {
> product_id: 427,
> quantity: 2
> }
> ],
> shipping_lines: [
> {
> method_id: "flat_rate",
> method_title: "Flat Rate",
> total: 10
> }
> ]
> }

Awesome. it worked.

**Comment by rajkumargaur91** [comment]
isnt it a loop hole that anyone can generate the order for any user using third party tools. if he steal the request from browser.

**Comment by rajkumargaur91** [comment]
can I pass the customer id dynamically  to prevent the loop hole

**Comment by kulterryan** [comment]
is the issue resolved?
