### ISSUE TITLE
How to add forcefully apply shipping method product based?

### ISSUE THREAD

**Issue by nishitlangaliya** [woothemes/woocommerce#10823]
@mikejolley @claudiosmweb 

Hope you are doing well.

I have a query regarding adding forcefully shipping method product base. So below is my scenario.

For Example:

1.  I have 3 Products.

- Product Name: Test1
- Product Price: 5
- Shipping method set = Free shipping.

- Product Name: Test2
- Product Price: 10
- Shipping method set = 'Flat rate' cost = 15

- Product Name: Test3
- Product Price: 15
- Shipping method set = International Flat Rate Cost = 10

So now If I have all above product in my cart than I need below functionality:
1. Free shipping should be disable if the product of other shipping method in cart.
2. I need to apply both rest of the shipping method to cart.
1. Flat rate for product Test1.
2. International Flat Rate for Test2

So my  cart should look like below:

SUBTOTAL : 30
Flat rate shipping for Test2: 15
International Flat Rate for Test3 Cost: 10
Total: 55

So how can I achieve this using WooCommerce Hooks and filters. because currently all shipping method available in cart page so user can select any of the method.

Please help me for the same.

Thanks,

**Comment by mikejolley** [comment]
Look into splitting cart items into packages.

https://gist.github.com/mikejolley/347b8f162257f6736c4d

Please don't post support questions here in future.

**Comment by nishitlangaliya** [comment]
@mikejolley 

Thanks for reply :)

Next time I will post it into plugin support.

Thanks again....
