### ISSUE TITLE
General Details in dashboard

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10828]
The dashboard shows Order date & time:
![3](https://cloud.githubusercontent.com/assets/17761830/14940574/5df6f418-0f84-11e6-80e4-8ab975890ccb.png)

is it possible to also add there the **payment date and time**? 
This information is valuable to sellers as most of us start process and count days since the payment.
If we say that delivery is 5 days from order, we actually means it's 5 days from the payment of the order.

**Comment by mikejolley** [comment]
It's stored, just not exposed in the UI https://github.com/woothemes/woocommerce/blob/87dc31ffacbe96b3cdd6b73fcd31f7c77d14631c/includes/abstracts/abstract-wc-order.php#L2449

**Comment by test101test101** [comment]
I know it is stored... I get this information from the database... but it's very inconvenient. 
Why not show it?

**Comment by mikejolley** [comment]
Well this is called from gateways when payment is received. That date cannot change so why make it editable?

**Comment by test101test101** [comment]
don't make it editable, just make it shown.
