### ISSUE TITLE
Hardcoded http on admin bar help links causes "mixed content" warnings for pages using SSL

### ISSUE THREAD

**Issue by skillio** [woothemes/woocommerce#10825]
A minor thing, but the URL's in class-wc-admin-help.php are hardcoded to http, e.g. from line 219:
`'<p><a href="' . 'http://wordpress.org/extend/plugins/woocommerce/' . '" target="_blank">' . __( 'WordPress.org Project', 'woocommerce' ) . '</a></p>'`

Relative protocol links (//docs.woothemes.com/...) should be used to honor SSL pages and eliminate these errors. There are 11 urls like this as of v2.5.5.

**Comment by mikejolley** [comment]
I've never seen an external link cause mixed content. They are not the same as scripts. 

Screenshot your console for proof?

**Comment by skillio** [comment]
![image](https://cloud.githubusercontent.com/assets/4606352/14938111/b55b020a-0ee7-11e6-8fd6-406000d7cf5b.png)

So it's from a form to search the docs. Which I don't see in that file, I'll look elsewhere...

**Comment by skillio** [comment]
Okay, apparently this is caused by the "WooCommerce Admin Bar Addition" plugin injecting a search form into the admin bar, I thought that was the native admin bar. Sorry about that! Closing now.
