### ISSUE TITLE
Special tax on one item in a bundled product/variation taxing the whole product

### ISSUE THREAD

**Issue by BHEADRICK** [woothemes/woocommerce#10821]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

My proposed solution would be to add the product to the WC_Tax::calc_tax function so that the taxable amount per tax class for a given product/variation could be set using the woocommerce_calc_tax filter

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://beta.poolwarehouse.com
Site URL: http://beta.poolwarehouse.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Amazon) OpenSSL/1.0.1k-fips PHP/5.5.33
PHP Version: 5.5.33
PHP Post Max Size: 13 MB
PHP Time Limit: -1
PHP Max Input Vars: 10000
SUHOSIN Installed: –
MySQL Version: 5.5.46
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✕ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (43) ###

Gravity Forms: by rocketgenius – 1.9.18
Add From Server: by Dion Hulse – 3.3.1
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.0.8

AMP: by Automattic – 0.3.2
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Disable Emojis: by Ryan Hellyer – 1.5.1
Email Log: by Sudar – 1.8.2
EWWW Image Optimizer: by Shane Bishop – 2.8.0
Glue for Yoast SEO & AMP: by Joost de Valk – 0.3.2
Google Analytics by MonsterInsights: by MonsterInsights – 5.4.9
Gravity Forms Products AddOn Fix: by Catman Studios – 1.0.0
IgniteWoo Updater: by IgniteWoo – 1.2.2
Network Privacy: by Ron Rennick – 0.1.5
Page Views Count: by A3 Revolution – 1.4.0
Facebook Instant Articles & Google AMP Pages by PageFrog: by PageFrog Team – 1.0.9
Cart Product Feed: by ExportFeed.com – 3.1.4.3
PW Pop Up Sales: by Jeremy Fairbank – 0.0.0
Quote System Administrator: by Author Name – 1.0.0
Quote System: by Adam Ayres – 1.0
Redirection: by John Godley – 2.4.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Responsive Slider: by AlienWP – 0.1.8
Simple Login Log: by Max Chirkov – 1.1.0
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
INC – 1.7.17

Toolset Types: by OnTheGoSystems – 2.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.5.22

Upload Larger Plugins: by David Anderson – 1.2
W3 Total Cache: by Frederick Townes – 0.9.4.1
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Free Shipping Pro: by IgniteWoo.com – 2.2.17
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.5.1 – 3.6.0 is available
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.6
WooCommerce Product Bundles: by WooThemes – 4.14.1 – 4.14.2 is available
WooCommerce Social Buttons PRO: by Terry Tsang – 1.0.5
WooCommerce: by WooThemes – 2.5.5
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.6.2
WordPress Importer: by wordpressdotorg – 0.6.1
Yoast SEO: by Team Yoast – 3.2.3
WP All Export: by Soflyy – 1.0.4
WP Crontrol: by John Blackbourn & Edward Dale – 1.3
WP Responsive Menu: by MagniGenie – 2.0.7

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #9 - /shop/
Cart: #10 - /pool-kit-shopping-cart/
Checkout: #11 - /pool-kit-checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: PW
Version: 2.0
Author URL: 
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: pw/woocommerce/emails/email-addresses.php
pw/woocommerce/order/order-details-customer.php

`

**Comment by mikejolley** [comment]
If this is a bundle specific calculation issue, use support.woothemes.com. Bundles are not part of core, so it needs feedback from the developer whom can make a request if needed.
