### ISSUE TITLE
Paypal IPN variables

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10832]
Woo commerce allow user to enter a customer message (In Woocommerce  itself) , However the user can also add a comment via PayPal. The variable `memo `is passed with PayPal IPN.
![a44](https://cloud.githubusercontent.com/assets/17761830/14949480/fe40dfa0-1052-11e6-841c-d48bf52f631a.png)

https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/

Currently this variable isn't saved in Woocommerce which makes it difficult to work as in each order we need to check the Paypal email message to see if user left a message there. 

Is it possible that this variable will be saved in WC and also will be presented in dashboard (under the order) ?

**Comment by mikejolley** [comment]
WooCommerce passes 'no_note' => 1 to disable this field. -.- You failed to mention you'd customised this.

**Comment by mikejolley** [comment]
Confirmed. Note is disabled.

If you re-enable this I'd recommend using the action hooks to append this to the WC note field (post excerpt).
