### ISSUE TITLE
products API - how do i you retrieve and view products by product ids in array.

### ISSUE THREAD

**Issue by JosephMendez** [woothemes/woocommerce#10830]
how do i you retrieve and view products by product ids in array.

productids = [1,3,4,5];
http request only allows single product id.

 /wc-api/v3/products/<id>

please enlighten me. thank you.

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This is not possible. If you need a subset of products, use the /product/ endpoint instead.

**Comment by claudiosmweb** [comment]
@JosephMendez you can do it with the filter `in`.

For example:

```
GET /wc-api/v3/products?filter[in]=1,3,4,5
```

**Comment by JosephMendez** [comment]
@claudiosmweb thank you very much

**Comment by JosephMendez** [comment]
@claudiosmweb 

i got error 

oauth_signature_method=HMAC-SHA256&oauth_timestamp=1462639387&filter[in]=379,379,271,370,370&oauth_signature=jR0%2F67FMRk1B3DG20MatdRHMVK%2FdLhrRoCdvc0wsa18%3D
Request Method:GET
Status Code:401 Unauthorized
Remote Address:[::1]:80

**Comment by JosephMendez** [comment]
ok got. 

productsid.replace(/,/g, "%2C");
