### ISSUE TITLE
Fatal Error thrown when running the data updater

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce#10837]
## EXPLANATION OF THE ISSUE

Fatal error is thrown out when running the data updater. The reason for that is class `WC_Shipping_International_Delivery` got renamed to `WC_Shipping_Legacy_International_Delivery` per this https://github.com/woothemes/woocommerce/commit/119f19a5c148d48ebd1688f462b863f91253547f.
However, [includes/updates/woocommerce-update-2.4.php](https://github.com/woothemes/woocommerce/blob/master/includes/updates/woocommerce-update-2.4.php#L29) instantiates old class name `WC_Shipping_International_Delivery`

## STEPS TO REPRODUCE THE ISSUE

Checkout the `master` branch and "data updated" notice should be displayed if you've installed WooCommerce before:

<img width="1494" alt="screen shot 2016-05-02 at 9 18 30 pm" src="https://cloud.githubusercontent.com/assets/78313/14960082/134c8e20-10bd-11e6-8c30-e468ae47f4ee.png">

I ran the data updater and got fatal error:

```
[02-May-2016 16:05:00 UTC] PHP Fatal error:  Class 'WC_Shipping_International_Delivery' not found in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/updates/woocommerce-update-2.4.php on line 29
```

**Comment by jamesgol** [comment]
Also ran into this issue.  The PR resolved the issue
