### ISSUE TITLE
Duplicate rows in download permissions after 'Generate Download Permissions'

### ISSUE THREAD

**Issue by dcelsey** [woothemes/woocommerce#10839]
## EXPLANATION OF THE ISSUE

For an existing order with download permissions, selecting the Generate Download Permissions option in Order Actions (order admin screen) leads to all of the download permissions being duplicated (visible in Downloadable Product Permissions section and , duplicate rows in wp_woocommerce_downloadable_product_permissions, only made unique by the auto-increment permission_id field.)

Because the download handler gets the download data based on product id, order key, email and download id (class-wc-download-handler.php line 35-43) there is no way for the code to differentiate between the rows. On subsequent downloads the original record continues to have the downloaded/downloads remaining updated, while the new record is ignored.

Having an actions to RE-generate the download permissions would be great (I have orders that can have 90 downloadable files so having to reset all the individual permissions when someone exceeds the limit etc isn't very practical). However I think that this action should delete the existing permissions from the table before regeneration.

class-wc-meta-box-order-actions.php contains the lines:

delete_post_meta( $post_id, '_download_permissions_granted' );
wc_downloadable_product_permissions( $post_id );

so it deletes the flag in post _meta to allow regeneration, and the function 

wc_downloadable_product_permissions contains the lines
if ( get_post_meta( $order_id, '_download_permissions_granted', true ) == 1 ) {
return; // Only do this once
}
so it doesn't make sense to delete the flag without also deleting the existing download permissions for the order, especially as the duplicate permissions can't accessed using the current query fields.

## STEPS TO REPRODUCE THE ISSUE

1. Create a product with downloadable files with an download limit
2. Complete an order for that product
3. In the back end select the order and then the order action 'Generate Download Permissions'
4. Looks at the Download section of the order in admin - there are duplicate rows
5. Look at the download permission table - there are rows with the same download it, product id and order id only differentiated by the sequential permission id
6. Repeatedly download the files in the order from the order confirmation screen or email, whilst watching the download count in the back end.  One of the permission rows will be updated while the other one is untouched. Once the first row reaches zero the download expires regardless of the duplicate row.

The most obvious fix to me would be to delete the download permissions for the order just before re-generating them - after the line that deletes the meta-data flag in class-wc-meta-box-order-actions.php :

delete_post_meta( $post_id, '_download_permissions_granted' );

(maybe the action should be renamed to Regenerate Download Permissions).

I am currently achieving this with the following code in functions.php to avoid modifying core files:
add_action ('deleted_post_meta','tctc_delete_download_permissions',10,4);

function tctc_delete_download_permissions ($meta_ids, $object_id, $meta_key, $_meta_value )
{
               //log_me("DELETE PERMISSIONS");
               //log_me($object_id);
               
               if($meta_key == '_download_permissions_granted')
               {
                              global $wpdb;
                              $permissions_table = $wpdb->prefix . "woocommerce_downloadable_product_permissions";

                              $wpdb->delete($permissions_table,array('order_id'=>$object_id),array('%d'));
               }
}

**Comment by mikejolley** [comment]
I think that makes sense for default behaviour.

**Comment by fabrizioschiavi** [comment]
Fixed?

**Comment by dcelsey** [comment]
I believe so!

**Comment by fabrizioschiavi** [comment]
![screenshot_2017-05-11_07-25-09](https://cloud.githubusercontent.com/assets/1576663/26113924/39a0784c-3a5c-11e7-910e-f4c14402949e.png)

**Comment by dcelsey** [comment]
I think I only had this problem when I was using product bundles and the same file could be available from more than one bundle. I did implement a work around for it last year, but then I stopped using bundles so I haven’t thought about it since.
