### ISSUE TITLE
Order marked processing and paid despite PayPal IPN not returning

### ISSUE THREAD

**Issue by dogrescuer** [woothemes/woocommerce#10833]
Client's customer said he had trouble with his browser. He didn't know if his payment went through so he ordered again. 

On the admin side, the order existed, was set to "processing," but no money had transferred from paypal to my client's account.

I'm afraid this has to be a code search issue as it happened on a live site.

My client said "this is very dangerous, we could ship goods for which we haven't been paid."

Apparently the code making an order as "processing" is triggered despite the IPN not returning.

Paypal version is Standard.

The order has no order notes.  

The refund area says "This order has been paid for and is no longer editable." 

There is one line in the paypal log (below) for this event. The arrows point to the order's relevant log entry. Everything else is for context. 

There is no log data, only this one line on 4/27/16.

04-25-2016 @ 18:16:59 - Received valid response from PayPal
04-25-2016 @ 18:16:59 - Found order #323717
04-25-2016 @ 18:16:59 - Payment status: completed
---->>>>04-27-2016 @ 15:38:53 - Generating payment form for order 25422. Notify URL: https://redacted/wc-api/WC_Gateway_Paypal/<<<<----
04-28-2016 @ 04:32:17 - Generating payment form for order 25424. Notify URL: https://redacted/wc-api/WC_Gateway_Paypal/
04-28-2016 @ 04:35:00 - Checking IPN response is valid
04-28-2016 @ 04:35:02 - IPN Request: Array
(
    [body] => Array
        (
            [cmd] => _notify-validate

### WordPress Environment ###
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: 5.4.43
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.6.30
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (41) ###

Gravity Forms: by rocketgenius – 1.9.18
LayerSlider WP: by Kreatura Media – 5.6.2
Ajax Upload for Gravity Forms: by Adrian Gordon – 1.7.4
Advanced Automatic Updates: by pento – 1.0.2
BackWPup: by Inpsyde GmbH – 3.3
Envira Gallery Lite: by Thomas Griffin – 1.5.0
Far Future Expiration Plugin: by Tips and Tricks HQ – 1.3
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.5
Fusion Core: by ThemeFusion – 1.8.3
MailChimp for WordPress: by ibericode – 3.1.6
MailChimp User Sync: by ibericode – 1.4.3
Ozh' Admin Drop Down Menu: by Ozh – 3.6.10
Query Strings Remover: by Atul Kumar Pandey – 1.0
Slider Revolution: by ThemePunch – 5.1.6
Say What? Pro: by Lee Willis – 1.7
Smart Manager: by Store Apps – 3.9.15
Ultimate Social: by WPSmarter – 6.0.0
Woo Search Box: by Guaven Labs – 1.1.0
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 2.9
WooCommerce Auto Restore Stock: by Gerhard Potgieter – 1.0.1
WooCommerce Customizer: by SkyVerge – 2.2.0
WooCommerce Dynamic Gallery LITE: by A3 Revolution – 2.2.1
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.5.1 – 3.6.0 is available
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooThemes – 4.4.2
WooCommerce Jetpack Plus: by Algoritmika Ltd – 1.0.4
Booster for WooCommerce: by Algoritmika Ltd – 2.4.7
WooCommerce Menu Extension: by August Infotech – 1.3
WooCommerce Print Invoices/Packing Lists: by WooThemes / SkyVerge – 3.0.7
WooCommerce Product Reviews Pro: by WooThemes / SkyVerge – 1.4.3
WooCommerce Product SKU Generator: by SkyVerge – 2.1.0
WooCommerce Sequential Order Numbers: by SkyVerge – 1.6.1
WooCommerce UPS Shipping: by WooThemes – 3.1.2
WooCommerce USPS Shipping: by WooThemes – 4.3.2
WooCommerce Smart Coupons: by WooThemes – 3.0.14
WooCommerce WishLists: by Lucas Stark – 1.10.5
WooCommerce: by WooThemes – 2.5.5
WooThemes Helper: by WooThemes – 1.6.2
Yoast SEO Premium: by Team Yoast – 3.2.4
WP SEO HTML Sitemap: by Magna Technology
LLC – 0.9.6

WP Super Simple Speed: by RSPublishing – 1.4.920
ZF WordPress Category Accordion: by ZuFusion – 1.9

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #41145 - /scart/
Cart: #4098 - /cart/
Checkout: #4099 - /checkout/
My Account: #4100 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: child1
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 3.9.3
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: child1/woocommerce/cart/cart.php
child1/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/content-product.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/myaccount/form-edit-address.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php
Avada/woocommerce/single-product-reviews.php

`

**Comment by mikejolley** [comment]
If there are no order notes, that means you have something setting default status to processing. Unless you have pending and processing confused; there is a big difference. 

WC uses pending. 

Only IPN or PDT can update this but order notes get added.

**Comment by dogrescuer** [comment]
Thank you. I see your point. OK this is not a bug.

**Comment by mikejolley** [comment]
👍
