### ISSUE TITLE
Wrong stock status with Allow Backorder combination

### ISSUE THREAD

**Issue by orangeicarus** [woothemes/woocommerce#10834]
## EXPLANATION OF THE ISSUE

Wrong stock status with Allow Backorder combination. The details are below. I expect correct stock status for customers.

## STEPS TO REPRODUCE THE ISSUE

1. Use variable product (for t-hirts), with attributes: size, color, material. Only size is used for variables (M, L, XL, 2XL, 3XL).
2. Set up variable product:
Enabled, SKU, Regular Price
Attention! : Manage Stock = Yes, Stock Qty = 0,  Allow Backorders = Yes + Inform to customer, Stock Status = Not in Stock

FIRST issue
If you save changes or save changes + update all product page then Stock status changes to "In Stock". Which is wrong.
If you open this variable again, change stock status to "Not in Stock" and save this second time then stock status is "In Stock". This is dangerous for all customers, because they possibly see wrong stock information.

SECOND issue
If customer order this product (Manage Stock = Yes, Stock Qty = 0,  Allow Backorders = Yes + Inform to customer, Stock Status = Not in Stock) then Stock Qty is minus and !!! Stock Status is changed to "In Stock". Which is wrong. Other customers then see wrong stock status.

### WordPress Environment ###

Home URL: http://www.elitnirebel.cz
Site URL: http://www.elitnirebel.cz
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: cs_CZ

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.20
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
SUHOSIN Installed: ✔
MySQL Version: 5.6.29
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Vzdálená metoda Post: ✔
Vzdálená metoda Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (31) ###

LayerSlider WP: o Kreatura Media – 5.5.1
Advanced Custom Fields: o Elliot Condon – 4.4.7
Advanced Sidebar Menu: o Mat Lipe – 5.1.4
Akismet: o Automattic – 3.1.10
BackWPup: o Inpsyde GmbH – 3.3
CommerceGurus Toolkit: o CommerceGurus – 1.2.8
Contact Form 7: o Takayuki Miyoshi – 4.4.2
Duplikování: o Enrico Battocchi – 2.6
Envato WordPress Toolkit: o Envato – 1.7.3
Google Analytics by MonsterInsights: o MonsterInsights – 5.5
Insert Headers and Footers: o WPBeginner – 1.3.3
WPBakery Visual Composer: o Michael M - WPBakery.com – 4.11.2
Loco Translate: o Tim Whitlock – 1.5.5
MailChimp pro WordPress: o ibericode – 3.1.6
Redux Framework: o Tým Redux – 3.6.0.2
Regenerate Thumbnails: o Alex Mills (Viper007Bond) – 2.2.6
Say What?: o Lee Willis – 1.7
Simple Photo Gallery: o Tips and Tricks HQ
Peter Petreski – v1.8.1

SumoMe: o SumoMe – 1.10
WooCommerce Conversion Tracking: o Tareq Hasan – 1.2
Woocommerce CSV Import: o Allaerd Mensonides – 3.1.4
WooCommerce Quantity Increment: o WooThemes
Bryce Adams – 1.0.0

WooCommerce Table Rate Shipping: o Bolder Elements – 3.6.4
WooCommerce: o WooThemes – 2.5.5
WooSidebars: o WooThemes – 1.4.3
WordPress Importer: o wordpressdotorg – 0.6.1
Yoast SEO: o Team Yoast – 3.2.4
WP Facebook Pixel: o Night Shift Apps – 3.5
YITH WooCommerce Ajax Product Filter: o YITHEMES – 2.8.1
YITH WooCommerce Ajax Search: o Yithemes – 1.3.9
YITH WooCommerce Badge Management: o YITHEMES – 1.2.8

### Settings ###

Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Sídlo obchodu: #4 - /shop/
Košík: #5 - /cart/
Pokladna: #6 - /checkout/
Můj účet: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Adrenalin Child
Version: 1.0
Author URL: http://www.commercegurus.com
Child Theme: ✔
Parent Theme Name: Adrenalin
Parent Theme Version: 1.9.3
Parent Theme Author URL: http://www.commercegurus.com
WooCommerce Support: ✔

### Templates ###

Overrides: adrenalin/woocommerce/archive-product.php
adrenalin/woocommerce/cart/cart.php
adrenalin/woocommerce/checkout/form-checkout.php
adrenalin/woocommerce/checkout/review-order.php
adrenalin/woocommerce/checkout/thankyou.php
adrenalin/woocommerce/content-product.php
adrenalin/woocommerce/content-product_cat.php
adrenalin/woocommerce/content-single-product.php
adrenalin/woocommerce/global/wrapper-end.php
adrenalin/woocommerce/global/wrapper-start.php
adrenalin/woocommerce/loop/loop-end.php
adrenalin/woocommerce/loop/loop-start.php
adrenalin/woocommerce/loop/orderby.php
adrenalin/woocommerce/loop/pagination.php
adrenalin/woocommerce/loop/result-count.php
adrenalin/woocommerce/loop/sale-flash.php
adrenalin/woocommerce/single-product/meta.php
adrenalin/woocommerce/single-product/price.php
adrenalin/woocommerce/single-product/product-image.php
adrenalin/woocommerce/single-product/product-thumbnails.php
adrenalin/woocommerce/single-product/related.php
adrenalin/woocommerce/single-product/sale-flash.php
adrenalin/woocommerce/single-product/share.php
adrenalin/woocommerce/single-product/tabs/tabs.php
adrenalin/woocommerce/single-product/up-sells.php
adrenalin/woocommerce/single-product-reviews.php
adrenalin/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
> Allow Backorders = Yes + Inform to customer

A product on backorder is purchasable, so we still list it as 'in stock' (in reality, the notice on the frontend changes) but its not out of stock.

Thats also why the field reverts back; on save, it does a check of stock levels + backorder setting, and if this mismatches it updates the stock status.

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/lzm8813srzwn7mo/2016-05-03%20at%2012.29.png?dl=0
