### ISSUE TITLE
Circular call of woocommerce_attribute_label filter

### ISSUE THREAD

**Issue by jlad26** [woothemes/woocommerce#10845]
## EXPLANATION OF THE ISSUE

Hi there using the woocommerce_attribute_label filter causes an error when looking at any given order I think because of a bug in woocommerce/includes/admin/meta-boxes/views/html-order-item.php.

Line 90 in that file currently reads:
`$meta['meta_key']   = apply_filters( 'woocommerce_attribute_label', wc_attribute_label( $meta['meta_key'], $_product ), $meta['meta_key'] );`

However the function wc_attribute_label itself already applies the woocommerce_attribute_label filter - see lines 82 - 101 of woocommerce/includes/wc-attribute-functions.php (Sorry - can't get it all to format as code properly for some reason):

`
function wc_attribute_label( $name, $product = '' ) {
	global $wpdb;

	if ( taxonomy_is_product_attribute( $name ) ) {
		$name = wc_sanitize_taxonomy_name( str_replace( 'pa_', '', $name ) );

		$label = $wpdb->get_var( $wpdb->prepare( "SELECT attribute_label FROM {$wpdb->prefix}woocommerce_attribute_taxonomies WHERE attribute_name = %s;", $name ) );

		if ( ! $label ) {
			$label = $name;
		}
	} elseif ( $product && ( $attributes = $product->get_attributes() ) && isset( $attributes[ sanitize_title( $name ) ]['name'] ) ) {
		// Attempt to get label from product, as entered by the user
		$label = $attributes[ sanitize_title( $name ) ]['name'];
	} else {
		$label = str_replace( '-', ' ', $name );
	}

	return apply_filters( 'woocommerce_attribute_label', $label, $name, $product );
}
`

So changing line 90 of html-order-items.php to the below fixes the bug and the filter still works fine because it is in the wc_attribute_label function:
`$meta['meta_key']   = wc_attribute_label( $meta['meta_key'], $_product );`

## STEPS TO REPRODUCE THE ISSUE

Use the filter without making any changes to the $label value as per below:
`
add_filter( 'woocommerce_attribute_label', 'my_filter_attribute_label', 10, 3 );function my_filter_attribute_label( $label, $name, $product ) {
    return $label;
}`

Then looking at any specific order will generate the warning Missing argument 3 for my_filter_attribute_label

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://www.windseekerbooking.dev
Site URL: http://www.windseekerbooking.dev
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.5.24
PHP Version: 5.5.24
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (11) ###

JC Submenu: by James Collings – 0.8.4
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.7
WooCommerce Stripe Gateway: by WooThemes – 2.6.12
WooCommerce: by WooThemes – 2.5.5
WooThemes Helper: by WooThemes – 1.6.2
WP Crontrol: by John Blackbourn & Edward Dale – 1.3
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
Native PHP Sessions for WordPress: by Pantheon – 0.5
Windseeker Booking Only Last Child Product Categories: by  – 1.0.0
Windseeker Booking Party Bookings: by  – 1.0.0
Windseeker Spinner: by  – 1.0.0

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /destinations/
Basket: #8 - /basket/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)


### Theme ###

Name: Storefront Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 1.6.1
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
This is fixed in master; the filter was used differently in 2 places.

**Comment by jlad26** [comment]
Maybe I'm looking at the wrong bit, but I can't see how the Master version changes do anything differently. In master the same code now appears on line 36 of html-order-item-meta instead of html-order-item:
`$meta['meta_key']   = apply_filters( 'woocommerce_attribute_label', wc_attribute_label( $meta['meta_key'], $_product ), $meta['meta_key'] );`

And wc_attribute_label is still defined the same and still applies the woocommerce_attribute_label filter, so at best I think the use of the filter in html-order-item-meta has to be superfluous.

But feel free to ignore if you think I've missed something. I have a workaround in the current version which works fine so no problem for me.

**Comment by mikejolley** [comment]
Let me find it...

**Comment by mikejolley** [comment]
This https://github.com/woothemes/woocommerce/commit/6f42514afbc2551b494e43297086391e83133481 The args passed to the filter were wrong in one instance, meaning functions relying on that variable would error.

I see what you mean now though about the filter on wc_attribute_label.

**Comment by jlad26** [comment]
Thanks - and I now see what you mean about the missing argument that you had already added in :)
