### ISSUE TITLE
Change how coupon exclusions work

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#10847]
Currently the way coupon exclusions work (either product or category) is to not allow them in the cart while the coupon is applied. This is troublesome in that it makes customers have to process 2 separate transactions to get everything they want if they want to use a coupon and still purchase the excluded item. 

It would be a far better experience from the customer standpoint if the coupon just didn't apply to the items excluded, rather than force them to not purchase the items together. 

In reference, a ticket came up about this: 416008

**Comment by mikejolley** [comment]
Just change it from cart coupon to a product coupon...?

**Comment by slash1andy** [comment]
Even on a product coupon, if the store wanted to do for all products except this certain category, the exclusion works the same way.

**Comment by mikejolley** [comment]
Have you confirmed that? Last time I checked with product coupons it applies, just to the products not in said category. Which is what you want here.

**Comment by slash1andy** [comment]
Ok, I am really sorry about this. I tested cart coupons, then relied on the docs about the product coupon. I'll work on clarifying the docs.
