### ISSUE TITLE
Email field disabled after filed validation

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#10848]
> We have discovered that when you try to checkout having filled in all the required checkout fields APART from the email field and you are creating an account, the email field is disabled (after clicking the Place Order button). I can actually see this happening whilst watching the page source update during the error checking process.

I was able to replicate that on my local installation.

Screencast: http://cld.wthms.co/11pUr/bA25tVpY

_Link to the ticket: https://woothemes.zendesk.com/agent/tickets/415026_

**Comment by mikejolley** [comment]
Not for me under 2.5. https://dl.dropboxusercontent.com/s/snxa1eb2lwj1tlj/2016-05-05%20at%2016.25.png?dl=0 Nor master.

> I was able to replicate that on my local installation.

Not with stock core + default WP theme I bet?

There is no code I can find which would disable an input. The only thing I know of is password strength meter but that disables nothing on checkout. 

Look at extensions and checkout customisations on that site. If you can really replicate it on local, screencast that and provide your system status report.
