### ISSUE TITLE
Inconsistant VAT display

### ISSUE THREAD

**Issue by ktraving** [woothemes/woocommerce#10849]
During testing of an upcoming webshop, I've experienced a rather troubling inconsistancy regarding the display of product prices excl. or incl. VAT.

Please observe the following steps.

1. I add a product to the cart, price is shown incl. VAT as it should. See http://i.imgur.com/IKruJSV.png
2. I go to the cart page, where prices a borken down excl. VAT, as it should, and the total of the mini cart remains incl. VAT, as it should. See http://i.imgur.com/bjuNgyi.png
3. Lets say I refresh the page or update it because I removed a product. Note how the minicart now changes into excl. VAT, yet product prices remain Incl. VAT. http://i.imgur.com/77NeLyz.png

The only way to make the minicart display totals incl. VAT again, is to empty the cart and start my shopping anew.

I've been in contact with the theme developer (UX themes) and the theme holds no overrides for the mini-cart.php, but I have disabled metadata for it, as well as disabled the product price column in the cart.php.

As I am currently in a tight loop, I haven't had time to test it on a vanilla theme.

WooCommerce VAT settings: See http://i.imgur.com/kq4GQjs.png
WP Version 
WC Version 2.5.5
Apache server / PHP 7.0.5
MySQL server 5.5.47

**Comment by mikejolley** [comment]
WooCommerce never shows the mini-cart on the actual cart page, so this is why it's non-tested and probably not supported.

**Comment by mikejolley** [comment]
Also, that in your screenshot is NOT mini-cart. It's something in the theme custom. Nice catch UX themes -.-

**Comment by mikejolley** [comment]
Did not happen in my test after forcing mini cart to display.

https://github.com/woothemes/woocommerce/blob/2.5.5/templates/cart/mini-cart.php#L79

This function always using the settings of the cart.

https://github.com/woothemes/woocommerce/blob/2.5.5/includes/class-wc-cart.php#L2083

So given your settings (http://i.imgur.com/kq4GQjs.png) this is always ex. tax.
