### ISSUE TITLE
Product Category image is not being imported

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10844]
Well it's fine if I export my store data and import woocommerce products and their respective images. But for the product categories images, it's not working. I am using WordPress Importer Plugin.

Ref: https://github.com/woothemes/woocommerce/pull/10366

**Comment by mikejolley** [comment]
Dummy data does not cover product_cat term meta/images. It won't until we've ported over to 4.4 term meta tables and it's handled in the importer.
