### ISSUE TITLE
Update order item meta through REST API

### ISSUE THREAD

**Issue by arber** [woothemes/woocommerce#10846]
I noticed that order item metadata do not get updated through the REST API (v3). It would be awesome to have this feature in the future.  Do you have any suggestion how I can achieve this with the current version?

**Comment by claudiosmweb** [comment]
"order item metadata"?
What "metadata"?

**Comment by arber** [comment]
Maybe I expressed myself wrong, sorry. I meant the line item meta for an order.

**Comment by claudiosmweb** [comment]
You can remove this product and add again a new variation.

**Comment by LilianDyer** [comment]
Hi Claudio,

But what if the customer changed his choice to a different color.  It is not the product that needs to change but his choice. 

I am having trouble updating  the line_item meta also.  In my case this field has been created in woo, and it has a value as a place holder for a serial number that will be generated and send back through the api.

These is the json I'm trying to send in a PUT with the order id.

{
  "order":

{
   "line_items": [
      {
         "id": 145,
         "product_id": 57
         
         "meta": [
           {
               "key": "Serial Number",
               "label": "Serial Number",
               "value": "ABC1234567"
            }
         ]
      }
   ]
   
}
}

But the response is an error: 
{
  "errors": [
    {
      "code": "woocommerce_api_missing_callback_param",
      "message": "Missing parameter data"
    }
  ]
}

Is there a way to update a meta field at the line level?  Thanks so much!

**Comment by arber** [comment]
Hello Lilian,

I solved this by adding some code in the following files and methods:

1. abstract-wc-order.php
   method: public function update_product( $item_id, $product, $args )
   line 324, before backorders add:
   
   // other meta
		if ( isset ( $args['meta'] )){
			foreach($args['meta'] as $key => $value){				
				wc_update_order_item_meta( $item_id, $value['key'], $value['value'] );
			}
		}


 2. class-wc-api orders.php.
     method: protected function set_line_item( $order, $item, $action )
     line 976 (before if($creating) ) add:

      // other meta
		if( isset ( $item['meta'] )) {
			$item_args['meta'] = $item['meta'];
		}	

Hope this helps!

Regards,
Arber

**Comment by mohammadfurqanofficial** [comment]
https://github.com/woocommerce/woocommerce/issues/13024

**Comment by mohammadfurqanofficial** [comment]
#arber I added your provided code but not working can you please help me to resolve issue

**Comment by arber** [comment]
Hello,

it might be that you are modifying the wrong files. The second modification needs to be done in "class-wc-api-orders.php" in the legacy API v3 (includes/api/legacy/v3).

Regards,
Arber

**Comment by amjad** [comment]
That is not meta, its variations dictionary

**Comment by arber** [comment]
Well, since the naming in the JSON is "meta" I thought it is meta.

**Comment by amjad** [comment]
WooCommerce documentation is not very developer friendly. It has a lot of things that we need to figure out on our own.

**Comment by suruchibabbar1** [comment]
Update_product function is not present in updated woocommerce file kindly suggest something soon as em unable to update orderitemmeta using woocommerece rest api.plzzzz

**Comment by suruchibabbar1** [comment]
@claudiosanches plz reply

**Comment by amjad** [comment]
@suruchibabbar1 you can remove the item and add it again with the new metas.

**Comment by suruchibabbar1** [comment]
@amjad after adding new item also meta array is still empty.im using woocommerce 3 and v3 version of woocommerce rest api.

**Comment by amjad** [comment]
you need to use variations dictionary to add meta. check the api docs example.

**Comment by suruchibabbar1** [comment]
variations dict???but why
API URL:https://www.mrbutton.in/wc-api/v3/orders/130647?filter[meta]=true
method:put
body:{
"order": {
	"line_items": [
				{
					"id": 176489,
					"product_id": 48124,
            		"sku": "CATSHR24",
					"meta": {
						"key": "Blue",
						"value": "Cotton",
						"label": "A"
					},
					"quantity":1
				}
		]
}
}

response:
{
    "order": {
        "id": 130647,
        "order_number": "MB130647",
        "order_key": "wc_order_59e20b323b623",
        "created_at": "2017-10-14T13:03:00Z",
        "updated_at": "2017-10-26T12:45:14Z",
        "completed_at": "2017-10-26T12:44:59Z",
        "status": "processing",
        "currency": "INR",
        "total": "7995.00",
        "subtotal": "7995.00",
        "total_line_items_quantity": 5,
        "total_tax": "0.00",
        "total_shipping": "0.00",
        "cart_tax": "0.00",
        "shipping_tax": "0.00",
        "total_discount": "0.00",
        "shipping_methods": "Free shipping",
        "payment_details": {
            "method_id": "cod",
            "method_title": "Cash on Delivery",
            "paid": true
        },
        "billing_address": {
            "first_name": "rerty4tr",
            "last_name": "",
            "company": "",
            "address_1": "test",
            "address_2": "",
            "city": "FARIDABAD",
            "state": "HR",
            "postcode": "121001",
            "country": "IN",
            "email": "test@test.com",
            "phone": "7291017998"
        },
        "shipping_address": {
            "first_name": "rerty4tr",
            "last_name": "",
            "company": "",
            "address_1": "test",
            "address_2": "",
            "city": "FARIDABAD",
            "state": "HR",
            "postcode": "121001",
            "country": "IN"
        },
        "note": "",
        "customer_ip": "111.93.41.174",
        "customer_user_agent": "mozilla/5.0 (windows nt 6.1) applewebkit/537.36 (khtml, like gecko) chrome/61.0.3163.100 safari/537.36",
        "customer_id": 1,
        "view_order_url": "https://www.mrbutton.in/my-account/view-order/130647",
        "line_items": [
            {
                "id": 176489,
                "subtotal": "1599.00",
                "subtotal_tax": "0.00",
                "total": "1599.00",
                "total_tax": "0.00",
                "price": "1599.00",
                "quantity": 1,
                "tax_class": "",
                "name": "The Master Skipper Cotton Shirt - L",
                "product_id": 48124,
                "sku": "CATSHR24",
                "meta": [
                    {
                        "key": "track",
                        "value": "1",
                        "label": "track"
                    }
                ]
            },
            {
                "id": 176832,
                "subtotal": "1599.00",
                "subtotal_tax": "0.00",
                "total": "1599.00",
                "total_tax": "0.00",
                "price": "1599.00",
                "quantity": 1,
                "tax_class": "",
                "name": "The Master Skipper Cotton Shirt - L",
                "product_id": 48124,
                "sku": "CATSHR24",
                "meta": []
            },
            {
                "id": 176833,
                "subtotal": "1599.00",
                "subtotal_tax": "0.00",
                "total": "1599.00",
                "total_tax": "0.00",
                "price": "1599.00",
                "quantity": 1,
                "tax_class": "",
                "name": "The Master Skipper Cotton Shirt - L",
                "product_id": 48124,
                "sku": "CATSHR24",
                "meta": []
            },
            {
                "id": 176834,
                "subtotal": "1599.00",
                "subtotal_tax": "0.00",
                "total": "1599.00",
                "total_tax": "0.00",
                "price": "1599.00",
                "quantity": 1,
                "tax_class": "",
                "name": "The Master Skipper Cotton Shirt - L",
                "product_id": 48124,
                "sku": "CATSHR24",
                "meta": []
            },
            {
                "id": 176835,
                "subtotal": "1599.00",
                "subtotal_tax": "0.00",
                "total": "1599.00",
                "total_tax": "0.00",
                "price": "1599.00",
                "quantity": 1,
                "tax_class": "",
                "name": "The Master Skipper Cotton Shirt - L",
                "product_id": 48124,
                "sku": "CATSHR24",
                "meta": []
            }
        ],
        "shipping_lines": [
            {
                "id": 176490,
                "method_id": "free_shipping:2",
                "method_title": "Free shipping",
                "total": "0.00"
            }
        ],
        "tax_lines": [],
        "fee_lines": [],
        "coupon_lines": [],
        "customer": {
            "id": 1,
            "created_at": "2013-09-27T06:00:49Z",
            "last_update": "2017-10-26T12:44:59Z",
            "email": "ashislubumohanty@gmail.com",
            "first_name": "rerty4tr",
            "last_name": "test",
            "username": "mrbutton",
            "role": "administrator",
            "last_order_id": 130647,
            "last_order_date": "2017-10-14T13:03:00Z",
            "orders_count": 192,
            "total_spent": "41241.71",
            "avatar_url": "https://secure.gravatar.com/avatar/6492ad0e80b233136e0359f50d8535aa?s=96&d=mm&r=g",
            "billing_address": {
                "first_name": "rerty4tr",
                "last_name": "",
                "company": "",
                "address_1": "test",
                "address_2": "",
                "city": "FARIDABAD",
                "state": "HR",
                "postcode": "121001",
                "country": "IN",
                "email": "test@test.com",
                "phone": "7291017998"
            },
            "shipping_address": {
                "first_name": "rerty4tr",
                "last_name": "",
                "company": "",
                "address_1": "test",
                "address_2": "",
                "city": "FARIDABAD",
                "state": "HR",
                "postcode": "121001",
                "country": "IN"
            }
        },
        "order_meta": {
            "cod_confirm": "4",
            "ship_tracking_code": "123",
            "ship_courier_name": "0",
            "tracking_cou": "test",
            "hello": "fh"
        }
    }
}

META ARRAY IS NOT CHANGING.kindly reply soon.

**Comment by suruchibabbar1** [comment]
@claudiosanches ,@amjad

**Comment by amjad** [comment]
Your post request is wrong. Check v3 API docs. You have to use variations instead of meta.

**Comment by suruchibabbar1** [comment]
{
    "errors": [
        {
            "code": "woocommerce_api_invalid_product_variation",
            "message": "The product variation is invalid"
        }
    ]
}
when meta is renamed to "variations 
"

**Comment by claudiosanches** [comment]
@suruchibabbar1 read the REST API docs and for better support for meta data, you should use the latest REST API version: https://woocommerce.github.io/woocommerce-rest-api-docs/
