### ISSUE TITLE
2.6-beta-1 - Fatal Error when Upgrading with table-rate-shipping activated

### ISSUE THREAD

**Issue by silicondales** [woothemes/woocommerce#10843]
Upgrading in staging environment to 2.6-beta-1 from 2.5.5

Have a heap of other plugins & customer functions.

On activating new woocommerce, fatal error thrown:

PHP Fatal error:  Cannot redeclare wc_get_shipping_zone() (previously declared in /var/www/html/wp-content/plugins/woocommerce-table-rate-shipping/shipping-zones/includes/wc-shipping-zone-functions.php:9) in /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1171, referer: wp-admin/plugins.php

Removing the table-rate-shipping plugin (which is superseded by this version?) fixes this.

Points: 
1) this should probably be noted, in docs, under "before upgrading": Remove table rate shipping plugin.

2) On a related note, the database upgrade does not completely import the "old" shipping settings: zone names import, but **shipping methods** do not. May post another issue and see if we can fix this.

**Comment by gedex** [comment]
For TRS, @mikejolley is working on WC 2.6 compat. Much shipping zones functionalities come from TRS, that's the reason you got redeclared method error. Ideally TRS with WC 2.6 compat should be shipped before WC 2.6 release.

**Comment by mikejolley** [comment]
^ yep we'll have an update out before launch. For now....

**Comment by silicondales** [comment]
No problem - just checking off suitability on other parts, and this cropped up.

Lot of cool features going into core which will reduce reliance on customisations.

If you want a hand with the shipping table stuff (mainly firing upgrade procedure at in the wild staging environments with varying degrees of data quality), drop me an email.

**Comment by silicondales** [comment]
Am I right in thinking TRS will not be needed with the new table rates which are in 2.6 - if not, what does / will TRS do that 2.6 doesn't?

**Comment by mikejolley** [comment]
@silicondales TRS still offers more advanced shipping rules than you can manage with flat rates. e.g. rules based on qty or weight.
