### ISSUE TITLE
WooCommerce Registration Forces Customer Role

### ISSUE THREAD

**Issue by johnlanglois** [woothemes/woocommerce#10851]
I have tried getting WooCommerce to change the role from "Customer" to "Group Leader" when someone registers using the WooCommerce registration form at checkout.
I have added a radio field to the form and checking that provides authorization for the change.

When the code fires, the role gets changed to "None."
I am assuming that's because WC doesn't recognize "Group Leader" as a role.
However, the WooCommerce Role Pricing Pro plug-in that I use has established "Group Leader" as a role and uses it to change the displayed price.  It works as advertised if I manually change a user's role.
My issue is how to change the role via functions.php on the WC registration page.
```
function my_new_customer_data($new_customer_data){
		
			$new_customer_data['role'] = 'Group Leader';
			return $new_customer_data;
		
}
add_filter( 'woocommerce_new_customer_data', 'my_new_customer_data');

```
A look at the metadata shows wp448_capabilities is set to a:1:{s:12:"Group Leader";b:1;}
However, If I manually assign the role, I get
a:2:{s:12:"Group Leader";b:1;s:12:"group_leader";b:1;}

Should I be using the lower case, hyphenated value instead?

THank you.

**Comment by claudiosmweb** [comment]
>  I am assuming that's because WC doesn't recognize "Group Leader" as a role.

Why? Since WooCommerce use `wp_insert_user()` to create the user?
It's a WordPress function... So should work with any value, do you agree?

But the most important question: Why are you using the role "name" and note the role "slug"?

Have you tried it?

```php
function my_new_customer_data( $new_customer_data ) {
            $new_customer_data['role'] = 'group_leader';

            return $new_customer_data;
}

add_filter( 'woocommerce_new_customer_data', 'my_new_customer_data' );
```
