### ISSUE TITLE
[API] Settings a custom price for an item when creating order

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#10855]
## EXPLANATION OF THE ISSUE

I'm building an app integrated with WooCommerce. I need to be able to create an order in which I can send a custom price of an item. basically overriding it for that order only. How can I do this?

## STEPS TO REPRODUCE THE ISSUE

I tried editing the API call by adding "price": 99.99 to it but it didn't work obviously as its a readonly field.

**Comment by mikejolley** [comment]
Price is product price and read only. You should instead set the line prices (total, total_tax). See https://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties

**Comment by amjad0** [comment]
Thanks!

Isn't the total_tax automatically calculated?

**Comment by mujuonly** [comment]
@mikejolley  The link is not working anymore - May be it can be replace with new one https://woocommerce.github.io/woocommerce-rest-api-docs/#order-line-items-properties
