### ISSUE TITLE
Add to cart on variation will not work in firefox

### ISSUE THREAD

**Issue by mrleira** [woothemes/woocommerce#10857]
## EXPLANATION OF THE ISSUE
In firefox, its not possible to select variation and add it to cart.
Example: http://www.new.thechef.no/produkt/vakuumposer-mstruktur-ekstra-tykk-100-stk/

## STEPS TO REPRODUCE THE ISSUE

1. Open page
2. Select variation
3. Note that price dont update
3. Add to cart
4. note that cart dont update, and also note that error msg is given " Please select variation" 

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.new.thechef.no
Site URL: http://www.new.thechef.no
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: nb_NO

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.4.45
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Fjernt innlegg: ✔
Fjernt 'Get': ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (38) ###

Akeeba Backup Professional for WordPress: av Akeeba Ltd – 1.3.0
Async Javascript: av David Clough (cloughit) – 1.16.03.23
Contact Form 7 Honeypot: av Nocean – 1.8
Kontaktskjema 7: av Takayuki Miyoshi – 4.4.2
Envato WordPress Toolkit: av Envato – 1.7.3
Google Analytics by MonsterInsights eCommerce tracking addon: av The MonsterInsights Team – 5.4.9
Google Analytics by MonsterInsights: av MonsterInsights – 5.5
Loco Translate: av Tim Whitlock – 1.5.5
MailChimp for WordPress Pro: av ibericode – 2.7.20
PayPal for WooCommerce: av Angell EYE – 1.1.9.2
Really Simple CAPTCHA: av Takayuki Miyoshi – 1.9
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: av Your WP Expert – 1.3
User Role Editor Pro: av Vladimir Garagulya – 4.19
WC Sequential Order Numbers: av Dualcube
Putul Sahoo
Aveek Kr. Saha – 1.1.3

WooCommerce Advanced Messages: av Jeroen Sormani – 1.0.2
WooCommerce Bring Shipping: av Nettpilot – 1.1.0
WooCommerce Cart Based Shipping: av Bolder Elements – 3.0.1 (DEV copy)
WooCommerce Email Customizer: av cxThemes – 2.36
WooCommerce Klarna Gateway: av WooThemes – 2.1.4
WooCommerce Stripe Gateway: av WooThemes – 2.6.12
WooCommerce AdWords Conversion Tracking: av Wolf+Bär GmbH – 1.3.1
WooCommerce Header Category Image: av Get Bowtied – 1.0.0
WooCommerce jQuery Cookie Fix: av Roy Ho – 1.0
WooCommerce Pricefiles: av Peter Elmered – 0.1.11
WooCommerce Google Product Feed: av Lee Willis – 6.5
WooCommerce Smart Coupons: av WooThemes – 3.0.12 – 3.0.16 er tilgjengelig
WooCommerce Social Media Share Buttons: av Toastie Studio – 1.3.0
Tripletex for WooCommerce: av SlopeTracker – 2.6.56
WooCommerce: av Woothemes – 2.5.5
Shipping Details for WooCommerce: av PatSaTECH – 1.7.0
WooThemes Helper: av WooThemes – 1.6.2
Wordfence Security: av Wordfence – 6.1.5
WordPress Importer: av wordpressdotorg – 0.6.1
Yoast SEO: av Vi i Yoast – 3.2.4
WP Mobile Detect: av Jesse Friedman – 2.0
WP Smush Pro: av WPMU DEV – 2.2.2
WPMU DEV Dashboard: av WPMU DEV – 4.0.9

### Settings ###

Force SSL: ✔
Currency: NOK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Butikkbase: #440 - /nettbutikk/
Handlekurv: #441 - /handlekurv/
Til kassen: #442 - /kassen/
Min konto: #443 - /min-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ✕ – Hvis du endrer WooCommerce eller et foreldertema du selv ikke bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/zd2vabnkr1s4b2d/2016-05-05%20at%2011.31.png?dl=0

**Comment by mrleira** [comment]
No active plugins but woocommerce and standard theme. Problem is still there
`
### WordPress Environment ###

Home URL: http://www.new.thechef.no
Site URL: http://www.new.thechef.no
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: nb_NO

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.4.45
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Fjernt innlegg: ✔
Fjernt 'Get': ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: av Woothemes – 2.5.5

### Settings ###

Force SSL: ✔
Currency: NOK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Butikkbase: #440 - /nettbutikk/
Handlekurv: #441 - /handlekurv/
Til kassen: #442 - /kassen/
Min konto: #443 - /min-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ✕ – Hvis du endrer WooCommerce eller et foreldertema du selv ikke bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
There is a functions.js with the error. See the error console.

**Comment by mrleira** [comment]
Yes, I can see that. But I have disable all plugins but woocommerce it self, and I have enable a standard wordpress theme Twenty Sixteen. And there is no custom work left on the site. Im not sure the if the problem is related to wordpress or woocommerce, but I would expect it to work when all is running with core install??

**Comment by mikejolley** [comment]
functions.js is not coming from WooCommerce. it's your install. We cannot debug this for you.

**Comment by mrleira** [comment]
Okey, I thought it was in woocommerce interest to work with core wordpress install. Ill keep trying solve this elsewhere. Thanks

**Comment by mikejolley** [comment]
@mrleira it **does** work with default themes. Your problem is specific to your install. ^ "Maybe your version of 2016 is out of date or customized."

**Comment by mikejolley** [comment]
2016, no errors https://dl.dropboxusercontent.com/s/4pd05u8lfjdeple/2016-05-05%20at%2012.53.png?dl=0

**Comment by mikejolley** [comment]
@mrleira can you do a test without images in your product description? The JS seems to be looking for those elements and doing stuff. Could be a 2016 issue.

**Comment by mrleira** [comment]
Sorry, made no difference. Im in the process of creating a new theme. But
seems to me there are some jquery conflicts going on after the last
wordpress updates..

On 5 May 2016 at 14:01, Mike Jolley <notifications@github.com> wrote:

> @mrleira <https://github.com/mrleira> can you do a test without images in
> your product description? The JS seems to be looking for those elements and
> doing stuff. Could be a 2016 issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/10857#issuecomment-217136394>
>



-- 
Med vennlig hilsen / Kind Regards
Robert Leira
Phone: +00 47 46470660
Mail:       robert@leira.cc
.........................................................................................................................
This e-mail and any attachments may contain confidential and privileged
information.

**Comment by mrleira** [comment]
@mikejolley please have a look:
http://www.new.thechef.no/nettbutikk/vakuum-og-sous-vide-emballasje/vakuumposer-mstruktur-ekstra-tykk-100-stk/

All errors are related to woocommerce and wordpress, not theme.. and still it not work in firefox.

**Comment by mikejolley** [comment]
Wrong again. Scripts are broken because your theme is loading a custom version of jQuery to the page. There are 2 jquery scripts in your source, 1 enqueued by WordPress, 1 by your theme. Your custom.js also errors because of this and that is NOT a WooCommerce script.

I'm locking this topic; these are not woocommerce bugs, and this is not a support forum.
