### ISSUE TITLE
get_currentuserinfo is deprecated since version 4.5! 

### ISSUE THREAD

**Issue by MicroKloon** [woothemes/woocommerce#10852]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
WooCommerce version?

![screenshot from 2016-05-04 15-51-52](https://cloud.githubusercontent.com/assets/1264099/15025538/254f10bc-1210-11e6-87dc-f5ac45c99dfc.png)

Please, read this again:

>And before logging BUGS, ensure you:
>- **Use the latest stable release of WooCommerce.**
>- Disabled all plugins to ensure it's a core bug and not a plugin issue.
>- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.

**Comment by MicroKloon** [comment]
`

WC Version: 2.5.5



### WordPress Environment ###

Home URL: https://woo.microkloon.nl
Site URL: https://woo.microkloon.nl
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10
PHP Version: 5.6.20-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 400
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (17) ###

Acumulus: by SIEL Acumulus – 4.4.0
AfterShip - WooCommerce Tracking: by AfterShip – 1.4.8
Akismet: by Automattic – 3.1.10
Advanced Automatic Updates: by pento – 1.0.2
Enhanced Media Library: by wpUXsolutions – 2.2.2
FG PrestaShop to WooCommerce: by Frédéric GILLES – 2.4.2
Jetpack by WordPress.com: by Automattic – 4.0.2
Mobile Assistant Connector: by eMagicOne – 1.1.1
Mollie Payments for WooCommerce: by Mollie – 2.2.1
PayPal for WooCommerce: by Angell EYE – 1.1.9.2
Storefront Footer Bar: by WooThemes – 1.0.3
WooCommerce Weight Based Shipping: by dangoodman – 4.1.3
WooCommerce Shipping Pro with Table Rate (BASIC): by WooForce – 1.1.7
WooCommerce: by WooThemes – 2.5.5
Wp Mail Bank: by Tech Banker – 1.41
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.4
Zopim Widget: by Zopim – 1.4.3

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /winkel/
Basket: #5 - /winkelmand/
Checkout: #6 - /winkel/afrekenen/
My Account: #7 - /mijn-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 1.6.1
Author URL: http://www.woothemes.com
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
@MicroKloon try find any `get_currentuserinfo()` in the WooCommerce source code in version 2.5.5:

![screenshot from 2016-05-04 16-57-57](https://cloud.githubusercontent.com/assets/1264099/15027283/6967e0c2-1219-11e6-8807-36911296419e.png)

**Comment by claudiosmweb** [comment]
@MicroKloon show me the complete error message.
