### ISSUE TITLE
[WC 2.6] Name Your Price compat: variable product w/ all nyp variations show no attributes on product page

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#10854]
Just started my testing and found a problem with variable products that have all their variations set to be nyp and have no value in the `_price` field. This is the result:

![image](https://cloud.githubusercontent.com/assets/507025/15028507/e0f5f3e6-120e-11e6-93ae-c322763b4153.png)

No attributes are displayed. Tracing it backwards that seems to be because `$product->get_variation_attributes()` is calling `$product->get_children()`with a [`$true` parameter](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L383) which then hard codes a [meta query with a `_price` meta key](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L121)  that does not exist for certain NYP products.

**Comment by helgatheviking** [comment]
If `false` is the default value of the filter then nothing is changed when `$visible_only` is set to `true`.

**Comment by mikejolley** [comment]
Prices are required usually... Test with no prices and no NYP too see why.

**Comment by helgatheviking** [comment]
Ok, so with that filter in place if all the variations have no price and aren't NYP then the attribute dropdowns still appear.... which was not happening prior to this commit. All the options are available in the dropdown, which is different from previous versions, but not worse. Prior to the commit the dropdown didn't appear at all, so I think this is better. Thanks Mike!

![image](https://cloud.githubusercontent.com/assets/507025/15052364/f4a88bb0-12c2-11e6-8640-2748b3767412.png)

**Comment by mikejolley** [comment]
>All the options are available in the dropdown, which is different from previous versions, but not worse. 

What ones are showing? Should be those with no price no? Don't see what else changed.

**Comment by helgatheviking** [comment]
I mean the different color options for the attribute. In 2.5.x if they have no price and are not NYP they don't appear in the dropdown at all if, but in 2.6 they do. 

Here's an example in 2.5.x. The colors dropdown is empty:
https://wordpress-helgatheviking.c9.io/product/ship-your-idea-2/

I don't think it is problematic, just slightly different.

**Comment by claudiosmweb** [comment]
@mikejolley @helgatheviking not fixed yet.

We don't have any `$variation` in the `get_children()` method:
https://github.com/woothemes/woocommerce/commit/edbb03a5d81e7e7315ea4a3b7cdaaa2c7f4abd6e#diff-9d28960c60468fc038da5e6232cf0d8cR123

And we are applying this filter twice:

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L545-L569

First in `get_children()` and then for each variation... Maybe will be better a new filter or move this filter into `get_children()`.

**Comment by claudiosmweb** [comment]
Fixed now ^
