### ISSUE TITLE
Showing download links in order for troubleshooting

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#10867]
When a customer complains about failing to download a digital product, the easiest way to troubleshoot without asking for their order confirmation message is to grab the link from the order itself.

Can this please be implemented?

If I'm totally blind and couldn't find it, my apologies. Please point me in the right direction.

**Comment by WPprodigy** [comment]
Fixed with the above pull request: 

![](https://camo.githubusercontent.com/a678ff25e80e9e731d24e22f229e5d6b35359a12/687474703a2f2f636c642e7774686d732e636f2f636278342f325377436e56794e2b)
