### ISSUE TITLE
Create Webhook API doesn't add a secret by default

### ISSUE THREAD

**Issue by frankszymanski** [woothemes/woocommerce#10866]
I used the create webhook API to create a webhook with the following JSON body (delivery URL different)
{\"webhook\":{\"name\":\"StoneEdge Fusion product.created\",\"topic\":\"product.created\",\"delivery_url\":\"https://example.com/endpoint\"}}
My webhook endpoint code failed when trying to validate. I added some temporary logging to the code that generates the signature in my development store to try and track down the problem and I found that the secret was a blank string.  I verified this by changing the secret used in my hash code in the webhook endpoint to a blank string and the validation worked fine.

## STEPS TO REPRODUCE THE ISSUE

1. Enable the API and create API Keys
2. Create a webhook using the above json, replacing the delivery_url with a valid endpoint (e.. requestbin).
3. Create a SHA256 hash of the webhook body using a blank string as the secret and convert to base64. Compare to the signature sent in the webhook headers.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://woocommerce.stoneedge.com
Site URL: http://woocommerce.stoneedge.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.44
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (2) ###

Page Builder by SiteOrigin: by SiteOrigin – 2.4.6
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Vantage
Version: 1.4.4
Author URL: http://siteorigin.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Yes, if you need to validate, you need to create a "secret" every time, that's why don't create one for you.

**Comment by frankszymanski** [comment]
The create_webhook function in class-wc-api-webhooks.php suggests that the API user's secret should be set as the default if you don't provide one:
`$webhook->set_secret( ! empty( $data['secret'] ) ? $data['secret'] : get_user_meta( get_current_user_id(), 'woocommerce_api_consumer_secret', true ) );`
The documentation also states that the API user's secret should be used if it isn't provided: "Secret key used to generate a hash of the delivered webhook and provided in the request headers. This will default to the current API user’s consumer secret if not provided "

**Comment by claudiosmweb** [comment]
@frankszymanski this is deprecated. I'll update the docs.

**Comment by frankszymanski** [comment]
@claudiosmweb Does this mean that unless you are using https or the admin pages there is no way to securely create a secret for a webhook?

**Comment by claudiosmweb** [comment]
@frankszymanski nop, just set a secret.

**Comment by frankszymanski** [comment]
@claudiosmweb But to set a secret when creating the webhook without https, I have to send that secret in the JSON body unencrypted. There's really no way to securely keep it secret.

**Comment by frankszymanski** [comment]
@claudiosmweb By the way, I opened a documentation issue for the doc change: https://github.com/woothemes/woocommerce/issues/10881
