### ISSUE TITLE
Add downloadable subject and heading to processing emails

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#10868]
Since there is an option to allow downloads when orders are in the "Processing" status, it makes sense to include "download your products" to the email subject and heading, as per the completed order email setup.

There is a way to do this through the woocommerce_email_subject_customer_processing_order and woocommerce_email_heading_customer_processing_order filters, but that's hard and requires unnecessary code. Proper admin settings will be much cleaner and it's almost a copy and paste job for the plugin developers :)

Please implement these options.

**Comment by mikejolley** [comment]
Will revisit after #10704 which is going to change these emails, specifically for downloadable goods.
