### ISSUE TITLE
[WC 2.6] Free Gift Coupons compat- JS coupon application doesn't add free gift to cart items

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#10863]
A page refresh is required to show the free gift has been added to the cart. Similarly, a refresh is required to remove a free gift from the cart if the coupon is removed. So I think I need a way to either force a page refresh, or a way to reload the cart?

**Comment by mikejolley** [comment]
I've added a trigger to the page. This can be used to call a window.reload.

**Comment by helgatheviking** [comment]
Is there anyway to only call `window.reload` conditionally for freegift coupons? And/or is there any way to just refresh the cart items? 

Ps- going to need a similar trigger for `remove_coupon_clicked`

**Comment by mikejolley** [comment]
No, it would need to be on all apply coupon triggers. I couldn't see any other way around it because the ajax response in this case contains *just* notices. It would take an extra ajax reload, or a new endpoint.

See how you get on otherwise we'll need something else.

**Comment by helgatheviking** [comment]
I'll test it out. It's a shame that fgc users won't get to take advantage
of the new Ajax refresh for coupons, but that's not the end of the world
since reload is the current state.

Don't forget that we'll need a similar trigger for removing coupons.

**Comment by helgatheviking** [comment]
PS- Should I only add this script to the cart page if WC>=2.6?
