### ISSUE TITLE
[WC 2.6] The "learn more about shipping zones" button link is a 404

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#10864]
The "learn more about shipping zones" button link is a 404:

![image](https://cloud.githubusercontent.com/assets/507025/15052298/8644d9da-12c2-11e6-99b5-adc8d0dd25ae.png)

https://docs.woothemes.com/document/setting-up-shipping-zones/

It may just not be live yet, but I thought I'd report it before I forgot.

**Comment by mikejolley** [comment]
Thanks, it's a draft.
