### ISSUE TITLE
Re-calculate shipping after editing an Subscription

### ISSUE THREAD

**Issue by antoniosHafez** [woothemes/woocommerce#10861]
**Step 1**: Ordered A + B:
(shipping zone "Norge: Postlegging" adds shipping pr item. This means that if a customer order A + B (in initial order) he gets charged 2x of the zone cost (150+150=300) which is right.)
**Step 2**: Removed one of the products, so customer is only left with A: 
he is still charged 300 (240 + taxes) for shipping. Should be 150 (120 + taxes).

**Comment by mikejolley** [comment]
Shipping cannot be recalculated automatically in the backend. Rates are often dynamic or based on many things - won't be possible until https://trello.com/c/HP1KuD4v/21-shipping-quotes-backend

For now, you can edit the shipping line items and modify the costs.
