### ISSUE TITLE
please do NOT point, encourage, or distract from the RIGHT plugin

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/woocommerce#10860]
fresh installation, php7, spiderman underwear, thursday, shiny updates, storefront, SSL, yadda yadda
_let's get to the issue now_

Activate WC, go through the onboarding dialogue, choose stripe, then this glorious message pops up:

![faith-stripe-1](https://cloud.githubusercontent.com/assets/6208757/15044879/01ae9dc0-129d-11e6-9825-2ade4bd92f8e.png)

_all seems good, right?_  But **watch** what happens when the customer follows the prompt and clicks on the underlined text....

![faith-stripe-2](https://cloud.githubusercontent.com/assets/6208757/15044907/33947b3e-129d-11e6-9758-6697bc25ac96.png)
:open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: :open_mouth: 

Look, there's no way we want people downloading and looking for just any random piece of code to process their financial transactions, right? **It's kinda one of the important pieces to WooCommerce** :stuck_out_tongue_winking_eye: Let's get 'em to the **right** plugin straight out the gate and set 'em up right the **first** time.

That link has GOT to prompt people to go to the OFFICIAL WooThemes Stripe Extension and **nothing** else.

:heart: ~Brad

**Comment by mikejolley** [comment]
There is no 'single' view for extensions on that screen, so thats pretty much the best we can offer.. that said, once new Stripe is on .org, this notice should be a rare occurrence.

**Comment by claudiosmweb** [comment]
@mikejolley maybe we can open the modal in this page.

```
wp-admin/plugin-install.php?tab=plugin-information&plugin=woocommerce-gateway-stripe&TB_iframe=true&width=772&height=491
```

**Comment by mikejolley** [comment]
We could add an install button, so long as the nonce doesn't expire. This message is added once and stored. It's not dynamic.

**Comment by claudiosmweb** [comment]
@mikejolley we can have a endpoint to redirect with a fresh nonce too.
