### ISSUE TITLE
Automatic Tax Rate Sorting

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10873]
Something I want to get rid of in 2.7 is the tax rate drag and drop. It's difficult to use, especially when you have multiple pages of rates.

We should instead try to sort rates automatically, based on and in order of priority:

- Priority
- Country code
- State code
- # of Zip code
- # of City

This order would make sense and ensure more specific rules get matched first. Currently the admin has to set the order which leaves it prone to user error.

To avoid confusing when adding a row (it adds to bottom of the list now), we could move this to a modal so that the rate is added in the correct position, with success notice and updated rate count.

cc @claudiosmweb @mattyza

**Comment by DavidAnderson684** [comment]
> when adding a row

If there are any changes with adding a row, then please you make sure that it's possible for extensions to easily add and update their own rows? (e.g. route through a re-usable function). This is important for extensions that want to make it easy for users to add/update rates en masse (e.g. get the latest EU VAT rates covering 28 countries). The changes in WC 2.4 (?) when Backbone was introduced to this page brought in a world of pain; I eventually got it working (with the help of some insight from @daigo75, who also has an extensions doing that); but, it's very tricky and inelegant.
