### ISSUE TITLE
[API] Get Order Custom Meta along with the order 

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#10879]
Is it possible to get Order Custom Meta fields along with the order?

**Comment by claudiosmweb** [comment]
Only if you make this data available using the filters in the API.
For example you can add custom data using the `woocommerce_api_order_response` filter.

**Comment by amjad0** [comment]
@claudiosmweb I didn't get you. How can I make the custom fields of an order available using filters? Can you give an example API call and response? I am trying to get b
