### ISSUE TITLE
Woocommerce Bulgarian Version Bug

### ISSUE THREAD

**Issue by alemanchev** [woothemes/woocommerce#10877]
Hello everyone!
There seems to be a bug with the Bulgarian language version of woocommerce.
When the plugin is translated the word "product" is changed to "produkt".
Therefore when creating a new product it says that it will be created on www.domain.com/produKt/name , but instead is created at www.domain.com/product/name.
When the product is clicked on the website the redirection is to www.domain.com/produKt/name
and you get 404. The issue can be fixed simply by changing the bulgarian language file to say product on product and product-category on product-category. However woocommerce automaticale overwrittens files every hour or so. Could you help us bulgarians get over this issue?

**Comment by mikejolley** [comment]
Needs to be corrected in https://translate.wordpress.org/locale/bg/default/wp-plugins/woocommerce if wrong, otherwise Settings > Permalinks > save will stop the 404
