### ISSUE TITLE
Product Link Goes To Blank 404 Page

### ISSUE THREAD

**Issue by rhlandon** [woothemes/woocommerce#10878]
## EXPLANATION OF THE ISSUE

When I try to preview my product using preview,  or the perma link itself, even after updating it goes to a 404 error page cant be found. Never happened before now what?

## STEPS TO REPRODUCE THE ISSUE

1. Link was working fine all of the sudden it just stopped working and wont restore

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Don't post support questions here. Settings > Permalinks > save will resolve. It's likely translation related.
