### ISSUE TITLE
V2 API broken on 2.6.0-beta-1

### ISSUE THREAD

**Issue by girtsu** [woothemes/woocommerce#10887]
V2 API seems to be broken on 2.6 beta 
I get this error:
```
Cannot redeclare class WC_API_Exception in /wordpress/wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-exception.php
```
It seems that v3 exception was already included in `rest_api_includes` method so `handle_v2_rest_api_request` can't include a class with the same name anymore.

**Comment by briedis** [comment]
@claudiosmweb I've got a client with 2.6.4 with this error:
```
Cannot redeclare class WC_API_Exception in wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-exception.php on line 48
```

Looks like the same problem? Is this fixed?

**Comment by claudiosmweb** [comment]
@briedis already fixed in 2.6.4.

**Comment by briedis** [comment]
@claudiosmweb Except the version already is 2.6.4.
Can it be because of a plugin? I've got no idea where to look.

**Comment by mikejolley** [comment]
A plugin could be re-including the file with WC_API_Exception defined, or have its own WC_API_Exception class.
