### ISSUE TITLE
Create Webhook documentation doesn't match functionality for empty secret

### ISSUE THREAD

**Issue by frankszymanski** [woothemes/woocommerce#10881]
The documentation for the create webhook API states that the API user's secret should be used if it isn't provided: "Secret key used to generate a hash of the delivered webhook and provided in the request headers. This will default to the current API user’s consumer secret if not provided ".

When creating a webhook leaving the secret blank, the secret is set to a blank string. The documentation should be updated to indicate that the default value is a blank string.

It may be worth noting that the code appears to try get the secret from the user meta info, but it doesn't appear that the secret is ever set in the user meta.

## STEPS TO REPRODUCE THE ISSUE

1. Enable the API and create API Keys
2. Create a webhook using the above json, replacing the delivery_url with a valid endpoint (e.. requestbin).
3. Create a SHA256 hash of the webhook body using a blank string as the secret and convert to base64. Compare to the signature sent in the webhook headers.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
It can't automatically generate a secret since we moved API keys to a new interface.
We can get some user data by default, like the username or email instead.
What you think?

**Comment by frankszymanski** [comment]
@claudiosmweb If a user can have multiple API keys assigned to them, then anything specific to the user might be OK, but isn't quite as robust in my opinion as using the API secret.
I never was deep in WordPress or PHP (enough to get around). The new API key interface won't let you get the secret associated with the current API Key when sending a create?

**Comment by claudiosmweb** [comment]
@frankszymanski nop, once authenticated, we don't now what keys are used.
