### ISSUE TITLE
Sales reports are inaccurate when an order with sales tax is refunded

### ISSUE THREAD

**Issue by stevetested** [woothemes/woocommerce#10885]
WooCommerce uses the following logic to create the sales report:
Total sales = All orders - Refunded
Net sales = Total sales - Taxes - Shipping - Shipping Tax

Net sales are calculated on total sales which already excludes refunded orders. This is causing a discrepancy in reports when the customer has refunded an item with tax.

Zen desk ticket: 412409-zd-woothemes

cc. @mikejolley

**Comment by mikejolley** [comment]
@stevetested In testing I found no issue. However, I think I may know whats up.

In the refunded order, did the guy enter the amount in this total, but not in the lines? https://dl.dropboxusercontent.com/s/gxo81s62je2unkt/2016-05-10%20at%2017.42.png?dl=0

If you don't refund the line itself, the refund won't have negative taxes which will cause this.

Debating whether or not we should disable the highlighted field and just enforce refunding lines to preven this. Thoughts?

**Comment by mikejolley** [comment]
cc @SiR-DanieL

**Comment by stevetested** [comment]
Ah, that makes sense. I will check with the customer. 

My thought is that you still want to keep line for refunds at the bottom, in case a customer wants to refund a partial amount. For example refunding $5 on that order because the product did not arrive on time. This would also make sense, because even though a partial refund was given, the merchant would still need to pay the full tax amount to the tax collection agency*.

* I confirmed this to be the case in California, and it may be similar elsewhere.

**Comment by SiR-DanieL** [comment]
I think that we shouldn't change this. If we want to refund something tax included we would do it directly from the line items. Also that works when selling downloadable files, you lose access to them when refunding the line item.

In some cases instead I just want to refund an amount for a reason, but I still have to pay taxes and the customer still has to have download permissions.

**Comment by decimoseptimo** [comment]
I came here to report exactly this. These are my findings:

```
Example April reports (2 items sold, 1100 each, 10% tax included. 1 item refunded)

gross sales = 2200
explanation: 1100 + 1100

refund = 1100

net sales prior refund = 2000
1000 + 1000

net sales after refund (as shown in reports) = 2000 - 1100 = 900
net sales after refund (what i think i correct) = 2000 - 1000 = 1000
```

I may be missing something, i just don't see where.
