### ISSUE TITLE
[API] Custom post_name when creating a product

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10888]
Hello,

when editing a product it's possible to set `post_name` to a custom value.
It would be great to set `post_name` also when creating a new product.

Sometimes we want a different `post_name` than the `post_title` from the beginning.
i.e: 

    'title' => 'CoolProduct',
    'name' => 'Brand CoolProduct'

Is it possible to just add it to the $new_product array in class-wc-api-products.php?

    $new_product = array(
		'post_title'   => wc_clean( $data['title'] ),
		'post_name'   => wc_clean( $data['name'] ),
		'post_status'  => isset( $data['status'] ) ? wc_clean( $data['status'] ) : 'publish',
		'post_type'    => 'product',
		'post_excerpt' => isset( $data['short_description'] ) ? $post_excerpt : '',
		'post_content' => isset( $data['description'] ) ? $post_content : '',
		'post_author'  => get_current_user_id(),
		'menu_order'   => isset( $data['menu_order'] ) ? intval( $data['menu_order'] ) : 0,
	);

Cheers,
Adis

**Comment by claudiosmweb** [comment]
We support it into the new REST API: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php

**Comment by ad-on-is** [comment]
That's great!
Could you still implement it in the WC API?

Because I'm working on it and I need this functionality in the future until I rewrite my code to the new WP API?

**Comment by claudiosmweb** [comment]
@ad-on-is fixed, still in the WP REST API we have a better support for it.
