### ISSUE TITLE
API v3 total_sales is missing

### ISSUE THREAD

**Issue by dagoebel** [woothemes/woocommerce#10898]
Whenever I import a new product via the API v3, the total_sales attribute is missing, even it is 0. 

This is important, when sorting by "orderby=popularity". Without the total_sales meta key, the product will be missing in the listing.

- Daniel

**Comment by claudiosmweb** [comment]
It's not missing, is a **read-only** field, you can't change it using the API.
Please check our documentation: http://woothemes.github.io/woocommerce-rest-api-docs/#products-properties

**Comment by dagoebel** [comment]
But it should be set to 0 if a product is imported. Because otherwise it will mess up with the sorting if this field is missing.

**Comment by dagoebel** [comment]
Are you really sure that it should be 

add_post_meta( $product_id, 'total_sales', **'0'**, true ); and not

add_post_meta( $product_id, 'total_sales', **0**, true );

**Comment by scottbasgaard** [comment]
Seeing this as well. Thanks for fix @claudiosmweb @mikejolley.

**Comment by claudiosmweb** [comment]
@dagoebel ?

**Comment by vladdvs** [comment]
for solve alredy uploaded products:
```
$products = $woocommerce->get('products');
foreach($products['products'] as $i => $product){
    printr($product['id']);
    $query = 'INSERT INTO wp_postmeta (post_id, meta_key, meta_value)
            SELECT * FROM (SELECT "'.$product['id'].'", "total_sales", 0) AS tmp
            WHERE NOT EXISTS (
                SELECT post_id FROM wp_postmeta WHERE
                meta_key = "total_sales" AND post_id="'.$product['id'].'"
            ) LIMIT 1; ';
    execute_your_query($query);
}
```

this will insert missing "total_sales" metakeys
