### ISSUE TITLE
Shipping destination settings - are they necessary?

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10894]
In the spirit of "Decisions, not Options", what do you think about removing these settings: http://cld.wthms.co/KZ3H/5akc2nSh

I've asked a few people, and nobody has been able to correctly tell me the difference between the first two options. I've watched some people read over those options, and instinctively switch to "Default to customer shipping address" just because it makes more sense (without actually knowing what it means).

Instead of settings, I propose setting up some filters instead (if there aren't already some). I would imagine that very few are using the "Force shipping to the customer billing address" option, and having the "ship to a different address" box checked automatically or not at checkout is purely preference.

As far as backwards compatibility goes, we can just leave the options in the database for a while - similar to the old "order notes" option. So this wouldn't be a breaking change by any means, and it will make the WooCommerce settings even less bloated, thus making on-boarding smoother :)

**Comment by mikejolley** [comment]
"I've asked a few people" isn't very reflective of the community at large is it. Plus you're asking people in the support area who are likely less experienced anyway :p

Forcing shipping to billing address only is a popular ask, and thats part of this setting.

**Comment by mikejolley** [comment]
This can fit into https://github.com/woothemes/woocommerce/issues/10672 since the new flow will need new options (only the force ship to billing will apply when done).

**Comment by WPprodigy** [comment]
I thought the same, but then I also asked some people who work with WooCommerce daily, and got the same result ;p. It's hard to make the connection between that setting and the "ship to a different address" checkbox being checked automatically or not.

And true, I guess this will need to be re-looked any anyways soon.
