### ISSUE TITLE
Backbone Modal select2 issue plus looks blurry

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#10896]
If select2 has multiple selected products then its height is not changing because overflow is set to auto. 
https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/backbone-modal.js#L81-L91
![select2](https://cloud.githubusercontent.com/assets/3774827/15154678/89400408-16fe-11e6-92eb-1d722fb798fd.PNG)
Also, select2 result text is not hidden while clicking on content area. It should be close.
![capture-2](https://cloud.githubusercontent.com/assets/3774827/15175348/918f574e-1785-11e6-8af0-79b3a9fd2f7f.PNG)

Additionally, Backbone Modal looks blurry due to the use of `transform` or `box-sizing`:
https://github.com/woothemes/woocommerce/blob/master/assets/css/admin.scss#L4912
https://github.com/woothemes/woocommerce/blob/master/assets/css/admin.scss#L4902-L4904

![capture](https://cloud.githubusercontent.com/assets/3774827/15175120/a5be3f56-1784-11e6-86e9-a4ba09bc4641.PNG)

![capture-1](https://cloud.githubusercontent.com/assets/3774827/15175121/a649a744-1784-11e6-8674-940c0e074236.PNG)

**Comment by claudiosmweb** [comment]
@shivapoudel submit a pull request.

**Comment by mikejolley** [comment]
The click seems to be a bug in select2.

**Comment by shivapoudel** [comment]
Modal blurry is not only for the products modal but also for others too. This [Google search](https://www.google.com/?gws_rd=cr,ssl&ei=o2MzV7COK8n9vATcp6eoAg#q=css+transform+translate+blurry
) must somehow make sense.

CC @mikejolley @jameskoster @claudiosmweb

**Comment by mikejolley** [comment]
The transform css centres the modal. I don't want to remove it.

**Comment by shivapoudel** [comment]
@mikejolley No need to remove the transform. Two options are present from my rough test:

* If box-sizing is refactor by @jameskoster for the backbone modal.
* If we detect the suitable article height and apply its odd number height in px.
