### ISSUE TITLE
WC_Order::calculate_taxes does not store taxes for shipping items

### ISSUE THREAD

**Issue by ragulka** [woothemes/woocommerce#10897]
## EXPLANATION OF THE ISSUE

When adding a new shipping item to the order, and calling `$order->calculate_taxes()`, then the taxes are correctly calculated, but for some reason, `taxes` is not stored for `shipping_items`. The equivalent (`line_tax_data`) is [stored for fees and line items only](https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L723), but [not shipping items](https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L735-L758).

I would expect the tax data to be saved for shipping items as well, since this is what happens when you click "Calculate Taxes" in Edit Order screen. Interestingly, that AJAX call is not using `$order->calculate_taxes()` at all, it [has it's own implementation](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-ajax.php#L1474-L1661).

I wonder if this is by design (if it is, then what's the reasoning?), or should `$order->calculate_taxes()` store `taxes` for shipping items as well?

With the current implementation, whenever a shipping method is added programmatically, there's no easy way to make sure the taxes are calculated and stored for shipping items. This in turn will show up in the Edit Order screen as shipping items missing tax data:

![screen shot 2016-05-11 at 14 03 31](https://cloud.githubusercontent.com/assets/593267/15178899/354b6e7c-1781-11e6-9884-7ac6247d8181.png)

## STEPS TO REPRODUCE THE ISSUE

```php
$order->add_shipping( $rate );
$order->calculate_taxes();
```

**Comment by mikejolley** [comment]
FYI this is taken care of in https://github.com/woothemes/woocommerce/pull/10259
