### ISSUE TITLE
Consider integration tests for your WP REST API endpoints

### ISSUE THREAD

**Issue by danielbachhuber** [woothemes/woocommerce#10905]
Hi!

On behalf of [Pantheon](https://pantheon.io/), I'm [writing a tutorial](https://paper.dropbox.com/doc/You-absolutely-need-test-coverage-for-your-WP-REST-API-project-MKvKy9DzoTQ2HYhbyWBxM) on why integration tests are critical for your WP REST API endpoints, and how you can go about writing them. 

Given your use of `register_rest_field()`, I think you could benefit from reading and applying the tutorial. And, because the tutorial isn't yet published, I'd very much appreciate any constructive criticism you have, so that we can make the tutorial an evergreen resource for the community.

Thanks in advance for your time. Happy to take any questions, comments, etc. you might have in this Github issue, or on the document itself (you'll need to be signed into Dropbox).

**Comment by claudiosmweb** [comment]
@danielbachhuber I was to start doing it next week, but for sure your tutorial will make things faster :)
Thanks.

**Comment by danielbachhuber** [comment]
> I was to start doing it next week, but for sure your tutorial will make things faster :)

Glad to hear!

Please do let me know if you'd like any feedback on your tests, run into questions about the tutorial, or so on. I have time available to help out a bit, and I want to make sure all of the supporting documentation around the REST API is easily accessible.

**Comment by mikejolley** [comment]
This is ongoing/being worked on. We don't need to track with specific issue. Thanks for reporting.

**Comment by danielbachhuber** [comment]
👍
