### ISSUE TITLE
[API] variation_attributes return slugs in options instead of names

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10908]
When fetching a product i get this kind of result. Notice that the option returned is the slug not the name.

    [variations] => Array
    (
    [0] => Array
        (
            [id] => 29104
            [attributes] => Array
                (
                    [0] => Array
                        (
                            [name] => Hardness
                            [slug] => attr_var_mattress_hardness
                            [option] => attr_var_mattress_hardness_weich
                        )

                    [1] => Array
                        (
                            [name] => Dimensions
                            [slug] => attr_var_mattress_size
                            [option] => attr_var_mattress_size_160-x-200
                        )

                )

**Comment by claudiosmweb** [comment]
@ad-on-is in what endpoint and API version?

Because don't seems to be possible.

v3: https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-products.php#L2475-L2488

WP REST API v1: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L326-L336

The slug must be correct, perhaps something you changed in the application.

**Comment by ad-on-is** [comment]
Sorry i missed to write the expected result:

    [variations] => Array
    (
    [0] => Array
    (
        [id] => 29104
        [attributes] => Array
            (
                [0] => Array
                    (
                        [name] => Hardness
                        [slug] => attr_var_mattress_hardness
                        [option] => weich
                    )

                [1] => Array
                    (
                        [name] => Dimensions
                        [slug] => attr_var_mattress_size
                        [option] => 160 x 200
                    )

            )

**Comment by ad-on-is** [comment]
compared to a simple product where I assign exactly the same attributes, I get this kind of result:

    [product] => Array
        (
            [id] => 31054
            [attributes] => Array
                (
                    [1] => Array
                        (
                            [name] => Hardness
                            [slug] => attr_var_mattress_hardness
                            [position] => 1
                            [visible] => 1
                            [variation] => 
                            [options] => Array
                                (
                                    [0] => weich
                                )

                        )
                    [3] => Array
                        (
                            [name] => Dimensions
                            [slug] => attr_var_mattress_size
                            [position] => 3
                            [visible] => 1
                            [variation] => 
                            [options] => Array
                                (
                                    [0] => 100 x 200
                                )

                        )

                )
