### ISSUE TITLE
Notice not displayed after login

### ISSUE THREAD

**Issue by saulfautley** [woothemes/woocommerce#10904]
## EXPLANATION OF THE ISSUE

When a user logs in, they are not shown the notice "You are now logged in as..."

It looks like this is happening because `WC_Session_Handler` is storing the queued notice with the `_customer_id` property value which is generated before the user is authorized. So when the user is logged in, the stored session data is no longer valid for that user.

## STEPS TO REPRODUCE THE ISSUE

1. Login from the Woocommerce My Account page.
2. No notice is displayed on successful login.

**Comment by mikejolley** [comment]
I think we can do away with that notice; the fact the account page changes and shows username is enough feedback.

**Comment by saulfautley** [comment]
It's not just about the login notice. The underlying cause of the issue means that you can't simply show a notice upon registration either, without coding in a hacky double-redirect. The same goes for logging in and registering from the guest checkout page, or storing any kind of ‘WC_Session‘ data upon user authorization for that matter.

If you want to have away with the login notice that's fine, but at least do it properly by removing the actual ‘wc_add_notice‘ call. Fixing ‘WC_Session_Handler‘ so that it updates the ‘_customer_id‘ property accordingly when a user is authorized is a separate issue that needs addressing.

If you don't have the time or manpower to fix it I'm happy to submit a pull request.

**Comment by mikejolley** [comment]
@saulfautley go ahead. I'd be curious to know why sessions are not lost if you register/login via checkout though. The same does not happen there.

**Comment by saulfautley** [comment]
@mikejolley Yes I saw that just now as well. It looks like the thing keeping the session alive is the following line in `WC_Session_Handler`:

```
add_action( 'woocommerce_set_cart_cookies', array( $this, 'set_customer_session_cookie' ), 10 );
```

It only fires when the user has something in their cart though. It even seems to work when logging in from the My Account page with something in your cart, i.e. the notice is now displayed.

I've tested calling `WC()->session->set_customer_session_cookie(true)` on the `set_auth_cookie` action and it seems to fix any sessions being lost upon user auth regardless of cart contents, but I feel like I do not know enough about how you guys have set up the cookies with regards to cache/etc to submit this as a fix for this issue.

Perhaps you could advise or take it from here @mikejolley?

**Comment by mikejolley** [comment]
Ah of course, I forgot about this.

Users without carts don't have sessions, thats why it's lost between the page loads. This is by design; having a session causes problems with caching systems and logged out users.

This should be left as it. If messages are needed for logged out users between page load, there is a query var that can be used.

**Comment by saulfautley** [comment]
Ok fair enough. The `wc_add_notice` upon login should at least be removed then, not so? Otherwise users with cart items will see it and users with empty carts won't, which is weirdly inconsistent.
