### ISSUE TITLE
WC API / CLI order taxes not calculated correctly

### ISSUE THREAD

**Issue by ragulka** [woothemes/woocommerce#10900]
## EXPLANATION OF THE ISSUE

1. When creating/updating an order with either WC API or WC CLI, taxes for shipping lines are not calculated. There's also no way to provide them manually. I would expect taxes to be correctly calculated.
2. Taxes are calculated based on the shop base country, not the customer's billing country. Since the storefront/cart calculates taxes based on customer's country, I would expect API/CLI follow the same pattern.

When you click "Calculate Taxes" in Edit Order screen, for an order that was created via API or CLI, the correct taxes are calculated.

## STEPS TO REPRODUCE THE ISSUE

1. Add a tax rate 20% for a country otehr than the store's base country (example `EE`) and apply it to shipping.
2. Add a customer, whose billing and shipping country matches the tax rate's country
3. Add a new order using WC CLI or WC API, specifying at least 1 line item, and 1 shipping item, using the ID of the customer in the other country
4. Observe that the newly created order uses taxes for store base country and does not have any shipping taxes at all

This happens on the `master` branch. Likely related to https://github.com/woothemes/woocommerce/issues/10897

**Comment by mikejolley** [comment]
Should be same fix as in #10897. Let me know if there are other issues.
