### ISSUE TITLE
Items do not leave the cart once checkout is completed

### ISSUE THREAD

**Issue by jbu915** [woothemes/woocommerce#10911]
In testing my website, the items are not leaving the cart once checkout has been completed. The web developer has told me there is some script missing in my version of WooCommerce.  I have updated all the plugins and WP as well.  Can you assist with this issue? www.austinsunderdawgs.com

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
> In testing my website, the items are not leaving the cart once checkout has been completed. The web developer has told me there is some script missing in my version of WooCommerce.

Actually you should find it's the gateway you're using. 

https://github.com/woothemes/woocommerce/blob/fa30a38c58373d9c3706cc0b7ae22032de3a2985/includes/gateways/paypal/includes/class-wc-gateway-paypal-response.php#L70

Gateways can handle it.

**Comment by georgejipa** [comment]
Hello!

I have the same problem. When I pay using paypal gateway (ipn or pdt, same result), the cart is not emptied. Actually "payment_on_hold" method is not even called.
