### ISSUE TITLE
[API v3] Bad product image names

### ISSUE THREAD

**Issue by dagoebel** [woothemes/woocommerce#10927]
Hi,

whenever I create a product with product images via the API, the product images are named sequentially like this uploads/2016/05/image-199.jpeg ... uploads/2016/05/image-200.jpeg

Actually for the sake of Google Image visibility, I want to give the images a better name.

How can this be done if I create products via the API?

**Comment by mikejolley** [comment]
WordPress controls this, not WooCommerce. See https://developer.wordpress.org/reference/functions/wp_upload_bits/#source-code
