### ISSUE TITLE
Order processing notification not sent when order status is changed under 'actions'

### ISSUE THREAD

**Issue by chris-64** [woothemes/woocommerce#10925]
When the order status is changed to _processing_ under the 'actions' column in the order overview, no notification email is being sent. 

This only seems to be the case when the order is changed to _processing_ on the **main order overview**. When the order status is changed to _completed_ the notification mail is sent without problems. And when the order status is changed to  _processing_ in the **order details page**, the email is sent without problems.

**Comment by mikejolley** [comment]
Tested in master (2.6) and this is working as expected. Should be fixed with the new version.
