### ISSUE TITLE
Allow thousand separator in Refund amount

### ISSUE THREAD

**Issue by szelpe** [woothemes/woocommerce#10920]
## EXPLANATION OF THE ISSUE

My current setup:
- thousand separator: "."
- decimal separator: ","
- number of decimals: 2

Which is not an uncommon setup.

If I want to refund an order and use the thousand separator in the number, the amount refunded would be invalid. E.g. in this case:

![image](https://cloud.githubusercontent.com/assets/192612/15302261/64a7283e-1bb2-11e6-8cf5-b6063ccb89e1.png)

I want to refund "2614", but I will end up refunding "2.61" instead, without warning.
I would assume I'm allowed to provide the Refund amount in a way it is displayed, in fact, most of the time I'd just copy and paste the price.

Even the price displayed on the button suggests it will refund "2614".

At least provide a warning or something in this type of scenario, though I'd prefer providing the price in the format it's displayed in.

**Comment by WPprodigy** [comment]
A value like "2.614,50" looks to be just ignored. When the separator's are reversed, "2,614.50" is also just ignored.
