### ISSUE TITLE
Filtering by category in Rest API

### ISSUE THREAD

**Issue by Crojach** [woothemes/woocommerce#10926]
## EXPLANATION OF THE ISSUE

I am making a get request to the V3 api which in the end looks like this

http://foo/wc-api/v3/products?filter[limit]=15&filter[category]=some-category&oauth_consumer_key=ck_xx&oauth_nonce=xx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=xx&oauth_version=1.0&filter%5Blimit%5D=15&filter%5Bcategory%5D=some-category&oauth_signature=xx

and am getting this as a response

DENIED - The requested resource requires user authentication. (XHR): GET ...

In the end what I figured out is that when the category filter is the first parameter then everything is working fine. Can you check this and confirm.

**Comment by claudiosmweb** [comment]
Please, check the REST API docs:

http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

![screenshot from 2016-05-17 15-46-06](https://cloud.githubusercontent.com/assets/1264099/15334906/81b40c00-1c46-11e6-81fc-ad1eb3344582.png)

**Comment by Crojach** [comment]
Just a follow up question.

The customer wanted to switch from using http to https and now I am getting again the same error. Everything worked while on http. Is there something else I have to do to make it work with https?

**Comment by JamesGeiger** [comment]
Just making sure @claudiosmweb is cc'd on this.

**Comment by claudiosmweb** [comment]
@JamesGeiger please don't do it, I already receive by email every comment here and you don't need to duplicate it without adding anything good for this conversation...

**Comment by claudiosmweb** [comment]
@Crojach follow the docs, this is only oAuth1.0 and have specs for it too, not to forget that you can use a lib for it too: http://woothemes.github.io/woocommerce-rest-api-docs/#index

**Comment by Crojach** [comment]
Thanks! Found what I was looking for.
