### ISSUE TITLE
Product Category Widgets not Changing # per Row

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#10928]
Howdy y'all,

So we have a scenario where a customer wants 5 items across in their product listings as opposed to the three default. Normally we'd use the [snippet here](https://docs.woothemes.com/document/change-number-of-products-per-row/), but they're using the WooCommerce Product Category widget. Their shop displays fine, but the widget seems to ignore the function - on loading it has five, then changes to 3. They're using Storefront and Arcade child themes.

How would we modify that snippet so it changed the output of the Product Category widget?

```
// Override theme default specification for product # per row
function loop_columns() {
return 5; // 5 products per row
}
add_filter('loop_shop_columns', 'loop_columns', 999);
```

Related Ticket: https://woothemes.zendesk.com/agent/tickets/417958

**Comment by mikejolley** [comment]
Replied on slack.
