### ISSUE TITLE
Internal Server Error when checking out with CC 

### ISSUE THREAD

**Issue by ericshun** [woothemes/woocommerce#10932]
I get the following errors in the console

![image 2016-05-17 at 1 11 38 pm](https://cloud.githubusercontent.com/assets/5192385/15331892/5f544018-1c31-11e6-8e69-229e1bf76a7b.png)

Any ideas how to fix this? Checkout works through paypal

I'm using newspaper 7 theme with woocommerce 2.5.5

**Comment by WPprodigy** [comment]
Hey @ericshun,

Have you tried to replicate this while having a default theme and just WooCommerce and the CC gateway plugin active?

Also, what gateway are you using aside from Paypal? If you are using a separate plugin for this, then you will need to contact the plugin authors through their appropriate support channel.

**Comment by ericshun** [comment]
Yes I still get the same problem with another theme. I am only using the woocommerce plugin for checkout.

**Comment by WPprodigy** [comment]
What gateway are you using for the credit cards then? Simplify?

And then I **think** the console errors are coming from Jetpack. Try disabling all plugins except WooCommerce and testing.

**Comment by ericshun** [comment]
Yes using Simplify. I tried deactivating everything and unfortunately still the same failed to load resource error :/

**Comment by WPprodigy** [comment]
>  I tried deactivating everything and unfortunately still the same failed to load resource error

The middle error was still showing, or all three?

> Yes I still get the same problem with another theme.

Is the other theme one of the core WordPress themes? Looks like themes can cause this problem: http://www.kriesi.at/support/topic/woocommerce-internal-server-error-500-on-checkout/

The url is accessible for me: https://www.thetractioncircle.com/checkout/?wc-ajax=checkout

**Comment by ericshun** [comment]
Only the middle error was showing. It's not a core wordpress theme but I think a pretty well supported one. http://tagdiv.com/ 

I cannot access that URL https://www.thetractioncircle.com/checkout/?wc-ajax=checkout 

Any suggestions of other tweaks to try?

**Comment by WPprodigy** [comment]
Can you try a default WordPress theme with only WooCommerce active just to be sure?

And you should just see something like this: http://cld.wthms.co/17ovX/RY9Zl3lY

**Comment by ericshun** [comment]
I have all plugins except woocommerce deactivated and am running the default theme. Still getting the error. http://cl.ly/1O1D1G130p3U

**Comment by mikejolley** [comment]
This is loading now https://www.thetractioncircle.com/checkout/?wc-ajax=checkout

If in doubt, look at your server error logs. There will be log entries pertaining to these errors. Error 500 is generic and hides the actual issue.

**Comment by ericshun** [comment]
What does it mean that its loading now? It looks the same to me and I still cant checkout

**Comment by mikejolley** [comment]
It's showing JSON which is a correct response. So something else is causing the error.

> If in doubt, look at your server error logs. There will be log entries pertaining to these errors. Error 500 is generic and hides the actual issue.

View the logs.
