### ISSUE TITLE
Inconsistent "Continue Shopping" button behavior

### ISSUE THREAD

**Issue by mzak** [woothemes/woocommerce#10930]
## EXPLANATION OF THE ISSUE

The behavior of the "Continue Shopping" button in the cart is inconsistent.  My understanding is that button is supposed to direct to the previous page, but it does not do so after adding an item to the cart from a single product view.

## STEPS TO REPRODUCE THE ISSUE

**Adding from single product view**
Configure WooCommerce to redirect shoppers to cart after adding item
View single product (http://mystaging.website/product/batman/)
Click "Add to Cart"
Click "Continue Shopping"
_You'll be redirected to the site homepage_

**Adding from Shop view**
View shop page (http://mystaging.website/shop/)
Click "Add to Cart" on any product
Click "Add to Cart"
Click "Continue Shopping"
_You'll be redirected to the site shop_

**Adding a related product**
View single product (http://mystaging.website/product/batman/)
Click "Add to Cart" for related product (Island)
Click "Continue Shopping"
_You'll be redirected to the product you were previously viewing (http://mystaging.website/product/batman/)_

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://mystaging.website
Site URL: http://mystaging.website
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.41
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #1928 - /shop/
Cart: #1929 - /cart/
Checkout: #1930 - /checkout/
My Account: #1931 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Twelve
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by WPprodigy** [comment]
I'm able to replicate the above. Also, if you add from an archive category page, you will be redirected back to that category's archive (same with tags).

So I'm thinking there is just an issue when adding from the single product page. It should take you back to that product page, definitely not back to the home page. Then the behavior would be consistent in always sending back to where they were. Breadcrumbs can be used from there to continue shopping as the customer pleases.

**Comment by WPprodigy** [comment]
Looks like the problem is that `wp_get_referer()` is empty after adding from the product page: https://github.com/woothemes/woocommerce/blob/master/includes/wc-cart-functions.php#L90

So it isn't empty when adding from the loop (those buttons use the ?add-to-cart url). May have something to do with the `add_to_cart_action()` method: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-form-handler.php#L601.

The problematic instance is when it's added to the cart via an actual form submission. From the WP docs regarding `wp_get_referer`:

> If page "refered" (form posted) to itself, returns false (because $_SERVER['HTTP_REFERER'] == $_REQUEST['_wp_http_referer'])

**Comment by WPprodigy** [comment]
Hmmm, found a solution - but messy. If you add another parameter to `wc_add_to_cart_message()` for $referer, you can pass along the current url in the methods like `add_to_cart_handler_simple()`.

Unfortunately, it gets messier. First, getting the current url isn't pretty, and the best solution I found requires the global $wp, and you need to be hooking into the `wp` hook. But that is before `wp_safe_redirect` can run...sooo...yea. I'm out ¯\\\_(ツ)\_/¯

**Comment by claudiosmweb** [comment]
@WPprodigy because we make the request in the same page and then we redirect ;)

So it fails in this check:

```php
$ref !== home_url() . wp_unslash( $_SERVER['REQUEST_URI'] )
```
