### ISSUE TITLE
REST API, update order -- Order Date changes when changing Order Status from 'pending'

### ISSUE THREAD

**Issue by tomsleeter** [woothemes/woocommerce#10943]
## EXPLANATION OF THE ISSUE

When updating order status via the Woocommerce REST API, the Order Date changes to current_time() when the previous order status = 'pending'.  This happens when updating order status via REST API -- updating status from the admin area does not affect order date.

Is there a reason for this?  The completed date should update (and it does update correctly), but I can't think of why you would ever want the order date / post date to update.  In our case, "pending payment" means the customer is paying by check.  Changing the original Order Date throws off customer service and our accounting processes.

The issue is with lines 2283-2286 abstract-wc-order.php within function update_status().  update_status is called by the Woo API.

```
if ( 'pending' === $old_status && ! $manual ) {
			$update_post_data[ 'post_date' ]     = current_time( 'mysql', 0 );
			$update_post_data[ 'post_date_gmt' ] = current_time( 'mysql', 1 );
}
```

Removing the above lines of code fixes the problem -- order date no longer gets updated.  But I imagine this will also cause issues for other woo extensions.

## STEPS TO REPRODUCE THE ISSUE

1. Create an order and set status to pending payment
2. Update the order to completed via REST API as detailed here: https://woothemes.github.io/woocommerce-rest-api-docs/#update-an-order
3. The order date will update to current_time().

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 1,000 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.45
PHP Post Max Size: 128 MB
PHP Time Limit: 99
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.49
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ 
						
							 No
Subscriptions Mode: ✔ 
						
							 Live

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (3) ###

WooCommerce AvaTax: by WooThemes / SkyVerge – 1.1.1-1
WooCommerce Subscriptions: by Prospress Inc. – 2.0.13 – 2.0.14 is available
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #945 - /shop/
Cart: #946 - /cart/
Checkout: #947 - /checkout/
My Account: #948 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Twenty Fifteen
Version: 1.3 – 1.5 is available
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by claudiosmweb** [comment]
>The issue is with lines 2283-2286 abstract-wc-order.php within function update_status(). update_status is called by the Woo API.
>
>if ( 'pending' === $old_status && ! $manual ) {
>$update_post_data[ 'post_date' ] = current_time( 'mysql', 0 );
>$update_post_data[ 'post_date_gmt' ] = current_time( 'mysql', 1 );
>}

`abstract-wc-order.php` is used in the entire WooCommerce, this don't seems to be an issue in the REST API.

@mikejolley should we keep updating the date or is the correct behavior?

**Comment by tomsleeter** [comment]
Assuming you need to keep updating the date, below is the REST API-specific call and another potential fix.  Set $manual = true in $order->update_status. class-wc-api-orders.php line 669:

current:

`$order->update_status( $data['status'], isset( $data['status_note'] ) ? $data['status_note'] : '' );`

change to:

`$order->update_status( $data['status'], isset( $data['status_note'] ) ? $data['status_note'] : '', TRUE );`

**Comment by mikejolley** [comment]
We do it so order dates match payment, since pending orders are temporary. Adding true would be my suggestion as above.

**Comment by karelgeenen** [comment]
Excuse me for asking guys, but I'm not sure how to continue on this issue.

I **don't want the order date to be changed** upon payment, what should I change?

Thanks.
