### ISSUE TITLE
Bugs when use the API from ajax.

### ISSUE THREAD

**Issue by mobisync** [woothemes/woocommerce#10941]
Hi,

Whenever I call the update API function (e.g. Update product), the AJAX requests seems to send a request with method "OPTIONS" before sending "PUT" method in the request (so basically, it is sending 2 requests- probably to verify accessiblity).

However, looking at the dispatch() function inside class-wc-api-server.php, the code doesn't accept requests that have method "OPTION", therefore all of our update API calls fail and we get the error "woocommerce_api_unsupported_method".

For example:

$.ajax({
            url: URL + 'wc-api/v3/products/4',
            data: JSON.stringify({"product": data}),
            dataType: 'json',
            type: 'PUT',
            error: function() {},
            success: function(){},
            contentType: 'application/json; charset=UTF-8',
            beforeSend: function (request)
            {...

If we add the "OPTIONS" case to the switch it works perfectly.

What did we do wrong here, and why do you omit "OPTIONS" method?

Please let me know ASAP if this is a bug.

Cheers

**Comment by claudiosmweb** [comment]
> Whenever I call the update API function (e.g. Update product), the AJAX requests seems to send a request with method "OPTIONS" before sending "PUT" method in the request (so basically, it is sending 2 requests- probably to verify accessiblity).

Don't seems to be an issuw with our REST API, seems like you need to properly write the AJAX call.
