### ISSUE TITLE
Shipping Zones REST API Endpoint

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10954]
Needs to cover;

- Creation
- Editing
- Getting all zones
- Getting a single zone

Zones should return data about the zone, as well as methods which are within the zone. There is no 'shipping method' api right now so this will be an array list of IDs, which will need expanding once this API does exist.

**Comment by mikejolley** [comment]
To add, once done the docs should also be added in a new branch on https://github.com/woothemes/woocommerce-rest-api-docs pending release.

**Comment by jeffstieler** [comment]
@mikejolley are you OK with shipping methods have their own endpoints?

I think it makes sense to separate methods (moreso than locations) from zones, since each method instance will have settings, etc.

The work I have so far separates locations: https://github.com/woothemes/woocommerce/compare/add/10954-shipping-zones-api?expand=1

**Comment by jeffstieler** [comment]
> There is no 'shipping method' api right now so this will be an array list of IDs

Is it possible to have multiple instances of the same shipping method in a zone? If so, this will need to be a list of objects, containing something like `instance_id` and `method_id`.

**Comment by mikejolley** [comment]
@jeffstieler yes thats possible. So you would need to know the instance ID too, if you wanted to configure one instance only.

**Comment by jeffstieler** [comment]
@mikejolley Did you want to include full CRUD for shipping methods (excluding instance settings)?

Without getting into a full Shipping Method instance settings API, this would just be CRUD for the `order` and `enabled` properties of a Shipping Method.

**Comment by mikejolley** [comment]
@jeffstieler Would be good if possible. Why do we need to exclude settings? Just thinking out loud without research ( 👊 me if wrong ), could we have something like:

Shipping Method level
- getX setX etc per setting
- list of props/settings it supports (we have this now)

Abstract level
- Handle the saving of all method level settings via settings api
- get_api_schema (?) method which translates the settings array into something for API

Then you could in theory expose all custom settings via API per method without controlling which settings get exposed.

cc @claudiosmweb

**Comment by jeffstieler** [comment]
> Why do we need to exclude settings?

I'm asking if it's in the scope of this issue, since you said:

> There is no 'shipping method' api right now so this will be an array list of IDs, which will need expanding once this API does exist.

**Comment by mikejolley** [comment]
Well, given this issue is specifically to do with zones, this part can probably be left until the shipping method apis are expanded. But whatever you do, I'd keep the above in mind as I think the final version will need this type of settings manipulation to be useful.

Waiting for feedback from Claudio.

**Comment by claudiosmweb** [comment]
> get_api_schema (?) method which translates the settings array into something for API

If you need something more than the schema, then will be better create an endpoint for it.

**Comment by mikejolley** [comment]
Closed in favour of https://github.com/woothemes/woocommerce/pull/11176
