### ISSUE TITLE
Include Custom Taxonomy in response

### ISSUE THREAD

**Issue by Crojach** [woothemes/woocommerce#10953]
I have been using the Rest API and everything is looking good except for Custom Taxonomies.

I have two of them "Status" and "Region" but don't know how to get them included in the response.

To get the product custom fields i added '?filter[meta]=true' to my query but can't find something similar to tell the API to return taxonomies as well.

Can you guys help me out?

**Comment by claudiosmweb** [comment]
> I have two of them "Status" and "Region" but don't know how to get them included in the response.

In which response?

**Comment by Crojach** [comment]
When making a call to /wc-api/v3/products?filter[meta]=true I get the usual response with the product_meta added.

What do I have to add as a parameter to get the custom taxonomities as well?

**Comment by claudiosmweb** [comment]
@Crojach you don't, you need to include then into the responses using WP filters.

**Comment by Crojach** [comment]
Thanks for that. Can you jut give me a link to the docs where this is described so I can let the devs know?

**Comment by claudiosmweb** [comment]
This filter: https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-products.php#L214

**Comment by JamesGeiger** [comment]
Hi @claudiosmweb - I am working with @Crojach on this. I checked out the linked filter, but can you provide an example of how to integrate that into the response? Do I need to use tax_query, and if so how do I implement that? Thanks!

**Comment by claudiosmweb** [comment]
@JamesGeiger here how to use filters in WordPress: https://developer.wordpress.org/reference/functions/add_filter/

**Comment by JamesGeiger** [comment]
@claudiosmweb ok, but that does not answer my question about `tax_query`? Are you saying to return the status and region (taoxnomies) for every product (like for the other custom fields) I need to write a filter? Or something like [this](https://wordpress.org/support/topic/send-custom-data-in-woocommerce-webhook#post-7355871) answer using and action?

**Comment by claudiosmweb** [comment]
@JamesGeiger if you need to use a custom `tax_query`, need to filter this https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-resource.php#L217

**Comment by JamesGeiger** [comment]
@claudiosmweb oh ok, in your opinion what would you recommend to return the status and region (taoxnomies) for every product (like for the other custom fields)?

**Comment by claudiosmweb** [comment]
@JamesGeiger this is your custom data, go ahead and do your best :)
