### ISSUE TITLE
bug report in wordpress . need help

### ISSUE THREAD

**Issue by sparkleandtwinkle** [woothemes/woocommerce#10960]
Hi Team,

Please can you help me understanding this issue.

Warning: fopen(/home/content/n3pnexwpnas01_data03/76/3196276/html/wp-includes/cbdom.ini): failed to open stream: Permission denied in /home/content/n3pnexwpnas01_data03/76/3196276/html/wp-content/plugins/woocommerce/includes/admin/cbdom.php on line 126

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/content/n3pnexwpnas01_data03/76/3196276/html/wp-content/plugins/woocommerce/includes/admin/cbdom.php on line 140

Warning: chmod(): No such file or directory in /home/content/n3pnexwpnas01_data03/76/3196276/html/wp-content/plugins/woocommerce/includes/admin/cbdom.php on line 141

Warning: include_once(/home/content/n3pnexwpnas01_data03/76/3196276/html/wp-includes/cbdom.ini): failed to open stream: No such file or directory in /home/content/n3pnexwpnas01_data03/76/3196276/html/wp-content/plugins/woocommerce/includes/admin/cbdom.php on line 142

Warning: include_once(): Failed opening '/home/content/n3pnexwpnas01_data03/76/3196276/html/wp-includes/cbdom.ini' for inclusion (include_path='.:/usr/local/php5_4/lib/php') in /home/content/n3pnexwpnas01_data03/76/3196276/html/wp-content/plugins/woocommerce/includes/admin/cbdom.php on line 142

sonali
chow2sonali@yahoo.com

**Comment by claudiosmweb** [comment]
Please, read this again:

>PLEASE NOTE:
>- These comments won't show up when you submit the issue.
>- Try to add as much detail as possible. Be specific!
>- **GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:**
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support
>- If you're requesting a new feature, explain why you'd like it to be added.
>- Search this repository (top of the page) for the issue and it has not been fixed or reported already.


And we don't have any `includes/admin/cbdom.php` inside WooCommerce.
