### ISSUE TITLE
cant access to downloadable file

### ISSUE THREAD

**Issue by abdeljalilq** [woothemes/woocommerce#10969]
hello im using woocommerce and autocomplete ORDER. i try to purchase a digital product i receive Email for ORDER Complete.when i try to click on links i get this msg : 
you you no longer have access to this file

Note : all digital product are granted for access
please any help

**Comment by mikejolley** [comment]
Why are you double posting? You have a topic on https://wordpress.org/support/topic/digital-product-not-downloading?replies=9 - don't spam our bug tracker.
