### ISSUE TITLE
Grouped product success message after adding to cart has wrong product title 

### ISSUE THREAD

**Issue by maximus80** [woothemes/woocommerce#10974]
When adding a grouped product to the cart, directly on single product page, the success message that is displayed, picks up the wrong post title: http://i.imgur.com/4prd8u7.png (using "Hello World" post title instead of "Shirt 4" product title). Tested with Twentysixteen theme.

**Comment by maximus80** [comment]
Thanks!

**Comment by Bluxart** [comment]
This problem with Woocommerce 2.6.2 not resolved.
I see the file ( wc-cart-functions.php ) and the change does not appear to have been carried out.
