### ISSUE TITLE
display of order in main dashboard.

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#10972]
When guest makes an order the display shows:
#ordernumber by FirstName LatName
example:
#13263 by Chris Beron

However if the order is made by registered customer it display as:
#ordernumber by NickName
Example:
#13263 TheHolyMan

The nickname means nothing to the seller. It is not easy to navigate between man114 and green90

Please change it to FirstName LastName like it is for guest orders or allow the owner of store to choose what way it will be displayed.

**Comment by mikejolley** [comment]
This uses the 'display_name' which is the correct data to use within WP admin. Look at the address if you want their provided billing name.

**Comment by test101test101** [comment]
While the data is true it's irrelevant for the sellers that use WC.
Also, the 'Search for a customer..." feature in the dashboard search in this NickName, it doesn't search in the real name of the customer.

**Comment by mikejolley** [comment]
it actually joins first and last names and searches them too.
