### ISSUE TITLE
Variation order is ignored on frontend

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/woocommerce#10971]
Using Twenty Sixteen and WooCommerce 2.5.5, the order of product variations seem to be ignored entirely.

Dragging them into different combinations doesn't seem to have any effect either; I've also tested with Storefront (Same result).

**Screenshots**
* Backend Setup: http://cld.wthms.co/193uK/8mTnpys4
* Frontend Order: http://cld.wthms.co/1jFoy/46xaC7SY

Not that I think it plays any roles for variations, but I've got the **Default Product Sorting** section set to *Custom Ordering + Name* (Screenshot at: http://cld.wthms.co/14ObZ/17v8tQfK) as found under **WooCommerce > Settings > Products > Display**.

Am I missing something obvious here?

**Comment by mikejolley** [comment]
Yes you are. You need to sort the attributes in products > attributes, NOT the variations.
