### ISSUE TITLE
Suggestions for code improving

### ISSUE THREAD

**Issue by NenadObradovic** [woothemes/woocommerce#10979]
Hi WooThemes,

1) Could you please fix escaping for all translatable labels in templates?
Example
`__( 'Password reset email has been sent.', 'woocommerce' )`
to replace with
`esc_html__( 'Password reset email has been sent.', 'woocommerce' )`

2) Is there some way to replace your select box html with some new select box? 
Example [Select2](https://select2.github.io/)

3) Could you add some filter or action to replace your quantity input fields html inside theme and not to override whole template file for quantity fields?

4) Could you improve your css/scss for product lists to be in grid logic instead of margin right and to remove margin right for last element in row? 
Example solution with sass

`
 .woocommerce {

    ul.products {
        list-style: none;
        margin: 0 -15px;
        clear: both;

        > .product {
            position: relative;
            float: left;
            display: inline-block;
            vertical-align: middle;            
            padding: 0 15px;
            margin: 0 0 30px;
            box-sizing: border-box;
        }
    }

    &.columns-1 {

        > .products {

            > .product {
                float: none;
                width: 100%;
            }
        }
    }

    $product_list_columns: ('columns-2', 'columns-3', 'columns-4', 'columns-5', 'columns-6');

    @for $i from 0 to length($product_list_columns) { 
        &.#{nth($product_list_columns,$i+1)} {
            $column_width: 100%/($i+2);

            > .products { 

                > .product {
                    width: $column_width;

                    $product_list_columns_label: #{nth($product_list_columns,$i+1)};

                    @if $product_list_columns_label == 'columns-6' {
                        @media only screen and (min-width: 1441px) {

                            &:nth-child(#{$i+2}n+1) {
                                clear: both;
                            }
                        }
                    } else @if $product_list_columns_label == 'columns-5' {
                        @media only screen and (min-width: 1281px) {

                            &:nth-child(#{$i+2}n+1) {
                                clear: both;
                            }
                        }
                    } @else if $product_list_columns_label == 'columns-3' {
                        @media only screen and (min-width: 769px) {

                            &:nth-child(#{$i+2}n+1) {
                                clear: both;
                            }
                        }
                    } @else if $product_list_columns_label == 'columns-2' {
                        @media only screen and (min-width: 601px) {

                            &:nth-child(#{$i+2}n+1) {
                                clear: both;
                            }
                        }
                    } @else {
                        @media only screen and (min-width: 1025px) {

                            &:nth-child(#{$i+2}n+1) {
                                clear: both;
                            }
                        }
                    }
                }
            }
        }
    }
 }
`
Code will be better and programmers/customers will easily change space between items or margin with one custom css code and responsive will always works fine, and also you will be able to add option in your WooCommerce General section for user to set any number of columns for shop list and to work always for any case.

I hope this helps you :)

Best Regards,
Nenad

**Comment by mikejolley** [comment]
1. Could be done in PRs, however the one you note is escaped when output later on.
2. WC Core has select2 and has classnames to enable it.
3. There are existing filters for this.
4. This could break existing themes. If you need custom CSS, dequeue WC CSS.
