### ISSUE TITLE
product_ids term meta not cleared properly

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#10980]
## EXPLANATION OF THE ISSUE

When I create product in code and assign terms to it using wp_set_object_terms counter in layered nav filter is not updated. Looks like the issue in wc_clear_term_product_ids function which deletes 'product_ids'  term meta based on term_taxonomy_id (taken from $tt_ids parameter). But layered nav filters use term_id in filter_* query string parameter and when it gets product_ids for specific term it uses term_id instead of term_taxonomy_id.

**Comment by mikejolley** [comment]
How to recreate? I ask because since WP 4.4 term splitting, these two values should be identical.

**Comment by mikejolley** [comment]
Seems 2.6 is not affected since the layered nav queries are rewritten and product_ids is no longer used.
