### ISSUE TITLE
2.6 - Is there any way to disable shipping - completely?

### ISSUE THREAD

**Issue by jconroy** [woothemes/woocommerce#10987]
Hi Guys,

Question...we're testing out 2.6 with subs at the moment and I can't find way to disable shipping - am I just losing the plot :-S and can't find the setting? or has it been removed and shipping is now always enabled?

Previously there was the enable/disable shipping checkbox http://cl.ly/1p0L2z3t1F29 which appears to be disabled by default.

In 2.6 we now start with http://cl.ly/1p353I3t0U34 with an empty zone with no shipping methods enabled http://cl.ly/0j0K1R050X3F.  I can't see anything in the options to disable http://cl.ly/2Z3L1S411l1m - but perhaps I'm not looking in the right place.

If I go to the checkout with the default set up I can't actually check out any of my existing products (because there is no valid shipping method) unless I go and specify them as virtual. I get why it works like this - but I can see the enabled by default (and no way to completely disable shipping) catching a few people out who otherwise might not have set their products as virtual or previously had to worry about shipping.

Anyways was chatting with @thenbrent and we thought we'd better ask in case it was an oversight.

Cheers,
Jason

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/goxkk1wiv45oh7w/2016-05-25%20at%2011.38.png?dl=0

**Comment by mikejolley** [comment]
Might actually be good to disable shipping if no methods exist, just so orders can go through if missed. Will adjust the wc_shipping_enabled() function for this.

**Comment by jconroy** [comment]
Boom, thanks! Kinda hidden away in there.

> Might actually be good to disable shipping if no methods exist, just so orders can go through if missed. 

Yeah possibly. Especially if the default is basically going to be _enabled_ now.

**Comment by dfvink** [comment]
The dropbox link is dead - is is possible to share anew?

**Comment by matt3224** [comment]
@mikejolley Can you repost please im wanting to switch shipping off all together also. Thanks!

**Comment by mikejolley** [comment]
The option is on the main WC settings page.

**Comment by matt3224** [comment]
I see, this:
![screen shot 2017-07-06 at 5 22 22 pm](https://user-images.githubusercontent.com/2401925/27921435-b8740414-626f-11e7-890c-fe620f4f6392.png)

Why does shipping still display in the variation product interface?
![screen shot 2017-07-06 at 5 22 15 pm](https://user-images.githubusercontent.com/2401925/27921459-c9e25660-626f-11e7-842c-557ca2084590.png)

**Comment by mikejolley** [comment]
Thats the edit product screen.

> The option is on the main WC settings page.

**Comment by matt3224** [comment]
Yes, the second screen is. My point is why is shipping still there even though I have disabled shipping

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/32slslddafu7pwm/2017-07-06%20at%2018.34.png

**Comment by matt3224** [comment]
Thats what I have set

**Comment by matt3224** [comment]
See my post above, with that screenshot in it

**Comment by mikejolley** [comment]
I guess shipping class is not hidden then. It does not enable shipping though. Shipping methods are not the same thing as shipping classes.

**Comment by DataVizWorks** [comment]
I finally found the option in >Settings>General>Shipping Locations

Not as straight forward as it looks like it used to be w/ enable/disable shipping

**Comment by vayurobins** [comment]
Hi. Would it not make sense to hide the shipping tab, when shipping is disabled in settings like @matt3224 mentions here? https://github.com/woocommerce/woocommerce/issues/10987#issuecomment-313446773
