### ISSUE TITLE
Shortcode Order Breaking with Numbers 

### ISSUE THREAD

**Issue by xtechgamer735** [woothemes/woocommerce#10981]
## EXPLANATION OF THE ISSUE

I am using version 2.5.5 on wordpress version 4.5.2. I am filtering items by using the the following shortcode [product_category category="win" orderby="title" order="asc"]. Items are names in the fashion of "Item 1 - <description>" "Item 2 - <description>" etc... I want them to display in order which works fine for Items 1 - 9 but Item 10 is placed in-between Item 1 and Item 2. Having tried ordering by every different type and without orderly variable nothing fixes this issue,

## STEPS TO REPRODUCE THE ISSUE

1. Add items names "Item 1", Item 2" etc... to "Item 9" in category win.
2. Use the shortcode "[product_category category="win" orderby="title" order="asc"]" on a page and see items are ordered Items 1 - Item 9 correctly,
3. Add an item 10 and see it get placed in-between item 1 and item 2.

### WordPress Environment ###

Home URL: http://www.oakmontclothing.com
Site URL: http://www.oakmontclothing.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.35
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.45
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (11) ###

Contact Form 7: by Takayuki Miyoshi – 4.4.2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.1
Oakmont Winner Finder: by Olly Downing – 1.0
SendGrid: by SendGrid – 1.8.1
Soundy Background Music: by Bertrand du Couédic – 3.2
TC Custom JavaScript: by Tiny Code – 1.1.0
TJ Custom CSS: by Theme Junkie – 0.1.6
Woocommerce Product Custom Options Lite: by phoeniixx – 1.3.7
WooCommerce: by WooThemes – 2.5.5
WP Crontrol: by John Blackbourn & Edward Dale – 1.3
WP Email Users: by techspawn1 – 1.2.4

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Store WP
Version: 1.22
Author URL: http://iograficathemes.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: store-wp/woocommerce/emails/customer-completed-order.php
store-wp/woocommerce/emails/customer-new-account.php
store-wp/woocommerce/emails/customer-processing-order.php

**Comment by WPprodigy** [comment]
Hi xtechgamer735,

This isn't really a bug. In lexicographic / alphanumeric sorting, 10 does go between 1 and 2. This would be why TV series use the S01E03 structure. To get your desired result, you will need to change the ordering arg, or add in the prefixing '0' to the 1-9 products.

You have three choices to orderby: menu_order, title, date, rand, or id. You could use id if you created them in a certain order, or you can use date and manually ensure their creation dates work sequentially in order.

Your last option is to use the `menu_order` option. This will let you manually drag and drop their sorting order: http://cld.wthms.co/17xc8/2p1qA0iw & http://cld.wthms.co/1fTpI/1AUczCEo

**Comment by xtechgamer735** [comment]
Hello WPprodigy,

Thank you for your reply and explanation of the issue! I have successfully done this using the menu_order sorting.

Many thanks,

xtechgamer735
