### ISSUE TITLE
comments_clauses and exclude_order_comments

### ISSUE THREAD

**Issue by renanno** [woothemes/woocommerce#10989]
Hi

I tried to submit a bug report to Woothemes directly, but they sent me here.

I have another plugin working in my Wordpress together with Woocommerce, Wordpress Advanced Ticket System.

Both WATS and Woocommerce modify comments query using 'comments_clauses' filter. Problem is that Woocommerce is not using any alias to 'wp_posts' table. WATS is, so as both of them are modifying the query, I have an error caused by Woocommerce.

Both change 'comments_clauses' filter, and Woocommerce changes also 'comment_feed_join' and 'comment_feed_where'.

wats/wats.php (1235)
`add_filter('comments_clauses','wats_get_comments_clauses');`

wats_get_comments_clauses function has, among other modifications, this:
`$clauses['where'] .= " AND wp3.post_status = 'publish' AND wp3.post_type != 'ticket' AND NOT EXISTS (SELECT * FROM ".$wpdb->commentmeta." AS wp2 WHERE wp1.comment_ID = wp2.comment_id AND wp2.meta_key = 'wats_internal_update' AND wp2.meta_value = 1) ";`

woocommerce/includes/class-wc-comments.php (33)
```
add_filter( 'comments_clauses', array( __CLASS__, 'exclude_order_comments' ), 10, 1 );
add_action( 'comment_feed_join', array( __CLASS__, 'exclude_order_comments_from_feed_join' ) );
add_action( 'comment_feed_where', array( __CLASS__, 'exclude_order_comments_from_feed_where' ) );

add_filter( 'comments_clauses', array( __CLASS__, 'exclude_webhook_comments' ), 10, 1 );
add_action( 'comment_feed_join', array( __CLASS__, 'exclude_webhook_comments_from_feed_join' ) );
add_action( 'comment_feed_where', array( __CLASS__, 'exclude_webhook_comments_from_feed_where' ) );
```

Function 'exclude_order_comments' (63) of Woocommerce excludes order comments from queries and RSS and include this clause (that's the clause that generate the error I mentioned before).

class-wc-comments.php (82)
`$clauses['where'] .= " $wpdb->posts.post_type NOT IN ('" . implode( "','", wc_get_order_types() ) . "') ";`

And includes this to the query:

... AND prevwp_posts.post_type NOT IN ('shop_order','shop_order_refund','shop_subscription') AND prevwp_posts.post_type 'shop_webhook' AND prevwp_posts.post_type 'wc_user_membership' ...

('prev' is my table preffix)

Which causes this to happen:

... Unknown column 'prevwp_posts.post_type' in 'where clause' ...

As you can see, everytime when a plugin adds an alias to that query (wp3 in this case), Woocommerce crashes it because is not using one. So I can't use any plugin that modifiy that query together with Woocommerce.

**Shoudn't Woocommerce also set an alias to it's custom query, instead of using table's name 'wp_posts'?**

Thank you!
Renan

**Comment by mikejolley** [comment]
@renanno share the full `$clauses['where']` after this plugin adds its code and any joins it makes or changes. The default query includes `$wpdb->posts` prefix on its FROM clause, so our query should work fine.

If however some other plugin changes the prefix due to a FROM clause change, this error would occur.

**Comment by mikejolley** [comment]
Actually looking again we do the join if not present!:

`
if ( ! strstr( $clauses['join'], "JOIN $wpdb->posts" ) ) {
			$clauses['join'] .= " LEFT JOIN $wpdb->posts ON comment_post_ID = $wpdb->posts.ID ";
		}
`

So in this case this must be present, but its being assigned `AS` some other name.

**Comment by renanno** [comment]
Hi Mike, thank you for helping me.

This is the complete function used by the other plugin:


```
function wats_get_comments_clauses($clauses)
{
	global $wpdb, $wats_settings, $current_user;

	if (!current_user_can('administrator'))
	{

		if ($clauses['fields'] !== '*')
			$clauses['fields'] = 'wp1.comment_ID';

		$clauses['where'] = str_replace('comment_approved','wp1.comment_approved',$clauses['where']);
		$clauses['where'] = str_replace('comment_post_ID','wp1.comment_post_ID',$clauses['where']);
		$clauses['where'] = str_replace($wpdb->posts.'.post_status','wp3.post_status',$clauses['where']);
		$clauses['where'] = str_replace('AND comment_parent = 0','',$clauses['where']);
		$clauses['orderby'] = str_replace($wpdb->comments.'.comment_date_gmt','wp1.comment_date_gmt',$clauses['orderby']);
		$clauses['orderby'] = str_replace($wpdb->comments.'.comment_ID','wp1.comment_ID',$clauses['orderby']);

		if ($wats_settings['visibility'] == 2 && is_user_logged_in())
		{

			$clauses['join'] = " AS wp1 LEFT JOIN ".$wpdb->posts." AS wp3 ON wp1.comment_post_id = wp3.ID ";
			$where = '';
			if ($wats_settings['ticket_visibility_same_company'] == 1)
			{
				$clauses['where'] = str_replace('user_id','wp1.user_id',$clauses['where']);
				$clauses['join'] .= " LEFT JOIN ".$wpdb->usermeta." as wp4 ON wp3.post_author = wp4.user_id ";
				$clauses['join'] .= " LEFT JOIN ".$wpdb->usermeta." as wp5 ON wp5.user_id = ".$current_user->ID." ";
				$where = " OR (wp4.meta_key = '".$wats_settings['company_meta_key_profile']."' AND wp5.meta_key = '".$wats_settings['company_meta_key_profile']."' AND wp4.meta_value = wp5.meta_value) ";
				$clauses['groupby'] = "wp1.comment_ID";
			}

			$clauses['where'] .= " AND wp3.post_status = 'publish' AND (wp3.post_author = ".$current_user->ID." ".$where." OR wp3.post_type != 'ticket') AND NOT EXISTS (SELECT * FROM ".$wpdb->commentmeta." AS wp2 WHERE wp1.comment_ID = wp2.comment_id AND wp2.meta_key = 'wats_internal_update' AND wp2.meta_value = 1) ";
			//$clauses['orderby'] = "wp1.comment_date_gmt ASC, wp1.comment_ID ASC ";
		}
		else if (($wats_settings['visibility'] == 1 && is_user_logged_in()) || $wats_settings['visibility'] == 0)
		{
			$clauses['join'] = " AS wp1 LEFT JOIN ".$wpdb->posts." AS wp3 ON wp1.comment_post_id = wp3.ID";
			$clauses['where'] .= " AND wp3.post_status = 'publish' AND NOT EXISTS (SELECT * FROM ".$wpdb->commentmeta." AS wp2 WHERE wp1.comment_ID = wp2.comment_id AND wp2.meta_key = 'wats_internal_update' AND wp2.meta_value = 1) ";
			//$clauses['orderby'] = "wp1.comment_date_gmt ASC, wp1.comment_ID ASC";
		}
		else
		{
			$clauses['join'] = " AS wp1 LEFT JOIN ".$wpdb->posts." AS wp3 ON wp1.comment_post_id = wp3.ID ";
			$clauses['where'] .= " AND wp3.post_status = 'publish' AND wp3.post_type != 'ticket' AND NOT EXISTS (SELECT * FROM ".$wpdb->commentmeta." AS wp2 WHERE wp1.comment_ID = wp2.comment_id AND wp2.meta_key = 'wats_internal_update' AND wp2.meta_value = 1) ";
			//$clauses['orderby'] = "wp1.comment_date_gmt ASC, wp1.comment_ID ASC";
		}
	}

	return $clauses;
}
```

Working together with Woocommerce, this is the complete query and the error:

`Unknown column 'prevwp_posts.post_type' in 'where clause' para a consulta SELECT SQL_CALC_FOUND_ROWS wp1.comment_ID FROM prevwp_comments  AS wp1 LEFT JOIN prevwp_posts AS wp3 ON wp1.comment_post_id = wp3.ID  WHERE ( ( wp1.comment_approved = '1' ) OR ( user_id = 13207 AND wp1.comment_approved = '0' ) ) AND wp1.comment_post_ID = 27251  AND wp3.post_status = 'publish' AND (wp3.post_author = 13207  OR wp3.post_type != 'ticket') AND NOT EXISTS (SELECT * FROM prevwp_commentmeta AS wp2 WHERE wp1.comment_ID = wp2.comment_id AND wp2.meta_key = 'wats_internal_update' AND wp2.meta_value = 1)  AND  prevwp_posts.post_type <> 'follow_up_email'  AND  prevwp_posts.post_type NOT IN ('shop_order','shop_order_refund','shop_subscription')  AND  prevwp_posts.post_type <> 'shop_webhook'  AND  prevwp_posts.post_type <> 'wc_user_membership'   ORDER BY wp1.comment_date_gmt ASC, wp1.comment_ID ASC  feita por require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/TheFox_child_theme/page.php'), comments_template, WP_Comment_Query->__construct, WP_Comment_Query->query, WP_Comment_Query->get_comments, WP_Comment_Query->get_comment_ids, W3_Db->query, W3_DbCache->query, W3_DbCallUnderlying->query, W3_Db->query, W3_DbProcessor->query, W3_Db->default_query`

**Comment by mikejolley** [comment]
See above fix.

**Comment by renanno** [comment]
PERFECT! Thank you!
