### ISSUE TITLE
Very minor styling issue

### ISSUE THREAD

**Issue by j-mccarthy** [woothemes/woocommerce#10988]
Hi, this is very minor issue, but as the 2.0 update had focussed on refining alignment of header elements I thought I'd bring this up.

On the site-header-cart area the cart icon is out of alignment from the amount and count. You can see it in the screenshot for the theme too. It's maybe 4-5 pixels out but noticeably out of alignment. 

Perhaps position: relative; top: 4-5px; would do? 

All the best!

**Comment by mikejolley** [comment]
What theme? WooCommerce core doesn't have a cart header widget and is not a theme so I don't know what you're referring to :)

**Comment by j-mccarthy** [comment]
Well that was silly, sorry.

I thought I was in the storefront issues area. 

I’m talking about Storefront 2.0.

**Comment by mikejolley** [comment]
cc @jameskoster

**Comment by jameskoster** [comment]
This was fixed in the 2.0.1 release fyi @j-mccarthy.

**Comment by j-mccarthy** [comment]
Hey James,

I thought it’d be picked up pretty quick, so I made sure I had the latest update before I sent this in. I don’t have any plugins installed - apart from WooCommerce and I don’t have any caching in place and the alignment is the same.



Cheers

**Comment by jameskoster** [comment]
It's looking good here; https://cloudup.com/cFtrau38who

Please open an issue on the Storefront repo and we can investigate further :)

**Comment by j-mccarthy** [comment]
Thanks James will do.
