### ISSUE TITLE
When the guest checkout is enabled the woocommerce is not working

### ISSUE THREAD

**Issue by mickbigda** [woothemes/woocommerce#10982]
## EXPLANATION OF THE ISSUE
When the guest checkout is enabled the woocommerce is not working ...

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.karolinaniwinska.com
Site URL: http://www.karolinaniwinska.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: pl_PL

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.17
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
SUHOSIN Installed: –
MySQL Version: 5.5.48
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Metoda Remote Post: ✔
Metoda Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (29) ###

BackWPup: przez Inpsyde GmbH – 3.3.1
Black Studio TinyMCE Widget: przez Black Studio – 2.2.9
CodeStyling Localization: przez Heiko Rabe – 1.99.30
Contact Form DB: przez Michael Simpson – 2.10.13
Formularze: przez Takayuki Miyoshi – 4.4.2
Easy Facebook Likebox: przez Sajid Javed – 4.2.5
Google Analytics by MonsterInsights: przez MonsterInsights – 5.5
Instagram Feed: przez Smash Balloon – 1.4.3
Limit Login Attempts: przez Johan Eenfeldt – 1.7.1
Pinterest RSS Widget: przez bkmacdaddy designs – 2.3.1
Pronamic Cookies: przez Pronamic – 0.3.1
Odnawianie miniaturek: przez Alex Mills (Viper007Bond) – 2.2.6
Page Builder by SiteOrigin: przez SiteOrigin – 2.4.8
SiteOrigin Widgets Bundle: przez SiteOrigin – 1.5.11
Nifty Newsletters: przez SolaPlugins – 4.0.14
TinyMCE Advanced: przez Andrew Ozz – 4.3.10.1
WP Canvas - Portfolio: przez Chris Baldelomar – 1.2
WP Canvas - Gallery: przez Chris Baldelomar – 1.51
WP Canvas - Responsive Videos: przez Chris Baldelomar – 1.10
WP Canvas - Shortcodes: przez Chris Baldelomar – 1.85
WP Canvas - Widgets: przez Chris Baldelomar – 1.7
Transferuj.pl Woocommerce payment module: przez Transferuj.pl – 1.1.3
WooCommerce: przez WooThemes – 2.5.5
WordPress Importer: przez wordpressdotorg – 0.6.1
WP Tryb Konserwacji: przez Designmodo – 2.0.3
WP Rollback: przez WordImpress – 1.3
WP Smush: przez WPMU DEV – 2.2.2
WP Canvas - Insert Code: przez Chris Baldelomar – 1.1
WP Canvas - Self Hosted Updates: przez Chris Baldelomar – 1.2

### Settings ###

Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Strona sklepu: #1400 - /sklep/
Koszyk: #1100 - /koszyk/
Zamówienie: #1101 - /zamowienie/
Moje konto: #1102 - /moje-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Meadowbrook - Premium
Version: 2.53.1
Author URL: http://angiemakes.com/
Child Theme: ✕ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: meadowbrook-premium/woocommerce/emails/admin-new-order.php
`

**Comment by WPprodigy** [comment]
Hi @mickbigda,

I can't replicate this. Can you try disabling all plugins except WooCommerce and switching to a default theme? After doing that, test again to see if the issue still occurs.

**Comment by gaserna50** [comment]
I have the same problem: Woocommerce doesn't give the customer the option of paying thru Paypal as a Guest

**Comment by WPprodigy** [comment]
Hi,

I'm sorry but this is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

What you are describing isn't easily replicated, meaning something on your site specifically is causing this. Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.
