### ISSUE TITLE
can't download digital files with "space" symbol in the file name

### ISSUE THREAD

**Issue by lz1nud** [woothemes/woocommerce#10990]
If you upload a file with spaces in the name like - "my file.zip" , you can't download it after purchase. It shows page 403, if you rename it to "my-file.zip", everything works.

**Comment by mikejolley** [comment]
That would be an invalid name. If you upload via WordPress, it actually sanitises the name with hyphens. Just tested this works as normal.

We cannot control what you upload outside of WordPress.

**Comment by lz1nud** [comment]
Yes, sorry. My mistake. I was uploading them throgh FTP as they were bigger than 2MB's.
