### ISSUE TITLE
Woocommerce/wordpress not functioning properly. Cancelling orders on it's own and sending only cancelled order emails.

### ISSUE THREAD

**Issue by griplsd** [woothemes/woocommerce#10992]

**Comment by griplsd** [comment]
WordPress 4.5.2 running U-Design theme.

`
### WordPress Environment ###

Home URL: https://phantomgrip.com
Site URL: https://phantomgrip.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.42
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.43
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (8) ###

flickrRSS: by Dave Kellam – 5.3.1
Get The Image: by Justin Tadlock – 1.0.1
Slider Revolution: by ThemePunch – 5.2.5.1
U-Design WooCommerce Integration: by Andon – 2.1.14
U-Design Shortcode Insert Button: by Andon – 1.1.7
WooCommerce: by WooThemes – 2.5.5
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.90
WP125: by Matt Harzewski (redwall_hp) – 1.5.4

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4704 - /shop/
Cart: #4705 - /cart/
Checkout: #4706 - /checkout/
My Account: #4707 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: U-Design
Version: 2.10.2
Author URL: http://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Github is our bug tracker, not a place to get product support.

If you need help with core, use our [support forum](https://wordpress.org/support/plugin/woocommerce) or if you need help with a WooThemes premium plugin, use our [helpdesk](https://support.woothemes.com).

I suggest you look into PayPal IPN as that is what it sounds like is broken on your site. https://docs.woothemes.com/document/paypal-standard/#section-9
