### ISSUE TITLE
[API v3] View product API mixes attribute slug and name

### ISSUE THREAD

**Issue by m-huber** [woothemes/woocommerce#10997]
Hi there,
when creating a variable product with identical attribute name and attribute slug, everything works fine. However, when the values for attribute name and attribute slug are different, those values get mixed and options are left blank/empty.

When using the view product API:
- _product.attributes.n.slug_ is actually the attribute name.
- _product.variations.n.attributes.name_ is actually the (unhyphenated) attribute slug.
- _product.attributes.n.options_ and _product.variations.n.attributes.m.option_ are empty
 
Here's the data I'm using to create the product:
```javascript
{
   "product":{
      "title":"product title",
      "type":"variable",
      "sku":"sku940",
      "attributes":[
         {
            "name":"attribute name 940",
            "slug":"attribute slug 940",
            "visible":false,
            "variation":true,
            "options":[
               "a",
               "b",
               "c"
            ]
         }
      ],
      "variations":[
         {
            "sku":"sku_v940",
            "regular_price":"100",
            "attributes":[
               {
                  "name":"attribute name 940",
                  "slug":"attribute slug 940",
                  "option":"a"
               }
            ]
         }
      ]
   }
}
```

Here's the (partial) view product response:
```javascript
{
   "product":{
      "title":"product title",
      "sku":"sku940",
      "attributes":[
         {
            "name":"attribute name 940",
            "slug":"attribute name 940",
            "position":0,
            "visible":false,
            "variation":true,
            "options":[
               ""
            ]
         }
      ],
      "variations":[
         {
            "sku":"sku_v940",
            "attributes":[
               {
                  "name":"attribute slug 940",
                  "slug":"attribute-slug-940",
                  "option":""
               }
            ]
         }
      ]
   }
}
```

**Comment by mikejolley** [comment]
I can see why this might be a little misleading, but it's because the attribute you're creating/assigning is not global - its text based. Text based attributes don't have 'slugs' - the name is stored. Your passed in slug is not saved anywhere.

If you look in Products > Attributes, this one won't exist. It's at product level. I'll see if we can get the docs improved in the new version.

If you create the global attribute in advance this won't happen.

cc @claudiosmweb
