### ISSUE TITLE
Woocommerce not compliant with VAT EU rules

### ISSUE THREAD

**Issue by Johanwalter** [woothemes/woocommerce#11007]
Hi,

WOOCOMMERCE is not compliant with VAT EU rules

There is a plugin EU VAT NUMBER from Woothemes to handle VAT but unfortunately the plugin does not  handle VAT properly ; this plugin tried to be compliant with rules from 2015 about selling digital products but does not handle shipping physical products and I guess is not compliant about purchaser based in the same country than seller.

Here are the rules for VAT in Europe - All this information have been confirmed by the accountants of our companies; both gave us exactly the same information one is in UK and the other is in France.

Let's take example with a company based in France.
A company based in France can sell to any country in Europe.
1 -  Orders from french customer (B2B or B2c) must have the french VAT applied even if a company is entering their french VAT EU Number. Since the company is also based in France, they will have the VAT back in their VAT declaration.
It is forbidden in Europe to have an invoice from a company based in the same country than the purchaser without VAT 

2 - Orders from a country out of France can exempt VAT for B2B if the purchaser has a valid EU VAT NUMBER.

3 - Orders in a country out of France must applied French VAT for B2C if the annual threshold to the ship to country is not reached, if the threshold of annual turn over to the ship to country is reached then VAT of the ship to country must be applied. 
Threshold should not be handle by Woocommerce or plugin, it is the responsability of seller to register to VAT in ship to country or create a company in the ship to country - Threshold could be handle by Woocommerce or plugin as a warming message.
Here's the threshold (2nd column) on europa website http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/traders/vat_community/vat_in_ec_annexi.pdf

**Comment by DavidAnderson684** [comment]
I don't think the WC devs see it as a role of WC core to comply with the tax rules of one particular geographic jurisdiction. That's a job for extensions. e.g. https://www.simbahosting.co.uk/s3/product/woocommerce-eu-vat-compliance/

**Comment by mikejolley** [comment]
> There is a plugin EU VAT NUMBER from Woothemes to handle VAT but unfortunately the plugin does not handle VAT properly ; this plugin tried to be compliant with rules from 2015 about selling digital products but does not handle shipping physical products

Thats incorrect. The extension existed before 2015 and does handle standard products.

Point 1 is in settings; you can choose to not take off VAT if the user is in the same country as store. This is the same as the UK so I know this works :)

2. Handled.

3. b2c are ignored; vat applied. It does not handle thresholds.

Closing as this issue is not related to WC core.

**Comment by Johanwalter** [comment]
@Mike Thanks for your answer. I have posted a ticket for presales questions of EU VAT NUMBER plugin (#425517) to make sure it handles VAT properly. Answer I got is that nothing meet my requirements, I need custom work, if I think it is a bug, I should post issue on Github.
Please check the ticket and answer I got, that's different from what you say

**Comment by mikejolley** [comment]
Looks like they just got confused between EU VAT for digital vs physical. The above information I posted is accurate.
