### ISSUE TITLE
woocommerce_account_navigation

### ISSUE THREAD

**Issue by anteksiler** [woothemes/woocommerce#11013]
Using WC 2.6 beta3 
Using `do_action( 'woocommerce_account_navigation' );` on my-account.php file. However, I cannot see any menu items being rendered.

It should at least render the contents of myaccount/navigation.php file, but it doesn't.

**Comment by bekarice** [comment]
you need to manually pull in the changes in c8527468c557c72edf1aa587cd79789764cbbafc, it was after beta-3 was tagged so the action doesn't exist yet 😸
