### ISSUE TITLE
WooCommerce REST API issue(invalid signature)

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#11019]
Hello,
I am Developing Android App for Woo Commerce Website using REST API and am able to successfully POST and GET data using rest API.

But problem is if i have external plugin installed in my website like (one of from below list)
1. Word App,
2. Security plugin,
3. Wp-transit  (used for language translation) 
i m getting result:
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

Also i am sure this error is caused when one of above plugin is activated and everything works these plugins are deactivated.

So Can you please tell me what is blocking REST API from working OR any other way so that installing any plugin won't cause  "Invalid Signature - provided signature does not match" error.

Thank you.
Please reply soon.

**Comment by mikejolley** [comment]
Can be related to your request or server:

http://stackoverflow.com/questions/32948988/invalid-signature-provided-signature-does-not-match-woocommerce-rest-api-calli

https://www.google.co.uk/?ion=1&espv=2#q=invalid%20signature%20-%20provided%20signature%20does%20not%20match%20woocommerce

If you're building an app now, I suggest building for 2.6's new API which has better authentication methods and is built on WP Rest API https://woocommerce.wordpress.com/2016/04/22/new-rest-api-based-on-the-wp-rest-api-in-2-6/
