### ISSUE TITLE
jQuery.payment needs update to support Maestro with 19 digits

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#11012]
Or version of jQuery.payment is 1.2.4 and we need to update to the latest version (1.4.1)

**Comment by arymaynart** [comment]
O problema está de volta na versão mais recente.

**Comment by claudiosanches** [comment]
@arymaynart not an issue on WooCommerce core.

**Comment by arymaynart** [comment]
@claudiosanches , it is an issue with you plugin then?
I tested on a fresh wordpress + woocommerce + [Cielo WooCommerce – Solução Webservice](https://br.wordpress.org/plugins/cielo-woocommerce/).
Cant use maestro debit card with more then 16 digits.

**Comment by Aerendir** [comment]
But isn't jquery.payment deprecated?

**Comment by claudiosanches** [comment]
@arymaynart here is not the place for it.
