### ISSUE TITLE
REST API product request fails as soon as a product has a sale-price

### ISSUE THREAD

**Issue by zz745** [woothemes/woocommerce#11025]
I`m requesting a product, for example
https://www.example.com/wc-api/v3/products/1234?consumer_key=[consumer_key]&consumer_secret=[consumer_secret]
to edit some values if required, such as availability or price.

Usually I get the expected JSON (product details or error message), but requesting a product with a sale-price returns nothing, not even an error message.
It`s still possible to update a product which has no sale-price yet. I can set a sale-price for the product, and the sale-price is set correctly in the shop. But as soon as the sale-price is set (whether through the API or in the backend), the API call fails. 

I can`t tell a date, but this worked well until shortly.
Happens on at least 2 different domains which worked well so far. Different Plugins/Themes, no major changes, just updates.

WC Version: 2.5.5
WP Version: 4.5.2
PHP Version: 5.5.35
WC Database Version: 2.5.5
API Version: 3.1.0

**Comment by claudiosmweb** [comment]
> But as soon as the sale-price is set (whether through the API or in the backend), the API call fails. 

Show me an example.
Turn on the WP_DEBUG and show me the errors.

**Comment by zz745** [comment]
Never thought a Plugin would mess with the API, but...

[02-Jun-2016 00:51:09 UTC] PHP Fatal error:  Call to a member function get_id() on a non-object in /homepages/21/d19090763/htdocs/clickandbuilds/alBurli/wp-content/plugins/woocommerce-german-market/inc/WGM_Template.php on line 1356

I will check the Plugin right away. Thank you for pointing me in the right direction...
