### ISSUE TITLE
Site admin & shop manager can't see customer details in thank you page

### ISSUE THREAD

**Issue by ryan-boder** [woothemes/woocommerce#11026]
In 2.5.3 a tweak was made to only show customer details on the thank you page to the customer.

https://github.com/woothemes/woocommerce/commit/14e03038e33d32b60c02a205c43bcdc7aa647612

Admins and shop managers should also be able to see that customer info. Can you change it so that $show_customer_details will be true for site admins and shop managers as well as the customer?

Our shop managers use that page when processing orders. Hiding the customer information slows down our process.

**Comment by claudiosmweb** [comment]
Not sure if admin or shop manager need to access this URL since you can already check by email and in the admin interface.
In fact any admin or shop manager receive any URL from this page.

**Comment by ryan-boder** [comment]
I agree they don't "need" to access the thank you page but ours do. We have a custom add-on for that page which has some additional information they use so it's more convenient to see it all in that page.

I think the tweak is great but I don't see any reason to hide the customer info from admins or shop managers who can get to that info with a few more clicks per order anyway. It seems logical that it would be visible to them just like it is to the customer.

**Comment by claudiosmweb** [comment]
> We have a custom add-on for that

Since it's a custom add-on you can do a custom template too for it.
Since is just an variable, you can check if the user is an admin or shop manager and display this information. https://codex.wordpress.org/Roles_and_Capabilities

> I think the tweak is great but I don't see any reason to hide the customer info from admins or shop managers who can get to that info with a few more clicks per order anyway

Admins and shop managers don't receive this link, so there's no need to allow it on WooCommerce core.
