### ISSUE TITLE
Check Booking Availability being Displayed during Checkout for Non Bookable Products

### ISSUE THREAD

**Issue by ndoolin** [woothemes/woocommerce#11024]
"Check Booking Availability" Payment Option being Displayed during Checkout with Non Bookable Products in Cart.

**Comment by WillBrubaker** [comment]
Howdy,

Bookings support is not provided in this repository. You will need to open a ticket from your WooThemes.com account. If you have already opened a ticket, please give me the id number and I'll make sure it gets to the right people.

**Comment by ndoolin** [comment]
#426683

**Comment by WillBrubaker** [comment]
Oh, this was specific to WooCommerce 2.6, correct? Thanks, we're aware and have merged code in to Bookings for this.

**Comment by ndoolin** [comment]
Yes, correct. :-)

**Comment by WillBrubaker** [comment]
Sorry for my confusion. I'll update the ticket as well.

**Comment by ndoolin** [comment]
No problem, Thanks!
