### ISSUE TITLE
Frontend AJAX Cart events

### ISSUE THREAD

**Issue by apsolut** [woothemes/woocommerce#11020]
## EXPLANATION OF THE ISSUE

Frontend AJAX Cart events
We're developing a plugin for adding editing gifts/free products on the cart page, and since the cart has been AJAXified we're having problems submitting the cart form and responding to cart updates (triggering the submit event on the cart form does nothing, and none of the objects/methods in frontend cart.js are accessible in any way?)...   

It would be great if we had a way to trigger submit event on the cart form after updating/modifying some values and some events triggered if/when the cart is submitted and when the new cart content/html is loaded/replaced so we can run some code and update our cart-related frontend components appropriately...

+ Let`s say that we want to offer extra products from widget area that will be carousel/slider.
(event triggers would be useful.)

Right now we can enable input "Update Cart" and re-submit...

## SYSTEM STATUS REPORT

```
4.5
2.6.0-beta-3 
```

**Comment by mikejolley** [comment]
If you need something for your _own_ products, it would be nice to submit a PR directly in future. I'll handle this one.
