### ISSUE TITLE
How to extend the shema of the REST-API

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11028]
I would add some extra fields to the new Rest-API `wp-json/wc/v1/product` endpoint. I use the filter in the `WC_REST_Products_Controller` for that. But how can i extend the schema for the products https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1689-L1692. 

Or must i use another way with register_rest_field() to do that?

**Comment by mikejolley** [comment]
@claudiosmweb ideas?

**Comment by claudiosmweb** [comment]
Just use the `register_rest_field()` function.
Here the docs for it: http://v2.wp-api.org/extending/modifying/

And here an example for you:

```php
add_action( 'rest_api_init', function() {
	register_rest_field( 'product', // Object type.
		'custom_field_name', // field slug.
		array(
			'get_callback' => function( $object, $field_name, $request ) {
				return get_post_meta( $object[ 'id' ], '_' . $field_name, true );
			},
			'update_callback' => function( $value, $object, $field_name ) {
				if ( ! empty( $value ) ) {
					return update_post_meta( $object->ID, '_' . $field_name, sanitize_text_field( $value ) );
				}
			},
			'schema' => array(
				'description' => __( 'Description here.', 'woocommerce' ),
				'type'        => 'string',
				'context'     => array( 'view', 'edit' )
			),
		)
	);
} );
```

**Comment by danielhuesken** [comment]
Yes, but how schuld i do that to extend coustomers and there one filed in the billing_address data.
Same is with the variations array for products.

I think the register_rest_field() function is very limited for adding some fields.

**Comment by claudiosmweb** [comment]
> I Think easiest is to add filters for the schema array and fo the collations too.

Not a standard in the WP REST API, so no new filters... And still possible do manipulate it using the `$wp_rest_additional_fields` global variable.

**Comment by claudiosmweb** [comment]
@danielhuesken sorry! I just saw, no away to use this global variable.

**Comment by huykon** [comment]
@claudiosanches  I have tried your code but still now not working. Any solution for this?
