### ISSUE TITLE
[API] Bulk-Import takes too long.

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#11029]
Hi,

I have a CSV with about 4.000 products, which I try to import via the API.
Problem is, it takes about 5 hours to import these products.

What I've tried.

A) run 100 products per bulk in a for-loop until all 4.000 are iterated
B) set the `woocommerce_api_bulk_limit` to 10.000 and run everything at once

Is there anything I can do to improve the performance?

Cheers,
Adis

**Comment by claudiosmweb** [comment]
Nop, is not the "bulk", is the volume of data too. It will be improved once we have our CRUDs done.

**Comment by ad-on-is** [comment]
Hi,

Does that mean this problem is *only* API-related? 
Or is it also possible to additionally improve performance by tweaking the environmental settings (i.e. php, mysql, apache, etc.)?

Cheers,
Adis

**Comment by claudiosmweb** [comment]
> Does that mean this problem is only API-related? 

Not related to API, related of how WP save all the data and will be improved with our CRUDs.

>  Or is it also possible to additionally improve performance by tweaking the environmental settings (i.e. php, mysql, apache, etc.)?

Yes, can help.
