### ISSUE TITLE
Product Category Images Not Preserved During Update

### ISSUE THREAD

**Issue by ndoolin** [woothemes/woocommerce#11023]
Product Category Images are not preserved from Production 2.5.5 to 2.6 Beta 3 Update
Default "Woo" Image being displayed for all Product Categories

**Comment by mikejolley** [comment]
Just tested - the images do disappear, instead you run the data update (there is a prompt). Once complete, images return. Confirmed working.

**Comment by ndoolin** [comment]
The Data Update has been running for the past 24 hours.
Is there way to restart it?  My WC DB is still showing 2.5.5

Thanks!

-Nick

**Comment by ndoolin** [comment]
Just Deactivated and Reactivated the Plugin and Clicked the Prompt to Run the Updater Again.
Message Bar is still being displayed up top.

"WooCommerce Data Update - Your database is being updated in the background."

DB Logs shows the following.

06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_options
06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_termmeta
06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_zones
06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_zone_methods
06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_refunds
06-02-2016 @ 10:22:29 - Queuing 2.6.0 - wc_update_260_db_version

**Comment by ndoolin** [comment]
Looks like DB Update Errors

[Thu Jun 02 15:22:16.678777 2016] [:error] [pid 26984] [client XXX.XXX.XXX.XXX:20938] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_shipping_zone_locations ADD KEY location_type_code (location_type(40),location_code(90)) /* From [xxxxx.xxxxxxx.com/wp-admin/plugins.php?action=activate&plugin=woocommerce%2Fwoocommerce.php&plugin_status=all&paged=1&s&_wpnonce=7821a45b33] in [/xxxxxxxx/xxxxxxx/wp-content/plugins/woocommerce/includes/class-wc-install.php:403] */ made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), call_user_func_array, WC_Install::install, WC_Install::create_tables, dbDelta, referer: https://xxxxx.xxxxxxx.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

Similar Error Messages for tax_rate_state and tax_rate_country

**Comment by mikejolley** [comment]
Those alter table errors shouldn't stop execution - thats a known issue and logged in WP core trac.

Are there PHP errors in your PHP error logs? Is cron working on your site? WP DEBUG BAR and WP DEBUG BAR CRON plugins can tell you more.

**Comment by mikejolley** [comment]
If you can gather more feedback based on above, you can email me at mike.jolley@automattic.com - the updater was something I wanted more feedback on before we release.

**Comment by WillBrubaker** [comment]
@mikejolley we have a ticket on this if that helps 426683

**Comment by mikejolley** [comment]
@WillBrubaker the updater did not dispatch due to password protection. It's fine after update.
