### ISSUE TITLE
Eastern order names

### ISSUE THREAD

**Issue by DuckDagobert** [woothemes/woocommerce#11027]
Since Asia is really up and coming in ecommerce, but they use a Eastern order naming convention (Last name, First Name instead of First Name, Last Name) I think we should perhaps add a condition if base_country Hungary, China, Japan, Korea, Malaysia, Singapore, Taiwan, Vietnam, Hong Kong, Macao then switch it around by php.

I already set this in my functions.php, so I can contribute the code if you want to integrate this.

**Comment by mikejolley** [comment]
I assume if would go inside https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-countries.php#L544-L557? Feel free to submit a PR, but if you can back this up with examples of stores within each country that would be useful. JP and TW are the only ones we format last before first, and no users from the other countries have raised issue.
