### ISSUE TITLE
REST API & Product Add-ons

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11036]
I'm using the latest version of WP, WC and Product Add-ons plugin. I am unable to get the product add-ons I set on WooCommerce in the product meta while using the REST API to view a product. What can I do to show them or is this something that is being worked on?

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

**Comment by mikejolley** [comment]
Add ons is not integrated with the rest API.

**Comment by amjad0** [comment]
is there a way to integrate it?

**Comment by amjad0** [comment]
@mikejolley any plans on integrating Add ons with the API soon?

**Comment by claudiosanches** [comment]
@amjad0 need to contact the WooCommerce Support: https://woocommerce.com/my-account/tickets/
Since here we deal only with WooCommerce core.

**Comment by gregBerthelot** [comment]
@mikejolley did you manage to get product addon with the REST API. I can get add on added on product but not global addon

**Comment by peterfabian** [comment]
As of version 6.9.0, Product Add-ons support REST API: https://woocommerce.com/document/product-add-ons-rest-api-reference/
