### ISSUE TITLE
API: Rest-API and handling of image download

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11034]
In moment the REST-API downloads images, every time a url is given. I think it is better that the `wc_rest_upload_image_from_url( $image_url )` function, will check if the $image_url alredy a WordPress image url and than only give back the image id and not copy it again.

**Comment by claudiosmweb** [comment]
> In moment the REST-API downloads images, every time a url is given

Yes and no... Just pass the attachment ID and will stop upload the image again.

**Comment by danielhuesken** [comment]
On categories you can only pass the url and than every time a donwload will be done.

**Comment by claudiosmweb** [comment]
@danielhuesken I'll fix it then.
