### ISSUE TITLE
House number validator

### ISSUE THREAD

**Issue by DuckDagobert** [woothemes/woocommerce#11031]
Hey,

in our last ~10.000 orders we realised a issue quite often: people put in the street, but forget their house number. (around 2-3% of cases)
We could easily solve this by using this code, which prompts an error message when wc checks other required fields:

`/* Split House numebr in stree field and Validate */
add_action( 'woocommerce_after_checkout_validation', 'generate_street_error_notice', 10, 1 );
    function generate_street_error_notice( $this_posted ) {
    $shipping_add=(isset($this_posted['shipping_address_1']) && $this_posted['shipping_address_1']!='')?$this_posted['shipping_address_1']:$this_posted['billing_address_1'];
            if(!isset($_SESSION['street_split']))
                {
                    if (!preg_match('#[0-9]#',$shipping_add)){
                    $_SESSION['street_split']=1;   
                    wc_add_notice( '<div class="woocommerce-error">' . __('It seems you forgot your house number. Please add it after the street name.<br>If it is already there, please ignore this message and click on place order.','woocommerce') . '</div>', 'error' );
                    }
                }
            else
            {
            unset($_SESSION['street_split']);
            }
    }
/* End Split House numebr in stree field and Validate */`

(sorry for formatting, dont know how to do it properly in github)

Should there be countries where house numbers are not used, these could be easily excluded. Moreover this triggers on the first try only anyways, so even in case of a false positive, the customer can check out.

This saves a lot of time as you do not need to check with the customer for their house number and you do not have to handle returns/issues with delivery companies because of missing house numbers.

**Comment by mikejolley** [comment]
I find it hard to believe this - address line 1 is common practice on address forms. Amazon for example: https://dl.dropboxusercontent.com/s/6tthe1waekl5bnq/2016-06-02%20at%2013.36.png?dl=0

Additionally, some addresses don't have numbers. e.g. some houses have names. Therefore this type of validation would be unreliable.

There are address validator plugins should you wish to use one. Or you could tweak the placeholder text https://dl.dropboxusercontent.com/s/24xhpj8d0bxenr4/2016-06-02%20at%2013.38.png?dl=0

cc @jameskoster

**Comment by mikejolley** [comment]
Closing as validator is not something that should be in core. Text tweaks would be fine.

**Comment by DuckDagobert** [comment]
All APIs for all European shipping providers demand a separate house number field; check DHL, DPD, Correos, UK Post, Hermes, post.at, post.ch,... APIs
Amazon does the splitting in backend, as we did in the past too, but now moved it to frontend.

**Comment by mikejolley** [comment]
For shipping labels maybe, but that doesn't justify a new field nor restrictive validation rules. Have you looked into why the users forgot to add the number? Label text? Bad auto-complete?

**Comment by jameskoster** [comment]
@DuckDagobert seen this? https://www.woothemes.com/products/postcodeaddress-validation/

**Comment by DuckDagobert** [comment]
"For shipping labels maybe" - yeah what else? No one delivers it themselves, so everybody needs to create shipping labels. And if there's no number, you have to send an email/create a ticket, wasting employees time (and company's money)

I suggest in any case to at least change the label of address_1 to "Street & house number" (this helped reduce to the number for us to 2-3%, was higher before), but it's up to you to decide. I have set it for myself already, just a suggestion other people might profit from.

@jameskoster thanks, yep, seen it, but not really helpful as we deliver to ~16 different countries on a daily basis and it's for UK, US & NL only. Moreover you have to pay for it, even though you only need to check if there is a number or not.

**Comment by mikejolley** [comment]
> "For shipping labels maybe" - yeah what else? 

That was regarding an extra field, which would be overkill in this case.

**Comment by DuckDagobert** [comment]
Totally agree. Also an extra field would have the disadvantage that "house number" is not defined in the autocomplete in browsers/password managers (see autocomplete & autocompletetype). Thats why we use the validator.

**Comment by mikejolley** [comment]
@jameskoster lets look at this along with #10672

**Comment by addrexx** [comment]
I'm with Addrexx and we see this issue happen quite frequently.  

As Mike Jolly mentioned, it is true that some houses don't have house numbers ( this happens alot in Ireland ).  In other countries, the house number trails the street name.  This occurs in much of Europe and Scandanavia.  

Other countries such as United Arab Emirates will not deliver to a house number, all shipments must be sent to a PO Box.  Finally, countries such as Australia and New Zealand combine the apartment and house together ( 13/7 Green Street).  

We will be happy to discuss this further and see if we can help.  Thanks!
