### ISSUE TITLE
Forcing Local Pickup to always be free?

### ISSUE THREAD

**Issue by ryanr14** [woothemes/woocommerce#11045]
I was curious to know why Local Pickup currently will always be free if any store owner wanted to use it in 2.6? I can imagine someone wanting to charge something for a customer using Local Pickup, not to mention setting pickup times/windows somehow. 😄

Nonetheless, they could for certain create a zone for the approved zip codes and rename it to Local Pickup to charge for it. But if there is a default method called Local Pickup that is essentially stripped back Free Shipping with a new title, is there something better we can do with that method?

It seems to be either made redundant by Free Shipping (that has more flexibility), or adding a specific zone and adding a renamed Flat Rate method to charge for Local Pickup.

Is a Local Pickup method with a cost field, address field, and perhaps pickup hours field too much? I know it starts encroaching on Local Pickup Plus, but it seems like a redundant method at the moment. I can always be missing something though. 😛 

I'll take my answer off the air, thanks!

**Comment by mikejolley** [comment]
You'd charge someone to pick up an item??!! Wow. 

The description field could be used for those additional details, and the difference between local pickup and free is tax - it will tax based on shop location instead of shipping address. So there is a subtle difference.

**Comment by ryanr14** [comment]
You never know what a store owner wants, maybe they're paying someone to operate/run a pickup location and pay for that through local pickup fees (just imagining wild scenarios). Thanks for explaining the tax difference. 😄

**Comment by test101test101** [comment]
@mikejolley  I think simply people don't understand that Shipping isn't always Shipping. It's not only the costs of the Shipping itself.. Its also the cost of packing, materials, working hours of workers to deliver the item to post office, gas etc... This is why it's should be called 'Shipping & Handling' rather than just 'Shipping'.  Some of these costs are also apply for 'Pick Up'. And here is another concept... Shelf Time is also a cost for a merchant.

**Comment by mikejolley** [comment]
Every pickup/collection service I've ever used has been free. Maybe just me :)

**Comment by rocketeer76** [comment]
It's getting more popular to "give" away products. Just pay shipping and handling :) Changing shipping to shipping & handling might reflect the reality better than just calling it shipping!?

**Comment by test101test101** [comment]
@rocketeer76  No, but changing the title helps people to understand why it's not always free.
I've seen stores where Pick Up service cost money while Shipment is free!
Some merchants pay fixed amount, no matter how much they send (until a specified limit)
So it's easier for them to ship and forget rather then handling a client who wants to pick up.

My point is that there are many kinds of merchants.... let each one deiced what is best for his business.
