### ISSUE TITLE
How to customize product category page?

### ISSUE THREAD

**Issue by chaiyapk** [woothemes/woocommerce#11046]
Hello

I try to add new product category on Products -> Categories but in section "Custom setting for this taxonomy (and nested):" display like picture in the attached file. There is no setting display. So, i cannot customize the product category page. 

![screen shot 2559-06-05 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/19757626/15804073/30f57db4-2b26-11e6-86bf-27fa23aeab96.png)

Could you please help?

**Comment by mikejolley** [comment]
This is not part of WooCommerce. Please raise with the theme author.
