### ISSUE TITLE
Rest API & Plugin Hooks

### ISSUE THREAD

**Issue by itjunkii** [woothemes/woocommerce#11043]
Does the REST API trigger hooks in other plugins such as woocommerce_thankyou

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

And the answer is: Yes and no, it depends on the hooks.
