### ISSUE TITLE
Getting 401 error 'Invalid Signature - provided signature does not match'  after upgrading to 2.6 - python woocommerce module

### ISSUE THREAD

**Issue by babinos87** [woothemes/woocommerce#11040]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

Hi,

I am using the python module to connect to my wooCommerce plugin on wordpress (I use WP version 4.5.2). 

Today I installed Woocommerce 2.6 beta-4 (from 2.5.5 that I used) and changed from the wc-api to WP REST API.

But now I get authentication error like below (response from the url: /wp-json/wc/v1/customers):

{'code': 'woocommerce_rest_authentication_error', 'data': {'status': 401}, 'message': 'Invalid Signature - provided signature does not match.'}

I used the same setup as in 2.5.5 that was connecting and fetching data without issues. Only difference is that I updated the WP plug-in to WooCommerce 2.6 beta4 and switched to use the WP-API. Configuration of python module is like:

from woocommerce import API

wc_api = API(
            url=conf.client_api_url,   # My site from config
            consumer_key=conf.consumer_key,    # Regenerated API keys after plug-in update just in case this was the issue but still getting 401
            consumer_secret=conf.consumer_secret,
            wp_api=True,  # This was set to False previously, I switched to WP API now
            version='wc/v1', 
            verify_ssl=False   # Same as previous version
        )

wc_api.get('customers')

This URL is generated by python:

http://<my-site>/wp-json/wc/v1/customers?oauth_consumer_key=<my_key>&oauth_timestamp=1464957745&oauth_nonce=b762a4d50882fac8394347283bf86ed58edde861&oauth_signature_method=HMAC-SHA256&oauth_signature=ltHypsSGhJTySNdPFyFG6M%2FEQNhNMRTjRfboeJORZ6U%3D

Wondering if there is any problem with the python module for this version (beta4)? Is this tested with the python module?

Unless I have missed something in my config, but what I really changed is only to use the WP-API (and the plug-in version).

Thanks anyway,
Babis

## STEPS TO REPRODUCE THE ISSUE

Use the python module to conenct to wooCommerce using the WP-API with same configuration as above

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Database ###

WC Database Version: 2.6.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (2) ###

WooCommerce: by WooThemes – 2.6.0-beta-4

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@claudiosmweb 

https://wordpress.org/support/topic/getting-401-error-invalid-signature-provided-signature-does-not-match-after?replies=1

**Comment by claudiosmweb** [comment]
Wrong place to report any issue about one API wrapper. This repository is for WooCommerce issues only. Next time feel free to report it in https://github.com/woothemes/wc-api-python or in wp.org, but do not make duplicate reports like you did.
