### ISSUE TITLE
Problems page and product image.

### ISSUE THREAD

**Issue by brunohfreitas** [woothemes/woocommerce#11048]
Good afternoon,
I am new to the wp universe and ending in computer technician course.
When checking the status of the system I noticed a red message on one of the pages following image. Also I wanted to know if possible if this message is not related to the fact that no picture appears the entered products. The following image as well.

If you can help me thank you very much.

Regards,

Bruno.
![captura de tela 2016-06-05 13 39 32](https://cloud.githubusercontent.com/assets/19762971/15806929/b47ca1fe-2b25-11e6-94dd-a4afd6d93b19.png)
![captura de tela 2016-06-05 13 46 14](https://cloud.githubusercontent.com/assets/19762971/15806928/b464c912-2b25-11e6-9f8a-c49b90b203f5.png)

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by WPprodigy** [comment]
Hi brunohfreitas ,

I'm sorry but this is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. See: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page for help.
