### ISSUE TITLE
Product CSV Import Suite not merging cost of goods

### ISSUE THREAD

**Issue by LevlUp** [woothemes/woocommerce#11044]
## EXPLANATION OF THE ISSUE

I'm trying to do a product merge to import cost of goods and it says it's successful, but there are no cogs being merged.

## STEPS TO REPRODUCE THE ISSUE

1. Select CSV Import Suite from the woocommerce menu
2. Select Merge Products below Import Product CSV
3. Choose the csv with the cogs 
4. Select upload file and import
5. Map the sku to the product sku and the cost of good to cost of good
6. Select Submit
7. The results of the import: http://screencast.com/t/nDPaa4X4
8. The products with no cogs: http://screencast.com/t/nDPaa4X4

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.livnfresh.com
Site URL: https://www.livnfresh.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: 5.6.99-hhvm
PHP Post Max Size: 
PHP Time Limit: 0
PHP Max Input Vars: 
SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (34) ###

Gravity Forms: by rocketgenius – 1.9.19
Divi Builder: by Elegant Themes – 1.3.4
Easy Pie Maintenance Mode: by Bob Riley – 0.6.7
Elegant Themes Updater: by Elegant Themes – 1.1
Enable Media Replace: by Måns Jonasson – 3.0.4
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.1
Image Sitemap: by Prayoga Teguh – 1.3
Insert Headers and Footers: by WPBeginner – 1.3.3
Collapse-O-Matic: by twinpictures
baden03 – 1.7.1

Livnfresh Custom: by Erik Bahle – 1.0
OneFeed SuperCharger: by S&R Group LLC – 2.0.4
WooCommerce Order Export and More: by JEM Plugins – 1.2.4
Search & Filter: by Designs & Code – 1.2.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.9.22

WooCommerce Conversion Tracking: by Tareq Hasan – 1.2
WooCommerce Cost of Goods: by WooThemes / SkyVerge – 2.1.1 – 2.2.0 is available
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Intuit QBMS Gateway: by WooThemes / SkyVerge – 1.8.0 – 1.10.0 is available
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooThemes – 4.4.2
WooCommerce Stripe Gateway: by WooThemes – 2.6.12
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10
WooCommerce Sequential Order Numbers: by SkyVerge – 1.6.1
WooCommerce Stamps.com API integration: by WooThemes – 1.2.3 – 1.2.5 is available
WooCommerce - ShipStation Integration: by WooThemes – 4.1.4 – 4.1.5 is available
WooCommerce Social Media Share Buttons: by Toastie Studio – 1.3.0
WooCommerce: by WooThemes – 2.5.5
WooMobile: by Bowdie Mercieca – 1.2.4
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.6.2
Wordfence Security: by Wordfence – 6.1.8
Yoast SEO: by Team Yoast – 3.2.5
YITH WooCommerce Stripe: by YIThemes – 1.2.7.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #179 - /shop/
Cart: #180 - /cart/
Checkout: #181 - /checkout/
My Account: #182 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Livnfresh.com Custom
Version: 1.0
Author URL: http://www.livnfresh.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.5.8
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/single-product/add-to-cart/variable.php
Divi-child/woocommerce/single-product/up-sells.php

`

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com **for premium plugin support**
