### ISSUE TITLE
Custom My Account Endpoint error

### ISSUE THREAD

**Issue by dare-devil-arrives** [woothemes/woocommerce#11054]
I'm adding a new custom endpoint inside my plugin after orders page. Using WC 2.6 beta 4.

As explained here : https://woocommerce.wordpress.com/2016/04/21/tabbed-my-account-pages-in-2-6/ about how to add an endpoint inside an class. Is it necessary to write endpoint code in another class?
Because I have written the same code inside my main php file and upon visiting that page, I'm getting 'Oops! That page can’t be found' error.

Any help?

**Comment by mikejolley** [comment]
You may need to re-save permalinks after adding a new endpoint so WordPress knows about it.

**Comment by dare-devil-arrives** [comment]
Ya that worked. Thanks Mike!
Is it possible to forcefully trigger save permalinks settings upon plugin update/install?

**Comment by mikejolley** [comment]
Yes, WC does this itself.

**Comment by dare-devil-arrives** [comment]
It is not, in this case.
Situation, plugin is checking WC version and if it is 2.6 (or greater), then only it is registering endpoint (not on activation, but at later stage).
Upon visiting endpoint, 'Page not found' error is thrown which is solved if save permalinks is hit. But how to handle it via plugin?
