### ISSUE TITLE
How to Insert Hyperlink to buy product in RSS Feed

### ISSUE THREAD

**Issue by dealsediscount** [woothemes/woocommerce#11059]
In continuation to the post - https://github.com/woothemes/woocommerce/issues/118

I want to know how can i add the "Buy Now" button or hyperlink of the item in the RSS feed.

Thank you

**Comment by mikejolley** [comment]
Github is our bug tracker, not a place to get product support.

If you need help with core, use our [support forum](https://wordpress.org/support/plugin/woocommerce) or if you need help with a WooThemes premium plugin, use our [helpdesk](https://support.woothemes.com).
