### ISSUE TITLE
Possible race condition with zxcvbn loader

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#11057]
I initially reported this as a WordPress bug, because the logic behind the loader for the zxcvbn library seems flawed to me. But, [that issue](https://core.trac.wordpress.org/ticket/36584) was closed as a duplicate, and their solution to the problem does not seem like it will help in this particular case.

## EXPLANATION OF THE ISSUE

On the edit password account page, the zxcvbn library may fail to load in time leading to javascript errors. 

## STEPS TO REPRODUCE THE ISSUE

1. Login to a user account and navigate to the edit password page
2. Using Chrome's dev tools, set the Network Throttling to "Regular 3G, 750kb/s"
3. Do a hard refresh (on Windows, Ctrl+F5)
4. Type in the new password field
5. In the js console you should see "Uncaught ReferenceError: zxcvbn is not defined"

**Comment by mikejolley** [comment]
Can you confirm this after their fix since you recreated it? We don't use zxcvbn directly. We use wp.passwordStrength, which does exist.

**Comment by dominic-p** [comment]
@mikejolley, oh, I didn't realize that you used wp.passwordStrength. My mistake. In that case, their fix should resolve the issue. I am not able to confirm that right now however.
