### ISSUE TITLE
Improvement of the System Status Report

### ISSUE THREAD

**Issue by moonspa** [woothemes/woocommerce#11051]
Hello.

I have recently developed for one of my clients WooCommerce (WC) plugin that incorporated to the WC core new custom product type. This project required to override some of the WC template files, but client instructions forced me to place modified template files not to the the wordpress template (as WC Codex is recommending), but ratter to my plugin folder, so it could be used with various of installations and templates independently. 

In order to achieve given customer requirement I have hooked the 'woocommerce_locate_template' filter thanks to the [following](https://www.skyverge.com/blog/override-woocommerce-template-file-within-a-plugin/) blog. Everything has worked perfectly except the WC System Status Report was unable to recognize overrides implemented in my plugin folder. 

Unfortunately, report it-self isn't as flexible as rest of the WC and so I was forced to modified it (it's [attached](https://github.com/woothemes/woocommerce/files/299524/html-admin-page-status-report.zip) with this issue). My version of the report is declaring new filter callback called 'woocommerce_add_override_template_destination', which can be hooked as showing following example:

```
DEFINE( 'PLG_DIR_BASE', plugin_dir_path(__FILE__));

function wcpdw_add_override_template_destination( $destinations) {
	// Add plugin destination
	array_push( $destinations, PLG_DIR_BASE . 'woocommerce/');

	// Get Output.
	return $destinations;
}

add_filter( 'woocommerce_add_override_template_destination', 'example_add_override_template_destination');
```

Combination of the blog, modified report and new filter worked for me perfectly, yet with all future WC releases report will be replaced with original version. So, what do you thinks guys, could this modification be incorporated to the official WC source code?

Maybe, there's another way how to do it. In any case, thanks in advance for your opinions and insights.

Regards,
Tomas aka mOOnSPa.

[html-admin-page-status-report.zip](https://github.com/woothemes/woocommerce/files/299524/html-admin-page-status-report.zip)

**Comment by mikejolley** [comment]
There is already a hook for this report; woocommerce_template_overrides_scan_paths

**Comment by moonspa** [comment]
:( ... OMG, what a shame ... I have carefully looked at every single line of that file except one with filter your have placed above. Anyway, thanks for such fast response. T.
