### ISSUE TITLE
Adding duplicate order functionality in core

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#11067]
At our shop we have many recurring orders that are added manually by shopmanagers. I wrote a class-wc-admin-duplicate-order.php which fulfills this as part of our child theme. ATM I just added it as a gist at https://gist.github.com/gerdneuman/9406ff1964ccbfe8fef83e7dd020f724  

I would very much like to put some more efforts into this to eventually make a PR that gets included into core (maybe for 2.7).

There's still work to be done for a reviewable PR (many TODOs in the file, refactorings in other files - see the TODOs in it, adding tests). So I thought I better ask before continuing to work on this if you welcome the idea of adding this functionality into core? Otherwise I would just leave it as it is and use it only in our child theme. 

A PR would then fix this issue and the proposed idea at http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/4209207-idea-an-admin-function-to-duplicate-orders

In case you would like to have this in Core, then I'd have a few questions: 

1. Currently, the class is very much based on [class-wc-admin-duplicate-product.php](https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php) and this [SO answer](http://stackoverflow.com/questions/19805789/duplicate-copy-order-woocommerce). Do you in generell agree on how it is done? I am wondering as there seem to be no higher class functions like `getBilling`/`setBilling` or `getShipping`/`setShipping` but it is all done with individual, low level `update_post_meta` calls. 
2. Maybe also some other feedback on the code? See also the TODOs in the gist file

**Comment by aneeshjajodia** [comment]
+1

**Comment by gerdneuman** [comment]
Since the `2.7` label was added I assume the question whether this could be included in Core is Yes ;) 

However, I do not know what you think about the other questions raised. 

For instance, AFAICS, for this to land it would be better if [create_order](https://github.com/woothemes/woocommerce/blob/c8efb71dc53a5ae3ce4da4a644552adea247d649/includes/class-wc-checkout.php#L171-L347) was refactored (this function is almost 200 lines anyways) and split into smaller reusable units like `getBilling`/`setBilling` or `getShipping`/`setShipping`. And then these be used instead of adding yet another longish `duplicate_order` function. 

So, I do not know how to proceed here. Doesn't look like a beginner's job. So either some mentoring would be needed or I also wouldn't be unhappy if a core dev took over ;)

**Comment by mikejolley** [comment]
@gerdneuman Actually after thinking about this more I'm going to suggest we close the issue and put the idea on ice until a future release.

Why? Not because I'm lazy, but because we're making some substantial changes to:

- Order data https://github.com/woothemes/woocommerce/issues/10071
- UIs
- APIs and CRUD classes

When these items are tackled in core, the implementation of this feature should be really, really simply and then I'll happily include it in core. Until then, I don't think it's worth duplicating a whole bunch of legacy code and then being forced to support it when we plan on replacing most of it anyway :)

**Comment by erikdemarco** [comment]
Any update about this?

**Comment by ptravassos** [comment]
Any update about this duplicate order functionality?

**Comment by alpha-pix** [comment]
I think we can safely say this will NOT be included in core, since there is now a paid ($49/y!) official plugin to do it:
https://woocommerce.com/products/clone-orders/

**Comment by pacmanito** [comment]
This is silly. Such a simple functionality should be in core. Automattic is digging it's own grave through nickel-and-diming WC users. Yes they get some money through selling such plugins for every small feature but the platform as a whole becomes fragmented, cumbersome and increasingly lagging behind the market.
