### ISSUE TITLE
The Header Mini Cart does not update after a product is removed

### ISSUE THREAD

**Issue by nbstreet** [woothemes/woocommerce#11064]
## EXPLANATION OF THE ISSUE

After removing a product on the Shopping cart page "/cart/", the removal/changes are not reflected on the top mini cart (usually in the header of the page).   To be precise, the Quantity and Total do not reflect the removal in the mini cart(in the header).  

## STEPS TO REPRODUCE THE ISSUE

1. Add 3 or 4 items to the shopping cart
2. Goto /cart/ (View Cart)
3. Remove a product from the shopping cart.  Click "Remove this Item" circle icon on the left 
4. The item is removed, but look at the top(header) Mini Cart, and Total/Quantity is the same. 
5. Hit "refresh", and they are updated.   

This is happening in the latest release of WC 2.6.      

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://24hourbattery.com
Site URL: http://24hourbattery.com
WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.6-1~dotdeb+8.1
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
CURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (19) ###

Ajaxy Live Search: by Ajaxy Team – 3.0.7
Ajaxy Search Keyword Analyzer & Tracker: by Ajaxy Team – 1.0.0
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.2

CSV Importer: by Denis Kobozev – 0.3.8
Ninja Forms: by The WP Ninjas – 2.9.47
No CAPTCHA reCAPTCHA for WooCommerce: by Agbonghama Collins – 1.2
Redirection: by John Godley – 2.4.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.12

Upload Endicia Tracking: by ACW – 1.0 beta
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.0.11
WooCommerce Beta Tester: by Mike Jolley – 1.0.1
WooCommerce Export Customer Email: by MH Mithu – 1.3
WooCommerce Stripe Gateway: by Mike Jolley – 2.2.0 – 2.6.12 is available
WooCommerce Min/Max Quantities: by WooThemes – 2.2.8 – 2.3.13 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.32
WooCommerce: by WooThemes – 2.6.0-beta-4
Yoast SEO: by Team Yoast – 3.2.5
WP Dev Info: by Michael Ott (@mikeyott) – 1.02
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.9.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

**Comment by huykon** [comment]
I have the same problem. Did you have any way to fix it ?

**Comment by webmatter** [comment]
Me too (mini cart in sidebar widget)

**Comment by mensmaximus** [comment]
This is usually a theme issue.

**Comment by webmatter** [comment]
Thanks for the hint. In my case it was not the theme but a plugin (fly to cart) that seemed to cause the issue. After adding the code snippet of mikejolley to the javascript of the plugin the error seems to be gone (it incurred irregularly anyway). So keep fingers crossed ... thanks.

**Comment by anjan-rsi** [comment]
I am facing the same issue, but with the ShopStar Theme. Can you please share the code snippet of mikejolley. I looked for that snippet, but could not find it...

**Comment by aslamdoctor** [comment]
Here is my fix. Update your minicart template code with this

`<div class="widget_shopping_cart_content"><?php woocommerce_mini_cart();?></div>`

As for some reasons, it uses "widget_shopping_cart_content" as a fregment when you remove last product and mini cart is empty.

**Comment by jaessi** [comment]
@anjan-rsi The snippet from mikejolley is linked above (where he closed the issue). Here's the link for convenience: https://github.com/woocommerce/woocommerce/commit/99f6540fe9b55cfda33d8991f9b14f5127c7b304

**Comment by davood89** [comment]
@aslamdoctor Your Fix worked for me too. Thank you.

**Comment by aslamdoctor** [comment]
Great. Happy to know that it was useful 👍

**Comment by Firestone91** [comment]
@aslamdoctor  This snippet WORKS! Thanks for share this. 
`<div class="widget_shopping_cart_content"><?php woocommerce_mini_cart();?></div>`

**Comment by cfxd** [comment]
Confirmed, the markup in @aslamdoctor's post is still required and fixed the issue for me!

**Comment by hayderprada** [comment]
@aslamdoctor Great Job! Thanks, it´s worked for me

**Comment by alfatahnesab** [comment]
Hi All, 
I have the same problem.
I am using oceanwp child theme, and create "mini-cart.php" override file. But I don't know how to use below code.  
```<div class="widget_shopping_cart_content"><?php woocommerce_mini_cart();?></div>```

**Comment by erickocrs** [comment]
> Here is my fix. Update your minicart template code with this
> 
> `<div class="widget_shopping_cart_content"><?php woocommerce_mini_cart();?></div>`
> 
> As for some reasons, it uses "widget_shopping_cart_content" as a fregment when you remove last product and mini cart is empty.

OMG Thats the guy!

**Comment by vandigroup** [comment]
> @aslamdoctor This snippet WORKS! Thanks for share this.
> `<div class="widget_shopping_cart_content"><?php woocommerce_mini_cart();?></div>`

This still works in 2021!

**Comment by CUBICinfinity** [comment]
Note about this. It replaces the element with the class `widget_shopping_cart_content`, so instead of
`<div class="mysuperawesomeminicartclass widget_shopping_cart_content"><?php woocommerce_mini_cart(); ?></div>`
it needs to be
```
<div class="mysuperawesomeminicartclass">
    <div class="widget_shopping_cart_content"><?php woocommerce_mini_cart(); ?></div>
</div>
```

**Comment by pabloes90** [comment]
I am using (Twenty Twenty-One) Theme and this solution does not works.

When I go to the /cart/ page and remove item from there, the mini cart still shows item.

But this problems is the same vice versa.

If I go to mini cart and delete item from there, the cart page still shows item and it only gets deleted from mini cart.

Twenty Twenty-One Version: 1.9 
WooCommerce Version 8.0.3
WordPress version: 6.3.1

I have no other plugins, just WooCommerce

Everything is up to date

I pasted this code inside header.php

```
<div class="mysuperawesomeminicartclass">
    <div class="widget_shopping_cart_content"><?php woocommerce_mini_cart(); ?></div>
</div>
```
