### ISSUE TITLE
Why the general product data translation is invalid?

### ISSUE THREAD

**Issue by tinyhill** [woothemes/woocommerce#11061]
I use /wp-contents/languages/plugins/woocommerce-zh_CN.mo in my site. But I got the dashboard display as follow, some words translated to chinese, when some are still english:

![](http://img.alicdn.com/tfs/TB14OtBKpXXXXaVXVXXXXXXXXXX-731-165.jpg)

It has been translated in /wp-contents/languages/plugins/woocommerce-zh_CN.po, but invalid. How can I fix this problem?

**Comment by mikejolley** [comment]
Missing strings - contribute to https://translate.wordpress.org/projects/wp-plugins/woocommerce :)
