### ISSUE TITLE
Ajax shipping for Woocommerce is not functioning as it should. 

### ISSUE THREAD

**Issue by Loftydsm** [woothemes/woocommerce#11063]
## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

This was working fine until the latest version of woocommerce / wordpress. 
Theme doesnt matter. Plugins disabled, enabled, doesnt matter. 
What is basically happening is when you select an option it is checking for changes in the location here. 
 wc-ajax=update_shipping_method 

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

Basically, you go into the cart. Fill out information and then when you get to the shipping calculator, you input any adress, it calculates shipping for you. Then you select a shipping option. A grey screen will go over the shipping options with a loading animation (new WP update) and then once this is over with, the selected shipping option reverts to the first or (default) option. 
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
`
### WordPress Environment ###

Home URL: https://www.tmzperformance.com
Site URL: https://www.tmzperformance.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 5.5.36
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.5
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (13) ###

WooCommerce Car Filter: by Bigboss555 – 1.2
BackWPup: by Inpsyde GmbH – 3.3.1
Better WordPress Minify: by Khang Minh – 1.3.3
Contact Form 7: by Takayuki Miyoshi – 4.4.2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.1
Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 4.11.2
Nginx Helper: by rtCamp – 1.9.7
W3 Total Cache: by Frederick Townes – 0.9.4.1
Woocommerce EasyPost Shipping Tool: by wanderlust-webdesign.com – 4.0
WooCommerce Stripe Gateway: by WooThemes – 2.6.12
WooCommerce: by WooThemes – 2.5.5
WooThemes Helper: by WooThemes – 1.6.2
WP Smush: by WPMU DEV – 2.3.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –
API Version: 3.1.0

### WC Pages ###

Shop Base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: SalientChild
Version: 1.0.1
Author URL: http://your%20web%20address%20goes%20here
Child Theme: ✔
Parent Theme Name: Salient
Parent Theme Version: 7.0.8
Parent Theme Author URL: http://themenectar.com
WooCommerce Support: ✔

### Templates ###

Overrides: salient/woocommerce/cart/cart-shipping.php
salient/woocommerce/cart/cart-totals.php
salientchild/woocommerce/cart/cart.php
salientchild/woocommerce/cart/shipping-calculator.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/form-shipping.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/content-product.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/single-product/product-image.php
salient/woocommerce/single-product/tabs/description.php
salient/woocommerce/single-product/tabs/tabs.php


```

**Comment by mikejolley** [comment]
"Theme doesn't matter" - I see you have template overrides. Do the test with twenty twelve. This issue always ends up being theme/plugin related.

**Comment by silentkillzr** [comment]
I'm helping lofty with this where i can; we've tried other themes such as twenty twelve and the same issue occurs.

**Comment by silentkillzr** [comment]
Also tried removing all the overrides with the same result.

**Comment by Loftydsm** [comment]
All plugins disabled but woocommerce and easypost shipping tool and twenty twelve enabled with no luck. Still bugged.

**Comment by roykho** [comment]
Perhaps the issue is with Easy Post? Have you tried a different shipping plugin?

**Comment by mikejolley** [comment]
It's definitely something custom to your site. Look at the field names:

https://dl.dropboxusercontent.com/s/befft9dn72qwevz/2016-06-08%20at%2011.40.png?dl=0

Easypost?

This value/name is changing after page load. So it's that and possibly a conflict with the caching plugin too which shouldn't be active on the cart/checkout pages.

Core shipping methods do not have dynamic names and thus won't break in this manner. This is not a wc bug.

**Comment by Loftydsm** [comment]
@mikejolley  just wanted to say thanks, your response helped us track down the issue...

**Comment by jramsey32** [comment]
Hey @Loftydsm I am getting this issue now for one of my clients and wanted to see how you resolved this?

**Comment by ConradGalli** [comment]
@jramsey32 I'm easypost plugin developer, if you still have this issue, please contact me so I can help.
