### ISSUE TITLE
Order with the API doesn't change stock quantity of variable product.

### ISSUE THREAD

**Issue by luandro** [woothemes/woocommerce#11076]
Probably related to #5117.

When using the WooCommerce API to create an order, the stock quantity of an item isn't reduced. Should I be manually doing that every time an order is created or completed?

**Comment by claudiosmweb** [comment]
You need to set it as "paid".
Here you can find an example of how to do it: http://woothemes.github.io/woocommerce-rest-api-docs/v3.html#create-an-order

**Comment by vineet-agrawal96** [comment]
Hi,
I'm facing same problem and i'm already set paid as true. I'm using woocommerce v3 version.
Please help me to resolve this issue.

**Comment by claudiosanches** [comment]
@vineet-agrawal96 you are using a deprecated version of the REST API, you should update to your new REST API integration with WordPress REST API.

**Comment by vineet-agrawal96** [comment]
Thanks for the reply. let me try.

**Comment by gauravmillipixels** [comment]
@claudiosan  @vineet-agrawal96  i am facing the same issue while setting flag doesn't reducing the quantity.
