### ISSUE TITLE
False variation post data in REST-API and somewhere else ?

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11079]
The REST-API gives back the Variation data of the parent post and not the Variation.
You can see it here: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L507-L508 this gives back the dates of the parrent post and not of the variation post. 
It depends on: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variation.php#L90 there the parent post data will be stored and not the Variation post data.

I don't know what will be affected else if the line will be changed to the variation post data and how WooCommerce exactly need this.

The Object from the WC_Product_Variation has in moment no WP_Post object from the variation.

**Comment by claudiosmweb** [comment]
I just fixed it in the API: https://github.com/woothemes/woocommerce/commit/745f161456dcdfe50ed3cb2af1fa71f8ac528f34

But it's intensionally that, variations should return the parent data.
It's really a bug on the REST API, but fixed now, thanks for report it.
