### ISSUE TITLE
Is API docs outdated?

### ISSUE THREAD

**Issue by luandro** [woothemes/woocommerce#11073]
I've been using the WooCommerce API for a few weeks now, but some of the endpoints simply don't work as expected. I'm using the docs found here: [http://woothemes.github.io/woocommerce-rest-api-docs](http://woothemes.github.io/woocommerce-rest-api-docs).

For example this is the example in the documentation for creating an order:

```
var data = {
  payment_method: 'bacs',
  payment_method_title: 'Direct Bank Transfer',
  set_paid: true,
  billing: { ... },
  shipping: { ... },
  line_items: [
    {
      product_id: 93,
      quantity: 2
    },
    {
      product_id: 22,
      variation_id: 23,
      quantity: 1
    }
  ],
};

WooCommerce.post('orders', data, function(err, data, res) {
  console.log(res);
});
```

I found out that `billing` and `shipping` should in reality be `billing_address` and `shipping_address`. And the meta tags for variable products are empty (which is my real main issue).

The example for creating order notes responds with a `'woocommerce_api_invalid_order_note'`.
```
var data = {
  note: 'Order ok!!!'
};

WooCommerce.post('orders/645/notes', data, function(err, data, res) {
  console.log(res);
});
```

Am I doing something wrong, or is the documentation really outdated?

**Comment by claudiosmweb** [comment]
Have you read it http://woothemes.github.io/woocommerce-rest-api-docs/#introduction ?

The API this updated for what will be on the WooCommerce 2.6.

So...

> Is API docs outdated? 

The answer is: no!

**Comment by luandro** [comment]
Cê vai acabar me batendo ainda...

**Comment by claudiosmweb** [comment]
@luandro que nada, tudo suave, acontece xD
