### ISSUE TITLE
2.6 RC1 Pernicious Message

### ISSUE THREAD

**Issue by varktech** [woothemes/woocommerce#11074]
Updated to 2.6 RC1.  Message
"WooCommerce Data Update – Your database is being updated in the background."
has not gone away in 24 hours.

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by varktech** [comment]
`
### WordPress Environment ###

Home URL: http://test.varktech.com
Site URL: http://test.varktech.com
WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.22
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (5) ###

Shield: by iControlWP – 5.2.0
Members: by Justin Tadlock – 1.1.1
WooCommerce: by WooThemes – 2.6.0-RC1
WordPress Database Backup: by Austin Matzko – 2.3.1
WP Robots Txt: by Christopher Davis – 1.1

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Fourteen
Version: 1.6 – 1.7 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by varktech** [comment]
Debug file contents:

[08-Jun-2016 00:01:00 UTC] WordPress database error Duplicate key name 'tax_rate_country' for query ALTER TABLE wp_woocommerce_tax_rates ADD KEY tax_rate_country (tax_rate_country(191)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta
[08-Jun-2016 00:01:00 UTC] WordPress database error Duplicate key name 'tax_rate_state' for query ALTER TABLE wp_woocommerce_tax_rates ADD KEY tax_rate_state (tax_rate_state(191)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta
[08-Jun-2016 00:01:00 UTC] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_tax_rate_locations ADD KEY location_type_code (location_type(40),location_code(90)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta

**Comment by mikejolley** [comment]
Is your test site behind a password or inaccessible?

**Comment by varktech** [comment]
Hi Mike,
Yup, locked to my IP address.
Best,
Mark

**Comment by mikejolley** [comment]
```
Error 403 - Forbidden
```

Yep. The background updater works by generating remote requests. If this were open, it would complete. can you open it temporarily?

**Comment by varktech** [comment]
Will do and report back thereafter.

**Comment by varktech** [comment]
Done.  Message has resolved to dismissable 'all done' msg.  Issue resolved.

**Comment by varktech** [comment]
Thanks!

**Comment by mikejolley** [comment]
Is cron enabled on your site? Maybe the fallback isn't working.

**Comment by varktech** [comment]
Cron has not been disabled, so should be working I believe

**Comment by varktech** [comment]
PS
Mike, please ask your colleague to replace the reference to my Pricing Deals plugin in this article:
https://support.woothemes.com/hc/en-us/articles/205006795-Plugin-Causing-Fatal-Error.
Thanks

**Comment by varktech** [comment]
That is, refer to some generic name, rather than my plugin, please.

**Comment by BurlesonBrad** [comment]
@varktech you **_do_** know that you're allowed to ask @msdesign21 **_your_**self,
..............right? :+1: 

Pretty sure she ain't gonna reach through the keyboard and bite 'ya :fearful:

**Comment by msdesign21** [comment]
Thanks for the tag @BurlesonBrad - @varktech we will get this updated for you. 

cc @californiakat
