### ISSUE TITLE
Cannot connect to my WooCommerce REST API using Ruby and Python wrappers

### ISSUE THREAD

**Issue by museyoucoulduse** [woothemes/woocommerce#11071]
I've been hacking something in `Wordpress`, when I felt strange need to use API's and found one at `WooCommerce` plugin. Unfortunately I can't get it going the right way, as it's giving me the same result, whatever it's `Python` wrapper or `Ruby` wrapper -

```ruby
wapi = WooCommerce::API.new(
  "http://myapp.rhcloud.com",
  "ck_xxxxxxxxx",
  "cs_xxxxxxxxx",
  {
    wp_api: true,
    version: "wc/v1"
  }
)
=> #<WooCommerce::API:0x007fb2bb0a6840 @url="http://myapp.rhcloud.com", @consumer_key="ck_xxxxxxxxx",     @consumer_secret="cs_xxxxxxxxx", @wp_api=true, @version="wc/v1",     @verify_ssl=true, @signature_method="HMAC-SHA256", @is_ssl=false>

print wapi.get("products")
{"code"=>"rest_no_route", "message"=>"No route was found matching the     URL and request method", "data"=>{"status"=>404}}=> nil
```

Please help me get this going on... Wordpress is fresh provisioned from OpenShift cartridges and I can do everything manually, but you know where the fun is?

**Comment by mikejolley** [comment]
Are you using woocommerce 2.5 or 2.6?

**Comment by museyoucoulduse** [comment]
I am using version 2.5.5 is there a difference in REST API? Should I use a previous version of wrappers?

**Comment by mikejolley** [comment]
Wp-API support is for 2.6 only. See our docs.

**Comment by museyoucoulduse** [comment]
Believe me or not, but I intend to use WC REST API, is there a connection between this two?

**Comment by claudiosmweb** [comment]
@museyoucoulduse if you are using 2.5.5, why are you setting the wrapper to use the REST API included ONLY in 2.6?

> With wp_api: false I get code 400 and no output...

Because if you use `wp_api` you should use `version: "v3"` or `v2` or `v1`.

See: http://woothemes.github.io/woocommerce-rest-api-docs/v3.html?ruby#official-libraries

**Comment by museyoucoulduse** [comment]
I'm very thankful for your help... I have no idea how I could'n make it work for me, but now it's doing it's thing. I guess that if I would upgrade to version 2.6 I would have it working with the previous code. After all thank you for the time you spend on answering my question.

**Comment by claudiosmweb** [comment]
@museyoucoulduse we'll release 2.6 in June 14. It's only a few more days, but you can test 2.6 RC 1 now: https://woocommerce.wordpress.com/2016/06/07/woocommerce-2-6-release-candidate/
