### ISSUE TITLE
404 on Subscriptions tab in My Account

### ISSUE THREAD

**Issue by ClearMarble** [woothemes/woocommerce#11072]
I’m testing out the release candidate on an existing store (in local dev environment) and while most everything seems to be working great, I get a 404 when trying to view the “Subscriptions” tab on the new tabbed My Account page (mydomain/my-account/subscriptions/)

Am I the only one experiencing this or is this functionality broken at the moment?

Subscriptions plugin and Storefront theme are both updated to the latest version…just checked.

`
### WordPress Environment ###

Home URL: http://localhost/mothere-upgradetest
Site URL: http://localhost/mothere-upgradetest
WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11
PHP Version: ❌ 5.5.11 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 750 MB
PHP Time Limit: 5000
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.16
Max Upload Size: 750 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (16) ###

Advanced Custom Fields: by Elliot Condon – 4.4.7
Duplicator: by LifeInTheGrid – 1.1.8
Anti-Malware Security and Brute-Force Firewall: by Eli Scheetz – 4.16.17
Homepage Control: by WooThemes – 2.0.1
Instagram Feed Pro Personal: by Smash Balloon – 2.2
SimpleModal Login: by Noah Cinquini – 1.1
Storefront Hamburger Menu: by WooThemes – 1.1.3
WooCommerce Accordions: by Magnigenie – 1.0
Woocommerce Add to cart Ajax for variable products: by Rishi Mehta - Rcreators Websolutions – 1.2.8
WooCommerce Beta Tester: by Mike Jolley – 1.0.1
WooCommerce Authorize.net CIM Gateway: by WooThemes / SkyVerge – 2.3.0
WooCommerce Product Bundles: by WooThemes – 4.14.4
WooCommerce Subscribe All the Things: by Prospress – 1.0.3
WooCommerce Subscriptions: by Prospress Inc. – 2.0.15
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.5.0 – 1.6.0 is available
WooCommerce: by WooThemes – 2.6.0-RC1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #12 - /products/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My Account: #15 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Mother E
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.0.3
Parent Theme Author URL: https://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: mothere/woocommerce/cart\cart-shipping.php
mothere/woocommerce/checkout\review-order.php
mothere/woocommerce/global\quantity-input.php
mothere/woocommerce/single-product\tabs\tabs.php

### Authorize.net CIM ###

Environment: Test
Tokenization Enabled: 
`

**Comment by claudiosmweb** [comment]
We don't have any "subscriptions" tab in WooCommerce. Seems like you are reporting it to the wrong plugin.

>  WooCommerce Subscriptions: by Prospress Inc. – 2.0.15

You should open a ticket in the https://support.woothemes.com

**Comment by dauidus** [comment]
@ClearMarble What ever came of this issue?  We're experiencing the same 404 error on the Subscriptions tab, after updating the subscriptions plugin.

**Comment by folkhack** [comment]
Seeing this same issue. Help us @ClearMarble you're our only hope...

**Comment by dauidus** [comment]
Looks like this problem persists after an update to PHP v7.  Not sure if that helps - just trying on my 'debug' hat here.  :-)

**Comment by folkhack** [comment]
It's too late at night to test the theory but I just updated my dev environment to PHP7 since I'm primarily a Laravel dev - I bet this is it.

**Comment by dauidus** [comment]
To be clear, we're having this problem on an Apache server running PHP 5.6.2 - and on our dev NGINX environment running PHP 7.

Something in that update took the subscriptions details away from the user's dashboard and tried to put in into its own tab.  But, its broken... seemingly on all our environments.

I'll take a dive into some code this evening and tomorrow.  Our goal is to revert this functionality back to its previous working state, while retaining some of the other updates/bug fixes from the latest version of the plugin.

**Comment by claudiosmweb** [comment]
Here is not a support forum for WooCommerce Subscriptions.
You should open a ticket in the https://support.woothemes.com
