### ISSUE TITLE
Issue when including files

### ISSUE THREAD

**Issue by DuckDagobert** [woothemes/woocommerce#11087]
See: https://core.trac.wordpress.org/ticket/37060#ticket
One of the plugins causing this is woocommerce itself e.g. in wc-widget-functions.php (& probably other files; I didnt debug this to the end).

**Comment by mikejolley** [comment]
This code has been present for several releases now so not an immediate concern. Punting to 2.7.

**Comment by DuckDagobert** [comment]
Yes, it's not urgent, just pointing it out.
For woothemes plugins with the same issue do I have to point it out
separetely (& create a ticket via woothemes?) or will they be checked too?
Mike Jolley <notifications@github.com> schrieb am Fr., 10. Juni 2016 um
21:47:

**Comment by mikejolley** [comment]
I'll notify @gedex to review.
