### ISSUE TITLE
My Subscriptions display error

### ISSUE THREAD

**Issue by blogjunkie** [woothemes/woocommerce#11088]
Getting this error on the My Subscriptions page with WC 2.6.0-RC1 and WC Subscriptions 2.0.15. Same issue on Twenty Sixteen and Storefront.

<img width="640" alt="my_account_ _woocommerce_playground" src="https://cloud.githubusercontent.com/assets/1391919/15965706/20b90238-2f52-11e6-9bbe-24df1580649d.png">

Apologies if this isn't the correct avenue for this report. If so, please direct me to the correct channel. Thank you

**Comment by mikejolley** [comment]
Already aware and is being fixed in subs.
