### ISSUE TITLE
$post_status param not being usefull in duplicate_product

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#11097]
What's the point of the [$post_status](https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L118) param in `duplicate_product` of `woocommerce/includes/admin/class-wc-admin-duplicate-product.php`? AFAICS the `$post_status` gets overriden anyway in [lines 125 to 133](https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L125-L133).

If this param is not used anyway, then I'd propose to remove it from the function's signature in order to improve code quality. The way now it looks obfuscating.

**Comment by mikejolley** [comment]
The point is to set the status of the new product during duplication. 

It's not overridden; it's only set to publish/draft if not empty. Re-read the lines you posted - I think you've made a mistake in understanding :)

https://www.abeautifulsite.net/how-to-use-the-php-ternary-operator/

**Comment by jnachtigall** [comment]
@mikejolley Woo, that's embarrassing ;) I must have stopped reading after the `=` sign. Thanks for pointing this out.
