### ISSUE TITLE
Grouped products do not display private products

### ISSUE THREAD

**Issue by douglsmith** [woothemes/woocommerce#11094]
A grouped product that contains private products will not show those private products on the front end, even to admins. I would expect the product to display normally for those with sufficient privileges because private products are often used to set up products before public release.

Tested on multiple installs of WordPress and WooCommerce. Testing included a fresh install of the latest WordPress 4.5.2 and WooCommerce 2.5.5, no other plugins active, and using the Twenty Fifteen theme.

## STEPS TO REPRODUCE THE ISSUE

1. Log into WordPress as an admin.
2. Create and publish a grouped product. Default settings are fine.
3. Create a simple product. Set the grouping on this product so it is associated with the grouped product previously created. Publish the product.
4. Create another simple product. Set the grouping on this product so it is associated with the grouped product previously created. Set the visibility of this product to _private_. Publish the product.
4. View the grouped product on the font end. It will only show the product that does not have private visibility.

**Comment by mikejolley** [comment]
I think it's always been this way, so not an immediate concern. 2.7.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/11249

**Comment by douglsmith** [comment]
I applied the changes in #11249 and confirm that this did fix the issue in my testing. Thanks.
