### ISSUE TITLE
address verification fails ungracefully,  minification has error

### ISSUE THREAD

**Issue by kosmar** [woothemes/woocommerce#11091]
## EXPLANATION OF THE ISSUE

http://bassball.net

## STEPS TO REPRODUCE THE ISSUE

cannot checkout, cannot login, cannot create user

if i want to login, it starts a download …

research showd: minify is broken at least on row 343 of checkout.js

### WordPress Environment ###

Home URL: http://www.bassball.net
Site URL: http://www.bassball.net
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: de_DE

### Server Environment ###

Server Info: Apache/2.2.31 (Unix)
PHP Version: 5.5.35
PHP Post Max Size: 48 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
SUHOSIN Installed: –
MySQL Version: 5.5.48
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (8) ###

Quick Page/Post Redirect Plugin: von anadnet – 5.1.8
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
Responsive Video Light: von Bill Knechtel – 1.5.1
Under Construction: von Noah Kagan – 1.17
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.12.13

WooCommerce Print Invoice & Delivery Note: von Triggvy Gunderson – 4.1.5
WooCommerce Sequential Order Numbers: von SkyVerge – 1.7.0
WooCommerce: von WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop-Basis: #33 - /
Warenkorb: #34 - /cart/
Kasse: #35 - /checkout/
Mein Konto: Seite nicht festgelegt

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Mystile
Version: 1.3.1 – 1.3.12 ist verfügbar
Author URL: http://www.woothemes.com
Child Theme: ✕ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
I guess you ignored the big notice during issue submission that this is not a support forum.

1. There are no JS errors on your checkout.
2. There is no address verification in WC. Just checks for required fields. Which I confirmed work.

Use https://wordpress.org/support/plugin/woocommerce in future if you have issues.

**Comment by kosmar** [comment]
thx

**Comment by mikejolley** [comment]
@kosmar there is no error on console. The min files are fine. If there were an error, you'd see it on all WooCommerce sites.

demo.woothemes.com

I suggest you look at plugins on your own site for conflicts if you see an issue. I do not on your site :)
