### ISSUE TITLE
Permalink problems with subcategories

### ISSUE THREAD

**Issue by rocketeer76** [woothemes/woocommerce#11092]
## EXPLANATION OF THE ISSUE

I always run into permalink problems when trying to setup a new store. For each store I want the same structure:

http://domain.com/shop/category/subcategory/subsubcategory/product/

In issue #6158 this problem was discussed and I thought it was solved:
https://github.com/woothemes/woocommerce/issues/6158

I've also tried to use Bryce's WooCommerce Breadcrumb Permalinks plugin without any luck. Either the categories return 404 or the product return 404.

Can you please explain how to set up the permalinks in the Wordpress settings? It's not explained in the WooCommerce manual. Perhaps it should be updated.

## STEPS TO REPRODUCE THE ISSUE

1. Create categories and subcategories in WooCommerce and add them to the menu.
2. Change the permalink structure in the Wordpress settings.
3. Click through the the categories to get to the product.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://fondamenta.net
Site URL: http://fondamenta.net
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.16
PHP Post Max Size: 32 MB
PHP Time Limit: 40
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.1.73
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (2) ###

WooCommerce Breadcrumb Permalinks: by Bryce Adams – 1.1.0
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: SEK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #6 - /webbutik/
Cart: #7 - /varukorg/
Checkout: #8 - /kassan/
My Account: #9 - /mitt-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Mary Kate - Premium
Version: 2.49.1
Author URL: http://angiemakes.com/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
What manual/doc are you reading?

Category permalinks CANNOT have the same base as products. It conflicts. WP limitation.

**Comment by rocketeer76** [comment]
I was referring to the documentation: https://docs.woothemes.com/document/permalinks/

So as I understand it, WooCommerce does not support a structure like this?
http://domain.com/shop/category/subcategory/subsubcategory/product/

And #6158 did not resolve the initial problem discussed?

**Comment by mikejolley** [comment]
That was about hierarchy. You're using 'shop' base for both category and product, which is not supported. Category needs a unique base. e.g. /shop/product-category/

**Comment by rocketeer76** [comment]
OK! So the hierarchies will be like this.

For products:
http://domain.com/shop/category/subcategory/subsubcategory/product/

For categories:
http://domain.com/product-category/category/subcategory/subsubcategory/product/

That's very bad for SEO. But if it's not supported, that's how it is.

Have you considered implementing Bryce's solution?

**Comment by mikejolley** [comment]
Yep, thats the way to do it. I'll leave it open until I update the docs.

**Comment by kymcarlsson** [comment]
@rocketeer76 you may have already though of it, but if you want shop as a common base, another option is running WC isolated as its own WP install under /shop. That way you should be able to have domain.com/shop/products/product-category-slug/.../product-slug/ and domain.com/shop/product-categories/product-category-slug/.../ a bonus you should also get domain.com/shop/my-account/.../ and domain.com/shop/checkout/ which is tidier in my opinion.
