### ISSUE TITLE
Tax calculation going wrong if price inclusive tax added after order completion.

### ISSUE THREAD

**Issue by umeshnevase** [woothemes/woocommerce#11098]
I have setup woocommerce one my sites, I've not added tax before products sale. But my client asked me to add price inclusive tax for products before shipping started. I've added tax for inclusive tax. When I edit order Tax getting calculated correct (line total, line subtotal, total), but for discounted product line total, line subtotal and total showing wrong calculation. 

### WordPress Environment ###

Home URL: http://wordpress-local.com
Site URL: http://wordpress-local.com
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.8.0
PHP Version: 5.6.15-1+deb.sury.org~trusty+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 10.0.22
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
:
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (2) ###

Social Media Feather: by Synved – 1.7.9
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #32 - /shop/
Cart: #33 - /cart/
Checkout: #34 - /checkout/
My Account: #35 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

: Learn how to update outdated templates
`

## EXPLANATION OF THE ISSUE

What happens, under which versions, under what conditions, when, and what were you expecting instead.

## STEPS TO REPRODUCE THE ISSUE

1. List steps to reproduce your issue so we can replicate.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Don't double post. https://wordpress.org/support/topic/tax-calculation-going-wrong-if-price-inclusive-tax-added-after-order-completion?replies=1
