### ISSUE TITLE
Searching order through the rest api return empty array.

### ISSUE THREAD

**Issue by nursahketene** [woothemes/woocommerce#11100]
## EXPLANATION OF THE ISSUE

I am making a request to list the orders with a search param. However when I make the call I receive an empty array as a result. 

the following code is the request code

```
 const searchQuery = params.searchQuery;
    const requestURL = baserurl + '/wp-json/wc/v1/orders ;
    const requestData = {
      url: requestURL,
      method: 'GET',
      data: {
        oauth_token: token.oauth_token
      }
    };

    request({
      url: requestData.url,
      method: requestData.method,
      body: { search: searchQuery }
      json: true,
      headers: oauth.toHeader(oauth.authorize(requestData, token))
    }, function (error, response, body) {
      if (error) {
        reject(error);
      } else {
        const data = {
          offers: body
        };
        resolve(data);
      }
    });
```

### Plugins
Woocommerce 2.6 RC1
Wordpress Rest API Version 2.0-beta13

Otherwise the search is working with posts and custom post types. Just not the orders.

**Comment by claudiosmweb** [comment]
>  Wordpress Rest API Version 2.0-beta13

Do you that it's not required to use the `Wordpress Rest API` plugin?

**Comment by nursahketene** [comment]
Ok thats great. I guess we are waiting for a CI to pass the tests and merge. awesome and thanks
