### ISSUE TITLE
Drag and Drop re-ordering of Select2 inputs

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#11106]
The [issue](https://github.com/woothemes/woocommerce-mix-and-match-products/issues/124) came up with Mix and Match regarding re-ordering Select2 inputs. If a user has a lot of selections and then needs to change the order, or add something new later, she has to delete all the selections and re-add them in the desired order. 

The [select2](http://select2.github.io/select2/) docs indicate that drag and drop is supported via `jquery-ui-sortable`. And it's a pretty easy change on the MNM side, but I think it makes sense to apply to all Select2 inputs. 

cc: @om4james @franticpsyx

**Comment by mikejolley** [comment]
Why change all? It would be an un-neccessary addition to some inputs.

**Comment by helgatheviking** [comment]
Specifically in the MNM context, we're looping through the array of product IDs to display them on the front-end. So if you have selected products A, B, C, D, E and you later add F but want it to display first on the front-end you have to clear all the input and then add them again in the new order. 

I'll send a PR in a second. There isn't really any change to the inputs, just a few lines of JS.

**Comment by franticpsyx** [comment]
I think I'd rather have a class or data attribute control whether `sortable` functionality would be enabled or not. It probably does make sense for a few multi-select inputs already in core, such as Up-sells and Cross-sells (?).

Would make sure it's still supported in select2 v4, though.

**Comment by mikejolley** [comment]
Indeed.

**Comment by helgatheviking** [comment]
I like the data attribute idea. I'm a little stuck testing against 4.0.x because I'm not sure what else has changed since the docs are still for 3.5.x.

**Comment by helgatheviking** [comment]
e670dc2 adds the data attributes. Is WC planning on switching to Select2 4.0 soon? the enhanced select script produces errors with Select2 4.0 even without my additions.

**Comment by franticpsyx** [comment]
@helgatheviking ref https://github.com/woothemes/woocommerce/pull/8123

**Comment by helgatheviking** [comment]
Thanks. I'd forgotten all about that thread. 

You said:
>They have changed how ajax-powered multi-selects work, too, which used to rely on input fields with comma-separated values but now require us to go back to select fields with options.

If that's true, then the drag and drop code I've borrowed from their 3.5 docs might not work. I don't know if I feel like digging in to their script to figure it out before their docs are updated and before WC updates to Select2 4.0.x.

**Comment by mikejolley** [comment]
Closed in favour of #11107. Will need to decide when select2 is updating first.
