### ISSUE TITLE
Minor Save Issue with Shipping Classes

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#11104]
## EXPLANATION OF THE ISSUE

When making changes to a shipping class in WooCommerce 2.6 RC1 the changes do not show up after I click save. I have to refresh the page in order to see that they were indeed saved.

## STEPS TO REPRODUCE THE ISSUE

Visit the Shipping Classes page under the Shipping tab of your WooCommerce settings. Hover over an existing class and click the 'Edit' link. Change text in any of the text input boxes that appear. Click on the Save Changes button. The box will fade while saving, but when it comes back it displays the previous entry. Fortunately it does save but may be confusing to users.

**Comment by mikejolley** [comment]
@bolderelements Can you rule out conflicts please? I'm trying locally and not seeing the issue occur.

**Comment by mikejolley** [comment]
@claudiosmweb can you replicate?

**Comment by claudiosmweb** [comment]
@mikejolley works fine for me too.

**Comment by bolderelements** [comment]
Ugh, I didn't disable every plugin when I was testing my staging site. Seems one of the remaining ones was the issue. Sorry :(
