### ISSUE TITLE
Tax rate is being applied wrong

### ISSUE THREAD

**Issue by magpacker** [woothemes/woocommerce#11108]
## EXPLANATION OF THE ISSUE

I have my tax set to charge based on shipping within texas. I had 2 customers shipping, 1 in virginia, and 1 rhode Island get charged the tx sales tax..

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Setup issues are not bugs. Post on the forum with more information + screenshots https://wordpress.org/support/plugin/woocommerce

**Comment by magpacker** [comment]
It's not a set up issue if it does it randomly to orders outside of the parameters specified

Thanks,
Erin M.
Admin Office
Magpacker, LLC

**Comment by mikejolley** [comment]
Post on the forum if you want to discuss.
