### ISSUE TITLE
Thank you page not coming after Placing an order and redirects to cart page

### ISSUE THREAD

**Issue by experttalk** [woothemes/woocommerce#11110]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

Guys any idea why thank you page not working if everything exits in woo commerce like thankyou.php and all files. when i am placing an order via BACS, COD or PayU  these order have been placed and notification comes to admin but WC not redirecting to bydefault Thankyou page after placing an order?

Any idea why this is happening search lots of forums, groups and adding redirection code, hooks in function.php nothing work.

Every time after placing an order redirects to Cart page and messages comes Your cart is empty.

**Comment by mikejolley** [comment]
Can be plugin or theme caused, missing cart/checkout page assignment in settings, or just a badly coded payment gateway. 

Lack of details in report, and wrong place anyway; as said on the submission form, support should be done on the forums https://wordpress.org/support/plugin/woocommerce
