### ISSUE TITLE
Woocommerce status page incorrectly detect mariadb 10.0.25 as mysql 5.5.5

### ISSUE THREAD

**Issue by nextime** [woothemes/woocommerce#11117]
## EXPLANATION OF THE ISSUE

just checking the status page, it says: MySQL Version:		 5.5.5 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements

I'm running: 
Server version: 10.0.25-MariaDB-1 Debian unstable

**Comment by mikejolley** [comment]
This is a wontfix and should be fixed by the host to be compatible with WP.

https://github.com/woothemes/woocommerce/issues/10793

is_mysql should return false in your case, but doesn't. We cannot detect anything else using WP functions.
