### ISSUE TITLE
New Issues Checkout Payment Methods and My Account Payment Methods WOO 2.6

### ISSUE THREAD

**Issue by jeasysehgal** [woothemes/woocommerce#11125]
HI @Mikejolley & Team,

Congratulations on the latest version of WOoCommerce 2.6, Loving it however am confused about 2 things so far. I am only using PayPal Standard as checkout option but after the update, and proceeding to checkout, I am shown 3 checkout options: PayPal, Cash, Card.

Not sure where the other 2 are coming from and trying to use the Cash or Card option gives the message: Error processing checkout. Please try again. but creates an order in the backend. Don't need these two to be present. Can't find any documentation for the same. What am I missing here????

On the My Account Page, Great idea simplifying the layout. Looks great. Again there is Payment Methods section present. Clicking on the same says Add Payment Method, On Clicking that I get: Sorry, it seems that there are no payment methods which support adding a new payment method. Please contact us if you require assistance or wish to make alternate arrangements.

Again no idea where this is coming from, How to go about setting it up and making it work.

Can you please help? The site in question is http://www.ImperialSwords.com

Thanks,

Jeasy

System Report Attached:

WordPress Environment
Home URL:		http://imperialswords.com
Site URL:		http://imperialswords.com
WC Version:		2.6.0
Log Directory Writable:		 /home/imperil5/public_html/wp-content/uploads/wc-logs/
WP Version:		4.5.2
WP Multisite:		
WP Memory Limit:		256 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache
PHP Version:		 5.4.28 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size:		256 MB
PHP Time Limit:		200
PHP Max Input Vars:		5000
cURL Version:		7.24.0, OpenSSL/1.0.0
SUHOSIN Installed:		–
MySQL Version:		 5.5.50 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size:		256 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.5.5
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /home/imperil5/public_html/wp-content/uploads/GeoIP.dat
Active Plugins (38)
VaultPress	 	by Automattic – 1.8.3
AfterShip - WooCommerce Tracking	 	by AfterShip – 1.6.2
Akismet	 	by Automattic – 3.1.11
All 404 Redirect to Homepage	 	by Fakhri Alsadi – 1.4
Beeketing For WooCommerce	 	by Beeketing – 2.2.3
Bloom	 	by Elegant Themes – 1.1.5
Code Snippets	 	by Shea Bunge – 2.6.1
ContestHopper for WordPress	 	by Webikon (Matúš Čerman) – 0.9.5
Custom Login	 	by Austin Passy – 3.2.5
EWWW Image Optimizer	 	by Shane Bishop – 2.8.5
Jetpack by WordPress.com	 	by Automattic – 4.0.3
Monarch Plugin	 	by Elegant Themes – 1.3
Muut	 	by Muut, Inc. – 3.0.6
My Custom Functions	 	by Arthur Gareginyan – 2.2
Optin Forms	 	by FancyThemes – 1.2.4
Regenerate Thumbnails	 	by Alex Mills (Viper007Bond) – 2.2.6
RS FeedBurner	 	by Scott Allen – 1.5.3
RSS Image Feed	 	by Stefan Crämer – 4.2.5
SOFT79 Cart Links for WooCommerce	 	by Jos Koenis – 0.1.2
Unsplash WP	 	by Darren Cooney – 1.1.2
WooCommerce Extended Coupon Features	 	by Jos Koenis – 2.3.3
WooCommerce Cart Notices	 	by WooThemes / SkyVerge – 1.6.0
WooCommerce Cost of Goods	 	by WooThemes / SkyVerge – 2.2.0
WooCommerce Currency Converter	 	by WooThemes – 1.6.2
WooCommerce POS	 	by kilbot – 0.4.5
WooCommerce Smart Coupons	 	by WooThemes – 3.0.17
WooCommerce Smart Sale Badge	 	by Hugh Lashbrooke – 1.1
WooCommerce Sold Out Products	 	by Gerhard Potgieter – 1.0.4
WooCommerce Subscribe to Newsletter	 	by WooThemes – 2.3.3
WooCommerce Waitlist	 	by Neil Pie – 1.4.13
WooCommerce	 	by WooThemes – 2.6.0
Yoast SEO Premium	 	by Team Yoast – 3.2.5
WP Better Emails	 	by Nicolas Lemoine – 0.3
Yoast WooCommerce SEO	 	by Team Yoast – 3.2.1
YITH WooCommerce Advanced Reviews Premium	 	by YITHEMES – 1.3.8
YITH WooCommerce Ajax Search Premium	 	by YITHEMES – 1.4.0
YITH WooCommerce Recover Abandoned Cart Premium	 	by yithemes – 1.0.4
YITH WooCommerce Wishlist Premium	 	by YITHEMES – 2.0.15
User Activation Keys	 	by D. Sader – 3.5.2
User Switching	 	by John Blackbourn – 1.0.9
WordPress Importer	 	by wordpressdotorg – 0.6.1
WP-Optimize	 	by Ruhani Rabin – 1.9
Jetpack by WordPress.com	 	by Automattic – 4.0.3
Wordfence Security	 	by Wordfence – 6.1.8
Settings
Force SSL:		–
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		0
API
API Enabled:		
WC Pages
Shop Base:		#11 - /shop/
Cart:		#12 - /cart/
Checkout:		#13 - /checkout/
My Account:		#14 - /my-account/
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		DiviNity
Version:		2.7.5
Author URL:		http://www.graphicmonk.com/
Child Theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		
Templates
Overrides:	 	–

**Comment by mikejolley** [comment]
For payment methods I've logged this https://github.com/woothemes/woocommerce/issues/11127

I don't see cash/card, but these are not added by WooCommerce core so must be an addon you are running. See your checkout settings.

**Comment by jeasysehgal** [comment]
Ah! Yes you are a Genius @mikejolley :) The Cash and Card options were being thrown by WooCommerce POS https://wordpress.org/plugins/woocommerce-pos/

Have disabled the plugin and we are back in business. Have contacted the plugin developer to update the plugin to support WOO 2.6.

On a personal note, The WooCommerce Pos is a great feature to incorporate into the Core WOO at some stage. This will enhance the overall market share for WOO and Wordpress in general.

Catch you later. Thanks.
