### ISSUE TITLE
Inconsistent elements in payment methods between checkout and order-pay pages

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#11129]
The payment method elements on the checkout page appear directly inside the li.wc_payment_method  element, but on the order-pay page, used for retrying payments, the label element is preceded by an empty paragraph tag and wrapped in a paragraph tag, which throws off styling.

Styling these paragraphs as inline blocks makes the appearance consistent, but a better solution is to ensure that the HTML is identical.

**Comment by claudiosmweb** [comment]
> but on the order-pay page, used for retrying payments, the label element is preceded by an empty paragraph tag and wrapped in a paragraph tag, which throws off styling.

Not sure what you mean...

![screenshot from 2016-06-14 22-18-29](https://cloud.githubusercontent.com/assets/1264099/16065123/0193d188-327e-11e6-85ee-287cb62a97b8.png)

See the `form-pay.php` and the `payment-method.php`:

https://github.com/woothemes/woocommerce/blob/master/templates/checkout/form-pay.php#L72-L82

https://github.com/woothemes/woocommerce/blob/master/templates/checkout/payment-method.php#L26-L28

**Comment by galbaras** [comment]
I think this may be the result of an extra application of wpautop() to the output in one case. Surely you can see the blank line after the input element, then the label and then a div element. If you pasted this into the WP editor, it would be rendered as a blank paragraph, followed by the label wrapped in a paragraph.

I see your screenshot and now, here's mine:

![image](https://cloud.githubusercontent.com/assets/7981897/16068884/3069be98-330d-11e6-8c85-63292e49fa0c.png)
