### ISSUE TITLE
Unknown SSL protocol error in connection

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#11126]
Hi,

I am unsure if this is the proper forum to post this issue. 

I am trying to pair WooCommerce REST API using my app. I get this error:

Error: Unknown SSL protocol error in connection to www.cloudcartconnector.com:443

Here is the URL:

https://www.dinyashopfittings.com.au/wc-auth/v1/access_granted?app_name=Cloud_Cart_Connector&user_id=info_AT_dinyadesigns.com.au%2Chttps%3A%2F%2Fwww.dinyashopfittings.com.au&return_url=https%3A%2F%2Fwww.cloudcartconnector.com%2Fintegrations%2Fwoocommerceredirect&callback_url=https%3A%2F%2Fwww.cloudcartconnector.com%2Fintegrations%2Fwoocommerceauthcallback&scope=read_write&wc_auth_nonce=2ec6ff0446

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/1679993/16062178/91a20c78-325f-11e6-82be-5e35d819d9e9.png)

WooCommerce version is 2.55. CloudCartConnector.com uses TLS 1.2. Do you need to add code to support this version of TLS?

**Comment by claudiosmweb** [comment]
@jmawebtech 

> Error: Unknown SSL protocol error in connection to www.cloudcartconnector.com:443

Your server is not being able to check the SSL from `cloudcartconnector.com`.
Most often it is solving updating the OpenSSL.
