### ISSUE TITLE
Add a Review Button

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#11128]
## EXPLANATION OF THE ISSUE

When a product has no existing reviews, there is no obvious way to add one. The customer likely has to scroll a bit and find the reviews tab. Reviews are important social proof for an e-commerce store and we want to reduce the amount of friction it takes to leave one.

## STEPS TO REPRODUCE THE ISSUE

Compare a product page that has existing reviews to one that does not. The product page with reviews has a link such as "(2 customer reviews)" which jumps to the reviews tab. One would expect a similar link to add a review if no reviews currently exist.

## SUGGESTION

For consistency and visibility's sake, I think an "Add a review" button would encourage more reviews.

When the button is clicked, the page will smooth scroll to the Reviews tab and make it active.

I have already implemented this on a site. [View a live demo »](https://www.oldshoedawg.com/p/romika-milla-women-replacement-insole-sand/)

![add-review-button](https://cloud.githubusercontent.com/assets/11021583/16063502/91a53a8a-324e-11e6-8040-97960eadb264.jpg)

## OTHER CONSIDERATIONS

I think the stars ratings should also be clickable and link to the reviews tab. Also, adding some smooth scrolling would make clicking the customer reviews link so much more satisfying :)

Thanks for your consideration!

**Comment by claudiosmweb** [comment]
You can change it in your theme like you did.
No really a priority, since people should leave a review only after buy the product... But I'm logging your suggestion into your roadmap for voting: https://trello.com/c/FPmbTzwi/88-show-add-a-review-text-when-product-don-t-have-any-review

**Comment by lawkwok** [comment]
Thanks for adding it to the roadmap. The button is definitely for those who have already bought the product, but we want to make it as easy as possible :)

**Comment by claudiosmweb** [comment]
@lawkwok then you should consider follow-up emails, which are much more efficient.

**Comment by lawkwok** [comment]
Are you referring to the Follow-up Emails extension? We currently use that to send review emails to customers. Since that plugin just sends a link to the product page, having a more optimized product page experience should help conversions.
