### ISSUE TITLE
[API] Application Password Method not working for HTTPS urls.

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11124]
When using HTTP url and application password plugin, it works fine.. 

```
{
  "namespace": "wc/v1",
  "routes": {
    "/wc/v1": {
      "namespace": "wc/v1",
      "methods": [
        "GET"
      ],

```

When I use HTTPS and the same Application Password, I get this.

```
{
  "code": "woocommerce_rest_authentication_error",
  "message": "Consumer Key is invalid.",
  "data": {
    "status": 401
  }
}
```

Note: I am testing this using Postman.

**Comment by claudiosmweb** [comment]
What plugin?

**Comment by amjad0** [comment]
@claudiosmweb As recommended by WP API documentation. 
https://github.com/georgestephanis/application-passwords

**Comment by claudiosmweb** [comment]
@amjad0 good catch, I just fixed it ^.
