### ISSUE TITLE
GRID VIEW ERROR AFTER Woo 2.6 Update

### ISSUE THREAD

**Issue by NgashTony** [woothemes/woocommerce#11139]
Hi Guys, My website store Front Just went Bananas After the WooCommers 2.6 Update, the grid view is displaying products in this Format  []
                                                           [] []
                                                           []
                                                           [] []  
 You Catch the drift, I have tried tweaking this code in the content-product.php (woocommerce/content-product.php) but no change

// Store column count for displaying the grid
if ( empty( $woocommerce_loop['columns'] ) ) {
    $woocommerce_loop['columns'] = apply_filters( 'loop_shop_columns', 4 );
}
       
Please help me out.

Thanks

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/26-update-product-column-display-is-wrongwrong-number-of-products-shown?replies=1

^ theme/template file related. Read that post.

@jeffikus this was the issue I raised in one of our themes btw.

**Comment by NgashTony** [comment]
Let me check it out thanks.

**Comment by jeffikus** [comment]
Thanks @mikejolley
