### ISSUE TITLE
bad CVS rate import

### ISSUE THREAD

**Issue by canet** [woothemes/woocommerce#11136]
Trying to import tax rates from CSV into an ADDITIONAL TAX CLASS always imports data to the DEFAULT STANDARD RATES instead.

I'm running latest WP and Woocommerce release, no other plugins installed!

**Comment by mikejolley** [comment]
Need your CSV to check.

**Comment by canet** [comment]
here it is
[tax_rates_10.zip](https://github.com/woothemes/woocommerce/files/315674/tax_rates_10.zip)

**Comment by mikejolley** [comment]
You are missing the tax class column values. Leaving it blank = standard.

Example:

```
GB,*,*,*,0.0000,VAT,1,1,1,zero-rate
```
