### ISSUE TITLE
Shortcodes gets all weary

### ISSUE THREAD

**Issue by el-presidente** [woothemes/woocommerce#11135]
WooCommerce seems to have messed up in product shortcodes - see https://www.landgarden.se/ - the skus 1,2,3,4 should just display those four but actually outputs a lot more.

```
Odlingslåda är idealiska för inredning av olika typer av gröna växter, blommor, buskar och träd. Det finns flera olika modeller, fyrkantiga, avlånga och extra stora. Odlingslåda kan också med fördel användas för en mer praktisk utformning av köksträdgården.

[products skus = "1, 2, 3, 4" orderby = "skus"]

<h2>Klassiska balkonglådor</h2>
```

**Comment by el-presidente** [comment]
Seems to be only for SKU and not ID which is working so I better start transferring my shortcodes for products to ID's..

**Comment by el-presidente** [comment]
Yes it doesn't work - the bug came with the new upgrade - but I'm moving from SKU to ID now as they work.

**Comment by el-presidente** [comment]
And I can't remember if I even had spaces between the skus and inbetween =

**Comment by mikejolley** [comment]
See above fix.

**Comment by el-presidente** [comment]
Thanks Mike - while I have you: why can't WC output the order I give it in the shortcode, but chooses random. Fx there's is no way I can get it to output the following order:

[products ids="136,135,134,144,146,217,143"]

And there's no option of doing it either I can see in the docs https://docs.woothemes.com/document/woocommerce-shortcodes/#section-21 - like a orderby list or input value.

**Comment by el-presidente** [comment]
The default is alphabetical by title I've observed, but I want to use the list to be sorted by most sold hence the specific order. Should I create an enhancement issue?

**Comment by mikejolley** [comment]
Doing a manual sort is not something we want to add to core; it would be a performance issue. You can 'sort' products in the backend products section if you need a custom order.

**Comment by el-presidente** [comment]
OK - it just seems strange that per default it's not sorting after the input the user gives, but does it by title which is actually a duplicate option..

**Comment by mikejolley** [comment]
It does it by the orders supported by WP -see https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
