### ISSUE TITLE
WooCommerce message is moving above section

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#11134]
WooCommerce message is moving above section in WooCommerce Settings page.

![capture](https://cloud.githubusercontent.com/assets/3774827/16069386/c68173be-32ed-11e6-85b8-36e0922e4c3e.PNG)

Additionally, for theme support notice shipping zone notice spacing style for paragraph is applied:
![capture](https://cloud.githubusercontent.com/assets/3774827/16069531/e4b64d90-32ee-11e6-871a-92aa4da07fa2.PNG)

CC @claudiosmweb @mikejolley IMO they should be below section just like of settings update message :P

**Comment by mikejolley** [comment]
max width is for readability

**Comment by mikejolley** [comment]
This is not an inline notice - it should move to where regular admin notices are, in this case above navnavnav
