### ISSUE TITLE
content-product.php hasn't had the version number increased

### ISSUE THREAD

**Issue by Dooza** [woothemes/woocommerce#11146]
After the update I reviewed which templates needed updating, and this wasn't one of them, yet I was having issues with the number of products displaying per row. I looked at my old template and compared it to the current one in the latest update, they both said version 2.5.0 but the new one was different. Once I removed the code and made sure I had added the extra class name in post_class (the only reason for overriding the template) everything was back to normal.

I checked history of the template file here in github and could see the code being removed but the version didn't get updated.

If this had been changed developer would have been aware that the template needs to be updated.

**Comment by mikejolley** [comment]
cc @jameskoster
