### ISSUE TITLE
Woocommerce 2.6 - Shipping Method Issue

### ISSUE THREAD

**Issue by emyawasap** [woothemes/woocommerce#11140]
## EXPLANATION OF THE ISSUE

After Updating to version 2.6 of woocommerce I have noticed that under Shipping Zones, you will be adding Shipping Methods, That part is cool. however most of the shipping now is based on table rate shipping. but the shipping method is only limited to 'flex rate, free shipping, local pickup' which has a limited options unlike using table rate.

**Comment by mikejolley** [comment]
You can use table rates with new zones.

Other methods will be updated with zones support over time.

**Comment by emyawasap** [comment]
Alright. Thanks for the update. :+1:
