### ISSUE TITLE
PayPal issue on Cart page

### ISSUE THREAD

**Issue by NenadObradovic** [woothemes/woocommerce#11144]
## EXPLANATION OF THE ISSUE

Fatal error: Call to a member function get_payer_id() on a non-object in D:\projects\lime\wp-content\plugins\woocommerce-gateway-paypal-express-checkout\includes\class-wc-gateway-ppec-cart-handler.php on line 136

## STEPS TO REPRODUCE THE ISSUE

I just updated the latest version of WooCommerce plugin 2.6 and try to go to Cart page. Also I just enabled PayPal shipping without connection to PayPal account

Best Regards
Nenad

**Comment by NenadObradovic** [comment]
Also I can't now disabled PayPal Configuration for PayPal Express Checkout so only way is to clear database with that option

**Comment by mikejolley** [comment]
Disable the plugin in the 'plugins' section. I'll let someone know there may be an issue in the extension.

**Comment by NenadObradovic** [comment]
Thanks for the update.

I removed this option from database and fix it
I hope you will fix soon this issue 

Best Regards,
Nenad

**Comment by bobbingwide** [comment]
+1 - similar problems - it's a development environment so I just deactivated the plugin.
