### ISSUE TITLE
Cart Page Issue

### ISSUE THREAD

**Issue by NenadObradovic** [woothemes/woocommerce#11157]
## EXPLANATION OF THE ISSUE

Error found in: D:\projects\theme22\wp-content\plugins\woocommerce\includes\libraries\class-wc-eval-math.php, nfx, 117 
Warning: illegal character '%' in D:\projects\theme22\wp-content\plugins\woocommerce\includes\libraries\class-wc-eval-math.php on line 289
Error found in: D:\projects\theme22\wp-content\plugins\woocommerce\includes\libraries\class-wc-eval-math.php, nfx, 117 
Warning: illegal character '%' in D:\projects\theme22\wp-content\plugins\woocommerce\includes\libraries\class-wc-eval-math.php on line 289

## STEPS TO REPRODUCE THE ISSUE

I just updated plugin to the latest version and tried to go to Cart page

Best Regards,
Nenad

**Comment by mikejolley** [comment]
Go to flat rate shipping settings and tell me what is in your cost field.

**Comment by NenadObradovic** [comment]
Please check this
http://screencast.com/t/S4YCb5PY

**Comment by mikejolley** [comment]
The rates at the bottom contain 18%. This is invalid. Remove it.
