### ISSUE TITLE
max fee parameter in Shipping Zones

### ISSUE THREAD

**Issue by emersonag** [woothemes/woocommerce#11158]
## EXPLANATION OF THE ISSUE

Shipping Zones > Local Zone > Flat Rate, currently only allows for `min_fee` 

Example: `[fee percent="7" min_fee="25"]` is a 7% fee $25 minimum fee

Need: `max_fee` parameter to limit fee to maximum fee charge. Many deliveries are local and a max fee of $95 (for example) is desired. Many large items may run the fee upwards to $200 which is overcharging and customers will go elsewhere.

Please add `max_fee` to Flat Rate

**Comment by BFTrick** [comment]
Hey @emersonag I updated your original post. Since this is a feature request there's no reason to post your system status. I also added some code highlighting to make it easier to read.

Will let one of the core devs evaluate.

Originally from: https://woothemes.zendesk.com/agent/tickets/431596

**Comment by mikejolley** [comment]
Please search first https://github.com/woothemes/woocommerce/issues/11151
