### ISSUE TITLE
New Order Issue

### ISSUE THREAD

**Issue by aneeshjajodia** [woothemes/woocommerce#11153]
I've been getting an issue while trying to create a New Order via Backend after the latest WC update.

<img width="1440" alt="screenshot 2016-06-16 11 57 38" src="https://cloud.githubusercontent.com/assets/1062704/16107369/9724c202-33b9-11e6-9fa8-f400332b17ee.png">

**Comment by mikejolley** [comment]
woocommerce-product-stock-alert needs patching.

And you need to ensure the update has ran and the tables exist (see system status) for the notice. Although, that may also be triggered by the stock alert plugin too.
