### ISSUE TITLE
sale-flash is covered by product image

### ISSUE THREAD

**Issue by BinaryMoon** [woothemes/woocommerce#11156]
On the category and product pages the 'onsale' span is hidden by the product image.

![screen shot 2016-06-16 at 10 43 36](https://cloud.githubusercontent.com/assets/1004130/16112472/62a013ba-33af-11e6-98bc-682838c355ae.png)

I think this can be fixed by changing the order of the html so it appears after the image - or you can add a z-index but I imagine that could cause issues with themes

**Comment by mikejolley** [comment]
@BinaryMoon what theme is that? 

https://dl.dropboxusercontent.com/s/i2c87q671qlzffi/2016-06-16%20at%2012.23.png?dl=0

**Comment by BinaryMoon** [comment]
It's a premium theme that I've recently released on wordpress.com
https://carmackdemo.wordpress.com/

It currently doesn't have woocommerce support but I am looking at adding it for the .org version.

Since you pointed this out I've dug into the elements and it seems it's happening because the global img style is applying 'position:relative;' to all images. Not sure why this would affect the depth though.

**Comment by claudiosmweb** [comment]
@BinaryMoon Ohhh are you the theme author? So why you can just fix it using `z-index`?

**Comment by claudiosmweb** [comment]
Not an issue with WooCommerce, only in your theme, so I'm closing it.

**Comment by mikejolley** [comment]
Heh. To add, we shouldn't really add z-index to core if not needed here. A blanket position:relative for *all* images is probably not a great idea to be honest. It adjusts the position in the layout. Say I have a position:absolute image on purpose, thats gonna break it.
