### ISSUE TITLE
paypal not charging postage

### ISSUE THREAD

**Issue by Jjas88** [woothemes/woocommerce#11169]
I updated woocommerce yesterday and now paypal isn't chargin for the postage even through it is showing that it is being charged on my site

`
### WordPress Environment ###

Home URL: http://westcountryangling.com
Site URL: http://westcountryangling.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.20
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/0.9.8b

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.45 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (12) ###

Akismet: by Automattic – 3.1.11
Alpine PhotoTile for Instagram: by the Alpine Press – 1.2.7.7
Alpine PhotoTile for Google Plus and Picasa: by the Alpine Press – 1.2.6.8
Backup: by Backup Guard – 1.1.8
CloudFlare: by Ian Pye
Jerome Chen
James Greene
Simon Moore
David Fritsch
John Wineman (CloudFlare Team) – 1.3.24

CM Answers Anonymous Posting: by CreativeMindsSolutions – 1.3.5
CM Answers Pro: by CreativeMindsSolutions – 2.9.6
Code Snippets: by Shea Bunge – 2.6.1
Elegant Themes Updater: by Elegant Themes – 1.1
Jetpack by WordPress.com: by Automattic – 4.0.3
WooCommerce: by WooThemes – 2.6.1
WP Super Cache: by Automattic – 1.4.8

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #156 - /shop/
Cart: #157 - /cart/
Checkout: #158 - /checkout/
My Account: #159 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Divi
Version: 2.7.5
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
-->

**Comment by mikejolley** [comment]
You need to login to your PayPal account and remove all shipping rules you have setup there. PayPal shipping rules override WooCommerce shipping rules now that shipping is sent as a 'real' shipping line.
