### ISSUE TITLE
Local Delivery in 2.6

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11164]
Do we still need this folder in 2.6: https://github.com/woothemes/woocommerce/tree/master/includes/shipping/local-pickup ?

I don't believe there are plans to keep Local Delivery around, so should we just move that class to the legacy folder for local delivery?

**Comment by WPprodigy** [comment]
Woops, that is local pickup, no delivery xD

**Comment by BurlesonBrad** [comment]
middle of MeetUp.  open GH. show folks WooCommerce. open issue tab. find this.  
......LAUGH MY A$$ OFF!!!!!!!!!!!!!  :heart: _that was awesome!_
best ice-breaker ever

**Comment by WPprodigy** [comment]
Haha, of course.

This is what happens when Caleb doesn't get his daily dose of Mountain Dew 😬
