### ISSUE TITLE
NOT WORKING: Hide other shipping methods when FREE SHIPPING is available

### ISSUE THREAD

**Issue by gruppenrausch** [woothemes/woocommerce#11165]
hi there

## EXPLANATION OF THE ISSUE

i'm running wordpress 4.5.2. and made the update from woocommerce 2.5. to 2.6 (and just now to 2.6.1). since the update to 2.6., in the cart, other shipping methods are shown, although the minimum order for free shipping is reached. it worked before.
i tried that one: https://docs.woothemes.com/document/hide-other-shipping-methods-when-free-shipping-is-available/ not working.

## STEPS TO REPRODUCE THE ISSUE

when u got to http://www.blattrausch.de/ and put products with an amount over 80€ in the cart, free shipping is shown up. but still the 3€ standard shipping is shown. which shouldnt.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.blattrausch.de
Site URL: http://www.blattrausch.de
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.22
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.21.0
OpenSSL/0.9.8o

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (27) ###

Coming Soon Page & Maintenance Mode by SeedProd: von SeedProd – 5.0.2
Essential Grid: von ThemePunch – 2.0.9.1
Gravity Forms Multilingual: von OnTheGoSystems – 1.3.9
WPBakery Visual Composer: von Michael M - WPBakery.com – 4.11.2
Language Fallback: von Bernhard Kau – 1.0.3
Multilingual Tools: von WPML Compatibility Team – 1.2
Organics Utilities: von AxiomThemes – 2.0
Revolution Slider: von ThemePunch – 5.1
WPML Multilingual CMS: von OnTheGoSystems – 3.4.0
Vendidero Helper: von Vendidero – 1.1.1
WooCommerce Email Validation: von Hugh Lashbrooke – 2.0
WooCommerce Germanized Pro: von Vendidero – 1.5.3
WooCommerce Germanized: von Vendidero – 1.6.6
WooCommerce Gift Card: von Isaac Oyelowo – 2.2
WooCommerce Multilingual: von OnTheGoSystems – 3.8
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.5.32
WooCommerce Sequential Order Numbers: von SkyVerge – 1.7.0
WooCommerce Wholesale Prices: von Rymera Web Co – 1.2.4
WooCommerce: von WooThemes – 2.6.1
Yoast SEO: von Team Yoast – 3.3.1
WPML All Import: von OnTheGoSystems – 2.0.2
WPML CMS Nav: von OnTheGoSystems – 1.4.18
WPML Media: von OnTheGoSystems – 2.1.21
WPML Sticky Links: von OnTheGoSystems – 1.3.18
WPML String Translation: von OnTheGoSystems – 2.3.8
WPML Translation Management: von OnTheGoSystems – 2.2.0
YITH WooCommerce Gift Cards: von YITHEMES – 1.0.10

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Mein Konto: #7 - /mein-account/

### Taxonomies ###

Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Organics
Version: 1.0
Author URL: http://axiomthemes.net/
Child Theme: ✔
Parent Theme Name: Organics
Parent Theme Version: 1.2
Parent Theme Author URL: http://axiomthemes.net/
WooCommerce Support: ✔

### Templates ###

Overrides: organics-child/woocommerce/emails/admin-failed-order.php
organics-child/woocommerce/emails/customer-completed-order.php
organics-child/woocommerce/emails/email-styles.php

`

**Comment by claudiosmweb** [comment]
Not an issue with WooCommerce my friend!

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support
