### ISSUE TITLE
Attributes and Variation Layout on Cart & Checkout Page

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/woocommerce#11179]
Default and Custom are two different things, I know. I totally **get that**.  However.....  Does it make any sense to align the attribute label and it's variation description on top of each other? 

![variations-cart](https://cloud.githubusercontent.com/assets/6208757/16169392/253b8fa2-34f1-11e6-8542-4b5400f60acc.png)

On both the cart and the checkout page, the current layout lengthens the page **significantly!**  It's exponentially **worsened** when there are multiple items in the cart & checkout.

Now, I'm all about human behavior and doing my damndest to be a bridge between **a lot of users and store owners** and the WooNinjas.  Since I've seen this request come up over and over and over again, I can't help but ask if anyone sees any reason why this layout can't be modified in the next release?

![variations-cart-new-layout](https://cloud.githubusercontent.com/assets/6208757/16169434/91fbcc4a-34f3-11e6-99e5-4e53b4a003fe.png)

The new layout simply would take the attribute name along with it's variation description and align them so that the attribute ```name``` is on one line, it's variation ```description``` is on the next, then **both** of those get a ```div``` and are aligned ```left```.

**FYI:** The attribute name and the variation description are stacked _(as opposed to both being on **one** long line)_ to accommodate for any longer/more descriptive attribute labels and variation labels.  

I have found **zero** theme conflicts or plugin issues on any of the sites I've done this on. So, does anyone see a reason why this proposed layout would **not** be able to become **core**?

**Comment by mikejolley** [comment]
This is a Storefront issue right? Default is side by side: http://glui.me/?i=lxxxyo582g4puke/2016-06-18_at_12.21.png/

**Comment by BurlesonBrad** [comment]
Right. But.... wait, eh..... ok do this.... Take the demo.woothemes.com's and pick a product.  Now, instead of just one variation like _size_ **or** _color_, go ahead and add **two** attributes for the variation.  Heck, crank it up a notch and add **three** attributes! Ok, now run over to the cart/checkout page.  

Each **additional** attribute comes up on a new line, right?

**Comment by roykho** [comment]
Just to drop something to keep in mind here. In other languages such as Russian which is between 10% to 30% longer than English characters when translated over can easily get jumbled up where when it gets too long, it would drop down to the next line potentially causing confusion if the label is before it. Might have to play around with word wrap on this one.

**Comment by BurlesonBrad** [comment]
@roykho The blue font paragraph text is right at **doubled** the size of the actual text.
![variation-cart-roys-concern](https://cloud.githubusercontent.com/assets/6208757/16172776/b73c9d16-3554-11e6-9a85-12f837f216b6.png)

**Comment by claudiosmweb** [comment]
"Align left" can be a problem with someday we implement that feature to change variations in the cart...

**Comment by BurlesonBrad** [comment]
ugh.... I think this is being **Lost in Translation**  Ok, it's a valid point, but let's try to get this demonstrated another way:  Run over here: http://www.calvertkettlecorn.com/product/2-gallon-tin/?attribute_tin-design=Country+Birdhouse, pick 7 flavors real quick, then head over to the cart and we'll all be looking at this:
![variation-popcorn](https://cloud.githubusercontent.com/assets/6208757/16174506/611f0de8-358a-11e6-93e6-6d162f9a77b5.png)
#### Just so we're all on the same page:
I'm **not** in the least bit suggesting that **BOTH** the ```attribute name``` of **Bag 1, Bag 2, ...., & Bag 7** should be on the **same line** as the ```variation title``` of **Cheese, Banana, ...., & Vanilla**
so that it would read **Bag 1:** Cheese **Bag 2:** Banana .... **Bag 7:** Vanilla

_that's not it at all_

Pardon my horrific hack job with the graphic, but remember that URL, _(now keep @roykho's comment in mind as well :wink: )_ but look what happens here:
![variation-popcorn2](https://cloud.githubusercontent.com/assets/6208757/16174568/924b0e06-358c-11e6-888b-8a4c29f51254.png)
No, that's not the best layout.  _**WHY?**_ Well, b/c it didn't take into account any spacing and with that additional spacing would come my initial concern with the wording as @roykho additionally pointed out. Ok, so we're on the right track.  But :arrow_double_down: look at this page :arrow_double_down: 
![screencapture-www-calvertkettlecorn-com-checkout-1466296719887](https://cloud.githubusercontent.com/assets/6208757/16174579/0355c514-358d-11e6-9bc9-7faa3a0fd357.png)

### We **CAN** Do Better :+1: 

And, @claudiosmweb , should the day come when you'd like to add a ```chosen``` or other selection method for changing the variations in the cart, then.... **that's AWESOME!**

Which layout's gonna work then? Being stacked on top of each other like they are now will implement a chosen selector actually opening **on-top-of** the additional options below it. Having them side-by-side means that the selectors would open and each of the other attribute names and variation would **still be visible.**

**Comment by claudiosmweb** [comment]
@BurlesonBrad feature to change variations in the cart:

![screenshot from 2016-06-18 22-19-55](https://cloud.githubusercontent.com/assets/1264099/16174659/d6d1f1be-35a2-11e6-931d-1870802f85eb.png)

**Comment by claudiosmweb** [comment]
http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/4090265-woocommerce-allow-edit-of-product-variations-in

**Comment by claudiosmweb** [comment]
> And, @claudiosmweb , should the day come when you'd like to add a chosen or other selection method for changing the variations in the cart, then.... that's AWESOME!

And yes, I have plans to try it soon :P

**Comment by BurlesonBrad** [comment]
Surely there's a layout where those can be next to each other horizontally instead of stacked vertically.
Currently that layout makes the cart & checkout pages wAAAAAAy too long.
Perhaps on mobile that layout would work, but on desktops?  Surely there's a way to arrange those so that they are horizontal.  
The bottom line here is that the Call To Action on the Cart page is to **Proceed to Checkout**, right?
And the Call To Action on the checkout page is to **Pay** _via whatever method_

Putting those in a vertical layout places the two most critical buttons wAAAAAAAy down the page.  The store owner can obviously hook in and move the buttons _(similar to what I did w/ the **Proceed to Checkout** button on the second screenshot in the first post)_ But even then, once the variations start adding up, both the **Proceed to Checkout** and **Payment** buttons are so stinkin' far down the page.  

Surely we can arrange the variations _(even the proposed select options)_ horizontally?

**Comment by claudiosmweb** [comment]
Do not understand why you are doing it something so big and noisy, it's just CSS, it can be solved in your theme:

```css
.woocommerce .cart .product-name .variation dt,
.woocommerce-page .cart .product-name .variation dt {
    float: left;
    margin-right: 5px;
    display: block;
}
```

![screenshot from 2016-06-19 16-09-16](https://cloud.githubusercontent.com/assets/1264099/16179320/31a3e54e-3638-11e6-9489-409af6a5d362.png)

Or if you really hate your customers, you can put all the items side by side, no need to worry for what @roykho said, since you don't need any `width`.

First you need to change the template `cart/cart-item-data.php` to:

```php
<div class="variation">
	<?php foreach ( $item_data as $data ) : ?>
		<p class="variation-<?php echo sanitize_html_class( $data['key'] ); ?>"><strong><?php echo wp_kses_post( $data['key'] ); ?>:</strong> <span><?php echo wp_kses_post( wpautop( $data['display'] ) ); ?></p>
	<?php endforeach; ?>
</div>
```

And then you can use this CSS:

```css
.woocommerce .cart .product-name .variation p {
    float: left;
    display: block;
    margin-right: 20px;
}

.woocommerce .cart .product-name .variation span {
    display: block;
}
```

![screenshot from 2016-06-19 16-28-00](https://cloud.githubusercontent.com/assets/1264099/16179395/cf11146c-363a-11e6-9738-74f694f68551.png)

**Comment by mikejolley** [comment]
CSS FTW :)

**Comment by linesbytim** [comment]
I've got a similar problem on both my cart and checkout page. 
![Attributes on cart page](https://user-images.githubusercontent.com/93785924/140545636-59778482-03a4-44b8-a339-508dc7cc4985.png)

Items with three attributes list the attributes and also with their title whilst the ones with two are inline and do not bear the title. Is their any way I can get them all like the ones for two attributes? (So, Amsterdam and Rotterdam are perfect, how can I get They Bay also shown in this way?)

**Comment by phpokdeveloer** [comment]
> http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/4090265-woocommerce-allow-edit-of-product-variations-in
