### ISSUE TITLE
Product price is not always float

### ISSUE THREAD

**Issue by BJ1ADUMUP** [woothemes/woocommerce#11175]
Using Woo api v3, got problem is that price, regular_price and sale_price are declared in docs to be float, but WooCOmmerce allows to save price "%" or simple ",". In these cases response is not deserialized.
Now we use price as string and try to parse float out of it. Not a big problem, but.. if it is declared as double in docs, would be happy to always receive a valid value

## STEPS TO REPRODUCE THE ISSUE

Set price to "%%%......-----" and try do deserialize response using field types given in api docs

**Comment by claudiosmweb** [comment]
@BJ1ADUMUP we need update the docs to be as `string`, like we did with REST API v1 docs.
Thanks for report it, but I'm moving it to https://github.com/woothemes/woocommerce-rest-api-docs
