### ISSUE TITLE
jquery.payment throwing an error when working with Stripe Plugin

### ISSUE THREAD

**Issue by jackabox** [woothemes/woocommerce#11170]
## EXPLANATION OF THE ISSUE

Just updated to the latest version of WooCommerce (2.6.1) and the Official Stripe Plugin (3.0.2). Whenever trying to checkout using the form the console is logging an error with the jquery.payment.min.js

```
jquery.payment.min.js:1 Uncaught TypeError: Cannot read property 'split' of undefined
a.payment.cardExpiryVal @ jquery.payment.min.js:1
a.payment.fn.cardExpiryVal @ jquery.payment.min.js:1
a.fn.payment @ jquery.payment.min.js:1
stripeFormHandler @ stripewoo.js:18
dispatch @ jquery.js:3
r.handle @ jquery.js:3
trigger @ jquery.js:3
a.event.trigger @ jquery-migrate.min.js:2
triggerHandler @ jquery.js:3
submit @ checkout.min.js:1
dispatch @ jquery.js:3
r.handle @ jquery.js:3
```

## STEPS TO REPRODUCE THE ISSUE

1. Upgraded to WooCommerce 2.6
2. Upgraded to WooCommerce Stripe Gateway 3.0.2
3. Updated keys in the backend
4. Tested checkout on form
5. Fails to process, returns error.

**Comment by mikejolley** [comment]
I saw this with a different stripe plugin. Check you don't have both active..

**Comment by jackabox** [comment]
Cheers, been going crazy (can tell it's a Friday). Had a legacy plugin running alongside.
