### ISSUE TITLE
Can't turn off  In Stock message on product

### ISSUE THREAD

**Issue by kristinaplauche** [woothemes/woocommerce#11171]
## EXPLANATION OF THE ISSUE

The In Stock message appears on the product even if "Enable Stock Management" is dis-abled in WooCommerce settings and/or on the product itself.

I would expect that if Inventory is not managed and/or if inventory is managed, but the Stock Display format is set to Never show stock amount, that no stock messages would display.

As it is now, I cannot turn off the in-stock message. 

## STEPS TO REPRODUCE THE ISSUE
WooCommerce>Settings>Products>Inventory
Uncheck the "Enable Stock Management" box.  And/or You can also leave it checked here and uncheck it on the product and the results are the same. 

View 

## SYSTEM STATUS REPORT

```
This is on a local install: `
### WordPress Environment ###

Home URL: http://woothemes.dev
Site URL: http://woothemes.dev
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.1
PHP Version: 7.0.7-4+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by claudiosmweb** [comment]
@kristinaplauche what kind of stock message?

Even not managing stock you need at least to show the "Out of stock" or "In stock", since you have settings for it at product level:

![screenshot from 2016-06-17 16-32-08](https://cloud.githubusercontent.com/assets/1264099/16162329/0f4a892a-34a9-11e6-99c1-278ae6969ee8.png)

**Comment by mikejolley** [comment]
Yup. Intentional as of 2.6 due to that option.

**Comment by kristinaplauche** [comment]
Sorry. I'm AFK. People need to be able to turn off In Stock message. It
shows even if Inventory management is not enabled. So customers who have
previously had this message turned off, now have it showing and they don't
want it. They didn't change their settings, but now it's showing up in 2.6
and they need to be able to turn it off like they have in the past. It
appears that the option to turn it off is in the settings, it just doesn't
work.

**Comment by WPprodigy** [comment]
I've had quite a few complaints about this as well. If inventory is disabled, why would they need to show the "in stock" message? Especially doesn't make sense for for virtual product stores (like woothemes.com).

Maybe we could make this an option here: http://cld.wthms.co/1jZIV/8zFMb2VL ?
