### ISSUE TITLE
Coupon maximum spending calculated after taxes

### ISSUE THREAD

**Issue by damarusama** [woothemes/woocommerce#11177]
## EXPLANATION OF THE ISSUE

When using a coupon that has a maximum amount to be spent, that maximum amount includes the taxes. Which is fine, for most case, but when a new client arrive and then use the coupon, it work well, until they choose their region, then the taxes get calculated and if the total amount of the order exceed the coupon max spending, then the coupon is disable, without error of any sort. 

## STEPS TO REPRODUCE THE ISSUE

Buy items, check out, enter the coupon, once you select your region and the taxes are calculated, if the amount is over the coupon maximum spending, then the coupon is removed.

**Comment by mikejolley** [comment]
So it seems to disable itself as it should, so what is the expected behavior?

**Comment by damarusama** [comment]
Is there a system in place that alert the client about the coupon not being active anymore? We use extra fields at the checkout and the client doesn't really see that the coupon hasn't been applied until after they pay (most of the time)
