### ISSUE TITLE
Website account registration 

### ISSUE THREAD

**Issue by DBrenn06** [woothemes/woocommerce#11186]
Account registration is completely messed up
1) saves wrong username
2) redirects lost password back to same account login/register page
3)Any links like dashboard, change shipping/billing address and etc. All redirect to same account page
4) in the last update before 2.6.0 I noticed it wouldn't send an email with password reset link, since this update doesn't even go to reset page, not sure if this is still am issue, but wanted to make you aware of it, just in case.

**Comment by mikejolley** [comment]
I stopped looking once I confirmed at least 2 of your points were not occurring on my test sites.

https://dl.dropboxusercontent.com/s/yxnx3ihqvdtne4m/2016-06-20%20at%2014.49.png?dl=0

See if you have account page template overrides, and if you have a caching plugin, exclude the account page.

You can reply back here with your findings, but as I cannot replicate I am closing this issue for now and chalking it up as a theme conflict.

**Comment by DBrenn06** [comment]
i'm not good at html coding...what exactly would the account page info. look like it the text? I tried override with my theme...and without over riding neither worked.. I currently use the wootique theme, should I try another like storefront?

**Comment by DBrenn06** [comment]
I tried a new theme, storefront with child theme. Boutique, I have the same issue as I did with wootique theme, so it isn't an theme issue. Can u tell me how to fix this exactly as I don't know much bout editing HTML or CSS

**Comment by DBrenn06** [comment]
I want an account page, as I want to offer an wish list option.
