### ISSUE TITLE
My Account Page Suggestions

### ISSUE THREAD

**Issue by dare-devil-arrives** [woothemes/woocommerce#11189]
Instead of current structure,
![001](https://cloud.githubusercontent.com/assets/16662063/16183913/49945394-36d5-11e6-8fa7-113d2eda6fff.png)
it would be great if it is like this,
![002](https://cloud.githubusercontent.com/assets/16662063/16183920/5acad836-36d5-11e6-8bd1-81b609630ec0.png)

Reason : Current structure occupies page space making things look congested (specially in tables).
Whereas if you change structure by showing links on top, full width page is available and things look cleaner.
A setting to choose layout would also be great.

Just a suggestion :)

**Comment by claudiosmweb** [comment]
Bad idea with you have 10 or 50 items in this menu. And of course, you can change it by CSS in your theme.
