### ISSUE TITLE
2.6 Shipping to Rest of the World ~ Remove if not used

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/woocommerce#11184]
#### Sorry!
_this screenshot should have been me selecting the "Shipping Locations" area_
![rest-of-the-world](https://cloud.githubusercontent.com/assets/6208757/16175317/067a7a8e-35ae-11e6-8318-4c117b66a044.png)

A store owner sets the country that they ship to in the General Settings, then they go to set up their Zones. So, once the get to the Zone screen, they see the row labelled "Rest of the World".

Now, while the customer in the other country won't really be able to checkout, that doesn't help the store owner with confusion _(and I'd be willing to guess a ZenDesk ticket or two has come across about this as well)_

Is there anyway we can allow the store owner to remove that row?
_**better yet**_
Is there a way we can automatically hide that row when they've selected **only one** country to deliver to via **General > Selling Locations** or **General > Shipping Locations**

**Comment by mikejolley** [comment]
@BurlesonBrad A user can buy from an allowed location and ship to another location. 

This zone needs to stay (it's default/fallback and was present in table rates too) but if you have an idea for a wording change on that screen by all means say so.
