### ISSUE TITLE
hidden products type select

### ISSUE THREAD

**Issue by MahdiY** [woothemes/woocommerce#11183]
hi

woocommerce 2.6.1
woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-data.php Line 78

products type are hidden! remove hidden class from span ...

**Comment by mikejolley** [comment]
No need. This area is revealed with our javascript. There is no bug here in core. If yours is remaining hidden, rule out a conflict with another plugin.

**Comment by MahdiY** [comment]
thanks for your response
