### ISSUE TITLE
Shipping zones

### ISSUE THREAD

**Issue by DBrenn06** [woothemes/woocommerce#11185]
On wocommerce 2.6.0 I noticed when u have 2 shipping zones, one flat rate and one free shipping that both options are showing up. Free shipping is only suppose to replace flat rate shipping option once an certain amount is meet. So either time you only have one option available. The flat rate option until free shipping amount is meet. Then free shipping should be the only option. I don't want my customers being able to choose free shipping before the free shipping amount is met.

**Comment by mikejolley** [comment]
You've not setup the free shipping requires option (select box). Free shipping is hidden if you have a min amount and that option set.

It also does not replace flat rate - both are offered.

**Comment by DBrenn06** [comment]
I set it up but when I realized they could choose either option at the same time...it was pointless to offer a free for a certain amount, when both was offered for lower than the specified amount, so I went back to using the legacy.  I played around with the shipping zones to see if I could figure it out to only show flat rate till the free shipping amount kicked in, but I couldn't they could choose from free shipping or flate rate no matter what price they spent.

**Comment by mikejolley** [comment]
There is a snippet to offer one rate, same as with legacy.
