### ISSUE TITLE
[2.6.1] Every currency symbol appear to be $ both front-end and back-end.

### ISSUE THREAD

**Issue by korrio** [woothemes/woocommerce#11180]
## EXPLANATION OF THE ISSUE

WooCommerce v.2.6.1

Every currency symbol appear to be $ both front-end and back-end.
![Image of Dollar symbol](http://mamybooking.com/mamy/1.png)

## STEPS TO REPRODUCE THE ISSUE
Update woocommerce from Wordpress plugin dashboard.

**Comment by mikejolley** [comment]
This is due to a snippet you have on your site I expect. Look in your theme functions.php!

Use the https://wordpress.org/support/plugin/woocommerce in future.

**Comment by korrio** [comment]
fixed it, because of this plugin "Currency Switcher". Thanks.
