### ISSUE TITLE
wp wc product how to add product

### ISSUE THREAD

**Issue by lordspace** [woothemes/woocommerce#11182]
## EXPLANATION OF THE ISSUE

The image needs to be URL and I can't use local image.
Also how to set a featured image via WooCommerce CLI?

## STEPS TO REPRODUCE THE ISSUE

wp wc product create --title="Prod 002" --sale_price=5 --regular_price=10 --porcelain --sku=PROD_002 --images.0.src="http://localhost/test/ceramics-vase-1422630.jpg"  --featured_src="http://localhost/test/ceramics-vase-1422630.jpg"

**I also wanted to set the featured image.**
I have tried passing --featured_src without any success.
```
wp wc product list --fields="id,title,sku,featured_src"
+----+----------+----------+------------------------------------------------+
| id | title    | sku      | featured_src                                   |
+----+----------+----------+------------------------------------------------+
| 74 | Prod 002 | PROD_002 | http://localhost/wp-content/upload |
|    |          |          | s/2016/06/ceramics-vase-1422630-1.jpg          |
| 72 | Prod 001 | PROD_001 |                                                |
+----+----------+----------+------------------------------------------------+

wp wc product update 72 --featured_src="http://localhost/test/ceramics-vase-1422630.jpg"
Success: Updated product 72.

wp wc product list --fields="id,title,sku,featured_src"
+----+----------+----------+------------------------------------------------+
| id | title    | sku      | featured_src                                   |
+----+----------+----------+------------------------------------------------+
| 74 | Prod 002 | PROD_002 | http://localhost/wp-content/upload |
|    |          |          | s/2016/06/ceramics-vase-1422630-1.jpg          |
| 72 | Prod 001 | PROD_001 |                                                |
+----+----------+----------+------------------------------------------------+


````

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: bg_BG

### Server Environment ###

Server Info: Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/0.9.8t PHP/5.4.17
PHP Version: ❌ 5.4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 58 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.30.0
OpenSSL/0.9.8t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.29 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (7) ###

Go359 Branding: by Svetoslav Marinov (Slavi) – 1.0.0
Go359 Control Panel: Attachments: by Svetoslav Marinov (Slavi) – 1.0.0
Go359 Control Panel: by Svetoslav Marinov (Slavi) – 1.0.0
Go359 Signup: by Svetoslav Marinov (Slavi) – 1.0.0
Orbisius Auto Login: by Svetoslav Marinov (Slavi) – 1.0.0
Orbisius Modest WP Branding: by Svetoslav Marinov (Slavi) – 1.0.0
WooCommerce: by WooThemes – 2.6.1

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My Account: ❌ Page not set

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Don't works with local images since it must be available so you can download it using `wp_safe_remote_get()`.
