### ISSUE TITLE
Support for CodeClimate

### ISSUE THREAD

**Issue by bhubbard** [woothemes/woocommerce#11196]
CodeClimate is free for open source projects, and now supports WordPress standards for PHPCodeSniffer. It would be a good idea to create a config file for it. While the team doesn't need to use it on a regular basis it would be nice to see CodeClimate give more accurate results for those who reference it.

Repo on CodeClimate
https://codeclimate.com/github/woothemes/woocommerce

Example .codeclimate.yml
https://docs.codeclimate.com/docs/example-codeclimateyml

PHP Code Sniffer config instructions:
https://github.com/codeclimate/codeclimate-phpcodesniffer

**Comment by mikejolley** [comment]
We use scrutinizer-ci.com/g/woothemes/woocommerce/ which is also free for open source and seems to be more in depth. I don't see any benefit to using this?

**Comment by coderkevin** [comment]
Actually, it looks like Scrutinizer only checks PHP code and CodeClimate does both PHP and JavaScript

**Comment by bhubbard** [comment]
I see your point, I just thought it would be useful and nice for those who use CodeClimate. There would be no need for your team to use or reference it on a regular basis, but having a second free tool to review code shouldn't hurt.

**Comment by claudiosmweb** [comment]
Well I like Scrutinizer, but at least I can spell "CodeClimate" correct :P
But speaking seriously, it seems interesting, since we can use for JavaScript as well.

**Comment by mikejolley** [comment]
Good, @claudiosmweb you just volunteered :)

**Comment by claudiosmweb** [comment]
@mikejolley :heart:
