### ISSUE TITLE
wp wc product update ignores --porcelain parameter

### ISSUE THREAD

**Issue by lordspace** [woothemes/woocommerce#11197]
## EXPLANATION OF THE ISSUE
wp wc product update ignores --porcelain parameter

## STEPS TO REPRODUCE THE ISSUE

```
wp wc product create --path='/doc/site/staging.qsandbox.com/htdocs/' --sale_price='5' --regular_price='10' --title='new_title2' --porcelain
19

wp wc product update 19 --path='/doc/site/staging.qsandbox.com/htdocs/' --sale_price='5' --regular_price='20' --title='new_title' --porcelain
Success: Updated product 19.

```

## SYSTEM STATUS REPORT

```
woocommerce | 2.6.1 
```

**Comment by claudiosmweb** [comment]
`wp wc product update` do not ignore `--porcelain`, in fact `wp wc product update` do not support it.

You can check using `wp wc product update --help` and `wp wc product create --help`. So please, before you open an issue, check the command docs using `--help` or in: https://github.com/woothemes/woocommerce/wiki/WP-CLI-commands

You can check `wp user update` or `wp post update`, both don't have support for `--porcelain` too.
