### ISSUE TITLE
Add css class to coupon name to allow it to be uppercase

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#11190]
Coupons are internally always converted to lowercase (which is fine technically). In some countries it is more usual than coupon codes are _communicated_ (e.g. on flyers) to the user in upper case, e.g. ILOVECOUPONS instead of ilovecoupons.

I thought to change the way coupons are presented to the user by using `text-transform: uppercase`. But woocommerce outputs the coupon html stuff without a css selectable attribute for the coupon name:

```
<tr class="cart-discount coupon-ilovecoupons">
  <th>Coupon: ilovecoupons</th>
  <td data-title="Coupon: ilovecoupons">...</td>
</tr>
```

I am talking about the `<th>` line here. This should be changed to something like 
`<th>Coupon: <span class="woocommerce-coupon-name">ilovecoupons</span></th>`

which would allow me in a child theme to have
```
.woocommerce-coupon-name {
 text-transform: uppercase;
}
```

Looks like [wc_cart_totals_coupon_label](https://github.com/woothemes/woocommerce/blob/0f714a13a424ff3ab928ec1b3896e560d0123c42/includes/wc-cart-functions.php#L233) would need to be changed for this. 

Could this small change be done? I know I could also change the filter that auto-converts inserted codes to lower case, but I do not want to change (side-effects) the way coupons are internally handled, but just the way these are presented/displayed to the user.

**Comment by mikejolley** [comment]
Can be done with code already.

`
add_fitler( 'woocommerce_cart_totals_coupon_label', 'custom_woocommerce_cart_totals_coupon_label', 10, 2 );

function custom_woocommerce_cart_totals_coupon_label( $label, $coupon ) {
   return 'Coupon: '. strtoupper( $coupon->code );
}
`

No extra HTML is needed.

**Comment by joeljerushan** [comment]
change 'add_filter' instead 'add_fitler' ;) cheers #Typo

**Comment by membus** [comment]
Thanks for the code. It worked, but with one small issue. Non-latin characters like Ç are not uppercased. Is there a way to accomplish this as well?

**Comment by mikejolley** [comment]
use `wc_strtoupper` which calls mb_ string functions.

**Comment by membus** [comment]
> use `wc_strtoupper` which calls mb_ string functions.

Worked like a charm. Thanks a million @mikejolley.

**Comment by freefugga** [comment]
This is perfect!

**Comment by saeed-kashout** [comment]
hey guys

i want the field to only type uppercase
so when a customer add the code i want the field to automatically change the letters to uppercase 
could you please help me!
