### ISSUE TITLE
Bad param in NodeJS example wp_api should be wpAPI

### ISSUE THREAD

**Issue by kevin-frugier** [woothemes/woocommerce#11193]
The exemple given at this URL : http://woothemes.github.io/woocommerce-rest-api-docs/?javascript#libraries-and-tools mentions a parameter **wp_api**.
However, when you use it as such, even the Index request fails with error 400:

```
WooCommerce.get('', function(err, data, res) {
  console.log(data);
});
```

When we look in data at the path it tries to access we see it tries to talk to **/wc-api/wc/v1**.
However the documentation for index (http://woothemes.github.io/woocommerce-rest-api-docs/?javascript#index) mentions **/wp-json/wc/v1**

When we look in the code https://github.com/woothemes/wc-api-node/blob/master/index.js#L99
we see that this wp-json vs. wc-api switch is conditioned by **this.wpAPI** and we follow it to the init https://github.com/woothemes/wc-api-node/blob/master/index.js#L44
we see that is looks at the **wpAPI** parameters in the options and **NOT wp_api**.

Indeed, when we change to the proper wpAPI, then the index call above now works.

http://woothemes.github.io/woocommerce-rest-api-docs/?javascript#libraries-and-tools should instead give the following proper exemple:
```
// Install:
// npm install --save woocommerce-api

// Setup:
var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: 'http://example.com', // Your store URL
  consumerKey: 'consumer_key', // Your consumer key
  consumerSecret: 'consumer_secret', // Your consumer secret
  wpAPI: true, // Enable the WP REST API integration
  version: 'wc/v1' // WooCommerce WP REST API version
});
```

**Comment by claudiosmweb** [comment]
Reporting in the wrong place!

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce-rest-api-docs
