### ISSUE TITLE
Illegal characters allowed in shipping method price fields

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#11199]
When you add a shipping method and define the price of that shipping method (say Flat Rate in this example), you can set the price, but it doesn't prompt you when you accidentally enter an invalid character (such as a $ sign).

The result is a confusing error on the front end in the cart & checkout screens and there's no real way to know what the problem is:

Error found in: /[...]/wp-content/plugins/woocommerce/includes/libraries/class-wc-eval-math.php, nfx, 117 
Warning: illegal character '$' in /[...]/wp-content/plugins/woocommerce/includes/libraries/class-wc-eval-math.php on line 289

I think it should behave similar to regular pricing fields, for example on Products, it shows a notice which is quite handy:

![image](https://cloud.githubusercontent.com/assets/531540/16214088/360b0a20-3798-11e6-9d49-87c20f1f99dc.png)

And the label should probably also be adjusted to indicate that the currency symbol isn't required:

![image](https://cloud.githubusercontent.com/assets/531540/16214137/a94d8364-3798-11e6-95c6-cf9a165ee98a.png)

![image](https://cloud.githubusercontent.com/assets/531540/16214171/f72e195e-3798-11e6-9505-bb4f92f26718.png)

I think "Cost ($):" would be more clear than just "Cost:" and should remove some of the confusion and keep it consistent with other pricing fields throughout the system.

STEPS TO REPRODUCE THE ISSUE

1. Create a zone, add a shipping method
2. Define the cost as "$20" for example or just include any random illegal character
3. View the cart/checkout, there's an error.
4. Remove the illegal characters and the error disappears.

**Comment by claudiosmweb** [comment]
Thanks :)
