### ISSUE TITLE
[theme issue, please close] Product category shortcode only outputting two products per row in WC 2.6

### ISSUE THREAD

**Issue by scottbuscemi** [woothemes/woocommerce#11194]
This appears to be a theme-related issue, since the problem isn't happening with a default theme. This issue can be closed.

## EXPLANATION OF THE ISSUE

Starting with WooCommerce 2.6, the [product-category] shortcode is outputting only two products per row. This appears to be the result of the ".first" CSS class being added to every other `<li>` in the shortcode's output.

## STEPS TO REPRODUCE THE ISSUE

In WC 2.6, add the shortcode [product_category category="category-slug"] to a page, then view the page.

See WC 2.6 here: http://cframe.staging.wpengine.com/figure-frame/
WC 2.5 here: http://collectorframe.com/figure-frame/

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://cframe.staging.wpengine.com
Site URL: http://cframe.staging.wpengine.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (11) ###

ManageWP - Worker: by ManageWP – 4.1.33
BAW Login/Logout menu: by Juliobox – 1.3.3
BM Custom Login: by BinaryMoon – 2.0
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.5
Formidable: by Strategy11 – 2.02.02
Google Analyticator: by SumoMe – 6.4.9.7
Revolution Slider: by ThemePunch – 4.6.5
WooCommerce Custom Fields: by RightPress – 1.2.1
WooCommerce UPS Shipping: by WooThemes – 3.1.2 – 3.1.3 is available
WooCommerce: by WooThemes – 2.6.1
Yoast SEO: by Team Yoast – 3.3.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #33 - /shop/
Cart: #34 - /cart/
Checkout: #35 - /checkout/
My Account: #36 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: collector-frame
Version: 1.0.0
Author URL: http://underscores.me/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not Declared

### Templates ###

Overrides: collector-frame/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 2.6.1
collector-frame/woocommerce/content-single-product.php
collector-frame/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
collector-frame/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 2.5.0
collector-frame/woocommerce/single-product/meta.php
collector-frame/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 2.4.9
collector-frame/woocommerce/single-product/title.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/26-update-product-column-display-is-wrongwrong-number-of-products-shown?replies=1
