### ISSUE TITLE
Stock Qty display gets cut off while on Quick Edit on Safari 9.1.1/MacOS 10.11.5

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#11191]
## STEPS TO REPRODUCE THE ISSUE

Goto Dashboard >> Products and click `Quick Edit` for a product with Stock Quantity entered on Safari 9.1.1

![](http://cld.wthms.co/1e4G7/2xdALBZQ+)

Here is how it looks:

![](http://cld.wthms.co/H0C0/4suy08j5+)

zd-woothemes-430530

**Comment by mikejolley** [comment]
![2016-06-20 at 14 54](https://cloud.githubusercontent.com/assets/90977/16196717/ff8467b8-36f6-11e6-8e72-b98c13ec27e0.png)

Version 9.1.1 (11601.6.17)

WC 2.6

**Comment by spraveenitpro** [comment]
@mikejolley 

Myself and the customer are still getting this while on safari Version 9.1.1 (11601.6.17):

![](http://cld.wthms.co/1d3oC/2Rf1KfYC+)

**Comment by mikejolley** [comment]
@jameskoster can you confirm?

**Comment by jameskoster** [comment]
Seems to be a wp core issue; https://core.trac.wordpress.org/ticket/37024
