### ISSUE TITLE
Add hook for wrapper class (shortcode)

### ISSUE THREAD

**Issue by marcwieland95** [woothemes/woocommerce#11204]
Hi, there
I was trying to change the wrapper class called "woocommerce". It turned out that this is not easy to do.
It would be great if there's a hook to change this.

Something like this:
```
public static function shortcode_wrapper(
		$function,
		$atts    = array(),
		$wrapper = array(
			'class'  => apply_filters('woocommerce_shortcode_class', 'woocommerce'),
			'before' => null,
			'after'  => null
		)
	) {
```

**Comment by mikejolley** [comment]
Replied in PR

**Comment by metamn** [comment]
Sorry to ask, I don't really get "Replied in PR" I would also need a solution / workaround for this. Thank you!

**Comment by marcwieland95** [comment]
There's a discussion here, but no good solution to the problem. https://github.com/woocommerce/woocommerce/pull/11205

**Comment by metamn** [comment]
Oh thanks!!
