### ISSUE TITLE
Wootique theme homepage settings not updating

### ISSUE THREAD

**Issue by DBrenn06** [woothemes/woocommerce#11209]
I had a previous issue about the account registration not functioning properly, was told he is chalking it up to theme issue, so I tried a different theme (storefont theme with a child theme boutique). I had the same issue, so I decided to go back to wootique. When I got back my homepage was messed up and back to the default home page, but without the featured products slider showing or recent products. Just the Hello world blog. I went into the wootique setting, homepage settings made sure the homepage content wasn't selected (gets rid of hello world blog) and made sure the homepage featured products was set to slider, and the featured entries set to 12. I saved changes and nothing changed on my store's homepage, still have the hello world blog. I even tried refreshing, and saving again. I seem to not be having luck with anyone helping me. I would like resolution to this issue and the account registration issue.

**Comment by claudiosmweb** [comment]
This is not a question/issue about WooCommerce.
You should contact support.woothemes.com
