### ISSUE TITLE
Click event issue in admin order page

### ISSUE THREAD

**Issue by emehran** [woothemes/woocommerce#11203]
from ver 2.6 based on this commit 
https://github.com/woothemes/woocommerce/commit/f73149feaff892b4e02654c818c735d8f696ad82
on 
assets/js/admin/meta-boxes-order.js
line 235
`.on( 'click', 'tr.item :input, tr.fee :input, tr.shipping :input, tr.item a, tr.fee a, tr.shipping a', this.select_row_child )
`
This prevents having any click event handler for custom columns added with third-party extensions. For example, if I need to add a column with a link to Thickbox modal, this addition stops "click" and doesn't allow it.

It's because of using event.stopPropagation() for item a, item input, etc
Please check it

## STEPS TO REPRODUCE THE ISSUE

in Edit order page > metabox of items. If you try to add a custom column to the tables and bind an event to a link or input button, it's not possible anymore from version 2.6.

**Comment by mikejolley** [comment]
@emehran did you close this for a reason?

**Comment by emehran** [comment]
Actually, I made a wrong question. sorry. 
The issue comes when I want to add a custom column to edit order items table in admin panel with a link that has a "click" event. As the 2.6 has  
event.stopPropagation() for link and input inside .item "tr", Thickbox won't work anymore. I guess the use of 'body' selector for "click" event by Thickbox made it unusable here.

`jQuery( 'body' )
		.on( 'click', domChunk, tb_click )
		.on( 'thickbox:iframe:loaded', function() {
			jQuery( '#TB_window' ).removeClass( 'thickbox-loading' );
		});`
By the way, I think there should be a solution, and it's not a real issue.
