### ISSUE TITLE
Points Not Appearing in Cart

### ISSUE THREAD

**Issue by jamesdidit** [woothemes/woocommerce#11206]
## EXPLANATION OF THE ISSUE

Points redemption field not showing in shopping cart

## STEPS TO REPRODUCE THE ISSUE

1. Add a product to the cart
2. Go to view cart
3. Points aren't available

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://finisjhung.com
Site URL: http://finisjhung.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.19 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 33 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.48.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (37) ###

Gravity Forms: by rocketgenius – 1.9.19
WooCommerce Blacklister: by Aelia (Diego Zanella) – 0.8.6.150612
BackupBuddy: by iThemes – 5.1.1.8
Builder Block - Audio: by iThemes – 1.0.24
Spam Protection by CleanTalk: by СleanTalk  – 5.42
Gravity Forms Constant Contact Add-On: by Katz Web Services
Inc. – 2.2.1

Gravity Forms Placeholder Add-On: by Able Engine
William Wilkerson – 1.1.0

Groups 404 Redirect: by itthinx – 1.2.4
Groups WooCommerce: by itthinx – 1.9.5
Groups: by itthinx – 1.10.3
Builder Mobile Navigation: by iThemes – 1.0.2
iThemes Sync: by iThemes – 1.7.1
Jetpack by WordPress.com: by Automattic – 4.0.4
Huge IT lightbox: by Huge-IT – 1.6.3
Login Widget With Shortcode: by avimegladon – 5.4.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.1.0.1

Vimeography Pro: by Dave Kiss – 1.0.1
Vimeography: by Dave Kiss – 1.3.3
Aelia Foundation Classes for WooCommerce: by Aelia – 1.7.3.160531
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.0.18
WooCommerce Constant Contact: by WooThemes / SkyVerge – 1.7.0
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.1
Woocommerce Custom Tabs: by WebshopLogic – 1.0.18 PRO
WooCommerce - Store Exporter: by Visser Labs – 1.8.6
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.7.0
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Points and Rewards: by WooThemes – 1.5.9
WooCommerce Product Search: by itthinx – 1.4.3
SOD QuickBooks Connector for WooCommerce: by 61 Extensions – 1.3.18
WooCommerce Table Rate Shipping: by WooThemes – 3.0.1
WooCommerce: by WooThemes – 2.6.1
WooSlider: by WooThemes – 2.3.0
WooThemes Helper: by WooThemes – 1.6.2
WordPress Importer: by wordpressdotorg – 0.6.1
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
YITH WooCommerce Featured Video: by YITHEMES – 1.1.7

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My Account: #22 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Finis Jhung
Version: 5.0.10
Author URL: http://ithemes.com/
Child Theme: ✔
Parent Theme Name: Easton
Parent Theme Version: 5.0.12
Parent Theme Author URL: http://ithemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: Builder-Finis-Jhung/woocommerce/checkout/thankyou.php
Builder-Finis-Jhung/woocommerce/emails/customer-invoice.php
Builder-Finis-Jhung/woocommerce/loop/sale-flash.php
Builder-Finis-Jhung/woocommerce/single-product/add-to-cart/external.php
Builder-Finis-Jhung/woocommerce/single-product/add-to-cart/grouped.php
Builder-Finis-Jhung/woocommerce/single-product/add-to-cart/simple.php
Builder-Finis-Jhung/woocommerce/single-product/meta.php
Builder-Finis-Jhung/woocommerce/single-product/product-attributes.php
Builder-Finis-Jhung/woocommerce/single-product/product-image.php
Builder-Finis-Jhung/woocommerce/single-product/related.php
Builder-Finis-Jhung/woocommerce/single-product/sale-flash.php
Builder-Finis-Jhung/woocommerce/single-product/share.php
Builder-Finis-Jhung/woocommerce/single-product/short-description.php
Builder-Finis-Jhung/woocommerce/single-product/title.php
Builder-Finis-Jhung/woocommerce/single-product/up-sells.php
Builder-Finis-Jhung/woocommerce/single-product.php

### Authorize.net AIM ###

Environment: Production
`

**Comment by mikejolley** [comment]
You're not on the latest release, and this is not the place for support.

Changelog: http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-points-and-rewards/changelog.txt

If you need help after updating, go to support.woothemes.com
