### ISSUE TITLE
Netherlands Antilles is no longer a country

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11217]
From a customer:

> Just upgraded to WooCommerce 2.6. and I would like to select Curacao as the local zone. However, that is not an option, only Netherlands Antilles which Curacao was a part of but since 2010 does not exist anymore. The 5 islands that made up the Netherlands Antilles, Curacao, Bonaire, St. Maarten, Saba and St. Eustatius are now “Curacao” as a separate entity, “St. Maarten” a separate entity, and Bonaire, Saba and St. Eustatius as "Caribbean Netherlands".

In Shipping Zones, we only offer Netherlands Antilles: http://cld.wthms.co/1i9zS/3LMJsWMj.

From wikipedia: https://en.wikipedia.org/wiki/Netherlands_Antilles

**Comment by mikejolley** [comment]
Updating from https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by WPprodigy** [comment]
Will we be adding in the new countries, like Curacao?

**Comment by mikejolley** [comment]
It's there

**Comment by claudiosmweb** [comment]
@mikejolley not there and need to fix the continents too :P
