### ISSUE TITLE
Token script contains code for checking the "create account" checkbox but only loads if the user is logged in

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#11214]
woocommerce/assets/js/frontend/tokenization-form.js contains these lines

```
				// OR if create account is checked
				$ ( 'input#createaccount' ).change( this.onCreateAccountChange );
```
(https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/tokenization-form.js#L61-L62)

which would show the save token checkbox if the Create Account check box is checked BUT the script is only loaded if the customer is logged in

```
	public function payment_fields() {
		if ( $this->supports( 'tokenization' ) && is_checkout() && is_user_logged_in() ) {
			$this->tokenization_script();
			$this->saved_payment_methods();
			$this->form();
			$this->save_payment_method_checkbox();
		} else {
			$this->form();
		}
	}
```
(https://github.com/woothemes/woocommerce/blob/master/includes/gateways/class-wc-payment-gateway-cc.php#L21)

**Comment by ChromeOrange** [comment]
@mikejolley any reason we can't just simply remove

```
&& is_user_logged_in()
```

?? It seems redundant, especially as you'd want to allow new customers who are creating an account to also save a card IMO.

**Comment by ChromeOrange** [comment]
removed it in the PR (https://github.com/woothemes/woocommerce/pull/11219)

**Comment by mikejolley** [comment]
Will review #11219 thanks.
