### ISSUE TITLE
WooCommerce folder name alert

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#11215]
If someone changes the folder name from `woocommerce` to something else it causes issues with various plugins, some not being active, some being active but not working like expected without throwing a message.

Can we add a check in the core that reads the folder of itself and shows an error message if it's not exactly `woocommerce`?

That would be helpful for us in support to quickly understand what is the issue even without having FTP creds, and also for customers to fix everything by themselves.

**Comment by ChromeOrange** [comment]
as a temporary measure you can check the plugin editor (assuming it's available)

![](https://dl.dropboxusercontent.com/s/f13v9u1vs3p5lhk/2016-06-22%20at%2008.32.png?dl=0)

**Comment by mikejolley** [comment]
You can also view page source. As it's been bought up before, I'd rather see our updated ignore base that add extra report data :) View source for now.
