### ISSUE TITLE
WC_Meta_Box_Order_Reviews class doesn't exist but is being used in 'comment_edit_redirect' hook.

### ISSUE THREAD

**Issue by wpexplorer** [woothemes/woocommerce#11210]
In the file located at woocommerce/includes/admin/class-wc-admin-meta-boxes.php there is an action hook referencing a class that doesn't exist:

`add_action( 'comment_edit_redirect', 'WC_Meta_Box_Order_Reviews::save', 1, 2 );`

The WC_Meta_Box_Order_Reviews doesn't appear to be anywhere in the plugin so this action will generate an error:

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Meta_Box_Order_Reviews' not found...

**Comment by BurlesonBrad** [comment]
Not that I'm the rocket ninja genius full stack coding scientist that (tagging-->) @claudiosmweb is, but that was left from a version or two back, right?

Once upon a time, in a village far far away, there was 
`woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-reviews.php`
But that was some time ago (v 2.4.?), right?



_....or I'm loopy, should stay off of Github, go back to TeamTreeHouse, and stop pretending that I can make Windows 10 load VVV_
