### ISSUE TITLE
legacy API v3 OAuth Signature is wrong

### ISSUE THREAD

**Issue by machajdik** [woothemes/woocommerce#11224]
## EXPLANATION OF THE ISSUE

The OAuth Signature in (legacy) API v3 is wrong.

## STEPS TO REPRODUCE THE ISSUE

Call v3 API.

Problem: in /api/legacy/v3/class-wc-api-authentication.php, a '&' (ampersand) is concatenated to the consumer secret before the signature is calculated.

$secret = $keys['consumer_secret'] . '&';

This was not the case in v1 and v2. Without the '&', the OAuth signature is correct.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://localhost:8093
Site URL: http://localhost:8093
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
PHP Version: 5.6.21
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.47.1
OpenSSL/1.0.2d

SUHOSIN Installed: –
MySQL Version: 5.7.12
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (1) ###

WooCommerce: von WooThemes – 2.6.1

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /cart/
Kasse: #6 - /checkout/
Mein Konto: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Fourteen
Version: 1.4 – 1.7 ist verfügbar
Author URL: https://wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
PLEASE read the documentation before open an issue!
This is `ampersand` is required by the Oauth 1.0a specs and wrong implemented in v1/v2 and finally we fixed in v3. We talk about it in the docs.
