### ISSUE TITLE
legacy API v3 OAuth Signature is wrong for filter[] parameters

### ISSUE THREAD

**Issue by machajdik** [woothemes/woocommerce#11223]
## EXPLANATION OF THE ISSUE

In (legacy) API v3, the oauth signature get calculated wrong (and therefore an auth error occurres) when using array-style parameters (e.g. filter[]):

## STEPS TO REPRODUCE THE ISSUE

Authenticate against API v3 with a filter[] parameter, e.g.:

GET&http://localhost:8093/wc-api/v3/orders&filter%5Bcreated_at_min%5D=2015-12-22&filter%5Blimit%5D=999&filter%5Bupdated_at_min%5D=2016-06-20&oauth_consumer_key=xxx&oauth_nonce=123&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1466609462&page=1&status=on-hold%2Cprocessing

Note the filter parameter. It is an array:
filter[limit]=999
filter[created_at_min]=2015-12-22
filter[updated_at_min]=2016-06-20

Note that the parameters are not in alphabetical order! And that's the problem. In /includes/api/legacy/v3/class-wc-api-authentication.php "uksort" gets called. But uksort does not care about the parameters in the array.

Compare /includes/api/legacy/v2/class-wc-api-authentication.php: there, normalize_parameters() gets called before uksort. And that works, becaues it sorts correctly.

## SYSTEM STATUS REPORT

GET&http://localhost:8093/wc-api/v2/orders&filter%5Bcreated_at_min%5D=2015-12-22&filter%5Blimit%5D=999&filter%5Bupdated_at_min%5D=2016-06-20&oauth_consumer_key=ck_0941795811c0d367bcd4f19b8e7d8d9a8cedd1a4&oauth_nonce=14666094625391100111645610413317&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1466609462&page=1&status=on-hold%2Cprocessing

**Comment by claudiosmweb** [comment]
Please read the docs before you open an issue: http://woothemes.github.io/woocommerce-rest-api-docs/v3.html

![screenshot from 2016-06-22 12-56-36](https://cloud.githubusercontent.com/assets/1264099/16273648/c771a5ec-3878-11e6-9e94-8aa62a8c745d.png)

>Note the filter parameter. It is an array:
>filter[limit]=999
>filter[created_at_min]=2015-12-22
>filter[updated_at_min]=2016-06-20

This does not seem to me that was ordered alphabetically...

**Comment by machajdik** [comment]
Ok, I see. But it works in v1 and v2, that's confusing :-)
