### ISSUE TITLE
Products grouped when reaching PayPal if taxes are enabled

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#11221]
Products aren't displayed in the same way on PayPal standard payment page when taxes are enabled.

When this option is disabled:

![](http://cld.wthms.co/1cm5k/3XmhVCJy+)

During checkout, when reaching PayPal Standard page we get this:

![](http://cld.wthms.co/16ZC3/2kjNpsKA+)

but when the option is enabled:

![](http://cld.wthms.co/1bEYN/1v2EXvG5+)

Products are grouped:

![](http://cld.wthms.co/xCwa/2lD8tkSA+)

Is that intended?

**Comment by roykho** [comment]
Yes that is intended because when taxes are enabled, it is common to have small penny discrepancies during the calculation between WC and PayPal so in order to circumvent this, we had to total it up before sending it.
