### ISSUE TITLE
Extra zip code information normalized in shipping zones

### ISSUE THREAD

**Issue by hannahswain** [woothemes/woocommerce#11220]
Zip code range defined in shipping zone: 78600...78799

When a zip code such as 78575-2375 is entered at checkout, wc_normalize_postcode converts it to 787572375. It is then compared with the 78600...78799 range, which which it fails. 

Possible solution: make the postal code check more explicit, especially for zones with extra `-0000` or consider the range without extra 4 digits.

433783-zd-woothemes

**Comment by mikejolley** [comment]
WC does not support 9 digital postcodes when it comes to tax and shipping zone range matching. It is correct to remove the hyphen though.

> Possible solution: make the postal code check more explicit, especially for zones with extra -0000 or consider the range without extra 4 digits

Don't add the extra 4 digits in rules.
