### ISSUE TITLE
Get Downloadable Products Fatal Error

### ISSUE THREAD

**Issue by renatonascalves** [woothemes/woocommerce#11227]
After the recent WooCommerce update, I'm facing this error:

[23-Jun-2016 00:16:29 UTC] PHP Fatal error:  Call to a member function get_downloadable_products() on a non-object in path/to/site\wp-content\plugins\woocommerce\includes\wc-account-functions.php on line 90

Front-end: No action, if WP_Debug is on, this error appears.
Back-end (WP Panel): HTTP ERROR 404
![screenshot_1](https://cloud.githubusercontent.com/assets/19148962/16288122/287fcae4-38bf-11e6-81ab-7dc0d3557e50.png)

Still investigating the reason of this problem and a fix.

**Comment by mikejolley** [comment]
Sounds like something is calling wc_get_account_menu_items() too early. Added workaround but you should look into it.

**Comment by renatonascalves** [comment]
Indeed I was, but even after I Removed the code that was interacting with wc_get_account_menu_items(), the error kept happening in WP painel.
