### ISSUE TITLE
[API] Incorrect timezone on response

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11228]
Using both latest WP and WC. WP timezone is set to UTC - 5 (Chicago). When I create a new order using API, the created date in the response is UTC time (5 hours ahead). Is this default behavior or a bug? 

Due to this my app shows orders placed in the future.

**Comment by mikejolley** [comment]
> Dates are returned in RFC3339 format in UTC timezone: YYYY-MM-DDTHH:MM:SSZ

https://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by amjad0** [comment]
@mikejolley Does this mean I need to have a setting in my app to set local timezone and then convert the dates retrieved from server to local timezone?

**Comment by mikejolley** [comment]
Yes. UTC is a standard.

**Comment by vincent-shippo** [comment]
@mikejolley 
It says here in order properties:
[http://woocommerce.github.io/woocommerce-rest-api-docs/?python#order-properties](http://woocommerce.github.io/woocommerce-rest-api-docs/?python#order-properties)
that the 'date_created' attribute is 'The date the order was created, in the site’s timezone.' 

I believe in previous versions, it was UTC. Can you confirm which one it is: UTC or local timezone?
