### ISSUE TITLE
Canada Post shipping plugin

### ISSUE THREAD

**Issue by Bokashiliving** [woothemes/woocommerce#11239]
Since the recent Woocommerce update (version 2.6.1) shipping costs are no longer added to the total in my Woocommerce shop. All shipping on our shop is calculated through the Canada Post plugin only (no flat rate, local pickup etc offered). You can see the calculated shipping rate but this is not added to the total and when you click on 'proceed to paypal' the following error message is given:

![image](https://cloud.githubusercontent.com/assets/20117583/16321698/3f28b0a0-3953-11e6-808d-4965ef2f2651.png)

The customer cannot proceed any further and cannot complete the order.

I am using the Moesia theme.

Please advise ASAP. Thanks
Nicki

**Comment by claudiosmweb** [comment]
Seems to be an issue with "Canada Post plugin" and not in WooCommerce.
Check with the author of "Canada Post plugin"

**Comment by Bokashiliving** [comment]
Thanks for the quick response! I asked the same to the canada post support so fingers crossed there is a simple solution!

Sent from my iPhone

On Jun 23, 2016, at 3:46 PM, "Claudio Sanches" <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems to be an issue with "Canada Post plugin" and not in WooCommerce.
Check with the author of "Canada Post plugin"

-
