### ISSUE TITLE
[API] Override product name?

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11231]
So there is a way to override the price of an item when creating the order which is great when selecting custom items. But I want to know if theres a way to change the name of the product as well for that particular order? I know its read only in the api docs, but is there a way to do this otherwise?

Eg: Custom Item - $2.99 and this product does not exist in the products but is just a temporary item name for those rare usually one time purchases that don't need a separate product created.

**Comment by mikejolley** [comment]
Why are you asking questions here? This is not a support forum. Please use github for bug reports only. Forum for everything else.
