### ISSUE TITLE
Issue in My Account Menu

### ISSUE THREAD

**Issue by jake2townz** [woothemes/woocommerce#11233]
## EXPLANATION OF THE ISSUE

I noticed that when browsing a second-level page and then clicking on the Account menu, the standard menu items (e.g. Dashboard, Orders, Downloads, Addresses, etc.) do not point to the correct URIs since they are linked relative to the currently viewed page.

## STEPS TO REPRODUCE THE ISSUE

For example:
I am currently browsing https://kevloproducts.com/support/contact/

If I click the Orders in the My Account menu in the navbar, it points to:
https://kevloproducts.com/support/contact/orders/
instead of https://kevloproducts.com/account/orders/

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: https://kevloproducts.com
Site URL: https://kevloproducts.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.32 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 48 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.50 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 48 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (20) ###

Gravity Forms: by rocketgenius – 2.0.1
Akismet: by Automattic – 3.1.11
Better WooCommerce Stars Shortcode: by ClickNathan – 1.0
Configure SMTP: by Scott Reilly – 3.1
Easy Table: by Takien – 1.6
Envato WordPress Toolkit: by Envato – 1.7.3
Font Awesome 4 Menus: by New Nine Media – 4.6.1.0
LocalCurrency: by Stephen Cronin – 2.9
Materializer: by Cody Reichert – 0.2.0
Nextend Facebook Connect: by Roland Soos – 1.5.9
Quick Flag: by Marko Martinović – 2.11
Really Simple SSL: by Rogier Lankhorst – 2.3.9
Theia Post Slider: by WeCodePixels – 1.9.7
Booster for WooCommerce: by Algoritmika Ltd – 2.5.2
WooCommerce: by WooThemes – 2.6.1
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 3.3.2
Yoast SEO: WooCommerce: by Team Yoast – 3.3
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16
Zopim Widget: by Zopim – 1.4.3

### Settings ###

Force SSL: ✔
Currency: PHP (₱)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #762 - /products/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My Account: #37 - /account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child Theme
Version: 1.8
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.9.5.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome-child/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome-child/woocommerce/myaccount/my-downloads.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by claudiosmweb** [comment]
Not seems to be an issue with WooCommerce.

See the generated HTML for it:

```html
<nav class="woocommerce-MyAccount-navigation">
	<ul>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--dashboard is-active">
				<a href="http://woo.dev/my-account/">Dashboard</a>
			</li>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--orders">
				<a href="http://woo.dev/my-account/orders/">Orders</a>
			</li>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--downloads">
				<a href="http://woo.dev/my-account/downloads/">Downloads</a>
			</li>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--edit-address">
				<a href="http://woo.dev/my-account/edit-address/">Addresses</a>
			</li>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--edit-account">
				<a href="http://woo.dev/my-account/edit-account/">Account Details</a>
			</li>
					<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--customer-logout">
				<a href="http://woo.dev/my-account/customer-logout/">Logout</a>
			</li>
			</ul>
</nav>
```

This looks like some change in your theme or site.
