### ISSUE TITLE
WooCommerce 2.6.1 - Category Images Gone

### ISSUE THREAD

**Issue by BikiniFlirt** [woothemes/woocommerce#11238]
Hi, I upgraded my site to WooCommerce 2.6.1 and now the category images won't show up: http://www.coastalartisan.com/product-category/art/stones/

I have WordPress 4.5.3 running StyleShop theme.

I deactivated the theme, tried 2012 instead, deactivated all other plug-ins but the problem remained.

Is anyone else having this issue?

Thank you!

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
Need to run the "updater".
