### ISSUE TITLE
wc_get_loop_class() hookable

### ISSUE THREAD

**Issue by Anydog** [woothemes/woocommerce#11230]
## EXPLANATION OF THE ISSUE

Not an issue, a request : please make wc_get_loop_class() hookable so we can change it with actions and/or filters (main problem was the "first" / "last" classes and clearing columns)

## SYSTEM STATUS REPORT

```
WC Version 2.6 +
```

Thank You.

**Comment by mikejolley** [comment]
wc_get_loop_class is simply using post_class() which you also have access to. Use the standard WP hooks.

**Comment by Anydog** [comment]
Hi,
thanks for fast reply. I am using post_class() hook, already, but it would be nice to have possibility to make changes in 
```
if ( 0 === ( $woocommerce_loop['loop'] - 1 ) % $woocommerce_loop['columns'] || 1 === $woocommerce_loop['columns'] ) {
		return 'first';
	} elseif ( 0 === $woocommerce_loop['loop'] % $woocommerce_loop['columns'] ) {
		return 'last';
	} else {
		return '';
	}
```
Just a small suggestion. Thanks anyway.

**Comment by mikejolley** [comment]
You can via the hook I mentioned. Since you can remove classes and add your own logic based on the above.

**Comment by Anydog** [comment]
Ok, thanks for such a fast replies. :)
