### ISSUE TITLE
Only 2 columns showing in shop

### ISSUE THREAD

**Issue by Bokashiliving** [woothemes/woocommerce#11241]
My online shop is only showing 2 columns of products. Before the recent update it was showing 4 columns. I can't find any options to change this in the plugin. I have tried a couple of suggestions for adding CSS and a suggested plugin (from googling the problem) but neither of these have solved the problem.

I am using the Moesia theme and here is a link to my shop www.bokashiliving.com/shop
Thanks in advance

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/26-update-product-column-display-is-wrongwrong-number-of-products-shown?replies=1
