### ISSUE TITLE
WooCommerce for large variations

### ISSUE THREAD

**Issue by hiddenpearls** [woothemes/woocommerce#11243]
I have 4k Product Variations in total and When I try to load all Products page at wp-admin backend. It takes forever and throws me Memory Exhausted and Maximum execution errors. What is the best way to handle such a case when you have thousands of variations. I know each Variation is a Post.  but why It is being called on all products page load ?

Product variation should be called only when you switch to Variations tab and there should be limit as well. It sucks really.

**Comment by mikejolley** [comment]
Since some of the parent props are based on the children, this is why they are loaded. Most data is however cached to transients. If you're using 50+ variations per product, I'd seriously reconsider what you're doing.

**Comment by mikejolley** [comment]
No need to spam multiple places https://wordpress.org/support/topic/woocommerce-for-large-variations?replies=1
