### ISSUE TITLE
Sorry, you cannot list resources over HTTPS

### ISSUE THREAD

**Issue by briantheitguy** [woothemes/woocommerce#11246]
## EXPLANATION OF THE ISSUE

After reading the docs and trying Basic Auth & Querystring Auth on HTTPS, I get "Sorry, you cannot list resources."

## STEPS TO REPRODUCE THE ISSUE

In Postman, I run a GET with my URL 
https://myprojectsolution.net/wsp_woo/wp-json/wc/v1/orders
Headers: Auth = Basic and User = Consumer Key, Pwd = Consumer Secret
I also tried with no headers and user query string "?consumer_key=...&consumer_secret=...

{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://myprojectsolution.net/wsp_woo
Site URL: http://myprojectsolution.net/wsp_woo
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.48 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #8 - /index.php/shop/
Cart: #9 - /index.php/cart/
Checkout: #10 - /index.php/checkout/
My Account: #11 - /index.php/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Yes you can, read the docs before open issues: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

**Comment by briantheitguy** [comment]
Seriously? Even if it is painfully obvious to you, take the extra minute and tell me the issue.
Better yet, provide better docs that list the codes that could be returned and steps to resolve.

**Comment by claudiosmweb** [comment]
@briantheitguy yes, seriously, this is an issue with your keys or your environment.
Have you checked your server? Are it blocked by ModSecurity? CloudFlare?

**Comment by claudiosmweb** [comment]
@briantheitguy "docs that list the codes that could be returned and steps to resolve" no need, will be always 401, since is missing the authentication.

**Comment by mikejolley** [comment]
@briantheitguy please use the forums for support. We don't want our issue (bug) tracker clogged up with questions like this ideally.

**Comment by briantheitguy** [comment]
I generated a second set of keys... same response.
Check the server? We are using Host Gator shared server... can't do anything to the server.
We've made no changes to ModSecurity.
We are not using cloudflare.
I've made no purchases so I can't submit a ticket to the forums.
What else can I check?

**Comment by claudiosmweb** [comment]
@briantheitguy contact the Hostgator support to checkout the ModSecurity and the access log, so then can check if the query strings are stripped.
And better use the wp.org support forum, since here is not a place for support.

**Comment by briantheitguy** [comment]
Ok, thanks.

**Comment by RoohBear** [comment]
Hi Brian, did you ever solve this?  I"m getting the same problem

**Comment by briantheitguy** [comment]
Sorry @RoohBear, I'm not completely sure what this ended up being, but I'm pretty sure it was because my OAuth headers were not properly formatted. That is all I can think of. :/ It took me a little too to get them formatted and hashed just right.

**Comment by Webnizam** [comment]
Hi @briantheitguy did u solved the issue ?
Can you share with us if you fixed it.
I'm in the same situation, getting same error since a week. 
Installed 0Auth1 plugin as mentioned by some user in this forum, still error exists.

**Comment by lmatab** [comment]
Hello @briantheitguy  I am having the same problem, I have tried to follow the steps in the docs with no luck so far!, could you share your steps to get it work?, thanks ahead.

**Comment by lmatab** [comment]
For anyone  having similar problems, I finally had access using 0auth 1, I followed this link:
http://nobil.cc/blog/oauth-in-wp-rest-api/

**Comment by grillendor** [comment]
I'm having the same problem here, I get the error {"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}
even in Postman, been trying Basic authentication and the previous OAUTH 1.0 that I was using.  Can't for the life of me figure out what is wrong here.

**Comment by davidvexel** [comment]
I had this problem when switching from `http` to `https` and just added `queryStringAuth: true` below my CK and CS.

**Comment by briantheitguy** [comment]
Again, those of you getting a 401, the issue came down to me getting the base string & hash EXACTLY right based on the requirements (the order of the params and everything)... (Attached are the classes I ended up using; Some classes referenced are not included as they proprietary, but the props referenced should be clear as to what is needed.)
[ApplyOAuthAuthentication.zip](https://github.com/woocommerce/woocommerce/files/910081/ApplyOAuthAuthentication.zip)

**Comment by rickbeacham** [comment]
OAuth is not working for me either.  I have to add the cs and ck in the url as parameters.  I can't get CURL to work either using this method so what is the problem?

**Comment by U1timatePeter** [comment]
Trying to help others:
I was struggling with the 401 response while trying to CURL, and also with VBA trying to request as content-type "application/json"
However, I was able to pull a valid response by just entering this in my browser address bar:
https://mywebsite.com/wp-json/wc/v2/products?consumer_key=ck_blahblah&consumer_secret=cs_blahblah

Following this line of thought, I went back to my VBA app and changed the content type to "application/text" and was able to pull a valid response text with response code 200. 
Hope this helps someone.

**Comment by JoelSParker** [comment]
Verify that the user you have assigned the API key to is an admin. They must be an admin to use the the API.
