### ISSUE TITLE
Bug: Shipping method is not getting enable on checkout page on change of country dropdown box.

### ISSUE THREAD

**Issue by jacksperrow1988** [woothemes/woocommerce#11247]
@mikejolley , @claudiosan 

Hello Team.

I have an issue regarding shipping method is not enable when we change country and states from dropdown on chekout page.

i have created video for reproduce case please see the video and let us know your feedback..

Please see below video URL: 

http://www.screencast.com/t/5l5bZ3QD2ff

Thanks

**Comment by mikejolley** [comment]
It updates when the full address is input.
