### ISSUE TITLE
Missing filter while loading persistent cart

### ISSUE THREAD

**Issue by mrdonthave** [woothemes/woocommerce#11256]
Hi!

at "class-wc-cart.php" in the method "public function get_cart_from_session()" WC loads the persistent cart from user meta if user is logged in, the cart is empty and the user has a stored cart at his user meta:

`if ( is_null( $cart ) && ( $saved_cart = get_user_meta( get_current_user_id(), '_woocommerce_persistent_cart', true ) ) ) {...}`

for some more flexibility in handling multiple persistent carts it would be make sense, there would be a filter like:

`$saved_cart = apply_filters ( 'woocommerce_load_persistent_cart_from_user_meta', get_user_meta ( get_current_user_id (), '_woocommerce_persistent_cart', true ) );`

i think additional args are not necessary.

Maybe even more better would be control about forcing restoring the cart session also if the cart session is already filled. So the filter could be below:

```
if ( is_null( $cart ) && ( $saved_cart = get_user_meta( get_current_user_id(), '_woocommerce_persistent_cart', true ) ) ) {
	$cart                = $saved_cart['cart'];
	$update_cart_session = true;
} elseif ( is_null( $cart ) ) {
	$cart = array();
}

$cart = apply_filters ( 'woocommerce_load_persistent_cart_from_user_meta', $cart );
```

`do_action( 'woocommerce_cart_loaded_from_session', $this );` later comes too late after the checks WC does above.

would be very cool! :-)

Christian

**Comment by mikejolley** [comment]
Multiple carts could make use of:

https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/meta.php#L486


I don't think we need yet another wrapper here - you can use the WP hooks.
