### ISSUE TITLE
Notice: Your theme version of my-account.php template is deprecated since version 2.6! Use the latest version, which supports multiple account pages and navigation, from WC 2.6.0 instead. in /home/themename/public_html/wp-includes/functions.php on line 3658

### ISSUE THREAD

**Issue by arulmoto** [woothemes/woocommerce#11251]
## Database
WC Database Version:		2.6.1
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /home/mytheme/public_html/wp-content/uploads/GeoIP.dat

My issue is like am getting notice on my account page as below after the woocommerce got its new update.

the notice is like 
Notice: Your theme version of my-account.php template is deprecated since version 2.6! Use the latest version, which supports multiple account pages and navigation, from WC 2.6.0 instead. in /home/mytheme/public_html/wp-includes/functions.php on line 3658

Please help me to remove this message from my account page. Thanks

**Comment by mikejolley** [comment]
Turn off WP_DEBUG/error reporting or update your theme as instructed.
