### ISSUE TITLE
"Customer matched zone" is missing translation

### ISSUE THREAD

**Issue by mrweix** [woothemes/woocommerce#11268]
## EXPLANATION OF THE ISSUE

The WC Notice 'Customer matched zone "Rest of the World"' is not translatable at the moment.

Instead of 

`wc_add_notice( 'Customer matched zone "' . $shipping_zone->get_zone_name() . '"' );`

it should be something like:

`wc_add_notice( __( 'Customer matched zone', 'woocommerce' ).' "' . $shipping_zone->get_zone_name() . '"' );`

## STEPS TO REPRODUCE THE ISSUE

Have a non english Woocommerce set up and add any product to cart and choose a country

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.eticketablanca.com
Site URL: https://www.eticketablanca.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_CO

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (27) ###

Akismet: by Automattic – 3.1.11
Co-Authors Plus: by Mohammad Jangda
Daniel Bachhuber
Automattic – 3.2.1

CodeStyling Localization: by Heiko Rabe – 1.99.30
Custom Post Type UI: by WebDevStudios – 1.3.5
Members: by Justin Tadlock – 1.1.2
No CAPTCHA reCAPTCHA for WooCommerce KW Tweak: by Agbonghama Collins
Tweak by Konstantin Weixelbaum – 1.1

OpenTickets Community Edition: by Quadshot Software LLC – 2.3.0
Post Thumbnail Editor: by sewpafly – 2.4.8
Quadshot OT Debugger: by Loushou – 0.1.3
OpenTickets - Box Office: by Quadshot Software LLC – 2.0.3
OpenTickets - Coupons & Passes: by Quadshot Software LLC – 2.0.1
OpenTickets - Display Options: by Quadshot Software LLC – 2.0.3
OpenTickets - General Admission Multiple Pricing (GAMP): by Quadshot Software LLC – 2.1.0
OpenTickets - Seating: by Quadshot Software LLC – 2.1.5
Simple Fields: by Pär Thernström – 1.4.11
Simple History: by Pär Thernström – 2.7.3
User Role Editor: by Vladimir Garagulya – 4.25.2
Widgets on Pages: by Todd Halfpenny – 0.0.12
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.11
WooCommerce Extra Fee Option KW: by Konstantin Weixelbaum Terry Tsang – 1.0.7
Reminder for WooCommerce Unpaid Orders: by MB Création – 2.7.1
WooCommerce - PayU Latam Gateway: by Code is in the Air - Jairo Ivan Rondon Mejia – 1.1.9
WooCommerce Promotion Manager: by IndoWebKreasi – 1.2.2
Plugin de Integración WooCommerce - TuCompra: by TuCompra S.A.S. – 1.0
WooCommerce: by WooThemes – 2.6.1
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7

### Settings ###

Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page ID is set
but the page does not exist

Cart: #20 - /cart/
Checkout: #21 - /checkout/
My Account: #22 - /cuenta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Fourteen Child
Version: 1.0.0
Author URL: http://example.com
Child Theme: ✔
Parent Theme Name: Twenty Fourteen
Parent Theme Version: 1.7
Parent Theme Author URL: https://es-co.wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentyfourteen-child/woocommerce/cart/cart-empty.php
twentyfourteen-child/woocommerce/cart/cart-shipping.php
twentyfourteen-child/woocommerce/cart/cart-totals.php
twentyfourteen-child/woocommerce/cart/cart.php
twentyfourteen-child/woocommerce/checkout/form-checkout.php
twentyfourteen-child/woocommerce/checkout/form-login.php
twentyfourteen-child/woocommerce/checkout/form-shipping.php
twentyfourteen-child/woocommerce/checkout/payment-method.php
twentyfourteen-child/woocommerce/checkout/payment.php
twentyfourteen-child/woocommerce/checkout/review-order.php
twentyfourteen-child/woocommerce/checkout/thankyou.php
twentyfourteen-child/woocommerce/emails/customer-completed-order.php
twentyfourteen-child/woocommerce/emails/customer-processing-order.php
twentyfourteen-child/woocommerce/emails/email-order-details.php
twentyfourteen-child/woocommerce/myaccount/form-lost-password.php
twentyfourteen-child/woocommerce/myaccount/my-account.php
twentyfourteen-child/woocommerce/notices/error.php
twentyfourteen-child/woocommerce/order/order-details-customer.php

`

**Comment by mikejolley** [comment]
This is for debugging only. Like error logs, this is english so it's easier to support :)
