### ISSUE TITLE
Apply coupon and update cart

### ISSUE THREAD

**Issue by vdberggert** [woothemes/woocommerce#11267]
hi,
When I try to add a coupon, it all show up coorectly, but when I click apply coupon nothing happens. Also when I ammend the qty, it show me a not allowed icon. For free shipping, it makes me choose the option between my other flat rate options and free shipping, this might be confusing to my customer?

Website is www.goldengown.co.nz

Thanks.

**Comment by mikejolley** [comment]
Please check for theme updates from the author. it has some cart page customisations which is breaking ajax click events.

**Comment by vdberggert** [comment]
Hi there,

My theme is on the latest version. This issue started with the latest 
woo commerce update very recently.

Thanks.
