### ISSUE TITLE
Show price near each variation in the Dropdown box.

### ISSUE THREAD

**Issue by panbill** [woothemes/woocommerce#11266]
Hello,
Is there a way to show the price near each variation in the dropdown box? 
I think that is very useful especially if the store has a lot of variations.
I think its better for the customer to see the prices and not to have to click on each varation to see the price.
Thanks

**Comment by mikejolley** [comment]
This won't work for all cases. Variations are a sum of all attributes. Each separate attribute has no baring on price. Use product addons if thats the setup you want.

**Comment by panbill** [comment]
![dropdown_variable_price](https://cloud.githubusercontent.com/assets/12981097/16414417/2a15228e-3d40-11e6-90a8-7b54a93c84f1.JPG)

I am not looking for something like product addons. I just found out that when i enable the Twenty Fifteen (screenshot) the prices are there as i want it. So how can i do the same without the span fort the current theme that i use?
THanks

**Comment by lawkwok** [comment]
You aren't able to style options using CSS unfortunately – you would need to create a custom dropdown for that.

The beauty is that WooCommerce outputs an array of variation information right on the product page which you can read using JS. Here's a gist I created for displaying stock status, which you can modify to display prices. https://gist.github.com/lawkwok/d2480679fa3a1b79618dae9e376e1930

Just add the script to your content-single-product.php template.

**Comment by MattyLB** [comment]
Just to chime in, I believe this should be up to the theme developer as a configurable option - not all of us want the long strings it creates (especially in mobile screens).

Thanks for the code, btw, @lawkwok !
