### ISSUE TITLE
[REST API] "woocommerce_rest_invalid_product_id" returned for Variation IDs

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#11263]
## EXPLANATION OF THE ISSUE

Prior to the WC 2.6 API, I was able to access variations using the ID. However, now I get the following error: 

` {"code":"woocommerce_rest_invalid_product_id","message":"Invalid id.","data":{"status":404}}
`
## STEPS TO REPRODUCE THE ISSUE

Try accessing a product by id. JSON data is returned when using a parent id, but not a variation id.
 
This works: https://www.domain.com/wp-json/wc/v1/products/*product_id*/
This does not: https://www.domain.com/wp-json/wc/v1/products/*variation_id*/

**Comment by claudiosmweb** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/11534cf4573b7ead0a3964888253d726e581cf84
