### ISSUE TITLE
Checkout update remove shipping_methods from shipping object. 

### ISSUE THREAD

**Issue by Musilda** [woothemes/woocommerce#11260]
When checkout is updated, WC()->shipping->shipping_methods is undefined. This happening, only, when shipping debug is inactive. 

When shipping debug is active, WC()->shipping->shipping_methods isnt empty. 

This is, what happens, when checkout is updated:

`O:11:"WC_Shipping":6:{s:7:"enabled";b:1;s:16:"shipping_methods";N;s:14:"shipping_total";i:0;s:14:"shipping_taxes";a:0:{}s:16:"shipping_classes";a:0:{}s:8:"packages`

**Comment by mikejolley** [comment]
This issue report lacks a) what is breaking b) how to reproduce c) system status report.

AFAIK there is no bug here because once it's calculated the package rates, they get cached.  If there were a bug, no shipping methods/rates would be showing on checkout. They are.

**Comment by Musilda** [comment]
Thank you 

Now i understand, why shipping_methods missing. Sorry for my lack report. 
Thank you for your help.
