### ISSUE TITLE
General Section is Empty for Variable Products

### ISSUE THREAD

**Issue by seb86** [woothemes/woocommerce#11262]
Since version 2.6 the general section of the product data for variable products now appears empty.

I'm wondering if this should be hidden based on the condition that the general section is not used or needed.

What do you all think?

![Variable Product with the General Section empty](https://cldup.com/CzGxsEoL1f.png)

**Comment by claudiosmweb** [comment]
No needed at least now for core, but we had this before for the SKU field... Since we moved to the Inventory tab, we don't need anymore. But 3rd party plugins may still be using this tab, if we remove will broke this kind integrations... I think we should remove it, but maybe hold until 2.7.

**Comment by mikejolley** [comment]
Taxes disabled @seb86?

**Comment by mikejolley** [comment]
Closed in favour of #11271

**Comment by seb86** [comment]
@mikejolley Yes. Taxes were disabled as this was found from setting up a new store. Sorry, I should have remembered that. Good job on the fix.

**Comment by pippinsplugins** [comment]
This has broken our AffiliateWP integration.

We add fields to the General tab with the `woocommerce_product_options_general_product_data` action:
```php
add_action( 'woocommerce_product_options_general_product_data', array( $this, 'product_settings' ), 100 );

/**
 * Adds per-product referral rate settings input fields
 *
 * @access  public
 * @since   1.2
*/
public function product_settings() {

	global $post;

	woocommerce_wp_text_input( array(
		'id'          => '_affwp_woocommerce_product_rate',
		'label'       => __( 'Affiliate Rate', 'affiliate-wp' ),
		'desc_tip'    => true,
		'description' => __( 'These settings will be used to calculate affiliate earnings per-sale. Leave blank to use default affiliate rates.', 'affiliate-wp' )
	) );
	woocommerce_wp_checkbox( array(
		'id'          => '_affwp_woocommerce_referrals_disabled',
		'label'       => __( 'Disable referrals', 'affiliate-wp' ),
		'description' => __( 'This will prevent orders of this product from generating referral commissions for affiliates.', 'affiliate-wp' ),
		'cbvalue'     => 1
	) );

	wp_nonce_field( 'affwp_woo_product_nonce', 'affwp_woo_product_nonce' );

}
```

Our fields no longer show on Variable products.

**Comment by seb86** [comment]
@pippinsplugins I think you just need to put your fields inside of a `<div class="options_group"></div>` so the new JavaScript can count the length. See [line 168](https://github.com/woothemes/woocommerce/blob/0a8e219c9dcd97b772efcee31a07c9cee91a3a08/assets/js/admin/meta-boxes-product.js#L168) of `assets/js/admin/meta-boxes-product.js`

**Comment by pippinsplugins** [comment]
Ah! That does look like it would work. We've opted to just register our own tab instead: https://github.com/AffiliateWP/AffiliateWP/issues/1427
