### ISSUE TITLE
My Account triggers get_downloadble_products()

### ISSUE THREAD

**Issue by krbvroc1** [woothemes/woocommerce#11274]
I am excited to see the the new My Account endpoint. I have a get_downloadable_products() routine that performs some DB queries and sorts the results in reverse chronological order. 

I understand reducing the load/heaviness of the old single My Account page was a goal of 2.6.

However the wc_get_account_menu_items() call get_downloadable_products() to simply  remove the 'Downloads' tab if there are no downloads yet. The downloads template already handles 'No downloads yet'. I think if someone want to remove an empty download tab they should use a filter on woocommerce_account_menu_items and unset it rather than get_downloadable_products() being triggered on every myaccount endpoint (which means twice on the downloads page and once on all other pages).

**Comment by claudiosmweb** [comment]
@mikejolley can we save it on transients?

**Comment by mikejolley** [comment]
We could do a lighter query, e.g. see if the store has downloadable product.

**Comment by krbvroc1** [comment]
@mikejolley - Was this the final solution?

I see a few scenarios where this is not ideal. For those, like myself, who use the `woocommerce_customer_get_downloadable_products` filter to dynamically generate downloads querying the woocommerce_downloadable_product_permissions table would not apply. Only for customers that have entries in that table would it show the Download tab. At least before, while heavier, the decision/count, was centralized in one place. If you split them it would be better if the
wc_get_customer_download_permissions you added simply returned a boolean rather than a table of downloads. At least I could override it to always be true or a custom lightweight test rather than being constrained to return a full set of items just so an isset() can determine whether to show the tab or not.

Or is there any reason we cant just get rid of this check and just show the Downloads tab always? If there are no downloads the tab will say so. If someone doesn't like that behavior they can use the existing `woocommerce_account_menu_items ` to remove the Downloads tab just like they can remove the Logout tab, etc.

**Comment by mikejolley** [comment]
In the end I simplified the query so it didn't get order objects too. There were lots of moans about the tab showing in 2.6.0 so this needs to stay.

**Comment by krbvroc1** [comment]
@mikejolley - Any chance of changing the `wc_get_customer_download_permissions()` routine to simply be a simpler wc_get_customer_downloads_available() that returns a boolean - and you can limit the query to 1? I am concerned that since it returns an array of permissions, someone might want to use that API for more than a boolean to determine whether to show the tab or not. If it stays this way, now I have to duplicate logic from the `woocommerce_customer_get_downloadable_products` filter into the `woocommerce_permission_list` filter you added to merge dynamically generated items with items in the database.

**Comment by mikejolley** [comment]
It's essentially the same query, and this allows people to add custom permissions and still have the tab enabled.

**Comment by krbvroc1** [comment]
@mikejolley - I guess I am not communicating the issue. I use `woocommerce_customer_get_downloadable_products` filter to dynamically generate a list of downloads. They are dynamic so for that customer their woocommerce_downloadable_product_permissions table is empty. Thus with this change the tab is no longer showing at all. For me to work around this, now I have to add an additional `woocommerce_permission_list` filter. If that was just a boolean it would be simple, but they way you coded it requires that I generate the full list again just so you can check for a simple tab.

**Comment by mikejolley** [comment]
@krbvroc1 then how did it work with wc_get_customer_available_downloads() before? Did you just not use that filter?

I guess we could also see if woocommerce_customer_get_downloadable_products returns something, but I don't know if thats ideal. Care to submit a PR that works in your case?

**Comment by mikejolley** [comment]
Either way it needs to account for both methods of adding extra non-db based permissions. Not just the way you're using.

**Comment by krbvroc1** [comment]
@mikejolley - When you say ''we could also see if woocommerce_customer_get_downloadable_products returns something, but I don't know if thats ideal' - isn't that how it was originally? It originally called WC()->customer->get_downloadable_products() which does exactly that. When wc_get_customer_available_downloads() was called and it invokes `woocommerce_customer_get_downloadable_products` filter where I dynamically add items. Everything worked fine - I wrote this issue because this path was getting invoked on every myaccount endpoint (and twice on the downloads tab).

As far as a PR, I will have to think of something to handle the various cases, but I would probably back this change out now. Because I think it is going to break any existing sites that dynamically generate their download pages. The tab will be missing. The issue I reported was not something broken, but a performance issue. I have not benchmarked it, perhaps it is not a big deal with caching.

**Comment by mikejolley** [comment]
No the other change just moved the query to a different function.

**Comment by krbvroc1** [comment]
@mikejolley Your change breaks existing sites that use the `woocommerce_customer_get_downloadable_products` filter to dynamically add items to the customers available downloads. I am testing with master right now and the download tab is missing.

**Comment by claudiosmweb** [comment]
@krbvroc1 how?
He create a new function called `wc_get_customer_download_permissions()` and still apply all filters.
And the only place that we use `wc_get_customer_download_permissions()` is inside `wc_get_customer_available_downloads()`. So how it break "breaks existing sites that use the woocommerce_customer_get_downloadable_products filter to dynamically add items to the customers available downloads"?

**Comment by claudiosmweb** [comment]
@krbvroc1 did you saw my changes, right?

**Comment by krbvroc1** [comment]
@claudiosmweb - Unless I am looking at different code, @mikejolley changed

	$downloads = WC()->customer->get_downloadable_products();
  TO
	$downloads = wc_get_customer_download_permissions( get_current_user_id() );

The original call invoked the woocommerce_customer_get_downloadable_products filter so plugins can add items to the download list (which might be empty). The second call is a brand new query that does not call that same filter. It does introduce a new filter woocommerce_permission_list. What am I missing?

**Comment by claudiosmweb** [comment]
@krbvroc1 for sure you are looking for the wrong code!

**Comment by krbvroc1** [comment]
@claudiosmweb Isn't what I described what is shown in this commit 9a77620 ???

**Comment by claudiosmweb** [comment]
@krbvroc1 PLEASE see my commit:
https://github.com/woothemes/woocommerce/commit/18b1b8c238b878e947be1ff359facd4756ae91f4

**Comment by mikejolley** [comment]
Claudio revised it. The change you didn't like is gone.

**Comment by krbvroc1** [comment]
Argh!. I had done a git pull upstream and forgot to specify master. So it pulled but I wasn't running with claudiosweb change. So sorry guys.
