### ISSUE TITLE
woocommerce  Shipping Zones

### ISSUE THREAD

**Issue by bossysaifong** [woothemes/woocommerce#11279]
![cart joe electronics 65](https://cloud.githubusercontent.com/assets/20180628/16433306/8ebf62be-3d57-11e6-8c7e-172d5e20ec57.png)
![cart joe electronics 66](https://cloud.githubusercontent.com/assets/20180628/16433308/92b3d634-3d57-11e6-926d-e9841b095efb.png)
![cart joe electronics 66](https://cloud.githubusercontent.com/assets/20180628/16433313/9a0f84f0-3d57-11e6-8597-a72ac85cbff5.png)
![checkout joe electronics 2](https://cloud.githubusercontent.com/assets/20180628/16433321/a681bd2a-3d57-11e6-93a5-415d08b7000d.png)

## EXPLANATION OF THE ISSUE
# **

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: https://joe-electronics.com
Site URL: https://joe-electronics.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.42 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (30) ###

Contact Form 7 Honeypot: by Nocean – 1.9
Contact Form 7: by Takayuki Miyoshi – 4.4.2
Envato WordPress Toolkit: by Envato – 1.7.3
Faq Responsive: by wpshopmart – 1.3.5
Far Future Expiration Plugin: by Tips and Tricks HQ – 1.3
IgniteWoo Updater: by Ignition – 2.1.3
McAfee SECURE: by McAfeeSECURE – 1.5.3
Nextend Facebook Connect: by Roland Soos – 1.5.9
Ninja Forms: by The WP Ninjas – 2.9.50
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3
Search Engine Visibility: by GoDaddy – 0.5
Social Media Feather: by Synved – 1.7.11
Compress JPEG & PNG images: by TinyPNG – 1.7.2
Woo Extra Flat Rate: by Multidots – 1.2.1
WooCommerce Accepted Payment Methods: by jameskoster – 0.7.0
WooCommerce Advanced Product Labels: by Jeroen Sormani – 1.0.4
Woocommerce Force Product Payments: by TicianaH – 1.0
Woocommerce Force Product Shippings: by TicianaH – 1.0
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce Pre-Orders: by WooThemes – 1.4.5
WooCommerce Shipment Tracking: by WooThemes – 1.4.3
WooCommerce Spam Stopper: by IgniteWoo – 1.2.1
WooCommerce: by WooThemes – 2.6.1
WooSidebars: by WooThemes – 1.4.3
WordPress Importer: by wordpressdotorg – 0.6.1
WP Instagram Widget: by Scott Evans – 1.9.8
WP101 Video Tutorials: by WP101Plugin.com – 0.3
YITH WooCommerce Ajax Search: by YITHEMES – 1.4.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.9.5.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
Check with the author of "WOO EXTRA RAT PLUGING", that seems to be the problem and STOP open the same issue over and over again, thank you :)
