### ISSUE TITLE
Broken link to Drip after set up

### ISSUE THREAD

**Issue by fluidjunction** [woothemes/woocommerce#11289]
The "Get eCommerce advice in your inbox" link after set up goes to a Drip 404 page.

Installed WooCommerce version 2.6.1 locally. Under the "Ready" step I received a Drip 404 page when attempting to subscribe.

**Comment by BFTrick** [comment]
Hey @fluidjunction - Sorry about that.

The drip campaign was on, but the form was off. That's happened a few times to us. Not sure why it happens right now. We'll investigate. For now though that form should be live. :)

**Comment by claudiosmweb** [comment]
Sorry! We just fixed the link. Thanks for let us know about it.

**Comment by fluidjunction** [comment]
No worries - was more of a heads up to help out. I ran a fresh install and was able to easily subscribe.

Thanks for knocking it out and getting back so quickly!
