### ISSUE TITLE
WC_Cart::add_to_cart() should support negative quantities

### ISSUE THREAD

**Issue by andyexeter** [woothemes/woocommerce#11286]
Is there a reason why the `WC_Cart::add_to_cart()` method only supports quantitys greater than 0? I've added in quantity increment/decrement buttons and I've added the `add_to_cart_button` and `ajax_add_to_cart` classes so woocommerce can take care of the AJAX calls and refreshing of fragments etc.

I've added two data attributes to each button: `product_id` and `quantity`. I set the quantity to 1 for the increment button and -1 for the decrement button but because of this "Sanity check" in the add_to_cart method (line 911 of `includes/class-wc-cart.php`) decrementing doesn't work and an exception is thrown:

````
// Sanity check
if ( $quantity <= 0 || ! $product_data || 'trash' === $product_data->post->post_status  ) {
	throw new Exception();
}
````

If I remove the first expression from the sanity check everything seems to work perfectly so I'm not sure why this is necessary and if there's any way around it?

I'm using woocommerce version 2.6.1 btw.

**Comment by mikejolley** [comment]
The method itself is 'add to cart' - it was never intended to support removal of items.

**Comment by andyexeter** [comment]
I get that, but if you 'add' -1 to something you're subtracting 1 from it, so by that logic 'adding' -1 of a product should reduce the quantity of that product by 1 in my opinion.

If there's a reason the method can't handle a quantity less than 1 then fair enough, but that particular expression in the sanity check appears to be there for no reason.

**Comment by mikejolley** [comment]
The reason would be that within the context of the function, it's for adding items to the cart, not removing them. Whether or not it 'could' work with negative amounts is besides the point - that is a hack. 

What is the actual use case anyway? You're not setting the cart amount, you're adding to it. Quantity increment/decrement is relative so unless you know how many are in the cart at any given time you're basically guessing if the amount you try to remove can be removed or not.

**Comment by andyexeter** [comment]
I was trying to set up quantity increment/decrement buttons in a mini cart without having to write custom JavaScript and an AJAX callback. The buttons only increment/decrement the quantity by one at a time so the amount currently in the cart isn't relevant from what I can see. When I removed the `$quantity <= 0` from the sanity the following appeared to be working perfectly:

````
<span class="add_to_cart_button ajax_add_to_cart qty-dec" data-product_id="99" data-quantity="-1">-</span>
<span class="qty-num">1</span>
<span class="add_to_cart_button ajax_add_to_cart qty-inc" data-product_id="99" data-quantity="1">+</span>
````

So if there's 1 of an item in the cart, and I clicked the `.qty-inc` button it was increasing the quantity to 2. Then if I clicked the `.qty-dec` button it'd reduce it back down to 1, clicking `.qty-dec` again would then remove that item from the cart.

**Comment by mikejolley** [comment]
@jameskoster what do you think? Ever wanted this?

I prefer to keep validation in place and expect a positive integer. As you said, custom ajax can handle custom widgets and custom code like you're presenting.

**Comment by claudiosmweb** [comment]
I don't like this, we don't need on core and there is way to increase or decrease the quantities.

**Comment by jameskoster** [comment]
No I don't like this in core either. It's _add_ to cart and that is the expected behaviour. Selecting -1 then clicking _add_ to cart is nonsense.

I see a use-case but it should be self-contained in an extension I think.
