### ISSUE TITLE
itemprop="price" displays an incorrect price for variable products

### ISSUE THREAD

**Issue by jelefra** [woothemes/woocommerce#11281]
## EXPLANATION OF THE ISSUE

WooCommerce 2.6.1
Version 2.4.9 of the single-product/price.php template

Google use the field itemprop="price" to determine the price of a product. WooCommerce supports variable products, and price for variable products may differ. Currently the field itemprop="price" is not updated based on which variation is selected. This can cause problems as Google Shopping will disapprove products when the price submitted via the product feed doesn't match the price on the website.

url: http://www.99cufflinks.co.uk/shop/cufflinks/lamborghini-cufflinks/?attribute_pa_holder=box
actual price: £11.93
source code: `meta itemprop="price" content="6.93"`

url: http://www.99cufflinks.co.uk/shop/cufflinks/lamborghini-cufflinks/?attribute_pa_holder=pouch
actual price: £6.93
source code: `meta itemprop="price" content="6.93"`

It looks like the price used in the field is the lowest of all variation prices (not the price from the default product variation).

## STEPS TO REPRODUCE THE ISSUE

Access any page for a variable product with at least 2 distinct prices.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://www.99cufflinks.co.uk
Site URL: http://www.99cufflinks.co.uk
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18
PHP Version: 5.6.17-0+deb8u1
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.47 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (13) ###

Akismet: by Automattic – 3.1.11
Google Analytics by MonsterInsights: by MonsterInsights – 5.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce Print Invoices/Packing Lists: by WooThemes / SkyVerge – 3.1.2
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10
WooCommerce Google Product Feed: by Lee Willis – 6.7.5
WooCommerce Shipment Tracking: by WooThemes – 1.4.3
WooCommerce Subscribe to Newsletter: by WooThemes – 2.3.3
WooCommerce Table Rate Shipping: by WooThemes – 3.0.1
WooCommerce: by WooThemes – 2.6.1
WooThemes Helper: by WooThemes – 1.6.2
Yoast SEO: by Team Yoast – 3.3.2

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: 99 Child
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: 99
Parent Theme Version: 1.5.10
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: 99-child/woocommerce/single-product/meta.php
99-child/woocommerce/single-product/tabs/additional-information.php

`
```

**Comment by mikejolley** [comment]
How would this work when the variation changes? Prices are variable. Is there a reason why you'd not just linking to the variable product without a pre-selected attribute?

**Comment by jelefra** [comment]
I've just realised the code snippets for each URL above weren't displaying, I meant to write that for both URL the source code was `meta itemprop="price" content="6.93"` even though one price was 6.93 and the other 11.93.

_How would this work when the variation changes?_
When a different variation is selected `meta itemprop="price" content=""` is updated with the price that corresponds for the variation.

_Is there a reason why you'd not just linking to the variable product without a pre-selected attribute?_
The two URL linked above are the one submitted by the WooCommerce Google Product Feed extension. It makes sense to submit different URL as it will show the details for the given variation straight away.

[About microdata for Google Shopping](https://support.google.com/merchants/answer/6069143)

**Comment by leewillis77** [comment]
Putting the merchant centre feed integration to one side, the normal best practice for products that include purchase options is that a schema.org Offer would be included for each option, which would include the price.

So the product page should include an Offer, and therefore a Price for each item, not just the currently selected one. 

You can do this with meta tags rather than renderable tags if you want to avoid visible information being included on the page, e.g. 

```html
<div itemscope itemtype="http://schema.org/Product" id="product-256" 
    <div class="summary entry-summary">
        <h1 itemprop="name" class="product_title entry-title">Differently sized product</h1>
        <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <meta itemprop="price" content="18">
            <meta itemprop="priceCurrency" content="GBP">
        </div>
        <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <meta itemprop="price" content="17">
            <meta itemprop="priceCurrency" content="GBP">
        </div>
        <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <meta itemprop="price" content="16">
            <meta itemprop="priceCurrency" content="GBP">
        </div>
    <meta itemprop="url" content="http://woocommerce.dev/product/differently-sized-product/">
</div>
```

It might be helpful to have additional schema tags added solely for product feed validation - although the documentation on that is pretty sparse, and unhelpful. I suspect just adding the additional offers would solve most issues, but some hooks in there would be useful and then anything needed solely for the feed can be added using those.

**Comment by mikejolley** [comment]
See #11455
