### ISSUE TITLE
Some admin screens missing headers

### ISSUE THREAD

**Issue by lutrov** [woothemes/woocommerce#11296]
There's an inconsistency in the admin screens, in terms of (H1) page headers. Some screens have them, some don't.

* Orders YES
* Coupons YES
* Reports YES
* Settings NO
* System Status NO
* WooCommerce Add-ons/Extensions YES

Is there a rationale for this? I assume so, since every admin page should have a H1 and it doesn't seem like the settings & system pages have been accidentally omitted.

**Comment by mikejolley** [comment]
Screens with tabs should not have headings.

**Comment by lutrov** [comment]
I don't recall reading anything about that being the recommended standard in WP. Where can I find out about this?

**Comment by mikejolley** [comment]
WordPress does not use tabs in the same way as WooCommerce, so it won't be one of their 'standards'.

**Comment by lutrov** [comment]
That's true. So how is it a "standard" then? Or in other words, what does "screens with tabs should not have headings" mean?

**Comment by mikejolley** [comment]
Settings, Reports, and System reports have a tabbed navigation if you look. The h1 is there, but for screen readers only. In most cases, the h1 heading would just be a repeat of the active tav, so it's removed for simplicity.

**Comment by lutrov** [comment]
This is closed now?

**Comment by mikejolley** [comment]
I just committed a change to make reports match settings. Yes it is closed.

**Comment by lutrov** [comment]
Actually, I just remembered. Wordpress __does use tabs__ in the menu editor (Appearance > Menus) and it __does use a visible H1 heading__, so for anyone having spent some time in WP admin, Woocommerce's lack of H1 will come as a surprise.

I know WP doesn't have a "standards" document which outlines how the admin pages look, or at least I'm not aware of it. However, this discussion on the WP Core blog talks about the semantic admin changes introduced a year ago:

https://make.wordpress.org/core/2015/07/31/headings-in-admin-screens-change-in-wordpress-4-3/

While tabs aren't mentioned in that discussion, my conclusion is that a visible H1 is still required, tabs or no tabs. The absence of a main page title can be quite jarring for some people. Best case scenario is that it just doesn't look quite right.
