### ISSUE TITLE
Free Shipping not showing

### ISSUE THREAD

**Issue by thehung2224** [woothemes/woocommerce#11298]
I've noticed that my Woocommerce shipping options are not all appearing. In fact, only one that shows up on the cart page is International Flat Rate, which is the most expensive option. 

This is a link to a screenshot detailing the problem:
[http://prntscr.com/bmvl57]

The website address is http://www.sweetcheeksproducts.com

Please advise on how to resolve this issue and I appreciate you for taking the time.

Cheers,

**Comment by mikejolley** [comment]
This is not a bug report, this is a request for support. Please use https://wordpress.org/plugins/woocommerce/ and read https://wordpress.org/support/topic/before-posting-gather-the-following-details?replies=1
