### ISSUE TITLE
The product_category Shortcode Should Follow Default Sorting

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#11295]
WooCommerce's default sorting is controlled by manually sorting the products in the admin.

![products_ _patrick_s_baller_test_site_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/16472854/1fb0c3bc-3e25-11e6-84c3-4b0a23c21164.jpg)

Unfortunately when you use the `[product_category]` shortcode it doesn't follow that sort. In fact I'm not sure what the default sort is for that shortcode. It should be the same as the default sort for WooCommerce.

In addition if you manually try to use parameters in the shortcode like `orderby="menu_order"` the shortcode still don't follow the order set in the WooCommerce admin.

We should fix both of these issues.

Originally from: https://woothemes.zendesk.com/agent/tickets/434764

**Comment by claudiosmweb** [comment]
@BFTrick not a bug, since by default is forcing to order only by title... And don't works by default if you sort only by `menu_order` too, but not an issue on WooCommerce.
But I'm updating it to use the `menu_order` since makes more sense than by title.
