### ISSUE TITLE
Update class-wc-meta-box-coupon-data.php

### ISSUE THREAD

**Issue by rspublishing** [woothemes/woocommerce#11299]
The `free shipping method` link available in the coupon data meta-box is no longer valid following the 2.6 release. Clicking here will take the user to a blank page (`admin.php?page=wc-settings&tab=shipping&section=WC_Shipping_Free_Shipping`)

Changing wording and replacing link with https://docs.woothemes.com/document/free-shipping/

Thanks!

**Comment by claudiosmweb** [comment]
Closing in favor of #11300
