### ISSUE TITLE
Coupon calculations and free shipping issue.

### ISSUE THREAD

**Issue by stratosvetsos** [woothemes/woocommerce#11302]
## EXPLANATION OF THE ISSUE

If you have a free shipping method lets say over 50€, and the customer applies a coupon, woocommerce uses the 'before the discount' price and gives the free shipping even if the final price plus discount is under the free shipping limit.

## STEPS TO REPRODUCE THE ISSUE

Add a free shipping rule over 50€.
Create a coupon with a Cart % Discount ( I assume that the issue exists for any discount type ) lets say 30%.
Checkout with a product that costs over 50€ lets say 60.
Apply the coupon, the total now is 60 - (60 * 30 / 100) = 42€.
42 < 50 so the user shouldn't get the free shipping.

@mikejolley I can send a pull request later today. Please confirm thats not the expected behavior so I can proceed.

## SYSTEM STATUS REPORT

WordPress Environment

Home URL: http://localhost/git/senseshop
Site URL: http://localhost/git/senseshop
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el

Server Environment

Server Info: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11
PHP Version: :x: 5.5.11 - We recommend a minimum PHP version of 5.6. See: Πως να αναβαθμίσετε την έκδοση της PHP σας
PHP Post Max Size: 512 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.16
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Απομακρυσμένο Post: ✔
Απομακρυσμένο Get: ✔

Database

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

Active Plugins (3)

Meta Box: κατα Rilwis – 4.8.7
Woocommerce Invoice Wizard: κατα Stratos Vetsos – 1.0.0
WooCommerce: κατα WooThemes – 2.6.1

Settings

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

API

API Enabled: ✔

WC Pages

Βάση Καταστήματος: #7 - /shop/
Καλάθι: #8 - /cart/
Ολοκλήρωση παραγγελίας: #9 - /checkout/
Ο Λογαριασμός μου: #10 - /my-account/

Taxonomies

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Theme

Name: Senseshop Theme
Version: 1.0-wpcom
Author URL: http://itrust.gr/
Child Theme: :x: – Αν τροποποιείτε το WooCommerce σε ένα γονικό θέμα που δεν δημιουργήσατε εσείς προσωπικά
τότε προτείνουμε τη χρήση ενός θέματος-παιδιού
Δείτε: Πως να δημιουργήσετε ένα θέμα-παιδί

WooCommerce Support: ✔

Templates

Overrides: –

**Comment by mikejolley** [comment]
This is already fixed in master.
