### ISSUE TITLE
Shortcode product_categories orderby menu_order

### ISSUE THREAD

**Issue by daviedR** [woothemes/woocommerce#11308]
The `product_categories` shortcode currently doesn't accept `menu_order` value for the `orderby` attribute. Ordering using `menu_order` should be a normal expected behavior, considering user might have sorted their product categories in the admin page. But they can't get it ordered properly using the shortcode.

Actually this can be done if the shortcode accept `meta_key` and then user can define `meta_key="order"` and `orderby="meta_value_num"` to their shortcode. This would work because the shortcode render uses `get_terms` function, and the function can process `meta_value_num` as the `orderby` value.

**Comment by mikejolley** [comment]
2.6.2 uses this by default - coming out later.

**Comment by daviedR** [comment]
Hi @mikejolley, version 2.6.2 has been released, still can sort the categories by menu order.

**Comment by claudiosmweb** [comment]
@daviedR the default is by `menu_order title`, that's is how to do it.
