### ISSUE TITLE
"Checkout is not available whilst your cart is empty" should probably be an info notice

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#11307]
[Here](https://github.com/woothemes/woocommerce/blob/697b24e2621f1b1ce4e273955344ba189403ceba/includes/wc-template-functions.php#L31). Seems a little odd to have this shown as a success message.

**Comment by seyishemba** [comment]
yes it also appears in my wordpres wppcommerce website...what is the solutin
