### ISSUE TITLE
Products going automatically out of stock

### ISSUE THREAD

**Issue by irfanwv** [woothemes/woocommerce#11301]
In my website some product show out of stock automatically without any order,
I am adding more than 100 product in quantity. How I can resolve issue?

**Comment by mikejolley** [comment]
What are you editing stock with?

**Comment by irfanwv** [comment]
Hello @mikejolley , I am just import CSV and after that add 100 and above in stock. But after some time latter show out of stock.

**Comment by mikejolley** [comment]
Then the data you're importing is not valid, or you're forgetting to set all properties.

**Comment by irfanwv** [comment]
I read your [https://wordpress.org/support/topic/problems-with-too-many-variations-causing-out-of-stock-error#post-7308065](https://wordpress.org/support/topic/problems-with-too-many-variations-causing-out-of-stock-error#post-7308065)

and my post also show `_stock_status` as `instock`

**Comment by mikejolley** [comment]
So do a test with a product you set stock via admin with. I bet that won't break :)

**Comment by irfanwv** [comment]
Ok, I'll add a product manually. Hope you are right.
