### ISSUE TITLE
Use minified version of jquery-ui.css

### ISSUE THREAD

**Issue by kristinaplauche** [woothemes/woocommerce#11317]
#### What I expected
For minified versions of CSS to be loaded

#### What happened instead
in ticket: #436847-zd-woothemes the customer points out that non-minified css is being loaded from ajax.googleapis.com

Submitted Pull Request to fix for Bookings.  Submitting pull request to fix in WooCommerce core as well.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
Closed in favor of #11318
