### ISSUE TITLE
Number of product order can be changed through inspect element

### ISSUE THREAD

**Issue by tarunchetaru** [woothemes/woocommerce#11316]
## EXPLANATION OF THE ISSUE
In many woocommerce(2.6.1) website in wordpress 4.5.3, I have seen customer can change product's quantity without affecting order total price on cart and checkout page. e.g if I added a product x at $20 and on either checkout page through inspect element, I changed to X 5 then price will remain same. and payable amount remain same to $20. Also, in order received mail quantity remains 5.

Bug reported on Mac: 10.11.5 (15F34)
Browser: Chrome
Website: http://proplenish.com.au/

## STEPS TO REPRODUCE THE ISSUE

1)Add Products and go to checkout page
2) Inspect Element and change product quantity 
3) Quantity will be changed but price remain unchanged(BUG Found)
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://www.proplenish.com.au
Site URL: https://www.proplenish.com.au
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.5 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (30) ###

Advanced Custom Fields: by Elliot Condon – 4.4.7
Contact Form 7: by Takayuki Miyoshi – 4.4.2
Easy FancyBox: by RavanH – 1.5.7
Export User Data: by Q Studio – 1.3.1
WooCommerce Gift Certificates Pro: by IgniteWoo.com – 3.5.18
IgniteWoo Updater: by Ignition – 2.1.3
MailChimp for WordPress: by ibericode – 3.1.10
Maintenance: by fruitfulcode – 3.0
WooCommerce Table Rate Shipping Plus: by mangohour – 1.8.1
New RoyalSlider: by Dmitry Semenov – 3.3.2
Popup Maker: by WP Popup Maker – 1.4.13
Post Types Order: by Nsp Code – 1.8.9.2
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove Dashboard Access: by Drew Jaynes (DrewAPicture) – 1.1.3
Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
TinyMCE Advanced: by Andrew Ozz – 4.3.10.1
UltimateWoo Pro: by UltimateWoo – 1.2.12
User Switching: by John Blackbourn – 1.0.9
Velvet Blues Update URLs: by justingreerbbi – 3.2.5
WebDev WooComerce eParcel Export: by Daniel Kirton – 2.0.7
WooCommerce Free Gift Coupons: by Kathy Darling – 1.0.9 – 1.1.0 is available
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.9
WooCommerce Newsletter Signup by ContactUs: by contactus.com – 1.1.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.34
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.0
WooCommerce Subscriptions: by Prospress Inc. – 2.0.17
WooCommerce: by WooThemes – 2.6.1
WooThemes Helper: by WooThemes – 1.6.2
Yoast SEO: by Team Yoast – 3.3.2

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #133 - /shop/
Cart: #134 - /cart/
Checkout: #135 - /checkout/
My Account: #136 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Proplenish
Version: – 0 is available
Author URL: http://www.chetaru.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: proplenish/woocommerce/archive-product.php
proplenish/woocommerce/content-product.php
proplenish/woocommerce/content-single-product.php
proplenish/woocommerce/emails/customer-new-account.php
proplenish/woocommerce/global/wrapper-end.php
proplenish/woocommerce/global/wrapper-start.php
proplenish/woocommerce/single-product/add-to-cart/external.php
proplenish/woocommerce/single-product/add-to-cart/grouped.php
proplenish/woocommerce/single-product/add-to-cart/simple.php
proplenish/woocommerce/single-product/add-to-cart/variable.php
proplenish/woocommerce/single-product.php

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: email
Export Start Time: 5:00am
Export Interval: 1440
Next Export: Scheduled on July 1
2016 5:00 am

Order Statuses: wc-processing
`

**Comment by mikejolley** [comment]
That would change the order hash - you should get an error either in the order notes, or as you place. What element are you editing anyway? Item qty's are not posted via checkout.

**Comment by mikejolley** [comment]
There is no qty input on checkout.

**Comment by claudiosmweb** [comment]
You can change on the cart, still will be calculated again in the checkout. So do not seems to be a problem...

**Comment by mikejolley** [comment]
@tarunchetaru any comments?

**Comment by tarunchetaru** [comment]
I think issue is associated with a plugin free gift coupon. This plugin was common in all woocommerce installation.

Thanks for your time :) :)
