### ISSUE TITLE
dynamic_sidebar('sidebar-all_products_types') not working in woocommerce 2.6

### ISSUE THREAD

**Issue by katawura** [woothemes/woocommerce#11312]
l was using a previous version of WooCommerce to display all the product types on my shop page.
l currently upgraded to WooCommerce 2.6 and this seem to have stopped the code dynamic_sidebar('sidebar-all_products_types') from working and thus not showing the product types anymore. l was wondering if this code has been changed to something completely different in the new version of WooCommerce thus 2.6?

**Comment by mikejolley** [comment]
WooCommerce does not register sidebars - all_products_types is not something I recognise. Must be custom/part of your theme...

**Comment by katawura** [comment]
Hi @mikejolley ,

It's a custom sidebar 

```
    register_sidebar(
        array(
            'name' => __('All Products – Types', 'optident'),
            'id' => 'sidebar-all_products_types',
            'description' => 'All products by Type',
            'before_widget' => '<nav class="%2$s c-filter">',
            'after_widget' => '</nav>',
            'before_title' => '<h1 class="c-filter__title js-nav-toggle js-nav-filter">',
            'after_title' => '</h1>',
        )
    );
```

**Comment by katawura** [comment]
`
### WordPress Environment ###

Home URL: http://optident.app
Site URL: http://optident.app/wp
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
PHP Post Max Size: 60 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 40 MB
Default Timezone is UTC: ❌ Default timezone is Europe/London - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (11) ###

Advanced Custom Fields Pro: by elliot condon – 5.3.6.1
Marvellous – EventON: by AshanJay – 0002.3.14
Marvellous – EventON - Full cal: by Ashan Jay – 0.31
Jetpack by WordPress.com: by Automattic – 4.0.4
Optident: by Tom de Bruin – 1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 2.8
WooCommerce Promotion Manager: by IndoWebKreasi – 1.2.2
WooCommerce SellMore: by IndoWebKreasi – 1.1
WooCommerce: by WooThemes – 2.6.2
Yoast SEO: by Team Yoast – 3.3.4
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.0.1

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #55 - /products/
Basket: #56 - /basket/
Checkout: #57 - /checkout/
My Account: #58 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Optident
Version: – 0 is available
Author URL: http://wearemarvellous.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: optident/woocommerce/archive-product.php
optident/woocommerce/checkout/form-billing.php
optident/woocommerce/checkout/form-shipping.php
optident/woocommerce/checkout/thankyou.php
optident/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1
optident/woocommerce/content-single-product.php
optident/woocommerce/emails/admin-new-order.php
optident/woocommerce/emails/customer-processing-order.php
optident/woocommerce/loop/loop-end.php
optident/woocommerce/loop/loop-start.php
optident/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
optident/woocommerce/myaccount/my-account.php version 2.0.0 is out of date. The core version is 2.6.0
optident/woocommerce/single-product/title.php
optident/woocommerce/single-product/up-sells.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
As WC doesn't affect sidebars directly, there may be an error on your page, or you may just have a broken widget. Enable WP_DEBUG mode.

**Comment by katawura** [comment]
l agree is a broken widget

![screen shot 2016-07-01 at 11 10 54](https://cloud.githubusercontent.com/assets/5200700/16518772/9855a85c-3f7c-11e6-9685-9a12fc3da94e.png)

**Comment by katawura** [comment]
Nothing in that widget shows apart from the test content so l suppose the Woocmms layered nav is broken. Any ideas on fixing this?  l have tried almost everything that l know.

**Comment by mikejolley** [comment]
Since this only shows on shop pages, is your shop page still set in WC > Settings > Products?

**Comment by katawura** [comment]
![screen shot 2016-07-01 at 11 30 46](https://cloud.githubusercontent.com/assets/5200700/16519222/4c742410-3f7f-11e6-8e39-53ad8aaf330d.png)


Its called All Products

**Comment by mikejolley** [comment]
That page and the category pages are the only places this widget should work and be shown. No where else.

**Comment by katawura** [comment]
l have tried side bar directly using dynamic_sidebar('sidebar-all_products_types');  in the archive-products.php but this doesn't seem to work as expected.

**Comment by mikejolley** [comment]
What about regular sidebars in another theme?

I cannot think of anything in core which would affect this sorry.

**Comment by katawura** [comment]
l got this in my side bar 

```
<?php

if (is_shop() && isset($wp_query->query_vars['manufacturers'])) {
    dynamic_sidebar('sidebar-all_products_manufacturers');
    echo '&nbsp;';
} elseif (is_page('products')) {
    dynamic_sidebar('sidebar-all_products_types');
    echo '&nbsp;';
} elseif (is_product_category()) {
    dynamic_sidebar('sidebar-manufacturer');
    echo '&nbsp;';
}
```

All of them show up except this dynamic_sidebar('sidebar-all_products_types');

**Comment by mikejolley** [comment]
is_page will never work - its a custom post type archive, not a real page.

**Comment by katawura** [comment]
l changed it to is_shop() and that doesn't seem to work either

**Comment by mikejolley** [comment]
So remove all your custom logic?

**Comment by katawura** [comment]
l tried that and just actually called the dynamic_sidebar('sidebar-all_products_types'); directly in the archive-product.php . But wasn't working. Also l removed all the log in the sidebar.php and only had 

```
dynamic_sidebar('sidebar-all_products_types');
```

which didn't work so l tried 

```
if (is_shop()) {
    dynamic_sidebar('sidebar-all_products_types');
}
```

which didnt work aswell.

**Comment by mikejolley** [comment]
The only other thing I can think of is something is resetting the query before the sidebar is rendered, so the layered nav widget doesn't know it's supposed to show. 

As this is working with default WP themes, I don't think its a bug anyway.
