### ISSUE TITLE
"Copy to a new draft" doesn't clone variation's post_name and guid

### ISSUE THREAD

**Issue by daviedR** [woothemes/woocommerce#11311]
When using the `Copy to a new draft` link, the variation's post_name and guid is not created. These fields are used in a plugin to detect duplicate posts (by checking the guid field).

**Comment by mikejolley** [comment]
Doesn't post_name have to be unique? How could it duplicate then?

**Comment by daviedR** [comment]
@mikejolley Yes it has to be unique. WooCommerce did this and generated those fields everytime user hit the `Add variation` button on product details tabs. The `post_name` value would be generated like this `product-43-variation`, `product-43-variation-2`, and so on. The `guid`s would follow: `http://domain.com/product_variation/product-43-variation/`, `http://domain.com/product_variation/product-43-variation-2/`, and so on.

@claudiosmweb Yes, there is no error or issue shown. However in your database, table `wp_posts` the variation created by `Copy to a new draft` doesn't have `post_name` and `guid`.

Please look at this screenshot, the differences between the "manually-created" variations and the "copy-to-new-draft" variations. The ones with `post_parent` 43 are variations created by `Add Variation` method. And the rests below them are created by `Copy to a new draft` link.

![image](https://cloud.githubusercontent.com/assets/1287713/16538359/cf55ac50-404c-11e6-909a-17b2ae14bad0.png)

-

What I am questioning here, when you use `Copy to a new draft` link, those `post_name` and`guid` fields are left blank. WooCommerce doesn't generate them. The manual `Add Variation` method generates those fields, why it doesn't work the same way for the `Copy to a new draft` method. Not sure, but I think `guid` is quite important to have, regardless it's used on front end or not.

-

An importer plugin: https://github.com/humanmade/WordPress-Importer, takes advantage of the 
`guid` field to check if the same posts are already imported or not. I have exported my database using WordPress Tools > Export which has product variations with the `post_name` and `guid` blank (because of the `Copy to a new draft`). This causes the plugin fail to check because the `guid` field is blank.
