### ISSUE TITLE
Whitespace in WooCommerce Product Categories Display

### ISSUE THREAD

**Issue by om4erana** [woothemes/woocommerce#11329]
## EXPLANATION OF THE ISSUE

Using WooCommerce Shortcode:
[product_categories columns="5" parent="0" hide_empty="0"]

WooCommerce Version: 2.6.2
WordPress theme: Twenty Sixteen
Browser: All

Whitespace between html elements causing layout issues. Category list items "step" down, category title h3's have blank tabs before/after.

## STEPS TO REPRODUCE THE ISSUE

1. Insert product categories shortcode into page.
2. View page. Notice layout issues.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###
![woocommerce product categories](https://cloud.githubusercontent.com/assets/20238125/16537085/678cfc1c-403e-11e6-9e8a-eed86c730f02.png)

WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.2

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #145 - /shop/
Cart: #146 - /cart/
Checkout: #147 - /checkout/
My Account: #148 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
`

**Comment by WPprodigy** [comment]
Go to the text editor and make sure your shortcode doesn't have `<pre>` tags around it. https://docs.woothemes.com/document/woocommerce-shortcodes/#section-20
