### ISSUE TITLE
htaccess Set-Cookie and WC bug

### ISSUE THREAD

**Issue by michelve** [woothemes/woocommerce#11327]
when i enable the following in my hatccess:

```
#Header always edit Set-Cookie (.*) "$1; HttpOnly"
#Header always edit Set-Cookie (.*) "$1; Secure"
```

and try to place and order by clicking add-to-cart button within the product page, it sends you to the cart page but not product was added.

**Comment by claudiosmweb** [comment]
You should exclude it from at least the cart and checkout.
Not a bug in WooCommerce, since need to have fresh content in this dynamic pages.
