### ISSUE TITLE
System Status incorrectly identifies MariaDB as MySQL

### ISSUE THREAD

**Issue by AndrewNaturals** [woothemes/woocommerce#11320]
## EXPLANATION OF THE ISSUE

WooCommerce settings report an out-of-date MySQL version with servers running an up-to-date version of MariaDB. I would recommend renaming "MySQL version" to "Database Version" and detecting MariaDB & MySQL together. I don't believe I'm skilled enough to create a pull request but I was able to put together some code that may help expedite the process here:

`$sql_version =  mysqli_get_server_info( $wpdb->dbh );`

`$sql_version = preg_split("/-/",  $sql_version);`
`$c = count($sql_version);`
`if ($c === 2 ) {`
`$mariadb_version = $sql_version[0];`
`} else if ($c === 3 ) {`
`$mariadb_version = $sql_version[1];`
`}`

`if ( version_compare( $mariadb_version, '10.0', '<' ) ) {`
`echo '<mark class="error"><span class="dashicons dashicons-warning"></span> ' . sprintf( __( '%s - We recommend a minimum MariaDB version of 10.0. See: %s', 'woocommerce' ), esc_html( $mariadb_version ), '<a href="https://wordpress.org/about/requirements/" target="_blank">' . __( 'WordPress Requirements', 'woocommerce' ) . '</a>' ) . '</mark>';`
`} else {`
`echo '<mark class="yes">' . esc_html( $mariadb_version ) . '</mark>';`
`}`

## STEPS TO REPRODUCE THE ISSUE

1. Server must use MariaDB instead of MySQL
2. Visit WooCommerce System Status
3. Scroll down to MySQL version

**Comment by claudiosmweb** [comment]
You code don't works or not for all cases:

```
wp>  mysqli_get_server_info( $wpdb->dbh )
string(17) "5.7.12-0ubuntu1.1"
```

This comments can be applied here too: https://github.com/woothemes/woocommerce/issues/11117#issuecomment-225924942
