### ISSUE TITLE
possible command injection vulnerability.

### ISSUE THREAD

**Issue by michelve** [woothemes/woocommerce#11328]
Classification: Information
Resource: /product/**product_name_here**/
Parameter: add-to-cart
Method: POST
Detection Type: Linux/Unix Blind Timing Analysis Checks
Risk: High

**REQUEST:**
POST /product/**product_name_here**/ [add-to-cart=; /bin/sleep 31 ; ]

**Comment by claudiosmweb** [comment]
Possible? Have you tested it?

Here where we get the `add-to-cart` parameter:

https://github.com/woothemes/woocommerce/blob/ccd6389eccd0ec88918df1a5e05fcb6ec449156d/includes/class-wc-form-handler.php#L686-L698
