### ISSUE TITLE
Notice: Array to string conversion

### ISSUE THREAD

**Issue by crazysnowflake** [woothemes/woocommerce#11326]
## EXPLANATION OF THE ISSUE
Error on the store page when `$_GET` is recursive array.
 

> Notice: Array to string conversion 

## STEPS TO REPRODUCE THE ISSUE

Go to the store page and add query to url
Example: `site.com/shop/?uf[t][product_cat][value][0]=15&uf[t][product_cat][value][1]=10&uf[t][product_cat][rel]=OR&uf[m][_price][value][0]=0&uf[m][_price][value][1]=12950&uf[m][_price][rel]=BETWEEN`

## A quickfix:

add new function:

```
function query_string_vars($key, $val)
{
	if ( is_array( $val ) ) {
		foreach( $val as $index => $innerVal ) {
			query_string_vars($key . '['.$index.']', $innerVal );
		}
	} else {
		echo '<input type="hidden" name="' . esc_attr( $key ) . '" value="' . esc_attr( $val ) . '" />';
	}
}
```
on the template file woocommerce\templates\loop\orderby.php  replace lines 36-38 to
```
foreach( $val as $index => $innerVal ) {
	query_string_vars($key . '['.$index.']', $innerVal );
}
```

**Comment by mikejolley** [comment]
Requires a template change so punting to 2.7.

**Comment by crazysnowflake** [comment]
Thank you. But I found another related issue, when checking the excluded keys (in _wc_query_string_form_fields_ function)
```
if ( in_array( $key, $exclude ) ) {
    continue;
}
```
if key is '0' it will be skipped too, for fix this just need to add third parameter.
```
if ( in_array( $key, $exclude, empty($key) && $key !== '0' ) ) {
   continue;
}
```

**Comment by mikejolley** [comment]
@crazysnowflake $exclude doesn't contain 0 - are you sure?

**Comment by crazysnowflake** [comment]
@mikejolley Yes, I'm sure. Please read http://stackoverflow.com/a/13846839

**Comment by mikejolley** [comment]
Ok, should just need to enable strict then at all times.
