### ISSUE TITLE
Out of stock threshold: products showing in results count on product category pages

### ISSUE THREAD

**Issue by hannahswain** [woothemes/woocommerce#11322]
## EXPLANATION OF THE ISSUE

When the `out of stock threshold` is set to 1 or more, products which should be out of stock are 
counted on the product category page but not displayed. Tested on WooCommerce 2.6.1 and 2.6.2.

![2016-07-01_10-07-23](https://cloud.githubusercontent.com/assets/17844465/16515684/b6f75912-3f73-11e6-9e97-736154361de5.png)

Reproduced on customer site and local dev site.

436128-zd-woothemes

## STEPS TO REPRODUCE THE ISSUE

1) Set WooCommerce > Settings > Products > Inventory:  `out of stock threshold` to 1

2) On a product, enable `manage stock`, set `stock quantity` to 1 and set `stock status` to "in stock".  Add this product to a new/empty product category. 

![2016-07-01_10-08-55](https://cloud.githubusercontent.com/assets/17844465/16515708/dad46d20-3f73-11e6-9511-25219cd4c762.png)

3) Check the product category page and see that it returns 1 result, even though no results are displayed.

**Comment by mikejolley** [comment]
@hannahswain this is because the threshold has been changed after the fact. In normal usage, that product would have an 'out of stock' status once it hits 1. This would hide it from queries.

Since the threshold has been changed after stock was set, this is not going to happen.

**Comment by nesbtesh** [comment]
But for some reason for me, even after I update the product to out of stock it still counts it in the product loop. Even do is not actually showing the product
