### ISSUE TITLE
Error in get_gallery_attachment_ids when empty

### ISSUE THREAD

**Issue by nbdamian** [woothemes/woocommerce#11321]
When a product has no gallery, the $this->product_image_gallery variable returns array() instead of an empty string.
This is causing an error of "Warning: explode() expects parameter 2 to be string, array given in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 187"

A quickfix would be adding:
````
if (is_array($this->product_image_gallery))
$this->product_image_gallery = "";
````
to the function.

**Comment by claudiosmweb** [comment]
By default `product_image_gallery` is always string... Seems like you used some custom code that broke it, since in core we don't try to convert it to an array.
