### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by Purkis** [woothemes/woocommerce#11331]
Under settings within WooCommerce we select shipping  and proceed to add a shipping zone called Local Pickup and when we go to save this it Cant save or wont save. We have disabled plugins that are under wooCommerce but that makes no difference.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
````
### WordPress Environment ###

Home URL: http://www.glutenfreegrocer.co.nz
Site URL: http://www.glutenfreegrocer.co.nz
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_perl/2.0.8 Perl/v5.10.1
PHP Version: ❌ 5.5.36 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 10.0.20
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ❌ Table does not exist
woocommerce_shipping_zone_locations: ❌ Table does not exist
woocommerce_shipping_zone_methods: ❌ Table does not exist
woocommerce_payment_tokens: ❌ Table does not exist
woocommerce_payment_tokenmeta: ❌ Table does not exist
MaxMind GeoIP Database: ✔

### Active Plugins (30) ###

Redux Framework: by Team Redux – 3.6.0.2
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.8.1
WooCommerce Smart Coupons: by WooThemes – 3.0.6
WooCommerce Points and Rewards: by WooThemes – 1.5.4
Contact Form 7: by Takayuki Miyoshi – 4.4.2
Duplicator Pro: by Snap Creek – 3.0.12
Hide Plugins: by brianmiyaji – 1.0.4
iThemes Security Pro: by iThemes – 2.1.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
MailChimp for WordPress: by ibericode – 3.1.10
Mega Main Menu: by MegaMain.com – 2.1.1
ModelTheme Framework: by ModelTheme – 1.0
WooCommerce New Zealand Post Shipping Method: by WPRuby – 1.1.0
Parallax Backgrounds for VC: by Benjamin Intal - Gambit – 4.3
Premium SEO pack - Wordpress Plugin: by AA-Team – 1.1.0
Slider Revolution: by ThemePunch – 5.2.5.3
Easy Updates Manager: by Easy Updates Manager Team – 6.1.5
User Registration Aide: by Brian Novotny – 1.5.2.6
User Role Editor: by Vladimir Garagulya – 4.25.2
White Label Branding for WordPress: by Alberto Lau (RightHere LLC) – 4.0.8.66283
WooCommerce Product Archive Customiser: by jameskoster – 1.0.1
WooCommerce Shipping Pro with Table Rate: by WooForce – 2.4.0
WooCommerce: by WooThemes – 2.6.1
Payment Express Gateway for WooCommerce: by PatSaTECH – 1.3.1
WooThemes Helper: by WooThemes – 1.6.2
Wp Mail Bank: by Tech Banker – 1.44
WP Super Cache: by Automattic – 1.4.8
YITH WooCommerce Compare: by YITHEMES – 2.0.9
YITH WooCommerce Quick View: by YITHEMES – 1.1.2
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop Base: #6 - /shop/
Basket: #1957 - /cart-2/
Checkout: #8 - /checkout/
My Account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Glutentheme1.9.7
Version: 1.9.7
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: GlutenTheme1.9.7/woocommerce/archive-product.php
GlutenTheme1.9.7/woocommerce/checkout/form-billing.php
GlutenTheme1.9.7/woocommerce/checkout/form-checkout.php
GlutenTheme1.9.7/woocommerce/checkout/form-coupon.php
GlutenTheme1.9.7/woocommerce/checkout/form-login.php
GlutenTheme1.9.7/woocommerce/checkout/form-shipping.php
GlutenTheme1.9.7/woocommerce/checkout/payment-method.php
GlutenTheme1.9.7/woocommerce/checkout/review-order.php
GlutenTheme1.9.7/woocommerce/checkout/thankyou.php
GlutenTheme1.9.7/woocommerce/content-product.php
GlutenTheme1.9.7/woocommerce/content-single-product.php
GlutenTheme1.9.7/woocommerce/loop/add-to-cart.php
GlutenTheme1.9.7/woocommerce/single-product/add-to-cart/external.php
GlutenTheme1.9.7/woocommerce/single-product/add-to-cart/grouped.php
GlutenTheme1.9.7/woocommerce/single-product/add-to-cart/simple.php
GlutenTheme1.9.7/woocommerce/single-product/meta.php
GlutenTheme1.9.7/woocommerce/single-product/product-attributes.php
GlutenTheme1.9.7/woocommerce/single-product/product-image.php
GlutenTheme1.9.7/woocommerce/single-product/product-thumbnails.php
GlutenTheme1.9.7/woocommerce/single-product/rating.php
GlutenTheme1.9.7/woocommerce/single-product/related.php
GlutenTheme1.9.7/woocommerce/single-product/sale-flash.php
GlutenTheme1.9.7/woocommerce/single-product/share.php
GlutenTheme1.9.7/woocommerce/single-product/short-description.php
GlutenTheme1.9.7/woocommerce/single-product/tabs/additional-information.php
GlutenTheme1.9.7/woocommerce/single-product/tabs/description.php
GlutenTheme1.9.7/woocommerce/single-product/title.php
GlutenTheme1.9.7/woocommerce/single-product/up-sells.php
GlutenTheme1.9.7/woocommerce/single-product-reviews.php
GlutenTheme1.9.7/woocommerce/single-product.php
GlutenTheme1.9.7/woocommerce/taxonomy-product_cat.php
GlutenTheme1.9.7/woocommerce/taxonomy-product_tag.php

`

**Comment by WPprodigy** [comment]
I'm sorry but this is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around in the [WooThemes Support](http://support.woothemes.com) documentation.
