### ISSUE TITLE
Add A Email Filed On Shipping And Notify Order Via Email 

### ISSUE THREAD

**Issue by naflan121** [woothemes/woocommerce#11338]
**Wordpress Version**  4.5.3
**Wocommerce Version**  2.6.2

Hi
I want to add a extra email field on checkout page i have use the following codes in function.php to add it 

`
/**
 * Add the field to the checkout
 */
add_action( 'woocommerce_after_order_notes', 'my_custom_checkout_field' );

function my_custom_checkout_field( $checkout ) {

    echo '<div id="my_custom_checkout_field"><h2>' . __('My Field') . '</h2>';

    woocommerce_form_field( 'my_field_name', array(
        'type'          => 'text',
        'class'         => array('my-field-class form-row-wide'),
        'label'         => __('Shipping Email'),
        'placeholder'   => __('Enter something'),
        ), $checkout->get_value( 'my_field_name' ));

    echo '</div>';

}
`
![image](https://cloud.githubusercontent.com/assets/11876070/16544378/4c4d9f8a-4136-11e6-94a1-e5ef6cc362fa.png)

So now i want to send the order copy to that email, could it possible to do so, have tried for plugins nothing worked out. 
Thank You

**Comment by claudiosmweb** [comment]
Please read this:

>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

So better you open a topic in the https://wordpress.org/support/plugin/woocommerce
