### ISSUE TITLE
Applying coupons using woocommerce rest api

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#11336]
Hello,
I am registering order using woo commerce REST API.Order is successfully placed and is also reflected in admin dashboard.But the problem is when i add coupon lines in order the coupon amount is not registered in admin dashboard though its displaying applied coupon name.Hence the order amount calculation is displayed wrong. 
------------------------------------------------------------------------------
I am using woo commerce version 2.2.5 and API version is v3.
Below is order in put in json.
$data = [
    'order' => [
        'payment_details' => [
            'method_id' => 'cod',
            'method_title' => 'Cash on Delivery',
            'paid' => true,
        ],
        'billing_address' => [
            'first_name' => 'John1',
            'last_name' => 'Doe',
            'address_1' => '969 Market',
            'address_2' => '',
            'city' => 'San Francisco',
            'state' => 'CA',
            'postcode' => '94103',
            'country' => 'US',
            'email' => 'john.doe@example.com',
            'phone' => '(555) 555-5555'
        ],
        'shipping_address' => [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'address_1' => '969 Market',
            'address_2' => '',
            'city' => 'San Francisco',
            'state' => 'CA',
            'postcode' => '94103',
            'country' => 'US'
        ],
        'customer_id' => 2,
        'line_items' => [
            [
                'product_id' => 96,
                'quantity' => 2
            ]
        ],
		'coupon_lines'=>
		[
		   [
		    'id' => '',
		    'code'=>'wer',
			//'id'=>'128',
            'amount'=>'10.00'
			//'discount'=>10
		   ]
		]
    ]
];
echo ''.json_encode($woocommerce->post('orders', $data));

----------------------------------------------------------------
![couponissue](https://cloud.githubusercontent.com/assets/15122702/16540902/58722186-4092-11e6-95e7-68bb8d988c43.png)

Also i have attached screen shot below that displays tat "wer" coupon code is applied but discount
is not applied.

So can you please tell me if i m doing something wrong or is there any way to do this.

Thank you.

**Comment by claudiosmweb** [comment]
Please, read the docs for your version of REST API: http://woothemes.github.io/woocommerce-rest-api-docs/v3.html#orders-properties

**Comment by ankurgecr** [comment]
You are doing it properly as per the REST API doc. I don't understand why @claudiosmweb  closed this !!
