### ISSUE TITLE
Load time on queries with large product sets significantly hampered by _visibility meta query.

### ISSUE THREAD

**Issue by matthewduhig** [woothemes/woocommerce#11339]
## EXPLAIN THE ISSUE

On sites with a large number of products (30k +), the '_visibility' meta query performed on all wc product queries can increase the time taken to perform the query by as much as 8 times.

## STEPS TO REPRODUCE THE ISSUE

Query for some products (in my case I am using the featured_products shortcode) to show some products on the frontend of a site with over 30k products (in my case I have around 70k, but I started experiencing slower load times at around 30k plus).

On the site I am working on, the query (which used the featured_products shortcode to grab 4 products) was taking between 7 - 8 seconds. Commenting out line 645 from class-wc-query.php ($meta_query[] = $this->visibility_meta_query()) reduced this to 0.8 seconds.

I understand the purpose of the _visiblity meta_query, but in my case (and I'm sure some others) I don't use this functionality. Therefore, it would be awesome if we could simply enable/disable this function either through an option in the WooCommerce settings, or a simple true/false hook in a functions.php file.

Thanks guys!

Matt

**Comment by mattyza** [comment]
Thanks for sharing this, @matthewduhig.

As an interim measure, while we work to optimise this query, perhaps we should add array keys to the array we use to add meta queries?

This will enable the filter (which currently exists) to easily allow for removing a specific meta query.

![image](https://cloud.githubusercontent.com/assets/880803/16547220/16219bca-4166-11e6-88ca-2c4fcbcb20c3.png)

Thoughts @claudiosmweb ?

**Comment by claudiosmweb** [comment]
It's easy to remove the `_visiblity meta_query`, but yes, maybe add new keys can help too.
