### ISSUE TITLE
Variant Selection doesn't change image

### ISSUE THREAD

**Issue by nidsss** [woothemes/woocommerce#11330]
http://99creativewebsite.co.in/j-chiron/product/test-product
this is the url of my site and color variation  images of products are not showing when  I select color options from given dropdown option.

**Comment by WPprodigy** [comment]
I'm sorry but this is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around in the [WooThemes Support](http://support.woothemes.com) documentation.
