### ISSUE TITLE
Layered nav counts - not affected by search criteria

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#11335]
Reported in https://wordpress.org/support/topic/woocommerce-layered-nav-on-search-results?replies=1

**Comment by twoelevenjay** [comment]
I jumped the gun earlier and submitted PR #11394 earlier, it corrected this issue great on a test site with a very small amount of products lol. I closed that PR and gave it another shot. Rather than submit another PR, I figured i would get some feedback here first. Here are my changes: https://github.com/woothemes/woocommerce/compare/master...twoelevenjay:master

I added search terms to the SQL Query when is_search() returns true like so:

```php
		if ( is_search() ) {
			$search_terms = $wp_query->query_vars['search_terms'];
			$count = 0;
			$query['where'] .= " AND (";
			foreach ( $search_terms as $search_term ) {
				$query['where'] .= $count > 0 ? " AND " : "";
				$query['where'] .= "((wp_posts.post_title LIKE '%" . $search_term . "%') OR (wp_posts.post_excerpt LIKE '%" . $search_term . "%') OR (wp_posts.post_content LIKE '%" . $search_term . "%'))";
				$count++;
			}
			$query['where'] .= ")";
		}
```

**Comment by twoelevenjay** [comment]
I updated it to give the search related query string its own array key for better access during woocommerce_get_filtered_term_product_counts_query.

```php
		if ( is_search() ) {
			$search_terms     = $wp_query->query_vars['search_terms'];
			$count            = 0;
			$query['search']  = " AND (";
			foreach ( $search_terms as $search_term ) {
				$query['search'] .= $count > 0 ? " AND " : "";
				$query['search'] .= "((wp_posts.post_title LIKE '%" . $search_term . "%') OR (wp_posts.post_excerpt LIKE '%" . $search_term . "%') OR (wp_posts.post_content LIKE '%" . $search_term . "%'))";
				$count++;
			}
			$query['search'] .= ")";
		}
```

@claudiosmweb should I submit a PR?

**Comment by twoelevenjay** [comment]
@jchristopher, what are your thoughts on how this would affect the SearchWP WooCommerce integration?

**Comment by twoelevenjay** [comment]
I created a PR, #11400.

**Comment by twoelevenjay** [comment]
I cleaned up my fork and restarted it from the upstream, and I that closed this PR by mistake. I restarted the fork for a different PR (#11429) that is currently open, it is simpler and more straightforward so I will leave that open for now and submit a new PR for nav filters after. But the code is here in the thread for critiquing ;-)
