### ISSUE TITLE
Include clickable attributes in default Woocommerce

### ISSUE THREAD

**Issue by rebastion** [woothemes/woocommerce#11332]
Hi Everyone

I am a Github novice so please excuse if the way I'm doing it is wrong. There's an issue with Woocommerce out of the box where product attributes aren't clickable. Which is basically what most users would expect to allow further filtering (e.g. on a catalog of DVDs, click the year of release, the language option, or most commonly the actor, director, etc.)

So someone made this very helpful GIST
https://gist.github.com/mikejolley/e2e85f8883776211681c

And I am wondering if this could be integrated into the default Woocommerce, because right now I need to modify the file each time I update Woocommerce, and it's really such a no-brainer this modification. Thanks!

**Comment by WPprodigy** [comment]
You don't need to (and never should) modify the core files. You can override the template in your child theme and stay upgrade safe: http://docs.woothemes.com/document/template-structure/

Attributes aren't clickable by default because not all stores want to show the archive pages for them. That is what tags and categories are for.

**Comment by rebastion** [comment]
the problem with overriding is that I potentially miss out on any improvements or other fixes applied in the default file...

**Comment by claudiosmweb** [comment]
@rebastion the idea of allow people override templates is for they overriding templates!

**Comment by rebastion** [comment]
I know what the idea is for, but my argument is this: why force people to meddle with sub themes for such a feature that could easily be a checkbox in woocommerce settings, when the price to pay for overrides is to miss out on possible fixes and improvements made in the original file!

**Comment by WPprodigy** [comment]
> a feature that could easily be a checkbox in woocommerce settings

This could be set about hundreds of things. A setting for everything like this would results in pages and pages of settings.

Yes, overriding a template does mean you won't immediately get the future enhancements to that template. But we do notify you when you're overriding a template that has been updated in core. This one in particular has not been updated since WooCommerce 2.1.3.

**Comment by rebastion** [comment]
Well there is already a pretty convoluted set of options and settings in woocommerce, just consider my idea raised, I don't know who decides what goes into the product and what doesn't....

**Comment by claudiosmweb** [comment]
> when the price to pay for overrides is to miss out on possible fixes and improvements made in the original file!

Not a price to pay, we did not do too much changes in templates. You guys need to lose the fear of use templates.

**Comment by claudiosmweb** [comment]
I don't see this happen and you should use templates, but I logged your idea to our roadmap for voting: https://trello.com/c/O1lbEXQz/89-clickable-attributes
Good look!

**Comment by ZaheerAbbasAghani** [comment]
<?php


global $product;
global $post;


 
$attributes = $product->get_attributes();

//print_r($attributes);
 
if ( ! $attributes ) {
     
    return;
     
}
 
foreach ( $attributes as $attribute ) {
              
    // Get the taxonomy.
    $terms = wp_get_post_terms( $product->id, $attribute[ 'name' ], 'all' );
    $taxonomy = $terms[ 0 ]->taxonomy;
          
    // Get the taxonomy object.
    $taxonomy_object = get_taxonomy( $taxonomy );
     
    // Get the attribute label.
    $attribute_label = $taxonomy_object->labels->name;
     
    // Display the label followed by a clickable list of terms.
    echo get_the_term_list( $post->ID, $attribute[ 'name' ] , '<div class="attributes">' . $attribute_label . ': ' , ', ', '</div>' );
     
}

**Comment by WPprodigy** [comment]
Don't need any custom code for this. If the attribute is public, WooCommerce will now show a link instead by default: https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-attributes.php#L53-L55

http://cld.wthms.co/zKlmw &

**Comment by rajbaron** [comment]
I'm in a desperate need for a way to make attribute image clickable so larger image loads in lightbox to show details. I'm not coder. Any help will be much appreciated.

**Comment by WPprodigy** [comment]
@rajbaron Sorry, this isn't the place to ask for customization requests.

I'd recommend contacting one of the services on this page: https://woocommerce.com/customizations/
