### ISSUE TITLE
"Net sales this month" & Stock Management

### ISSUE THREAD

**Issue by aneeshjajodia** [woothemes/woocommerce#11333]
Team,

After a lot of fidgeting, I was able to figure out one thing with the new update of WooCommerce that is, the **Net sales this month** _(which is located on the dashboard)_, has the issue that, none of the **manual orders** _(created using backend)_ are included in the total sales amount.

I don't know if I am the only one facing this since I was able to find just one person other than me who had the similar issue but wasn't resolved.

<img width="404" alt="capture" src="https://cloud.githubusercontent.com/assets/1062704/16540321/2e2a01e6-407e-11e6-9567-aa9a09bcf496.PNG">

Also, **by generating the order manually**, the stock management was not working perfectly that is, it was not deducting from the stock available. Can someone help me resolving this, that is the best practice for the same?

Awaiting a reply.

Best.

**Comment by mikejolley** [comment]
This seems to be working fine my end. I suspect it's just related to a) your line items + totals and b) your order status.
