### ISSUE TITLE
[API] When update Variations sku generate error 

### ISSUE THREAD

**Issue by uganof** [woothemes/woocommerce#11344]
## EXPLANATION OF THE ISSUE

using REST API v1 (the last) 
woocommerce v. 2.6.2 with wp 4.5.3
when I modify Variantions generate error with:
 {"code":"woocommerce_rest_product_sku_already_exists","message":"The SKU already exists on another product.","data":{"status":400}}(HTTP/1.1 400 Bad Request)
sky is really unique in db

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://shop.forcard.it/wp
Site URL: http://shop.forcard.it/wp
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache/2.2.22 (Debian)
PHP Version: ❌ 5.4.45-0+deb7u2 - We recommend a minimum PHP version of 5.6. See: Come aggiornare la versione di PHP
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
POST remoto: ✔
GET remoto: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (5) ###

WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.2.1
WP REST API: by WP REST API Team – 2.0-beta13.1
WooCommerce Custom Product Data Fields: by Kharis Sulistiyono – 1.2.3
WooCommerce Multilingual: by OnTheGoSystems – 3.8.1
WooCommerce: by WooThemes – 2.6.2

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /
Carrello: #5 - /carrello/
Cassa: #6 - /cassa/
Il mio account: #7 - /mio-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.0.4
Author URL: https://www.woothemes.com
Child Theme: ❌ – Se stati modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

**Comment by claudiosmweb** [comment]
Because the variation still exists due a bug, need to delete from the database. Fixed in https://github.com/woothemes/woocommerce/commit/0fe6be1eec98dadc6dc92f983f157b78df6ef66d
