### ISSUE TITLE
Comma in flat rate shipping cost field gives an error

### ISSUE THREAD

**Issue by mikkamp** [woothemes/woocommerce#11346]
When a comma is used in the cost field for the flat rate shipping method it shows an error when calculating the shipping costs.

To test this I added a flat rate shipping method with the cost of 10,5
I then get the following error:

`Error found in: /srv/www/woo-tablerate.dev/htdocs/wp-content/plugins/woocommerce/includes/libraries/class-wc-eval-math.php, nfx, 167`

This only happens if we are using a '.' for the decimal separator. When I switch to using a ',' as the decimal separator I can enter both 10,5 and 10.5 without getting the error to show up.

I understand that entering 10,5 is not correct when '.' is being used as the decimal separator. But considering that some countries use the ',' as a decimal separator, this can be confusing especially since the error is not very descriptive.
It would be helpful to get either a descriptive error message or get a warning when saving the shipping costs that the calculation might not be correct.

Maybe an easy solution would to use the Eval Math class to run through the cost sum when it is saved in the backend. And if it returns any errors then warn the user that the cost sum might not be correct.

**Comment by rocketeer76** [comment]
There was a similar "error" in the Product CSV Import Suite plugin when having a comma in the price. That time they changed the documentation describing not to use a comma in the price. But off course using comma as a separator is common in many countries on this planet.

**Comment by claudiosmweb** [comment]
@rocketeer76 need to fix in CSV Import Suite plugin and not here. This is for WooCommerce core issues only.

**Comment by rocketeer76** [comment]
I understand. I'm using the SUBSTITUTE function in Excel to replace the delimiter, which works good for the Product CSV Import Suite plugin.
