### ISSUE TITLE
Fatal error: Class 'WC_Email_Customer_On_Hold_Order' not found

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#11348]
## EXPLANATION OF THE ISSUE

After upgrading to version 2.6.2 got fatal error:

Fatal error: Class 'WC_Email_Customer_On_Hold_Order' not found in .../woocommerce/includes/emails/class-wc-email-customer-on-hold-order.php on line 103

## STEPS TO REPRODUCE THE ISSUE

Call WC()->mailer();

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
Not available

**Comment by smazur** [comment]
Looks like copy-paste issue:
woocommerce/includes/emails/class-wc-email-customer-on-hold-order.php:7
```
if ( ! class_exists( 'WC_Email_Customer_Processing_Order' ) ) :
/**
 * Customer On-hold Order Email.
 *
 * An email sent to the customer when a new order is on-hold for.
 *
 * @class       WC_Email_Customer_On_Hold_Order
 * @version     2.6.0
 * @package     WooCommerce/Classes/Emails
 * @author      WooThemes
 * @extends     WC_Email
 */
class WC_Email_Customer_On_Hold_Order extends WC_Email {
```

**Comment by claudiosmweb** [comment]
@smazur thanks
