### ISSUE TITLE
How To Show In-Active Variations As Grey Out In Drop Down Menu 

### ISSUE THREAD

**Issue by askamin** [woothemes/woocommerce#11342]
## EXPLANATION OF THE ISSUE

Hi,
I am new to WC.
Lets say i have two attributes.

1. Color : green | red
2. Size : XL | XXL

Red Color Have only XL Size
Green Color Has only XXL Size.

Now, by default, when user select color green the second drop down only shows XXL size & XL size disappear as it is not assigned to color green.

I want to show inactive variations as Grey Out.(all possible variations)
See Example Below.

![a](https://cloud.githubusercontent.com/assets/20277770/16554118/4739bf6e-41e6-11e6-8d1c-04ba545abae1.PNG)
![b](https://cloud.githubusercontent.com/assets/20277770/16554119/47455608-41e6-11e6-9d81-1b06ffc7ff78.png)

Please help

**Comment by claudiosmweb** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

Please use the https://wordpress.org/support/plugin/woocommerce for general support
