### ISSUE TITLE
Remove default state selection on checkout

### ISSUE THREAD

**Issue by nrezane** [woothemes/woocommerce#11354]
## EXPLANATION OF THE ISSUE

I am having problem finding a solution on how to set the default selection of "state" during checkout to be "select an option" rather than selecting a default state.

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

Please the https://wordpress.org/support/plugin/woocommerce for general support
