### ISSUE TITLE
woocommerce_rest_invalid_shop_order_id

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#11352]
## EXPLANATION OF THE ISSUE

Retrieving orders by order id returns this error **woocommerce_rest_invalid_shop_order_id**

## STEPS TO REPRODUCE THE ISSUE

Get an order using the API with `$woocommerce->get( 'orders/order_id' );`

I am using WC 2.6.2

**Comment by claudiosmweb** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/8f62c322dde7c5d5df3cacc97d9163b9df65b197
