### ISSUE TITLE
WC_Abstract_Order->get_cancel_order_url() returning invalid URI

### ISSUE THREAD

**Issue by aianus** [woothemes/woocommerce#11355]
## EXPLANATION OF THE ISSUE

The [get_cancel_order_url](https://docs.woothemes.com/wc-apidocs/source-class-WC_Abstract_Order.html#2137-2155) function on a fresh install is returning an invalid URI (in my case, `http://coinbase-woocommerce-testing.alexian.us/cart/?cancel_order=true&#038;order=wc_order_577b0453cd8b5&#038;order_id=9&#038;redirect`)

## STEPS TO REPRODUCE THE ISSUE

1. Install Wordpress 4.5.3
2. Install WooCommerce Version 2.6.2
3. Install a custom payment gateway, for example, [coinbase-woocommerce](https://github.com/coinbase/coinbase-woocommerce)
4. When the function [get_cancel_order_url](https://docs.woothemes.com/wc-apidocs/source-class-WC_Abstract_Order.html#2137-2155) is called on the order as part of the checkout process, it returns an invalid URI, causing Coinbase's backend to reject the checkout.

The URI that the plugin is getting from that function is `http://coinbase-woocommerce-testing.alexian.us/cart/?cancel_order=true&#038;order=wc_order_577b0453cd8b5&#038;order_id=9&#038;redirect`

The expected URI, and the URI that was returned by previous versions of wordpress/woocommerce, is  `http://coinbase-woocommerce-testing.alexian.us/cart/?cancel_order=true&order=wc_order_577b0453cd8b5&order_id=9&redirect` or similar (no redundant encoded ampersands).

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://coinbase-woocommerce-testing.alexian.us
Site URL: http://coinbase-woocommerce-testing.alexian.us
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (2) ###

coinbase-woocommerce: by Coinbase Inc. – 2.1.2
WooCommerce: by WooThemes – 2.6.2

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.1 – 1.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
````

**Comment by claudiosmweb** [comment]
Not invalid, this returns a escape URL. See https://developer.wordpress.org/reference/functions/esc_url/

If you need an "unescaped" URL, you can use `$order->get_cancel_order_url_raw()`.

**Comment by aianus** [comment]
Thanks for the response. Using `$order->get_cancel_order_url_raw()` solved the problem.

As an aside, this is a very confusing default since obtaining the cancel URL for display purposes is a practically non-existent use case.

**Comment by claudiosmweb** [comment]
@aianus works when printing on HTML. Several plugins uses it and on Core too. I need to confess that I prefer to escape only before to print and not ever that we try to get the URL, but this is a legacy method, so no good try to change it now =/

**Comment by aianus** [comment]
Got it, thanks.
