### ISSUE TITLE
Post codes with a dash don't work in Shipping Zones

### ISSUE THREAD

**Issue by SukcesStrony** [woothemes/woocommerce#11359]
## EXPLANATION OF THE ISSUE

Post (ZIP) codes that have dashes (minus characters: -) don't work in Shipping Zones. Postal codes with dashes are common in some countries. For example: in Poland, all the post codes have a dash in them.

## STEPS TO REPRODUCE THE ISSUE

1. Add a zone with a shipping method and type in the following post code: 87-100
2. Check that the corresponding shipping method is not displayed on the Cart & Checkout pages when providing your post code as "87-100"
3. Change the post code in the shipping zones settings to 87100 and see that now the shipping methods are displayed correctly even if the code "87-100" is provided at the checkout.

## CURRENT WORKAROUND

Remove the dashes from the postal codes in the Shipping Zones settings.

**Comment by claudiosmweb** [comment]
On the frontend you need avoid any `-`. I did some changes in it, since Brazil uses `-` too. But we had to remove.
I'll check if we can do something, but no promises.

@mikejolley maybe we need to put a warning saying to not use formated values, leave without escapes, dashs and so on...

**Comment by SukcesStrony** [comment]
Looks like you could just strip the dashes at the top of the `wc_make_numeric_postcode( $postcode )` function definition inside `includes/wc-formatting-functions.php`. This would leave the dashes in the admin panel, but filter them out for processing. That would fully fix it as far as I see.

**Comment by claudiosmweb** [comment]
@SukcesStrony good catch!

**Comment by stuartduff** [comment]
Hey @claudiosmweb,

A customer has indicated to me today that after stripping our the **-** from postcodes this causes issues with shipping fulfillment software like ShipStation etc which can no longer validate customer addresses. 

The store owner then needs to goto their fulfillment software and add the dash back to the zip code in each individual order before the address is validated and they can print a label for postage.

The United States Postal Service introduced a dash for US zip codes so as to better group deliveries.

> The basic 5-digit format was first introduced in 1963 and later extended to add an additional 4 digits after a dash to form a ZIP+4 code. The additional 4 digits help USPS more precisely group mail for delivery.

I feel we should follow the government postcode / zipcode  specifications on this one as it's causing issues outwith WooCommerce with order fulfillment's who do follow governmental standards.

**Comment by mikejolley** [comment]
@stuartduff WooCommerce does not support 9 digit zip codes, this is not a zones issue. Extensions like USPS cannot deal with them.

**Comment by claudiosmweb** [comment]
@stuartduff but this only remove while is checking against shipping zones. Don't save anything with this format in the database.

**Comment by MrFent** [comment]
I am that customer that @stuartduff mentioned. Before the introduction of shipping zones in woocommerce, the 5 zip + 4 system worked great, and I never had any issues. Now I have to go into my shipping fulfillment system and manually edit the address  and put the dash back in in for each order where a customer includes the extra 4 digits. I can't print my shipping labels until I do so.

**Comment by claudiosmweb** [comment]
@MrFent show me where is missing the `-`.

**Comment by tiffanyrenee** [comment]
Does a customer entering the zip+4 change how FedEx shipping plugin or Shipstation plugin work? We've had issues with customers getting error message that say there are no shipping options for them and we don't know why it's occuring. Wondering if enter zip+4 is the problem. Thanks!

**Comment by claudiosmweb** [comment]
Already fixed it, just waiting for a new release.

**Comment by MrFent** [comment]
This still isn't fixed. If a customer from the US puts a 9 digit zip code on the checkout page, he will get a notice that the zip code needs a dash. However, after putting a dash in the zip code and saving the order, the dash is missing from the order. This causes issues wit shipping fulfillment. Here's a screencast showing the issue. 

http://screencast.com/t/oZgfIoiMi

**Comment by claudiosmweb** [comment]
@MrFent "Already fixed it, just waiting for a new release."
