### ISSUE TITLE
Applying coupons using woocommerce rest api

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#11358]
I am registering order using woo commerce REST API.Order is successfully placed and is also reflected in admin dashboard.But the problem is when i add coupon lines in order the coupon amount is not registered in admin dashboard though its displaying applied coupon name.Hence the order amount calculation is displayed incorrect.

I am using woo commerce version 2.2.5 and API version is v3.
Below is order in put in json.

```
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;
use Automattic\WooCommerce\HttpClient\HttpClientException;


    $woocommerce = new Client(
    'baseurl', // Your store URL
    'ck', // Your consumer key
    'cs', // Your consumer secret
    [
        'version' => 'v3', // WooCommerce API version
		'verify_ssl'=>false,
    ]
);

$data = [
	'order' => [
	'payment_details' => [
		'method_id' => 'cod',
		'method_title' => 'Cash on Delivery',
		'paid' => true,
	],
	'billing_address' => [
		'first_name' => 'John1',
		'last_name' => 'Doe',
		'address_1' => '969 Market',
		'address_2' => '',
		'city' => 'San Francisco',
		'state' => 'CA',
		'postcode' => '94103',
		'country' => 'US',
		'email' => 'john.doe@example.com',
		'phone' => '(555) 555-5555'
	],
	'shipping_address' => [
		'first_name' => 'John',
		'last_name' => 'Doe',
		'address_1' => '969 Market',
		'address_2' => '',
		'city' => 'San Francisco',
		'state' => 'CA',
		'postcode' => '94103',
		'country' => 'US'
	],
	'customer_id' => 2,
		'line_items' => [
			[
				'product_id' => 96,
				'quantity' => 2
			]
	],
	'coupon_lines'=>
	[
		[
			'code'=>'wer',
			'id'=>128,
			'amount'=>'10.00',
			'discount'=>'10'
		]
	]
	]
];

echo ''.json_encode($woocommerce->post('orders', $data));
```
![couponissue](https://cloud.githubusercontent.com/assets/15122702/16577801/e41ae848-42b4-11e6-9536-469ec58026f8.png)

Also i have attached screenshot below that displays that "wer" coupon code is applied but discount
is not applied.So can you please tell me if i m doing something wrong or is there any way to do this.

I had posted issue same on
https://github.com/woothemes/woocommerce/issues/11336

but it was closed. Please explain me why it was closed as i m not able to find solution for this.
 I have  implemented according to documentation but not able to figure it out what's causing this.
If i am not clear enough to explain my issue please just leave a comment before closing the topic.

Waiting for answer.
Thank you.

**Comment by claudiosmweb** [comment]
You don't apply coupons on REST API, you can register the coupon, but WooCommerce still don't have anything to apply or calculate the value of a coupon.

**Comment by claudiosmweb** [comment]
Logged in our roadmap for voting: https://trello.com/c/wdRNLlIA/92-calculate-coupons-using-rest-api

**Comment by pkhutal** [comment]
Thanks @claudiosmweb for your feedback.

**Comment by Lewiscowles1986** [comment]
To anyone that cares about the low-level how-to there are two pieces of meta-data `_order_total` and `_cart_discount`, currently in the postmeta table with a `post_id` equal to that of the order's `$post.ID`

You could increment the `_cart_discount` meta by the coupon amount using bcadd, then use bcsub (requires bcmath) and save the post meta's. Of course it's less than ideal, I'm sure others would be able to point out the woo-way, but for now at least it works

**Comment by enricodeleo** [comment]
I tried to figure out how to accomplish this task on a custom endpoint but got stuck at some point. As far as I can see, every discount/coupon related task is done on the cart, not order, so I tried to expose the cart to rest but:

At the moment every function related to cart (in WC_Cart) is based on the assumption that the actor is the customer and the primary persistence is its session. 

I built a custom endpoint that extends WC_Cart and got both get and add products working (bypassing $cart_contents and persisting the cart directly to user meta). I also assumed that the actor here is a shop manager that passes a target user ID. 

Unfortunately it seems to hacky and I think we should rethink the entire WC_Cart class.

Furthermore:
at first, I tried to act as an user with wp_set_current_user but this technique doesn't work and if I try to login the user programatically as shown here https://developer.wordpress.org/reference/functions/wp_set_current_user/#user-contributed-notes it breaks the shop manager authentication.

Any ideas?

**Comment by basanthalluri** [comment]
@claudiosmweb, Do you have any solution for coupons discount calculation in total?

@enricodeleo, Are you able to resolve the issue? 

I am also struck at the same point in my project. I hope some one could found the solutions for discount calculation in orders section.

**Comment by enricodeleo** [comment]
@basanthalluri I didn't check if something changed with WC 2.7 but as far as I could see the "right" way is to expose cart's methods to a custom endpoint. It is possible since the cart is smart enough to save/retrieve cart data to/from the database in addition to cookies, but some method needs to be rewritten because it assumes that the user is on the website with a browser and a session.

Another way is to check the coupon details with the builtin coupon endpoint and calculate everything on the client, but you need to reimplement all the coupon logics and take care of any coupon extension that may introduce new conditions.

A third way could be to hook orders via api, do everything on the backend and thrown an error if the coupon is not valid. I can imagine (not tested, just thinking) this basic flow:
the user goes to checkout -> save order as pending -> hook on save_post with type order -> create  a cart on the fly and apply the coupon if any -> if the coupon fails remove the coupon item -> if the client known it was trying to apply a coupon it could show an error as soon as the order comes back without a coupon line

**Comment by basanthalluri** [comment]
@enricodeleo  I am using the REST API's in mobile application. 

Here is i am passing in the body for create order including coupons.

{
  
 "payment_method": "cod",
    "payment_method_title": "Direct Bank Transfer",
    "set_paid": true,
   
    "billing": {
      "first_name": "Ram",
      "last_name": "Kumar",
      "address_1": "969 Market",
      "address_2": "",
      "city": "Vsp",
      "state": "AP",
      "postcode": "530016",
      "country": "India",
      "email": "hussain.s@stellentsoft.com",
      "phone": "(986) 444-5555"
    },
    
    "shipping": {
      "first_name": "Ram",
      "last_name": "Kumar",
      "address_1": "969 Market",
      "address_2": "",
      "city": "Vsp",
      "state": "AP",
      "postcode": "530016",
      "country": "India"
    },
    "line_items": [
      {
        "product_id": 263,
        "quantity": 1,
        "meta": [
          {
            "key": "Camper Name",
            "label": "Camper Name",
            "value": "Hussian"
          }
        ]
      }
    ],
    "fee_lines": [
		{
		"title": "Extra Fee",
		"total": 100,
		"tax_class":"reduced-rate",
		"tax_status":"taxable",
		"name":"Mahesh"
		}
	],
	
	"coupon_lines": [{
		"id":4334,
	   "code":"cstore",
	   "discount":5
	}],
    "shipping_lines": [
      {
        "method_id": "flat_rate",
        "method_title": "Flat Rate",
        "total": 2
      }
    ]
}

Here is the response i am getting from REST API

{
  "id": 2161,
  "parent_id": 0,
  "status": "processing",
  "order_key": "wc_order_58994c4f836f7",
  "number": 2161,
  "currency": "USD",
  "version": "2.6.13",
  "prices_include_tax": false,
  "date_created": "2017-02-07T04:25:52",
  "date_modified": "2017-02-07T04:25:52",
  "customer_id": 0,
  "discount_total": "0.00",
  "discount_tax": "0.00",
  "shipping_total": "2.00",
  "shipping_tax": "0.00",
  "cart_tax": "0.00",
  "total": "104.00",
  "total_tax": "0.00",
  "billing": {
    "first_name": "Ram",
    "last_name": "Kumar",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "Vsp",
    "state": "AP",
    "postcode": "530016",
    "country": "India",
    "email": "hussain.s@stellentsoft.com",
    "phone": "(986) 444-5555"
  },
  "shipping": {
    "first_name": "Ram",
    "last_name": "Kumar",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "Vsp",
    "state": "AP",
    "postcode": "530016",
    "country": "India"
  },
  "payment_method": "cod",
  "payment_method_title": "Direct Bank Transfer",
  "transaction_id": "",
  "customer_ip_address": "192.241.252.248",
  "customer_user_agent": "WooCommerce API Client-Node.js/1.4.2",
  "created_via": "rest-api",
  "customer_note": "",
  "date_completed": "2017-02-07T04:25:52",
  "date_paid": "2017-02-07 04:25:53",
  "cart_hash": "",
  "line_items": [
    {
      "id": 5172,
      "name": "Woo Single",
      "sku": "654613612",
      "product_id": 263,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "price": "2.00",
      "subtotal": "2.00",
      "subtotal_tax": "0.00",
      "total": "2.00",
      "total_tax": "0.00",
      "taxes": [],
      "meta": []
    }
  ],
  "tax_lines": [],
  "shipping_lines": [
    {
      "id": 5173,
      "method_title": "Flat Rate",
      "method_id": "flat_rate",
      "total": "2.00",
      "total_tax": "0.00",
      "taxes": []
    }
  ],
  "fee_lines": [
    {
      "id": 5174,
      "name": "Mahesh",
      "tax_class": "reduced-rate",
      "tax_status": "taxable",
      "total": "100.00",
      "total_tax": "0.00",
      "taxes": []
    }
  ],
  "coupon_lines": [
    {
      "id": 5175,
      "code": "cstore",
      "discount": "5.00",
      "discount_tax": "0.00"
    }
  ],
  "refunds": [],
  "_links": {
    "self": [
      {
        "href": "http://campstore.myworkdemo.com/wp-json/wc/v1/orders/2161"
      }
    ],
    "collection": [
      {
        "href": "http://campstore.myworkdemo.com/wp-json/wc/v1/orders"
      }
    ]
  }
}

After applying coupons also i am not getting any value in discount_total. How can i resolve the issue? I don't have any core experience in word press. Please suggest me.

**Comment by enricodeleo** [comment]
@basanthalluri I know it's the whole point here :) You need to implement as per my suggestions above. 
As @claudiosanches already said WC apis are not going to do any calculation for you, they just register a coupon you either need to do your math on the consumer side or via a custom endpoint.

**Comment by Lewiscowles1986** [comment]
@enricodeleo could you do us a favor and label `bug`, `enhancement`, `wontfix` then close if it's decided?

**Comment by enricodeleo** [comment]
@Lewiscowles1986 I'm sorry I do not have write access. I won't say its a bug here it's more related to the design.  As I pointed out back in September everything related to coupon discounts is done within the cart and this class basically doesn't account stateless scenarios.

**Comment by Lewiscowles1986** [comment]
Happy enough to drop calling it a bug if it helps tag the issue. Ha

**Comment by mikejolley** [comment]
It's not a bug, it s won't fix **UNTIL** we add discount calculation classes which are planned for 2.8 milestone.

**Comment by basanthalluri** [comment]
Can i know when 2.8 milestone will be released?

**Comment by mikejolley** [comment]
Later in the year. Development has not begun on that yet.

**Comment by basanthalluri** [comment]
@mikejolley, orderby and order parameters working in list products API?

**Comment by zfalen** [comment]
For reference, what I've ended up doing to circumvent the issue is to apply a discount code using the `coupon_lines` field, then issuing a `refund` for the relevant amount. The 'reason' line is given a short description that explicitly includes the refund code for reference.  

Hacky way to do things but it accomplishes what we needed for now.

**Comment by vasikgreif** [comment]
Any news on this one?

**Comment by claudiosanches** [comment]
Probably possible on our new REST API v3.

**Comment by vasikgreif** [comment]
Hello, it looks that WC 3.2 made it possible to apply coupons programmatically. 

https://woocommerce.wordpress.com/2017/08/24/coupon-and-cart-improvements-in-3-2/

Any news on when we can see this implemented in the API?

**Comment by GoldAndLink** [comment]
Still no updates about applying coupons with the REST API however I found another hacky way to do things (less hacky than using refund):

you can set discount_line to keep a track about your coupon but the real way to change the discount field is changing the total of each items when you set your data object for the creation of the new order using REST API ( WooCommerce.post('orders', data..... ).

Basic example:
- 1 coupon with a value of $20
- 1 item in the cart with a value of $100

Before creating your order you will have to set the total field of this item to $80 ($100 - $20).
The subtotal remain the initial amount.
```
let payload = {
      customer_id: user.id,
      customer_note: null,
      billing: customerInfo,
      line_items: this.getItemsCart(),
    }

getItemsCart() {
    const {cartItems} = this.props;
    let items = []
    for (var i = 0; i < cartItems.length; i++) {
      const cartItem = cartItems[i]

      let item = {
        product_id: cartItem.product.id,
        quantity: cartItem.quantity,
        total: cartItem.total // The magic happens here, you apply the coupon to your item's price
      }
      items.push(item)
    }
    return items;
  }
```

The subtotal field of the item, the discount field visible in WC interface and the discount_total field of the order will be calculate automatically

<img width="1377" alt="skitch" src="https://user-images.githubusercontent.com/2128970/31012391-ff396e60-a4e7-11e7-94a4-310ab3f864ac.png">


You can’t modify the discount_total field directly because it’s a read-only field https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

Good luck

**Comment by shubhamsharma95** [comment]
Problem is not in "coupon_lines" it is in "line_items"
add "total", "price" and "subtotal" 
'line_items' => array(
            array(
                'product_id' => 35,
                'quantity' => 1,
                'total' => 500,
                'price' => 1000,
                'subtotal' => 1000
            )
        ),

or check other parameters 
https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by vasikgreif** [comment]
@claudiosanches I can see this is closed, but I *think* this should be possible now considering the changes in WC 3.2. 

Any chance to get this fixed, Claudio?

**Comment by claudiosanches** [comment]
@vasikgreif this is not a "fix" anymore, this should be a feature in v3.

**Comment by vasikgreif** [comment]
@claudiosanches Got your point. Any timeframe on this feature?

**Comment by claudiosanches** [comment]
There is no date to release it yet, but you can follow all development on https://github.com/woocommerce/wc-api-dev

**Comment by Mr-AjayM** [comment]
@shubhamsharma95 I have a look into this https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties there is the "discount_total" parameter but it is ready only. so, can you please explain in details.

**Comment by mikejolley** [comment]
Discount totals are calculated automatically and don't need to be manually set.
