### ISSUE TITLE
Meta data saved at woocommerce_pre_payment_complete not output in completed order emails

### ISSUE THREAD

**Issue by Einkoro** [woothemes/woocommerce#11353]
When using ``wc_add_order_item_meta`` to save data within the hook ``woocommerce_pre_payment_complete`` the customer order completed emails are missing the meta data lines. L49 of templates/emails/email-order-items.php output is as follows:
```
<br/><small></small>
```

However when I use the resend order emails action for completed order from wp-admin the email sends with the meta data as expected:
```
<br/><small>License Key(s):
ECJK...VQRX</small>
```

The orders consists entirely of virtual / downloadable products and is completed immediately as expected without being set to processing first. Looking through the code it seems the meta data should be saved before the email is sent but the behaviour seems to indicate otherwise.

**Comment by mikejolley** [comment]
There is some caching in core which stores meta and doesn't update it before send under certain circumstances. We're working on the meta/data system in https://github.com/woothemes/woocommerce/pull/11208 for the next release to avoid issues such as this.
