### ISSUE TITLE
Wrong number of decimals

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#11368]
Seems like that we need to do some fixes to work with a lot of decimals, like is needed for Bitcoin.

![screenshot from 2016-07-05 20-24-08](https://cloud.githubusercontent.com/assets/1264099/16602933/7a67aa32-42ee-11e6-88c2-93e98c5795fd.png)

https://wordpress.org/support/topic/total-number-of-decimals-10?replies=2

**Comment by claudiosmweb** [comment]
Related to `$this->define( 'WC_ROUNDING_PRECISION', 4 );`

**Comment by franticpsyx** [comment]
@claudiosmweb A heads-up that this is causing issues to any extension that is using the `WC_ROUNDING_PRECISION` constant. Got at least one example. 

Not sure why solving https://wordpress.org/support/topic/total-number-of-decimals-10?replies=2 requires getting rid of the `WC_ROUNDING_PRECISION` constant.
