### ISSUE TITLE
Checkout / custom checkbox validation errors not highlighted

### ISSUE THREAD

**Issue by krbvroc1** [woothemes/woocommerce#11360]
#9464 made sure that custom checkboxes added to the checkout page were validated. However the current checkout.js contains:
```
// Inline validation
this.$checkout_form.on( 'blur change', '.input-text, select', this.validate_field );
```
which does not include the checkbox fields so they end up not being validated despite being marked required when added via `woocommerce_form_field()` to the checkout form.

**Comment by claudiosmweb** [comment]
@krbvroc1 I tested and seems to be working fine now, let me know if you have a chance to test too.
Thanks for report this.

**Comment by krbvroc1** [comment]
@claudiosmweb I just tested and it works, thank you.

**Comment by krbvroc1** [comment]
@claudiosmweb - After clearing cache of my browser I find that if I goto checkout page and simply hit 'Place Order' the checkbox form field is not fixed. I think you may have missed a part of the fix in checkout.js.

There are two places in there such as line 314 and line 443:
```
// Lose focus for all fields
$form.find( '.input-text, select' ).blur();
```
```
wc_checkout_form.$checkout_form.find( '.input-text, select' ).blur();
```
I think the checkbox needs to be added to those so blur is triggered like the select and text areas.

**Comment by claudiosmweb** [comment]
@krbvroc1 now I think that is all covered.

**Comment by krbvroc1** [comment]
@claudiosmweb Yes that is it - tested again and it works - thanks.
