### ISSUE TITLE
wc_get_account_endpoint_url confusion

### ISSUE THREAD

**Issue by krbvroc1** [woothemes/woocommerce#11365]
I would expect wc_get_account_endpoint_url() to provide the URL for the new my account endpoints.
If I use wc_get_account_endpoint_url('downloads'), it only works from the myaccount page. If used on a different page such as the homepage, it produces 'www.site.com/downloads' rather than 'www.site.com/myaccount/downloads'.

I think this is bug and wc_get_account_endpoint_url() should be calling
`wc_get_endpoint_url( $endpoint, "",  wc_get_page_permalink( 'myaccount' ));`

**Comment by claudiosmweb** [comment]
The initial idea is only to return the path, but since the name is `wc_get_account_endpoint_url()` it's better return the full URL.
