### ISSUE TITLE
Woocommerce Checkout AJAX issue with BuddyPress Ajax

### ISSUE THREAD

**Issue by kubko32459** [woothemes/woocommerce#11364]
The only way how to fix is to disable ajax woocommerce checkout.

```
<?php
/**
 * Disable checkout script, because of conflict BuddyPress and Woocommerce Ajax conflict.
 */
function disable_checkout_script(){
    wp_dequeue_script( 'wc-checkout' );
}
add_action( 'wp_enqueue_scripts', 'disable_checkout_script' );
?>
```

**Comment by claudiosmweb** [comment]
Tested and I did not see any problem.

**Comment by kubko32459** [comment]
If you are using this script, then it works fine, but without there is problem, install default theme, buddypress plugin and woocommerce, go to checkout and you have got a problem.
