### ISSUE TITLE
MyAccount Tabs - Active tab for CSS styling

### ISSUE THREAD

**Issue by silicondales** [woothemes/woocommerce#11374]
## EXPLANATION OF THE ISSUE

WC 2.6.2 installed, and attempting to style tabs in my account.

Appears there is no "active" tab.

## STEPS TO REPRODUCE THE ISSUE

Install wc2.6
Visit myaccount
Check the css..

## SYSTEM STATUS REPORT
N/A - present on any install.

Am going to work on this one - client in this case doesn't mind much.

Also feel free to point out any errors - not looked into styling the new tabbed my account until now; I could easily have missed the simplest of things.

**Comment by claudiosmweb** [comment]
We display an `is-active` class. See: https://github.com/woothemes/woocommerce/blob/master/includes/wc-account-functions.php#L123-L151

**Comment by silicondales** [comment]
> I could easily have missed the simplest of things.

Sorry @claudiosmweb . I very much thought this was case. Doesn't help that this job is to rework a truly nightmarish custom theme.
