### ISSUE TITLE
Woocommerce 2.6 Variable products now say "Read more" 

### ISSUE THREAD

**Issue by L-Rock** [woothemes/woocommerce#11375]
## EXPLANATION OF THE ISSUE

Woocommerce 2.6.1 and 2.6.2 have same issue - Variable products do not heave "select options" buttons in store anymore. They now say "Read more". 
I found that if I go into each product in the WP backend and hit save, then the buttons converts back to select options. However, it is not feasible for me to do this one by one for each variable product as we have over a 1000 products in the store. 

## STEPS TO REPRODUCE THE ISSUE

Read above

Screenshot:

![screen shot 2016-07-06 at 11 48 17 am](https://cloud.githubusercontent.com/assets/20211266/16624697/b824cee6-436f-11e6-94de-fd2192838534.png)

## SYSTEM STATUS REPORT

```
WC Version:		2.6.2
Log Directory Writable:		 /nas/content/staging/eurosport/wp-content/uploads/wc-logs/
WP Version:		4.5.3
WP Multisite:		–
WP Memory Limit:		512 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache
PHP Version:		 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size:		200 MB
PHP Time Limit:		3600
PHP Max Input Vars:		9000
cURL Version:		7.35.0, OpenSSL/1.0.1f
SUHOSIN Installed:		–
Max Upload Size:		200 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.2
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	


Settings
Force SSL:		–
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		
WC Pages
Shop Base:		#9 - /shop/
Cart:		#10 - /cart/
Checkout:		#11 - /checkout/
My Account:		#12 - /my-account/
Taxonomies
Product Types:	 	composite (composite), external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Paralax Custom
Version:		1.2
Author URL:		
Child Theme:		
Parent Theme Name:		Genesis
Parent Theme Version:		2.1.2
Parent Theme Author URL:		http://www.studiopress.com/
WooCommerce Support:		 Not Declared
Templates
Overrides (WooCommerce):	 	parallax-pro/woocommerce/archive-product.php

```

**Comment by claudiosmweb** [comment]
All that products are in stock?

**Comment by L-Rock** [comment]
Yes they are.

**Comment by MattyLB** [comment]
If you're using Booster for WooCommerce (formerly WooCommerce JetPack) or a similar WC modifying plugin, these have features that change the "add to cart" button text and I know from experience that "Booster" defaults to "Read More" for certain types of products.

Just to prove it's not another plugin causing this, can you disable all other "woocommerce" related plugins, and just keep the actual WC plugin active and see if this still occurs? If it does, it could also be a theme issue. In that case, switch to the 2016 theme to test - if it's fine, contact your theme developer.

Hope that helps! :)

**Comment by L-Rock** [comment]
Hi MattyBL, 
I disabled all of the plugins and the problem still happened. I also tried activating 2 other themes and again the problem persisted, so it looks to me that it is a woocommerce issue.

**Comment by adamkinder** [comment]
I had the same issue. I just targeting the text and displayed what I wanted. 

`add_filter( 'woocommerce_product_add_to_cart_text' , 'custom_woocommerce_product_add_to_cart_text' );

/**
 * custom_woocommerce_template_loop_add_to_cart
*/
function custom_woocommerce_product_add_to_cart_text() {

	global $product;
	
	$product_type = $product->product_type;
	
	switch ( $product_type ) {
		case 'external':
			return __( 'Buy product', 'woocommerce' );
		break;
		case 'grouped':
			return __( 'View products', 'woocommerce' );
		break;
		case 'simple':
			return __( 'Add to cart', 'woocommerce' );
		break;
		case 'variable':
			return __( 'Select options', 'woocommerce' );
		break;
		default:
			return __( 'Read more', 'woocommerce' );
	}
	
}`

**Comment by mikejolley** [comment]
This is based on:

```
$text = $this->is_purchasable() && $this->is_in_stock() ? __( 'Select options', 'woocommerce' ) : __( 'Read more', 'woocommerce' );
```

So if your variable product has no variations or is classes out of stock, it will show read more. If you imported your products, there was likely a problem with the data itself.

No bug with new, valid variable products.

**Comment by andrewjohnstrong** [comment]
It may not be a bug but it's definitely not desirable to have a product button say "read more". That's relevant for a blog post but not a product. There should be flexibility for the admin to change this text to "More Details" or "Select Options" etc.
