### ISSUE TITLE
Can no longer have cart and checkout on same page.

### ISSUE THREAD

**Issue by jacobraccuia** [woothemes/woocommerce#11371]
Up to 2.6.1, I was able to successfully have the cart and checkout on the same page.  Changes in 2.6.2 removed the code in cart.js that helped make this possible.

Is there a different solution to getting the cart to work?

It seems to stop showing filters after the main cart section is shown.  I don't see the sub total or total area and the proceed to checkout button.

**Comment by mikejolley** [comment]
Why show two totals areas in this setup? Pointless.

**Comment by jacobraccuia** [comment]
I removed the order review from the checkout shortcode:

remove_action('woocommerce_checkout_order_review',
'woocommerce_order_review', 10);

and I hid the entire woocommerce checkout div, and when you click “proceed
to checkout” i would fade the div in.

I guess I can try to remove the action I have above and modify the template
a bit so I can still “proceed to checkout” but within the scope of 2.6.2

On July 6, 2016 at 9:42:24 AM, Mike Jolley (notifications@github.com) wrote:

Why show two totals areas in this setup? Pointless.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/woothemes/woocommerce/issues/11371#issuecomment-230774493>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEcK9OQEP7-YgcpWOGOolK0UopWPJ5Q_ks5qS7C9gaJpZM4JFyXh>
.

**Comment by jacobraccuia** [comment]
Actually, scratch that.  The totals I was removed are at the very bottom of
the checkout page, and it doesn’t make sense to only show the totals after
you put in your shipping address, etc.  Also, I can’t see a way to edit the
shipping methods if I’m only showing the totals in the checkout section.

Maybe I’m missing something?



On July 6, 2016 at 9:42:24 AM, Mike Jolley (notifications@github.com) wrote:

Why show two totals areas in this setup? Pointless.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/woothemes/woocommerce/issues/11371#issuecomment-230774493>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEcK9OQEP7-YgcpWOGOolK0UopWPJ5Q_ks5qS7C9gaJpZM4JFyXh>
.

**Comment by claudiosmweb** [comment]
This seems like custom code... if you need changes, you can send Pull Requests, but it does not seem like the kind of thing we should support the core.
