### ISSUE TITLE
WooCommerce product variations dropdown to display in shop loop

### ISSUE THREAD

**Issue by lukecav** [woothemes/woocommerce#11370]
woocommerce_variable_add_to_cart
http://hookr.io/functions/woocommerce_variable_add_to_cart/
https://docs.woothemes.com/wc-apidocs/function-woocommerce_variable_add_to_cart.html
https://docs.woothemes.com/wc-apidocs/source-function-woocommerce_variable_add_to_cart.html#962-982

woocommerce_dropdown_variation_attribute_options_args
http://hookr.io/filters/woocommerce_dropdown_variation_attribute_options_args/

Any idea, how it would be possible to display the product variations dropdown with add-to-cart function on the shop loop?

Thanks in advance.

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

For questions, please use the https://wordpress.org/support/plugin/woocommerce

**Comment by lukecav** [comment]
K

https://wordpress.org/support/topic/woocommerce-product-variations-dropdown-to-display-in-shop-loop?replies=1#post-8611169
