### ISSUE TITLE
Variable Products No Longer Showing In Stock Quantity on WP-ADMIN >Products >Products dashboard. 

### ISSUE THREAD

**Issue by nyrotica** [woothemes/woocommerce#11381]
## EXPLANATION OF THE ISSUE

Since updating to either the latest or one of the last few releases of Woocommerce, In Stock amounts for Variable Products are not showing in the WP-ADMIN/Woo dashboard Products page. Simple product quantities are showing fine next to the green In Stock text and the site is working fine and its definitely managing stock just fine for variable products, just now showing the amounts on the backend dashboard only on the live site. Tried switching themes to the default 2012 and 2015 to see if it was a theme conflict and it is not working in either of those themes either - so no theme conflict. 

## STEPS TO REPRODUCE THE ISSUE

Go to wp-admin and select >Products and then >Products from the menu. The green **"In Stock"** indicator used to say **x3** for stock amounts where stock is managed, whether those products were simple or variable. Now it shows a quantity in brackets **(3)** but only for simple products, not the variable products. 

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: N/A
Site URL: N/A
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.43 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 2000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (11) ###

Animate It!: by eLEOPARD Design Studios – 2.1.5
Black Studio TinyMCE Widget: by Black Studio – 2.2.10
Better WordPress reCAPTCHA: by Khang Minh – 2.0.3
Chase E-Xact Payment Gateway For WooCommerce: by Ishan Verma / Kermit Woodall – 1.0
Formidable: by Strategy11 – 2.02.03
Google Analytics by MonsterInsights: by MonsterInsights – 5.5
Kadence Slider: by Kadence Themes – 2.0.5
Really Simple SSL: by Rogier Lankhorst – 2.3.9
Simple Social Icons: by Nathan Rice – 1.0.13
Page Builder by SiteOrigin: by SiteOrigin – 2.4.10
WooCommerce: by WooThemes – 2.6.2

### Settings ###

Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Pinnacle Premium Child Theme
Version: 1.0
Author URL: http://kadencethemes.com/
Child Theme: ✔
Parent Theme Name: Pinnacle Premium
Parent Theme Version: 1.7.1
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: pinnacle_premium/woocommerce/archive-product.php
pinnacle_premium/woocommerce/content-product.php
pinnacle_premium/woocommerce/content-product_cat.php
pinnacle_premium/woocommerce/content-single-product.php
pinnacle_premium/woocommerce/loop/loop-end.php
pinnacle_premium/woocommerce/loop/loop-start.php
pinnacle_premium/woocommerce/loop/rating.php
pinnacle_premium/woocommerce/loop/sale-flash.php
pinnacle_premium/product-searchform.php
pinnacle_premium/woocommerce/single-product/add-to-cart/variable.php
pinnacle_premium/woocommerce/single-product/product-image.php
pinnacle_premium/woocommerce/single-product/product-thumbnails.php
pinnacle_premium/woocommerce/single-product/related.php
pinnacle_premium/woocommerce/single-product/up-sells.php
pinnacle_premium/woocommerce/single-product.php
pinnacle_premium/woocommerce/taxonomy-product_cat.php
pinnacle_premium/woocommerce/taxonomy-product_tag.php

````

**Comment by jonnyvaughan** [comment]
According to a comment in the source, this was intentionally removed in 2.6 to avoid confusion:
https://github.com/woothemes/woocommerce/blob/96c9dcf77702af6ef4baef4413336ee0aebedc82/includes/admin/class-wc-admin-post-types.php

> Line 410: 	// If the product has children, a single stock level would be misleading as some could be -ve and some +ve, some managed/some unmanaged etc so hide stock level in this case.

The good news, is that a filter was added called woocommerce_admin_stock_html. I've added it back to our sites that needed this with the following filter function that can go in functions.php:

`
add_filter( 'woocommerce_admin_stock_html', 'tmt_show_variation_stock_level', 10, 2 );

function tmt_show_variation_stock_level( $stock_html, $the_product ) {

	if( $the_product->managing_stock() ) {

		$stock_html .= ' (' . $the_product->get_total_stock() . ')';

	}

	return $stock_html;

}
`

**Comment by nyrotica** [comment]
Thanks so much for this. I am using a child theme and tried adding it to the functions.php within the child theme. What is does is double up the bracketed stock amount on the Simple Products - so they look like this "In Stock (6) (6)" but doesn't seem to want to add any amounts to the Variable Products. Any thoughts on this? Your assistance is very much appreciated!

**Comment by jonnyvaughan** [comment]
I've tweaked the code a little to stop it doubling up on Simple Products and fixed an issue that wasn't showing the stock values if you weren't managing it at product level as well. Give it a try:

```
add_filter( 'woocommerce_admin_stock_html', 'tmt_show_variation_stock_level', 10, 2 );

function tmt_show_variation_stock_level( $stock_html, $the_product ) {

	if( sizeof( $the_product->get_children() ) ) {

		$stock_html .= ' (' . $the_product->get_total_stock() . ')';

	}

	return $stock_html;

}
```

**Comment by nyrotica** [comment]
You are a star! Thank you!

**Comment by claudiosmweb** [comment]
If the product has children, a single stock level would be misleading as some could be -ve and some +ve, some managed/some unmanaged etc so hide stock level in this case.

That's why we changed it.

**Comment by BillKarkavos** [comment]
If the product has children (aka variations) then I doubt that some of them are stock managed and some not - in most cases the variations are either managed or not - haven't seen any case so far that some variations of the same product needed to be stock managed and some not! 

In any case removing this very useful feature is not a good decision as there is really no other place to see the total stock of a variable product with ease. 

Reports > Stock are not showing the total, same goes for the stock management plugin extension.

to clarify more >

on WooCommerce 2.5.2,
when enabling stock management at product level –> set this to 0,
then defining stock for each product variation,
eg. Size Small 2 items, Size Medium 3 items, and Size Large 4 items,
the total stock quantity of 9 WAS INDEED showing next to “In stock” in the Products Page.

That was such a useful feature – more useful than going to Reports > Stock

**Comment by dgloveruk** [comment]
Hi Jonny, I had this problem too, my products are sold in different pack quantities so the variations are just different deductions with the product having the total stock.  So I am using the standard inventory tab in the product and the variations have deduct from total with an amount to deduct.
When I used your code the output was blank.  Should it have worked in my scenario or was this really only going to work for people managing stock at variation level?
Thanks!

**Comment by j4ck89** [comment]
Hi, I have two variations and I would like to 'wp-admin - products' see the stock divided by variations. it's possible?
Example:
**Product Name**   -   **Stock**                         -   **Price**
Product No.1     -   no.1 Variation  =   2  -      $
                          - no.2 Variation  =   5  -      $
Product No.2    -   no.1 Variation   =   8  -      $
                         - no.2 Variation  =    9  -      $

**Comment by nwmcinc** [comment]
The Filter above is great. I'm having a problem where a product is not showing on the category page, well multiple products when they have the main inventory 0 and variations for example 9 instock.  It was only after the Woocommerce 3.0 update that some product with inventory in the variations stopped showing on the outside of the site.

Is there a way for this filter so some how update the woocommerce loop to reconize that there is actually inventory on the product?

**Comment by eduardoalfaro** [comment]
@jonnyvaughan thank you sooooooo much! ;-D
May I ask you a question, if you do not mind? It will be any way to have, the variations name with its stock, in the same column $stock_html per line... so you will have a total stock, and then, in the same colun, per line, the variation name and its stock. ;-D Thank you so much!!!
