### ISSUE TITLE
Certificate configuration error on woocommerce.com

### ISSUE THREAD

**Issue by daniel-mueller-3w-media-de** [woothemes/woocommerce#11389]
## EXPLANATION OF THE ISSUE

The server listening on port 443 of woocommerce.com is configured incorrectly and offers an SSL certificate that does not match the server name. This affects the URL 'https://www.woothemes.com/wc-api/product-key-api?request=ping&network=0' (which redirects to 'https://woocommerce.com/wc-api/product-key-api?request=ping&network=0'), used in your system status report to check for 'Remote Get' functionality. This causes some of your clients to see the error message "wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: SSL: certificate subject name 'wooconf.com' does not match target host name 'www.woothemes.com'" in their system status report.

## STEPS TO REPRODUCE THE ISSUE

Use the command line tools of OpenSSL 1.0.1k or later and execute

 openssl s_client -servername www.woothemes.com -connect woocommerce.com:443

followed by

 openssl s_client -servername woocommerce.com -connect woocommerce.com:443

The first will see an SSL certificate with serial number 5073613136511137126, issued to wooconf.com, www.wooconf.com, wooslider.com & 2014.wooconf.com (none of which match woocommerce.com or www.woothemes.com). The second will see an SSL certificate with serial number 530420, issued to *.woocommerce.com and woocommerce.com. The second one is the correct certificate, but all clients without support for SNI (server name indication) will see the incorrect certificate.

## SYSTEM STATUS REPORT

wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: SSL: certificate subject name 'wooconf.com' does not match target host name 'www.woothemes.com'

**Comment by claudiosmweb** [comment]
Fixed 3 days ago: https://github.com/woothemes/woocommerce/commit/c59a5c0c31693eaa13375370f2ec9825c099d1b6
Way for a new release.

**Comment by daniel-mueller-3w-media-de** [comment]
There seems to be a misunderstanding. This can not be fixed by changing the software. The server delivers the wrong certificate. A fix would be to remove the old certificate from the server. Assuming that the old certificate is still needed, a different kind of fix would be to put each certificate on its own IP address. Currently 192.0.66.2 delivers 2 different certificates (wooconf.com & *.woocommerce.com) and delivers one of them (wooconf.com) even if the client sends random domain names like `naosdoiwerwe.com` (which definitely does not match `wooconf.com`). More importantly, it delivers this certificate if the client does not send a name at all (i.e. if the client has no support for SNI).

**Comment by claudiosmweb** [comment]
@daniel-mueller-3w-media-de we already fixed it too.

**Comment by daniel-mueller-3w-media-de** [comment]
Well, I'm not making this up. With `openssl s_client -connect 192.0.66.2:443` and `openssl s_client -servername naosdoiwerwe.com -connect 192.0.66.2:443` you can check that 192.0.66.2 still delivers the wooconf.com-certificate for random domains and for clients without SNI. Maybe you changed your DNS records, but your name server ns1.automattic.com still gives me the same answers for woothemes.com (192.0.66.3), woocommerce.com (192.0.66.2) and wooconf.com (192.0.66.2).

**Comment by mikejolley** [comment]
I've let @kloon know thanks.

**Comment by kloon** [comment]
We use ["Server Name Indentification" (SNI)](https://en.wikipedia.org/wiki/Server_Name_Indication) on our servers for SSL, it is possible that your server you are running this on are running an older operating system that does not support SNI, I'd suggest you contact your hosting provider and enquire about SNI support on your server.

**Comment by daniel-mueller-3w-media-de** [comment]
If SNI is mandatory for usage of WooCommerce, then it should probably be added to https://docs.woothemes.com/document/server-requirements/ (which is where I looked first, hoping to resolve the issue). Non-SNI-capable clients are not some rare oddity. curl added it in 2008, which means Red Hat Enterprise Linux 4 & 5 don't have it. RHEL 5 is still fully supported by Red Hat, RHEL 4 is at least in extended support. Given that you claim to be able to run on PHP 5.2.4 (released 2007), it is unlikely that all clients that fullfill your minimum requirements are SNI-capable.

Another possibility would be a different error message in the status report. Simply check for the used curl version and say something like "this feature only works with PHP curl extension 7.18.1 or newer". The current error message contains no useful information for the user that could guide him to a solution (i.e. more current curl extension).

**Comment by bazza** [comment]
This was an oversight in the woothemes.com -> woocommerce.com domain name change.  SNI is the default for all of our deployments.  woothemes.com has a configuration override to not use SNI.  This same configuration was not applied to woocommerce.com.  We will implement the change for woocommerce.com and update this issue when it's complete.   Sorry for the inconvenience.

**Comment by bazza** [comment]
This is now fixed: 

```

**Comment by bazza** [comment]
This is now fixed: 

```
$ openssl s_client -showcerts -connect woocommerce.com:443 < /dev/null 2>&1 | openssl x509 -noout -subject
subject= /CN=*.woocommerce.com
```

**Comment by daniel-mueller-3w-media-de** [comment]
Thank you. The system status report now shows green for the 'Remote Get' check.
