### ISSUE TITLE
Hold stock setting - time drop doesnt seem to work?

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#11388]
Under WooCommerce - Settings - Products - Inventory there is a setting:

`Hold Stock (minutes) 	Hold stock (for unpaid orders) for x minutes. When this limit is reached, the pending order will be cancelled. Leave blank to disable.`

Putting a time of 5 or 10 minutes in here, it stops customers from ordering regularly - but does not clear the carts after a period of time. It just seems to persist forever.

Thanks

**Comment by claudiosmweb** [comment]
>  but does not clear the carts after a period of time. It just seems to persist forever.
This was never the idea... This cancels "unpaid orders", if the products are still in the cart, then no order was made yet.

**Comment by shawaj** [comment]
Why have a time limit then?!?

It says it will hold stock for 10 minutes but out good holds it forever!
