### ISSUE TITLE
Feature request for BACS payments

### ISSUE THREAD

**Issue by ozoneboy** [woothemes/woocommerce#11391]
## EXPLANATION OF THE ISSUE

I have two payment options in the checkout: credit card and internet banking (BACS). Internet Banking is selected by default (no merchant fees).

If a user places an order with the Internet Banking option selected, the order is immediately accepted and they are taken to a confirmation page - there is no second chance: great for capturing sales but not so good for customers who actually wanted to pay by credit.

Unfortunately consumers are always in a rush and don't read, therefore they overlook the payment gateway options. I have found many customers expect to have a confirmation stage such as a pop-up "You have selected to pay by Internet Banking -> Continue -> Go Back".

Or perhaps a better option is to have the payment gateways set with no default pre-selected - so the user has to choose the correct option before proceeding.

Thoughts?

**Comment by claudiosmweb** [comment]
You can change the order, but this is a default and offline gateway... No integration with any back and the same if you choice PayPal for example, you'll need to do the order again.
