### ISSUE TITLE
Woocommerce widget

### ISSUE THREAD

**Issue by highacid** [woothemes/woocommerce#11398]
The woocommerce catgories widget does not display 3 rd level subcategories, any idea or workaround to make them visible?

**Comment by claudiosmweb** [comment]
![screenshot from 2016-07-11 10-01-44](https://cloud.githubusercontent.com/assets/1264099/16723638/83bab052-474e-11e6-8cbb-7ab13342fd0a.png)

> The woocommerce catgories widget does not display 3 rd level subcategories

Since when?

It's working fine. Not a WooCommerce issue.
