### ISSUE TITLE
Missing String 'Showing all %d results' in Language files 

### ISSUE THREAD

**Issue by alexgzb** [woothemes/woocommerce#11397]
Missing translation for the 'Showing all %d results' String found in the result-count.php file on line 39
This String is not available to translate in the POT file

**Comment by claudiosmweb** [comment]
It's a plural and works fine.

```
#: templates/loop/result-count.php:39
msgid "Showing the single result"
msgid_plural "Showing all %d results"
msgstr[0] ""
msgstr[1] ""
```
