### ISSUE TITLE
Use geoip php extention if available

### ISSUE THREAD

**Issue by Ninos** [woothemes/woocommerce#11392]
## EXPLANATION OF THE ISSUE

Seems that `class-wc-geolocation.php` is not checking for php-extension.

## STEPS TO REPRODUCE THE ISSUE

1. Install php extension 'geoip'
2. Enable
3. Have a look into woocommerce status page

## SYSTEM STATUS REPORT
GEOIP is not installed...

BTW: After upgrade the geoip database is not automatically downloaded into /uploads/ folder.

**Comment by claudiosmweb** [comment]
We don't use any "php-extension" for it. We have our own code for GEOIP.

> BTW: After upgrade the geoip database is not automatically downloaded into /uploads/ folder.

It's installed and works fine, check for permissions and if you can upload media on your WordPress correctly, but don't seems a valid report it.

**Comment by Ninos** [comment]
> It's installed and works fine, check for permissions and if you can upload media on your WordPress correctly, but don't seems a valid report it.

Permissions are fine. I'll check that and create a new issue if needed..
