### ISSUE TITLE
Checkout/My Account state field being force-reordered by address-i18n.js, overriding filtered order

### ISSUE THREAD

**Issue by indextwo** [woothemes/woocommerce#11399]
I re-ordered the standard address fields on the **My Account** page using `woocommerce_default_address_fields` to put the `postcode` field before the `state` field (so the last three fields in order were Postcode, State, Country). I then spent 3 hours tearing my hair out trying to figure out why the state and postcode field were still the wrong way around. I tried half a dozen different methods before realising it was being done on the fly by `address-i18n.js`, within the custom `'country_to_state_changing'` event, based on the store's set locale.

I understand that address field ordering is a PITA (as referenced in #2293), but I'd _really_ like some way to stop the jQuery force-reordering without dequeueing the entire `address-i18n.js` file. is a jQuery shiv my only way around this?

### Update

I stumbled across a [StackOverflow post](http://stackoverflow.com/questions/37902436/woocommerce-checkout-postcode-field-order) where someone seems to be having the same issue, and the answer also suggests trying to 'override' or 'write your own js' to deal with the effects of `address-i18n.js`. I have subsequently tried:

- to enqueue a script listening for the `'country_to_state_changing'` event that would swap the fields back... but it still gets enqueued before `address-i18n.js` (so the effect isn't seen);
- enqueuing my script with a dependency on `wc-address-i18n`, but it doesn't seem to work;
- enqueuing my script in a separate function with a ridiculously low priority (like, 99999), but it still doesn't get enqueued after `address-i18n`;
- Writing a `wp_footer` action for some inline jQuery. This _does_ get printed after `address-i18n`... but unfortunately, because all of my scripts are `defer`ed, the inline jQuery is undefined (even though it comes after the jQuery include).

I felt that adding in a jQuery shiv was a little hacky anyway, but it seems I can't even do that. Is there a WooCommerce-specific hook I could use (rather than regular `wp_enqueue_scripts`) to get around this?

**Comment by mikejolley** [comment]
We can re-look at this during #10672 - I'd suggest removing this logic completely and just basing field order on the base country to remove the confusion. Labels can still update based on country however, as that is still useful.

**Comment by spreadzz** [comment]
It's 2024 and this is still a issue. A lot of people want their Checkout page customized which requires re-arranging the fields. What is the reason of providing a hook to set the priority of fields if they are just going to be ignored and re-arranged with JavaScript... There should be a solution for this....

**Comment by LucaL1fe** [comment]
Any help, this issue drives me quazy and I find no way around because i manage everthing in php but get overwritten from some (for me) magic javascript, which makes no sense in my eyes. Fun fact I  have the problem with city and postcode but first name and last name works fine. its quazy....
