### ISSUE TITLE
When eligible for free shipping , flat fee options still available does no hide

### ISSUE THREAD

**Issue by proitex** [woothemes/woocommerce#11396]
When client is eligible for free shipping(for example $99.00 free shipping) , flat fee options still is available to be selected, does not hide from the options in the new version of woocomerce  WordPress 4.5.3 running storefront theme.

Parent Theme Name:		Storefront
Parent Theme Version:		2.0.5
Parent Theme Author URL:		https://woocommerce.com/
WP Version:		4.5.3

Thanks

**Comment by claudiosmweb** [comment]
Great, so is working fine, since we don't have anything by default to hide other shipping options when free shipping is available.

If you need do it, you can use this code: https://claudiosmweb.com/en/woocommerce-en/woocommerce-2-6-hide-others-shipping-methods-when-free-shipping-is-avaiable/
