### ISSUE TITLE
Users unable to register if existing user in multisite install on another site

### ISSUE THREAD

**Issue by DeanMarkTaylor** [woothemes/woocommerce#11409]
## EXPLANATION OF THE ISSUE
Users unable to register if user already exists in another site as a part of a WordPress multisite install.

Registering displays the message: "Error: An account is already registered with your email address. Please login."

Using the "lost password" page results in: "Invalid username or e-mail."

WooCommerce 2.6.1

## STEPS TO REPRODUCE THE ISSUE
1. On a multisite install create two sites, A) WooCommerce site B) A normal simple WordPress blog or another WooCommerce site.
2. Turn on "Enable registration on the "My Account" page" option for site A.
3. On site B create a normal user via WordPress admin and complete verification.
4. Log out of site B.
5. On site A attempt to register a user via the /my-account page.

### Expected result
- User to be registered with the Site A successfully.

### Actual result
- Displays the message: "Error: An account is already registered with your email address. Please login."

## Additional Notes
There is specific code in the function `wc_create_new_customer` which prevents existing accounts from being used:
```
		if ( email_exists( $email ) ) {
			return new WP_Error( 'registration-error-email-exists', __( 'An account is already registered with your email address. Please login.', 'woocommerce' ) );
		}
```

I believe there should be a code path where `add_user_to_blog` is called instead of `wp_insert_user`.

**Comment by rhurtik** [comment]
The issue is still there, I can reproduce is on a new WP vanilla installation WC  Version 3.1.1 |

**Comment by ThatGirlSlays** [comment]
Hello. This issue occurs for me as well. I have a multisite network and many users will create accounts on multiple subsites using the same user name or email. They should not be blocked from registering.
