### ISSUE TITLE
Successful Order Payment Generates an error message.

### ISSUE THREAD

**Issue by ohryan** [woothemes/woocommerce#11407]
When a customer pays for an order WooCommerce generates "success" message which is displayed as an error message. It reads `This order's status is "Complete" - it cannot be paid for. Please contact us if you need assistance."

To be clear, this is happening *after* a **successful** payment has been made. 

The affected code appears to be `wc_add_notice( sprintf( __( 'This order&rsquo;s status is &ldquo;%s&rdquo;&mdash;it cannot be paid for. Please contact us if you need assistance.', 'woocommerce' ), wc_get_order_status_name( $order->get_status() ) ), 'error' );`. Appearing on lines 121 and 168 of `includes/shortcodes/class-wc-shortcode-checkout.php` in version 2.5.5.

## Steps to reproduce
1. Create an order for a customer via the backend.
2. Have the customer pay for the order via checkout shortcode via their my-account page.
3. Customer user a valid payment method and the payment is successful.

**Comment by claudiosmweb** [comment]
Tested and works fine, maybe is an error with your payment method plugin.

**Comment by ohryan** [comment]
What is the expected behaviour? 
And is this error message supposed to appear? Displaying an error when an order is complete seems like a mistake in most circumstances.
