### ISSUE TITLE
Woocommerce 2.6.2 - Sales Tax is incorrectly being calculated in Washington State on sale items

### ISSUE THREAD

**Issue by eeisaacs** [woothemes/woocommerce#11402]
## EXPLANATION OF THE ISSUE

In WooCommerce 2.6.2 when an item is on sale, it calculates sales tax in Washington State as being on the sale/discounted amount instead of on the pre-sale/regular price amount.  As per RCW 82.08.010 (1)(b), sales tax is not supposed to be calculated on discounted amounts.  
Source: http://apps.leg.wa.gov/rcw/default.aspx?cite=82.08.010

## STEPS TO REPRODUCE THE ISSUE

Assuming you have a store in Washington, configure a WA state sales tax rate, add a product that has a regular price and a sales price.  Check out with that product in your cart.  The calculated sales tax should be based on the regular price of the product instead of the sales price of the product.  

With coupons it gets more complicated because it depends on the type of coupon.  If it's a manufacturer's coupon that will be credited to the seller, that amount is required to be passed onto the buyer, so in that case the buyer does not have to pay sales tax on that amount.  But if it's a seller's coupon (not a manufacturer's coupon) the sales tax is to be applied to the regular price.

I understand that Kansas has a similar law as well and more states are adopting this law.

## SYSTEM STATUS REPORT

Home URL: 		
Site URL: 		
WC Version: 		2.6.2
Log Directory Writable: 		
WP Version: 		4.5.3
WP Multisite: 		–
WP Memory Limit: 		256 MB
WP Debug Mode: 		–
WP Cron: 		
Language: 		en_US
Server Environment
Server Info: 		Microsoft-IIS/8.5
PHP Version: 		5.6.13
PHP Post Max Size: 		128 MB
PHP Time Limit: 		300
PHP Max Input Vars: 		10000
cURL Version: 		7.42.1, OpenSSL/1.0.1p
SUHOSIN Installed: 		–
Max Upload Size: 		128 MB
Default Timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte String: 		
Remote Post: 		
Remote Get: 		
Database
WC Database Version: 		2.6.2
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
Active Plugins (9)
Configure SMTP 	  	by Scott Reilly – 3.1
Contact Form 7 	  	by Takayuki Miyoshi – 4.4.2
Email Subscribers 	  	by Store Apps – 3.1.4
WPBakery Visual Composer 	  	by Michael M - WPBakery.com – 4.11.2.1
Slider Revolution 	  	by ThemePunch – 5.2.5.1
BigOne Plugin 	  	by theAlThemist – 1.2.2
WooCommerce 	  	by WooThemes – 2.6.2
YITH WooCommerce Compare 	  	by YITHEMES – 2.0.9
YITH WooCommerce Wishlist 	  	by YITHEMES – 2.0.16
Settings
Force SSL: 		–
Currency 		USD ($)
Currency Position 		left
Thousand Separator 		,
Decimal Separator 		.
Number of Decimals 		2
API
API Enabled: 		
WC Pages
Shop Base:		#1708 - /shop/
Cart:		#1709 - /cart/
Checkout:		#1710 - /checkout/
My Account:		#1711 - /my-account/
Taxonomies
Product Types: 	  	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name: 		BigOne
Version: 		1.3.0
Author URL: 		http://www.althemist.com
Child Theme: 		– If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 		
Templates
Overrides (WooCommerce): 	  	the-bigone/the-bigone/woocommerce/archive-product.php,
the-bigone/the-bigone/woocommerce/cart\cart.php,
the-bigone/the-bigone/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1,
the-bigone/the-bigone/woocommerce/content-single-product.php,
the-bigone/the-bigone/woocommerce/content-widget-product.php,
the-bigone/the-bigone/woocommerce/global\quantity-input.php,
the-bigone/the-bigone/woocommerce/global\sidebar.php,
the-bigone/the-bigone/woocommerce/global\wrapper-start.php,
the-bigone/the-bigone/woocommerce/loop\add-to-cart.php,
the-bigone/the-bigone/woocommerce/loop\loop-end.php,
the-bigone/the-bigone/woocommerce/loop\loop-start.php,
the-bigone/the-bigone/woocommerce/loop\orderby.php,
the-bigone/the-bigone/woocommerce/loop\pagination.php,
the-bigone/the-bigone/woocommerce/loop\price.php,
the-bigone/the-bigone/woocommerce/loop\sale-flash.php,
the-bigone/the-bigone/product-searchform.php version - is out of date. The core version is 2.5.0,
the-bigone/the-bigone/woocommerce/single-product\meta.php,
the-bigone/the-bigone/woocommerce/single-product\product-image.php,
the-bigone/the-bigone/woocommerce/single-product\product-thumbnails.php,
the-bigone/the-bigone/woocommerce/single-product\related.php,
the-bigone/the-bigone/woocommerce/single-product\review.php version 2.5.0 is out of date. The core version is 2.6.0,
the-bigone/the-bigone/woocommerce/single-product\short-description.php,
the-bigone/the-bigone/woocommerce/single-product\title.php,
the-bigone/the-bigone/woocommerce/single-product.php

**Comment by mikejolley** [comment]
I'm not sure how you can you charge *sales* tax on a price that wasn't used for the sale?

>  "Selling price" or "sales price" does not include: Discounts, including cash, term, or coupons that are not reimbursed by a third party that are allowed by a seller and taken by a purchaser on a sale

A "sale" price is not a coupon based discount. It is the product price as listed. Does not sound like this applies in that case?

You'd have to check with an advisor I assume to confirm this, but if this were a problem I guess you'd just have to change the regular price instead and not list is as a sale. This hasn't come up before so I am not certain if it's a real world problem or not.

Regarding coupons, the supported implementation is to calc tax AFTER the coupon is applied. Any other behaviour (e.g. calculating tax before the discount is applied) _would need to be done via a plugin or custom code_ if needed. There are some special coupon/discount plugins which apply taxes in this way, such as gift card type coupons.

This issue has nothing to do with the 2.6.2 release by the way. The above behavior has been present for a very long time.

**Comment by eeisaacs** [comment]
Mike, as per your post in 2014, it appears that the required functionality used to be present: 
https://woocommerce.wordpress.com/2014/12/12/upcoming-coupon-changes-in-woocommerce-2-3/

In Washington State (and I believe in Kansas base on other comments I've read on the subject) the sales tax must (by Washington State RCW law) be applied AFTER the sales tax is calculated.  This change that was made in version 2.3 made WooCommerce 2.3 no longer compatible with Washington State law.  But earlier versions apparently were in compliance.  

I understand that different areas have different requirements and I totally agree that it is BETTER if a state charged tax AFTER the order was totaled, but that is currently illegal in Washington State.  It would be ideal if WooCommerce out of the box could handle these different requirements based on the website's jurisdictions.  

Thanks

**Comment by mikejolley** [comment]
I did ask a few coworkers from Washington State area and for general sale products they'd never heard about what you're saying. Just to clarify, it sounded like you meant the regular/sale price fields - these are not coupon discounts. This logic never changed in 2.3.

**Comment by eeisaacs** [comment]
Mike,

Sorry.  I think you're correct.  It applies to manufacturer coupons, not in store coupons or sales.  Read the fine print on this ad.  It shows that Costco charges tax on presale prices when a manufacturer coupon is redeemed.  But that's not going to apply to me.  Sorry for the trouble. 
 https://www.patroneer.com/196737/costco/new-online-only-coupon-offers-start-today



Sent from my Windows Phone

-----Original Message-----
