### ISSUE TITLE
Error updating images, with the property image id

### ISSUE THREAD

**Issue by jairgarcia** [woothemes/woocommerce#11404]
I try to upload images of the products with the attribute image id for no duplicate with a rename the images.
var dataUpdate = {
images: [
  {
									id: idImage, (integer)
									src: url, (string)
									position: key (integer)
								}
]
}
I do the follow:

WooCommerce.put('products/' + id, dataUpdate, function(err, data, res) {}); 

But, the images no upload to the media library.

I appreciate any help.

Thanks.

**Comment by claudiosmweb** [comment]
If you are using ID, will try to assign for the image... So no image upload to the media library.
