### ISSUE TITLE
PayPal API credentials documentation link

### ISSUE THREAD

**Issue by macbookandrew** [woothemes/woocommerce#11408]
## EXPLANATION OF THE ISSUE

The PayPal API Credentials section has a link to PayPal documentation, but they’ve apparently updated it since this link was added.

Clicking the link leads to a page about NVP/SOAP API credentials including API certificates, which are not applicable to WooCommerce.

The link should instead be https://developer.paypal.com/webapps/developer/docs/classic/api/apiCredentials/#creating-an-api-signature

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/commit/7b6bd21810481cc7d11d71a99854217e34b7c0ef
