### ISSUE TITLE
Shipping Zone postal code ranges changed from - to ... but not updated

### ISSUE THREAD

**Issue by joelwills** [woothemes/woocommerce#11403]
Dupe of https://github.com/woothemes/woocommerce-table-rate-shipping/issues/44 but is a core issue.

For the shipping zones, the updater needs to convert - in ranges to ... as it breaks the old ranges entered using the table rate shipping plugin. 

Changes made in:
https://github.com/woothemes/woocommerce/commit/a02ac79339db02acd4a4737d40a5fc45058d4471#diff-c49e4a77afbd1a753435a745896942a2

**Comment by om4james** [comment]
I'm seeing the same problem.

After updating from WC 2.5.x to 2.6.x, our table rate shipping zones that use postcode ranges weren't migrated across to the new ```...`` range format that WC core now uses.

Here's a quick PHPMyAdmin screenshot illustrating the problem: 
![screen shot 2016-07-12 at 10 17 15 am](https://cloud.githubusercontent.com/assets/108233/16753145/e3d1acf4-4819-11e6-92df-57f3b036baa1.png)

(I manually re-saved the last zone after updating, but the other zones are still using `-` instead of `...`

**Comment by om4james** [comment]
Thanks for this @mikejolley!

Can you confirm whether or not this change runs when updating from 2.6.2 to 2.6.3?

It **looks** like it may only get run when first updating to 2.6.x?

There are probably quite a few sites that have already updated to 2.6.x in the last month or so, who have the issue with postcode ranges in their database, so when they update to 2.6.3, I'd think it would be worthwhile running the `wc_update_260_zone_methods()` function on their database?

When I updated my master install this morning from 2.6.2-dev to latest, the upgrade routine didn't run which means it didn't fix my existing postcode ranges.

Thanks again.

James

**Comment by om4james** [comment]
Hi @mikejolley, would it be possible to include `wc_update_260_zone_methods()`in the 2.6.4 db upgrade routine?
