### ISSUE TITLE
Unnecessary #content in the CSS file

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11416]
```
.woocommerce div.product .woocommerce-tabs ul.tabs li:after,
.woocommerce #content div.product .woocommerce-tabs ul.tabs li:after {  }
.woocommerce div.product .woocommerce-tabs ul.tabs li:before,
.woocommerce #content div.product .woocommerce-tabs ul.tabs li:before {  }
```

Both have superfluous `#content` which should be removed from all places from all CSS files.

Also, `div.product` is redundant and should be renamed to `.product`. Otherwise it only makes updating styles harder. Same with `ul.tabs`.

**Comment by mikejolley** [comment]
Actually this is for one of the default WP themes - to make the rules specific enough to change the theme's styles.

**Comment by manake** [comment]
It should go to woocommerce-2016.css (or equivalent) then because otherwise other theme developers can't easily overwrite that if it comes with #content ID (we have to use the same duplicated lines) (this ID is a part of underscores framework and we prefer to not remove it).

Therefore, it's a valid request to remove #content ID or move everything that uses it to a separate style file.

**Comment by mikejolley** [comment]
Theme devs can remove our styles...

**Comment by manake** [comment]
All styles that style WC for 2016 default theme should go to style.css of 2016 theme.

But if WooCommerce plugin decided to include styles of default themes then it's reasonable to pack that into woocommerce-2016.css and enqueue this file only when 2016 theme is active.

That will make woocommerce.css cleaner, we (theme developers) won't see duplicated lines of code with IDs (hard to overwrite).

I know that I can dequeue woocommerce.css but I don't want to since it provides a good starting styling that I want to modify only slightly.

You can keep this closed but so far #content ID and other duplicates or !importants were only obstacles.

**Comment by jameskoster** [comment]
> I know that I can dequeue woocommerce.css but I don't want to since it provides a good starting styling that I want to modify only slightly.

So copy/paste it in to a stylesheet you control and modify from there. For any custom themes we recommend dequeuing our css as it is prone to change over time.
