### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by temp-temp-temp** [woothemes/woocommerce#11410]
## EXPLANATION OF THE ISSUE

Hi,
I am using PostMan client to call woocommerce (v 2.6.0) rest api. I am not using nginx server and I am getting invalid signature error (401). 

Link for postman - https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
Authentication is working just fine.
Please read the REST API docs: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

**Comment by temp-temp-temp** [comment]
Thank you so much for the reply. I think the issue is with my server but I am not able to rectify it. I even spoke to GoDaddy but it was of no use. Could be please tell me what could be the possible issues with my server?

**Comment by claudiosmweb** [comment]
Check the OAuth tips.

**Comment by temp-temp-temp** [comment]
Thank you very much.  It worked. I was not using www in my request.

**Comment by claudiosmweb** [comment]
;)
