### ISSUE TITLE
REST API Fails to return individual webhook

### ISSUE THREAD

**Issue by leeroyrose** [woothemes/woocommerce#11414]
## EXPLANATION OF THE ISSUE

When fetching a webhook using the api, I get the following errors:

Notice: Undefined variable: post in woocommerce/includes/abstracts/abstract-wc-rest-posts-controller.php on line 141

Notice: Trying to get property of non-object in woocommerce/includes/abstracts/abstract-wc-rest-posts-controller.php on line 141

## STEPS TO REPRODUCE THE ISSUE

Create a webhook and try to retrieve it using the rest api. I'm using postman.

## ADDITIONAL NOTES

the get_post_types() method in the file abstract-wc-rest-posts-controller.php looks like it should return an array of post types, but instead it's trying to fetch the post type of a non existent post object.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://es.local/wootest
Site URL: http://es.local/wootest
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.23 (Ubuntu)
PHP Version: 5.6.23-2+deb.sury.org~trusty+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (10) ###

AJAX Thumbnail Rebuild: by junkcoder – 1.12
Akismet: by Automattic – 3.1.11
Gravity Forms: by rocketgenius – 2.0.2
Meta Box Group: by Rilwis – 1.0.4
Meta Box Include Exclude: by Rilwis – 0.2.4
Meta Box: by Rilwis – 4.8.7
WooCommerce PayPal Express Checkout Gateway: by Automattic/WooCommerce – 1.0.4
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.2
Yoast SEO: by Team Yoast – 3.3.2

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My Account: ❌ Page not set

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: ES Boilerplate
Version: 2.0
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not Declared

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/8f62c322dde7c5d5df3cacc97d9163b9df65b197
