### ISSUE TITLE
Not necessary to load "star" font in reviews

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11419]
I think "star" font may have some different (more blurred) stars than WooCommerce icons.

review-rating.php should print actual stars (so that anyone who styles this can add spacing between them and colorize them with gray and another color) and not one tag that prints five stars at once. Then WooCommerce icons should be used and "star" font could be removed.

There is no reason to have "star" font and make more HTTP requests for just some small SVG star when this is already included in another font file.

Then also "x out of 5 stars" text could be styled in a better way without padding.

**Comment by mikejolley** [comment]
Star fonts are not present in all font families. We've seen issues in the past using special characters (e.g. for currency symbols) where some users don't have the glyph on their system and therefore see a square.

SVG is consistent across all.
