### ISSUE TITLE
Missing author name and date in reviews when "review is awaiting approval"

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11418]
review-meta.php forgets to print author name and date when comment is awaiting approval. This is incompatible with what happens with default WP output.

**Comment by mikejolley** [comment]
If your review is not published, and it's your review, why is this information relevant?

**Comment by manake** [comment]
Default WP comments show author and date in this situation. It's very confusing that author's name and date have been omitted, people think that there was a bug and they didn't fill in the "author" field.
