### ISSUE TITLE
Dates in the reviews are not links (but should be)

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11421]
WP prints dates for comments as links and to make WC comments consistent the same should happen.

**Comment by mikejolley** [comment]
Thats like saying products should look identical to posts. Reviews are not comments - we show lots of different information there. I'm not sure if there would be much benefit to adding a link here - it would also need extra jquery code to focus the tab, so its not just as simple as adding a link.

**Comment by jameskoster** [comment]
Not worth in core, add it via customisation/plugin if you like :)
