### ISSUE TITLE
Visibility of "Clear" button in variations

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11427]
The "clear" button of variations changes visibility to hidden when no variation is chosen but display remains at block.

It should get class "inactive" instead. Otherwise it's not possible to style inactive button. Adding inline CSS = bad idea. (Your current inline CSS is not suitable for many themes anyway.)

**Comment by claudiosmweb** [comment]
It's not a button, it's a link.
And it show or hide using jQuery, that's why have inline CSS.

**Comment by manake** [comment]
Well, it shouldn't have inline CSS then and it shouldn't be hidden with jQuery.

It should have "inactive" class that gets proper CSS.

How am I supposed to style it otherwise?

**Comment by mikejolley** [comment]
Show me a theme where the clear link is a problem. It can be styled, and the default behavior is to hide it. Adding classes now instead of inline CSS will break the hiding across **all** themes with custom css.

**Comment by manake** [comment]
How can it be styled if it doesn't have any CSS class when it's hidden? It can't.

Here is a theme that this doesn't work in:
1. I download underscores framework.
2. I install WooCommerce.
3. I want the "clear" link to have `display: none;` instead of `visibility: hidden;` because it messes my margin and creates unwanted 10px of space (**the link is hidden but it takes space**).
4. I can't because it turns out there is no CSS class there.
5. I open a ticket.

If you want to maintain backward compatibility you can leave inline style but in addition give us some sort of "hidden" CSS class so that we can overwrite this to `display: none;`.

**Comment by pixedelic** [comment]
👍  maybe it is not an issue that involves many themes, but we have been having this problem since we started working with WooCommerce and over time we have found various work-around more or less elegant. It would be nice to have a native method that avoids adding empty space when the link is hidden and preserves the vertical rhythm in every situation.
