### ISSUE TITLE
Product reviews are missing paragraph formatting

### ISSUE THREAD

**Issue by axcho** [woothemes/woocommerce#11425]
Ever since commit d0d3481091041410955845c593f8d94cf6103c34, product reviews that are written with multiple paragraphs show up without paragraph formatting. That is, the paragraphs run together rather than being separated by newlines.

For example, this:

> What a great product!
>
> I'm going to start a new paragraph.

Shows up as this:

> What a great product! I'm going to start a new paragraph.

This happens even with all plugins disabled and a default theme. The problem is solved if the change is reverted, that is if this:

`echo '<div itemprop="description" class="description">' . get_comment_text() . '</div>';`

Is changed back to this:

`echo '<div itemprop="description" class="description">' . comment_text() . '</div>';`

Please fix.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/d7aea130b0e918e819d15275933f581e3811d8a2
