### ISSUE TITLE
Feature request: better product selector in "cross-sells" and "up-sells"

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11424]
Currently in the admin panel on product page it's possible to add "cross-sell" and "up-sell" products by typing in the first 3 characters of other product's title.

That requires user to open products list in another browser tab. It would be better UX to show the whole list without opening other tabs. WP already comes with solutions that list all posts or pages in Appearance > Menus and in Appearance > Customize.

**Comment by mikejolley** [comment]
This is being looked at in a new admin UI - we're aware of the issue. Listing all however is not ideal as it doesn't scale.
