### ISSUE TITLE
Missing translation strings on GlotPress

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#11422]
For some reason this string (and maybe some others) aren't automatically taken into account on GlotPress and though are not included in .po files downloaded from GlotPress. For example this string:

https://github.com/woothemes/woocommerce/blob/e39274e75391a186413da0bc5c217fa4c8bf2885/templates/loop/result-count.php#L39

**Comment by claudiosmweb** [comment]
Seems fine for me: 
![screenshot from 2016-07-14 12-48-43](https://cloud.githubusercontent.com/assets/1264099/16837102/80b041f4-49c1-11e6-9148-77e55924794a.png)

![screenshot from 2016-07-14 12-49-55](https://cloud.githubusercontent.com/assets/1264099/16837103/80c8dc50-49c1-11e6-880f-df1dccb6cf7b.png)
