### ISSUE TITLE
report.js bug in export_csv table export format

### ISSUE THREAD

**Issue by charlestonsoftware** [woothemes/woocommerce#11428]
## EXPLANATION OF THE ISSUE

Exporting a table using the reports.js export_csv data type will break on download if the table cell contains the hash (pound) character.

## STEPS TO REPRODUCE THE ISSUE

Add an export button to the customer list report.   Export the CSV.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.storelocatorplus.com
Site URL: https://www.storelocatorplus.com
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Amazon) OpenSSL/1.0.1k-fips PHP/5.6.22
PHP Version: 5.6.22
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 2000
cURL Version: 7.40.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (33) ###

VaultPress: by Automattic – 1.8.3
Gravity Forms: by rocketgenius – 2.0.2
Akismet: by Automattic – 3.1.11
bbPress Enable TinyMCE Visual Tab: by Jared Atchison – 1.0.1
JP bbPress Slack Integration: by Josh Pollock – 0.3.1
bbPress: by The bbPress Community – 2.5.10
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.18
GD bbPress Attachments: by Milan Petrovic – 2.3.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Groups WooCommerce: by itthinx – 1.9.6
Groups: by itthinx – 1.11.2
Jetpack by WordPress.com: by Automattic – 4.1.1
Location Tools: by Charleston Software Associates – 4.5-RC-02
OPcache Dashboard: by Daisuke Takahashi(Extend Wings) – 0.3.1
Sidebar Login: by Mike Jolley – 2.7.3
Slideshow: by StefanBoonstra – 2.3.1
Subpage Listing: by Mark Jaquith – 0.6.2
SyntaxHighlighter Evolved: by Alex Mills (Viper007Bond) – 3.2.1
User Switching: by John Blackbourn – 1.0.9
WooCommerce Chained Products: by Store Apps – 2.4.2
WooCommerce Coupons Countdown: by itthinx – 2.4.3
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.5.0
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Add-ons: by WooThemes – 2.7.20
WooCommerce Report Modifier: by Charleston Software Associates – 4.5-beta-6
WooCommerce Subscriptions: by Prospress Inc. – 2.0.17
WooCommerce: by WooThemes – 2.6.2
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.6.2
WooTransmitter: by WooThemes – 1.0.1
WordPress Development Kit Plugin: by Charleston Software Associates – 4.5
Yubikey-plugin: by Henrik Schack – 0.96

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4066 - /products/
Cart: #4067 - /products/checkout/cart/
Checkout: #4068 - /products/checkout/
My Account: #4070 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable-subscription (variable-subscription)

### Theme ###

Name: Store Locator Plus Storefront
Version: 1.0.02
Author URL: https://www.storelocatorplus.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.0.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

This replaces the '#' character with nothing.   There may be a better way to escape a pound character for CSV export but this is quick & easy and makes report.js applicable to a lot more data exports.

`
		if ( 'table' === export_format ) {

			$( this ).offsetParent().find( 'thead tr,tbody tr' ).each( function() {
				$( this ).find( 'th, td' ).each( function() {
					var value = jQuery.trim($( this ).text());
					value = value.replace( '#', '' );
					value = value.replace( '[?]', '' );
					csv_data += '"' + value + '"' + ',';
				});
				csv_data = csv_data.substring( 0, csv_data.length - 1 );
				csv_data += '\n';
			});

			$( this ).offsetParent().find( 'tfoot tr' ).each( function() {
				$( this ).find( 'th, td' ).each( function() {
					var value = $( this ).text();
					value = value.replace( '#', '' );
					value = value.replace( '[?]', '' );
					csv_data += '"' + value + '"' + ',';
					if ( $( this ).attr( 'colspan' ) > 0 ) {
						for ( i = 1; i < $(this).attr('colspan'); i++ ) {
							csv_data += '"",';
						}
					}
				});
				csv_data = csv_data.substring( 0, csv_data.length - 1 );
				csv_data += '\n';
			});
`

**Comment by mikejolley** [comment]
Do you want to raise the above as a PR? Does not seem like core reports themselves are affected by this.
