### ISSUE TITLE
MasterCard is changing their logo and name

### ISSUE THREAD

**Issue by chriscct7** [woothemes/woocommerce#11438]
Effective immediately (and already in place on the US main website), MasterCard is now "mastercard" with no camel-casing, or uppercase first letter, and a new period in certain cases. In addition, they have a new logo (depicted below).

![image](https://cloud.githubusercontent.com/assets/1324637/16846680/65039bfa-49bb-11e6-809a-d67cbb8f8a13.png)

This change is already live on the frontpage of the US main website:
![image](https://cloud.githubusercontent.com/assets/1324637/16846714/84a84870-49bb-11e6-86fe-9f8f51ee9895.png)

Cross-ref: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4796

**Comment by BurlesonBrad** [comment]
sheesh. I love how they've updated their own logo, but yet the downloadable files for folks to actually **use...** https://www.mastercardbrandcenter.com/us/getourbrand/index.shtml?pageId=dl_1210&expertVisible=false&staticPage=yes ...don't seem to be a priority.

Even PayPal's assets used in class-wc-gateway-paypal.php aren't updated yet:  https://www.paypalobjects.com/es_XC/Marketing/i/banner/paypal_visa_mastercard_amex.png
https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg
https://www.paypalobjects.com/webstatic/mktg/Logo/AM_mc_vs_ms_ae_UK.png
_......and on and on and on_

![giphy 4](https://cloud.githubusercontent.com/assets/6208757/16852127/5b4d98e8-49cc-11e6-8bd4-28eba03050b2.gif)

**Comment by claudiosmweb** [comment]
Not hard to change, but we need some EPS or PNG file for it.

**Comment by claudiosmweb** [comment]
Not even here: http://www.mastercardbrandcenter.com/us/moreabout/bh_bme.shtml

**Comment by jameskoster** [comment]
Yeah as soon as an official vector graphic is available we'll update
