### ISSUE TITLE
Product Tags/Categories can share WP Post Object ID

### ISSUE THREAD

**Issue by sybrew** [woothemes/woocommerce#11432]
## EXPLANATION OF THE ISSUE

The Product Tag (and maybe Category) ID can cross a WordPress Post object ID, like a page, CPT, category, tag or post.
The object ID should always be unique.

## STEPS TO REPRODUCE THE ISSUE

1. Create hundreds of posts.
2. Create hundreds of tags (asynchronously with step 1).
3. Find plausible identical ID's between the two.

## Plausible solution

1. Check and compare with `$wpdb->insert_id`.
2. Reserve ID at both tables.

## SYSTEM STATUS REPORT

_It's a client (sub)site, I've stripped as much unneeded info for security concerns._

WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL_formal

Server Info: Apache
PHP Version: 7.0.8

WC Database Version: 2.6.2

**Comment by mikejolley** [comment]
WooCommerce does not control this. And terms are not the same as posts - WordPress uses different tables and different IDs. This is not an issue.

**Comment by sybrew** [comment]
This will cause an issue in various existing code, however.

A simple common example, where `get_queried_object_id()` could be another ambiguous ID to check for outside the loop:
`return get_queried_object_id() == get_option( 'page_for_posts' ) : // Product Tag has been verified as is_home()`

Evidently, `is_archive()` should also be evaluated to prevent that statement from returning this, but developers and users of said plugins that aren't aware of this will encounter such issues.

WooCommerce doesn't control this as you said, it's the table that WooCommerce has created that controls this (auto_increment). The tables won't collide in the database, however, as seen in the code below (WP core insert term), WordPress does try to prevent conflicts prior to inserting data.

WordPress core insert term:
https://github.com/WordPress/WordPress/blob/4.5-branch/wp-includes/taxonomy.php#L2853-L2873

Eventually, the following function will result in a WP_Error if the taxonomial term IDs collide as of WP 4.4:
Trace 1: 
https://github.com/woothemes/woocommerce/blob/1e70bc71720d76d34d38940e5915da7e33c583c2/includes/wc-term-functions.php#L264-L266
Trace 2: https://github.com/WordPress/WordPress/blob/4.5-branch/wp-includes/taxonomy.php#L1839-L1857
Trace 3: https://github.com/WordPress/WordPress/blob/4.5-branch/wp-includes/taxonomy.php#L4491-L4501

I could be wrong on the last part, but I believe it's something to check into.

I hope this clears things up!
