### ISSUE TITLE
WooCommerce 2.6 removed actions and filters related to shipping classes

### ISSUE THREAD

**Issue by Chouby** [woothemes/woocommerce#11434]
In previous WooCommerce versions, [Polylang](https://wordpress.org/plugins/polylang/) was relying on the following actions:
`product_shipping_class_add_form_fields`
`product_shipping_class_edit_form_fields`
as well as the following filters:
`manage_edit-product_shipping_class_columns`
`manage_product_shipping_class_custom_column`
`quick_edit_custom_box`
to provide multilingual support of the Shipping classes.

As far as I have seen, all these have been removed with the new interface for Shipping classes.
Is there a way to come back to the old interface and get these filters and actions back?
Are there new actions and filters to replace them?

**Comment by claudiosmweb** [comment]
Remove since we don't use the WP taxonomy interface for it anymore.
I don't thin that you need any new actions or filters for it, since all strings are translatable.

**Comment by Chouby** [comment]
Yes of course, all WooCommerce strings are translatable.

But on a multilingual shop, we also need to translate all the content: Products, Categories, ... and Shipping classes. 

For these shipping classes, we need to translate the name, slug and description which are all user defined content. Thus we need to associate a language and a translation group to the shipping classes and provide a UI to manage this additional data. I was using the actions and filters above to achieve this (the same way you do for the image for product categories).

See how it was integrated in WooCommerce 2.5: http://nimb.ws/PlQo6y

I am of course not questioning the new interface. But by providing actions and filters, you allow 3rd party plugins to integrate with WooCommerce. Removing them breaks this integration.

That would be nice to integrate these actions and filters in your new interface.

**Comment by claudiosmweb** [comment]
Still, don't makes sense translate shipping classes, you can and should have different shipping classes for each country and needs.

**Comment by claudiosmweb** [comment]
Shipping classes are different than categories or tags, we don't display shipping classes in the frontend, so it's not required to translate your shipping classes, even now with Shipping Zones, where you can set several Flat Rates too with all your shipping classes.

**Comment by mahype** [comment]
Hello,

I have also problems with your remove of the actionhooks. I need the filters:

product_shipping_class_add_form_fields
product_shipping_class_edit_form_fields

Because I need to add some fields for Weight, Height, Length and Width. This is for the automatic price calculation for our shipment gateway.

Do you have a quick information how to insert such fields now?

Thank you! :)

Greetings,

Sven

**Comment by mahype** [comment]
OK. I got it. I have added a gist for all who want so see or compare the functionality between WooCommerce 2.5 and 2.6:

https://gist.github.com/mahype/280aac194ae0e73901c074eac376bc14
