### ISSUE TITLE
Please add a composer.json

### ISSUE THREAD

**Issue by dnaber-de** [woothemes/woocommerce#11436]
We use WooCommerce on many projects and while wpackagist.org is sufficient for deploying to staging/live systems, we sometimes have to deploy the master branch to testing environments. I know I could define a package on the fly in `composer.json` on a per-project base, but I have to do that on any project and it's quite error-prone.

However, adding a `composer.json` to this repository and report it to packagist.org is almost zero effort and would provide a high benefit to users working with composer. 

I read https://github.com/woothemes/woocommerce/pull/8662 as well as https://github.com/woothemes/woocommerce/issues/6170 but neither came with an argument, why WooCommerce should not have a `composer.json`.

Thanks in advance.

**Comment by claudiosmweb** [comment]
Because it's not needed and you can write custom code for it on the `composer.json` if you don't want to use wpackagist.org. And now we sync or beta and RC versions on SVN Master, so it makes easy if you need to test before releases.

**Comment by danielhuesken** [comment]
@claudiosmweb The trunk is 2 weeks old that is in sync?  
https://plugins.trac.wordpress.org/browser/woocommerce/trunk

**Comment by claudiosmweb** [comment]
@danielhuesken "And now we sync our beta and RC versions to SVN Master", we have any beta or RC now?

**Comment by dnaber-de** [comment]
@claudiosmweb You should make you clear, that I don't want to provoke you nor I want to troll here. I write this only once and then I'll leave and think about twice if I'll contribute to WooCommerce the next time. 

> Because it's not needed.
You should face the reality that PHP projects are managed via Composer these days. Supporting your users in their work is a thing you either want to or not. However, I'll write the package definition only once and then I'll go and automate these process (probably by forking this repo and distribute it on my own). This costs me a lot of time and clutters everything just because you don't want to spend 10 minutes to support a common tool.

If you ever change your opinion I'd happy to help you on questions about how this `composer.json` should look like and how to distribute a package on packagist.org.

**Comment by claudiosmweb** [comment]
@dnaber-de what not use it?

```json
{
    "name": "root/test-woocommerce",
    "description": "Testing WoooCommerce Master",
    "require": {
        "woocommerce/woocommerce": "dev-master"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "woocommerce/woocommerce",
                "version": "dev-master",
                "source": {
                    "url": "https://github.com/woothemes/woocommerce.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    ]
}
```

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/commit/36f9e156c7686f715a7c5725cbe90539fc73a2ba

**Comment by claudiosmweb** [comment]
https://packagist.org/packages/woocommerce/woocommerce

**Comment by dnaber-de** [comment]
Again, thanks a lot.

**Comment by claudiosmweb** [comment]
@dnaber-de "because you don't want to spend 10 minutes". I can say the same for you about add it to the `repositories` section and for sure don't have the risk of lose a arm while doing it, I always do it in my projects and works just fine :P
But now with the `composer.json` file you Germans can give me break xD

**Comment by GaryJones** [comment]
> you Germans

Not cool.
