### ISSUE TITLE
Empty error when searching for non-existent product by SKU paramater

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#11444]
## EXPLANATION OF THE ISSUE

When using the API to retrieve a product that does not exist on the database using the SKU parameter, an empty error is returned.

### Method 1: Retrieve a product by endpoint:
> www.example.com/wp-json/wc/v1/products?sku=product_sku&consumer_key=X&consumer_secret=X

Returns:
```
<html>
<head></head>
<body></body>
</html>
```

### Method 2: Retrieve a product programatically:

```
$woocommerce->get( 'products?sku=' . $sku );
```

Returns:
> Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: []' in ...

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US


### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### API ###

API Enabled: ✔
```

**Comment by claudiosmweb** [comment]
Works fine and with our PHP wrapper you suppose to use:

```php
$woocommerce->get( 'products', ['sku' => $sku]) );
```
