### ISSUE TITLE
Reports Customer List Cannot Change Page Length

### ISSUE THREAD

**Issue by charlestonsoftware** [woothemes/woocommerce#11445]
## EXPLANATION OF THE ISSUE

Go to WooCoomerce / Reports / Customer List.

Screen options is not available & cannot set number of customer records to display.

Third party products have no hooks or filters or other means of modifying this parameter as it is hard-coded into the WC_Report_Customer_List class.

## STEPS TO REPRODUCE THE ISSUE

Go to WooCoomerce / Reports / Customer List.

Try to find "screen options".

## PROPOSED CHANGE

Change prepare_items to use the standard WP_List_Table method to set this value:

`		$per_page     = 20;
`
TO

`
        $per_page = $this->get_items_per_page( 'customers_per_page' , 20 );
`

This proposed change assumes a user_meta slug "customers_per_page" set via the page options.      This may need to be modified, but this simple change will at least allow third party add ons to modify this value.

**Comment by claudiosmweb** [comment]
Well, since it's a custom table, we don't have any "Screen Options" there.
But we can try do add it in some future release. Logging it to our roadmap: https://trello.com/c/KHD7FnNj/95-screen-options-customers-per-page-on-the-customers-reports-list
