### ISSUE TITLE
Visibility of "Clear" button in variations

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11443]
I'm reopening https://github.com/woothemes/woocommerce/issues/11427 - closing this without a solution is not a valid response. Adding inline CSS is not a valid solution here. No one can style it without extensive modifications at this moment and default styling added by jQuery doesn't fit many themes.

**Comment by claudiosmweb** [comment]
Fell free to submit a Pull Request then. But stop to reopen closed issues.

**Comment by mikejolley** [comment]
@manake - comment or add PR, don't open duplicates.
