### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by thednp** [woothemes/woocommerce#11442]
With today's modern browsers and low percent usage of legacy browsers it makes complete sense to kill the bug, **remove jQuery dependency**.

Currently developing a theme that's supposed to work with / without jQuery, but I would rather have it without it. For faster load speed, better performance, less long run JS code maintenance, etc etc.

**Comment by mikejolley** [comment]
I get that you don't like jQuery, but this is not a bug. 

All of the script files use jQuery syntax, so you're basically saying rewrite **all** the JS (which incidentally means we'll have bigger files and more browser issues for things jQuery handles). This is not something I feel we should do right now, and lets not forget many plugins/themes already include jQuery, which is cached, meaning you'll not see much improvement unless all plugins and WP core do the same thing.

**Comment by thednp** [comment]
I get that all/most developers use jQuery, but at least the front-end interactions should not require it.
* add to cart
* remove/update cart
* ajax apply coupon
* ajax checkout forms
* rating
* .. and so on, maybe this is it

So why load 130k of bloat for only 4-5 functions for which some 2-3 polyfills could also handle browser support?
