### ISSUE TITLE
Added to cart message uses blog posts

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#11448]
## EXPLANATION OF THE ISSUE

When on a grouped product page, adding one of the children products it shows the Added to cart message but the product name is wrong, it seems that it uses the title of a blog post instead.

![](http://g.recordit.co/oJC2GZZPkm.gif)

I'm on Storefront and WooCommerce last version.

Reported also in 437588-zd-woothemes

**Comment by WPprodigy** [comment]
Replicated and 438377-zd-woothemes

**Comment by stratosvetsos** [comment]
#11465
