### ISSUE TITLE
Admin UI - Option Pages/Tabs Improvments

### ISSUE THREAD

**Issue by JoeHana** [woothemes/woocommerce#11446]
In the case where many various WooCommerce Extensions are getting used, the option pages/tabs become clearly messy. Depending on the screen size it breaks the tab navigation sooner or later which simply looks...well...ugly.

With a few CSS Adjustments (Element Inspector) I've made a quick mockup which I want to submit as ui improvment. It is basically nothing spectacular, JetPack already comes with that kind of navigation, which simply makes it more comfortable to browse through all the panels.

Further along it would maybe be better to have some kind of "Core" Option Tabs (General, Products, Checkout,...), then some kind of separator and then a menu where 3rd party plugins can hook into.

![8wij1rcxkxjaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/122551/16863059/6645a4f6-4a4f-11e6-9ea9-75209a5196bc.png)

**Comment by mikejolley** [comment]
We're already working on something like this behind the scenes :) Thanks for the suggestion.
