### ISSUE TITLE
Conflict between cart ajax and Smart Coupons

### ISSUE THREAD

**Issue by lsterling03** [woothemes/woocommerce#11441]
## EXPLANATION OF THE ISSUE
There appears to be a conflict with the WooCommerce cart ajax and Smart Coupons. 

When on the Cart page, you can click a coupon in the "Available coupons" section and it will be added to your cart totals table. 

However, if you update the quantity of an item in your cart or remove an item from the cart, the coupons are no longer clickable. It appears to be related to the ajax used to update the cart. You have to refresh the page to restore the click function on the coupon.

A similar problem occurs if you remove a coupon from your cart totals table. It is removed (via ajax) but it does not reappear in your "Available Coupons" section unless you refresh the page first.

## STEPS TO REPRODUCE THE ISSUE

To reproduce: 

1. Put some products in your cart.
2. Ensure you have a coupon in your account.
3. Go to your cart.
4. Edit the quantity or remove an item in your cart.
5. Try to click on a coupon. It won't click anymore.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.23
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (24) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.3.9.2
Akismet: by Automattic – 3.1.11
Custom Facebook Feed: by Smash Balloon – 2.4.1.2
Formidable: by Strategy11 – 2.02.04
Gmail SMTP: by naa986 – 1.0.6
Maintenance: by fruitfulcode – 3.0
SG CachePress: by SiteGround – 2.3.8
Subscribe & Connect: by WooThemes – 1.1.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.15

WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.2
WooCommerce Nested Category Layout: by WooThemes / SkyVerge – 1.9.0
WooCommerce Product Bundles: by WooThemes – 4.14.5
WooCommerce Shipment Tracking: by WooThemes – 1.4.3 – 1.4.4 is available
WooCommerce Smart Coupons: by WooThemes – 3.1.1
WooCommerce Subscriptions: by Prospress Inc. – 2.0.17
WooCommerce: by WooThemes – 2.6.2
WooThemes Helper: by WooThemes – 1.6.2
Wordfence Security: by Wordfence – 6.1.10

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #17 - /shop/
Cart: #18 - /cart/
Checkout: #19 - /checkout/
My Account: #20 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Storefront
Version: 2.0.1
Author URL: https://www.woothemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

`

**Comment by mikejolley** [comment]
This is not a support portal. Use support.woothemes.com.

**Comment by lsterling03** [comment]
Sorry. WooCommerce Twitter posted that we could report bugs here. I thought this counted as a bug. Will use official support instead.

**Comment by shadimanna** [comment]
Was this issue fixed in WC or Smart Coupons as I have the same issue?
