### ISSUE TITLE
Feature request: No "Update cart" button for cart

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11457]
People create plugins such as:
https://gist.github.com/mikaelz/f41e29c6a99a595602e4
https://wordpress.org/plugins/woocommerce-ajax-cart/

I think this "update cart" button only adds friction and unnecessary additional user actions and it's rare in proper real shops (many do use AJAX and delay to update the total price though.)

I fixed this by using the code from the plugins but this could be an optional WC feature (or a new default behavior).

**Comment by claudiosmweb** [comment]
Better in a plugin for it, since if we remove it now, we risk make people confused.
Check it: https://github.com/woothemes/woocommerce/issues/6734#issuecomment-91245262
