### ISSUE TITLE
Out of stock not always working

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11452]
## STEPS TO REPRODUCE THE ISSUE

1. Create a product with "Black" and "White" colors and sizes: S, M, L, XL, XXL.
2. Create variation "Black" and another "White" - both with "Any size...".
3. Now create "White; XXL" variation and set it to out of stock.
4. Result: "White; XXL" variation can still be purchased on the front-end. But if I reorder "White; XXL" to be above "White; Any size..." then it's indicated correctly as "out of stock" on the front-end.

What should happen is:

1. (This is not related to the above steps but I noticed this while trying to fix this.) Creating a duplicated variation should not be allowed to begin with because user in the admin panel has no idea which to edit. When I create duplicated "White; XXL" then my original "White; Any size..." is reset to "Any color...; Any size..." and all data is erased (price, SKU, stock number). (Both duplicated "White; XXL" persist in the admin panel so I have a total of 3 items for "White" color.)
2. After solving the above issue (so that I never should be able to create duplicated variations) what would be logical for me is that "White XXL" (more specific) overwrites "White; Any size..." if it exists regardless of how it's positioned on the list.

**Comment by mikejolley** [comment]
This will be affected by the option to hide out of stock products from the catalog. When that one is out of stock, it's hidden so it immediately falls back to the 'any color' variation which is in stock.

To avoid this you'd need to explicitly create a variation for each combination, or disable the option to hide out of stock products.
