### ISSUE TITLE
Problum to get woocommerce product by category in REST API

### ISSUE THREAD

**Issue by royalnavneet** [woothemes/woocommerce#11451]
hello i am using REST API of woocommerce REST API , i want to get product by category . when i pass this url i got all product .

https://www.ezdarshan.com/wc-api/v2/products/?consumer_key=ck_dbf0f35e37dc0xxxxxxxxxxxb31d2&consumer_secret=cs_ea299e9b86xxxxxxxxxxxxxxf785a9f77ec7
But when i use filter like this : ?category=56,37

Again i got all product but i want only product which related to these category

i Follow this docs : https://woothemes.github.io/woocommerce-rest-api-docs/?php#list-all-products

Some on help me

**Comment by claudiosmweb** [comment]
You are following the docs for WP REST API and not our legacy REST API v2.
