### ISSUE TITLE
Legacy Shipping Methods affecting cost of new Shipping Zones

### ISSUE THREAD

**Issue by nathanielks** [woothemes/woocommerce#11454]
## EXPLANATION OF THE ISSUE

Having upgraded to the latest WooCommerce(2.6.2), disabled old Shipping Methods and adding new Shipping Zones (I forget which I did first), the price of the legacy methods is being being added to the cost of the new shipping zones, affecting the cost.

For example, if there were a Flat Rate shipping method before that cost 7.95 and a new Shipping Zone Flat Rate that also cost 7.95, the total cost for shipping would be 15.90.

I believe this may be related to the extra fields for the legacy methods related to shipping classes (in my case the `no_class_cost`. I'm attaching the `woocommerce_flat_rate_settings` record from my database with the legacy settings for you to take a look at. Removing this record resolves the problem.

## STEPS TO REPRODUCE THE ISSUE

1. Use latest WooCommerce.
2. Create Flat Rate shipping zone.
3. Add attached `woocommerce_flat_rate_settings` record to the options table.
4. Add something to your cart.
5. Go to checkout page to view shipping costs.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://example.dev
Site URL: http://example.dev/wp
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.1
PHP Version: 7.0.7-4+deb.sury.org~trusty+1
PHP Post Max Size: 25 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #374 - /products/
Cart: #425 - /cart/
Checkout: #426 - /checkout/
My Account: #428 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Fifteen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

~~## DISCLAIMER~~

~~I wasn't able to reproduce this in my development environment, but I was able to in my production environment, so I'm not sure this is a common bug. I'm filing this so that in case others encounter this as well.~~

Here's the database record:
```sql
INSERT INTO `dbQZLTxvXB0_options` (`option_name`, `option_value`, `autoload`)
VALUES
	('woocommerce_flat_rate_settings', 'a:16:{s:7:\"enabled\";s:2:\"no\";s:5:\"title\";s:9:\"Flat Rate\";s:14:\"cost_per_order\";s:0:\"\";s:12:\"availability\";s:8:\"specific\";s:9:\"countries\";a:1:{i:0;s:2:\"US\";}s:4:\"type\";s:5:\"order\";s:10:\"tax_status\";s:7:\"taxable\";s:4:\"cost\";s:5:\"21.95\";s:3:\"fee\";s:0:\"\";s:11:\"minimum_fee\";s:0:\"\";s:7:\"options\";b:0;s:7:\"version\";s:5:\"2.4.0\";s:13:\"no_class_cost\";s:4:\"7.95\";s:35:\"class_cost_suplement-shipping-class\";s:4:\"7.95\";s:14:\"class_cost_699\";s:0:\"\";s:13:\"class_cost_60\";s:4:\"7.95\";}', 'yes')
```

**Comment by nathanielks** [comment]
Not sure if you want this closed or not, so I'll leave that to your discretion!

**Comment by nathanielks** [comment]
I take that back! I was able to reproduce this in development. I forgot that the cart caches the shipping costs. When I viewed the checkout page, the shipping cost changed when that database record was present. I updated the original ticket with the system report.

**Comment by claudiosmweb** [comment]
Not able to reproduce it, maybe you are using some custom code.
Since we don't have any `class_cost_suplement-shipping-class` on core.

**Comment by whitsey** [comment]
I believe that this is a valid issue.

I have a system where I setup Legacy Flat Rate at $10 before trying the new shipping zone setup.

I then deactivated Legacy Flat Rate

No, All I have is Free Shipping (> $100) and Flat Rate = $10 for 1 zone = Australia and I am getting Shipping = $22 ($20 + 10% GST)
I then set Flat Rate shipping to $0 YET the cart still shows Flat Rate = $11 ($10 + 10% GST)

Here are the settings and results prior to setting Flat Rate to $0

https://www.dropbox.com/s/0w76855wo6w5tu9/WooCommerce-Shipping.jpg?dl=0
https://www.dropbox.com/s/0y879nnratbelsq/WooCommerce-Cart.jpg?dl=0

**Comment by kwd1** [comment]
It is definitely an issue. I just deactivated the legacy settings and now I have "There are no shipping methods available. Please double check your address, or contact us if you need any help." No matter what I do, it still will not show shipping cost.  Is there a fix for this?
