### ISSUE TITLE
WooCommerce API v3 - OAuth

### ISSUE THREAD

**Issue by JamesGeiger** [woothemes/woocommerce#11463]
Hi, I have a Windows 10 app that I build that ties into WooCommerce's API (v3). I have a few questions:

1. We are using OAuth for the communication and need to know if it's possible to use it together with v3 version of the WooCommerce API to handle password changes and username/password reminders?

2. If the above isn't possible then we need to know if this functionality can be implemented in v3 of the WooCommerce API with custom endpoints?

Let me know - thanks.

**Comment by claudiosmweb** [comment]
Hello, have you read this before?

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

I'll be happy to reply you question on https://wordpress.org/support/plugin/woocommerce
