### ISSUE TITLE
Add a hook on set_price WC_Product method

### ISSUE THREAD

**Issue by oscargare** [woothemes/woocommerce#11462]
I'm working in a plugin that adds new price fields. The plugin override the product's price through _woocommerce_get_price_ filter, returning the price stored in the new field. 

I have a problem when other plugin set a products price dynamically through  **set_price** method, I haven't got a way to remove the _woocommerce_get_price_ filter and not override the price set dynamically.

Add a action in **set_price** method solved this problem.

Thanks in advance!

**Comment by mikejolley** [comment]
This could have authors going into a chicken egg situation and/or endless loop of price modifications :p 

TBH `set_price` should do what it says - set price to an amount. Not allowing filtering.

If the plugin is not respecting your initial price change, unless it has a good reason to do so, it should be fixed on it's side.
