### ISSUE TITLE
Query var added with filter 'woocommerce_my_account_my_orders_query' is stripped out since WooCommerce 2.6

### ISSUE THREAD

**Issue by Chouby** [woothemes/woocommerce#11464]
Hi!

I am using the filter 'woocommerce_my_account_my_orders_query' to add a query var and modify the orders list seen by customers on their account accordingly. The query var is coming from a custom taxonomy.

The orders query was correctly modified in WooCommerce 2.5 but no more since WooCommerce 2.6.

The reason is that the query var added in the filter 'woocommerce_my_account_my_orders_query' is then not taken into account in the function wc_get_orders, as this function accepts only a white list of query vars.

**Comment by claudiosmweb** [comment]
We don't exclude taxonomies on this query... Can you show me your code?

**Comment by mikejolley** [comment]
Post in https://wordpress.org/support/plugin/woocommerce with your code please. If this is a real bug report you need to provide more information for anyone to solve.

**Comment by Chouby** [comment]
Hi!

My code is as simple as:
```
add_filter( 'woocommerce_my_account_my_orders_query', 'account_orders_query' );

function account_orders_query( $args ) {
	$args['lang'] = 'en';
	return $args;
}
```
The fact that 'lang' is a custom taxonomy query var doesn't matter (I wrote that just fro the context). 

The problem is in the function wc_get_orders where you accept only a white list of parameters. Here are some details:

The query is done at https://github.com/woothemes/woocommerce/blob/2.6.2/includes/wc-order-functions.php#L121 with parameters stored in `$wp_query_args`.

This variable is previously defined in the block https://github.com/woothemes/woocommerce/blob/2.6.2/includes/wc-order-functions.php#L87#L118

Here, only a white list of arguments are copied from `$args` to `$wp_query_args`. So query vars unknown to your function are stripped out from the query.

You can test with the code above and a dump of `$args` at line 82 and `$wp_query_args` at line 119.

The code was different in WooCommerce 2.5  and query args added with the filter  'woocommerce_my_account_my_orders_query' were correctly passed to the query.

**Comment by claudiosmweb** [comment]
@Chouby anyway it will stop working after https://github.com/woothemes/woocommerce/issues/10071
Better you think in other method to do it.

Still, for now you can override the `woocommerce_account_orders()` function in your theme/plugin: https://github.com/woothemes/woocommerce/blob/d7aea130b0e918e819d15275933f581e3811d8a2/includes/wc-template-functions.php#L2143-L2163
But as I said, will stop work soon.

**Comment by Chouby** [comment]
I would rather not override `woocommerce_account_orders()` just to change one line in `wc_get_orders()`. Moreover, I am quite sure that overriding the function will end up in a conflict with another plugin which would do the same.

I guess that you believe that #10071 will break my code because you don't plan to support taxonomies for orders in the future. But if you provide relevant filters for the database query - and you usually do :) - it should be no problem for modify the database query based on a custom query var value. If my custom query var can reach the relevant code. 

To come back to the initial issue, do you prefer that I propose a PR?

**Comment by mikejolley** [comment]
Yes best do that.
