### ISSUE TITLE
Slow query when trying to add a product if wp_postmeta table is very large

### ISSUE THREAD

**Issue by amfriedman** [woothemes/woocommerce#11467]
## EXPLANATION OF THE ISSUE

If wp_postmeta table is large enough, the "Add new product" admin product page hangs (and never loads). I have a wp_postmeta table with 500M rows. I have identified a query that is generated by WP that will run as a terribly slow query if the table is large enough. The query will take many minutes to complete if the number of meta_key records that match the conditions in the WHERE clause is fewer than 30 (the number in the limit clause). This is because the query will not complete until either the limit is reached or the full table is scanned to collect all possible distinct meta_key records. If the limit can never be reached, then the query will scan the full table, which is very slow for a "high scale" table (100M+ rows, etc).

Here is the problem query generated by the woocommerce plugin:

SELECT DISTINCT meta_key
FROM wp_postmeta
WHERE meta_key NOT BETWEEN '_' AND '_z'
HAVING meta_key NOT LIKE '_%'
ORDER BY meta_key LIMIT 30;

## STEPS TO REPRODUCE THE ISSUE

1. Have a "high-scale" wp_postmeta table (100M+ rows) that has FEWER than 30 meta_key entries that would match the conditions in the query above.
2. In the admin, click on the menu item "Add new product"
3. You'll experience the hang as the query runs and never completes (or takes minutes to complete)

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
This will no longer be a problem after #10071, since orders are usually the bad guy in this scenario.
And we are already working to improve the performance of products in all of the things in the admin too. So I'm closing it since we already is covering it in other issues and PRs. Thanks.

**Comment by amfriedman** [comment]
Thanks for the response. Actually, this is my mistake. The query is apparently part of a WP core bug, not a WooCommerce bug: https://core.trac.wordpress.org/ticket/33885
