### ISSUE TITLE
Grouped products wc_add_to_cart_message missing second argument

### ISSUE THREAD

**Issue by dorkster100** [woothemes/woocommerce#11466]
I managed to find a bug or so it seems to me in the version 2.6.2.

So i will copy contents of the message that i sent into support, they said i should write here:
'I stumbled upon a problem today, after i clicked add to cart button, the message said '"Hello World" has been added to your cart', although the title of the product was different and it happened to all grouped products. So i have been digging up the code and i found that in file class-wc-form-handler.php on line 786: wc_add_to_cart_message( $added_to_cart ); seems to be missing a second argument that should be boolean true. Because according to the code the array that is built there is actually in the form of array('id'=>'quantity'). But when the second argument is not specified the key (id) is dismissed later and quantity is used as the id. So for example if i added 2 products, then it would actually say Sample Page instead of Hello World in the message.

So this is a bug right? And i can change the core plugin expecting it to be fixed in new release?'

**Comment by claudiosmweb** [comment]
Duplicated of #11448
