### ISSUE TITLE
Make WC logger pluggable

### ISSUE THREAD

**Issue by kloon** [woothemes/woocommerce#11474]
At present the WooCommerce logger class is not pluggable, meaning all logging will log to a file on the webserver. On enterprise hosting where file system access is restricted and remote logging tools are used it would be great to replace the class with a custom class to log to remote logging services instead.

I propose to make the logger class just like the session class where you can override the default one with a custom class of your own.

**Comment by claudiosmweb** [comment]
> I propose to make the logger class just like the session class where you can override the default one with a custom class of your own.

For the sessions we use:

```php
$session_class  = apply_filters( 'woocommerce_session_handler', 'WC_Session_Handler' );
$this->session  = new $session_class();
```

Still not a solution, since people create new instances of the `WC_Logger` in they own plugins.
Better wrap it into a function now... It would be simpler if we already had done this when we removed the `$woocommerce->logger()`.
