### ISSUE TITLE
Editing the status of an order causes fatal error

### ISSUE THREAD

**Issue by Robert-Held** [woothemes/woocommerce#11477]
## EXPLANATION OF THE ISSUE

Just updated to 2.6.2 (after a long run without any update) and added shipping zones as required. An order was placed successfully.
Now I want to edit that order in detail but when trying to change the order status, a fatal error occurs with this message:

> Fatal error: Call to undefined method WC_Shipping_Flat_Rate::get_meta_data() in C:\xampp\htdocs\fslocal\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-order.php on line 491

This error does not occur, however, when I change the status in the order overview.

I can't find any direct link to a modification I made, so I don't know if this is an issue solely on my config. Below you'll find the status report for my local dev system.

## STEPS TO REPRODUCE THE ISSUE

1. Go to the edit page of any order.
2. Change the order status.
3. Save the order.

### WordPress Environment ###

Home URL: http://localhost/fslocal
Site URL: http://localhost/fslocal
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
PHP Version: 5.6.8
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.40.0
OpenSSL/1.0.1l

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (14) ###

Advanced Custom Fields: von Elliot Condon – 4.4.8
Contact Form 7: von Takayuki Miyoshi – 4.4.2
Duplicator: von LifeInTheGrid – 1.1.14
WPBakery Visual Composer: von Michael M - WPBakery.com – 4.12
Profile Builder: von Cozmoslabs
Madalin Ungureanu
Antohe Cristian
Barina Gabriel
Mihai Iova – 2.4.2

Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
Revolution Slider: von ThemePunch – 4.6.8
Simple Lightbox: von Archetyped – 2.5.3
UpdraftPlus – Backup/Wiederherstellung: von UpdraftPlus.Com
DavidAnderson – 1.12.15

WooCommerce German Market: von Inpsyde GmbH – 2.5
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.5.35
WooCommerce Simple Registration: von Astoundify – 1.0.1
WooCommerce: von WooThemes – 2.6.2
WP-Piwik: von André Bräkling – 1.0.9

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #9 - /shop/
Warenkorb: #10 - /warenkorb/
Kasse: #11 - /kasse/
Mein Konto: #12 - /benutzerkonto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Frozen Screams
Version: 1.1.1
Author URL: http://woothemes.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.0.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: frozen/woocommerce/archive-product.php
frozen/woocommerce/cart\cart-totals.php
frozen/woocommerce/cart\cart.php
frozen/woocommerce/checkout\review-order.php
frozen/woocommerce/checkout\thankyou.php
frozen/woocommerce/content-product.php
frozen/woocommerce/content-single-product.php
frozen/woocommerce/emails\customer-completed-order.php
frozen/woocommerce/emails\customer-processing-order.php
frozen/woocommerce/single-product\add-to-cart\variable.php
frozen/woocommerce/single-product\meta.php
frozen/woocommerce/single-product\price.php
frozen/woocommerce/single-product\product-attributes.php
frozen/woocommerce/single-product\product-image.php
frozen/woocommerce/single-product\product-thumbnails.php
frozen/woocommerce/single-product\rating.php
frozen/woocommerce/single-product\related.php
frozen/woocommerce/single-product\review.php
frozen/woocommerce/single-product\sale-flash.php
frozen/woocommerce/single-product\share.php
frozen/woocommerce/single-product\short-description.php
frozen/woocommerce/single-product\tabs\additional-information.php
frozen/woocommerce/single-product\tabs\description.php
frozen/woocommerce/single-product\tabs\tabs.php
frozen/woocommerce/single-product\title.php
frozen/woocommerce/single-product\up-sells.php
frozen/woocommerce/single-product.php

**Comment by mikejolley** [comment]
Definitely look at customisations because if you're adding a custom shipping method for example, it may lack this method.

**Comment by mikejolley** [comment]
Closing due to lack of feedback. Please perform basic troubleshooting steps (debug mode, disable plugin and themes) before replying further.

**Comment by Robert-Held** [comment]
Got it.
The cause was a conflict with an older version of the WooCommerce German Market plugin. It referred to WC_Shipping_Flat_Rate instead of WC_Shipping_Rate.

thanks

**Comment by Stef-S** [comment]
Thanks Robert! I currently have the exact same problem. 
How did you fix it? Did you simply buy a renewal license of WooCommerce German Market?
Thanks in advance, Stefan.

**Comment by Robert-Held** [comment]
Hey Stefan, I hope you managed to cope with this problem in the meantime.
Since we currently cannot renew our license, I did the following:
In plugins/woocommerce-german-market/inc/WGM_Tax.php you'll see in line 223
`$new_shipping = new WC_Shipping_Flat_Rate( );`
Change that to
`$new_shipping = new WC_Shipping_Rate( );`
WooCommerce shipping system got a big change. That's why this breaks the old versions of WGM.

**Comment by Stef-S** [comment]
Hey Robert, thanks so much!!! This really helped a lot! Regards, Stefan

**Comment by xvostikk** [comment]
Thank you very much! I had the same problem, it helps.
