### ISSUE TITLE
Product discounts not shown in my-account order overview

### ISSUE THREAD

**Issue by mikkamp** [woothemes/woocommerce#11476]
When an order is created in the dashboard the product price can be adjusted. This can be useful when creating a wholesale order for a client with discounted prices.
However when the order is viewed on the my-account order preview page only the original product price is shown. A total discount is shown but this does not reflect which product was discounted and by how much.

![Order Details](https://cloudup.com/cyqnJerCPvC+)

In the dashboard view of the order you can see the discount applied for each product. The original product price is stored in the _line_subtotal and the discounted price is stored in _line_total.

![Dashboard](https://cloudup.com/c3cuhF4sd7i+)

**Comment by mikejolley** [comment]
Discussed on Slack - intentional and matches the frontend.
