### ISSUE TITLE
Passwords saved via settings API are HTML-encoded

### ISSUE THREAD

**Issue by chesio** [woothemes/woocommerce#11473]
Hi,

I'm using a plugin that implements a payment gateway as a subclass of WC_Payment_Gateway (and thus uses WC_Settings_API methods to store gateway settings).

I had a problem with one of my passwords being constantly revoked by the gateway and found out the reason is that the password is malformed when it gets stored in database. Specifically, "<" was HTML-encoded to "`&lt;`" in my case, but [others have similar problems](https://wordpress.org/support/topic/username-and-or-password-with-ampersand-breaks-plugin) with other special characters. I tracked the problem to [wp_kses_post](https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-settings-api.php#L828) being applied to all password input fields by default.

I fixed the plugin by creating `validate_FIELDID_field` methods for password fields, but I think that it would be reasonable to process password inputs with slightly less strict validation method than `wp_kses()`. I'd say that passwords with "<", ">" or "&" are not that uncommon.

Cheers,
Česlav

**Comment by funkysoul** [comment]
I'm not quite sure if this needs to be reopened. I'm having the same issue as Ceslav, my password contains the ">" and "%" characters, when I save the settings, the password stored in the database is without those 2 chars, running the latest version of WC with WP 4.7.2
