### ISSUE TITLE
callback functions similar to paypal ipn

### ISSUE THREAD

**Issue by opmc** [woothemes/woocommerce#11479]
While writing a plugin for woocommerce, I am stuck with callback function. I am following all instructions to created notification url using $woocommerce->api_request_url( <my plugin class name here> ) and when I try to hook into callback handler of this class with add_action( 'woocommerce_api_<my plugin class name in lowercase>', array( $this, 'callback_handler' ) ), It never reaches this function.

Any help to resolve this will be appreciated.

**Comment by mikejolley** [comment]
Look at the source code for PayPal - woocommerce_api_ needs a suffix. You also need to ensure your handler/code is loaded when this action is called - this may require something extra in your main plugin file, or moving your handler out of the gateway class.

Please don't ask support questions here as it's a bug tracker. Email or use the forum.
