### ISSUE TITLE
Cash on delivery: it is impossible to select shipping methods

### ISSUE THREAD

**Issue by vkn999** [woothemes/woocommerce#11482]
I can't select shipping methods in the field: **Enable for shipping Methods** at WooCommerce >> Settings >> Checkout >> Cash on delivery
However, all three shipping methods are enabled

![cash_on_delivery](https://cloud.githubusercontent.com/assets/14319784/16981652/362f74da-4e74-11e6-9dda-6ef79a141c8b.png)

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/fce7771d82eb5f7a4e15d606e266fbd88460e6fc
