### ISSUE TITLE
Enable/disable checkbox too narrow when not enabled

### ISSUE THREAD

**Issue by bobbingwide** [woothemes/woocommerce#11484]
## EXPLANATION OF THE ISSUE
This is a problem with a shipping plugin that I am upgrading to work with for WooCommerce 2.6 shipping zones.

On Google chrome, when the Enable/Disable checkbox for Enable this shipping method is not enabled (ie. not checked) the checkbox is far too narrow. 

The offending CSS is in admin.css
`.wc-modal-shipping-method-settings form .form-table tr td input[type=checkbox]{width:auto;min-width:0}`

#### Workaround
Overriding the min-width to the value used in form.css seems to resolve the issue.

`.wc-modal-shipping-method-settings form .form-table tr td input[type=checkbox]{min-width:16px;}` 

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Screenshot? Just to note as well, you no longer need an enabled checkbox in instance settings - it's handled on the list of shipping methods for you.

**Comment by bobbingwide** [comment]
Hi Mike, here's a screen shot from Chrome.
![image](https://cloud.githubusercontent.com/assets/2474435/16988752/5ea9504c-4e89-11e6-9001-66e0810267e6.png)

Note: This screenshot exhibits the same blurriness as I noted previously. I believe the blurriness is a Chrome issue related to a.  Hardware acceleration, b. Number of screens in use. 

It's fine in Firefox
![image](https://cloud.githubusercontent.com/assets/2474435/16988804/95a461e0-4e89-11e6-89b8-fbf321aec05f.png)

BTW: I discovered that I don't need the checkbox when I was looking at the next issue #11486
