### ISSUE TITLE
it will change my custome payment gateway link in admin checkout page

### ISSUE THREAD

**Issue by bharatmaher** [woothemes/woocommerce#11485]
## EXPLANATION OF THE ISSUE
- i see blank page in admin checkout option after updating WC to 2.6
- for (v-2.5.3 ): i created custom payment gateway for WC and its working great with WC version 2.5.3 so,for this version in admin-side when i go to checkout tab and hover over my custom payment gateway it's show me link like this
 - http://localhost/demo_site/wp-admin/admin.php?page=wc-settings&tab=checkout&section=_wc_xy_payment_gateway_

 but when i update WC to 2.6 and again go to same page it's will generate different link like.
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
When you submitted this issue it clearly states not to post support questions here.

https://wordpress.org/support/plugin/woocommerce

Yes the links changed in 2.6. No this is not a bug.
