### ISSUE TITLE
is_checkout() true on Pages admin screen when Checkpage is displayed first

### ISSUE THREAD

**Issue by tamarazuk** [woothemes/woocommerce#11489]
## EXPLANATION OF THE ISSUE

While it's very rare, if your Checkout page appears as the [first page](http://cloud.skyver.ge/3w1w1Z1m0524) in the list of Pages in the admin, `is_checkout()` returns `true`. This isn't a huge issue as we just added an additional check to make sure we're not in the admin, but I think it would be best if the  `is_checkout()` itself is adjusted to avoid issues since this ended up causing a fatal error for a customer running Address Validation. 

## STEPS TO REPRODUCE THE ISSUE

It's very easy to reproduce:

1. Log/var_dump the value `is_checkout()` returns and you should see it's `false` when you visit /wp-admin/edit.php?post_type=page as long as the Checkout page does not appear first

2. Quick edit your Checkout page and set the order to `-1`: http://cloud.skyver.ge/29371I3D1i0C

3. Observe that `is_checkout()` now returns `true`

Thanks!

**Comment by mikejolley** [comment]
I think it also depends where you var_dump, but we can add an is_singular check.

**Comment by tamarazuk** [comment]
thanks @mikejolley, this does avoid the fatal error if any other extension uses `is_checkout()` on  the `wp` action without first checking if in the admin. 🍻
