### ISSUE TITLE
Reviews counted a Comments

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/woocommerce#11499]
If you go into your Comments section, you may notice a very large amount of comments counted even if very few exist:
![screen shot 2016-07-21 at 9 35 02 am](https://cloud.githubusercontent.com/assets/3220162/17030902/81db5630-4f26-11e6-8e3d-6d34e229fc43.png)
This is because Product Reviews are being counted here!  When you make a new product review it will add to that number.

Steps to reproduce:
1. Make a product review
2. See your comment count go up, up up!

In my test one review actually counted as multiple comments, maybe because I am using Product Reviews Pro that has multiple fields.

**Comment by mikejolley** [comment]
@mikeyarce I'd ping Skyverge about this ticket - WC reviews are included on the comments page as pictured here https://dl.dropboxusercontent.com/s/9qbrsnmor7egrjc/2016-07-22%20at%2012.52.png?dl=0
