### ISSUE TITLE
Date Pattern WooCommerce Edit-Order IE Edge bug

### ISSUE THREAD

**Issue by Jordy-van-Lankveld** [woothemes/woocommerce#11494]
## EXPLANATION OF THE ISSUE

A client of us uses IE Edge to manage and edit WooCommerce orders. When editing the 'Order date' of an order,  the date pattern of ' #order_date_hour ' which is being validated with HTML5-validation throws an incorrect error when using the browser IE Edge. I noted that this is only when the input field ( #order_date_hour ), is higher than 19 ( seven o'clock ). I think this pattern is not recognized correctly by IE Edge: pattern="([01]?[0-9]{1}|2[0-3]{1})".

## STEPS TO REPRODUCE THE ISSUE

Steps to recreate this issue:
1. Open a random order in ' /wp-admin/edit.php?post_type=shop_order ' with the browser IE Edge.
2. You may have to edit the date if the order is not placed between 19:59 and 00:00. My issue was for example: 2016-07-21 - 21:32.

( i'm not sure, but the HTML5-validation at our side is in Dutch language, but I assume the validation is not language specific )

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://dev.webber.nl/plugin-test
Site URL: http://dev.webber.nl/plugin-test
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.14 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 25000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.3

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #45 - /winkel/
Cart: #46 - /winkelmand/
Checkout: #47 - /afrekenen/
My Account: #48 - /mijn-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@jameskoster one you can look at?

**Comment by mikejolley** [comment]
@jameskoster is that fix safe to go with 2.6.4 or can it break?

**Comment by jameskoster** [comment]
Just updated the input type. All my orders are fine. I can't think of a way it can break.
