### ISSUE TITLE
API product update attempts placeholder image upload

### ISSUE THREAD

**Issue by kooliokey** [woothemes/woocommerce#11491]
## EXPLANATION OF THE ISSUE

I have WooCommerce 2.6.3 with API V1 which was released with 2.6. When I try to change a product with a placeholder image, I get an error about being unable to upload the image: "Error getting remote image https://wordpress.local/wp-content/plugins/woocommerce/assets/images/placeholder.png Error: name lookup timed out.". 

I've never had success uploading images through the WooCommerce API, so I upload them directly and tell WooCommerce API the id of it. I would expect the API to know this is it's own placeholder image and not bother to upload it. Perhaps adding this placeholder to the WP Media so it has an actual id would be best, or simply check in the image upload function if the URL of the image matches what the placeholder's would be.

## STEPS TO REPRODUCE THE ISSUE

1. Install WooCommerce 2.6.3
2. Create a product, I just created one with a name only. Leaving all defaults and NOT uploading images
3. Attempt to update that product through an API call

### WordPress Environment ###

Home URL: http://wordpress.local
Site URL: http://wordpress.local
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.20 (Unix) PHP/5.6.21 mod_wsgi/3.5 Python/3.5.1 OpenSSL/1.0.1p
PHP Version: 5.6.21
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (8) ###

Application Passwords: by George Stephanis – 0.1-dev
Breadcrumb NavXT: by John Havlik – 5.4.0
CPT Bootstrap Carousel: by Phil Ewels – 1.9.1
WP REST API: by WP REST API Team – 2.0-beta13.1
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.1.1 – 3.3.1 is available
WooCommerce: by WooThemes – 2.6.3
WooThemes Helper: by WooThemes – 1.6.2
WordPress Importer: by wordpressdotorg – 0.6.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: JAPG
Version: 1.0
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: tjpg/woocommerce/cart/cart-empty.php
tjpg/woocommerce/cart/cart-item-data.php
tjpg/woocommerce/cart/cart-shipping.php
tjpg/woocommerce/cart/cart-totals.php
tjpg/woocommerce/cart/cart.php
tjpg/woocommerce/cart/cross-sells.php
tjpg/woocommerce/cart/mini-cart.php
tjpg/woocommerce/cart/proceed-to-checkout-button.php
tjpg/woocommerce/cart/shipping-calculator.php
tjpg/woocommerce/checkout/form-checkout.php
tjpg/woocommerce/checkout/form-shipping.php
tjpg/woocommerce/emails/admin-cancelled-order.php
tjpg/woocommerce/emails/admin-failed-order.php
tjpg/woocommerce/emails/admin-new-order.php
tjpg/woocommerce/emails/customer-completed-order.php
tjpg/woocommerce/emails/customer-invoice.php
tjpg/woocommerce/emails/customer-new-account.php
tjpg/woocommerce/emails/customer-note.php
tjpg/woocommerce/emails/customer-processing-order.php
tjpg/woocommerce/emails/customer-refunded-order.php
tjpg/woocommerce/emails/customer-reset-password.php
tjpg/woocommerce/emails/email-addresses.php
tjpg/woocommerce/emails/email-customer-details.php
tjpg/woocommerce/emails/email-footer.php
tjpg/woocommerce/emails/email-header.php
tjpg/woocommerce/emails/email-order-details.php
tjpg/woocommerce/emails/email-order-items.php
tjpg/woocommerce/emails/email-styles.php
tjpg/woocommerce/emails/plain/admin-cancelled-order.php
tjpg/woocommerce/emails/plain/admin-failed-order.php
tjpg/woocommerce/emails/plain/admin-new-order.php
tjpg/woocommerce/emails/plain/customer-completed-order.php
tjpg/woocommerce/emails/plain/customer-invoice.php
tjpg/woocommerce/emails/plain/customer-new-account.php
tjpg/woocommerce/emails/plain/customer-note.php
tjpg/woocommerce/emails/plain/customer-processing-order.php
tjpg/woocommerce/emails/plain/customer-refunded-order.php
tjpg/woocommerce/emails/plain/customer-reset-password.php
tjpg/woocommerce/emails/plain/email-addresses.php
tjpg/woocommerce/emails/plain/email-customer-details.php
tjpg/woocommerce/emails/plain/email-order-details.php
tjpg/woocommerce/emails/plain/email-order-items.php
tjpg/woocommerce/loop/sale-flash.php
tjpg/woocommerce/myaccount/navigation.php
tjpg/woocommerce/product-searchform.php
tjpg/woocommerce/single-product/sale-flash.php
tjpg/woocommerce/single-product/tabs/tabs.php

**Comment by mikejolley** [comment]
https://woothemes.github.io/woocommerce-rest-api-docs/#product-properties

https://dl.dropboxusercontent.com/s/cicbtg12cpzu60y/2016-07-21%20at%2015.34.png?dl=0

Sounds like you're providing a file name and not an image.  Feel free to respond with your actual API request and I'll look again,  but I see nothing wrong here.

**Comment by kooliokey** [comment]
Hello!

Thanks for the response :) I've double checked and I'm providing an array of image objects to the API. I've put the JSON I am submitting to the API at the bottom of the post. Before I posted an issue I checked the API code that runs when you update a product and it checks if the id is 0 and if the src is set, then it tries to upload. The image object I have below is exactly how I get it from the API, so it is giving me an ID of 0.

Thanks!

````
{
  "tax_class" : "",
  "categories" : [

  ],
  "download_type" : "standard",
  "short_description" : "",
  "description" : "",
  "shipping_class" : "",
  "variations" : "",
  "dimensions" : "",
  "managing_stock" : false,
  "stock_quantity" : null,
  "name" : "Test Placeholder Issue More",
  "type" : "simple",
  "sku" : "",
  "purchase_note" : "",
  "id" : 262,
  "tax_status" : "taxable",
  "button_text" : "",
  "weight" : "0",
  "product_url" : "",
  "regular_price" : "7",
  "status" : "publish",
  "images" : [
    {
      "date_modified" : "2016-07-21T15:29:18.0Z",
      "src" : "https://wordpress.local/wp-content/plugins/woocommerce/assets/images/placeholder.png",
      "date_created" : "2016-07-21T15:29:18.0Z",
      "id" : 0,
      "alt" : "Placeholder",
      "position" : 0
    }
  ],
  "catalog_visibility" : "visible"
}
````

**Comment by mikejolley** [comment]
If you send a src when writing to the API, you're telling it to upload. Seems that you don't want to do this.

**Comment by kooliokey** [comment]
So I guess it's working as designed. Just seems odd that if I pass the same data the API gave me back to the API that it attempts to upload it again, but I guess I'll just have to stick with my workaround of removing placeholder images. Thanks!
