### ISSUE TITLE
checkout_update trigger reverts payment gateway selection when payment token present

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#11492]
When you have a saved payment token, it default to using that payment gateway with the payment token pre-selected which is working as intended.

However, if visit the checkout, then choose a payment gateway other than the one with the saved payment method, it will revert back to the payment gateway with the default payment token when you change something like the Country (which will trigger "checkout_update")

To reproduce:

1. Visit checkout
2. Saved default payment token should be pre-selected
3. Select a new payment gateway
4. Change Country (or similar, basically looking to trigger checkout_update)
5. On AJAX refresh it reverts the selected payment gateway back to the default payment token.

I came across this issue due to our third party plugin triggering checkout_update on payment gateway change in order to add a fee specific to the payment gateway (loads of third party plugins and custom code examples do this, eg. charge a fee for using cheque gateway) which then automatically reverted the gateway again meaning you couldn't change the payment gateway if there was saved payment token!

Ideally you would only pre-select the payment gateway with the default payment token on initial page load not after every checkout update. Basically if subsequent checkout_updated calls retained the selected payment gateway then this would avoid a whole host of issues with 3rd party code integration.

Alternatively another approach would be to provide additional filters for third party plugins to hook in and change the selected payment token during checkout update.

This issue is present on WooCommerce 2.6.x after Payment Token API was released. Happens on all themes.

**Comment by mikejolley** [comment]
@justinshreve

**Comment by mikejolley** [comment]
Closed in favour of #11501
