### ISSUE TITLE
Paypal IPN and echeck payment.

### ISSUE THREAD

**Issue by test101test101** [woothemes/woocommerce#11493]
One of the customers payed with echeck.
I don't understand how woo commerce handle it.
The status has changed to "On-Hold"
In paypal I see : `Shopping Cart Payment Received (Unique Transaction ID #UNIQUE_KEY) `
Why in woocommerce I don't see this unique key?
The order page contains:
```
Order #13474 details
Payment via PayPal. Customer IP: __________

```

Usually there is a transaction id right under that.

When echeck is completed will paypal send new IPN and then the status in woocommerce will change?
Its not clear how the system handle different payment methods.
if it's temp key why not display it until the permanent one?

**Comment by mikejolley** [comment]
When payment is not complete (due to cheque or other reason) the TXN Id might not be returned. When the cheque clears, the order will be updated with TXN ID and the completed/processing status.
