### ISSUE TITLE
Is it possible to add shipping method vendor specific ?

### ISSUE THREAD

**Issue by jacksperrow1988** [woothemes/woocommerce#11498]
@mikejolley , @claudiosmweb 

Hello Team,

Hope you are doing well.

Below is my requirement:

I have installed wc vendor plugin.  and I have below configurations:

Vendor 1:
Product Name: T-shirt

Vendor 2:
Product Name:  Mobile

so suppose I am admin of site and I want to allow vendor to create their shipping method.
So if Vendor 1 has created Flatrate shipping based on India = 5
and if Vendor 2 has created Flatrate shipping based on India = 10

So now in cart If I have 2 products in cart 

1 - T-shirt
2- Mobile

So now both shipping will be enable so at that time user can checkout using lowest shipping price and that I don't want to do. So would you please let me know how can I setup vendor specific shipping methods ? So all vendor have their own shipping methods.

Thanks

**Comment by mikejolley** [comment]
This is not a bug report. Use the forums/vendors support since this is not even core related.
