### ISSUE TITLE
do_action "woocommerce_api_process_product_meta_" has not been ported to new Woocommerce Api "/wp-json/wc/v1"

### ISSUE THREAD

**Issue by adoerler** [woothemes/woocommerce#11495]
## EXPLANATION OF THE ISSUE

After upgrading from 2.5 to 2.6 branch and switching to new api endpoint /wp-json/wc/v1 I've found out, that one do_action call is missing in function `save_product_meta`.

As we are using this action in our project, it would be great if you could readd it to the new API, as this would make woocommerce updates easier for us :)

## STEPS TO REPRODUCE THE ISSUE

You can easyly see this issue by comparing old and new file:
* Line 1723 form v2.5.5 https://github.com/woothemes/woocommerce/blob/2.5.5/includes/api/class-wc-api-products.php
* Line 1287 from v2.6.3 https://github.com/woothemes/woocommerce/blob/2.6.3/includes/api/class-wc-rest-products-controller.php

Here is a patch which would add the missing action to the function `save_product_meta` in the file `includes/api/class-wc-rest-products-controller.php`:
```
@@ -1285,6 +1285,8 @@ class WC_REST_Products_Controller extends WC_REST_
 			}
 		}
 
+		do_action( 'woocommerce_rest_process_product_meta_' . $product_type, $product, $request );
+
 		return true;
 	}
```

Please note that I've already renamed the action call from `woocommerce_api_process_product_meta_` to `woocommerce_rest_process_product_meta_`

Kind regards
Andreas

**Comment by mikejolley** [comment]
@claudiosmweb removed on purpose?

**Comment by claudiosmweb** [comment]
Yes, we did not ported any action or filter, since this is a complete new rest api.

**Comment by claudiosmweb** [comment]
Better use the new available filters and actions for it.

**Comment by adoerler** [comment]
@claudiosmweb 
but there is no "new" filter or action in function "save_product_meta" or have I missed something?

I'm using this action to update custom meta via REST using a patched version of plugin WC API Custom Meta (https://wordpress.org/plugins/wc-api-custom-meta/).

Is updating of custom meta data now possible through the new API? I'm talking about fields added bei Advanced Custom Fields Pro or any other extension adding fields to products or variations.

Kind regards and many thanks in advance
Andreas

**Comment by psopacua** [comment]
@claudiosanches 
what action/filter replaced that action? I've got the same situation as @adoerler
