### ISSUE TITLE
Rewrite rules are not saved in the correct order

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#11500]
I'm not sure whether this is a WooCommerce bug, a WordPress bug, or something environment related that nothing accounts for. Ran into this while debugging a support ticket.

The basic problem is that the rewrite rules that get saved to the database (with option name `rewrite_rules`) are in different order on two different machines given same codebase.

The setup:

* @WillBrubaker's DO box running WP 4.5.3, WooCommerce 2.6.3 (inactive), twenty fifteen
* my local mamp running WP 4.5.3, WC 2.6.3 (inactive), twenty sixteen

To reproduce, do these on both environments:

1. have all plugins deactivated
2. go to Settings -> Permalinks, and choose Plain
3. Check to see what the value of the `rewrite_rules` option is. It should be empty on both environments.
4. Go to Permalinks again, and select Post name.
5. Check the value of the `rewrite_rules`. Unserialize and compare them (https://www.diffchecker.com/diff is an easy to use tool). There should be minimal difference between them. The only one I had was about a page ID for a comment page.
6. Activate WooCommerce.
7. Check that the WC specific rewrite rules are the same. Set them to their defaults (clear the optional ones and use default for the product permalinks: https://cloudup.com/cWRXPHR1a5a
8. Save permalinks on both environments.
9. Check the option values.

These are the values that I have:
My local mamp: [local-3-wp-wc-default-wc-perms.txt](https://github.com/woothemes/woocommerce/files/376540/local-3-wp-wc-default-wc-perms.txt)
Will's DO box: [remote-3-wp-wc-default-wc-perms.txt](https://github.com/woothemes/woocommerce/files/376541/remote-3-wp-wc-default-wc-perms.txt)

PHP versions:

* local: 5.6.10 (works), with mod_rewrite
* remote: 5.5.9-1ubuntu4.9 with mod_rewrite

Both are using apache.

I am at a loss.

**Comment by javorszky** [comment]
.htaccess files are identical, both the stock versions that WP produces.

**Comment by WillBrubaker** [comment]
for reference and testing site creds: #441143-zd-woothemes

**Comment by mikejolley** [comment]
@javorszky I think your permalink configs/pages might differ. See if `$GLOBALS['wp_rewrite']->use_verbose_page_rules` is different on each install.

WC doesn't control the order of rules afaik

**Comment by javorszky** [comment]
This is the permalink settings on Will's box, which is broken: https://cloudup.com/cTVkGkVXoKO

And this is the permalink settings on my box, which works: https://cloudup.com/cp5Ck6Z5bGJ

The plot thickens, as use verbose page rules is set to true both locally and remotely (var_dump at the end of the function here: https://github.com/woothemes/woocommerce/blob/master/includes/wc-core-functions.php#L775).

**Comment by javorszky** [comment]
Reading settings remote (broken): https://cloudup.com/cN8Qz6J3FZe

Locally: https://cloudup.com/cXOkTl6vm7S

**Comment by javorszky** [comment]
I also put some logging here: https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-rewrite.php#L1434-L1437, and both sites reported that verbose page rules have been used.

**Comment by mikejolley** [comment]
@javorszky Can you grab the status reports from both sites as well - might be good to compare.

**Comment by javorszky** [comment]
Sure.

<details>
 <summary>Working Local's status report</summary>
 ```
### WordPress Environment ###

Home URL: http://127.0.0.1/derp
Site URL: http://127.0.0.1/derp
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 5.6.10
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.46.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path:

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.3

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>


<details>
 <summary>Broken Remote's status report</summary>
 ```
### WordPress Environment ###

Home URL: http://104.131.116.80/will
Site URL: http://104.131.116.80/will
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu) mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.9 OpenSSL/1.0.1f
PHP Version: ❌ 5.5.9-1ubuntu4.9 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.3

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Twenty Fifteen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
Yikes almost the same. I guess we'd have to add some output during rule generation in WP core to see what is changing/filtering results :/?

**Comment by mikejolley** [comment]
it's added by `add_filter( 'rewrite_rules_array', 'wc_fix_rewrite_rules' );` - there is some added logic to fix 404s with verbose page rules enabled.

What is the impact of that code? I wonder if we can move it somehow without removing it completely.
