### ISSUE TITLE
Add Regions for shipping zones

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#11509]
I'm not sure if this has been proposed already, but I can't find anything.

What do you think about adding regions for shipping zones?
In Italy, in example, we have almost always different costs based on the region, like in Sicily because it's an island.

Right now, you have to choose all the provinces or insert a range of zip codes for that region. While it would be useful to just select the region like we do for states.

**Comment by vkn999** [comment]
I think the same situation in many countries. Maybe this issue needs to be resolved by some plugin?

**Comment by mikejolley** [comment]
Then you'd need to somehow map regions to shipping addresses which isn't really workable, especially when its open text field and open to mistakes/typos/different spellings.

If regions are states in your case, you can contribute a state file.

Otherwise zip/postal codes are the best way in most places.

**Comment by jonathan-kosgei** [comment]
@mikejolley what about a dropdown of towns? In many developing countries the postal system is no good, ecommerce sites often send out parcels via courier services with pick up locations in different towns/cities

**Comment by RalfCT** [comment]
@jonathan-kosgei, you're absolutely right!  We have the same problem in South Africa.  The postal service is not always reliable and courier delivery is limited to major centers within the 9 provinces, at this point WooCommerce Shipping Options only allows me to select an entire province, not individual towns within that province.  Zip codes aren't an option as these cover large areas.  I want a situation where the customer can simply select his province and search for his town in a drop-down BEFORE he wastes his time entering all his Billing/Delivery details... if his town isn't listed we can't supply him and he cannot accidentally place an order. 

Can someone not come up with a WooCommerce tweak to address the above, there's definitely a need and thus a market for one?

**Comment by jonathan-kosgei** [comment]
@RalfCT I came up with a way to solve this using a custom plugin you can see the functionality on the order page of https://seedlingskenya.tk, I haven't had time to document how I did it, have a look and if it's something you need I could write it up as soon as I get a chance.

**Comment by RalfCT** [comment]
@jonathan-kosgei, I've had a look at the website above.  I placed an order for 100 chive and 100 cabbage seedlings after which I was still taken to the page where billing details need to be entered.  I want to add a step before this one, i.e. the customer has to select his Province and Town, only if he finds a match will he be able to proceed to the page where he fills in his billing details.  The whole procedure must tie in with weight based shipping, which I have already configured.

**Comment by jonathan-kosgei** [comment]
@RalfCT You could customise the cart for this, the current setup works for me because the user has to pick a town on the checkout page for shipping to be calculated.

**Comment by RalfCT** [comment]
@jonathan-kosgei, actually, your 'selection of town' may could work in my case.  I could then list the Province and the customer selects the town from a selection I've entered beforehand.  Which files did you edit, and how?

**Comment by RalfCT** [comment]
@jonathan-kosgei, my shipping costs are already calculated by the weight-based-shipping plugin, the town drop-down will simply allow my customer to complete his Checkout process.

**Comment by RalfCT** [comment]
@jonathan-kosgei, did you use Checkout Manager to create the drop-down of towns?  If yes, please let me know how.

**Comment by RalfCT** [comment]
@jonathan-kosgei, did you use Checkout Manager to create the drop-down of towns?  If yes, please let me know how.

**Comment by RalfCT** [comment]
@jonathan-kosgei, by perseverance the snail reached the ark. :)  I manged to add my list of Towns by tweaking the conditions for the Billing/Shipping "Town / City" field, using the WooCommerce Checkout Manager.  Now my customers can only complete their order if they select one of the towns in the list (required field).

**Comment by jonathan-kosgei** [comment]
Glad to hear it :). Here's my code for reference
```
$towns_cities_arr = array(
    '0' => __('Select your city', 'my_theme_slug'),
    '1' => 'Ahero',
    '197' => 'Amagoro',
    '198' => 'Amonding',
    '199' => 'Amukura',
    '492' => 'Angurai',
    '200' => 'Asumbi',
    '2' => 'Athi river',
    '201' => 'Awasi'.
... >500
}
add_filter( 'woocommerce_default_address_fields' , 'customize_checkout_city_field', 99999);
function customize_checkout_city_field( $address_fields ) {

    // Set HERE the cities (one line by city)
    $towns_cities_arr = $GLOBALS['towns_cities_arr'];

    // Customizing 'billing_city' field
    $address_fields['city']['type'] = 'select';
    $address_fields['city']['class'] = array('form-row-last'); // your class here
    $address_fields['city']['label'] = __('Town / city', 'storefront');
    $address_fields['city']['options'] = $towns_cities_arr;

    // Returning Checkout customized fields
    return $address_fields;
}
```
To enable `select2` (to make my long list of towns searchable) use
```
<?php
// Using the select2 plugin

function select2() {
?>
<script type="text/javascript">

    jQuery(document).ready(function( $ ) {
      $(".select").select2();
    });

</script>
<?php
}
add_action( 'wp_footer', 'select2' );

function ensure_jquery() {
    wp_enqueue_script( 'jquery' );
}
add_action( 'wp_head' , 'ensure_jquery' );

function admin_select2() {
?>
<script type="text/javascript">

    jQuery(document).ready(function( $ ) {
      $(".select").select2();
    });

</script>
```

**Comment by madivad** [comment]
Good to see this is re-opened. Since I'm from an area where postcodes (can) cover many districts, a better system needs to be added. The google API and mapping makes zoning pretty simple, town/district/locality names alone are even simpler.

Any improvements on the basics of this would be welcomed.

**Comment by SilverNodashi** [comment]
> 
> 
> @jonathan-kosgei, by perseverance the snail reached the ark. :) I manged to add my list of Towns by tweaking the conditions for the Billing/Shipping "Town / City" field, using the WooCommerce Checkout Manager. Now my customers can only complete their order if they select one of the towns in the list (required field).

Hi, 

Would you mind telling me how you did this?

**Comment by DanielFloris** [comment]
I would just like to highlight, that New Zealand (size 268,021 km²) has 16 regions to choose from, whereas Australia (size 7.692 million km²) (29 times bigger) has 8 regions you can select. Whoever is creating these regions needs to reassess.

**Comment by byteknight1** [comment]
There are many regions which are far away and needs divided shipping within states.
For those who still facing problem, below solution may work.

I added custom states in specific countries using below

Add code to your child theme’s functions.php file or via a plugin that allows custom functions to be added, such as the Code snippets plugin. Avoid adding custom code directly to your parent theme’s functions.php file as this will be wiped entirely when you update the theme.

Add your own or modify shipping states in WooCommerce.

Note: You must replace both instances of XX with your country code. This means each state id in the array must have your two letter country code before the number you assign to the state.

`/**
 * Add or modify States
 */
add_filter( 'woocommerce_states', 'custom_woocommerce_states' );

function custom_woocommerce_states( $states ) {

  $states['XX'] = array(
    'XX1' => 'State 1', 
    'XX2' => 'State 2'
  );

  return $states;
}
`
Source – Add / Modify States woocommerce

**Comment by developer-mohamed-saad** [comment]
Hello 

I wanted to let you know also about this plugin i think it can help you doing so 

https://wordpress.org/plugins/shipping-manager-for-woocommerce/

Adds custom cities with rates and also it adds WooCommerce shipping zones so easily on [Pro Version]

https://wpsaad.com/shipping-manager-for-woocommerce/

and got so many great features for shipping.
