### ISSUE TITLE
[REST API] Is it possible to create an order and charge a credit card?

### ISSUE THREAD

**Issue by kainjow** [woothemes/woocommerce#11504]
With the 2.6 API, is it possible to create an order with a credit card?

The documentation only references "Direct Bank Transfer". However, we are using the [Elavon plugin](https://woocommerce.com/products/elavon-vm-payment-gateway/) for credit card processing. I am able to create orders like so:

    curl -X POST https://example.com/wp-json/wc/v1/orders \
        -u key:secret \
        -H "Content-Type: application/json" \
        -d '{
      "payment_method": "elavon_vm",
      "payment_method_title": "Credit Card",
      "customer_id": 11,
      "line_items": [
        {
          "product_id": 16623,
          "quantity": 1
        }
      ]
    }'

This creates the order, but I don't see any options to specify additional details for the payment method.

If this is not possible, is the solution to charge the credit card processor directly, and then store the transaction ID into "transaction_id"?

We are essentially trying to integrate in-app purchasing with our desktop software.

**Comment by mikejolley** [comment]
Gateways/payments are not handled via the API. Only order creation itself.

**Comment by biswajit-paul** [comment]
@kainjow I look into latest WooCommerce v4 routes. There is an transaction id parameter over there. You can make a transaction through API and pass the transaction id into order object.

![Screenshot_2019-06-12 Screenshot](https://user-images.githubusercontent.com/14993725/59353253-2fbf4b80-8d40-11e9-8ca9-366212e36542.png)
