### ISSUE TITLE
Filters request for backorders naming

### ISSUE THREAD

**Issue by pdobrescu** [woothemes/woocommerce#11505]
There is a nice [plugin](https://github.com/anttiviljami/woocommerce-custom-availability) built by @anttiviljami which sets a custom message (on a per-product basis) for items not in stock, such as `Ships in 2 weeks`.

While on the product page you can easily filter the backorder message, it's not the same on the `cart` page and on the `thank-you/checkout` page. The simple way to solve this is to add some additional filters for the text that shows up on those pages, making the information persistent for the customers. Looking at the code, for the `cart` page, I'd say the place to add that filter is here:

https://github.com/woothemes/woocommerce/blob/master/templates/cart/cart.php#L92

While for the `thank-you` page, it's not very clear to me as I haven't studied the whole WC code. A wild guess is that the backorder info is stored in a meta and gets displayed here:

https://github.com/woothemes/woocommerce/blob/master/templates/order/order-details-item.php#L38

Do you think the corresponding filters can be added in a future plugin version, for being able to update the plugin and close its [1st issue](https://github.com/anttiviljami/woocommerce-custom-availability/issues/1)? :-)

Thanks!

**Comment by mikejolley** [comment]
@pdobrescu why doesn't the author submit a PR? Be best if they did so they can test it covers their use case first.
