### ISSUE TITLE
Unable to load image in Product Categories

### ISSUE THREAD

**Issue by vkn999** [woothemes/woocommerce#11502]
In Woocommerce 2.6.3 Products >> Categories>> Upload/Add image unable to load image
![add_category_image1](https://cloud.githubusercontent.com/assets/14319784/17033427/c458201e-4f86-11e6-8f8e-3fea19b9cd73.png)
And after click "Refresh":
![add_category_image2](https://cloud.githubusercontent.com/assets/14319784/17033445/e1227ae6-4f86-11e6-97cc-36cb66e73201.png)
Result:
![add_category_image3](https://cloud.githubusercontent.com/assets/14319784/17033473/faafe4bc-4f86-11e6-9382-fd6262928ea4.png)
In Woocommerce 2.6.2 this works perfectly with the same image.

**Comment by mikejolley** [comment]
This is down to your server/install - the images cannot be loaded. If you're running SSL ensure the entire site is over HTTPS including admin.
