### ISSUE TITLE
Impossible get featured products by filter param

### ISSUE THREAD

**Issue by johuder33** [woothemes/woocommerce#11518]
I am trying to get all featured products by filter params but it is impossible, has not effect over the request

```
http://localhost:8888/solid-wp/wp-json/wc/v1/products?filter[meta_key]='_featured'&filter[meta_value]='yes'
```

but has not effect with that, just return de normal 10 first products,

please can anyone help me ?

**Comment by mikejolley** [comment]
Use 'meta_query' for now. I'll add support for meta_key in future version.

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Class_Reference/WP_Query
