### ISSUE TITLE
Empty cart doesn't get 'woocommerce' body class

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11521]
Empty cart doesn't get 'woocommerce' body class

**Comment by roykho** [comment]
Cart page uses the `woocommerce-cart` body class. You can use that for manipulation.

**Comment by manake** [comment]
I will but woocommerce.css has 

```
.woocommerce .woocommerce-error,
.woocommerce .woocommerce-info,
.woocommerce .woocommerce-message
```

so I thought that this CSS class is supposed to be on every WC page. It would be good to have some class like that everywhere.

**Comment by roykho** [comment]
You could custom add it via the filter `body_class`

**Comment by manake** [comment]
Yes, I can, thank you for your suggestions.

The point of me submitting this ticket is not to get help but to report something that potentially qualifies as a fix for the main package. If you think this is the right behavior then this ticket can be closed. I don't know if this is the right behavior myself because there are various classes added to the body tag and "woocommerce" class is (unexpectedly) added to widgets as well (where I would rather expect `woocommerce-widget`).

If there is some logic there then this ticket can be closed.

**Comment by mikejolley** [comment]
See `wc_body_class` function for the logic. Cart gets slightly different classes it's a regular page, not a WC generated page like archives. woocommerce-page is constant across all.
