### ISSUE TITLE
Checkout - initial AJAX request

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11522]
Right after entering the checkout page it's performing an AJAX request even if I didn't do anything yet.

Furthermore, when I put "totals" data outside of the table in /checkout/review-order.php it becomes duplicated after every AJAX request. This limits customization capabilities but I don't know what would be the correct solution for that if WC decided to fix this.

Maybe everyone who customizes /checkout/review-order.php should indicate all containers that should be removed and loaded again with something like data-template="review-order.php".

Both these behaviors were unexpected to someone who's customizing that template for the first time ever so it might be worth investigating.

Update: I'm finding similar issues https://support.woothemes.com/hc/en-us/articles/204314075-I-see-two-Proceed-to-checkout-buttons-and-or-two-checkout-payment-forms and I don't think this is not a theme issue like support answers there. It's something WC can do differently.

To fix this the theme needs to make a lot of custom modifications to class-wc-ajax.php (it has hardcoded CSS class) that shouldn't be necessary if WC was replacing all containers or if the content of review-order.php was wraped in a more general DIV (with a sole purpose of being used for AJAX) rather than table.

**Comment by mikejolley** [comment]
The current flow requires the refresh; it passes any saved address info fields to the calculation functions, and updates fields based on the user's address if there are differences from the base location.

This won't be resolved until we re-do the process in https://github.com/woothemes/woocommerce/issues/10672 - that includes how you move things around.

Look at storefront to see what things can be moved/how. Storefront changes the checkout layout with a sidebar payment form.
