### ISSUE TITLE
wp_terms_checklist_args filter in class-wc-admin-taxonomies.php missing an argument.

### ISSUE THREAD

**Issue by italianst4** [woothemes/woocommerce#11526]
## EXPLANATION OF THE ISSUE

When trying to use wp_terms_checklist for a new taxonomy added to the product post type, it errors out with the following:

Notice: Undefined index: taxonomy in /Users/amontalbano/git/wdi-wordpress/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-taxonomies.php on line 361

I'm using Woocommerce version 2.6.3

## STEPS TO REPRODUCE THE ISSUE

Create a new taxonomy for products.
Create a custom metabox to output the taxonomy using wp_terms_checklist().
You'll get the error above.

I have the solution to this, which is rather simple, that I can resolve this.  Either I can make a pull request to make the change or someone can fix it doing the following:

Edit the following two lines in /woocommerce/includes/admin/class-wc-admin-taxonomies.php
Line 51: add_filter( 'wp_terms_checklist_args', array( $this, 'disable_checked_ontop' ), 10, 2);

Line 359: public function disable_checked_ontop( $post_id, $args ) {

This adheres to the 2 variables passed through to this filter as seen on line 98 here: https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-admin/includes/template.php#L98

Let me know if you have any questions.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://wdi.local
Site URL: http://wdi.local
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 5.6.10
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (9) ###

Gravity Forms: by rocketgenius – 2.0.3
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.1.0
Advanced Custom Fields PRO: by Elliot Condon – 5.3.10
WDI Publishing Custom Functionality: by AMBR Detroit – 1.0.0
WooCommerce CyberSource SA SOP Gateway: by WooThemes / SkyVerge – 2.6.0
WooCommerce: by WooThemes – 2.6.3
WooThemes Helper: by WooThemes – 1.6.2
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.5
WP Migrate DB Pro: by Delicious Brains – 1.6.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wdi_case_study (wdi_case_study)

### Theme ###

Name: WDI Publishing Custom Design
Version: 1.0.0
Author URL: https://ambrdetroit.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: wdi-design/woocommerce/content-single-product.php

### CyberSource SA SOP ###

Environment: Test

### CyberSource SA SOP eCheck ###

Environment: Test
`

**Comment by mikejolley** [comment]
If you look at the docs for wp_terms_checklist, taxonomy is a field that should be passed. Maybe you're using it wrong?

**Comment by italianst4** [comment]
@mikejolley I agree, taxonomy is required, which is being passed, that's not the issue.  The wp_terms_checklist_args filter takes two arguments and in Woocommerce it's only taking in one.  My suggestion was to update the filter to accept both arguments.

**Comment by mikejolley** [comment]
Doesn't need both.

https://developer.wordpress.org/reference/hooks/wp_terms_checklist_args/

Post ID is not needed here.

**Comment by italianst4** [comment]
Got it. 

—
Sent really fast from mobile. Really, really fast. 

AMBR Detroit 
We build things. Web things. 
Office: 313-444-8004
Cell: 586-242-4157
“Keep making moves."




On Tue, Jul 26, 2016 at 11:30 AM -0400, "Mike Jolley" <notifications@github.com> wrote:












Doesn't need both.



https://developer.wordpress.org/reference/hooks/wp_terms_checklist_args/



Post ID is not needed here.
