### ISSUE TITLE
Feature request: hooks to add fields to Attributes and Global Add-ons

### ISSUE THREAD

**Issue by nimmolo** [woothemes/woocommerce#11529]
It is impossible to hook into admin functions for **Attributes** or  **Global Add-ons** to add extra fields, like "description" or "thumbnail". ACF can't add fields to them either. I need some extra fields.

While it is possible to add these at the **variation** level, an attribute is not the same as a product variation. In a highly configurable product such as a personal computer, the attribute is the _hard drive_, the variation is the _computer with whatever hard drive_. And it can be very helpful to have a graphic and a description to tell the client exactly what **attribute** they are configuring (the monitor, hd, keyboard, mouse) and why you'd want one or the other option. 

In my case, configured plumbing systems, these fields are pretty essential.

For a post_type like **Add-ons**, it seems to me the most WP way to add these two fields would be to enable them via swtiches in the post_type declaration: `'supports' => $selected` where $selected is an `array( 'title', 'thumbnail', 'excerpt' )` chosen by the user on a Settings page. For a taxonomy like **Attributes** maybe hooks would do. In any case, the problem is these objects both seem impervious to modification, without redeclaring the classes that create them as suggested in #7105.

**Comment by mikejolley** [comment]
Attributes are standard WP terms - the admin screens for attributes have standard WP hooks that you can use. The same hooks we use to add category images. Use those.

If I'm missing something, raise a PR so its clear.

**Comment by nimmolo** [comment]
@mikejolley I am digging into it now, thanks. Is that also true for Global Add-ons (via the paid Product Add-ons plugin)? That's where i really need the extra fields.

Why is ACF not able to add any metaboxes to those edit screens? It would be easier.

**Comment by nimmolo** [comment]
Hooking into attribute admin screens is actually a bit more complicated!  Each attribute is a separate taxonomy and therefore the hooks are each uniquely named.

For product category images, the hooks are `product_cat_add_form_fields` and `product_cat_edit_form_fields`.

But for attribute "Wheel width", the hooks might be `pa_wheel-width_add_form_fields` - you have to loop through all the attributes?

**Comment by nimmolo** [comment]
#11549 PR
