### ISSUE TITLE
Add product object to filter for is_in_stock() function

### ISSUE THREAD

**Issue by sembisoft** [woothemes/woocommerce#11528]
At the moment, the product object is not passed as a variable in the filters for the is_in_stock() functions. We are working on a plugin to use an alternative stock level for users with a **wholesale** user role, but we are unable to set the correct **in_stock** status without passing the product object.

I propose that the following changes are made:

**class-wc-product-variation.php** line 439
change 
`return apply_filters( 'woocommerce_variation_is_in_stock', $status );`

to 
`return apply_filters( 'woocommerce_variation_is_in_stock', $status, $this);`

**abstract-wc-product.php** line 624

change 
`return apply_filters( 'woocommerce_product_is_in_stock', $status );`

to 
`return apply_filters( 'woocommerce_product_is_in_stock', $status, $this);`

This would allow us to use this filter to get the desired instock status for the current product.

**Comment by mikejolley** [comment]
Already in master/2.7

**Comment by sembisoft** [comment]
Fantastic, thank you.
