### ISSUE TITLE
[API] cURL Error: Empty reply from server 

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#11535]
Hi,

I have the following script that gets all products from a website

    try {
        $return = $this->woocommerce->get('products', array('filter[limit]' => 100000));
    } catch (HttpClientException $e) {
        print_r($e);
    }

When I open i.e. 5 tabs that run the script, then not all requests are handled properly. Instead some of the instances jump into the catch-clause and receive an empty reply, saying:

     cURL Error: Empty reply from server 

Unfortunately I need to have multiple instances calling this script.

Is there any solution?

Cheers,
Adis

**Comment by mikejolley** [comment]
Look at **server** error logs. All tabs would break if it were a bug in WC. 

http://serverfault.com/questions/546787/how-to-troubleshoot-connectivity-when-curl-gets-an-empty-response
http://stackoverflow.com/questions/1924434/curl-error-52-empty-reply-from-server
