### ISSUE TITLE
Cannot update order with line item,fee line,shipping line from json. Error: Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Invalid JSON returned' in /home/builhsqv/public_html/test/wc/src/WooCommerce/HttpClient/HttpClient.php:332 Stack trace: #0 

### ISSUE THREAD

**Issue by Rachit-Dev** [woothemes/woocommerce#11538]
## EXPLANATION OF THE ISSUE
I am integrating woocommerce with external application and trying to update an order from external system. I convert the json which i get from external application to data array and pass that array in order update put method.

## STEPS TO REPRODUCE THE ISSUE
json string - '{
  "status":"pending",
  "shipping_lines":[
    {
      "total":"12.00",
      "method_title":"Train transport",
      "method_id":"awd_shipping",
      "id":1386
      
    }],
  "shipping":{
    "state":"",
    "postcode":"123445",
    "last_name":"Thakur",
    "first_name":"Yashwant",
    "country":"SG",
    "company":"Scholastic",
    "city":"",
    "address_2":"",
    "address_1":"22c"
  },
  "set_paid":false,
  "payment_method_title":"N/A",
  "payment_method":"",
  "customer_note":"",
  "customer_id":1,
  "billing":{
    "state":"CH",
    "postcode":"123445",
    "phone":"7814024414",
    "last_name":"Thakur",
    "first_name":"Yashwant",
    "email":"bobbyaryan160@gmail.com",
    "country":"SG",
    "company":"Scholastic",
    "city":"Chandigarh",
    "address_2":"#2688",
    "address_1":"22c75"
  }
}
'
 $entityBody=decode that into data array by json_decode().
$woocommerce->put($'orders/'.$id, $entityBody);

## SYSTEM STATUS REPORT

```
Warning: in_array() expects parameter 2 to be array, null given in /home/builhsqv/public_html/test/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 746

Warning: in_array() expects parameter 2 to be array, null given in /home/builhsqv/public_html/test/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 746

Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Invalid JSON returned' in /home/builhsqv/public_html/test/wc/src/WooCommerce/HttpClient/HttpClient.php:332 Stack trace: #0 /home/builhsqv/public_html/test/wc/src/WooCommerce/HttpClient/HttpClient.php(371): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 /home/builhsqv/public_html/test/wc/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('orders/9920', 'PUT', Array) #2 /home/builhsqv/public_html/test/wc/RestUpdateOrder.php(50): Automattic\WooCommerce\Client->put('orders/9920', Array) #3 {main} thrown in /home/builhsqv/public_html/test/wc/src/WooCommerce/HttpClient/HttpClient.php on line 332
```

**Comment by mikejolley** [comment]
Please post in the correct place - https://github.com/woothemes/wc-api-php/issues

**Comment by Rachit-Dev** [comment]
done.
