### ISSUE TITLE
Sell On Third Party Websites

### ISSUE THREAD

**Issue by mkhandouzy** [woothemes/woocommerce#11530]
I'm running a museum and want an online ticket selling system. I have a woocommerce installed on my wordpress and tieckera add-on on top of my woocommerce. I'm selling tickets over woocommerce, that's awesome, THANKS TO WOOCOMMERCE TEAM!!!
I have only one problem, I want to sell my ticket on other sites, other tour agencies, Can I sell my product on other websites and solve their commission issues? Does rest API help me?

Thanks
Best Regards,

**Comment by mikejolley** [comment]
They would need to link through to your cart/checkout. It wouldn't be 'direct'.
