### ISSUE TITLE
Invoice Link invalid for customer-processing-order email

### ISSUE THREAD

**Issue by johannesmutter** [woothemes/woocommerce#11537]
## EXPLANATION OF THE ISSUE

In 2.6.4 the invoice link sent in the customer-processing-order email or order receipt email is invalid. When user clicks on “view invoice” the message appears “You are not allowed to view this page.”

The problem is in order_paid_email_view_invoice_link() in line 252 - 255.
The url returned by the function get_print_invoice_url() is false:
This it what I currently get:
account/?wc_pip_action=print&wc_pip_document=invoice&order_id=123456&_wpnonce=XXX

But this is what it should look like (this one worked in previous versions):
account/view-order/123456/?wc_pip_action=print&wc_pip_document=invoice&order_id=123456&_wpnonce=XXXX

## STEPS TO REPRODUCE THE ISSUE

Create an order with pending payment.
Open order receipt email.
Click on view invoice.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (XX) ###

User Role Editor Pro: by Vladimir Garagulya – 4.27.1
WooCommerce: by WooThemes – 2.6.4
WooThemes Helper: by WooThemes – 1.6.2

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4563 - /products/
Basket: #402 - /cart/
Checkout: #403 - /checkout/
My Account: #404 - /account/

### Taxonomies ###

Product Types: appointment (appointment)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


WooCommerce Support: ✔

````

**Comment by mikejolley** [comment]
wc_pip_action is not part of WC core.

**Comment by mikejolley** [comment]
Yeah you're talking about an extension, not core. WooCommerce PIP.

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>   - https://wordpress.org/support/plugin/woocommerce for general support
>   - https://support.woothemes.com for premium plugin support

**Comment by mikejolley** [comment]
Hiding active plugins from the report is also not a great idea for getting help :)
