### ISSUE TITLE
Multiple Zone issue

### ISSUE THREAD

**Issue by todd0218** [woothemes/woocommerce#11546]
## EXPLANATION OF THE ISSUE

When we setup a flat rate zone, and also setup a free shipping zone, both to USA then use drag and drop to order the newly created zones, they cause errors to one another. If for instance I make the Free shipping one the first and the flat rate second, the free shipping one will cause the flat rate to say "There are no shipping methods available. Please double check your address, or contact us if you need any help" when the free shipping requirements are not met. 

If free shipping requirements are met the free shipping appears and flat rate is hidden (desired outcome)

If free shipping is listed 2nd in priority below flat rate, free shipping will not work or show when the minimum requirements are made. 
   2.6.4

## STEPS TO REPRODUCE THE ISSUE

1. create a flat rate zone, select United States as the region and set method as flat rate. 
2. now create a shipping class, ours we names flat rate. 
3. go to products select all products and edit, then associate all products to the newly created shipping class and click save. 
4. go back to shipping tab>shipping zones>then click the flat rate option created in step 1. 
5. put a price under the class created ours we put $4.99  then save.
5. create the free shipping zone. Set the region to united states and shipping method to free shipping
6. click free shipping, and set to a minimum order amount, then set minmum order amount $39.99

now drag and drop the free shipping zone above the flat rate and save changes. 

7. visit the website and place items in your cart you will now see the error. to get rid of the error go back to shipping zones and drag and drop the free option below flat rate. Flat rate will begin working however when you meet the minmum order value requirements free no longer works. 
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
WordPress Environment
Home URL:		http://www.happyhowies.com
Site URL:		http://www.happyhowies.com
WC Version:		2.6.4
Log Directory Writable:		 /var/www/html/wp-content/uploads/wc-logs/
WP Version:		4.5.3
WP Multisite:		–
WP Memory Limit:		256 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache/2.4.7 (Ubuntu)
PHP Version:		 5.5.9-1ubuntu4.16 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size:		55 MB
PHP Time Limit:		30
PHP Max Input Vars:		1000
cURL Version:		N/A
SUHOSIN Installed:		–
MySQL Version:		5.6.27
Max Upload Size:		55 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.4
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /var/www/html/wp-content/uploads/GeoIP.dat
Active Plugins (20)
Gravity Forms	 	by rocketgenius – 1.9.19
iThemes Security	 	by iThemes – 5.6.0
Captcha by BestWebSoft	 	by BestWebSoft – 4.2.2
Contact Form 7	 	by Takayuki Miyoshi – 4.4.2
Pinterest Verify	 	by Phil Derksen – 1.0.4
PixelYourSite	 	by PixelYourSite – 3.0.3
Regenerate Thumbnails	 	by Alex Mills (Viper007Bond) – 2.2.6
SendGrid	 	by SendGrid – 1.9.0
Woobox	 	by Woobox – 1.0
WooCommerce Cart Notices	 	by WooThemes / SkyVerge – 1.6.0
WooCommerce Custom Product Tabs Lite	 	by SkyVerge – 1.5.0
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway	 	by WooThemes – 4.4.3
WooCommerce Advanced Product Quantities	 	by WP BackOffice – 2.1.9
WooCommerce MailChimp	 	by Adam Anderly – 1.3.7
WooCommerce Pinterest Pin-it Button	 	by 61 Extensions – 1.0
WooCommerce Thumbnail Input Quantities	 	by WP BackOffice – 1.1.2
WooCommerce	 	by WooThemes – 2.6.4
WooCommerce Helper	 	by WooCommerce – 1.7.0
Yoast SEO	 	by Team Yoast – 3.4
WP Super Cache	 	by Automattic – 1.4.8
Settings
Force SSL:		
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		
WC Pages
Shop Base:		#6277 - /happy-howies-products/
Cart:		#351 - /cart/
Checkout:		#352 - /checkout/
My Account:		#353 - /my-account/
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Enfold
Version:		3.6.1
Author URL:		http://www.kriesi.at
Child Theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		
Templates
Overrides:	 	–

**Comment by claudiosmweb** [comment]
This happens because you have two equal shipping zones... so for all intents and purposes you have only one zone... Since both are only for US. In this case you can include the Flat Rate and the Free Shipping into only one shipping zone. Or limit the free shipping into a shipping zone limited by states or postcodes or anything more than the US area.

**Comment by todd0218** [comment]
thanks claudio! I didn't realize I was doing this incorrectly. If you don't mind me asking is there a way to set the default? So when the Free shipping appears it becomes the default?

**Comment by claudiosmweb** [comment]
You can put the free shipping at the top inside your shipping zone.
