### ISSUE TITLE
Update to 2.6.4. deletes some product attributes

### ISSUE THREAD

**Issue by peterkorchnak** [woothemes/woocommerce#11550]
## EXPLANATION OF THE ISSUE

After I updated to 2.6.4., Product > Attributes > Color (apparel) disappeared from the attributes list. 

## STEPS TO REPRODUCE THE ISSUE

1. Update to 2.6.4.
2. Lose attribute Color.
3. Recreate attribute Color.
4. TWO Color attributes show up.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: https://thesaladlobby.com
Site URL: https://thesaladlobby.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.23
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.23
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (27) ###

A2 Optimized WP: by A2 Hosting – 2.0.3
Akismet: by Automattic – 3.1.11
Better Click To Tweet: by Ben Meredith – 4.7.1
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.2

EWWW Image Optimizer: by Shane Bishop – 2.9.3
Google Analytics: by Kevin Sylvestre – 1.0.6
MailChimp: by MailChimp – 1.5.1
Make Plus: by The Theme Foundry – 1.7.4
Menu Image: by Alex Davyskiba aka Zviryatko – 2.6.7
No Self Pings: by Michael D. Adams – 0.2
Printful Integration for WooCommerce: by Printful – 1.2.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Relevanssi: by Mikko Saari – 3.5.3
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
SeedProd Coming Soon Pro: by SeedProd – 5.0.26
Ultimate Social: by WPSmarter – 6.0.7
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.3
WooCommerce: by WooThemes – 2.6.4
Wordfence Security: by Wordfence – 6.1.12
Yoast SEO: by Team Yoast – 3.4
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.5
WP Migrate DB Pro: by Delicious Brains – 1.6.1
WP Rollback: by WordImpress – 1.3
WP Sitemap Page: by Tony Archambeau – 1.5.6
YITH WooCommerce Quick View: by YITHEMES – 1.1.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #15 - /shop/
Cart: #23 - /cart/
Checkout: #24 - /checkout/
My Account: #25 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Make (child theme)
Version: 1.1.0
Author URL: https://thethemefoundry.com
Child Theme: ✔
Parent Theme Name: Make
Parent Theme Version: 1.7.5 – 1.7.7 is available
Parent Theme Author URL: https://thethemefoundry.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Unable to replicate based on the information given. I notice you have some DB migration plugins active - you may have been missing the woocommerce_attribute_taxonomies table, or had a transient without these values stored.
