### ISSUE TITLE
Free shipping not selected by default when it was not added as the first method in the shipping zone

### ISSUE THREAD

**Issue by samuelaguilera** [woothemes/woocommerce#11551]
## EXPLANATION OF THE ISSUE

In WC 2.6.x free shipping is not selected by default in the cart when the user is eligible for it but free shipping method was not added as the first shipping method in the shipping zone setup.

In WC 2.5.x (and older) free shipping is selected by default in the cart when free shipping is available for the user. No matter the display order or even if all shipping methods have the same selection priority, free shipping is always the default selected method when it's available.

## STEPS TO REPRODUCE THE ISSUE

1. Create any shipping zone.
2. Add Flat Rate to your shipping zone.
3. Click the Flat Rate method and set any amount in Cost.
4. Add Free Shipping to your shipping zone.
5. Go to your store and add some products to the cart.
6. Go to cart.

**Free shipping should be selected by default, but flat rate is selected instead.**

Using the drag and drop to change the order of the shipping methods doesn't help, the only way to fix this is to remove completely both shipping methods and add them again, but this time adding free shipping first.

All tests were done using a fresh installation of WC 2.6.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://localhost/woocommerce
Site URL: https://localhost/woocommerce
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24-1+deb.sury.org~trusty+1
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (31) ###

WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #292 - /shop/
Cart: #293 - /cart/
Checkout: #294 - /checkout/
My Account: #295 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
The top method is selected by default regardless, if available. Changing this would lead to inconsistency which we no longer want.

**Comment by samuelaguilera** [comment]
so you changed the default shipping behavior and removed the ability to change the default method without having to reconfigure again all methods and you think that fixing that would lead to a inconsistency? interesting...

**Comment by mikejolley** [comment]
@samuelaguilera No Samuel, zones is a new system. So 2.5 and below styling shipping methods no longer exist, and thus the sorting/default selection they used to use also does not exist.

**Comment by samuelaguilera** [comment]
@mikejolley A new system should make things easier not harder. What's the point in not allowing the store owner to choose what shipping method should be used by default in the shipping zone? 

I can't see any sense in forcing a store owner to remove all shipping methods in a zone and adding them again and configure all settings in each one simply to change the default method. What if you want to set a new shipping as default in three different zones? You need to put the site in maintenance and reconfigure all methods in all the three zones just because WC 2.6 lacks a way to set the default method. Do you really think this is a good user experience?

You want to use the top method as default, ok that makes sense, but then when the store owner moves a shipping method to the top in a zone it should be the default also. Not doing that is the real inconsistency here.

**Comment by mikejolley** [comment]
Whats the point is allowing a global default when it could vary in each zone?

Whats the point is offering yet another UI on top of zones just to choose a default?

Whats the point is forcing them to choose 1 default when that default might not be available? What comes next?

There are arguments for both ways. This way works better with zones. If you don't like it, there are filters available.

**Comment by mikejolley** [comment]
> I can't see any sense in forcing a store owner to remove all shipping methods in a zone and adding them again and configure all settings in each one simply to change the default method. 

You do realise they are sortable..

**Comment by mikejolley** [comment]
![2016-07-29 at 22 03](https://cloud.githubusercontent.com/assets/90977/17263324/5b80f2ca-55d8-11e6-8618-fdb4c07a98b0.png)

**Comment by samuelaguilera** [comment]
> Whats the point is allowing a global default when it could vary in each zone?
> 
> Whats the point is offering yet another UI on top of zones just to choose a default?
> 
> Whats the point is forcing them to choose 1 default when that default might not be available? What comes next?

I'm not asking for any of the above. And I know that shipping methods are sortable since the start of this issue, just read my original message:

> Using the drag and drop to change the order of the shipping methods doesn't help

What I have tried to explain you many times already (and I'm not sure if you're just not reading my messages in full) is that moving the shipping method inside of a zone to the top of the list using the sorting should also change set that as the default method.

> The top method is selected by default regardless

Well that is not what WC is doing now.

In your screenshot, if you use the sorting icon to move Flat Rate 2 to the top of the list in that zone, Flat Rate 2 should become the default shipping for that zone. If Flat Rate 2 is removed for that zone at some point, then the Flat Rate 1 should become the default method in the zone. 

Sincerely I can't believe this... But I'm not going to make any more efforts trying to make you see how ridiculous is not having a way in WC interface to set default shipping method in the zones.

**Comment by mikejolley** [comment]
After you move it to the top, are you saving? Have you checked it's not cache? Top is default. You don't need to delete and re-add methods as you suggested. That would be ridiculous.

**Comment by samuelaguilera** [comment]
> After you move it to the top, are you saving? 

Yes I'm clicking the save changes button after moving the method to the top.

> Have you checked it's not cache? 

If you check the system report included you will see that I'm running latest WP without any other plugin and using WP default theme, no caching of any kind (no plugin, no server side, none). I'm also able to reproduce in other sites hosted in different servers.

> Top is default. You don't need to delete and re-add methods as you suggested. 

I took my time to fill the issue report with all the information required, have you taken the time to read it? And to try to reproduce the issue before closing the issue?

> That would be ridiculous.

**That IS ridiculous**, and the only way to change default method in a zone in WC 2.6.4.

Can you please just try to reproduce the issue at your side?

**Comment by mikejolley** [comment]
Yes I tried it. I have shipping debug mode on to disable caching though. Try it.

**Comment by mikejolley** [comment]
I'm afk till morning anyhow. Debug is in system status > tools.

**Comment by claudiosmweb** [comment]
I just tested 2.6.4 and works fine.

**Comment by samuelaguilera** [comment]
Same result with shipping debug mode enabled. I can see the order change in the front-end, but Flat Rate is still selected by default when it's the second method in the list.

![image201607005](https://cloud.githubusercontent.com/assets/1039772/17265046/da363482-55eb-11e6-81f7-a48d418e5d41.png)


![image201607007](https://cloud.githubusercontent.com/assets/1039772/17265071/1864f82e-55ec-11e6-9bb4-796afb198b2c.png)


![image201607006](https://cloud.githubusercontent.com/assets/1039772/17265052/e30e13ea-55eb-11e6-8f12-4bbd17d7bef6.png)

**Comment by claudiosmweb** [comment]
What version?

**Comment by samuelaguilera** [comment]
Of WC? 2.6.4, it's in the sytem report included in the issue.

**Comment by samuelaguilera** [comment]
I just created another fresh WP install in a different hosting (a well known shared hosting provider) and same result...

I can provide you a WP admin user and FTP details if you want to take a look.

**Comment by mikejolley** [comment]
@samuelaguilera On 2.6.4. Debug off. These rates:

http://glui.me/?i=kp7fwbnxjcwpwhr/2016-07-30_at_10.20.png/

Result:

http://glui.me/?i=ivcc1akhuq019wf/2016-07-30_at_10.20_(1).png/

Change method order to this, save:

http://glui.me/?i=38p2axk043p687v/2016-07-30_at_10.20_(2).png/

Back to cart page (had to change cart contents to refresh cache) and yes, the new default was not chosen. **However, looking at the code this is because I'd already selected flat rate.**

New session on new browser was free shipping. So this does work as default. Hooray.

@claudiosmweb

**Comment by samuelaguilera** [comment]
> So this does work as default.

Not here. Fresh WP installation, never selected any shipping method in front-end and the issue is present.

**Comment by mikejolley** [comment]
Go to the other browser to ensure clean session. I've just tested this.

**Comment by mikejolley** [comment]
> Not here. Fresh WP installation, never selected any shipping method in front-end and the issue is present.

If you viewed the cart page, a method was chosen (previous default).

**Comment by jeffvee** [comment]
The problem I'm having with this is when you mix in the USPS, FEDEX, and UPS extensions -- you cannot define those yet.

**Comment by mikejolley** [comment]
@jeffvee team are working on zones support for all of them.

**Comment by jeffvee** [comment]
@mikejolley Any ETA on when that will be in production?

**Comment by mikejolley** [comment]
They are in testing. I assume a few weeks but don't want to provide a hard date.

**Comment by TopOnlineMarketer** [comment]
So the short answer is drag Free Shipping to the top if you want it to default to free shipping when available now, instead of updating the functions.php file like we used to.

**Comment by ToddNewent** [comment]
@mikejolley I had this same situation and going to a new browser to ensure clean session did fix the issue for me

**Comment by gahsto** [comment]
Still not working. SMH
