### ISSUE TITLE
AJAX update_order_review in infinite LOOP

### ISSUE THREAD

**Issue by yendiLeon** [woothemes/woocommerce#11553]
## EXPLANATION OF THE ISSUE

I've tested it on Safari, Chrome, Firefox and Edge. If you go to: https://divamilano.com.mx/finalizar-comprar/ after adding any product to cart, all the DIV that's under order_review flashes constantly. It gets enabled and disabled in less than a second. Firebug displays a call to https://divamilano.com.mx/finalizar-comprar/?wc-ajax=update_order_review every 800ms approximately. 

I am really getting desperate here, because my customers can't BUY from the store. PLEASE HELP! Any idea how to fix it? It happened right after the last update.

## STEPS TO REPRODUCE THE ISSUE
No idea

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: https://divamilano.com.mx
Site URL: https://divamilano.com.mx
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.2.24 (Unix) mod_hive/5.0 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
PHP Version: 5.6.24
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicar remoto: ✔
Obtén remoto: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (61) ###

PW Advanced Woo Reporting: por Proword.net – 2.3
AffiliateWP: por AffiliateWP
LLC – 1.8.5

AffiliateWP - Affiliate Info: por Pippin Williamson and Andrew Munro – 1.0.3
AffiliateWP - Allow Own Referrals: por AffiliateWP
LLC – 1.0.2

AfterShip - WooCommerce Tracking: por AfterShip – 1.6.2
All In One SEO Pack: por Michael Torbert – 2.3.8
Asset Queue Manager: por Nate Wright – 1.0.3
Black Studio TinyMCE Widget: por Black Studio – 2.2.10
BWL Advanced FAQ Manager: por Md Mahbub Alam Khan – 1.6.3
Better WordPress Minify: por Khang Minh – 1.3.3
Contact Form 7 Honeypot: por Nocean – 1.9
Contact Form 7: por Takayuki Miyoshi – 4.4.2
Duplicate Post: por Enrico Battocchi – 2.6
Easy Social Share Buttons for WordPress: por CreoApps – 3.4
Enhanced E-commerce for Woocommerce store: por Tatvic – 1.0.18
EWWW Image Optimizer: por Shane Bishop – 2.9.3
Google XML Sitemaps: por Arne Brachhold – 4.0.8
Follow up email: por Hungnam – 3.2.0
Indeed My Team: por indeed – 1.5
Indeed My Testimonials: por indeed – 1.2.pix.2
Loco Translate: por Tim Whitlock – 1.5.6
User Profile Picture: por Ronald Huereca – 1.3.1
Openpay Cards Plugin: por Federico Balderas – 1.1.0
Openpay Stores Plugin: por Federico Balderas – 1.0
PixelYourSite PRO: por PixelYourSite – 3.2.0
PixGridder Pro: por Manuel Masia | Pixedelic.com – 3.3.3.p
PixMenu: por Manuel Masia | Pixedelic.com – 0.0.7
Product Catalog Feed Pro by PixelYourSite: por PixelYourSite – 1.9.1
Really Simple CAPTCHA: por Takayuki Miyoshi – 1.9
Really Simple SSL: por Rogier Lankhorst – 2.3.9
Remove Widget Titles: por Stephen Cronin – 1.0
PDF Wizard - Responsive FlipBook WP Extension: por MassivePixelCreation – 1.2
Responsive FlipBook WordPress Plugin: por MassivePixelCreation – 2.1.3
SEO Optimized Images: por priyanshu.mittal – 1.5
SG CachePress: por SiteGround – 2.3.8
Shortcodelic Addons: por Manuel Masia | Pixedelic.com – 0.0.9
Shortcodelic: por Manuel Masia | Pixedelic.com – 2.4.9.2
Compress JPEG & PNG images: por TinyPNG – 2.0.2
User Role Editor: por Vladimir Garagulya – 4.26.3
W3 Total Cache: por Frederick Townes – 0.9.4.1
Widget Importer & Exporter: por Steven Gliebe – 1.3.1
Woocommerce Advanced Bulk Edit: por George Iron – 3.7
WooCommerce Advanced Review Reminder: por kodemann.com – 1.8.1
WooCommerce Cart Reports: por WPBackOffice – 1.1.8 – 1.1.9 está disponible
WooCommerce Checkout Add-Ons: por WooThemes / SkyVerge – 1.6.2 – 1.8.0 está disponible
WooCommerce Cost of Goods: por WooThemes / SkyVerge – 1.9.3 – 2.2.0 está disponible
Historia del Consumidor en Woocommerce: por Brian Richards – 1.1.1
WooCommerce Email Customizer: por WooThemes – 1.1.3 – 1.1.5 está disponible
WooCommerce - Store Exporter: por Visser Labs – 1.8.6
WooCommerce Extra Product Sorting Options: por SkyVerge – 2.5.0
WooCommerce Discounts Per Payment Method: por Claudio Sanches – 2.2.1
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 1.5.36
WooCommerce Quick Export Plugin: por MB Création – 2.2
WooCommerce Role Based Methods: por WPBackOffice – 2.0.8
WooWaitlist: por WPCream.com – 3.0.10
WooCommerce: por WooThemes – 2.6.4
LiveChat: por LiveChat – 3.3.1
YITH WooCommerce Compare: por YITHEMES – 2.0.9
YITH WooCommerce Mailchimp: por Yithemes – 1.0.8
YITH WooCommerce Social Login: por Yithemes – 1.0.9
YITH WooCommerce Wishlist: por YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Base de la tienda: #44 - /tienda/
Carrito: #5 - /carro/
Finalizar compra: #6 - /finalizar-comprar/
Mi cuenta: #7 - /mi-cuenta/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Geode
Version: 1.7.4.2
Author URL: http:%20//themeforest.net/user/pixedelic
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: Tu tema tiene un archivo woocommerce.php
no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.

Overrides: geode/woocommerce/cart/cart-empty.php
geode/woocommerce/cart/mini-cart.php
geode/woocommerce/content-product.php versión2.5.0 no está actualizado. La versión del sistema es2.6.1
geode/woocommerce/content-product_cat.php versión2.5.2 no está actualizado. La versión del sistema es2.6.1
geode/woocommerce/content-widget-product.php
geode/woocommerce/global/breadcrumb.php
geode/woocommerce/loop/add-to-cart.php
geode/woocommerce/loop/loop-end.php
geode/woocommerce/loop/loop-start.php
geode/woocommerce/single-product/add-to-cart/grouped.php
geode/woocommerce/single-product/add-to-cart/variable.php
geode/woocommerce/single-product/product-image.php versión2.0.14 no está actualizado. La versión del sistema es2.6.3
geode/woocommerce/single-product/product-thumbnails.php versión2.3.0 no está actualizado. La versión del sistema es2.6.3
geode/woocommerce/single-product/rating.php
geode/woocommerce/single-product/related.php
geode/woocommerce/single-product/tabs/tabs.php
geode/woocommerce/single-product/title.php
geode/woocommerce/single-product/up-sells.php

`

**Comment by yendiLeon** [comment]
This issue is theme-related. Thanks. I'll check it out with my theme developer.

**Comment by spogulis** [comment]
I'm experiencing this issue with WC 3.9.0-rc.1 randomly in checkout page. 

This is the response:
`{"result":"success","messages":"","reload":false,"fragments":{".woocommerce-checkout-review-order-table":"<table class=\"shop_table woocommerce-checkout-review-order-table\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th class=\"product-name\">Product<\/th>\n\t\t\t<th class=\"product-total\">Subtotal<\/th>\n\t\t<\/tr>\n\t<\/thead>\n\t<tbody>\n\t\t\t\t\t\t<tr class=\"cart_item\">\n\t\t\t\t\t<td class=\"product-name\">\n\t\t\t\t\t\tSimple product&nbsp;\t\t\t\t\t\t <strong class=\"product-quantity\">&times;&nbsp;3<\/strong>\t\t\t\t\t\t\t\t\t\t\t<\/td>\n\t\t\t\t\t<td class=\"product-total\">\n\t\t\t\t\t\t<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>300.00<\/span>\t\t\t\t\t<\/td>\n\t\t\t\t<\/tr>\n\t\t\t\t\t\t\t\t<tr class=\"cart_item\">\n\t\t\t\t\t<td class=\"product-name\">\n\t\t\t\t\t\tVariable product - Red, Small&nbsp;\t\t\t\t\t\t <strong class=\"product-quantity\">&times;&nbsp;1<\/strong>\t\t\t\t\t\t\t\t\t\t\t<\/td>\n\t\t\t\t\t<td class=\"product-total\">\n\t\t\t\t\t\t<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>410.00<\/span>\t\t\t\t\t<\/td>\n\t\t\t\t<\/tr>\n\t\t\t\t\t\t\t\t<tr class=\"cart_item\">\n\t\t\t\t\t<td class=\"product-name\">\n\t\t\t\t\t\tExample Tools box - red, sm&nbsp;\t\t\t\t\t\t <strong class=\"product-quantity\">&times;&nbsp;2<\/strong>\t\t\t\t\t\t\t\t\t\t\t<\/td>\n\t\t\t\t\t<td class=\"product-total\">\n\t\t\t\t\t\t<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>700.00<\/span>\t\t\t\t\t<\/td>\n\t\t\t\t<\/tr>\n\t\t\t\t\t\t\t\t<tr class=\"cart_item\">\n\t\t\t\t\t<td class=\"product-name\">\n\t\t\t\t\t\tExample Tools box - black, sm&nbsp;\t\t\t\t\t\t <strong class=\"product-quantity\">&times;&nbsp;1<\/strong>\t\t\t\t\t\t\t\t\t\t\t<\/td>\n\t\t\t\t\t<td class=\"product-total\">\n\t\t\t\t\t\t<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>350.00<\/span>\t\t\t\t\t<\/td>\n\t\t\t\t<\/tr>\n\t\t\t\t\t<\/tbody>\n\t<tfoot>\n\n\t\t<tr class=\"cart-subtotal\">\n\t\t\t<th>Subtotal<\/th>\n\t\t\t<td><span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>1,760.00<\/span><\/td>\n\t\t<\/tr>\n\n\t\t\t\t\t<tr class=\"cart-discount coupon-percent-30\">\n\t\t\t\t<th>Coupon: percent-30<\/th>\n\t\t\t\t<td>-<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#036;<\/span>528.00<\/span> <a href=\"http:\/\/zibbywoo.local\/checkout\/?remove_coupon=percent-30\" class=\"woocommerce-remove-coupon\" data-coupon=\"percent-30\">[Remove]<\/a><\/td>\n\t\t\t<\/tr>\n\t\t\n\t\t\n\t\t\t\n\t\t\t<tr class=\"woocommerce-shipping-totals shipping\">\n\t<th>Shipping<\/th>\n\t<td data-title=\"Shipping\">\n\t\t\t\t\t<ul id=\"shipping_method\" class=\"woocommerce-shipping-methods\">\n\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t<input type=\"hidden\" name=\"shipping_method[0]\" data-index=\"0\" id=\"shipping_method_0_flat_rate1\" value=\"flat_rate:1\" class=\"shipping_method\" \/><label for=\"shipping_method_0_flat_rate1\">Flat rate: <span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>20.00<\/span><\/label>\t\t\t\t\t<\/li>\n\t\t\t\t\t\t\t<\/ul>\n\t\t\t\t\t\t\n\t\t\n\t\t\t<\/td>\n<\/tr>\n\n\t\t\t\n\t\t\n\t\t\n\t\t\n\t\t\n\t\t<tr class=\"order-total\">\n\t\t\t<th>Total<\/th>\n\t\t\t<td><strong><span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>1,252.00<\/span><\/strong> <\/td>\n\t\t<\/tr>\n\n\t\t\n\t<\/tfoot>\n<\/table>\n",".woocommerce-checkout-payment":"<div id=\"payment\" class=\"woocommerce-checkout-payment\">\n\t\t\t<ul class=\"wc_payment_methods payment_methods methods\">\n\t\t\t<li class=\"wc_payment_method payment_method_bacs\">\n\t<input id=\"payment_method_bacs\" type=\"radio\" class=\"input-radio\" name=\"payment_method\" value=\"bacs\"  data-order_button_text=\"\" \/>\n\n\t<label for=\"payment_method_bacs\">\n\t\tDirect bank transfer \t<\/label>\n\t\t\t<div class=\"payment_box payment_method_bacs\" style=\"display:none;\">\n\t\t\t<p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.<\/p>\n\t\t<\/div>\n\t<\/li>\n<li class=\"wc_payment_method payment_method_zibby\">\n\t<input id=\"payment_method_zibby\" type=\"radio\" class=\"input-radio\" name=\"payment_method\" value=\"zibby\"  checked='checked' data-order_button_text=\"\" \/>\n\n\t<label for=\"payment_method_zibby\">\n\t\tZibby <img src=\"http:\/\/zibbywoo.local\/wp-content\/plugins\/zibby\/assets\/images\/icon.png\"><a  style=\"float: right; font-size: .83em;\" onclick=\"javascript:window.open('https:\/\/s3.amazonaws.com\/about-zibby\/index.html','WIZibby','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;\" title=\"What is Zibby?\">What is Zibby?<\/a>\t<\/label>\n\t<\/li>\n\t\t<\/ul>\n\t\t<div class=\"form-row place-order\">\n\t\t<noscript>\n\t\t\tSince your browser does not support JavaScript, or it is disabled, please ensure you click the <em>Update Totals<\/em> button before placing your order. You may be charged more than the amount stated above if you fail to do so.\t\t\t<br\/><button type=\"submit\" class=\"button alt\" name=\"woocommerce_checkout_update_totals\" value=\"Update totals\">Update totals<\/button>\n\t\t<\/noscript>\n\n\t\t\t<div class=\"woocommerce-terms-and-conditions-wrapper\">\n\t\t<div class=\"woocommerce-privacy-policy-text\"><p>Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our <a href=\"http:\/\/zibbywoo.local\/?page_id=3\" class=\"woocommerce-privacy-policy-link\" target=\"_blank\">privacy policy<\/a>.<\/p>\n<\/div>\n\t\t\t<\/div>\n\t\n\t\t\n\t\t<button type=\"submit\" class=\"button alt\" name=\"woocommerce_checkout_place_order\" id=\"place_order\" value=\"Place order\" data-value=\"Place order\">Place order<\/button>\n\t\t\n\t\t<input type=\"hidden\" id=\"woocommerce-process-checkout-nonce\" name=\"woocommerce-process-checkout-nonce\" value=\"30d77a9116\" \/><input type=\"hidden\" name=\"_wp_http_referer\" value=\"\/?wc-ajax=update_order_review\" \/>\t<\/div>\n<\/div>\n"}}`

**Comment by spogulis** [comment]
This is still relevant in WC 3.9.2. Any fix?

**Comment by varunsridharan** [comment]
I am also facing the same issue but this loop happens when "update_order_review" get response as failure
