### ISSUE TITLE
SEO Tweaks for WooCommerce

### ISSUE THREAD

**Issue by opportus** [woothemes/woocommerce#11562]
There are few things that can be done for optimizing SEO on WooCommerce. I open this issue for discussing about them.

### 1.1 - Document outline
The actual document outline is wrong. From the archive/page title's tag `<h1>`, it jumps to `<h3>` for looped products and subcategories headings.
On these pages, the `<h3>` has to be replaced by `<h2>` which will:

1. Valid the document outline
2. Give more weight to subcategories and product titles, which are **keywords**.

### 1.2 - Structure
Maybe we could **optionally** wrap looped products inside `<article>` structural elements if we refer to its description from [W3C](https://www.w3.org/TR/html5/sections.html#the-article-element):
> The article element represents a complete, or self-contained, composition in a document, page, application, or site and that is, in principle, independently distributable or reusable, e.g. in syndication. This could be a forum post, a magazine or newspaper article, a blog entry, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

But it remains ambiguous enough. Can we consider a looped product a self-contained item ? Though on that one would be welcome...

### 1.3 - More content
We should add a little more content to the categories by adding the short description (or a part of it) and/or attributes of each product, that will be displayed nicely when we hover them. That also improve user experience. I'm sure @jameskoster could give us a neat solution here.

### 2.1 - Tabs sections
If possible we'd need **dynamic** headings that won't repeat all over the site again and again. The obvious solution here would be... "Description for {Product Name}", but if we apply the same to other tab section headings, I'm afraid Google consider it as keyword stuffing... Does somebody have an idea ?

**Comment by jameskoster** [comment]
This mostly sounds good to me. Couple of points;

> We should add a little more content to the categories by adding the short description (or a part of it) and/or attributes of each product, that will be displayed nicely when we hover them. That also improve user experience.

This requires some discussion I think. While there are no doubt some SEO benefits to doing this it does move significantly away from traditional shop design (referring to displaying the description). Wouldn't a good _category_ description be enough for SEO purposes on these pages? Personally I'm not so hot on this particular idea and there are a few plugins that add this functionality in existence anyway. But like I said, it needs discussion :)

> If possible we'd need dynamic headings that won't repeat all over the site again and again. The obvious solution here would be... "Description for {Product Name}", but if we apply the same to other tab section headings, I'm afraid Google consider it as keyword stuffing... Does somebody have an idea ?

We already do this on the reviews tab. For the description tab perhaps we could replace the generic and bland 'Product Description' with the actual product name? That along with the reviews tab would be an improvement I think and hopefully wouldn't be deemed inappropriate.

**Comment by opportus** [comment]
> We already do this on the reviews tab. For the description tab perhaps we could replace the generic and bland 'Product Description' with the actual product name? That along with the reviews tab would be an improvement I think and hopefully wouldn't be deemed inappropriate.

For sure, but we need to be prudent here, again, I don't want this to be considered as keyword stuffing by Google... Actually trying to get more info about that on specialized forums.

**Comment by mikejolley** [comment]
@jameskoster since this will be yours, if you don't think it should be 2.7 please move :)

**Comment by jameskoster** [comment]
Depends on 2.7 deadline, we might have to bump

**Comment by mikejolley** [comment]
@jameskoster optimistic but would be nice to get to a beta stage by end of month.

**Comment by jameskoster** [comment]
@opportus I'd say create a PR for this (if you have time) and we'll work through it the same way we did for Storefront. If it's done in time it can go in 2.7.

Otherwise I'll try and get it in 2.7 myself but wouldn't like to commit to that milestone at this stage.

**Comment by opportus** [comment]
@jameskoster and everybody...

> If it's done in time it can go in 2.7.

If we can decide about all questions that have been enlighted, we should be done before end of the month without problem, the most difficult here will be to take the decisions, the implementation is absolutly nothing.

So first let's decide about **related** and **upsell** products sections **headings**...

On the PR #11583, we actually have this:

"**Other {product categories}**" - If you think it might sound right in every situations, we can leave it like this, otherwise we can also remove the "Other", or find another word...
"**You might also like...**" - About that one I guess there is nothing to do to make it dynamic ? 💭 💭 💭

**Comment by opportus** [comment]
About tabs section headings, we finally better give up the idea to include product name in them.
The idea would be good only if we could guarantee a given keyword/content ratio... which is not possible.

**Comment by opportus** [comment]
Now we should decide about description/attributes snippets displaying on loop products when we hover them.

**Comment by lawkwok** [comment]
I think we should prioritize user experience above all else. Shouldn't search engines be smart enough to figure out what the page is about by analyzing header product descriptions, linking, etc?

To build onto @opportus, imagine seeing all this on a product page within clicks of each other:

> "Product Description for 4L Food Mixer with 10-piece blade set"
> "Review the for 4L Food Mixer with 10-piece blade set"
> "Additional information for 4L Food Mixer with 10-piece blade set"

Repeating the product name may give the user trigger semantic satiation and make sites appear templated/overeager to optimize for search engines.

**Comment by opportus** [comment]
@lawkwok 

> I think we should prioritize user experience above all else.

About user experience, we could argue that would be a bad solution in every cases. Like when the size of the content between the headings is important enough, especially on mobiles phones, in such obvious cases, it could be worth reminding the main item. That coincide to the fact for which we gave up this idea... because we can't guarantee the size of the content will be important enough.

> Shouldn't search engines be smart enough to figure out what the page is about by analyzing header product descriptions, linking, etc?

Since the time some people want to convince us of that... It's not that simple. If that would be completly true, SEO would be dead **already**.
There is optimizing a site the good way, just what we need by putting accent on what  is **important to the customer** and **make sure Google interpret it the way we want**. That's totally legitime and natural... And Google **needs** it.
It doesn't mean that we should do put 20 unoptimized headings all over the pages with no direct relation with their main contents and other such SEO technical errors,  naively thinking Google will understand all by itself, because it won't.
