### ISSUE TITLE
Add an index to comment_type field

### ISSUE THREAD

**Issue by rodrigoprimo** [woothemes/woocommerce#11560]
As discussed in PR #11449, the query used by WC_Comments::wp_count_comments() can be slow when a site has a big number of comments. In the referred PR, a transient was added with the comments count per type significantly reducing the number of times this query is called but it is still called whenever there is a new comment or a comment status changes.

There is a open WordPress core ticket (https://core.trac.wordpress.org/ticket/31072) proposing the addition of an index to the field `comment_type` of the table `wp_comments`. In this ticket Gary Pendergast suggested that plugins can add this index themselves while this is not added in WordPress core (which can take a while):

https://core.trac.wordpress.org/ticket/31072#comment:4

What are you thoughts on this? I can open a PR if you guys think other WC users will benefit from this change.

I have manually added this index to WooCommerce.com and the query execution time dropped from 5 seconds to 0.3 seconds.

**Comment by mikejolley** [comment]
@rodrigoprimo sounds good. Can go in our install routine.
