### ISSUE TITLE
Wrong Address Format in Admin Order View

### ISSUE THREAD

**Issue by dwdonline** [woothemes/woocommerce#11573]
## EXPLANATION OF THE ISSUE
Version 2.6.4
The store I'm working on is based in Australia. Apparently, newer versions of WooCommerce have a feature (which is more like a bug in my mind) that changes the order of the address in the admin based on the customer's country. Now, this is insane. Why? Well, if you are based in a western country, and you are trying to enter this information into ANY shipping software, it wants it in that order. To force a store owner in the West to try to decipher an address in the East, or to force a store owner in the East to try to decipher an address in the West serves no practical purpose that I can think of.

## STEPS TO REPRODUCE THE ISSUE

Place a customer order from another country, and then view in the admin. You will see the address listed differently.

To me, the solution would be allowing the store owner to turn this off or on. For stores in the US, AU, and UK I know for sure that this causes confusion when trying to ship internationally. 

Apparently, even adding reformatting overrides to the functions.php will not work.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
It's presented how it would be written on a package manually. e.g. from https://en.wikipedia.org/wiki/Address_(geography)#Address_format I don't think it's fair to assume all store owners in the world use the same software as you, or that all users have to do this manually. This is also the first time this has been brought up so I don't think its a common issue.

Change/remove/customise using the filter here https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-countries.php#L410 You have full control over those handled.

Additionally if you edit the address on the view order screen, you can see each piece of data before formatting.

**Comment by dwdonline** [comment]
I think you miss my point. I'm not assuming that people use the same software. However, I do have an extensive background in shipping, and understand the reasoning behind the formatting.

However, anyone – regardless of their country, when using shipping software are presented a screen that puts it in their format. If I'm in Canada, US, UK, AU, etc. I am presented a screen (with all software) that has me enter the address as western style. If I'm in China, it presents it the opposite way. 

My point is, that WooCommerce presents the address to the store owner as it would be for the client (rather than the owner). Anyone using any shipping software, is going to have the address fields presented in local format. Therefore, they have to decipher the address.

If this is going to be a "feature" it should be able to be turned off, so those using shipping software (whether manual or cut-and-paste entry) can use it. 

Check out a few shipping softwares - local to China versus local to the US, Canada, or AU.
