### ISSUE TITLE
Refunds and the API

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#11578]
When processing a refund, it looks like we add a new database entry to the posts table, to record the refunded order. We also add a note to the order, referencing the refund ID.

How would we recommend that refunds be tracked and processed through the API by, for example, a hosted accounting system?

@mikejolley

**Comment by mikejolley** [comment]
Looks like it's missing from the docs, but in addition to the refunds endpoint, orders endpoint returns all order refunds in an array https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L163

@claudiosmweb [Can you add updating the docs to your todo list?](https://github.com/woothemes/woocommerce-rest-api-docs/issues/50)

**Comment by claudiosmweb** [comment]
we already have docs for it: http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-refund
