### ISSUE TITLE
Unable to fetch Meta data in View Order and Email Template

### ISSUE THREAD

**Issue by mayank-bothra** [woothemes/woocommerce#11575]
Hi 

I am using Woocommerce Product Add Ons plugin.
I am unable to Unable to fetch Meta data in View Order and Email Template. 
Kindly review the image for more understanding.

Red Circle data is missing in the email template and in the view order.

![2](https://cloud.githubusercontent.com/assets/6221520/17291162/d9cbff52-57ff-11e6-91f2-a56773efd042.PNG)

![1](https://cloud.githubusercontent.com/assets/6221520/17291161/d9c4593c-57ff-11e6-8f86-5f44d9fed9bb.PNG)

![3](https://cloud.githubusercontent.com/assets/6221520/17291234/603092ce-5800-11e6-9162-6db0d5c330c3.PNG)

**Comment by mikejolley** [comment]
support.woothemes.com

**Comment by mayank-bothra** [comment]
Its not a plugin issue !

**Comment by mikejolley** [comment]
Product Add-ons is a plugin, so yes it is. Seeing as this works on other user's installs, it's likely something specific to yours. 

Not to mention you ignored this on the submission form:

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
> - https://wordpress.org/support/plugin/woocommerce for general support
> - https://support.woothemes.com for premium plugin support

Use the correct channel.
