### ISSUE TITLE
Some KEY definitions in database schema are not compatible with dbDelta requirements.

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#11572]
## EXPLANATION OF THE ISSUE

When I upgraded WC to version 2.6.3 I got following warning in error log 

> WordPress database error Duplicate key name 'attribute_name' for query ALTER TABLE mood_woocommerce_attribute_taxonomies ADD KEY attribute_name (attribute_name(191)) 
WordPress database error Duplicate key name 'download_order_key_product' for query ALTER TABLE mood_woocommerce_downloadable_product_permissions ADD KEY download_order_key_product (product_id,order_id,order_key(191),download_id)
...

I checked the code and found that some KEY definitions (for example, `KEY attribute_name (attribute_name($max_index_length))`) doesn't match following dbDelta requirement:
> KEY must be followed by a SINGLE SPACE then the key name then a space then open parenthesis with the field name then a closed parenthesis.

This makes dbDelta to generate ALTER TABLE .. ADD KEY statements for keys that already exist in DB causing warnings above.

## STEPS TO REPRODUCE THE ISSUE

Upgrade WC from 2.6.2 to 2.6.3

**Comment by mikejolley** [comment]
See https://github.com/woothemes/woocommerce/search?q=alter+table+trac&type=Issues&utf8=%E2%9C%93 It's a WP core issue. Nothing to do with the spaces (which do follow what you just pasted anyway).

**Comment by gedex** [comment]
@smazur I've workaround for this until WP test framework fixes it. Basically you can register a cleanup handler during shutdown in your bootstrap file. For example, I use this to delete all WP and WC tables:

~~~php
tests_add_filter( 'shutdown', function() {
	global $wpdb;

	$tables = array_merge(
		array_values( $wpdb->tables() ),
		array(
			$wpdb->prefix . 'woocommerce_api_keys',
			$wpdb->prefix . 'woocommerce_attribute_taxonomies',
			$wpdb->prefix . 'woocommerce_downloadable_product_permissions',
			$wpdb->prefix . 'woocommerce_order_items',
			$wpdb->prefix . 'woocommerce_payment_tokens',
			$wpdb->prefix . 'woocommerce_payment_tokens',
			$wpdb->prefix . 'woocommerce_shipping_zone_locations',
			$wpdb->prefix . 'woocommerce_sessions',
			$wpdb->prefix . 'woocommerce_shipping_zones',
			$wpdb->prefix . 'woocommerce_shipping_zone_methods',
			$wpdb->prefix . 'woocommerce_tax_rates',
			$wpdb->prefix . 'woocommerce_tax_rate_locations',
		)
	);

	foreach ( $tables as $table ) {
		$wpdb->query( "DROP TABLE IF EXISTS $table;" );
	}
}, 9999 );
~~~
