### ISSUE TITLE
Improving the refund journey for merchants

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#11577]
I have some customer feedback regarding how we handle refunds on the merchant-facing side of WooCommerce.

> Basic journey is…
> + customer contacts us (before or after shipping) and wants some form of a refund.
> + have to open the order and refund items and/or money back. if items then $ and tax should be auto calculated.
> + If $ back and not product, we have to calculate by hand the product $ and tax $ to give them back. Usually you want to give back the same ratio for product $ versus tax $. The taxes you really owe are a % against revenue. 
> + sometimes you want to apply a coupon code after the fact. that should be simple to enter and let the system do the math. right now you have to change every product by hand to apply a coupon code if the user forgot.
> + confusing being able to change product details and total order amounts. we definitely got into trouble editing total order value and not doing it on a per item level.

Something we can work into 2.7 or 2.8, @mikejolley ?

**Comment by mikejolley** [comment]
@mattyza Would be good to ping in slack first with similar requests so we don't have issues within issues etc. Feedback is all well and good, but issues should either list the problem, or actions required to solve the problem. Once confirmed they are actually issues of course.

> have to open the order and refund items and/or money back. if items then $ and tax should be auto calculated.

We do the auto calc if you increase the qty to refund per line item.

> If $ back and not product, we have to calculate by hand the product $ and tax $ to give them back. Usually you want to give back the same ratio for product $ versus tax $. The taxes you really owe are a % against revenue.

Same as above. Screen demo:

![example](https://cloud.githubusercontent.com/assets/90977/17298424/ef310fca-5801-11e6-851c-aadd6c763fc8.gif)

> sometimes you want to apply a coupon code after the fact. that should be simple to enter and let the system do the math. right now you have to change every product by hand to apply a coupon code if the user forgot.

**Unrelated to refunds** completely [and logged elsewhere](https://github.com/woothemes/woocommerce/issues/4404) 

> confusing being able to change product details and total order amounts. we definitely got into trouble editing total order value and not doing it on a per item level.

Understood and something s9n team are looking at. We could for example prevent the custom refund amount and make it item based. Needs some user feedback before rollout with s9n.
