### ISSUE TITLE
Error: Missing parameter app_name

### ISSUE THREAD

**Issue by dheerajsingla** [woothemes/woocommerce#11571]
EXPLANATION OF THE ISSUE

On of our customer is facing the issue "Error: Missing parameter app_name" on the link. (wordpress 4.5.3, woocommerce 2.6.4)

STEPS TO REPRODUCE THE ISSUE

Click this: 
https://golosiy.com/wc-auth/v1/authorize?app_name=orangetwig&scope=read_write&user_id=AAAiOAv&return_url=https://orangetwig.com/platforms/woocommerce/returnurl?domain=https://golosiy.com&callback_url=https://orangetwig.com/platforms/woocommerce/accessCallback?data={"email":"test@test.com","domain":"https://golosiy.com","referCode":"orangetwig"}

SYSTEM STATUS REPORT

Error: Missing parameter app_name

**Comment by mikejolley** [comment]
Means their server (probably NGINX config) is ignoring query string vars.

**Comment by penmetsa55** [comment]
I also got this Missing parameter app_name error. Issue is NGINX server configuration was not proper. NGINX server ignoring the parameters.

After added the $args to index.php solved the issue like below.

location / {
try_files $uri /index.php$args;
}
