### ISSUE TITLE
Attribute value issue with sanitize_title

### ISSUE THREAD

**Issue by swarnat** [woothemes/woocommerce#11574]
## EXPLANATION OF THE ISSUE
Hy,

We use latest Wordpress and WooCommerce Version. 
I already search within Issues, because I cannot imagine nobody else recognize this effect, but  do not found any entry.

(All values in following report are configured in woocommerce without quotes. For easier reading I add quotes.)

We have a variable product with one attribute "length". There are defined size values "10", "5.0", "1.5", "1,0". 
I know the wrong order and correct first value would be "10,0", but not every employee think in an ordered and correct way.

Now if you create a variation for value "10" and save the product, the chosen attribute of the variation select and show "1,0". The source code shows both options "10" and "1,0" have the selected attributes.
In Frontend the correct option is available, but in backend maybe the wrong price is set, because the attribute show wrong value to shop manager.

The problem will get bigger, if the product will be saved a second time. Then wrong attribute is saved and also shown in frontend.

I debug it a little bit and saw the chosen attribute is send through the function sanitize_title, which simple remove the comma. Then "1,0" = "10".

I could not imagine a solution for this, because the sanitize_title function should remove unsafe chars. 
The problem is solved and works in both directions, if the numbers are setup in sorted order, but I cannot say why.
Maybe an info somewhere, numbers must entered in ordered sequence, will be helpful.

Thanks!
Regards,

Stefan

**Comment by mikejolley** [comment]
Input https://dl.dropboxusercontent.com/s/liovjvua8jv6oq7/2016-08-01%20at%2012.24.png?dl=0

Selected attributes https://dl.dropboxusercontent.com/s/f7kkg0p5p6147vp/2016-08-01%20at%2012.25.png?dl=0

Options https://dl.dropboxusercontent.com/s/ljmklltge4geh24/2016-08-01%20at%2012.25%20%281%29.png?dl=0

Seems to save fine and work on frontend without issue. Not sure what you are trying to describe here.
