### ISSUE TITLE
Sub category permalinks

### ISSUE THREAD

**Issue by lgfstudio** [woothemes/woocommerce#11582]
Hi, 

I have problems with sub-category permalinks.  The category permalinks are fine, but I can not get the subpage for a sub-category, I get "Page not found" / 404.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://carolweddings.com
Site URL: http://carolweddings.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.31 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (29) ###

Social Login WordPress Plugin - AccessPress Social Login Lite: by AccessPress Themes – 3.1.3
Admin Language Per User: by unclego – 1.0.4
Akismet: by Automattic – 3.1.11
iThemes Security: by iThemes – 5.6.0
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.2

Wpdevart Facebook comments: by wpdevart – 1.3.6
Contact Form 7: by Takayuki Miyoshi – 4.4.2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Imagify: by WP Media – 1.5.6
Insert Headers and Footers: by WPBeginner – 1.3.3
Loco Translate: by Tim Whitlock – 1.5.6
Max Mega Menu: by Tom Hemsley – 2.2.2
Social Login: by Claude Schlesser – 5.0
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 2.5
Photo Gallery: by WebDorado – 1.3.4
Responsive Lightbox: by dFactory – 1.6.8
Same Category Posts: by DFlöter – 1.0.8
Social Buttons Pack by BestWebSoft: by BestWebSoft – 1.0.8
Ultimate Facebook Page Plugin Widget: by VisualScope – 1.0
Virtue / Pinnacle ToolKit: by Kadence Themes – 3.5
W3 Total Cache: by Frederick Townes – 0.9.4.1
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.4
WP SMTP: by BoLiQuan – 1.1.9
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.3.2
YITH WooCommerce Badge Management: by YITHEMES – 1.2.9
Zopim Widget: by Zopim – 1.4.3

### Settings ###

Force SSL: –
Currency: VND (₫)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #216 - /shop-hoa
Cart: #8 - /gio-hang
Checkout: #9 - /thanh-toan
My Account: #10 - /tai-khoan

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Virtue
Version: 2.7.6
Author URL: https://kadencethemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: virtue/woocommerce/archive-product.php
virtue/woocommerce/content-product.php
virtue/woocommerce/content-product_cat.php
virtue/woocommerce/content-single-product.php
virtue/woocommerce/loop/loop-end.php
virtue/woocommerce/loop/loop-start.php
virtue/woocommerce/loop/price.php
virtue/woocommerce/loop/rating.php
virtue/woocommerce/loop/sale-flash.php
virtue/woocommerce/single-product/add-to-cart/external.php
virtue/woocommerce/single-product/add-to-cart/grouped.php
virtue/woocommerce/single-product/add-to-cart/simple.php
virtue/woocommerce/single-product/add-to-cart/variable.php
virtue/woocommerce/single-product/price.php
virtue/woocommerce/single-product/product-image.php
virtue/woocommerce/single-product/product-thumbnails.php
virtue/woocommerce/single-product/sale-flash.php
virtue/woocommerce/single-product.php
virtue/woocommerce/taxonomy-product_cat.php
virtue/woocommerce/taxonomy-product_tag.php

`

**Comment by opportus** [comment]
Can you go in WP settings -> Permalinks... Try again to open a subcategory... Does it "fix" it ?

**Comment by lgfstudio** [comment]
I tried changing the link structure and re-generating them, editing the sub category, but nothing...

**Comment by mikejolley** [comment]
Use the support forum please https://wordpress.org/plugins/woocommerce/ and include details on current permalink structures.

Also, before posting, disable all other plugins, change themes, then resave permalinks and retest to rule out conflicts.
