### ISSUE TITLE
Small CSS fix for Tabs

### ISSUE THREAD

**Issue by SukcesStrony** [woothemes/woocommerce#11585]
The bottom corners of the product tabs (Description, Reviews etc.) are set to white, which is a small problem which comes up if the background of the site changes.

## How to test it ##
Use the following CSS and navigate to a product page.
`body{
    background-color: #f2e7ff;
}
.woocommerce div.product .woocommerce-tabs ul.tabs li.active {
    background-color: #f2e7ff;
    border-bottom: 1px solid #f2e7ff;
}`

## How to fix it ##

File: woocommerce.css (2.6.4):

Currently is:
`.woocommerce div.product .woocommerce-tabs ul.tabs li.active:before {
    box-shadow: 2px 2px 0 #fff;
}`

Should be:
`.woocommerce div.product .woocommerce-tabs ul.tabs li.active:before {
    box-shadow: 2px 2px 0 transparent;
}`

**Comment by mikejolley** [comment]
This breaks on white after your change. It's not a bug, the same tab bg color is used. 

https://dl.dropboxusercontent.com/s/adbxrl8jwlqsjjv/2016-08-02%20at%2014.04.png?dl=0

So account for this in your CSS.
