### ISSUE TITLE
Can `wc_check_if_attribute_name_is_reserved` be removed?

### ISSUE THREAD

**Issue by neonics** [woothemes/woocommerce#11581]
Hi there,

I have a question about `function validate_attribute_slug`, particularly [this line and the next](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-product-attributes-controller.php#L636):

```
    } elseif ( wc_check_if_attribute_name_is_reserved( $slug ) ) {
        return new WP_Error( 'woocommerce_rest_invalid_product_attribute_slug_reserved_name', ....
```

Is this check still necessary? 

[The documentation for `wc_check_if_attribute_name_is_reserved`](https://github.com/woothemes/woocommerce/blob/master/includes/wc-attribute-functions.php#L179) references [the codex on register_taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy#Reserved_Terms) , but the Description on the top of that page states that this applies to *taxonomy names*, not product attributes. A product attribute in the `woocommerce_attribute_taxonomies` has a `pa_` prefix in the `term_taxonomy` table, which does not conflict with any reserved terms. It doesn't seem logical to first strip `pa_` from the slug and compare that to the reserved words, since the slug does contain the `pa_` prefix.

As far as I can tell, there is no need to mark any product attribute name as reserved, since the whole point of using a `pa_` prefix is to scope these product attribute taxonomies to a 'private' namespace so that users can define their own extra attributes.

I ask, because our products have an attribute named 'type' (taxonomy `pa_type`), and these 2 lines of code prevent creating that attribute. We've been running a couple of shops for 3 years with this attribute on all products without problems (we use a custom importer bypassing this restriction).

Perhaps I'm overlooking something?

Thanks!
-- Kenney

**Comment by mikejolley** [comment]
It's needed. The 'slug' doesn't need a prefix and is used for rewrites (if public). This is used in things like query strings. It can conflict with WP core.

**Comment by neonics** [comment]
Thanks for the response. Can you give an example of such a rewrite and/or a query string where a product attribute is used without the prefix?

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-post-types.php#L210
