### ISSUE TITLE
Categories not returning as list of objects

### ISSUE THREAD

**Issue by deusprogrammer** [woothemes/woocommerce#11599]
## EXPLANATION OF THE ISSUE

When retrieving products from V1 using the API, the categories are returned as names only and not objects (containing their id, name, and slug).

## STEPS TO REPRODUCE THE ISSUE

Assuming you have some products with categories assigned to them, just call GET and you will see that your JSON payload for the categories of each product looks nothing like your example.

**Comment by mikejolley** [comment]
This API is not latest: https://woothemes.github.io/woocommerce-rest-api-docs/v1.html#products That only returns names.

You need to use the WP Rest API. https://woothemes.github.io/woocommerce-rest-api-docs/#product-properties
