### ISSUE TITLE
Variation shows wrong photo only when size small is selected

### ISSUE THREAD

**Issue by bendabam** [woothemes/woocommerce#11597]
I published my first product, and the product color variation will update appropriately for each color I select - until I select size Small. Then the photography switches back to the original first product color. I'm not sure how to fix this. I checked that the attribute and variation had the correct color image attached to it. The other areas of these variations are the same as the other sizes, so I'm not sure what else to try. Please help!

To replicate: Go to `gurlzbrand.com - go to Shop - select any color and size medium. Then select size small - and you will see the color flips to the incorrect color.`

Any help would be very welcome!

`
### WordPress Environment ###

Home URL: http://www.gurlzbrand.com
Site URL: http://www.gurlzbrand.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.17
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (18) ###

Contact Form 7: by Takayuki Miyoshi – 4.4.2
Cornerstone: by Themeco – 1.3.0
Duplicate Post: by Enrico Battocchi – 2.6
Slider Revolution: by ThemePunch – 5.2.6
Rich Reviews: by Nuanced Media – 1.7.3
SKU Error Fixer for WooCommerce: by Alio Master – 1.0
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.4.1
WP Store Locator: by Tijmen Smit – 2.2.3
X – Content Dock: by Themeco – 1.0.0
X – Custom 404: by Themeco – 1.1.1
X – Disqus Comments: by Themeco – 1.0.0
X – Email Forms (MailChimp): by Themeco – 1.1.2
X – Facebook Comments: by Themeco – 1.0.1
X – Google Analytics: by Themeco – 1.0.0
X – Smooth Scroll: by Themeco – 1.0.2
X – Terms of Use: by Themeco – 1.0.0

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1081 - /shop/
Cart: #1083 - /cart/
Checkout: #1085 - /checkout/
My Account: #1087 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: X
Version: 4.6.1
Author URL: http://theme.co/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: x/woocommerce/cart/cart-empty.php
x/woocommerce/cart/cross-sells.php
x/woocommerce/emails/admin-new-order.php
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/product-image.php
x/woocommerce/single-product/product-thumbnails.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php

**Comment by mikejolley** [comment]
We don't deal with support questions here. Use the forum https://wordpress.org/plugins/woocommerce/

No doubt you have a variation with the same attributes selected which is taking priority.
