### ISSUE TITLE
How to add a specific attribute to all the product in woocommerce

### ISSUE THREAD

**Issue by raunak-cispl** [woothemes/woocommerce#11590]
## EXPLANATION OF THE ISSUE
Hi,
I have a Woocommerce shop, running on WordPress 4.5.3. I want to add a specific attribute to all the 5000 products. 
For example, I want to add a color attribute 'Black', ONLY to those product which does not have a color attribute. If Product A has blue color then black will not be added and if Product B did not have color attribute then it will add Black color. 
Manually I can check and add the product attribute but it a time consuming so i was thinking of doing it programmatically as there are more then 5k product. Thanks.

I also asked this in stackoverflow, wordpress forum but no one answered till now
http://stackoverflow.com/questions/37541913/how-to-add-a-specific-attribute-to-all-the-product-in-woocommerce

## SYSTEM STATUS REPORT
WordPress (Version 4.5.3)
WooCommerce (Version 2.6.4)

Thanks.

**Comment by mikejolley** [comment]
This is not a support forum.

Use https://wordpress.org/support/plugin/woocommerce

**Comment by raunak-cispl** [comment]
Hi, 
Sorry for this,
I had posted this question over there also, but did't get any help.
can you please help me over there.
https://wordpress.org/support/topic/how-to-add-a-specific-attribute-to-all-the-product-in-woocommerce
