### ISSUE TITLE
Update Cart Button does not work when changing quantities during checkout

### ISSUE THREAD

**Issue by Hawthornek** [woothemes/woocommerce#11596]
## EXPLANATION OF THE ISSUE

What DOESN'T Happen: when you add an item to the cart and want to change the quantity, click Update Cart, it does not update or do anything.  I'd expect if I tell it I want 2 items it would change to 2 items and update the price.

WC Version 2.6.4

## STEPS TO REPRODUCE THE ISSUE

GoTo: www.gridironproductions.com / Click on "Order Here" / Add a HighLight DVD to the Cart / Click View Cart / Attempt to Change Quantity.

## SYSTEM STATUS REPORT

WordPress Environment 

Home URL:  http://gridironproductions.com 
Site URL:  http://gridironproductions.com 
WC Version:  2.6.4 
Log Directory Writable:   /home/gridipllc/public_html/wp-content/uploads/wc-logs/  
WP Version:  4.5.3 
WP Multisite:  – 
WP Memory Limit:  256 MB 
WP Debug Mode:  –  
WP Cron:    
Language:  en_US 

Server Environment 

Server Info:  Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4 mod_fcgid/2.3.9 
PHP Version:   5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version 
PHP Post Max Size:  32 MB 
PHP Time Limit:  30 
PHP Max Input Vars:  1000 
cURL Version:  7.36.0, OpenSSL/1.0.1e 
SUHOSIN Installed:  – 
MySQL Version:  5.6.21	 
Max Upload Size:  32 MB 
Default Timezone is UTC:  	 
fsockopen/cURL:     
SoapClient:     
DOMDocument:     
GZip:     
Multibyte String:     
Remote Post:     
Remote Get:     

Database 

WC Database Version:  2.6.4 

woocommerce_sessions    
woocommerce_api_keys    
woocommerce_attribute_taxonomies    
woocommerce_downloadable_product_permissions    
woocommerce_order_items    
woocommerce_order_itemmeta    
woocommerce_tax_rates    
woocommerce_tax_rate_locations    
woocommerce_shipping_zones    
woocommerce_shipping_zone_locations    
woocommerce_shipping_zone_methods    
woocommerce_payment_tokens    
woocommerce_payment_tokenmeta    
MaxMind GeoIP Database:   /home/gridipllc/public_html/wp-content/uploads/GeoIP.dat  

Active Plugins (8) 

All-in-One Event Calendar Extended Views by Time.ly   by Time.ly Network Inc. – 1.2.9 
All-in-One Event Calendar by Time.ly   by Time.ly Network Inc. – 2.5.8 
Comet Cache   by WebSharks, Inc. – 160706 
SumoMe   by SumoMe – 1.18 
WooCommerce   by WooThemes – 2.6.4 
Yoast SEO   by Team Yoast – 3.4 
WP Robots Txt   by Christopher Davis – 1.1 
WP Smush   by WPMU DEV – 2.4.3 

Settings 

Force SSL:  – 
Currency  USD ($) 
Currency Position  left 
Thousand Separator  , 
Decimal Separator  . 
Number of Decimals  2 

API 

API Enabled:   

WC Pages 

Shop Base:  #855 - /order-here/ 
Cart:  #856 - /cart/ 
Checkout:  #857 - /checkout/ 
My Account:  #858 - /my-account/ 

Taxonomies 

Product Types:   downloadable (downloadable), external (external), grouped (grouped), simple (simple), variable (variable), virtual (virtual) 

Theme 

Name:  Enfold Child 
Version:  1.0 
Author URL:  http://www.kriesi.at 
Child Theme:   
Parent Theme Name:  Enfold 
Parent Theme Version:  3.5.2 
Parent Theme Author URL:  http://www.kriesi.at 
WooCommerce Support:   

Templates 

Overrides:   – 

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Theme issue. Contact author/update https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990 You are not on latest.
