### ISSUE TITLE
[API] Filter products by tags

### ISSUE THREAD

**Issue by EmmanuelFdzGtz** [woothemes/woocommerce#11598]
I'm using WooCommerce api V3 and want to get products based on a tag , and return error.

url:
wc-api/v3/products?oauth_consumer_key=ck_523c84af07b5b594d457ccd11214b228cf885bc4&oauth_nonce=6ee6c1e2a87644b59f8a18d99446bcc43d0dd48c01eeba58b6b18a5171afb42f&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1470181738&**filter[tag]=artesanal**&filter[limit]=6&oauth_signature=TqqBNYeb%2B9EKct5kT46OOldHpzMWO7Aotklv6s7stPM%3D

return:
Object {data: Object, status: 401, config: Object, statusText: "Unauthorized"}

when i filter by category (filter[category]=some_category) work well.

**Comment by mikejolley** [comment]
This will be the function you're using for signature generation, not the filter itself. Not a bug in my testing. @claudiosmweb You could use the new API also - that has other methods of auth if easier.

**Comment by claudiosmweb** [comment]
When using filters, you need sort in alphabetical order.

Need to fix it:
`filter[tag]=artesanal&filter[limit]=6`

**Comment by aadilali** [comment]
> I'm using WooCommerce api V3 and want to get products based on a tag , and return error.

url:
wc-api/v3/products?oauth_consumer_key=ck_523c84af07b5b594d457ccd11214b228cf885bc4&oauth_nonce=6ee6c1e2a87644b59f8a18d99446bcc43d0dd48c01eeba58b6b18a5171afb42f&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1470181738&filter[tag]=artesanal&filter[limit]=6&oauth_signature=TqqBNYeb%2B9EKct5kT46OOldHpzMWO7Aotklv6s7stPM%3D

return:
Object {data: Object, status: 401, config: Object, statusText: "Unauthorized"}

when i filter by category (filter[category]=some_category) work well.
Hi @EmmanuelFdzGtz 

I am facing same issue using API version 3. Did you find any solution??
