### ISSUE TITLE
No Puerto Rico?

### ISSUE THREAD

**Issue by saulfautley** [woothemes/woocommerce#11617]
A client of mine just brought to my attention that Puerto Rico, which is apparently a U.S. State, is not showing up in the State selection at Checkout (probably on other pages as well). I checked and he is right, there is no Puerto Rico option anywhere under State or Country.

Is Puerto Rico not considered part of the world by WooCommerce for any particular reason, or is there something more sinister going on?

**Comment by mikejolley** [comment]
He blind https://github.com/woothemes/woocommerce/blob/master/i18n/countries.php#L195
