### ISSUE TITLE
Rounding issues with 50% coupons

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#11626]
## EXPLANATION OF THE ISSUE

On Woocommerce 2.6.4 we are seeing a rounding issue when a customer applies a 50% coupon on his order. You can see it in the checkout/cart but also in the backend.

If the grand total is 33,09€ and he applies the 50% coupon he should get a discount-value of 16,54 € and a total of 16,55 € which still has to be paid.

## STEPS TO REPRODUCE THE ISSUE

0. Set tax rate to 19% and currency € (standard settings for Germany)
1. Create a 50% coupon
2. Add products to your cart with the following prices:
5,17€ + 3,32€ + 1,25€ + 3,50€ + 5,01€ + 3,34€ + 5,99€ + 5,51€
2. Go to checkout or cart and apply a 50% coupon
3. You can see that the coupons is calculated correctly (16,54€) but the order total gets 16,57€ unless it should be 16,55€ to be correct.
4. Also if you do a checkout the sum will remain wrong and is saved to the database.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://kindermode.clean
Site URL: http://kindermode.clean
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.42
MySQL Version: ❌ 5.5.42
Default Timezone is UTC: ❌ Standard-Zeitzone ist Europe/Berlin – es sollte UTC sein
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() schlug fehl. Fehler: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (38) ###

WooCommerce Domination: von Claudio Sanches – 1.1.4
WooCommerce Quantity Increment: von Automattic WooThemes – 1.1.0
WooCommerce Social Login: von WooThemes / SkyVerge – 1.8.0
WooCommerce WishLists: von Lucas Stark – 1.11.1
WooCommerce: von WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Divi
```

**Comment by mikejolley** [comment]
Prices including tax affected.

Caused by https://github.com/woothemes/woocommerce/commit/e00c3450c5d7edd172216a741587236d77e1e596

Related 
https://github.com/woothemes/woocommerce/issues/10963
https://github.com/woothemes/woocommerce/issues/10573

**Comment by krautnerds** [comment]
Is there anything I can do to support you fixing this issue?

I thought about implementing a unit test for the example case I wrote in my issue?

**Comment by mikejolley** [comment]
Already writing it.

**Comment by mikejolley** [comment]
Move discussion to #11629.
