### ISSUE TITLE
Change font, font size and color of various elements within WooCommerce

### ISSUE THREAD

**Issue by rocketeer76** [woothemes/woocommerce#11631]
Many themes have options and settings allowing you to change font, font size and color of various elements within the theme without changing the styles.css files manually. But when you install WooCommerce, the styles are sometimes not congruent with the styles used in the theme.

My suggestion is that the General settings page in WooCommerce is expanded a bit to be able to make some style changes without making manual changes in the styles.css file or any other css file used. Or perhaps adding a new Styles tab for these changes.

**Comment by opportus** [comment]
Hi @rocketeer76 

That's not a WooCommerce problem but your theme that seem not perfectly compatible with it.
My suggestion would be that you switch to Storefront , the official WooCommerce theme.

**Comment by mikejolley** [comment]
WC cannot control all themes elements - it won't know what CSS the theme uses/class names differ/etc.

Basic color changes without css https://en-gb.wordpress.org/plugins/woocommerce-colors/

CSS is better.
