### ISSUE TITLE
Missing a native CVS export/import feature in WooCommerce core.

### ISSUE THREAD

**Issue by raykai** [woothemes/woocommerce#11638]
## EXPLANATION OF THE ISSUE
Why is there no native CVS export/import feature in WooCommerce core ? we are in 2016 ... Backup is a must and having to spend days importing or exporting by hand is nuts even more paying a plugin 200$ when it should be free in the Core of WooCommerce.

Wordpress by default has a import and export option under tools in its core and we can choose what to export/import why not add WooCommerce import and export option in it ?

Why not add this feature in WooCommerce core ?

**Comment by mikejolley** [comment]
> Wordpress by default has a import and export option under tools in its core and we can choose what to export/import why not add WooCommerce import and export option in it ?

This supports products.

There are other vendors of CSV import/export plugins which work with custom post types.

We have no plans on including one in core for orders until https://github.com/woothemes/woocommerce/issues/10071 is complete.
