### ISSUE TITLE
Database Upgrade Routine for 2.6.x for Issue #11403

### ISSUE THREAD

**Issue by om4james** [woothemes/woocommerce#11637]
Issue #11403 fixed a bug where shipping zone postcode ranges weren't being changed from `-` to `...` when updating from WC 2.5 (with table rate shipping) to WC 2.6.

However I don't think the change in bf93f74 is going to be run for people that are already on 2.6.x prior to the fix being committed.

The result is that store owners that updated from 2.5.x to 2.6.x prior to two weeks ago won't have their postcode ranges fixed automatically.

Would it be possible to include `wc_update_260_zone_methods()` in the 2.6.5 db upgrade routine?

// cc @mikejolley @joelwills

**Comment by mikejolley** [comment]
I did contemplate this, but no. It's too risky as it would affect all users even those unaffected by this specific issue. Zone postcodes allow formatting chars now (such as -) which should not be converted to range. We have no way of knowing if the - is before upgrade, or post upgrade, so it's safer to leave alone.

`wc_update_260_zone_methods()` can be called manually if needed. But I don't want to force it on everyone.

**Comment by om4james** [comment]
Thanks for the explanation @mikejolley, that makes sense :)
