### ISSUE TITLE
REST API GET /products pagination is missing results

### ISSUE THREAD

**Issue by deusprogrammer** [woothemes/woocommerce#11635]
## EXPLANATION OF THE ISSUE

Pagination is missing multiple entries at the beginning of a page.  It seems to stop at higher id's.  The missing items are published and visible.

## STEPS TO REPRODUCE THE ISSUE

See this forum entry: https://wordpress.org/support/topic/woocommerce-get-productspagexper_pagey-missing-results

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://devcloud.bigcloudmedia.net/ttah_new45
Site URL: http://devcloud.bigcloudmedia.net/ttah_new45
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 96 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 96 MB
Default Timezone is UTC: ❌ Default timezone is America/New_York - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (9) ###

Advanced Custom Fields: by Elliot Condon – 4.4.8
The Product Brain: by Big Cloud Media – 7.0
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Simple Site Lockdown: by Philip John – 1.1.1
Social Media Feather: by Synved – 1.7.11
WooCommerce UPS Shipping: by WooThemes – 3.1.2 – 3.1.3 is available
TTAH Pay - WooCommerce Gateway: by Carlita – 1
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.4.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: TTAH_WP
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: TTAH_WP/woocommerce/archive-product.php
TTAH_WP/woocommerce/auth/footer.php
TTAH_WP/woocommerce/auth/form-grant-access.php
TTAH_WP/woocommerce/auth/form-login.php
TTAH_WP/woocommerce/auth/header.php
TTAH_WP/woocommerce/cart/cart-empty.php
TTAH_WP/woocommerce/cart/cart-item-data.php
TTAH_WP/woocommerce/cart/cart-shipping.php
TTAH_WP/woocommerce/cart/cart-totals.php
TTAH_WP/woocommerce/cart/cart.php
TTAH_WP/woocommerce/cart/cross-sells.php
TTAH_WP/woocommerce/cart/mini-cart.php
TTAH_WP/woocommerce/cart/proceed-to-checkout-button.php
TTAH_WP/woocommerce/cart/shipping-calculator.php
TTAH_WP/woocommerce/checkout/cart-errors.php
TTAH_WP/woocommerce/checkout/form-billing.php
TTAH_WP/woocommerce/checkout/form-checkout.php
TTAH_WP/woocommerce/checkout/form-coupon.php
TTAH_WP/woocommerce/checkout/form-login.php
TTAH_WP/woocommerce/checkout/form-pay.php
TTAH_WP/woocommerce/checkout/form-shipping.php
TTAH_WP/woocommerce/checkout/payment-method.php
TTAH_WP/woocommerce/checkout/payment.php
TTAH_WP/woocommerce/checkout/review-order.php
TTAH_WP/woocommerce/checkout/thankyou.php
TTAH_WP/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1
TTAH_WP/woocommerce/content-product_cat.php version 2.5.0 is out of date. The core version is 2.6.1
TTAH_WP/woocommerce/content-single-product.php
TTAH_WP/woocommerce/content-widget-product.php
TTAH_WP/woocommerce/emails/admin-cancelled-order.php
TTAH_WP/woocommerce/emails/admin-new-order.php
TTAH_WP/woocommerce/emails/customer-completed-order.php
TTAH_WP/woocommerce/emails/customer-invoice.php
TTAH_WP/woocommerce/emails/customer-new-account.php
TTAH_WP/woocommerce/emails/customer-note.php
TTAH_WP/woocommerce/emails/customer-processing-order.php
TTAH_WP/woocommerce/emails/customer-refunded-order.php
TTAH_WP/woocommerce/emails/customer-reset-password.php
TTAH_WP/woocommerce/emails/email-addresses.php
TTAH_WP/woocommerce/emails/email-footer.php
TTAH_WP/woocommerce/emails/email-header.php
TTAH_WP/woocommerce/emails/email-order-items.php
TTAH_WP/woocommerce/emails/email-styles.php
TTAH_WP/woocommerce/emails/plain/admin-cancelled-order.php
TTAH_WP/woocommerce/emails/plain/admin-new-order.php
TTAH_WP/woocommerce/emails/plain/customer-completed-order.php
TTAH_WP/woocommerce/emails/plain/customer-invoice.php
TTAH_WP/woocommerce/emails/plain/customer-new-account.php
TTAH_WP/woocommerce/emails/plain/customer-note.php
TTAH_WP/woocommerce/emails/plain/customer-processing-order.php
TTAH_WP/woocommerce/emails/plain/customer-refunded-order.php
TTAH_WP/woocommerce/emails/plain/customer-reset-password.php
TTAH_WP/woocommerce/emails/plain/email-addresses.php
TTAH_WP/woocommerce/emails/plain/email-order-items.php
TTAH_WP/woocommerce/global/breadcrumb.php
TTAH_WP/woocommerce/global/form-login.php
TTAH_WP/woocommerce/global/quantity-input.php
TTAH_WP/woocommerce/global/sidebar.php
TTAH_WP/woocommerce/global/wrapper-end.php
TTAH_WP/woocommerce/global/wrapper-start.php
TTAH_WP/woocommerce/loop/add-to-cart.php
TTAH_WP/woocommerce/loop/loop-end.php
TTAH_WP/woocommerce/loop/loop-start.php
TTAH_WP/woocommerce/loop/no-products-found.php
TTAH_WP/woocommerce/loop/orderby.php
TTAH_WP/woocommerce/loop/pagination.php
TTAH_WP/woocommerce/loop/price.php
TTAH_WP/woocommerce/loop/rating.php
TTAH_WP/woocommerce/loop/result-count.php
TTAH_WP/woocommerce/loop/sale-flash.php
TTAH_WP/woocommerce/myaccount/form-add-payment-method.php version 2.1 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/form-edit-account.php version 2.5.1 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/form-edit-address.php version 2.1.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/form-lost-password.php version 2.3.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/my-account.php version 2.0.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/myaccount/my-downloads.php
TTAH_WP/woocommerce/myaccount/my-orders.php
TTAH_WP/woocommerce/myaccount/view-order.php version 2.2.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/notices/error.php
TTAH_WP/woocommerce/notices/notice.php
TTAH_WP/woocommerce/notices/success.php
TTAH_WP/woocommerce/order/form-tracking.php
TTAH_WP/woocommerce/order/order-again.php
TTAH_WP/woocommerce/order/order-details-customer.php
TTAH_WP/woocommerce/order/order-details-item.php
TTAH_WP/woocommerce/order/order-details.php version 2.5.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/order/tracking.php
TTAH_WP/woocommerce/product-searchform.php
TTAH_WP/woocommerce/single-product/add-to-cart/external.php
TTAH_WP/woocommerce/single-product/add-to-cart/grouped.php
TTAH_WP/woocommerce/single-product/add-to-cart/simple.php
TTAH_WP/woocommerce/single-product/add-to-cart/variable.php
TTAH_WP/woocommerce/single-product/meta.php
TTAH_WP/woocommerce/single-product/price.php
TTAH_WP/woocommerce/single-product/product-attributes.php
TTAH_WP/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
TTAH_WP/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3
TTAH_WP/woocommerce/single-product/rating.php
TTAH_WP/woocommerce/single-product/related.php
TTAH_WP/woocommerce/single-product/review.php version 2.5.0 is out of date. The core version is 2.6.0
TTAH_WP/woocommerce/single-product/sale-flash.php
TTAH_WP/woocommerce/single-product/share.php
TTAH_WP/woocommerce/single-product/short-description.php
TTAH_WP/woocommerce/single-product/tabs/additional-information.php
TTAH_WP/woocommerce/single-product/tabs/description.php
TTAH_WP/woocommerce/single-product/tabs/tabs.php
TTAH_WP/woocommerce/single-product/title.php
TTAH_WP/woocommerce/single-product/up-sells.php
TTAH_WP/woocommerce/single-product-reviews.php
TTAH_WP/woocommerce/single-product.php
TTAH_WP/woocommerce/taxonomy-product_cat.php
TTAH_WP/woocommerce/taxonomy-product_tag.php

: Learn how to update outdated templates

**Comment by deusprogrammer** [comment]
Nope.  That doesn't resolve the issue at all.  In fact I get this error when I capitalize it.

curl -X GET https://devcloud.bigcloudmedia.net/et_test48/wp-json/wc/v1/products?orderby=ID\&order=asc\&page=7\&per_page=100 | python -m json.tool

{
    "code": "rest_invalid_param",
    "data": {
        "params": {
            "orderby": "orderby is not one of date, id, include, title, slug"
        },
        "status": 400
    },
    "message": "Invalid parameter(s): orderby"
}

**Comment by mikejolley** [comment]
@deusprogrammer a) you don't need to comment in multiple places. b) I didn't say you needed to adjust your query. The bug is in the plugin, patched above. It translates id to ID when it makes the query.

Apply fix.
Continue to use id.

**Comment by deusprogrammer** [comment]
I get that,  I just fail to see how this fixed the problem.  I am missing records regardless of what I order it by...unless all of them had this problem.

**Comment by deusprogrammer** [comment]
In any case, I will ask my client to try installing the fix and I will let you know if I continue to have the issue.  Thank you for your time.

**Comment by deusprogrammer** [comment]
I apologize for asking again, is this change in the current release, or do I have to install an unreleased version?  Because as far as I can tell, the test server I was running my REST calls on is running this newest version.
