### ISSUE TITLE
How to validate checkout field when set an order

### ISSUE THREAD

**Issue by johuder33** [woothemes/woocommerce#11634]
Hi, hope you all fine, I am trying to apply a custom validation when user set a new order with Woocommerce REST API, but I have not idea how to get it, please can anyone point me in the right direction to get this works.

**Comment by mikejolley** [comment]
There are some hooks such as woocommerce_rest_pre_insert_shop_order, however the REST API gives you direct access - any validation should be in the app creating the orders.
