### ISSUE TITLE
Translation issue w/ results count

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11644]
These lines aren't playing nice with translations: https://github.com/woothemes/woocommerce/blob/master/templates/loop/result-count.php#L38-L42

They translate fine pre-this commit: https://github.com/woothemes/woocommerce/commit/91768619599116b6004b4d031d79cd990f1c650b

Translation test:

```
function my_text_strings( $translated_text, $text, $domain ) {
	switch ( $translated_text ) {
		case 'Showing the single result' :
			$translated_text = 'Just one product';
			break;
		case 'Showing all %d results' :
			$translated_text = 'This many results: %d';
			break;
		case 'Showing %1$d&ndash;%2$d of %3$d results' :
			$translated_text = 'Displaying %1$d&ndash;%2$d of %3$d results';
			break;
	}
	return $translated_text;
}
add_filter( 'gettext', 'my_text_strings', 20, 3 );
```

https://wordpress.org/support/topic/product-counter

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Function_Reference/_nx

> Uses the 'ngettext_with_context' filter.

**Comment by claudiosmweb** [comment]
@WPprodigy after this commit, probably in some languages will need to be translated again, since WP will update the "singular" and let missing the "plural" translation. I had to fix it in the pt_BR translation.

**Comment by claudiosmweb** [comment]
![screenshot from 2016-08-16 17-25-05](https://cloud.githubusercontent.com/assets/1264099/17714491/6865a90c-63d6-11e6-92e6-d953327430ab.png)

The first one is when are missing the second translation ^
