### ISSUE TITLE
WooCommerce Subscriptions + WooCommerce Subscription Downloads

### ISSUE THREAD

**Issue by russoanthony** [woothemes/woocommerce#11656]
## EXPLANATION OF THE ISSUE

Using the following:
Fresh Install of WordPress and WordPress 2016 Theme
WooCommerce 2.6.4
WooCommerce Subscriptions 2.0.18
WooCommerce Subscription Downloads 1.1.4

Note: All products are using the subscription downloads plugin to attach to a subscription.

What Happens:
A new subscription order is placed and activated.  When checking the download permissions in the backend the new order shows nothing on the subscription details screen located in WooCommerce > Subscriptions > #subscriptionorder

However, it does show the download permissions on the "parent order" from the orders screen.

Now here is where it gets really weird, when you add a new product, that product WILL show up on the subscription details screen that nothing was showing on earlier, Even if the product is set as "DRAFT" it will still show on the front end in their downloads area. However, if you regenerate download permissions it will remove it.  If you don't regenerate the download permissions then it will show a duplicate downloadable product on the front end.

And to top all of this off, if you cancel the subscription, any products using the subscription downloads will still show on the front end for the customer.  So they have unlimited access all the time, regardless of subscription status.

There is something seriously wrong here that needs to be addressed.

How it should work:
1) If a downloadable product is using subscription downloads area, a "DRAFT" product shouldn't show on any order until marked "PUBLISHED"

2) All download permissions should be attached to the subscriptions screen only, not to the parent order, to eliminate duplicate products.

3) After a subscription is cancelled, on hold, not active --- user shouldn't see downloads on front end.

**Comment by mikejolley** [comment]
From the ticket form:

> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

use support.woothemes.com for subscriptions issues please.

**Comment by russoanthony** [comment]
It's not really a support issue, it's a bug in your plugin but alright.
