### ISSUE TITLE
Put order_review_heading into a hook

### ISSUE THREAD

**Issue by allanchau** [woothemes/woocommerce#11655]
`<h3 id="order_review_heading"><?php _e( 'Your order', 'woocommerce' ); ?></h3>`

This line of code grows separately to the rest of the Your Order sections when using flexbox and trying to move the Your Order sections to the right of the billing and shipping details.

Replacing this with a hook would provide more flexibility and allow the heading to be moved into the order_review section.

![screen shot 2016-08-09 at 11 41 06 pm](https://cloud.githubusercontent.com/assets/1763968/17519380/de583c02-5e8a-11e6-8c36-2226a145f5b9.png)

**Comment by jameskoster** [comment]
`woocommerce_checkout_order_review` looks like the best candidate

**Comment by jameskoster** [comment]
Let's leave this. It won't be an issue once we've worked through #10672 (should be next year).

You can create this layout currently using CSS. It's not perfect but it works. See Storefront.
