### ISSUE TITLE
Failed to receive the new order by email

### ISSUE THREAD

**Issue by sammieEdinburgh** [woothemes/woocommerce#11660]
## EXPLANATION OF THE ISSUE
Failed to receive the new order by email. We rely on the email to monitor the new order. It always work. However, since I update the new version of woocommerce yesterday. It failed. It still show new orders in the woocommerce but I am no longer receive the email. Please help

## STEPS TO REPRODUCE THE ISSUE

Woocommerce ---> setting ----> email ----> new order ---> config ---> put new email. ---> save

## SYSTEM STATUS REPORT
we test it with different emails account. The emails are fine. We just don't receive the order anymore
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://sammieedinburgh.co.uk
Site URL: https://sammieedinburgh.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.42 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 65 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (16) ###

Share Buttons by AddThis: by The AddThis Team – 5.3.3
Akismet: by Automattic – 3.1.11
EU Cookie Law: by Alex Moss
Marco Milesi
Peadig
Shane Jones – 2.9.3

Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.1
MailMunch - Increase your Email Subscribers by over 500%: by MailMunch – 2.0.3
VarkTech Min and Max Purchase for WooCommerce: by Vark – 1.07.91
Ninja Forms: by The WP Ninjas – 2.9.55.1
Post Types Order: by Nsp Code – 1.8.9.2
Slider Revolution: by ThemePunch – 5.2.3.5
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.3
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce SagePay Form and SagePay Direct Gateway: by Add On Enterprises (Andrew Benbow) – 3.2.3 – 3.3.3 is available
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.4.2
WP Smush: by WPMU DEV – 2.4.3

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #3152 - /shop-2/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #11 - /my-account-2/

### Taxonomies ###

Product Types: external (external)
food (food)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: store-child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.0.4 – 2.0.7 is available
Parent Theme Author URL: https://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: store-child/woocommerce/emails/plain/admin-new-order.php
`

**Comment by mikejolley** [comment]
Emails send when the order status is changed to 'processing', 'on-hold' or 'completed'. Check your orders have this status.

You can see if emails are 'sending' but you're just not receiving them with https://wordpress.org/plugins/wp-mail-logging/ Don't forget to check your spam box.

If not spammed, but logged as sending, it may be a server issue. Try using a different method of email sending with https://wordpress.org/plugins/wp-smtp/

You can also combine https://wordpress.org/plugins/wp-smtp/ with https://www.mandrill.com/ or https://www.mailgun.com/ for improved deliverability and logging. I recommend this anyway.
