### ISSUE TITLE
json_encode add JSON_PRESERVE_ZERO_FRACTION Parameter for Webhooks

### ISSUE THREAD

**Issue by 3rdMillWeb** [woothemes/woocommerce#11663]
## EXPLANATION OF THE ISSUE

On 2.6.4 and since 2.2, on line 198 of class-wc-webhook.php, it trims and json_encodes the $payload array for the webhook. However, the PHP json_encode function converts PHP floats back to the original number (sometimes with many many decimal places. This has been problematic for our accounting system, which doesn't like partial cents.

However, this can be fixed by replacing this line:
`			'body'        => trim( json_encode( $payload ) ),
`
With this line:
`			'body'        => trim( json_encode( $payload ), JSON_PRESERVE_ZERO_FRACTION ),
`

With this implemented, numbers in the $payload variable that are floats will retain the same amount of decimals (and therefore the same exact value). However, if this is not implemented, there are numeric discrepancies between the numbers in the array of the $payload variables and the 'body' parameter of the request based on the $payload variable. Does that make sense?

Many thanks,

Kyle

**Comment by mikejolley** [comment]
Can your system round @3rdMillWeb? I mean, we could add that but it's PHP 5.6 + so the API would be inconsistent between versions which isn't great.

**Comment by 3rdMillWeb** [comment]
From what I understand, I would have to take all the numbers, put them in a database, take them out of the database, and then send it to the json_encode. The reason being, is that the number that gets dumped in the json_encode is slightly different than a rounded number in PHP. If you round a number:
`$number = round( 1.4999900005566222, 2 ) `
then var_dump it
`var_dump( $number )`
You will see:
`float(21.36)`
However, after it goes through the JSON Encode, it will go back to its unrounded value:
`1.4999900005566222`
The only way besides the database trick above that I have found to work is to add the constant JSON_PRESERVE_ZERO_FRACTION.

**Comment by claudiosmweb** [comment]
Well, first of all... It's good to read the `trim()` function documentation: http://php.net/manual/en/function.trim.php

> Strip whitespace (or other characters) from the beginning and end of a string

So what removing whitespace from the beginning and end of the JSON can change the number of decimals? 
The answer is: Absolutely nothing...

Good to read the description of this second param for `trim()` too, see:

> Optionally, the stripped characters can also be specified using the `character_mask` parameter. Simply list all characters that you want to be stripped. With .. you can specify a range of characters.

And checking the `JSON_PRESERVE_ZERO_FRACTION`:

```
php -a  
Interactive mode enabled

php > var_dump(JSON_PRESERVE_ZERO_FRACTION);
int(1024)
```

Well, no idea now why you want to remove `1024` from the beginning and end of the JSON string.

Ok, and if we use the `JSON_PRESERVE_ZERO_FRACTION` in the correct place, I mean, if we use this in the `json_encode()` function?

```
php -a  
Interactive mode enabled

php > var_dump(json_encode([1.4999900005566222]));
string(17) "[1.4999900005566]"
php > var_dump(json_encode([1.4999900005566222], JSON_PRESERVE_ZERO_FRACTION));
string(17) "[1.4999900005566]"
```

It's only returning the same number, check the constant docs http://php.net/manual/en/json.constants.php

> Ensures that `float` values are always encoded as a float value. Available since PHP 5.6.6.

This don't change anything in the number of decimals or something like it... Just ensure that `float` is a real `float` value.
But in our REST API we use `wc_format_decimal()` that will make all `float` converted to `string`, there is no problem with that and you can convert to `float` with you really need this as a `float`.

Example in PHP:

```
php -a
Interactive mode enabled

php > var_dump('1.4999900005566222');
string(18) "1.4999900005566222"
php > var_dump((float) '1.4999900005566222');
float(1.4999900005566)
```

**Comment by claudiosmweb** [comment]
But if the problem is the number of decimals returned after the `wc_format_decimal()`, you can solve after apply this my commit: https://github.com/woothemes/woocommerce/commit/9da3f79f41148f5e97e2b4e58beb7ee6ab097b90

Now you can set the number of decimals from the response.
Here an example:

```
add_filter( 'woocommerce_webhook_order_payload_filters', function( $filters ) {
    $filters['dp'] = 4; // 4 decimals.

    return $filters;
});
```

**Comment by 3rdMillWeb** [comment]
Thank you @claudiosmweb, that answer the question.
