### ISSUE TITLE
Woo-commerce webhook are sending incorrect json

### ISSUE THREAD

**Issue by Yashwant16005** [woothemes/woocommerce#11677]
## EXPLANATION OF THE ISSUE

Hi There, We are testing woocommerce rest API, we created a webhook for Products to sync data between salesforce anf woo-commerce  and earlier webhook was sending correct data but from this Monday there is some issue with same webhook.
**Correct format before-**
`"price_html":"<del><span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">$<\/span>5.00<\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">$<\/span>4.00<\/span><\/ins>"`

**Current format-**
`"price_html":"<del><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>8.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>7.00</span></ins>"`

Notice there are no '\' that is causing the issue

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://test.ducklearning.com
Site URL: http://test.ducklearning.com
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 168 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.44 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
Max Upload Size: 32 MB
Default Timezone is UTC: ❌ Default timezone is Asia/Singapore - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (57) ###

Gravity Forms: by rocketgenius – 1.9.17.6
Admin Custom Login: by weblizar – 2.1
Better Analytics: by Digital Point – 1.1.2
Duplicate / Clone Pages and Posts: by It Spiders – 1.2
Easy WP SMTP: by wpecommerce – 1.2.3
Event Espresso - Calendar: by Event Espresso – 2.2.6.p
Event Espresso API Plugin: by Event Espresso
(Mike Nelson) – 2.1.4.P

Event Espresso - Recurring Events: by Abel Sekepyan – 1.1.4
Event Espresso - Ticketing: by Event Espresso – 2.2.0.p
Event Espresso (shared on wplocker.com): by Event Espresso – 3.1.36.6.P
FlatFolio - Portfolio & Gallery: by unCommons – 1.0
Global Content Blocks: by Dave Liske – 2.1.5
Event Espresso - Social Coupons: by Seth Shoultes – 1.5.4.p
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.7.2
Media from FTP: by Katsushi Kawamori – 9.01
Newsletter: by Stefano Lissa
The Newsletter Team – 4.0.7

oik Weight/Country Shipping: by bobbingwide – 1.3.1
Parallax Backgrounds for VC: by Benjamin Intal - Gambit – 3.6.1
Quotation List: by An Thai – 1.0
Real 3D Flipbook: by zlac – 1.4.11
REST API Console: by WP REST API Team – 2.0.1
WP REST API: by WP REST API Team – 2.0-beta13.1
Revolution Slider: by ThemePunch – 4.6.5
Scroll Back to Top: by Joe Sexton – 1.1.3
Special Recent Posts FREE Edition: by Luca Grandicelli – 2.0.4
Event Espresso - Custom Template Display: by Event Espresso – 1.1.p
Testimonials Showcase: by Carlos Moreira – 1.1.7
ThemeStudio Post Types, Metaboxes: by ThemeStudio Development Group – 1.0
ThemeStudio Shortcodes: by ThemeStudio – 1.0
Types: by OnTheGoSystems – 1.8.11
Ultimate Member: by Ultimate Member – 1.3.52
Widgets on Pages: by Todd Halfpenny – 0.0.12
WonderPlugin Slider: by Magic Hills Pty Ltd – 5.1
Advanced Order Export For WooCommerce: by AlgolPlus – 1.1.11
WooCommerce Category Slider: by gVectors Team – 1.0.0
WooCommerce Checkout Field Editor (shared on wplocker.com): by WooThemes / Mike Jolley / Patrick Garman – 1.2.11 – 1.4.10 is available
WooCommerce Cost of Goods: by WooThemes / SkyVerge – 2.0.1 – 2.2.1 is available
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Dropdown Cart: by svincoll4 – 1.4.1
WooCommerce Dynamic Gallery LITE: by A3 Revolution – 1.4.4
WooCommerce Grid / List toggle: by jameskoster – 1.0.0
Woocommerce Login / Signup Lite: by phoeniixx – 1.2
WooCommerce My Account Widget: by Bart Pluijms – 0.5.0
Woocommerce New Orders Dashboard Widget: by swadeshswain – 2.2
Woocommerce Product Slider: by Kiran Polapragada – 1.5.5
WOOF - WooCommerce Products Filter: by realmag777 – 1.1.2
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.1
WooCommerce To Salesforce Integration: by Yojacnce Rabelo – 0.0.1
WooCommerce Local Pickup Plus: by WooThemes / SkyVerge – 1.12.0 – 1.13.2 is available
WooCommerce Simple Registration: by Astoundify – 1.0.1
WooCommerce: by WooThemes – 2.6.2
WooThemes Helper: by WooThemes – 1.5.9
WordPress Importer: by wordpressdotorg – 0.6.1
WP All Import: by Soflyy – 3.3.3
WP Resized Image Quality: by Mike Bijon
Etch Software – 2.1.2

WPB WooCommerce Product slider: by wpbean – 1.0.2
YITH Infinite Scrolling: by Yithemes – 1.0.4

### Settings ###

Force SSL: ✔
Currency: SGD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #2852 - /shop/
Cart: #2853 - /cart/
Checkout: #2854 - /checkout/
My Account: #2855 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: ALASKA
Version: 1.4.2
Author URL: http://www.vungoclinh.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: alaska/woocommerce/archive-product.php
alaska/woocommerce/cart/cart-empty.php
alaska/woocommerce/cart/cart-item-data.php version 2.1.0 is out of date. The core version is 2.4.0
alaska/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 2.5.0
alaska/woocommerce/cart/cart-totals.php
alaska/woocommerce/cart/cart.php
alaska/woocommerce/cart/cross-sells.php
alaska/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 2.5.0
alaska/woocommerce/cart/shipping-calculator.php
alaska/woocommerce/checkout/cart-errors.php version 1.6.4 is out of date. The core version is 2.4.0
alaska/woocommerce/checkout/form-billing.php
alaska/woocommerce/checkout/form-checkout.php
alaska/woocommerce/checkout/form-coupon.php
alaska/woocommerce/checkout/form-login.php
alaska/woocommerce/checkout/form-pay.php version 1.6.4 is out of date. The core version is 2.5.0
alaska/woocommerce/checkout/form-shipping.php
alaska/woocommerce/checkout/payment-method.php
alaska/woocommerce/checkout/payment.php version 2.3.0 is out of date. The core version is 2.5.0
alaska/woocommerce/checkout/review-order.php
alaska/woocommerce/checkout/thankyou.php
alaska/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 2.6.1
alaska/woocommerce/content-product_cat.php version 1.6.4 is out of date. The core version is 2.6.1
alaska/woocommerce/content-single-product.php
alaska/woocommerce/content-widget-product.php version - is out of date. The core version is 2.5.0
alaska/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 2.5.0
alaska/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 2.5.0
alaska/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 2.5.0
alaska/woocommerce/global/breadcrumb.php
alaska/woocommerce/global/form-login.php
alaska/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
alaska/woocommerce/global/sidebar.php
alaska/woocommerce/global/wrapper-end.php
alaska/woocommerce/global/wrapper-start.php
alaska/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 2.5.0
alaska/woocommerce/loop/loop-end.php
alaska/woocommerce/loop/loop-start.php
alaska/woocommerce/loop/no-products-found.php
alaska/woocommerce/loop/orderby.php
alaska/woocommerce/loop/pagination.php
alaska/woocommerce/loop/price.php
alaska/woocommerce/loop/rating.php
alaska/woocommerce/loop/result-count.php
alaska/woocommerce/loop/sale-flash.php
alaska/woocommerce/notices/error.php
alaska/woocommerce/notices/notice.php
alaska/woocommerce/notices/success.php
alaska/woocommerce/order/form-tracking.php
alaska/woocommerce/order/order-again.php
alaska/woocommerce/order/order-details.php version 2.3.0 is out of date. The core version is 2.6.0
alaska/woocommerce/order/tracking.php
alaska/woocommerce/product-searchform.php version - is out of date. The core version is 2.5.0
alaska/woocommerce/single-product/add-to-cart/external.php
alaska/woocommerce/single-product/add-to-cart/grouped.php
alaska/woocommerce/single-product/add-to-cart/simple.php
alaska/woocommerce/single-product/add-to-cart/variable.php version 2.3.0 is out of date. The core version is 2.5.0
alaska/woocommerce/single-product/meta.php
alaska/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 2.4.9
alaska/woocommerce/single-product/product-attributes.php
alaska/woocommerce/single-product/rating.php
alaska/woocommerce/single-product/related.php
alaska/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.6.0
alaska/woocommerce/single-product/sale-flash.php
alaska/woocommerce/single-product/share.php
alaska/woocommerce/single-product/short-description.php
alaska/woocommerce/single-product/tabs/additional-information.php
alaska/woocommerce/single-product/tabs/description.php
alaska/woocommerce/single-product/tabs/tabs.php version 2.0.0 is out of date. The core version is 2.4.0
alaska/woocommerce/single-product/title.php
alaska/woocommerce/single-product/up-sells.php
alaska/woocommerce/single-product-reviews.php
alaska/woocommerce/single-product.php
alaska/woocommerce/taxonomy-product_cat.php
alaska/woocommerce/taxonomy-product_tag.php

**Comment by mikejolley** [comment]
Logging the actual content, it is escaped:

http://glui.me/?i=eka0w4bpm6g6rus/2016-08-12_at_14.35.png/

It's just the log which removes those due to it being saved to meta. The actual webhook content is fine. Does not look like a bug.

@claudiosmweb

**Comment by claudiosmweb** [comment]
Need to be escaped since this are using JSON.
