### ISSUE TITLE
Cash on delivery does not work for Physical + Virtual Product in an order

### ISSUE THREAD

**Issue by agarwalc** [woothemes/woocommerce#11671]
## EXPLANATION OF THE ISSUE

When a customer places an order for Physical product and a virtual product together; and chooses Cash on delivery mode of payment, the order registers in the system successfully, but status changes to "On-Hold" instead of "Processing" and Payment mode changes to BACS automatically. 

## STEPS TO REPRODUCE THE ISSUE

1) Add a Physical Product to Cart
2) Add a Virtual Product to Cart
3) Check out normally using "Cash on delivery" payment method
4) Go to Wordpress Admin > Woocommerce > Orders
5) Select the order just placed for this story
6) View Order Status and Payment Method

Running latest version of Wordpress and Woocommerce. 

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Works perfectly fine my side. Also, on-hold is used for downloadable virtual orders FYI. So the user does not have instant access before payment.
