### ISSUE TITLE
Order Create, Product create webhook not working 

### ISSUE THREAD

**Issue by Rachit-Dev** [woothemes/woocommerce#11686]
## EXPLANATION OF THE ISSUE

On latest version of woo commerce, I am testing order create and product create  action of web hook and its not working no logs are generated , but its working for customer create , order update and any other action. i am using UI to create a order or update it. 

Please help me resolve the issue.
    

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by Rachit-Dev** [comment]
The issue is not fix with edit the code.

**Comment by mikejolley** [comment]
Is on my store - started logging as soon as I fixed the above.

**Comment by souravthakur1992** [comment]
i have done a test installation of the woocomerce on my local enviornment  to setup a integration with my .net app , i am able to do authorization and registration of  webhook in wocommerce app from my .net app.first time authorization of the devilery url is also completed succesfully but whenever i am creating any order or product nothing is triggred from my wocommerce app  to .net app.
I have gone through status > logs but nothing appears there.kindly suggest me to solve this :)
![image](https://user-images.githubusercontent.com/13482053/37080539-a2652696-220c-11e8-9c5e-3b176613cffc.png)
