### ISSUE TITLE
Slow query when viewing a product if wp_posts is very large

### ISSUE THREAD

**Issue by amfriedman** [woothemes/woocommerce#11683]
## EXPLANATION OF THE ISSUE

There is a query that I believe is originating in WooCommerce that runs on single product pages. I have a wp_posts table with 45M rows (but only a few of these are post_type "product"). I am using an unmodified twentyfifteen theme. When I visit a test product front-end page, my database spends 60 seconds on the query below. Nothing else is really on the page. The only widget is the WooCommerce cart with a product in it. Here is the problem query:

`SELECT p.ID FROM wp_posts AS p WHERE p.post_date < '2016-08-11 16:30:53' AND p.post_type = 'product' AND ( p.post_status = 'publish' OR p.post_status = 'private' ) ORDER BY p.post_date DESC LIMIT 1;`

(The specific date-time you see is really the current date-time that the page is accessed.)
 
When I run EXPLAIN on the query, it shows that it is accessing all 45M rows even though the table is well-indexed. When I remove the "p.post_date" entry from the WHERE clause, then the query successfully uses the best index and runs in milliseconds. (And yes, post_date has also been indexed.)

**Comment by mikejolley** [comment]
get_adjacent_post() called by WP core.

Can be disabled with filter https://gist.github.com/aaronpeterson/9637291

**Comment by mikejolley** [comment]
This is for paginated relationships - totally pointless for products. Will unhook.
