### ISSUE TITLE
Customer Invoice has the items priced at Zero even after entering the price manually in the Backend

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#11680]
## EXPLANATION OF THE ISSUE

Customer Invoice has the items priced at Zero even after entering the price manually in the Backend. 

## STEPS TO REPRODUCE THE ISSUE
 
1.  Create a Simple product with out any regular/sale price. ![](http://cld.wthms.co/10Od3/1w0WdsTJ+)
2. Create an order in the backend, add the above created Simple product and increase the quantity to 4 while setting each product cost at 29.95, this would lead to a total cost of $134.80 after adding a shipping cost of 15:  ![](http://cld.wthms.co/1gXgu/5v92GLAA+)
3. Save the order and send customer invoice and this is received:   ![](http://cld.wthms.co/1fu8F/5bZw8joH+)

@gedex @dwainm @stevetested @BFTrick @tommyshellberg @slash1andy @pmciano @hannahswain @iMazed @corsonr

**Comment by mikejolley** [comment]
Testing on both release/2.6 and master branches.

Added zero cost product.

Add to order. Click send invoice.

It sent with price included https://dl.dropboxusercontent.com/s/9wbg8fbhphbvgmo/2016-08-12%20at%2011.12.png?dl=0

Tried a few variations e.g. not saving line items/saving line items. Each case passed.

**Comment by danieldudzic** [comment]
I was able to replicate the issue with WooCommerce 2.6.4.

Here's the screencast: http://cld.wthms.co/1aus0/4K3nJPhN

**Comment by mikejolley** [comment]
Subtotal is shown; you left it as 0.

**Comment by harishankerr** [comment]
Tried replicating the issue using the same steps as @danieldudzic and @spraveenitpro in WC 2.6.4 : Created a product with zero cost, added the order cost in the backend (including shipping costs) and got the invoice with correct order totals but with the subtotals shown as zero.

However, the _real_ issue here seems to be _different_. Please allow me to explain.

So, after manually adding the zero priced product to the manually created order, I tried changing its pricing in the same way:

![Changing Pricing](http://cld.wthms.co/okfs/55UuNmS9+)
http://cld.wthms.co/okfs/55UuNmS9

However, when I saved my changes, it seems, WooCommerce still calculated the total price as zero.:

![Order Price Still Zero](http://cld.wthms.co/10nRJ/3cGMiIcV+)
http://cld.wthms.co/10nRJ/3cGMiIcV

Evidently, the changes I tried to make in the product price were applied as a *discount*. So, in short, the product price remains the same when you try to edit the price of a product, for an order you placed from the backend. The changes you made will be added as discounts. So, the overall price of the product is jacked up, but any changes you make will be reversed as discounts, and the net product price remains the same, as evident in the screenshot. 

However, this is a little confusing when it comes to the customer invoice, where the overall product price(s) and the subtotals are set to zero, while the order totals show a different number. 

![Order Totals Screenshot](http://cld.wthms.co/1kYxG/5lM758TG+)
http://cld.wthms.co/1kYxG/5lM758TG

So, my questions here are:

1. Can we edit product prices from the order screen for manually created orders. If we can, then there is a bug here, as WooCommerce adds a discount equivalent to the same change in price.

2. If this is not a bug, I think it would be a good idea to change the invoice to include the discount(s) and/or disable the price editing functionality in the manual order adding screen.

3. Make provision to add a discount in the order page clearer? (Just a suggestion)

@mikejolley

**Comment by mikejolley** [comment]
You need to set both the total and subtotal fields - that is the issue here.
