### ISSUE TITLE
WP CLI: filter to wp wc list

### ISSUE THREAD

**Issue by mihdan** [woothemes/woocommerce#11689]
Command

`wp wc product list --attributes.supplier.0.name="FineDesign" --limit=10 --order=asc `

not work for me

PS: supplier - custom attribute

**Comment by mikejolley** [comment]
Can you test @claudiosmweb? Not sure if this is documented or even possible.

**Comment by claudiosmweb** [comment]
Will not work, since is limiting to only 10, this method will query for all products and filter the results... not the query. It may work for you if use the limit as `1000` or something bigger than 10.

**Comment by claudiosmweb** [comment]
There's no filter like `attributes.ATTRIBUTE_SLUG.0.name="VALUE"`.

**Comment by granatmedia** [comment]
how to filter by attributes?

**Comment by claudiosmweb** [comment]
@granatmedia don't have support for it yet, will be after #11611

**Comment by granatmedia** [comment]
ok
