### ISSUE TITLE
v3 API site capabilities index not ported to wp-json/wc/v1

### ISSUE THREAD

**Issue by neonics** [woothemes/woocommerce#11693]
The [`/wc-api/v3/` index](http://woothemes.github.io/woocommerce-rest-api-docs/v3.html#index) containing the site timezone, currency, woocommerce  version etc. capabilities  ([code here](https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-server.php#L442)) is missing in the new wp-json/wc/v1 endpoint.

**Comment by mikejolley** [comment]
This is not a straight up port - the new rest API is completely new so we shouldn't assume things in v3 should be present. 

The data on the endpoints are the important parts. As long as the data is consistent across v1 of the new Rest API, WooCommerce version for example is irrelevant. 

If you have a valid use-case for this information, reply back and @claudiosmweb can review. I don't however feel that should be public.

Just to note, the next version will have a settings API which could be a place to pull such information if needed. Just not on the index.

**Comment by neonics** [comment]
Yes, I've noticed it's not a straight port when upgrading my client code :-)

I understand and agree that it doesn't need to be on the public index, but I feel there's definitely a place for at least timezone, currency and language information in the API somewhere. That new settings API you mentioned will be sufficient.

The use case is that we manage multiple shops with multiple languages and currencies (a few of which are WooCommerce) using a single product catalog and central order processing. Having access to it using the API would allow us to set up a new shop using only the shop URL and the API keys, and verify that both ends are configured the same.
But it's by no means a must - the data can be redundantly entered by the user. It's just that the new API has less functionality than the old one, where this information is concerned, and I thought I'd make a note about this.

Again thanks for your time and keep up the good work!
