### ISSUE TITLE
'File' link on My Accounts->Downloads incorrect for variations

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#11699]
Explanation here:

https://wordpress.org/support/topic/customer-dashboard-downloadable-item-link-is-wrong?replies=2#post-8755836

http://cld.wthms.co/MKkl/3cz0u1UG

Using 2.6.4.

**Comment by nishitlangaliya** [comment]
@tommyshellberg ,
I have added fixes for above issue and created pull request for the same please check for the same
Commits : https://github.com/woothemes/woocommerce/pull/11698/commits/dd445d8f0984c66a7117bc50d96be09fc4d81dff
