### ISSUE TITLE
Default Permalinks makes Shop Page 2 yield "File not found (404 Error)"

### ISSUE THREAD

**Issue by Vaygrim** [woothemes/woocommerce#11692]
## EXPLANATION OF THE ISSUE
WooCommerce v2.6.4 / WooCommerce Currency Switcher v1.1.7 / Printful Integration for WooCommerce v1.2.5 / Wordpress 4.5.3

If you go to http://vaygrim.com/shop/ you'll see a list of 5 product pages, with a set of 'change page' buttons just below them. Click on the link for Page 2 of the shop and you get a "File not found (404 Error". However! If you go to http://vaygrim.com/product-category/product/ then the Page 2 button WORKS.

This means that customers have to go to the shop main page, click on a product, click on the "Products" breadcrumb at the top of that product page.. THEN they've got a working main shop page.

Permalinks settings right now: 
- COMMON SETTINGS: "Post Name"
- PRODUCT PERMALINKS: "Default"
- OPTIONAL: All fields empty / default.

## STEPS TO REPRODUCE THE ISSUE
See description of issue directly above, this describes the steps to reproduce the error.

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://vaygrim.com
Site URL: http://vaygrim.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 48 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.45 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (6) ###

Jetpack by WordPress.com: by Automattic – 4.1.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Printful Integration for WooCommerce: by Printful – 1.2.5
The Events Calendar: by Modern Tribe
Inc. – 4.2.4

WooCommerce Currency Switcher: by realmag777 – 1.1.7
WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #538 - /shop/
Cart: #539 - /cart/
Checkout: #540 - /checkout/
My Account: #541 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Arcade Basic
Version: 1.0.8
Author URL: http://bavotasan.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
No issues locally with the settings you explain, however, your site is not matching what you've said.

http://vaygrim.com/product-category/product/ - thats not a product category, thats your shop page. 

You can see here their is an extra suffix on category links http://vaygrim.com/product-category/product/mugs/

So re-check your settings and recreate your shop page if you need to.

Closing as I'm unable to replicate with these settings:

https://dl.dropboxusercontent.com/s/n2uad1f28dvti8h/2016-08-15%20at%2018.14.png?dl=0
