### ISSUE TITLE
Error on orderby template

### ISSUE THREAD

**Issue by vajrasar** [woothemes/woocommerce#11701]
Whenever I try to override whole woocommerce folder, it gives me the following error -

` Call to undefined function wc_query_string_form_fields() in /home/imakewmq/public_html/ccat/wp-content/themes/understrap/woocommerce/loop/orderby.php on line 30`

If I comment the file in question or the loop template folder, everything runs fine. I'm on the latest version of woocommerce. Any ideas?

**Comment by mikejolley** [comment]
You're taking the version from github (master). This is not compatible with the stable release. Download the stable version from https://wordpress.org/plugins/woocommerce/ and use those templates.

p.s. overriding all templates is not a great idea. Just do the ones you need.
