### ISSUE TITLE
Inventory quantity does not show in front-end

### ISSUE THREAD

**Issue by doviis** [woothemes/woocommerce#11706]
## EXPLANATION OF THE ISSUE

The problem is that when I check that always show the stock under Woocommerce->Settings->Products->Inventory, the website does not show. It only shows "IN STOCK" or "OUT OF STOCK". 2 lines, thats all.

I want that the customer can see how many stock is available. Also, if there is none available (0 items in stock), they can also see, that the product is out of stock, but can be backordered and will be delivered in a week.

## SYSTEM STATUS REPORT

Woocommerce 2.6.5
WP Version:	4.5.3
Installed theme: Furnicom

I am also uploading a pictures to be clear!

![github 1](https://cloud.githubusercontent.com/assets/16043398/17698463/080d9f9a-63c4-11e6-913e-05ce4b8b1d6f.PNG)
![github 2](https://cloud.githubusercontent.com/assets/16043398/17698464/08242a8a-63c4-11e6-9481-153e4c1fa7a3.PNG)
![github 3](https://cloud.githubusercontent.com/assets/16043398/17698465/083aa5bc-63c4-11e6-928c-0365857724d8.PNG)

**Comment by claudiosmweb** [comment]
Check with the theme author, since this is working just fine in Storefront and in the WordPress default themes.

**Comment by cajustus** [comment]
i have exactly the same issue as the person above and I have activated the custom stock status plugin but nothing shows in frontend
