### ISSUE TITLE
Backorders - Customers can not order products which are out of stock, but backorders are allowed.

### ISSUE THREAD

**Issue by klocki** [woothemes/woocommerce#11705]
## EXPLANATION OF THE ISSUE

The new behaviour for backorders doesn´t make sense - and it is not working together with the logic of several ERP Connectors.

If quantity is 0 the product should be out of stock and if you allow backorders for the product the product should be still out of stock but the user should be able to order it. It is NOT the same as if the product would be "in stock" because for backorders we display a different time for delivery than for items which are on stock.

This is how the logic should work:

    Available: 10 Backorder: no - display: "on stock" enable add to cart
    Available: 0 Backorder: no - display: "out of stock" disable add to cart
    Available: 10 Backorder: yes - display: "on stock" enable add to cart
    Available: 0 Backorder: yes - display: "delivery time X - Y days" enable add to cart

**Comment by doviis** [comment]
I have the same problem and looking for fix of this problem for weeks!! Please help someone?!

**Comment by claudiosmweb** [comment]
> The new behaviour for backorders doesn´t make sense - and it is not working together with the logic of several ERP Connectors.

What new behaviour?
We did not changed how backorders works... 

With stock:

![screenshot from 2016-08-18 01-04-31](https://cloud.githubusercontent.com/assets/1264099/17761701/c2b67576-64df-11e6-8e1c-45f5d92e5c74.png)
![screenshot from 2016-08-18 01-04-55](https://cloud.githubusercontent.com/assets/1264099/17761707/cbb92092-64df-11e6-82c8-ec7e37f8c6c8.png)

`0` stock:

![screenshot from 2016-08-18 01-05-37](https://cloud.githubusercontent.com/assets/1264099/17761723/f6a6421c-64df-11e6-943f-7a9e50f20667.png)
![screenshot from 2016-08-18 01-05-58](https://cloud.githubusercontent.com/assets/1264099/17761725/f935aa90-64df-11e6-9c86-512bda7a4485.png)
![screenshot from 2016-08-18 01-06-07](https://cloud.githubusercontent.com/assets/1264099/17761726/fb7cdc92-64df-11e6-9f74-caa387018fd6.png)

This working correctly, the same way that always works.

**Comment by klocki** [comment]
Hello Claudio, 
Thank you for your reply. I think I did not really clarify what the point is. The flag "stock status" needs to be set to "in stock" while the product is actually out of stock and available for backorder - this does not make sense, and it is a behaviour that was actually changed somewhere between 2.5.1 and today.
Alex

**Comment by mikejolley** [comment]
Out of stock products cannot be purchased and in some cases are hidden from the catalog. That's why it uses in stock status, but customer never sees this so it matters not.

**Comment by puregraphx** [comment]
Hi Mike,
On our site, products in stock can be delivered withing 2 days, but products out of stock take about 2-3 weeks to be delivered. In order to avoid losing customers for out of stock products, we allow backorders.

Now, to allow backorders, a product needs to be set to "In Stock" which will trigger the message in the front end "will ship in 2 days", which is false. If we set it to Out of Stock, we get "ships in 2-3 weeks" BUT, then the Add to Cart button is disabled even though backorders are allowed.

So you see, with the current WC logic, we are stuck. Either we misinform people that backorders ship in 2 days, either customers cannot add to cart because of the Out of Stock setting. What do you suggest?

**Comment by clapczyn** [comment]
Hey puregraphx, 
I am currently trying to achieve the exact same thing – show different delivery times for products on backorder. Did you ever solve this problem? 

Would be really cool if you could point me in the right direction!
Thx

**Comment by puregraphx** [comment]
@clapczyn we changed the the message through the theme's functions.php file
`add_filter( 'woocommerce_get_availability', 'wcs_custom_get_availability', 1, 2);
function wcs_custom_get_availability( $availability, $_product ) {
    // Change In Stock Text
    if ( $_product->is_in_stock() && ! $_product->backorders_allowed() ) {
        $availability['availability'] .= __('<br />Shipped immediately', 'custom');
    }
    if ( $_product->is_in_stock() && $_product->backorders_allowed() ) {
        $availability['availability'] = __('<br />We will inform you via email when the product is back in stock. Please send us your contact info via the form below.', 'custom');
    }
    // Change Out of Stock Text
    if ( ! $_product->is_in_stock()  ) {
        $availability['availability'] .= __('<br />We will inform you via email when the product is back in stock. Please send us your contact info via the form below.', 'custom');
    }
    return $availability;
}`

**Comment by clapczyn** [comment]
Thx man, works like a charm!
