### ISSUE TITLE
Modal shipping zone instance settings fails for array inputs.

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#11703]
## EXPLANATION OF THE ISSUE

I have a shipping method that uses a custom field type on its settings form, whereby the rendered form elements are "array-style", e.g. 

```
<input type="text" name="woocommerce_woo_ps_qty_layers[]" size="2">
<input type="text" name="woocommerce_woo_ps_qty_layers[]" size="2">
<input type="text" name="woocommerce_woo_ps_qty_layers[]" size="2">
```

If I only register support for 'instance-settings', then everything works as expected. I'm able to grab all of the submitted values in a validate handler. If I register support for 'instance-settings-modal' then the data isn't accessible.

Specific example, when not using the modal, ```$this->get_post_data()``` for a set of 3 input boxes with the values 1, 3 and 5 returns the following (trimmed down to just this field):
```
Array
(
    [woocommerce_woo_ps_qty_layers] => Array
        (
            [0] => 1
            [1] => 3
            [2] => 5
        )
)
```

When using the modal, for the same form input, ```$this->get_post_data()``` returns the following:

```
Array
(
    [woocommerce_woo_ps_qty_layers[] => 5
)
```

This has two issues: 

- Two of the values have been lost
- The key name is incorrect. Instead of ```woocommerce_woo_ps_qty_layers```, it's ```woocommerce_woo_ps_qty_layers[``` with a trailing **[**

I'm aware this is fairly non-standard, so before I spend time trying to pair my code back to a minimal test case, can you advise if you think that this *should* work? If so, I'll try and knock together a simple test case that shows the issue (if the cause isn't obvious). Maybe related to issue #9329 ?

**Comment by mikejolley** [comment]
Would this be backbone-modal.js:

```
getFormData: function() {
			var data = {};

			$( document.body ).trigger( 'wc_backbone_modal_before_update', this._target );

			$.each( $( 'form', this.$el ).serializeArray(), function( index, item ) {
				if ( data.hasOwnProperty( item.name ) ) {
					data[ item.name ] = $.makeArray( data[ item.name ] );
					data[ item.name ].push( item.value );
				} else {
					data[ item.name ] = item.value;
				}
			});

			return data;
		},
```

Core doesn't use inputs like this, so that would be why it's not been noticed I guess.

**Comment by leewillis77** [comment]
Maybe, although I think it's possible wherever the POST data is unpacked on the PHP side. The data that is posted looks sensible bar some "extra" brackets:

```
data[woocommerce_woo_ps_qty_layers[]][]:1
data[woocommerce_woo_ps_qty_layers[]][]:3
data[woocommerce_woo_ps_qty_layers[]][]:5
```

**Comment by leewillis77** [comment]
Just confirming that the proposed change resolves this for me - thanks Mike!

**Comment by bobbingwide** [comment]
I hadn't noticed the spare open bracket until I re-read Lee's problem explanation.
