### ISSUE TITLE
Please implement a query cache for WC_Shortcodes

### ISSUE THREAD

**Issue by Biont** [woothemes/woocommerce#11708]
I have noticed an immense performance bottleneck with the shortcodes [*featured_products*](https://github.com/woothemes/woocommerce/blob/e99798f16e9bcb94c27eb14c7359fcf5ca741a50/includes/class-wc-shortcodes.php#L620-L649) and [*best_selling_products*](https://github.com/woothemes/woocommerce/blob/e99798f16e9bcb94c27eb14c7359fcf5ca741a50/includes/class-wc-shortcodes.php#L554-L575) on a client's shop (with a couple 10.000 products) 

Both shortcodes run an expensive Meta Query, which evidently does not scale well at all.
I would argue that the results of both queries could easily be cached in a transient to speed things up considerably on subsequent requests.

PS: I have not checked if there are more shortcodes affected by this, these were the main offenders in my Cachegrind investigation. Maybe there are more candidates for caching here

**Comment by mikejolley** [comment]
Why would we need additonal caching layers here when you can implement page caching?

**Comment by Biont** [comment]
Well, I would consider pache caching to be the _additional_ layer here, that would help shadowing an observable and measurable performance bottleneck, but certainly not **solve** it.

Also depending on the traffic and site structure, the page cache can be a lot more dynamic than a more or less fixed selection of featured posts, meaning the cache would have to be flushed a lot more often and for a large number of reasons (including completely arbitrary ones).
Meanwhile, caches for featured and best selling products would only need to be flushed for saving products and completing orders and could otherwise be kept for all eternity. Isn't that an objectively better solution?

We're talking about ~4 seconds to load a page here. Please consider the possibility that this issue can be fixed on your side.

**Comment by Biont** [comment]
I can't dictate the actual implementation, but why not cache the product IDs returned by the expensive query?

After all, the resulting output may differ each time the shortcode is called, since a complete product loop is started each time. So caching HTML is completely out of the question
