### ISSUE TITLE
[2.7] On checkout user rights will  be deleted 

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11713]
## EXPLANATION OF THE ISSUE

User roles will be deleted after placing a order (checkout).

## STEPS TO REPRODUCE THE ISSUE

- Use WordPress 4.6 Multisite
- Use WooComemrce master branch
- Use a superadmin with administrator rolle on the site
- Do a checkout on frontpage
- After placing the order the user has no longer Administrator rolle (for all sites!) and will be loggt off.

The user meta fields with the capebilities do not longer exsits.

**Comment by mikejolley** [comment]
Think you may be out of sync - was fixed already https://github.com/woothemes/woocommerce/commit/c7ae2c31ea8a2dee244c97a2e2ad3f22f97141ce
