### ISSUE TITLE
Top Rated Widget missing filter

### ISSUE THREAD

**Issue by reefki** [woothemes/woocommerce#11712]
I noticed that on the Top Rated Widget there is no filter to modify the list wrapper like on Product Widget:

```
echo apply_filters( 'woocommerce_before_widget_product_list', '<ul class="product_list_widget">' );
    ....
echo apply_filters( 'woocommerce_after_widget_product_list', '</ul>' );
```

**Comment by arshidkv12** [comment]
I am seeing filter in https://github.com/woothemes/woocommerce/blob/master/includes/widgets/class-wc-widget-top-rated-products.php

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/includes/widgets/class-wc-widget-top-rated-products.php#L84

**Comment by reefki** [comment]
@mikejolley @arshidkv12 I am using version 2.6.4 installed from WP Admin, I think this is the latest version there. Here is what I have:

![screen shot 2016-08-18 at 12 25 30 am](https://cloud.githubusercontent.com/assets/10998084/17746459/54b0ec1e-64da-11e6-9ded-1e75cd7936ba.png)

**Comment by Infolu** [comment]
Hello @reefki create A que Action modify As the filter
`
echo apply_filters( 'woocommerce_before_widget_product_list', '<ul class="product_list_widget">' );
    ....
echo apply_filters( 'woocommerce_after_widget_product_list', '</ul>' );
`
per ( div )
`
echo apply_filters( 'woocommerce_before_widget_product_list', '<div class="product_list_widget">' );
    ....
echo apply_filters( 'woocommerce_after_widget_product_list', '</div>' );
`
tranks
