### ISSUE TITLE
Sorting by average rating duplicates code and doesn't actually sort

### ISSUE THREAD

**Issue by cindyward1** [woothemes/woocommerce#11711]
This problem is occurring using WooCommerce 2.6.4 and WordPress 4.5.3

Most of my products do not have any ratings at all. When I attempt to sort by average rating, all of the products are still in post_date order, and the few average ratings present appear to be ignored. I thought maybe the problem was due to my large number of products without ratings, so I temporarily changed includes/class-wc-query.php to not select the products without ratings (by eliminating the 'OR $wpdb->commentmeta.meta_key IS null' clause on $args['where']). But even just the rated products were still in post_date order without regard to average rating.

So I greatly simplified the order_by_rating_post_clauses function as shown below and added a meta_key to the case statement in the get_catalog_ordering_args function, and now everything selects and sorts perfectly even with lots of products without ratings. My changes are in italics:

public function get_catalog_ordering_args( $orderby = '', $order = '' ) {
...
case 'rating' :
    *$args['meta_key'] = '_wc_average_rating';*
    // Sorting handled later though a hook
    add_filter( 'posts_clauses', array( $this, 'order_by_rating_post_clauses' ) );
    break;
...

	/**
	 * Order by rating post clauses.
	 *
	 * @access public
	 * @param array $args
	 * @return array
	 */
	public function order_by_rating_post_clauses( $args ) {
		global $wpdb;
		$args['orderby'] = "$wpdb->postmeta.meta_value DESC, $wpdb->posts.post_date DESC";
		$args['groupby'] = "$wpdb->posts.ID";
		return $args;
	}

In the process of getting this code to work, I eliminated the following code with lots of complicated SQL joins:

*// $args['fields'] .= ", AVG( $wpdb->commentmeta.meta_value ) as average_rating ";
// $args['where']  .= " AND ( $wpdb->commentmeta.meta_key = 'rating') OR $wpdb->commentmeta.meta_key IS null ) ";
// $args['join']   .= "
//	LEFT OUTER JOIN $wpdb->comments ON($wpdb->posts.ID = $wpdb->comments.comment_post_ID)
//	LEFT JOIN $wpdb->commentmeta ON($wpdb->comments.comment_ID = $wpdb->commentmeta.comment_id)
// ";*

I don't understand why the order_by_rating_post_clauses function is recalculating the average rating from the ratings in the comments when this information lives and is appropriately maintained in the product post's _wc_average_rating metadata. It seems like the order_by_rating_post_clauses code is unnecessarily repeating functionality that is working correctly elsewhere and doesn't work correctly anyway.

**Comment by mikejolley** [comment]
The meta didn't exist in previous versions. I'll see if it can be refactored.
