### ISSUE TITLE
Fatal error: Class 'WC_Gateway_Paypal' not found 

### ISSUE THREAD

**Issue by jeefo88** [woothemes/woocommerce#11719]
Woocommerce 2.6.4
Using php 5.5

While navigating to following URLs
/wp-admin/admin.php?page=wc-settings
/checkout/

 I got following error:

Fatal error: Class 'WC_Gateway_Paypal' not found in /home/u629145876/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 91

### WordPress Environment ###

Home URL: http://avtosvet.kharkov.ua
Site URL: http://avtosvet.kharkov.ua
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.21
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (7) ###

Feature On Homepage: от Matt Royal – 1.0.0
Hyper Cache: от Stefano Lissa – 3.2.6
Keyword Meta: от appleuser – 1.0.2
PayPal Advanced for Woo: от wpremiumdev – 1.0.1
WooCommerce - All in One SEO Pack: от Visser Labs – 1.3.4
WooCommerce Customizer: от SkyVerge – 2.3.1
WooCommerce: от WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: UAH (₴)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Ссылка магазина: #27 - /
Корзина: #29 - /cart/
Оформление заказа: #31 - /checkout/
Мой аккаунт: #33 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Azera Shop
Version: 1.0.14
Author URL: http://themeisle.com/
Child Theme: ❌ – Если вы модифицируете элементы WooCommerce в теме WordPress
которую вы не разрабатывали самостоятельно
рекомендуется использовать дочернюю тему. Читайте: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Alarm bells: PayPal Advanced for Woo: от wpremiumdev – 1.0.1

Test with other extensions off before reporting issues, or use the forums. This is not a bug - it would affect all users.

If the notice still appears after turning other things off, reupload the woocommerce files in case the class file is missing on your server.

**Comment by jeefo88** [comment]
All plugins are turned off, I deleted them now though. I re-uploaded payments files @mikejolley

**Comment by mikejolley** [comment]
They were not when you ran the above report.
