### ISSUE TITLE
Post codes with a dash incorrectly displayed in the admin area

### ISSUE THREAD

**Issue by SukcesStrony** [woothemes/woocommerce#11727]
## EXPLANATION OF THE ISSUE

When checking out the order and providing a post code with a dash (like 32-020), it is then displayed in the Orders and in viewing the particular order in the admin panel without the dash (so 32020). Please try to reproduce the issue.

## CAUSE AND FIXING

The likely (but not confirmed) cause is a fix #11359, which stripped the dashes in particular situations. WC is saving the post code to the database with the dashes already stripped (confirmed). If #11359 is indeed the reason for saving stripped values to the db, you might not need to use `wc_make_numeric_postcode( $postcode )` - unless there's a reason (and maybe that reason can be worked around).

This issue is likely to affect postal codes with spaces, which #11359 also addressed.

**Comment by claudiosmweb** [comment]
The changes from #11359 remove when try to test against shipping zones.
We don't have any kind of "sanitization" for it in the admin.
I just tested and works as always:

![screenshot from 2016-08-19 20-11-05](https://cloud.githubusercontent.com/assets/1264099/17826632/1d89dfaa-6649-11e6-8833-dffff336699e.png)
![screenshot from 2016-08-19 20-11-16](https://cloud.githubusercontent.com/assets/1264099/17826633/1fe8911a-6649-11e6-84d4-8480509dc349.png)


> WC is saving the post code to the database with the dashes already stripped (confirmed).

Confirmed where?
As I said, only for shipping zones, not for orders.
