### ISSUE TITLE
Autoload customers fields does not fetch info for custom fields

### ISSUE THREAD

**Issue by sarakinos** [woothemes/woocommerce#11724]
## EXPLANATION OF THE ISSUE

I've recently spoted that when creating an new order manually from the Admin Panel and selection a customer from the dropdown list, only the default billing and shipping fields are loaded.
![woocommerce_screen1](https://cloud.githubusercontent.com/assets/1629759/17805941/9499a0e2-660a-11e6-9b63-0117cb33aed4.jpg)

## STEPS TO REPRODUCE THE ISSUE
Just register a custom customer checkout field and display it on the Shop Order Page, after that loading the customer from the dropdown menu (as shown in the above picture) fetch only the default fields

## SYSTEM STATUS REPORT

Περιβάλλον WordPress
URL Αρχικής:		http://localhost/git/senseshop
Site URL:		http://localhost/git/senseshop
Έκδοση WC:		2.6.3
Εγγράψιμος Κατάλογος Αρχείου Καταγραφής:		 C:\xampp\htdocs\git\senseshop/wp-content/uploads/wc-logs/
Έκδοση WP:		4.6
WP Multisite:		–
WP Memory Limit:		256 MB
Κατάσταση Αποσφαλμάτωσης WordPress:		–
WP Cron:		
Γλώσσα:		el
Περιβάλλον Διακομιστή
Πληροφορίες Διακομιστή:		Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
Έκδοση PHP:		5.6.21
PHP Post Max Size:		512 MB
PHP Time Limit:		100000000
PHP Μέγιστες Input Vars:		10000000
cURL Version:		7.47.1, OpenSSL/1.0.2d
SUHOSIN αντικαταστήθηκε :		–
Μέγιστο Μέγεθος Μεταφόρτωσης:		512 MB
Η Προεπιλεγμένη Ζώνη Ώρας είναι UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Απομακρυσμένο Post:		
Απομακρυσμένο Get:		
Βάση Δεδομένων
Έκδοση βάσης WC:		2.6.3
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: C:\xampp\htdocs\git\senseshop/wp-content/uploads/GeoIP.dat

## POSIBLE SOLUTION

Change function on file class-wc-ajax.php
`get_customer_details() `

Replace the hardcoded customer values with dynamic ones, following the fields conversion
startgin with _billing and _shipping filter the get_user_meta result and grab only the desired one depending on the $type_to_load variable.

**Comment by claudiosmweb** [comment]
This already have a filter called `woocommerce_found_customer_details`, so no need to get any arbitrary data.
And this will be improved soon with our Orders CRUD.

**Comment by sarakinos** [comment]
So the suggested solution is to use the filter to get the extra field?

**Comment by claudiosmweb** [comment]
Yes, since it's extra fields, best use the filter.
