### ISSUE TITLE
Disable double scrolling for System Status > Logs

### ISSUE THREAD

**Issue by bizzthemes** [woothemes/woocommerce#11729]
## EXPLANATION OF THE ISSUE

System Status > Logs uses double scrolling, a general page scrollbar and inline scrollbar for the log info. This is a bad UX practice, so disable the inline scrolling and only leave default page scrolling with all the log displayed by default. Not a big issue, but very annoying, when developing stuff with WooCommerce. You need to position inside the log area and then scroll.

## STEPS TO REPRODUCE THE ISSUE

Go to WooCommerce > Systems Status > Logs.  When very long log is available, double scrolling appears, one for the data in general page scrollbar.

**Comment by claudiosmweb** [comment]
Closed in favor of #11730
