### ISSUE TITLE
Checkout Payment Area: <h3>

### ISSUE THREAD

**Issue by BusinessBloomer** [woothemes/woocommerce#11720]
## EXPLANATION OF THE ISSUE

I've already done this on several websites. Not really an "issue" but a request to integrate this in the WooCommerce checkout template!

So, on the checkout, Billing has a heading "Billing Details", and so has shipping and "Your Order".

Why is there no similar heading for the payment area? I had to add this on all my websites to make the experience consistent on the checkout:

`
// ----------------------
// Add "Payments" title to checkout

add_action ('woocommerce_review_order_before_payment','add_checkout_payment_title');

function add_checkout_payment_title() {
echo '<h3>Payment Details</h3>';
}
`

Let me know if this makes sense :)

R

**Comment by mikejolley** [comment]
Similar to https://github.com/woothemes/woocommerce/issues/11655 - this won't be going into core until the checkout page is redesigned as it impacts themes.
