### ISSUE TITLE
Notices: after data updater ended, add some CSS class indicating its success

### ISSUE THREAD

**Issue by eliorivero** [woothemes/woocommerce#11722]
## EXPLANATION OF THE ISSUE

In the upcoming Jetpack built in React, we're moving the VaultPress and WooCommerce notices to an area in Jetpack dedicated to notices.
Right now, after moving the notice after data updating finished, we can only stylize it as any other notice since there's nothing indicating that it's a success message: 
<img width="741" alt="captura de pantalla 2016-08-18 a las 18 07 58" src="https://cloud.githubusercontent.com/assets/1041600/17790621/ac958848-656d-11e6-8718-2aad6f5aa6e0.png">

## DESIRED ENHANCEMENT
It would be good to have some CSS class that we can sniff and realize it's a success message so we can stylize it differently, like:
<img width="745" alt="captura de pantalla 2016-08-18 a las 18 01 22" src="https://cloud.githubusercontent.com/assets/1041600/17790641/ca25989e-656d-11e6-8179-5e7b199896aa.png">

**Comment by mikejolley** [comment]
@coderkevin for your reference too ^ Not sure if you saw that.

**Comment by coderkevin** [comment]
Interesting, @eliorivero, I'll ping you to discuss some of the work I've done for this in another project.

**Comment by eliorivero** [comment]
Thanks Mike!
