### ISSUE TITLE
Show "[Out of Stock]" beside variations in drop down

### ISSUE THREAD

**Issue by christopherpm** [woothemes/woocommerce#11738]
## EXPLANATION OF THE ISSUE

When stock control at variation is enabled, stock reaches 0 and cannot be back ordered, it would be really nice to grey out the option in the variation dropdown AND show [Out of Stock] (or some other customisable message) beside the variation.

Bear in mind that there may be multiple variations - for example t-shirts could have Male and Female variations, then various sizes for each sex too.

## STEPS TO REPRODUCE THE ISSUE

On variable products, enable stock control on each variation, and on a product, set stock level to 0 and do NOT allow backorders. Dropdown for that product should show out of stock.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.fortwilliammarathon.co.uk
Site URL: https://www.fortwilliammarathon.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (41) ###

Gravity Forms: by rocketgenius – 2.0.2.5
404 Redirection: by flippingwp.com – 1.8
Advanced Automatic Updates: by pento – 1.0.2
iThemes Security: by iThemes – 5.6.1
Bloom: by Elegant Themes – 1.1.8
AG C2O API Plugin: by Aaron Bowie – 3.1.4
Cache Enabler: by KeyCDN – 1.1.0
CDN Enabler: by KeyCDN – 1.0.3
Divi Booster: by Dan Mossop – 2.3.1
Divi Commerce: by Bolt Themes – 1.2
Duplicate Post: by Enrico Battocchi – 2.6
Elegant Themes Updater: by Elegant Themes – 1.2
EWWW Image Optimizer: by Shane Bishop – 2.9.6
Gravity Forms Divi Styling Add-On: by Divi Space – 1.2.2
Google-Maps-GPX-Viewer: by ATLsoft
Bernd Altmeier – 3.6

Gravity Forms Multilingual: by OnTheGoSystems – 1.3.11
Gravity Forms MailChimp Add-On: by rocketgenius – 3.7.3
Menu Icons: by Dzikri Aziz – 0.10.1
Monarch Plugin: by Elegant Themes – 1.3.2
Remote Medias Libraries: by Team OneCodeShop.com – 1.3.1
Revision Control: by Dion Hulse – 2.3.2
WPML Multilingual CMS: by OnTheGoSystems – 3.5.0
Smart Variations Images Pro: by David Rosendo – 3.0.7
Section Styles Manager: by Fosker Media – 1.0.1
TablePress: by Tobias Bäthge – 1.7
Test Payment Module for Woocommerce: by Sean Barton (Tortoise IT) – 1.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.18.22

Install via URL: by Michał Zagalski – 1.2
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Multilingual: by OnTheGoSystems – 3.8.5
Woocommerce Table Rate Shipping Pro: by JEM Plugins – 1.3
WooCommerce: by WooThemes – 2.6.4
Wordfence Security: by Wordfence – 6.1.14
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 3.4.2
WP Retina 2x: by Jordy Meow – 4.5.5
WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.7
WPML Media: by OnTheGoSystems – 2.1.22
WPML String Translation: by OnTheGoSystems – 2.4.0
WPML Translation Management: by OnTheGoSystems – 2.2.2
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #2356 - /shop/
Cart: #998 - /cart/
Checkout: #999 - /checkout/
My Account: #1000 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: FWM
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.7.10
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: fwm/.listing
`

**Comment by mikejolley** [comment]
We do include the option to hide the options, but showing in the dropdown is not something we can offer because if you have more than 1 attribute (e.g. size and color) those options can be used by multiple variations.
