### ISSUE TITLE
When adding Products --categories attribute will only accept Category id (not name)

### ISSUE THREAD

**Issue by glenncogar** [woothemes/woocommerce#11735]
## EXPLANATION OF THE ISSUE

When I use the wp wc product create ... command the --categories attribute will only accept Category ids not names of Categories

## STEPS TO REPRODUCE THE ISSUE

I tried wp wc product create --title="<some title>" ... --categories="<name of category>" ... but it did not work.  It only added the proper category when I triedwp wc product create --title="<some title>" ... --categories=<id of category>

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.mncof.com.au.dev
Site URL: http://www.mncof.com.au.dev
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.5.24 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: ❌ 5.5.24 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.30.0
OpenSSL/1.0.1m

SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (16) ###

Builder Contact: by Themify – 1.1.2
Builder Tiles: by Themify – 1.2.3
Builder WooCommerce: by Themify – 1.1.4
Google Analytics +: by WPMU DEV – 3.1.5.1
Snapshot: by WPMU DEV – 2.5.0.1
Themify Portfolio Post: by Themify – 1.0.4
Woocommerce Catalog Enquiry: by Dualcube – 2.3.1
Woocommerce CSV import attributes: by Allaerd Mensonides – 3.0.1
Woocommerce CSV import custom fields: by Allaerd Mensonides – 3.0.1
Woocommerce CSV import downloadable, external, grouped products: by Allaerd Mensonides – 3.0.1
Woocommerce CSV import variable products: by Allaerd Mensonides – 3.0.1
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.0
WooCommerce: by WooThemes – 2.6.4
WP Super Cache: by Automattic – 1.4.8
SmartCrawl: by WPMU DEV – 1.7.7
WPMU DEV Dashboard: by WPMU DEV – 4.1.2

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1509 - /shop/
Basket: #1511 - /basket/
Checkout: #1513 - /checkout/
My Account: #1515 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: ultra-child
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Themify Ultra
Parent Theme Version: 1.4.8
Parent Theme Author URL: http://www.themify.me
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
That's is the idea, allow only category IDs.
After #11611 will be possible to create categories with CLI too.
