### ISSUE TITLE
Updating variation has no effect on stock_quantity and other params

### ISSUE THREAD

**Issue by Gutenisse** [woothemes/woocommerce#11736]
## EXPLANATION OF THE ISSUE

Trying to update variation stock_quantity using PUT on endpoint "products/ID" has no effect. Neither does price and other params, but stock_quantity is my primary issue.

Updating the weight does, however, work.

All products are added using REST API and everything seems to work as it should with correct stock quantities etc. 
Main product has different SKU than variation. The variations has "-x" added after the SKU where "x" is 1, 2, 3 etc. for each iteration. Main product SKU = 123456 and the variation products then has 123456-1, 123456-2 etc.

I also have the issue that the price disappears when using this endpoint, but if manually updating the post from the Admin GUI, it will reappear.   

## STEPS TO REPRODUCE THE ISSUE

Using the following code to update variations products with unique SKU

$data =
[
    "weight" => "10",
    "stock_quantity" => 12
];

$response = $this->woocommerce->put("products/$id", $data);

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

WC Version: 2.6.4

WP Version: 4.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.23-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (1) ###

WooCommerce: av WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: SEK (kr)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikbas: #4 - /shop/
Varukorg: #5 - /cart/
Kassan: #6 - /checkout/
Mitt konto: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –
````

**Comment by mikejolley** [comment]
You'd need to provide the request result so I can see all other data; looking at and testing the code via my client works but only if `manage_stock` is true. If that is false, your change will be ignored. Hopefully thats it  :)

**Comment by Gutenisse** [comment]
Thanks for your reply, @mikejolley !

The following is the request for creating a variable product with it's variations. Sorry for the wall of text, but I don't want to remove anything in case that would screw things up :flushed:

## Request

`
Array
(
    [name] => Kängor herr
    [description] => Kängor herr
    [short_description] => Kängor herr
    [type] => variable
    [sku] => 620916
    [manage_stock] => 
    [categories] => Array
        (
            [0] => Array
                (
                    [id] => 2680
                )

            [1] => Array
                (
                    [id] => 2681
                )

        )

    [attributes] => Array
        (
            [0] => Array
                (
                    [id] => 85
                    [name] => Storlek
                    [position] => 0
                    [visible] => 1
                    [variation] => 1
                    [options] => Array
                        (
                            [0] => 39
                            [1] => 40
                            [2] => 41
                            [3] => 42
                            [4] => 43
                            [5] => 44
                            [6] => 45
                            [7] => 46
                            [8] => 47
                            [9] => 48
                        )

                )

        )

    [images] => Array
        (
            [0] => Array
                (
                    [src] => http://xxxxxx.xx/images/162_divi_crasher 14000.jpg
                    [name] => 620916
                    [position] => 0
                )

        )

    [variations] => Array
        (
            [0] => Array
                (
                    [sku] => 620916-1
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 4
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 39
                                )

                        )

                )

            [1] => Array
                (
                    [sku] => 620916-2
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 5
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 40
                                )

                        )

                )

            [2] => Array
                (
                    [sku] => 620916-3
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 4
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 41
                                )

                        )

                )

            [3] => Array
                (
                    [sku] => 620916-4
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 8
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 42
                                )

                        )

                )

            [4] => Array
                (
                    [sku] => 620916-5
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 3
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 43
                                )

                        )

                )

            [5] => Array
                (
                    [sku] => 620916-6
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 2
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 44
                                )

                        )

                )

            [6] => Array
                (
                    [sku] => 620916-7
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 1
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 45
                                )

                        )

                )

            [7] => Array
                (
                    [sku] => 620916-8
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 46
                                )

                        )

                )

            [8] => Array
                (
                    [sku] => 620916-9
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 47
                                )

                        )

                )

            [9] => Array
                (
                    [sku] => 620916-10
                    [name] => Kängor herr
                    [regular_price] => 1299.0000
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 48
                                )

                        )

                )

        )

)
`

## The response is as follows:

`Array
(
    [id] => 5993
    [name] => Kängor herr
    [slug] => kangor-herr
    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/
    [date_created] => 2016-08-24T06:44:27
    [date_modified] => 2016-08-24T06:44:27
    [type] => variable
    [status] => publish
    [featured] => 
    [catalog_visibility] => visible
    [description] => <p>Kängor herr</p>

    [short_description] => <p>Kängor herr</p>

    [sku] => 620916
    [price] => 1299.0000
    [regular_price] => 
    [sale_price] => 
    [date_on_sale_from] => 
    [date_on_sale_to] => 
    [price_html] => <span class="woocommerce-Price-amount amount">1.299,00<span class="woocommerce-Price-currencySymbol">&#107;&#114;</span></span>
    [on_sale] => 
    [purchasable] => 1
    [total_sales] => 0
    [virtual] => 
    [downloadable] => 
    [downloads] => Array
        (
        )

    [download_limit] => -1
    [download_expiry] => -1
    [download_type] => standard
    [external_url] => 
    [button_text] => 
    [tax_status] => taxable
    [tax_class] => 
    [manage_stock] => 
    [stock_quantity] => 
    [in_stock] => 1
    [backorders] => no
    [backorders_allowed] => 
    [backordered] => 
    [sold_individually] => 
    [weight] => 
    [dimensions] => Array
        (
            [length] => 
            [width] => 
            [height] => 
        )

    [shipping_required] => 1
    [shipping_taxable] => 1
    [shipping_class] => 
    [shipping_class_id] => 0
    [reviews_allowed] => 1
    [average_rating] => 0.00
    [rating_count] => 0
    [related_ids] => Array
        (
        )

    [upsell_ids] => Array
        (
        )

    [cross_sell_ids] => Array
        (
        )

    [parent_id] => 0
    [purchase_note] => 
    [categories] => Array
        (
            [0] => Array
                (
                    [id] => 2680
                    [name] => Herr
                    [slug] => herr
                )

            [1] => Array
                (
                    [id] => 2681
                    [name] => Kängor &amp; Boots
                    [slug] => herr-kangor-boots
                )

        )

    [tags] => Array
        (
        )

    [images] => Array
        (
            [0] => Array
                (
                    [id] => 5994
                    [date_created] => 2016-08-24T06:44:27
                    [date_modified] => 2016-08-24T06:44:27
                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                    [name] => 620916
                    [alt] => 
                    [position] => 0
                )

        )

    [attributes] => Array
        (
            [0] => Array
                (
                    [id] => 85
                    [name] => Storlek
                    [position] => 0
                    [visible] => 1
                    [variation] => 1
                    [options] => Array
                        (
                            [0] => 39
                            [1] => 40
                            [2] => 41
                            [3] => 42
                            [4] => 43
                            [5] => 44
                            [6] => 45
                            [7] => 46
                            [8] => 47
                            [9] => 48
                        )

                )

        )

    [default_attributes] => Array
        (
        )

    [variations] => Array
        (
            [0] => Array
                (
                    [id] => 5995
                    [date_created] => 2016-08-24T06:44:29
                    [date_modified] => 2016-08-24T06:44:29
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=39
                    [sku] => 620916-1
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 4
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 39
                                )

                        )

                )

            [1] => Array
                (
                    [id] => 5996
                    [date_created] => 2016-08-24T06:44:30
                    [date_modified] => 2016-08-24T06:44:30
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=40
                    [sku] => 620916-2
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 5
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 40
                                )

                        )

                )

            [2] => Array
                (
                    [id] => 5997
                    [date_created] => 2016-08-24T06:44:31
                    [date_modified] => 2016-08-24T06:44:31
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=41
                    [sku] => 620916-3
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 4
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 41
                                )

                        )

                )

            [3] => Array
                (
                    [id] => 5998
                    [date_created] => 2016-08-24T06:44:32
                    [date_modified] => 2016-08-24T06:44:32
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=42
                    [sku] => 620916-4
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 8
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 42
                                )

                        )

                )

            [4] => Array
                (
                    [id] => 5999
                    [date_created] => 2016-08-24T06:44:33
                    [date_modified] => 2016-08-24T06:44:33
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=43
                    [sku] => 620916-5
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 3
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 43
                                )

                        )

                )

            [5] => Array
                (
                    [id] => 6000
                    [date_created] => 2016-08-24T06:44:34
                    [date_modified] => 2016-08-24T06:44:34
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=44
                    [sku] => 620916-6
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 2
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 44
                                )

                        )

                )

            [6] => Array
                (
                    [id] => 6001
                    [date_created] => 2016-08-24T06:44:35
                    [date_modified] => 2016-08-24T06:44:35
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=45
                    [sku] => 620916-7
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 1
                    [in_stock] => 1
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 45
                                )

                        )

                )

            [7] => Array
                (
                    [id] => 6002
                    [date_created] => 2016-08-24T06:44:36
                    [date_modified] => 2016-08-24T06:44:36
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=46
                    [sku] => 620916-8
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [in_stock] => 
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 46
                                )

                        )

                )

            [8] => Array
                (
                    [id] => 6003
                    [date_created] => 2016-08-24T06:44:37
                    [date_modified] => 2016-08-24T06:44:37
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=47
                    [sku] => 620916-9
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [in_stock] => 
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 47
                                )

                        )

                )

            [9] => Array
                (
                    [id] => 6004
                    [date_created] => 2016-08-24T06:44:38
                    [date_modified] => 2016-08-24T06:44:38
                    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=48
                    [sku] => 620916-10
                    [price] => 1299.0000
                    [regular_price] => 1299.0000
                    [sale_price] => 
                    [date_on_sale_from] => 
                    [date_on_sale_to] => 
                    [on_sale] => 
                    [purchasable] => 1
                    [visible] => 1
                    [virtual] => 
                    [downloadable] => 
                    [downloads] => Array
                        (
                        )

                    [download_limit] => -1
                    [download_expiry] => -1
                    [tax_status] => taxable
                    [tax_class] => 
                    [manage_stock] => 1
                    [stock_quantity] => 0
                    [in_stock] => 
                    [backorders] => no
                    [backorders_allowed] => 
                    [backordered] => 
                    [weight] => 
                    [dimensions] => Array
                        (
                            [length] => 
                            [width] => 
                            [height] => 
                        )

                    [shipping_class] => 
                    [shipping_class_id] => 0
                    [image] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 5994
                                    [date_created] => 2016-08-24T06:44:27
                                    [date_modified] => 2016-08-24T06:44:27
                                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                                    [name] => 620916
                                    [alt] => 
                                    [position] => 0
                                )

                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 85
                                    [name] => Storlek
                                    [option] => 48
                                )

                        )

                )

        )

    [grouped_products] => Array
        (
        )

    [menu_order] => 0
    [_links] => Array
        (
            [self] => Array
                (
                    [0] => Array
                        (
                            [href] => http://xxxxxx.xx/wp-json/wc/v1/products/5993
                        )

                )

            [collection] => Array
                (
                    [0] => Array
                        (
                            [href] => http://xxxxxx.xx/wp-json/wc/v1/products
                        )

                )

        )

)`

**Comment by mikejolley** [comment]
Which ID were you editing stock on?

**Comment by Gutenisse** [comment]
I tried all of them but the only result is that the main products price disappears.

**Comment by mikejolley** [comment]
> Updating variation has no effect on stock_quantity

Your report said the values for qty does not update. Which ID are you updating from above so I don't have to compare the long list for changes.

**Comment by Gutenisse** [comment]
I'm sorry, but the request and responses above is from when I created the products.

Then, when I try to update I send and get the following data.

## Request
`		$data =
			[
				"stock_quantity" => 5
			];
		
		$response = $this->woocommerce->put("products/5995", $data);
`

## Response

`
Array
(
    [id] => 5995
    [name] => Kängor herr
    [slug] => kangor-herr
    [permalink] => http://xxxxxx.xx/produkt/kangor-herr/?attribute_pa_h1=39
    [date_created] => 2016-08-24T06:44:27
    [date_modified] => 2016-08-24T06:44:27
    [type] => variation
    [status] => publish
    [featured] => 
    [catalog_visibility] => visible
    [description] => <p>Kängor herr</p>

    [short_description] => <p>Kängor herr</p>

    [sku] => 620916-1
    [price] => 1299.0000
    [regular_price] => 1299.0000
    [sale_price] => 
    [date_on_sale_from] => 
    [date_on_sale_to] => 
    [price_html] => <span class="woocommerce-Price-amount amount">1.299,00<span class="woocommerce-Price-currencySymbol">&#107;&#114;</span></span>
    [on_sale] => 
    [purchasable] => 1
    [total_sales] => 0
    [virtual] => 
    [downloadable] => 
    [downloads] => Array
        (
        )

    [download_limit] => -1
    [download_expiry] => -1
    [download_type] => standard
    [external_url] => 
    [button_text] => 
    [tax_status] => taxable
    [tax_class] => 
    [manage_stock] => 1
    [stock_quantity] => 12
    [in_stock] => 1
    [backorders] => no
    [backorders_allowed] => 
    [backordered] => 
    [sold_individually] => 
    [weight] => 
    [dimensions] => Array
        (
            [length] => 
            [width] => 
            [height] => 
        )

    [shipping_required] => 1
    [shipping_taxable] => 1
    [shipping_class] => 
    [shipping_class_id] => 0
    [reviews_allowed] => 1
    [average_rating] => 0.00
    [rating_count] => 0
    [related_ids] => Array
        (
        )

    [upsell_ids] => Array
        (
        )

    [cross_sell_ids] => Array
        (
        )

    [parent_id] => 5993
    [purchase_note] => 
    [categories] => Array
        (
            [0] => Array
                (
                    [id] => 2680
                    [name] => Herr
                    [slug] => herr
                )

            [1] => Array
                (
                    [id] => 2681
                    [name] => Kängor &amp; Boots
                    [slug] => herr-kangor-boots
                )

        )

    [tags] => Array
        (
        )

    [images] => Array
        (
            [0] => Array
                (
                    [id] => 5994
                    [date_created] => 2016-08-24T06:44:27
                    [date_modified] => 2016-08-24T06:44:27
                    [src] => http://xxxxxx.xx/wp-content/uploads/2016/08/162_divi_crasher2014000-19.jpg
                    [name] => 620916
                    [alt] => 
                    [position] => 0
                )

        )

    [attributes] => Array
        (
            [0] => Array
                (
                    [id] => 85
                    [name] => Storlek
                    [option] => 39
                )

        )

    [default_attributes] => Array
        (
        )

    [variations] => Array
        (
        )

    [grouped_products] => Array
        (
        )

    [menu_order] => 0
    [_links] => Array
        (
            [self] => Array
                (
                    [0] => Array
                        (
                            [href] => http://xxxxxx.xx/wp-json/wc/v1/products/5993
                        )

                )

            [collection] => Array
                (
                    [0] => Array
                        (
                            [href] => http://xxxxxx.xx/wp-json/wc/v1/products
                        )

                )

            [up] => Array
                (
                    [0] => Array
                        (
                            [href] => http://xxxxxx.xx/wp-json/wc/v1/products/5993
                        )

                )

        )

)
`

**Comment by mikejolley** [comment]
Replying here https://github.com/woocommerce/woocommerce/issues/12201
