### ISSUE TITLE
Display customers email in email header

### ISSUE THREAD

**Issue by jordanESsystems** [woothemes/woocommerce#11742]
## EXPLANATION OF THE ISSUE

I'm using WP version 4.6 with the latest available version of WooCommerce 2.6.4.

I want to be able to pull the customers email address into the heading of an incoming completed or new order email that admin receive. Is this possible?

![image](https://cloud.githubusercontent.com/assets/14834837/17857407/89c5a000-6879-11e6-8f6e-1f0d65b5b03b.png)

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://downatthefarm.co.uk
Site URL: http://downatthefarm.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.7 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 500 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.41 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (13) ###

Gravity Forms: by rocketgenius – 2.0.6
BackWPup: by Inpsyde GmbH – 3.3.4
FunFarm Functions: by  –
Gravity Forms - Placeholders add-on: by Joan Piedra – 1.2.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.2

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
ThemeLoom Widgets: by Tim Hyde – 1.8.2
WooCommerce Bookings: by WooThemes – 1.9.10
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.5.3
WooCommerce Product Add-ons: by Automattic – 2.7.22
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.0

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop Base: #823 - /shop/
Cart: #824 - /cart/
Checkout: #825 - /checkout/
My Account: #826 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: funfarm
Version: 1.0
Author URL: http://underscores.me/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: animal-farm/woocommerce/checkout/thankyou.php
`

**Comment by mikejolley** [comment]
Yes, templates can be customised via template files or hooks https://docs.woocommerce.com/document/template-structure/

We don't provide customisations here however; Github is for bug reports which this is not.
