### ISSUE TITLE
Woocommerce - Payment method not switching.

### ISSUE THREAD

**Issue by basserd** [woothemes/woocommerce#11740]
## EXPLANATION OF THE ISSUE
Where: On the checkout page, where the payment method could be selected.
When: When the payment method is selected.
Expectation: I was expecting that the payment method would change to whatever I selected but it kept going to the first option. 

## STEPS TO REPRODUCE THE ISSUE
- I cannot reproduce the problem because the problem occurred because of a problem in checkout.js 

## WHAT I DID TO SOLVE THE PROBLEM
Changed the first line (line1) in checkout.min.js to line(line2). The reason I did this was because when I printed the **wc_checkout_form.$order_review.find( 'input[name="payment_method"]:checked' ).val()** I Constantly got the old value which was the first available value in the payment methods. When I changed this to **$('input[name="payment_method"]:checked').val();** I got the form value instead of the preselected value. The problem that occurred which causes the payment method to switch back to the first available option was solved.

_line1: wc_checkout_form.$order_review.find( 'input[name="payment_method"]:checked' ).val();
line2: $('input[name="payment_method"]:checked').val();_

**Comment by mikejolley** [comment]
Sounds like your theme doesn't use our div structure. Does not happen my side on default themes or storefront.

Please report to the theme author - if it needs a workaround or fix they can comment here or raise a PR.

Thanks
