### ISSUE TITLE
wrong calculation of item price in order

### ISSUE THREAD

**Issue by behrang1981** [woothemes/woocommerce#11743]
on woocommerce 2.6.4 on wordpress 4.5:

When viewing an order (admin/order details) i notice wrong calculation of the price.
product costs 50,37 (excl. tax, 53,90 including 7% tax) we have 2 of it in the order
and sum is 100,75 instead of 100,74

when editing the item i see 100,7477 which is rounded to 100,75.

imo this is not right.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.bahn-fachverlag.de
Site URL: https://www.bahn-fachverlag.de
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.19 - Wir empfehlen eine PHP-Version von mindestenstens 5.6. Siehe: Wie Sie Ihre PHP-Version updaten können:
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 20000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.50 – Wir empfehlen mindestens die MySQL Version 5.6. Mehr dazu: WordPress-Anforderungen
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (51) ###

Advanced Custom Fields: Repeater Field: von Elliot Condon – 1.1.1
Adminer: von Frank Bültge – 1.4.5
Advanced Custom Fields PRO: von Elliot Condon – 5.3.10
BackWPup: von Inpsyde GmbH – 3.3.3
BFV CA Banner: von Code Alliance – 2.0
iThemes Security: von iThemes – 5.6.0
Breadcrumb NavXT: von John Havlik – 5.4.0
Contact Form DB: von Michael Simpson – 2.10.20
Contact Form 7: von Takayuki Miyoshi – 4.5
Display Widgets: von Strategy11 – 2.05
BFV CA Empfehlung: von Code Alliance – 1.0
EU Cookie Law: von Alex Moss
Marco Milesi
Peadig
Shane Jones – 2.9.3

Events Manager and WPML Compatibility: von Marcus Sykes – 1.0.1
Events Manager: von Marcus Sykes – 5.6.5
Heroic Favicon Generator: von Hero Themes – 1.4.2
Google Analytics: von Kevin Sylvestre – 1.0.6
Meta Slider: von Matcha Labs – 3.3.7
Multilingual Tools: von WPML Compatibility Team – 1.2
No CAPTCHA reCAPTCHA for WooCommerce: von Agbonghama Collins – 1.2
oik Weight/Country Shipping: von bobbingwide – 1.3.2
PAYMILL GmbH: von Matthias Reuter info@straightvisions.com – 1.10.9
PayPal for WooCommerce: von Angell EYE – 1.2.3
WooCommerce Product Filter: von Mihajlovic Nenad – 5.8.3
BFV CA Programm: von Code Alliance – 1
Umleitungen: von John Godley – 2.4.5
Vorschaubilder regenerieren: von Alex Mills (Viper007Bond) – 2.2.6
WPML Multilingual CMS: von OnTheGoSystems – 3.4.1.1
Toolset Types: von OnTheGoSystems – 2.1
Vendidero Helper: von Vendidero – 1.1.1
Woo Preview Emails: von Digamber Pradhan – 1.1.2
WooCommerce Checkout Field Editor: von WooThemes – 1.4.10 – 1.5.0 ist verfügbar
WooCommerce Coupons By Location: von Store Apps – 1.2.6
WooCommerce Gateways Country Limiter: von OnTheGoSystems – 1.3
WooCommerce Germanized Pro: von Vendidero – 1.5.3
WooCommerce Germanized: von Vendidero – 1.6.8
WooCommerce Multilingual: von OnTheGoSystems – 3.8.4
WooCommerce PDF Watermark: von WooThemes – 1.0.4
Woocommerce Products Per Page: von Jeroen Sormani – 1.2.2
SOFORT Banking for WooCommerce: von Awesome UG & MarketPress – 1.1.18
WooWaitlist: von WPCream.com – 3.0.10
WooCommerce: von WooThemes – 2.6.4
WooCommerce Helper: von WooCommerce – 1.7.0
Yoast SEO: von Team Yoast – 3.4.2
WPML CMS Nav: von OnTheGoSystems – 1.4.19
WPML Media: von OnTheGoSystems – 2.1.22
WPML Sticky Links: von OnTheGoSystems – 1.3.19
WPML String Translation: von OnTheGoSystems – 2.3.9
WPML Translation Management: von OnTheGoSystems – 2.2.1.2
YITH WooCommerce Customize My Account Page: von YITHEMES – 1.1.0
YITH WooCommerce Quick View: von YITHEMES – 1.1.2
YITH WooCommerce Wishlist Premium: von YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #23 - /shop/
Warenkorb: #304 - /shop/warenkorb/
Kasse: #305 - /shop/kasse/
Mein Konto: #306 - /shop/mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: _tk
Version: 1.1.10
Author URL: http://www.code-alliance.de/
Child Theme: ❌ – Wenn Sie WooCommerce oder ein Parent Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie Sie ein Child Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: _tk-master/woocommerce/emails/admin-cancelled-order.php
_tk-master/woocommerce/emails/admin-failed-order.php
_tk-master/woocommerce/emails/admin-new-order.php
_tk-master/woocommerce/emails/customer-completed-order.php
_tk-master/woocommerce/emails/customer-invoice.php
_tk-master/woocommerce/emails/customer-new-account.php
_tk-master/woocommerce/emails/customer-note.php
_tk-master/woocommerce/emails/customer-on-hold-order.php
_tk-master/woocommerce/emails/customer-processing-order.php
_tk-master/woocommerce/emails/customer-refunded-order.php
_tk-master/woocommerce/emails/customer-reset-password.php
_tk-master/woocommerce/emails/email-addresses.php
_tk-master/woocommerce/emails/email-customer-details.php
_tk-master/woocommerce/emails/email-footer.php
_tk-master/woocommerce/emails/email-header.php
_tk-master/woocommerce/emails/email-order-details.php
_tk-master/woocommerce/emails/email-order-items.php
_tk-master/woocommerce/emails/email-styles.php
_tk-master/woocommerce/emails/plain/admin-cancelled-order.php
_tk-master/woocommerce/emails/plain/admin-failed-order.php
_tk-master/woocommerce/emails/plain/admin-new-order.php
_tk-master/woocommerce/emails/plain/customer-completed-order.php
_tk-master/woocommerce/emails/plain/customer-invoice.php
_tk-master/woocommerce/emails/plain/customer-new-account.php
_tk-master/woocommerce/emails/plain/customer-note.php
_tk-master/woocommerce/emails/plain/customer-on-hold-order.php
_tk-master/woocommerce/emails/plain/customer-processing-order.php
_tk-master/woocommerce/emails/plain/customer-refunded-order.php
_tk-master/woocommerce/emails/plain/customer-reset-password.php
_tk-master/woocommerce/emails/plain/email-addresses.php
_tk-master/woocommerce/emails/plain/email-customer-details.php
_tk-master/woocommerce/emails/plain/email-order-details.php
_tk-master/woocommerce/emails/plain/email-order-items.php
_tk-master/woocommerce/loop/add-to-cart.php Version 2.1.0 ist veraltet. Die Hauptversion ist 2.5.0

: Erfahren Sie
wie Sie veraltete Templates aktualisieren

`

**Comment by mikejolley** [comment]
Thats simply not enough information for me to work with but before replying back I suggest you read https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce so you can see what calculations are used and work that out first.

**Comment by behrang1981** [comment]
hi
well i know how tax calculation works. i don't think it's the point.
the issue is that  a product price of 50,37 when doubled can't be 100,75.

even if the final amount after tax calculation is ok  this is not right display at least:
https://ibin.co/2sSqvW2NVZWU.png
that is a screenshot from the invoice

and thats what you can see in the order edit screen
https://ibin.co/2sSrDw8BLAKQ.png
https://ibin.co/2sSrJFD0TjNa.png
greets

**Comment by mikejolley** [comment]
I'd need to know product prices and tax rates to replicate. I don't know if those values are unaltered.

**Comment by behrang1981** [comment]
product price is 53,90
tax is 7%
so net price is 50,373831775701

quantity is 2

so the price shown is 100,75 because of 2 * 50,373831775701 = 100,747663551402
and this is rounded to 100,75 because of 2 digits after comma.

but it leads to the display above:

50,37      x        2  => 100,75

**Comment by mikejolley** [comment]
The sum would be `107.8 - 107.8-(107.8/1.07)` but it would be correct to round up. It would be wrong to round down regardless.

You should use ex tax prices for products if the rounding is not suitable for your country.

**Comment by behrang1981** [comment]
ok we will check this
