### ISSUE TITLE
Select main image in variations differently

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11744]
This is the current code:
`$product_link     = $product.find( 'div.images a.zoom:eq(0)' );`

This is the new proposed code:

`$product_link     = $product.find( '.woocommerce-main-image' );`

add-to-cart-variation.js

Without this change as soon as I remove 'zoom' class and prettyPhoto to restyle this and implement another lightbox library variations stop updating the link.

I could stay with "zoom" class but this is definitely a bug to init prettyPhoto like this:

```
(function($) {
$(function() {

	// Lightbox
	$("a.zoom").prettyPhoto({
		hook: 'data-rel',
		social_tools: false,
		theme: 'pp_woocommerce',
		horizontal_padding: 20,
		opacity: 0.8,
		deeplinking: false
	});
	$("a[data-rel^='prettyPhoto']").prettyPhoto({
		hook: 'data-rel',
		social_tools: false,
		theme: 'pp_woocommerce',
		horizontal_padding: 20,
		opacity: 0.8,
		deeplinking: false
	});

});
})(jQuery);
```

Corrected code:

```
(function($) {
	$('a[data-rel="prettyPhoto"]').prettyPhoto({
		hook: 'data-rel',
		social_tools: false,
		theme: 'pp_woocommerce',
		horizontal_padding: 20,
		opacity: 0.8,
		deeplinking: false
	});
})(jQuery);
```

(I would even go with [data-prettyphoto] without any value or with a CSS class.)

My main concern is that "zoom" is used for two things and that prevented me from disabling prettyPhoto and retaining image switching on variation change.

**Comment by mikejolley** [comment]
This will cause theme breakage, so rather than 'fix' this it would be best to just wait for https://github.com/woothemes/woocommerce/issues/10721 to be implemented to avoid disruption. PrettyPhoto is being removed.

Thanks
