### ISSUE TITLE
Checkout page - hidden error message due to refresh

### ISSUE THREAD

**Issue by mattalberon** [woothemes/woocommerce#11741]
## EXPLANATION OF THE ISSUE

The checkout page refreshes when a credit card is declined; the error message is therefore not viewable because it appears at the top of the page. 

The versions are: WordPress 4.7-alpha-38304; WooCommerce 2.6.4; WooCommerce Stripe Gateway 3.0.2.

The user will not be logged in, and will use a declined credit card.

The page should scroll to the top on receiving the error, consistent with other checkout errors.

## STEPS TO REPRODUCE THE ISSUE

1. Stripe Checkout should be disabled in Settings > Checkout > Stripe
2. Add an item to the cart
3. Go to the checkout
4. Use a declined test card number aka 4000000000000002
5. Submit the checkout form
6. (optional - manually scroll to the top of the page to verify that there is an error message)

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://woocommerce-test.jericho.alberon.co.uk
Site URL: http://woocommerce-test.jericho.alberon.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.7-alpha-38304
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.19 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.50 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #102 - /shop/
Cart: #103 - /cart/
Checkout: #104 - /checkout/
My Account: #105 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Fifteen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I've gone ahead and moved this to the correct place.

https://github.com/woothemes/woocommerce-gateway-stripe/issues/49
