### ISSUE TITLE
Custom permalink without prefix, all  articles failed

### ISSUE THREAD

**Issue by colas31** [woothemes/woocommerce#11754]
## EXPLANATION OF THE ISSUE

When I set a custom permalink for product without prefix, all pages and articles respond in 404.
I guess it's a problem of rewriterule, because I can fix it with by a dirty way by adding a RewriteRule
`RewriteRule ^contact\/$ index.php?page_id=22 [L,QSA]`

But it's not very handy, mostly with lot of articles

## STEPS TO REPRODUCE THE ISSUE

1. Go in admin Settings / permalinks 
2. Set Custom Base like this "/%product_cat%"
3. Set Article base to "Name of article"
4. Create an article with url "contact"
5. This page responses in 404

**Comment by mikejolley** [comment]
This structure is non supported. There will be a fix in the upcoming release to prevent this being saved. WP cannot handle a taxonomy only base - it does not know how to handle the content.

Already implemented in master.
