### ISSUE TITLE
Refactor woocommerce_form_field function to allow modifying the markup

### ISSUE THREAD

**Issue by pixeline** [woothemes/woocommerce#11753]
Our designer has redesigned our checkout process UI and html markup, and I cannot implement his template without plugging the woocommerce_form_field() function entirely. An API that would allow for custom form layout and markup (wrapper elements).

Example of desired code:

```html
<div class="o-form__group">
	<div class="o-form__item o-form__item--half">
		<label class="o-form__label" for="firstname">
			First name
		</label>
		<input class="o-form__input o-form__input--text" type="text" id="firstname" name="firstname" placeholder="First name" autocorrect="off">
	</div>
	<div class="o-form__item o-form__item--half">
		<label class="o-form__label" for="lastname">
		        Last name
		</label>
		<input class="o-form__input o-form__input--text" type="text" id="lastname" name="lastname" placeholder="Last name" autocorrect="off">
	</div>
</div>

<span class="o-form__spacing"></span>
<div class="o-form__item o-form__item--full">
	<label class="o-form__label" for="street">
		Street address
	</label>
	<input class="o-form__input o-form__input--text" type="text" id="street" name="street" placeholder="Street address" autocorrect="off">
</div>
```
I know I can reorder the fields' order using `woocommerce_checkout_fields` and change the wrapper, input and label classes, but I can't seem to be able changing the wrapping element (currently a `p`) and decide on a wether fields should be in the same row or not.

Thank you,
Alexandre.

**Comment by mikejolley** [comment]
If you're making major markup changes to what we offer you have 2 choices;

- Override the pluggable function
- Use apply_filters to change the field markup

But then in reality, the markup we offer can be styled with CSS so such changes shouldn't even be required to implement your design.

I don't really see much benefit to allowing tag changes - thats messy and makes it harder for both ourselves and 3rd parties to support.

cc @jameskoster 

p.s. `<span class="o-form__spacing"></span>` tags for spacing? Why - use a margin.
