### ISSUE TITLE
Deleting a tax class will not delete tax rates

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11759]
If we delete a tax class in the WooCommerce settings, than the corresponding tax rates will not be deleted in the database.

In that case the Rest-API will deliver all tax rates including that with the deleted tax class.

Sorry, but i don't know is there a reason why the tax rates will not be deleted?

**Comment by ShariqKhan2012** [comment]
> If stock reduced when an item added to the cart probably small store owners will lose customers due to lack of stock

Is there a state for products/items which indicates they have been "added to cart" but not yet puchased?

If so, could we have a provision wherein if there are two customers are vying for a last piece of item, and one of them is fast to "add to cart"  but has not purchased it thereby blocking it, a message is displayed to other users notifying them that the product COULD be available if the current user abondons it..and that they could try out after <CART_EXPIRE_TIMEOUT> time?
