### ISSUE TITLE
Shipping Zones bug?

### ISSUE THREAD

**Issue by rafaschou** [woothemes/woocommerce#11761]
## EXPLANATION OF THE ISSUE

Hello, I'm running Woocommerce 2.6.4 on Wordpress 4.6. 

When Shipping Zones were introduced, I created the zones and the rules normally. Then after an update of Woocommerce, my Shipping Zones screen shows only Rest of the World, with no shipping options. The button to add a shipping option doesn't do anything, and I'm unable to add any shipping option or shipping zone. 

The funny thing is that the previous shipping options and rules, prior to Shipping Zones being introduced, are still running on the website, but I am unable to see them in the admin and edit. 

Have you guys encountered the same issue elsewhere?

Thanks

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.thefinefinder.com
Site URL: https://www.thefinefinder.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.2.22
PHP Version: ❌ 5.5.35 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (25) ###

Add Meta Tags: by George Notaras – 2.11.3
Autoptimize: by Frank Goossens (futtta) – 2.0.2
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.30
Contact Form 7: by Takayuki Miyoshi – 4.5
Cookie Notice: by dFactory – 1.2.35
Duplicate Post: by Enrico Battocchi – 2.6
GetBowtied Tools: by GetBowtied – 1.0.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
Leadin: by Leadin – 5.4.1
MailChimp for WordPress: by ibericode – 3.1.12
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.2

Popup Builder: by Sygnoos – 2.3.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.2.3.5
themesFor.me Google Product Feed for WooCommerce: by Themes For Me – 1.0.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.17

WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
Woocommerce Mailchimp Discount: by Magnigenie – 1.9.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.36
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3
WP Maintenance Mode: by Designmodo – 2.0.7
WP Super Cache: by Automattic – 1.4.8
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /jewellery/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Shopkeeper Child
Version: 1.0
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 1.6.12
Parent Theme Author URL: http://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper/woocommerce/checkout/form-billing.php
shopkeeper/woocommerce/checkout/form-checkout.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/checkout/form-shipping.php
shopkeeper/woocommerce/checkout/payment-method.php
shopkeeper/woocommerce/checkout/thankyou.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global/breadcrumb.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/loop/orderby.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper/woocommerce/single-product/add-to-cart/external.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
shopkeeper/woocommerce/single-product/add-to-cart/variable.php
shopkeeper/woocommerce/single-product/meta.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/rating.php
shopkeeper/woocommerce/single-product/related.php
shopkeeper/woocommerce/single-product/short-description.php
shopkeeper/woocommerce/single-product/tabs/additional-information.php
shopkeeper/woocommerce/single-product/tabs/description.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product/up-sells.php
shopkeeper/woocommerce/single-product-reviews.php
shopkeeper/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
No; enable WP_DEBUG and look at the screen again.

**Comment by rafaschou** [comment]
Will give it a try, hold on

**Comment by rafaschou** [comment]
I enabled WP_DEBUG, nothing changed in the Shipping Zones screen.

**Comment by mikejolley** [comment]
Screenshot it here. Also look in debug logs for anything else.

**Comment by rafaschou** [comment]
![screenshot 2016-08-24 16 32 18](https://cloud.githubusercontent.com/assets/11579534/17937539/617168d0-6a1a-11e6-8faf-8a4f9df1e994.png)
![screenshot 2016-08-24 16 32 07](https://cloud.githubusercontent.com/assets/11579534/17937540/61714990-6a1a-11e6-913a-76f390c877b7.png)

**Comment by mikejolley** [comment]
Whats in the tables? 

> When Shipping Zones were introduced, I created the zones and the rules normally.

With the new UI? Any chance someone removed them?

**Comment by rafaschou** [comment]
![screenshot 2016-08-24 21 39 42](https://cloud.githubusercontent.com/assets/11579534/17947182/86da9b40-6a43-11e6-9226-3d10a9244830.png)
![screenshot 2016-08-24 21 39 37](https://cloud.githubusercontent.com/assets/11579534/17947180/86d77924-6a43-11e6-8dee-26d6988f360f.png)
![screenshot 2016-08-24 21 39 13](https://cloud.githubusercontent.com/assets/11579534/17947181/86d7fff2-6a43-11e6-844b-58562f68114d.png)

**Comment by rafaschou** [comment]
The database seems to be fine. It's the UI that is not reading the data.. weird

**Comment by mikejolley** [comment]
On the zones page, right click > inspect > then look at the console. Any JS errors?

**Comment by rafaschou** [comment]
![screenshot 2016-08-25 10 14 30](https://cloud.githubusercontent.com/assets/11579534/17963293/bfe8dc58-6aac-11e6-9535-452f716c5172.png)

**Comment by mikejolley** [comment]
ajaxChosen is not something in core anymore. This means one of your extensions is causing the issue. Remove the extension, fix the issue.

This does not look like a core bug afterall.

**Comment by rafaschou** [comment]
hmmm I'll investigate the add-ons then. Thank you so much for your help!

**Comment by warby16** [comment]
I had the same issue, it was caused by the plugin "WooCommerce First Purchase Discounts". Hope this helps someone!

**Comment by rafaschou** [comment]
Yes, mine was "Woocommerce Mailchimp Discount". Once deactivated, Shipping Zones work.
