### ISSUE TITLE
WooCommerce > Add Product

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11779]
Is it necessary to have a sub-menu item just to add a product? There is no WooCommerce > Add Order, or WooCommerce > Add Category.

I'm thinking it could perhaps make the settings panels look less intimidating with one less option by removing this un-necessary sub menu item?

![](http://cld.wthms.co/lUWt/dyyZGPyn+)

Just an idea ¯\\\_(ツ)\_/¯

**Comment by mikejolley** [comment]
@kellychoffman?

**Comment by kellychoffman** [comment]
> Is it necessary to have a sub-menu item just to add a product? 

I think it makes sense in the context of the current menu. Products > Add Products. Just like there is Plugins > Add New, and Users > Add New. These are quick ways to access primary and frequently used actions. I'd rather keep the action of adding products in the menu as a quick way to access and not hide it behind an extra click. 

> There is no WooCommerce > Add Order, or WooCommerce > Add Category.

I think this is a side effect of the current menu structure. We don't have an Order or a Category top level menu item. If we did, I think one would expect to see Add Order and Add Category as sub menu items. If there was an easy way to do that now, it would be nice to have these actions be more accessible in the menu. For now, they will have to go into the Orders page for example, or via the top `+ New` menu. 

> I'm thinking it could perhaps make the settings panels look less intimidating with one less option by removing this un-necessary sub menu item?

Has there been feedback that the panel is too intimidating? 

I'd also worry that if we took this out without warning, existing users would initially think something was broken or their rights were removed.

**Comment by WPprodigy** [comment]
> Has there been feedback that the panel is too intimidating?

Not specifically to this panel, I'm just always in favor of removing settings when possible. Figured you can do this action by going to Products > Add New already, but your points are quite valid :)

**Comment by mikejolley** [comment]
Agree with Kelly. Closing :)
