### ISSUE TITLE
Order marked as failed in WC... but payment to Paypal Pro went through

### ISSUE THREAD

**Issue by RonTheWebsiteGuy** [woothemes/woocommerce#11770]
## EXPLANATION OF THE ISSUE

Woocommerce 2.3.11 
Wordpress 4.01

I have a strange issue with an order that reads as FAILED in the records report, but payment actually went through on the Paypal end. It shows in the report. The problem, of course, is that because the order doesn't go through, the seller is not given an order email and the buyer is not given a confirmation. It is an internal error 10001, but there is not much detail out there regarding it out there.  I am quite sure that it is an isolated incident. Paypal Pro, credit card checkout is the only method of payment. I would like to understand how this could happen though. Quite a serious bug, though seemingly rare.

Here is the error message:
PayPal Pro payment failed (Correlation ID: cd____________). Payment was rejected due to an error: (10001) “10001-Internal Error” Order status changed from Pending Payment to Failed.

## STEPS TO REPRODUCE THE ISSUE

Not sure what the steps were. 

### WordPress Environment ###
I removed some client info for anonymity sake.

Home URL: http://www.
Site URL: http://www
WC Version: 2.3.11
WC Database Version: 2.3.11
Log Directory Writable: ✔ /...    uploads/wc-logs/
WP Version: 4.0.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (14) ###

All In One SEO Pack: by Michael Torbert – 2.2.7.6.2
Rental System Addon for WooCommerce Booking & Appointment Plugin: by Ashok Rane – 1.3
Easy Pie Maintenance Mode: by Bob Riley – 0.6.7
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
PayPal for WooCommerce: by Angell EYE – 1.1.9.2
Fast Secure Contact Form: by Mike Challis
Ken Carlson – 4.0.39

Simple Responsive Slider: by marcelotorres – 0.2.2.5
WooCommerce Booking & Appointment Plugin: by Tyche Softwares – 2.5.2
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.2
WooCommerce Checkout Field Editor: by WooThemes / Mike Jolley / Patrick Garman – 1.4.5 – 1.5.0 is available
WooCommerce More Sorting: by Algoritmika Ltd – 2.0.0
WooCommerce Table Rate Shipping: by Erica Dion – 3.5
WooCommerce: by WooThemes – 2.3.11
WPFront Notification Bar: by Syam Mohan – 1.7

### Settings ###

API Enabled: ✔
Taxes Enabled: ✔
Shipping Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #13 - /________________-__________/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My Account: #16 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: _____________
Version: 1.0.0
Author URL: _____________________
Child Theme: ✔
Parent Theme Name: Virtue
Parent Theme Version: 2.6.3
Parent Theme Author URL: http://kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: __________/woocommerce/archive-product.php
__________/cart/cart-shipping.php version 2.1.0 is out of date. The core version is 2.3.0
__________/woocommerce/cart/cart-totals.php version 2.1.0 is out of date. The core version is 2.3.6
__________/woocommerce/cart/cart.php version 2.1.0 is out of date. The core version is 2.3.8
__________/checkout/form-billing.php
__________/checkout/form-checkout.php version 2.0.0 is out of date. The core version is 2.3.0
__________/checkout/form-pay.php
__________/checkout/form-shipping.php
__________/woocommerce/checkout/payment-method.php
__________/woocommerce/checkout/payment.php
__________/checkout/review-order.php version 2.1.8 is out of date. The core version is 2.3.0
__________/woocommerce/content-product.php
__________/woocommerce/content-product_cat.php
__________/woocommerce/content-single-product.php
__________/woocommerce/emails/admin-new-order.php
__________/woocommerce/emails/customer-completed-order.php
__________/woocommerce/emails/customer-processing-order.php
__________/woocommerce/emails/email-addresses.php
virtue/woocommerce/loop/loop-end.php
virtue/woocommerce/loop/loop-start.php
virtue/woocommerce/loop/price.php
virtue/woocommerce/loop/rating.php
virtue/woocommerce/loop/sale-flash.php
virtue/woocommerce/single-product/add-to-cart/external.php
virtue/woocommerce/single-product/add-to-cart/grouped.php
__________/woocommerce/single-product/add-to-cart/simple.php
virtue/woocommerce/single-product/add-to-cart/variable.php
virtue/woocommerce/single-product/price.php
virtue/woocommerce/single-product/product-image.php
virtue/woocommerce/single-product/product-thumbnails.php
__________/woocommerce/single-product/related.php
virtue/woocommerce/single-product/sale-flash.php
__________/woocommerce/single-product.php
__________/woocommerce/taxonomy-product_cat.php
virtue/woocommerce/taxonomy-product_tag.php

: Learn how to update outdated templates

**Comment by mikejolley** [comment]
You should read out to "PayPal for WooCommerce: by Angell EYE" - I don't know how they handle errors in their plugin.

**Comment by RonTheWebsiteGuy** [comment]
ah, i'm sorry about that. i forgot that woocommerce does not come with payment gateways and that errors of this nature are probably due to the payment gateway/error handling and not woocommerce itself.

**Comment by sgehrman** [comment]
I'm getting this today. Not sure if it's the sandbox or what.  Any explanation?

PayPal Pro payment failed (Correlation ID: e168ef6780e5c). Payment was rejected due to an error: (10001) “Internal Error” Order status changed from Pending payment to Failed.
