### ISSUE TITLE
Backend-Order For Guest Is Allowed To Make Payments When Guest Checkout Is Disabled?

### ISSUE THREAD

**Issue by harishankerr** [woothemes/woocommerce#11776]
Not sure if this is expected, but guest customers can make payments and check out, for orders created in the backend, without having to register.

### Recreating the issue.

1. Disable Guest Checkout first.

![Disable Guest Checkout](http://cld.wthms.co/128wu/3WvDblGH+)
http://cld.wthms.co/128wu/3WvDblGH

2. Created order by adding items to the order and not selecting a customer for the same:

![Created Order in Backend](http://cld.wthms.co/2xo6/OPBBlSth+)
http://cld.wthms.co/2xo6/OPBBlSth

3. A customer payment page link is created on saving this order. The link redirects to the payment page:

![Payment Page Created](http://cld.wthms.co/1i423/1R4dg6tS+)
http://cld.wthms.co/1i423/1R4dg6tS

![Link Redirected to Payment Page](http://cld.wthms.co/12Joz/5hTzZQs7+)
http://cld.wthms.co/12Joz/5hTzZQs7

4. After the payment is made, the order is successfully placed - without the customer having to register in the site where checkout is disabled

![Order Successfully Placed](http://cld.wthms.co/T2V8/1Igg8eZa+)
http://cld.wthms.co/T2V8/1Igg8eZa

### Footnotes

I'm not sure if this is expected functionality, as the order is placed in the administrator side, with the adminstrator's knowledge - which invalidates the need for customer registration.

**Comment by mikejolley** [comment]
> I'm not sure if this is expected functionality, as the order is placed in the administrator side, with the adminstrator's knowledge - which invalidates the need for customer registration.

Correct this is intended. This isn't actually full checkout, just payment of an existing order which requires the special link + key. It's not possible for a random to stumble upon this link by accident.

I will make a note of this for https://github.com/woothemes/woocommerce/issues/10764 where we should maintain this behavior.

Thanks

**Comment by harishankerr** [comment]
Thanks, Mike! 👍
