### ISSUE TITLE
Setting meta items for an order with the rest API

### ISSUE THREAD

**Issue by theshaune** [woothemes/woocommerce#11783]
I am attempting to add an order with the REST API, and it works correctly, however I cannot add meta details to each product line, I understand that the meta is read only and have read this in the [docs](http://woothemes.github.io/woocommerce-rest-api-docs/#order-properties), but I don't understand why?

A use case for being able to write meta items per product in an order is when we need to customise the product, for example, have a user enter text or something that isn't quite a variation.

I'd be interested to hear thoughts on this or if there is an alternate way to go about this?

Thanks

**Comment by mikejolley** [comment]
It's read only so no, there is not a way around this without writing a plugin on the server you're communicating with. We're adding support for meta in future versions - REST API is a work in progress.

https://github.com/woothemes/woocommerce/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.7
