### ISSUE TITLE
unicode support on rest-api url

### ISSUE THREAD

**Issue by hamzeh1388** [woothemes/woocommerce#11787]
how can send utf8-charset to rest-api url?
like:
$product_title='%25D8%25B2%25D9%2586%25D8%25A7%25D9%2586%25D9%2587';
$result = $client->custom->get('',array('filter[q]' => $product_title));
this string not support in url;

**Comment by mikejolley** [comment]
@claudiosmweb

**Comment by claudiosmweb** [comment]
Show me the title without converting, so I can test.

**Comment by hamzeh1388** [comment]
زنانه

**Comment by mikejolley** [comment]
No issues sending that value via PAW https://dl.dropboxusercontent.com/s/bo3z5q5lj3c0opw/2016-09-06%20at%2011.45.png?dl=0

**Comment by hamzeh1388** [comment]
OK.
i write a route in  local wordpress /wp-content/plugins/wocommerce/includes/api/class-wc-api-products.php  like this:
$routes[$this->base . '/tak/(?P<tag>\w[\w\s\-]*)'] = array(
            array(array($this, 'get_product_all'), WC_API_Server::READABLE),
        );


and create a request like this:
 $result = $client->custom->get(array('tak/زنانه'),array('fields'=>'id,title,sku','filter[limit]' => '10'));
NOT WORK and error in URL
but when request like this:
  $result = $client->custom->get(array('tak/womanly'),array('fields'=>'id,title,sku','filter[limit]' => '10'));
it's WORK
