### ISSUE TITLE
TGM Plugin Activation PHP fatal error when activating plugin

### ISSUE THREAD

**Issue by webmandesign** [woothemes/woocommerce#11795]
Using WooCommerce 2.6.4 on WordPress 4.6 I'm trying to recommend the plugin via [TGM Plugin Activation script version 2.6.1](https://github.com/TGMPA/TGM-Plugin-Activation/releases/tag/2.6.1). 

My WordPress is set to multisite (haven't noticed this issue on single site installation).

When activating WooCommerce via TGMPA **Appearance &raquo; Install Plugins** I get the same PHP fatal error as described at https://github.com/TGMPA/TGM-Plugin-Activation/issues/369

Though the issue was fixed before in WooCommerce, the fix was removed in some of recent versions. Please reintroduce the `function_exists( 'wc_get_screen_ids' )` check in `WC_Admin->admin_footer_text()` method.

**Comment by webmandesign** [comment]
Fixing the issue with #11796

**Comment by claudiosmweb** [comment]
Solved by #11796 
Thanks.

**Comment by shivapoudel** [comment]
@claudiosanches Confirmed! its not fixed.
See #12792
