### ISSUE TITLE
Intergrate the Payment Request API

### ISSUE THREAD

**Issue by jonkoops** [woothemes/woocommerce#11794]
The Payment Request API can give WooCommerce all the information it needs to pay and ship a product without ever showing a checkout form. This could potentially reduce friction of user engagement significantly, resulting in greater conversion rates. All major browser vendors have announced [support](https://www.chromestatus.com/features/5639348045217792) for the Payment Request API.

I would like to use this issue to discuss possible ways of implementing the Payment Request API in WooCommerce core or possibly a plugin.

## Demo Video
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/hmqZxP6iTpo/0.jpg)](https://www.youtube.com/watch?v=hmqZxP6iTpo)

## Reading Material
https://developers.google.com/web/fundamentals/primers/payment-request/
https://www.w3.org/TR/payment-request/

**Comment by jonkoops** [comment]
cc @agektmr @zkoch

**Comment by claudiosmweb** [comment]
I think that we can try put it into a plugin and see what happens before include to the core.

**Comment by jonkoops** [comment]
@claudiosmweb Any chance we can do this under the WooCommerce banner?

**Comment by claudiosmweb** [comment]
@jonkoops what banner?

**Comment by claudiosmweb** [comment]
This can be related to #10672

**Comment by jonkoops** [comment]
Well, as part of the [WooThemes](https://github.com/woothemes) github profile. If you want I can set it up under my own name.

**Comment by claudiosmweb** [comment]
@jonkoops we can do it under WooThemes or Automattic profile, but first I need to check with the team about it.
I like this idea, but need more talk before start doing something.

**Comment by jonkoops** [comment]
Agreed. Just putting it out there. You raise a valid point that this would probably influence #10672. I would definitely take these developments into account, because it's most likely the future of paying for stuff on the web.

**Comment by mikejolley** [comment]
This would be an overlay and shouldn't affect regular checkout at all. We have internal plans to do something with this, but not part of WC core. Probably an extension until it's standardized and supported in all browsers/devices.

Closing this as it's not related to core. If this ends up being an open repo, I'll send you a ping.

cc @mattyza

**Comment by jonkoops** [comment]
Well, not really an overlay. It would replace most of the checkout page if implemented. But yeah, it could be a separate plugin.

**Comment by mikejolley** [comment]
Yeah but it's along those lines. Need to work out best implementation :)
