### ISSUE TITLE
Filter widget bug

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11791]
### EXPLANATION OF THE ISSUE

Some product will never show up w/ price filter due to decimals in their price. Should only happen with the highest priced items.

### STEPS TO REPRODUCE THE ISSUE

1. Create a product w/ the price of $250.50 (or whatever it takes to be the highest price in the store, then add 50 cents)
2. Using the price filter widget, filter the page from say $225 - $250(the max it will let you).
3. Notice that the product you just created does not show up, because it is above $250.

**Comment by dhakshinait** [comment]
We can use CEIL() to get maximum price from the database. We need to alter the below query in price filter widget to fix the issue.

`$sql  = "SELECT min( CAST( price_meta.meta_value AS UNSIGNED ) ) as min_price, max( CAST( price_meta.meta_value AS UNSIGNED ) ) as max_price FROM {$wpdb->posts} ";`

to

`$sql  = "SELECT min( CAST( price_meta.meta_value AS UNSIGNED ) ) as min_price, max( CAST( CEIL(price_meta.meta_value) AS UNSIGNED ) ) as max_price FROM {$wpdb->posts} ";`


Function Name: get_filtered_price
Path: woocommerce/widgets/class-wc-widget-price-filter.php

**Comment by dhakshinait** [comment]
Hi, It seems issue closed. Will that fix add in next release?. thanks

**Comment by WPprodigy** [comment]
It's now in the master branch. Should be included in the next release.

**Comment by dhakshinait** [comment]
ok. thanks.

**Comment by lukeliasi** [comment]
Is there a fix for the minimum price also? If I have a product price above 9.50 the product will show up on a min price filter of 10

**Comment by WPprodigy** [comment]
It rounds up for min price I believe, but it sounds like it is working like it should. If your lowest price is 9.50 and the lowest filter is 10, the product should still show up. Otherwise it never would.

**Comment by lukeliasi** [comment]
The filter range that is automatically set seems to round down. I have a product for 9.99 and the filter range minimum automatically gets set at 9 (and the product shows as it should with 9 as min price). If I then slide the min price filter up to 10 the product at 9.99 still shows even though the minimum price is set at 10.

Should this be happening? Seems a bit odd to me to work like this. Especially considering if you have smaller valued products at say 1.55 and 2.50 - with 1.55 being rounded up to 2 that product is being classified as 0.45 more which is 29% of it's value.

**Comment by WPprodigy** [comment]
Hmm, probably best to open up a new issue then and you can link over to this one for reference.
