### ISSUE TITLE
Better layout for Downloads page

### ISSUE THREAD

**Issue by jessepearson** [woothemes/woocommerce#11806]
## EXPLANATION OF THE ISSUE

The table on the Downloads page in 2.6.x is confusing and gives a bad user experience. The first column is named `File`, however, it links to the product. Additionally, it combines the Product and File names together to make a long link, which turns out being hard to read. The other columns seem to take up much more space than needed, as well.

![screen shot on 2016-08-29 at 16-02-41](https://cloud.githubusercontent.com/assets/4634416/18065578/6913f3c8-6e02-11e6-924c-4cab2c1de3ae.png)

## STEPS TO REPRODUCE THE ISSUE

1. Create a downloadable product
1. Purchase the product
1. Go to My Account > Downloads to view

### Other

User brought up this issue in 460792.

**Comment by claudiosmweb** [comment]
@jameskoster @kellychoffman thoughts?

**Comment by kellychoffman** [comment]
Lets do something like this:

![screen shot 2016-08-31 at 11 10 47 am](https://cloud.githubusercontent.com/assets/5835847/18138783/a3042296-6f6b-11e6-9792-1d8a2d643f50.png)

- Take product name out of link
- Product name becomes bold, on first line
- File name underneath product name
- Table cells are`vertical-align: top`

**Comment by mikejolley** [comment]
@kellychoffman what about putting the file name in the download button rather than having 2 links for the same thing?

**Comment by mikejolley** [comment]
Also need to check how multiple file support works.

**Comment by claudiosmweb** [comment]
The link in the "File" column is for the product page... So we don't need a link in the "File name", maybe we can add a extra column for file names too.

@mikejolley one file per row, even if comes from the same product.

**Comment by claudiosmweb** [comment]
About the extra column, we can have:

| File | Product | Remaining | Expires | Download |
| --- | ---- | --- | --- | --- |
| File name | Product name | 12 | Never | Button |

**Comment by kellychoffman** [comment]
> what about putting the file name in the download button rather than having 2 links for the same thing?

Yeah, that makes more sense. 

Since there's not much space here, maybe we should remove a column instead of adding one and add the download button in place of the `File name` in https://github.com/woothemes/woocommerce/issues/11806#issuecomment-243833963?

**Comment by jessepearson** [comment]
`File name` is something that the user sets, so I don't believe removing it is an option.

**Comment by kellychoffman** [comment]
@jessepearson: I was suggesting what Mike said: 

> what about putting the file name in the download button rather than having 2 links for the same thing?

**Comment by jameskoster** [comment]
@claudiosmweb I think 'Product' should be the first column. So for products with multiple files you can do;

| Product | File | Downloads remaining | Expires | Download |
| --- | ---- | --- | --- | --- |
| Product name | File name | 12 | Never | Button |
|| Another file name | 8 | Never | Button |
| Another Product name | File name | 12 | Never | Button |
|| Another file name | 8 | Never | Button |
|| Another file name | 99 | Never | Button |
