### ISSUE TITLE
Open free shippings docs link in a new tab/window

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#11801]
## EXPLANATION OF THE ISSUE

When editing a coupon, the following link doesn't open in a new window:

![](http://cld.wthms.co/12lub/5KN1fkqz+)

## STEPS TO REPRODUCE THE ISSUE

1. Go to WooCommerce > Coupons
2. Click `Add Coupon`

**Comment by corsonr** [comment]
Apparently the link is now internal https://github.com/woothemes/woocommerce/commit/63c0445957f92a88197f03bebdd979a6674f85c8

**Comment by claudiosmweb** [comment]
Not internal, right now we redirect to the docs, since we need to configure free shipping using shipping zones.
