### ISSUE TITLE
After updating to 2.6 does not show on a dasboard board system status woocommerce not gross profits but net profit.

### ISSUE THREAD

**Issue by lukasprelovsky** [woothemes/woocommerce#11807]
After updating to 2.6 does not show on a bulletin board system status woocommerce not gross profits but net profit. 

How to return to the original?

shop owners were complaining about everything from me, this has changed.

To display system status woocommerce dashboard in wordpress dasboard net profit and not pure profit!

thx for help

**Comment by mikejolley** [comment]
You can remove the dashboard widget and add a custom one https://codex.wordpress.org/Dashboard_Widgets_API

Showing net matches reports and is generally better since it reflects refunds which skew stats.
