### ISSUE TITLE
Cannot edit the shipping options

### ISSUE THREAD

**Issue by masteryacht** [woothemes/woocommerce#11809]
## EXPLANATION OF THE ISSUE

In the woocommere>setttings>shipping menu I get "rest of the world" but I am unable to add a shipping zone, averytime I click on add a shipping zone or shipping option, nothing is happening at all

## STEPS TO REPRODUCE THE ISSUE
woocommere>setttings>shipping zones

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://masteryachtservices.fr
Site URL: http://masteryachtservices.fr
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Nous recommandons l’augmentation de la mémoire à 64Mo minimum. Voir : Augmenter la mémoire allouée à PHP
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (25) ###

PricingTable: par wpkids – 1.8
AddToAny Share Buttons: par AddToAny – 1.7
Akismet: par Automattic – 3.1.11
BAW Post Views Count: par Juliobox – 3.0.2
CC Child Pages: par Caterham Computing – 1.34
Contact Form 7 MailChimp Extension: par Renzo Johnson – 0.4.30
Contact Form 7: par Takayuki Miyoshi – 4.5
Display Widgets: par Strategy11 – 2.05
Duplicator / Cloner / Migrator: par www.wpadm.com – 2.1.2
Duplicator: par LifeInTheGrid – 1.1.16
Easy Facebook Likebox: par Sajid Javed – 4.2.6
Google Analytics Dashboard for WP: par Alin Marcu – 4.9.3.1
Hello Bar (Official): par Hello Bar – 1.0
MailChimp pour WordPress: par ibericode – 4.0.3
Mailchimp Forms by Optin Cat: par Fatcat Apps – 1.6.1
NovelPro Unlimited: par ThemeHunk – 1.0.3
Redirection: par John Godley – 2.4.5
W3 Total Cache: par Frederick Townes – 0.9.4.1
WooCommerce Amazon Payments Advanced Gateway: par WooThemes – 1.5.4
WooCommerce PayPal Express Checkout Gateway: par Automattic – 1.1.2
WooCommerce: par WooThemes – 2.6.4
WooCommerce Helper: par WooCommerce – 1.7.0
Wordfence Security: par Wordfence – 6.1.15
Yoast SEO: par L’équipe Yoast – 3.4.2
WP Menu Cart: par Jeremiah Prummer
Ewout Fernhout – 2.5.7

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: #300 - /shop
Panier: #301 - /cart
Commande: #302 - /checkout
Mon Compte: #303 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: NovelPro Responsive Theme
Version: 2.3.3
Author URL: http://www.themehunk.com
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: Votre thème a un fichier woocommerce.php
vous ne serez pas en mesure de substituer le modèle personnalisé woocommerce/archive-product.php étant donné que woocommerce.php a la priorité sur archive-product.php. Ceci vise à prévenir les problèmes d’affichage.

Overrides: –
`
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
Works just fine.

> I click on add a shipping zone or shipping option, nothing is happening at all

Check the browser console for this first one, since it works with JavaScript.
But seems like conflict with other plugin and not an issue on WooCommerce.

**Comment by masteryacht** [comment]
Hello Claudio,
Thanks a lot for responding, I did not understand what I need to do to fix the problem. I not developper or whatever just a regular business owner
So what can I do?

**Comment by masteryacht** [comment]
in the console I have this  : 

`load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:9 JQMIGRATE: Migrate is installed, version 1.4.1
widget.js?ver=1.0:8 Uncaught TypeError: Cannot read property 'editor' of undefinedmedia_upload @ widget.js?ver=1.0:8(anonymous function) @ widget.js?ver=1.0:50i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2ready @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2K @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2`
