### ISSUE TITLE
Product type icons are all the same in edit.php

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#11819]
The ship your idea hoodie is a variable product, but the icon in the type column is the same as the simple products. Only when you hover over it, does it reveal that it's a variable product. 

![image](https://cloud.githubusercontent.com/assets/507025/18132453/90c8c9ec-6f5c-11e6-9b27-86388d6536d8.png)

**Comment by mikejolley** [comment]
There is a subtle difference - the variable one has a border around it. It's not very clear though - those icons will be removed and reworked in the next big UI update currently being worked on behind the scenes. We'll announce when ready.

**Comment by helgatheviking** [comment]
I see it now. Damn, that is "subtle". Look forward to the new UI.
