### ISSUE TITLE
Shouldn't WC_Shortcode_Checkout  wc_print_notices be in a template instead of the core function?

### ISSUE THREAD

**Issue by pixeline** [woothemes/woocommerce#11814]
I would like to control the checkout form submission errors (print each input error next to its input instead of all on top of the form) but it happens inside the shortcode callback function. (the exact line is [223](https://github.com/woothemes/woocommerce/blob/efd390e9510d168ae730b05504225aa21b2a99cc/includes/shortcodes/class-wc-shortcode-checkout.php#L223)  )

Forgive my shortsightedness, but it seems to me strange that wc_print_notices() be so early in the process. It should, in my view, only be called inside the template files (since it's about output), giving easier control of the screen flow to designers.

**Comment by claudiosmweb** [comment]
Closing in favor of #10672 since maybe we can include "print each input error next to its input instead of all on top of the form" as default.
