### ISSUE TITLE
product transient cache doesn't save version information

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#11812]
Related to #11520 

I've copied some of the current code with unnecessary things omitted. The question I have is with cache invalidation with the product version. Steps below code.

```
if ( empty( $this->prices_array[ $price_hash ] ) ) {

	// Get value of transient
	$prices_array = array_filter( (array) json_decode( strval( get_transient( $transient_name ) ), true ) );

	// If the product version has changed, reset cache
	if ( empty( $prices_array['version'] ) || $prices_array['version'] !== WC_Cache_Helper::get_transient_version( 'product' ) ) {
		$this->prices_array = array( 'version' => WC_Cache_Helper::get_transient_version( 'product' ) );
	}

	// If the prices are not stored for this hash, generate them
	if ( empty( $prices_array[ $price_hash ] ) ) {
		// get stuff
		set_transient( $transient_name, json_encode( $prices_array ), DAY_IN_SECONDS * 30 );
	}

	$this->prices_array[ $price_hash ] = apply_filters( 'woocommerce_variation_prices', $prices_array[ $price_hash ], $this, $display );	
}
```

1. we're checking whether we already have the prices in the property. Let's assume we don't
2. we're fetching the stored prices from the transient, and storing it in a local variable `$prices_array`. Because of what happens later in `set_transient`, `$prices_array` does NOT have a `version` key / value.
3. we're checking the existence / value of the `version` in the local variable `$prices_array`. Because of 2., it is guaranteed to fail
4. because of this, we're fetching the current product version, and storing it on the `$this->prices_array` property, but NOT the local variable `$prices_array`. This also overwrites anything in `$this->prices_array`, though because we've checked whether it's empty, there's nothing to overwrite on the property. The local variable `$prices_array` still has the fetched price array though, unchanged by the version.
5. we then check the local variable `$prices_array` whether the price hash key is empty. Because we haven't done anything to clear the local variable, it will not be empty, unless the transient didn't have anything about it in the first place. For the sake of argument let's suppose there are no prices here
6. Then it's fetching the actual prices, and stores them in the local variable `$prices_array`, and then that gets saved to the transient. Note that `version` is not on the variable, so that will NOT be saved alongside the array, which causes the check in 2. to be unnecessary

## What I think should happen

In step 4 above the version should be fetched to local variable `$prices_array`. That way it would be saved into the transient in step 6, and the comparison with the current version vs stored version in step 3 would actually make sense. Then later in step 4 if the version changed, the assignment would immediately clear any `price_hash` keys on the `$prices_array`, forcing the rest of the method to re-fetch new, and updated prices.

On top of that, `$this->prices_array['version']` isn't even used anywhere else in that method, and is definitely not being returned to the caller.

It looks like it's an oversight / typo / error, but I want to double check whether I'm missing something.

The same comment is posted on the related issue, but I'm growing increasingly convinced it's an actual bug needing its own issue.

**Comment by franticpsyx** [comment]
@javorszky I think it's an oversight in https://github.com/woothemes/woocommerce/pull/10984/files which is why I posted the link.

It's been a long time since I sent that PR to address another issue, so this doesn't quite ring a "ohhh right, I missed that line" bell... Looks like a bug introduced in https://github.com/woothemes/woocommerce/pull/10984 ?

**Comment by javorszky** [comment]
@franticpsyx yeah, it does look like a bug. It normally flies under the radar too, because transients are short lived on most sites that this would cause a problem on. Right now they wouldn't be invalidated if the product version changed, but it's okay because the transients are cleaned shortly anyways.

**Comment by mikejolley** [comment]
@franticpsyx @javorszky Regarding #11817, thats not going to solve anything. In your suggested edit, you're setting the version in the local variable yes, however, thats never saved either because if you look further down:

```
$this->prices_array[ $price_hash ] = apply_filters( 'woocommerce_variation_prices', $prices_array[ $price_hash ], $this, $display );
```

Thats all we set to the class variable. Not the entire thing - just the one hash. The cache is 'cleared' because $this->prices_array is emptied already.

**Comment by mikejolley** [comment]
Looks like we have to clear both, or set versions in both.

**Comment by javorszky** [comment]
Lemme rework the PR then, hold on.

**Comment by javorszky** [comment]
Done :)

**Comment by mikejolley** [comment]
Logic is still confusing. Seeing if I can clear it up based on your PR too.
