### ISSUE TITLE
You can add the same shipping method multiple times

### ISSUE THREAD

**Issue by lutrov** [woothemes/woocommerce#11816]
The shipping zone editor lets you add the same shipping method multiple times.

![screenshot-201608311610](https://cloud.githubusercontent.com/assets/11863829/18118226/dafbb24c-6f96-11e6-81b8-b21d4a99aa01.png)

**Comment by mikejolley** [comment]
Yes, thats the point of zones. https://docs.woocommerce.com/document/setting-up-shipping-zones/

**Comment by lutrov** [comment]
Would you know where I can get the documentation that explains why you'd ever want multiple flat rate shipping costs for the same shipping zone? I have read the docos here already:

https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/shipping/

For instance, if I have a zone called "Australian Domestic", I then add one flat rate that's $2 and another flat rate that's $3, they both come up as choices at checkout. Which one would the customer pick?

**Comment by lutrov** [comment]
Sorry, my mistake. I wasn't able to change the method titles (it looks to have been some JS conflict that caused it) so all I ever saw was "Flat Rate" for all of them, which led to the confusion.

Once you change the method title to something like "Aussie Post" and "Aussie Post Express" and make them $2 and $3 respectively, it makes sense. :-)

**Comment by claudiosmweb** [comment]
;)
