### ISSUE TITLE
Tax calculation on coupon amount for zero tax rate

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#11810]
### EXPLANATION OF THE ISSUE

Having a product of 199€ including Tax of 19% and setting up a product discount coupon of 150€ works fine if the customer is within same tax rate and has to pay 49€ including tax [199 - 150] . But if the customer is in an zero tax rate country, he is billed only 17,23€ because the coupon is still 150€ and the product is 167,23€ without tax.

### Screenshots

Coupon settings:

![](http://cld.wthms.co/qarH/4GBbiH9j+)

Tax settings:

![](http://cld.wthms.co/11JMM/31KQhmPD+)

Tax Options:

![](http://cld.wthms.co/TxUp/2JZPTWPJ+)

When the customer is in the taxable region [19% included]:

![](http://cld.wthms.co/1dXBM/3TtcI9bz+)

When the customer is in the non taxed region:

![](http://cld.wthms.co/1cop2/tPEOa92U+)

### Related ticket
zd-woothemes-452071

**Comment by mikejolley** [comment]
This is correct. The coupon is worth 150 regardless of the amounts or taxes, as it should.

If the user wants the country to make no difference to final amounts (so they pay the same wherever they are) see https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior This is something I want to make default in future versions.
