### ISSUE TITLE
select.variation_actions.Triggerhandler initialized before field available

### ISSUE THREAD

**Issue by GordonRelenda** [woothemes/woocommerce#11829]
## EXPLANATION OF THE ISSUE
WordPress 4.5.3
Woocommerce 2.6.7

File: /assets/js/admin/meta-boxes-product-variation.js
Line: 756

We added custom bulk calls to the select.variation_actions form (Backend - Products new/edit - Variations tab). In one call we need to use the triggerHandler to get data from a custom function, before sending the ajax request.

The problem is that the field select.variation_actions isn't created from the beginning, for a new product. (For an existing product, in edit mode, no problem.) As the select.variation_actions isn't there, the triggerhandler does not trigger it and our function is never called.

Also: 
- We can also not bind the function to a higher DOM element, as triggerHandler does not bubble up in the DOM. 
- We can not use the trigger event one line before, as it does not handle data.

_The second problem is that, if 'data' is filled before, triggerHandler can set the entire variable to 'undefined'. (But this currently not my problem)_

An example custom function for the trigger (which is located in theme folder):
`$( 'select.variation_actions' ).on('tmp_create_variations_ajax_data', function () {
        var data = {};
        data = "abc";
        alert("works!");
        return data;
});`

Could you please give me any feedback on this. Need help :)

Cheers
Gordon

**Comment by mikejolley** [comment]
You could add your handlers after 'woocommerce_variations_added' event is triggered. Thats when the variation panel is loaded and the select becomes available.

If you can find a better workaround, please submit a PR for review. It's your code so you have more knowledge about what you need here.

Thanks
