### ISSUE TITLE
price_html is empty if product variables are exactly the same price

### ISSUE THREAD

**Issue by pojke** [woothemes/woocommerce#11827]
We're currently working on the project where we use price_html in the theme for displaying pricing of the product.
The issue is when a product is a variable product and all prices of variations are the same. In this configuration price_html is empty based on the code.

This comes from this part: 
https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L614

Is the reason for showing price_html **only** when maximum is different to minimum (which is causing the bug)?

**Comment by mikejolley** [comment]
Not a bug - deliberate. The price for all variations is the same, so it's shown below the main product title only (like on all other product types).

**Comment by pojke** [comment]
Ok understood. It's quite illogical behavior though I have to say. You're deciding for template provider about variable, it should be up to template provider to decide whether price is displayed or not and where. The price **should never** be returned empty, that's why in my opinion it's unwanted feature that should be eliminated.

**Comment by nickbreen** [comment]
For anyone else that's run afoul of this _bug_, i resorted to this (rest of the template elided) in `single-product/add-to-cart/variable.php`

```php
global $product;
foreach ($available_variations as $i => $variation) :
    echo $variation['price_html'] ?: $product->get_price_html();
endforeach;
```

**Comment by hypnoboutique** [comment]
`add_filter( 'woocommerce_show_variation_price', '__return_true');`
