### ISSUE TITLE
Missing Countries In Country-List?

### ISSUE THREAD

**Issue by harishankerr** [woothemes/woocommerce#11826]
In 462790, a customer reported the following countries missing in the list of Countries in WooCommerce.

## Missing Countries

1. Kosovo ([seems to be a disputed territory](https://en.wikipedia.org/wiki/Political_status_of_Kosovo))
2. Sao Tome and Principe (Doesn't [seem to have such issues at first glance](https://www.cia.gov/library/publications/the-world-factbook/geos/tp.html))

Anything we can do about this? @mikejolley

**Comment by mikejolley** [comment]
Please don't take their word for it :p Lookup the ISO country codes and compare.

Seo Tome is defined: https://github.com/woothemes/woocommerce/blob/master/i18n/countries.php#L210

Kosovo has no official country code and only has a temporary code as defined here https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

If the user wants it before official, extend via the filter or use a plugin https://wordpress.org/plugins/woocommerce-add-countries/

**Comment by harishankerr** [comment]
Wow! Thank you so much, @mikejolley 👍

**Comment by AceAutomation** [comment]
Greetings,
This plugin seem not updated today.
I don't want to try it.
Do you know another way for add Kosovo in the countries list ?
I tried some snippets, but they doesn't work.
Thanks
Rémi
