### ISSUE TITLE
After update to WP 4.6 problem with display atrribute

### ISSUE THREAD

**Issue by ScAArY** [woothemes/woocommerce#11820]
After update WP to 4.6, Woocommerce (2.6.4) does not display the attributes of the order (eg color) in the summary of the order, and in the mail order confirmation.

In the old version of WP it worked without a problem. The problem showed up after upgrade to 4.6.

In backend i have this attributes.

![sklep](https://cloud.githubusercontent.com/assets/21075970/18133198/ee84df3e-6f99-11e6-9aa4-5838a124e4c3.png)

**Comment by mikejolley** [comment]
This might be a template problem. No other reports I've seen, and it's working fine my side. So its either template or plugin conflict - do some testing.

Please also for future reference, do all of the steps in the new issue form.

**Comment by ScAArY** [comment]
ok, in WP 4.4.4 all working ok
