### ISSUE TITLE
Expensive Comments Query Run on Every Admin Page

### ISSUE THREAD

**Issue by w00tw00t111** [woothemes/woocommerce#11824]
## EXPLANATION OF THE ISSUE
WooCommerce 2.5.5 and under

On every Admin WordPress page a comment_approved, count comments query is run.

On an extremely large database with thousands of comments this causes a drastic slow down on all admin pages. On a development server we are consistently seeing a query load time of 0.16+ seconds.

The exact query being run is:
SELECT comment_approved, COUNT( * ) AS num_comments
FROM wp_comments
WHERE comment_type != 'order_note'
GROUP BY comment_approved

## STEPS TO REPRODUCE THE ISSUE

1) Use a query profiling program such as [https://wordpress.org/plugins/query-monitor/](Query Monitor)
2) Go to any page in the admin section
3) View Queries run
4) Look for query:
`SELECT comment_approved, COUNT( * ) AS num_comments
FROM wp_comments
WHERE comment_type != 'order_note'
GROUP BY comment_approved`

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: [Blocked For Privacy]
Site URL: [Blocked For Privacy]
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (82) ###

Query Monitor: by John Blackbourn – 2.12.0
ManageWP - Worker: by ManageWP – 4.2.9
Gravity Forms: by rocketgenius – 2.0.6
Akismet: by Automattic – 3.1.11
amr shortcode any widget: by anmari – 3.3
Better Analytics: by Digital Point – 1.1.4
Better WordPress reCAPTCHA: by Khang Minh – 2.0.3
CategoryTinymce: by Kevin Heath – 3.6.4
Admin Columns: by AdminColumns.com – 2.5.6.2
Disable All WordPress Updates: by Oliver Schlöbe – 1.4.7
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.18
Enhanced Text Widget: by Boston Dell-Vandenberg – 1.4.5
Facebook Conversion Pixel: by Kellen Mace – 1.3.4
Features: by WooThemes – 1.5.0
FreshDesk AddOn: by Allen Bradley – 1.0.0
Freshdesk: by Harish Chouhan – 1.2.1
Genesis eNews Extended: by Brandon Kraft – 2.0.2
WC Cart Shortcode: by Allen Bradley – 1.0
Heartbeat Control: by Jeff Matson – 1.0.3
Icegram - Popups, Optins, CTAs & lot more...: by icegram – 1.9.18
Gravity Forms Infusionsoft Add-On: by Katz Web Services
Inc. – 1.5.12

NIX Gravatar Cache: by NIX Solutions Ltd – 0.0.7
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Page Links To: by Mark Jaquith – 2.9.6
Per page head: by Erik von Asmuth – 1.3
PHP Compatibility Checker: by WP Engine – 1.1.2
Plugin Organizer: by Jeff Sterup – 6.0.10
Q2W3 Fixed Widget: by Max Bond – 4.0.6
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Recover Abandoned Cart: by Fantastic Plugins – 8.9
Red Apple Lipstick: by Allen Builder – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Registration Honeypot: by Justin Tadlock – 1.0.0
Save with keyboard: by Mattia Trapani (zupolgec) – 2.1
Say What?: by Lee Willis – 1.7.1
Simple Copy Post: by John Regan – 1.0
Simple Social Icons: by Nathan Rice – 1.0.13
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

Testimonials: by WooThemes – 1.5.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.18.1

User Switching: by John Blackbourn – 1.0.9
Woocommerce Add-to-Cart Custom Redirect: by Ren Ventura – 1.2
WooCommerce Anti Fraud: by WooThemes – 1.0.5
WooCommerce Attributes Menu Manager: by Varun Sridharan – 0.6
WooCommerce Checkout Add-Ons: by WooThemes / SkyVerge – 1.7.1 – 1.8.2 is available
WooCommerce Composite Products: by WooThemes – 3.6.5 – 3.6.9 is available
WooCommerce Conditional Content: by Lucas Stark – 1.2.0
WooCommerce Customizer: by SkyVerge – 2.2.0
WooCommerce Dynamic Pricing: by Lucas Stark – 2.11.0 – 2.11.6 is available
WooCommerce Freshdesk: by WooThemes – 1.1.4
WooCommerce Stacked Add-to-Cart Product Forms: by franticpsyx
SomewhereWarm – 1.1.1

WooCommerce Authorize.net CIM Gateway: by WooThemes / SkyVerge – 2.2.1 – 2.3.2 is available
WooCommerce Min/Max Quantities: by WooThemes – 2.3.13 – 2.3.14 is available
WooCommerce Order Status Manager: by WooThemes / SkyVerge – 1.4.5 – 1.6.2 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.32
WooCommerce Points and Rewards: by WooThemes – 1.4.1
WooCommerce Product Bundles: by WooThemes – 4.14.3 – 4.14.7 is available
WooCommerce Sequential Order Numbers: by SkyVerge – 1.6.1
WooCommerce USPS Shipping: by WooThemes – 4.3.2 – 4.3.3 is available
WooCommerce - ShipStation Integration: by WooThemes – 4.1.6
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce Smart Coupons: by WooThemes – 3.0.17 – 3.1.2 is available
WooCommerce Waitlist: by Neil Pie – 1.4.13
WooCommerce Warranty Requests: by 75nineteen Media LLC – 1.7.4 – 1.8.3 is available
WooCommerce: by WooThemes – 2.5.5
WooReports: by Lucian Capdefier (luciancapdefier) – 1.2.2
Shipping Details for WooCommerce: by PatSaTECH – 1.7.0
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.6.2
Yoast SEO Premium: by Team Yoast – 3.4.2
WP Add Custom CSS: by Daniele De Santis – 0.9.7
WP Clean Up: by BoLiQuan – 1.2.3
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP Crontrol: by John Blackbourn & Edward Dale – 1.3.1
WP Custom Login: by Ninos Ego – 1.4.8
Email Login: by Beau Lebens – 4.6.4
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
WP-Optimize: by Ruhani Rabin – 1.9.1
WP Super Cache: by Automattic – 1.4.8
WP User Avatar: by flippercode – 2.0.7
YITH WooCommerce Ajax Search: by Yithemes – 1.3.9
YITH WooCommerce Wishlist: by YITHEMES – 2.0.15

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Flatsome Child Theme
Version: 2.2
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.8.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-child/woocommerce/archive-product.php
flatsome-child/woocommerce/cart/cart.php
flatsome-child/woocommerce/checkout/form-checkout.php
flatsome-child/woocommerce/checkout/payment.php
flatsome-child/woocommerce/checkout/terms.php
flatsome-child/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome-child/woocommerce/emails/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome-child/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome-child/woocommerce/myaccount/form-edit-account.php
flatsome-child/woocommerce/myaccount/form-login.php
flatsome-child/woocommerce/myaccount/my-account.php
flatsome-child/woocommerce/myaccount/my-orders.php
flatsome-child/woocommerce/myaccount/view-order.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome-child/woocommerce/single-product/meta.php
flatsome/woocommerce/single-product/price.php
flatsome-child/woocommerce/single-product/product-image.php
flatsome-child/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome-child/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome-child/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome-child/woocommerce/single-product/tabs/tabs.php
flatsome-child/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Overrides: flatsome-child/woocommerce/single-product/component-options-thumbnails.php
: Learn how to update outdated templates

### Authorize.net CIM ###

Environment: Production
Tokenization Enabled: –
`

**Comment by claudiosmweb** [comment]
We improved it in 2.6.
So just need to update.

**Comment by w00tw00t111** [comment]
Great!
