### ISSUE TITLE
Woocommerce message position

### ISSUE THREAD

**Issue by lutrov** [woothemes/woocommerce#11825]
Why does the Woocommerce settings screen put message boxes under the tabs? This is contrary to the Wordpress standard of putting them above the tabs and under the page heading.

![woocommerce-standard](https://cloud.githubusercontent.com/assets/11863829/18151865/a2386df2-7035-11e6-95fe-62a358ab3e7c.png)

![wordpress-standard](https://cloud.githubusercontent.com/assets/11863829/18151872/adb43a12-7035-11e6-97e9-fb2cc3133985.png)

I realise that the Woocommerce designers have deliberately chosen not to print page headers but why aren't message boxes at the top of the page, as is the common practice?

**Comment by mikejolley** [comment]
There is no standard or guideline for this I could find. WP moves those notices below the h2 - in our case, the tab also serves as the heading for the page, so placement makes sense to me.

**Comment by lutrov** [comment]
No, that's incorrect. WP puts them below the H1, not H2. Below the H2 would make no sense at all, as you can see if you look at any of the standard screens, like users, for instance.

**Comment by mikejolley** [comment]
Ok, fine h1. Same deal.
