### ISSUE TITLE
Displaying categories gallery style on the shop page

### ISSUE THREAD

**Issue by ajames05** [woothemes/woocommerce#11828]
## EXPLANATION OF THE ISSUE

Ive tried changing the settings in settings > products > display > Shop Page Display to 'Show Categories' and im not getting the gallery style display with categories displaying side by side. Instead mine are showing in a list. Any ideas ?﻿

## STEPS TO REPRODUCE THE ISSUE

Go to settings > products > display > Shop Page Display and set to 'Show Categories' 

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://xtremejetskifishing.agwebdesign.com.au
Site URL: http://xtremejetskifishing.agwebdesign.com.au
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (24) ###

Admin Menu Editor Pro: by Janis Elsts – 2.4.1
Akismet: by Automattic – 3.1.11
All In One SEO Pack: by Michael Torbert – 2.3.9.1
Black Studio TinyMCE Widget: by Black Studio – 2.2.11
Easy Google Fonts: by Titanium Themes – 1.4.1
Huge IT Image Gallery: by Huge-IT – 1.9.65
CDN-Powered NextGEN Galleries with Jetpack Photon: by Erick Hitter – 0.2
Jetpack by WordPress.com: by Automattic – 4.2.2
Livemesh SiteOrigin Widgets: by Livemesh – 1.4.3
NextGEN Gallery Optimizer: by Helpful Media – 2.1.4
NextGEN Gallery: by Imagely – 2.1.50
Page Builder by SiteOrigin: by SiteOrigin – 2.4.13
Smart Manager: by Store Apps – 3.9.18
Smart Slider 3: by Nextend – 3.0.35
SiteOrigin Widgets Bundle: by SiteOrigin – 1.6.5
NextScripts: Social Networks Auto-Poster: by NextScripts – 3.6.10
TinyMCE Advanced: by Andrew Ozz – 4.4.1
WooCommerce Widget Product Slider LITE: by A3 Revolution – 1.4.2
Booster for WooCommerce: by Algoritmika Ltd – 2.5.5
Woocommerce Login / Signup Lite: by phoeniixx – 1.4.10
WooCommerce Product Sort and Display LITE: by A3 Revolution – 1.7.0
WooCommerce: by WooThemes – 2.6.4
WordPress Toolbar Editor: by Janis Elsts – 1.2.1
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.3.3

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Sparkling
Version: 2.2.2
Author URL: http://colorlib.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
````

<!--
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
-->

**Comment by mikejolley** [comment]
You are using a plugin which groups by category it seems. This is changing the layout and breaking styling. Not a core bug.
