### ISSUE TITLE
wp_remote_get() failed. The WooCommerce plugin updater won't work with your server.

### ISSUE THREAD

**Issue by lightlycooked** [woothemes/woocommerce#11822]
## EXPLANATION OF THE ISSUE

I installed the latest version of WooCommerce on a fresh install of Wordpress and I'm getting the following error:

**wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received**

I've scoured the net and the issues of this repository and haven't been able to find a solve. I've also contacted my hosting company and they have no idea why I would we experiencing this error.

Any help would be greatly appreciated.

### WordPress Environment ###

Home URL: http://flyandsick.com
Site URL: http://flyandsick.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: 5.6.18
PHP Post Max Size: 60 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (2) ###

WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Twelve
Version: 2.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Not an issue with WooCommerce core, since the "WooCommerce plugin updater" is part of premium plugins.

So you should contact the support in https://woocommerce.com/my-account/create-a-ticket/

```
wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

And as the message said "Contact your hosting provider".

**Comment by AlvinAdbox** [comment]
Hi, May i know how to solve the error, 

**The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /home/adboxadvertising/public_html/ABB-online/wp-content/uploads/GeoIP.dat. Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"**
