### ISSUE TITLE
Feature Request: Support upload field type in settings API

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#11830]
Should be easy enough to launch the media window and save the selected item in a hidden text input. Along the same lines, maybe allow for any kind of custom field type because right now the [`generate_settings_html()`](https://github.com/woothemes/woocommerce/blob/1b2df3dd3b02e836286b899f858687e33fc0d5aa/includes/abstracts/abstract-wc-settings-api.php#L280) method is only looking at defined methods in the settings abstract and reverting anything else to a text input.

**Comment by mikejolley** [comment]
Will review #11831
