### ISSUE TITLE
Display attribute on frontend not load correct and not on order 

### ISSUE THREAD

**Issue by diventimage** [woothemes/woocommerce#11834]
## EXPLANATION OF THE ISSUE

Hello have a website with a lot of attribute and variable. I have a problem with some product.

If i save and create combination, the value of attribute. If i go on code page i see correct all values and attribute (image http://imgur.com/a/NdzJC ) but if i go on front-end not load correct all values (image http://imgur.com/a/QaX6F ).

All variations exist (here image on variations screenshot http://imgur.com/a/QcnFu ). I’ve just write above that i’ve just try to swich into defoult theme (Twenty Sixteen and also StoreFront) and disable all plugin but nothing change. Problme remain so is not any conflict.

Image with Twenty Sixteen http://imgur.com/a/pxNFk

I create a defoult combination http://imgur.com/a/HWCMj and in this case not work selection on attribute on front-end. If i not put any value on defoult combination if i select one value of first attribute (in my case “Supporto”) and then select value on last atribute (in my case “Composizione Plastificazione”) is not possible to retour on last select on first attribute “Supporto”.

Is very very strange. I have six attributes and are positioned in order. It seems that no interpreters woocommerce order and instead bring up the combination based on what I select in the attribute ordered at No. 3 to do it based on what I select with the number 5 attribute.

So is very very strange. I also try do downgrade version WordPress and WooCommerce (on localhost website) but nothing change.

I not be able to use my website becouse is not possibile to select the real variaiton combination. 

`
### WordPress Environment ###

Home URL: http://www.diventimage.com/clicktoprint
Site URL: http://www.diventimage.com/clicktoprint
WC Version: 2.6.2
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (12) ###

Advanced Custom Fields: by Elliot Condon – 4.4.8
bxSlider integration for WordPress: by MarvinLabs – 1.7.2
Contact Form 7: by Takayuki Miyoshi – 4.5
Meteor Slides: by Josh Leuze – 1.5.6
WooCommerce jQuery Cookie Fix: by Splashing Pixels (Roy Ho) – 1.0
WooCommerce MailChimp: by Adam Anderly – 1.3.7
WooCommerce Sequential Order Numbers: by SkyVerge – 1.7.0
WooCommerce: by WooThemes – 2.6.2
Yoast SEO: by Team Yoast – 3.4.2
YITH WooCommerce Badge Management: by YITHEMES – 1.2.9

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /negozio/
Cart: #5 - /carrello/
Checkout: #6 - /checkout/
My Account: #7 - /mio-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Without seeing all the data I cannot say for certain, but I'd expect your 750 variations have no price or are not in stock. Without that, the options will not be displayed.
