### ISSUE TITLE
Reports are not showing correct Sum

### ISSUE THREAD

**Issue by Mashenka** [woothemes/woocommerce#11838]
## EXPLANATION OF THE ISSUE

Woo version 2.6.1

In  period which I'm choosing in REPORTS it shows me some odd sales.(I have counted manually) 
While investigating the reason I found that refund which was done using PayPal IPN is still showing as sale for this day.

Order was marked as refunded
Was trying to update order manually to be sure it is refunded, but no change.

Here is how it shows in reports (refunded 0 orders but 1 item) - http://screencast.com/t/YfTadyO34md

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://www.usabilitydynamics.com
Site URL: https://www.usabilitydynamics.com
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: ✔
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.9.4
PHP Version: ❌ 5.5.33-1+deb.sury.org~trusty+1 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (24) ###

Akismet: by Automattic – 3.1.11
Black Studio TinyMCE Widget: by Black Studio – 2.2.10
Google Analytics by MonsterInsights: by MonsterInsights – 5.5
HookPress: by mitcho (Michael Yoshitaka Erlewine) – 1.14
Nav Menu Images: by Milan Dinić – 3.3
Redirection: by John Godley – 2.4.5
Simple History: by Pär Thernström – 2.7.3
Page Builder by SiteOrigin: by SiteOrigin – 2.4.9
SiteOrigin Widgets Bundle: by SiteOrigin – 1.6.1
TablePress: by Tobias Bäthge – 1.7
WooCommerce API Manager: by Todd Lahman LLC – 1.3.9.3
WooCommerce Authorize.net CIM Gateway: by WooThemes / SkyVerge – 2.0.2 – 2.3.2 is available
WooCommerce Product Bundles: by WooThemes – 4.11.3 – 4.14.7 is available
WooCommerce Subscriptions: by Prospress Inc. – 1.5.30 – 2.0.19 is available
WooCommerce UsabilityDynamics: by Usability Dynamics
Inc. – 1.1.0

WooCommerce: by WooThemes – 2.6.1
Yoast SEO: by Team Yoast – 3.3.2
WP-Cloud: Navbar: by wpCloud.io – 0.5.0
WP-CRM: by Usability Dynamics
Inc. – 1.0.5

WP Crontrol: by John Blackbourn & Edward Dale – 1.3
GitHub Wiki: by Usability Dynamics
Inc. – 1.9.0

WP-Invoice: Power Tools: by Usability Dynamics
Inc. – 2.0.1

WP-Invoice: by Usability Dynamics
Inc. – 4.1.2

wpMandrill: by Mandrill – 1.33
Meta Box: by Rilwis – 4.8.7
WP-Network: by Usability Dynamics – 0.2.1
Simple History: by Pär Thernström – 2.7.3
WP Upstream: by Usability Dynamics Inc. – 0.1.6
WP-Stateless: by Usability Dynamics
Inc. – 1.9.0

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #196092 - /products
Cart: #195003 - /cart
Checkout: #195008 - /checkout
My Account: #194480 - /account

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Kiwi v1.0
Version: 0.2.0
Author URL: http://UsabilityDynamics.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: wp-kiwi-v1.0/woocommerce/cart/cart-empty.php
wp-kiwi-v1.0/woocommerce/cart/cart-item-data.php
wp-kiwi-v1.0/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/cart/cart-totals.php
wp-kiwi-v1.0/woocommerce/cart/cart.php
wp-kiwi-v1.0/woocommerce/cart/cross-sells.php
wp-kiwi-v1.0/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/cart/shipping-calculator.php
wp-kiwi-v1.0/woocommerce/checkout/cart-errors.php
wp-kiwi-v1.0/woocommerce/checkout/form-billing.php
wp-kiwi-v1.0/woocommerce/checkout/form-checkout.php
wp-kiwi-v1.0/woocommerce/checkout/form-coupon.php
wp-kiwi-v1.0/woocommerce/checkout/form-login.php
wp-kiwi-v1.0/woocommerce/checkout/form-pay.php version 1.6.4 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/checkout/form-shipping.php
wp-kiwi-v1.0/woocommerce/checkout/payment.php version 2.3.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/checkout/review-order.php
wp-kiwi-v1.0/woocommerce/checkout/thankyou.php
wp-kiwi-v1.0/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 2.6.1
wp-kiwi-v1.0/woocommerce/emails/admin-cancelled-order.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/customer-invoice.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/customer-new-account.php
wp-kiwi-v1.0/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/customer-processing-order.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/emails/customer-reset-password.php
wp-kiwi-v1.0/woocommerce/emails/email-styles.php
wp-kiwi-v1.0/woocommerce/global/form-login.php
wp-kiwi-v1.0/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/woocommerce/loop/loop-end.php
wp-kiwi-v1.0/woocommerce/loop/loop-start.php
wp-kiwi-v1.0/woocommerce/loop/price.php
wp-kiwi-v1.0/woocommerce/loop/sale-flash.php
wp-kiwi-v1.0/woocommerce/myaccount/form-edit-account.php version 2.2.7 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/form-edit-address.php version 2.1.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/form-lost-password.php version 2.3.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/my-account.php version 2.0.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/myaccount/view-order.php version 2.2.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/notices/error.php
wp-kiwi-v1.0/woocommerce/notices/notice.php
wp-kiwi-v1.0/woocommerce/notices/success.php
wp-kiwi-v1.0/woocommerce/order/order-details.php version 2.4.0 is out of date. The core version is 2.6.0
wp-kiwi-v1.0/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 2.5.0
wp-kiwi-v1.0/single-product.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
It's hard to debug or look at this issue since I don't have your data. When it says something like 0 orders, 1 item, thats a partial refund inside one of the orders in the range. Look through the orders on that date for it.

Post back if you can repeat the issue and I'll try on my store.

**Comment by Mashenka** [comment]
You can test that by doing refund via PayPal and see how it will influence on sales report. Refund was done fully, that wasn't partial refund.

If you need more data or screenshots from my side just let me know what you need.

**Comment by mikejolley** [comment]
It shouldn't matter where the refund originated because the system is the same.

Our of interest, if you save the order, does the report change?

**Comment by Mashenka** [comment]
No, I have tried to re-save the order which was refunded automatically via PayPal IPN. The same thing.

When someone request refund for credit card purchases we do them manually(mark order as refunded and Update) and they are not showing in sales report. But when I do refund via PayPal it is updating using IPN and automatically become refunded. (As I mentioned I have also tried to update the order manually but that didn't help)

**Comment by mikejolley** [comment]
Can you screenshot that order? Hide personal details.

**Comment by Mashenka** [comment]
http://screencast.com/t/cNaMErdo8
http://screencast.com/t/UoA4BYEi8

**Comment by Mashenka** [comment]
Some more details. It showing as sale for 19 August. Refund was done on 23 August. 
With manual refunds do not have such issue.

**Comment by mikejolley** [comment]
Managed to replicate by refunding the order, not the items.

**Comment by Mashenka** [comment]
can you explain that? If in order only one item and I do refund via PayPal where is the difference between refunding the order and the items?

**Comment by mikejolley** [comment]
It should be showing refunds when performed and not affecting past reports. Only the count is incorrect.

**Comment by Mashenka** [comment]
Sale was on 19 August, refund on 23 August. But the order is the same. And it shouldn't show in report odd amount of money if the order was refunded. 

Don't you agree with me?

E.g if we create our sales reports every week, we can't use your Reports because of this issue.

**Comment by mikejolley** [comment]
If you report on 19, it will show as sale. 

if you report on 23, it will show as negative sale.

If you report on 19-23, it will show 0 amount.

The counts are wrong. This is what I'm patching.

**Comment by silicondales** [comment]
Hi @mikejolley (this is not a me too - well it kind of is but please don't shoot me!).

I am trying to work through issues like this with 1 client who came along experiencing just this. I'm not yet sure where their refund issue stems from, but it follows a similar pattern to the above, hence I am querying on this issue rather than posting anything further (we still have a question mark over hosting and data).

Issue experienced is similar in many respects to the above, except gateway is PayPal Pro. Refunds mark as below in reports:

![refunds-not-showing](https://cloud.githubusercontent.com/assets/17259256/19030932/e54c1cac-8948-11e6-84f5-81bb68432258.jpg)

This is a report for September. There is 1 order totally refunded via PayPal Pro, which is correctly marked as far as I can tell:

![refunded-order-example-sept-2016](https://cloud.githubusercontent.com/assets/17259256/19030965/25a40e5e-8949-11e6-8049-3c6bd8b73bde.jpg)

Is this in the same ball park - or am I in the wrong issue here?

**Comment by silicondales** [comment]
Note client is on the latest version of everything, and has been suffering this refund report issue for some time (though is new to me, hence I'm tenatively posting this here).
