### ISSUE TITLE
Sold Individual bug possibly found? Quantity remains 1 but total still increases.

### ISSUE THREAD

**Issue by seb86** [woothemes/woocommerce#11844]
## EXPLANATION OF THE ISSUE

WooCommerce v2.6.4

If a product has been set to only allow one of the item to be bought in a single order and you have added it to the cart, the product page reloads (unless redirected) and notifies the customer that the product has been added to the cart.

However, you are still allowed to add the item to the cart again via the "Add to Cart" button.

After adding the item the second time and go to the cart page, you will see that the quantity of the item still appears as **1** but the total price of that item is double the amount or more depending on how many times it was added.

I think this is wrong. Not only will the customer think they are being charged for the item only once with a higher price but the order will also think you are shipping only 1 of that item.

If the customer attempts to add the item again should they not get a notification to say it has already been added to the cart and are only allowed one per order instead, rather than adding an additional quantity to the cart?

**Comment by hemnathmouli** [comment]
But it must say `You cannot add that amount to the cart — we have 1 in stock and you already have 1 in your cart.`

**Comment by seb86** [comment]
@hemnathmouli Well, the quantity field does not show when this option is enabled on the product so saying you cannot add that amount sounds funny.

`You have already added this item to the cart. Only one of this item can be purchased per order.`

This message could also be filterable allowing developers to display an alternative message depending on further conditions.

**Comment by mikejolley** [comment]
All messages are filterable via gettext.

The actual bug doesn't occur. The 2nd add to cart is prevented by the notice @hemnathmouli said about. Only 1 can be added to the cart at once. Validation stops all others.

**Comment by seb86** [comment]
@mikejolley What version of WooCommerce is this applied in because I did not get that notice.

**Comment by mikejolley** [comment]
It's been there since implementation...

testing on 2.6.x and master
