### ISSUE TITLE
[API] v3-legacy: define primary category when assigning multiple categories

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#11840]
hi,

in WordPress backend it's possible to assign multiple categories to a product whereas it's possible to define one of these as primary.

How is this done via API? It's not documented anywhere.

Cheers,
Adis

**Comment by WPprodigy** [comment]
WordPress doesn't allow you to set one as primary, that is likely coming from another plugin like Yoast SEO.
