### ISSUE TITLE
Conflict between WooCommerce and NexGEN Gallery

### ISSUE THREAD

**Issue by Suenee** [woothemes/woocommerce#11847]
## EXPLANATION OF THE ISSUE

The problem is on woocomerce checkout site: http://www.spontannibubnovani.cz/obchod/checkout/ when you order something from eshop and you want click on "Objednat" (=Order)... it is not possible if NextGEN Gallery plugin is activated. When I disable NextGEN Gallery plugin, woocomerce works well.
I use last verison of both plugins - woocommerce too and NextGEN Gallery too.

## STEPS TO REPRODUCE THE ISSUE

1. activate woocommerce and setup eshop
2. activete nextgen gallery and setup
3. pickup something from eshop
4. try to finish ORDER

### WordPress Environment ###

Home URL: http://www.spontannibubnovani.cz
Site URL: http://www.spontannibubnovani.cz
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Microsoft-IIS/7.5
PHP Version: ❌ 5.5.8 - Doporučujeme PHP minimálně ve verzi 5.6. Více: Jak aktualizovat verzi PHP
PHP Post Max Size: 80 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.30.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.46 - Minimální doporučená verze MYSQL je 5.6. Více: Požadavky Wordpressu
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Vzdálená metoda Post: ✔
Vzdálená metoda Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (37) ###

Add Linked Images To Gallery: o Randy Hunt – 1.4
Share Buttons by AddThis: o The AddThis Team – 5.3.3
Akismet: o Automattic – 3.1.11
All-in-One Event Calendar od Time.ly: o Time.ly Network Inc. – 2.5.10
Auto Tag Links: o SEO Roma by PMI Servizi – 1.0.6
Automatic Post Tagger: o Devtard – 1.8.2
BAW Post Views Count: o Juliobox – 2.19.11
Captcha by BestWebSoft: o BestWebSoft – 4.2.4
Co-Authors Plus: o Mohammad Jangda
Daniel Bachhuber
Automattic – 3.2.1

Comment Disable Master: o Shamim Hasnath – 1.0
Contact Form 7: o Takayuki Miyoshi – 4.5
Cool Video Gallery: o Praveen Rajan – 2.3
Facebook Comments Plugin: o talspotim – 2.3.6
File Gallery: o Bruno "Aesqe" Babic – 1.8.5.2
Google Analytics: o DrSoto – 3.0
Meta Slider: o Matcha Labs – 3.3.7
New Facebook Popup Like Box (Responsive): o Krishna Sharma (DoNotTraceME) – 2.00
Platinum SEO Pack: o Rajesh - Techblissonline Dot Com – 1.3.8
prettyPhoto Media: o binaryhideout – 1.4
Redirection: o John Godley – 2.4.5
Related Posts via Taxonomies: o alphasis – 1.0.1
Rich Text Tags, Categories, and Taxonomies: o Katz Web Services
Inc. – 1.8

RSS Image Feed: o Stefan Crämer – 4.2.5
RSS Thumbnail: o Sueneé – 1.0
Search Meter: o Bennett McElwee – 2.12
Simple Breaks: o Hit Reach – 3.0.0
Simple Local Avatars: o Jake Goldman
10up – 2.0

Sitemap Generator WP: o Danilo Andreini – 1.08
NextScripts: Social Networks Auto-Poster: o NextScripts – 3.6.10
TinyMCE Advanced: o Andrew Ozz – 4.4.1
WooCommerce: o WooThemes – 2.6.4
Yoast SEO: o Team Yoast – 3.4.2
WP Facebook Open Graph protocol: o Chuck Reynolds – 2.0.13
WP OpenSearch: o Fabio Savina – 1.0
WP-Optimize: o Ruhani Rabin – 1.9.1
WP-UserOnline: o Lester 'GaMerZ' Chan – 2.87
MailPoet Newsletters: o MailPoet – 2.7.5

### Settings ###

Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Sídlo obchodu: #1139 - /obchod/
Košík: #1140 - /obchod/cart/
Pokladna: #1141 - /obchod/checkout/
Můj účet: #1142 - /obchod/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Spontanni bubnovani
Version: 1.0
Author URL: 
Child Theme: ❌ – Pokud upravujete WooCommerce
nebo rodičovskou šablonu
kterou jste nevytvořili
doporučujeme použít child šablonu. Viz. Jak vytvořit child šablonu

WooCommerce Support: ❌ Podpora neuvedena

### Templates ###

Overrides: Vaše šablona obsahuje soubor woocommerce.php. Nebudete schopni přepsat vlastní šablonu woocommerce/archive-product.php
protože woocommerce.php má vyšší prioritu než archive-product.php. Je to z důvodu předcházení problémům se zobrazením.

Overrides: –

**Comment by mikejolley** [comment]
I installed NextGen 2.1.50 and had no issues. It sounds like a JS error anyway. Open view > developer > javascript console and see what is thrown on checkout. That will tell you which nextgen script is breaking it.
