### ISSUE TITLE
WC_Post_Data::sync_product_stock_status() ignores products

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#11852]
## EXPLANATION OF THE ISSUE

If another plugin registers a custom post type and tries to set the `_stock` post meta field for a post of that type, and if WooCommerce is also running, a fatal error can result.

## STEPS 

* Third party code calls `update_post_meta()` to set `_stock` for a non-product
* The corresponding action fires and one of the callbacks is `WC_Post_Data::sync_product_stock_status()`
* This method checks if the meta key is `'_stock'` (it is!) and checks if the post type is *not* a `'product'` (it isn't!)
* It then tries to load the product object and attempts to call it's `check_stock_status()` method

The problem is that loading the product object fails, because we're not looking at a WooCommerce product, so we end up trying to call a method on a non-object.

**Comment by mikejolley** [comment]
The fix wasn't quite right. We don't sync products, but variations, hence your PR is breaking.

**Comment by franticpsyx** [comment]
@mikejolley - Why does this "safety net" hook exist for variations but not for products?

**Comment by barryhughes** [comment]
Thanks @mikejolley!

I did wonder the same as @franticpsyx ... looking back at [this PR](https://github.com/woothemes/woocommerce/issues/8605) it didn't seem like the intent was to target variations only?
