### ISSUE TITLE
abstract order class should offer ability to remove payment tokens

### ISSUE THREAD

**Issue by rsouthgate** [woothemes/woocommerce#11857]
## EXPLANATION OF THE ISSUE

The class allows gateways to add payment tokens to an order. Useful for subscriptions which can then use the token on recurring payments. However it offers no way of removing tokens from the order which means, in the subscriptions example - multiple payment tokens associated with the same subscription.

## STEPS TO REPRODUCE THE ISSUE

(Steps specific to subscriptions but issue still belongs with core as I believe the abstract should offer the method)

Create a subscription.
Under "My account" -> Subscriptions, Update payment info for subscription. (Uses same process payment flow as standard checkout, instead of the add payment method which might make more sense)

Gateways then adds a second token to the subscription.

This probably will open up a discussion on whether susbcriptions is doing the right thing here, but I am curious as to why the abstract offers an "add_payment_token" method without a "remove_payment_token" method.

**Comment by mikejolley** [comment]
The token itself is an object. You get it's ID on create, and you can retrieve them all from the order.

Once you have the token, call `$token->delete()` and you're done. If this was in the order it would just be a helper to use this so I don't see much benefit in adding it.

**Comment by rsouthgate** [comment]
Well that's what I tried, but in this instance, making use of the ability to save credit cards to the users account and add the same token to the subscription then if you use the token->delete method it actually removes the same saved card token, so if a user desires to update the payment method on a subscription but not affect that same saved card related to other subscriptions then deleting the token is not an option, which is why I thought a remove method would be useful.. (rather than directly manipulating the post meta)
