### ISSUE TITLE
WC Login Cookie Error

### ISSUE THREAD

**Issue by nhadsall** [woothemes/woocommerce#11854]
## EXPLANATION OF THE ISSUE
Users cannot login under certain conditions.

## STEPS TO REPRODUCE THE ISSUE
1. The expiration for the WC session cookie was extended, but the WP session cookie was left with the default. 
2. As a result, any browser with a WC session cookie, but no WP session cookie cannot login through the my-account page.

**Comment by mikejolley** [comment]
To attempt this I just deleted my wp_logged_in cookie and logged in from account page. Worked fine. I don't see why our cookie would break anything - it's not used in the login process. Sounds like a caching config problem on your server due to it's presence.
