### ISSUE TITLE
generate all variations is slow

### ISSUE THREAD

**Issue by lalop** [woothemes/woocommerce#11851]
I use woocomerce version 2.6.4, and I have some issue while generating variations.
I have more than 800 variations for a product and when I have to add a new attribute generating the new variation is really slow.

Trying to understand why I logged sql queries executed during this process and I find that when wp_insert_post is called (https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-ajax.php#L939) one request is made for each previous variations

```
SELECT post_name FROM wp_posts WHERE post_name = 'product-1686-variation-4' AND post_type = 'product_variation' AND ID != 0 LIMIT 1
```

I didn't go deeper so I imagine this is used to compute the variation id but for a big number of variation this isn't really efficient.
Couldn't we get this id in an other way ? via the number of children or a post meta for exemple ?

**Comment by claudiosmweb** [comment]
We need to use `wp_insert_post()`, since we need to create a post on WordPress for each product.
That's why we create it using ajax, because take time, but still a WordPress issue.

**Comment by lalop** [comment]
@claudiosan I completely understand why you use wp_insert_post and it makes sense, why I don't understand it's why to create the 800th variations we have to request the 799 firsts ones

**Comment by lalop** [comment]
Do you see what I mean  ?
