### ISSUE TITLE
CURL API Response works, others do not

### ISSUE THREAD

**Issue by chipoglesby** [woothemes/woocommerce#11856]
## EXPLANATION OF THE ISSUE

using a curl command, I am able to get paginated results as expected. Example:
````
curl -X GET -H "Authorization: Basic xxx" "https://mysite.com/wp-json/wc/v1/orders?page=2"
````
When I try to call the same results using Google Apps Scripts, I get a 401 response. Example:
````
function wooCommerce() {
    api = 'https://mysite.com';
    options = {"headers": {"Authorization": 'Basic xxx'}};
    // this works orders = '/wp-json/wc/v1/orders';
    orders = '/wp-json/wc/v1/orders?page=2';
    apiCall = UrlFetchApp.fetch(api+orders,options);
    var json = JSON.parse(apiCall.getContentText());
    Logger.log(json)
  }
}
````

I think there may be a bug because I've built other calls to API's with the exact same method and they seem to be working fine. I also tried this with a different variation using a POST method, but it was only returning one result at a time.

**Comment by mikejolley** [comment]
The current stable version (2.6.4) doesn't fully support authorization headers. It needs to use querystring. See the auth section in https://woothemes.github.io/woocommerce-rest-api-docs/

401 response will be thrown if the user is not authenticated. The above requests work fine for me in master/2.6.5. Confirmed using my REST client.

Additional; if you do use querystring, remember 'page' would need to become part of your signature generation to work.

**Comment by chipoglesby** [comment]
So in the documentation:

[Authentication over HTTPS](https://woothemes.github.io/woocommerce-rest-api-docs/?javascript#authentication-over-https)

`You may use HTTP Basic Auth by providing the REST API Consumer Key as the username and the REST API Consumer Secret as the password.`

This is no longer supported?

**Comment by claudiosmweb** [comment]
@mikejolley we support for headers for Basic Auth you troll!

@chipoglesby don't seems like the authentication is a problem. But I guess is something in your code.
We build several libraries for the REST API, you can test then, all will work with this pagination.
