### ISSUE TITLE
Bug: Woocommerce doesn't pickup Page Style in Paypal

### ISSUE THREAD

**Issue by tonydc1** [woothemes/woocommerce#11863]
I am using Wordpress 4.6 and Woocommerce 2.6.4.
I use Paypal standard.
Under Woocommerce Settings > Checkout > Paypal settings, I have set which Page Style to use.
But it doesn't work, it keeps loading the page style set as Main in Paypal, not any of the others I have created on Paypal.

**Comment by mikejolley** [comment]
Show me what you input into the option, and what you have setup in paypal. WC just sends this with the request; how PayPal handle it is outside of WC control.

**Comment by tonydc1** [comment]
This in attachment is what I have on Woocommerce settings, and what I have
on my CVfolio website admin.
Names of Page Style match, but it picks up the Primary (Trendy) and not the
one set in admin.

What does it mean how Paypal handle it is outside of WC control?
There's an option in there to send the request and probably there's
something wrong. It's not how Paypal handles it but how WC sends the
request.

Unless I am doing something wrong. But I was using WooCommerce PayPal
Express Gateway Version 3.7.0, until a few minutes ago and the Page Style
was pulled fine.

**Comment by tonydc1** [comment]
Sorry I had replied via email and attachments didn't come, attaching here.
![screencapture-cvfolio-wp-admin-admin-php-1473265565220](https://cloud.githubusercontent.com/assets/22057068/18320468/46c8abd6-752a-11e6-9ef5-344da23ce03b.png)
![screencapture-paypal-cgi-bin-customerprofileweb-1473265642613](https://cloud.githubusercontent.com/assets/22057068/18320473/4d781c28-752a-11e6-843e-a0c12d9dff5b.png)

**Comment by tonydc1** [comment]
This is the plugin where the Page Style option works well if you want to check how it's done. Please let me now. [woocommerce-gateway-paypal-express-3.7.2.zip](https://github.com/woothemes/woocommerce/files/461270/woocommerce-gateway-paypal-express-3.7.2.zip)

**Comment by mikejolley** [comment]
Works fine https://dl.dropboxusercontent.com/s/sqd89jw26kmk4al/2016-09-08%20at%2010.28.png?dl=0

> This is the plugin where the Page Style option works well if you want to check how it's done

Make sure you're not adding rules to sandbox for live and vice versa. Contact paypal if stuck. There is no bug here - you can enable logging and confirm page_style is set if you don't want to take my word :)

**Comment by vitalisx** [comment]
There was a change to how paypal handles the page style a few months ago. And the core woocommerce functionality stayed behind.
