### ISSUE TITLE
Wrong sequence of events in waiting for payment?

### ISSUE THREAD

**Issue by UserName011** [woothemes/woocommerce#11867]
![123](https://cloud.githubusercontent.com/assets/22069599/18339104/32427666-75a6-11e6-9aaa-4711969494f5.png)

How does it make sense that on September 7, 2016 at 8:06 pm the status was changed from **Pending** to **canceled** and on September 7, 2016 at 8:46 pm it was changed from **canceled** to **on hold**  ?

Shouldn't it be Pending - > On Hold -> Canceled?

How can the customer restart a canceled order?

**Comment by mikejolley** [comment]
Gateway dependent - it may be that the time limit was reached and THEN the gateway finally updated the order. Customer cannot do this.

**Comment by UserName011** [comment]
So this order is going to be stuck on 'On Hold' forever?

**Comment by mikejolley** [comment]
Orders are put on hold for a reason. The note says you need to review payment.

**Comment by UserName011** [comment]
What is payment review and who triggered this note?

**Comment by mikejolley** [comment]
Your gateway is telling you to check the payment..
