### ISSUE TITLE
Need a hook when login failed

### ISSUE THREAD

**Issue by emehran** [woothemes/woocommerce#11864]
There is no hook that can be used when login fails.  
I recommend adding a hook like what WordPress has :'wp_login_failed'.

It could be added in class-wc-form-handler.php line 931

```
} catch ( Exception $e ) {
	wc_add_notice( apply_filters('login_errors', $e->getMessage() ), 'error' );

}
```

so plugin/theme authors can, for example, redirect users when login failed.

**Comment by mikejolley** [comment]
You just pointed out your own solution; whats wrong with `wp_login_failed`?

**Comment by emehran** [comment]
As WooCommerce has its own wrapper and uses wp_signon. So that action doesn't work.

**Comment by hambos22** [comment]
And how can I catch errors? The `do_action` doesn't have any arguments passed in.

**Comment by 19h47** [comment]
Late to the party, but I had the same problem as @cpouldev and there isn't way to catch message yet.

My solution is to hook into [`login_errors`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L981) to catch message:

```php
$message = '';

add_filter( 'login_errors', 'get_login_error_message' , 10, 1 );

function get_login_error_message( string $message_error ) : string {
	$message_error = $message;

	return $message;
}
```

And then hook into [`woocommerce_login_failed`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L982), add notice and redirect (in this case to `myaccount`):

```php
add_action( 'woocommerce_login_failed', 'redirect_on_login_failed' , 10, 0 );

function redirect_on_login_failed() : void {
        wc_add_notice( $message, 'error' );
        wp_redirect( wp_validate_redirect( wc_get_page_permalink( 'myaccount' ) ) );
        exit;
}


```

**Comment by 19h47** [comment]
Late to the party, but I had the same problem as @cpouldev and there isn't way to catch message yet.

My solution is to hook into [`login_errors`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L981) to catch message:

```php
$message = '';

add_filter( 'login_errors', 'get_login_error_message' , 10, 1 );

function get_login_error_message( string $message_error ) : string {
	$message_error = $message;

	return $message;
}
```

And then hook into [`woocommerce_login_failed`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L982), add notice and redirect (in this case to `myaccount`):

```php
add_action( 'woocommerce_login_failed', 'redirect_on_login_failed' , 10, 0 );

function redirect_on_login_failed() : void {
    // Logout user doesn't have session, we need this to display notices
    if ( ! WC()->session->has_session() ) {
        WC()->session->set_customer_session_cookie( true );
    }
    wp_redirect( wp_validate_redirect( wc_get_page_permalink( 'myaccount' ) ) );
    exit;
}
```
