### ISSUE TITLE
Changing product data metabox classes for custom product type

### ISSUE THREAD

**Issue by Dartui** [woothemes/woocommerce#11861]
## EXPLANATION OF THE ISSUE

I have created new product type. For now there is no way to change classes for elements in product data panels. There is only one filter in which we can change behavior of tabs (`woocommerce_product_data_tabs`), but there are also classes hardcoded inside panels (`<div class="options_group pricing show_if_simple show_if_external hidden">` for example for pricing, which is useful for most of product types I guess). For now I have to change this by jQuery, but I think this should be possible by filters.

## STEPS TO REPRODUCE THE ISSUE

1. Create custom product type
2. Switch product type to new one

**Comment by mikejolley** [comment]
There are no plans to make this filterable - use jquery to change classes. 

The long term goal is to make all panels API driven and/or replace the current meta box system, in which case everything will be filterable and this will no longer be a problem.
