### ISSUE TITLE
API Variation returns sanitize attribute names

### ISSUE THREAD

**Issue by danielhuesken** [woothemes/woocommerce#11868]
In the Rest-API a variation will be return a sanitize attribute name if it is not a global attribute.
If it is a global attribute it gives back the normal name. I think it is better to have the same on both preferred the not sanitize name.

See: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L428

**Comment by danielhuesken** [comment]
I don't thnik that that fixes the problem that you have in one case a sanitized name in in other case not.
In varation atributes the **option** name is sanitized for global attributes.

**Comment by mikejolley** [comment]
This fixes the problem of removing pa on attribute names which never have PA_. Your issue may have not been explained clear enough if thats not it.

**Comment by danielhuesken** [comment]
And now must i open a new one or is the Pull request enough?

**Comment by mikejolley** [comment]
@danielhuesken Would be good to add more explanation to your PR. I cannot tell what you're 'fixing'.

**Comment by danielhuesken** [comment]
OK @mikejolley.

There is a difference on output of global attributes and local product attributes (options field). Global attributes will give back the slug and local attributes the name. I think that should be the same on both. Same for input see #11871

**Comment by mikejolley** [comment]
Then thats not even possible @danielhuesken because local attributes **do not have slugs.**

**Comment by mikejolley** [comment]
I see your suggestion in the other ticket though to lookup from name. That can work. Let me relook at PR.
