### ISSUE TITLE
Displaying variation key field as label instead of name field

### ISSUE THREAD

**Issue by Dartui** [woothemes/woocommerce#11870]
## EXPLANATION OF THE ISSUE

I'm using `woocommerce_get_item_data` filter to add my own data to product in cart. For now, I use it in this way:

```
$item_data['my-variation'] = array(
	'key' => 'my-variation'
	'name' => 'My variation name',
	'value' => 'My variation value',	
);

return $item_data;
```

Everything works great, but I don't understand, why template file `cart/cart-item-data.php` is using `key` field for name of variation instead of `name`. Also after removing `key` field or changing it to `name` field value, `dt` and `dd` tags are getting weird class name, for example `variation-Myvariationname` (because of fallback in `includes/class-wc-cart.php`)

I think that this code in `cart/cart-item-data.php`:
```
<dt class="variation-<?php echo sanitize_html_class( $data['key'] ); ?>"><?php echo wp_kses_post( $data['key'] ); ?>:</dt>
<dd class="variation-<?php echo sanitize_html_class( $data['key'] ); ?>"><?php echo wp_kses_post( wpautop( $data['display'] ) ); ?></dd>
```
should be changed to
```
<dt class="variation-<?php echo sanitize_html_class( $data['key'] ); ?>"><?php echo wp_kses_post( $data['name'] ); ?>:</dt>
<dd class="variation-<?php echo sanitize_html_class( $data['key'] ); ?>"><?php echo wp_kses_post( wpautop( $data['display'] ) ); ?></dd>
```
and in `includes/class-wc-cart.php` should be created fallback for empty `name`, like now for empty `key` field or something like this:
`$item_data[ $key ]['name']     = ! empty( $data['name'] ) ? $data['name'] : $data['key'];`

I know that I can override this template file, but shouldn't it be default behavior?

**Comment by mikejolley** [comment]
Name appears to be legacy. It is not handled any differently from what I can see. Correct me if I'm wrong, but it looks like KEY is the only field we handle, display, use, and store.

**Comment by Dartui** [comment]
It looks that you are right, I can't find any other place where `name` field is used so it must be legacy. However what do you think about changing it a bit, because even variations use taxonomy name as key. For short attribute name it is good (variation-Size for example, note that name of taxonomy starts from uppercase), but longer with spaces looks weird, because of `sanitize_html_class` which remove spaces (variation-Sizeofboots for example). `sanitize_html_class` also remove all diacritics, so for my shop which is dedicated to customers from Poland I can do two things:

- name taxonomy in English, but this could be weird for customers
- name taxonomy in Polish, which will be good for customers, but then class names will be weird for developers (for example Placówka, which means Place, became variation-Placwka)

For this case I will suggest using taxonomy slug as key (by default term slugs has changed spaces to semicolons, uppercases to lowercases and diacritics to similar chars, so Placówka became variation-placowka and Size of boots became variation-size-of-boots) and taxonomy name as variation/attribute name

**Comment by mikejolley** [comment]
We can only store name value pairs so it does not make sense to use both on cart.

**Comment by Dartui** [comment]
So we can store term slug => value and on cart page get it name by `get_term_by('slug', ...)` to show term name as label for variation

**Comment by Dartui** [comment]
My bad, variations are stored in pairs term slug => value, so it is good. There is only one thins to change in this loop: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L591.
I will create PR so you could look at it and see my proposal
