### ISSUE TITLE
When is widget cache invalidated?

### ISSUE THREAD

**Issue by webaware** [woothemes/woocommerce#11884]
I notice that the output of some of the WooCommerce widgets are now cached, if WordPress has a persistent object cache (e.g. memcached). I admit that I hadn't been paying attention to this, until I saw widgets on the cart page on a website where that page can be loaded either http or https -- triggering insecure content errors. I'm using the `woocommerce_cached_widget_id` to get around the insecure content problem, but that makes me ask:

How do these caches get invalidated? I looked and couldn't easily find where that happens apart from someone editing a widget in the WP admin. What happens when products are added / edited / deleted, and the widgets should adjust to show new content?

If there is a way to invalidate a widget cache, triggering a call to `WC_Widget::flush_widget_cache()`, I can't see how that will clear secondary caches saved by filtering `woocommerce_cached_widget_id` -- e.g. in my situation where I'm adding a cache for https views, or for WPML language overrides as in the case that created that filter hook.

A suggestion: when something happens that causes the product transients to be cleared, perhaps change the widget cache group so that all widgets are regenerated. That requires two steps:

1. generate the widget cache group with `uniqid()` or something else based on `microtime()`, and save it in the cache
2. hook `woocommerce_delete_product_transients` (at minimum) and delete the saved widget cache group

**Comment by mikejolley** [comment]
Saving posts, switching themes, and updating the widget options. This is not a transient. It's WP_CACHE

**Comment by webaware** [comment]
OK, I see what's going on now.

When there's _only one instance of a widget_, then the widget is cached and is flushed on those actions (`save_post`, `deleted_post`, `switch_theme`). That's basically what I was asking. So we're part-way there now.

However: if anyone filters `woocommerce_cached_widget_id` to create separate caches for whatever reason (e.g. WPML language config), then only one version of the widget's cache is flushed. The other versions are probably never flushed, until invalidated some other way such as a full wp_cache flush (which some systems disable); a reboot; or being pushed out when the cache reclaims memory for fresh items.

So again: I suggest that invalidating the widget caches would be simpler if you generated a time-based cache group, and renewed it when flushing. That will cater for multiple versions of the widget caches. You can also hook those invalidating actions statically, once, within the abstract widget class and flush just once.

Additionally, the widget cache currently only works when there is _only one instance_ of a widget. If you have multiple instances, then the cache `get_cached_widget()` will get lots of misses and will return false, forcing the widget to render anyway -- and call `wp_cache_set()` again. In other words, with multiple instances of a widget, there is increased load, not reduced load, through multiple fruitless calls to both `wp_cache_get()` and `wp_cache_set()`. 

(Example of multiple instances: Products widget, one for new products, one for featured products)

**Comment by webaware** [comment]
Just remembered something else. The reason I suggested hooking it to the `woocommerce_delete_product_transients` action is that it then fires whenever a WooCommerce product is saved or deleted. This is a little more targeted than hooking `save_post` and `deleted_post` because it ignores any changes to posts, pages, media, and other non-WooCommerce post types. Hooking it to `switch_theme` is still a good idea though.
