### ISSUE TITLE
Query by Date Modified Range

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#11888]
Hi,

How do I pull a list of orders using the date_modified field?

https://woothemes.github.io/woocommerce-rest-api-docs/#list-all-orders

Select all orders where date_modified > January 1st and date_modified < January 30th?

I see you have a parameter called filter. How do I use it with this API? Can you send me a URL?

**Comment by claudiosmweb** [comment]
![screenshot from 2016-09-10 01-16-33](https://cloud.githubusercontent.com/assets/1264099/18407899/564d09f0-76f4-11e6-9927-ca683fc534ad.png)

And do not forget about:

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- **GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:**
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://support.woothemes.com for premium plugin support
```

**Comment by ambro23** [comment]
Actually, after and before filter parameters work on date_created field and not on date_modified.

**Comment by mikejolley** [comment]
The API is extendable if you need to filter by other props. Date created = published date. I don't think it makes sense to add new filters for modified date at this point - we are working on more search params for future releases though.

**Comment by mikejolley** [comment]
Also, avoid `filter`. It's deprecated in WP Rest API.

**Comment by ambro23** [comment]
Well, it would have helped us at least... I might be missing something, bug as far as I know, currently it is not possible to query orders modified eg. today without paging through all orders. Neither filtering, nor ordering works on the date_modified field (but date_created).

**Comment by steffanhalv** [comment]
@mikejolley Its soon been a year and I think this is still relevant..

F.ex. now I need to delete all prods not modified in x days for a customer regulary as a cron job which is using the rest api

**Comment by mikejolley** [comment]
Presumably if you're consuming the API you're developers, so if you want to make sure it gets added, you can contribute here: https://github.com/woocommerce/wc-api-dev
