### ISSUE TITLE
can i know the context inside woocommerce_add_to_cart_validation?

### ISSUE THREAD

**Issue by gine** [woothemes/woocommerce#11881]
Inside my function on the woocommerce_add_to_cart_validation hook i can't know in the context where i am. Every function(is_cart() is_checkout()) to know the context return false. 

I want know this information to modify notice message. Is it a bug or i am in the wrong direction?

## STEPS TO REPRODUCE THE ISSUE

```
add_action( 'woocommerce_add_to_cart_validation', 'add_to_cart_validation', 5, 6 );

function add_to_cart_validation(){
  if(is_cart()){
    wc_notice_add('cart');
  } else if(is_product()){
    wc_notice_add('product');
  }
}
```

**Comment by mikejolley** [comment]
Not really possible - you're not on cart or product if it's an ajax request. Plus the call is likely too early. Not something we can support right now.
