### ISSUE TITLE
I need help with webhook using ssl

### ISSUE THREAD

**Issue by sicarpv** [woothemes/woocommerce#11880]
## EXPLANATION OF THE ISSUE

I have a woocommerce and recently change http to https and after change the services webhook not working, not save any information. I need your help.
Thks.

## STEPS TO REPRODUCE THE ISSUE

When change http to https

## SYSTEM STATUS REPORT

```
All  OK
```

**Comment by claudiosmweb** [comment]
>BEFORE POSTING YOUR ISSUE
> - These comments won't show up when you submit the issue.
> - Try to add as much detail as possible. Be specific!
> - **GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:**
>   - https://wordpress.org/support/plugin/woocommerce for general support
>   - https://support.woothemes.com for premium plugin support
