### ISSUE TITLE
New Shipping Status in Woocommerce

### ISSUE THREAD

**Issue by aftabdev99** [woothemes/woocommerce#11897]
I have a feature request. Please add a new shipping status in woocommerce order.  I  begin to wonder to see this. This feature is not available in woocommerce.

**Comment by UserName011** [comment]
This can be useful.. also a place to enter tracking number per order. It's just a simple text field that can make life much simpler.

**Comment by mikejolley** [comment]
We were thinking about adding a separate order to payment status in the future, but right now with one level of statuses we don't feel it's needed.

Processing = ready to ship
Completed = shipped.

It's just wording. 

> This can be useful.. also a place to enter tracking number per order.

Shipment tracking extension exists.

**Comment by UserName011** [comment]
@mikejolley this isn't always the case. for example sometimes customers order items whom are not in stock and there is a lead time between payment and shipping.

**Comment by galbaras** [comment]
@mikejolley Completed is not always the same as Shipped, e.g. in the case of providing services (virtual products). Personally, I have a store that ships some products and delivers some services, and the meaning of Completed therefore depends on the product.

If I could manually set some products to Shipping, this would also allow me to monitor delivery for a while, and ENSURE good service, not just assume it.

Please reconsider.
