### ISSUE TITLE
Smiley Faces Break Checkout. :) :)

### ISSUE THREAD

**Issue by bentasm1** [woothemes/woocommerce#11891]
## EXPLANATION OF THE ISSUE

Using smiley faces in the product title, such as 😉 will break checkout.

## STEPS TO REPRODUCE THE ISSUE

1.) Create a product.  Lets title it "Smiley! 😉" -- Copy and paste it just like that.

2.) Add product to cart, checkout, any gateway is fine to test with.

3.) Error 525: Unable to create order. Please try again.

4.) Rename product to "Smiley!", omitting the actual emoticon, and reload checkout page.

5.) Success!

## SYSTEM STATUS REPORT

None needed for this issue, bug in all installations

**Comment by mikejolley** [comment]
Must be something else at play here such as plugin, SQL table type or other. I have no such issue on release/2.6 and I know we already fixed the same issue for billing fields with smiles.

https://dl.dropboxusercontent.com/s/anfakus4869hjx8/2016-09-12%20at%2013.05.png?dl=0
