### ISSUE TITLE
Incorrect Example for REST API Coupon calls.

### ISSUE THREAD

**Issue by smithalan92** [woothemes/woocommerce#11894]
Hi there, 

I'm using WC 2.6.4 and WP 4.6.1 , The Rest API I am using should be v1, and I am using the Node Woocommerce module ( v2.2.1)  to interact with the API.

I have noticed 2 issues, with **Create a Coupon**. First in the example POST request params, to specify the discount type ( Percent, fixed etc.. ), it says to use the `discount_type` property. This appears to be incorrect, the correct property to use is `type` , which seems to fall in line with a legacy API version for some reason?

Also in the response to that post request, the sample response is listed as something like
```
{
  "id": 113,
  "code": "10off",
  "date_created": "2016-04-28T21:55:54",
  "date_modified": "2016-04-28T21:55:54",
  "discount_type": "percent",
  "description": "",
  "amount": "10.00"
}
```
The correct format for the response should be something like
```
{ coupon:
   {
     id: 889,
     code: 'chbtaihe',
     type: 'percent',
     created_at: '2016-09-10T01:39:36Z',
     updated_at: '2016-09-10T01:39:36Z',
     amount: '10.00',
   }
}
```

Unless for some reason I am still using a legacy version of the API ( Which I'm not sure how that would be possible as I am using the most recent version of WC) , the latest API docs seem to be incorrect.

**Comment by claudiosmweb** [comment]
You are still using a legacy version of the API.
See: http://woothemes.github.io/woocommerce-rest-api-docs/v3.html#view-a-coupon
