### ISSUE TITLE
Lost languages content using WooCommerce & qTranslate-X

### ISSUE THREAD

**Issue by albertomoral** [woothemes/woocommerce#11892]
Hi, I'm using **qTranslate-X** Versión 3.4.6.8 and **WooCommerce & qTranslate-X** Versión 1.3 plugins in my self hosted WordPress website. 

Calls to WC-JSON Api products endpoints returns only main language content in **description** and **short description** product fields.

Is it the expected behavior or there is a way to get all languages (3) content for this fields?

thanks in advance.

A.

**Comment by claudiosmweb** [comment]
Not an issue on WooCommerce, looks like need to be fixed on qTranslate-X side.
Good luck.
