### ISSUE TITLE
Hide out of stock product's price automatically

### ISSUE THREAD

**Issue by MMaKenZi** [woothemes/woocommerce#11896]
## EXPLANATION OF THE ISSUE
I am using Woocommerce 2.6.2
and as I saw, this option isn't available in 2.6.4 either 

## STEPS TO REPRODUCE THE ISSUE
I think when a product is sold out, it's price shouldn't be visible
because it's possible that the product price changed after sold out and raise down 
so when customer come to the product page, see the old price while the product is out of stock
I think adding this option is so helpful

e.x. when a product has stock quantity and the quantity finished, automatically the price became hidden

**Comment by mikejolley** [comment]
I think users may want this either way. Sounds best left to customisation - it wouldn't be too difficult to filter the price and return nothing when out of stock.
