### ISSUE TITLE
Creating new variable product with a variation SKU that matches a variation product SKU in the trash throws Duplicate SKU warning.

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#11898]
## EXPLANATION OF THE ISSUE

Version: 2.6.4

## STEPS TO REPRODUCE THE ISSUE

1. Create variable product with a variation that has a sku of ISUNIQUE
1. Publish product
1. Delete product (don't empty trash)
1. Repeat Step 1
1. Save Changes on variations

Result:

- Duplicate sku error on the variation.

Notes:

Unsure if the same happens on non-variable products. Only have time to confirm variable products right now.

**Comment by mikejolley** [comment]
This is expected, otherwise you'd risk dupe SKUs if the product was restored from trash.
