### ISSUE TITLE
Calendar in Woocommerce missing when ativating follow up email

### ISSUE THREAD

**Issue by beanzl** [woothemes/woocommerce#11902]
When I activate Follow up email the calendar and book now button in all products for bookable products disappears. When I deactivate follow up emails the calendar is back.
I had a look at firebug and there is an inline style that is set to display:none. When I turn that off on firebug the calendar and book now button are back.

Follow up email deactivated:
<div style="" class="wc-bookings-booking-form" id="wc-bookings-booking-form">

Follow up email activated:
<div style="display:none" class="wc-bookings-booking-form" id="wc-bookings-booking-form">
	

I have tried to hard-code the booking.php file in single-product/add-to-cart folder by removing the display:none, but then I get the date selector and not the calendar.

I'm running Gantry 4 and Osmosis as themes. When I tried a default theme the problem still existed.

Wordpress: 4.6.1
Woocommerce: Version 2.6.4
Woocommerce Bookings: Version 1.9.11
Follow up emails: Version 4.4.16

I have also tried to deactivate as many plug-ins as possible and the problem persisted.

**Comment by mikejolley** [comment]
This is an issue tracker for core. Log a ticket on https://woocommerce.com/my-account/
