### ISSUE TITLE
total_sales is always 0

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11909]
Hi guys,

The total_sales field for any product in my WooCommerce instance is always 0. I am using latest versions of both WP and WC. What is going on and how can I fix this? I already have a lot of orders and I want the count of total_sales to be calculated correctly. Thanks.

**Comment by mikejolley** [comment]
Not much I can do with the details provided. It works here.

`
add_action( 'woocommerce_order_status_completed', 'wc_update_total_sales_counts' );
add_action( 'woocommerce_order_status_processing', 'wc_update_total_sales_counts' );
add_action( 'woocommerce_order_status_on-hold', 'wc_update_total_sales_counts' );
`

Sales log on these statuses. It's stored in meta.

**Comment by amjad0** [comment]
@mikejolley thanks. I will try this out. Could it be related to the fact that these products were imported from another imported infra structure.

**Comment by mikejolley** [comment]
Not really sure without debugging.

**Comment by amjad0** [comment]
@mikejolley is there a way to re-calculated this field?

**Comment by mikejolley** [comment]
No, it's only counted after orders. It can be set, but not recalculated.

**Comment by amjad0** [comment]
@mikejolley I had to delete all orders and start fresh, the totals are now working correctly. It seems, if there are some orders in the system, new items are imported via CSV using the WooCommerce CSV Import Suite plugin, the total sales are not being calculated then.

**Comment by amjad0** [comment]
@mikejolley today again all total_sales became 0. I don't get is causing this. Is there a way to debug this?

**Comment by amjad0** [comment]
Also I am using v3 API
