### ISSUE TITLE
wp_comments with comment_author Woocommerce and user_id of 0 (zero)

### ISSUE THREAD

**Issue by jobst** [woothemes/woocommerce#11900]
## EXPLANATION OF THE ISSUE

I have 10's of thousands of entries in wp_comments, that have comment_author of "WooCommerce" with a user_id of 0 {zero).

Now by Wordpress definition the USER_ID of 0 (zero) is an ILLEGAL user id value. For example if you call "wp_get_current_user" to early (pluggable) you get 0. Also there is no such user and there should never be. It also should never be referred to.

These wp_comments should be attached to the USER that purchased the item/order, after all the entries are about that particular user and the state of the order. If the admin adds a note, the comment should still get the user_id of the order. This way when the user gets deleted these comments disappear as well. If you make the note to some other value the note stays forever and clogs the DB for no particular reason ...

It also makes is really hard to clean the database, every wp_comment should be attached to a VALID user_id but NOT the shop owner, this is user_id based.

## STEPS TO REPRODUCE THE ISSUE

Use PhPMyadmin or a tool of your choice to list wp_comment table, search for user_id of zero, lots of them.

## SYSTEM STATUS REPORT

WC Version: 2.6.4
WP Version: 4.6.1

**Comment by mikejolley** [comment]
Why would 0 be illegal?

These comments are a) hidden. b) **internal system notes** (not tied to a user) and c) easily removable via query by looking at the comment type.

Comment type is `order_note`
