### ISSUE TITLE
Shipping zones and shipping methods not saving

### ISSUE THREAD

**Issue by karstenrowe** [woothemes/woocommerce#11912]
## EXPLANATION OF THE ISSUE

I navigate to Woocommerce > Settings > Shipping. I try to add a new shipping zone or add a shipping method to an existing shipping zone. Neither seem to save and therefore I can't add any delivery charge for the products.

![screen recording 2016-09-13 at 09 04 am](https://cloud.githubusercontent.com/assets/1147708/18474663/2129f3e2-7991-11e6-8612-e6655e109f9c.gif)

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://easyclad.co.uk
Site URL: http://easyclad.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.31 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/0.9.8b

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.48 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ❌ Table does not exist
woocommerce_api_keys: ❌ Table does not exist
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ❌ Table does not exist
woocommerce_shipping_zone_locations: ❌ Table does not exist
woocommerce_shipping_zone_methods: ❌ Table does not exist
woocommerce_payment_tokens: ❌ Table does not exist
woocommerce_payment_tokenmeta: ❌ Table does not exist
MaxMind GeoIP Database: ✔

### Active Plugins (8) ###

Akismet: by Automattic – 3.2
Contact Form 7: by Takayuki Miyoshi – 4.5
Homepage Control: by WooThemes – 2.0.2
Jetpack by WordPress.com: by Automattic – 4.3.1
MailChimp for WordPress: by ibericode – 4.0.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.20

WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.5

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /hygienic-wall-cladding-products/
Basket: #6 - /my-basket/
Checkout: #10 - /checkout/
My Account: #11 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront Child Two
Version: 1.0.0
Author URL: http://example.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.2
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

I'd really appreciate some help on this – thank you.

**Comment by mikejolley** [comment]
Your log states the tables are missing. Thats your problem. Re-activate the plugin or check server to find out why the tables are missing.

**Comment by guillaumemolter** [comment]
@mikejolley I have the same issue here. The tables actually exist (similar to #12635), but the system report says they don't. And I see the same behavior where saving shipping methods does nothing.

### WordPress Environment ###

WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: nginx/1.11.4
PHP Version: 7.0.11-1+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 49 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: molterwpmu_9_
woocommerce_sessions: ❌ La table n’existe pas
woocommerce_api_keys: ❌ La table n’existe pas
woocommerce_attribute_taxonomies: ❌ La table n’existe pas
woocommerce_downloadable_product_permissions: ❌ La table n’existe pas
woocommerce_order_items: ❌ La table n’existe pas
woocommerce_order_itemmeta: ❌ La table n’existe pas
woocommerce_tax_rates: ❌ La table n’existe pas
woocommerce_tax_rate_locations: ❌ La table n’existe pas
woocommerce_shipping_zones: ❌ La table n’existe pas
woocommerce_shipping_zone_locations: ❌ La table n’existe pas
woocommerce_shipping_zone_methods: ❌ La table n’existe pas
woocommerce_payment_tokens: ❌ La table n’existe pas
woocommerce_payment_tokenmeta: ❌ La table n’existe pas
MaxMind GeoIP Database: ✔
![screen shot 2017-09-05 at 14 59 16](https://user-images.githubusercontent.com/1478527/30078310-d5a188bc-924a-11e7-905b-11897067f88d.png)
### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (20) ###

Advanced Custom Fields PRO: par Elliot Condon – 5.6.1
Contact Form 7: par Takayuki Miyoshi – 4.9
Easy WP SMTP: par wpecommerce – 1.2.6
MailChimp: par MailChimp – 1.5.7
Really Simple CAPTCHA: par Takayuki Miyoshi – 2.0.1
SEO Ultimate: par SEO Design Solutions – 7.6.5.9
Simple Share Buttons Adder: par Simple Share Buttons – 6.3.6
User Role Editor: par Vladimir Garagulya – 4.35.3
WooCommerce PayPal Express Checkout Gateway: par WooCommerce – 1.4.3
WooCommerce: par Automattic – 3.1.2
WP Instagram Widget: par Scott Evans – 1.9.8
Related Posts: par iLen – 5.12.70
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 2.2.6
Disable Comments: par Samir Shah – 1.7
TinyMCE Advanced: par Andrew Ozz – 4.6.3
Better Sanitize File Name: par Guillaume Molter – 1.0
User Role Editor: par Vladimir Garagulya – 4.35.3
Fix Meta Slider SSL: par Guillaume Molter – 1.0
Redis Object Cache: par Till Krüss – 1.3.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base boutique: #4429 - /shop/
Panier: #4430 - /panier/
Commande: #4431 - /commande/
Mon compte: #4432 - /mon-compte/

### Theme ###

Name: ---
Version: 1.0
Author URL: https://www.guillaumemolter.me
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by guillaumemolter** [comment]
@karstenrowe did you ever found a solution to this?

**Comment by alisajil** [comment]
Disable and Enable the wooCommerce Plugin.. It works!
