### ISSUE TITLE
Variable Products – Attributes & Variations ---WooCommerce REST API

### ISSUE THREAD

**Issue by pkhutal** [woothemes/woocommerce#11919]
I am using WooCommerce REST API to display products in Mobile App and its working fine.
But in VARIABLE PRODUCT,
Let,
	Number of Options for Attribute_1 = m
	Number of Options for Attribute_2 = n

then their must be,
	Number of Variations = m x n (Let m=5 and n=5 hence total Variations = 5 x 5 =25)
	
But I get,
	Number of Variations = 4 (which is less than m x n)

And in WooCommerce website it shows all possible Variations, So I need to know that how it is working fine in website.
So please explain me, so that i will implement it in my mobile app.

**Comment by claudiosmweb** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://support.woothemes.com for premium plugin support

This don't seems an issue with WooCommerce, so it's better ask for help in the support forum.
