### ISSUE TITLE
Slow on 100k+ Products

### ISSUE THREAD

**Issue by dima-stefantsov** [woothemes/woocommerce#11913]
## WP/WC is slow for both read and write when products count is more than 100k.

Latest WP, WC. For each Product in wp_posts, there are ~29 rows in wp_postmeta. When postmeta have more than 1M rows, certain queries become slow. Really slow. Unusably slow.

I've heard "it's not a bug, it's a feature", "it's as intended", "it's wordpress way". But my understanding of "wordpress way" is when everything is easy and fast. Not when page takes seconds to load.

**I expect WC to work fast, even with millions of products. And it would be fast, if meta would be stored in one row per product, in a custom table. This is how I see it can be fixed. Is there other ways? Will it be fixed?**

I was advised to make new issue, original comment with explanation is here https://github.com/woothemes/woocommerce/issues/10071#issuecomment-246581179 
> "Products" should stay in wp_posts, what makes WooCommerce slow on 50k+ products is huge wp_postmeta. WC creates ~29 meta rows per every post/product. Everything gets slow when wp_postmeta have few millions rows.
>
All that needs to be done is flatten this postmeta EAV hell somehow. Move it to new table wp_woocommerce_product_meta, where it takes 1 row per product, not ~29 in common table.
>
There is kind of solution that does exactly this https://wordpress.org/plugins/horizontal-meta/ , but it's abandoned and "doesn't work well past wp 4.1".

and here https://github.com/woothemes/woocommerce/issues/10071#issuecomment-246684666

> SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE 1=1 AND ( ( wp_postmeta.meta_key = '_visibility' AND wp_postmeta.meta_value IN ('visible','catalog') ) ) AND wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID ORDER BY wp_posts.menu_order ASC, wp_posts.post_title ASC LIMIT 48, 12;
> 
> Above is the code WP/WC generates for page 5 root of shop products. It joins with postmeta and checks if each product should be counted/displayed or hidden. It takes about 0.8 seconds on ~93k products, on 4.2GHz top i7 PC. Not much faster CPU can get. (ssd, innodb, db warm in cache)
> 
> http://4.stefantsov.com/s/?2016.09.13_16.35.14_a0dwycvp.png
> 
> You say I am doing it wrong, and there is a way to make browsing faster? Currently page loads more than a second, on too fast pc, taking 100% CPU of one core for the time. You say it can become 10-100 times faster?
> 
> I'm not DBA, but I'm seasoned developer, in many languages. General phrases like "you do need to be more careful with the plugins and other site setups than just installing whatever plugin you find" are not about me. Naked WP. WC. 100k products. Opening full products list. You say it can be fast? How? What about 3 000 000 products?
> 
> Even more, what about adding products? Adding 50-100k products is not DB-capped on my 4GHz cpu, it's about 300 products/minute with default setup. After that, things become exponentially slower. If WP would use horizontal table for product meta, it would work with millions products no problem. Can I make it work this way now? How does "hosting setup suitable for my site" looks in my case?
> 
> My current understanding is that it's impossible with EAV ~29 postmetas per product.
> Please open my eyes, tell me I'm wrong. Your 100M postmeta sure sounds impressive.

## STEPS TO REPRODUCE THE ISSUE

1. Import 500k products with wp all import from any csv
2. (few days later)
3. Now you have 500k posts, try browsing your products catalog root. Page1, page2, page3.
4. It takes forever.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://wooshop.local
Site URL: http://wooshop.local
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.20 (Win64) OpenSSL/1.0.2h PHP/7.0.8
PHP Version: 7.0.8
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.9
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (2) ###

WooCommerce: by WooThemes – 2.6.4
WP All Import: by Soflyy – 3.3.7

### Settings ###

Force SSL: –
Currency: RUB (руб.)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My Account: ❌ Page ID is set
but the page does not exist


### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront Child
Version: 2
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.2
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/loop\add-to-cart.php
storefront-child/woocommerce/single-product\add-to-cart\simple.php
storefront-child/woocommerce/single-product\price.php
```

**Comment by dima-stefantsov** [comment]
http://nathanfranklin.com.au/plugins/introducing-horizontal-meta-performance-benchmarks/ and other posts there = elaboration on how horizontal meta (plugin mentioned in comment above) was able to drastically speed WC up.

**Comment by claudiosmweb** [comment]
> Will it be fixed?

Yes, right now we are creating CRUDs for all kind of data in WooCommerce, especially for products.
So will be really easy to move any data to a custom table.

Closing this issue because this is already an work in process.

**Comment by unity100** [comment]
That's a major, major, major, MAJOR problem with wordpress indeed. Naturally Woocommerce inherits it since it uses its EAV format, and indeed it becomes a hell when you have many products.

This must be addressed post haste.

**Comment by ThomasVeld** [comment]
Is there a fix already?

`            do {
                $i++;

                $productData = [
                    'per_page' => 100,
                    'page' => $i
                ];

                $products = $woocommerce->get('products', $productData);

                echo 'processing...'.$i;
                sleep(1);

            } while($i <= (int) $totalPages);`

This loop with 167 pages takes up to 7 minutes already!

**Comment by claudiosanches** [comment]
@ThomasVeld makes sense, since is calling to sleep.

**Comment by claudiosanches** [comment]
Since I already said, this comes from WordPress REST API: https://github.com/WordPress/WordPress/blob/bebb0b0d82759aa3abbaa33baed6430f37ec1164/wp-includes/rest-api/endpoints/class-wp-rest-controller.php#L317-L325
If changed on WordPress core, should change on WooCommerce too.
