### ISSUE TITLE
I get a responce from staging but not from production, same site different servers.

### ISSUE THREAD

**Issue by phillipswdc** [woothemes/woocommerce#11914]
I am having an issue trying to reach the WC API

the code I am using...

$woocommerce = new Client(
    'http://example.com',
    'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]
);

print_r($woocommerce->get(''));

On staging I get a response. On production I get a blank error.

I thought that it might be some differences between production and staging so I pulled from production and tried to use the API on staging. It worked.

I originally thought it was some weird (or not so weird) firewall issue. No not so.

staging is with one host and production with another. Both are VPS Servers.

The error message is blank...

Fatal error:  Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error:  []' in /var/www/phillipswdc.com/public_html/curl/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:315
Stack trace:
#0 /var/www/phillipswdc.com/public_html/curl/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(334): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(NULL)
#1 /var/www/phillipswdc.com/public_html/curl/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(370): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#2 /var/www/phillipswdc.com/public_html/curl/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('', 'GET', Array, Array)
#3 /var/www/phillipswdc.com/public_html/curl/live.php(90): Automattic\WooCommerce\Client->get('')
#4 {main}
  thrown in /var/www/phillipswdc.com/public_html/curl/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 315

I just got this from the host who found this in a log file...

[13-Sep-2016 18:51:16 UTC] PHP Fatal error:  Class 'WC_REST_Controller' not found in /home/cpanelusr/public_html/wp-content/plugins/woocommerce-shipment-tracking/includes/class-wc-shipment-tracking-rest-api-controller.php on line 11

I am wits end with this one staging and production are in sync. Anyone ever have this happen?

**Comment by claudiosmweb** [comment]
> [13-Sep-2016 18:51:16 UTC] PHP Fatal error: Class 'WC_REST_Controller' not found in /home/cpanelusr/public_html/wp-content/plugins/woocommerce-shipment-tracking/includes/class-wc-shipment-tracking-rest-api-controller.php on line 11

You need to fix this in your production server, if is throwing errors will of course break the JSON response from the REST API.

**Comment by phillipswdc** [comment]
Thank you for the reply but can you please tell me what is broken? The WP/WC installation is exactly the same on staging (where it works) as on production. Any insight would be awesome. Thanks.

**Comment by claudiosmweb** [comment]
@phillipswdc this is not a support channel, that  `woocommerce-shipment-tracking` plugin is from WooCommerce.com?
If so, you can open a ticket in https://woocommerce.com/my-account/tickets/

**Comment by phillipswdc** [comment]
My apologies, thanks for your time.
