### ISSUE TITLE
No hook to skip fieldset before loop over each field in processing checkout 

### ISSUE THREAD

**Issue by Dartui** [woothemes/woocommerce#11910]
## EXPLANATION OF THE ISSUE
I have created my own fieldset (company) in checkout, which is expanded when user checks checkbox (like create account). In code is part, where whole fieldset is skipped before looping over each element of this fieldset, for example for account
```
// Skip account if not needed
if ( 'account' === $fieldset_key && ( is_user_logged_in() || ( false === $this->must_create_account && empty( $this->posted['createaccount'] ) ) ) ) {
	continue;
}
```

I would like to add my own rule to skip whole fieldset, because I have got there required fields, which are tested for being empty (if someone don't want to get invoice for company, then he will not fill this fields). For now, this is impossible, because there is no hook for this. Is there any possibilities to improve this or show me where I can do this in actual code? I would like to note, that I can't unset this fieldset before loop, because I need it in later hooks.

**Comment by mikejolley** [comment]
We won't be tackling this until https://github.com/woothemes/woocommerce/issues/10672 Maybe you should add your fields outside of that account fieldset instead.
