### ISSUE TITLE
[REST-API] Wrong documentation for update product category

### ISSUE THREAD

**Issue by nrodriguez-tupaca** [woothemes/woocommerce#11925]
## EXPLANATION OF THE ISSUE

In the [Product Category Update documentation URL](https://woothemes.github.io/woocommerce-rest-api-docs/#update-a-product-category) it says that the JSON of the request body should be:

> curl -X PUT https://example.com/wp-json/wc/v1/products/categories/9 \
>     -u consumer_key:consumer_secret \
>     -H "Content-Type: application/json" \
>     -d '{
>   "product_category": {
>     "description": "All kinds of clothes."
>   }
> }'
> 

But actually, it should be:
```
curl -X PUT https://example.com/wp-json/wc/v1/products/categories/9 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
    "description": "All kinds of clothes."
  }'
```

**Comment by claudiosmweb** [comment]
Fixed https://github.com/woothemes/woocommerce-rest-api-docs/commit/3ccbb8cec8897ae2ac0a9b8dbbe7e97b9ed6c3a2

If you find more issues like this with the REST API docs, please open issues in https://github.com/woothemes/woocommerce-rest-api-docs/issues

Thanks.
