### ISSUE TITLE
Orphaned variations cause fatal error in stock reports

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#11921]
## EXPLANATION OF THE ISSUE
When orphaned variations exist and stock management is not enabled, clicking on the 'Stock' report tab results in something similar to 

`Fatal error: Call to a member function get_stock_quantity() on a non-object in ..../wp-content/plugins/woocommerce/includes/class-wc-product-variation.php on line 399`

now [here](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variation.php#L404)

## STEPS TO REPRODUCE THE ISSUE

1. Orphaned variations exist
2. Stock management is not enabled
3. Navigate to Reports -> Stock
4. Fatal error thrown

source: ticket: #467948-zd-woothemes

I think the solution for this would be to not display the 'stock' tab in reports unless stock management is enabled since if stock management isn't enabled that tab doesn't appear to be of any use. I'd be happy to submit a PR for that if you think that's the right way to handle it @claudiosmweb

**Comment by claudiosmweb** [comment]
The problem is "orphaned variations exist" and not about display the "Stock" tab.
By default WooCommerce don't generate orphaned variations, so this may be generate by a custom importer or code, and should be removed.

@mikejolley Thoughts?

**Comment by justinshreve** [comment]
I agree. Do we run into orphaned variations a lot? (Being generated from importers, etc). If so, maybe a system status tool to clear them would help? Otherwise I'm not sure if we need to do anything here.

Hiding 'Stock' under reports if `woocommerce_manage_stock` is disabled does makes sense and would be a tiny PR, but is separate from this.

**Comment by claudiosmweb** [comment]
> If so, maybe a system status tool to clear them would help

Yeah, I think we should have some tool for it.
It's common see this things.

**Comment by justinshreve** [comment]
See #11979.
