### ISSUE TITLE
Shortcodes for checkout

### ISSUE THREAD

**Issue by streamworksaudio** [woothemes/woocommerce#11926]
Hi,

I created a few shortcodes that generate sections of the WC checkout page (billing form, review etc).  

They display the checkout page perfectly, and payments work per normal.  However the thank you page always returns the error 'Sorry, your session has expired.'  

The orders are processed properly, just that message shows up after the checkout is complete.  Is there something someone can suggest I look at to see what could be causing this issue?

Cheers

**Comment by claudiosmweb** [comment]
Sorry, but don't looks like an issue on WooCommerce core, looks like an issue related with your custom code so you should try the https://wordpress.org/support/plugin/woocommerce for general support.
