### ISSUE TITLE
Hide shipping address for local pickup orders

### ISSUE THREAD

**Issue by ramilS** [woothemes/woocommerce#11935]
Too many people searching ways how to hide shipping address when local pickup and how to hide paid shipping when free shipping available, so, please:

make two options..
1. hide paid shipping, when free is available
2. hide shipping address, when local pickup checked

a lot of people will be thankful for you for these options...

**Comment by Dartui** [comment]
Part of #10672 I guess

**Comment by mikejolley** [comment]
Yes, shipping is currently before options so it cannot and should not be hidden (yet). #10672
