### ISSUE TITLE
[REST API] total_sales is not updating 

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11937]
This may be a bug. Tested it on 3 different vanilla WC instances. (using both latest versions of WP and WC)

When I place orders via dashboard or front-end, its updating the total_sales value. 
When I place orders via REST API v3, its not updating the value.

@mikejolley @claudiosmweb

**Comment by mikejolley** [comment]
Creating an order via the API is not really a 'sale' - it doesn't come via checkout, and we don't handle the payment.

You can increase those values on the product endpoint if you are handling payment elsewhere.

**Comment by amjad0** [comment]
@mikejolley The problem is reports are inconsistent with total_sales in this scenario. Reports show X amount items sold for a product, but each product itself has a different value. Also total_sales is read only, so can't update that via the API either.

**Comment by mikejolley** [comment]
But why are you creating paid orders via API and not allowing payment so those values get updated manually?

**Comment by amjad0** [comment]
@mikejolley I developed a Point of Sale client app for WooCommerce. What I am doing is creating orders on the app, accepting swipe payments via a card reader on the iPad. Every time an order is created (and paid for) on the app, it syncs with WooCommerce.

Now, I have a special category in the app that lists frequent items, this category lists the top 20 products based on total_sales value. This does not work since the field is not updating. 

CloudPOS - Restaurants (on AppStore)

**Comment by amjad0** [comment]
@mikejolley any help on how I can achieve this would be appreciated please! Thanks!

**Comment by amjad0** [comment]
@mikejolley - Would like to know of any solution that can calculate total_sales on API based sales... Thanks.

**Comment by mikejolley** [comment]
You can do your own query if you don't want to rely on our meta.

**Comment by amjad0** [comment]
@mikejolley Thanks. I do want to rely on meta, however. I was wondering, what's the point of the API if you are allowing creating orders via it but not updating the sales count of items.
