### ISSUE TITLE
Tax included in price setting doesn't effect postage

### ISSUE THREAD

**Issue by wanton7** [woothemes/woocommerce#11931]
## EXPLANATION OF THE ISSUE

There is taxes settings in finnish "Hinnat ilmoitettu/ syötetään verollisina (sisältää veron)" rough translation tax is included in prices.
Currently this settings doesn't extent to postage. Almost all prices in Finland include tax and this include finnish postal office prices. 
Example I would like to use postage 5,10€ that includes 24% tax. Because that setting doesn't work for postage, I have to use 4,11290€ instead to get it close enough.

### WordPress Environment ###

Home URL: https://www.sitenamechanged.fi
Site URL: https://www.sitenamechanged.fi
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fi

### Server Environment ###

Server Info: nginx/1.10.0
PHP Version: 7.0.8-0ubuntu0.16.04.2
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: Ei saatavilla/-tietoa
SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Palvelimella ei ole käytössä "SoapClient-luokkaa – ne lisäosat jotka käyttävät SOAP eivät ehkä toimi odotetulla tavalla.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Etälähetys/ Remote Post -toiminto: ✔
Etänouto/ Remote Get -toiminto: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (8) ###

Check Email: -- Chris Taylor – 0.3
GetBowtied Tools: -- GetBowtied – 1.1
WPBakery Visual Composer: -- Michael M - WPBakery.com – 4.12.1
Loco Translate: -- Tim Whitlock – 2.0.7
Regenerate Thumbnails (Luo pikkukuvat uudelleen): -- Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: -- ThemePunch – 5.2.6
WooCommerce Checkout: -- Lauri Karisola / markup.fi – 1.0.3
WooCommerce: -- WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Kaupan polkutunnus: #5 - /shop/
Ostoskori: #6 - /cart/
Kassa: #7 - /checkout/
Oma tili: #437 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Shopkeeper
Version: 1.6.13
Author URL: http://www.getbowtied.com/
Child Theme: ❌ – Suositus: jos muokkaat WooCommercen isäntäteemaa jota et itse ole tehnyt
suosittelemme käyttämään lapsiteemaa. Katso: Kuinka luodaan lapsiteema

WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper/woocommerce/checkout/form-billing.php
shopkeeper/woocommerce/checkout/form-checkout.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/checkout/form-shipping.php
shopkeeper/woocommerce/checkout/payment-method.php
shopkeeper/woocommerce/checkout/thankyou.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global/breadcrumb.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/loop/orderby.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper/woocommerce/single-product/add-to-cart/external.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
shopkeeper/woocommerce/single-product/add-to-cart/variable.php
shopkeeper/woocommerce/single-product/meta.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/rating.php
shopkeeper/woocommerce/single-product/related.php
shopkeeper/woocommerce/single-product/short-description.php
shopkeeper/woocommerce/single-product/tabs/additional-information.php
shopkeeper/woocommerce/single-product/tabs/description.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product/up-sells.php
shopkeeper/woocommerce/single-product-reviews.php
shopkeeper/woocommerce/single-product.php

**Comment by mikejolley** [comment]
Not currently a feature https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425
