### ISSUE TITLE
"Select All" checkbox header is missing from "Orders" admin panel page

### ISSUE THREAD

**Issue by raspberrysmile** [woothemes/woocommerce#11949]
With reference from https://github.com/woothemes/woocommerce/issues/11764

I've tried disabling all plugins except for woocommerce and the issue still persists.
I've also tried deleting all the plugins and theme and re-installed only woocommerce, but the issue still persists.

Attached screenshot below:
![admin-order](https://cloud.githubusercontent.com/assets/6565327/18656138/49320632-7f21-11e6-80da-e7cfaf3c3b83.jpg)

**Comment by claudiosmweb** [comment]
Do not open the same topic more than one time.
If you want to add something, you can do in your first topic.
