### ISSUE TITLE
Less AJAX

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11941]
I'm aiming to have WC website that is as much static as possible because otherwise performance analyzers such as https://tools.keycdn.com/performance indicate that I have 100ms loading for static assets (with a CDN) and all AJAX requests (that connect to 1 main server) have values like even 1711ms (or generally in 600-1000ms area).

The shop page (which is a fully static HTML file for me) has 100ms loading but each "Add to cart" button triggers an AJAX request and takes too long from some locations. Shouldn't this be handled 100% by localStorage? Is this feature planned?

As for the /cart/ page I understand that adding coupon requires an AJAX request but changing quantity for 99% of shops doesn't require an AJAX request. I don't have any PHP filters or special conditions there.

Sidebar filters: default PHP reload is OK and there is an AJAX plugin in the Woo store but this is one of the things that can be handled 100% by JavaScript if there is only one page of products (and many shops have just one page for each category or on the main shop page). Is this planned that WC would not trigger AJAX request in such case? Many people would use this feature if it was implemented for sure (if it cuts loading from 2s to 0s).

By the way: AJAX sidebar filters https://woocommerce.com/products/ajax-layered-navigation/ should be a built-in WC feature since it's almost essential for fast WC store or it should offer a license that allows reselling with a theme.

Another example: https://wordpress.org/plugins/yith-woocommerce-wishlist/ plugin (which I know doesn't have good quality code but I'm mentioning it because it will picture the issue well) adds AJAX "add to wishlist" button to the shop page and toggling item on/off from wishlist is 2 seconds. That's beyond acceptable. I haven't tried https://woocommerce.com/products/woocommerce-wishlists/ yet but I bet it comes with the same issue.

**Comment by mikejolley** [comment]
Static pages cannot show a dynamic cart, hence its loaded with AJAX.

An AJAX request, on the cart screen for example, is no slower than a full page load. It's done on click. This shouldn't even be a problem.

We don't use local storage because we store session data in our database so it cannot be manipulated.

This issue does not seen to be a bug report or anything, just things you want (and can) customise for your own needs, so I'm closing it.
