### ISSUE TITLE
Widgets disappearing

### ISSUE THREAD

**Issue by manake** [woothemes/woocommerce#11942]
I have "color" and "size" widgets.

When I select anything in one widget (e.g. "color") then many links disappear from "color" and/or "size" widget or entire "size" widget can disappear. I would expect links in the "color" and "size" widgets to become grayed out.

Visitor is confused because they don't know what options there were if something unexpectedly disappears...

I consider Amazon or eBay filters to be a good reference and they don't hide filters.

**Comment by mikejolley** [comment]
You can build your own widgets based on our code if not suitable. We show only valid options. Showing all would be a long list, with unrelated options, on most stores.
