### ISSUE TITLE
Allow plugins to declare secure settings fields

### ISSUE THREAD

**Issue by cellar-door** [woothemes/woocommerce#11946]
When a plugin has settings fields that contains secure information (password, API key, application secret etc.) it would be good to have the ability to store those in a secure manner.

What I propose is a generic secure field handler that occurs during the process_admin_options() function to allow for secure settings to be handled in a universal manner. In order to do this we would need to:

1. Allow a plugin to declare in their settings that a field is secure. To do this I propose adding a secure flag to the field ("secure" => true,)

2. During the process_admin_options() we look for that flag and if there and set to true we call a filter on the value to allow for plugins to handle the information before it hits the database.

Pull request incoming for the updates to core and will create an issue in other plugins should we decide this is a good route to go.

**Comment by claudiosmweb** [comment]
You can simple use the `woocommerce_settings_api_sanitized_fields_*` filter for it, don't need an extra filter.
You will achieve the same that you are trying from if with filter you tried to introduce in the #11947

**Comment by cellar-door** [comment]
I did see that filter, however it creates a specific filter for every plugin by concatenating the id of the plugin to the filter. This means that plugin developers will have to maintain a large array of filters for every plugin in the woocommerce ecosystem, of which only a handful may be relevant to a specific installation. This is going to be difficult to maintain for plugin developers.

Instead, what I'm proposing is a generic filter that provides a singular interface for plugins to filter and secure only values that plugins deem as secure, but do so in a unified way for all plugins. See pull request in the Stripe plugin for how this could work: https://github.com/woothemes/woocommerce-gateway-stripe/pull/66 .
