### ISSUE TITLE
[REST API] stock_quantity not updating on products endpoint

### ISSUE THREAD

**Issue by leeuweriq** [woothemes/woocommerce#11943]
## EXPLANATION OF THE ISSUE

When trying to update the stock of a product (whether this is a simple or configurable product), the response is a 200 OK, but after checking the product attributes, the 'stock_quantity' field is not updated at all. I expect the stock_quantity to be updated with the quantity I provided. Running WooCommerce 2.6.2 on Wordpress latest.

## STEPS TO REPRODUCE THE ISSUE

- Using the Automattic/WooCommerce package as client
- (Note: client works fine, all other 'put' requests I perform in my script do work).
- Updating the stock as follows (in which 123 is the new stock quantity for productId 140):

`$productId = 140;
$params = [
            'stock_quantity' => 214
        ];
$this->woo->put('products/' . $productId, $params);
`

Product details **before** put request:
`array(62) {
["id"] 140
["name"] "Digitale coaxiale kabel"
["slug"] "digitale-coaxiale-kabel"
(...)
["sku"] "coa3m"
["virtual"] false
["downloadable"] false
(...)
["manage_stock"] true
["stock_quantity"] 80`

Product details **after** put request (exactly the same, stock_quantity did not update):
`array(62) {
["id"] 140
["name"] "Digitale coaxiale kabel"
["slug"] "digitale-coaxiale-kabel"
(...)
["sku"] "coa3m"
["virtual"] false
["downloadable"] false
(...)
["manage_stock"] true
["stock_quantity"] 80`

## SYSTEM STATUS REPORT
[systemstatusreport.txt](https://github.com/woothemes/woocommerce/files/479645/systemstatusreport.txt)

**Comment by leeuweriq** [comment]
Problem was with the server config. Closed!

**Comment by davidalzate** [comment]
Hello @leeuweriq , could you please explain how you fix it?
