### ISSUE TITLE
WooCommerce plugin not shown.

### ISSUE THREAD

**Issue by Psych0tix** [woothemes/woocommerce#11958]
## EXPLANATION OF THE ISSUE

![image](https://cloud.githubusercontent.com/assets/22356338/18729776/63abc844-8053-11e6-9367-c67103e92cbd.png)

WordPress 4.6.1 using Theme Salient.

WooCommerce plugin is installed and activ but not shown on the sidebar.

If I click on "settings" on the plugin page there comes an error "your are not allowed to see this page" 

![image](https://cloud.githubusercontent.com/assets/22356338/18729959/3a4bdbc8-8054-11e6-861b-e0069a87e29f.png)

![image](https://cloud.githubusercontent.com/assets/22356338/18729853/d01afcd4-8053-11e6-9da6-63069d8a070e.png)

(sorry for the german pictures)

Best regards,

Tobi

**Comment by mikejolley** [comment]
Looks like one of your other plugins has taken it's place in the menu. We use a pretty unique position so perhaps that borrowed code from us.
