### ISSUE TITLE
Shipping taxes get lost after order update

### ISSUE THREAD

**Issue by partyka1** [woothemes/woocommerce#11961]
## EXPLANATION OF THE ISSUE

WC version: 2.5.5
If you make an order, and later admin hits 'recalculate taxes' on order edit page, taxes for shipping fee get lost.
## STEPS TO REPRODUCE THE ISSUE

0. Turn on taxes in your system, and add tax rate other than default. Set it as applicable for shipping. Make default tax rate not applicable for shipping.
1. Make an order with shipping
2. Go to admin edit page for that order. Order has properly calculated taxes for products, and for shipping.
3. Hit 'recalculate taxes' 
4. Taxes for shipping line item get lost

I believe the reason for this, is WC_Abstract_Order::calculate_taxes, in second loop, you have:
```

			$tax_rates         = WC_Tax::find_rates( array(
				'country'   => $country,
				'state'     => $state,
				'postcode'  => $postcode,
				'city'      => $city,
				'tax_class' => ''
			) );
```
so if your tax rate for shipping is not the default one(but one set by `get_option( 'woocommerce_shipping_tax_class' )` or other), than it won't be present in `$tax_rates` array ( because `'tax_class'=>''` will select only default tax class)
## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://home.app
Site URL: http://home.app/wordpress
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 7.0.8
PHP Post Max Size: 3 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 3 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Metoda Remote Post: ✔
Metoda Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (23) ###

Caldera Forms: przez David Cramer – 1.3.5
Edytor kolumn: przez AdminColumns.com – 2.5.6.3
Contact Form DB: przez Michael Simpson – 2.10.11
Formularze: przez Takayuki Miyoshi – 4.4
Google Tag Manager for Wordpress: przez Thomas Geiger – 1.3.2
Flamingo: przez Takayuki Miyoshi – 1.4
WPBakery Visual Composer: przez Michael M - WPBakery.com – 4.11.1
Loco Translate: przez Tim Whitlock – 1.5.5
WooCommerce Sponsor a Friend Plugin: przez MB Création – 2.3
Meta Box: przez Rilwis – 4.8.7
Post Types Order: przez Nsp Code – 1.8.7
Odnawianie miniaturek: przez Alex Mills (Viper007Bond) – 2.2.6
Ultimate Member: przez Ultimate Member – 1.3.68
Ultimate Member - WooCommerce: przez Ultimate Member – 1.0.10
WooCommerce - Bramka Płatności PayU: przez Inspire Labs – 1.2.1
WooCommerce W-zetki: przez MoveCloser – 1.0
WooCommerce wFirma: przez WP Desk – 1.1.1
WooCommerce: przez WooThemes – 2.5.5
WP Retina 2x: przez Jordy Meow – 4.4.4
WP Sync DB: przez Sean Lang – 1.5
WP Desk Helper: przez WP Desk – 1.1
WPML CMS Nav: przez OnTheGoSystems – 1.4.12
WPML Media: przez OnTheGoSystems – 2.1.14

### Settings ###

Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Strona sklepu: #40 - /shop/
Koszyk: #41 - /cart/
Zamówienie: #42 - /checkout/
Moje konto: #43 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
home_bundle (home_bundle)
simple (simple)
variable (variable)

### Theme ###

Name: Home
Version: 1.0.0
Author URL: 
Child Theme: ✕ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: home/woocommerce/archive-product.php
home/woocommerce/cart/cart-totals.php
home/woocommerce/cart/cart.php
home/woocommerce/cart/mini-cart.php
home/woocommerce/cart/proceed-to-checkout-button.php
home/woocommerce/checkout/form-billing.php
home/woocommerce/checkout/form-checkout.php
home/woocommerce/checkout/form-shipping.php
home/woocommerce/checkout/payment-method.php
home/woocommerce/checkout/payment.php
home/woocommerce/checkout/review-order.php
home/woocommerce/checkout/terms.php
home/woocommerce/checkout/thankyou.php
home/woocommerce/content-product.php
home/woocommerce/content-single-product.php
home/woocommerce/emails/customer-completed-order.php
home/woocommerce/emails/customer-processing-order.php
home/woocommerce/emails/email-addresses.php
home/woocommerce/emails/email-header.php
home/woocommerce/emails/email-order-items.php
home/woocommerce/global/quantity-input.php
home/woocommerce/loop/add-to-cart.php
home/woocommerce/loop/loop-end.phpwersja - jest nieaktualna. Wersja systemu to 2.0.0
home/woocommerce/loop/loop-start.php
home/woocommerce/loop/orderby.php
home/woocommerce/loop/pagination.php
home/woocommerce/loop/price.php
home/woocommerce/loop/rating.php
home/woocommerce/loop/result-count.php
home/woocommerce/loop/sale-flash.php
home/woocommerce/notices/notice.php
home/woocommerce/notices/success.php
home/woocommerce/single-product/product-thumbnails.php
home/woocommerce/single-product.php

: Dowiedz się jak zaktualizować przestarzałe szablony
`

**Comment by mikejolley** [comment]
Pretty sure this has already been patched. You are not on latest.

**Comment by partyka1** [comment]
Problem still exists in 2.6.4. If you update order from admin panel, shipping taxes get lost. Possible cause is that in WC_AJAX::calc_line_taxes there is different logic for finding `$matched_tax_rates` than in `WC_Abstract_Order::calculate_taxes`

**Comment by partyka1** [comment]
@mikejolley any updates on this?
