### ISSUE TITLE
Woocommerce Rest API seems conflict with session cookies

### ISSUE THREAD

**Issue by geckoslair** [woothemes/woocommerce#11969]
## EXPLANATION OF THE ISSUE

I'm trying to perform an ajax call to an endpoint (GET products) from an option page inside the dashboard.

Performing the call outside (using curl and postman) i have a 200 response with correct response data
Performing the same call from the option page i have the following response:

{
  "code": "woocommerce_rest_cannot_view",
  "message": "Non puoi creare una lista delle risorse.",
  "data": {
    "status": 401
  }
}

## STEPS TO REPRODUCE THE ISSUE

I'm working on local environment with https enabled.
This is the script that i'm trying to run from the option page:

jQuery.ajax({
            url:      "https://test.dev/wp-json/wc/v1/products",
            beforeSend: function (xhr){
                xhr.setRequestHeader ("Authorization", "Basic " + btoa(ck + ":" + cs));
            }
        });

where ck and cs are valid customer_key and customer_secret.

## SYSTEM STATUS REPORT
```
### WordPress Environment ###

Home URL: https://test.dev
Site URL: https://test.dev
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
PHP Version: 5.6.3
PHP Post Max Size: 100 MB
PHP Time Limit: 700
PHP Max Input Vars: 1000
cURL Version: 7.39.0
OpenSSL/1.0.1i

SUHOSIN Installed: –
MySQL Version: 5.6.21
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
POST remoto: ✔
GET remoto: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Il database di MaxMind GeoIP non esiste - La geolocalizzazione non funzionerà. Puoi scaricarlo da http://dev.maxmind.com/geoip/legacy/geolite/ ed installarlo manualmente in: . Scorri a \"Downloads\" e scarica il file \"Binary / gzip/" dopo \"GeoLite Country\"

### Active Plugins (4) ###

Gdrive Importer: by Enrico Cicconi – 1.0
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /negozio/
Carrello: #5 - /carrello/
Cassa: #6 - /checkout/
Il mio account: #7 - /mio-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – Se stati modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by geckoslair** [comment]
I've investigate in wc-rest-functions.php and seems to be a capabilities issue for admin and superadmin.

**Comment by claudiosmweb** [comment]
> I'm trying to perform an ajax call to an endpoint (GET products) from an option page inside the dashboard.

So you don't need to do basic auth...
You can use Cookie Authentication: http://v2.wp-api.org/guide/authentication/#cookie-authentication

**Comment by saturday** [comment]
Why was the cookie authentication documentation removed for v1 - which is what this question refers to?

**Comment by pabloleone** [comment]
I'm having a similar issue...

When I'm not logged in the WooCommerce REST API response is correct listing all products, as soon as I log in, the response is 401.

I've checked the request using Postman and I get down the error to be the cookie header.

If I remove the cookie header it works, I've add it back and it fails.

I can't prevent the cookie to be sent when using the browser, so how can I make WooCommerce to respect the consumer keys instead of using the cookies?

Thank you.

**Comment by claudiosanches** [comment]
@pabloleone for what you are reporting, maybe you issue is related to #23682
