### ISSUE TITLE
2.6.4: `wp wc order list` cannot be filtered

### ISSUE THREAD

**Issue by lkraav** [woothemes/woocommerce#11962]
`wp wc order list --total=1` returns all orders.
`wp wc order list --status=processing` returns all orders.
etc.

At the very least, there are no examples provided for `wp wc order list` in the documentation, which makes it quite obscure to diagnose issues.

**Comment by justinshreve** [comment]
We are overhauling the CLI right now to use the REST API as a backend. See #11611. The goal is to have that ready for the next version, and at that point you should be able to filter.
