### ISSUE TITLE
Free shipping line item has no tax

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#11977]
## EXPLANATION OF THE ISSUE

The tax column is blank for free shipping line item. The tax appears when you manually select Calculate Taxes.

## STEPS TO REPRODUCE THE ISSUE

Edit an order and see the tax column.

<img width="761" alt="screen shot 2016-09-27 at 8 44 13 am" src="https://cloud.githubusercontent.com/assets/11021583/18881260/864f778e-848f-11e6-9a6a-5d6a28779ce2.png">

## SYSTEM STATUS REPORT

```
Tested using WooCommerce 2.6.4 with the Twenty Twelve theme and no other plugins. 
```

**Comment by claudiosmweb** [comment]
> The tax appears when you manually select Calculate Taxes.

Right now we have two aways to calculate taxes.
When you manually select make it always try to calculate something.
But this should be fixed in 2.7 since now we are creating CRUD for orders.
