### ISSUE TITLE
Customers endpoint - date filtering no longer works (including legacy endpoints)

### ISSUE THREAD

**Issue by rfink** [woothemes/woocommerce#11974]
## EXPLANATION OF THE ISSUE

Hello,

We are consumers of the WooCommerce API, and up until version 2.6, we were able to provide the "created_at_min" and "created_at_max" filters to the query string, and have it apply the filter to the query (and only return customers created in that range).  As of 2.6, this functionality no longer appears to work (in both the new v1, as well as legacy v2 and legacy v3).  We now receive the entire customer set on every query, regardless of those filters.  We've also tried date_created_min and date_created_max, as well as "after" and "before", to no avail.  This is a significant issue for 3rd party integrations who rely on being able to query customers by date.

## STEPS TO REPRODUCE THE ISSUE

Query the legacy (v2 or v3) customers endpoint with "filter[created_at_min]=2016-01-01&filter[created_at_max]=2016-01-01", and the new v1 endpoint with the same, or "filter[date_created_min]=2016-01-01&filter[date_created_max]=2016-01-01", and check the created dates of the customers (they were not filtered).

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

Unavailable

**Comment by tommyredz91** [comment]
My WC account endpoints are not properly redirecting, so the customer won't either bè able to access and modify any of the input fields on the account page. I have got the AccessPress Mag free theme set-up on my site at: http://floodnews.net.
What on Earth am I supposed to do, to make it work properly once and for all?!?
Tell me how to fix this major issue once and for all, step by step, in detail!!

**Comment by justinshreve** [comment]
@rfink I just tested on 2.6.4 and can't reproduce. Nothing has changed that would break the legacy versions and I can indeed filter using them. Is there exact code you can share here?

Note: I did have to filter using time stamps to get things from the same day
created_at_min: 2016-01-01 00:00:00
created_at_max: 2016-01-01 23:59:59

Other variations (2016-01-01 to 2016-01-02) also correctly filtered. For dates with no customers, no results were returned. I never got a full response like you report.

@tommyredz91 

GitHub is not for support request. Support can take place in the appropriate channels:

* The WooThemes premium support portal for customers who have purchased themes or extensions. https://docs.woocommerce.com/
* Our community forum on wp.org which is available for all WooCommerce users. https://wordpress.org/support/plugin/woocommerce

**Comment by rfink** [comment]
Would it be possible for you to share the curl command for what you used?  With keys and url excluded of course. I'm perplexed as to how it would work, as the code for the legacy system uses WP_User_Query and manually attaches the filter to the "$query_where" public variable, which no longer seems to be available (although I admit I'm rusty with anything wordpress).

I don't have the specific version that the customer is using, but I attempt to retrieve that information.  I do know that the identical curl command, with another customer on 2.5, works on the legacy v2 and v3 endpoints, if that helps.

**Comment by justinshreve** [comment]
@rfink 

`curl -k -X GET -H "Authorization: Basic <AUTH>" "https://woo.dev/wc-api/v3/customers?filter%5Bcreated_at_min%5D=2016-01-01&filter%5Bcreated_at_max%5D=2016-01-01%2023:59:59"`

I also wrote a simple test to try this out https://gist.github.com/justinshreve/fcd7c0646b9149d3d5df5d2b94c995bc

**Comment by justinshreve** [comment]
What version of WP is this by the way?

**Comment by rfink** [comment]
Great question - I'm going to email the client now, and hopefully I can get more information as needed.

**Comment by rfink** [comment]
While on that, I don't suppose there is a way to glean version information via the API?

**Comment by justinshreve** [comment]
`/wc-api/v3/` (no other path) should return it.

**Comment by rfink** [comment]
That's great, had no idea that existed.  Here are the 2 relevant lines, I believe:

  wc_version:  2.6.4
  version:     3.1.0

**Comment by justinshreve** [comment]
Sorry - I just realized `version` returns the version of the API itself, not WP -- it doesn't look like we return the WP version in the legacy API (we will in an upcoming system status endpoint in 2.7).

**Comment by rfink** [comment]
No problem - I've sent out an email to get that information.

**Comment by rfink** [comment]
Got it - it's 4.6.1

**Comment by justinshreve** [comment]
Okay I just verified and the above request still works for me with both WC 2.6.4 and 4.6.1 as well as WP trunk. Since there doesn't seem to be a bug here and we've received no other reports, there might be some plugin/custom code or another issue preventing this from working. I can try to help a bit more over at https://wordpress.org/support/plugin/woocommerce - if I can (since this doesn't seem to be a core issue).

**Comment by rfink** [comment]
Thanks for taking a look. I've found another client with this same issue - WC 2.6.4, unknown Wordpress version.  It's odd that we only have this issue with 2.6 customers, no 2.5 customers. I doubt this has anything to do with it, but we authenticate using QS params for key/secret.
