### ISSUE TITLE
'enable delivery box' unable to disable when editing product

### ISSUE THREAD

**Issue by pedrowsemporium** [woothemes/woocommerce#11972]
## EXPLANATION OF THE ISSUE

I have several products in my store that I want to remove the stock 'delivery box' option (which shows a delivery time standard text which cannot seem to edit)

I can untick the box but when updating the product  the box re-ticks itself, ie I cannot remove the delivery box from the product.

Alternatively, can I change the standard text of the delivery box.? If so, how please.

## STEPS TO REPRODUCE THE ISSUE
editing a product that has the delivery box enabled and trying to update

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.

`
### WordPress Environment ###

Home URL: http://www.noveltynurse.co.uk
Site URL: http://www.noveltynurse.co.uk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (6) ###

WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Table Rate Shipping: by Erica Dion – 3.3.8
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 3.4.2
WP Clone by WP Academy: by WP Academy – 2.2.2

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Cogs Child Theme
Version: 0.2
Author URL: http://jarilo.co.uk
Child Theme: ✔
Parent Theme Name: Jarilo Cogs
Parent Theme Version: 2.5.5
Parent Theme Author URL: http://jarilo.co.uk
WooCommerce Support: ✔

### Templates ###

Overrides: cogs/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 2.5.0
cogs/woocommerce/loop/rating.php

: Learn how to update outdated templates
`
```

**Comment by BurlesonBrad** [comment]
@pedrowsemporium 
> I want to remove the stock 'delivery box' option (which shows a delivery time standard text which cannot seem to edit

That is not a **_BUG_** of WooCommerce. Consequently, this should **_NOT_** be on Github.
> Alternatively, can I change the standard text of the delivery box.? If so, how please.

That is not a **_BUG_** of WooCommerce. Consequently, this should **_NOT_** be on Github.

Nowhere in WooCommerce will you find any files to deliver, render, show, display, or deliver 
this feature, function, capability or option.
![noveltynurse](https://cloud.githubusercontent.com/assets/6208757/18821291/87ed11da-836a-11e6-9dc6-05cc0ec0caa9.png)
That is not a **_BUG_** of WooCommerce. Consequently, this should **_NOT_** be on Github.

**Comment by claudiosmweb** [comment]
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support

**Comment by pedrowsemporium** [comment]
Excuse me for my ignorance - i had a problem and this is where I as directed.
I stand corrected
