### ISSUE TITLE
How to filter products in woocommerce based on some parameters…endpoints required

### ISSUE THREAD

**Issue by NishithGit** [woothemes/woocommerce#11975]
## EXPLANATION OF THE ISSUE

I am trying to apply filters while fetching products from my woocommerce inventory for my android app. For fetching the products based on categories I am using the URL

mysite/wc-api/v3/products?filter[category]="+mycategory".

This is working fine and I am getting the required results.

Now I need to fetch the products based on some filters such as price, brand etc.

I tried using

1> mysite/wc-api/v3/products?filter[category]="+category+"?filter[price]="+price+"" and

2> mysite/wc-api/v3/products?filter[category]="+category+"&filter[price]="+price+"".

Its not working.

**Comment by justinshreve** [comment]
Hi - GitHub issues are not for support.

If you have questions, please use
* https://wordpress.org/support/plugin/woocommerce for general support
* https://support.woothemes.com for premium plugin support

I'm able to filter based on price using the new APIs (you are using a legacy version - see https://woothemes.github.io/woocommerce-rest-api-docs/#introduction).

`filter[meta_key]=_price&meta_value=15`.

**Comment by NishithGit** [comment]
Hi , thanks for the response . I am still unable to get the desired response. Please send me a complete URL. Suppose I want to filter products of some particular category based on price between 500 to 1000, what should be my URL. Please find my response in the attachment.
[wooCommerceResponse.txt](https://github.com/woothemes/woocommerce/files/497279/wooCommerceResponse.txt)

**Comment by justinshreve** [comment]
@NishithGit Please open up a thread on WordPress.org. There is no bug here and as mentioned above we don't offer support here on GitHub (including writing API code for consumers).

https://codex.wordpress.org/Class_Reference/WP_Query meta_query should be able to help you get the result you want since the API allows you to filter that way.
