### ISSUE TITLE
PHPCompatibility in composer.json -> prefer stable

### ISSUE THREAD

**Issue by wimg** [woothemes/woocommerce#11980]
## EXPLANATION OF THE ISSUE

It's best to change the inclusion of PHPCompatibility in composer.json to the latest stable release (currently 7.0.6) instead of "*". This ensure you are using a stable release instead of master which, although fully unit tested, we do not guarantee to be 100% stable.

Seems prudent to add :
"prefer-stable" : true

**Comment by claudiosmweb** [comment]
Already locked in 7.0.5: https://github.com/woothemes/woocommerce/blob/master/composer.lock#L251

**Comment by claudiosmweb** [comment]
And still you can use `composer install --prefer-stable` to ensure it.

**Comment by claudiosmweb** [comment]
Ohh yeah and I removed because of:

```
composer install            
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package prefer-stable could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

More easy to install and lock in the correct version.
