### ISSUE TITLE
'New order' email not triggered if emoji is in 'Additional content' of email body

### ISSUE THREAD

**Issue by jrick1229** [woothemes/woocommerce#30458]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

If an emoji is located in the 'Additional content' of the 'New order' email, the email is not triggered.

**Expected behavior**

Emojis would either be removed if not supported or visible in the email body, but ultimately triggered regardless.

**Actual behavior**

Email is never triggered.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:
1. Copy the thumb emoji from this page: https://emojipedia.org/thumbs-up/
2. Go to: `WooCommerce > Settings > Emails > 'New order'`
3. Paste the emoji into the 'Additional content' field:
   - `Thanks for shopping with us. 👍`
4. Save
5. Go to an order and process a new order email
6. See that no email is triggered

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional Information:**

31045245-hc

**WordPress Environment**

<details>

```
### WordPress Environment ###

WordPress address (URL): http://testsite10.local
Site address (URL): http://testsite10.local
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 149.04MB
Database Data Size: 127.72MB
Database Index Size: 21.32MB

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.5.2

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #403 - /checkout-block/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1 (update to version 3.7.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by juliaamosova** [comment]
Hi @jrick1229,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.5.2. 

Below is the screenshot of my email set up and result of testing:

![email2](https://user-images.githubusercontent.com/19143190/129413350-57eedcfe-93e6-4751-bd83-fda41a573aa3.png)

![email](https://user-images.githubusercontent.com/19143190/129413363-17ffa7ec-7c10-4045-b523-9f30bc5e7f4b.png)

Could this be an issue with the WP Mail Logging plugin by any chance as discovered in https://github.com/woocommerce/woocommerce/issues/28767.

**Comment by jrick1229** [comment]
Hey @juliaamosova - I think that explains it! 😁
