### ISSUE TITLE
Changes not saving after reordering Grouped Products

### ISSUE THREAD

**Issue by sukafia** [woothemes/woocommerce#30459]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
According to the grouped products [documentation](https://docs.woocommerce.com/document/managing-products/#create-grouped-product), one can drag and drop to reorder the Grouped Products "linked products" on the group product page. However, while dragging and dropping works in the backend, the changes are reverted once saved (meaning after reordering in the backend, the changes aren't saved when the product is updated. 

**Expected behavior**

After reordering the linked products in the product editor and clicking "update" to save changes, the changes should be saved. 

**Actual behavior**

Dragging and rearranging products work but the changes aren't being saved when "update" is clicked.

1. Create a new product
2. Change the product data to "grouped product"
3. Add multiple products in the "linked products" field (e.g 3) and publish
4. Reorder the linked products and try to "update" the product to save changes

**Screenshots**
https://d.pr/v/Q0lwfR

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔
```

4209967-zen

**Comment by juliaamosova** [comment]
Hi @sukafia,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 5.5.2. 

Documenting my experience below:

https://user-images.githubusercontent.com/19143190/129414510-31835444-e536-4573-bac5-a8b21cf0aa8b.mov

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by vedanshujain** [comment]
This was fixed in #30108 and should be available with WC 5.6
