### ISSUE TITLE
Woocommerce cron runs every minute..

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#30453]
To recreate:
-) install Debug Bar
-) refresh page, every minute WP_Http will be red. Because it calling WP_cron. Sometimes the ttfb can be more than 500ms just for this single call.

It will not be a problem if most of the user is logged out. We can use page cache. But If most of the users is logged in, it will affect performance.

The best practice is at most cron should not less than 15minutes recurrence. Thats why default cron_schedules have the smallest recurrence is 1 hour.

Other source:  
https://docs.wpvip.com/technical-references/code-review/vip-warnings/#h-cron-schedules-less-than-15-minutes-or-expensive-events

**Comment by juliaamosova** [comment]
Hi @erikdemarco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @erikdemarco—thanks for flagging this.

> The best practice is at most cron should not less than 15minutes recurrence.

I think that's fine as a "rule of thumb", but really it's something that needs to be assessed on a case-by-case basis: not only the case of the individual scheduled event, but the case of what the plugin is trying to achieve in general. Remember that WooCommerce facilitates ecommerce: there are times that a delay of 15 minutes may be unacceptable to a merchant or their customer.

Are there specific jobs (scheduled events, or scheduled actions) managed by WooCommerce that you feel we should review?

Please also note that there are various ways to exercise control over WordPress's processing of scheduled events. For instance, you can disable the native runner and move everything to a system crontab (which allows fine-grained control). You can also take advantage of several cron management plugins that can provide an alternative way to tune things.
