### ISSUE TITLE
[REST API] Variation attributes are losing selected after update

### ISSUE THREAD

**Issue by PhantomD** [woothemes/woocommerce#30469]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When creating a variable product via the REST API, the variations are created and all attributes are pre-selected correctly. However, when trying to update the same variable again using: (products/<product-id>/variations/batch OR products/<product-id>/variations/<variation-id>), the selected attribute is changing to "Any..." even though I did not make any change to the previously selected attribute but I need to keep the same detail in the request.

**Expected behavior**
The correct variation attribute shall be selected.

**Actual behavior**
The previously selected attribute is changing to "Any...".

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

First create the product and variation with attribute.

Then, using rest API endpoint, products/<product-id>/variations/batch
{"update":[{"sku":"1234511141","id":8744,"attributes":[{"id":4,"option":"فودج براوني"}],"weight":"0.50","dimensions":{"length":"10","width":"10","height":"10"},"manage_stock":true,"stock_quantity":"26.00","regular_price":"29.95","sale_price":""}]}

 OR 
products/<product-id>/variations/<variation-id>
{"sku":"1234511141","id":8744,"attributes":[{"id":4,"option":"براوني"}],"weight":"0.50","dimensions":{"length":"10","width":"10","height":"10"},"manage_stock":true,"stock_quantity":"26.00","regular_price":"29.95","sale_price":""}

The response will be:

{
    "update": [
        {
            "id": 8744,
            "date_created": "2021-05-31T07:22:25",
            "date_created_gmt": "2021-05-31T07:22:25",
            "date_modified": "2021-08-10T14:25:21",
            "date_modified_gmt": "2021-08-10T14:25:21",
            "description": "",
            "permalink": "https://xxx/",
            "sku": "1234511141",
            "price": "29.95",
            "regular_price": "29.95",
            "sale_price": "",
            "date_on_sale_from": null,
            "date_on_sale_from_gmt": null,
            "date_on_sale_to": null,
            "date_on_sale_to_gmt": null,
            "on_sale": false,
            "status": "publish",
            "purchasable": true,
            "virtual": false,
            "downloadable": false,
            "downloads": [],
            "download_limit": -1,
            "download_expiry": -1,
            "tax_status": "taxable",
            "tax_class": "",
            "manage_stock": true,
            "stock_quantity": 26,
            "stock_status": "instock",
            "backorders": "no",
            "backorders_allowed": false,
            "backordered": false,
            "low_stock_amount": null,
            "weight": "0.50",
            "dimensions": {
                "length": "10",
                "width": "10",
                "height": "10"
            },
            "shipping_class": "",
            "shipping_class_id": 0,
            "image": {
                "id": 1021,
                "date_created": "2021-05-31T07:22:18",
                "date_created_gmt": "2021-05-31T07:22:18",
                "date_modified": "2021-05-31T07:22:18",
                "date_modified_gmt": "2021-05-31T07:22:18",
                "src": "https://xxx.jpg",
                "name": "xxx.jpg",
                "alt": ""
            },
            "attributes": [],
            "menu_order": 1,
            "meta_data": [],
            "_links": {
                ...
            }
        }
    ]
}

In the response, the attributes are lost and the same is in the products view when checking from Woocommerce products panel where attributes are changed to "Any.." for all the updated variables.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ar
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.3
PHP Version: 7.4.21
PHP Post Max Size: 512 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-1:10.5.12+maria~focal
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: psup_
Total Database Size: 262.33MB
Database Data Size: 195.28MB
Database Index Size: 67.05MB
psup_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
psup_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
psup_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
psup_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
psup_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
psup_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_actionscheduler_actions: Data: 8.52MB + Index: 12.11MB + Engine InnoDB
psup_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_actionscheduler_logs: Data: 6.52MB + Index: 6.02MB + Engine InnoDB
psup_categorymeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
psup_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_options: Data: 8.08MB + Index: 1.28MB + Engine InnoDB
psup_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_postmeta: Data: 48.55MB + Index: 29.98MB + Engine InnoDB
psup_posts: Data: 115.30MB + Index: 8.23MB + Engine InnoDB
psup_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_rank_math_analytics_gsc: Data: 2.52MB + Index: 5.83MB + Engine InnoDB
psup_rank_math_analytics_objects: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
psup_rank_math_internal_links: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
psup_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_terms: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
psup_term_relationships: Data: 2.33MB + Index: 1.23MB + Engine InnoDB
psup_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
psup_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
psup_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
psup_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
psup_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
psup_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
psup_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
psup_wc_product_meta_lookup: Data: 0.36MB + Index: 0.64MB + Engine InnoDB
psup_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
psup_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
psup_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 5050
block: 4
custom_css: 1
customize_changeset: 2
elementor_library: 4
nav_menu_item: 154
page: 16
popup: 1
post: 8
product: 2209
product_variation: 759
raccartlist: 48
racemailtemplate: 1
racmaillog: 47
revision: 161
shipping_package: 1
shop_coupon: 2
shop_order: 79
was: 2
wp-rest-api-log: 3016
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Admin Menu Editor Pro: by Janis Elsts – 2.14.2
Aramex Shipping WooCommerce: by aramex.com – 1.1.6
Autoclear Autoptimize Cache: by Theme Surgeons – 2.1.1
Autoptimize: by Frank Goossens (futtta) – 2.9.0
Booster Plus for WooCommerce: by Pluggabl LLC – 5.4.3
Contact Form 7: by Takayuki Miyoshi – 5.4.2
Custom Fonts: by Brainstorm Force – 1.3.2
Disable Admin Notices Individually: by Creative Motion  – 1.2.6
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
Elementor: by Elementor.com – 3.3.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.18.0
Kirki Customizer Framework: by David Vongries – 3.1.9
Loco Translate: by Tim Whitlock – 2.5.2
Meta Box: by MetaBox.io – 5.4.6
Molla Theme - Core: by D-THEMES – 1.2.9
PayTabs - WooCommerce Payment Gateway: by PayTabs – 4.3.4
Recover Abandoned Cart: by FantasticPlugins – 22.9
Really Simple SSL: by Really Simple Plugins – 5.0.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
RunCloud Hub: by RunCloud – 1.1.2
Rank Math SEO: by Rank Math – 1.0.69.2
WooCommerce - Tap WebConnect: by Tap Payments – 1.1
Ultimate Dashboard PRO: by David Vongries – 3.3.2
Ultimate Dashboard: by David Vongries – 3.4
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.14
Booster for WooCommerce: by Pluggabl LLC – 5.4.3
WooCommerce: by Automattic – 5.5.2
REST API Log: by Pete Nelson – 1.6.8
WhatsApp Chat PRO: by QuadLayers – 2.5.5
Social Chat: by QuadLayers – 4.8.9
YITH WooCommerce Ajax Product Filter: by YITH – 4.1.1
YITH WooCommerce Ajax Search: by YITH – 1.9.2
YITH WooCommerce Wishlist: by YITH – 3.0.25

### Inactive Plugins (13) ###

Admin Menu Editor: by Janis Elsts – 1.9.10
Akismet Anti-Spam: by Automattic – 4.1.10
Cities Shipping Zones for WooCommerce: by Condless – 1.1.2
City Drop-Down: by PluginHive – 1.0.8
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Hide Shipping Method For WooCommerce: by theDotstore – 1.1.0
States, Cities, and Places for WooCommerce: by Kingsley Ochu – 1.3.2
WhatsApp Chat by NinjaTeam: by NinjaTeam – 3.1.1
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
WooCommerce Aramex: by WooCommerce – 1.0.10
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: SAR (ر.س)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #4725 - /shop/cart/
Checkout: #8 - /shop/checkout/
My account: #9 - /shop/my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: psupps
Version: 1.0
Author URL: https://molla.org/about-me/
Child Theme: ✔
Parent Theme Name: Molla
Parent Theme Version: 1.2.9
Parent Theme Author URL: https://molla.org/about-me/
WooCommerce Support: ✔

### Templates ###

Overrides: molla/woocommerce/archive-product.php
molla/woocommerce/cart/cart.php
molla/woocommerce/cart/mini-cart.php
molla/woocommerce/checkout/form-checkout.php
molla/woocommerce/checkout/terms.php
molla/woocommerce/content-product-cat.php
molla/woocommerce/content-product.php
molla/woocommerce/content-single-product.php
molla/woocommerce/content-widget-price-filter.php
molla/woocommerce/global/breadcrumb.php
molla/woocommerce/loop/add-to-cart.php
molla/woocommerce/loop/loop-end.php
molla/woocommerce/loop/loop-start.php
molla/woocommerce/loop/orderby.php
molla/woocommerce/loop/pagination.php
molla/woocommerce/loop/result-count.php
molla/woocommerce/loop/sale-flash.php
molla/woocommerce/myaccount/form-login.php
molla/woocommerce/myaccount/my-account.php
molla/woocommerce/myaccount/my-address.php
molla/woocommerce/single-product/add-to-cart/variable.php
molla/woocommerce/single-product/product-image.php
molla/woocommerce/single-product/product-thumbnails.php
molla/woocommerce/single-product/rating.php
molla/woocommerce/single-product/related.php
molla/woocommerce/single-product/review-meta.php
molla/woocommerce/single-product/review.php
molla/woocommerce/single-product/stock.php
molla/woocommerce/single-product/tabs/tabs.php
molla/woocommerce/single-product/up-sells.php
molla/woocommerce/single-product-reviews.php
molla/woocommerce/single-product.php

### Action Scheduler ###

Complete: 31,953
Oldest: 2021-07-28 17:28:54 +0000
Newest: 2021-08-10 14:26:11 +0000

Pending: 1
Oldest: 2021-08-14 23:12:16 +0000
Newest: 2021-08-14 23:12:16 +0000

### Status report information ###

Generated at: 2021-08-10 14:28:56 +00:00
`
</details>

**Comment by tammullen** [comment]
Hi @PhantomD 

To us evaluate this issue can you confirm which API endpoint are you using (including the version e.g. /wp-json/wc/v3/products) as well as an example request you used to create the product?
