### ISSUE TITLE
Unneeded double spaces in some strings

### ISSUE THREAD

**Issue by NekoJonez** [woothemes/woocommerce#30486]
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/nl-be/default/?filters%5Bterm%5D=++&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

There are some unneeded double spaces in strings. I'm creating PR's in the right locations to fix them ;)

**Comment by juliaamosova** [comment]
Hi @NekoJonez,

Thank you for submitting the issue and PR!
