### ISSUE TITLE
Homepage link at npm page is broken for `@woocommerce/e2e-utils`

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#30484]
The "Homepage" link in npm package page https://www.npmjs.com/package/@woocommerce/e2e-utils is broken
it leads to `https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e-utils/README.md`
which is `404`. It should point to `https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/utils/README.md` (see slash between "e2e" and "utils")

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
"Homepage" link at https://www.npmjs.com/package/@woocommerce/e2e-utils leads to `404`

**Expected behavior**
It should link to `https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/utils/README.md`

**Actual behavior**
Links to `404 https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e-utils/README.md`

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://www.npmjs.com/package/@woocommerce/e2e-utils 
2. Click on "Homepage"
4. See 404

**Screenshots**
![404](https://user-images.githubusercontent.com/17435/129190702-92a59a02-bd25-4893-9ff2-a6101bb3f825.gif)

**Isolating the problem (mark completed items with an [x]):**
n/a
**WordPress Environment**
n/a

**Comment by tomalec** [comment]
@rrennick sorry for reviewing so late, but it seems the URL is still incorrect 
`https://github.com/woocommerce/woocommerce/tree/trunk/tests/utils/README.md` also gives 404

**Comment by rrennick** [comment]
@tomalec The new URL is `https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/utils/README.md`. 

npmjs.com won't be updated until we release the next version of the package.
