### ISSUE TITLE
Stats: Stats data doesn't take into account currency conversion

### ISSUE THREAD

**Issue by iamgabrielma** [woothemes/woocommerce#30495]
Stats data seems to ignore any currency conversion, so if the store currency is changed from the site settings, only the symbol is actually changed but the raw data is still the same. This causes that all aggregated data regarding sales, refunds, coupons, shipping, and fees will show as incorrect. 

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
It seems that we're displaying Stats data in a base currency only, and if the store currency is changed we only change the currency symbol but the raw data remains the same. Data points like sales, refunds, shipping, and coupons seem to be treated as raw numbers ignoring in which currency were performed, which may lead to data skew.

While converting currency at the exact exchange rate may be a bit overkill, I wonder if there's a way to use some of the official daily currency exchange rates, for example the rates at the time that the store currency is changed, to make this better.

**Expected behavior**
The data should be converted to the currency selected in the store settings.

**Actual behavior**
The data doesn't convert into the new currency set into the store settings.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

_In this case I used Japanese Yen and USD to make it more visible:_

1. Set your store to a different currency, in my case from USD to JPY
2. Refund an order, in this case 120.000 JPY
3. Switch back to your store's normal currency
4. Go to your store stats and see that so rather than a refund of 120.000 JPY ( ~1000 USD ), it is 120.000 USD

**Screenshots**

<img width="1237" alt="Screenshot 2021-08-13 at 08 24 10" src="https://user-images.githubusercontent.com/3812076/129291691-33e23dfd-d062-4a78-95f1-de90f1f2f90a.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @iamgabrielma,

Thanks for reporting the issue! 

Note that with the release of WooCommerce 4.0 in March 2019, these reports are deprecated and won’t receive further updates.

There is a new and better Analytics section available for users running WordPress 5.3+. Learn more about the new reports and admin experience in the [WooCommerce Analytics documentation](https://docs.woocommerce.com/document/woocommerce-analytics/). 

The same is stated in the [WooCommerce Reports documentation](https://docs.woocommerce.com/document/reports/). 

With the above in mind, I am closing this issue as `won't fix`.
