### ISSUE TITLE
Cannot add variation to cart without javascript enabled

### ISSUE THREAD

**Issue by mttindustries** [woothemes/woocommerce#30496]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I don't know if this has been deliberately removed, I could have sworn I previously tested this last year and it worked fine. Basically if javascript is disabled on a product variation page, when selecting a variation and clicking on "add to cart" it comes up with an error message "Please choose product options by visiting [product title]" 

**Expected behavior**
Previously and I would have thought that when purchasing a variable product that the purchase still goes ahead without javascript enabled. 

**Actual behavior**
Instead the purchase doesn't go through and just goes to above error message.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. disable javascript in the browser
2. go to a product with variations
3. select a variation
4. click add to cart button.
5. See error message

**Screenshots**
https://ibb.co/0K75Mr7

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```

`
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2h mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.4.1 mod_perl/2.0.8 Perl/v5.16.3
PHP Version: 7.4.1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 7.57MB
Database Data Size: 5.41MB
Database Index Size: 2.16MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fm_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.30MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.44MB + Index: 0.59MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxcf_leads: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxcf_leads_detail: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_vxcf_leads_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_x4ml_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 63
acf-field-group: 14
attachment: 94
events: 1
page: 14
post: 2
product: 30
product_variation: 73
revision: 53
shipping_zone: 5
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.5.2

### Inactive Plugins (28) ###

Advanced Custom Fields: by Delicious Brains – 5.9.9
Advanced Custom Fields: ACF Country: by Nicolas Lemoine – 2.0.2
Advanced Custom Fields: Extended: by ACF Extended – 0.8.8.4
Advanced Custom Fields PRO: by Delicious Brains – 5.9.8
Akismet Anti-Spam: by Automattic – 4.1.10
Compress JPEG & PNG images: by TinyPNG – 3.2.1
Contact Form 7: by Takayuki Miyoshi – 5.4.2
Contact Form Entries: by CRM Perks – 1.2.0
Custom Post Type Editor: by OM4 – 1.4.2
Custom Post Type UI: by WebDevStudios – 1.9.2
Custom Upload Dir: by Ulf Benjaminsson – 3.4.6
Flexible Shipping: by WP Desk – 4.7.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Honeypot for Contact Form 7: by Nocean – 2.1
Post Types Order: by Nsp Code – 1.9.5.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Search Everything: by Sovrn
zemanta – 8.1.9

WebP Express: by Bjørn Rosell – 0.20.1
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.14
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.2.1
WooCommerce Advanced Shipping Zones: by Jeroen Sormani – 1.1.2
Woocommerce Bulk update variations Prices: by Itpathsolutions – 1.0.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.2
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.0.23
WooCommerce Stock Manager: by StoreApps – 2.6.0
WooCommerce Stripe Gateway: by WooCommerce – 5.3.0
Wp Maximum Upload File Size: by CodePopular – 1.0.6
X4 Media Library: by x4wp – 2.0.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 119
Oldest: 2021-08-10 20:15:00 +1000
Newest: 2021-08-13 16:46:24 +1000

Pending: 2
Oldest: 2021-08-13 17:46:24 +1000
Newest: 2021-08-13 17:46:24 +1000

### Status report information ###

Generated at: 2021-08-13 16:50:18 +10:00
`
</details>

**Comment by lkraav** [comment]
> Previously and I would have thought that when purchasing a variable product that the purchase still goes ahead without javascript enabled.

I think this has required JS for a long long while now. Having worked on product page variation selection JS overrides, my insight here is that without JS you would indeed get something added to cart on POST, but it wouldn't be the correct variation.

If you look at https://github.com/woocommerce/woocommerce/blob/5.5.0/assets/js/frontend/add-to-cart-variation.js it does a lot of magic and probably also carries plenty legacy baggage, as it's very difficult to override any of its behavior.

**Comment by juliaamosova** [comment]
Hi @mttindustries,

Thank you for opening the issue! I plus one to @lkraav's comment above. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look as well. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @mttindustries,

Thanks for opening the issue. I'm also adding a plus one to @lkraav's comment. While it used to be possible to add a variation to the cart with javascript disabled, this actually led to issues, as the correct variation wasn't selected. We won't be able to fix this issue. While it may be possible to accomplish this with custom code, it's not anything that we'll be able to provide support for, as there's a lot of logic in the `add-to-cart-variation.js` file that would need to be carried over to any completely server-side implementation.
