### ISSUE TITLE
ability Exclude free shipping on special sales products.

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#30550]
hello
I wanted to send products for free, but shipping is not free for products that are for special sale. Unfortunately, this feature is not available in woocommerce.
Please add this feature so that we can exclude special sales products from free shipping.
**This feature will be such that if the user's products are not for special sale, shipping is free. But if the product is a special sale among the user's products, shipping costs will be charged.**

Please add this feature. It is very useful. thank you

**Comment by juliaamosova** [comment]
Hi @79ho3ein,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

In the meantime, you can check out these 2 plugins that provide the functionality you are looking for:

- [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/)
- [Per Product Shipping](https://woocommerce.com/products/per-product-shipping/)
