### ISSUE TITLE
Product Type option not appearing

### ISSUE THREAD

**Issue by mohammadhosseinz** [woothemes/woocommerce#30568]
Prerequisites (mark completed items with an [x]):

[x ] I have have carried out troubleshooting steps and I believe I have found a bug.
[x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
Describe the bug
Hi there,

There was a dropdown option next to "Product Type" which isn't appearing anymore as now I am unable to see the below options.

Expected behavior

I should have the option to add different types of product types such as:

Simple product
Grouped product
External/Affiliate product
Variable product
but I am unable to see these as there is no drop down menu.

Actual behavior

I am unable to see the above options

Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)
Steps to reproduce the bug:

Go to "Products"
Click on "Add New"
Scroll down to Product Data
and next to Product Data, there is no dropdown option
Screenshots
<img width="934" alt="Capture" src="https://user-images.githubusercontent.com/50516049/130641487-090d9aa9-d088-449f-b8fd-83cf96ae7b2d.PNG">

`
### WordPress Environment ###

WordPress address (URL): https://biomedicalbrain.ir
Site address (URL): https://biomedicalbrain.ir
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 280 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.11
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.7.31-cll-lve
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. 403
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: wp_
Total Database Size: 1.27MB
Database Data Size: 1.13MB
Database Index Size: 0.14MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.08MB + Index: 0.04MB + Engine MyISAM
wp_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_posts: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-08-24 13:04:28 +0000
Newest: 2021-08-24 15:05:29 +0000

### Status report information ###

Generated at: 2021-08-24 15:31:32 +00:00
`

**Comment by zhongruige** [comment]
Hi @mohammadhosseinz,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

* On WordPress 5.8 and WooCommerce 5.6, I navigated to `Products > Add New`
* The product type option showed as expected:

<img width="1326" alt="Screen Shot 2021-08-24 at 09 50 41" src="https://user-images.githubusercontent.com/71906536/130652252-3f0c006e-2163-4301-a44f-a03fa8197c8a.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

I am curious if there is perhaps a JavaScript error. Could you open your dev tools in your browser and see if there are any errors in the console?

<img width="1495" alt="Screen Shot 2021-08-24 at 09 56 50" src="https://user-images.githubusercontent.com/71906536/130652170-41c58979-2111-4c8d-bdb0-71f3114c8086.png">

Also, if you can try this in a private browser window, I am curious if the issue is still showing there as well.

Thank you in advance!

**Comment by mohammadhosseinz** [comment]
@zhongruige
Tank for your attention
<img width="951" alt="Capture1" src="https://user-images.githubusercontent.com/50516049/130654740-7f1e51dc-99fc-407b-9116-10bc8ff40278.PNG">
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

**Comment by mohammadhosseinz** [comment]
@zhongruige
Tank for your attention
<img width="951" alt="Capture1" src="https://user-images.githubusercontent.com/50516049/130654740-7f1e51dc-99fc-407b-9116-10bc8ff40278.PNG">
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

**Comment by mohammadhosseinz** [comment]
> Hi @mohammadhosseinz,
> 
> Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end.
> 
> * On WordPress 5.8 and WooCommerce 5.6, I navigated to `Products > Add New`
> * The product type option showed as expected:
> 
> <img alt="Screen Shot 2021-08-24 at 09 50 41" width="1326" src="https://user-images.githubusercontent.com/71906536/130652252-3f0c006e-2163-4301-a44f-a03fa8197c8a.png">
> 
> Please provide us with more details about the issue which may help us to evaluate it further.
> 
> I am curious if there is perhaps a JavaScript error. Could you open your dev tools in your browser and see if there are any errors in the console?
> 
> <img alt="Screen Shot 2021-08-24 at 09 56 50" width="1495" src="https://user-images.githubusercontent.com/71906536/130652170-41c58979-2111-4c8d-bdb0-71f3114c8086.png">
> 
> Also, if you can try this in a private browser window, I am curious if the issue is still showing there as well.
> 
> Thank you in advance!

**Comment by zhongruige** [comment]
Hi @mohammadhosseinz,

Thanks so much for the prompt reply and sharing those screenshots! It looks like you may have the Grammarly plugin or Chrome extension installed, and it seems to be throwing quite a few errors. Could you try disabling that and reloading the page, ideally with a hard refresh to make sure the cache is cleared? You can find instructions on how to do that here: https://www.documate.org/automation/what-is-a-hard-refresh-how-to-do-a-hard-refresh-in-any-browser/

Thanks!

**Comment by mohammadhosseinz** [comment]
@zhongruige
Thank you very much😊
<img width="960" alt="Capture3" src="https://user-images.githubusercontent.com/50516049/130657657-200b494d-90ca-44d6-a85f-1b3d11732e46.PNG">

**Comment by zhongruige** [comment]
> @zhongruige
> Thank you very much😊
> <img alt="Capture3" width="960" src="https://user-images.githubusercontent.com/50516049/130657657-200b494d-90ca-44d6-a85f-1b3d11732e46.PNG">

You're welcome! Glad that is working for you now @mohammadhosseinz!
