### ISSUE TITLE
[All Products] Selecting the "expand" chevron on a product row on mobile expands the row below

### ISSUE THREAD

**Issue by Garance91540** [woothemes/woocommerce#30567]
Hi! 

I found a small bug on the "All Products" section of WC Admin. 

1. Go to Products > All Products on mobile web
2. Select the chevron icon on the right edge of a product row to expand the row
3. You'll see that it opens the row under the selected row. It should open the row that was selected

Here's a video of that behavior:
https://cloudup.com/cDdeL4ICA5E

Let me know if you have any questions

**Comment by tammullen** [comment]
Thank you @Garance91540 for reporting the issue! However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26770 We are closing your issue in favor of the previously submitted.
