### ISSUE TITLE
I think I found a bug.

### ISSUE THREAD

**Issue by Yrerix** [woothemes/woocommerce#30562]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Paypal does not appear in payment methods and the Cart, Shop, etc. pages that have to be created automatically have not been created.

**Expected behavior**
I want to solve the problem since I cannot continue with my website.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @Yrerix,

Thank you for submitting the issue! 

Are you trying out WooCommerce for the first time or on a new site? Note that with WooCommerce 5.5 and above, PayPal Standard which is included in WooCommerce core will not be loaded by default. 

You can read about it in more detail and learn about the alternative options available in [Developer Advisory: PayPal standard will be hidden on new installs](https://developer.woocommerce.com/2021/07/12/developer-advisory-paypal-standard-will-be-hidden-on-new-installs/). 

Please let us know if you have any other questions or issues around it. We will keep this ticket open for a few more days.
