### ISSUE TITLE
Convert the product attributes lookup table creation process to a data migration

### ISSUE THREAD

**Issue by Konamiman** [woothemes/woocommerce#30564]
[The new product filtering by attributes using a lookup table feature](https://developer.woocommerce.com/2021/08/12/brace-yourselves-new-product-filtering-by-attributes-is-coming/) is initially aimed at experienced users for testing. As such, the table needs to be created manually via a dedicated tool in the Status - Tools page.

The second step towards enabling the feature for everybody (after https://github.com/woocommerce/woocommerce/issues/30563) would be to create and fill the lookup table automatically in a data migration. The manual creation and filling currently in place is already done via scheduled actions, so most of the infrastructure needed should be already in place.

Note that while the tool to delete the table should be removed, the tool to regenerate the table contents could be left in place.

**Comment by slightlyfaulty** [comment]
If the tool to regenerate the table contents is left in place, it might be a good idea to make it so the `woocommerce_attribute_lookup_enabled` setting isn't disabled every time it runs, like it currently does in `6.0.0-rc.1`.

**Comment by Konamiman** [comment]
Hi @slightlyfaulty, the setting needs to be disabled because the regeneration takes some time and meanwhile there's no available data to use in the table (the regeneration starts by erasing the table contents). The setting isn't disabled when regenerating one single product, though.
