### ISSUE TITLE
Investigate e2e test failure around Analytics pages › should allow a user to add a section back in

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#30581]
We've seen some failures around `Analytics pages › should allow a user to add a section back in` where it throws a `ode is either not visible or not an HTMLElement` error. Screenshots are showing that the element clicked in the test is visible, so we need to investigate a bit more into this.

Some initial results from @rrennick indicates that this could be due to differences between the Chromium version for Mac and Linux.

**Comment by rrennick** [comment]
Noting here that this issue stopped occurring when testing https://github.com/woocommerce/woocommerce/pull/31103 . The smaller viewport does seem like a good potential reason for these tests to fail in some scenarios.

**Comment by MrJnrman** [comment]
Also noting that with the addition of [test retries](https://github.com/woocommerce/woocommerce/pull/31336), flaky tests are more reliable. I'll be keeping an eye out for this issue occurring for the next 1.5 sprints and close/work it accordingly.

**Comment by MrJnrman** [comment]
Closing this since the tests have been stable.
