### ISSUE TITLE
REST API keys are not saved because API key label can be too long

### ISSUE THREAD

**Issue by ventsislaf** [woothemes/woocommerce#30594]
**Issue:**

We have an app where we request our customers to authorize our application in order to use the WooCommerce REST API. In many cases the API keys we got after the authorization were not valid. After some investigation we found out that the API keys are not persisted at all in the Wordpress database during the authorization step.

We don't have an access to the codebase of our customers but after looking at the source code we made few educated guesses and we found the potential issue – [the generation of the API key description](https://github.com/woocommerce/woocommerce/blob/ead815eea471d97335d6233c35cfcfc274686a0e/includes/class-wc-auth.php#L212-L219).

```php
$description = sprintf(
	/* translators: 1: app name 2: scope 3: date 4: time */
	__( '%1$s - API %2$s (created on %3$s at %4$s).', 'woocommerce' ),
	wc_clean( $app_name ),
	$this->get_i18n_scope( $scope ),
	date_i18n( wc_date_format() ),
	date_i18n( wc_time_format() )
);
```

**TLDR:** The generated `$description` is longer than the database constraint `varchar(200)`.

----

**Details:**

We know the API key is not persisted at all because in the [payload for the inserted ID](https://github.com/woocommerce/woocommerce/blob/ead815eea471d97335d6233c35cfcfc274686a0e/includes/class-wc-auth.php#L248) we get `0`.

In our case the `$scope` is `read_write` and the store is using a plugin for translations. Our guess is that the translation is either too long and it doesn't fit the database constraint or the translation is missing and the translation function is returning some kind of error message string that is too long. In either case, _the behaviour is flaky_ when it relies on translation and the outcome is unknown. The workaround we did for one of our customers was to force the English language and the API key got persisted as expected.

**Suggestion:**

Could we drop the translation entirely here? What about if we use a simpler format like `[APP_NAME] - API ([DATE])` or something else that relies on less variables with unknown values. Another option is to truncate the generated description.

**Comment by rodelgc** [comment]
Hi @ventsislaf,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Thanks for the report, agree with your suggestions, we need to do following things here:

1. Truncate app_name if longer than a certain limit, let's say 100
2. Drop English words so we can drop translation. So final string could look like : app_name - scope (date_time)
3. Throw an exception when insertion fails regardless.

**Comment by vedanshujain** [comment]
Eventually, we would like to move to [WordPress's application password](https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/) instead of using our own implementation.
