### ISSUE TITLE
"Personalize My Store" deletes saved theme customizer database entry.

### ISSUE THREAD

**Issue by CodeConnectPtyLtd** [woothemes/woocommerce#30592]
**Prerequisites (mark completed items with an [x]):**
- [ x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Hi Team,

I encountered an issue in WooCommerce 5.6.0, WordPress 5.8 & OceanWP Theme 3.05.

When uploading a logo via "Personalize My Store" (other steps skipped),  It reset the active theme's customizer settings stored in wp_options table -> option_name -> theme_mods_THEME_NAME.

I had a backup that I could restore from but I thought you'd like to know about this issue.

It appears that this issue is not related specifically to WooCommerce 5.6.0 as others users have reported this issue on the WordPress support forum approximately 6 months ago.:
https://wordpress.org/support/topic/woocommerce-shop-deleted-my-theme-customizations/

I have also opened a support request on the forums for clarity:
https://wordpress.org/support/topic/woocommerce-personalize-your-store-overwrites-theme-customizer-settings/

Thanks for your support and obviously WooCommerce is a wonderful plugin :)

**Comment by rodelgc** [comment]
Hi @CodeConnectPtyLtd,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Thanks for the report. I am closing this one in favor of https://github.com/woocommerce/woocommerce/issues/29996, both of these seems to have the same root cause, and 29996 is already prioritized and being worked upon.
