### ISSUE TITLE
Passing order item ID to WC_Order_Item loads WC_Order instead and throws an invalid order error

### ISSUE THREAD

**Issue by donjajo** [woothemes/woocommerce#30603]
It seems there is no function to get order item by id. I have googled so far, but I found nothing.
I have the order item id, but to load it up and get other data related to it, I had to do:
```php
new \WC_Order_Item( $id );
```
Which throws the error:
> Uncaught Exception: Invalid order. in woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:104

Meanwhile, this should be calling the `WC_Order_Item_Data_Store` class instead, not `WC_Order_Data_Store_CPT`

If I pass an order id to `WC_Order_Item`, it loads up the `WC_Order_Item` class but tries to call functions related to `WC_Order` and fails.

I made a slight change to my core files by returning `product` in `WC_Order_Item::get_type()` which fixed the issue for me. These are what I realized.
- `WC_Order_Item::get_type()` method is returning empty string, which it should be returning `product` by default?
- Also, I am guessing `WC_Order_Item_Product::get_type()` should return `product` instead of `line-item`? Looking at `WC_Data_Store::$stores`

I might be having this wrong, but looking at what exists on default data stores and behaviours, I think something is done wrong.

Thanks.

<details>
### WordPress Environment ###

WordPress address (URL): http://wordpress.localhost
Site address (URL): http://wordpress.localhost
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.4.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.34
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 11.30MB
Database Data Size: 9.18MB
Database Index Size: 2.12MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ld_notifications_delayed_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_learndash_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_user_activity: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_learndash_user_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.23MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 23
acf-field-group: 4
attachment: 10
elementor_library: 1
groups: 1
nav_menu_item: 5
page: 10
post: 2
product: 9
revision: 39
sfwd-certificates: 1
sfwd-courses: 8
sfwd-lessons: 1
sfwd-question: 1
sfwd-quiz: 1
sfwd-topic: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (24) ###

Advanced Custom Fields: Extended PRO: by ACF Extended – 0.8.8.4
Advanced Custom Fields PRO: by Delicious Brains – 5.9.9
Advanced Custom Fields: by Delicious Brains – 5.9.9
Alma Monthly Payments for WooCommerce: by Alma – 1.3.0
Astra Pro: by Brainstorm Force – 3.5.8
WP Portfolio: by Brainstorm Force – 1.11.3
Premium Starter Templates: by Brainstorm Force – 2.6.21
CartFlows: by CartFlows Inc – 1.7.0
Elementor: by Elementor.com – 3.4.2
LearnDash LMS - Certificate Builder: by LearnDash – 1.0.3
LearnDash LMS - Course Grid: by LearnDash – 1.7.0
LearnDash LMS - Elementor: by LearnDash – 1.0.3
LearnDash LMS - Notifications: by LearnDash – 1.5.3
LearnDash LMS - ProPanel: by LearnDash – 2.1.4.1
LearnDash LMS - Stripe Integration: by LearnDash – 1.8.1
LearnDash Trainers: by TheCodingMachine – 1.0
LearnDash LMS - WooCommerce Integration: by LearnDash – 1.9.3
LearnDash LMS: by LearnDash – 3.4.2.1
Ultimate Addons for Elementor: by Brainstorm Force – 1.33.2
User Role Editor: by Vladimir Garagulya – 4.60.1
WooCommerce Stripe Gateway: by WooCommerce – 5.4.0
WooCommerce Product Bundles: by SomewhereWarm – 6.11.1
WooCommerce: by Automattic – 5.6.0
Yoast SEO: by Team Yoast – 16.9

### Inactive Plugins (3) ###

Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.1.0
Akismet Anti-Spam: by Automattic – 4.1.10
WPForms Lite: by WPForms – 1.6.8.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /boutique/
Cart: #7 - /panier/
Checkout: #8 - /commander/
My account: #9 - /mon-compte/
Terms and conditions: ❌ Page not set

### Theme ###

Name: TheCodingMachine
Version: (update to version 0 is available)
Author URL: https://www.linkedin.com/in/donjajo/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: tcm-diagt/woocommerce/content-product.php
tcm/woocommerce/content-single-product.php
tcm/woocommerce/loop/loop-end.php
tcm/woocommerce/loop/loop-start.php
tcm/single-product.php version - is out of date. The core version is 1.6.4

Outdated Templates: ❌
					
					
						Learn how to update

### Product Bundles ###

Database Version: 6.11.1
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Complete: 58
Oldest: 2021-08-11 18:17:07 +0200
Newest: 2021-08-20 20:58:59 +0200

Pending: 5
Oldest: 2021-08-26 20:37:09 +0200
Newest: 2021-08-26 22:03:40 +0200

### Status report information ###

Generated at: 2021-08-29 18:16:58 +02:00
</details>

**Comment by donjajo** [comment]
The final solution for me was setting a default type in `WC_Order_Item::get_type()` to `line_item`

**Comment by rodelgc** [comment]
Hi @donjajo ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @donjajo , thanks for the suggestion,

To load an order item that you know is a product, you can use the order item class directly, like ` $order_item = new WC_Order_Item_Product( $id )`. This way you won't have to modify the core files.

> WC_Order_Item::get_type() method is returning empty string, which it should be returning product by default

So order items can be product, shipping items, tax, fees etc, so it cannot return `product` by default. However, class for the particular order item, does return that item type by default which is something you can use.

> I am guessing WC_Order_Item_Product::get_type() should return product instead of line-item? Looking at WC_Data_Store::$stores

Your suggestion is correct, but it's a line item for backward compatibility reasons, so we cannot change it. We [explicitly convert it into `product` to load the correct datastore on the fly](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-order-item.php#L71).

I closing the issue for repo maintenance, but let me know if the suggestion to use `$order_item = new WC_Order_Item_Product( $id )` does not work and can reopen and take another look.
