### ISSUE TITLE
Marketplace/Extensions: Improve the design of the extensions cards by adding titles and/or increasing the image sizes for the text in them to be readable

### ISSUE THREAD

**Issue by zdenys** [woothemes/woocommerce#30600]
**Is your feature request related to a problem? Please describe.**

Currently, the cards shown for all extensions in WooCommerce > Marketplace/Extensions sections have:

- Very tiny images
- No titles

For example, if I search for PayPal, it's really hard for me to see if I'm looking at the right extension or not and recognize it from the list. Images are so tiny, and having no titles doesn't help either.

![image](https://user-images.githubusercontent.com/39308239/131212044-358d1a61-5e9c-41f6-8ace-8edcaf79cb59.png)

**Describe the solution you'd like**

Cards could be made more recognizable if the titles for the extensions were visible and if the image sizes could be increased. Possibly to make them look more like at https://woocommerce.com/products/

![image](https://user-images.githubusercontent.com/39308239/131211969-2601e0ca-4ecd-42d2-951d-1106519c6030.png)

![image](https://user-images.githubusercontent.com/39308239/131212153-7b7d8bd2-408c-4982-b767-0d29518c81ff.png)

There are no titles displayed, it's true, but images are big enough for the text (extension titles) in them to be readable.

**Describe alternatives you've considered**

None. 

**Additional context**

Every single time during the [Quick Start sessions](https://wordpress.com/support/quickstart-support/) where I show customers how to look for WooCommerce extensions, I personally struggled to find the extension I'm looking for in WooCommerce > Marketplace/Extensions due to what I described above. And so the only solution so far is to search at https://woocommerce.com/products/ directly.

I see a lot of work has been done in https://github.com/woocommerce/woocommerce/pull/30391, so hopefully the above can be considered too.

**Comment by zdenys** [comment]
Shared thoughts: p6JqRr-4f6-p2#comment-12034

**Comment by andfinally** [comment]
Thanks Denys, I absolutely agree about this issue. As discussed on the project thread, we're updating the product card in WooCommerce 5.7 to have a clearly visible title, and we'll soon be adding an "app icon" which will hopefully make it much easier to find the extension you're after. Below is the design we're working towards. I'll close this issue for now – please reopen if you find the changes don't completely solve this.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1647564/131498854-959a697c-8ad6-4a5f-b815-f060782fc2d1.png">
