### ISSUE TITLE
Manual Order Search for product isn't accessible via keyboard, but everything else  works.

### ISSUE THREAD

**Issue by simplysaru** [woothemes/woocommerce#30613]
User came on live chat to report this. I'm able to replicate it on my end as well. The user mentioned that this used to work until April 2021, but they aren't sure on which version it worked. I tested this from 5.6.0 until 4.9.0 but could replicate the issue even until 4.9.0.

**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you are trying to add an order manually from the dashboard, Keyboard access works on most aspects([Shipping doesn't](https://github.com/woocommerce/woocommerce/issues/26875)) of order creation except for the product search field to search for a product. The field does get selected, but typing further to enter the product name doesn't input any characters. One needs to use the mouse to select the field to enter characters which is an accessibility issue. 

**Expected behaviour**

The product search field should be selected and available to accept text input.

**Actual behaviour**
The field does get selected, but typing further to enter the product name doesn't input any characters. One needs to use the mouse to select the field again to enter characters which is an accessibility issue. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to the Orders dashboard, create a new order, 
2. Input all required info and use tab/enter keys to navigate fields.
3. Navigate to Add items, press enter, then tab key to select add products and enter to select product search field. 
4. Then two tab key presses select the product search field, but doesn't accept any text input. 

**Screenshots**
![Screen Capture on 2021-08-31 at 17-07-13](https://user-images.githubusercontent.com/2734132/131498457-c489d8d5-1923-4102-a8c9-5d079e466802.gif)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): http://woolocal.local
Site address (URL): http://woolocal.local
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 24.29MB
Database Data Size: 14.99MB
Database Index Size: 9.30MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 6.27MB + Index: 7.03MB + Engine InnoDB
wp_posts: Data: 1.09MB + Index: 0.27MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 1.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.41MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

afreg_fields: 1
attachment: 759
def_reg_fields: 10
page: 7
post: 2
product: 59
product_variation: 237
shop_order: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.7.1
Jetpack: by Automattic – 10.0
Custom User Registration Fields for WooCommerce: by Addify – 1.7.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.2
WooCommerce Stripe Gateway: by WooCommerce – 5.4.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.44
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce: by Automattic – 5.6.0
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Inactive Plugins (4) ###

Disable Real MIME Check: by Sergey Biryukov – 1.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
Product Variation Table Plugin: by FMEADDONS – 1.0.2
User Switching: by John Blackbourn & contributors – 1.5.7

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0 (update to version 3.8.1 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 240
Oldest: 2021-08-02 06:03:19 +0000
Newest: 2021-08-31 11:48:46 +0000

### Status report information ###

Generated at: 2021-08-31 11:59:30 +00:00
`
</details>

**Comment by roykho** [comment]
Hi @simplysaru - thanks for reporting however there is already an existing report of this issue here https://github.com/woocommerce/woocommerce/issues/30607 So I will be closing this one.
