### ISSUE TITLE
Importing Product Images. Will not attach images to the product

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#30621]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When Importing product via csv file. All images is unattached to the products.So when you open the media menu, all images you just imported will be shown as unattached. This is bad. Because media cleaner plugin usually will clean unattached media files.

It will not happen when using "WooCommerce Product CSV Import Suite". All images will get attached to the products correctly.

**Expected behavior**
 All images should get attached to the products after import

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Delete all woocommerce sample products
2. Delete all woocommerce sample product images
3. Download sample file here: https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv
4. Import it
5. See the media library, all imported images will be unattached

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by erikdemarco** [comment]
The problem is in https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/import/abstract-wc-product-importer.php#L277

set_image_data( ) should be run after $object->save(); 
Because if it runs before, the product_id will be 0. Thus the attachment parent_id will still be 0

**Comment by tammullen** [comment]
Hi @erikdemarco ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27281. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
