### ISSUE TITLE
E2E: Create an e2e test to cover the flow of copying billing/shipping address on the order page

### ISSUE THREAD

**Issue by juliaamosova** [woothemes/woocommerce#30622]
Create an e2e test to cover the test case described in https://github.com/woocommerce/woocommerce/issues/30075. 

The following steps may be used, but feel free to add more steps or assertions if they're critical to the "Copy billing address" or "Load billing/shipping address" flow.

Pre-test setup:
1. There should be a customer with no customer billing and shipping addresses saved in their profile.

#### "Load billing & shipping" test steps:
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Select the test customer.
5. Save the order.
6. In the customer's profile, add a billing and shipping address.
7. Reopen the order.
8. Click 'Load billing address'.
9. Assert that the billing address was loaded.
10. Click 'Load shipping address'.
11. Assert that the shipping address was loaded.
12. Save the order.
13. Assert that both the billing and shipping addresses were saved in the order.

#### "Copy billing" test steps.
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Fill up the "Billing" section completely.
5. Click 'Copy billing address'.
6. Assert that the billing address was copied over to the shipping address.
7. Save the order.
8. Assert that both the billing and shipping addresses were saved.

**Comment by rodelgc** [comment]
The following steps may be used, but feel free to add more steps or assertions if they're critical to the "Copy billing address" or "Load shipping address" flow.

Pre-test setup:
1. There should be a customer with no customer billing and shipping addresses saved in their profile.


"Load billing & shipping" test steps:
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Select the test customer.
5. Save the order.
6. In the customer's profile, add a billing and shipping address.
7. Reopen the order.
8. Click 'Load billing address'.
9. Assert that the billing address was loaded.
10. Click 'Load shipping address'.
11. Assert that the shipping address was loaded.
12. Save the order.
13. Assert that both the billing and shipping addresses were saved in the order.

"Copy billing" test steps.
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Fill up the "Billing" section completely.
5. Click 'Copy billing address'.
6. Assert that the billing address was copied over to the shipping address.
7. Save the order.
8. Assert that both the billing and shipping addresses were saved.

**Comment by veljkho** [comment]
Looks like we have coverage for the load billing details, but it seems we don't have coverage for the copy details.
- [merchant/order-edit.spec.js#L213](https://github.com/woocommerce/woocommerce/blob/7d5b3a81a28eb56a98a879828b7cdd9d84df1b5a/plugins/woocommerce/tests/e2e-pw/tests/merchant/order-edit.spec.js#L213)
