### ISSUE TITLE
Support non interactive generation of woocommerce Rest API keys

### ISSUE THREAD

**Issue by buddudevelopers** [woothemes/woocommerce#30649]
**Is your feature request related to a problem? Please describe.**
It is frustrating to setup woocommerce api keys manually in non interactive environments like docker

**Describe the solution you'd like**
Have the ability to generate woocommerce rest api keys via the commandline non interactively for example using wp wc cli

**Describe alternatives you've considered**
I have considered directly editing the database to add the keys but this  feels like a hack
**Additional context**

**Comment by tammullen** [comment]
Hi @buddudevelopers ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
