### ISSUE TITLE
PHP Notice: "is_page or is_singular incorrectly called" on each wp-cron / 404 error / etc. if nocache_headers() is called

### ISSUE THREAD

**Issue by yoancutillas** [woothemes/woocommerce#30646]
Hello, an error repeatedly appears in the PHP error logs.

- `nocache_headers()` is called and it should be fine to do so for any page.
- This triggers a filter in WooCommerce that calls `WC_Cache_Helper::additional_nocache_headers()`
- The consecutive call to `is_page()` or `is_singular()` triggers the warning on this kind of pages (wp-cron, error, ... ). They lack some check it seems.

```
[03-Sep-2021 13:12:54 UTC] PHP  10. nocache_headers() C:\Users\me\websites\my-site.com\www\wp-content\plugins\qtranslate-xt\qtranslate_core.php:92
[03-Sep-2021 13:12:54 UTC] PHP  11. wp_get_nocache_headers() C:\Users\me\websites\my-site.com\www\wp-includes\functions.php:1487
[03-Sep-2021 13:12:54 UTC] PHP  12. apply_filters() C:\Users\me\websites\my-site.com\www\wp-includes\functions.php:1465
[03-Sep-2021 13:12:54 UTC] PHP  13. WP_Hook->apply_filters() C:\Users\me\websites\my-site.com\www\wp-includes\plugin.php:189
[03-Sep-2021 13:12:54 UTC] PHP  14. WC_Cache_Helper::additional_nocache_headers() C:\Users\me\websites\my-site.com\www\wp-includes\class-wp-hook.php:303
[03-Sep-2021 13:12:54 UTC] PHP  15. is_cart() C:\Users\me\websites\my-site.com\www\wp-content\plugins\woocommerce\includes\class-wc-cache-helper.php:67
[03-Sep-2021 13:12:54 UTC] PHP  16. is_page() C:\Users\me\websites\my-site.com\www\wp-content\plugins\woocommerce\includes\wc-conditional-functions.php:98
[03-Sep-2021 13:12:54 UTC] PHP  16. wc_post_content_has_shortcode() C:\Users\me\websites\my-site.com\www\wp-content\plugins\woocommerce\includes\wc-conditional-functions.php:98
[03-Sep-2021 13:12:54 UTC] PHP  17. is_singular() C:\Users\me\websites\my-site.com\www\wp-content\plugins\woocommerce\includes\wc-conditional-functions.php:421
[03-Sep-2021 13:12:54 UTC] PHP  18. _doing_it_wrong() C:\Users\me\websites\my-site.com\www\wp-includes\query.php:765
```

First described in: https://github.com/qtranslate/qtranslate-xt/issues/1062

How to reproduce the bug:
- Install qTranslate-XT (`nocache_headers()` is called in [qtranslate_core.php line 92](https://github.com/qtranslate/qtranslate-xt/blob/3.11.0/qtranslate_core.php#L92) on `'plugins_loaded'` hook, priority 2)
- visit `your-site.com/wp-cron.php`
- see your PHP error logs

**Comment by tammullen** [comment]
Hi @yoancutillas ,

Thank you for opening the issue! 
The issue you are having seems to be caused by the 3rd party plugin qTranslate-XT however I can see in the issue you link to that they have suggested this is a WooCommerce core issue.
It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
Hi @yoancutillas, thanks for your report. This indeed looks like a bug in WooCommerce, I'll mark it as such so that it goes to our tasks queue.

**Comment by Konamiman** [comment]
For the record, the problem seems to be that `noncache_headers` is forcing calls into WooCommerce's filters before the query runs; the fix would be adding an exit condition to check if `wp_query` is set before trying the `is_page` call.

**Comment by yoancutillas** [comment]
Thanks a lot!

**Comment by peterfabian** [comment]
This just produces a warning, but as far as I understand doesn't cause any other problems, so I'm inclined to reclassify as low priority. Please comment if you disagree.

**Comment by yoancutillas** [comment]
I agree, but Konamiman has actually already found how to fix it:
if you replace
```
if ( false !== strpos( $agent, 'Chrome' ) && is_cart() ) {
```
with
```
global $wp_query;
if ( false !== strpos( $agent, 'Chrome' ) && isset( $wp_query ) && is_cart() ) {
```
in [class-wc-cache-helper.php line 67](https://github.com/woocommerce/woocommerce/blob/5.8.0-rc.1/includes/class-wc-cache-helper.php#L67), the case is closed :)

**Comment by peterfabian** [comment]
@Konamiman do you reckon we should add create a PR for this? I think we can...

**Comment by Konamiman** [comment]
Yep, I think we can add that fix in a PR.

**Comment by Nic-Sevic** [comment]
👋 @peterfabian @Konamiman We seem to be seeing a related issue to this in all AT sites with WC active. 

`PHP Notice:  is_page was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8.2/wp-includes/functions.php on line 5663`

`PHP Notice:  is_singular was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8.2/wp-includes/functions.php on line 5663`

It looks like the frequency of these notices is increasing and is making troubleshooting AT sites a bit difficult. Any chance this could be reviewed again? Or if I'm misunderstanding the issue in this report I can open a new one

**Comment by crstauf** [comment]
Six months for a simple fix and nothing. 😖 

On one of my client sites this issue is triggered by Jetpack.

**Comment by crstauf** [comment]
@peterfabian @Konamiman Submitted PR #32747 in an attempt to get this small fix into the next version.

**Comment by crstauf** [comment]
> This just produces a warning, but as far as I understand doesn't cause any other problems, so I'm inclined to reclassify as low priority. Please comment if you disagree.

Yes it is high priority; maybe not for WooCommerce in an isolated environment, but it is in the real world.

This [comment](https://github.com/woocommerce/woocommerce/issues/30646#issuecomment-941044554) is discouraging: checking server error logs for issues when there are 10000s of meaningless warnings is very difficult. Then finding that the plugin author doesn't care because it's "only a warning" is exhausting. Why not just fix the warning, especially if it's an easy fix?

**Comment by lkraav** [comment]
> This https://github.com/woocommerce/woocommerce/issues/30646#issuecomment-941044554 is discouraging: checking server error logs for issues when there are 10000s of meaningless warnings is very difficult.

Not only direct server error logs, but quotas needlessly run out on external error tracking services like Sentry etc.

Talking about "low priority" unfortunately means the person has limited production environment experience.

**Comment by crstauf** [comment]
@peterfabian @Konamiman Please review the recent comments and accept the submitted PR.

**Comment by crstauf** [comment]
Also tagging @roykho for some attention.

**Comment by peterfabian** [comment]
Thanks for the ping and the PR, appreciated! @vedanshujain is going to review the PR soon.
