### ISSUE TITLE
$product->get_meta not returning correct data

### ISSUE THREAD

**Issue by ciclick** [woothemes/woocommerce#30652]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Using the woocommerce subscriptions plugin, at the file "woocommerce-subscriptions/includes/class-wc-subscriptions-product.php" inside the "get_meta_data" function, if I use the next order:

$meta_value = $product->get_meta( $prefixed_key, true );

it returns 0 for a product with a "subscription_sign_up_fee" meta_value. 

If I use this order instead:

$meta_value = get_post_meta($product->get_id() , $prefixed_key, true);

It returns the correct value. 

**Expected behavior**
That the function returns the correct meta_value for the "subscription_sign_up_fee" key

**Actual behavior**
The function returns allways 0 for the "subscription_sign_up_fee" meta_value

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Configure a subscription product with a sign up fee
2. Make a grouped product with this one and another product
3. Subscribe to this other product
4. Switch to the product with the sign up fee
5. The cart total is 0 instead of the sign up fee value

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://newsitebeta.tivify.es
Site address (URL): https://newsitebeta.tivify.es
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: ❌ 5.6.4 - Hay una versión nueva de WordPress disponible (5.8)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 7.4.23
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.68-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: Pkmywxn_
Tamaño total de la base de datos: 983.51MB
Tamaño de los datos de la base de datos: 527.96MB
Tamaño del índice de la base de datos: 455.55MB
Pkmywxn_woocommerce_sessions: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
Pkmywxn_woocommerce_order_items: Datos: 4.52MB + Índice: 1.52MB + Motor InnoDB
Pkmywxn_woocommerce_order_itemmeta: Datos: 37.55MB + Índice: 33.09MB + Motor InnoDB
Pkmywxn_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
Pkmywxn_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
codigos_postales: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_actionscheduler_actions: Datos: 32.06MB + Índice: 28.19MB + Motor InnoDB
Pkmywxn_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_actionscheduler_logs: Datos: 17.02MB + Índice: 14.03MB + Motor InnoDB
Pkmywxn_advanced_notifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_advanced_notification_triggers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_failed_logins: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_global_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_login_activity: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_login_lockdown: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_aiowps_permanent_block: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_comments: Datos: 45.58MB + Índice: 32.09MB + Motor InnoDB
Pkmywxn_ct_ugdpr_consent_log: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_fusion_forms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_fusion_form_entries: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_fusion_form_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_fusion_form_submissions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_icl_languages_translations: Datos: 0.20MB + Índice: 0.17MB + Motor InnoDB
Pkmywxn_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_icl_mo_files_domains: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_strings: Datos: 0.48MB + Índice: 0.41MB + Motor InnoDB
Pkmywxn_icl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_string_packages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_string_pages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_icl_string_positions: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_string_translations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_icl_string_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_translate: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_translate_job: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_icl_translations: Datos: 0.34MB + Índice: 1.06MB + Motor InnoDB
Pkmywxn_icl_translation_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_translation_downloads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_icl_translation_status: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_layerslider: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_layerslider_revisions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_oauth_access_tokens: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_oauth_authorization_codes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_oauth_jwt: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_oauth_public_keys: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_oauth_refresh_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_oauth_scopes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_options: Datos: 10.22MB + Índice: 1.06MB + Motor InnoDB
Pkmywxn_paytpv_customer: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_postmeta: Datos: 188.64MB + Índice: 196.88MB + Motor InnoDB
Pkmywxn_posts: Datos: 65.20MB + Índice: 14.89MB + Motor InnoDB
Pkmywxn_revslider_css: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_revslider_css_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_layer_animations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_navigations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_sliders: Datos: 0.08MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_revslider_sliders_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_slides: Datos: 0.11MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_revslider_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_revslider_static_slides: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_revslider_static_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_sm_sessions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_termmeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_term_relationships: Datos: 0.03MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_usermeta: Datos: 71.14MB + Índice: 83.89MB + Motor InnoDB
Pkmywxn_users: Datos: 3.52MB + Índice: 4.55MB + Motor InnoDB
Pkmywxn_wcs_payment_retries: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_wc_customer_lookup: Datos: 2.52MB + Índice: 1.92MB + Motor InnoDB
Pkmywxn_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_wc_order_product_lookup: Datos: 7.52MB + Índice: 7.06MB + Motor InnoDB
Pkmywxn_wc_order_stats: Datos: 6.52MB + Índice: 5.55MB + Motor InnoDB
Pkmywxn_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
Pkmywxn_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
Pkmywxn_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_yoast_indexable: Datos: 27.36MB + Índice: 22.41MB + Motor InnoDB
Pkmywxn_yoast_indexable_hierarchy: Datos: 3.52MB + Índice: 5.27MB + Motor InnoDB
Pkmywxn_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Pkmywxn_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
Pkmywxn_yoast_seo_links: Datos: 0.14MB + Índice: 0.11MB + Motor InnoDB

### Post Type Counts ###

acf-field: 19
acf-field-group: 2
attachment: 1004
avada_faq: 15
ct_ugdpr_service: 7
fusion_element: 9
fusion_form: 3
fusion_tb_layout: 4
fusion_tb_section: 5
fusion_template: 1
mc4wp-form: 1
nav_menu_item: 11
page: 41
post: 15
product: 13
product_variation: 1
revision: 890
shop_coupon: 4
shop_order: 51739
shop_subscription: 17355
slide: 1
sp_lc_shortcodes: 11
sp_logo_carousel: 156

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Query Monitor: por John Blackbourn – 3.7.1
WPML Multilingual CMS: por OnTheGoSystems – 4.4.10
Advanced Custom Fields: Theme Code: por Ben Pearson y Phil Kurth – 2.5.0
Advanced Custom Fields: por Elliot Condon – 5.9.6
All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.8

Ciclick: por Ciclick – 1.0
Ultimate GDPR & CCPA: por CreateIT – 2.9
Easy WP SMTP: por wpecommerce
alexanderfoxc – 1.4.6

Avada Builder: por ThemeFusion – 3.3.1
Avada Core: por ThemeFusion – 5.3.1
Invisible reCaptcha: por Mihai Chelaru – 1.2.3
JSM's Show Post Metadata: por JS Morisset – 1.3.0
JSM's Show User Metadata: por JS Morisset – 1.3.0
Loco Translate: por Tim Whitlock – 2.5.2
Logo Carousel: por ShapedPlugin – 3.2.13
Logo Carousel Pro: por ShapedPlugin – 3.3.16
MC4WP: Mailchimp for WordPress: por ibericode – 4.8.5
PAYCOMET Woocommerce: por PAYCOMET – 5.6
Prevent Browser Caching: por Kostya Tereshchuk – 2.3.2
Slider Revolution: por ThemePunch – 6.4.8
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.16.56

WebP Express: por Bjørn Rosell – 0.19.0
WooCommerce One Page Checkout: por Automattic – 1.7.11
WooCommerce Subscriptions CSV Importer and Exporter: por Prospress Inc – 2.1.0
WooCommerce Subscriptions: por WooCommerce – 3.0.13
WooCommerce: por Automattic – 5.5.1 (la actualización a la versión 5.6.0 está disponible)
Yoast SEO: por Equipo Yoast – 16.2
WP Bulk Delete: por Xylus Themes – 1.2.2
WP Post Popup: por Allure Web Solutions – 9999
WP Post Page Clone: por Gaurang Sondagar – 1.1
WP Rocket: por WP Media – 3.8.7
WP Session Manager: por Eric Mann – 4.2.0
WPML Media: por OnTheGoSystems – 2.6.4
WPML String Translation: por OnTheGoSystems – 3.1.8
WPML Translation Management: por OnTheGoSystems – 2.10.6

### Inactive Plugins (6) ###

Akismet Anti-Spam: por Automattic – 4.1.8
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.4.8
Direct Checkout for WooCommerce: por QuadLayers – 2.4.5
LayerSlider WP: por Kreatura Media – 6.11.5
WC Delete orders: por Rynaldo Stoltz – 1.1
WP Mass Delete: por CyberSEO.NET – 3.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #8 - tienda-test/
Carrito: #9 - carrito/
Finalizar compra: #998 - checkout/
Mi cuenta: #999 - my-account/
Términos y condiciones: #4773 - terminos-de-uso/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.3.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada-Child-Theme/woocommerce/cart/cart.php
Avada-Child-Theme/woocommerce/checkout/form-billing.php
Avada-Child-Theme/woocommerce/checkout/form-checkout.php
Avada-Child-Theme/woocommerce/checkout/form-login.php
Avada/woocommerce/checkout/form-pay.php
Avada-Child-Theme/woocommerce/checkout/payment.php
Avada-Child-Theme/woocommerce/checkout/review-order.php
Avada-Child-Theme/woocommerce/checkout/thankyou.php
Avada-Child-Theme/woocommerce/emails/customer-processing-order.php
Avada-Child-Theme/woocommerce/emails/email-addresses.php
Avada-Child-Theme/woocommerce/emails/email-customer-details.php
Avada-Child-Theme/woocommerce/emails/email-footer.php
Avada-Child-Theme/woocommerce/emails/email-header.php
Avada-Child-Theme/woocommerce/emails/email-order-details.php
Avada-Child-Theme/woocommerce/emails/email-styles.php
Avada-Child-Theme/woocommerce/global/form-login.php
Avada/woocommerce/loop/loop-start.php
Avada-Child-Theme/woocommerce/myaccount/dashboard.php
Avada-Child-Theme/woocommerce/myaccount/form-edit-account.php
Avada-Child-Theme/woocommerce/myaccount/form-login.php
Avada-Child-Theme/woocommerce/myaccount/my-account.php
Avada-Child-Theme/woocommerce/myaccount/my-address.php
Avada-Child-Theme/woocommerce/myaccount/orders.php
Avada-Child-Theme/woocommerce/order/order-details.php
Avada-Child-Theme/woocommerce/single-product/add-to-cart/grouped.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Suscripciones ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Activo
Subscriptions Live URL: https://newsitebeta.tivify.es
Subscriptions Template Theme Overrides: Avada-Child-Theme/woocommerce/emails/email-order-details.php
Avada-Child-Theme/woocommerce/myaccount/my-subscriptions.php
Avada-Child-Theme/woocommerce/myaccount/subscription-details.php
Avada-Child-Theme/woocommerce/myaccount/view-subscription.php

Subscription Statuses: trash: 1
wc-active: 17237
wc-expired: 15
wc-pending: 10
wc-on-hold: 18
wc-cancelled: 74

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Si
Cache Update Failures: ✔ 0 fallo

### Configuración de la tienda ###

Country / State: España — Barcelona

### Suscripciones por pasarela de pago ###

other: wc-active: 2
wc-cancelled: 2
wc-on-hold: 1

PAYCOMET: wc-active: 17093
wc-cancelled: 17
wc-expired: 15
wc-on-hold: 17
wc-pending: 10

### Compatibilidad de pasarelas de pago ###

PAYCOMET: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes

### Action Scheduler ###

Cancelada: 35
Oldest: 2021-08-09 01:26:35 +0000
Newest: 2021-08-31 01:26:13 +0000

Completo: 51.755
Oldest: 2021-08-31 11:22:24 +0000
Newest: 2021-09-07 17:00:50 +0000

Fallida: 12
Oldest: 2021-04-18 16:26:16 +0000
Newest: 2021-08-11 09:13:56 +0000

Pendiente: 17.253
Oldest: 2021-09-08 04:15:00 +0000
Newest: 2200-01-01 00:00:12 +0000

### Status report information ###

Generated at: 2021-09-07 18:07:51 +00:00

</details>

**Comment by tammullen** [comment]
Hi @ciclick ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin. 

I will also copy this issue to the developers of the plugin for their info

**Comment by tammullen** [comment]
Issue moved to [woocommerce/woocommerce-subscriptions #4187](https://github.com/woocommerce/woocommerce-subscriptions/issues/4187) via [**ZenHub**](https://www.zenhub.com/)
