### ISSUE TITLE
WooCommerce Status dashboard returns blank page for product summary

### ISSUE THREAD

**Issue by tsetend** [woothemes/woocommerce#30651]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
As reported in 4279137-zen when we click on the Product out of stock or Products low in stock summary in the WooCommerce Status dashboard it returns a blank page.

![screenshot](https://d.pr/i/rxOiuD+) **Image Link:** https://d.pr/i/rxOiuD

**Expected behavior**
I would expect it to list all the products that are either low in stock or out of stock. 

**Steps to reproduce the bug **
1. Go to 'dashboard'
2. Click on 'Products - out of stock or low in stock as mentioned in the above screenshot'
3. You will notice that it redirects you to a blank page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vinodglobalstep** [comment]
Hi @tsetend ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.6 version.

I have followed the exact steps mentioned. Here's the screencast:

https://user-images.githubusercontent.com/46351294/132535449-ff78a477-0650-497a-b9b8-4194617b1d73.mp4

Please provide us with more details about the issue which may help us to evaluate it further.
