### ISSUE TITLE
Customer Facing Order Page Allows Entering Billing/Shipping Address for Guest

### ISSUE THREAD

**Issue by DynAggelos** [woothemes/woocommerce#30686]
**Is your feature request related to a problem? Please describe.**
When I need to enter a customer's order manually, I am forced to ask ahead of time what the customer's address is. It would be a nice feature if it were possible to leave the address information blank, so that the customer can fill out this information him/herself, like they can on the checkout page.

**Describe the solution you'd like**
If the billing address information is left blank on a new order and the customer is Guest, the order page should include the checkout page's billing and shipping address fields, to allow the customer to enter their address information themselves. Additionally, a checkbox on the back end order page labeled "Allow customer to enter address," which grayed out the billing and shipping sections, would be nice, to make it clear whether the user wants their customer to be able to enter in a custom billing/shipping address for this order.

**Describe alternatives you've considered**
The only two alternatives I can think of is to 1) ask ahead of time for the customers billing/shipping address, or to 2) force all customers to register before having an order made for them. However, in many cases an order would be made for a customer specifically because they have trouble with computers or the website in the first place, so option two doesn't seem like a great solution with that in mind. The first option is do-able, but not ideal.

**Additional context**
![Capture](https://user-images.githubusercontent.com/35944457/132733924-5842141a-a331-41d2-8ae0-1b75942a0b86.png)
It would be nice to have a checkbox near the billing address section which allows choosing whether the customer can enter their own billing/shipping address on the order page.

**Comment by tammullen** [comment]
Hi @DynAggelos ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
