### ISSUE TITLE
Log WC version number when running `wc-e2e docker:up`

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#30687]
**Is your feature request related to a problem? Please describe.**
As a consumer of `@woocommerce/e2e-environment` package, I had a hard time finding what version of WooCommerce it is actually running.

That information is useful while investigating the CI logs, as well as running locally when testing a plugin against multiple versions of WC.

**Describe the solution you'd like**
I'd like to see WC version in use in the way I get WordPress & PHP versions:
```
WordPress 5.8.0
PHP 7.4.23
MariaDB 10.6.4
WooCommerce 5.6.0
```

**Describe alternatives you've considered**
1. It could be also useful, to have it logged in every e2e run.
2. I was trying to log it from my own `initialize.sh`, but [`echo`s from there](https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/docker/initialize.sh#L3) does not end up in the logs. So I ended up with only:
	```
	WordPress 5.8.0
	PHP 7.4.23
	MariaDB 10.6.4
	Initializing /home/tomalec/repos/google-listings-and-ads/tests/e2e/docker/initialize.sh
	Building with native build. …
	```

**Additional context**

**Comment by rrennick** [comment]
```
WordPress 5.8.0
PHP 7.4.23
MariaDB 10.6.4
Initializing /home/tomalec/repos/google-listings-and-ads/tests/e2e/docker/initialize.sh
Building with native build. …
```

@tomalec WooCommerce isn't installed at the time this runs in any repo other than `woocommerce`. However, version e2e-environment 0.2.3 has [`withRestApi. getSystemEnvironment()](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/utils#rest-api-withrestapi) that returns the WP & WC version. You could use that to log the WC version at the beginning of your tests.

**Comment by tomalec** [comment]
Thanks for the quick reply @rrennick :)

> WooCommerce isn't installed at the time this runs in any repo other than `woocommerce`. 

Hm… so when is the `/tests/e2e/docker/initialize.sh` run? I would like to log the version [once it's installed](https://github.com/woocommerce/google-listings-and-ads/blob/develop/tests/e2e/docker/initialize.sh#L13) not for any particular test.

**Comment by rrennick** [comment]
> so when is the /tests/e2e/docker/initialize.sh run?

It's called from `docker-compose` - https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/env/bin/docker-compose.js#L50:L90.

**Comment by rrennick** [comment]
@tomalec You could add the following to your initialize.sh

```
echo WooCommerce $(wp plugin status woocommerce | grep Version)
```

~~Edit to add: We should add this to our initialization scripts.~~

Edit #2: initialize.sh is logged to the docker logs vs the console. We'll keep this open to investigate if there is an alternative way to do this.

**Comment by tomalec** [comment]
>  version e2e-environment 0.2.3 has `withRestApi. getSystemEnvironment() that returns the WP & WC version.

How can I use it?

I tried:
```js
import {
	withRestApi,
	merchant, // eslint-disable-line import/named
} from '@woocommerce/e2e-utils';

describe( 'My test suite', () => {
	beforeAll( async () => {
		await merchant.login();
		const WCenv = await withRestApi.getSystemEnvironment();
		console.log( 'Starting tests with WC ', WCenv);
	} );
```

But it results in 

<details>
<summary><code>401 woocommerce_rest_cannot_view</code></summary>

```
Failed: HTTPResponse {
      "data": Object {
        "code": "woocommerce_rest_cannot_view",
        "data": Object {
          "status": 401,
        },
        "message": "Sorry, you cannot list resources.",
      },
      "headers": Object {
        "access-control-allow-headers": "Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type",
        "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages, Link",
        "connection": "close",
        "content-length": "107",
        "content-type": "application/json; charset=UTF-8",
        "date": "Tue, 14 Sep 2021 19:28:01 GMT",
        "link": "<http://localhost:8084/index.php?rest_route=/>; rel=\"https://api.w.org/\"",
        "server": "Apache/2.4.38 (Debian)",
        "vary": "Origin",
        "x-content-type-options": "nosniff",
        "x-powered-by": "PHP/7.4.13",
        "x-robots-tag": "noindex",
      },
      "statusCode": 401,
    }

       8 |
       9 | describe( 'Merchant who is getting started', () => {
    > 10 |      beforeAll( async () => {
         |      ^
      11 |              await merchant.login();
      12 |              const WCenv = await withRestApi.getSystemEnvironment();
      13 |              console.info( 'Starting tests with WC ', WCenv);

      at Env.beforeAll (../../jest/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:41:24)
      at Suite.<anonymous> (../../../tests/e2e/specs/get-started.test.js:10:2)
      at Object.<anonymous> (../../../tests/e2e/specs/get-started.test.js:9:1)
```

</details>

**Comment by rrennick** [comment]
> How can I use it?

Do you have the Basic Auth plugin installed and active?

**Comment by tomalec** [comment]
Nope, I didn't know I need to do that.

Personally, I find it strange that I need to install another plugin just to check the WC version being installed and run. Plus, it ads 1~2s on my local machine to the test's execution time. Not to mention the technical debt, of yet another dependency.

**Comment by rrennick** [comment]
> Nope, I didn't know I need to do that.

Unfortunately, it's unavoidable because the docker container is non-SSL and the REST API only supports basic authentication.

**Comment by tomalec** [comment]
I wonder, why do we need all that REST routing, couldn't `e2e/utils` or `e2e/env` expose those configurations directly and synchronously?

I totally get why production runtime system environment REST API needs to be behind authentication. But I don't get the reason why the developer/consumer of `@woocommerce/e2e*` package needs to authenticate to make it access some information from its config/initialize files.

(I'm not speaking about `withRestApi` itself, probably it has way more use-cases. I'm thinking more of something like `import getSomeEnvironmentSetupInformation from '@woocommerce/e2e-environment'`)

-----

Anyway, those are quite hypothetical ideas that went quite far from the original issue, of not being able to log the versions of plugins or actually anything from `initialize.sh` to the test log. And adding more (non-loggable) plugins, calling REST API, to console log it from an individual test, seems like working too far around to me.

**Comment by rrennick** [comment]
> I wonder, why do we need all that REST routing, couldn't e2e/utils or e2e/env expose those configurations directly and synchronously?

@tomedme I know this is an old issue but thought I should add this for posterity: Outside of this repo, WC is installed inside the docker container so the alternatives to the api are `wp shell`, `ssh` or the browser because we don't have access to the files.

I'm closing the issue as the `e2e-enviroment` package has been deprecated.
