### ISSUE TITLE
Product Category Widget - Add "All" Link Option To Redirect Back To Shop Archive.

### ISSUE THREAD

**Issue by amber-c** [woothemes/woocommerce#30685]
Currently there appears to be no option in either the Legacy or new Block Widgets to have an "All" link that re-directs a user back to the main Shop archive.

If a shop is not using Ajax based filters (i.e the Product Filters plugin), and just relying on the default widgets, this results in a poor user experience if they try to navigate back to view all products. They either have to use the main "Shop" in a primary menu (assuming it's been added), or potentially have to use the Back button on their browser multiple times.

It would be nice to see this get addressed in both Legacy and Block Widgets.

**Comment by tammullen** [comment]
Hi @amber-c ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
