### ISSUE TITLE
Add product to order requires extra click

### ISSUE THREAD

**Issue by hannahswain** [woothemes/woocommerce#30691]
**Is your feature request related to a problem? Please describe.**

When adding a product to the order screen, this requires an extra click - these clicks add up if you repeat the action often. 

1. Open a new or existing order
2. Click "Add product", the pop-up opens
3. Click "Search for a product", the search field appears 
4. Click in the search field to be able to start typing

![Add a product](https://d.pr/i/A7M92L+)
Full size: https://d.pr/i/A7M92L

**Describe the solution you'd like**

When the "search for a product" button is clicked, the search field should have focus so that you can immediately start typing. 

**Describe alternatives you've considered**

The current situation works but takes an extra click. If you repeat this many times a day, the time adds up.

**Additional context**

Reported via 4287686-zen

**Comment by roykho** [comment]
Hi @hannahswain - thanks for reporting. This is already fixed via https://github.com/woocommerce/woocommerce/pull/30626 and will be in 5.8 release.

**Comment by joerifrantz** [comment]
> Hi @hannahswain - thanks for reporting. This is already fixed via #30626 and will be in 5.8 release.

If it's already fixed why will it only come in the release of 5.8? And not just in 5.7?

Many of our customers have been affected by this bug and it is costing them all extra time to process orders.
