### ISSUE TITLE
HTTP API Error

### ISSUE THREAD

**Issue by Nick776** [woothemes/woocommerce#30700]
Hi There!

If we go in the WordPress backend and click to WooCommerce/Status QueryMonitor drops the following HTTP -API error:

Methode:
GET

URL:
https://api.wordpress.org/themes/info/1.2/
?action=theme_information
&request%5Bslug%5D=mh-magazine
&request%5Bfields%5D%5Bsections%5D=0
&request%5Bfields%5D%5Btags%5D=0
&request%5Blocale%5D=de_DE
&request%5Bwp_version%5D=5.7

Status:
404 Not Found
HTTP API Transport: curl
DNS Resolution Time: 0,0012
Connection Time: 0,1077
Zeit bis zum Beginn der Übertragung (TTFB): 0,3928
Response Size: 31 B
Response Content Type: application/json; charset=UTF-8
IP-Adresse: 198.143.164.251

Call-Function:
themes_api()
wp-admin/includes/theme.php:536
WC_Admin_Status::get_latest_theme_version()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php:251
WC_REST_System_Status_V2_Controller->get_theme_info()
wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php:1025
WC_REST_System_Status_V2_Controller->get_item_mappings_per_fields()
wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php:594
WC_REST_System_Status_V2_Controller->get_items()
wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php:75
WP_REST_Server->respond_to_request()
wp-includes/rest-api/class-wp-rest-server.php:1139
WP_REST_Server->dispatch()
wp-includes/rest-api/class-wp-rest-server.php:985
rest_do_request()
wp-includes/rest-api.php:479
WC_API->get_endpoint_data()
wp-content/plugins/woocommerce/includes/class-wc-api.php:97
WC_Admin_Status::status_report()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php:30
WC_Admin_Status::output()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php:23
WC_Admin_Menus->status_page()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php:287
do_action('woocommerce_page_wc-status')
wp-includes/plugin.php:484

Komponente:
Plugin WooCommerce

WooCommerce Status Report:
`
### WordPress Environment ###

WordPress address (URL): https://www.hello-world.net
Site address (URL): https://www.hello-world.net
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.3 - Es ist eine neuere Version von WordPress verfügbar (5.8.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 75 MB
PHP Time Limit: 60
PHP Max Input Vars: 3000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 10.4.21-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 248.98MB
Datenbank-Datengröße: 181.09MB
Datenbank-Indexgröße: 67.89MB
wp_2_woocommerce_sessions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_actions: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_actionscheduler_logs: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_adtribes_my_conversions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_alm: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_blocked_content_types: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_log: Daten: 14.60MB + Index: 37.99MB + Engine MyISAM
wp_2_bwg_album: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_album_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_comment: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_rate: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_tag: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_option: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_shortcode: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_theme: Daten: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_2_commentmeta: Daten: 0.33MB + Index: 0.11MB + Engine MyISAM
wp_2_comments: Daten: 0.60MB + Index: 0.09MB + Engine MyISAM
wp_2_duplicator_pro_entities: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_duplicator_pro_packages: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ewwwio_images: Daten: 20.56MB + Index: 3.53MB + Engine MyISAM
wp_2_ewwwio_queue: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider: Daten: 0.27MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider_revisions: Daten: 12.13MB + Index: 0.00MB + Engine MyISAM
wp_2_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_lockdowns: Daten: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_2_login_fails: Daten: 1.60MB + Index: 0.56MB + Engine MyISAM
wp_2_ms_snippets: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_pictures: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 2.83MB + Index: 0.11MB + Engine MyISAM
wp_2_postmeta: Daten: 38.64MB + Index: 15.91MB + Engine MyISAM
wp_2_posts: Daten: 70.83MB + Index: 4.04MB + Engine MyISAM
wp_2_reorder_post_rel: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_snippets: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_subscribe_reloaded_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_termmeta: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_2_terms: Daten: 0.18MB + Index: 0.34MB + Engine MyISAM
wp_2_term_relationships: Daten: 0.06MB + Index: 0.13MB + Engine MyISAM
wp_2_term_taxonomy: Daten: 0.15MB + Index: 0.26MB + Engine MyISAM
wp_2_tm_taskmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_tm_tasks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_categories: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_galleries: Daten: 0.90MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_items: Daten: 0.97MB + Index: 0.03MB + Engine MyISAM
wp_2_usermeta: Daten: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_2_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_admin_note_actions: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_category_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_comments_subscription: Daten: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_2_wc_customer_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_download_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_feedback_forms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_follow_users: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_product_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_stats: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_phrases: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_wc_product_meta_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_reserved_stock: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_users_rated: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_users_voted: Daten: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_2_wc_webhooks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfblockediplog: Daten: 0.13MB + Index: 0.09MB + Engine MyISAM
wp_2_wfblocks7: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfconfig: Daten: 0.39MB + Index: 0.02MB + Engine MyISAM
wp_2_wfcrawlers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilechanges: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilemods: Daten: 1.56MB + Index: 0.33MB + Engine MyISAM
wp_2_wfhits: Daten: 0.64MB + Index: 0.11MB + Engine MyISAM
wp_2_wfhoover: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfissues: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wfknownfilelist: Daten: 0.81MB + Index: 0.10MB + Engine MyISAM
wp_2_wflivetraffichuman: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflocs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflogins: Daten: 0.11MB + Index: 0.03MB + Engine MyISAM
wp_2_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wfnotifications: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfpendingissues: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfreversecache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfsnipcache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfstatus: Daten: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_2_wftrafficrates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_comments_subscription: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_phrases: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wpc_users_voted: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wplc_chat_msgs: Daten: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_ratings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_sessions: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_custom_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_departments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_offline_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_conversions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_goals: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_2_wprm_analytics: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wprm_ratings: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_indexable: Daten: 8.46MB + Index: 2.58MB + Engine MyISAM
wp_2_yoast_indexable_hierarchy: Daten: 0.29MB + Index: 0.80MB + Engine MyISAM
wp_2_yoast_migrations: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_primary_term: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_prominent_words: Daten: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_2_yoast_seo_links: Daten: 0.50MB + Index: 0.10MB + Engine MyISAM
wp_2_yoast_seo_meta: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

amn_smtp: 2
attachment: 2593
custom_css: 2
customize_changeset: 2
nav_menu_item: 27
oembed_cache: 37
page: 12
popup: 1
popup_theme: 6
post: 107
product: 36
revision: 3891
schema: 2
somdn_tracked: 38346
tablepress_table: 30
wpcf7_contact_form: 2
wpdiscuz_form: 3
wprm_recipe: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Query Monitor: von John Blackbourn – 3.7.1
Borlabs Cookie - Cookie Opt-in: von Benjamin A. Bornschein
Borlabs – 1.9.9

Classic Editor: von WordPress-Mitwirkende – 1.6.2
Code Snippets: von Code Snippets Pro – 2.14.1
Contact Form 7 Extension For Mailchimp: von Renzo Johnson – 0.5.46
Contact Form 7: von Takayuki Miyoshi – 5.4.2
EWWW Image Optimizer: von Exactly WWW – 6.2.4
Lightweight Social Icons: von Thomas Usborne – 1.1
Post Types Order: von Nsp Code – 1.9.5.6
Product Filter for WooCommerce: von XforWooCommerce – 8.2.0
Shortcodes Ultimate: von Vladimir Anokhin – 5.10.2
Free Downloads WooCommerce Pro: von Square One Media – 3.3.31
TablePress: von Tobias Bäthge – 1.14
Unite Gallery: von Valiano – 1.7.53
UpdraftPlus – Sichern/Wiederherstellen: von UpdraftPlus.Com
DavidAnderson – 2.16.61.25

WooCommerce: von Automattic – 5.6.0
Yoast SEO Premium: von Team Yoast – 17.1.2
Yoast SEO: von Team Yoast – 17.1
WP Mail SMTP: von WPForms – 3.0.3
WP Rezept Maker: von Bootstrapped Ventures – 7.5.1
WP STAGING PRO: von WP-STAGING – 4.0.3
wpDiscuz - Subscription Manager: von gVectors Team – 7.0.4
wpDiscuz: von gVectors Team – 7.3.0
Yoast SEO: WooCommerce: von Team Yoast – 14.4

### Inactive Plugins (1) ###

Classic Widgets: von WordPress Contributors – 0.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

WP STAGING Optimizer: von René Hermenau – 1.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #3312 - /jakobswegreisen-shop/
Warenkorb: #3314 - /warenkorb/
Kasse: #3316 - /kasse/
Mein Konto: #3318 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: MH Magazine Child Theme
Version: 1.0.0
Author URL: https://www.mhthemes.com/
Child Theme: ✔
Parent Theme Name: MH Magazine
Parent Theme Version: 3.9.9
Parent Theme Author URL: https://mhthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mh-magazine-child/woocommerce/single-product-reviews.php

### Action Scheduler ###

Abgeschlossen: 74
Oldest: 2021-09-05 11:30:27 +0200
Newest: 2021-09-09 08:10:44 +0200

Ausstehend: 1
Oldest: 2021-09-13 14:00:34 +0200
Newest: 2021-09-13 14:00:34 +0200

### Status report information ###

Generated at: 2021-09-12 09:03:31 +02:00
`

thnx for hleping

best regards
Nick
![2021-09-11_07h44_22](https://user-images.githubusercontent.com/43967959/132937676-d446e163-e871-40bc-997a-d863b7041f1f.png)

**Comment by tammullen** [comment]
Hi @Nick776 ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Nick776** [comment]
@tammullen sry for that, its my first post in github. Hope that it is all fine now.

**Comment by Nick776** [comment]
@tammullen Tam do you need more informations?

**Comment by simplysaru** [comment]
Hi @Nick776,

Sorry, we are unable to replicate this issue.  This issue is possibly coming from a plugin/theme on your site and not WooCommerce. This is what we see on our end. Please [test](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) for conflicts. 

![Markup on 2021-09-26 at 20:33:58](https://user-images.githubusercontent.com/2734132/134813310-21af202f-5227-4a14-b104-9f94e8b08677.png)

**Comment by Nick776** [comment]
Hi @simplysaru,

the problem is that our (premium)theme MH_Theme is not listed on WordPress.org. So we spoke to our theme provider. He says that they will not list the theme on WordPress and we should ask WooCommerce not to query this “parameter” any more.

Is it possible that you disable this query for this theme? It really sucks.

thnx for helping
Nick

**Comment by AashikP** [comment]
Hi there!

Thank you for clarifying.

WooCommerce System Status Report queries WordPress.org to check for updates to a theme in case the theme is found in WordPress.org: https://github.com/woocommerce/woocommerce/blob/release/5.8/includes/admin/class-wc-admin-status.php#L245

I am adding the `needs developer feedback` label to this issue so that the Core team could take a look and decide if this PHP notice needs to be addressed to account for custom themes not available in WordPress.org

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Nick776** [comment]
@AashikP 

Whow, sounds great. Thnx for helping AashipP. Because I think the error message is quite annoying for those whose provider has not registered the theme with Wordpress.org.

**Comment by barryhughes** [comment]
Hi @Nick776,

Thanks for the report!

I can imagine that the warning highlighted by Query Monitor might be a little annoying, but it sounds like:

* There are no functional problems (nothing is actually broken).
* The problem only shows up on the **WooCommerce ▸ Status** screen and not elsewhere.

Although the red styling used by Query Monitor might be a tad alarming at first sight, in surfacing this it's just trying to be helpful—it doesn't mean anything is actually broken, as such. In fact, all that is happening is we ask [api.wordpress.org](https://api.wordpress.org) for information about the theme and—in a case like this—it replies to tell us that it doesn't know anything about the theme. Part of the way it communicates this is via its HTTP response status (a 404).

> Is it possible that you disable this query for this theme?

That's not the most attractive option from our perspective. 

If simply ignoring it is not viable, you could conceivably write a small snippet to hide the problem. The following might act as a starting point (and you could for instance place it in a file like `wp-content/mu-plugins/suppress-wc-status-404-problem.php`):

```php
/**
 * A simple 'hack' to short-circuit WordPress.org theme API searches initiated
 * by the WooCommerce System Status screen.
 */
add_filter( 'rest_pre_dispatch', function ( $dispatch, $server, $request ) {
	if ( $request->get_route() === '/wc/v3/system_status' ) {
		add_filter( 'themes_api', function ( $do_not_short_circuit, $action, $args ) {
			$theme_slug = 'my-premium-theme'; // ← UPDATE! Set this to your theme slug.

			return $action === 'theme_information' && $args->slug === $theme_slug
				? (object) [ 'version' => 'x.y.z' ]
				: $do_not_short_circuit;
		}, 10, 3 );
	}

	return $dispatch;
}, 10, 3 );
```

- This is really just a possible 'starting point', if you wish to use it please review and do your own testing...
- ...and don't forget to update the `$theme_slug` as appropriate.
- If the code is added to a file by itself, don't forget to add a `<?php` tag to the top of the file.

I hope that helps, but will also close the issue.
