### ISSUE TITLE
ERROR Spec is invalid because the locale could not be retrieved in feed

### ISSUE THREAD

**Issue by Nick776** [woothemes/woocommerce#30710]
Hi There!

Every day we get the following error message in our WC log-file:

2021-08-31T16:09:03+00:00 ERROR Spec is invalid because the locale could not be retrieved in feed
2021-08-31T16:09:03+00:00 ERROR stdClass Object
(
    [slug] => mercadopago_q3_2021_ES
    [type] => marketing
    [status] => unactioned
    [is_snoozable] => 0
    [source] => woocommerce.com
    [locales] => Array
        (
            [0] => stdClass Object
                (
                    [locale] => es_ES
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [1] => stdClass Object
                (
                    [locale] => es_MX
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [2] => stdClass Object
                (
                    [locale] => es_CO
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [3] => stdClass Object
                (
                    [locale] => es_AR
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [4] => stdClass Object
                (
                    [locale] => es_CL
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [5] => stdClass Object
                (
                    [locale] => es_UY
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

            [6] => stdClass Object
                (
                    [locale] => es_PE
                    [title] => Cobrá con el Checkout de Mercado Pago
                    [content] => El procesador de pagos líder en América Latina ya está disponible para las tiendas de WooCommerce. Acepta pagos de forma segura con tarjetas de débito y crédito, dinero en efectivo, transferencias bancarias y meses con y sin interés, con el respaldo herramientas exclusivas de prevención del fraude.
                )

        )

    [actions] => Array
        (
            [0] => stdClass Object
                (
                    [name] => mercadopago_q3_2021_ES
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => es_ES
                                    [label] => Descargalo gratis
                                )

                            [1] => stdClass Object
                                (
                                    [locale] => es_MX
                                    [label] => Descargalo gratis
                                )

                            [2] => stdClass Object
                                (
                                    [locale] => es_CO
                                    [label] => Descargalo gratis
                                )

                            [3] => stdClass Object
                                (
                                    [locale] => es_AR
                                    [label] => Descargalo gratis
                                )

                            [4] => stdClass Object
                                (
                                    [locale] => es_CL
                                    [label] => Descargalo gratis
                                )

                            [5] => stdClass Object
                                (
                                    [locale] => es_UY
                                    [label] => Descargalo gratis
                                )

                            [6] => stdClass Object
                                (
                                    [locale] => es_PE
                                    [label] => Descargalo gratis
                                )

                        )

                    [url] => https://woocommerce.com/products/mercado-pago-checkout/?utm_source=inbox&utm_medium=product&utm_campaign=mercadopago_q3_2021_ES"
                    [url_is_admin_query] => 
                    [is_primary] => 1
                    [status] => actioned
                )

            [1] => stdClass Object
                (
                    [name] => dismiss
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => es_ES
                                    [label] => Desestimar
                                )

                            [1] => stdClass Object
                                (
                                    [locale] => es_MX
                                    [label] => Desestimar
                                )

                            [2] => stdClass Object
                                (
                                    [locale] => es_CO
                                    [label] => Desestimar
                                )

                            [3] => stdClass Object
                                (
                                    [locale] => es_AR
                                    [label] => Desestimar
                                )

                            [4] => stdClass Object
                                (
                                    [locale] => es_CL
                                    [label] => Desestimar
                                )

                            [5] => stdClass Object
                                (
                                    [locale] => es_UY
                                    [label] => Desestimar
                                )

                            [6] => stdClass Object
                                (
                                    [locale] => es_PE
                                    [label] => Desestimar
                                )

                        )

                    [url] => 
                    [url_is_admin_query] => 
                    [is_primary] => 
                    [status] => actioned
                )

        )

    [rules] => Array
        (
            [0] => stdClass Object
                (
                    [type] => publish_after_time
                    [publish_after] => 2021-08-30 00:00:00
                )

            [1] => stdClass Object
                (
                    [type] => publish_before_time
                    [publish_before] => 2021-09-10 00:00:00
                )

            [2] => stdClass Object
                (
                    [type] => not
                    [operand] => stdClass Object
                        (
                            [type] => or
                            [operands] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => plugins_activated
                                            [plugins] => Array
                                                (
                                                    [0] => woocommerce-gateway-stripe
                                                )

                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => plugins_activated
                                            [plugins] => Array
                                                (
                                                    [0] => woocommerce-paypal-payments
                                                )

                                        )

                                )

                        )

                )

            [3] => stdClass Object
                (
                    [type] => or
                    [operands] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => MX
                                )

                            [1] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => AR
                                )

                            [2] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => CO
                                )

                            [3] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => CL
                                )

                            [4] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => UY
                                )

                            [5] => stdClass Object
                                (
                                    [type] => base_location_country
                                    [operation] => =
                                    [value] => PE
                                )

                        )

                )

            [4] => stdClass Object
                (
                    [type] => or
                    [operands] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_MX
                                )

                            [1] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_AR
                                )

                            [2] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_CO
                                )

                            [3] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_CL
                                )

                            [4] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_UY
                                )

                            [5] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => es_PE
                                )

                        )

                )

        )

)

2021-08-31T16:09:03+00:00 ERROR Spec is invalid because the locale could not be retrieved in feed
2021-08-31T16:09:03+00:00 ERROR stdClass Object
(
    [slug] => mercadopago_q3_2021_PT
    [type] => marketing
    [status] => unactioned
    [is_snoozable] => 0
    [source] => woocommerce.com
    [locales] => Array
        (
            [0] => stdClass Object
                (
                    [locale] => pt_PT
                    [title] => Venda agora com o Checkout Mercado Pago
                    [content] => O líder em processamento de vendas na américa latina agora está disponível para WooCommerce. Aceite de forma segura pagamentos com cartão de débito e crédito, boleto, transferências bancárias e pagamentos parcelados- tudo isso apoiado por ferramentas exclusivas de prevenção a fraude.
                )

            [1] => stdClass Object
                (
                    [locale] => pt_BR
                    [title] => Venda agora com o Checkout Mercado Pago
                    [content] => O líder em processamento de vendas na américa latina agora está disponível para WooCommerce. Aceite de forma segura pagamentos com cartão de débito e crédito, boleto, transferências bancárias e pagamentos parcelados- tudo isso apoiado por ferramentas exclusivas de prevenção a fraude.
                )

        )

    [actions] => Array
        (
            [0] => stdClass Object
                (
                    [name] => mercadopago_q3_2021_PT
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => pt_PT
                                    [label] => Baixar grátis
                                )

                            [1] => stdClass Object
                                (
                                    [locale] => pt_BR
                                    [label] => Baixar grátis
                                )

                        )

                    [url] => https://woocommerce.com/products/mercado-pago-checkout/?utm_source=inbox&utm_medium=product&utm_campaign=mercadopago_q3_2021_PT
                    [url_is_admin_query] => 
                    [is_primary] => 1
                    [status] => actioned
                )

            [1] => stdClass Object
                (
                    [name] => dismiss
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => pt_PT
                                    [label] => Liberar
                                )

                            [1] => stdClass Object
                                (
                                    [locale] => pt_BR
                                    [label] => Liberar
                                )

                        )

                    [url] => 
                    [url_is_admin_query] => 
                    [is_primary] => 
                    [status] => actioned
                )

        )

    [rules] => Array
        (
            [0] => stdClass Object
                (
                    [type] => publish_after_time
                    [publish_after] => 2021-08-30 00:00:00
                )

            [1] => stdClass Object
                (
                    [type] => publish_before_time
                    [publish_before] => 2021-09-10 00:00:00
                )

            [2] => stdClass Object
                (
                    [type] => not
                    [operand] => stdClass Object
                        (
                            [type] => or
                            [operands] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => plugins_activated
                                            [plugins] => Array
                                                (
                                                    [0] => woocommerce-gateway-stripe
                                                )

                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => plugins_activated
                                            [plugins] => Array
                                                (
                                                    [0] => woocommerce-paypal-payments
                                                )

                                        )

                                )

                        )

                )

            [3] => stdClass Object
                (
                    [type] => base_location_country
                    [operation] => =
                    [value] => BR
                )

            [4] => stdClass Object
                (
                    [type] => or
                    [operands] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => pt_PT
                                )

                            [1] => stdClass Object
                                (
                                    [type] => option
                                    [option_name] => WPLANG
                                    [operation] => =
                                    [value] => pt_BR
                                )

                        )

                )

        )

)

Status Report:
`
### WordPress Environment ###

WordPress address (URL): https://www.hello-world.net
Site address (URL): https://www.hello-world.net
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.3 - Es ist eine neuere Version von WordPress verfügbar (5.8.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 75 MB
PHP Time Limit: 60
PHP Max Input Vars: 3000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 10.4.21-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 249.40MB
Datenbank-Datengröße: 181.33MB
Datenbank-Indexgröße: 68.07MB
wp_2_woocommerce_sessions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_actions: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_actionscheduler_logs: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_adtribes_my_conversions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_alm: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_blocked_content_types: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_log: Daten: 14.66MB + Index: 38.06MB + Engine MyISAM
wp_2_bwg_album: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_album_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_comment: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_rate: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_tag: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_option: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_shortcode: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_theme: Daten: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_2_commentmeta: Daten: 0.33MB + Index: 0.12MB + Engine MyISAM
wp_2_comments: Daten: 0.61MB + Index: 0.09MB + Engine MyISAM
wp_2_duplicator_pro_entities: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_duplicator_pro_packages: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ewwwio_images: Daten: 20.57MB + Index: 3.54MB + Engine MyISAM
wp_2_ewwwio_queue: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider: Daten: 0.27MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider_revisions: Daten: 12.13MB + Index: 0.00MB + Engine MyISAM
wp_2_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_lockdowns: Daten: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_2_login_fails: Daten: 1.60MB + Index: 0.56MB + Engine MyISAM
wp_2_ms_snippets: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_pictures: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 2.83MB + Index: 0.11MB + Engine MyISAM
wp_2_postmeta: Daten: 38.74MB + Index: 15.96MB + Engine MyISAM
wp_2_posts: Daten: 70.83MB + Index: 4.06MB + Engine MyISAM
wp_2_reorder_post_rel: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_snippets: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_subscribe_reloaded_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_termmeta: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_2_terms: Daten: 0.18MB + Index: 0.34MB + Engine MyISAM
wp_2_term_relationships: Daten: 0.06MB + Index: 0.13MB + Engine MyISAM
wp_2_term_taxonomy: Daten: 0.15MB + Index: 0.26MB + Engine MyISAM
wp_2_tm_taskmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_tm_tasks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_categories: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_galleries: Daten: 0.90MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_items: Daten: 0.97MB + Index: 0.03MB + Engine MyISAM
wp_2_usermeta: Daten: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_2_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_admin_note_actions: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_category_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_comments_subscription: Daten: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_2_wc_customer_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_download_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_feedback_forms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_follow_users: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_product_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_stats: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_phrases: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_wc_product_meta_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_reserved_stock: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_users_rated: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_users_voted: Daten: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_2_wc_webhooks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfblockediplog: Daten: 0.13MB + Index: 0.09MB + Engine MyISAM
wp_2_wfblocks7: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfconfig: Daten: 0.39MB + Index: 0.02MB + Engine MyISAM
wp_2_wfcrawlers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilechanges: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilemods: Daten: 1.56MB + Index: 0.33MB + Engine MyISAM
wp_2_wfhits: Daten: 0.64MB + Index: 0.11MB + Engine MyISAM
wp_2_wfhoover: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfissues: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wfknownfilelist: Daten: 0.81MB + Index: 0.10MB + Engine MyISAM
wp_2_wflivetraffichuman: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflocs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflogins: Daten: 0.11MB + Index: 0.03MB + Engine MyISAM
wp_2_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wfnotifications: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfpendingissues: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfreversecache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfsnipcache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfstatus: Daten: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_2_wftrafficrates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_comments_subscription: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_phrases: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wpc_users_voted: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wplc_chat_msgs: Daten: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_ratings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_sessions: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_custom_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_departments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_offline_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_conversions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_goals: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_2_wprm_analytics: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wprm_ratings: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_indexable: Daten: 8.51MB + Index: 2.59MB + Engine MyISAM
wp_2_yoast_indexable_hierarchy: Daten: 0.30MB + Index: 0.81MB + Engine MyISAM
wp_2_yoast_migrations: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_primary_term: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_prominent_words: Daten: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_2_yoast_seo_links: Daten: 0.50MB + Index: 0.10MB + Engine MyISAM
wp_2_yoast_seo_meta: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

amn_smtp: 2
attachment: 2598
custom_css: 2
customize_changeset: 2
nav_menu_item: 27
oembed_cache: 37
page: 12
popup: 1
popup_theme: 6
post: 108
product: 36
revision: 3950
schema: 2
somdn_tracked: 38475
tablepress_table: 32
wpcf7_contact_form: 2
wpdiscuz_form: 3
wprm_recipe: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Query Monitor: von John Blackbourn – 3.7.1
Borlabs Cookie - Cookie Opt-in: von Benjamin A. Bornschein
Borlabs – 1.9.9

Classic Editor: von WordPress-Mitwirkende – 1.6.2
Code Snippets: von Code Snippets Pro – 2.14.2
Contact Form 7 Extension For Mailchimp: von Renzo Johnson – 0.5.46
Contact Form 7: von Takayuki Miyoshi – 5.4.2
EWWW Image Optimizer: von Exactly WWW – 6.2.4
Lightweight Social Icons: von Thomas Usborne – 1.1
Post Types Order: von Nsp Code – 1.9.5.6
Product Filter for WooCommerce: von XforWooCommerce – 8.2.0
Shortcodes Ultimate: von Vladimir Anokhin – 5.10.2
Free Downloads WooCommerce Pro: von Square One Media – 3.3.31
TablePress: von Tobias Bäthge – 1.14
Unite Gallery: von Valiano – 1.7.53
UpdraftPlus – Sichern/Wiederherstellen: von UpdraftPlus.Com
DavidAnderson – 2.16.61.25

WooCommerce: von Automattic – 5.6.0
Yoast SEO Premium: von Team Yoast – 17.1.2
Yoast SEO: von Team Yoast – 17.1
WP Mail SMTP: von WPForms – 3.0.3
WP Rezept Maker: von Bootstrapped Ventures – 7.5.1
WP STAGING PRO: von WP-STAGING – 4.0.3
wpDiscuz - Subscription Manager: von gVectors Team – 7.0.4
wpDiscuz: von gVectors Team – 7.3.1
Yoast SEO: WooCommerce: von Team Yoast – 14.4

### Inactive Plugins (1) ###

Classic Widgets: von WordPress Contributors – 0.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

WP STAGING Optimizer: von René Hermenau – 1.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #3312 - /jakobswegreisen-shop/
Warenkorb: #3314 - /warenkorb/
Kasse: #3316 - /kasse/
Mein Konto: #3318 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: MH Magazine Child Theme
Version: 1.0.0
Author URL: https://www.mhthemes.com/
Child Theme: ✔
Parent Theme Name: MH Magazine
Parent Theme Version: 3.9.9
Parent Theme Author URL: https://mhthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mh-magazine-child/woocommerce/single-product-reviews.php

### Action Scheduler ###

Abgeschlossen: 76
Oldest: 2021-09-05 11:30:27 +0200
Newest: 2021-09-14 07:47:23 +0200

Ausstehend: 1
Oldest: 2021-09-20 14:01:04 +0200
Newest: 2021-09-20 14:01:04 +0200

### Status report information ###

Generated at: 2021-09-14 08:52:56 +02:00

Our shop does not using any payment functions at the moment as you can see here: 

https://www.hello-world.net/jakobswegreisen-shop/

Its only for downloading files (Pdfs)

thnx for helping
Nick

**Comment by juliaamosova** [comment]
Hi @Nick776,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [Mercado Pago Checkout](https://woocommerce.com/products/mercado-pago-checkout/) plugin which is one of the products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
