### ISSUE TITLE
[GlobalStep] For Atomic sites, "Marketplace" as header is displayed for "WooCommerce >> My Subscriptions" screen.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#30729]
## Bug Description:
"Marketplace" as header is displayed for "WooCommerce >> My Subscriptions" screen.

## Environment:
Woocommerce Version : WooCommerce 5.7.0 RC 1
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Login with valid credentials.
1. Install and activate WooCommerce 5.7.0 RC 1.
1. Complete the setup wizard.
1. Go to WooCommerce >> My Subscriptions.
1. Observe that "Marketplace" as header is displayed.

## Actual Result:
For Atomic sites, "Marketplace" as header is displayed for "WooCommerce >> My Subscriptions" screen.

## Expected Result:
My Subscriptions header should displayed for "WooCommerce >> My Subscriptions" screen.

## Screenshot:
![133648861-27ff70b5-1f92-4a79-a747-c572bf992d41](https://user-images.githubusercontent.com/4509348/133660555-d8ae8527-cca1-4d2d-848e-c4e30091ebd8.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Noting that this issue started happening in 5.7 beta. It's not specific to RC1.
Also, it only happens on Atomic sites that I created. But based on this internal conversation - p1629969197002400-slack-C01DT6U03HC - it doesn't happen on @andfinally's Atomic sites.

**Comment by rrennick** [comment]
The UI has changed (ie. My Subscriptions menu item was removed) and this is no longer applicable.
