### ISSUE TITLE
Importing Products Button 

### ISSUE THREAD

**Issue by jonathanhsholar** [woothemes/woocommerce#30725]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When attempting to import new products by clicking the "Import" button, I keep receiving an error message that says "This age isn't working...redirected too many times." 

I have cleared my cookies, and disabled any features that should cause the link to break. I have also attempted to circumvent this by going to the Woocommerce tab on my dashboard -> Get ready to start selling -> Add my products -> Import via CSV

All other links (Start a template, Add manually, and Import from from another service) all redirect as expected. 

**Expected behavior**
Page to redirect for various importing methods

**Actual behavior**
New page shows an error "This page isn't working"

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment]
Hi @jonathanhsholar ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I tested it using WC 5.6.0, and as you can see from the image below, I was able to import products just fine, without encountering the error you mentioned:
<img width="1365" alt="Screen Shot 2021-09-23 at 7 56 28 PM" src="https://user-images.githubusercontent.com/4509348/134502727-22add96a-961c-4ed9-8ca9-d0f6e8dfdc85.png">


Please provide us with more details about the issue which may help us to evaluate it further. 

Providing us with the screenshot of the problem as well as the System Status report will help a lot.
