### ISSUE TITLE
wcadmin_order_edit_recalc_totals track has invalid property format

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#30736]
The **wcadmin_order_edit_recalc_totals** track is being rejected, this is because it expects snake case for both the event name and the property keys.
The above track has a property key `OK_cancel` which doesn't follow this format, we should change it to `ok_cancel`.

https://github.com/woocommerce/woocommerce/blob/trunk/assets/js/admin/meta-boxes-order.js#L817-L829

See the tracks live view with rejected events enabled.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
**wcadmin_order_edit_recalc_totals** track event has an invalid property key `OK_cancel`.

**Expected behavior**
The property key should follow `^[a-z_][a-z0-9_]*$` pattern, changing it to `ok_cancel` will fix this.

**Actual behavior**
The event is rejected because of the invalid property format.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **WooCommerce > Orders** and create a new one or edit one
2. Add a product and click recalculate orders
3. Click either cancel or ok
4. Look in your console network tab for `t.gif` you can see one of the parameters being `OK_cancel`

**Comment by juliaamosova** [comment]
Hi @louwie17,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@louwie17 I assume there is no backward compatibility issue with this change right? seems like a straightforward fix, would you be interested in submitting a PR as well?

**Comment by louwie17** [comment]
> @louwie17 I assume there is no backward compatibility issue with this change right? seems like a straightforward fix, would you be interested in submitting a PR as well?

There shouldn't be any backwards compatibility issues here, as the track is getting rejected at the moment, so it wouldn't show up in funnels (if it was used).
I can certainly create a PR for this, I will put it on my to do list.
