### ISSUE TITLE
GitHub Actions: milestone action should not remove existing milestone

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#30734]
If a milestone has already been set for a PR, our action probably should not remove and overwrite it.

Script: [.github/workflows/scripts/assign-milestone-to-merged-pr.php](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/scripts/assign-milestone-to-merged-pr.php)
Example: https://github.com/woocommerce/woocommerce/pull/30712

**Comment by rrennick** [comment]
Addressed in https://github.com/woocommerce/woocommerce/pull/36549
