### ISSUE TITLE
wp wc does not allow product status of trash

### ISSUE THREAD

**Issue by WiredWonder** [woothemes/woocommerce#30737]
Using WP CLI to update products and can't set them to Trashed. This is often required instead of a hard delete where historical data is required (eg. order history or integration with 3rd party systems).

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
wp cli does gives an error when trying to use the trash status even thought the GUI supports it.

**Expected behavior**
trash status is allowed.

**Actual behavior**
CLI gives this error:
`Error: Invalid parameter(s): status {"status":400,"params":{"status":"status is not one of draft, pending, private, publish, and future."},"details":{"status":{"code":"rest_not_in_enum","message":"status is not one of draft, pending, private, publish, and future.","data":null}}}`

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Run `wp wc product update 1234 --status=trash`
2. 
**Screenshots**
na

**Isolating the problem (mark completed items with an [x]):**
- [] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
Can provide securely on request. WP 5.8.1, WC 5.6
```
</details>

**Comment by rrennick** [comment]
> Run wp wc product update 1234 --status=trash

@galapogos01 Use `delete` to trash a product:

```
wp wc product delete 1234
```

I'll close the issue.
