### ISSUE TITLE
WP passwords may not contain the character "\", however you can use it in My Account page

### ISSUE THREAD

**Issue by vyskoczilova** [woothemes/woocommerce#30731]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

WP passwords may not contain the character "\", however, you can use it on the My Account page

**Expected behavior**

Get the same error message as in WP Core.

**Actual behavior**
Password is changed, the user can't log in.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Try to change the User password to a password containing the character "\" (example: `F-tNzk^*%\<{0qWs&MPc`).
2. If you go via WP admin -> Profile, you'll get an error: Passwords may not contain the character "\".
3. If you try via the My Account page, you don't get the error, the password is changed, but you can't log in.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://getmantaportal.test
Site address (URL): http://getmantaportal.test
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Win64) OpenSSL/1.0.2q PHP/7.4.3
PHP Version: 7.4.3
PHP Post Max Size: 2 GB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: wp_
Total Database Size: 9.24MB
Database Data Size: 4.97MB
Database Index Size: 4.27MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_learndash_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_learndash_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_learndash_user_activity: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_learndash_user_activity_meta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_manta_sw_download: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.16MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.28MB + Index: 0.06MB + Engine InnoDB
wp_sabai_comment_post: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_sabai_comment_vote: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_content_post: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_sabai_entity_bundle: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_sabai_entity_field: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_sabai_entity_fieldcache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sabai_entity_fieldconfig: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_content_activity: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_sabai_entity_field_content_body: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_content_children_count: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_content_featured: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_sabai_entity_field_content_guest_author: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_content_parent: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_content_trashed: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_sabai_entity_field_field_images: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_questions_answer_accepted: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_questions_categories: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_questions_closed: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_questions_resolved: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_questions_tags: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_taxonomy_body: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_entity_field_taxonomy_content_count: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_entity_field_voting_favorite: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_sabai_entity_field_voting_flag: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_sabai_entity_field_voting_updown: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_sabai_entity_filter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sabai_file_file: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sabai_file_token: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sabai_system_addon: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sabai_system_adminroute: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_sabai_system_permission: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sabai_system_role: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sabai_system_route: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_sabai_taxonomy_term: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_sabai_taxonomy_term_tree: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sabai_voting_vote: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpsynchro_file_population_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpsynchro_sync_list: Data: 0.02MB + Index: 0.08MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 3
attachment: 14
nav_menu_item: 7
page: 21
post: 3
product: 2
revision: 101
sfwd-certificates: 1
sfwd-courses: 2
sfwd-lessons: 3
sfwd-question: 4
sfwd-quiz: 3
shop_order: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 3.7.1
Gravity Forms: by Gravity Forms – 2.5.9
Advanced Custom Fields: Gravityforms Add-on: by Danny van Holten – 1.2.8
AuthLDAP: by Andreas Heigl  – 2.4.10
Import and export users and customers: by codection – 1.17.8.4
Sabai Discuss: by onokazu – 1.4.8
Sabai: by onokazu – 1.4.8
User Role Editor: by Vladimir Garagulya – 4.60.1
WooCommerce: by Automattic – 5.6.0
WP Synchro: by WPSynchro – 1.6.4

### Inactive Plugins (1) ###

WooCommerce Stripe Gateway: by WooCommerce – 5.4.0

### Must Use Plugins (5) ###

kv.php: by  –
Manta Edge config.: by Karolína Vyskočilová – 0.0.1
new-user-email.php: by  –
Theme Guard: by Karolína Vyskočilová – 0.0.1
WP Synchro MU plugin: by WP Synchro – 1.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #113 - /shop/
Cart: #114 - /cart/
Checkout: #115 - /checkout/
My account: #116 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Getmanta - Portal
Version: 1.3.11
Author URL: https://kybernaut.cz
Child Theme: ✔
Parent Theme Name: Getmanta
Parent Theme Version: 5.7.4
Parent Theme Author URL: https://kybernaut.cz
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: getmanta-portal/woocommerce/emails\customer-reset-password.php
getmanta-portal/woocommerce/myaccount\form-edit-account.php
getmanta-portal/woocommerce/myaccount\orders.php

### Action Scheduler ###

Complete: 4
Oldest: 2021-08-19 09:03:49 +0000
Newest: 2021-09-17 11:07:40 +0000

Pending: 2
Oldest: 2021-09-17 11:07:48 +0000
Newest: 2021-09-17 11:07:49 +0000

### Status report information ###

Generated at: 2021-09-17 11:08:02 +00:00
`
</details>

**Comment by rodelgc** [comment]
Hi @vyskoczilova,

This issue seems specific to WordPress and not to WooCommerce Core. Please log an issue in the WordPress repository, which you can access from here - https://github.com/WordPress/WordPress.

I am closing this issue for now. But feel free to leave a comment in case I missed anything.
