### ISSUE TITLE
Cart quantities can appear incorrectly after modification

### ISSUE THREAD

**Issue by etoler1841** [woothemes/woocommerce#30733]
**Prerequisites**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
There is an extremely narrow issue in which the quantity display on the cart page may not match the actual quantity of an item in the cart. This issue is isolated to the quantity input; the line item total is still correct, as are the actual values stored on the back end. This issue stems from the way Firefox persists form data after a page refresh and is not a result of a programming issue within WooCommerce; however, a fix could be worked out using JavaScript to update the quantity field each time the page is loaded if this bug is deemed worth fixing.

**Expected behavior**
Anytime the cart page is refreshed, the quantity field should display the current quantity of the item in the cart.

**Actual behavior**
If the quantity of an item has been modified on the cart page in tab A, then modified again from any page in tab B, then refreshing tab A will show an incorrect quantity. (Specifically, it will show the value that was set when the cart was modified in tab A.)

**Steps to reproduce the bug**
(Note: This bug has so far been found only in Firefox. It is not present in Chrome. It has not been tested in other browsers.)
1. Add a product to your cart. There must be at least 2 of this product available.
2. Visit the cart page and modify the quantity of the item. Update the cart and confirm the quantity has been updated and that the item is still in your cart.
3. In a separate tab, visit the product page and add the product to your cart again. This must be the same product (and, if applicable, the same variation) you previously modified.
4. Refresh the original tab. The cart should now have updated totals reflecting the action taken in step 3. However, the quantity input will still display the same number you entered in step 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/37683339/133821639-4cff0e92-28de-40a4-8866-2b720ddce613.png)

**Isolating the problem**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

### WordPress Environment ###

WordPress address (URL): http://serials.local
Site address (URL): http://serials.local
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.4.20
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.34-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 4.54MB
Database Data Size: 3.11MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
page: 7
post: 3
product: 3
product_serial: 3
product_variation: 1
revision: 26

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (2) ###

Variation Images Gallery for WooCommerce: by RadiusTheme – 2.0.1.2
WooSerials: by Eric Toler <eric@bluesangelmusic.com> – 0.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
serial (serial)
serialized (serialized)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 2.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 119
Oldest: 2021-08-18 15:23:44 +0000
Newest: 2021-09-17 15:51:46 +0000

Pending: 1
Oldest: 2021-09-17 16:24:21 +0000
Newest: 2021-09-17 16:24:21 +0000

Failed: 57
Oldest: 2021-08-16 19:50:11 +0000
Newest: 2021-08-18 20:14:49 +0000

Canceled: 1
Oldest: 2021-08-20 16:33:17 +0000
Newest: 2021-08-20 16:33:17 +0000

### Status report information ###

Generated at: 2021-09-17 16:24:10 +00:00
</details>

**Comment by rodelgc** [comment]
Hi @etoler1841,

Thank you for submitting this issue. I can reproduce the issue on my end when I did a normal refresh on Firefox. However, when I did a hard refresh, the quantity was updated correctly. Here's the video of my test, where the last refresh I did in the end was a hard refresh:

https://user-images.githubusercontent.com/4509348/134510091-52f4a2ad-8a7e-4d34-b7b1-a8df4e27d40d.mov

I'll add a `needs developer feedback` label for the meantime so the Core team could decide whether this would be considered a bug or an enhancement, or if it's something that's already outside the scope of Core.

**Comment by vedanshujain** [comment]
This might be happening because of incorrect caching headers, or some change in firefox caching policy recently that we have not implemented yet. Thanks for the report, we will investigate and fix it. Note that there was a [similar issue in safari sometime back](https://github.com/woocommerce/woocommerce/issues/21544) and we had to add additional no-cache headers to fix it.
