### ISSUE TITLE
Benefit from PHPStan

### ISSUE THREAD

**Issue by szepeviktor** [woothemes/woocommerce#30765]
Hello!
Static analysis is equal to 100 additional WooCommerce developers :)
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬
👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬 👨‍🔬

`phpstan.neon.dist`
```neon
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    # On the way to level max
    level: 0
    scanFiles:
        - woocommerce.php
    scanDirectories:
        - packages/action-scheduler/classes/
        - packages/action-scheduler/deprecated/
    paths:
        - includes/
        - src/
```

:bulb: Currently it needs higher PHP version than WC.

I hope you will love it!

**Comment by szepeviktor** [comment]
Sent PR-s with the first two findings: #30763 #30764

**Comment by vedanshujain** [comment]
Thanks for the help. Looks like unit tests are failing on those PRs, can you please check if they are related?

**Comment by szepeviktor** [comment]
CI has a problem with installing `phpunit/phpunit`. Please see the above linked PR.
#30770 tries to fix it...

**Comment by rodelgc** [comment]
Thank you @vedanshujain for looking into it. I'll add a `needs developer feedback` since the author is requesting for some reviews.

**Comment by szepeviktor** [comment]
> the author is requesting for some reviews.

The reason this issue was opened is to 🧹 clean up your code base.
Do as you wish!

**Comment by rodelgc** [comment]
Changing this to an enhancement as it seems more appropriate.
