### ISSUE TITLE
WooCommerce updates to 5.6 / 5.7 restart WooCommerce Setup Wizard

### ISSUE THREAD

**Issue by seanvandermolen** [woothemes/woocommerce#30777]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I've had the issue on 3 separate WooCommerce sites I manage.  After logging in after the latest updates the WooCommerce Dashboard stats widget is replaced with the Setup Wizard and WooCommerce believes it needs to be setup when it already has.  Already had someone go through the setup process trying to get rid of it and the screwed up their shipping.

**Expected behavior**
An update for a store that has already been setup should not show the setup wizard.

**Actual behavior**
After the update, the setup wizard is unfinished and Finish Setup prompts are visible in all areas of Woocommerce admin pages.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Updates to 5.6 and 5.7 result in the setup wizard enabled.

**Screenshots**
https://snipboard.io/cIqh9J.jpg
https://snipboard.io/kJ7mDx.jpg

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment]
Hi @seanvandermolen ,

Thank you for taking the time to report this bug. We are already aware of the issue and our developers are now working on a fix. Please stay tuned for the fix!

**Comment by rodelgc** [comment]
Hi again @seanvandermolen,

I'm closing this issue now in favor of an earlier logged issue in the WooCommerce Admin repo - https://github.com/woocommerce/woocommerce-admin/issues/7696

You may monitor the progress of this issue there. Thanks!
