### ISSUE TITLE
wc_get_products() support querying by category and tag IDs

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#30778]
**Describe the solution you'd like**
I'd like to be able to query `wc_get_products()` and pass in a category or tag ID. IDs are always unique and so easier to store and translate. So querying by ID would be handy.

**Describe alternatives you've considered**

Support can be added by filtering in another query param:
```
function kia_query_by_ids( $wp_query_args, $query_vars ) {
	// Handle product categories by ID.
	if ( ! empty( $query_vars[ 'category_id' ] ) ) {
		unset( $wp_query_args['category_id'] );
		$wp_query_args['tax_query'][] = array(
			'taxonomy' => 'product_cat',
			'field'    => 'term_id',
			'terms'    => $query_vars['category_id'],
		);
	}

	// Handle product tags by ID.
	if ( ! empty( $query_vars['tag_id'] ) ) {
		unset( $wp_query_args['tag_id'] );
		$wp_query_args['tax_query'][] = array(
			'taxonomy' => 'product_tag',
			'field'    => 'term_id',
			'terms'    => $query_vars['tag_id'],
		);
	}

	return $wp_query_args;
}
add_filter( 'woocommerce_product_data_store_cpt_get_products_query', 'kia_query_by_ids', 10, 2 );
```

**Comment by rodelgc** [comment]
Hi @helgatheviking,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by helgatheviking** [comment]
Seems to be a case of switching the taxonomy query to `'field'    => 'term_id',` [here](https://github.com/woocommerce/woocommerce/blob/trunk/includes/data-stores/class-wc-product-data-store-cpt.php#L1864) though we'd probably need a clever way to distinguish if the value is an array of IDs or an array of slugs. OR use something like `category_id` as a query arg to differentiate like in my filter snippet.

**Comment by vedanshujain** [comment]
> Seems to be a case of switching the taxonomy query to 'field' => 'term_id'

we should add another field like `category_ids` to support searching via ids to differentiate. Otherwise, it will break any code which is using slugs currently. Your snippets look good, would you be interested in sending a PR?

**Comment by vedanshujain** [comment]
(Marking as low priority because workaround exist which will involve fetching slugs from IDs and then using those slugs to search instead).

**Comment by UraraReika** [comment]
Maybe a bit offtopic but still about  `wc_get_products()` and `WC_Product_Query`. I would like to know can we use `relation` parameter in `tax_query`? Like this:

```
$wc_query = new WC_Product_Query( array(
    'tax_query' => [
        'relation' => 'or',
        [
            'taxonomy' => 'product_cat',
            'field'    => 'slug',
            'terms'    => 'music',
        ],
        [
            'taxonomy' => 'custom-taxonomy-1',
            'field'    => 'slug',
            'terms'    => 'ct1-item-1',
        ]
    ]
) );
```

So if we use `'relation' => 'or'` we get all the products, if we use `'relation' => 'and'` or skip this parameter then we will get products that have music category and ct1-item-1 term.

Can we use `relation` parameter in `tax_query` with `WC_Product_Query`?
