### ISSUE TITLE
Tweak: Download filepaths - every download link broken

### ISSUE THREAD

**Issue by jamiepawprint** [woothemes/woocommerce#30772]
When updating WooCommerce to 5.7.0, the download file URL on the product page changes from https://domain.com/ to /var/www/html/, rendering the all download file links broken when using get_files().

Product Page, before update button pressed
![image](https://user-images.githubusercontent.com/91190204/134323687-67689856-dae2-4176-966c-62f603cb93e2.png)

Product Page, after update button pressed
![image](https://user-images.githubusercontent.com/91190204/134323815-5226c6fe-1ea7-423d-ad94-4137fabefd12.png)

Download link, before 5.7.0 update
https://pawprintfamily.com/wp-content/uploads/2021/08/Dreidel-Game-Instructions.pdf

Download link, after 5.7.0 update
https://pawprintfamily.com/var/www/html/wp-content/uploads/2021/08/Dreidel-Game-Instructions.pdf

**Comment by vedanshujain** [comment]
I can repro on my local environment, looks like this happens when download method is set to "Redirect (Unsecure)". While we work on a fix, can you check switching download method to "Force downloads" in WooCommerce > Setting > Product > Downloadable products fixes the issue?

**Comment by jamiepawprint** [comment]
Updated to "Force Downloads" doesn't seem to change anything. In the meantime i've added the below which seems to have temporarily fixed the issue.

`$files[] = str_replace('/var/www/html', 'https://pawprintfamily.com', $download["file"]);`

**Comment by dangrie158** [comment]
Can confirm the exact same issue. I temporarily fixed it in my reverse proxy by adding

```
server {
    ...
    rewrite ^/var/www/html/(.*)$ /$1 last;
    ...
}
```
