### ISSUE TITLE
Cannot see downloadable product permissions in latest update

### ISSUE THREAD

**Issue by pparker88** [woothemes/woocommerce#30779]
Upon updating to the latest WordPress today, I can no longer see Downloadable Product Permissions in Orders.

As seen below:
![Screen Shot 2021-09-22 at 2 55 49 PM](https://user-images.githubusercontent.com/47456438/134404890-97bbd7e8-da91-4961-b1e6-48614a397950.png)

There should be two downloadable items pictured above and I should be able to see the number of download attempts, be able to copy links download links, and revoke access.

**Comment by rodelgc** [comment]
Hi @pparker88 ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Downloadable product permissions are still showing up fine on my end after I upgraded my test site from WooCommerce 5.6 to 5.7. The image below shows the downloadable product permissions after the upgrade was made:

<img width="1086" alt="Screen Shot 2021-09-23 at 1 37 12 PM" src="https://user-images.githubusercontent.com/4509348/134459356-3b69be6b-9fef-400a-b371-0405601e7a80.png">


Please provide us with more details about the issue, particularly the steps you took to reproduce this issue and the System Status Report, which may help us to evaluate it further.

**Comment by dweuste** [comment]
Saw this that happened on 8 separate websites yesterday. They were not on WooCommerce 5.6.0 but on 5.6.1 and auto-updated to 5.7.0. Rolling back to 5.6.1 fixed the issue. Not only did all of the download permissions go away from past orders, new orders after the update weren't receiving download links or permissions, and new ones couldn't be added no matter the order status. And even worse in the products themselves, the variations with download files were not showing. They weren't lost - when I did a CSV export, the database information was still there - which was also shown by the fact that everything went back to normal after rolling back to 5.6.1. I was directed here from the WordPress Support forum.

**Comment by drsuperior11** [comment]
I have the exact same issue.  Logged the issue with WooCommerce Support and I was told their developers were aware of it and were working on it for a subsequent release.  My site is 5.6.0 trying to go to 5.7.0 and I had to revert back.

**Comment by pparker88** [comment]
Thanks for the replies!

Rolling back to 5.6.1 fixed the issue for me as well - I unfortunately did not do a System Status Report before rolling back, sorry.

My steps to reproduce were simply updating to 5.7.0 and the download permissions were gone. They did not show up in the UI on Safari or Google Chrome.

I do use Amazon s3 to host the download files - just in case that's of any help.

**Comment by drsuperior11** [comment]
> Thanks for the replies!
> 
> Rolling back to 5.6.1 fixed the issue for me as well - I unfortunately did not do a System Status Report before rolling back, sorry.
> 
> My steps to reproduce were simply updating to 5.7.0 and the download permissions were gone. They did not show up in the UI on Safari or Google Chrome.
> 
> I do use Amazon s3 to host the download files - just in case that's of any help.

Again, I had the exact experience and I too use Amazon s3 to host the download files.

**Comment by jonathansadowski** [comment]
Hi @pparker88, @dweuste, and @drsuperior11,

Thanks for all of the reports. This looks to be related to the S3 extension. I was able to reproduce it using that by following these steps:

1) Start with WooCommerce 5.6.1
2) Install and setup the "WooCommerce Amazon S3 Storage"
3) Create a new downloadable product using an S3 shortcode, such as `[amazon_s3 bucket=bucketname object=woologo.png]`
4) Purchase the product created in the previous step, and observe that the downloadable product permissions appear on the order.
5) Upgrade to WooCommerce 5.7.0
6) Return to the order, and note that those are now missing.

We'll address this shortly, stay tuned.

**Comment by dweuste** [comment]
@jonathansadowski - glad that worked. Can confirm all the sites I saw the issue on were also sites using S3. It happened both with those using the S3 Storage plugin and some that use the WP Offload S3 plugin from Delicious Brains (https://deliciousbrains.com/wp-offload-media/).

**Comment by drsuperior11** [comment]
Not only is our site using S3 but also utilize WP Offload Media from Delicious Brains.

**Comment by pparker88** [comment]
Glad you were able to replicate the bug!

My site uses the WooCommerce Amazon S3 Storage plugin.

**Comment by gr33ngrl** [comment]
WE are also experiencing this issue with 5.7 and Delicious Brains WP Offload Media.

**Comment by dweuste** [comment]
Reporting that so far on two sites at least, 5.7.1 has fixed the issue.

**Comment by drsuperior11** [comment]
We just updated to 5.7.1 and it resolved this issue.

**Comment by jonathansadowski** [comment]
Thanks for the confirmations that 5.7.1 resolved this issue!

**Comment by pparker88** [comment]
> Thanks for the confirmations that 5.7.1 resolved this issue!

Thank you so much for addressing this issue so quickly!

**Comment by gr33ngrl** [comment]
Thank you for resolving quickly. Hopefully, you'll add a unit test for this scenario to prevent in the future?
