### ISSUE TITLE
WP Woocommerce Dashboard 

### ISSUE THREAD

**Issue by kingyyyyyy** [woothemes/woocommerce#30782]
Hello,

Prior to latest version of Woocommerce (Version 5.7.0), the WP Dashboard would show boxes with Woocommerce items such as daily sales etc. Now, it shows a box with the title "Woocommerce Setup" (as shown in the attachment image). 

If you go through the setup process (even though everything was already setup), the steps won't update and will still show "2 out of 6", for example.

Tested this on two of my independent Woocommerce websites with the latest update, and the same issue occurs.

Looking forward to your update to bring back the WC boxes on dashboard. Thank you.

![700f17c71358572eaa1964dfc5444595](https://user-images.githubusercontent.com/54516457/134429622-819019cc-5195-4200-96a3-49caa93bc0b1.png)

**Comment by rodelgc** [comment]
Hello @kingyyyyyy,

Thank you for reporting this issue. We are already aware of this issue and our developers are now fixing it. I'm closing this issue as it has already been reported in https://github.com/woocommerce/woocommerce-admin/issues/7696. You can view the progress of the bug fix there. Thanks!
