### ISSUE TITLE
Settings submenus not working

### ISSUE THREAD

**Issue by nthnc** [woothemes/woocommerce#30787]
The submenu links are not working in the woocommerce settings menu, see screenshot attached ands system report below.

<img width="1397" alt="Screenshot 2021-09-23 at 14 31 56" src="https://user-images.githubusercontent.com/59650400/134516574-6691ae98-a6b6-4454-bfce-9a25e7f532b8.png">

System report:
`
### WordPress Environment ###

WordPress address (URL): https://ecomersh.co.uk
Site address (URL): https://ecomersh.co.uk
WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.4
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.33-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: LbEKlVkW
Total Database Size: 135.28MB
Database Data Size: 83.69MB
Database Index Size: 51.59MB
LbEKlVkWwoocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
LbEKlVkWwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwoocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
LbEKlVkWwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
LbEKlVkWwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWactionscheduler_actions: Data: 4.02MB + Index: 1.27MB + Engine InnoDB
LbEKlVkWactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWactionscheduler_logs: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
LbEKlVkWalm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWcommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWcomments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
LbEKlVkWe_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
LbEKlVkWe_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
LbEKlVkWe_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWmailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWmailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWoptions: Data: 8.06MB + Index: 1.14MB + Engine InnoDB
LbEKlVkWpostmeta: Data: 22.48MB + Index: 9.02MB + Engine InnoDB
LbEKlVkWposts: Data: 7.52MB + Index: 1.09MB + Engine InnoDB
LbEKlVkWsbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWsbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWsbi_instagram_posts: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWstock_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWtermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWterm_relationships: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
LbEKlVkWterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWusermeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
LbEKlVkWusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWwc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
LbEKlVkWwc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwc_product_meta_lookup: Data: 0.28MB + Index: 0.50MB + Engine InnoDB
LbEKlVkWwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWwfconfig: Data: 1.30MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwffilemods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfhits: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWwfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
LbEKlVkWwfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwflogins: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWwfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfpendingissues: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
LbEKlVkWwfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWwfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
LbEKlVkWwftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
LbEKlVkWwps_hit: Data: 0.23MB + Index: 0.83MB + Engine InnoDB
LbEKlVkWwps_index: Data: 25.22MB + Index: 31.39MB + Engine InnoDB
LbEKlVkWwps_key: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
LbEKlVkWwps_object_term: Data: 1.09MB + Index: 1.81MB + Engine InnoDB
LbEKlVkWwps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
LbEKlVkWwps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWwps_uri: Data: 0.47MB + Index: 0.16MB + Engine InnoDB
LbEKlVkWwps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWyoast_indexable: Data: 2.52MB + Index: 1.20MB + Engine InnoDB
LbEKlVkWyoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
LbEKlVkWyoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
LbEKlVkWyoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
LbEKlVkWyoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
LbEKlVkWyoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1554
elementor_library: 20
nav_menu_item: 20
oembed_cache: 3
page: 16
post: 24
product: 939
product_variation: 1953
revision: 2357
shop_coupon: 112
shop_order: 101
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Checkout Styling for WooCommerce and Elementor: by Skynet Solutions Inc. – 1.0.0
Elementor Pro: by Elementor.com – 3.4.1
Elementor: by Elementor.com – 3.4.4
F4 Total Stock Value for WooCommerce: by FAKTOR VIER – 1.1.5
Facebook for WooCommerce: by Facebook – 2.6.5
Smash Balloon Instagram Feed: by Smash Balloon – 2.9.3.1
Jetpack: by Automattic – 10.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.3
TinyPNG - JPEG, PNG & WebP image compression: by TinyPNG – 3.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.61

Country Based Restrictions for WooCommerce: by zorem – 3.1
WooCommerce Dropshipping: by OPMC Australia Pty Ltd – 3.6
WooCommerce Stripe Gateway: by WooCommerce – 5.5.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.3
WooCommerce Product Search: by itthinx – 4.0.1
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce Social Login: by SkyVerge – 2.11.0
WooCommerce: by Automattic – 5.7.0
Wordfence Security: by Wordfence – 7.5.5
Yoast SEO: by Team Yoast – 17.2
WP Fastest Cache: by Emre Vona – 0.9.4

### Must Use Plugins (2) ###

1&1 Product Subdomain: by 1&1 – 1.1.0
Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #236 - /shop/
Basket: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #238 - /checkout/
My account: #239 - /my-account/
Terms and conditions: #1260 - /terms-and-conditions/

### Theme ###

Name: Hello Elementor Child
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.4.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: hello-theme-child-master/woocommerce/emails/customer-processing-order.php

### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: ✔ Available
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Canceled: 1
Oldest: 2021-08-30 12:52:20 +0100
Newest: 2021-08-30 12:52:20 +0100

Complete: 3,963
Oldest: 2021-09-23 14:05:17 +0100
Newest: 2021-09-23 14:21:18 +0100

Failed: 8
Oldest: –
Newest: –

Pending: 1
Oldest: 2021-09-24 12:20:40 +0100
Newest: 2021-09-24 12:20:40 +0100

### Status report information ###

Generated at: 2021-09-23 14:27:33 +01:00
`

**Comment by rodelgc** [comment]
Hi @nthnc,

The issue you're experiencing seems to be from a 3rd party plugin and not from WooCommerce Core. I don't see a "Dropshipping" tab in Core, and the links here should like like these instead of as buttons:
<img width="930" alt="Screen Shot 2021-09-23 at 9 56 33 PM" src="https://user-images.githubusercontent.com/4509348/134520692-a5e41f74-989e-4fc0-9455-4ba0c0d81069.png">

If you can confirm that this issue is caused by another plugin, please contact its author directly for further help. I will leave this issue open for your feedback.

**Comment by nthnc** [comment]
Hi @rodelgc 

Yep, the links are not links as the other tabs.

The dropshipping plugin was purchased via woocommerce and the support links all point to woocommerce and not the plugin developer. Perhaps my query is misplaced here. Thanks for looking at it for me.

**Comment by simplysaru** [comment]
Hi @nthnc,

Looks like the DropShipping plugin is supported by a third-party developer. 
<img width="1613" alt="Markup 2021-09-26 at 18 57 16" src="https://user-images.githubusercontent.com/2734132/134810116-9c6c7f2f-3754-4fb5-a173-7f1c32df2bb3.png">

Please work with them. This isn't a WooCommerce bug. You can send an email to them [directly](https://woocommerce.com/my-account/create-a-ticket/).
