### ISSUE TITLE
WooCommerce database update required after updating to 5.7.0 doesn't go away

### ISSUE THREAD

**Issue by thesfboy** [woothemes/woocommerce#30781]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
WooCommerce database update required after updating to 5.7.0 doesn't go away even after clicking update woocommerce database.
**Expected behavior**
This popup should go away.
**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 
After updating to Woocommerce 5.7.0, I get the message when I click status: WooCommerce database update required
WooCommerce has been updated! To keep things running smoothly, we have to update your database to the newest version. The database update process runs in the background and may take a little while, so please be patient. Advanced users can alternatively update via WP CLI. But after a while, on the Dashboard, I get the message that the database has been updated and when I click status again, the notification persists. 
**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Status'
2. Click on 'Update Woocommerce Database'
3. Scroll down to 'Pending Actions'
4. See error: Same popup

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
`
### WordPress Environment ###

WordPress address (URL): http://www.wechoose.in
Site address (URL): http://www.wechoose.in
WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.4
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.11
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 86.07MB
Database Data Size: 68.40MB
Database Index Size: 17.67MB
wp_woocommerce_sessions: Data: 4.48MB + Index: 0.12MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.18MB + Index: 0.08MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 1.26MB + Index: 0.80MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 1.36MB + Index: 0.39MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.65MB + Index: 0.44MB + Engine MyISAM
wp_commentmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 0.25MB + Index: 0.10MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_img_optm: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_url: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.14MB + Index: 0.27MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 5.07MB + Index: 0.41MB + Engine MyISAM
wp_postmeta: Data: 20.22MB + Index: 5.37MB + Engine MyISAM
wp_posts: Data: 10.41MB + Index: 0.87MB + Engine MyISAM
wp_pv_commission: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_social_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wp_terms: Data: 0.06MB + Index: 0.10MB + Engine MyISAM
wp_term_relationships: Data: 0.28MB + Index: 0.50MB + Engine MyISAM
wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine MyISAM
wp_usermeta: Data: 0.69MB + Index: 0.37MB + Engine MyISAM
wp_users: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_wc_order_stats: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.26MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wfBlocks7: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfConfig: Data: 2.31MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfHits: Data: 4.21MB + Index: 1.01MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 1.32MB + Index: 0.16MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfLocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.28MB + Index: 0.07MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.08MB + Index: 0.05MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_yoast_indexable: Data: 5.79MB + Index: 0.82MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.07MB + Index: 0.17MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.35MB + Index: 0.20MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.09MB + Index: 0.08MB + Engine MyISAM

### Post Type Counts ###

attachment: 5845
blocks: 22
custom_css: 1
featured_item: 8
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 21
page: 20
post: 2
product: 1512
product_variation: 1103
revision: 837
shop_coupon: 11
shop_order: 268
shop_order_refund: 27
shop_order_vendor: 560
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Contact Form 7: by Takayuki Miyoshi – 5.4.2
LiteSpeed Cache: by LiteSpeed Technologies – 4.4.1
Custom Login Page Customizer: by Hardeep Asrani – 2.1.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.3
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Nextend Social Login: by Nextendweb – 3.1.1
Paytm Payment Gateway: by Paytm – 1.0
Super Progressive Web Apps: by SuperPWA – 2.1.16
WC Cancel Order: by Vikram S – 3.1.2
WC Vendors Marketplace: by WC Vendors – 2.3.2
WooCommerce GST: by Stark Digital – 1.3
Razorpay for WooCommerce: by Team Razorpay – 2.7.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.3
WooCommerce: by Automattic – 5.7.0
WooSidebars: by WooCommerce – 1.4.5
Wordfence Security: by Wordfence – 7.5.5
Yoast SEO: by Team Yoast – 17.2
WP Mail SMTP: by WPForms – 3.0.3
YITH WooCommerce Wishlist: by YITH – 3.1.0

### Inactive Plugins (9) ###

Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.2
Enable Media Replace: by ShortPixel – 3.5.0
Facebook for WooCommerce: by Facebook – 2.6.5
Jetpack: by Automattic – 10.1
OneSignal Push Notifications: by OneSignal – 2.2.2
Really Simple SSL: by Really Simple Plugins – 5.1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.5.1
WooCommerce Stripe Gateway: by WooCommerce – 5.5.0

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #63 - /shop/
Cart: #62 - /cart/
Checkout: #61 - /checkout/
My account: #60 - /my-account/
Terms and conditions: #741 - /terms-of-service/

### Theme ###

Name: WeChoose Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.14.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
wechoose-child/woocommerce/emails/customer-completed-order.php
wechoose-child/woocommerce/emails/customer-reset-password.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php

### Action Scheduler ###

Complete: 115
Oldest: 2021-09-09 04:10:13 +0530
Newest: 2021-09-23 01:43:54 +0530

Failed: 3,477
Oldest: 2020-05-28 21:14:40 +0530
Newest: 2020-07-10 16:49:47 +0530

### Status report information ###

Generated at: 2021-09-23 01:55:01 +05:30
`
</details>

**Comment by rodelgc** [comment]
Hi @thesfboy,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I was able to reproduce it when I upgraded from WC 5.5.0 to WC 5.7.0. After the database update was finished, I clicked on the "Thanks" button, but the notification still does not close. See video below:

https://user-images.githubusercontent.com/4509348/134494914-ceda3914-6781-4967-84a6-01aafc8aefed.mov

And when I looked at the WC db version in the Status page, I noticed that it's set to `5.6` instead of `5.7`, as you can see here:
<img width="1257" alt="Screen Shot 2021-09-23 at 6 51 48 PM" src="https://user-images.githubusercontent.com/4509348/134495253-34ecaae6-9990-4d3e-8e06-7f3ec459ad95.png">

Here are the steps I took to reproduce the issue:
1. Setup a clean install of WooCommerce 5.5.0
2. Go to Plugins > Add New, and then upload the zip file for WooCommerce 5.7.0
3. When the "WC Database update required" notification appears, click the 'Update' button and wait for it to finish.
4. Once done, click on the 'Thanks' button.
5. Notice that "WC Database update done"  notification does not close.
6. Go to WooCommerce > Status and scroll down to the WooCommerce Database version. Notice that it's set to 5.6 instead of 5.7

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by rodelgc** [comment]
Also, this bug is not happening when I upgraded from WC 5.5.0 to WC 5.6.0. Here's the video showing the notification closing after clicking 'Thanks'

https://user-images.githubusercontent.com/4509348/134497455-8230dc63-1ad2-476e-b970-13931a20bba4.mov

The thing I worry more about now is why the DB version was only upgraded to 5.6 and not 5.7.

**Comment by thesfboy** [comment]
Thanks for your help. Even my db is at 5.6 instead of 5.7. Strangely
enough, the notification has now gone. Having said that, when I upgraded
another site from 5.6 to 5.7, the notification didn't appear.

**Comment by thesfboy** [comment]
My bug was that the notification kept saying Database update required. Click here to update. And even clicking update, it would reappear. Also, the database has not been migrated to 5.7 as it should have. It still shows 5.6.

**Comment by CurtisL** [comment]
Experiencing the same (similar?) problem after updating from 5.5.2 to 5.7.1. 

The DB never actually updates and I am perpetually prompted "WooCommerce database update required". No "thanks" or failure alerts. I do get the "View Progress" alert, and seetwo scheduled actions:

```
woocommerce_run_update_callback
Pending	
'update_callback' => 'wc_update_560_create_refund_returns_page'
woocommerce-db-updates Non-repeating

woocommerce_run_update_callback
Pending	
'update_callback' => 'wc_update_560_db_version'
woocommerce-db-updates Non-repeating
```

These do end up in the Complete section  after the Schedule actions have executed. But I am immediately prompted to update the database again. Our DB version now says 5.0 for some reason.

As a result of this, TaxJar extension has hurt itself in its confusion, which is more likely on them, but this is still problematic. 

> TaxJar is inactive. This version of TaxJar requires WooCommerce 5.1.0 or newer. Please install or update WooCommerce to version 5.1.0 or newer.

**Update:** After clearing various caches I decided to try and clear our site cache via `wp cache flush` then re-ran the update from the admin alert. This seems to have worked? Db version now says 5.6.0, knowing that the db version doesn't always match the core version (tooltip in the admin) I imagine this is the correct version?

**Comment by SirDarcanos** [comment]
I am experiencing the same issue. I run WooCommerce 5.9.0 and I confirm that the DB version in the SSR is 5.9.0 as well. The Database Updated notification keeps reappearing even after clicking on "Thanks".

**Comment by thesfboy** [comment]
Just wait for the new update to come. It will go away.
