### ISSUE TITLE
woocommerce_product_options_shipping hook needs parity with other panels

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#30811]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The [`woocommerce_product_options_shipping`](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/admin/meta-boxes/views/html-product-data-shipping.php#L63) hook is _inside_ the `<div class="options_group">` element. This is inconsistent with the other panels (See: [`woocommerce_product_options_general_product_data`](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/admin/meta-boxes/views/html-product-data-general.php#L186) and [`woocommerce_product_options_inventory_product_data`](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/admin/meta-boxes/views/html-product-data-inventory.php#L130) exist after the options group div is closed and if you'd like to add an additional options_group div element you need to _close_ the open div. This can ultimately cause problem markup.

**Expected behavior**
The hook should be _outside_ the `<div class="options_group">` element.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
```
/**
 * Shipping field, missing in action.
 */
function test_shipping_options_admin_html() { ?>

	<div class="options_group hide_if_virtual test_options show_if_simple">
		Missing in action.
	</div>

<?php
}
add_action( 'woocommerce_product_options_shipping', 'test_shipping_options_admin_html', 10000 );
```

Note that this element is nested inside the core `options_group`.

**Proposed solutions**
Either move the `woocommerce_product_options_shipping` outside of the `options_group` div...
or introduce a `woocommerce_product_options_shipping_product_data` for parity with the other panels. 

See: https://github.com/woocommerce/woocommerce-subscriptions/issues/4206

**Comment by tammullen** [comment]
Hi @helgatheviking,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.
