### ISSUE TITLE
Change capitalization of Eway payment gateway, fix associated linter errors

### ISSUE THREAD

**Issue by jacob-sewell** [woothemes/woocommerce#30817]
In [this woocommerce-admin issue](https://github.com/woocommerce/woocommerce-admin/issues/7591) we changed the capitalization of the Eway payment gateway (from eWAY), and this repository also references Eway, so should be changed as well. Unfortunately, the file that needs to be changed ([includes/admin/class-wc-admin-setup-wizard.php](https://github.com/woocommerce/woocommerce/blob/2bbaca9621e012c6f2d8196a434313dc30377609/includes/admin/class-wc-admin-setup-wizard.php)) has a lot of grandfathered PHP that the linter [doesn't like](https://github.com/woocommerce/woocommerce/pull/30742/checks?check_run_id=3680033132).

[x] Change Eway capitalisation in that file (already done in [PR 30742](https://github.com/woocommerce/woocommerce/pull/30742))
[] Fix linter errors so that PR can be merged.

**Comment by jacob-sewell** [comment]
@mattsherman what pipline should I put this in?

**Comment by mattsherman** [comment]
@jacob-sewell Put it in Mothra's "Groom" and I'll take a closer look at this to see what we should do with it. Thanks!

**Comment by rrennick** [comment]
The only place I found `eWAY` was in the old setup wizard which is disabled so I'll close the issue.
