### ISSUE TITLE
Old Woo Purple a36597 & a16696

### ISSUE THREAD

**Issue by dougaitken** [woothemes/woocommerce#30829]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

There are still pieces of code that have the old woo purple #a36597 and secondary #a16696

Some shown here - https://github.com/woocommerce/woocommerce/search?q=a36597&unscoped_q=a36597

Mainly around `button-primary`.
This can be seen on the Front-end on **WooCommerce > Status > System Status**, the `Get system report` button, the buttons shown with there are outdated theme templates, and the product importer/exporter.

**Expected behavior**

All styles match "new" WooCommerce Purple 50, #7F54B3 and (secondary) WooCommerce Purple 80, #3C2861

See [Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines) and the colors used in the WordPress.org listing - https://wordpress.org/plugins/woocommerce

**Actual behavior**

Many of the components are still the older woo purples

**Screenshots**

![old_woo_purple_status_report](https://user-images.githubusercontent.com/52214/135093439-c97a41c3-05f2-420e-834f-7e5dffddc9d6.gif)
![old_woo_purple_outdated_theme](https://user-images.githubusercontent.com/52214/135093453-0a7fe408-5996-4b33-967e-7308f7506ff2.png)
<img width="765" alt="old_woo_purple_importer" src="https://user-images.githubusercontent.com/52214/135093456-7796912a-596c-4215-9f11-8d5c0b7e12ed.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by san-coding** [comment]
Hey, can I work on this issue, I am new to open source ?

**Comment by dougaitken** [comment]
Sure @san-coding! Are you looking for support when working on it or are you okay to handle this yourself?

**Comment by san-coding** [comment]
Thanks, I will need some help getting started

**Comment by nielslange** [comment]
Hello @san-coding 👋 Great to hear that you want to pick up this issue. To getting started, you first need to set up the [WooCommerce development environment](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment). Once you did this, you can then replace the color code in the IDE of your choice, e.g. VSCode. As mentioned on [Minification of SCSS and JS](https://github.com/woocommerce/woocommerce/wiki/Minification-of-SCSS-and-JS), you only need to add the changed SCSS files in your PR. 

I hope this helps to getting started. If you need further assistance, just let me know! 😀
