### ISSUE TITLE
Taxes endpoint pagination

### ISSUE THREAD

**Issue by stevenbrookes** [woothemes/woocommerce#30838]
**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Pagination for the taxes endpoint /wp-json/wc/v3/taxes is broken.  If you have say more than 10 tax rates and send the following request

GET https://host.com/wp-json/wc/v3/taxes only the first 10 will be returned.  That's correct however the headers to allow for paghination aren't set

Link: <https://host.com/wp-json/>; rel="https://api.w.org/"
X-WP-Total: 10
X-WP-TotalPages: 1

**Expected behavior**
Headers should contain the information about the other pages

Link: <https://host.com/wp-json/wc/v3/products?page=2>; rel="next"
X-WP-Total: 15
X-WP-TotalPages: 2

**Actual behavior**
Link :<https://host.com/wp-json/>; rel="https://api.w.org/"
X-WP-Total: 10
X-WP-TotalPages: 1

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1.  Create more than 10 tax rates via the settings
2. Call the API

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://woocommerce.talisman-innovations.com
Site address (URL): https://woocommerce.talisman-innovations.com
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 756 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.1
PHP Version: 7.4.23
PHP Post Max Size: 8 MB
PHP Time Limit: 18000
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.19
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 16.15MB
Database Data Size: 9.27MB
Database Index Size: 6.88MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.34MB + Index: 0.39MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.33MB + Index: 0.38MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 3.91MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.34MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 541
page: 7
post: 4
product: 1152
product_variation: 48
revision: 15
shop_coupon: 21
shop_order: 591
shop_order_refund: 187

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.7.1

### Inactive Plugins (5) ###

Sequential Order Numbers for WooCommerce: by WebToffee – 1.3.9
WooCommerce Shipment Tracking: by WooCommerce – 1.6.28
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.7
Woo Product Remover: by Mohammad Farhat – 1.1.0
WP Rollback: by Impress.org – 1.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0 (update to version 3.9.1 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 385
Oldest: 2021-09-07 14:09:37 +0100
Newest: 2021-09-29 16:46:02 +0100

Failed: 1
Oldest: –
Newest: –

### Status report information ###

Generated at: 2021-09-29 16:46:22 +01:00
`
</details>

**Comment by tammullen** [comment]
Hi @stevenbrookes 

Thanks for raising the issue.

As per https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-tax-rates have you tired using the the 'per_page' parameter.

On a site with 14 tax rates I get 10 results when using `wp-json/wc/v3/taxes`

If I add the 'per_page' parameter set to 15 I see all 14 tax rates.

**Comment by mahmoudsaeed** [comment]
@tammullen I can confirm the issue. The endpoint does return the correct results in the response body, but the pagination headers `X-WP-Total` and `X-WP-TotalPages` are incorrect. I have created a PR that fixes the issue.

**Comment by mahmoudsaeed** [comment]
@tammullen I can confirm the issue. The endpoint does return correct results in the response body, but the pagination headers X-WP-Total and X-WP-TotalPages are incorrect. I have created a [PR](https://github.com/woocommerce/woocommerce/pull/30890) that fixes the issue.

**Comment by stevenbrookes** [comment]
@mahmoudsaeed Thank you for resolving this issue.  I look forward to it being in a future release.  
@tammullen Do you still want the feedback you mentioned above?
