### ISSUE TITLE
Problem getting "older" shipping phone field

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#30835]
Before 5.6.0 the order `get_shipping_phone` method did not exist.

In several shops, for years now, I've been adding the shipping phone as a custom field, called `_shipping_phone` to follow the same logic as the internal fields. I'm sure a lot of developers did the exact same thing, as this is a common request from shop owners.

I used to get the shipping phone by calling `$order->get_meta( '_shipping_phone' )` which now does not work because on the `get_meta` method of the `WC_Data` class you are checking if the meta is an internal key, which returns false because there's no getter called `get__shipping_phone` on the (notice the double "_") as tested on the `is_internal_meta_key` method. But indeed now `_shipping_phone` is an internal key of the order and because of that is not present on the array returned by `read_meta_data` because it is removed by the `filter_raw_meta_data` method of the `WC_Data_Store_WP` class.

In short: everyone that created a custom `_shipping_phone` before 5.6.0 has to change their code to use `$order->get_shipping_phone()` instead of `$order->get_meta( '_shipping_phone' )` and I'm pretty sure there are a lot of implementations out there having this issue and not understanding why a simple get_meta doesn't work. This is happening in the future for any new field you decide to create internally but already existed before in a custom implementation.

Although I agree custom code needs to be maintained, that's not always the case, and it's not very hard to keep this backward compatible.

Solution: I think the get_meta method should always return the value even if the field is an internal key, or maybe the `is_internal_meta_key` and `get_meta` method should account for the double "_" issue and make it work anyway, like this:

abstract-wc-data.php, line 308:
`$has_setter_or_getter = is_callable( array( $this, 'set_' . $key ) ) || is_callable( array( $this, 'get_' . $key ) ) || is_callable( array( $this, 'set' . $key ) ) || is_callable( array( $this, 'get' . $key ) );`

abstract-wc-data.php, line 330, add a new check after line 334:
`$function = 'get_' . $key;

if ( is_callable( array( $this, $function ) ) ) {
	return $this->{$function}();
}

//Double _?
$function = 'get' . $key;

if ( is_callable( array( $this, $function ) ) ) {
	return $this->{$function}();
}`

**Comment by tammullen** [comment]
Hi @webdados ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Closing this in favor of #31140.

Though this issue predates that one, there are useful notes and discussion in the later issue we can reference.

Of course, if I've misunderstood/if anyone disagrees, please let me know.
