### ISSUE TITLE
Image Title no longer shows as title attribute when hovering over product gallery thumbnails--attempt 2

### ISSUE THREAD

**Issue by madriverweb** [woothemes/woocommerce#30837]
Can get a real WooCommerce support person to answer this? Please reference my previous post, https://github.com/woocommerce/woocommerce/issues/30728, for the info you request. Note: I changed the title because I said "Product" inadvertently rather than "Image" Title.

Some contributor responded and stated that default themes "really don't have title attributes on the variation thumbnails" and then later asked me to troubleshoot. This is not a theme problem; our theme DOES show title attributes elsewhere in the non-Woo sections of the website, for example the large image on our home page. <b>The problem is that WooCommerce used to support this and no longer does.</b> Will someone please confirm that? With every hosting platform wanting us to update plugins immediately, I have no examples to show where this used to work, nor do I know exactly when it changed because my customer alerted me to it, although I am now reviewing the changelog.

If this is something you can't fix or reverse, is there a function you can provide so that we can display as we used to--the thousands of image titles as title attributes when hovering over thumbnails? Is there perhaps an older version file that I can grab that function from and make a new custom file?

Thank you for any HELP that you can provide.

**Comment by tammullen** [comment]
Hi @madriverweb ,

Thank you for additional information. However, as you noted this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/30728. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
