### ISSUE TITLE
Not able to search the order via order number in admin dashboard in woocommerce version 5.7.1

### ISSUE THREAD

**Issue by de17** [woothemes/woocommerce#30841]
![Screenshot_1](https://user-images.githubusercontent.com/91219840/135342234-fe4057ca-c7f7-416a-a4bf-0d6b957c89b9.png)
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by swatipawarGS** [comment]
Hi @de17  ,

Thank you for taking the time to report this bug, we really appreciate your help. I can't reproduce it on my end using WooCommerce  5.9.0  version.



Below is the screenshot documenting my experience:



![#30841](https://user-images.githubusercontent.com/94531721/142581141-c2a22dd8-b455-4120-b42d-b3d8e497e8d6.jpg)

**Comment by swatipawarGS** [comment]
Hi @de17 ,

We retested this issue and couldn't reproduce this issue at our end using WooCommerce 5.9.0  version.

Please find below screenshots documenting for reference:

![#30841](https://user-images.githubusercontent.com/94531721/143203399-690908ba-6af5-4aaf-8682-19d651f2d87d.jpg)


Please provide us more details and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by de17** [comment]
This issue occurs with the activated booster plugin with woocommerce on my
website.

Thanks

**Comment by tammullen** [comment]
Hi @de17 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party booster plugin you mention.
​
Please contact the author of the plugin directly for further help.
