### ISSUE TITLE
Review count in product page should be formatted with thousand separator

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#30847]
Currently when you have review count more than 999. For example it will show "**** (123456 customer reviews)" instead of "**** (123.456 customer reviews)"

This is small fix but improve the readability.

**Comment by tammullen** [comment]
Hi @erikdemarco ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
