### ISSUE TITLE
Adopt the WP changes made to the PHPUnit test suite

### ISSUE THREAD

**Issue by Chouby** [woothemes/woocommerce#30852]
**Is your feature request related to a problem? Please describe.**
Currently WooCommerce is using a fork of PHPUnit 7.5 to run tests with PHP 8 and it's not possible to use the latest version of PHPUnit.

**Describe the solution you'd like**
I suggest to adopt the method used by WordPress which allows to use PHPUnit 5.7 to PHPUnit 9.5 depending on the PHP version used. Part of the job has already been done in #30472 by the adoption of the Yoast Polyfills. This now requires to use snake case alternatives for fixtures and possibly fix assertions deprecated or removed in recent version of PHPUnit. See https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/ for the details.

**Additional context**
This switch should interest all developers relying on the WooCommerce test framework when developing their extensions.

**Comment by tammullen** [comment]
Hi @Chouby 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
@Konamiman @ObliviousHarmony thoughts, folks? Seems reasonable to me...

**Comment by ObliviousHarmony** [comment]
This feels like a reasonable change @peterfabian.

**Comment by rrennick** [comment]
Looks like this was addressed as we are using [Yoast polyfills](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/composer.json#L34).
