### ISSUE TITLE
Add action after product is imported via csv

### ISSUE THREAD

**Issue by plainviewp1206** [woothemes/woocommerce#30854]
**Is your feature request related to a problem? Please describe.**
I'd like an action to be called after the csv product importer imports a product.

**Describe the solution you'd like**
includes/import/class-wc-product-csv-importer.php
On line 1052 you have do_action( 'woocommerce_product_import_before_import', $parsed_data );
It would be nice if you could add
do_action( 'woocommerce_product_import_after_import', $data );
on line 1117

**Additional context**
This is in order to programmatically handle products with custom code after the import.

**Comment by tammullen** [comment]
Hi @plainviewp1206 ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
