### ISSUE TITLE
Update to npm 7

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#30864]
I did a trial test of updating npm to version 7 and found that there are some dependencies that need to be updated to be compatible with version 7.

**Comment by psealock** [comment]
Now that we use pnpm is this required?

**Comment by rrennick** [comment]
The reason that I created the issue is that npm 7 will install peer dependencies while versions 6 and earlier do not. A secondary issue is that our packages seem to have [an issue with npm 7](https://github.com/woocommerce/woocommerce-e2e-boilerplate/issues/7). As long as we can resolve both issues with pnpm then I'd be fine with closing this.

**Comment by ObliviousHarmony** [comment]
We're using Node v16 which ships with npm v7. For what it's worth, we use `pnpm` now instead of `npm`.
