### ISSUE TITLE
Unable to add tags to a product using Update product API

### ISSUE THREAD

**Issue by vasanthhr** [woothemes/woocommerce#30872]
I am able to update other product attributes but couldnt add new tags or update tag to a prodcut

Here 26 is the tag id that created and available under Tags.

```

$woocommerce = new Client(
   
    'http://localhost:8012/testwp_v2',
    'ck_XXXXXXXXXXXXXXX',
    'cs_XXXXXXXXXXXXXXX',

    [
        'wp_api' => true,
        'version' => 'wc/v3',
        'timeout' => 30
    ]
);

$data = "['tags' => ['id'=> '26',],]";

print_r($woocommerce->put("products/13", $data));
```

But I always get the result as  200 and no error but tags not updating .

screenshot where it returns result but new tag: 26 is not adding into product:13

![image](https://user-images.githubusercontent.com/20619142/135811346-5726f736-e375-4f6d-b853-5469aa046c5c.png)

**Comment by juliaamosova** [comment]
Hi @vasanthhr,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @vasanthhr,

I can successfully update a product using the REST API and can set a tag, so I think that side of things is working well.

In this case, I believe the problem may be the way you are using the client. The `$data` param accepts an array (which will then be encoded into JSON), but it looks as if you are passing a *string representation* of an array. Can you try amending:

```php
$data = "['tags' => ['id'=> '26',],]";
```

To:

```php
$data = [ 'tags' => [ 'id' => 26 ] ];
```

Does that help?
