### ISSUE TITLE
Duplicate order confirmation email sent with TWINT as payment method

### ISSUE THREAD

**Issue by ppwebox** [woothemes/woocommerce#30871]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using TWINT (managed by the WP plugin "mame TWINT for WooCommerce") as payment method the customer receives the order confirmation message twice by E-mail. Both E-mails have the same time stamp. This does not happen when PayPal is used. The developer of "mame TWINT for WooCommerce" was notified about this bug. He examined his code regarding the issue but did not find any cause.   

**Expected behavior**
Only one order confirmation mail should be sent to the customer using the TWINT plugin. 

**Actual behavior**
See bug description. TWINT differs from PayPal payment in that a page with a QR code opens after order submission, which the buyer confirms with the TWINT app on his mobile phone. On success, the buyer gets redirected to the "Thank you" page. Woocommerce, which controls the whole payment process after adding to the shopping cart, seems to trigger the mail purchase flag twice with TWINT. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Order Checkout
2. Click on TWINT as payment method
3. Verify TWINT QR code on next page with mobile phone app
4. On success receive two instead of one order confirmation message by mail 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

WordPress address (URL): https://www.kap-kundalini-activation-process.ch/kapschweizch_w
Site address (URL): https://www.kap-kundalini-activation-process.ch
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.6
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 20000
cURL Version: 7.66.0
OpenSSL/1.1.1d-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 121.46MB
Database Data Size: 114.10MB
Database Index Size: 7.36MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfef_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_eum_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kbp_form_entry: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kbp_form_entrymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ksp_layers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ksp_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ksp_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mec_attendees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mec_dates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mec_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mec_external_sites: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mec_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.38MB + Index: 0.28MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 9.45MB + Index: 2.91MB + Engine InnoDB
wp_posts: Data: 90.09MB + Index: 0.33MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 1.38MB + Index: 0.22MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsssl_csp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_simple_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_simple_history_contexts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolkit_gtmetrix: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
wp_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

_pods_pod: 1
ajde_events: 6
attachment: 131
cartflows_flow: 1
cartflows_step: 2
carts: 4
custom_css: 1
customize_changeset: 6
def_reg_fields: 10
ele-check-template: 1
elementor_font: 1
elementor_library: 26
epta: 1
event_magic_tickets: 1
gfw_report: 11
kt_font: 14
lc_partial: 1
mastermega_content: 1
mec_calendars: 18
mec_designer: 2
mec_esb: 1
mec_form: 1
mec_invoice: 168
mec-books: 167
mec-events: 12
nav_menu_item: 59
option-tree: 1
page: 24
post: 1
product: 210
revision: 229
shop_order: 161
shop_order_refund: 11
tablepress_table: 1
ticket-meta-fieldset: 1
tribe_events: 20
tribe_organizer: 1
tribe_venue: 4
wc_order_status: 7
wp_log: 140
wpea_import_history: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.29
Better Search Replace: by Delicious Brains – 1.3.4
Code Snippets: by Code Snippets Pro – 2.14.2
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 5.4.0
Custom Fonts: by Brainstorm Force – 1.3.3
Elementor Pro: by Elementor.com – 3.4.1
Elementor: by Elementor.com – 3.4.4
Advanced Scripts: by Clean Plugins – 1.1.0
GTmetrix for WordPress: by GTmetrix – 0.4.4
Kadence Custom Fonts: by Kadence WP – 1.1.0
Kadence WooCommerce Extras: by Kadence WP – 1.6.22
Kadence WooCommerce Elementor: by Kadence WP – 1.0.6
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.8
Mailchimp for WooCommerce: by Mailchimp – 2.5.3
Maintainn Tools: by Maintainn – 2.3.4
mame TWINT for WooCommerce: by mame software development hüttig – 3.0.5
Manage Notification E-mails: by Virgial Berveling – 1.8.0
Elementor Form Builder for MEC: by Webnus – 1.1.6
MEC Tickets und Rechnungen: by Webnus – 1.2.6
Elementor Shortcode Builder for MEC: by Webnus – 1.5.6
Elementor Shortcode Designer: by Webnus – 1.2.1
Elementor Single Builder for MEC: by Webnus – 1.6.5
WooCommerce Integration for MEC: by Webnus – 1.4.5
Moderner Event Kalender: by Webnus – 5.22.3
Really Simple SSL: by Really Simple Plugins – 5.1.0
Search Exclude: by Roman Pronskiy – 1.2.6
Rank Math SEO: by Rank Math – 1.0.71.1
Easy Updates Manager: by Easy Updates Manager Team – 9.0.9
TablePress: by Tobias Bäthge – 1.14
WC Multiple Email Recipients: by Con Schneider – 1.4.0
WooCommerce Custom Thank You Pages: by Jeroen Sormani – 1.0.4
WooCommerce Email Customizer: by WooCommerce – 1.3.0
WooCommerce: by Automattic – 5.7.1
WP Rocket: by WP Media – 3.9.1.1

### Inactive Plugins (11) ###

CAOS: by Daan from FFW.Press – 4.1.6
DoLogin Security: by WPDO – 3.1
Query Monitor: by John Blackbourn – 3.7.1
Simple History: by Pär Thernström – 2.42.0
WP Mail SMTP: by WPForms – 3.1.0
WP Show Posts: by Tom Usborne – 1.1.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: right
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /kap-events/
Cart: #8 - /warenkorb/
Checkout: #224229 - /checkout/
My account: #12 - /mein-konto/
Terms and conditions: #226357 - /agb-allgemeine-geschaftsbedingungen/

### Theme ###

Name: Kadence
Version: 1.1.5 (update to version 1.1.6 is available)
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 472
Oldest: 2021-09-01 19:32:06 +0200
Newest: 2021-10-02 12:11:29 +0200

Pending: 1
Oldest: 2021-10-03 10:22:55 +0200
Newest: 2021-10-03 10:22:55 +0200

### Status report information ###

Generated at: 2021-10-02 15:50:02 +02:00
`

</details>

**Comment by juliaamosova** [comment]
Hi @ppwebox,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin [Twint for WooCommerce](https://www.mamedev.ch/downloads/twint-for-woocommerce-2/?lang=en). 

Please contact the author of the plugin directly for further help.
