### ISSUE TITLE
Need for clicking on the billing/shipping address form for `Add new Order` - Tedious Cursor Issue

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#30878]
**Is your feature request related to a problem? Please describe.**

When trying to add details to the billing and shipping address form from `WooCommerce >> Orders >> Add new Order` from WP-admin, we used to be able to use the tab to toggle all the way to the country and the state field and begin to type the country/state name which would then get selected all through keyboard like [this demo](https://d.pr/v/9ip0to)

Now, we are unable to start typing as we have to click on the field after toggling to the state or country field like this:

![](https://d.pr/i/rmQ7wk+)
[Direct Link](https://d.pr/i/rmQ7wk+)

The same behavior persists on the `Add product` dialog box also:

![](https://d.pr/i/MTIw9F+)
[Direct Link](https://d.pr/i/MTIw9F+)
 

**Describe the solution you'd like**
Being able to tab my way to the field and then start typing without clicking in the box

**Describe alternatives you've considered**
1. Downgraded to 5.4.0 - Same issue for both the address forms and the `add product` dialog
2. Downgraded to 5.1.0 - Same issue for both the address forms and the `add product` dialog
3. Tested on latest Chrome and firefox builds and the issue persists.

**Additional context**
1. Here is what the demo of the working setup provided by customer https://d.pr/v/9ip0to
2. Instead of onclick and type, now basically we have to click twice as explained here https://www.loom.com/share/dcd3c08c65534d44819f5ebd9de09257
3. This becomes an issue when adding scores of products to the order from the backend via keyboard.

**Comment by roykho** [comment]
Did you test trunk? It has already been fixed here https://github.com/woocommerce/woocommerce/pull/30626
