### ISSUE TITLE
WordPress.org readme.txt should be updated

### ISSUE THREAD

**Issue by mircobabini** [woothemes/woocommerce#30885]
**Is your feature request related to a problem? Please describe.**
It's still reported that WooCommerce Payments is U.S. only. That's not true.

**Describe the solution you'd like**
Available in the U.S., U.K., Ireland, Australia, New Zealand, Canada, and now: Spain, France, Germany, and Italy as reported here https://woocommerce.com/payments/

**Comment by lukecav** [comment]
I would post on the WooCommerce Payments repo.
https://github.com/Automattic/woocommerce-payments/issues

**Comment by mircobabini** [comment]
Good, but I’m referring to WC page: https://wordpress.org/plugins/woocommerce/

**Comment by juliaamosova** [comment]
Hi @mircobabini,

Thank you for taking the time to report this issue, we really appreciate your help. 

You've reached the right team as we are the ones who update the WooCommerce plugin page on WordPress.org. 

Looping in @vedanshujain and @peterfabian as we may want to address this sooner than later.

**Comment by lukecav** [comment]
https://github.com/woocommerce/woocommerce/pull/30934

**Comment by peterfabian** [comment]
Thanks @lukecav . Merged.
