### ISSUE TITLE
Make free shipping taxable for compatibility reasons

### ISSUE THREAD

**Issue by KristFlex** [woothemes/woocommerce#30907]
Hey, 

we recently switched to Woocommerce and are pretty happy with our new shop. It's connected via API with our ERP System, sending order information etc. via webhooks over to the ERP. However there is a problem. The ERP expects products and services to have a VAT and it's working fine with everything except the *free shipping* method. I assume that because it's free it's not taxable and there is no option to turn it on or off like it is with flatrate shipping (which makes sense cause it's free) but the ERP needs that VAT in the data it gets via the webhook. Is there any possibility to make free shipping taxable? 

Thank you in advance!

**Comment by juliaamosova** [comment]
Hi @KristFlex,

We are excited to have you on board with us! Thanks for choosing WooCommerce as your e-commerce solution.  

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by DavidAnderson684** [comment]
What would it mean to make free shipping taxable? In WooCommerce, taxes are percentages. No matter what you multiply free (zero) by, it's still zero.

Sounds like what you should be doing is hooking in to customise the REST output for your needs.

**Comment by KristFlex** [comment]
`\"shipping_lines\":[{\"id\":5433,\"method_title\":\"DHL EU\",\"method_id\":\"flat_rate\",\"instance_id\":\"11\",\"total\":\"10.84\",\"total_tax\":\"2.17\",\"taxes\":[{\"id\":101,\"total\":\"2.168\",\"subtotal\":\"\"}]`

`\"shipping_lines\":[{\"id\":5430,\"method_title\":\"Kostenloser Versand\",\"method_id\":\"free_shipping\",\"instance_id\":\"3\",\"total\":\"0.00\",\"total_tax\":\"0.00\",\"taxes\":[]`

Comparing the content of the Webhook you can see that the first shipping method has a taxes id (101) for France, the second - free - shipping method has nothing in taxes. While I do realize that it would be still zero, our ERP needs the tax rate for every product, even ones that are free.

**Comment by KristFlex** [comment]
@DavidAnderson684 Could you take a look at my reply, please? Thank you very much in advance.

**Comment by DavidAnderson684** [comment]
@KristFlex I am not on the WooCommerce core team. The "Contributor" label means that I've had pull requests accepted in the past.

**Comment by KristFlex** [comment]
Hi @juliaamosova,

can anyone please take a look at this ticket and reply? So far no developer has ever replied to this. Thank you in advance.

**Comment by barryhughes** [comment]
Sorry for the delay, @KristFlex.

I'm not sure that, generally, there would be much value in this. Given the custom nature of the change, might you explore tweaking things via some light custom development? You could for instance leverage the [`woocommerce_webhook_payload`](https://github.com/woocommerce/woocommerce/blob/6.3.1/plugins/woocommerce/includes/class-wc-webhook.php#L481) filter hook to add the additional data when needed.
