### ISSUE TITLE
BUG: 0 Variations added when attribute value is "1"

### ISSUE THREAD

**Issue by christopherdarling** [woothemes/woocommerce#30903]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A variable product has an attribute with value of "1". When trying to "create all variations" this variation is always missed. This is looks to be due to `wc_array_cartesian` converting the string value to integer. 

**Expected behavior**
A new variation to be added for the attribute with value "1"

**Actual behavior**
No variation is added.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create attribute with value of 1
2. add Attribute to a product
3. Click Create all variations action
4. Observe it says 0 variations added

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://domain.test/wp
Site address (URL): https://domain.test
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.4.21
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.77.0
(SecureTransport) OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 36.97MB
Database Data Size: 28.19MB
Database Index Size: 8.78MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.11MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.09MB + Index: 0.04MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_image_storage: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_section_storage: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_options: Data: 5.18MB + Index: 0.19MB + Engine MyISAM
wp_postmeta: Data: 15.91MB + Index: 6.08MB + Engine MyISAM
wp_posts: Data: 5.32MB + Index: 0.54MB + Engine MyISAM
wp_termmeta: Data: 0.16MB + Index: 0.16MB + Engine MyISAM
wp_terms: Data: 0.06MB + Index: 0.09MB + Engine MyISAM
wp_term_relationships: Data: 0.43MB + Index: 0.77MB + Engine MyISAM
wp_term_taxonomy: Data: 0.06MB + Index: 0.07MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.39MB + Index: 0.42MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 466
custom_css: 1
nav_menu_item: 32
option-tree: 1
page: 27
post: 2
postman_sent_mail: 250
product: 1200
product_variation: 4158
revision: 263
shop_order: 60
shop_order_refund: 4
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Contact Form 7: by Takayuki Miyoshi – 5.4.2
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.3.3
WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0
AG WooCommerce Lloyds Cardnet Payment Gateway: by We are AG – 3.3.2
Members: by MemberPress – 3.1.5
PeakShops - Required Plugin: by fuelthemes – 1.1.4
Post SMTP: by Yehuda Hassine – 2.0.23
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Smart Slider 3: by Nextend – 3.5.0.11
SVG Support: by Benbodhi – 2.3.19
WooCommerce Tiered Price Table: by bycrik – 2.5.0
WooCommerce: by Automattic – 5.7.1

### Inactive Plugins (8) ###

AG WooCommerce Lloyds Cardnet Payment Gateway: by We are AG – 3.3.0
AG WooCommerce Lloyds Cardnet Payment Gateway: by We are AG – 2.1.0
All-in-One WP Migration: by ServMask – 7.28
Perfect Brands for WooCommerce: by QuadLayers – 1.8.4
PPOM for WooCommerce by N-MEDIA: by Najeeb Ahmad – 20.5
Relevanssi: by Mikko Saari – 4.8.2
Wordfence Security: by Wordfence – 7.5.5
WordPress Importer: by wordpressdotorg – 0.7

### Must Use Plugins (3) ###

Bedrock Autoloader: by Roots – 1.0.3
Disallow Indexing: by Roots – 1.0.0
Register Theme Directory: by Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #10 - /terms-conditions/

### Theme ###

Name: Theme name
Version: 1.8.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Base Theme
Parent Theme Version: 1.5.0
Parent Theme Author URL: 
WooCommerce Support: ✔

### Action Scheduler ###

Complete: 23
Oldest: 2021-10-08 08:11:31 +0100
Newest: 2021-10-08 08:20:58 +0100

### Status report information ###

Generated at: 2021-10-08 09:05:04 +01:00
`
</details>

**Comment by swatipawarGS** [comment]
Hi @christopherdarling ,


Thank you for taking the time to report this bug, we really appreciate your help. I can't reproduce it on my end using WooCommerce 5.9 .0 version.



Below is the screencast documenting my experience:



https://user-images.githubusercontent.com/94531721/142432819-1cd3500c-4d81-4454-ad0a-9eaa65a0399f.mp4

**Comment by swatipawarGS** [comment]
Hi @christopherdarling ,

We retested this issue again and couldn't reproduce this issue at our end using WooCommerce 5.9.0  version.

Please find below the screencast for your reference :

https://user-images.githubusercontent.com/94531721/143207786-7a975e0d-4533-4b19-9d98-672b100b379b.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by christopherdarling** [comment]
Hi @swatipawarGS I can confirm this is now resolved - thank you!
