### ISSUE TITLE
Order "steals" other order's shipping method

### ISSUE THREAD

**Issue by Argentus** [woothemes/woocommerce#30940]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Sometimes when two orders are created at the same time (or with only a small time difference, 0-3 min) (by separate users, on separate computers, in separate locations), one order steals the other's shipping method. This results in an order that has two different shipping item lines, on an eshop which never allows this on purpose. This happens on a live eshop sometimes, I am not able to reproduce this on purpose.
What possible cause could there be, what mechanism could allow something like this to happen?

**Expected behavior**
All orders have one shipping method, the one chosen on checkout.

**Actual behavior**
Some orders have two shipping methods, one of them taken from another order created at the same time. 

**I am unable to actively reproduce the bug**

**Comment by rodelgc** [comment]
Hi @Argentus,

Thank you for submitting this issue. However, without the exact steps to replicate, we couldn't evaluate this issue accurately. 
Would you at least be able to provide screenshots and the system status report from **WooCommerce > System Status** in WordPress admin?
