### ISSUE TITLE
WooCommerce My subscriptions

### ISSUE THREAD

**Issue by uebes** [woothemes/woocommerce#30965]
I get the follwing message if I click on WOOCOMMERCE My subscriptions:

Ein Fehler vom Typ E_ERROR wurde in der Zeile 807 der Datei /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-addons.php verursacht. Fehlermeldung: Uncaught TypeError: Argument 1 passed to WC_Admin_Addons::filter_admin_body_classes() must be of the type string, null given, called in /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-includes/class-wp-hook.php on line 303 and defined in /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-addons.php:807
Stack trace:
#0 /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-includes/class-wp-hook.php(303): WC_Admin_Addons::filter_admin_body_classes()
#1 /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-admin/admin-header.php(226): apply_filters()
#3 /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-admin/admin.php(239): require_once('/var/www/vhosts...')
#4 {main}
thrown
**WordPress Environment**

### WordPress Environment ###

WordPress address (URL): https://heimvorteil.webneumarkt.at
Site address (URL): https://heimvorteil.webneumarkt.at
WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 7.4.24
PHP Post Max Size: 40 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-cll-lve
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: KtS4szE8u_
Datenbank-Gesamtgröße: 105.48MB
Datenbank-Datengröße: 74.80MB
Datenbank-Indexgröße: 30.68MB
KtS4szE8u_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
KtS4szE8u_woocommerce_order_items: Daten: 0.47MB + Index: 0.16MB + Engine InnoDB
KtS4szE8u_woocommerce_order_itemmeta: Daten: 8.52MB + Index: 7.03MB + Engine InnoDB
KtS4szE8u_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
KtS4szE8u_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_actionscheduler_actions: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
KtS4szE8u_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_ac_segments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_admin_columns: Daten: 0.11MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_cjl_bdemail_unsubscribe: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_cmap_endpoints: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_comments: Daten: 1.52MB + Index: 0.84MB + Engine InnoDB
KtS4szE8u_duplicator_pro_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_duplicator_pro_packages: Daten: 0.23MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_easy_query: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_energyplus_daily: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_energyplus_events: Daten: 0.08MB + Index: 0.05MB + Engine InnoDB
KtS4szE8u_energyplus_requests: Daten: 12.52MB + Index: 4.55MB + Engine InnoDB
KtS4szE8u_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_options: Daten: 7.52MB + Index: 0.30MB + Engine InnoDB
KtS4szE8u_pmr_status: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_postmeta: Daten: 19.55MB + Index: 13.97MB + Engine InnoDB
KtS4szE8u_posts: Daten: 2.52MB + Index: 0.58MB + Engine InnoDB
KtS4szE8u_post_Status: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_pum_subscribers: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
KtS4szE8u_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_signups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_snippets: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_term_relationships: Daten: 0.19MB + Index: 0.11MB + Engine InnoDB
KtS4szE8u_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_usermeta: Daten: 1.52MB + Index: 0.58MB + Engine InnoDB
KtS4szE8u_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
KtS4szE8u_user_registration_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_wc_order_product_lookup: Daten: 1.52MB + Index: 0.55MB + Engine InnoDB
KtS4szE8u_wc_order_stats: Daten: 0.17MB + Index: 0.16MB + Engine InnoDB
KtS4szE8u_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_wc_product_meta_lookup: Daten: 0.09MB + Index: 0.16MB + Engine InnoDB
KtS4szE8u_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
KtS4szE8u_wmfo_fraud_attempts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wmfo_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
KtS4szE8u_wpdatacharts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatables: Daten: 0.38MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatables_columns: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatables_rows: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatable_25_1: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatable_25_2: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatable_28: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpdatatable_33: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpgmza: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpie_template: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpmailsmtp_tasks_meta: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_wpr_rucss_resources: Daten: 11.47MB + Index: 0.09MB + Engine InnoDB
KtS4szE8u_wpr_rucss_used_css: Daten: 2.50MB + Index: 0.05MB + Engine InnoDB
KtS4szE8u_yoppoll_anonymous_users_votes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_bans: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_delete_requests: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_elements: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_logs: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_other_answers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_polls: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_skins: Daten: 0.28MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_subelements: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_votes: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
KtS4szE8u_yoppoll_votes_details: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 69
acf-field-group: 7
aoc_popup: 104
attachment: 677
boxzilla-box: 1
br_notice: 1
br_product_filter: 2
bsf-sidebar: 1
calendar: 1
custom_css: 3
ditty_news_ticker: 2
envira: 6
everest_form: 1
export_template: 4
foobar_notification: 1
mailpoet_page: 1
mec_calendars: 15
mec-events: 1
ml-slider: 1
modalpopupbox: 1
nav_menu_item: 156
ninja-table: 1
notificationx: 1
oembed_cache: 2
page: 120
pms-subscription: 2
poll: 1
popup: 69
popup_theme: 9
post: 23
product: 548
product_variation: 49
scheduled_export: 1
shop_order: 1129
shopmagic_automation: 1
tabs_pro: 2
tabs_responsive: 2
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
turbo-sidebar-cpt: 1
um_directory: 1
um_form: 3
user_registration: 1
waef: 1
watermark: 2
wbcr-snippets: 4
wc_order_email: 1
wc_order_status: 35
wc_product_table: 1
wccf_order_field: 7
wcct_countdown: 1
wpcdt_countdown: 1
wpcf7_contact_form: 1
wpforms: 1
wphash_ntf_bar: 1
wphtmlmail_mail: 21
wpt_product_table: 52
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (56) ###

404page - Ihre maßgeschneiderte 404-Fehlerseite: von Peter Raschendorfer – 11.3.0
WooCommerce Min Max Menge & Step Control: von Saiful Islam – 1.6
Admin Columns Pro - Advanced Custom Fields (ACF): von AdminColumns.com – 2.7
Admin Columns Pro - WooCommerce: von AdminColumns.com – 3.6
Admin Columns Pro: von AdminColumns.com – 5.6
Advanced Custom Fields: von Delicious Brains – 5.10.2
Advanced Database Cleaner PRO: von Younes JFR. – 3.1.6
Akismet Anti-Spam: von Automattic – 4.2.1
Approve New User Registration: von Addify – 1.4.0
Back Button Widget: von Algoritmika Ltd – 1.5.2
Code Snippets: von Code Snippets Pro – 2.14.2
Contact Form 7: von Takayuki Miyoshi – 5.5.1
Cookie Notice & Compliance for GDPR / CCPA: von Hu-manity.co – 2.1.5
Duplicator Pro: von Snap Creek – 4.0.4.1
Energy+: von EN.ER.GY – 1.2.1.1
HashBar Pro: von HasTech – 1.2.6
Inactive Logout: von Deepen Bajracharya – 2.0.2
Kadence Blocks – Gutenberg Blocks for Page Builder Features: von Kadence WP – 2.1.14
Media Library Organizer: von WP Media Library – 1.3.9
Multiple Roles: von Florian TIAR – 1.3.1
Nav Menu Roles: von Kathy Darling – 2.0.1
Page Links To: von Mark Jaquith – 3.3.5
Page Restrict: von Matt Martz & Andy Stratton – 2.5.2
PDFjs Viewer: von <a href="http://byterevel.com/">Ben Lawson</a>
<a href="https://www.twistermc.com/">Thomas McMahon</a> – 2.0.0

Phoenix Media Rename: von crossi72 – 3.4.4
Popup Anything - A Marketing Popup: von WP OnlineSupport
Essential Plugin – 2.0.4

reCaptcha for WooCommerce: von I Thirteen Web Solution – 2.4
Redirect After Login, Registration & Logout: von Addify – 1.1.4
Sidebar Manager: von Brainstorm Force – 1.1.7
SKU Generator for WooCommerce: von WP Wham – 1.5.1
WooCommerce Split Bestellg/Buchg: von Vibe Agency – 1.2.0
WP Sticky PRO: von WebFactory Ltd – 5.30
Storefront Footer Bar: von WooThemes – 1.0.4
Storefront Hamburger Menu: von WooCommerce – 1.2.2
Storefront Top Bar: von Wooassist – 1.1.1
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.16.62

User Role Editor: von Vladimir Garagulya – 4.60.2
WC Duplicate Order: von Jamie Gill – 1.7
Menge Plus Minus Button for WooCommerce: von CodeAstrology – 1.0.8
Widget Options: von Widget Options Team – 3.7.9
WooCommerce for Logged-in Users: von Rahmon – 1.2.2
Woo Manage Fraud Bestellg/Buchg: von Prasidhda Malla – 2.4.1
WOO Product Table Pro: von CodeAstrology – 7.0.9
Product Table for WooCommerce - (wooproducttable): von CodeAstrology – 3.0.1
WooCommerce AJAX Bestellkorb: von Moises Heberle – 1.3.21
Germanized für WooCommerce: von vendidero – 3.6.1
Advanced Order Export For WooCommerce (Pro): von AlgolPlus – 3.1.9
WooCommerce Order Status Manager: von SkyVerge – 1.13.0
Woocommerce Side Bestellkorb Premium: von XootiX – 3.0
WooCommerce: von Automattic – 5.8.0
WP HTML Mail - WooCommerce: von Hannes Etzelstorfer // codemiq – 2.9.9
WP HTML Mail - Email Template Designer: von Hannes Etzelstorfer // codemiq – 3.0.9
WP Mail SMTP: von WPForms – 3.1.0
WP Rocket: von WP Media – 3.10.1
wpDataTables: von TMS-Plugins – 3.6
WPFront Scroll Top: von Syam Mohan – 2.0.7.08086

### Inactive Plugins (2) ###

Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.1.2
YOP Poll Pro: von yourownprogrammer – 6.3.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #321 - /bestellung-fuer-ladentermin/
Warenkorb: #104 - /warenkorb/
Kasse: #105 - /kasse/
Mein Konto: #106 - /mein-konto/
Allgemeine Geschäftsbedingungen: #840 - /iump-tos-page/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/admin-cancelled-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/admin-failed-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/admin-new-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-completed-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-invoice.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-new-account.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-note.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-on-hold-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-processing-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-refunded-order.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/customer-reset-password.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/email-customer-details.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/email-order-details.php
/var/www/vhosts/webneumarkt.at/heimvorteil.webneumarkt.at/wp-content/plugins/wp-html-mail-woocommerce/views/woocommerce/template/email-order-items.php

### SKU Generator Settings ###

SKU Generator for WooCommerce: yes
Number generation: product_id
Sequential number generation counter: 1
Prefix: P
Minimum number length: 5
Suffix: 
Variable Produkte variations: as_variable
Template: {category_prefix}{tag_prefix}{prefix}{sku_number}{suffix}{tag_suffix}{category_suffix}{variation_suffix}
Automatically generate SKU for new Produkte: yes
Delay SKU generation till product is Veroeffentlichted: yes
Generate SKUs only for Produkte with empty SKU: no
Allow duplicate SKUs: no
Suche by SKU: no
Suche by SKU: Algorithm: posts_search
Add SKU to Mitglied emails: yes
Enable/Disable: yes
Sequential numbering on per Produzent basis: no
Use Yoast primary Produzenten: no
Alle: 
Suffix: All
Counter: 1
Almannsgrub: 
Suffix: Alm
Counter: 1
Arcushof: 
Suffix: Arc
Counter: 1
Baier R&H: 
Suffix: Bai
Counter: 1
Barbara Strasser: 
Suffix: Stra
Counter: 1
BIO Obst OÖ: 
Suffix: Biooö
Counter: 1
Biohof Hainz: 
Suffix: Hai
Counter: 1
Biohof Pertiller: 
Suffix: Pert
Counter: 1
Feldinger Wals: 
Suffix: Feld
Counter: 1
Finanzen: 
Suffix: Fin
Counter: 1
Flachgauer Biopilze: 
Suffix: Fla
Counter: 1
FoodCoop: 
Suffix: Fch
Counter: 1
Foodcoop Heimvorteil: 
Suffix: 
Counter: 
Georg Eder: 
Suffix: Ede
Counter: 1
Georg Eder Gans: 
Suffix: EdeG
Counter: 1
Gröberh. Mang: 
Suffix: GröM
Counter: 1
Gröberh.Lamm: 
Suffix: GröL
Counter: 1
Gröberhof: 
Suffix: Grö
Counter: 1
Gröberhof Truth.: 
Suffix: GröT
Counter: 1
Hölzlbauer: 
Suffix: Hölz
Counter: 1
Imkerhof Salzburg: 
Suffix: Imk
Counter: 1
Langwieder: 
Suffix: Lan
Counter: 1
Lenzenbauer: 
Suffix: Len
Counter: 1
Mani Kleinbauer: 
Suffix: Mani
Counter: 1
Rathmacherhof: 
Suffix: Rath
Counter: 1
Samshofbauer: 
Suffix: Sam
Counter: 1
Schusterbauer: 
Suffix: Sch
Counter: 1
Schusterbauer Rind: 
Suffix: SchR
Counter: 1
Sperlbauer: 
Suffix: Spe
Counter: 1
Zachhiesenhof: 
Suffix: Zac
Counter: 1
Enable/Disable: no
Aktuell: 
Suffix: 
Aufstriche: 
Suffix: 
Beeren: 
Suffix: 
Beilagen: 
Suffix: 
Beiträge: 
Suffix: 
Brot u. Gebäck: 
Suffix: 
Diverses: 
Suffix: 
Eier: 
Suffix: 
Fertiggerichte: 
Suffix: 
Finanzen: 
Suffix: 
Fisch: 
Suffix: 
Foodcoop: 
Suffix: 
Gans: 
Suffix: 
Geflügel: 
Suffix: 
Geflügel Sonderbestellung: 
Suffix: 
Gemüse: 
Suffix: 
Getreide: 
Suffix: 
Gewürze: 
Suffix: 
Gewürze griech.: 
Suffix: 
Gustostückerl: 
Suffix: 
Honig: 
Suffix: 
Hühnerfleisch: 
Suffix: 
Kalbfleisch: 
Suffix: 
Käse: 
Suffix: 
Kräuter: 
Suffix: 
Lammfleisch: 
Suffix: 
Mangaliza: 
Suffix: 
Mehlspeisen: 
Suffix: 
Milchprodukte: 
Suffix: 
Neu: 
Suffix: 
Nudeln: 
Suffix: 
Obst: 
Suffix: 
Obstbio: 
Suffix: 
Öle: 
Suffix: 
ÖlMani: 
Suffix: 
Ölmani1: 
Suffix: 
Pfand: 
Suffix: 
Pilze: 
Suffix: 
Rindfleisch: 
Suffix: 
Säfte: 
Suffix: 
Salate: 
Suffix: 
Sams1: 
Suffix: 
Sams2: 
Suffix: 
Sams3: 
Suffix: 
Schinken-Geselchtes: 
Suffix: 
Schweinefleisch: 
Suffix: 
Sirupe: 
Suffix: 
Sonderbestellung: 
Suffix: 
Sonderlieferung: 
Suffix: 
Tee: 
Suffix: 
Truthahn: 
Suffix: 
Vergleich1: 
Suffix: 
Wild: 
Suffix: 
Würste: 
Suffix: 
Zubehör: 
Suffix: 

### Action Scheduler ###

Abgeschlossen: 49
Oldest: 2021-10-15 17:01:17 +0200
Newest: 2021-10-16 12:59:57 +0200

Ausstehend: 1
Oldest: 2021-10-17 01:46:32 +0200
Newest: 2021-10-17 01:46:32 +0200

### Status report information ###

Generated at: 2021-10-16 13:00:53 +02:00
`Bericht Mitglieder

**Comment by juliaamosova** [comment]
Hi @uebes,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.8 version. 

Have you managed to isolate the issue to WooCommerce Core?

I see that you have several plugins installed. Please test your site for plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce. Then test again.

If the issue is resolved with the default theme (Storefront which is what you use) and all plugins deactivated, it means that one of your plugins is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
