### ISSUE TITLE
Site health check for missing WooCommerce shortcodes for pages

### ISSUE THREAD

**Issue by lukecav** [woothemes/woocommerce#30969]
The shortcodes would be related to the default pages that WooCommerce uses and display if any are missing in site health.

`[woocommerce_cart]` – shows the cart page
`[woocommerce_checkout]` – shows the checkout page
`[woocommerce_my_account]` – shows the user account page
`[woocommerce_order_tracking]` – shows the order tracking form

https://docs.woocommerce.com/document/woocommerce-shortcodes/#page-shortcodes
https://docs.woocommerce.com/document/woocommerce-pages/
https://docs.woocommerce.com/document/pages-not-displaying/

**Comment by juliaamosova** [comment]
Hi @lukecav,

Thanks for opening the issue! It is not clear if your report is a suggestion for improvement. Can you please confirm? If so, do you see it being a part of the System Status Report or some other section? 

![ssr](https://user-images.githubusercontent.com/19143190/138144701-766074df-2a42-4851-95ce-b705dca5e9d1.png)

**Comment by lukecav** [comment]
It would be a suggestion for an improvement for both the System Status Report and in Tools > Site Health.

**Comment by lanej0** [comment]
Hi @lukecav,
﻿
Thank you for taking the time to share this idea, we really appreciate your help. 
﻿
While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.
﻿
Stay tuned for updates.
