### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by troyibm** [woothemes/woocommerce#30974]
_Removed - Please see our security policy https://github.com/woocommerce/woocommerce/security/policy_

**Comment by ObliviousHarmony** [comment]
Hello @troyibm,

Thank you for taking the time to file this report. [As per our security policy](https://github.com/woocommerce/woocommerce/security/policy), please report any potential security issues via HackerOne. This allows us to handle them appropriately, as well as avoid accidental disclosure.
