### ISSUE TITLE
Special sales products do not include free shipping.

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#30985]
Please add a feature for free shipping, so that products in the special sales do not include free shipping.
This is much needed.
Because most customers want this feature from us, but we can not implement it ...

thank you

**Comment by juliaamosova** [comment]
Hi @79ho3ein,

Thank you for opening the issue! There are several Free Shipping options already available in WooCommerce - please refer to the [Free Shipping documentation](https://docs.woocommerce.com/document/free-shipping/).

Is there any particular scenario that you are missing? There are many plugins available to address various Free Shipping cases as well depending on your needs.

**Comment by 79ho3ein** [comment]
hello @juliaamosova , Thank you for your answer.
I did not find it like that. But the problem was solved. thank you
I will close this request with your permission
