### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: method_exists()

### ISSUE THREAD

**Issue by mujuonly** [woothemes/woocommerce#30991]
PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given in /example/plugins/woocommerce/includes/class-wc-install.php:621

WC 5.8
WP 5.8

**Comment by juliaamosova** [comment]
Hi @mujuonly,

Thank you for opening the issue! It doesn't have enough information for us to further evaluate it. Are there any specific actions that you take on the site that generate the error?

**Comment by dartrax** [comment]
Hi,
I have the same problem. It occures every 10 minutes when I'm in the admin interface. There is also another topic in the [wordpress plugin support forum](https://wordpress.org/support/topic/critical-error-after-upgrading-to-woocomerce-v6-x-class-wc-install-php/). 

I believe that this error can happen when one of the filters applied to `woocommerce_get_settings_pages` adds an item that is not inherited of `WC_Settings_Page` to the settings array [here](https://github.com/woocommerce/woocommerce/blob/2c1885f69a7ed66fd56ef8cf028b9184939664a2/plugins/woocommerce/includes/admin/class-wc-admin-settings.php#L62) for any reason.

I made a quick fix, I added the following line:
`if ( ! is_a( $section, 'WC_Settings_Page' ) ) continue;`
directly before this line: https://github.com/woocommerce/woocommerce/blob/2c1885f69a7ed66fd56ef8cf028b9184939664a2/plugins/woocommerce/includes/class-wc-install.php#L643

It checks if the item is inherited of `WC_Settings_Page` before passing it to method_exists() which will fail if not. Shouldn't this check be implemented to upstream woocommerce?
