### ISSUE TITLE
Limit the order statuses when manually creating a new order

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#31003]
**Is your feature request related to a problem? Please describe.**
At the moment, you when you manually create a New Order on the backend, you can choose from illogical statuses such as "failed" and "cancelled" and "refunded". This seems like poor UX and opens up the possibility of mistakenly choosing an order status that makes no sense at this stage in the workflow.

**Describe the solution you'd like**
Limit order statuses to only those that make sense (pending payment, processing, complete) and gray out the other statuses.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Jplus2** [comment]
### Screenshots

![image](https://user-images.githubusercontent.com/5361093/138196508-6f14637a-ddce-4fc9-a38b-d10eeaa8a0e3.png)

![image](https://user-images.githubusercontent.com/5361093/138196833-b5983dc4-4797-4fe2-b241-73b8274ee358.png)

![image](https://user-images.githubusercontent.com/5361093/138196839-98972df4-f564-4f3a-ab9f-7d0c5d4663d7.png)

**Comment by pacmanito** [comment]
@jkohlbach I am sorry for interfering, but in my opinion, it's no good to limit users' freedom considering them not capable to make proper decisions. I can imagine some situations when you would want to create an order with some obscure status and finding that it's impossible would be very frustrating.
BTW there's a special filter 'wc_order_statuses' which allows you to easily achieve the desired effect. Some examples are available here - https://rudrastyh.com/woocommerce/order-statuses.html and here - https://stackoverflow.com/questions/64439917/hide-order-statuses-in-dropdown-based-on-order-status-in-woocommerce-edit-order

**Comment by jkohlbach** [comment]
@pacmanito they'd still be able to change the status after the order is created, for me it just doesn't make sense to create a brand new order manually directly into refunded or cancelled or failed status. It's bad UX. 

Also, I always appreciate feedback and its definitely not interfering - I think this should be a core change and getting comments is exactly why I raised it so definitely don't hold back! :)

**Comment by juliaamosova** [comment]
Hi @jkohlbach,

Thank you for raising the issue, it is an interesting one. 

Making changes to core functionality such as order statuses will be a big one and will require us to support backward compatibility to make sure things still work for those merchants who use these statuses as well as extensions developers who rely on the functionality as it is. Removing these order statuses won't be a decision that we will take lightly. 

I'll mark this issue as an enhancement with votes needed tag to gather feedback from folks over time. However, please don't be alarmed if there will be no action taken on our end on it for a while.

**Comment by barryhughes** [comment]
I like this idea, but I share the concern already expressed about the potential for disruption. Additionally, we have a pretty large backlog of requests—and so it seems unlikely we'll reach this one any time soon.

For those reasons, I'm going to close the issue. This idea could definitely be worth revisiting in the future, though, especially if we begin work on a larger refactoring of the order editor experience.
