### ISSUE TITLE
Restock refunded products not working properly

### ISSUE THREAD

**Issue by clukas1** [woothemes/woocommerce#31011]
Hi,

The problem occurs when products are restocked during refunds and the admin order page is saved anytime after. This is because the order item meta data `_reduced_stock` and `_restock_refunded_items` are deleted when the full amount of order_items is refunded in `wc_restock_refunded_items(`), which then causes `wc_maybe_adjust_line_item_product_stock()` to deduct the order items again from stock and thereby reversing the stock increase from the refund.

The passage which causes this error, is Line 715-727 in wc-order-functions.php.
```
// Update _reduced_stock meta to track changes.
$item_stock_reduced = $item_stock_reduced - $qty_to_refund;

if ( 0 < $item_stock_reduced ) {
	// Keeps track of total running tally of reduced stock.
	$item->update_meta_data( '_reduced_stock', $item_stock_reduced );

	// Keeps track of only refunded items that needs restock.
	$item->update_meta_data( '_restock_refunded_items', $qty_to_refund + $restock_refunded_items );
} else {
	$item->delete_meta_data( '_reduced_stock' );
	$item->delete_meta_data( '_restock_refunded_items' );
}
```

In my opinion, the `0 <` comparison should at least be `0 <=`, as a full refund results in `$item_stock_reduced == $qty_to_refund` and further down the line to `$item_stock_reduced = 0`. This is not greater zero, hence the item meta data will be deleted. Although, I generally do not understand, why this comparison is necessary in any case and the meta data values should be deleted in any scenario. One could just cap `$qty_to_refund` to be maximally `$item_stock_reduced`.

Thanks and best regards.

**Comment by juliaamosova** [comment]
Hi @clukas1,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @clukas1 , thanks for the detailed report. Looks like this issue is same as https://github.com/woocommerce/woocommerce/issues/30618. I will close this issue in favor of #30618 for repository maintenance, but this is one of higher priority issue that we will be working on soon.
