### ISSUE TITLE
Track the type of product added/published

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#31032]
**Description:** We'd like to update the `wcadmin_product_add_publish` event to include new props identifying the type of product that was published, among other things:

New event props:

`product_type`
values: simple, variable, external, bookings, etc

`is_downloadable`
values: yes | no

`is_virtual`
values: yes | no

`manage_stock`
values: yes | no

The `wcadmin_product_update` event already includes the same props ([src](https://github.com/woocommerce/woocommerce/blob/66ad8774d9cdccda421e2a7ff44418fcdd2e4bbd/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L127)).

## Acceptance criteria

- Every time the `wcadmin_product_add_publish` Tracks event is recorded, it includes the `product_type`, `is_downloadable`, `is_virtual`, and `manage_stock` properties as described above.

## Dev tasks

- [ ] Figure out how to access the product properties in the src listed below (you should be able to take the post object and use it to create a `WC_Product` object)
- [ ] Update code that records the `wcadmin_product_add_publish` Tracks event to include the props listed above ([src](https://github.com/woocommerce/woocommerce/blob/66ad8774d9cdccda421e2a7ff44418fcdd2e4bbd/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L163))

**Comment by pmcpinto** [comment]
@elizaan36 is there anything else that you'd like to include

cc @becdetat just to ensure this is included in Cycle 19

**Comment by elizaan36** [comment]
looks great!

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/31032?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro

**Comment by mattsherman** [comment]
@woocommerce/mothra Just making sure that everybody notices that @joshuatf started on this issue... before picking this up, check with him to see if he has any WIP to push first.
