### ISSUE TITLE
WooCommerce order notification emails not triggered when using the PayPal Standard Checkout

### ISSUE THREAD

**Issue by tloughlin130** [woothemes/woocommerce#31040]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Notification emails are not being triggered for New Orders or Cancelled Orders ONLY when using the PayPal Standard Checkout option.

**Expected behavior**
Notification emails should be sent when a new order is received and when orders are cancelled.

**Actual behavior**
No emails are even being triggered.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://harpersferrywoodwork.com/
2. Click on Shop
3. Add an item to your cart
4. Complete the form and click Checkout, which takes you to PayPal. If you cancel your order and return to the website, it'll cancel your order with the website. Which should normally generate an email notification.

 DONE... I've tried deleting all plugins but WooCommerce and changing themes. Only changing the Checkout option to something other than PayPal fixed the issue.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://harpersferrywoodwork.com
Site address (URL): https://harpersferrywoodwork.com
WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.24
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.35-38-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: wp_
Total Database Size: 90.99MB
Database Data Size: 49.63MB
Database Index Size: 41.36MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 1.95MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 2.02MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.02MB + Index: 1.06MB + Engine InnoDB
wp_postmeta: Data: 24.22MB + Index: 31.91MB + Engine InnoDB
wp_posts: Data: 2.41MB + Index: 0.55MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_country: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.47MB + Index: 0.75MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.13MB + Index: 0.22MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 180
avia_framework_post: 33
mailpoet_page: 1
nav_menu_item: 7
page: 10
post: 3
product: 37
product_variation: 2270
revision: 23
shop_coupon: 1
shop_order: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Add More Shipping Fields (For Multi Part Product): by PluginHive – 1.1.3
Code Snippets: by Code Snippets Pro – 2.14.2
Coming Soon Badge for WooCommerce: by wpcentrics – 1.0.10
Facebook for WooCommerce: by Facebook – 2.6.5
Genesis Blocks: by StudioPress – 1.3.0
Google Listings and Ads: by WooCommerce – 1.5.1
Smash Balloon Instagram Feed: by Smash Balloon – 2.9.4
Jetpack: by Automattic – 10.2
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.23
Product Input Fields for WooCommerce: by Tyche Softwares – 1.3.1
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 2.0.30
WooCommerce Shipping & Tax: by WooCommerce – 1.25.19
WooCommerce UPS Shipping: by WooCommerce – 3.2.36
WooCommerce: by Automattic – 5.8.0
Yoast SEO: by Team Yoast – 17.3
WP Debugging: by Andy Fragen – 2.11.2
WP Mail Logging: by Wysija – 1.9.9

### Inactive Plugins (1) ###

Akismet Anti-Spam: by Automattic – 4.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.1
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #506 - /shop/
Cart: #507 - /cart/
Checkout: #28 - /checkout/
My account: #29 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.8.3
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,193
Oldest: 2021-10-01 14:06:02 +0000
Newest: 2021-10-27 14:19:24 +0000

Failed: 7,319
Oldest: 2021-07-09 13:58:14 +0000
Newest: 2021-09-03 05:07:53 +0000

Pending: 3
Oldest: 2021-10-27 14:42:53 +0000
Newest: 2021-10-28 03:28:18 +0000

### Status report information ###

Generated at: 2021-10-27 09:42:57 -05:00
`
</details>

**Comment by rodelgc** [comment]
Hi @tloughlin130,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. The "New Order" and "Cancelled Order" email notifications were generated correctly on my end in WC 5.8.0.
 
I tested it using the following setup:
- WC 5.4.3 that's later upgraded to WC 5.8.0 to match your WC version as stated in your system status report
- PHP 7
- Apache Server
- MySQL 5
- Twenty Twenty-One Theme

Here are the steps I took in trying to replicate your issue:
1. Install WC `5.4.3` as it's the version that still shows PayPal Standard in the list of Payment settings.
2. In _WooCommerce > Settings > Payments_, I enabled PayPal Standard with the "PayPal Sandbox" option enabled as well (for testing).
3. I upgraded WC `5.4.3` to `5.8.0`.
3. I visited the store page as a customer in another browser session, checked out a product using PayPal Checkout (in sandbox mode), and went through the PayPal Checkout process until payment, and then returned to the merchant site.
4. I verified in WooCommerce > Orders that the order was entered as "Pending Payment". I updated the status to "Processing".
5. As you can see from the screenshot below, the "New Order" email was generated both for the merchant and the customer:
    <img width="936" alt="Screen Shot 2021-11-04 at 9 30 38 PM 1" src="https://user-images.githubusercontent.com/4509348/140324763-ac30a6cc-1ffa-46d7-baf6-97e5e1913ccd.png">
    <img width="936" alt="Screen Shot 2021-11-04 at 9 33 15 PM" src="https://user-images.githubusercontent.com/4509348/140324806-b55129e3-fad3-44c9-9c82-06cf8853835e.png">
6. While the order was opened in WooCommerce > Orders > Edit Order, I changed the status to "Cancelled". As you can see from the image below, the "Cancelled Order" email notification was generated correctly:
    <img width="938" alt="Screen Shot 2021-11-04 at 9 36 06 PM" src="https://user-images.githubusercontent.com/4509348/140325071-5d347a50-6333-4cc9-abaf-6e95bfc5814b.png">

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by tloughlin130** [comment]
I must've needed to actually hit Cancel Order in WordPress to generate that email then. I just assumed that an email would be generated after a person abandons their order in the PayPal process, ie. when they click "cancel and return to website" within the PayPal app, since the order then appears as Cancelled in WordPress. 

The emails are now working for New Orders, so I'm not sure if an update fixed that.

**Comment by AashikP** [comment]
> The emails are now working for New Orders, so I'm not sure if an update fixed that.

Thank you for clarifying that things are working as expected now. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
