### ISSUE TITLE
Products table accordion expands different row on mobile

### ISSUE THREAD

**Issue by elizaan36** [woothemes/woocommerce#31054]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
On mobile the products table collapses into a layout showing an accordion for each row. When clicking the accordion, the row below opens rather than the row being clicked.

![Screen Recording 10-29-2021 at 4 01 PM](https://user-images.githubusercontent.com/5121465/139501472-1ba7ce21-ff62-43fc-bc9d-46c87c2f7759.gif)

**Expected behavior**
The accordion should open the product listing row that the user has just clicked on, not the one below.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'All products' on mobile web
2. Click on the accordion caret to expand the product listing row
3. See error

**Comment by tammullen** [comment]
Thank you @elizaan36 for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26770. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
