### ISSUE TITLE
Make sure WooRelease works with the monorepo structure

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#31061]
[WooRelease](https://github.com/woocommerce/woorelease) is used to release WooCommerce. Since the repo now has a non-standard structure, we need to make sure it can still be used to release WooCommerce.

**Comment by psealock** [comment]
I'd like to note the `trunk` branch of [action-build](https://github.com/woocommerce/action-build) Github Action has updated processes to handle the monorepo.

[build-release-zip-file](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/build-release-zip-file.yml) still points to `@v2` and it may be useful to use `trunk` and eventually make another release or bring the code into the monorepo. I wasn't sure you were aware @jonathansadowski, so pointing it out here.

Another interesting thought I had on this was the possibility of running woo-release directly on the [production repo](https://github.com/woocommerce/woocommerce-production) which has all assets already built.

**Comment by jonathansadowski** [comment]
https://github.com/woocommerce/woorelease/pull/337 merged a PR that has been tested to make monorepo work with WR.
