### ISSUE TITLE
WC_Checkout::get_posted_data() returns an array of default values and empty strings when called inside an AJAX call, since most of the data it uses is inside post_data field.

### ISSUE THREAD

**Issue by EngHell** [woothemes/woocommerce#31096]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the `bug**`
When doing `jQuery('body').trigger('update_checkout')` the checkout data is sent through AJAX this put the field `ship_to_different_address` and other fields, like `shipping_address, billing_address, etc` inside a serialized field called 'post_data', which makes WC_Checkout::get_posted_data() fail, which makes a lot of functions to return wrong data in an AJAX context for the checkout, examples: 
1. WC_Checkout::get_posted_address_data

**Expected behavior**
Calling `WC_Checkout::get_posted_data()` inside an AJAX call to calculate_shipping should yield correct results.

**Actual behavior**
Calling `WC_Checkout::get_posted_data()` inside an AJAX call to calculate_shipping  returns default values and empty strings.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to the checkout page.
2. Check the option to use a different shipping address.
2. Fullfill the data.
2. In the javascript console, call `jQuery('body').trigger('update_checkout')`
2. Inside `calculate_shipping` of the selected shipping class call `WC_Checkout::get_posted_data()` and assign the result to any variable.
3. Inspect the contents of `ship_to_different_address` key of the associative array.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active, im developing a plugin for pickup requests.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): http://localhost/ft
Site address (URL): http://localhost/ft
WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Ubuntu)
PHP Version: 7.4.24
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1j

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-0ubuntu0.21.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: wp_
Total Database Size: 8.17MB
Database Data Size: 6.11MB
Database Index Size: 2.06MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.25MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_freightQuote_carriers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.13MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_warehouse: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 168
custom_css: 1
nav_menu_item: 3
page: 8
post: 2
product: 63
revision: 45
shop_order: 26
shop_order_refund: 3
shortcoder: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

FreightQuotes
WooCommerce: by Automattic – 5.8.0

### Inactive Plugins (14) ###

BugFu Console Debugger: by Federico Andrioli – 1.3.0
eCheck Processing eCheckProcessing.com: by eCheckProcessing.com – 1.5
Genesis Blocks: by StudioPress – 1.2.3
Min and Max Quantity for WooCommerce: by BeRocket – 1.3.2.1
New User Approve: by NewUserApprove – 1.9.1
Payment Gateways by User Roles for WooCommerce: by Imaginate Solutions – 1.2.3
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.12

Product Prices by User Roles for WooCommerce Pro: by Tyche Softwares – 1.3.4
Shortcoder: by Aakash Chakravarthy – 5.5
User Role Editor: by Vladimir Garagulya – 4.60.1
WooCommerce for Logged-in Users: by Rahmon – 1.2.2
WooCommerce Measurement Price Calculator: by SkyVerge – 3.19.2
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18 (update to version 1.25.19 is available)
WPForms Lite: by WPForms – 1.6.8.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3 (update to version 1.4 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 127
Oldest: 2021-10-11 15:10:23 -0500
Newest: 2021-11-05 14:19:19 -0500

Pending: 2
Oldest: 2021-11-05 14:20:19 -0500
Newest: 2021-11-05 17:00:46 -0500

### Status report information ###

Generated at: 2021-11-05 14:19:30 -05:00
`

**Comment by EngHell** [comment]
This is the fastest workaround I could've thought of
``` php
public function get_posted_data() {
		// phpcs:disable WordPress.Security.NonceVerification.Missing


		if(is_ajax()){
			$post_data = [];
			parse_str($_POST['post_data'], $post_data);
			$_POST = array_merge($_POST, $post_data);
		}
...
```
Although it's a really hacky option to follow, and would be better placed inside calculate_shipping

**Comment by tammullen** [comment]
Hi @EngHell ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for highlighting this.

It is indeed a little confusing, but methods such as `WC_Checkout::get_posted_data()` are intended to be called when the checkout is finally submitted, rather than during ajax requests. Updating it to work as noted in your expectations is probably viable, but we would first need to make sure doing so won't cause problems elsewhere (including with other third party integrations).

To help us figure out the extent to which this is needed, could you outline why deriving the information you need from the `$package` data in your custom `calculate_shipping()` method isn't sufficient?
