### ISSUE TITLE
Document wc_get_products default 10 objects fetch

### ISSUE THREAD

**Issue by mfru** [woothemes/woocommerce#31101]
**Is your feature request related to a problem? Please describe.**
I spent quite some time debugging because it was not clear to me that `wc_get_products` only returns 10 objects if you do not specify a limit.

I expected the query to return all products per default or have the default limit documented in https://woocommerce.github.io/code-reference/files/woocommerce-includes-wc-product-functions.html and/or https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query

I finally found out about the default limit on https://stackoverflow.com/a/52710078/3146046

What would have been the correct path to discover that peculiarity? 
Is it somewhat of a WP convention?

**Describe the solution you'd like**
Document that `wc_get_posts` returns 10 items if one doesn't specify the `limit` option.

**Describe alternatives you've considered**
Alternatively, I would like to know where I could have looked instead of the provided locations.

**Additional context**
_None_

**Comment by juliaamosova** [comment]
Hi @mfru,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
I'd say we're broadly following WordPress conventions here, and the [wiki page](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query) we link to from the [wc_get_products() docs](https://woocommerce.github.io/code-reference/files/woocommerce-includes-wc-product-functions.html) does already describe that `limit` must be set to `-1` to retrieve all products:

> **limit**
> 
> Accepts an integer: Maximum number of results to retrieve or -1 for unlimited.

We could probably make things a little clearer, though. In case helpful, please note that default isn't actually 10: it is the value of the `posts_per_page` option (which does itself default to 10, but is configurable and overrideable).

**Comment by mfru** [comment]
Thank you for your clarification.
As a not-full-time WP dev it is quite hard for me to go through the source code, otherwise I probably could have spotted the `posts_per_page` default behavior.

If you are interested in outside contributions, I would be willing to open a pull request for clarification.

The easiest and most concise way for me personally would have been to communicate the default behavior in `limit`.

`When not specified, it defaults to WordPress' posts_per_page, which is usually 10 (if not overridden)`.

and maybe in the most simple use case:

```
// Default query
// Returns the 10 most recent results. (Note: 10 is the default for WordPress' posts_per_page variable and can be overridden)

$products = wc_get_products( array() );
```

**Comment by barryhughes** [comment]
For sure, I agree it's something for us to improve—thank you for flagging it.

> If you are interested in outside contributions

Always! We have some guidance [on making contributions](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and are happy to review submissions.

That said, as things are currently configured, I believe only team members can update the wiki—which is where the main documentation for querying products sits at present (and we can take care of that one).

**Comment by barryhughes** [comment]
The [WC Query documentation](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query) in the wiki has now been updated in respect of the `limit` argument.
