### ISSUE TITLE
Javascript 'address-i18n.js' does not support checkboxes added by custom plugins.

### ISSUE THREAD

**Issue by noknokcody** [woothemes/woocommerce#31107]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
address-i18n assumes that all ":inputs" are inputs when it comes to hidden fields.
``` PHP

// Hidden fields.
if ( 'state' !== key ) {
    if ( typeof fieldLocale.hidden !== 'undefined' && true === fieldLocale.hidden ) {
        field.hide().find( ':input' ).val( '' );
    } else {
        field.show();
    }
}
``` 

Specifically speaking, this line here.

``` PHP
field.hide().find( ':input' ).val( '' );
```

This line is a problem because, on checkbox fields, WooCommerce adds a static ```<input ... value="1" />``` to all checkbox fields on address/checkout forms. When you clear this value using ```.val('')``` this field will always be treated as "unchecked" and submit an ambiguous empty value when submitted.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
 
### Custom Code 
_**NOTE: Certain names have been changed to protect IP and code has been simplified for demo purposes so I apologise for bugs (if any)**_
```PHP
// Setup the custom field
add_filter( 'woocommerce_checkout_fields', function( $fields ) {
    $fields['billing']['my_custom_field'] = array(
            'type'      => 'checkbox',
            'label'     => __( 'My custom field '  ),
            'required'  => false, 
            'priority'  => 310,
            'class'     => [
                'form-fow-wide'
            ],
    )
    return $fields
}  );

// Add internationalization for checkbox field
add_filter( 'woocommerce_get_country_locale', function( $locale ) {
    $locale['NZ']['my_custom_field'] =  [
        'hidden' => true
    ];
    
    return $locale;
}, 100 );
```

Now inspect the code at checkout and look for the new field. Take note of ```<input ... value="1" />```

Change the Billing Country to "New Zealand"

Now inspect the code for the new field. You should see ```<input ... value />``` instead.

Now when this form is submitted WooCommerce will assume this checkbox is unticked regardless of whether it was ticked or not. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
n/a

**Comment by juliaamosova** [comment]
Hi @noknokcody,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
Removing "needs developer feedback" as discussion is being conducted in the attached PR.

**Comment by noknokcody** [comment]
> Removing "needs developer feedback" as discussion is being conducted in the attached PR.

Had another client complain about checkboxes on their custom forms playing up after a WooCommerce update. Could someone please take another look at this ?
