### ISSUE TITLE
GDPR compliance for default customer location by geolocation

### ISSUE THREAD

**Issue by jankarres** [woothemes/woocommerce#31118]
### Technical feature
In WooCommerce Core, you can go to _WooCommerce > Settings > Integration > MaxMind Geolocation_ and enter a license key for the MaxMind Geolocation Database to download it. Then you can set the option to _Geolocate_ or _Geolocate (with page caching support)_ under _WooCommerce > Settings > General > Default customer location_. This will run https://github.com/woocommerce/woocommerce/blob/9d08ac8ac3723c897e08ac2ff8a6d950f0e26b5b/plugins/woocommerce/includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-database-service.php#L144-L171 on page load and check the visitor's full IP address against the MaxMind Geolocation Database to determine the visitor's country. 

To store the determination of the visitor's country, a redirect mechanism is used in https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/class-wc-cache-helper.php#L183-L229, which stores the user's location in hashed form in the cookie `woocommerce_geo_hash`.

### Legal situation in the EU

We consider the pre-selection of the customer location as a convenience feature, as the WooCommerce store would work without this feature.

According to [ECJ Case C-582/14](https://curia.europa.eu/juris/document/document.jsf?docid=184668&text=&dir=&doclang=EN), the IP address may constitute a personal data. If it constitutes personal data, a legal basis for its processing is required under [Art. 6 GDPR](https://gdpr-info.eu/art-6-gdpr/). As this not a technically necessary feature, we consider Art. 6(1)(f) GDPR (legitimate interest) not applicable, which conversely means that presumably only Art. 6(1)(a) GDPR (consent) is applicable.

Furthermore, according to [ePrivacy Directive (Directive 2009/136/EC) Art. 66](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32009L0136), the storage of non-essential cookies (regardless of whether personal data or other data is stored in them) is only permitted with explicit consent. Since the operation of the WooCommerce store could also be done without setting the cookie, we assume that to set the cookie must have explicit consent.

**Practical consequence:** This means that we are in the legal opinion that the above-mentioned feature can only be used for visitors in the EU if the visitor has given his or her explicit consent. 

### Question

We as CMP (consent management platform) manufacturer could unfortunately not find e.g. a filter to tell WooCommerce if the EU legislation applies and if the visitor has consented. Manipulating the `wp_option` line `woocommerce_default_customer_address` to disable the geolocation feature for visitors without consent also does not seem to make sense, as this way the redirect mechanism would never be triggered and thus when using a page cache the determination of the user's location would never be possible.

How can a CMP hook into this geolocation feature to tell WooCommerce if EU legislation applies and if the visitor has consented?

**Comment by juliaamosova** [comment]
Hi @jankarres,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by kkmuffme** [comment]
In my opinion the country cookie is a technical necessity (to comply with privacy laws, unit price, currency, ...) and not just a convenience feature.

Especially, since we can just **not** set the cookie and just resolve the IP dynamically on every request (which would be slower in this case) - but this is what is happening for most of internet traffic, since most proxy-CDNs (Cloudflare,...) provide the user country in a header on every request anyways.
Why is that covered by GDPR? Because user country is commonly used for web application firewalls, geo-blocking,... which are not for convenience but required. By just storing this data as a cookie, no additional data processing happens whatsoever (in fact the opposite is true, since we only locate the IP once instead of on every request).

**Comment by jankarres** [comment]
Thanks for your feedback @kkmuffme.

### CDNs
> [...] this is what is happening for most of internet traffic, since most proxy-CDNs (Cloudflare,...) provide the user country in a header on every request anyways.
Why is that covered by GDPR? Because user country is commonly used for web application firewalls, geo-blocking,... which are not for convenience but required. 

I can agree with you that e.g. CDNs have to do an IP address lookup. In my legal opinion, this is justified by [Art. 6 lit. f GDPR](https://gdpr-info.eu/art-6-gdpr/), since both the provision of the service would not be possible without this data processing and the security of the systems, e.g. by avoiding the overloading of systems, can only be guaranteed in this way.

### Technical advantages

> Especially, since we can just not set the cookie and just resolve the IP dynamically on every request (which would be slower in this case) 

The [ePrivacy Directive (Directive 2009/136/EC)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32009L0136) Art. 66 (setting cookies) and [Art. 6 GDPR](https://gdpr-info.eu/art-6-gdpr/) (processing of personal data) are two different rights. Lumping them together and highlighting a technical advantage of data processing one way or the other, I see as legally irrelevant.


### Data processing by WooCommerce

However, I have to disagree with you in the case of WooCommerce's feature.

@kkmuffme You write that the feature is necessary "to comply with privacy laws, unit price, currency, ...". I assume you are referring to the legal basis for processing personal data under [Art. 6 lit. c GDPR](https://gdpr-info.eu/art-6-gdpr/). Could you please explain with evidence which legal provisions are fulfilled here, exactly with which code unit?

According to my knowledge, the country code is primarily used to pre-fill the user's country in the ordering process. I do not see any legal obligation for this from the perspective of EU law and German law.

### Optional feature technically mandatory?

The geolocation feature in WooCommerce must be explicitly enabled by the store owner. So, WooCommerce works technically flawless even without this feature. The feature is technically not essential because the website works without it.

According to [ePrivacy Directive (Directive 2009/136/EC)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32009L0136) Art. 66, only the technical necessity is essential. Obviously, this is not the case, as WooCommerce works fine without this feature. Therefore, from my perspective, setting the cookie is already subject to consent.

If there is a necessity for data processing according to [Art. 6 lit. c GDPR](https://gdpr-info.eu/art-6-gdpr/) (fulfillment of a legal obligation): Why is the feature disabled by default, and why doesn't WooCommerce inform its users that its use is illegal in the default settings within the EU?

I would appreciate a more detailed explanation to be able to clarify the issue, @kkmuffme!

**Comment by kkmuffme** [comment]
Let's just take the simplest use case you mention (and argue against it, for the sake of it):
>According to my knowledge, the country code is primarily used to pre-fill the user's country in the ordering process. I do not see any legal obligation for this from the perspective of EU law and German law.

Let's find the simplest reason why geolocating is required for EU shops: (e.g. selling digital goods like woocommerce.com)
to comply with the EU VAT laws, every company is required to confirm the customer's location for VAT purposes. By geolocating the user, we have complied with this - we have a reason for data processing.

Regarding the cookie:
since we have a legal obligation to geolocate, we also have a reason why we are allowed to store the cookie.

>why doesn't WooCommerce inform its users that its use is illegal in the default settings within the EU?

Because it's not true. In fact, it is mandatory if you are selling to EU countries.
Why doesn't WooCommerce tell you about it? Because WooCommerce is not your lawyer.
e.g. WooCommerce doesn't support base unit pricing either - but it's required in a couple EU countries (Germany being one of them)

===

To look at another example: go to amazon.co.uk (or .de as you're from there) in a private mode window. You'll see they store a cookie "i18n-prefs" which stores the user's currency. Using your argumentation above, this would be illegal.
Please get in touch with amazon; you can use the exact same text and legalese as in your text above, and report back what they say about it ;-)

Conclusion:
Honestly, this is such a non-issue. GDPR has been in force since x years, there are more than a million WooCommerce shops and there were no legal issues reported so far.

EDIT: btw you gave the reason why the cookie is a technical necessity yourself in your OP:
>to disable the geolocation feature for visitors without consent also does not seem to make sense, as this way the redirect mechanism would never be triggered and thus when using a page cache the determination of the user's location would never be possible.

Related: https://github.com/woocommerce/woocommerce/issues/26383 as #wontfix

Anyway, I provided a pull request for you. It's up to woocommerce to decide on this then. Is this filter something that would work for you?

**Comment by jankarres** [comment]
> Let's find the simplest reason why geolocating is required for EU shops: (e.g. selling digital goods like woocommerce.com)
to comply with the EU VAT laws, every company is required to confirm the customer's location for VAT purposes. By geolocating the user, we have complied with this - we have a reason for data processing.

Unfortunately, this statement shows a legal lack of knowledge on your part.

The [Directive 2006/112/EC Art. 138 para. 1](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32006L0112) and newer versions of the legislation regulate the procedure generally known as Reverse Charge. In Germany, as an example, the legal was implemented in [§ 6a UStG](https://www.gesetze-im-internet.de/ustg_1980/__6a.html).

The European Court of Justice has ruled in [case C-21/16](https://curia.europa.eu/juris/document/document.jsf?docid=187683&text=&dir=&doclang=EN&part=1&occ=first&mode=DOC&pageIndex=0&cid=3316674) that an EU VAT check must be performed via e.g. [VIES](https://europa.eu/youreurope/business/taxation/vat/check-vat-number-vies/index_en.htm). A check of the location via geolocation technologies such as IP-to-Country is not permissible in terms of the EU-wide standardization of VAT tax law.

Therefore, from my perspective, your raised argument does not apply. If you should see it differently, I would be very pleased if you could substantiate your claims with sources in the future, so that we can have a fact-oriented discussion.

What other legal obligation do you see to use geo-location technologies processing personal data?

> Because it's not true. In fact, it is mandatory if you are selling to EU countries.
Why doesn't WooCommerce tell you about it? Because WooCommerce is not your lawyer.
e.g. WooCommerce doesn't support base unit pricing either - but it's required in a couple EU countries (Germany being one of them)

If I understand you correctly you want to say that WooCommerce is not designed for EU law. From this you deduce that technically optional features in countries outside the EU is technically necessary within the EU?

This argument sounds a bit far-fetched to me. A technical necessity is limited to a technical consideration of the circumstances. In my understanding, a legal necessity does not imply a technical necessity.

> To look at another example: go to amazon.co.uk (or .de as you're from there) in a private mode window. You'll see they store a cookie "i18n-prefs" which stores the user's currency. Using your argumentation above, this would be illegal.

This is not correct. The cookie "i18n-prefs" on Amazon's country-specific websites does not contain the user's currency (which for example is assumed by geolocation). Instead, it initially stores currency of the currency typical in Amazon's country-specific websites (e.g. for amazon.de EUR or amazon.co.uk GBP).

Whether this cookie, without processing personal data, may be set without consent, I think one can be discussed.

At this point, to point out that Amazon is certainly doing everything right, sounds to me like a straw man argument. It is widely known that large companies and often prefer to violate data protection laws instead of complying with them, because from an economic point of view this is more favorable. For example, [Amazon has already been fined 42 million euros for an inappropriate cookie banner](https://techcrunch.com/2020/12/10/france-fines-google-120m-and-amazon-42m-for-dropping-tracking-cookies-without-consent/).

> btw you gave the reason why the cookie is a technical necessity yourself in your OP:

Please re-read the original request and include the overall context in your argument. 

The quoted statement is not an argument that processing the IP address or setting a cookie with this information is technically essential. It describes that disabling until consent is not a working technical approach with the current design of WooCommerce to implement a hook to check for consent.

> Anyway, I provided a pull request for you. It's up to woocommerce to decide on this then. Is this filter something that would work for you?

Thank you for providing #31317 despite the different legal opinion.

Unfortunately, the filter only prevents the cookie from being set. It does not prevent the processing of personal data (IP address). Therefore, it is unfortunately not suitable for solving the problem.

However, our developer has again read deeper into the WooCommerce core code and has found a solution to the problem with existing means.

**Solution:** Using the filter `option_woocommerce_default_customer_address`, the setting can be manipulated in such a way that no processing of personal data (and subsequently the setting of the cookie) does not take place. This works due to the concrete way the redirect mechanism of WooCommere works, if the option "Default customer location" is set to "Geolocate (with page caching support)" also with page caches (unless the page cache delivers the cache before executing the geolocation logic, when WooCommerce appends the parameter `v` to the URL as query string).

**Code example:**
```
add_filter('option_woocommerce_default_customer_address', function ($set_default_location_to) {
    $isConsentGiven = [...];

    if (
        in_array($set_default_location_to, ['geolocation', 'geolocation_ajax'], true) &&
        !$isConsentGiven
    ) {
        return 'base';
    }
    
    return $set_default_location_to;
});
```

**Comment by kkmuffme** [comment]
@jankarres fyi the pull request was merged. From WC 6.2 which will release next month, you can use the filter `woocommerce_set_cookie_enabled` to set it fo false to not set any WC cookies.
