### ISSUE TITLE
Update Monorepo Documentation

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#31116]
Once both #31066 and #31072 have been merged, the primary infrastructure for managing and interacting with the Monorepo will be in place. This requires us to update documentation across the repository, as well as the wiki, in order to make it clear how to use the new features. We also have a number of references to old file locations that should be cleaned up.

- [x] [E2E Testing Readme](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests/e2e)
- [x] [Development Environment Wiki Page](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment)
- [x] [Unit Testing Readme](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/README.md)
- [x] Document `wp-env` Usage
- [x] Review other potential links within repository to old paths

**Comment by helgatheviking** [comment]
This page: https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment
could stand to be a lot more discoverable... could you put it on the project readme.md? The main readme.md links to the [developer wiki](https://github.com/woocommerce/woocommerce/wiki) but the setup page isn't linked.... nor is it linked from the [developer doc site](https://developer.woocommerce.com/). I had to dig through closed issues to find it myself.
