### ISSUE TITLE
get_woocommerce_currency_symbol() is undefined AFTER update from 5.8 to 5.9

### ISSUE THREAD

**Issue by alisamie97** [woothemes/woocommerce#31115]
Just did auto update to 5.9 and got stuck in admin panel error
Set WP_DEBUG to true
Got this error: get_woocommerce_currency_symbol() is undefined 
changed to get_woocommerce_currency() and worked
changed to get_option('woocommerce_currency') and workd
changed back to get_woocommerce_currency_symbol() and no errors
it was wierd
NO PROBLEMS NOW

**Comment by juliaamosova** [comment]
Hi @stifler97,

Thank you for reporting the issue. It appears that it was resolved, however, according to your explanation. We haven't received any other reports similar to it. With this in mind, I am going to close this issue. However, please feel free to comment further in case you think we missed something.
