### ISSUE TITLE
set_price() method not working inside woocommerce_before_calculate_totals hook

### ISSUE THREAD

**Issue by katsar0v** [woothemes/woocommerce#31111]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
The issue might be similar to https://github.com/woocommerce/woocommerce/issues/21649 which is basically unresolved.

**Describe the bug**
I am trying to add a product in the cart and set a different price than the one saved in the database. Let's say I have a product which costs $100, I want to add it in the cart with the price of $200. For the following purpose I have this code:
```
add_action('woocommerce_before_calculate_totals', function( $cart ) {
    foreach ( $cart->get_cart() as $cart_item ) {
        $cart_item['data']->set_price( 200 );
    }
});
```

**Expected behavior**
I expect the price of each item in the cart to be $200.

**Actual behavior**
Nothing happens

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Sandbox install wordpress
2. Create an item which is $100
3. Use the code as code snippet, for example with the code snippet plugin
4. Add a sample product in the cart.

**Comment by katsar0v** [comment]
It was my mistake as the hook was not called directly in functions.php

**Comment by adamkentdev** [comment]
https://github.com/woocommerce/woocommerce/issues/21649#issuecomment-3649458442
