### ISSUE TITLE
Changelogger Automation

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#31135]
Adopt [the Jetpack Changelogger ](https://packagist.org/packages/automattic/jetpack-changelogger).

- [x] Add Jetpack Changelogger to all projects https://github.com/woocommerce/woocommerce/pull/31136
- [x] Add Jetpack Changelogger NX scripts https://github.com/woocommerce/woocommerce/pull/31166
- [x] Add Validation to check for changelogger entry in Github Action
- [x] Append PR number to changelog entry in Github Action https://github.com/woocommerce/woocommerce/pull/31348
- [x] Create a process to append the latest changelog entries to readme.txt for all plugins [so wordpress.org can display changes](https://github.com/woocommerce/woocommerce-admin/issues/7993)
- [x] Move processes from previous changelog scripts to Jetpack Changelogger
- [x] Update PR template and update instructions

**Comment by psealock** [comment]
I re-worked the original comment to include several steps before we can get to automation. The result is more of an epic than issue.

**Comment by jonathansadowski** [comment]
Sorry for not updating this last week before heading out for the long weekend, but I started diving into the GH action for validating the changelogger entry. I'll post an update again at the end of the day.
