### ISSUE TITLE
Clean Up E2E Infrastructure

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#31134]
While working on creating this monorepo, we've discovered some idiosyncrasies with our E2E testing infrastructure when used in GitHub Actions. One notable thing that seemed strange was the difference between the text execution context and the plugin used in the E2E environment itself. The way we're building the plugin has led to some interesting workarounds, and it feels like we could get away with centralizing some of this to decrease the amount of time it takes before the tests get to execute (~5 minutes). 

We have the ability to use Nx commands to simplify the execution of different project functionality now, so maybe it also makes sense to have an `nx e2e` executor that can run E2E tests on any project that has them. I'm not 100% sure what this task may entail entirely, but we should take a look at whatever we might be able to do here.

cc @woocommerce/solaris as you own this infrastructure!

**Comment by rrennick** [comment]
> One notable thing that seemed strange was the difference between the text execution context and the plugin used in the E2E environment itself.

> cc @woocommerce/solaris as you own this infrastructure!

We started the E2E tooling project with the E2E tooling that was already in place in this repo. We created the E2E packages to enable other projects to implement E2E without having to manually port our tooling to their projects. For example, [docker-compose.js](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-environment/bin/docker-compose.js) replaced a single `docker-compose` command and provides flexibility to support a variety of projects. This is one source of complexity in the environment package.

The second source of complexity is that the location of the package folder relative to the project is different in this repository than it is when installed in another project through `npm`. When I was helping out in p1634873226019400-slack-C0E1AV8T0, I had to delete my clone and pull down a fresh one to switch away from that PR branch. I asked that we merge the PR as soon as it was working in this repo. Changes in this repo do not affect package users. 

Once your team is finished with the migration and tooling work our team will correct any issues created in #30977 and follow up PRs. To simplify thing for your team and avoid additional changes that might adversely affect package users I have created a [branch that creates an environment variable](https://github.com/woocommerce/woocommerce/compare/add/e2e-environment-dev-flag?expand=1) `WC_E2E_WOOCOMMERCE_DEV` that will be `true` in this repo.

Please use the commit & environment variable in that branch to restrict your follow up work to only affect this repository. Also, it would be great if you could let Solaris know when you have completed the restructure work.

**Comment by ObliviousHarmony** [comment]
Thanks for the clarification @rrennick! The restructuring work is starting to settle now that we've integrated PNPM and Nx fully. We've also updated as many of the GitHub Actions as possible to use Nx, so I think next Monday we can say that we've completed enough of the migration that others can start adjusting their work to suit. Please let us know if you need any help sorting through anything, or guidance in how best to do something with this new infrastructure.

**Comment by rrennick** [comment]
> Please let us know if you need any help sorting through anything, or guidance in how best to do something with this new infrastructure.

@ObliviousHarmony Thanks. I had time this week to do a couple of cleanup PRs to address issues related to the file reorg:
- https://github.com/woocommerce/woocommerce/pull/31233
- https://github.com/woocommerce/woocommerce/pull/31232

With those, I think Solaris should be straightened away for the initial reorg.

**Comment by ObliviousHarmony** [comment]
Thanks for taking care of that @rrennick!
