### ISSUE TITLE
Isolate Legacy Asset Builds

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#31132]
[With Nx now in place](https://github.com/woocommerce/woocommerce/issues/31131), we should most of the `grunt` tasks that contribute to the length of time it takes to build the WooCommerce plugin locally. Since we can rely on Nx for incremental builds, a private package will enable us to only have to build these assets when they have actually changed.

- [ ] As per the accepted Monorepo structure, most of the JS and CSS in `plugins/woocommerce/assets` should be moved to `plugins/woocommerce/legacy` in `js` and `css` sub-folders. For both the JS and CSS, there's a precedent growing towards adding them both in React code, so these make sense as "legacy" assets, looking towards the future build of Blocks.
- [ ] This should be a private package, and it should be an `implicitDependency` for the Core plugin. We shouldn't make it a _real_ dependency, since this isn't a real NPM package that we will be shipping.
- [ ] Consider removing Grunt for direct Webpack execution, but it isn't a necessary step.
- [ ] All of the content should build into `plugins/woocommerce/assets`, and make sure we use `.gitignore` to avoid having the build artefacts in the repo.

**Comment by psealock** [comment]
Prior art https://github.com/woocommerce/woocommerce-monorepo/pull/13
