### ISSUE TITLE
`get_percent_complete` method in `WC_CSV_Batch_Exporter` giving float value but expecting int value

### ISSUE THREAD

**Issue by SadikurSadik** [woothemes/woocommerce#31137]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The `get_percent_complete` method in `WC_CSV_Batch_Exporter` giving `float` value but expecting `integer` value in `write_csv_data` method of same Class.

**Expected behavior**
`get_percent_complete` method should return `integer` value.

**Actual behavior**
`get_percent_complete` method giving `float` value. If we see the code `floor( ( $this->get_total_exported() / $this->total_rows ) * 100 )`. Here `floor` function can give `int` or `float` value. But there is no `int` casting.

**Steps to reproduce the bug**
To reproduce, You have to create one class by extending `WC_CSV_Batch_Exporter`. For example i added `OrderExporter` class
````
<?php

namespace Your/Namespace;

/**
 * Include dependencies.
 */
if ( ! class_exists( 'WC_CSV_Batch_Exporter', false ) ) {
    include_once WC_ABSPATH . 'includes/export/abstract-wc-csv-batch-exporter.php';
}

class OrderExporter extends \WC_CSV_Batch_Exporter {
    protected $filename = 'order-export.csv';

    public function get_column_names() {
        return $this->column_names;
    }

    public function set_items( $items = [] ) {
        $this->items = $items;
    }

    public function set_total_rows( $total_rows ) {
        $this->total_rows = absint( $total_rows );
    }

    public function prepare_data_to_export() {
        // TODO: Implement prepare_data_to_export() method.
    }
}
````
Now following code will reproduce the issue
````
include_once DIR_To . '/OrderExporter.php';
$exporter = new OrderExporter();
$exporter->set_page( 1 );
$exporter->set_total_rows(2);
var_dump($exporter->get_percent_complete());
die();
````

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
PHP Version: **7.4**
Wordpress Version: **5.8**
WooCommerce Version: **5.9.0**

**Comment by juliaamosova** [comment]
Hi @SadikurSadik,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by SadikurSadik** [comment]
Hi @juliaamosova,

Any update regarding this issue?

**Comment by barryhughes** [comment]
Confirming as a bug—looks like it can be resolved with a cast.
