### ISSUE TITLE
API-T Follow-up task: Extend the expect() function to show the request and the response

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#31143]
There are a few improvements that I suggested in pcr5Cj-1zj-p2#comment-1719 that would be nice to implement right after completing the automated tests for WC Core REST API critical flows.

One of which is: Extend the `expect` function to show the request and the response

**Comment by juliaamosova** [comment]
Thanks for opening the issue @rodelgc! It will be great to split it into 2 separate issues in order to be able to submit 2 separate PRs each closing specific issue as opposed to mixing 2 issues in 1 PR.

**Comment by rodelgc** [comment]
Thanks @juliaamosova I'll split them into 2 now.

**Comment by rodelgc** [comment]
Unassigning a sprint for this task, since I think it would be good to work on this once we've started adding annotations to our allure reports.

**Comment by rodelgc** [comment]
Good to close, since this task is aimed towards the SuperTest version of the API tests.
