### ISSUE TITLE
Deprecated: WC_Cart->tax_display_cart was called with an argument that is deprecated since version 4.4

### ISSUE THREAD

**Issue by Josh-Millard** [woothemes/woocommerce#31142]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Deprecated: WC_Cart->tax_display_cart was called with an argument that is deprecated since version 4.4! Use WC_Cart->get_tax_price_display_mode() instead. in /home/aesthayrsh/public_html/wp-includes/functions.php on line 5495

**Comment by juliaamosova** [comment]
Hi @Josh-Millard,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @Josh-Millard,

It looks like you deleted most of the bug report template, and there is unfortunately not enough information in what remains to properly assess things.

The deprecation notice you quoted would occur if another plugin or your theme tries to access the `tax_display_cart` property, but I don't believe there is a path in which WooCommerce (assuming you are using a recent version) would trigger this by itself.

What other plugins are you using (and what is your theme)? Can you replicate this on a clean test site that uses *only* WooCommerce plus a default theme such as Storefront? Are there any steps we would need to follow to see the problem (do we need to go to a specific page or admin screen, etc)?

Thanks!
