### ISSUE TITLE
States for Bolivia

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#31150]
**Is your feature request related to a problem? Please describe.**
The out of the box experience of woocommerce for the bigger countries is waaay different from the ones in the development world.
We need on latinamerican countries to have a better out of the box experience. And the only i humbly help is giving by default states for shipping.

As i described on https://github.com/woocommerce/woocommerce/issues/30375

**Describe the solution you'd like**
Add the different shipping states for the country, and change the 'state' label for the one corresponding to this country.
This country uses [Departamento](https://es.wikipedia.org/wiki/Departamentos_de_Bolivia) as 'State'.

**Describe alternatives you've considered**
I am chilean, but i can bet that on our sibling countries, they have the same problem. A lot of custom plugins that gives the geographical divisions for the country.

**Additional context**
I've talked to different friends around the continent to get a better idea, but because every country have different ways to set shipping costs around, this is a mild solution.
Like chile, we use Comunas (cities) rather than Regiones (states) for shipping. And how @masteradhoc pointed out, woo cannot have cities for calculating shipping costs. That will be the ultimate solution for everyone.

But at least, this will help latinamerican users to have a better platform experience with Woo, which i love <3.

**Comment by TheRadicalDreamer** [comment]
Bolivia is ok.

Just check that the name is Departamento and not State please :)

**Comment by masteradhoc** [comment]
@avagp please check pr and let me know if anything needs to be changed.

**Comment by juliaamosova** [comment]
Hi @avagp,

Thank you for submitting the issue. Since there is already a PR open by @masteradhoc, I will leave it to the PR reviewer to revive the change proposed further. 

Noting that in WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 40 (released 18 days ago) showing current country/state names can be seen below:

https://github.com/unicode-org/cldr/blob/release-40/common/subdivisions/en.xml

Any proposed changes need to match the data available via UNICODE CLDR.

**Comment by kkmuffme** [comment]
It should still be "State" not Departemento (which would be the localized name). We don't use the "native" name for all other languages/countries either.

**Comment by TheRadicalDreamer** [comment]
@kkmuffme i get it, but @masteradhoc changed the localization of the actual variable?

**Comment by kkmuffme** [comment]
>'label' => __( 'Departamento', 'woocommerce' ),

should be

>'label' => __( 'State', 'woocommerce' ),

**Comment by TheRadicalDreamer** [comment]
So, @masteradhoc had to change the translation?

But, for example. I have my site on Spanish (spain) language, because most of the plugins only have that spanish translated (not all the 32 other spanish).

So, it will say estado? or departamento, for example for my country Chile?

**Comment by kkmuffme** [comment]
Yes @masteradhoc has to change it.

If you use es_es translation it will whatever they use in Spain (I guess "estado")

If you want to use Chile locale, you just need to provide the translation for "State" in Chilean Spanish (= "Departamento") for WooCommerce.

**Comment by TheRadicalDreamer** [comment]
But that is not a solution :/

Unless there is a string for state for every country. (I don't if there is)

Imagine if woo was created in Argentina, and everything is named
'Provincia', then California and New York will be 'provincias'. That would
be so weird.

That is the same appreciation we have when we have 'departamentos', but are
called 'estados'.

If there is no string for each country, wouldn't be good to have something
like it? So we can give a simple and proper solution to every country?

**Comment by masteradhoc** [comment]
Thats exactly the reason why the labels are set in the PR to the country. As a big language like yours combines a lot countries. This wont hurt anybody and just show "Departamentos" when country is choosen to Bolivia. if the US is choosen then it goes back to state.

i think and believe its the proper way. Handling everything over translations would make this lable feature useless.

**Comment by kkmuffme** [comment]
@masteradhoc you need to use the English name. In this case the state field should be "Department" (instead of "Departamento") see https://en.wikipedia.org/wiki/Departments_of_Bolivia

The translation to "Departamento" will happen via the regular translation process and will be available to you then normally (so your site will show Departamento, even though you set the English string Department in the code)

**Comment by masteradhoc** [comment]
@kkmuffme true that. change it now on all PRs.
