### ISSUE TITLE
States for Salvador

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#31163]
**Is your feature request related to a problem? Please describe.**
The out of the box experience of woocommerce for the bigger countries is waaay different from the ones in the development world.
We need on latinamerican countries to have a better out of the box experience. And the only i humbly help is giving by default states for shipping.

As i described on https://github.com/woocommerce/woocommerce/issues/30375

**Describe the solution you'd like**
Add the different shipping states for the country, and change the 'state' label for the one corresponding to this country.
This country uses [Departamento](https://es.wikipedia.org/wiki/Organizaci%C3%B3n_territorial_de_El_Salvador) as 'State'

**Describe alternatives you've considered**
I am chilean, but i can bet that on our sibling countries, they have the same problem. A lot of custom plugins that gives the geographical divisions for the country.

**Additional context**
I've talked to different friends around the continent to get a better idea, but because every country have different ways to set shipping costs around, this is a mild solution.
Like chile, we use Comunas (cities) rather than Regiones (states) for shipping. And how @masteradhoc pointed out, woo cannot have cities for calculating shipping costs. That will be the ultimate solution for everyone.

But at least, this will help latinamerican users to have a better platform experience with Woo, which i love <3.

**Comment by masteradhoc** [comment]
@avagp please check the pull request with the changes requested. Let me know inside the PR or here if all is fine and as needed.

**Comment by juliaamosova** [comment]
Hi @avagp,

Thank you for submitting the issue. Since there is already a PR open by @masteradhoc, I will leave it to the PR reviewer to revive the change proposed further. 

Noting that in WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 40 (released 18 days ago) showing current country/state names can be seen below:

https://github.com/unicode-org/cldr/blob/release-40/common/subdivisions/en.xml

Any proposed changes need to match the data available via UNICODE CLDR.

**Comment by TheRadicalDreamer** [comment]
@masteradhoc , as stated by @juliaamosova , the states should match to cldr.

And the ones you wrote are incorrect:
![image](https://user-images.githubusercontent.com/11801254/141837915-700375e1-cb73-4920-91f1-2998d2d43ffe.png)


Here are the ones:
![image](https://user-images.githubusercontent.com/11801254/141837897-04fc60c3-c1be-4fb7-b121-b86224aff022.png)

**Comment by masteradhoc** [comment]
Soory my fault. done now
