### ISSUE TITLE
States for Venezuela

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#31165]
**Is your feature request related to a problem? Please describe.**
The out of the box experience of woocommerce for the bigger countries is waaay different from the ones in the development world.
We need on latinamerican countries to have a better out of the box experience. And the only i humbly help is giving by default states for shipping.

As i described on https://github.com/woocommerce/woocommerce/issues/30375

**Describe the solution you'd like**
Add the different shipping states for the country, and change the 'state' label for the one corresponding to this country.
This country uses [Estado](https://es.wikipedia.org/wiki/Anexo:Entidades_federales_de_Venezuela) as 'State'

**Describe alternatives you've considered**
I am chilean, but i can bet that on our sibling countries, they have the same problem. A lot of custom plugins that gives the geographical divisions for the country.

**Additional context**
I've talked to different friends around the continent to get a better idea, but because every country have different ways to set shipping costs around, this is a mild solution.
Like chile, we use Comunas (cities) rather than Regiones (states) for shipping. And how @masteradhoc pointed out, woo cannot have cities for calculating shipping costs. That will be the ultimate solution for everyone.

But at least, this will help latinamerican users to have a better platform experience with Woo, which i love <3.

**Comment by masteradhoc** [comment]
@avagp the states for Venezuela are already inside woocommce. Check: https://github.com/masteradhoc/woocommerce/blob/trunk/plugins/woocommerce/i18n/states.php#L1839

if they are fine please close the open issue again.

**Comment by TheRadicalDreamer** [comment]
They are all there.

But one changed the name on 2019: 'Vargas' State

Here, take a look:
https://en.wikipedia.org/wiki/Vargas_(state)

Now it is called 'La Guaira' state

So that should be the only modification.

Thanks for pointing it out @masteradhoc

**Comment by TheRadicalDreamer** [comment]
And aldo, i don't get why they are related to a letter
![image](https://user-images.githubusercontent.com/11801254/141504794-0e6dae95-a36e-4f50-9c67-40e7b67427ba.png)

I will check with a venezuela's friend i have.

**Comment by masteradhoc** [comment]
@avagp please check the pull request with the changes requested. Let me know inside the PR or here if all is fine and as needed.

**Comment by juliaamosova** [comment]
Hi @avagp,

Thank you for submitting the issue. In WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 40 (released 18 days ago) still shows the state as Vargas:

https://github.com/unicode-org/cldr/blob/release-40/common/subdivisions/en.xml#L5644

I am not sure we will be able to rename it. I'll leave it up to the PR reviewer further.

**Comment by TheRadicalDreamer** [comment]
@juliaamosova to make that change, i cannot just ask it. I need to do a pull request. Which I don't know how to do it.

It will be good to have it changed on Unicode cldr as well.

**Comment by TheRadicalDreamer** [comment]
@masteradhoc i checked, and there are all right.

The way you handled la guaira is great.

**Comment by TheRadicalDreamer** [comment]
@juliaamosova the pull request is like this:
![image](https://user-images.githubusercontent.com/11801254/141838162-f828e67b-1186-42ed-8027-c750e0434cf9.png)


And the cldr is like this:
![image](https://user-images.githubusercontent.com/11801254/141838189-493ad01e-0ab7-40b1-a5d7-77443499022e.png)


It is ok?
