### ISSUE TITLE
Fix the symbol for SZL currency (patch included)

### ISSUE THREAD

**Issue by sicelo** [woothemes/woocommerce#31182]
**Is your feature request related to a problem? Please describe.**
Yes, WC uses the symbol 'L' for SZL. However this is confusing for Eswatini users (and looks weird). "L" can also be potentially mistaken for the Lesotho Loti.

**Describe the solution you'd like**
Use of the correct and natural symbol that SZL users are familiar with. MR #30602 is a proposed solution.

**Describe alternatives you've considered**
Working around it as described in #25398 . However, this is not a good solution in the long-term, since L vs. E is not a matter of personal taste (see quotation from official Central Bank website included in #30602 ).

**Comment by juliaamosova** [comment]
Related to https://github.com/woocommerce/woocommerce/issues/31184.

**Comment by sicelo** [comment]
Seems CLDR has, for some time already, used "E" for SZL.
Using the version 40 survey tool, https://st.unicode.org/cldr-apps/v#/ss_SZ/C_SAfrica/56ac78f7e192bb1

**Comment by barryhughes** [comment]
Apologies for the delay: this is now [merged](https://github.com/woocommerce/woocommerce/pull/30602). It should be available from 6.4.0 onwards.
