### ISSUE TITLE
Rename Swaziland to Eswatini

### ISSUE THREAD

**Issue by sicelo** [woothemes/woocommerce#31184]
**Is your feature request related to a problem? Please describe.**
The country of Swaziland was renamed to Eswatini back in April 2018. A number of projects and operating systems have reflected this change.

**Describe the solution you'd like**
A simple rename in WC code :-) see #31185

**Describe alternatives you've considered**
None. The name adjustment is official/legal.

**Additional context**
Some links:
https://www.bbc.com/news/world-africa-43821512
[Official government website](https://gov.sz)

**Comment by juliaamosova** [comment]
Hi @sicelo,

Thank you for submitting the issue. In WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 40 (released 18 days ago) still shows the country as Swaziland:

https://github.com/unicode-org/cldr/blob/release-40/common/subdivisions/en.xml#L4996

I am not sure we will be able to rename it. I'll leave it up to the PR reviewer further.

**Comment by sicelo** [comment]
Alright. Now need to find out how the CLDR gets updated. Hints will be appreciated.

**Comment by sicelo** [comment]
Hmm, looks like Eswatini is also accepted there as the primary country name, with Swaziland remaining as an alternate.
see also the thread https://unicode-org.atlassian.net/browse/CLDR-11083 : "TC: Decided to go with "Eswatini" as main, use old name as alt value."

Going through the version 40 survey tool, it is also referred to as Eswatini, https://st.unicode.org/cldr-apps/v#/ss_SZ/T_Africa/6e49aa3c9aa50dc9

Please let me know if further action needs to be taken to update the CLDR

**Comment by barryhughes** [comment]
CLDR isn't something we control, though we try to adhere to it, but if I'm interpreting things correctly this change will be reflected in release 41 (they seem to follow a 6-month cadence, so I'd assume we'll see this change in April 2022).

**Comment by barryhughes** [comment]
Removed the dev feedback label: this sounds like a good change, though I think we should wait until CLDR 41 rolls out and confirm things then. Please do let us know if you strongly disagree.
