### ISSUE TITLE
Add logging for database operations

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#31200]
The first step in fixing #29027: let people know if insert/update fails. We might introduce exceptions at a later stage, but let's first start with logging failed updates. 

This task is done if all write database operations return values are checked and all the errors are logged into the WooCommerce error log.

**Comment by jeffstieler** [comment]
We should probably exclude inserts/updates using the WP metadata functions for this issue since there isn't enough information to know if a falsy return is due to an error or no update needing to be performed (unchanged value).

**Comment by peterfabian** [comment]
That's perhaps a bit unfortunate wrt to issues like these (p74xnj-wu-p2) where the erroneous meta data for orders cause strange side effects, but I'm hoping we'll be able to solve this when we migrate to custom tables, so let's go with what is possible now without expending too much effort.

**Comment by jeffstieler** [comment]
After some consideration, I'm going to remove my assignment.

So long as a store hasn't chosen to suppress errors in `wpdb`, all query errors will be logged (using `error_log()`), so I'm not sure how much value additional logging will have.

**Comment by peterfabian** [comment]
I agree, we apparently have forgotten about that. The db errors are written using `error_log` unless someone intentionally calls `$wpdb->suppress_errors()` or sets `$wpdb->suppress_errors` to truthy value. I think we can close this task, since the actual handling of the errors in WC code is out of scope for this issue.
