### ISSUE TITLE
WP CLI db update bug?

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#31214]
It seems like [this part of the code](https://github.com/woocommerce/woocommerce/blame/trunk/plugins/woocommerce/includes/cli/class-wc-cli-update-command.php#L64-L72) either uses some magic, or won't run as expected. The while loop probably never runs and result from the callback is ignored. We should check if this actually works.

**Comment by jaredyork** [comment]
Does the DB version even get updated after the callbacks are ran?  I don't see WC_Install::update_db_version(); get called prior to the success message.

**Comment by barryhughes** [comment]
I've logged the second issue (thanks for flagging, @jaredyork) separately ... though we should address both problems.

See: #33262
