### ISSUE TITLE
WC_Order::needs_processing - possible bug

### ISSUE THREAD

**Issue by erikkubica** [woothemes/woocommerce#31220]
Hello,

Today I have noticed that needs processing is broken. Our client sells virtual product that is not downloadable and after payment is done, it does not change the order status to completed. 

I have backtracked everything and found out that in order to achieve completed order status after payment, the product must be both downloadable and virtual. When I changed the product to downloadable + virtual it started working correctly. So I strongly believe its not intended like this, therefore it's a possible bug from my perspective.

https://github.com/woocommerce/woocommerce/blob/98b63e027fae51e7b61d856f79dfd186b8cb4c43/plugins/woocommerce/includes/class-wc-order.php#L1553

This line should have and OR operator instead of an AND operator.

**Comment by DavidAnderson684** [comment]
Note that your shop is behaving as the documentation describes it should given your settings - https://woocommerce.com/document/digital-downloadable-product-handling/#usage .

**Comment by erikkubica** [comment]
> Note that your shop is behaving as the documentation describes it should given your settings - https://woocommerce.com/document/digital-downloadable-product-handling/#usage .

Thank you @DavidAnderson684 , I guess it's my bad then, because somewhere I red that processing status is skipped if order consists of only downloadable **or** virtual products, which I have automatically assumed that it means that product does not have to have both checkboxes checked.
