### ISSUE TITLE
Add New Action Hook Before Displaying Review Comments

### ISSUE THREAD

**Issue by sameer-rajpoot** [woothemes/woocommerce#31231]
**Add Hook Before Review Comments List**
Please add a new action hook before displaying review comments in the Woocommerce plugin. Even a new action hook should be included after display review comments to facilitate developers for customizing and developing new plugins. Although template file can be overridden in the plugin but a good approach is to customize and extend the plugin functionality via WordPress action hooks and filters.

--Add action hook here--
```
<h2 class="woocommerce-Reviews-title">
<?php
	$count = $product->get_review_count();
	if ( $count && wc_review_ratings_enabled() ) {
		/* translators: 1: reviews count 2: product name */
		$reviews_title = sprintf( esc_html( _n( '%1$s review for %2$s', '%1$s reviews for %2$s', $count, 'woocommerce' ) ), esc_html( $count ), '<span>' . get_the_title() . '</span>' );
		echo apply_filters( 'woocommerce_reviews_title', $reviews_title, $count, $product ); // WPCS: XSS ok.
	} else {
		esc_html_e( 'Reviews', 'woocommerce' );
	}
?>
</h2>

```

**Comment by tammullen** [comment]
Hi @sameer-rajpoot ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
