### ISSUE TITLE
Fix flaky unit tests

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#31249]
21 out of the last 25 PRs have failed tests. 10 instances of unit tests failing is too much and it prevents us from using these tests effectively. Investigate and fix or disable flaky tests so that we can rely on the unit tests again.

Thanks for the stats, @barryhughes !

```
PR#     Build zip   E2E Fails   Unit Fails
⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼
31237                   x
31228       x           -
31225                   x
31224       x           -
31218 ✓
31212                               x
31207                   x
31205 ✓
31196                   x           x
31169                   x
31149                   x
31148                               x
31147                   x
31136       x           x
31130       x           -
31129                               x
31127                               x
31125                   x
31122                               x
31121                               x
31117                               x
31114                               x
31104                               x
31103 ✓
31102 ✓
```

**Comment by barryhughes** [comment]
Flagging as flaky:

`WC_Tests_REST_System_Status::test_get_system_status_info_environment_filtered_by_field()`

**Comment by barryhughes** [comment]
Also hitting this quite often, in relation to various API tests:

`connect ECONNREFUSED 127.0.0.1:80`

Example:

```
Refunds API tests › can list all refunds

connect ECONNREFUSED 127.0.0.1:80
```

**Comment by jeffstieler** [comment]
I see the `ECONNREFUSED` error on all PRs from forks - it's an issue with GH secret accessibility that's being actively worked on by Solaris.

**Comment by barryhughes** [comment]
It's been a while since this issue was last updated but, especially with E2E tests, we still hit occasional roadbumps.

In [this PR](https://github.com/woocommerce/woocommerce/pull/37713), the only modifcation is to a markdown file but E2E tests failed twice. I then re-based, and they failed again. I triggered another re-run, and they passed 🎉 

E2E tests take a long time to run, though, so when this occurs it can be a little frustrating/it's a little distracting having to cycle back periodically to trigger re-runs, etc.

**Comment by tammullen** [comment]
@barryhughes that particular flaky test is being worked on here https://github.com/woocommerce/woocommerce/issues/37724

**Comment by barryhughes** [comment]
Nice. That may also cover some of the flakiness seen via https://github.com/woocommerce/woocommerce/pull/37676 (though not entirely—some of the fails which I'm pretty confident are unrelated to the change are surfacing in relation to tests for payment setup tasks, analytics page, and others).

**Comment by rrennick** [comment]
@barryhughes Closing this one.

**Comment by barryhughes** [comment]
No worries, thanks Ron. Unit tests (which I think were the focus of this issue) are definitely far more stable now, and the remaining problems tend to be with E2E tests [(very recent example here)](https://github.com/woocommerce/woocommerce/pull/31787#issuecomment-1823748125), which continue to add friction and delay to the review/merge flow ... but that can be addressed elsewhere, of course.
