### ISSUE TITLE
Deprecated jQuery code in minified version of paypal-admin.js

### ISSUE THREAD

**Issue by pacmanito** [woothemes/woocommerce#31244]
Hi, while checking for deprecated jQuery I found a notice coming from WooCommerce. I was rather surprised cause all old code was cleaned some time ago - https://github.com/woocommerce/woocommerce/issues/28286.

Here's the notice:
**jQuery.fn.change() event shorthand is deprecated** in woocommerce/includes/gateways/paypal/assets/js/paypal-admin.min.js

Upon checking the js file I found that the code is fixed in non-minified version of file but in minified one there is still deprecated code. Namely:

`$( '#woocommerce_paypal_testmode' ).trigger( 'change' );` in paypal-admin.js

and

`$('#woocommerce_paypal_testmode').change()` in paypal-admin.min.js

So it seems you forgot to update the minified version of paypal-admin.js.

**Comment by tammullen** [comment]
Hi @pacmanito ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by pacmanito** [comment]
Hey, maybe someone is gonna check this?

**Comment by pacmanito** [comment]
Two months has passed and still no attention.

**Comment by barryhughes** [comment]
Does indeed look like an oversight. My guess is when [this work was done](https://github.com/woocommerce/woocommerce/commit/387e095a01284401484f1810447aa38cf246ab2c) it was assumed our build script would take care of minification, but presumably this asset was not in one of the covered paths.
