### ISSUE TITLE
downloads array for API endpoint /wc/v3/products is not parsing all files

### ISSUE THREAD

**Issue by Mikestr0** [woothemes/woocommerce#31248]
It appears as though the following endpoint "/wc/v3/products" is not functioning correctly. The downloads parameter is an array which should allow you to submit multiple downloadable files but it only appears to be accepting a single file.

**REQUEST DETAILS**

Date: 2021-11-18 15:20:27
Source: WP REST API
Method: POST
Status: 201
Elapsed Time: 2,486ms
Response Length: 3,455
User: user
IP Address: redacted

**REQUEST HEADERS**

{
    "connection": "close",
    "host": "www.redacted.co.uk",
    "content_length": "666",
    "user_agent": "WooCommerce REST API - JS Client\/1.0.1",
    "content_type": "application\/json;charset=utf-8",
    "accept": "application\/json",
    "authorization": "Basic Y2tfMjZkYTVlYzkwZGFiZTUxODUxYzM5NlZmNkMGJlZDc1ODYwMjVhODpjc183YTAwZmY1MDEwZmU0N2U5MmU0MDM3MTMzYmExYmQ5MWQzYmIxZjNk"
}

**REQUEST BODY CONTENT**

{"name":"Digital Download A4","slug":"61966f3829d4c90468b96c50","regular_price":"19.99","virtual":true,"downloadable":true,"downloads":[{"id":"fd10b300e2caf8c31f26e0b7376e6dc0","name":"Digital Download - (PDF - Best Quality)","file":"https://dev.redacted.co.uk/pdf/16f37ff4a53290ace2715624b8841916.pdf"},{"id":"fd10b300e2caf8c31f26e0b7376e6dc0","name":"Digital Download - (PNG - Standard Quality)","file":"https://dev.redacted.co.uk/image/021769d8d9ccda625f14b43bd0ba6c41.png"}],"reviews_allowed":false,"catalog_visibility":"hidden","purchase_note":"This is a purchase note","images":[{"src":"https://dev.redacted.co.uk/image/9edf3025aa4364c427faf7a05417f9dd.png"}]}

(Note there are two downloads specified here in the syntax and formatting are correct)

**RESPONSE HEADERS**

{
    "X-Powered-By": "PHP\/7.4.24",
    "Content-Type": "application\/json; charset=UTF-8",
    "X-Robots-Tag": "noindex",
    "Link": "<https\/\/www.redcated.co.uk\/wp-json\/>; rel="https\/\/api.w.org\/"",
    "X-Content-Type-Options": "nosniff",
    "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages, Link",
    "Access-Control-Allow-Headers": "Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type",
    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "X-WP-CF-Super-Cache-Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "X-WP-CF-Super-Cache": "no-cache",
    "Pragma": "no-cache",
    "Expires": "Thu, 18 Nov 2021 152025 GMT",
    "Location": "https\/\/www.redacted.co.uk\/wp-json\/wc\/v3\/products\/242140",
    "Allow": "GET, POST"
}

**RESPONSE BODY**

{
    "data": {
        "id": 242140,
        "name": "Digital Download A4",
        "slug": "61966f3829d4c90468b96c50",
        "permalink": "https://www.redacted.co.uk/shop/61966f3829d4c90468b96c50/",
        "date_created": "2021-11-18T15:20:25",
        "date_created_gmt": "2021-11-18T15:20:25",
        "date_modified": "2021-11-18T15:20:25",
        "date_modified_gmt": "2021-11-18T15:20:25",
        "type": "simple",
        "status": "publish",
        "featured": false,
        "catalog_visibility": "hidden",
        "description": "",
        "short_description": "",
        "sku": "",
        "price": "19.99",
        "regular_price": "19.99",
        "sale_price": "",
        "date_on_sale_from": null,
        "date_on_sale_from_gmt": null,
        "date_on_sale_to": null,
        "date_on_sale_to_gmt": null,
        "on_sale": false,
        "purchasable": true,
        "total_sales": 0,
        "virtual": true,
        "downloadable": true,
        "downloads": [
            **{
                "id": "fd10b300e2caf8c31f26e0b7376e6dc0",
                "name": "Digital Download - (PNG - Standard Quality)",
                "file": "https://dev.redacted.co.uk/image/021769d8d9ccda625f14b43bd0ba6c41.png"
            }**
        ],
        "download_limit": -1,
        "download_expiry": -1,
        "external_url": "",
        "button_text": "",
        "tax_status": "taxable",
        "tax_class": "",
        "manage_stock": false,
        "stock_quantity": null,
        "backorders": "no",
        "backorders_allowed": false,
        "backordered": false,
        "low_stock_amount": null,
        "sold_individually": false,
        "weight": "",
        "dimensions": {
            "length": "",
            "width": "",
            "height": ""
        },
        "shipping_required": false,
        "shipping_taxable": false,
        "shipping_class": "",
        "shipping_class_id": 0,
        "reviews_allowed": false,
        "average_rating": "0",
        "rating_count": 0,
        "upsell_ids": [],
        "cross_sell_ids": [],
        "parent_id": 0,
        "purchase_note": "This is a purchase note",
        "categories": [
            {
                "id": 15,
                "name": "Uncategorized",
                "slug": "uncategorized"
            }
        ],
        "tags": [],
        "images": [
            {
                "id": 242139,
                "date_created": "2021-11-18T15:20:25",
                "date_created_gmt": "2021-11-18T15:20:25",
                "date_modified": "2021-11-18T15:20:25",
                "date_modified_gmt": "2021-11-18T15:20:25",
                "src": "https://www.redacted.co.uk/wp-content/uploads/2021/11/9edf3025aa4364c427faf7a05417f9dd.jpg",
                "name": "9edf3025aa4364c427faf7a05417f9dd.jpg",
                "alt": ""
            }
        ],
        "attributes": [],
        "default_attributes": [],
        "variations": [],
        "grouped_products": [],
        "menu_order": 0,
        "price_html": "<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">£</span>19.99</bdi></span>",
        "related_ids": [
            241856,
            241860
        ],
        "meta_data": [],
        "stock_status": "instock"
    },
    "headers": {
        "Location": "https://www.redacted.co.uk/wp-json/wc/v3/products/242140",
        "Allow": "GET, POST"
    },
    "status": 201
}

(Please note how the response is 201 created but only one product download is actually created)

Can somebody please reproduce this issue and confirm it's a legitimate bug?

Thanks,

Mike

**Comment by Mikestr0** [comment]
I have confirmed that this issue appears to be intermittent. For every 10 requests I send to the server approximately one will succeed in creating both the files. I'm unable to reproduce the successful requests at will and they appear to be random as no change was made to the request or the server configuration.

**Comment by Mikestr0** [comment]
Resolved: We were manually defining the ID parameter which is unnecessary.  id: "", resolved the issue.

**Comment by tammullen** [comment]
Thanks @Mikestr0 for the update. I will close this issue for now as it appears to be resolved. Free feel to raise a new issue if needed.
