### ISSUE TITLE
$loop variable in woocommerce_variation_header hook

### ISSUE THREAD

**Issue by bravomediamats** [woothemes/woocommerce#31252]
**Is your feature request related to a problem? Please describe.**
This feature request added the possibility to add custom information to the Product Variation Header:
https://github.com/woocommerce/woocommerce/issues/21362

But with this hook, a developer can not add a new field, for example the ability to set SKU or other simple options that differs between products without having to toggle the products one at a time.
This is because we lack the $loop variable in this hook.

https://github.com/woocommerce/woocommerce/blob/388dc0290e74db2b7539512a3e38a77db0659d4a/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php#L53-L62

**Describe the solution you'd like**

If we add the $loop variable to this hook this can be achieved. The $loop variable is present in other hooks in this template, but not in the woocommerce_variation_header hook.

`do_action( 'woocommerce_variation_header', $variation, $loop );`

**Describe alternatives you've considered**
I've tried using post_id as separator for the form field, but the update function seems to look exclusively at the $loop int to update the post.

**Comment by tammullen** [comment]
Hi @bravomediamats ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @bravomediamats, that seems like a reasonable change to me (alternatively, I imagine that the callback could maintain its own counter—but this seems like a safe and clean change that would make things a bit easier). 

Are you happy to take a shot at submitting a PR for this? If not, we can leave for either one of the team or for another community contributor to tackle.

**Comment by johnregan3** [comment]
Since it's been a few days, I'm happy to take this one.

**Comment by bravomediamats** [comment]
Sorry for the late response, been busy.
Are you working on it @johnregan3 or shall I try to make a pull-request?

**Comment by johnregan3** [comment]
PR Issued #31565
