### ISSUE TITLE
Displayed units is not translated

### ISSUE THREAD

**Issue by poletaew** [woothemes/woocommerce#31263]
https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/wc-formatting-functions.php#L1296

Need to replace with:
```
$weight_string .= ' ' . __(get_option( 'woocommerce_weight_unit' ), 'woocommerce');
```

The same inside **wc_format_dimensions** function.

**Comment by masteradhoc** [comment]
@poletaew check PR please. #31281

**Comment by poletaew** [comment]
Thanks, awesome!

**Comment by rodelgc** [comment]
Hi @poletaew,

Thank you for raising this issue! And @masteradhoc thanks for submitting a PR for it. The Core team will be looking at this soon. Please note it may take them a few days to respond. I'm labelling this issue as an enhancement.

**Comment by rrennick** [comment]
> $weight_string .= ' ' . __(get_option( 'woocommerce_weight_unit' ), 'woocommerce');

@poletaew This does not work. The translation functions require string literals for the string to be included in the translation files. I'll close the issue as a question.
