### ISSUE TITLE
Use variant slug instead of variant name in exporting/importing products

### ISSUE THREAD

**Issue by RVandenbussche** [woothemes/woocommerce#31261]
Hi guys and girls,

There is a bug in the import/export function when you have two variant types with the same name. I have two products with different types of black, still they are both called black. Black on both products are a bit different, one has a bit of a pattern and to show this to the user I use image swatches (plugin). 

Everything goes well until I export and import the product with all it's variants. In the export it says under the colour column black and not the slug (eg. black_2). When I'm importing the product again it uses black with the slug black_1.

I think it would be better to use the slug name in variants instead of the name to identify the variant used.

**Comment by rodelgc** [comment]
Hi @RVandenbussche,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
