### ISSUE TITLE
Loop of /wp-admin/plugins.php unable to access anything in the admin area or active ot deactive plugins.

### ISSUE THREAD

**Issue by zeroanarchy01** [woothemes/woocommerce#31269]
**Describe the bug**
Deactivating Woocommerce produces the following error 
"To use "WooSquare WooCommerce Square Integration" WooCommerce Or MYCRED must be activated or installed!"

all links force the admin back to wp-admin/plugins.php however no list of plugins is available only a back button.

**Expected behavior**
An error message should appear only.
If the user is kicked back to the plugin page, a list of plugins should be available to activate or deactivate.

**Actual behavior**
Continuous refresh of the plugin page every 3 seconds providing the users with only a back button.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to plugins
2. Click on de active WooCommerce

Attached image of error message.
![Screenshot from 2021-11-22 10-55-31](https://user-images.githubusercontent.com/48507206/142784173-aa58d97c-74bf-4375-9c90-10a3b6f7ecbd.png)

**Comment by rodelgc** [comment]
Hi @zeroanarchy01,

Could you please provide us the system status report and a link to the "WooSquare WooCommerce Square Integration" plugin if possible? Deactivating WooCommerce while other extensions that depend on it like (WooCommerce Bookings in my test) does not cause the /wp-admin/plugins.php page to continuously reload. Therefore the issue you're experiencing could probably be specific to the plugin/theme set up that you have.
