### ISSUE TITLE
WooCommerce core and tests not compatible with PHP 8.1

### ISSUE THREAD

**Issue by thejamescollins** [woothemes/woocommerce#31270]
As far as I can tell, WooCommerce core isn't currently being tested against the upcoming PHP version 8.1, which is due to be released in 3 days time on 25 November.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Unit tests fail to run (with a PHP fatal error) when using PHP 8.1 (both WooCommerce trunk and 5.8.2).

**Expected behavior**
Ideally, WooCommerce (including all tests) would run and pass when running against PHP 8.1.

**Actual behavior**

PHPUnit exits with several warnings and a fatal error during tests bootstrap before any tests can be run:
```
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 176

Warning: Private methods cannot be final as they are never overridden by other classes in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 176
PHP Fatal error:  Cannot acquire reference to $GLOBALS in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 543

Fatal error: Cannot acquire reference to $GLOBALS in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 543
```

This means that currently no tests are run against PHP 8.1, making it impractical to know what actual plugin code changes are required to work successfully on PHP 8.1

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Check out latest trunk. cd to the `plugins/woocommerce` subdirectory
2. Using PHP 8.1, run `composer update --ignore-platform-reqs`
3. Run `vendor/bin/phpunit` and the above fatal error occurs.

**Screenshots**

N/A

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

```
php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 06:07:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
```

</details>

**Suggested Way Forward**

I believe the composer configand test suite will need to be updated [as outlined here](https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/), so that the test suite correctly uses newer PHPunit versions on PHP 8.1, while still using older PHPUnit versions. 

`yoast/phpunit-polyfills` likely needs to be updated to v1.0.1 as well.

The [CI config](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/ci.yml) should also ideally run against PHP 8.1.

Any PHP 8.1 related compatibility notices/warnings/errors should ideally be identified and resolved.

In our WooCommerce extension, we are running our own unit tests by using some of WooCommerce core's test structures, and so far I've been able to identify the following WooCommerce core deprecation warnings that will likely need to be resolved:

<details>
```
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Deprecated:  Return type of WC_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 57

Deprecated: Return type of WC_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 57
PHP Deprecated:  Return type of WC_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 47

Deprecated: Return type of WC_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 47
PHP Deprecated:  Return type of WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 68

Deprecated: Return type of WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 68
PHP Deprecated:  Return type of WC_Meta_Data::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-meta-data.php on line 50

Deprecated: Return type of WC_Meta_Data::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-meta-data.php on line 50

PHP Deprecated:  Return type of ActionScheduler_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 60

Deprecated: Return type of ActionScheduler_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 60
PHP Deprecated:  Return type of ActionScheduler_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 48

Deprecated: Return type of ActionScheduler_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 48
PHP Deprecated:  Return type of ActionScheduler_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 27

Deprecated: Return type of ActionScheduler_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 27

PHP Fatal error:  Declaration of WP_HTTP_TestCase::setUpBeforeClass() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUpBeforeClass(): void in /wp-content/plugins/woocommerce/plugins/woocommerce/tests/legacy/includes/wp-http-testcase.php on line 137

Fatal error: Declaration of WP_HTTP_TestCase::setUpBeforeClass() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUpBeforeClass(): void in /wp-content/plugins/woocommerce/plugins/woocommerce/tests/legacy/includes/wp-http-testcase.php on line 137
```
</details>

Avoiding those kinds of deprecation warnings involves either bumping the minimum required PHP version from 7.0 to 7.1, or alternatively adding the `#[\ReturnTypeWillChange]` attribute.

Changes to Action Scheduler also look to be necessary.

Thanks for your time!

**Comment by rodelgc** [comment]
Hi @om4james,

Thank you for raising this concern with us. The Core team is already looking into it. Please stay tuned for updates.

For reference: Internal discussion on PHP 8.1 support - p1637571539189300-slack-C0E1AV8T0

**Comment by thejamescollins** [comment]
Thank you for the update @rodelgc, I appreciate it :)

**Comment by thejamescollins** [comment]
Hi there @rodelgc ,

I'm wondering if you have an update on progress here?

I'm sure there are many WooCommerce extension developers that are relying on using WooCommerce's (now legacy) unit testing facility to test their plugins.

Our WooCommerce Zapier extension has 10,000+ active users, and we're currently unable to run our unit test suite on PHP 8.1 because WooCommerce core's test suite isn't compatible with 8.1.

I note a few PHP 8.1 related PR's (such as #31333) have been submitted but they are addressing WP core plugin deprecation issues, and not issues within the WooCommerce legacy unit test suite framework.

We currently get this error when running our test suite on PHP 8.1:

```
Fatal error: Declaration of WP_HTTP_TestCase::setUpBeforeClass() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUpBeforeClass(): void in plugins/woocommerce/tests/legacy/includes/wp-http-testcase.php on line 137
```

And there are quite a few other changes required in `WP_HTTP_TestCase`, `WC_Unit_Test_Case` and `WC_REST_Unit_Test_Case` as well.

I'm open to contributing the above fixes, however, I'm reluctant to do so without a clear idea of Automattic's plan for PHP 8.1 support.

Is it on the roadmap?

WordPress 5.9 is due out in a week, and it contains a lot of PHP 8.1 fixes. It would be *really* nice if WooCommerce 6.2 could include PHP 8.1 fixes also.

Thank you, I look forward to hearing from you.

**Comment by rodelgc** [comment]
Hi @om4james,

Apologies for the delayed response. Thanks for bringing these up. I'll labeling this with `needs developer feedback` so that our Core devs could take a deeper look.

**Comment by peterfabian** [comment]
Hi @om4james . Thanks for raising those issues. As you can see from the PRs (https://github.com/woocommerce/woocommerce/pull/31286, https://github.com/woocommerce/woocommerce/pull/31333 and the [extra commit on our PHPUnit patch](https://github.com/woocommerce/phpunit/pull/1/commits/555282e03f826a5f6c58be2ff2b02ae107e455dd)) we have been working on making WC compatible with PHP 8.1, although it stalled a bit because we were waiting on WordPress core to address some PHP 8.1 issues. 

cc @Konamiman in case this can move forward, or if you can give any guidance what's missing so that @om4james can potentially help us with his PRs. Thx.
