### ISSUE TITLE
Password change security issue

### ISSUE THREAD

**Issue by WhoopDav** [woothemes/woocommerce#31297]
Hello. Can I report a security issue here?

**Comment by tammullen** [comment]
Hi @WhoopDav 
Please report all security issues only via https://www.hackerone.com 

Also please see [the security policy here.](https://github.com/woocommerce/woocommerce/security/policy)

**Comment by WhoopDav** [comment]
Yes I went there but can you tell me where I click on that website to
notify them? I do not see anywhere for a non hacker to notify them about a
potential bug! Your help would be appreciated :)

**Comment by rodelgc** [comment]
Hi @WhoopDav,

Here's the link to Automattic's HackerOne page: https://hackerone.com/automattic
You should see a button there to submit a report, and it will take you to a form where you'd fill up the details of the issue.
