### ISSUE TITLE
无法加载店面向导

### ISSUE THREAD

**Issue by Aaronmengxin** [woothemes/woocommerce#31300]
![P7KIWZJ@CF@ ~$) {HNJHAU](https://user-images.githubusercontent.com/41654532/143452612-353a29f3-874b-4837-a1f9-3502f6c9c84b.png)
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment]
Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

In this issue you only provided us the title, which translated to:
> Illegal loading store face-to-face guidance


Although we see from your screenshot that a certain WooCommerce page loads as a blank screen (seems like it's the Home page), we still need the other details that we ask for in the template such as the steps to replicate and the system status report. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
