### ISSUE TITLE
Updating an order (adding line items) with rest api returns invalid_item_id

### ISSUE THREAD

**Issue by gijoecodes** [woothemes/woocommerce#31332]
I’m attempting to update an order according to the documentation as shown here: [(http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order)](http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order) When updating the quantity of a line item that is currently in the order, the order is updated. When adding new line items, the response is.

```
"code":"woocommerce_rest_invalid_item_id",
"message":"Order item ID provided is not associated with order."
```

It is my understanding that line items ids are generated automatically when the order is process therefore when adding new line items I do not include the id for that new item. This was change from a few years ago when null was required as the value for id as described here: https://github.com/woocommerce/woocommerce/issues/11450#issuecomment-233696284.

Adding additional line items to the order was working up to a month or two ago by simply not including the line item id. I can’t find where I read that solution.

```
          "line_items" : [
            {
              "id" : 140,
              "product_id" : 250,
              "quantity" : 3,
              "sku" : "",
              "subtotal" : "777.0",
              "price" : "259",
              "variation_id" : 0,
              "tax_class" : "",
              "meta_data" : [],
              "total" : "777.0"
              "name" : "Chair"
            },
            {
              "product_id" : 238,
              "quantity" : 1,
              "sku" : "",
              "subtotal" : "267.0",
              "price" : "267",
              "variation_id" : 0,
              "tax_class" : "",
              "meta_data" : [],
              "total" : "267.0",
              "name" : "Table"
            }
          ],
```

**Comment by mrandreiv** [comment]
I omitted the "id"  and used "sku" insead and it worked to add new item.
{
        "line_items":[   
        {
               "name":"test",
               "sku":"4433",
               "price":34,
               "quantity":3,
               "total":"554"
    }
    ]
    }
