### ISSUE TITLE
add action  woocommerce_payment_token_deleted not working 

### ISSUE THREAD

**Issue by pankajswarankar** [woothemes/woocommerce#31341]
Ive added a action to receive woocommerce_payment_token_deleted

add_action('woocommerce_payment_token_deleted', array($this, 'action_woocommerce_payment_token_deleted'), 10, 2 );

However my function "action_woocommerce_payment_token_deleted" is never called when I delete a token in the my accounts payment method page. 

I have checked that the WooCommerce function public function delete( &$token, $force_delete = false ) 
in class-wc-payment-token-data-store.php is definitely getting called. But for some reason the do_action is not triggering my function. I even tried declaring it within the woocommerce class-wc-payment-token-data-store.php as a test but still it wasnt being triggered. If I call do_action myself it works fine. 

I also installed a plugin called "Show Hooks" which helps to show actions triggered and its not showing woocommerce_payment_token_deleted

Please assist.

**Comment by pankajswarankar** [comment]
I resolved it by create new payment token file and create separate add_action for  woocommerce_payment_token_deleted
and create function for the same and it works

**Comment by mendozal** [comment]
@pankajswarankar I was facing the same issue, and your answer guide me towards the solution.
Apparently, the 
`
add_action('woocommerce_payment_token_deleted', 'woocommerce_payment_token_deleted', 10, 2);
`
needs to be called in the main plugin php file, and the function needs to be there too and not inside the WC_Payment_Gateway object definition.

I moved the function to another php file too and required it in the main php file.

Just leaving the comment here in case someone else needs help in the future.
