### ISSUE TITLE
Deprecated and removed jQuery code in jquery.zeroclipboard.js

### ISSUE THREAD

**Issue by pacmanito** [woothemes/woocommerce#31349]
Hi. There's some deprecated and even removed jQuery code in Zeroclipboard script (https://github.com/woocommerce/woocommerce/blob/release/6.0/plugins/woocommerce/assets/js/zeroclipboard/jquery.zeroclipboard.js), namely, it uses deprecated and removed $.event.props on lines 1762-1774.

https://github.com/woocommerce/woocommerce/blob/7e124b40113e3da13f2e6315f150170bfbf265d9/plugins/woocommerce/assets/js/zeroclipboard/jquery.zeroclipboard.js#L1762-L1774

Check for more information https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed
I reported it in the original jQuery 3 compatibility issue (https://github.com/woocommerce/woocommerce/issues/28284#issuecomment-972796001) but nobody reacted.

**Comment by juliaamosova** [comment]
Hi @pacmanito,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Thanks for reporting and raising the issue, @pacmanito! 

I can see we have a duplicate here #31353 with a PR from a contributor, so hope you don't mind if I close this one (even though you created the issue before the other one) and we continue the discussion on the other ticket.
