### ISSUE TITLE
Incorrect Order Data Using `@woocommerce/api`

### ISSUE THREAD

**Issue by jeffstieler** [woothemes/woocommerce#31345]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The `Order` model transformation appears to be broken. Keys are transforms, but values seem to be missing or incorrectly cast to other data types.

See the comparison below:

<table>
<tr>
<th align="left">API Response</th>
<th align="left">Transformed Object</th>
</tr>
<tr>
<td valign="top">
<pre>
{
  id: 1218,
  parent_id: 0,
  status: 'pending',
  currency: 'USD',
  version: '6.1.0',
  prices_include_tax: false,
  date_created: '2021-12-01T05:43:38',
  date_modified: '2021-12-01T07:31:05',
  discount_total: '5.00',
  discount_tax: '0.60',
  shipping_total: '0.00',
  shipping_tax: '0.00',
  cart_tax: '6.00',
  total: '56.00',
  total_tax: '6.00',
  customer_id: 0,
  order_key: 'wc_order_GFHWVmAiamh0B',
  billing: {
    first_name: '',
    last_name: '',
    company: '',
    address_1: '',
    address_2: '',
    city: '',
    state: '',
    postcode: '',
    country: '',
    email: '',
    phone: ''
  },
  shipping: {
    first_name: '',
    last_name: '',
    company: '',
    address_1: '',
    address_2: '',
    city: '',
    state: '',
    postcode: '',
    country: '',
    phone: ''
  },
  payment_method: '',
  payment_method_title: '',
  transaction_id: '',
  customer_ip_address: '',
  customer_user_agent: '',
  created_via: 'admin',
  customer_note: '',
  date_completed: null,
  date_paid: null,
  cart_hash: '',
  number: '1218',
  meta_data: [],
  line_items: [
    {
      id: 6137,
      name: 'Belt',
      product_id: 16,
      variation_id: 0,
      quantity: 1,
      tax_class: '',
      subtotal: '55.00',
      subtotal_tax: '6.60',
      total: '50.00',
      total_tax: '6.00',
      taxes: [ { id: 1, total: '6', subtotal: '6.6' } ],
      meta_data: [],
      sku: 'woo-belt',
      price: 50,
      parent_name: null
    }
  ],
  tax_lines: [
    {
      id: 6139,
      rate_code: 'US-TAX-1',
      rate_id: 1,
      label: 'Tax',
      compound: false,
      tax_total: '6.00',
      shipping_tax_total: '0.00',
      rate_percent: 12,
      meta_data: []
    }
  ],
  shipping_lines: [],
  fee_lines: [],
  coupon_lines: [
    {
      id: 6138,
      code: 'save5',
      discount: '5',
      discount_tax: '0.6',
      meta_data: [
        {
          id: 57112,
          key: 'coupon_data',
          value: {
            id: 171,
            code: 'save5',
            amount: '5',
            date_created: {
              date: '2021-05-19 04:28:31.000000',
              timezone_type: 3,
              timezone: 'Pacific/Auckland'
            },
            date_modified: {
              date: '2021-05-19 04:28:31.000000',
              timezone_type: 3,
              timezone: 'Pacific/Auckland'
            },
            date_expires: null,
            discount_type: 'fixed_cart',
            description: '',
            usage_count: 3,
            individual_use: false,
            product_ids: [],
            excluded_product_ids: [],
            usage_limit: 0,
            usage_limit_per_user: 0,
            limit_usage_to_x_items: null,
            free_shipping: false,
            product_categories: [],
            excluded_product_categories: [],
            exclude_sale_items: false,
            minimum_amount: '',
            maximum_amount: '',
            email_restrictions: [],
            virtual: false,
            meta_data: []
          },
          display_key: 'coupon_data',
          display_value: {
            id: 171,
            code: 'save5',
            amount: '5',
            date_created: {
              date: '2021-05-19 04:28:31.000000',
              timezone_type: 3,
              timezone: 'Pacific/Auckland'
            },
            date_modified: {
              date: '2021-05-19 04:28:31.000000',
              timezone_type: 3,
              timezone: 'Pacific/Auckland'
            },
            date_expires: null,
            discount_type: 'fixed_cart',
            description: '',
            usage_count: 3,
            individual_use: false,
            product_ids: [],
            excluded_product_ids: [],
            usage_limit: 0,
            usage_limit_per_user: 0,
            limit_usage_to_x_items: null,
            free_shipping: false,
            product_categories: [],
            excluded_product_categories: [],
            exclude_sale_items: false,
            minimum_amount: '',
            maximum_amount: '',
            email_restrictions: [],
            virtual: false,
            meta_data: []
          }
        }
      ]
    }
  ],
  refunds: [],
  date_created_gmt: '2021-11-30T16:43:38',
  date_modified_gmt: '2021-11-30T18:31:05',
  date_completed_gmt: null,
  date_paid_gmt: null,
  currency_symbol: '$',
  _links: {
    self: [
      {
          href: 'http://local.wordpress.test/wp-json/wc/v3/orders/1218'
      }
    ],
    collection: [
      {
          href: 'http://local.wordpress.test/wp-json/wc/v3/orders'
      }
    ]
  }
}
</pre>
</td>
<td valign="top">
<pre>
Order {
  metaData: [],
  parentId: 0,
  status: 'pending',
  currency: 'USD',
  version: '6.1.0',
  pricesIncludeTax: false,
  discountTotal: '5.00',
  discountTax: '0.60',
  shippingTotal: '0.00',
  shippingTax: '0.00',
  cartTax: '6.00',
  total: '56.00',
  totalTax: '6.00',
  customerId: 0,
  orderKey: '',
  billing: OrderAddress {
    firstName: '',
    lastName: '',
    companyName: '',
    address1: '',
    address2: '',
    city: '',
    state: '',
    postCode: '',
    countryCode: '',
    email: '',
    phone: ''
  },
  shipping: {
    first_name: '',
    last_name: '',
    company: '',
    address_1: '',
    address_2: '',
    city: '',
    state: '',
    postcode: '',
    country: '',
    phone: ''
  },
  paymentMethod: '',
  paymentMethodTitle: '',
  transactionId: '',
  customerIpAddress: '',
  customerUserAgent: '',
  createdVia: '',
  customerNote: '',
  dateCompleted: null,
  datePaid: null,
  cartHash: '',
  orderNumber: '',
  currencySymbol: '',
  setPaid: false,
  lineItems: [],
  taxLines: [],
  shippingLines: [],
  feeLines: [],
  couponLines: [],
  refunds: [],
  links: { collection: [ { href: '' } ], self: [ { href: '' } ] },
  id: 1218,
  parent_id: 0,
  order_key: 'wc_order_GFHWVmAiamh0B',
  payment_method_title: '',
  customer_ip_address: '',
  customer_user_agent: '',
  created_via: 'admin',
  date_completed: null,
  date_paid: null,
  cart_hash: '',
  number: '1218',
  meta_data: [],
  line_items: [
    OrderLineItem {
      metaData: [],
      name: '',
      productId: -1,
      variationId: 0,
      quantity: -1,
      taxClass: '',
      subtotal: '',
      subtotalTax: '',
      total: '',
      totalTax: '',
      taxes: [],
      sku: '',
      price: -1,
      parentName: null
    }
  ],
  tax_lines: [
    OrderTaxRate {
      rateCode: '',
      rateId: 0,
      label: '',
      compoundRate: false,
      taxTotal: '',
      shippingTaxTotal: '',
      ratePercent: 0
    }
  ],
  shipping_lines: [],
  fee_lines: [],
  coupon_lines: [
    OrderCouponLine {
      metaData: [],
      code: '',
      discount: '',
      discountTax: ''
    }
  ],
  date_created_gmt: '2021-11-30T16:43:38',
  date_modified_gmt: '2021-11-30T18:31:05',
  date_completed_gmt: null,
  date_paid_gmt: null,
  currency_symbol: '$',
  _links: {
    self: [
      {
          href: 'http://local.wordpress.test/wp-json/wc/v3/orders/1218'
      }
    ],
    collection: [
      {
          href: 'http://local.wordpress.test/wp-json/wc/v3/orders'
      }
    ]
  }
}
</pre>
</td>
</tr>
</table>

**Expected behavior**

I would expect the snake case properties to be omitted from the transformed model, the data types to be cast correctly, and data to not be missing (such as `OrderCouponLine`s, etc).

**Actual behavior**

See the example above.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

```javascript
const API = require( '@woocommerce/api' );
const { HTTPClientFactory, Order } = API;

const httpClient = HTTPClientFactory.build( 'http://local.wordpress.test' )
    .withBasicAuth( 'admin', 'password' )
    .create();

httpClient.get( '/wc/v3/orders/1218' ).then( ( response ) => {
    console.dir( response.data, { depth: null } );
} );

const repository = Order.restRepository( httpClient );

repository.read( 1218 ).then( ( order ) => console.dir( order, { depth: null } ) );
```

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Luc45 I'm going to close this as #31665 has been merged. We should create one or more new issues pending the results of planning for the package.
