### ISSUE TITLE
Collect metrics on E2E test retries

### ISSUE THREAD

**Issue by MrJnrman** [woothemes/woocommerce#31351]
E2E retries were implemented [here](https://github.com/woocommerce/woocommerce/pull/31336)

It would be great to collect metrics on which tests are being retried. This could help us identify flaky tests and make them more robust.

**Comment by lanej0** [comment]
Can we call this one done with [Flaky test reporting](https://github.com/woocommerce/woocommerce/issues?q=is:issue+is:open+%5BFlaky%5D)?  Or are there additional metrics you think would be useful?
