### ISSUE TITLE
Deprecated library zeroclipboard on project

### ISSUE THREAD

**Issue by gs-nasc** [woothemes/woocommerce#31353]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:** Woocommerce has using a deprecated library (zeroclipboard), zeroclipboard uses flash ([that descontinuated for security issues](https://www.howtogeek.com/700229/adobe-flash-is-dead%C2%A0heres-what-that-means/)), and flash doesn't work more in the recent browsers and ins't possible download him.

ZeroClipboard is registered in admin panel
https://github.com/woocommerce/woocommerce/blob/7e124b40113e3da13f2e6315f150170bfbf265d9/plugins/woocommerce/includes/admin/class-wc-admin-assets.php#L115

and have deprecated jquery methods, like $.event.props
https://github.com/woocommerce/woocommerce/blob/7e124b40113e3da13f2e6315f150170bfbf265d9/plugins/woocommerce/assets/js/zeroclipboard/jquery.zeroclipboard.js#L1762-L1774

**Comment by juliaamosova** [comment]
Hi @gs-nasc,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by gs-nasc** [comment]
Hello, thanks for the response, i'll wait the time it was need.

**Comment by peterfabian** [comment]
Thanks for reporting and the PR, appreciated!

We will first include a dev advisory on the blog to communicate we're going to drop it and then can merge it and drop the dependency. Just to make sure we keep things backward compatible, if possible.

**Comment by barryhughes** [comment]
Removing from the *needs-dev-feedback* queue, since we have a plan-of-action :-)
