### ISSUE TITLE
Product attribute lookup table is created without indexes

### ISSUE THREAD

**Issue by slightlyfaulty** [woothemes/woocommerce#31367]
The new `wc_product_attributes_lookup` table in WC 6.0 is created without any indexes. This seems strange for a lookup table. Is it intentional or an oversight?

https://github.com/woocommerce/woocommerce/blob/313d40d3960da3de560a96566491bb6115141eec/plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php#L137-L148

**Comment by tammullen** [comment]
Hi @slightlyfaulty ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by zenagency-US** [comment]
I just attempted to create and build this table and it keeps stalling out. The most rows it's built is 1078. My site has several hundred thousand attributes. Any thoughts on why it just stops building?

**Comment by pduclo** [comment]
My "Regenerate the product attributes lookup table" also stopped at "Filling in Progess (1610)".  The button is greyed out and no option to kickstart it.

I have 2400 products. 100s of variations for each product.  Several attributes for each product. Hundreds of values in each attribute.

The attribute lookup table regeneration seemed to be making progress for a few hours then stopped at 1610. 

wp_wc_product_attributes_lookup data_length 85,573,632

Has this been tested on stores with huge numbers of product/variation/attribute/value?

**Comment by Konamiman** [comment]
Hi @zenagency-US and @pduclo, thanks for your report. I'm going to investigate this issue but it would be helpful for me to have some more information. When the table regeneration stalls, if you go to _WooCommerce - Status - Scheduled actions_ do you see entries with hook name `woocommerce_run_product_attribute_lookup_regeneration_callback`? If so, what are the values of the "status" and "log" columns? Many thanks!

**Comment by zenagency-US** [comment]
@Konamiman  I do not see woocommerce_run_product_attribute_lookup_regeneration_callback at all when I search the scheduled actions. However, my lookup table is now up to 93000 rows ever since I turned off the redis object cache. So that may be where the issue lies.

**Comment by grig-23** [comment]
Not sure if this requires a separate report, but it looks like this wc_product_attributes_lookup table doesn't have a primary key by default.

With some hosting service providers, e.g. Digital Ocean, sql_require_primary_key seems to be 1 by default, which prevents this table from being created in certain cases, e.g. when the table is re-generated or perhaps even during the data migration during an update.

Some users reported only being able to get the table to create after setting sql_require_primary_key to 0, `SET SESSION sql_require_primary_key = 0;`

https://wordpress.org/support/topic/after-6-3-0-missing-base-tables-wp_wc_product_attributes_lookup/#post-15448764

4846240-zen
4851879-zen

Should this database table have a primary key? Seems like all other tables have it.

**Comment by Konamiman** [comment]
An update on this:

- As of WooCommerce 6.3 the product attributes lookup table has indices.
- As of WooCommerce 6.4 it will have a primary key too.
- Also, a tool has been added (WooCommerce - Status - Tools) that allows the table regeneration process to be paused, and from there, to be either resumed or restarted (see https://github.com/woocommerce/woocommerce/pull/31889)
