### ISSUE TITLE
html_entity_decode() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by bluantinoo** [woothemes/woocommerce#31364]
https://github.com/woocommerce/woocommerce/blob/313d40d3960da3de560a96566491bb6115141eec/plugins/woocommerce/includes/wc-attribute-functions.php#L19

Don't really know what's happening here, but I get this having default WP theme and just Woocommerce as plugin.

`PHP Warning:  html_entity_decode() expects parameter 1 to be string, array given in /wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 19`

apparently the variable `$raw_attributes` is an array, if I print it I get something like this:

```
Array
(
    [0] => 7971
    [1] => 7972
    [2] => 7973
    [3] => 7974
    [4] => 7975
)
```

This is my backtrace: file, line - function

```
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/wc-product-functions.php, 723 - wc_get_text_attributes
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php, 83 - wc_get_product_variation_attributes
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/class-wc-data-store.php, 159 - read
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php, 137 - read
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/class-wc-product-simple.php, 24 - __construct
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/class-wc-product-variation.php, 54 - __construct
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/class-wc-product-factory.php, 46 - __construct
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/wc-product-functions.php, 72 - get_product
[04-Dec-2021 12:16:52 UTC] /wp-content/plugins/woocommerce/includes/class-wc-cart-session.php, 112 - wc_get_product
[04-Dec-2021 12:16:52 UTC] /wp-includes/class-wp-hook.php, 303 - get_cart_from_session
[04-Dec-2021 12:16:52 UTC] /wp-includes/class-wp-hook.php, 327 - apply_filters
[04-Dec-2021 12:16:52 UTC] /wp-includes/plugin.php, 470 - do_action
[04-Dec-2021 12:16:52 UTC] /wp-settings.php, 600 - do_action
[04-Dec-2021 12:16:52 UTC] /wp-config.php, 84 - require_once
[04-Dec-2021 12:16:52 UTC] /wp-load.php, 50 - require_once
[04-Dec-2021 12:16:52 UTC] /wp-admin/admin-ajax.php, 22 - require_once
```

it happens just loading the dashboard, or on any other page (admin or frontend) that includes products

**Comment by juliaamosova** [comment]
Hi @bluantinoo,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Hi, thanks for reporting! It seems this depends on some configuration, namely having some product in your store, etc. Can you please provide the system status report so that we know which WC version this relates to and describe the variable product this happens for (or, provide an export, if possible). Thanks!

@juliaamosova would you folks please be able to follow up and try to reproduce? Thanks!

**Comment by bluantinoo** [comment]
Here's the status report.
I can share also an export of products and variations, but only privately (tell me how to share privately, if that's the case).
Publicly I can just say that most of the contents are in Japanese, also some attributes and their slugs are generated from Japanese titles.

`
### WordPress Environment ###

WordPress address (URL): sorry can't publish
Site address (URL): sorry can't publish
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: ja
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.25
PHP Post Max Size: 150 MB
PHP Time Limit: 7200
PHP Max Input Vars: 12000
cURL Version: 7.79.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.36-log
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 339.09MB
Database Data Size: 283.76MB
Database Index Size: 55.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 6.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_admin_columns: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_smart_filters_indexer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.48MB + Index: 0.16MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 124.52MB + Index: 7.03MB + Engine InnoDB
wp_posts: Data: 83.52MB + Index: 1.03MB + Engine InnoDB
wp_simple_history: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
wp_simple_history_contexts: Data: 50.58MB + Index: 29.11MB + Engine InnoDB
wp_subscription_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_teachers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.16MB + Index: 0.22MB + Engine InnoDB
wp_term_relationships: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 1.00MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 18
acf-field-group: 5
attachment: 414
customize_changeset: 2
elementor_library: 56
jet-smart-filters: 7
jet-woo-builder: 1
nav_menu_item: 37
page: 44
post: 8
product: 122
product_variation: 666
restaurant: 6
revision: 4200
scholarship: 4
shop_order: 9
text-books: 53

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (40) ###

Admin Columns Pro: by AdminColumns.com – 5.6.3
Admin Columns Pro - Advanced Custom Fields (ACF): by AdminColumns.com – 2.7
Admin Columns Pro - WooCommerce: by AdminColumns.com – 3.6.1
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.2.0
DynamicConditions: by RTO GmbH – 1.5.1
Ele Custom Skin: by Dudaster.com – 3.1.4
Elementor: by Elementor.com – 3.4.8
Elementor Beta (Developer Edition): by Elementor.com – 1.1.1
Elementor Pro: by Elementor.com – 3.5.2
Enable Media Replace: by ShortPixel – 3.6.3
GP Limit Checkboxes: by Gravity Wiz – 1.3.3
GP Limit Choices: by Gravity Wiz – 1.7.5
GP Preview Submission: by Gravity Wiz – 1.3.8
Gravity Forms: by Gravity Forms – 2.5.15
Gravity Forms Quiz Add-On: by Gravity Forms – 3.8
Gravity Perks: by Gravity Wiz – 2.2.7
JetSmartFilters: by Crocoblock – 2.3.7
JetWooBuilder For Elementor: by Crocoblock – 1.10.5
KOMOJU: by KOMOJU – 2.1.0
Loco Translate: by Tim Whitlock – 2.5.5
Mail logging - WP Mail Catcher: by James Ward – 1.5.4
Maximum Products per User for WooCommerce: by WPFactory – 3.5.9
Post Duplicator: by Metaphor Creations – 2.23
Redirection: by John Godley – 5.1.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Show Hooks: by rafiq91
exlac – 0.2

Simple Custom Post Order: by Colorlib – 2.5.6
Simple History: by Pär Thernström – 2.43.0
SMTP Mailer: by naa986 – 1.1.2
The Plus Addons for Elementor: by POSIMYTH – 5.0.3
The Plus Addons for Elementor - Pro: by POSIMYTH – 5.0.7
Woocommerce Orders Addon: by BLUCLOUD SRL – 1.4.8
WooCommerce Product Bundles: by SomewhereWarm – 6.12.5
WP All Import - ACF Add-On: by Soflyy – 3.3.5
WP All Import Pro: by Soflyy – 4.7.1
WPC Variations Radio Buttons for WooCommerce: by WPClever – 2.5.6
WP Migrate DB: by Delicious Brains – 2.2.1
WP reCaptcha Integration: by weDevs – 1.2.5
Yoast SEO: by Team Yoast – 17.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: JPY (¥)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /courses/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #34 - /terms-and-conditions/

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 16,785
Oldest: 2021-11-05 17:37:43 +0900
Newest: 2021-12-04 21:02:01 +0900

Pending: 1
Oldest: 2021-12-08 02:55:21 +0900
Newest: 2021-12-08 02:55:21 +0900


### Status report information ###

Generated at: 2021-12-08 02:55:37 +09:00
`

**Comment by lanej0** [comment]
Hi @bluantinoo.

> I can share also an export of products and variations, but only privately (tell me how to share privately, if that's the case).

That would be great, and would really help us in tracking down this issue.  If you wouldn't mind uploading that export using [QuickForget](https://quickforget.com/) and then drop me an email at jon dot lane at automattic dot com with the secret, we'll be able to dig into things a bit deeper.

**Comment by bluantinoo** [comment]
> Hi @bluantinoo.
> 
> > I can share also an export of products and variations, but only privately (tell me how to share privately, if that's the case).
> 
> That would be great, and would really help us in tracking down this issue. If you wouldn't mind uploading that export using [QuickForget](https://quickforget.com/) and then drop me an email at jon dot lane at automattic dot com with the secret, we'll be able to dig into things a bit deeper.

Just sent, thanks @lanej0

**Comment by lanej0** [comment]
Just confirming that I've got it, thanks for sending that.  I'll dig in and take a look!

**Comment by lanej0** [comment]
Hi @bluantinoo

Thanks again for sending in that listing.  I was able to import it into a local test site, but I'm not seeing any errors displayed (either in the Admin, the store or in the logs).  I tried matching themes, plugins and settings as best I could, but I'm not seeing any errors.  I'll bounce this back over to our developers for another look, but there might not be much that we can do without being able to reproduce this on our end.

**Comment by bluantinoo** [comment]
hi @lanej0 
forgive me a question, does the import contains also products taxonomies, including attributes?

**Comment by lanej0** [comment]
Yes, it looks like it.  I clicked on a few different products from the import and they all have multiple attributes.  I am only seeing 3 different product categories (but the products all seem to be assigned).

**Comment by githuzz** [comment]
Today I had the same issue, I created some products with variations without problems, but suddenly when i added a new variation for a new product, the product area kept spinning. Then the whole store broke. All plugins and themes are up to date.

here is the debug info:

[07-Nov-2024 16:01:35 UTC] PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, array given in /wp-content/plugins/woocommerce/includes/wc-attribute-functions.php:19
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/wc-attribute-functions.php(19): html_entity_decode()
#1 /wp-content/plugins/woocommerce/includes/wc-product-functions.php(801): wc_get_text_attributes()
#2 /wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php(83): wc_get_product_variation_attributes()
#3 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Product_Variation_Data_Store_CPT->read()
#4 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(139): WC_Data_Store->read()
#5 /wp-content/plugins/woocommerce/includes/class-wc-product-simple.php(24): WC_Product->__construct()
#6 /wp-content/plugins/woocommerce/includes/class-wc-product-variation.php(54): WC_Product_Simple->__construct()
#7 /wp-content/plugins/woocommerce/includes/class-wc-product-factory.php(46): WC_Product_Variation->__construct()
#8 /wp-content/plugins/woocommerce/includes/wc-product-functions.php(73): WC_Product_Factory->get_product()
#9 /wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(299): wc_get_product()
#10 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): WC_Product_Variable_Data_Store_CPT->read_price_data()
#11 /wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(97): WC_Data_Store->__call()
#12 /wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(508): WC_Product_Variable->get_variation_prices()
#13 /wp-content/plugins/woocommerce/includes/wc-template-functions.php(678): WC_Product_Variable->is_on_sale()
#14 /wp-content/plugins/woocommerce/includes/wc-template-functions.php(740): wc_get_product_class()
#15 /wp-content/plugins/woocommerce/templates/content-product.php(27): wc_product_class()
#16 /wp-includes/template.php(812): require('...')
#17 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(284): load_template()
#18 /wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-products.php(660): wc_get_template_part()
#19 /wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-products.php(100): WC_Shortcode_Products->product_loop()
#20 /wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(283): WC_Shortcode_Products->get_content()
#21 /wp-includes/shortcodes.php(434): WC_Shortcodes::products()
#22 [internal function]: do_shortcode_tag()
#23 /wp-includes/shortcodes.php(273): preg_replace_callback()
#24 /wp-content/plugins/elementor/includes/widgets/shortcode.php(137): do_shortcode()
#25 /wp-content/plugins/elementor/includes/base/controls-stack.php(2325): Elementor\Widget_Shortcode->render()
#26 /wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#27 /wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#28 /wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#29 /wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#30 /wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#31 /wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#32 /wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#33 /wp-content/plugins/elementor/core/base/document.php(1874): Elementor\Element_Base->print_element()
#34 /wp-content/plugins/elementor/core/base/document.php(1799): Elementor\Core\Base\Document->do_print_elements()
#35 /wp-content/plugins/elementor/core/base/document.php(1200): Elementor\Core\Base\Document->print_elements()
#36 /wp-content/plugins/elementor/includes/frontend.php(1190): Elementor\Core\Base\Document->print_elements_with_wrapper()
#37 /wp-content/plugins/elementor/includes/frontend.php(1085): Elementor\Frontend->get_builder_content()
#38 /wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content()
#39 /wp-includes/plugin.php(205): WP_Hook->apply_filters()
#40 /wp-includes/post-template.php(256): apply_filters()
#41 /wp-content/themes/shoptimizer/inc/shoptimizer-template-functions.php(677): the_content()
#42 /wp-includes/class-wp-hook.php(324): shoptimizer_page_content()
#43 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#44 /wp-includes/plugin.php(517): WP_Hook->do_action()
#45 /wp-content/themes/shoptimizer/content-page.php(18): do_action()
#46 /wp-includes/template.php(812): require('...')
#47 /wp-includes/template.php(745): load_template()
#48 /wp-includes/general-template.php(206): locate_template()
#49 /wp-content/themes/shoptimizer/template-canvas.php(22): get_template_part()
#50 /wp-includes/template-loader.php(106): include('...')
#51 /wp-blog-header.php(19): require_once('...')
#52 /index.php(17): require('...')
#53 {main}
  thrown in /wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 19
