### ISSUE TITLE
Add the possibility to filter orders according to products

### ISSUE THREAD

**Issue by rodolphebertozzo** [woothemes/woocommerce#31366]
On the orders page : Woocommerce > Orders, add in the filters a "sort by products" function

**Comment by tammullen** [comment]
Hi @rodolphebertozzo ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
