### ISSUE TITLE
Loading speed on product categories with 1000s of products

### ISSUE THREAD

**Issue by sethbarrett** [woothemes/woocommerce#31374]
How can I speed up the time it takes to pull a product category? 
I have done all the recommended optimizations I could find. Still taking ages to pull any category page that has more than 3k products:
https://sbsimpson.shop/product-category/cutting-tools/

This category only has 114 products & loads fast:
https://sbsimpson.shop/product-category/electrical-lighting/

All the other areas of the site - sku page, backend, regular content page - load really fast... but not the product cat pages. & I tried this before I installed WP Product Tables. This was very slow with everything stock & storefont theme installed... 

What can be done about this? I have the site on a very fast server. Every other area of the site loads very quickly. My hosting partner noted the following details:

Following mysql query is being executed while loading the link https://sbsimpson.shop/product-category/cutting-tools/

------------------------------

| 1379 | sbsimpso_2nd | localhost | sbsimpso_2nd | Query | 6 | executing | SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts. |

--------------------------------

It seems this query need some optimization to improve the loading and execution time.Please review this with the site developer. Also check the suggestions provided in https://gtmetrix.com/reports/sbsimpson.shop/2GQ47lNI/

There is 27 GB of free memory and the server load and I/O is fine.

**Comment by sethbarrett** [comment]
And to be clear I've done the css / js minifcation, gzip compression, etc. etc. all of the suggested ways to speed the site up. The site is very fast in all ways except this. Product cats take forever to load when there are a large volume of skus.. problem is client wants to import another 100k skus so all product cats are going to have 1000s of skus and will therefore take forever to load...

**Comment by tammullen** [comment]
Hi @sethbarrett 

It will be great if you could share your current System Status Report to help us evaluate this issue. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.
