### ISSUE TITLE
Post dev advisory about dropping zeroclipboard

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#31384]
We should post on our dev blog that we're dropping the dependency, then drop it. 

Ref issue: https://github.com/woocommerce/woocommerce/issues/31353

Ideally, follow up with a task that reviews other dependencies.

**Comment by barryhughes** [comment]
Draft dev advisory: 

238-gh-woocommerce/woocommerce-developer-advocacy

**Comment by barryhughes** [comment]
Closing. This was published on [March 30](https://developer.woocommerce.com/2022/03/30/removal-of-zeroclipboard/).
