### ISSUE TITLE
Deprecated warnings in WP CLI with PHP 8.1

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31386]
I was testing a WP CLI PR with PHP 8.1 and had the following deprecated notices:

- `Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 371`
- `Deprecated: Automatic conversion of false to array is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/wc-term-functions.php on line 536`
- `Deprecated: Function strftime() is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 264`

The line # correspond to WC5.9.0.

**Comment by ghost** [comment]
Problem happening on production site.
OS: Debian 11 x64 (Bullseye)
Webserver: Litespeed 6.0.12
PHP: 8.1.6 (lsphp)
WP: 6.0
WooCommerce: 6.5.1
