### ISSUE TITLE
Geolocating an IP always uses country codes set in headers

### ISSUE THREAD

**Issue by tc33** [woothemes/woocommerce#31393]
**Prerequisites:**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The `WC_Geolocation::geolocate_ip()` function can be called with an optional IP address. If an IP address is not provided, it uses the current user's IP address. The function then returns an array containing location information for that IP, such as the country code. If HTTP headers exist containing a country code (e.g. `HTTP_CF_IPCOUNTRY` which is added by Cloudflare) then the function uses this country code instead of geolocating the IP address.

The bug is that the function will use this country code header if it exists, even when the function is called with a specific IP address. This causes the function to return the current user's country code for any IP passed.

In WooCommerce core this function only seems to be called with an IP address when it's using an external IP service, so by chance probably avoids this bug as these headers are unlikely to exist in a local environment. However, I suspect there are other extensions relying on this function.

**Demonstration code**

```
// Geolocate a 'US' IP address
$ip_address = 'X.X.X.X;
var_dump( WC_Geolocation::geolocate_ip( $ip_address ) );

// Set a 'GB' country code header
$_SERVER['HTTP_CF_IPCOUNTRY'] = 'GB';

// Geolocate the same 'US' IP address
var_dump( WC_Geolocation::geolocate_ip( $ip_address ) );
```

The output will be something like this:
```
array(4) { ["country"]=> string(2) "US" ["state"]=> string(0) "" ["city"]=> string(0) "" ["postcode"]=> string(0) "" }
array(4) { ["country"]=> string(2) "GB" ["state"]=> string(0) "" ["city"]=> string(0) "" ["postcode"]=> string(0) "" }
```

**Comment by tammullen** [comment]
Hi @tc33 ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for flagging! I agree—if a specific IP address is passed, then that is what should be assessed (and we shouldn't assume that headers from the current request should override it). I can't envision any serious backward compatibility concerns that would arise from resolving this.
