### ISSUE TITLE
My Subscriptions: HTML doesn't render correctly for extensions that are installed without a subscription

### ISSUE THREAD

**Issue by joashrajin** [woothemes/woocommerce#31399]
### Describe the bug
If you download some extensions from WooCommerce.com but don't own them on the WooCommerce.com account connected to your site, you get them listed under 'Installed Extensions without a Subscription'. All of the warning messages do not render correctly and show as: 

` To receive updates and support for this extension, you need to <strong>purchase</strong> a new subscription or consolidate your extensions to one connected account by <strong><a href="https://docs.woocommerce.com/document/managing-woocommerce-com-subscriptions/#section-10" title="Sharing Docs">sharing</a> or <a href="https://docs.woocommerce.com/document/managing-woocommerce-com-subscriptions/#section-5" title="Transferring Docs">transferring</a></strong> this extension to this connected account.`

### To Reproduce

1. Connect your site to WooCommerce.com (via WooCommerce > My Subscriptions > Connect)
2. Download an extension manually from WooCommerce.com ([downloads](https://woocommerce.com/my-account/downloads/)) and install it on your site 
3. As long as you don't own a subscription for that extension on the connected account, you will see the error. 

### Actual behavior:
An error is shown but the HTML does not render correctly

### Screenshots

![image](https://user-images.githubusercontent.com/16253818/137131330-9818af39-6147-4a5b-86c6-b499b584982f.png)

### Expected behavior
The HTML in the error messages should render correctly.

**Comment by barryhughes** [comment]
I believe this was solved in https://github.com/woocommerce/woocommerce/pull/30859 but feel free to create a fresh issue if you still see a problem.
