### ISSUE TITLE
WC_Shortcode_My_Account::retrieve_password(): add filter for user_data

### ISSUE THREAD

**Issue by bome** [woothemes/woocommerce#31403]
**Is your feature request related to a problem? Please describe.**
Under certain circumstances, we would like to create a user account when the user tries to log in. 

Background: we keep on getting emails from frustrated customers that they cannot log in. They expect that the account is automatically created on purchase (which is an option in our WC store). It would be sufficient for them to just create a new account. But some customers don't consider that, and get frustrated. We have a separate database of customer email addresses (who actually purchased a product -- which can also be purchased outside of our WooCommerce store), and we would like to create an account automatically when such an actual customer tries to log in.

**Describe the solution you'd like**
To us, the simplest solution seems to add a filter to [WC_Shortcode_My_Account::retrieve_password() (line 275)](https://github.com/woocommerce/woocommerce/blob/fedb5e9677401eb9e0fe6456474cf89ce7351d90/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php#L275):

```php
public static function retrieve_password() {
	$login = isset( $_POST['user_login'] ) ? sanitize_user( wp_unslash( $_POST['user_login'] ) ) : ''; // WPCS: input var ok, CSRF ok.

	if ( empty( $login ) ) {

		wc_add_notice( __( 'Enter a username or email address.', 'woocommerce' ), 'error' );

		return false;

	} else {
		// Check on username first, as customers can use emails as usernames.
		$user_data = get_user_by( 'login', $login );
	}

	// If no user found, check if it login is email and lookup user based on email.
	if ( ! $user_data && is_email( $login ) && apply_filters( 'woocommerce_get_username_from_email', true ) ) {
		$user_data = get_user_by( 'email', $login );
	}

	// --------------- proposed code starts here ---------------
	$user_data = apply_filters( 'woocommerce_retrieve_password_filter_user_data', $user_data, $login );
	// --------------- proposed code end ---------------

	$errors = new WP_Error();

	do_action( 'lostpassword_post', $errors, $user_data );

	if ( $errors->get_error_code() ) {
		wc_add_notice( $errors->get_error_message(), 'error' );

		return false;
	}

	if ( ! $user_data ) {
		wc_add_notice( __( 'Invalid username or email.', 'woocommerce' ), 'error' );

		return false;
	}
	...
```

**Describe alternatives you've considered**
*Could we implement the functionality without a new filter?*
We considered implementing the `lostpassword_post` hook and create the account if the passed `$user_data` object is `null`. But for that, we would need to directly access the internal `$_POST['user_login']` field. And the WC implementation would still fail with an error to the user.
We've considered overriding `get_user_by(...)`, but that would mean that we will need to track any changes to the original implementation. And again, our code would then need to guess if the user currently tries to log in, or on the other hand, if it is called because some component wants to query existence of an account (in which case we shouldn't create an account).
Also, overriding other functionality could work (somehow), but usually has the same problems.
And because all of this is security related, I'd rather not resort to copying/pasting such core parts.

*Could the filter be implemented differently?*
Yes, for example it could be made a filter that is only called when `$user_data` is `null`, and/or if `$login` is a valid email address. The above is the most generic, though.

**Additional context**
I'm not a WC developer, so I don't know the conventions for filters (when/how/why/naming). But if we can get to an acceptable approach in this issue discussion, I can create a pull request.

**Comment by barryhughes** [comment]
Apologies for the long delay here.

> Under certain circumstances, we would like to create a user account when the user tries to log in.

I'm not sure I understand how this would work. Let's start with the login form on the My Account page. It contains a username and password field:

<div align="center"><img width="850" alt="Screenshot of the My Account page login form." src="https://github.com/woocommerce/woocommerce/assets/3594411/cf0353bd-634c-4b82-ae29-7cb1a6f7b74d"></div>

For users without an existing account, are you envisioning that you will capture whatever they supply as a password, and save it as the password of the new user? This seems pretty niche (seems like custom development territory), and I'm inclined to think we won't take it forward as a core plugin feature.

**Comment by bome** [comment]
Thanks! My actual request is to **add one line** to the function above invoking the proposed filter. 
That will be sufficient for what I would like to do. And the filter can be useful for other plugins or themes, too.

But to fully answer your question, this is how I would like to do it:

1. A user without an account tries to log in.
2. It fails. The user still thinks they already have an account, so uses the Lost Password function.
3. The Lost Password implementation calls the requested/new filter (see above)
4. My module gets called via the requested filter
5. My module checks if the user's email address belongs to a customer (i.e. who has bought something in our web shop without registering a user account)
6. If so, my module creates the user account (with a random password).
7. The Lost Password handling proceeds normally. Because the account exists now, it sends out the "Lost Password" email so that the user can finish setting up the account with an own password.

If there is any other action or filter that I could use for that, I'd be more than happy.

I can only suspect that many web shop owners have a similar problem.

**Comment by barryhughes** [comment]
Apologies for the delay. I guess it sounds a little unorthodox to me, and perhaps even verging on an anti-pattern (unless you are adding supporting messaging to make it absolutely clear that an account will be created).

<div align="center"><img width="1163" alt="Login failed notice." src="https://github.com/woocommerce/woocommerce/assets/3594411/0e1f440e-02dc-4813-9021-94c01e0608f4"></div>

Might it be better to customize the above notice (which is what someone will normally see, if logging in via My Account fails) to indicate they can register an account? On the other hand, if you are positive you want to follow this route, can you take advantage of this existing hook?

```php
do_action( 'lostpassword_post', $errors, $user_data );
```

Your callback could use the supplied data to determine if a new account should be generated, and modify the error data to allow execution to continue.

**Comment by bome** [comment]
Hi Barry, I appreciate that you've taken the time to reply.

Thank you for the suggestions. We have already customized the error message above, but customers still "don't get it". Most of our support requests are because they "cannot log in". Despite our hint, they think that they must have an account already, because they're already a customer.

Regarding the `lostpassword_post` hook: unfortunately, the $user_data variable is `NULL`. So even if we can create the account during that hook, `retrieve_password()` will still fail after calling the hook due to the subsequent check:

```
	if ( ! $user_data ) {
		wc_add_notice( __( 'Invalid username or email.', 'woocommerce' ), 'error' );

		return false;
	}
```

Right now, WC uses 2 ways to retrieve `$user_data`: 1. via username, 2. via email address. The proposed filter would add a 3rd way, by allowing a plugin or theme to do so, too:
```
$user_data = apply_filters( 'woocommerce_retrieve_password_filter_user_data', $user_data, $login );
```

A shorter filter name would be `woocommerce_lostpassword_user_data'.
Thanks!

**Comment by barryhughes** [comment]
Gotcha, good catches!

Probably our preferred way in that case would be to replace the default shortcode handler with one of your own (which could inherit everything except this one method, which it would override).  However, we'd still consider a pull request if you strongly feel that is not viable.

> A shorter filter name would be `woocommerce_lostpassword_user_data'.

I'd actually tend to be more verbose, if anything.

`woocommerce_my_account_shortcode_retrieve_password_user_data`

This makes it clear the filter is 'pegged' to the current shortcode implementation (important, because we are in the midst of transitioning to a Block-driven experience, and so there are some considerations to be mindful of there in terms of what each experience supports, and if the delta between them will be confusing).

**Comment by bome** [comment]
> Probably our preferred way in that case would be to replace the default shortcode handler with one of your own

That's an excellent idea!
- our overridden shortcode handler only checks the conditions when a new account should be created. If yes, create it.
- then call the original WC shortcode handler `WC_Shortcode_My_Account::retrieve_password()`

Thank you very much, I think that will solve our problem and we will not need to do a pull request. I'll close this issue here in the next days when we've verified that it works.

**Comment by barryhughes** [comment]
We'd definitely prefer that (and, please let us know if you hit up against any difficulties). Thanks for considering it!

**Comment by barryhughes** [comment]
Sounds like no further action is required, here, but feel free to open a fresh issue (referencing this one, if appropriate) if that's not the case :+1:
