### ISSUE TITLE
Broken links on docs and @woocommerce NPM packages

### ISSUE THREAD

**Issue by leonardola** [woothemes/woocommerce#31406]
After packages got moved to the /packages folder inside this repo our NPM packages links broke. Also the documentation on the packages are broken or pointing to our master branch

These are the ones I stumbled upon. But probably all packages broke:
- [@woocommerce/e2e-environment/](https://www.npmjs.com/package/@woocommerce/e2e-environment/)
- [@woocommerce/e2e-utils](https://www.npmjs.com/package/@woocommerce/e2e-utils)
- [@woocommerce/api](https://www.npmjs.com/package/@woocommerce/api)

**Expected behavior**
All @woocommerce NPM packages should point to the correct place
All packages should have up to date documentation with links pointing to the correct place

**Comment by rrennick** [comment]
@leonardola The links have been updated but they won't be propagated to npmjs.com until new version of the packages are released. npmjs.com does not allow updating existing published packages so we just have to wait for package releases. I'm closing this as we can't do anything more on this.
