### ISSUE TITLE
LearnPress error: Query lp/v1/courses/archive-course learnpress

### ISSUE THREAD

**Issue by AssadMalik** [woothemes/woocommerce#31426]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are using LearnPress + WooCommerce to build an online Course selling platform but when we connect the woo-commerce to learn press then it gave us an error which is maybe AJAx conflict between the two plugins.  error: Query lp/v1/courses/archive-course learn press. 

### Expected behavior

After this, we can use woo commerce with learn press and the learn press default course template can be able to load. 

### Actual behavior

ajax conflicts with learn press and woo-commerce.

### Steps to reproduce

install learn press
install woocommerce
use woo-commerce checkout and payment method
see the learn press default our course template will not appear on the website.

### WordPress Environment

not the WordPress admin but it is in the front end

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @AssadMalik,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin LearnPress. 

Please contact the author of the plugin directly for further help.

**Comment by Hypamania** [comment]
This is a new error from version 6 of woocommerce.  It is not a LearnPress issue.  Please fix ASAP.

**Comment by developerxxl** [comment]
The cause of the problem is the cache plugin. (Wp rocket, wp fastest cache, Litespeed cahce…etc) And to fix it you can either clear your cache or disable your cache plugin and the problem will be solved. [source](https://8y35.com/learnpress/error-query-lp-v1-courses-archive-course/)

**Comment by MustafaBKLZ** [comment]
> The cause of the problem is the cache plugin. (Wp rocket, wp fastest cache, Litespeed cahce…etc) And to fix it you can either clear your cache or disable your cache plugin and the problem will be solved. [source](https://8y35.com/learnpress/error-query-lp-v1-courses-archive-course/)

Yes this is work. I remove LiteSpeed Cache and issiue is solved.
