### ISSUE TITLE
[GlobalStep - WooCommerce 6.0 RC2][Mac-Safari] For Twenty Twenty One theme, Product Image is displayed small after clicking "Apply coupon" and "Update cart" buttons Cart page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#31427]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For Twenty Twenty One theme, Product Image is displayed small after clicking ”Apply coupon" and "Update cart" buttons Cart page.

### Expected behavior

For Twenty Twenty One theme, Product Image is displayed should remain same after clicking ”Apply coupon" and "Update cart" buttons Cart page.

### Actual behavior

For Twenty Twenty One theme, Product Image is displayed small after clicking ”Apply coupon" and "Update cart" buttons Cart page.

### Steps to reproduce

1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins
3. Complete the Onboarding setup wizard.
4. Select Twenty Twenty One Theme.
5. Add some products.
6. Go to frontend and click on "Add to Cart" and add some Products to cart.
7. Click on "View Cart" button.
8. Update product quantity or add coupon.
9. Click "Update Cart" or "Apply Coupon".
10. Observe that for Twenty Twenty One theme, Product Image is displayed small after clicking ”Apply coupon" and "Update cart" buttons Cart page.

### WordPress Environment

Woocommerce Version : 
WooCommerce 6.0 RC-2
Wordpress version: 5.8.2

PC:
macOS v11.6.1 
Browser: Safari: v15.1

## Video:

https://user-images.githubusercontent.com/41110392/145842242-e9bae7b8-5018-49fb-9e96-4a627fef64be.mp4

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.1
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.26
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 6.11MB
Database Data Size: 4.58MB
Database Index Size: 1.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
nav_menu_item: 5
page: 7
post: 2
product: 18
product_variation: 7
shop_coupon: 1
shop_order: 13

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.21
WooCommerce: by Automattic – 6.0.0-rc.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 53
Oldest: 2021-12-13 13:38:03 +0000
Newest: 2021-12-13 14:50:52 +0000

### Status report information ###

Generated at: 2021-12-13 15:32:36 +00:00
`

</details>

**Comment by zhongruige** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. Just noting that this issue also occurs on WooCommerce 5.9.0 following the steps below:

* Set up a site with WooCommerce 5.9.0 and the Twenty Twenty-one theme installed
* Imported the sample products
* Added a coupon to use for testing
* Opened the store page in Safari (version 15.1)
* I updated the product counts and clicked "Update cart" and noticed the product images shrank:

<img width="1352" alt="Screen Shot 2021-12-13 at 11 10 33" src="https://user-images.githubusercontent.com/71906536/145866167-e2ea7292-7b02-4d32-b361-5310e377a88a.png">

* In a new window, I added a coupon and clicked "Apply coupon" and the product images shrank:

<img width="1316" alt="Screen Shot 2021-12-13 at 11 10 47" src="https://user-images.githubusercontent.com/71906536/145866238-f9320115-9193-4f10-9516-8f9e4f948bbe.png">

Also noting that I tested this on Firefox and Chrome as well and the product thumbnails stayed the same size:

<img width="1458" alt="Screen Shot 2021-12-13 at 11 13 58" src="https://user-images.githubusercontent.com/71906536/145866059-83f66393-30bb-4763-b91c-a22280a63623.png">

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
This no longer happens with the latest version of Safari.
