### ISSUE TITLE
Block Templates enqueue scripts before wp_head registers them.

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#31421]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Just some brief context**, the following bug occurred during the project WooCommerce Store Editing Templates where we are converting WC Core PHP templates into Block Templates (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4926). For V1 we essentially rendered the entire template as a single block represented as a placeholder within the editor (see screenshot below).

![Screenshot 2021-12-11 at 09 44 40](https://user-images.githubusercontent.com/8639742/145672110-c0bc8e85-6391-466d-9bd8-f7c4facadaf0.png)

**The Bug**

During this project we found that users were unable to add variable products to their cart. The cause of this bug was because the code that [enqueues the required scripts](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1710) is running _before_ the code that [registers the required scripts](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-frontend-scripts.php#L169).

This is only an issue for block templates because we are getting the block template html by running `get_the_block_template_html` which enqueues the required scripts, before we run `wp_head()`, which registers the required scripts [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/template-canvas.php#L12). Resulting in a scenario where we are trying to enqueue scripts before they are registered, meaning they don't get included on the frontend.

We were able to implement a fix which meant running the `load_scripts()` method in our block template code, you can see the PR for this [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5346). I am wondering if there is a better way to solve this problem upstream rather than patching it downstream in our template code.

### Expected behavior

Variable products get added to the users cart

### Actual behavior

Adding variable products to the cart returns an error, and they do not get added.

### Steps to reproduce

* Install WooCommerce 6.0.0 (inc beta) or greater.
* Install Woo Blocks. If the fix linked above is included in your Woo Blocks build please comment this out.
* Install and activate Gutenberg plugin and a block theme such as TT1.
* Load variable product on the frontend and try add it to the cart.
* Observe error.

### WordPress Environment

* WordPress 5.8.2 or latest
* WooCommerce 6.0.0 (or beta version)
* WooCommerce Blocks 6.5.0 or greater (If the fix linked in this description is included in your Woo Blocks build please comment this out.)
* Gutenberg latest

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Thanks for creating an issue, @tjcafferkey ! I think you're right that it might be better to solve it upstream. Would you like to take a stab at submitting a PR for it?

**Comment by tjcafferkey** [comment]
Thanks @peterfabian we'll take a look at this as part of our V2 work for this project 🙂

**Comment by tjcafferkey** [comment]
I can no longer reproduce this issue. @gigitux are you able to double check this for me? You'll need to revert to using the LegacyTemplate block (now known as the ClassicTemplate block).

If it's no longer reproducible I may close this issue, also considering most templates now are blockified and we don't actively support the Legacy/ClassicTemplate block.
