### ISSUE TITLE
Textarea in Checkout Form will not be highlighted if empty

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#31436]
### Describe the solution you'd like

Currently when you add custom texarea checkout field. And you set this field as required. Then when you go to checkout form and do not fill this field. After you click the submit button this textarea will not get highlighted red. Because currently woocommerce only look highlight the error if the field type is 'select' / 'input' / 'checkbox'.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this is very helpful, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility). We'll revisit the list of suggestions like this one once our priorities are updated. Don’t be alarmed if you don’t see any activity on this issue for a while.
