### ISSUE TITLE
wc_get_formatted_cart_item_data() product type check not working

### ISSUE THREAD

**Issue by mmilosheski** [woothemes/woocommerce#31434]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

on line 3676 in woocommerce/includes/wc-template-functions.php

where we have:

`if ( $cart_item['data']->is_type( 'variation' ) && is_array( $cart_item['variation'] ) ) {`

it needs to be changed to

`if ( $cart_item['data']->is_type( 'variable' ) && is_array( $cart_item['variation'] ) ) {`

the product type is changed from variation to variable, it's always false, condition is not met and no attributes are shown in cart/checkout/thank-you or order email

### Expected behavior

`if ( $cart_item['data']->is_type( 'variable' ) && is_array( $cart_item['variation'] ) ) {`

changing this to is_type('variable') works fine

### Actual behavior

no product attributes are included

### Steps to reproduce

1. add variable product to the cart
2. go to the cart no attributes listed below product name using `wc_get_formatted_cart_item_data( $cart_item );`

### WordPress Environment

all checks are green :)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @mmilosheski,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Hi, 

There are two options for how variable product appears in the cart: If there are less than 3 (I think) attributes, then the values are part of the product name. If there are more attributes, then the list of attributes is shown. 

Either way, it seems to me that the `$cart_item['data']` is actually a variation, as you can see below from my test just now:
![Screenshot 2022-04-22 at 16 52 14](https://user-images.githubusercontent.com/2207451/164740383-789cfa5d-5331-4553-8232-795dda836d70.png)


So maybe you're using another plugin that changes how this works?
