### ISSUE TITLE
Allow passing in multiple parameters to test commands

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#31449]
**Issue Description:**

We should look into allowing passing in more parameters to test commands, for example:

```
pnpx wc-e2e test:e2e plugins/woocommerce/tests/e2e/specs/smoke-tests/upload-plugin.js woocommerce/facebook-for-woocommerce 'Facebook for WooCommerce'
```

To do this, we'll need to update `wc-e2e.sh` to accept all arguments (currently it only grabs `$2` so we may want to update this to be `$@` instead).

See the discussion in this comment for more details: https://github.com/woocommerce/woocommerce/pull/31400#discussion_r768176394

**Comment by rrennick** [comment]
Closing as `wc-e2e` is no longer being used.
