### ISSUE TITLE
Add config defaults for remaining E2E tests

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31452]
This issue is a follow up to #31428 which adds support for default `config` values. We have some tests which call `config.get` without checking whether the value exists. All of those calls should be updated to provide default values.

**Comment by Luc45** [comment]
@rrennick While working on this issue, I realized that for some values, especially those that are objects or arrays, providing a  default value might be counter-productive. 

Without default values:

```js
const percentageCoupon = config.get( 'coupons.percentage' );
const order = config.get( 'orders.basicPaidOrder' );
const defaultVariableProduct = config.get('products.variable');
const defaultGroupedProduct = config.get('products.grouped');
```

With default values:

```js
const percentageCoupon = config.get( 'coupons.percentage', {
	"code": "20percent",
	"discountType": "percent",
	"amount": "20.00"
  } );
const order = config.get( 'orders.basicPaidOrder',  {
	  "paymentMethod": "cod",
	  "status": "processing",
	  "billing": {
		"firstName": "John",
		"lastName": "Doe",
		"email": "john.doe@example.com"
	  }
	} );
const defaultVariableProduct = config.get('products.variable', {
	  "name": "Variable Product with Three Attributes",
	  "defaultAttributes": [
		{
		  "id": 0,
		  "name": "Size",
		  "option": "Medium"
		},
		{
		  "id": 0,
		  "name": "Colour",
		  "option": "Blue"
		}
	  ],
	  "attributes": [
		{
		  "id": 0,
		  "name": "Colour",
		  "isVisibleOnProductPage": true,
		  "isForVariations": true,
		  "options": [
			"Red",
			"Green",
			"Blue"
		  ],
		  "sortOrder": 0
		},
		{
		  "id": 0,
		  "name": "Size",
		  "isVisibleOnProductPage": true,
		  "isForVariations": true,
		  "options": [
			"Small",
			"Medium",
			"Large"
		  ],
		  "sortOrder": 0
		},
		{
		  "id": 0,
		  "name": "Logo",
		  "isVisibleOnProductPage": true,
		  "isForVariations": true,
		  "options": [
			"Woo",
			"WordPress"
		  ],
		  "sortOrder": 0
		}
	  ]
    });
const defaultGroupedProduct = config.get('products.grouped', {
	  "name": "Grouped Product with Three Children",
	  "groupedProducts": [
		{
		  "name": "Base Unit",
		  "regularPrice": "29.99"
		},
		{
		  "name": "Add-on A",
		  "regularPrice": "11.95"
		},
		{
		  "name": "Add-on B",
		  "regularPrice": "18.97"
		}
	  ]
	});
```

This tends to make the tests confusing, as it might not be obvious at a first sight which one is the source of truth, the test entries or the data JSON entries, especially for someone maintaining the test code in the long run. We also lose the advantage of a central source of truth for the data, if we need to update the data in the original JSON, we'd probably need to update the default values in the tests as well.

Personally, I have a preference that the test code enforces that the data JSON is up-to-date and hard-fail with a meaningful message if it's not, than to try to handle this scenario for every config get.

What do you think?

**Comment by Luc45** [comment]
cc @MrJnrman If you'd like to give your opinion, too? :point_up:

**Comment by rrennick** [comment]
> We also lose the advantage of a central source of truth for the data, if we need to update the data in the original JSON, we'd probably need to update the default values in the tests as well.

@Luc45 `@woocommerce/e2e-core-tests` is published as an `npm` package. Projects that use the package are not required to use the same data as our tests do. For example, the downstream project can use different coupon values so long as the coupon properties calculate correctly. 

The purpose of this issue/PR is to ensure the tests run without entries in a local `default.json` vs to establish a source of truth.

**Comment by Luc45** [comment]
@rrennick Yup, I understood that part. I'm still not 100% convinced this is better than requiring the existence of a JSON with the required data, as we scatter defaults all over the tests, but I acknowledge this is more of a personal preference. I will have a PR open for it by tomorrow.

**Comment by rrennick** [comment]
> I'm still not 100% convinced this is better than requiring the existence of a JSON with the required data, as we scatter defaults all over the tests

The `e2e-core-tests` folder is a package. When it is installed in another project, the `default.json` file that is in this repo does not get installed/copied with it. The reason we are doing this is to allow other projects to use the package without having to manually copy default.json every time there is an update to this package.
