### ISSUE TITLE
"list all products" has stopped working properly

### ISSUE THREAD

**Issue by webtech-jomase** [woothemes/woocommerce#31459]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Today, I understand that after a woocommercer update (I have the plugin update automated), the REST API call under PHP $woocommerce->get('products') has stopped working correctly: it has stopped listing all products. Until today I have been using this call passing as parameters: ('per_page' => 100, 'page' => $ page) without any inconvenience to date but suddenly it has stopped showing certain products. By doing tests I have discovered that by adding the filter "after" if I get it to show these products but: If I go back to the same year of its creation it shows them, if I go back even further it stops showing them. If I remove this filter it stops showing them.

### Expected behavior

That shows all the products using pagination and without applying more filters than page and per_page

### Actual behavior

I only get it to show the missing products from the list by filtering by their specific year with the "after" filter. Obviously the products with a date before this stop being shown. If I request the product by its identifier or by its SKU, the product will be returned to me correctly.

### Steps to reproduce

$page = 1;
$products = [];
$all_products = [];
do{
  try {
    $products = $wc->get('products',array('per_page' => 100, 'page' => $page);
    // $products = $wc->get('products',array('per_page' => 100, 'page' => $page, 'after' => '2017-01-01T00:00:00+00:00'));
  }catch(HttpClientException $e){
    die("Can't get products: $e");
  }
  $all_products = array_merge($all_products,$products);
  $page++;
} while (count($products) > 0);

### WordPress Environment ###

WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.48-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: lc_
Tamaño total de la base de datos: 204.54MB
Tamaño de los datos de la base de datos: 141.58MB
Tamaño del índice de la base de datos: 62.96MB
lc_woocommerce_sessions: Datos: 8.02MB + Índice: 1.02MB + Motor InnoDB
lc_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lc_woocommerce_order_items: Datos: 1.52MB + Índice: 0.38MB + Motor InnoDB
lc_woocommerce_order_itemmeta: Datos: 7.52MB + Índice: 9.03MB + Motor InnoDB
lc_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lc_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_woocommerce_payment_tokenmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
lc_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_410_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_actionscheduler_actions: Datos: 2.39MB + Índice: 1.25MB + Motor InnoDB
lc_actionscheduler_claims: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
lc_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_actionscheduler_logs: Datos: 1.23MB + Índice: 0.72MB + Motor InnoDB
lc_ahm_download_stats: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_ahm_emails: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_auto_updates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_commentmeta: Datos: 0.08MB + Índice: 0.09MB + Motor InnoDB
lc_comments: Datos: 5.52MB + Índice: 3.66MB + Motor InnoDB
lc_groups_capability: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_groups_group: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_groups_group_capability: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_groups_user_capability: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_groups_user_group: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
lc_itsec_bans: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_itsec_dashboard_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_itsec_distributed_storage: Datos: 18.02MB + Índice: 0.02MB + Motor InnoDB
lc_itsec_fingerprints: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_itsec_geolocation_cache: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_itsec_lockouts: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
lc_itsec_logs: Datos: 1.02MB + Índice: 0.11MB + Motor InnoDB
lc_itsec_mutexes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_itsec_opaque_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_itsec_temp: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lc_itsec_user_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_litespeed_avatar: Datos: 0.13MB + Índice: 0.06MB + Motor InnoDB
lc_litespeed_img_optm: Datos: 7.52MB + Índice: 4.02MB + Motor InnoDB
lc_litespeed_img_optming: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lc_litespeed_url: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_litespeed_url_file: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
lc_options: Datos: 7.13MB + Índice: 3.19MB + Motor InnoDB
lc_postmeta: Datos: 55.58MB + Índice: 24.03MB + Motor InnoDB
lc_posts: Datos: 13.45MB + Índice: 3.56MB + Motor InnoDB
lc_rank_math_404_logs: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
lc_rank_math_analytics_gsc: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lc_rank_math_analytics_objects: Datos: 0.39MB + Índice: 0.23MB + Motor InnoDB
lc_rank_math_internal_links: Datos: 0.11MB + Índice: 0.05MB + Motor InnoDB
lc_rank_math_internal_meta: Datos: 0.14MB + Índice: 0.00MB + Motor InnoDB
lc_rank_math_redirections: Datos: 0.14MB + Índice: 0.02MB + Motor InnoDB
lc_rank_math_redirections_cache: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_redirection_404: Datos: 1.02MB + Índice: 0.08MB + Motor InnoDB
lc_redirection_groups: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_redirection_items: Datos: 0.11MB + Índice: 0.13MB + Motor InnoDB
lc_redirection_logs: Datos: 0.16MB + Índice: 0.05MB + Motor InnoDB
lc_termmeta: Datos: 0.14MB + Índice: 0.19MB + Motor InnoDB
lc_terms: Datos: 0.09MB + Índice: 0.09MB + Motor InnoDB
lc_term_relationships: Datos: 0.42MB + Índice: 0.28MB + Motor InnoDB
lc_term_taxonomy: Datos: 0.11MB + Índice: 0.14MB + Motor InnoDB
lc_update_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_usermeta: Datos: 5.52MB + Índice: 7.03MB + Motor InnoDB
lc_users: Datos: 0.31MB + Índice: 0.28MB + Motor InnoDB
lc_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_wc_customer_lookup: Datos: 0.33MB + Índice: 0.23MB + Motor InnoDB
lc_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_wc_order_product_lookup: Datos: 1.52MB + Índice: 0.73MB + Motor InnoDB
lc_wc_order_stats: Datos: 0.47MB + Índice: 0.44MB + Motor InnoDB
lc_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lc_wc_product_meta_lookup: Datos: 0.22MB + Índice: 0.45MB + Motor InnoDB
lc_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lc_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_yith_wcwl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_yith_wcwl_lists: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lc_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lc_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 4382
custom_css: 3
elementor_library: 2
ig_message: 6
nav_menu_item: 70
o-discount: 1
o-list: 1
oembed_cache: 7
page: 18
post: 57
postman_sent_mail: 250
product: 1611
product_variation: 131
revision: 11
shop_coupon: 2
shop_order: 5591
shop_order_refund: 37

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Advanced noCaptcha & invisible Captcha: por WP White Security – 6.1.7
Antispam Bee: por pluginkollektiv – 2.10.0
iThemes Security: por iThemes – 8.0.2
CMB2: por El equipo de CMB2 – 2.9.0
Companion Auto Update: por Papin Schipper – 3.8.3
GDPR Cookie Consent: por WebToffee – 2.0.6
Elementor: por Elementor.com – 3.5.0
Envíos por provincias (ES): por Enrique J. Ros – 2.1.1
Facebook for WooCommerce: por Facebook – 2.6.7
FG PrestaShop to WooCommerce Premium: por Frédéric GILLES – 3.48.1
Kirki Customizer Framework: por David Vongries – 3.1.9
LiteSpeed Cache: por LiteSpeed Technologies – 4.4.5
Loco Translate: por Tim Whitlock – 2.5.5
Meta Generator and Version Info Remover: por Pankaj Kumar Mondal – 13.0
Post SMTP: por Yehuda Hassine – 2.0.23
Redirection: por John Godley – 5.1.3
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.5
Rank Math SEO: por Rank Math – 1.0.78
Simple Banner: por Ryan Petersen – 2.10.6
Simple Like Page Plugin: por topdevs.net – 1.5.1
User Role Editor: por Vladimir Garagulya – 4.60.2
WC - APG Campo NIF/CIF/NIE: por Art Project Group – 1.7
Conditional Discounts for WooCommerce por ORION: por ORION – 2.26
WooCommerce Stripe Gateway: por WooCommerce – 5.9.0
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.11.1
WooCommerce Shortcodes: por WooThemes
Claudio Sanches – 1.0.0

WooCommerce: por Automattic – 6.0.0
410 for WordPress: por Samir Shah – 0.8.7
YITH WooCommerce Compare: por YITH – 2.8.0
YITH WooCommerce Quick View: por YITH – 1.10.0
YITH WooCommerce Wishlist: por YITH – 3.3.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #370185 - /tienda/
Carrito: #2 - /carrito/
Finalizar compra: #3 - /finalizar-compra/
Mi cuenta: #4 - /mi-cuenta/
Términos y condiciones: #6 - /condiciones-uso/

### Theme ###

Name: Alpha Store
Version: 1.4.3
Author URL: http://themes4wp.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Archive Template: Tu tema tiene un archivo woocommerce.php
no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.

Overrides: –

### Action Scheduler ###

Complete: 3.129
Oldest: 2021-11-15 04:33:24 +0100
Newest: 2021-12-16 04:01:43 +0100

Failed: 919
Oldest: 2019-06-15 10:34:33 +0200
Newest: 2019-08-14 14:35:05 +0200

Pending: 4
Oldest: 2021-12-16 04:52:49 +0100
Newest: 2021-12-17 02:36:49 +0100

### Status report information ###

Generated at: 2021-12-16 04:10:26 +01:00

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @webtech-jomase,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

FWIW when I tested in Postman, the "List all products" endpoint is correctly showing 100 items when I used only `page: 1` and `per_page: 100` as parameters like so:
```
{
    "page": 1,
    "per_page": 100
}
```

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by webtech-jomase** [comment]
Thanks rodelgc. In my case, not only does it return the list without problems, also the final count coincides with the number of products listed in the store. The problem is that we are talking about a loss of tens of thousands of products. Now I am going to work to check what is filling in the lost products and then share it. We have realized the problem thanks to having a platform running for years without incident in this regard to date that returns us like 50 products that it suddenly cannot find. If we look for that same ID if they are. If we ask for that ID if it finds them, but in the global list they do not appear by ID, SKU or title. We have also verified that these lost products do appear in the "related" list.

**Comment by vedanshujain** [comment]
hey @webtech-jomase this is essentially just a wrapper on the REST API. Can you make the same API call directly over HTTP and see if the issue persists. This will help us in figuring out whether the issue is in the SDK or in the REST API itself.

**Comment by webtech-jomase** [comment]
Hello @vedanshujain, I have located the trigger for the error in this specific case:
At the time, this particular page was partially migrated from a prestashop solution through a third-party plugin.
Reviewing the entries I found that ALL the products that were excluded outside the lists had been migrated by the aforementioned plugin. Until the day before the publication of this incident, the acquisition of all the products had been as expected, without exceptions and verified every hour since the last 3 years.
I have found that there must have been some modification in the way in which the products are managed since any product that **shares its exact date and time with another is excluded from the total list**.

I have solved this incident by **modifying each of the dates / times avoiding any coincidence** between the more than 400 affected products, verifying that just modifying per second already solves it.

I understand that this is not exactly a woocommerce problem, but I also understand that this new behavior can affect all the entries that cohere by sharing dates with each other. It may be that with a manual insertion of products this situation does not occur but I think it would be good to take into account that there are many plugins that using direct access to the database can be affected.

Perhaps they should take this assumption into account since they have left more than 400 products from a store in production with more than 3000 products, **without any warning or error message**.

I share the solution for this issue in case it can help someone in our same situation but we are going to seriously consider whether to continue using woocommerce seeing the response time from support. We are talking about thousands of dollars of loss and we do not hold the woocommerce team directly responsible for it but we imagine another similar situation and it is unacceptable.

**Comment by barryhughes** [comment]
> I have found that there must have been some modification in the way in which the products are managed since any product that shares its exact date and time with another is excluded from the total list.
> ...
> I have solved this incident by modifying each of the dates / times avoiding any coincidence between the more than 400 affected products, verifying that just modifying per second already solves it.

Apologies if I have missed a key detail, but which date or dates specifically are we discussing? In my local testing, setting the `post_date`, `post_date_gmt`, `post_modified` and `post_modified_gmt` fields to the same value does not cause the problem you noted.

**Comment by webtech-jomase** [comment]
> > I have found that there must have been some modification in the way in which the products are managed since any product that shares its exact date and time with another is excluded from the total list.
> > ...
> > I have solved this incident by modifying each of the dates / times avoiding any coincidence between the more than 400 affected products, verifying that just modifying per second already solves it.
> 
> Apologies if I have missed a key detail, but which date or dates specifically are we discussing? In my local testing, setting the `post_date`, `post_date_gmt`, `post_modified` and `post_modified_gmt` fields to the same value does not cause the problem you noted.

I am sorry for not having responded within a reasonable time but I have suffered an accident that has left me disconnected these last few months.

The answer is post_date, in the database generated with a third-party application for importing products from a prestashop platform, all the products of the old store with the same date (same date, time, seconds) were generated in batch.

As I mentioned, I understand that it is not a common operation or the best way to do it, far from it, but it gives the impression that the product list request from the woocommerce api indexes using the date as a key and overlaps products until it maintains only the last to index.

Also comment that this situation is only reproduced by requesting the total list of products, not with the rest of the REST API calls

**Comment by barryhughes** [comment]
> I am sorry for not having responded within a reasonable time but I have suffered an accident that has left me disconnected these last few months.

I'm sorry to hear that ... and no problem: I'll re-open and try to take a second look (though, it probably won't be before next week).

**Comment by barryhughes** [comment]
> The answer is post_date, in the database generated with a third-party application for importing products from a prestashop platform, all the products of the old store with the same date (same date, time, seconds) were generated in batch.

OK, I tested that scenario last time, and again today, and still cannot replicate. This does not seem to cause products to be skipped.

Would you be able to share a (sanitized) dump of your products, or even a subset that we can use locally to simulate the problem? Otherwise, there unfortunately is not enough information in this report for us to successfully replicate the issue.

**Comment by webtech-jomase** [comment]
Very sorry, the problem was in a production environment and was solved by altering the post_date from the database, applying a different date for each product, generating it by increasing it by one second.

I understand that when replicating the error you tried to apply the same date-hour-minutes-seconds to multiple products. More specifically, as I mentioned above, the store contains more than 3000 products, more than 700 had the same date-hour-minutes-seconds as post_date (imported as I mention with a third-party plugin several years ago, without causing problems until the week when this thread was opened) and when requesting all the products from the woocommerce rest api using php, it did not ignore the 700 but about 400. 

I understand that given the volume it can be complex to reproduce said problem, but unequivocally the problem disappeared after updating these dates, making each one different since it had several copies of the page and the process was replicated to ensure that it was not a coincidence.

**Comment by webtech-jomase** [comment]
I'm going to try to reproduce the problem on a non-production server, but I'm going to have a hard time because I'm still trying to recover the work that was delayed due to my convalescence. 

I would appreciate it if you could tell me what database tables you need to perform an import to achieve it by removing the customer information.

**Comment by barryhughes** [comment]
> I understand that given the volume it can be complex to reproduce said problem

Creating the volume of test data isn't really the problem—we have tools for that [(like this one)](https://github.com/woocommerce/wc-smooth-generator). Modifying a subset (and it can be a subset of any size) so that the post dates are identical, for example, is similarly easy and is very fast.

> I'm going to try to reproduce the problem on a non-production server 

I think that is a good next step: as you can appreciate, there are a lot of factors at play in a production environment and so finding a way to reliably replicate in a clean testing environment using only WooCommerce and a default theme, plus a subset of your catalog data, would be ideal if we're to track this one down.

(Noting that, supposing it can't be replicated in that environment, what we may in fact be looking at is a plugin conflict of some kind that is unique to your production environment and is not necessarily a problem in WooCommerce itself.)

> I would appreciate it if you could tell me what database tables you need

Not knowing how this is happening, makes it a little hard to say. I would certainly start with:

- `wp_posts`
- `wp_postmeta`

We don't necessarily need rows that do not relate to products. If that's insufficient, we'll probably need to broaden the scope. It may also be useful to look at a third-party tool [like this one](https://wordpress.org/plugins/wp-migrate-db-anonymization/) to help migrate data out of one environment and into another, because it comes complete with anonymization features.

**Comment by webtech-jomase** [comment]
The error occurs again on another system, unrelated to the system where the first error described in this thread occurred. Same situation.

**Comment by barryhughes** [comment]
@webtech-jomase do you think the problem might in fact be the same as the one described in the following issue?

https://github.com/woocommerce/woocommerce/issues/34546

**Comment by webtech-jomase** [comment]
> @webtech-jomase do you think the problem might in fact be the same as the one described in the following issue?
> 
> #34546

Yes, it is exactly the same problem on a different server, with products generated entirely from the woocommerce REST API and I can carry out the necessary tests.
