### ISSUE TITLE
[Enhancement]: Option remove "WooCommerce knowledge base" in "Marketing"

### ISSUE THREAD

**Issue by datgausaigon** [woothemes/woocommerce#31462]
### Describe the solution you'd like

Hi,
I request a feature is: Option to remove "WooCommerce knowledge base" in "Marketing".
In current version of WooCommerce we have any solution to disable / remove this? (Hook, hardcode etc)
Thanks.

**Comment by lukecav** [comment]
https://github.com/woocommerce/woocommerce/issues/31430

**Comment by rrennick** [comment]
Closing this as the marketing screen has been refactored.

**Comment by kanlukasz** [comment]
refactored `!=` allow to removal

**Comment by datgausaigon** [comment]
@rrennick Please understand this issue and re-open it.
Thanks ❤️

**Comment by rrennick** [comment]
@datverse Create a new issue with details of the current implementation.
