### ISSUE TITLE
"can create simple virtual product and add it to the cart." fails on retry

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31468]
On the second and third pass of the `can create simple virtual product and add it to the cart` test, the screenshot shows the login screen. Ref p1639688149236300-slack-C01QTJVUCRX. The test may be relying on the merchant logging in during the previous test.

**Comment by lanej0** [comment]
It looks like the issue is/was that the test was failing after the `merchant.logout()` was being called.  Because the login was in the beforeAll() block, it wasn't running when the test was being retried.
