### ISSUE TITLE
Bug in repeated reduction of product inventory

### ISSUE THREAD

**Issue by BirRobotic** [woothemes/woocommerce#31460]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unfortunately, in the order tab, by changing the waiting status to the current payment, instead of executing the order, the inventory reduction request is executed several times.
![Inkedwooo_LI](https://user-images.githubusercontent.com/96230995/146347344-60929476-4d25-439f-8742-07026232cee4.jpg)

 please help me to fix this bug.. 

### Expected behavior

I expect the command to be executed only once, not several times as it reduces inventory by mistake.

### Actual behavior

Unfortunately, in the order tab, by changing the waiting status to the current payment, instead of executing the order, the inventory reduction request is executed several times.
![Inkedwooo_LI](https://user-images.githubusercontent.com/96230995/146347404-9ed41a0b-f8af-4d88-9eb0-1094c3c91766.jpg)
 please help me to fix this bug.. 

### Steps to reproduce

![Inkedwooo_LI](https://user-images.githubusercontent.com/96230995/146347503-f57741d7-d10d-4057-a2de-30a2f57357d3.jpg)

 please help me to fix this bug.. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): x
Site address (URL): x
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 مگابایت
WP Debug Mode: ✔
WP Cron: ✔
Language: fa_IR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.26
PHP Post Max Size: 48 مگابایت
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB-0ubuntu0.20.04.1-log
Max Upload Size: 48 مگابایت
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() ناموفق شد. با ارائه کننده میزبانی وب خود، تماس بگیرید. 403
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
اندازه کل پایگاه داده: 675.49MB
اندازه داده‌های پایگاه داده: 536.02MB
اندازه فهرست پایگاه داده: 139.47MB
wp_woocommerce_sessions: داده: 103.16مگابایت + ایندکس: 4.02مگابایت + انجین InnoDB
wp_woocommerce_api_keys: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_woocommerce_attribute_taxonomies: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_woocommerce_downloadable_product_permissions: داده: 0.02مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_woocommerce_order_items: داده: 1.52مگابایت + ایندکس: 0.33مگابایت + انجین InnoDB
wp_woocommerce_order_itemmeta: داده: 4.52مگابایت + ایندکس: 7.03مگابایت + انجین InnoDB
wp_woocommerce_tax_rates: داده: 0.02مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_woocommerce_tax_rate_locations: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_woocommerce_shipping_zones: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_woocommerce_shipping_zone_locations: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_woocommerce_shipping_zone_methods: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_woocommerce_payment_tokens: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_woocommerce_payment_tokenmeta: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_woocommerce_log: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_actionscheduler_actions: داده: 2.48مگابایت + ایندکس: 1.16مگابایت + انجین InnoDB
wp_actionscheduler_claims: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_actionscheduler_groups: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_actionscheduler_logs: داده: 2.52مگابایت + ایندکس: 0.75مگابایت + انجین InnoDB
wp_commentmeta: داده: 0.31مگابایت + ایندکس: 0.34مگابایت + انجین InnoDB
wp_comments: داده: 6.52مگابایت + ایندکس: 4.86مگابایت + انجین InnoDB
wp_comment_notifier: داده: 0.06مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_cpd_counter: داده: 16.52مگابایت + ایندکس: 6.03مگابایت + انجین InnoDB
wp_dgwt_wcas_index: داده: 1.52مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_dgwt_wcas_invindex_cache: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_dgwt_wcas_invindex_doclist: داده: 1.52مگابایت + ایندکس: 3.03مگابایت + انجین InnoDB
wp_dgwt_wcas_invindex_info: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_dgwt_wcas_invindex_wordlist: داده: 0.22مگابایت + ایندکس: 0.16مگابایت + انجین InnoDB
wp_dgwt_wcas_tax_index: داده: 0.06مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_dgwt_wcas_var_index: داده: 0.13مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_duplicator_pro_entities: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_duplicator_pro_packages: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_EWD_OTP_Customers: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_EWD_OTP_Custom_Fields: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_EWD_OTP_Fields_Meta: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_EWD_OTP_Orders: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_EWD_OTP_Order_Statuses: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_EWD_OTP_Sales_Reps: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_failed_jobs: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_gf_draft_submissions: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_gf_entry: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_gf_entry_meta: داده: 0.06مگابایت + ایندکس: 0.08مگابایت + انجین InnoDB
wp_gf_entry_notes: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_gf_form: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_gf_form_meta: داده: 0.08مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_gf_form_revisions: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_gf_form_view: داده: 0.13مگابایت + ایندکس: 0.11مگابایت + انجین InnoDB
wp_gf_mellat: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_gf_zaringate: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_layerslider: داده: 1.52مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_layerslider_revisions: داده: 0.38مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_lgp_crons: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_lgp_linking: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_lgp_log: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_lgp_posts: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_links: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_litespeed_crawler: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_litespeed_crawler_blacklist: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_litespeed_url: داده: 0.39مگابایت + ایندکس: 0.47مگابایت + انجین InnoDB
wp_litespeed_url_file: داده: 0.02مگابایت + ایندکس: 0.08مگابایت + انجین InnoDB
wp_mailchimp_carts: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_options: داده: 193.50مگابایت + ایندکس: 25.59مگابایت + انجین InnoDB
wp_pmr_status: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_postmeta: داده: 99.48مگابایت + ایندکس: 31.11مگابایت + انجین InnoDB
wp_posts: داده: 40.47مگابایت + ایندکس: 3.64مگابایت + انجین InnoDB
wp_queue: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_rsssl_csp_log: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_smush_dir_images: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_sm_sessions: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_statistics_exclusions: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_statistics_historical: داده: 0.02مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_statistics_pages: داده: 0.17مگابایت + ایندکس: 0.55مگابایت + انجین InnoDB
wp_statistics_search: داده: 4.52مگابایت + ایندکس: 5.55مگابایت + انجین InnoDB
wp_statistics_useronline: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_statistics_visit: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_statistics_visitor: داده: 7.52مگابایت + ایندکس: 15.61مگابایت + انجین InnoDB
wp_statistics_visitor_relationships: داده: 0.23مگابایت + ایندکس: 0.33مگابایت + انجین InnoDB
wp_stock_log: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_termmeta: داده: 0.17مگابایت + ایندکس: 0.23مگابایت + انجین InnoDB
wp_terms: داده: 4.52مگابایت + ایندکس: 7.03مگابایت + انجین InnoDB
wp_term_relationships: داده: 0.36مگابایت + ایندکس: 0.25مگابایت + انجین InnoDB
wp_term_taxonomy: داده: 5.52مگابایت + ایندکس: 3.03مگابایت + انجین InnoDB
wp_usermeta: داده: 4.39مگابایت + ایندکس: 4.70مگابایت + انجین InnoDB
wp_users: داده: 0.19مگابایت + ایندکس: 0.17مگابایت + انجین InnoDB
wp_wc_admin_notes: داده: 0.06مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wc_admin_note_actions: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wc_category_lookup: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wc_customer_lookup: داده: 0.33مگابایت + ایندکس: 0.16مگابایت + انجین InnoDB
wp_wc_download_log: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_wc_order_coupon_lookup: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_wc_order_product_lookup: داده: 1.52مگابایت + ایندکس: 0.88مگابایت + انجین InnoDB
wp_wc_order_stats: داده: 1.52مگابایت + ایندکس: 0.44مگابایت + انجین InnoDB
wp_wc_order_tax_lookup: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_wc_product_meta_lookup: داده: 0.19مگابایت + ایندکس: 0.31مگابایت + انجین InnoDB
wp_wc_rate_limits: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wc_reserved_stock: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wc_tax_rate_classes: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wc_webhooks: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wfblockediplog: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfblocks7: داده: 0.02مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_wfconfig: داده: 0.47مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfcrawlers: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wffilechanges: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wffilemods: داده: 5.52مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfhits: داده: 0.16مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_wfhoover: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wfissues: داده: 0.05مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_wfknownfilelist: داده: 2.52مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wflivetraffichuman: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wflocs: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wflogins: داده: 0.27مگابایت + ایندکس: 0.13مگابایت + انجین InnoDB
wp_wfls_2fa_secrets: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_wfls_settings: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfnotifications: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfpendingissues: داده: 0.02مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_wfreversecache: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_wfsnipcache: داده: 0.02مگابایت + ایندکس: 0.05مگابایت + انجین InnoDB
wp_wfstatus: داده: 0.16مگابایت + ایندکس: 0.09مگابایت + انجین InnoDB
wp_wftrafficrates: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_woocommerce_bundled_itemmeta: داده: 0.09مگابایت + ایندکس: 0.14مگابایت + انجین InnoDB
wp_woocommerce_bundled_items: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_woocommerce_ir: داده: 0.02مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB
wp_yoast_indexable: داده: 12.52مگابایت + ایندکس: 6.53مگابایت + انجین InnoDB
wp_yoast_indexable_hierarchy: داده: 1.52مگابایت + ایندکس: 2.17مگابایت + انجین InnoDB
wp_yoast_migrations: داده: 0.02مگابایت + ایندکس: 0.02مگابایت + انجین InnoDB
wp_yoast_primary_term: داده: 0.09مگابایت + ایندکس: 0.06مگابایت + انجین InnoDB
wp_yoast_prominent_words: داده: 0.02مگابایت + ایندکس: 0.03مگابایت + انجین InnoDB
wp_yoast_seo_links: داده: 2.42مگابایت + ایندکس: 0.72مگابایت + انجین InnoDB
wp_yoast_seo_meta: داده: 0.41مگابایت + ایندکس: 0.00مگابایت + انجین InnoDB

### Post Type Counts ###

aam_policy: 1
attachment: 5357
avia_framework_post: 14
gf_live_preview: 2
nav_menu_item: 50
oembed_cache: 27
page: 100
portfolio: 36
post: 22
product: 898
product_variation: 148
revision: 10
schema: 2
shop_order: 3411
shop_order_refund: 135
ticket: 227
ticket_history: 690
ticket_log: 13
ticket_reply: 483
wbcr-snippets: 19
wc_afrsm: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

درگاه پرداخت بهپرداخت ملت افزونه ووکامرس: توسط ووکامرس فارسی – 5.5
افزونه مدیریت و گزارش موجودی محصولات ووکامرس: توسط ووکامرس فارسی – 2.2.29
Add IDs to Header Tags with uniqid: توسط Hadi Ahrovani – 1.0
Advanced Access Manager: توسط Vasyl Martyniuk <vasyl@vasyltech.com> – 6.8.0
FiboSearch - AJAX Search for WooCommerce (Pro): توسط FiboSearch Team – 1.14.1
Aparat: توسط Nima Saberi – 1.7.1
افزونه اضافه کردن امکانات به ووکامرس Booster Plus: توسط ووکامرس فارسی – 5.3.5
Lightweight Subscribe To Comments: توسط Isabel Castillo – 1.5.8
Goftino: توسط Ali Rahimi – 1.4
Woody code snippets (PHP snippets | Insert PHP): توسط Creative Motion
Will Bontrager Software
LLC  – 2.4.2

کش LiteSpeed: توسط LiteSpeed Technologies – 4.4.5
افزونه حمل و نقل ووکامرس: توسط Mahdi Yousefi [MahdiY] – 3.0.3
ووکامرس فارسی: توسط ووکامرس فارسی – 5.8.0
تغییرنام رسانه فونیکس: توسط crossi72 – 3.4.8
SSL واقعاً ساده: توسط افزونه های واقعا ساده – 5.2.1
بازسازی تصاویر بندانگشتی: توسط Alex Mills – 3.1.5
WooCommerce Split Orders: توسط Vibe Agency – 1.4.0
ویرایشگر پیشرفته (TinyMCE Advanced): توسط اتوماتیک – 5.6.0
درگاه پرداخت آیدی پی برای ووکامرس: توسط آیدی پی – 2.1.2
WooCommerce Expand Tabs: توسط Diana Burduja – 1.12
فاکتور حرفه ای ووکامرس: توسط سید رضا صالحی – 10.5.1
بسته های محصول WooCommerce: توسط بیر رباتیک – 6.7.7
WooCommerce Quick Buy: توسط Varun Sridharan – 1.9
ووکامرس: توسط اتوماتیک – 6.0.0
Yoast SEO Premium: توسط 20script – 15.0
WP External Links: توسط WebFactory Ltd – 2.50
WPS Hide Login: توسط WPServeur
NicolasKulka
wpformation – 1.9.2

سئو: ووکامرس: توسط پرشین اسکریپت – 13.5
Custom Product Tabs for WooCommerce: توسط YIKES
Inc. – 1.7.1

YITH WooCommerce Customize My Account Page: توسط پرشین اسکریپت – 3.1.0
افزونه پرداخت امن زرین‌پال برای ووکامرس: توسط Masoud Amini 
alireza yousefi – 4.8.1

### Inactive Plugins (10) ###

Awesome Support: توسط Awesome Support Team – 5.8.0
Awesome Support: Custom Status: توسط Awesome Support – 1.1.1
Awesome Support: Front-end Ticket Buttons: توسط Awesome Support – 1.0.0
Awesome Support: WooCommerce: توسط Awesome Support Team – 1.5.0
Duplicator Pro: توسط میهن اسکریپت – 3.8.8.1
Epnb Featured Image Widget: توسط EPNB – 1.0
Really Simple SSL pro: توسط پرشین اسکریپت – 4.0.5
Smush Pro: توسط WPMU DEV – 3.8.1
Woocommerce Invoice Pro: توسط S.Reza Salehi – 10.9.0
WP Google Search: توسط WebshopLogic – 1.0.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

پایگاه فروشگاه: #4133 - /shop/
سبد خرید: #266 - /cart/
پرداخت: #267 - /checkout/
حساب کاربری من: #268 - /my-account/
شرایط و ضوابط: #610 - /terms-of-service/

### Theme ###

Name: Enfold
Version: 4.8.6.2
Author URL: https://kriesi.at
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس روی قالب والد هستید پیشنهاد می کنیم از قالب فرزند استفاده کنید. ببینید: چگونه یک قالب فرزند بسازیم
WooCommerce Support: ✔

### Templates ###

Overrides: enfold/woocommerce/cart/cart-shipping.php
enfold/woocommerce/cart/cart-totals.php
enfold/woocommerce/cart/cart.php
enfold/woocommerce/checkout/form-billing.php
enfold/woocommerce/checkout/form-pay.php
enfold/woocommerce/checkout/payment.php
enfold/woocommerce/checkout/review-order.php
enfold/woocommerce/myaccount/dashboard.php
enfold/woocommerce/myaccount/downloads.php
enfold/woocommerce/myaccount/form-login.php
enfold/woocommerce/myaccount/form-lost-password.php
enfold/woocommerce/myaccount/my-address.php
enfold/woocommerce/myaccount/orders.php
enfold/woocommerce/myaccount/view-order.php
enfold/woocommerce/order/order-again.php
enfold/woocommerce/order/order-details.php
enfold/woocommerce/single-product/related.php
enfold/woocommerce/single-product/up-sells.php
enfold/woocommerce/single-product-reviews.php

### Product Bundles ###

Database Version: 6.7.7
Loopback Test: ❌ Loopback test failed.
Template Overrides: –

### Action Scheduler ###

لغو شده: 1
Oldest: 2021-11-16 11:50:52 +0330
Newest: 2021-11-16 11:50:52 +0330

تکمیل شده: 3,147
Oldest: 2021-11-15 12:43:00 +0330
Newest: 2021-12-16 12:30:32 +0330

ناموفق: 4
Oldest: 2020-09-20 14:40:53 +0430
Newest: 2021-02-23 01:18:19 +0330

در انتظار: 1
Oldest: 2021-12-16 23:00:00 +0330
Newest: 2021-12-16 23:00:00 +0330

### Status report information ###

Generated at: 2021-12-16 12:34:21 +03:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @BirRobotic,

Thank you for submitting the issue. Even though you provided screenshots and the status report, you didn’t fill out the portion for the steps to replicate this issue.
Also, if you could provide us the System Status Report in english, that would be of great help as well.
Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
