### ISSUE TITLE
WooCoomerce Emails are Not Responsive IN RTL WP V5.8.2

### ISSUE THREAD

**Issue by emakx** [woothemes/woocommerce#31478]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I Contacted WooComerce Support and they confirmed that this is a bug.

WooCommerce Email is not longer Responsive in RTL Website.

I installed a fresh installation of WP 5.8.2 and the latest version of WooCommerce, Also I used the default WordPress theme, and I did not use any other plugins.

– I sit the language to be Arabic which is RTL Language.

I have created a sample test and create new order
you can check yourself, https://shpabeek.com/emails/product/sample-product/

The New Order EMAIL is NOT RESPONSIVE in Mobile (Gmail in my case),

This is a Serious Problem need to be fixed.

Kind Regards

### Expected behavior

To have Responsive Email In RTL Languages websites

### Actual behavior

emails get cropped in mobile in RTL language, please see this screenshot:
https://snipboard.io/EPHShC.jpg

### Steps to reproduce

You can simply check the problem your self, by this test product, i set the payment to be Cash on delivery just so you can get the order email and see the problem: https://shpabeek.com/emails/product/sample-product/ 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shpabeek.com/emails
Site address (URL): https://shpabeek.com/emails
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 ميغابايت
WP Debug Mode: –
WP Cron: ✔
Language: ar
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.26
PHP Post Max Size: 128 ميغابايت
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.36-cll-lve
Max Upload Size: 128 ميغابايت
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp1t_
إجمالي حجم قاعدة البيانات: 1.75MB
حجم بيانات قاعدة البيانات: 1.54MB
حجم فهرس قاعدة البيانات: 0.21MB
wp1t_woocommerce_sessions: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_api_keys: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_attribute_taxonomies: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_downloadable_product_permissions: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_order_items: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_order_itemmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_tax_rates: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_tax_rate_locations: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zones: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zone_locations: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zone_methods: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_payment_tokens: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_payment_tokenmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_log: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_actionscheduler_actions: البيانات: 0.01 م.ب. + الفهرس: 0.02 م.ب. + المحرك MyISAM
wp1t_actionscheduler_claims: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_actionscheduler_groups: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_actionscheduler_logs: البيانات: 0.01 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_commentmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_comments: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_links: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_options: البيانات: 1.45 م.ب. + الفهرس: 0.04 م.ب. + المحرك MyISAM
wp1t_postmeta: البيانات: 0.02 م.ب. + الفهرس: 0.02 م.ب. + المحرك MyISAM
wp1t_posts: البيانات: 0.02 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_termmeta: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_terms: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_term_relationships: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_term_taxonomy: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_usermeta: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_users: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_admin_notes: البيانات: 0.02 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_admin_note_actions: البيانات: 0.01 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_category_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_customer_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_download_log: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_order_coupon_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_order_product_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_order_stats: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_order_tax_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_product_meta_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_rate_limits: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_reserved_stock: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_tax_rate_classes: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_webhooks: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 2
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: بواسطة Automattic – 6.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

المتجر: #6 - /shop/
السلة: #7 - /cart/
إتمام الطلب: #8 - /checkout/
لوحة حسابي: #9 - /my-account/
الشروط والأحكام: ❌ الصفحة لم تحدد

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://ar.wordpress.org/
Child Theme: ❌ – إذا كنت تقوم بتعديل WooCommerce على قالب أب، لم تقم ببنائه شخصيًا، نحن نوصي بإستخدام قالب إبن. شاهد: كيفية إنشاء قالب إبن
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

(مُكتمل): 25
Oldest: 2021-12-16 13:20:13 +0000
Newest: 2021-12-19 06:34:58 +0000

### Status report information ###

Generated at: 2021-12-19 06:35:06 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @emakx ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end for Arabic language using WooCommerce 6.0.0 version. 

Please find below screenshot for reference :

![#31478](https://user-images.githubusercontent.com/94531721/146733188-25b0dc50-023d-4c1d-9e2f-3a80065b692e.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by emakx** [comment]
Hello,

Any Updates on This?

Regards

**Comment by rotem657** [comment]
Hi,
I have the same problem with Hebrew in the RTL emails.
![WhatsApp Image 2022-02-27 at 16 03 43](https://user-images.githubusercontent.com/63625134/155885625-829efe8d-ca5d-4f34-aeb1-aa81d73959ee.jpeg)

**Comment by emakx** [comment]
Any Eta for this to be solved? its more than 3 months now? @WordCommerce

**Comment by rotem657** [comment]
@ObliviousHarmony Hey, Are there any updates about this issue?

**Comment by ObliviousHarmony** [comment]
Hello @rotem657, this issue is awaiting prioritization from the owning development team.

**Comment by izonnn** [comment]
Also facing this issue no responsive emails on phone, 
Please update when fixing/starting to solve this issue. 

Tnx!

**Comment by wassem** [comment]
hello this problem is still there hoping someone find solution for this

**Comment by emakx** [comment]
@ObliviousHarmony  This is taking too much time, WooCommerce is a worldwide Plugin. and this is a serious problem needs to be fixed.

Fixing this is much more important than, adding new features !!!

**Comment by izonnn** [comment]
@wassem 
@emakx  
https://github.com/woocommerce/woocommerce/issues/25076#issuecomment-718809528
Check this out, a workaround I found and it's working for me.

**Comment by emakx** [comment]
I don't want to do this for every store I will install.  This is a serious problem that needs to be fixed. this won't take more than 1 day form WooCommerce team

**Comment by izonnn** [comment]
I agree with you...

**Comment by codeproblemsolver** [comment]
why this is still not taking care of ? no one care ? WooCommerce team should take 2 hours work

**Comment by emakx** [comment]
Is there any ETA on this?

**Comment by ho30hero** [comment]
Hi
I also have the same problem with the latest vesion of every thing in server, wp and android mobile phone (samsung fe).

**Comment by JoMedia2017** [comment]
Hey all, would like to share with all of you my Dirty Workaround (CSS hack) for this thing, as I was facing this same issue with my RTL (hebrew) website

**NOTE: it might not be sufficient for all, as it depends on the actual content of the email. on my emails (which are the native WooCommerce templates), I've found that the elements which causes the overflow are the email and phone number on shipping and billing address at the bottom of the email. so if you put there a longer email address \ phone number, this solution may still not get everything inside the viewport.**

So first - you should copy 3 files from woocommerce/templates/emails into your child-theme/woocommerce/emails/ folder ->
1. email-header.php
2. email-footer,php
3. email-styles.php

A. in email-header -
1/ add this line inside the `<head>` tag (right below the opening html tag) -
`<meta content="width=device-width, initial-scale=1.0" name="viewport">`
2/ in `<table>` tag (appears twice in this file) - find ' width="600" ' and change it to width="100%", then add inside those `<table>` tags ' style="max-width:600px" '

B. in email-footer -
1/ same thing as A.2 above - find the `<table>` tag, change width=600 to width=100% and add style="max-width:600px" inside the `<table>` tag

C. in email-styles -
1/ find this line -
#body_content table td {
	padding: 48px 48px 32px;
}

change it to
#body_content table td {
	padding: 48px 24px 32px;
}

or you can change this to whatever value you want

2/ 
#header_wrapper {
	padding: 36px 48px;
	display: block;
}

same here - change the 48px to 24px

It's a dirty workaround I know, not working perfectly as the table body background still overflows, but at least all the content is inside the viewport

hope this helps guys!

Cheers and Salute

**Comment by ho30hero** [comment]
Hello, @ObliviousHarmony and Woo Staff and others! :)
We don't see any changes yet. Please Do something about this.
It is really a bad thing for Woocommerce store managers and also for customers.
Regards

**Comment by emakx** [comment]
@barryhughes 
why this is still not taking care of ? no one care ? WooCommerce team should take 2 hours work

its over a year now,

**Comment by peterfabian** [comment]
I'm going to have a look at this. Apologies for the delay.

**Comment by lecmo** [comment]
Hi Everyone,

I am having the same issue that you guys having related to the RTL emails.

I am using Arabic Language on my website and order Emails are not coming Responisve.

Please help me to fix this if anyone fixed that issue before let me know.

Thanks

**Comment by JoMedia2017** [comment]
May want to check my solution provided on this thread, more of a dirty
workaround rather than a solution, but does the work most of the time

and could give you a clue about how to approach the issue and how to fix it

cheers

**Comment by prnvrna** [comment]
Update requested on this issue here 5712577-zen

**Comment by lecmo** [comment]
what do you mean by this Update requested on this issue here 5712577-zen @prnvrna

**Comment by Moj2358** [comment]
Hello all 

I am having the same problem and it's really annoying. Could you please at least provide a quick fix till the bug is fixed completely in the next update or something ?! 

Come on, it's been almost a year now !! @peterfabian @ObliviousHarmony Would you please help?

**Comment by hamdy94** [comment]
**Unbelievable, this problem has been going on for a year and I'm still facing it !!!!
Tell us you can't solve it and we will go to any other platform that respects its users**

**Comment by hamdy94** [comment]
any one here !!!!

**Comment by hamdy94** [comment]
@peterfabian @ObliviousHarmony !!!!

**Comment by hamdy94** [comment]
How will I make a store with this serious problem!!
Email is one of the basics of any store
Help us 
@peterfabian @ObliviousHarmony

**Comment by vadimprt** [comment]
Hi,
Issue still happen in WooCommerce version 7.3.0 with native RTL emails.

Is this bug fixed?

**Comment by ho30hero** [comment]
I guess they plan to fix this in 2030 :)) Please fix this old issue. 
@emulsion-io @psealock @lsinger

**Comment by barryhughes** [comment]
Apologies for the delay, here. The fix is milestoned for 7.4.0.

**Comment by vadimprt** [comment]
@barryhughes thanks, do you know when it will be released?

**Comment by barryhughes** [comment]
Hi @vadimprt: we currently plan to [release 7.4.0 on Feb 14](https://developer.woocommerce.com/2023/01/30/woocommerce-7-4-beta-2/).

**Comment by yarlevi** [comment]
this is still happening in 7.4.0
![image](https://user-images.githubusercontent.com/13298087/220543261-7cc86974-1944-4dec-a63d-c7028b4f81bc.png)

**Comment by barryhughes** [comment]
Hi @yarlevi,

Sorry to hear you are still experiencing difficulties.

In general, when an issue or pull request (like this one) has been closed, it is best to [create a new issue](https://github.com/woocommerce/woocommerce/issues/new/choose) if you want to flag further problems—this helps to ensure it is seen and triaged by the right team.

I did try to replicate this on a fresh testing site running WooCommerce 7.4.0, with the language set to `he_IL`—but the emails worked well for me, including when using Gmail via a desktop web browser and with the Gmail mobile app for Android. So, we'll need more information to be able to solve this.

- Again, please start by creating a new issue [(bug report)](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml).
- Please do take the time to follow the self-service and basic troubleshooting steps linked to from the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml).
- It would be especially useful to confirm which email client you are using when you see the problem, and if your theme has any template overrides in place that might be causing this.

Thanks.
