### ISSUE TITLE
Updating to 6.0.0 caused php error

### ISSUE THREAD

**Issue by Nick776** [woothemes/woocommerce#31473]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi There!

We just updated to WC 6.0.0 on our test page and received the following error:

======
Creating default object from empty value

wp-content/themes/mh-magazine/includes/updater/theme-updater-class.php:120
EDD_Theme_Updater->theme_update_transient()
wp-includes/class-wp-hook.php:305
apply_filters(‘site_transient_update_themes’)
wp-includes/option.php:1945
get_site_transient()
wp-includes/update.php:790
wp_get_update_data()
wp-admin/menu.php:33

PHP Warning: Creating default object from empty value in /kunden/xx_xx/webseiten/testseite.hello-world.net/wp-content/themes/mh-magazine/includes/updater/theme-updater-class.php on line 120

thnx for helping
Nick

### Expected behavior

No error message

### Actual behavior

Nach dem Update auf version 6.0.0 trat der oben beschriebene Fehler im WordPress Backend auf und wurde durch Query Monitor ausgegeben. Zur gleichen Zeit wurde der Fehler im php errorlog auf dem server dokumentiert. Es erfolgten in Summe 4 Einträge ins php errorlog.

### Steps to reproduce

We set up the test environment a total of three times and activated the update to version 6.0.0. The result was the error message described above every time
![2021-12-17_13h57_08](https://user-images.githubusercontent.com/43967959/146547935-ec9c571f-0ed6-430a-9c8a-6eb2a2eee1f1.png)
.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://testseite.hello-world.net
Site address (URL): http://testseite.hello-world.net
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.25
PHP Post Max Size: 75 MB
PHP Time Limit: 60
PHP Max Input Vars: 3000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 10.4.22-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 271.09MB
Datenbank-Datengröße: 192.90MB
Datenbank-Indexgröße: 78.19MB
wp_2_woocommerce_sessions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_actions: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_2_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_actionscheduler_logs: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_2_adtribes_my_conversions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_alm: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_blocked_content_types: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_borlabs_cookie_log: Daten: 16.55MB + Index: 40.63MB + Engine MyISAM
wp_2_bwg_album: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_album_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_gallery: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_comment: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_rate: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_image_tag: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_option: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_shortcode: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_bwg_theme: Daten: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_2_commentmeta: Daten: 0.34MB + Index: 0.12MB + Engine MyISAM
wp_2_comments: Daten: 0.65MB + Index: 0.10MB + Engine MyISAM
wp_2_duplicator_pro_entities: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_duplicator_pro_packages: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ewwwio_images: Daten: 20.68MB + Index: 4.27MB + Engine MyISAM
wp_2_ewwwio_queue: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider: Daten: 0.27MB + Index: 0.00MB + Engine MyISAM
wp_2_layerslider_revisions: Daten: 12.26MB + Index: 0.00MB + Engine MyISAM
wp_2_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_lockdowns: Daten: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_2_login_fails: Daten: 1.60MB + Index: 0.56MB + Engine MyISAM
wp_2_ms_snippets: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_pictures: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 2.47MB + Index: 0.11MB + Engine MyISAM
wp_2_postmeta: Daten: 41.62MB + Index: 20.09MB + Engine MyISAM
wp_2_posts: Daten: 75.54MB + Index: 5.67MB + Engine MyISAM
wp_2_reorder_post_rel: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_snippets: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_subscribe_reloaded_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_termmeta: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_2_terms: Daten: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_2_term_relationships: Daten: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_2_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_2_tm_taskmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_tm_tasks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_categories: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_galleries: Daten: 0.92MB + Index: 0.00MB + Engine MyISAM
wp_2_unitegallery_items: Daten: 0.98MB + Index: 0.03MB + Engine MyISAM
wp_2_usermeta: Daten: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_2_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_admin_notes: Daten: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_admin_note_actions: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_category_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_comments_subscription: Daten: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_2_wc_customer_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_download_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_feedback_forms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_follow_users: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_product_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_stats: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_phrases: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_2_wc_product_meta_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_reserved_stock: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wc_users_rated: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_users_voted: Daten: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_2_wc_webhooks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfblockediplog: Daten: 0.13MB + Index: 0.09MB + Engine MyISAM
wp_2_wfblocks7: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfconfig: Daten: 0.39MB + Index: 0.02MB + Engine MyISAM
wp_2_wfcrawlers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilechanges: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wffilemods: Daten: 1.56MB + Index: 0.33MB + Engine MyISAM
wp_2_wfhits: Daten: 0.67MB + Index: 0.14MB + Engine MyISAM
wp_2_wfhoover: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfissues: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wfknownfilelist: Daten: 0.81MB + Index: 0.10MB + Engine MyISAM
wp_2_wflivetraffichuman: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflocs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wflogins: Daten: 0.11MB + Index: 0.03MB + Engine MyISAM
wp_2_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wfnotifications: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfpendingissues: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfreversecache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfsnipcache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wfstatus: Daten: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_2_wftrafficrates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_comments_subscription: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wpc_phrases: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_wpc_users_voted: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_2_wplc_chat_msgs: Daten: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_ratings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_sessions: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_chat_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_custom_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_departments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_offline_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_conversions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wplc_roi_goals: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Daten: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_2_wprm_analytics: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wprm_ratings: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_indexable: Daten: 10.83MB + Index: 3.94MB + Engine MyISAM
wp_2_yoast_indexable_hierarchy: Daten: 0.33MB + Index: 1.04MB + Engine MyISAM
wp_2_yoast_migrations: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_primary_term: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_2_yoast_prominent_words: Daten: 0.05MB + Index: 0.15MB + Engine MyISAM
wp_2_yoast_seo_links: Daten: 0.54MB + Index: 0.10MB + Engine MyISAM
wp_2_yoast_seo_meta: Daten: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

amn_smtp: 2
attachment: 2663
custom_css: 2
nav_menu_item: 28
oembed_cache: 38
page: 12
popup: 1
popup_theme: 6
post: 110
product: 50
r3d: 25
revision: 4534
schema: 2
somdn_tracked: 42914
tablepress_table: 34
wpcf7_contact_form: 2
wpdiscuz_form: 3
wprm_recipe: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Query Monitor: von John Blackbourn – 3.7.1
Borlabs Cookie - Cookie Opt-in: von Benjamin A. Bornschein
Borlabs – 1.9.9

Classic Editor: von WordPress-Mitwirkende – 1.6.2
Classic Widgets: von WordPress-Mitwirkende – 0.2
Code Snippets: von Code Snippets Pro – 2.14.3
Contact Form 7 Extension For Mailchimp: von Renzo Johnson – 0.5.52
Contact Form 7: von Takayuki Miyoshi – 5.5.3
EWWW Image Optimizer: von Exactly WWW – 6.3.0
Lightweight Social Icons: von Thomas Usborne – 1.1
Post Types Order: von Nsp Code – 1.9.5.7
Product Filter for WooCommerce: von XforWooCommerce – 8.2.1
Real3D Flipbook: von creativeinteractivemedia – 3.31.2
Shortcodes Ultimate: von Vladimir Anokhin – 5.11.1
Free Downloads WooCommerce Pro: von Square One Media – 3.4.0
TablePress: von Tobias Bäthge – 1.14
Unite Gallery: von Valiano – 1.7.53
UpdraftPlus – Sichern/Wiederherstellen: von UpdraftPlus.Com
DavidAnderson – 2.16.66.25

WooCommerce: von Automattic – 6.0.0
WP Mail SMTP: von WPForms – 3.2.1
WP Rezept Maker: von Bootstrapped Ventures – 7.7.2
WP STAGING PRO: von WP-STAGING – 4.1.2
wpDiscuz: von gVectors Team – 7.3.9

### Inactive Plugins (3) ###

Yoast SEO: von Team Yoast – 17.8
Yoast SEO: WooCommerce: von Team Yoast – 14.5
Yoast SEO Premium: von Team Yoast – 17.8

### Must Use Plugins (1) ###

WP STAGING Optimizer: von René Hermenau – 1.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #3312 - /jakobswegreisen-shop/
Warenkorb: #3314 - /warenkorb/
Kasse: #3316 - /kasse/
Mein Konto: #3318 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: MH Magazine Child Theme
Version: 1.0.0
Author URL: https://www.mhthemes.com/
Child Theme: ✔
Parent Theme Name: MH Magazine
Parent Theme Version: 3.9.9
Parent Theme Author URL: https://mhthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mh-magazine-child/woocommerce/single-product-reviews.php

### Action Scheduler ###

Abgeschlossen: 63
Oldest: 2021-11-19 08:38:04 +0100
Newest: 2021-12-17 13:58:38 +0100

Ausstehend: 2
Oldest: 2021-12-17 13:58:39 +0100
Newest: 2021-12-20 13:05:05 +0100

### Status report information ###

Generated at: 2021-12-17 13:58:39 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Hi, thanks for reporting! This error relates to your theme, please contact your theme provider, they will most likely need to release an update for the theme.
