### ISSUE TITLE
Product review page in WooCommerce Core

### ISSUE THREAD

**Issue by tturton-godaddy** [woothemes/woocommerce#31470]
Proposed by GoDaddy – Managed WordPress Ecommerce Product Team

### Overview
Product reviews should have a dedicated location within WooCommerce. Novice users have difficulty discovering and managing product reviews since it’s not clear they’re managed alongside site comments via WordPress > Comments.

### Justification
Separation of blog comments and product reviews in WooCommerce Core makes it easier for users to discover, monitor, and moderate reviews.

- Users will be able to find a dedicated list of product reviews for easier discovery and review
- Users will be able to moderate and publish reviews more easily, improving sales and store growth

### Proposed implementation
We propose creating a Reviews section within WooCommerce. The implementation includes the following:

- Product reviews will be accessible via the admin menu at Products > Reviews
- A notification icon on the sub-menu item will indicate the number of pending reviews
- The page layout will be similar to the Comments page, with the following differences:
    - The page will be titled Reviews
    - The Comment column will be renamed to Review
    - A new column named Type will indicate whether the entry is a review or comment
    - The review’s star rating will be displayed on the review entry
    - The search button will be renamed to Search reviews
    - Users will be able to view the list by status (All, Pending, Approved, Spam, Trash only)
- The functionality will remain the same as the Comments page:
    - Users will be able to apply the same moderation actions (e.g., approve, edit, mark as spam, etc.)
    - Users will be able to filter, search, and apply bulk actions to the list
- Developers will be able to use filters to replace and modify the page’s content and layout

**Comment by HowdyMcGee** [comment]
Moving away from comments to a dedicated reviews page is a great enhancement. At least adding a "Reviews" subpage under WooCommerce linking to "edit-comments.php?comment_type=review" could add some clarity for users.

**Comment by rodelgc** [comment]
Hi @tturton-godaddy,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.

**Comment by bekarice-godaddy** [comment]
heya @rodelgc we are happy to tackle this and look forward to it! just want to be sure we capture any requirements or requests for how to implement before we start hacking away at code. Is there anything we need to be mindful of to have the PR accepted?

**Comment by bekarice-godaddy** [comment]
@rodelgc howdy! returning to this convo now :) We would love to contribute this project to core from the GoDaddy / SkyVerge team. Do we need a PRD or any other docs to ensure it's accepted before we invest development time?

**Comment by rodelgc** [comment]
Hi @bekarice-godaddy, apologies for the delayed response. I'm now adding a `needs developer feedback` to get you in touch with the Core team shortly.

**Comment by peterfabian** [comment]
Thanks for the proposal, sounds like a good improvement. We're discussing this with our product folks and will be back shortly.

**Comment by peterfabian** [comment]
Hi again. Thanks again for proposing this feature, I think this change makes sense and although it isn't among our current priorities, we'd be happy to discuss it and review PRs related to this change. 

> The page titled Reviews
> ...
> A new column named Type will indicate whether the entry is a review or comment

This bit is somewhat confusing to me. Will this page only list reviews or also other WC-related comments?

I wonder how you plan to tackle backward compatibility since I suppose there is a possibility that some extensions are using filters/actions on the Comments page to modify the current behavior for WC? 

This also got me thinking about how merchants actually use the reviews? Do they just care about them as a stream of reviews that they need to approve/reject or are there some other workflows they use that might be useful to capture? Maybe they want to list reviews per product or something similar?

So yeah, in short, a PRD or a short design doc might be useful to bounce ideas before diving into the implementation. What do you think?

**Comment by bekarice-godaddy** [comment]
Hey @peterfabian 

> This bit is somewhat confusing to me. Will this page only list reviews or also other WC-related comments?

Customers can review products, but then site admins can also leave a comment in reply to their review. So, "reviews" really end up being both reviews and comments. This clarifies when a "comment" is a review or a response to a review (and we'd let users filter the list). We could consider changing that behavior, but merchants often find value in being able to add a reply to show public engagement.

> I wonder how you plan to tackle backward compatibility since I suppose there is a possibility that some extensions are using filters/actions on the Comments page to modify the current behavior for WC?

We felt that we shouldn't assume customizations to the comments list table are specific to Woo or product reviews -- given the primary JTBD of that table now is **comments**, not reviews, customizations should be assumed to be related to comments.

Without having defined ways of interacting with reviews and lists of reviews, there's no possible way for us to actually maintain 100% BC with every possible customization. We don't think this should stop us from making the change though, and would do this as a _presentational_ change in the first iteration, before considering migrating any backing data stores.

> This also got me thinking about how merchants actually use the reviews? Do they just care about them as a stream of reviews that they need to approve/reject or are there some other workflows they use that might be useful to capture? Maybe they want to list reviews per product or something similar?

We were thinking of just getting reviews as a proper object in a first iteration, so that merchants can review them and discover the reviews feature more easily. This would also show star rating, which they can't see while moderating in the backend now. From a dev perspective, it gives you an easy way to interact with only reviews as well, modifying that list table or enriching reviews -- which isn't feasible now while they're all lumped into the comments table (and being sure we have proper standardized helpers / hooks to make this happen).

We did intend to add user-facing filters - "Users will be able to filter, search, and apply bulk actions to the list" - so to clarify: being able to filter the list of reviews by product would be included. We'd have filters for: review type, product, status, as well as a search that includes reviewer name and email along with body (content).

> So yeah, in short, a PRD or a short design doc might be useful to bounce ideas before diving into the implementation. What do you think?

Sure thing, we can share more specific details -- anyone else we should ping to review?

**Comment by peterfabian** [comment]
Thanks @bekarice-godaddy for the feedback and elaborating. I think your approach makes sense to me. We can cc @pmcpinto as the product lead for managing WC stores.

**Comment by tturton-godaddy** [comment]
Hey @peterfabian, thanks so much for sharing your feedback as well! I've put together a [Google doc](https://docs.google.com/document/d/1oMku-8Fqzj6PCSmXh5j3ElE2hsxABp6TQ3ayuQ-Or8Q/edit#) so we can discuss/fine-tune before moving forward. Looking forward to collaborating with you and @pmcpinto.

**Comment by pmcpinto** [comment]
👋 I just looked at the PRD and all the proposed changes make sense. We allow users to moderate reviews directly in the WooCommerce Home Screen. Feel free to provide feedback regarding this part of the experience, as it can impact the 1st and 2nd job story. Thanks!

**Comment by peterfabian** [comment]
Thanks for sharing the doc. I think it makes sense and besides the considerations raised by Pedro, my only feedback would be to potentially add working within the WC Admin framework as a future consideration. I think we can proceed.

**Comment by tturton-godaddy** [comment]
Hey folks, I'm looping back to this after spending some time on other projects. Thanks for your raising the WC Home > Reviews section consideration @pmcpinto. I've updated the PRD to account for that user experience to ensure we maintain the same layout/functionality and users are directed to the new Products > Reviews page from the section's "manage" link.

@peterfabian, can you expand on what you have in mind re: working within the WC Admin framework?

**Comment by tturton-godaddy** [comment]
@pmcpinto @peterfabian Great news! Our dev team has completed discovery and is getting ready for the development phase. I have a few questions for you as we move forward:

1.  Is there someone on the Woo dev side that would be a good point of contact for our engineers when they have questions about implementation or would like to get a review?
2. Would you be able to review the discovery [Overview](https://docs.google.com/document/d/1oMku-8Fqzj6PCSmXh5j3ElE2hsxABp6TQ3ayuQ-Or8Q/edit#heading=h.qv9n90g7k1ml) here and flag anything that might need to be modified? (e.g., changing the directory or namespace)
3. What's the process for release notes and announcements about new features, is that something we should prepare and are guidelines available?
4. How should we approach documentation? Our team is happy to contribute the support docs, just curious about the submission process and where they'd be available for end-users.

**Comment by peterfabian** [comment]
Hi, thanks for coming back and sorry for the delay in our response.

As for point no 1 (aka the development workflow), I think the best way is to submit PRs (and draft PRs before they're ready for review) and let us know. It will be mostly us in the @woocommerce/proton team looking at the code (and @/pmcpinto checking the product decisions), so if you can assign the Proton team as the reviewer, that would be the best.
If we'd need more direct communication, I suppose we can set up a slack channel in our workspace (unless you already use one that we can reuse?).

2. Thanks for sharing the discovery overview doc.  cc @pmcpinto as our product manager for the area. 

3. The changelog is generated as part of our PR process, that feeds directly into release notes.
We can also publish a post on the dev blog about the feature to give heads up to developers. We'd be happy for you to contribute with the post. We have no strict guidelines, so it's quite free-form at the moment, but if we want it to be more aimed at developers, you can check out one of our dev advisories for a rough template (e.g. [1](https://developer.woocommerce.com/2022/03/30/removal-of-zeroclipboard/) or [2](https://developer.woocommerce.com/2022/04/14/approved-download-directories/), but you can see [larger features](https://developer.woocommerce.com/2022/03/25/store-api-is-now-considered-stable/) don't use any template). In the meantime, the doc can be created in Google docs and shared with us if that works? 

Additionally, we also have the customer-oriented blog https://woocommerce.com/blog/ that our marketing folks write, so I can chat with them if that's something they would consider blog-worthy.

4. Currently, we, unfortunately, don't have an easy way how to allow contributors to add/edit the docs by themselves, so again, that would probably need to go through us (and Google Docs). The documentation would end up on the [customer facing documentation portal](https://woocommerce.com/documentation/). It would be best if you could check the docs and propose new content with links to pages that need to be updated.

Please let us know If that works for you. Thanks!

**Comment by tturton-godaddy** [comment]
Thanks a bunch @peterfabian! The discovery overview I linked was performed by our engineering team so it might be helpful to get a set of eyes on it from the @woocommerce/proton team if possible. I'll sync up with our content team re: documentation and the blog post. We can get create the Google docs and I'll share the links to collaborate there.

**Comment by dmagalhaes-godaddy** [comment]
I've just opened the PR for this feature to be reviewed by the WooCommerce team (see the link just above this comment).

**Comment by peterfabian** [comment]
Hey, @tturton-godaddy , @barryhughes is going to check out the doc. 
Thanks @dmagalhaes-godaddy , it's a larger one, so it might take a couple of days until we get to it, but we'll try to give you some feedback soon.

**Comment by bekarice-godaddy** [comment]
@peterfabian  just a heads up if y'all need to see more of a history, the [more granular PRs are all in our fork](https://github.com/godaddy-wordpress/woocommerce/pulls?q=is%3Apr+is%3Aclosed)

**Comment by barryhughes** [comment]
@peterfabian | @tturton-godaddy | @dmagalhaes-godaddy,

The doc looks good and the engineering overview is comprehensive, the assumptions seem fine to me. I'd say we should move ahead to code review (bandwidth allowing).

**Comment by smoen-godaddy** [comment]
Hey @peterfabian , the customer-facing documentation is in place now on the [Google doc](https://docs.google.com/document/d/1oMku-8Fqzj6PCSmXh5j3ElE2hsxABp6TQ3ayuQ-Or8Q/edit#) is ready for review/feedback.

**Comment by barryhughes** [comment]
FYI @megphillips91 and @thisissandip on the above.

**Comment by thisissandip** [comment]
@smoen-godaddy the customer-facing documentation in this [Google doc](https://docs.google.com/document/d/1oMku-8Fqzj6PCSmXh5j3ElE2hsxABp6TQ3ayuQ-Or8Q/edit#) for WooCommerce.com still says:

> [TBD] Our docs team can prepare documentation and submit it to WooCommerce.com for approval.

Can you please point me in the right direction?

**Comment by smoen-godaddy** [comment]
@thisissandip Sorry, it seems I sent the incorrect link. [Here is the correct one](https://docs.google.com/document/d/1j12Jn-jwAxkr5tPuEne5mHjf7qYGAy_MSPyFxCxd6Qo/edit). Thanks for the heads up!

**Comment by thisissandip** [comment]
Thanks, @smoen-godaddy! 

The document looks good. We may need to add FAQs later (after this is released). Please do add the screenshot under the "Viewing and managing Product Reviews" section 😄

Once [the PR](https://github.com/woocommerce/woocommerce/pull/32763) is merged, I'll create a document for the same on WooCommerce.com

**Comment by smoen-godaddy** [comment]
@thisissandip I added the screenshot for WooCommerce > Home to the doc. 

Is the post for the dev blog still needed?

**Comment by thisissandip** [comment]
> I added the screenshot for WooCommerce > Home to the doc.

Thanks, @smoen-godaddy!

> Is the post for the dev blog still needed?

Yes, the dev post is still needed that would go on - `https://developer.woocommerce.com/`

**Comment by thisissandip** [comment]
Hi @smoen-godaddy, I have created a [document](https://woocommerce.com/document/product-reviews/) in `woocommerce.com/document` using the provided Google Docs.

Please review that and let me know if you want to add anything else 😄
