### ISSUE TITLE
Undefined property: WP_Block_Template::$origin 

### ISSUE THREAD

**Issue by kafleg** [woothemes/woocommerce#31488]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**WordPress: 5.8.2
Gutenberg: 12.1.0 Activated
Theme: Twenty Twenty-Two Activated
WooCommerce: Version 6.0.0**

The list of error found,

```
<b>Notice</b>:  Undefined property: WP_Block_Template::$origin in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>467</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$author in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>477</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$origin in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>467</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$author in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>477</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$origin in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>467</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$author in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>477</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$origin in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>467</b><br />
  | <br />
  | <b>Notice</b>:  Undefined property: WP_Block_Template::$author in <b>C:\laragon\www\review\wp-content\plugins\gutenberg\lib\compat\wordpress-5.9\class-gutenberg-rest-templates-controller.php</b> on line <b>477</b><br />
```
Here is the screenshot, 
![image](https://user-images.githubusercontent.com/13062231/146877202-f2eb3afe-2673-4132-b994-a87e9b5a18f6.png)

### Expected behavior

WooCommerce should work without the issue.

### Actual behavior

When you have Gutenberg activated and you will see Appearance > Editor(Beta). Click on that issue to get it. 

### Steps to reproduce

1. Go to Appearance > Editor(Beta)
2. You will see the error.

### WordPress Environment

**WordPress: 5.8.2
Gutenberg: 12.1.0 Activated
Theme: Twenty Twenty-Two Activated
WooCommerce: Version 6.0.0**

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @kafleg,

We are still working on making WooCommerce compatible with the new Twenty Twenty-Two theme. I'm closing this issue for the meantime. Stay tuned for announcements in our public channels.
