### ISSUE TITLE
Product Featured Image not displaying as "attached" in the media library 

### ISSUE THREAD

**Issue by hi99ins** [woothemes/woocommerce#31487]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I create a product and then add a featured image to it (2 separate operations) then return to the media library, none of the featured product images are listed as "attached.
There is a similar (unsolved thread at https://github.com/woocommerce/woocommerce/issues/27281) where the user reports the same issue but caused by importing products and ,media from a .csv  - In my case I assigned them manually and got the same result.

I did import products from a .csv originally, but then went and uploaded 100's of media files manually (not using an import feature). Then I went though individually and assigned images to the product featured image. 

None of them show as attached when I look in the media library. This is a real time consuming issue to get around and is plainly a bug in either Woocommerce or perhaps WordPress. I cannot find any plugins which get around this functional error as all the bulk-editing media plugins I looked at simply use the media library as a basis (WPSheetEditor for example). 
Its a logistical nightmare to resolve what will be 3800 products/images where I cannot determine which images are used/attached as a featured image and which are not.

Note: I used 2 different themes inc. Storefront and disabled plugins; there was no difference in behavior. WordPress is up to date.

### Expected behavior

When you assign a featured image in the product editing screen, it should appear as "attached" with the URL of the product in the WordPress media library

### Actual behavior

When I create a product and then add a featured image to it (2 separate operations) then return to the media library, none of the featured product images are listed as "attached. Products were imported from csv, images were uploaded manually  then assigned to products individually.

### Steps to reproduce

import/create product
save product (published or not makes no difference)
upload an image
edit product and assign a "featured image"
save product
open media library
Observe that the image you just assigned to the product is listed as "not attached"

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.caravan-spare-parts.co.uk
Site address (URL): https://www.caravan-spare-parts.co.uk
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Unix)
PHP Version: 7.2.34
PHP Post Max Size: 256 MB
PHP Time Limit: 3000
PHP Max Input Vars: 9000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.48-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 25.09MB
Database Data Size: 19.35MB
Database Index Size: 5.74MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_loginizer_logs: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_section_storage: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_options: Data: 2.11MB + Index: 0.09MB + Engine MyISAM
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 5.46MB + Index: 0.78MB + Engine MyISAM
wp_posts: Data: 4.50MB + Index: 0.19MB + Engine MyISAM
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 1.42MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.34MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 1.81MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 587
consal_testimonial: 4
customize_changeset: 5
nav_menu_item: 4
oembed_cache: 10
page: 19
portfolio: 6
post: 2
press: 2
product: 694
revision: 246
seedprod: 1
service: 8
shop_order: 3
shop_order_refund: 4
wpcf7_contact_form: 1
wphb_minify_group: 23

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Redux: by Extendify – 4.3.5
All-in-One WP Migration: by ServMask – 7.51
Auto Image Attributes From Filename With Bulk Updater: by Arun Basil Lal – 2.1
Breadcrumb NavXT: by John Havlik – 6.6.0
Bulk Featured Image: by CreedAlly – 1.0.0
CMB2: by CMB2 team – 2.9.0
Code Snippets: by Code Snippets Pro – 2.14.2
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.6.0
Consal Theme Plugin: by CodersPoint – 1.0.0
Contact Form 7 Captcha Pro: by 247wd – 0.0.1
Contact Form 7: by Takayuki Miyoshi – 5.5.3
Disable Gutenberg: by Jeff Starr – 2.5.1
ELEX WooCommerce Bulk Edit Products, Prices & Attributes (Basic): by ELEXtensions – 1.2.0
FileBird Lite: by Ninja Team – 4.9.5
Hummingbird: by WPMU DEV – 3.1.3
iOS Images Fixer: by Bishoy A. – 1.2.4
WPBakery Page Builder: by Michael M - WPBakery.com – 5.5.2
Media Cleaner: by Jordy Meow – 6.2.6
Smart Slider 3: by Nextend – 3.5.1.2
User Role Editor: by Vladimir Garagulya – 4.60.2
Online Worldpay For WooCommerce: by Payment Plugins
support@paymentplugins.com – 2.0.6

WooCommerce: by Automattic – 6.0.0
Yoast SEO: by Team Yoast – 17.8
WP All Import: by Soflyy – 3.6.4
Smush: by WPMU DEV – 3.9.2

### Inactive Plugins (1) ###

WooCommerce Admin: by WooCommerce – 2.9.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #678 - /shop-online/
Cart: #7470 - /shopping-cart/
Checkout: #7478 - /checkout/
My account: #7480 - /my-account/
Terms and conditions: #7476 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 606
Oldest: 2021-12-05 17:17:57 +0000
Newest: 2021-12-20 20:33:06 +0000

### Status report information ###

Generated at: 2021-12-20 21:23:21 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @hi99ins ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version. 

Please find below screenshots for reference :

Assigned a featured image to product : 

![#31487(product image)](https://user-images.githubusercontent.com/94531721/146888160-db464a58-ce0c-4d18-809a-5a6a671e3d1d.jpg)


Product is listed as "Unattached" in Media Library : 

![#31487(media libary )](https://user-images.githubusercontent.com/94531721/146888299-5d01a462-e02b-417a-88cc-d533b78a57a3.jpg)
 
Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by hi99ins** [comment]
Has there been any update on this issue? Thanks
Tim

**Comment by barryhughes** [comment]
We would appear to be paralleling core WordPress behavior in this regard (if I'm understanding the problem correctly):

- Upload a new image to the media library.
- Visit an existing post, set the image as the post's featured image.
- Return to/refresh the media library, and the image appears unattached.

I understand the problem this presents for you; but I'm also not sure it should be regarded as a bug in WooCommerce. Have you checked in core WP trac for a bug report there?
