### ISSUE TITLE
Variation Pricing

### ISSUE THREAD

**Issue by user8342912** [woothemes/woocommerce#31491]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I created a variable product named 'Test' with a single attribute with multiple values.

- Option 1
- Option 2
- Option 3

<img width="597" alt="Screenshot 2021-12-21 at 22 21 19" src="https://user-images.githubusercontent.com/93920643/147005831-b97554b9-2758-42ee-bea0-ea08ea2d2128.png">

I then added 2 variations, the first variation was for Option 1 only with a price of £3.00 the second variation was for any option with a price of £2.50

<img width="503" alt="Screenshot 2021-12-21 at 22 30 46" src="https://user-images.githubusercontent.com/93920643/147006073-c7e38539-3f5e-4d5d-9bf1-e837bc083063.png">

When adding the product to basket on the front end choosing Option 1, the product is displayed as 'Test - Option 1' compared to choosing the other options it is displayed as 'Test' for the product name, then below it shows 'Options: Option 3'.

Basket
<img width="646" alt="Screenshot 2021-12-21 at 22 24 51" src="https://user-images.githubusercontent.com/93920643/147005867-b904f79b-2323-412e-a7ac-4c5fec3ed779.png">

Order Details after placing the order
<img width="709" alt="Screenshot 2021-12-21 at 22 25 36" src="https://user-images.githubusercontent.com/93920643/147005875-a3769a0b-255c-4238-b00f-f2d61158f527.png">

Order shown in the admin
<img width="689" alt="Screenshot 2021-12-21 at 22 25 50" src="https://user-images.githubusercontent.com/93920643/147005886-41dd1dbe-613c-43aa-ae0b-24ec9019e9cf.png">

_woocommerce_order_items Database table
<img width="355" alt="Screenshot 2021-12-21 at 22 26 15" src="https://user-images.githubusercontent.com/93920643/147005898-feb3912c-eb64-4b73-8ecf-8f2985563cd4.png">

After placing an order, in the woocommerce_order_items table the product is saved in the order_item_name column as 'Test - Option 1' compared to the other options being saved as 'Test', the order_item_type is the same on all 3 options line_item.

### Expected behavior

When a variable product has a different price for different variations, the product should be displayed in the same way in the basket, admin and database.

### Actual behavior

Variable products with different pricing for each variation, is displayed and saved differently in the basket, admin and database.

### Steps to reproduce

1. Create a variable product
2. Add an attribute with a few options: Option 1, Option 2, Option 3
3. Add 2 variations - Set a price of £3.00 for Option 1 and use Any on the other variation to set a price of £2.50 for the other 2 options.
4. Add Option 1 and Option 2 to basket
5. Both products are shown in different formats for the option name - Option 1 is included in the title whereas Option 2 is listed as an option below the title.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wp.dev.local
Site address (URL): https://wp.dev.local
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.9 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.9
PHP Post Max Size: 8 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 4.31MB
Database Data Size: 2.89MB
Database Index Size: 1.42MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 1
product_variation: 2
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3 (update to version 1.4 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2021-12-21 22:20:33 +0000
Newest: 2021-12-21 22:24:25 +0000

### Status report information ###

Generated at: 2021-12-21 22:26:47 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @user8342912 ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version. 

Please find below screenshots for reference :

Cart : 

![#31491(cart)](https://user-images.githubusercontent.com/94531721/147065768-2eda71fe-53ec-4d0a-ae97-04a42e2f6d44.jpg)

Order Details after placing the order : 

![#31491(order details)](https://user-images.githubusercontent.com/94531721/147065828-b90c3074-6846-4513-8a7e-980407ee2aef.jpg)

Order shown in the admin :
 
![#31491(admin page)](https://user-images.githubusercontent.com/94531721/147065867-9f11897d-5610-499b-a5e4-bf913fad2449.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by ObliviousHarmony** [comment]
Hello @user8342912,

This is how variations are intended to work. Each of the variations is a distinct product that is named after the options that it selects. When there are "any" options present, it doesn't do this, hence the difference.
