### ISSUE TITLE
[Enhancement]: Remove the star icon font

### ISSUE THREAD

**Issue by erikyo** [woothemes/woocommerce#31490]
### Describe the solution you'd like

Nowadays the performance of ecommerce sites is fundamental and I would like WooCommerce to stop loading the "star.font" since it is useless. In addition there is already the star icon in the "WooCommerce.font" at uni U+E02(0|1) and it is enqueued as well. 
It would be enough to use \E020 and \E021 with the font called woocommerce instead of the star font "\53" and "\57" (BTW... why is the hex unicode point value was used when you could use "S" or "s" to get the star icon?)

### Describe alternatives you've considered

Removing the star font would break all the websites that use that font-family... to solve this I modified and added in position \53 and \73 to the WooCommerce font the same star and the same size. 
In this way the woocommerce font will completely replace the star one, and we only need to substitute the sources in the css file avoid any issue. 

[#diff-78e8a298fbfa5c945fca62c0ff17a15f71c66c7177e7c6ab4077b4b8288fe7dd](https://github.com/erikyo/woocommerce/commit/f97739c392effd4d8822fe94bc897afc6827bfc1)

### Additional context

here you can find the new font set:
https://github.com/erikyo/woocommerce/tree/f97739c392effd4d8822fe94bc897afc6827bfc1/assets/fonts

* added woff2 format
* removed useless charsets (this has almost halved the weight of the font originally - .ttf before 15kb - now 9kb)
* NOT removed the star font for backward compatibility since some plugins might use it

**Comment by peterfabian** [comment]
Hi @erikyo . Thanks for your contribution. Could you please create a pull request so that we can review it and provide feedback using the usual GitHub workflow?
