### ISSUE TITLE
Cropping image via customizer

### ISSUE THREAD

**Issue by Webtica** [woothemes/woocommerce#31496]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

When changing the crop in the customizer find under: Customizer -> Woocommerce -> Product Images -> Thumbnail cropping it is not defaulted to anything. When changing for example to uncropped and saving then when reloading the page it removes the setting. The images stay cropped to 1:1. 

See image: 

<img width="538" alt="Schermafbeelding 2021-12-22 om 14 22 01" src="https://user-images.githubusercontent.com/26842388/147099225-756a075f-776c-490a-ba21-75f1c6b61c4d.png">

### Expected behavior

When changing cropping it should save the setting.

### Actual behavior

When changing the crop in the customizer find under: Customizer -> Woocommerce -> Product Images -> Thumbnail cropping it is not defaulted to anything. When changing for example to uncropped and saving then when reloading the page it removes the setting. The images stay cropped to 1:1. 

### Steps to reproduce

 Customizer -> Woocommerce -> Product Images -> Thumbnail cropping and then change setting and save. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://leggielegz.com
Site address (URL): https://leggielegz.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.27
PHP Post Max Size: 50 MB
PHP Time Limit: 250
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.27-0ubuntu0.20.04.1
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 72.06MB
Database Data Size: 52.43MB
Database Index Size: 19.63MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.31MB + Index: 1.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_facetwp_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_facetwp_index: Data: 1.38MB + Index: 0.78MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 9.02MB + Index: 0.28MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 16.52MB + Index: 8.97MB + Engine InnoDB
wp_posts: Data: 4.52MB + Index: 1.11MB + Engine InnoDB
wp_sib_model_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_trp_gettext_nl_nl: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.45MB + Index: 0.77MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 4.52MB + Index: 2.64MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.23MB + Index: 0.34MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 20
acf-field-group: 4
attachment: 2564
customize_changeset: 6
elementor_library: 9
elementor_snippet: 1
language_switcher: 2
page: 12
post: 5
product: 380
product_variation: 2993
revision: 118
shop_order: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

ManageWP - Worker: by GoDaddy – 4.9.11
Redirect 404 to Homepage: by pipdig – 1.0
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
Elementor Pro: by Elementor.com – 3.5.2
Elementor: by Elementor.com – 3.5.1
FacetWP - Cache: by FacetWP
LLC – 1.6.1

FacetWP - Color: by FacetWP
LLC – 1.5.3

FacetWP - Elementor: by FacetWP
LLC – 1.6.6

FacetWP: by FacetWP
LLC – 3.9.2

FileBird: by Ninja Team – 4.9.7
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.25
Make Column Clickable Elementor: by Fernando Acosta – 1.3.1
Mollie Payments for WooCommerce: by Mollie – 6.7.0
TranslatePress - Developer: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.0.9

TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.1.8

Ultimate Addons for Elementor: by Brainstorm Force – 1.35.3
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.19
WC MyParcel Belgium: by Richard Perdaan – 4.4.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.11.1
WooCommerce: by Automattic – 6.0.0
Wordfence Security: by Wordfence – 7.5.7
Yoast SEO: by Team Yoast – 17.8
WP Rocket: by WP Media – 3.10.5.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #18 - /shop/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #21 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Webtica Theme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4,555
Oldest: 2021-11-21 14:44:18 +0100
Newest: 2021-12-22 13:04:22 +0100

Failed: 2
Oldest: 2021-11-22 12:51:22 +0100
Newest: 2021-11-23 09:27:20 +0100

### Status report information ###

Generated at: 2021-12-22 14:23:11 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @Webtica ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version.

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/147229034-4be5371c-19f1-4b6e-a3f4-09807814c6b7.mp4



Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by Webtica** [comment]
Hi @swatipawarGS, It seems that it could be on my install only? Is there a way to repair maybe broken database tables? As everything seems fine? 

The steps I do are the same as you do in your video. only it's doesn't save the state. When I reload the page all the options are grey and not selected at all. 

Thanks

**Comment by zhongruige** [comment]
Hi @Webtica,

I wonder if this may have something to do with the Elementor plugin/theme or possibly another plugin that could be causing an issue. To verify this, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
﻿
If the issue is resolved with the default theme and all plugins deactivated, it means that one of the plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Another thought is potentially there is a JavaScript error that may be causing the button to not save and give us some more insight. You can open the dev tools (for example, [how to do this in Chrome](https://developer.chrome.com/docs/devtools/open/)) and view the `Console` tab to see if there are any errors logged there, for example:

<img width="1000" alt="Screen Shot 2021-12-28 at 08 55 16" src="https://user-images.githubusercontent.com/71906536/147583966-a5857f01-afbc-4f57-9302-41538f2609be.png">

**Comment by Webtica** [comment]
Hi @zhongruige, 

Got it working again after deactivating everything besides woocommerce. 
Then activated everything again and the setting stayed. 

So this is okay now! 

Thanks
Dieter

**Comment by zhongruige** [comment]
That's great to hear Dieter! I am glad that is working for you now--thank you for following up on this!
