### ISSUE TITLE
Where is 6.0.0 tag in Github repository. 

### ISSUE THREAD

**Issue by danielcivit** [woothemes/woocommerce#31516]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WooCommerce 6.0.0 has been released but 6.0.0 tag is missing in GitHub repository. 

The reason why I am asking about this.. is because I work in a project in which I run some github actions, and one of the steps on those actions is download the latest tag from GitHub WooCommerce repository, then run some integration tests with that   code... however, since latest version has not been tagged; i can't run the test with the latest version properly..  it seems somebody forgot that step during the release; or maybe something changed in the release process.

### Expected behavior

Be able to run: 

git clone --branch 6.0.0 https://github.com/woocommerce/woocommerce

In the same way I am able to run

git clone --branch 5.9.0 https://github.com/woocommerce/woocommerce

### Actual behavior

git clone --branch 6.0.0 https://github.com/woocommerce/woocommerce 

return "Remote branch 6.0.0 not found in upstream origin"

### Steps to reproduce

1. Go to command line. 
2. git clone --branch 6.0.0 https://github.com/woocommerce/woocommerce 

### WordPress Environment

No need of WP environment.  

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @Daniel-MultiSafepay,

Thank you for reporting the issue! Just noting that this issue had been reported previously [here](https://github.com/woocommerce/woocommerce/issues/31475). We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed. Thank you!
