### ISSUE TITLE
[Enhancement]: Woocommerce Multi Currency

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#31514]
### Describe the solution you'd like

Hello there,
We have a Woocommerce site based in Bahrain. We are planning to expand our site into Saudi Arabia. We noticed that currently Woocommerce supports only one currency. It's there any way to add one more currency into Woocommerce ? Is there any plugin available to reach our goal ? I've checked most of the free plugins provides only currency switcher. we need add one more currency into Woocommerce like native. please advise.

**Comment by helgatheviking** [comment]
while this isn't a support forum, you might want to check out:
https://woocommerce.com/products/multi-currency/
https://woocommerce.com/products/woocommerce-payments/

**Comment by ghost** [comment]
Dear @helgatheviking,

Thanks for your reply, really appreciate. first link you provided currency switcher which is not helpful for us, second link is look like payment gateway which is enable stripe i think.

We have products in multiple currencies and need to enter them with different, original currency. The same counts for checkout add-ons.

Products would need to be displayed in original currency that was entered and even paid in this currency.

**Comment by kkmuffme** [comment]
Check out WPML, they offer that.

**Comment by helgatheviking** [comment]
WooCommerce Payments is a gateway, with a multi-currency feature. Though they don't have per-currency prices. I think aelia might: https://aelia.co/shop/currency-switcher-woocommerce/

**Comment by ghost** [comment]
Hello @helgatheviking,

Thanks for your reply. We are based in Bahrain @helgatheviking while config its shows only supports list of countries. and about aelia.co plugins really new for me i think looks really cool i try to check it out, really appreciate @helgatheviking thank you so much

**Comment by ghost** [comment]
Hello @kkmuffme 
Let me check Thanks for your reply

**Comment by DavidAnderson684** [comment]
Aelia's has multi-currency prices. I can't claim to have tried out any others, since Aelia's worked great for me for about 7+ years. Very good code quality, excellent support from a top WooCommerce coder.

**Comment by ghost** [comment]
Hello there,  i contact Aelia's plugin support, they have only option currency switcher. so as per my analysis woo commerce don't support more than one currency by default. i tried many plugins they just provide features to switch on currency into another instead of add. I request in future woo commerce update, they should consider about this. anyways ill achieve my requirement by code ill add that sample logic here for future reference, thanks for your all support and help

**Comment by masteradhoc** [comment]
+1 to get this into core :)

**Comment by Luc45** [comment]
It seems WooCommerce Payments has a pretty good multi-currency solution already: https://woo.com/document/woopayments/currencies/multi-currency-setup/
