### ISSUE TITLE
🔥 Filters based on featured products (Simple but essential)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#31513]
### Describe the solution you'd like

If we mark products as "featured", it is very difficult to find them among many products. https://prnt.sc/24p91ld
The only way is to search for each product so that we can access them. This is very time consuming.

**proposed solution :** 
Please add an option as "Featured Products" to the above filters. https://prnt.sc/24p9qlm
Using this filter, we can separate outstanding products from all products and easily access them.
Adding this feature will definitely not be difficult. But much is needed.
thanks

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
