### ISSUE TITLE
Meta: release tag 6.0.0 missing

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#31525]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://wordpress.org/plugins/woocommerce/ shows latest version 6.0.0, but this version is missing in the Github releases (only beta/RC is there): https://github.com/woocommerce/woocommerce/releases

### Expected behavior

add missing release

### Actual behavior

missing release

### Steps to reproduce

none

### WordPress Environment

irrelvant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @kkmuffme,

Thank you for reporting the issue. However, this issue had been reported previously [here](https://github.com/woocommerce/woocommerce/issues/31475). We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed. Thank you!
