### ISSUE TITLE
[Enhancement]: Woo commerce Hyperlink Thumbnail 

### ISSUE THREAD

**Issue by JordanWP** [woothemes/woocommerce#31538]
### Describe the solution you'd like

Hi,

I have used this code to implement thumbnails to each item on the my orders page.
Is it possible to hyperlink the thumbnail to open the original size image?

> // Display the product thumbnail in order view pages
add_filter( 'woocommerce_order_item_name', 'display_product_image_in_order_item', 20, 3 );
function display_product_image_in_order_item( $item_name, $item, $is_visible ) {
    // Targeting view order pages only
    if( is_wc_endpoint_url( 'view-order' ) ) {
        $product   = $item->get_product(); // Get the WC_Product object (from order item)
        $thumbnail = $product->get_image(array( 40, 40)); // Get the product thumbnail (from product object)
        if( $product->get_image_id() > 0 )
            $item_name = '<div class="item-thumbnail">' . $thumbnail . '</div>' . $item_name;
    }
    return $item_name;
}

This is so the customers can access the full sized image.

![wporder](https://user-images.githubusercontent.com/96917506/147829824-9b9fb29d-3c5e-4a3f-8a46-82fad6ab5cf2.png)

**Comment by vijayhardaha** [comment]
```php
/**
 * Display the product thumbnail in order to view pages.
 *
 * @param string $item_name Order item name.
 * @param object $item Order item object.
 * @return string
 */
function display_product_image_in_order_item( $item_name, $item ) {
	// Targeting view order pages only.
	if ( ! is_admin() && is_wc_endpoint_url( 'view-order' ) ) {
		$product      = $item->get_product();
		$thumbnail_id = $product->get_image_id();

		if ( $thumbnail_id ) {
			$thumbnail      = $product->get_image( array( 40, 40 ) );
			$full_image_url = wp_get_attachment_image_url( $thumbnail_id, 'full' );
			$thumbnail_link = sprintf( '<a href="%s">%s</a>', esc_url( $full_image_url ), $thumbnail );
			$item_name      = $thumbnail_link . $item_name;
		}
	}
	return $item_name;
}
add_filter( 'woocommerce_order_item_name', 'display_product_image_in_order_item', 20, 2 );
```

Here is complete working code for you.

**Comment by JordanWP** [comment]
> ```
> /**
>  * Display the product thumbnail in order to view pages.
>  *
>  * @param string $item_name Order item name.
>  * @param object $item Order item object.
>  * @return string
>  */
> function display_product_image_in_order_item( $item_name, $item ) {
> 	// Targeting view order pages only.
> 	if ( ! is_admin() && is_wc_endpoint_url( 'view-order' ) ) {
> 		$product      = $item->get_product();
> 		$thumbnail_id = $product->get_image_id();
> 
> 		if ( $thumbnail_id ) {
> 			$thumbnail      = $product->get_image( array( 40, 40 ) );
> 			$full_image_url = wp_get_attachment_image_url( $thumbnail_id, 'full' );
> 			$thumbnail_link = sprintf( '<a href="%s">%s</a>', esc_url( $full_image_url ), $thumbnail );
> 			$item_name      = $thumbnail_link . $item_name;
> 		}
> 	}
> 	return $item_name;
> }
> add_filter( 'woocommerce_order_item_name', 'display_product_image_in_order_item', 20, 2 );
> ```
> 
> Here is complete working code for you.

Thankyou  @vijayhardaha 

This works perfectly!
