### ISSUE TITLE
[Enhancement]: Cookie “cookieName” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. 

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#31541]
### Describe the solution you'd like

If you using firefox it will gives warning:
Cookie “cookieName” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. 

Maybe we should start to implement a fix for this issue before this security enhancement rolled out globally.

At the time of writing, for chrome:
`This is an industry-wide change for browsers and is not something Mozilla is undertaking alone. Google has been rolling this change out to Chrome users since February 2020, with SameSite=Lax being the default for a certain (unpublished) percentage of all their channels (release, beta, canary).`

for firefox:
`Starting with Beta 79 today, we are rolling out this change to the default behavior of SameSite cookies to a small percentage of the beta population. The initial target is 10%, slowly increasing to 50% by the end of the beta cycle. We will hold at 50% for at least two more beta cycles, at which point we will consider introducing this to a small percentage of the Firefox release population.`

**Comment by rrennick** [comment]
This seems to have been addressed. A related [PR](https://github.com/woocommerce/woocommerce/pull/33219)
