### ISSUE TITLE
API Request: Add the status field to the GET Coupons API endpoint

### ISSUE THREAD

**Issue by anitaa1990** [woothemes/woocommerce#31555]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
The Woo mobile team is working on adding coupon support in the Woo mobile app. As part of the project, we would like the option to:
- [x] View the `status` of a coupon. 
- [ ] Update the `status` of a coupon from the API.
- [x] Filter coupons by `status`.  There are two parts to this request.
   - [x] It looks like only published coupons are available in the API response. It would be nice to list all coupons available for the store, regardless of the status.
   - [ ] As part of the designs, we would need to display active and expired coupons separately in the app. It would be nice to be able to filter coupons by expiry or other statuses. 

It looks like there is no `status` field in the GET Coupons API response. So adding that field would be a good first step.

**Context:**
`p91TBi-6ZF`

**Comment by anitaa1990** [comment]
I'd like to take a crack at this issue, if that's alright 😊

**Comment by anitaa1990** [comment]
Closed via #31561

**Comment by DanielLanger** [comment]
@jeffstieler  @anitaa1990 im not seeing this in the API docs https://woocommerce.github.io/woocommerce-rest-api-docs/#coupons

nor am I able to use the field. was this deployed?

**Comment by weetbicks** [comment]
@anitaa1990 was this ever done? I'm not seeing it in documentation. It would be very useful to have access to a coupon status as well as edit it, so that draft coupons can be managed and turned on/off via the API
