### ISSUE TITLE
Twenty Twenty Two (2022) theme compatibility for cart related pages

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31550]
### Describe the solution you'd like

This issue tracks adding WooCommerce compatibility for following pages:

- [ ] Cart - empty
- [ ] Cart - full
- [ ] Checkout
- [ ] Order placed

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by peterfabian** [comment]
Resolved by several PRs.
