### ISSUE TITLE
Add/Edit Customer details on my-account page[Enhancement]: 

### ISSUE THREAD

**Issue by KBSMayo** [woothemes/woocommerce#31563]
### Describe the solution you'd like

I want to allow customers to add/amend their address, email, phone and profile image.

### Describe alternatives you've considered

I tried WooCommerce Extension My Account Page Editor but this does not address the issue.

**Comment by rrennick** [comment]
@KBSMayo I apologize for the long delay in responding. Your customers can edit their address, phone, and email at `my-account/edit-address`.
