### ISSUE TITLE
Search product sku with spaces return not found in ?s=sku+space&post_type=product url

### ISSUE THREAD

**Issue by AlexWebpuro** [woothemes/woocommerce#31584]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When i try to search product by SKU in search field, return product not found, but if i try same sku with a ajax search, the search get me a product

### Expected behavior

Return a page with product or list of product with the same sku

### Actual behavior

Return product not found

### Steps to reproduce

1. Search product by sku ( with space )
2. press enter

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://ebanicomco.bigscoots-staging.com
Site address (URL): https://ebanicomco.bigscoots-staging.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.1
PHP Version: 7.4.21
PHP Post Max Size: 800 MB
PHP Time Limit: -1
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 3659.33MB
Tamaño de los datos de la base de datos: 2857.43MB
Tamaño del índice de la base de datos: 801.90MB
wp_woocommerce_sessions: Datos: 1.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.09MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 3.52MB + Índice: 1.52MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 49.59MB + Índice: 35.11MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_a3_exclude_email_subject: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 32.56MB + Índice: 23.13MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.17MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 28.56MB + Índice: 12.03MB + Motor InnoDB
wp_adtribes_my_conversions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ajaxsearchpro: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ajaxsearchpro_priorities: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ajaxsearchpro_statistics: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_asp_index: Datos: 53.63MB + Índice: 114.47MB + Motor InnoDB
wp_asp_synonyms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_ass_survey_completions: Datos: 0.38MB + Índice: 0.00MB + Motor InnoDB
wp_ass_survey_offer_attempts: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp_ass_survey_uptakes: Datos: 0.41MB + Índice: 0.00MB + Motor InnoDB
wp_botlabmarketing: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bulkgate_module: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_bv_fw_requests: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bv_ip_store: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp_bv_lp_requests: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_commentmeta: Datos: 1.52MB + Índice: 0.73MB + Motor InnoDB
wp_comments: Datos: 56.59MB + Índice: 19.09MB + Motor InnoDB
wp_cpf_customfeeds: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cpf_custom_products: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cpf_feedproducts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cpf_resolved_product_data: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cp_feeds: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_announcement: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_follow_store_followers: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_dokan_orders: Datos: 1.52MB + Índice: 1.03MB + Motor InnoDB
wp_dokan_product_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_refund: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_report_abuse_reports: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_dokan_rma_conversations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_rma_request: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_rma_request_product: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_shipping_zone_locations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_vendor_balance: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
wp_dokan_withdraw: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_epayco_order: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_hustle_entries: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_hustle_entries_meta: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_hustle_modules: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_hustle_modules_meta: Datos: 0.09MB + Índice: 0.03MB + Motor InnoDB
wp_hustle_tracking: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_ik_ebanicobros_ganancias_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ik_ebanicobros_retenciones: Datos: 0.14MB + Índice: 0.00MB + Motor InnoDB
wp_ik_relacionador_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_import_detail_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_import_log_detail: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_import_postID: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailchimp_carts: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp_mailchimp_jobs: Datos: 0.16MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_actions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_action_meta: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_chunks: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_fields: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_field_meta: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_form_meta: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_objects: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_object_meta: Datos: 4.52MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_relationships: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nf3_upgrades: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 179.48MB + Índice: 1.78MB + Motor InnoDB
wp_pmxe_exports: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxe_google_cats: Datos: 0.39MB + Índice: 0.00MB + Motor InnoDB
wp_pmxe_posts: Datos: 5.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxe_templates: Datos: 0.31MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_files: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_hash: Datos: 4.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_images: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_imports: Datos: 5.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_posts: Datos: 6.52MB + Índice: 0.00MB + Motor InnoDB
wp_pmxi_templates: Datos: 0.20MB + Índice: 0.00MB + Motor InnoDB
wp_postmeta: Datos: 296.88MB + Índice: 205.09MB + Motor InnoDB
wp_posts: Datos: 37.58MB + Índice: 19.13MB + Motor InnoDB
wp_promag_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_fields: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_friends: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_group_requests: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_msg_conversation: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_promag_msg_threads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_notification: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_paypal_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_promag_sections: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ps: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_ps_answers: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_ps_answers_values: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ps_data: Datos: 0.27MB + Índice: 0.17MB + Motor InnoDB
wp_ps_logic_conditions: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_ps_questions: Datos: 0.02MB + Índice: 0.13MB + Motor InnoDB
wp_pts_tables: Datos: 0.36MB + Índice: 0.00MB + Motor InnoDB
wp_pv_commission: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_redirection_404: Datos: 2.02MB + Índice: 0.19MB + Motor InnoDB
wp_redirection_groups: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_redirection_items: Datos: 0.08MB + Índice: 0.09MB + Motor InnoDB
wp_redirection_logs: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_revslider_css: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_sliders: Datos: 0.28MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_slides: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_sb_queue: Datos: 1341.00MB + Índice: 284.69MB + Motor InnoDB
wp_sgpb_subscribers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_sgpb_subscription_error_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shipment_batch_process: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_smackcsv_file_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_smackuci_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_termmeta: Datos: 2.52MB + Índice: 4.03MB + Motor InnoDB
wp_terms: Datos: 0.52MB + Índice: 0.61MB + Motor InnoDB
wp_term_relationships: Datos: 5.52MB + Índice: 5.52MB + Motor InnoDB
wp_term_taxonomy: Datos: 1.52MB + Índice: 0.73MB + Motor InnoDB
wp_ultimate_csv_importer_acf_fields: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ultimate_csv_importer_mappingtemplate: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ultimate_csv_importer_media: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ultimate_csv_importer_shortcode_manager: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ultimate_post_entries: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_usermeta: Datos: 41.56MB + Índice: 37.14MB + Motor InnoDB
wp_users: Datos: 2.52MB + Índice: 2.55MB + Motor InnoDB
wp_wcpv_commissions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wcpv_per_product_shipping_rules: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.16MB + Índice: 0.13MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.22MB + Índice: 0.28MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.17MB + Índice: 0.17MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 3.52MB + Índice: 10.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woo_shipment_status_email: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woo_shippment_provider: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wpfm_backup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wpml_mails: Datos: 590.52MB + Índice: 0.00MB + Motor InnoDB
wp_wpmm_subscribers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpr_rucss_resources: Datos: 12.52MB + Índice: 0.14MB + Motor InnoDB
wp_wpr_rucss_used_css: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wp_phpmyadmin_extension__errors_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wt_iew_action_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wt_iew_cron: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wt_iew_ftp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wt_iew_mapping_template: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_xoo_wl_list: Datos: 0.23MB + Índice: 0.09MB + Motor InnoDB
wp_xoo_wl_list_meta: Datos: 0.28MB + Índice: 0.36MB + Motor InnoDB
wp_yith_vendors_commissions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_vendors_commissions_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_vendors_payments: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_vendors_payments_relationship: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcwl: Datos: 0.50MB + Índice: 0.22MB + Motor InnoDB
wp_yith_wcwl_lists: Datos: 0.47MB + Índice: 0.45MB + Motor InnoDB
wp_yoast_indexable: Datos: 59.55MB + Índice: 17.61MB + Motor InnoDB
wp_yoast_indexable_hierarchy: Datos: 1.52MB + Índice: 1.06MB + Motor InnoDB
wp_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yoast_primary_term: Datos: 1.52MB + Índice: 0.75MB + Motor InnoDB
wp_yoast_seo_links: Datos: 0.11MB + Índice: 0.09MB + Motor InnoDB
wp_yoast_seo_meta: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

as_survey: 1
as_survey_response: 1839
attachment: 32557
awl_filter_gallery: 1
cobros: 323
custom_css: 1
custom-css-js: 8
customize_changeset: 1
dokan_store_reviews: 1
lcg_mainpost: 12
lcg_shortcode: 1
logocarousel: 5
mc4wp-form: 3
nav_menu_item: 262
nf_sub: 26
oembed_cache: 139
page: 64
popup: 5
popup_theme: 8
popupbuilder: 1
portfolio: 1
post: 3
pricingtable: 1
product: 10328
product_variation: 6138
ps: 1
rpt_pricing_table: 1
shop_coupon: 7
shop_order: 16889
shop_order_refund: 379
team: 1
team_member: 1
team_showcase_post: 3
tmm: 1
um_directory: 1
um_form: 3
wc_afrsm: 1
wcp_ruleset: 1
wppopups: 1
wptwa_accounts: 1
ywar_reviews: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (73) ###

Wompi Plugin para WooCommerce: por Vlipco SAS – 0.1.1
Ajax Search Pro: por Ernest Marcinko – 4.21.5
Akismet Anti-Spam: por Automattic – 4.2.1
All-in-One WP Migration: por ServMask – 7.50
Bancolombia - WooCommerce Payment Gateway: por  – 1.0
BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce (Premium): por Pagup – 1.4.4.5
Bulk remove posts from category: por MasterNs – 3.2.1
WP Check No JavaScript or Cookie: por Tips and Tricks HQ – 1.2
Editor clásico: por Colaboradores de WordPress – 1.6.2
Clear Logout: por Ayesh Karunaratne – 1.2
Flexible SSL for CloudFlare: por One Dollar Plugin – 1.3.1
CodeSniffer WooCommerce added to cart popup: por CodeSniffer – 1.0.4
Simple Custom CSS and JS: por SilkyPress.com – 3.38
Customer Reviews for WooCommerce: por CusRev – 4.28
Departamentos y ciudades de Colombia para WooCommerce: por Saul Morales Pacheco – 1.1.31
Direct Deposit for WooCommerce: por Melissa Freeman – 1.1
Disable Cart Fragments: por Optimocha – 2.0
Disable WooCommerce Bloat: por ospiotr – 2.6.1
Dokan: por weDevs – 3.3.0
Dokan Pro: por weDevs – 3.4.0
Google Tag Manager for WordPress: por Thomas Geiger – 1.13.1
Facebook for WooCommerce: por Facebook – 2.6.7
Header and Footer Scripts: por Digital Liberation – 2.2.1
Ebani Cobros: por Gabriel Caroprese / Inforket – 2.7.15
Dokan RMA Requests Todos: por Gabriel Caroprese / Inforket – 1.3.11
Relacionador de Productos: por Gabriel Caroprese / Inforket – 1.1.1
Incdustry Personalización Ebani: por Juan González - Incdustry – 0.0.1
WPBakery Page Builder: por Michael M - WPBakery.com – 6.7.0
Kirki Customizer Framework: por David Vongries – 3.1.9
Loco Translate: por Tim Whitlock – 2.5.3
Mailchimp for WooCommerce: por Mailchimp – 2.5.3
Martfury Addons: por DrFuri – 2.2.6
Meta Box: por MetaBox.io – 5.4.8
Perfect Survey: por Webaid – 1.5.1
Product page shipping calculator for WooCommerce: por PI Websolution – 1.2.37
Really Simple SSL: por Really Simple Plugins – 5.1.3
Redirection: por John Godley – 5.1.3
Redis Object Cache: por Till Krüss – 2.0.21
Lazy Load - Optimize Images: por WP Rocket – 2.3.4
Servebolt Optimizer: por Servebolt – 3.3
Mostrar IP del servidor y uso de memoria: por Apasionados
Apasionados del Marketing – 2.1.0

Team Builder For WPBakery Page Builder: por Labib Ahmed – 1.0
TinyPNG - JPEG, PNG & WebP image compression: por TinyPNG – 3.3
User Switching: por John Blackbourn y colaboradores – 1.5.8
WooCommerce Variation Swatches Pro: por Drfuri – 1.0.5
Waitlist Woocommerce Premium ( Back in stock notifier ): por  – 3.0
Open Graph and Twitter Card Tags: por Webdados – 3.1.1
Advanced Shipment Tracking for WooCommerce: por zorem – 3.1.8
Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.7
Preview E-mails for WooCommerce: por Digamber Pradhan – 2.0.1
WooCommerce Deals: por Drfuri – 1.0.9
WooCommerce Extra Product Sorting Options: por SkyVerge – 2.9.0
Mercado Pago payments for WooCommerce: por Mercado Pago – 5.5.0
WooCommerce Social Login: por SkyVerge – 2.11.0 (la actualización a la versión 2.11.1 está disponible)
WooCommerce: por Automattic – 6.0.0
WooSMS - SMS module for WooCommerce: por BulkGate SMS gateway – 2.0.31
Yoast SEO: por Equipo Yoast – 17.5
WP All Export Pro: por Soflyy – 1.7.2
WP All Import Pro: por Soflyy – 4.7.1
Asset CleanUp Pro: Page Speed Booster: por Gabe Livan – 1.2.0.1
WP Email Template LITE: por a3rev Software – 2.5.4
WP Mail Logging: por Wysija – 1.9.9
WP Mail SMTP: por WPForms – 3.2.0
WP Maintenance Mode: por Designmodo – 2.4.1
WP Rocket: por WP Media – 3.10.1
WP Rollback: por Impress.org – 1.7.1
WP All Export - ACF Export Add-On Pro: por Soflyy – 1.0.3
WP All Export - WooCommerce Export Add-On Pro: por Soflyy – 1.0.3
WP All Import - WooCommerce Add-On Pro: por Soflyy – 3.2.8
WPFront Notification Bar: por Syam Mohan – 2.3.0.102911
XML for Google Merchant Center: por Maxim Glazunov – 2.4.0
YITH WooCommerce Wishlist: por YITH – 3.3.0
Yoast Test Helper: por El equipo de Yoast – 1.15

### Inactive Plugins (16) ###

Advanced Shipment Tracking for WooCommerce: por zorem – 3.3
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.5.0
Doofinder for WooCommerce: por doofinder – 1.5.13
Ebani Cobros: por Gabriel Caroprese / Inforket – 2.7.15
Ebani Cobros: por Gabriel Caroprese / Inforket – 2.7.15
FakerPress: por Gustavo Bordoni – 0.5.1
FiboSearch - AJAX Search for WooCommerce: por FiboSearch Team – 1.14.0
Hotjar: por Hotjar – 1.0.12
KP Fastest Chat: por Kreativo Pro – 1.0.3
New Relic Reporting for WordPress: por 10up – 1.3.1
Popup Maker: por Popup Maker – 1.16.2
Product Feed PRO for WooCommerce: por AdTribes.io – 10.8.5
Query Monitor: por John Blackbourn – 3.7.1
Relacionador de Productos: por Gabriel Caroprese / Inforket – 1.1.1
WooCommerce Google Ads Dynamic Remarketing: por woopt – 1.8.1
WooCommerce Google Analytics Integration: por WooCommerce – 1.5.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Asset CleanUp Pro: Plugin Filtering: por Gabriel Livan – 1.0
Clear PHP opcode caches: por Jan Reilink – 1.0
disable-admin-password-change-email-notification.php: por  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #4 - /tienda/
Carrito: #5 - /carrito-de-compras/
Finalizar compra: #6 - /checkout/
Mi cuenta: #7 - /mi-cuenta/
Términos y condiciones: #4594 - /terminos-y-condiciones-para-usuarios/

### Theme ###

Name: Martfury Child
Version: 1.0
Author URL: http://drfuri.com
Child Theme: ✔
Parent Theme Name: Martfury
Parent Theme Version: 2.4.9
Parent Theme Author URL: http://demo2.drfuri.com
WooCommerce Support: ✔

### Templates ###

Overrides: martfury-child/woocommerce/cart/cart-empty.php
martfury-child/woocommerce/cart/cart-item-data.php
martfury-child/woocommerce/cart/cart-shipping.php
martfury-child/woocommerce/cart/cart-totals.php
martfury-child/woocommerce/cart/cart.php
martfury-child/woocommerce/cart/cross-sells.php
martfury-child/woocommerce/cart/mini-cart.php
martfury-child/woocommerce/cart/proceed-to-checkout-button.php
martfury-child/woocommerce/cart/shipping-calculator.php
martfury-child/woocommerce/checkout/form-billing.php
martfury/woocommerce/checkout/form-checkout.php
martfury/woocommerce/checkout/form-coupon.php
martfury/woocommerce/checkout/form-login.php
martfury-child/woocommerce/checkout/form-shipping.php
martfury/woocommerce/checkout/terms.php
martfury-child/woocommerce/checkout/thankyou.php
martfury/woocommerce/content-product.php
martfury/woocommerce/content-single-product.php
martfury/woocommerce/content-widget-product.php
martfury-child/woocommerce/emails/customer-completed-order.php
La  version 3.7.0 de martfury-child/woocommerce/emails/customer-new-account.php está obsoleta. La versión del núcleo es la 6.0.0
martfury-child/woocommerce/emails/customer-on-hold-order.php
martfury-child/woocommerce/emails/customer-processing-order.php
La  version 3.9.0 de martfury-child/woocommerce/emails/email-addresses.php está obsoleta. La versión del núcleo es la 5.6.0
martfury-child/woocommerce/emails/email-order-details.php
martfury-child/woocommerce/emails/email-order-items.php
martfury/woocommerce/global/form-login.php
martfury/woocommerce/global/quantity-input.php
martfury/woocommerce/global/wrapper-end.php
martfury/woocommerce/global/wrapper-start.php
martfury-child/woocommerce/loop/add-to-cart.php
martfury-child/woocommerce/loop/orderby.php
martfury-child/woocommerce/loop/pagination.php
martfury-child/woocommerce/myaccount/form-edit-address.php
martfury-child/woocommerce/myaccount/form-login.php
martfury/woocommerce/myaccount/form-lost-password.php
martfury/woocommerce/myaccount/my-address.php
martfury/woocommerce/single-product/add-to-cart/external.php
martfury-child/woocommerce/single-product/add-to-cart/simple.php
martfury/woocommerce/single-product/add-to-cart/variable.php
martfury-child/woocommerce/single-product/meta.php
martfury/woocommerce/single-product/product-image.php
martfury/woocommerce/single-product/product-thumbnails.php
martfury/woocommerce/single-product/rating.php
martfury-child/woocommerce/single-product/related.php
martfury/woocommerce/single-product/review-meta.php
martfury/woocommerce/single-product/stock.php
martfury-child/woocommerce/single-product/tabs/tabs.php
martfury/woocommerce/single-product/up-sells.php
martfury/woocommerce/single-product-reviews.php

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### Social Login ###

Google: ✔ Available
Facebook: ✔ Available
Twitter: Disabled
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Cancelada: 7
Oldest: 2021-12-09 13:14:31 +0000
Newest: 2021-12-26 13:30:24 +0000

Completo: 13.309
Oldest: 2021-12-07 21:00:22 +0000
Newest: 2022-01-06 22:23:08 +0000

Fallida: 66.688
Oldest: 2019-11-20 12:48:11 +0000
Newest: 2022-01-06 22:23:08 +0000

### Status report information ###

Generated at: 2022-01-06 17:53:54 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @AlexWebpuro ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress  5.8.3 version.


Please find below screencast for reference : 

https://user-images.githubusercontent.com/94531721/148560398-7429bebd-ff52-4b6e-8b63-919fb8a279bb.mp4

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by vijayhardaha** [comment]
@swatipawarGS Issue if for frontend.

@AlexWebpuro The default search doesn't look into SKU meta. it just looks for product title and product content/short description(I guess). While ajax search which I assume is another plugin functionality, they have their own search system so they search for SKU as well.

**Comment by rodelgc** [comment]
Hi @AlexWebpuro,

I also couldn't reproduce the issue on my end. I was able to search for the product using a SKU that contains a whitespace.

<img width="1370" alt="Screen Shot 2022-01-10 at 3 48 53 PM" src="https://user-images.githubusercontent.com/4509348/148733200-870cb4a3-efa5-4388-8e0a-e5cb4e2611e8.png">


I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
