### ISSUE TITLE
Special characters in email subject

### ISSUE THREAD

**Issue by witcher83** [woothemes/woocommerce#31586]
### Describe the solution you'd like

If in the email subject there's the "&" character, it will be converted into "&amp;"

This can be solved by changing the line /woocommerce/includes/emails/class-wc-email.php:654 from this
`$mail_callback_params = apply_filters( 'woocommerce_mail_callback_params', array( $to, $subject, $message, $headers, $attachments ), $this );`
into this:
`$mail_callback_params = apply_filters( 'woocommerce_mail_callback_params', array( $to, wp_specialchars_decode( $subject ), $message, $headers, $attachments ), $this );`
according to what WordPress already does in its core.

**Comment by masteradhoc** [comment]
@witcher83 thanks for opening the issue - see the PR with your code suggestion in the history above.
