### ISSUE TITLE
Switch to using using data stores instead of direct post or post meta access for orders

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31597]
This issue scopes converting common occurrences of direct wp_post or wp_postmeta access via WP APIs to use data stores instead.

#30228

**Comment by jeffstieler** [comment]
I tried to handle all uses of `get_post_meta()` and `update_post_meta()` pertaining to Order metadata in https://github.com/woocommerce/woocommerce/pull/31874.

One question I had - is it OK to leave the legacy API classes unchanged? There are still some [post meta uses](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/legacy/api/v2/class-wc-api-orders.php#L435) there.

Here are the direct post/meta queries relating to Orders that I found (to be handled in a separate PR):

* `wc_customer_bought_product()` - direct query
* `wc_reset_order_customer_id_on_deleted_user()` - direct table access
* `WC_Admin_Dashboard::get_top_seller()` - direct query
* `WC_Admin_Report::get_order_report_data()` - direct query, legacy reports - **can this be ignored/removed?**
* `WC_Customer_Data_Store::get_last_order()` - direct query
* `WC_Customer_Data_Store::get_order_count()` - direct query
* `WC_Customer_Data_Store::get_total_spent()` - direct query - **has a filter, argh**

Will we want to form separate direct queries for store using COT, or should these functions be refactored push the queries into filterable data stores?

**Comment by peterfabian** [comment]
[The PR](https://github.com/woocommerce/woocommerce/pull/31890) is not fully tested yet.

**Comment by vedanshujain** [comment]
Linking https://github.com/woocommerce/woocommerce/pull/31874 for review as well

**Comment by vedanshujain** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/34124, https://github.com/woocommerce/woocommerce/pull/34178 and https://github.com/woocommerce/woocommerce/pull/34121
