### ISSUE TITLE
MVP for data migration for custom order table from wp_post and wp_postmeta tables

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31599]
This spike scopes finding a performant and reliable approach to migrating data from wp_post and wp_postmeta tables. This also scopes testing the migration approach across stores of different sizes with different hosting configurations.

#30228

Desired output: an RFC discussing approaches and suggesting best approach

**Comment by vedanshujain** [comment]
We are currently considering following migration policy, documenting here for more feedback.

### Migration policy 

Migration for this project is going to be more complex than what we would do in normal circumstances.

In this case, feature for merchants to not only opt-in to the custom tables but also opt-out whenever they want is necessary. This ability to opt-out should instill more confidence in trying out the feature, with an option to go back if there are extensions or customization that they use which are still not compatible with custom order tables.

The ability to opt-out instantly comes with a performance penalty, since this means that we would need to keep both posts and custom order tables in sync. Therefore, we plan to provide this as an optional setting, which will be enabled by default. This mode is intended to be very temporary, to guide the merchants in testing out the feature. We will provide a setting to disable this sync and remove the performance penalty.

One way of thinking about migrations would be to divide them into the following scenarios:

**Note**: COT is short for custom order table(s)



#### Case 1: When migration is started but not completed yet

1. When reading, we are not concerned about COT as our authoritative source of data is still wp_posts.
1. When inserting, we can schedule an action to insert in COT, since it’s a new order. We can safely do this async as authoritative source of data is still wp_posts, so it’s fine if COT is still outdated in context of that request.
1. When updating/deleting, we need to find out if that record is already migrated. If yes, then it’s a “dirty row” and we need to update/delete again.

<img width="709" alt="Screenshot 2022-01-31 at 7 54 09 PM" src="https://user-images.githubusercontent.com/7571618/151810719-6554accb-664d-432e-91c7-b80034bffe96.png">

#### Case 2: Migration is completed and sync is enabled (default behavior)

1. Authoritative source of data is now COT. However we want to keep data in post table in sync temporarily so that if merchant needs to revert, they can do so in a snap without losing data.
    1. Reading is bit complex here, as there might be some plugin still writing to post tables directly. If we want to handle this case, then following algorithm may work (inspired from on-the-fly migration by Liquid Web custom order table plugin:
    1. We compare date_modified of both COT and wp_posts rows. Given that we are updating synchronously, if the dates are different than only model in wp_posts has to be the latest one. So we load from wp_posts instead of COT.
1. We push back into COT to keep these in sync.
<img width="670" alt="Screenshot 2022-01-31 at 7 56 11 PM" src="https://user-images.githubusercontent.com/7571618/151811122-48bdd642-a088-4b7e-b396-78ddc7ce959a.png">

#### Case 3: Migration is completed and sync is off

This is our final stat, and we want everyone to be here eventually. This is the simplest one as well:
<img width="421" alt="Screenshot 2022-01-31 at 7 57 17 PM" src="https://user-images.githubusercontent.com/7571618/151811322-3ff48e07-f55e-48a2-86e8-1ef0bb5415a0.png">


Over-all the migration user story may look like:

<img width="563" alt="Screenshot 2022-01-31 at 8 02 58 PM" src="https://user-images.githubusercontent.com/7571618/151812336-8789c917-24fd-4ff8-9ccb-777760066815.png">

#### Next steps:
While we discuss the migration policy, I am going to create GH issues to track small pieces that we are confident about, even if there are changes in our approach.

**Comment by rrennick** [comment]
Closing as complete.
