### ISSUE TITLE
Fatal errors when accessing WooCommerce > Orders in PHP 8 environment

### ISSUE THREAD

**Issue by csmcneill** [woothemes/woocommerce#31595]
### Describe the bug

A user experienced the following fatal errors after updating to PHP 8 and then accessing WooCommerce > Orders:

```
2022-01-03T11:28:17+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Order_Data_Store_CPT::filter_raw_meta_data() in /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:207
Stack trace:
#0 /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(598): WC_Data_Store->__call('filter_raw_meta...', Array)
woocommerce/woocommerce-admin#1 /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(117): WC_Data->read_meta_data()
woocommerce/woocommerce-admin#2 /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
woocommerce/woocommerce-admin#3 /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(116): WC_Data_Store->read(Objec in /data/9/e/9e290bbf-44f7-4933-b243-9b323359c5ba/stilllifeacademy.com/web/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 207
```

### To Reproduce

I tried reproducing this on their site with admin credentials, but I couldn't. The user came back and indicated that's because they reverted back to PHP 7.4.

I do not have a PHP 8 environment to test, but I wanted to relay this to the development team in case it's a larger issue.

### Additional context

4655450-zen

### System Status Report

<details>
`
### WordPress Environment ###

WordPress address (URL): https://stilllifeacademy.com
Site address (URL): https://stilllifeacademy.com
WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.7-MariaDB-1:10.3.7+maria~xenial-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: pjyhmi
Total Database Size: 142.50MB
Database Data Size: 102.15MB
Database Index Size: 40.35MB
pjyhmiwoocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
pjyhmiwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pjyhmiwoocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
pjyhmiwoocommerce_order_itemmeta: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
pjyhmiwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pjyhmiwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiactionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
pjyhmiactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiactionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pjyhmibadgeos_achievements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibadgeos_points: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibadgeos_ranks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibb_email_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_activity: Data: 2.52MB + Index: 1.98MB + Engine InnoDB
pjyhmibp_activity_meta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
pjyhmibp_document: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
pjyhmibp_document_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_document_folder_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_document_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_follow: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmibp_friends: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
pjyhmibp_groups: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmibp_groups_groupmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_groups_members: Data: 0.09MB + Index: 0.19MB + Engine InnoDB
pjyhmibp_invitations: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
pjyhmibp_media: Data: 0.23MB + Index: 0.36MB + Engine InnoDB
pjyhmibp_media_albums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_messages_drafts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_messages_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_messages_label_message: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmibp_messages_messages: Data: 2.52MB + Index: 0.23MB + Engine InnoDB
pjyhmibp_messages_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_messages_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmibp_messages_recipients: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
pjyhmibp_moderation: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_moderation_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_notifications: Data: 1.52MB + Index: 2.14MB + Engine InnoDB
pjyhmibp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_suspend: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmibp_suspend_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmibp_user_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_user_blogs_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmibp_xprofile_data: Data: 0.36MB + Index: 0.27MB + Engine InnoDB
pjyhmibp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
pjyhmibp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmibp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmicf_forms: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
pjyhmicf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pjyhmicf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmicf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmicf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmicf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmicf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmicommentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
pjyhmicomments: Data: 0.25MB + Index: 0.28MB + Engine InnoDB
pjyhmie_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
pjyhmie_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
pjyhmie_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmifbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmifbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmigamipress_logs: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
pjyhmigamipress_logs_meta: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
pjyhmigamipress_user_earnings: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
pjyhmigamipress_user_earnings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearndash_user_activity: Data: 1.52MB + Index: 1.77MB + Engine InnoDB
pjyhmilearndash_user_activity_meta: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
pjyhmilearnpress_order_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_question_answermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_question_answers: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_review_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_sections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_section_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmilearnpress_user_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilearnpress_user_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmilrsync: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilrsync_collections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilrsync_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmilrsync_relations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmimailerlite_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhminewsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhminewsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhminewsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhminewsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhminewsletter_user_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhminobuna_backups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhminobuna_downloads: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhminobuna_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmioptions: Data: 7.19MB + Index: 0.31MB + Engine InnoDB
pjyhmip2p: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmip2pmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmipostmeta: Data: 46.52MB + Index: 6.03MB + Engine InnoDB
pjyhmiposts: Data: 12.22MB + Index: 13.73MB + Engine MyISAM
pjyhmirank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmirank_math_internal_links: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
pjyhmirank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmirank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmirank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmishortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmishortpixel_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmisignups: Data: 0.30MB + Index: 0.16MB + Engine InnoDB
pjyhmitermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiusermeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
pjyhmiusers: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
pjyhmiwcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pjyhmiwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwc_customer_lookup: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
pjyhmiwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
pjyhmiwc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
pjyhmiwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
pjyhmiwc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pjyhmiwpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmiwp_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiwp_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwp_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiwp_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiwp_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pjyhmiyoast_indexable: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
pjyhmiyoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pjyhmiyoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pjyhmiyoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pjyhmiyoast_seo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
pjyhmiyoast_seo_meta: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wehjaqcommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqcomments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wehjaqlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wehjaqoptions: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wehjaqpostmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqposts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wehjaqtermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wehjaqterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqusermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wehjaqusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

achievement-type: 1
attachment: 1967
badges: 7
bp-email: 28
bp-invite: 5
bp-member-type: 3
buddyboss_slides: 1
custom_css: 1
elementor_library: 12
forum: 3
groups: 1
job_listing: 1
lp_question: 82
lp_quiz: 7
nav_menu_item: 21
oembed_cache: 143
page: 25
point_type: 1
points-award: 9
points-type: 1
post: 16
product: 14
revision: 1904
sfwd-courses: 12
sfwd-lessons: 116
shop_coupon: 19
shop_order: 458
shop_order_refund: 5
step: 6
tribe_events: 7
tribe_organizer: 1
tribe_venue: 5
user_request: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Akismet Anti-Spam: by Automattic – 4.2.1
BuddyBoss Platform: by BuddyBoss – 1.8.4
BuddyBoss Products Updater: by BuddyBoss – 1.2.8
CB Change Mail Sender: by Md Abul Bashar – 1.2.2
Elementor Pro: by Elementor.com – 3.5.2
Elementor: by Elementor.com – 3.5.3
Filester - File Manager Pro: by Ninja Team – 1.7.4
LearnDash LMS - Course Grid: by LearnDash – 2.0.3
LearnDash LMS - WooCommerce Integration: by LearnDash – 1.9.3.3
PRO Elements: by Elementor.com – 2.9.3
Rank Math SEO: by Rank Math – 1.0.79
LearnDash LMS: by LearnDash – 3.6.0
ShortPixel Image Optimizer: by ShortPixel – 4.22.6
Temporary Login Without Password: by StoreApps – 1.7.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.69

WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.11.2
WooCommerce: by Automattic – 5.8.0 (update to version 6.0.0 is available)
WP Rocket: by WP Media – 3.10.5.1

### Inactive Plugins (1) ###

User Export (with their Meta Data): by Daniel Loureiro – 0.6.8

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

LearnDash LMS Multisite: by LearnDash – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: woocommerce/woocommerce-admin#444 - /cart/
Checkout: woocommerce/woocommerce-admin#447 - /check-out/
My account: woocommerce/woocommerce-admin#450 - /account/
Terms and conditions: woocommerce/woocommerce-admin#458 - /terms-of-service/

### Theme ###

Name: BuddyBoss Child
Version: 1.0.0
Author URL: https://www.buddyboss.com/
Child Theme: ✔
Parent Theme Name: BuddyBoss Theme
Parent Theme Version: 1.8.2
Parent Theme Author URL: https://www.buddyboss.com/
WooCommerce Support: ✔

### Templates ###

Overrides: buddyboss-theme/woocommerce/checkout/form-checkout.php
buddyboss-theme/woocommerce/checkout/review-order.php
buddyboss-theme/woocommerce/checkout/thankyou.php
buddyboss-theme/woocommerce/global/quantity-input.php
buddyboss-theme/woocommerce/myaccount/dashboard.php
buddyboss-theme/woocommerce/myaccount/downloads.php
buddyboss-theme/woocommerce/myaccount/form-edit-account.php
buddyboss-theme/woocommerce/myaccount/form-edit-address.php
buddyboss-theme/woocommerce/myaccount/form-login.php
buddyboss-theme/woocommerce/myaccount/form-lost-password.php
buddyboss-theme/woocommerce/myaccount/my-account.php
buddyboss-theme/woocommerce/myaccount/my-address.php
buddyboss-theme/woocommerce/myaccount/my-downloads.php
buddyboss-theme/woocommerce/myaccount/my-orders.php
buddyboss-theme/woocommerce/myaccount/navigation.php
buddyboss-theme/woocommerce/myaccount/orders.php
buddyboss-theme/woocommerce/myaccount/view-order.php
buddyboss-theme/woocommerce/order/order-details-customer.php
buddyboss-theme/woocommerce/order/order-details-item.php
buddyboss-theme/woocommerce/order/order-details.php
buddyboss-theme/woocommerce/single-product/meta.php

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: RO
WooCommerce currency supported: ✔
PayPal card processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔

### Action Scheduler ###

Complete: 92
Oldest: 2021-12-07 19:12:00 +0000
Newest: 2022-01-03 10:48:27 +0000

Failed: 1
Oldest: 2021-08-19 16:33:51 +0000
Newest: 2021-08-19 16:33:51 +0000

### Status report information ###

Generated at: 2022-01-04 22:49:13 +00:00
`
</details>

**Comment by swatipawarGS** [comment]
Hi @csmcneill ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.0.0 version, WordPress 5.8.3 version and PHP 8.0.14 version .

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/148754450-f7c059e6-5498-402b-9b7b-ff0ff5c468e9.mp4

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by csmcneill** [comment]
Howdy @swatipawarGS,

Thanks for letting me know—perhaps this was some sort of issue surrounding this user's particular setup and may not have been solely related to WC core.
