### ISSUE TITLE
[Enhanceme]: Dropshipping is very popular all over the worldnt]

### ISSUE THREAD

**Issue by DanielCyran** [woothemes/woocommerce#31604]
### Describe the solution you'd like

Dropshipping is very popular all over the world and one small feature is missing in Woocommerce; / When we have thousands of products and we want to hide products that are in stock, e.g. 3, you cannot hide these products, you need to use an external code. this function is important because the stock levels are not updated in the LIVE form
 Did I write in the right place to introduce the functions of hiding products with stock, e.g. 3 ?
function hide_products_with_low_stock( $q, $query ){
    $min = 2;
    $meta_query = $q->get( 'meta_query' );
    $meta_query[] = array(
        'key' => '_stock',
        'value' => $min,
        'type' => 'numeric',
        'compare' => '>'
    );
    $q->set( 'meta_query', $meta_query );
}
add_action( 'woocommerce_product_query', 'hide_products_with_low_stock', 10, 2 );
function product_out_of_stock_redirect(){
    global $post;
    if( is_product() ){
        $product = wc_get_product($post->ID);
		
		if( $product->get_stock_quantity() <= 2 ){
			wp_redirect(get_permalink( get_option( 'woocommerce_shop_page_id' ) ) . "?pna=true");
			exit();
		}
    }
	if( is_shop() && !empty(get_query_var('pna')) && !is_admin() ){
		wc_add_notice("Produkt nie jest już dostępny. Przepraszamy!", "notice");
	}
}
add_action('wp', 'product_out_of_stock_redirect');
 this is the code that fixes this problem ... but it better if it works without pasting the code

**Comment by rrennick** [comment]
@DanielCyran There are quite a few [drop shipping extensions](https://woocommerce.com/product-category/woocommerce-extensions/shipping-delivery-and-fulfillment/fulfillment-and-dropshipping/?categoryIds=28690&collections=product&page=1) available. I'm closing this issue as we would be unlikely to implement this functionality in core.
