### ISSUE TITLE
DKK currency code needs to be replaced with short symbol

### ISSUE THREAD

**Issue by conschneider** [woothemes/woocommerce#31601]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The short symbol defined for DKK here: https://github.com/woocommerce/woocommerce/blob/59ab939282ebca560583fa13068e54b5cf51cbb6/plugins/woocommerce/i18n/locale-info.php#L939 should be used here: https://github.com/woocommerce/woocommerce/blob/77917a2de31d76f90b4380815a48b4efcef543a8/plugins/woocommerce/includes/wc-core-functions.php#L706

That is all :). 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

#goodfirstchange

**Comment by lanej0** [comment]
Hi @conschneider,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Yes, that would seem to match what [CLRDr40](https://github.com/unicode-org/cldr/blob/release-40/common/main/en_DK.xml#L98) says, though I think we may wish a period symbol at the end (ie, `kr.`).

**Comment by masteradhoc** [comment]
@conschneider check https://github.com/woocommerce/woocommerce/pull/33509 please :)
