### ISSUE TITLE
Add console suppression documentation

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31613]
The `e2e-environment` package exports the console suppression functionality in https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-environment/utils/filter-console.js. Example usage can be found in the local jest setup. A section describing the functionality should be included in the package readme.

**Comment by MrJnrman** [comment]
Console suppression functionality is already documented in the `e2e-environment` readme with the exception of the `consoleShouldSuppress` method that doesn't need to be there since package users won't need to use it when developing their own tests. Closing this issue.
