### ISSUE TITLE
Wrong Tax calucaltions and Tax Settings

### ISSUE THREAD

**Issue by wdm-janis** [woothemes/woocommerce#31614]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A new bug in Woocommerce 6.0 version with tax setup

Feel like Tax Settings are rechanged.

When I change to No, I will enter prices exclusive of tax, on the front-end I see 100 USD.
The first time sees this bug for a clean install, only the WooCommerce plugin is activated.
Setup screens:
Tax Settings: https://gyazo.com/80b02bfe5b1189cfeda3a05c54f8da34
Product Settings: https://gyazo.com/e1b220781068a67c9a0fe9f9d88d8bbc
Rates: https://gyazo.com/77a8d1d9030812f1fb2eef7431ed3fcd

### Expected behavior

Tax need to work like it works before and always you need change only tax display type how you want to see. 

### Actual behavior

In one of our dev shops (new dev mode), we can not get tax calculations. We set up a whole debugging process, remove plugins, reactivate themes, reset all woocommerce cache tables, reset tax tables via WooCommerce - Tools. Nothing helps to solve these issues like temporary change clean install vs dev install database and see if the problem solve this issues, but on the same clean install on the first time, we get the same as dev version. Even on dev version we try all that we can in WooCommerce settings mode to get any clue of this issue. 

### Steps to reproduce

Add Tax: Yes, I will enter prices inclusive of tax
Calculate tax based on: Shop Base
Add Product for 100 EUR or USD
And standard rate with * for all and 21%
What did you see on the front-end?  €82.64?

Clean install. 

### WordPress Environment

WordPress 5.8.3 running Twenty Twenty-One theme.
WooCommerce Version 6.0.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @wpxagency ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.1.0 version, WordPress 5.8.3 version and Twenty Twenty-One theme. 

Please find below screenshots for reference :

Tax Settings : 

![#31614(Tax Setting)](https://user-images.githubusercontent.com/94531721/149084285-de7079e6-d944-494c-bd41-42334fa63d22.jpg)

Product Settings :
 
![#31614(Product Setting)](https://user-images.githubusercontent.com/94531721/149084316-fcb7eb59-3752-4f04-a4c8-498b2f976604.jpg)

Tax Rates : 

![#31614(Rate Setting)](https://user-images.githubusercontent.com/94531721/149084349-3070a691-8db4-4948-a61a-86bf96d492fb.jpg)

 Frontend : 

![#31614(front-end)](https://user-images.githubusercontent.com/94531721/149084458-d766d241-4364-4848-ba62-adb46803b4ef.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by wdmarketLV** [comment]
Than You for this!

**Comment by wdm-janis** [comment]
Any updates of this issue?

**Comment by vedanshujain** [comment]
hey @wdm-janis 

Everything in the screenshots looks correct and expected actually. You have configured the shop to display without taxes, that's why you are seeing `82.64` (at 21% tax, for gross price of 100, net price would be 82.64). To display including taxes, go to `WooCommerce -> Settings -> Tax` and configure the options `Display price in the shop` to `Including tax`. You might want to do the same for `Display prices during cart and checkout` setting as well.

I am closing the issue for repository maintenance but will re-open if there are more questions or bug reports.

**Comment by wdm-janis** [comment]
@vedanshujain Please see closer @swatipawarGS screenshots on the cart and settings. If you select on settings that you want to show price exclusive not inclusive. Settings are an upside-down. and sometimes settings change don't take effect of what you see on cart and checkout. All the time settings were worked fine for multiple woocommerce stores before. This bug is only on the new version.
