### ISSUE TITLE
The `is_ajax` function is deprecated since version 6.1.0. Replace with `wp_doing_ajax()`

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#31628]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello, for information, the update to 6.1.0 there is the error message at the top:
The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_aj

I downgraded version 6.0

I'm obviously not the only one,

cordially

### Expected behavior

*

### Actual behavior

*

### Steps to reproduce

*

### WordPress Environment

*

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi,

Thanks for reporting this.  Would you mind dropping us a screenshot of where you're seeing this error?  I suspect that this error is likely coming from a plugin or theme that needs an update to work with 6.1.0 -- but a little additional information will help me track down the issue!

**Comment by steve340700** [comment]
Hello,

The culprit for me is: sequential woocommerce order numbers
I had to deactivate it for it to work

https://prnt.sc/26d5hc2

**Comment by joashrajin** [comment]
+1, another report for this happening with 'WooCommerce Sequential Order Numbers Pro' in 4685271-zd-woothemes. Looks like something the plug-in authors need to fix.

**Comment by zdenys** [comment]
Another case in 4683773-zd-woothemes where WP-CLI shows the message: ` The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_ajax.`

**Comment by joashrajin** [comment]
@zdenys I think that is related to https://github.com/woocommerce/facebook-for-woocommerce/issues/2133 since the customer uses FB for WC

**Comment by lanej0** [comment]
Thanks for bringing this up.  Best to get in touch with [SkyVerge](https://woocommerce.com/products/sequential-order-numbers-pro/) for support on this issue -- hopefully they'll be able to get an update out for their plugin quickly!
