### ISSUE TITLE
Impossible to add or edit fields in Checkout Forms

### ISSUE THREAD

**Issue by oviazcan** [woothemes/woocommerce#31635]
The UI for editing or adding fields in Checkout Forms is crooked, it is impossible to accept changes or add changes. Please fix.
![imagen](https://user-images.githubusercontent.com/49696943/149258020-792b8900-f0c4-4a47-8a52-d9c9d85c1e73.png)

**Comment by joashrajin** [comment]
Hi @oviazcan 👋

Thank you for submitting the issue. However, I can’t reproduce this and based on the screenshot you have shared, it seems like this may be coming from a Checkout Field Editor Plugin. 

In order for us to get a better idea of your site setup and advise you which plugin may be to blame here, it will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment. 

Thanks!
