### ISSUE TITLE
As of version 6.1.0, disabling jQuery Migrate breaks product images on products with multiple images.

### ISSUE THREAD

**Issue by Spellhammer** [woothemes/woocommerce#31636]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When jQuery migrate is disabled, products with multiple images do not display images properly.

Console errors below:

jQuery.Deferred exception: e.indexOf is not a function TypeError: e.indexOf is not a function
    at S.fn.init.S.fn.load (http://woocohotfix.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:84932)
    at new S.fn.init (http://woocohotfix.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:25740)
    at S (http://woocohotfix.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:1051)
    at Object.setupPaging (http://woocohotfix.local/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1:4866)
    at Object.setup (http://woocohotfix.local/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1:4464)
    at Object.init (http://woocohotfix.local/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1:2106)
    at new v.flexslider (http://woocohotfix.local/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1:21309)
    at HTMLDivElement.<anonymous> (http://woocohotfix.local/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1:22487)
    at Function.each (http://woocohotfix.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:3003)
    at S.fn.init.each (http://woocohotfix.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:1481)

jquery.min.js?ver=3.6.0:2 Uncaught TypeError: e.indexOf is not a function
    at S.fn.init.S.fn.load (jquery.min.js?ver=3.6.0:2)
    at new S.fn.init (jquery.min.js?ver=3.6.0:2)
    at S (jquery.min.js?ver=3.6.0:2)
    at Object.setupPaging (jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1)
    at Object.setup (jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1)
    at Object.init (jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1)
    at new v.flexslider (jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1)
    at HTMLDivElement.<anonymous> (jquery.flexslider.min.js?ver=2.7.2-wc.6.1.0:1)
    at Function.each (jquery.min.js?ver=3.6.0:2)
    at S.fn.init.each (jquery.min.js?ver=3.6.0:2) 

### Expected behavior

Images should be displayed.

### Actual behavior

Images are not displayed.

### Steps to reproduce

1. Install WooCommerce on a WordPress site with the Twenty Twenty-One theme
2. Ensure you have a product with multiple product images
3. View the product on the front-end to ensure the images appear as expected
4. Using your browser's developer tools, block the request for jQuery migrate and refresh
5. See that the images are no longer displayed

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woocohotfix.local
Site address (URL): http://woocohotfix.local
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 5.99MB
Database Data Size: 4.54MB
Database Index Size: 1.45MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
ct_template: 1
page: 7
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 27
Oldest: 2022-01-12 14:42:02 +0000
Newest: 2022-01-12 17:31:59 +0000

Pending: 2
Oldest: 2022-01-13 17:20:53 +0000
Newest: 2022-01-13 17:21:58 +0000

### Status report information ###

Generated at: 2022-01-13 17:21:45 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roberthedlund** [comment]
Same thing happened to my site after updating to 6.1.0. As soon as I disabled "disable jQuery Migrate" thru perfmatters the product pictures started to work again.

**Comment by rodelgc** [comment]
Seems like we already have a pull request to fix this: https://github.com/woocommerce/woocommerce/pull/31623

**Comment by joashrajin** [comment]
4684140-zd-woothemes

**Comment by joashrajin** [comment]
4682223-zd-woothemes

**Comment by swatipawarGS** [comment]
Hi @Spellhammer ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.1.0 version , WordPress 5.8.3 version and Twenty Twenty-One theme. 

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/149473611-48ae073d-c8c7-49a9-a0d5-d2a2c668a756.mp4



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by lanej0** [comment]
As @rodelgc noted above, looks like this is resolved in the next minor release (the PR listed has been merged).  Thanks for taking the time to bring this to our attention!

**Comment by darcie** [comment]
33409317-hc

**Comment by ElenaCt** [comment]
Hi everyone.
I come here from woocommerce support.

My problem is that I no longer see product images after updating to version 6.1.0.
I solved the problem by replacing the files 
/assets/js/flexslider/jquery.flexslider.js
/assets/js/flexslider/jquery.flexslider.min.js
with those from the previous version

**Comment by hdsheena** [comment]
Hoping to see this released soon :)

**Comment by omarmfouad25** [comment]
Hey guys I had the same problem for the last 6 days,
I did my research I tried everything written here and on GitHub also
what worked for me really well, to deactivate WooCommerece Plugin, then download Version 6.0.0 from the WP website, then upload it and roll back to 6.0.0 instead of 6.1.0
don’t forget to disable the auto-update

**Comment by omarmfouad25** [comment]
> Hi everyone. I come here from woocommerce support.
> 
> My problem is that I no longer see product images after updating to version 6.1.0. I solved the problem by replacing the files /assets/js/flexslider/jquery.flexslider.js /assets/js/flexslider/jquery.flexslider.min.js with those from the previous version

it didn't work for me

**Comment by despokd** [comment]
@omarmfouad25 Downgrade jQuery temporary fixed it for me.
I just used [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) to change to legacy jQuery Migrate

**Comment by hdsheena** [comment]
> @omarmfouad25 Downgrade jQuery temporary fixed it for me. I just used [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) to change to legacy jQuery Migrate

@despokd 
I just tried this and it didn't make the images reappear on the instance I'm working on :(

**Comment by dakine1977** [comment]
> Hi everyone. I come here from woocommerce support.
> 
> My problem is that I no longer see product images after updating to version 6.1.0. I solved the problem by replacing the files /assets/js/flexslider/jquery.flexslider.js /assets/js/flexslider/jquery.flexslider.min.js with those from the previous version

Thanks... This helped!

**Comment by CEB3895** [comment]
It's 2026 now. Is this already solved? I just encountered the problem.

**Comment by darcie** [comment]
Hey @CEB3895, the PR #31623 in 2022 was expected to fix this. If you're still having a similar issue, have you opened up a support topic in the forums? You can create a topic at https://wordpress.org/support/plugin/woocommerce/#new-topic-0
