### ISSUE TITLE
Bambora extension incompatible with new version of Woocommerce

### ISSUE THREAD

**Issue by tammyphi** [woothemes/woocommerce#31645]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I have Woocommerce on my Wordpress website - I recently updated my Woocommerce plugin to 6.1 and now the Bambora extension only works with 5.8.3 - will you be updating the compatibility soon - I can't use my e-commerce at all with it Here are the error codes 

eprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php on line 5211

Deprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php on line 5211

Deprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php on line 5211

Warning: Cannot modify header information - headers already sent by (output started at /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php:5211) in /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php on line 6712

Warning: Cannot modify header information - headers already sent by (output started at /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php:5211) in /services/webpages/m/a/magnifiedts.com/public/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /services/webpages/m/a/magnifiedts.com/public/wp-includes/functions.php:5211) in /services/webpages/m/a/magnifiedts.com/public/wp-admin/admin-header.php on line 9

**Comment by lanej0** [comment]
Hi @tammyphi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done.

- Contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/) -- they'll be able to get in touch with SkyVerge, the developer of the Bambora extension and get it updated for you.

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
