### ISSUE TITLE
When I activate Woocommerce, my page breaks

### ISSUE THREAD

**Issue by Roberta1999** [woothemes/woocommerce#31654]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I activate Woocommerce, my page breaks the site is brand new, everything works, but when i install the woocommerce site, it shows errors.

The page I need help with: https://bubba.lt/

### Expected behavior

I want you to help solve the problem

### Actual behavior

the site is down at all

### Steps to reproduce

![Be pavadinimo](https://user-images.githubusercontent.com/97883362/149752262-8f665b74-976e-46b8-acbc-39b31171d420.png)
![Be pavadinimo2](https://user-images.githubusercontent.com/97883362/149752268-19033e73-c151-43da-ad3f-60b02fb96756.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bubba.lt
Site address (URL): https://bubba.lt
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.79.1
OpenSSL/1.1.1m

SUHOSIN Installed: –
MySQL Version: 5.7.36-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: Iv3EP4NX_
Total Database Size: 2.89MB
Database Data Size: 2.71MB
Database Index Size: 0.18MB
Iv3EP4NX_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
Iv3EP4NX_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_mapping_to_external_entities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_scheduled_tasks: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_options: Data: 1.64MB + Index: 0.04MB + Engine MyISAM
Iv3EP4NX_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Iv3EP4NX_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Iv3EP4NX_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1
mailpoet_page: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Jetpack: by Automattic – 10.5
MailPoet 3 (New): by MailPoet – 3.76.0
WooCommerce: by Automattic – 6.1.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Google Listings and Ads: by WooCommerce – 1.10.0
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /index.php/shop/
Cart: #7 - /index.php/cart/
Checkout: #8 - /index.php/checkout/
My account: #9 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3 (update to version 1.4 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2022-01-17 09:37:32 +0000
Newest: 2022-01-17 10:25:25 +0000

### Status report information ###

Generated at: 2022-01-17 10:26:25 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @Roberta1999,

A great place to start troubleshooting this sort of issue is by checking out your server logs.  Depending on your hosting provider, they might have logs available to you through some sort of dashboard, or if you have direct shell access you can take a look at the logs there to see what type of error you're getting.

Let us know if you need any help interpreting the log results.

**Comment by Roberta1999** [comment]
errors show these things
![error](https://user-images.githubusercontent.com/97883362/149813948-5f890e46-e5cb-48a9-b9ac-4d98178bf773.png)
