### ISSUE TITLE
HTML tags wrapping the asterisk symbol in required checkout fields

### ISSUE THREAD

**Issue by mrleemon** [woothemes/woocommerce#31657]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The asterisk symbol in required checkout fields is wrapped in `abbr` tags with a `title` attribute that is displayed when a user hovers over the asterisk:
`<abbr class="required" title="required">*</abbr>`

But the asterisk symbol in the "terms and conditions" checkout field is wrapped in a simple `span` tag:
`<span class="required">*</span>`

Is this a deliberate decision? Or should it be wrapped like the other required fields in an `abbr` tag?

### Expected behavior

Not a functional bug

### Actual behavior

Not a functional bug

### Steps to reproduce

1. Create a "terms and condition" page and set it up in the Advanced tab in the WooCommerce settings
2. Go to the checkout page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.example.com
Site address (URL): https://www.example.com
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.6.40
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: ea_
Tamaño total de la base de datos: 46.16MB
Tamaño de los datos de la base de datos: 25.81MB
Tamaño del índice de la base de datos: 20.35MB
ea_woocommerce_sessions: Datos: 1.02MB + Índice: 0.02MB + Motor InnoDB
ea_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ea_woocommerce_order_items: Datos: 0.31MB + Índice: 0.11MB + Motor InnoDB
ea_woocommerce_order_itemmeta: Datos: 2.52MB + Índice: 3.03MB + Motor InnoDB
ea_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ea_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_actions: Datos: 0.11MB + Índice: 0.13MB + Motor InnoDB
ea_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_logs: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
ea_commentmeta: Datos: 0.08MB + Índice: 0.11MB + Motor InnoDB
ea_comments: Datos: 1.52MB + Índice: 1.05MB + Motor InnoDB
ea_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_options: Datos: 3.16MB + Índice: 0.14MB + Motor InnoDB
ea_pimwick_gift_card: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_pimwick_gift_card_activity: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_postmeta: Datos: 12.52MB + Índice: 13.03MB + Motor InnoDB
ea_posts: Datos: 2.52MB + Índice: 0.72MB + Motor InnoDB
ea_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
ea_term_relationships: Datos: 0.23MB + Índice: 0.17MB + Motor InnoDB
ea_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
ea_usermeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
ea_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
ea_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_wc_customer_lookup: Datos: 0.20MB + Índice: 0.19MB + Motor InnoDB
ea_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_order_product_lookup: Datos: 0.38MB + Índice: 0.42MB + Motor InnoDB
ea_wc_order_stats: Datos: 0.33MB + Índice: 0.33MB + Motor InnoDB
ea_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_product_meta_lookup: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
ea_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 700
customize_changeset: 2
gift_card: 1
nav_menu_item: 30
options: 5
page: 44
polylang_mo: 3
popup: 1
popup_theme: 8
post: 64
product: 189
product_variation: 99
revision: 4
shop_coupon: 170
shop_order: 3229
shop_order_refund: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Polylang: por WP SYNTEX – 3.1.3
The SEO Framework: por El equipo de The SEO Framework – 4.2.2
BBQ Firewall: por Jeff Starr – 20210719
Editor clásico: por Colaboradores de WordPress – 1.6.2
Widgets clásicos: por Colaboradores de WordPress – 0.2
Imsanity: por Exactly WWW – 2.7.2
Limit Login Attempts Reloaded: por Limit Login Attempts Reloaded – 2.23.2
PDF Embedder: por WP PDF Embedder Team – 4.6.4
Rather Simple Mailchimp: por mrleemon – v1.0
Rather Simple WooCommerce Alternate Product Categories: por mrleemon – 2.0
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.5.1
WooCommerce Extended Coupon Features FREE: por Soft79 – 3.2.8
WooCommerce Redsys payment gateway: por Jesús Ángel del Pozo Domínguez – 1.2.10
WooCommerce: por Automattic – 6.1.0
YITH WooCommerce Gift Cards: por YITH – 2.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #4191 - /tienda/
Carrito: #12 - /carro/
Finalizar compra: #13 - /realizar-pedido/
Mi cuenta: #14 - /mi-cuenta/
Términos y condiciones: #5218 - /terminos-y-condiciones/

### Theme ###

Name: Example
Version: 1.0.0
Author URL: http://example.com/code/
Child Theme: ✔
Parent Theme Name: MyTheme
Parent Theme Version: 2.0
Parent Theme Author URL: https://example.com/code/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 322
Oldest: 2021-12-23 09:22:40 +0100
Newest: 2022-01-17 20:01:11 +0100

### WooCommerce Polylang Integration ###

Language Locale: es_ES
Polylang Language Locale: es_ES
Polylang Available Languages: es_ES (WooCommerce translation file found OK at /srv/vhost/example.com/home/html/wp-content/languages/plugins/woocommerce-es_ES.mo) ca (WooCommerce translation file found OK at /srv/vhost/example.com/home/html/wp-content/languages/plugins/woocommerce-ca.mo) en_US Warning - missing WooCommerce translation file NOT found at /srv/vhost/example.com/home/html/wp-content/languages/plugins/woocommerce-en_US.mo

### Status report information ###

Generated at: 2022-01-17 20:25:50 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @mrleemon ,

Confirmed.  Form fields appear to use the HTML `abbr` tag to indicate a required field:

<img width="1488" alt="Screen Shot 2022-01-17 at 12 18 13 PM" src="https://user-images.githubusercontent.com/80276/149832789-53b2a9eb-e747-43d5-a858-3ad690953909.png">

The checkbox for terms and conditions uses a `span` to indicate it's required:

<img width="1488" alt="Screen Shot 2022-01-17 at 12 19 01 PM" src="https://user-images.githubusercontent.com/80276/149832908-9cdbe1de-c666-459d-a28b-26671b3fb541.png">

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. I'm not sure if it's an intentional inconsistency, or if it's just an oversight/issue that needs fixing.

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Sounds like an oversight, thanks for reporting. Would you like to contribute with a PR, @mrleemon ?

**Comment by mrleemon** [comment]
@peterfabian, here it is:
https://github.com/woocommerce/woocommerce/pull/31673
