### ISSUE TITLE
Price display suffix incorrect when showing a range on product category page

### ISSUE THREAD

**Issue by jpswade** [woothemes/woocommerce#31659]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the "product-category" pages, for each product type it provides a price range, but it only adds the suffix of the first price to the end of the second price. This is a problem when you want to use the variables.

### Expected behavior

There should be the option to display the suffix to each price or disable it on certain pages.

### Actual behavior

![image](https://user-images.githubusercontent.com/1087963/149832255-f900759d-1d5d-42b3-9f31-9d7d1f0316d2.png)

### Steps to reproduce

1. Go to WooCommerce
2. Go to Settings
3. Go to Tax
4. Under Tax Options, add "Ex. VAT ({price_including_tax} Inc. VAT)" to "Price display suffix".
5. Save.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.stoketimber.com
Site address (URL): https://www.stoketimber.com
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ❌ To allow logging
make gs://stoketimber/1/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.36-google
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 167.13MB
Database Data Size: 129.55MB
Database Index Size: 37.58MB
wp_woocommerce_sessions: Data: 32.06MB + Index: 1.11MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.66MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.28MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.33MB + Engine InnoDB
wp_cpmp_player: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mappress_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mappress_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_options: Data: 9.33MB + Index: 1.09MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 13.03MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.98MB + Engine InnoDB
wp_storelocatorwidget: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_wc_order_stats: Data: 0.30MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 33.56MB + Index: 5.55MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.20MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_yaysmtp_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 2.48MB + Index: 0.72MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.20MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1409
jetpack_migration: 2
nav_menu_item: 29
page: 18
post: 3
postman_sent_mail: 2
product: 367
revision: 520
shop_order: 2529
shop_order_refund: 104
wafs: 1
wp_block: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Angell EYE Updater: by Angell EYE – 2.0.17
Contact Form 7: by Takayuki Miyoshi – 5.5.3
Creative Mail by Constant Contact: by Constant Contact – 1.4.9
Font Awesome: by Font Awesome – 4.0.4
Front Page Category: by Ben Gillbanks – 3.3.2
Google Cloud Storage plugin: by Google Inc – 0.1.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.3.0
Jetpack: by Automattic – 10.5
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Manage Notification E-mails: by Virgial Berveling – 1.8.2
One Click Demo Import: by OCDI – 3.0.2
PayPal for WooCommerce: by Angell EYE – 3.0.14
Simple Shortcode for Google Maps: by Alan Fuller – 1.4.1
Smart Slider 3: by Nextend – 3.5.1.2
Store Locator Widget: by StoreLocatorWidgets.com – 20200131
Tawk.to Live Chat: by Tawkto – 0.6.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.1

Woo Set Price Note (Units, Offers, Editions): by Sh Shanker – 2.0.2
Woo Total Sales: by Sh Shanker – 3.1.4
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.7.4
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce: by Automattic – 6.1.0
Wordfence Security: by Wordfence – 7.5.7
Yoast SEO: by Team Yoast – 17.9
WP Mail SMTP: by WPForms – 3.2.1
WP Post Author: by AF themes – 2.0.4
WPForms Lite: by WPForms – 1.7.2
YITH WooCommerce Compare: by YITH – 2.10.0
YITH WooCommerce Quick View: by YITH – 1.11.0
YITH WooCommerce Wishlist: by YITH – 3.5.0

### Inactive Plugins (2) ###

WP Mail Logging: by Wysija – 1.10.2
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Shopage
Version: 1.0.0
Author URL: https://afthemes.com
Child Theme: ✔
Parent Theme Name: Shopical
Parent Theme Version: 1.2.2
Parent Theme Author URL: https://afthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopical/woocommerce/archive-product.php
shopical/woocommerce/content-product.php
shopical/woocommerce/content-single-product.php
shopical/woocommerce/content-widget-reviews.php
shopical/woocommerce/single-product.php

### Action Scheduler ###

Complete: 1,481
Oldest: 2021-12-20 20:35:22 +0000
Newest: 2022-01-17 19:50:24 +0000

Failed: 1
Oldest: 2021-07-15 08:12:34 +0000
Newest: 2021-07-15 08:12:34 +0000

Pending: 8
Oldest: 2022-01-17 20:50:24 +0000
Newest: 2022-01-24 02:50:03 +0000

### Status report information ###

Generated at: 2022-01-17 20:17:26 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @jpswade ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.1.0 version and WordPress 5.8.3 version. 

Please find below screenshot for reference :

![#31659(final)](https://user-images.githubusercontent.com/94531721/149911144-05f53262-e04f-4ad4-bd31-3765ee7b3d0f.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by jpswade** [comment]
That's strange, on your version, when it's a range, it doesn't display the suffix, while on mine it does.

**Comment by fourstepper** [comment]
I am also experiencing this issue right now, the suffix doesn't show up at all
