### ISSUE TITLE
Product sorting order is not working correctly

### ISSUE THREAD

**Issue by arunschandran** [woothemes/woocommerce#31661]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

I have a problem with my WooCommerce website. Product sorting is not working correctly. In my WordPress dashboard, under “All products” menu item. I sorted products based on price in ASC Order. But this is how it is showing https://prnt.sc/25y5s5d. I disabled all the plugins except WooCommerce. And changed theme to default “Twenty twenty One” theme. But the order is not correct. Can you please check if it is a bug?

Thank you,
Arun

### Expected behavior

I sorted products based on price in ASC Order. It should sort in ascending order. 

### Actual behavior

I sorted products based on price in ASC Order. It isn't sorting in ascending order. 

### Steps to reproduce

I don't know how to reproduce this issue

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://p68850-893-26286.s893.upress.link
Site address (URL): http://p68850-893-26286.s893.upress.link
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.4.13
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: kwu_
הגודל הכולל של בסיס הנתונים: 582.48MB
גודל הנתונים של בסיס הנתונים: 503.88MB
גודל האינדקס של בסיס הנתונים: 78.60MB
kwu_woocommerce_sessions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_woocommerce_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woocommerce_attribute_taxonomies: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_woocommerce_downloadable_product_permissions: נתונים: 0.02MB + אינדקס: 0.17MB + מנוע InnoDB
kwu_woocommerce_order_items: נתונים: 1.52MB + אינדקס: 0.34MB + מנוע InnoDB
kwu_woocommerce_order_itemmeta: נתונים: 6.52MB + אינדקס: 5.55MB + מנוע InnoDB
kwu_woocommerce_tax_rates: נתונים: 0.02MB + אינדקס: 0.08MB + מנוע InnoDB
kwu_woocommerce_tax_rate_locations: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_woocommerce_shipping_zones: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_woocommerce_shipping_zone_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woocommerce_shipping_zone_methods: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_woocommerce_payment_tokens: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woocommerce_payment_tokenmeta: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_woocommerce_log: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_actionscheduler_actions: נתונים: 1.05MB + אינדקס: 0.13MB + מנוע InnoDB
kwu_actionscheduler_claims: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_actionscheduler_groups: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_actionscheduler_logs: נתונים: 0.09MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_alp_pickup_location: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_berocket_termmeta: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_booter_404s: נתונים: 2.52MB + אינדקס: 1.52MB + מנוע InnoDB
kwu_braapf_product_stock_status_parent: נתונים: 0.22MB + אינדקס: 0.16MB + מנוע InnoDB
kwu_braapf_product_variation_attributes: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_braapf_term_taxonomy_hierarchical: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_braapf_variable_attributes: נתונים: 0.06MB + אינדקס: 0.09MB + מנוע InnoDB
kwu_braapf_variation_attributes: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_cartflows_ca_cart_abandonment: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_cartflows_ca_email_history: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_cartflows_ca_email_templates: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_cartflows_ca_email_templates_meta: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_check_email_log: נתונים: 10.05MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_commentmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_comments: נתונים: 2.52MB + אינדקס: 1.25MB + מנוע InnoDB
kwu_ezcache_webp_images: נתונים: 15.55MB + אינדקס: 2.52MB + מנוע InnoDB
kwu_e_submissions: נתונים: 0.22MB + אינדקס: 0.39MB + מנוע InnoDB
kwu_e_submissions_actions_log: נתונים: 0.09MB + אינדקס: 0.17MB + מנוע InnoDB
kwu_e_submissions_values: נתונים: 0.08MB + אינדקס: 0.09MB + מנוע InnoDB
kwu_followup_coupons: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_followup_coupon_logs: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_followup_customers: נתונים: 0.09MB + אינדקס: 0.17MB + מנוע InnoDB
kwu_followup_customer_carts: נתונים: 0.34MB + אינדקס: 0.11MB + מנוע InnoDB
kwu_followup_customer_notes: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_followup_customer_orders: נתונים: 0.13MB + אינדקס: 0.08MB + מנוע InnoDB
kwu_followup_email_excludes: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_followup_email_logs: נתונים: 0.08MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_followup_email_orders: נתונים: 1.52MB + אינדקס: 0.39MB + מנוע InnoDB
kwu_followup_email_tracking: נתונים: 0.06MB + אינדקס: 0.08MB + מנוע InnoDB
kwu_followup_followup_history: נתונים: 2.52MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_followup_order_categories: נתונים: 0.36MB + אינדקס: 0.42MB + מנוע InnoDB
kwu_followup_order_items: נתונים: 0.19MB + אינדקס: 0.28MB + מנוע InnoDB
kwu_followup_subscribers: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_followup_subscribers_to_lists: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_followup_subscriber_lists: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_gf_addon_feed: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_gf_draft_submissions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_gf_entry: נתונים: 0.30MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_gf_entry_meta: נתונים: 0.22MB + אינדקס: 0.38MB + מנוע InnoDB
kwu_gf_entry_notes: נתונים: 0.19MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_gf_form: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_gf_form_meta: נתונים: 0.05MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_gf_form_revisions: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_gf_form_view: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_gf_rest_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_import_detail_log: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_import_log_detail: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_import_postID: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_jet_post_types: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_jet_taxonomies: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_offline_giftcard: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_options: נתונים: 23.03MB + אינדקס: 1.73MB + מנוע InnoDB
kwu_pmxe_exports: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_pmxe_google_cats: נתונים: 0.39MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_pmxe_posts: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_pmxe_templates: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_postmeta: נתונים: 263.30MB + אינדקס: 37.13MB + מנוע InnoDB
kwu_posts: נתונים: 41.11MB + אינדקס: 7.06MB + מנוע InnoDB
kwu_rank_math_404_logs: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_rank_math_internal_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_rank_math_internal_meta: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_rank_math_redirections: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_rank_math_redirections_cache: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_rank_math_sc_analytics: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_redirection_404: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_redirection_groups: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_redirection_items: נתונים: 0.22MB + אינדקס: 0.28MB + מנוע InnoDB
kwu_redirection_logs: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_smackcsv_file_events: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_smackuci_events: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_smush_dir_images: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_termmeta: נתונים: 0.11MB + אינדקס: 0.14MB + מנוע InnoDB
kwu_terms: נתונים: 0.05MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_term_relationships: נתונים: 0.47MB + אינדקס: 0.41MB + מנוע InnoDB
kwu_term_taxonomy: נתונים: 0.06MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_tm_taskmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_tm_tasks: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_ultimate_csv_importer_acf_fields: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_ultimate_csv_importer_mappingtemplate: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_ultimate_csv_importer_media: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_ultimate_csv_importer_shortcode_manager: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_usermeta: נתונים: 1.52MB + אינדקס: 0.86MB + מנוע InnoDB
kwu_users: נתונים: 0.08MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_wcsc_error_logs: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wcsc_logs: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_wc_admin_notes: נתונים: 0.06MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wc_admin_note_actions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wc_category_lookup: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wc_customer_lookup: נתונים: 0.22MB + אינדקס: 0.20MB + מנוע InnoDB
kwu_wc_download_log: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_wc_order_bundle_lookup: נתונים: 0.02MB + אינדקס: 0.08MB + מנוע InnoDB
kwu_wc_order_coupon_lookup: נתונים: 0.05MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_wc_order_product_lookup: נתונים: 0.52MB + אינדקס: 0.75MB + מנוע InnoDB
kwu_wc_order_stats: נתונים: 0.30MB + אינדקס: 1.00MB + מנוע InnoDB
kwu_wc_order_tax_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_wc_product_meta_lookup: נתונים: 1.52MB + אינדקס: 2.42MB + מנוע InnoDB
kwu_wc_rate_limits: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wc_reserved_stock: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wc_tax_rate_classes: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wc_webhooks: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_wc_zapier_history: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wdr_order_discounts: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wdr_order_item_discounts: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wdr_rules: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfblockediplog: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfblocks7: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_wfconfig: נתונים: 0.45MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfcrawlers: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wffilechanges: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wffilemods: נתונים: 2.52MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfhits: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_wfhoover: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wfissues: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_wfknownfilelist: נתונים: 1.52MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wflivetraffichuman: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wflocs: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wflogins: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_wfls_2fa_secrets: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wfls_settings: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfnotifications: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfpendingissues: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_wfreversecache: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_wfsnipcache: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_wfstatus: נתונים: 0.13MB + אינדקס: 0.09MB + מנוע InnoDB
kwu_wftrafficrates: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_woobe_history: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
kwu_woobe_history_bulk: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woocommerce_bundled_itemmeta: נתונים: 0.08MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_woocommerce_bundled_items: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woocommerce_gc_activity: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_woocommerce_gc_cards: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
kwu_woocommerce_gc_cardsmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_woof_query_cache: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_wpml_mails: נתונים: 100.05MB + אינדקס: 0.00MB + מנוע InnoDB
kwu_yith_wcwl: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_yith_wcwl_lists: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
kwu_yoast_indexable: נתונים: 10.47MB + אינדקס: 5.83MB + מנוע InnoDB
kwu_yoast_indexable_hierarchy: נתונים: 0.23MB + אינדקס: 0.38MB + מנוע InnoDB
kwu_yoast_migrations: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
kwu_yoast_primary_term: נתונים: 0.09MB + אינדקס: 0.13MB + מנוע InnoDB
kwu_yoast_seo_links: נתונים: 6.52MB + אינדקס: 3.03MB + מנוע InnoDB
kwu_yoast_seo_meta: נתונים: 0.13MB + אינדקס: 0.00MB + מנוע InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 5
aiosrs-schema: 5
attachment: 10880
br_filters_group: 1
br_product_filter: 4
custom_css: 1
cwginstocknotifier: 2315
elementor_font: 1
elementor_library: 24
elementor_snippet: 2
follow_up_email: 2
giftcard: 4
mc4wp-form: 1
nav_menu_item: 113
oembed_cache: 6
page: 34
post: 4
product: 1434
product_variation: 3425
project: 48
revision: 3553
shop_coupon: 21
shop_order: 2556
sp_wps_shortcodes: 1
wafs: 1
wc_zapier_feed: 1
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ❌
					החנות לא משתמשת בHTTPS. מידע נוסף על HTTPS ותעודות SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

ווקומרס: מאת חברת אוטומטיק – 6.1.0

### Inactive Plugins (71) ###

Add-on: Export CSV - Back In Stock Notifier for WooCommerce: מאת codewoogeek – 1.4
Advanced AJAX Product Filters for WooCommerce: מאת BeRocket – 1.6.1.1
Advanced Custom Fields PRO: מאת Delicious Brains – 5.11.1
Advanced Local Pickup for WooCommerce: מאת zorem – 1.3.5
Advanced Order Export For WooCommerce: מאת AlgolPlus – 3.2.1
Ajax add to cart for WooCommerce: מאת QuadLayers – 1.2.6
Akismet Anti-Spam: מאת Automattic – 4.2.1
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: מאת codewoogeek – 100.10.2
BEAR – Bulk Editor and Products Manager Professional for WooCommerce: מאת realmag777 – 1.0.9
Bulk Edit Products, Prices & Attributes for Woocommerce: מאת ELEXtensions – 1.1.0
CeTu – Zap Mirror Site for WooCommerce: מאת Wisy – 1.0.0
Check & Log Email: מאת WPChill – 1.0.4
Checkout Fields Manager for WooCommerce: מאת QuadLayers – 5.5.2
Classic Editor: מאת WordPress Contributors – 1.6.2
Clear Cache For Me: מאת Webhead LLC – 1.7
Crocoblock Wizard: מאת Crocoblock – 1.1.0
Custom Post Type UI: מאת WebDevStudios – 1.10.1
Disable Comments: מאת WPDeveloper – 2.2.4
Duplicate Page: מאת mndpsingh287 – 4.4.6
Elementor: מאת Elementor.com – 3.5.2
Elementor Pro: מאת Elementor.com – 3.5.2
ELEX Bulk Edit Products, Prices & Attributes for Woocommerce: מאת ELEX – 2.6.0
Enable Accessibility: מאת uPress – 1.3.2
English WordPress Admin: מאת khromov – 1.5.1
Essential Addons for Elementor: מאת WPDeveloper – 4.9.6
Facebook for WooCommerce: מאת Facebook – 2.6.7
Follow-Up Emails: מאת WooCommerce – 4.9.14
Google Analytics and Google Tag Manager by WebKinder: מאת WebKinder – 1.9.4
Gravity Forms: מאת Gravity Forms – 2.5.14
Gravity Forms Mailchimp Add-On: מאת Gravity Forms – 5.0
Helastic Woocommerce Video: מאת Helastic – 1.0.9
iCount Payment Gateway: מאת iCount Systems – 1.5.6
Insert Headers and Footers: מאת WPBeginner – 1.6.0
JetEngine: מאת Crocoblock – 2.10.3
JetSmartFilters: מאת Crocoblock – 2.3.8
JetWooBuilder For Elementor: מאת Crocoblock – 1.11.4
Join.chat: מאת Creame – 4.1.15
Make Column Clickable Elementor: מאת Fernando Acosta – 1.3.1
MC4WP: Mailchimp for WordPress: מאת ibericode – 4.8.6
Media Library Assistant: מאת David Lingren – 2.98
NitroPack: מאת NitroPack LLC – 1.5.8
PixelYourSite: מאת PixelYourSite – 8.2.13
Prevent Browser Caching: מאת Kostya Tereshchuk – 2.3.2
Product Catalog Feed Pro by PixelYourSite: מאת PixelYourSite – 5.1.2
Product Slider and Carousel with Category for WooCommerce: מאת WP OnlineSupport – 102.1
Redirection: מאת John Godley – 5.1.3
Schema Pro: מאת Brainstorm Force – 2.1.1
Simple Custom Post Order: מאת Colorlib – 2.5.6
Smush Pro: מאת WPMU DEV – 3.9.4
Social Feed Gallery: מאת QuadLayers – 3.3.3
UberMenu 3 - The Ultimate WordPress Mega Menu: מאת Chris Mavricos
SevenSpark – 3.6.1

Ultimate Gift Cards For WooCommerce: מאת MakeWebBetter – 2.2.2
Ultimate WooCommerce Gift Cards-PRO: מאת MakeWebBetter – 3.0.3
WooCommerce Advanced Free Shipping: מאת Jeroen Sormani – 1.1.4
WooCommerce Breadcrumbs: מאת Anthony Hortin – 1.0.8
WooCommerce Cart Abandonment Recovery: מאת CartFlows Inc – 1.2.13
WooCommerce Extended Coupon Features FREE: מאת Soft79 – 3.2.8
WooCommerce Gift Cards: מאת SomewhereWarm – 1.8.0
WooCommerce Google Analytics Integration: מאת WooCommerce – 1.5.5
WooCommerce Load More Products: מאת BeRocket – 1.1.9.3
WooCommerce Product Bundles: מאת SomewhereWarm – 6.11.1
WooCommerce Zapier: מאת OM4 Software – 2.2.0
Woo Discount Rules: מאת Flycart – 2.3.10
Woo Discount Rules PRO 2.0: מאת Flycart – 2.3.7
WOOF - WooCommerce Products Filter: מאת realmag777 – 1.2.6.3
WP Crontrol: מאת John Blackbourn & crontributors – 1.12.0
WP Mail Logging: מאת Wysija – 1.10.2
WPMU DEV Dashboard: מאת WPMU DEV – 4.11.8
WP Ultimate CSV Importer: מאת Smackcoders – 6.3
YITH WooCommerce Wishlist: מאת YITH – 3.5.0
Yoast SEO: מאת Team Yoast – 17.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wgm_gift_card (wgm_gift_card)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

בסיס חנות: #326 - /shop/
סל קניות: #1128 - /cart/
תשלום: #1129 - /checkout/
החשבון שלי: #1130 - /my-account/
תנאי שימוש: ❌ דף לא מוגדר

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

הושלם: 125
Oldest: 2021-12-19 00:17:21 +0000
Newest: 2022-01-18 06:38:28 +0000

ממתין לאישור: 3
Oldest: 2022-01-18 06:39:17 +0000
Newest: 2022-01-18 17:31:42 +0000

נכשל: 50
Oldest: 2020-05-27 12:55:16 +0000
Newest: 2021-11-11 14:18:38 +0000

### Status report information ###

Generated at: 2022-01-18 06:38:29 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @arunschandran,

Thanks for taking the time to report this.  I'm having some trouble reproducing it on my end.  I've tried setting up some products of varying values and playing around with currency settings and such (but no luck).  Could I ask for a little more information from you?  Specifically:

Under WooCommerce > Settings > General, what currency options do you have set?  This is what I was testing with:

<img width="658" alt="Screen Shot 2022-01-18 at 12 05 08 PM" src="https://user-images.githubusercontent.com/80276/150010492-2cb3d3ee-62ce-484e-bc04-574887bae7c3.png">

Are you using Multicurrency support at all (WooCommerce > Settings > Multicurrency)? What currencies are you showing there?

Finally, any chance you'd be willing/able to share an export of your products?  Then I'd be able to import that and work with the same data you are to try to reproduce this.

Thanks!

**Comment by arunschandran** [comment]
Hi @lanej0 

This is the currency options in the site

![Screenshot (6)](https://user-images.githubusercontent.com/8776680/150065586-dd541271-49ca-4b0b-9701-9be7e796e47d.png)


If you could have a private messaging option or Email, I can send the product export there

Thanks,
Arun

**Comment by AashikP** [comment]
Hello @arunschandran 

Thank you for raising the issue. However, I can’t reproduce it on my end. Here's a screen recording of what I'm seeing:

[https://d.pr/i/1KoQi6](https://d.pr/i/1KoQi6)

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Comment by arunschandran** [comment]
In the screen recording I can see the issue. Please see the screenshot I added here which is taken from your screen recording. In the screenshot, you can se the sorting isn't working fine. It isn't sorted based on the price
![Screenshot (8)](https://user-images.githubusercontent.com/8776680/150124654-3cf4c924-72b3-4777-b8db-82d0020dbc0e.png)

**Comment by AashikP** [comment]
Hello @arunschandran 

In the screen-recording, I tried sorting in both ascending and descending orders. The screenshot you shared above is for the descending order.

Here are screenshots from the recording I shared previously:

1. Ascending order:

    ![https://d.pr/i/2fxESL+](https://d.pr/i/2fxESL+)

2. Descending order: (*includes most part of what you shared*)
   
    ![https://d.pr/i/xxhtAg+](https://d.pr/i/xxhtAg+)

Please feel free to add more details in case I'm missing something here.
