### ISSUE TITLE
Low stock email is not triggered via the API

### ISSUE THREAD

**Issue by thuautp** [woothemes/woocommerce#31664]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

4686173-zen

User here says that they have an external system that updates product stock via the API. When the stock goes below the low or no stock threshold, they do *not* receive an email. 

@vedanshujain [confirmed this was a bug](https://a8c.slack.com/archives/C7U3Y3VMY/p1642191794037300) and not intentional, hence this bug report.

### Expected behavior

Low stock email should be triggered via API when stock goes below the low stock threshold.

### Actual behavior

User mentioned:

>  I have tested over API via postman via this call:
> https://visitsiberia.voxop.dk/wp-json/wc/v3/products/16440?stock_quantity=0
> This does write down stock but does not trigger "sold out" or "low
> stock" emails.

### Steps to reproduce

`wc_maybe_reduce_stock_levels ()` (which eventually fires off the email) is only hooked into order-related actions here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-stock-functions.php#L112-L115

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woosite.mystagingwebsite.com
Site address (URL): https://woosite.mystagingwebsite.com
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 16.85MB
Database Data Size: 8.19MB
Database Index Size: 8.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.34MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ced_ebay_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_discription_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_FmeCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 1.50MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

afadv_qty: 1
af_crt_order_rstrct: 1
attachment: 40
aw_workflow: 13
bookable_person: 6
bookable_resource: 2
customize_changeset: 4
custom_css: 2
event_ticket: 1
follow_up_email: 1
gtw_custom_fields: 3
gtw_rules: 1
mc4wp-form: 1
nav_menu_item: 4
order_shipment: 4
page: 29
post: 3
pos_outlet: 1
pos_receipt: 1
pos_register: 1
prl_engine: 1
product: 164
product_variation: 170
revision: 64
rts_order_rule: 1
shipping_package: 3
shop_coupon: 5
shop_order: 227
shop_order_refund: 5
shop_subscription: 46
slide: 1
user_request: 1
warranty_request: 1
wc-donation: 1
wcpf_item: 12
wcpf_project: 1
wc_booking: 23
wc_membership_plan: 1
wc_order_status: 11
wc_pickup_location: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Cart and Order Restrictions: by Addify – 1.0.1
WooCommerce Bookings: by WooCommerce – 1.15.43 (update to version 1.15.49 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce Payments: by Automattic – 3.5.0
WooCommerce: by Automattic – 6.1.0
WP Mail Logging: by Wysija – 1.10.2

### Inactive Plugins (67) ###

Akismet Anti-Spam: by Automattic – 4.2.1
AutomateWoo: by WooCommerce – 5.5.4
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.2
Bookings Helper: by WooCommerce – 1.0.3
Classic Widgets: by WordPress Contributors – 0.2
Code Snippets: by Code Snippets Pro – 2.14.1
eBay Integration for Woocommerce: by CedCommerce – 2.0.4
Facebook for WooCommerce: by Facebook – 2.6.8
Google Listings and Ads: by WooCommerce – 1.10.0
Jetpack: by Automattic – 10.6-a.1
Loco Translate: by Tim Whitlock – 2.5.5
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Meks Quick Plugin Disabler: by Meks – 1.0
Order Restrictions for WooCommerce: by FantasticPlugins – 1.3
Product Filters for WooCommerce: by WooCommerce – 1.2.5 (update to version 1.2.8 is available)
Say What?: by Ademti Software – 2.0.2
Storefront Mega Menus: by WooCommerce – 1.6.2
Storefront Powerpack: by WooCommerce – 1.6.1
Teams for WooCommerce Memberships: by SkyVerge – 1.6.0 (update to version 1.6.2 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24 (update to version 1.1.25 is available)
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.6.0 (update to version 1.7.0 is available)
WooCommerce Advanced Notifications: by WooCommerce – 1.2.36
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
WooCommerce All Products For Subscriptions: by WooCommerce – 3.1.33 (update to version 3.2.0 is available)
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.29 (update to version 2.4.31 is available)
WooCommerce AvaTax: by SkyVerge – 1.12.0 (update to version 1.15.0 is available)
WooCommerce Back In Stock Notifications: by SomewhereWarm – 1.2.0
WooCommerce Blocks: by Automattic – 6.7.0
WooCommerce Box Office: by WooCommerce – 1.1.34 (update to version 1.1.36 is available)
WooCommerce Brands: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1 (update to version 1.7.0 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.11.0 (update to version 1.12.0 is available)
WooCommerce Currency Converter: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Deposits: by WooCommerce – 1.5.6 (update to version 1.5.7 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.1
WooCommerce Gift Cards: by WooCommerce – 1.10.0
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.5 (update to version 2.9.10 is available)
WooCommerce Memberships: by SkyVerge – 1.22.5 (update to version 1.22.9 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Order Barcodes: by WooCommerce – 1.3.23 (update to version 1.3.24 is available)
WooCommerce Order Status Manager: by SkyVerge – 1.13.2 (update to version 1.13.3 is available)
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce Points and Rewards: by WooCommerce – 1.7.2 (update to version 1.7.5 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.30
WooCommerce Product Add-ons: by WooCommerce – 4.4.0 (update to version 4.5.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.13.2 (update to version 6.13.3 is available)
WooCommerce Product Recommendations: by WooCommerce – 1.4.15
WooCommerce Product Vendors: by WooCommerce – 2.1.51 (update to version 2.1.58 is available)
WooCommerce Royal Mail: by WooCommerce – 2.5.34 (update to version 2.5.39 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.13 (update to version 2.3.17 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.32 (update to version 3.6.39 is available)
WooCommerce Software Add-On: by WooCommerce – 1.7.19
WooCommerce Square: by WooCommerce – 2.7.0
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions: by WooCommerce – 3.1.5 (update to version 3.1.6 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36
WooCommerce UPS Shipping: by WooCommerce – 3.2.34 (update to version 3.2.37 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.50 (update to version 4.4.69 is available)
WooCommerce Warranty Requests: by WooCommerce – 1.9.30 (update to version 1.9.31 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.38 (update to version 1.7.40 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP STAGING: by WP-STAGING – 2.9.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #15 - /communication-preferences/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Payments ###

Version: 3.5.0
Connected to WPCOM: Yes
Blog ID: 191000457
Account ID: acct_1IpV8z2HOdqomKRe

### Action Scheduler ###

Complete: 765
Oldest: 2022-01-05 10:16:09 +0000
Newest: 2022-01-18 10:39:22 +0000

Failed: 12
Oldest: 2021-09-21 11:03:07 +0000
Newest: 2021-09-30 10:07:17 +0000

Pending: 20
Oldest: 2022-01-18 11:35:02 +0000
Newest: 2022-10-22 12:45:17 +0000

### Status report information ###

Generated at: 2022-01-18 11:24:29 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by simplysaru** [comment]
Can confirm this still reproducible in 6.2.0

**Comment by DontFollowMeDownItsRocky** [comment]
Seconded - a little OT here not API call, but I use ajax in an admin page to decrement stock by barcode in a continuous stream-style POS I made for computer illiterate staff. I face the same issue because I'm not creating individual Order objects for every single product scanned in a day (hundreds) the emails never get triggered.

**Comment by prokopsdk** [comment]
Hej!
    Jeg holder ferie til d. 14. August , så jeg behandler
      henvendelser primært om aftenen. 
    
    Hvis henvendelsen er akut så send en SMS på 25 99 83 47.
     -- 
      Med venlig hilsen
      
      
        
        
          
            Prokop
              Suchánek
            
             VOXOP 
            
             WooCommerce
              Eksperten
            
             tlf: 25 99 83 47 
            cvr: 
                35 11 77 41
