### ISSUE TITLE
Downloadable Product Permissions: The text "-1" is rendered every time merchants click the "Grant access" button without entering any product

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#31678]
### Description
When editing orders, if you go to the "Downloadable product permissions" section and click the "Grant access" button without selecting any downloadable product, a "-1" is rendered in the component.

### To Reproduce
1. Create an order.
2. Open the order and go to the "Downloadable product permissions" section at the bottom.
3. Make sure you have not searched any product.
4. Click the "Grant access" button.

### Actual behavior
A text with the value `-1` appears in the component.

### Video
https://user-images.githubusercontent.com/45979455/149620893-0c46e051-6a58-412c-a33d-3af6972940d2.mp4

### Expected behavior
I can see 3 expected behaviours, so this would be open to discussion:
- Nothing should happen.
- Users should be notified that they need to enter a valid downloadable product so that they can grant access.
- The "Grant access" button is disable is no product is entered.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

**Comment by lanej0** [comment]
Hi @alopezari ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

1. Create an order with a downloadable product
2. Click on the order listed on WooCommerce > Orders
3. Scroll down to Downloadable product permissions
4. Click on Grant access

<img width="561" alt="Screen Shot 2022-01-18 at 2 16 33 PM" src="https://user-images.githubusercontent.com/80276/150027502-b124726c-fd15-4fa3-b92d-840dbc809f0e.png">

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by mt8** [comment]
Yey ✌️
