### ISSUE TITLE
Redirect users not logged in to login / register page (Request new feature)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#31684]
### Describe the solution you'd like

hello

Please add a feature to WooCommerce so that users who have not logged in and want to log in to the payment page will be automatically redirected to the login / registration page. Now, WooCommerce has put very simple settings for this part. In this way, if the user who has not logged in refers to the payment slip, only the text "You must log in first" is displayed, which is not interesting at all.
Please consider this suggestion.

thank you

**Comment by Michaelgimii** [comment]
+1

**Comment by barryhughes** [comment]
Sorry for the delay here.

I'm not sure I completely understand ... are you asking for a new setting, something like *'Force users to login or register before checking out'* and, when that is enabled, we take them to the login page *before* letting them access the checkout page?

It's an interesting idea, though I tend to think it's something better handled as a customization (but, I wanted to check I'm understanding correctly in the first instance).

**Comment by coreymckrill** [comment]
Since this enhancement request has been awaiting clarification for a few months and is, at this point, stale, I'm going to close it. Feel free to reopen if you have more details to add.
