### ISSUE TITLE
Blank screens on Safari

### ISSUE THREAD

**Issue by VanWebDev** [woothemes/woocommerce#31694]
On updating to the latest version of WooCommerce, the Home and Customers pages in WP Admin are both blank on Safari (Mac). I can see them on chrome, but even after clearing caches and transients they remain blank on Safari. System info attached.

`
### WordPress Environment ###

WordPress address (URL): https://vancouverwebdev.com/devsites/elektra/content
Site address (URL): https://vancouverwebdev.com/devsites/elektra
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.37
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 25.03MB
Database Data Size: 21.22MB
Database Index Size: 3.81MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.05MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_facebook_feed_locator: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cff_feeds: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cff_feed_caches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cff_sources: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_cf_forms: Data: 2.23MB + Index: 0.00MB + Engine MyISAM
wp_cf_form_entries: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_cf_form_entry_meta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_cf_form_entry_values: Data: 0.28MB + Index: 0.11MB + Engine MyISAM
wp_cf_pro_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cf_queue_failures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cf_queue_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cf_tracking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cf_tracking_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_cpk_wpcsv_export_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cpk_wpcsv_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_tickets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_em_tickets_bookings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_evr_answer: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_evr_attendee: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_evr_category: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_evr_cost: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_evr_event: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_evr_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_evr_payment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_evr_question: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ImgSlider_plugin: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_pictures: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 5.90MB + Index: 0.09MB + Engine MyISAM
wp_podsrel: Data: 0.17MB + Index: 0.58MB + Engine MyISAM
wp_pods_alpha: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pods_alphabetical: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 3.56MB + Index: 1.27MB + Engine MyISAM
wp_posts: Data: 1.94MB + Index: 0.45MB + Engine MyISAM
wp_products_brandsmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_products_categoriesmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rednao_smart_forms_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rednao_smart_forms_entry_detail: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_rednao_smart_forms_table_name: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rednao_smart_forms_uploaded_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfconfig: Data: 2.17MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wp_wfhits: Data: 0.57MB + Index: 0.12MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 2.89MB + Index: 0.35MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wflogins: Data: 0.30MB + Index: 0.08MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.39MB + Index: 0.16MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_also_bought: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_cart_contents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_cart_item_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_checkout_forms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_claimed_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_coupon_codes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_currency_list: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_download_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_product_rating: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_purchase_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_purchase_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_region_tax: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_submited_form_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_visitors: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_visitor_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

_pods_field: 39
_pods_pod: 16
attachment: 2041
cds: 17
composers: 355
concerts_events: 5
displayed_gallery: 1
gal_display_source: 10
home_section: 6
lightbox_library: 14
mc4wp-form: 1
mep_events: 5
mep_events_attendees: 67
mep_events_reg_form: 1
mp_order: 69
nav_menu_item: 136
ngg_gallery: 12
ngg_pictures: 58
page: 106
performances: 85
pieces: 581
post: 44
product: 27
revision: 26
shop_coupon: 22
shop_order: 37
slide: 7
smartforms_preview: 1
soliloquy: 7
weekly_email_archive: 32
wpsc_cart_orders: 50

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Admin Menu Editor: by Janis Elsts – 1.10
AdminPad: by Iftekhar Bhuiyan – 1.8
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.2
Smash Balloon Custom Facebook Feed: by Smash Balloon – 4.1.1
Google XML Sitemaps: by Auctollo – 4.1.1
Event Manager and Tickets Selling Plugin for WooCommerce: by MagePeople Team – 3.5.7
MagePeople PDF Support: by MagePeople Team – 2.0
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.8.8.1
Post Types Order: by Nsp Code – 1.9.7
Smart Forms - Summary: by RedNao – 1
Smart Forms - Stripe: by  –
Smart Forms - WooCommerce: by RedNao – 0.1
Smart Forms: by RedNao – 2.6.68
Widget Logic: by WPChef – 5.10.4
Woocommerce Event Manager Addon: Coupon: by MagePeople Team – 1.0.1
Woocommerce Event Manager Addon: Form Builder: by MagePeople Team – 3.8.3
Woocommerce Event Manager Addon: Global Quantity: by MagePeople Team – 1.0.4
Woocommerce Event Manager Addon: Recurring Events: by MagePeople Team – 2.2.2
Woocommerce Event Manager Addon: PDF Tickets: by MagePeople Team – 3.8.3
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce: by Automattic – 6.1.1
Wordfence Security: by Wordfence – 7.5.7
Multi-Step Checkout for WooCommerce: by SilkyPress – 2.19

### Inactive Plugins (8) ###

All-in-One WP Migration: by ServMask – 7.53
All-in-One WP Migration File Extension: by ServMask
Inc. – 1.8

All-in-One WP Migration Unlimited Extension: by ServMask – 2.40
Caldera Forms: by Caldera Forms – 1.9.6
Caldera Forms Stripe: by Caldera Labs – 1.4.11
CalderaWP License Manager: by CalderaWP – 1.2.11
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
NextGEN Gallery: by Imagely – 3.22

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8948 - /shop/
Cart: #8949 - /cart/
Checkout: #8950 - /checkout/
My account: #8951 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty Child
Version: 1.0
Author URL: https://vancouverwebdev.com/
Child Theme: ✔
Parent Theme Name: Twenty Twenty
Parent Theme Version: 1.8
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentytwenty-child/woocommerce/archive-product.php
twentytwenty-child/woocommerce/cart/cart-item-data.php
twentytwenty-child/woocommerce/cart/cart-shipping.php
twentytwenty-child/woocommerce/cart/cart-totals.php
twentytwenty-child/woocommerce/cart/cart.php
twentytwenty-child/woocommerce/checkout/cart-errors.php
twentytwenty-child/woocommerce/checkout/form-billing.php
twentytwenty-child/woocommerce/checkout/form-checkout.php
twentytwenty-child/woocommerce/checkout/form-coupon.php
twentytwenty-child/woocommerce/checkout/form-login.php
twentytwenty-child/woocommerce/checkout/form-pay.php
twentytwenty-child/woocommerce/checkout/form-shipping.php
twentytwenty-child/woocommerce/checkout/order-receipt.php
twentytwenty-child/woocommerce/checkout/payment-method.php
twentytwenty-child/woocommerce/checkout/payment.php
twentytwenty-child/woocommerce/checkout/review-order.php
twentytwenty-child/woocommerce/checkout/terms.php
twentytwenty-child/woocommerce/checkout/thankyou.php
twentytwenty-child/woocommerce/content-product.php
twentytwenty-child/woocommerce/content-single-product.php
twentytwenty-child/woocommerce/loop/add-to-cart.php
twentytwenty-child/woocommerce/loop/loop-end.php
twentytwenty-child/woocommerce/loop/loop-start.php
twentytwenty-child/woocommerce/loop/price.php
twentytwenty-child/woocommerce/myaccount/dashboard.php
twentytwenty-child/woocommerce/myaccount/downloads.php
twentytwenty-child/woocommerce/myaccount/my-account.php
twentytwenty-child/woocommerce/myaccount/my-downloads.php
twentytwenty-child/woocommerce/myaccount/my-orders.php
twentytwenty-child/woocommerce/myaccount/navigation.php
twentytwenty-child/woocommerce/myaccount/orders.php
twentytwenty-child/woocommerce/myaccount/view-order.php
twentytwenty-child/woocommerce/notices/error.php
twentytwenty-child/woocommerce/notices/notice.php
twentytwenty-child/woocommerce/notices/success.php
twentytwenty-child/woocommerce/order/order-details-customer.php
twentytwenty-child/woocommerce/order/order-details-item.php
twentytwenty-child/woocommerce/order/order-details.php
twentytwenty-child/woocommerce/order/order-downloads.php
twentytwenty-child/woocommerce/single-product/price.php
twentytwenty-child/woocommerce/single-product/product-attributes.php
twentytwenty-child/woocommerce/single-product/product-image.php
twentytwenty-child/woocommerce/single-product/product-thumbnails.php
twentytwenty-child/woocommerce/single-product/short-description.php
twentytwenty-child/woocommerce/single-product/title.php
twentytwenty-child/woocommerce/single-product.php
twentytwenty-child/woocommerce/taxonomy-product-cat.php

### Action Scheduler ###

Complete: 10
Oldest: 2022-01-21 09:46:14 -0800
Newest: 2022-01-21 10:28:04 -0800

### Status report information ###

Generated at: 2022-01-21 10:32:42 -08:00
`

**Comment by swatipawarGS** [comment]
Hi @VanWebDev ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.1.1 version and WordPress 5.8.3 version.

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/150741844-a3ac3270-d91b-45b4-9a93-fb7fef87c977.mp4

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by rrennick** [comment]
Closing due to lack of feedback.
