### ISSUE TITLE
WooCommerce functionality development (Select a variable on the products page)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#31704]
### Describe the solution you'd like

hello

n the single product page, a new price appears in addition to the existing price if we select the variables. Therefore, two prices are displayed. This is not really good and it completely destroys the user interface. Simultaneous display of prices is also confusing for users. Especially if there is a selle price. https://prnt.sc/26i3vct

### Describe alternatives you've considered

I think it is better for WooCommerce to develop its performance in this area. **It is better not to add a new price by selecting any variable. But the previous price is updated.** 
For example, we have a product whose price changes based on different variables. The user enters the product page, and for example the price of that product is $ 100. Now the user selects the variable and by selecting each variable, the previous price ($ 100) is updated. (Depending on the choice of the price variable will be more or less.)

To better understand this issue, please watch this video : 

https://user-images.githubusercontent.com/77163248/150688123-33751245-e138-442e-874e-b3288350955e.mp4

**As you can see in the video above, after selecting the variable (color), the price was automatically updated.**

**Comment by rrennick** [comment]
@79ho3ein Could you provide a system status report and confirm you see this behavoiur with a default theme and no extensions active?
