### ISSUE TITLE
Add troubleshoot guide to solve common issues when e2e tests fail locally

### ISSUE THREAD

**Issue by Luc45** [woothemes/woocommerce#31747]
E2E tests might fail to complete successfuly on the local development environment of a developer, while it works on the same branch for another developer.

We should write a troubleshoot guide with the most common issues and solutions when e2e tests are failing locally.

For instance, one good item to add to the troubleshoot is running `pnpm install --force` to make sure you pnpm installs fresh versions of `node_module` dependencies.

**Comment by rrennick** [comment]
Closing this as we no longer use the e2e-environmant package
