### ISSUE TITLE
E2E packages should behave the same when in the monorepo and package contexts

### ISSUE THREAD

**Issue by Luc45** [woothemes/woocommerce#31748]
When `@woocommerce/e2e-core-tests` is used in the monorepo and require code from one of the monorepo packages (`@woocommerce/e2e-environment`, `@woocommerce/e2e-utils`, `@woocommerce/api`), the code that is loaded is the one inside the `src` folder. However, when running these tests outside the monorepo context, the code that is executd from these packages are those that are inside the `build` or `build-module` folders.

We should simplify this and have a predictable code being used at runtime: Either always `build` or always `build-module`, for instance.

This should help us catch any issues that would only occur if the packages were to be executed outside the monorepo, as we would be running the exact same code in monorepo and package contexts.

**Comment by rrennick** [comment]
> Either always build or always build-module, for instance.

In places where the path is explicit I have used `build`. The `api` package is currently [`dist`](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/api/tsconfig.json#L6).
