### ISSUE TITLE
[COT] Implement function to query non-migrated data

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31769]
To assure data integrity, we would need to implement functions that can tell if there are orders data wp_posts table that is not migrated yet, or if the migration is outdated for the custom order table. This function will be used to support re-entry, opt-in/opt-out, etc features.

Contributes towards #31599

**Comment by peterfabian** [comment]
Only id mismatches or update timestamp mismatches in this issue, we need to find a performant way to compare the tables.

Maybe later/nice to have would be to add checksums.
