### ISSUE TITLE
[COT] Implement basic sync functions to move data into wc_order custom table

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31766]
This issue scopes implementing basic functions that we will use to migrate data into wc_order custom table from wc_posts.

Depends on #31596

Contributes towards #31599

**Comment by peterfabian** [comment]
The function gets the order number and migrates the data (inserts it into the new table), this includes testing to ensure data is compatible, etc.

It should also handle failure correctly by throwing an exception.
