### ISSUE TITLE
[Enhancement]: offset item on shortcode

### ISSUE THREAD

**Issue by odirlon** [woothemes/woocommerce#31778]
### Describe the solution you'd like

Would it be possible to add offset item on shortcode?

### Describe alternatives you've considered

Today we give display none on the first items via CSS to be able to put a banner in the middle of the ilstage, but it doesn't look fancy.

### Additional context

We have divided the home page into 2 sessions of featured products, hence these sessions are divided by a banner.

**Comment by rrennick** [comment]
@odirlon I apologize for the long delay in responding. Could you clarify which shortcode you are referring to and what changes are are you looking to see with the attribute?

**Comment by odirlon** [comment]
Hi, we solved it with our internal development. But basically it would be adding the "off-set" tag to remove products from the front of the loop...
