### ISSUE TITLE
pnpm publish branch needs updating

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31828]
The following warning is issued when running `pnpm publish`:

```
$ pnpm publish
? You're on branch "xxx" but your "publish-branch" is set to "master|main". Do you want to continue? (y/N) › false
```

Neither of the choices are current branches.

**Comment by irfan-maulana-tkp** [comment]
https://github.com/pnpm/pnpm/issues/2995

**Comment by rrennick** [comment]
Closing as I assume this one has been addressed.
