### ISSUE TITLE
[Enhancement]: Include order ID if in the error log message when possible

### ISSUE THREAD

**Issue by terriann** [woothemes/woocommerce#31824]
### Describe the solution you'd like

If an order fails to save, a log entry is created in the `wp_woocommerce_log` table which displays on `/wp-admin/admin.php?page=wc-status&tab=logs` page with the message `Error saving order`. That message is the same whether there was, or was not, an existing order ID associated with that entry.

It would help store managers to triage what (if any) steps are needed if the message included the order ID. In [`/plugins/woocommerce/includes/abstracts/abstract-wc-order.php`](https://github.com/woocommerce/woocommerce/blob/c36d25af713d55cb4b97e25ef3b99ffe5fc78ab5/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L177-L204) where the log entry is created, it should be possible to have two messages to handle the cases, for example: `Error saving order id 123` or `Error saving order (no ID)`.

### Describe alternatives you've considered

The current workaround is to read the ID from the serialized contents inside the `context` field in the `wp_woocommerce_log` database table. If a user doesn't have access to the database there is no other way to get that ID. There are related suggestions about providing additional access to this information in woocommerce/woocommerce/issues/31823

**Comment by johnregan3** [comment]
@barryhughes Tagging just so there is some visibility on this PR.  Feel free to reassign as needed.
