### ISSUE TITLE
Woocommerce Square wc-square.js prevents inline validation upon submit of checkout form

### ISSUE THREAD

**Issue by carasmo** [woothemes/woocommerce#31832]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Woocommerce Square wc-square.js prevents inline validation upon submit of checkout form

No matter the theme, when Square is being used as the gateway, the script wc-square.min.js prevents the frontent/checkout.min.js from adding classes on the input parent and so the user has zero clue what field (besides the message at the top). 

### Expected behavior

The classes should be added. They are not. When other gateways are used, the classes are added upon submit. 

### Actual behavior

No classes are added to the parent.

### Steps to reproduce

Install and activate Square either sandbox or live. Use any theme. 

### WordPress Environment

Latest all.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by carasmo** [comment]
Added the following to the `render_errors( errors ) ` function and registered the same handle in my theme. 

`
			this.form.find(  '.input-text, select, input:checkbox' ).trigger( 'validate' ).trigger( 'blur' );
`

**Comment by ObliviousHarmony** [comment]
Hi @carasmo,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Square plugin. To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.

**Comment by carasmo** [comment]
The plugin is created by [WooCommerc](https://wordpress.org/plugins/woocommerce-square/)e and I reported it on the support forum for the 1 star plugin. They were no help either. It's a VERY SIMPLE fix too.

**Comment by ObliviousHarmony** [comment]
Hello @carasmo,

While that may be true, that is maintained by a different team and this is a repository for WooCommerce Core. As I said, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/)!

**Comment by badfeather** [comment]
I have a related issue, but don't see any repos for the WooCommerce Square plugin on Github, even though the other payment gateway integrations developed by WooCommerce are on here. Does it possibly exist elsewhere?
