### ISSUE TITLE
WebAPI: ProductAttribute list always contains the same elements

### ISSUE THREAD

**Issue by giacomoarru** [woothemes/woocommerce#31848]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While retrieving Product Attributes, I found a problem with the pagination.
I only have 1 attribute, but I get the same result for every page.

verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=1
verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=2
verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=3

and so on

the result is always the same: a page with 1 element, instead of empty pages.

### Expected behavior

The API should return an empty page starting from page 2

### Actual behavior

The API always returns page 1

### Steps to reproduce

Create 1 Product Attribute

Get API response for the following endpoints:
verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=1
verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=2
verb: GET; endpoint /wp-json/wc/v3/products/attributes?page=3

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://leoeluna-dev.x2x.cloud
Site address (URL): https://leoeluna-dev.x2x.cloud
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wptw_
Dimensione totale database: 44.45MB
Dimensione dati database: 40.64MB
Dimensione indice database: 3.81MB
wptw_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wptw_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wptw_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_actionscheduler_actions: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
wptw_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wptw_e_submissions: Dati: 0.02MB + indice: 0.27MB + motore InnoDB
wptw_e_submissions_actions_log: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wptw_e_submissions_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_mailchimp_jobs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_mailpoet_custom_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_dynamic_segment_filters: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_feature_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_mailpoet_log: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_mailpoet_mapping_to_external_entities: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_newsletter_links: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_mailpoet_newsletter_option: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_newsletter_option_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_newsletter_posts: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_newsletter_segment: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_newsletter_templates: Dati: 2.52MB + indice: 0.00MB + motore InnoDB
wptw_mailpoet_newsletters: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_scheduled_task_subscribers: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_scheduled_tasks: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_segments: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_sending_queues: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_settings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_statistics_clicks: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_mailpoet_statistics_forms: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_statistics_newsletters: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_statistics_opens: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wptw_mailpoet_statistics_unsubscribes: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_mailpoet_statistics_woocommerce_purchases: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wptw_mailpoet_stats_notifications: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_subscriber_custom_field: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_subscriber_ips: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_subscriber_segment: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_mailpoet_subscribers: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
wptw_mailpoet_user_agents: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_mailpoet_user_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_options: Dati: 3.11MB + indice: 0.06MB + motore InnoDB
wptw_postmeta: Dati: 24.50MB + indice: 0.61MB + motore InnoDB
wptw_posts: Dati: 8.52MB + indice: 0.25MB + motore InnoDB
wptw_smush_dir_images: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_usermeta: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wptw_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wptw_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wptw_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wptw_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_wpforms_tasks_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza_circles: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza_maps: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza_polygon: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza_polylines: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_wpgmza_rectangles: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wptw_yoast_indexable: Dati: 0.11MB + indice: 0.09MB + motore InnoDB
wptw_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wptw_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wptw_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wptw_yoast_seo_links: Dati: 0.02MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

astra-advanced-hook: 1
attachment: 92
elementor_library: 3
gdpr_service: 3
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 8
page: 14
post: 2
revision: 941
sp_wps_shortcodes: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Redux: by Extendify – 4.3.5
Astra Pro: by Brainstorm Force – 3.6.0
Astra Bulk Edit: by Brainstorm Force – 1.2.6
Import / Export Customizer Settings: by Brainstorm Force – 1.0.5
Astra Widgets: by Brainstorm Force – 1.2.9
Join.chat: by Creame – 4.1.15
Custom Fonts: by Brainstorm Force – 1.3.3
Custom Adobe Fonts (Typekit): by Brainstorm Force – 1.0.18
Customizer Search: by Brainstorm Force – 1.1.6
Elementor Pro: by Elementor.com – 3.4.1
Elementor: by Elementor.com – 3.5.3
Facebook for WooCommerce: by Facebook – 2.6.8
Gallery Slider for WooCommerce: by ShapedPlugin – 1.1.1
Site Kit by Google: by Google – 1.48.1
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.9.1
Jetpack: by Automattic – 10.4
Google Ads & Marketing di Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.4
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Maintenance: by WebFactory Ltd – 4.03
Product Variations Swatches for WooCommerce: by VillaTheme – 1.0.1.16
Astra Customizer Reset: by Brainstorm Force – 1.0.5
Sidebar Manager: by Brainstorm Force – 1.1.7
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.5.1
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.2.1
Product Slider for WooCommerce: by ShapedPlugin – 2.4.2
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WooCommerce PayPal Payments: by WooCommerce – 1.6.4 (aggiornamento alla versione 1.6.5 disponibile)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20 (aggiornamento alla versione 1.25.22 disponibile)
WooCommerce: by Automattic – 6.0.0 (aggiornamento alla versione 6.1.1 disponibile)
WordPress GDPR: by weLaunch – 1.9.20
Yoast SEO: by Team Yoast – 17.8
WPForms Lite: by WPForms – 1.7.1.2

### Inactive Plugins (1) ###

Smush: by WPMU DEV – 3.9.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /negozio/
Carrello: #9 - /carrello/
Pagamento: #10 - /pagamento/
Il mio account: #11 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Astra
Version: 3.7.0 (aggiornamento alla versione 3.7.7 disponibile)
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Action Scheduler ###

Completato: 27
Oldest: 2022-02-06 07:44:57 +0000
Newest: 2022-02-06 09:14:09 +0000

In attesa: 7
Oldest: 2022-02-06 14:26:15 +0000
Newest: 2022-02-07 07:43:44 +0000

### Status report information ###

Generated at: 2022-02-06 09:42:40 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vijayhardaha** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-attributes

Documentation says that the endpoint doesn't have any param for pagination.

**Comment by giacomoarru** [comment]
I see, my API manager is using an interface that inherits pagination for every entity and I assumed that was the same for WooCommerce.

Resolving.
