### ISSUE TITLE
[Enhancement]: Multi Vendor build-in

### ISSUE THREAD

**Issue by sanskritkm** [woothemes/woocommerce#31858]
### Describe the solution you'd like

I saw few tools out there, but why WC does not do build-in multi vendor?

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
