### ISSUE TITLE
Run linting on @woocommerce/api package in CI when it changes

### ISSUE THREAD

**Issue by Luc45** [woothemes/woocommerce#31856]
We should add a GitHub workflow that will run `npm run lint` in the `@woocommerce/api` package whenever files inside `woocommerce/packages/js/api/*` changes, as it helps with reducing code reviews for code style, and minimizes merge conflicts.

On a preliminarly investigation, if we run `woocommerce/packages/js/api && npm run lint` it throws 2k errors, of which 1700 are automatically fixable by running `npm run lint --fix`.

Of the remaning 300, I'd say 250 are `Expected preceding "Internal dependencies" comment block @woocommerce/dependency-group`, which we can ignore, and the remaining 50 would have to be looked over manually.

**Comment by adimoldovan** [comment]
This was implemented in the meantime. The package `@woocommerce/api` is included in the matrix of CI jobs and the lint script runs on changes to the package.
Ran the lint command locally and there are only a few warnings.
I will close this one. @Luc45 please reopen if needed.
