### ISSUE TITLE
MPN, GTIN and Brand included in Woocommerce out of the box[Enhancement]: 

### ISSUE THREAD

**Issue by accountsatelpengineering** [woothemes/woocommerce#31900]
### Describe the solution you'd like

Please include the fields MPN, GTIN and Brand into Woocommerce and allow a product search to find them.

Google feed mandatory requires the aforementioned the MPN or GTIN and BRAND sent in the product feed.

Customers need to search on my website for the MPN to find replacement products.

### Describe alternatives you've considered

I have had to comprimise and put the MPN and Brand data in GPF ( google product feed) and use Fibrosearch to discover them.

My SKU is not the same as the MPN.

### Additional context

Without a MPN search, customers cannot find my products in an out of the box installation.

**Comment by betayazilim** [comment]
Waiting like since forever

**Comment by skullo27** [comment]
Look at it this way... if google merchant center needs a field then surely it should be part of the core fields offered by an eCommerce system. In this case, brand, GTIN and MPN are all required by google so should be available in Woocommerce.

Furthermore, Shopify, Magento, and Bigcommerce all offer these fields so if Woocommerce wants to keep up with them they need to consider this seriously.

**Comment by accountsatelpengineering** [comment]
Can you also please include the **Google product Category** onto the product page.

I am using the google API to upload data and I have had to put a work around in Google merchant centre to class all my items with the same google product category to enable the feed to upload, google call this taxonomy and the input field is numeric.

Thanks in advance.  ED

**Comment by masteradhoc** [comment]
+1

**Comment by mattsherman** [comment]
Implemented by #49312

**Comment by betayazilim** [comment]
This should not be closed since MPN didn't add to core yet.
