### ISSUE TITLE
[Enhancement]: Button to delete ALL logs

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#31916]
### Describe the solution you'd like

Could we introduce some kind of button/action that will clear all the logs at once? 
![image](https://user-images.githubusercontent.com/507025/154526276-918ffa5d-192c-45c5-b1ef-b689ebc796e4.png)

### Describe alternatives you've considered

Currently the way to delete logs is to delete them one at a time, which can be quite slow if you have collected a lot of logs. I might be missing a setting somewhere else? But if so, it makes sense to have it here in this context

**Comment by Mte90** [comment]
Indeed it will be very helpful.

**Comment by coreymckrill** [comment]
@helgatheviking in 8.6 that was just released this week, the logging UI has been overhauled and you now have a list table of all your log files, from which you can select all of them at once and delete! Check out the [release post](https://developer.woo.com/2024/02/15/woocommerce-8-6-product-blocks-order-attribution-updates/#feature-highlight-improvements-to-debug-logging) for more details.
