### ISSUE TITLE
[Enhancement]: Pass a class for <tr valign="top"> using woocommerce_admin_fields() settings array

### ISSUE THREAD

**Issue by hakikz** [woothemes/woocommerce#31918]
### Describe the solution you'd like

Sometimes we add some extra settings _(to create WooCommerce base extension)_ and insert them into the tab of the WooCommerce settings. So, a wrapper class for **tr tag** would be great to create a dependent field. For example- selecting a value from the dropdown will hide a checkbox **tr tag**

**We can pass an array like this-**

```
array(
    'title'      => __( 'Add From', 'woocommerce' ),
    'id'        => 'test_id',
    'type'      => 'radio',
    'desc'     => __( 'Test Description', 'woocommerce' ),
    'class'     => 'checkbox-class',
    'tr_wrapper_class'     => 'my-class',
    'default'   => 'yes',
),
```
**For example:** 
_In woocommerce > includes > admin > class-wc-admin-settings.php line number 422_
We can set the 'tr_wrapper_class' (like below) to push our own class.
 ```
    // Radio inputs.
    case 'radio':
    $option_value = $value['value'];
    
    ?>
    <tr valign="top" class="<?php echo esc_attr( $value['tr_wrapper_class'] ); ?>">
```

**Comment by coreymckrill** [comment]
I believe this was implemented in #39912, but using `row_class` as the property name rather than `tr_wrapper_class`.
