### ISSUE TITLE
[Enhancement]: Estimated Delivery Dates for Japan eCommerce Shops

### ISSUE THREAD

**Issue by raifd** [woothemes/woocommerce#31945]
### Describe the solution you'd like

Looks like there will be some legislation changes for eCommerce shops in Japan starting from June 2022 that will require all shops to display the _estimated delivery time_ on the checkout page.

Here is a link to an article describing the new requirements: https://eczine.jp/article/detail/11020

### Additional context

4774831-zd-woothemes as a reference of this information

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this. We appreciate your help, and we're sorry for the late reply.

This issue will be closed. AFAIK the merchant is responsible for complying with the country's legislation, and some extensions provide this feature.
