### ISSUE TITLE
Fatal Error WC 6.2.1

### ISSUE THREAD

**Issue by naturalweb-business** [woothemes/woocommerce#31969]
After the last update we have this issue...

2022-02-23T08:36:20+00:00 CRITICAL Uncaught Error: Call to undefined function disk_free_space() in /www/XXXX/public/wp-admin/includes/file.php:1666
Stack trace:
#0 /www/XXXXX/public/wp-admin/includes/file.php(1586): _unzip_file_ziparchive('/tmp/woocommerc...', '/www/XXXXX...', Array)
#1 /www/XXXXXis_778/public/wp-admin/includes/class-wp-upgrader.php(329): unzip_file('/tmp/woocommerc...', '/www/XXXXX...')
#2 /www/XXXXXis_778/public/wp-admin/includes/class-wp-upgrader.php(780): WP_Upgrader->unpack_package('/tmp/woocommerc...', true)
#3 /www/XXXXXis_778/public/wp-admin/includes/class-language-pack-upgrader.php(256): WP_Upgrader->run(Array)
#4 /www/XXXXXis_778/public/wp-admin/includes/class-language-pack-upgrader.php(140): Language_Pack_Upgrader->bulk_upgrade(Array, Array)
#5 /www/XXXXXis_778/public/wp-admin/includes/class-wp-automatic-updater.php(403): Language_Pack_Upgrader->upgrade(Array, Array)
#6 /www/XXXXXis_778/public/wp-admin/includes/class-wp-automatic-updater.php(516): WP_Automatic_Updater->update('translation', Object(stdClass))
#7 /www/XXXXXis_778/public/wp-includes/update.php(729): WP_Automatic_Updater->run()
#8 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(307): wp_maybe_auto_update('')
#9 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#10 /www/XXXXXis_778/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#11 /www/XXXXXis_778/public/wp-includes/update.php(256): do_action('wp_maybe_auto_u...')
#12 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(307): wp_version_check()
#13 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#14 /www/XXXXXis_778/public/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#15 /www/XXXXXis_778/public/wp-cron.php(138): do_action_ref_array('wp_version_chec...', Array)
#16 {main}
  thrown en /www/XXXXXis_778/public/wp-admin/includes/file.php en la línea 1666

2022-02-23T13:02:32+00:00 CRITICAL Uncaught Error: Call to a member function get() on null in /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php:156
Stack trace:
#0 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(154): WC_Gateway_COD->is_available()
#1 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/OnboardingTasks/Tasks/Payments.php(89): WC_Payment_Gateways->get_available_payment_gateways()
#2 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/OnboardingTasks/Tasks/Payments.php(71): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments::has_gateways()
#3 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/OnboardingTasks/TaskList.php(152): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments->is_complete()
#4 [internal function]: Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->Automattic\WooCommerce\Admin\Features\OnboardingTasks\{closure}(true, Object(Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments))
#5 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/OnboardingTasks/TaskList.php(154): array_reduce(Array, Object(Closure), true)
#6 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php(173): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->is_complete()
#7 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php(44): WC_Admin_Dashboard_Setup->should_display_widget()
#8 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php(181): WC_Admin_Dashboard_Setup->__construct()
#9 /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin.php(102): include('/www/XXXXX...')
#10 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(307): WC_Admin->conditional_includes(Object(WP_Screen))
#11 /www/XXXXXis_778/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#12 /www/XXXXXis_778/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#13 /www/XXXXXis_778/public/wp-admin/includes/class-wp-screen.php(421): do_action('current_screen', Object(WP_Screen))
#14 /www/XXXXXis_778/public/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#15 /www/XXXXXis_778/public/wp-admin/admin.php(212): set_current_screen()
#16 /www/XXXXXis_778/public/wp-admin/index.php(10): require_once('/www/XXXXX...')
#17 {main}
  thrown en /www/XXXXXis_778/public/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php en la línea 156

**Comment by jonathansadowski** [comment]
Hi @naturalwebcl,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by naturalweb-business** [comment]
Hi Jonathan,

Thanks for your quick answer, we find the error, it was with a custom snippet and we deactivated, everything worked fine again:

add_filter( 'woocommerce_cart_needs_shipping', '__return_true' );
add_filter( 'woocommerce_cart_no_shipping_available_html', 'change_noship_message' );
add_filter( 'woocommerce_no_shipping_available_html', 'change_noship_message' );
function change_noship_message() {
    print "No hemos podido obtener costo en línea para tu envío.<br>Por favor comunícate con nosotros al <a href='tel:+XXXXXXX'>+XXXXXXXX</a> para buscar una alternativa.<br>Muchas gracias.";
}
