### ISSUE TITLE
[Enhancement]: Back Button support

### ISSUE THREAD

**Issue by davidjcreative** [woothemes/woocommerce#31963]
### Describe the solution you'd like

After I click on the pagination in the store, and navigate away from the page, I would like the page to remember what page I was looking at.

### Describe alternatives you've considered

A breadcrumb at the top of the product page that has the pagination number in the link.

**Comment by floyedxman** [comment]
how did you work it out ?

**Comment by davidjcreative** [comment]
@floyedxman I did not do a custom implementation. I just rolled with what WC provided. But I have wrote similar logic for other custom filters and thought it would be nice to see that in WC.
