### ISSUE TITLE
npm ERESOLVE error when using npm install

### ISSUE THREAD

**Issue by rinke300X** [woothemes/woocommerce#31988]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm following along the Getting Started guide for developers on [https://developer.woocommerce.com/extension-developer-guide/getting-started/](url).

After cloning and nvm use, I carry out the following command:

`npm install`

The following error is thrown:

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! ...

See below for the full error

### Expected behavior

No dependency errors and a clean install

### Actual behavior

The error:

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @nrwl/workspace@13.8.3
> npm ERR! Found: prettier@2.2.1-beta-1
> npm ERR! node_modules/prettier
> npm ERR!   dev prettier@"npm:wp-prettier@^2.2.1-beta-1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional prettier@"^2.5.1" from @nrwl/workspace@13.8.3
> npm ERR! node_modules/@nrwl/workspace
> npm ERR!   dev @nrwl/workspace@"^13.3.4" from the root project
> npm ERR!   @nrwl/workspace@"13.8.3" from @nrwl/web@13.8.3
> npm ERR!   node_modules/@nrwl/web
> npm ERR!     dev @nrwl/web@"^13.3.4" from the root project
> npm ERR!   2 more (@nrwl/cypress, @nrwl/js)
> npm ERR! 
> npm ERR! Conflicting peer dependency: prettier@2.5.1
> npm ERR! node_modules/prettier
> npm ERR!   peerOptional prettier@"^2.5.1" from @nrwl/workspace@13.8.3
> npm ERR!   node_modules/@nrwl/workspace
> npm ERR!     dev @nrwl/workspace@"^13.3.4" from the root project
> npm ERR!     @nrwl/workspace@"13.8.3" from @nrwl/web@13.8.3
> npm ERR!     node_modules/@nrwl/web
> npm ERR!       dev @nrwl/web@"^13.3.4" from the root project
> npm ERR!     2 more (@nrwl/cypress, @nrwl/js)
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Steps to reproduce

`cd /your/server/wp-content/plugins`

`git clone https://github.com/woocommerce/woocommerce.git`

`cd woocommerce`

`nvm use`

`npm install`

### WordPress Environment

No System Status Report, as WooCommerce can't be installed.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rinke300X** [comment]
pnpm was needed to build the project. Please update the documentation at the Getting Started guide for Devs mentioned in my original post.

**Comment by claudiosanches** [comment]
@rinke300X thanks for reporting this issue with our docs, indeed is required pnpm now to manage our monorepo dependencies. I made the necessary updates for that post.

There's also a quick guide for developers inside this project, you can check here: https://github.com/woocommerce/woocommerce/blob/trunk/DEVELOPMENT.md

Thanks!
