### ISSUE TITLE
GitHub actions for managing "needs: author feedback" labels too aggressive

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#32025]
@barryhughes reported that he removed `needs: developer feedback` and added `needs: author feedback` at the same time on [this issue](https://github.com/woocommerce/woocommerce/issues/30159). The action that manages labels removed `needs: author feedback` and added `needs: triage feedback`.

Notes: Maybe it's considering the addition of the label itself as author feedback? There could be another problem. Either way, this is definitely too aggressive, and the label shouldn't have been changed in this case.

**Comment by barryhughes** [comment]
In case useful, a further example of what I think may essentially be the same problem can be [seen here](https://github.com/woocommerce/woocommerce/issues/31459#issuecomment-1072883048) (I removed `needs: triage feedback` and applied `needs: author feedback`, which was swiftly reversed by the action).

<img width="861" alt="author-feedback-triage" src="https://user-images.githubusercontent.com/3594411/159096944-5351e5e7-8eb2-4a05-a9c8-919b33880bc3.png">

**Comment by rrennick** [comment]
I'm closing this pending it occurring again. I haven't seen this happen on issues in the last year where the two labels were changed at the same time. If it recurs we can re-open the issue.
