### ISSUE TITLE
PHP 8 Fatal error: Uncaught TypeError: method_exists() in class-wc-install.php:642

### ISSUE THREAD

**Issue by dartrax** [woothemes/woocommerce#32028]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Still present in WC 6.3.1

PHP 8 changed the way method_exists() behaves as it now throws a fatal error on passing the first parameter with anything other than string or object. 
This can happen when one of the filters applied to `woocommerce_get_settings_pages` adds an item that is not inherited of `WC_Settings_Page` to the settings array [here](https://github.com/woocommerce/woocommerce/blob/2c1885f69a7ed66fd56ef8cf028b9184939664a2/plugins/woocommerce/includes/admin/class-wc-admin-settings.php#L62) for any reason.

And this already happened:
- reported by another user at the Woocommerce Community forum [here](https://wordpress.org/support/topic/critical-error-after-upgrading-to-woocomerce-v6-x-class-wc-install-php/)
- I also run into this issue, it occured every 10 minutes when I'm in the admin interface
- reported (without solution due to inactivity) in #30991 ([Line 621](https://github.com/woocommerce/woocommerce/blob/d9620e89de7d473ac2f8962091dbe6d4990d76cf/includes/class-wc-install.php#L621) in WC5.8 is Line 642 in WC6.2.1 is Line 648 in WC6.3.1)

Encouraged by [wc-admin#7758](https://github.com/woocommerce/woocommerce-admin/issues/7758), which got solved by adding a safety check, I decided to report here because I think that there should be a safety check in this case, too. 

### Expected behavior

Ignore and do not throw a fatal error. To do so, implement a safety check like in [wc-admin#7758](https://github.com/woocommerce/woocommerce-admin/issues/7758).

Replace this:
https://github.com/woocommerce/woocommerce/blob/2c1885f69a7ed66fd56ef8cf028b9184939664a2/plugins/woocommerce/includes/class-wc-install.php#L643

with this:
` if ( ! is_a( $section, 'WC_Settings_Page' ) || ! method_exists( $section, 'get_settings' ) ) { `

### Actual behavior

```
2022-02-23T19:09:44+00:00 CRITICAL Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php:642
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php(642): method_exists()
#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php(316): WC_Install::create_options()
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php(199): WC_Install::install()
#3 /var/www/html/wp-includes/class-wp-hook.php(307): WC_Install::check_version()
#4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /var/www/html/wp-settings.php(587): do_action()
#7 /var/www/html/wp-config.php(83): require_once('...')
#8 /var/www/html/wp-load.php(50): require_once('...')
#9 /var/www/html/wp-admin/admin.php(34): require_once('...')
#10 /var/www/html/wp-admin/index.php(10): require_once('...')
#11 {main}
  thrown en /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php en la línea 642
```

### Steps to reproduce

Apply a filter to `woocommerce_get_settings_pages` that adds an item that is not inherited of `WC_Settings_Page` to the settings array.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://schlauhaus.biz
Site address (URL): https://schlauhaus.biz
WC Version: 6.2.1
REST API Version: ✔ 6.2.1
WC Blocks Version: ✔ 6.7.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: 5.9.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.16
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
...

### Post Type Counts ###

...

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Videopack (formerly Video Embed & Thumbnail Generator): von Kyle Gilman – 4.7.4
Variation Images Gallery for WooCommerce: von RadiusTheme – 2.2.1.6
Save and Share Cart for WooCommerce: von Ankit Gade – 1.0.8
Woocommerce Cross Sell Products Display: von Logicfire – 2.0.1
Germanized für WooCommerce: von vendidero – 3.8.4
WooCommerce Mindestbestellwert: von dartrax – 1.0
WooCommerce Product Dependencies: von SomewhereWarm – 1.2.7
WooCommerce: von Automattic – 6.2.1

### Inactive Plugins (6) ###

...

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #12 - /
Warenkorb: #79 - /cart/
Kasse: #78 - /checkout/
Mein Konto: #77 - /my-account/
Allgemeine Geschäftsbedingungen: #17 - /agb/

### Theme ###

...

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome_schlauhaus/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
/var/www/vhosts/schlauhaus.biz/httpdocs/wp_pub/wp-content/plugins/woo-product-variation-gallery/templates/product-images.php
/var/www/vhosts/schlauhaus.biz/httpdocs/wp_pub/wp-content/plugins/woo-product-variation-gallery/templates/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome_schlauhaus/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php

### Action Scheduler ###

Abgeschlossen: 256
Oldest: 2022-02-02 01:49:02 +0100
Newest: 2022-03-04 15:49:02 +0100

Ausstehend: 1
Oldest: 2022-03-05 07:19:02 +0100
Newest: 2022-03-05 07:19:02 +0100

### Status report information ###

Generated at: 2022-03-04 23:30:16 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hi @dartrax,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.
