### ISSUE TITLE
API documentation incorrect with regard to data type

### ISSUE THREAD

**Issue by johnknoop** [woothemes/woocommerce#32037]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The API documentation states that the `rate_id` property of `order.tax_lines` is a string, but in reality it's a number. I've checked with two different Woo stores and both return numbers:

![image](https://user-images.githubusercontent.com/3394270/157069762-e00179ad-5833-44d2-a22d-0316911035a3.png)

### Expected behavior

The API documentation should state that `rate_id` property of `order.tax_lines` is a number.

### Actual behavior

It says that it's a string.

### Steps to reproduce

Just fetch some orders from the v3 API of a Woo store.

### WordPress Environment

I only have API access to these stores so I can't access this information, but I don't think it should matter.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hi @johnknoop,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Both REST API v2 and v3 needs to update the `orders.tax_lines.rate_id` type to `integer`.

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.
