### ISSUE TITLE
Deprecation notices after upgrading WooCommerce Blocks to 7.2.0

### ISSUE THREAD

**Issue by rafaelzaleski** [woothemes/woocommerce#32077]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading WooCommerce Blocks to version 7.2.0, Woo Core is generating deprecation notices for code in `WC_Subscriptions_Extend_Store_Endpoint::init()`.

### Expected behavior

No deprecation notices are expected.

### Actual behavior

`Deprecated: Automattic\WooCommerce\Blocks\StoreApi\SchemaController is deprecated since version 7.2.0! Use Automattic\WooCommerce\StoreApi\SchemaController instead. in /var/www/html/wp-includes/functions.php on line 5316 Call Stack: 0.0031 411056 1. {main}() /var/www/html/wp-admin/index.php:0 0.0031 412304 2. require_once('/var/www/html/wp-admin/admin.php') /var/www/html/wp-admin/index.php:10 0.0032 412944 3. require_once('/var/www/html/wp-load.php') /var/www/html/wp-admin/admin.php:34 0.0033 413608 4. require_once('/var/www/html/wp-config.php') /var/www/html/wp-load.php:50 0.0040 420456 5. require_once('/var/www/html/wp-settings.php') /var/www/html/wp-config.php:256 0.9983 4996568 6. do_action() /var/www/html/wp-settings.php:450 0.9983 4996944 7. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:474 0.9983 4996944 8. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:331 1.1410 6229880 9. Automattic\WooCommerce\Blocks\Package::init() /var/www/html/wp-includes/class-wp-hook.php:307 1.1411 6229880 10. Automattic\WooCommerce\Blocks\Registry\Container->get() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Package.php:42 1.1411 6229880 11. Automattic\WooCommerce\Blocks\Registry\SharedType->get() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/Container.php:96 1.1411 6229880 12. Automattic\WooCommerce\Blocks\Registry\SharedType->resolve_value() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/SharedType.php:28 1.1411 6229880 13. Automattic\WooCommerce\Blocks\Package::Automattic\WooCommerce\Blocks\{closure:/var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Package.php:120-124}() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/AbstractDependencyType.php:42 1.1414 6231008 14. Automattic\WooCommerce\Blocks\Domain\Bootstrap->__construct() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Package.php:122 1.1500 6368568 15. do_action() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Domain/Bootstrap.php:63 1.1500 6368944 16. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:474 1.1500 6368944 17. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:331 1.1519 6376088 18. WC_Subscriptions_Extend_Store_Endpoint::init() /var/www/html/wp-includes/class-wp-hook.php:307 1.1519 6376088 19. Automattic\WooCommerce\Blocks\Registry\Container->get() /var/www/html/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-extend-store-endpoint.php:47 1.1519 6376088 20. Automattic\WooCommerce\Blocks\Registry\SharedType->get() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/Container.php:96 1.1519 6376088 21. Automattic\WooCommerce\Blocks\Registry\SharedType->resolve_value() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/SharedType.php:28 1.1519 6376088 22. Automattic\WooCommerce\Blocks\Domain\Bootstrap->Automattic\WooCommerce\Blocks\Domain\{closure:/var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Domain/Bootstrap.php:280-283}() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/AbstractDependencyType.php:42 1.1519 6376088 23. _deprecated_function() /var/www/html/wp-content/plugins/woo-gutenberg-products-block/src/Domain/Bootstrap.php:281 1.1521 6376408 24. trigger_error() /var/www/html/wp-includes/functions.php:5316`

### Steps to reproduce

- Update WooCommerce Blocks to version 7.2.0
- Enable WP_DEBUG_LOG on wp-config.php.

### WordPress Environment ###

WordPress address (URL): http://localhost:8090
Site address (URL): http://localhost:8090
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 7.2.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rafaelzaleski** [comment]
I'm closing this because it was another plugin causing the issue.

**Comment by rjchow** [comment]
@rafaelzaleski It seems to go away when I disable wcpay plugin, but if we [release Woocommerce 6.4](https://developer.woocommerce.com/2022/03/15/woocommerce-blocks-7-2-0-release-notes/) and include the changes for Woocommerce Blocks 7.2.0 it will affect many users who have wcpay enabled.

wcpay seems aware of the issue: https://github.com/Automattic/woocommerce-payments/issues/4004

**Comment by jonathansadowski** [comment]
Thanks for the report. I'm going to close this, as WooCommerce Blocks 7.2.1 has been releases, which should address this problem.

If you still experience this issue, please open a [new issue in the repository for Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new/choose), as those issues are tracked separately there.
