### ISSUE TITLE
Can you create a generic password for all users in woocommerce?

### ISSUE THREAD

**Issue by jhonatan11530** [woothemes/woocommerce#32084]
### Describe the solution you'd like

you can modify the woocommerce source code to generate a generic password for all users example password: 123
What security problems would I have when trying to make this change?

### Describe alternatives you've considered

put a generic password instead of a random one when creating an account

**Comment by roykho** [comment]
Thanks for the suggestion @jhonatan11530,

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look.

In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while. We'll keep an eye on the popularity of this request.
