### ISSUE TITLE
Woocommerce report wrong calculation when using multi currency

### ISSUE THREAD

**Issue by kelderkolddk** [woothemes/woocommerce#32080]
Hi I use Currency switcher:

Currency Switcher for WooCommerce.
Version 2.15.0 | Af [WP Wham](https://wpwham.com/) 

And when using that my reports do not show the right numbers, only sales in DKK (my local currency) is being showed.
All sales in Euro dont show up.

**Comment by roykho** [comment]
Hi @kelderkolddk,

Unfortunately this is not something we can help you with. I would suggest you reach out to the author of that plugin you're using for assistance.
