### ISSUE TITLE
[Enhancement]: "Set up payments" option available until two payment gateways are active

### ISSUE THREAD

**Issue by Konamiman** [woothemes/woocommerce#32126]
@csmcneill commented on [Wed Mar 16 2022](https://github.com/woocommerce/woocommerce/issues/32088)

### Describe the solution you'd like

When [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) is active on a site, the "Set up payments" option on the `Get ready to start selling` checklist should be checked off.

### Describe alternatives you've considered

1. Changing the verbiage so that, if one payment gateway is currently active, it says "Set up additional payment options" (or something similar.
2. Reducing it so that _any_ single payment gateway checks this item off on the list.

### Additional context

The "Set up payments" option on the `Get ready to start selling` checklist will continue to show until at least two payment gateways are active on a site, even if [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) is active:

<img width="899" alt="Markup 2022-03-16 at 15 49 25" src="https://user-images.githubusercontent.com/82999806/158688527-87197eee-dbfd-4539-a14e-bce953727698.png">

This creates some confusion about whether or not payments are set up.

Affected tickets: 

- 4828705-zen
- 4825826-zen

---

@woocommercebot commented on [Thu Mar 17 2022](https://github.com/woocommerce/woocommerce/issues/32088#issuecomment-1071287299)

Hi @csmcneill,

  Thank you for opening the issue! It requires further feedback from the WooCommerce Core team.

  We are adding the `needs developer feedback` label to this issue so that the Core team could take a look.

  Please note it may take a few days for them to get to this issue. Thank you for your patience.

---

@Konamiman commented on [Fri Mar 18 2022](https://github.com/woocommerce/woocommerce/issues/32088#issuecomment-1072541230)

Issue moved to [woocommerce/woocommerce-admin woocommerce/woocommerce#32127](woocommerce/woocommerce#32127) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mattsherman** [comment]
@pmcpinto Do you agree with this proposed enhancement?

**Comment by pmcpinto** [comment]
Yes, I think it makes sense to check off the Payments task when WCPayments is active. 
In WC 6.4 we'll make some changes to start showing the "Setup additional payment providers" task in "Things to do next" when the user completes the WCPayments setup. More info about this change [here](https://github.com/woocommerce/woocommerce-admin/issues/8315).

**Comment by WillBrubaker** [comment]
36062300-HC experiences this as well

**Comment by chihsuan** [comment]
I'm going to close this. The `Set up payments` task is now hidden when WooPayments is active and we show `Set up additional payment options` task in `Things to do next` section.
