### ISSUE TITLE
Minor UI issues with tasks experiment 1

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#32128]
### Describe the bug
A couple minor UI issues with the tasks experiment layout. 

1. Kebab menu doesn't have the normal spacing, compared to others on the page (should have greater spacing on the top and right margins).
2. Some of the images for various task headers obstruct the text when in the two-column layout on the Homescreen.

### To Reproduce

1. Checkout latest main
3. Enable `tasklist-setup-experiment-1` feature flag
4. Go to home when the task list is not complete
5. Enable two-column layout

### Screenshots
![image](https://user-images.githubusercontent.com/444632/158834919-6fd2e0ae-2a3f-4496-bddf-7660d939cac5.png)

**Comment by mattsherman** [comment]
These are issues from woocommerce/woocommerce-admin#8457.

**Comment by joshuatf** [comment]
@joelclimbsthings I wasn't able to see the ellipsis menu in the above screenshot.  Has that been resolved or is there a specific config needed to show?

It looks like it might be part of the `ProgressHeader` but I don't see it in the above screenshot.

**Comment by joelclimbsthings** [comment]
Hey @joshuatf , sorry for the delay on this. Looks like the ellipsis was already resolved by the addition of the progress header. ✅
