### ISSUE TITLE
Include JP connection package

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32135]
**Description:** we've received a suggestion to include the JP connection package, in order to streamline the setup flow of some extensions that rely on a wp.com connection. More info here: wp.me/p7bje6-3UY-p2

We should evaluate if introducing the package can really remove friction from the setup flow.

**Comment by adrianduffell** [comment]
Just blocking this until the designs are finished for this flow. p7bje6-3UY-p2#comment-7020

**Comment by becdetat** [comment]
@pmcpinto I'm treating this as blocked and won't include it in the scope for C23 at the moment, it looks like we need some design exploration and you're questioning whether it should actually be done or not in the issue description

**Comment by chihsuan** [comment]
Closing this. We've added JP connect package in https://github.com/woocommerce/woocommerce/pull/38674.
