### ISSUE TITLE
PHP Warning when adding a Digital product from template

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#32137]
### Describe the bug

The following PHP warning is visible when adding a `Digital product` from a template.

```
exif_read_data(album-1.jpg): Incorrect APP1 Exif Identifier Code
 Type: PHP Warning Line: 829
 File: /wp-admin/includes/image.php
```

### To Reproduce

1. Go to the `Home` screen
2. Press `Add my products`
3. And then press `Start with a template`
4. Select `Digital product`
5. The PHP warning below will be visible
 ```
exif_read_data(album-1.jpg): Incorrect APP1 Exif Identifier Code
 Type: PHP Warning Line: 829
 File: /wp-admin/includes/image.php
```

### Screenshots

![screenshot-misty-caribou jurassic ninja-2022 03 08-18_15_00](https://user-images.githubusercontent.com/1314156/157326483-57ed583b-0034-4e90-9ed5-811552709004.png)

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/32137?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @octaedro
