### ISSUE TITLE
Payment settings - UI changes to the recommended payment options section

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32130]
**Description:** we want to introduce some tweaks to this section of the payment settings screen, in order to reduce cognitive load and increase the visibility of WCPay.

**Acceptance criteria:**
- [ ] If the store is located in a country where WCPayments is eligible, hide the **Recommended Ways to Get Paid** panel and only show the "other payment methods" CTA at the bottom of the table.

![WooCommerce › Settings › Payments › Payment Gateway Table.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/acf44927-0432-49f4-9103-e77d254800a0)

### Recommended Ways to Get Paid Panel

![image](https://user-images.githubusercontent.com/9312929/160794957-c17960ed-4744-404d-9076-cfb2088e3c11.png)

☝️ Hide this when the store is located in a country where WCPayments is eligible.

**Event tracking:**
I think we already have all the tracking in place, but let me know if I'm missing something.

**Comment by adrianduffell** [comment]
<del>I've split the A/B test into its own issue https://github.com/woocommerce/woocommerce/issues/32414</del>

Edit: this comment was intended for another issue.
