### ISSUE TITLE
Update all `@wordpress/*` and react-related dependencies

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32139]
We've updated all packages with **minor/patch** version changes (https://github.com/woocommerce/woocommerce-admin/issues/8344). 

Next, we should focus on dependencies that need to be updated with **major version** changes. It would require updating the code for any breaking changes and adding some tests if needed. Since there are many outdated dependencies. This task is aim to update all `@wordpress/*` and react-related dependencies. We have other issues to update the others.

```
┌───────────────────────────────────────────────────────┬─────────┬────────────┐
│ Package                                               │ Current │ Latest     │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ @wordpress/a11y                                       │ 2.15.3  │ 3.3.1      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ @wordpress/base-styles                                │ 3.6.0   │ 4.1.1      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ @wordpress/hooks                                      │ 2.12.3  │ 3.3.1      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ @wordpress/icons                                      │ 6.3.0   │ 7.0.1      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ history                                               │ 4.10.1  │ 5.3.0      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ react-dates                                           │ 17.2.0  │ 21.8.0     │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ react-router-dom                                      │ 5.3.0   │ 6.2.2      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ @types/history (dev)                                  │ 4.7.11  │ 5.0.0      │
├───────────────────────────────────────────────────────┼─────────┼────────────┤
│ memoize-one                                           │ 5.2.1   │ 6.0.0      │
```

Related
- https://github.com/woocommerce/woocommerce-admin/issues/8425
- https://github.com/woocommerce/woocommerce-admin/issues/8326

**Comment by adrianduffell** [comment]
Here's the breaking changes noted in these packages’ changelogs.

## @wordpress/a11y

* Drop support for Internet Explorer 11
* Increase the minimum Node.js version to v12

https://github.com/WordPress/gutenberg/blob/50b5bfa7de660d41a3b0e0693bf3fc9fc56836d8/packages/a11y/CHANGELOG.md

## @wordpress/base-styles   

* Remove the background-colors, foreground-colors, and gradient-colors mixins.
https://github.com/WordPress/gutenberg/blob/50b5bfa7de660d41a3b0e0693bf3fc9fc56836d8/packages/base-styles/CHANGELOG.md

## @wordpress/hooks 

* Drop support for Internet Explorer 11
* Increase the minimum Node.js version to v12

https://github.com/WordPress/gutenberg/blob/50b5bfa7de660d41a3b0e0693bf3fc9fc56836d8/packages/hooks/CHANGELOG.md

## @wordpress/icons

* Changed dragHandle footprint from 18x18 to 24x24 to match other icons. 
* Removed icons that were added by mistake: alignJustifyAlt, cogAlt, sparkles, trashFilled. 

https://github.com/WordPress/gutenberg/blob/50b5bfa7de660d41a3b0e0693bf3fc9fc56836d8/packages/icons/CHANGELOG.md

## history

* Removed support for browsers that do not support the HTML5 history API (no pushState)
* Removed relative pathname support in hash history and memory history
* Removed getUserConfirmation, keyLength, and hashType APIs

https://github.com/remix-run/history/releases/tag/v5.0.0

## react-dates 

* Remove propTypes in production
* Call onDatesChange before onFocusChange in the DRP
* Omit tabindex prop from calendar navigation buttons when custom buttons are supplied
* Update react-with-styles and other deps

https://github.com/react-dates/react-dates/blob/master/CHANGELOG.md

## react-router-dom

* Various breaking changes.

https://reactrouter.com/docs/en/v6/upgrading/v5

## @types/history

* This package is deprecated.

> history provides its own type definitions, so you don't need @types/history installed!

https://www.npmjs.com/package/@types/history

## memoize-one

* This release is a major, but there are no behaviour or API changes. The major is to reflect that some of the TypeScript types have been tightened which might cause some peoples TypeScript builds to break.

https://github.com/alexreardon/memoize-one/releases

**Comment by adrianduffell** [comment]
I'm going to make this an epic and split it into multiple tasks.

**Comment by adrianduffell** [comment]
I've split this out into the following issues:

https://github.com/woocommerce/woocommerce/issues/32884
https://github.com/woocommerce/woocommerce/issues/32881
https://github.com/woocommerce/woocommerce/issues/32882
https://github.com/woocommerce/woocommerce/issues/32883
https://github.com/woocommerce/woocommerce/issues/32884

Rather than managing an epic, we can just handle the new issues directly and I'll close this issue out.
