### ISSUE TITLE
Payments task: UI changes to the additional payment gateways section

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32131]
**Description:** we want to introduce some tweaks to the additional payment gateways section, in order to reduce cognitive load and increase the visibility of WCPay.

![Payments _ WooCommerce Payments.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/b4b02bf4-bc45-4037-b594-097f8c5d75ff)

**Acceptance criteria:**
- [x] Split the section into two sections: "Choose a payment provider" [online payments] and "Offline payment methods" [offline payments]
- [x] Change the CTA copy to "Get started"
- [x] Update the payment's icon
- [x] Add a "See more" option at the bottom of the online payments section with a link to https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/online-payments/

If the store is located in a country where WCPayments is eligible but it's not installed
- [x] Hide the online and offline payment sections under an "Other payment methods" toggle
- [x] Remove the online payment header section

![Frame 2048.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/b86f88ce-94ba-4d10-b8cf-5b4313f7ea5a)

**Event tracking:**
We already have most of the tracking in place. We should only add new event Tracking to the following actions:
- Show/Hide the "Other payment methods" section
- Click on the "See more" option

Ilyas' edit:

I've moved the conditional hiding of "See more" and additional gateway acceptance criteria to a more relevant issue, https://github.com/woocommerce/woocommerce/issues/32132

**Comment by ilyasfoo** [comment]
Hi @pmcpinto, to confirm the details on new tracks:

- Show/Hide the "Other payment methods" section
Name: `wcadmin_tasklist_payment_show_toggle`
Props:
   - `show: 0` if toggle to hide, otherwise `show: 1`
   - `payment_method_count`: Number of gateways shown

- Click on the "See more" option
Name:  `wcadmin_tasklist_see_more`

**Comment by ilyasfoo** [comment]
>Update the payment's icon

Hi @jarekmorawski @verofasulo, it seems some payment icons aren't provided in the figma e428PXC0QyEwYqtX48lLq0-fi. I can't figure out where else to obtain them, so I'll need help from you 🙏 

Namely: 
- Mercado Pago
- PayU
- Razorpay
- Payfast
- Paystack
- Afterpay
- Mollie

It'll be great if we can get them in either svg/png, thanks!

**Comment by rogermattic** [comment]
Hey @ilyasfoo !
Just heads up – I'll supply the icons, just need to check which ones I already have and which ones need making :)

**Comment by ilyasfoo** [comment]
Great, thanks @rogermattic!

As an aside, is it also possible for you to help design a generic image for a placeholder in case of a failed load? Currently, this is what a user will see:

![image](https://user-images.githubusercontent.com/3747241/161191963-33a516d5-08dc-46f1-ab60-9e336466fe9f.png)

**Comment by pmcpinto** [comment]
@ilyasfoo thanks for the suggestions. Here's my feedback:

> Click on the "See more" option
> Name: wcadmin_tasklist_see_more
We should include payment to make it clear that the event is only about this task: wcadmin_tasklist_payment_see_more

> Show/Hide the "Other payment methods" section
> Name: wcadmin_tasklist_payment_show_toggle

The name looks good to me.

> payment_method_count: Number of gateways shown

Same

> show: 0 if toggle to hide, otherwise show: 1

Maybe this one is a bit confusing. I'd change it to:

`toggle`: `show` (when the user clicks to show the options) | `hide` (when the user clicks to hide the options)

Let me know what you think

**Comment by ilyasfoo** [comment]
@pmcpinto Sounds good, thanks!

**Comment by ilyasfoo** [comment]
@pmcpinto I have a few more clarifications to make:

1. I have moved "Enabled payment gateways" to below "Other payment gateways" since otherwise, it may disrupt the new flow when WCPay is available. I assume this is ok.
2. The new WCPay UI no longer uses the values from remote payment suggestion JSON since:
    - The elements in this section aren't standard anymore - i.e: There's the three-icon card below it, privacy policy link, and t&c link.
    - Changing the remote gateway suggestion to match the new design may disrupt other places where the values are used, thus breaking their UI.
3. `tasklist_payment_learn_more` track will no longer be recorded since the link component for that track is removed

Here's a screenshot of the WIP, let me know if anything is amiss (other payment icons are not ready yet):

![image](https://user-images.githubusercontent.com/3747241/161987372-b884e718-17b7-4658-8627-f44bcd04666b.png)

**Comment by pmcpinto** [comment]
Hey @ilyasfoo here's my feedback:

> I have moved "Enabled payment gateways" to below "Other payment gateways" since otherwise, it may disrupt the new flow when WCPay is available. I assume this is ok.

That's ok. Just one detail: the offline payments methods section should also be included within the "Other payment methods". In your screenshot, this section is placed below the "Enabled payment gateways".

> The new WCPay UI no longer uses the values from remote payment suggestion JSON since

I think I forgot to mention this: the goal is to keep the existing WCPay UI because the Payments team still needs to test the new UI in the WCPayments welcome screen. @rogermattic @LevinMedia let me know if you're ok with this. As Ilyas mentioned, changing the UI in the payments task has other ramifications.  It would be better to validate the impact of the new UI first before applying the changes to this task.

**Comment by ilyasfoo** [comment]
Thanks for the feedback, @pmcpinto!

>That's ok. Just one detail: the offline payments methods section should also be included within the "Other payment methods". In your screenshot, this section is placed below the "Enabled payment gateways".

Alright, I'll move the offline section to above "Enabled payment gateways" section.

> I think I forgot to mention this: the goal is to keep the existing WCPay UI because the Payments team still needs to test the new UI in the WCPayments welcome screen. 

Ah, bummer. I should've asked why it wasn't on the AC list, my bad. I'll revert this part if we confirm it's not ready yet. I think I can keep the work done somewhere and I'll be able to help the WCPay team if they want it.
