### ISSUE TITLE
Payments promo in the task and settings: update logic

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32132]
**Description:** we want to change the logic behind the promo of payments solutions in the payments task and setting. Logic [here](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-gateway-suggestions.php#L20-L339). The goal is to have 3 categories, and the existing logic is already practically aligned with the first 2 categories. It probably needs some refinements: Display for Preferred Payment Provider Placement, Display for other (non-WCPay) Payment Provider placements, Display for other (non-WCPay) Payment Provider placements, Display as Additional Payment Option

**Acceptance criteria:** 

- [ ] Update the logic on how we display payments options in the payments task and settings to follow the logic outlined in the spreadsheet shared in this comment: paJDYF-3oZ-p2#comment-10304

If a user has selected and set up either WCPay or a solution provided by “other payment providers” 
- [x] Only display in the online payment section the solutions included in the "Display as Additional Payment Option" category.
- [x] Hide the "See more" option at the bottom of the online payments section

Ilyas' edit:

- As mentioned, the first two categories are aligned with the current WooCommerce. What's left to be done for these is to check for consistency with the spreadsheet shared.
- I've moved the last 2 ACs from the other issue https://github.com/woocommerce/woocommerce/issues/32131

**Comment by ilyasfoo** [comment]
Adding in details from our discussion for posterity:

- As mentioned, the first two categories are aligned with the current WooCommerce. What's left to be done for these is to check for consistency with the spreadsheet shared.
- For the third category, we'd need to replace the places where the second category would be when either first or second category payment provider is installed. This is because they're a "supplemental" provider instead of a "competitor" provider.

**Comment by ilyasfoo** [comment]
Hi @pmcpinto, it seems there are some discrepancies with the spreadsheet. For example, Stripe is currently visible for countries `'MY', 'SI', 'PR'` but they aren't listed in the spreadsheet. What should we do for these cases?

**Comment by ilyasfoo** [comment]
@pmcpinto Another discrepancy with Paypal's current rule [not showing for `IN`](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-gateway-suggestions.php#L158-L162) but is an additional gateway in spreadsheet.

**Comment by ilyasfoo** [comment]
For posterity: Another discrepancy with Paypal's current rule  shows for every country except for `IN` but is an additional gateway in spreadsheet

**Comment by pmcpinto** [comment]
> Hi @pmcpinto, it seems there are some discrepancies with the spreadsheet. For example, Stripe is currently visible for countries 'MY', 'SI', 'PR' but they aren't listed in the spreadsheet. What should we do for these cases?

We should keep Stripe visible for the countries included in the current logic.

Here's the info regarding the new extensions that are included in the logic:

**Title:** Afterpay
**Description:** Afterpay allows customers to receive products immediately and pay for purchases over four installments, always interest-free.
Plugin download: https://wordpress.org/plugins/afterpay-gateway-for-woocommerce/
**Logo:** TBD

**Title:** Amazon Pay
**Description:** Enable a familiar, fast checkout for hundreds of millions of active Amazon customers globally.
Plugin download: https://wordpress.org/plugins/woocommerce-gateway-amazon-payments-advanced/
**Logo:** TBD

**Title:** Affirm
**Description:** Affirm’s tailored Buy Now Pay Later programs remove price as a barrier, turning browsers into buyers, increasing average order value, and expanding your customer base.
Plugin download: The plugin is not available in wp.org, so we need to redirect them to woocommerce.com: https://woocommerce.com/products/woocommerce-gateway-affirm
**Logo:** TBD

**Comment by ilyasfoo** [comment]
Thanks for clarifying, @pmcpinto!

> Plugin download: The plugin is not available in wp.org, so we need to redirect them to woocommerce.com: https://woocommerce.com/products/woocommerce-gateway-affirm

This is a new use case, we don't currently have a non-wporg plugin listed in there. Should the CTA be "Get Started" even though it would go to wccom?

**Comment by pmcpinto** [comment]
>  Should the CTA be "Get Started" even though it would go to wccom?

Yes. Thanks
