### ISSUE TITLE
Add Pinterest extension to onboarding wizard and marketing task

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32141]
**Description:** we plan to include the new Pinterest extension in the marketing task, starting in the WooCommerce 6.5 release (code freeze: April 14). More info here: paqDfi-3fd-p2

**OBW: Business features step:**
Location: Grow your store - below Google Listing and Ads
Copy: Inspire shoppers with [Pinterest for WooCommerce](https://woocommerce.com/products/pinterest-for-woocommerce/)

**Tasks: Marketing:**
Location: Grow your store - below Google Listing and Ads
Copy:
Pinterest for WooCommerce
Get your products in front of Pinterest users searching for ideas and things to buy. Get started with Pinterest and make your entire product catalog browsable.

**Logo:** https://brand.pinterest.com/brand-assets
**wp.org link:** https://wordpress.org/plugins/pinterest-for-woocommerce/

**Comment by octaedro** [comment]
Hi @jarekmorawski,

I'm working on this issue now and I would need an image (Pinterest logo) to show in the marketing task, like these:

![screenshot-localhost_10038-2022 04 07-11_55_38](https://user-images.githubusercontent.com/1314156/162229453-dfd6a88f-c7ed-423b-b3d8-ed25a5b2b5c4.png)

I don't have the right programs to edit images, could you give me a `.png` to use here or point me in the right direction to get one?

**Comment by octaedro** [comment]
Hey @pmcpinto,

I wanted to ask you if, in addition to the tasks described above, we should add a link to the [Pinterest setup documentation](https://woocommerce.com/products/pinterest-for-woocommerce/) in the help panel for marketing extensions.

![screenshot-localhost_10038-2022 04 07-14_38_23](https://user-images.githubusercontent.com/1314156/162264172-8cb2b494-dd8e-4dc1-867b-758e2846b68a.png)

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm pinging you again just in case you didn't see [the question I asked above](https://github.com/woocommerce/woocommerce/issues/32141#issuecomment-1092025295).

**Comment by pmcpinto** [comment]
@octaedro sorry for the late reply, I was afk on Friday.

> I wanted to ask you if, in addition to the tasks described above, we should add a link to the [Pinterest setup documentation](https://woocommerce.com/products/pinterest-for-woocommerce/) in the help panel for marketing extensions.

I think that makes total sense. Feel free to move forward with the suggestion. Thanks!

**Comment by jarekmorawski** [comment]
Hi! 👋 I agree with what Pedro said, it'll be nice to keep the documentation tab up to date. As for the Pinterest logo, I've attached it below. It's the same one that we use in the official plugin.

![pinterest_logo](https://user-images.githubusercontent.com/79307566/162917574-49eec00b-cda3-4d5a-ab55-ac88ba41832b.svg)

**Comment by pmcpinto** [comment]
Hi @octaedro I was reviewing this flow with the BizDev team and we came to the conclusion that it is best to start by just including the extension in the Marketing task. Can we revert the inclusion in the business features step between the 6.5 beta and RC?

**Comment by mattsherman** [comment]
@octaedro @pmcpinto What is the status of this PR? It looks like it can be closed?

**Comment by octaedro** [comment]
Hey @mattsherman,
Yes, you're right. I thought it was already closed.
I'm closing this issue now 🙂
