### ISSUE TITLE
Is not possible to mark the marketing task as complete in the setup tasklist

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#32149]
### Describe the bug

Is not possible to mark the marketing task as complete in the setup tasklist.

### To Reproduce

1. In a brand new store, go through the OBW, and in step 4 (Business Details), go to `Free features` and install the `MailPoet` extension.
2. Finish the OBW.
3. On the `Home` page, press `Set up marketing tools`.
4. The marketing task should be marked as complete but that is not happening and there is no way to do it without installing an extension in the task.

### Actual behavior:

Is not possible to mark the marketing task as complete in the setup tasklist. To accomplish that it's necessary [to install an extension in the step](https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/fills/Marketing/index.tsx#L153).

### Screenshots

![screenshot-confused-fly jurassic ninja-2022 02 25-18_45_23](https://user-images.githubusercontent.com/1314156/155807460-b1c65cba-85d3-46a3-a803-93af478011b1.png)

### Expected behavior

If the user has one of the marketing extensions installed, we should action the task after pressing `Set up marketing tools` (p1645789832142759/1645544417.244379-slack-C01CMSA1VHS).

**Comment by senff** [comment]
Additional information: if the store owner does not want any of these marketing tools to begin with, there should be a "Skip this step" on the page at **http://YOURSITE.com/wp-admin/admin.php?page=wc-admin&task=marketing** ). 

![skip](https://user-images.githubusercontent.com/1710669/162787826-007ae78a-d641-4d53-b1a7-d61b9a1cfea9.png)

**Comment by senff** [comment]
Even more additional details: this step will only be marked as "Completed" if any of the 4 plugins is actually **installed** on the site (though it does not need to be **active**). If you delete them again (and so none of the 4 plugins is present on the site), Step 6 will revert back to "Uncompleted".

It should not be a requirement to have at least one of these 4 plugin installed, in order to mark the onboarding steps complete.

**Comment by octaedro** [comment]
Just to give @senff's [comment](https://github.com/woocommerce/woocommerce/issues/32149#issuecomment-1095279515) more visibility.
@pmcpinto and @jarekmorawski what do you think about adding a skip button to this step?

**Comment by jarekmorawski** [comment]
That's a great point. Thanks for bringing this to my attention. @verofasulo is currently working on changes to this screen. Whatever we do here, it'd be great to think about skipping in the context of all tasks. It's quite possible that for some merchants even shipping or taxes may be irrelevant. Ideally, people could skip all tasks in the same way.

**Comment by verofasulo** [comment]
Thank you for raising the point @senff and for tagging me @jarekmorawski 🙌 

I think it makes total sense and I'll explore it more while working on the designs.

**Comment by pmcpinto** [comment]
Hey @octaedro this will be fixed with #32630, right?

**Comment by octaedro** [comment]
Hi @pmcpinto,

> this will be fixed with #32630, right?

That's right. Thank you for the ping. I'm going to close this issue.
