### ISSUE TITLE
Task completion event not firing with WCPay task

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32140]
### Describe the bug
The `wcadmin_tasklist_task_completed` event is not working properly with the WooCommerce Payments task. It went from ~200/day to almost 0 after Dec 15 (WooCommerce 6.0, [WC Admin 2.9](https://github.com/woocommerce/woocommerce-admin/blob/release/2.9.4/changelog.txt))

### To Reproduce

1. Create a new store with US as a country
2. Install WCPay in the business features step
3. Visit the home screen and click on the WCPay task
4. Finish the WCPay KYC
5. Confirm that `wcadmin_tasklist_task_completed` `task_name`: `woocommerce-payments`

**Comment by pmcpinto** [comment]
@becdetat @mattsherman is it possible to check this during the current cycle? I'm not sure if this was caused by woocommerce/woocommerce-admin#7736

Thanks!

**Comment by becdetat** [comment]
@mattsherman it would be good to at least assess this in this cycle. It's also probably a good opportunity to add some tests around it (which obviously increases the time, so up to you if we can actually fix it in this cycle).

**Comment by pmcpinto** [comment]
Hey @mattsherman do you have news about this? Thanks

**Comment by mattsherman** [comment]
@pmcpinto Sorry about this... I missed these pings originally. I'll have the team look at this early next week and update you both.

**Comment by pmcpinto** [comment]
@mattsherman does the team have the bandwidth to take a look at this during the cycle?

**Comment by mattsherman** [comment]
@pmcpinto We will look at this in Cycle 23.

**Comment by louwie17** [comment]
@pmcpinto I had a look at the tracks again, and it appears this has been fixed during the WC 6.3 release our `3.2` release ( I am not a 100% sure which change exactly fixed it, but the daily average seems to be around ~200 again:
<img width="1515" alt="Screen Shot 2022-04-05 at 11 03 35 AM" src="https://user-images.githubusercontent.com/2240960/161772079-d07152bf-dbba-4301-b433-36761a223457.png">

Let me know if this is what is expected? If so, we can close this.

**Comment by louwie17** [comment]
I actually believe this PR fixed it - https://github.com/woocommerce/woocommerce-admin/pull/8321
As the task completion only gets triggered for viewable tasks and in the two column task list experiment we removed the WooCommerce Payments task after completion (not triggering the completion), I can fix this as part of this PR, although it won't be relevant with the new task list experiments.

**Comment by pmcpinto** [comment]
Thanks for spotting this. I didn't notice that it was fixed in the previous release. 

The WC-Payments counts are in line with what we're getting before the Tracks issue, so we can close this one.
