### ISSUE TITLE
Setup experiment: setup complete card in the Home screen

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32158]
**Description:**
When merchants complete store setup, we replace the task list with a congratulatory card and use this opportunity to collect feedback.

Feedback will only be requested if the user has enabled tracking. 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/79307566/155333389-73994b9e-f4ce-4b30-ad20-36b273e8c4b6.png">

**Design overview:**
* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-36%3A92987

**Acceptance Criteria:**

- [ ] Works and looks the same for both task list layout experiments (woocommerce/woocommerce#32165, woocommerce/woocommerce#32164)
- [ ] Clicking the ellipsis icon brings up a menu where merchants can dismiss the card entirely or bring back the task list
- [ ] The feedback emojis will only be shown if the user has enabled tracking
- [ ] Hovering over an emoji shows a tooltip with the sentiment and clicking saves feedback (neutral, good, very good) or opens up the CES modal (very difficult, difficult)
- [ ] The feedback is collected in the same DB as the rest of our CES responses and marked as `Store setup`
- [ ] After sending feedback, we show a thank you message, then hide that section in the card (after 1200ms delay)

**Event tracking:** to be assessed by the team

**Comment by louwie17** [comment]
@jarekmorawski / @pmcpinto what if the user click's cancel after the feedback Modal opens (when the user clicked difficult or very difficult). Will we then still submit the score data and show the `We appreciate your feedback!`? or show neither and make the bar dissapear?

**Comment by pmcpinto** [comment]
> what if the user click's cancel after the feedback Modal opens

@louwie17 Just to clarify, are you talking about clicking on the "hide this" option?

**Comment by louwie17** [comment]
> @louwie17 Just to clarify, are you talking about clicking on the "hide this" option?

No, I mean when the user clicks on the Very difficult, or difficult option and then the CES Modal shows up. The user has the ability to click cancel instead of `Send`. What should we be doing in that case? (still submit the original score without comments? and show the 'Thank you for your feedback' - maybe a bit confusing for the user, or not submit it, and make the feedback disappear).
<img width="718" alt="Screen Shot 2022-04-11 at 9 13 53 AM" src="https://user-images.githubusercontent.com/2240960/162737098-a688c369-301d-44af-9819-5e5eca8114fd.png">

**Comment by jarekmorawski** [comment]
Hi @louwie17! Thanks for raising this question, it's a really good one. I think it'd make sense to only submit the rating when someone clicks `Send`. If someone selects `Cancel`, they wouldn't submit the score. The comment is optional so they can send the rating in a just one click.

By the way, can we change the font case of the `Optional` part in the comment field's label to sentence? `Comments (Optional)` -> `Comments (optional)`.

**Comment by louwie17** [comment]
>  If someone selects Cancel, they wouldn't submit the score. The comment is optional so they can send the rating in a just one click.

Thanks, that makes sense, will we make the the `How was your experience` also disappear after they clicked cancel?

> By the way, can we change the font case of the Optional part in the comment field's label to sentence? Comments (Optional) -> Comments (optional).

To clarify, you mean just changing `Comments (Optional)` to `Comments (optional)`?

**Comment by jarekmorawski** [comment]
> Thanks, that makes sense, will we make the the How was your experience also disappear after they clicked cancel?

No. I was thinking it'd just close the modal, but not dismiss the card in the Home screen (people could do that manually if needed).

>To clarify, you mean just changing Comments (Optional) to Comments (optional)?

Yes, just the text. The `optional` part should be written in sentence case since it's part of the field's label.

**Comment by louwie17** [comment]
> No. I was thinking it'd just close the modal, but not dismiss the card in the Home screen (people could do that manually if needed).

@jarekmorawski not sure if we are exactly on the same page. When I am revering to making the `How was your experience` disappear, I only mean the bar the red arrow is pointing at here:

<img width="814" alt="155333389-73994b9e-f4ce-4b30-ad20-36b273e8c4b6" src="https://user-images.githubusercontent.com/2240960/163254498-e1339227-e8ed-479e-a279-bd2deb127140.png">

**Comment by jarekmorawski** [comment]
Yup. I think `Cancel` should only close the modal and not dismiss neither card or the `How was your experience` part. In other words, the only way to make it disappear is to either click the `Hide this` button in the dropdown or submit a rating.

**Comment by louwie17** [comment]
@jarekmorawski there doesn't seem to be any specific time mentioned for when to auto hide the `Thank you for your feedback`

**Comment by jarekmorawski** [comment]
Sorry about that. I just added the time to the issue description. ✅
