### ISSUE TITLE
Setup experiment: add Preview store button

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32156]
**User Story:**
As a new merchant
I want to see what my new store looks like
So I can start customizing it

<img width="717" alt="image" src="https://user-images.githubusercontent.com/79307566/155334635-61f5e507-6d9a-49c0-8caa-1ea6b3163e34.png">

**Description:**
To make it easy for merchants to see what their store looks like, we could add a `Preview store` button to the action bar in the Home screen.

**Acceptance Criteria:**

- [ ] The `Preview store` button is visible in the Home screen
- [ ] Button uses Gutenberg's external link icon
- [ ] Clicking it opens the store's URL in a new tab

**Event tracking:** to be assessed by the team

**Comment by pmcpinto** [comment]
Just to add a note that we already have a preview store button in the personalize store task: https://d.pr/i/BPQIcE

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/32156?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro @joshuatf
