### ISSUE TITLE
Cannot compare variations under Analytics Products

### ISSUE THREAD

**Issue by aheckler** [woothemes/woocommerce#32151]
### Is your feature request related to a problem? Please describe.

It's not possible to choose specific variations under Analytics > Products when using the Comparison view. This presents a problem for any merchant who wants to compare data while using variable products.

![Screenshot taken on 2022-02-24 at 13 35 34 UTC@2x](https://user-images.githubusercontent.com/5512652/155534303-58888ad5-acca-4234-a9a9-93b9c43e9825.png)

### Describe the solution you'd like

Ideally it would be possibly to compare variations like you can with the single product view:

<img width="1142" alt="Screenshot taken on 2022-02-24 at 13 37 04 UTC@2x" src="https://user-images.githubusercontent.com/5512652/155534442-df973f7d-6017-4ff1-a88a-6d00800fd320.png">

### Describe alternatives you've considered

None. Are there any?

### Should this be prioritized? Why?

That's up to y'all. Given that this is the first request we've seen for this, might not be High priority, but still... seems like it's incomplete as-is.

### Additional context

4803984-zen

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.

The users can leverage the Variations report as a workaround.
