### ISSUE TITLE
Setup experiment: experiments for task lists

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#32150]
**Description:**

We have two new task lists developed as part of woocommerce/woocommerce#32165 and woocommerce/woocommerce#32164. We want to run both of these task lists during the same experiment. 

Acceptance Criteria:

- [ ] Create an experiment P2 in a8cexperiments - pbxNRc-1n1-p2 or pbxNRc-ZP-p2 
- [ ] Create experiments in Abacus with some of the criteria below:
- [ ] One visible only to new stores in the US
- [ ] One visible only to new stores in Australia & Canada

**Event tracking**

Primary goal metric: Task list clicks: `wcadmin_tasklist_click` (metric - `wc_web_admin_tasklist_task_click` )
Other metrics: Task list completions: `wcadmin_tasklist_task_completed` ( metric -`wc_web_admin_tasklist_task_complete` )
~~Exposure event: Viewing the setup task list: wcadmin_tasklist_view~~ this was not used in the last experiment (see pbxNRc-WS-p2 )

Other metrics to consider are the `task_click` and `task_complete` events for each individual task ( store_details, products, payments, shipping, appearance, tax, wcpay ) see the below screenshot:

![Screen Shot 2022-02-24 at 2.14.47 PM.png](https://images.zenhubusercontent.com/5fa15baa8c308be7f0496579/7d7ac754-1dfe-4504-9ae7-6fde17151960)

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/8377?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro

**Comment by louwie17** [comment]
This Slack thread contains some extra context for managing experiments in specific countries more reliably - p1646150506687989-slack-C9K5T0XSP 
Ask Ghidorah for more help if you need it.

**Comment by mattsherman** [comment]
P2 post with ExPlat tips: pbIJXs-1k3-p2
