### ISSUE TITLE
WooCommerce ESLint plugin should be upgraded to work with ESLint >= 8.0.0

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#32153]
### Describe the bug
Consumers of `@woocommerce/eslint-plugin` using  ESLint 8 or greater will result in errors since `plugin:testing-library/recommended` has been removed.

To fix this we can:

* Bump `eslint` to 8.0.0 or greater
* Bump `eslint-plugin-testing-library` to 5.0.0 or greater
* Update `plugin:testing-library/recommended` to `plugin:testing-library/react` in `packages/eslint-plugin/configs/react-testing-library.js`

For anyone using `@woocommerce/eslint-plugin` in the meantime, you can downgrade to both `eslint@^7.32.0` and `eslint-plugin-testing-library^3.10.2` to keep this ruleset.

### To Reproduce

1. In a new repo, clone `@woocommerce/eslint-plugin`
2. Install eslint 8 or greater
3. Run eslint from the command line
4. Note the error

**Comment by adrianduffell** [comment]
@chihsuan can this now be closed by https://github.com/woocommerce/woocommerce-admin/pull/8475?

**Comment by chihsuan** [comment]
@adrianduffell Yes. 😄 thanks for the ping!
