### ISSUE TITLE
Setup experiment: disable welcome modals

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32157]
**User Story:**
As a new merchant
I want to explore my new store without interruptions
So I can start selling as quickly as possible

**Description:**
Most of the information currently displayed in the 3-step modal isn't relevant to merchants who're just starting out. With the changes we're trying out in this cycle, we can replace it with a personalized welcome experience in the Home screen.

**Acceptance Criteria:**

- [ ] Merchants no longer see the welcome modal when they enter the Home screen for the first time

**Comment by octaedro** [comment]
Hi @jarekmorawski,

Just to confirm, the idea is not to show the `Welcome modals` anymore even for Calypso users, correct?

**Comment by jarekmorawski** [comment]
Yes!

**Comment by mattsherman** [comment]
Reopening... it isn't Done... e2e testing are outstanding (#32505)
