### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: int - string

### ISSUE THREAD

**Issue by melek** [woothemes/woocommerce#32167]
### Describe the bug

This is similar to [https://github.com/woocommerce/woocommerce-admin/issues/7891](https://github.com/woocommerce/woocommerce-admin/issues/7891) which has been closed already.

Reported in 34069883-hc and followed up in 4757604-zen, where the user provided the System Status Report. This is a ***multisite***.

For more details, please refer to 4757604-zen

Originally filed by @jacoswan

**Comment by adrianduffell** [comment]
This should now be fixed by https://github.com/woocommerce/woocommerce-admin/pull/8100. Please re-open if it continues to be a problem.
