### ISSUE TITLE
Woocommerce analytics query filter is not working for a report export / download

### ISSUE THREAD

**Issue by appschris** [woothemes/woocommerce#32169]
### Describe the bug
To manipulate the WooCommerce analytics reports we use the `woocommerce_analytics_clauses_where` filter.
This works great for all statistics (revenue, orders, etc.). The direct download of an revenue export also works.
As soon as the export is created in a queue and sent by email (e.g. an export of revenue from the previous month), the `woocommerce_analytics_clauses_where` filter is no longer applied.

The filter loos like this
```
function woocommerce_analytics_query_filter( $clauses ) {
    $user = wp_get_current_user();
    $user_subcompany = get_user_meta( $user->ID, 'assigned_subcompany', true );

    if ( empty( $user_subcompany ) ) {
        return $clauses;
    }

    global $wpdb;
    array_push($clauses,"AND {$wpdb->prefix}wc_order_stats.order_id IN (SELECT post_id FROM $wpdb->postmeta WHERE meta_key = 'subcompany' AND meta_value = ".$user_subcompany.")");
    return $clauses;
}
add_filter( 'woocommerce_analytics_clauses_where', 'woocommerce_analytics_query_filter' );
```

Any ideas how to use the filter even if the report is created in the background queue?

**Comment by adrianduffell** [comment]
Hi @appschris,

Thanks for opening this issue. The filter should apply to reports created in the background queue as far as I'm aware.

To help us reproduce the issue, would you be able to provide a small example plugin that exhibits the problem? I'm curious if it might be a priority/timing issue with your `add_filter` call.
