### ISSUE TITLE
Setup experiment: setup reminder bar

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32161]
**User Story:**
As a new merchant
I want to know how to continue store setup
So I can do it quickly and easily

**Description:**
To create awareness about the task list and steps left in the store setup, we'd add a reminder bar to all non-onboarding screens in Woo.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/79307566/155330658-0ea43105-9bc7-46b7-97d3-d6dc42af768d.png">

**Design overview:**

* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-123%3A7773

**Acceptance Criteria:**

- [x] The bar is only shown if the task list is *not* hidden (so, even if tasks are not all complete, if the user has hidden the task list, we should *not* show the bar)
- [x] The bar is displayed persistently for 4 weeks from the date of creating a store
- [x] Reminder can be dismissed permanently by clicking the X button on the right hand side
- [x] Bar doesn't show up in the Home screen and any screen that belongs to the internal task flow (f.e. shipping)
- [x] The number of steps in the copy updates dynamically
- [x] Button links to the Home screen
- [x] Copy inside the reminder changes when there's 1 step left in setup (`🎉 ️Almost there. Only 1 step left get your store up and running. Finish setup`)

**Event tracking:** to be assessed by the team

**Comment by pmcpinto** [comment]
@joelclimbsthings @louwie17 I'm testing 6.5 Beta 1 and I've noticed that we don't have Tracks implemented in the progress bar. We should have at least 3 events: one for viewing the bar, another one for clicking "continue setup", and one for closing the bar. Let me know if it's possible to implement them in time to be included in the 6.5 RC. Thanks

**Comment by louwie17** [comment]
Thanks @pmcpinto, we will keep you updated if we get it in, in time.
I know they do plan to be a little more strict with cherry picking bugs for the release (see here: pdqwkG-aK-p2 ) so we will have to make a strong case for this one.
Otherwise we could also disable this feature and push it to the next release, but lets keep that as a last resort.

**Comment by jarekmorawski** [comment]
@louwie17, on that note, can we do anything to improve the loading speed of this bar? Currently, it takes about 1-2 seconds for the bar to appear, which makes the page jump a little. Ideally the bar would load along with other page elements.

**Comment by pmcpinto** [comment]
@louwie17 were the Tracks events and the loading speed mentioned by Jarek included in the 6.5 RC?

**Comment by louwie17** [comment]
> @louwie17 were the Tracks events and the loading speed mentioned by Jarek included in the 6.5 RC?

The track events should be added in the 6.5 RC, the loading speed hasn't. Should we create a separate issue for that? Or re-open this one?

**Comment by pmcpinto** [comment]
> The track events should be added in the 6.5 RC, the loading speed hasn't. 

Thanks!

> Should we create a separate issue for that? Or re-open this one?

Maybe it's better to open a follow-up issue about the loading speed. @jarekmorawski can you create one with the tweak you want to implement and cc Lourens?
