### ISSUE TITLE
Setup experiment: progressive header

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32163]
**User Story:**
As a new merchant
I want to see how much store setup is left
So I can plan out the next steps

**Description:**
For both task list layout experiments (#8350, woocommerce/woocommerce#32164), we'd used a shared header component that would give the Home screen more structure, provide encouragement and guidance to new merchants, and include a progress bar to visualize the number of completed setup steps.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/79307566/155326263-f3614dfb-e8cb-47dc-a364-c4e20097509e.png">

**Design overview:**
* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-839%3A103382

**Acceptance Criteria:**
- [ ] When merchant visits the Home screen for the first time, the heading says `Welcome to [store_name]`
- [ ] On a 2nd and any next visit the header will have copy that corresponds with the number of completed steps (pbIJXs-1ew-p2): `Let’s get you started` (1-3), `You are on the right track` (4-6), `You are almost there` (6-8)
- [ ] Header description includes the number of completed and total steps: `X out of Y complete`
- [ ] By clicking the `...` icon, merchants can display a menu and hide the setup list
- [ ] When the task list is hidden, we show a toast message with an `Undo` button, which brings it back
- [ ] When all tasks are complete, the progress bar and description are hidden and the title defaults to `Welcome to [store_name]` (G9vi4e286yjdzyIdg8hBb1-fi-847%3A118761)
- [ ] In 2-column layout, the new header replaces the existing one

**Event tracking:** to be assessed by the team

**Comment by octaedro** [comment]
Hi @jarekmorawski,

I have a couple of questions related to the point

> When merchant visits the Home screen for the first time, the heading says Welcome to [store_name]

Should the users see the `Welcome to <store_name>` when they skip the OBW? What should they see if they skip the OBW and then they start it again and finish it?

**Comment by jarekmorawski** [comment]
Hi @octaedro 👋 Yes, they should always see the welcome message. If in any case we don't know the store's name, we can say `Welcome to your store.`

> What should they see if they skip the OBW and then they start it again and finish it?

The same message. The goal isn't to just say hi to them when they first create the store, but also every time they visit the Home screen. It could be months or years after they create it. In the future we may explore more contextual messages, but that depends on the outcome of this experiment.

**Comment by octaedro** [comment]
Thank you @jarekmorawski for your answer.

Just to confirm, the `Welcome to <store_name>` title will be visible when the user doesn't have any completed tasks and also after completing all of them?

**Comment by jarekmorawski** [comment]
> when the user doesn't have any completed tasks

That's correct.

> also after completing all of them?

Yes, but only after people bring back the task list from the celebratory card when they complete all tasks. Then they'll see the `Welcome to <store_name>` message along with a list of completed tasks. It's the same for both layout experiments.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/79307566/165331915-32378c15-c00c-4288-b1e5-237194b510c5.png">

**Comment by octaedro** [comment]
Hi @jarekmorawski,

I have an additional question 🙂

>> when the user doesn't have any completed tasks

>That's correct.

Does that include the OBW? I mean, will the title (`Welcome to <store_name>`) be visible after the user finishes the OBW?

**Comment by octaedro** [comment]
I'm writing down what @jarekmorawski  and I talked about in slack.
The progress header title (`Welcome to <store_name>`) will be visible after finishing the OBW too.
