### ISSUE TITLE
Payments settings: recommended extensions card tweaks

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32168]
**Description:** we plan to refine how we display the additional payments card in the Payment settings screen, in order to minimize cognitive load and increase the focus on setting up WCPayments.

**Acceptance criteria:**
- [ ] Hide list of additional payment gateways when WCPayments is available
- [ ] Apply low visual treatment to additional payment gateway options (PayPal, Stripe, etc) when WCPayments is available

Final mockups coming soon

**Event tracking:**
TBD

**Comment by adrianduffell** [comment]
Just blocking this until the final mockups are ready.

**Comment by pmcpinto** [comment]
I created a new issue about this: #32130
