### ISSUE TITLE
Add a wc_version prop to all events

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32178]
**Description:** as we introduce changes in the product experience it can be difficult to have a clear picture of the impact of our work, as not everyone is using the latest version of WooCommerce.

**Acceptance criteria:**

- [ ] Add a wc_version prop to all the wcadmin_ events, in order to have a clear picture of the WC version being used when the event is fired.

**Comment by beaulebens** [comment]
This might provide the foundation for a good approach; https://github.com/woocommerce/woocommerce/pull/32060

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/32178?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro
