### ISSUE TITLE
Manually disabled ExPlat experiments doesn't stop users from getting treatment

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#32171]
### Describe the bug
It seems that a user may be able to get treatment experience on an experiment that's prematurely disabled. We suspect it to be related to cache/TTL. The bug identified was using [PHP ExPlat integration](https://github.com/woocommerce/woocommerce-admin/blob/release/3.2.0-rc.1/src/Features/WcPayWelcomePage.php), but it's worth checking both PHP and JS implementation.

User first treatment exposure: 9th Feb
Experiment disabled: 10th Feb
User still getting treatment after experiment disabled: 18th Feb

Relevant logs: p1645498640168989/1645225634.037509-slack-CGGCLBN58

### To Reproduce
Unsure on how to reproduce, but we could try:
1. Create a new experiment in Abacus, status staging
2. Assign ourselves treatment via bookmarklet
3. Disable the experiment in Abacus
4. Refresh and see how long the treatment experience lasts (it should not be more than TTL)

### Expected behavior
Experiments should not outlive their TTLs and get refreshed of its latest status. Disabled experiments should also remove treatment experience.

**Comment by adrianduffell** [comment]
I've looked into this on the PHP side of things, but couldn't find a fault in the caching implementation. It essentially defers caching to WordPress using the transient system and looks to be working well.

I followed the steps above using the PHP client but could not reproduce.

**Comment by ilyasfoo** [comment]
Thanks for investigating, @adrianduffell! I think this may have been a one-off oddity or the user's setup may have something up. I think it's safe to close this issue.
