### ISSUE TITLE
Simplify the init routine

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32174]
### Is your feature request related to a problem? Please describe.

With WooCommerce Admin no longer being released as a feature plugin, the init routines of the feature plugin could be removed, along with the de-activation logic when the Core version is not met.

### Describe the solution you'd like

Streamline the code in `woocommerce-admin.php` and `src/Composer/Package.php` into a simplified init routine.

### Describe alternatives you've considered

n/a

### Should this be prioritized? Why?

Yes, the merge is happening soon

### Additional context

Internal discussion p90Yrv-2If-p2

**Comment by adrianduffell** [comment]
This is currently blocked as it is dependent on Woo Admin being moved to the monorepo first.

**Comment by chihsuan** [comment]
@adrianduffell Could we remove `woocommerce-admin.php` and `uninstall.php`?

Looks like`woocommerce-admin.php` is only be used in unit tests and [`wcAdminAssetUrl`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Settings.php#L179-L181. I think we could simply remove it from tests and retire the `wcAdminAssetUrl`.

**Comment by adrianduffell** [comment]
Thanks for the ping @chihsuan ,

* I think `woocommerce-admin.php` is good to remove now. It was only being used to init the feature plugin.
* I think `uninstall.php` can be removed. It looks like the `drop_tables()` call is being made in Core already. https://github.com/woocommerce/woocommerce/blob/605fc47389829501d16e3467dc8be009c69f4426/plugins/woocommerce/uninstall.php#L32
* `wcAdminAssetUrl` needs some effort to retire. It might be better to create a new issue for it. We would need to post a developer advisory on the WooCommerce blog and check for any usage of the setting in the marketplace extensions and other plugins like WC Pay. I can help wrangle this.

**Comment by chihsuan** [comment]
Thanks @adrianduffell, I'll go head to remove them and simplify the `src/Composer/Package.php`.
 
I have also added a new [issue](https://github.com/woocommerce/woocommerce/issues/32491) to our backlog for `wcAdminAssetUrl`.
