### ISSUE TITLE
Investigate next steps for TypeScript migration

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32179]
TypeScript support was added to the WooCommerce Admin and WC Calpyso Bridge projects in 2021 and some components were migrated over.

This investigation should survey previous work done migrating to Typescript and make suggestions for next steps.

**Comment by rjchow** [comment]
The current state of the entire WCA repo has
- 42656 LOC in 756 JS/JSX files
- 15894 LOC in 192 TS/TSX files

The breakdown within `./client` and `./packages`:

`./client`
- 45414 LOC in 381 JS/JSX files
- 6762 LOC in 59 TS/TSX files

`./packages:`
- 35894 LOC in 375 JS/JSX files
- 9132 LOC in 133 TS/TSX files

Within `./packages`, Typescript is correctly enabled and is free of any type errors. However within `./client`, it seems that type checking has not been correctly enabled and there are 173 errors that need to be fixed before we can begin enforcing Typescript checks in the build.

The general next steps for Typescript migration would look like this:
- [x] Enable TS checking for ./client repo (#8372)
- [x] Fix each of the TS errors as outlined in the task list (p90Yrv-2NC-p2)
- [x] Fix ./client tests TS errors
- [ ] Migrate @woocommerce/* as necessary, as part of fixing the errors from previous items
- [ ] Begin next phase which is to start transcribing existing JS files in `./client` to TS files

**Comment by adrianduffell** [comment]
Making some great progress here! Looks like our next step is 

* Migrate @woocommerce/* as necessary, as part of fixing the errors from previous items

**Comment by rjchow** [comment]
Might want to consider this! 

https://github.com/codemix/deprank#typescript-conversion

**Comment by chihsuan** [comment]
Closing this since we've completed it and started working on small issues. 🙂
