### ISSUE TITLE
Update i18n Text Domain

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32175]
### Is your feature request related to a problem? Please describe.

The Woo Admin and JS packages use a text domain of `woocommerce-admin` on i18n strings, and should be changed to `woocommerce` to align with Core.

### Describe the solution you'd like

Perform a global search/replace of `woocommerce-admin` i18n strings and replace with `woocommerce`

### Describe alternatives you've considered
n/a

### Should this be prioritized? Why?
Yes, the merge is happening soon.

### Additional context

* Internal discussion p90Yrv-2If-p2

**Comment by adrianduffell** [comment]
To prevent large amounts of code churn / conflicts, I've blocked this while the internal namespace refactor is underway.

**Comment by adrianduffell** [comment]
This is no longer blocked.

**Comment by adrianduffell** [comment]
There are scripts that converted the domain string previously when Woo Admin was bundled in Core.

* https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/bin/package-update.sh (PHP)
* https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/bin/package-update-textdomain.js

We need to match strings like :

 ```
 __( 'Learn more', 'woocommerce-admin' ),
 ```
and:
```
title={ __(
	'Good data leads to smart business decisions',
	'woocommerce-admin'
) }
```
but not:
```
$note->set_source( 'woocommerce-admin' );
```

**Comment by rjchow** [comment]
I'm assigning this to myself for C23 because I have an interest in exploring the application of [codemods](https://github.com/facebook/jscodeshift) 😬
