### ISSUE TITLE
Analytics: Add an option to report on payment methods used for orders

### ISSUE THREAD

**Issue by pauljacobson** [woothemes/woocommerce#32172]
### Is your feature request related to a problem? Please describe.

We have received requests from merchants for an option to generate reports in WooCommerce Analytics that include details of payment methods used for orders.

### Describe the solution you'd like

Add an option to generate a payment method report, perhaps integrated into the existing [Orders Report](https://woocommerce.com/document/woocommerce-analytics/#orders-report) functionality.

### Describe alternatives you've considered

Currently there aren't many convenient options. One possible workaround is the [WooCommerce Customer / Order / Coupon Export](https://woocommerce.com/products/ordercustomer-csv-export/?aff=10486&cid=1131038), although ideally this option should be integrated into the WooCommerce Analytics feature.

### Should this be prioritized? Why?

The priority is likely normal. That said, this is a gap in our product that our merchants have asked for.

### Additional context

The latest request is in 4781678-zen

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
