### ISSUE TITLE
Migrate Install Routine to Core Install Routine

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32176]
### Is your feature request related to a problem? Please describe.

The install routine is triggered from a change in WooCommerce Admin version number, however this is proposed to be deprecated in issue woocommerce/woocommerce#32177, resulting in the version number never changing.

The install routine also has concurrency issues presently, as described in PR https://github.com/woocommerce/woocommerce-admin/pull/8257.

### Describe the solution you'd like

The [Install class](https://github.com/woocommerce/woocommerce-admin/blob/aaeedf779385fd98e68c981cc2a3017bf1f50720/src/Install.php) shares a [similar structure to Core](https://github.com/woocommerce/woocommerce/blob/fbd450c24d38715c2c975c6a058095a995ec519a/plugins/woocommerce/includes/class-wc-install.php). To avoid the performance concerns and the ambiguity of having 2 install classes present, I'd like the contents of the Woo Admin `Install` class directly merged into Core’s. For example:

* Copy the contents of Woo Admin’s `get_schema`  into Core’s `get_schema`.
* Copy the contents of Woo Admin’s `create_events `  into Core’s `create_cron_jobs `.
* Copy Woo Admin’s `delete_obsolete_notes ` entirely and add a call to it in Core’s `install ` method.
* Copy Woo Admin’s `$db_updates` and associated callbacks into Core, however care needs to be taken to replace the version number key with the equivalent Core version number.

### Describe alternatives you've considered
n/a

### Should this be prioritized? Why?
Yes, the merge is happening soon

### Additional context
* Internal discussion p90Yrv-2If-p2

**Comment by moon0326** [comment]
As we discussed in /C01SFMVEYAK/p1646379430146279 (slack thread), we'll implement some of the simple changes (https://github.com/woocommerce/woocommerce-admin/pull/8384, https://github.com/woocommerce/woocommerce-admin/pull/8421 and https://github.com/woocommerce/woocommerce-admin/pull/8423)  in WCA first then migrate the routine to the core after the merge.

**Comment by adrianduffell** [comment]
Just blocking this until after the merge.

**Comment by adrianduffell** [comment]
This was fixed by PR https://github.com/woocommerce/woocommerce/pull/32513.
