### ISSUE TITLE
Revisit the shipping and tax smart defaults

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32180]
**Description:** smart defaults are a powerful way to simplify the setup experience, remove friction and ensure that users can focus on critical tasks. 
We've tested the shipping and tax smart defaults concept during 2020. See woocommerce/woocommerce-admin#4594 and woocommerce/woocommerce-admin#4595. However, was had some issues as both tasks rely on 3rd party plugins (Jetpack and WooCommerce Shipping and Tax) and we ended up removing them during Q1 2021. I think we could have done a better job of making sure that users understood what had been automatically configured and how they could confirm and adjust the settings. We should revisit the smart default idea, starting with the shipping task. In the Tax task we're required to display the WC Tax and Avalara. 

**Acceptance criteria:**
TBD

**Event tracking:**
TBD

**Comment by adrianduffell** [comment]
Closing due to age
