### ISSUE TITLE
Store profiler - business features step: install extensions in the background

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32184]
**Description:** this issue is a spin-off of woocommerce/woocommerce-admin#6988. About 17% of users drop the store profiler flow in the business features step. Although the conversion rate is relatively healthy, it is below the other profiler steps. They are usually around 98% conversion rate.

One of our assumptions is that users are having issues while the extensions are being installed, as it was outlined here: woocommerce/woocommerce#32234

Now that we have an asynchronous option to install plugins (#8079), we should evaluate if it makes sense to install and activate the extensions in the background.

We can start by identifying the pros & cons of moving forward with this approach:

**Pros**
- We mitigate the risks of having users stuck in the business features step
- The business features > theme step transition will be faster

**Cons**
- How can we address the install/activate failure use case in this scenario?

**Comment by pmcpinto** [comment]
@mattsherman @joshuatf @jarekmorawski I'd love to have your feedback regarding this topic.

**Comment by joshuatf** [comment]
I'm definitely in favor of doing this and I think this will be a great improvement to have in the setup wizard flow.  Seeing how long wait times could be on this step was a little shocking and definitely something I think we should prioritize.

While it's obviously much quicker than if a user was to install the plugins one by one, it's detrimental to the user experience in the wizard.

The async plugin installer should almost entirely resolve this issue, so I don't see a lot of heavy lifting here to implement this (my gut feel is a 3 estimate).  Though one thing we need to consider is error handling of failed plugin installations.  The two immediate options I see are:

* Create a note (optionally as an alert type to place it at the top of screens) showing failed plugin installations, along with any actions that can be taken.
* Using the `TransientNotice` api to show on next refresh.  However, these by nature are transient and may not give the user enough time to act on any actions needed.

**Comment by mattsherman** [comment]
@pmcpinto @joshuatf @jarekmorawski  I'd like Mothra to tackle this in Cycle 22.

> Create a note (optionally as an alert type to place it at the top of screens) showing failed plugin installations, along with any actions that can be taken.

This seems like a good approach to take, especially with the alert type to ensure it is at the top of screens.

**Comment by pmcpinto** [comment]
> Create a note (optionally as an alert type to place it at the top of screens) showing failed plugin installations, along with any actions that can be taken.

Creating an inbox notification can work well. @jarekmorawski @verofasulo what do you think?

**Comment by jarekmorawski** [comment]
> we should evaluate if it makes sense to install and activate the extensions in the background.

I think it still does. People don't think of the plugins we install during onboarding as separate features—rather features that they can toggle on and off. Having them enabled in the background means less friction in the setup journey.

> Creating an inbox notification can work well. @jarekmorawski @verofasulo what do you think?

Out of curiosity, how often does installation or activation fail? What people can do to fix that?

Inbox notes have rather low visibility (and people have lots of them when they start off), which means that ours could get lost or be ignored. I wonder if we could add a L2 task to Things to do next? Preferably linked to the Marketplace and/or some type of guide.

> Setup and enable [plugin_name]

In this case we don't really need to inform people that something has failed (no one wants to start a new experience with an error notice). The task should work as a reminder and help people fix the plugin that broke. What do you think?

**Comment by mattsherman** [comment]
> In this case we don't really need to inform people that something has failed (no one wants to start a new experience with an error notice). The task should work as a reminder and help people fix the plugin that broke. What do you think?

Not framing it as an error makes sense.

I do wonder though... if we think that the user can install these extensions without providing any additional information (merely clicking the task), we should consider auto-retrying to install the extension at least one more time before showing anything to the user.

What do you envision the task for one of these would look like?

**Comment by jarekmorawski** [comment]
> we should consider auto-retrying to install the extension at least one more time before showing anything to the user.

Love that. 👍 Maybe we could try 3 times on 2 consequential visits (2+1), then show the task?

> What do you envision the task for one of these would look like?

The task could say: **Get [plugin_name] to enable it on your store**. Clicking the task would ideally show some sort of a loading state and success or error message. I'm thinking about snackbar since they're quite flexible and don't require a more complex interface.

* User clicks the task in `Things to do next`
* We show a toast message: `Enabling [plugin_name]...`
* (if success) We show another toast message: `Enabled [plugin_name]. Enjoy!`
* (if error) We show another toast message: `We couldn't enable [plugin_name]. Try again` where `Try again` would be a button triggering another installation attempt.

What do you think?

**Comment by mattsherman** [comment]
> > we should consider auto-retrying to install the extension at least one more time before showing anything to the user.
> 
> Love that. 👍 Maybe we could try 3 times on 2 consequential visits (2+1), then show the task?

Since we are installing them in the background already, we could probably set up a scheduled action to retry. So, we wouldn't be dependent on the user accessing the home screen to trigger the retry.

> > What do you envision the task for one of these would look like?
> 
> The task could say: **Get [plugin_name] to enable it on your store**. Clicking the task would ideally show some sort of a loading state and success or error message. I'm thinking about snackbar since they're quite flexible and don't require a more complex interface.
> 
> * User clicks the task in `Things to do next`
> * We show a toast message: `Enabling [plugin_name]...`
> * (if success) We show another toast message: `Enabled [plugin_name]. Enjoy!`
> * (if error) We show another toast message: `We couldn't enable [plugin_name]. Try again` where `Try again` would be a button triggering another installation attempt.

I think that snackbar/toast messages are easily missed, since they are not in the direct field of vision for the user.

I think each task should take the user to a distinct task page where we show the loading/progress state and then the result. Since these tasks would only be for the scenario where we were able to automatically install the plugin in the background initially (and with the re-try), I think the experience should be tailored on the more common error outcome, where the plugin still fails to install and we need to direct the user to support/documentation.

**Comment by pmcpinto** [comment]
> As a part of this repository’s maintenance, this issue is being marked as stale due to inactivity. Please feel free to comment on it in case we missed something.

This is still in our backlog to be implemented in one of the upcoming cycles.

**Comment by adrianduffell** [comment]
Background installation has been introduced in the new profiler.
