### ISSUE TITLE
Tracks on the backend should allow for easier testing

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#32188]
### Is your feature request related to a problem? Please describe.
When testing we have a difficult time mocking track functionality.

### Describe the solution you'd like
Either a quick investigation into an easy solution or some function to more easily mock tracks during test.

### Describe alternatives you've considered
In a recent PR, I've explicitly returned a value from a function to show that tracks have been recorded.  However, this only works in methods that are isolated with small responsibilities and is not ideal for all scenarios.

### Should this be prioritized? Why?

Yes, so that we can address testing of all tracks issues.  See woocommerce/woocommerce#32192

**Comment by joshuatf** [comment]
There are some libraries here that would be useful in mocking out static methods or we could also create a wrapper around the tracks class and pass in instances, but I think both approaches bring some level of complication.

Instead, I think the best approach here is to keep logic of methods using tracks simple and return at a minimum a boolean response for testing purposes.

Closing this issue.

**Comment by becdetat** [comment]
I don't think returning a magic value for testing purposes only is a good solution to this. Having a tracks wrapper class that gets injected (we have prior art - see https://github.com/woocommerce/woocommerce-admin/blob/main/tests/remote-inbox-notifications/plugins-activated-rule-processor.php) is much cleaner and maintainable in the long run.

There is going to be a cost up front in converting units under test to use an injectable tracks component however I think it's worth it.

**Comment by joshuatf** [comment]
@becdetat I don't see any tracks wrappers in the file you linked to.  Or are you just referring to the dependency injection in those files?

I'm not opposed to moving towards dependency injection for testing/decoupling purposes, but it's definitely worth keeping in mind that we heavily rely on singletons and this will result in a decent amount of refactoring should we go this route.

**Comment by becdetat** [comment]
@joshuatf  I'm just referring to dependency injection.

We can keep the singletons and existing static usages, just use a wrapper class for DI whenever you want to test a specific tracks usage. The wrapper class calls the static `WC_Tracks::record_event()` but it can be swapped out with a mock for the test.

Only the code under test needs to be changed to accept a tracks implementation via DI - the other tracks usages continue to use the static method.

**Comment by mattsherman** [comment]
@joshuatf @becdetat This issue is closed yet there continues to be discussion on it... reopening.
