### ISSUE TITLE
Tax task: provide more context about Automated Taxes

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32182]
**Description:** If the user has the store located in one of the countries covered by WC Tax, has the extension installed + connected to Jetpack, we nudge him to enable automated taxes. However, we don't provide any information about this feature and we should help users make an informed decision regarding enabling automated taxes. 
We provide links to the documentation through the Help panel, but Help has low usage. 

![Captura de ecrã 2022-02-03, às 17.27.47.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/d00b590b-f376-4c2f-ad76-350ba87f6024)

**Acceptance criteria:**
TBD

**Event tracking:**
TBD

**Comment by adrianduffell** [comment]
Closing due to age
