### ISSUE TITLE
Store setup - introduce an additional flow to add store location

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32183]
**Description:** collecting the store location right at the beginning of the new user experience is critical, as payments, shipping, and taxes recommendations are tailored according to the store country. About 25% of new users skip the store profiler. Among them, less than 2% add the store location during the first 3 days of activity through settings or the shipping/tax tasks. 
When the user doesn't add the country, we automatically default them to the US. This means that we're not providing suitable recommendations to most users who skip the profiler, adding friction to the experience. 

**Acceptance criteria:**
TBD

**Event tracking:**
TBD

**Comment by pmcpinto** [comment]
@jarekmorawski how do you think we could solve this?

**Comment by jarekmorawski** [comment]
> how do you think we could solve this?

I can see 2 ways:

* default to the geolocation and let people fix/update the address later in settings
* if someone skipped the profiler, we'd ask them in a modal like many ecommerce stores do (example below)

![image](https://user-images.githubusercontent.com/79307566/152808607-0978b729-e250-448e-84cc-3716956400e9.png)

I think the two aren't mutually exclusive and could work well together.

**Comment by pmcpinto** [comment]
> default to the geolocation and let people fix/update the address later in settings

Using geolocation or the locale set in WordPress can be too complex. See this [issue](https://github.com/woocommerce/woocommerce/issues/29499) for more details.

I think that using a modal or a setup task (which is less intrusive) is our best shot. cc @verofasulo as you're also exploring the setup flows

**Comment by verofasulo** [comment]
Thanks for the tag @pmcpinto. I had no idea the percentage of users that skip the store location was so high. I think it makes sense to introduce this point as the first step of the task list so that the user can be addressed to Settings > General.

**Comment by pmcpinto** [comment]
I will close this issue, since we already have others with a couple of different solutions that we want to explore:
#32586
#32587
#32585
