### ISSUE TITLE
Add __unstableHTML option to createNotice() with API error messages where appropriate

### ISSUE THREAD

**Issue by jacob-sewell** [woothemes/woocommerce#32190]
Issue woocommerce/woocommerce-admin#4314 referenced one particular API call whose error message gets put into a Snackbar via `createNotice()`. As of PR woocommerce/woocommerce-admin#8173 it's possible to preserve tags in messages displayed in a Snackbar if you pass `{ __unstableHTML: true }` as a third parameter to `createNotice()`. This only affects the specific Sample Products Import case, so any other API calls that display server-provided messages in a `Snackbar` might need the same change.

From @joshuatf's review:

Just noting that we still need a follow-up for this.  This solves the issue in this task, but we would need to do this in all REST API calls since this error has the potential to pop up in any of those.

I would love a more catch-all solution, but this may be the best to handle this.

_Originally posted by @joshuatf in https://github.com/woocommerce/woocommerce-admin/issues/8173#issuecomment-1021499624_

**Comment by adrianduffell** [comment]
Going to close this due to the lack of activity on the issue and unstable APIs are [now considered dangerous](https://github.com/WordPress/gutenberg/pull/46131). Please feel free to re-open however.
