### ISSUE TITLE
Setup Wizard: No maximum file size limit when uploading themes

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#32199]
### Description
Seems there isn't any file size restriction when uploading themes. I could start uploading a +700MB zip file that resulted in a HTTP 500 after 36 seconds loading, with the following message: 
```
{
   "code":"internal_server_error",
   "message":"<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>",
   "data":{
      "status":500
   },
   "additional_errors":[
      
   ]
}
``` 

### To Reproduce
1. Start the Setup Wizard.
2. Fill the "Store Details", "Industry", "Product Types" and "Business Details" forms and go to the "Theme" page.
3. Click on "Upload a theme" at the bottom.
4. Select a really big zip file (greater than 500 MB at least, as this is the default WordPress file size restriction).

### Actual behavior
The file starts loading and - after a while - the page raises a critical error.

### Video
https://user-images.githubusercontent.com/45979455/149211085-1ecd6bbd-def0-453e-9d0b-f964d1224cc2.mp4

### Expected behavior
The page should check the file size before starting the upload and let the user know that the file couldn't be uploaded because it increase the allowed limit. Apart from that, the API should return a different HTTP status code, like 408 or 413, and provide a more appropriate  error message.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.0
* WooCommerce 6.1.0-dev
* PHP 7.4.25

### Additional context
Please find attached the HAR file of the session, just in case it could be helpful for debugging the issue:
[Setup Wizard P01.zip](https://github.com/woocommerce/woocommerce-admin/files/7857324/Setup.Wizard.P01.zip)

### Comments
In the video you won’t see the OS window that opened after I clicked the button to upload the file, and where I selected the file to be uploaded. There is nothing wrong about that in WooCommerce, it’s just that the software I used for recording the screen can’t record multiple applications at the same time.

**Comment by joelclimbsthings** [comment]
Thanks @alopezari , this is an interesting one. Since the upload limit is often set by the host, and WooCommerce is in general host agnostic, it's a bit debatable on how to approach this. Options:
- Just say that we don't see the need to police this on this layer, and that's up to the host configuration (although that doesn't help the usability aspect here)
- Just set this to some static sane limit client-side, to assist with usability.
- Fetch any configured upload limit via `init_get('upload_max_filesize')` or something similar, and enforce that client-side as well.

I'd be curious for any other opinions @woocommerce/mothra .

**Comment by alopezari** [comment]
Indeed it's interesting! Please, let me know if I can help with anything or provide more info. I'm quite interested on how this one is addressed!

**Comment by adrianduffell** [comment]
Closing this out as the setup wizard has a new implementation now (themes are removed).
