### ISSUE TITLE
Setup Wizard: Error message in API after successfully entered the Store Address

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#32198]
### Description
When I submitted the “Store Address” field from the “Store Details” page, everything looked fine, I was redirected to the “Industry” page and no error message appeared on the UI. However, I checked the response from the `POST /wp-json/wc-analytics/settings/general/batch?_locale=user endpoint` and saw the following object in the response body:
```
"update": [
        {
            "id": "store_address",
            "error": {
                "code": "rest_setting_setting_invalid",
                "message": "Invalid setting.",
                "data": {
                    "status": 404
                }
            }
        },
        ...
```

### To Reproduce
1. Start the Setup Wizard
2. Complete the Setup Details form and click 'Continue'.
3. Check the response body of the `POST /wp-json/wc-analytics/settings/general/batch?_locale=user` request sent to the API.

### Actual behavior
Although everything looks fine in the UI, the following error message appears the response body:
```
"update": [
        {
            "id": "store_address",
            "error": {
                "code": "rest_setting_setting_invalid",
                "message": "Invalid setting.",
                "data": {
                    "status": 404
                }
            }
        },
        ...
```

### Video
https://user-images.githubusercontent.com/45979455/149217807-27ae6f3d-f7aa-4e31-bbe4-48ab68e38fae.mp4

### Expected behavior
No error should be shown in the response body, considering everything looks fine in the UI and seems data is persisted.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

### Additional context
Please find attached the HAR file of the session, just in case it could be helpful for debugging the issue:
[DQ02.zip](https://github.com/woocommerce/woocommerce-admin/files/7857619/DQ02.zip)

**Comment by joelclimbsthings** [comment]
Confirmed, I'm seeing this as well on `main`, although as mentioned it doesn't seem to be consequential in any way. That said, it's worth looking into this just to ensure nothing is amiss, and give the correct responses in our endpoints. 

It's possible the solution may lie in core as we're inheriting some of this logic from `WC_REST_Setting_Options_Controller` which resides there, but it will require a more in-depth analysis.

**Comment by adrianduffell** [comment]
Closing this out as it refers to the older setup wizard.
