### ISSUE TITLE
Test coverage for key tracks events

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32192]
We need to have test coverage for the following key tracks events. Please add your GitHub username to the table when you start and complete implementing coverage.

Edit by ilyas: These events might be outdated, please check if we're going to proceed with it. p7Ldg5-5Kv-p2#comment-12148

  |   | Started (username) | Completed (username)
-- | -- | -- | --
Store profiler |   |   |  
Event name | Description |   |  
wcadmin_storeprofiler_store_details_continue | Step 1 proceed |   |  
wcadmin_storeprofiler_store_details_skip | Step 1 skip |   |  
wcadmin_storeprofiler_store_industry_continue | Step 2 proceed |   |  
wcadmin_storeprofiler_store_product_type_continue | Step 3 proceed |   |  
wcadmin_storeprofiler_store_business_details_continue_variant | Step 4.1 proceed |   |  
wcadmin_storeprofiler_store_business_features_continue | Step 4.2 proceed |   |  
wcadmin_storeprofiler_store_theme_choose | Step 5 proceed |   |  
wcadmin_storeprofiler_complete | Profiler completion |   |  
wcadmin_storeprofiler_step_complete | Individual step completion |   |  
  |   |   |  
Task list |   |   |  
Event name | Description |   |  
wcadmin_tasklist_view | Task List view |   |  
wcadmin_task_view | Task view |   |  
wcadmin_tasklist_click | Task click |   |  
wcadmin_tasklist_task_completed | Task completed |   |  
wcadmin_tasklist_completed | Task List dismiss |   |  
wcadmin_tasklist_add_product | Add product task |   |  
wcadmin_tasklist_payment_install_method | Set up payments task - install |   |  
wcadmin_tasklist_payment_setup | Set up payments task click - "set up" |   |  
wcadmin_tasklist_payment_connect_method | Set up payments task - connect method |   |  
wcadmin_tasklist_tax_view_options | Tax task - view options |   |  
wcadmin_tasklist_tax_select_option | Tax task - select option |   |  
wcadmin_tasklist_tax_setup_automated_proceed | Tax task - enable automated taxes |   |  
wcadmin_tasklist_shipping_set_costs | Shipping task - set costs |   |  
wcadmin_tasklist_shipping_label_printing | Shipping task - enable printing labels |   |  
wcadmin_tasklist_marketing_install | Marketing task - get started |   |  
wcadmin_marketing_manage | Marketing task - manage |   |  
wcadmin_tasklist_appearance_import_demo | Personalize task - import content |   |  
wcadmin_tasklist_appearance_upload_logo | Personalize task - upload logo |   |  
wcadmin_tasklist_appearance_create_homepage | Personalize task - create homepage |   |  
  | Personalize task - finish/add notice |   |  
  |   |   |  
Store management |   |   |  
Event name | Description |   |  
wcadmin_page_view | Page view |   |  
wcadmin_inbox_note_view | Inbox view |   |  
wcadmin_inbox_action_click | Inbox click |   |  
wcadmin_orders_edit_status_change | Update order status |   |  
wcadmin_orders_view | View orders screen |   |  
wcadmin_orders_view_search | Orders search |   |  
wcadmin_settings_view | Settings page view |   |  
wcadmin_settings_change | Settings change |   |  
wcadmin_product_add_publish | Product publish |   |  
wcadmin_product_import_complete | Product import finish |   |  
wcadmin_product_update | Product update |   |  
wcadmin_products_view | Product view |   |  
wcadmin_products_search | Product search |   |  
wcadmin_ces_feedback | CES feedback |   |  
wcadmin_ces_view | CES view |   |  
wcadmin_analytics_filter | Analytics filter |   |  
wcadmin_activity_panel_open | Activity panel open |   |  
wcadmin_activity_panel_orders_orders_begin_fulfillment | Activity panel - begin fulfillment |   |  
wcadmin_activity_panel_stock_update_stock | Activity panel - update stock |   |

**Comment by adrianduffell** [comment]
Closing this out as it is no longer a planned project. If we do wish to revisit it, I think we should file separate issues for each of the Tracks events.

**Comment by ilyasfoo** [comment]
Re-opening since there's interest to ensure tracks reliability. p7Ldg5-5Kv-p2#comment-12149

**Comment by jonathansadowski** [comment]
@ilyasfoo I added the team label to this, please feel free to change if that's incorrect

**Comment by ilyasfoo** [comment]
Hi, @jonathansadowski! I think it's more appropriate to assign tracks to relevant teams according to work area. I think we'll end up with multiple issues later on. FYI, there's changes to the list above, particularly around onboarding p7Ldg5-5Kv-p2#comment-12148.

**Comment by adrianduffell** [comment]
@ilyasfoo, do you want to create individual issues for the highest priority onboarding events (to start with)? I think that will be a simpler workflow to handle.

I'll close this issue because it's too unwieldy  😅
