### ISSUE TITLE
Setup Wizard: Question from Business Details form is not shown properly in smartphone resolution

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#32197]
### Description
When using Chrome with an **iPhone X resolution**, the first question of the form at the Business Details page is not fully readable. Users familiar to WooCommerce won’t have any problem to answer that question, but those new users might not be sure about what is the form asking about. It would be nice to find about a way to show the full question in the dropdown.

### To Reproduce
1. Start the Setup Wizard
2. Complete all the pages until you reach the "Business Details" one
3. Check the first question of the "Business Details" form (_How many products do you want to display?_)

### Actual behavior
It doesn't fit in the component and is not fully readable.

### Screenshots
![CP01](https://user-images.githubusercontent.com/45979455/149219353-433acdc6-b645-4af4-8c78-5964686d9ee5.png)

### Expected behavior
It should be fully readable by the user.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits) **running on iPhone X resolution**
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

**Comment by joelclimbsthings** [comment]
Thanks @alopezari , I was able to see the same and we definitely want this to be readable via a mobile device. I'm not immediately sure what the best solution would be, so I'll loop in @elizaan36 to see if she has any thoughts.

**Comment by elizaan36** [comment]
Thanks for pointing this out, @alopezari!

@jarekmorawski Would you mind taking a look at this?

**Comment by jarekmorawski** [comment]
Ideally, the labels would sit outside the fields, but that's not how they're currently built. We might change that in the future but for now maybe we could make the the text break in two lines? It'll take up more space, but it'll be legible.

**Comment by adrianduffell** [comment]
This was fixed in the new core profiler.

<img width="353" alt="Screen Shot 2024-03-01 at 3 57 16 pm" src="https://github.com/woocommerce/woocommerce/assets/9312929/64289f29-c887-4aea-9067-2aacd12f0d2e">
