### ISSUE TITLE
Suggestion: Remove padding/margin around paragraph tags in Snackbar notices

### ISSUE THREAD

**Issue by jacob-sewell** [woothemes/woocommerce#32191]
As of PR woocommerce/woocommerce-admin#8173 it's possible to include markup in Snackbar error notices, though the only place it's currently happening is on server-side errors importing sample products. This can result in some odd padding if the error message has a `p` tag in it.

![Screen Shot 2022-01-25 at 13 19 34](https://user-images.githubusercontent.com/890809/151044512-dd7d3184-da45-4569-baad-fac834a24f5e.png)

From @louwie17's review:

I was wondering if we should remove the styling on a `p` tag within the snackbar component (only the direct children). Something like this:
```
components-snackbar__content > div > p { margin: 0; padding: 0 }
```

I am not totally set on this, as it doesn't seem like a huge issue, just me being slightly picky on the extra spacing.

Also for reference I added this filter to my `mu-plugin` to product the error:

```
add_filter('woocommerce_product_csv_importer_class', function() {
    throw new \RuntimeException();
    return '';
});
```

_Originally posted by @louwie17 in https://github.com/woocommerce/woocommerce-admin/pull/8173#pullrequestreview-862664116_

**Comment by adrianduffell** [comment]
I'll close this out -- I don't think server-side error messages should be directly output to users. To solve this, I think we would be better to provide the Snackbar with a string more tailored for users.
