### ISSUE TITLE
Setup Wizard: Recently uploaded theme gets lost under certain conditions

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#32200]
### Description
If you are at the "Theme" page, and you have uploaded a theme successfully, when you go back to another page in the form and go to Theme again, the theme is not found in the list. If you try to upload it again, a message raises saying "Destination folder already exists", but you won't be able to see the new theme in the list in order to select it. This is solved once you exit the Setup Wizard and open it again.

### To Reproduce
1. Start the Setup Wizard.
2. Fill all the forms until you reach the "Theme" page.
3. Upload a valid theme.
4. Go back to the "Business Details" page.
5. Go again to the "Theme" page.

### Actual behavior
The new theme is not shown in the list, and you are not able to upload it again.

### Video
https://user-images.githubusercontent.com/45979455/149210107-bfdc5000-ef82-48f2-9613-5fae73dd15dc.mp4

### Expected behavior
The new theme should be in the list.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

### Comments
In the video you won’t see the OS window that opened after I clicked the button to upload the theme, and where I selected the theme to be uploaded. There is nothing wrong about that in WooCommerce, it’s just that the software I used for recording the screen can’t record multiple applications at the same time.

**Comment by joelclimbsthings** [comment]
Thanks again @alopezari ! Definitely a valid issue, and I confirmed it with another theme on the latest `main`.

**Comment by adrianduffell** [comment]
Closing this out as the setup wizard has a new implementation now.
