### ISSUE TITLE
Filter notes in inbox and home screen by user capability

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#32206]
### Description

Currently any note is displayed to any user that has access to the **WooCommerce > Home** screen. Some of these notes focus on specific tasks like creating a product, or enabling a payment gateway and it could be that users don't have those privileges, but are still shown this note while on the WC homescreen.

We should filter notes by a users capability. This will require, either adding a `capability` column to the `wp_wc_admin_notes` table and/or adding this to our Note class, the second approach would not work for any notes coming from the remote inbox notification.

See here for more context: p90Yrv-2vK-p2#comment-6480

### Acceptance criteria
- Notes on home screen should be filtered by user capability
- A capability option should be added to the Note class
- We should be able to define the capability in our json for remote inbox notifications

**Comment by moon0326** [comment]
I'll work on the remote inbox notification part.

**Comment by mattsherman** [comment]
@moon0326 Since you have assigned yourself to this and mentioned you are working on it, can you please move it to the appropriate pipeline? Thanks!

**Comment by moon0326** [comment]
I'll work in it as a cooldown task next week.

**Comment by moon0326** [comment]
Hey @mattsherman 

It's been a long time and I will probably start working on it soon (hopefully 😄 ), but I wanted double check since Inbox is now owned by Mothra.

Do you want to take it over by any chance?

**Comment by mattsherman** [comment]
@moon0326 It makes sense for Mothra to handle this, since we are responsible for Inbox.

Do you agree, @adrianduffell ?

**Comment by adrianduffell** [comment]
@mattsherman Yeah, agree, although I'm happy for Ghidorah team members to work outside of Start as part of professional development opportunities.

There's perhaps an opportunity for @moon0326 to work closely with Mothra on this if you're both interested.

I'll move it out of the Ghidorah backlog however.

**Comment by adrianduffell** [comment]
Closing this out due to age
