### ISSUE TITLE
Fatal error in WooSubscriptions note when accessing note that doesn't exist

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32216]
### Describe the bug
A site owner reported a fatal error in the `WooSubscriptionsNotes` class.

```
An error of type E_ERROR was caused in line 204 of the file /home/customer/www/crefovi.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WooSubscriptionsNotes.php. Error message: Uncaught Error: Call to a member function get_content_data() on bool in /home/customer/www/crefovi.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WooSubscriptionsNotes.php:204 
Stack trace: 
#0 /home/customer/www/crefovi.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WooSubscriptionsNotes.php(224): AutomatticWooCommerceAdminNotesWooSubscriptionsNotes->get_product_id_from_subscription_note(false) 
woocommerce/woocommerce-admin#1 /home/customer/www/crefovi.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WooSubscriptionsNotes.php(417): AutomatticWooCommerceAdminNotesWooSubscriptionsNotes->prune_inactive_subscription_notes() 
woocommerce/woocommerce-admin#2 /home/customer/www/crefovi.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WooSubscriptionsNotes.php(97): AutomatticWooCommerceAdminNotesWooSubscriptionsNotes->refresh_subscription_notes() 
woocommerce/woocommerce-admin#3 /home/customer/www/crefovi.com/public_html/wp-includes/class-wp-hook.php(3
```

We can see in the stacktrace, a call is made to `get_product_id_from_subscription_note ` with a note of `false`, rather than a valid `Note` object. A possible quick fix is to check for `false` return values and defensively handle them.

A possible reason for the `false` return value is due to a race condition. The `refresh_subscription_notes` method is run on the  WordPress `admin_init` hook, but does not have a locking system to prevent multiple users on the site triggering the refresh at the same time. I think a fix for this situation would be bringing the routine into a cron or Action Scheduler job.

### To Reproduce

Not yet available.

### Actual behavior:

The resulting fatal error causes WordPress to send an email to the site owner with the stacktrace.

### Expected behavior

Graceful handling and logging of the error instead of fatal error.

### Additional context
Original zendesk issue: 4553364-zd-woothemes

**Comment by zackeryfretty** [comment]
Is there any update on this? We've recently been seeing the same thing on several of our WooCommerce sites. Typically when logging in as an admin.
