### ISSUE TITLE
Add slots to allow fills in main content area of pages

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#32214]
### Is your feature request related to a problem? Please describe.
Related to https://github.com/Automattic/wc-calypso-bridge/issues/720

### Describe the solution you'd like
Being able to extend the main content area of pages with SlotFill would greatly improve the extensibility of all WCA pages.

### Describe alternatives you've considered
We could hardcode these elements in WCA, but that feels very messy and outside the scope of WooCommerce Admin.

### Should this be prioritized? Why?
In general, SlotFill extensibility needs to be addressed, but we need a thorough plan on how we plan to tackle.

**Comment by adrianduffell** [comment]
I'll close this out due to age and because a SlotFill approach has been used to provide extensibility to Calypso Bridge in the time since.
