### ISSUE TITLE
Resume the install routine after failure

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32218]
### Is your feature request related to a problem? 

An install routine runs every time Woo Admin is updated, performing jobs such as migrating the database.

https://github.com/woocommerce/woocommerce-admin/blob/aa608396ce1427b58d2573c3971089bf95dc3e5a/src/Install.php#L189-L214

However when the install routine fails for some reason, it can leave the site in an expected state with not all jobs being completed. 

These types of issues were reported in PR https://github.com/woocommerce/woocommerce-admin/pull/6726.

### Describe the solution you'd like

The progress of the install routine could be tracked, with the ability for admin users to resume it after a failure. Logging could also be added to report failures.

### Describe alternatives you've considered

N/A

### Should this be prioritized? Why?

Yes, the current situation leaves users without a path to perform corrective actions when the site is in an unexpected state.

**Comment by joshuatf** [comment]
This issue affects a relatively small subset of users, but does impact the product experience.  Keeping this issue open for now.

Also noting here that while potentially somewhat out of scope for this issue, scheduled update actions through action scheduler are not guaranteed to run in order and version update callbacks (which signal the end of an update) have potential to cause issues.

**Comment by adrianduffell** [comment]
I'm going to close this out now that WooCommerce Admin is merged to Core and no longer has its own install routine. Potentially, the same improvement could be made to the Core install routine, but I haven't seen evidence of any failures to justify it.
