### ISSUE TITLE
Restore previous name for paypal gateway in relevant tracks events. 

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#32225]
The switch to remote payment gateways resulted in an inadvertent change for the ID for the Paypal gateway. 

Previously identified as `paypal`, it's now referred to as `ppcp-gateway` in tracks events. Explore options for restoring the previous ID of `paypal` in events such as `wcadmin_tasklist_payment_setup` currently fired [here](https://github.com/woocommerce/woocommerce-admin/blob/a6e35e94333cb07f95327c0f4629d44343c4d587/client/tasks/fills/PaymentGatewaySuggestions/components/List/Item.js#L91).

For additional background on why this was created, see https://github.com/woocommerce/woocommerce-admin/issues/7836.

**Comment by pmcpinto** [comment]
@joelclimbsthings is it possible to implement this change in cycle 20?

**Comment by joelclimbsthings** [comment]
@pmcpinto This hasn't been pointed, but I don't believe this would be a problem to bring into cycle 20 👍🏻

**Comment by adrianduffell** [comment]
@joelclimbsthings @pmcpinto Do you know if this issue was resolved?

**Comment by joelclimbsthings** [comment]
@adrianduffell Glancing at the [more recent tracks events](https://mc.a8c.com/tracks/events/event.php?eventname=wcadmin_tasklist_payment_setup), I think not. That may have been a miss on my part, although I don't recall the details. At this point I'm not certain of if it would be desired to go ahead with changing the name, so I'll defer to @pmcpinto .

**Comment by adrianduffell** [comment]
No worries, thanks @joelclimbsthings , I'll go ahead and close this out as I'd agree it wouldn't be desirable to change the name now.

@pmcpinto please just go ahead and re-open the issue if you disagree 😊
