### ISSUE TITLE
[Setup Wizard]- Free features options present on Business Details page are getting selected automatically even though user has not selected them during the setup.

### ISSUE THREAD

**Issue by shishurajpandey** [woothemes/woocommerce#32223]
### Describe the bug
[Setup Wizard]- When the User is navigated to the WooCommerce Setup Wizard flow and is on the `Free features` section of the `Business details` page, then if the user unselects them and move to the next step which is for choosing the theme now if the user moves back to `Business Details` page and check for `free features` sections then all the options are shown as selected even though user unselected them while setting up the store.

### To Reproduce

1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Now move on to the `Free features` section of the `Business details` page, Uncheck all the checked items and press continue.
4. When the user is on the `Choose a theme ` section now again move back to the `Free features` section of the `Business details` page using the browser back button or by selecting `Business details` present on top.
5. When a user is on the `Free features` section of the `Business details` page check that all the options present on `Free features` are coming as checked.

### Actual behavior:
If the user moves back to the `Business Details` page and checks for the `free features` sections then all the options are shown as selected even though the user unselected them while setting up the store.

### Screenshots

https://user-images.githubusercontent.com/19307354/140267060-02ced7db-7c5f-479f-bab4-b385038bc034.mp4

### Expected behavior
If the user has unchecked the items on the` Free features` page during the setup then those items should not be shown as selected once he moves back to the same page.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by moon0326** [comment]
Thank you @raj007champ for taking the time to test and report this issue. I was able to reproduce it locally.

I think this is also related to https://github.com/woocommerce/woocommerce-admin/issues/7890 issue. Basically, user updated values are not saved. We'll work on it as soon as possible.

**Comment by rjchow** [comment]
Closing since OBW has been deprecated
