### ISSUE TITLE
[Setup Wizard]- Selected items on Product Page is getting unselected on doing browser refresh(f5)

### ISSUE THREAD

**Issue by shishurajpandey** [woothemes/woocommerce#32222]
### Describe the bug
When a user moves back to the `Product page` of Setup Wizard flow from `Business details page` and make some changes on the page and saves it, Now if the user moves back to `Product page` again and do the browser refresh then the selected items are getting unselected.

### To Reproduce

1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Now complete the setup flow and move to the Business details page.
4. Now move back to the `Product page` of Setup Wizard flow from `Business details page` and make some changes on the page and save it by clicking continue.
5. Now again move back to `Product page` and do the browser refresh and verify the items which were selected on step 4.

### Actual behavior:
If the user moves back to the `Product page` again and do the browser refresh then the selected items are getting unselected.

### Screenshots

https://user-images.githubusercontent.com/19307354/140269741-fcf7dab4-d926-41d7-b227-d36fcfe1d15a.mp4

### Expected behavior
User-selected items should not be unselected/unchecked on doing the browser refresh.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by moon0326** [comment]
Thank you @raj007champ. I think this is also related to woocommerce/woocommerce#32223 and https://github.com/woocommerce/woocommerce-admin/issues/7890.

We'll take a loo at them together.

**Comment by joshuatf** [comment]
This issue still occurs.  It's likely related to preloaded data not being ready by the time the `Form` is initialized.

**Comment by chihsuan** [comment]
This issue has been fixed. I can't reproduce it with the latest WC.
