### ISSUE TITLE
[Setup Wizard] - Currency isn't clear on Themes

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#32228]
### Describe the bug

Similar to woocommerce/woocommerce#32230 - the prices listed on the Themes page aren't clear.  The $ currency symbol is used by a number of countries, and it's not clear that the prices shown are in USD.

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=theme
2. Click on 'Paid themes'

### Actual behavior:

Several themes are listed at $79.00 per year.  It's not clear if that's Canadian Dollars, US Dollars, Australian Dollars or some other currency.

### Screenshots

![Screen Shot 2021-10-11 at 5 19 26 PM](https://user-images.githubusercontent.com/80276/136870123-6327d633-237c-4d83-910c-453d8c652174.png)

### Expected behavior

The simplest solution would be to add some test to the footer stating "Prices shown are billed in US dollars", or to implement the currency code (USD, CAD, AUD). Optionally, it would be great if an estimated price in the local currency was shown (based on the selection in step 1).

### Desktop (please complete the following information):

* OS: MacOS
* Browser Chrome
* Version  94.0.4606.71

**Comment by octaedro** [comment]
Hi @lanej0,

Thank you for taking the time to share this idea, we really appreciate your help.

While this is clearly a great idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.

**Comment by chihsuan** [comment]
Closing this since the theme step has been removed from OBW.
