### ISSUE TITLE
[Setup Wizard] - User checked options are getting unchecked on doing refresh(F5) at Industry page of Setup Wizard flow.

### ISSUE THREAD

**Issue by shishurajpandey** [woothemes/woocommerce#32224]
### Describe the bug
- When a user is on the Industry page of Setup Wizard flow with few checked options and when the user tries to refresh the browser, the checked options are getting unchecked for the user.
- This issue is also happening if a user is trying to move back to the Industry page from some other sections and then do the browser refresh then in that case also user saved check options are getting unchecked.

### To Reproduce
1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Navigate to the Industry page of the flow and check some options and then do the browser refresh.
4. Observe your previously checked items on the page and see if they are getting unchecked.
5. To reproduce the second scenario, Save your checked options on the Industry page and continue to the product page. After moving to the product page, again move back to the Industry page by the browser back button and again do the browser refresh.
6. Observe your previously checked items on the Industry page and see if they are getting unchecked.

### Actual behavior:
Checked options of industry page is getting unchecked on doing browser refresh.

### Screenshots

https://user-images.githubusercontent.com/19307354/140187102-b7fa67aa-8144-4c7d-b7e1-b649a1d5f36c.mp4

### Expected behavior
The checked options should not be unchecked on doing the browser refresh

### Desktop (please complete the following information):

1. OS: Windows OS
2. Browser: Chrome
3. Version: 95.0.4638.69

**Comment by moon0326** [comment]
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it on my end. We'll work on it as soon as possible.

**Comment by moon0326** [comment]
Not stale. Reopening.

**Comment by adrianduffell** [comment]
Closing this out as the setup wizard has a new implementation now.
