### ISSUE TITLE
Support `@wordpress/components.Button` isLink as wc-admin link

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#32231]
### Is your feature request related to a problem? Please describe.

When developing Google Listings and Ads plugin. We have a number of button links: 
![image](https://user-images.githubusercontent.com/17435/135122371-f6b67c02-d599-43f5-b9e7-ad49aad55d2c.png)
We use [`@wordpress/components.Button`](https://wordpress.github.io/gutenberg/?path=/story/components-button--secondary), to achieve the look, to make it an accessible link, we just set the `href` component - easy and convenient.
```jsx
import { Button } from '@wordpress/components';
import { getNewPath } from '@woocommerce/navigation';
// …
<Button isSecondary	href={ getNewPath( null, '/google/settings' ) } >Edit</Button>
```

But it does the full page reload and does not use WC SPA feature.

In few places we tried making some use of `@woocommerce/components.Link` element:
```jsx
import { Button } from '@wordpress/components';
import { Link } from '@woocommerce/components';
import { getNewPath } from '@woocommerce/navigation';
// …
<Link href={ getNewPath( null, '/google/settings' ) }><Button isSecondary href={ getNewPath( null, '/google/settings' ) } >Edit</Button></Link>
```
Which uses the Woo navigation features, and looks good at the first sight.

But it has a few drawbacks:
- :red_circle:  A11Y is impaired, as the screenreader finds it as "Edit, button", instead of "Edit, visited link"
- :red_circle:  It produces invalid HTML `<a><button>`
- :factory_worker: Requires additional, fragile CSS workarounds
- :nail_care: HTML markup is a bit redundant `<Link><KindaLink>`
- :nail_care: :crystal_ball:  We may loose any features of WP.Button, for link buttons, like specific stling for visited button links, etc.

----

So we need to choose either:
- impaired experience for everybody, or
- impaired experience, for people using assistive technology

### Describe the solution you'd like

I'd like to be able to use an accessible link button, without compromising UX.

I was thinking of two solutions:
1. Make `@woocommerce/components` proxy `@wordpress/~` Buttons, adding the [`wc-admin` type handler](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/link/index.js#L47-L49).
	- + This could help cover other issues related to WC vs WP Links, like woocommerce/woocommerce#32236
	- - Requires significant implementation and maintenance effort.
2. Let the `Link` module export its intercepting logic, in the form of 
	- component hook (p7H4VZ-2IH-p2, @diegohaz is that the applicable use-case?)
	- more composable component
	- or just a bare function, that a consuming developer, could use to attach `onClick` to WP or any other component.
	Basically, export https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/link/index.js#L18-L40

### Describe alternatives you've considered

We could also think of a more sophisticated way to intercept any navigation on the DOM, or history API level. So any link pointing to a location within wc-admin would use SPA flow. With opt-in or opt-out strategy.

(For example, In my previous Web Components based project, we had a solution, that was intercepting all navigation, then was finding the originating `<a>` element (even in shadow/composed events), checking if it was within a scope/subtree of a specific custom element, let's call it `<wc-page>` for our case, and without opt-out via an attribute or another component. Then it was either doing page morph, or letting the default behavior)

### Should this be prioritized? Why?
I believe the longest we have this uncovered, the more workarounds will popup in the plugins, effectively increasing the global maintenance cost for A8C and 3PDs.

### Additional context

- The problem sparked to me at https://github.com/woocommerce/google-listings-and-ads/pull/1025#discussion_r717329726

**Comment by diegohaz** [comment]
> Let the `Link` module export its intercepting logic, in the form of
> * component hook (p7H4VZ-2IH-p2, @diegohaz is that the applicable use-case?)
> * more composable component
> * or just a bare function, that a consuming developer, could use to attach `onClick` to WP or any other component.
>   Basically, export https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/link/index.js#L18-L40

I think all of these options are applicable. The Link logic could be provided through a component hook, render props, or component injection ([video talking about these patterns](https://www.youtube.com/watch?v=_kyv3tnQKfg)). I'd also add the [Next.js Link](https://nextjs.org/docs/api-reference/next/link) as a reference here.

**Comment by joshuatf** [comment]
Love all these ideas, @tomalec!  This is definitely something worth tackling.  I'll add it to our backlog.

**Comment by chihsuan** [comment]
Keeping this in the backlog. I think this can increase the team’s capacity to generate more impact in the future.

**Comment by AnnaMag** [comment]
@rrennick I think it is worth finding a home for this issue, which is worth looking into. Maybe Proton?

**Comment by rrennick** [comment]
@AnnaMag I added `team: TBD` earlier today. I'll update this issue.

**Comment by Manussakis** [comment]
I have started looking into this issue.

**Comment by Manussakis** [comment]
Hello @tomalec 👋

I looked into this issue from the accessibility point of view since it was labeled with the `focus:accessibility` label.

> I'd like to be able to use an accessible link button, without compromising UX.

I am not 100% aware of all the changes the WooCommerce Link component has undergone since this issue was created (2021), but after testing it, I realized it's possible to achieve what you need by simply adding the `components-button is-secondary` classes to the Link component:

```tsx
import { Link } from '@woocommerce/components';
import { getNewPath } from '@woocommerce/navigation';

<Link
  className="components-button is-secondary"
  href={ getNewPath( null, '/google/settings' ) }
>
    Edit
</Link>
```

With that in place, this is what the Link looks like:
![Image](https://github.com/user-attachments/assets/faf675e9-47ac-4b32-9a06-89d46f1013cd)

And this is how it's announced by screen readers:
![Image](https://github.com/user-attachments/assets/dcfc05ce-945c-4bac-b147-fd2aaf949342)

This also preserves the WC SPA feature.

While I agree that the proposed approaches to turn the Link into a more generic component are valid, I don't see this necessarily as an effort towards accessibility since it's already accessible.

Unless I missed something, I'd like to suggest removing the `focus:accessibility` label, so other developers can look into it.

Thanks!

**Comment by ralucaStan** [comment]
@tomalec you can see the new Link Woo component on this [Storybook](https://woocommerce.github.io/woocommerce/?path=/docs/woocommerce-admin-components-link--docs). 

I think it's in a place where it can be used, so I'm going to close this issue. If you consider the opposite feel free to share your findings on this ticket.

If you are still interested in improvements to the Button component from WordPress components then that request needs to happen on the Gutenberg repo https://github.com/WordPress/gutenberg
