### ISSUE TITLE
[Setup Wizard] - Currency isn't clear on Product Types

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#32230]
### Describe the bug
A number of prices are listed on the Product Types step.  They are all listed as a dollar amount, but it isn't clear what currency those are using.  Are they Canadian Dollars?  US Dollars?  Australia Dollars?  A number of countries use the dollar sign for their currency, but there's no indication on this page what the currency is.

I thought maybe the prices changed based on your country selection in Step 1 (if I select "Canada" I'll get one set of prices, whereas if I select "United States", I'll get a different set) but that doesn't appear to be the case

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=product-types
2. Note the prices displayed
3. (Optionally) toggle "Display monthly prices"

### Actual behavior:

Monthly (or yearly) prices are displayed in dollars.  There isn't any indication that prices listed are in (US|Canadian|Australian...) dollars.  Even clicking through to "Learn more" doesn't clarify which currency is being used for billing.

### Screenshots

![Screen Shot 2021-10-11 at 12 24 05 PM](https://user-images.githubusercontent.com/80276/136845178-b70e270e-bf2d-4e16-9bf8-d1614309c814.png)

![Screen Shot 2021-10-11 at 12 23 36 PM](https://user-images.githubusercontent.com/80276/136845126-74c616e9-02d1-4886-9fd2-f05b1db9bd86.png)

### Expected behavior

The simplest solution would be to add some test to the footer stating "Prices shown are billed in US dollars".  Optionally, it would be great if an estimated price in the local currency was shown (based on the selection in step 1).

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 94.0.4606.71

**Comment by louwie17** [comment]
We are making use of this query under the hood -> https://woocommerce.com/wp-json/wccom-extensions/1.0/search
Which does take a `?country=NL` option, but after trying a couple different countries I didn't see a price difference.

Even the checkout page on woocommerce.com isn't clear about the currency and only adds the specified taxes if the country has been changed: https://woocommerce.com/checkout/

<img width="453" alt="Screen Shot 2021-11-29 at 2 50 25 PM" src="https://user-images.githubusercontent.com/2240960/143925597-dc0e0b83-8982-4e12-901d-9e34ba710d22.png">

Adding "Prices shown are billed in US dollars" in the footer is a good suggestion, cc @pmcpinto what are your thoughts on this?

**Comment by joshuatf** [comment]
cc @pmcpinto as well as @elizaan36 for your thoughts on displaying the currency.

It would be great to get the respective prices on the WCCOM side of things, but it might be a bit of an overhaul if they don't have any currency support as @louwie17 noted above.

**Comment by pmcpinto** [comment]
> Adding "Prices shown are billed in US dollars" in the footer is a good suggestion, cc @pmcpinto what are your thoughts on this?

This is a good workaround for the moment. 

> It would be great to get the respective prices on the WCCOM side of things, but it might be a bit of an overhaul if they don't have any currency support as @louwie17 noted above.

This would be a great solution. The way how these extensions are promoted is going to be reviewed in the upcoming months. So it's better to wait until we have more clarity about this.

**Comment by elizaan36** [comment]
Thanks for bringing this up @lanej0! Agreed on the workaround for clarity in the interim.

Sounds like a WooCommerce.com issue that needs to be resolved, especially with the upcoming onboarding/essentials work. Is there someone we should flag this with for visibility, @mattyza ?

If paid products are shown in the onboarding it's going to be key to first present the correct currency based on what we know of the user, make it clear for the user which currency it is, and even potentially provide an option to change the currency (which would give us more info.)

cc @jarekmorawski

**Comment by jarekmorawski** [comment]
I found some research that suggests that presenting prices in customer's local currency by reduce checkout abandonment by up to 50%. It should be easier once WCCOM starts using WCPay and built-in multi-currency feature. When that happens, in addition to the currency switcher mentioned by Elizabeth above, we probably should display the exchange rate and FX fee, too.

**Comment by adrianduffell** [comment]
Closing this out as this is no longer displayed in the new setup wizard.
