### ISSUE TITLE
WooCommerce Payments task should be busy while installing

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#32233]
### Describe the bug
The WC Pay task installs WC Pay and redirects, but nothing seems to occur while this is happening.  A busy state should be placed on this task while we await install.

@elizaan36 do you have thoughts on the loading state for this task?  Disable the input and gray overlay on the entire task?

This issue may exist in the current task list, but we should address in the new REST API driven task list since that will take over.

See https://github.com/woocommerce/woocommerce-admin/pull/7616#discussion_r711301805 for more context.

Dev note:  We previously handled this by allowing `onClick`s from tasks to return Promises and resolving once they were complete.

```
setIsBusy( true );
Promise.resolve( taskOnClick ).then( () => setIsBusy( false ) );
```

### To Reproduce

1. Install WC Pay through business extensions in the onboarding profiler.
2. Make sure to set your store to a WC Pay supported country.
3. (preferably) enable the new `tasks` feature flag.
4. Click on the WC Pay task and not the delay without indication of busy state.

### Actual behavior:
Page sits until the install/activate/connect function completes.

### Screenshots

![Screen Shot 2021-09-21 at 9 59 28 AM](https://user-images.githubusercontent.com/10561050/134184656-390bf141-5bf7-4ee3-8008-1b70a6419c32.png)

### Expected behavior
Expected some indication of busy state.

**Comment by elizaan36** [comment]
> The WC Pay task installs WC Pay and redirects, but nothing seems to occur while this is happening. A busy state should be placed on this task while we await install. @elizaan36 do you have thoughts on the loading state for this task? Disable the input and gray overlay on the entire task?

I just tested it on a site that's already connected to Jetpack and it was about 8 seconds from clicking the task to bringing up the KYC. What are the processes happening in the background at this time? WCPay is already installed.

Would be best to indicate to the user what's happening so trying to understand what's actually causing the delay.

**Comment by joshuatf** [comment]
@elizaan36 It looks like no matter whether WC Pay is already installed and connected, it still walks through the entire flow:

1. Install
2. Activate
3. Connect

And because those are all separate synchronous (they have to be) requests, it can be a little slow if the server is not responding quickly.

I think there's some area to speed this up if the plugin is already installed/connected, but the original flow will still take roughly the same time.

**Comment by elizaan36** [comment]
Just chatted about this in Slack and maybe the best way forward would be, rather than creating a new pattern for a loading animation with the existing task list, use the action that's visible in the new task list UI (if the experiment is successful) to indicate all three steps, “Installing”/ “Activating” / “Connecting”.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/5121465/136094799-9d6b84a9-9958-4ded-889f-f81fa076b294.png">

**Comment by joshuatf** [comment]
@elizaan36 do we have a rough timeframe on when we will implement this experiment?  I'll keep this issue open for tracking until we add it.

**Comment by elizaan36** [comment]
The new task list experiment is going out with the next WC release so we'll have the results by the end of this month!

**Comment by joshuatf** [comment]
Removing `Needs triage`; this issue should remain open until the task list experiment is complete if we decide to keep it.  If we keep the old task list, this will still been to be fixed.

**Comment by elizaan36** [comment]
@verofasulo @rogermattic What do you think about a loading state on this task? Since there's a decent amount of time where the plugin goes through the process Joshua detailed above, we should let users know what's happening in some way.

**Comment by rrennick** [comment]
@adrianduffell This looks like it has probably been addressed. I'll close it but feel free to re-open and assign to a team if it still needs to be addressed.
