### ISSUE TITLE
Analytics: Orders report does not filter by attributes on simple products

### ISSUE THREAD

**Issue by okwasniewski** [woothemes/woocommerce#32237]
**Note: This bug only manifests itself when filtering by attributes on simple products. - @mattsherman** 

### Describe the bug
Our shop has multiple additional attributes, one of them is 'author' of the product. We want to filter by advanced filter in the Reports > Orders tab. When choosing specific attribute value for example: Attribute => Author = 'Author Name'. The list shows that there is no results, but clearly i've bought the product with same attribute as i filtered.   

### To Reproduce

1. Create attribute, in my case author.
2. Assign attribute to product, name it 'John Doe'
3. Buy the product
4. Mark the order as completed
5. Go to Reports > Orders
6. Change the date to from beginning of the year to today
7. Filter by advanced search
8. Choose attribute from the list 
9. Set to "is", and chose Author
10. Pick attribute value as "John Doe"
11. Click filter

### Actual behavior:
No results is shown. It shows empty list.

### Screenshots
**Before filtering by Advanced Filters**
<img width="1233" alt="Screen Shot 2021-09-02 at 11 29 09@2x" src="https://user-images.githubusercontent.com/52801365/131819744-17c93771-e46a-4bca-804a-ef124be1c458.png">
**After filtering by Advanced Filters**
<img width="1246" alt="Screen Shot 2021-09-02 at 11 29 17@2x" src="https://user-images.githubusercontent.com/52801365/131819815-ba4fd5a1-c688-4d00-9425-bc2da2812561.png">

### Expected behavior
It shows the list of orders with the provided attribute. 

### Desktop (please complete the following information):

* OS: MacOS 11.5.2 
* Browser Brave
* Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) (arm64)

**Comment by ilyasfoo** [comment]
Hi @okwasniewski, thank you for taking the time to report this. I was able to reproduce the bug with WooCommerce 5.6.0, WooCommerce Admin 2.6.1, and WordPress 5.8.

**Comment by louwie17** [comment]
Just to follow up on this, I did some more testing, and it does appear that the attributes filter only works for orders with variations, that required a certain attribute to be selected within the order.

Although I do think that filtering by any product with that attribute would be beneficial and a nice feature to have. I will label this as an enhancement.

**Comment by songsta** [comment]
Has there been any movement on this issue? I have the same need for it.

**Comment by ramzysa** [comment]
+1

**Comment by tszwed** [comment]
Also waiting for this - any news?

**Comment by AnnaMag** [comment]
@okwasniewski @tszwed @songsta 

hi 👋 witam 👋 
I could not reproduce the issue with the given instructions. Could you please re-test with the latest version of WooCommerce to check if the issues persist?
<img width="1327" alt="Screenshot 2023-03-15 at 23 32 49" src="https://user-images.githubusercontent.com/13561163/225459056-4f2fbba3-a8a8-43c1-9663-6b6912ecb598.png">

**Comment by tszwed** [comment]
Still have issue:
https://www.screencast.com/t/giboWTKt

**Comment by mattsherman** [comment]
I can reproduce this and am investigating a fix.

/cc @AnnaMag @louwie17

**Comment by rrennick** [comment]
Closing this as I'm not able to reproduce it.

**Comment by MichaelGillessen** [comment]
Hi @rrennick ,

I'm still experiencing this bug with WooCommerce 8.2.1 ;

https://snipboard.io/FYZAf6.jpg

Steps to reproduce the above screenshot: 
1. Create an attribute "Domaines"
2. Configure terms with a value "Caprai"
3. Create a simple product with the attribute "Capraï"
4. Create an order with at least this product
5. Change the status of this order as Completed
6. Launch page: Analytics > Orders
7. Create an advanced filter on attribute with "Domaines" is "Capraï"
8. Hit Filter button

**Current behaviour :** 0 orders retrieved

**Expected result :** 
Each and every orders, in the proper time range, which includes at least one product which has an attribute "Capraï", should be retrieved and displayed

**Comment by xue28** [comment]
Another issue here: https://wordpress.org/support/topic/cant-filter-out-by-attributes

**Comment by kamazeuci** [comment]
Having same problem. Hope this gets opened and solved. Thanks!

**Comment by AnnaMag** [comment]
cc @pmcpinto for visibility

**Comment by pmcpinto** [comment]
@louwie17 can we include this in the next engineering cycle?

**Comment by louwie17** [comment]
> @louwie17 can we include this in the next engineering cycle?

We can, we may have to move things around a bit.
