### ISSUE TITLE
Spike: Add i18n support to WooCommerce.com APIs

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#32242]
### Spike

We should dig into our recent P2 discussion (p90Yrv-2pn-p2) and come up with a plan for how we can add i18n support to the WooCommerce.com APIs. Right now, there is a lot of good info in the P2 discussion, but no concise plan of how to address the situation.

### Acceptance criteria

- [x] Look into whether WooCommerce.com already makes use of [GlotPress](https://translate.wordpress.com/glotpress/) for translations
- [x] An Epic breaking down what needs to be done to support i18n in the WooCommerce.com APIs
    - Work should be broken up into smaller chores/stories
    - Care and understanding of any compatibility issues
- [x] A P2 post/comment closing the loop on the initial discussion

**Comment by mattsherman** [comment]
Setting estimate to a 2 to timebox it to around two days of investigation and the creation of the stories and post.

**Comment by mattsherman** [comment]
This is still relevant.

**Comment by becdetat** [comment]
@mattsherman Should it have been included in Cycle 19's scope or can it be left unprioritised?

**Comment by mattsherman** [comment]
@becdetat It is okay to keep this unprioritized for now.

**Comment by mattsherman** [comment]
This is still relevant

**Comment by chihsuan** [comment]
> Look into whether WooCommerce.com already makes use of [GlotPress](https://translate.wordpress.com/glotpress/) for translations

Yes, but only a few strings are translated.

![Screen Shot 2022-07-06 at 11 14 50](https://user-images.githubusercontent.com/4344253/177460355-738c0abb-6756-4e80-a3f1-86215893e324.png)
https://translate.wordpress.com/projects/wccom/

However, I think we can use woocommerce language files since the text domain in remote APIs is `woocommerce`.

**Comment by chihsuan** [comment]
I've created an epic: 13783-gh-Automattic/woocommerce.com

**Comment by chihsuan** [comment]
Closing this - P2 post (pbIJXs-280-p2). we'll continue adding i18 support to WCCOM APIs internally since WCCOM is private.
