### ISSUE TITLE
WooCommerce 6.3.x: Some WC Blocks JS resources fail to load on Appearance > Widgets screen

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#32285]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With WooCommerce 6.3.x: Some WC Blocks JS resources fail to load on the Appearance > Widgets screen.

* wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-stock-indicator.js?ver=6.9.0
* wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-summary.js?ver=6.9.0
* wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-title.js?ver=6.9.0

* Happens on any theme with a registered widget area.

* Screenshot of the issue: https://d.pr/i/TGCiAj
* These files are not included in WC Core, but are getting included on Appearance > Widgets Screen somehow.
* Issue is fixed on downgrading WooCommerce to 6.2.2
* Issue is also fixed on installing the additional plugin - WooCommerce Blocks

Similar issues reported:

https://wordpress.org/support/topic/missing-js-files-5/
https://wordpress.org/support/topic/failed-2-no-such-file-or-directory/
https://wordpress.org/support/topic/missing-js-files-4/

### Expected behavior

* The JS files should not be included on the Appearance > Widgets screen or should be provided in the WC Core package if they are used somewhere.

### Actual behavior

* The missing JS files are getting included somewhere due to which the browser console is throwing 404 not found error for those files.

### Steps to reproduce

1. Install WooCommerce on a new WordPress site.
2. Install a theme that has sidebars, like Twenty-twenty-one or Storefront
3. Go to Appearance > Widgets
4. Check the browser console.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/1.1.1m

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wpfh_
Total Database Size: 4.75MB
Database Data Size: 3.33MB
Database Index Size: 1.42MB
wpfh_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpfh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_options: Data: 2.42MB + Index: 0.03MB + Engine InnoDB
wpfh_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfh_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpfh_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfh_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfh_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpfh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.3.1

### Inactive Plugins (37) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Avada Builder: by ThemeFusion – 3.4
Avada Core: by ThemeFusion – 5.4
Check & Log Email: by WPChill – 1.0.5
Classic Editor: by WordPress Contributors – 1.6.2
Follow-Up Emails: by WooCommerce – 4.9.18
Gravity Forms: by Gravity Forms – 2.5.16.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.7
Lottery for WooCommerce: by FantasticPlugins – 5.6
MOJO Marketplace: by Mike Hansen – 1.5.3
OptinMonster: by OptinMonster Team – 2.6.11
Storefront Powerpack: by WooCommerce – 1.6.1
Under Construction: by Noah Kagan – 1.19
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WooCommerce Bookings: by WooCommerce – 1.15.50
WooCommerce Bookings Availability: by WooCommerce – 1.1.19
WooCommerce Cart Add-Ons: by WooCommerce – 2.1.0
WooCommerce Conversion Tracking: by weDevs – 2.0.9
WooCommerce Conversion Tracking Pro: by weDevs – 1.0.7
WooCommerce Gift Cards: by WooCommerce – 1.10.0
WooCommerce Gravity Forms Product Add-Ons: by Element Stark – 3.3.26
WooCommerce Measurement Price Calculator: by SkyVerge – 3.20.1
WooCommerce Order Test: by WP Fix It – 1.6
WooCommerce Payments: by Automattic – 3.8.2
WooCommerce PayPal Payments: by WooCommerce – 1.7.0
WooCommerce Photography: by WooCommerce – 1.0.29
WooCommerce Product Add-ons: by WooCommerce – 4.7.0
WooCommerce Product Recommendations: by WooCommerce – 1.4.15
WooCommerce Product Search: by itthinx – 4.4.0
WooCommerce Square: by WooCommerce – 2.9.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.69
WP File Manager: by mndpsingh287 – 7.1.4
WPForms Lite: by WPForms – 1.7.3
WP phpMyAdmin: by Puvox.software – 5.1.19
WP Reset: by WebFactory Ltd – 1.95
WP Rollback: by GiveWP.com – 1.7.1

### Must Use Plugins (1) ###

Endurance Page Cache: by Mike Hansen – 2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2022-03-19 06:58:04 +0000
Newest: 2022-03-19 07:10:55 +0000

Pending: 1
Oldest: 2022-03-19 07:13:53 +0000
Newest: 2022-03-19 07:13:53 +0000

### Status report information ###

Generated at: 2022-03-19 07:13:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
@kaushikasomaiya  - Thanks for reporting.

According to Rubiks team, these errors while annoying does not affect the functionality. In addition, some fixes for this are already in place seen here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5989 So in 6.4, this should be a non issue.

With that, I will close this for now.

**Comment by corbolais** [comment]
Installing WC Blocks plugin provided the missing product-*js files.
