### ISSUE TITLE
Add end-to-end tests around bulk editing

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#32307]
We have had a few issues come in with bugs around bulk editing so we should look into adding tests around it.

**Comment by rodelgc** [comment]
When we say 'bulk editing', it could refer to:
- bulk editing of products
- bulk editing of variations

###  For bulk editing products

This is done by selecting "Bulk actions > Edit" in the "Bulk actions" menu.

<img width="400" alt="Screen Shot 2023-04-17 at 11 05 43 PM" src="https://user-images.githubusercontent.com/4509348/232527619-96538d4a-f109-4b52-aea8-59e5f7ee8e46.png">

We don't have any tests for these fields yet:

<img width="600" alt="Screen Shot 2023-04-17 at 11 19 04 PM" src="https://user-images.githubusercontent.com/4509348/232533476-f3483872-c265-4fea-b362-5408276ba336.png">

### For bulk editing variations

We already have the [`can bulk edit variations`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/create-variable-product.spec.js#L643) test, but it only tests the "Toggle Downloadable" bulk action. 

More tests should be done for the other, more common bulk actions like:
- Set regular prices
- Set sale prices
- Increase/decrease regular/sale prices
- Set scheduled sale dates
- Bulk actions within the "Inventory" section
- Would be great to have tests on the rest of the bulk actions too!

**Comment by veljkho** [comment]
These are existing relevant e2e tests:
- [merchant/product-edit.spec.js](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/product-edit.spec.js)
- [merchant/order-bulk-edit.spec.js](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/order-bulk-edit.spec.js)

As mentioned above, there are more bulk options to cover. We could cover them all, as shown in the screenshot.

**Comment by adimoldovan** [comment]
I think this is done.
