### ISSUE TITLE
Force download broken for distributed filesystem

### ISSUE THREAD

**Issue by ovidiul** [woothemes/woocommerce#32314]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Possibly related to https://github.com/woocommerce/woocommerce/issues/30288.

When we setup a WooCommerce Downloadable product, and the `File Download method` is set to `Force Downloads`, we get this error in the frontend

```
wp_die()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:650
WC_Download_Handler::download_error()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:456
WC_Download_Handler::download_file_force()
wp-includes/class-wp-hook.php:307
do_action('woocommerce_download_file_force')
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:234
WC_Download_Handler::download()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:131
WC_Download_Handler::download_product()
wp-includes/class-wp-hook.php:307
do_action('init')
wp-settings.php:587
```

On VIP, we have a distributed file system that usually gets prefixed with `vip://wp-content/uploads/file.txt`.

The filesystem has a special [wrapper](https://github.com/Automattic/vip-go-mu-plugins/tree/master/files) that knows how to handle when it finds a matching case prefix with `vip://`.

Upon debugging, we've found out the source of this issue might be this [code](https://github.com/woocommerce/woocommerce/blob/da241f6c70a551a2a8ba9f48fe37c8c33924e23b/plugins/woocommerce/includes/class-wc-download-handler.php#L286-L290) where the `$file_path` is using `ABSPATH` to check for its existence, so that will always fail.

this is how the `wp_upload_dir()` response would look like:
```
wp> wp_upload_dir()
array(6) {
  'path' =>
  string(32) "vip://wp-content/uploads/2022/03"
  'url' =>
  string(64) "https://test-develop.go-vip.co/wp-content/uploads/2022/03"
  'subdir' =>
  string(8) "/2022/03"
  'basedir' =>
  string(24) "vip://wp-content/uploads"
  'baseurl' =>
  string(56) "https://test-develop.go-vip.co/wp-content/uploads"
  'error' =>
  bool(false)
}
```

### Expected behavior

I would expect, that when the `wp_upload_dir` points to a distributed file system, prefixed in our case with `vip://` for the download to work

### Actual behavior

The error received is

```
wp_die()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:650
WC_Download_Handler::download_error()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:456
WC_Download_Handler::download_file_force()
wp-includes/class-wp-hook.php:307
do_action('woocommerce_download_file_force')
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:234
WC_Download_Handler::download()
wp-content/plugins/woocommerce/includes/class-wc-download-handler.php:131
WC_Download_Handler::download_product()
wp-includes/class-wp-hook.php:307
do_action('init')
wp-settings.php:587
```

### Steps to reproduce

1. Create a downloadable product within WooCommerce
2. Change the filesystem wrapper to point to a distributed filesystem, VIP uses this wrapper to make it work https://github.com/Automattic/vip-go-mu-plugins/tree/master/files
3. Order the product and try to download it from the frontend
4. Adding this extra [check](https://github.com/woocommerce/woocommerce/blob/da241f6c70a551a2a8ba9f48fe37c8c33924e23b/plugins/woocommerce/includes/class-wc-download-handler.php#L290) seems to help, but not sure if its the right way, happy to submit a PR if this can be considered:

```
if ( file_exists( $file_path ) ) {
			$remote_file = false;
			$file_path   = $file_path;

		}
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): ******
Site address (URL): ******
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
So we don't limit schemes for security reasons, basically to prevent local files from being incorrectly detected as remote files. We would be happy to accept PR with a filter on all `return` statements in that function though, that way you can customize based on the protocols you have.

**Comment by ovidiul** [comment]
@vedanshujain PR has been added here https://github.com/woocommerce/woocommerce/pull/32317 for further analysis.

Thanks for checking this. Ovidiu
