### ISSUE TITLE
Fix WCA lint commands (post WooCommerce Admin merge)

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32310]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Linting is failing because our packages have been moved to `./packages/js`:

```bash
pnpm nx lint woocommerce-admin

> nx run woocommerce-admin:lint
 WARN  Unsupported engine: wanted: {"node":">=12.20.1 <15"} (current: {"node":"v16.14.0","pnpm":"6.24.2"})

> @woocommerce/admin-library@3.4.0-dev lint /Users/chihsuan/Projects/woocommerce/plugins/woocommerce-admin
> pnpm run lint:js && pnpm run lint:css

 WARN  Unsupported engine: wanted: {"node":">=12.20.1 <15"} (current: {"node":"v16.14.0","pnpm":"6.24.2"})

> @woocommerce/admin-library@3.4.0-dev lint:js /Users/chihsuan/Projects/woocommerce/plugins/woocommerce-admin
> wp-scripts lint-js ./packages ./client --ext=js,ts,tsx


Oops! Something went wrong! :(

ESLint: 8.2.0

No files matching the pattern "./packages" were found.
Please check for typing mistakes in the pattern.

 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 1.

———————————————————————————————————————————————

>  NX   ERROR  Running target "woocommerce-admin:lint" failed

  Failed tasks:

  - woocommerce-admin:lint

  Hint: run the command with --verbose for more details.
```

### Expected behavior

Run `pnpm nx lint woocommerce-admin` without errors

### Actual behavior

Not able to run the lint command.

### Steps to reproduce

- Run `pnpm nx lint woocommerce-admin`

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Hi @ObliviousHarmony I have some questions about the linting setup.  Previously we only had [a lint command](https://github.com/woocommerce/woocommerce-admin/blob/main/package.json#L44) in the root package.json to check our js code. But it looks like in the monorepo, each package has its own "lint" command now in its `package.json`, such as [e2e-environment](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-environment/package.json#L76). 

Should we follow the same practices that add "lint" to our packages or use the previous way? 

I also created another relevant issue to [add JS lint/test Github action](https://github.com/woocommerce/woocommerce/issues/32311). 

cc @woocommerce/isotope

**Comment by rjchow** [comment]
I suspect there's a bunch of work to do in the tsconfigs too 💀

**Comment by ObliviousHarmony** [comment]
> Should we follow the same practices that add "lint" to our packages or use the previous way?

Ideally, every package and plugin should have a `lint` command that the executor runs. This allows us to run things like `pnpm nx affected lint` and have every package or plugin updated in a pull request execute linting. This will give us better performance in pull request checks as well as local development.
