### ISSUE TITLE
adjust_download_permissions row in database

### ISSUE THREAD

**Issue by tsetend** [woothemes/woocommerce#32316]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in 4877582-zen

Whenever the user updates a product (CSV or using the editor), it creates a row `adjust_download_permissions` on the database (even for non-downloadable products).

This brings a problem because they end up with a large database when editing in bulk.

This occurs when updating a variable product without any downloadable variation, but not with a simple product.

### Expected behavior

The `adjust_download_permissions` row in the database should be only added if the product is a downloadable product.

### Actual behavior

Duplicate and multiple `adjust_download_permissions` rows in the database.

### Steps to reproduce

1. Create a new product
2. Select "Variable product"
3. Add attributes
4. Create variations from all attributes

After creating variations I can see the 'adjust_download_permissions' row in the database.

Also after the product is published I can see another 'adjust_download_permissions' row in the database. And the same thing every time I update this product.

So this occurs even if I didn’t create a downloadable product first.

### WordPress Environment

Can reproduce with only WooCommerce + Storefront theme.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Noting that to fix, ideally, we should return early [in the function that we use to schedule action](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php#L40) if none of the variation has downloadable products.

**Comment by kevin25** [comment]
The same issue for me. I don't have any download products but it's there
