### ISSUE TITLE
Setup additional payment providers task - issue in the logic to display the task

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32330]
**Description:** there was a misunderstanding with the logic for the Setup additional payment providers task implemented in [#8391](https://github.com/woocommerce/woocommerce-admin/pull/8391). This task should only be displayed in countries where WCPay is available and after the WCPay setup is finished. Otherwise, it's just a duplication of the payments task, which is already visible: https://d.pr/i/QDcSes

**Comment by pmcpinto** [comment]
@octaedro @adrianduffell let me know if it's possible to fix this in time to be included in WC 6.4 RC (and WC Admin 3.3). Thanks

**Comment by adrianduffell** [comment]
@octaedro Thanks for your work on this one! Just checking @pmcpinto's message above , is this included in WC 6.4 via https://github.com/woocommerce/woocommerce-admin/pull/8506?

Is there a separate PR in the monorepo to include the change in WC 6.5?

**Comment by pmcpinto** [comment]
Let me know when this is merged and shipped in the RC, so I can test it again. Thanks!

**Comment by octaedro** [comment]
Hi @adrianduffell,

> is this included in WC 6.4 via https://github.com/woocommerce/woocommerce-admin/pull/8506?

Yes, the final release will include this PR.

> Is there a separate PR in the monorepo to include the change in WC 6.5?

Yes, [this PR](https://github.com/woocommerce/woocommerce/pull/32298) includes the fix.

**Comment by octaedro** [comment]
> Let me know when this is merged and shipped in the RC, so I can test it again. Thanks!

Hey @pmcpinto, I'll cut `3.3.0` final today, it will include the fix for this issue. I'll ping you in slack to let you know when that happens

**Comment by pmcpinto** [comment]
@adrianduffell @octaedro I've just tested 6.4 RC and it's not working as expected:

- When I start a new store with WC 6.4 RC and install WCPayments during the profiler I'm not seeing the WCPayments task and I'm  still seeing the additional payment methods task

<img width="1258" alt="Captura de ecrã 2022-03-30, às 11 32 40" src="https://user-images.githubusercontent.com/3380168/160812314-52a50c9e-f77e-4375-8d15-7e58d7bf2c87.png">

- When I install WC Admin 3.3 the additional payment methods task is hidden but I'm still not seeing the WCPayments task

<img width="1284" alt="Captura de ecrã 2022-03-30, às 11 35 53" src="https://user-images.githubusercontent.com/3380168/160812833-b00e1880-434b-4f46-926a-7c23fd4cbfdd.png">

We should always show the WCPayments task when the extension is installed. Let me know if you have questions

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm taking a look at [that task](https://github.com/woocommerce/woocommerce-admin/blob/release/3.3.0/src/Features/OnboardingTasks/Tasks/WooCommercePayments.php#L96-L101) and right now we only show the WC-Pay task (`Get paid with WooCommerce Payments`) when the following conditions are present:
- WC-Pay has been installed in the `Business Details` step during the OBW.
- The plugin is actually installed.
- The store is in a supported country ([this is the country list](https://github.com/woocommerce/woocommerce-admin/blob/release/3.3.0/src/Features/OnboardingTasks/Tasks/WooCommercePayments.php#L149-L159)).
- It's displayed in a single column or (in the case that it's displayed in two columns) it's connected.

Considering the comments you made, we should remove the first condition and show the task always when it's installed, correct?

**Comment by pmcpinto** [comment]
> Considering the comments you made, we should remove the first condition and show the task always when it's installed, correct?

I'll open a new issue about this, as we discussed in Slack
