### ISSUE TITLE
Missing JS Resources 

### ISSUE THREAD

**Issue by davevsdave** [woothemes/woocommerce#32344]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you enable the block editor for Products, the following resources are not found:
woocommerce/packages/woocommerce-blocks/build/product-title.js
woocommerce/packages/woocommerce-blocks/build/product-summary.js
woocommerce/packages/woocommerce-blocks/build/product-stock-indicator.js

According to this thread, https://wordpress.org/support/topic/missing-js-files-4/ - These files are not supposed to be called from woocommerce core, but are called and are not included in the core. Instead should only be called from the woocommerce blocks plugin.

### Expected behavior

When enabling the block editor for products, all resources/dependencies should be loaded.

### Actual behavior

When enabling the block editor for products, the following files are not found:

woocommerce/packages/woocommerce-blocks/build/product-title.js
woocommerce/packages/woocommerce-blocks/build/product-summary.js
woocommerce/packages/woocommerce-blocks/build/product-stock-indicator.js

### Steps to reproduce

1. Enable the block editor for product pages:
function wplook_activate_gutenberg_products($can_edit, $post_type){
    if($post_type == 'product'){
        $can_edit = true;
    }

    return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'wplook_activate_gutenberg_products', 10, 2);

2. Edit or create a new product page.
3. View console log in browser, see missing resources noted.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 7.2.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.1.1d
PHP Version: 7.4.28
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 6.99MB
Database Data Size: 4.87MB
Database Index Size: 2.12MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 0.42MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_as3cf_items: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cerber_sets: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_cerber_uss: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.22MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.34MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
younit_sign_up_verification: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 177
acf-field-group: 31
attachment: 36
nav_menu_item: 19
page: 15
post: 2
product: 38
product_variation: 9
revision: 67
wp_global_styles: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.12
All in One SEO: by All in One SEO Team – 4.1.8
WP Offload Media Lite: by Delicious Brains – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.5.6
Password Protected: by WPExperts – 2.5
WooCommerce UPS Shipping Plugin with Print Label: by PluginHive – 4.4.5
WooCommerce Blocks: by Automattic – 7.2.1
WooCommerce: by Automattic – 6.3.1
WordPress Importer: by wordpressdotorg – 0.7
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 8.9.6
WP Mail SMTP: by WPForms – 3.3.0
WP Super Cache: by Automattic – 1.7.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: 
Version: (update to version 0 is available)
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: younit-shop/woocommerce/emails/customer-new-account.php
younit-shop/woocommerce/myaccount/form-edit-account.php
younit-shop/woocommerce/myaccount/form-edit-address.php
younit-shop/woocommerce/myaccount/form-login.php
younit-shop/woocommerce/myaccount/form-lost-password.php
younit-shop/woocommerce/myaccount/form-reset-password.php
younit-shop/woocommerce/myaccount/lost-password-confirmation.php
younit-shop/woocommerce/myaccount/my-account.php
younit-shop/woocommerce/myaccount/my-address.php
younit-shop/woocommerce/myaccount/navigation.php
younit-shop/woocommerce/notices/error.php
younit-shop/woocommerce/notices/success.php

### Action Scheduler ###

Complete: 189
Oldest: 2022-03-09 11:42:39 -0800
Newest: 2022-03-24 08:20:20 -0700

Pending: 3
Oldest: 2022-03-24 08:35:20 -0700
Newest: 2022-03-25 07:47:23 -0700

### Status report information ###

Generated at: 2022-03-24 08:31:18 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Please ref https://github.com/woocommerce/woocommerce/issues/32285
