### ISSUE TITLE
Merge woocommerce admin e2e actions into existing workflows

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32355]
### Describe the solution you'd like

We should merge our e2e actions.

https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-build-and-e2e-tests.yml
https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/smoke-test-daily.yml

- [x] Add e2e test screenshots step (https://github.com/woocommerce/woocommerce/pull/32389)
- [x] Add homescreen tests
- [ ] Remove our woocommerce-admin [e2e.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/e2e.yml) & [daily-e2e.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/daily-e2e.yml)
- [ ] Remove E2E tests in the woocommerce-admin tests in the `plugins/woocommerce-admin` folder.

**Comment by louwie17** [comment]
@chihsuan could you clarify this issue a bit, do you mean we should take any overlapping steps from our [WooCommerce Admin github actions ](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/e2e.yml) and merge them with core current one's?

The only difference I am seeing currently is making the e2e test screenshots available as an artifact (which would be handy).

As outside of that most of our E2E tests are already being run against `trunk` within these Github actions, I think the only one that is currently missing are the homescreen tests which @octaedro might have a PR for soon.

**Comment by chihsuan** [comment]
> do you mean we should take any overlapping steps from our [WooCommerce Admin github actions ](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/e2e.yml)and merge them with core current one's?

@louwie17 Sorry I didn't know most of our E2E tests are already being run. I think we only need to add missing things to core's actions. 🙂  

So we only need to do three things:

- [x] Add e2e test screenshots step (https://github.com/woocommerce/woocommerce/pull/32389)
- [x] Add homescreen tests
- [ ] Remove our woocommerce-admin [e2e.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/e2e.yml) & [daily-e2e.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/daily-e2e.yml)

**Comment by louwie17** [comment]
@octaedro will be adding the homescreen E2E tests (I am pretty sure).

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/32355?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro

**Comment by chihsuan** [comment]
Close this since we've run our e2e tests in the core.
