### ISSUE TITLE
[COT] Implement migration for order notes from wp_comments into custom table

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32379]
Similar to other migrations, we would also like to implement migration from wp_comments to a dedicated order notes table.

Ideally, this migration will use the `MetaToCustomTableMigrator` class to provide functionality, linking the source table as wp_comments and then the wc_order_notes table as the destination table. Similarly, this should use the `MetaToMetaTableMigrator` class for the migration of metadata.

**Comment by peterfabian** [comment]
Perhaps outside of scope unless we decide differently.

**Comment by nicomollet** [comment]
@peterfabian @vedanshujain please reconsider this.

I understand the focus of High-performance Order Storage is performance, but still one of the huge benefits of decoupling tables is to allow easy migrations of data.
For example redesigns are now almost impossible with core WooCommerce.
After doing a redesign on a staging site, how to publish your new design to production without erasing the store (orders) data?

If store (order) data is completely outside of posts and postmeta tables, we can achieve that.

In the current state of WooCommerce, designers and store owners are discouraged by the lack of this possibility, I see it everyday. And many times they consider another system for their shop, like Shopify, BigCommerce which are growing fast.

Thank you.

**Comment by vedanshujain** [comment]
Hey @nicomollet , I assume you are talking about the requirement that we still write a placeholder post to the posts when creating an order and possible conflict of new post_ids in staging with order_ids in production. (Please correct me if that's wrong because rest of my comment is based on that).

We took this call of storing placeholder posts to not only provide additional compatibility with comments, tags, and other external systems but it also allows reverting to posts tables possible if merchants encounter issues with HPOS and need their site in a reliable state ASAP. 

Note that we are not storing any postmeta if sync is ~enabled~ disabled with placeholder posts, so a workaround I could suggest would be to when you begin a redesign, you can manually insert a post with id set to (LAST_INSERT_ID() + 10000) in production (but not in staging). This will provide space for adding new posts in staging that you can eventually migrate to production without any ID conflict.

**Comment by nicomollet** [comment]
Yes @vedanshujain I am talking about the placeholder post.
I do understand that it is needed to allow reverting to posts table, and it is absolutely legitime.

But since you `plan to stop synchronizing orders to posts and postmeta tables with WooCommerce 8.0 in August 2023`, this placeholders posts would not be needed anymore (except for order notes in wp_comments)?
That's why I am insisting on the order notes table, that could also be decoupled from posts.
Am I correct?

**Comment by vedanshujain** [comment]
Hey @nicomollet , I am closing this issue for now as won't fix as we will indeed be relying on the shop order placeholder post to link HPOS orders with order notes.

However, I am curious if this strategy works for developing in staging:

>you can manually insert a post with id set to (LAST_INSERT_ID() + 10000) in production (but not in staging). This will provide space for adding new posts in staging that you can eventually migrate to production without any ID conflict.

Is there a reason that this strategy does not, we do want to support the use case of developing in staging.
