### ISSUE TITLE
[Post merge]: Typescript check command for woocommerce-admin is broken

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#32374]
### Describe the solution you'd like

It seems to be littering the entire file tree with .d.ts files which should not be happening.

Haven't investigated further but it should be a configuration issue related to the includes/excludes

**Comment by rjchow** [comment]
The `.vscode/tasks.json` tasks for editor Typescript build needs to be updated and moved to the root as well

**Comment by chihsuan** [comment]
@rjchow Do we still have something to fix for this?

**Comment by rjchow** [comment]
Nope! Thanks I forgot to clean this up 😅
