### ISSUE TITLE
Page load tests may fail when extensions are installed

### ISSUE THREAD

**Issue by MrJnrman** [woothemes/woocommerce#32392]

**Comment by MrJnrman** [comment]
The Page load tests ensure that specific WooCommerce links are visible, click each one, and assert some content on the page that is loaded. This works fine on our PRs, but it may fail when a new menu item is added because the CSS selectors uses `nth:child()`.

The [elements.js](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-core-tests/src/specs/data/elements.js) file should be updated to use a better selector. A possible option could be `a[href=]`.

**Comment by tammullen** [comment]
Not applicable to latest Playwright tests https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/page-loads.spec.js
