### ISSUE TITLE
Deprecated Woo Admin classes don't have the core version number

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32410]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `@deprecated` tag on PHP classes does not use the core version number. Rather it uses version number for the feature plugin.

For example:

```
/**
 * WC_Admin_Note.
 *
 * @deprecated since 1.7.0, use Note
 */
class WC_Admin_Note extends DeprecatedClassFacade {
```

In this instance, 1.7.0 refers to the version of WooCommerce Admin feature plugin.

### Expected behavior

The `@deprecated` tag should contain the Core version number when the class was deprecated.

### Actual behavior

The `@deprecated` tag on PHP classes contains the Woo Admin feature plugin version number.

### Steps to reproduce

Search for `@deprecated` inside `plugins/woocommerce/src/Admin/` and see the wrong version number used.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
Hi @adrianduffell ✋ 

Are you still working on it? If not, I can take it as a porter.

**Comment by adrianduffell** [comment]
Hi @moon0326, thanks that would be great if you could take this one!

So far I've made a table of the versions.

| Core Version | Admin Package |
|---|---|
| 4.0.0 | 1.0.0 | 
| 4.1.0 | 1.1.1 | 
| 4.2.0 | 1.2.3 | 
| 4.3.0 | 1.3.0 | 
| 4.4.0 | 1.4.0 | 
| 4.5.0 | 1.5.0 | 
| 4.6.0 | 1.6.1 | 
| 4.7.0 | 1.6.3 | 
| 4.8.0 | 1.7.3 | 
| 4.9.0 | 1.8.3 | 
| 5.0.0 | 1.9.0 | 
| 5.1.0 | 2.0.2 | 
| 5.2.0 | 2.1.5 | 
| 5.3.0 | 2.2.6 | 
| 5.4.0 | 2.3.1 | 
| 5.5.0 | 2.4.1 | 
| 5.6.0 | 2.5.1 | 
| 5.7.0 | 2.6.4 | 
| 5.8.0 | 2.7.2 | 
| 5.9.0 | 2.8.0 | 
| 6.0.0 | 2.9.4 | 
| 6.1.0 | 3.0.3 | 
| 6.2.0 | 3.1.0 | 
| 6.3.0 | 3.2.1 | 
| 6.4.0 | 3.3.2 |
