### ISSUE TITLE
Store setup - Product page: Interactive walkthrough

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32421]
**User story:**
As a new merchant with no WooCommerce experience
I want to get some guidance on the product page
So I can quickly add my products 

**Description:**
We tested a new and more interactive walkthrough with some users ([user research recap here](https://woostartp2.wordpress.com/2022/03/25/add-and-import-products-user-testing-recap/) if you'd like to dive deeper), and the results were very positive. 

Main differences compared to the current design:

- The spotlight provides more focus on the specific action to perform.
- All the components are in focus state.
- The number of steps is always visible.
- The number of steps is reduced, and the product data popovers are tailored to each specific template.
- The next button is disabled till the action is completed.
- The page scrolls up and down automatically based on the information highlighted.
- The interactive walkthrough is always available and repeatable for users.

Now, we'd like to start implementing and testing this interactive walkthrough, at least for the physical product template. 

**Physical products**

https://user-images.githubusercontent.com/98944206/160862714-fd1aa0a6-0fcd-41d4-a267-2694271eb282.mov

**Current walkthrough**

https://user-images.githubusercontent.com/98944206/160853422-9bfb6759-6aff-46bd-97e8-164b6ac07883.mp4

**Design overview with new spotlight component:**
cJQeyyhx9PraQrY3YAtCGM-fi-1104%3A134672

**Acceptance criteria:**

- [x] New walkthrough available for users that select the physical product template
- [x] Enable the spotlight for each step
- [x] Enable the focus state to nudge the user to interact and take action
- [x] Replace the "Add product" button right close to the title "Edit product" with the "Enable guided mode" button.

**Event tracking:**  https://github.com/woocommerce/woocommerce/issues/33160
To be assessed by the team - some things I'd like to measure:

- [ ] % of users that clicks on "Enable interactive walkthrough"
- [ ] % of users that complete the guided mode without dismissing it
- [ ] % of users that clicks on "Skip guided mode"
- [ ] Which steps the user complete by adding information

**Comment by verofasulo** [comment]
Following up on the [new spotlight component initiative](https://ghidorahp2.wordpress.com/2022/04/13/shared-in-app-spotlight-component/), please implement the new spotlight that’s part of a larger design element used for help and guidance. 

Example: Step 1 - Add your product name

![image](https://user-images.githubusercontent.com/98944206/164714306-ff41e2cd-ede2-4856-b2de-98ef98544d6d.png)


**You can find the updated designs here:**
cJQeyyhx9PraQrY3YAtCGM-fi-1104%3A134672

**Comment by becdetat** [comment]
It may be worth reviewing pbIJXs-1NK-p2 (which explored some usability issues and confusion around the existing product management walkthrough) when implementing this feature.

**Comment by verofasulo** [comment]
@jarekmorawski I think it makes sense for you to take over this part as it's connected with the product management experience redesign 😄 What do you think?

**Comment by jarekmorawski** [comment]
Thanks for the ping! I agree and will take it from here. :) We'll likely need a completely different walkthrough for the new experience (but we'll still use the same design/components).

**Comment by adrianduffell** [comment]
@jarekmorawski Ghidorah have this lined up in the current sprint (updating the experience on the current products screen).

Would it be possible to paste into this issue the text of each step of the walkthrough?

**Comment by chihsuan** [comment]
> Ghidorah have this lined up in the current sprint (updating the experience on the current products screen).

> Would it be possible to paste into this issue the text of each step of the walkthrough?

Re-ping @jarekmorawski 🙏

**Comment by jarekmorawski** [comment]
Absolutely! Here are the steps.

**Point to:**
Product name input field

**Copy:**
> **Add your product name**
Start typing your new product name here. This will be what your customers will see in your store.

**Buttons:**
[Next]

---

**Point to:**
Description input field

**Copy:**
> **Add your product description**
Start typing your new product name here. Add your full product description here. Describe your product in detail.

**Buttons:**
[Back] [Next]

---

**Point to:**
Product data section

**Copy:**
> **Add your product data**
Use the tabs to switch between sections and insert product details. Start by adding your product price.

**Buttons:**
[Back] [Next]

---

**Point to:**
Short description input field

**Copy:**
> **Add your short product description**
Type a quick summary for your product here. This will appear on the product page right under the product name.

**Buttons:**
[Back] [Next]

---

**Point to:**
Product image section

**Copy:**
> **Add your product image**
Upload an image to your product here. Ideally a JPEG or PNG about 600 px wide or bigger. This image will be shown in your store’s catalog.

**Buttons:**
[Back] [Next]

---

**Point to:**
Tags section

**Copy:**
> **Add your product tags**
Add your product tags here. Tags are a method of labeling your products to make them easier for customers to find. For example, if you sell clothing, and you have a lot of cat prints, you could make a tag for “cat.”

**Buttons:**
[Back] [Next]

---

**Point to:**
Categories section

**Copy:**
> **Add your product categories**
Add your product categories here. Assign categories to your products to make them easier to browse through and find in your store.

**Buttons:**
[Back] [Next]

---

**Point to:**
Publish section

**Copy:**
> **Publish your product 🎉**
Good work! Now you can publish your product to your store by hitting the “Publish” button or keep editing it.

**Buttons:**
[Back] [Keep editing]

**Comment by chihsuan** [comment]
> Replace the "Add product" button right close to the title "Edit product" with the "Enable guided mode" button.

Hi @verofasulo 👋  Should we replace the button for all users or only for users that select the physical product template?

**Comment by chihsuan** [comment]
I've created a draft PR
- https://github.com/woocommerce/woocommerce/pull/33268

Just labeling this as blocked until we complete the following tasks:

- https://github.com/woocommerce/team-ghidorah/issues/33
- https://github.com/woocommerce/team-ghidorah/issues/34
