### ISSUE TITLE
Migrate Storybook

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#32434]
The `plugins/woocommerce-admin/storybook` directory needs to be migrated. I think a good place for it to live would be `plugins/woocommerce/storybook/admin`.

**Comment by psealock** [comment]
@ObliviousHarmony I'm not so sure this belongs in `plugins/woocommerce`. The current usage is exclusively `@woocommerce/components`, but I remember you had some ideas of composing entire UI's using storybook, is that right?  Another potential use case is [design systems](https://storybook.js.org/tutorials/design-systems-for-developers/), which is an extension of a component library.

To be agnostic, how about in `tools/`?
