### ISSUE TITLE
WooCommerce Permalink Conflicts With Really Simple SSL Plugin  

### ISSUE THREAD

**Issue by vaiyyy** [woothemes/woocommerce#32440]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have found this issue on working with one of my client's websites. Upon activation of this plugin (https://wordpress.org/plugins/really-simple-ssl/) and fixing the mixed content warning. I have found that It creates issues with the permalinks structure. 

This causes the product page to redirect the page at 404. 

### Expected behavior

expected behaviour of the plugin is to move urls http to https  only.  The 

### Actual behavior

Creating conflict with Woocommerce permalinks causing a 404 error on the Product Page. 

### Steps to reproduce

1. Install the plugin
2. Activate the plugin
3. Fix mixed content warning and move HTTP to HTTPS
4. check the product page.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://prehealthadmit.com
Site address (URL): http://prehealthadmit.com
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.81.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.37
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: VB0JEIr_
Total Database Size: 57.79MB
Database Data Size: 40.27MB
Database Index Size: 17.52MB
VB0JEIr_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VB0JEIr_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VB0JEIr_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
VB0JEIr_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
VB0JEIr_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
VB0JEIr_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
VB0JEIr_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_options: Data: 6.52MB + Index: 0.14MB + Engine InnoDB
VB0JEIr_pmxe_exports: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxe_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxe_templates: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_hash: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_pmxi_templates: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_postmeta: Data: 11.52MB + Index: 12.03MB + Engine InnoDB
VB0JEIr_posts: Data: 2.52MB + Index: 0.13MB + Engine InnoDB
VB0JEIr_relevanssi: Data: 0.23MB + Index: 0.38MB + Engine InnoDB
VB0JEIr_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_search_filter_cache: Data: 1.52MB + Index: 2.13MB + Engine InnoDB
VB0JEIr_search_filter_term_results: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
VB0JEIr_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_usermeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
VB0JEIr_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VB0JEIr_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VB0JEIr_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VB0JEIr_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
VB0JEIr_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VB0JEIr_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_wpr_rucss_resources: Data: 7.52MB + Index: 0.09MB + Engine InnoDB
VB0JEIr_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VB0JEIr_yoast_indexable: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
VB0JEIr_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
VB0JEIr_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VB0JEIr_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VB0JEIr_yoast_prominent_words: Data: 0.09MB + Index: 0.20MB + Engine InnoDB
VB0JEIr_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 178
acf-field-group: 2
ae_global_templates: 1
attachment: 54
custom_css: 1
customize_changeset: 10
elementor_library: 52
elementor_snippet: 1
nav_menu_item: 30
page: 36
paschool: 286
post: 8
product: 1
revision: 37
scheduled-action: 1
search-filter-widget: 3
shop_order: 22
wc_membership_plan: 1
wc_user_membership: 21

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Query Monitor: by John Blackbourn – 3.8.2
AnyWhere Elementor Pro (Premium): by WP Vibes – 2.24
ACF QuickEdit Fields: by Jörn Lund – 3.1.11
Actions Pack: by Wpfolk – 2.3.9
Advanced Custom Fields: by Delicious Brains – 5.12.1
Anywhere Elementor: by WPVibes – 1.2.5
Classic Editor: by WordPress Contributors – 1.6.2
Code Snippets: by Code Snippets Pro – 2.14.3
Admin Columns: by AdminColumns.com – 4.4.5
Custom Post Type Permalinks: by Toro_Unit – 3.4.5
Custom Post Type UI: by WebDevStudios – 1.11.2
Docket Cache: by Nawawi Jamili – 21.08.04
Dynamic.ooo - Dynamic Content for Elementor: by Dynamic.ooo – 2.4.5
Dynamic Visibility for Elementor: by Dynamic.ooo – 4.1.2
Ele Custom Skin: by Dudaster.com – 3.1.4
Elementor Pro: by Elementor.com – 3.6.4
Elementor: by Elementor.com – 3.6.1
Premium Addons for Elementor: by Leap13 – 4.9.4
Relevanssi: by Mikko Saari – 4.15.1
Remove Dashboard Access: by Drew Jaynes (DrewAPicture) – 1.1.3
Search & Filter - Elementor Extension: by Code Amp – 1.0.10
Search & Filter Pro: by Code Amp – 2.5.12
Send E-mails with Mandrill: by Miller Media ( Matt Miller ) – 1.2.13
Speed Booster Pack: by Optimocha – 4.4.1.1
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.5
WooCommerce Memberships: by SkyVerge – 1.22.11 (update to version 1.23.0 is available)
WooCommerce Payments: by Automattic – 3.9.0 (update to version 3.9.1 is available)
WooCommerce: by Automattic – 6.3.1
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO Premium: by Team Yoast – 18.2.1
Yoast SEO: by Team Yoast – 18.4.1
WP All Export Pro: by Soflyy – 1.7.4
WP All Import Pro: by Soflyy – 4.7.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.2.2
ElementsKit Lite: by Wpmet – 2.5.5
Really Simple SSL: by Really Simple Plugins – 5.3.0
S&F Pro Accordion: by Krishna Neupane – 1.0.0
WP Rocket: by WP Media – 3.10.9
WP Rocket | Disable Page Caching: by WP Rocket Support Team –
WP Rollback: by GiveWP.com – 1.7.1

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
maintenance.php: maintenance.php
object-cache.php: Docket Cache Drop-in

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #2805 - /shop/
Cart: #2806 - /cart/
Checkout: #2807 - /checkout/
My account: #2808 - /my-account/
Terms and conditions: #3868 - /terms-and-conditions/

### Theme ###

Name: Astra
Version: 3.7.6 (update to version 3.7.9 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 1
PA Toolkit Subscription:: Members: 21Access method: Product(s) purchaseAccess length: Specific length (1 years) No access-granting products are purchasable

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://prehealthadmit.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### WooCommerce Payments ###

Version: 3.9.0
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 1
Oldest: 2022-03-31 05:10:22 -0700
Newest: 2022-03-31 05:10:22 -0700

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

### Status report information ###

Generated at: 2022-03-31 06:25:27 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @vaiyyy,

Thanks for the report. Can you confirm, are there still problems with the product permalinks after disabling the Really Simple SSL plugin? If so, would you be able to provide steps to reproduce the issue that do not involve that plugin?

**Comment by vaiyyy** [comment]
Hi, No it’s doesn’t have the issue once I uninstall/deactivate the plugin.
Looks like the plugin fixes the issues. I don’t know weather it’s a
WooCommerce issue or Really Simple SSL. But, that’s a high demanding plugin
for starter. I think compatibility with that is necessary.

**Comment by vedanshujain** [comment]
hey @vaiyyy , can you share some details with us? for example, a screenshot of woocommerce permalinks setting page (which is usually at `wp-admin/options-permalink.php`) and settings in the SSL plugin as well. This will help us in reproducing the issue as this error can happen for so many reasons which may or may not be bugs (maybe some setting is misconfigured).
