### ISSUE TITLE
Setup experiment: Tracks

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#32442]
We should go through Epic: Increase setup tasks completion - task list / home https://github.com/woocommerce/woocommerce/issues/32155 and make sure we have Tracks events in place to measure the usage of these changes.

Some specific needs (there may be more):
- [ ] Track for progressive header "Hide setup list"
- [ ] Track when completing the task list (may be in place already, please confirm)
- [ ] Track when segmented list is collapsed/expanded
      - Include boolean when all sections are collapsed

**Comment by louwie17** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/32442?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @octaedro

**Comment by louwie17** [comment]
@pmcpinto in terms of tracks for the expanded/collapsed sections, do you have a preference for id's to use, or will any id work? 
In the current open PR I am using `basics`, `sales`, and `expand` as id's for the three sections.

**Comment by pmcpinto** [comment]
👍 these IDs are fine.
