### ISSUE TITLE
WCPayments task: change the display logic

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32451]
**Description:** Currently, we only show the WCPay task (Get paid with WooCommerce Payments) when the following conditions are present:

- WCPay has been installed in the Business Details step during the OBW.
- The plugin is actually installed.
- The store is in a supported country
- It's displayed in a single column or (in the case that it's displayed in two columns) it's connected.

We should update the logic so that the WCPay task is displayed independently if the extension was installed in the Business details. But also make sure that we don't re-enable the task list if the extension is installed by an existing store, as this would overwhelm users. 
Perhaps we can remove the first condition but add a new one to only display the task if the task list is enabled.

**Comment by adrianduffell** [comment]
> We should update the logic so that the WCPay task is displayed independently if the extension was installed in the Business details

> Perhaps we can remove the first condition but add a new one to only display the task if the task list is enabled.

@pmcpinto Do you mean we should display the task regardless of how it's installed? If so, I think (like you say) that would just require removing this condition: `WCPay has been installed in the Business Details step during the OBW.`

> But also make sure that we don't re-enable the task list if the extension is installed by an existing store, as this would overwhelm users.

Got it, so potentially a store that's finished the task list, could later install WC Pay for the first time, and in this scenario it would not be ideal to re-display the task list just to show the "Get paid with WooCommerce Payments" task.

I understand we have an option `woocommerce_task_list_complete`, which might be helpful for this.

**Comment by pmcpinto** [comment]
> @pmcpinto Do you mean we should display the task regardless of how it's installed? If so, I think (like you say) that would just require removing this condition: WCPay has been installed in the Business Details step during the OBW.

Correct.

> Got it, so potentially a store that's finished the task list, could later install WC Pay for the first time, and in this scenario it would not be ideal to re-display the task list just to show the "Get paid with WooCommerce Payments" task.

Yes. Re-displaying the task list would be suboptimal.
