### ISSUE TITLE
Document Woo Admin’s webpack config

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32466]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Woo Admin's [webpack config](https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/plugins/woocommerce-admin/webpack.config.js) contains custom plugins that are difficult to maintain and understand.

For example, one of the custom plugins [unminifies the webpack output](https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/plugins/woocommerce-admin/unminify.js) by hooking into internal webpack processes. It is not clear what the original intent of using this plugin is, nor how to maintain it when webpack's internal processes change.

This issue is to document the webpack config, particularly the use of custom plugins. As part of this we might also wish to remove some of these custom plugins, once there is a better understanding of them. 

I think this documentation could be placed in the repo wiki but welcome any other suggestions.

**Comment by adrianduffell** [comment]
> one of the custom plugins [unminifies the webpack output](https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/plugins/woocommerce-admin/unminify.js) by hooking into internal webpack processes. It is not clear what the original intent of using this plugin is

Unminification is possibly related to translations. It was mentioned in the comment https://github.com/woocommerce/woocommerce/issues/32485#issuecomment-1093384417.

**Comment by chihsuan** [comment]
> I think this documentation could be placed in the repo wiki but welcome any other suggestions.

Maybe we can just add comments in the webpack config? I think we don't have many things to document. And I'm afraid if we place the documentation in the repo wiki, someone would forget to update it when changes are made.

**Comment by adrianduffell** [comment]
> Maybe we can just add comments in the webpack config? 

Yeah that sounds perfect, good idea!
