### ISSUE TITLE
[Enhancement]: WC Admin - Free trial message

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32461]
### Describe the solution you'd like

This is part of an internal project that Start+Manage is working on. Please see the project thread (pbIJXs-1qN-p2) for additional context.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by adrianduffell** [comment]
Closing - a different project has now implemented extensibility points to support the free trial of [Woo Express](https://woocommerce.com/express/).
