### ISSUE TITLE
[Enhancement]: Set-up checklist: Extract help panel component into a general purpose content panel

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32479]
### Describe the solution you'd like

This is part of an internal project - see (pbIJXs-1r9-p2) for more context.

Extract the help panel component into a general purpose content panel.

The help panel itself should eventually use this general purpose content panel however that can wait if it isn't practical in this issue.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by adrianduffell** [comment]
Closing, as this is no longer a part of current plans.
