### ISSUE TITLE
PHP Fatal error WooCommerce admin

### ISSUE THREAD

**Issue by ifNoob** [woothemes/woocommerce#32476]
### Describe the bug
PHP Fatal error when adding an Object cache

### Actual behavior:
Fatal error: Uncaught Error: Cannot access offset of type string on string
in /Users/vbvmacpro/Local Sites/wppure/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 603

### Expected behavior
not an Array. Onboarding.php on line 603
Avoid the error after changing this code

if ( is_array($woocommerce_products) && isset($woocommerce_products['body'])) { 
  $product_data = json_decode( $woocommerce_products['body'] );
}

### WooCommerce system report
WordPress address (URL): http://wppure.local
Site address (URL): http://wppure.local
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###
Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by adrianduffell** [comment]
Hi @ifNoob , thanks for reporting this and apologies for our slow response. 

I believe this has since been fixed in the refactor of `Onboarding.php` that occurred prior to the merge of WC Admin. The specific line of code no longer exists. 

If it is still an issue for you, please re-open and we'll take another look.
