### ISSUE TITLE
Facing issue WooCommerce Admin Setup for dev

### ISSUE THREAD

**Issue by jignam** [woothemes/woocommerce#32478]
Hi There,

Thanks for preparing Git repository. We have cloned using git command. We have successfully got the files, then we have installed composer and pnpm. When are creating new extension as we want to develop custom report using this. When are creating new extension, we are facing error. Please refer this URL https://www.screencast.com/t/bXkUpBQb screenshot for the same. We are using this "npm run create-wc-extension" command to create new extension.

Please advise on above. If you have any steps for creating new extension for new reports, can you please share working steps guide for the same ? if you have any working example, please share with us.

Thanks in advance for your help & support.

Thank you,

**Comment by chihsuan** [comment]
@jignam Sorry, I think `npm run create-wc-extension` is broken. I was able to reproduce this. We'll fix it soon!

**Comment by jignam** [comment]
HI chihsuan

Thanks for the updates. Please keep us update once you resolve this issue, so we can continue with this once you reosolved.

Thank you
Jigna

**Comment by chihsuan** [comment]
Hi @jignam, we have fixed the command. You can clone the [`woocommerce`](https://github.com/woocommerce/woocommerce) repo (we have merged `woocommerce-admin` into core repo.) and use the following commands:

```
pnpm install
pnpm nx create-wc-extension woocommerce-admin
```

Let me know if you're still facing the issue. Thanks!
