### ISSUE TITLE
[Enhancement]: Set-up checklist: Contribute the general purpose content panel components to WP.com

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32483]
### Describe the solution you'd like

This is part of an internal project - see pbIJXs-1r9-p2 for more context.

- General purpose content panel component
- Checklist steps child component
- Checklist child single step component

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by adrianduffell** [comment]
Closing this issue because it is no longer planned.
