### ISSUE TITLE
Retire `wcAdminAssetUrl` 

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32491]
### Describe the solution you'd like

Since `woocommerce-admin` plugin images has been added to core, `wcAdminAssetUrl` can be retired.

As discussed [here](https://github.com/woocommerce/woocommerce/issues/32174#issuecomment-1088413516)

- [ ] post a developer advisory on the WooCommerce blog and check for any usage of the setting in the marketplace extensions and other plugins like WC Pay
- [ ] Remove `wcAdminAssetUrl` from loader.php and Settings.php.
- [ ] Define `WC_ASSET_URL` constant
- [ ] Use `wcAssetUrl` to replace `wcAdminAssetUrl` in frontend code

**Comment by moon0326** [comment]
I found out that `wcAdminAssetUrl` returns an incorrect value in the latest WC. It returns `http://your-domain/wp-content/plugins/woocommerce/src/Internal/images/`, which doesn't exist at all.

I think we should make the following changes before removing the function completely.

1. Fix the incorrect return value.
2. Deprecate [WC_ADMIN_IMAGES_FOLDER_URL](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php#L113) constant.
3. Deprecate [$settings['wcAdminAssetUrl']](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Settings.php#L183)
