### ISSUE TITLE
[Enhancement]: Add a filter in the checkout shortcode

### ISSUE THREAD

**Issue by pogla** [woothemes/woocommerce#32504]
### Describe the solution you'd like

We have a case where we do not want to display `cart-errors.php` on the checkout at all. So even if there are error notices, we would like the customer to see the normal checkout page (with error notices displayed).

Our site does not have an option for the customer to remove their coupon. So if the current coupon in the cart applies to items that are not in the cart, an error notice is added to the session. In this case, the user will not land on the checkout page but on the `cart-errors.php` template. This creates a lot of friction,

### Describe alternatives you've considered

The solution is pretty simple. I would like to get a new hook here:
https://github.com/UniversalYumsLLC/universalyums-com/blob/main/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php#L280

So instead of

`if ( empty( $_POST ) && wc_notice_count( 'error' ) > 0 ) {`

It should be:

`if ( empty( $_POST ) && wc_notice_count( 'error' ) > 0 && apply_filters( 'woocommerce_should_display_cart_errors', true ) ) {`

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help.

Our team is currently focused on the Cart and Checkout experience powered by blocks. We'll close the issue, as improving the shortcodes doesn't fit our current priorities. Please take a look at the [extensibility options](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility) available in the Cart and Checkout blocks and make a request in our [GitHub repository](https://github.com/woocommerce/woocommerce-blocks/issues/new/choose) in case you need a new extensibility point or component/utility.
