### ISSUE TITLE
Remove WCA deactivation hook usage

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#32522]
### Describe the solution you'd like

WooCommerce Admin has been merged to the core and there is no deactivation hook fired for WooCommerce Admin anymore. However, we have two places where we still depend on WCA deactivation.

We should consider using WC deactivation hook instead.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Composer/Package.php#L59

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Notes/OrderMilestones.php#L86

**Comment by adrianduffell** [comment]
Setting a critical priority to this to make it into 6.5. It is needed to ensure the previous Woo Admin uninstall routines occur when the plugin is uninstalled.
