### ISSUE TITLE
Use REST API to query orderCount and publishedProductCount

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#32524]
### Describe the solution you'd like

We're injecting `orderCount` and `publishedProductCount` via [woocommerce_admin_shared_settings](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Homescreen.php#L54) filter on the pages where we don't need the values. It is unoptimized and might cause performance issues.

We should use REST API to query the values to prevent potential performance issues.

### Tasks

- [ ] Set up Product data store, using API to populate:
    - https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
    - https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders
    - There are a lot of ways things can be filtered, we should be working on a general data store
 - [ ] Use data store to get `orderCount` and `publishedProductCount`

**Comment by moon0326** [comment]
Hey @mattsherman  ✋ 

I think this issue is a Manage issue. Could you take a look at it, please?

more details: p6JqRr-5HZ-p2#comment-13560

**Comment by mattsherman** [comment]
@moon0326 Thanks for putting this on my radar... Mothra will take a look at this.

**Comment by mattsherman** [comment]
See also: 13033-gh-Automattic/woocommerce.com
