### ISSUE TITLE
Add schema documentation for Admin's JSON endpoints

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#32532]
### Describe the solution you'd like

Some of WooCommerce plugin and WooCommerce.com [[1](https://woocommerce.com/wp-json/wccom/payment-gateway-suggestions/1.0/suggestions.json), [2](https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json), [3](https://woocommerce.com/wp-json/wccom/obw-free-extensions/3.0/extensions.json)] JSON endpoints are not documented. The risk of this is eventually it'll become harder to reason as time goes on.

So far the best way to document is to use [WordPress' JSON schema](https://href.li/?https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/). Some of our APIs already use this p90Yrv-2TX-p2#comment-7206.

P2 of our discussion: p90Yrv-2TX-p2

**Comment by moon0326** [comment]
Dev note: endpoints 1 and 3 return `is_visible` field in the response. The field is a set of Inbox Notification Rule. I'll exclude the field from the JSON schema as it's unrelated to the endpoint.

**Comment by moon0326** [comment]
I'm not sure if we want to document https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json endpoint with JSON Schema 🤔 Remote Inbox Notification has a good enough [README](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/RemoteInboxNotifications) IMO

**Comment by moon0326** [comment]
We also have https://woocommerce.com/wp-json/wccom/payment-gateway-suggestions/1.0/payment-method/suggestions.json and https://woocommerce.com/wp-json/wccom/payment-gateway-suggestions/1.0/payment-method/promotions.json endpoint

**Comment by ilyasfoo** [comment]
> Dev note: endpoints 1 and 3 return is_visible field in the response. The field is a set of Inbox Notification Rule. I'll exclude the field from the JSON schema as it's unrelated to the endpoint.

Fair point, but do we have something that's more generic to replace it? Like "Object" so it doesn't actually check the formats? And then in the description, we'll put a link to Inbox's rule readme or something.

>I'm not sure if we want to document https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json endpoint with JSON Schema 🤔 Remote Inbox Notification has a good enough [README](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/RemoteInboxNotifications) IMO

I can agree to skip that one as well.

Thanks again for working on this, @moon0326 !
