### ISSUE TITLE
The `auto-draft` status for orders is not recogized in some places in the code, causing the order status to present as the default `pending` instead

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#32539]
When submitting data to update an order through the API, and including `auto-draft` as the value of the `status` property, WC doesn't recognize `auto-draft` as a valid status _of the existing order_ and resolves it as `pending` instead. So then it interprets that the status is changing from "Pending" to "auto-draft" and creates an order note about it.

**To reproduce:**

1. Find the ID of an existing order
2. Using a client like Insomnia, `PUT` to the endpoint `wc/v3/orders/{order_id}` with this payload:
  ```
  {
	  "status": "auto-draft"
  }
  ```
3. The first time, this will change the order status to `auto-draft` if it isn't already, so this probably won't create a note.
4. Hit the endpoint again a couple more times with the same payload. Each time, a new order note should be created saying the status was changed from "Pending" to "auto-draft".

There are a couple of things that contribute to this. One is that `auto-draft` is not in [the canonical list](https://github.com/woocommerce/woocommerce/blob/f7937593e90739421e15ecf27e54c3d7d0bb24b5/plugins/woocommerce/includes/wc-order-functions.php#L86-L104) of valid order statuses. The other is [a place](https://github.com/woocommerce/woocommerce/blob/f7937593e90739421e15ecf27e54c3d7d0bb24b5/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L562) where a conditional checking for a valid status does not have a clause making `auto-draft` an exception (several other conditionals do have this exception, like [here](https://github.com/woocommerce/woocommerce/blob/f7937593e90739421e15ecf27e54c3d7d0bb24b5/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L557)).

The simplest way to fix this is probably to just add the exception to the conditional that's missing it. However, having to maintain exceptions in several different places in the code seems fragile, so I'm wondering if it would be feasible to instead add `auto-draft` to the canonical list and then make sure the code no longer assumes that every status has the `wc-` prefix.

Related: #31290

**Comment by joshbetz** [comment]
> The simplest way to fix this is probably to just add the exception to the conditional that's missing it. However, having to maintain exceptions in several different places in the code seems fragile

Is there a function that checks that something is a valid WC status? Or can we add one? My only concern with removing the `wc-` check is that it seems pretty easy to have collisions with other plugins.

**Comment by coreymckrill** [comment]
There's [`wc_is_order_status()`](https://github.com/woocommerce/woocommerce/blob/e9e382adf8509ae407c68cc5ebef378f29de8cdc/plugins/woocommerce/includes/wc-order-functions.php#L106-L115), although unfortunately it doesn't do any handling of the `wc-` prefix the way that [`wc_get_order_status_name()`](https://github.com/woocommerce/woocommerce/blob/e9e382adf8509ae407c68cc5ebef378f29de8cdc/plugins/woocommerce/includes/wc-order-functions.php#L137-L149) does.

I'm not entirely sure why there are some places like in the abstract wc order class that use a direct `in_array` check instead of that function.

> My only concern with removing the wc- check is that it seems pretty easy to have collisions with other plugins.

Yeah, I do think it's good to prefix the custom statuses that are registered by WC. Honestly I don't understand why WC strips the prefix off in some cases, just to add it back on later, but I'm sure there's context for it. It just complicates validating the status. Ideally the status validation function would be robust enough to take any string and try it both with and without the prefix to see if it's valid.

**Comment by coreymckrill** [comment]
If we're going to try adding `auto-draft` to the canonical status list, should we add `trash` also?
