### ISSUE TITLE
WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display

### ISSUE THREAD

**Issue by andrewbacon** [woothemes/woocommerce#32544]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display

No problems with any one or two plugins together. All three plugins active together breaks AVIA Builder elements.

**Comment by jonathansadowski** [comment]
Hi @andrewbacon,

Thanks for the report, but it appears you also filed this in #32545. I'm going to close this issue, as the other contains more detail.
