### ISSUE TITLE
Issue Description: WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display  No problems with any one or two plugins together. All three plugins active together breaks AVIA Builder elements.

### ISSUE THREAD

**Issue by andrewbacon** [woothemes/woocommerce#32545]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Issue Description:
WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display

No problems with any one or two plugins together. All three plugins active together breaks AVIA Builder elements.

### Expected behavior

I expected no problems.

### Actual behavior

Issue Description:
WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display

No problems with any one or two plugins together. All three plugins active together breaks AVIA Builder elements.

### Steps to reproduce

Issue Description:
WooCommerce Core + GiveWP Core + Events Calendar and Events Calendar PRO + Enfold theme (AVIA Builder) = AVIA Builder elements do not display

No problems with any one or two plugins together. All three plugins active together breaks AVIA Builder elements.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.foodisfreewashington.org
Site address (URL): https://staging.foodisfreewashington.org
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 92.00MB
Database Data Size: 61.67MB
Database Index Size: 30.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 20.05MB + Index: 17.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 9.02MB + Index: 8.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_redirects: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_aioseo_redirects_404_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_redirects_hits: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_redirects_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_give_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_comments: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_give_donormeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_give_donors: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_give_funds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_fund_form_relationship: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_log: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_give_logmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_revenue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_give_subscriptionmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_subscriptions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 10.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 3.02MB + Index: 0.50MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.03MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 0.95MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.25MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpgmza_datasets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_live_tracking_devices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps_has_custom_fields_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_markers_has_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_markers_has_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_markers_has_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 196
avia_framework_post: 10
give_forms: 13
give_payment: 248
give_pdf_template: 8
give-zapier-sub: 1
itsec-dash-card: 8
itsec-dashboard: 1
nav_menu_item: 32
page: 45
post: 15
product: 14
product_variation: 178
revision: 26
shop_order: 11
tribe_events: 46
tribe_organizer: 1
tribe_venue: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

The Events Calendar PRO: by The Events Calendar – 5.12.2
Give - Donation Plugin: by GiveWP – 2.19.8
The Events Calendar: by The Events Calendar – 5.14.1
WooCommerce: by Automattic – 6.3.1

### Inactive Plugins (33) ###

AIOSEO - Image SEO: by All in One SEO Team – 1.0.8
AIOSEO - Local Business: by All in One SEO Team – 1.2.5
AIOSEO - News Sitemap: by All in One SEO Team – 1.0.6
AIOSEO - Redirects: by All in One SEO Team – 1.1.8
AIOSEO - Video Sitemap: by All in One SEO Team – 1.1.2
Akismet Anti-Spam: by Automattic – 4.2.2
All in One SEO Pro: by All in One SEO Team – 4.1.10
Autoptimize: by Frank Goossens (futtta) – 2.9.5.1
Duplicate Page: by mndpsingh287 – 4.4.8
Facebook for WooCommerce: by Facebook – 2.6.12
Give - Annual Receipts: by GiveWP – 1.1.0
Give - Authorize.net Gateway: by GiveWP – 1.5.1
Give - Donation Upsells for WooCommerce: by GiveWP – 1.2.0
Give - Fee Recovery: by GiveWP – 1.9.7
Give - Form Field Manager: by GiveWP – 2.0.3
Give - Funds and Designations: by GiveWP – 1.1.0
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.5
Give - PDF Receipts: by GiveWP – 2.3.13
Give - Recurring Donations: by GiveWP – 1.15.0
Give - Tributes: by GiveWP – 1.5.9
Give - Zapier: by GiveWP – 1.4.0
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 8.8.15
iThemes Security Pro: by iThemes – 7.1.0
Jetpack: by Automattic – 10.8
MWB HubSpot for WooCommerce: by MakeWebBetter – 1.2.9
Nested Pages: by Kyle Phillips – 3.1.20
Printful Integration for WooCommerce: by Printful – 2.1.30
ShortPixel Image Optimizer: by ShortPixel – 4.22.9
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.6.1
WooCommerce Shipping & Tax: by WooCommerce – 1.25.25
WordPress Importer: by wordpressdotorg – 0.7
WP Engine Smart Plugin Manager: by WP Engine – 5.10.7
WP Mail SMTP Pro: by WPForms – 3.3.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.8
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #24 - /gift-shop/
Cart: #25 - /gift-shop/cart/
Checkout: #26 - /gift-shop/checkout/
My account: #27 - /my-account/
Terms and conditions: #378 - /terms-conditions/

### Theme ###

Name: Food is Free Washington
Version: 1.0
Author URL: https://northernpacificdigital.com/
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.9.2.1
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 34,749
Oldest: 2022-03-10 10:17:34 -0800
Newest: 2022-04-09 11:02:51 -0700

Pending: 7
Oldest: 2022-04-09 11:07:51 -0700
Newest: 2022-04-14 15:38:29 -0700

### Status report information ###

Generated at: 2022-04-09 11:06:38 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @andrewbacon,

Thanks for the report. Because it sounds like the issue lies in one (or more) of the plugins you listed, and those plugins are not developed by WooCommerce, we're unable to look into this issue, as we'll be unable to reproduce it.

If you're able to reproduce the issue with the plugins disabled, and with the default theme, please open a new issue. Otherwise, I recommend that you reach out to support for the plugin that causes the issue. To figure out which plugin causes the issue, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again with each plugin individually.

**Comment by eamankwah250** [comment]
Hello, I have a problem with the woocommerce plugin. Currently, my give WP forms are stuck constantly loading on my website. After troubleshooting, i found out the issue is the woocommerce plugin. If de-activated the givewp forms show. But i need both plugins to be activated as they are being used to run the ecommerce part of the site and the donations on the site. Any suggestions?
