### ISSUE TITLE
WooCommerce product importer parse categories issue during Cron

### ISSUE THREAD

**Issue by Johnny99211** [woothemes/woocommerce#32546]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since I need to develop an automatic product import from a sub-service, I've created a WordPress cron job. Within the function of the cron job, I'm using the WooCommerce product CSV importer:

```
$update_importer = WC_Product_CSV_Importer_Controller::get_importer( $import_result, [
	'delimiter'       => ',',
	'start_pos'       => 0,
	'mapping'         => $mapping_columns,
	'update_existing' => true,
	'lines'           => apply_filters( 'woocommerce_product_import_batch_size', 30 ),
	'parse'           => true
] );

$update_results          = $update_importer->import();
$update_percent_complete = $update_importer->get_percent_complete();
```

I was really wondering why everything worked instead of the product categories, so I've started digging into things. I've found out, that there is a function which parses the category names to the existing IDs or creates a new category in case there is no category:

`public function parse_categories_field( $value )`

Within the function there is a check which ruins all my functionality and work of weeks:
```
// Don't allow users without capabilities to create new categories.
if ( ! current_user_can( 'manage_product_terms' ) ) {
	break;
}
```

My question is now: Is it possible for you to exclude a running cron in this check to prevent this issue? Because a cron job will always be executed as logged-out user. At least I can set an admin user during this run, but this is more wacky than nice.

I would suggest something like:

```
// Don't allow users without capabilities to create new categories.
if ( ! wp_doing_cron() && ! current_user_can( 'manage_product_terms' ) ) {
	break;
}
```

Tested and works.

### Expected behavior

Categories are getting parsed also during cron execution.

### Actual behavior

Categories are not parsed because of the check.

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
hey @Johnny99211 , thanks for the report. perhaps we can add a filter here (or may be a more generic one to suppress checks).

**Comment by vedanshujain** [comment]
Closing for repo maintenance, it's a really old issue. But happy to reopen if there's still interest.
