### ISSUE TITLE
Order again item meta stores term value vs. Order item meta stores term slug

### ISSUE THREAD

**Issue by froger-me** [woothemes/woocommerce#32542]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There seems to be an inconsistency when saving order item meta between a normal order and an order placed after using the  "Order again" button:

* Upon placing an order #xxx for a variation with a taxonomy product attribute, the order item meta value stored in the database is the taxonomy product attribute term **slug**.
* Upon using the "Order again" button for order #xxx and placing the order #yyy, the order item meta value stored in the database is the taxonomy product attribute term **name**.

This seems to come from `WC_Cart_Session::populate_cart_from_order` on line 378:

```php
foreach ( $item->get_meta_data() as $meta ) {
	if ( taxonomy_is_product_attribute( $meta->key ) ) {
		$term                     = get_term_by( 'slug', $meta->value, $meta->key );
		$variations[ $meta->key ] = $term ? $term->name : $meta->value; // Line 378 - why assigning the name?
	} elseif ( meta_is_product_attribute( $meta->key, $meta->value, $product_id ) ) {
		$variations[ $meta->key ] = $meta->value;
	}
}
```

### Expected behavior

* Upon placing an order #xxx for a variation with a taxonomy product attribute, the order item meta value stored in the database is the taxonomy product attribute **term slug**.
* Upon using the "Order again" button for order #xxx and placing the order #yyy, the order item meta value stored in the database is the taxonomy product attribute **term slug**.

### Actual behavior

* Upon placing an order #xxx for a variation with a taxonomy product attribute, the order item meta value stored in the database is the taxonomy product attribute **term slug**.
* Upon using the "Order again" button for order #xxx and placing the order #yyy, the order item meta value stored in the database is the taxonomy product attribute **term name**.

### Steps to reproduce

For:
* a product attribute "Test Attribute" with `slug:value` tuples:
    *  `test1:TEST1`
    *  `test2:TEST2`
* a variable product "Test Product"
* a product variation "Test Variation" with attribute `test1:TEST1`
* a product variation "Test Variation" with attribute `test2:TEST2`

Follow the steps below from the `/shop` page:
* Click "Select options" for product "Test Product"
* Select "Test Attribute" > "TEST1"
* Click "Add to cart"
* Click "view cart" > "Proceed to checkout"
* Place the order #xxx with "Cash on delivery" payment method

Follow the steps below from the `/wp-admin/edit.php?post_type=shop_order` page:
* Ensure order #xxx  is "Processing"
* Edit the order #xxx status to "Completed"

Follow the steps below from the `/my-account/orders` page:
* Click "View" for order #xxx
* Click "Order again" button
* Click "view cart" > "Proceed to checkout"
* Place the order #yyy with "Cash on delivery" payment method

Follow the steps below from the `/wp-admin/edit.php?post_type=shop_order` page:
* Ensure order #yyy  is "Processing"
* Edit the order #yyy status to "Completed"

With phpMyAdmin or an RDBMS:
* Connect to the WordPress database
* Execute the following query:

```sql
SELECT * FROM `wp_woocommerce_order_itemmeta` WHERE `meta_value` LIKE '%test%'
```

* See the following result (ids have been edited out in the sample below):

meta_id | order_item_id | meta_key | meta_value
-------- | -------------- | ---------- | ------------
1 | xxx | 'pa_test-attribute' | 'test1'
2 | yyy | 'pa_test-attribute' | 'TEST1'

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://test.froger.me
Site address (URL): https://test.froger.me
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/1.1.1m

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 1.46MB
Database Data Size: 1.17MB
Database Index Size: 0.29MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.95MB + Index: 0.05MB + Engine MyISAM
wp_postmeta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_posts: Data: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_signups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1
page: 5
post: 1
product: 1
product_variation: 2
revision: 67
shop_coupon: 1
shop_order: 2
wp_stream_alerts: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Cloudflare: by Cloudflare
Inc. – 4.8.3

WooCommerce: by Automattic – 6.3.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CNY (¥)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #120 - /shop/
Cart: #121 - /cart/
Checkout: #122 - /checkout/
My account: #123 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 24
Oldest: 2022-04-09 18:28:55 +0800
Newest: 2022-04-09 18:45:14 +0800

### Status report information ###

Generated at: 2022-04-09 18:47:13 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by froger-me** [comment]
In the meantime, one can use a (somewhat inefficient) fix like below:

```php
if ( ! function_exists( 'my_custom_woocommerce_add_order_again_cart_item' ) ) {

	add_filter( 'woocommerce_order_again_cart_item_data', 'my_custom_woocommerce_order_again_cart_item_data', PHP_INT_MIN, 3 );
	function my_custom_woocommerce_order_again_cart_item_data( $cart_item_data, $item, $order ) {
		$cart_item_data['original_item'] = $item;
		return $cart_item_data;
	}

}

if ( ! function_exists( 'my_custom_woocommerce_add_order_again_cart_item' ) ) {

	add_filter( 'woocommerce_add_order_again_cart_item', 'my_custom_woocommerce_add_order_again_cart_item', PHP_INT_MIN, 2 );
	function my_custom_woocommerce_add_order_again_cart_item( $cart_item, $cart_id ) {

		foreach ( $cart_item['original_item']->get_meta_data() as $meta ) {
			if (
				taxonomy_is_product_attribute( $meta->key ) ||
				meta_is_product_attribute( $meta->key, $meta->value, $cart_item['product_id'] )
			) {
				$cart_item['variation'][ $meta->key ] = $meta->value;
			}
		}

		unset( $cart_item['original_item'] );
		return $cart_item;
	}

}
```

**Comment by vedanshujain** [comment]
Thanks for the detailed report, it looks likes this is a bug and we should be setting the `slug` instead of name. I am marking this low priority for now (as compared to other high priority bugs in the repo). Given the effort you have already put in, we would really appreciate it if you can send a PR to correct this.

**Comment by froger-me** [comment]
Hi @vedanshujain,

Pull request #34076 created.
