### ISSUE TITLE
[REST api] option fields in product default_attributes are always lowercase

### ISSUE THREAD

**Issue by synapticweb** [woothemes/woocommerce#32548]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The products REST api has a key named default_attributes that contains the default form values set in product variations on variable products. It is a list of maps that have the following keys: id, name, option. No matter the letter case of the attribute term names, the option key is always returned in lowercase.

### Expected behavior

The option key should contain the attribute term name as it was entered in the Attributes tab.

### Actual behavior

The option key always contains a lowercase version of the attribute term name.

### Steps to reproduce

1. Create 2 attributes with some terms, name one the terms "Term".
2. Create a variable product.
3. Attach attributes for variations.
4. Create variations.
5. Set default form values in Variations tab that contain the term named "Term".
6. Access with Insomnia or similar software the url https://hostname/wp-json/wc/v3/products/product_id
7. Under "default_attributes" key you will see that "Term" becomes "term".

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by synapticweb** [comment]
In product[default_attributes] the option keys are populated using the terms slugs instead of terms names, that's why they're always in lowercase.
I still think this is a bug.

**Comment by vedanshujain** [comment]
hey @synapticweb , thanks for the report. i think changing this to return names instead of slug would be a breaking change. we can perhaps another field `option_title` or `option_name` which can have the rendered name.

**Comment by johndcoy** [comment]
@vedanshujain 

I reported another problem with the REST API returning the slug or name within the name value based on if the slug contained Cyrillic characters. If you use one or the other, the result of the `name:` will be the name or the slug.

<img width="878" alt="Screenshot 2022-12-21 at 5 00 55 PM" src="https://user-images.githubusercontent.com/55294242/209019715-4ae04b42-5933-4b49-8a1e-58e601e62ca5.png">

https://github.com/woocommerce/woocommerce/issues/36138

I also found that if you edit the slug to from Latin letters back to Cyrillic letters, the slug remained the Latin characters although the attribute no longer contained that data from the front end.

**Comment by rpldom** [comment]
Any updates on this? Bug with Cyrillic letters makes WC Rest API unusable. This is high priority task and more than an year past with no fix. 

![изображение](https://github.com/woocommerce/woocommerce/assets/70687269/e2227258-9200-4cd2-9874-c1839011446e)

**Comment by coreymckrill** [comment]
Adding a new field for default attribute names is not planned at this time.
