### ISSUE TITLE
Improve performance of changelogger validation GH action

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#32566]
In #32525, we attempted to deepen the git history to the merge base so that we don't have to pull the entire git history to check the current PR against trunk. We observed some inconsistent behavior with the approach in that PR, so I created #32564 to update the fetch-depth to fetch the entire history of the repo so we could unblock anybody stuck by the issue fixed in both PRs.

Despite this, checking out the entire history does add some time to the process. We should consider revisiting #32525 to shave off some of the time taken by the full checkout approach.

**Comment by rrennick** [comment]
@jonathansadowski This one looks like it's safe to close as the changelogger has been moved to the `utils` command.
