### ISSUE TITLE
Wordpress Author level log in is redirecting to Homepage

### ISSUE THREAD

**Issue by kerrmcilwraith** [woothemes/woocommerce#32567]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When Author level users try to log in to our website, they are re-directed to the homepage (logged out) rather than the WP Dashboard.

### Expected behavior

Once logging in, the authors should go directly to the dashboard where they can edit their posts.

### Actual behavior

Once logging in, the authors are re-directed to the website homepage. Initially they were re-directed to the My Account page since I activated WooCommerce, but I disabled that, and now they are sent to the homepage.
The only way I can make it direct to the WP Dashboard is by disabling WooCommerce (I have tried turning off all other plug ins)

### Steps to reproduce

1. go to asianartinlondon.com/wp-admin
2. log in with these test details:
3. you will be re-directed

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.asianartinlondon.com
Site address (URL): https://www.asianartinlondon.com
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.27
PHP Post Max Size: 100 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.30 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 75.51MB
Database Data Size: 65.84MB
Database Index Size: 9.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.33MB + Index: 0.08MB + Engine InnoDB
wp_pantheon_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 27.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 14.52MB + Index: 1.22MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.25MB + Index: 0.20MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfblockediplog: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.41MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_entries: Data: 2.52MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_logs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 3.47MB + Index: 1.48MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.19MB + Index: 0.28MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_pantheon_heartbeat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_pt_heartbeat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4229
curated-by: 7
curated-by-2021: 7
customize_changeset: 80
event: 102
library_rows: 1
nav_menu_item: 69
oembed_cache: 34
online-participant: 8
page: 77
participant: 79
pick-of-the-museums: 23
post: 2
press: 159
product: 16
revision: 1975
service-provider: 5
tb_cf: 4
tbuilder_layout_part: 8
themify_popup: 3
wp_global_styles: 14
wpforms: 66

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Native PHP Sessions for WordPress: by Pantheon – 1.2.4
Builder Button Pro: by Themify – 2.0.4
Builder Timeline: by Themify – 2.0.2
Builder WooCommerce: by Themify – 2.1.0
PublishPress Capabilities: by PublishPress – 2.3.4
Site Kit by Google: by Google – 1.71.0
Pantheon Advanced Page Cache: by Pantheon – 1.0.0
Redirection: by John Godley – 5.2.3
Themify Builder Pro: by Themify – 2.2.8
Themify Event Post: by Themify – 1.2.2
Themify Popup: by Themify – 1.3.1
PTB Extra Fields: by Themify – 1.5.5
PTB Map View: by Themify – 1.2.7
PTB Search: by Themify – 1.4.0
Post Type Builder: by Themify – 1.7.4
Themify Updater: by Themify – 1.3.5
WooCommerce: by Automattic – 6.3.1
Wordfence Security: by Wordfence – 7.5.9
Yoast SEO: by Team Yoast – 18.5.1
WP Mail SMTP: by WPForms – 3.3.0
WP Migrate Lite: by Delicious Brains – 2.3.0
WPForms Mailchimp: by WPForms – 2.1.1
WPForms: by WPForms – 1.7.3

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Featured Image Custom Link Pro: by Mitali
Viitorcloud – 1.1.0

Hello Dolly: by Matt Mullenweg – 1.7.2
Themify - WooCommerce Product Filter: by Themify – 1.3.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.11

### Must Use Plugins (1) ###

Pantheon: by Pantheon – 0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8412 - /shop/
Basket: #8413 - /cart/
Checkout: #8414 - /checkout/
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Themify Parallax
Version: 5.6.3
Author URL: https://www.themify.me
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 266
Oldest: 2022-03-14 15:58:19 +0000
Newest: 2022-04-11 18:03:23 +0100

Failed: 10
Oldest: 2020-06-30 06:35:11 +0100
Newest: 2020-09-04 11:12:31 +0100

Pending: 5
Oldest: 2022-04-13 10:55:55 +0100
Newest: 2022-04-17 03:36:01 +0100

### Status report information ###

Generated at: 2022-04-11 18:16:47 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kerrmcilwraith** [comment]
Hi there. I have solved the problem. You have to allow the AUTHOR level user access to manage WooCommerce.

**Comment by jonathansadowski** [comment]
Hi @kerrmcilwraith,

Thanks for the follow-up. As you've figured out the issue you were running into, I'm going to close this issue. If you do have any issue that you believe is a bug, please open a new issue.
