### ISSUE TITLE
[Enhancement]: [woocommerce_checkout] Shortcode does not contain Phone Field. 

### ISSUE THREAD

**Issue by seanbelly** [woothemes/woocommerce#32563]
### Describe the solution you'd like

The block version of the checkout shortcode shows the phone number field in the shipping section, but the shortcode version doesn’t. 

You can see [in the code](https://github.com/woocommerce/woocommerce/blob/f7937593e90739421e15ecf27e54c3d7d0bb24b5/plugins/woocommerce/includes/class-wc-countries.php#L1577-L1599) this is done on purpose (i.e. hiding the e-mail and phone fields in the shipping section).

If this is done intentionally, great! If not, this is inconsistent and the shortcode and block versions should match. 

### Describe alternatives you've considered

Supplied a PHP snippet to the customer. 

`add_filter(
	'woocommerce_checkout_fields',
	function ( $fields ) {
		if ( ! empty( $fields['shipping'] ) && ! empty( $fields['billing']['billing_phone'] ) ) {
			$fields['shipping']['shipping_phone'] = $fields['billing']['billing_phone'];
		}

		return $fields;
	}
);`

**Comment by neilmccreadie** [comment]
It's also suggested for consistency that the Shipping Phone field be included in the MY ADDRESSES section of the  [woocommerce_my_account] shortcode.

**Comment by BrunoPoncePerez** [comment]
Good afternoon, I have a similar problem. Currently I have the phone field disabled and the mandatory option also, but even so, when the user places their data and sends the form I see the following problem: 
-Please enter a valid phone number. Only numbers. 
I have seen that there are similar problems with emails, but this is not the case. Can someone help me with the solution, please.

**Comment by ralucaStan** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply. While this is very helpful, it doesn’t fit our current priorities, as our team is currently focused on the Cart and Checkout experience powered by blocks. We'll revisit the list of suggestions like this one once our priorities are updated.
