### ISSUE TITLE
Store location: Welcome dialog

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32586]
**Description:**
Collecting the store location right at the beginning of the new user experience is critical, as payments, shipping, and taxes recommendations are tailored according to the store country. About 25% of new users skip the store profiler. Among them, less than 2% add the store location during the first 3 days of activity through settings or the shipping/tax tasks.
We assume it might be helpful to add the country selection to the welcome dialog highlighting the benefits for the user.  

![image](https://user-images.githubusercontent.com/98944206/162930620-7ea22207-2310-4b64-b9d1-549e75749298.png)

**Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-888%3A122274

**Acceptance Criteria:**

- [ ] Remove steps 2 and 3 from the current welcome dialog
- [ ] Tweak step 1 by changing illustration and copy and by adding the Country selection as showcased in the design.
- [ ] This dialog appears only if the user skipped the Profiler.

**Event tracking:**
To be assessed by the team

**Comment by ilyasfoo** [comment]
Hi @verofasulo, we're wondering if:
1. This issue is still applicable since the Profiler work
2. If so, is it applicable as-is, or will it need any copy/design update?

Thank you!

**Comment by verofasulo** [comment]
> Hi @verofasulo, we're wondering if:
This issue is still applicable since the Profiler work
 If so, is it applicable as-is, or will it need any copy/design update?

Hey @ilyasfoo, great point! Once the new onboarding is implemented, we don't need it anymore as the country selection is a mandatory field.

**Comment by ilyasfoo** [comment]
Great, thanks for confirming! Closing this issue now.

 cc @adrianduffell
