### ISSUE TITLE
Add tests for admin installation routine

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32584]
As a follow-up to PR https://github.com/woocommerce/woocommerce/pull/32513, this issue is to improve the amount of automated tests related to the admin install routine.

**Comment by moon0326** [comment]
FYI: I'm going to add more tests to this [PR](https://github.com/woocommerce/woocommerce/pull/32513) as the PR has all the install-related changes.

**Comment by moon0326** [comment]
Closing this as changes are added to https://github.com/woocommerce/woocommerce/pull/32513 and the MR has been merged
