### ISSUE TITLE
Save SEPA Direct Debit for future transfer

### ISSUE THREAD

**Issue by rupole1185** [woothemes/woocommerce#32590]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Error when saving SEPA DD on stripe using WOOCOMMERCE. 
Stripe replies that a "_Parameter missing: owner.addresss.country_”. 

I investigated a bit more and I found in Stripe documentation that:

`Creating a SEPA Direct Debit PaymentMethod requires that you include the customer's name and email address in the billing_details property of the payment_method parameter. Additionally, IBANs with the country codes AD, PF, TF, GI, GB, GG, VA, IM, JE, MC, NC, BL, PM, SM, CH, and WF require the country and line1 properties of the billing_details.address property`

I guess currently woocommerce is not doing so [for the sake of clarification my IBAN is a UK one]. 

I here link the stripe documentation: https://stripe.com/docs/payments/sepa-debit/accept-a-payment?platform=web

### Expected behavior

In the stripe request we have to add the "address" part nested inside the "owner" if country is one among AD, PF, TF, GI, GB, GG, VA, IM, JE, MC, NC, BL, PM, SM, CH, and WF.

{
  "type": "sepa_debit",
  "owner": {
    "name": "Name Surname",
    "email": "email@email.com",
    _**"address": {
      "country": GB
    }**_
  },
  "currency": "eur",
  "mandate": {
    "notification_method": "email"
  },
  "sepa_debit": {
    "iban": "GB********************"
  },
  "guid": "XX*******************",
  "muid": "XX*******************",
  "sid": "XX*******************",
  "payment_user_agent": "XX*******************",
  "time_on_page": "XX*******************",
  "key": "XX*******************"
}

### Actual behavior

Post request made without address

### Steps to reproduce

1. Attempt to save a GB IBAN as saved SEPA DIRECT DEBIT payment method using stripe plugin

### WordPress Environment

Woocommerce: Version 6.3.1
WordPress5.9.3

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @rupole1185,

Thanks for the issue. Can you please include the complete system status report in a reply to this message? You can get the system status report from **WooCommerce > System Status** in WordPress admin and then copy and paste it in reply to this message.

**Comment by rupole1185** [comment]
Hi there. Working with other people, I found the BUG I mentioned here is actually this one: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2312

It is a bug of the Stripe Gateway which is going to be fixed in that plugin.

You can close and sorry for the waste of time I might have caused.

**Comment by dougaitken** [comment]
Your details are very useful @rupole1185, thanks for adding them. 

I'll close this out and add details on https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2312
