### ISSUE TITLE
Error when requiring `feature-config.php` as it doesn't exist

### ISSUE THREAD

**Issue by jimjasson** [woothemes/woocommerce#32601]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

At this point: https://github.com/woocommerce/woocommerce/blob/d914efc8ba5e0bc8c6261b80c1a53f8c8cb70aad/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php#L77, the `/includes/react-admin/feature-config.php` file is required. 

However, this file doesn't exist at that location: https://github.com/woocommerce/woocommerce/tree/d914efc8ba5e0bc8c6261b80c1a53f8c8cb70aad/plugins/woocommerce/includes/react-admin.

This file used to exist when the `require_once` command was first added: https://github.com/woocommerce/woocommerce/tree/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/includes/react-admin but probably got deleted by another commit.

### Expected behavior

All required files should exist at the locations where they are expected to be.

### Actual behavior

Requiring files that don't exist triggers PHP errors.

### Steps to reproduce

Do not apply.

### WordPress Environment

Fresh WordPress install.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Hi @jimjasson `feature-config.php` will be dynamically generated when you run the command `pnpm nx build woocommerce`. The changes are made in [this PR](https://github.com/woocommerce/woocommerce/pull/32500).

I'm closing this. Let me know if you still find this an issue. Thanks!

**Comment by jimjasson** [comment]
Thanks @chihsuan for sharing some more insight on this! 

We were seeing these errors in our CI tool when we were running unit tests -- WooCommerce doesn't need to be built for unit tests to run. 

Looking at the PR you mentioned, we found that we could get the `feature-config.php` file by running `php bin/generate-feature-config.php`. 

Thanks for pointing us to the right direction!
