### ISSUE TITLE
[Enhancement]: Paginate enhanced product search results when over search threshhold

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#32607]
### Describe the solution you'd like

An enhanced product search, maps to the `WC_Ajax::json_search_products()` method and the results are ultimately limited by a threshold of 30, set here:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L1583

What I'd like to see is a UI for paginating to the next set of found matches if the results are more than the threshold.

### Describe alternatives you've considered

The threshold is filterable via `woocommerce_json_search_limit` but making that really high or unlimited could her performance issues.

### Additional context

Mix and Match Products plugin uses an enhanced search for store owners to pick the products they want to make available as part of a Mix and Match container. As store owners start to get a variable product with a lot of variations, or otherwise a lot of products with similar names

ex:
Fun Product - Red
Fun Product - Blue
Fun Product - Yellow
...etc

Once they have more products with that name than the threshold will return they won't be able to search for all their products. 

Another thought might be, to exclude currently selected products from the next search. So if you've selected the above Fun Product variations, the next time you search for "Fun Product" you won't see red, blue, or yellow. This might work as a workaround. 

Select2 (and therefore I assume SelectWoo) [supports pagination](https://select2.org/data-sources/ajax#pagination).

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
