### ISSUE TITLE
(6.4.0) WooCommerce Menu occasionally inaccessible for self-hosted sites

### ISSUE THREAD

**Issue by csmcneill** [woothemes/woocommerce#32609]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When updating to WooCommerce 6.4, some users on self-hosted sites are reporting issues where the WooCommerce menu is no longer visible or accessible.

### Expected behavior

The WooCommerce menu should be accessible.

### Actual behavior

The WooCommerce menu is sometimes inaccessible.

### Steps to reproduce

I have not been able to reproduce this issue locally, and neither have my peers.

Some users note that they are running newer versions of PHP (e.g. 8.1.4), but this has not resulted in successfully reproducing the issue.

This appears to (at least in some part) be related to a conflict with the menu order number: https://wordpress.org/support/topic/woocommerce-tab-missing-from-admin-bad-after-6-3-0-update/#post-15555723

Users have reported that modifying some lines of code have resolved the issue:

- https://wordpress.org/support/topic/woocommerce-menu-item-gone/page/2/#post-15554972
- https://wordpress.org/support/topic/woocommerce-is-no-longer-in-the-wordpress-menu-left-menu/#post-15555051

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by csmcneill** [comment]
4944517-zen

**Comment by csmcneill** [comment]
https://wordpress.org/support/topic/woocommerce-menu-item-gone/
https://wordpress.org/support/topic/woocommerce-tab-missing-from-admin-bad-after-6-3-0-update/
https://wordpress.org/support/topic/woocommerce-is-no-longer-in-the-wordpress-menu-left-menu/

**Comment by wpniall** [comment]
1208339-hc

**Comment by raifd** [comment]
4945439-zd-woothemes

**Comment by devappsteam** [comment]
Bug reproduced on 3 sites using the same settings.

### WordPress Environment ###

WordPress address (URL): https://myfamilycinemaplanos.com
Site address (URL): https://myfamilycinemaplanos.com
WC Version: 6.4.0
REST API Version: ✔ 6.4.0
WC Blocks Version: ✔ 7.2.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.1.1d
PHP Version: 7.4.27
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 15.90MB
Tamanho dos dados do banco de dados: 13.66MB
Tamanho do índice do banco de dado: 2.24MB
wp_woocommerce_sessions: Dados: 0.03MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_aioseo_notifications: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_aioseo_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_cli_cookie_scan: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cli_cookie_scan_categories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_cli_cookie_scan_cookies: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_cli_cookie_scan_url: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cli_scripts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_fusion_forms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_fusion_form_entries: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_fusion_form_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_fusion_form_submissions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_options: Dados: 5.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_pgly_pix: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_postmeta: Dados: 0.17MB + Índex: 0.09MB + mecanismo InnoDB
wp_posts: Dados: 6.45MB + Índex: 0.06MB + mecanismo InnoDB
wp_rsssl_csp_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_usermeta: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_fs_licensed_products: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_fs_product_licenses_keys: Dados: 0.48MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_fs_product_licenses_keys_generator_rules: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_fs_queue: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wpr_rucss_resources: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wpr_rucss_used_css: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wpsmtp_logs: Dados: 0.11MB + Índex: 0.00MB + mecanismo InnoDB
wp_yoast_indexable: Dados: 0.06MB + Índex: 0.09MB + mecanismo InnoDB
wp_yoast_indexable_hierarchy: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_yoast_migrations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yoast_primary_term: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_yoast_prominent_words: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_yoast_seo_links: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 42
cookielawinfo: 6
fusion_element: 3
nav_menu_item: 7
page: 11
post: 4
product: 18
revision: 121
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

License Manager: por  – 4.3.5
Editor clássico: por Colaboradores do WordPress – 1.6.2
GDPR Cookie Consent: por WebToffee – 2.1.1
Join.chat: por Creame – 4.4.2
Avada Builder: por ThemeFusion – 3.6.1
Avada Core: por ThemeFusion – 5.6.1
Pix por Piggly (para Woocommerce): por Piggly Lab – 2.0.26
Really Simple SSL pro: por Really Simple Plugins – 5.2.1
Really Simple SSL: por Really Simple Plugins – 5.3.1
WooCommerce Boleto e PIX PagHiper: por PagHiper Pagamentos – 2.1.5
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2
Mercado Pago payments for WooCommerce: por Mercado Pago – 5.7.5
Claudio Sanches - PagSeguro for WooCommerce: por Claudio Sanches – 2.14.0
WooCommerce: por Automattic – 6.4.0
Yoast SEO Premium: por Equipe Yoast – 18.0
Yoast SEO: por Equipe da Yoast – 18.5.1
WordPress Manutenção: por Filipe Seabra – 1.0.4
WP Rocket: por WP Media – 3.10.7
WP SMTP: por WPChill – 1.2.4
WPS Hide Login: por WPServeur
NicolasKulka
wpformation – 1.9.4

WPS Limit Login: por WPServeur
NicolasKulka
wpformation – 1.5.5

Yoast SEO: WooCommerce: por Time Yoast – 14.3

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #11 - /loja/
Carrinho: #12 - /carrinho/
Finalização de compra: #13 - /finalizar-compra/
Minha conta: #14 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: My Family Cinema
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.6.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Action Scheduler ###

Concluído: 18
Oldest: 2022-04-13 00:47:09 -0300
Newest: 2022-04-13 08:35:03 -0300


### Status report information ###

Generated at: 2022-04-13 14:31:46 -03:00

**Comment by devappsteam** [comment]
Performing some tests, I noticed that the failure only occurs when we use positions 55 and 56.
Test between ranges 26 and 54 all worked correctly.

**Comment by dlcallaway** [comment]
4945729-zen

**Comment by shaunkuschel** [comment]
4945553-zen

**Comment by csmcneill** [comment]
4944285-zen

**Comment by csmcneill** [comment]
35152379-hc

**Comment by csmcneill** [comment]
Confirmed with 35152379-hc that reverting to 6.3.1 resolved the issue.

File download: https://github.com/woocommerce/woocommerce/releases/download/6.3.1/woocommerce.zip

Documentation: https://woocommerce.com/document/installing-uninstalling-woocommerce/#reverting-to-a-previous-version-of-woocommerce

**Comment by jaxr** [comment]
4945154-zen

**Comment by ryanr14** [comment]
4946323-zen

This was the best place to put this issue, though this ticket is experiencing this issue with menus disappearing with their atomic site and only with Subscriptions 4.1.0 and WooCommerce 6.4.0 active.

**Comment by jnineb** [comment]
[34071878-hc](34071878-hc)

**Comment by thisissandip** [comment]
4946232-zen 

Atomic Site, the WooCommerce Setting disappeared.

**Comment by thisissandip** [comment]
35142201-hc | 4946990-zen

**Comment by zyousafi** [comment]
#4947306-zen

**Comment by imodouglas** [comment]
#4944437-zen

* WooCommerce > Home shows blank page
* Analytics menu shows blank page

**Comment by fredrikekelund** [comment]
#4947647-zen

Same problems as @imodouglas reports.
Possibly this is a separate bug, any maybe related to the fact that the `/packages/woocommerce-blocks/build/wc-settings.js` JS file returns a 404 error.

**Comment by rinazrina** [comment]
#4946963-zen 

Same issue as @imodouglas reports -- WooCommerce Home and Analytics show a blank page. 

This site doesn't have WooComerce Subscriptions. During plugin testing, I found that those pages are loading with all plugins deactivated and show blank pages when Jetpack is activated.

**Comment by gwensmithx** [comment]
35150771-hc / 4948352-zen

Sorry to open this back up but I just ran into this today. The Woo menu disappears on all Woo pages in the dashboard and stats are not visible. This is resolved when the WooCommerce Subscriptions plugin is deactivated.

**Comment by csmcneill** [comment]
With this particular issue, the `WooCommerce` option on the left-hand side of the menu is not visible at all for some users, almost like WooCommerce is not even installed/active.

Accessing the associated URLs directly (e.g. `http://example.site/wp-admin/edit.php?post_type=shop_order` instead of **WooCommerce > Orders**) is one way to bypass this.

There is a separate issue affecting sites hosted on WordPress.com and Pressable. When [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) is active, pages will become unavailable (e.g. **WooCommerce > Home** or **Analytics**) or the sidebar will disappear after accessing certain pages (e.g. **WooCommerce > Orders**). In these instances, the `WooCommerce` option on the sidebar is still visible.

This issue and [the associated PR](https://github.com/woocommerce/woocommerce/pull/32623) appear to be separate from the issue experienced by sites hosted on WordPress.com and Pressable while [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) is active. For sites experiencing an issue with pages not loading or the sidebar not appearing while [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) is active, there is a separate PR in a different repo. That can be accessed [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6260).

I've updated the title of this issue to reflect this discrepancy.

cc: @imodouglas @fredrikekelund @rinazrina @gwensmithx

**Comment by gwensmithx** [comment]
Thank you for that information @csmcneill!

**Comment by renataNavarro** [comment]
My Woocommerce asked for update the database and then appeared in the menu.

**Comment by wpniall** [comment]
35144083-hc

**Comment by jadolyo** [comment]
Found a fix:

in plugins/woocommerce/includes/admin/class-wc-admin-menus.php
line 64

Replace:
`add_menu_page( __( 'WooCommerce', 'woocommerce' ), __( 'WooCommerce', 'woocommerce' ), 'edit_others_shop_orders', 'woocommerce', null, $woocommerce_icon, 55 );`

By:
`add_menu_page( __( 'WooCommerce', 'woocommerce' ), __( 'WooCommerce', 'woocommerce' ), 'edit_others_shop_orders', 'woocommerce', null, $woocommerce_icon, 56 );`
