### ISSUE TITLE
Task List: Add Products Task - Import CSV

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32638]
**Description:** 

Implement the "import CSV" steps of import products task

Design overview:

cJQeyyhx9PraQrY3YAtCGM-fi-547%3A49811

Acceptance criteria:

 - Includes new icons and new copy.

**Screen shots**

<img width="1099" alt="Screen Shot 2022-04-21 at 8 44 55 am" src="https://user-images.githubusercontent.com/9312929/164349734-f9e58c69-c867-461a-8c4c-c5ae3da3c73e.png">
<img width="1099" alt="Screen Shot 2022-04-21 at 8 45 13 am" src="https://user-images.githubusercontent.com/9312929/164349740-ad329c24-ec00-4397-9c0b-4cb44194ae22.png">
<img width="1111" alt="Screen Shot 2022-04-21 at 8 45 31 am" src="https://user-images.githubusercontent.com/9312929/164349747-7ac83a0d-d58a-43b0-81a2-c6fb04bfdbfc.png">
<img width="1094" alt="Screen Shot 2022-04-21 at 8 45 42 am" src="https://user-images.githubusercontent.com/9312929/164349765-e3932e09-c3be-490d-8604-30c535a2af66.png">
<img width="1097" alt="Screen Shot 2022-04-21 at 8 46 16 am" src="https://user-images.githubusercontent.com/9312929/164349775-8e80ce36-5325-459c-a49c-08e680180def.png">
<img width="1099" alt="Screen Shot 2022-04-21 at 8 46 26 am" src="https://user-images.githubusercontent.com/9312929/164349784-f4810c4e-e5f1-451e-b41e-524b11e25531.png">
<img width="1097" alt="Screen Shot 2022-04-21 at 8 46 36 am" src="https://user-images.githubusercontent.com/9312929/164349788-07369984-8e0b-4be7-8279-0a325d468401.png">
<img width="1071" alt="Screen Shot 2022-04-21 at 8 47 05 am" src="https://user-images.githubusercontent.com/9312929/164349798-c401c96b-c48d-4e32-b422-e118fbdbb2e8.png">
<img width="1090" alt="Screen Shot 2022-04-21 at 8 47 21 am" src="https://user-images.githubusercontent.com/9312929/164349802-c63f2b8a-62c6-4062-a64c-f4a5bfcf33bf.png">

**Comment by adrianduffell** [comment]
These designs were exploratory, I'll close the issue for now.
