### ISSUE TITLE
Task List: Add Products Task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32636]
See: pbIJXs-1mj-p2

**Comment by masteradhoc** [comment]
@chihsuan for me the add products task is still there although i added a product. in my case i only have a woocommerce bookings product but the task doesnt close / not marked as completed. 

When i create a simple product it gets closed. Is this intended that woo bookings products get ignored?

**Comment by chihsuan** [comment]
@masteradhoc Thanks for reaching out! 

> for me the add products task is still there although i added a product. in my case i only have a woocommerce bookings product but the task doesnt close / not marked as completed.

I was able to reproduce this.

> When i create a simple product it gets closed. Is this intended that woo bookings products get ignored?

Good question. Yes, I think it's intended because [the booking product type is not natively supported by WooCommerce core](https://github.com/woocommerce/woocommerce/blob/99f8cd15b38c4d2122a2d0526d1cef5e10d79bce/plugins/woocommerce/includes/wc-product-functions.php#L596-L606).

However, it does confuse that the add products task is still active when you already have a product. I think we should update the completed logic to support the booking product type. @SamratBiswas1 @pmcpinto What do you think?

**Comment by chihsuan** [comment]
BTW, I forgot to close this issue. The task is already completed.
