### ISSUE TITLE
Page Break Attributes and Variations

### ISSUE THREAD

**Issue by julionalesso** [woothemes/woocommerce#32646]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm facing a problem with a page break in my Wordpress right in the Attributes and Variations tabs (a part appears off the screen making it impossible to edit the fields). Can you tell me how I can solve it?

### Expected behavior

perform product editing

### Actual behavior

Part of edit page is off screen

### Steps to reproduce

![Erro abas Atributos e variações](https://user-images.githubusercontent.com/103770254/163599738-068997af-c481-4f7d-8b58-d42779decaf0.JPG)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://seuproduto.com.br
Site address (URL): https://seuproduto.com.br
WC Version: 6.4.0
REST API Version: ✔ 6.4.0
WC Blocks Version: ✔ 7.2.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.26
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB-1:10.4.22+maria~stretch
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() malsucedido. Entre em contato com seu provedor de hospedagem.

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wpmaster_
Tamanho total do banco de dados: 27.33MB
Tamanho dos dados do banco de dados: 19.10MB
Tamanho do índice do banco de dado: 8.23MB
wpmaster_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wpmaster_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wpmaster_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_actionscheduler_actions: Dados: 1.30MB + Índex: 1.06MB + mecanismo InnoDB
wpmaster_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_actionscheduler_logs: Dados: 1.44MB + Índex: 0.56MB + mecanismo InnoDB
wpmaster_aiowps_debug_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_events: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_failed_logins: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_global_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_login_activity: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_login_lockdown: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_aiowps_permanent_block: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_cli_cookie_scan: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_cli_cookie_scan_categories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_cli_cookie_scan_cookies: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_cli_cookie_scan_url: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_cli_scripts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wpmaster_e_events: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_e_submissions: Dados: 0.02MB + Índex: 0.27MB + mecanismo InnoDB
wpmaster_e_submissions_actions_log: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wpmaster_e_submissions_values: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_fbv: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_fbv_attachment_folder: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_ff_scheduled_actions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_entry_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_form_analytics: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_logs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_submissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_fluentform_submission_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_gla_budget_recommendations: Dados: 0.22MB + Índex: 0.14MB + mecanismo InnoDB
wpmaster_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_gla_shipping_rates: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_jet_post_types: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_jet_taxonomies: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_litespeed_url: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_litespeed_url_file: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wpmaster_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_newsletter_templates: Dados: 2.06MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_mailpoet_scheduled_tasks: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_bounces: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wpmaster_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wpmaster_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_options: Dados: 4.02MB + Índex: 0.13MB + mecanismo InnoDB
wpmaster_postmeta: Dados: 5.19MB + Índex: 2.67MB + mecanismo InnoDB
wpmaster_posts: Dados: 2.16MB + Índex: 0.42MB + mecanismo InnoDB
wpmaster_rank_math_analytics_gsc: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wpmaster_rank_math_analytics_inspections: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wpmaster_rank_math_analytics_objects: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_rank_math_internal_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_rank_math_internal_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_termmeta: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_term_relationships: Dados: 0.05MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_tinvwl_analytics: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_tinvwl_items: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_tinvwl_lists: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_tm_taskmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_tm_tasks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_um_metadata: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_usermeta: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_user_registration_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_wc_admin_notes: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wpmaster_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wpmaster_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wc_product_attributes_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wc_product_meta_lookup: Dados: 0.11MB + Índex: 0.09MB + mecanismo InnoDB
wpmaster_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wpmaster_wpfm_backup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_wpum_fieldmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wpum_fields: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wpum_fieldsgroups: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wpum_registration_formmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wpmaster_wpum_registration_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wpmaster_wpum_search_fields: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 1026
cookielawinfo: 6
customize_changeset: 2
elementor_icons: 1
elementor_library: 8
jet-menu: 1
mailpoet_page: 1
nav_menu_item: 79
oembed_cache: 1
page: 18
post: 3
product: 50
product_variation: 419
revision: 113
seedprod: 1
shop_order: 1
shopengine-template: 2
um_directory: 1
um_form: 3
user_registration: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

FiboSearch - AJAX Search for WooCommerce: por FiboSearch Team – 1.17.0
Automatic Translate Addon For Loco Translate: por Cool Plugins – 2.2.3
Cloudflare: por Cloudflare
Inc. – 4.8.3

GDPR Cookie Consent: por WebToffee – 2.1.1
Crocoblock Wizard: por Crocoblock – 1.2.3
Dynamic Visibility for Elementor: por Dynamic.ooo – 4.1.2
Elementor Pro: por Elementor.com – 3.6.5
Elementor: por Elementor.com – 3.6.4
Essential Addons for Elementor - Pro: por WPDeveloper – 5.0.10
Essential Addons for Elementor: por WPDeveloper – 5.0.13
Google Listings and Ads: por WooCommerce – 1.12.5
JetBlocks For Elementor: por Crocoblock – 1.3.2
JetElements For Elementor: por Crocoblock – 2.6.4
JetMenu: por Crocoblock – 2.1.7
JetTabs For Elementor: por Crocoblock – 2.1.17
JetThemeCore Compatibility Kit: por Zemez – 1.1.0
JetThemeCore: por Crocoblock – 2.0.0
Kadence Starter Templates: por Kadence WP – 1.2.13
Kadence WooCommerce Email Designer: por Kadence WP – 1.4.10
Loco Translate: por Tim Whitlock – 2.6.1
Really Simple SSL: por Really Simple Plugins – 5.3.1
WooCommerce: por Automattic – 6.4.0
TI WooCommerce Wishlist: por TemplateInvaders – 1.42.1
Claudio Sanches - Correios for WooCommerce: por Claudio Sanches – 3.8.0
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2
Mercado Pago payments for WooCommerce: por Mercado Pago – 5.7.5
Ryviu - Product Reviews for WooCommerce: por Ryviu – 3.1.23
WP User Manager: por WP User Manager – 2.8.1

### Inactive Plugins (25) ###

All-in-One WP Migration: por ServMask – 7.58
All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.11

FileBird Lite: por Ninja Team – 4.9.8
Fluent Forms: por Contact Form - WPManageNinja LLC – 4.3.4
Integration with Mautic for WooCommerce - Open Source Marketing Automation: por MakeWebBetter – 2.2.3
JetEngine: por Crocoblock – 2.11.6
JetPlugins Dynamic Data Addon: por Crocoblock – 1.3.1
JetPopup: por Crocoblock – 1.5.6
JetReviews For Elementor: por Crocoblock – 2.2.4
JetSearch For Elementor: por Crocoblock – 2.1.16
JetSmartFilters: por Crocoblock – 2.3.11
JetTricks: por Crocoblock – 1.4.1
JetWooBuilder For Elementor: por Crocoblock – 1.12.2
JivoChat: por JivoChat – 1.3.5.3
LiteSpeed Cache: por LiteSpeed Technologies – 4.6
MailPoet 3 (New): por MailPoet – 3.87.1
Nginx Helper: por rtCamp – 2.2.2
Rank Math SEO: por Rank Math – 1.0.87
Redis Object Cache: por Till Krüss – 2.0.23
ShopEngine: por Wpmet – 2.2.1
Smart Manager For WooCommerce – Stock Management, Bulk Edit & more...: por StoreApps – 5.40.0
Upsell Order Bump Offer for WooCommerce: por WP Swings – 2.1.1
Variation Swatches for WooCommerce: por Emran Ahmed – 1.1.19
WP File Manager: por mndpsingh287 – 7.1.4
WP Mautic: por Mautic community – 2.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #1135 - /loja/
Carrinho: #1136 - /carrinho/
Finalização de compra: #9 - /finalizar-compra/
Minha conta: #1138 - /minha-conta/
Termos e condições: #2398 - /termos-de-uso/

### Theme ###

Name: Kadence
Version: 1.1.17
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Modelos TI WooCommerce Wishlist ###

Substituições: –

### Action Scheduler ###

Cancelado: 4
Oldest: 2022-03-15 19:51:32 -0300
Newest: 2022-03-16 16:44:57 -0300

Concluído: 2.939
Oldest: 2022-03-15 20:05:26 -0300
Newest: 2022-04-15 14:00:07 -0300

Malsucedido: 4
Oldest: 2022-04-01 23:58:28 -0300
Newest: 2022-04-01 23:58:30 -0300

Pendente: 2
Oldest: 2022-04-16 14:00:07 -0300
Newest: 2022-04-21 09:25:03 -0300

### Status report information ###

Generated at: 2022-04-15 14:07:34 -03:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @julionalesso,

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue. If you're still able to reproduce the issue with other plugins disabled, let us know so we can try to reproduce the issue.

**Comment by julionalesso** [comment]
Hello!

Won't changing the theme harm my site's settings?

Att

Outlook Mobile

Em 19 de abr. de 2022, à(s) 15:16, jonathansadowski ***@***.***> escreveu:

﻿

Hi @julionalesso<https://github.com/julionalesso>,

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront<https://en-gb.wordpress.org/themes/storefront/>. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue. If you're still able to reproduce the issue with other plugins disabled, let us know so we can try to reproduce the issue.
