### ISSUE TITLE
Standardize `lint` Scripts

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#32653]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In order to simplify the execution of linting tasks, we should enforce consistency in `lint` scripts. The goal of this issue is to review all of the `lint` scripts in the below `package.json` files. Each of them should be linting all of the code in the project, including both PHP and JavaScript. The goal is for running `pnpm run lint` on a package to automatically find, fix, and document any code style violations.

- [x] packages/js/admin-e2e-tests https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/api https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/api-core-tests https://github.com/woocommerce/woocommerce/pull/32794
- [x] packages/js/components https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/csv-export https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/currency https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/customer-effort-score https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/data https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/date https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/dependency-extraction-webpack-plugin https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/e2e-builds https://github.com/woocommerce/woocommerce/pull/32794
- [x] packages/js/e2e-core-tests https://github.com/woocommerce/woocommerce/pull/32794
- [x] packages/js/e2e-environment https://github.com/woocommerce/woocommerce/pull/32794
- [x] packages/js/e2e-utils https://github.com/woocommerce/woocommerce/pull/32794
- [x] packages/js/eslint-plugins https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/experimental https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/explat https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/js-tests https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/navigation https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/notices https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/number https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/onboarding https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/style-build https://github.com/woocommerce/woocommerce/pull/32793
- [x] packages/js/tracks https://github.com/woocommerce/woocommerce/pull/32793
- [x] plugins/woocommere https://github.com/woocommerce/woocommerce/pull/32795
- [x] plugins/woocommerce-admin https://github.com/woocommerce/woocommerce/pull/32795
- [x] plugins/woocommerce-beta-tester https://github.com/woocommerce/woocommerce/pull/32795

## NX or Turbo Executor

- [ ] Create an executor in NX or Turbo to allow running scripts at project root

**Comment by psealock** [comment]
After internal discussion, the path forward will be:

* `lint` to display errors and warnings
*  `lint:fix` to actually fix those.
