### ISSUE TITLE
Migrate From `nx` to `turbo`

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#32656]
**Description:**

Over the last few weeks, the changes made to our repository have given us a great opportunity to battle-test [Nx](https://nx.dev). When we began diving into better integration, however, we encountered a few blocking problems. Nx has strong opinions about a single-version policy, as well as mangles arguments passed from executors to scripts. While these issues could potentially be overcome, the work involved is non-trivial. As an alternative to that work, we examined a migration to [Turborepo](https://turborepo.org). It has very few opinions and gives a great deal of flexibility around how and when commands should be cached.

As a result, I have created a few issues to outline the migration:

- [x] https://github.com/woocommerce/woocommerce/issues/32652
- [x] https://github.com/woocommerce/woocommerce/issues/32653
- [x] https://github.com/woocommerce/woocommerce/issues/32654
- [x] https://github.com/woocommerce/woocommerce/issues/32655

**Comment by juristr** [comment]
Sad to see you go 😃. 

> Nx has strong opinions about a single-version policy

yeah we believe the single-version policy is beneficial and have it seen implemented successfully in large corporations. That said, that setup is the "full Nx with plugins" setup, which is more opinionated, comes also with more support (via plugins) etc.

But Nx can also be [setup without plugins](https://nx.dev/getting-started/nx-core). At which point it works with any structure, basically identically to Turbo or Lerna. Sad we could help with that earlier 🙂.

> as well as mangles arguments passed from executors to scripts

that's being fixed and should be out in one of the next releases. It has been bugging us too 😃

**Comment by ObliviousHarmony** [comment]
No worries @juristr, I appreciate you replying to this issue :) Although we've made the migration, I'll give some additional context around the internal discussions that led to this migration.

>  we believe the single-version policy is beneficial and have it seen implemented successfully in large corporations.

I see the benefits of a single-version policy, however, it isn't necessarily a great fit for our development practices. We would prefer to rely on a tool like [`syncpack`](https://www.npmjs.com/package/syncpack) so that we have control over what dependencies are synchronized and which ones aren't. This lets us keep very package-specific dependencies and developer dependencies out of the global space.

> But Nx can also be [setup without plugins](https://nx.dev/getting-started/nx-core). At which point it works with any structure, basically identically to Turbo or Lerna. Sad we could help with that earlier 🙂.

That was the approach we took with Nx in this repository. It's true that you can use Nx without plugins, but, it was clearly built with the intention that plugins _should_ be used. A lot of functionality is baked into the internal API and plugins end up being _very_ powerful. This is one thing I appreciate about Nx, however, the single-version policy excludes us from being able to use the provided plugins.

Given the option of moving to another tool or writing our own plugins, we chose the former.

> that's being fixed and should be out in one of the next releases. It has been bugging us too 😃

As a minor bit of feedback, [this issue has been open for over a year](https://github.com/nrwl/nx/issues/5710). After the initial request for a reproduction case, no maintainer ever replied to the issue again. It's hard to understand whether or not a maintainer sees a bug as a priority and whether it's going to be fixed if they don't tell anyone!

--

Once again, I appreciate you taking the time to reply here. Nx is an incredibly neat tool. I like that it's very language-agnostic and that the plugin system allows you to extend it while utilizing the internal API. It provides a level of extensibility that I don't think any other tool matches. I really like Nx but it ended up not being a great fit for this repository and our workflows.

If I could suggest anything specific to make the core-only use-case more viable, I would say that cache inputs need to be more opaque. Above all else, the fact that Turborepo allows you to configure what files result in a cache invalidation is super useful. I don't think any engineer likes magic!
