### ISSUE TITLE
Add/edit products: add new Tracks props

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32674]
**Description:** we want to add new props to the Add and Edit product Tracks events, to understand what fields are being used by users.

**Acceptance criteria:**
Include the following event props in the `wcadmin_product_add_publish` and `wcadmin_product_update` events
- [ ] description: Yes|No
- [ ] short_description: Yes|No
- [ ] product_image: Yes|No
- [ ] product_gallery: arrow with the number of images included [0,1,2…]
- [ ] categories: arrow with the number of categories included [0,1,2…]
- [ ] tags: arrow with the number of tags included [0,1,2…]
- [ ] sale_price: Yes|No
- [ ] weight: Yes|No
- [ ] dimensions: Yes|No
- [ ] upsells: Yes|No
- [ ] cross-sells: Yes|No
- [ ] attributes: arrow with the number of attributes included [0,1,2…]
- [ ] purchase_note: Yes|No
- [ ] menu_order: Yes|No
- [ ] enable_reviews: Yes|No

**Comment by pmcpinto** [comment]
@louwie17 @mattsherman another Tracks-related issue that should be included in the cycle 24 planning :)

**Comment by octaedro** [comment]
Hey @pmcpinto,

I'm working on this issue, and I wanted to confirm with you what is expected for this kind of prop:

- categories: arrow with the number of categories included [0,1,2…]

The expectation for that kind of prop is to send an `Int` with the total count of the product's categories, right?

Also, I noticed that we were sending more props when a product is published than when it's edited.
The props are: `product_type`, `is_downloadable`, `is_virtual`  and `manage_stock`.
If you think that adding those props when a product is edited would be something worthwhile I can do it easily now.

**Comment by octaedro** [comment]
Actually, I'm seeing that we're tracking the product update twice, once [on the client side](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L150) (named `wcadmin_product_update`) and another time [on the PHP side](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L119) (named `wcadmin_product_edit`). Is that expected?

**Comment by pmcpinto** [comment]
Hey @octaedro in the props where I mentioned the arrow probably it's better to keep it simple to just show the number of times an event was fired with 0,1,2.... categories/tags/etc. Similar to what we have for the products_count prop. Makes sense?

> Actually, I'm seeing that we're tracking the product update twice, once [on the client side](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L150) (named wcadmin_product_update) and another time [on the PHP side](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L119) (named wcadmin_product_edit). Is that expected?

Yes. `wcadmin_product_edit` was the original event but we thought that the numbers could be inflated by extensions that automate the edit process. So we then started using the `wcadmin_product_update` event. The new props should be included in `wcadmin_product_update`

**Comment by octaedro** [comment]
Thank you @pmcpinto for clarifying.

 >  probably it's better to keep it simple to just show the number of times an event was fired with 0,1,2.... categories/tags/etc. Similar to what we have for the products_count prop. Makes sense?

Right now the tracking event is triggered after the user clicks the `Publish`/`Update` button. If it's ok with you we can track the count of attributes/categories/tags/gallery images the product has. For instance, if the product has 1 attribute, 3 categories, 2 tags, and 5 images in the gallery, we will record (among the other props):
```
attributes: 1
categories: 3
tags: 2
product_gallery: 5
```
Would that cover what we need here?

**Comment by pmcpinto** [comment]
Yes. That's perfect
