### ISSUE TITLE
Add categories and tags: new Tracks events

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32676]
**Description:** we want to include Tracks events in the Categories, Tags and Attributes pages to learn more about how users interact with the features. 

**Acceptance criteria:**

- [ ] wcadmin_product_attributes_add
Description: fired when the user adds a new attribute
Event props:
page: attributes | product (identify if the attribute was created in the attributes page or within the add/edit product)
enable_archive: Yes|No
default_sort_order

- [ ] wcadmin_product_attributes_edit
Description: fired when the user adds a new attribute
Event props:
page: attributes | product (identify if the attribute was created in the attributes page or within the add/edit product)
enable_archive: Yes|No
default_sort_order

- [ ] wcadmin_product_attributes_configure_terms
Description: fired when the user clicks the “configure terms” option in the attributes list

- [ ] wcadmin_product_attributes_add_term
Description: fired when the user adds a new term

- [ ] wcadmin_product_tags_add
Description: fired when the user adds a new tags
Event props:
page: tags | product (identify if the tag was created in the tags page or within the add/edit product)

- [ ] wcadmin_product_category_add
Description: fired when the user adds a new category
Event props:
page: category | product (identify if the attribute was created in the category page or within the add/edit product)
parent_category: None|Uncategorized|Other
display_type: default|products|...
image: Yes|No

- [ ] wcadmin_product_category_manage
Description: fired when the user clicks on one of the manage options
Event props:
option_selected: edit| quick edit| delete...

- [ ] wcadmin_product_category_update
Description: fired when the user updates one of the categories

**Comment by pmcpinto** [comment]
@louwie17 @mattsherman last Tracks-related issue :) I understand that it may not be possible to add all events during cycle 24. Let me know how you prefer me to prioritize the issues. I can order them by priority in the Mothra Dev Sprint pipeline

**Comment by louwie17** [comment]
@pmcpinto for the `wcadmin_product_attributes_add` track on the product page, this means not creating a new attribute but just adding one to a specific product correct? Although the one within the attributes page actually creates a new attribute.

Also in terms of adding attributes on the product page. We have the add and remove buttons, but they are not saved until the user clicks `Save attributes`. Did we want to track this when the user just adds the attribute, and maybe a different one from when the user saves the attributes?

**Comment by pmcpinto** [comment]
> @pmcpinto for the wcadmin_product_attributes_add track on the product page, this means not creating a new attribute but just adding one to a specific product correct? Although the one within the attributes page actually creates a new attribute.

> @pmcpinto for the wcadmin_product_attributes_add track on the product page, this means not creating a new attribute but just adding one to a specific product correct? Although the one within the attributes page actually creates a new attribute.

Hey @louwie17 this event should be fired when the user creates a new attribute. On the product page it should be fired when the user hits save.

In the meantime, I included 3 additional events in the issue description targeting the category page. Let me know if you have any questions. Thanks
