### ISSUE TITLE
[COT] Implement the `create` function for the custom order table data store.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32670]
Similar to [`create` function in `Abstract_WC_Order_Data_Store_CPT` class](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php#L58) we would like to implement a `create` function for `OrdersTableDataStore` as well.

This issue scopes implementing this function along with unit tests.

**Comment by jorgeatorres** [comment]
Addressed by #33341.
