### ISSUE TITLE
Add a “Subscriptions” menu item to the primary “WooCommerce” menu

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#32682]
ℹ️ This issue relates to the "Experiment with subscriptions empty state in WooCommerce core" project, read more here → pdjTHR-Vi-p2

Pull requests related to this project will be targeted to a feature branch (`add/experiment-subscriptions-admin-menu`). A final pull request will be opened against `trunk` when all issues are completed and the feature branch is in a production-ready state.

---

A new “Subscriptions” child menu item is added to the primary “WooCommerce” menu in the WordPress dashboard.

**Acceptance criteria**

- A “Subscriptions” child menu item appears in the primary “WooCommerce” menu in the WordPress dashboard.
- A "beta" badge appears alongside the “Subscriptions” menu item.
- The menu item can link to a blank page for now. The page contents will be implemented in #32691.
- This menu item is positioned below the existing “Orders” menu item and above the existing “Customers” menu item.
- This menu item is only be added to stores that meet the following criteria:
  - The store meets the "installed plugins" criteria discussed here pdjTHR-WQ-p2 
  - The store does not have WooCommerce Payments installed.
  - The store address is USA (eligible for [WCPay Subscriptions](https://woocommerce.com/document/payments/subscriptions/)).
  - The store has:
    - Been live for 6+ months.
    - Had 1+ sale in last 30 days.

ExPlat "audience targeting" should be used to control which participants are eligible for this experiment based on the criteria above. We will likely need to use custom segments to programmatically filter for certain users. More info on this:
- PCYsg-FqJ-p2
- pbIJXs-1k3-p2

**Technical notes**

**PHP implementation** - We should be able to use the `Experimental_Abtest` class, ref: https://github.com/woocommerce/woocommerce/blob/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php

**JS implementation** - See below for an example of a previous WooCommerce experiment that utilizes custom request args for the purpose of audience targeting via custom segments: https://github.com/woocommerce/woocommerce/blob/dfdafc1568de0548ce3fbabcfe7282714306e2df/plugins/woocommerce-admin/client/homescreen/hooks/use-headercard-experiment-hook.js#L29-L42

**Design**

<img width="160" alt="Screen Shot 2022-04-19 at 10 43 37 am" src="https://user-images.githubusercontent.com/1527164/163936732-780e9c20-fadd-4fe5-a269-193be7b15743.png">

**Comment by james-allan** [comment]
> ExPlat "audience targeting" should be used to control which participants are eligible for this experiment based on the criteria above. We will likely need to use custom segments to programmatically filter for certain users.

Will ExPlat be required at this stage of the project? That is, is the menu item displayed for all sites which meet the criteria or based on the experiment users only (as determined by ExPlat)?

Or does ExPlat only come into determining what flow the user is sent on when clicking on the get started button on the subsequent screen?

**Comment by aprea** [comment]
Hey @james-allan, see my answers below:

>Will ExPlat be required at this stage of the project?

Yes, I believe so.

>That is, is the menu item displayed for all sites which meet the criteria or based on the experiment users only (as determined by ExPlat)?

The menu item will only be shown to users/stores that are eligible for this experiment. If they **are eligible** for this experiment then the menu item will be shown to 100% of the experiment participants.

My understanding is that we can use ExPlat audience targeting to filter out ineligible users/stores from this experiment.

>Or does ExPlat only come into determining what flow the user is sent on when clicking on the get started button on the subsequent screen?

Yep, ExPlay also comes into play here. This is more the "A/B test" part of the experiment (i.e. determining what flow the user is sent on when clicking on the get started button) whereas the menu item logic is more related to experiment eligibility.

**Comment by james-allan** [comment]
> My understanding is that we can use ExPlat audience targeting to filter out ineligible users/stores from this experiment.

ooh thanks that's made it more clear. I didn't realise that would be possible given you can target by locale and location by default and our criteria is pretty complex in terms of plugins installed etc. I can see there's existing custom segments as you mentioned though with examples. PCYsg-FqJ-p2#audience-targeting-custom

So we could for example send via request args a list of plugins, store "live" date, sales data and house the eligibility criteria in Explat custom segments?

**Comment by aprea** [comment]
>So we could for example send via request args a list of plugins, store "live" date, sales data and house the eligibility criteria in Explat custom segments?

I believe we can, the [`Experimental_Abtest` class ](https://github.com/woocommerce/woocommerce/blob/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php) has a `woocommerce_explat_request_args` filter. I _believe_ we can use this filter to pass additional request args to ExPlat when requesting the variation. Then the filtering/assignment logic will occur at the ExPlat end.

One thing I haven't fully figured out is how the eligibility piece works.

It seems like our experiment is a little non-standard, i.e. there's usually an existing experience (aka the control) and then a new experience that we want to test it against (aka the treatment).

In our scenario, there is no control because this admin menu (and "Subscriptions" page) is new to WooCommerce core. Instead, we have 2 treatments that we want to test against each other.

After looking through the `Experimental_Abtest` class, I'm not entirely sure how we'd rig up the admin menu to not show if a particular user is ineligible for the experiment.

I'll probably need to inspect the HTTP response from the [`request_assignment()`](https://github.com/woocommerce/woocommerce/blob/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php) function to see if there's something we can use for this.

cc @Jinksi (in case this has implications on the P2 post you're working on)
