### ISSUE TITLE
Handle the "Get started" button click on the "Subscriptions" page

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#32694]
ℹ️ This issue relates to the "Experiment with subscriptions empty state in WooCommerce core" project, read more here → pdjTHR-Vi-p2

Pull requests related to this project will be targeted to a feature branch (`add/experiment-subscriptions-admin-menu`). A final pull request will be opened against `trunk` when all issues are completed and the feature branch is in a production-ready state.

---

This issue is dependent on:
- https://github.com/woocommerce/woocommerce/issues/32682
- https://github.com/woocommerce/woocommerce/issues/32691

---

A "Get started" button appears on the "Subscriptions" page located in the WordPress dashboard via **WooCommerce → Subscriptions**. When the store owner clicks this button, the [WooCommerce Payments](https://wordpress.org/plugins/woocommerce-payments/) plugin will be downloaded, installed and activated on the site.

After WooCommerce Payments is installed and activated the user will enter into one of two flows depending on which experiment treatment the user was assigned.

**Acceptance criteria**
- When the "Get started" button is clicked, the [WooCommerce Payments](https://wordpress.org/plugins/woocommerce-payments/) plugin will be downloaded, installed and activated on the site.
- When the "Get started" button is clicked, the `wcadmin_wccore_subscriptions_empty_state_get_started_click` tracks event is fired.

Then, if the user is assigned to Treatment A:
- The user is navigated to the “Add new product” page, i.e. `/wp-admin/post-new.php?post_type=product&select_subscription=true&subscription_pointers=true`

Else, if the user is assigned to Treatment B:
- The user is navigated to the WCPay onboarding (Stripe KYC), i.e. `/wp-admin/admin.php?wcpay-connect=WC_SUBSCRIPTIONS_TABLE`

**Note:** Similar flows occur in the "subscriptions empty state" implemented in WooCommerce Payments. You can view that implementation here → https://github.com/Automattic/woocommerce-payments/blob/c2169b24335e06c2bc169349cd573e888a6219f6/client/subscriptions-empty-state/index.js

**Error handling**

We should also add error handling to the "Get started" button. This is necessary as not every WordPress website allows direct plugin installation. One example of this is if the [`DISALLOW_FILE_MODS`](https://magicpress.net/2017/06/06/file-modification-security-wordpress/) constant is set to `true`.

>DISALLOW_FILE_MODS is a constant defined in wp-config.php, which disables plugin and theme updates and installation through the Dashboard.

You can observe this behaviour yourself by creating a `plugins/woocommerce/.wp-env.override.json` file and adding the following contents.

```json
{
	"config": {
		"DISALLOW_FILE_MODS": true
	}
}
```

In this scenario, we should direct the store owner to manually download, install and activate the WooCommerce Payments plugin.

**Technical notes**

We should be able to use [`installAndActivatePlugins`](https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/packages/js/data/src/plugins/actions.ts#L256) to install and activate WooCommerce Payments. You can view usages of it here → https://github.com/woocommerce/woocommerce/search?q=installAndActivatePlugins

**Design**

<img width="1220" alt="wcpay-subscriptions-empty-state-v1-1 (1)" src="https://user-images.githubusercontent.com/1527164/166624137-cada8952-bd6a-49a9-9d79-8803fa819124.png">

**Comment by james-allan** [comment]
> We should also add error handling to the "Get started" button. This is necessary as not every WordPress website allows direct plugin installation. One example of this is if the [DISALLOW_FILE_MODS](https://magicpress.net/2017/06/06/file-modification-security-wordpress/) constant is set to true.
> In this scenario, we should direct the store owner to manually download, install and activate the WooCommerce Payments plugin.

I've had a look into error handling and when the `DISALLOW_FILE_MODS` constant is set you can't even add plugins manually via the plugins screen either. So you'd need to download and install it manually via ssh, ftp or some other file management system made available via the host I guess.

I also had a look at how this was handled in other places and here's what it looks like for the WooCommerce Payments page. 

https://user-images.githubusercontent.com/8490476/166401742-19591f09-a852-4cb4-86b0-0bc1efceae17.mov

Should we do something like that? ie Add an error notice banner to the top with a note suggesting that they download and install WooCommerce payment manually and perhaps link them to the WooCommerce Payments wp.org page or woocommerce.com page.

**Comment by aprea** [comment]
>Should we do something like that? ie Add an error notice banner to the top with a note suggesting that they download and install WooCommerce payment manually and perhaps link them to the WooCommerce Payments wp.org page or woocommerce.com page.

That sounds good to me @james-allan!

**Comment by Jinksi** [comment]
> When the "Get started" button is clicked, the `wcadmin_core_subscriptions_empty_state_get_started_click` tracks event is fired.

@aprea To disambiguate the meaning of `core`, I've updated the description to change the event name prefix `wcadmin_core` → `wcadmin_wccore`.

As discussed on pdjTHR-YI-p2#comment-1166.
