### ISSUE TITLE
[Enhancement]: Disable payment gateway change after order is placed

### ISSUE THREAD

**Issue by jofbe** [woothemes/woocommerce#32696]
### Describe the solution you'd like

We have quite a few orders, where the fees are miscalculated, and the invoices are wrong, because of the following reasons:
* Customer selects Simple payment gateway to pay with credit/debit card
* Customer gets redirected to the payment gateway, but payment fails (balance issue, cancelled payment, wrong details...)
* Customer gets redirected back to the thank you page, where they select a different payment gateway (eg. COD)

Problems we have
* COD fee is not added to the order
* The invoice says payed with card (against the law here to say that when it's payed COD)

### Additional context

We have tried to add the COD fee two different ways:
* `woocommerce_cart_calculate_fees` hook
* WooCommerce Smart COD plugin
Neither of these have worked, since the order was already placed.

If this issue is already fixable by configuration, please forgive us, and help by pointing us to the right part of the documentation.

**Comment by jofbe** [comment]
Hi @jonathansadowski , can you give us any update on this ticket, or some ideas how to prevent the cases described above? Or if this is not the right place for this, please direct me to the right one.
Thank you very much!

**Comment by jofbe** [comment]
Hi @jonathansadowski , @Konamiman , do you have any updates for us on this ticket?

**Comment by jofbe** [comment]
@jonathansadowski , @Konamiman , we would really like to have a fix for this. Do you have any updates? Thanks!

**Comment by vbelolapotkov** [comment]
@pierorocca , there seem to be some issues with fees calculations during checkout when another payment method is chosen. Could you please take a look with one of your teams?

**Comment by pierorocca** [comment]
@vbelolapotkov the core issue here is more likely that the original payment method, credit/debit is failing, but still places the order against that method hence the invoice showing credit/debit and a TYP being rendered. A failed order would keep the shopper on Checkout and display an error banner. Given this is almost 2 years old, and I cannot replicate this I'm inclined to close this issue.

@jofbe thanks for reporting this issue and apologies no one had bothered to even acknowledge you. Is this an issue that you're still dealing with? If yes, could you provide more details on how to replicate this issue and what payment gateway you were encountering this against?

**Comment by jofbe** [comment]
@pierorocca , thanks for looking into this ticket. The gateway I'm using is for a Hungarian bank, developed by a Hungarian team. You can find the lates release here: https://github.com/conedevelopment/simplepay-gateway/releases/tag/v2.7.2

It seems like this got fixed/implemented at one point, as now with WooCommerce 8.2.1, if I want to reproduce the issue, I can't change the payment method anymore.

**Comment by vbelolapotkov** [comment]
Thanks for confirming @jofbe. I'll go ahead and close this one. However, if you see it again, please feel free to reopen it.
