### ISSUE TITLE
Add the "Subscriptions" admin page

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#32691]
ℹ️ This issue relates to the "Experiment with subscriptions empty state in WooCommerce core" project, read more here → pdjTHR-Vi-p2

Pull requests related to this project will be targeted to a feature branch (`add/experiment-subscriptions-admin-menu`). A final pull request will be opened against `trunk` when all issues are completed and the feature branch is in a production-ready state.

---

This issue is dependent on:
- https://github.com/woocommerce/woocommerce/issues/32682

---

A "Subscriptions" admin page is available via the WordPress dashboard by navigating to **WooCommerce → Subscriptions** (this admin menu will be implemented in #32682).

This page will include copy to explain the offering, i.e. free subscriptions functionality powered by WooCommerce Payments.

**Acceptance criteria**

* When the page loads, the `wcadmin_wccore_subscriptions_empty_state_view` tracks event is fired.
* Includes a “Terms of Service” text link which links to – [https://wordpress.com/tos/](https://wordpress.com/tos/).
* Includes a primary button that reads "Get started". For the time being, the button will not perform an action when clicked. This will be handled in https://github.com/woocommerce/woocommerce/issues/32694.

**Design**

<img width="1220" alt="wcpay-subscriptions-empty-state-v1-1 (1)" src="https://user-images.githubusercontent.com/1527164/166624156-5449bdca-7423-4f1b-a771-fc10bf086180.png">

**Comment by Jinksi** [comment]
> When the page loads, the `wcadmin_core_subscriptions_empty_state_view` tracks event is fired.

@aprea To disambiguate the meaning of `core`, I've updated the description to change the event name prefix `wcadmin_core` → `wcadmin_wccore`.

As discussed on pdjTHR-YI-p2#comment-1166.
