### ISSUE TITLE
Inbox note: task list - card sorting

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32703]
As part of the [broader initiative](https://woostartp2.wordpress.com/2022/02/11/project-thread-increase-setup-tasks-completion/) of driving more usage of the store setup task list and increasing the completion rate of each task, we’d like to gather some more data on users priorities in order to shape a setup task list more in line with their expectations and needs.

**New inbox note, delivered using the remote system:**

**Title**: We want to know what matters most to you
**Content**: Take 2 minutes to give us your input on what is important for you while setting up your store and help shape the future of WooCommerce together.
**Segmentation**: store_age > 6 months
**Timing**: Immediate
**Cadence**: once
**CTA leads to**: https://t.maze.co/87390007
**CTA label**: Share your input

![image](https://user-images.githubusercontent.com/98944206/164644869-78a034bc-f03b-40fb-8807-bb27bdca2b1f.png)

**Acceptance criteria:**

- [x]  A new inbox note is delivered, using the remote system, with the details shown above
- [x]  The CTA for the note redirects the user to the card sorting exercise

**Comment by pmcpinto** [comment]
> Segmentation: all the users

@verofasulo  it would be great to target only new users or at least those who have recently gone through the setup experience. For example: store age less than 3 months old. What do you think?

**Comment by verofasulo** [comment]
Thanks for your feedback @pmcpinto! Why do you think it's better to focus on new users only?

**Comment by pmcpinto** [comment]
@verofasulo I've just reviewed the inbox copy and I think it would be interesting to make some adjustments to the content, mainly to be more specific on the time it takes and what we want from users. The way it's framed right now it looks like we're asking them to provide open-ended feedback. Makes sense?

**Comment by verofasulo** [comment]
@pmcpinto totally! I updated the content with something more specific and goal-oriented.

**Comment by pmcpinto** [comment]
@adrianduffell can you publish it on Monday or Tuesday?

**Comment by verofasulo** [comment]
@pmcpinto @adrianduffell could you please double-check the test at [this link](https://app.maze.co/maze-preview/mazes/87390007/) and let me know if you spot any typos? 🙏 Once I publish it, I can't go back and make any changes (I guess it's a restriction due to the free plan). After publishing it, I'll update the Maze link in the issue (the previous one is not working anymore as I had to delete it and create a new one to make changes). Thanks a lot, guys!

**Comment by adrianduffell** [comment]
> @adrianduffell can you publish it on Monday or Tuesday?

Yup, can do 👍

**Comment by adrianduffell** [comment]
>  let me know if you spot any typos?

@verofasulo I didn't spot any typos, all LGTM! Looking forward to seeing the survey results.

**Comment by verofasulo** [comment]
Thanks, @adrianduffell! I'm going to make it live then :)

**Comment by ilyasfoo** [comment]
Inbox note is published 
https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json:

```json

{
  "slug": "setup_task_initiative_survey_q2_2022",
  "type": "survey",
  "status": "unactioned",
  "is_snoozable": 0,
  "source": "woocommerce.com",
  "locales": [
    {
      "locale": "en_US",
      "title": "We want to know what matters most to you",
      "content": "Take 2 minutes to give us your input on what is important for you while setting up your store and help shape the future of WooCommerce together."
    }
  ],
  "actions": [
    {
      "name": "setup_task_initiative_survey_q2_2022_share_your_input",
      "locales": [{ "locale": "en_US", "label": "Share your input" }],
      "url": "https://t.maze.co/87390007",
      "url_is_admin_query": false,
      "is_primary": false,
      "status": "actioned"
    }
  ],
  "rules": [
    { "type": "publish_after_time", "publish_after": "2022-04-26 00:00:37" },
    { "type": "wcadmin_active_for", "operation": "<", "days": 180 }
  ]
}
```

**Comment by mboyle190** [comment]
Hey all @verofasulo @pmcpinto @ilyasfoo @adrianduffell I noticed on my support rotation in setting up a new store that this inbox notification is still live and publishes for every new store on set-up, but the maze.co link is no longer active. I'm assuming that means the survey is closed (or we're not monitoring results), so I'm unpublishing the note for now. The note set-up is here FYI: https://woocommerce.com/wp-admin/post.php?post=18734000369290&action=edit

**Comment by ilyasfoo** [comment]
Thank you for catching and rectifying that, @mboyle190!

**Comment by verofasulo** [comment]
Thank you @mboyle190! Yes, the survey is closed so please just unpublish the note 🙏 Thanks a lot
