### ISSUE TITLE
Inbox message: remove wc-admin-set-up-additional-payment-types

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32719]
**Description:** The `wc-admin-set-up-additional-payment-types` message needs to be removed as we're using the "things to do next" list to promote additional payment gateways. 

![Captura de ecrã 2022-04-21, às 15.41.37.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/073cddd9-236b-43d9-b38b-9e6413ddf64f)

The message was removed a couple of months ago. See this [issue](https://github.com/woocommerce/woocommerce-admin/issues/7720). I don't know why it's showing up again. 

**Acceptance criteria:**

- [ ] Remove the `wc-admin-set-up-additional-payment-types` inbox message

**Comment by pmcpinto** [comment]
@adrianduffell @ilyasfoo I don't know if this is connected to the Payments task work implemented for WC 6.5.

**Comment by ilyasfoo** [comment]
> I don't know if this is connected to the Payments task work implemented for WC 6.5.

@pmcpinto Not connected afaik. There could be a misunderstanding in the previous issue, the merged [PR](https://github.com/woocommerce/woocommerce-admin/pull/7980) does the following:
> Deletes the note for setting up additional payment gateways when WC Pay is active

Note that "delete" mentioned here is not the deletion of `SetUpAdditionalPaymentTypes.php` note code, but rather the removal of that particular note if it was added to a store (through `wc_admin_daily` cron job).

So I'm just clarifying that we'd want to delete the note code altogether? The previous issue only mentioned its removal on condition of WCPay task:

> If the WCPayments task is displayed, remove the `wc-admin-set-up-additional-payment-types` inbox message ([src](https://github.com/woocommerce/woocommerce-admin/blob/5eefe37ccd7bfbf39c96c72917c2f96f46e231ee/src/Notes/SetUpAdditionalPaymentTypes.php))

**Comment by pmcpinto** [comment]
@ilyasfoo thanks for the clarification.

> So I'm just clarifying that we'd want to delete the note code altogether? The previous issue only mentioned its removal on condition of WCPay task

Yes. It should be removed whether the WCPay task displayed or not
