### ISSUE TITLE
[WC 6.5 beta1] WCPay task leads to a blank page in the two variants

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32714]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The WooCommerce Payments task is not working well with the two variants:
- Clicking the WCPayments task redirects the user to a blank page
- We're not showing the legal message

### Expected behavior

- Clicking in the WCPayments task should redirect the user to the WCPayments onboarding
- We need to display the legal message:
_By setting up, you are agreeing to the [Terms of Service](https://wordpress.com/tos/)_

### Actual behavior

- Clicking the WCPayments task redirects the user to a blank page

### Steps to reproduce

1. Install WC 6.5 Beta 1 and WooCommerce Admin Test Helper 0.7.2
2. Enable usage tracking
3. Install WooCommerce Payments in the Business features step
4. Visit Tools > WCA Test Helper > Experiments and enable woocommerce_tasklist_setup_experiment_2_2022_04
5. Visit the home screen and see that the legal message is missing in the WCPaymens task, click and see the blank page
6. Visit Tools > WCA Test Helper > Experiments and enable woocommerce_tasklist_setup_experiment_1_2022_04
7. Visit the home screen and see that the legal message is missing in the WCPaymens task, click and see the blank page

### WordPress Environment

WooCommerce 6.5 Beta 1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@joshuatf @louwie17 can you take a look at this? Thanks

**Comment by louwie17** [comment]
> @joshuatf @louwie17 can you take a look at this? Thanks

Thanks, yeah one of us on Mothra should have time to look at this. Thanks @pmcpinto

**Comment by jarekmorawski** [comment]
Hi there! Here's the updated design and copy for both experiments:

* G9vi4e286yjdzyIdg8hBb1-fi-1607%3A156382 (Experiment 1)
* G9vi4e286yjdzyIdg8hBb1-fi-1607%3A171234 (Experiment 2)

**Comment by louwie17** [comment]
I created a separate issue for the Terms of Use stuff (as discussed in Slack), given this issue is largely fixed in relation to the blank page issue. - https://github.com/woocommerce/woocommerce/issues/32762
