### ISSUE TITLE
[HPOS] [Sync] Add support for deleting meta rows that don't exist in the source table anymore, in the destination meta table as well

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32757]
In #32640 we implement meta to migration support. We use this to power migration from wp_postmeta to wc_orders_meta table.

While this implementation takes care of updating and creating meta rows as needed, it currently does not take care of deleting rows in the destination table that have been deleted from the source table.
This issue scopes implementing delete as well.

**Comment by jorgeatorres** [comment]
Augmenting the scope of this issue to include metadata sync in the opposite direction (from #35490):

> ### Describe the bug
> 
> When the "Use the WooCommerce orders tables" feature is enabled then the function delete_meta_data( $metaKey ) is not working. It deletes order meta by the given meta key but only from the new table wc_orders_meta. So after a while the meta key apperas again in the table because it remains in the postmeta table.
> This happen when the table sychronization is enabled with transaction enabled or not.
> I didn't tested if this happens when the synchronization is disabled.
> I found a work around for the moment:
> first I make a call to delete_postmeta( $postID, $metaKey ) and then delete_meta_data( $metaKey )
> 
> ### Expected behavior
> 
> The given order meta be deleted.
> 
> ### Actual behavior
> 
> The given order meta be deleted only from wc_orders_meta and remains in postmeta table. So with data sychronization it apears again in wc_orders_meta table.
> 
> ### Steps to reproduce
> 
> 1. Call function delete_meta_data( $metaKey )
> 2. Check the wc_order_meta and postmeta table records

**Comment by Konamiman** [comment]
Closing at it's already implemented.
