### ISSUE TITLE
[Enhancement]: phpDoc for apply_filters/do_action

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#32750]
### Describe the solution you'd like

All apply_filters/do_action should have phpDoc with all @param, as outlined in WP core https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters

This makes using them much faster (since I don't have to check what types this filter needs) and also less bug prone (incorrect type passed) both for WooCommerce core contributors and people who extend WooCommerce.

**Comment by roykho** [comment]
Hi @kkmuffme 

Thanks for raising this and we're aware. While we may not be able to retrospectively add docblocks to all existing hooks, we will however try our best to have them on new hooks.
