### ISSUE TITLE
Pin Ubuntu Version in Workflows

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#32768]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We are currently experiencing problems due to using the latest version of ubuntu in our GitHub workflows. We need to pin these to the last working version.

- Review other PRs for last working version
- Create a PR pinning all of the versions in our workflows
- Update `release/6.5` as well so that our release automation works

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce/pull/32782
