### ISSUE TITLE
Setup experiment: Add a store details card

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#32760]
### Describe the solution you'd like

👋 Hi there! Following up on our Slack conversation (p1650522879606939-slack), I put together a design for the store details task. It'd show up if merchants skipped the OBW and did not enter store details during setup.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/79307566/165108643-7ae18c23-3f5d-44c8-b2e4-b6ed67055036.png">

**See it in Figma: G9vi4e286yjdzyIdg8hBb1-fi-1609%3A157417**

In the same situation in Experiment 2, we'd only need to mark the store details as unfinished and change the body copy to:

> **Add store details**
We’ll use this info to quickly set up shipping, tax, and payments.

Let me know if you have any questions!

**Comment by adrianduffell** [comment]
Closing due to age -- the store details are now not possible to skip in the Core Profiler.
