### ISSUE TITLE
Marketing task: add new TikTok extension

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32778]
**Description:** The TikTok extension is launching soon. We plan to include the extension in the marketing task, starting in the WooCommerce 6.6 release (code freeze: May 19). More info here: paqDfi-3AU-p2

Location: Marketing task - below Google Listing and Ads
Copy:
Headline: TikTok for WooCommerce
Description: Grow your online sales by promoting your products on TikTok to over one billion monthly active users around the world.
wp.org link: https://wordpress.org/plugins/tiktok-for-business/

Logo: 

There's two variations of the logo (black and transparent). Let's proceed with the black one for now, however could comparison screenshots be provided in the PR for each logo, so our designers can make a final decision on it in the testing phase.

![TT_black](https://user-images.githubusercontent.com/9312929/168202929-2cad29c7-86d9-4388-a694-76385bac0dbb.svg)

![TT_transparent](https://user-images.githubusercontent.com/9312929/168202934-92372f1e-7602-417e-9830-7d8d1f614aa1.svg)

**Comment by pmcpinto** [comment]
@adrianduffell @becdetat this has to be included in Cycle 24 in time to be implemented before the 6.6 code freeze. Let me know if we have to adjust any priorities to accommodate this work. Thanks!

**Comment by moon0326** [comment]
> We’re planning to promote the extension in regions where users are able to run product ads via the extension, these regions are:
> US, Canada, Mexico, Austria, Belgium, Czech Republic, Denmark, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Netherlands, Poland, Portugal, Romania, Spain, Sweden, the United Kingdom, Switzerland, Norway, Australia, New Zealand, Singapore, Malaysia, Philippines, Indonesia, Vietnam, Thailand, South Korea, Israel, UAE, Russia, Ukraine, Turkey, Saudi Arabia, Brazil, Japan

Country codes: US, CA, MX, AT, BE, CZ, DK, FI, FR, DE, GR, HU, IE, IT, NL, PL, PT, RO, ES, SE, GB, CH, NO, AU, NZ, SG, MY, PH, ID, VN, TH, KR, IL, AE, RU, UA, TR, SA, BR, JP

**Comment by moon0326** [comment]
I've opened a draft [PR](https://github.com/woocommerce/woocommerce/pull/32850) to add TikTok task to the default task list. Once we have logo and link to the wp.org, we also need to work on adding a new entry to `https://woocommerce.com/wp-json/wccom/obw-free-extensions/3.0/extensions.json`

**Comment by adrianduffell** [comment]
Just labelling this as blocked until we have the remaining items (logo and link to the wp.org).

**Comment by adrianduffell** [comment]
I've now updated the description with the logo and link to wp.org.

**Comment by moon0326** [comment]
@adrianduffell @pmcpinto 

The plugin page says, "Follow the prompts to complete set-up and create or connect your TikTok accounts." on https://wordpress.org/plugins/tiktok-for-business/, but it never did when I installed the plugin on my local and a JN site.

There is no settings page either. I must be missing something 🤔 Could you try installing the plugin and see how it works for you? 

![Screen Shot 2022-05-13 at 4 28 37 PM](https://user-images.githubusercontent.com/4723145/168401132-be340b64-0aa0-4257-ad70-7370a26bb75f.jpg)

**Comment by pmcpinto** [comment]
@moon0326 thanks for spotting this. I've just installed the extension on a JN site and I'm not being redirected to their setup and I'm also not seeing any settings. Let me see if we can get in touch with them

**Comment by pmcpinto** [comment]
There's a menu item within Marketing with a prompt to connect the account
