### ISSUE TITLE
Add event tracking for import products

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32811]
Event tracking for
- #32143 

**Import products**

- Task completion rate
- Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
- % of users that clicks on one of the two recommended options
- % of users that clicks on "add your products from scratch"
- % of users that clicks on one product type pr start blank (Same as https://github.com/woocommerce/woocommerce/issues/32633)
- List of the most clicked import products option (from CSV or Cart2Cart)

**Comment by chihsuan** [comment]
Based on https://github.com/woocommerce/woocommerce/issues/32633#issuecomment-1112399807

For import products event tracking, we should also use what we already have:

- `wcadmin_task_view`
- `wcadmin_tasklist_task_completed`
- `wcadmin_tasklist_add_product`
product_template - fired when one of the template options is selected
manually - fired when the user selects start blank
import - fired when the user selects the import option
migrate - fired when the user selects the migration option
sampe_products - fired when the selects the sample products option

I think we need to add `import_cart2cart` or a new prop to distinguish between CSV and Cart2Cart.

New tracks

-  Event for when the user clicks "add your products from scratch"
-  The completion time

cc @pmcpinto

**Comment by pmcpinto** [comment]
Hey @chihsuan 

> I think we need to add import_cart2cart or a new prop to distinguish between CSV and Cart2Cart.

We're firing `import` when the user selects CSV and `migrate` when the user selects the Cart2Cart options. So it's not necessary to add `import_cart2cart`

**Comment by chihsuan** [comment]
@pmcpinto Gotcha. Thanks for the clarification!

Regarding the task completion time, I noticed that we use time frames ( '0-2s','3-4s','5-9s'...) for onboarding flow. Should we also use the same format here for `task_completion_time`, or time in milliseconds? cc @rjchow 

![screenshot](https://user-images.githubusercontent.com/2240960/146444895-c43568e8-6805-49cc-8b10-ac28a98b8f0f.png)

New events:

- `tasklist_add_product_from_scratch_click`: Event for when the user clicks "add your products from scratch"
- `task_completion_time`: 
     - task_name
     - time

**Comment by pmcpinto** [comment]
> Regarding the task completion time, I noticed that we use time frames ( '0-2s','3-4s','5-9s'...) for onboarding flow. Should we also use the same format here for task_completion_time, or time in milliseconds? 

It's ok to use the same time frames we're using for the task completion time. Thanks
