### ISSUE TITLE
[COT] Publish a call for testing to test migrations into custom order tables.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32844]
Now that implementation for migrations is complete, we should publish a call for testing to test out migrations. This document should include:
- [x] Instructions along with code on how to run/re-run migrations (along with a warning to not run on production).
- [x] Instructions on how to measure and report back the instrumentation data that we will identify in #
- [x] Queries to verify the integrity of the migrated data.

**Comment by lukecav** [comment]
Are there any WP-CLI commands for checking the number of existing orders on a site, along with running the migration of orders to the new order tables?

**Comment by vedanshujain** [comment]
@lukecav not yet, currently there is only UI. Although it would be a nice to have before publishing a call for testing especially for large stores.

**Comment by vedanshujain** [comment]
Added  https://github.com/woocommerce/woocommerce/issues/32917 to track CLI implementation.

**Comment by vedanshujain** [comment]
Published here [Call for early testing – custom order table migrations](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
