### ISSUE TITLE
[COT] Implement `delete` function for when migrating from posts to COT table

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32842]
In the current implementation, when migration is still in progress, we plan to update the corresponding record in the custom order table (if it's already migrated). However, so far, we have not implemented a delete method yet.

This issue scopes adding functionality to delete the COT record if the post record is being deleted, and the posts table are still the authoritative ones.

**Comment by Konamiman** [comment]
Closing at it's already implemented.
