### ISSUE TITLE
[COT] Research caching API for custom order table datastore and its interaction with WC_Order object

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32841]
Currently, we use a mix of caching provided by WP posts as well as our own implementation in `WC_Cache_Helper`. However, since we won't be using WP Posts cache (at least in its current form), we should settle on a cache implementation that we will in-fact use.

In the caching implementation, we should be able to manage order and all its data (order properties, refunds, order items, etc) in a single call per order.

Note that the implementation must be compatible with the `WP_Object_Cache` class which does not allow for grouping in the default implementation. Currently, we implement grouping by algorithm for [simulating namespaces](https://github.com/memcached/memcached/wiki/ProgrammingTricks#simulating-namespaces-with-key-prefixes):

1. Maintaining a prefix in a cache object for a group (or an id).
2. Using that prefix in the cache keys for all objects in the group.
3. To invalidate the cache, we modify the prefix, thereby making all currently stored cache values for that group in-accessible.

This issue scopes designing an API to combine current order cache implementation and WP posts cache that we won't be able to use anymore.

**Comment by peterfabian** [comment]
Part of the research is defining policy for extensions---will they be able to include data in the cached data? Preferably yes, so that they don't need to hook too much into actions. 

VIP also had some reservations with core fetching orders too often from the db... (source?)

The estimate is the timebox [days] for the research.

**Comment by Konamiman** [comment]
The result of the research was this approved RFC: p7bje6-45j-p2

**Comment by peterfabian** [comment]
I assume this can be closed now as the RFC has been resolved? Do we want to create an external RFC for this once the PR is up?

**Comment by vedanshujain** [comment]
Closing the issue now, but let's add a public RFC as well as part of the PR.
