### ISSUE TITLE
Add fashion csv sample file

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32859]
### User Story

> As a new fashion merchant, I want to import sample products related to my industry, so that I can preview my store before my products are ready to add.

**Design overview**
Here you can find all the images and the author:
cJQeyyhx9PraQrY3YAtCGM-fi-1517%3A156861

### Acceptance Criteria

* New [sample data file](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/sample-data) `onboarding/fashion.csv`.
* Nine products in file.
* Products have generic names/description but realistic data for price/weight/stock/etc.
* Product photos may be sourced from CC0-licensed images on [openverse](https://wordpress.org/openverse/)
* Product photos are credited in the product description.
* Product photos are hosted from https://woocommercecore.mystagingwebsite.com

**Comment by verofasulo** [comment]
Hi @adrianduffell 😄

The following are 12 free images we can use. [Pexels](https://www.pexels.com/) is the source. I tried to find something on Openverse but there wasn't anything suitable for our purpose. Let me know if you prefer a .zip file and I'll email it to you (I just can't add it here on GH). 

![pexels-cottonbro-7760006](https://user-images.githubusercontent.com/98944206/167113823-3f0757ff-c7c2-44d0-a1e9-0b006772b39a.jpg)
![pexels-cottonbro-7760034](https://user-images.githubusercontent.com/98944206/167113836-efdbde32-7863-4a24-9d2d-979025b51260.jpg)
![pexels-cottonbro-7760230](https://user-images.githubusercontent.com/98944206/167113851-84b1da86-5c2a-4cce-9deb-4444848778d4.jpg)
![pexels-cottonbro-7760796](https://user-images.githubusercontent.com/98944206/167113854-b669deff-4c3e-4bb0-b00f-96cfbdc4087e.jpg)
![pexels-cottonbro-7760804](https://user-images.githubusercontent.com/98944206/167113857-839785e4-d25a-45f0-b647-cd8d9be8bc2d.jpg)
![pexels-cottonbro-7761083](https://user-images.githubusercontent.com/98944206/167113861-531ebbcd-f9b5-4c18-b5c7-a878d5017ca2.jpg)
![pexels-cottonbro-7764066](https://user-images.githubusercontent.com/98944206/167113864-14d59cf5-1233-4053-8193-070413ea3434.jpg)
![pexels-cottonbro-7760001](https://user-images.githubusercontent.com/98944206/167113817-0fd3751e-b81b-4def-be53-040d8fa049f2.jpg)
![pexels-cottonbro-6626750](https://user-images.githubusercontent.com/98944206/167113801-fd8243b7-8465-4f82-86c1-2c54797fe296.jpg)
![pexels-cottonbro-6626876](https://user-images.githubusercontent.com/98944206/167113811-0be977aa-edfe-4a09-b36d-a62f02de4a29.jpg)
![pexels-cottonbro-6626747](https://user-images.githubusercontent.com/98944206/167113788-89c7c55f-f4e0-4cae-99f0-a8915393b07d.jpg)
![pexels-cottonbro-6626743](https://user-images.githubusercontent.com/98944206/167113771-3fc25ad5-df86-4c3c-88a3-ee6fa81ad84a.jpg)

**Comment by verofasulo** [comment]
And, of course, if you think it's necessary to upload more than 12 sample images, please just let me know and I'll add some more 🙂

**Comment by adrianduffell** [comment]
@verofasulo Thank you, these photos are amazing! I was planning to ask you whether you thought there were any suitable ones on openverse.

That's probably enough fashion photos for now. If you're keen, you could possibly work ahead and find photos for the other industries?

**Comment by verofasulo** [comment]
@vivialice did an amazing work putting together a collection of fashion images 🙌 I just picked a few ones 😄

> If you're keen, you could possibly work ahead and find photos for the other industries?

@adrianduffell  Yes, for sure! I attach a graph that shows the industries where most of our users operate. I think we can start collecting images from `food and drinks` and `electronics and computers`. What do you think?

**Comment by adrianduffell** [comment]
> I think we can start collecting images from food and drinks and electronics and computers. What do you think?

That sounds great, thanks! Yes I think it makes sense to prioritize those industries based on the chart.

**Comment by adrianduffell** [comment]
Potentially the photos would be hosted on the site `https://woocommercecore.mystagingwebsite.com`, like in the existing sample files. I'll check with others if this site has the capacity to handle additional traffic.

**Comment by adrianduffell** [comment]
@verofasulo Do you know which user(s) provided these photos on Pexels? It would be nice to give them credit in the product description if we can. Here's what it says on Pexels:

> Attribution is not required. Giving credit to the photographer or Pexels is not necessary but always appreciated.

https://www.pexels.com/license/

**Comment by verofasulo** [comment]
> Do you know which user(s) provided these photos on Pexels? It would be nice to give them credit in the product description if we can

Nice idea @adrianduffell! cottonbro is the author (all the photos) - you can find the profile at [this link](https://www.pexels.com/@cottonbro/).

**Comment by verofasulo** [comment]
Hey @adrianduffell 😄

I created this page in Figma where you can find all the pics and the authors:

cJQeyyhx9PraQrY3YAtCGM-fi-1517%3A156861 

Industries:
- Clothing and accessories
- Beauty and health
- Electronics and computers
- Food and drinks

**Comment by pmcpinto** [comment]
@adrianduffell have you checked with the wp.org plugin review team if it's ok to use this approach?

Here's the feedback I received from them more than 1 year ago when we were thinking about hosting images externally:

> You may INCLUDE CC0 images in your plugins but you cannot load them remotely without opt in consent. People need to CHOOSE to use the service, and be told what service it is. Remember GDPR.
Keep in mind, if you accidentally include non GPL compatible plugins, we will have to close the plugin because you put the entire directory at risk. So ... y’know be VERY CAREFUL here.

**Comment by adrianduffell** [comment]
Hey @pmcpinto , good call out!

We've had a few discussions around this internally in Ghidorah but not with the wp.org plugin review team. We think it needs to be restricted to sites that have opted into tracking, similarly to the approach we use for the remote configuration for onboarding (marketing extensions / payment gateways) and the externally hosted images for those.

At the moment, the sample products import is gated behind an experiment, which requires opt-in consent for tracking. Do you think this satisfies the consent requirements?

I think that if we go ahead with deploying the feature after the experiment ends, we could also implement an opt-in consent check on the feature when tracking is disabled.

**Comment by pmcpinto** [comment]
Just to be safe, I think it would be good to check with them if they're ok with this approach. Can you send them an email? plugins@wordpress.org

**Comment by pmcpinto** [comment]
@adrianduffell have you talked to them?

**Comment by adrianduffell** [comment]
@pmcpinto Thanks for that ping, I've just seen your original reply and asked the PRT about it now.

**Comment by adrianduffell** [comment]
@pmcpinto The PRT replied and said the UI needs to state that images will be downloaded from woocommerce.com in order to create sample products.

I'll close this issue out (since the csv file itself is done) and we can address this concern in https://github.com/woocommerce/woocommerce/issues/33167
