### ISSUE TITLE
Inbox note: Store setup survey

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#32856]
**Description**: we want to start triggering a new survey to collect qualitative feedback about the store setup experience, and the easiest way is to deliver a new inbox note.

**Title**: How is your store setup going?
**Content**: Our goal is to make sure you have all the right tools to start setting up your store in the smoothest way possible. 
We’d love to know if we hit our mark and how we can improve. To collect your thoughts, we made a 2-minute survey.
**Segmentation**: new users
**Timing**: 8 days after registration
**Cadence**: once
**CTA leads to**: https://automattic.survey.fm/store-setup-survey-2022
**CTA label**: Tell us how it’s going

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/98944206/166426909-8ba8c905-fb24-4e68-85ca-1fd16c7a8c16.png">

**Acceptance criteria:**
- [ ]  A new inbox note is delivered, using the remote system, with the details shown above
- [ ]  The CTA for the note redirects the user to the store setup survey

**Comment by pmcpinto** [comment]
@adrianduffell I'm adding this to the cycle 24 backlog in case there's time to implement this notification during the last days of the cycle

**Comment by chihsuan** [comment]
I've published it and tested it well.

<img width="910" alt="Screen Shot 2022-05-10 at 11 02 58" src="https://user-images.githubusercontent.com/4344253/167537837-371d2aef-6e96-4aa6-b08a-976bb2eddfd2.png">


```json
{
  "slug":"store_setup_survey_survey_q2_2022",
  "type":"survey",
  "status":"unactioned",
  "is_snoozable":0,
  "source":"woocommerce.com",
  "locales":[
    {
      "locale":"en_US",
      "title":"How is your store setup going?",
      "content":"Our goal is to make sure you have all the right tools to start setting up your store in the smoothest way possible.\r\nWe\u2019d love to know if we hit our mark and how we can improve. To collect your thoughts, we made a 2-minute survey."
    }
  ],
  "actions":[
    {
      "name":"store_setup_survey_survey_q2_2022_share_your_thoughts",
      "locales":[
        {
          "locale":"en_US",
          "label":"Tell us how it\u2019s going"
        }
      ],
      "url":"https:\/\/automattic.survey.fm\/store-setup-survey-2022",
      "url_is_admin_query":false,
      "is_primary":false,
      "status":"actioned"
    }
  ],
  "rules":[
    {
      "type":"publish_after_time",
      "publish_after":"2022-05-09 08:42:10"
    },
    {
      "type":"wcadmin_active_for",
      "operation":">",
      "days":7
    },
    {
      "type":"wcadmin_active_for",
      "operation":"<",
      "days":9
    }
  ]
}
```
