### ISSUE TITLE
Encoding problem on products export

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#32878]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I found a bug when I export products to CSV file. Generated CSV file contains wrong characters (wrong encoding). This happens on server with **PHP 8.1 installed**.
Encoding on Apache server, DB, and WordPress settings are correct (UTF-8 in my case).
The problem presents in this file: `/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php`
with this code:
```
$use_mb = function_exists( 'mb_convert_encoding' );
if ( $use_mb ) {
  $encoding = mb_detect_encoding( $data, 'UTF-8, ISO-8859-1', true );
  $data     = 'UTF-8' === $encoding ? $data : utf8_encode( $data );
}
```

When I comment this code above, the export is correct - with correct characters.

Thank you

### Expected behavior

Characters should be exported correctly, with preferred encoding.

### Actual behavior

Characters are exported in wrong encoding.

### Steps to reproduce

1. located file: /wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php
2. line no: 398 - 403 after I comment this lines it export products correctly

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sk_SK
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.1.3
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.5.15-MariaDB-1:10.5.15+maria~focal-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 160.86MB
Database Data Size: 114.08MB
Database Index Size: 46.78MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
unimodul_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ju_queue: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.17MB + Index: 0.33MB + Engine InnoDB
wp_postmeta: Data: 61.59MB + Index: 20.06MB + Engine InnoDB
wp_posts: Data: 15.52MB + Index: 3.89MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_usermeta: Data: 0.28MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.34MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_sf_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpio_images: Data: 7.52MB + Index: 4.52MB + Engine InnoDB
wp_wpio_listimages: Data: 10.52MB + Index: 7.56MB + Engine InnoDB
wp_wpio_queue: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 1.81MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 238
acf-field-group: 15
attachment: 6747
awcdp_payment: 12
b_gems: 12
cookielawinfo: 6
custom_css: 1
elementor_library: 1
gems: 30
nav_menu_item: 23
page: 36
post: 16
product: 648
product_variation: 624
revision: 4326
shop_order: 45
shop_order_refund: 3
tablepress_table: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WooCommerce GPWebPayGpe: by platiti.cz – 1.00
WooCommerce GPWebPayGpe ApplePay: by platiti.cz – 1.00
WooCommerce GPWebPayGpe GooglePay: by platiti.cz – 1.00
WooCommerce platiti.cz adapter: by platiti.cz – 1.00
Advanced Custom Fields: Woocommerce Attribute Picker: by Nick Kalscheur – 1.0.0
ACF QuickEdit Fields: by Jörn Lund – 3.1.11
Advanced Custom Fields PRO: by Delicious Brains – 5.12.2
All-in-One WP Migration: by ServMask – 7.59
Classic Editor: by WordPress Contributors – 1.6.2
Contact Form 7: by Takayuki Miyoshi – 5.5.6
GDPR Cookie Consent: by WebToffee – 2.1.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.4
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.7

Egne Stones: by HR - Kreatívna agentúra s.r.o. – 0.8.0
Elementor Pro: by Elementor.com – 3.6.5
Elementor: by Elementor.com – 3.6.5
Encyklopedia drahokamov: by TOMAXED DIGITAL – 1.0
Flexible Shipping: by WP Desk – 4.11.6
ImageRecycle pdf & image compression: by ImageRecycle – 3.1.9
Instagram Feed Pro Personal: by Smash Balloon – 6.0.5
Simple Custom CSS: by John Regan – 4.0.5
TablePress: by Tobias Bäthge – 1.14
Duplicate Variations for WooCommerce: by Emran Ahmed – 2.0.2
WooCommerce Deposits: by WooCommerce – 1.5.7
WooCommerce Shipping & Tax: by WooCommerce – 1.25.26 (update to version 1.25.27 is available)
WooCommerce SuperFaktúra: by Webikon (Ján Bočínec)
2day.sk – 1.11.9

WooCommerce: by Automattic – 6.4.1
Yoast SEO: by Team Yoast – 18.7
WP Media folder: by Joomunited – 5.4.1
WP Migrate Lite: by Delicious Brains – 2.3.0

### Inactive Plugins (2) ###

WooCommerce Balikobot: by IDEATECH
s. r. o. – 1.33

WP Fastest Cache: by Emre Vona – 1.0.0

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #24 - /obchod/
Cart: #25 - /kosik/
Checkout: #26 - /pokladna/
My account: #27 - /moj-ucet/
Terms and conditions: #3 - /gdpr/

### Theme ###

Name: EGNE
Version: 999
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: egne/woocommerce/archive-product.php
egne/woocommerce/cart/cart-shipping.php
egne/woocommerce/cart/cart-totals.php
egne/woocommerce/cart/cart.php
egne/woocommerce/cart/proceed-to-checkout-button.php
egne/woocommerce/cart/shipping-calculator.php
egne/woocommerce/checkout/form-billing.php
egne/woocommerce/checkout/form-checkout.php
egne/woocommerce/checkout/form-coupon.php
egne/woocommerce/checkout/form-login.php
egne/woocommerce/checkout/form-pay.php
egne/woocommerce/checkout/form-shipping.php
egne/woocommerce/checkout/payment-method.php
egne/woocommerce/checkout/payment.php
egne/woocommerce/checkout/review-order.php
egne/woocommerce/checkout/terms.php
egne/woocommerce/checkout/thankyou.php
egne/woocommerce/content-product.php
egne/woocommerce/content-single-product.php
egne/woocommerce/emails/email-addresses.php
egne/woocommerce/global/form-login.php
egne/woocommerce/loop/loop-end.php
egne/woocommerce/loop/loop-start.php
egne/woocommerce/loop/orderby.php
egne/woocommerce/loop/pagination.php
egne/woocommerce/loop/result-count.php
egne/woocommerce/myaccount/dashboard.php
egne/woocommerce/myaccount/form-edit-account.php
egne/woocommerce/myaccount/form-edit-address.php
egne/woocommerce/myaccount/form-login.php
egne/woocommerce/myaccount/form-lost-password.php
egne/woocommerce/myaccount/form-reset-password.php
egne/woocommerce/myaccount/my-account.php
egne/woocommerce/myaccount/my-address.php
egne/woocommerce/myaccount/navigation.php
egne/woocommerce/myaccount/orders.php
egne/woocommerce/myaccount/view-order.php
egne/woocommerce/order/order-details-customer.php
egne/woocommerce/order/order-details-item.php
egne/woocommerce/order/order-details.php
egne/woocommerce/single-product/add-to-cart/simple.php
egne/woocommerce/single-product/add-to-cart/variable.php
egne/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
egne/woocommerce/single-product/add-to-cart/variation.php
egne/woocommerce/single-product/product-attributes.php
egne/woocommerce/single-product/product-image.php
egne/woocommerce/single-product/review-meta.php
egne/woocommerce/single-product/review-rating.php
egne/woocommerce/single-product/review.php
egne/woocommerce/single-product/tabs/tabs.php
egne/woocommerce/single-product-reviews.php
egne/single-product.php

### Action Scheduler ###

Pending: 8
Oldest: 2022-05-03 13:03:58 +0200
Newest: 2022-05-05 12:12:15 +0200

### Status report information ###

Generated at: 2022-05-05 13:44:13 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Hi @martinkovac - thanks for reporting but can you please provide clear steps to reproduce as a user?

**Comment by uiroshan** [comment]
I got this issue with my wordpress installation as well. I have php 8.1.6 installed with openlitespeed web server.

Steps:
1. I have products has unicode (Sinhala language) characters in their name and description.
2. From Admin panel Products, When I export them into CSV, I am not getting correct characters in the output. 

Expected after export (Actually this is what I am importing):
`240,simple,,"පියාඹන තොප්පිය | Piyambana Thoppiya",1,0,visible,"දවසක් එක්තරා මහත්මයෙක් කඩේට ගිහින් කුඩයක් මිලදී ගත්තා. ඒක එයා ඔළුවේ දා ගත්තා. තට්ටේ රත් වෙලා නිසා තොප්පියට ඔළුව උඩ ඉන්න අමාරුයි. තොප්පිය දැන් මොනවා කරයිද?",,,,taxable,,1,4,,0,0,0.049,24.5,18,0.2,1,,200,210,"Story Books",,,"",,,,,,,,,0,%e0%b6%b4%e0%b7%92%e0%b6%ba%e0%b7%8f%e0%b6%b9%e0%b6%b1-%e0%b6%ad%e0%b7%9c%e0%b6%b4%e0%b7%8a%e0%b6%b4%e0%b7%92%e0%b6%ba-piyambana-thoppiya,Writer,"Sybil Wettasinghe",1,1,Publisher,"M.D. Gunasena",1,1,Language,සිංහල,1,1,"No of Pages",10,1,0,ISBN,978-955-21-2460-0,1,0,Illustrator,"Sybil Wettasinghe",1,1,"Story Telling Age","2-4, 4-6",1,1,"Self Reading Age",6-8,1,1,,,,`

Actual Output
`31,simple,,"à¶´à·à¶ºà·à¶¹à¶± à¶­à·à¶´à·à¶´à·à¶º | Piyambana Thoppiya",1,0,visible,"à¶¯à·à·à¶à· à¶à¶à·à¶­à¶»à· à¶¸à·à¶­à·à¶¸à¶ºà·à¶à· à¶à¶©à·à¶§ à¶à·à·à·à¶±à· à¶à·à¶©à¶ºà¶à· à¶¸à·à¶½à¶¯à· à¶à¶­à·à¶­à·. à¶à¶ à¶à¶ºà· à¶à·à·à·à· à¶¯à· à¶à¶­à·à¶­à·. à¶­à¶§à·à¶§à· à¶»à¶­à· à·à·à¶½à· à¶±à·à·à· à¶­à·à¶´à·à¶´à·à¶ºà¶§ à¶à·à·à· à¶à¶© à¶à¶±à·à¶± à¶à¶¸à·à¶»à·à¶ºà·. à¶­à·à¶´à·à¶´à·à¶º à¶¯à·à¶±à· à¶¸à·à¶±à·à· à¶à¶»à¶ºà·à¶¯?",,,,taxable,,1,4,,0,0,0.049,24.5,18,0.2,1,,200,210,"Story Books",,,,,,,,,,,,0,Writer,"Sybil Wettasinghe",1,1,Publisher,"M.D. Gunasena",1,1,Language,à·à·à¶à·à¶½,1,1,"No of Pages",10,1,0,ISBN,978-955-21-2460-0,1,0,Illustrator,"Sybil Wettasinghe",1,1,"Story Telling Age","2-4, 4-6",1,1,"Self Reading Age",6-8,1,1,,,,`

Thank you.

**Comment by datgausaigon** [comment]
Hi, this issue happen in server with PHP 8.2.x installed too.
Thanks
