### ISSUE TITLE
Build process incompatible with latest pnpm

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#32885]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Building from the `release/6.5` branch (as per [instructions here](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets)) is currently failing for us as we're using `pnpm` v7 (latest stable), and the project appears to be locked to an older release (v6.24.2) as per https://github.com/woocommerce/woocommerce/blob/release/6.5/plugins/woocommerce/package.json#L84

### Expected behavior

Build completes as normal.

### Actual behavior

Build errors, and `pnpm install` step cannot be completed:

```
$ nvm install
Found '/Users/lee/sites/wc/wp-content/plugins/woocommerce-repo/.nvmrc' with version <v16>
v16.15.0 is already installed.
Now using node v16.15.0 (npm v8.5.5)
$ nvm use
Found '/Users/lee/sites/wc/wp-content/plugins/woocommerce-repo/.nvmrc' with version <v16>
Now using node v16.15.0 (npm v8.5.5)
$ pnpm install
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/Users/lee/sites/wc/wp-content/plugins/woocommerce-repo/plugins/woocommerce".

Expected version: ^6.24.2
Got: 7.0.0

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

### Steps to reproduce

1. Install pnpm or update to latest stable release
2. Checkout `release/6.5` branch of woocommerce repo
3. Attempt to install following instructions from https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @leewillis77,

We are aware of this issue and will be resolving it soon. We're currently changing a few things about our infrastructure tooling and then we will address this issue.

**Comment by redtux** [comment]
Hi, the following worked for me:

```
git checkout release/6.7
nvm install
nvm use
curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
pnpm install
pnpm -- turbo run build
```

I had the same issue in `trunk` and I also successfully tested the version pinning for pnpm with WC 6.5.

NOTE: I understand that downloading an older release of pnpm might just be a temporary workaround, nevertheless you might consider changing the readme (and the CI/CD docs) accordingly until the dependency issues are fixed in `package.json` and `.nvmrc`.

**Comment by psealock** [comment]
Thanks for the issue @leewillis77, we've now updated to PNPM 7

https://github.com/woocommerce/woocommerce/pull/34661
