### ISSUE TITLE
Clean up Product Task layout experiments

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#32918]
This is a post-launch task for https://github.com/woocommerce/woocommerce/issues/32635.

Once the experiments have completed:

* Remove the experiment logic.
* Deploy the winning variation if required.

**Comment by chihsuan** [comment]
We've deployed the stack layout since it's the winning variation. However, we still need to clean up the code.

**Comment by chihsuan** [comment]
Close. There is already a cleanup task [#131](https://github.com/woocommerce/team-ghidorah/issues/131)
