### ISSUE TITLE
[COT] Propose ways for plugins and extensions to declare compatibility with custom order tables.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32920]
When we rollout, all plugins and extensions will not be compatible with custom order tables, and we should display this to the merchant if they enable COT for a painless experience.

This could be a filter that extensions can use to declare compatibility, or this could be a plugin header field. Note that we may eventually roll our custom tables for products, customers and other entities, so ideally solution here should be extensible to these future enhancements as well.

**Comment by vedanshujain** [comment]
We should also look into ways for plugins to find out whether a feature is implemented or not, and then plugins should have ways to declare support for particular feature.

**Comment by wnolfm** [comment]
For this you could implement something like `wc_add_support()` and `wc_get_support()`, modeled after `add_theme_support()` and `get_theme_support()`. 

Such as: `wc_add_support( 'custom-order-tables', ...$args );`

Just a thought.

**Comment by Konamiman** [comment]
Proposal: p7bje6-4kh-p2

**Comment by rrennick** [comment]
@Konamiman This one could be closed?

**Comment by Konamiman** [comment]
> This one could be closed?

Yes, as we implemented the features engine already.

**Comment by maddisondesigns** [comment]
@Konamiman @rrennick Hi, Just wondering what the solution is here. It's mentioned that the feature has been implemented, but no mention of how plugin developers should actually declare compatibility.

**Comment by rrennick** [comment]
@maddisondesigns You can find that at https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility.

**Comment by maddisondesigns** [comment]
@rrennick Thanks for that link. It's much appreciated
