### ISSUE TITLE
Fatal error: Cannot use Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments as WooCommercePayments because the name is already in use

### ISSUE THREAD

**Issue by brunoheel** [woothemes/woocommerce#32930]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Clean wordpress (5.9.3) install with no plugins**

Fatal error: Cannot use Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments as WooCommercePayments because the name is already in use

![Erro-›-WordPress](https://user-images.githubusercontent.com/831889/167515859-a96ec898-0bab-4e02-9a23-edd49ba333b8.png)

**Comment by ObliviousHarmony** [comment]
I'm closing this in favor of [your other report](https://github.com/woocommerce/woocommerce/issues/32931) since it has testing instructions.
