### ISSUE TITLE
[Enhancement]: Email validation/verification

### ISSUE THREAD

**Issue by glcalabr** [woothemes/woocommerce#32948]
### Describe the solution you'd like

During checkout, when creating an account a customer can put in an incorrect email address, or put in an email that ends in .cm when its supposed to be .com, and the order will go through. 

Have a second field that forces the customer to put in their email address again and verifies that both emails are the same.

### Describe alternatives you've considered

Require that the customer has to put in their email address twice so that the fields can look at each other and verify that the email is put in the same both times. 

### Additional context

Also make it so both of these fields disappear when the customer is logged in. Since the system knows their email address already.

**Comment by ObliviousHarmony** [comment]
Hello @glcalabr,

This request would be more of something that you would implement in a theme. I would suggest looking at the `woocommerce_billing_fields` hook in `WC_Countries::get_address_fields()` to add an `email_validation` field and validating that it matches the email given in `"billing_email"` using the `woocommerce_after_checkout_validation` hook. This is just off the top of my head though and might not work out, but custom code isn't something we offer on GitHub.
