### ISSUE TITLE
Deprecation tags still refer to WooCommerce Admin feature plugin versions

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#32967]
**Is your feature request related to a problem? Please describe.**
Since WooCommerce Admin has been merged into WooCommerce core, deprecation tags and notices refer to versions that don't match the plugin they are in.

For example, `WC_Admin_Note` says deprecated since `1.7.0` referring to the previous WCA version, not the core version number.

**Describe the solution you'd like**
Update deprecation notices to use WC versions instead of WCA versions.  This should most likely point to the version of WooCommerce where these were merged in `6.4.0`.

**Describe alternatives you've considered**
If for some reason versions are important for the deprecation tags, we could alternatively specify the plugin along with the version, but this is less semantic and introduces complexity for little benefit.

**Additional context**

```
/**
 * WC_Admin_Note.
 *
 * @deprecated since 1.7.0, use Note
 */
```

**Comment by chihsuan** [comment]
Hey @joshuatf Thanks for creating this issue! 🙌 

I think we have [a same issue](https://github.com/woocommerce/woocommerce/issues/32410) in Ghidorah backlog and I believe we'll work on it soon.

I'm closing this in favor of it.
