### ISSUE TITLE
[COT] Add column and migration for customer note (currently in post_excerpt)

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#32972]
Currently, the customer provided note on the order (`customer_note`) is stored in the posts table inside the `post_excerpt` column:

https://github.com/woocommerce/woocommerce/blob/82e6e3190346b6bab17c955c8d9c77575946e4e6/plugins/woocommerce/includes/class-wc-order.php#L469-L471

This field is available at checkout time and displayed on the admin too:

<img width="886" alt="Screen Shot 2022-05-11 at 21 46 55" src="https://user-images.githubusercontent.com/184724/167970404-ba68f4aa-3a27-4874-ac1d-53bc02a573c7.png">

<img width="1037" alt="Screen Shot 2022-05-11 at 21 46 43" src="https://user-images.githubusercontent.com/184724/167970416-e29ad913-e9b4-4757-8cdc-ca6ed58d8429.png">

We probably need to add a column to the `wc_orders` table for this field and also account for it in the migration code.

**Comment by seanbelly** [comment]
Looks like an instance of this happening here: 6026665-zd-woothemes

**Comment by jorgeatorres** [comment]
Hi @seanbelly!

This was already implemented in #34477 a while ago but we forgot to close the issue. Also, this had nothing to do with the field being displayed or not during checkout (which is what the ticket is about).

After a quick glance at the ticket, I believe this could be a case of the option `woocommerce_enable_order_comments` set to `no`. This option controls whether the customer note field is displayed or not. AFAIK we don't allow changing this anywhere and it has a default value of `yes` so under normal circumstances, sites should get the customer note field, but maybe it was manually changed on this site via a plugin or theme or something else. As a first step, I'd try to confirm that this option is not set to `no` (maybe via wp-admin/options.php?). If so, it can be either removed or set to `yes`.

If this doesn't help, feel free to reach via woo-devs and we'll take a look.

**Comment by seanbelly** [comment]
Thanks for setting me straight! Much appreciated. I'll swing back with more info if necessary.
