### ISSUE TITLE
Notice: Trying to access array offset on value of type bool in

### ISSUE THREAD

**Issue by braddalton** [woothemes/woocommerce#32985]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the single product pages without product images, i get this :

Notice: Trying to access array offset on value of type bool in /www/daltonwineltd_666/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1578

Notice: Trying to access array offset on value of type bool in /www/daltonwineltd_666/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1579

Notice: Trying to access array offset on value of type bool in /www/daltonwineltd_666/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1580

Notice: Trying to access array offset on value of type bool in /www/daltonwineltd_666/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1581

Notice: Trying to access array offset on value of type bool in /www/daltonwineltd_666/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1590

### Expected behavior

Load without error.

### Actual behavior

Error messages

### Steps to reproduce

When i add a single product image, the error is gone but i don't get any errors locally. But i still get the errors when testing on a fresh install of Twenty Twenty and deactivating all plugins. 

![woo](https://user-images.githubusercontent.com/3328585/168130068-446de80c-a5d6-4249-aff9-0cc41b6c6221.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://braddalton.xyz
Site address (URL): https://braddalton.xyz
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.0
PHP Version: 7.4.25
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
Total Database Size: 5.07MB
Database Data Size: 2.87MB
Database Index Size: 2.20MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_rcp_customers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcp_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcp_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rcp_membershipmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcp_memberships: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcp_membership_counts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcp_payments: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_rcp_payment_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcp_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rcp_subscription_level_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_restrict_content_pro: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 44
custom_css: 2
customize_changeset: 1
listing: 27
nav_menu_item: 22
nf_sub: 2
page: 26
post: 3
product: 9
revision: 19
shop_order: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.6.2
Genesis Connect for WooCommerce: by StudioPress – 1.1.1
WooCommerce: by Automattic – 6.4.1

### Inactive Plugins (10) ###

AgentPress Listings: by StudioPress – 1.3.4
Genesis Blocks: by StudioPress – 1.4.0
New User E-mail Mods: by Brad Dalton - wpsites – 1.1.1
Ninja Forms: by Saturday Drive – 3.6.9
Restrict Content Pro: by iThemes – 3.4.4
Simple Social Icons: by StudioPress – 3.1.0
WordPress Importer: by wordpressdotorg – 0.7
WPForms Lite: by WPForms – 1.7.4.1
WP htaccess Control: by António Andrade – 3.5.1
Yoast SEO: by Team Yoast – 18.8

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #225 - /
Cart: #226 - /cart/
Checkout: #227 - /checkout/
My account: #228 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.9
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 60
Oldest: 2022-05-12 15:20:04 +0000
Newest: 2022-05-12 17:16:53 +0000

### Status report information ###

Generated at: 2022-05-12 17:18:18 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by braddalton** [comment]
Updated from 6.4.1 to 6.5.1 and problem still exists.

**Comment by ObliviousHarmony** [comment]
Hello @braddalton,

Could you please provide some more exhaustive testing instructions so that we can attempt to reproduce this on our end?

**Comment by braddalton** [comment]
I can't reproduce the error locally.

**Comment by braddalton** [comment]
NO idea what caused it apart from this `$data         = json_decode( $woocommerce_products['body'] );` which i've seen on [stackoverflow](https://stackoverflow.com/questions/68392753/woocommerce-illegal-string-offset-body-error-message-issue)

**Comment by ObliviousHarmony** [comment]
@braddalton that StackOverflow link looks unrelated. Unfortunately, if we can't figure out how to reproduce this issue, there isn't really anything our teams can do to resolve it.

**Comment by seothemes** [comment]
This happens when a featured image is set for a product and the image file doesn't exist.

I hit this bug after importing some demo content from an XML file using the WordPress Importer plugin.

The `$full_src` variable needs `isset` checks in case the data isn't available - https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1597

<img width="1280" alt="woocommerce product image missing file error" src="https://user-images.githubusercontent.com/24793388/224634917-5ce4af70-9058-41ba-961e-ce15c6c140ed.png">

**Comment by seothemes** [comment]
@ObliviousHarmony should I submit a new issue or is it possible to reopen this one?

**Comment by seothemes** [comment]
Here's a temporary fix for anyone else running into this issue:

```php
add_filter(
	'wp_get_attachment_image_src',
	fn( $image ): array => $image ? $image : [ '', 0, 0, false ]
);
```

**Comment by Fidgetbg** [comment]
Hello team,

Yesterday and today we’re hiting all limits to our hosting due to same errors on our website: Fidget.bg

We’re using Divi theme + Woocommerce.

Due to these errors we cannot even access our site, neither our customers. 

Can you please assist to sort these issues out?

Mainly the errors are: Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on lines 1600, 1601, 1602, 1612 and repeating almost each minute. 

Please find below the error log:

[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1600
[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1601
[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1602
[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1603
[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1612
[04-Jun-2023 19:00:15 UTC] PHP Warning:  Trying to access array offset on value of type bool in /home/fidgetbg/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1612
[04-Jun-2023 19:00:19 UTC] PHP Warning:  Undefined variable $max_percentage in /home/fidgetbg/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(582) : eval()'d code on line 20
[04-Jun-2023 19:00:19 UTC] PHP Warning:  Undefined variable $max_percentage in /home/fidgetbg/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(582) : eval()'d code on line 20
[04-Jun-2023 19:00:54 UTC] PHP Warning:  Undefined variable $max_percentage in /home/fidgetbg/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(582) : eval()'d code on line 20
[04-Jun-2023 19:05:43 UTC] PHP Warning:  Undefined variable $max_percentage in /home/fidgetbg/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(582) : eval()'d code on line 20
[04-Jun-2023 19:05:43 UTC] PHP Warning:  Undefined variable $max_percentage in /home/fidgetbg/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(582) : eval()'d code on line 20

How to fix them?

Regards,
Nikolay

**Comment by tarsonis123** [comment]
Ok, so what is the underlying issue? In my case the images were imported via stock WP media manager before importing the products. The image links were also correct and no images were missing. So the theory that the cause is a missing image, isnt correct in my case. It must be a different cause in my case. The fix is great but watching it in few months when WC fixes whatever went wrong, one needs to keep an eye on to delete that snippet again as it may cause new issues in the future.

**Comment by tradesouthwest** [comment]
If still open for answers, Woo did not add any conditional checks for empty array indexes. 

Fix

```apply_filters(
			'woocommerce_gallery_image_html_attachment_image_params',
			array(
				'title'                   => _wp_specialchars( get_post_field( 'post_title', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
				'data-caption'            => _wp_specialchars( get_post_field( 'post_excerpt', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
				'data-src'                => (empty($full_src[0] )) ? '' : esc_url( $full_src[0] ),
				'data-large_image'        => (empty($full_src[0] )) ? '' : esc_url( $full_src[0] ),
				'data-large_image_width'  => (empty($full_src[1] )) ? '' : esc_attr( $full_src[1] ),
				'data-large_image_height' => (empty($full_src[2] )) ? '' : esc_attr( $full_src[2] ),
				'class'                   => esc_attr( $main_image ? 'wp-post-image' : '' ),
			),
			$attachment_id,
			$image_size,
			$main_image
		)
	);

	return '<div data-thumb="' 
	. (empty($thumbnail_src[0] )) ? '' : esc_url( $thumbnail_src[0] ) 
	. '" data-thumb-alt="' . esc_attr( $alt_text ) . '" class="woocommerce-product-gallery__image"><a href="' . esc_url( $full_src[0] ) . '">' . $image . '</a></div>';```

**Comment by tradesouthwest** [comment]
That's starts at line 1607 in  /wp-content/plugins/woocommerce/includes/wc-template-functions.php

**Comment by tarsonis123** [comment]
> If still open for answers, Woo did not add any conditional checks for empty array indexes.
> 
> Fix
> 
> ```
> 			'woocommerce_gallery_image_html_attachment_image_params',
> 			array(
> 				'title'                   => _wp_specialchars( get_post_field( 'post_title', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
> 				'data-caption'            => _wp_specialchars( get_post_field( 'post_excerpt', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
> 				'data-src'                => (empty($full_src[0] )) ? '' : esc_url( $full_src[0] ),
> 				'data-large_image'        => (empty($full_src[0] )) ? '' : esc_url( $full_src[0] ),
> 				'data-large_image_width'  => (empty($full_src[1] )) ? '' : esc_attr( $full_src[1] ),
> 				'data-large_image_height' => (empty($full_src[2] )) ? '' : esc_attr( $full_src[2] ),
> 				'class'                   => esc_attr( $main_image ? 'wp-post-image' : '' ),
> 			),
> 			$attachment_id,
> 			$image_size,
> 			$main_image
> 		)
> 	);
> 
> 	return '<div data-thumb="' 
> 	. (empty($thumbnail_src[0] )) ? '' : esc_url( $thumbnail_src[0] ) 
> 	. '" data-thumb-alt="' . esc_attr( $alt_text ) . '" class="woocommerce-product-gallery__image"><a href="' . esc_url( $full_src[0] ) . '">' . $image . '</a></div>';```
> ```

Still getting:
PHP Warning:  Trying to access array offset on value of type bool in /home/customer/www/example/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1632

for:

`	return '<div data-thumb="' . (empty($thumbnail_src[0]) ? '' : esc_url($thumbnail_src[0])) . '" data-thumb-alt="' . esc_attr($alt_text) . '" class="woocommerce-product-gallery__image"><a href="' . esc_url($full_src[0]) . '">' . $image . '</a></div>';`

**Comment by tradesouthwest** [comment]
^and YES! that is the better/doing_it_correctly way of adding the conditionals. Always sanitize. Thanks 4 updating that.

**Comment by tarsonis123** [comment]
Still getting tons of errors with the fix above and latest WooCommerce.
PHP Warning: Trying to access array offset on value of type bool in /home/customer/www/example/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1632

There are no product images missing.. Any other fix?

**Comment by tradesouthwest** [comment]
Try re-uploading the images. they may not be fully registered for some reason. Regenerate thumbnails kind of plugin may help as well.

**Comment by OmarFPG** [comment]
8681202-zen
8617090-zen

**Comment by betayazilim** [comment]
This issue is still happening, right?

**Comment by crawpappy** [comment]
I am seeing this issue as well.
