### ISSUE TITLE
Update 6.5.1 shows as 6.4.1 and requires new update 

### ISSUE THREAD

**Issue by brag-man** [woothemes/woocommerce#33029]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Update 6.5.1 shows as 6.4.1 and requires new update. When I try to update it still shows that an update is required. Have tried across several websites and same result

### Expected behavior

Should update as normal and show latest version when complete

### Actual behavior

Updates to 6.5.1 but does not indicate this and continues to request update from 6.4.1

### Steps to reproduce

1. Update Woocommerce
2. Refresh page after update

### WordPress Environment

No need

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by braddalton** [comment]
I updated 2 sites, 1 local and 1 live from 6.4.1 to 6.5.1 and it now shows 6.5.1

**Comment by brag-man** [comment]
I've updated 4 sites and same happens every time?

**Comment by joashrajin** [comment]
Hi @brag-man 👋

Thanks for the report. I cannot replicate this at all on my end. No update message shows up for me after I finish updating WooCommerce and refresh the page: 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/16253818/168279621-633cdca8-ee4b-4bc3-aa49-dc075eafd942.png">


It will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by ObliviousHarmony** [comment]
Hello @brag-man,

This was a problem with wordpress.org and has been resolved.

**Comment by brag-man** [comment]
Yep. Just re-installed Woocommerce on two of the websites and all seems to be OK now. Thank you Wordpress.
