### ISSUE TITLE
[COT] Rollout: full functionality: enabled for all

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#33021]
Yay!

**Comment by lukecav** [comment]
Is COT going to be enabled for all by default or enabled for all new sites as the default?

Would COT be opt-in on existing sites running WooCommerce?

**Comment by peterfabian** [comment]
We plan to roll it out in stages. At first, it will only be possible to enable it via a filter or in settings, later perhaps as a default for new sites and finally for everyone. 

We will still need to include proactive checks on whether plugins are not doing something they shouldn't.

This task is for future preparation when we'll decide to make it enabled for all. We have tasks also for other stages of deployment (https://github.com/woocommerce/woocommerce/issues/33019, https://github.com/woocommerce/woocommerce/issues/33020). Hope that makes it more clear!

**Comment by barryhughes** [comment]
HPOS is now enabled by default for new stores, with existing stores able to opt in.
