### ISSUE TITLE
[Enhancement]: Hide optional state fields

### ISSUE THREAD

**Issue by Apfelbiss** [woothemes/woocommerce#33033]
### Describe the solution you'd like

Since version 6.3.0 for Germany a state field for billing and shipping is shown in checkout (and cart, if shipping calculator is activated).

As already explained in the [pull request](https://github.com/woocommerce/woocommerce/pull/31825), the state field is not relevant for shipping and billing. This specification is therefore very unusual in German stores and only complicates the ordering process unnecessarily.

For this reason, the following options would be very useful to improve the user experience for customers through a tidy interface:

- On Cart: Only show state field in shipping calculator, if it is relevant because of different shipping zones.
- On Checkout: Add an admin setting to hide optional state field for billing and shipping.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help.

Our team is currently focused on the Cart and Checkout experience powered by blocks, and we only display the state field in the new experience if it's relevant for shipping zones. 

We'll close the issue, as it doesn't fit our current priorities. We'll revisit the list of suggestions like this one once our priorities are updated. Don’t be alarmed if you don’t see any activity on this issue for a while.
