### ISSUE TITLE
json error when posting more than 40 variations

### ISSUE THREAD

**Issue by saidmrn** [woothemes/woocommerce#33042]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i'm using rest api to create variations and it's working as expected when i have less than 40 variations 
the json i'm sending with the variations is valid.
`$woocommerce->post('products/'.$id_prod.'/variations/batch', $data);
`
i'm sending this array with the variations :
https://pastebin.com/gRR5FYnG

i don't know how,but i think the large number of variations is generating the json error
 The variations are being add correctly but generating this error at the response 

### Expected behavior

get the same response body when i send less than 40 variations

### Actual behavior

 Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:411
Stack trace:
#0 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(455): Automattic\WooCommerce\HttpClient\HttpClient-&gt;processResponse()
#1 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient-&gt;request('products/7627/v...', 'POST', Array)
#2 C:\xampp\htdocs\wp-content\plugins\cadastro-produto\cadastrar-produto.php(74): Automattic\WooCommerce\Client-&gt;post('products/7627/v...', Array)
#3 {main}
  thrown in <b>C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php</b> on line <b>411</b><br />

### Steps to reproduce

batch update with 40 variations

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://localhost
Site address (URL): https://localhost
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29
PHP Version: 7.4.29
PHP Post Max Size: 40 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.24-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ O seu servidor não possui a classe SoapClient ativada - alguns plugins de sistemas de pagamento que usam SOAP podem não funcionar como esperado.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
Tamanho total do banco de dados: 34.34MB
Tamanho dos dados do banco de dados: 23.54MB
Tamanho do índice do banco de dado: 10.80MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 1.52MB + Índex: 1.03MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 1.52MB + Índex: 0.53MB + mecanismo InnoDB
wp_aioseo_cache: Dados: 0.08MB + Índex: 0.03MB + mecanismo InnoDB
wp_aioseo_notifications: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_aioseo_posts: Dados: 0.09MB + Índex: 0.02MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_e_events: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_litespeed_url: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_litespeed_url_file: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_options: Dados: 4.34MB + Índex: 0.17MB + mecanismo InnoDB
wp_postmeta: Dados: 7.50MB + Índex: 6.03MB + mecanismo InnoDB
wp_posts: Dados: 6.39MB + Índex: 0.58MB + mecanismo InnoDB
wp_revslider_css: Dados: 0.13MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_css_bkp: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_layer_animations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_revslider_layer_animations_bkp: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_revslider_navigations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_revslider_navigations_bkp: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_revslider_sliders: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_sliders_bkp: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_slides: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_slides_bkp: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_static_slides: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_revslider_static_slides_bkp: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_termmeta: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.22MB + Índex: 0.17MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 0.33MB + Índex: 0.31MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.25MB + Índex: 0.50MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wpforms_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_yith_wcwl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yith_wcwl_lists: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 461
custom_css: 1
customize_changeset: 9
elementor_library: 1
flamingo_contact: 2
flamingo_inbound: 1
nav_menu_item: 28
page: 28
post: 13
product: 147
product_variation: 2182
revision: 40
wp-rest-api-log: 295
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Query Monitor: por John Blackbourn – 3.9.0
JSON Basic Authentication: por WordPress API Team – 0.1
Hostinger: por Hostinger – 1.0
WP REST API: por WP REST API Team – 2.0-beta15
All in One SEO: por Equipe All in One SEO – 4.1.10
All-in-One WP Migration: por ServMask – 7.58
botao-medidas: por Said – 1.0.0
Contact Form 7: por Takayuki Miyoshi – 5.5.6
Elementor: por Elementor.com – 3.6.4
Flamingo: por Takayuki Miyoshi – 2.2.3
Google Analytics for WordPress by MonsterInsights: por MonsterInsights – 8.5.0
Insert Headers and Footers: por WPBeginner – 1.6.0
WPBakery: por Michael M - WPBakery.com – 6.8.0
Kirki Customizer Framework: por David Vongries – 4.0.23
LiteSpeed Cache: por LiteSpeed Technologies – 4.6
Loco Translate: por Tim Whitlock – 2.6.1
Martfury Addons: por DrFuri – 2.4.6
Melhor Envio: por Melhor Envio – 2.11.9
Meta Box: por MetaBox.io – 5.6.3
OptinMonster: por OptinMonster Popup Builder Team – 2.6.12
Slider Revolution: por ThemePunch – 6.5.14
Sincronizar-estoque: por Said – 1.0.0
Soo Demo Importer: por SooThemes – 2.2
Duplicate Variations for WooCommerce: por Emran Ahmed – 2.0.2
WCBoost - Variation Swatches: por WCBoost – 1.0.10
Integração da Rede para WooCommerce: por MarcosAlexandre – 2.1.1
Additional Variation Images Gallery for WooCommerce: por Emran Ahmed – 1.3.1
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2
WooCommerce: por Automattic – 6.4.1 (atualização para a versão 6.5.1 está disponível)
REST API Log: por Pete Nelson – 1.6.8
WPForms Lite: por WPForms – 1.7.3
YITH WooCommerce Compare: por YITH – 2.13.0
YITH WooCommerce Wishlist: por YITH – 3.8.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: por Automattic – 4.2.2
Hello Dolly: por Matt Mullenweg – 1.7.2
JWT Authentication for WP-API: por Enrique Chavez – 1.2.6

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #5 - /shop/
Carrinho: #6 - /cart/
Finalização de compra: #7 - /checkout/
Minha conta: #8 - /my-account/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Martfury
Version: 2.8.0
Author URL: http://demo2.drfuri.com
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: martfury/woocommerce/cart\cart-shipping.php
martfury/woocommerce/cart\cart-totals.php
martfury/woocommerce/cart\cart.php
martfury/woocommerce/cart\mini-cart.php
martfury/woocommerce/checkout\form-checkout.php
martfury/woocommerce/checkout\form-coupon.php
martfury/woocommerce/checkout\form-login.php
martfury/woocommerce/checkout\terms.php
martfury/woocommerce/content-product.php
martfury/woocommerce/content-single-product.php
martfury/woocommerce/content-widget-product.php
martfury/woocommerce/global\form-login.php
martfury/woocommerce/global\quantity-input.php
martfury/woocommerce/global\wrapper-end.php
martfury/woocommerce/global\wrapper-start.php
martfury/woocommerce/loop\add-to-cart.php
martfury/woocommerce/loop\orderby.php
martfury/woocommerce/loop\pagination.php
martfury/woocommerce/myaccount\form-login.php
martfury/woocommerce/myaccount\form-lost-password.php
martfury/woocommerce/myaccount\my-address.php
martfury/woocommerce/single-product\add-to-cart\external.php
martfury/woocommerce/single-product\add-to-cart\simple.php
martfury/woocommerce/single-product\add-to-cart\variable.php
martfury/woocommerce/single-product\meta.php
martfury/woocommerce/single-product\product-image.php
martfury/woocommerce/single-product\product-thumbnails.php
martfury/woocommerce/single-product\rating.php
martfury/woocommerce/single-product\related.php
martfury/woocommerce/single-product\review-meta.php
martfury/woocommerce/single-product\stock.php
martfury/woocommerce/single-product\tabs\tabs.php
martfury/woocommerce/single-product\up-sells.php
martfury/woocommerce/single-product-reviews.php

### Action Scheduler ###

Concluído: 3.190
Oldest: 2022-04-22 11:03:31 -0300
Newest: 2022-05-14 15:21:29 -0300

Pendente: 5
Oldest: 2022-05-14 15:29:47 -0300
Newest: 2022-05-19 09:46:17 -0300

### Status report information ###

Generated at: 2022-05-14 15:26:12 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @saidmrn, thanks for your report. We need some more information in order to troubleshoot this:

1. The `$data` that you are supplying to `$woocommerce->post` is the object you posted as is, or is it a JSON string? If it's the later could you please post the original JSON string?

2. The JSON error might be caused by the request returning an error message that the HTTP handler is trying to interpret as JSON. Would you be able to run your request into a try-catch block like in the following example? That would give us more details about the actual error:

```php
try {
$woocommerce->post('products/'.$id_prod.'/variations/batch', $data);
} catch (HttpClientException $e) {
  echo '<pre><code>' . print_r($e->getMessage(), true) . '</code><pre>'; // Error message.
  echo '<pre><code>' . print_r($e->getRequest(), true) . '</code><pre>'; // Last request data.
  echo '<pre><code>' . print_r($e->getResponse(), true) . '</code><pre>'; // Last response data.
}
```

**Comment by saidmrn** [comment]
Hello,i can't reproduce the error anymore.
Tested again today after reinstalling everything and it is working.
Thanks for the support.
