### ISSUE TITLE
Wrong Description In Payments Settings when WCPay is Installed but not Set up yet

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33056]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Description of WCPay is too short

### Expected behavior

In this state we should be displaying the full copy with T&C and Privacy Policy. 

`Payments made simple, with no monthly fees – designed exclusively for WooCommerce stores. Accept credit cards, debit cards, and other popular payment methods.

By using WooCommerce Payments you agree to be bound by our Terms of Service  and acknowledge that you have read our Privacy Policy `
<img width="1237" alt="Screenshot 2022-05-16 at 10 05 27" src="https://user-images.githubusercontent.com/94967682/168558031-2389986c-e0a8-4848-a6dc-d1547a4fb887.png">

### Actual behavior

Should be this: 
<img width="1449" alt="Screenshot 2022-05-16 at 10 06 34" src="https://user-images.githubusercontent.com/94967682/168558279-80d71c83-f0bc-4b52-ae49-0204be6b6758.png">

### Steps to reproduce

Instructions to trigger the banner are [described here](https://woostartp2.wordpress.com/2022/05/13/call-for-testing-payments-banner-in-settings/).

### WordPress Environment

Version 5.9.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rogermattic** [comment]
+ @ilyasfoo @pmcpinto @adrianduffell

**Comment by chihsuan** [comment]
Reopen.  We still need to update the "description" in payment settings.

p1652739018438239/1652708657.130679-slack-C01SFMVEYAK
