### ISSUE TITLE
Clicking on the `Set up` CTA in Payments Settings should skip the Payments Welcome Screen

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33055]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Clicking on the WooCommerce Payments `Set up` button takes user to the Payments Welcome screen instead entering the setup straight away

### Expected behavior

User's already been introduced to WCPay so they don't need to see the Payments Welcome screen again. As described in the design, it should go directly to the country / business structure step. 
![Uploading Screenshot 2022-05-16 at 10.01.21.png…]()

### Actual behavior

In the `treatment` [version of the experiment](https://woostartp2.wordpress.com/2022/05/13/call-for-testing-payments-banner-in-settings/) (when the banner is displayed)
<img width="757" alt="Screenshot 2022-05-16 at 09 55 53" src="https://user-images.githubusercontent.com/94967682/168556824-ae0375d2-0a66-4bc8-9480-059f73ca6867.png">

clicking on the WooCommerce Payments `Set up` button takes you to the Payments Welcome screen.
<img width="2341" alt="Screenshot 2022-05-16 at 09 57 57" src="https://user-images.githubusercontent.com/94967682/168556780-bb892ce6-2ab0-4780-91d8-a8b1f5e5c919.png">

### Steps to reproduce

Instructions to trigger the banner are [described here](https://woostartp2.wordpress.com/2022/05/13/call-for-testing-payments-banner-in-settings/).

### WordPress Environment

Version 5.9.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rogermattic** [comment]
+ @ilyasfoo @pmcpinto @adrianduffell

**Comment by ilyasfoo** [comment]
Hi @rogermattic, by saying "Set up" button, do you mean the "Get started" button in the WCPay banner?

If you meant the "Set up" button in the payments table below the banner, it's actually a different part of the code, not modified by our experiment yet.

**Comment by chihsuan** [comment]
> by saying "Set up" button, do you mean the "Get started" button in the WCPay banner?

> If you meant the "Set up" button in the payments table below the banner, it's actually a different part of the code, not modified by our experiment yet.

@ilyasfoo Thanks. I've confirmed this.  "Get started" and "Set up" buttons should link to the same page.

![Screen Shot 2022-05-18 at 10 00 02](https://user-images.githubusercontent.com/4344253/168941758-75efa180-5d6d-48bb-8b56-2b69b111f18b.png)

figma: e428PXC0QyEwYqtX48lLq0-fi-3%3A47
