### ISSUE TITLE
Store Setup - Sample Products

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#33061]
**User story:**
As a new merchant, I want to import sample products related to my industry, so that I can preview my store before my products are ready to add.

**Design overview**
cJQeyyhx9PraQrY3YAtCGM-fi-1517%3A156861

Here you can find the images and the author for the following industries:
- Clothing and accessories
 
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/98944206/168595164-ecd8426e-0afc-46f0-9eb5-af263d34ccf5.png">

- Beauty and health

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/98944206/168594976-55bdea20-5d64-4f8a-a5c1-9b4240fa116d.png">

- Electronics and computers

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/98944206/168595101-8bd4db37-edda-4cde-9db1-107739f225bb.png">

- Food and drinks

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/98944206/168595045-07bb62d7-3b2e-441c-b875-a73dd051a860.png">

**Acceptance criteria**

For each vertical:
- [ ] New sample data file
- [ ] 12 products in file
- [ ] Products have generic names/description but realistic data for price/weight/stock/etc
- [ ] Product photos are sourced from CC0-licensed images on Pexels
- [ ] Product photos are credited in the product description.
- [ ] Product photos are hosted from https://woocommercecore.mystagingwebsite.com/

**Comment by ilyasfoo** [comment]
Hey, @verofasulo! Do you think this is still desirable? Otherwise we could close the issue

**Comment by chihsuan** [comment]
Closing this as we already added fashion sample products in https://github.com/woocommerce/woocommerce/pull/32977
