### ISSUE TITLE
Inbox note backend accepts unsupported banner layout 

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#33067]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Admin's inbox note frontend currently only accepts `thumbnail` layout for images: https://github.com/woocommerce/woocommerce/blob/02ef6c534e6cefbc935731df5a0eb0b55867d8a5/packages/js/experimental/src/inbox-note/inbox-note.tsx#L161

However, our backend code seems to accept `banner`: https://github.com/woocommerce/woocommerce/blob/02ef6c534e6cefbc935731df5a0eb0b55867d8a5/plugins/woocommerce/src/Admin/Notes/Note.php#L581

We should remove banner since it's wont be functional in frontend.

**Comment by adrianduffell** [comment]
From the code, it looks like a banner image would be rendered as a thumbnail? I'd imagine that could be a messy looking image in some cases.

I think it would be good to also create developer advisory on the WooCommerce blog about this, and give suggested steps to update existing notes to the thumbnail format.

**Comment by chihsuan** [comment]
We will deprecate unsupported Inbox note banner layout in 9.4. I'll create another task to remove this in 9.5.
