### ISSUE TITLE
[Enhancement]: add hooks to ReserveStock so that user can select to enable/disable feature

### ISSUE THREAD

**Issue by ykawato** [woothemes/woocommerce#33070]
### Describe the solution you'd like

in src/Checkout/Helpers/ReserveStock.php 
ReserveStock is enabled for woocommerce_schema_version > 430.

However, ReserveStock requires you to save product stock info in specified table  {$wpdb->wc_reserved_stock}.
We are trying to customize this stock quantity feature selectively. For example, control stock quantity by date, user, etc. for specific products.

### Describe alternatives you've considered

I have tried the following:
- force woocommerce_schema_version to be less than 430. 
This will disable other woocommerce's new features, which we do not want.
- change woocommerce_hold_stock_minutes to 0
This will disable stock for all products.

**Comment by ObliviousHarmony** [comment]
Hello @ykawato,

One option would be to use the `woocommerce_hold_stock_for_checkout` filter to disable the `ReserveStock` functionality and then implement your own stock reservation functionality.

**Comment by bd-viget** [comment]
This did not resolve the issue for me. When the item is added to the cart, it is always inserted into the `reserved_stock` table with a 10min expiration (and this value is unfilterable).

The only way I was able to bypass this was by filtering the query that inserts the `reserved_stock` product/quantity.

```php
add_filter(
	'query',
	function ( string $query ): string {
		global $wpdb;
		if ( ! str_contains( $query, $wpdb->wc_reserved_stock ) || ! str_contains( $query, 'INSERT INTO' ) ) {
			return $query;
		}

		return 'SELECT 1';
	}
);
```
