### ISSUE TITLE
[COT] Consider Back-Compat Issues

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#33094]
(Logged following a team discussion) as we make further progress, we should pro-actively consider potential backwards-compatibility concerns.

For example, we're building alternative implementations of the existing admin list table and order editor which will mimic the existing implementations in many ways: we want a high degree of compatibility, but might this create issues for extensions that are already deeply integrated here?

Let's consider possible scenarios (though the above example mentions the admin UI, this issue is more general in nature than that) and think about mitigation strategies. 

Expected output is one or more RFCs.

**Comment by barryhughes** [comment]
When addressing this, please also be sure to look at the following internal conversation (re REST API, but also actions and filters relating to post objects more generally): p1668592182746839-slack-C0E1AV8T0

**Comment by jorgeatorres** [comment]
This probably made a lot of sense a while ago when we were in the planning stages, but it seems to me this has been addressed organically in other ways. So far we haven't had any reports of backwards compatibility issues that would require us to do new research (or RFCs). Feel free to re-open if I'm missing something @barryhughes!

**Comment by barryhughes** [comment]
Nope, I agree: this was logged at a much earlier stage, I don't think there's any need for it now. Thank you!
