### ISSUE TITLE
[Enhancement]: Instructions for configuring a Downloadable file (with tutorial active) 

### ISSUE THREAD

**Issue by AashikP** [woothemes/woocommerce#33107]
### Describe the solution you'd like

* As of now, this is what we see when we try to create a product during new product flow: `&wc_onboarding_active_task=products&tutorial=true` -> https://d.pr/i/V1xCQM
* Notice that there are no instructions for the downloadable file itself

    ![image](https://user-images.githubusercontent.com/17475174/169206987-2c64935f-ca31-4e9a-8775-96007906d504.png)

The tour/tutorial/tips should include details about the downloadable files and configuring them along with details about the other product configuration options

### Describe alternatives you've considered

N/A

### Additional context

Moved from internal discussion: pbIJXs-1Qb-p2#comment-3923

**Comment by chihsuan** [comment]
Closing this since we've introduced a new product tutorial.

![Screenshot 2023-03-30 at 18 41 56](https://user-images.githubusercontent.com/4344253/228811760-a5d8b2f7-3ab8-4215-b0b3-e2254870b9bd.png)
