### ISSUE TITLE
[Enhancement]: Add filter to woocommerce_cart_item_required_stock_is_not_enough error message

### ISSUE THREAD

**Issue by Dekadinious** [woothemes/woocommerce#33114]
### Describe the solution you'd like

It is not possible to filter messages in the function `check_cart_item_stock()` inside class-wc-cart.php. Other error messages are filterable in the function `add_to_cart()`. There shouldn't be a reason that the exact same error message types cannot be filtered in another function.

To change this:

`$error->add( 'out-of-stock', sprintf( __( 'Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused.', 'woocommerce' ), $product->get_name(), wc_format_stock_quantity_for_display( $product->get_stock_quantity() - $held_stock, $product ) ) );`

I have to hook into `woocommerce_check_cart_items` and get the notices from the session, and do a strpos-check to determine if I have the correct notice. It's prone to errors and should not be needed.

### Describe alternatives you've considered

Add filters.

### Additional context

The same goes for error messages that get thrown as ReserveStockException in ReserveStock.php and RouteException in CartController. It's confusing to have so many similar or identical error messages, where only some are filterable some of the time.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help.

Our team is currently focused on the Cart and Checkout experience powered by blocks. We'll close the issue, as improving the shortcodes doesn't fit our current priorities. Take a look at the [extensibility options](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility) available in the Cart and Checkout blocks and make a request in our [GitHub repository](https://github.com/woocommerce/woocommerce-blocks/issues/new/choose) in case you need a new extensibility point or component/utility.
