### ISSUE TITLE
[Enhancement]: How about "Ward, District" in wp_wc_order_addresses

### ISSUE THREAD

**Issue by datgausaigon** [woothemes/woocommerce#33116]
### Describe the solution you'd like

Hi, 
The next big update we have wp_wc_order_addresses. But the structure of this table still only have:

- address_1
- address_2
- city
- state
- postcode
- country

How about some country on the world have "Ward, District". And they must be use "Ward, District" on payment/shipping info?

Can you add Ward, District Field for wp_wc_order_addresses in next update too?

Thanks

**Comment by psealock** [comment]
Which country has these fields please?

**Comment by datgausaigon** [comment]
@psealock Vietnam

**Comment by vedanshujain** [comment]
Hey @datverse, generally, we would use the `state` field for the province and the `city` field for the district. Will this work for your use case?

**Comment by datgausaigon** [comment]
Hi @vedanshujain 
Thanks for your reply. How about "Country-Cities-Districts-Wards" in my case? In my case:

Country have many Cities
City have many Districts 
District have many Wards

-- Country
--- City
---- District
----- Ward

Thanks

**Comment by vedanshujain** [comment]
@datverse , thanks for the explanation. So adding a new field in checkout from WC Core is bit heavy handed, as then all themes, checkout plugins etc would need to account for it.

I recommend that you take advantage of [customising the checkout fields blog](https://woocommerce.com/posts/customize-checkout-fields-woocommerce/) which list several ways from free code snippets to paid plugins to achieve this. I am going to close this as won't fix for now, but feel free to respond if you think there is a good argument for why this should be included in WC core.
