### ISSUE TITLE
The `wcadmin_settings_change` Tracks event isn't being logged correctly for `settings: woocommerce_navigation_enabled`

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#33128]
### Describe the bug

When the Navigation feature is toggled in Settings, the `wcadmin_settings_change` Tracks event is supposed to be logged with `settings: woocommerce-navigation_enabled`.

![Screenshot%20on%202022-05-19%20at%2012%3A26%3A14](https://user-images.githubusercontent.com/2098816/169427850-b34dd5da-f96f-47dc-a448-bdeeffc4db28.png)
 
However, looking at our analytics, this does not appear to be working correctly.

The Tracks event introduced when the user enables/disables the navigation (
WooCommerce - Settings - Advanced - Features) is broken. This event should be fixed in order to understand how many users are enabling or disabling the navigation. And the same should be applied to the analytics feature.

### Expected behavior

The `wcadmin_settings_change` Tracks event is supposed to be logged with `settings: woocommerce-navigation_enabled`.

### Actual behavior

The `wcadmin_settings_change` Tracks event is not being logged with `settings: woocommerce-navigation_enabled`

### Acceptance criteria

- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_navigation_enabled) when the user enables the navigation
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_navigation_disabled) when the user disables the navigation
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_analytics_enabled) when the user enables analytics
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_analytics_disabled) when the user disables analytics

### References

- Slack thread: p1652965397899679-slack-C01CMSA1VHS

**Comment by AnnaMag** [comment]
Just to add that the same applies to the` _analytics_ `setting.
