### ISSUE TITLE
Remove enable navigation note

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33144]
**Description:** we already have enough people using the new navigation to extract valuable learnings. We can remove for now the Inbox notification about the new navigation

**Acceptance criteria:**
- [ ] Remove Inbox note with the title "You now have access to the WooCommerce navigation”

**Comment by pmcpinto** [comment]
@mattsherman is it possible to include this in cycle 26? I think this was forgotten in the previous cycle. Thanks

**Comment by mattsherman** [comment]
@pmcpinto This was implemented in the previous cycle, in https://github.com/woocommerce/woocommerce/pull/33241
