### ISSUE TITLE
[Enhancement]: More feedback on progress in Setup Wizard when installing recommended business features

### ISSUE THREAD

**Issue by j19sch** [woothemes/woocommerce#33150]
### Describe the solution you'd like

In the Setup Wizard, depending on the store's country, you can install up to 5 recommended business features: WooCommerce Payments, WooCommerce Shipping, WooCommerce Tax, MailPoet, and Google Listings and Adds. As these are installed, the only feedback you get from the page on the progress of installation, is that the "Continue"-button shows an animation. Once the installation is done, the Theme-page of the Wizard is shown with in the bottom-left a dark grey box saying "Plugins were successfully activated".

Although installing the plugins does not seem to take extremely long (12-15 seconds the two times I timed it), it would be nice to get more feedback on the progress as these plugins are installed.

**Comment by adrianduffell** [comment]
Hi @j19sch, thanks for creating this issue and sharing the idea. We'll consider it in an upcoming release cycle.

**Comment by chihsuan** [comment]
Closing this since the OBW will be replaced by Core Profiler in WC 7.9 and there is a new loading screen for installation progress.
