### ISSUE TITLE
Add Event Tracking for Product Page Spotlight Tour

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#33160]
## User Story
>  As a product owner, I want to telemetry on the Product Page Spotlight Tour, so that I can make informed decisions about this feature.

## Acceptance criteria

Create tracks to enable the reporting of:

* % of users that clicks on "Enable interactive walkthrough"
*  % of users that complete the guided mode without dismissing it
*  % of users that clicks on "Skip guided mode"
*  Which steps the user complete by adding information

**Comment by ilyasfoo** [comment]
We should add all tracks for both old walkthrough and spotlight to start tracking performance of both.

**Comment by ilyasfoo** [comment]
Hi @pmcpinto, can you confirm the following tracks:

>% of users that clicks on "Enable interactive walkthrough" (Unavailable for old walkthrough)

`wcadmin_walkthrough_product_enable_button_click`

> % of users who views product walkthrough

`wcadmin_walkthrough_product_view`:
- `spotlight`: `yes/no`

>% of users that complete the guided mode without dismissing it

`wcadmin_walkthrough_product_completed`

>% of users that clicks on "Skip guided mode"

`wcadmin_walkthrough_product_dismissed`

>Which steps the user complete by adding information

I need to clarify when does this track trigger? Is it immediately after user types something, or when user clicks on "Next"?

`wcadmin_walkthrough_product_step_completed`:
- `step_name`

**Comment by pmcpinto** [comment]
> I need to clarify when does this track trigger? Is it immediately after user types something, or when user clicks on "Next"?

I think we should fire it when the user clicks on "Next".

> wcadmin_walkthrough_product_dismissed

It would also be useful to track when the user clicks on "X" to dismiss the tour and the step where it happened.

The rest looks good to me. Thanks!

**Comment by ilyasfoo** [comment]
Sounds good!

>It would also be useful to track when the user clicks on "X" to dismiss the tour and the step where it happened.

We'll add a `step_name` and `added_info`: `yes/no` prop to it
