### ISSUE TITLE
[COT] Research locking for order edits

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#33173]
From a comment in [#33026](https://github.com/woocommerce/woocommerce/pull/33026#discussion_r879165631):

> I wonder if we were to implement locking sometime in the future, should we add a provision in the DB schema itself right now? Maybe at least an edit lock column.

The output of this issue should be a document detailing possible race conditions, and what can we do in the DB structure to address them (even if we don't implement them now).

**Comment by psealock** [comment]
Hi @jorgeatorres could you just add a `status: ...` label to this so its properly classified? Cheers!

**Comment by vedanshujain** [comment]
Closing in favor of #38230
