### ISSUE TITLE
WooCommerce Plugin is giving my Wordpress front end redirecting problems

### ISSUE THREAD

**Issue by dropdps** [woothemes/woocommerce#33175]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With WooCommerce's plugin activated, the front end is giving me this message
![Screenshot (156)](https://user-images.githubusercontent.com/106162024/170042095-12178e51-6f74-499a-ba27-20995ba5f84d.png)
I know it's WC because if i deactivate it there isn't this problem but obviously i need WC.
I've tried to reinstall the penultimate version or rename the file woocommerce but it doesn't work.
Help

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://dropdps.com
Site address (URL): http://dropdps.com
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1n-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: eyu_
Total Database Size: 71.79MB
Database Data Size: 67.75MB
Database Index Size: 4.04MB
eyu_woocommerce_sessions: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
eyu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eyu_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eyu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_actionscheduler_actions: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
eyu_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
eyu_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
eyu_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
eyu_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
eyu_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
eyu_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
eyu_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_newsletter_templates: Data: 4.06MB + Index: 0.00MB + Engine InnoDB
eyu_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
eyu_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eyu_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
eyu_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_options: Data: 4.05MB + Index: 0.08MB + Engine InnoDB
eyu_postmeta: Data: 35.33MB + Index: 0.53MB + Engine InnoDB
eyu_posts: Data: 20.41MB + Index: 0.20MB + Engine InnoDB
eyu_sgs_log_events: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
eyu_sgs_log_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
eyu_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
eyu_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
eyu_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
eyu_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
eyu_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eyu_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eyu_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 176
cookielawinfo: 6
elementor_library: 22
mailpoet_page: 1
nav_menu_item: 11
page: 10
post: 1
product: 56
revision: 1045
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.4
Elementor Pro: by Elementor.com – 3.7.1
Elementor: by Elementor.com – 3.6.5
Google Listings and Ads: by WooCommerce – 1.13.1
Cookie and Consent Solution for the GDPR & ePrivacy: by iubenda – 3.0.0
Jetpack: by Automattic – 10.9.1
MailPoet 3 (New): by MailPoet – 3.89.3
SiteGround Optimizer: by SiteGround – 7.1.1
SiteGround Security: by SiteGround – 1.2.8
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.1
WooCommerce Payments: by Automattic – 4.1.0
WooCommerce: by Automattic – 6.5.1
WooLentor - WooCommerce Elementor Addons + Builder: by HasThemes – 2.2.9
SiteGround Central: by SiteGround – 2.0.4

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #172 - /digital-products/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #35 - /my-account/
Terms and conditions: #1380 - /terms-conditions/

### Theme ###

Name: Hello Elementor Child
Version: (update to version 0 is available)
Author URL: 
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Payments ###

Version: 4.1.0
Connected to WPCOM: Yes
Blog ID: 204424034
Account ID: acct_1Khgmz2EL88R3nPA

### Action Scheduler ###

Canceled: 1
Oldest: 2022-05-23 16:29:38 +0000
Newest: 2022-05-23 16:29:38 +0000

Complete: 268
Oldest: 2022-04-23 22:59:30 +0000
Newest: 2022-05-24 12:48:54 +0000

Pending: 1
Oldest: 2022-05-25 01:04:28 +0000
Newest: 2022-05-25 01:04:28 +0000

### Status report information ###

Generated at: 2022-05-24 13:16:32 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Have you tried deactivating all other plugins to see if the problem persists?

**Comment by dropdps** [comment]
I already solved the problem, thank you!
