### ISSUE TITLE
error when adding or editing a product

### ISSUE THREAD

**Issue by derridHeidegger** [woothemes/woocommerce#33174]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

if you have a post template, or you create a post template from the editor, when you try to edit or add a product you get this error:

Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in C:\xampp\htdocs\boo\wp-content\plugins\woocommerce\includes\admin\class-wc-admin-meta-boxes.php:283 Stack trace: #0 C:\xampp\htdocs\boo\wp-content\plugins\woocommerce\includes\admin\class-wc-admin-meta-boxes.php(283): in_array('product', NULL) #1 C:\xampp\htdocs\boo\wp-includes\class-wp-hook.php(309): WC_Admin_Meta_Boxes->remove_block_templates(Array) #2 C:\xampp\htdocs\boo\wp-includes\plugin.php(189): WP_Hook->apply_filters(Array, Array) #3 C:\xampp\htdocs\boo\wp-includes\class-wp-theme.php(1334): apply_filters('theme_product_t...', Array, Object(WP_Theme), Object(WP_Post), 'product') #4 C:\xampp\htdocs\boo\wp-admin\includes\theme.php(145): WP_Theme->get_page_templates(Object(WP_Post), 'product') #5 C:\xampp\htdocs\boo\wp-admin\includes\meta-boxes.php(1504): get_page_templates(Object(WP_Post)) #6 C:\xampp\htdocs\boo\wp-admin\edit-form-advanced.php(271): register_and_do_post_meta_boxes(Object(WP_Post)) #7 C:\xampp\htdocs\boo\wp-admin\post-new.php(75): require('C:\\xampp\\htdocs...') #8 {main} thrown in C:\xampp\htdocs\boo\wp-content\plugins\woocommerce\includes\admin\class-wc-admin-meta-boxes.php on line 283

the code in the meta boxes, not checking if it is an array, or cast it to array. 
if you then delete the template it works again. by the way in the support of the plugin other people got the same error.

### Expected behavior

there should be a better if statment and cast it to array, then the error will be avoided.

### Actual behavior

a fatal error

### Steps to reproduce

1- i have twenty twenty two theme
2 - enter a post and create a template from the editor
3- then go to add or edit a product

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/boo
Site address (URL): http://localhost/boo
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.5
PHP Version: 8.1.5
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.24-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ מחלקת SoapClient אינה פעילה בשרת - שיטות תשלום המשתמשות ב-SOAP עשויות לא לעבוד כמצופה.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
הגודל הכולל של בסיס הנתונים: 4.54MB
גודל הנתונים של בסיס הנתונים: 3.07MB
גודל האינדקס של בסיס הנתונים: 1.47MB
wp_woocommerce_sessions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_attribute_taxonomies: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_downloadable_product_permissions: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_woocommerce_order_items: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_order_itemmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_tax_rates: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_woocommerce_tax_rate_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zones: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_shipping_zone_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zone_methods: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_payment_tokens: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_payment_tokenmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_log: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_actions: נתונים: 0.02MB + אינדקס: 0.11MB + מנוע InnoDB
wp_actionscheduler_claims: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_groups: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_logs: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_commentmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_comments: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_options: נתונים: 2.03MB + אינדקס: 0.03MB + מנוע InnoDB
wp_postmeta: נתונים: 0.09MB + אינדקס: 0.06MB + מנוע InnoDB
wp_posts: נתונים: 0.06MB + אינדקס: 0.06MB + מנוע InnoDB
wp_termmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_terms: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_term_relationships: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_term_taxonomy: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_usermeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_users: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_wc_admin_notes: נתונים: 0.05MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_admin_note_actions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_category_lookup: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_customer_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_download_log: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_order_coupon_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_order_product_lookup: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_wc_order_stats: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_wc_order_tax_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_product_attributes_lookup: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_product_download_directories: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_product_meta_lookup: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_wc_rate_limits: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_reserved_stock: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_tax_rate_classes: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_webhooks: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 20
product_variation: 7
revision: 6
wp_global_styles: 2
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					החנות לא משתמשת בHTTPS. מידע נוסף על HTTPS ותעודות SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

ווקומרס: מאת חברת אוטומטיק – 6.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

בסיס חנות: #8 - /shop/
סל קניות: #9 - /cart/
תשלום: #10 - /checkout/
החשבון שלי: #11 - /my-account/
תנאי שימוש: ❌ דף לא מוגדר

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

הושלם: 39
Oldest: 2022-05-17 10:57:48 +0300
Newest: 2022-05-24 09:13:31 +0300

### Status report information ###

Generated at: 2022-05-24 16:19:10 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the report @derridHeidegger. This is a duplicate issue to https://github.com/woocommerce/woocommerce/issues/33179, which is currently being worked on. So I will close this in favour of that one.
