### ISSUE TITLE
Analytics shows blank pages + Undefined property in stdClass::$net_sales

### ISSUE THREAD

**Issue by tradesouthwest** [woothemes/woocommerce#33181]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All pages blank under Analytics menu [https://prnt.sc/hrQ1YjY8OrKz](https://prnt.sc/hrQ1YjY8OrKz) 

Error in wp-admin Dashboard Woocommerce Status widget "Undefined property in stdClass::$net_sales in .../admin/class-wc-admin-dashboard.php on line 155" [https://prnt.sc/ijaZF-AiFjX8](https://prnt.sc/ijaZF-AiFjX8)

Issues occurred after updating to WC 6.5.1 (yesterday).
 

### Expected behavior

Visible fields or content in analytics pages.

### Actual behavior

Pages blank in Analytics section... ALL pages!

Error unknown.

Also WC adds Custom fields to every Woo Product called sf_attachments and total_sales without my knowledge. It would be nice to NOT have additional database fields such as these custom fields. AND the ability to remove or turn off these custom fields. 

As well as turn off Analytics completely.

### Steps to reproduce

1. Go To: wp-admin > MenuItem > Analytics > [any sub item]
2. View pages

1a. Go To: wp-admin > Dashboard
2a. Read error in Woo Status Dashboard Widget

### WordPress Environment

[WCStatusReport-May241010AM.txt](https://github.com/woocommerce/woocommerce/files/8764884/WCStatusReport-May241010AM.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi I had a look with a fresh site and WC 6.5.1 did not produce an error in Analytics pages. Is there a JS error in the console?

You can turn off Analytics in WooCommerce > Settings > Advanced > Features

![image](https://user-images.githubusercontent.com/1922453/170181654-dbb7a2de-edee-4a9d-9b2a-19a9928216af.png)
