### ISSUE TITLE
Some typos in CLIRunner.php file

### ISSUE THREAD

**Issue by mrleemon** [woothemes/woocommerce#33204]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://github.com/woocommerce/woocommerce/blob/13fe9b49707afdb50387bece76d2f588c3f05164/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/CLIRunner.php#L383

Some typos, some repeated sentences and missing periods can be found in this string:
`%1$d orders were verified in %2$f seconds Please review above errros. %3$d error(s) found %4$s. Please review above errors.`

### Expected behavior

Rewrite it to:
`%1$d orders were verified in %2$f seconds. %3$d error(s) found %4$s. Please review above errors.`

### Actual behavior

The current string is:
`%1$d orders were verified in %2$f seconds Please review above errros. %3$d error(s) found %4$s. Please review above errors.`

### Steps to reproduce

Not a bug but a typo

### WordPress Environment

WooCommerce 6.6 beta 1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Great find @mrleemon !

Would you be interested in opening up a pull request with that change?

**Comment by mrleemon** [comment]
Here it is: #33231
