### ISSUE TITLE
'Show setup task list' button is not working.

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#33211]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After finishing the setup tasklist it's not possible to see the setup task list again without refreshing the page. The button `Show setup task list` in the kebab menu is not working.

![screenshot-glamorous-echidna jurassic ninja-2022 05 26-13_33_36](https://user-images.githubusercontent.com/1314156/170532857-4e41e5f7-9f63-409d-bfda-16fd0bc06e7a.png)

### Expected behavior

After pressing `Show setup task list` the setup tasklist should be visible again. 

### Actual behavior

The button `Show setup task list` is not working.

![Screen Capture on 2022-05-26 at 13-19-57](https://user-images.githubusercontent.com/1314156/170549403-cf2e7f57-7e10-46f9-a6ab-613bf3ce06a0.gif)

### Steps to reproduce

1. Start with a fresh install
2. Install and activate the latest [WooCommerce Test Helper plugin](https://github.com/woocommerce/woocommerce-admin-test-helper/releases/tag/v0.7.4)
3. Navigate to **Tools > WCA Test Helper > Experiments** and toggle `woocommerce_tasklist_setup_experiment_2_2022_*` to treatment.
4. Finish all the tasks.
5. The message `You've completed store setup` will be visible.
6. Select `Show setup task list` in the kebab menu. 
7. Nothing happens.

### WordPress Environment

WordPress 6.0
WooCommerce 6.6.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
We should get this in for the WC 6.6 RC (May 31) as well.
