### ISSUE TITLE
Add e2e test for Admin translations

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#33230]
This idea came from @ilyasfoo in a conversation we had.

## Acceptance criteria

* Add an admin e2e test that changes the language (which might need new functionality added to the [reset helper plugin](https://github.com/woocommerce/woocommerce-reset)).
* Assert a stable string (that doesn't change often) has been translated originating from:
  * React admin client
  * PHP class
  * `@woocommerce/components` or other package

**Comment by moon0326** [comment]
After working on the reset plugin to add an endpoint to switch site language, I'm not sure if we want to add tests for translations.

`__()` function is part of the core and it's the core's responsibility to make sure it works. 
Translation files are community-driven (mostly) work and it's out of our control. 

Unless we want to test each component and make sure they are fully translated, I'm not sure what value it brings to test a single stable string.

@woocommerce/ghidorah Do we still want to add tests for translations?

**Comment by ilyasfoo** [comment]
@moon0326 While I agree the responsibility for maintaining translation functionality isn't ours, the main intention of adding a test is to catch translation issues potentially caused by us. A recent example is when the packages build process was changed, all strings from packages weren't translated and we weren't able to catch it.

>Unless we want to test each component and make sure they are fully translated, I'm not sure what value it brings to test a single stable string.

I don't think we should test each component, I think testing a single stable string for 3 different places should be sufficient to catch all known facets of translation, i.e: 1 each for PHP, react client, and a single package.

**Comment by moon0326** [comment]
> . A recent example is when the packages build process was changed, all strings from packages weren't translated and we weren't able to catch it.

@ilyasfoo  Thank you for sharing it 👍  I did not know about it. Do you have a link to the issue by any chance?

It would be helpful to see what type of test we need to write.

**Comment by ilyasfoo** [comment]
Sure, @moon0326! This was the issue: https://github.com/woocommerce/woocommerce/issues/32485

>It would be helpful to see what type of test we need to write.

I think just comparing an expected string would be sufficient

**Comment by moon0326** [comment]
> Sure, @moon0326! This was the issue: #32485
> 
> > It would be helpful to see what type of test we need to write.
> 
> I think just comparing an expected string would be sufficient

Now that I think about it, yup! it should be enough as tests run after the build process.

**Comment by rjchow** [comment]
220-gh-woocommerce/woocommerce-quality
