### ISSUE TITLE
API search parameter does not work

### ISSUE THREAD

**Issue by nameer94** [woothemes/woocommerce#33248]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I want to get list of products based on title that contain a string, basically a simple search.
the `search` parameter does not work, I tested it on two sites and both not working.

here is a request url:
`https://website.com/wp-json/wc/v3/products?search=mouse`

### Expected behavior

Return a list of products contain a string in its name

### Actual behavior

Return the same list without any parameters

### Steps to reproduce

Using REST API list products search parmeter

### WordPress Environment

WordPress: 6.0
Woocommerce: 6.5.1
Woocommerce REST API: 6.5.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi @nameer94 If you can add some step-by-step testing instructions, we'll be better able to reproduce the bug.
