### ISSUE TITLE
woocommerce_checkout_login_message filter not set up properly

### ISSUE THREAD

**Issue by t-bo** [woothemes/woocommerce#33250]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This concern the following filter: woocommerce_checkout_login_message

`<?php wc_print_notice( apply_filters( 'woocommerce_checkout_login_message', esc_html__( 'Returning customer?', 'woocommerce' ) ) . ' <a href="#" class="showlogin">' . esc_html__( 'Click here to login', 'woocommerce' ) . '</a>', 'notice' ); ?>
`

### Expected behavior

Check the closing parentheses for the apply_filter function:

`<?php wc_print_notice( apply_filters( 'woocommerce_checkout_login_message', esc_html__( 'Returning customer?', 'woocommerce' ) . ' <a href="#" class="showlogin">' . esc_html__( 'Click here to login', 'woocommerce' ) . '</a>'), 'notice' ); ?>`

### Actual behavior

Only the Returning Customer? bit of the message is covered by the filter so the ‘Click here to login’ link remain unaffected. 

### Steps to reproduce

no step

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.9.3 - There is a newer version of WordPress available (6.0)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 8.0.15
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~stretch-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 1140.64MB
Database Data Size: 652.05MB
Database Index Size: 488.59MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 8.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 71.61MB + Index: 81.23MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 2.86MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.44MB + Index: 2.33MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.48MB + Index: 0.11MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_aioseo_cache: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 2.52MB + Index: 0.16MB + Engine InnoDB
wp_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bw_pricing_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_visitor_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_comments: Data: 54.58MB + Index: 35.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 3.52MB + Index: 6.64MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.36MB + Index: 0.11MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 20.52MB + Index: 0.52MB + Engine InnoDB
wp_icl_translate_job: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.17MB + Index: 0.56MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 4.48MB + Index: 0.05MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 14.05MB + Index: 0.42MB + Engine InnoDB
wp_phone_compatibility_tmobile: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_phone_compatibility_v2: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 383.89MB + Index: 318.69MB + Engine InnoDB
wp_posts: Data: 26.44MB + Index: 6.52MB + Engine InnoDB
wp_redirection_404: Data: 2.52MB + Index: 0.64MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.41MB + Index: 0.11MB + Engine InnoDB
wp_sm_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 1.78MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_ld_license_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.52MB + Index: 9.06MB + Engine InnoDB
wp_wc_order_stats: Data: 4.52MB + Index: 5.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 2.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_entries: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 3.05MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 21.52MB + Index: 0.06MB + Engine InnoDB
wp_wpvivid_scan_result: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_unused_uploads_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1884
cookielawinfo: 6
custom_css: 1
customize_changeset: 1
e-landing-page: 2
elementor_library: 46
elementor_snippet: 1
nav_menu_item: 90
note: 8
page: 65
post: 43
product: 128
product_variation: 129
revision: 1180
shop_coupon: 30
shop_order: 22286
shop_order_refund: 2220
shop_subscription: 102
wc_product_tab: 24
wp_global_styles: 1
wp_product_tab: 32
wp-rest-api-log: 58
wpforms: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (58) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.7
AffiliateWP: by AffiliateWP – 2.9.4
AffiliateWP - Affiliate Product Rates: by Sandhills Development
LLC – 1.2

Akismet Anti-Spam: by Automattic – 4.2.4
All in One SEO Pro: by All in One SEO Team – 4.2.1.1
Attachment Pages Redirect: by Samuel Aguilera – 1.1.2
Boxtal Connect: by API Boxtal – 1.2.14
Code Snippets: by Code Snippets Pro – 3.1.0
Elementor Pro: by Elementor.com – 3.7.0
Elementor: by Elementor.com – 3.6.5
Site Kit by Google: by Google – 1.75.0
Jetpack Backup: by Automattic – 1.3.0
LiveChat WooCommerce: by LiveChat – 2.2.4
Magic Login - Passwordless Authentication for WordPress: by HandyPlugins – 1.3
Metorik Helper: by Metorik – 1.5.2
Order Export & Order Import for WooCommerce: by WebToffee – 2.2.4
PH Display Estimated Delivery Date on Product Page addon: by PluginHive – 1.0.2
Redirection: by John Godley – 5.2.3
SIM USA delivery date custom pluginhive: by Spyros Vlachopoulos – 1.0.0
sim usa - La Poste Integration: by Aelia – 1.0.2.200221
SIM USA Phone Compatibility: by Spyros Vlachopoulos – 1.0.0
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.6
GDPR Cookie Consent: by WebToffee – 2.3.7
Estimated Delivery Date Plugin For WooCommerce: by PluginHive – 2.0.3
Woocommerce autocomplete checkout address: by Acespritech Solutions Pvt. Ltd. – 1.1.0
Sogecommerce for WooCommerce: by Lyra Network – 1.9.5
WooCommerce Print Address Labels: by Ewout Fernhout – 1.7.0
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.15.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.37
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.3
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.12.1 (update to version 1.13.0 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.2
Pixel Manager for WooCommerce: by SweetCode – 1.17.4
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.0
WooCommerce PayPal Payments: by WooCommerce – 1.8.1-test1
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.14.5
WooCommerce PDF Invoices & Packing Slips Professional: by WP Overnight – 2.12.1
WooCommerce PDF Invoices & Packing Slips Premium Templates: by WP Overnight – 2.18.1
WooCommerce Product Add-ons: by WooCommerce – 5.0.0
WooCommerce Shipment Tracking: by WooCommerce – 1.7.0
WooCommerce Subscriptions: by WooCommerce – 4.3.0
WooCommerce Tab Manager: by SkyVerge – 1.14.1
Trustbadge Reviews for WooCommerce: by vendidero – 4.0.13
WooCommerce: by Automattic – 6.5.1
WP Dashboard Notes: by Jeroen Sormani – 1.0.10
WP Mail SMTP: by WPForms – 3.4.0
WP Rocket | Disable Page Caching: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.11.2
WPForms Form Abandonment: by WPForms – 1.6.0
WPForms Geolocation: by WPForms – 2.2.0
WPForms User Registration: by WPForms – 2.0.0
WPForms: by WPForms – 1.7.4.2
WPML Media: by OnTheGoSystems – 2.7.0
WPML String Translation: by OnTheGoSystems – 3.2.1
WPForms Multilingual: by OnTheGoSystems – 0.2.0
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.4.0

Related Products for WooCommerce: by WebToffee – 1.4.3
Sequential Order Numbers for WooCommerce: by WebToffee – 1.4.6

### Inactive Plugins (2) ###

Query Monitor: by John Blackbourn – 3.9.0
REST API Log: by Pete Nelson – 1.6.8

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.14.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: braintree-subscription (braintree-subscription)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #59398 - /shop/
Cart: #59399 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #59401 - /my-account/
Terms and conditions: #24749 - /terms-of-sale/

### Theme ###

Name: Astra
Version: 3.8.1
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscription Statuses: trash: 1
wc-active: 31
wc-expired: 4
wc-pending-cancel: 6
wc-on-hold: 1
wc-cancelled: 59

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: France

### Subscriptions by Payment Gateway ###

other: trash: 1
PayPal Card Processing: wc-active: 24
wc-cancelled: 19
wc-expired: 2
wc-on-hold: 1
wc-pending-cancel: 4

PayPal: wc-active: 7
wc-cancelled: 3
wc-pending-cancel: 2

### Payment Gateway Support ###

Direct bank transfer: products
PayPal Card Processing: refunds
products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal: refunds
products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: FR
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: –

### Action Scheduler ###

Canceled: 1
Oldest: 2022-05-23 18:11:00 +0200
Newest: 2022-05-23 18:11:00 +0200

Complete: 6,801
Oldest: 2022-04-28 15:24:09 +0200
Newest: 2022-05-29 12:20:10 +0200

Failed: 10
Oldest: 2021-11-01 13:36:36 +0100
Newest: 2022-05-05 08:08:49 +0200

Pending: 52
Oldest: 2022-05-29 12:20:35 +0200
Newest: 2022-07-05 07:00:18 +0200

### Status report information ###

Generated at: 2022-05-29 12:20:40 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Can you provide a screen shot please?
