### ISSUE TITLE
WooCommerce Admin Store Details task is indiscriminate about the onboarding experience

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#33267]
From: https://github.com/Automattic/wp-calypso/issues/63704

> The store details task is redirecting the user to the WooCommerce Profiler. However, the WP.com customer probably never saw the WC Profiler because they went through the WP.com stepper. This can cause some confusion, so it would be better to redirect the store details task to the WP.com stepper or hide the task.

**Comment by valterlorran** [comment]
Hey, do we have any progress on this issue?

**Comment by rjchow** [comment]
Hey @valterlorran thanks for the ping on this, I applied the wrong label so it wasn't showing up on our teams' dashboard.
I've applied the correct labels now so we'll look into this in the upcoming weeks

**Comment by chihsuan** [comment]
Hey @valterlorran I've created a PR for it. When users click on the store details task, they will be redirected to the setting page instead. The change will be released in 6.8 on August 9.
