### ISSUE TITLE
Analytics - the line/bar icon to toggle the chart is barely visible

### ISSUE THREAD

**Issue by alanwaitati** [woothemes/woocommerce#33263]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In Woocommerce Analytics, the icon to toggle between line/bar charts (top right in the image below) is barely visible. 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/75771732/171063324-19f8ccd1-0285-4537-9f29-8325a7fb52ca.png">

### Expected behavior

The icon should be clear enough to be obvious to the user.

### Actual behavior

I looked around and clicked the kebab icon, the active icon etc. It took time to find the icon.

### Steps to reproduce

1. Go to the Analytics Overview. 

### WordPress Environment

<details>

WordPress address (URL): http://starkravingdadblog.com
Site address (URL): http://starkravingdadblog.com
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.9.3 - There is a newer version of WordPress available (6.0)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.17
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.37-40-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: _DGD_
Total Database Size: 76.95MB
Database Data Size: 48.95MB
Database Index Size: 28.00MB
_DGD_woocommerce_sessions: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
_DGD_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_woocommerce_downloadable_product_permissions: Data: 0.25MB + Index: 0.48MB + Engine InnoDB
_DGD_woocommerce_order_items: Data: 0.28MB + Index: 0.09MB + Engine InnoDB
_DGD_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
_DGD_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_DGD_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_DGD_actionscheduler_actions: Data: 3.02MB + Index: 2.19MB + Engine InnoDB
_DGD_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_actionscheduler_logs: Data: 2.02MB + Index: 1.42MB + Engine InnoDB
_DGD_ahm_assets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_country: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_download_stats: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_order_renews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_payment_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_refunds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_ahm_withdraws: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_cartflows_ca_cart_abandonment: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
_DGD_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
_DGD_comments: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
_DGD_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_dlm_order_customer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_download_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_es_download_counter: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_mailchimp_carts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
_DGD_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_options: Data: 8.48MB + Index: 0.22MB + Engine InnoDB
_DGD_postmeta: Data: 17.55MB + Index: 12.97MB + Engine InnoDB
_DGD_posts: Data: 2.47MB + Index: 0.66MB + Engine InnoDB
_DGD_post_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_redirection_404: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
_DGD_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
_DGD_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_DGD_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_sbi_instagram_posts: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
_DGD_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
_DGD_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
_DGD_usermeta: Data: 4.47MB + Index: 3.89MB + Engine InnoDB
_DGD_users: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
_DGD_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
_DGD_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wc_customer_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
_DGD_wc_download_log: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
_DGD_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_wc_order_product_lookup: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
_DGD_wc_order_stats: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
_DGD_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
_DGD_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wc_zapier_history: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
_DGD_wdi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wdi_themes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_DGD_yoast_indexable: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
_DGD_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
_DGD_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_DGD_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_DGD_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
_DGD_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 36
acf-field-group: 6
attachment: 600
biolink: 1
custom_css: 1
elementor_library: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mc4wp-form: 1
ml-slide: 3
ml-slider: 1
nav_menu_item: 17
newsletters: 17
oembed_cache: 3
page: 52
podcasts: 21
post: 71
product: 36
product_variation: 36
revision: 5
shop_order: 2187
shop_order_refund: 3
shop_subscription: 74
stark_post_podcast: 1
wbcr-snippets: 15
wdi_instagram: 1
wp_block: 26
wp_global_styles: 1
wpdmpro: 1
wpforms: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
AFL UTM Tracker: by Appfromlab – 2.5.0
Akismet Anti-Spam: by Automattic – 4.2.3
Clicky Analytics: by Alin Marcu – 1.6.5
Cloudflare: by Cloudflare
Inc. – 4.8.3

Customizer Export/Import: by The Beaver Builder Team – 0.9.4
Duplicate Page: by mndpsingh287 – 4.4.8
Enable Media Replace: by ShortPixel – 3.6.3
Pixel Cat Lite: by Fatcat Apps – 2.6.6
Gelato Integration for WooCommerce: by Gelato – 1.0.3
Gutenberg: by Gutenberg Team – 13.1.0
Hotjar: by Hotjar – 1.0.12
Woody code snippets (PHP snippets | Insert PHP): by Creative Motion
Will Bontrager Software
LLC  – 2.4.4

Integromat Connector: by Integromat – 1.5.1
Lazy Social Comments: by Joel James – 2.0.4
Mailchimp for WooCommerce: by Mailchimp – 2.6.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.7
Neve Hooks: by ThemeIsle – 1.0.1
Neve Pro Addon: by ThemeIsle – 2.2.1
Facebook for WordPress: by Facebook – 3.0.6
Gutenberg Blocks and Template Library by Otter: by ThemeIsle – 2.0.1
Page Links To: by Mark Jaquith – 3.3.6
Redirection: by John Godley – 5.2.3
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.15
Advanced Order Export For WooCommerce: by AlgolPlus – 3.2.2
Variation Swatches for WooCommerce Pro: by RadiusTheme – 2.0.1.1
Variation Swatches for WooCommerce: by RadiusTheme – 2.1.1.6
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0 (update to version 2.0.0 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.8
WooCommerce Payments: by Automattic – 4.0.2 (update to version 4.2.0 is available)
WooCommerce Price Based on Country Pro Add-on: by Oscar Gare – 2.17.0
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.2.2
WooCommerce Sales Analysis: by itthinx – 1.12.0
WooCommerce Subscriptions: by WooCommerce – 4.1.0 (update to version 4.3.0 is available)
WooCommerce Waitlist: by Neil Pie – 2.3.2
WooCommerce Xero Integration: by WooCommerce – 1.7.41 (update to version 1.7.42 is available)
WooCommerce Zapier: by OM4 Software – 2.3.0
WooCommerce: by Automattic – 6.5.1
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 18.6
WP Mail SMTP: by WPForms – 3.4.0
WPC Variations Radio Buttons for WooCommerce (Premium): by WPClever – 3.0.4
WPForms Lite: by WPForms – 1.7.4

### Inactive Plugins (3) ###

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Simply Show Hooks: by Stuart O'Brien
cxThemes – 1.2.1

YITH WooCommerce Ajax Product Filter: by YITH – 4.9.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (7) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
SSO: by Garth Mortensen
Mike Hansen – 0.3

WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.9
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #1958 - /shop/
Cart: #1959 - /cart/
Checkout: #1960 - /checkout/
My account: #1961 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Neve Child for SRD
Version: 1.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Neve
Parent Theme Version: 3.1.6 – 3.2.5 is available
Parent Theme Author URL: https://themeisle.com
WooCommerce Support: ✔

### Templates ###

Overrides: neve-child/woocommerce/archive-product.php
neve-child/woocommerce/auth/footer.php
neve-child/woocommerce/auth/form-grant-access.php
neve-child/woocommerce/auth/form-login.php
neve-child/woocommerce/auth/header.php
neve-child/woocommerce/cart/cart-empty.php
neve-child/woocommerce/cart/cart-item-data.php
neve-child/woocommerce/cart/cart-shipping.php
neve-child/woocommerce/cart/cart-totals.php
neve-child/woocommerce/cart/cart.php
neve-child/woocommerce/cart/cross-sells.php
neve-child/woocommerce/cart/mini-cart.php
neve-child/woocommerce/cart/proceed-to-checkout-button.php
neve-child/woocommerce/cart/shipping-calculator.php
neve-child/woocommerce/checkout/cart-errors.php
neve-child/woocommerce/checkout/form-billing.php
neve-child/woocommerce/checkout/form-checkout.php
neve-child/woocommerce/checkout/form-coupon.php
neve-child/woocommerce/checkout/form-login.php
neve-child/woocommerce/checkout/form-pay.php
neve-child/woocommerce/checkout/form-shipping.php
neve-child/woocommerce/checkout/order-receipt.php
neve-child/woocommerce/checkout/payment-method.php
neve-child/woocommerce/checkout/payment.php
neve-child/woocommerce/checkout/review-order.php
neve-child/woocommerce/checkout/terms.php
neve-child/woocommerce/checkout/thankyou.php
neve-child/woocommerce/content-product.php
neve-child/woocommerce/content-single-product.php
neve-child/woocommerce/content-widget-price-filter.php
neve-child/woocommerce/content-widget-product.php
neve-child/woocommerce/content-widget-reviews.php
neve-child/woocommerce/global/breadcrumb.php
neve-child/woocommerce/global/form-login.php
neve-child/woocommerce/global/quantity-input.php
neve-child/woocommerce/global/sidebar.php
neve-child/woocommerce/global/wrapper-end.php
neve-child/woocommerce/global/wrapper-start.php
neve-child/woocommerce/loop/add-to-cart.php
neve-child/woocommerce/loop/loop-end.php
neve-child/woocommerce/loop/loop-start.php
neve-child/woocommerce/loop/no-products-found.php
neve-child/woocommerce/loop/orderby.php
neve-child/woocommerce/loop/pagination.php
neve-child/woocommerce/loop/price.php
neve-child/woocommerce/loop/rating.php
neve-child/woocommerce/loop/result-count.php
neve-child/woocommerce/loop/sale-flash.php
neve-child/woocommerce/myaccount/dashboard.php
neve-child/woocommerce/myaccount/downloads.php
neve-child/woocommerce/myaccount/form-add-payment-method.php
neve-child/woocommerce/myaccount/form-edit-account.php
neve-child/woocommerce/myaccount/form-edit-address.php
neve-child/woocommerce/myaccount/form-login.php
neve-child/woocommerce/myaccount/form-lost-password.php
neve-child/woocommerce/myaccount/form-reset-password.php
neve-child/woocommerce/myaccount/lost-password-confirmation.php
neve-child/woocommerce/myaccount/my-account.php
neve-child/woocommerce/myaccount/my-address.php
neve-child/woocommerce/myaccount/my-downloads.php
neve-child/woocommerce/myaccount/my-orders.php
neve-child/woocommerce/myaccount/navigation.php
neve-child/woocommerce/myaccount/orders.php
neve-child/woocommerce/myaccount/payment-methods.php
neve-child/woocommerce/myaccount/view-order.php
neve-child/woocommerce/notices/error.php
neve-child/woocommerce/notices/notice.php
neve-child/woocommerce/notices/success.php
neve-child/woocommerce/order/form-tracking.php version 3.6.0 is out of date. The core version is 6.5.0
neve-child/woocommerce/order/order-again.php
neve-child/woocommerce/order/order-details-customer.php
neve-child/woocommerce/order/order-details-item.php
neve-child/woocommerce/order/order-details.php
neve-child/woocommerce/order/order-downloads.php
neve-child/woocommerce/order/tracking.php
neve-child/woocommerce/product-searchform.php
neve-child/woocommerce/single-product/add-to-cart/external.php
neve-child/woocommerce/single-product/add-to-cart/grouped.php
neve-child/woocommerce/single-product/add-to-cart/simple.php
neve-child/woocommerce/single-product/add-to-cart/variable.php
neve-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
neve-child/woocommerce/single-product/add-to-cart/variation.php
neve-child/woocommerce/single-product/meta.php
neve-child/woocommerce/single-product/photoswipe.php
neve-child/woocommerce/single-product/price.php
neve-child/woocommerce/single-product/product-attributes.php
neve-child/woocommerce/single-product/product-image.php
neve-child/woocommerce/single-product/product-thumbnails.php
neve-child/woocommerce/single-product/rating.php
neve-child/woocommerce/single-product/related.php
neve-child/woocommerce/single-product/review-meta.php
neve-child/woocommerce/single-product/review-rating.php
neve-child/woocommerce/single-product/review.php
neve-child/woocommerce/single-product/sale-flash.php
neve-child/woocommerce/single-product/share.php
neve-child/woocommerce/single-product/short-description.php
neve-child/woocommerce/single-product/stock.php
neve-child/woocommerce/single-product/tabs/additional-information.php
neve-child/woocommerce/single-product/tabs/description.php
neve-child/woocommerce/single-product/tabs/tabs.php
neve-child/woocommerce/single-product/title.php
neve-child/woocommerce/single-product/up-sells.php
neve-child/woocommerce/single-product-reviews.php
neve-child/woocommerce/single-product.php
neve-child/woocommerce/taxonomy-product-cat.php
neve-child/woocommerce/taxonomy-product-tag.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://starkravingdadblog.com
Subscription Statuses: wc-active: 52
wc-pending-cancel: 2
wc-on-hold: 7
wc-cancelled: 13

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: New Zealand — Otago

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 51
wc-cancelled: 11
wc-on-hold: 7
wc-pending-cancel: 2

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

PayPal Standard: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: NZ
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 182.54.172.21
Real external IP: 182.54.172.21
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 2.2.2
Base location: NZ:OT
Base currency: USD
Price Based On: billing
Shipping: –
Test mode: –
Test country: –
Load products price in background: ✔
Currency format: [symbol][price]
Exchange rate API: floatrates
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: excl

### Zone Pricing NZ ###

zone_id: nz
name: NZ
countries: NZ
currency: NZD
exchange_rate: 1.52763414179
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 0.5
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 1.527634
round_after_taxes: no
trim_zeros: no

### Zone Pricing AU ###

zone_id: au
name: AU
countries: AU
currency: AUD
exchange_rate: 1.39321528936
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 0.5
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 1.393215
round_after_taxes: no
trim_zeros: no

### Zone Pricing UK ###

zone_id: uk
name: UK
countries: GB
currency: GBP
exchange_rate: 0.791592269973
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 0.5
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 0.791592
round_after_taxes: no
trim_zeros: no

### Zone Pricing EU ###

zone_id: eu
name: EU
countries: AX | AD | AT | BE | CY | EE | FI | FR | GF | TF | DE | GR | GP | IE | IT | LV | LT | LU | MT | MQ | YT | MC | ME | NL | PT | RE | BL | MF | PM | SM | SK | SI | ES | VA
currency: EUR
exchange_rate: 0.92980811675
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 0.5
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 0.929808
round_after_taxes: no
trim_zeros: no

### Zone Pricing CA ###

zone_id: ca
name: CA
countries: CA
currency: CAD
exchange_rate: 1.27072932758
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 0.5
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 1.270729
round_after_taxes: no
trim_zeros: no

### WooCommerce Payments ###

Version: 4.0.2
Connected to WPCOM: Yes
Blog ID: 150505596
Account ID: acct_1Jd0hw2HzE63yYs8

### Action Scheduler ###

Canceled: 8
Oldest: 2022-04-30 05:27:33 +0000
Newest: 2022-05-29 06:50:02 +0000

Complete: 6,619
Oldest: 2022-04-30 04:08:52 +0000
Newest: 2022-05-30 22:10:21 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 61
Oldest: 2022-05-30 22:20:07 +0000
Newest: 2023-05-19 05:26:29 +0000

### WooCommerce Zapier ###

Database Version: ✔ 14
Detailed Logging Enabled: No
Legacy Mode Disabled: ✔ Yes
SSL: ✔ Yes
REST API Authentication Key(s): ✔ 10
Task History Record Count: ✔ 1922
Webhook #41: WooCommerce Zapier
- Status: active
- Trigger: subscription.status_changed
- Delivery Count: 26
Webhook #40: WooCommerce Zapier
- Status: active
- Trigger: subscription.created
- Delivery Count: 37
Webhook #39: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 224
Webhook #38: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 224
Webhook #37: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 224
Webhook #36: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 224
Webhook #35: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 224
Webhook #22: WooCommerce Zapier
- Status: disabled
- Trigger: order.paid
- Delivery Count: 159
Deleted Webhook Delivery Count: 580

### Status report information ###

Generated at: 2022-05-31 08:10:54 +10:00

</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this change is very useful, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
