### ISSUE TITLE
No payments available-HELP

### ISSUE THREAD

**Issue by WHneedshelp** [woothemes/woocommerce#33276]
I have deleted and reinstalled woocommerce. I have ordering set to only the USA and am using woocommerce payment.... I can't figure out how to get the payments to work.

**Prerequisites (mark completed items with an [x]):**
- [X ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Comment by psealock** [comment]
Hi @WHneedshelp, sounds like you're having a hard time. 

You'll need to be more specific and include some steps to reproduce for us so we can figure out the problem. Can you use the template provided when creating an issue?
