### ISSUE TITLE
Admin can refund more quantity than the order have for one product

### ISSUE THREAD

**Issue by MiladRezaeian** [woothemes/woocommerce#33271]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

when admin want to refund a product that it has a product with one quantity in order, it can refund more than one. it dose not make sense. 

### Expected behavior

it should show a error and say you want to refund more that quantity of product in order.

### Actual behavior

when admin want to refund a product that it has a product with one quantity in order, it can refund more than one. it dose not make sense. 

### Steps to reproduce

1. in order
2. do refund
3. and if product have for example 1 quantity in order, refund 3 
4. you can do it and it is wrong.

### WordPress Environment

no need to this one.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@MiladRezaeian Thanks for reporting this. This has been addressed:

<img width="652" alt="Screenshot 2023-07-18 at 4 53 18 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/7deb28fa-70a2-40fa-9bf8-2c92d77fc508">
