### ISSUE TITLE
Countdown delayed load for 20 to 30 seconds - preset 3 - recurring timer

### ISSUE THREAD

**Issue by taniagraphem123** [woothemes/woocommerce#33277]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is a Countdown delayed load for 20 to 30 seconds - preset 3 - recurring timer
It's happening on many pages we are using but here is an example
https://join.ragingbull.com/jason-bonds-daily-shot/
when you open the page the countdown doesn't load immediately takes sometimes 20 seconds sometimes more
we believe it's hurting our sales

### Expected behavior

Countdown preset 3 recurring timer loads inmediatelyimmediately

### Actual behavior

There is a Countdown delayed load for 20 to 30 seconds - preset 3 - recurring timer

### Steps to reproduce

1. Open https://join.ragingbull.com/jason-bonds-daily-shot/
2. See the countdown doesn't load immediately

### WordPress Environment

Failed: 1
Oldest: 2022-03-18 11:13:07 -0400
Newest: 2022-03-18 11:13:07 -0400

Pending: 349
Oldest: 2022-05-31 14:40:37 -0400
Newest: 2026-05-17 14:47:35 -0400

### Status report information ###

Generated at: 2022-05-31 14:39:50 -04:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Is this the countdown? It loads right away for me

![image](https://user-images.githubusercontent.com/1922453/171307557-f2e1be04-5b6d-49c5-b42a-2ad2f2f0a34c.png)
