### ISSUE TITLE
Onboarding tasks documentation uses deprecated filters

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#33293]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://developer.woocommerce.com/extension-developer-guide/handling-merchant-onboarding/ is out of date.

Code that implements task list items in the manner described in that article causes deprecation errors in the browser console:
woocommerce_admin_onboarding_task_list is deprecated and will be removed from @woocommerce/data in version 2.10.0. Please use TaskLists::add_task() instead.

TaskLists::add_task() seems to be server side (PHP), not JS though, so it's unclear what the *right* way to register these tasks is now.

### Expected behavior

- Documentation is updated so that implementations that follow the documentation do not throw deprecation warnings
- Developer advisory published outlining how to migrate from the old filter-based task adding to its new replacement

### Actual behavior

- Implementations that follow the documentation currently throw deprecation warnings
- No developer advisory available about the change

### Steps to reproduce

Follow documentation, not the deprecation warning in browser console.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
I've updated the setup task section https://developer.woocommerce.com/extension-developer-guide/handling-merchant-onboarding/

**Comment by leewillis77** [comment]
Please can this be re-opened. It's completely unclear from the documentation how a migration from the originally advised approach to the new approach should be carried out, and the examples in the updated documentation are incomplete / incorrect (syntax errors, missing imports, no information on required build config etc.).

The updated documentation / examples don't solve the original issue I had :(

**Comment by leewillis77** [comment]
Just for reference, I've attempted to re-work an existing (working) task list information based on the information provided, and once I've resolved the issues with missing includes / builds / syntax issues I'm left with an implementation that doesn't throw any errors (either at the PHP level, or in the browser console), but also doesn't render the task lists as intended. 

I suspect it's down to the `registerPlugin()` call (which looks like it's what has replaced the filter we previously used), but I can't see how to get that all hooked up correctly, and the documentation and lack of errors is unfortunately not terribly helpful in working out why things aren't working.

**Comment by chihsuan** [comment]
@leewillis77 I apologize, the update didn't resolve your issue. It has been reopened now. We will update the document as soon as possible. Thanks for your information!

**Comment by leewillis77** [comment]
Just as a further update on our side of things. We did manage to get everything moved over. The issue seems to have been on the PHP side, specifically where we changed from registering the tasks by filtering `woocommerce_get_registered_extended_tasks` and pushing the tasks into the array to calling `TaskLists::add_task()` directly. 

Something meant that the new code wasn't running in the right context / right priority to actually register the task. We needed to pull the code out to a place that ran with less restrictions and at a different hook (now running on `init`). I'm not too sure what the exact issue, but a simple swap out of `add_filter('woocommerce_get_registered_extended_tasks',...)` to an equivalent `TaskLists:add_task()` didn't actually register the task.

**Comment by chihsuan** [comment]
> Something meant that the new code wasn't running in the right context / right priority to actually register the task. We needed to pull the code out to a place that ran with less restrictions and at a different hook (now running on init). I'm not too sure what the exact issue, but a simple swap out of add_filter('woocommerce_get_registered_extended_tasks',...) to an equivalent TaskLists:add_task() didn't actually register the task.

Hey @leewillis77, Thanks for the updates! Yes, you're right. To register a task, you need to ensure that the code for registering tasks using TaskLists::add_task() in `init` hook because onboarding tasks are registered in `init` hook. Sorry didn't mention that in the documentation.

I've made changes to the documentation. Would you mind taking a look to see? You could also find an example plugin [here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-admin/docs/examples/extensions/add-task).

**Comment by chihsuan** [comment]
@leewillis77 👋  I'm going to close this. Free feel to let me know if you have any feedback. Thanks!

**Comment by leewillis77** [comment]
Hi; 

Thanks for coming back on this, and apologies for the delay replying. I can see that the updated documentation covers off some of the issue we raised, but I think there are still some things that really aren't covered well:

- What the difference is between actioning a task and completing it - what functions are available from WooCommerce to handle this (in the previous incarnation, this had to be handled by the individual plugin themselves, but it looks like there are now standard WC-provided methods to track actioning/completion?
- The need / process for enqueueing the Javascript relating to setup tasks
- The build config required if you're doing this in your own plugin

As I said in the original bug report it would be helpful if Woo published a migration guide showing how to transition from the previous "official method" (https://developer.woo.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/) to the new implementation. 

Personally speaking we've managed to get everything migrated, so no need to re-open this issue for my personal benefit, but hope the feedback is helpful.

**Comment by chihsuan** [comment]
> Hi;
> 
> Thanks for coming back on this, and apologies for the delay replying. I can see that the updated documentation covers off some of the issue we raised, but I think there are still some things that really aren't covered well:
> 
> * What the difference is between actioning a task and completing it - what functions are available from WooCommerce to handle this (in the previous incarnation, this had to be handled by the individual plugin themselves, but it looks like there are now standard WC-provided methods to track actioning/completion?
> * The need / process for enqueueing the Javascript relating to setup tasks
> * The build config required if you're doing this in your own plugin
> 
> As I said in the original bug report it would be helpful if Woo published a migration guide showing how to transition from the previous "official method" (https://developer.woo.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/) to the new implementation.
> 
> Personally speaking we've managed to get everything migrated, so no need to re-open this issue for my personal benefit, but hope the feedback is helpful.

Thanks for the great feedback! @leewillis77 

 cc @woocommerce/ghidorah It would be helpful if we could continue updating documentation or write some related articles in the future.
