### ISSUE TITLE
Block editor: add property to post create/edit/update Tracks events 

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#33294]
Expand the product editing related events, e.g. wcadmin_product_add_publish/_edit with a property indicating block editor usage.
Theme for testing e.g. Blooms. 
To-do: confirm the events list.

**Comment by pmcpinto** [comment]
@AnnaMag I think it will be enough to add the prop to wcadmin_product_add_publish and wcadmin_product_update

**Comment by AnnaMag** [comment]
Closed in https://github.com/woocommerce/woocommerce/pull/33321 for the wcadmin_product_update event.
It is still to be investigated [how to include the change in the product_add_publish event.](https://github.com/woocommerce/woocommerce/issues/33406#issuecomment-1162172825).
