### ISSUE TITLE
Wrong product stock check on order-pay page with a custom status

### ISSUE THREAD

**Issue by whispercodeDev** [woothemes/woocommerce#33307]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you try to pay for an order through the order-pay page and this order has a custom status which already reduced stock, there comes this error message: "Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused."

### Expected behavior

The order already reduced stock, so there shouldn't be any stock check and no error message.

### Actual behavior

The product is checked for stock although the stock is already reduced for this order. If there is none left in stock, the order can't be paid and you are getting an error message. 

### Steps to reproduce

1. Create a custom order status (e.g. with Booster for WooCommerce)
2. Enable reduce stock for this status
3. Enable valid for payment for this status
4. Create an order in the admin backend
5. Put a product with price > 0 in this order which has a total quantity of 4.
6. Increase the item quantity to 3, so there is 1 left.
7. Put the order in the custom status -> stock is now reduced by 3
8. Try to pay for it through the pay order link at the order
9. Error message: Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused.

Here some filters to help to reproduce: 

```
// enable "reduce stock" for custom status
add_action( 'woocommerce_order_status_confirmed', 'wc_maybe_reduce_stock_levels' );

// set custom status as valid for payment
add_filter( 'woocommerce_valid_order_statuses_for_payment', 'custom_status_valid_for_payment', 10, 2 );
function custom_status_valid_for_payment( $statuses, $order ) {
		// Registering the custom status as valid for payment
		$statuses[] = 'confirmed';
		return $statuses;
	}
```

I have fixed this bug in our shop by doing this. Imho, there shouldn't be any stock check if the stock is already reduced. 

```
add_filter( 'woocommerce_pay_order_product_has_enough_stock', 'cvz_woocommerce_pay_order_product_has_enough_stock', 10, 3 );
function cvz_woocommerce_pay_order_product_has_enough_stock( $result, $product, $order ) {
		$stockReduced = get_post_meta( $order->get_id(), '_order_stock_reduced', true );
		if( $stockReduced == 'yes' ) {
			$result = true;
		}
		return $result;
	}
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://localhost/bug
Site address (URL): https://localhost/bug
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Win64) OpenSSL/1.1.1a PHP/7.4.29
PHP Version: 7.4.29
PHP Post Max Size: 256 MB
PHP Time Limit: 3000
PHP Max Input Vars: 10000
cURL Version: 7.70.0
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.38-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 3.93MB
Datenbank-Datengröße: 2.46MB
Datenbank-Indexgröße: 1.47MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Daten: 0.03MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Booster for WooCommerce: von Pluggabl LLC – 5.5.9
WooCommerce: von Automattic – 6.5.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: von Automattic – 4.2.4
Hello Dolly: von Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop-Basis: #6 - /?page_id=6
Warenkorb: #7 - /?page_id=7
Kasse: #8 - /?page_id=8
Mein Konto: #9 - /?page_id=9
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://de.wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 9
Oldest: 2022-06-03 12:24:50 +0200
Newest: 2022-06-03 12:34:54 +0200

### Status report information ###

Generated at: 2022-06-03 12:41:18 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for reporting this, I was able to replicate this and suspect we need to update [`WC_Shortcode_Checkout::order_pay()`](https://github.com/woocommerce/woocommerce/blob/6.6.1/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php#L154-L166) to test if stock has already been reduced for each line item (which, of course, is what you are working around with your `woocommerce_pay_order_product_has_enough_stock` filter).
