### ISSUE TITLE
Create a Woo Flavored ExPlat Client for PHP

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#33306]
## User Story

As a Woo developer, I want an ExPlat client pre-configured for use in WooCommerce, so that I don't have to configure it myself for each experiment.

## Criteria

* Contribute the existing class back to Jetpack in https://github.com/Automattic/jetpack/issues/19596
* Use Composer to include [automattic/jetpack-abtest](https://packagist.org/packages/automattic/jetpack-abtest).
* Create a new "Woo flavored" class, which wraps the Jetpack class. The [decorator pattern](https://sourcemaking.com/design_patterns/decorator/php) can be good for this.
  * Configure the wrapper class to fetch the anonymous ID on its own.
  * Configure the wrapper class to provide custom segment values.

**Comment by moon0326** [comment]
Not exactly a 'Woo Favored' implementation, but I've added [in_treatment](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php#L106) method a few months ago to make it a bit simpler to use.

**Comment by adrianduffell** [comment]
I'll close this out due to age.
