### ISSUE TITLE
Implement Valid Changelog Files

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33317]
### Describe the solution you'd like

While we may be using the Jetpack Changelogger to create changelog entries, we aren't enforcing the expected `CHANGELOG.md` format. We need to make sure that all of the packages and plugins are fully configured and have valid changelog files. 

**NOTE**: Solaris owned packages will be omitted from this process. We can bring them up to speed when a complete process is in place. Private packages that have no `composer.json` are also omitted.

## Steps Required

See https://github.com/woocommerce/woocommerce/pull/33359  for an example

1. Create `CHANGELOG.md` and rename the old to `PREVIOUS_CHANGELOG.md`
2. Run the script, `./vendor/bin/changelogger write --use-version=10.1.0`
3. Add `# Unreleased` entries
4. Add the footer to the new changelog with a link to the previous one
5. Update version number in `package.json`
6. Add or modify `.gitignore` so that things like `vendor/` don't get bundled up
7. Merge a pull request like this
8. Run `pnpm publish --publish-branch=trunk --dry-run` to check that its all ok
9. Run `pnpm publish --publish-branch=trunk`

## Packages             
- [x] components https://github.com/woocommerce/woocommerce/pull/33359              
- [x] csv-export https://github.com/woocommerce/woocommerce/pull/33412             
- [x] currency https://github.com/woocommerce/woocommerce/pull/33412
- [x] customer-effort-score https://github.com/woocommerce/woocommerce/pull/33412   
- [x] data https://github.com/woocommerce/woocommerce/pull/33412
- [x] date https://github.com/woocommerce/woocommerce/pull/33412             
- [x] dependency-extraction-webpack-plugin https://github.com/woocommerce/woocommerce/pull/33412                          
- [x] eslint-plugin https://github.com/woocommerce/woocommerce/pull/33412                        
- [x] experimental https://github.com/woocommerce/woocommerce/pull/33412 
- [x] explat https://github.com/woocommerce/woocommerce/pull/33412
- [x] extend-cart-checkout-block https://github.com/woocommerce/woocommerce/pull/33412                             
- [x] navigation https://github.com/woocommerce/woocommerce/pull/33412                     
- [x] number https://github.com/woocommerce/woocommerce/pull/33412
- [x] onboarding https://github.com/woocommerce/woocommerce/pull/33412
- [x] tracks https://github.com/woocommerce/woocommerce/pull/33412

**Comment by psealock** [comment]
All relevant packages have been released with same changelog configurations. This one is ready to be closed out now.
