### ISSUE TITLE
Store remote inbox cache as transient instead of as option

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#33314]
The remote inbox implementation currently caches the result of calling the https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json endpoint in the following option:

`wc_remote_inbox_notifications_specs`

This is currently over 7.2kb and as such, isn't ideally stored as an option, since that can cause performance issues on some installations.

Instead, the cache result should be stored as a transient.

Reference: pMz3w-fi5-p2

**Comment by joshuatf** [comment]
@mattsherman From what I'm seeing, this is already stored in a transient.  https://github.com/woocommerce/woocommerce-admin/pull/7671/ introduced the `DataSourcePoller` which stores all polled info in transients.

It's possible that these sites are using older versions of WC or the option has just been left in the options table.

Should we add in a migration to clean up this old option?  I think a deletion would be safe given this is re-fetched daily in our cron event.

**Comment by mattsherman** [comment]
@joshuatf Interesting. Can you dig into this a bit more and follow up on the linked reference post. It seems odd that the sites would be running an older version of WC. I imagine we are just missing some detail. Thanks!

**Comment by joshuatf** [comment]
@mattsherman It's likely they are not running older versions, but the previous option where remote specs were stored is no longer used and was not deleted.  I can follow up in that thread, but if it's an ongoing issue, we should introduce a migration to handle this.

**Comment by mattsherman** [comment]
Agreed. Since the option is no longer used, a migration to delete it would be ideal.
