### ISSUE TITLE
Create Package Release Workflow

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33319]
### Describe the solution you'd like

We should create a dispatchable workflow to automate the release of packages. This should be a workflow that accepts the package's name and runs a script.

- [x] Should update the changelog https://github.com/woocommerce/woocommerce/pull/33515
- [x] Should update the package.json version https://github.com/woocommerce/woocommerce/pull/33515
- [x] Should open a PR to update https://github.com/woocommerce/woocommerce/pull/33614
- [x] After merging they can run a script that runs `pnpm publish` and be done. https://github.com/woocommerce/woocommerce/pull/33743
- [x] Add a Github workflow to release directly from GH https://github.com/woocommerce/woocommerce/pull/33743
- [x] Document the process somewhere https://github.com/woocommerce/woocommerce/pull/33743

**Comment by ObliviousHarmony** [comment]
* Should update the changelog
* Should update the `package.json` version
* Should open a PR to update
* AFter merging they can run `pnpm publish` and be done

**Comment by psealock** [comment]
This one is finished 🎆
