### ISSUE TITLE
Add `woo_wcadmin_install_timestamp` parameter to JS ExPlat client by default

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#33331]
### Describe the solution you'd like

In https://github.com/woocommerce/woocommerce/pull/33300, we added `woo_wcadmin_install_timestamp` to default query parameter PHP ExPlat client. 

I think it makes sense to add this to JS client as well, but it will require preloading the `woocommerce_admin_install_timestamp` option.

**Comment by ilyasfoo** [comment]
cc @woocommerce/mothra if anyone is interested to pick up since you've made the changes for PHP

**Comment by mattsherman** [comment]
Thanks, @ilyasfoo

**Comment by adrianduffell** [comment]
With WC Admin no longer a thing after the merge, would we be able to set the parameter name to `woo_install_timestamp` to reduce confusion in the future?

However, both names would probably need to be used in a short transition period, to support the current experiments using the existing parameter name.

**Comment by ilyasfoo** [comment]
@adrianduffell I'm neutral on that, I think having `wcadmin` wouldn't introduce too much confusion, but I can appreciate the updated name

**Comment by jacob-sewell** [comment]
> @adrianduffell I'm neutral on that, I think having `wcadmin` wouldn't introduce too much confusion, but I can appreciate the updated name

Given that the backend version that references wcadmin is already merged, I've gone ahead with that name on the client side PR. If we decide to change it, I vote that it should be done at the same time in both codebases.

**Comment by mattsherman** [comment]
> > @adrianduffell I'm neutral on that, I think having `wcadmin` wouldn't introduce too much confusion, but I can appreciate the updated name
> 
> Given that the backend version that references wcadmin is already merged, I've gone ahead with that name on the client side PR. If we decide to change it, I vote that it should be done at the same time in both codebases.

Agreed. Such a change in the future should be done with careful consideration.
