### ISSUE TITLE
Update product tour to ensure next button is disabled till the action is completed.

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33346]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

follow-up issue for https://github.com/woocommerce/woocommerce/issues/32421 / https://github.com/woocommerce/woocommerce/pull/33268

> The next button is disabled till the action is completed.

**Comment by ilyasfoo** [comment]
Hi @pmcpinto @verofasulo, some questions:

1. How do we determine a completed action for textarea/textbox? Since in templates we already have pre-filled fields, do we consider it completed as soon as the user inputs a keystroke in them?
2. Are all steps mandatory to be actioned?

**Comment by chihsuan** [comment]
> How do we determine a completed action for textarea/textbox? Since in templates we already have pre-filled fields, do we consider it completed as soon as the user inputs a keystroke in them?

> Are all steps mandatory to be actioned?

cc @jarekmorawski since @verofasulo is AFK this week.

**Comment by jarekmorawski** [comment]
> How do we determine a completed action for textarea/textbox? Since in templates we already have pre-filled fields, do we consider it completed as soon as the user inputs a keystroke in them?

To be perfectly honest, I'd remove the pre-filled text in the templates. It's currently lorem ipsum, which is neither helpful, nor very professional. As for your question, I think we can skip the competion check for these fields. The goal of the spotlight is to assist so when people are done with the description, they can click Next to jump to the next step.

> Are all steps mandatory to be actioned?

The opposite. I'd say that all steps are optional and people should be able to jump between them at any given moment.

**Comment by pmcpinto** [comment]
Agreed. The next button should always be enabled to avoid forcing the user to fill a specific field.

**Comment by ilyasfoo** [comment]
I agree with that. Not making any fields mandatory sounds perfect, thanks!

Closing this issue.

>It's currently lorem ipsum, which is neither helpful, nor very professional.

I agree, perhaps we should come up with a realistic description? Considering this is a "template"

**Comment by adrianduffell** [comment]
> I agree, perhaps we should come up with a realistic description? Considering this is a "template"

Yeah perhaps create a new issue for this? Lorem ipsum does seem problematic.

**Comment by ilyasfoo** [comment]
@adrianduffell Done! https://github.com/woocommerce/woocommerce/issues/33380
