### ISSUE TITLE
[Enhancement]: Add product ID to analytics leaderboards

### ISSUE THREAD

**Issue by joshbetz** [woothemes/woocommerce#33352]
### Describe the solution you'd like

The leaderboard endpoints contain "rows" of stats. These are formatted like CSV data with headings and rows. The row data is output as HTML, which isn't great for native apps. It's also missing some data and the format makes it hard to add additional data without breaking anything.

We should add structured data in a new field called `data`. Instead of returning data like a CSV, each object would be a set of key, value pairs like:

```
{
  "id": 1234,
  "name": "Awesome Steel Keyboard",
  "items sold": "3371",
  "net sales": "1944797.32",
}
```

As a bonus, if we can omit `data` from `_fields` by default, this data will only be included if you explicitly ask for it.

### Describe alternatives you've considered

We could also do this as /v4 analytics endpoints. I suspect there will be some hesitation to start introducing v4 endpoints in a piecemeal way like this though.

### Additional context

A row in the product leaderboard looks like this:

```
[
    {
        "display": "<a href='https://joshbetz.ngrok.io/wp-admin/admin.php?page=wc-admin&path=/analytics/products&filter=single_product&products=55'>Practical Silk Gloves</a>",
        "value": "Practical Silk Gloves"
    },
    {
        "display": "3,345",
        "value": 3345
    },
    {
        "display": "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>3,329,077.80</bdi></span>",
        "value": 3329077.8000000077
    }
],
```

In order to get the product ID, we have to parse the HTML and get the product ID from the URL.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
