### ISSUE TITLE
Add event tracking for shipping smart defaults

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33369]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Design overview (with new spotlight component):**
cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783

**Acceptance Criteria:**
To be assessed by the team - some things I'd like to measure:

- Task completion rate
- After how many tasks users click on the Review shipping options task
- % of stores where the first order is placed without reviewing the shipping options

ref https://github.com/woocommerce/woocommerce/issues/32318

**Comment by ilyasfoo** [comment]
Hi @SamratBiswas1 @verofasulo cc @pmcpinto, these are the tracks changes we have for shipping smart defaults. Let me know if they're ok

> Task completion rate

Existing track `wcadmin_extended_tasklist_task_completed` with props `task_name: 'review-shipping'` will be added

> After how many tasks users click on the Review shipping options task

Existing track`wcadmin_tasklist_click` with props `task_name: 'review-shipping'` will be added

> % of stores where the first order is placed without reviewing the shipping options

Unfortunately I can't find any that tracks when the first order is created. I don't think this is possible with our current tracks.

### New tracks:

| Setting      | Value |
| ----------- | ----------- |
| Name      |  `wcadmin_tasklist_shipping_recommendation_connect_store`   |
| What does the track measure      | Users who connect to WPCOM via the new shipping task from settings page |
| When does the track fire      | When the "Connect" button in connect step is clicked |
| Event properties      | `connect: true` |

| Setting      | Value |
| ----------- | ----------- |
| Name      |  `wcadmin_tasklist_shipping_recommendation_install_extensions`   |
| What does the track measure      | Users who agrees to install Jetpack & WooCommerce Shipping extension via the new shipping task from settings page. Users who already has the extension installed will not trigger this track.  |
| When does the track fire      | When the "Install & activate" is clicked and installation is completed. |
| Event properties      |  `install_extensions: true`  |

| Setting      | Value |
| ----------- | ----------- |
| Name      |  `wcadmin_tasklist_shipping_recommendation_set_location`   |
| What does the track measure      | Users who sets location via the new shipping task from settings page. |
| When does the track fire      | When the "Continue" button is clicked.   |
| Event properties      | `country: ...` store country  |

**Comment by chihsuan** [comment]
Hey @ilyasfoo FYI, I originally created [an issue](https://github.com/woocommerce/woocommerce/issues/33700) for https://github.com/woocommerce/woocommerce/issues/32318#issuecomment-1169143039, but I've closed it. I think it belongs to this task.
