### ISSUE TITLE
Update shipping task display logic

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33363]
## User Story
> As a new merchant
> I want to the task list to contain prioritized tasks
> So I can focus on what's import to set up next

## Acceptance Criteria

Do not display the shipping task on the home page when:
- The store sells digital products only

When automated shipping options have been set in #33366:
- Change the name of the shipping task to `Review shipping options` and move it the `Things to do next` section.

Otherwise, display the `"Set up shipping"` task in the `"Get ready to start selling"` section when either of the following is true:
   -  We don't know if the store sells physical products and where it's located, and ~JP is not installed~ (https://github.com/woocommerce/woocommerce/issues/32318#issuecomment-1119395274)
   -  The store is located in the UK, Australia or Canada
 

ref: https://github.com/woocommerce/woocommerce/issues/32318

**Comment by adrianduffell** [comment]
> Move the "Review shipping options task" to the "Things to do next" section

@verofasulo Do you have more info about the "Review shipping options" task? Is it the existing "Set up shipping" task, but renamed because the defaults have been applied?

**Comment by verofasulo** [comment]
> Do you have more info about the "Review shipping options" task? Is it the existing "Set up shipping" task, but renamed because the defaults have been applied?

@adrianduffell yes, exactly 😄 If the defaults are applied (conditions listed in [this issue](https://github.com/woocommerce/woocommerce/issues/32318)), the task is renamed and moved to the Things to do next section.

**Comment by chihsuan** [comment]
@verofasulo Sorry for another question. How to decide whether a user completes the `Review shipping options` task or not?

**Comment by verofasulo** [comment]
> How to decide whether a user completes the Review shipping options task or not?

That's an excellent question. To actually review shipping options, the user needs to click on one of the shipping zones as the options are all nested in a second level. This would be the most certain indicator that a user reviewed shipping options, but I don't know if we want to make it so granular or the fact that the user clicked on the task and interacted with the tooltips is enough to mark the task as completed.

@pmcpinto what do you think?

**Comment by pmcpinto** [comment]
> @pmcpinto what do you think?

@verofasulo I think we can mark it as completed when the user visits the page. I'm assuming that users don't need to do anything if they're happy with the predefined shipping methods. Makes sense?

**Comment by verofasulo** [comment]
@pmcpinto yes, we can avoid overcomplicating things. 

> I'm assuming that users don't need to do anything if they're happy with the predefined shipping methods

Yes, my point was that due to the current IA and layout, no user is able to see the predefined shipping cost just by visiting the page. 

![image](https://user-images.githubusercontent.com/98944206/174791110-2f4da5e5-19ec-45fc-861b-c850414605d7.png)

As you can see from this img, the user needs to click on the shipping zone to see the default rate.

**Comment by pmcpinto** [comment]
@verofasulo gotcha. Thanks for the clarification.

Currently, about 57% of new users set up free local shipping in the shipping task. What do you think about establishing free shipping as the default for US?

**Comment by chihsuan** [comment]
> Currently, about 57% of new users set up free local shipping in the shipping task. What do you think about establishing free shipping as the default for US?

ping @verofasulo Just in case you missed it.

**Comment by chihsuan** [comment]
I've created another issue for task complete logic, but let's keep discussing this here.

**Comment by verofasulo** [comment]
> Currently, about 57% of new users set up free local shipping in the shipping task.

Thanks, @pmcpinto ! When you say "local shipping", do you mean the entire US or Australia for example? Or is it limited to one state (e.g. Arizona)? Thank you!

**Comment by pmcpinto** [comment]
@verofasulo the entire country

**Comment by chihsuan** [comment]
@pmcpinto @verofasulo I just wanted to double check. Do we agree to mark it as completed when the user visits the page?

**Comment by verofasulo** [comment]
> I just wanted to double check. Are we agree to mark it as completed when the user visits the page?

@chihsuan yes, thank you 🙏

**Comment by pmcpinto** [comment]
@chihsuan yes. It should also fire `wcadmin_tasklist_task_completed` `task_name`: `shipping`
