### ISSUE TITLE
Add intro tooltips in Shipping Settings

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33365]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Design overview (with new spotlight component):**
cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783

**Acceptance Criteria:**

- [ ] Display intro tooltips in Shipping Settings: Shipping zones, shipping methods when a user from shipping task 
- [ ] Display intro tooltips in WCS tab If the store sells physical products, has JP and WCS installed and connected, and is located in the US

![https://user-images.githubusercontent.com/98944206/159504026-16f514c4-4c39-4b87-aeac-3a91f4c91628.gif](https://user-images.githubusercontent.com/98944206/159504026-16f514c4-4c39-4b87-aeac-3a91f4c91628.gif)

ref: https://github.com/woocommerce/woocommerce/issues/32318

**Comment by ilyasfoo** [comment]
Estimated as 8 but we should put this under its own feature flag since Spotlight may not support a partial table highlight.

**Comment by rjchow** [comment]
My heart jumped a little when I saw that the config key was named referenceElement**s** but alas it does not support multiple elements.

I have some thoughts on how to proceed - 

I'll finish this story without enhancing spotlight, regardless, so the spotlight effect by the completion of this story will cover the entire table. This needs to be done whether or not we enhance spotlight, and there will be little or no reworking required - only additional work on top to enhance spotlight.

As for approaches to enhance spotlight:

1. Upgrade spotlight itself to support multiple reference elements, it could either be done in a way that calculates the edges of the elements or apply multiple spotlights. They both have their own intricacies as the overlay works by applying an infinite border around the reference element - so the latter will need to rework this mechanism. However the latter is probably more useful in future scenarios, for highlighting multiple elements in a single step perhaps.
2. Create an invisible floating element on top of the table elements that we need (note that this will share the algorithm with above step, part 1) and then apply wp-tour-kit-spotlit class manually for our tour elements. This option will not require modifying @automattic/tour-kit at all.

The exploration of these two could be a standalone issue unrelated to working on the tour, actually

**Comment by rjchow** [comment]
For approach 1, multiple spotlights method, redoing the overlay using [svg masking](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Clipping_and_masking) to "cut holes" and [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to calculate the cutout coordinates might be a clean way to do it
