### ISSUE TITLE
Optimize existing shipping task flow

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33368]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
~With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.~

**Design overview (with new spotlight component):**
cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783

**Acceptance Criteria:**

- [ ] If the store is located in the UK, Australia or Canada:
- [ ] Same flow as now with a few optimizations in terms of copy and visual.

https://user-images.githubusercontent.com/98944206/161233363-b71277bc-82f1-48ef-bb25-151b7bc4ac09.mov

ref https://github.com/woocommerce/woocommerce/issues/32318

**Comment by moon0326** [comment]
@woocommerce/ghidorah I'm a bit confused with this task 🤔 

> With Jetpack installed and connected, alongside WCS

When both are installed and connected, we already have shipping label printing enabled. I don't think we need to prompt to install and enable WooCommerce Shipping again.

**Comment by chihsuan** [comment]
> When both are installed and connected, we already have shipping label printing enabled. I don't think we need to prompt to install and enable WooCommerce Shipping again.

@moon0326 I think we could ignore the **Description** here. It's copied from the original issue https://github.com/woocommerce/woocommerce/issues/32318 and seems to be only applicable for some cases.

**Comment by moon0326** [comment]
> 

Thanks! I'll update the description in that case.

**Comment by chihsuan** [comment]
I think we just need to make ‘Set your store location’ clickable and expandable since ShipStation UI is done in https://github.com/woocommerce/woocommerce/pull/33630.

**Comment by moon0326** [comment]
> I think we just need to make ‘Set your store location’ clickable and expandable since ShipStation UI is done in #33630.

Do we need to make each step clickable? I think that's currently not a feature and I don't see a requirement for that 🤔

**Comment by chihsuan** [comment]
> Do we need to make each step clickable? I think that's currently not a feature and I don't see a requirement for that 🤔

Actually, it's mentioned in cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783. cc @verofasulo


![Screen Shot 2022-06-29 at 15 51 52](https://user-images.githubusercontent.com/4344253/176382296-edd89e61-8208-410e-81af-b9ba7819186e.png)

**Comment by moon0326** [comment]
> > Do we need to make each step clickable? I think that's currently not a feature and I don't see a requirement for that 🤔
> 
> Actually, it's mentioned in [cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783](https://href.li/?https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/?node-id=705%3A80783). cc @verofasulo
> 
> ![Screen Shot 2022-06-29 at 15 51 52](https://user-images.githubusercontent.com/4344253/176382296-edd89e61-8208-410e-81af-b9ba7819186e.png)

Thank you! Not that I'm opposed to the idea, but I wonder the reason for it when the address is already filled 🤔

**Comment by ilyasfoo** [comment]
> Do we need to make each step clickable? 

1. Would the store location also need to be clickable on https://github.com/woocommerce/woocommerce/issues/33367?
2. Does it apply to all steps, or just store location step?

**Comment by verofasulo** [comment]
> Do we need to make each step clickable?

Yes, only the steps that have already been completed by the user. I think it's important to give the possibility to review and eventually edit the details. :)
