### ISSUE TITLE
Automatically set default shipping options

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33366]
## User story
As a new merchant
I want to shipping options set by default
So I can review it later

## Acceptance Criteria:

Automatically set the following default shipping options:

- Free shipping in the same country as the store.
- Flat rate in all other countries.

When any of the conditions are true:
- The store sells physical products, has JP and WCS installed and connected, and is located in the US.
- The store sells physical products, and is not located in US/Canada/Australia/UK (irrelevant if JP is installed or not).
- The store sells physical products and is located in US, but JP and WCS are not installed.

ref: https://github.com/woocommerce/woocommerce/issues/32318

**Comment by moon0326** [comment]
Hi @verofasulo ✋ 

I have a couple of questions.

> The store sells physical products, and is not located in US/Canada/Australia/UK (irrelevant if JP is installed or not).

Does WCS also irrelevant in this case?

**Comment by verofasulo** [comment]
Hi @moon0326 🤗

> Does WCS also irrelevant in this case?

Yes, as we offer this service only if the store is located in the US.

**Comment by moon0326** [comment]
Hi @verofasulo 

I have another question.

Let's say a merchant selects "Downlaods" as product type on the initial OBW and then changes it to "Physical products" after a week or so. Do we still want to add the default shipping options in that case? or do we want to set the default shipping options within X days?

It's possible that the merchant already set the shipping methods at that point.

**Comment by verofasulo** [comment]
> Let's say a merchant selects "Downlaods" as product type on the initial OBW and then changes it to "Physical products" after a week or so.

Good point @moon0326 , I didn't think about this edge case! 

> Do we still want to add the default shipping options in that case?

Yeah, I think it makes total sense to update the shipping options as well. 

> It's possible that the merchant already set the shipping methods at that point.

I'm assuming that it's not happened as if the selected product type was "Downloads", there was no reason to set up shipping.
