### ISSUE TITLE
Display WCS as recommended extension in Shipping Settings

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33370]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Design overview (with new spotlight component):**
cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783

**Acceptance Criteria:**

- [ ] Display WCS as recommended extension to be installed in Shipping Settings If the store sells physical products and is located in US, but JP and WCS are not installed and connected:

<img width="1440" alt="WooCommerce _ Settings" src="https://user-images.githubusercontent.com/4344253/172814321-76a3a716-184f-44da-be9f-45911c58685e.png">

ref https://github.com/woocommerce/woocommerce/issues/32318

**Comment by adrianduffell** [comment]
This recommendation already exists, however it seems it is not yet be limited to US and physical products.

**Comment by chihsuan** [comment]
>  Display WCS as recommended extension to be installed in Shipping Settings If the store sells physical products and is located in US, but JP and WCS are not installed:

@verofasulo The existing page still displays WCS if **installed but not activated**. I just want to confirm that we're going to hide WCS in Shipping Settings if installed?

**Comment by verofasulo** [comment]
> The existing page still displays WCS if installed but not activated. I just want to confirm that we're going to hide WCS in Shipping Settings if installed?

@chihsuan the flow is different with the new design, so the two steps are incorporated together.

**Current design:**
When the user clicks on `Get started`, we install WCS and display this message to nudge the user to install JP to complete the activation:

<img width="1952" alt="Screenshot 2022-06-21 at 09 35 50" src="https://user-images.githubusercontent.com/98944206/174743426-e74b1b09-6f90-461c-b144-4b450a5644cd.png">

**New design:**
When the user clicks on `Get started`, they get directed to this page with all the steps to install and activate WCS:

![image](https://user-images.githubusercontent.com/98944206/174743710-27a486dd-1a7c-4b70-a776-f420d37a477b.png)

![image](https://user-images.githubusercontent.com/98944206/174743888-c758bcfd-c9aa-4a21-a7b3-7fb40ed29548.png)


If the user doesn't complete all the steps (eg. they leave the stepper before activating WCS), we can still display the banner (img attached below) changing the CTA from `Get started` to `Activate`.

![image](https://user-images.githubusercontent.com/98944206/174744347-e29e79ff-2741-41c8-bbb4-a6f3e7dc60f5.png)

**Comment by chihsuan** [comment]
> https://user-images.githubusercontent.com/98944206/174744347-e29e79ff-2741-41c8-bbb4-a6f3e7dc60f5.png

@verofasulo Thanks for the clarification! But I would like to know when to display the banner. From the original issue (https://github.com/woocommerce/woocommerce/issues/32318):

>  If the store sells physical products and is located in US, but JP and WCS are not installed:
> - Display intro tooltips in Shipping Settings: Shipping zones, shipping methods, **WCS as recommended extension to be installed.**

So we'll only display the banner when JP and WCS are not installed? In the current design, we display the banner when it is **not activated**. (Still display it if installed but not activated)

**Comment by verofasulo** [comment]
Hey @chihsuan yes, as mentioned in m previous reply it makes sense to display the banner if WCS is installed but not activated yet:

> If the user doesn't complete all the steps (eg. they leave the stepper before activating WCS), we can still display the banner (img attached below) changing the CTA from `Get started` to `Activate`.

Does it make sense? :)

**Comment by chihsuan** [comment]
@verofasulo Ah, thanks, make sense to me!
