### ISSUE TITLE
[GlobalStep] Language translation fails to display for "GET THE BASICS" and "GROW YOUR STORE" on "Free feature" step of OBW.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#33375]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Language translation fails to display for "GET THE BASICS" and "GROW YOUR STORE" on "Free feature" step of OBW.

### Expected behavior

"GET THE BASICS" and "GROW YOUR STORE" should be translated to French language on "Free feature" step of OBW.

### Actual behavior

Language translation fails to display for "GET THE BASICS" and "GROW YOUR STORE" on "Free feature" step of OBW.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.6.0-rc.3.
3. Go to Dashboard > Settings > General
4. Change the site language to a language with good translation coverage such as French (France)
5. Go to Dashboard > Updates and click on the button to update translations.
6. Go to "Free feature" step and click Dropdown Button
7. Observe that Language translation fails to display for "GET THE BASICS" and "GROW YOUR STORE" on "Free feature" step.

### Instruction Link:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-6.6#cleanup-and-fix-translation-path-changes-33226

### Screenshot:

![#33375](https://user-images.githubusercontent.com/41110392/172871789-7d67fe85-4c5e-4d94-8ca4-953037dbce9c.jpg)

### WordPress Environment

Woocommerce Version: 
WooCommerce: 6.6.0-rc.3
Wordpress version: 6.0

PC:
Windows 10
Chrome(Version 102.0.5005.63) 
Firefox(Version 101.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.6.0
REST API Version: ✔ 6.6.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.29
PHP Post Max Size: 1 Go
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.0
WC Database Prefix: wp_
Taille totale de la base de données: 8.88MB
Taille de la base de données: 6.46MB
Taille de l’index: 2.42MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_mapping_to_external_entities: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_templates: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_scheduled_tasks: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_subscribers: Données : 0.02MB + Index : 0.13MB + Moteur InnoDB
wp_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 2.42MB + Index : 0.08MB + Moteur InnoDB
wp_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1
mailpoet_page: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: par John Blackbourn – 3.9.0
Companion Plugin: par Osk – 1.26
WooCommerce: par Automattic – 6.6.0-rc.3

### Inactive Plugins (3) ###

Akismet Anti-Spam: par Automattic – 4.2.4
Hello Dolly: par Matt Mullenweg – 1.7.2
Jetpack: par Automattic – 11.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base de la boutique: #7 - /shop/
Panier: #8 - /cart/
Commander: #9 - /checkout/
Mon compte: #10 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-10 08:38:04 +00:00
Options: ✔
Notes: 37
Onboarding: completed

### Action Scheduler ###

Terminé: 3
Oldest: 2022-06-09 08:39:22 +0000
Newest: 2022-06-09 08:43:53 +0000

En attente: 1
Oldest: 2022-06-10 08:39:22 +0000
Newest: 2022-06-10 08:39:22 +0000

### Status report information ###

Generated at: 2022-06-09 14:28:45 +00:00
`

</details>

**Comment by rjchow** [comment]
Thank you for filing this! I have some additional information on this:

This bug has existed for awhile, I tested 6.4.1 and it manifested there as well. Not sure how much further back it goes.

The string in question appears here: https://github.com/woocommerce/woocommerce/blob/5d076cc7d47e77580c73ca3afbebe732038aef50/plugins/woocommerce/src/Internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php#L136

I suspect it might have something to do with i18n settings not being applied to this API, as I can see the plain english text showing in the API payload, on a site with French language:

![image](https://user-images.githubusercontent.com/27843274/172873669-44b71d16-8440-4684-9ac9-b5cdfc3b2389.png)

**Comment by chihsuan** [comment]
It seems like we should change text-domain on woocommerce.com. I've created a PR for it.

However, There are some known issues with translations on the endpoints.
p2: p1654830159868539/1654829580.506039-slack-C01SFMVEYAK
slack thread: p1654830061997579/1654829580.506039-slack-C01SFMVEYAK

**Comment by chihsuan** [comment]
Closing this in favor of #32242.
