### ISSUE TITLE
Move linting check from pre-commit to pre-push

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#33387]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently the PHP linter runs on a [pre-commit hook](https://github.com/woocommerce/woocommerce/blob/trunk/.husky/pre-commit#L4). This means if there are any linter violations, even in unrelated code in the same file, you get blocked from completing your commit. I find this disruptive when I'm "in the flow" and this has sometimes caused me to resort to committing with `--no-verify`, which is obviously not a great habit to get into. For new contributors, this can be confusing and discouraging ([example](https://github.com/woocommerce/woocommerce/issues/33135#issuecomment-1147334703)).

I would like to propose that the linter check instead happen on the pre-push hook.

* Better supports the habit of making atomic commits. Fixing linting violations can happen in a separate commit.
* Doesn't break your "flow".
* Still ensures that new linting violations aren't introduced to the codebase.

**Comment by roykho** [comment]
Hi @coreymckrill - We've recently made a change with this [PR](https://github.com/woocommerce/woocommerce/pull/33584) to validate only code that you've changed and not the entire file. Do you still feel we need to change to use `pre-push`?

**Comment by coreymckrill** [comment]
🤔 I guess if it was changed to pre-push, we'd end up with a proliferation of "fix linting errors" commits. Since it's now only checking lines of code that you've added or changed, I guess you'd want to be able to correct problems in your changes before committing. So, I think I'm fine keeping this on pre-commit now 👍
