### ISSUE TITLE
When creating a refund via the API, the "refunded_payment" property does not appear in POST requests

### ISSUE THREAD

**Issue by iamgabrielma** [woothemes/woocommerce#33389]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we perform a POST request to the `/wc/v3/orders/$ORDER_ID/refunds&_method=post` endpoint, the 
 `refunded_payment` property is not part of the response, however, when we perform a GET request to `/wc/v3/orders/$ORDER_ID/refunds&_method=get`, the property can be found in the response.

Related: https://github.com/woocommerce/woocommerce-ios/issues/6704

### Expected behavior

The `refunded_payment` property to appear in the POST request. The docs seem to include it as well on its example: https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-refund 

### Actual behavior

The `refunded_payment` property does not appear in the POST request, only in the GET request.

### Steps to reproduce

Perform POST and GET requests to the API using the refunds endpoint, and check the response details. As an example:

POST `/wc/v3/orders/$ORDER_ID/refunds&_method=post`

Response:
```
{ "data": { "id": 6680, "date_created": "2022-06-08T09:05:22", "date_created_gmt": "2022-06-08T09:05:22", "amount": "0.83", "reason": ":)", "refunded_by": 1, "meta_data": [ { "id": 3959, "key": "_wcpay_refund_id", "value": "re_3L8KoO2Ev1jcPAUs1jPqhXeL" } ], "line_items": [ { "id": 25, "name": "TEST Product!", "product_id": 6649, "variation_id": 0, "quantity": -1, "tax_class": "", "subtotal": "-0.83", "subtotal_tax": "0.00", "total": "-0.83", "total_tax": "0.00", "taxes": [], "meta_data": [ { "id": 238, "key": "_refunded_item_id", "value": "24", "display_key": "_refunded_item_id", "display_value": "24" } ], "sku": "", "price": 0.826446, "parent_name": null } ], "shipping_lines": [], "tax_lines": [], "fee_lines": [], "_links": { "self": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679/refunds/6680" } ], "collection": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679/refunds" } ], "up": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679" } ] } } }
```

GET: `/wc/v3/orders/$ORDER_ID/refunds&_method=get`

Response
```
{ "data": [ { "id": 6680, "date_created": "2022-06-08T09:05:22", "date_created_gmt": "2022-06-08T09:05:22", "amount": "0.83", "reason": ":)", "refunded_by": 1, "refunded_payment": true, "meta_data": [ { "id": 3959, "key": "_wcpay_refund_id", "value": "re_3L8KoO2Ev1jcPAUs1jPqhXeL" } ], "line_items": [ { "id": 25, "name": "TEST Product!", "product_id": 6649, "variation_id": 0, "quantity": -1, "tax_class": "", "subtotal": "-0.83", "subtotal_tax": "0.00", "total": "-0.83", "total_tax": "0.00", "taxes": [], "meta_data": [ { "id": 238, "key": "_refunded_item_id", "value": "24", "display_key": "_refunded_item_id", "display_value": "24" } ], "sku": "", "price": 0.826446, "parent_name": null } ], "shipping_lines": [], "tax_lines": [], "fee_lines": [], "_links": { "self": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679/refunds/6680" } ], "collection": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679/refunds" } ], "up": [ { "href": "https://mywootestingstore.mystagingwebsite.com/wp-json/wc/v3/orders/6679" } ] } } ] }
```

Note that `"refunded_payment": true` is missing in the POST request.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://mywootestingstore.mystagingwebsite.com
Site address (URL): https://mywootestingstore.mystagingwebsite.com
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.83.1
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.35-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 6.06MB
Database Data Size: 4.12MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.47MB + Index: 0.27MB + Engine InnoDB
wp_posts: Data: 1.14MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
custom_css: 3
feedback: 1
jp_img_sitemap: 1
jp_pay_product: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 2
page: 41
post: 2
product: 23
product_variation: 4
revision: 5
shop_order: 22
shop_order_refund: 21
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-Spam: by Automattic – 4.2.4
Cleaner Gallery: by Justin Tadlock – 1.1.0
Featured Image from URL: by Marcel Jacques Machado – 2.7.2
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.54
Jetpack Beta Tester: by Automattic – 3.1.2
Jetpack: by Automattic – 9.9-1045838692-g1bb54d2
Amazon Link Localizer: by Prourls Ltd – 1.6
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 (update to version 2.1.3 is available)
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce One Page Checkout: by Automattic – 1.9.4
WooCommerce Payments: by Automattic – 4.2.0 (update to version 4.2.1 is available)
WooCommerce: by Automattic – 6.5.1
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 12.6.1
WP Staging: by WP-Staging – 2.6.4

### Inactive Plugins (1) ###

Jetpack: by Automattic – 11.1-a.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
deposit (deposit)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #102 - /shop/
Cart: #103 - /cart/
Checkout: #104 - /checkout/
My account: #105 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Payments ###

Version: 4.2.0
Connected to WPCOM: Yes
Blog ID: 121710041
Account ID: acct_1L6w0D2Ev1jcPAUs

### Action Scheduler ###

Complete: 400
Oldest: 2022-06-01 08:42:56 +0000
Newest: 2022-06-10 03:08:14 +0000

### Status report information ###

Generated at: 2022-06-10 08:57:12 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by iamgabrielma** [comment]
Adding additional notes from p1655114212211609?thread_ts=1654743450.371799&cid=CB0GAP5EK-slack-CB0GAP5EK

> It would seem that it's filtered out in the POST request because [the schema](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-order-refunds-v2-controller.php#L394-L398) specifies it to be for view context only. I think adding a property to response should be fine, so we can update it to include it in the edit context

**Comment by Sidsector9** [comment]
Hi @nielslange I would like to pick this up for contributor's day.
