### ISSUE TITLE
[GlobalStep] "Store Management" fails to display after selecting "Paid theme" while OBW flow.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#33405]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Store Management" fails to display after selecting "Paid theme" while OBW flow.

### Expected behavior

"Store Management" should be displad after selecting "Paid theme" while OBW flow.

### Actual behavior

"Store Management" fails to display after selecting "Paid theme" while OBW flow.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.6.0.
3. Complete "Store Details" by selecting "Storefront".
4. Complete all steps on setup checklist.
5. Go to Woocommerce > Home.
6. Verify that Store Management Links are shown.
7. Click on "Store Details" on Setup Check List.
8. While finishing the OBW flow select a "Paid" theme on Theme step.
9. After the page reload, observe that "Store Management" fails to display after selecting "Paid theme".

### Video:

https://user-images.githubusercontent.com/41110392/173368054-a70c79fe-a8e1-4f4e-b71f-db72799ae119.mp4

### WordPress Environment

Woocommerce Version: 
WooCommerce: 6.6.0
Wordpress version: 6.0

PC:
Windows 10
Chrome(Version 102.0.5005.63) 
Firefox(Version 101.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.6.0
REST API Version: ✔ 6.6.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.7
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.83.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.0
WC Database Prefix: wp_
Total Database Size: 3.38MB
Database Data Size: 1.76MB
Database Index Size: 1.62MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.31MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 32
page: 8
post: 3
product: 23
product_variation: 11
revision: 2
shop_coupon: 2
shop_order: 18
shop_order_refund: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
Jetpack: by Automattic – 11.0
WooCommerce: by Automattic – 6.6.0
WP Crontrol: by John Blackbourn & crontributors – 1.12.1
WP Mail Logging: by Wysija – 1.10.4

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.4
Gutenberg: by Gutenberg Team – 13.4.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-14 06:30:11 +00:00
Options: ✔
Notes: 27
Onboarding: completed

### Action Scheduler ###

Complete: 108
Oldest: 2022-06-13 06:40:10 +0000
Newest: 2022-06-13 12:44:38 +0000

Pending: 2
Oldest: 2022-06-13 13:43:28 +0000
Newest: 2022-06-14 06:31:37 +0000

### Status report information ###

Generated at: 2022-06-13 13:42:47 +00:00
`

</details>

**Comment by tammullen** [comment]
I think this is because the task list experiments aren't showing the task item for installing the premium theme so it looks like all the tasks are complete but the premium theme task isn't being shown and isn't complete.

![Screenshot 2022-06-13 at 22 03 59](https://user-images.githubusercontent.com/24649833/173445183-5fb2c478-30da-4b9a-8ec4-db0c9a6c078a.png)

![Screenshot 2022-06-13 at 22 03 47](https://user-images.githubusercontent.com/24649833/173445198-8b4b23d4-c042-46b1-b394-bb2b81352cec.png)

![Screenshot 2022-06-13 at 22 03 25](https://user-images.githubusercontent.com/24649833/173445208-d961bd0b-e158-4ee0-b819-be279571c493.png)

I notice this also happens for the task list experiments in 6.5.1

![Screenshot 2022-06-13 at 22 09 40](https://user-images.githubusercontent.com/24649833/173445987-15d57f5b-503c-4a07-a364-3258ddbfc990.png)
![Screenshot 2022-06-13 at 22 09 23](https://user-images.githubusercontent.com/24649833/173445968-5f13b13f-0933-4487-97cf-32813d5eebea.png)

**Comment by mattsherman** [comment]
This is fixed by https://github.com/woocommerce/woocommerce/pull/33178, which will be in WooCommerce 6.7
