### ISSUE TITLE
Rest API Call responding for create product  [woocommerce_product_invalid_image_id]

### ISSUE THREAD

**Issue by qamaruldinhamza** [woothemes/woocommerce#33408]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi Woocommerce Team, 

I am a web developer and implementing a sync between woocommerce and custom build website, because my client want to transfer all his products to woocommerce when his vendor create in custom app, all is working fine just one thing is creating issue, which is an error related to invalid image id, because images are taking little time in upload or maybe some glitch on wp side, but I found the solution inside the plugin for now and did it, but when we will update plugin it will cause issue again.

https://github.com/woocommerce/woocommerce/blob/3fd9ee99aa72b9dc1524ab7b2a8be06add53161f/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L327

In this file and this line I commented for now, this is the exception which is throwing, once I commented it then my products are importing fine, all images are also importing, I used sleep function after attachment upload right before this if statement it also worked, it looks like there's a little delay in image upload and it's checking earlier.

### Expected behavior

It should wait for the upload or at least id creation for the image.

### Actual behavior

It's triggering wp_attachment_is_image this function earlier then the image upload.

### Steps to reproduce

https://github.com/woocommerce/woocommerce/blob/3fd9ee99aa72b9dc1524ab7b2a8be06add53161f/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L327

This is the file and line number

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.geeksunleash.com
Site address (URL): https://www.geeksunleash.com
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.51 (Debian)
PHP Version: 7.4.29
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: sty_
Total Database Size: 4143.22MB
Database Data Size: 3312.75MB
Database Index Size: 830.47MB
sty_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
sty_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sty_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
sty_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.27MB + Engine InnoDB
sty_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sty_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
sty_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_actionscheduler_actions: Data: 18.05MB + Index: 33.19MB + Engine InnoDB
sty_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_actionscheduler_logs: Data: 13.02MB + Index: 10.03MB + Engine InnoDB
sty_addonlibrary_addons: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
sty_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_comments: Data: 0.33MB + Index: 0.33MB + Engine InnoDB
sty_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_delivery_time: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_dokan_distance_rate_shipping: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_dokan_follow_store_followers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_report_abuse_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_shipping_tracking: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_dokan_table_rate_shipping: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_dokan_vendor_balance: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sty_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_elasticemail_log: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
sty_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_e_submissions: Data: 0.06MB + Index: 0.27MB + Engine InnoDB
sty_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
sty_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_fpd_products: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
sty_fpd_views: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
sty_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_gf_entry: Data: 0.25MB + Index: 0.03MB + Engine InnoDB
sty_gf_entry_meta: Data: 51.02MB + Index: 2.00MB + Engine InnoDB
sty_gf_entry_notes: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
sty_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_gf_form_meta: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
sty_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
sty_graphist_elementor_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_lecm_rewrite: Data: 1.50MB + Index: 0.00MB + Engine InnoDB
sty_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_login_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_options: Data: 90.22MB + Index: 9.75MB + Engine InnoDB
sty_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_postmeta: Data: 2400.63MB + Index: 614.81MB + Engine InnoDB
sty_posts: Data: 332.55MB + Index: 96.14MB + Engine InnoDB
sty_signups: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
sty_sm_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_tatum_lazy_nft: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_tatum_prepared_nft: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_termmeta: Data: 0.27MB + Index: 0.27MB + Engine InnoDB
sty_terms: Data: 0.47MB + Index: 0.69MB + Engine InnoDB
sty_term_relationships: Data: 8.52MB + Index: 5.52MB + Engine InnoDB
sty_term_taxonomy: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
sty_usermeta: Data: 1.48MB + Index: 0.47MB + Engine InnoDB
sty_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
sty_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
sty_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
sty_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sty_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_wc_product_attributes_lookup: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
sty_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wc_product_meta_lookup: Data: 33.56MB + Index: 51.13MB + Engine InnoDB
sty_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_account: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_account_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_category: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_export_order_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_export_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_order_rawdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_price_rule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_product: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
sty_wk_woo_shopify_product_rawdata: Data: 320.52MB + Index: 0.00MB + Engine InnoDB
sty_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wplsl_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wplsl_configs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wplsl_countries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wplsl_markers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wplsl_storelogos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wplsl_stores: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sty_wplsl_stores_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sty_wpr_rucss_resources: Data: 21.50MB + Index: 1.38MB + Engine InnoDB
sty_wpr_rucss_used_css: Data: 0.36MB + Index: 0.05MB + Engine InnoDB
sty_wpuf_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sty_wpuf_transaction: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.39MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 8
acf-field-group: 4
attachment: 195862
custom_css: 1
custom-css-js: 1
customize_changeset: 219
dokan_announcement: 4
e-landing-page: 2
elementor_library: 32
giftcard: 4
merch: 385
nav_menu_item: 15
oembed_cache: 22
page: 30
post: 2
postman_sent_mail: 1
product: 10919
product_variation: 285958
revision: 4618
shop_coupon: 685
shop_order: 141
shop_order_refund: 1
shop_subscription: 38
ticket: 18
ticket_history: 10
ticket_reply: 6
wp_global_styles: 1
wpuf_forms: 1
wpuf_input: 2
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (60) ###

Query Monitor: by John Blackbourn – 3.9.0
Gravity Forms: by Gravity Forms – 2.5.16
Admin Menu Editor: by Janis Elsts – 1.10.1
Advanced Custom Fields: by Delicious Brains – 5.12.2
Astra Pro: by Brainstorm Force – 3.6.6
Awesome Support: by Awesome Support Team – 6.0.14
Better Search Replace: by Delicious Brains – 1.4
Checkout Address AutoFill For WooCommerce Pro: by zetamatic – 2.1.1
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 2.14.3
Colorlib Login Customizer: by Colorlib – 1.3.1
Custom Post Type UI: by WebDevStudios – 1.11.2
Disable Gutenberg: by Jeff Starr – 2.6
Dokan: by weDevs – 3.4.3
Dokan Pro: by weDevs – 3.5.6
Download Plugins and Themes from Dashboard: by WPFactory – 1.8.1
Duplicate Page: by mndpsingh287 – 4.4.8
Elastic Email Sender: by Elastic Email Inc. – 1.2.5
Ele Custom Skin: by Dudaster.com – 3.1.5
Elementor Pro: by Elementor.com – 3.6.5
Elementor: by Elementor.com – 3.6.4
Essential Addons for Elementor: by WPDeveloper – 5.1.0
PayPal Express Checkout Payment Gateway for WooCommerce ( Basic ): by WebToffee – 1.7.1
Fancy Product Designer Plus: by fancyproductdesigner.com – 1.3.5
Fancy Product Designer: by fancyproductdesigner.com – 4.7.5
Geek Rocks: by Your Name – 0.1.0
Graphist for Elementor: by Merkulove – 1.2.1
Gravity Forms Advanced Post Creation Add-On: by Gravity Forms – 1.2
Gravity Forms User Registration Add-On: by Gravity Forms – 5.0
Order Sync App: by qamar – 1.0
Order Tip for WooCommerce: by Adrian Emil Tudorache – 1.2.2
LoginWP (Formerly Peter's Login Redirect): by LoginWP Team – 3.0.0.8
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.385

Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Sezzle WooCommerce Payment: by Sezzle – 4.0.4
String Locator: by Clorith – 2.5.0
Monobunt Syncspider: by Monobunt – 1.0.32
NFT Maker: by Lukas Kotol – 2.0.28
Under Construction: by WebFactory Ltd – 3.93
Unlimited Elements for Elementor: by Unlimited Elements – 1.5.11
User Menus: by Code Atlantic – 1.2.9
User Role Editor: by Vladimir Garagulya – 4.61.2
User Switching: by John Blackbourn & contributors – 1.5.8
Visibility Logic for Elementor: by StaxWP – 2.3.0
W3 Total Cache: by BoldGrid – 2.2.1
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.0
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.2
Woo Product Category Discount: by WooExtend – 4.2
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.6.3
WooCommerce PayPal Payments: by WooCommerce – 1.8.0 (update to version 1.8.1 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.28 (update to version 1.26.0 is available)
WooCommerce Subscriptions: by WooCommerce – 4.2.0
WooCommerce Zapier: by OM4 Software – 2.3.0
WooCommerce: by Automattic – 6.5.1
WooPanel – FrontEnd Manager for Store Manager and WooCommerce Vendor: by NetBase team – 2.0.0
WP File Manager: by mndpsingh287 – 7.1.4
WP User Frontend: by weDevs – 3.5.27
WooCommerce Shopify Connector: by Webkul – 2.1.0
YayMail - WooCommerce Email Customizer: by YayCommerce – 2.9
Zapier for WordPress: by Zapier – 1.0.4

### Inactive Plugins (13) ###

All-in-One WP Migration: by ServMask – 7.61
Breeze: by Cloudways – 2.0.3
Gallery Slider for WooCommerce: by ShapedPlugin – 1.1.6
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.77
Post SMTP: by Post SMTP – 2.0.26
Real-Time Find and Replace: by Marios Alexandrou – 4.0.2
Redis Object Cache: by Till Krüss – 2.0.25
Shopify Connector for WooCommerce: by CedCommerce – 1.0.3
Simple Custom CSS and JS: by SilkyPress.com – 3.39
SiteGround Central: by SiteGround – 2.0.3
Ultimate Gift Cards For WooCommerce: by WP Swings – 2.4.0
WooCommerce Admin: by WooCommerce – 3.3.2
WP Rocket: by WP Media – 3.10.9

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.14.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
product_pack (product_pack)
pw gift card (pw-gift-card)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
wgm_gift_card (wgm_gift_card)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 3.7.9 (update to version 3.8.2 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra/woocommerce/emails/admin-new-order.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.geeksunleash.com
Subscription Statuses: wc-active: 37
wc-pending-cancel: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Ohio

### Subscriptions by Payment Gateway ###

Authorize.Net Credit Card: wc-active: 37
wc-pending-cancel: 1

### Payment Gateway Support ###

PayPal Express: products
Sezzle: products
refunds

Authorize.Net Credit Card: products
card_types
payment_form
inline
lightbox
tokenization
token_editor
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
apple_pay
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ✔

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Action Scheduler ###

Canceled: 1
Oldest: 2022-06-07 15:12:04 +0000
Newest: 2022-06-07 15:12:04 +0000

Complete: 58,116
Oldest: 2022-05-24 16:11:01 +0000
Newest: 2022-06-13 21:53:21 +0000

Pending: 77
Oldest: 2022-06-14 09:42:26 +0000
Newest: 2022-07-13 19:02:28 +0000

### WooCommerce Zapier ###

Database Version: ✔ 14
Detailed Logging Enabled: No
Legacy Mode Disabled: ✔ Yes
SSL: ✔ Yes
REST API Authentication Key(s): ❌ 0
Task History Record Count: ✔ 1
Product Action Count: 1

### Status report information ###

Generated at: 2022-06-14 03:31:32 +05:30
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by qamaruldinhamza** [comment]
The same thing is happening with the variations, I also commented this line of code and it's working fine, but when I uncomment this line it stopped working. 

https://github.com/woocommerce/woocommerce/blob/3fd9ee99aa72b9dc1524ab7b2a8be06add53161f/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php#L386

Please check, if this line of code is unnecessary then remove it or solve that issue. Or at least provide any hook on this place so that we can perform whatever we want outside of the plugin and updates don't remove our customisations.

Thanks

**Comment by roykho** [comment]
Hi @qamaruldinhamza - Thanks for reporting however you did not provide exact steps as to how to replicate your issue. Please provide that so we can assess further.

**Comment by qamaruldinhamza** [comment]
Hi, you can regenerate this issue when you submit any product using API via PHP code, I am using woocommerce SDK in PHP and creating products according to your given API, and using version 3, but I was getting this message for all requests. then I edited the woocommerce plugin in Wordpress and commented the line https://github.com/woocommerce/woocommerce/commit/3fd9ee99aa72b9dc1524ab7b2a8be06add53161f

If you need more info than I can provide you that, now I will be fully active on this issue
