### ISSUE TITLE
Reminder bar appears above navigation sidebar when new navigation is enabled

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#33420]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The reminder bar (see image below) should only span the content section of the site, which it does with the classic navigation:

![image](https://user-images.githubusercontent.com/444632/173664202-b1124562-4d4b-488d-b116-af6d1f6b6720.png)

However, when the new navigation is enabled it spans the entire site width, appear above the navigation sidebar:

![image](https://user-images.githubusercontent.com/444632/173663578-d4469227-40d2-49da-957b-71019fb1efe8.png)

### Expected behavior

The reminder bar should only appear above the content and not above the sidebar with the new navigation enabled.						

### Actual behavior

The reminder bar appears above the new navigation	

### Steps to reproduce

1. Create a new site
2. Install WooCommerce
3. Enable marketing and enable the new navigation in `WooCommerce -> Settings -> Advanced -> Features`
4. Navigate to the _Orders_ page (or other), where the reminder bar is displayed
5. Observe the incorrect UI

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
I'll close this issue as the new navigation was paused a few months ago.
