### ISSUE TITLE
Undismissable message: "Your store's uploads directory is browsable via the web"

### ISSUE THREAD

**Issue by CodeSmith32** [woothemes/woocommerce#33436]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I click "Dismiss" on the admin notice, I would expect it to hide after the page reloads, but it doesn't.

```
Your store's uploads directory is browsable via the web.
```

I looked in the code, though. Simple fix:

```
// woocommerce/includes/admin/views/html-notice-uploads-directory-is-unprotected.php: line 15

<a class="woocommerce-message-close notice-dismiss" href="<?php echo esc_url( wp_nonce_url( add_query_arg( 'wc-hide-notice', 'uploads_directory_is_public' ), 'woocommerce_hide_notices_nonce', '_wc_notice_nonce' ) ); ?>"><?php esc_html_e( 'Dismiss', 'woocommerce' ); ?></a>
```

According to `woocommerce/includes/admin/class-wc-admin-notices.php: line 42 / line 545`, the **public** in `uploads_directory_is_public` should be **unprotected** instead: `uploads_directory_is_unprotected`.

As proof, I was able to get it to hide by manually modifying the url.

### Expected behavior

The notice should not appear again when the page reloads.

### Actual behavior

The message *doesn't* go away.

### Steps to reproduce

1. Get notice message to show up if it is not already (`Options +Indexes`, etc.)
2. Click dismiss
3. It will not hide the message

### WordPress Environment ###

WordPress address (URL): <redacted>
Site address (URL): <redacted>
WC Version: 6.6.0
REST API Version: ✔ 6.6.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for reporting this, @CodeSmith32: I can replicate the problem successfully. We'll get round to this as soon as we can, but we would also be receptive to any PR you or others might submit for this (looks like you already have a good handle on what's needed).
