### ISSUE TITLE
Delete a shipping class via the data store

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#33458]
### Description

Add the code to be able to delete shipping classes through the products data store.

_For now, this should be marked as experimental/internal as we iterate on the API so that it is clear that this is incomplete and subject to change_.

#### _Delete_
**HTTP Request**
> **DELETE** `/wp-json/wc/v3/products/shipping_classes/<id>`

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-shipping-class

**Properties**
| Parameter | Type | Description |
| --------- | -------- | -------- |
| `force` | string | Required to be `true`, as resource does not support trashing. |

### Acceptance criteria
- [ ] Data store updates
- [ ] Unit tests
- [ ] Documentation with examples

**Comment by louwie17** [comment]
Fixed as part of #33765
