### ISSUE TITLE
Get/list all shipping classes via data store

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#33457]
### Description

Add the code to be able to get the shipping classes through the products data store.

_For now, this should be marked as experimental/internal as we iterate on the API so that it is clear that this is incomplete and subject to change_.

#### _Get_
**Description**
> This API lets you retrieve a shipping class by ID.

**HTTP Request**
> **GET** `/wp-json/wc/v3/products/shipping_classes/<id>`

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-shipping-class

#### _List all_
**Description**
> This API lets you retrieve all shipping classes.

**HTTP Request**
> **GET** `/wp-json/wc/v3/products/shipping_classes`

**Properties**
Parameter | Type | Description
--------- | -------- | --------
context | string | Scope under which the request is made; determines fields present in response. Options: view and edit. Default is view.
page | integer | Current page of the collection. Default is 1.
per_page | integer | Maximum number of items to be returned in result set. Default is 10.
search | string | Limit results to those matching a string.
exclude | array | Ensure result set excludes specific ids.
include | array | Limit result set to specific ids.
offset | integer | Offset the result set by a specific number of items.
order | string | Order sort attribute ascending or descending. Options: asc and desc. Default is asc.
orderby | string | Sort collection by resource attribute. Options: id, include, name, slug, term_group, description and count. Default is name.
hide_empty | boolean | Whether to hide resources not assigned to any products. Default is false.
product | integer | Limit result set to resources assigned to a specific product.
slug | string | Limit result set to resources with a specific slug.

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-shipping-classes

### Acceptance criteria
- [ ] Data store updates
- [ ] Unit tests
- [ ] Documentation with examples

**Comment by louwie17** [comment]
Fixed as part of #33765
