### ISSUE TITLE
[Enhancement]: Make it possible to highlight the VAT number field if there is an error (plugin: EU VAT Number)

### ISSUE THREAD

**Issue by devplus-bram** [woothemes/woocommerce#33516]
### Describe the solution you'd like

Plugin: EU VAT Number
It would be nice if the `.woocommerce-invalid` CSS class is added to the `.form-row` container of the VAT number field if there is an error concerning the VAT number (e.g. if an invalid VAT number is filled in).

**Comment by jonathansadowski** [comment]
Hi @devplus-bram,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs and enhancement requests for WooCommerce and the other projects we manage in this repository.

The enhancement you are requesting seems to be in the EU VAT Number plugin, which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/).
