### ISSUE TITLE
Redirect users to the shipping setting when the user clicks on the shipping task

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#33526]
This is part of https://github.com/woocommerce/woocommerce/issues/32318

**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Design overview (with new spotlight component):**
[cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783](https://href.li/?https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/?node-id=705%3A80783)

**Acceptance Criteria:**
Given a store with the following OBW selections
| Section | Value |
|------|-------|
| Product type | physical products| 
| Store Details[Country / Region] | US or not one of the US, Canada, Australia, and the UK

When a user clicks on the shipping task on WooCommerce -> Home
Then redirect the user to WooCommerce -> Settings -> Shipping

**Comment by chihsuan** [comment]
@moon0326 I just found we probably don't need this because we'll add a new task `Review shipping options` under `Things to do next` section in https://github.com/woocommerce/woocommerce/issues/33363 based on the same condition.

**Comment by moon0326** [comment]
Thank you @chihsuan 

Closing this issue since it's a duplicate.
