### ISSUE TITLE
Product creation experience: add more context about product data

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33539]
**Description:** The product data naming is far from being self-explanatory and it can be challenging for users to understand the differences between all the product types. This is one of those cases where it's better to provide documentation to help users understand how to complete their tasks.

**Acceptance criteria:**

- [ ] Add a tooltip with a link to a help article about product types: https://woocommerce.com/document/managing-products/#product-types

**Comment by octaedro** [comment]
Hi @pmcpinto,
I started working on this issue and wanted to ask you about a few related details.

![Screen Shot 2022-07-04 at 15 21 45](https://user-images.githubusercontent.com/1314156/177203769-6832e0b1-5c83-42cd-8248-827fd2d4419d.png)

- The tooltip that we're using on the `Product data` box hasn't been designed to use links inside it. As a workaround, we can make the icon (`?`) a link.
- Is it ok to put the icon between the `Product type` selector and the `Virtual` checkbox as shown in the image above?
- Also I wanted to ask you about the text inside the tooltip, maybe we can use a text that asks the user to click the icon if they want to get extra information.

**Comment by pmcpinto** [comment]
> Is it ok to put the icon between the Product type selector and the Virtual checkbox as shown in the image above?

Yes.

> The tooltip that we're using on the Product data box hasn't been designed to use links inside it. As a workaround, we can make the icon (?) a link.

> Also I wanted to ask you about the text inside the tooltip, maybe we can use a text that asks the user to click the icon if they want to get extra information.

Something like "Click in the icon to learn more about each product type"?

This is not that intuitive, but I'm not seeing a viable alternative. @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
> This is not that intuitive, but I'm not seeing a viable alternative. @jarekmorawski what do you think?

We'd break a pattern that exists everywhere else. I wonder if we could show a different text based on the form selection? Then the tooltip could provide some details about the currently selected type. 🤔

**Comment by octaedro** [comment]
Thank you @jarekmorawski,

>I wonder if we could show a different text based on the form selection? Then the tooltip could provide some details about the currently selected type. 🤔

Good idea! Do you have the texts that will be shown there?

// CCing @pmcpinto

**Comment by jarekmorawski** [comment]
> Good idea! Do you have the texts that will be shown there?

We'd borrow some from the [documentation](https://woocommerce.com/document/managing-products/#product-types). I'm not sure about custom product types added by plugins because they would have to add their tooltip contents separately.

Maybe the simplest solution would be to show a generic text while hovering over the tooltip?

> Product types define available product details and attributes, such as downloadable files and variations. They're also used for analytics and inventory management.

What do you think? cc @pmcpinto

**Comment by pmcpinto** [comment]
> What do you think? cc @pmcpinto

Sounds good to me.
