### ISSUE TITLE
Product creation experience: improve the "add media" and "add contact form" CTA in the long description

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33538]
**Description:** the "add media" and "add contact form" CTA can be misleading and make the users think that this is the path they need to take to add product images. 

**Acceptance criteria:**

- [x] Improve the CTA copy to make sure users understand that the media or form will be added to the description: "Add media to description" and "Add contact form to the description"
Or
- [ ] Change the layout to make it clear that the CTAs are part of the long description - similar to what we have for the short description

**Comment by louwie17** [comment]
@pmcpinto after talking about this with the team, we thought a layout change might be a better approach as a button containing `"Add contact form to the description"` gets rather long.

One approach was to add a similar card style as the short description around the description field, with the option of also adding a `Product Description`, or `Description` title (similar to how short description is displayed and the rest of the items within this screen).
cc: @jarekmorawski  for potential design suggestions.

One side note: the `Add contact form` only shows up for Jetpack connected sites.

**Comment by pmcpinto** [comment]
> One approach was to add a similar card style as the short description around the description field, with the option of also adding a Product Description, or Description title (similar to how short description is displayed and the rest of the items within this screen).

👍 I think this can be the best approach
