### ISSUE TITLE
Product creation experience: no clear distinction between long and short description

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33537]
**Description:** we don't offer any context about the difference between the long and short description fields. This can lead the user to use one of the fields with the wrong expectations, which can lead to errors and slow down the product creation process.

**Acceptance criteria:**
- [x] Improve the empty state of each field with copy explaining the differences or add a tooltip
- [x] Collapse the short description module by default
- [ ] Change the short description name to "Summary". This change can be risky as it will require updating documentation and screenshots. It should be treated as a nice to have

**Comment by mdperez86** [comment]
Hello @jarekmorawski, talking with @louwie17 and @octaedro about the check number one of the list, we think about two approaches:
1. Adding a placeholder to each editor one for the Short Description and another for the Description of the product.
1.1. After making a research about this, we found that it's not easy to add a placeholder to the editor because tinymce 4.9.11 which is the current version used by woo does not support placeholders (this was solved since version 5.0.0). There are patches like [this one](https://stackoverflow.com/questions/27237876/how-do-i-add-placeholder-text-to-tinymce) that can help us with this. But this is something that should be added to WP global editor and not only in Woo.
2. Adding a tooltip with an explanation to each editor to clarify them in a better way.
2.1. This is a more viable solution to implement (unless someone have another approach). But we want to know where is the right place to put the tooltip.
<img width="888" alt="description-tooltip" src="https://user-images.githubusercontent.com/13334210/189170591-52e2f520-86ed-4eb7-bbf2-a2b497258639.png">
<img width="888" alt="short-description-tooltip" src="https://user-images.githubusercontent.com/13334210/189170194-95768741-f407-4dbd-9787-ee764b5e6ad0.png">
Note: The icon above and the tooltip are just a reference. We are gonna use the current icon and tooltip from the WP lib like below.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/13334210/189177724-f6cf5ade-e903-4917-9e25-2678d0809e85.png">

Also we are thinking to use the texts described for the new experience as the tooltip content.

- Short description: "Summarize this product in 1-2 short sentences. We’ll show it at the top of the page."
- Full description: "Describe this product. What makes it unique? What are its most important features?"

**Comment by jarekmorawski** [comment]
Hi @mdperez86. Thanks for the ping. I think that adding the tooltip icon to each field is the way to go. It's a good idea to use copy from the new experience. I think it'll fit. 👍

**Comment by thuautp** [comment]
Passing a user's feedback here who is affected by this change so we can understand their use case. They decided to downgrade now:

> We use the short description only and a lot
> We now experience a lot more time to edit products 

37483465-hc

**Comment by jarekmorawski** [comment]
@thuautp Thanks for sharing! How did this change affect the user? We've only added an icon in the module's header, which should not impact any workflows. Can you please ask the user to provide more details and create a new issue if there's a bug? Thanks!

**Comment by louwie17** [comment]
@jarekmorawski we also added logic to collapse the short description by default, so the user will have to expand it every time, we could revert this change?

> Collapse the short description module by default

**Comment by pmcpinto** [comment]
> @jarekmorawski we also added logic to collapse the short description by default, so the user will have to expand it every time, we could revert this change?

I think it's our best option. @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
Yes, please!

**Comment by louwie17** [comment]
I can work on this as Porter today, given it's a minimal change and seems important.

**Comment by louwie17** [comment]
@pmcpinto I have a PR in flight to revert this (#35213), did we want to make a code exception for this for the current release that is in-flight, or wait till 7.2?

**Comment by Mercurial78** [comment]
It has to be mandatory also because in my 20 years experience all my clients use the SD and this slow down the process with one additional and not usefull click.

**Comment by loulemos** [comment]
Agree with @Mercurial78

**Comment by pmcpinto** [comment]
> @pmcpinto I have a PR in flight to revert this (https://github.com/woocommerce/woocommerce/pull/35213), did we want to make a code exception for this for the current release that is in-flight, or wait till 7.2?

@louwie17 it's a small change, so I'd try to see if we can include it in 7.2

**Comment by ZigZagWebXYZ** [comment]
Hi there,
Last night I posted the following on woo support in WP.org I was asked to share it here:

**"Having the short description as it is now – CLOSED by default with no way to override it, is adding large number of unnecessary steps to editing each product.

It closes after every small edits updates and when it is open, it is very small by default and allows only 2 lines of text in view which means having to enlarge it as many times too.

Product’s short description is what most shops use the most.
The product long description is often not used at all.
Having the long description at the top by default is not going to change how people use it!

Please bring back the large and open short description. If possible place it at the top or in the very least allow the first time a user is changing it’s behaviour to stick until the user changes it again!"**

When I teach clients to edit their products this is the most confusing thing for them! They expect to see the editing windows in the back end reflect the same order the information appear in the front end product pages. 

I hope this helps inform the discussion.

**Comment by pmcpinto** [comment]
Thanks for the feedback.

@louwie17 can you also change the location of the short description to be displayed before the long description?

**Comment by louwie17** [comment]
> @louwie17 can you also change the location of the short description to be displayed before the long description?

Hmmm maybe, this may be more difficult without changing core Wordpress code. The short description is a meta box, which you can actually drag and drop above the product data meta box for example, or even move it to the side panel if you desired to do this.
The slight problem is that the long description is not a meta box. The long description does have a `action` available to put things before the long description field, but this may also be used by plugins for other use cases.

We could further explore this, but may require some playing around with it, as we want to keep the re-arranging feature as well.

**Comment by perks98** [comment]
Please make the short description at least not collapsed by default. Had a bunch of customers complain that it was missing when it is now collapsed as a thin bar to click on. This is a terrible change for existing users, by collapsing by default you are telling me it shouldn't really get used?

**Comment by ZigZagWebXYZ** [comment]
> @louwie17  The long description does have a action available to put things before the long description field

in my experience there is no way to move anything above the long description

**Comment by pmcpinto** [comment]
> Please make the short description at least not collapsed by default. Had a bunch of customers complain that it was missing when it is now collapsed as a thin bar to click on. This is a terrible change for existing users, by collapsing by default you are telling me it shouldn't really get used?

We'll revert this change in WC 7.2.

**Comment by pmcpinto** [comment]
> Hmmm maybe, this may be more difficult without changing core Wordpress code. The short description is a meta box, which you can actually drag and drop above the product data meta box for example, or even move it to the side panel if you desired to do this.
The slight problem is that the long description is not a meta box. The long description does have a action available to put things before the long description field, but this may also be used by plugins for other use cases.
> We could further explore this, but may require some playing around with it, as we want to keep the re-arranging feature as well.

Thanks for the clarification. So let's place it after the long description.

**Comment by perks98** [comment]
> > Please make the short description at least not collapsed by default. Had a bunch of customers complain that it was missing when it is now collapsed as a thin bar to click on. This is a terrible change for existing users, by collapsing by default you are telling me it shouldn't really get used?
> 
> We'll revert this change in WC 7.2.

@pmcpinto  Thanks for the update and prompt response 👍🙏
I don't know the development cycle of Woocommerce, is WC 7.2 update weeks away? 
<hr>

Update: so it seems it take more than a month to fix something that should already have been resolved and committed to 7.1, especially as it is a revert that doesn't break anything... great development cycle...

**Comment by ApeRunner** [comment]
Yes, please make short description expanded and placed at the very top. That's how dedicated eCommerce software work.  (Shopify, PrestaShop...)

**Comment by pmcpinto** [comment]
I'm closing this issue and I'll open a new one with the missing AC: Change the short description name to "Summary". This change can be risky as it will require updating documentation and screenshots. It should be treated as a nice to have
