### ISSUE TITLE
Product creation experience: no feedback on required fields to set up a store

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33536]
**Description:** currently, it's possible to publish a product with just empty fields. Without context, users can feel overwhelmed by all the options available in the product creation experience, making it difficult to understand which fields are critical to creating a compelling product. Marking some fields as required can potentially introduce unforeseen consequences. We can start by having the title as the required field (most companies in the e-commerce space follow this approach).

**Acceptance criteria:**
- [ ] Product name field has the red asterisk on the label
- [ ]  The publish button is disabled until the user enters the name
- [ ]  On hover, we show a tooltip message: Give this product a name before saving it.
- [ ]  The publish button becomes active if the user enters at least 1 character in the product name

**Comment by pmcpinto** [comment]
cc @jarekmorawski for design feedback

**Comment by AnnaMag** [comment]
@jarekmorawski in case it slipped through your notifications :)

**Comment by jarekmorawski** [comment]
I agree with Pedro. Unfortunately, there's no way for us to determine what's required, except for the product name (I spoke with merchants who post products without a price). Maybe this could be the only required field, and we could add a red asterisk to it and display a validation message when the user clicks the field but doesn't type the name. Additionally, we'd block the Publish button until the user fills the name field.

As for the Recommended label, I'm unsure about it because each product has a different workflow. I'd be afraid that marking some fields but not others could look random and confusing.

**Comment by pmcpinto** [comment]
> As for the Recommended label, I'm unsure about it because each product has a different workflow. I'd be afraid that marking some fields but not others could look random and confusing.

That's a good point. But we still have some fields that should be filled independently of the product, right? For example, price and image 🤔

**Comment by jarekmorawski** [comment]
> That's a good point. But we still have some fields that should be filled independently of the product, right? For example, price and image 🤔

Not necessarily. One of the merchants I spoke with said that sometimes they publish secret products without the price and images. Almost every other platform I tried has the product name as the only required field in the form.

**Comment by pmcpinto** [comment]
Right. So maybe we should close this issue and rely on the guided tour to help users distinguish what's critical from accessory. Do you agree?

**Comment by jarekmorawski** [comment]
Yes. I would, however, make the product name the only required field. Some acceptance criteria I can think of:

- [ ] Product name field has the red asterisk in the label
- [ ] The publish button is disabled until the user enters the name
- [ ] On hover, we show a tooltip message: `Give this product a name before saving it.`
- [ ] The publish button becomes active if the user enters at least 1 character in the product name

**Comment by pmcpinto** [comment]
Sounds good to me. I'll update the AC

**Comment by pmcpinto** [comment]
I'll close this issue, as this isn't a priority.
