### ISSUE TITLE
[EPIC] Product creation/editing experience: incremental improvements

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33534]
We plan to move forward with several usability improvements to the current experience while exploring how to create a new and more streamlined product creation and editing experience. 

We'll compile all the issues and potential solutions under this epic. The prioritization will depend on the effort/risk involved in implementing each change.

**Comment by AnnaMag** [comment]
https://app.zenhub.com/workspaces/mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce/33534

**Comment by AnnaMag** [comment]
The issues are listed in the `no status ` column under "Product creation experience*".
We will prioritize 1 (selected from the 5-6 top ones based on the required effort).

**Comment by pmcpinto** [comment]
@AnnaMag I think we should prioritize #34000. Do you already have a sense of the time/effort required to implement the changes proposed in the issue? It can influence our prioritization.

Thanks

**Comment by pmcpinto** [comment]
Hey Anna, I'm not sure if you saw my previous comment. Thanks :) 

> @AnnaMag I think we should prioritize https://github.com/woocommerce/woocommerce/issues/34000. Do you already have a sense of the time/effort required to implement the changes proposed in the issue? It can influence our prioritization.

**Comment by AnnaMag** [comment]
Apologies for the delay in addressing it. We have evaluated it last week and left a comment [on the main issue](https://github.com/woocommerce/woocommerce/issues/34000#issuecomment-1215032005).

**Comment by pmcpinto** [comment]
@AnnaMag it would be great to have high-level estimates on the remaining issues, to make sure we prioritize them properly. Thanks
