### ISSUE TITLE
Always show pricing group fields, disable if not available for a product type

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33540]
## Description

When the user selects the variable or bundle product type, we currently remove the `Regular price` and `Sale price` fields from the `General` tab (which also causes the entire `General` tab to be removed if no other fields on it are visible.

This can lead to confusion for the user, who might not know where to go to set the price.

We should change this to always show the pricing group fields, and disable them if they are not available for the current product type. If the fields are disabled, a message should be shown at the top of the `General` tab directing the user where to go to set the pricing information. 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/79307566/223413537-2eaa881b-0c7f-49b0-a227-46567277990c.png">

## Designs

`zs56kcy53K7GoGhgyjcQ2R-fi-213%3A37111`

## Acceptance criteria

- [x] The pricing group (`Regular price` input, `Sale price` input, and `Schedule` link fields) should always be visible (therefore, the `General` tab, will also always be visible, since it will have these fields at a minimum).
- [x] Fields in the pricing group will be disabled for `Variable` and `Grouped` products, so the user cannot enter and edit values.
- [x] When fields are disabled, the cursor is set to `not-allowed` to indicate the fields are not interactive. 
- [x] When fields are disabled, they are shown at 50% opacity.
- [x] When fields are disabled, their disabled state is reflected properly according to accessibility guidelines.
- [x] If disabled fields have set values, the set value should be shown.
    - **TODO: confirm this. Perhaps we also need a class or something to specify whether a value should be shown in a disabled field or not.**
- [x] For a `Variable` product, a message is shown at the top of the `General` tab.
    - Message: `You can manage pricing and other details individually for each product variation. Go to Variations`
    - The `Go to Variations` text links to the `Variations` tab.
    - A Tracks event is logged when the `Go to Variations` link is clicked.
- [x] For a `Grouped` product, a message is shown at the top of the `General` tab.
    - Message: `You can manage pricing and other details individually for each product added to this group. Go to Linked Products`
    - The `Go to Linked Products` text links to the `Linked Products` tab.
    - A Tracks event is logged when the `Go to Linked Products` link is clicked.
- [x] For any other product type, when the pricing group fields are disabled, a message is shown at the top of the `General` tab.
    - Message: `You can manage pricing and other details in one of the other tabs.`
- [x] A filter allows extensions to customize the message shown when pricing group fields are disabled.
    - The filter will have two parameters: the product type, and the default message.
- [ ] Let product ambassador know about UX changes 
- [ ] Update dev documentation to reflect this change, if `.hide_if_` and `.show_if_` are documented
   - **TODO: confirm if and how to accomplish this**

## Implementation details

- The showing/hiding of fields is done in [`show_and_hide_panels()`](https://github.com/woocommerce/woocommerce/blob/dc88812e906f2f29448c68b66c4967506c293852/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js#L192)
    - This function is called when the product type select is changed
    - Queries are made based on CSS classes added to fields (and field groups): `.hide_if_`, `.show_if_`
    - Entire tabs ("panels") are hidden if there are no visible fields on them
- We could take a similar approach with `.disable_if_` classes
- We need to make sure that extensions don't get tripped up by these disabled fields
- The showing of the messages at the top of the form should be determined based on the disabled state of the pricing group

**Comment by AnnaMag** [comment]
To be discussed further on a product call.

**Comment by pmcpinto** [comment]
@jarekmorawski how do you think we could solve this?

**Comment by jarekmorawski** [comment]
Regarding this and issue #33562, how do we know it's a problem? Do we know people struggle or find this behavior confusing? Data says that merchants don't change the product type often, so maybe we could instead focus on making it easy to choose the correct product type in the first place?

**Comment by pmcpinto** [comment]
Good questions :) 

>  Data says that merchants don't change the product type often, so maybe we could instead focus on making it easy to choose the correct product type in the first place?
The data we have is about the product type selected when a product is published/updated. We don't know if users play around with different product types before publishing/updating a product.

> how do we know it's a problem? Do we know people struggle or find this behavior confusing? 
One of the main usability heuristics is the visibility of the system status. We're not offering a good experience if the general tab with one of the most important fields (price) disappears when the user changes the type: 
https://user-images.githubusercontent.com/3380168/222398333-70f5e468-e579-41ce-85bd-03738cb7ffc6.mp4

However, we should leave it for now if we don't find an easy way to improve this.

**Comment by jarekmorawski** [comment]
Added designs and updated the ACs.

**Comment by pmcpinto** [comment]
For the engineering team: it would be great to have feedback on the feasibility of each AC item before we move forward with the implementation. 

> Other product types that do not use the system price field should behave similarly. 3PDs who own them should be able to show and customize a message similar to those above.

What should happen if they don't add a message?

**Comment by jarekmorawski** [comment]
> What should happen if they don't add a message?

Good question. I tested the top 5 extensions that add product types, and none required it. However, we could default to a generic message that may not be as helpful as a custom one but could indicate that the price should now be managed elsewhere. Let me know what you think.

> You can manage pricing and other details in one of the other tabs.

**Comment by pmcpinto** [comment]
Sounds good. I'd just change "elsewhere" to something like "in one of the options below"

**Comment by jarekmorawski** [comment]
Good point. I updated the copy to: 

> You can manage pricing and other details in one of the other tabs.
