### ISSUE TITLE
Product creation experience: streamline the attribute creation experience

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33541]
**Description:** the UI for creating attributes is an error-prone and time-consuming experience. We should explore ways to streamline the experience with minimal effort.  

**Acceptance criteria:**

- [ ] Add a tooltip near the "custom product attribute" dropdown and "add" CTA with a link to the support doc: https://woocommerce.com/document/managing-product-taxonomies/#section-6
- [ ] If there are no attributes in the store: show the add attribute form by default
- [ ] If there's at least one attribute: add an empty state screen with a choice between adding a custom attribute or importing an existing one
- [ ] Add "Custom attribute" title to each new attribute until the user adds the attribute name
- [ ] The 2 expand/close options are confusing. Should we just keep one of them?
- [ ] Improve the visibility of the secondary actions: delete, etc. Should they be visible by default?
- [ ] Existing attribute options are always reset when added to a new product. Remember the last used settings for attributes, i.e. "Used for variations" and select all values by default so that the user doesn't have to add them manually

**Comment by AnnaMag** [comment]
It is not technically difficult, but a lot of work for a single issues, so it is difficult to put estimates on it.

Let's select tasks as per bandwidth and circle back to pick the next one time allowing.

**Comment by pmcpinto** [comment]
@AnnaMag do you want me to break it down into smaller and independent issues?

**Comment by AnnaMag** [comment]
It would indeed be helpful to have this issue defined in smaller self-contained chunks.

**Comment by pmcpinto** [comment]
@jarekmorawski what do you think about the following split? Would you reorganize them differently?

Issue 1:
- [ ] Add a tooltip near the "custom product attribute" dropdown and "add" CTA with a link to the support doc: https://woocommerce.com/document/managing-product-taxonomies/#section-6
- [ ] If there are no attributes in the store: show the add attribute form by default
- [ ] If there's at least one attribute: add an empty state screen with a choice between adding a custom attribute or importing an existing one

Issue 2:
- [ ] Add "Custom attribute" title to each new attribute until the user adds the attribute name
- [ ] The 2 expand/close options are confusing. Should we just keep one of them?
- [ ] Improve the visibility of the secondary actions: delete, etc. Should they be visible by default?

Issue 3:
- [ ] Existing attribute options are always reset when added to a new product. Remember the last used settings for attributes, i.e. "Used for variations" and select all values by default so that the user doesn't have to add them manually

**Comment by AnnaMag** [comment]
I opened 3 separate issues with smaller scopes as suggested above. Closing this issue.

**Comment by jarekmorawski** [comment]
Looks good to me. Regarding the expand/close options, I'd go with text buttons. They make the UI clearer and may help solve the problems we're now dealing with in variations (which use the same layout).
