### ISSUE TITLE
Product creation experience: shortcut to add variation price

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33554]
**Description:** Variations won't appear on storefront without a price. We should try to introduce an easy way for users to add the variation price. 

**Acceptance criteria:**

- [ ] when variations don't have a price: add a button to the notice that currently appears there. Button click will launch a browser modal window to add a price, much like an action in the bulk actions dropdown menu.

Design here: 6cBYbZmiet1l7gzc28ce8k-fi-4177%3A154971

**Comment by AnnaMag** [comment]
It could benefit from the design input.

**Comment by pmcpinto** [comment]
> It could benefit from the design input.

@jarekmorawski can you explore how this flow will look like next week?

**Comment by jarekmorawski** [comment]
Here are the designs I put together after we've first identified this issue: `6cBYbZmiet1l7gzc28ce8k-fi-4177%3A154971`
