### ISSUE TITLE
Product creation experience: improve inventory copy

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33557]
**Description:** some of the copy in the Inventory section is confusing and can be easily improved

**Acceptance criteria:**

- [ ] To focus on the final result, rename “Enable stock management at product level” to “Manage stock level (quantity)” 
- [ ] Change “Enable this to only allow one of this item to be bought in a single order” to “Limit purchases to 1 item per order”
- [ ] Add a tooltip to the "Limit purchases to 1 item..." checkbox with the following copy: "Check to let customers to purchase only 1 item in a single order. This is particularly useful for items that have limited quantity, for example art or handmade goods."

**Comment by mattsherman** [comment]
@pmcpinto I wonder if removing the term "stock" will introduce additional confusion. What about something like "Manage stock level (quantity)"? I don't love the parenthesis, but that could help make it more clear. And/or, we could have a tooltip.

**Comment by pmcpinto** [comment]
I think that can work well
