### ISSUE TITLE
Product creation experience: improve stock management discoverability

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33556]
**Description:** the "Manage Stock" option (Inventory section) is only available if the "Enable stock management" global setting is enabled. Users may feel lost when they visit the Inventory section and cannot find an option to manage stock. Even if they know where to find the "Enable stock management", they need to get out of the product creation experience and go to WooCommerce - Settings - Products - Inventory - Enable stock management - Save changes. 

**Acceptance criteria:**

- [ ] Show the "Manage stock?" option by default, even if the "Enable stock management" global setting is disabled 
- [ ] Enabled the "Enable stock management" global setting if the user clicks to Enable stock management at product level
- [ ] Include a tooltip informing the user about what will happen if they enable management at product level

**Comment by mattsherman** [comment]
@pmcpinto The global "Enable stock management" setting is enabled by default. So, this feels like a bit of an edge case. The user would have had to disable stock management globally to get in this situation.

**Comment by pmcpinto** [comment]
You're right

**Comment by AnnaMag** [comment]
> this feels like a bit of an edge case.

Keeping the backlog for the time being.

**Comment by pmcpinto** [comment]
I'll close this, as this is an edge case, and we're focused on the new experience.
