### ISSUE TITLE
Product creation experience: improve Variations actions discoverability/accessibility

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33553]
**Description:** most of the Variations primary and secondary actions have discoverability and accessibility issues. These issues make it difficult for users to easily create and manage variations. 

**Designs:**
`zs56kcy53K7GoGhgyjcQ2R/%5BProject%5D-fi-209%3A30408&t=Wravf3I84jXombqq-4`

**Acceptance criteria:**

- [ ] Key actions are hidden in the dropdown menu: bring out "Generate variations" (previously "Create from all attributes") and "Add manually"(previously "Add variation") into separate buttons and rename the dropdown to "Bulk actions"
- [x] Single variation controls are hidden by default: Show the actions for each variation (Move, Remove, Open) as buttons visible at all times, rather than on hover
- [x] Replace the up/down arrow for expanding/collapsing variation details with text buttons: Edit/Done

**Comment by pmcpinto** [comment]
> Key actions are hidden in the dropdown menu: bring out "Add variation" and "Create from all attributes" into separate buttons and rename the dropdown to "Bulk actions"

@jarekmorawski can you create a mockup for this flow? Feel free to suggest more improvements. Thanks

**Comment by jarekmorawski** [comment]
Updated the AC and added a link to the designs.

**Comment by jarekmorawski** [comment]
I added more details in https://github.com/woocommerce/woocommerce/issues/37100.

**Comment by pmcpinto** [comment]
@octaedro do you think we should merge this issue with #37100 ?

**Comment by octaedro** [comment]
@pmcpinto, looks good to me. The change in the dropdown actions looks quite feasible with a high impact.
I see that Jarek already added the change to [the variations epic](https://github.com/woocommerce/woocommerce/issues/37100). We will start to work on that next week.

**Comment by pmcpinto** [comment]
Ok. So I'll close this issue. Thanks!
