### ISSUE TITLE
Product creation experience: include additional guidance about product image size and format

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33559]
**Description:** the product image or gallery is one of the most impactful elements of the product page. However, we don't offer any guidance on the right image size and formats to ensure that the products have compelling images.

**Acceptance criteria:**

- [ ] Update the upload modal for "Set product image" and "Add gallery images" using the [`post-upload-ui`](https://developer.wordpress.org/reference/hooks/post-upload-ui/) hook to add specific copy (TODO) about suggestion image dimensions and format, along with a link to the WooCommerce blog article about creating great product images (TODO: include link)

**Comment by joelclimbsthings** [comment]
@pmcpinto Do you have copy in mind for this? 

Also, for the link, I see a couple potential posts ([1](https://woocommerce.com/posts/fast-high-quality-product-photos/), [2](https://woocommerce.com/posts/how-to-take-professional-product-photos-top-tips/)). Which one do we have in mind?

**Comment by jarekmorawski** [comment]
I think the [first link](https://woocommerce.com/posts/fast-high-quality-product-photos/) will work best. As for the copy, here's what I had in mind. Do you accept, @pmcpinto?

> For best results, upload JPEG files that are 1000 by 1000 pixels or larger.

([source 1](https://woocommerce.com/posts/fast-high-quality-product-photos/), [source 2](https://www.nexcess.net/blog/woocommerce-image-size/))

**Comment by joelclimbsthings** [comment]
Thanks @jarekmorawski ; do you have an idea of how we want the copy around the link itself? I currently have:

![image](https://user-images.githubusercontent.com/444632/176547353-d78f1736-4bb0-47db-805b-69a4cb833946.png)

Fun fact, the copy around the link itself was decided by GitHub Copilot and I decided not to offend the AI overlords.

**Comment by pmcpinto** [comment]
> As for the copy, here's what I had in mind. Do you accept, @pmcpinto?

Sounds good to me. Thanks

**Comment by jarekmorawski** [comment]
> Fun fact, the copy around the link itself was decided by GitHub Copilot and I decided not to offend the AI overlords.

It's surprisingly good. Didn't know Copilot can do copy. Should I be be scared for my job? 😉

On a more serious note, I've been thinking about something a bit simpler and more actionable:

> How to prepare images?

**Comment by joelclimbsthings** [comment]
> It's surprisingly good. Didn't know Copilot can do copy. Should I be be scared for my job? wink

No more than I! 😟
