### ISSUE TITLE
WooCommerce Setup Dashboard Widget links to empty page for WC Pay task

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#33564]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the WooCommerce Setup Dashboard Widget "Start Selling" button links to the WooCommerce Payments task (e.g. when the WooCommerce Payments task is the only remaining task on the task list) the page it links to (`wp-admin/admin.php?page=wc-admin&task=woocommerce-payments`) is blank.

WC Pay task is not completed
<img width="1096" alt="Screenshot 2022-06-13 at 12 43 22" src="https://user-images.githubusercontent.com/24649833/175066152-87d55eda-42ef-4dd3-84d6-bbbbce103887.png">

Widget shows we have one step remaining
<img width="569" alt="Screenshot 2022-06-13 at 12 43 35" src="https://user-images.githubusercontent.com/24649833/175066175-b4c0752a-b346-4e81-85c4-2b300a11729e.png">

Clicking start selling brings us to empty page. `wp-admin/admin.php?page=wc-admin&task=woocommerce-payments`
<img width="1308" alt="Screenshot 2022-06-13 at 12 43 56" src="https://user-images.githubusercontent.com/24649833/175066202-d0d01c35-4987-43c8-9f8e-6a04498e3ba3.png">

This is happening in 6.6 but I also observed it in 6.5.1 and 6.3.1

### Expected behavior

If we return to the task list and click on the WC Pay task we are redirected to the WooCommerce Payments authorize screen at `https://wordpress.com/jetpack/connect/authorize`
<img width="1096" alt="Screenshot 2022-06-13 at 12 43 22" src="https://user-images.githubusercontent.com/24649833/175066152-87d55eda-42ef-4dd3-84d6-bbbbce103887.png">

If we follow the `Return to` link on this screen we are brought to the `wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect` screen
<img width="518" alt="Screenshot 2022-06-22 at 16 23 18" src="https://user-images.githubusercontent.com/24649833/175129946-826bebe3-75f1-4303-8c95-410178282b08.png">
<img width="1045" alt="Screenshot 2022-06-22 at 16 22 53" src="https://user-images.githubusercontent.com/24649833/175069283-d2170a89-b03e-498e-9446-4738b2f539b2.png">

I expected the WooCommerce Setup Wizard would have linked to one of these screens or just back to the task list itself

### Actual behavior

Link to empty page

### Steps to reproduce

1. Go through the onboarding wizard and set the store country to an eligible WooCommerce Payments country, such as United States. (List of eligible countries here https://woocommerce.com/document/payments/countries/#section-1).
2. Allow WooCommerce Payments to be installed on the "Add recommended business features to my site" step of the wizard
3. Complete the tasks in the task list that are listed above "Get paid with WooCommerce Payments" task OR complete all tasks except for the "Get paid with WooCommerce Payments" task
4. Go to the WordPress dashboard at `wp-admin/index.php`
5. Press the WooCommerce Setup Dashboard Widget "Start Selling" button
6. Note you are now on an empty page titled "Get Paid with WooCommerce Payments"

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://flightless-sugar.jurassic.ninja
Site address (URL): https://flightless-sugar.jurassic.ninja
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 4.84MB
Database Data Size: 3.37MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Companion Plugin: by Osk – 1.26
WooCommerce Payments: by Automattic – 4.3.0
WooCommerce: by Automattic – 6.6.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.4
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://flightless-sugar.jurassic.ninja
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Arizona

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-23 15:10:30 +00:00
Options: ✔
Notes: 40
Onboarding: completed

### WooCommerce Payments ###

Version: 4.3.0
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 6
Oldest: 2022-06-22 15:15:29 +0000
Newest: 2022-06-22 15:16:09 +0000

Pending: 1
Oldest: 2022-06-23 15:10:41 +0000
Newest: 2022-06-23 15:10:41 +0000

### Status report information ###

Generated at: 2022-06-22 15:35:42 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@adrianduffell it would be great to have someone from Ghidorah taking a look at this.

**Comment by adrianduffell** [comment]
Thanks @pmcpinto, we're looking into it.
