### ISSUE TITLE
Store setup: update WCPay copy to include a mention of in-person payments

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33570]
**Description:** in-person payments has just been released in Canada (p6q6po-cQp-p2) We want to update the copy in the payments task to promote the new feature:

> With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies – with no setup costs or monthly fees – and you can now accept in-person payments with the Woo mobile app. [Learn more]

**Acceptance criteria:**
- [ ] Update the WCPayments banner in the Payments task with information about in-person payments. This change should only target stores located in Canada. (This was already implemented in the US).

**Comment by pmcpinto** [comment]
@adrianduffell  is it possible to implement this change in time to be included with 6.8? I'm assuming it's already too late to include it with 6.7. Thanks

**Comment by chihsuan** [comment]
@pmcpinto Yes, we can include it with 6.8.

It also fetches data from a WCCOM remote endpoint when `woocommerce_show_marketplace_suggestions` is true so we can update and deploy it when PR is merged.

**Comment by chihsuan** [comment]
Re-open, we'll also need to update woocommerce.com.
