### ISSUE TITLE
Payment Overview: `See more` link directs users to a wrong place

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33599]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When `Other payment provides` is expanded, users can see the link to explore more options in the Marketplace. 
Currently, the link directs users to the Marketplace inside WC Dashboard, but it should go to the [external marketplace](https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/)

### Expected behavior

The `See more` link should direct users to the [external marketplace](https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/)

### Actual behavior

The link currently takes the user to the wrong marketplace
<img width="1757" alt="Screenshot 2022-06-24 at 18 01 27" src="https://user-images.githubusercontent.com/94967682/175610325-81fbf9e7-6c48-496d-ad81-3022baee8efb.png">
:

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country **BUT** during onboarding opt out from installing WCPay
2. Go to the Payments Overview
3. Click on the `Other payment providers` link
4. Scroll to the bottom

### WordPress Environment

`
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Related to https://github.com/woocommerce/woocommerce/issues/33617#issuecomment-1167427386

**Comment by chihsuan** [comment]
Close this since this can be fixed in #33617
