### ISSUE TITLE
Tracks issue in some key store management actions

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33594]
**Description:** we've identified a significant drop in the number of events fired when users interact with some key store management and setup actions:

`wcadmin_tasklist_task_completed`: significant drop (-80%) after the 6.6 release. It was also trending down after June 1 (maybe related to some a/b test issue).

`wcadmin_inbox_action_click`: significant drop (-80%) after the 6.6 release.

`wcadmin_orders_edit_status_change`: significant drop (-50%) after the 6.6 release.

`wcadmin_orders_view`: significant drop (-50%) after the 6.6 release.

`wcadmin_settings_view`: significant drop (-50%) after the 6.6 release.

`wcadmin_settings_change`: significant drop (-50%) after the 6.6 release.

`wcadmin_product_add_publish`: significant drop (-50%) after 6.4 and another drop (-70%) after 6.6.

`wcadmin_products_view`: significant drop (-50%) after the 6.6 release.

**Comment by pmcpinto** [comment]
@mattsherman is it possible to prioritize this? It should be a top priority and ideally include the fix with WC 6.7. 

Most of our indicators and some of the division's indicators use these events to measure the product performance and we don't have an accurate view of what is going on until it is resolved.

**Comment by mattsherman** [comment]
@pmcpinto Yes, we will investigate this, come up with a fix, and work to get this in WC 6.7.

**Comment by pmcpinto** [comment]
Thanks. Let me know if you need any help debugging this and/or testing a fix.

**Comment by becdetat** [comment]
s
