### ISSUE TITLE
Payments Overview: Outdated design

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33598]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Payments overview is displaying some old version of the hero box.

### Expected behavior

It should be updated inline with the design in [Figma](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12830%3A93773).

<img width="439" alt="Screenshot 2022-06-24 at 17 56 55" src="https://user-images.githubusercontent.com/94967682/175607619-725e2039-c752-4fcb-813e-cd0329b7cc5c.png">

New design was previously implemented as a test as a part of the [KYC Optimization Project](https://wcpay.wordpress.com/2022/02/15/project-thread-kyc-optimization/)

### Actual behavior

Outdated design of the Payments Overview hero box
<img width="404" alt="Screenshot 2022-06-24 at 17 57 33" src="https://user-images.githubusercontent.com/94967682/175607800-ddba44b5-bbd9-4ad0-a3c2-21f52533a17c.png">

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country **BUT** during onboarding opt out from installing WCPay
2. Go to the Payments Overview

### WordPress Environment

`
WordPress address (URL): https://rogermatticwoo.mystagingwebsite.com
Site address (URL): https://rogermatticwoo.mystagingwebsite.com
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔
`

**Comment by chihsuan** [comment]
@adrianduffell These changes look large, but I think we can update it quickly since we've implemented a part of UI in the WCPay setting page.

**Comment by chihsuan** [comment]
@rogermattic ~In the current design, we display a different CTA button based on the WCPay state (installed, isEnabled, needsSetup). Do we need to follow it in the new design?~ (Ignore, I found it actually only displays "Get Started")

For example, when a user has set up the WCPay, the CTA button is `manage`.
![Image](https://user-images.githubusercontent.com/4344253/176589064-7626c680-a813-405a-a0dc-ebe13b0a7105.png)


On the other hand, the banner on the setting page always displays the `Get started` button and links to wcpay-connect.

**Comment by rogermattic** [comment]
@chihsuan I may be wrong but the screenshot that you attached looks like the view that comes after clicking on the Home task list... is that right?
I think what I was referring to was the view that you can get to from the Payments item in the main navigation.

**Comment by chihsuan** [comment]
> I may be wrong but the screenshot that you attached looks like the view that comes after clicking on the Home task list... is that right?

@rogermattic Yes. Sorry, please ignore the previous comment. It's a false alarm.

> I think what I was referring to was the view that you can get to from the Payments item in the main navigation.

Does that mean we only want to update the view from the Payments item in the main navigation, or both?

I think we already have [another issue](https://github.com/orgs/woocommerce/projects/58/views/1) for the view from the Payments item in the main navigation.
