### ISSUE TITLE
Outdated design of the payments page after clicking on `Install` in WCPay settings

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33601]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Outdated design of the payments page after clicking on `Install` WCPayments in the payments settings table

### Expected behavior

We should display a consistent version of the Payments Overview hero, as in this [Figma design](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12830%3A94658)

### Actual behavior

The version of the payments screen is outdated:
![Uploading Screenshot 2022-06-24 at 18.25.18.png…]()

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country **BUT** during onboarding opt out from installing WCPay
2. Go to Payments Settings

### WordPress Environment

`
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
> Outdated design of the payments page after clicking on Install WCPayments in the payments settings table

Did the test show that this design performs better than the existing one?

Btw, after clicking on install the WCPay, the user is redirected to a plugin screen. It's outside of Core. So this change should be handled by Transact :)

**Comment by rogermattic** [comment]
@pmcpinto 
When I was testing the flow I assumed the experiment was already running, so I was expecting to see the banner there, but I just checked and it's still in _staging_. Sorry, my bad.

> Btw, after clicking on install the WCPay, the user is redirected to a plugin screen. It's outside of Core. So this change should be handled by Transact :)

In this ticket I was only after the WCPay hero banner in Settings, which I assume is still part of Core, right?

**Comment by pmcpinto** [comment]
Hey @rogermattic judging by the issue title I assume that you're talking about this screen, which is from the plugin

<img width="1440" alt="Captura de ecrã 2022-07-07, às 10 50 54" src="https://user-images.githubusercontent.com/3380168/177745645-075a9077-8b5d-4e4d-83fd-6a95d7b038e0.png">

Let me know if I misunderstood your request. Thanks

**Comment by chihsuan** [comment]
Hi @rogermattic, as @pmcpinto said, I think the screen is from the plugin. Similar to https://github.com/woocommerce/woocommerce/issues/33623.

I'm going to close this, but feel free to reopen it if you find it's part of Core. Thanks!
