### ISSUE TITLE
`Other payment options` link in Payments Settings is wrong

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33600]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Currently `Discover other` link in Payments Settings directs users to the wrong Marketplace and displays the wrong copy.

### Expected behavior

As in the design here in Figma e428PXC0QyEwYqtX48lLq0-fi-12830%3A96550 the link should:

- [x] be displayed as `Discover other payment providers`
- [ ] next to the link we should display the logos of selected payment providers (as in the design)
- [x] should direct users to the external marketplace 

### Actual behavior

<img width="1471" alt="Screenshot 2022-06-24 at 18 17 47" src="https://user-images.githubusercontent.com/94967682/175611179-57a96e8f-c044-4160-84f0-d140696fd236.png">

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country **BUT** during onboarding opt out from installing WCPay
2. Go to Settings

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
> next to the link we should display the logos of selected payment providers (as in the design)

@rogermattic Do we need to hide the logos when they are installed and activated?

**Comment by chihsuan** [comment]
> 1. be displayed as Discover other payment providers
> 3. should direct users to the external marketplace

Those will be fixed in https://github.com/woocommerce/woocommerce/pull/33716

**Comment by rogermattic** [comment]
Hey @chihsuan !

> Do we need to hide the logos when they are installed and activated?

Thanks for asking! 
When they are installed and activated, which means that they will be displayed in the table above we don't need to display the logos. The logos should only be visible in the initial stage. Thanks :)

**Comment by moon0326** [comment]
Closing it as this [PR](https://github.com/woocommerce/woocommerce/pull/33744) fixed the issue
