### ISSUE TITLE
Add end-to-end tests around product reviews

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#33607]
**Issue Description:**

With the new product reviews feature, we should add end-to-end tests around it.

**Comment by rodelgc** [comment]
For the test steps, see the [Product reviews](https://woocommerce.com/document/product-reviews/) documentation.

Potential tests could be:
1. Approve a review.
2. Edit a review.
3. Mark a review as spam.
4. Reply to a review.
5. Edit a review reply.
6. Delete a review.
7. View all reviews.
8. Filter reviews.
9. Search reviews.

For tests that have a noticeable effect on the customer UI (like "Reply to a review"), assertions should be made on the customer-facing pages to make sure the changes are visible there.

**Comment by veljkho** [comment]
There are existing tests relevant:
- [shopper/product-simple.spec.js](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/shopper/product-simple.spec.js)
- [merchant/product-reviews.spec.js](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/product-reviews.spec.js)

However, according to [the above](https://github.com/woocommerce/woocommerce/issues/33607#issuecomment-1511489316) possible scenarios, it looks like we could extend the existing tests. Let's take a look at what's covered and what is left to cover:

Current coverage:
1. Filter review (merchant)
2. Edit review (merchant)
3. Create review (shopper)
4. Search review (merchant)
5. Update review (merchant)
6. Delete review (merchant)
7. Restore review (merchant)

Possible coverage:
+ Approve review
+ Mark as spam review
+ Reply to review
