### ISSUE TITLE
Wrong link in `Set up payments` screen

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33617]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the current version, when the user clicks on the `See more` link they are sent to the _internal_ marketplace, but the link should direct them to the _external_ marketplace instead.

### Expected behavior

The link should direct the user to https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/

### Actual behavior

<img width="1486" alt="Screenshot 2022-06-27 at 14 14 25" src="https://user-images.githubusercontent.com/94967682/175952196-b19c6975-575f-4c33-b5eb-510d6a4b4378.png">

### Steps to reproduce

1. Onboard to WooCommerce from a country that WCPayments doesn't support
2. Go to WooCommerce Home
3. Click on the `Set up payments` task 

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@rogermattic is there a specific reason why we shouldn't send them to the in-app marketplace?

**Comment by chihsuan** [comment]
<img src="https://user-images.githubusercontent.com/4344253/176583538-8a8e8225-b1ea-4ae9-a58b-3c60121bd1b2.png" width="400px" />

@pmcpinto I found @rogermattic has explained it in https://github.com/woocommerce/woocommerce/issues/33600.

Are we okay to update it to the external marketplace?

**Comment by pmcpinto** [comment]
Yes. Sorry, I missed this ping :)
