### ISSUE TITLE
Implement the `query` method in order table data stores.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#33613]
Similar to CPT data store, we would like to implement `query` method in `OrdersTableDataStore` as well which should be fully compatible with CPT's query method and implement all or similar hooks.

**Comment by peterfabian** [comment]
...to replace this method: https://github.com/woocommerce/woocommerce/blob/6.6.1/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L955

Plus we need to include tests.

**Comment by jorgeatorres** [comment]
Per p1657716951293399-slack-C0E1AV8T0, we're splitting this up in various issues (linked below), and this issue will deal with basic support (i.e. fields already in the COT tables).

- https://github.com/woocommerce/woocommerce/issues/33876
- https://github.com/woocommerce/woocommerce/issues/33877
- https://github.com/woocommerce/woocommerce/issues/33878
- https://github.com/woocommerce/woocommerce/issues/33879
