### ISSUE TITLE
Payments Settings: When WCPay is installed and setup the current version of the page is wrong

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33626]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When WCPay is installed and setup, we shouldn't display the `Recommended ways to get paid` box in the payment settings as it presents competitive alternatives to WCPay when it's already setup. Instead we should direct users to the marketplace where they can see the payment options that will enhance their store. 

### Expected behavior

[As in this Figma design](e428PXC0QyEwYqtX48lLq0-fi-12830%3A96246): 

e428PXC0QyEwYqtX48lLq0-fi-12830%3A96246

When WCPay is installed and setup:

- [ ] We should not display the recommended additional payment providers at the bottom of the Payment Methods page. 
- [ ] The link should say: `Discover additional payment options`
- [ ] Next to the link we should include selected payment options logos
- [x] The link should direct the user to the external Marketplace with BNPL filter https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/wallets/?categoryIds=28681&collections=product&page=1

### Actual behavior

Currently this page includes a box with the recommended payment providers
The link goes to the wrong place
<img width="1683" alt="Screenshot 2022-06-27 at 15 45 42" src="https://user-images.githubusercontent.com/94967682/175970029-c9e68861-82f4-42d1-bd01-c0cedf40a8d5.png">

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country 
2. Install WCPay
3. Set up WCPay
4. Go to Payments Settings

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
Hi @rogermattic ✋ 

Unfortunately, I wasn't able to reproduce it on my end. I've added the payment icons though. I'll make a PR for the payment icons first.

This is what I see when I go to Payment Settings without installing the WC Pay

![Screen Shot 2022-07-05 at 8 17 36 PM](https://user-images.githubusercontent.com/4723145/177460861-cdb6065a-f2ca-4687-a476-50efffc4cac3.jpg)

After installing WC Pay
![Screen Shot 2022-07-05 at 8 18 17 PM](https://user-images.githubusercontent.com/4723145/177460884-e55c8268-6a66-4bbb-869b-094ebe8776c8.jpg)
