### ISSUE TITLE
Payments Settings: wrong link and some copy changes required

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33622]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A few things are not aligned with the design.

### Expected behavior

[As in this Figma design](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12830%3A96868), we should:
1. Display the WCPay hero with the CTA to `Finish set up` (AB test)
2. The CTA for WCPay inside the table should also say `Finish set up`  
3. The link at the bottom of the Payment Methods table should say `Discover other payment providers` and should include selected payment providers' logos. 
4. The `Discover other payment providers` link should direct the user to the external marketplace (https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/) 

### Actual behavior

<img width="1474" alt="Screenshot 2022-06-27 at 15 08 14" src="https://user-images.githubusercontent.com/94967682/175961139-ac704c35-9398-45ec-914a-a7b58abe1967.png">

The current version is missing the WCPay hero (perhaps this is a result of the hero still running as an AB experiment cc: @pmcpinto 
The link is setup to a wrong copy and the WCPay CTA should prompt the user to `finish` the setup. 

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country (opt in to install WCPay during the initial onboarding)
2. Go to Payments Settings

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
> The link at the bottom of the Payment Methods table should say Discover other payment providers and should include selected payment providers' logos.

@rogermattic can you add more details about this? This wasn't in the initial exploration, right?
