### ISSUE TITLE
Updating feature image via API is not working.

### ISSUE THREAD

**Issue by kumarmanishc** [woothemes/woocommerce#33653]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Motivation :** The main reason to raise this issue is because it is working in API v1 but same is not working with v3 of Woocommerce Product [APIs.](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product)

**Objective :** Add an image as feature image by adding position 0.

**Product object :** Sending product object as follows
`{...,
"images": [
    {
      "id": 123,
      "src": "",
      "position":0
    }],
...}`

### Expected behavior

When we add position 0 to an image in array of images it should marks that image as feature image as it is working in woocommerce APIs V1.

### Actual behavior

When we send images data as above to woocommerce v3 APIs it is not working.

### Steps to reproduce

1. Get media image Id and src from media library.
2. Add those image Id and src as above object.
3. Make API call to woocommerce update product v3 API call with above data.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://dev.automatezo.com
Site address (URL): https://dev.automatezo.com
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1n-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: cny_
Total Database Size: 17.95MB
Database Data Size: 12.97MB
Database Index Size: 4.98MB
cny_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cny_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
cny_woocommerce_order_itemmeta: Data: 0.28MB + Index: 0.20MB + Engine InnoDB
cny_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cny_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cny_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cny_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_actionscheduler_actions: Data: 2.41MB + Index: 1.61MB + Engine InnoDB
cny_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_actionscheduler_logs: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
cny_cartbounty: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cny_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
cny_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_lws_wr_achieved_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_lws_wr_historic: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_options: Data: 4.47MB + Index: 0.16MB + Engine InnoDB
cny_postmeta: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
cny_posts: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
cny_sgs_log_events: Data: 1.34MB + Index: 0.00MB + Engine InnoDB
cny_sgs_log_visitors: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
cny_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
cny_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cny_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
cny_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
cny_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cny_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
cny_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cny_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cny_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
cny_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cny_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cny_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_zcwc_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cny_zoho_ordersale_error: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 146
custom_css: 1
custom_order_status: 2
def_reg_fields: 10
lws-wre-event: 4
lws-wre-pool: 1
nav_menu_item: 2
page: 9
post: 4
product: 66
product_variation: 127
purchase_orders: 1
revision: 1
shop_coupon: 7
shop_order: 92
shop_order_refund: 8
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Child Theme Configurator: by Lilaea Media – 2.5.9
Custom Order Statuses for WooCommerce: by Nuggethon – 1.5.1
HTTP Headers: by Dimitar Ivanov – 1.18.5
JSM's Show User Metadata: by JS Morisset – 3.0.4
Login as User: by Web357 – 1.4.4
SiteGround Optimizer: by SiteGround – 7.1.5
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.1
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 7.1.2.5
WooCommerce Exact Online: by Roadmap Studios – 2.1.0
WooCommerce Product Bundles: by SomewhereWarm – 6.12.4
WooCommerce Subscriptions: by WooCommerce – 3.1.4
WooCommerce Zoho Inventory - Pro: by Roadmap Studios – 3.8.5
WooCommerce: by Automattic – 6.6.1
MyRewards: by Long Watch Studio – 4.9.3
Wooventory: by wooventory – 1.0.0
Zoho CRM for WooCommerce: by Roadmap Studios – 1.1.0

### Inactive Plugins (8) ###

Advanced Custom Fields: by Delicious Brains – 5.12.2
B2B for WooCommerce: by Addify – 1.8.2
Custom Order Status for WooCommerce: by Tyche Softwares – 2.1.1
Query Monitor: by John Blackbourn – 3.9.0
SiteGround Security: by SiteGround – 1.2.9
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.2.9
WooCommerce Payments: by Automattic – 4.3.0
Zoho Campaigns: by Zoho Campaigns – 2.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
onbackorder (onbackorder)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child
Version: 3.7.0.1627639276
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://dev.automatezo.com
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Netherlands

### Payment Gateway Support ###

Check payments: products
Cash on delivery: products

### Product Bundles ###

Database Version: 6.12.4
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-30 08:45:59 +02:00
Options: ✔
Notes: 69
Onboarding: completed

### Action Scheduler ###

Complete: 5,278
Oldest: 2022-05-29 19:07:37 +0200
Newest: 2022-06-29 12:18:20 +0200

Failed: 3
Oldest: –
Newest: –

Pending: 1
Oldest: 2022-06-29 15:23:40 +0200
Newest: 2022-06-29 15:23:40 +0200

### Status report information ###

Generated at: 2022-06-29 12:34:40 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Hey, `position` property is not supported in v3. However, we will use the first image (i.e. image with index zero) in the array to be set as the main image).

If you do not want an image to be set as the featured image in a request, then perhaps you can send the image array with specifying indexes (starting from 1) instead of just a linear array.

I am closing the issue for repo maintenance, but feel free to reply if this does not work or has issues, in which case we will reopen. Thanks for the report.

**Comment by mx931** [comment]
Hey, the solution is still not working, if i try to send the ids from the new sequence, then the API resort the ids from small to big

also if i try to post a new picture, its always on the end of the row in woocommerce

**Comment by rrennick** [comment]
This will be addressed by the addition of #38462.
