### ISSUE TITLE
Empty product is created when submitting an EMPTY json

### ISSUE THREAD

**Issue by jurian360** [woothemes/woocommerce#33655]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using the API to create new products I accidentally submited an empty body, not even "{}". This resulted in  the creation of an extra product.
![image](https://user-images.githubusercontent.com/15157670/176457204-d7e530fe-1b14-430d-abae-a49a65b1dfca.png)

### Expected behavior

When submitting no JSON or an empty JSON to the request, I expect an error stating that it is not possible to create such a product, without the required fields. 

### Actual behavior

Using the API to create new products I accidentally submited an empty body, not even "{}". This resulted in  the creation of an extra product.

### Steps to reproduce

1. Go to postman
2. Enter the url for creating a product
3. Leave the BODY empty
4. Submit

![image](https://user-images.githubusercontent.com/15157670/176457820-ecf56325-baf8-4d42-8199-148fd06519bc.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://dev.hem2b.com
Site address (URL): https://dev.hem2b.com
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.30
PHP Post Max Size: 128 MB
PHP Time Limit: 3000
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wpbw_
Total Database Size: 43.42MB
Database Data Size: 30.63MB
Database Index Size: 12.79MB
wpbw_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbw_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbw_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbw_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wpbw_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbw_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wpbw_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_options: Data: 2.42MB + Index: 0.08MB + Engine InnoDB
wpbw_pmxe_exports: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxe_google_cats: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxe_posts: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_hash: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_images: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_imports: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_posts: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wpbw_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpbw_postmeta: Data: 18.55MB + Index: 9.03MB + Engine InnoDB
wpbw_posts: Data: 2.52MB + Index: 0.75MB + Engine InnoDB
wpbw_rcp_customers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_rcp_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_rcp_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbw_rcp_membershipmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_rcp_memberships: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbw_rcp_membership_counts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_rcp_payments: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wpbw_rcp_payment_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_rcp_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbw_rcp_subscription_level_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_restrict_content_pro: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_slides: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_termmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpbw_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbw_term_relationships: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wpbw_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbw_usermeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wpbw_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbw_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpbw_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbw_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpbw_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbw_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wpbw_wc_product_meta_lookup: Data: 0.31MB + Index: 0.47MB + Engine InnoDB
wpbw_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbw_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbw_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 2591
b2bking_custom_field: 10
b2bking_custom_role: 2
b2bking_group: 2
mc4wp-form: 1
nav_menu_item: 46
page: 30
post: 13
product: 2808
revision: 17
shop_order: 197
tbay_brand: 8
tbay_footer: 2
tbay_megamenu: 1
tbay_testimonial: 5
wcb2b_group: 2
wpcf7_contact_form: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Template Library and Redux Framework: by Extendify – 4.3.13
A2 Optimized WP: by A2 Hosting – 2.1.3.10.3
B2BKing Core: by WebWizards – 4.0.0
B2BKing Pro: by WebWizards – 4.1.74
Better Search Replace: by Delicious Brains – 1.4
CMB2: by CMB2 team – 2.10.1
Code Snippets: by Code Snippets Pro – 3.1.1
Contact Form 7: by Takayuki Miyoshi – 5.6
Easy Hide Login: by Arshid – 1.0.7
Jetpack: by Automattic – 10.9
WPBakery Page Builder: by Michael M - WPBakery.com – 6.8.0
Loco Translate: by Tim Whitlock – 2.6.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Repeat Order for Woocommerce: by polyres – 1.2.0
Slider Revolution: by ThemePunch – 6.5.14
Tbay Framework: by Team TbayTheme – 2.2.11
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.19
WooCommerce Pos Payment Gateway: by Jurian Amatsahip – 1.0.0
WooCommerce: by Automattic – 6.4.1 (update to version 6.6.1 is available)
WP All Export Pro: by Soflyy – 1.7.6-beta-1.0
WP All Import Pro: by Soflyy – 4.7.2
Smart Image Resize PRO: by Nabil Lemsieh – 1.7.6.4
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.4
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.6
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.0
YITH WooCommerce Compare: by YITH – 2.15.0
YITH WooCommerce Frequently Bought Together: by YITH – 1.14.0
YITH WooCommerce Quick View: by YITH – 1.16.0

### Inactive Plugins (3) ###

Warp iMagick - Image Compressor: by PageSpeed Club – 1.9.5
WooCommerce B2B: by Code4Life – 3.0.7
YITH WooCommerce Wishlist: by YITH – 3.9.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: SRD (SRD)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #1662 - /terms-of-use/

### Theme ###

Name: GreenMart Child
Version: 1.0
Author URL: https://thembay.com/
Child Theme: ✔
Parent Theme Name: GreenMart
Parent Theme Version: 4.0.6
Parent Theme Author URL: https://thembay.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: greenmart/woocommerce/cart/cart.php
greenmart/woocommerce/cart/cross-sells.php
greenmart/woocommerce/checkout/form-checkout.php
greenmart/woocommerce/content-product-cat.php
greenmart/woocommerce/content-product.php
greenmart/woocommerce/content-single-product.php
greenmart/woocommerce/global/breadcrumb.php
greenmart/woocommerce/global/quantity-input.php
greenmart/woocommerce/loop/add-to-cart.php
greenmart/woocommerce/loop/loop-end.php
greenmart/woocommerce/loop/loop-start.php
greenmart/woocommerce/loop/orderby.php
greenmart/woocommerce/loop/pagination.php
greenmart/woocommerce/loop/rating.php
greenmart-child/woocommerce/myaccount/form-login.php
greenmart/woocommerce/myaccount/my-address.php
greenmart/woocommerce/myaccount/my-orders.php
greenmart/woocommerce/single-product/product-image.php
greenmart/woocommerce/single-product/product-thumbnails.php
greenmart/woocommerce/single-product/rating.php
greenmart/woocommerce/single-product/related.php
greenmart/woocommerce/single-product/review.php
greenmart/woocommerce/single-product/tabs/additional-information.php
greenmart/woocommerce/single-product/tabs/description.php
greenmart/woocommerce/single-product/tabs/tabs.php
greenmart/woocommerce/single-product/up-sells.php
greenmart/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 120
Oldest: 2022-05-30 12:56:38 +0000
Newest: 2022-06-29 14:03:52 +0000

Failed: 1
Oldest: 2022-04-29 23:20:21 +0000
Newest: 2022-04-29 23:20:21 +0000

Pending: 2
Oldest: 2022-06-29 14:10:40 +0000
Newest: 2022-06-29 14:10:51 +0000

### Status report information ###

Generated at: 2022-06-29 14:11:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @jurian360!

Thanks for reaching out and for the detailed report. While it could be argued that empty requests shouldn't create a new product, this isn't something WP necessarily forbids on the backend and it's in line with how some other of our endpoints are working. For instance a POST request to /wc/v3/orders will create an "empty" new order.

Given these requests are all authenticated, we feel the likelihood of something going wrong is minimal. As such, we're closing the issue as "won't fix" but feel free to re-open and provide more details if I have misrepresented something or if this behavior is impacting some workflow.
