### ISSUE TITLE
Marketing task: alternate the sections within recommended extensions

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33657]
**Description:** we want to start alternating the order of the two sections included in the Recommended marketing extensions card: reach to our customers and grow your store.
Our goal is to ensure that all the extensions have the opportunity to be displayed above the fold and assess if this change impacts the individual install rate. 

**Acceptance criteria:**

- [ ] Randomize the order to ensure that each section is displayed first in 50% of the marketing task views. 

**Event tracking:** we can add a prop to identify the sections' order.

**Comment by adrianduffell** [comment]
@pmcpinto Which event would the prop be added to?

**Comment by pmcpinto** [comment]
> @pmcpinto Which event would the prop be added to?

We're using wcadmin_task_view to track the marketing task view. So we can add a prop to this event or create a new one just for this purpose. Let me know what you think. Thanks
