### ISSUE TITLE
i18n broken in a few places

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#33666]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

![image](https://user-images.githubusercontent.com/27843274/176584126-971869ed-c64a-4fe0-8045-374dff83ed8c.png)

![image](https://user-images.githubusercontent.com/27843274/176584445-d1b32b7c-8858-46d9-a271-8b3a923b73d8.png)

![image](https://user-images.githubusercontent.com/27843274/176584979-0084f698-fc2b-4451-9541-0f356b9a646c.png)

**Comment by rjchow** [comment]
Some discussion here as well: p1656559454371029/1656559041.206229-slack-C01SFMVEYAK

**Comment by chihsuan** [comment]
Only "future" and "past" strings are translated.

![Screen Shot 2022-06-30 at 16 02 03](https://user-images.githubusercontent.com/4344253/176625342-4d7a6790-2cc5-405a-9997-f4aecc70a9ba.png)

It has been fixed in https://github.com/WordPress/gutenberg/pull/16728/files#diff-03d0cf6d312040748a895b1aee2b5fb759e5936800e7e90ec1966e60000c3e35L65-L79. I think we just need to contact wp.org to ship it.

**Comment by fernandotellado** [comment]
Same issue with es_ES translations.

**Comment by rjchow** [comment]
Hey @fernandotellado 👋 

That is correct, it is broken for all translations as it’s due to a code issue. We’ve had a bit of i18n trouble recently due to the merge of WooCommerce Admin into WooCommerce Core, and it looks like we still missed some parts.

Much appreciate your comprehensive report  bringing this to our attention, and we’ll do our best to resolve it!

**Comment by fernandotellado** [comment]
Ok @rjchow I have a lot of screen captures if you need more places where the issue occurs

**Comment by rjchow** [comment]
There were 3 other screenshots in the report I received from my colleague, but I noticed that they have already been fixed in WooCommerce 6.6.1, what version were you testing on?

**Comment by fernandotellado** [comment]
6.6.1 too

**Comment by chihsuan** [comment]
@fernandotellado Thanks, we'll investigate it more.

**Comment by chihsuan** [comment]
> 6.6.1 too

Hey @fernandotellado, Thanks again for your report. I've tried it on a fresh site with 6.6.1 and es_ES. 

Here’s what I found:

![payment](https://user-images.githubusercontent.com/27843274/176584126-971869ed-c64a-4fe0-8045-374dff83ed8c.png)

I did find a translation bug in the payment setting page. I've created [a PR](https://github.com/woocommerce/woocommerce/pull/33718) for it. Thanks for catching it!

--- 

![https://user-images.githubusercontent.com/27843274/176584979-0084f698-fc2b-4451-9541-0f356b9a646c.png](https://user-images.githubusercontent.com/27843274/176584979-0084f698-fc2b-4451-9541-0f356b9a646c.png)

We'll need more time to fix this one. Sorry about that, this is a known issue related to https://github.com/woocommerce/woocommerce/issues/32242.

----

![Screen Shot 2022-07-05 at 10 57 17](https://user-images.githubusercontent.com/4344253/177242803-40a86c09-c2fb-4225-9b62-712e08ba4c03.png)
*Home Screen*

![Screen Shot 2022-07-05 at 10 57 54](https://user-images.githubusercontent.com/4344253/177242818-a669de1d-f4a9-4dc0-884c-4eb67f51963f.png)
*Orders*

![Screen Shot 2022-07-05 at 10 59 38](https://user-images.githubusercontent.com/4344253/177242839-65a75f1b-69a9-4761-b732-82ad3dd01580.png)
*Customers*

![Screen Shot 2022-07-05 at 11 03 32](https://user-images.githubusercontent.com/4344253/177242853-4c8146ba-d357-406c-a5d4-30782043041e.png)
*Analytics*

Unfortunately, as you can see in the above screenshots ☝️, I was not able to reproduce them and they are translated properly. Would you be able to try it on a fresh site, or follow [this](https://woocommerce.com/document/woocommerce-localization/#section-1) to confirm if your site has the latest language files?

---

![time](https://user-images.githubusercontent.com/27843274/176584445-d1b32b7c-8858-46d9-a271-8b3a923b73d8.png)

For all time translation issues like the above, I've reached out to wp.org folks. Ideally, the fix will be released in WordPress 6.1. [#47373](https://core.trac.wordpress.org/ticket/47373).

**Comment by rjchow** [comment]
I think the issues have been addressed so I'm closing this issue.
Feel free to reopen if I missed something!
