### ISSUE TITLE
PNPM Update: `@woocommerce/e2e-environment`'s App Root Fetching Broken

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33684]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating PNPM I started receiving errors from the `@woocommerce/e2e-environment` package in the `getAppRoot()` function. The `require.resolves()` call is returning errors because in v7 because the package is unable to resolve itself. The solution is probably to always expect the package to be in `node_modules` and change the way that the tests are executed so that it runs from the `plugins/woocommerce` context using the `@woocommerce/e2e-environment` dependency that it has.

There also seems to be a `getCoreTestsRoot()` in the monorepo that does the same kind of lookup.

### Expected behavior

There should be no errors from `getAppRoot()`.

### Actual behavior

There are errors.

### Steps to reproduce

1. Update to PNPM v7 and `pnpm install`. You will need to temporarily allow V7 in the `package.json` constraint.
2. Run `pnpm -- turbo run build --filter="@woocommerce/e2e-environment"`

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tomalec** [comment]
> The solution is probably to always expect the package to be in `node_modules`

WDYT, of providing a param to provide the custom path manually? If https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-environment/utils/app-root.js is about to provide the app root, and all it does is just blindly assume it is `node_modules`, which may not be accurate. Maybe it would be safe just to get it set apriori explicitly?

The person setting up e2e env knows where they located their app, see we would be less bug prone here.
