### ISSUE TITLE
PNPM Update: Address PNPM v6 Public Hoisting Differences

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33685]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Once we upgrade to PNPM v7 we are going to be subject to some of the new hoisting preferences. [The `public-hoist-pattern`](https://pnpm.io/6.x/npmrc#public-hoist-pattern) has changed between v6 and v7. While it's possible we could just change it back, there are a couple of consequences with TypeScript types and conflicts within our repository. Given PNPM's strictness goals, we should go ahead and just fix the packages that have broken dependencies.

We should change the `public-hoist-pattern` to what PNPM v7 has the default set to. This will mean `@types` packages and both ESLint and Prettier plugins will potentially break. The process will ultimately be checking `package.json` files when there are errors and making sure that they declare all of the dependencies that are required. We could also set the `typeRoots` in `tsconfig.json` files to only search `"./node_modules/@types", "./typings"`. This would break any builds where types aren't being included.

### Expected behavior

There are no errors with the `public-hoist-pattern` changed.

### Actual behavior

There are errors.

### Steps to reproduce

1. Upgrade to PNPM v7. You will have to edit the root `package.json` to allow for `pnpm install` to work.
2. Run `pnpm -- turbo run build --filter=woocommerce`. There will be many errors in different packages.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rjchow** [comment]
I've added the necessary @types packages in order for the build process to complete without missing type definition errors (or any errors)

However it looks like there is a new issue with tests, and I don't see a direct causation between adding type definitions and `useSelect` returning undefined - so I've filed it as a [separate issue](https://github.com/woocommerce/woocommerce/issues/34203) and added it to the PNPM 7 epic.
