### ISSUE TITLE
Add unit tests for "purchase" task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33691]
**Issue Description:**

Add unit tests for the onboarding "purchase" task in React admin

Acceptance criteria

Add tests for 
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/tasks/fills/purchase.js

**Comment by ilyasfoo** [comment]
Due to deprecation of purchase task (https://github.com/woocommerce/woocommerce/issues/39955), this is no longer relevant.
