### ISSUE TITLE
add selection button in wordpress in image in product selection and much more missing

### ISSUE THREAD

**Issue by mhd311** [woothemes/woocommerce#33712]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

hi i come from shopify store i have a lott of bug in wordpress i will give you small issue 

see the picture i want delete the shipping from all country exept china and united state i delete it manualy one by one no button for selection why hhh? 

the media file i take three days to to discover where the selection button because i want delete some image 

### Expected behavior

.

### Actual behavior

.

### Steps to reproduce

![wordpress selsction](https://user-images.githubusercontent.com/101460717/176986939-dc8ce3b1-7022-4b8b-8edc-b4ec3158cecd.jpg)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kotomoto.co
Site address (URL): https://kotomoto.co
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 516 MB
PHP Time Limit: 100
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wpdl_
Total Database Size: 380.60MB
Database Data Size: 274.71MB
Database Index Size: 105.89MB
wpdl_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_actionscheduler_actions: Data: 2.02MB + Index: 10.14MB + Engine InnoDB
wpdl_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_actionscheduler_logs: Data: 2.02MB + Index: 3.03MB + Engine InnoDB
wpdl_adsw_activities: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpdl_adsw_ali_meta: Data: 8.17MB + Index: 0.06MB + Engine InnoDB
wpdl_adsw_comments_hash: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wpdl_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_adsw_task_upload_images: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_adsw_variations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_abandoned_emails: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_abandoned_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_abandoned_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_activities: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_ali_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_apply: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_comments_hash: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpdl_ads_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_orders_item: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_products_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_search_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_shipping: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_shipping_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_ads_task_upload_images: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ads_variations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_ads_variations_map: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_commentmeta: Data: 1.16MB + Index: 0.16MB + Engine InnoDB
wpdl_comments: Data: 1.19MB + Index: 0.09MB + Engine InnoDB
wpdl_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wpdl_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpdl_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_frmt_form_entry: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_frmt_form_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_frmt_form_views: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_fw_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpdl_fw_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpdl_fw_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpdl_gla_budget_recommendations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpdl_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpdl_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wpdl_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_mclean_refs: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpdl_mclean_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_options: Data: 16.19MB + Index: 2.19MB + Engine InnoDB
wpdl_payment_discount: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_payment_transaction: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_postmeta: Data: 68.14MB + Index: 42.19MB + Engine InnoDB
wpdl_posts: Data: 67.05MB + Index: 7.64MB + Engine InnoDB
wpdl_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wpdl_prli_links: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wpdl_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_realmedialibrary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_realmedialibrary_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_realmedialibrary_tmp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_sship_shipping: Data: 46.17MB + Index: 0.05MB + Engine InnoDB
wpdl_sship_shippings_order: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_sship_shipping_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_terms: Data: 0.22MB + Index: 0.30MB + Engine InnoDB
wpdl_term_relationships: Data: 1.42MB + Index: 0.30MB + Engine InnoDB
wpdl_term_taxonomy: Data: 0.31MB + Index: 0.39MB + Engine InnoDB
wpdl_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_trp_dictionary_ar_en_us: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_trp_dictionary_en_us_ar: Data: 4.52MB + Index: 6.48MB + Engine InnoDB
wpdl_trp_gettext_ar: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wpdl_trp_gettext_en_us: Data: 1.52MB + Index: 1.94MB + Engine InnoDB
wpdl_trp_original_meta: Data: 0.41MB + Index: 0.55MB + Engine InnoDB
wpdl_trp_original_strings: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wpdl_ulike: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_ulike_activities: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_ulike_comments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_ulike_forums: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_ulike_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_usermeta: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
wpdl_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_vi_wad_ali_orders_info: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_vi_wad_error_product_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_vi_wbe_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wacv_abandoned_cart_record: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wacv_cart_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wacv_email_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wacv_guest_info_record: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpdl_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpdl_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpdl_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_wc_product_attributes_lookup: Data: 1.50MB + Index: 0.45MB + Engine InnoDB
wpdl_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_wc_product_meta_lookup: Data: 3.52MB + Index: 5.39MB + Engine InnoDB
wpdl_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_wishsuite_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_woocommerce_saving_cards: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wotv_woo_track_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpdl_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_yoast_indexable: Data: 28.13MB + Index: 10.91MB + Engine InnoDB
wpdl_yoast_indexable_hierarchy: Data: 1.45MB + Index: 0.89MB + Engine InnoDB
wpdl_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpdl_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpdl_yoast_prominent_words: Data: 0.20MB + Index: 0.50MB + Engine InnoDB
wpdl_yoast_seo_links: Data: 3.38MB + Index: 2.72MB + Engine InnoDB

### Post Type Counts ###

astra_adv_header: 1
attachment: 15109
custom_css: 5
elementor-hf: 1
elementor_library: 46
language_switcher: 4
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 80
oceanwp_library: 1
oembed_cache: 2
page: 51
pauple_element: 1
post: 3
product: 544
product_variation: 18647
revision: 808
shop_coupon: 3
shop_order: 3
um_directory: 1
um_form: 3
woolentor-template: 1
wpcf7_contact_form: 1
wpforms: 4
wp_global_styles: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Ads Abandoned Cart AliDropship Plugin: by Yaroslav Nevskiy & Pavel Shishkin – 2.0.28
Shipping Product Aliexpress: by Pavel Shishkin – 1.3.73
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin & Denis Zharov – 1.6.46
Contact Form 7: by Takayuki Miyoshi – 5.6
Elementor Beta (Developer Edition): by Elementor.com – 1.1.1
Elementor Pro: by Elementor.com – 3.7.2
Elementor: by Elementor.com – 3.7.0-dev10
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.3.0

WooCommerce PayPal Payments: by WooCommerce – 1.8.1
WooCommerce: by Automattic – 6.6.1
WooLentor Pro: by HasThemes – 1.9.8
WooLentor - WooCommerce Elementor Addons + Builder: by HasThemes – 2.3.2

### Inactive Plugins (5) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.12

WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.6

YITH WooCommerce Wishlist: by YITH – 3.10.0
Yoast SEO: by Team Yoast – 19.2
Yoast SEO Premium: by Team Yoast – 18.5

### Must Use Plugins (1) ###

Endurance Page Cache: by Mike Hansen – 2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #27583 - /categories/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #12482 - /account/
Terms and conditions: #12478 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 4.1.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: SD
WooCommerce currency supported: ✔
PayPal card processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-02 11:39:17 +00:00
Options: ✔
Notes: 35
Onboarding: completed

### Action Scheduler ###

Canceled: 7
Oldest: 2022-06-11 15:05:55 +0000
Newest: 2022-06-18 10:33:19 +0000

Complete: 2,880
Oldest: 2022-06-01 09:32:00 +0000
Newest: 2022-07-02 04:46:18 +0000

Failed: 9
Oldest: 2022-05-19 09:49:12 +0000
Newest: 2022-06-30 06:43:56 +0000

Pending: 2
Oldest: 2022-07-02 10:35:04 +0000
Newest: 2022-07-03 03:31:42 +0000

### Status report information ###

Generated at: 2022-07-02 04:50:34 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi, could you isolate to one issue you've found and give step by step instructions on reproducing?

**Comment by jonathansadowski** [comment]
I'm not sure why the bot didn't follow up and do this, but since there hasn't been activity in 7 days, so I'm closing this as stale.
