### ISSUE TITLE
Latest version has corrupted billing email field

### ISSUE THREAD

**Issue by jessebrightman** [woothemes/woocommerce#33738]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Latest version has corrupted billing email field

### Expected behavior

Billing email should show the customers email

### Actual behavior

A random email has been generated has the domain name then @protonmail

### Steps to reproduce

order something then go to checkout

### WordPress Environment

regular setup

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Could you give more detailed steps for reproduction please?

**Comment by jonathansadowski** [comment]
@jessebrightman thanks for the report. As we haven't received a response, I'm going to close this issue due to inactivity. If you're still think that there's a bug, please feel free to open a new issue.
