### ISSUE TITLE
Product description editor

### ISSUE THREAD

**Issue by sanskritkm** [woothemes/woocommerce#33753]
### Describe the solution you'd like

Hi,

In WC product long and short description editor classic it does not have much ability to edit product style, I know WP migrate to Gutenberg  but it cant use in WC product editor, should safe to use Advanced Editor Tools (previously TinyMCE Advanced)?

Thank,

**Comment by rrennick** [comment]
@williamgh2019 Thanks for creating the issue. A block enbled product editor is currently under development across multiple issues so I'll close this as a duplicate.
