### ISSUE TITLE
Shipping smart defaults not handling edge cases 

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#33751]
### Describe the bug

It seems there are some gaps in the logic we used to manage default shipping zones and shipping task.

An example case would be a user from US who already has Jetpack installed but doesn't have WCS, they would not be able to see the shipping task, nor have the default shipping zones created. 

- The check for shipping task to appear [doesn't include US](https://github.com/woocommerce/woocommerce/blob/b274831334fe8979ad7eaa4db579b030a7451019/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Shipping.php#L113)
- The [check for creating]( https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Homescreen.php#L118:L122) shipping zones does not cover users who has Jetpack installed but not installed WCS

### Expected behavior

Ideally, I think we should have the logic consolidated where there will never be a case for users to neither have the shipping task visible nor shipping zones created. However, if this is too complicated, we should just fix the case mentioned above.

### Actual behavior

Edge case happens for some users

### Steps to reproduce

 1. Create a fresh site in the US, select physical products, install Jetpack in extension step
2. Observe no shipping task nor review shipping options in setup tasklist
3. Observe no shipping zones set

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
I think the simplest fix is adding the US to the [checklist](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Shipping.php#L113) 

cc @verofasulo

**Comment by ilyasfoo** [comment]
@moon0326 I'm thinking having shipping zone set seems like better than having shipping task for US users 🤔 

But yeah I think Veronica should be able to confirm it

**Comment by moon0326** [comment]
> @moon0326 I'm thinking having shipping zone set seems like better than having shipping task for US users 🤔
> 
> But yeah I think Veronica should be able to confirm it

Yup! That's works too 👍

**Comment by ilyasfoo** [comment]
Re-ping @verofasulo 👋

**Comment by verofasulo** [comment]
Hey @ilyasfoo @moon0326 😄

If the store sells physical products, has JP installed but not WCS,  and is located in the US:

- [ ] Automatically turn on automated shipping options.
- [ ] Move the "Review shipping options task" to the "Things to do next" section.
- [ ] Address users to WooCommerce > Settings > Shipping once clicked on the task on the home page.
- [ ] Display intro tooltips in Shipping Settings: Shipping zones, shipping methods, WCS tab.

![US_Canada_Australia - Plugin not installed (1)](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif)

What do you think?

**Comment by moon0326** [comment]
> Hey @ilyasfoo @moon0326 😄
> 
> If the store sells physical products, has JP installed but not WCS, and is located in the US:
> 
> * [ ]  Automatically turn on automated shipping options.
> * [ ]  Move the "Review shipping options task" to the "Things to do next" section.
> * [ ]  Address users to WooCommerce > Settings > Shipping once clicked on the task on the home page.
> * [ ]  Display intro tooltips in Shipping Settings: Shipping zones, shipping methods, WCS tab.
> 
> ![US_Canada_Australia - Plugin not installed (1)](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) [ ](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) ![US_Canada_Australia - Plugin not installed (1)](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) [ ](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif)
> 
> What do you think?

I think that's most reasonable approach 👍

**Comment by moon0326** [comment]
> Hey @ilyasfoo @moon0326 😄
> 
> If the store sells physical products, has JP installed but not WCS, and is located in the US:
> 
> * [ ]  Automatically turn on automated shipping options.
> * [ ]  Move the "Review shipping options task" to the "Things to do next" section.
> * [ ]  Address users to WooCommerce > Settings > Shipping once clicked on the task on the home page.
> * [ ]  Display intro tooltips in Shipping Settings: Shipping zones, shipping methods, WCS tab.
> 
> ![US_Canada_Australia - Plugin not installed (1)](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) [ ![US_Canada_Australia - Plugin not installed (1)](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) ](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif) [ ](https://user-images.githubusercontent.com/98944206/159506263-a846740e-b536-4c7f-896f-398d4c2aa238.gif)
> 
> What do you think?

Hey @verofasulo  ✋ 

After working on this issue, I realized that we are enabling shipping smart defaults when the store sells physical products and the country is the US with all the requirements combined. Is this okay?

The original [issue](https://github.com/woocommerce/woocommerce/issues/33366) states we should enable shipping smart defaults when the store is in the US and 

1. Sells physical products, have JP and WCS installed, and JP is connected.
2. Sells physical products, but JP and WCS are not installed

These two requirements mean that we're enabling shipping smart defaults regardless of JP and WCS

and this issue states
3. Sells physical products, has JP installed

**Comment by verofasulo** [comment]
Hey @moon0326 , good question.

The reason why I created two different points is that the flow is different. 

1. Sells physical products, have JP and WCS installed, and JP is connected.: we don't display the banner to install WCS, but we use the spotlight to highlight the WCS tab.
2. Sells physical products, but JP and WCS are not installed: In this case, the last step is to highlight the WCS banner.

Hope it's more clear now :)

**Comment by moon0326** [comment]
> Hey @moon0326 , good question.
> 
> The reason why I created two different points is that the flow is different.
> 
> 1. Sells physical products, have JP and WCS installed, and JP is connected.: we don't display the banner to install WCS, but we use the spotlight to highlight the WCS tab.
> 2. Sells physical products, but JP and WCS are not installed: In this case, the last step is to highlight the WCS banner.
> 
> Hope it's more clear now :)

Thank you for the clarification 👍 

If that's the case, we're good to go 😄
