### ISSUE TITLE
[Enhancement]: Product Qty in a Variable Product should be equal to sum of stock qty of all variations. 

### ISSUE THREAD

**Issue by jwad93** [woothemes/woocommerce#33764]
### Describe the solution you'd like

Product Qty in a Variable Product should be equal to sum of stock qty of all variations.

**Comment by psealock** [comment]
Can you please use the issue template, complete with steps to reproduce?

**Comment by jonathansadowski** [comment]
@jwad93  thanks for the report. As we haven't received a response, I'm going to close this issue due to inactivity. If you're still think that there's a bug, please feel free to open a new issue.
