### ISSUE TITLE
Sale price is not updating using the REST API V2 

### ISSUE THREAD

**Issue by bhagatakshay662** [woothemes/woocommerce#33785]
I am trying the update the **Sale Price** of the Product using the REST API into the Laravel. But it is not reflecting at Woo Commerce side. I am using V2 API version. 
Is their anything missing from me. Please guide.

**Comment by psealock** [comment]
Hi @bhagatakshay662 would you be able to use the issue template complete with reproduction steps?

**Comment by bhagatakshay662** [comment]
@psealock I got the root cause this that, for set **sale price** at woo commerce it should be different than the **regular price**. If we putting same value to both then Sale price will not set.
