### ISSUE TITLE
Add caching for loading shipping zones in shipping task

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#33782]
@vedanshujain [Identified](https://github.com/woocommerce/woocommerce/issues/33073#issuecomment-1178819595) that the Shipping task queries DB for shipping zones in every request in [this PR](https://github.com/woocommerce/woocommerce/pull/33422). Ideally, we'd want to get this in before 6.8 code freeze, but I think we can have a little leniency to get it cherry-picked before the final release since it's a bug fix.

We could explore caching strategies such as using storing the value option as mentioned by vedanshujain or transients. We should also make sure the caching is refreshed when a shipping zone is added/removed.

**Comment by thelogicwizards** [comment]
Affected user: [5341199-zen](https://woothemes.zendesk.com/agent/tickets/5341199)

I suggested a workaround: rolling back to [release 6.5.1](https://github.com/woocommerce/woocommerce/releases/tag/6.5.1) to avoid this until we find a patch.
