### ISSUE TITLE
Warenkorb und Kasse funktionieren nicht und ich kann keine Vorschau der Versandkosten anzeigen

### ISSUE THREAD

**Issue by Sabs40** [woothemes/woocommerce#33792]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Meine Warenkorbseite und die Kasse funktionieren nicht und ich kann keine Versandkosten direkt bei den Produkten anzeigen, da steht immer nur die komplette URL

### Expected behavior

Ich möchte Hilfe auf Deutsch, dass mein Shop endlich funktioniert. Ich habe keine Ahnung von dem ganzen und verstehe die Fachbegriffe auf Deutsch schon nicht wirklich, da nutzen mir keine Hilfeseiten auf Englisch.

### Actual behavior

Wenn ich Artikel in den Warenkorb lege und dann den Warenkorb anzeigen will bekomme ich eine leere Seite, genauso bei der Kasse
bei den Artikelpreisen sollte eigentlich stehen zzgl. 6,99€ Versandkosten aber es steht dort nur: zzgl. (www.sabswolllaedchen/versandarten) Versandkosten

### Steps to reproduce

Shop Artikel ( keine Versandkosten angezeigt) Warenkorb wird nicht angezeigt wenn ich darauf klicke, Kasse ebenso nicht

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.sabswolllaedchen.com
Site address (URL): https://www.sabswolllaedchen.com
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 102 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.20
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-1:10.3.34+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: www_
Datenbank-Gesamtgröße: 70.60MB
Datenbank-Datengröße: 60.81MB
Datenbank-Indexgröße: 9.79MB
www_woocommerce_sessions: Daten: 0.03MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
stg_b42c9_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
stg_b42c9_gla_budget_recommendations: Daten: 0.22MB + Index: 0.14MB + Engine InnoDB
stg_b42c9_gla_merchant_issues: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_gla_shipping_rates: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_gla_shipping_times: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_imagify_files: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
stg_b42c9_imagify_folders: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_newsletter_templates: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_subscribers: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
stg_b42c9_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_options: Daten: 5.45MB + Index: 0.13MB + Engine InnoDB
stg_b42c9_postmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_posts: Daten: 0.13MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
stg_b42c9_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_b42c9_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_b42c9_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_b42c9_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_b42c9_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_actionscheduler_actions: Daten: 0.50MB + Index: 0.47MB + Engine InnoDB
www_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_actionscheduler_logs: Daten: 0.30MB + Index: 0.23MB + Engine InnoDB
www_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
www_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_gla_budget_recommendations: Daten: 0.22MB + Index: 0.14MB + Engine InnoDB
www_gla_merchant_issues: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_gla_shipping_rates: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_gla_shipping_times: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_imagify_files: Daten: 0.33MB + Index: 0.48MB + Engine InnoDB
www_imagify_folders: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_newsletter_templates: Daten: 3.28MB + Index: 0.00MB + Engine InnoDB
www_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
www_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_subscribers: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
www_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_options: Daten: 9.02MB + Index: 0.17MB + Engine InnoDB
www_postmeta: Daten: 22.23MB + Index: 1.84MB + Engine InnoDB
www_posts: Daten: 12.05MB + Index: 0.33MB + Engine InnoDB
www_rcb_asset_seo_redirect: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_blocker_thumbnails: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_rcb_consent: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_rcb_presets: Daten: 0.16MB + Index: 0.02MB + Engine InnoDB
www_rcb_revision: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_rcb_revision_independent: Daten: 0.03MB + Index: 0.02MB + Engine InnoDB
www_rcb_scan: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_rcb_scan_markup: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
www_rcb_stats: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_rcb_tcf_features: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_tcf_purposes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_tcf_special_features: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_tcf_special_purposes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_tcf_stacks: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_rcb_tcf_vendors: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_real_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
www_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
www_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_yoast_indexable: Daten: 0.19MB + Index: 0.13MB + Engine InnoDB
www_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_yoast_seo_links: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 410
custom_css: 1
elementor_library: 15
envato_tk_import: 1
mailpoet_page: 1
nav_menu_item: 15
option-tree: 1
page: 17
post: 1
product: 10
product_variation: 42
rcb-blocker: 1
rcb-cookie: 3
revision: 1196
wp_global_styles: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Elementor: von Elementor.com – 3.6.7
Envato Elements: von Envato – 2.0.11
Imagify: von WP Media – 1.10
Jetpack: von Automattic – 11.1
Ocean Extra: von OceanWP – 2.0.2
one.com Spam Protection: von one.com – 1.0.3
one.com: von one.com – 4.0.0
one.com Maintenance Mode: von one.com – 2.0.3
Performance Cache: von one.com – 3.0.0
Pinterest for WooCommerce: von WooCommerce – 1.2.1
Real Cookie Banner (Free): von devowl.io – 3.0.1
Responsive Ready Sites Importer: von CyberChimps – 2.6.3
WooCommerce Stripe-Gateway: von WooCommerce – 6.4.3
Germanized für WooCommerce: von vendidero – 3.9.8
WooCommerce-Zahlungen: von Automattic – 4.4.0
WooCommerce PayPal Payments: von WooCommerce – 1.9.0
WooCommerce: von Automattic – 6.6.1
Yoast SEO: von Team Yoast – 19.2

### Must Use Plugins (1) ###

Elementor Safe Mode: von Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop-Basis: #404 - /shop/
Warenkorb: ❌ Die Seite enthält nicht den [woocommerce_cart]-Shortcode oder woocommerce/cart-Block.
Kasse: #32 - /kasse/
Mein Konto: ❌ Die Seite enthält nicht den Shortcode [woocommerce_my_account].
Allgemeine Geschäftsbedingungen: #187 - /agb-2/

### Theme ###

Name: OceanWP
Version: 3.3.3
Author URL: https://oceanwp.org/about-oceanwp/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-09 19:31:46 +02:00
Options: ✔
Notes: 63
Onboarding: completed

### WooCommerce Payments ###

Version: 4.4.0
Connected to WPCOM: Nein
Blog ID: -
Account ID: -

### Action Scheduler ###

Abgeschlossen: 1.146
Oldest: 2022-06-08 09:36:48 +0200
Newest: 2022-07-09 00:40:24 +0200

Ausstehend: 6
Oldest: 2022-07-09 00:50:24 +0200
Newest: 2022-07-09 19:35:07 +0200

### Status report information ###

Generated at: 2022-07-09 00:48:55 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Would you be able to translate this into english using translate.google.com ?

**Comment by jonathansadowski** [comment]
@Sabs40 thanks for the report. As we haven't received a response, I'm going to close this issue due to inactivity. If you're still think that there's a bug, please feel free to open a new issue.
