### ISSUE TITLE
API update existing product SKU returns product_invalid_sku

### ISSUE THREAD

**Issue by codeagencybe** [woothemes/woocommerce#33806]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After creating a new product via API (successful) trying to update that same product later with more and other details but still the same SKU, it returns an error as below. 
I'm not creating a new product, I'm just updating the existing product with the same SKU. 

{"code":"product_invalid_sku","message":"Ongeldig of dubbel artikelnummer.","data":{"status":400,"resource_id":361069}}

I can't remember this behavior was like this before. Did something change in one of the last WooCommerce updates that is causing this behavior? 

### Expected behavior

Just update the existing product with the same SKU instead of throwing an error. 

### Actual behavior

I create a new product via API, example SKU "SKU1" with some meta data for title and description. 
It returns ID example 1234

After this process I want to update the product with ID 1234 and pass meta data for price and category and the same SKU "SKU1". 
API returns an error {"code":"product_invalid_sku","message":"Ongeldig of dubbel artikelnummer.","data":{"status":400,"resource_id":1234}}

So this results in impossible to update the price or any other fields because the SKU is "the same"? 
When I remove the SKU field from the PUT body, it works fine. 
If I put a DIFFERENT SKU via PUT body, it also works fine!

So clearly there is something off going on that does not accept the same SKU for the same product ID it already has. 

### Steps to reproduce

1. create a new product via API, example SKU "SKU1" with some meta data for title and description. 
2. It returns ID example 1234

3. update the product with ID 1234 and pass meta data for price and category and the same SKU "SKU1". 
4. API returns an error {"code":"product_invalid_sku","message":"Ongeldig of dubbel artikelnummer.","data":{"status":400,"resource_id":1234}}

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.3
PHP Version: 7.3.13
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB-1:10.4.13+maria~bionic
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: mp_
Total Database Size: 905.48MB
Database Data Size: 670.75MB
Database Index Size: 234.73MB
mp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
mp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
mp_woocommerce_order_items: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
mp_woocommerce_order_itemmeta: Data: 0.44MB + Index: 0.50MB + Engine InnoDB
mp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
mp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_actionscheduler_actions: Data: 2.02MB + Index: 2.53MB + Engine InnoDB
mp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_actionscheduler_logs: Data: 1.02MB + Index: 3.03MB + Engine InnoDB
mp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
mp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
mp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mp_e_submissions: Data: 0.03MB + Index: 0.27MB + Engine InnoDB
mp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
mp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
mp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_icl_mo_files_domains: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
mp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_strings: Data: 0.31MB + Index: 0.58MB + Engine InnoDB
mp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_string_translations: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
mp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_icl_translate: Data: 28.56MB + Index: 3.52MB + Engine InnoDB
mp_icl_translate_job: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
mp_icl_translations: Data: 22.14MB + Index: 41.56MB + Engine InnoDB
mp_icl_translation_batches: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
mp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_icl_translation_status: Data: 48.34MB + Index: 5.25MB + Engine InnoDB
mp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_mclean_scan: Data: 3.52MB + Index: 0.33MB + Engine InnoDB
mp_options: Data: 13.02MB + Index: 0.11MB + Engine InnoDB
mp_postmeta: Data: 439.44MB + Index: 100.83MB + Engine InnoDB
mp_posts: Data: 76.20MB + Index: 49.73MB + Engine InnoDB
mp_seopress_significant_keywords: Data: 5.03MB + Index: 6.09MB + Engine InnoDB
mp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_shortpixel_queue: Data: 3.52MB + Index: 9.09MB + Engine InnoDB
mp_termmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
mp_terms: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
mp_term_relationships: Data: 4.09MB + Index: 2.09MB + Engine InnoDB
mp_term_taxonomy: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
mp_usermeta: Data: 2.50MB + Index: 3.02MB + Engine InnoDB
mp_users: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
mp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
mp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_wc_order_product_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
mp_wc_order_stats: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
mp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_wc_product_attributes_lookup: Data: 1.42MB + Index: 1.44MB + Engine InnoDB
mp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_wc_product_meta_lookup: Data: 1.48MB + Index: 1.44MB + Engine InnoDB
mp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.08MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 3
attachment: 283412
custom_css: 1
elementor_library: 12
nav_menu_item: 32
page: 50
post: 17
product: 4949
realisaties: 42
revision: 1
shop_coupon: 1
shop_order: 185
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.8
Admin Menu Editor Pro: by Janis Elsts – 2.17
Advanced Custom Fields PRO: by Delicious Brains – 5.12.2
Custom Post Type UI: by WebDevStudios – 1.12.1
Elementor Pro: by Elementor.com – 3.7.2
Elementor: by Elementor.com – 3.6.7
iThemes Security Pro: by iThemes – 7.1.3
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.2
LoginPress - Auto Login: by WPBrigade – 1.0.7
LoginPress Pro: by WPBrigade – 2.5.2
LoginPress - Customizing the WordPress Login Screen.: by WPBrigade – 1.6.1
Mailgun: by Mailgun – 1.7.9
Ocean Cookie Notice: by OceanWP – 2.0.4
Ocean Elementor Widgets: by OceanWP – 2.2.2
Ocean Extra: by OceanWP – 2.0.2
Ocean Hooks: by OceanWP – 2.0.1
Ocean Sticky Header: by OceanWP – 2.0.5
Ocean White Label: by OceanWP – 2.0.0
PowerPack Pro for Elementor: by Team IdeaBox - PowerPack Elements – 2.9.4
Regenerate Thumbnails Advanced: by ShortPixel – 2.4.0
WooCommerce EU VAT Assistant: by Aelia – 2.0.32.220704
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.11
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.4
WooCommerce: by Automattic – 6.6.1
WP Rocket: by WP Media – 3.11.4.1
SEOPress PRO: by SEOPress – 5.8.0.1
SEOPress: by SEOPress – 5.8.0.5
Smart Image Resize PRO: by Nabil Lemsieh – 1.7.6.4
WPML String Translation: by OnTheGoSystems – 3.2.1

### Inactive Plugins (1) ###

Query Monitor: by John Blackbourn – 3.9.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #93 - /shop/
Cart: #94 - /winkelmand/
Checkout: #95 - /afrekenen/
My account: #96 - /mijn-account/
Terms and conditions: #112 - /algemene-voorwaarden/

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 3.3.3
Parent Theme Author URL: https://oceanwp.org/about-oceanwp/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-11 18:44:43 +02:00
Options: ✔
Notes: 91
Onboarding: completed

### Action Scheduler ###

Complete: 2,202
Oldest: 2022-06-13 09:05:02 +0200
Newest: 2022-07-11 12:32:01 +0200

Pending: 1
Oldest: 2022-07-11 17:15:02 +0200
Newest: 2022-07-11 17:15:02 +0200

### Status report information ###

Generated at: 2022-07-11 12:40:37 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vkwasinski** [comment]
I believe I'm having the same error. I'll try to debug it and see what I can find.

**Comment by vkwasinski** [comment]
Actually the problem relies in this method: 
![image](https://user-images.githubusercontent.com/13423266/181823397-8a873e78-9806-4058-be5b-c5c8ba1c15e0.png)

When the request reaches the **WC_REST_Products_V2_Controller@prepare_object_for_database** and 

![image](https://user-images.githubusercontent.com/13423266/181825650-814bbad8-cd71-4519-848d-f4bf5f8f6488.png)

This logic flow is always reaching **$this->error( 'product_invalid_sku', __( 'Invalid or duplicated SKU.', 'woocommerce' ), 400, array( 'resource_id' => $sku_found ) );**

![image](https://user-images.githubusercontent.com/13423266/181825951-56aa92d3-00c3-42b9-98b7-a23e719dbaf8.png)


My fix for this would be just check if the sku was found like this:
			**if ($sku_found)** $this->error( 'product_invalid_sku', __( 'Invalid or duplicated SKU.', 'woocommerce' ), 400, array( 'resource_id' => $sku_found ) );

I know that the problem with updating is not really this but this is a part of the problem. I did not see a PUT resource for this route Perhaps a solution relies in the creation of this PUT route for this resource.

**Comment by vedanshujain** [comment]
Hey, PUT route is supported for this resource, which you should be able to use in the requests after creating the product. Can you please also add some sample request that we can replay to repro the issue (along with HTTP VERB used, and ofc without any auth data)? Thanks for the report!

**Comment by WillieHuizing** [comment]
I was researching this issue as we have several customers facing the same problem. I believe the reason suggested by @vkwasinski  as to why this is happening isn't what is causing this though. 

When reaching the IF statement, it checks wether or not the SKU is a unique one using 'wc_product_has_unique_sku'. If a product with the same SKU exists this will return FALSE. The '**!**' infront of wc_product_has_unique_sku() validates the statement resulting in a valid error. If no other product was found with the same SKU it would have returned TRUE, skipping the IF statement.

I believe WPML is causing this. 
When adding a translation, they will copy the original product (same SKU). When loading a product, WPML handles retrieving the correct data (translation) for a product and should prevent a 'Invalid or duplicated SKU' error. For some reason this does not always work as it should and I have yet to find a reason as to why this is happening.

The error itself is actually a valid one if you consider that each product translation has the same (duplicate) SKU.

**Comment by codeagencybe** [comment]
@WillieHuizing 
You are touching a very valid point!! 
I have done a few more projects in the past months with the WooCommerce API and we got repeatable "bad" behaviour when WPML is involved. 
Because the SKU field is native WooCommerce, I didn't consider WPML as a potential bad actor, but I just did a test with your feedback by creating a staging copy from one of my projects, disabling WPML and the problem is immediately solved. 

So I definitely can confirm, somehow/somewhere WPML is messing with the 'wc_product_has_unique_sku' method. 
I also don't understand why would do this, because the SKU never changes, it's also not translatable so I don't get why they would even touch it. They already have their own ID's which they refer back to for the translations. 

So I think we better report this problem now back to WPML unfortunately.

**Comment by jorgeatorres** [comment]
Hi @codeagencybe @WillieHuizing!

Given this seems to be an issue with WPML, we're going to close this issue, but feel free to reopen if info comes to light that might suggest this is truly a bug in WC or there's something we can do on our end to improve compatibility.

Thanks!

**Comment by WillieHuizing** [comment]
I know this is not Woocommerce related but I wanted to post my findings in case anyone else comes across this issue having similar problems. 

@codeagencybe I've found the problem and a solution, though I'm not sure how to prevent this from happening. The file 'woocommerce-multilingual/inc/class-wcml-products.php' adds a hook for 'wc_product_has_unique_sku' which triggers the 'check_product_sku' method. It searches for all products with a certain SKU. It then searches 'wp_icl_translations' to find a translation for each of these products. If one of these products has no value in wp_icl_translations it will fail and throw the 'invalid_product_sku' error. 

Removing the product that has no translation will resolve the issue. I think that removing a language from WPML doesn't always remove the duplicate product it had created for that specific language.

**Comment by Mteamr** [comment]
Is this issue still the case? 

> Hi @codeagencybe @WillieHuizing!
> 
> Given this seems to be an issue with WPML, we're going to close this issue, but feel free to reopen if info comes to light that might suggest this is truly a bug in WC or there's something we can do on our end to improve compatibility.
> 
> Thanks!



> @WillieHuizing You are touching a very valid point!! I have done a few more projects in the past months with the WooCommerce API and we got repeatable "bad" behaviour when WPML is involved. Because the SKU field is native WooCommerce, I didn't consider WPML as a potential bad actor, but I just did a test with your feedback by creating a staging copy from one of my projects, disabling WPML and the problem is immediately solved.
> 
> So I definitely can confirm, somehow/somewhere WPML is messing with the 'wc_product_has_unique_sku' method. I also don't understand why would do this, because the SKU never changes, it's also not translatable so I don't get why they would even touch it. They already have their own ID's which they refer back to for the translations.
> 
> So I think we better report this problem now back to WPML unfortunately.

Hi, is this already solved by WPML?

**Comment by JowJoris** [comment]
For anyone looking for a fix, change the filter 
`add_filter( 'wc_product_has_unique_sku', '[ $this, 'check_product_sku' ], 10, 3 ');` 
to the following:
`add_filter( 'wc_product_has_unique_sku', '__return_false');`
Removing the `add_filter`-method does not work.
