### ISSUE TITLE
Marketing task - tweak flow after installing a plugin

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33846]
**Description:** currently, when the user installs a plugin in the marketing task, we automatically redirect him to the home screen. I think keeping him in the marketing task makes more sense where he can install other extensions or click "Manage" to continue setting up the extension.

**Acceptance criteria:**
- [ ] Keep the user in the marketing task after installing an extension

**Comment by pmcpinto** [comment]
@verofasulo @SamratBiswas1  @adrianduffell  let me know if this makes sense

**Comment by SamratBiswas1** [comment]
Makes sense. I would add that we do the same for cash on delivery step. Instead of taking the user to WCPay, we let the user to clock 'manage' to continue setting it up.

**Comment by verofasulo** [comment]
@pmcpinto It makes sense for me, too!
