### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by dgosar** [woothemes/woocommerce#33887]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When executing order create functionality, the API returns **certificate has expired**. I am using npm library woocommerce-api on node js side and woocommerce is independently hosted on a separate url. I have configure the API as below:

```
var WooCommerceAPI = require('woocommerce-api');
var WooCommerce = new WooCommerceAPI({
    url: 'website url where WooCommerce is hosted',
    consumerKey: 'ck_*******',
    consumerSecret: 'cs_*******',
    version: 'v3'
  }); 
```
FrontEnd: React Js
Backend: Node Js
WooCommerce hosted: WordPress (independent website)

### Expected behavior

Its should return me expected output

### Actual behavior

certificate has expired

### Steps to reproduce

1. Install and configure woocommerce on wordpress
2. Create a webhook in woocommerce for order creation
3. Create a react app with a test button
4. On click on button it will trigger API written in Node Js for creating order

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.byowave.io
Site address (URL): http://www.byowave.io
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 880 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB
Max Upload Size: 880 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 132.91MB
Database Data Size: 99.00MB
Database Index Size: 33.91MB
wp_woocommerce_sessions: Data: 16.05MB + Index: 3.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 18.06MB + Index: 12.34MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.02MB + Index: 5.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bb_email_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_activity: Data: 0.06MB + Index: 0.16MB + Engine InnoDB
wp_bp_activity_meta: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wp_bp_document: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_document_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_document_folder_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_document_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_follow: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_friends: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_groups: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_groups_groupmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_groups_members: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_bp_media: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_media_albums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_messages_messages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_messages_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_bp_messages_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_messages_recipients: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bp_moderation: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_moderation_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_suspend: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_suspend_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_zoom_meetings: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_zoom_meeting_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_zoom_recordings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_zoom_webinars: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_zoom_webinar_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_zoom_webinar_recordings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gamipress_logs_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_transfers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_transfers_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_transfer_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_transfer_items_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_transfer_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gamipress_transfer_notes_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_user_earnings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gamipress_user_earnings_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_monsterinsights_pageinsights_cache: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.02MB + Index: 1.16MB + Engine InnoDB
wp_postmeta: Data: 36.41MB + Index: 1.83MB + Engine InnoDB
wp_posts: Data: 8.12MB + Index: 6.03MB + Engine MyISAM
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 0.36MB + Index: 0.06MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_transactions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

achievement-type: 1
attachment: 306
bp-email: 26
customize_changeset: 5
elementor_library: 9
forum: 1
job_listing: 3
nav_menu_item: 17
page: 29
points-type: 1
post: 7
product: 4
rank-type: 1
reply: 4
revision: 903
shop_order: 155
slime: 1
step: 1
topic: 1
wp_global_styles: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Akismet Anti-Spam: by Automattic – 4.2.4
All in One SEO Pro: by All in One SEO Team – 4.1.10
AWS for WordPress: by AWS Labs
WP Engine – 4.3.2

BuddyBoss Platform Pro: by BuddyBoss – 2.0.2
BuddyBoss Platform: by BuddyBoss – 2.0.5
Elementor Pro: by Elementor.com – 3.7.2
Elementor: by Elementor.com – 3.6.7
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 8.3.5
GamiPress - BuddyBoss integration: by GamiPress – 1.2.5
GamiPress - BuddyBoss Notifications: by GamiPress – 1.0.4
GamiPress - Elementor integration: by GamiPress – 1.0.6
GamiPress - Frontend Reports: by GamiPress – 1.0.3
GamiPress - Leaderboards: by GamiPress – 1.3.9
GamiPress - Points Limits: by GamiPress – 1.0.5
GamiPress - Progress Map: by GamiPress – 1.1.2
GamiPress - Progress: by GamiPress – 1.4.1
GamiPress - Referrals: by GamiPress – 1.1.0
GamiPress - Reports: by GamiPress – 1.0.8
GamiPress - Restrict Content: by GamiPress – 1.2.2
GamiPress - Social Share: by GamiPress – 1.2.4
GamiPress - Time-based Rewards: by GamiPress – 1.0.8
GamiPress - Transfers: by GamiPress – 1.2.5
GamiPress: by GamiPress – 2.3.5
MonsterInsights Pro: by MonsterInsights – 8.7.0
Google Listings and Ads: by WooCommerce – 2.0.0
Site Kit by Google: by Google – 1.75.0
Hide My WP Ghost: by WPPlugins – 6.0.18
Hide My WP Ghost: by WPPlugins – 6.0.18
Hotjar: by Hotjar – 1.0.14
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 8.13.58
MWB HubSpot for WooCommerce: by MakeWebBetter – 1.3.1
OAuth Single Sign On - SSO (OAuth client): by miniOrange – 48.4.5
MonsterInsights - Dimensions Addon: by MonsterInsights Team – 2.0.4
MonsterInsights - EU Compliance: by MonsterInsights Team – 2.2.2
MonsterInsights - Forms Tracking Addon: by MonsterInsights Team – 2.2.3
MonsterInsights - Google Optimize Addon: by MonsterInsights Team – 1.5.0
MonsterInsights - Media Addon: by MonsterInsights Team – 1.0.1
MonsterInsights - Page Insights Addon: by MonsterInsights Team – 1.5.0
WooCommerce Stripe Gateway: by WooCommerce – 6.4.3
WooCommerce Payments: by Automattic – 4.4.0
WooCommerce: by Automattic – 6.6.1
WP Crowdfunding: by Themeum – 2.1.2
WP Job Manager: by Automattic – 1.36.2
WP Mail SMTP Pro: by WPForms – 3.4.0
Smush Pro: by WPMU DEV – 3.9.9
WPMU DEV Dashboard: by WPMU DEV – 4.11.12

### Inactive Plugins (10) ###

3D Embedder - Simple yet powerful 3D embedder for Elementor.: by bPlugins – 1.0.0
Image optimization service by Optimole: by Optimole – 3.4.3
Jetpack: by Automattic – 11.1
Login with Cognito: by miniOrange – 1.4.7
OAuth Single Sign On - SSO (OAuth Client): by miniOrange – 6.23.0
W3 Total Cache: by BoldGrid – 2.2.1
WooCommerce PayPal Payments: by WooCommerce – 1.8.1
WooCommerce Product Add-ons: by WooCommerce – 4.9.0 (update to version 5.0.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.26.2
WPForms Lite: by WPForms – 1.7.5.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: crowdfunding (crowdfunding)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 3.8.2 (update to version 3.8.5 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-15 11:31:30 +00:00
Options: ✔
Notes: 69
Onboarding: completed

### WooCommerce Payments ###

Version: 4.4.0
Connected to WPCOM: Yes
Blog ID: 204900762
Account ID: acct_1KkWCa2HaEzwpQUw

### Action Scheduler ###

Complete: 32,511
Oldest: 2022-06-13 14:52:41 +0000
Newest: 2022-07-14 11:43:16 +0000

Pending: 13
Oldest: -0001-11-30 00:00:00 +0000
Newest: 2022-07-21 06:04:11 +0000

### Status report information ###

Generated at: 2022-07-14 11:45:33 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @dgosar,

Thanks for reaching out. First of all, the JS API you're using is now deprecated, with the alternative being https://www.npmjs.com/package/woocommerce-api, which is pretty similar.
That said, it seems to us that the error isn't coming from the library itself but it just means SSL verification has failed, which might be related to the site you're testing on and its SSL certificate.

While not ideal, you can try disabling SSL verification while using the API, by passing `verifySsl: false` to the client args:

```js
var WooCommerce = new WooCommerceAPI({
    url: 'website url where WooCommerce is hosted',
    consumerKey: 'ck_*******',
    consumerSecret: 'cs_*******',
    version: 'v3',
    verifySsl: false
  }); 
```

Please let us know if either that or using the new version of the API works for you. We'll be happy to take it from there!
