### ISSUE TITLE
Implement a feature toggle that allows users to switch between the old UI and the new UI.

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#33896]
This is part of the epic issue https://github.com/woocommerce/woocommerce/issues/33895.

In this issue, we want to implement a feature toggle that allows users to switch between the old UI and the new UI:

- When the toggle is on, `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing` will display the new UI.
	- For starter, the new UI can be just an empty placeholder page. We will put in components into the page in other tasks. 
- When the toggle is off, `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing` will display the existing UI.

The toggle can be put into the WooCommerce > Settings > Advanced > Features page: `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`

<img width="805" alt="image" src="https://user-images.githubusercontent.com/417342/179003511-3455f36f-c5be-4606-a889-bb443fb5cacf.png">

**Comment by lukecav** [comment]
Is there an ETA on when the new navigation experience UI will be the default experience for users?

**Comment by ecgan** [comment]
> Is there an ETA on when the **new navigation experience UI** will be the **default experience** for users?

Hi @lukecav, thanks for the question. Unfortunately I don't have the answer. Based on WooCommerce's [How to Get Help](https://woocommerce.com/document/how-to-get-help/) page ("Questions and Support" section at the bottom of the page), I think the best way is to [Open a Support Request](https://woocommerce.com/my-account/create-a-ticket/) (if you are a paying customer) or reach out in the [WooCommerce Support Forum](https://wordpress.org/support/plugin/woocommerce/).

The issue in this page is related to the Marketing page work that we are working on (see the parent epic issue https://github.com/woocommerce/woocommerce/issues/33895), not related to the WooCommerce Navigation experience.

**Comment by ecgan** [comment]
This task is done in PR https://github.com/woocommerce/woocommerce/pull/33964. Closing this issue.
