### ISSUE TITLE
[Enhancement]: Add icon to admin bar for new review

### ISSUE THREAD

**Issue by vladoATL** [woothemes/woocommerce#33894]
### Describe the solution you'd like

Since the products reviews were moved under Product we are not able to see if a new review is waiting for approval. Going to dashboard is one more step and we do not go there often. It used to show waiting reviews which was very helpful.  I suggest you add a new icon similar to the Comments to admin area.
[https://www.screencast.com/t/errWOaJgpJ](https://www.screencast.com/t/errWOaJgpJ)

### Describe alternatives you've considered

Create a new icon in admin bar for waiting product reviews

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this change is very helpful, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
