### ISSUE TITLE
UI Revamp on Marketing Page

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#33895]
This is an epic issue to keep track of our UI revamp on marketing page in WooCommerce Admin.

## Designs

This is how the current Marketing page looks like:

![image](https://user-images.githubusercontent.com/417342/179001079-8b429aa3-68e9-4d8f-b9b9-d79ebbcce294.png)

This is the design for the new Marketing page:

![image](https://user-images.githubusercontent.com/417342/179001195-b01b7f44-96a9-4329-8e85-adb3dd4dbe39.png)

## Tasks

Tasks related to this epic:

- [x] #33896
- [x] #34025
- [x] #34107
- [x] #34108
- [x] #34431
- [x] #34655
- [x] #34732

Note that this epic does not include the "Channels" card and the "Campaigns" card in the new design. 

Update: Note that the top banner card is now out of scope of this epic issue. For more info, see pe2C5g-hG-p2.

## Notes

Internal P2 project thread: pe2C5g-bH-p2

**Comment by ecgan** [comment]
👋 Hi @becdetat, with regards to your comment in pe2C5g-by-p2#comment-57 to get cross-team collaboration, could you advise if the PR review process that we are doing here is alright?

In the description of this epic issue above, there are 4 task issues. 3 of them have associated PRs created:

- https://github.com/woocommerce/woocommerce/pull/33964: already reviewed by Ventures team member @puntope.
- https://github.com/woocommerce/woocommerce/pull/34080: already reviewed by Ventures team member @puntope.
- https://github.com/woocommerce/woocommerce/pull/34264

All the PRs above have their base branch set to the main feature branch, `feature/33895-marketing-page/main`. I plan to merge `feature/33895-marketing-page/main` into `trunk` branch when all the task issues are completed.

Does the above look okay? Should I request reviews from others in my PRs (and if yes, who or which team)? Is there anything that I should change? Maybe I should have merged the PRs into the `trunk` branch directly, instead of the `feature/33895-marketing-page/main` branch?

This is my first code contribution project in the https://github.com/woocommerce/woocommerce repo, appreciate your advice for my learning. 🙂 🙏

**Comment by becdetat** [comment]
Hi @ecgan . I'm so sorry I haven't answered earlier. I was AFK (post-vaccine blues) the end of last week and have been playing catch up this week on a number of projects.

I think using the feature branch is a valid strategy when you have PRs that form the same unit of functionality. If each PR could be released separately as individual, usable units of functionality then it might be better to target `trunk`, just to get them into the main line faster and possibly have longer for them to be tested. Obviously using a feature branch also has the risk of getting stale compared to `trunk` and needing rebasing.

You can totally request a review from someone in the Start and Manage teams, but probably the best way to do that is to drop into the #woo-start-manage Slack channel and ask for a review there, and someone should pick it up fairly quickly. Either team should be able to look it it, marketing is kind of a split responsibility. Our process is for a single reviewer to approve a PR, unless they need a second opinion :-) but we'll handle that. I would request a review for each individual PR/task issue, regardless of whether you're using a feature branch or targeting `trunk` directly.

If you're using the feature branch model and all of your PRs are approved and merged and the feature branch is ready, please request another PR review for the merge, just for a check over the combined code to see if there are any issues that weren't evident in the individual PRs.

The PRs themselves look good, you seem to have clear testing instructions which make things easy.

I did notice that you've got a TODO in [one of them](https://github.com/woocommerce/woocommerce/pull/33964/files#diff-e408579fe78195c4846ef8cc5d6dd8fd1af41e62ec933b93f8261da029cd85f0R2), I don't think this is officially discouraged at A8C but if I was reviewing the PR I would ask for it to be removed and created as an issue - TODO comments tend to just never get done despite our best intentions.

The major thing I can see that is missing though is any tests. I've been encouraging more tests (not full coverage, but enough that it makes sense). Any complex interactions I would love to see a UI test for, as there is a big risk of regressions. Any complex logic should be unit tested where possible (and the logic should be factored in a way to make it possible).

**Comment by ilyasfoo** [comment]
Hey, @ecgan! 👋 

Feature branch strategy works well for this case since (as far as I'm aware) we've not planned any refactors or big changes in the marketing section.

Generally, a reviewer from your team would be sufficient, but if you feel you've changed something that should be looked at by us, feel free to include @woocommerce/mothra and @woocommerce/ghidorah as a reviewer. And @becdetat mentioned, ping us in slack to get a quicker response!

Thanks for your contribution as well!

**Comment by ecgan** [comment]
@becdetat , thank you for the feedback! Now I know I'm heading towards the right direction. 😄 

> I did notice that you've got a TODO in [one of them](https://github.com/woocommerce/woocommerce/pull/33964/files#diff-e408579fe78195c4846ef8cc5d6dd8fd1af41e62ec933b93f8261da029cd85f0R2), I don't think this is officially discouraged at A8C but if I was reviewing the PR I would ask for it to be removed and created as an issue - TODO comments tend to just never get done despite our best intentions.

Gotcha. Just want to note that It has already been removed in PR https://github.com/woocommerce/woocommerce/pull/34080/files#diff-e408579fe78195c4846ef8cc5d6dd8fd1af41e62ec933b93f8261da029cd85f0L2-L4.

> The major thing I can see that is missing though is any tests. I've been encouraging more tests (not full coverage, but enough that it makes sense). Any complex interactions I would love to see a UI test for, as there is a big risk of regressions. Any complex logic should be unit tested where possible (and the logic should be factored in a way to make it possible).

Yeah the tests are missing because I am kinda in a crunch time to develop the feature, and there isn't really any complex logic (they are pretty straightforward) that I feel worth the unit tests.

At one point, I discovered that we have [playwright e2e test for coupons](https://github.com/woocommerce/woocommerce/blob/5f257ed7d0439214a58affac99968d4315ce0f6a/plugins/woocommerce/tests/e2e-pw/tests/admin-marketing/coupons.spec.js), and I'm thinking to have some e2e tests for the marketing page to test the interactions after the feature development is done.

**Comment by ecgan** [comment]
@ilyasfoo , thanks for the feedback, especially for the team names (I needed that)! 😄 👍

**Comment by becdetat** [comment]
> Yeah the tests are missing because I am kinda in a crunch time to develop the feature, and there isn't really any complex logic (they are pretty straightforward) that I feel worth the unit tests

Crunch time is an issue, we shouldn't ever be doing that IMO but you're not on my team so I won't argue ;-).

If tests were important then they are even more critical if you have pressure and crunch time. Otherwise you're potentially shipping buggy, broken code which is worse than not shipping on time in a product like WooCommerce Core with a relatively slow release cadence.

However if you feel like there's not enough complex logic to warrant tests then that's ok, it's important to consider cost vs benefit with anything like that. Just make sure it's manually tested well enough and the test instructions cover all scenarios and edge cases.

**Comment by ecgan** [comment]
> If tests were important then they are even more critical if you have pressure and crunch time. Otherwise you're potentially shipping buggy, broken code which is worse than not shipping on time in a product like WooCommerce Core with a **relatively slow release cadence**.

@becdetat, this is really a golden nugget of advice that I need to remind myself often. Thank you! 😃

**Comment by findingsimple** [comment]
> we shouldn't ever be doing that IMO but you're not on my team so I won't argue ;-).

Just want to be clear that no one is forcing anyone to not write tests 😄 @ecgan please be pragmatic about writing tests. The feature will be behind a feature flag (as an MVP/beta) so I think it's good to have the basics covered. We can always add more.

**Comment by ecgan** [comment]
> writing tests

Closing the loop here with @jconroy @becdetat, I've added some Playwright e2e tests and component tests under issue https://github.com/woocommerce/woocommerce/issues/34732 and PR https://github.com/woocommerce/woocommerce/pull/34840. 🙂

**Comment by ecgan** [comment]
All the tasks are completed, I'm closing this issue.

**Comment by ecgan** [comment]
The next iteration of multichannel marketing page is in epic issue https://github.com/woocommerce/woocommerce/issues/34903.
