### ISSUE TITLE
Cache `.turbo` Directories in CI

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33908]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The entire point of using Turborepo is to take advantage of task caching. We need to integrate this caching into our CI so that we can speed it up.

* Use a branch-specific cache key
* Cache `.turbo` directories in each package, likely using our composite install/build action
  * We can take this opportunity to make sure all of the workflows are using this too!

**Comment by Luc45** [comment]
I was playing around with hashing the build of `woocommerce-admin` to cache it.

It's end of day here and I'll be dropping this, but this is what I've done so far, if it helps:


`./bin/check-cache.php` This file will pre-compute the hash of the build to be created based on the sum of hashes of the source.

```php
<?php

$root_dir         = __DIR__ . '/../';
$build_cache_file = $root_dir . '.build-cache';

echo sprintf( "Getting hash for directory '%s'\n", realpath( $root_dir ) );

$current_hash = trim( shell_exec( "find '$root_dir' -type f ! -path '*/node_modules/*' ! -name .build-cache -print0 | sort -z | xargs -0 sha1sum | sha1sum | cut -d' ' -f1" ) );

// We expect a SHA1 hash composed of 40 hexadecimal characters.
if ( ! preg_match( '/^[0-9a-f]{40}$/i', $current_hash ) ) {
	echo "Invalid SHA1 hash. $current_hash\n"; // $hash will contain the error, such as "find: command not found" if the host does not have 'find'
	die( 0 ); // Signal that will continue to process chain of scripts. (Will simply skip cache)
}

$existing_cache = null;

if ( isset( $argv[2] ) ) {
	$existing_cache = trim( $argv[2] );
	echo "Using cache key found in argument: $existing_cache\n";
} elseif ( is_string( getenv( 'WOOCOMMERCE_ADMIN_BUILD_CACHE_KEY' ) ) && ! empty( getenv( 'WOOCOMMERCE_ADMIN_BUILD_CACHE_KEY' ) ) ) {
	$existing_cache = trim( getenv( 'WOOCOMMERCE_ADMIN_BUILD_CACHE_KEY' ) );
	echo "Using cache key found in environment variable: $existing_cache\n";
} elseif ( file_exists( $build_cache_file ) ) {
	$existing_cache = trim( file_get_contents( $build_cache_file ) );
	if ( ! empty( $existing_cache ) ) {
		echo "Using cache key found in .build-cache file\n";
	}
}

$written = file_put_contents( $build_cache_file, $current_hash );

if ( empty( $written ) ) {
	echo "Could not write to '$build_cache_file' file\n";
}

if ( $current_hash === $existing_cache ) {
	echo "Hashs match.\nExisting: $existing_cache\nCurrent: $current_hash\n";
	die( 1 ); // Signal that will stop further execution of chained scripts.
} else {
	echo "Hashes do not match\nExisting: $existing_cache\nCurrent: $current_hash\n";
	die( 0 ); // Signal that will continue to process chain of scripts.
}
```

**To test:**

- cd plugins/woocommerce-admin
- php ./bin/check-cache.php

Verify it says something like:

```
Getting hash for directory '/home/lucas/automattic/woocommerce/plugins/woocommerce-admin'
Hashes do not match
Existing: 
Current: ede98d8273868775f84b6abc94c93db0d7641ca8
```

Repeat steps above and it should say:

```
Getting hash for directory '/home/lucas/automattic/woocommerce/plugins/woocommerce-admin'
Using cache key found in .build-cache file
Hashs match.
Existing: ede98d8273868775f84b6abc94c93db0d7641ca8
Current: ede98d8273868775f84b6abc94c93db0d7641ca8
```

Change any file and repeat the steps. The hash should have changed, and the output should reflect that.

**Integrating this with the `build` command:**

Edit the build step of `plugins/woocommerce-admin/package.json` and add `php ./bin/check-cache.php` as first step of the build:

```
"build": "php ./bin/check-cache.php && node ./node_modules/require-turbo && pnpm run install-if-deps-outdated && pnpm run clean && WC_ADMIN_PHASE=core pnpm run build:packages && WC_ADMIN_PHASE=core pnpm run build:feature-config && cross-env NODE_ENV=production WC_ADMIN_PHASE=core webpack",
```
If the hashes matches, it will bail early execution of the build.

So in CI, on a run with invalid cache, it will process the build. Then we cache `woocommerce/assets/client` and save/restore it using the hash in .build-cache, which will be persisent in runtime given that the source does not change.

**Comment by ObliviousHarmony** [comment]
While we can cache the outputs of each, what about the `assets` output in `plugins/woocommerce`? They're built as part of the sub-package and need to be cached somehow? Maybe copy them after cache hydration to the correct directory. Maybe it can use directory traversal in `turbo.json` to cache there?
