### ISSUE TITLE
Simplify Repository Tooling

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33907]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We are currently requiring contributors to use both `pnpm` and `turbo` commands. This has proven unwieldy for many people, so, I'd like to iterate on our current usage of Turborepo.

* Change pipelines to `turbo:` prefixed ones.
* Move `build`, `lint`, `test`, and `e2e` scripts into `turbo:` prefixed ones.
* Replace `build`, `lint`, `test,` and `e2e` scripts with those that run `turbo` commands.
  * We need to make sure arguments are passed correctly to both turbo _and_ the underlying script.
  * These should use `--filter` and either the project name or the `package.json`'s directory (maybe there's an `$npm_` variable to get this information?. This way they're only running on the project.
* Add root `build`, `lint`, `test,` and `e2e` scripts that run `turbo` commands without a `--filter`.
* Replace `pnpm -- turbo run` documentation with this easier-to-follow documentation. We _do_ want to keep Turborepo extensively documented in some form so that people are aware of the more complex usage, but, it should be for advanced users.
* Aggressively communicate this to developers internally.

Our goal with this work is to make it so that you can run `pnpm build|lint|test|e2e` commands from within a package folder without knowing anything about Turborepo. It will still be available (and documented) for those who want to use more powerful commands, but, this should cover most use-cases.

**Comment by adrianduffell** [comment]
This sounds good, thank you @ObliviousHarmony 

> * Change pipelines to `turbo:` prefixed ones.
> * Move `build`, `lint`, `test`, and `e2e` scripts into `turbo:` prefixed ones.
> * Replace `build`, `lint`, `test,` and `e2e` scripts with those that run `turbo` commands.

What's the reason for creating the `turbo:` prefixed scripts? Just curious in learning more.

**Comment by ObliviousHarmony** [comment]
That's a good question @adrianduffell.

So, `turbo run` actually works by calling NPM scripts. `turbo run build` will call `"build"` in every related package according to its place in the dependency graph. If we had `"build": "turbo run build"`, we would just recurse and never actually build anything. By moving the _real_ operation into `"turbo:build": "build-the-package"`, we can change `"build"` to make sure it's always using `turbo`.

The end result is that it's impossible to accidentally not use turbo. No avoiding the build cache, no weird funniness locally, and guaranteed building|linting|testing|e2eing of dependencies.

**Comment by adrianduffell** [comment]
> If we had `"build": "turbo run build"`, we would just recurse and never actually build anything.

Ha, I see! Thank you for explaining 👍
