### ISSUE TITLE
Generate JSON of detected changes from `code_analyzer`

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#33921]
This task is to generate a JSON file (or files) representing the detected hook/template/schema changes that `code-analyzer` is already scanning.

`code-analyzer` just outputs these changes as CLI output at the moment, but outputting a file representing changes will allow other tools to easily consume a list of changes for other automation tasks like generating release posts.

**Comment by ObliviousHarmony** [comment]
Hey @samueljseay, could you add a description to this issue so that it's more understandable? I've gone ahead and labeled it appropriately as well as added it to the team's project.

**Comment by samueljseay** [comment]
This was resolved in #33955
