### ISSUE TITLE
Attempting to run pnpm changelog add without composer install gives cryptic error

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#33937]
If you attempt to run `pnpm changelog add --filter=woocommerce` (for example) prior to there being a `composer install`, the error you receive is cryptic. We should either find a way to improve the error messaging to tell you how to resolve the issue, or perhaps just resolve the issue automatically.

See p1657911267976909-slack-C02GB41LGHM

**Comment by psealock** [comment]
Now that `compser install` is run after `pnpm install` is this issue still valid @jonathansadowski or is it safe to close?

I will close it out because thats my understanding, but feel free to open it up again if need be.

**Comment by jonathansadowski** [comment]
@psealock I think we're good to close this, as you mentioned. If we keep seeing people experiencing this, we can revisit.
