### ISSUE TITLE
Optimize React Admin's `package.json` Scripts

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33948]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There are a large number of different workflows supported by the current `package.json` script. As a consequence of our tooling changes, however, there is a non-trivial amount of extra work being done in these scripts. Once https://github.com/woocommerce/woocommerce/issues/33907 lands, we should review all of the scripts and look for areas of performance deficit:

- `build:packages` is no longer necessary, `turbo` builds all dependencies.
- Check for cases where `turbo` is being bypassed entirely.
- Review supported workflows and discuss flattening them where appropriate with their respective teams.

**Comment by ObliviousHarmony** [comment]
About the `dev` and `start` scripts:

This script feels like it's doing a lot that it doesn't need to.

* Can we add `build:feature-config` to `"turbo:build"`? Would you want it to build the feature config whenever it builds the command?
* We don't need to run `build` on all of the JS packages, right? They're dependencies of `woocommerce/client/internal` and Turbo will build them for us, right?
* If the above is all true, can we replace this with `cross-env WC_ADMIN_PHASE=development pnpm run build && cross-env WC_ADMIN_PHASE=development webpack` or something similar?

**Comment by psealock** [comment]
>Can we add build:feature-config to "turbo:build"? Would you want it to build the feature config whenever it builds the command?

It's in there now and the result is being cached when it should not. ie, changing a config then running `pnpm run build` should result in correct feature config generation.

This is fixed in https://github.com/woocommerce/woocommerce/pull/34296

**Comment by samueljseay** [comment]
One thing we could also tie this into is consolidating lint as in: https://github.com/woocommerce/platform-private/issues/94

**Comment by lsinger** [comment]
This specific issue seems like it hasn't been worked on in a long time and is also part of the blocked Epic https://github.com/woocommerce/woocommerce/issues/32433. Moving this to Not Started.

**Comment by ObliviousHarmony** [comment]
Closing this in favor of new issues as an output from a larger project to complete the merge.
