### ISSUE TITLE
Filename cannot be empty in /.../saintmedie.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 53

### ISSUE THREAD

**Issue by studioatable** [woothemes/woocommerce#33946]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello.
impossible to display the last order validation page (thank you) on woocommerce regardless of the type of payment.
Bank transfer generates a 404 error. 
![bug17072022](https://user-images.githubusercontent.com/52157224/179403148-acb63b3c-8397-4f4c-a453-f83950c22984.png)
Payment in test and transaction generates the following error:

Warning: include(): Filename cannot be empty in /home/sc2sid11/public_html/saintmedie.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 53

Warning: include(): Failed opening '' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/sc2sid11/public_html/saintmedie.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 53

>>> Panier: ❌ La page ne contient pas le code court [woocommerce_cart] ou le bloc woocommerce/cart.
>>> Commander: ❌ La page ne contient pas le code court [woocommerce_checkout] ou le bloc woocommerce/checkout.

These two pages use the latest code functions provided by Elementor and even if I put these shortcodes back by default. It doesn't change anything...

### Expected behavior

The site uses the latest version of woocommerce with Elementor Pro and child theme under Hello theme.
All mods are up to date. I tried disabling them all with the default wordpress theme. This does not change the bug.

### Actual behavior

When you click on order, the site looks for the order validation page and does not find it while everything is ok on the woocommerce setting side

### Steps to reproduce

1 go to: https://www.saintmedie.com
2 place order. (use customer test account: test@saintmedie.com / TSTsmd#2022!)
3 click on the "order" button
4 generates the error.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.saintmedie.com
Site address (URL): https://www.saintmedie.com
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 4 Go
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 512 Mo
PHP Time Limit: 360
PHP Max Input Vars: 2000000
cURL Version: 7.84.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.35-MariaDB
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: StMd01_
Taille totale de la base de données: 18.83MB
Taille de la base de données: 16.21MB
Taille de l’index: 2.62MB
StMd01_woocommerce_sessions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
StMd01_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
StMd01_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_woocommerce_order_itemmeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
StMd01_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
StMd01_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_actionscheduler_actions: Données : 0.06MB + Index : 0.11MB + Moteur InnoDB
StMd01_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_actionscheduler_logs: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
StMd01_aiowps_debug_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_events: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_failed_logins: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_global_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_login_activity: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_login_lockdown: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_aiowps_permanent_block: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
StMd01_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_e_notes: Données : 0.02MB + Index : 0.17MB + Moteur InnoDB
StMd01_e_notes_users_relations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
StMd01_e_submissions: Données : 0.02MB + Index : 0.27MB + Moteur InnoDB
StMd01_e_submissions_actions_log: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
StMd01_e_submissions_values: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_litespeed_url: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_litespeed_url_file: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
StMd01_options: Données : 3.50MB + Index : 0.08MB + Moteur InnoDB
StMd01_postmeta: Données : 10.08MB + Index : 0.14MB + Moteur InnoDB
StMd01_posts: Données : 1.06MB + Index : 0.06MB + Moteur InnoDB
StMd01_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_usermeta: Données : 0.06MB + Index : 0.03MB + Moteur InnoDB
StMd01_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
StMd01_wc_admin_notes: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
StMd01_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_wc_etransactions_cards: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_etransactions_payment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
StMd01_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
StMd01_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
StMd01_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
StMd01_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_yoast_indexable: Données : 0.08MB + Index : 0.09MB + Moteur InnoDB
StMd01_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
StMd01_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
StMd01_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
StMd01_yoast_seo_links: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB

### Post Type Counts ###

attachment: 41
elementor_library: 8
nav_menu_item: 10
page: 8
post: 2
product: 2
shop_order: 25
sl-insta-account: 1
sl-insta-feed: 1
sl-insta-media: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (14) ###

Advanced Database Cleaner: par Younes JFR. – 3.1.1
All In One WP Security: par All In One WP Security & Firewall Team – 4.4.12
Classic Editor: par Contributeurs et contributrices WordPress – 1.6.2
Yoast Duplicate Post: par Enrico Battocchi & l’équipe Yoast – 4.5
e-Transactions: par e-Transactions – 1.0.2
Elementor Pro: par Elementor.com – 3.7.2
Elementor: par Elementor.com – 3.6.7
Flexible Shipping: par Octolize – 4.13.1
Really Simple SSL: par Really Simple Plugins – 5.3.2
Spotlight - Social Media Feeds: par RebelCode – 1.1.1
UpdraftPlus - Backup/Restore: par UpdraftPlus.Com
DavidAnderson – 2.22.14.25

Invoices for WooCommerce: par Bas Elbers – 3.1.9
WooCommerce: par Automattic – 6.7.0
Yoast SEO: par L’équipe Yoast – 19.3

### Inactive Plugins (4) ###

Advanced Dynamic Pricing for WooCommerce: par AlgolPlus – 4.1.2
LiteSpeed Cache: par LiteSpeed Technologies – 4.6
Min and Max Quantity for WooCommerce: par BeRocket – 1.3.2.4
Woo Discount Rules: par Flycart – 2.4.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la boutique: #7 - /boutique/
Panier: ❌ La page ne contient pas le code court [woocommerce_cart] ou le bloc woocommerce/cart.
Commander: ❌ La page ne contient pas le code court [woocommerce_checkout] ou le bloc woocommerce/checkout.
Mon compte: #10 - /mon-compte/
Conditions générales de vente et d’utilisation: #3 - /politique-de-confidentialite/

### Theme ###

Name: Studio à Table Hello Theme
Version: 0.1.0
Author URL: https://www.studioatable.fr
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.0.5
Parent Theme Author URL: https://elementor.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-18 07:11:31 +02:00
Options: ✔
Notes: 44
Onboarding: completed

### Action Scheduler ###

Terminé: 122
Oldest: 2022-06-17 20:07:17 +0200
Newest: 2022-07-17 16:29:25 +0200

Échoué: 1
Oldest: 2022-03-17 17:49:25 +0100
Newest: 2022-03-17 17:49:25 +0100

En attente: 1
Oldest: 2022-07-17 19:19:13 +0200
Newest: 2022-07-17 19:19:13 +0200

### Status report information ###

Generated at: 2022-07-17 16:37:09 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @studioatable,

Can you confirm that this bug also happens with the Storefront theme and no plugins active? This sounds like it might be the case of a template file in a theme being broken or something of the sort.
