### ISSUE TITLE
Review React Admin Build Process

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33947]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

With our current tooling in place, we need to take a look at the build process in `plugins/woocommerce-admin`. Given how old the Webpack file is and how many iterations it has gone through, it is worthwhile for us to examine it and consider even rewriting it. Packages should be consumed as if they were any other NPM package and the latest Webpack features should be fully utilized. We might also consider looking into alternatives if that's desired, but, that will require additional buy-in from the teams working on the admin experience.

**Comment by lsinger** [comment]
This specific issue seems like it hasn't been started and is also part of the blocked Epic #32433. Moving this to Not Started.

**Comment by ObliviousHarmony** [comment]
Closing this in favor of new issues as an output from a larger project to complete the merge.
