### ISSUE TITLE
Blank payment task when user disable marketplace suggestions

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#33958]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a user agrees to tracking but disables marketplace suggestions, payment task will render an infinitely loading screen.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/3747241/179459227-d5dad4c8-9210-4c83-8fb6-8e6ee5e23b43.png">

API call to `/wp-json/wc-admin/payment-gateway-suggestions?_locale=user` returns empty array:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/3747241/179459294-e6dc3e3c-ee01-4f0a-be05-4b8083874f65.png">

### Expected behavior

Payment task should be loaded with locally sourced payment options.

### Actual behavior

Payment task never finished loading

### Steps to reproduce

1. Set up a store and agree tracking but don't install WCPay in business step
2. Go to WooCommerce > Settings > Advanced > WooCommerce.com > Untick "Show Suggestions" checkbox
3. Go to set up payments task
4. Observe infinite loading

### WordPress Environment

WooCommerce 6.8

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
Hi @woocommerce/mothra, this bug is possibly caused by https://github.com/woocommerce/woocommerce/commit/834307e15540541458a1c08883d6286e845b0e2a and I'm wondering what would be the appropriate solution for it:

1. Hide set up payments task since user has disabled suggestion
2. Create another endpoint that returns default suggestion regardless of if user accepted suggestions
3. Suggest only offline payment gateways

cc @SamratBiswas1 @pmcpinto

**Comment by moon0326** [comment]
@ilyasfoo 

I opted to add an argument to the suggestion endpoint to return the default suggestions when the marketplace suggestion option is set to no in this [PR](https://github.com/woocommerce/woocommerce/pull/34083) for now

pinging @SamratBiswas1  and @pmcpinto again for feedback 🙏

**Comment by SamratBiswas1** [comment]
I would go ahead with option 2 since payments is critical and the user intent of disabling marketplace suggestion is more to do with extensions and not the basic functionality like payments. 
Option 2 being - Create another endpoint that returns default suggestion regardless of if user accepted suggestions
