### ISSUE TITLE
Algerian province list is incomplete as of 2019 (Also some are misspelled)

### ISSUE THREAD

**Issue by melek** [woothemes/woocommerce#33969]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Algeria ( Country ) Has 58 provinces ( Wilayas ) and you can check on wikipedia if you want to update:
Provinces of Algeria - Wikipedia (https://en.wikipedia.org/wiki/Provinces_of_Algeria)

According to the article, 10 more provinces were added in 2019. This issue was received from a customer in 5405465-zen.

In WooCommerce, these 10 states do not appear in the state list for the country. Additionally, some states need their English spelling updated.

### Expected behavior

WooCommerce should have up-to-date, correctly spelled province lists for each country.

### Actual behavior

In `plugins/woocommerce/i18n/states.php` I see only 48 states listed. The missing states appear to be:

State Code | English Name
-- | --
49 | El M'Ghair
50 | El Menia
51 | Ouled Djellal
52 | Bordj Baji Mokhtar
53 | Béni Abbès
54 | Timimoun
55 | Touggourt
56 | Djanet
57 | In Salah
58 | In Guezzam

I also noticed a few other issues:
1. "Bouira" (`DZ-10`) is spelled "Bouïra" on the Wikiedia page.
2. "Tamanghasset" (`DZ-11`) is spelled "Tamanrasset" on the Wikipedia page.
3. "Tipasa" (`DZ-42`) is spelled "Tipaza" on the Wikipedia page.
4. "Naama" (`DZ-45`) is spelled "Naâma" on the Wikipedia page.

### Steps to reproduce

View the state list directly: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/states.php#L446

You can also confirm that one of the missing states doesn't appear in the drop-down during checkout: 
![Screenshot](https://d.pr/i/h1M6uc+.png)
*If you do not see the image, please [click here](https://d.pr/i/h1M6uc).*

### WordPress Environment

State list as of commit [1e67304](https://github.com/woocommerce/woocommerce/commit/1e67304e80737b45ce2274a70f9c9a5e7d34ffe1) on May 9, 2022.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by melek** [comment]
Per @barryhughes WooCommerce practice has been to follow CLDR (current stable version is release 41). That still lists 48 provinces, rather than 58:

https://github.com/unicode-org/cldr/blob/release-41/common/subdivisions/en.xml#L1176-L1224

> I imagine Wikipedia is correct and there are now 58 provinces, but, I still think we should wait until this is reflected in CLDR (which is updated every 6 months iirc) since that is the strategy we have adopted for other similar issues.

This is noted in `states.php`: https://github.com/woocommerce/woocommerce/blob/6.7.0/plugins/woocommerce/i18n/states.php#L7

**Comment by thisissandip** [comment]
7488247-zen

Shared the workaround:

```
add_filter( 'woocommerce_states', 'adding_custom_country_states' );
function adding_custom_country_states( $states ) {
     $country_code = 'DZ'; 
     $new_states = array(
         	 'DZ-49' => __("El M'Ghair", 'woocommerce'),
	    	 'DZ-50' => __("El Menia", 'woocommerce'),
		     'DZ-51' => __("Ouled Djellal", 'woocommerce'),
		     'DZ-52' => __("Bordj Baji Mokhtar", 'woocommerce'),
		     'DZ-53' => __("Béni Abbès", 'woocommerce'),
		     'DZ-54' => __("Timimoun", 'woocommerce'),
		     'DZ-55' => __("Touggourt", 'woocommerce'),
		     'DZ-56' => __("Djanet", 'woocommerce'),
		  	 'DZ-57' => __("In Salah", 'woocommerce'),
		  	 'DZ-58' => __("In Guezzam", 'woocommerce'),
     );
     $states[$country_code] += $new_states;

     return $states;
 }
```

**Comment by senadir** [comment]
@melek shouldn't the numbering for the new Wilayat be like this:

```php
'DZ-49' => __( 'Timimoun', 'woocommerce' ),
'DZ-50' => __( 'Bordj Baji Mokhtar', 'woocommerce' ),
'DZ-51' => __( 'Ouled Djellal', 'woocommerce' ),
'DZ-52' => __( 'Béni Abbès', 'woocommerce' ),
'DZ-53' => __( 'Ain Salah', 'woocommerce' ),
'DZ-54' => __( 'In Guezzam', 'woocommerce' ),
'DZ-55' => __( 'Touggourt', 'woocommerce' ),
'DZ-56' => __( 'Djanet', 'woocommerce' ),
'DZ-57' => __( 'El M\'Ghair', 'woocommerce' ),
'DZ-58' => __( 'El Menia', 'woocommerce' ),
```

**Comment by barryhughes** [comment]
As discussed in the linked PR, our current policy is to adhere to CLDR and (as of the current stable release, R45) that [doesn't yet include the new states](https://github.com/unicode-org/cldr/blob/release-45/common/subdivisions/en.xml#L1174-L1221) you listed. So, I'm going to close this issue, but of course we can revisit once CLDR is updated.
