### ISSUE TITLE
Update context prop of wcadmin_tasklist_click

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33992]
**Description:** the team added a `context ` property to the `wcadmin_tasklist_click` event. The goal of this property is to identify if the user is interacting with the task list on the home screen or in any other screen through the side panel.

The Home value is being localized, which can add some friction to the data analysis. It would be better to have the Home value standardized rather than showing the value obtained through the breadcrumbs as it is.

**Comment by chihsuan** [comment]
> It would be better to have the Home value standardized rather than showing the value obtained through the breadcrumbs as it is.

@pmcpinto I think we can use [`page.navArgs.id`](
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/layout/controller.js#L84-L86) instead. 

- `context: woocommerce-home` when the event is fired on the home screen
- `context:  page/activity-panel`  when the event is fired on the activity-panel

Does that sound good to you?

cc @woocommerce/ghidorah

**Comment by ilyasfoo** [comment]
@chihsuan Great suggestion, I think that'll work!

**Comment by chihsuan** [comment]
@ilyasfoo Nice, thanks for confirming. I'll go ahead with that!
