### ISSUE TITLE
Design issue coming to order admin home page

### ISSUE THREAD

**Issue by aezazs-multidots** [woothemes/woocommerce#34015]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you open the order admin home page, then the circle design is created in the counts like order counts and stock counts, that design counts after 3 digits, and the design of the circle is deteriorating.

![CleanShot 2022-07-21 at 15 43 29@2x](https://user-images.githubusercontent.com/72435501/180190097-f1ac4957-8abd-41cc-86cc-55f68a39fddb.png)

### Expected behavior

![CleanShot 2022-07-21 at 15 53 30@2x](https://user-images.githubusercontent.com/72435501/180191889-301a343e-e94f-4f86-8d09-d90ae8b97695.png)

### Actual behavior

![CleanShot 2022-07-21 at 15 43 29@2x](https://user-images.githubusercontent.com/72435501/180190097-f1ac4957-8abd-41cc-86cc-55f68a39fddb.png)

### Steps to reproduce

1. Activate the WooCommerce plugin by installing it on your site
2. Go to order admin home page
3. Inspect and write down more than 3 digits of order counts

### WordPress Environment

Woocommerce Version: 6.7.0
WordPress version: 6.0.1

PC
Mac OS: Version 12.4
Google Chrome: Version 103.0.5060.114 (Official Build) (arm64)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by aezazs-multidots** [comment]
Hello @ObliviousHarmony 

Can you tell me what the progress status of this ticket is?

Thank you in advance.

**Comment by adrianduffell** [comment]
Hi @aezazs-multidots , I was able to reproduce the issue by modifying the DOM in dev console. We'll schedule it to be completed in an upcoming release.

This looks to be an issue with the [badge component stylesheet setting a fixed width](https://github.com/woocommerce/woocommerce/blob/0859204f25a6864afe18934c1b07eb94526225b7/packages/js/components/src/badge/style.scss#L11).
