### ISSUE TITLE
New product editing experience 0.5

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#34029]
**As a merchant,
I want to easily publish a product
so I can earn money from my store**

---

**Description**
This epic contains all issues related to the 0.5 version of the new product form MVP where the merchant can create a product, add a name and description, assign it to a category, and upload images.

---

**Product info**

> As a merchant,
> I want to name my product and add it to a specific category
> so that my customers can easily find and buy it.

**Pricing**

> As a merchant,
> I want to quickly add a price to my product
> so I can earn money from my store.

> As a merchant,
> I want to run a 5 hr-long flash sale on my best selling product
> so I can take advantage of the extra traffic I’m getting today.

**Images**

> As a merchant,
> I want to upload photographs of my product
> so that my customers can see what they’re buying.

> As a merchant,
> I want to replace the current photos of this product with newer ones I took today
> so that customers can better see the finish and other details.

**Comment by louwie17** [comment]
Closing this, as all these items have been finished.
