### ISSUE TITLE
Asistente de configuración

### ISSUE THREAD

**Issue by Samuel-273** [woothemes/woocommerce#34047]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Al ingresar al asistente de configuración en el punto 1 "Detalles de la tienda" en el campo "País /Región" no está funcionando, no se puede seleccionar ningún país

### Expected behavior

Al escribir la dirección (País /Región) debería agregarse correctamente

### Actual behavior

Al escribir el país / ciudad no se guarda y el casillero se queda en blanco, lo cuál impide seguir con la configuración

### Steps to reproduce

1. Vaya a AJUSTES 2. Seleccione Ayuda 3. Asistente de configuración 4. Ver error

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://relojtower.ga
Site address (URL): https://relojtower.ga
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 20 MB
PHP Time Limit: 60
PHP Max Input Vars: 8000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wpzh_
Tamaño total de la base de datos: 8.96MB
Tamaño de los datos de la base de datos: 8.67MB
Tamaño del índice de la base de datos: 0.29MB
wpzh_woocommerce_sessions: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_order_itemmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_actionscheduler_actions: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpzh_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_actionscheduler_logs: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wpzh_cartflows_ca_cart_abandonment: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_cartflows_ca_email_history: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_cartflows_ca_email_templates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_cartflows_ca_email_templates_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_commentmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_comments: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_options: Datos: 6.05MB + Índice: 0.05MB + Motor MyISAM
wpzh_postmeta: Datos: 0.20MB + Índice: 0.05MB + Motor MyISAM
wpzh_posts: Datos: 2.36MB + Índice: 0.06MB + Motor MyISAM
wpzh_termmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_terms: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_term_relationships: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_term_taxonomy: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_usermeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_users: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_admin_note_actions: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_customer_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_order_product_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_order_stats: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_product_attributes_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_product_download_directories: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_wc_product_meta_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_wc_rate_limits: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpzh_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpzh_wpforms_tasks_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM

### Post Type Counts ###

attachment: 52
custom_css: 3
customize_changeset: 139
nav_menu_item: 8
page: 11
post: 2
product: 12
revision: 143
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Plantillas de inicio: por Brainstorm Force – 3.1.13
Astra Widgets: por Brainstorm Force – 1.2.12
Checkout Plugins - Stripe for WooCommerce: por Checkout Plugins – 1.4.6
Click to Chat: por HoliThemes – 3.10
Ultimate Addons for Gutenberg: por Brainstorm Force – 1.25.6
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.18
WooCommerce: por Automattic – 6.7.0
WP Force SSL: por WebFactory Ltd – 1.65
WPForms Lite: por WPForms – 1.7.5.3

### Inactive Plugins (3) ###

Akismet Anti-Spam: por Automattic – 4.2.4
Hello Dolly: por Matt Mullenweg – 1.7.2
Multipurpose Gutenberg Block: por theDotstore – 1.7.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: PEN (S/)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base de la tienda: #70 - /shop/
Carrito: #71 - /carrito/
Finalizar compra: #72 - /pago/
Mi cuenta: #73 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 3.8.5 (la actualización a la versión 3.9.0 está disponible)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-23 00:22:58 +00:00
Options: ✔
Notes: 40
Onboarding: -

### Action Scheduler ###

Completo: 32
Oldest: 2022-07-20 00:25:54 +0000
Newest: 2022-07-22 13:44:37 +0000

Pendiente: 6
Oldest: 2022-07-23 00:30:58 +0000
Newest: 2022-07-29 13:44:37 +0000

### Status report information ###

Generated at: 2022-07-22 18:23:28 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @Samuel-273,

Você poderia arquivar este relatório em inglês?

(Sorry, Google Translate)
