### ISSUE TITLE
In Twenty Twenty Two theme Shop page and single product page footer tag is missing

### ISSUE THREAD

**Issue by theminaldiwan** [woothemes/woocommerce#34043]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

As I compared with Sample or other page having footer tag but in shop page and single product page footer tag is seems missing.

### Expected behavior

We need to add footer tag for shop and single product page
`<footer class="wp-block-template-part"></footer>`

Need to add tag in single-product.html and archive-product.html file
`
`

### Actual behavior

Here i have added screenshot
![CleanShot 2022-07-22 at 15 04 33](https://user-images.githubusercontent.com/38693713/180411043-56a70ebe-84d0-43b7-85a3-729593ae916f.jpeg)

### Steps to reproduce

1)In Twenty twenty two theme
2)Go to Shop and single-product page
3)Inspect the element then we got missing footer tag

### WordPress Environment

1)Wordpress version - 6.0
2)Woocommerce - Version 6.7.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi, we are unable to reproduce this issue with the latest version of WooCommerce. I see you are using 6.7.0, could you please upgrade and see if it still happens for you?
