### ISSUE TITLE
[Enhancement]: Frequently bought together option

### ISSUE THREAD

**Issue by sanskritkm** [woothemes/woocommerce#34049]
### Describe the solution you'd like

This feature is helpful please kindly add.

https://snipboard.io/Qo0wRl.jpg

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this idea is promising, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
