### ISSUE TITLE
Store Location: Skip Button

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#34063]
## User Story

> As an experienced builder setting up a new store,
> I want to skip the onboarding wizard,
> So I can manually set up the store later.

## Acceptance Criteria

```
Feature: Onboarding Profiler

  Scenario: User views the onboarding wizard
    When the user views any page of the onboarding wizard
    Then a small button labelled "Skip" displays below the form
    And a tooltip button appears next to the skip button

  Scenario: User skips the onboarding wizard
    When a user skips the onboarding wizard
    Then the user is asked to confirm usage tracking
    Then the user is redirected to WooCommerce Home Screen.
 
  Scenario: User has unsaved data
    Given unsaved data exists on the form
    When a user skips the onboarding wizard
    Then the user is prompted with a confirm dialog 
    And the dialog text is "You're about to skip store setup with unsaved changes. Do you want to continue"
    And the dialog buttons are "Cancel" and "Skip setup"
   
   Scenario: User clicks on the tooltip button
    When a user clicks on the tooltip button
    Then a tooltip displays with the text "Manual setup is only recommended for experienced WooCommerce users or developers."
```

## Screenshots

![image](https://user-images.githubusercontent.com/9312929/180934287-68ff836e-505d-4b49-aa40-158979230a1a.png)

**Comment by ilyasfoo** [comment]
@adrianduffell I assume when a user clicks on "skip" while having edited anything in the step, it should also popup a prompt to confirm the skip?

@verofasulo @SamratBiswas1 If we display the "skip" button in all of the steps, I think users can get confused with skipping the particular step, or skipping the entire profiler. Do you think it's fine, or should we think of another wording?

**Comment by adrianduffell** [comment]
> I assume when a user clicks on "skip" while having edited anything in the step, it should also popup a prompt to confirm the skip?

@ilyasfoo That sounds good to me. I don't think we have this on the skip button at the moment, but we do when navigating with the progress bar?

<img width="1284" alt="Screen Shot 2022-07-26 at 2 47 16 pm" src="https://user-images.githubusercontent.com/9312929/180941548-76e0a7c4-8d98-4ac9-801d-502a9f3db57a.png">

**Comment by adrianduffell** [comment]
I've now updated the description with a new scenario for unsaved data. 

@ilyasfoo @verofasulo @SamratBiswas1 What you think?

**Comment by verofasulo** [comment]
Thanks for taking care of this @adrianduffell @ilyasfoo 🙏

I attach this old exploration that I did when I joined to allow users to skip steps - the only mandatory field is Country / Region to locate them. 

https://user-images.githubusercontent.com/98944206/181045790-354f9e17-e3f6-4836-8664-8278e7a61865.mov

So, in this case, the skip button would not be added in the first step but only in the other ones. And I don't think there's the need to add any confirmation modal for the other steps.

What do you think?

**Comment by ilyasfoo** [comment]
> So, in this case, the skip button would not be added in the first step but only in the other ones. And I don't think there's the need to add any confirmation modal for the other steps.

@verofasulo I think the skip button that we wanted was to allow users skipping the remaining setup. @SamratBiswas1 can correct me if I'm wrong?

Personally, I think both serve a similar purpose where users who don't want/not ready to share certain information can move forward to other parts of WooCommerce.

**Comment by verofasulo** [comment]
> I think the skip button that we wanted was to allow users skipping the remaining setup.

@ilyasfoo I misunderstood then. I thought the idea was to implement a Skip button for each step, avoiding the "Skip all" solution that we have now.

**Comment by moon0326** [comment]
@verofasulo @ilyasfoo 

So the issue has been closed with https://github.com/woocommerce/woocommerce/pull/34176, but I have a question 🙏 

The current implementation skips the OBW entirely when a merchant clicks `Skip` button.

I think it might be better if we skip the current step and move to the next step instead.

What do you guys think?

**Comment by ilyasfoo** [comment]
@moon0326 I think it could work either way, but I'm not sure which would a new user prefer. Veronica may have a better input

**Comment by verofasulo** [comment]
> I think it might be better if we skip the current step and move to the next step instead.

Good point. As mentioned in the [comment above](https://github.com/woocommerce/woocommerce/issues/34063#issuecomment-1195630777), I think it doesn't make much sense to skip the OBW entirely. It's a weird pattern and it's not clear at all - I think the best solution would be to allow the user to skip each step individually as shown in the video.

**Comment by moon0326** [comment]
>  I think the best solution would be to allow the user to skip each step individually as shown in the video.

Thank you @ilyasfoo @verofasulo 

@verofasulo I'll create a new issue to make the change. 

Update: Added a new issue https://github.com/woocommerce/woocommerce/issues/34450
