### ISSUE TITLE
Moment.js error when enabling Gutenberg blocks.

### ISSUE THREAD

**Issue by RepoByMe** [woothemes/woocommerce#34101]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When enabling the Gutenberg blocks for WooCommerce products a JS error occurs (many times) in the console. This error causes additional javascript to not function properly.

### Expected behavior

Expect no errors to occur in the console.

### Actual behavior

An error occurs +- 500 times saying `Moment Timezone has no data for WP.`

### Steps to reproduce

1. Clean install WordPress. (Using twentytwentytwo theme)
2. Install WooCommerce
3. Enable Gutenberg blocks with the following snippet.
```php
function activate_gutenberg_product($can_edit, $post_type) {
	if ('product' === $post_type) {
	  $can_edit = true;
	}
  
	return $can_edit;
  }
add_action('use_block_editor_for_post_type', 'activate_gutenberg_product', 10, 2);
```
4. Open developer tools and create new product/edit existing product. Errors should now appear in the console.

![screenshot-wc-errors](https://user-images.githubusercontent.com/5379886/180951344-5fa6ff0a-85d9-4387-b243-f4b0304a2632.png)

### WordPress Environment ###

WordPress address (URL): http://clean.test
Site address (URL): http://clean.test
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.6
PHP Version: 7.4.28
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.82.0
(SecureTransport) OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 4.84MB
Database Data Size: 3.37MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 6
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /winkel/
Cart: woocommerce/woocommerce#7 - /winkelwagen/
Checkout: woocommerce/woocommerce#8 - /afrekenen/
My account: woocommerce/woocommerce#9 - /mijn-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://nl.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-27 07:22:48 +00:00
Options: ✔
Notes: 35
Onboarding: skipped

### Action Scheduler ###

Complete: 2
Oldest: 2022-07-26 07:23:54 +0000
Newest: 2022-07-26 07:23:54 +0000

Pending: 2
Oldest: 2022-07-26 07:40:06 +0000
Newest: 2022-07-27 07:23:54 +0000

### Status report information ###

Generated at: 2022-07-26 07:40:22 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @reynotekoppele,

Since your report relates to our Blocks, I am going to transfer this issue to the appropriate repository for further handling.

**Comment by Aljullu** [comment]
Thanks for opening this issue @reynotekoppele! We are having some issues reproducing it in our dev environments. What might be happening is a race condition when scripts are loaded, and that's why in some environments it's easier to reproduce than others.

We don't currently support the block editor for products, so fixing this is not one of our priorities right now. At the same time, we accept PRs to improve the block editor for products, so feel free to work on it if you want to contribute! :slightly_smiling_face: 

To add some more context, the file that causes the error seems to be this one: https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/date/src/index.ts. I'm not sure how it's enqueued in the product editor, but maybe it's not setting its dependencies properly when it's enqueued?

**Comment by RepoByMe** [comment]
I've been doing some extra debugging and it seems to be an issue specific to NGINX (I use Laravel Valet). Switching to an Apache environment (MAMP) seems to solve the issue, not quite sure what is wrong though I expect it is indeed some kind of race condition.

**Comment by nielslange** [comment]
Hello @reynotekoppele 👋

Based on @Aljullu's comment in https://github.com/woocommerce/woocommerce/issues/34101, I'll move this issue back to the WooCommerce repo, in which you initially created this issue.

**Comment by ObliviousHarmony** [comment]
Hello @reynotekoppele,

We don't currently support the block editor on product pages. You can view a [full list of our supported blocks here](https://woocommerce.com/products/woocommerce-gutenberg-products-block/).
