### ISSUE TITLE
Support `woocommerce/client/admin` Changelog Workflow

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#34111]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Since folks have been using this workflow for changelog generation for a while, we should work to support it still. This shouldn't be a changelog in `plugins/woocommerce-admin` though and should instead just run `changelog` in the `--filter=woocommerce` project.

**Comment by ObliviousHarmony** [comment]
The same is probably needed in the legacy assets!

**Comment by jonathansadowski** [comment]
Based on discussion with @ObliviousHarmony, I'm closing this as not needed, as the current workflow will guide you toward the correct changelogger command if you run this filtered toward WCA.

**Comment by ObliviousHarmony** [comment]
We actually _should_ do this, at least, in that we should validate the changelog entries as part of WooCommerce.

**Comment by ObliviousHarmony** [comment]
One option could be to add the change logger back to WCA and set the changelog directory (I think it's a supported config) to the Core one. Also make sure that the validation for CI checks the correct directory.

**Comment by psealock** [comment]
>We can set the changelog directory in Changelogger’s configs in composer.json

This idea was proposed today. By adding a composer.json entry for changelogger in wc-admin, we can point it to Core's changelog. 

If that works, the second part of this issue will be to update the changelog validation to reflect this change.
