### ISSUE TITLE
Clarify Changelog Git Push Hook

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#34110]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Right now the messaging around what has gone wrong with the changelog is a bit unclear and verbose, especially in tools like VS Code. We should review the error messaging and output and perhaps have a `--debug` or `-v` flag to display more log output, such as to use in CI.

**Comment by jonathansadowski** [comment]
Forgot to mention this in the fix via #34163. Closing via that PR.
