### ISSUE TITLE
Enforce Consistent Dependency Versioning

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#34112]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Right now there are a ton of different versions of the same dependency. Not only does this increase the size of the package, but, it also makes it more likely that strange bugs can appear and bundle sizes can grow unnecessarily. 

Last year we looked at using [`syncpack`](https://www.npmjs.com/package/syncpack) and this may still be a great choice. Renovate might support PNPM and monorepos now, but, there's still probably a benefit to something that synchronizes all of the dependencies to the same constraint. Maybe the two work together? (I know there's a GitHub Action for Syncpack, maybe that does everything?)

This may not be the path we want to take, but, we should decide on something and implement a solution (while also clearly communicating it to all stakeholders!). This will go a long way towards making a lot of things easier.

**Comment by ObliviousHarmony** [comment]
* What happens if a package needs a breaking version of a dependency and we don't want to update the others yet?
* `syncpack` provides a `list-mismatches` command that can help
* `devDependencies` are less harmful to match
* `react` and `react-dom` with a version constraint
* We need to P2 this change and start the discussion about updating

So set up sync pack with these few dev dependencies, add GitHub Action to validation (maybe update?), and start discussion about what updating our dependencies looks like.

**Comment by jonathansadowski** [comment]
After some discussion about this, I'm boiling this down to some high-level steps for this:

- [x] An action that uses the output of `syncpack list-mismatches` to list any version mismatches in submitted PRs
- [x] A top-level `package.json` script that runs `syncpack fix-mismatches`
- [x] A pre-push hook for `list-mismatches`
- [x] P2 change and start discussion about updating

**Comment by jonathansadowski** [comment]
P2 draft: pdV5qK-58-p2

**Comment by ObliviousHarmony** [comment]
Thanks @jonathansadowski, the draft looks good.
