### ISSUE TITLE
Run Release Cherry-Pick Tool In GitHub Action

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#34135]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In the interest of automating more of the release process, we should make the process of cherry-picking pull requests from `trunk` into the `release/X.X` branch automatic. This should run when a pull request has been merged after the code freeze and targets the release. We have a few possible ways we could go about this:

* When the `release: cherry-pick` label is added? We can validate the milestone to find the branch to merge it?
* When a pull request is merged with a milestone targeting an existing release branch? So if they add the milestone before merge, it adds it?

Personally, I like the first option. We can hook into the label modification event and perform the cherry-pick. Another consideration could be that perhaps this workflow is ran manually against a release, that way, all of the cherry-pick pull requests can be performed in a batch?

By "merge", this issue is talking about:

* Create a new branch and cherry-pick the pull request merge commit.
* Create a new pull request targeting `release/X.X` according to the milestone of the PR.
  * Tag the author of the pull request
  * When there's a merge conflict, send a Slack message so that it can be resolved.
  * When the pull request is created, send a Slack message for validation.

Ultimately, the goal is that once a change or fix has been merged into `trunk`, we should be able to easily get it into the release branch. As a reminder, we currently have a tool that can be run locally!

**Comment by psealock** [comment]
>When the release: cherry-pick label is added? We can validate the milestone to find the branch to merge it?

I like this option as well, but it poses a problem because the release lead should be the only person firing off this task. Theres no way to establish permissions per label as far as I can tell. A manual workflow will be better. Other admins can still fire off the workflow, but you'd get less accidental usage.
