### ISSUE TITLE
[COT] order note not saved

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#34148]
When checking out with Checkout block or shortcode, customer notes are not persisted, I didn't find any mention of them in wc_orders or wc_orders_meta tables.

Customer notes are set using `order->set_customer_note` function.

When it works, it look like this
<img width="246" alt="image" src="https://user-images.githubusercontent.com/6165348/182148533-32e3f440-5b97-4dec-baa5-159d036659be.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/6165348/182148558-5901c4d7-07dd-4737-a248-75507c4ac4af.png">

**Comment by vedanshujain** [comment]
Looks like we save customer_note as a post_excerpt, which does not have corresponding field in the order table. So this issue also scopes adding that field in the database and linking the migration.

**Comment by senadir** [comment]
That's a good observation @vedanshujain 
Is there a specific handling for custom fields in COT? Part of upcoming Checkout work is supporting custom fields and I would love to understand how is that handled.
