### ISSUE TITLE
Homescreen should default to two columns after setup tasklist is completed

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#34149]
**Issue Description:**

There was a regression of [this PR](https://github.com/woocommerce/woocommerce-admin/pull/5465) where homescreen layout is set to two_columns after setup tasklist is completed. Regression may have caused by the removal of [this section](https://github.com/woocommerce/woocommerce-admin/pull/5465/files#diff-148b443dac4ecc6e426b7dca0475271e131ff015d751fb90262bd16156695856L215-R220).

User preference should take precedence, if not then it should determine display based on the default.

**Comment by pmcpinto** [comment]
@adrianduffell is it possible to have this fixed and shipped in the upcoming Core release? TY

**Comment by ilyasfoo** [comment]
@pmcpinto I'll put this on priority, it should be simple enough to squeeze in the cycle
