### ISSUE TITLE
[COT] Order list view shows all types of orders, including Draft and trash types.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#34145]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the WooCommerce -> Orders view, when you're viewing "All" orders, you get Draft and Trash orders included as well
<img width="648" alt="image" src="https://user-images.githubusercontent.com/6165348/182132242-f7587d92-e0be-4965-843a-2d97c7c3cf9c.png">

### Expected behavior

Originally, those 2 status (Draft and trash) are excluded from that view.

### Actual behavior

Draft and Trash are included

### Steps to reproduce

Using Checkout block, start the Checkout process but abandon it.
Trash an order.
You will see them both.

### WordPress Environment

WooCommerce COT zip.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
We should also check how this behaves with custom order statuses (and that it's 100% the same).

**Comment by senadir** [comment]
Draft orders are treated as any custom status, they're registered via `wc_order_statuses` and `woocommerce_register_shop_order_post_statuses` so I would assume the behavior would be the same.
