### ISSUE TITLE
Connect backfill to migrations when COT is authoritative and migration is triggered.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#34151]
When COT is authoritative, and there are new orders in the COT table, migration does not pick it as expected and tries to migrate from posts table again (instead of backfilling). This issue scopes fixing this behavior.

**Comment by peterfabian** [comment]
Quick fix commit that @vedanshujain did: https://github.com/woocommerce/woocommerce/commit/88aa6ac1e7652249de6e86e5318e315f2a01f7c9

Needs a proper fix.
