### ISSUE TITLE
Automatically Label Community Issues & Pull Requests

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#34197]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In order to better identify community contributions, we should automatically label issues and pull requests that have not originated from an account in one of Automattic's teams. There are likely some existing GitHub Actions we can utilize. I'm not sure what label would fit best, maybe another `type` label? `type: community contribution`?

**Comment by jonathansadowski** [comment]
I'm reopening this for the time-being as I've disabled the action that does the labeling. The reason I disabled it is that, as it turns out, the default Github action token doesn't have permission to check organization membership. We just need to decide what token we want to use for that, and this'll be unblocked with a simple PR to add that token to the action.

**Comment by jonathansadowski** [comment]
After discussion, I'm closing this as done again. The current workflow checks for public memberships. We can monitor how well that detects community contributions and re-evaluate the token if need be in the future.

**Comment by lsinger** [comment]
@jonathansadowski thanks for your work on this! Can you think of a good way to retroactively label the existing community issues and PRs? As is, the script is only run on issue / PR creation if I understand correctly?

**Comment by jonathansadowski** [comment]
Noting here that this was disabled again, and we're exploring alternatives in 
* https://github.com/woocommerce/woocommerce/issues/34480

@lsinger it should be possible, yes... is that important for mainly open issues and not the large number of closed ones?

**Comment by lsinger** [comment]
> for mainly open issues and not the large number of closed ones

Yes, I'm asking so that we can make the remaining open issues and PRs more discoverable.
