### ISSUE TITLE
Tax not added when using `woocommerce_package_rates`/`WC_Shipping_Rate`

### ISSUE THREAD

**Issue by strarsis** [woothemes/woocommerce#34202]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Tax is not included to the final tax when using the `woocommerce_package_rates` filter and creating a new `WC_Shipping_Rate` there with tax.

### Expected behavior

Shipping cost taxes are added to the final tax.

### Actual behavior

No shipping tax is added to the final tax.

### Steps to reproduce

Add filter `woocommerce_package_rates` that returns a `WC_Shipping_Rate` with taxes.

```
function custom_special_shipping_rates( $rates, $package ) {
    $special_flatrate_price = 2.00;
    $special_flatrate_tax   = 0.00; // no tax on shipping price

    $special_rate = new WC_Shipping_Rate(
        'flat_rate_special',
        __( 'Special flat rate', 'custom-plugin' ),
        strval($special_flatrate_price),
        $special_flatrate_tax,
        'flat_rate'
    );

    // Store package data.
    if ( $package ) {
        $items_in_package = [];
        foreach ( $package[ 'contents' ] as $item ) {
            $product            = $item[ 'data' ];
            $items_in_package[] = $product->get_name() . ' &times; ' . $item[ 'quantity' ];
        }
        $special_rate->add_meta_data( __( 'Items', 'woocommerce' ), implode( ', ', $items_in_package ) );
    }

    $rates = [ $special_rate->id => $special_rate ] + $rates;
    return $rates;
}
add_filter( 'woocommerce_package_rates', 'custom_special_shipping_rates', 100, 2 );
```
### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.example.com/wp
Site address (URL): https://www.example.com
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.21.6
PHP Version: 7.4.30
PHP Post Max Size: 150 MB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.16-MariaDB-1:10.5.16+maria~focal
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 149.14MB
Datenbank-Datengröße: 84.93MB
Datenbank-Indexgröße: 64.21MB
wp_woocommerce_sessions: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_cf_forms: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_cf_form_entries: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cf_form_entry_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cf_form_entry_values: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_cf_pro_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_failures: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_tracking: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_tracking_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lockdowns: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_login_fails: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 4.23MB + Index: 0.23MB + Engine InnoDB
wp_pmxi_files: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Daten: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Daten: 1.39MB + Index: 0.22MB + Engine InnoDB
wp_redirection_404: Daten: 9.52MB + Index: 5.55MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.17MB + Index: 0.05MB + Engine InnoDB
wp_stream: Daten: 0.52MB + Index: 0.84MB + Engine InnoDB
wp_stream_meta: Daten: 1.52MB + Index: 3.45MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfBlockedIPLog: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Daten: 2.30MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Daten: 1.02MB + Index: 1.17MB + Engine InnoDB
wp_wfHoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Daten: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Daten: 0.44MB + Index: 0.14MB + Engine InnoDB
wp_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Daten: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_wfTrafficRates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Daten: 32.52MB + Index: 40.00MB + Engine InnoDB
wp_wsal_occurrences: Daten: 19.53MB + Index: 6.03MB + Engine InnoDB
wp_yoast_indexable: Daten: 0.52MB + Index: 0.36MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 396
condition_group: 7
el_events: 1
nav_menu_item: 6
oembed_cache: 2
page: 22
points_image: 5
popup: 6
popup_theme: 4
product: 273
product_variation: 21
revision: 257
shop_order: 33
shop_order_refund: 1
sidebar: 4
text-blocks: 5
wcps: 1
wcps_layout: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (52) ###

Admin Menu Editor: von Janis Elsts – 1.10.2
Adminimize: von Frank Bültge – 1.11.8
Test: von <...> – 1.0.0
Caldera Forms Admin Label Addon: von <...> – 1.3.0
Caldera Formulare: von Caldera Formulare – 1.9.7
Classic Editor: von WordPress-Mitwirkende – 1.6.2
Content Aware Sidebars: von Joachim Jensen - DEV Institute – 3.18
Crop Thumbnails: von Volkmar Kantor – 1.4.0
Image Hotspot by DevVN: von Le Van Toan – 1.2.2
Disable Blog: von Joshua Nelson – 0.5.0
Disable Comments: von WPDeveloper – 2.4.0
Disable Title: von Frank Staude – 0.9
Dublin Core Title Metatag: von <...> – 1.3.0
Easy Options for WooCommerce: von Jeff Sherk – 1.6.2
Enable Media Replace: von ShortPixel – 3.6.3
Favicon by RealFaviconGenerator: von Philippe Bernard – 1.3.29
Force Regenerate Thumbnails: von Pedro Elsner – 2.0.6
Google Analytics Dashboard for WP (GADWP): von ExactMetrics – 5.3.10
Opt-Out for Google Analytics: von WP-Buddy – 2.3.4
ImageMagick Sharpen Resized Images: von Hans van Eijsden,niwreg – 1.1.7
Login LockDown: von Michael VanDeMar – v1.8.1
Menu Icons: von ThemeIsle – 0.12.12
menu shortcode: von Nirmal Bhagwani – 1.0
Meta Tag Manager: von Marcus Sykes – 3.0.2
PayPal for WooCommerce: von Angell EYE – 3.0.33
PDF Thumbnails: von Stian Liknes – 2.2.0
Popup Maker: von Popup Maker – 1.16.7
Preferred Languages: von Pascal Birchler – 1.8.0
PW WooCommerce Bulk Edit: von Pimwick
LLC – 2.104

Redirection: von John Godley – 5.3.1
Text Blocks: von Hal Gatewood – 1.5.3
Simple Page Ordering: von Jake Goldman
10up – 2.4.1

Stream: von XWP – 3.9.0
SVG dimensions fix: von <...> GbR – 1.1.0
SVG Support: von Benbodhi – 2.4.2
User Role Editor: von Vladimir Garagulya – 4.63
WC Hide Shipping Methods: von Rynaldo Stoltz – 1.5
Variation Swatches for WooCommerce: von Emran Ahmed – 2.0.6
Germanized für WooCommerce: von vendidero – 3.9.8
Booster for WooCommerce: von Pluggabl LLC – 5.6.2
WooCommerce Max Quantity: von Isabel Castillo – 1.5.2
WooCommerce PDF Invoices & Packing Slips: von WP Overnight – 3.0.0
PickPlugins Product Slider for WooCommerce: von PickPlugins – 1.13.36
GoWP WooCommerce Variations Apply All: von GoWP – 1.0.2
WooCommerce: von Automattic – 6.7.0
Yoast SEO: von Team Yoast – 19.4
WP Mail SMTP: von WPForms – 3.5.1
WP-Optimize - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.2.6

WP-Matomo Integration: von André Bräkling – 1.0.27
WP Redis: von Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.2.0

WP Activity Log: von WP White Security – 4.4.2.1
wp-Typography: von Peter Putzer – 5.8.1

### Inactive Plugins (5) ###

Facebook for WooCommerce: von Facebook – 2.6.19
Jetpack: von Automattic – 11.1.2
Pinterest for WooCommerce: von WooCommerce – 1.2.1
WP Product Feed Manager: von Michel Jongbloed – 1.42.0
YITH Request a Quote for WooCommerce: von YITH – 2.12.0

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Must Use Plugins (3) ###

Bedrock Autoloader: von Roots – 1.0.3
Disallow Indexing: von Roots – 1.0.0
Register Theme Directory: von Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /shop/warenkorb/
Kasse: #6 - /shop/kasse/
Mein Konto: #7 - /shop/mein-konto/
Allgemeine Geschäftsbedingungen: #10 - /shop/agbs/

### Theme ###

Name: Test
Version: 1.0.0
Author URL: https://www.example.com
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: test/resources/woocommerce/global/quantity-input.php Version - ist veraltet. Die Hauptversion ist 4.0.0
Outdated Templates: ❌
					
					
						Erfahren Sie
wie Sie aktualisieren können

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-05 15:35:19 +02:00
Options: ✔
Notes: 87
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 220
Oldest: 2022-07-18 17:38:18 +0200
Newest: 2022-08-05 08:50:43 +0200

Ausstehend: 4
Oldest: 2022-08-05 18:00:06 +0200
Newest: 2022-08-06 05:15:05 +0200

### Status report information ###

Generated at: 2022-08-05 09:21:26 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Hi @strarsis - Thanks for reporting. Could you please provide the exact snippet of code you're using on that filter?

**Comment by strarsis** [comment]
@roykho: I tried to create a simple example based on that code:
```php
function custom_special_shipping_rates( $rates, $package ) {
    $special_flatrate_price = 2.00;
    $special_flatrate_tax   = 0.00; // no tax on shipping price

    $special_rate = new WC_Shipping_Rate(
        'flat_rate_special',
        __( 'Special flat rate', 'custom-plugin' ),
        strval($special_flatrate_price),
        $special_flatrate_tax,
        'flat_rate'
    );

    // Store package data.
    if ( $package ) {
        $items_in_package = [];
        foreach ( $package[ 'contents' ] as $item ) {
            $product            = $item[ 'data' ];
            $items_in_package[] = $product->get_name() . ' &times; ' . $item[ 'quantity' ];
        }
        $special_rate->add_meta_data( __( 'Items', 'woocommerce' ), implode( ', ', $items_in_package ) );
    }

    $rates = [ $special_rate->id => $special_rate ] + $rates;
    return $rates;
}
add_filter( 'woocommerce_package_rates', 'custom_special_shipping_rates', 100, 2 );

````

**Comment by barryhughes** [comment]
Thanks for the snippet, @strarsis. 

```php
$special_rate = new WC_Shipping_Rate(
    'flat_rate_special',
    __( 'Special flat rate', 'custom-plugin' ),
    strval($special_flatrate_price),
    array( $special_flatrate_tax ), # <- YOU MUST PASS AN ARRAY
    'flat_rate'
);
```

One thing to note is you must pass an array (see above revision) to specify the tax rate. Also, if you want to apply the taxes you have already defined in your store settings, you could change that line to `WC_Tax::calc_shipping_tax( 2, WC_Tax::get_shipping_tax_rates() )`.

Does that help at all? If not, can you clarify exactly what you expect to see (it wasn't initially clear, since you noted tax was not being applied but were also specifying a tax of `0.00` in your snippet).

Thanks!

**Comment by strarsis** [comment]
@barryhughes: Thanks for your answer! Instead of the filter above I use a class that extends `WC_Shipping_Method` now, and the taxes work out of the box. For that previous filter approach additional tax-specific filters are probably necessary. Using a shipping method class instead bundles these parts together.
