### ISSUE TITLE
Assign pull request reviews to community contributions

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34215]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Community pull requests should be assigned a reviewer Automatically in an effort to foster empowerment amongst community developers. 

After https://github.com/woocommerce/woocommerce/issues/34197 is completed, create a Github action that checks to see if pull requests are community contributions, and if so, assign a reviewing team based on where the code changes lie.

**Comment by psealock** [comment]
I added the blocked status so we wait until the results of the following issues can determine a path forward.

* [Workflow actions and bots: Security Audit](https://github.com/woocommerce/woocommerce/issues/34479)
* [Community Contributions: Investigate new labelling strategy](https://github.com/woocommerce/woocommerce/issues/34480)

**Comment by psealock** [comment]
This is now un-blocked since https://github.com/woocommerce/woocommerce/pull/34971 has been merged.

**Comment by jonathansadowski** [comment]
Reopening for the moment, as the solution I was able to test sans-team reviewers, as it turns out, didn't work with team reviewers. Digging into it.
