### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: string * int

### ISSUE THREAD

**Issue by iamdharmesh** [woothemes/woocommerce#34224]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This bug is a continuation of https://github.com/woocommerce/woocommerce/issues/30168 and https://github.com/woocommerce/woocommerce/issues/33924, both of those bugs are fixed but during testing one PR of https://github.com/woocommerce/woocommerce-min-max-quantities I found that we still have issue in WooCommerce, which is pretty similar to https://github.com/woocommerce/woocommerce/issues/33924 but happening from different place than reported in https://github.com/woocommerce/woocommerce/issues/33924. it only occurs when taxes are disabled on product or store.

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php:2032
```

Stack trace:
```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php:2032
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/templates/checkout/review-order.php(43): WC_Cart->get_product_subtotal()
#1 /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#2 /var/www/html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(2333): wc_get_template()
#3 /var/www/html/wp-includes/class-wp-hook.php(307): woocommerce_order_review()
#4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/html/wp-content/plugins/woocommerce/templates/checkout/form-checkout.php(59): do_action()
#7 /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#8 /var/www/html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(313): wc_get_template()
#9 /var/www/html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(67): WC_Shortcode_Checkout::checkout()
#10 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output()
#11 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper()
#12 /var/www/html/wp-includes/shortcodes.php(356): WC_Shortcodes::checkout()
#13 [internal function]: do_shortcode_tag()
#14 /var/www/html/wp-includes/shortcodes.php(228): preg_replace_callback()
#15 /var/www/html/wp-includes/class-wp-hook.php(307): do_shortcode()
#16 /var/www/html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#17 /var/www/html/wp-includes/post-template.php(253): apply_filters()
#18 /var/www/html/wp-content/themes/storefront/inc/storefront-template-functions.php(352): the_content()
#19 /var/www/html/wp-includes/class-wp-hook.php(307): storefront_page_content()
#20 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#21 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
#22 /var/www/html/wp-content/themes/storefront/content-page.php(18): do_action()
#23 /var/www/html/wp-includes/template.php(772): require('...')
#24 /var/www/html/wp-includes/template.php(716): load_template()
#25 /var/www/html/wp-includes/general-template.php(204): locate_template()
#26 /var/www/html/wp-content/themes/storefront/page.php(24): get_template_part()
#27 /var/www/html/wp-includes/template-loader.php(106): include('...')
#28 /var/www/html/wp-blog-header.php(19): require_once('...')
#29 /var/www/html/index.php(17): require('...')
#30 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 2032
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/10613171/183417560-0c3dd79a-a2a3-4d40-901f-081a71639621.png)

### Expected behavior

It should work fine  without fatal error.

### Actual behavior

Getting fatal error on checkout page when tax is disabled on product/store.

### Steps to reproduce

Follow the same steps as in https://github.com/woocommerce/woocommerce/pull/30493, but with disable taxes on product or store.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wooqa.test
Site address (URL): https://wooqa.test
WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.4
PHP Version: 8.0.12
PHP Post Max Size: 0 B
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB-1:10.3.32+maria~focal
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_
Total Database Size: 5.99MB
Database Data Size: 3.88MB
Database Index Size: 2.11MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.38MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 31
page: 9
polylang_mo: 1
post: 2
product: 42
product_variation: 11
revision: 4
shop_order: 33
shop_subscription: 8
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.9.0-dev

### Inactive Plugins (12) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.5
WooCommerce Blocks: by Automattic – 8.2.1
WooCommerce Currency Converter: by WooCommerce – 1.6.28
WooCommerce Deposits: by WooCommerce – 1.6.0
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.19
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.25
WooCommerce PayFast Gateway: by WooCommerce – 1.4.20 (update to version 1.4.24 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.7.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.49
WooCommerce Stripe Gateway: by WooCommerce – 6.5.1
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WP Crontrol: by John Blackbourn & crontributors – 1.14.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-09 07:16:47 +00:00
Options: ✔
Notes: 47
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2022-08-02 10:45:10 +0000
Newest: 2022-08-02 10:45:10 +0000

Complete: 585
Oldest: 2022-08-02 07:19:45 +0000
Newest: 2022-08-08 12:27:31 +0000

Pending: 9
Oldest: 2022-08-09 04:22:09 +0000
Newest: 2022-09-08 06:40:46 +0000

### Status report information ###

Generated at: 2022-08-08 12:30:29 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for flagging this, @iamdharmesh. If you have time to submit a PR that would be great, otherwise we'll get to it in an upcoming dev cycle :+1:
