### ISSUE TITLE
[COT] Investigate flakiness in migrating orders via Action Scheduler

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#34223]
@ilyasfoo reported flakiness when migrating orders, where just triggering the migration does not actually migrate orders.

An example workflow would be:
1. Have an initial 1 order
2. Enabled COT
3. Wait until initial sync is done
4. Created 10 new orders via smooth generator
5. Set "Use the WooCommerce orders tables" & save
6. Created another new order

The 10 orders created via smooth generated should have, but they didn't. This is intermittent as I was not able to reproduce it. We should investigate why this is happening and fix it.

**Comment by ilyasfoo** [comment]
For additional context, I was testing this in a `wp-env` environment

**Comment by gedex** [comment]
I experienced a condition in which it stuck with following state:

![image](https://user-images.githubusercontent.com/78313/183665628-26a61ad7-2655-4e67-ad05-17e6fbe3f507.png)

I was switching between the authoritative source back-and-forth with some new orders created in-between. One known issue that @vedanshujain told me is verification doesn't ignore `auto-draft` status. 

<details>
<summary>The other two orders from <code>wp wc cot verify_cot_data</code>:</summary>

<pre>
[3574333] => Array
        (
            [0] => Array
                (
                    [column] => ID
                    [original_value] => 3574333
                    [new_value] => 
                )

            [1] => Array
                (
                    [column] => post_status
                    [original_value] => wc-pending
                    [new_value] => 
                )

            [2] => Array
                (
                    [column] => post_date_gmt
                    [original_value] => 2022-08-09 11:40:02
                    [new_value] => 
                )

            [3] => Array
                (
                    [column] => post_modified_gmt
                    [original_value] => 2022-08-09 11:48:14
                    [new_value] => 
                )

            [4] => Array
                (
                    [column] => post_parent
                    [original_value] => 0
                    [new_value] => 
                )

            [5] => Array
                (
                    [column] => post_type
                    [original_value] => shop_order
                    [new_value] => 
                )

            [6] => Array
                (
                    [column] => _order_currency
                    [original_value] => USD
                    [new_value] => 
                )

            [7] => Array
                (
                    [column] => _order_tax
                    [original_value] => 0
                    [new_value] => 
                )

            [8] => Array
                (
                    [column] => _order_total
                    [original_value] => 149
                    [new_value] => 
                )

            [9] => Array
                (
                    [column] => _customer_user
                    [original_value] => 1
                    [new_value] => 
                )

            [10] => Array
                (
                    [column] => _billing_email
                    [original_value] => alpha+adminwoocommercedottest@woocommerce.com
                    [new_value] => 
                )

            [11] => Array
                (
                    [column] => _payment_method
                    [original_value] => 
                    [new_value] => 
                )

            [12] => Array
                (
                    [column] => _payment_method_title
                    [original_value] => 
                    [new_value] => 
                )

            [13] => Array
                (
                    [column] => _customer_ip_address
                    [original_value] => 
                    [new_value] => 
                )

            [14] => Array
                (
                    [column] => _customer_user_agent
                    [original_value] => 
                    [new_value] => 
                )

            [15] => Array
                (
                    [column] => _transaction_id
                    [original_value] => 
                    [new_value] => 
                )

            [16] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _automatewoo_order_created
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [17] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _billing_address_index
                    [orig_meta_values] => Array
                        (
                            [0] => Test Test  768 Vista fort  Fort Wayne WA 40666 US alpha+adminwoocommercedottest@woocommerce.com 
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [18] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _edit_last
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [19] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1660045564:1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [20] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _order_number
                    [orig_meta_values] => Array
                        (
                            [0] => 5101996116
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [21] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _order_number_formatted
                    [orig_meta_values] => Array
                        (
                            [0] => 5101996116
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [22] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _order_number_meta
                    [orig_meta_values] => Array
                        (
                            [0] => a:3:{s:6:"prefix";s:0:"";s:6:"suffix";s:0:"";s:6:"length";s:2:"10";}
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [23] => Array
                (
                    [order_id] => 3574333
                    [meta_key] => _shipping_address_index
                    [orig_meta_values] => Array
                        (
                            [0] => Test Test  132 Hawthorne Street  San Francisco CA 94107 US 
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

        )

    [3574334] => Array
        (
            [0] => Array
                (
                    [column] => ID
                    [original_value] => 3574334
                    [new_value] => 
                )

            [1] => Array
                (
                    [column] => post_status
                    [original_value] => wc-completed
                    [new_value] => 
                )

            [2] => Array
                (
                    [column] => post_date_gmt
                    [original_value] => 2022-08-09 12:19:09
                    [new_value] => 
                )

            [3] => Array
                (
                    [column] => post_modified_gmt
                    [original_value] => 2022-08-09 12:19:37
                    [new_value] => 
                )

            [4] => Array
                (
                    [column] => post_parent
                    [original_value] => 0
                    [new_value] => 
                )

            [5] => Array
                (
                    [column] => post_type
                    [original_value] => shop_order
                    [new_value] => 
                )

            [6] => Array
                (
                    [column] => _order_currency
                    [original_value] => USD
                    [new_value] => 
                )

            [7] => Array
                (
                    [column] => _order_tax
                    [original_value] => 0
                    [new_value] => 
                )

            [8] => Array
                (
                    [column] => _order_total
                    [original_value] => 149
                    [new_value] => 
                )

            [9] => Array
                (
                    [column] => _customer_user
                    [original_value] => 3
                    [new_value] => 
                )

            [10] => Array
                (
                    [column] => _billing_email
                    [original_value] => alpha+customerwoocommercedottest@woocommerce.com
                    [new_value] => 
                )

            [11] => Array
                (
                    [column] => _payment_method
                    [original_value] => woocommerce_payments
                    [new_value] => 
                )

            [12] => Array
                (
                    [column] => _payment_method_title
                    [original_value] => Credit card / debit card
                    [new_value] => 
                )

            [13] => Array
                (
                    [column] => _customer_ip_address
                    [original_value] => 172.27.0.6
                    [new_value] => 
                )

            [14] => Array
                (
                    [column] => _customer_user_agent
                    [original_value] => WordPress/6.0.1; https://woocommerce.test
                    [new_value] => 
                )

            [15] => Array
                (
                    [column] => _transaction_id
                    [original_value] => pi_3LUrPH2EFWHevyzk14ZIsIvA
                    [new_value] => 
                )

            [16] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _automatewoo_order_created
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [17] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _billing_address_index
                    [orig_meta_values] => Array
                        (
                            [0] => John Doe a8c 132 Hawthorne Street  San Francisco CA 94107 US alpha+customerwoocommercedottest@woocommerce.com 
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [18] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _charge_id
                    [orig_meta_values] => Array
                        (
                            [0] => ch_3LUrPH2EFWHevyzk1DNNwm2Q
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [19] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _completed_date
                    [orig_meta_values] => Array
                        (
                            [0] => 2022-08-09 14:19:37
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [20] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _coupons_processed
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [21] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1660050800:1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [22] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _intent_id
                    [orig_meta_values] => Array
                        (
                            [0] => pi_3LUrPH2EFWHevyzk14ZIsIvA
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [23] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _intention_status
                    [orig_meta_values] => Array
                        (
                            [0] => succeeded
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [24] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _is_sales_order
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [25] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _old_payment_method
                    [orig_meta_values] => Array
                        (
                            [0] => woocommerce_payments
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [26] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _old_payment_method_title
                    [orig_meta_values] => Array
                        (
                            [0] => Credit card / debit card
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [27] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _order_number
                    [orig_meta_values] => Array
                        (
                            [0] => 5101996117
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [28] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _order_number_formatted
                    [orig_meta_values] => Array
                        (
                            [0] => 5101996117
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [29] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _order_number_meta
                    [orig_meta_values] => Array
                        (
                            [0] => a:3:{s:6:"prefix";s:0:"";s:6:"suffix";s:0:"";s:6:"length";s:2:"10";}
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [30] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _paid_date
                    [orig_meta_values] => Array
                        (
                            [0] => 2022-08-09 14:19:39
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [31] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _payment_method_id
                    [orig_meta_values] => Array
                        (
                            [0] => pm_1LI8tQ2EFWHevyzkuXafYSU0
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [32] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _payment_tokens
                    [orig_meta_values] => Array
                        (
                            [0] => a:1:{i:0;i:14;}
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [33] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _shipping_address_index
                    [orig_meta_values] => Array
                        (
                            [0] => John Doe a8c 132 Hawthorne Street  San Francisco CA 94107 US 
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [34] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _stripe_customer_id
                    [orig_meta_values] => Array
                        (
                            [0] => cus_M09BXQrOVbEufI
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [35] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _subscription_renewal
                    [orig_meta_values] => Array
                        (
                            [0] => 3574325
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [36] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _wc_wt_tracks_tracked
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [37] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _wccom_locale
                    [orig_meta_values] => Array
                        (
                            [0] => en_US
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [38] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _wcpay_intent_currency
                    [orig_meta_values] => Array
                        (
                            [0] => USD
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [39] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _wcpay_mode
                    [orig_meta_values] => Array
                        (
                            [0] => test
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [40] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => _wcpv_commission_added
                    [orig_meta_values] => Array
                        (
                            [0] => yes
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [41] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => is_vat_exempt
                    [orig_meta_values] => Array
                        (
                            [0] => no
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [42] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => product_keys_processed
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [43] => Array
                (
                    [order_id] => 3574334
                    [meta_key] => taxamo_transaction_key
                    [orig_meta_values] => Array
                        (
                            [0] => TyikAAEdDfgusHykRf8pi8lDAGXY
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

        )

    [3574329] => Array
        (
            [0] => Array
                (
                    [order_id] => 3574329
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1660049784:1
                        )

                    [new_meta_values] => Array
                        (
                            [0] => 1659625653:1
                        )

                )

        )

    [3574330] => Array
        (
            [0] => Array
                (
                    [order_id] => 3574330
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1660041660:1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

        )

    [3574331] => Array
        (
            [0] => Array
                (
                    [order_id] => 3574331
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1660050239:1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

        )
</pre>
</details>

**Comment by jorgeatorres** [comment]
Hey everyone!

I couldn't reproduce this (at least following the initial instructions). We've implemented a ton of improvements to the sync process since this issue was opened, so I think it should be ok to close and we can re-open or add a new issue should a specific problem reappear.

Do let me know if anyone feels otherwise.
