### ISSUE TITLE
Code Analyzer: Add PR links in change descriptions

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34248]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In going through previous final release posts, it appears we used to include relevant PR numbers when highlighting important changes. These weren't included in Code Analyzer's original spec because it was a CLI tool, but since the output is used to automatically generate release posts now, we should include PR numbers in the output.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1922453/183801281-50e0eff2-36ba-4666-9f9d-9473707404f4.png">

This issue has two parts:

- [ ] Enhance Code Analyzer to output PR links
- [ ] Update developer blog post creation tools to output resulting PRs number from Code Analyzer

**Comment by samueljseay** [comment]
This is way more challenging than I thought it would be. Basically you need info from both `git diff / log` and `git blame`. I found some scripts on the internet but none were quite what I was looking for. I also couldn't find a way to do this with the GitHub graphQL API but someone who is more experienced with complex queries might be able to tackle it.

I tried a few first cuts of getting the info but the complexity felt too steep for the value. 

@psealock I wonder if we should deprioritize this, or maybe someone else has a cleverer idea of how we might achieve this.

**Comment by psealock** [comment]
Thanks for looking into this @samueljseay. I think deprioritizing is a good idea.
