### ISSUE TITLE
List of Tracks that should be covered by testing utils

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34257]
**Description:** Here's the [list of key Tracks events](https://docs.google.com/spreadsheets/d/12YlSbrEG2vbNHS5lMBkGnxn-g3QKI61VExwKOm0oM_Q/edit?usp=sharing) to be covered by testing utils. More context here: pcQJnU-B2-p2

**Comment by pmcpinto** [comment]
cc @joshuatf

**Comment by mattsherman** [comment]
@pmcpinto Moving this back to "Priorization", as it isn't ready to start work on.

**Comment by nathanss** [comment]
Closed in favor of #37856 and #37857 .
