### ISSUE TITLE
Cherry pick tool enhancements

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#34262]
We currently have an automated cherry picking tool. While it work as expected, there are edge cases where it will fail. This issue is to track what issues we see happening and address it.

* If the readme.txt has no changelog entries (ref: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/readme.txt ), the step that adds the changelog entry will not add anything because it expects some changelog entries to be there already so it knows where to insert the changelog entry.
* This closely relates to the first issue and perhaps are related and fixing this one will actually fix both. The issue is if the changelog entry `Type` does not already exist in the readme.txt changelog entries, then it will also not add it because it doesn't know where to append that entry.

So I think to fix the issues, we need to add the changelog entry even if there are no existing entries and second, add the changelog entry to the end of the list if the changelog entry `Type` does not already exist.

Here is the cherry pick tools we need to potentially fix:
https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/cherry-pick.yml

**Comment by psealock** [comment]
@roykho Is this issue still valid now without the CLI cherry-picking tool? Can we close it?

**Comment by roykho** [comment]
@psealock - yes this edge case still exists in the automated workflow.

**Comment by roykho** [comment]
After looking at this deeper, it is quite difficult to handle this edge case without a very convoluted solution that is sometimes error prone in itself. I think we can just settle with the fact that if on an edge case, the changelog entry is not added, the cherry picked PR reviewer will need to catch that.
