### ISSUE TITLE
Review Shipping Options Task should be sentence case

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#34270]
The task title needs to be switched to sentence case: "Review shipping options".

At present, title case is used.

## Screenshot 

Existing behavior:

![image](https://user-images.githubusercontent.com/9312929/184041915-058c4280-9c46-4a56-b39d-5d2e507f7fe6.png)

**Comment by chihsuan** [comment]
Good eye! @adrianduffell
