### ISSUE TITLE
Remove the WCPay Subscriptions offer page experiment code

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#34275]
As per this request: pdjTHR-Vi-p2#comment-1841

In https://github.com/woocommerce/woocommerce/pull/32957 we added an admin page to **WooCommerce → Subscriptions** as an experiment to promote WooCommerce Payments to eligible merchants.

This experiment has ended and as such, we need to remove the experiment code from WooCommerce Core.

**Acceptance criteria**
- The code added in https://github.com/woocommerce/woocommerce/pull/32957 is removed.
- The WCPay Subscriptions offer page is no longer available at **WooCommerce → Subscriptions**.

**Comment by Jinksi** [comment]
Labelled this as high priority, since it is being superseded by and conflicts with the work in #34251 which is planned for release in 6.9.0.
