### ISSUE TITLE
Woocommerce checkout page [Country/Region] and [State/County] don't have drop down

### ISSUE THREAD

**Issue by ASJ999** [woothemes/woocommerce#34298]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

From this Wednesday, [Country/Region] and [State/County] don't have drop-down. 

Nothing happens when customers click on them directly, and they can't finish the checkout. The system notification is that "Please enter correct details for this required field".

### Expected behavior

Customer can pay successfully

### Actual behavior

From this Wednesday, [Country/Region] and [State/County] don't have drop-down. 

Nothing happens when customers click on them directly, and they can't finish the checkout. The system notification is that "Please enter correct details for this required field".

### Steps to reproduce

![W-checkout problem2](https://user-images.githubusercontent.com/98144636/184295886-10c22ecf-df57-480d-aabb-c9ca9c71e325.jpg)
![WO-checkout PC](https://user-images.githubusercontent.com/98144636/184295904-67953f5e-cd5a-4d3f-965a-935d047eef85.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.ridepropel.com
Site address (URL): https://www.ridepropel.com
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.30
PHP Post Max Size: 256 MB
PHP Time Limit: 360
PHP Max Input Vars: 8000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.35-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp246_
Total Database Size: 172.86MB
Database Data Size: 166.47MB
Database Index Size: 6.39MB
wp246_woocommerce_sessions: Data: 10.10MB + Index: 0.34MB + Engine MyISAM
wp246_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_order_items: Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wp246_woocommerce_order_itemmeta: Data: 1.55MB + Index: 0.51MB + Engine MyISAM
wp246_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_shipping_zone_locations: Data: 0.35MB + Index: 0.37MB + Engine MyISAM
wp246_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ping_pong_payment_log: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
ping_pong_secondary_payment_log: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_actionscheduler_actions: Data: 0.78MB + Index: 0.29MB + Engine MyISAM
wp246_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_actionscheduler_logs: Data: 0.54MB + Index: 0.41MB + Engine MyISAM
wp246_awb_critical_css: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp246_comments: Data: 0.44MB + Index: 0.13MB + Engine MyISAM
wp246_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_fusion_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_fusion_form_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_fusion_form_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_fusion_form_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_getpaid_invoices: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_getpaid_invoice_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_litespeed_img_optm: Data: 1.10MB + Index: 0.51MB + Engine MyISAM
wp246_litespeed_img_optming: Data: 0.19MB + Index: 0.05MB + Engine MyISAM
wp246_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_mailerlite_checkouts: Data: 0.15MB + Index: 0.00MB + Engine MyISAM
wp246_mailerlite_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_ml_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_options: Data: 11.26MB + Index: 0.27MB + Engine MyISAM
wp246_postmeta: Data: 4.80MB + Index: 1.51MB + Engine MyISAM
wp246_posts: Data: 129.91MB + Index: 0.34MB + Engine MyISAM
wp246_revslider_css: Data: 0.10MB + Index: 0.01MB + Engine MyISAM
wp246_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_sliders: Data: 0.24MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_slides: Data: 1.55MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_static_slides: Data: 0.18MB + Index: 0.00MB + Engine MyISAM
wp246_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_s2w_error_product_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_termmeta: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp246_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp246_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp246_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp246_usermeta: Data: 0.79MB + Index: 0.41MB + Engine MyISAM
wp246_users: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp246_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp246_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp246_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_customer_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp246_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_wc_order_product_lookup: Data: 0.09MB + Index: 0.08MB + Engine MyISAM
wp246_wc_order_stats: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp246_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp246_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wpinv_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp246_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_yoast_indexable: Data: 1.74MB + Index: 0.68MB + Engine MyISAM
wp246_yoast_indexable_hierarchy: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp246_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp246_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp246_yoast_seo_links: Data: 0.16MB + Index: 0.04MB + Engine MyISAM

### Post Type Counts ###

attachment: 785
avada_portfolio: 10
awb_off_canvas: 6
customize_changeset: 3
custom_css: 1
elementor_library: 4
fusion_element: 27
fusion_form: 7
fusion_icons: 2
fusion_tb_layout: 9
fusion_tb_section: 18
fusion_template: 3
nav_menu_item: 47
page: 24
post: 8
product: 98
product_variation: 106
revision: 1286
shop_coupon: 38
shop_order: 468
shop_order_refund: 6
wpcf7_contact_form: 3
wpi_payment_form: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Affiliatly Integration: by Affiliatly.com – 3.0.1
Contact Form 7: by Takayuki Miyoshi – 5.6
Facebook for WooCommerce: by Facebook – 2.6.18
Avada Builder: by ThemeFusion – 3.7.1
Avada Core: by ThemeFusion – 5.7.1
Site Kit by Google: by Google – 1.78.0
LiteSpeed Cache: by LiteSpeed Technologies – 4.6
Slider Revolution Before/After Add-On: by ThemePunch – 3.0.7
Slider Revolution Bubblemorph AddOn: by ThemePunch – 3.0.5
Slider Revolution Mousetrap Add-On: by ThemePunch – 3.0.4
Slider Revolution Particles Effect: by ThemePunch – 3.3.0
Slider Revolution Particle Wave Add-On: by ThemePunch – 1.0.2
Slider Revolution Transitionpack Add-On: by ThemePunch – 1.0.3
Slider Revolution: by ThemePunch – 6.5.25
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.1
MailerLite - WooCommerce integration: by MailerLite – 1.7.4
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.2.1
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.1.0
WooCommerce Affirm Gateway: by WooCommerce – 1.3.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.11
WooCommerce PayPal Payments: by WooCommerce – 1.9.2
pingpongpay: by acq-tech@pingpongx.com – 2.0.0
WooCommerce: by Automattic – 6.6.1 (update to version 6.8.0 is available)
Yoast SEO: by Team Yoast – 19.2
WP Mail SMTP: by WPForms – 3.4.0
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.4.0
LianlianPay for WooCommerce: by LianLian Global – 2.0.14

### Inactive Plugins (2) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.3.3
MailerLite - Signup forms (official): by MailerLite – 1.5.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #6 - /cart/
Checkout: #21478 - /checkout/
My account: #74 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.7.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CN
WooCommerce currency supported: ✔
PayPal card processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-12 13:19:13 +08:00
Options: ✔
Notes: 41
Onboarding: completed

### Action Scheduler ###

Complete: 898
Oldest: 2022-08-12 00:41:46 +0000
Newest: 2022-08-12 06:13:45 +0000

Pending: 5
Oldest: 2022-08-12 14:55:04 +0000
Newest: 2022-08-16 14:52:15 +0000

### Status report information ###

Generated at: 2022-08-12 14:19:31 +08:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hello @ASJ999,

Thanks for the report. I see you have several plugins beside WooCommerce active. Are you able to reproduce this issue with just WooCommerce active?

**Comment by liuhuanjun08** [comment]
I hope you can provide the pingpongpay plugin
