### ISSUE TITLE
Add Pinterest to Onboarding Wizard

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#34302]
## User Story

> As a new merchant, I want to install the Pinterest extension, to grow my store.

## Acceptance Criteria

```
Feature: Onboarding Wizard

  Scenario: User navigates to Free Features
    When the User navigates to Free Features
    Then the Pinterest extension should be listed
    And the description should be `Get your products in front of Pinners searching for ideas and things to buy.`
```

**Comment by adrianduffell** [comment]
Closing, this is no longer required.

**Comment by chihsuan** [comment]
> We'd like to add Pinterest to the OBW before the December 15th deadline to ensure they are included in the WooCommerce 7.3 release.

pbIJXs-31S-p2

**Comment by ilyasfoo** [comment]
Currently waiting for 7.3 to be released for us to merge WCCOM changes, which is slated for 10th Jan.

**Comment by chihsuan** [comment]
Merged and deployed.

https://github.com/Automattic/woocommerce.com/pull/15486
