### ISSUE TITLE
[Enhancement]: Allow images to be loaded in CSS (Webpack)

### ISSUE THREAD

**Issue by ismaeldcom** [woothemes/woocommerce#34306]
### Describe the solution you'd like

While working on a new feature I noticed we're not able to use images in CSS due to [`woocommerce-admin` webpack configuration](https://github.com/woocommerce/woocommerce/blob/5324852223ec30beb70e90fe67262e0d06aad4f6/plugins/woocommerce-admin/webpack.config.js).

We will need to update webpack config to handle images (SVG, PNG, ...) differently. For now, webpack generates a module for each asset, allowing us to import them in JS but not in CSS.

We're using [`asset/inline`](https://webpack.js.org/guides/asset-modules/) in [WCPay](https://github.com/Automattic/woocommerce-payments/blob/2db0e16ddb0d5932888d9f8d7760abd6d2fd4063/webpack.config.js#L95) to replace `url-loader`, and after a quick attempt here seems to work just fine.

### Describe alternatives you've considered

We could keep loading assets in JS, but that will prevent us to use images with CSS backgrounds for example.

**Comment by psealock** [comment]
Is there a performance difference between the two approaches? The image gets bundled, as far as I can tell, so they'd be the same from this standpoint - unless I'm missing something.

Is the desire to reuse the same code from WC Pay?

**Comment by ismaeldcom** [comment]
Well, I think there are plenty of comparisons and debates about those approaches performance. But the main point here is the possibility to use images in CSS.

EG To meet a design I loaded an image as background in CSS. But as it doesn't work, I replaced it with a flex based solution. Although, I think we could have some cases where the best option will be to use backgrounds, because without them, we might end implementing overcomplicated solutions involving absolute positioning and z-index.

**Comment by moon0326** [comment]
I've tested it out and ran a smoke test. Everything worked as expected including `url()` in CSS. 

Pinging @psealock for additional feedback.

What do you think about using `asset/inline` for images?  This is a nice addition and requires just a few lines We still have to run a full test*

**Comment by psealock** [comment]
Would this mean we'd replace our use of `url-loader`?

https://github.com/woocommerce/woocommerce/blob/d191ecc275c8654efbb11409a6f1002c3dacafff/plugins/woocommerce-admin/webpack.config.js#L132

**Comment by rjchow** [comment]
@psealock I've made a PR here with an article linked: https://github.com/woocommerce/woocommerce/pull/34649
