### ISSUE TITLE
woocommerce "Personal data retention" not working

### ISSUE THREAD

**Issue by datenwerkstatt** [woothemes/woocommerce#34338]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the woocommerce settings under Accounts & Privacy there is the area "Personal data retention". These settings are handled by the woocommerce_cleanup_personal_data task. The "$query" parameter in the "trash_orders_query" and "anonymize_orders_query" functions in "/includes/class-wc-privacy.php" is passed as an array. The subsequent result of the "$orders = wc_get_orders( $query )" function is always NULL. If I pass the values of the array as a string, I get a result. The "<" character may be post-processed. Ich bin mir aber nicht sicher.

### Expected behavior

Orders or order data should be deleted or edited according to the settings in the settings.

### Actual behavior

No function

### Steps to reproduce

![grafik](https://user-images.githubusercontent.com/13044952/184853751-a8372c08-ebb1-4600-82ae-d47f5d3a3d1c.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://datenwerkstatt.dev/nocrotec.de
Site address (URL): https://datenwerkstatt.dev/nocrotec.de
WC Version: 6.8.0
REST API Version: ✔ 6.8.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1500
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.0
WC Database Prefix: nct_
Total Database Size: 80.38MB
Database Data Size: 50.48MB
Database Index Size: 29.90MB
nct_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nct_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
nct_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nct_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_actionscheduler_actions: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
nct_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nct_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
nct_borlabs_cookie_consent_log: Data: 2.52MB + Index: 0.52MB + Engine InnoDB
nct_borlabs_cookie_content_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_borlabs_cookie_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_borlabs_cookie_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_borlabs_cookie_script_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_borlabs_cookie_statistics: Data: 0.11MB + Index: 0.19MB + Engine InnoDB
nct_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
nct_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
nct_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_icl_mo_files_domains: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
nct_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_strings: Data: 4.52MB + Index: 8.78MB + Engine InnoDB
nct_icl_string_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_string_pages: Data: 9.52MB + Index: 14.03MB + Engine InnoDB
nct_icl_string_positions: Data: 0.31MB + Index: 0.09MB + Engine InnoDB
nct_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_string_translations: Data: 2.52MB + Index: 1.83MB + Engine InnoDB
nct_icl_string_urls: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
nct_icl_translate: Data: 6.52MB + Index: 0.05MB + Engine InnoDB
nct_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_icl_translations: Data: 0.09MB + Index: 0.25MB + Engine InnoDB
nct_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_icl_translation_status: Data: 4.52MB + Index: 0.02MB + Engine InnoDB
nct_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_options: Data: 2.34MB + Index: 0.17MB + Engine InnoDB
nct_postmeta: Data: 2.52MB + Index: 2.02MB + Engine InnoDB
nct_posts: Data: 13.28MB + Index: 0.22MB + Engine InnoDB
nct_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
nct_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
nct_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nct_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
nct_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_wc_customer_lookup: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
nct_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
nct_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nct_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
nct_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nct_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nct_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_gzd_dhl_labelmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_dhl_labels: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nct_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_gzd_shipmentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_shipments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_shipment_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_shipment_items: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nct_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nct_woocommerce_gzd_shipping_provider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nct_woocommerce_gzd_shipping_providermeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 341
custom_css: 1
nav_menu_item: 12
page: 24
product: 208
revision: 311
shop_order: 40
shop_order_refund: 1
user_request: 1
viwec_template: 14
wafs: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
Advanced Cron Manager: by BracketSpace – 2.4.2
Nocrotec-Custom-Functions: by Holger Heinemann – 1.0
WooCommerce: by Automattic – 6.8.0
WP Crontrol: by John Blackbourn & crontributors – 1.14.0

### Inactive Plugins (23) ###

Borlabs Cookie - Cookie Opt-in: by Borlabs GmbH – 2.2.54
Cart Weight: by Octolize – 1.4.11
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.6.2
Contact Form 7 Multilingual: by OnTheGoSystems – 1.0.2
Country Based Payments for WooCommerce: by Ivan Paulin – 1.4.2
dc SMTP Mail: by datenwerkstatt – 1.0.0
Debug Bar: by wordpressdotorg – 1.1.3
Germanized for WooCommerce: by vendidero – 3.9.8
Maintenance: by WebFactory Ltd – 4.06
Preserved HTML Editor Markup Plus: by Marcus E. Pope
marcuspope
Jason Rosenbaum
J-Ro
Azragh
azragh – 1.5.4

Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.3
Toggle wpautop: by Linchpin & Jonathan Desrosiers – 1.3.0
WooCommerce Grid / List toggle: by jameskoster – 1.2.1
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6
WooCommerce Tabular Country And Weight Shipping: by datenwerkstatt.com – 1.0.1
Woo Email Manager: by Vendidero – 1.0.0
WP Debugging: by Andy Fragen – 2.11.14
WPML Multilingual CMS: by OnTheGoSystems – 4.4.8
WPML String Translation: by OnTheGoSystems – 3.1.6
WPML Translation Management: by OnTheGoSystems – 2.10.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
partnerproduct (partnerproduct)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-en)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5959 - /shop/
Cart: #7 - /warenkorb/
Checkout: #8 - /kasse/
My account: #9 - /mein-konto/
Terms and conditions: #12 - /agb/

### Theme ###

Name: nocrotec
Version: 1.0.0
Author URL: https://www.datenwerkstatt.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: nocrotec/woocommerce/cart/cart-shipping.php
nocrotec/woocommerce/cart/cart-totals.php
nocrotec/woocommerce/cart/proceed-to-checkout-button.php
nocrotec/woocommerce/checkout/form-checkout.php
nocrotec/woocommerce/checkout/review-order.php version 3.8.0 is out of date. The core version is 5.2.0
nocrotec/woocommerce/content-product.php
nocrotec/woocommerce/content-widget-product.php
nocrotec/woocommerce/emails/admin-cancelled-order.php
nocrotec/woocommerce/emails/admin-failed-order.php
nocrotec/woocommerce/emails/admin-new-order.php
nocrotec/woocommerce/emails/customer-completed-order.php
nocrotec/woocommerce/emails/customer-invoice.php
nocrotec/woocommerce/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
nocrotec/woocommerce/emails/customer-note.php
nocrotec/woocommerce/emails/customer-on-hold-order.php
nocrotec/woocommerce/emails/customer-processing-order.php
nocrotec/woocommerce/emails/customer-refunded-order.php
nocrotec/woocommerce/emails/customer-reset-password.php
nocrotec/woocommerce/emails/email-addresses.php version 3.9.0 is out of date. The core version is 5.6.0
nocrotec/woocommerce/emails/email-customer-details.php
nocrotec/woocommerce/emails/email-downloads.php
nocrotec/woocommerce/emails/email-footer.php
nocrotec/woocommerce/emails/email-header.php
nocrotec/woocommerce/emails/email-order-details.php
nocrotec/woocommerce/emails/email-order-items.php
nocrotec/woocommerce/emails/email-styles.php
nocrotec/woocommerce/emails/plain/admin-cancelled-order.php
nocrotec/woocommerce/emails/plain/admin-failed-order.php
nocrotec/woocommerce/emails/plain/admin-new-order.php
nocrotec/woocommerce/emails/plain/customer-completed-order.php
nocrotec/woocommerce/emails/plain/customer-invoice.php
nocrotec/woocommerce/emails/plain/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
nocrotec/woocommerce/emails/plain/customer-note.php
nocrotec/woocommerce/emails/plain/customer-on-hold-order.php
nocrotec/woocommerce/emails/plain/customer-processing-order.php
nocrotec/woocommerce/emails/plain/customer-refunded-order.php
nocrotec/woocommerce/emails/plain/customer-reset-password.php
nocrotec/woocommerce/emails/plain/email-addresses.php version 3.4.0 is out of date. The core version is 5.6.0
nocrotec/woocommerce/emails/plain/email-customer-details.php
nocrotec/woocommerce/emails/plain/email-downloads.php
nocrotec/woocommerce/emails/plain/email-order-details.php
nocrotec/woocommerce/emails/plain/email-order-items.php version 3.7.0 is out of date. The core version is 5.2.0
nocrotec/woocommerce/global/breadcrumb.php
nocrotec/woocommerce/myaccount/form-login.php
nocrotec/woocommerce/order/order-details-customer.php version 3.4.4 is out of date. The core version is 5.6.0
nocrotec/woocommerce/single-product/add-to-cart/external.php
nocrotec/woocommerce/single-product/add-to-cart/grouped.php version 4.0.0 is out of date. The core version is 4.8.0
nocrotec/woocommerce/single-product/add-to-cart/simple.php
nocrotec/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-16 12:43:18 +02:00
Options: ✔
Notes: 16
Onboarding: completed

### Action Scheduler ###

Complete: 94
Oldest: 2022-07-17 15:07:10 +0200
Newest: 2022-08-16 11:16:51 +0200

Pending: 3
Oldest: 2022-08-17 04:00:00 +0200
Newest: 2022-08-17 10:28:34 +0200

### Status report information ###

Generated at: 2022-08-16 11:54:59 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for the report, @datenwerkstatt. So far, we cannot seem to replicate the problem—but it is possible we are misunderstanding.

While your notes about what may be happening within the code are useful, it would be really great if you could provide a set of steps-to-replicate that describe what each user needs to do for the problem to be triggered. Would that be possible?

**Comment by barryhughes** [comment]
If possible, a screenshot of your _"Personal data retention"_ settings (from the Accounts & Privacy screen) could also be useful. Thank you!
