### ISSUE TITLE
Not able to delete single brand using REST API V3

### ISSUE THREAD

**Issue by Abdullah-Iftikhar** [woothemes/woocommerce#34340]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am a LARAVEL developer. I am working on an admin panel for my client to manage the WC store.

  $wc = new Client(
        env('WOOCOMMERCE_STORE_URL'),
        env('WOOCOMMERCE_CONSUMER_KEY'),
        env('WOOCOMMERCE_CONSUMER_SECRET'),
        [
            'wp_api' => true,
            'version' => 'wc/v3',
            'timeout' => 60
        ]
    );
    $wc->delete("products/brand/$brandId", ['force' => true]);

I am using endpoint products/brands/id?force=true     -- For deleting the single brand but this is not working for me.

### Expected behavior

Brand should be deleted through REST API V3.

### Actual behavior

Error: No route was found matching the URL and request method. [rest_no_route]

![image](https://user-images.githubusercontent.com/53434692/184873026-09c8b44b-3763-4b1f-8575-dcea04151838.png)

this brand is available in my WC brands list.

### Steps to reproduce

1 - Integrate ENV variables like consumer keys ETC for the LARAVEL project.
2- access the scope and implements the endpoints.

### WordPress Environment

I am using the LARAVEL stack for the working on WC store through REST API V3. 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Abdullah-Iftikhar,

Thanks for your report. It sounds like you may be reporting an issue with another plugin or an extension to WooCommerce. This repository is for reporting issues that are in the WooCommerce plugin. Please reach out to the developer of the plugin or extension author for any issues you encounter with their plugin or extension.

If I misunderstood and you do believe this is an issue with WooCommerce, please reply with the steps required to reproduce the issue with only the WooCommerce plugin installed. Please also include the System Status Report.

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. Please select "Get system report", then "Copy for support", and then paste it in reply to this thread.
