### ISSUE TITLE
Moment Timezone has no data for WP

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#34342]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the package `@woocommerce/date`(or any package that depends on it) loads when Gutenberg is loaded too, the console shows many times the error:
`Moment Timezone has no data for WP`. 
The problem is [that `moment-timezone` import](https://github.com/woocommerce/woocommerce/blob/3a76aa42555f037a0a565e9f0feaa43f89b197d2/packages/js/date/src/index.ts/#L5-L6) remove WordPress' timezone and causes this issue.

Similar issue https://github.com/woocommerce/woocommerce/issues/34101.

### Steps to reproduce

1. Build [this branch](https://github.com/woocommerce/woocommerce-blocks/tree/moment-timezone-bug-repro) of WooCommerce Blocks.
2. Install and enable it on a WooCommerce website.
3. Add a new post and open the console.
4. You will see a lot of `Moment Timezone has no data for WP` errors.
5. If you remove [this import](https://github.com/woocommerce/woocommerce-blocks/blob/99ac66b819e5252d1ff1b9774fca614cecca3906/assets/js/blocks/products/all-products/edit.js/#L50-L51), no errors will show up.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by davidwebca** [comment]
I'm getting this issue as well, my theme enables the block editor on products.

**Comment by thuautp** [comment]
also reported in 42551310-hc

**Comment by thuautp** [comment]
> also reported in 42551310-hc

The merchant found that this error happens when AutomateWoo is enabled. I can replicate this error on my site with only WooCommerce and AutomateWoo. Disabling AutomateWoo removed the error.

**Comment by gigitux** [comment]
I followed the steps to reproduce it, and I can't anymore! I will close the issue!
