### ISSUE TITLE
[Enhancement]: Get Export Status Through WooCommerce API

### ISSUE THREAD

**Issue by AlexDewey** [woothemes/woocommerce#34398]
### Describe the solution you'd like

I'm trying to get orders with a specific export status. (Either has been exported "✅" or hasn't "-" given as True or False)

### Describe alternatives you've considered

I've considered having to use beautiful soup and collect the information through the website's interface.

**Comment by rrennick** [comment]
@AlexDewey I apologize for the delay in responding. WooCommerce core doesn't maintain an export status for orders. If you are using an extension that does then it would be best to contact the extensions support / developers to request this feature.
