### ISSUE TITLE
WooCommerce breaks (white screen with a bunch of JS errors) when Gutenberg and WP Log Viewer are installed

### ISSUE THREAD

**Issue by zmaglica** [woothemes/woocommerce#34392]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When combination of mentioned plugin (WP Log Viewer, Gutenberg and WooCommerce) are active, the end result is that white screen is shown (on setup wizard too) and a bunch of JavaScript errors are shown in console. A similar issue has been already detected a while ago, and it is no longer causing any issues (https://github.com/WordPress/gutenberg/issues/4397), but when you add WooCommerce to the mix, the similar case is presented.

### Expected behavior

Make sure that website is not broken when combination of mentioned plugins are installed

### Actual behavior

When WooCommerce, WP Log Viewer and Gutenberg are installed, the white screen will be shown with a bunch of JS erros.

### Steps to reproduce

1. Install and activate WP Log Viewer (https://github.com/allbitsnbytes/wp-log-viewer/)
2. Install and activate Gutenberg
3. Install and activate WooCommerce
4. You should be redirected to setup wizard and a white screen should be shown instead of WooCommerce setup wizard.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://silly-bobcat.jurassic.ninja
Site address (URL): https://silly-bobcat.jurassic.ninja
WC Version: 6.8.0
REST API Version: ✔ 6.8.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.0
WC Database Prefix: wp_
Total Database Size: 3.84MB
Database Data Size: 2.40MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.47MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Companion Plugin: by Osk – 1.27
Gutenberg: by Gutenberg Team – 13.9.0
Jetpack: by Automattic – 11.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.6.0
WooCommerce: by Automattic – 6.8.1
WP Log Viewer: by Maxwell Berkel – 1.2.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://silly-bobcat.jurassic.ninja
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-20 13:41:30 +00:00
Options: ✔
Notes: 40
Onboarding: -

### WooCommerce Payments ###

Version: 4.6.0
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 5
Oldest: 2022-08-19 13:43:16 +0000
Newest: 2022-08-19 13:45:16 +0000

Pending: 1
Oldest: 2022-08-20 13:43:16 +0000
Newest: 2022-08-20 13:43:16 +0000

### Status report information ###

Generated at: 2022-08-19 14:22:41 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @zmaglica,

Thanks for the report. Are you able to reproduce this issue at all without any other plugins installed, or does it only happen with WP Log Viewer also installed?

**Comment by zmaglica** [comment]
Hi @jonathansadowski 

This issue occurs only when all three plugins are activated at the same time.

**Comment by swatipawarGS** [comment]
Hi @zmaglica,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.9.0 version and WordPress 6.0.2 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/190108953-35584a74-a567-4c7e-bd5a-58dd87a07c17.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by Aljullu** [comment]
Thanks for opening this issue, @zmaglica! I'm able to reproduce as well.

@rrennick I think this issue would be better handled by Team Mothra. It affects the onboarding flow, analytics, etc. and it's not related to blocks, so I don't think that's something that belongs to Kirigami & Origami. What do you think? Is it ok if I switch the labels?

Related to the issue, I didn't take an in-depth look, but the plugin is likely modifying how JS dependencies are appended and that's making some WooCommerce admin screens not to work.

Having said that, WP Log Viewer hasn't been updated in the past 7 years and it's tested up to WordPress 4.8 (we are currently at 6.4.2). The plugin has some PHP warnings and the version in GitHub doesn't seem to be up-to-date with what's released in WP.org. Based on all of that, I don't think we should spend too much time on this task, it would be impossible for us to guarantee compatibility with all unmaintained plugins out there.

For users, I would recommend either disabling Gutenberg or WP Log Viewer. For developers, I would encourage anybody who wants to investigate this issue to debug and update WP Log Viewer, but unfortunately that's not something we can do on our end.

**Comment by rrennick** [comment]
> I would recommend either disabling Gutenberg or WP Log Viewer.

@Aljullu Thanks for the follow up. If you deactivate WP Log Viewer does it solve the issue?

**Comment by Aljullu** [comment]
> If you deactivate WP Log Viewer does it solve the issue?

Yes, it does for me.

**Comment by mattsherman** [comment]
Closing this is as `status: won't fix` as WP Log Viewer hasn't been updated in many, many years (7+) and doesn't appear maintained anymore. The issue likely lies with that plugin and not WooCommerce.
