### ISSUE TITLE
Release Automation: Create a CLI command to automate bumping versions 

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34424]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Bumping versions for WooCommerce requires several places to be updated. The release lead needs to remember all instances or do a search all to find them.

For example, see this PR https://github.com/woocommerce/woocommerce/pull/34422

- [x] Make a CLI command to update these all at once. https://github.com/woocommerce/woocommerce/pull/34555
- [x] Add Logger to make CLI better and pnpm script and add README https://github.com/woocommerce/woocommerce/pull/34636
- [x] Change Code Analyzer's `getPluginData` to return all data in its raw form so the current version can be determined. https://github.com/woocommerce/woocommerce/pull/34951
- [x] Update any workflows that may be able to take advantage of this tool. For instance, updating `trunk` in the code freeze process and automatically create PR
- [x] Update Release Lead guide section about Code freeze.
- [x] Update Release Lead guide section about Fix releases.

**Comment by jonathansadowski** [comment]
The process for syncing users to the Automattic and WooCommerce orgs is described a bit in p6q6po-cy6-p2. I don't know much about it, but I think that'd be a good starting place for anyone picking up the issue.

**Comment by roykho** [comment]
This issue is closed via https://github.com/woocommerce/woocommerce/pull/35078
