### ISSUE TITLE
PHP warning when using the WooCommerce Navigation feature with coupons disabled

### ISSUE THREAD

**Issue by xristos3490** [woothemes/woocommerce#34433]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the WC navigation featured is enabled, and the coupons are disabled in a store, the system produces a warning:
```
PHP Notice:  Trying to access array offset on value of type null in /Users/chris/Repos/woocommerce/plugins/woocommerce/src/Admin/Features/Navigation/CoreMenu.php on line 235
```

### Expected behavior

Proper handling of the core menu in this case.

It seems that the `/Admin/Features/Navigation/Menu` class is not handling properly the early exit of the various getters (e.g., `get_post_type_items()`, `get_taxonomy_items()` etc. ) see this case for the coupons: https://github.com/woocommerce/woocommerce/blob/9e891cf47b9516573b2f5a7d2ee30a4e75fb19d1/plugins/woocommerce/src/Admin/Features/Navigation/Menu.php#L404

It's expected to return an `array`, but when coupons are disabled in the store the return type is `null`.

### Steps to reproduce

1. Go to "WooCommerce > Settings > General"
2. Uncheck the "Enable the use of coupon codes" option
3. Make sure you have enabled the Navigation feature under "WooCommerce > Settings > Advanced > Features"
4. Navigate to any wp-admin page and see the warning.

### Source

5492942-zn

### WordPress Environment

WooCommerce v6.8.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by neilmccreadie** [comment]
36378521-hc - disabling the new navigation resolved things.

**Comment by AnnaMag** [comment]
We're closing the issue as we aren't actively working on the new navigation.
