### ISSUE TITLE
[Components] Image gallery toolbar

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#34437]
Once https://github.com/woocommerce/woocommerce/pull/34435 is merged, we should add a toolbar to adjust image gallery items.  This toolbar should allow:

* Dragging of the item via a handle
* Updating the order of an item up/down
* Setting the cover for the gallery
* Replacing an image (should open the media modal)
* Removing an item

Some additional props for the `ImageGallery` will be useful:

* `onRemove`
* `onReplace`
* `onOrderChange`

![Image](https://user-images.githubusercontent.com/10561050/186276842-83da011c-b5f0-47c0-ad38-8d38347d134b.png)

**Comment by joelclimbsthings** [comment]
@jarekmorawski A couple quick questions about the cover image behavior:
- I believe it was mentioned that the cover would always be the first item, is that correct?
- So, if an item is set as the cover, it will move to be the first item?
- Also, if the first item (cover) is moved to another position, should it cease to be the cover, and the one in the first position automatically be assigned as the cover?

**Comment by jarekmorawski** [comment]
> I believe it was mentioned that the cover would always be the first item, is that correct?

Yes. If you select an image that is the last item in the row, it'd jump to the first position.

> So, if an item is set as the cover, it will move to be the first item?

Yup!

> Also, if the first item (cover) is moved to another position, should it cease to be the cover, and the one in the first position automatically be assigned as the cover?

Great question. I think that we should hide the < > arrows on the cover item, so that it could not be moved. If the user set a different photo as the cover, the previous one would go to the second position in the top row. What do you think?

https://user-images.githubusercontent.com/79307566/191720204-dec2b465-91df-4eff-8dec-16fafac8a954.mov

**Comment by joelclimbsthings** [comment]
> Great question. I think that we should hide the < > arrows on the cover item, so that it could not be moved. If the user set a different photo as the cover, the previous one would go to the second position in the top row. What do you think?

@jarekmorawski That works! Just to be 🔮 clear, that means that the first item also is not draggable at all, correct? Slightly more complex but shouldn't be a problem.
