### ISSUE TITLE
[Enhancement]: New navigation survey pop up appears repeatedly

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#34440]
### Describe the solution you'd like

Every time we disable the new navigation menu, a survey pop up appears no matter if we've already pressed the No, Thanks button or filled it up.

![image](https://d.pr/i/3016vX+)

It would be good to have this appear only once. 

### Additional context

Originally reported: https://wordpress.org/support/topic/survey-feedback-spam/

**Comment by pmcpinto** [comment]
Thank you for taking the time reporting this bug, we really appreciate your help. I'll close this issue, as the new navigation was disabled a couple of months ago.
