### ISSUE TITLE
sales order does not work well on variable products

### ISSUE THREAD

**Issue by Michaelgimii** [woothemes/woocommerce#34447]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

hi woocommerce team!

I try to display my products based on sale. In simple products everything is fine and displayed correctly. But in variable products, the order of products is displayed completely wrong.
In fact, [this is what](https://prnt.sc/TcT_Ei_Bn2Yd) WooCommerce displays. But this order is displayed correctly only in simple products. Please solve this issue. So that the order of sale in variable products displays the products like the WooCommerce sale list (previous screenshot).
I have shared this with other developers and they confirm it is a bug from WooCommerce.

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

1- Make sure all products are variable.
2- Add multiple orders to display the products in [this list](https://prnt.sc/0ERB_fLEi5Jm).
3- After that, if you apply [this setting](https://prnt.sc/NYemTCbSG6IH), the products will not be displayed in the order of [this list](https://prnt.sc/TcT_Ei_Bn2Yd).

But there is no problem in simple products. Everything is displayed correctly. Please check this item. For an e-commerce website this is very important.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Michaelgimii,

Thanks for the issue. Could you please include information from your [System Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/)? You can get your System Status Report by going to **WooCommerce > Status** from your WordPress Admin, and then click `Get System Report` followed by `Copy for support`. This information is helpful to us in trying to reproduce the issue.

**Comment by Michaelgimii** [comment]
hi @jonathansadowski , Is this problem only on my website? Please note that there are no simple products on my website. All products are variable. But if all products are of simple type, this bug does not exist.

`
### WordPress Environment ###

WordPress address (URL): http://localhost:85/jetengine
Site address (URL): http://localhost:85/jetengine
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
PHP Version: 7.3.2
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.38-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. 403
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 38.29MB
Database Data Size: 33.63MB
Database Index Size: 4.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_apartment_bookings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_apartment_units: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 12.03MB + Index: 1.98MB + Engine InnoDB
wp_posts: Data: 14.02MB + Index: 0.39MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.16MB + Index: 0.22MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 138
customize_changeset: 5
elementor_font: 3
elementor_icons: 1
elementor_library: 26
elementor_snippet: 1
estate: 4
jet-engine: 6
jet-engine-booking: 1
jet-menu: 1
jet-smart-filters: 5
jet-woo-builder: 2
nav_menu_item: 10
nbbfem_template: 1
page: 13
post: 6
product: 4
product_variation: 6
revision: 2282
shop_coupon: 1
shop_order: 4
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Elementor: by Elementor.com – 3.7.2
WooCommerce: by Automattic – 6.3.1 (update to version 6.8.2 is available)

### Inactive Plugins (16) ###

Elementor Pro: by Elementor.com – 3.7.3
JetSearch: by Crocoblock – 3.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page not set
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 2.5.0 (update to version 2.6.1 is available)
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 334
Oldest: 2022-08-11 12:51:57 +0430
Newest: 2022-08-30 02:37:16 +0430


### Status report information ###

Generated at: 2022-08-30 02:39:27 +04:30
`

**Comment by swatipawarGS** [comment]
Hi @Michaelgimii,


Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 6.9.0 version, PHP 8.0.22 version, and WordPress 6.0.2 version. 

Please find below the screencast for reference :


https://user-images.githubusercontent.com/94531721/190105306-b19659ce-29e6-4c23-b3f2-bd9f4322ff5c.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.
