### ISSUE TITLE
[Enhancement]: fix typo in Wiki for COT

### ISSUE THREAD

**Issue by Sidsector9** [woothemes/woocommerce#34441]
### Describe the solution you'd like

Under [Audit for order administration screen functions](https://github.com/woocommerce/woocommerce/wiki/COT-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions), fix the typo in regex from `manage_shop_order_posts_custom_columns` to `manage_shop_order_posts_custom_column`

**Comment by barryhughes** [comment]
Fixed, thank you!
