### ISSUE TITLE
Missing products when using filters

### ISSUE THREAD

**Issue by StephanFlury** [woothemes/woocommerce#34448]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If I use filters (e.g. "sku=123456" in URL) and the result is multiple pages long, some products will not get loaded on any of the requested pages.

For example:
I use the filter "sku=123456,234567,345678,456789,567890,678901,789012,890123,901234,012345,1123456,1223456" and my page size is set with "per_page=10", it could for example happen that the result is as following:
Page 1: skus: 123456, 234567, 345678, 456789, 567890, 678901, 789012, 890123, 901234, 012345
Page 2: skus: 1223456
Missing sku: 1123456

In reality, the bug occured with 160 products and page size 100.
Additionally, it's assured that the url isn't too long (shorter than 2048 characters)

The same error occured when using WooCommerce-Multilingual-Plugin with the filter "lang=all"

When no filters are used, all products get loaded (except for some of the Multilingual-Plugin due to missing "lang=all").

### Expected behavior

All products (with the corresponding sku) get loaded (across multiple pages)

### Actual behavior

See above

### Steps to reproduce

Create about 160 products with an unique sku, use page size 100 and load them according to their skus (at minimum 100)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://ubuntusfl.local
Site address (URL): http://ubuntusfl.local
WC Version: 6.8.0
REST API Version: ✔ 6.8.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.0.21
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 13.25MB
Datenbank-Datengröße: 8.39MB
Datenbank-Indexgröße: 4.86MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 2.52MB + Index: 1.66MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_content_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Daten: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_string_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Daten: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 2.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Daten: 0.45MB + Index: 0.45MB + Engine InnoDB
wp_posts: Daten: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 45
page: 16
post: 1
product: 215
product_variation: 1
revision: 2
shop_order: 9
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

WPML Multilingual CMS: von OnTheGoSystems – 4.5.8
WooCommerce Multilingual & Multi-Currency: von OnTheGoSystems – 5.0.2
WooCommerce: von Automattic – 6.8.0 (Update auf Version 6.8.2 ist verfügbar)
WPML String Translation: von OnTheGoSystems – 3.2.1

### Inactive Plugins (10) ###

Advanced Custom Fields: von Delicious Brains – 5.12.3
Advanced Product Fields for WooCommerce: von StudioWombat – 1.5.1
Akismet Anti-Spam: von Automattic – 4.1.12
Connector for SelectLine ERP: von Gadola Information Systems GmbH – 1.0.0
Customizer Export/Import: von The Beaver Builder Team – 0.9.4
Export Themes: von Sergio Milardovich – 2.12
Hello Dolly: von Matt Mullenweg – 1.7.2
OTGS Installer: von OnTheGoSystems – 3.0.3
WordPress Importer: von wordpressdotorg – 0.7
WordPress REST API Authentication: von miniOrange – 2.4.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /kasse/
Mein Konto: #9 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Gadola storefront Child Theme
Version: 1.1
Author URL: https://www.gadola.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.2 – 4.1.3 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-24 16:44:12 +02:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 5.482
Oldest: 2022-07-25 10:19:35 +0200
Newest: 2022-08-24 14:18:42 +0200

Ausstehend: 1
Oldest: 2022-08-25 10:21:57 +0200
Newest: 2022-08-25 10:21:57 +0200

### Status report information ###

Generated at: 2022-08-24 14:23:55 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Hi @StephanFlury 

Thanks for reporting! Can you please specify in which context do you see this? Would that be in the REST API context? It would be great if you could provide us with a full query string (you can omit the domain part of course) so that we have an easier time reproducing it. 

It would be even better if you could provide us with a db dump of yours, especially if this needs 160 products to be reproduced. You can share it with us e.g. via email by sending it to name-dot-surname-at-automattic-dot-com. 

Thanks!

**Comment by StephanFlury** [comment]
Of course the REST API is meant. Sorry for not specifying it. The URL and HTTP-Verb would be for example:
GET /wp-json/wc/v3/products?sku=123456,234567,345678,456789,567890,678901,789012,890123,901234,012345,1123456,1223456&per_page=100&page=1

Because the error has vanished and has not appeared again, providing a dump wouldn't be that useful, i think. Nevertheless, if you want, i can send it to you via email.

**Comment by barryhughes** [comment]
@StephanFlury it sounds like you can no longer reproduce this issue, is that correct? It certainly sounds like a transient issue so I'm not sure how much more we are going to be able to do to assist, and am therefore closing the issue, but please do let me know if I have misunderstood.

Additionally, if you do experience this again, it would be interesting to know what happens if you repeat the same request but pass the SKUs in a different order.

Thanks!
