### ISSUE TITLE
Fatal error if a coupon is (permanently) deleted after being added to a cart

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#34459]
If a customer adds a coupon to the cart, and the coupon is then **permanently** deleted, the customer will experience a fatal error when accessing the checkout page/when attempting to check out.

```
Fatal error: Uncaught Exception: Invalid coupon.
in /.../plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php on line 118
```

Originally flagged by @nickpagz [(over here)](https://github.com/woocommerce/woocommerce/issues/22052#issuecomment-1226136046).

### Steps to replicate

1. As an admin, create a coupon.
2. As a customer, add some items to your cart and apply the coupon (on the cart page).
3. As the admin, trash then permanently delete the coupon.
4. As the customer, attempt to access the checkout page.
5. Fatal/uncaught exception.

**Comment by ralucaStan** [comment]
I could no longer replicate this bug.

On the checkout shortcode the page loads fine after deleting the already applied coupon.
<img width="711" alt="Screenshot 2023-08-02 at 17 37 11" src="https://github.com/woocommerce/woocommerce/assets/1628454/0311a62e-f309-405b-95fd-fb68e5362af1">

On the Checkout Block we show this message that the code was removed as it does not exist anymore
<img width="703" alt="Screenshot 2023-08-02 at 17 38 39" src="https://github.com/woocommerce/woocommerce/assets/1628454/1b5b7ffa-fe4a-41a5-8326-3c7f50f9e6b3">
