### ISSUE TITLE
[Enhancement]: Dual currency for Croatia as of September 5th

### ISSUE THREAD

**Issue by rynaldos** [woothemes/woocommerce#34463]
### Describe the solution you'd like

As per a recent support request here https://wordpress.org/support/topic/two-currency-both-visible/ Croatia will be using both the Kuna as well as Euro currency as of September. 

I was able to find some information on that at the following link: 

https://www.euronews.com/next/2022/01/18/croatia-to-display-prices-in-both-kuna-and-euro-from-september-5

I am not sure if this is something that needs adjusting in core, to display dual currency for Croatia, or if there are alternative solutions to this. 

Thanks!

### Describe alternatives you've considered

https://woocommerce.com/products/currency-converter-widget/

**Comment by rynaldos** [comment]
As a (dirty) workaround for now, we can use something like the following.


```
function convert_price_cart( $price ){
$convertion_rate = 0.13;
$new_price = $price * $convertion_rate;
return number_format($new_price, 2, '.', '');
}

add_filter( 'wc_price', 'my_custom_price_format', 10, 3 );
function my_custom_price_format( $formatted_price, $price, $args ) {

$price_euro = convert_price_cart($price);
$currency = 'EUR';
$currency_symbol = get_woocommerce_currency_symbol( $currency );
$price_euro = $currency_symbol.$price_euro; // adding currency symbol

$formatted_price_euro = "<span class='price-euro'> ($price_euro)</span>";

return $formatted_price . $formatted_price_euro;
}
```

The conversion rate value needs to be manually set.

**Comment by fab17an** [comment]
Thank you very much rynaldos your answer helped me, I adapted it so that it is in dollars

**Comment by vbelolapotkov** [comment]
Closing it since Euro is official currency in Croatia since January 1st 2023, and dual circulation period expired at midnight on 14 January.

Please reopen if still relevant.
