### ISSUE TITLE
Workflow actions and bots: Security Audit

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34479]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We have several bots and tokens used to access data via read only or write permissions. 

- [ ] Can these be executed via a pull request? 
- [ ] What if the pull request modifies the workflow, can it execute the changed code?
- [ ] If so, can sensitive information be extracted, such as organization details?
- [ ] And also, can arbitrary writes be executed? And to what extent?
- [ ] And the final part of this issue - create a mitigation strategy against any findings

**Comment by samueljseay** [comment]
Please see my recommendations in the draft RFC I made in this issue: https://github.com/woocommerce/platform-private/issues/67

I think we should update the description of this to match the outcome of the RFC.

**Comment by psealock** [comment]
Thanks for the work here @samueljseay. Since this issue is just for an audit, I will close it and mark it as done and create additional issues from the result of the RFC.

**Comment by samueljseay** [comment]
@psealock I've marked the RFC as accepted now. thanks for the reminder.
