### ISSUE TITLE
[Enhancement]: Add partity for woocommerce_applied_coupon hook in order class apply_coupon() method

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#34473]
### Describe the solution you'd like

the cart class' [`apply_coupon()` method has a `do_action( 'woocommerce_applied_coupon', $coupon_code )` hook. ](https://github.com/woocommerce/woocommerce/blob/9db2c452905ebf796a8e8b4d63db64b57e169dbe/plugins/woocommerce/includes/class-wc-cart.php#L1791)

Need a similar hook in the [order class' `apply_coupon()` method](https://github.com/woocommerce/woocommerce/blob/9db2c452905ebf796a8e8b4d63db64b57e169dbe/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L1120) for parity.

### Describe alternatives you've considered

Nothing obvious is jumping out at me. It may be possible to review the order items on save and if a specific coupon type is present... add the product to the order at that time. But I'd need to save some kind of meta value as a flag to prevent it from adding the free gift on every save. 

### Additional context

Specific use case is my Free Gift Coupons plugin which adds a product to the cart when a coupon is applied. It would be nice to work this way in the admin as well.

**Comment by bradmkjr** [comment]
Why didn't we also add the same hook to the remove coupon function?

```
	/**
	 * Remove a coupon from the order and recalculate totals.
	 *
	 * Coupons affect line item totals, but there is no relationship between
	 * coupon and line total, so to remove a coupon we need to work from the
	 * line subtotal (price before discount) and re-apply all coupons in this
	 * order.
	 *
	 * Manual discounts are not affected; those are separate and do not affect
	 * stored line totals.
	 *
	 * @since  3.2.0
	 * @param  string $code Coupon code.
	 * @return void
	 */
	public function remove_coupon( $code ) {
		$coupons = $this->get_items( 'coupon' );


		// Remove the coupon line.
		foreach ( $coupons as $item_id => $coupon ) {
			if ( $coupon->get_code() === $code ) {
				$this->remove_item( $item_id );
				$coupon_object = new WC_Coupon( $code );
				$coupon_object->decrease_usage_count( $this->get_user_id() );
				$this->recalculate_coupons();

				/**
				* Action to signal that a coupon has been removed from an order.
				*
				* @param  WC_Coupon $coupon The removed coupon object.				
				* @param  WC_Order  $order  The current order object.
				*
				* @since 7.?
				*/
				do_action( 'woocommerce_order_removed_coupon', $coupon, $this );
				
				break;
			}
		}
	}
```

I have a situation which I need to update a running tally on a coupon when it's added or removed from an order. Currently there is no way to add hook or filter which knows about the coupon and the order the coupon is being removed from?
