### ISSUE TITLE
Community Contributions: Investigate new labelling strategy

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34480]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

https://github.com/woocommerce/woocommerce/pull/34309 Added a "community contribution" label to PRs submitted to the monorepo by authors outside of the WooCommerce or Automattic organizations.

This turned out to be about 50% accurate because some folks keep their organization details private.

One solution is to create another bot or select an existing one and give it permissions to read org details. While this is possible, it's best to wait for the result of this [workflow token audit](https://github.com/woocommerce/woocommerce/issues/34479) before heading dow this route.

In the meantime, we can investigate a potential alternate solution where we piggy back off the mechanism that syncs automattic org members with WooCommerce org members.

- [ ] See if alternate strategy is pursuable
- [ ] Implement new strategy is possible

**Comment by psealock** [comment]
>The process for syncing users to the Automattic and WooCommerce orgs is described a bit in p6q6po-cy6-p2. I don't know much about it, but I think that'd be a good starting place for anyone picking up the issue.

This comment in https://github.com/woocommerce/woocommerce/issues/34424#issuecomment-1228527476 was supposed to be here

**Comment by samueljseay** [comment]
@jonathansadowski pinging you because I know you worked on this last time.

What do you think about just checking the PR/issue author's permission levels on the repo?

Octokit has:

```
octokit.rest.repos.getCollaboratorPermissionLevel({
  owner,
  repo,
  username,
});
```

which returns `admin, write, read, and none.` as possible values

We could assume anything `read` or lower is an outside collaborator?

It seems a lot simpler than most other approaches I can think of.

**Comment by jonathansadowski** [comment]
> > The process for syncing users to the Automattic and WooCommerce orgs is described a bit in p6q6po-cy6-p2. I don't know much about it, but I think that'd be a good starting place for anyone picking up the issue.
> 
> This comment in [#34424 (comment)](https://github.com/woocommerce/woocommerce/issues/34424#issuecomment-1228527476) was supposed to be here

Oops... thanks for the assist @psealock  😄 

> What do you think about just checking the PR/issue author's permission levels on the repo?

@samueljseay if we can do that with the default action token, then that sounds like a good approach... if it doesn't have access to that method and we'll need an increased level of permission anyways, then I think we should probably explore the other options or use the existing implementation with a special token

**Comment by samueljseay** [comment]
@jonathansadowski pretty sure you can pass the `GITHUB_TOKEN` to the rest API and ours has read/write repo permissions by default so I *think* it should work.
