### ISSUE TITLE
[COT] Sync: handle case when order is missing in COT, but post is not a placeholder

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#34486]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

COT DataSynchronizer doesn't pick up a discrepancy.

### Expected behavior

DataSynchronizer probably needs to cover more discrepancies.

### Actual behavior

Sync not working, COT UI having empty rows, missing data.

### Steps to reproduce

1. Have the COT enabled, but the CPT data store active
2. Create a new order (checkout flow)
3. The order fails to be sync'd to COT for some reason (in my case, no action got scheduled to run the sync, but could be some other failure). I think this would be a problem also in case of e.g. a delay in CRON tasks.
4. At this point I can freely switch between COT and CPT.
5. When COT is active, the sync logic in DataSynchronizer checks for out of sync data using the following query:
```
SELECT(
	(
SELECT COUNT(1) FROM wp_posts posts
INNER JOIN wp_wc_orders orders ON posts.id=orders.id
WHERE posts.post_type = 'shop_order_placehold')
	+
	(SELECT COUNT(1) FROM (
		SELECT orders.id FROM wp_wc_orders orders
		JOIN wp_posts posts on posts.ID = orders.id
		WHERE
		  posts.post_type IN ('shop_order', 'shop_order_refund', 'shop_subscription')
		  AND orders.date_updated_gmt > posts.post_modified_gmt
	) x)
) count
```
6. This returns 0 and everything seems sync'd. 
7. Even if I trigger the sync'ing job, nothing happens, the new order is kept in post, but isn't in the COT table.

### WordPress Environment

Up to date cot-main with a bunch of orders generated by the smooth generator

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Could be solved by https://github.com/woocommerce/woocommerce/pull/34465.

**Comment by jorgeatorres** [comment]
I'm happy to report that this shouldn't be a problem anymore. The count should reflect the correct situation, and we've also added a background sync (https://github.com/woocommerce/woocommerce/pull/39952) that runs frequently to ensure things are ok and schedule a sync if needed (in case we missed some particular sync event).
