### ISSUE TITLE
Core Changelog Writing: Consolidate 3 ways

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34481]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There are currently 3 ways to compile changelogs for WooCommerce core releases - two in JS and one in PHP. We need to consolidate them into one, preferably a TS implementation in our `/tools`.

* https://github.com/woocommerce/woocommerce/blob/trunk/tools/cherry-pick/bin/run.js
* https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/cherry-pick.yml#L1
* Code freeze implementation using Jetpack changelogger / PHP script:
  * https://github.com/woocommerce/woocommerce/blob/f171913c93b93864e8f46231f683b0b00be7cbb6/.github/workflows/release-changelog.yml#L48-L49
  * https://github.com/woocommerce/woocommerce/blob/f171913c93b93864e8f46231f683b0b00be7cbb6/.github/workflows/release-changelog.yml#L61-L62

**Comment by roykho** [comment]
So after some thoughts I am not sure if we need to do anything here. Firstly `https://github.com/woocommerce/woocommerce/blob/trunk/tools/cherry-pick/bin/run.js` was created before we had the workflow automation seen here `https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/cherry-pick.yml`. This automation workflow has worked well so I think we can retire/remove the CLI tool.

Then we have the changelog generation logic in the code freeze workflow. There is a difference in how it is generated compared to the cherry pick one. The code freeze one generates the entire changelog entry while the other one in the cherry pick is very specific as to where to insert the changelog entry.

Yes we probably could still extract it and make it work differently depending on the context but the bulk of how it works is the specific logic as to how to insert the changelog entry. That means we would have very different "insertion" logic living in tools as well which then isn't much different than what we have now.

I am open to further thoughts.

**Comment by psealock** [comment]
>This automation workflow has worked well so I think we can retire/remove the CLI tool.

I agree on this. The CLI tool is a shortcut for something we could do manually in the rare case that we'd want to do it locally. Removal of the code reduces maintenance burden.

>Then we have the changelog generation logic in the code freeze workflow. There is a difference in how it is generated compared to the cherry pick one. The code freeze one generates the entire changelog entry while the other one in the cherry pick is very specific as to where to insert the changelog entry.

This sounds like an Ok situation to leave as is.

@roykho  I think we should remove the CLI tool and close this issue.
