### ISSUE TITLE
Live Branches: Add installation via Beta Tester

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34524]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Once https://github.com/woocommerce/woocommerce/issues/34523 adds builds for every pull request to Jetpack's Beta Download site, the manifest should display all available builds in https://betadownload.jetpack.me/woocommerce-branches.json

- [ ] Add a UI in Beta Tester to select any build from the manifest, which should be all open pull requests
- [ ] Add a button or mechanism for downloading, installing, and activating a selected build of WooCommerce

**Comment by samueljseay** [comment]
As we discussed in team meeting, I've gotten the work so far on this to a stage that I can hand off to someone else and we can subtask the remaining work: https://github.com/woocommerce/woocommerce/pull/35643
