### ISSUE TITLE
Multichannel Marketing Backend MVP: Framework

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#34549]
This issue is part of the epic https://github.com/woocommerce/woocommerce/issues/34548.

As part of the multichannel marketing feature, we will implement a light framework/library in the core that other marketing extensions can use and give us access to their data through a unified method.

## Data definition
Each marketing channel will provide the following data to the core:

**Channel Metadata:**

This data defines each marketing channel and will be used to represent it on the marketing dashboard.

Data name | Data type
-- | --
Name | Text
Description | Text
Logo/Icon | URL
Is the channel set up? | Boolean
Setup/Dashboard URL | URL

**Product Listings:**

This data defines the channel’s product listings’ synchronization status (if applicable).

Data name | Data type
-- | --
Is the product listing synced? | Boolean
Number of product syncing issues | Integer

**Marketing Campaigns:**

The marketing channel will return the list of active marketing campaigns (or the equivalent terminology like ads) with the following properties.

Data name | Data type
-- | --
Campaign title | Text
Cost (including currency) | Text
Manage campaign URL | URL

## How to obtain the data?

Each channel implements an instance of the `MarketingChannelInterface` class in its codebase and then registers itself by calling the `register_marketing_channel` method of the `MarketingChannels` class or using a WordPress filter.

When we need the data, we use the `MarketingChannels` to query the registered channels for their data. The `MarketingChannels` class acts as a repository that holds all registered marketing channels.

Each channel is responsible for compiling its data and returning it in the appropriate format. This means that caching should be handled by each extension separately and not by the MCM core.

Note that even though all extensions may use the classes defined in the core to register themselves as a marketing channel, we ideally would cross-check it with a predefined list of extensions obtained from the WooCommerce.com API to ensure that we only include specific extensions on the multichannel marketing dashboard.

## Implementation

The classes for this feature will be implemented under the `Automattic\WooCommerce\Admin\Marketing` namespace. Three classes need to be implemented here; one is an interface that each marketing channel extension will later implement, one is a value object class representing a marketing campaign, and the last is the central repository class that registers and holds all marketing channels.

### `MarketingChannelInterface`

This interface represents the Marketing Channel in our system. Each marketing channel will implement this interface in their codebase and then register an instance of it by calling our register methods (explained further below). It’s a good idea to ensure that any class implementing this interface is a singleton.

**Methods:**

Method definition | Description
-- | --
`get_name(): string;` | Returns the name of the marketing channel.
`get_description(): string;` | Returns the description of the marketing channel.
`get_icon_url(): string;` | Returns the path to the channel icon.
`get_plugin_slug(): string;` | Returns the unique identifier string for the marketing channel extension, also known as the plugin slug.
`get_setup_status(): string;` | Returns the setup status of the marketing channel. This value should be an Enum and defined as either a set of constants that the marketing channels can use or a value object that we can validate and sanitize.
`get_setup_url(): string;` | Return the URL to the setup page. This URL can be the link to the onboarding page if the extension has not been set up yet, or it can link to the extension’s settings page.
`get_campaigns(): MarketingCampaign[];` | This method will fetch and return all marketing campaigns for the channel.

### `MarketingCampaign`

This class represents a marketing campaign and includes the data necessary to display the campaigns on the MCM dashboard. This class is a value object; therefore, it must be immutable.

**Properties:**

Property Name | Property Type
-- | --
`id` | null\|string
`title` | string
`country` | string
`daily_budget` | string
`manage_url` | string

Each channel must adapt its campaign data to this format and return an array of `MarketingCampaign` objects when requested through the `MarketingChannelInterface::get_campaigns()` method.

### `MarketingChannels`

This class is the repository that holds and returns the registered marketing channels. The primary purpose of this class is to register a marketing channel and return it if requested.

**Methods:**

Method definition | Description
-- | --
`register( MarketingChannelInterface $channel );` | This method will accept a marketing channel object, which is an implementation of `MarketingChannelInterface` and store it in memory. The plugin slug is a good option to use as a unique identifier when registering the channels. This method will also validate each channel using the `is_channel_allowed` method and only register the allowed marketing channels.
`is_channel_allowed( MarketingChannelInterface $channel ): bool;` | This method will check if the given marketing channel is valid and allowed to be included in the multichannel marketing dashboard. It can use a hardcoded list of extension slugs or get the list of permitted marketing channels from the WooCommerce.com API.
`find_by_id( string $channel_id ): MarketingChannelInterface` | This method finds and returns the marketing channel object by using its unique identifier (i.e. its plugin slug).
`find_all(): MarketingChannelInterface[]` | Returns all marketing channels previously registered in memory.

### WordPress filter

A filter will be implemented in the MarketingChannels class to allow marketing channels to register themselves. This filter can be implemented in a shared method that both `find_all` and `find_by_id` methods utilize to get the list of marketing channels.

**Comment by ecgan** [comment]
> ### `MarketingCampaign`

@nima-karimi , in your properties table, you have the `country` and `daily_budget` properties. I believe we want to move away from those properties (which are specific to extensions like Google Listings and Ads) to more generic business metric properties like cost, reach and revenue. More info is in this P2 comment thread: pe2C5g-4k-p2#comment-61.

**Comment by nima-karimi** [comment]
Thanks, Gan. I don't think we can include `sales` and `sessions` in the MVP, but I'll remove the `country` property and rename `budget` to `cost` for now to be more in-line with the new design.

**Comment by nima-karimi** [comment]
Just an update, this is implemented in https://github.com/woocommerce/woocommerce/pull/35099 and merged to the [feature branch](https://github.com/woocommerce/woocommerce/tree/feature/34548-multichannel-marketing-backend) (`feature/34548-multichannel-marketing-backend`) but is still not merged to `trunk`.
