### ISSUE TITLE
`get_price_html` does not display sale price set by `woocommerce_product_get_sale_price` filter

### ISSUE THREAD

**Issue by luboslives** [woothemes/woocommerce#34545]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The recommended way to filter a product sale price dynamically is with `woocommerce_product_get_sale_price`, and the default way of displaying prices in WooCommerce templates is with `echo $product->get_price_html()`.

It appears that `get_price_html` does not grab the product's sale price when it needs to. I've tried different priorites for the filter, no change. Tested with all plugins disabled save WC, using storefront theme and a simple product with no sale price saved in the db.

Here's the code as it is, and my fix below which appears to be working:

```
public function get_price_html( $deprecated = '' ) {
	if ( '' === $this->get_price() ) {
		$price = apply_filters( 'woocommerce_empty_price_html', '', $this );
	} elseif ( $this->is_on_sale() ) {
		$price = wc_format_sale_price( wc_get_price_to_display( $this, array( 'price' => $this->get_regular_price() ) ), wc_get_price_to_display( $this ) ) . $this->get_price_suffix();
	} else {
		$price = wc_price( wc_get_price_to_display( $this ) ) . $this->get_price_suffix();
	}

	return apply_filters( 'woocommerce_get_price_html', $price, $this );
}
```

The fix:

```
public function get_price_html( $deprecated = '' ) {
	if ( '' === $this->get_price() ) {
		$price = apply_filters( 'woocommerce_empty_price_html', '', $this );
	} elseif ( $this->is_on_sale() ) {
		$price = wc_format_sale_price( wc_get_price_to_display( $this, array( 'price' => $this->get_regular_price() ) ), wc_get_price_to_display( $this, array( 'price' => $this->get_sale_price() ) ) ) . $this->get_price_suffix();
	} else {
		$price = wc_price( wc_get_price_to_display( $this ) ) . $this->get_price_suffix();
	}

	return apply_filters( 'woocommerce_get_price_html', $price, $this );
}
```

The sale price needs to be passed as the missing second parameter for `wc_get_price_to_display`, itself being the second parameter inside `wc_format_sale_price`.

### Expected behavior

Display the dynamic sale price next to the crossed out regular price.

### Actual behavior

Displays the regular price next to the crossed out regular price.

### Steps to reproduce

1. create a dynamic sale price filter such as:

```
function cdnrec_apply_discount_sale_price ( $price, $product ) {

	$reg_price = $product->regular_price;

	// check if already on sale, don't apply further discounts
	if ( is_numeric( $price ) || ! is_numeric( $reg_price) ) {
		return $price;
	}
	
	$newprice = $reg_price * 0.5;
	
	return floatval($newprice);
}

add_filter('woocommerce_product_get_sale_price', 'cdnrec_apply_discount_sale_price', 99, 2);
```

2. View a simple product page to see `get_price_html` in action inside the `/single-product/price.php` template.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://cdnrec
Site address (URL): https://cdnrec
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.1.1k PHP/7.4.22 mod_perl/2.0.11 Perl/v5.32.1
PHP Version: 7.4.22
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: wp_
Total Database Size: 303.67MB
Database Data Size: 170.50MB
Database Index Size: 133.17MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 48.58MB + Index: 26.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_comments: Data: 11.52MB + Index: 11.09MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 52.59MB + Index: 56.17MB + Engine InnoDB
wp_posts: Data: 12.52MB + Index: 7.06MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 1.38MB + Index: 0.25MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_tinvwl_analytics: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_tinvwl_items: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_wccs_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wccs_condition_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.22MB + Index: 0.28MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 4.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 0.30MB + Index: 0.19MB + Engine InnoDB
wp_wdp_order_items: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woo_sales_country_region: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 10.52MB + Index: 8.67MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.41MB + Index: 0.58MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.44MB + Index: 0.55MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 4
acf-field: 16
acf-field-group: 4
attachment: 6788
awdp_pt_products: 1
awdp_pt_rules: 1
cdn_label_artist: 7
condition_group: 54
faq: 17
flamingo_contact: 2520
flamingo_inbound: 901
hurrytimer_countdown: 1
ll_slider: 40
nav_menu_item: 17
oembed_cache: 1039
page: 16
post: 87
product: 6368
product_variation: 96
revision: 43
shop_coupon: 67
shop_order: 7070
shop_order_refund: 5
sidebar: 45
vtprd-rule: 8
wafs: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.8.2

### Inactive Plugins (46) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.0.1

Advanced Custom Fields: by Delicious Brains – 5.12.3
Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.1.3
Aelia Foundation Classes for WooCommerce: by Aelia – 2.2.4.220224
Angell EYE Updater: by Angell EYE – 2.0.17
Arconix FAQ: by Tyche Softwares – 1.9.2
Block List Updater: by pluginkollektiv – 1.0.0
CDN Records Label Artists: by luboslives – 1.0.0
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.6.3
Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.18
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.0.3
Flamingo: by Takayuki Miyoshi – 2.3
GDPR Cookie Compliance: by Moove Agency – 4.8.12
Hide SEO Bloat: by SO WP – 3.14.8
HurryTimer: by Nabil Lemsieh – 2.7.2
Inactive User Deleter: by Korol Yuriy aka Shra <to@shra.ru> – 1.57
LiteSpeed Cache: by LiteSpeed Technologies – 5.2
Login No Captcha reCAPTCHA (Google): by Robert Peake and Contributors – 1.7
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.5.2
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.26

PayPal for WooCommerce: by Angell EYE – 3.0.35
Product Sales Report for WooCommerce: by Aspen Grove Studios – 1.5.1
Product Visibility by Country for WooCommerce Pro: by WP Wham – 1.4.7
Query Monitor: by John Blackbourn – 3.9.0
Rank Math SEO: by Rank Math – 1.0.96
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.4.3
Recent Posts Widget With Thumbnails: by Kybernetik Services – 7.1.1
Redirection: by John Godley – 5.3.2
Sales Report By Country for WooCommerce: by zorem – 1.6.5
Simple Store Sliders: by luboslives – 0.10.6
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.2.6
TI WooCommerce Wishlist: by TemplateInvaders – 1.47.0
Transients Manager: by WPBeginner – 2.0.3
Woo Attributes Coupon: by Gaurav Nagpal – 2.2.0
WooCommerce Accounting Report: by BjornTech – 2.1.3
WooCommerce Blacklister: by Aelia – 1.0.5.200727
WooCommerce Brands: by WooCommerce – 1.6.2
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.2.9
WooCommerce Product Bundles: by WooCommerce – 6.14.0
WooCommerce Sort By Stock: by Brandon Yanofsky – 2.2.0
WooCommerce Weight Based Shipping +: by weightbasedshipping.com – 5.3.15
WP Clear File Cache: by Be Seismic – 1.0.0
Yoast SEO: by Team Yoast – 19.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #25025 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/single-product/price.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-09-02 09:17:15 -04:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2022-08-26 14:55:25 -0400
Newest: 2022-08-26 14:55:25 -0400

Complete: 177
Oldest: 2022-08-26 13:41:10 -0400
Newest: 2022-09-01 04:11:49 -0400

Pending: 3
Oldest: 2022-09-01 15:12:02 -0400
Newest: 2022-09-03 03:21:26 -0400

### Status report information ###

Generated at: 2022-09-01 08:13:02 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by luboslives** [comment]
I see now that the price is not being accounted for in the cart or checkout either, so I do I also need to set the final price using `woocommerce_product_get_price` ? I've tried doing so with no luck, let me know if I should give it another stab.

Edit: My mistake, did not mean to close the issue. Bad UI!

**Comment by luiseduardobraschi** [comment]
Neither `woocommerce_product_get_sale_price` or `woocommerce_product_get_regular_price` change the final price.
