### ISSUE TITLE
Warning :  Creating default object from empty value in woocommerce\includes\admin\helper\class-wc-helper-updater.php

### ISSUE THREAD

**Issue by a-ragaee** [woothemes/woocommerce#34542]
https://github.com/woocommerce/woocommerce/blob/5af66c4b1ef70acd4b7bfc4fb0caa27ca10a31fc/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L81

Warning :  Creating default object from empty value in woocommerce\includes\admin\helper\class-wc-helper-updater.php

**Comment by Konamiman** [comment]
Hi @a-ragaee, thanks for your report. Could you please provide some context so we can try to troubleshoot the issue? At the very least we would need reproduction steps, how can we trigger the issue? Thank you!
