### ISSUE TITLE
"Finish setup" icon remains if tasks are disabled without being completed

### ISSUE THREAD

**Issue by jrick1229** [woothemes/woocommerce#34550]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The "Finish setup" icon remains even when the both the **Task List** and **Extended task List** items are set to Disabled.

This was reported in 5521440-zen and was then duplicated on a JN site.

### Expected behavior

If both the **Task List** and **Extended task List** are set to Disabled, the "Finish setup" icon should not be shown (unless there are any other tasks expected to be seen).

### Actual behavior

If there are incomplete tasks in the setup wizard and the tasks are disabled, the "Finish setup" icon is still shown. When clicked, a blank sidebar is shown.

Tasks and Extended tasks Enabled with incomplete tasks:

![setup-11](https://user-images.githubusercontent.com/19918755/187975587-d1572bca-d900-49de-9bca-8e058fa43aa3.png)

Tasks and Extended tasks Disabled with incomplete tasks:

![setup-2](https://user-images.githubusercontent.com/19918755/187975799-b9dcb42e-e656-49fc-947b-e8c158214c96.png)

### Steps to reproduce

1. Create a new install with incomplete setup wizard tasks
2. On an admin settings page, click the "Finish setup" icon to see the unfinished tasks
3. Click the 'Help' dropdown below "Finish setup", then click on 'Setup wizard'
4. Disable both task lists: 
   - ![asdf](https://user-images.githubusercontent.com/19918755/187976665-aa3390d0-a1b5-42e6-8027-9c15ec843620.png)
5. Reload page

You should still see the "Finish setup" icon with no progress wheel. If you click on the "Finish setup" icon, you'll see a blank sidebar that is not dismissable.

### WordPress Environment ###

WordPress address (URL): ---
Site address (URL): ---
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: wp_
Total Database Size: 3.73MB
Database Data Size: 2.29MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.34MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.8.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @jrick1229,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/188075258-be03b9ad-b457-46eb-b7c9-59da93ad634c.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by melek** [comment]
Noting this appears to be the same issue as in this Forum thread: https://wordpress.org/support/topic/woo-commerce-finish-setup/

Crosslinking that thread to this issue.

**Comment by jacoswan** [comment]
Also reported in 5573797-zen. 

Can recreate in WC 6.9.2 and 6.9.3, but "Finish Setup" seems to disappear as expected in 7.0.0-beta.1

**Comment by lsinger** [comment]
I will close this issue as it seems like it was resolved in 7.0. Please feel free to reopen / create a new issue should this still be a problem.

**Comment by JapeNZ** [comment]
Hi there,
I'm not sure if this has come back or if I'm doing something wrong, but the only way for me to remove the "Finish setup" icon is to enable the task list and install one of the 'Recommended marketing extensions' in the 'Get more sales' step.
If I install and then remove the added plugin, the "Finish setup" icon reappears.
Is it possible to add an option to skip this setup stage please?

**Comment by phkoon** [comment]
@lsinger here it keeps showing even after dismissing all the tasks; any workaround to dismiss that god damn "Finish setup"?

**Comment by jjbarreno** [comment]
It seems that the bug has reentered, as currently have version 8.5.0 and I have the same behavior.  The finish button doesn't go away. 

I have completed all the steps, including the installation of Mailchimp for step 5, but it's marked as it hasn't being installed.

**Comment by phkoon** [comment]
Well, I decided to hide it all using css

**Comment by dcx15** [comment]
@lsinger This seems to still be an issue in Woo 8.6.1.

Note to anyone else that stumbles on this issue, I solved it by simply removing the entire top nav with CSS:

```
// Remove top nav section from WC Admin pages
add_action('admin_head', function() {	
	?>
	<style>.woocommerce-layout__header {display: none}</style>
	<?php
});
```

**Comment by dsgolfside** [comment]
this is happening to me stuck at "customize design" i'm not willing to try and choose a new theme as i have no interest in changing themes no matter what i try though i can't get that finish setup button to disappear so i will try hiding it with this css thank you @lsinger

**Comment by bobteree** [comment]
I am having identical problem and repeated multiple times. This issue has NOT gone away. These setup wizards are a mess and overengineered. They need to be able to be fully disabled. My client is confused and I am confused and it makes us look stupid that we can't get rid of the setup wizard! Or actions.

**Comment by bobteree** [comment]
Why is this closed, when the bug persists? How to reopen?

**Comment by OmarFPG** [comment]
8443146-zen

I was able to replicate and confirm:
[Step 1](https://snipboard.io/suaQWv.jpg), [step 2](https://snipboard.io/suaQWv.jpg), and [step 3](https://snipboard.io/mgRZW9.jpg)

@lsinger, could you please take a look at this one? (or tag whoever may be in charge now?). Thanks a lot!

**Comment by lsinger** [comment]
Pinging @barryhughes.

**Comment by barryhughes** [comment]
Thanks, @lsinger 👋🏼 ... re-opening.

**Comment by Aljullu** [comment]
I was able to reproduce this bug today as well, I was going to open a new issue but found this one. In case it helps, here there is a video of the bug:

https://github.com/woocommerce/woocommerce/assets/3616980/4bd27ae0-cd24-4bc9-bf56-66e1ce300961

After hiding all contents of the panel, the _Finish setup_ button persists in the top bar, with no way to remove it.

**Comment by betayazilim** [comment]
I can confirm that this issue still persists.
I can't get rid of finish setup part.

**Comment by freecookbr** [comment]
Hello people, there is any fix about this issue even after years and years of this persistent bug on Woocommerce?
Thanks for all!

**Comment by wpchannel** [comment]
Hi there, just tried on a fresh WooCommerce install today and this issue persists. All my customers websites see this empty panel.

**Comment by JustDecay** [comment]
Three years later, and the issue still persists. It’s not a bug; it’s by design. They’re trying to force us into signing up for their paid services and overpriced garbage themes. The only way to get rid of that awful ‘finish setup’ notification is to jump through every ridiculous hoop WooCommerce wants you to, and then immediately delete or disable everything once you finally get the "confetti" celebrating your submission and compliance. And as a matter of principle, I’ll never touch any of their 'premium' services again. Personally, I despise these tactics software developers use to trick us into paying for things we neither need nor want. They can suck a lemon for all I care. Not only will I never spend a penny on them, but I’ll also happily support any competitor’s plugin or extension just out of spite.

The only reason I’m still using WooCommerce is because I manage several websites and have been a user since 2012. But, my Lord, they’re really testing my patience lately.

**Comment by freecookbr** [comment]
Guys, forget Woocommerce support. This is useless, even after years. To fix this, just hide this annoying false notifications, follow this steps:

1. Install a snippet code plugin.
2. Insert this code below and run only in Admin panel. 
3. That's it!

> add_action('admin_head', 'remove_woo_aside_panel');
> function remove_woo_aside_panel() {
>   echo '<style>
>     aside#woocommerce-activity-panel.woocommerce-layout__activity-panel {
>       display:none!important
>     } 
>   </style>';
> }

Hope this help you all.

**Comment by wpchannel** [comment]
@freecookbr I've reported issues by the past and there were fixed even by Mike Jolley himself, so I'll wait for an answer.

By the way, installing a snippet plugin which are most of the time not secured is not a good solution. Hiding things using CSS is more like a hacky thing than a real fix here. My 2 cents.

**Comment by freecookbr** [comment]
By the way, is just waiting, but this kind of bug is repeatedly happen when new Woocommerce version updates. Good luck to all.

**Comment by joyryde456** [comment]
> Guys, forget Woocommerce support. This is useless, even after years. To fix this, just hide this annoying false notifications, follow this steps:
> 
> 1. Install a snippet code plugin.
> 2. Insert this code below and run only in Admin panel.
> 3. That's it!
> 
> > add_action('admin_head', 'remove_woo_aside_panel');
> > function remove_woo_aside_panel() {
> > echo '<style>
> > aside#woocommerce-activity-panel.woocommerce-layout__activity-panel {
> > display:none!important
> > }
> > </style>';
> > }
> 
> Hope this help you all.

Thank you, but this only hides the buttons on the right, the large white banner (woocommerce-layout__header) still goes across the whole admin screen and blocks usability.

**Comment by datgausaigon** [comment]
Hi, 
This bug still exists in the latest version of WooCommerce (v9.2.2).
Previously I was able to complete the Setup Wizard using these codes. But now it gives me the above error. 
[https://randomadult.com/disable-woocommerce-setup-wizard/](https://randomadult.com/disable-woocommerce-setup-wizard/)
Can you help us fix this? Hiding the button with CSS is not the right way.
Thanks
🐻

**Comment by wlakin** [comment]
> Hi, This bug still exists in the latest version of WooCommerce (v9.2.2). Previously I was able to complete the Setup Wizard using these codes. But now it gives me the above error. https://randomadult.com/disable-woocommerce-setup-wizard/ Can you help us fix this? Hiding the button with CSS is not the right way. Thanks 🐻

Same issue here :(

**Comment by wlakin** [comment]
> Hi, This bug still exists in the latest version of WooCommerce (v9.2.2). Previously I was able to complete the Setup Wizard using these codes. But now it gives me the above error. https://randomadult.com/disable-woocommerce-setup-wizard/ Can you help us fix this? Hiding the button with CSS is not the right way. Thanks 🐻

I had same issue. 

My solution was enable again Task List in Help tab. And "finish" all points.

**Comment by sawinskipio** [comment]
I've created a simple plugin to remove this notification and i've add control to settings. Feel fre to use it :)

[Clean-Badge-2.zip](https://github.com/user-attachments/files/17535625/Clean-Badge-2.zip)

code below

```php
<?php
/**
 * Plugin Name: Clean Badge by PIO
 * Description: A simple plugin to clean up WooCommerce admin header and remove finish setup.
 * Version: 1.2
 * Author: Piotr Sawiński
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Define setting key
define('CLEAN_BADGE_OPTION', 'clean_badge_options');

// Register activation hook to set default options
register_activation_hook(__FILE__, 'clean_badge_activate');
function clean_badge_activate() {
    $options = array(
        'remove_header' => '1',
        'remove_badge' => '1'
    );
    update_option(CLEAN_BADGE_OPTION, $options);
}

// Add Admin Menu
add_action('admin_menu', function() {
    add_options_page(
        'Clean Badge Settings',
        'Clean Badge',
        'manage_options',
        'clean-badge-settings',
        'clean_badge_settings_page'
    );
});

// Render the settings page
function clean_badge_settings_page() {
    if ( ! current_user_can('manage_options') ) {
        return;
    }

    $options = get_option(CLEAN_BADGE_OPTION);
    ?>
    <div class="wrap">
        <h1>Clean Badge Settings</h1>
        <form method="post" action="options.php">
            <?php
            settings_fields(CLEAN_BADGE_OPTION);
            ?>
            <h2>Settings</h2>
            <table class="form-table">
                <tr valign="top">
                    <th scope="row">Remove WooCommerce Header</th>
                    <td>
                        <input type="checkbox" name="clean_badge_options[remove_header]" value="1" <?php checked(1, isset($options['remove_header']) ? $options['remove_header'] : 0); ?>/>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Remove Live Badge</th>
                    <td>
                        <input type="checkbox" name="clean_badge_options[remove_badge]" value="1" <?php checked(1, isset($options['remove_badge']) ? $options['remove_badge'] : 0); ?>/>
                    </td>
                </tr>
            </table>
            <?php submit_button(); ?>
        </form>
    </div>
    <?php
}

// Register settings
add_action('admin_init', function() {
    register_setting(CLEAN_BADGE_OPTION, CLEAN_BADGE_OPTION);
});

// Hook into the 'admin_head' action
add_action('admin_head', function() {
    $options = get_option(CLEAN_BADGE_OPTION);
    if (isset($options['remove_header']) && $options['remove_header'] == '1') {
        echo '<style>.woocommerce-layout__header { display: none; }</style>';
    }
    if (isset($options['remove_badge']) && $options['remove_badge'] == '1') {
        echo '<style>.woocommerce-site-status-badge-live { display: none; }</style>';
    }
}); 
```

**Comment by betayazilim** [comment]
@sawinskipio love the idea.
I am not a programmers but Chatgpt says there are some points to improve.

Summary of Improvements:
Explicit admin check to ensure only admins see the changes.
Sanitization and validation for user inputs for better security.
Modular code structure by organizing code in functions and potentially a class, improving readability and maintainability.

````
<?php
/**
 * Plugin Name: WooCommerce Clean Finish Setup
 * Description: A simple plugin to clean up WooCommerce admin header and remove finish setup.
 * Version: 1.2
 * Author: Piotr Sawiński
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

class CleanBadge {
    const OPTION_KEY = 'clean_badge_options';

    public static function init() {
        register_activation_hook(__FILE__, [self::class, 'activate']);
        add_action('admin_menu', [self::class, 'add_settings_page']);
        add_action('admin_init', [self::class, 'register_settings']);
        add_action('admin_head', [self::class, 'output_styles']);
    }

    public static function activate() {
        update_option(self::OPTION_KEY, [
            'remove_header' => '1',
            'remove_badge' => '1'
        ]);
    }

    public static function add_settings_page() {
        add_options_page(
            'Clean Badge Settings',
            'Clean Badge',
            'manage_options',
            'clean-badge-settings',
            [self::class, 'render_settings_page']
        );
    }

    public static function render_settings_page() {
        if ( ! current_user_can('manage_options') ) {
            return;
        }

        $options = get_option(self::OPTION_KEY);
        ?>
        <div class="wrap">
            <h1>Clean Badge Settings</h1>
            <form method="post" action="options.php">
                <?php
                settings_fields(self::OPTION_KEY);
                ?>
                <table class="form-table">
                    <tr valign="top">
                        <th scope="row">Remove WooCommerce Header</th>
                        <td>
                            <input type="checkbox" name="clean_badge_options[remove_header]" value="1" <?php checked(1, isset($options['remove_header']) ? $options['remove_header'] : 0); ?> />
                        </td>
                    </tr>
                    <tr valign="top">
                        <th scope="row">Remove Live Badge</th>
                        <td>
                            <input type="checkbox" name="clean_badge_options[remove_badge]" value="1" <?php checked(1, isset($options['remove_badge']) ? $options['remove_badge'] : 0); ?> />
                        </td>
                    </tr>
                </table>
                <?php submit_button(); ?>
            </form>
        </div>
        <?php
    }

    public static function register_settings() {
        register_setting(self::OPTION_KEY, self::OPTION_KEY, [
            'sanitize_callback' => [self::class, 'sanitize_options']
        ]);
    }

    public static function output_styles() {
        if ( ! current_user_can('manage_options') ) {
            return;
        }

        $options = get_option(self::OPTION_KEY);
        $styles = '';

        if ( isset($options['remove_header']) && $options['remove_header'] == '1' ) {
            $styles .= '.woocommerce-layout__header { display: none; }';
        }
        if ( isset($options['remove_badge']) && $options['remove_badge'] == '1' ) {
            $styles .= '.woocommerce-site-status-badge-live { display: none; }';
        }

        if ($styles) {
            echo '<style>' . $styles . '</style>';
        }
    }

    public static function sanitize_options($input) {
        $output = [];
        $output['remove_header'] = isset($input['remove_header']) ? '1' : '0';
        $output['remove_badge'] = isset($input['remove_badge']) ? '1' : '0';
        return $output;
    }
}

CleanBadge::init();
