### ISSUE TITLE
failure on new WC_Order ->  empty wc_get_order_types -> Fatal error: Uncaught Exception: Invalid Order

### ISSUE THREAD

**Issue by FacturaOne** [woothemes/woocommerce#34568]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am trying to access the detail of an order via array with:

$order = new WC_Order($order_id);
print_r($order)

i think the problem:   Looking inside the file I see inside line abstract-wc-order-data-store-cpt.php:104:
if ( ! $order->get_id() || ! $post_object || ! in_array( $post_object->post_type, wc_get_order_types(), true ) ) {

wc_get_order_types() is an empty array, and never compare with a “shop_order” 

### Expected behavior

array values from order_id

### Actual behavior

--->> returns the error:
Fatal error: Uncaught Exception: Invalid Order. in /var/www/vhosts/tbai.facturaone.com/httpdocs/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:104

### Steps to reproduce

1. in a function add code:    $order = new WC_Order($order_id);    print_r($order)
2. returns the error    Fatal error: Uncaught Exception: Invalid Order
3. 
 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://tbai.facturaone.com
Site address (URL): https://tbai.facturaone.com/tienda
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB-0+deb10u1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: 6ZAXHcY_
Tamaño total de la base de datos: 13.51MB
Tamaño de los datos de la base de datos: 11.09MB
Tamaño del índice de la base de datos: 2.42MB
6ZAXHcY_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
6ZAXHcY_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_woocommerce_order_itemmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
6ZAXHcY_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_actionscheduler_actions: Datos: 0.08MB + Índice: 0.13MB + Motor InnoDB
6ZAXHcY_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_actionscheduler_logs: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_cartflows_ca_cart_abandonment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_cartflows_ca_email_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
6ZAXHcY_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_options: Datos: 8.14MB + Índice: 0.08MB + Motor InnoDB
6ZAXHcY_postmeta: Datos: 1.20MB + Índice: 0.17MB + Motor InnoDB
6ZAXHcY_posts: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
6ZAXHcY_statistics_exclusions: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_statistics_historical: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
6ZAXHcY_statistics_pages: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
6ZAXHcY_statistics_search: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
6ZAXHcY_statistics_useronline: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_statistics_visit: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_statistics_visitor: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
6ZAXHcY_statistics_visitor_relationships: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
6ZAXHcY_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
6ZAXHcY_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
6ZAXHcY_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
6ZAXHcY_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
6ZAXHcY_yith_wcwl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_yith_wcwl_lists: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_yoast_indexable: Datos: 0.20MB + Índice: 0.16MB + Motor InnoDB
6ZAXHcY_yoast_indexable_hierarchy: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
6ZAXHcY_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
6ZAXHcY_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
6ZAXHcY_yoast_seo_links: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB

### Post Type Counts ###

attachment: 28
cartflows_flow: 2
cartflows_step: 4
customize_changeset: 3
custom_css: 2
elementor_library: 5
nav_menu_item: 14
page: 9
post: 2
product: 1
revision: 17
shop_coupon: 1
shop_order: 25
wpcf7_contact_form: 1
wpforms: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

FiboSearch - AJAX Search for WooCommerce: por Equipo de FiboSearch – 1.19.0
Plantillas de inicio: por Brainstorm Force – 3.1.15
CartFlows: por CartFlows Inc – 1.10.4
Widgets clásicos: por Colaboradores de WordPress – 0.3
Contact Form 7: por Takayuki Miyoshi – 5.6.2
Elementor: por Elementor.com – 3.7.2
Error Log Monitor: por Janis Elsts – 1.7.2
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.18
Variation Swatches for WooCommerce: por Emran Ahmed – 2.0.8
WooCommerce Menu Cart: por WP Overnight – 2.12.0
WooCommerce PDF Invoices & Packing Slips: por WP Overnight – 3.0.1
WooCommerce Product Documents: por SkyVerge – 1.11.2
WooCommerce: por Automattic – 6.8.2
WP TicketBaiFacturas: por  – 0.01
WP Mail SMTP: por WPForms – 3.5.2
WPForms Lite: por WPForms – 1.7.6
YITH WooCommerce Wishlist: por YITH – 3.12.0

### Inactive Plugins (1) ###

GazChap's WooCommerce Auto Category Product Thumbnails: por Gareth 'GazChap' Griffiths – 1.4

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la tienda: #38 - /
Carrito: ❌ La página no contiene el shortcode [woocommerce_cart] o el bloque woocommerce/cart.
Finalizar compra: ❌ La página no contiene el shortcode [woocommerce_checkout] o el bloque woocommerce/checkout.
Mi cuenta: ❌ La página no contiene el shortcode [woocommerce_my_account].
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 3.9.1
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-09-04 17:22:00 +00:00
Options: ✔
Notes: 47
Onboarding: completed

### Action Scheduler ###

Completo: 150
Oldest: 2022-08-19 07:49:28 +0000
Newest: 2022-09-04 16:41:10 +0000

Pendiente: 6
Oldest: 2022-09-05 02:00:56 +0000
Newest: 2022-09-10 02:00:57 +0000

### Status report information ###

Generated at: 2022-09-04 16:49:08 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
I'm sorry, we cannot replicate this. Can you provide more details?

- Do you have other code present that may be filtering the list of order types?
- When is this code running (is it during `init` or some other action)?
- You noted being able to replicate this when other plugins are inactive and a theme like Storefront is active; can you confirm that is the case as we are unable to reproduce at present.

Thanks!

**Comment by FacturaOne** [comment]
> I'm sorry, we cannot replicate this. Can you provide more details?
> 
> * Do you have other code present that may be filtering the list of order types?
> * When is this code running (is it during `init` or some other action)?
> * You noted being able to replicate this when other plugins are inactive and a theme like Storefront is active; can you confirm that is the case as we are unable to reproduce at present.
> 
> Thanks!

hi BarryHughes...... my fault are not runing INIT  :)
thanks for your answer

**Comment by barryhughes** [comment]
No problem, I hope everything is now on track 👍🏽
