### ISSUE TITLE
[Enhancement]: Add woocommerce-notices-wrapper to all notices container

### ISSUE THREAD

**Issue by luizbills** [woothemes/woocommerce#34567]
### Describe the solution you'd like

In checkout page the notices are wrapper in a `div.woocommerce-notices-wrapper` but in other pages is `div.woocommerce`. Maybe a good solution would be an `div.woocommerce-notices-wrapper.woocommerce` everywhere to maintain consistency and not break anything.

**Comment by barryhughes** [comment]
Hi @luizbills, 

Within the checkout page isn't `.woocommerce-notices-wrapper` itself contained within `div.woocommerce`? That is, can't both sets be successfully targeted using rules such as the following (albeit you may need for specificity, depending on what you wish to do):

```css
.woocommerce .woocommerce-message {}
```

Let me know if I'm misunderstanding!

**Comment by luizbills** [comment]
> Within the checkout page isn't .woocommerce-notices-wrapper itself contained within div.woocommerce?

Yes, but it would be interesting to have consistency in this output.

**Comment by barryhughes** [comment]
True, but my hesitation would be unintentional impact on existing customizations. 

For instance, if I understood your proposal correctly, all notices would become targetable via `div.woocommerce-notices-wrapper.woocommerce` and, for that to be true, they could also all be targeted using just `.woocommerce-notices-wrapper` ... the risk being some merchants may already be targeting a specific subset of notices using the second rule, and may not wish to apply those tweaks to all other messages.

That said, it's obviously not such a large risk that we wouldn't ever contemplate it—it's just I'm not sure the potential disruption is worth the reward, given there is already a viable existing means of selecting both (`.woocommerce .woocommerce-message`).

**Comment by luizbills** [comment]
I agree. Maybe more appropriate for a v7.0+ version because of that risk of breaking. Anyway, it's just a suggestion.

**Comment by barryhughes** [comment]
> Maybe more appropriate for a v7.0+ version because of that risk of breaking.

Yes ... I know what you mean in principle, although, for over 18 months now, we have used WordPress versioning for our releases [(see this announcement)](https://developer.woocommerce.com/2021/01/22/developer-advisory-changes-to-woocommerce-versioning-scheme/) and, under this scheme, 7.0 is just the next regularly scheduled version after 6.9, it has no other significance:

> Most importantly, changes to the first number do not signify backwards incompatible changes.

At any rate, thank you for the suggestion. It's definitely worth exploring options like these.
