### ISSUE TITLE
Coupon amount is not deducted after order

### ISSUE THREAD

**Issue by Matze1006** [woothemes/woocommerce#34569]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a voucher is used for an order, the voucher amount is not reduced in the backend after the order. The voucher can thus be used multiple times. The usage is counted up, but the amount remains. 

### Expected behavior

The voucher amount will be reduced after the order. Or set to 0

### Actual behavior

The voucher amount will not be reduced. 

### Steps to reproduce

1. new installation without further settings
2. create product
3. create voucher
4. log out
5. Go to the store.
6. add product to shopping cart
7. pay with voucher
8. check voucher with admin

### WordPress Environment

6.0.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @Matze1006,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/188567120-c7bb2f2e-0523-409a-80d1-2dc5b3bd640e.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by Matze1006** [comment]
Good evening, what else do I need to do here. The case is 1 month old and has not elicited any response.
