### ISSUE TITLE
product average rating and review count is NOT kept up to date

### ISSUE THREAD

**Issue by Lolosan** [woothemes/woocommerce#34565]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

File:
wp-content\plugins\woocommerce\includes\class-wc-comments.php

Line 208:
	public static function clear_transients( $post_id ) {
		if ( 'product' === get_post_type( $post_id ) ) {
			$product = wc_get_product( $post_id );
			$product->set_rating_counts( self::get_rating_counts_for_product( $product ) );
			$product->set_average_rating( self::get_average_rating_for_product( $product ) );
			$product->set_review_count( self::get_review_count_for_product( $product ) );
			$product->save();
		}
	}

Is suposed to clear transients and recount everything as it says "Ensure product average rating and review count is kept up to date."

But function only ensures LAST or OLD values get setted

### Expected behavior

After comment inserted, 
print_r( $product->get_rating_count() );
print_r( $product->get_rating_counts() );
print_r( $product->get_average_rating() );
print_r( $product->get_review_count() );

should echo new counts and average

### Actual behavior

After comment inserted, 
print_r( $product->get_rating_count() );
print_r( $product->get_rating_counts() );
print_r( $product->get_average_rating() );
print_r( $product->get_review_count() );

shows last values

**Altough if:**
After comment inserted, 
WC_Comments::clear_transients( $post_id );
print_r( $product->get_rating_count() );
etc

Shows correct numbers
So i think that 'clear_transients' function hook runs too early

### Steps to reproduce

`$comment_id = wp_new_comment( array(
'comment_post_ID'      => 999,
'comment_type'         => 'review',
'comment_author'       => 'name',
'comment_author_email' => 'mail',
'comment_author_url'   => '',
'user_id'			   => 1,
'comment_content'      => 'awsome product!',
), true );

if( $comment_id )
{
	add_comment_meta( $comment_id, 'rating', 5, true );
	add_comment_meta( $comment_id, 'verified', 1, true );
}
`
$product = wc_get_product(999);
print_r( $product->get_rating_count() );
print_r( $product->get_rating_counts() );
print_r( $product->get_average_rating() );
print_r( $product->get_review_count() );

### WordPress Environment

fresh, no other plugins or themes
WP 6.0.2
WC 6.8.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @Lolosan,

The method you referenced isn't automatically triggered when you use `add_comment_meta()` directly. 

What if, following your calls to set the `'rating'` and `'verified`' fields, you add a call to `wp_update_comment_count_now()` (passing the relevant product ID) ... would that work?

**Comment by Lolosan** [comment]
@barryhughes 

I see. It throwed me off, since the description of that hooked function says "Ensure **product average rating and review count** is kept up to date."

So i figured that function should run on the add rating metadata

I've ended up doing this:

```
remove_action('wp_update_comment_count', 'WC_Comments::clear_transients');
	$id_opinion = wp_new_comment( array(
		'comment_post_ID'      => $product_id,
		'comment_type'         => 'review',
		'comment_author'       => 'author',
		'comment_author_email' => 'mail@mail.com,
		'comment_author_url'   => '',
		'user_id'			   => '100',
		'comment_content'      => 'awsome product,
		), true );
	add_action('wp_update_comment_count', 'WC_Comments::clear_transients');

	if( $id_opinion )
	{
		add_comment_meta( $id_opinion, 'rating', 5, true );
		add_comment_meta( $id_opinion, 'verified', 1, true );
		
//both work 
		//WC_Comments::clear_transients( $post_id );
		wp_update_comment_count_now( $product_id );
}
```

**Comment by barryhughes** [comment]
Glad you found a solution. 

We appreciate that, as things stand, it could be a little confusing—so we created an issue to follow up and hopefully create a pathway that is easier and more obvious [(link)](https://github.com/woocommerce/woocommerce/issues/34640).
