### ISSUE TITLE
Image getting cut off in a marketing slider.

### ISSUE THREAD

**Issue by aezazs-multidots** [woothemes/woocommerce#34580]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The marketing slider in the marketing section on the backend of the site is getting the image cut.

Below I have added a screenshot of the marketing slider.

![CleanShot 2022-09-05 at 16 33 38@2x](https://user-images.githubusercontent.com/72435501/188434601-525fb962-8aae-43be-bbb2-9b435adeced6.png)

### Expected behavior

![CleanShot 2022-09-05 at 16 35 58@2x](https://user-images.githubusercontent.com/72435501/188434920-5e9ae870-7ff3-4f37-a657-6c735a8841a2.png)

### Actual behavior

![CleanShot 2022-09-05 at 16 33 38@2x](https://user-images.githubusercontent.com/72435501/188434556-880f6ee9-d89e-452b-b561-1ecabc317b82.png)

### Steps to reproduce

1. Go to the backend of the site
2. After that go to marketing page
3. Then you will see that the image is getting cut in the marketing slider.

### WordPress Environment

WooCommerce Version: 6.8.2
WordPress version: 6.0.2

PC
Mac OS: Version 12.4
Google Chrome: Version 103.0.5060.114 (Official Build) (arm64)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @aezazs-multidots,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2 version. 

Please find below the screenshot for reference :
![#34580](https://user-images.githubusercontent.com/94531721/188562138-ae05297e-7976-41e9-95bb-45e2c978b78a.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.
