### ISSUE TITLE
Edit Product Permalink in Windows malformed URL

### ISSUE THREAD

**Issue by pekka-28** [woothemes/woocommerce#34598]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After installing WooCommerce and entering the WooCommerce Products|Edit Product page, I noticed that the Permalink provide for the part was not as expected. While the shown link "https://www.domain.com/index.php//product/design-review/" contains two adjacent slash '/' characters it is odd. The underlying address is "https://www.domain.com/?post_type=product&p=...".

The WordPress Permalinks are set to Post name https://www.domain.com/index.php/sample-post/. The server is running IIS 10 and does not hide the processing PHP page.

### Expected behavior

A valid URL is expected to be displayed 

### Actual behavior

The URL shown for the Permalink contains two adjacent '/' characters. This is not expected, even if it is not considered incorrect. The link used when selecting the hyperlink is the active link for the product.

### Steps to reproduce

Open the Edit Products page to see the odd URL.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.domain.com
Site address (URL): https://www.domain.com
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Microsoft-IIS/10.0
PHP Version: 8.1.9
PHP Post Max Size: 20 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 10.5.16-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: cl_
Total Database Size: 8.50MB
Database Data Size: 7.94MB
Database Index Size: 0.56MB
cl_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
cl_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_actionscheduler_actions: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
cl_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_actionscheduler_logs: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
cl_aryo_activity_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
cl_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_comments: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
cl_duplicator_pro_entities: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
cl_duplicator_pro_packages: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
cl_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_loginizer_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
cl_mycred_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cl_options: Data: 2.84MB + Index: 0.07MB + Engine MyISAM
cl_postmeta: Data: 1.35MB + Index: 0.13MB + Engine MyISAM
cl_posts: Data: 0.85MB + Index: 0.05MB + Engine MyISAM
cl_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_ualp_user_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cl_usermeta: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
cl_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
cl_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
cl_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
cl_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cl_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cl_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 32
acf-field-group: 3
attachment: 89
customize_changeset: 19
design: 2
elementor_library: 3
mycred_rank: 1
nav_menu_item: 8
page: 19
post: 11
product: 2
revision: 110
shop_coupon: 3
shop_order: 53
wc_order_status: 19
wp_block: 1
wp_global_styles: 2
wp_navigation: 5
wp_template: 11
wp_template_part: 4
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
Activity Log: by Activity Log Team – 2.8.4
Custom Post Type UI: by WebDevStudios – 1.12.1
Duplicator Pro: by Snap Creek – 4.5.5.2
Duplicator Pro: by Snap Creek – 4.5.5.2
Site Kit by Google: by Google – 1.82.0
Google XML Sitemaps: by Auctollo – 4.1.5
LiteSpeed Cache: by LiteSpeed Technologies – 5.2
Loginizer: by Softaculous – 1.7.3
Ultimate Blocks: by Ultimate Blocks – 2.5.2
User Activity Log: by Solwin Infotech – 1.4.9
User Role Editor: by Vladimir Garagulya – 4.63
WooCommerce Order Status Manager: by SkyVerge – 1.13.4
WooCommerce PayFast Gateway: by WooCommerce – 1.4.24
WooCommerce: by Automattic – 6.8.2
WordPress Importer: by wordpressdotorg – 0.7
WP Mail SMTP: by WPForms – 3.5.2
WP Test Email: by Boopathi Rajan – 1.1.5
YITH WooCommerce Uploads Premium: by YITH – 1.2.27

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 5.0
Contact Form 7: by Takayuki Miyoshi – 5.6.3
Elementor: by Elementor.com – 3.7.4
Essential Addons for Elementor: by WPDeveloper – 5.2.4
Hello Dolly: by Matt Mullenweg – 1.7.2
License Manager for WooCommerce (Free): by LicenseManager – 2.2.8
Points and Rewards for WooCommerce: by WP Swings – 1.2.9
Really Simple SSL: by Really Simple Plugins – 5.3.3
WP Migrate DB Pro: by Delicious Brains – 2.2.1
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.6

Zero Spam for WordPress: by Highfivery LLC – 5.3.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #89 - /index.php/order/
Cart: #15 - /index.php/cart/
Checkout: #16 - /index.php/checkout/
My account: #17 - /index.php/my-account/
Terms and conditions: #83 - /index.php/privacy-policy-2/

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-09-07 11:16:00 +02:00
Options: ✔
Notes: 52
Onboarding: skipped

### Action Scheduler ###

Complete: 244
Oldest: 2022-08-11 19:38:58 +0000
Newest: 2022-09-06 21:19:26 +0000

Pending: 2
Oldest: 2022-09-07 06:29:45 +0000
Newest: 2022-09-12 14:00:05 +0000

### Status report information ###

Generated at: 2022-09-07 00:12:09 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pekka-28** [comment]
Contact me if you need the actual domain name or access to the system.

**Comment by pekka-28** [comment]
I have subsequently realised that my observations about the benign nature of this were unfounded. When viewing the product list, the Add to cart button works correctly as it uses the canonical product number. Selecting the product or its image returns a 404 error as the link has propagated to the site.

Until now, I had thought the problem was a documentation only problem on the Product editing page.

**Comment by swatipawarGS** [comment]
Hi @pekka-28,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2version. 

Please find below the screenshot for reference :
![#34598](https://user-images.githubusercontent.com/94531721/189058914-f71d8b25-f468-404d-bf33-5272c9a06f27.jpg)

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by pekka-28** [comment]
Swati

I have appended an image showing where I first located the concern, and a second one showing how the link to a product is also incorrect.

Perhaps you are not running Windows like I am. I pointed out that the permalinks on the installation include the “index.php” file as I the web server is IIS.

Regards
Pekka Pihlajasaari
--
***@***.***           Data Abstraction (Pty) Ltd         +27 11 484 9664
--
***@***.***
***@***.***

**Comment by pekka-28** [comment]
Swati

My apologies. I have subsequently been told that a colleague had inadvertently change the permalink settings in WooCommerce. The problem has now cleared and no longer affects the site.

I’m sorry for having suspected an application rather than a configuration error.

You can close the incident out as opened in error.

Regards
Pekka Pihlajasaari
--
***@***.***           Data Abstraction (Pty) Ltd         +27 11 484 9664

From: Pekka Pihlajasaari
Sent: 8 September 2022 17:05
To: woocommerce/woocommerce ***@***.***>
Subject: RE: [woocommerce/woocommerce] Edit Product Permalink in Windows malformed URL (Issue #34598)

Swati

I have appended an image showing where I first located the concern, and a second one showing how the link to a product is also incorrect.

Perhaps you are not running Windows like I am. I pointed out that the permalinks on the installation include the “index.php” file as I the web server is IIS.

Regards
Pekka Pihlajasaari
--
***@***.******@***.***>           Data Abstraction (Pty) Ltd         +27 11 484 9664
--
***@***.***
***@***.***
