### ISSUE TITLE
getting error while trigger command  "pnpm run build"

### ISSUE THREAD

**Issue by vikas6918** [woothemes/woocommerce#34591]
command (packages\js\e2e-core-tests) pnpm run turbo:build -- exited (1)

 Tasks:    10 successful, 11 total
Cached:    7 cached, 11 total
  Time:    40.1s

 ELIFECYCLE  Command failed with exit code 1.

**Comment by samueljseay** [comment]
Hey @vikas6918 ideally you wouldn't run `turbo:build` directly. Turbo repo calls that command.

Could you try `pnpm run build` instead and let me know if that works?

**Comment by helgatheviking** [comment]
@samueljseay Here's what I am seeing with the latest trunk:

>helga@Helga:~/woocommerce$ pnpm run build
>
>\> woocommerce-monorepo@ build /home/helga/woocommerce
>\> pnpm exec turbo run turbo:build
>
>ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: turbo run turbo:build
spawn turbo ENOENT
> ELIFECYCLE  Command failed with exit code 1.

For what it's worth `pnpm install` is also failing 

>node_modules/.pnpm/puppeteer@2.1.1/node_modules/puppeteer: Running install script, failed in 889ms
.../node_modules/puppeteer install$ node install.js
│ ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
│ Error: read ECONNRESET
│     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
│   -- ASYNC --
│     at BrowserFetcher.<anonymous> (/home/helga/woocommerce/node_modules/.pnpm/puppeteer@2.1.1/node_modules/puppeteer
│     at Object.<anonymous> (/home/helga/woocommerce/node_modules/.pnpm/puppeteer@2.1.1/node_modules/puppeteer/install
│     at Module._compile (node:internal/modules/cjs/loader:1126:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
│     at Module.load (node:internal/modules/cjs/loader:1004:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
│     at node:internal/main/run_main_module:17:47 {
│   errno: -104,
│   code: 'ECONNRESET',
│   syscall: 'read'
│ }
└─ Failed in 890ms
 ELIFECYCLE  Command failed with exit code 1.

**Comment by vikas6918** [comment]
its works fine thanks.

**Comment by jonathansadowski** [comment]
@vikas6918, Thanks for letting us know that it's working for you now!

@helgatheviking I've done some searching on that error messaging, and there are some reports that that happens with older versions of node/npm. Can you confirm whether or not you've installed [nvm](https://github.com/nvm-sh/nvm#installing-and-updating)? If you've installed nvm, did you run `nvm use` prior to attempting the `pnpm install`?

**Comment by helgatheviking** [comment]
Yes, I used `nvm use` first.... I'll test again eventually but I had to get going one another project so downloaded a release asset.

**Comment by vikas6918** [comment]
Glad to hear it!

**Comment by psealock** [comment]
Since the original author has found a solution I will close this out. @helgatheviking if you have further problems, feel free to open a new issue.

**Comment by helgatheviking** [comment]
Was this issue actually resolved? I worked around it by downloading a compiled asset... That hardly seems like a solution for somebody who wants to work on the repo.

**Comment by psealock** [comment]
@helgatheviking  can you confirm `pnpm install` fails with node 16.13.1 and pnpm 7.13.3 ?

**Comment by helgatheviking** [comment]
well hot damn... after installing composer and a few missing php extensions, it compiled. I guess it's ok.... for now. Thanks!

**Comment by psealock** [comment]
Nice! Glad to hear its working @helgatheviking. If you run into any more issues, please open a new issue
