### ISSUE TITLE
"No orders found" when clicking 'View other orders →" link from an order.

### ISSUE THREAD

**Issue by mjmolo** [woothemes/woocommerce#34618]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Today when using WooCommerce I noticed that I get a 'No orders found' result, when I click on any customer's 'View other orders →" link from an order page. I tested this on 3+ orders and all came back with zero results. This just started happening after the recent update 3-5 days ago.

### Expected behavior

Typically you see the orders (even if it's just one single order) from the customer on this page, with their email in the filter.

### Actual behavior

Now there is no filter and all orders show the 'No orders found' message.

### Steps to reproduce

1. Go to Orders in WooCommerce
2. Click an order to view it.
3. Click the link button for 'View other orders →" 
4. See the 'no orders found' message.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://filtergrade.com
Site address (URL): https://filtergrade.com
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/5.1.0
PHP Version: 7.4.30
PHP Post Max Size: 3 GB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.38-google
Max Upload Size: 3 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: wp_
Total Database Size: 6248.12MB
Database Data Size: 3971.33MB
Database Index Size: 2276.79MB
wp_woocommerce_sessions: Data: 82.09MB + Index: 4.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 66.59MB + Index: 88.39MB + Engine InnoDB
wp_woocommerce_order_items: Data: 11.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 84.61MB + Index: 66.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ahm_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.05MB + Index: 6.77MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aepc_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 8.52MB + Index: 1.52MB + Engine InnoDB
wp_ahm_download_stats: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_as3cf_items: Data: 502.98MB + Index: 45.77MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_contact_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_logmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_syncrecords: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_tasks: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_task_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 2.52MB + Index: 1.22MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 5.52MB + Index: 0.27MB + Engine InnoDB
wp_commentmeta: Data: 1.19MB + Index: 0.23MB + Engine InnoDB
wp_comments: Data: 72.59MB + Index: 52.09MB + Engine InnoDB
wp_dae_linkmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dae_links: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_dae_subscribermeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dae_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hustle_modules_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_hustle_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_conversions: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_om_leads: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 47.52MB + Index: 18.06MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_oses_emails: Data: 26.52MB + Index: 0.13MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 1331.98MB + Index: 469.77MB + Engine InnoDB
wp_posts: Data: 193.67MB + Index: 52.16MB + Engine InnoDB
wp_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wp_prli_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_prli_links: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sdm_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sharebar: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
wp_terms: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wp_term_relationships: Data: 27.56MB + Index: 14.55MB + Engine InnoDB
wp_term_taxonomy: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_tinvwl_analytics: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_tinvwl_items: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 150.69MB + Index: 96.20MB + Engine InnoDB
wp_users: Data: 9.52MB + Index: 7.55MB + Engine InnoDB
wp_wbz404_logs: Data: 0.41MB + Index: 0.19MB + Engine InnoDB
wp_wbz404_redirects: Data: 0.20MB + Index: 0.38MB + Engine InnoDB
wp_wcpv_commissions: Data: 18.55MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 9.52MB + Index: 6.03MB + Engine InnoDB
wp_wc_download_log: Data: 13.52MB + Index: 9.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.23MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 15.55MB + Index: 13.06MB + Engine InnoDB
wp_wc_order_stats: Data: 10.52MB + Index: 7.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 6.52MB + Index: 10.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppg_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppg_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppg_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppg_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 9.52MB + Index: 15.63MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_hit: Data: 61.59MB + Index: 134.92MB + Engine InnoDB
wp_wps_index: Data: 686.98MB + Index: 686.53MB + Engine InnoDB
wp_wps_key: Data: 4.52MB + Index: 2.52MB + Engine InnoDB
wp_wps_object_term: Data: 214.75MB + Index: 335.59MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 5.52MB + Index: 3.52MB + Engine InnoDB
wp_wps_uri: Data: 32.56MB + Index: 12.58MB + Engine InnoDB
wp_wps_user_agent: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_yoast_indexable: Data: 170.72MB + Index: 66.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 11.52MB + Index: 12.55MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.27MB + Index: 0.23MB + Engine InnoDB
wp_yoast_seo_links: Data: 7.52MB + Index: 3.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 21
acf-field-group: 2
adstxt: 1
advanced_ads: 1
algolia_log: 46
algolia_task: 13753
amn_mi-lite: 3
attachment: 117900
custom_css: 3
download: 1
edd_payment: 2
elementor_library: 2
insertpostads: 1
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 68
newsletter: 10
oembed_cache: 1964
optin: 5
page: 85
photo: 2
portfolio: 1
post: 1250
product: 14141
product_variation: 44200
revision: 27
safecss: 1
sdm_downloads: 1
shop_coupon: 87535
shop_order: 86141
shop_order_refund: 686
shop_subscription: 3
subscriber: 210
vc_grid_item: 1
wfacp_checkout: 1
wffn_landing: 1
wffn_ty: 1
wfocu_funnel: 1
wfocu_offer: 1
wp_block: 2
wp_global_styles: 1
wpdmpro: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Akismet Anti-Spam: by Automattic – 5.0
WP Offload Media: by Delicious Brains – 2.6.2
Classic Editor: by WordPress Contributors – 1.6.2
Cloudflare: by Cloudflare
Inc. – 4.11.0

Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.0
Disable Cart Fragments: by Optimocha – 2.1.1
Download After Email: by MK-Scripts – 2.1.4
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
Elementor Pro: by Elementor.com – 3.7.5
Elementor: by Elementor.com – 3.7.4
Envato Market: by Envato – 2.0.7
Filtergrade Custom Download Settings: by WiserDev Ltd – 1.0.0
FilterGrade Custom Emails: by dcardona@bluecoding.com – 1.0
FilterGrade Payments CSV: by WiserDev Ltd – 1.0.0
FilterGrade Vendors: by  –
Site Kit by Google: by Google – 1.82.0
Grant download permissions for past WooCommerce orders: by Claudio Sanches – 0.0.2
Smash Balloon Instagram Feed: by Smash Balloon – 6.0.6
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
Mailchimp for WooCommerce: by Mailchimp – 2.7.3
Product Blocks for WooCommerce: by GetBowtied – 1.5.1
Fixed Widget: by Thomas Maier
Max Bond – 6.1.1

CM Commerce for WooCommerce: by Campaign Monitor – 1.6.6
Remove Dashboard Access: by TrustedLogin – 1.1.5
Simple 301 Redirects: by WPDeveloper – 2.0.6
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.34
The Retailer Deprecated Features: by GetBowtied – 1.2.4
The Retailer Extender: by GetBowtied – 1.5.7
TI WooCommerce Wishlist: by TemplateInvaders – 1.47.0
Top Bar: by WP Darko – 3.0.3
User Switching: by John Blackbourn & contributors – 1.7.0
Shortcodes by Angie Makes: by Chris Baldelomar – 3.46
CTX Feed: by WebAppick – 4.5.1
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0
Pixel Manager for WooCommerce: by SweetCode – 1.20.2
WP WooCommerce Mailchimp: by Saint Systems – 2.4.9
WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Product Search: by itthinx – 4.7.0
WooCommerce Product Vendors: by WooCommerce – 2.1.65
WooCommerce Shop as Customer: by cxThemes – 2.16
WooCommerce: by Automattic – 6.8.2
Yoast SEO: by Team Yoast – 19.6.1
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Offload SES: by Delicious Brains – 1.5.6
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.7

WP Rocket: by WP Media – 3.12.0.5
Trending/Popular Post Slider and Widget: by WP OnlineSupport
Essential Plugin – 1.5.5

WPForms Lite: by WPForms – 1.7.6

### Inactive Plugins (4) ###

AffiliateWP: by Sandhills Development
LLC – 2.7.6

Gravity Forms: by Gravity Forms – 2.6.4
Query Monitor: by John Blackbourn – 3.9.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php

### Must Use Plugins (1) ###

Disable file editing: by  –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4-2)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #1523 - /shop/
Cart: #1524 - /cart/
Checkout: #1525 - /checkout/
My account: #1520 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: The Retailer Child Theme
Version: 20220326
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: The Retailer
Parent Theme Version: 3.3
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: theretailer-child/woocommerce/archive-product.php
theretailer-child/woocommerce/content-product.php
theretailer-child/woocommerce/content-single-product.php
theretailer-child/woocommerce/product-searchform.php
theretailer-child/woocommerce/single-product/add-to-cart/variable.php
theretailer/woocommerce/single-product/related.php
theretailer/woocommerce/single-product/tabs/tabs.php
theretailer-child/woocommerce/single-product/up-sells.php
theretailer/woocommerce/single-product.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-09-08 17:08:45 -04:00
Options: ✔
Notes: 101
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 23
Oldest: 2022-08-08 14:29:02 -0400
Newest: 2022-09-08 08:03:55 -0400

Complete: 14,153
Oldest: 2022-08-09 10:50:54 -0400
Newest: 2022-09-08 11:53:47 -0400

Failed: 125
Oldest: 2019-07-08 16:26:18 -0400
Newest: 2022-01-20 01:12:26 -0500

Pending: 8
Oldest: 2022-09-08 12:08:42 -0400
Newest: 2022-09-15 10:53:03 -0400

### Status report information ###

Generated at: 2022-09-08 12:07:52 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @mjmolo,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/189591814-9a6f42f6-8bb1-4e70-a10a-9ab7af0a96f1.mp4


Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by mjmolo** [comment]
Thanks swatipawarGS, just tested this on our site, and we can confirm this appears fixed. Maybe it was a small bug/error limited to something, but the error is no longer occurring.
