### ISSUE TITLE
[Enhancement]: Product Table > UX (quick win) > non sortable Featured Product column 

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#34628]
### Describe the solution you'd like

just add make the column sortable (with the sort icon like on other critical fields)
* Actual columns that are sortable : Name / SKU / Price / Date
* One major is missing : featured product (the little star icon)

![image](https://user-images.githubusercontent.com/919332/189370655-263a8f56-921b-472c-b257-33b45c4e7fc2.png)

### Describe alternatives you've considered

Missing feature !
the only way is to export to CSV and play with Excel, but the extractor has some bugs also when you make use of variations...

### Additional context

When you manage your shop, you'll have to deal with featured product for sure, and more to say you need from time to time to update the due list of featured product !!! Especially when you make use of the Featured Product Block.
* When you have less thant 60 products, it is doable, the only way is to play with product table pagination or CSV export to find the complete list of featured products and then edit them back in the product menu.
*  but when you have 100+ more products, it is a nighmare ! Actually is it extremely difficult to manage the featured product block items manually ....
* it is mandatory so we can make use of the featured product block properly (manage the due list of featured product we push to front)

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities. We're going to close the issue and at some point, we may revisit our priorities and review the list of suggestions like this one to see if it warrants a second look. Don’t be alarmed if you don’t see any activity on this issue for a while.
