### ISSUE TITLE
Enhancement Issue Voting: Improve the process

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34623]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We have a workflow to deal with enhancement requests by way of voting.

https://github.com/woocommerce/woocommerce/blob/6.8.2/.github/workflows/triage-replies.yml#L86-L120

Once the label is applied, the issue is closed and voting can begin. There are a few problems:

* Voting on a closed issue seems like a wasted democratic effort
* Issues to be voted on aren't easily found because they are closed
* Even if they are found, one might not partake in the democratic process due to thinking its not relevant anymore
* The comment doesn't say how to vote
* We are not getting an accurate measure of how much demand there might be for issues

This issue should investigate an alternate solution. Perhaps like closing an issue if not enough votes are gathered in a set time period?

**Comment by lsinger** [comment]
Woo Developer Advocacy would like to be in the loop on this and consult as needed. Documenting a new process e.g. on the Developer Portal could be a good option to make it more visible and discoverable.

**Comment by samueljseay** [comment]
@lsinger I'd like to re-raise this with y'all on advocacy. We see enhancement triage/prioritization being quite useless right now with no-one owning the process on the dev side. 

I think it would be great to move enhancements off of Github to a voting system.

I see several benefits:

1. Declutter the issue board which is very bloated right now
2. Community voting will auto-highlight issues that 3pds and others care about, a community contributed prioritization list. I can imagine this would also be encouragement for teams to pick up high voted work on hack weeks!
3. Enhancement is used in Github right now by teams doing project management with that category, so it would also declutter enhancements that are being used to track project management of features

**Comment by lsinger** [comment]
@samueljseay @psealock thanks for the ping! I agree we need to change how this works. 

Would you mind kicking off a discussion on your team's P2 and cross-posting to Woo Engineering, Woo Product, and Developer Advocacy? That way we can ensure all affected parties will have visibility into the discussion.

**Comment by psealock** [comment]
This issue deserves a larger format for discussion because there are a few ways we can go with this.

@samueljseay has already begun the conversation in pdqwkG-xu-p2 so I will close this out and create new issues once a process has been decided on.
