### ISSUE TITLE
Synchin issue of transaction in woocommerce panel or store and payu plugin.

### ISSUE THREAD

**Issue by askrun** [woothemes/woocommerce#34675]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Error in syncing of transaction in real time in woo-commerce.

### Expected behavior

before 11 of this month , the activity of transaction is synching.onwards syncing issues.

### Actual behavior

main problem transaction is displayed in payu ,but not shown in woocommerce order panel.

### Steps to reproduce

yes , problem not resolved yet.

### WordPress Environment

hi team ,

i am not able to sync my real time transaction of my woo-commerce order's

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
hi @askrun Could you please include steps for reproduction and provide details of your environment?

**Comment by askrun** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://www.eamzn.in
	Home URL: https://www.eamzn.in
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Kolkata
	Admin Email: ***@***.***
	Debug Mode: Inactive

== Theme ==
	Name: Chromium
	Version: 1.3.28
	Author: Themes Zone
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0

== Active Plugins ==
	Advanced Order Export For WooCommerce
		Version: 3.3.2
		Author: AlgolPlus

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Cron Jobs
		Version: 1.2.9
		Author: Ariel

	CTX Feed
		Version: 4.5.1
		Author: WebAppick

	Easy Watermark
		Version: 1.0.11
		Author: BracketSpace

	Elementor
		Version: 3.7.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.0
		Author: Wpmet

	Facebook for WooCommerce
		Version: 2.6.23
		Author: Facebook

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.20.0
		Author: FiboSearch Team

	Folders
		Version: 2.8.5
		Author: Premio

	Google Listings and Ads
		Version: 2.1.2
		Author: WooCommerce

	Google XML Sitemaps
		Version: 4.1.5
		Author: Auctollo

	IndexNow
		Version: 1.0.1
		Author: Microsoft Bing

	Jetpack
		Version: 11.3.1
		Author: Automattic

	Jetpack Boost
		Version: 1.5.1
		Author: Automattic - Website Speed and Performance team

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	Max Mega Menu
		Version: 2.9.8
		Author: megamenu.com

	Nextend Social Login
		Version: 3.1.6
		Author: Nextendweb

	PayU India
		Version: 3.8.2
		Author: PayU

	Pinterest for WooCommerce
		Version: 1.2.2
		Author: WooCommerce

	Poptin
		Version: 1.3
		Author: Poptin

	Product Slider for WooCommerce
		Version: 2.6.1
		Author: ShapedPlugin

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Shipment Tracker for Woocommerce
		Version: 1.3.2
		Author: Bitss Techniques

	Shiprocket
		Version: 1.0.7
		Author: Shiprocket

	Simple History
		Version: 3.3.0
		Author: Pär Thernström

	Site Kit by Google
		Version: 1.83.0
		Author: Google

	Slider Revolution
		Version: 6.5.21
		Author: ThemePunch

	Stars Testimonials
		Version: 3.2.7
		Author: Premio

	Themes Zone Feature Pack for Chromium Theme
		Version: 1.4.2
		Author: Themes Zone

	TM WooCommerce Compare &amp; Wishlist
		Version: 1.1.7
		Author: JetImpex

	WCFM - WooCommerce Frontend Manager
		Version: 6.6.5
		Author: WC Lovers

	WCFM - WooCommerce Multivendor Marketplace
		Version: 3.5.6
		Author: WC Lovers

	WCK - Custom Fields and Custom Post Types Creator
		Version: 2.3.2
		Author: Cozmoslabs, Madalin Ungureanu, Cristian Antohe

	WooCommerce
		Version: 6.9.1
		Author: Automattic

	WooCommerce Blocks
		Version: 8.5.0
		Author: Automattic

	WooCommerce Google Analytics Integration
		Version: 1.5.14
		Author: WooCommerce

	WooCommerce GST
		Version: 1.3
		Author: Stark Digital

	WooCommerce Payment Gateway - CoinGate
		Version: 2.0.2
		Author: CoinGate

	WooCommerce PayPal Payments
		Version: 1.9.3
		Author: WooCommerce

	WooCommerce PDF Invoices &amp; Packing Slips
		Version: 3.1.1
		Author: WP Overnight

	WooCommerce Price Based on Country (Basic)
		Version: 2.2.5
		Author: Oscar Gare

	WooCommerce Shipping &amp; Tax
		Version: 1.26.3
		Author: WooCommerce

	WooCommerce Wholesale Prices
		Version: 2.1.4
		Author: Rymera Web Co

	WP Blockchain
		Version: 3.2.1
		Author: Good Rebels Inc.

	Wp Fundraising Donation
		Version: 1.6.0
		Author: Wpmet

	Wp Social
		Version: 1.9.0
		Author: Wpmet

	Wp Ultimate Review
		Version: 2.0.2
		Author: Wpmet

	XML for Google Merchant Center
		Version: 2.9.8
		Author: Maxim Glazunov

	YITH Essential Kit for WooCommerce #1
		Version: 2.12.0
		Author: YITH

	Yoast SEO
		Version: 19.6.1
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 292022-09-01 02:06:12 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-09-01 02:06:13 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-09-01 02:06:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.2',
  'to' => '3.6.3',
)]
2022-09-01 02:06:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.2',
  'to' => '3.6.3',
)]
2022-09-06 06:46:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.4',
)]
2022-09-06 06:46:53 [info] elementor::elementor_updater Started 
2022-09-06 06:46:53 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-06 06:46:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-06 06:46:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.4',
)]
2022-09-15 15:58:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-15 15:58:43 [info] elementor::elementor_updater Started 
2022-09-15 15:58:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-15 15:58:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-15 15:58:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-15 15:58:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-15 15:58:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-16 00:06:13 [info] elementor::elementor_updater Started 
2022-09-16 00:06:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-16 00:06:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-16 00:06:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]

JS: showing 2 of 2JS: 2022-08-12 13:38:54 [error X 2][https://eamzn.in/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:766552] Cannot read properties of undefined (reading \&#039;localized\&#039;) 
JS: 2022-09-05 18:51:27 [error X 5][https://eamzn.in/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.2:2:15625] Cannot read properties of undefined (reading \&#039;global\&#039;) 

PHP: showing 11 of 11PHP: 2022-08-13 08:06:37 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor-pro/plugin.php::311] Uncaught Error: Class &#039;ElementorPro\Core\Modules_Manager&#039; not found in /home2/eamzn6qf/public_html/wp-content/plugins/elementor-pro/plugin.php:311
Stack trace:
#0 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#1 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /home2/eamzn6qf/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
#3 /home2/eamzn6qf/public_html/wp-content/plugins/elementor/includes/plugin.php(646): do_action(&#039;elementor/init&#039;)
#4 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(307): Elementor\Plugin-&gt;init(&#039;&#039;)
#5 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /home2/eamzn6qf/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
#7 /home2/eamzn6qf/public_html/wp-settings.php(598): do_action(&#039;init&#039;)
#8 /home2/eamzn6qf/public_html/wp-config.php(98): require_once(&#039;/home2/eamzn6qf...&#039;)
#9 /home2/ea [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 08:06:37 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor-pro/modules/global-widget/module.php::202] Uncaught Error: Class &#039;ElementorPro\Modules\GlobalWidget\Documents\Widget&#039; not found in /home2/eamzn6qf/public_html/wp-content/plugins/elementor-pro/modules/global-widget/module.php:202
Stack trace:
#0 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\GlobalWidget\Module-&gt;register_documents(Object(Elementor\Core\Documents_Manager))
#1 /home2/eamzn6qf/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /home2/eamzn6qf/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
#3 /home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/documents-manager.php(692): do_action(&#039;elementor/docum...&#039;, Object(Elementor\Core\Documents_Manager))
#4 /home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/documents-manager.php(177): Elementor\Core\Documents_Manager-&gt;register_types()
#5 /home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/editor/editor.php(237): Elementor\Core\Documents_Manager-&gt;get(NULL)
#6 /home2/eamzn6qf/pub [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-28 06:11:39 [notice X 43][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::469] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-01 02:07:12 [notice X 348][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property &#039;ID&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-05 12:23:48 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 26065840 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-05 13:02:48 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 26072560 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-05 13:43:14 [notice X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 06:54:21 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 1810432 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 09:30:08 [notice X 9][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 11:52:50 [error X 1][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 26086848 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 15:19:42 [error X 3][/home2/eamzn6qf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 26086592 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by psealock** [comment]
Thanks @askrun for the details of your environment.
Could you please provide steps to reproduce the error?

**Comment by askrun** [comment]
Hi team, Problem not resolved yet. Sent from Mail for Windows From: Paul SealockSent: 20 September 2022 07:41To: woocommerce/woocommerceCc: askrun; MentionSubject: Re: [woocommerce/woocommerce] Synchin issue of transaction in woocommerce panel or store and payu plugin. (Issue #34675) Thanks @askrun for the details of your environment.Could you please provide steps to reproduce the error?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> Virus-free.www.avg.com

**Comment by jonathansadowski** [comment]
Hi @askrun,

Thanks for this report, but I didn't see any steps for reproduction come through with your last message. Without steps for reproduction, we're unable to research this issue further. Could you please provide a list of steps that you take that will allow us to reproduce the issue?
