### ISSUE TITLE
Woocommerce  6.9 latest version Have wp-admin backend issue 

### ISSUE THREAD

**Issue by manojvashist91** [woothemes/woocommerce#34673]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When i install a latest version of Woo-commerce with Woo-commerce shop theme and any other theme then back end of WordPress give error. 

"There has been a critical error on this website. "
Front side of side running fine while back end give issue.

### Expected behavior

Expected behaviour is back-end (wp-admin) runnning fine also. 

### Actual behavior

Wp-admin not working after installing and activating latest version of woo-commerce.

### Steps to reproduce

1. Go to wp-admin 
2. Add plugins 
3. search woo-commerce plugin.
4. install woo-commerce latest plugin and active it
5. Check wp-admin working or not.   
[screen-capture.webm](https://user-images.githubusercontent.com/33026000/190145060-ca1f5961-3110-4bd4-aed4-5461b8a68ab1.webm)

### WordPress Environment

As back-end(wp-admin) is not open after activate woo-commerce so not able to check status.
thanks.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by NaitChris** [comment]
i have the same problem but my backend works fine. The Elementor doen´t work. When i will edit a Page with Elementor, i get an critical error by wordpress.

Can you switch to PHP Version 7.4? My problem is solved now after i switched down to 7.4. It looks like an PHP 8.x Problem.
