### ISSUE TITLE
Multiple additional instructions for product image displayed

### ISSUE THREAD

**Issue by enricobattocchi** [woothemes/woocommerce#34678]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using WooCommerce 6.9 with Yoast SEO for WooCommerce, creating a new Product or editing a Product without a featured image results in a repetition of the new notice to guide users with the image upload.

### Expected behavior

There should be only one copy of the notice.

### Actual behavior

See image:
![image (5)](https://user-images.githubusercontent.com/15989132/190186267-8c8e9601-fd8f-4217-8cec-a5ad8988b877.png)

### Steps to reproduce

1. Install and activate WooCommerce 6.9
2. Install and activate Yoast SEO 19.6 + Yoast SEO for WooCommerce 15.1 (these are the latest released version, but any recent version is triggering the same behaviour)
3. Start creating a new Product, e.g. with Products > Add New
4. Check the "Product Image" section in the edit screen

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://basic.wordpress.test
Site address (URL): http://basic.wordpress.test
WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.30
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.38
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: 
Total Database Size: 8.72MB
Database Data Size: 6.77MB
Database Index Size: 1.95MB
woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
options: Data: 5.02MB + Index: 0.06MB + Engine InnoDB
postmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
posts: Data: 0.33MB + Index: 0.06MB + Engine InnoDB
termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yoast_indexable: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yoast_prominent_words: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
book: 1
elementor_library: 1
page: 13
post: 113
product: 3
product_variation: 4
revision: 20
wp_global_styles: 2
wpseo_locations: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.10.1
Debug Bar: by wordpressdotorg – 1.1.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
WooCommerce: by Automattic – 6.9.0
Yoast SEO: by Team Yoast – 19.6
Yoast SEO: WooCommerce: by Team Yoast – 15.1
Yoast Test Helper: by Team Yoast – 1.18

### Inactive Plugins (57) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.0.1

Advanced Custom Fields: by Delicious Brains – 5.12.3
Advanced Custom Fields PRO: by Elliot Condon – 5.8.11
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Akismet Anti-Spam: by Automattic – 5.0
All in One SEO: by All in One SEO Team – 4.2.5.1
altavoce-demo — CGB Gutenberg Block Plugin: by mrahmadawais
maedahbatool – 1.0.0

Andreatest: by Andrea Fercia – 1.0
Auto Amazon Links: by Michael Uno (miunosoft) – 5.2.9
Avada Builder: by ThemeFusion – 3.1.1
Avada Core: by ThemeFusion – 5.1.1
bbPress: by The bbPress Contributors – 2.6.9
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Co-Authors Plus: by Mohammad Jangda
Daniel Bachhuber
Automattic – 3.5.2

Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.5
Custom Post Type UI: by WebDevStudios – 1.13.1
Divi Builder: by Elegant Themes – 4.9.4
Elementor: by Elementor.com – 3.7.4
Elementor Pro: by Elementor.com – 3.3.1
Give - Donation Plugin: by GiveWP – 2.22.0
Gutenberg: by Gutenberg Team – 14.0.3
Health Check & Troubleshooting: by The WordPress.org community – 1.5.0
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.3.1
JSON Basic Authentication: by WordPress API Team – 0.1
JWT Auth: by Useful Team – 2.1.0
LearnDash LMS: by LearnDash – 3.0.5.1
Log HTTP Requests: by FacetWP
LLC – 1.3.2

Mailster WordPress Newsletter Plugin Compatibility Tester: by EverPress – 1.0.3
Members: by MemberPress – 3.2.1
Page Builder by SiteOrigin: by SiteOrigin – 2.17.0
Perfect Brands for WooCommerce: by QuadLayers – 2.2.1
Scripts n Styles: by unFocus Projects – 3.5.2
SportsPress: by ThemeBoy – 2.7.15
The Events Calendar: by The Events Calendar – 6.0.0.1
User Switching: by John Blackbourn & contributors – 1.7.0
Web Stories: by Google – 1.24.0
WooCommerce Admin: by WooCommerce – 3.3.2
Wordfence Security: by Wordfence – 7.6.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.2

WordPress Importer: by wordpressdotorg – 0.7
WordPress Sentry: by Alex Bouma – 6.0.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.7

WPBakery Page Builder: by Michael M - WPBakery.com – 6.7.0
WP CLI Faker: by  –
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.5
WP Search with Algolia: by WebDevStudios – 2.2.0
Yoast Comment Hacks: by Team Yoast – 1.7
Yoast Comment Hacks: by Team Yoast – 1.7
Yoast Crawl Cleanup: by Joost de Valk & Team Yoast – 0.1
Yoast SEO: Local: by Team Yoast and Arjan Snaterse – 14.6
Yoast SEO: News: by Team Yoast – 13.1
Yoast SEO: Video: by Team Yoast – 14.6
Yoast SEO Premium: by Team Yoast – 19.3-RC7

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #142 - /shop/
Cart: #143 - /cart/
Checkout: #144 - /checkout/
My account: #145 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-15 13:11:35 +00:00
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Complete: 60
Oldest: 2022-09-02 13:14:00 +0000
Newest: 2022-09-14 12:51:37 +0000

Pending: 1
Oldest: 2022-09-15 11:04:03 +0000
Newest: 2022-09-15 11:04:03 +0000

### Status report information ###

Generated at: 2022-09-14 14:48:25 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the report @enricobattocchi. Just to confirm, this issue doesn't exist when the Yoast SEO plugin is deacitvated?

**Comment by enricobattocchi** [comment]
Hi @psealock, I confirm!
If it can help, from an investigation we performed it seems that every call to `wc_get_product()` triggers a new object creation and thus a new addition to the product image notices.

**Comment by tijosh** [comment]
I can reproduce this on 6.9.2 without Yoast SEO installed

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/35117248/190875818-3aa3bb4f-767e-4139-a62e-e263897055ab.png">

It's related to this PR: https://github.com/woocommerce/woocommerce/pull/33660

SSR
<details>
`
### WordPress Environment ###

WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.83.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.2
WC Database Prefix: wp_
Total Database Size: 3.46MB
Database Data Size: 1.67MB
Database Index Size: 1.79MB

### Post Type Counts ###

attachment: 1
customize_changeset: 2
custom_css: 1
page: 7
post: 1
product: 3
revision: 2
shop_order: 100
shop_order_refund: 1
shop_subscription: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 5.0
Jetpack: by Automattic – 11.4-a.3
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0
WooCommerce Payments: by Automattic – 4.7.2
WooCommerce: by Automattic – 6.9.2
WP phpMyAdmin: by Puvox.software – 5.2.0.7

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscription Statuses: wc-on-hold: 3
wc-cancelled: 4

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-cancelled: 4
wc-on-hold: 3


### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products
Stripe: products
refunds
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-17 23:10:14 +00:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Canceled: 3
Oldest: 2022-08-17 23:00:35 +0000
Newest: 2022-09-17 18:59:44 +0000

Complete: 306
Oldest: 2022-08-17 23:00:35 +0000
Newest: 2022-09-17 19:09:04 +0000

Pending: 1
Oldest: 2022-09-18 18:54:51 +0000
Newest: 2022-09-18 18:54:51 +0000


### Status report information ###

Generated at: 2022-09-17 20:51:55 +00:00
`
</details>

**Comment by Adriandufour** [comment]
Hello, I have noticed a couple of other repositories linked and I will post an update here with any helpful updates. I wanted to check if there are any updates to this issue? I haven't seen instructions on any fixes or workarounds so I wanted to check. There was mention of creating a WooCommerce filter but I'm unfamiliar with that so if someone has a fix and can explain it that would be helpful. Thanks! I'm showing 5 instances of the instructions error on my website.

**Comment by swatipawarGS** [comment]
Hi @enricobattocchi,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 6.9.2 version and WordPress 6.0.2 version. 

Please find below the screenshot for reference :
![#34678](https://user-images.githubusercontent.com/94531721/191183413-15ecd102-a414-45b1-adb6-6db30a7acd98.jpg)

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by enricobattocchi** [comment]
Hi @swatipawarGS, it still happens to me with all the most recent versions of the relevant plugins:
* Install and activate WooCommerce 6.9.2
* Install and activate Yoast SEO 19.7.1
* Install and activate Yoast SEO for WooCommerce 15.2 (which is a Premium plugin and we can provide if needed)
* Start creating a new Product, e.g. with Products > Add New
* Check the "Product Image" section in the edit screen, see that there are multiple notices
* Disable Yoast SEO for WooCommerce 15.2
* Start creating a new Product, e.g. with Products > Add New
* Check the "Product Image" section in the edit screen, see that there is only one notice

This is the screencast: https://drive.google.com/file/d/13JTAFizULiBLBGge22krhuJWA-0SvdSG/view?usp=sharing

**Comment by peterfabian** [comment]
This will probably be solved by https://github.com/woocommerce/woocommerce/pull/34739

**Comment by enricobattocchi** [comment]
@peterfabian, you're right! Just tested with WooCommerce 6.9.3, the issue is solved. Thanks!

**Comment by larkbegins** [comment]
Thank you! It helped[.](https://profitparrot.com/)!
