### ISSUE TITLE
[Enhancement]: Fix the type error of $screen_id in "/woocommerce/includes/admin/class-wc-admin-assets.php"

### ISSUE THREAD

**Issue by dadizk** [woothemes/woocommerce#34688]
### Describe the solution you'd like

With the latest release 6.9.1 2022-09-14
I got a uncaught Error: Argument 1 passed to WC_Admin_Assets::is_order_meta_box_screen() must be of the type string, null given

Then i found in "/woocommerce/includes/admin/class-wc-admin-assets.php":
line 503, the type of the argument in is_order_meta_box_screen() must be string.
and in line 104, you guys let $screen_id = $screen ? $screen->id : ''; ≧O≦
so , I make a temporary fix，give a "strval()"; 
Please fix it!!
[20220915155947](https://user-images.githubusercontent.com/17421036/190348964-c035af02-3bf9-4145-aa59-b2f144082dcb.png)

**Comment by psealock** [comment]
Hi @zkez, thanks for the report. Could you give clear instructions on how to reproduce this?

**Comment by dennisnissle** [comment]
The screen_id might be null in case `set_current_screen()` is called with no parameter and WP is not able to determine a screen_id for this page (possibly a page added by a third-party) automatically.

**Comment by dadizk** [comment]
> The screen_id might be null in case `set_current_screen()` is called with no parameter and WP is not able to determine a screen_id for this page (possibly a page added by a third-party) automatically.

Thx,very helpful,it indeed caused by the third theme and it has been fixed.

**Comment by contemplate** [comment]
This exact error seems to be breaking the Smart Offers plugin by StoreApps too.  I'll submit a ticket to them as well.
