### ISSUE TITLE
Order Date/Time in admin is wrong since update

### ISSUE THREAD

**Issue by pk-nick** [woothemes/woocommerce#34686]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php

Around line 241 you are outputting the date, hour, and the minute inputs for the order meta data on the edit order screen.

The previous version of the plugin was outputting it correctly with:
esc_attr( date_i18n( ‘H’, strtotime( $post->post_date ) ) )

The newest version is outputting the UTC time, even with a local timezone set via:
esc_attr( date_i18n( ‘H’, strtotime( $order->get_date_created() ) ) )

This is messing up ALL orders in the admin by showing incorrect date/times and potentially making them get saved incorrectly if they update the order after creation. Needs a fix ASAP

### Expected behavior

Viewing the edit order screen, I expect the order date to show my localized time.

### Actual behavior

The date created is showing the UTC time, so in some cases it is showing the next day depending on when the order was placed.

### Steps to reproduce

1. Update Woocommerce to 6.9.1
2. Go to edit order that exist
3. Take notice of the order date, it will reflect the UTC time and not your site local time

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://wzh.localhost.devpki.us
Site address (URL): http://wzh.localhost.devpki.us
WC Version: 6.9.1
REST API Version: ✔ 6.9.1
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 8.0.21
PHP Post Max Size: 100 MB
PHP Time Limit: 720
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.2.44-MariaDB-1:10.2.44+maria~bionic
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.1
WC Database Prefix: pkwp_
Total Database Size: 5.78MB
Database Data Size: 3.84MB
Database Index Size: 1.94MB
pkwp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pkwp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pkwp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
pkwp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
pkwp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pkwp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
pkwp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_ju_queue: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_options: Data: 2.34MB + Index: 0.06MB + Engine InnoDB
pkwp_pk_redirection: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_postmeta: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
pkwp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
pkwp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_tec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pkwp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pkwp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pkwp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pkwp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pkwp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
pkwp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pkwp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pkwp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 39
acf-field-group: 5
attachment: 4
earning: 1
meta: 13
nav_menu_item: 6
page: 10
post: 4
product: 4
product_variation: 15
rating: 6
revision: 21
shop_order: 6
testposttype: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (16) ###

Gravity Forms: by Gravity Forms – 2.6.6
Admin Columns Pro - Advanced Custom Fields (ACF): by AdminColumns.com – 3.0.3
Admin Columns Pro: by AdminColumns.com – 5.7.3
Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Enable Media Replace: by ShortPixel – 4.0.0
Imsanity: by Exactly WWW – 2.8.1
Reorder Posts: by Ryan Hellyer
Ronald Huereca
Scott Basgaard – 2.5.3

Powderkeg Swiss Army Knife: by Nick Kalscheur – 0.4.6
Powderkeg Utility Plugin: by Powderkeg Web Design – 4.8.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
The Events Calendar: by The Events Calendar – 6.0.0.1
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
User Role Editor: by Vladimir Garagulya – 4.63
WooCommerce: by Automattic – 6.9.1
WP Media folder: by Joomunited – 5.4.7

### Inactive Plugins (7) ###

ACF: Better Search: by Mateusz Gbiorczyk – 4.0.1
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.0.1

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.8.2
Gravity Perks: by Gravity Wiz – 2.1.8
Relevanssi: by Mikko Saari – 4.17.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.35
Yoast SEO: by Team Yoast – 19.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #115 - /shop/
Cart: #116 - /cart/
Checkout: #117 - /checkout/
My account: #118 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Powderkeg Custom Website Theme
Version: 6088452900.0
Author URL: https://www.powderkegwebdesign.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: wzh/woocommerce/single-product/add-to-cart/external.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-15 18:37:44 -05:00
Options: ✔
Notes: 51
Onboarding: completed

### Action Scheduler ###

Complete: 67
Oldest: 2022-09-05 13:45:44 -0500
Newest: 2022-09-14 19:10:38 -0500

Pending: 1
Oldest: 2022-09-15 12:00:45 -0500
Newest: 2022-09-15 12:00:45 -0500

### Status report information ###

Generated at: 2022-09-14 19:23:07 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
Can replicate on the latest version:

![image](https://user-images.githubusercontent.com/17475174/190331995-1b1caee5-5ce2-4ea7-9acb-8d5a771d3158.png)

![image](https://user-images.githubusercontent.com/17475174/190331866-d8e9fe1c-4772-4315-9eb0-dd2850b79f1e.png)

Just noting that reverting back to 6.8.2 seems to fix the issue:

![image](https://user-images.githubusercontent.com/17475174/190332746-08701f3f-6d76-4540-948b-fe7527567c28.png)

**Comment by EjayhanFernandes** [comment]
Confirming as well that rolling back to `6.8.2` does resolve the issue:

Version `6.9.1`:

![https://d.pr/VwtTnY+](https://d.pr/VwtTnY+)
*If the image does not load, please click this link: https://d.pr/VwtTnY*

Version `6.8.2`:

![https://d.pr/8FWPGB+](https://d.pr/8FWPGB+)
*If the image does not load, please click this link: https://d.pr/8FWPGB*

**Comment by pehaa** [comment]
Reported by a user zd-5558633

**Comment by solstudioim** [comment]
Reported by another user: 5558596-zd-woothemes

**Comment by roykho** [comment]
This has already been fixed [here](https://github.com/woocommerce/woocommerce/pull/34687) and will be released soon.
