### ISSUE TITLE
[Enhancement]: Don't clean sale start and end dates / why are they being cleared?

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#34696]
### Describe the solution you'd like

Why are the sale dates cleaned after the [sale starts](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L451) or the [sale ends](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L478)?
Is there any performance gain or other rationale behind this? (honest question)

At least while the sale is still on, I can't find a reason to clean the `_sale_price_dates_from` meta.

### Additional context

The reason behind this question is that in some jurisdictions (at least in Portugal and I guess other European countries), shop owners are required by law to show the promotion/sales start and end date.
I got at least one customer who I developed a shop for that was already fined for not showing that information.
I thought: "it's easy to fix, I'll just show the start/end dates next to the price". I was surprised to find out that the [`wc_scheduled_sales` function](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L436) actually cleans that information, making it impossible to show those dates on the frontend.

**Comment by robertbui** [comment]
Google Shopping requires the sale start date if there is a sale end date, or vice versa. Otherwise, Google Shopping will flag an error on the product and not display in the product listing.

https://github.com/wp-plugins/woocommerce/blob/master/includes/wc-product-functions.php
Line 366 - doesn't clear the sale end date (the correct way)


https://woocommerce.github.io/code-reference/files/woocommerce-includes-wc-product-functions.html#source-view.436
Line 451 - clears the the sale end date (incorrect)

Very confusing.

**Comment by barryhughes** [comment]
I suspect this was done as a matter of database cleanliness but, knowing it's problematic in at least some cases, I'm sure we can introduce a change.

**Comment by luciointg** [comment]
Just found this issue. We are also having problems with this behaviour as we need to use both dates to show on the store frontend, at least while the sale is active. Having the start date removed before the end is a problem. Also it doesn't make sense to create custom fields just to duplicate this information.

**Comment by webdados** [comment]
Any updates on this?

How much performance gain, or database cleanliness, is being achieved by deleting one meta key before the sale even ends?

**Comment by barryhughes** [comment]
We have not been working on this. If you (or anyone else with an interest) would like to submit a pull request, though, we'd be happy to review it.

**Comment by webdados** [comment]
I can definitely submit a PR, i was just wondering if there was a good reason for this. (I've inspected the WooCommerce code and can't see one)
