### ISSUE TITLE
CSV Importer: CSV containing 2251 to 2260 products only imports 2250

### ISSUE THREAD

**Issue by jacoswan** [woothemes/woocommerce#34709]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a CSV contains from 2,251 to 2,260 products, only 2,250 products are imported. 
However, if it contains fewer or more than the range above, all products are imported. 

5535712-zen, kudos to @gabriel-fuentes for ID'ing the range. 

### Expected behavior

Expected all products to be imported regardless of how many are listed in the CSV. 

### Actual behavior

When the CSV contains products within that range, only 2,250 products are imported. 

### Steps to reproduce

The following was tested by dropping the database in between each CSV import and starting fresh. 
The CSVs are the same basic products (type, SKU, name), but the SKUs/products in each are unique, so can be imported consecutively. The issue is the same whether importing new or existing products. 

Files: 
1. CSV with 2,249 products (all products are imported): [5535712-csv-with-2249-prods.csv](https://github.com/woocommerce/woocommerce/files/9582567/5535712-csv-with-2249-prods.csv)
2. CSV with 2,258 products (example of the troublesome range, only 2,250 products are imported): [5535712-csv-with-2258-prods.csv](https://github.com/woocommerce/woocommerce/files/9582591/5535712-csv-with-2258-prods.csv)
3. CSV with 2,261 products (all products are imported): [5535712-csv-with-2261-prods.csv](https://github.com/woocommerce/woocommerce/files/9582577/5535712-csv-with-2261-prods.csv)

Steps: 
1. Under Products > All Products > Import, import the file from Files > No. 1 above.
2. Notice that all 2,249 products are imported. 
3. Repeat step No. 1 but use the file from Files > No. 2 above. 
4. Notice how only 2,250 products are imported. 
5. Lastly, repeated No. 1 again, this time with Files > No. 3 above. 
6. Notice how all 2,261 products are imported again. 

Import result of using Files > No. 1 above: 

![xWnc4G.png](https://user-images.githubusercontent.com/15178758/190597529-f63f7bec-b11f-487e-9959-02a769f28048.png)

Import result of using Files > No. 2 above (is the same if CSV contains 2,251 - 2,260 products): 

![HXo6fh.png](https://user-images.githubusercontent.com/15178758/190593263-d0ef70f7-39fb-4ef5-a107-7dadc7425735.png)

Import result of using Files > No. 3 above: 

![YXnh0A.png](https://user-images.githubusercontent.com/15178758/190600221-bb31f67e-4564-438b-9b07-033f42b27310.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woo.tst
Site address (URL): https://woo.tst
WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/8.1.8
PHP Version: 8.1.8
PHP Post Max Size: 500 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 10.8.3-MariaDB
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.2
WC Database Prefix: wp_
Total Database Size: 14.66MB
Database Data Size: 8.53MB
Database Index Size: 6.13MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.38MB + Index: 0.28MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.42MB + Index: 0.38MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.23MB + Index: 0.42MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 2250

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.9.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 6
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2022-09-16 09:15:51 +0000
Newest: 2022-09-16 09:15:51 +0000

Complete: 1,301
Oldest: 2022-09-16 09:15:46 +0000
Newest: 2022-09-16 09:15:52 +0000

Pending: 959
Oldest: 2022-09-16 09:15:53 +0000
Newest: 2022-09-17 09:14:45 +0000

### Status report information ###

Generated at: 2022-09-16 09:16:43 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@jacoswan This one looked like it might be fixed. Could you check?

<img width="1251" alt="Screenshot 2023-07-31 at 4 13 12 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/26bce5bd-096e-4d06-8868-8cddc72de581">
<img width="721" alt="Screenshot 2023-07-31 at 4 12 46 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/6cf73d40-0f99-439a-a137-8bce26bf201b">

**Comment by jacoswan** [comment]
Hey @rrennick 👋 Indeed, I followed the steps above, and file No. 2 now imports all 2,258 products as expected. 

Any idea of what might have caused such an unusual blip?

**Comment by rrennick** [comment]
@jacoswan Thanks for the follow up. I don't see anything it the commit history. It could have been a change somewhere else.
