### ISSUE TITLE
PHP Fatal woocommerce/includes/class-wc-download-handler.php on line 559

### ISSUE THREAD

**Issue by axaak** [woothemes/woocommerce#34710]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the php 8.0 apache module I get this error in woo:
`PHP Fatal error:  Only variables can be passed by reference in /htdocs/wp-content/plugins/woocommerce/includes/class-wc-download-handler.php on line 559`
It seems php 8.0 does not allow dereferencing of numbers. The manual seems quite clear on this:
https://www.php.net/manual/en/language.references.pass.php

If I switch to php8.0-fpm the error does not occur. The problem also doesn't occur with the php 7.4 module.

I think the line
`if ( function_exists( 'apache_setenv' ) ) {`
returns false under php-fpm which is why we only get the problem when using the module.
This change to the woo code works here:

From
```
if ( function_exists( 'apache_setenv' ) ) {
                        @apache_setenv( 'no-gzip', 1 ); // phpcs:ignore Generic.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.DiscouragedPHPFunctions.runtime_configuration_apache_setenv
                }
```
To:
```
if ( function_exists( 'apache_setenv' ) ) {
                        $one    = 1;
                        @apache_setenv( 'no-gzip', $one ); // phpcs:ignore Generic.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.DiscouragedPHPFunctions.runtime_configuration_apache_setenv
                }
```
We are on Debian 10.

### Expected behavior

Viewing the homepage should be possible.  A fatal error should not occur.

### Actual behavior

Homepage is not rendered, screen shows 
**There has been a critical error on this website.**

Apache error log file has fatal described above.

Email sent to site owner:
Error Details

An error of type E_COMPILE_ERROR was caused in line 559 of the file
/home/path/htdocs/wp-content/plugins/woocommerce/includes/class-wc-download-handler.php.
Error message: Only variables can be passed by reference

### Steps to reproduce

1.  Switch environment to apache's mod_php for php 8.0.
2. View website.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.example.com
Site address (URL): https://www.example.com
WC Version: 6.9.1
REST API Version: ✔ 6.9.1
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.5 - There is a newer version of WordPress available (6.0.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 8.0.22
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-0+deb10u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.1
WC Database Prefix: wp_
Total Database Size: 24.91MB
Database Data Size: 19.36MB
Database Index Size: 5.55MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_layerslider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.13MB + Index: 3.03MB + Engine InnoDB
wp_postmeta: Data: 6.34MB + Index: 0.66MB + Engine InnoDB
wp_posts: Data: 6.38MB + Index: 0.22MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 1
acf-field: 6
acf-field-group: 1
ak_enfold_libitem: 2
attachment: 55
avia_framework_post: 13
itl_testimonial: 322
nav_menu_item: 34
oembed_cache: 1
page: 40
post: 3
product: 6
product_variation: 22
revision: 442
shop_order: 45

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
AK Enfold Library: by Ian Stevens – 1.0.0
ITL Course class and associated functions: by Akriga Ltd – 2.0
AK Slider: by Ian Stevens / Adrian Allen – 1.0.0
AK Standard: by Ian Stevens / Adrian Allen – 1.0.2
AK Testimonials: by Ian Stevens / Adrian Allen – 1.0.0
Debug Bar: by wordpressdotorg – 1.1.3
W3 Total Cache: by BoldGrid – 2.2.4
WooCommerce: by Automattic – 6.9.1 (update to version 6.9.2 is available)
Yoast SEO: by Team Yoast – 19.3

### Inactive Plugins (3) ###

Debug Bar Slow Actions: by Konstantin Kovshenin – 0.8.4
Query Monitor: by John Blackbourn – 3.10.1
WordPress Importer: by wordpressdotorg – 0.7

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #3256 - /shop/
Cart: #3253 - /cart/
Checkout: #3254 - /checkout/
My account: #3255 - /my-account/
Terms and conditions: #47 - /terms-and-conditions/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 5.1.1
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-17 08:21:15 +00:00
Options: ✔
Notes: 98
Onboarding: completed

### Action Scheduler ###

Complete: 52
Oldest: 2022-08-16 14:12:18 +0000
Newest: 2022-09-15 14:58:02 +0000

Pending: 2
Oldest: 2022-09-16 11:08:38 +0000
Newest: 2022-09-16 14:58:02 +0000

### Status report information ###

Generated at: 2022-09-16 11:08:44 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks, we'll take a look at this.

> It seems php 8.0 does not allow dereferencing of numbers. The manual seems quite clear on this:
> https://www.php.net/manual/en/language.references.pass.php

The rules on passing by reference are certainly clear, but what's confusing in this case is that, at time of writing, the [`apache_setenv()`](https://www.php.net/manual/en/function.apache-setenv.php) function itself is not documented as receiving a variable by reference. So, this could be a 'bug' in the docs or possibly even a bug in the Apache extension.

We'll take a look, though, and try to replicate—thanks for reporting :+1:

**Comment by axaak** [comment]
Many thanks for looking at this. Apache php extension bug could be a possibility since it doesn't happen with php-fpm or the earlier 7.4 Apache module.

**Comment by barryhughes** [comment]
Sorry for the delay; but I can't seem to replicate this bug. Simplifying things a bit, if I have a script like this:

```php
var_dump( PHP_VERSION );
var_dump( php_sapi_name() );
var_dump( function_exists( 'apache_setenv' ) );
var_dump( apache_setenv( 'no-gzip', 1 ) );
```

And I test with [`php:8.0-apache`](https://hub.docker.com/layers/library/php/8.0-apache/images/sha256-41947fcded88a05964decd0f67b2fc30c94c35c89f2d8d48ee984c918293a05a?context=explore) (which uses `mod_php`), then there is no error in the output:

```
string(6) "8.0.24"
string(14) "apache2handler"
bool(true)
bool(true)
```

This matches my expectations (since, as noted earlier, [`apache_setenv()`](https://www.php.net/manual/en/function.apache-setenv.php) is not documented as expecting a var by reference) ... So it would seem this issue is either specific to your installation, or is perhaps a bug that impacts a very specific version of PHP running under Apache's `mod_php` (perhaps a distro patch?). Given that, I'm just a little reluctant to move toward a fix. 

One last thought ... and this is admittedly a bit of a shot in the dark. If you were to create a `test.php` file containing the following, and access it via your web browser:

```php
<? var_dump( ( new ReflectionFunction( 'apache_setenv' ) )->isUserDefined() );
```

Is the output `(bool) false` or `(bool) true`? I'd expect it to be false, but if it was true it might indicate you have a shim or polyfill in place.

**Comment by axaak** [comment]
Hi,
thank you very much for looking at this.
I have

```
more htdocs/barryh.php 
<?php
var_dump( PHP_VERSION );
var_dump( php_sapi_name() );
var_dump( function_exists( 'apache_setenv' ) );
var_dump( apache_setenv( 'no-gzip', 1 ) );
?>
```
which fails with

`Mon Oct 17 13:25:27.474579 2022] [php:error] [pid 16859] [client 86.138.100.188:47758]  PHP Fatal error:  Only variables can be passed by reference in /home/path/htdocs/barryh.php on line 5`
so re-creatable here.

Picking up on your point that its installation specific, I restarted Apache (again) and all is well!  We have a later version of the php module since I opened this but I can't be sure its that.  Many thanks for your time on this I really appreciate the support.

**Comment by barryhughes** [comment]
> I restarted Apache (again) and all is well!

Terrific! I wonder if it was indeed a bug in `mod_php` (or else the [Apache extension](https://www.php.net/manual/en/book.apache.php)), then? In any case, I'm glad things are now resolved—and thank you for providing an update.
