### ISSUE TITLE
fatal error when moving from php 7.4 to php 8.0 or 8.1

### ISSUE THREAD

**Issue by meestergijs** [woothemes/woocommerce#34718]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have an error in my child theme that doesn't conflict with Woocommerce plugin in php7.4, but it does in 8.0 or up. When I deactivate Woocommerce I don't get the fatal error. Once I activate the Woo plugin my website instantly goes blanc.

This is what my hosting (Kinsta) sends me immediately after:
[error] 78188#78188: *3391 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, no array or string given in /www/live2_166/public/wp-includes/class-wp-hook.php:307

The line in that php file is: $value = call_user_func_array( $the_['function'], $args );

Does anyone here know what all of this means? What the root cause of the problem is? And even how to fix it?

Thanks,

Gijs

### Expected behavior

A code fix to trouble shoot this problem.

### Actual behavior

I have an error in my child theme that doesn't conflict with Woocommerce plugin in php7.4, but it does in 8.0 or up. When I deactivate Woocommerce I don't get the fatal error. Once I activate the Woo plugin my website instantly goes blanc.

### Steps to reproduce

I have deactivated all plugins, changed theme, deleted custom php code. Eventually I found out it was the combination of the child theme + Woocommerce plugin + php.8 and up.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging2.kinsta.cloud
Site address (URL): https://staging2.kinsta.cloud
WC Version: 6.9.1
REST API Version: ✔ 6.9.1
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.10
PHP Version: 7.4.30
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.10-MariaDB-1:10.5.10+maria~focal
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.1
WC Database Prefix: wp_
Totale databasegrootte: 510.74MB
Database datagrootte: 370.04MB
Database index grootte: 140.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.22MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 6.14MB + Index: 5.31MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.08MB + Index: 0.97MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.27MB + Index: 0.44MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_activity: Data: 200.14MB + Index: 69.53MB + Engine InnoDB
wp_bp_activity_meta: Data: 6.02MB + Index: 4.03MB + Engine InnoDB
wp_bp_friends: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_groups: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_groups_groupmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_bp_groups_members: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_bp_messages_messages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_messages_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_messages_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_messages_recipients: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_optouts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 4.20MB + Index: 2.36MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_FmeCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_cc_consentlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents: Data: 6.50MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_libraries: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_user_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_counters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries: Data: 0.48MB + Index: 0.03MB + Engine InnoDB
wp_h5p_libraries_cachedassets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries_hub_cache: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_h5p_libraries_languages: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries_libraries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_h5p_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_tmpfiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.34MB + Index: 0.34MB + Engine InnoDB
wp_p2p: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_p2pmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pmpro_membership_levelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pms_payments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 56.56MB + Index: 40.88MB + Engine InnoDB
wp_posts: Data: 28.31MB + Index: 4.91MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_fields: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rm_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_front_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_paypal_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_sent_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_sessions: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rm_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_submission_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rm_tasks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 14.02MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_weu_group27: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_weu_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_weu_unsubscriber: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_weu_user_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfConfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfLogins: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 4.31MB + Index: 1.58MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

achievement-type: 2
attachment: 757
audiolist: 8
audioplayer: 9
aw_workflow: 1
badgeos-log-entry: 358
badges: 1
bnfw_notification: 1
bp-email: 102
bpptc_profile_tab: 1
certificate: 2
course: 83
course-card: 2
course-layout: 2
custom-css-js: 2
customize_changeset: 184
elementor_library: 4
flamingo_contact: 3981
flamingo_inbound: 574
forum: 58
group-card: 2
group-layout: 2
language_switcher: 2
learningpath: 2
lmsbadge: 2
nav_menu_item: 130
oembed_cache: 6
page: 147
pms-subscription: 1
post: 38
postman_sent_mail: 1
product: 5
product_variation: 5
question: 20
quiz: 383
reply: 31
revision: 1329
shop_coupon: 70
shop_order: 2760
shop_order_refund: 2
step: 1
topic: 28
unit: 168
user_request: 9
wc_membership_plan: 1
wc_user_membership: 5
wppb-epf-cpt: 1
wppb-rf-cpt: 1
wppb-ul-cpt: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

PDF Embedder Premium: door PDF Embedder Team – 5.0.2
Ultimate Addons for WPBakery Page Builder: door Brainstorm Force – 3.19.11
Booster Plus for WooCommerce: door Pluggabl LLC – 5.6.0
BuddyPress: door De BuddyPress Community – 10.4.0
Classic Editor: door WordPress Contributors – 1.6.2
Elementor Pro: door Elementor.com – 3.7.5
Elementor: door Elementor.com – 3.7.4
GDPR Cookie Compliance: door Moove Agency – 4.8.12
H5P: door Joubel – 1.15.4
H5P Mods: door H5P – 0.0.1
Html5 Audio Player PRO: door bPlugins – 2.2.10
Imagify: door Imagify - Optimize Images & Convert WebP – 2.0
WPBakery Page Builder: door Michael M - WPBakery.com – 6.9.0
Loco Translate: door Tim Whitlock – 2.6.2
Mollie-betalingen voor WooCommerce: door Mollie – 7.3.1
User Switching: door John Blackbourn & contributors – 1.7.0
VibeBP: door VibeThemes – 1.8.9.2
WooCommerce Memberships: door SkyVerge – 1.23.1
WooCommerce Smart Coupons: door StoreApps – 6.1.1
WooCommerce: door Automattic – 6.9.1 (update naar versie 6.9.2 is beschikbaar)
Yoast SEO: door Team Yoast – 19.6.1
Button Color Customizer for WPBakery Composer: door Greenville Webworks – 1.0
WPLMS Batches: door Vibethemes – 4.9
WPLMS Course Custom Nav Plugin: door VibeThemes – 1.5.1
WPLMS Custom Learning Paths: door Vibethemes – 1.4
WPLMS Customizer Plugin: door VibeThemes – 1.0
WPLMS H5p custom: door VibeThemes,alexhal – 1.3
WPLMS woocommerce membership addon: door VibeThemes,alexhal – 1.0
WPLMS WooCommerce: door Mr.Vibe – 1.8
WPLMS: door VibeThemes – 1.8.9.3

### Inactive Plugins (14) ###

BuddyCommerce: door BuddyDev – 1.0.5
Conditional Checkout Fields for WooCommerce: door FME Addons – 1.2.0
Disable Cart Fragments: door LittleBizzy – 1.3.0
Disable WooCommerce Admin: door  – 1.0
GDPR Cookie Compliance - Premium Add-On: door Moove Agency – 3.3.2
Hover Effects Pack: door borisolhor – 2.6.2
Logout clear cookies: door Joel Hardi – 0.2
Query Monitor: door John Blackbourn – 3.10.1
Site Kit by Google: door Google – 1.83.0
WooCommerce Checkout Field Editor: door WooCommerce – 1.7.4
WP Bulk Delete: door Xylus Themes – 1.2.2
WPLMS Assignments: door VibeThemes – 3.9.9.2
WPLMS H5p Plugin: door VibeThemes,alexhal – 2.3
WPS Hide Login: door WPServeur
NicolasKulka
wpformation – 1.9.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: door Kinsta Team – 2.4.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
registrations (registrations)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Winkelbasis: #2002 - /winkel/
Winkelmand: #120 - /cart/
Afrekenen: #118 - /checkout/
Mijn account: #781 - /mijn-abonnement/
Algemene voorwaarden: #2008 - /algemene-voorwaarden/

### Theme ###

Name: MetMeesterGijs
Version: 21102019/
Author URL: http://www.gijspalsrok.nl
Child Theme: ✔
Parent Theme Name: WPLMS
Parent Theme Version: 4.400
Parent Theme Author URL: http://www.VibeThemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: wplms/woocommerce/archive-product.php
wplms/woocommerce/cart/cart.php
wplms/woocommerce/checkout/form-checkout.php
wplms/woocommerce/content-product.php
wplms/woocommerce/content-single-product.php
metmeestergijs/woocommerce/emails/admin-new-order.php
metmeestergijs/woocommerce/emails/customer-completed-order.php
metmeestergijs/woocommerce/emails/customer-new-account.php
wplms/woocommerce/single-product/short-description.php
wplms/woocommerce/single-product/title.php
wplms/woocommerce/single-product.php

### Memberships ###

Restriction mode:: Hide content only
Public content:: Pagina's: 1 item
Excluded from discounts:: –
Membership plans:: 1
abonnement:: Members: 5Access method: Product(s) purchaseAccess length: Specific length (1 years)

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-16 19:56:49 +02:00
Options: ✔
Notes: 87
Onboarding: completed

### Action Scheduler ###

Geannuleerd: 21
Oldest: 2022-09-16 21:47:15 +0200
Newest: 2028-03-09 20:57:19 +0100

Afgerond: 2.382
Oldest: 2022-08-17 10:53:02 +0200
Newest: 2022-09-16 21:47:16 +0200

Mislukt: 137
Oldest: 2021-01-13 09:24:57 +0100
Newest: 2021-01-20 08:57:40 +0100

In afwachting: 9
Oldest: 2022-09-17 21:37:33 +0200
Newest: 2025-01-11 00:00:00 +0100

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: 
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: 
Combine emails: 
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: yes
Rounding: no
Display prices in the shop: incl
Display prices during cart and checkout: incl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2022-09-16 22:15:46 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by meestergijs** [comment]
I found the solution. In my function.php file I had these lines that I had to delete to make it work. Unbelievable!

add_filter( 'woocommerce_admin_disabled', '__return_true' );
add_filter( 'woocommerce_admin_disabled', true );

**Comment by rwkyyy** [comment]
@meestergijs was about to write that I know that error and it's usually from a plugin/theme, not from core.
