### ISSUE TITLE
Weird /*! message on store page

### ISSUE THREAD

**Issue by Nikotoh** [woothemes/woocommerce#34737]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am experiencing a weird message on my store page and I cannot get rid of it. I have tried older versions and deactivating different plugins. I have tried to add this to 'custom css' but it doesn't work and I'm not familiar enough with the code to customize it to work.

"Error" message can be seen at: https://repoketo.fi/wip/unelmamuija/kauppa/
And it goes like this: 
/*! elementor – v3.7.6 – 15-09-2022 */
.elementor-column .elementor-spacer-inner{height:var(–spacer-size)}.e-container{–container-widget-width:100%}.e-container>.elementor-widget-spacer{width:var(–container-widget-width,var(–spacer-size));-ms-flex-item-align:stretch;align-self:stretch;-ms-flex-negative:0;flex-shrink:0}.e-container>.elementor-widget-spacer>.elementor-widget-container,.e-container>.elementor-widget-spacer>.elementor-widget-container>.elementor-spacer{height:100%}.e-container>.elementor-widget-spacer>.elementor-widget-container>.elementor-spacer>.elementor-spacer-inner{height:var(–container-widget-height,var(–spacer-size))}

### Expected behavior

I dont know.

### Actual behavior

A message under header displaying some custom css (I think) and I can't get rid of it.

### Steps to reproduce

1. I'm using elementor & elementor pro
2. with woocommerce
3. my store page is set via settings to this page that is linked above

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://repoketo.fi/wip/unelmamuija
Site address (URL): https://repoketo.fi/wip/unelmamuija
WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 Mt
WP Debug Mode: –
WP Cron: ✔
Language: fi
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.1.1
PHP Version: 8.0.3
PHP Post Max Size: 64 Mt
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.23
Max Upload Size: 64 Mt
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.2
WC Database Prefix: wp_
Tietokannan kokonaiskoko: 43.76MB
Tietokannan tietojen koko: 41.06MB
Tietokannan hakemiston koko: 2.70MB
wp_woocommerce_sessions: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_api_keys: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_attribute_taxonomies: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_downloadable_product_permissions: Tiedot: 0.02MB + Indeksi: 0.06MB + Moottori InnoDB
wp_woocommerce_order_items: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_order_itemmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_tax_rates: Tiedot: 0.02MB + Indeksi: 0.06MB + Moottori InnoDB
wp_woocommerce_tax_rate_locations: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_shipping_zones: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_woocommerce_shipping_zone_locations: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_shipping_zone_methods: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_woocommerce_payment_tokens: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_payment_tokenmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_log: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_actions: Tiedot: 0.06MB + Indeksi: 0.11MB + Moottori InnoDB
wp_actionscheduler_claims: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_groups: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_logs: Tiedot: 0.06MB + Indeksi: 0.03MB + Moottori InnoDB
wp_commentmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_comments: Tiedot: 0.02MB + Indeksi: 0.08MB + Moottori InnoDB
wp_e_events: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_e_notes: Tiedot: 0.02MB + Indeksi: 0.17MB + Moottori InnoDB
wp_e_notes_users_relations: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_e_submissions: Tiedot: 0.02MB + Indeksi: 0.23MB + Moottori InnoDB
wp_e_submissions_actions_log: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_e_submissions_values: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_links: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_options: Tiedot: 3.03MB + Indeksi: 0.06MB + Moottori InnoDB
wp_postmeta: Tiedot: 23.47MB + Indeksi: 0.63MB + Moottori InnoDB
wp_posts: Tiedot: 13.50MB + Indeksi: 0.28MB + Moottori InnoDB
wp_term_relationships: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_term_taxonomy: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_termmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_terms: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_usermeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_users: Tiedot: 0.02MB + Indeksi: 0.05MB + Moottori InnoDB
wp_wc_admin_note_actions: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_admin_notes: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_category_lookup: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_customer_lookup: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_download_log: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_order_coupon_lookup: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_order_product_lookup: Tiedot: 0.02MB + Indeksi: 0.06MB + Moottori InnoDB
wp_wc_order_stats: Tiedot: 0.02MB + Indeksi: 0.05MB + Moottori InnoDB
wp_wc_order_tax_lookup: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_product_attributes_lookup: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_product_download_directories: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_product_meta_lookup: Tiedot: 0.02MB + Indeksi: 0.09MB + Moottori InnoDB
wp_wc_rate_limits: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_reserved_stock: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_tax_rate_classes: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_webhooks: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB

### Post Type Counts ###

attachment: 207
customize_changeset: 2
elementor_library: 12
nav_menu_item: 15
page: 12
post: 1
product: 29
revision: 2008
wp_global_styles: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Elementor Pro: -- Elementor.com – 3.7.6
Elementor: -- Elementor.com – 3.7.6
Spotlight - Social Media Feeds: -- RebelCode – 1.3
WooCommerce: -- Automattic – 6.9.2
StoreCustomizer: -- Kaira – 2.4.3

### Inactive Plugins (4) ###

Akismet Anti-Spam: -- Automattic – 5.0
Hello Dolly: -- Matt Mullenweg – 1.7.2
Under Construction: -- WebFactory Ltd – 3.93
WP File Manager: -- mndpsingh287 – 7.1.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Kaupan polkutunnus: #1449 - /kauppa/
Ostoskori: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Kassa: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
Oma tili: #9 - /oma-tili/
Tilaus- ja sopimusehdot: ❌ Sivua ei ole asetettu

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Suositus: jos muokkaat WooCommercen isäntäteemaa jota et itse ole tehnyt
suosittelemme käyttämään lapsiteemaa. Katso: Kuinka luodaan lapsiteema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-20 11:44:04 +03:00
Options: ✔
Notes: 36
Onboarding: skipped

### Action Scheduler ###

Valmis: 104
Oldest: 2022-08-20 18:53:02 +0300
Newest: 2022-09-19 20:28:58 +0300

Odottaa: 1
Oldest: 2022-09-20 06:28:05 +0300
Newest: 2022-09-20 06:28:05 +0300

### Status report information ###

Generated at: 2022-09-19 20:29:27 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi @Nikotoh it appears some CSS from Elementor is getting printed to the page. I'm not sure why that would be happening. Have you tried disabling Elementor?

**Comment by Nikotoh** [comment]
Hi @psealock I have tried disabling Elementor and the problem still remains.

**Comment by jonathansadowski** [comment]
Hi @Nikotoh,

I noticed that you might have several other plugins active, and you're using a theme other than a default WordPress theme or [Storefront](https://woocommerce.com/storefront/). I just wanted to confirm, can you reproduce this with **only** WooCommerce and a WordPress theme or Storefront active?
