### ISSUE TITLE
[Enhancement]: Suppress `Coupon management has moved` Note

### ISSUE THREAD

**Issue by PanosSynetos** [woothemes/woocommerce#34731]
### Describe the solution you'd like

The note to inform users that the coupons have moved, takes up space and introduces unnecessary friction (especially for new users). 

The same goes for the “duplicate” menu item, one under **WooCommerce** and the other under **Marketing**.

### Additional context

For reference, see 

- https://github.com/Automattic/wc-calypso-bridge/issues/809
- https://github.com/Automattic/wc-calypso-bridge/pull/810

**Comment by adrianduffell** [comment]
As a significant amount of time has now passed, [this note](https://github.com/woocommerce/woocommerce/blob/aed63a9797b6311cc2b066d35a6f1cab92479444/plugins/woocommerce/src/Internal/Admin/Notes/CouponPageMoved.php) could now be removed. We will need to ensure the legacy menu item is not shown to new sites (WP option `wc_admin_show_legacy_coupon_menu`).
