### ISSUE TITLE
Add milestone to PRs based on paths

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#34767]
Currently our automated workflow is to add milestones to PRs when it also contains the label `plugins: woocommerce`. However this can sometimes be missed if the PR does not contain this label and gets merged [for example](https://github.com/woocommerce/woocommerce/pull/34382). 

The [workflow](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pull-request-post-merge-processing.yml) had an initial acceptance criteria set [here](36-gh-woocommerce/platform-private). I believe it was so that other items in the monorepo such as tools does not get picked up as a release PR.

The better solution "if possible" perhaps is to exclude the paths that are not going into WooCommerce release. For example https://github.com/woocommerce/woocommerce/tree/trunk/tools

Acceptance criteria:
* Add milestone to PRs only if the PR contains work that goes into the WooCommerce release.

**Comment by roykho** [comment]
Update: We've removed the `plugins: woocommerce` label check for now so we don't miss anymore PRs without milestones. Ref https://github.com/woocommerce/woocommerce/pull/34820

**Comment by psealock** [comment]
@roykho Is the update above a sufficient solution to close this issue?

**Comment by roykho** [comment]
@psealock - Yeah I believe we still need to implement this especially as we add more and more plugins/tools into our monorepo in the future. Right now if you wanted to know all the issues/PRs that have 7.0 milestone, it would pull up many that are not related to the WooCommerce release and you would have to manually prune those from the list which makes it more tedious.

**Comment by lsinger** [comment]
Related note from @tammullen: 

> I notice WooCommerce Beta Tester PRs get assigned a WooCommerce Core milestone ([example](https://github.com/woocommerce/woocommerce/pull/36072)). Is it possible to exclude them?

**Comment by lsinger** [comment]
PR is here: https://github.com/woocommerce/woocommerce/pull/36897
