### ISSUE TITLE
Orders not getting refunded with custom order tables (HPOS).

### ISSUE THREAD

**Issue by kudaleganesh** [woothemes/woocommerce#34761]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While testing the HPOS I found that orders created WooCommerce Custom Order Table (HPOS) are not getting refunded.
I tried with the Stripe payment gateway and redunding the order through stripe itself.
After debugging more found the below fatal error.

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore::persist_order_to_db() must be an instance of WC_Order, object given, called in \app\public\wp-content\plugins\woocommerce\src\Internal\DataStores\Orders\OrdersTableDataStore.php on line 1822 and defined in \app\public\wp-content\plugins\woocommerce\src\Internal\DataStores\Orders\OrdersTableDataStore.php:1433

### Expected behavior

The order should be refunded succesfully.successfully

### Actual behavior

The order is not getting redunded and loader loads continuously.

### Steps to reproduce

1. Opt in the HPOS option.
2. Create a WooCommerce order through the official stripe payment gateway.
3.  Go to WooCommerce > Order > one of the order and Click on Refund.
4. Enter the amont and click on the button which refund the amount using payment gateway. ( Refund via Stripe )

### WordPress Environment

WooCommerce version: Version 7.0.0-hpos.dev.1
WordPress Version: 6.0.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @kudaleganesh,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 6.9.3 version and WordPress 6.0.2 version. 

Please find below the screenshot for reference :


![#34761](https://user-images.githubusercontent.com/94531721/191989394-ca0ed1c3-a056-4402-b0b9-9d3dd98855fe.jpg)


Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by kudaleganesh** [comment]
@swatipawarGS It is not with the WooCommerce 6.9.3, it's with the **WooCommerce Custom order table ( HPOS ) 7.0.0-hpos.dev.1**

**Comment by kudaleganesh** [comment]
Even though refund is not working for COD with **WooCommerce Custom order table ( HPOS ) 7.0.0-hpos.dev.1.** Below is the screencast for it.
- [Screencast](https://www.awesomescreenshot.com/video/11312139?key=cf4d69d27584194465beb51cd5339e73)

**Comment by kudaleganesh** [comment]
@swatipawarGS I have tested it with WooCommerce Version 7.0.0-hpos.dev.4 and it is not working yet.
Note: The order is created after enabling the HPOS.

**Comment by psealock** [comment]
I've re-labelled this `status:developer reproduction`. Hopefully this helps get this reproduced

**Comment by kudaleganesh** [comment]
@psealock This issue is fixed in 7.0.0-hpos.dev.6 
https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table

**Comment by psealock** [comment]
>@psealock This issue is fixed in 7.0.0-hpos.dev.6

Great, thanks for writing up the ticket. Is it safe to close?

**Comment by kudaleganesh** [comment]
> > @psealock This issue is fixed in 7.0.0-hpos.dev.6
> 
> Great, thanks for writing up the ticket. Is it safe to close?

Yes.
