### ISSUE TITLE
Fatal error while activating WooCommerce 7.0.0-hpos.dev.1

### ISSUE THREAD

**Issue by kudaleganesh** [woothemes/woocommerce#34776]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While activating the WooCommerce 7.0.0-hpos.dev.1 on the new site got the error.

Here is the error:
```PHP Fatal error:  Uncaught Error: Class 'Automattic\WooCommerce\Admin\Features\Analytics' not found in /wp-content/plugins/woocommerce/src/Internal/Features/FeaturesController.php:312```

### Expected behavior

The plugin must activate successfully.

### Actual behavior

The plugin is not activated. After a second try, it is activated but not showing the WooCommerce menu.

### Steps to reproduce

Below is the video to reproduce the issue.
- https://www.awesomescreenshot.com/video/11245510?key=bdb2db6b16d242b4a13964263a0ecb6c

### WordPress Environment

WordPress Version 6.0.2
WooCommerce Version 7.0.0-hpos.dev.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @kudaleganesh, the latest test package, `7.0.0-hpos.dev.4`, has a fix for this issue.
