### ISSUE TITLE
`wc_customer_bought_product` function is not compatible with WooCommerce (Custom Order Tables) HPOS. 

### ISSUE THREAD

**Issue by kudaleganesh** [woothemes/woocommerce#34775]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `wc_customer_bought_product` function query is not updated with respect to the custom order table. It is still using the post and post_meta table to get the orders. Hence it returns an incorrect result.

### Expected behavior

It should take the order from the post or custom order table based on the HPOS opt-in option.
As mentioned below.
https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#detecting-whether-hpos-tables-are-being-used-in-the-store

### Actual behavior

It is taking the order from the post and post_meta tables irrespective of the HPOS opt-in option and returns the wrong result.

### Steps to reproduce

I have used this function in custom code. You will get it once you check the definition of the `wc_customer_bought_product` function.

### WordPress Environment

WordPress version: 6.0.2
WooCommerce version: 7.0.0-hpos.dev.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @kudaleganesh, you are absolutely right, this function should be using the new tables when the feature is active. Thanks!
