### ISSUE TITLE
The ellipsis dropdown menu is mostly hidden within the task list

### ISSUE THREAD

**Issue by jbordonado** [woothemes/woocommerce#34780]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In WooCommerce Payments, we display a task list in Payments > Overview, using [`CollapsibleList`](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/experimental/src/experimental-list/collapsible-list/index.tsx) and [`TaskItem`](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/experimental/src/experimental-list/task-item/index.tsx) from '@woocommerce/experimental' (see [here](https://github.com/Automattic/woocommerce-payments/blob/0b2030b7a99210461f5a3a35b97f9400a3a1654c/client/overview/task-list/index.js#L177-L219));

We noticed that the dismiss action from the ellipses menu gets cut off when we open it. The text is not readable and it's impossible to dismiss the task (see the issue raised: https://github.com/Automattic/woocommerce-payments/issues/4470).
This is only happening when the Gutenberg plugin is also installed. Gutenberg comes with `@wordpress/components` v20.0.0 and WooCommerce Payments bundles v11.1.5, so once Gutenberg is installed, the site is using v20.0.0.

![Screen Recording 7-21-2022 at 8 45 PM](https://user-images.githubusercontent.com/5121465/180345688-ef7d402b-499e-4ee1-a438-9a727309f0e8.gif)

The same behavior can be observed in the TaskList StoryBook: https://woocommerce.github.io/woocommerce-admin/components/storybook/?path=/story/woocommerce-admin-experimental-list--task-item-example

It looks like this is due to a change in how the ellipsis menu is built in `@wordpress/components`. There used to be a `position: fixed` on one of the `<div>` from the ellipsis menu (v11.1.5), and I can see now that it uses `position: absolute`. 
And the TaskItem defines a class with an `overflow: hidden` rule (see [here](https://github.com/woocommerce/woocommerce/blob/ea6a0d31f999a60f99b3625071b860476255629a/plugins/woocommerce-admin/client/tasks/task-list.scss#L2)), which now affects the absolute positioned div from the menu (while it had no effects on it when it was fixed).

![image](https://user-images.githubusercontent.com/28830738/191742281-e796e546-5ce6-4e8f-a271-201730f20c67.png)

We may just need to remove the `position: relative` on `woocommerce-experimental-list__item` and move it one level up, to avoid having the absolute div relatively positioned to the element with hidden overflow.

### Expected behavior

When clicking on the ellipsis menu from a task, we can see the content and dismiss the task.

### Actual behavior

When clicking on the ellipsis menu from a task, we cannot see the content and dismiss the task.

### Steps to reproduce

1. Go to https://woocommerce.github.io/woocommerce-admin/components/storybook/?path=/story/woocommerce-admin-experimental-list--task-item-example
2. Click on the ellipsis menu and observe that the content cannot be seen properly

### WordPress Environment

`@wordpress/components` 20.0.0
`@woocommerce/experimental` 2.1.0 (also tried on 3.2.0, same problem)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Close by https://github.com/woocommerce/woocommerce/pull/35949
