### ISSUE TITLE
404 on wp-includes/js/dist/ JS scripts after WC>=6.9.0 update on bedrock structure

### ISSUE THREAD

**Issue by webaxones** [woothemes/woocommerce#34786]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

- PHP 8.0.21
- Bedrock project structure
- WooCommerce 6.8.2  

Update to WooCommerce 6.9.0 or later  
then go edit a post and check the console:

![image](https://user-images.githubusercontent.com/17084006/191816135-badd1574-a609-4124-bd0f-42560a8158ed.png)
![image](https://user-images.githubusercontent.com/17084006/191816434-7cbbfd97-4e34-48c8-b8ce-2f051fe1da1d.png)

Files are still in the folder.
We can see that /wp/ is missing. Something is retrieving the bad URL:
![image](https://user-images.githubusercontent.com/17084006/191820338-85fdb901-fae2-4c1f-af01-1eb4798bd5ef.png)

Does the same with 6.9.1, 6.9.2, 6.9.3
I tried several times with new installations.

### Expected behavior

No bug

### Actual behavior

Bug

### Steps to reproduce

Read above

### WordPress Environment

[Bedrock structure](https://roots.io/bedrock/)
PHP 8.0.21

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by beaulebens** [comment]
Related: [woocommerce-blocks/issues/6186](https://github.com/woocommerce/woocommerce-blocks/issues/6186)

Seems to be specific to sub-directory installs.

**Comment by beaulebens** [comment]
@webaxones what version of WordPress are you running?

**Comment by webaxones** [comment]
WordPress 6.0.2

**Comment by beaulebens** [comment]
Observation: If I have the Gutenberg plugin installed and active, these errors go away.

**Comment by voxoff79** [comment]
I installed Gutenberg plugin. Now i have less errors but still having 404 in this files:

wp-includes/js/dist/vendor/regenerator-runtime.min.js/?ver=0.13.9 
wp-includes/js/dist/vendor/wp-polyfill.min.js/?ver=3.15.0 
wp-includes/js/dist/vendor/lodash.min.js/?ver=4.17.19

**Comment by ralucaStan** [comment]
This issue is coming from the Cart and Checkout Blocks and has been fixed in this PR https://github.com/woocommerce/woocommerce-blocks/pull/7211. We are working on releasing the fix ASAP.

**Comment by jonathansadowski** [comment]
Thanks for the report, I'm closing this as it was fixed in WooCommerce Core in #34814.
