### ISSUE TITLE
Mobile App Magic Link Feature: premature success message

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#34796]
When there’s an error with sending the magic link, we already show We just sent you the magic link which I think is premature. There’s a toast message to let users know it erred, but this could also confuse some users. I think having a loading indicator and showing success/failure in modal would be a great improvement.

If possible, we’d add a loading state to the ✨️ Send the sign-in link button, much like in the Jetpack installation step.

![image](https://user-images.githubusercontent.com/27843274/191898944-55cec699-b548-4072-bef9-6add309552c5.png)

**Comment by ilyasfoo** [comment]
Thanks for making the issue, @rjchow! I'd also like to add the suggestion by Jarek here: pbIJXs-2A7-p2#comment-5113
