### ISSUE TITLE
Subdivisions Missing for Ukraine in states.php file

### ISSUE THREAD

**Issue by CGA8C** [woothemes/woocommerce#34803]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Ukraine is missing 3 subdivisions, Kyiv, Sevastopol, and the Autonomous Republic of Crimea, according to https://en.wikipedia.org/wiki/ISO_3166-2:UA and https://www.iso.org/obp/ui/#iso:code:3166:UA. 

### Expected behavior

Kyiv, Sevastopol, and the Autonomous Republic of Crimea should appear along with the existing Oblasts, since they do not fall under these subdivisions. 

### Actual behavior

Currently, these 3 subdivisions are missing from the states.php file. 

### Steps to reproduce

Ukrainian Subdivisions can be found starting on line 1795 of states.php

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/states.php#L1795

### WordPress Environment

<details>
<summary>
### WordPress Environment
</summary>
`
### WordPress Environment ###

WordPress address (URL): https://coreyswootestsite.mystagingwebsite.com
Site address (URL): https://coreyswootestsite.mystagingwebsite.com
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.83.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: wp_
Total Database Size: 36.16MB
Database Data Size: 23.11MB
Database Index Size: 13.05MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.31MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.45MB + Index: 0.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.36MB + Index: 0.27MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 9.52MB + Index: 6.95MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.45MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpstg_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2110
aw_workflow: 7
bookable_resource: 2
custom-product-type: 1
elementor_library: 1
enr_subsc_plan: 3
event_ticket: 11
jp_pay_product: 3
mailpoet_page: 1
page: 21
post: 2
product: 209
product_variation: 1294
revision: 55
shop_coupon: 4
shop_order: 78
shop_order_refund: 3
shop_subscription: 11
sm_fw_suppliers: 1
wcpd: 3
wc_booking: 3
wc_membership_plan: 2
wc_pickup_location: 3
wc_user_membership: 1
wpdesk-coupons: 4
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Jetpack: by Automattic – 11.4-a.7
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.1
WooCommerce Composite Products: by WooCommerce – 8.5.2
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0
WooCommerce Memberships: by SkyVerge – 1.23.0 (update to version 1.23.1 is available)
WooCommerce Payments: by Automattic – 4.7.2
WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Product Bundles: by WooCommerce – 6.17.0
WooCommerce Subscriptions: by WooCommerce – 4.5.1
WooCommerce: by Automattic – 6.9.3
WP Mail Logging: by Wysija – 1.10.4

### Inactive Plugins (74) ###

Affiliate For WooCommerce: by StoreApps – 4.11.0 (update to version 5.4.0 is available)
Akismet Anti-Spam: by Automattic – 5.0
AutomateWoo: by WooCommerce – 5.5.18
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.10
Backup Duplicator & Migration - WP STAGING: by WP-STAGING
WPStagingBackup – 2.9.14

Bulk Discounts for WooCommerce: by Plugify – 1.0.5 (update to version 1.0.6 is available)
Check Conflicts: by ioannup – 1.1.4
Code Snippets: by Code Snippets Pro – 3.2.0
Creative Mail by Constant Contact: by Constant Contact – 1.5.4
Custom Product Type for WooCommerce: by Mohamed Saad – 1.2.3
Elementor: by Elementor.com – 3.6.6
Enhancer for WooCommerce Subscriptions: by FantasticPlugins – 3.4
Facebook for WooCommerce: by Facebook – 2.6.21
Featured Image from URL (FIFU): by fifu.app – 4.0.4
Flexible PDF Coupons for WooCommerce: by WP Desk – 1.5.7
Google Listings and Ads: by WooCommerce – 2.0.1
Loco Translate: by Tim Whitlock – 2.6.2
MailPoet: by MailPoet – 3.98.1
Meks Quick Plugin Disabler: by Meks – 1.0
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.24

PayU India: by PayU – 3.8.2
Paywall for WooCommerce: by TIV.NET INC – 3.5.0 (update to version 3.8.0 is available)
Pinterest for WooCommerce: by WooCommerce – 1.2.2
Product Bundles - Variation Bundles: by franticpsyx – 1.1.3
Products By Attributes & Variations for WooCommerce: by Addify – 1.4.4
Product Sold Counter: by KoalaApps – 1.0.0 (update to version 1.0.1 is available)
Quick Buy Now Button for WooCommerce: by Addify – 1.3.7 (update to version 1.3.8 is available)
Say What?: by Ademti Software – 2.0.2
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Mega Menus: by WooCommerce – 1.6.2
Storefront Powerpack: by WooCommerce – 1.6.2
Storefront Pricing Tables: by WooCommerce – 1.1.0
String Locator: by Clorith – 2.5.0
Supplier Management for Woocommerce: by P5Cure – 1.2.1
WooCommerce Additional Variation Images: by WooCommerce – 2.0.0 (update to version 2.1.0 is available)
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.15.1 (update to version 1.15.2 is available)
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.9.0
WooCommerce Amazon Fulfillment: by Never Settle – 3.3.8
WooCommerce AvaTax: by SkyVerge – 1.16.2 (update to version 1.16.3 is available)
WooCommerce Back In Stock Notifications: by WooCommerce – 1.3.2
WooCommerce Bookings: by WooCommerce – 1.15.60 (update to version 1.15.62 is available)
WooCommerce Box Office: by WooCommerce – 1.1.39 (update to version 1.1.40 is available)
WooCommerce Chained Products: by StoreApps – 2.11.0
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.6 (update to version 2.5.7 is available)
WooCommerce Custom Cancelled order for Customers: by rynald0s – 0.1
WooCommerce Drip: by WooCommerce – 1.2.30 (update to version 1.2.34 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.3 (update to version 2.6.0 is available)
WooCommerce Eway Payment Gateway: by WooCommerce – 3.4.4
WooCommerce Force Sells: by WooCommerce – 1.1.31
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.18 (update to version 2.5.0 is available)
WooCommerce Gravity Forms Product Add-Ons: by Element Stark – 3.3.26
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.12
WooCommerce Mix and Match Products: by Kathy Darling – 1.12.0 (update to version 2.1.3 is available)
WooCommerce Multi-currency: by TIV.NET INC – 2.15.5 (update to version 2.16.2 is available)
WooCommerce Nested Category Layout: by SkyVerge – 1.17.4
WooCommerce Ninja Forms Product Add-Ons: by WooThemes – 1.3 (update to version 1.4 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.4.0 (update to version 1.5.1 is available)
WooCommerce Order Status Logger: by @billrobbins – 0.1
WooCommerce Points and Rewards: by WooCommerce – 1.7.12 (update to version 1.7.13 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.7.1 (update to version 1.7.3 is available)
WooCommerce Product Add-ons: by WooCommerce – 5.0.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.49
Woocommerce Product Disclaimer: by wpexperts.io – 2.6.1
WooCommerce Sales Report Email: by WooCommerce – 1.1.27 (update to version 1.1.28 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.7.1 (update to version 1.8.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce Smart Coupons: by StoreApps – 6.0.0 (update to version 6.1.1 is available)
WooCommerce Square: by WooCommerce – 3.2.0
WooCommerce Subscription Downloads: by WooCommerce – 1.3.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.40 (update to version 3.0.41 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.5.0 (update to version 4.5.1 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.44 (update to version 1.7.48 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.14.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
paywall (paywall)
simple (simple)
subscription (subscription)
test_product (test_product)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Storefront
Version: 4.1.2 (update to version 4.1.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
Free Membership Plan:: Members: 0Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
Membership Plan:: Members: 1Access method: Product(s) purchaseAccess length: Unlimited Subscription: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://coreyswootestsite.mystagingwebsite.com
Subscription Statuses: auto-draft: 1
wc-on-hold: 5
wc-cancelled: 5

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Arizona

### Subscriptions by Payment Gateway ###

Stripe: wc-cancelled: 2
wc-on-hold: 1

WooCommerce Payments: wc-cancelled: 3
wc-on-hold: 3

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal: refunds
products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Composite Products ###

Database Version: 8.5.2
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.17.0
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-24 09:59:21 +03:00
Options: ✔
Notes: 79
Onboarding: completed

### WooCommerce Payments ###

Version: 4.7.2
Connected to WPCOM: Yes
Blog ID: 205502926
Account ID: acct_1KprVh2EV70dOaMM

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Complete: 1,541
Oldest: 2022-08-23 11:56:54 +0000
Newest: 2022-09-23 11:15:28 +0000

Pending: 7
Oldest: 2022-09-23 11:17:28 +0000
Newest: 2022-10-22 13:11:00 +0000

Failed: 18
Oldest: 2022-07-06 13:53:23 +0000
Newest: 2022-08-20 13:13:49 +0000

Canceled: 1
Oldest: 2022-09-06 11:06:39 +0000
Newest: 2022-09-06 11:06:39 +0000

### Status report information ###

Generated at: 2022-09-23 14:17:31 +03:00
`
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by CGA8C** [comment]
Reported in ZD-5570685

**Comment by WMspace** [comment]
All regions according to the Constitution of Ukraine are present in **ISO 3166-1** codes:
ISO 3166-2:UA - https://en.wikipedia.org/wiki/ISO_3166-2:UA

**UA-43 Avtonomna Respublika Krym
UA-30 Kyiv city
UA-40 Sevastopol city**

My only request was to add them to the /i18n/ststes.php file WooCommerce plugin.

_The absence of these regions is nothing else than the recognition of the possibility for Russia to establish the right of possession of the territories of the independent state of Ukraine by terror._
