### ISSUE TITLE
undefined function wc_get_container() error during uninstall 

### ISSUE THREAD

**Issue by streamworksaudio** [woothemes/woocommerce#34824]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When trying to uninstall WooCommerce when the define( 'WC_REMOVE_ALL_DATA', true ); is set in wp-config.php results in an Fatel Error saying the function wc_get_container() does not exist. 

PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_container() in /../wp-content/plugins/woocommerce/includes/class-wc-install.php:1465

 

### Expected behavior

Expect WooCommerce to uninstall and remove all data.

### Actual behavior

Deleting the plugin throws a PHP that the function wc_get_container() is undefined.

### Steps to reproduce

Deactivate WooCommerce plugin
Add 'define( 'WC_REMOVE_ALL_DATA', true );' to the wp-config.php
delete the woocommerce plugin.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://streamworksaudio.local
Site address (URL): https://streamworksaudio.local
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: wp_
Total Database Size: 71.46MB
Database Data Size: 36.27MB
Database Index Size: 35.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 1.52MB + Index: 2.23MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.38MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.69MB + Engine InnoDB
wp_fc_campaign_emails: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_fc_campaign_url_metrics: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_fc_campaigns: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_fc_contact_relation_items: Data: 0.41MB + Index: 0.66MB + Engine InnoDB
wp_fc_contact_relations: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_fc_funnel_metrics: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_sequences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_sequence_tracker: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_meta: Data: 0.23MB + Index: 0.19MB + Engine InnoDB
wp_fc_subscriber_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_pivot: Data: 0.30MB + Index: 0.36MB + Engine InnoDB
wp_fc_subscribers: Data: 0.34MB + Index: 0.28MB + Engine InnoDB
wp_fc_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_url_stores: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 13.52MB + Index: 16.06MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
wp_users: Data: 0.30MB + Index: 0.30MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.47MB + Index: 0.52MB + Engine InnoDB
wp_wc_order_stats: Data: 0.39MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
creator-content: 29
creator-course: 3
custom_css: 1
customize_changeset: 2
download: 49
instructor: 8
knowledgebase: 11
nav_menu_item: 10
oembed_cache: 3
page: 4
post: 1
product: 58
revision: 41
shop_order: 3413
shop_order_refund: 22
user_request: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Code Snippets: by Code Snippets Pro – 3.2.0
FluentCRM - Marketing Automation For WordPress: by Newsletter Team by Fluent CRM – 2.5.95
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.0
FluentCRM Pro: by Fluent CRM – 2.5.95
Streamworks Audio: by Chris Hawkins – 5.6.8
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce: by Automattic – 6.9.3

### Inactive Plugins (2) ###

WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Streamworks Audio
Version: 1.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-25 01:45:43 -07:00
Options: ✔
Notes: 31
Onboarding: completed

### Action Scheduler ###

Complete: 86
Oldest: 2022-08-10 18:05:38 -0700
Newest: 2022-09-23 18:54:27 -0700

Pending: 4
Oldest: 2022-09-23 18:54:28 -0700
Newest: 2022-09-30 18:54:05 -0700

### Status report information ###

Generated at: 2022-09-23 18:54:29 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Hi, thanks for reporting the issue. 

This should be fixed in the October release (WC 7.0) via https://github.com/woocommerce/woocommerce/pull/34469.
