### ISSUE TITLE
[Enhancement]: Remove usage of "putenv"

### ISSUE THREAD

**Issue by koellich** [woothemes/woocommerce#34825]
### Describe the solution you'd like

My client uses raidboxes.io as a hoster. There, they seem to blacklist PHP's putenv-function for PHP8.0+

I'm getting the following error when trying to use PHP 8.0+:

2022/09/24 10:13:03 [error] 17175#17175: *604546 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function putenv() in /home/wp/disk/wordpress/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images-request.php:37
thrown in /h" while reading response header from upstream, client: [REDACTED], server: [REDACTED], request: "POST /?wc-ajax=get_refreshed_fragments HTTP/2.0", upstream: "fastcgi://unix:/var/run/wordpress.php-fpm.sock:", host: "[REDACTED]", referrer: "[REDACTED]"
#9 {main}
#8 /home/wp/disk/wordpress/index.php(17): require('/home/wp/disk/w...')
#7 /home/wp/disk/wordpress/wp-blog-header.php(13): require_once('/home/wp/disk/w...')
#6 /home/wp/disk/wordpress/wp-load.php(50): require_once('/home/wp/disk/w...')
#5 /home/wp/disk/wordpress/wp-config.php(63): require_once('/home/wp/disk/w...')
#4 /home/wp/disk/wordpress/wp-settings.php(599): do_action()

This issue forces me to keep using PHP 7.4 which won't be recieving security updates anymore in the near future.
I'm assuming that my hoster blocks putenv for good reasons, so this is to kindly request that you fix woocommerce such that it doesn't rely on putenv. Thanks.

### Describe alternatives you've considered

For now: reaching out to my hoster to whitelist putenv. But this can only be a temporary solution.

**Comment by masteradhoc** [comment]
+1

**Comment by barryhughes** [comment]
This should now be solved (see [this change](https://github.com/woocommerce/woocommerce/pull/35339), which shipped in 7.4.0).
