### ISSUE TITLE
Thrive/Woocommerce purchase triggers several ActiveCampaing automations in stead of the one associated with the bought product

### ISSUE THREAD

**Issue by FionaStudio505** [woothemes/woocommerce#34830]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using Thrive Theme Builder Shapeshift with Thrive Apprentice and WooCommerce linked to ActiveCampaign and am encountering the following:

if someone registers for one of my trainings, that person will receive the ActiveCampaign emails for all 3 trainings. (I tested this live with an amount of 1 euro)

Fortunately, it is true that the person then only has access to the purchased training, but you can imagine how confusing it is to receive 3 welcome emails for 3 training sessions plus 3 intro lessons. The same also happens when I manually register people.

### Expected behavior

People are subscribed to only the ActiveCampaign automation associated with the product they buy, this is linked via the Thrive automator

### Actual behavior

People are subscribed to ALL the ActiveCampaign automations associated with ALL WooCommerce products that I offer 

### Steps to reproduce

Go to https://souldetectives-selfhealingspace.nl/product/liefdevol-zelfstandig/
Buy it
You will receive 1 account email, 1 email with the invoice (both from WooCommerce) and then 3x the welcome email and 3x the introlesson as per the 3 automations in ActiveCampaign linked to all three Woocommerce products that I have in my shop

With regards to the last question with the 3 checkboxes: I cannot deactivate the Thrive plugins as they contain the content and structure of my online courses, so I would not be able to check what is happening anymore with regards to access. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://souldetectives-selfhealingspace.nl
Site address (URL): https://souldetectives-selfhealingspace.nl
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.23
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.5.17-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: VQnPwIF_
Totale database grootte: 70.30MB
Database gegevens grootte: 65.25MB
Database index grootte: 5.05MB
VQnPwIF_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
VQnPwIF_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_automationmeta: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
VQnPwIF_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
VQnPwIF_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_options: Data: 5.11MB + Index: 0.09MB + Engine InnoDB
VQnPwIF_postmeta: Data: 51.22MB + Index: 1.88MB + Engine InnoDB
VQnPwIF_posts: Data: 3.42MB + Index: 0.28MB + Engine InnoDB
VQnPwIF_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_tap_error_log: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tap_limitations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tcm_email_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tcm_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_td_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_td_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_termmeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_thrive_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_thrive_reporting_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
VQnPwIF_tqb_event_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tqb_results_links: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tqb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tqb_variations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tva_bundles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tva_ipn_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tva_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_tva_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_tva_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tva_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_contact_download: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_event_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_tve_leads_form_summary: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_tve_leads_form_variations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_tve_leads_group_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_saved_group_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_split_test: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_tve_leads_split_test_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VQnPwIF_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
VQnPwIF_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VQnPwIF_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
VQnPwIF_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VQnPwIF_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VQnPwIF_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

_tcb_form_settings: 11
attachment: 188
custom_css: 1
customize_changeset: 1
mailpoet_page: 1
nav_menu_item: 3
page: 23
post: 4
product: 7
revision: 63
shop_coupon: 2
shop_order: 24
tcb_content_template: 93
tcb_symbol: 66
thrive_demo_page: 1
thrive_demo_post: 1
thrive_layout: 55
thrive_section: 9
thrive_template: 110
thrive_typography: 8
tva_chapter: 1
tva_course_overview: 11
tva_course_type: 1
tva_lesson: 83
tva_module: 21
tva_resource: 362
tva-acc-restriction: 7
tvd_content_set: 3
tvd_login_edit: 1
tve_automation: 3
tve_cond_display: 1
tve_notifications: 1
tve_saved_lp: 1
tve_user_template: 17

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

ManageWP - Worker: door GoDaddy – 4.9.14
Akismet Anti-Spam: door Automattic – 5.0
Classic Editor: door WordPress Contributors – 1.6.2
Code Snippets: door Code Snippets Pro – 3.2.0
Cookie Notice & Compliance for GDPR / CCPA: door Hu-manity.co – 2.4.0
Thrive Apprentice: door <a href="https://thrivethemes.com">Thrive Themes</a> – 4.7.1
Thrive Automator: door <a href="https://thrivethemes.com">Thrive Themes</a> – 1.4
Thrive Comments: door <a href="https://thrivethemes.com">Thrive Themes</a> – 2.11.1
Thrive Leads: door <a href="https://thrivethemes.com">Thrive Themes</a> – 3.11.1
Thrive Product Manager: door Thrive Themes – 1.3.0
Thrive Quiz Builder: door <a href="https://thrivethemes.com">Thrive Themes</a> – 3.11.1
Thrive Architect: door <a href="http://www.thrivethemes.com">Thrive Themes</a> – 3.13.1
WooCommerce Stripe Gateway: door WooCommerce – 6.7.0
WooCommerce PDF Invoices & Packing Slips: door WP Overnight – 3.1.1
WooCommerce Shipping & Tax: door WooCommerce – 1.26.3
WooCommerce: door Automattic – 6.9.3
wp_mail return-path: door Barnaby Puttick – 1.1.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Winkelbasis: #91 - /winkel/
Winkelwagen: #92 - /winkelwagen/
Afrekenen: #93 - /afrekenen/
Mijn account: #94 - /mijn-account/
Algemene voorwaarden: #223 - /algemene-voorwaarden/

### Theme ###

Name: Thrive Theme Builder
Version: 3.11.1
Author URL: 
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub-thema aan. Zie: Hoe maak je een sub-thema

WooCommerce Support: ✔

### Templates ###

Archive Template: Je thema heeft een woocommerce.php bestand. Je zult het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-25 15:40:47 +02:00
Options: ✔
Notes: 98
Onboarding: completed

### Action Scheduler ###

Afgerond: 278
Oldest: 2022-08-25 20:54:29 +0200
Newest: 2022-09-25 16:12:03 +0200

In afwachting: 2
Oldest: 2022-09-26 08:00:53 +0200
Newest: 2022-09-26 08:00:53 +0200

### Status report information ###

Generated at: 2022-09-25 17:14:30 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @FionaStudio505,

Thanks for reaching out to report this issue. It sounds like the issue might exist in one of the other plugins that you've installed. We are unable to provide support for those plugins here, as this repository is for reporting issues in WooCommerce. Please reach out to the plugin author directly for support.

I'm going to close this issue, but if you believe this is a mistake, please re-open the issue and provide steps for reproduction with all other plugins deactivated.
