### ISSUE TITLE
Order details are not showing in New Order email

### ISSUE THREAD

**Issue by pixaliastudio** [woothemes/woocommerce#34842]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since latest Woocommerce version, when I receive a new order, the email doesn`t show the order details completely.

This is a hotel website and works with YITH booking and appointment for woocommerce

### Expected behavior

The New Order email for admin and client should show the complete order details.
- product name
- reservation date
- number of nights
- number of people

It used to run like this only 2 weeks ago.

### Actual behavior

Now, the New Order email doesnt show the order details.

### Steps to reproduce

![before](https://user-images.githubusercontent.com/114446061/192388203-4f1239e3-a873-4c30-83e4-617bb380c550.jpg) > this is the before sceenshot, with everything OK. 

![after](https://user-images.githubusercontent.com/114446061/192388262-f7727bb0-b8b1-43b7-84c8-8bc392bfbc0b.jpg)
> Now, the emial template doesnt show the details. There is a thick line instead.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hotel26labrador.com
Site address (URL): https://hotel26labrador.com
WC Version: 6.9.4
REST API Version: ✔ 6.9.4
WC Blocks Version: ✔ 8.3.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.30
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.3.36-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: wp_
Tamaño total de la base de datos: 12.64MB
Tamaño de los datos de la base de datos: 10.21MB
Tamaño del índice de la base de datos: 2.43MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.11MB + Índice: 0.09MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.09MB + Índice: 0.13MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_cf7_vdata: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cf7_vdata_entry: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.05MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 3.22MB + Índice: 0.09MB + Motor InnoDB
wp_postmeta: Datos: 1.52MB + Índice: 0.30MB + Motor InnoDB
wp_posts: Datos: 3.52MB + Índice: 0.06MB + Motor InnoDB
wp_smush_dir_images: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_wc_bookings_availability: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_bookings_availabilitymeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_booking_relationships: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpr_rocket_cache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wpr_rucss_used_css: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_yith_wcbk_booking_meta_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_yith_wcbk_booking_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcbk_booking_resources: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yith_wcbk_external_bookings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcbk_logs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcbk_product_resources: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yoast_indexable: Datos: 0.22MB + Índice: 0.09MB + Motor InnoDB
wp_yoast_indexable_hierarchy: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_yoast_seo_links: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_yoast_seo_meta: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 139
custom_css: 2
gp_elements: 3
nav_menu_item: 8
oembed_cache: 1
page: 14
post: 2
product: 9
product_variation: 3
revision: 67
shop_coupon: 1
shop_order: 49
shop_order_refund: 5
wccc: 10
wp_global_styles: 1
wpcf7_contact_form: 1
yith_booking: 53
ywcbk-person-type: 2
ywcbk-search-form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

ManageWP - Worker: por GoDaddy – 4.9.14
Adminimize: por Frank Bültge – 1.11.8
Advanced CF7 DB: por Vsourz Digital – 1.9.1
Akismet Anti-Spam: por Automattic – 5.0
Contact Form 7: por Takayuki Miyoshi – 5.6.3
GDPR Cookie Consent: por WebToffee – 2.1.3
GA Google Analytics: por Jeff Starr – 20220517
GP Premium: por Tom Usborne – 2.1.2
Limit Login Attempts Reloaded: por Limit Login Attempts Reloaded – 2.25.5
LuckyWP Table of Contents: por LuckyWP – 2.1.4
Mailchimp for WooCommerce: por Mailchimp – 2.7.5
Metricool: por Metricool – 1.14
Redsys WooCommerce: por Redsys – 3.0.1
Ultimate Addons for Gutenberg: por Brainstorm Force – 1.25.6
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.22.22

WooCommerce Conditional Content: por Lucas Stark – 2.1.2
WooCommerce Google Analytics Integration: por WooCommerce – 1.5.14
WooCommerce: por Automattic – 6.9.4
Yoast SEO: por Equipo Yoast – 19.7.1
WP Comment Policy Checkbox: por Fco. J. Godoy – 0.3.2
WP Rocket: por WP Media – 3.12.0.5
Smush: por WPMU DEV – 3.11.1
YITH Booking and Appointment for WooCommerce Premium: por YITH – 4.1.0

### Inactive Plugins (1) ###

Members: por MemberPress – 3.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Funciones: por Pixalia Studio – 1.0
installatron_hide_status_test.php: por  –
ManageWP - Worker Loader: por GoDaddy –
Personalización del Admin de WordPress: por Pixalia Studio – 1.0
Personalizar Woocommerce: por Pixalia Studio – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la tienda: #20 - /habitaciones/
Carrito: #21 - /carrito/
Finalizar compra: #22 - /finalizar-compra/
Mi cuenta: #23 - /mi-cuenta/
Términos y condiciones: #900 - /terminos-condiciones/

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.1.3
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-27 11:18:07 +02:00
Options: ✔
Notes: 103
Onboarding: completed

### Action Scheduler ###

Complete: 150
Oldest: 2022-08-26 22:25:30 +0000
Newest: 2022-09-26 21:04:47 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 3
Oldest: 2022-09-27 00:00:00 +0000
Newest: 2022-09-27 15:09:53 +0000

### Status report information ###

Generated at: 2022-09-27 00:00:27 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by johndcoy** [comment]
I cannot replicate this problem using the core product types built into WooCommerce. This issue needs to be opened with YITH Booking and Appointment for WooCommerce Premium: by YITH, no WooCommerce core.

**Comment by jonathansadowski** [comment]
Hi @pixaliastudio,

Thanks for the report. As @johndcoy mentioned, unless we're able to reproduce the issue in WooCommerce Core itself, with no other plugins activated, there's nothing else that we'll be able to do. Please reach out to the authors of the plugin that you're having issues with and report the problem to them.

I'm going to close this issue, but if you think that this is a mistake, and you can provide us with a list of steps to reproduce the issue in WooCommerce alone, please feel free to open a new issue.
