### ISSUE TITLE
WordPress database error Specified key was too long; max key length is 1000 bytes for query on WAMP

### ISSUE THREAD

**Issue by PradeepTyche** [woothemes/woocommerce#34849]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WordPress database error Specified key was too long; max key length is 1000 bytes for query 

### Expected behavior

No error must be thrown while creating tables

### Actual behavior

Mysql server on Wamp throws the error
Specified key was too long; max key length is 1000 bytes for query

### Steps to reproduce

After having installed HPOS version, 
1. Go to Woocommerce >> Settings >> Advanced
enable
Enable the custom orders tables feature (still in development)

2. Then Go to Tools >> Click on 'Create' button under
Create the custom orders tables , then the following error is reported

### WordPress Environment

WAMP server 3.2.6 64 bit.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by PradeepTyche** [comment]
Go to 
\bin\mysql\mysql5.7.36\my.ini

Change
default-storage-engine=InnoDB

Add the following under
[wampmysqld64]
default-storage-engine=InnoDB
innodb-default-row-format=DYNAMIC
innodb-file-format=barracuda
innodb-file-per-table=ON
innodb-large-prefix=ON

**Comment by MichalisDBA** [comment]
The problem continues to exist with latest version 8.0.1.

First of all there is no button to create the tables manually.

Second of all, shared hosting environments do not allow you to change MySQL configuration of the server.

Please create a workaround else HPOS will not work on majority of woocommerce shops

**Comment by nqkyf** [comment]
> The problem continues to exist with latest version 8.0.1.
> 
> First of all there is no button to create the tables manually.
> 
> Second of all, shared hosting environments do not allow you to change MySQL configuration of the server.
> 
> Please create a workaround else HPOS will not work on majority of woocommerce shops

yeap he is right, we get that error on shared hostings, and the companies want us to buy vps...no way for HPOS.... woo must make changes and updates.

I cannot turn on HPOS it returs errors. Tested on 3 different shared hostings...triple times clean install...all tricks but nothing happen and cannot siwtch it on cuz cannnot make this tables with this one.

**Comment by MichalisDBA** [comment]
> > The problem continues to exist with latest version 8.0.1.
> > First of all there is no button to create the tables manually.
> > Second of all, shared hosting environments do not allow you to change MySQL configuration of the server.
> > Please create a workaround else HPOS will not work on majority of woocommerce shops
> 
> yeap he is right, we get that error on shared hostings, and the companies want us to buy vps...no way for HPOS.... woo must make changes and updates.
> 
> I cannot turn on HPOS it returs errors. Tested on 3 different shared hostings...triple times clean install...all tricks but nothing happen and cannot siwtch it on cuz cannnot make this tables with this one.

I found a solution.

Most shared hosting providers have by default MyISAM DB Engine. All your tables are MyISAM instead of InnoDB.

The workaround is to create manually the specific Woocommerce tables that have the problem with the InnoDB engine, enable HPOS and then use this plugin to convert all other tables to InnoDB.

Replace YOUR_WP_TABLE_PREFIX with your wordpress db table prefix. Usually is `wp_`

After you do that and enable HPOS, activate this plugin

https://wordpress.org/plugins/servebolt-optimizer/

and go to Performance Optimizer -> Database ->Hit Optimize button

```
CREATE TABLE YOUR_WP_TABLE_PREFIX_wc_orders (
  id bigint(20) unsigned, 
  status varchar(20) null, 
  currency varchar(10) null, 
  type varchar(20) null, 
  tax_amount decimal(26, 8) null, 
  total_amount decimal(26, 8) null, 
  customer_id bigint(20) unsigned null, 
  billing_email varchar(320) null, 
  date_created_gmt datetime null, 
  date_updated_gmt datetime null, 
  parent_order_id bigint(20) unsigned null, 
  payment_method varchar(100) null, 
  payment_method_title text null, 
  transaction_id varchar(100) null, 
  ip_address varchar(100) null, 
  user_agent text null, 
  customer_note text null, 
  PRIMARY KEY (id), 
  KEY status (status), 
  KEY date_created (date_created_gmt), 
  KEY customer_id_billing_email (customer_id, billing_email), 
  KEY billing_email (billing_email), 
  KEY type_status (type, status), 
  KEY parent_order_id (parent_order_id), 
  KEY date_updated (date_updated_gmt)
) ENGINE=InnoDB DEFAULT CHARACTER 
SET 
  utf8mb4 COLLATE utf8mb4_unicode_520_ci
```

```
CREATE TABLE YOUR_WP_TABLE_PREFIX_wc_orders_meta (
  id bigint(20) unsigned auto_increment primary key, 
  order_id bigint(20) unsigned null, 
  meta_key varchar(255), 
  meta_value text null, 
  KEY meta_key_value (
    meta_key, 
    meta_value(100)
  ), 
  KEY order_id_meta_key_meta_value (
    order_id, 
    meta_key, 
    meta_value(100)
  )
) ENGINE=InnoDB DEFAULT CHARACTER 
SET 
  utf8mb4 COLLATE utf8mb4_unicode_520_ci
```

**Comment by nqkyf** [comment]
U are the man! Works. Anyway that was my second thought but you save  me time. It's shame that they test this more than a year.

I do the Optimize from Servebolt Optimizer and db grow from 2.1MB to 4.1MB.

Can I ask you - do you see some real good results of HPOS ?

They say no more tones of meta info in postmeta from woo - will see that and db will be more fast.

Thanks again.

**Comment by MichalisDBA** [comment]
> U are the man! Works. Anyway that was my second thought but you save me time. It's shame that they test this more than a year.
> 
> I do the Optimize from Servebolt Optimizer and db grow from 2.1MB to 4.1MB.
> 
> Can I ask you - do you see some real good results of HPOS ?
> 
> They say no more tones of meta info in postmeta from woo - will see that and db will be more fast.
> 
> Thanks again.

Sadly i have not tested the newest HPOS. I have some customers with huge amount of orders BUT they have plugins that their developers haven't update them yet for the newest HPOS. Woocommerce HPOS can not be enabled yet because it says that they are incompatible plugins enabled.

**Comment by nqkyf** [comment]
WooCommerce update is here from 12.09.2023 - 8.1.0 - they fix and this problem.

Fix – Limit index length to 191 characters by default, additionally connect HPOS to verify DB tooling. [#39250](https://github.com/woocommerce/woocommerce/pull/39250)

Anyway - thanks to u I will use InnoDB instead of MyISAM for all my wordpress websites.
