### ISSUE TITLE
Schema: Review passing `priceSpecification` as well as `offers` schema, and pass `aggregateRating` as well.  

### ISSUE THREAD

**Issue by anant1811** [woothemes/woocommerce#34851]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1. Currently, we're adding `priceSpecification` and `offers` schema properties, and both of them have the "Price" values, thus each product gets price specified twice. Google's [documentation here](https://developers.google.com/search/docs/appearance/structured-data/product#pricing-example) mentions that price should only be passed once. 

This results in validation error. Removing `priceSpecification` resolves the issue. 

2. Also, currently we do pass `bestRating` and `worstRating` values, but not `aggregateRating` value. Can we consider adding the `aggregateRating` value as well? 

Reported in #5566308-zen
Slack: archives/C7U3Y3VMY/p1663512359477999

### Expected behavior

Price should only be passed once. We can also consider adding aggregateRating. 

### Actual behavior

Price is passed twice. aggregateRating is not passed. 

### Steps to reproduce

Create a product and do a schema validation: https://developers.google.com/search/docs/appearance/structured-data 

### WordPress Environment

N/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by or128** [comment]
I would like to second this, this is a major issue that can be easily addressed and fixed.

You can read about this here: https://support.google.com/webmasters/thread/180704786/pricespecification-error?hl=en-GB

**Comment by electrokit** [comment]
It's probably better to keep the `priceSpecification`, since it contains the field `valueAddedTaxIncluded`.

**Comment by darcie** [comment]
It looks like Google resolved their validation errors when a price was included for both `priceSpecification` and `offers`. This is no longer invalid when testing using their [Rich Results Test](https://search.google.com/test/rich-results). 
Additionally, their documentation here seems to indicate both are acceptable: 
https://developers.google.com/search/docs/appearance/structured-data/product#offer-details

>If you choose to use both offers.price and offers.priceSpecification properties, and there's a conflict between the two (for example, a different price or priceCurrency), Google will use the price information that's provided at the offers.price level.

As these schema properties we currently use no longer result in validation errors in Google, it's possible no changes are needed in WooCommerce.

(5621343-zen)

**Comment by electrokit** [comment]
Our validation errors are disappearing as well. This can be closed.

**Comment by vedanshujain** [comment]
Closing as per recent comments.
