### ISSUE TITLE
[PHP 7.1.x] Incompatible signature between `Container` interface and implementation

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#34886]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Because the signature for the `get()` method in our [`Container` interface](https://github.com/woocommerce/woocommerce/blob/35ede22a3d02d4ee09d7c59db3ccd1f4fda7c907/plugins/woocommerce/lib/packages/Psr/Container/ContainerInterface.php#L22) doesn't match the implementation in the [`Container` class](https://github.com/woocommerce/woocommerce/blob/35ede22a3d02d4ee09d7c59db3ccd1f4fda7c907/plugins/woocommerce/lib/packages/League/Container/Container.php#L154) (nor the [`ExtendedContainer` class](https://github.com/woocommerce/woocommerce/blob/23e237dc2ad3bfff6678dc6aff594e01e4d55631/plugins/woocommerce/src/Internal/DependencyManagement/ExtendedContainer.php#L112)), users on PHP 7.1.x might get the following fatal error when WC is activated:

> Fatal error: Declaration of Automattic\WooCommerce\Vendor\League\Container\Container::get($id, bool $new = false) must be compatible with Automattic\WooCommerce\Vendor\Psr\Container\ContainerInterface::get(string $id) in [...]/woocommerce/lib/packages/League/Container/Container.php on line 15

The interface declares `get()` receives a `string $id` while the implementations do not specify the type for `$id`. Even though the differences in the signature seem problematic, this is actually allowed in PHP 7.2.x onwards as it [doesn't break contravariance](https://www.php.net/manual/en/language.oop5.variance.php):

> [...] contravariance allows a parameter type to be less specific in a child method, than that of its parent.

Surprisingly, [PHP 7.1.x](https://onlinephp.io/c/96234) was more strict as it didn't have proper support for contravariance. PHP >= 7.2 [is ok](https://onlinephp.io/c/84cd4).

The fix seems very simple and might be worth aligning all the signatures, but we shouldn't necessarily worry too much about it because PHP 7.2 is our minimum requirement, and there's technically nothing wrong with the code as it is.

### Expected behavior

No fatal error.

### Actual behavior

Fatal error about incompatible signatures.

### Steps to reproduce

1. Enable PHP 7.1.x.
2. Activate WC 6.9.4.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by felipevelzani** [comment]
5982480-zen

**Comment by rrennick** [comment]
@jorgeatorres Closing this as I assume it's been addressed.
