### ISSUE TITLE
[Enhancement]: Load categories on demand in product editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#34885]
**Issue Description:**

This issue is a split off from #34000, to just work on the product categories widget within the product editor.

Currently all the categories are loaded/rendered in the categories widget within the Product Editor. This can potentially cause some performance issues for stores that have several thousand categories. Not only that, once you have over a hundred categories the current screen makes it hard to find the category you are looking for.

As mentioned [here](https://github.com/woocommerce/woocommerce/issues/34000#issuecomment-1252441278), we want to display the category widget in a similar format as the Product Tags widget, with an async typeahead search to search for the categories.
Currently we already have a very similar category search field on the product list page, see the **Filter by category** dropdown/typeahead.

New design:
*note that the **Categories -> Add** design could be ignored, as the **Categories -> Search** field will be easier to implement and better fits with the design (cc: @jarekmorawski  )

<img width="169" alt="Screen Shot 2022-11-30 at 11 19 21 AM" src="https://user-images.githubusercontent.com/2240960/204770500-015e18ef-db42-48ac-93a7-297881a9df87.png">
<img width="344" alt="Screen Shot 2022-11-30 at 11 19 13 AM" src="https://user-images.githubusercontent.com/2240960/204770518-9e85f56d-d9e8-4816-a75e-157498a5998d.png">

Figma: 6cBYbZmiet1l7gzc28ce8k-fi-5301%3A253895

### Acceptance criteria

- [ ] Update the **Product categories** widget within the product edit screen with the above design.
- [ ] Selected attributes should be shown below the search field, with a small 'x' to remove them (similar to **Product tags**)
- [ ] A typeahead search should be added that asynchronously searches for the categories ( see example of **Filter by category** )
- [ ] Add new category parent dropdown should be replaced with above typeahead search as well.
- [ ] Selected children should include the parent (ex: **Shoes > Hiking** )

### Additional context

Originally discussed in p7bje6-4if-p2.

**Comment by mattsherman** [comment]
@louwie17 Moving this back to "Prioritization" since it doesn't appear ready to start working on.

**Comment by louwie17** [comment]
> since it doesn't appear ready to start working on.

Why do you not think it's ready to start working on?

**Comment by joshuatf** [comment]
@louwie17 It might be good to add some more details from the p2 and GH comments to flesh out this issue along with some acceptance criteria.

Unless this is just a spike into how we do this, it might be good if we put up a potential solution or two to discuss how well they'd work.

**Comment by mattsherman** [comment]
> Why do you not think it's ready to start working on?

@louwie17 Echoing what @joshuatf said, there aren't any details or AC in this issue. We should add those before somebody starts implementing this.

**Comment by louwie17** [comment]
@jarekmorawski @pmcpinto one remaining question on this issue, should we remove the **Most used** tab or keep this? the most used tab only displays 10 or so items so this would not affect rendering or performance.
<img width="298" alt="Screen Shot 2022-11-30 at 11 21 31 AM" src="https://user-images.githubusercontent.com/2240960/204771083-9c12bf89-c4c4-4b4a-99c7-8be2718c5438.png">

**Comment by jarekmorawski** [comment]
Good question. I was planning to make that a future improvement where we'd show the 10 most used categories at the top of the list (when the field is first clicked), above other results. Unless you think we have space to work on this now?

**Comment by louwie17** [comment]
> Good question. I was planning to make that a future improvement where we'd show the 10 most used categories at the top of the list (when the field is first clicked), above other results. Unless you think we have space to work on this now?

I don't mind waiting, but if we do, I think we should keep the current form of **Most used** available, just incase this is something people use often (meaning we keep the tab functionality).
I don't want to make the same mistake as collapsing the short description, where we find out the hard way that people use this feature a lot (unless we already have tracks around this?)

**Comment by jarekmorawski** [comment]
Good point. I don't think we're currently tracking this anywhere. We definitely don't want to hinder or remove existing functionality so we could move **Most used** into the dropdown. Given the new interaction for adding categories, keeping the existing tabs would be confusing.

Do you think you could add it as part of this issue?

https://user-images.githubusercontent.com/79307566/204815915-89e47efe-9016-4b2d-add2-52bd419deb71.mov

**Comment by louwie17** [comment]
> Do you think you could add it as part of this issue?

yes that should be possible, although there might be slight chance the current select control will not like the extra headers, but I am thinking that is not very likely.

@jarekmorawski in terms of the UI though, I am a little confused on why it shows check boxes first and once a user searches it removes the check boxes? Wouldn't it be easier to never display the checkboxes?
Or are the checkboxes only for the **Most used**? It would be great to keep those consistent.

**Comment by jarekmorawski** [comment]
> Or are the checkboxes only for the Most used? It would be great to keep those consistent.

You're right, we should show checkboxes in both lists. It's an omission on my part because I don't know the old core components very well. Here's the updated video.

https://user-images.githubusercontent.com/79307566/205021667-70a6eb01-1c02-4981-9c7d-6954fed85c1a.mov

**Comment by louwie17** [comment]
> You're right, we should show checkboxes in both lists. It's an omission on my part because I don't know the old core components very well. Here's the updated video.

Thanks for updating this @jarekmorawski, although I am still slightly confused about some of the design.
When you open the dropdown first, the **Most used** list is fine, but then it shows the **All categories** list with nested items indented, but if a user searches it shows the list with nested items prefixed with the **[parent name] > **. 

I think we should either use indented for both, or use the prefixed format for both. Currently the prefixed format will be easier to support as we already have an API for that (so I would vouch for that option).
We could create a separate issue to have the API support a tree like structure that will make the indentation option easier to implement?

Final question: For the **All categories** list, do we just show the first 10 items? or is this suppose to be auto populated as the user scrolls down the list - infinite scrolling? It does appear the `select2` component supports this. The only caveat is that the current categories API used for this does not support pagination, so that would have to be added.

**Comment by jarekmorawski** [comment]
All good questions. This interaction is getting increasingly complex, making me wonder if we could reuse the new category dropdown component but style it differently so it matches the current experience? It'd probably save us a lot of effort.

If that's not possible, we can continue improving this one.

> I think we should either use indented for both or use the prefixed format for both. Currently, the prefixed format will be easier to support as we already have an API for that (so I would vouch for that option).

When you think about user jobs to be done, having an indentation in the list view makes sense because you may want to select both a parent and a child. The hierarchy would be clear because the items would be visually grouped. If we used prefixes, you'd see a list of multiple items with the same parent, making it more difficult to tell what's a parent and what's a child.

In the search view, however, accuracy is more important than hierarchy. If we used an indentation there, the user would see an irrelevant parent category if they searched for the child. For instance, if I search for `T-shirts`, should I see both `Menswear` (parent) and `T-shirts` (child)? The first may not be relevant because I'm looking for a specific subcategory. In this case, a prefix can be helpful because it gives you context and helps make sense of similar results, f.e. `Menswear > T-shirts` and `Womenswear > T-shirts`.

The list view is used for _browsing_ categories, while the search view is made for _selecting_ categories. It's a subtle difference that requires two separate approaches.

> For the All categories list, do we just show the first 10 items? or is this suppose to be auto populated as the user scrolls down the list - infinite scrolling?

Yes, the `All categories` list should load in batches on scroll–much like in the new dropdown component.

**Comment by jarekmorawski** [comment]
The compromise would be to use the checkboxes for both views and limit the results to just the parents and children that include the searched term. Here's a demo.

https://user-images.githubusercontent.com/79307566/205271168-255a6d47-83fc-4f43-be5b-44a186f555cf.mov

**Comment by pmcpinto** [comment]
> @jarekmorawski @pmcpinto one remaining question on this issue, should we remove the Most used tab or keep this? the most used tab only displays 10 or so items so this would not affect rendering or performance.

@louwie17 @jarekmorawski I think we should keep the "Most used" tab as is. I understand this can create some inconsistency, but we don't know how many users use this tab and we don't increase the scope of this issue. We can solve this later after validating that the new flow for all categories doesn't create problems.

**Comment by jarekmorawski** [comment]
This would lead to the user selecting categories in 2 different ways, which isn't good from a user experience point of view. It will also look off because if the user didn't add any categories using the dropdown, we wouldn't have anything to show in the first tab.

https://user-images.githubusercontent.com/79307566/206477947-a8e96872-349f-4bfc-8e67-91f4d90fb5e9.mov

**Comment by pmcpinto** [comment]
@louwie17 what's the limit of categories displayed in the "must used" tab?

**Comment by louwie17** [comment]
> @louwie17 what's the limit of categories displayed in the "must used" tab?

Sorry for the late reply @pmcpinto, the max it will show in the "most used" is 10.

**Comment by louwie17** [comment]
> This would lead to the user selecting categories in 2 different ways, which isn't good from a user experience point of view. It will also look off because if the user didn't add any categories using the dropdown, we wouldn't have anything to show in the first tab.

That makes sense, although the above video you shared doesn't look to bad. But I would be good with including it within the dropdown as well. The dropdown is just slightly less intuitive as the list with the checkboxes.

**Comment by pmcpinto** [comment]
@louwie17 @jarekmorawski I think that changing the category selection flow and merging it with the most used tabs at the same time is too risky. I think we should change the category selection flow and keep the most used tab as is for now. They can be merged 1-2 releases after we release the new category selection flow.

@louwie17 how much time do you need to implement this?

**Comment by louwie17** [comment]
> @louwie17 how much time do you need to implement this?

I don't think it should take a huge amount of time, maybe two days. Let me see what I can put together in these last two days of porter rotation.

**Comment by louwie17** [comment]
@pmcpinto slight update on this, I have put a couple day's into this now and might require a couple more day's. This is proving to be a bit more difficult then I expected as the categories metabox relies on WordPress core code that I am less familiar with.
I am checking with the team for some more insight, but otherwise I would question the value of this versus the development effort. Especially as we look at upgrading to the new product editor at some point in the future.

I also came to realize that creating a tree control with the JQuery select2 dropdown (used in the classic editor for most dropdowns) is a bit tedious, so I was going to propose make use of our internal React tree control, either the one made by @mdperez86 or this one (pdkevu-kA-p2 ) made by the ventures team.
