### ISSUE TITLE
`customers` REST API endpoint is throwing a `500 internal server error` or a fatal error when the customer was created via WP CLI

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#34894]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Recently, the `checkout-login.spec.js` e2e test is failing on `trunk` because it's getting a `500 internal server error` when it tries to update the billing address of our test customer "Jane Smith", a customer that's created via WP CLI in our local e2e setup scripts, using the `PUT /customers/<id>` endpoint.

Upon digging a bit more, I noticed that the `GET customers` and `PUT customers` endpoints throw the `500 internal server error` when:
- the `GET /customers` endpoint is expected to return a list of customers where at least one of them was created via WP CLI
- the `PUT /customers/<id>` endpoint tries to update a customer that was created via WP CLI. It doesn't throw a 500 error when it's updating a customer created via REST API or the UI.

I broke down the reproduction steps into several sections.

### Expected behavior

1. The `GET /customers` endpoint doesn't throw a 500 error when one of the customers was created via WP CLI.
2. The `PUT /customers/<id>` endpoint doesn't throw a 500 error when the customer it's trying to update was created via WP CLI.
3. The `GET customers/<id>` endpoint should not return a fatal error.

### Actual behavior

1. The `GET /customers` and `PUT /customers/<id>` endpoints throw a 500 error when one of your customers were created via WP CLI.
2. The `GET customers/<id>` returns a fatal error.

### Test site setup:

1. Create a JN site without WooCommerce installed.
1. Install WooCommerce nightly build. In my test, I used the Sep 30 nightly build:
    [woocommerce-trunk-nightly(2).zip](https://github.com/woocommerce/woocommerce/files/9680660/woocommerce-trunk-nightly.2.zip)
1. Install the Basic Auth plugin (from https://github.com/WP-API/Basic-Auth/archive/master.zip) so you could send REST API requests to this JN site using Postman.

### Create a customer using the `POST /customers` REST API endpoint and Postman

1. Open Postman in your local machine.
1. Set up the Basic Auth parameters in Postman to be the same as the `demo` username and password in the JN site you created above.
1. Create a new customer using the REST API by sending a  `POST /customers` request. You may use a very simple payload as this:

	```json
	{
    		"email": "restapi.customer@example.com",
    		"username": "restapi.customer",
    		"password": "password"
	}
	```
1. You should get a successful `201 Created` response.
1. Verify that you see this customer when you send a `GET /customers` request to list all customers in the JN site.

### Create a customer using WP CLI

1. SSH into the JN site.
1. `cd` into the server path.
1. Run this WP CLI command to create a new customer:

    ```bash
    wp user create wpcli.customer wpcli.customer@example.com \
	    --role=customer \
	    --user_pass=password
    ```

1. Run `wp user list` to verify that both the `restapi.customer` customer created earlier and this new `wpcli.customer` customer appears on the list.
3. Take note of their customer ID's.

### Now come the issues

1. Go back to Postman and once more send a `GET /customers` request to list all customers in this JN site. Notice that this time, you get a `500 internal server error` with the message _"There has been a critical error on this website."_. Take note that WP CLI lists the customers just fine, as we saw in the earlier step.
    <img width="968" alt="Screen Shot 2022-09-30 at 11 41 20 AM" src="https://user-images.githubusercontent.com/4509348/193189091-5a8ce0e7-255d-4c16-a844-8a6308841c24.png">

1. Now, try to update the first name of the `restapi.customer` customer by sending a `PUT /customers/<id>` request using Postman. You may use this payload as an example:

	```json
	{
   		"first_name": "Restapi",
		"_fields": "id, username, first_name"
	}
	```

1. You will get a successful `200 OK` as expected.
    <img width="757" alt="Screen Shot 2022-09-30 at 11 42 53 AM" src="https://user-images.githubusercontent.com/4509348/193189318-db24499a-1226-49b8-804b-927c1ae94753.png">

1. But now, try to update the first name of the `wpcli.customer` customer by sending a similar `PUT` request. You may use this payload:

	```json
	{
   		"first_name": "Wpcli",
		"_fields": "id, username, first_name"
	}
	```

1. Now, you get a `500 internal server error`. 
    <img width="957" alt="Screen Shot 2022-09-30 at 11 44 05 AM" src="https://user-images.githubusercontent.com/4509348/193189282-f61acd21-003f-4028-9f16-2acdd958d137.png">
1. Try doing a `GET customers/<id>` on the `restapi.customer` customer. You would be able to retrieve this customer just fine.
2. But then try doing a `GET customers/<id>` on `wpcli.customer`. You will get a `200 OK` response, but with this fatal error:
    <img width="957" alt="Screen Shot 2022-09-30 at 12 48 10 PM" src="https://user-images.githubusercontent.com/4509348/193192543-4beffedd-5075-4a94-b40f-8c3847e78a1d.png">

This shows that the `customers` REST API endpoint seems to be misbehaving when operating on a customer that's created via WP CLI.

### WordPress Environment

<details>
<summary>WordPress Environment</summary>
<pre>
WordPress address (URL): jurassic ninja
Site address (URL): jurassic ninja
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 4.81MB
Database Data Size: 3.37MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

JSON Basic Authentication: by WordPress API Team – 0.1
Companion Plugin: by Osk – 1.28
Jetpack: by Automattic – 11.3.2
WooCommerce: by Automattic – 7.0.0-dev

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.0
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-01 03:10:49 +00:00
Options: ✔
Notes: 37
Onboarding: skipped

### Action Scheduler ###

Complete: 6
Oldest: 2022-09-30 03:10:53 +0000
Newest: 2022-09-30 04:19:11 +0000

Failed: 1
Oldest: 2022-09-30 03:49:55 +0000
Newest: 2022-09-30 03:49:55 +0000

Pending: 1
Oldest: 2022-10-01 03:10:53 +0000
Newest: 2022-10-01 03:10:53 +0000

### Status report information ###

Generated at: 2022-09-30 04:19:15 +00:00
</pre>
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Just wanted to add that the error causing the 500 is this one:

> PHP Fatal error:  Uncaught Error: Call to a member function getTimestamp() on null in [...]/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-customers-controller.php:43

This relates [to the `'date_created'` property](https://github.com/woocommerce/woocommerce/blob/5cb5be8e9a4f269922877572b81e998d960dcc45/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-customers-controller.php#L43) on the `WC_Customer` object, which in turn depends on the [`user_registered` property of the underlying `WP_User`](https://github.com/woocommerce/woocommerce/blob/5cb5be8e9a4f269922877572b81e998d960dcc45/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php#L174) instance.

When this value is "0000-00-00 00:00:00" (the database default) `get_date_created()` considers it a `NULL` value, which obviously doesn't admit calling methods on it.

What is interesting is that by default `wp_insert_user()` does set this `user_registered` column, so it seems WP CLI is doing something funny (like manually passing `0000-00-00 00:00:00` as `user_registered` date when creating the user.

That's not to say we shouldn't be handling this correctly on the REST API's end.

**Comment by rrennick** [comment]
@rodelgc I wasn't able to reproduce any of the issues you described here in `trunk`. Could you confirm the issue whether the issue has been fixed for you and close if it has.

**Comment by jorgeatorres** [comment]
@rrennick: It has probably been fixed. I [submitted a PR](https://github.com/wp-cli/entity-command/issues/377) to WP-CLI, so if we're using a recent version, we should be good. In any case, I'll let @rodelgc confirm.

**Comment by lsinger** [comment]
@rodelgc can you confirm this can be closed?

**Comment by jorgeatorres** [comment]
Closing this as it's been fixed upstream (in WP-CLI). Feel free to reopen @rodelgc if we missed something 😸. Thanks!
