### ISSUE TITLE
Add the introduction banner card into Marketing page

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#34904]
This task issue is to add the introduction banner card into the multichannel marketing page.

Link to Figma design: 7cNed5RvTasoLgn38Hea0R-fi-2145%3A84807

- The introduction banner card is shown to New to Woo users & Existing supported channel users who are seeing multichannel for the first time.
- Its purpose is to introduce multichannel benefits and new features. 
- 3 variations: new users (no channels installed), existing users w/o campaigns, existing users w/ campaigns.
- User can dismiss the card.

## Design

New users:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/417342/206415766-80b95658-49e6-4d89-867a-546b7f236d93.png">

Existing users:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/417342/206415805-1260f87d-9baa-4700-9e32-a4a96cb9cf09.png">

## Technical

- Store the "card dismissed" state as a new WP Option.

**Comment by ecgan** [comment]
@shivanarrthine , what would happen when users click on the "Add channels" button? 🤔

**Comment by shivanarrthine** [comment]
> what would happen when users click on the "Add channels" button?

@ecgan It should scroll down to the `Add channels` section in the `Channels` card.
