### ISSUE TITLE
Task list inconsistency due to smart default when the user skips the profiler

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34908]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Description:**
The Shipping Smart Defaults flow needs to be tweaked to address the use case when the profiler is skipped. The current flow is a bit janky:

- Create a new store and skip the profiler without selecting a country
- See 7 tasks in the task list (including shipping)
<img width="1273" alt="Captura de ecrã 2022-09-30, às 18 37 42" src="https://user-images.githubusercontent.com/3380168/193326766-5070f213-427e-488e-bad0-91c24733f676.png">
- Go to settings and complete the store details adding a country covered by the smart default
- Go to the home screen and see that the shipping task was removed and replaced by the review shipping settings in the things to do next list
<img width="1289" alt="Captura de ecrã 2022-09-30, às 18 38 46" src="https://user-images.githubusercontent.com/3380168/193327107-9021eb6a-7b0f-4fc3-a4b9-8f061b89279b.png">

**Comment by pmcpinto** [comment]
cc @verofasulo @SamratBiswas1 @adrianduffell something that was spotted by Elizabeth today

**Comment by verofasulo** [comment]
Hey @pmcpinto, thanks for bringing this up!

I'm wondering if it makes any sense to invest time on this since we're changing the logic in the onboarding and the Country is a required field. 

> The current flow is a bit janky

I personally don't think it's a big issue/the flow is particularly awful but if you can expand a bit on the why it would be great 😊

**Comment by pmcpinto** [comment]
In the current logic, country is a required field, but users can skip the flow using the "skip" button or the address bar.

It's a bit janky because the user sees 7 tasks on the home screen. And after filling in the store details, he'll see 6 tasks on the list. TBC: I'm not saying that this should be a priority. There are other flaws in the setup flow that are more important.

**Comment by psealock** [comment]
This is no longer reproducible. Skipping the profiler now requires adding your store's country. Filling out store details in settings no longer has an affect on number of tasks. Closing
