### ISSUE TITLE
Epic: Multichannel Marketing Front-end

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#34903]
## Overview

This is an epic issue to track the development of an MVP version for the front-end part of the multichannel marketing feature. This builds on top of epic issue https://github.com/woocommerce/woocommerce/issues/33895 and relates to the back-end part in epic issue https://github.com/woocommerce/woocommerce/issues/34548.

As part of the multichannel marketing project (pbIy4N-213-p2), we will implement changes to the marketing dashboard to display the channels’ campaign data and basic information about their product listings.

The following is the design for the new Multichannel Marketing page:

![image](https://user-images.githubusercontent.com/417342/179001195-b01b7f44-96a9-4329-8e85-adb3dd4dbe39.png)

## Tasks

- [x] #34906
- [x] #34905
- [x] #34909
- [x] #34904
- [x] #34907
- [x] #37127
- [x] #37175
- [x] #37176
- [x] #37367

## Notes

- @nima-karimi is working on the back-end implementations required for this feature in https://github.com/woocommerce/woocommerce/issues/34548.

**Comment by findingsimple** [comment]
@ecgan can this be closed?

cc @budzanowski

**Comment by ecgan** [comment]
@jconroy , yes, all the tasks are complete, so this issue can be closed. I missed that. Closing this issue.
