### ISSUE TITLE
Scheduled sale date/time issue

### ISSUE THREAD

**Issue by Tommy-Hansen-Consortia** [woothemes/woocommerce#34915]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Vendor/Partner request: Our Bulk Table Editor uses date + time to schedule sales. Customers is complaining about the sale is not ending. We did some research and found that the cron job for sales ( wc_scheduled_sales ) just runs once a day. So having a sale from 09:00 to 12:00 the same day (or the like) is not possible anymore. This used to work. We manually changed this cron job to run every minute and problem solved. I think many WooCommerce users think that once a day is OK but if you schedule a sale using time it will not do. So our suggestion is: 1. In WooCommerce settings make an option to change this cron job. 2. Make a hook (filter) so developers can change the sales cron job (recurrence). Thanks, Tommy Hansen - Consortia AS

**Comment by jonathansadowski** [comment]
Hi @Tommy-Hansen-Consortia,

Thanks for the report. I'm labeling this as an enhancement request. If this is a mistake and there's a bug that you'd like to report, please [open a new issue using the template here](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml).

**Comment by barryhughes** [comment]
Closing as a duplicate of #31048.
