### ISSUE TITLE
Package scripting and builds: Separate from WooCommerce Admin

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34918]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

`@woocommerce/*` build logic currently resides in the WooCommerce Admin webpack config. This is preventing a clean migration of `plugins/woocommerce-admin` into `plugins/woocommerce` and should ideally be handled first.

- [ ] The following packages' build processes should be separated from WooCommerce Admin
https://github.com/woocommerce/woocommerce/blob/c46f4baa49616b3f47d44fa9b16fa60613ebfd6e/plugins/woocommerce-admin/webpack.config.js#L25-L39
- [ ] Determine and implement best way to house build logic. Does every package have its own? Or is there a central config packages extend from?

**Comment by rjchow** [comment]
I think the build (ts/js -> js) step is actually done by tsc within each of the @woocommerce packages, and the webpack config handles the bundling into wc-admin build

**Comment by psealock** [comment]
This is no longer relevant. Builds are handled by tsc as mentioned above
