### ISSUE TITLE
Change order count logic and copy to focus on new messages

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34929]
**Description:** the Inbox order count displays the total number of messages included in the panel. We think it will be more effective to use this space to indicate the number of new messages since the last visit.

**Acceptance criteria:**
- [ ] Tweak the Inbox order count logic only to include the new messages since the last visit and update the copy: X new messages since your last visit.

**Comment by pmcpinto** [comment]
@joshuatf was this merged in 7.3? I'm testing the beta and I don't see the copy update: 

> update the copy: X new messages since your last visit.

**Comment by pmcpinto** [comment]
@joshuatf can you confirm what I mentioned above? Thanks

**Comment by joshuatf** [comment]
Hey @pmcpinto sorry I missed the second half of that criteria.  The copy was not updated, only the logic around the order count.  I'll open an additional PR to address this.

**Comment by pmcpinto** [comment]
I'm closing this one, as it's not a priority.
