### ISSUE TITLE
Change the limit from 25 to 5 and allow users to load more messages

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34927]
**Description:** we show up to 25 notifications on the Inbox panel. This volume of messages makes it difficult to parse all the information and we don't offer an easy way to see older messages. The users need to delete messages to see older messages, which is a poor user experience. 

**Acceptance criteria:**

- [x] Change the Inbox messages limit from 25 to 5
- [x] Display the 5 most recent messages with a "Show older" CTA at the bottom of the panel
- [x] Load 10 messages when the user clicks "Show older" and change the CTA copy to "Show more"
- [x] The "Show more" CTA always loads the next 10 messages and it's displayed at the bottom until all messages are loaded

![MVP -_ Default](https://user-images.githubusercontent.com/3380168/193565553-2b707a91-0c78-40ca-a731-ea077126a4ec.png)
![MVP -_ Expanded](https://user-images.githubusercontent.com/3380168/193565571-18cc221d-3110-42c3-b7a1-292d8ce67840.png)

**Event Tracking:**
We should add a new event to track the new CTA interactions.

**Comment by joelclimbsthings** [comment]
@pmcpinto , I'm assuming these changes should impact both the inbox view on the homescreen, and the panel accessible through the Activity Panel on other screens? 

Edit: Also, I see the "This Week" and "Older" headings in the screenshot, but they're not mentioned in the acceptance criteria. Are those part of this issue, and if so how would they behave in other scenarios? (ie the next 5 inbox messages are older than a week)

**Comment by pmcpinto** [comment]
@joelclimbsthings 

> I'm assuming these changes should impact both the inbox view on the homescreen, and the panel accessible through the Activity Panel on other screens?

Correct. But the Inbox usage through the activity panel is low, so the home screen should be the priority. Let me know if implementing the changes in both areas will take much longer than just starting with the home screen. Thanks. 

>  I see the "This Week" and "Older" headings in the screenshot, but they're not mentioned in the acceptance criteria. Are those part of this issue, and if so how would they behave in other scenarios? (ie the next 5 inbox messages are older than a week)

These should not be included in the changes. Thanks

**Comment by joelclimbsthings** [comment]
@pmcpinto Looks like it's the same to implement in both locations 👍🏻
