### ISSUE TITLE
Improve the "Dismiss" button visibility

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34928]
**Description:** the "Dismiss" button is only visible when the user hovers the message. Due to this behavior, users may not realize that it is possible to remove messages when they are skimming through the panel. We also think this is why there's such a high % of users with 25 messages in the panel. Improving the visibility of the "Dismiss" button will help users to remove unnecessary/irrelevant notifications. 

**Acceptance criteria:**
- [ ] Show the dismiss button permanently in the Inbox message instead of just showing it on hover.

**Comment by octaedro** [comment]
Hi @pmcpinto,

I'm working on this improvement now. This is the way the button will look like:

![Screen Capture on 2022-10-12 at 13-37-17](https://user-images.githubusercontent.com/1314156/195399975-dc325a54-6f86-4bbf-98d1-4342f2d61d6c.gif)

Please let me know if you want a change in the styles.

// cc @jarekmorawski

**Comment by pmcpinto** [comment]
@octaedro this approach works for me. Thanks
