### ISSUE TITLE
[Enhancement]: Add filter "Show all orders that can be combined"

### ISSUE THREAD

**Issue by leyakoreya** [woothemes/woocommerce#34934]
### Describe the solution you'd like

Add more display of items in the section "Reports" "Clients" "List of clients"
https://we.tl/t-tsYRNSB9Tz

Add filter "Show all orders that can be combined"

Since, due to the large number of clients, doing it manually is very problematic and time consuming. it would be great if you add such a filter and allow more items to be displayed on the page, and not as it looks now (20 items when I have more than 3000 clients)

Your request (5583529) has been updated

Here was my request to your support where I talked about the difficulties and I was recommended to write here.

I hope you understand the situation and the problem correctly. And it's easy to solve

![Orders](https://user-images.githubusercontent.com/64163125/193608055-75f66ff1-7786-4999-ab23-00ce95cc07dd.png)
![Reports](https://user-images.githubusercontent.com/64163125/193608054-bc9f1e01-6550-4bc2-bf2e-af31946b5d44.png)
![Reports2](https://user-images.githubusercontent.com/64163125/193608052-2fdd9f89-5dab-486d-9e19-96561599080e.png)
![elements](https://user-images.githubusercontent.com/64163125/193608053-3bfdfbab-8ca1-44d1-9483-b48eb0efeb51.png)

### Describe alternatives you've considered

An alternative was suggested to install a plugin https://www.skyverge.com/blog/automatically-link-woocommerce-orders-customer-registration/ , but I don't want to install another plugin

### Additional context

I am sure that such an opportunity can benefit all e-commerce users to easily combine orders from customers that were made before registration and after registration.

**Comment by rrennick** [comment]
@leyakoreya Did you create the screenshots above with only WooCommerce active? When I view the customers list there isn't the fourth icon on the right:

<img width="589" alt="Screenshot 2023-06-23 at 2 06 46 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/8baedf81-c77d-4238-ac2c-a696bfd48ed5">

**Comment by rrennick** [comment]
Closing due to lack of feedback.
