### ISSUE TITLE
Remove low-performing notifications

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34930]
**Description:** we'll remove the inbox notifications with a low conversion rate. 

**Acceptance criteria:**
The following notifications should be removed (I'm not sure if some were already removed as they're still showing up in the Inbox stats):

- [ ] wc-admin-first-five-things-to-customize
- [x] wc-admin-navigation-nudge
- [ ] wc-admin-insight-first-product-and-payment
- [ ] wc-admin-first-downloadable-product
- [ ] wc-admin-adding-and-managing-products
- [ ] wc-admin-getting-started-in-ecommerce
- [x] eu_vat_changes_2021
- [x] wc-admin-onboarding-email-marketing
- [ ] wc-admin-manage-store-activity-from-home-screen
- [x] wc-admin-learn-more-about-variable-products
- [x] wc-admin-marketing-intro (I'd like to confirm the content of this message before removing it)
- [ ] wc_shipping_mobile_app_q4_2021  (I'd like to confirm the content of this message before removing it)
- [ ] wc-admin-first-product
- [ ] wc-admin-update-store-details
- [ ] wc-admin-insight-first-sale
- [x] wc-admin-complete-store-details
- [ ] wc-admin-welcome-to-woocommerce-for-store-users

**Comment by louwie17** [comment]
**Already removed**
- wc-admin-navigation-nudge
- eu_vat_changes_2021
- wc-admin-onboarding-email-marketing
- wc-admin-learn-more-about-variable-products
- wc-admin-marketing-intro ([original copy](https://github.com/woocommerce/woocommerce/blob/05cf7b010e4aa5ec8c148184f9aa8aba2734f493/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Marketing.php#L44-L45))
- wc-admin-complete-store-details

**On WooCommerce.com** can be removed here: https://woocommerce.com/wp-admin/edit.php?post_type=banner
- wc-admin-first-five-things-to-customize
- wc-admin-getting-started-in-ecommerce
- wc_shipping_mobile_app_q4_2021

cc @pmcpinto you should be able to remove these one's as well using the above link using the **Ads** plugin on woocommerce.com

**On WooCommerce Admin** -> woocommerce/src/Internal/Admin/Notes
- wc-admin-insight-first-product-and-payment
- wc-admin-first-downloadable-product
- wc-admin-adding-and-managing-products
- wc-admin-manage-store-activity-from-home-screen
- wc-admin-first-product
- wc-admin-update-store-details
- wc-admin-insight-first-sale
- wc-admin-welcome-to-woocommerce-for-store-users

**Comment by joshuatf** [comment]
>wc-admin-first-product

@louwie17 @pmcpinto Is this supposed to be `wc-admin-add-first-product-note` or has it already been removed?  I don't see `wc-admin-first-product` in WCA.

**Comment by pmcpinto** [comment]
> cc @pmcpinto you should be able to remove these one's as well using the above link using the Ads plugin on woocommerce.com

Thanks for the heads up. I'll remove them today.

> @louwie17 @pmcpinto Is this supposed to be wc-admin-add-first-product-note or has it already been removed? I don't see wc-admin-first-product in WCA.

Joshua, can you share the content of the wc-admin-add-first-product-note?

**Comment by joshuatf** [comment]
>Joshua, can you share the content of the wc-admin-add-first-product-note?

Sure thing @pmcpinto!  It's the one titled "Add your first product" and starts with "Nice one; you've created a WooCommerce store! Now it's time to add your first product and get ready to start selling."

**Comment by pmcpinto** [comment]
@joshuatf thanks for the clarification.

The inbox I'm talking in this issue is this one: https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/plugins/woocommerce/src/Internal/Admin/Notes/FirstProduct.php

**Comment by joshuatf** [comment]
**In progress / Under review:**

* wc-admin-insight-first-product-and-payment https://github.com/woocommerce/woocommerce/pull/35309
* wc-admin-first-downloadable-product https://github.com/woocommerce/woocommerce/pull/35318
* wc-admin-adding-and-managing-products https://github.com/woocommerce/woocommerce/pull/35319
* wc-admin-manage-store-activity-from-home-screen https://github.com/woocommerce/woocommerce/pull/35320
* wc-admin-update-store-details https://github.com/woocommerce/woocommerce/pull/35322
* wc-admin-insight-first-sale https://github.com/woocommerce/woocommerce/pull/35341
* wc-admin-welcome-to-woocommerce-for-store-users https://github.com/woocommerce/woocommerce/pull/35342

**To-do**

* wc-admin-first-product mentioned by @pmcpinto above

cc @mdperez86
