### ISSUE TITLE
Highlight changes workflow linting unrelated files

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#34933]
It seems our Highlight changes workflow is picking up phantom changes that are not related to the PR. Ref: https://github.com/woocommerce/woocommerce/pull/34597

![0b1SEB.png](https://user-images.githubusercontent.com/2132595/193607456-fd964c14-0e1e-4a91-8592-fda8c920d975.png)

Here is the original PR changed files:

![bPuI8m.png](https://user-images.githubusercontent.com/2132595/193607607-306ed4de-c17d-4d0e-bec4-843d6e415f66.png)

The theory of the cause is that the PR is probably not up to date with trunk. We should update the logic to check only changed files.

**Comment by psealock** [comment]
Another instance of this happening here: https://github.com/woocommerce/woocommerce/pull/34951#issuecomment-1271044696

**Comment by barryhughes** [comment]
In case useful, another example of what I think is the same problem can be seen in https://github.com/woocommerce/woocommerce/pull/35125/files.

<img width="678" alt="35125-irrelevant" src="https://user-images.githubusercontent.com/3594411/197020051-b6664eed-cf05-4cd1-87ca-15a0288e79f6.png">

☝🏽  The PR did not in fact add or even reference `woocommerce_feature_description_tip`.

**Comment by jonathansadowski** [comment]
It may be the case that this was also fixed via #35315. I'm going to close this issue, but if anyone still sees this pop up (after a rebase to include the changes from #35315), please comment here and we'll reopen and dig further.
