### ISSUE TITLE
[Enhancement]: Is there a way i can change the "Order" in admin as "Donation" and apply same elsewhere in emails, analytics & reports

### ISSUE THREAD

**Issue by mgkmoha** [woothemes/woocommerce#34941]
### Describe the solution you'd like

My solution is to provide more personalized and customized experience when utilizing WooCommerce as a powerful donation platform. 

Changing the "Order" in admin as "Donation" and apply the same elsewhere specially in WooCommerce summary, emails, analytics, reports and elsewhere.

### Describe alternatives you've considered

I did check WooCommerce documentation and could not find it in filters and hook.

Template override for email is possible. 

### Additional context

![1 1](https://user-images.githubusercontent.com/12834562/193751048-4968923a-4b71-4371-8b1f-e1afe4989b15.png)
![1 2](https://user-images.githubusercontent.com/12834562/193751058-cacd6745-7834-4c9f-b7d6-7ef58d2f341b.png)
![1 3](https://user-images.githubusercontent.com/12834562/193751059-106aec50-6925-4a99-9e15-8baae776c62c.png)
![1](https://user-images.githubusercontent.com/12834562/193751062-529ef964-7149-4421-b391-116d0b4427a2.png)
![2](https://user-images.githubusercontent.com/12834562/193751066-4299a9ce-ebbb-4173-aab6-006d6ad77bc8.png)
![3](https://user-images.githubusercontent.com/12834562/193751067-cb98f807-6762-4648-b53e-bc1311a0d564.png)

**Comment by barryhughes** [comment]
Hi @mgkmoha,

As currently framed, this seems like a customization task and so probably isn't suitable for the issue tracker.

I think what you want to achieve is likely possible via the translation layer (in the sense that you could translate various strings to replace 'orders' with 'donations', etc). That said, if that's something you've considered and don't think would be suitable, we'd definitely be interested to hear why.

Some developer resources that might be of interest:

- https://developer.wordpress.org/reference/hooks/gettext/
- https://developer.wordpress.org/reference/hooks/gettext_with_context/
