### ISSUE TITLE
[Enhancement]: Update legacy JITMs

### ISSUE THREAD

**Issue by Timstreep** [woothemes/woocommerce#34942]
### Describe the solution you'd like

Summary: Update old JITMs in WooCommerce.

Minor copy tweaks and suggestions on which outdated JITMs to remove [in this doc](https://docs.google.com/document/d/14aXzKLLpNVo5rz10Bjqkqb7NgSRu1UVzWk-PfRAN0hY/edit).

All JITMs need an updated Woo logo (with the new purple), and possibly the blue button colour is at odds with our current colour schemes.

### Describe alternatives you've considered

There are no alternatives.

**Comment by octaedro** [comment]
These changes have been deployed, after landing D89706-code
