### ISSUE TITLE
Product Categories widget 'show children' behaviour on Product Tag Archives

### ISSUE THREAD

**Issue by WiredWonder** [woothemes/woocommerce#34943]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Ticking the 'Show children of the current category' box on the Product Categories widget offers inconsistent behaviour across different elements.

On Category archives it correctly shows children.

On Product Tag archives it shows all site categories, not just those relevant to the tag. Clicking any entry does not refine/filter the Product Tag view, it just navigates to the category.

### Expected behavior

Clicking on a Category within the widget on a tag archive refines/filters the view of the tag to only show products that that tag and category.

### Actual behavior

On Product Tag archives the widget shows all site categories, not just those relevant to the tag. Clicking any entry does not refine/filter the Product Tag view, it just navigates to the category.

### Steps to reproduce

Configure product tags
Enable the Product Categories widget in the sidebar and tick 'show children of the current category'
Navigate to a tag archive (eg. https://site/products/product-tag)
Click any category in the widget

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): na
Site address (URL): na
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.15-MariaDB-0+deb11u1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 1256.65MB
Database Data Size: 953.17MB
Database Index Size: 303.48MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 25.56MB + Index: 42.64MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 8.02MB + Index: 10.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.25MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 7.52MB + Index: 6.02MB + Engine InnoDB
wp_commentmeta: Data: 1.34MB + Index: 0.36MB + Engine InnoDB
wp_comments: Data: 31.56MB + Index: 25.09MB + Engine InnoDB
wp_termmeta: Data: 0.17MB + Index: 0.31MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 2.47MB + Index: 1.34MB + Engine InnoDB
wp_term_taxonomy: Data: 0.28MB + Index: 0.13MB + Engine InnoDB
wp_usermeta: Data: 5.47MB + Index: 5.52MB + Engine InnoDB
wp_users: Data: 0.39MB + Index: 0.38MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.52MB + Index: 3.89MB + Engine InnoDB
wp_wc_order_stats: Data: 2.52MB + Index: 2.31MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.33MB + Index: 0.27MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 1.52MB + Index: 1.36MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.45MB + Index: 0.78MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

na

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

na

### Inactive Plugins (6) ###

na

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #2773 - /terms-and-conditions/

### Theme ###

Name: Enfold
Version: 1.0
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.9.2.3
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: enfold-child/woocommerce/emails/email-order-items.php

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-10-05 03:05:25 +11:00
Options: ✔
Notes: 76
Onboarding: completed

### Action Scheduler ###

Canceled: 4
Oldest: 2022-09-03 22:37:16 +1000
Newest: 2022-09-26 13:27:16 +1000

Complete: 20,343
Oldest: 2022-09-03 23:04:48 +1000
Newest: 2022-10-04 22:11:21 +1100

Pending: 4
Oldest: 2022-10-04 22:49:23 +1100
Newest: 2022-10-05 16:17:43 +1100

### Status report information ###

Generated at: 2022-10-04 22:11:48 +11:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @galapogos01,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.9.4 version, and WordPress 6.0.2 version.

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/194236956-db69226c-6335-4617-9d06-481ba3077d89.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
Hi @galapogos01 

> On Product Tag archives it shows all site categories, not just those relevant to the tag. 

Neither WordPress nor WooCommerce maintain any relationship between tags and (product) categories. When you are on a tags archive page the current category is undefined (`null`). 

> Clicking any entry does not refine/filter the Product Tag view, it just navigates to the category.

This is how the links work in the widget anywhere on the site. It is still navigating to the product category when the widget is on a category archive.

I'm closing the issue as there isn't a relationship between product tags and categories. Adding this add an enhancement would be lower priority than many of the existing enhancement requests.

**Comment by WiredWonder** [comment]
@rrennick I'm not suggesting there should be a relationship between tags and categories, that's weird. What I'm suggesting is that it would show categories relevant to the tag, and if a category is clicked, would refine the tag view to products of that category (AND). 

At the moment it navigates away from the tag, losing the power of refinement such that the tag becomes very difficult for a user to use.

Can you please re-open the ticket? It's certainly not Completed.

Thanks, 
Jason

**Comment by rrennick** [comment]
> Can you please re-open the ticket? It's certainly not Completed.

The `completed` message is applied by Github when closing an issue. What I hoped to explain in my closing comment is that an enhancement like this is low priority. There are currently 1900+ open issues and this isn't something we would look at doing. We would be happy to review a backward compatible pull request that implemented this feature.
