### ISSUE TITLE
[COT|HPOS] Incorrect order status after trashing then restoring an order

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#34956]
Discovered during testing for 7.0.0, it seems like when a (COT or HPOS) order is restored from the trash, it may not be restored to the expected status. Internal link: pb22l9-1xy-p2#comment-1580 

From the original discussion:

1. Change the status of Completed order to Processing.
2. Now send the order to the Trash.
3. Restore the order from the Trash.

At this point, I expect the order to have the status Processing, as it was the most recent status it had before being moved to the trash, but it turned out to be restored with the status Completed. Related video:

[📹 Screencast](https://href.li/?https://d.pr/v/OM5BLv)

**Comment by Konamiman** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/35125
