### ISSUE TITLE
On CSV import, product variations are not visible if parent is draft

### ISSUE THREAD

**Issue by ajdinmore** [woothemes/woocommerce#34962]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When variable products are exported with a draft status, all variations are also set to draft.  On import, the status of these variations remains draft, causing them not to appear.

### Expected behavior

Exporting and importing draft variable products works correctly.

### Actual behavior

Imported products appear to loose all variations.

### Steps to reproduce

1. Export a variable product draft
2. Import the generated file (to a different site, or first delete the product)
3. Check the imported product variations

### WordPress Environment

All

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ajdinmore** [comment]
Hack-job plugin for anyone needing a quick fix:
```php
<?php
declare(strict_types=1);
/**
 * Plugin Name: WooCommerce Import Fix 2022-10-05
 * Description: Fixes importing variable product drafts.
 */

add_filter('woocommerce_product_importer_formatting_callbacks', function (array $callbacks, \WC_Product_Importer $importer) {
    $key = array_search('published', $importer->get_mapped_keys());
    if (false !== $key && isset($callbacks[$key])){
        $original = $callbacks[$key];
        $callbacks[$key] = fn($value) => (int)$original($value);
    }
    return $callbacks;
}, PHP_INT_MAX, 2);
```

**Comment by swatipawarGS** [comment]
Hi @ajdinmore,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.9.4 version, and WordPress 6.0.2 version.

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/194484151-c7239916-ed82-45f8-8ab4-21a3c8394630.mp4



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by Konamiman** [comment]
Fix: https://github.com/woocommerce/woocommerce/pull/36933
