### ISSUE TITLE
[COT/HPOS]: UX Improvements to HPOS feature screen

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#34975]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We would like to make following improvements to HPOS feature screen to make it easier to use, combining them all into one issue since they are best handled by a single PR otherwise there will be lot of conflicts:

#### Remove the option to "Keep the posts table and the orders tables synchronized"
When COT/HPOS is enabled, if there are some orders pending migration and the `Keep the posts table and the orders tables synchronized` option is enabled on the COT/HPOS settings page, a new checkbox appears to enable an option for automatically switching to the new WC table once the migration is complete. It seems this option doesn't work as expected, see video below:

[https://d.pr/v/TjQk7y](https://d.pr/v/TjQk7y)

#### Remove other options for transactions except for "Read Uncommitted"

We currently allow using all modes of transactions that MySQL supports, such as Repeatable read, Read committed, Read uncommitted etc. However for our use case, just the "read uncommitted" transaction mode is sufficient, as it does not locks the posts table, but at the same if migration fails for some reason for the current batch, it will still roll back any partial changes.

We should declutter this UI to not only provide only this mode, as other modes can lock the posts and postmeta tables on a live site, but also we don't expect regular merchants to make sense of these transaction modes.

#### In the features controller page, add a link to the HPOS managment screen

When the feature is first enabled via WooCommerce > Settings > Advanced > Features, it is not immediately clear that the user would need to go to WooCommerce > Settings > Advanced > Custom Data Stores to actually enable the sync and make the HPOS authoritative. We should add a link to the manage feature page in the Features screen that should give the direction to user about where to go to.

**Comment by vedanshujain** [comment]
Hey @alopezari , I have hijacked this issue to make it more general purpose targeting other enhancements to these screens as well.
