### ISSUE TITLE
Problem retrieving orders via `wc_get_order()`

### ISSUE THREAD

**Issue by divyanshu-chaudhari-shipsy** [woothemes/woocommerce#34973]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are using the wc_get_order function in order to receive the order data. But, it is returning false.
This is because the get_class_name_for_order_id() function in get_order function(mentioned below) of the woocommerce repository returns false.

public static function get_order( $order_id = false ) {
$order_id = self::get_order_id( $order_id );

if ( ! $order_id ) {
return false;
}

$classname = self::get_class_name_for_order_id( $order_id );
if ( ! $classname ) {
return false;
}

try {
return new $classname( $order_id );
} catch ( Exception $e ) {
wc_caught_exception( $e, __FUNCTION__, array( $order_id ) );
return false;
}
}

We have checked and the $order_id is coming correct. Need to know why valid $classname is not returned.
Need your help regarding this.

### Expected behavior

We should get the order data after calling wc_get_order function.

### Actual behavior

wc_get_order function is returning false.

### Steps to reproduce

1. We use our plugin DTDC Econnect 1.0.10.
2.After activating the plugin, we go to the orders section.
3. When we click the sync order button, it is giving error at this point.
4. Internally this sync order feature uses wc_get_order function in order to receive the order data. But it is returning false.Because of which the error.

### WordPress Environment ###
WordPress address (URL): https://www.soilscents.com
Site address (URL): https://www.soilscents.com
WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
### Server Environment ###
Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 260 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1p
SUHOSIN Installed: –
MySQL Version: 5.7.38-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
### Database ###
WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 32.79MB
Database Data Size: 28.81MB
Database Index Size: 3.98MB
wp_woocommerce_sessions: Data: 0.54MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.10MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 1.36MB + Index: 0.49MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.77MB + Index: 0.51MB + Engine MyISAM
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_categorymeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
wp_digits_blocked_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_digits_mobile_otp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_digits_requests_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dv_assign_awb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dv_awb_no_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dv_logs: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_dv_my_warehouse: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dv_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_member_catmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 4.90MB + Index: 1.17MB + Engine MyISAM
wp_portfolio_catmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 1.55MB + Index: 0.38MB + Engine MyISAM
wp_posts: Data: 3.83MB + Index: 0.11MB + Engine MyISAM
wp_product_catmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sync_track_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.24MB + Index: 0.15MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpsmtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yoast_indexable: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
### Post Type Counts ###
attachment: 236
custom_css: 1
event: 7
faq: 10
member: 12
nav_menu_item: 40
page: 20
portfolio: 4
porto_builder: 30
post: 18
product: 24
revision: 542
shop_coupon: 1
shop_order: 137
wp_global_styles: 1
wpcf7_contact_form: 4
wpcs: 1
### Security ###
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔
### Active Plugins (31) ###
Aramex Shipping WooCommerce: by aramex.com – 1.1.12
CCAvenue Payment Gateway for WooCommerce: by CCAvenue – 4.1
Click to Chat: by HoliThemes – 3.8
Contact Form 7: by Takayuki Miyoshi – 5.2
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.3.3
DIGITS: Wordpress Mobile Number Signup and Login: by UnitedOver – 7.9.1.9
DTDC Econnect: by shipsyplugins – 1.0.10
Duplicate Page: by mndpsingh287 – 4.2
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.7
Facebook for WooCommerce: by Facebook – 2.6.22
Jetpack: by Automattic – 10.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.5.0
Microsoft Clarity: by Microsoft – 0.7.5
Mobile Menu: by Freshlight Lab – 2.8.2.7
Facebook for WordPress: by Facebook – 3.0.6
Porto Theme - Functionality: by P-Themes – 2.0.3
Slider Revolution: by ThemePunch – 6.1.3
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.5.3
WooCommerce Delhivery: by Can tech – 1.0.51
Force Authentification Before Checkout for WooCommerce: by Luiz Bills – 1.4.1
Instamojo for WooCommerce: by instamojo – 1.0.7
Razorpay for WooCommerce: by Team Razorpay – 4.2.0
BusinessOnBot: by BusinessOnBot – 19.7.95
WC - APG SMS Notifications: by Art Project Group – 2.24.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.5.3
WooCommerce: by Automattic – 6.9.2 (update to version 6.9.3 is available)
Wordfence Security: by Wordfence – 7.5.5
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Debugging: by Andy Fragen – 2.11.14
YITH WooCommerce Wishlist: by YITH – 3.0.11
### Inactive Plugins (5) ###
Advanced Shipment Tracking for WooCommerce: by zorem – 3.3.1
Akismet Anti-Spam: by Automattic – 4.1.2
Delhivery Logistics Courier: by Delhivery – 1.0.103
Flexible Shipping: by WP Desk – 4.8.3
Google Listings and Ads: by WooCommerce – 2.1.1
### Dropin Plugins (2) ###
db-error.php: db-error.php
maintenance.php: maintenance.php
### Settings ###
API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
### WC Pages ###
Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set
### Theme ###
Name: Porto
Version: 6.0.4
Author URL: http://www.portotheme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔
### Templates ###
Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php version 3.7.0 is out of date. The core version is 5.2.0
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php version 3.4.0 is out of date. The core version is 5.2.0
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php version 3.8.0 is out of date. The core version is 5.2.0
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php version 3.0.0 is out of date. The core version is 3.6.0
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php version 4.1.0 is out of date. The core version is 6.0.0
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php version 3.6.0 is out of date. The core version is 6.5.0
porto/woocommerce/order/order-details-customer.php version 3.4.4 is out of date. The core version is 5.6.0
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php version 3.5.5 is out of date. The core version is 6.1.0
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php
Outdated Templates: ❌
Learn how to update
### Admin ###
Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
Disabled Features: minified-js
new-product-management-experience
settings
Daily Cron: ✔ Next scheduled: 2022-09-27 05:46:15 +05:30
Options: ✔
Notes: 102
Onboarding: completed
### Action Scheduler ###
Complete: 3,789
Oldest: 2022-08-26 07:46:09 +0000
Newest: 2022-09-26 07:43:51 +0000
Failed: 2
Oldest: 2022-05-27 10:08:41 +0000
Newest: 2022-05-27 10:08:58 +0000
Pending: 7
Oldest: 2022-09-26 07:43:58 +0000
Newest: 2022-09-27 05:04:55 +0000
### Status report information ###
Generated at: 2022-09-26 13:14:14 +05:30

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @divyanshu-chaudhari-shipsy,

Thanks for the report. You've mentioned in the steps for reproduction first activating another plugin. Are you still able to reproduce this issue with only the WooCommerce plugin active? Are you able to reproduce it with either the default WordPress theme or the Storefront theme active? If so, could you please provide us a list of steps that we could use to reproduce the issue?

**Comment by divyanshu-chaudhari-shipsy** [comment]
Thanks jonathansadowski, your suggestion to deactivate other plugins worked. A plugin used for creating serial numbers was used which created that error. Have used an alternate plugin and its working fine now.
