### ISSUE TITLE
[COT/HPOS] $order->save_meta_data() not working when keeping tables syncronized

### ISSUE THREAD

**Issue by leonardola** [woothemes/woocommerce#34981]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug
While declaring HPOS compatibility on Gocardless payment gateway plugin I noticed that if you go to WooCommerce > Settings > Advanced > Custom Order Tables and activate the option `Keep the posts table and the orders tables synchronized` calling `$order->save_meta_data();` after `$order->update_meta_data();` does not save the order meta.

Creating an error when trying to pay for an order using Gocardless

### Expected behavior

`$order->save_meta_data();` should save the order meta data even when `Keep the posts table and the orders tables synchronized` is activated

### Actual behavior

If you go to WooCommerce > Settings > Advanced > Custom Order Tables and activate the option `Keep the posts table and the orders tables synchronized` calling `$order->save_meta_data();` after `$order->update_meta_data();` does not save the order meta.

### Steps to reproduce

- go to WooCommerce > Settings > Advanced > Custom Order Tables and activate the option `Keep the posts table and the orders tables synchronized`
- try to run `$order->save_meta_data();` after  a `$order->update_meta_data();` and notice the meta was not saved

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://gocardless.local
Site address (URL): http://gocardless.local
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 6.68MB
Database Data Size: 4.86MB
Database Index Size: 1.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_csv_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_csv_uploads_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_csv_uploads_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_page_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_page_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_table_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project_table_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_publisher: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_publisher_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_publisher_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_design: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_design_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_design_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings_BACKUP_20220909132944: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings_BACKUP_20221006171706: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 8
post: 1
product: 4
product_variation: 2
revision: 1
shop_order: 17
shop_order_placehold: 1
shop_subscription: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

Weak Password: by  –
WooCommerce GoCardless Gateway: by WooCommerce – 2.5.1
WooCommerce Order Status Control: by SkyVerge – 1.14.0
WooCommerce Subscriptions: by WooCommerce – 4.1.0
WooCommerce: by Automattic – 7.0.0-hpos.dev.7
WP Data Access: by Passionate Programmers B.V. – 5.2.6

### Inactive Plugins (1) ###

WooCommerce Blocks: by Automattic – 8.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.0.0 (update to version 4.1.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://gocardless.local
Subscription Statuses: wc-on-hold: 3
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Direct Debit (GoCardless): wc-on-hold: 3

### Payment Gateway Support ###

Cash on delivery: products
Direct Debit (GoCardless): products
refunds
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_date_changes
subscription_amount_changes
multiple_subscriptions
pre-orders

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-07 17:21:06 +00:00
Options: ✔
Notes: 60
Onboarding: completed

### Action Scheduler ###

Complete: 115
Oldest: 2022-09-09 13:27:26 +0000
Newest: 2022-10-06 17:24:42 +0000

Pending: 2
Oldest: 2022-10-06 18:25:49 +0000
Newest: 2022-10-07 17:14:32 +0000

### Status report information ###

Generated at: 2022-10-06 18:20:08 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by alexmigf** [comment]
For me it worked if I call `$order-save()` after updating meta, but this trick doesn't work if I try to delete meta using `$order->delete_meta_data( $key )`, but that shouldn't be necessary I believe, just saving meta should be enough.

I'm using latest 7.1 HPOS dev.

**Comment by leonardola** [comment]
@alexmigf `$order->save()` does work. The problem is with `$order->save_meta_data()` which stops working when activating `the keep tables syncronized` option. Many plugins rely on `$order->save_meta_data()` to save the meta. Having to change that to `$order->save()` would require some more changes. Also `$order->save()` should be more costly then `$order->save_meta_data()` so this would not be just a find and replace job.

**Comment by alexmigf** [comment]
I wasn't suggesting to replace with `save()`, just found that was working if I call it after updating meta, just that. `delete_meta_data()` has the same problem as `save_meta_data()`, it seems.

**Comment by barryhughes** [comment]
I realize this issue is the older of the two, but I'm going to close it as a duplicate since we already started work on this problem via https://github.com/woocommerce/woocommerce/issues/35703.
