### ISSUE TITLE
[Enhancement]: Nest shop-related pages under shop page

### ISSUE THREAD

**Issue by strarsis** [woothemes/woocommerce#34983]
### Describe the solution you'd like

The shop-related pages, as cart, checkout and my account pages should be nested under the shop page by default.
The user may still change this, but the default helps with grouping shop related pages and other pages of a site.

### Describe alternatives you've considered

Nesting those shop-related pages manually after WooCommerce created them.

**Comment by rrennick** [comment]
@strarsis You can do this by editing the pages and setting their parent to the shop page.

<img width="836" alt="Screenshot 2023-07-31 at 4 48 38 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/6dbdd75f-0a09-457e-8cf9-eb78c99d26c2">
