### ISSUE TITLE
Duplicate notices on the cart page cause a JS exception and eternal spinner: remove_duplicate_notices() in cart.js does not work because array is not copied, only referenced

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#35005]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The method remove_duplicate_notices in cart.js - https://github.com/woocommerce/woocommerce/blob/91e1347aab2212791b76861a30ccc8c2c39b3907/plugins/woocommerce/client/legacy/js/frontend/cart.js#L65 does not work, because the "new" array of notices that it creates is simply a reference to the old.

The outcome of this is that if there *are* any new notices, then the call to `.text()` will throw an exception, because one of the members will have been spliced, causing the jQuery `each()` loop (which apparently can't cope with the array being spliced whilst it is looping) to supply a reference to an object that was not part of the original list and upon which the `.text()` method cannot be called, resulting in the exception:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1727:19)
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at Sizzle.getText [as text] (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at jQuery.fn.init.<anonymous> (wp-includes/js/jquery/jquery.js?ver=3.6.0:6242:12)
    at access (wp-includes/js/jquery/jquery.js?ver=3.6.0:4202:13)
    at jQuery.fn.init.text (wp-includes/js/jquery/jquery.js?ver=3.6.0:6240:10)
    at wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:76:25
    at Function.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:385:19)
    at jQuery.fn.init.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:207:17)
    at remove_duplicate_notices (wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:72:11)
```

Look at this example:

```
var notices = [1, 2, 3];
var new_notices = notices; // This is just a reference!
new_notices.splice(1, 1); // Since this is just a reference, we just removed the entry from notices also...
console.log(notices); // Output the original array and observe that an entry has been removed
```

The output is `[1, 3]`, since `new_notices` was just a reference to `notices`.

The method should either copy the array, or build `new_notices` from empty using the non-duplicated notices.

### Expected behavior

Duplicate notices deleted.

### Actual behavior

JavaScript exception and eternal spinner; page then has to be reloaded.

### Steps to reproduce

Create a code snippet that outputs duplicate notices (as detected in `remove_duplicate_notices()` in `cart.js`). Add items to your cart, go to the cart page, then remove an item. This will trigger the above method and its bugs.

### WordPress Environment

WooCommerce 6.9.4, WordPress 6.0.2, PHP 8.0.23.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by DavidAnderson684** [comment]
Oh, and, as an aside.... my plugin (which was triggering this, though it took a while to track down how to do so) had a legitimate reason for including duplicate messages. The messages were hidden, but each one keyed to a different shipping class. JavaScript would cause the relevant message for the selected shipping class on the cart page to be shown - and some of those messages might be identical (i.e. message for shipping class X was actually the same as for shipping class Y, though different to the message for shipping class Z).

That is to say - the whole idea to remove duplicate messages appears to be a premature optimisation. A means of removing bugs from plugins that were wrongly doing so (which is where the fix should have gone), whilst breaking code that legitimately did so.

**Comment by DavidAnderson684** [comment]
Furthermore, because `new_notices.splice()` is doing the same as `notices.splice()`, if it gets called more than once, it'll not be operating on the index it thinks it is:

```
bob =  [1, 2, 3, 4, 5]; jQuery(bob).each(function(index) { console.log("index="+index); console.log(bob[index]); bob.splice(index, 1);});

Output:
index=0
1
index=1
3
index=2
5
index=3
undefined
index=4
undefined
```

**Comment by roykho** [comment]
Hi @DavidAnderson684 - thanks for the reporting. Could you please give us more detail as to the steps to reproduce. You mentioned `Create a code snippet that outputs duplicate notices (as detected in remove_duplicate_notices() in cart.js)` but could you include exactly the code snippet you're using?

**Comment by DavidAnderson684** [comment]
It's part of a plugin. Here's the essential line, run with different shipping method/instance ID combinations (as explained aboev), but identical messages:

```
echo "<p style=\"display: hide;\" class=\"woocommerce-message woocommerce-info woocommerce-info-minmaxinfo woocommerce-info-minmaxinfo-${shipping_method_id} woocommerce-info-minmaxinfo-${shipping_method_id}-${instance_id}\" id=\"wcminmax_minmaxinfo-${shipping_method_id}-${instance_id}\">\n\t".$message."\n</p>\n";
```

**Comment by peterfabian** [comment]
The original issue why the JS was created: https://github.com/woocommerce/woocommerce/issues/28914 (and PR https://github.com/woocommerce/woocommerce/pull/29480).

**Comment by vedanshujain** [comment]
Thanks for the report, for now, I think we can fix the bug. Because at this point, some plugins (or even core) that would be throwing multiple errors might be relying on this (unless that's not possible because of the reported bug). Marking it low priority for now (relative to other high-priority issues we have open in the repo).

Also marking good-first-bug as we are limiting the scope to only fixing the bug.

**Comment by paco3346** [comment]
Just got bit by this one as I too was affected after recently updating.


Quick fix is to use spread operator but I'm not sure what browsers Woocommerce is trying to target (or if the turbo config will transpile this down.)

https://github.com/woocommerce/woocommerce/blob/91e1347aab2212791b76861a30ccc8c2c39b3907/plugins/woocommerce/client/legacy/js/frontend/cart.js#L67

to

```javascript
var new_notices = [... notices];
```

**Comment by johanmolen** [comment]
Im also facing this issue on one of my WooCommerce sites, which triggers eternal loading once removing / or updating a cart item.

**Comment by DavidAnderson684** [comment]
@vedanshujain Should this bug still be "low priority" given that there have now been three developers independently encountering it "in the wild" who are reporting it here, and that it breaks core functionality when it occurs?

**Comment by johanmolen** [comment]
@DavidAnderson684 I purposed a fix in PR #36779.

**Comment by johanmolen** [comment]
Created a new PR #40170 for this.

**Comment by johanmolen** [comment]
@paco3346 @DavidAnderson684 do you maybe have an easy reproduction method for this issue? So @barryhughes can test my PR #40170?

**Comment by DavidAnderson684** [comment]
See https://github.com/woocommerce/woocommerce/issues/35005#issuecomment-1273525413 .
