### ISSUE TITLE
Make Product Gallery Images clickable: 

### ISSUE THREAD

**Issue by Farallon5** [woothemes/woocommerce#35002]
### Describe the solution you'd like

You should be able to assign a link to a product gallery image.

**Comment by roykho** [comment]
Hi @Farallon5 - Can you please be more specific as to what use case you're trying to achieve because by default, the gallery images work the same as the main product image where it can be scrolled and zoomed.

**Comment by Farallon5** [comment]
The need for clickable links in the gallery images especially comes into play when making those images display full column width, which is helpful for certain products. We use css like this to do it:

.postid-16912 .woocommerce-product-gallery__image {
    width: 100% !important;
}

Then, instead of the normal thumbnail (that you click to expand) the images become a fuller part of the product page design. It’s also a great way to balance a long 2-column product page where the right side is a ton of product description. The full-width gallery images in the left column take up what would otherwise be a long blank space. In the case of a product that is a live event you are selling tickets for, the full-width gallery images could be sponsor ads, or nice graphics with links to the streaming site where the event will be broadcast.

Our expectation would be that there would be the familiar way of adding custom links for any text or images for these images too.

Thanks!

**Comment by peterfabian** [comment]
Hi @Farallon5 

Thanks for submitting this idea. It seems to me it's more of a theme customization request that can perhaps be supported by Blocks once you'd be able to build your custom product page, or better served by a custom single product template from a theme. 

I don't think this is a typical use case and is probably better solved by other tools than changing the WC core itself, but we'll keep an eye on the popularity of this request and if it gets more support in the future, we'd be happy to reopen it. Hope that makes sense!
