### ISSUE TITLE
!!!!!!!!!!!!!! Important !!!!!!!!!!!!!!!!!!!!! When woocommerce is active, the admin brings the js files in the wp-content folders to the front end.

### ISSUE THREAD

**Issue by Ninetheme** [woothemes/woocommerce#35006]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When woocommerce is active, the admin brings the js files in the wp-content folders to the front end.
NOTE: it is clear default wordpress installation, you can test with any theme

### Expected behavior

Important hack problems - may be

### Actual behavior

When woocommerce is active, the admin brings the js files in the wp-content folders to the front end.

### Steps to reproduce

1. https://ninetheme.com/test2/
2. open firefox/chrome editor console
3. visit shop page https://ninetheme.com/test2/shop
4. check css js tabs

### WordPress Environment

it is frontend problem

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Hi @Ninetheme - I am not sure I understand what issue you're having. Could you please elaborate further as to what you mean by this report?

**Comment by ProdesignerAgency** [comment]
Its wird behavior:

when product is added to the cart (in storefront theme or others) i have this code added:

<img width="1219" alt="Zrzut ekranu 2022-10-11 o 22 53 55" src="https://user-images.githubusercontent.com/6230472/195196466-0fa45e26-7a0b-4992-9d95-b1869823c358.png">

BTW how to unset /remove all woocommerce blocks?
