### ISSUE TITLE
[COT/HPOS]: Add corresponding hooks for `untrash_post` for COT/HPOS implementation

### ISSUE THREAD

**Issue by iamdharmesh** [woothemes/woocommerce#35018]
### Describe the solution you'd like

I am working on the Deposits extension to add support for trash, untrash, and delete orders for COT/HPOS implementation. To handle, when a parent order is trashed related scheduled orders should get trashed, when parent order is untrashed/restored, related scheduled orders should get untrashed/restored and finally when parent order deleted, related parent order should get deleted as well.

We have added corresponding hooks for `wp_trash_post` and `delete_post` for COT implementation in PR https://github.com/woocommerce/woocommerce/pull/34858, but we still don't have support for `untrash_post` which I needed for restored related scheduled payment orders when parent order restored/untrashed.

### Describe alternatives you've considered

Alternatively, we may use the `woocommerce_order_status_changed` hook to check if the order gets updated from `trash` status to something else. 

### Additional context

Deposits issue https://github.com/woocommerce/woocommerce-deposits/issues/467

**Comment by barryhughes** [comment]
Thanks for flagging this, @iamdharmesh: we'll look into this.
