### ISSUE TITLE
Product creation experience: improve guidance about product image size/format

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35017]
**Description:** in #33660 we've added a message to include helpful guidance about product image size/format for new users. However, we received feedback that the message is sometimes distracting and unnecessary (#33660). We'll make some changes to focus the tooltip on new users.

**Acceptance criteria:**
- [ ] Add a help tip next to the button and only show the message when the user hovers the tip
<img width="476" alt="image (4)" src="https://user-images.githubusercontent.com/3380168/194869624-cff5b6fd-bc8f-486a-8e2e-d0c19e66b5ba.png">

- [ ] Only show the tip when the box is empty

**Comment by nathanss** [comment]
Hi @pmcpinto 

To confirm, do you want to remove what was added in #33660 and add the tooltip for both the Product image and Product gallery sections?

**Comment by jarekmorawski** [comment]
Correct! ✔️

**Comment by mattsherman** [comment]
@pmcpinto @jarekmorawski The mockup shows buttons, when currently these are links...

<img width="308" alt="Screenshot 2022-12-02 at 15 06 25" src="https://user-images.githubusercontent.com/2098816/205376873-adffa815-2069-48b1-999b-256a31721ed1.png">

Do we want to change the links to buttons as part of this issue?

**Comment by jarekmorawski** [comment]
Do you mean the `Set product image` and `Add product gallery images` links or the one in the help text (`How to prepare images?`)? If the former, it'd be nice for them to be buttons, but it's not part of this issue. Let's focus on the tooltip for now. The link from the help text won't be included in the tooltip (mostly because we can't put links in tooltips 🙈).

**Comment by mattsherman** [comment]
> Do you mean the Set product image and Add product gallery images links 

Yes, that's what I was referring to. Thanks!

**Comment by pmcpinto** [comment]
+1 on keeping the links for now. Thanks
