### ISSUE TITLE
[COT/HPOS] Investigate/Add adding `post_author` field to core DB schema.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#35022]
Some extension store data in the post_author field; we currently don't migrate it. This issue scopes investigating whether that's needed and adding the field if it is.

**Comment by coreymckrill** [comment]
@vedanshujain do you know a specific example of an extension that uses the `post_author` field for orders?

**Comment by coreymckrill** [comment]
I searched the (unzipped) all plugins repo using the following:

```
grep -nR -C 2 post_author ./ | grep -E -e "\.php[-+:]+[0-9]+[-+:]+.*order\b" | sort
```

There were a few results, but all were false positives. So it seems unclear that there's actually a use case for the `post_author` field. Perhaps we can deprioritize this unless an extension developer comes forward with a documented use case? @vedanshujain

**Comment by vedanshujain** [comment]
Yep, makes sense, thanks for doing the analysis, going to mark it as low prio.

**Comment by rrennick** [comment]
Here is a back reference to an [issue encountered with post_author](https://github.com/woocommerce/woocommerce/issues/21656). I thought of this because some of the larger shops looking to migrate to HPOS could be 5+ years old.

cc @vedanshujain @coreymckrill

**Comment by coreymckrill** [comment]
Thanks @rrennick! Do you think this means that we should, in fact, prioritize adding an `author` field to the wc_orders table? My read of that issue is that we aren't using `post_author` anymore, and presumably any current shops with orders older than that would have gone through upgrade routines by now. Plus my grepping efforts (above) didn't turn up anything in WC Subscriptions. But I could be misinterpreting what that issue is really saying.

**Comment by rrennick** [comment]
> Do you think this means that we should, in fact, prioritize adding an author field to the wc_orders table?

@coreymckrill I didn't go back and do a full refresh on the issue. I was mainly bringing it to attention here on the chance that an issue crops up over the next few months.

**Comment by ZILZAL** [comment]
This would be useful when giving specific permissions to shop managers to manage and see only thier own created orders.
i came across this thread when i was searching for this use.

**Comment by jorgeatorres** [comment]
Going to close this one as this hasn't come up again or at any point. We do have an open issue related to managing orders based on role (#39289), which possibly captures the above request.
