### ISSUE TITLE
[Enhancement]: REST API Orders

### ISSUE THREAD

**Issue by Tsonn** [woothemes/woocommerce#35035]
### Describe the solution you'd like

When updating an order status via REST API, there is no possible way to set this action as manual.
So the auto generated order note -eg. "Order status changed from Failed to On hold."- registers as a system note.
A "manual" parameter exists in woocommerce update_status() function.

It would be useful to be able to set this update action as manual because in this case the order note registers as "added by user" note and username of whom made this update is visible.

### Describe alternatives you've considered

Something like .post( 'orders/123', {status: 'failed', manual: true} );

**Comment by peterfabian** [comment]
Thanks @Tsonn that definitely sounds like a good improvement. If you'd like to take a stab at fixing it in `WC_REST_Orders_Controller::save_object` and submit a PR, we'd be happy to review it. Thanks!
