### ISSUE TITLE
Coupon amount is not deducted after order

### ISSUE THREAD

**Issue by Matze1006** [woothemes/woocommerce#35062]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a voucher is used for an order, the voucher amount is not reduced in the backend after the order. The voucher can thus be used multiple times. The usage is counted up, but the amount remains.

### Expected behavior

The voucher amount will be reduced after the order. Or set to 0

### Actual behavior

The voucher amount will not be reduced.

### Steps to reproduce

new installation without further settings
create product
create voucher
log out
Go to the store.
add product to shopping cart
pay with voucher
check voucher with admin

### WordPress Environment

7.0.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Matze1006** [comment]
https://user-images.githubusercontent.com/100772706/195443356-e78db097-58b8-415c-88d6-dcead10e4540.mp4

**Comment by roykho** [comment]
@Matze1006 - Thanks for reporting however I believe you didn't set this coupon correctly. According to your video, it shows unlimited use. The correct setting should look like this ![4wRrs2.png](https://user-images.githubusercontent.com/2132595/195458572-20a26d08-8471-4d57-903c-be7eedf55a17.png)

With that direction, you should be able to use it correctly so I will be closing this now.

**Comment by Matze1006** [comment]
Hello roykho, I probably did not describe the error correctly. It is a gift voucher. If a customer buys a voucher e.g. 50 €, then he can use the voucher until it is used up. 
E.g. 50 € start - sum x = remaining value. Unfortunately, the residual value is currently always the start value, because the sum X is not deducted. Even if I restrict the use to a maximum number. 

Thank you for your effort

**Comment by Matze1006** [comment]
@roykho sorry didn't link you

**Comment by roykho** [comment]
@Matze1006 - I believe you're looking for something like this https://woocommerce.com/products/gift-cards/

**Comment by Matze1006** [comment]
Hey @roykho , no I really know my way around. Please watch the video again and pay attention to the coupon amount. Before and after the order. The amount should have been reduced. My shop has been running for a few years now and until recently it worked great.

**Comment by roykho** [comment]
@Matze1006 - Unfortunately it was not designed to work that way as you can see in our documentation https://woocommerce.com/document/coupon-management/

Do you perhaps have a 3rd party plugin that works with WooCommerce in this way?
