### ISSUE TITLE
__experimentalSelectControl: Add async support

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#35076]
**Description**

The current [experimental select control](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/experimental-select-control) forces the consumer of the component to handle all the async logic, this is in theory fine, but will require quite a bit of boiler plate for any async fields.

The Select Control also makes it a bit tricky to notify the user when the dropdown is searching or not.

Here are a couple suggestions that should be explored and/or implemented as part of this issue:
- Allow the `getFilteredItems` callback to support the return of a promise.
- Allow the addition of `useDebounce` for either the `getFilteredItems` function or `onInputChange`, maybe this should be a default of 250ms that can be changed if needed?

See [this PR](https://github.com/woocommerce/woocommerce/pull/34949) and the comments left behind by @mattsherman  for some extra context.

**Acceptance criteria**

- [ ] The `getFilteredItems` prop should support setting it to a Promise
- [ ] The `getFilteredItems` prop should support setting it to a regular function
- [ ] The `getFilteredItems` prop should be debounced, so that it isn't called for every input change
- [ ] A loading/busy indicator should be displayed as the `suffix` when the `getFilteredItems` callback is pending

**Comment by mattsherman** [comment]
From [original PR](https://github.com/woocommerce/woocommerce/pull/34949):

> Why not just bake this into the base select control and have items and getFilteredItems support passing in a Promise? Or, maybe even just have getFilteredItems... do we really need both items and getFilteredItems? Does the select control need to ever know if it is dealing with "all" the items, or does it really just need to show and allow selection of the filtered items?

**Comment by mattsherman** [comment]
If we don't have any other instances of select controls right now where we need async support, this isn't high priority at this point.

**Comment by louwie17** [comment]
@mattsherman if not high priority then we should create a separate issue for this (if there isn't already one):

> A loading/busy indicator should be displayed when the getFilteredItems callback is pending

As this will be a design requirement. I know Ghidorah would like the ability to actually change the icon, so there may be a separate issue for it, this was discussed in this thread: p1666306876375659-slack-C01CMSA1VHS

**Comment by mattsherman** [comment]
The `suffix` icon/indicator functionality has been split into a separate issue: #35426

**Comment by AnnaMag** [comment]
@mdperez86 let's leave this change out and tackle when it is needed ( or time permitting at the end of the cycle).

**Comment by joshuatf** [comment]
>getFilteredItems support passing in a Promise

This is the way we handled this in the previous `SelectControl` component, but this is more opinionated and does not necessarily allow the consumer to customize this logic very much.

@mattsherman I'm not sure if you're still working on this, but I wonder if a separate component specific to async handling might be a better option than forcing a more opinionated structure on consumers.

@louwie17 it might be good to share some specific examples of the boilerplate so we can identify what's the most time consuming to write.

**Comment by mdperez86** [comment]
xp: 2

**Comment by joshuatf** [comment]
Some logic for this exists in https://github.com/woocommerce/woocommerce/blob/b186c77cbc61572d2a6e607d6faadf80226e0b1f/plugins/woocommerce-admin/client/products/fields/attribute-term-input-field/attribute-term-input-field.tsx#L155

I'm not completely opposed to implementing this directly within the `SelectControl` component, but I do think a new component that's a wrapper around `SelectControl` might be cleaner.

Estimate: 3

**Comment by mattsherman** [comment]
> I'm not completely opposed to implementing this directly within the SelectControl component, but I do think a new component that's a wrapper around SelectControl might be cleaner.

I think a single component would be cleaner. If we allow the props that provide/filter items to be Promises, we can also support them being regular functions. You can await non-Promises.

A wrapper where the only difference is the async support for handling items feels a bit unnecessary and I would be concerned that it makes it more confusing to choose the right component and also increases the maintenance cost (making sure that in the future the wrapper continues to be "just" a thin wrapper that adds async support and otherwise doesn't diverge from the non-async component).

But, I'm not dead-set against the wrapper approach. Just not in love with it.

Estimate: 3

**Comment by mattsherman** [comment]
> Or, maybe even just have getFilteredItems... do we really need both `items` and `getFilteredItems`? Does the select control need to ever know if it is dealing with "all" the items, or does it really just need to show and allow selection of the filtered items?

What do others think about this?

**Comment by mdperez86** [comment]
> What do others think about this?

I prefer `getFilteredItems` to be an event insted of a function that runs at render time. So the filtering happens on user interaction and not at render time. Which lead me to keep the items prop (which is more usual and natural) while the filtering process happens on interacting event.

cc: @mattsherman

**Comment by joshuatf** [comment]
> What do others think about this?

Downshift does need to know all the items it's dealing with for accessibility, unfortunately.

>I think a single component would be cleaner. If we allow the props that provide/filter items to be Promises, we can also support them being regular functions. You can await non-Promises.

If we think this pattern makes sense for all use-cases for the `SelectControl` component then I'm not opposed; let's just make sure it really works for all cases.

Though I'd like us to consider that batching (10 items at a time) and scrolling to trigger more items will be a follow-up to this.  If this all lives under the same folder, that's fine, but I don't want the main component to become overly complex in the process.

**Comment by louwie17** [comment]
> @louwie17 it might be good to share some specific examples of the boilerplate so we can identify what's the most time consuming to write.

Hmm yeah, given the `getFilteredItems` is currently called within the main component (on every render), we did probably have to create a separate state for `filteredItems`, something like this:
```javascript
const [ filteredItems, setFilteredItems ] = useState( [] );
const [ isLoading, setIsLoading ] = useState( false );
useEffect(() => {
   // we could push this to the consumer as a prop, or check if the return value of getFilteredItems and only call setIsLoading(true) if a promise is returned.
   setIsLoading(true); 
   // Promise.resolve will support both promises and values.
   Promise.resolve( getFilteredItems( ...args ) ).then( ( fItems ) => { 
      setIsLoading(false);
      setFilteredItems(fItems);
   });
}, [ inputValue, isFocused ]); // maybe remove isFocused?
```
The `isLoading` can toggle the post fix, or be used as a callback and have the consumer toggle the post/pre fix.
