### ISSUE TITLE
Audit action workflows to remove deprecated GitHub save-state/set-output commands.

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#35083]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I've noticed warnings about this in several of our actions. I assume that this won't be something with an urgent timeline, as many published actions probably utilize these outputs, but just getting it out there.

**Comment by samueljseay** [comment]
Just noting that there is not any use of `save-state` directly in any of our actions. So its just `set-output` we need to handle.
