### ISSUE TITLE
Feature compatibility and plugin-activating flows

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#35097]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Despite our work in #34879 and #35063, there are a still a few other flows/places that can lead to a plugin being activated and that are currently not being observed for possible conflicts with HPOS or other features:

1. Plugins on the **Plugins** screen that are installed but not active.
2. **Plugins > Add New**. Here you can search for a plugin and click "Activate".
3. **WC > Extensions > My Subscriptions** which displays a toggle to activate/deactivate the subscription and, in turn, calls `activate_plugin()` and `deactivate_plugin()`.
4. **WCCOM remote installation feature**. When you connect your site to WCCOM, purchase an extension and use the "Add to site" feature it'll not only install the extension but activate it automatically.

Given compatibility is declared via code, I'm not sure if we can fix that easily at this point. Even if we used headers or one of the other proposed solutions, only for (1) and (3) the plugin file is already in the web server and can be read. For the others the plugin information comes remotely or is handled entirely outside of WC.

**Comment by vedanshujain** [comment]
The current plan is to change the notification system little bit so that:

1. In the feature screen, currently, there is no warning before disabling the feature for pending sync. Disabling HPOS immediately switches over to the posts table, even if there are unsynced orders
2. We have a notification that appears when a plugin is active, which is not compatible but is only displayed for the plugin screen. We plan to display it on every screen, and elevate the severity to an `error` so that its displayed in red.

**Comment by Konamiman** [comment]
Created https://github.com/woocommerce/woocommerce/pull/35198 to address https://github.com/woocommerce/woocommerce/issues/35097#issuecomment-1280468370

**Comment by peterfabian** [comment]
One more scenario that we need to fix: **don't display any notice in the Plugin screens when the plugin is inactive**. It's incorrect to state a plugin is incompatible if it declared compatibility, but we just don't know yet, as the code hasn't run.

More internal ref: p1666700025757319-slack-C0E1AV8T0

**Comment by jorgeatorres** [comment]
After various iterations on the features controller, this no longer seems relevant.
