### ISSUE TITLE
Clearing the value of a fee item causes TypeError when saving order items

### ISSUE THREAD

**Issue by goransle** [woothemes/woocommerce#35093]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Clearing the value of a fee item on an order via the admin interface causes the following TypeError:
```sh
[14-Oct-2022 10:11:19 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int + string in /www/kinsta/publi
c/woo-local/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1784
Stack trace:
#0 /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(438): WC_Abstract_Order-
>calculate_totals()
#1 /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(1390): wc_save_order_items()
#2 /www/kinsta/public/woo-local/wp-includes/class-wp-hook.php(307): WC_AJAX::save_order_items()
#3 /www/kinsta/public/woo-local/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /www/kinsta/public/woo-local/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /www/kinsta/public/woo-local/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown in /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1784
[14-Oct-2022 10:16:55 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int + string in /www/kinsta/publi
c/woo-local/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1784
Stack trace:
#0 /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(438): WC_Abstract_Order-
>calculate_totals()
#1 /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(1390): wc_save_order_items()
#2 /www/kinsta/public/woo-local/wp-includes/class-wp-hook.php(307): WC_AJAX::save_order_items()
#3 /www/kinsta/public/woo-local/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /www/kinsta/public/woo-local/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /www/kinsta/public/woo-local/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown in /www/kinsta/public/woo-local/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1784
```

![image](https://user-images.githubusercontent.com/7478772/195823456-ca6985f2-be02-479b-8de6-fac73e13557e.png)

### Expected behavior

The fee should be set to the value of 0 without throwing an error, as it does when entering the number 0. 

(Alternatively, the user should not be able to save the order items in this state)

### Actual behavior

The user interface halts, and an error is logged.

### Steps to reproduce

1. Add a new order (/wp-admin/post-new.php?post_type=shop_order)
2. Add a fee with any value
3. Edit the total of the fee item by using the delete/backspace key. Should appear as 0
4. Click the Save button in the order items 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woo-local.local
Site address (URL): http://woo-local.local
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.1
PHP Version: 8.0.22
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 10.5.5-MariaDB-1:10.5.5+maria~focal
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: wp_
Total Database Size: 17.80MB
Database Data Size: 12.33MB
Database Index Size: 5.47MB
wp_woocommerce_sessions: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 30
acf-field-group: 9
attachment: 1
page: 8
post: 2
product: 37
product_variation: 115
shop_coupon: 1
shop_order: 151
shop_subscription: 80
ywraq-pdf-template: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.0.0

### Inactive Plugins (26) ###

Advanced Custom Fields: by WP Engine – 6.0.2
Akismet Anti-Spam: by Automattic – 4.2.5
Debug Log: by Andrew J Klimek/Sam – 0.3.3
Disable Admin Notices Individually: by Creative Motion <info@cm-wp.com> – 1.3.0
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.7

Git Updater: by Andy Fragen – 11.0.3
Git Updater PRO: by Andy Fragen – 2.0.0
Manage Notification E-mails: by Virgial Berveling – 1.8.2
Members: by MemberPress – 3.2.1
Nets Easy for WooCommerce: by Krokedil – 2.1.0
Ninja Forms: by Saturday Drive – 3.6.14
Precheckout for Nets Easy: by Gøran
Ken-Håvard
Sophie – 0.2.31

Query Monitor: by John Blackbourn – 3.10.1
Software libraries for WP Activity Log: by WP White Security – 1.0.4
TT2WOO: by Christer – 1.0.21
Woo-filters: by Sam
Goran and the Internets – 0.1.7

WooCommerce Subscriptions: by WooCommerce – 4.4.0
WP Activity Log (Premium): by WP White Security – 4.4.2.2
WP Activity Log for WooCommerce: by WP White Security – 1.4.4
WP GraphQL: by WPGraphQL – 1.12.0
WPGraphQL JWT Authentication: by WPGraphQL
Jason Bahl – 0.5.2

WPGraphQL Ninja Forms: by Giulio Ganci – 0.1.4
WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.11.2
WP Updates Notifier: by Scott Cariss – 1.6.0
write_log: by Sam and the Internets – 0.1
YITH WooCommerce Request A Quote Premium: by YITH – 4.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-15 08:23:48 +00:00
Options: ✔
Notes: 60
Onboarding: completed

### Action Scheduler ###

Complete: 587
Oldest: 2022-09-14 07:22:31 +0000
Newest: 2022-10-14 10:28:52 +0000

Pending: 19
Oldest: 2022-10-15 06:54:58 +0000
Newest: 2035-10-05 03:53:56 +0000

### Status report information ###

Generated at: 2022-10-14 10:31:22 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @goransle,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 7.0.0 version, and WordPress 6.0.2 version.

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/196161716-cbd0aca6-3f60-4dc7-9e9b-1d59c0b306b9.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.
