### ISSUE TITLE
[Enhancement]: Replace the trash can icon in the list item component

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35092]
### Describe the solution you'd like

Several people mentioned that the trash can icon used for removing items from lists in Attributes, Upsells, and Cross-sells draws too much attention and disturbs the element's visual balance.

I'd like to replace it with a simple X icon (`close-small` in the Gutenberg icon library. Note that there's also a larger X icon, but we should use the smaller one). Thank you!

![image](https://user-images.githubusercontent.com/79307566/195787315-a0bd8112-da0d-49d8-b504-44d8808ff456.png)

**Comment by louwie17** [comment]
> Several people mentioned that the trash can icon used for removing items from lists in Attributes, Upsells, and Cross-sells draws too much attention and disturbs the element's visual balance.

@jarekmorawski I assume this issue will only pertain to the work for the attributes list, given the upsells and cross-sells fields have not been implemented yet? so it would be done as part of the initial work for those fields?

**Comment by jarekmorawski** [comment]
> so it would be done as part of the initial work for those fields?

That's correct. We use the same list element in Attributes, Upsells, Cross-sells, Grouped Products, and Downloads. Most of them have not been implemented yet, but use the same principle and components, both design and code-wise.
