### ISSUE TITLE
Navigating to pages registered with URL parameter fully reloads the page instead of doing SPA navigation

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#35102]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I register the React-powered pages with URL parameter:

```js
addFilter( 'woocommerce_admin_pages_list', 'my_stable', ( pages ) => {
	return [
		...pages,
		{
			breadcrumbs: [
				__( 'My Stable', 'my-stable' ),
				__( 'Unicorn', 'my-stable' ),
			],
			title: __( 'Unicorn', 'my-stable' ),
			container: Unicorn,
			path: '/my-stable/unicorn/:uniname',
			wpOpenMenu: 'toplevel_page_my-stable',
			navArgs: {
				parent: 'my-stable/unicorn',
			},
		},
```

Then use WooCommerce navigation to navigate between individual pages, the full page reload happens instead of just SPA behavior.
![navigation](https://user-images.githubusercontent.com/17435/195880785-b2caae5f-741f-4e1b-8a89-5afe11ac8b60.gif)

This was an exact problem in AutomateWoo https://github.com/woocommerce/automatewoo/pull/1179/files/e448599fd61db9f374d51ae20bb937822c2e6b21

### Expected behavior

The page should not get fully reloaded, only the respective container should get updated.

### Actual behavior

The page fully reloads

### Steps to reproduce

1. Register pages in PHP
```php
wc_admin_register_page(
	[
		'id'     => 'automatewoo-analytics-foo',
		'title'  => 'Foo',
		'parent' => 'automatewoo-analytics',
		'path'   => '/automatewoo/analytics/foo'
   ]
);
wc_admin_register_page(
	[
		'id'     => 'automatewoo-analytics-bar',
		'title'  => 'Foo',
		'parent' => 'automatewoo-analytics',
		'path'   => '/automatewoo/analytics/bar'
   ]
);
```
2. Register navigation items in JS
```js
addFilter( 'woocommerce_admin_pages_list', 'automatewoo', ( pages ) => {
	return [
		...pages,
        {
			breadcrumbs: [
				__( 'AutomateWoo', 'automatewoo' ),
				__( 'Analytics', 'automatewoo' ),
			],
			title: __( 'Analytics', 'automatewoo' ),
			container: Analytics,
			path: '/automatewoo/analytics/:report',
			navArgs: {
				parent: 'automatewoo/analytics',
			},
		},
   ];
});
```
3. Click on any link in `WooCommerce > AutomateWoo > Analytics`

### WordPress Environment

<details>
<summary>SSR</summary>

`
### WordPress Environment ###

WordPress address (URL): https://wp600wc700.test
Site address (URL): https://wp600wc700.test
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.7
PHP Version: 7.4.22
PHP Post Max Size: 150 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.33
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 7.81MB
Database Data Size: 4.88MB
Database Index Size: 2.93MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
aw_workflow: 3
follow_up_email: 1
page: 9
post: 2
product: 18
product_variation: 7
revision: 2
shop_coupon: 7
shop_order: 9
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

AutomateWoo - Birthdays Add-on: by WooCommerce – 1.3.11
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.11
AutomateWoo: by WooCommerce – 5.5.19
Jetpack: by Automattic – 11.3.2
WCS Variables: by WooCommerce – 0.1
Follow-Up Emails: by WooCommerce – 4.9.30
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.14
WooCommerce Payments: by Automattic – 4.7.2 (update to version 4.8.1 is available)
WooCommerce: by Automattic – 7.0.0-beta.2 (update to version 7.0.0 is available)

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 5.0
Google Listings and Ads: by WooCommerce – 2.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Coupon Campaigns & Tracking: by WooCommerce – 1.1.25
WooCommerce Sales Report Email: by WooCommerce – 1.1.27

### Settings ###

API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-15 08:17:07 +00:00
Options: ✔
Notes: 55
Onboarding: completed

### WooCommerce Payments ###

Version: 4.7.2
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 181
Oldest: 2022-09-29 08:23:55 +0000
Newest: 2022-10-14 14:24:22 +0000

Pending: 4
Oldest: 2022-10-14 15:34:00 +0000
Newest: 2022-10-15 14:22:02 +0000

### Status report information ###

Generated at: 2022-10-14 15:22:23 +00:00
`

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AnnaMag** [comment]
We aren't actively working on the new navigation. Will @woocommerce/automata add/keep it to their backlog for prioritization? cc @eason9487

**Comment by eason9487** [comment]
Hi @AnnaMag, thanks for pinging us.

> Will @woocommerce/automata add/keep it to their backlog for prioritization? cc @eason9487

I updated AutomateWoo's issue but didn't change its priority as other follow-up issues within it are related to the classic/original navigation or the relevant functions.

**Comment by AnnaMag** [comment]
Thanks, I will close this issue for the time being.
