### ISSUE TITLE
Tracks: revise the events presence and naming in the form MVP.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#35108]
Verify the placement of the Tracks events within the new form and the flow entry points:

- [ ] flow for new users
- [ ] flow for the existing users

**Comment by pmcpinto** [comment]
@AnnaMag let me know if you need help with this.

**Comment by AnnaMag** [comment]
@octaedro @pmcpinto afaiu this issue is blocked by the new implementation, so we'd need to revisit it with new experience in place.

**Comment by AnnaMag** [comment]
@louwie17 @octaedro this issue was meant as a pre-release scan for completeness, executed at the end of cycle preceding the roll-out. We can assume that the tracking will be included on an ongoing basis during development.
As such I can see how it can belong to either of the squads.
