### ISSUE TITLE
Paragraph Tag Is Being Stripped from Customer Note Section

### ISSUE THREAD

**Issue by serafintechnology** [woothemes/woocommerce#35112]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The paragraph tag that's added to custom notes section under the shipping fields on each order is being stripped. I've tried this on several sites and believe this is a bug related to 7.0 In 6.9.4 it's fine.

I haven't left a system report because it's happening on 5 clean brand new installs and one client site as well.

I've created a loom for you to follow and replicate the process.

### Expected behavior

Separate lines when space is entered which ultimately adds a P Tag

### Actual behavior

P Tag being stripped out instead

### Steps to reproduce

Made a [loom](https://www.loom.com/share/60d8e26f41a94cff915c3d000fd4b452) for ya

### WordPress Environment

Haven't left a system report because it's happening on multiple installs

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by serafintechnology** [comment]
@roykho thank you for the update. Appreciate it.

**Comment by swatipawarGS** [comment]
Hi @serafintechnology,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 7.0.0 version, and WordPress 6.0.2 version.

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/196355789-75b526dd-cec3-47a9-b504-2b5074e633b4.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by Brianmitchtay** [comment]
This bug has been noted in a recent support ticket as well, and is a critical issue for that user: 5640654-zen

The user believes that the PR that caused this change is: #34477

**Comment by barryhughes** [comment]
Thanks for the report, we'll look into a fix :+1:
