### ISSUE TITLE
CES: Add prompt for modal feedback after user creates first product using the new experience.

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35129]
**Description:** we want to add a CES prompt with more visibility in the new add/edit product experience we'll test to collect more feedback during the alpha and beta stages. 

**Acceptance criteria:**
- [ ] Display the following bar at the bottom of the screen after the user creates a product using the new experience. The bar will only be dismissed when the user clicks on the "X" button. The "Share feedback" will open the CES modal. We don't need the "Turn it off" option for now. It will depend on the opt-in and opt-out flows (WIP).

<img width="929" alt="Captura de ecrã 2022-10-17, às 16 29 58" src="https://user-images.githubusercontent.com/3380168/196220119-4850d6a3-a0aa-4360-abb8-e6a88ce1142f.png">

**Design:**
5sAIeTRd9Yp7nSCT33BAWz-fi-5206%3A179833

**Event tracking:**
We need to add new values to the `action` of all the CES-related events to track the feedback on the new product UI: `new_product_add_publish` and `new_product_update`

**Comment by louwie17** [comment]
> The bar will only be dismissed when the user clicks on the "X" button.

Should this persist on a browser refresh?

**Comment by lukecav** [comment]
The new product editor will be opt-in or opt-out when available in beta?

**Comment by pmcpinto** [comment]
> The new product editor will be opt-in or opt-out when available in beta?

Hi Luke, we're still in the early stages of exploring a new experience, so it will be opted out by default. We plan to share more details soon.

**Comment by pmcpinto** [comment]
> Should this persist on a browser refresh?

Lourens, what's easier to implement?

**Comment by louwie17** [comment]
> Lourens, what's easier to implement?

The easier one is not to persist on browser refresh, or at-least I know we support that right now, so it will take minimal effort.
I am not a 100% sure if we CES/notices working to persist on page refresh, I am leaning towards not. Although looking at the CES tracks code in particular it looks like it will require minimal **extra** effort to persist it on refresh.

**Comment by louwie17** [comment]
@pmcpinto @jarekmorawski do we have a link to the Figma design for this?
I am just slightly confused if this bar is referring to our usual `notices` at the bottom left of the screen, or a new form of notice that spans across the entire bottom of the screen?

**Comment by jarekmorawski** [comment]
Added designs to the issue description.

**Comment by louwie17** [comment]
> Added designs to the issue description.

Thanks @jarekmorawski, although those designs link to the CES updates in the existing product edit form (legacy UI), but not the CES updates for the new product form. Do you have similar designs for the new product form?

**Comment by jarekmorawski** [comment]
Oh, right! My bad. I've updated the description.

**Comment by louwie17** [comment]
> Oh, right! My bad. I've updated the description.

Awesome, thanks! That looks good!

I do have one additional question now (cc @jarekmorawski ):
- Do you think we will use this same bar at the bottom of the screen for other notifications within the product management screen? Or will it only be for this specific CES prompt?

**Comment by pmcpinto** [comment]
AFAIK this will only be used for this prompt. @jarekmorawski to confirm, thanks

**Comment by jarekmorawski** [comment]
I confirm. We might use it in the future in a different place, but likely only for collecting feedback.

**Comment by louwie17** [comment]
@pmcpinto @jarekmorawski one last question for this issue.
Given we have two different CES action events for this `new_product_add_publish` and `new_product_update`, do we expect the bar to also show up for the two different actions. Meaning that if a user saved a product as draft and answered the CES, when they publish it, they will see it again, but not there after?

Or do we only want to show it once? but still accurately record the action that triggered the CES (saving draft or publishing)

**Comment by pmcpinto** [comment]
Hey @louwie17 the bar should remain at the bottom of the page after the user creates a product using the new experience. LMK if you have more questions.

**Comment by louwie17** [comment]
> the bar should remain at the bottom of the page after the user creates a product using the new experience. LMK if you have more questions.

@pmcpinto does the bar even stay after the user has given feedback?
My question was more so in regards to what we do after the user submits their feedback, will we hide the bar, even if the user does a publish after?

**Comment by pmcpinto** [comment]
The goal during the beta phase is to keep the bar after the user submits feedback, unless he clicks on the X button

**Comment by louwie17** [comment]
If we do keep the bar around will it matter if we use `new_product_add_publish` or the `new_product_update` action, should we maybe only use one of those?

**Comment by pmcpinto** [comment]
I see what you mean: considering that the bar will be displayed permanently after publishing a product, it's easier to track one value rather than trying to distinguish if the feedback was shared after the publish or update action, correct?

**Comment by louwie17** [comment]
> I see what you mean: considering that the bar will be displayed permanently after publishing a product, it's easier to track one value rather than trying to distinguish if the feedback was shared after the publish or update action, correct?

correct!

**Comment by louwie17** [comment]
Although we could potentially make the logic that, if a user hasn't published yet we use the `new_product_update`, and if a user publishes a product we only use `new_product_add_publish` going forward.
That is only if we think there could be a discrepancy between users publishing their product for the first time and those that don't.

**Comment by pmcpinto** [comment]
Ok. So we can keep it simple and have the same value (`new_product`) when the CES is submitted after the product was published or updated.
