### ISSUE TITLE
CES: additional add/edit product prompts

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35127]
**Description:** we want to include some additional prompts to the add/edit product, as it's our current focus. This will also be useful to test the effectiveness of different prompts and eventually apply them to other parts of the product experience.

**Acceptance criteria:**
- [ ] The changes should only be applied when the user is adding or editing a product 
- [ ] Include a "Feedback" icon in the WC Admin navbar
<img width="234" alt="Captura de ecrã 2022-10-17, às 16 18 35" src="https://user-images.githubusercontent.com/3380168/196216800-8383adef-77f0-4845-bbff-6e7a97ba1112.png">

- [ ] Show the CES modal when the user clicks on the icon
- [ ] Display a spotlight near the Feedback button when the user takes more than 7 mins to create a product (the copy needs to be updated)
<img width="405" alt="Captura de ecrã 2022-10-17, às 16 14 47" src="https://user-images.githubusercontent.com/3380168/196216145-e8f9d77d-76b6-446a-bbec-fb8c509bf48e.png">
- [ ] Display the CES snackbar when the user updates the product for the 3rd time

**Event tracking:**
TBD

**Comment by jarekmorawski** [comment]
How about this for the spotlight copy? A bit more casual and passive, but also tailor to this specific use case.

> We noticed you have been working hard on this product for a few minutes now. Is there something you’re struggling with? Share your feedback.

**Comment by pmcpinto** [comment]
@jarekmorawski overall, the copy looks good. I'm just unsure about the "we noticed" and the "working hard" terms. What do you think about this?

> You have been working on this product for a few minutes now. Is there something you’re struggling with? Share your feedback.

**Comment by louwie17** [comment]
> Display a spotlight near the Feedback button when the user takes more than 7 mins to create a product (the copy needs to be updated)

The copy implies the user hasn't done anything on the page for 7min, is that what we should take into account as well? Meaning that if a user switches through tabs or is writing in the product description we keep resetting the timer?
Meaning that the popup will only show if the user hasn't clicked or typed on the page for 7min.

**Comment by pmcpinto** [comment]
> Meaning that if a user switches through tabs or is writing in the product description we keep resetting the timer?

No. It should be 7 mins total independent of user interaction. Makes sense?

**Comment by louwie17** [comment]
> No. It should be 7 mins total independent of user interaction. Makes sense?

So not dependant on how active the user was on that page? That sounds good!

Are we limiting to how often this popup is being shown? or anytime a user is on the specific page longer than 7min?
Or maybe only for users that have a newer store or haven't completed the task list yet?

**Comment by pmcpinto** [comment]
> So not dependant on how active the user was on that page? That sounds good!

Yes.

> Are we limiting to how often this popup is being shown? or anytime a user is on the specific page longer than 7min?
Or maybe only for users that have a newer store or haven't completed the task list yet?

As the starting point, I think we should only show it once. We can evaluate whether we should increase the frequency depending on the effectiveness of this placement.

**Comment by joelclimbsthings** [comment]
I've broken this out into separate issues, closing this one.
