### ISSUE TITLE
Missing woocommerce session cookie unset when updating WP Salt keys 

### ISSUE THREAD

**Issue by andreDane** [woothemes/woocommerce#35120]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,
I found out that when the WP salt keys are updated, currently logged in users are logged out but then cannot log in until the `wp_woocommerce_session_{hash}` cookie is manually emptied.

### Expected behavior

1. Update WP Salt keys. 
2. Logged-in users are disconnected. 
3. Users return (or are redirected) to the login page. 
4. Users fill and submit login form. 
5. Users log in.

### Actual behavior

1. Update WP Salt keys. 
2. Logged-in users are disconnected. 
3. Users return (or are redirected) to the login page. 
4. Users fill and submit login form. 
5. Page reloads and nothing happened. Users are still logged out and login form is emptied. No error is displayed.

The only way to log in again is by manually emptying cookies.
By futher investigating we found that the cookie causing this behavior was the 'wp_woocommerce_session_{hash}' cookie.

It should be removed when changing WP Salt Keys.

### Steps to reproduce

1. Log in to your site. 
2. Update the WP salt keys. 
3. Check that you have been logged out. 
4. Go to the login page. 
5. Fill in the login form and submit. 
6. The page will be reloaded but you will remain logged out and the login form will be empty.

### WordPress Environment

```
### WordPress Environment ###

WC Version: 7.0.0
WP Version: 6.0.2
WP Multisite: –

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 8.0.17

### Database ###

WC Database Version: 6.6.1

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.0.0

### Theme ###

Name: Storefront Child
Version: 1.0
Parent Theme Name: Storefront
Parent Theme Version: 4.1.3
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jacoswan** [comment]
Also reported in 7323472-zen

**Comment by coreymckrill** [comment]
Following the steps above, we were not able to reproduce the issue. Does this still happen for you on the latest version of WooCommerce?

**Comment by andreDane** [comment]
Hi,
I tested it with the actual WC version and I confirm the bug is no more present.
Thank you
