### ISSUE TITLE
CES: Add additional question to CES modal

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35124]
**Description:** we're introducing one additional question about usefulness (similar to the [UX-lite survey](https://href.li/?https://measuringu.com/from-umux-lite-to-ux-lite/)) to allow us to collect feedback about an additional dimension. Currently, we're only collecting feedback on ease of use. 

**Acceptance criteria:**
- [ ] Add a second question with the 1-5 scale, as we have in the first question
- [ ] The copy should be adapted according to each feature: The [feature] functionality meets my needs
- [ ] The 2nd question should be added to all the features where we have the CES

![CES modal](https://user-images.githubusercontent.com/3380168/196204734-19848715-3673-43a9-91fe-e53d9060434d.png)

**Event tracking:**

- [ ] Keep the score prop for the 1st question
- [ ] Create a new prop for the 2nd question, something like: score_2nd_question
- [ ] Create a new prop to record the combined scores: score_combined

**Comment by pmcpinto** [comment]
@jarekmorawski can you add the 2nd question copy for each feature? Thanks
Store setup
Add product
Update product
Configure settings
Update order
Filter Analytics
Import Products
Product Categories
Product Attributes
Product Tags
Search (orders, products, customers)

**Comment by jarekmorawski** [comment]
> Store setup

`The store setup is easy to complete.`

`The store setup process meets my needs.`

> Add product

`The product creation screen is easy to use.`

`The product creation screen's functionality meets my needs.`

> Update product

`The product update process is easy to complete.`

`The product update process meets my needs.`

> Configure settings

`The settings screen is easy to use.`

`The settings screen's functionality meets my needs.`

> Update order

`The order details screen is easy to use.`

`The order details screen's functionality meets my needs.`

> Filter analytics

`The filters in the analytics screen are easy to use.`

`The filters' functionality meets my needs.`

> Import products

`The product import process is easy to complete.`

`The product import process meets my needs.`

> Product Categories

`The product category details screen is easy to use.`

`The product category details screen's functionality meets my needs.`

> Product Attributes

`Product attributes are easy to use.`

`Product attributes' functionality meets my needs.`

> Product Tags

`The product tag details screen is easy to use.`

`The product tag details screen's functionality meets my needs.`

> Search

`The search feature in WooCommerce is easy to use.`

`The search's functionality meets my needs.`

**Comment by louwie17** [comment]
Adding some extra context from a development context:
We currently trigger CES using the `enqueue_to_ces_tracks` PHP function in conjunction with a CES data store and component here: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-admin/client/customer-effort-score-tracks. The `enqueue_to_ces_tracks` is in our Internal folder, so we shouldn't need to worry about backwards compatibility.

Neither of these places are written in a manner that makes adding a second question easy. We have to either hardcode the support for a second question, or do a bigger re-factor to allow for any number of questions.
I would prefer the latter.

In any case, this will take some extra work, and it might be worth splitting this issue into two parts (or two PRs), the first one adding support to our CES logic for multiple questions. Then the second adding the above copy and questions.

**Comment by louwie17** [comment]
Adding some extra context from a development context:
We currently trigger CES using the `enqueue_to_ces_tracks` PHP function in conjunction with a CES data store and component here: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-admin/client/customer-effort-score-tracks. The `enqueue_to_ces_tracks` is in our Internal folder, so we shouldn't need to worry about backwards compatibility.

Neither of these places are written in a manner that makes adding a second question easy. We have to either hardcode the support for a second question, or do a bigger re-factor to allow for any number of questions.
I would prefer the latter.

In any case, this will take some extra work, and it might be worth splitting this issue into two parts (or two PRs), the first one adding support to our CES logic for multiple questions. Then the second adding the above copy and questions.

**Comment by AnnaMag** [comment]
> splitting this issue into two parts (or two PRs), the first one adding support to our CES logic for multiple questions. Then the second adding the above copy and questions.

@louwie17 let's do this as part of grooming 🙏

**Comment by joelclimbsthings** [comment]
I'd tend to agree @louwie17 , thanks for looking into this. The only potential counter-point would be that my understanding is that we'd always want to keep this form/experience as simple and quick as possible to encourage participation, so it might not be a feature that we would tend to expand with yet further questions. I'd have to defer to @pmcpinto on if that would be the case.

If we expect there may be additional expansion in the future I'd definitely be in favor in splitting this out and laying the foundation first. In anticipation of that I've [created this issue](https://github.com/woocommerce/woocommerce/issues/35299), and this one can capture the added content as @louwie17 suggested.

**Comment by pmcpinto** [comment]
I think that hardcode is the best approach for now. Eventually, we'll need to tweak the CES questions for the new product creation exp, but it can also be hardcoded.

**Comment by joelclimbsthings** [comment]
Thanks @pmcpinto , a few questions. 

Right now we're recording the scores resulting from the CES modal using the `ces_feedback` event with the following payload:
```
{
	action: CUSTOMER_EFFORT_SCORE_ACTION,
	score: recordedScore,
	comments: comments || '',
	store_age: storeAgeInWeeks,
}
```

The `score` is just a number, which won't capture more than one question of course. Is there a preferred format on how multiple scores will be passed? I'm not sure how this is parsed on your side, but we could pass both as a string (ie `"4|2"`) or an array (ie `[3, 2]`), or any other variation. It might be best to structure it in a way that is somewhat backwards compatible, so that you could recognize the data properly before/after the change, but this will depend on how parsing happens on the other side.

Also, should the feedback from the "how is that screen useful to you..." question just be passed within the `comments` property, or would you prefer a new one?

_Edit:_ I came up with another question. As it is now, the label shown on the notice is the same as the question. For instance, after adding a product the user sees:

![image](https://user-images.githubusercontent.com/444632/198739575-bdb1c0b9-c6bc-43d0-87ac-0b9971b92ca9.png)

The text on that notice being the same as the question. With the new design the first question is:
> The product creation screen is easy to use

Which wouldn't work well as the notice text. Should we just keep the _same_ text for the notice as we current have, and then add the questions as well as detailed above? So that the "add product" example would be as follows:

**Notice:** How easy was it to add a product?
**Question 1:** The product creation screen is easy to use.
**Question 2:** The product creation screen's functionality meets my needs.

**Comment by pmcpinto** [comment]
@joelclimbsthings here's my feedback:

> The score is just a number, which won't capture more than one question of course. Is there a preferred format on how multiple scores will be passed? I'm not sure how this is parsed on your side, but we could pass both as a string (ie "4|2") or an array (ie [3, 2]), or any other variation. It might be best to structure it in a way that is somewhat backwards compatible, so that you could recognize the data properly before/after the change, but this will depend on how parsing happens on the other side.

What do you think about doing the following to ensure some backwards compatibility:
- Keep the `score` prop for the 1st question
- Create a new prop for the 2nd question, something like: score_2nd_question
- Create a new prop to record the combined scores: score_combined

> Also, should the feedback from the "how is that screen useful to you..." question just be passed within the comments property, or would you prefer a new one?

We can use the `comments` prop.

> Edit: I came up with another question. As it is now, the label shown on the notice is the same as the question. For instance, after adding a product the user sees:

Maybe we should use the modal title in the snackbar. For example, "How's your experience with editing products?"

@jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
That's precisely how I imagined it. Having an additional prop for the second question could help us easily analyze the data.

**Comment by joelclimbsthings** [comment]
Thanks @pmcpinto ! Couple follow-ups:
- I noticed that the original description of this issue says to change score properties in tracking to `ease_of_use_score` and `usefulness_score`. Would you rather stick to that than the `score_2nd_question` you mentioned?
- The previous behavior of the text area at the bottom is that it only displays when the score is 1-2; is that behavior we want to keep, or to display it at all times?
- Also, that text area has the label text `How is that screen useful to you? What features would you add or change?`
I'm guessing we're keeping that copy the same for all events?

**Comment by pmcpinto** [comment]
@joelclimbsthings here's my feedback:

> I noticed that the original description of this issue says to change score properties in tracking to ease_of_use_score and usefulness_score. Would you rather stick to that than the score_2nd_question you mentioned?

Let's use the approach I suggested in this [comment](https://github.com/woocommerce/woocommerce/issues/35124#issuecomment-1296952568). I'll update the AC

> The previous behavior of the text area at the bottom is that it only displays when the score is 1-2; is that behavior we want to keep, or to display it at all times?

I think we should display the text area when the score is 1-2 in one of the two questions. Makes sense? 

> Also, that text area has the label text How is that screen useful to you? What features would you add or change?
I'm guessing we're keeping that copy the same for all events?

Yes. Thanks

**Comment by joelclimbsthings** [comment]
@pmcpinto @jarekmorawski What is the expectation for the behavior of the _Simple CES component_, as was implemented [here](https://github.com/woocommerce/woocommerce/pull/32538)? As it is now you can record your score just my selecting it within the page, and if it's a score of 1-2 it will display the entire CES modal. Since we're modifying the modal to add a second question there's a disparity here on what we're recording in terms of the scores.

We _could_ just record the first score if they click a positive score inline, and then record both scores if they trigger the modal and rate both. Any thoughts?

Also @jarekmorawski The modal header style in the screenshot above shows an altered appearance, with the bottom-border and the "?" icon. Do we want to implement that here? It would differ from the current appearance, as well as what I'm seeing on other modals (such as add attribute). Here's the current appearance:

![image](https://user-images.githubusercontent.com/444632/203170341-6bc89886-ce69-4b02-8d74-8a764e2b1397.png)

**Comment by pmcpinto** [comment]
@joelclimbsthings will it be easier if we show all the fields by default? 1st question, 2nd question and comments field

**Comment by joelclimbsthings** [comment]
@pmcpinto , I have that part already implemented in the standard CES modal, but if I understand correctly that wouldn't influence the Simple CES Component (only used for setup complete) as I mentioned. With that they're rating without seeing any questions at all other than "How was your experience?" : 

![image](https://user-images.githubusercontent.com/444632/203368162-d40fa08e-a72c-425d-b007-adc0f94f2880.png)

**Comment by pmcpinto** [comment]
Gotcha. In this use case, I think it would be better to open the modal after the user selects one of the emojis to complete the survey. Makes sense? @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
> Gotcha. In this use case, I think it would be better to open the modal after the user selects one of the emojis to complete the survey.

I'd stick to the emojis and record a one-dimensional answer here. The goal for this interaction is to collect the feedback and let people get on with their lives (finishing store setup is a major milestone, and merchants want to start doing business ASAP). There's nothing in this design that suggests that a modal will pop up, and it can become a pain point.

> Also @jarekmorawski The modal header style in the screenshot above shows an altered appearance, with the bottom-border and the "?" icon. Do we want to implement that here? It would differ from the current appearance, as well as what I'm seeing on other modals (such as add attribute). Here's the current appearance:

We can implement it without the "?" icon 👍

**Comment by joelclimbsthings** [comment]
> I'd stick to the emojis and record a one-dimensional answer here.

Thanks @jarekmorawski , to make sure I understand we wouldn't be triggering the modal at all then from that component? The current implementation is that it triggers the modal for a score of 1-2, but it's easy to change.
