### ISSUE TITLE
CES: exit prompt

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35126]
**Description:** we only trigger the CES when the user completes a task, which can be influenced by survivorship bias. We want to test showing the prompt at a different stage of the flow to collect feedback from users who don't complete the task.

**Acceptance criteria:**

- [ ] Show the CES snackbar after the users navigate away from a task without completing it (add a product, configure settings, etc). The snackbar should be displayed on the screen that follows the incomplete task. For example, if the user is in the add product screen and navigates to the home screen without adding a product, the CES should be displayed on the home screen.
- [ ] This should be applied to any feature where we fire the CES

**Event tracking:**
We need to add a new prop to `wcadmin_ces_snackbar_view`, `wcadmin_ces_snackbar_dismiss`, `wcadmin_ces_view`, and `wcadmin_ces_feedback`, to understand how many users share feedback without completing the task:

`ces_location`: inside feature | outside feature

**Events:**
- [x] Add a product (new UI)
- [x] Update product (new UI)
- [x] Add a product (current UI)
- [x] Update product (current UI)
- [x] Change setting
- [x] Edit order (any of the edit order events) https://github.com/woocommerce/woocommerce/pull/35762
- [x] Filter analytics (any action on the analytics reports) https://github.com/woocommerce/woocommerce/pull/35986
- [x] Import Products https://github.com/woocommerce/woocommerce/pull/35996
- [ ] Product Categories
- [ ] Product Attributes
- [ ] Product Tags
- [ ] Search (orders, products, customers)

**Comment by jarekmorawski** [comment]
LGTM. I'd only add a criterion to show the prompt once for the setup process. Otherwise, we'll risk annoying the users and getting skewed results.

**Comment by pmcpinto** [comment]
> LGTM. I'd only add a criterion to show the prompt once for the setup process. Otherwise, we'll risk annoying the users and getting skewed results.

@jarekmorawski good point. Maybe this prompt should only be displayed once in each feature. What do you think?

**Comment by louwie17** [comment]
Do we want to do this for all the tasks triggered from the task list?
As far as I am aware we don't explicitly keep track of a user when they are working on a specific task or not (meaning we don't know if a user is actually in the middle of a task list task, or just got there some other way).

Following what a user is doing might be a bit tedious to do and prone to error, but we could have some specific guidelines/actions that we can keep track off and trigger it in those situations.
For example: If a user is on the add new product screen and exits the page (when no other products have been created yet), this is probably the simplest example.

In relation to the product screen, currently we show a `Changes you made may not be saved` browser alert if a user made edits and wanted to leave, should the CES show up before this alert box? or after? Or only once they re-directed to the new page and we show a notice then?
Preventing a user from exiting a page just to show the CES might be a bit to much, and I could see users not liking that, but then again we will only do it once.

**Comment by louwie17** [comment]
Do we want to do this for all the tasks triggered from the task list?
As far as I am aware we don't explicitly keep track of a user when they are working on a specific task or not (meaning we don't know if a user is actually in the middle of a task list task, or just got there some other way).

Following what a user is doing might be a bit tedious to do and prone to error, but we could have some specific guidelines/actions that we can keep track off and trigger it in those situations.
For example: If a user is on the add new product screen and exits the page (when no other products have been created yet), this is probably the simplest example.

In relation to the product screen, currently we show a `Changes you made may not be saved` browser alert if a user made edits and wanted to leave, should the CES show up before this alert box? or after? Or only once they re-directed to the new page and we show a notice then?
Preventing a user from exiting a page just to show the CES might be a bit to much, and I could see users not liking that, but then again we will only do it once.

**Comment by pmcpinto** [comment]
> Do we want to do this for all the tasks triggered from the task list?
As far as I am aware we don't explicitly keep track of a user when they are working on a specific task or not (meaning we don't know if a user is actually in the middle of a task list task, or just got there some other way).
> Following what a user is doing might be a bit tedious to do and prone to error, but we could have some specific guidelines/actions that we can keep track off and trigger it in those situations.
For example: If a user is on the add new product screen and exits the page (when no other products have been created yet), this is probably the simplest example.

Yeah, this can be tricky to implement in the setup experience, as it's composed of different tasks. I'd exclude the setup from this implementation. 

> In relation to the product screen, currently we show a Changes you made may not be saved browser alert if a user made edits and wanted to leave, should the CES show up before this alert box? or after? Or only once they re-directed to the new page and we show a notice then?

We should only show it only once they are re-directed to the new page, @jarekmorawski in case you have anything to add.

**Comment by jarekmorawski** [comment]
> We should only show it only once they are re-directed to the new page, @jarekmorawski in case you have anything to add.

That's correct. The user has to click through the unsaved changes modal and go to the new page before seeing the CES modal.

**Comment by joelclimbsthings** [comment]
If we're not using this in the `setup` experience, I may need more clarity on in what exact circumstances we _do_ want to use it. Can you provide a list @jarekmorawski or @pmcpinto ?

**Comment by pmcpinto** [comment]
Here's the list, organized by priority:

Add a product (new UI) 
Update product (new UI) 
Add a product (current UI) 
Update product (current UI) 
Change setting 
Edit order (any of the edit order events)
Filter analytics (any action on the analytics reports)
Import Products
Product Categories
Product Attributes
Product Tags
Search (orders, products, customers)

**Comment by louwie17** [comment]
@pmcpinto do we have any specific copy on what the CES notice should say? And will the copy be unique for each item the user leaves behind?

**Comment by pmcpinto** [comment]
The copy for the product experience is available here: 5sAIeTRd9Yp7nSCT33BAWz-fi-8421%3A457630&t=UYPEf8EZPOOsRXaE-0

@jarekmorawski can you add the copy for each action? Thanks

**Comment by louwie17** [comment]
Thanks @pmcpinto!
One additional question in terms of the actions to use, given we are adding the `ces_location` do we still want to have unique `exit` actions for each of the items to clearly differentiate the type of feedback, or would the `ces_location` set to `outside` be enough?

**Comment by jarekmorawski** [comment]
> Add a product (new UI)

`💬  How is your experience with editing products? Share feedback`

> Update product (new UI)

`💬  How is your experience with updating this product? Share feedback`

> Add a product (current UI)

`💬  How is your experience with editing products? Share feedback`

> Update product (current UI)

`💬  How is your experience with updating this product? Share feedback`

> Change setting

`⚙️  Did you find the right setting? Share feedback`

> Edit order (any of the edit order events)

`📦  How easy or difficult was it to update this order? Share feedback`

> Filter analytics (any action on the analytics reports)

`📊  Did you find the data you were looking for? Share feedback`

> Import Products

`🔄  How is your experience with importing products? Share feedback`

> Product Categories

`✅  How is your experience with updating categories? Share feedback`

> Product Attributes

`ℹ️  How is your experience with updating attributes? Share feedback`

> Product Tags

`🏷️  How is your experience with updating tags? Share feedback`

> Search (orders, products, customers)

`🔎  Did you find what you were looking for? Share feedback`

**Comment by pmcpinto** [comment]
@jarekmorawski thanks for sharing the copy for each action, but in this case, we're targeting users who don't complete the action. So I feel that they copy should be different. Makes sense?

**Comment by pmcpinto** [comment]
> One additional question in terms of the actions to use, given we are adding the ces_location do we still want to have unique exit actions for each of the items to clearly differentiate the type of feedback, or would the ces_location set to outside be enough?

Lourens, sorry, I'm not sure if you're following. Do you have an example of what could be the unique exit action?

**Comment by louwie17** [comment]
> Lourens, sorry, I'm not sure if you're following. Do you have an example of what could be the unique exit action?

@pmcpinto well for the product publish in the current UI we use the `product_add_publish` or `product_update` action for example, I was curious if we wanted to use something different for the exit CES feedback, like `exit_product_update`, so you can more clearly differentiate which feedback came from where?

> @jarekmorawski thanks for sharing the copy for each action, but in this case, we're targeting users who don't complete the action. So I feel that they copy should be different. Makes sense?

To tag on to this, in the design the copy for product exit prompt looked something like this:
`We noticed you started editing a product, then left. How was it? Your feedback will help create a better experience for thousands of merchants like you.`

**Comment by pmcpinto** [comment]
> @pmcpinto well for the product publish in the current UI we use the product_add_publish or product_update action for example, I was curious if we wanted to use something different for the exit CES feedback, like exit_product_update, so you can more clearly differentiate which feedback came from where?

Thanks for the clarification. This is why included a new event property in the issue description: 
ces_location: inside feature | outside feature

**Comment by jarekmorawski** [comment]
@louwie17 [Here's the updated copy for all actions](https://docs.google.com/spreadsheets/d/1t0JplRZL3cC3vNCATmMy95surJzYH_uhsitznelYcRI/edit?usp=sharing).

**Comment by joelclimbsthings** [comment]
@pmcpinto Specifically regarding the filter analytics prompt, should it only be added if they _start_ to filter (either date or more advanced), but don't actually apply them? Or should it just any time the user utilizes analytics filters and doesn't interact with the first CES that fires immediately after filtering?

**Comment by joelclimbsthings** [comment]
Remaining work has been moved to separate issues, closing this one.

**Comment by pmcpinto** [comment]
> @pmcpinto Specifically regarding the filter analytics prompt, should it only be added if they start to filter (either date or more advanced), but don't actually apply them? Or should it just any time the user utilizes analytics filters and doesn't interact with the first CES that fires immediately after filtering?

Analytics is an interesting use case. I think we should fire it if they visit a report but don't do anything. @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
I think we should show the prompt if they start, but don't finish the task. This will increase the odds of collecting actionable feedback on broken or missing functionality in analytics.

**Comment by joelclimbsthings** [comment]
> I think we should show the prompt if they start, but don't finish the task. This will increase the odds of collecting actionable feedback on broken or missing functionality in analytics.

Thanks @jarekmorawski , although I think my question is what it means to start and not finish the task in this use case. Would this be as I described above?

> Specifically regarding the filter analytics prompt, should it only be added if they start to filter (either date or more advanced), but don't actually apply them? Or should it just any time the user utilizes analytics filters and doesn't interact with the first CES that fires immediately after filtering?

Basically clicking the filter or date drop-down, but not applying the changes? Or, as @pmcpinto mentioned, just going to a report and not interacting with the filters?

**Comment by jarekmorawski** [comment]
> Basically clicking the filter or date drop-down, but not applying the changes?

This. I don't think prompting people who had not interacted with the page would bring in any useful feedback. Our goal is to discover what makes them pause, what blocks them from completing a task, and what prevents them from finding insightful, actionable insights in Analytics.

I think that we should show the prompt to people who:

- clicked the filter or date dropdown and did not apply changes
- filtered the list but took no actions, e.g. didn't click any of the items, export the results, or compare items
- selected a few items but took no actions
- searched the report but didn't interact with the results in any way

Let me know if this helps!

**Comment by pmcpinto** [comment]
> This. I don't think prompting people who had not interacted with the page would bring in any useful feedback

I don't completely agree with that assessment :) If the user leaves the screen without interacting with any filter can be a signal that:
- The information displayed by default is enough for the user to get what he needs
- The user is so overwhelmed that he doesn't even know what to do or he doesn't find the report valuable.
