### ISSUE TITLE
[Components] Rich text editor block transform bug

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35134]
When adding the first block to an editor, attempting to transform the block ("P" button in the upper left of the editor) usually requires 2 clicks before it can be opened.

It looks like the first click may not have selected the block properly.

![Image](https://user-images.githubusercontent.com/10561050/196280180-1e0aa3ac-79a6-4f64-985d-4cfe2ebba3a6.png)

Note that it's possible this could be related to deselection in [this PR](https://github.com/WordPress/gutenberg/pull/44517).

It also doesn't seem possible to transform back from a list item to any other block type.  Though this may be standard behavior or have to do with the registered blocks.

![Image](https://user-images.githubusercontent.com/10561050/196280329-f3346e46-1221-4500-9e30-9d6b2000d6f3.png)

**Acceptance criteria**

* [ ] The block editor should allow switching to another block without needing to open the block transform menu multiple times
* [ ] Transforming from a list back to other block types should work as expected.

**Comment by pmcpinto** [comment]
I'm closing this as we're using a different UI
