### ISSUE TITLE
Move product action buttons to header menu

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35139]
To make the product page actions more prominent and easier for users to find, we should move them to the top right of the page in the header.

![Image](https://user-images.githubusercontent.com/10561050/196292740-7eb67cf8-2a93-48cf-b873-bdcb1e874097.png)

We can use the `WooHeaderItem` [slot](https://github.com/woocommerce/woocommerce/blob/e7290b287b2dd8b1a179ff8d6d8cf604fcf8fdb6/plugins/woocommerce-admin/client/header/utils.tsx#L29-L39) to add these buttons to the header while keeping their logic store under the products folder.

Note that this should also contextually hide activity panel items which may require some thought about how we want to organize the logic for showing/hiding those items going forward.  The logic for activity panel items will likely get very messy as we continue to add more and more pages.

![Image](https://user-images.githubusercontent.com/10561050/196293516-aab875ac-1342-4d29-9859-cf260b4d2f1f.png)

**Acceptance criteria**

* [x] Product actions are shown in the header at the top right
* [x] Activity panel items are not shown on the product page, but continue to show as expected on other respective pages

**Comment by louwie17** [comment]
I do think this would be a valuable change and would also align with the block editor format.

cc @jarekmorawski for design input on this, is this something that would seem good to you?

**Comment by louwie17** [comment]
I do think this would be a valuable change and would also align with the block editor format.

cc @jarekmorawski for design input on this, is this something that would seem good to you?

**Comment by AnnaMag** [comment]
@joshuatf, could you please help @mdperez86 take over the work, grooming it a bit to get him started? 
Let's aim for the "conditional version" this week, moving the extended implementation to the next cycle. Thanks!

**Comment by joshuatf** [comment]
Sure thing, @AnnaMag!  I think the description includes most of what needs to be done, but in short this issue will involve:

1. Wrapping the existing product actions in a `WooHeaderItem` component.  See https://github.com/woocommerce/woocommerce/blob/e7290b287b2dd8b1a179ff8d6d8cf604fcf8fdb6/plugins/woocommerce-admin/client/header/utils.tsx#L29-L39
2. Adding a condition to prevent the activity panel items from showing when on a product page.  https://github.com/woocommerce/woocommerce/blob/1dd21fcc2d5b0eeeae051f474a834537be87d9f8/plugins/woocommerce-admin/client/activity-panel/activity-panel.js#L271-L276

Going forward we need to come up with a better way to house logic/context for which pages show various header items, but for the very near-term we can add one more condition to the those activity panel items.

@mdperez86 let me know if you have any more questions about how to handle this.

**Comment by jarekmorawski** [comment]
@joshuatf @mdperez86 Please hold work on this as I'm working on a new set of issues describing the new header. They'll be ready very soon.

**Comment by jarekmorawski** [comment]
@mdperez86, while structuring the updated header as part of this issue, feel free to look at [future improvements](https://github.com/woocommerce/woocommerce/issues/35168) for additional context. Thank you!
