### ISSUE TITLE
[Downloads] Manage limits

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35144]
**Job story**

When I put my digital product or service on sale on my website,
I want to manage basic file settings
So that the customer has a better post-purchase experience

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7001_309122

**Acceptance criteria**

- [x] When there's at least 1 file uploaded, we add a `Manage limits` button to the Downloads section heading. Clicking it opens a modal with options.
- [x] In there, the user can set the download limit and expiry period. Both apply to all uploaded files.
- [x] By default, both fields are empty (values are set to unlimited).
- [x] The download limit field has a tooltip that reads: `Decide how many times customers can download files after purchasing the product. Leave blank for unlimited re-downloads.`
- [x] The expiry field has a help text that reads: `Decide how long customers can access the files after purchasing the product. Leave blank for unlimited access.`
- [ ] In the expiry period, the user can click "days" to change the unit to hours, days, months, or years.
- [x] If the user enters any value, then clears either field, we automatically set the value back to unlimited.
- [x] Both fields only accept numbers. We provide basic number input controls. There is no character limit (if one exists in the current experience, we should apply it here too).
- [x] Clicking `Save` saves changes. Clicking `Cancel` discards all changes (restores to the previous state, but doesn't clear values) and closes the modal.
- [x] When the user removes all files, we hide the `Manage limits` button but remember any custom values the user entered.

**Comment by pmcpinto** [comment]
> In the expiry period, the user can click "days" to change the unit to hours, days, months, or years.

We should treat this one as a "nice to have" in the initial iteration.
