### ISSUE TITLE
[Downloads] File list

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35142]
**Job story**

- When I put my digital product or service on sale on my website,
- I want to manage basic file settings
- So that the customer has a better post-purchase experience

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7001_308059

**Acceptance criteria**

- [x] When the user uploads at least 1 file, the product gets the Downloadable trait on the backend (the equivalent of checking the Downloadable box in the current UX).
- [x] By default, the list displays the files by their actual names (including the extension/format).
- [x] If the file has a custom name added by the user, we show it first. The actual file name is then shown in a second line.
- [x] Each file is a separate item in the list with action X (remove).
- [x] The user can click the X button to remove a file from the list (but not delete it from the library).

**Comment by mdperez86** [comment]
@jarekmorawski we can not do the following AC until we support drag and drop at a block level.

>The user can drag and drop the items to change their order on the front end.

**Comment by jarekmorawski** [comment]
That makes sense. We can handle it later. Thanks, Maikel. 🙇

**Comment by mdperez86** [comment]
@jarekmorawski can I have the `Learn more` link please? 

![Image](https://github.com/woocommerce/woocommerce/assets/13334210/f1d69d2d-ad62-4619-a0d5-9681419f66b9)

**Comment by jarekmorawski** [comment]
Updated ACs in the https://github.com/woocommerce/woocommerce/issues/35141. ✔️ I also tweaked the copy a bit to reflect that there are more supported file types than just the ones listed.
