### ISSUE TITLE
[Downloads] Edit file modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35143]
**Job story**

- When I put my digital product or service on sale on my website,
- I want to manage basic file settings
- So that the customer has a better post-purchase experience

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7001_309093

**Acceptance criteria**

- [ ] The user can click the Edit button to open a model with file details from each file row.
- [ ] The modal has the file’s name (custom or original) in the title.
- [ ] We display a file thumbnail next to its name. If we can’t obtain it, we show a grey rectangle.
- [ ] The user can swap the file for another one using the Replace button. The original file is removed from the list (but not from the library), and the new one is added in its place. The new file maintains the old one’s name.
- [ ] Clicking the Replace button opens the WordPress upload modal.
- [ ] The user can change the file name. It will be shown to customers on the order confirmation page and email. The name is only a label and doesn’t replace the file name.
- [ ] The file URL is displayed in a disabled, non-interactive text field. The user can copy the URL either by highlighting the field’s contents or clicking the blue icon on the right side.
- [ ] When the user clicks Save, we close the modal and immediately update the list. If needed, we show the loading spinner to the button, then close the modal.
- [ ] When the user clicks "Delete file", we remove the file without any confirmation. We're not deleting it from the library, just from the product.

**Comment by octaedro** [comment]
Hey @jarekmorawski,

I'm working on this issue now. However, there is a problem with the `Media Library` modal inside the `Edit` download modal. Right now is not possible to have a modal inside a modal. So, adding the `Replace` button (that opens the `Media Library` modal) to the `Edit` modal implies making a refactor that may take a few days.

Is it ok if we only show the preview image without `Replace` button here?

<img width="574" alt="Screenshot 2023-10-03 at 16 48 14" src="https://github.com/woocommerce/woocommerce/assets/1314156/f23e1ee0-f5dd-404a-bb83-5c364b3d6eb6">

**Comment by jarekmorawski** [comment]
Maybe `Replace` could open the system file picker instead? If that's not possible, it's okay to skip it for now (this functionality doesn't exist in the current UX anyway).
