### ISSUE TITLE
[Virtual] ‘Needs shipping’ toggle

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35145]
**Job story**

- When I put my digital product or service on sale on my website,
- I want to disable shipping,
- So that the customer has a better post-purchase experience

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-7943_181396

**Acceptance criteria**

- [ ] The user can enable and disable shipping options at the top of the Shipping tab.
- [ ] The toggle is on by default. The user can turn it off at any time.
- [ ] The product receives the `Virtual` trait when the toggle is off.
- [ ] When the toggle is off, we save and remember any shipping information and details the user might've entered before turning it off. When it's enabled again, we restore previously used settings.
- [ ] When the toggle is off, the Shipping fee sub-section in the card is greyed out. The controls are disabled. To re-enable it, the user must flip the toggle.

**Comment by pmcpinto** [comment]
@jarekmorawski just a few comments:

> The product receives the Virtual trait when the toggle is off.

When the product has shipping data (dimension, weight, shipping class), we should keep it instead of resetting it, right?

The toggle seems a little lost in the middle of the UI. Did you consider other locations or decreasing the padding/margin?

**Comment by jarekmorawski** [comment]
> When the product has shipping data (dimension, weight, shipping class), we should keep it instead of resetting it, right?

Yup! I'll update the AC.

> The toggle seems a little lost in the middle of the UI. Did you consider other locations or decreasing the padding/margin?

Yes, I've explored a few solutions, but this seemed the cleanest and most straightforward. I think it should be positioned on top because it impacts all other sections: dimensions, fees, details, shipping-related plugins, etc.

I tried giving it more weight by tying it to digital/virtual products and it seemed like too much (also, asking about product type here can be misleading given the breadth of context product types have in Woo).

<img width="502" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/00003804-f438-4ac6-9c7b-8e931d72fc59">

I also tried moving the toggle into the dimensions & weight section, but it didn't seem logically sound and could be a bit difficult to find.

<img width="488" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/c0777983-2e07-461c-aaec-cf879bf9a7eb">

How do you think decreasing paddings/margins could help?

**Comment by pmcpinto** [comment]
> How do you think decreasing paddings/margins could help?

I think it could make it feel more "connected" to the rest of the UI, but it's difficult to say without visualizing the change.

**Comment by mdperez86** [comment]
Hey @jarekmorawski I'm no able to locate the design screen of the Virtual product under the link you shared. Could you update the link/design please? Thanks

**Comment by jarekmorawski** [comment]
It should be working now. Let me know!
