### ISSUE TITLE
[External products] Product details

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35148]
**User story**

- As a merchant,
- I want to sell a product offered by a partner
- So that I can earn a commission

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-3427_372982

**Acceptance criteria**

- [x] When the user selects an external product type, we show an additional Buy button section in the General tab.
- [x] The link field is required. When the user attempts to publish a product without filling it out, we show an error message that reads: `Link to the external product is required`. AkVNGImLgSqCObTQ3idVn7-fi-8707_193347
- [x] When the user adds a link, we display an icon on the right side of the field. Clicking it will open the product link in a new tab. If the field is empty, the icon is hidden.
- [x] By default, the Button text field says “Buy”. The label should match the store’s language and locale (just like the regular buy button).
- [ ] The user can enter any text in the buy button field. If left empty, we show an error message that reads: `Buy button text cannot be empty`. AkVNGImLgSqCObTQ3idVn7-fi-8707_193347

**Comment by pmcpinto** [comment]
> When the user selects an external product type, we show an additional Buy button section in the General tab.

@jarekmorawski same comment. We need to find a way to surface this feature in the UI without requiring an intermediate selection step.

**Comment by mdperez86** [comment]
@jarekmorawski @pmcpinto 

>When the user selects an external product type

What does it mean? Where users have that option? Currently we don't have a way to let users create a new external product using the new product editor.

It has to be from here 
<img width="824" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/f105e314-d245-4923-a162-d05e2b07bcf3">

**Comment by pmcpinto** [comment]
I'm going to review this with @jarekmorawski as this isn't the only entry point to create products. Stay tuned!

**Comment by jarekmorawski** [comment]
@pmcpinto, could something like this work, perhaps? We already use the nested menu component in the variations table.

<img width="586" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/680bd200-8434-4345-af4d-ca86e6c1c639">

**Comment by pmcpinto** [comment]
@jarekmorawski do you think this has enough visibility?

**Comment by jarekmorawski** [comment]
Probably not. I've since tweaked the flow a bit. A link in the first section's description could be more discoverable than a dropdown in the top bar. What do you think?

<img width="612" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/f595fb69-6493-4434-bfdf-e4b8d298c9cb">

Full flow:

<img width="1379" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/5847e806-e668-4cf8-9417-a25dc5f7470c">

**Comment by pmcpinto** [comment]
@jarekmorawski thanks for the suggestion. This is a good stopgap solution, and I'll focus on the product form > change product type flow for now. We should avoid adding this intermediate step to the product list, as affiliate and grouped products only represent a small % of products.

Does the preview make a significant difference?

**Comment by pmcpinto** [comment]
> @jarekmorawski thanks for the suggestion. This is a good stopgap solution, and I'll focus on the product form > change product type flow for now. We should avoid adding this intermediate step to the product list, as affiliate and grouped products only represent a small % of products.
> Does the preview make a significant difference?

@mdperez86 @louwie17 do you want us to create a separate issue for the product type selector?

**Comment by louwie17** [comment]
> @mdperez86 @louwie17 do you want us to create a separate issue for the product type selector?

Yes a separate issue would be great ( if we don't have one already ), which I didn't think we did.

> Does the preview make a significant difference?

It would add 1/2 days of developer time most likely, as I don't think we have a preview implemented yet for any of the other items ( like attributes ).
