### ISSUE TITLE
[Grouped products] Product list

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35146]
**User story**

- As a merchant,
- I want to sell a set of similar products
- So that I can earn more money on each order

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-3427_365209

**Acceptance criteria**

**The preview and the SEO tab in the designs are not part of this work.**

- [x] When the user selects a grouped product type, we show an additional `Products in this group` section in the General tab.
- [x] When the user selects a grouped product type, we hide the Pricing and Shipping tabs.
- [x] When empty, the grouped products card has an empty state with an illustration. AkVNGImLgSqCObTQ3idVn7-fi-3427_365229
- [x] When the user clicks Add products, we show a modal. AkVNGImLgSqCObTQ3idVn7-fi-3427_369891
- [x] When the user clicks the search field, we immediately display the list of all existing products. It is sorted alphabetically. Clicking an item closes the search and adds the product to the list.
- [x] The user can search the list by product name.
- [x] The user can add multiple products and delete products directly in the modal.
- [x] When the user clicks `Add`, we close the modal and display the list of added products in the product form.
- [x] The list works the same as the one in the modal, but it has more details, like the price and current stock.
- [x] Clicking the product name will open it in the editing view in a new tab.
- [x] The product name column has a fixed width of 253 pixels. If the name or SKU extends beyond this width, we truncate the text. AkVNGImLgSqCObTQ3idVn7-fi-3427_369101
- [x] Clicking the arrow button will open the product's page in a new tab.
- [x] Clicking the X button will remove the product from the group.
- [x] Clicking `Add products` will re-open the modal (it'll be empty).
- [x] When the user removes all products, we show the empty state again.

Depends on https://github.com/woocommerce/woocommerce/issues/41593

**Comment by pmcpinto** [comment]
> When the user selects a grouped product type, we show an additional Products in this group section in the General tab.

@jarekmorawski when will this selection take place? We need to find a way to surface this feature in the UI without requiring an intermediate selection step

**Comment by mdperez86** [comment]
We are not supporting dragging and dropping within a block yet. But I think it should be possible in the modal so let's focus on that for now.
