### ISSUE TITLE
[COT/HPOS] Explore adding full text search index to address table for performance

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#35150]
Since we have a separate address table with HPOS, we can add a Full-text search index on all columns in the address table.

This issue explores feasibility by comparing MySQL server support and the tradeoff between insert performance degradation vs search performance upgrade. 

If feasible, this issue also scopes adding the index, determining minimum word size, and converting wildcard queries to `MATCH.....AGAINST` queries.

**Comment by nb** [comment]
There is a recent WordPress core conversation about full-text indices: https://core.trac.wordpress.org/ticket/51769

**Comment by jorgeatorres** [comment]
Closing this for now, as this is being explored via #46130 as an experimental feature.
