### ISSUE TITLE
Settings: remove the new nav option 

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35157]
**Description:** we want to remove the option to enable the beta version of the new navigation, as we're not actively working on it at the moment. 

**Acceptance criteria:**
- [ ] Remove the option to enable the new navigation in Settings > Advanced > Features. This option should be removed if the user doesn't have the navigation enabled. 
- [ ] Users with the navigation enabled should have access to this option, as they need a way to disable the experience if necessary.

**Comment by louwie17** [comment]
> Users with the navigation enabled should have access to this option, as they need a way to disable the experience if necessary.

Will this mean that once the user disables it, the option disappears for them as well, and they won't be able to re-enable it?

**Comment by pmcpinto** [comment]
Good question. Maybe we can include a brief message saying that the project was paused and it won't be possible to reenable the navigation for the time being. 
@jarekmorawski what would be the best approach from the UX POV?

**Comment by jarekmorawski** [comment]
> Good question. Maybe we can include a brief message saying that the project was paused and it won't be possible to reenable the navigation for the time being.

This. We could add a warning/confirmation modal saying something along the lines of:

> **Disable the experimental navigation?** The experimental navigation will soon become unavailable while we make necessary improvements. If you turn it off now, you won't be able to turn it back on. Do you want to continue? [Cancel] [Disable]

**Comment by pmcpinto** [comment]
Sounds good to me.

**Comment by pmcpinto** [comment]
@AnnaMag is it possible to include this in 7.4?

**Comment by AnnaMag** [comment]
yes.
