### ISSUE TITLE
Add message to the wc admin page

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35156]
**Description:** we want to add a message in https://wordpress.org/plugins/woocommerce-admin/, informing users that the plugin is no longer under development, since it is now a part of WooCommerce Core.

**Acceptance criteria:**
- [ ] Include the following message at the top of the page, ideally before the description section:
WooCommerce Admin is no longer supported
WooCommerce Admin is now part of WooCommerce Core! To make sure your store continues to run smoothly, check that WooCommerce is up-to-date – at least version 6.5 – and then disable the WooCommerce Admin plugin.

**Comment by mattsherman** [comment]
https://wordpress.org/plugins/woocommerce-admin/ has been updated.
