### ISSUE TITLE
[Header] Product status badge

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35169]
**User story**

- As a merchant,
- I want to quickly check the status of my product,
- So I can take immediate action if needed.

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-8921%3A376741

**Acceptance criteria**

- [ ] We show a badge (pill) next to the product's name in the header.
- [ ] In the future, it's possible there will be more than one badge shown simultaneously.
- [ ] The labels show the product's system (unsaved/draft) or inventory status (out of stock/in stock).
  - [ ] `Unsaved` is displayed when a user creates a product but doesn’t save it yet (or before it’s saved automatically).
  - [ ] `Draft` is displayed when the product has been saved, but not published yet.
  - [ ] `In stock` is displayed when the product has been published AND `Stock status` is set to `In stock` (or, if quantity tracking is enabled, the `Current quantity` field value is >0. The badge's color is `#00A32A`.
  - [ ] `Out of stock` is displayed when the product has been published AND `Stock status` is set to `Out of stock` (or, if quantity tracking is enabled, the `Current quantity` field value is 0. The badge's color is `#CC1818`.
- [ ] The badge updates dynamically. The badge changes when the product is saved (either automatically or when the user clicks Save draft in the header).

**Comment by joshuatf** [comment]
We can probably use `WooHeaderPageTitle` SlotFill to add the badge to the header.  This will keep our logic housed nicely under `products/` without making a mess of the frontend controller.

`product.status` and `product.stock_status` should provide us with enough information to determine which badge to display, though we should be double check that `manage_stock` correctly modifies `stock_status` depending on whether or not a product's inventory is being managed.

>Out Stock is displayed when the product has been published AND Stock status is set to Out of stock (or, if quantity tracking is enabled, the Current quantity field value is 0. The badge's color is #CC1818

I think this should be `Out of stock` and that's how it appears in the design, but just double checking.  cc @jarekmorawski

**Comment by jarekmorawski** [comment]
> I think this should be Out of stock and that's how it appears in the design, but just double checking. cc @jarekmorawski

Good eye! I've fixed this and capitalization in other statuses.
