### ISSUE TITLE
[Product details] Summary

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35167]
**User story**

- As a merchant,
- I want to add a captivating bit of text to the top of the product page,
- So that the customers can learn more about the product.

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-5614%3A223639

> The designs differ from what we've implemented for the description field. We'll likely go in the direction presented in Figma (and update the desc field accordingly), but it's not certain yet. Until then, please follow everything we've established for the desc field.

**Acceptance criteria**

- [ ]  Users can provide a summary of the product.
- [ ]  The description doesn’t have a character limit.
- [ ] The summary field works the same as the description field.
- [ ] The height of the input field is smaller than the description field (96 px).
- [ ]  The field can be resized up and down by dragging the arrow in the bottom right corner. It cannot be resized left and right.
- [ ] Like the current experience, keyboard shortcuts can activate formatting tools.
- [ ]  Each tool in the toolbar has the same description on hover as in the current experience.

**Comment by AnnaMag** [comment]
Hi @joshuatf! Here is the "missing" issue- thank you for agreeing to take it on.
