### ISSUE TITLE
Shipping class: auto-assign new shipping class to product

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35178]
**Description:** currently, the user needs to assign a shipping class to the product after creating one directly from the "new shipping class" modal. We can streamline this process by auto-assigning the new shipping class to the product.

**Acceptance criteria:**
- [ ] When a new shipping class is created, auto-assign the product to the shipping class

**Comment by mdperez86** [comment]
@pmcpinto I think this issue was covered here https://github.com/woocommerce/woocommerce/issues/35036
Could you check it so we can close this one please?

**Comment by pmcpinto** [comment]
You're right. I couldn't find that issue because I was only checking the open issues :) I'll close this one. Thanks!
