### ISSUE TITLE
[Header] Product name

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35172]
**User story**

- As a merchant,
- I want to see what product I'm editing at all times,
- So I can avoid possible mistakes.

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-8924%3A388910

**Acceptance criteria**

- [ ] We show the product's name as the last step in the breadcrumbs in the header.
- [ ] We use the product type if the product doesn't have a name yet. Example: `New standard product`, `New grouped product`, `New affiliate product`, `New gift card`, etc.
- [ ] The name updates dynamically when the user enters the product's name in the form field. The user doesn't need to save or update changes for the name to change.
- [ ] The character limit is 70. If the name is longer, we truncate it by adding `...` at the end of the last word. When the user hovers over it, we show the full product name in a tooltip.

**Comment by joshuatf** [comment]
>We use the product type if the product doesn't have a name yet. Example: New standard product, New grouped product, New affiliate product, New gift card, etc.

Are we foregoing these for the time being?  We don't yet have a way to change the product type AFAIK.

**Comment by jarekmorawski** [comment]
We'd add a way to switch between product types in the sidebar (https://github.com/woocommerce/woocommerce/issues/35175). This is not part of MVP 1.0, though.
