### ISSUE TITLE
[Header] Contextual action buttons – Settings

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35175]
**User story**

- As a merchant,
- I want to change the product type,
- So I can create a better product for my customers.

**Design**

5sAIeTRd9Yp7nSCT33BAWz-fi-8921%3A376741

**Acceptance criteria**

- [ ] When the user clicks the cog icon in the top right corner, we show a sidebar with several collapsible panels.
- [ ] The sidebar looks and behaves exactly as in the Gutenberg editor/FSE.
- [ ] The `Product type` section lists all available product types. It is expanded when the user opens the sidebar.
  - [ ] The user can choose between them at any time. If they switch to a product type that offers fewer fields, **we will remember the settings and data they entered there**.
  - [ ] The selected product type is marked with a check icon.
  - [ ] The link at the bottom of the list takes the user to `https://woocommerce.com/document/managing-products/#product-types`.
- [ ] The `Advanced` section is collapsed by default.
  - [ ] The `Enable reviews` box is checked by default.
  - [ ] The default value in `Menu order` is 0.

**Comment by joshuatf** [comment]
>The sidebar looks and behaves exactly as in the Gutenberg editor/FSE.

I think we can recompose most of this layout using Gutenberg components, but can't fully utilize the Gutenberg `InterfaceSkeleton` which dictates this layout.  While it would be great to use that, there are too many differing features that would be challenging for us to extend.

>The Product type section lists all available product types. It is expanded when the user opens the sidebar.

Is the product type logic implemented elsewhere?  Or is this just a placeholder for the time being?

**Comment by jarekmorawski** [comment]
> Is the product type logic implemented elsewhere? Or is this just a placeholder for the time being?

We'd use the logic that already exists. Regarding product types in general, our approach it to merge simple, downloadable, virtual, and variable product types into a single experience (while still keeping them separate in the DB, just a bit more... fluid in the admin UI), while grouped and external/affiliate product types would remain separate.

Therefore, the content of this section in the sidebar is the same as the `Type` dropdown in the current UX, except it only lists these 3 options. Does this help?
