### ISSUE TITLE
Remove some placeholder values

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35174]
**Description:** Some placeholder values can confuse the user rather than help him understand what should be added in the input field.

**Acceptance criteria:**

- [x] Remove the placeholder value in the list price
- [x] Remove the placeholder value in the sale price
- [x] Remove the placeholder value in the SKU

**Comment by pmcpinto** [comment]
@jarekmorawski do you think we should remove the placeholder value from the product name as well?

**Comment by jarekmorawski** [comment]
No, I think it's useful. The others are not because we can't meaningfully "inspire" or "suggest" a price without knowing what the product is.
