### ISSUE TITLE
[Header] Contextual action buttons – More menu

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35177]
**User story**

- As a merchant,
- I want to share feedback on the new product editing experience,
- So the WooCommerce development team can continue improving it.

**Design**

5sAIeTRd9Yp7nSCT33BAWz-fi-8921%3A376741

**Acceptance criteria**

- [ ] When the user clicks the ellipsis icon in the top right corner, we show a dropdown menu with several options.
- [ ] The menu looks and behaves exactly as in the Gutenberg editor/FSE.
- [ ] `Share feedback` opens the new CES feedback modal (https://github.com/woocommerce/woocommerce/issues/35122).
- [ ] `Use the classic editor` will let the user switch to the classic editing experience.

**Comment by joshuatf** [comment]
@jarekmorawski just confirming that this issue only covers the 3 ellipsis more menu and not the settings (cog) menu.

Are we adding the "Welcome guide" item used in the design?  Do we have a link for that if so?

**Comment by joshuatf** [comment]
You can ignore the settings menu question- I see the issue for that [here](https://github.com/woocommerce/woocommerce/issues/35175).

**Comment by jarekmorawski** [comment]
> Are we adding the "Welcome guide" item used in the design? Do we have a link for that if so?

Not at the moment, but we will have a welcome tour as part of the onboarding UX. We can forego the menu item for the time being, or add it as a placeholder.
