### ISSUE TITLE
[Header] Breadcrumbs

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35170]
**User story**

- As a merchant,
- I want to go back one or more steps in the navigation,
- So I can easily find the information or setting I am looking for.

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-8924%3A388910

**Acceptance criteria**

- [ ] We show breadcrumbs in the left part of the new page header.
- [ ] Each breadcrumb is clickable.
- [ ] The arrows between the links are not clickable.
- [ ] The links get an underline on hover to indicate they're clickable.
- [ ] The current page's name (in this case, the product's name) is Gutenberg 900, bold, and not clickable.
- [ ] If there are more than 3 levels of breadcrumbs on the screen (excluding the currently viewed page), we truncate the path and only show the first and last steps. Example: `5sAIeTRd9Yp7nSCT33BAWz-fi-8924%3A388912`
- [ ] On mobile, the breadcrumbs are displayed above the current page's name and have different styling. Design: `5sAIeTRd9Yp7nSCT33BAWz-fi-7325%3A345827`.

**Comment by joshuatf** [comment]
We previously took away breadcrumbs in the header in https://github.com/woocommerce/woocommerce-admin/pull/5232/ so I just want to confirm that we're reintroducing them here.

This change will likely affect all pages unless we attempt to isolate it to just this page.  This means we're looking at testing all pages and possibly tweaking breadcrumbs on those pages or removing them if unneeded.

**Comment by jarekmorawski** [comment]
> We previously took away breadcrumbs in the header in https://github.com/woocommerce/woocommerce-admin/pull/5232 so I just want to confirm that we're reintroducing them here.

I confirm. We've phased them out earlier because of the new nav project, but we won't be returning to it anytime soon. We want to have breadcrumbs on every page where the new header will be used, but it should be optional and easy to turn off if not needed (some pages may have a complex/unique structure or deliberately offer a separate experience).

**Comment by joshuatf** [comment]
I'm estimating this at a 5.  My hope is that we can reuse some of the existing breadcrumb logic without re-enabling it site-wide.  However, this could open up some challenges in how we prevent this form being a site-wide feature, so I want to leave some room for error.

**Comment by jarekmorawski** [comment]
We already only show the new top bar (with the button on the right) in the new product editing UX. Can we apply the same logic to the breadcrumbs?
