### ISSUE TITLE
[Enhancement]: Allow the user to select multiple images in the Media Library

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35181]
### Describe the solution you'd like

We currently only allow the user to select one image to add to the product gallery, but the user should be able to select any number of files.

**Acceptance criteria**

- [ ] The user can select multiple images in the Media Library, then add them to the image gallery in the product form.
- [ ] The same applies to the system file picker while choosing images to upload.

### Additional context

This is how it currently works in the gallery block in Gutenberg.

**Comment by joshuatf** [comment]
@octaedro I think the `multiple` prop can be added to the `MediaUploadComponent` to accomplish this.
https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/media-upload/README.md

We'll probably also need to change our `onSelect` prop type to allow for multiple values and verify that callbacks continue to work on the product page and storybook examples.

I'd estimate around a "2" for this issue to allow time for checking to make sure current implementations work.

**Comment by octaedro** [comment]
Yes @joshuatf, we will have to modify the [media-uploader](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/media-uploader/media-uploader.tsx) component, the [image section](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/sections/images-section.tsx#L178-L192) on the product page and the [storybook](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/media-uploader/stories/index.tsx#L119) as well.
My estimation is a `2`.
