### ISSUE TITLE
[Enhancement]: Allow users to open the file picker by clicking anywhere inside the product gallery card

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35183]
### Describe the solution you'd like

The copy in the product card suggests that the user can click anywhere inside the empty gallery card (and the drop area when there's at least 1 image) to select images, but we currently don't let them do that.

**Acceptance criteria**

- [ ] The user can open the system file picker by clicking anywhere within the empty product gallery card and the designated upload/drop area when at least 1 image is uploaded.

### Additional context

**Designs**

5sAIeTRd9Yp7nSCT33BAWz-fi-5175%3A125913

**Comment by octaedro** [comment]
I took a look at this issue a couple of weeks ago.
I think that the simplest way to add this functionality is by using the [FormFileUpload component](https://developer.wordpress.org/block-editor/reference-guides/components/form-file-upload/). I explored other options like using the [autoOpen prop](https://github.com/WordPress/gutenberg/tree/v10.9.1/packages/block-editor/src/components/media-upload#autoopen), but there are a few issues (not minor) that prevent us from using it in an easy way.

**Comment by mdperez86** [comment]
Estimation: 2
