### ISSUE TITLE
[Enhancement]: Add space between a selected image in the gallery and the toolbar

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35182]
### Describe the solution you'd like

I noticed there's no padding between the image and the toolbar. We need to add it for better clarity and visual order.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/79307566/196686362-391f9183-8a5f-4a4c-aec2-773ba41e08b7.png">

**Acceptance criteria**

- [ ] There's an 8 px space between the image and the toolbar

### Additional context

**Designs in Figma**

5sAIeTRd9Yp7nSCT33BAWz-fi-5180%3A118552

**Comment by mdperez86** [comment]
Estimation: 1

**Comment by mattsherman** [comment]
I've assigned myself to this, as it is right in the same code as #35184
