### ISSUE TITLE
[Enhancement]: Add a loading state when the user drops an image on the gallery to upload it

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35185]
### Describe the solution you'd like

We offer no visual feedback when images are being uploaded, which creates friction within the flow. We need to add a loading state, so the user knows that the images are being added in the background.

### Design

5sAIeTRd9Yp7nSCT33BAWz-fi-8787%3A365370

<img width="321" alt="image" src="https://user-images.githubusercontent.com/79307566/196689426-f55b3f50-8443-4888-a872-fd128774d186.png">

### Acceptance criteria

- [ ] When an image is being uploaded (after dragging it to the gallery), a placeholder for the image will be shown in the gallery, with an indication that it is being uploaded.
- [ ] The loading state is not interactive, meaning the user cannot click or interact with the image before it's uploaded.

**Comment by mattsherman** [comment]
We will need to enhance the images section/gallery to have a concept of "uploading"/"pending" images. This probably should be contained within the state of the image gallery itself. We will also need to update the media uploader to allow a callback to be called when an upload starts.

Images section:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/sections/images-section.tsx

Media uploader:

https://github.com/woocommerce/woocommerce/blob/64ee20ff0f47fc69c546eefeaa421536c4fa3a4a/packages/js/components/src/media-uploader/media-uploader.tsx

It does not appear that the underlying WordPress code we are using has any support for progress indication.

https://github.com/WordPress/gutenberg/blob/trunk/packages/media-utils/src/utils/upload-media.js#L45

**Comment by mattsherman** [comment]
I'm estimating this as a `3`, since we will need to make changes in few places to implement this. The placeholder items in the image gallery might be a little bit tricky, so that consumers of the gallery can properly deal with those (or, maybe they don't need to at all).

**Comment by mdperez86** [comment]
Estimation: 3

**Comment by pmcpinto** [comment]
@jarekmorawski can you check if this is happening in the new form or if you have duplicated issues?

**Comment by jarekmorawski** [comment]
Duplicate of https://github.com/woocommerce/woocommerce/issues/40941.
