### ISSUE TITLE
[Enhancement]: Update the drag state for the selected images

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35186]
### Describe the solution you'd like

When dragging an image, we show it in full, which makes it more challenging to see the drop indicator and its position in the gallery. This behavior is different from the designs in Figma and what already exists in Gutenberg.

**Acceptance criteria**

- [ ] The drag state looks the same as in Figma and Gutenberg
- [ ] When dragging the image over the delete area, the icon should change to the close icon (currently the upload icon).

### Additional context

**Designs**

5sAIeTRd9Yp7nSCT33BAWz-fi-5180%3A119404

<img width="434" alt="image" src="https://user-images.githubusercontent.com/79307566/196691272-ac167521-75b5-4ea4-ae04-1ba05da37919.png">

**Comment by mdperez86** [comment]
Estimation: 3

**Comment by pmcpinto** [comment]
@jarekmorawski can you confirm if this is happening in the new form?

**Comment by jarekmorawski** [comment]
We don't support drag and drop in the new UX yet. I'll close this issue and create another one when we solve that problem.
