### ISSUE TITLE
[Enhancement]: Improve the communication around required and optional fields

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35191]
### Describe the solution you'd like

Given that the product name is the only required field in the whole form, we should mark it as such and remove the (optional) label from the `Summary` and `Sale price` fields (and any other that has it).

**Acceptance criteria** 

- [x] The `Name` field has a `(required)` suffix.
- [x] The `Summary` and `Sale price` fields no longer have the `(optional)` suffix.

### Additional context

<img width="311" alt="image" src="https://user-images.githubusercontent.com/79307566/196696942-33769ddc-f3de-45d0-9f87-580b66659013.png">

**Comment by mdperez86** [comment]
@jarekmorawski Should we apply this to the Add new shipping class dialog also?

**Comment by jarekmorawski** [comment]
Yes, please!
