### ISSUE TITLE
SPIKE: PM MVP Extensibility guidelines

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#35193]
Combine the extensibility guidelines and technical exploration POV to propose an implementation in the new product management form.

See both the early Extensibility Guidelines doc and the Product management technical extensibility options doc (ping @louwie17 for the links).

Some items to consider:
- Should extensibility primarily be possible through Front-end, back-end or both?
- How can we ease the transition between the legacy and the new experience for 3PD?
- Talk to @joelclimbsthings about what came out of the 3PD feedback. 
     - Include some quotes if possible
- Look through the WooCommerce maintained plugins and see which plugin we could potentially update alongside the extensibility integration to help fix and find any caveats.
     - This plugin should primarily extend simple products for now, given that is what we are only supporting for the MVP

Acceptance criteria
- [ ] Have an initial proposal ready for the extensibility guidelines
- [ ] Summarize this proposal in a P2 post for feedback
- [ ] Create a couple small examples in code, that can also be included in the P2 post 
- [ ] Have some initial next steps ready (this will of-course depend on the wider feedback)

**Comment by AnnaMag** [comment]
cc @joelclimbsthings

**Comment by pmcpinto** [comment]
> How can we ease the transition between the legacy and the new experience for 3PD?

@louwie17 I think this piece is critical. We'll have a really hard time convincing 3PDs if we don't provide any kind of backwards compatibility or an easy way to adopt the new experience without rebuilding the extension from scratch.
