### ISSUE TITLE
[Enhancement]: Indicate disabled product variants in variation list

### ISSUE THREAD

**Issue by pierrerocket** [woothemes/woocommerce#35231]
### Describe the solution you'd like

Hello.  My enhancement request is regarding the UX of disabled variants in the variation list on product edit pages.  Currently you have to expand the variation to see if the enabled box is checked or not.  It would be nice to somehow indicate this information without having to open the drawer: either through graying it out, a color overlay, moving the checkbox to outside the drawer, or having a text label outside of the drawer.

**Comment by peterfabian** [comment]
Thanks @pierrerocket , that sounds like a good improvement indeed. Since we have a team working right now on a new product editing experience, let's highlight it to them, cc @pmcpinto .

**Comment by pmcpinto** [comment]
Thanks for the suggestion. This is a good improvement. I'll talk to the team to explore how to implement this. cc @jarekmorawski

**Comment by jarekmorawski** [comment]
We've implemented this change in the new UX and the disabled variations will be slightly faded. There's also an icon to indicate their status.

<img width="693" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/89e6243c-75db-4593-a2b7-126d1878a3f5">
