### ISSUE TITLE
[Enhancement]: Task list documentation needs to be updated

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35234]
### Describe the solution you'd like

The array provided to add a task is no longer applicable and a class extending `Automattic\WooCommerce\Admin\Features\OnboardingTasks\Task` should be added instead.  https://github.com/woocommerce/woocommerce/blob/d0278f4801f0edc72310796687c8539d805e3cde/plugins/woocommerce-admin/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php#L18-L31

E.g.,

```php
class MyTask extends Task {}
TaskLists::add_task(
	'extended',
	new MyTask()
);
```

Documentation will also need to be updated to reflect this.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/onboarding-tasks.md#L18

**Comment by rodrigoprimo** [comment]
I suggest updating this blog post as well, as it contains instructions that don't work anymore: https://developer.woocommerce.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/
