### ISSUE TITLE
Receiving products by attribute values not specifically working

### ISSUE THREAD

**Issue by Johnny99211** [woothemes/woocommerce#35274]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since I'm unable to find any information about this topic, I think I've found a bug. Within the last week, I've tried a lot of ways to modify the WooCommerce product (shop) query to implement a custom filter functionality with product attributes like this:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/43766368/197350968-ca067431-d434-4179-b6cb-dfe234b289e0.png">

I need to mention, that these are only product specific attributes and are not available at the general attributes page! 

This is the function I've used:

```
add_filter( 'woocommerce_product_query_meta_query', 'filter_woocommerce_product_query_meta_query', 10, 2 );
function filter_woocommerce_product_query_meta_query( array $meta_query ): array {
	$meta_query[] = [
		'key'     => '_pa_farbe',
		'value'   => 'Grün',
		'compare' => 'LIKE'
	];

	return $meta_query;
}
```

Somehow I resulted in no products. So I did a lot of research and found out, that I can not filter by the attribute key `pa_farbe`. For me, this is terrible, because I can not specifically say: I only want products with the color green.

At least I was able to somehow get a half-result by using a non-attribute-specific key:

```
add_filter( 'woocommerce_product_query_meta_query', 'filter_woocommerce_product_query_meta_query', 10, 2 );
function filter_woocommerce_product_query_meta_query( array $meta_query ): array {
	$meta_query[] = [
		'key'     => '_product_attributes',
		'value'   => 'Grün',
		'compare' => 'LIKE'
	];

	return $meta_query;
}
```

Sadly, this is still not working for me, since it is not specific enough.

### Expected behavior

The meta query filter should also allow custom product attributes by their key, to get a better filtering.

### Actual behavior

Currently, when I have for example 2 attributes with different keys, but same values like length = 20 and height = 20, I can not exactly receive products for either length or height when using `_product_attributes` as key.

### Steps to reproduce

1. Add filter for custom attribute `pa_xxx` from e.g. variable product attributes
2. Reload shop page
3. Experience the issue

### WordPress Environment

If relevant in this case, please let me know. I'm using latest version of WordPress, WooCommerce and Storefront.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Johnny99211 I apologize for the long delay in responding. Local product attributes (from screenshot) do not have the `pa_` prefix that you see in global product attributes. Local attributes are stored as a JSON encoded array:

```
|  118298 |    3357 | _product_attributes | a:1:{s:4:"size";a:6:{s:4:"name";s:4:"Size";s:5:"value";s:5:"Large";s:8:"position";i:0;s:10:"is_visible";i:0;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}}   
```

I'll close this issue as a support question.
