### ISSUE TITLE
woocommerce_receipt_  is duplicating on our payment

### ISSUE THREAD

**Issue by angelamollina30** [woothemes/woocommerce#35280]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have a payment gateway plugin that having an error and it was duplicating the woocommerce_receipt , where we input the card details in checkout/order-pay page
 here's the screenshot for reference
![image](https://user-images.githubusercontent.com/47047706/197513016-f886e042-4029-4092-9211-af6576e69b64.png)

> 

### Expected behavior

One Payment for showing used code woocommerce_receipt_ on checkout/order-pay page

### Actual behavior

the payment form is duplicated in checkout/order-pay page

### Steps to reproduce

1. Update Woo to 7.0
2. Order a product
3. Checkout

### WordPress Environment

Checking out the items

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jarscr** [comment]
Hello, how can fix this?
