### ISSUE TITLE
Importing sale price date "date_on_sale_to" is broken

### ISSUE THREAD

**Issue by ronnyadsetts** [woothemes/woocommerce#35281]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Importing products for future sale does not set the date_on_sale_to value correctly.

### Expected behavior

Setting the date_on_sale_to field in a product import CSV to "2023-01-16 23:59:59" should set that value .

### Actual behavior

Following the import, the product date_on_sale_to is set to "2023-01-16T00:00:00".

Compounding this, editing the product shows the sale end date as ""2023-01-16", and saving then set the date to "2023-01-16T23:59:59".

This means importing products to go on sale is impossible unless you're then prepared to manually edit every product to correct the sale end date.

### Steps to reproduce

1. Create a test product with an SKU and price
2. Create a CSV file with these columns:
"SKU","date sale price starts","date sale price ends""Sale price"
and a row for the test product. Set a start and end date both in the future and a sale price that is different to the regular price. Field format for the start date should be like "2022-10-28 00:00:00"; for the end date it should be like "2023-01-16 23:59:59".
3. Import the saved CSV with the "update products" option ticked.
4. Check the product sale dates using the $product object. You can do this using wp-cli as follows (with the right product ID):
$ wp --user=ainet wc product get 14939 | grep --color -E "(date_on_sale_|sku)"

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shop.graysofwestminster.co.uk
Site address (URL): https://shop.graysofwestminster.co.uk
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.0.2 - There is a newer version of WordPress available (6.0.3)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.32
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.36-MariaDB-0+deb10u2
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 502

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: wp_
Total Database Size: 565.30MB
Database Data Size: 375.52MB
Database Index Size: 189.78MB
wp_woocommerce_sessions: Data: 120.16MB + Index: 6.09MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 11.52MB + Index: 11.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 17.05MB + Index: 13.28MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 7.02MB + Index: 6.03MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 2.38MB + Index: 0.02MB + Engine InnoDB
wp_ac_atc_rules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_connector_sync: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_ac_link_clicked_notifications: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notification_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_notifications: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_ac_statistics: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 10.52MB + Index: 10.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mgmlp_csv_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_import_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_thumbnails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_userrole_permissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 20.08MB + Index: 1.22MB + Engine InnoDB
wp_postmeta: Data: 59.59MB + Index: 52.19MB + Engine InnoDB
wp_posts: Data: 12.52MB + Index: 5.05MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.25MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_contact: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_country: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 13.52MB + Index: 10.03MB + Engine InnoDB
wp_users: Data: 0.48MB + Index: 0.42MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.52MB + Index: 0.41MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.86MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.31MB + Index: 0.31MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.50MB + Index: 0.88MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Data: 22.56MB + Index: 37.20MB + Engine InnoDB
wp_wsal_occurrences: Data: 45.58MB + Index: 20.08MB + Engine InnoDB
wp_wsal_sessions: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 9.52MB + Index: 7.91MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.27MB + Index: 0.41MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.36MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 6719
custom_css: 1
customize_changeset: 3
mgmlp_media_folder: 641
nav_menu_item: 6
oembed_cache: 1
page: 7
popup: 2
popup_theme: 9
post: 6
product: 3381
product_variation: 51
revision: 1267
shop_coupon: 128
shop_order: 6375
shop_order_refund: 458
wc_order_email: 1
wc_order_status: 14
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

PublishPress Capabilities: by PublishPress – 2.5.0
Cookie Notice: by dFactory – 1.2.48
Custom Taxonomy Order: by Marcel Pol – 3.4.4
Facebook for WooCommerce: by Facebook – 2.6.22
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 7.8.2
Limit log in attempts reloaded: by Limit log in attempts reloaded – 2.25.5
Loco Translate: by Tim Whitlock – 2.6.2
Media Library Folders Pro For WordPress: by Max Foundry – 7.1.6
Facebook for WordPress: by Facebook – 3.0.7
Popup Maker: by Popup Maker – 1.16.7
PublishPress Future: by PublishPress – 2.7.7
Product GTIN (EAN, UPC, ISBN) for WooCommerce: by Emanuela Castorina – 1.1.1
Quick Featured Images: by Kybernetik Services – 13.6.0
Redirection: by John Godley – 5.3.3
Restricted Site Access: by Jake Goldman
10up
Oomph – 7.3.2

Search By SKU - for Woocommerce: by Unroll Digital – 0.8.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.22.21.25

Order Splitter for WooCommerce: by Fahad Mahmood – 4.6.2
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.0
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.20.1
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.5 (update to version 4.7.1 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.5
WooCommerce Global Payments HPP: by SkyVerge – 3.0.4
WooCommerce Stripe Gateway: by WooCommerce – 6.7.0
Pixel Manager for WooCommerce: by SweetCode – 1.20.2
WooCommerce Order Status Manager: by SkyVerge – 1.13.4
WooCommerce PayPal Payments: by WooCommerce – 1.9.3 (update to version 1.9.4 is available)
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 2.0.39
WooCommerce - ShipStation Integration: by WooCommerce – 4.2.0 (update to version 4.3.0 is available)
WooCommerce Waitlist: by Neil Pie – 2.3.4
WooCommerce: by Automattic – 6.8.2 (update to version 7.0.0 is available)
Yoast SEO: by Team Yoast – 19.6.1
WP Activity Log for WooCommerce: by WP White Security – 1.4.4
WP Activity Log (Premium): by WP White Security – 4.4.2.2
WP Updates Notifier: by Scott Cariss – 1.6.0

### Inactive Plugins (7) ###

Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.3
Akismet Anti-Spam: by Automattic – 5.0
Media Library Folders Pro for WordPress Reset: by Max Foundry – 7.1.6
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.19
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WP Activity Log: by WP White Security – 4.4.2.1

### Must Use Plugins (2) ###

Facebook Pixel GDPR Consent Checker: by Ronny Adsetts
Amazing Internet Ltd –

Find Products Failing Quality Control: by Orignally by Shane Gowland
Modifed and extended by Ronny Adsetts –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #8 - /
Basket: #9 - /basket/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Grays of Westminster Shop
Version: 1.0.0
Author URL: https://www.amazinginternet.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-10-25 10:49:52 +01:00
Options: ✔
Notes: 99
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Complete: 26,149
Oldest: 2022-09-23 15:00:22 +0100
Newest: 2022-10-24 14:56:59 +0100

Pending: 8
Oldest: 2022-10-24 15:11:57 +0100
Newest: 2022-10-24 21:14:43 +0100

### Status report information ###

Generated at: 2022-10-24 15:00:39 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @ronnyadsetts,

Thanks for your report. We were able to confirm there is a bug in the way the CSV import handles dates (vs the product edit page). We've created issue #35321 to take care of that.

We've also filed #35323, an enhancement request so that specific times can be set for on-sale dates too.

As such, I'm closing this issue for now, but feel free to re-open or ping me in case I've missed something or misrepresented your report.

Thank you!
