### ISSUE TITLE
CES: Display snackbar when the user updates the product for the 3rd time

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#35302]
After a user had published their 3rd product with the new MVP, prompt with the snackbar to collect feedback.

Acceptance criteria:
- After a user creates their 3rd product with the  new experience, display snackbar prompt that triggers CES modal.
- Should only occur after 7 days of previous prompt (publishing first product)

**Comment by AnnaMag** [comment]
This is not part of the Cycle 31 scope.

**Comment by louwie17** [comment]
Going to close this, as this may not be relevant anymore with the work around already done for the new product editor.
We can always re-open if we do want something similar.
