### ISSUE TITLE
FirstDownlaodableProduct misspelled

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#35307]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

/src/Internal/Admin/Notes/FirstDownlaodableProduct.php

Both the file & class name are spelled incorrectly, should be FirstDownlaodableProduct

### Expected behavior

Correct spelling

### Actual behavior

Wrong spelling

### Steps to reproduce

none

### WordPress Environment

none

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the bug report @kkmuffme, would you be interested in submitting a pull request?

**Comment by kkmuffme** [comment]
If you could pinpoint me to the docs how you handle depreciation of classes, I'm happy to PR it. Or does this not need any deprecation and I can just change it? @psealock

**Comment by psealock** [comment]
Thanks @kkmuffme, since this is an internal namespace not to be consumed by third parties a simple rename of the class and file will suffice. Cheers!
