### ISSUE TITLE
CES: Add prompt with spotlight after 7 minutes to create product

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#35301]
Display a spotlight near the Feedback button ([added here](https://github.com/woocommerce/woocommerce/issues/35300)) when the user takes more than 7 mins to create a product on the classic UI.

![image](https://user-images.githubusercontent.com/444632/197814360-d3c71de4-99c5-4276-b880-ec3580cb6e84.png)

Update the copy to read:
> You have been working on this product for a few minutes now. Is there something you’re struggling with? Share your feedback.

See additional context on [this](https://github.com/woocommerce/woocommerce/issues/35127#issuecomment-1282884238) (and following) comments, and note the feedback button is added on [this issue](https://github.com/woocommerce/woocommerce/issues/35806).

Acceptance criteria:
- Spotlight appears after user takes 7 minutes to create a product (independent of user interaction)
- It is only displayed once

**Comment by joelclimbsthings** [comment]
@pmcpinto @jarekmorawski  Feeling a little confused and just wanted to confirm. When I initially looked at these issues regarding the feedback button ([here](https://github.com/woocommerce/woocommerce/issues/35300)) and the spotlight issue (this one), I assumed this was for the new MVP. The screenshot above, though, is _not_ for the MVP but actually the classic product editor. 

Also the feedback button already implemented on [this PR](https://github.com/woocommerce/woocommerce/pull/35690) is for the MVP, but appears in the `...` drop-down menu:

![image](https://user-images.githubusercontent.com/444632/204920259-44a0eed0-f510-44e9-b967-448a73260dc0.png)

That said, I don't see any discussion in any of these issues saying explicitly whether this should be impacting the classic editor, the new MVP, or both. 

Could you clarify?

**Comment by jarekmorawski** [comment]
Thanks for the ping, @joelclimbsthings. This change is for the current UX, so we'll need to add both the spotlight and the feedback button it points to. As for the new MVP, we'll tackle this problem differently there. 👍

**Comment by joelclimbsthings** [comment]
@pmcpinto Do we want to throw any tracks in here when the tip is displayed, or any such thing? We'll of course have the tracks event when and if they actually submit feedback.

**Comment by pmcpinto** [comment]
@joelclimbsthings sorry, I missed this ping. In #35126 is asked for the inclusion of a new prop to track the location where the CES prompt is viewed: ces_location: inside feature | outside feature
I think we have two options:
- Add a new prop to track the exact location where the CES prompt was displayed inside the feature
- Include the exact location in the ces_location prop rather than the binary value (inside/outside)

Which option is the best? cc @louwie17
