### ISSUE TITLE
Edit product page

### ISSUE THREAD

**Issue by Sparkzoot** [woothemes/woocommerce#35308]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the edit product page in WooCommerce, the short description window is collapsed as the default when I get into the product page requiring that I expand it and enlarge it every time I go to a product. This changed since the last update and up until then, the default for this window upon opening a the edit product page, was an expanded pane or window. I work with this all day long so have to deal with it constantly. On the other hand, all the other windows that I use on a regular basis default to the expanded or open status.

### Expected behavior

I expect the short description pane or window to be open or expanded by default every time I go into a product without having to expand it manually.

### Actual behavior

By default, the product short description pane or window is collapsed upon entering or opening the edit product page for any and every product.

### Steps to reproduce

I can't give you these steps to walk through since you don't have an account with our company to access our products, but here is a screen shot.

![image](https://user-images.githubusercontent.com/116667491/197834590-60882f74-56d3-43bf-baae-a0d010963fd9.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.budsartbooks.com
Site address (URL): https://www.budsartbooks.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.24
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.6.51-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 3325.49MB
Database Data Size: 1600.14MB
Database Index Size: 1725.35MB
wp_woocommerce_sessions: Data: 9.02MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 29.56MB + Index: 8.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 256.80MB + Index: 258.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_buds_report_products: Data: 2.52MB + Index: 4.16MB + Engine InnoDB
wc_buds_report_products_copy: Data: 2.52MB + Index: 0.31MB + Engine InnoDB
wc_buds_report_sales: Data: 6.52MB + Index: 7.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 16.02MB + Index: 11.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.02MB + Index: 6.03MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wp_commentmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_comments: Data: 57.59MB + Index: 43.09MB + Engine InnoDB
wp_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_notes_users_relations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fg_redirect: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.42MB + Index: 0.30MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 41.08MB + Index: 6.05MB + Engine InnoDB
wp_postmeta: Data: 551.95MB + Index: 762.34MB + Engine InnoDB
wp_posts: Data: 117.66MB + Index: 45.98MB + Engine InnoDB
wp_redirection_404: Data: 9.02MB + Index: 8.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 3.02MB + Index: 1.31MB + Engine InnoDB
wp_searchwp_index: Data: 163.58MB + Index: 256.98MB + Engine InnoDB
wp_searchwp_log: Data: 34.56MB + Index: 50.64MB + Engine InnoDB
wp_searchwp_status: Data: 1.33MB + Index: 1.50MB + Engine InnoDB
wp_searchwp_tokens: Data: 5.52MB + Index: 11.55MB + Engine InnoDB
wp_swp_cf: Data: 0.36MB + Index: 0.47MB + Engine InnoDB
wp_swp_index: Data: 64.63MB + Index: 45.14MB + Engine InnoDB
wp_swp_log: Data: 9.52MB + Index: 13.55MB + Engine InnoDB
wp_swp_tax: Data: 1.52MB + Index: 3.50MB + Engine InnoDB
wp_swp_terms: Data: 3.52MB + Index: 5.55MB + Engine InnoDB
wp_termmeta: Data: 9.45MB + Index: 7.88MB + Engine InnoDB
wp_terms: Data: 4.47MB + Index: 6.83MB + Engine InnoDB
wp_term_relationships: Data: 39.59MB + Index: 34.09MB + Engine InnoDB
wp_term_taxonomy: Data: 4.47MB + Index: 4.86MB + Engine InnoDB
wp_tinvwl_analytics: Data: 6.52MB + Index: 3.52MB + Engine InnoDB
wp_tinvwl_items: Data: 3.38MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 41.52MB + Index: 36.11MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.48MB + Engine InnoDB
wp_usin_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usin_user_data: Data: 0.36MB + Index: 0.39MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 2.52MB + Index: 2.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 31.56MB + Index: 36.55MB + Engine InnoDB
wp_wc_order_stats: Data: 8.52MB + Index: 9.52MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 5.62MB + Index: 11.54MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.53MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.28MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 4.02MB + Index: 0.25MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpo_wccm_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpo_wccm_customers: Data: 5.52MB + Index: 2.55MB + Engine InnoDB
wp_wpo_wccm_customer_notes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yoast_indexable: Data: 0.25MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.23MB + Index: 0.20MB + Engine InnoDB

### Post Type Counts ###

attachment: 28815
ctct_forms: 1
ctct_lists: 9
custom_css: 2
cwginstocknotifier: 871
elementor_library: 7
elementor_snippet: 1
nav_menu_item: 176
oceanwp_library: 1
oembed_cache: 2
page: 28
post: 9
product: 8352
revision: 12341
shop_coupon: 2
shop_order: 75689
shop_order_refund: 1342
usin_note: 5
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Ocean Extra: by OceanWP – 2.0.5
Akismet Anti-Spam: by Automattic – 5.0.1
Bulk Edit Products, Prices & Attributes for Woocommerce: by ELEX – 1.0.1
Constant Contact Forms for WordPress: by Constant Contact – 1.13.0
Elementor Pro: by Elementor.com – 3.7.7
Elementor: by Elementor.com – 3.7.8
Extended CRM For Users Insights: by denizz – 1.2.1
FG Magento to WooCommerce Premium Customer Groups module: by Frédéric GILLES – 1.4.0
FG Magento to WooCommerce Premium: by Frédéric GILLES – 3.5.0
Flexible Shipping PRO: by Octolize – 2.13.0
Flexible Shipping: by Octolize – 4.16.0
Groups: by itthinx – 2.16.2
Product Sales Report Pro for WooCommerce: by WP Zone – 2.2.27
Jetpack: by Automattic – 11.4
Ocean Cookie Notice: by OceanWP – 2.0.4
Ocean Modal Window: by OceanWP – 2.0.7
Ocean Product Sharing: by OceanWP – 2.0.4
Ocean Social Sharing: by OceanWP – 2.0.2
Product/Review CSV Import Export: by WebToffee – 3.8.3
Redirection: by John Godley – 5.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SearchWP WooCommerce Integration: by SearchWP – 1.3.10
SearchWP: by SearchWP – 4.2.7
Sweet Report: by Rick Johnston – 1.0
TI WooCommerce Wishlist: by TemplateInvaders – 2.0.8
Transients Manager: by WPBeginner – 2.0.3
User Switching: by John Blackbourn & contributors – 1.7.0
Users Insights: by Pexeto – 4.3.0
WooCommerce Backorder Manager Pro: by jeffrey-wp – 2.1.1
WooCommerce Fraud Prevention Plugin: by theDotstore – 2.1.2
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.1.2
WooCommerce Filter Orders by Product: by Kowsar Hossain – 3.2.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.2.1
Woocommerce Partial Orders Pro: by Code Ninjas – 1.9.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.1
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.9.3
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce: by Automattic – 7.0.0
Wordfence Security: by Wordfence – 7.7.1
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Super Cache: by Automattic – 1.9
WP Overnight Sidekick: by WP Overnight – 2.5.1

### Inactive Plugins (1) ###

WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bud's Art Books theme (OceanWP Child)
Version: 1.0
Author URL: https://oceanwp.org/%20http://www.rb-com.com
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 3.3.5
Parent Theme Author URL: https://oceanwp.org/about-oceanwp/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp-child-theme-buds/woocommerce/emails/customer-completed-order.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
Webhooks Enabled: ❌
						No signature key configured

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-25 17:42:11 -07:00
Options: ✔
Notes: 40
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 24,677
Oldest: 2022-09-24 09:53:44 -0700
Newest: 2022-10-25 09:49:21 -0700

Failed: 8
Oldest: –
Newest: –

Pending: 5
Oldest: 2022-10-25 09:51:22 -0700
Newest: 2022-10-25 23:30:21 -0700

### Status report information ###

Generated at: 2022-10-25 09:50:40 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by perks98** [comment]
I have just had a few customers recently complain that the short description was missing. Turns out like in this issue report that section is now collapsed by default. Hopefully this will get fixed soon.

**Comment by mattsherman** [comment]
This behavior was reverted in https://github.com/woocommerce/woocommerce/pull/35213. The short description field will no longer be auto-collapsed in WooCommerce 7.2.0.
