### ISSUE TITLE
Missing use/FQCN for WP_Error in TaskList.php

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#35304]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Missing use for WP_Error - used with FQCN but missing FQCN in phpdoc.

### Expected behavior

use statement

### Actual behavior

missing

### Steps to reproduce

none

### WordPress Environment

none

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
hi @kkmuffme, can you add more details please? Steps to reproduce or what `FQCN` means?

**Comment by psealock** [comment]
@kkmuffme ah ok I see you've submitted a pull request already, you can disregard the previous message.
