### ISSUE TITLE
CES: Add the feedback button to the navbar only on product MVP

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#35300]
Add a feedback button to the upper navbar on the products MVP: 

![image](https://user-images.githubusercontent.com/444632/197812928-73a7abc7-3b39-44a1-b670-9834512666ce.png)

This will trigger the updated CES modal. 

Acceptance criteria:
- Add button that triggers modal that only appears on the Products MVP screen.
- Add tracks

**Comment by louwie17** [comment]
@pmcpinto is there a specific action we should trigger for this feedback? Or would it be either `new_product_add_publish` or `new_product_update` from #35129

**Comment by pmcpinto** [comment]
As I mentioned [here](https://github.com/woocommerce/woocommerce/issues/35129#issuecomment-1325273264) we can keep it simple and use the same value independently if the product was published or updated.

**Comment by louwie17** [comment]
> As I mentioned [here](https://github.com/woocommerce/woocommerce/issues/35129#issuecomment-1325273264) we can keep it simple and use the same value independently if the product was published or updated.

Gotcha, I did use `new_product_page` action for this one, as this could be triggered before a user saves or publishes a product. But could revert back to the `new_product` action.

**Comment by pmcpinto** [comment]
I think we should use the same value across any CES action in the new product experience to keep it consistent. I don't mind if it's new_product_page or new_product

**Comment by jarekmorawski** [comment]
As discussed on Slack (p1669913936000899-slack-C9K5T0XSP), please double-check that we've applied the same tracking event to the share feedback button in the new MVP (implemented as part of #35177). cc @louwie17
