### ISSUE TITLE
Scripts after added to cart.

### ISSUE THREAD

**Issue by ProdesignerAgency** [woothemes/woocommerce#35331]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When i add product to cart and refresh page i have those scripts added:

![Zrzut-ekranu-2022-10-26-o-10 00 34](https://user-images.githubusercontent.com/6230472/197969600-b1ff92b8-c949-4436-9ee4-c5d8fbd2e30d.jpg)

### Expected behavior

I don`t want those scripts :-)

### Actual behavior

Scripts are added after add to cart.

### Steps to reproduce

1. add product to cart (ajax or not)
2. refresh the page (if ajax)
3. scripts are added.

### WordPress Environment

Clean instalation - so dosent matter - woocommerce only.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
This would be the new [Cart and Checkout Block](https://woocommerce.com/checkout-blocks/). Offhand I don't know if the old one is still enabled by default, but if you added the block, then this would be the reason.

**Comment by lkraav** [comment]
Possibly somewhat related https://github.com/woocommerce/woocommerce-blocks/discussions/8166
