### ISSUE TITLE
Support change files with windows line endings

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#35335]
While we have a tool for creating change files, sometimes change files are created manually. If the change file is otherwise valid, excepting windows line endings, we should still consider it as valid and let it pass.

This came up in #34292, which merged a change file with Windows line endings, and caused change file validation to break across the monorepo.

**Comment by jonathansadowski** [comment]
A note: it appears this is how Jetpack handles the issue, unless that doesn't apply to change files. I wonder if there's any reason to not apply something similar. https://github.com/Automattic/jetpack/blob/0dac885c0fc6cf283542de6ca4ebe19c00d23b6c/.gitattributes#L1-L2

**Comment by psealock** [comment]
We will investigate the implications of doing this in the same way Jetpack does it. It may involve a very large changeset that touches many files and we'd like to preserve git history for git blame.

**Comment by ObliviousHarmony** [comment]
Since this doesn't seem to have ever been worked on, and isn't really a persistent problem anymore, I'm going to go ahead and close this to clean out our backlog.
