### ISSUE TITLE
The new analytics reports have removed the average revenue total previously seen on reports

### ISSUE THREAD

**Issue by nicdwilson** [woothemes/woocommerce#35345]
### Describe the solution you'd like

The older revenue reports included a feature for Average Daily Sales. This is a key metric - comparing yesterday's sales to the running total for seven days, a month or the year to date is a solid dashboard number of any merchant.

While this can be manually calculated, it would be great to see the return of this feature to Analytics before Reports are fully deprecated

**The previous report**

![ViIgnL.png](https://user-images.githubusercontent.com/3624025/198183245-f3f22cb9-fddc-444f-a4c4-db312d0aaea7.png)

### Additional context

This report came from the merchant in 5661729-zen via Happiness.

**Comment by ianlin** [comment]
Just started looking into cleaning up Analytics-related issues  and noticed that we already have an average order value displayed in the `Analytics > Orders` section. It’s [calculated based on net sales divided by the total orders](https://github.com/woocommerce/woocommerce/blob/6e36d92a59b5953d4c2c981e82d3c61c59aa746e/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/DataStore.php#L107).

I'm closing this issue for now, but feel free to reopen it if there are additional concerns we should address.

<img width="1264" alt="Screenshot 2024-07-01 at 17 57 25" src="https://github.com/woocommerce/woocommerce/assets/914406/468e8a1f-dfac-4514-91f2-5fc23a2a4e93">
