### ISSUE TITLE
Analytics - Revenue: change date used in the report

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35348]
**Description:** In the Revenue report of our Analytics, the payment date is assigned to the order creation date, regardless of when the payment was made. This approach can be misleading and lead to complications in terms of taxes and invoices. We'll change the default date used in this report and introduce the flexibility to use different dates: created, paid or completed.

More info:
#32693
#6535
Slack: p1650010691719899-slack-C7U3Y3VMY
Reports: 4949047-zen

**Acceptance criteria:**
- [ ] Change the default order date used in the Revenue report to `date_paid`
- [ ] Create a new section in Analytics - Settings called "Revenue Reporting" 
- [ ] In this section, the user can change the date used in the Revenue report. He should be able to pick between `date_paid`, `date_completed`, and `date_created`
- [ ] When the user visits the Revenue report for the first time after we implement the change, we should a spotlight with more context about it

Mockups & flow: Nzh2NAf9RtpTwQLRXKYTjf-fi

**Event tracking:**
- We should add tracking to the spotlight
- We should include the settings change in the `wcadmin_analytics_settings_save` event. Perhaps we should add a new property

**Comment by pmcpinto** [comment]
@octaedro @AnnaMag created a new issue with more details and added it to the "Todo" column

**Comment by PowerGPU** [comment]
@pmcpinto Now how would we make sure that the orders in the future are considering the order paid date at all times. Is this something that we have to configure in settings? I wanted to verify that it's not only on reporting that this is able to change. In general this was something that Avalara (taxing integrations) requires to have so that order and the tax liability shows on the same day and as mentioned before not on the date the invoice was put together. Needs to read back to Avalara as the paid date.

**Comment by AnnaMag** [comment]
@octaedro, could you please assign the estimation based on the discussions so far? Thank you!

**Comment by pmcpinto** [comment]
> @pmcpinto Now how would we make sure that the orders in the future are considering the order paid date at all times. Is this something that we have to configure in settings? I wanted to verify that it's not only on reporting that this is able to change. In general this was something that Avalara (taxing integrations) requires to have so that order and the tax liability shows on the same day and as mentioned before not on the date the invoice was put together. Needs to read back to Avalara as the paid date.

Sorry for the late reply, but I was away for a couple of days and missed this comment. We'll be leveraging the existing [`date_paid` property](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties). We're not changing the order paid date logic.

**Comment by joelclimbsthings** [comment]
I've broken this work into separate issues, referenced above. Closing this one.
