### ISSUE TITLE
wc_get_product_ids_on_sale() returns variations ID bug

### ISSUE THREAD

**Issue by Lolosan** [woothemes/woocommerce#35340]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

function wc_get_product_ids_on_sale() fails to use 'parent_id' instead of 'id'

Tries to use array_merge between:
"wp_list_pluck( $on_sale_products, 'id' )"
and 
"array_diff( wp_list_pluck( $on_sale_products, 'parent_id' ), array( 0 ) )"

But, since they are numerical keys, array_merge just adds to the end of array. Failing to actually use "parent_id"

It should be using array_replace() instead, since that function does update value, instead of adding to the end

Line 173 of woocommerce\includes\wc-product-functions.php should be:
$product_ids_on_sale = wp_parse_id_list( **array_replace**( wp_list_pluck( $on_sale_products, 'id' ), array_diff( wp_list_pluck( $on_sale_products, 'parent_id' ), array( 0 ) ) ) );

### Expected behavior

$productos_on_sale = wc_get_product_ids_on_sale();

Array
(
    [0] => 85 //simple
    [1] => 288 //simple
    [2] => 292 //variable
    [3] => 654 //variable
)

### Actual behavior

$productos_on_sale = wc_get_product_ids_on_sale();

Array
(
    [0] => 85 //simple
    [1] => 288 //simple
    [2] => 288 //variation of  292
    [3] => 288 //variation of 292
    [4] => 670//variation of 654
    [5] => 672 //variation of 654
    [6] => 292 //variable
    [7] => 654 //variable
)

### Steps to reproduce

1. create variable product X
2. create a bunch of variations in product X
3. put some of those variations on sale
4. go to file woocommerce\includes\wc-product-functions.php
5. comment line 168 (disable return transient)
6. $productos_on_sale = wc_get_product_ids_on_sale();
7. print_r($productos_on_sale)
8. check printed ids

### WordPress Environment

Fresh WP 6.0.3
Fresh WC 7.0.0
PHP 8.0.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the bug report @Lolosan 

>Line 173 of woocommerce\includes\wc-product-functions.php should be:
$product_ids_on_sale = wp_parse_id_list( array_replace( wp_list_pluck( $on_sale_products, 'id' ), array_diff( wp_list_pluck( $on_sale_products, 'parent_id' ), array( 0 ) ) ) );

Would you be interested in submitting a pull request?

**Comment by Lolosan** [comment]
> 

Never done it before. Just stumbled upon it when making my custom theme

Let me try

**Comment by Lolosan** [comment]
> Thanks for the bug report @Lolosan
> 
> > Line 173 of woocommerce\includes\wc-product-functions.php should be:
> > $product_ids_on_sale = wp_parse_id_list( array_replace( wp_list_pluck( $on_sale_products, 'id' ), array_diff( wp_list_pluck( $on_sale_products, 'parent_id' ), array( 0 ) ) ) );
> 
> Would you be interested in submitting a pull request?

I made the PR now

**Comment by vedanshujain** [comment]
Closing as won't fix, see details in https://github.com/woocommerce/woocommerce/pull/35364#issuecomment-1300504128
