### ISSUE TITLE
[Enhancement]: Declare compatibility for custom order tables

### ISSUE THREAD

**Issue by sebastianpisula** [woothemes/woocommerce#35359]
### Describe the solution you'd like

I would like to declare compatibility for custom order tables via plugin header data in custom param, for example: `WC comaptibility: HPOS`

Example: 
```
/**
 * Plugin Name: Example
 * WC requires at least: 6.7
 * WC tested up to: 7.1
 * WC comaptibility: HPOS
 * Requires PHP: 7.4
 */
```

### Describe alternatives you've considered

```
add_action( 'before_woocommerce_init', function() {
	if ( class_exists( '\Automattic\WooCommerce\Utilities\FeaturesUtil' ) ) {
		\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
	}
} );
```

**Comment by rrennick** [comment]
@sebastianpisula Thanks for creating the issue. I appreciate the simplicity of your proposal. It would be great if we could implement something this simple. However, scanning plugin headers on every request is a significant performance hit and does not scale on larger sites. The other plugin header are only used within the core plugin update functionality where the plugin header scans typically only occur a couple times a day.

I'll close the issue as won't fix for performance reasons.
