### ISSUE TITLE
Add to WooCommerce Product Price (multiple plugins)

### ISSUE THREAD

**Issue by phix8** [woothemes/woocommerce#35365]
### Describe the solution you'd like

There are projects that come up often for me where I need to have multiple plugins adding to the final product price. For example, I need to use variable products with **extra product options** and also include **complex calculations** based on the total of those two, like including rent to own or financing options. If rent to own or financing is chosen then the overall product price, the one that is passed through to the cart, will change to a down payment rather than paying the whole thing at once. Currently, WooCommerce doesn't allow for multiple plugins to work together to change the product price, nor does it allow for dynamic checkout pages/flows based on conditions chosen on the product page (like adding a contract signing step before payment where calculations from the product page are prepopulated). I've looked around at many many MANY plugins and there is no solution other than custom coding.

### Describe alternatives you've considered

I might be able to accomplish this with Formidible Forms, but not really in as clean of a way as I would like (and their plugin is $599 per year). There has been a distinct gap in this area in the WC community for years. I've been seeking solutions since 2017 for this and have only been able to come up with a clunky and cumbersome solution using Calculated Fields Form. Please consider adding some functionality that will help this idea along.

**Comment by rrennick** [comment]
@phix8 Thanks for creating the issue. Unfortunately, given how the WordPress hook and filter system works, compatibility between extensions needs to be coordinated among the extensions. There isn't any way for WooCommerce to arbitrate conflict among other extensions.
