### ISSUE TITLE
WooCommerce legacy assets missing SCSS files after being packaged

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#35386]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When running `pnpm run build:zip` for WooCommerce, `SCSS` files are missing from the build package of `assets/css`.

First reported p1666079900096379-slack-C02GB41LGHM

### Expected behavior

`SCSS` files should still be there.

### Actual behavior

`SCSS` files are missing.

### Steps to reproduce

1. `pnpm install`
2. `cd plugins/woocommerce`
3. `pnpm run build:zip`
4. Unzip the package and look in `assets/css`. `SCSS` files are missing.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by LukasFritzeDev** [comment]
might be related to https://github.com/woocommerce/woocommerce/issues/31617
