### ISSUE TITLE
Tracks: add new prop to product publish and update events

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35393]
**Description:** some extensions like WooCommerce Gift Cards create a "trait" in the product form, similar to the "virtual" and "downloadable" options. We should add a prop to wcadmin_product_update and wcadmin_product_add_publish, to understand how many users are managing products with this kind of 3PDs traits enabled.

**Comment by pmcpinto** [comment]
@AnnaMag it would be great if the porter could handle this during the current cycle and include it in 7.2.

**Comment by mattsherman** [comment]
@pmcpinto Are these traits standardized in any way? I didn't find any documentation for them, but maybe I'm just not looking in the right spot. I'm not sure exactly how we can do this in a standardized fashion.

**Comment by pmcpinto** [comment]
Good question. I couldn't find any documentation either, so maybe it's not standardized. Can you check how it's implemented in the Gift cards extension?

**Comment by nathanss** [comment]
I investigated for a while and it seems that the way of adding the checkboxes to the product screen is through the `product_type_options` filter. Here's where the filter is applied:

```php
private static function get_product_type_options() {
		/* phpcs:disable WooCommerce.Commenting.CommentHooks.MissingHookComment */
		return apply_filters(
			'product_type_options',
			array(
				'virtual'      => array(
					'id'            => '_virtual',
					'wrapper_class' => 'show_if_simple',
					'label'         => __( 'Virtual', 'woocommerce' ),
					'description'   => __( 'Virtual products are intangible and are not shipped.', 'woocommerce' ),
					'default'       => 'no',
				),
				'downloadable' => array(
					'id'            => '_downloadable',
					'wrapper_class' => 'show_if_simple',
					'label'         => __( 'Downloadable', 'woocommerce' ),
					'description'   => __( 'Downloadable products give access to a file upon purchase.', 'woocommerce' ),
					'default'       => 'no',
				),
			)
		);
		/* phpcs: enable */
	}
```

This is the way plugins like one page checkout and gift cards add their checkboxes. So I'm thinking that we can add a tracks event on the back-end and call this filter. This will return all the checkboxes that are added through plugins

**Comment by pmcpinto** [comment]
Nathan, thanks for investigating this. 

>  So I'm thinking that we can add a tracks event on the back-end and call this filter. This will return all the checkboxes that are added through plugins

It would be very helpful to add an event or property to give us this information.
