### ISSUE TITLE
Managed & Unmanaged stock - Pending-processing & processing-complete stock reduction issue. 

### ISSUE THREAD

**Issue by brettnzl** [woothemes/woocommerce#35408]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is a conflict or a bug issue that happens when you change stock from unmanaged to managed while an order is already placed. 

Please look to reproduce:
- Create a product with unmanaged stock ie (in stock): 
![image](https://user-images.githubusercontent.com/13056905/198911847-b92ba455-8a8d-4e6c-aed8-b5eba7f0dade.png)

- Place an order with a random number of items in stock (for example 5) 
- Once the order is placed under your shop orders you will have a correct order at the "pending" stage. 

At this point, we have a merchant who has grabbed items from their shelves and realized there are only 6 products in stock, so they have gone and edited the product to be managed. 

- Change product in order from unmanaged to managed stock - Change stock quantity to 1 (minus the 5 that have already been placed).
![image](https://user-images.githubusercontent.com/13056905/198912125-35419249-4499-47f8-a4b2-1713fe413a1d.png)

- Go back to the order that you have just placed, and changed the status from pending to complete.
- You will notice that the order (that was placed when stock available was unmanaged) has now changed the stock levels to a negative number on change to complete:
![image](https://user-images.githubusercontent.com/13056905/198912239-b9bab2a9-7331-4e1a-a06d-f32b16c35c27.png)

This now puts the product out of stock. 

If you use managed stock from the beginning everything works correctly, and the stock level is reduced when you change from pending to processing, but there is an issue with changing unmanaged to managed and processing an order which was placed on unmanaged stock levels. 

Ideally, this could be solved by changing the remaining stock to 6 instead of 1 when changing managed to unmanaged, but this would then allow other customers to potentially place orders before you have completed the order. 

I assumed this may be an issue relating to backorder and changing stock levels at 2 different hooks (either pending to processing, or processing to complete) either way it is an issue. test it for yourself. 

### Expected behavior

I would expect that the stock level wouldnt be decreased if an order was placed before the stock level was changed from managed to unmanaged. 

### Actual behavior

It is in the description of the bug, just to say it again:

**Managed Stock Product** - (current stock: 5) order placed for 5, status changed pending to processing (successful transaction) -5 stock.  remaining stock = 0.
﻿
**Unmanaged Stock Product** - (current stock: unlimited) order placed for 5,  status changed pending to processing (successful transaction). no stock levels changed. 

However, if you then change the **unmanaged** to **managed** and stock level to 1 (because after taking the 5 off the shelf you only have 1 left) the system checks on (processing to complete) to drop the stock level by order amount ie 5, if its managed and hasn't been dropped already.  which would give you -4 stock. 

### Steps to reproduce

1. Create a test product
2. Set the stock level to "instock" unmanaged.
3. Place an order ie 5. 
4. before you change the order from processing to complete, imagine you have 6 products on the shelf, you take 5 of and have 1 remaining, go change the product stock level to "managed" and 1 in stock.
5. go back to the order and change the status from processing to complete
6. you will see an "Adjusted stock: {product} (1 -> -4)
7. your product is now "out of stock" even if you have 1 on the shelf. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.chefscomplements.co.nz
Site address (URL): https://www.chefscomplements.co.nz
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 2171.37MB
Database Data Size: 1614.00MB
Database Index Size: 557.37MB
wp_woocommerce_sessions: Data: 49.09MB + Index: 1.45MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 8.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 49.59MB + Index: 46.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_order_sent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woof_query_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 12.02MB + Index: 14.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 10.02MB + Index: 7.03MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 20.55MB + Index: 19.09MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 6.44MB + Index: 0.78MB + Engine InnoDB
wp_gf_entry_meta: Data: 8.52MB + Index: 11.58MB + Engine InnoDB
wp_gf_entry_notes: Data: 2.52MB + Index: 0.58MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_grp_google_review: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_grp_google_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nbanalytics: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 34.34MB + Index: 10.41MB + Engine InnoDB
wp_postmeta: Data: 599.53MB + Index: 266.14MB + Engine InnoDB
wp_posts: Data: 102.59MB + Index: 24.86MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.38MB + Index: 0.09MB + Engine InnoDB
wp_rg_lead_detail: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 3.52MB + Index: 4.98MB + Engine InnoDB
wp_terms: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 4.31MB + Index: 2.36MB + Engine InnoDB
wp_term_taxonomy: Data: 1.48MB + Index: 0.14MB + Engine InnoDB
wp_trustindex_google_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 40.58MB + Index: 38.11MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_vtcrt_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtcrt_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtcrt_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 7.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 6.52MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 3.52MB + Index: 4.14MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 2.22MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 297.00MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 5.02MB + Index: 1.16MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Data: 134.64MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 1.02MB + Index: 0.27MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_wfStatus: Data: 7.02MB + Index: 3.03MB + Engine InnoDB
wp_wfTrafficRates: Data: 58.63MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.22MB + Index: 0.30MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.16MB + Index: 0.34MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 2.03MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 4.52MB + Index: 6.50MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 4.52MB + Index: 6.69MB + Engine InnoDB
wp_yith_wapo_addons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wapo_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 84.66MB + Index: 31.20MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 8.05MB + Index: 9.19MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_yoast_prominent_words: Data: 4.52MB + Index: 10.55MB + Engine InnoDB
wp_yoast_seo_links: Data: 12.48MB + Index: 7.80MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ywdpd_exclusion_list_table: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 193
acf-field-group: 20
attachment: 56429
ep-pointer: 1
ep-synonym: 1
laybuy_quote: 285
nav_menu_item: 54
oembed_cache: 115
page: 22
post: 397
postman_sent_mail: 250
product: 12106
product_variation: 5253
pst_spec: 3
pst_spec_attr: 7
pst_spec_group: 4
revision: 3614
shop_coupon: 16
shop_order: 42855
shop_order_refund: 2289
specs-table: 1
wishlist: 1352
wpmm_theme: 2
yith_wcan_preset: 1
ywar_reviews: 26
ywdpd_discount: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Gravity Forms: by Gravity Forms – 2.6.6
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.0.0
Advanced Custom Fields: Image Aspect Ratio Crop: by Johannes Siipola – 6.0.2
AddToAny Share Buttons: by AddToAny – 1.8.5
Advanced Cron Manager: by BracketSpace – 2.4.2
Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Classic Editor: by WordPress Contributors – 1.6.2
Cloudflare: by Cloudflare
Inc. – 4.11.0

Custom Post Type UI: by WebDevStudios – 1.13.1
Custom You May Also Like for WooCommerce: by Scott Nelle – 1.3
Debug Bar ElasticPress: by 10up – 2.1.1
ElasticPress: by 10up – 4.3.1
Human Presence: by Human Presence Technology – 3.4.38
Facebook Chat Plugin - Live Chat Plugin for WordPress: by Meta – 2.5
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 8.3.8
Gravity Forms Klaviyo Add-On: by EFE Technology – 1.1
MonsterInsights Pro: by MonsterInsights – 8.9.1
Imagify: by Imagify - Optimize Images & Convert WebP – 2.0
Imsanity: by Exactly WWW – 2.8.2
Klaviyo: by Klaviyo
Inc. – 3.0.4

Latitude Interest Free Gateway for WooCommerce: by Latitude Financial Services – 1.0.8
Laybuy Gateway for WooCommerce: by Laybuy – 5.3.7
Ninetyblack Analytics: by ninetyblack – 1.8.1
WooCommerce Paymark Online EFTPOS Payment Gateway: by YHP – 1.4
Post SMTP: by Post SMTP – 2.1.10
Product Sales Report for WooCommerce: by Aspen Grove Studios – 1.5.1
Product Specification Table for WooCommerce: by FantasticPlugins – 1.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
TP WooCommerce Product Gallery PRO: by TP Plugins – 2.2.4
Ultimate Dashboard: by David Vongries – 3.7.1.5
User Role Editor: by Vladimir Garagulya – 4.63.1
WPC Smart Wishlist for WooCommerce: by WPClever – 4.4.2
WooCommerce Back In Stock Notifications: by WooCommerce – 1.3.2
Windcave Gateway for WooCommerce: by Windcave – 1.1.3
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.5.2 (update to version 10.7.5 is available)
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.18.1
WooCommerce Shipment Tracking: by WooCommerce – 1.7.1 (update to version 1.8.0 is available)
WooCommerce Social Login: by SkyVerge – 2.8.5 (update to version 2.11.2 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.40 (update to version 3.0.41 is available)
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.6
WooCommerce: by Automattic – 7.0.0
Wordfence Security: by Wordfence – 7.7.1
Yoast SEO Premium: by Team Yoast – 19.4
Yoast SEO: by Team Yoast – 19.9
WP Mega Menu: by Themeum – 1.4.2
Widgets for Google Reviews: by Trustindex.io  – 9.5.1
WP Rocket: by WP Media – 3.12.2
YITH WooCommerce Advanced Reviews: by YITH – 1.7.0
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITH – 3.11.1
YITH WooCommerce Quick View Premium: by YITH – 1.22.0

### Inactive Plugins (9) ###

Ajax add to cart for WooCommerce: by QuadLayers – 1.3.6
Akismet Anti-Spam: by Automattic – 5.0.1
CTX Feed: by WebAppick – 4.5.6
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.1
Humm / Oxipay Payment Gateway: by flexigroup – 2.0.0
Query Monitor: by John Blackbourn – 3.10.1
Woo Custom Taxonomies Coupons: by Roman Bondarenko – 2.1
WP fail2ban: by Charles Lecklider – 4.4.0.8
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.6.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #12 - /kitchen-shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #15 - /my-account/
Terms and conditions: #115280 - /terms-conditions/

### Theme ###

Name: 
Version: (update to version 0 is available)
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: chefs/woocommerce/archive-product.php
chefs/woocommerce/cart/cart.php
chefs/woocommerce/checkout/form-checkout.php
chefs/woocommerce/checkout/form-coupon.php
chefs/woocommerce/checkout/review-order.php
chefs/woocommerce/content-product.php
chefs/woocommerce/content-single-product.php
chefs/woocommerce/emails/admin-cancelled-order.php version 2.5.0 is out of date. The core version is 4.1.0
chefs/woocommerce/emails/admin-new-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-invoice.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-new-account.php version 1.6.4 is out of date. The core version is 6.0.0
chefs/woocommerce/emails/customer-note.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-refunded-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/customer-reset-password.php version 2.0.0 is out of date. The core version is 4.0.0
chefs/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 5.6.0
chefs/woocommerce/emails/email-footer.php version 2.3.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/email-header.php version 2.4.0 is out of date. The core version is 4.0.0
chefs/woocommerce/emails/email-order-items.php version 3.2.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 4.0.0
chefs/woocommerce/emails/plain/admin-cancelled-order.php version 2.5.0 is out of date. The core version is 4.1.0
chefs/woocommerce/emails/plain/admin-new-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-invoice.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-new-account.php version 2.0.0 is out of date. The core version is 6.0.0
chefs/woocommerce/emails/plain/customer-note.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-refunded-order.php version 2.5.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/customer-reset-password.php version 2.3.0 is out of date. The core version is 3.7.0
chefs/woocommerce/emails/plain/email-addresses.php version 2.2.0 is out of date. The core version is 5.6.0
chefs/woocommerce/emails/plain/email-order-items.php version 2.1.2 is out of date. The core version is 5.2.0
chefs/woocommerce/loop/orderby.php
chefs/woocommerce/loop/result-count.php
chefs/woocommerce/loop/sale-flash.php
chefs/woocommerce/single-product/add-to-cart/simple.php
chefs/woocommerce/single-product/meta.php
chefs/woocommerce/single-product/price.php
/container/application/public/wp-content/plugins/yith-woocommerce-advanced-reviews//templates/ywar-rating.php version - is out of date. The core version is 3.6.0
chefs/woocommerce/single-product/related.php
chefs/woocommerce/single-product/review.php
chefs/woocommerce/single-product/title.php
chefs/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed feeds ###

7dd98d54ff6dd799: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": Enabled
Expanded schema markup: -
Debug key: ee1befcb-6e7e-4fff-90a7-045409a47f56

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Product description: Main product description (full preferred) plus variation description
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Global Trade Item Number (GTIN): 
Size system: 

### WooCommerce Google Product Feed DB status ###

{attr_name}: 15
{attr_name}: 15
{attr_name}: Empty
{attr_name}: 5595 items

### Back In Stock ###

Database Version: 1.3.2
Loopback Test: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-05 22:23:21 +12:00
Options: ✔
Notes: 79
Onboarding: completed

### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: ✔ Available
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Complete: 37,359
Oldest: 2022-10-02 16:49:41 +1300
Newest: 2022-10-31 14:20:27 +1300

Failed: 3
Oldest: 2022-04-13 14:33:28 +1200
Newest: 2022-10-27 08:55:37 +1300

Pending: 2
Oldest: 2022-10-31 14:21:27 +1300
Newest: 2022-11-01 11:21:46 +1300

### Status report information ###

Generated at: 2022-10-31 14:20:36 +13:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @brettnzl,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.0.0 version and WordPress 6.0.3 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/199178987-abb863f0-4aa3-4a26-8459-9d5ad36fd295.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
> we have a merchant who has grabbed items from their shelves and realized there are only 6 products in stock, so they have gone and edited the product to be managed.

> Change product in order from unmanaged to managed stock - Change stock quantity to 1 (minus the 5 that have already been placed).

> Go back to the order that you have just placed, and changed the status from pending to complete.

@brettnzl Thanks for creating the issue. When an order is in Pending status the product stock has not been reduced. The merchant should have set the stock to 6. I'll close this as a question.
