### ISSUE TITLE
[GlobalStep] [WP6.1 TT3] Unable to view "View cart" button text after hovering on "Product" page. 

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#35418]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unable to view "View cart" button text after hovering on "Product" page.

### Expected behavior

"View Cart" button text should be visible upon hovering over the button.

### Actual behavior

"View Cart" button text is not visible upon hovering over the button.

### Steps to reproduce

1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins.
3. Complete the Onboarding setup wizard.
4. Select Twenty Twenty three Theme.
5. From Shop page select any product and go to Product page
6. Add the product to cart.
7. Hover over the "View Cart" button
8. Observe that, "View Cart" button text is not visible upon hovering

### Note:
Same observed on different pages.
1. "Select options" button on shop page.
2. "Proceed to checkout" button on cart page.
3. "Return to shop" button when cart page is empty.

### Screenshot:
Twenty Twenty-Three Theme:

![#35418 1](https://user-images.githubusercontent.com/41110392/199035184-2bef0cf7-5fb7-46d9-a27c-1b53f00bab3b.png)

![#35418 2](https://user-images.githubusercontent.com/41110392/199035209-463a2c8d-68e2-4424-8cbd-c79c49cc72e6.png)

![#35418 3](https://user-images.githubusercontent.com/41110392/199035239-b14c1250-8a9f-46c5-b346-faddd97e0ac7.png)

![#35418 4](https://user-images.githubusercontent.com/41110392/199035273-a97725ea-9d42-4391-a709-2bc66a63d45f.png)

### WordPress Environment

WooCommerce 7.1-beta.1
WordPress version: 6.1-beta2

PC:
Windows 10
Chrome(Version 107.0.5304.88)
Firefox(Version 106.0.2)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.4
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1-RC5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.32
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 4.95MB
Database Data Size: 3.45MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Query Monitor: by John Blackbourn – 3.10.1
Companion Plugin: by Osk – 1.28
WooCommerce: by Automattic – 7.1.0-rc.1-pulls-238
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.3

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Gutenberg: by Gutenberg Team – 14.4.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-01 08:44:07 +00:00
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Complete: 37
Oldest: 2022-10-31 08:45:37 +0000
Newest: 2022-10-31 14:35:34 +0000

Pending: 1
Oldest: 2022-11-01 08:44:11 +0000
Newest: 2022-11-01 08:44:11 +0000

### Status report information ###

Generated at: 2022-10-31 14:43:19 +00:00
`

</details>

**Comment by tammullen** [comment]
This is related to a WordPress 6.1 Issue: https://core.trac.wordpress.org/ticket/56928

**Comment by sabernhardt** [comment]
Core 56928 should have fixed the "Add to Cart" link hover color for anyone who already visited the cart page. However, the "View Cart" or "Continue Shopping" link color defined within the plugin does not cooperate with the background change from green to black.
`.woocommerce .woocommerce-message a`
https://github.com/woocommerce/woocommerce/blob/e66d33554213f7b87294c6f312c1ee50baa41d16/plugins/woocommerce/client/legacy/css/twenty-twenty-three.scss#L141-L142

**Comment by rrennick** [comment]
This has been fixed:

<img width="230" alt="Screenshot 2023-06-22 at 4 08 12 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/418ae3f1-f8f6-4511-aa9a-38398c673188">
