### ISSUE TITLE
[HPOS] Support declaring (in)compatibility via header fields

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#35413]
We already support compatibility declarations via code. However, since the code compatibility declaration cannot be active without the plugin also being active, we can't tell whether the plugin is compatible with HPOS or not beforehand.

This issue scopes supporting compatibility declaration in the plugin header itself so that we can prevent activation of the incompatible plugin in the first (and/or disable the feature, whichever is appropriate).

**Comment by barryhughes** [comment]
Closing; after further discussion, we feel the `FeaturesController`-based approach (already in use) meets most of our needs, and we additionally confirmed that plugin headers will not be needed for marketplace purposes.
