### ISSUE TITLE
Download permissions do not work with custom order status.

### ISSUE THREAD

**Issue by shoelaced** [woothemes/woocommerce#35416]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I posted about this in the WordPress support forum and it seems unclear whether this is a bug or intentional for some reason, but it's bothersome and inconvenient so I'm reporting it nevertheless.

The issue is that despite being able to grant download permissions on an order that has a custom status (in my case, "Delivered," which is added by the Advanced Shipment Tracking plugin), the downloads are not available in the customer's account unless the order is reverted back to "Completed." 

### Expected behavior

I would expect downloads to still be available to customers for orders with a custom status by default. I'd also expect that if someone were creating a custom status such as "Pending Verification" or something that they may not want download permissions to be granted, and thus there should also be a way for developers to indicate that downloads should not be available for a certain status if desired.

### Actual behavior

After changing an order from "Completed" to "Delivered" (our custom status), the customer is no longer able to download their purchase, as the downloads vanish from their account page. The permissions still appear to be properly granted in the order admin, yet they do not appear on the frontend.

### Steps to reproduce

1. Create an order.
2. Set it to a custom status (to fully duplicate, install the Advanced Shipment Tracking plugin and turn on the option of Delivered status.)
3. Grant download permissions to a downloadable file.
4. Sign in as a customer.
5. View the account page and notice that the download is not available.

[The support person in the forums](https://wordpress.org/support/topic/download-permissions-not-working-for-custom-order-status/) was able to duplicate this.

### WordPress Environment

Latest WP, WC, and PHP 8.0, on a Nginx server.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @shoelaced. Agreed, the downloads availability login can be confusing at times; but the good news is that [there's a filter to alter the default download availability](https://github.com/woocommerce/woocommerce/blob/99be7b960b1d8cb99f4ad1f44747c275bd7e78d8/plugins/woocommerce/includes/class-wc-order.php#L1623), so you could use a snippet like this one:

```php
add_filter('woocommerce_order_is_download_permitted', function($available, $order) {
    return $available || $order->get_status() === 'delivered';
}, 10, 2);
```

I'm closing this issue for now, but feel free to comment back if the suggested solution doesn't work for you or if there's some more context you want to provide.

**Edit:** Indeed as commented below, it's `'delivered'`, not `'Delivered'`; I've fixed it.

**Comment by shoelaced** [comment]
@Konamiman Thanks! This worked (once I changed 'delivered' to lowercase). Cheers.
