### ISSUE TITLE
Two errors related to WooCommerce in the new version

### ISSUE THREAD

**Issue by Michaelgimii** [woothemes/woocommerce#35451]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi

After updating WooCommerce to a new version, two errors are always displayed in the browser console. **(These two errors are only displayed in the Elementor editor)**

![Screenshot (864)](https://user-images.githubusercontent.com/88034902/199223679-cf325e75-3afa-426c-a1a5-9f78cb562a5b.png)

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

View only in the Elementor editor in your browser console.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @Michaelgimii,
Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.1.0 version and WordPress 6.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/200764071-3a798b9c-bef3-4fc1-b7f2-4f20e060c45c.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.
