### ISSUE TITLE
[Enhancement]: Add tracks events to a few sections

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#35456]
### Describe the solution you'd like

There are a few sections that should have more tracks events.

The sections that need more tracks events recorded are:
- Attributes
- Shipping
- Images

**Comment by pmcpinto** [comment]
@octaedro do you have an estimate of when this will be implemented? I'd like to test the telemetry. Thanks

**Comment by octaedro** [comment]
Hey @pmcpinto,
The changes proposed in this issue have been included in WooCommerce `v7.3.0` in [this PR](https://github.com/woocommerce/woocommerce/pull/35262).
I'm going to close this issue.
