### ISSUE TITLE
Product not apear!

### ISSUE THREAD

**Issue by KitoDan-Dev** [woothemes/woocommerce#35454]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi, i had installed the "Event Manager and Tickets Selling Plugin for WooCommerce" and create a event, but when i go to the products page he has been counted but not appear on product list.

### Expected behavior

I need the created event on my product list, for seling him.

### Actual behavior

The Event don't apear on my produtc page and product list

### Steps to reproduce

![image](https://user-images.githubusercontent.com/82036894/199290238-8ae834d3-f025-4723-a146-0a99dbae297d.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://cerradovive.com
Site address (URL): http://cerradovive.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.32
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.16-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 14.65MB
Tamanho dos dados do banco de dados: 10.25MB
Tamanho do índice do banco de dado: 4.40MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 0.27MB + Índex: 0.17MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 0.14MB + Índex: 0.13MB + mecanismo InnoDB
wp_aioseo_cache: Dados: 0.09MB + Índex: 0.03MB + mecanismo InnoDB
wp_aioseo_notifications: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_aioseo_posts: Dados: 0.08MB + Índex: 0.02MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_edd_adjustmentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_adjustments: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_edd_customermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_customers: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_edd_customer_addresses: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_edd_customer_email_addresses: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_edd_logmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_logs: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_edd_logs_api_requestmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_logs_api_requests: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_logs_file_downloadmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_logs_file_downloads: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_edd_notemeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_notes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_edd_notifications: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_edd_ordermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_orders: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_edd_order_addresses: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_edd_order_adjustmentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_order_adjustments: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_edd_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_edd_order_items: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_edd_order_transactions: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_etn_events: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_etn_trans_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_e_events: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gla_budget_recommendations: Dados: 0.22MB + Índex: 0.14MB + mecanismo InnoDB
wp_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gla_shipping_rates: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_litespeed_url: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_litespeed_url_file: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_templates: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_scheduled_tasks: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_bounces: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wp_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscriber_tag: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_tags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_options: Dados: 4.50MB + Índex: 0.16MB + mecanismo InnoDB
wp_postmeta: Dados: 0.14MB + Índex: 0.06MB + mecanismo InnoDB
wp_posts: Dados: 0.11MB + Índex: 0.06MB + mecanismo InnoDB
wp_saso_eventtickets_codes: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_saso_eventtickets_ips: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_saso_eventtickets_lists: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_download_directories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wpforms_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 5
customize_changeset: 1
download: 1
elementor_library: 2
etn: 1
etn-schedule: 1
event_listing: 2
mailpoet_page: 1
mep_events: 5
page: 17
post: 2
product: 3
revision: 45
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Hostinger: por Hostinger – 1.0.1
Akismet Anti-Spam: por Automattic – 5.0.1
All in One SEO: por Equipe All in One SEO – 4.2.6.1
All-in-One WP Migration: por ServMask – 7.67
Elementor: por Elementor.com – 3.8.0
Facebook para WooCommerce: por Facebook – 2.6.28
Google Analytics for WordPress by MonsterInsights: por MonsterInsights – 8.9.1
Google Listings and Ads: por WooCommerce – 2.2.0
Jetpack Protect: por Automattic – 1.0.4
Jetpack: por Automattic – 11.4
LiteSpeed Cache: por LiteSpeed Technologies – 5.3
Event Manager and Tickets Selling Plugin for WooCommerce: por MagePeople Team – 3.7.6
MailPoet: por MailPoet – 3.101.1
Mercado Pago payments for WooCommerce: por Mercado Pago – 6.3.1
WooCommerce: por Automattic – 7.0.0
WP Event Manager: por WP Event Manager – 3.1.32
WPForms Lite: por WPForms – 1.7.7.2

### Inactive Plugins (1) ###

WooCommerce Order Test - WP Fix It: por WP Fix It – 2.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base da loja: #48 - /?page_id=48
Carrinho: #49 - /?page_id=49
Finalização de compra: #50 - /?page_id=50
Minha conta: #51 - /?page_id=51
Termos e condições: ❌ Página não definida

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-01 20:49:17 -03:00
Options: ✔
Notes: 41
Onboarding: completed

### Action Scheduler ###

Complete: 443
Oldest: 2022-10-28 20:15:58 +0000
Newest: 2022-11-01 16:55:30 +0000

Failed: 1
Oldest: 2022-10-28 22:15:55 +0000
Newest: 2022-10-28 22:15:55 +0000

Pending: 11
Oldest: 2022-11-01 16:56:14 +0000
Newest: 2022-11-04 20:15:59 +0000

### Status report information ###

Generated at: 2022-11-01 13:55:39 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
Hi @danilobritobo thanks for raising this, but I think this is probably a question for the authors of "Event Manager and Tickets Selling Plugin for WooCommerce" because we can't confirm if this is our problem or not. Perhaps you could reach out to them for support: https://wordpress.org/support/plugin/mage-eventpress/
