### ISSUE TITLE
[HPOS] Replace usage of `CALC_FOUND_ROW` with direct count query (and caching) for performance

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#35464]
In `WC_Query` we currently use `CALC_FOUND_ROW` to get pagination results. Unfortunately, this is slow because MySQL needs to scan all rows with `CALC_FOUND_ROWS` instead of just going through the index, which it can do with a `COUNT(*)` query instead.

This issue scopes breaking the `CALC_FOUND_ROW` in WC_Query for HPOS in two separate queries, one to get the order ids and another to count total number of records.

**Comment by kevin25** [comment]
I can't agree with you more. This slows down my store all the time.
