### ISSUE TITLE
Is this correct release version?

### ISSUE THREAD

**Issue by dinesh4monto** [woothemes/woocommerce#35469]
https://github.com/woocommerce/woocommerce/blob/8f5378a8166e2d242cfeb601bb9580195d41ab88/plugins/woocommerce/includes/wc-conditional-functions.php#L534

**Comment by mustafauysal** [comment]
I came here to report this as well. It seems version mismatches with template changes.

**Comment by samueljseay** [comment]
This isn't strictly a bug, but it needs a dev team member to confirm if the version number is correct.

**Comment by jorgeatorres** [comment]
Hi @dinesh4monto @mustafauysal!

Thanks for your report. The version number is, in fact, incorrect.
We have a PR open that fixes the version number for a similarly affected template (https://github.com/woocommerce/woocommerce/pull/35473), but I'll make sure we also fix this instance here.

Thanks for catching the error!

**Comment by jorgeatorres** [comment]
Fixed in #35473.
