### ISSUE TITLE
Woocommerce Status is Not Showing 

### ISSUE THREAD

**Issue by Nitin132** [woothemes/woocommerce#35478]
![Dashboard-‹-Sleek-Fo-—-WordPress](https://user-images.githubusercontent.com/63965617/199672886-d5e82543-e8c8-43cb-aa65-e3a3e010d984.png)

woocommerce status is not showing  in Wordpress Dashboard. I m Using Wordpress 6.1 Version . Check Out The Screenshot Please . Please Help Me in this . Same issue I M facing in 2 Websites

**Comment by samueljseay** [comment]
Hi @Nitin132 I can understand that must be frustrating but to be able to help you we need more information.

Have you followed [the troubleshooting guide?](https://woocommerce.com/document/woocommerce-self-service-guide/)

Otherwise we need other details to reproduce this error, for example, we need to know if you have tried deactivating all other plugins and if you still see this issue.

**Comment by shankeyb** [comment]
@Nitin132 I too confirm this issue...the woocommerce widget does not display because there is a issue in code from line 66 to 75 for an temporary fix navigate to **includes/admin/class-wc-admin-dashboard.php**

FROM Line 66 replace the code with below one
``
	private function should_display_widget() {
// 			if ( ! WC()->is_wc_admin_active() ) {
// 				return false;
// 			}
		$has_permission           = current_user_can( 'view_woocommerce_reports' ) || current_user_can( 'manage_woocommerce' ) || current_user_can( 'publish_shop_orders' );
	$task_completed_or_hidden = 'no' === get_option( 'woocommerce_task_list_complete' ) || 'no' === get_option( 'woocommerce_task_list_hidden' );
			return $task_completed_or_hidden && $has_permission;
		}
``

After that the widget will get appeared in the Dashboard Panel

**Comment by Nitin132** [comment]
Ok I will try to replace this Code from line Number 66

**Comment by Nitin132** [comment]
Now I M Getting This Error Parse error: syntax error, unexpected token "private" in /home/mazbox/public_html/Mazbox-New/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php on line 72

**Comment by Nitin132** [comment]
private function get_top_seller() {
			global $wpdb;

			$query            = array();
			$query['fields']  = "SELECT SUM( order_item_meta.meta_value ) as qty, order_item_meta_2.meta_value as product_id
			FROM {$wpdb->posts} as posts";
			$query['join']    = "INNER JOIN {$wpdb->prefix}woocommerce_order_items AS order_items ON posts.ID = order_id ";
			$query['join']   .= "INNER JOIN {$wpdb->prefix}woocommerce_order_itemmeta AS order_item_meta ON order_items.order_item_id = order_item_meta.order_item_id ";
			$query['join']   .= "INNER JOIN {$wpdb->prefix}woocommerce_order_itemmeta AS order_item_meta_2 ON order_items.order_item_id = order_item_meta_2.order_item_id ";
			$query['where']   = "WHERE posts.post_type IN ( '" . implode( "','", wc_get_order_types( 'order-count' ) ) . "' ) ";
			$query['where']  .= "AND posts.post_status IN ( 'wc-" . implode( "','wc-", apply_filters( 'woocommerce_reports_order_statuses', array( 'completed', 'processing', 'on-hold' ) ) ) . "' ) ";
			$query['where']  .= "AND order_item_meta.meta_key = '_qty' ";
			$query['where']  .= "AND order_item_meta_2.meta_key = '_product_id' ";
			$query['where']  .= "AND posts.post_date >= '" . gmdate( 'Y-m-01', current_time( 'timestamp' ) ) . "' ";
			$query['where']  .= "AND posts.post_date <= '" . gmdate( 'Y-m-d H:i:s', current_time( 'timestamp' ) ) . "' ";
			$query['groupby'] = 'GROUP BY product_id';
			$query['orderby'] = 'ORDER BY qty DESC';
			$query['limits']  = 'LIMIT 1';

			return $wpdb->get_row( implode( ' ', apply_filters( 'woocommerce_dashboard_status_widget_top_seller_query', $query ) ) ); //phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
		}

**Comment by Nitin132** [comment]
After Adding This Code Nothing Come

**Comment by anastas10s-afk** [comment]
Reported in 5693572-zen also.

I could replicate the issue on a test installation and can verify that changing both `'yes' === get_option(` to `'no' === get_option(`, in line 72 of [class-wc-admin-dashboard.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php) indeed enables the widget to appear in the WordPress dashboard properly.

**Comment by Nitin132** [comment]
Not Working

**Comment by shankeyb** [comment]
**private function should_display_widget() {
// 			if ( ! WC()->is_wc_admin_active() ) {
// 				return false;
// 			}
                      $has_permission           = current_user_can( 'view_woocommerce_reports' ) || current_user_can( 'manage_woocommerce' ) || current_user_can( 'publish_shop_orders' );
			$task_completed_or_hidden = 'no' === get_option( 'woocommerce_task_list_complete' ) || 'no' === get_option( 'woocommerce_task_list_hidden' );
			return $task_completed_or_hidden && $has_permission;
}**

@Nitin132  - Just copy this may be in previous comment you haven't copied correctly so use this.

**Comment by Nitin132** [comment]
Resolved Thanks For Help

**Comment by psealock** [comment]
@Nitin132, thanks for the report. I'm glad you got it resolved.

**Comment by Robin-Easy4You** [comment]
hi, sorry, but i have the same problem with

Wordpress: 6.8.3
Woocommerce : 10.2.2

i listen all data here, but i don't have this includes/admin/class-wc-admin-dashboard.php perhaps the structure of my version is different

**Comment by Nitin132** [comment]
Please Take backup or your Website or take backup

**Comment by Nitin132** [comment]
Please try to reinstall wordpress again .

**Comment by Robin-Easy4You** [comment]
the problem is the version, now is in react

**Comment by Nitin132** [comment]
I don't face any problems with latest version

**Comment by Robin-Easy4You** [comment]
The problem with this version is that there is no folder to write the code in, since these folders do not exist in React.

**Comment by Robin-Easy4You** [comment]
The problem with HPOS: I am currently developing a simple plugin to get around this problem and upload all the necessary data. As soon as it is ready and complete, it will be published on our website for download.
