### ISSUE TITLE
Fatal error! There has been a critical error on this website. 

### ISSUE THREAD

**Issue by rizvee** [woothemes/woocommerce#35471]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

> Fatal error: Uncaught Error: Class "Normalizer" not found in /home//public_html/wp-includes/formatting.php:1605 Stack trace: #0 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1866): remove_accents() #1 [internal function]: {closure}() #2 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1867): array_walk() #3 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale() #4 /home//public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(85): WC_Countries->get_countries() #5 /home//public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(244): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->get_core_data() #6 /home//public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(358): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->initialize_core_data() #7 /home//public_html/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data() #8 /home//public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #9 /home//public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #10 /home//public_html/wp-admin/admin-footer.php(95): do_action() #11 /home//public_html/wp-admin/admin.php(297): require_once('/home//...') #12 {main} thrown in /home//public_html/wp-includes/formatting.php on line 1605

 

[02-Nov-2022 14:51:17 UTC] PHP Fatal error:  Uncaught Error: Class "Normalizer" not found in /home//public_html/wp-includes/formatting.php:1605
Stack trace:
#0 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1866): remove_accents()
#1 [internal function]: {closure}()
#2 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1867): array_walk()
#3 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale()
#4 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()
#5 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(273): WC_Countries->__get()
#6 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1353): WC_Countries->get_allowed_countries()
#7 /home//public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(129): wc_get_customer_default_location()
#8 /home//public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(118): WC_Customer_Data_Store_Session->set_defaults()
#9 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Customer_Data_Store_Session->read()
#10 /home//public_html/wp-content/plugins/woocommerce/includes/class-wc-customer.php(125): WC_Data_Store->read()
#11 /home//public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(838): WC_Customer->__construct()
#12 /home//public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(2550): WooCommerce->initialize_cart()
#13 /home//public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(657): wc_load_cart()
#14 /home//public_html/wp-includes/class-wp-hook.php(308): WooCommerce->init()
#15 /home//public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#16 /home//public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#17 /home//public_html/wp-settings.php(617): do_action()
#18 /home//public_html/wp-config.php(99): require_once('/home//...')
#19 /home//public_html/wp-load.php(50): require_once('/home//...')
#20 /home//public_html/wp-blog-header.php(13): require_once('/home/konezovd/...')
#21 /home//public_html/index.php(17): require('/home//...')
#22 {main}
  thrown in /home//public_html/wp-includes/formatting.php on line 1605

### Steps to reproduce

1. surfing products
2. some product doesn't open and show wp fatal error
3. tried to open dashboard via wp-admin but failed
4. enable debug mode

SUHOSIN Installed: –
MySQL Version: 5.7.39-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by AngelEscobedoWH** [comment]
I had the same issue. I wasn't developing it at the time and all of a sudden my website came down.
I wouldn't recommend it as a permanent fix, but I temporarily commented out 

	array_walk(
		$data,
		function ( &$value ) {
			// $value = remove_accents( html_entity_decode( $value ) );
		}
	);


located at `/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1824` line
and my website came back up.

**Comment by rizvee** [comment]
> I had the same issue. I wasn't developing it at the time and all of a sudden my website came down. I wouldn't recommend it as a permanent fix, but I temporarily commented out
> 
> ```
> array_walk(
> 	$data,
> 	function ( &$value ) {
> 		// $value = remove_accents( html_entity_decode( $value ) );
> 	}
> );
> ```
> 
> located at `/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1824` line and my website came back up.

that brings out this>>>>

Fatal error: Uncaught TypeError: array_walk(): Argument #1 ($array) must be of type array, null given in /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1828 Stack trace: #0 /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1828): array_walk() #1 /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(447): include_once('/home/konezovd/...') #2 /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(176): WooCommerce->includes() #3 /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(135): WooCommerce->__construct() #4 /home/konezovd/public_html/wp-content/plugins/woocommerce/woocommerce.php(47): WooCommerce::instance() #5 /home/konezovd/public_html/wp-content/plugins/woocommerce/woocommerce.php(62): WC() #6 /home/konezovd/public_html/wp-settings.php(447): include_once('/home/konezovd/...') #7 /home/konezovd/public_html/wp-config.php(99): require_once('/home/konezovd/...') #8 /home/konezovd/public_html/wp-load.php(50): require_once('/home/konezovd/...') #9 /home/konezovd/public_html/wp-admin/admin.php(34): require_once('/home/konezovd/...') #10 {main} thrown in /home/konezovd/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1828

**Comment by Mxchael** [comment]
Also seen in 5679438-zen

**Comment by AashikP** [comment]
Another possible report in 5672620-zen

**Comment by peterfabian** [comment]
This seems to be related to the new code added in WP 6.1: https://github.com/WordPress/wordpress-develop/commit/1d5d9e24c4cdb09d22d9819c6573a0d2d677f2b2#diff-e2bc0d3d983191acdb2effe67311dc37666eae53d59983281b34a7b4eed238acR1605-R1606

We're investigating further.

**Comment by peterfabian** [comment]
The current working theory is that:
- WP 6.1 added the usage of `Normalizer` class in `remove_accents` function
- Woo just calls standard WP function `remove_accents` as it did before, no change there
- Most likely some PHP installations are missing `intl` extension, so they should add it: https://stackoverflow.com/questions/8597146/class-normalizer-not-found-in-php-5-3-8?noredirect=1&lq=1
- Otherwise they might face other problems. E.g. WP function `sanitize_user` calls `remove_accents` as well, so if they try to create a new user with a username that includes some accents, it should give the same fatal error even with WooCommerce disabled (if this theory is correct)

Edit: Confirmed that creating of a new user with accents in their username (e.g. "čačaný") should trigger the same code path and same error:

![Screenshot 2022-11-03 at 10 24 12](https://user-images.githubusercontent.com/2207451/199686084-ae24d92a-8195-4dbf-b819-0d3c766135d0.png)

(If you have PHP intl installed, it will complain about unsupported characters in the username instead)

Based on this I'd recommend:
- immediate fix: downgrade to WP 6.0
- long term solution: install [intl extension for PHP](https://www.php.net/manual/en/book.intl.php), then upgrade to WP 6.1

I'll keep this issue open for a couple more days in case there's more feedback, but it doesn't seem like we can do much about it, so if the above is correct, we will close the issue.

**Comment by Zodiac1978** [comment]
Hi @rizvee 

can you please check why the function exist check is returning `true` in your environment?

And is `function_exists( 'normalizer_is_normalized' )` also `true`?

Can you double-check if the `intl` extension is loaded or not?

**Comment by Jasperste** [comment]
Adding the `intl` extension did the trick here. Thanks!

**Comment by Zodiac1978** [comment]
Technical explanation and fix here: https://core.trac.wordpress.org/ticket/56980

**Comment by lynnjat7** [comment]
36121749-hc

**Comment by jchambo** [comment]
So is the "solution" here for WordPress instances running on Ubuntu Server, or say VPS's using OpenLiteSpeed WordPress installs to run these in order?

```
sudo apt-get update
sudo apt install php-intl
sudo reboot
```

Then we can go ahead and update all plugins & update to WordPress 6.1?

**Comment by Zodiac1978** [comment]
Yes, this should solve the problem, as then the `intl` extension is providing the function directly and no polyfill is necessary. Especially, the namespace problem (and therefore the fatal error) is gone then.

See also: 
https://make.wordpress.org/hosting/2021/05/20/why-hosters-should-install-the-php-intl-extension/

**Comment by rizvee** [comment]
problem resolved. thanks all of you.

**Comment by Zodiac1978** [comment]
Hey @rizvee 

Thank you for providing such a complete bug report. It was very helpful to have all the necessary data at hand. It wouldn't be solved so fast without this. 👍
