### ISSUE TITLE
Tracks: add new event to "View product" action

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35494]
**Description:** we'd like to add new Tracks events to understand how many users click to view a product through the wp-admin notification we display after publishing/updating it.

<img width="1267" alt="Captura de ecrã 2022-11-04, às 10 08 12" src="https://user-images.githubusercontent.com/3380168/199949174-20c86dd2-b8f2-43ee-a6fa-b9d43699f04c.png">

**Acceptance criteria:**
- [ ] Trigger a new event called `wcadmin_product_view_product_click`when the user clicks on "View product" in the wp-admin notification. This notification is displayed after a product is published or updated. This new event should include the same props as `wcadmin_product_update`
- [ ] Trigger a new event called `wcadmin_product_view_product_dismiss`when the user clicks to dismiss the "View product" wp-admin notification. This notification is displayed after a product is published or updated. This new event should include the same props as `wcadmin_product_update`

**Comment by pmcpinto** [comment]
@AnnaMag is it possible to have this implemented by the Porter? I'd like to include this in WC 7.2 (code freeze Nov 17). Thanks

**Comment by AnnaMag** [comment]
Assigning @mattsherman as he is the porter in the week following the meetup. 
but! @nathanss, this could be a good issue to grab in week 3, depending on where you are at in your dev set-up process at the beginning of it. Let's check in on the 14th.

**Comment by mattsherman** [comment]
@nathanss Put this "In Progress" and in "Cycle 30" since you have been working on it (https://github.com/woocommerce/woocommerce/pull/35582 -- you should add that to the board as well).
