### ISSUE TITLE
[Enhancement]: Add guidance when configuring tax settings to avoid situations that result in apparent "rounding errors"

### ISSUE THREAD

**Issue by beaulebens** [woothemes/woocommerce#35497]
### Describe the solution you'd like

When configuring how taxes will be handled, there is an opportunity to inform the merchant that if they configure things a certain way, they are likely to see rounding errors in their cart/checkout. Ideally we would just never have these "rounding errors", although it seems like perhaps that's not possible. Failing that, we should try to educate merchants about their options and implications a bit better.

We have documentation around [how to configure taxes](https://woocommerce.com/document/setting-up-taxes-in-woocommerce/), where we include a warning:

> If these settings are not consistent, then for a certain combination of product prices and tax rates, customers may see an off-by-one rounding error. This happens when the calculated price (whether including taxes or not), has more decimal precision than allowed to be displayed by the shop, and as a result, prices are rounded.

I think we should find a way to surface either this message (or similar), or a link to the documentation based on the settings selected on the `WooCommerce > Settings > Tax` screen. There might also be a better solution (making it harder to configure things in conflict? Restructuring/reordering settings on this page to make relationships clear), but this seems like a lightweight improvement.

<img width="727" alt="Screen Shot 2022-11-04 at 9 09 44 AM" src="https://user-images.githubusercontent.com/108942/200009150-6fadd442-0cee-4fdf-9e5b-74c30614df1a.png">

Related: #34529

**Comment by pmcpinto** [comment]
@SamratBiswas1 @adrianduffell @verofasulo I think the best option is to provide contextual guidance using our spotlight tour. We could display the spotlight the first time the user visits the screen and selects a combination that can trigger the rounding error.

The WC 7.2 code freeze happens the week after the meetup where we have some folks afk. Therefore, I think it's better to target 7.3, to ensure we have a solid solution and have time to test all the potential use cases.

**Comment by SamratBiswas1** [comment]
Agree. 

@adrianduffell - Let's target it for 7.3 as Pedro suggested.

**Comment by adrianduffell** [comment]
> We could display the spotlight the first time the user visits the screen and selects a combination that can trigger the rounding error.

How about displaying an error message when the settings are in conflict?

<img width="887" alt="Screen Shot 2022-11-17 at 11 28 37 am" src="https://user-images.githubusercontent.com/9312929/202347883-68cf584e-ccb1-436b-b4ad-7ea722f70854.png">

My concern with using a spotlight tour is the design language of it doesn't really have any signposts about how critical the information is. There are no red highlights for example. I think its probable users would skip through the tour without paying attention to the info. 

Alternatively, maybe there could be a mixed approach of using the spotlight tour on the first visit to introduce the tax settings as a whole, plus an error message when the user tries to save a conflicting combo of settings?

@verofasulo what do you think?

**Comment by verofasulo** [comment]
@adrianduffell Totally agree with you!

The spotlight tour is more about giving the user additional context and making them familiar with the content and the layout of a specific section/screen. Besides, we risk overwhelming the users with information that is not needed till the error happens. I would recommend following Adrian's suggestion and surfacing the error using an error message. One thing I'd like to add is to provide the user with a clear action to fix the error. It's actually not clear to me what is the disruptive combination, but maybe we can have a button that allows the user to go back to the safe recommended settings or explain a bit more about how to fix the problem.

**Comment by adrianduffell** [comment]
Thanks @verofasulo, I think the "fix" button could work quite well.

Here's a few mockups. How do you think we should label the button? I also added a link to learn more about the problem (linking to: https://woocommerce.com/document/setting-up-taxes-in-woocommerce/)



![Image](https://user-images.githubusercontent.com/9312929/202653648-3f578eb8-68de-47f2-8a35-a3991097e7aa.png)

![Image](https://user-images.githubusercontent.com/9312929/202653662-12d7f27e-6e08-4107-80db-0304ab00bc9f.png)

**Comment by adrianduffell** [comment]
@beaulebens Can you confirm the settings conflict when the following fields are different?

* Prices entered with tax
* Display prices in the shop
* Display prices during cart and checkout

In other words, would the safe recommended settings be that the "Display prices" fields should match the same inclusive/exclusive value selected for "Prices entered with tax" field ?

**Comment by adrianduffell** [comment]
To summarize so far:

* A error message should be added when the tax settings are in conflict. This probably needs to appear after save (i.e. saving shouldn't be prevented) as merchants may have valid use cases we don't yet know about.
* The combination of fields that cause the conflict need to be confirmed. See comment above: https://github.com/woocommerce/woocommerce/issues/35497#issuecomment-1319689939
* The error message should contain a button to restore the settings to safe values: 
![](https://user-images.githubusercontent.com/9312929/202653648-3f578eb8-68de-47f2-8a35-a3991097e7aa.png)

**Comment by verofasulo** [comment]
> This probably needs to appear after save

@adrianduffell are we able to display the message right after the user entered conflicted details? I think it would be better to provide immediate feedback, but not sure if it's feasible from a tech point of view.

If yes, I was thinking to implement something like this right below the input field:

![image](https://user-images.githubusercontent.com/98944206/203055477-424bdb04-eeee-4f56-bb1d-c61dc51ffa03.png)

Otherwise, an alert message like this after saving:

![image](https://user-images.githubusercontent.com/98944206/203055596-25cc3811-de12-42b0-a480-43ba1ee2a924.png)

If we go with this proposal, please automatically scroll up the page to the alert message as the save button is placed at the very end and the user might miss the message. 

In both scenarios, please add a close button and revert the cta order (primary cta before the secondary).

> The error message should contain a button to restore the settings to safe values

I think "Fix" is not vocal enough - I actually prefer "Use recommended settings". What do you think?

**Comment by adrianduffell** [comment]
> are we able to display the message right after the user entered conflicted details? I think it would be better to provide immediate feedback, but not sure if it's feasible from a tech point of view.

Love this design having the error message inline with the fields! 

Yes from a tech point of view it's feasible to have immediate feedback rather than waiting for save.

**Comment by adrianduffell** [comment]
> I think "Fix" is not vocal enough - I actually prefer "Use recommended settings". What do you think?

Yeah agree, this looks great to me 👍

**Comment by verofasulo** [comment]
> Yes from a tech point of view it's feasible to have immediate feedback rather than waiting for save.

Awesome! 🙌 Thanks, Adrian

**Comment by beaulebens** [comment]
> @beaulebens Can you confirm the settings conflict when the following fields are different?
> 
> * Prices entered with tax
> * Display prices in the shop
> * Display prices during cart and checkout
> 
> In other words, would the safe recommended settings be that the "Display prices" fields should match the same inclusive/exclusive value selected for "Prices entered with tax" field ?

That is my understanding, yes ( @peterfabian / @vedanshujain can you please confirm?).

I like the positioning of the warning right under the field, although it begs the question -- which field to display it under? I guess we can treat the "Prices entered with tax" field as the "main" one, and then the other two as being either aligned with, or potentially in conflict with that one?

In this specific context, I think we probably need a better/more descriptive warning as well, vs the one I referenced from the documentation. Since there are other settings also on this page, we need to make sure that the message clearly identifies which ones need to be changed together. Something like;

> **Inconsistent tax settings**: To avoid possible rounding errors, prices should be entered and displayed consistently in all locations either including, or excluding taxes.

If we assume the "Prices entered with tax" field is the "main" one, then I assume clicking the button would change the other two fields to match it?

**Comment by verofasulo** [comment]
> In this specific context, I think we probably need a better/more descriptive warning as well, vs the one I referenced from the documentation.

@beaulebens I agree. And the copy you suggested looks great to me! 🙌

> If we assume the "Prices entered with tax" field is the "main" one, then I assume clicking the button would change the other two fields to match it?

Yes, exactly. And the alert should appear once the user changes options in "Display prices in the shop" and "Display prices during cart and checkout" if they are in conflict with the selection made in "Prices entered with tax".

**Comment by vedanshujain** [comment]
> That is my understanding, yes ( @peterfabian / @vedanshujain can you please confirm?).

Yeah this is correct.

We can probably rearrange these settings a bit so that they are together (it seems like another comment also refers to it by calling the prices entered setting as "main").

**Comment by beaulebens** [comment]
> We can probably rearrange these settings a bit so that they are together (it seems like another comment also refers to it by calling the prices entered setting as "main").

I was thinking this as well, but then when I looked at how we'd actually do it, it started feeling like an even bigger change (e.g. it probably makes sense to hide/move some things, based on what you select/how you say you'll enter prices). I think that warrants a separate look from Design, but in the meantime we can probably get a simpler warning message shipped to reduce confusion.

**Comment by adrianduffell** [comment]
@verofasulo With the close button (X) on the error message, do you have in mind that users would be able to dismiss the error and proceed with the unsafe settings? 

<img width="390" alt="Screen Shot 2022-11-29 at 2 51 19 pm" src="https://user-images.githubusercontent.com/9312929/204459133-d4630584-5131-49a9-8a90-e470a956650f.png">

Potentially, we could disable the save button when the error message is present and re-enable it once the error is fixed. If the error is dismissed however, the save button could also be re-enabled.

This is what the button looks like when disabled:

<img width="666" alt="Screen Shot 2022-11-29 at 3 04 30 pm" src="https://user-images.githubusercontent.com/9312929/204461463-0b633e94-d43a-4ac3-a579-1dd49dd25a1d.png">

**Comment by verofasulo** [comment]
>With the close button (X) on the error message, do you have in mind that users would be able to dismiss the error and proceed with the unsafe settings?

@adrianduffell yes - my understanding was that there might be some use cases where these settings are ok anyway (I have no idea which special use case might be, but I guess there is 🤔). That's why I would avoid disabling the "Save" button as well.

**Comment by verofasulo** [comment]
>it started feeling like an even bigger change (e.g. it probably makes sense to hide/move some things, based on what you select/how you say you'll enter prices). I think that warrants a separate look from Design, but in the meantime we can probably get a simpler warning message shipped to reduce confusion.

I agree @beaulebens. The Manage team is thinking of reviewing the Settings area next year, so it would be a good moment for us to redesign the experience 😊 cc @pmcpinto

**Comment by adrianduffell** [comment]
> That's why I would avoid disabling the "Save" button as well.

Sounds good!

One more question. if the close button is used, should that permanently dismiss the error message appearing again?

> I have no idea which special use case might be, but I guess there is 🤔

I was thinking about adding a Tracks event when the message dismissed. Perhaps then we could reach out to a sample of these merchants and find out their use case 🤔

**Comment by verofasulo** [comment]
> if the close button is used, should that permanently dismiss the error message appearing again?

Great question - I see this task as a one-time action, so I don't expect users to go back and change these settings. But to answer your question, I would probably show the alert again even if it was dismissed - at least till we don't get data and have a clearer picture of this scenario. 

> I was thinking about adding a Tracks event when the message dismissed. Perhaps then we could reach out to a sample of these merchants and find out their use case 

Yes 🙌 Could we also track the other actions (main cta and secondary link to documentation)?

**Comment by asdfMaciej** [comment]
I consider the message "off-by-one rounding error" as dismissive, as the off by one error becomes a large accounting error, when dealing with large quantities of low valued products. Please consider introducing an option to round the price in a similar manner to [my patch solution](https://github.com/woocommerce/woocommerce/issues/34529#issuecomment-1334024739). In the meanwhile it would be worth it to properly inform the user about the scale of the issue.

**Comment by pmcpinto** [comment]
@adrianduffell how is this implementation going? I missed that call where you shared the demo and the video recording is not working-

**Comment by adrianduffell** [comment]
@pmcpinto It's going well and on track for the 7.3 release. In the design call we identified adding a Snackbar notification  after the safe settings are applied. I'll have another demo ready early next week.

**Comment by adrianduffell** [comment]
> Could we also track the other actions (main cta and secondary link to documentation)?

@verofasulo Yes, I'll add that in!

**Comment by adrianduffell** [comment]
> I consider the message "off-by-one rounding error" as dismissive, as the off by one error becomes a large accounting error, when dealing with large quantities of low valued products.

@asdfMaciej Thanks for raising this. Is it more like an "off-by-10" / "off-by-100" etc error when these amounts of quantities are ordered?

@beaulebens @verofasulo Do you think we should tweak the message on this a bit?

**Comment by beaulebens** [comment]
@adrianduffell if you switch to something like the message I suggested [here](https://github.com/woocommerce/woocommerce/issues/35497#issuecomment-1322237904), then I think it avoids the problem @asdfMaciej is referring to.

> Inconsistent tax settings: To avoid possible rounding errors, prices should be entered and displayed consistently in all locations either including, or excluding taxes.

**Comment by adrianduffell** [comment]
@pmcpinto We're still on track to have this for the 7.3 release, but aiming for the demo mid-week now

**Comment by adrianduffell** [comment]
Here's the demo!

https://user-images.githubusercontent.com/9312929/207861757-8946de23-e25c-424b-a5b0-24d75d27a595.mov
