### ISSUE TITLE
[Enhancement]: Make advanced searches possible inside WooCommerce product section

### ISSUE THREAD

**Issue by mastix01** [woothemes/woocommerce#35503]
### Describe the solution you'd like

Please make advanced searches possible inside WooCommerce product section. The search box never finds anything but the most basic title field etc. We need powerful searches like the one present in many plugins in the front end. Metadata like IPTC, Product Tags taxonomies etc. Right now to find anything when you have hundreds or thousands of products is a mess. Not everybody has the important information in the title or description. Shirts maybe . I for example sell images and need to search by tags.

If there are amazing plugins that can search for anything in the front end like advanced woo search I think something similar in the backend should be also important to have to locate products quickly

### Describe alternatives you've considered

I would love that advanced woo search would take over the default product search option of WooCommerce This is not possible but would be a way to solve the issue until the day WooCommerce takes search seriously

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

About the enhancement of admin search, we'd like to let you know that we acknowledge its potential for significant improvement. However, at this moment, it doesn't align with our near-term priorities. We'll close this issue temporarily and revisit it as soon as we focus on this particular problem space. Please don't worry if you don't observe any recent activity on this issue; it's still on our radar for future consideration.

**Comment by mastix01** [comment]
No worries I have moved on from woocommerce to a much more user friendly and easier solution for my shop.I prefer to pay a little more for peace of better support and easier shop handling.In any case thank you for your feedbackKind regardsCristian BaitgCristian ***@***.*** 2 oct 2023, a las 16:30, Pedro Pinto ***@***.***> escribió:﻿
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.
About the enhancement of admin search, we'd like to let you know that we acknowledge its potential for significant improvement. However, at this moment, it doesn't align with our near-term priorities. We'll close this issue temporarily and revisit it as soon as we focus on this particular problem space. Please don't worry if you don't observe any recent activity on this issue; it's still on our radar for future consideration.

**Comment by pmcpinto** [comment]
Hey @mastix01 thanks for your feedback. Can you indicate which solution you chose to replace Woo?

**Comment by mastix01** [comment]
Hello Pedro:After fighting 3 months eith Woocommerce I gave up and I open an account in Etsy Very easy to list products and also support is always there.With Woocommerce support was a nightmare , always looking youtube videos and scouting on forums , with the plugins the sameNow that I have established my presence I will open up my shop to direct selling with no intermediaries with ShopifyI inow it will be more expensive but I don't care. My time and less stress is much more valuable than the little more money of Shopify or the small comissions Etsy is taking now.Kind regardsCristianCristian ***@***.*** 2 oct 2023, a las 18:19, Pedro Pinto ***@***.***> escribió:﻿
Hey @mastix01 thanks for your feedback. Can you indicate which solution you chose to replace Woo?

**Comment by pmcpinto** [comment]
Hey @mastix01 thanks for your feedback. We appreciate it.
