### ISSUE TITLE
woocommerce-{locale}-wc-admin-app.json not being generated because of incorrect file format.

### ISSUE THREAD

**Issue by kenarsuleyman** [woothemes/woocommerce#35500]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

To generate wc-admin-app.json language file, code reads precompiled language JSON files in translations directory with the following format, woocommerce-{locale}-{MD5}.json, and then merges all the strings in to one single woocommerce-{locale}-wc-admin-app.json file.
Problem here is, code is looking for different format than what wp-cli or loco translate generates.

This is an example file downloaded automatically if selected locale has official translations.
`{
  "translation-revision-date": "2022-11-01 19:37:59+0000",
  "generator": "GlotPress/4.0.0-alpha.3",
  "domain": "messages",
  "locale_data": {
    "messages": {
      "": {
        "domain": "messages",
        "plural-forms": "nplurals=2; plural=n > 1;",
        "lang": "tr"
      },
      "Edit selected product": [
        "Seçili ürünü düzenle"
      ]
    }
  },
  "comment": {
    "reference": "packages/woocommerce-blocks/assets/js/blocks/single-product/edit/editor-block-controls.js"
  }
}`

And this is the same file generated by wp-cli make-json command.

`{
    "translation-revision-date": "2022-11-02 17:33+0300",
    "generator": "WP-CLI\/2.7.1",
    "source": "packages\/woocommerce-blocks\/assets\/js\/blocks\/single-product\/edit\/editor-block-controls.js",
    "domain": "messages",
    "locale_data": {
        "messages": {
            "": {
                "domain": "messages",
                "lang": "az",
                "plural-forms": "nplurals=2; plural=n > 1;"
            },
            "Edit selected product": [
                "Se\u00e7ili \u00fcr\u00fcn\u00fc d\u00fczenle"
            ]
        }
    }
}`

[https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/src/Internal/Admin/Translations.php#L96](https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/src/Internal/Admin/Translations.php#L96)

As you can see while the official file has the format ["comment"]["reference"] for associated file, wp-cli generates files with ["source"] format. Because of that woocommerce fails to generate woocommerce-{locale}-wc-admin-app.json file.

### Expected behavior

After saving a translation with Loco Translate or uploading compiled files from POEdit, woocommerce should generate woocommerce-{locale}-wc-admin-app.json file for that locale.

### Actual behavior

Due to mismatch in formats, Woocommerce is unable to generate that file, resulting most of admin dashboard is not being translated.

### Steps to reproduce

1- Generate a .po file from woocommerce.pot file using POEdit or Loco Translate
2- Save&compile new language.
3- Woocommerce analytics dashboard and many other places won't be translated because woocommerce-{locale}-wc-admin-app.json is not generated.

### WordPress Environment

`
### wp-core ###

version: 6.1
site_language: en_US
user_language: en_US
timezone: Africa/Abidjan
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\laragon\www\azeri
wordpress_size: 65.04 MB (68199323 bytes)
uploads_path: C:\laragon\www\azeri/wp-content/uploads
uploads_size: 291.02 KB (298009 bytes)
themes_path: C:\laragon\www\azeri/wp-content/themes
themes_size: 6.34 MB (6644043 bytes)
plugins_path: C:\laragon\www\azeri/wp-content/plugins
plugins_size: 30.41 MB (31886329 bytes)
database_size: 5.30 MB (5554176 bytes)
total_size: 107.37 MB (112581880 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.3
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: C:\laragon\www\azeri/wp-content/themes/twentytwentytwo
auto_update: Disabled

### wp-plugins-active (2) ###

Loco Translate: version: 2.6.3, author: Tim Whitlock, Auto-updates disabled
WooCommerce: version: 7.0.1, author: Automattic, Auto-updates disabled

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 5.0.1, author: Automattic, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 2G
upload_max_filesize: 2G
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.1.10
php_version: 8.1.10 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 2G
php_post_max_size: 2G
curl_version: 7.77.0 OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.30
client_version: mysqlnd 8.1.10
max_allowed_packet: 536870912
max_connections: 151

### wp-constants ###

WP_HOME: http://azeri.test
WP_SITEURL: http://azeri.test
WP_CONTENT_DIR: C:\laragon\www\azeri/wp-content
WP_PLUGIN_DIR: C:\laragon\www\azeri/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kenarsuleyman** [comment]
@samueljseay Hello sir, any update on reproducing the issue?

**Comment by samueljseay** [comment]
Hi @kenarsuleyman I have just labelled this for developer reproduction, one of our devs will have to work through a reproduction for this. There are a lot of new issues coming in regularly that need reproduction so you might have to wait sorry.
