### ISSUE TITLE
WP_Insert_Post NOT WORKING AS BEFORE

### ISSUE THREAD

**Issue by mikeisadev** [woothemes/woocommerce#35514]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

before updating WooCommerce to 7.0.1 I could insert PRODUCTS programmatically via `wp_insert_post()` function or through an instance of the class of the product I wanted to add (for example `$product = new WC_Product_Subscription()`.

I could set price, title, description, monthly price for subscriptions and a LOT more data.

Wih WooCommerce 7.0.1 I can still do this BUT I have a problem.

I can add products (and other post types) with WP_INSER_POST(). But the product do not shows price and category on front end and on product listing inside the admin area of WordPress.

But if I go to admin panel and I try to edit that product, the exact price is inside the field. Strangely it doesn't appear on front end (product page) and on the column of products listing inside the admin panel.

The moment I click the button "Update" the product price is shown on frontend (product page) and it appears on the column of product listing of woocommerce.

Before I didn't have to do this.

I tried to look for the dabase behavior inside wp_postmeta and yes: When I try to use WP_INSERT_POST only some data will be imported. But when I click UPDATE on the admin panel much more data appears for that post id (product).

Before this wasn't necessary at all! The product was created entirely even if you didn't fill up all the fields.

Now this problem happens, even If I set up price it only appears in the relative text box inside the admin panel but it seems that I cannot buy the product and the price is not shown.

I'm working on localhost.

I have several plugins and I have oceanwp theme as main theme and I've created my child theme with custom functions.

What I tried is to deactivate my custom core of functions (child theme) and I tried to deactivate all plugins.

But nothing. I have the same problem.

### Expected behavior

WP_INSERT_POST with arguments set as I want to add the product (view the code in the message) should add the product entirely.

All the fields should be at their place and if I didn't inserted them they should be have default values. Even the price must be visible and set up pubicly.

### Actual behavior

When I add a product with WP_INSERT_POST in the database some information are missing. When I click update in the admin panel for that product the remaining data appears.

### Steps to reproduce

This is the code. Is an example I used to perform some actions (like add a product subscription when a new user is registered to the platform).

In this case I wrote this example (on the submit of the form created a new product).

On submit the product is created but the product price (and even the category -> should be on empty, and this is another problem) are not shown. But if try to click update on the admin panel the product will show price, category and more.

Before that wasn't necessary at all!

```
<?php 

if ( isset( $_POST['invite'] ) ) {

    $product_id = wp_insert_post(
        array(
            'post_author' => get_current_user_id(),
            'post_status' => 'publish',
            'post_type'   => 'product',
            'post_title'  => 'Subscription to: ' . get_current_user_id(),
            'post_content'=> 'Test content',
        )
    );

    wp_set_object_terms( $product_id, 'subscription', 'product_type' );

    $product = wc_get_product( $product_id );

    update_post_meta( $product_id, '_subscription_price', '2.99' );
    update_post_meta( $product_id, '_subscription_period', 'month' );
    update_post_meta( $product_id, '_subscription_interval', '1' );
    update_post_meta( $product_id, '_visibility', 'visible' );

    $product->save();

}

?>

<form method="POST">
    <input type="submit" name="invite" value="Invita!" readonly>
</form>
```

### WordPress Environment

LocalHost
WooCommerce 7.0.1
WordPress 6.1

I've tried with all plugins deactivated and more.
After a lot of tests the problem persists.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by floyedxman** [comment]
how can I modify the payment gate ?

**Comment by barryhughes** [comment]
We always recommend using our CRUD layer to create entities like products (or indeed orders), instead of using WordPress functions directly. Additionally, it's not clear that this is a problem with WooCommerce Core (your example seems to relate specifically to subscriptions, which are not something we handle in this issue tracker).

For those reasons, I'm inclined to close the issue—but if you feel strongly that it should remain open, please let us know.
