### ISSUE TITLE
calendar began to fail.

### ISSUE THREAD

**Issue by pilinqn** [woothemes/woocommerce#35515]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The calendar began to fail.

When you click on one of the products, a window opens with the details of the reservation, after the last update that window does not open.

when you want to select the day, it disappears leaving only the option to advance day by day.

### Expected behavior

the detail of the reservation must be seen complete as it always worked.

### Actual behavior

the window looks compressed, it does not let you see the detail. The date when clicked is erased.

### Steps to reproduce

![1](https://user-images.githubusercontent.com/117698689/200457985-b5acbe0d-6cec-4d73-85ad-da7a6f3151da.jpg)
![2](https://user-images.githubusercontent.com/117698689/200457992-82c920a1-1ab7-419b-8779-a39f0bf84122.jpg)
![3](https://user-images.githubusercontent.com/117698689/200457994-eb8bbd78-506a-4cb8-8c24-86df1026b1fa.jpg)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://planetjump.com.ar
Site address (URL): https://planetjump.com.ar
WC Version: 7.0.1
REST API Version: ✔ 7.0.1
WC Blocks Version: ✔ 8.5.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.25
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.6.50-log
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 201.40MB
Tamaño de los datos de la base de datos: 147.85MB
Tamaño del índice de la base de datos: 53.55MB
wp_woocommerce_sessions: Datos: 1.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 2.06MB + Índice: 0.16MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 5.31MB + Índice: 6.27MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_appointments: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_cancelled_appointments: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_coupons: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_days_on_off: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_email_templates: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_gg_calendars: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_locked_time_slots: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_services: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wbk_service_categories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 5.02MB + Índice: 4.69MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 2.02MB + Índice: 1.47MB + Motor InnoDB
wp_bookacti_activities: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_bookings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_booking_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_event_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_exceptions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_exports: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_form_fields: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_groups_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_group_categories: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_permissions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookacti_templates_activities: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_booking: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bookingdates: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cartflows_ca_cart_abandonment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cartflows_ca_email_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_commentmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_comments: Datos: 4.44MB + Índice: 2.30MB + Motor MyISAM
wp_ea_error_logs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_e_submissions: Datos: 0.02MB + Índice: 0.27MB + Motor InnoDB
wp_e_submissions_actions_log: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_e_submissions_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_icl_strings: Datos: 0.15MB + Índice: 0.11MB + Motor MyISAM
wp_icl_string_translations: Datos: 0.23MB + Índice: 0.08MB + Motor MyISAM
wp_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_nm_personalized: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 4.32MB + Índice: 0.18MB + Motor MyISAM
wp_postmeta: Datos: 37.39MB + Índice: 17.73MB + Motor MyISAM
wp_posts: Datos: 7.75MB + Índice: 2.40MB + Motor MyISAM
wp_revslider_css: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_css_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_layer_animations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_navigations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_sliders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_sliders_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_slides: Datos: 0.16MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_static_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_sbi_feeds: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_sbi_feed_caches: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_sbi_instagram_feeds_posts: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_sbi_instagram_feed_locator: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_sbi_instagram_posts: Datos: 0.22MB + Índice: 0.00MB + Motor InnoDB
wp_sbi_sources: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_term_relationships: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_term_taxonomy: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_usermeta: Datos: 22.99MB + Índice: 1.98MB + Motor MyISAM
wp_users: Datos: 0.18MB + Índice: 0.13MB + Motor MyISAM
wp_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_bookings_availability: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_bookings_availabilitymeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_booking_relationships: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 1.25MB + Índice: 0.33MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 1.09MB + Índice: 0.69MB + Motor InnoDB
wp_wc_order_stats: Datos: 1.06MB + Índice: 0.31MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wdi_feeds: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wdi_themes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpforms_entries: Datos: 35.56MB + Índice: 0.36MB + Motor InnoDB
wp_wpforms_entry_fields: Datos: 13.52MB + Índice: 12.48MB + Motor InnoDB
wp_wpforms_entry_meta: Datos: 0.11MB + Índice: 0.22MB + Motor InnoDB
wp_wpforms_logs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpf_drop_uploader: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_debug_events: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

acf-field-group: 1
attachment: 265
custom_css: 1
elementor_library: 27
jet-popup: 1
nav_menu_item: 11
page: 23
post: 2
product: 3
revision: 927
shop_order: 3048
shop_order_refund: 6
wc_booking: 9093
wpforms: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Custom Fields PRO: por Cerebros deliciosos – 5.12.3
All-in-One WP Migration: por ServMask – 7.67
Contact Form 7: por Takayuki Miyoshi – 5.6.4
Customizer Export/Import: por The Beaver Builder Team – 0.9.5
Disable XML-RPC: por Philip Erb – 1.0.1
Elementor Pro: por Elementor.com – 3.7.3
Elementor: por Elementor.com – 3.8.0
Facebook Chat Plugin - Live Chat Plugin for WordPress: por Meta – 2.5
Smash Balloon Instagram Feed: por Smash Balloon – 6.1
JetElements For Elementor: por Crocoblock – 2.6.7
JetPopup: por Crocoblock – 1.6.0
JetTabs For Elementor: por Crocoblock – 2.1.19
WPBakery Page Builder: por Michael M - WPBakery.com – 6.10.0
Jupiter X Core: por Artbees – 2.5.2
Loco Translate: por Tim Whitlock – 2.6.3
TimThumb Vulnerability Scanner: por Peter Butler – 1.54
Under Construction: por WebFactory Ltd – 3.93
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.8.0
WooCommerce Bookings: por WooCommerce – 1.15.65
WooCommerce Email Customizer: por cxThemes – 3.33
Mercado Pago payments for WooCommerce: por Mercado Pago – 6.3.1
WooCommerce: por Automattic – 7.0.1
WP Change Default Email: por Vijay Sharma – 0.4
WP Mail SMTP: por WPForms – 3.6.1
WP Rollback: por GiveWP.com – 1.7.2
WP Super Cache: por Automattic – 1.9.1
WPForms AJAX Submit: por John A. Huebner II – 1.2.4
WPForms Signatures: por WPForms – 1.3.0
WPForms: por WPForms – 1.7.5.4

### Inactive Plugins (2) ###

Lock User Account: por teknigar – 1.0.4
WPForms Stripe: por WPForms – 2.3.1ß

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ARS ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la tienda: #13950 - /tienda/
Carrito: ❌ La página no contiene el shortcode [woocommerce_cart] o el bloque woocommerce/cart.
Finalizar compra: ❌ La página no contiene el shortcode [woocommerce_checkout] o el bloque woocommerce/checkout.
Mi cuenta: ❌ La página no contiene el shortcode [woocommerce_my_account].
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: JupiterX
Version: 2.5.1
Author URL: https://artbees.net/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: La  version 4.4.0 de jupiterx/lib/templates/woocommerce/cart/cart.php está obsoleta. La versión del núcleo es la 7.0.1
jupiterx/lib/templates/woocommerce/checkout/thankyou.php
jupiterx/lib/templates/woocommerce/content-product.php
La  version 3.7.0 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-cancelled-order.php está obsoleta. La versión del núcleo es la 4.1.0
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-failed-order.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-new-order.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-completed-order.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-invoice.php
La  version 3.7.0 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-new-account.php está obsoleta. La versión del núcleo es la 6.0.0
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-note.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-on-hold-order.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-processing-order.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-refunded-order.php
La  version 3.7.0 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-reset-password.php está obsoleta. La versión del núcleo es la 4.0.0
La  version 3.5.4 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-addresses.php está obsoleta. La versión del núcleo es la 5.6.0
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-customer-details.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-downloads.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-footer.php
La  version 2.4.0 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-header.php está obsoleta. La versión del núcleo es la 4.0.0
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-details.php
/home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-items.php
La  version 3.3.0 de /home/c1760524/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-styles.php está obsoleta. La versión del núcleo es la 4.0.0
jupiterx/lib/templates/woocommerce/loop/rating.php
jupiterx/lib/templates/woocommerce/order/order-details-item.php
La  version 4.8.0 de jupiterx/lib/templates/woocommerce/single-product/add-to-cart/grouped.php está obsoleta. La versión del núcleo es la 7.0.1
La  version 3.4.0 de jupiterx/lib/templates/woocommerce/single-product/add-to-cart/simple.php está obsoleta. La versión del núcleo es la 7.0.1
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variable.php
La  version 3.4.0 de jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php está obsoleta. La versión del núcleo es la 7.0.1
jupiterx/lib/templates/woocommerce/single-product/meta.php

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-06 20:31:16 -03:00
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Completo: 6.624
Oldest: 2022-10-08 14:45:52 +0000
Newest: 2022-11-08 02:02:08 +0000

Pendiente: 10
Oldest: 2022-11-08 02:17:08 +0000
Newest: 2022-11-12 00:02:52 +0000

### Status report information ###

Generated at: 2022-11-07 23:14:16 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
Thanks for raising this, but this looks like an issue with WooCommerce Bookings plugin. If you need support for that plugin you can ask for support directly on WooCommerce.com https://woocommerce.com/my-account/create-a-ticket/
