### ISSUE TITLE
Woocommerce shipping applying delivery fees on pickup option bug

### ISSUE THREAD

**Issue by IlungaNtita** [woothemes/woocommerce#35518]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Hello everyone,

I have installed the WooCommerce Distance Rate Shipping plugin and created shipping zones and shipping methods, for shipping methods we are using distance rate options with a fixed cost per delivery of R400 and a local pickup option of no charge.

This method works as intended, on our checkout page. A customer can select eighter a pickup option or a delivery option, with a pickup option they are not charged any costs, and with the delivery option, they are charged an extra fee of R400. But the issue is that at certain times it happens that though a customer chose a pickup option they are still charged the delivery cost of R400.

Here is an example of an invoice with this issue:

Your pickup location is Clearwater Mall.

[Order #1234] (November 4, 2022)
Product

...

Subtotal:

R311.90

Shipping:

R400.00 via Sandton City (8.8 km)

Payment method:

PayFast

Total:

R711.90

Order Type: Pickup

Pickup location: Clearwater Mall

In the above invoice, a customer was charged R400 but they chose a pickup option.
How can I solve this?

Plugins:
– WooCommerce Distance Rate Shipping v1.0.28
– WooCommerce v6.7.0
– WooODT extended v1.1.2
– WooCommerce PayFast Gateway v1.4.25

WordPress v6.1

**Comment by samueljseay** [comment]
Because you're using WooCommerce Distance Rate Shipping it will be hard for us to determine if this is a WooCommerce core issue or an issue created by the plugin. You would be better off to [request support](https://woocommerce.com/my-account/create-a-ticket/) for the problem you are facing.
