### ISSUE TITLE
Woocommerce shipping applying delivery fees on pickup option bug

### ISSUE THREAD

**Issue by IlungaNtita** [woothemes/woocommerce#35519]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello everyone,

I have installed the WooCommerce Distance Rate Shipping plugin and created shipping zones and shipping methods, for shipping methods we are using distance rate options with a fixed cost per delivery of R400 and a local pickup option of no charge.

This method works as intended, on our checkout page. A customer can select eighter a pickup option or a delivery option, with a pickup option they are not charged any costs, and with the delivery option, they are charged an extra fee of R400. But the issue is that at certain times it happens that though a customer chose a pickup option they are still charged the delivery cost of R400.

Here is an example of an invoice with this issue:

Your pickup location is Clearwater Mall.

[Order https://github.com/woocommerce/woocommerce/issues/1234] (November 4, 2022)
Product

...

Subtotal:

R311.90

Shipping:

R400.00 via Sandton City (8.8 km)

Payment method:

PayFast

Total:

R711.90

Order Type: Pickup

Pickup location: Clearwater Mall

In the above invoice, a customer was charged R400 but they chose a pickup option.
How can I solve this?

Plugins:
– WooCommerce Distance Rate Shipping v1.0.28
– WooCommerce v6.7.0
– WooODT extended v1.1.2
– WooCommerce PayFast Gateway v1.4.25

WordPress v6.1

### Expected behavior

Customers should not be charged R400 on pickup type

### Actual behavior

Sometimes we receive complaints from customers who chose a pickup option but were still charged the delivery cost of R400.

### Steps to reproduce

I have installed the WooCommerce Distance Rate Shipping plugin and created shipping zones and shipping methods, for shipping methods we are using distance rate options with a fixed cost per delivery of R400 and a local pickup option of no charge.

*This issue occurs once in a while*

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.krispykremesa.com
Site address (URL): https://www.krispykremesa.com
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.32
PHP Post Max Size: 64 MB
PHP Time Limit: 7200
PHP Max Input Vars: 5000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.26-MariaDB-1:10.4.26+maria~deb10
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: sQz6d9Ymg_
Total Database Size: 412.18MB
Database Data Size: 379.12MB
Database Index Size: 33.06MB
sQz6d9Ymg_woocommerce_sessions: Data: 3.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_woocommerce_order_items: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
sQz6d9Ymg_woocommerce_order_itemmeta: Data: 2.42MB + Index: 3.00MB + Engine InnoDB
sQz6d9Ymg_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_actionscheduler_actions: Data: 1.02MB + Index: 0.78MB + Engine InnoDB
sQz6d9Ymg_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_actionscheduler_logs: Data: 1.02MB + Index: 0.50MB + Engine InnoDB
sQz6d9Ymg_addonlibrary_addons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_aioseo_cache: Data: 0.33MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_aioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_aioseo_posts: Data: 1.50MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_bv_activities_store: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_bv_fw_requests: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_bv_ip_store: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_cocart_carts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_comments: Data: 0.31MB + Index: 0.38MB + Engine InnoDB
sQz6d9Ymg_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
sQz6d9Ymg_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
sQz6d9Ymg_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
sQz6d9Ymg_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_gf_entry: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_gf_entry_meta: Data: 0.28MB + Index: 0.39MB + Engine InnoDB
sQz6d9Ymg_gf_entry_notes: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
sQz6d9Ymg_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_kk_voucher_details: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletters: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_subscribers: Data: 0.38MB + Index: 0.63MB + Engine InnoDB
sQz6d9Ymg_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_subscriber_segment: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
sQz6d9Ymg_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_menuar_elementor_cache: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_nextend2_smartslider3_slides: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
sQz6d9Ymg_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_options: Data: 22.44MB + Index: 3.42MB + Engine InnoDB
sQz6d9Ymg_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_images: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_imports: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_posts: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_postmeta: Data: 207.48MB + Index: 9.80MB + Engine InnoDB
sQz6d9Ymg_posts: Data: 69.36MB + Index: 2.16MB + Engine InnoDB
sQz6d9Ymg_search_filter_cache: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
sQz6d9Ymg_search_filter_term_results: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_term_relationships: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
sQz6d9Ymg_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_usermeta: Data: 8.47MB + Index: 5.92MB + Engine InnoDB
sQz6d9Ymg_users: Data: 0.36MB + Index: 0.30MB + Engine InnoDB
sQz6d9Ymg_vxcf_leads: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_vxcf_leads_detail: Data: 0.48MB + Index: 0.27MB + Engine InnoDB
sQz6d9Ymg_vxcf_leads_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wc_customer_lookup: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
sQz6d9Ymg_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_wc_order_product_lookup: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
sQz6d9Ymg_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sQz6d9Ymg_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_product_meta_lookup: Data: 0.17MB + Index: 0.33MB + Engine InnoDB
sQz6d9Ymg_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wfblockediplog: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_wfconfig: Data: 1.30MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wffilemods: Data: 30.58MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfhits: Data: 1.02MB + Index: 0.23MB + Engine InnoDB
sQz6d9Ymg_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wfissues: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_wfknownfilelist: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wflogins: Data: 1.02MB + Index: 0.16MB + Engine InnoDB
sQz6d9Ymg_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sQz6d9Ymg_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sQz6d9Ymg_wfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
sQz6d9Ymg_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wpforms_entries: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wpforms_entry_fields: Data: 0.30MB + Index: 0.17MB + Engine InnoDB
sQz6d9Ymg_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sQz6d9Ymg_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wpmailsmtp_debug_events: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sQz6d9Ymg_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 1338
custom_css: 2
elementor_font: 2
elementor_library: 200
mailpoet_page: 1
main_stores: 40
mini_locations: 436
nav_menu_item: 89
page: 227
post: 8
product: 114
product_variation: 95
revision: 4023
search-filter-widget: 3
shop_coupon: 14
shop_order: 607
szbdzones: 1
ultimate-woo-cart: 1
viwec_template: 14
wcpa_pt_forms: 2
wp_global_styles: 1
wpcf7_contact_form: 4
wpcode: 3
wpforms: 9
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (61) ###

Location Picker At Checkout For WooCommerce: by Uriahs Victor – 1.6.3
Gravity Forms: by Gravity Forms – 2.6.4
WooODT extended: by Mrinmoy Dalabar – 1.1.2
Elementor Addon Elements: by WPVibes – 1.11.15
Advanced Custom Fields: by Delicious Brains – 5.12.3
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.20.0
All in One SEO: by All in One SEO Team – 4.2.5.1
Better Search Replace: by Delicious Brains – 1.4.1
Boostify Header Footer Builder: by Woostify – 1.2.8
Date Time Picker for Contact Form 7 (Pro): by Ruhul Amin – 1.1.1
Classic Editor: by WordPress Contributors – 1.6.2
Contact Form 7: by Takayuki Miyoshi – 5.6.1
Contact Form Entries: by CRM Perks – 1.2.8
Country & Phone Field Contact Form 7: by Narinder Singh Bisht – 2.2.9
Custom Post Type UI: by WebDevStudios – 1.12.1
Custom Adobe Fonts (Typekit): by Brainstorm Force – 1.0.18
Date Time Picker for Contact Form 7: by Ruhul Amin – 1.1.0
Ele Custom Skin: by Dudaster.com – 3.1.6
Elementor Pro: by Elementor.com – 3.8.1
Elementor: by Elementor.com – 3.6.8
ElementsKit Lite: by Wpmet – 2.6.3
Font Awesome: by Font Awesome – 4.3.1
Gravity Forms Image Choices: by JetSloth – 1.3.55
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.10.0
Google Listings and Ads: by WooCommerce – 2.1.1
HTTP Headers: by Dimitar Ivanov – 1.18.5
Intuitive Custom Post Order: by hijiri – 3.1.3
Jetpack: by Automattic – 11.3.1
Krispy Kreme Dependancy Extender: by sinappsus.co.za – 0.0.3
MailPoet 3 (New): by MailPoet – 3.96.1
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.82
Markup by Attribute for WooCommerce: by MarkTomlinson – 3.10.5
Search & Filter - Elementor Extension: by Code Amp – 1.0.10
Search & Filter Pro: by Code Amp – 2.5.13
Search & Filter: by Code Amp – 1.2.15
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.1
Ultimate Addons for Contact Form 7: by Themefic – 3.0.6
Use Any Font: by Dnesscarkey – 6.2.95
File Uploads Addon for WooCommerce: by Imaginate Solutions – 1.5.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.7.1
WooCommerce Custom Product Addons (Free): by Acowebs – 2.6.8
Force Authentification Before Checkout for WooCommerce: by Luiz Bills – 1.4.2
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.3
WooCommerce Cart Add-Ons: by WooCommerce – 2.1.0
WooCommerce Distance Rate Shipping: by WooCommerce – 1.0.28
WooCommerce Dynamic Pricing: by Element Stark – 3.1.27
WooCommerce PayFast Gateway: by WooCommerce – 1.4.25
Invoices for WooCommerce: by Bas Elbers – 3.1.9
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.4
WooCommerce: by Automattic – 6.7.0 (update to version 7.0.1 is available)
WooLentor - WooCommerce Elementor Addons + Builder: by HasThemes – 2.4.3
Wordfence Security: by Wordfence – 7.7.1
WP File Manager: by mndpsingh287 – 7.1.6
WP Headers And Footers: by WPBrigade – 2.0.0
WP Mail SMTP: by WPForms – 3.5.2
WP Maintenance Mode & Coming Soon: by Themeisle – 2.5.1
Smush: by WPMU DEV – 3.11.1
WPForms: by WPForms – 1.7.6
YayMail - WooCommerce Email Customizer: by YayCommerce – 3.0.3

### Inactive Plugins (5) ###

Check & Log Email: by WPChill – 1.0.6
N-Media WooCommerce PPOM PRO: by Najeeb Ahmad – 23.9
PPOM Addon: Image DropDown: by N-Media – 3.1
PPOM for WooCommerce by N-MEDIA: by Najeeb Ahmad – 30.1
WPForms Lite: by WPForms – 1.7.6

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)
gift-card (gift-card)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #674 - /shop/
Cart: #662 - /cart/
Checkout: #665 - /checkout/
My account: #668 - /my-account/
Terms and conditions: #659 - /ts-cs/

### Theme ###

Name: krispy-kreme
Version: 1.0.0
Author URL: https://sinappsus.co.za
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: krispy-kreme-official-theme/woocommerce/emails/admin-new-order.php
krispy-kreme-official-theme/woocommerce/emails/customer-completed-order.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-11-08 10:56:45 +02:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Complete: 2,538
Oldest: 2022-10-09 18:05:31 +0200
Newest: 2022-11-08 10:20:11 +0200

Pending: 11
Oldest: 2022-11-08 10:25:41 +0200
Newest: 2022-11-14 17:31:09 +0200

### Status report information ###

Generated at: 2022-11-08 10:25:17 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
Because this is an issue where another plugin is involved it is hard for us to determine if this would be a problem with WooCommerce core (this Github repository is just for the core plugin). I would recommend reaching out for [support](https://woocommerce.com/my-account/create-a-ticket/) for the plugin you're having trouble with
