### ISSUE TITLE
Fatal Error: "Uncaught Error: array_key_exists(): Argument #2 ($array) must be of type array, bool given" on upgrade to PHP 8.0

### ISSUE THREAD

**Issue by ChimaGhost** [woothemes/woocommerce#35513]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I upgrade from php version 7.4 to php 8.0.22 I immediately get a fatal php error when trying to view the wordpress admin.

### Expected behavior

No errors when I upgrade to php 8.0

### Actual behavior

The error I get is as follows:

Fatal error: Uncaught Error: array_key_exists(): Argument #2 ($array) must be of type array, bool given
in /var/www//public_html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-options.php on line 54

Call stack:
WC_Helper_Options::get()
Automattic\W\I\A\N\WooSubscriptionsNotes::is_connected()
Automattic\W\I\A\N\WooSubscriptionsNotes::check_connection()
Automattic\W\I\A\N\WooSubscriptionsNotes::admin_init()
WP_Hook::apply_filters()
WP_Hook::do_action()
do_action()
require_once()

I can fix this issue / make it go away by adding in 
```
if (!$options) {
	return $default;
}
```
right before line 54.

After fixing that fatal error I get a differ fatal error on my plugin page.

Fatal error: Uncaught Error: array_key_exists(): Argument #2 ($array) must be of type array, bool given
in /var/www//public_html/wp-content/plugins/woocommerce/src/Internal/WCCom/ConnectionHelper.php on line 24

Call stack:
array_key_exists()
Automattic\W\I\W\ConnectionHelper::is_connected()
WC_Install::plugin_row_meta()
WP_Hook::apply_filters()
apply_filters()
WP_Plugins_List_Table::single_row()
WP_Plugins_List_Table::display_rows()
WP_List_Table::display_rows_or_placeholder()
WP_List_Table::display()

Which I can fix / make it go away by adding in 
```
if (!$helper_options){
    return false;
}
```

### Steps to reproduce

1. Try to activate woocommerce 7.0.1 while the site is using php version 8.0

### WordPress Environment

Can't give a system report cause when I go to the system status page I get yet another error:

Fatal error: Uncaught Error: array_key_exists(): Argument #2 ($array) must be of type array, bool given
in /var/www//public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php on line 1241

Call stack:
WC_REST_System_Status_V2_Controller::get_settings()
WC_REST_System_Status_V2_Controller::get_item_mappings_per_fields()
WC_REST_System_Status_V2_Controller::get_items()
WP_REST_Server::respond_to_request()
WP_REST_Server::dispatch()
rest_do_request()
WC_API::get_endpoint_data()
include_once()
WC_Admin_Status::status_report()
include_once()
WC_Admin_Status::output()
WC_Admin_Menus::status_page()
WP_Hook::apply_filters()
WP_Hook::do_action()
do_action()

That being said here is the wordpress environment stats:
Wordpress version 6.1
Woocommerce Version 7.0.1
Theme: Twenty Twenty-Two, version: 1.3

and that is all that is active and running while I tested php 8.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Marking this as "status: developer reproduction" based on discussion in p1667981131393249-slack-C011ENB20Q1.

Thanks for your patience, in the mean time, if you're able to add any additional steps that we might help us try and reproduce the issue, it would be appreciated.
