### ISSUE TITLE
Checks not triggered upon payment of the Conditional Shipping and Payments plugin on certain payment methods

### ISSUE THREAD

**Issue by stfn00** [woothemes/woocommerce#35523]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi, after the latest updates, the destination restrictions check of "WooCommerce Conditional Shipping and Payments" paid plugin, are no longer triggered when the payment method used is Stripe or PayPal. While if it is used for example the "Bank Transfer", the restriction works correctly.

I think that the buttons inserted by the related PayPal and Stripe plugins do not trigger the event that performs the check. Have you encountered this problem?

The plugins used to manage payments with PayPal and Stripe are:
- WooCommerce PayPal Payments
- WooCommerce Stripe Gateway

I acknowledge the fact that the bug is not directly related to WooCommerce plugin but is part of it, and the plugins are directly developed by WooCommerce team.

Thank you.

### Expected behavior

When I proceed with the payment, if the rule I entered in "WooCommerce Conditional Shipping and Payments" is correct, it must print the non-processable purchase error because one of the products in the cart cannot be shipped to the country selected in the shipping address.

### Actual behavior

Currently the check does not take place when I choose PayPal or Stripe as a payment method.

### Steps to reproduce

1. Add product to cart
2. On checkout add all Shipping and Billing info
3. I choose to ship to a different country than the one selected in the "WooCommerce Conditional Shipping and Payments" rule
4. Click on PayPal button for payment
5. I expect the error will come out

### WordPress Environment

 - WordPress Version: 6.1
 - WooCommerce Version: 7.0.1
 - WooCommerce Conditional Shipping and Payments Version: 1.14.4
 - WooCommerce PayPal Payments Version: 1.9.5
 - WooCommerce Stripe Gateway Version: 6.9.0
 - PHP 8.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
> I acknowledge the fact that the bug is not directly related to WooCommerce plugin but is part of it, and the plugins are directly developed by WooCommerce team.

Yes although some plugins outside of core are developed by the WooCommerce team, we can't handle support for issues with them here. Sorry for the inconvenience.

If you are having trouble with plugins authored by WooCommerce you can reach out for [support](http://woocommerce.com/my-account/create-a-ticket/)
