### ISSUE TITLE
New Zealand zone regions no longer assigned after upgrade to 7.1.0

### ISSUE THREAD

**Issue by chthonic-ds** [woothemes/woocommerce#35535]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The 7.1.0 release changes the zone region IDs for New Zealand to a new format. For example, `AK` becomes `AUK`. See #35011 for further detail.

If a shipping zone has New Zealand zone regions assigned, the regions no longer appear after upgrading to 7.1.0. 

Zone regions assigned before upgrade:

![woocommerce-7-10-1-zone-regions-before-upgrade](https://user-images.githubusercontent.com/29587253/201031467-33a6d070-064e-449a-a383-fabe7b621579.jpg)

Zone regions absent after upgrade:

![woocommerce-7-10-1-zone-regions-after-upgrade](https://user-images.githubusercontent.com/29587253/201031659-0756f8b3-2437-49ef-9b7c-eed21660c771.jpg)

### Expected behavior

The region zone IDs would be updated to the new format automatically.

### Actual behavior

The zone regions need to be manually reassigned, either via the Shipping Zones UI or by updating the IDs to the new format in the `wp_woocommerce_shipping_zone_locations` table.

### Steps to reproduce

1. Install WooCommerce 7.0.1
2. Create a new shipping zone called "North Island"
3. In the "North Island" zone, add the following zone region: Auckland, New Zealand
4. Confirm the "North Island" zone has an "Auckland" region assigned
5. Upgrade to WooCommerce 7.1.0
6. Confirm the "North Island"  zone no longer has an "Auckland" region assigned

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woocommerce-nz-regions.test
Site address (URL): http://woocommerce-nz-regions.test
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.1l PHP/7.4.27
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 4.80MB
Database Data Size: 3.37MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-11 07:25:24 +00:00
Options: ✔
Notes: 35
Onboarding: skipped

### Action Scheduler ###

Complete: 3
Oldest: 2022-11-10 07:26:28 +0000
Newest: 2022-11-10 07:33:17 +0000

Pending: 1
Oldest: 2022-11-11 07:26:28 +0000
Newest: 2022-11-11 07:26:28 +0000

### Status report information ###

Generated at: 2022-11-10 07:59:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chthonic-ds** [comment]
Additionally: if Country/State for Store Address is set to a New Zealand location, after upgrading to 7.1.0 the value will fallback to Afghanistan. Guessing this is related but can open a new issue if necessary.

Country/State before upgrade:

![woocommerce-7-10-1-store-address-country-before-upgrade](https://user-images.githubusercontent.com/29587253/201035796-09a81edf-76ba-469c-8de1-5ceada1ecd9f.jpg)

Country/State after upgrade:

![woocommerce-7-10-1-store-address-country-after-upgrade](https://user-images.githubusercontent.com/29587253/201035813-c8aa357f-dc28-4112-9335-d92a797baa92.jpg)

**Comment by swatipawarGS** [comment]
Hi @chthonic-ds,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/201279074-e48d4f5c-d4c9-4661-9600-263efb0e587c.mp4

https://user-images.githubusercontent.com/94531721/201297625-62db0285-4f13-4a91-b409-d3fa8f691c0b.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by mouligreenlaw** [comment]
Another report from NZ 5737706-zen
The merchant is losing sales due to existing account holders' saved Region not being auto filled correctly in checkout.
They are working to add a Required label to the field via CSS but it is not a solid workaround since the field can still be ignored.
They have updated the shipping zones so new customers are not affected, but their existing customers are often not able to checkout

**Comment by ThyranWright** [comment]
Have about 10 WooCommerce stores transacting daily. Existing customers calling daily to find out why they cant place orders. One customer even admitted they googled another site and brought from a competitor. Thanks Dev team for not considering the implications of your latest update for New Zealand customers. Lets hope you shift into second gear and get a fix soon because its already been two weeks since the update and we still losing customers!

Using this CSS hack provided by first level support to try and circumnavigate the problem for now. 

/*Remove WooCommerce Region field label on checkout page*/
#billing_state_field label {
    font-size: 0 !important;
}

/*Add WooCommerce Region field label on checkout page*/
#billing_state_field label:after {
    content: '*REGION REQUIRED';
    font-size: 16px;
	font-weight: bold;
	color: #dd1a32;

}

All the NZ WooCommerce stores general settings have defaulted to selling in Afghanistan with selling locations to all countries.
