### ISSUE TITLE
[Enhancement]: HPOS flag in system status report

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#35533]
### Describe the solution you'd like

There's no indication in the system status report that HPOS is enabled or not. I'd like to see that field when opening a support ticket.

**Comment by barryhughes** [comment]
Hi!

This seems to be essentially the same thing [requested here](https://github.com/woocommerce/woocommerce/issues/34864), which has been implemented via [this pull request](https://github.com/woocommerce/woocommerce/pull/35487) and should be available starting with the 7.2.0 release.

With that in mind, I will go ahead and close this issue, but please do reach out if I have misunderstood.
