### ISSUE TITLE
[Enhancement]: Return Add to Cart Portuguese translation to what it was before.

### ISSUE THREAD

**Issue by loulemos** [woothemes/woocommerce#35544]
### Describe the solution you'd like

With the newest Woocommerce update the Portuguese translation for the "Add to Cart" Button went from "Adicionar" to "Adicionar ao Carrinho" this makes for an awkward button since it’s 10 more characters than the english “Add to cart”. 
I belive the before translation "Adicionar" was more than clear to users and clients, we never heard a complaint.

**Comment by barryhughes** [comment]
Hi @loulemos,

Thanks for flagging this. 

In fact, we do not manage translations directly: as with most plugins distributed through [WordPress.org](https://wordpress.org), translations are managed as a community effort and so I would encourage you to submit your proposed change [over here](https://translate.wordpress.org/projects/wp-plugins/woocommerce/). If you have questions or concerns about this process, the translation team can be reached through that page and I'm sure will be happy to help.
