### ISSUE TITLE
[Enhancement]: Fix price field currency symbol position

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35558]
### Describe the solution you'd like

We're looking to simplify the price input field and make it more usable by updating the layout, structure, and some interactions.

https://user-images.githubusercontent.com/79307566/201509568-d689ca80-54bb-433e-847b-a891ab7f065c.mov

**Acceptance criteria**

- [x] Applies to all price input fields in the experience.
- [x] Displayed currency unit follows the store's locale.
- [x] Currency symbol is fixed on the left side of the price input field.
- [x] Currency symbol has a different color from the input field value (`Gutenberg-700`).
- [x] Input value is aligned right.
- [x] Field formatting respects the store's setting, including thousand and decimal separators.
- [x] On blur, commas are added when the user enters a value. For example, when the user types `1234567` and leaves the field, we display the value as `1,234,567`.
- [x] On focus, we highlight the field's content so the user can quickly clear or overwrite the placeholder text.
- [x] On focus, the user can press the up and down arrow keys to increase or decrease the value by 1 (only concerns the value before the first comma, e.g. `0,5 -> 1.5`, NOT `0,5 -> 0.6`).

### Additional context

Related to #35180

**Comment by joshuatf** [comment]
I'd estimate this around a 1-2.  I think most of this has already been put in place by @mdperez86 but maybe there a couple minor tweaks that can be added.
