### ISSUE TITLE
Action Scheduler migration in progress. The list of scheduled actions may be incomplete.

### ISSUE THREAD

**Issue by jonasborneland** [woothemes/woocommerce#35556]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After installing Memcached Redux I get this notification:
Action Scheduler migration in progress. The list of scheduled actions may be incomplete.

It dosen't go away.

What does it mean and how can I fix it?

### Expected behavior

I didn't expect a notification

### Actual behavior

After installing Memcached Redux I get this notification:
Action Scheduler migration in progress. The list of scheduled actions may be incomplete.

### Steps to reproduce

Install Memcached redux on server with memcached
Look at status -> scheduled actions

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: da_DK
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 8.1.11
PHP Post Max Size: 500 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 10.6.3-MariaDB-1:10.6.3+maria~stretch-log
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: pv_
Total Database Size: 572.78MB
Database Data Size: 352.07MB
Database Index Size: 220.71MB
pv_woocommerce_sessions: Data: 6.02MB + Index: 0.08MB + Engine InnoDB
pv_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pv_woocommerce_order_items: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
pv_woocommerce_order_itemmeta: Data: 9.52MB + Index: 8.03MB + Engine InnoDB
pv_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pv_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
petitvert_dashboard: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
petitvert_members: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
petitvert_tbl_token_auth: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_actionscheduler_actions: Data: 20.11MB + Index: 26.73MB + Engine InnoDB
pv_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_actionscheduler_logs: Data: 75.61MB + Index: 44.11MB + Engine InnoDB
pv_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_alp_pickup_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_bv_ip_store: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
pv_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_comments: Data: 3.52MB + Index: 1.91MB + Engine InnoDB
pv_commercekit_searches: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
pv_commercekit_swatches_cache_count: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pv_commercekit_waitlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_commercekit_wishlist: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pv_commercekit_wishlist_items: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
pv_cpf_customfeeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_cpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_cpf_feedproducts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_cpf_resolved_product_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_cp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_debug_functions_time__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_facetwp_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_facetwp_index: Data: 1.42MB + Index: 1.92MB + Engine InnoDB
pv_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
pv_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pv_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_nf3_upgrades: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pv_options: Data: 28.48MB + Index: 4.08MB + Engine InnoDB
pv_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_postmeta: Data: 113.63MB + Index: 58.19MB + Engine InnoDB
pv_posts: Data: 24.52MB + Index: 7.98MB + Engine InnoDB
pv_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_rank_math_analytics_gsc: Data: 27.55MB + Index: 31.11MB + Engine InnoDB
pv_rank_math_analytics_inspections: Data: 2.52MB + Index: 0.92MB + Engine InnoDB
pv_rank_math_analytics_objects: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
pv_rank_math_internal_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
pv_rank_math_internal_meta: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
pv_rank_math_redirections: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
pv_rank_math_redirections_cache: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
pv_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
pv_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
pv_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_slides: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pv_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_s2w_error_product_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_termmeta: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
pv_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
pv_term_relationships: Data: 4.52MB + Index: 3.44MB + Engine InnoDB
pv_term_taxonomy: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
pv_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_usermeta: Data: 0.22MB + Index: 0.08MB + Engine InnoDB
pv_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pv_wccs_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wccs_condition_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pv_wc_customer_lookup: Data: 0.23MB + Index: 0.25MB + Engine InnoDB
pv_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
pv_wc_order_product_lookup: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
pv_wc_order_stats: Data: 0.38MB + Index: 0.34MB + Engine InnoDB
pv_wc_order_tax_lookup: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
pv_wc_product_attributes_lookup: Data: 1.52MB + Index: 1.27MB + Engine InnoDB
pv_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_wc_product_meta_lookup: Data: 2.52MB + Index: 5.17MB + Engine InnoDB
pv_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_wc_webhooks: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
pv_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pv_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pv_wdp_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_woobe_history: Data: 20.55MB + Index: 20.55MB + Engine InnoDB
pv_woobe_history_bulk: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pv_wpf_filters: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
pv_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wpr_rocket_cache: Data: 0.52MB + Index: 0.75MB + Engine InnoDB
pv_wpr_rucss_used_css: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
pv_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pv_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pv_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 11153
awdp_pt_rules: 1
ckit_size_guide: 1
custom_css: 2
customize_changeset: 1
elementor_library: 17
ep-synonym: 1
mc4wp-form: 1
nav_menu_item: 227
o-discount: 2
o-list: 2
oembed_cache: 20
page: 15
post: 6
postman_sent_mail: 250
product: 4826
product_variation: 11878
product-feed: 1
pwbf_deal: 1
pwbf_event: 1
revision: 21
schema: 2
shop_coupon: 126
shop_order: 2994
shop_order_refund: 326
size-chart: 11
sl-insta-account: 1
sl-insta-feed: 1
sl-insta-media: 384
vc_settings_preset: 1
warmcache: 2
wcct_countdown: 3
wp_global_styles: 1
yay-currency-manage: 2
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

WooCommerce Sale Category: by Webikon (Juraj Kiss) – 0.2
Action Scheduler High Volume: by Prospress Inc. – 1.1.0
Import / Export Customizer Settings: by Brainstorm Force – 1.0.6
Auto Image Attributes From Filename With Bulk Updater: by Arun Basil Lal – 3.3
Bulk remove posts from category: by MasterNs – 3.3
CommerceGurus Commercekit: by CommerceGurus – 2.1.1
Customizer Export/Import: by The Beaver Builder Team – 0.9.5
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.4
GTM4WP: by Thomas Geiger – 1.16.1
ElasticPress - Facet By Meta: by 10up – 1.0.0
ElasticPress: by 10up – 4.3.1
Elementor: by Elementor.com – 3.8.0
Facebook for WooCommerce: by Facebook – 2.6.30
FacetWP - Cache: by FacetWP
LLC – 1.6.1

FacetWP: by FacetWP
LLC – 4.1.2

Imsanity: by Exactly WWW – 2.8.2
Jetpack: by Automattic – 11.5.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.7
Kirki Customizer Framework: by David Vongries – 4.0.24
Klaviyo: by Klaviyo
Inc. – 3.0.4

Loco Translate: by Tim Whitlock – 2.6.3
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.82
Media File Renamer (Pro): by Jordy Meow – 5.4.9
Shipmondo til WooCommerce: by Shipmondo – 4.1.0
Post SMTP: by Post SMTP – 2.1.10
Product GTIN (EAN, UPC, ISBN) for WooCommerce: by Emanuela Castorina – 1.1.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Rank Math SEO: by Rank Math – 1.0.101
Shopping Feed for Google: by Simprosys InfoMedia – 1.8
String Locator: by InstaWP – 2.6.1
User Role Editor: by Vladimir Garagulya – 4.63.1
Widget Importer & Exporter: by ChurchThemes.com – 1.6
BEAR – Bulk Editor and Products Manager Professional for WooCommerce: by realmag777 – 1.1.2
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.12
Gift Wrapper: by Sagehen Studio – 5.2.5
WooCommerce QuickPay: by Perfect Solution – 6.8.2
WooCommerce: by Automattic – 7.1.0
WP Rocket | Change Preload Parameters: by WP Rocket Support Team –
WP Rocket | Change Remove Unused CSS Parameters: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.12.2.1
Smart Image Resize PRO: by Nabil Lemsieh – 1.7.8

### Inactive Plugins (3) ###

CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.5
Query Monitor: by John Blackbourn – 3.10.1
YITH WooCommerce Wishlist: by YITH – 3.14.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #3172 - /alle-produkter/
Cart: #3173 - /kurv/
Checkout: #3174 - /checkout/
My account: #3175 - /min-konto/
Terms and conditions: #72 - /handelsbetingelser/

### Theme ###

Name: Shoptimizer Child Theme
Version: 1.2.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Shoptimizer
Parent Theme Version: 2.6.2
Parent Theme Author URL: https://www.commercegurus.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shoptimizer-child-theme/woocommerce/checkout/form-checkout.php
shoptimizer-child-theme/woocommerce/single-product/related.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-12 09:36:10 +02:00
Options: ✔
Notes: 9
Onboarding: completed

### Action Scheduler ###

Complete: 61,203
Oldest: 2022-11-06 07:36:02 +0000
Newest: 2022-11-11 20:41:30 +0000

Pending: 4,837
Oldest: 2022-11-11 18:10:05 +0000
Newest: 2022-12-08 17:53:41 +0000

Failed: 199
Oldest: 2022-11-04 14:45:02 +0000
Newest: 2022-11-10 15:34:48 +0000

Canceled: 113
Oldest: 2022-11-07 12:39:11 +0000
Newest: 2022-11-10 15:50:06 +0000

### Status report information ###

Generated at: 2022-11-11 22:41:36 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
Hi, since this is happening with Memcached Redux installed, it really feels like it's a question for them, not about core WooCommerce (which is what this repository issues and discussion is for).

You could perhaps ask for support at https://wordpress.org/support/plugin/memcached-redux/

**Comment by jonasborneland** [comment]
Thank you very much for the answer 🙏
I see your point.
But could you give me a clue why “ Action Scheduler migration in progress. The list of scheduled actions may be incomplete “ is displayed?
Does it show when some tables need a upgrade or similar?
