### ISSUE TITLE
Allow adding custom task headers in the setup task list

### ISSUE THREAD

**Issue by xristos3490** [woothemes/woocommerce#35552]
### Description

Currently, it is possible to add custom tasks to any task list, but the task headers included in the setup task list are not extendable. 

That's because the entire system of task headers is handled directly in ReactJS. See https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/two-column-tasks/task-headers.ts#L14-L24

**Example adding a custom task in the setup list:**

Adding custom tasks can be done by using the singleton returned from `\Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::instance();`
```php
$tl = \Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::instance();
$list = $tl::get_lists_by_ids( array( 'setup' ) );
$list = array_pop( $list );
$custom_task = new \Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\CustomTask( $list );
$tl::add_task( 'setup', $custom_task );
```

This issue aims to ensure that a custom task list can also include a custom header.

**Comment by psealock** [comment]
Hi @xristos3490, you'll need to use JS to completely configure a custom task.

Here is more information on how to do that https://github.com/woocommerce/woocommerce/blob/trunk/docs/extension-development/handling-merchant-onboarding.md

If you'd like to set up an example development environment for React try this starter kit https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/create-woo-extension/README.md

I will close this issue for now, please come back and reopen it if you have questions on any of the above.
