### ISSUE TITLE
[Enhancement]: Align the field height across the whole form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35567]
### Describe the solution you'd like

Fields in our form have different heights: 30 px, 31 px, 38 px, etc. The core Gutenberg component (both in the actual editor on my test site and in the Figma library) is 36 px. We should align this for better consistency and usability (larger fields are easier to use on desktop and mobile).

<img width="447" alt="image" src="https://user-images.githubusercontent.com/79307566/201640775-bfa94993-ca22-4dc8-ae89-322fff335b11.png">

**Acceptance criteria**

- [x] All fields in the form are 36 px high (this includes core inputs and our custom dropdowns and search fields).

**Comment by joshuatf** [comment]
@octaedro I'll be working on https://github.com/woocommerce/woocommerce/issues/35566 - let's keep in touch to make sure we don't have any crossover on these issues.

**Comment by octaedro** [comment]
Thank you @joshuatf for the warning. I think that @mdperez86 assigned me this issue to groom and estimate it.

**Comment by octaedro** [comment]
Hey @jarekmorawski,
Just to confirm, we also want the shipping selector and the category input with the same height (36px), right?

**Comment by jarekmorawski** [comment]
Correct! We want all fields (except description and summary) to have the same height regardless of state (empty, with items, focused, disabled, etc).

**Comment by octaedro** [comment]
This fix looks quite simple.
I'll estimate a `1` for this issue.
