### ISSUE TITLE
[Enhancement]: Fix the field height in the Attributes modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35566]
### Describe the solution you'd like

I noticed that the attribute dropdown's height differs from the value picker in the Attributes modal (31 vs 38 px). It only happens after I add at least 1 value. Can we align for a more consistent experience? This should likely be applied on a component level.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/79307566/201639033-cec6b63c-b834-41d7-aa7e-1a8fd9696ac6.png">

**Acceptance criteria**

- [x] All fields in the form are the same height (36 px).

**Comment by joshuatf** [comment]
This should be a 1 for estimation.  We probably just need a min-height when no tags yet exist.
