### ISSUE TITLE
[Enhancement]: Improve element stacking in modals on tablet and mobile

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35565]
### Describe the solution you'd like

The usable space in the Attributes dialog is pretty small on tablet and mobile, especially when you add multiple attributes.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/79307566/201637018-02506a94-fd27-4425-b2f6-b1f602cc6740.png">

To fix that, we could tweak the layout so that the items are stacked vertically on lower-resolution devices.

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/79307566/201636368-04511313-c1fd-4195-9921-3216a75fc868.png">

**Acceptance criteria**

- [x] We don't show the table's header row on lower-resolution devices.
- [x] Instead, we stack each added item as a separate row.
- [x] The trash/delete icon is centered vertically and has a 8px right padding.
- [x] The list continues to have a fixed height and the whole modal fits within the device's viewport, fixing the CTA buttons in the bottom part of the screen.

**Comment by beaulebens** [comment]
Between the margins around the outside of the modal, and the header/footer sections, there is also very littler vertical space available, so I could only just see one row of the attribute details I was editing.
