### ISSUE TITLE
[Enhancement]: Generate a slug based on the shipping class's name

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35569]
### Describe the solution you'd like

Can we use the name to automatically generate a slug in the new shipping class modal? It'd save the user a click or two. We could use the same logic we apply to the SKU.

**Acceptance criteria**

- [ ] If the name field is filled, we generate a slug on the blur event (when the user clicks outside the name field or uses Tab to go to the slug field).
- [ ] If an identical slug already exists in the system, we add `-N` where `N` is the copy identifier (e.g. `new-class-3` if `new-class` and `new-class-2` slugs already exist in the system).

**Comment by AnnaMag** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/35158

**Comment by joshuatf** [comment]
>If an identical slug already exists in the system, we add -N where N is the copy identifier (e.g. new-class-3 if new-class and new-class-2 slugs already exist in the system).

@jarekmorawski Do we want to do this after the slug is filled in?  Or wait until submit to update it?  It seems like the former might be better since the latter could lead to unexpected slugs on save.

Similarly, I wonder if we want to do the same thing with product slugs and other slug fields.

**Comment by jarekmorawski** [comment]
> Do we want to do this after the slug is filled in? Or wait until submit to update it? It seems like the former might be better since the latter could lead to unexpected slugs on save.

Right after the slug is filled in (which, in some cases, will be when the user opens the modal).

> Similarly, I wonder if we want to do the same thing with product slugs and other slug fields.

I think we already do something similar to the product link, but the general logic should be the same for all slugs.

**Comment by mdperez86** [comment]
This logic has been implemented in the server side and it's the reason why the slug field is optional in the shipping class modal form.
Do we really want to duplicate that logic server and client side?
If we are going to have that logic in client side does make sense to mantain the slug field optional?
cc: @jarekmorawski

**Comment by joshuatf** [comment]
As @mdperez86 mentioned, this logic does reside on the server and currently the field is optional.  I'm okay with either approach, but getting the slugs client-side will require some changes in the REST API (or additional endpoints potentially).

Maybe this issue should instead check if a slug already exists when blurring the slug field and keep it optional?  Or do you think generating on the fly and filling out the slug field is a better interaction @jarekmorawski?

**Comment by jarekmorawski** [comment]
The field was optional because I assumed we'd generate it anyway without user input (after they enter the name and close the modal). The issue comes from Beau's feedback who found it odd and would prefer to have the slug generated on the fly.

I think we can make the slug field non-optional and move the logic from the server to the client. Can we do that or do we have to duplicate the logic?

**Comment by joshuatf** [comment]
It can be done, but also yes, there will need to be some level of duplicated logic.

I think more likely than copying over logic, we'll need some new endpoint or additional data on an existing endpoint to help us generate the slug.  The client will never fully be capable of generating the slug on its own because we need access to the database to generate the next sequential unique slug.

If that's what we want to do, we can move forward with this.

**Comment by mdperez86** [comment]
I agree with @joshuatf an endpoint with the new slug suggestion looks like the right way if we are going to show that suggestion to the user. That way the logic of calculating the next unique slug is contained only on one side (the server) and can be reused everywhere else we need the same logic.

**Comment by AnnaMag** [comment]
@mdperez86 I will include this for Cycle 32 planning.

**Comment by retrofox** [comment]
We need to rethink the implementation in terms of UI/UX, considering that this is (another) async process. This means that while the user introduces a class name and, for instance, leaves the input, the app should populate the slug input with the suggested slug.

All these steps are not immediate, at least from a system perspective. When it's doable, we can optimistically mitigate this "uncomfortable feeling" for the user by updating the UI.

We discussed this with the team during the grooming call, and a few ideas emerged. I want to work on them and provide technical feedback to polish the idea of the UI/UX implementation.

cc @j111q

**Comment by retrofox** [comment]
- [ ] Create a server function to generate the slug. We can probably extract/refactor the code from the [ wp_unique_term_slug ](https://github.com/WordPress/wordpress-develop/blob/a1b1e0339eb6dfa72a30933cac2a1c6ad2bbfe96/src/wp-includes/taxonomy.php#L3078-L3156)core function
- [ ] Create a custom endpoint to request a slug suggestion based on the class name
- [ ] Update the UI to perform a request to get the shipping class suggestion
