### ISSUE TITLE
I'm also having issue with fees added with  $wc->cart->add_fee() not being added to order.

### ISSUE THREAD

**Issue by mudasirhamid** [woothemes/woocommerce#35577]
I'm also having issue with fees added with  $wc->cart->add_fee() not beeing added to order. 

I use this code to add fee to order in checkout-page based on number of payments (custom select field added to billing fields)
```.php
function add_payments_fee($cart_object ){
    if (is_admin() && !defined('DOING_AJAX')) {
        return;
    }



    parse_str (WC()->checkout()->get_value('post_data'),$post_data);
    if(!isset($post_data['billing_number_of_payments'])) {
        return;
    }

    $number_of_payments=$post_data['billing_number_of_payments'];
    if ($number_of_payments>1) {
        $cartTotal=WC()->cart->get_cart_contents_total();
        $payment_fee=$cartTotal/$number_of_payments*($number_of_payments-1)*0.02;
        $cart_object ->add_fee('abc', $payment_fee);
    }
}
add_action('woocommerce_cart_calculate_fees','add_payments_fee');
```
It add the fee to the order details in checkout-page, however when making order it disapear. 

Found a work-around in adding the fee again with woocommerce_checkout_create_order hook
```.php
function add_fee_to_order( $order, $data ){
    //This should not be needed at all as the fee should be added from the cart automatically, may lead in future to double payment-fee if the autoumatic add starts to work.

    $number_of_payments=$data['billing_number_of_payments'];
    if ($number_of_payments>1) {
        $cartTotal = WC()->cart->get_cart_contents_total();
        $payment_fee = $cartTotal / $number_of_payments * ($number_of_payments - 1) * 0.02;

        $item_fee = new WC_Order_Item_Fee();
        $item_fee->set_name('abc');
        $item_fee->set_amount($payment_fee); // Fee amout
        $item_fee->set_tax_class(''); // default for ''
        $item_fee->set_tax_status('none'); // or 'none'
        $item_fee->set_total($payment_fee); // Fee amount

        // Add Fee item to the order
        $order->add_item($item_fee);

        $order->calculate_totals();
        $order->save();


    }

}

add_action( 'woocommerce_checkout_create_order', 'add_fee_to_order', 10, 2 );
```

_Originally posted by @nathanrona in https://github.com/woocommerce/woocommerce/issues/26951#issuecomment-963152062_

**Comment by thomas-zg** [comment]
Hello,

I'm doing this by using the WC()->cart->fees_api()->add_fee() method and it works well.
[https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-cart-fees.html](url)

Best,
Thomas

**Comment by MahimZaman** [comment]
Well, I also have faced this issue and the solution for mine was.

I was using a class and on the **construct,** I added the **'woocommerce_cart_calculate_fees'**- hook and a callback function. 
inside the callback function, I added **require_once** and the path to my **add_fee** code. This was adding the fee on checkout totals fine but not in the order, But then I replaced the code, and instead of using a path to the code file I directly wrote the code inside the **callback function** and it worked fine.

**Comment by mikejolley** [comment]
Looks like this has some solutions now so I will mark closed. Usually the issue is due to the code not executing every time `woocommerce_cart_calculate_fees` runs.

Thanks
