### ISSUE TITLE
[Enhancement]: Fix the gap in the featured product checkbox

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35572]
### Describe the solution you'd like

There's currently a significant gap between the featured product checkbox label and the tooltip button. It looks like the button already has the desired 8 px margin-left, but combined with the extra 6/12 px padding, it looks detached from the checkbox.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/79307566/201649696-2b9d795a-7d27-4689-96b3-7a0e0686f038.png">

**Acceptance criteria**

- [ ] The gap between the ending of the checkbox's label and the tooltip button is 8 px.

**Comment by octaedro** [comment]
We should add the styles we need [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/product-page.scss#L40-L42).
My estimation for this issue is `1`
