### ISSUE TITLE
wc_get_products() - some products missing

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#35585]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello!

Some products missing from results when loop through wc_get_products

```php
// products in woocommerce: 40 000+

$page = 1;
$limit = 50;
do {
    $wc_query = wc_get_products(['paginate' => true, 'page' => $page, 'limit' => $limit]);
    foreach ($wc_query->products as $wc_product) {
        /* ... */
    }
    $page++;
} while ($page <= ceil($wc_query->total / $limit));
```

### Expected behavior

Get all products

### Actual behavior

Some products missing

### Steps to reproduce

Add a lot of products to store
Loop wc_get_products

** The problem does not always occur, try loop 5-10 times **

Someone reported similar things: https://wordpress.org/support/topic/wc_get_products-some-products-are-missing/

### WordPress Environment

Wordpress 6.1
Woocommerce 7.1

No other plugins installed

Default theme used

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ghost** [comment]
catalog real product count: 43 437

5 test, same catalog, same script:

C:\xampp\php>php ../htdocs/wordpress/test.php
Internal Products: 43430

C:\xampp\php>php ../htdocs/wordpress/test.php
Internal Products: 43437

C:\xampp\php>php ../htdocs/wordpress/test.php
Internal Products: 43416

C:\xampp\php>php ../htdocs/wordpress/test.php
Internal Products: 43437

C:\xampp\php>php ../htdocs/wordpress/test.php
Internal Products: 43432

**Comment by barryhughes** [comment]
I cannot so far replicate this, I end up with a consistent total. Closing, but feel free to open a fresh issue if you continue to experience the problem with the latest version of our plugin.
