### ISSUE TITLE
Product short description (postexcerpt) metabox does not remember its open/closed state

### ISSUE THREAD

**Issue by EricDu** [woothemes/woocommerce#35580]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since WooCommerce 7.x, the Product short description (postexcerpt) metabox is closed when editing a product or after saving the product.

WooCommerce 6.9.3 did not exhibit this problem. This appears to be a regression.

### Expected behavior

Expect metabox to remember its previous state.

### Actual behavior

Metabox is always closed.

### Steps to reproduce

1. Add New or Edit product
2. Open Short description metabox
3. Save, Publish, or Update product
4. Once page refreshes, Short description metabox is closed

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.lizgouletdubois.com
Site address (URL): https://www.lizgouletdubois.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.3.36-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 49.35MB
Database Data Size: 40.61MB
Database Index Size: 8.74MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpau_active_plugins_info: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpau_upgrade_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_adrotate_stats_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 0.35MB + Index: 0.09MB + Engine MyISAM
wp_dgwt_wcas_index: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 0.27MB + Index: 0.22MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fb3d_pages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_options: Data: 1.85MB + Index: 0.09MB + Engine MyISAM
wp_postmeta: Data: 9.59MB + Index: 2.09MB + Engine MyISAM
wp_posts: Data: 7.21MB + Index: 0.70MB + Engine MyISAM
wp_redirection_404: Data: 0.41MB + Index: 0.08MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.13MB + Index: 0.23MB + Engine MyISAM
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.57MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 5.93MB + Index: 0.50MB + Engine MyISAM
wp_wfHits: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 4.33MB + Index: 0.21MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.30MB + Index: 0.06MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.01MB + Index: 0.01MB + Engine InnoDB
wp_wfls_settings: Data: 0.01MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 0.89MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.23MB + Index: 0.34MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.29MB + Index: 0.07MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.04MB + Index: 0.04MB + Engine MyISAM

### Post Type Counts ###

3d-flip-book: 17
acf: 3
acf-field: 4
acf-field-group: 3
administer: 1
attachment: 2423
customize_changeset: 1
flamingo_contact: 449
flamingo_inbound: 2663
jb_store_css: 11
mailpoet_page: 1
mgmlp_media_folder: 294
nav_menu_item: 24
page: 345
post: 267
product: 314
revision: 1390
shop_order: 3
wpcf7_contact_form: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Add From Server: by Dion Hulse – 3.4.5
Admin Post Navigation: by Scott Reilly – 2.1
Advanced Custom Fields: by WP Engine – 6.0.4
FiboSearch - AJAX Search for WooCommerce (Pro): by FiboSearch Team – 1.20.2
Akismet Anti-Spam: by Automattic – 5.0.1
BackWPup: by Inpsyde GmbH – 3.10.0
CC Child Pages: by Caterham Computing – 1.42
Classic Editor: by WordPress Contributors – 1.6.2
CMS Tree Page View: by Jon Christopher – 1.6.6
Code Snippets: by Code Snippets Pro – 3.2.1
Contact Form 7: by Takayuki Miyoshi – 5.6.4
Crop Thumbnails: by Volkmar Kantor – 1.4.0
Enable Media Replace: by ShortPixel – 4.0.0
Flamingo: by Takayuki Miyoshi – 2.3
Smash Balloon Instagram Feed: by Smash Balloon – 6.1
3D FlipBook - Lite Edition: by iberezansky – 1.12.5
Jetpack: by Automattic – 11.5.1
List category posts: by Fernando Briano – 0.87
NK Google Analytics: by Manfred Rodríguez – 1.6.2
Official StatCounter Plugin: by Aodhan Cullen – 2.0.9
Redirection: by John Godley – 5.3.5
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.3
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Widget Options: by Widget Options Team – 3.8.9.1
WooCommerce Payments: by Automattic – 5.0.2
WooCommerce PayPal Payments: by WooCommerce – 1.9.5
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.4
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce: by Automattic – 7.1.0
Wordfence Security: by Wordfence – 7.7.1
Yoast SEO: by Team Yoast – 19.10
WP Mail SMTP: by WPForms – 3.6.1

### Inactive Plugins (3) ###

Jetpack Boost: by Automattic - Jetpack Site Speed team – 1.5.4
Media Library Folders: by Max Foundry – 8.0.3
Media Library Folders Reset: by Max Foundry – 8.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)
subscription (subscription)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #10264 - /shop/
Cart: #10265 - /cart/
Checkout: #10266 - /checkout/
My account: #10267 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: _LGD
Version: 5.0.0
Author URL: https://www.ericdubois.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: _LGD-5/woocommerce/archive-product.php
_LGD-5/woocommerce/single-product.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.lizgouletdubois.com
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Rhode Island

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

PayPal: refunds

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-15 00:17:00 -05:00
Options: ✔
Notes: 49
Onboarding: completed

### WooCommerce Payments ###

Version: 5.0.2
Connected to WPCOM: Yes
Blog ID: 212058730
Account ID: acct_1M0DreC2ucVp5PZb

### Action Scheduler ###

Complete: 893
Oldest: 2022-11-03 20:04:39 -0400
Newest: 2022-11-14 09:26:06 -0500

Pending: 1
Oldest: 2022-11-14 19:30:43 -0500
Newest: 2022-11-14 19:30:43 -0500

### Status report information ###

Generated at: 2022-11-14 11:55:13 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by edequalsawesome** [comment]
Issue also reported in #5711319-zen, and I was also able to duplicate on a new local test site

**Comment by swatipawarGS** [comment]
Hi @EricDu,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/202101751-34fe3524-96d1-4692-b850-ffe89e691799.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
@EricDu Thanks for reporting the issue. I'm not seeing this in the latest version of WooCommerce. Can you let us know if you still see the issue?
