### ISSUE TITLE
High-Performance order storage (COT) Option dose not enable correctly.

### ISSUE THREAD

**Issue by zenaul** [woothemes/woocommerce#35589]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This feature is not enabled correctly if the plugin header are contain the the 'WC tested up to' property.
After investigate i found this line if 'WC tested up to' exist in plugin header then this option is not visible.
Some screenshot are bellow:

Enable checkbox dose not visible
![image](https://user-images.githubusercontent.com/10365575/201879039-9bad1c2e-7461-41c6-91de-2c6bfab8255e.png)

Plugin Header
![image](https://user-images.githubusercontent.com/10365575/201879331-710a6f4c-49b5-47a4-bbc7-3ff6a1db5d45.png)

woocommerce/src/Utilities/PluginUtil.php
![image](https://user-images.githubusercontent.com/10365575/201880164-dbeebda5-70f0-435f-8ab2-d2cc860cf94a.png)

### Expected behavior

I think if contain the 'WC tested up to' in the plugin header then it should be enable.

### Actual behavior

I think if contain the 'WC tested up to' in the plugin header then it should be enable.

### Steps to reproduce

1. At First Install and Active YITH Wishlist / YITH Compare plugin
2. Go to Dashboard
3. Navigate to WooCommerce > Settings > Advanced > Features

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://plugincheck.test
Site address (URL): http://plugincheck.test
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.1
PHP Version: 8.0.10
PHP Post Max Size: 5 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.78.0
(SecureTransport) OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 8.0.26
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wpwl_
Total Database Size: 6.58MB
Database Data Size: 5.07MB
Database Index Size: 1.51MB
wpwl_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpwl_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpwl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpwl_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpwl_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwl_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_options: Data: 4.05MB + Index: 0.06MB + Engine InnoDB
wpwl_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpwl_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpwl_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpwl_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpwl_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwl_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpwl_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpwl_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpwl_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpwl_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwl_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpwl_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
elementor_library: 1
page: 8
post: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Elementor: by Elementor.com – 3.8.1
WooCommerce: by Automattic – 7.1.0
WP Reset: by WebFactory Ltd – 1.95
YITH WooCommerce Wishlist: by YITH – 3.15.0

### Inactive Plugins (16) ###

Akismet Anti-Spam: by Automattic – 5.0.1
All-in-One WP Migration: by ServMask – 7.67
BetterLinks: by WPDeveloper – 1.5.1
EmbedPress: by WPDeveloper – 3.6.1
Essential Addons for Elementor: by WPDeveloper – 5.4.2
Ever Compare: by HasTheme – 1.2.3
Hello Dolly: by Matt Mullenweg – 1.7.2
HT Mega - Absolute Addons for Elementor Page Builder: by HasThemes – 1.9.8
HT Mega Pro: by HasThemes – 1.3.4
Loco Translate: by Tim Whitlock – 2.6.3
Monetization Code plugin: by aerin Singh – 1.0
Ocean Extra: by OceanWP – 2.0.6
Query Monitor: by John Blackbourn – 3.10.1
Starter Templates: by Brainstorm Force – 3.1.18
Support Genix: by Support Genix – 1.1.1
WishSuite - Wishlist for WooCommerce: by HasTheme – 1.3.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 3.9.4
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-16 03:39:43 +00:00
Options: ✔
Notes: 45
Onboarding: completed

### Action Scheduler ###

Complete: 10
Oldest: 2022-11-01 09:26:06 +0000
Newest: 2022-11-15 09:41:47 +0000

Pending: 1
Oldest: 2022-11-16 09:36:17 +0000
Newest: 2022-11-16 09:36:17 +0000

### Status report information ###

Generated at: 2022-11-15 09:41:53 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @zenaul,

For a plugin to indicate that it is compatible with HPOS, it needs to do two things:

1. The `WC tested up to` field must be present in the plugin header.
2. Compatibility with HPOS needs to be declared [as in this example](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility).

If you have any active plugins that include the `WC tested up to` header but which either do not declare compatibility with HPOS, or that explicitly declare they are incompatible, then it will not generally be possible to enable the feature.

I hope that makes things a little clearer :-)

**Comment by barryhughes** [comment]
Apologies for the above message, I accidentally triggered an automated workflow.

**Comment by zenaul** [comment]
Hello @barryhughes,

Thank you so much for your kind and detailed response. I truly appreciate you for clarifying the matter.

With all due respect, I think if 'WC tested up to' field's value in the plugin header is greater than or equals to 7.1, don't you think the option should be enabled automatically ? It's my earnest request to the developer team to take this into consideration.

**Comment by barryhughes** [comment]
Thanks, @zenaul. 

The reality is that HPOS is a new, large, and complex feature. 

In the long term, it will be the only data-store we ship and so, in a sense, we are moving in the direction you have requested. However, initially, we want to be very careful about how we roll this out (the last thing we want is unexpected problems for merchants).

> I think if 'WC tested up to' field's value in the plugin header is greater than or equals to 7.1, don't you think the option should be enabled automatically?

Our thinking is that the feature needs to be opt-in (at least initially) and that extensions must explicitly declare compatibility (again, initially—at some future point both these things will be revised). If they do not, or if they declare they are incompatible, then we want to protect merchants from accidentally activating the feature.

Can I ask what you see as the main drawbacks of this approach? Though I can think of a few possibilities, I'd be interested to hear your own perspective (and that of anyone else who might want to share).

**Comment by zenaul** [comment]
Hi @barryhughes 

Thank you so much for your response.
I first thought that since the value is 7.1 or more if it can be done automatically rather than manually.
But now I am clear that since this is a rich feature it will be better for all of us to keep it as it is.
