### ISSUE TITLE
Generating multiple orders while using "woocommerce_create_order" filter

### ISSUE THREAD

**Issue by sanesh-acowebs** [woothemes/woocommerce#35599]
Woocommerce 7.1 seems to be calling the function 'possibly_schedule_import' while creating orders ( using the "**woocommerce_create_order**" filter ), the function returning null values instead of order id. This prevents the third-party plugin from having the opportunity to create an order (generating multiple orders). hoping this will be fixed asap.

https://github.com/woocommerce/woocommerce/blob/42d2260ca691c4b0422088199d3f6fdfba56c529/plugins/woocommerce/src/Internal/Admin/Schedulers/OrdersScheduler.php#L43

**Comment by rahulpba** [comment]
Same issue for me also

**Comment by sanesh-acowebs** [comment]
Still, waiting for an update on this issue?

Hope you understand the issue. Let me explain the issue in detail.

In the Woocommerce plugin, there is a filter hook,  **woocommerce_create_order**, available for third-party plugins to create their own orders in the default Woocommerce **create_order** function. On the “**woocommerce/includes/class-wc-checkout.php**” file (line number: 323). 
As in the screenshot https://tinyurl.com/2zyo7677
The **create_order** function checks for this filter return value and proceeds to create an order. As in the screenshot https://tinyurl.com/2p2q2k2p
Actually, this should be required to return newly created order IDs from third-party plugins.

From Woocommerce 7.1 update, they added a new action function on the “**woocommerce/src/Internal/Admin/Schedulers/OrdersScheduler.php**”
File. As in the screenshot https://tinyurl.com/2ztjr2pe 
The same filter hook is added as an action hook here. And that function body returns nothing. Moreover, they didn’t give any priority parameter to override it.  
Please check the screenshot https://tinyurl.com/2j7kavmp

Due to that, the action function **possibly_schedule_import** will always run first and return null and make the order id exist checking on the **create_order** function to false. Then create an additional order. We request this function to return the **order id.** 

We have a plugin that uses “**woocommerce_create_order**” to create our own orders and override the default order creation. But after the Woocommerce 7.1 update due to the above reason, it creates multiple orders ( orders from our plugin code and default orders ) and breaks the plugin functionality flow. 

Hope you will have a detailed look at the same and will release an update with the fix asap.

**Comment by tomalec** [comment]
Tested it locally, and it seems the issue was successfully fixed in https://github.com/woocommerce/woocommerce/pull/35743. Released in 8.3.0
