### ISSUE TITLE
CRITICAL Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF' at line 1 in wp-includes/wp-db.php:2056

### ISSUE THREAD

**Issue by pschonmann** [woothemes/woocommerce#35593]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Tried to upgrade from WP 5.8 to 6.1, but still getting broken site. This is what i see in phpfpm logs. When restore 5.8 files from backup. Wordpress works fine again
```
2022-11-15T15:09:47+00:00 CRITICAL Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF' at line 1 in /data/www/example.com/public_html/wp-includes/wp-db.php:2056
Stack trace:
#0 /data/www/example.com/public_html/wp-includes/wp-db.php(2056): mysqli_query()
#1 /data/www/example.com/public_html/wp-includes/wp-db.php(1945): wpdb->_do_query()
#2 /data/www/example.com/public_html/wp-includes/wp-db.php(2695): wpdb->query()
#3 /data/www/example.com/public_html/wp-admin/includes/upgrade.php(2749): wpdb->get_results()
#4 /data/www/example.com/public_html/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php(412): dbDelta()
#5 /data/www/example.com/public_html/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php(327): WP_Maintenance_Mode::single_activate()
#6 /data/www/example.com/public_html/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php(346): WP_Maintenance_Mode::activate()
#7 /data/www/example.com/public_html/wp-includes/class-wp-hook.php(303): WP_Maintenance_Mode->check_update()
#8 /data/www/example.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#9 /data/www/example.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#10 /data/www/example.com/public_html/wp-admin/admin.php(175): do_action()
#11 /data/www/example.com/public_html/wp-admin/plugins.php(10): require_once('...')
#12 {main}
  thrown v /data/www/example.com/public_html/wp-includes/wp-db.php na řádku 2056
```

### Expected behavior

Upgrade without problem

### Actual behavior

Broken Site

### Steps to reproduce

1. Just click to update wp to 6.1
2. wait
3. website broken

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.6 - Je dostupná nová verze WordPress (6.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.23
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.29-21
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: nwkx_
Celková velikost databáze: 39.77MB
Velikost dat databáze: 29.64MB
Velikost indexu databáze: 10.13MB
nwkx_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nwkx_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nwkx_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_actionscheduler_actions: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
nwkx_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
nwkx_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
nwkx_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
nwkx_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nwkx_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
nwkx_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
nwkx_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_gopay_inline_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_idoklad_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_options: Data: 5.47MB + Index: 0.20MB + Engine InnoDB
nwkx_postmeta: Data: 13.52MB + Index: 5.03MB + Engine InnoDB
nwkx_posts: Data: 6.52MB + Index: 0.59MB + Engine InnoDB
nwkx_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
nwkx_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_toret_tvokativ_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_trp_gettext_cs_cz: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
nwkx_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nwkx_trp_gettext_original_strings: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
nwkx_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nwkx_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nwkx_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
nwkx_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
nwkx_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nwkx_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nwkx_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_wc_product_attributes_lookup: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
nwkx_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_wc_product_meta_lookup: Data: 0.23MB + Index: 0.47MB + Engine InnoDB
nwkx_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nwkx_woobe_history: Data: 0.33MB + Index: 0.48MB + Engine InnoDB
nwkx_woobe_history_bulk: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nwkx_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_zasilkovna_dopravci: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_zasilkovna_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nwkx_zasilkovna_staty: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 2
acoplw_prod_list: 2
attachment: 723
custom_css: 2
elementor_library: 19
filter-field: 7
filter-set: 2
language_switcher: 2
nav_menu_item: 15
page: 17
post: 3
product: 199
product_variation: 1891
revision: 448
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Acowebs Product Labels For Woocommerce: Autor: Acowebs – 1.4.1
Elementor Pro: Autor: Elementor.com – 3.8.1
Elementor: Autor: Elementor.com – 3.8.1
Filter Everything PRO: Autor: Andrii Stepasiuk – 1.6.0
Health Check & Troubleshooting: Autor: Komunita WordPressu – 1.5.1
Limit Login Attempts Reloaded: Autor: Limit Login Attempts Reloaded – 2.25.8
Markup by Attribute for WooCommerce: Autor: MarkTomlinson – 3.11.0
Otter – Page Builder Blocks & Extensions for Gutenberg: Autor: ThemeIsle – 2.1.3
Temporary Login Without Password: Autor: StoreApps – 1.8.0
Toret Telefon: Autor: toret.cz – 1.0.3
Toret České oslovení: Autor: Toret.cz – 1.1.0
Toret Zásilkovna: Autor: Toret.cz – 5.11.1
TranslatePress - Multilingual: Autor: Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.4.1

UpdraftPlus - Backup/Restore: Autor: UpdraftPlus.Com
DavidAnderson – 1.22.23

BEAR – Hromadný editor a produktový manažer Professional pro WooCommerce: Autor: realmag777 – 1.1.2
Woo GoPay Inline: Autor: Toret.cz – 2.2.12
Toret iDoklad: Autor: toret.cz – 2.2.0
WooCommerce Google Analytics Integration: Autor: WooCommerce – 1.5.17
Product Variation Swatches for WooCommerce (Pro): Autor: ThemeHigh – 2.2.0
WooCommerce: Autor: Automattic – 7.1.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: Autor: Themeisle – 2.6.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: Autor: Automattic – 5.0.1
Duplicator: Autor: Snap Creek – 1.5.0
Hello Dolly: Autor: Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Obchod: #9 - /obchod/
Košík: #10 - /kosik/
Pokladna: #11 - /pokladna/
Můj účet: #12 - /muj-ucet/
Obchodní podmínky: #3050 - /obchodni-podminky/

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-16 15:36:35 +00:00
Options: ✔
Notes: 82
Onboarding: skipped

### Action Scheduler ###

Dokončeno: 560
Oldest: 2022-10-16 09:25:43 +0000
Newest: 2022-11-15 17:07:42 +0000

Čekající: 1
Oldest: 2022-11-16 16:09:12 +0000
Newest: 2022-11-16 16:09:12 +0000

### Status report information ###

Generated at: 2022-11-15 17:26:41 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @pschonmann,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1 version. 

Please find below the screenshot for reference :
![#35593](https://user-images.githubusercontent.com/94531721/202124776-7d542363-513b-49ec-b49c-c40dd135988e.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
@pschonmann Were you able to reproduce this issue with only WooCommerce active?
