### ISSUE TITLE
`ObjectCache::set()`: Optional parameter `$id` declared before required parameter `$object`

### ISSUE THREAD

**Issue by swissspidy** [woothemes/woocommerce#35600]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the `ObjectCache::set()` method, the first parameter `$id` is declared optional, and the second parameter `$object` is required. Thus, `$id` is implicitly treated as a required parameter.

This is deprecated since PHP 8.0

See https://php.watch/versions/8.0/deprecate-required-param-after-optional

https://github.com/woocommerce/woocommerce/blob/42d2260ca691c4b0422088199d3f6fdfba56c529/plugins/woocommerce/src/Caching/ObjectCache.php#L173

The solution is basically:

```diff
-public function set( $id = null, $object, int $expiration = self::DEFAULT_EXPIRATION ): bool {
+public function set( $id, $object, int $expiration = self::DEFAULT_EXPIRATION ): bool {
```

### Expected behavior

No required params after optional ones.

### Actual behavior

Deprecation notices due to improper usage.

### Steps to reproduce

Turn on logging and use `ObjectCache::id()` on a PHP 8 environment.

### WordPress Environment

WordPress 6.1 / PHP 8.0+

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
This was already addressed and the order of the arguments was also altered, the current signature of the method is:

```
public function set( $object, $id = null, int $expiration = self::DEFAULT_EXPIRATION ): bool 
```
