### ISSUE TITLE
[Enhancement]: Remove email/telephone from customer emails

### ISSUE THREAD

**Issue by alpha-pix** [woothemes/woocommerce#35604]
### Describe the solution you'd like

Remove the customer email and telephone number from customer emails. These are unecessary and in the case of the telephone number it introduces a small security risk that is not outweighed by any utility. Other platforms such as Shopify do not include this information. 

### Describe alternatives you've considered

I could edit email templates but this is a solution that is better done by default.

**Comment by KoolPal** [comment]
As a store owner I disagree. We have had numerous customer writing back to asking for corrections in their phone numbers (which is used for shipping purposes) once they see that they have done a typo during checkout!
