### ISSUE TITLE
[Enhancement]: wc_get_template_part passing variable

### ISSUE THREAD

**Issue by ngdangtu-vn** [woothemes/woocommerce#35636]
### Describe the solution you'd like

`wc_get_template_part` should accept the third param as passing variable. Simply make its interface looks like [the core function](https://developer.wordpress.org/reference/functions/get_template_part).

### Describe alternatives you've considered

I have to use `global $product` which I usually try to avoid in my work.

### Additional context

I think I can do this. Please assign me this task.

**Comment by psealock** [comment]
Thanks @ngdangtu-vn, looking forward to your contribution

**Comment by barryhughes** [comment]
Closing as per discussion in the [linked PR](https://github.com/woocommerce/woocommerce/pull/35736).
