### ISSUE TITLE
Analytics/WCPay: Advanced filtering date selection does not work on WordPress 6.1

### ISSUE THREAD

**Issue by alefesouza** [woothemes/woocommerce#35630]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While debugging https://github.com/Automattic/woocommerce-payments/issues/5073 we've noticed a bug that occur only on WordPress 6.1 due to its `moment` package drop on https://github.com/WordPress/gutenberg/pull/43005, all datepickers on WCPay stopped working on WP 6.1 even on old versions and ~it should be happening to all pages and plugins that uses the `DatePicker` component from `@woocommerce/components` package~ it happens for any use of advanced filtering date selection, such as on the Transactions and Disputes pages of WCPay.

_Update: This only currently happens for the advanced filtering date selection as found on the Transactions and Disputes pages of WCPay. It does not happen for other usages of `DatePicker`. @mattsherman_

![](https://user-images.githubusercontent.com/41110392/200596335-49ff344f-6359-4aed-90ca-92cd5a60a1cf.gif)

### Expected behavior

Change the dates without any error.

### Actual behavior

An error occur after change dates, also hides the entire page due to React error handling.

### Steps to reproduce

1. On WP 6.1, ~find a page that uses WooCommerce DatePicker (or~ install WCPay and use the Date filter on Transactions or Disputes page ~)~.
2. Select a date.
3. Click again on the DatePicker, a error should be shown hiding the entire page.

### WordPress Environment

WordPress address (URL): http://localhost:8082
Site address (URL): http://localhost:8082
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 22.72MB
Database Data Size: 12.79MB
Database Index Size: 9.93MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.47MB + Index: 0.38MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mail_catcher_logs: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_orders: Data: 0.23MB + Index: 0.08MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 10
post: 2
product: 28
product_variation: 7
revision: 4
shop_order: 522
shop_order_refund: 3
shop_subscription: 160
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (8) ###

Code Snippets: by Code Snippets Pro – 3.2.0
WooCommerce Blocks: by Automattic – 7.2.0
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.14.4
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.0.3
WooCommerce Pre-Orders: by WooCommerce – 1.8.0
WooCommerce: by Automattic – 7.1.0
Mail logging - WP Mail Catcher: by James Ward – 2.0.4

### Inactive Plugins (8) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Admin: by WooCommerce – 3.4.0-dev
WooCommerce Deposits: by WooCommerce – 1.6.2
WooCommerce PayFast Gateway: by WooCommerce – 1.4.25
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.12
WooCommerce Subscriptions: by WooCommerce – 4.2.0
WordPress Importer: by wordpressdotorg – 0.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #160 - /shortcode-checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.0.0 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: http://woopay-merchant.loca.lt
Subscription Statuses: wc-on-hold: 112
wc-cancelled: 48

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-cancelled: 3
wc-on-hold: 1

WooCommerce Payments: wc-cancelled: 45
wc-on-hold: 111

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-18 16:15:48 +00:00
Options: ✔
Notes: 85
Onboarding: completed

### WooCommerce Payments ###

Version: 5.0.3
Connected to WPCOM: Yes
Blog ID: 204048669
Account ID: acct_1KfmJBR3icXCJd5X

### Action Scheduler ###

Complete: 325
Oldest: 2022-11-10 18:42:07 +0000
Newest: 2022-11-17 23:32:27 +0000

Failed: 125
Oldest: 2022-03-31 22:38:41 +0000
Newest: 2022-09-01 00:22:32 +0000

Pending: 1
Oldest: 2022-11-18 22:24:52 +0000
Newest: 2022-11-18 22:24:52 +0000

### Status report information ###

Generated at: 2022-11-18 01:12:13 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by sukafia** [comment]
The issue extends to the date-picker in the Analytics:

![Wacdp7.gif](https://user-images.githubusercontent.com/60121732/202670571-0e7afb26-715b-431d-96f0-46cbdcfc0dbf.gif)

5721995-zen

**Comment by mattsherman** [comment]
@sukafia I believe that to be a distinct, but possibly related, issue.

**Comment by mattsherman** [comment]
> The issue extends to the date-picker in the Analytics:
> 
> ![Wacdp7.gif](https://user-images.githubusercontent.com/60121732/202670571-0e7afb26-715b-431d-96f0-46cbdcfc0dbf.gif)
> 
> 5721995-zen

I have opened a separate issue for the custom date range calendar styling: https://github.com/woocommerce/woocommerce/issues/35645
