### ISSUE TITLE
Explore Storybook plugins

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#35640]
**Issue Description:**

This is a spike to spent some time to explore different Storybook plugins, to see which one's would be usefull for us and would make storybooks even more useful.

We should timebox this to 2 day's.

Some items for consideration:
- Are their plugins that would allow us to organize the components better
- Display and extract example information from comments

**Comment by louwie17** [comment]
[Chromatic](https://www.chromatic.com/) seems like an interesting option, as suggested by @jarekmorawski in Slack.

**Comment by octaedro** [comment]
Hey @mdperez86,
I know you have been doing some research related to plugins that would help us. Would you happen to have any recommendations for plugins we should use?
Thanks!

**Comment by louwie17** [comment]
Not relevant anymore - closing.
