### ISSUE TITLE
[Enhancement]: Gutenberg in product description, backend UI and Analytics

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#35646]
### Describe the solution you'd like

I am a store owner who really loves WooCommerce. However there are a few small issues that I'd like to point out.

1. I would love to get Gutenberg in the product description. It would be great to add icons, accordions, columns, background colors and other graphical elements to the product description (even shopify figured it out: https://www.lovehair.com/products/ultimate-bundle) and Gutenberg works great for that. I enabled Gutenberg in the product description with a PHP snippet, but by not being officially supported it has a couple of issues: for example, the new WooCommerce navigation experience is not compatible with that.
2. I really like the new WooCommerce navigation experience and I really like the styling of the table in the "customers" page ([sitename.com/wp-admin/admin.php?page=wc-admin&path=%2Fcustomers](http://sitename.com/wp-admin/admin.php?page=wc-admin&path=%2Fcustomers)). It has a nice UI, it's possible to filter and sort without reloading the page, it is possible to export. Why isn't the Orders ([sitename.com/wp-admin/edit.php?post_type=shop_order](http://sitename.com/wp-admin/edit.php?post_type=shop_order)) table not styled the same? It has the old wordpress UI, it refreshed every time you try to filter or sort it and it's not possible to export orders in CSV. I need to install a plugin for such a simple feature.
3. Add page view, reached checkout and abandoned carts in the Analytics. It's such an inconvenience to always check Google Analytics just to see how many Abandoned carts I have

**Comment by tomxygen** [comment]
@psealock Hello, I saw you've added the "prioritization" status.
Could you please let me know on the three suggestions I gave, which are being worked on?
Thank you!

**Comment by AnnaMag** [comment]
Thank you for opening the issue @tomxygen.

I will close the issue for now.  Part 1 is our current focus, while 2+3 are not part of the roadmap at this time.
