### ISSUE TITLE
Analytics: Custom date range calendar styling is broken in WordPress 6.1

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#35645]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The custom date range calendar's styling on Analytics pages is broken in WordPress 6.1.

### Expected behavior

The custom date range calendar is styled properly.

### Actual behavior

The custom date range calendar's styling is broken.

![image](https://user-images.githubusercontent.com/2098816/202836113-341c7144-cea8-4aa0-a818-150fce24862c.png)

### Steps to reproduce

1. Go to any Analytics page.
2. Click on the "Date range" and click "Custom".
3. Observe that the calendar styling is broken (see above).

### WordPress Environment

WordPress 6.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
The styles we are depending on were previously included in `@wordpress/components` and were removed in:

https://github.com/WordPress/gutenberg/commit/c1f96c2d23b539e33168a0ba4a9f96b7b535c43c

We will need to add them directly to our included CSS.

**Comment by cena** [comment]
5727380-zen

**Comment by sukafia** [comment]
5737886-zen

**Comment by sukafia** [comment]
5721995-zen

**Comment by felipevelzani** [comment]
5770036-zen
