### ISSUE TITLE
Options/variations management experience phase 1

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35656]
**Description:** this epic includes all the issues that should be part of the 1st implementation phase of the variations management experience:
Options tab/screen
Add product options flow
Auto-creation of variations
Variations list with pagination
Manage individual variations flow
Quick actions

**Comment by tomxygen** [comment]
@pmcpinto Is Woocommerce changing the variation management experience anytime soon?

**Comment by pmcpinto** [comment]
> Is Woocommerce changing the variation management experience anytime soon?

We're exploring a new flow, but we still don't have an ETA of when it will be available for testing. Stay tuned! Thanks

**Comment by tomxygen** [comment]
@pmcpinto thank you for the update.
Is there a list of other improvements that Woocommerce is working on? (not related to the variation management)

**Comment by pmcpinto** [comment]
> Is there a list of other improvements that Woocommerce is working on? (not related to the variation management)

Are talking about improvements targeting any part of WooCommerce Core?

**Comment by tomxygen** [comment]
@pmcpinto any part in general.
I am a store owner and I wish to get improvements in some areas such as gutenberg in product description to add accordions, graphics, columns, sections, background colors etc in product description
I have enabled Gutenberg in product description with a PHP snippet but unfortunately it's not compatible with the new WooCommerce navigation experience that I would really like to use.
Talking about that, I like it's modern UI, but I would like it to be taken further. All the Woocommerce backend elements should be redesigned with that navigation experience in mind.
Also, the "Customers" page features a nice table with the new table UI, it can be filtered and ordered without reloading the page.
Why does the "orders" page have the old table UI?

**Comment by pmcpinto** [comment]
Closing this in favor of #38846
