### ISSUE TITLE
Registering by email allows special characters

### ISSUE THREAD

**Issue by Terrox** [woothemes/woocommerce#35668]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Registering by Email from the Login page from this option: "Allow customers to create an account on the "My account" page"
allows % character in email address.

### Expected behavior

Email should be sanitised by default wordpress sanitize_email() function.

### Actual behavior

Is not sanitised. email%20@example.com is saved as email%20@example.com in database.

### Steps to reproduce

1. enable WooCommerce settings->Accounts & Privacy -> Account Creation -> Allow customers to create an account on the "My account" page
2. visit /my-account/
3. register by email address email%20@example.com
4. see email address in user account is not stripped of % symbol

### WordPress Environment

WooCommerce Version 7.1.0
Wordpress 6.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @Terrox,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/203715046-41c34acf-f8d4-4422-b6f1-f710a10678ae.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by 79mplus-admin** [comment]
`%` is a valid character in email address. sanitize_email() function doesn't strip this character.

**Comment by Terrox** [comment]
> `%` is a valid character in email address. sanitize_email() function doesn't strip this character.

I would think that if the email ends up in a url there will be translation to a url character, such %40 = @ and that seems bad.  And all sorts of encoding gotchas in mailto: uri.

But if it's legal it's legal I guess, depending on which RFC it's using.

**Comment by coreymckrill** [comment]
Given that we're using WordPress's `sanitize_email` function here, this probably isn't the right venue to question the set of characters considered valid for email addresses. Could be a topic for a [Core ticket](https://core.trac.wordpress.org/), though.
