### ISSUE TITLE
State "transport" disappeared. Orders in shipping state no longer appear in the Orders Dashboard

### ISSUE THREAD

**Issue by nathanferla** [woothemes/woocommerce#35664]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

State "transport" disappeared. Orders in shipping state no longer appear in the Orders Dashboard

### Expected behavior

There are 30 commands in total

### Actual behavior

There are 10 commands that are not showing up. These are the commands in "transporting" state. How to reactivate them please

### Steps to reproduce

![Capture d’écran 2022-11-22 à 00 08 29](https://user-images.githubusercontent.com/35003825/203176286-abc7230b-ae2c-4cdc-9914-7b8224e29333.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bulteauservices.com
Site address (URL): https://bulteauservices.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 000 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 898 Mo
PHP Time Limit: 900
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.36-MariaDB-0+deb10u2
Max Upload Size: 896 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: GlfzEo6_
Taille totale de la base de données: 47.98MB
Taille de la base de données: 42.91MB
Taille de l’index: 5.07MB
GlfzEo6_woocommerce_sessions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_woocommerce_order_itemmeta: Données : 0.08MB + Index : 0.11MB + Moteur InnoDB
GlfzEo6_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_actionscheduler_actions: Données : 2.02MB + Index : 0.48MB + Moteur InnoDB
GlfzEo6_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_actionscheduler_logs: Données : 2.02MB + Index : 0.25MB + Moteur InnoDB
GlfzEo6_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_comments: Données : 0.05MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_ewwwio_images: Données : 0.20MB + Index : 0.16MB + Moteur InnoDB
GlfzEo6_ewwwio_queue: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_e_submissions: Données : 0.02MB + Index : 0.27MB + Moteur InnoDB
GlfzEo6_e_submissions_actions_log: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
GlfzEo6_e_submissions_values: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_gla_budget_recommendations: Données : 0.20MB + Index : 0.11MB + Moteur InnoDB
GlfzEo6_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_litespeed_img_optming: Données : 0.05MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_options: Données : 12.05MB + Index : 0.36MB + Moteur InnoDB
GlfzEo6_postmeta: Données : 4.39MB + Index : 0.45MB + Moteur InnoDB
GlfzEo6_posts: Données : 1.52MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_revslider_css: Données : 0.13MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_css_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_layer_animations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_revslider_layer_animations_bkp: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_revslider_navigations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_revslider_navigations_bkp: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_revslider_sliders: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_sliders_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_slides: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_slides_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_static_slides: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_revslider_static_slides_bkp: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_tm_taskmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_tm_tasks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_usermeta: Données : 0.14MB + Index : 0.14MB + Moteur InnoDB
GlfzEo6_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_wcpdf_invoice_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wcpdf_packing_slip_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_wc_order_bundle_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wfblockediplog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_wfconfig: Données : 1.38MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wffilemods: Données : 10.52MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfhits: Données : 0.25MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_wfknownfilelist: Données : 5.52MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wflogins: Données : 0.16MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
GlfzEo6_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_wfstatus: Données : 0.13MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_woocommerce_bundled_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woocommerce_bundled_items: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_woodmart_wishlists: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
GlfzEo6_woodmart_wishlist_products: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_yoast_indexable: Données : 0.20MB + Index : 0.09MB + Moteur InnoDB
GlfzEo6_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
GlfzEo6_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
GlfzEo6_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
GlfzEo6_yoast_prominent_words: Données : 0.06MB + Index : 0.13MB + Moteur InnoDB
GlfzEo6_yoast_seo_links: Données : 0.08MB + Index : 0.06MB + Moteur InnoDB

### Post Type Counts ###

addify_quote: 6
addify_rfq: 1
addify_rfq_fields: 8
attachment: 136
cms_block: 17
elementor_library: 5
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 49
page: 21
post: 1
product: 10
product_variation: 2
revision: 40
shop_order: 32
shop_order_refund: 2
whatsapp-accounts: 1
woodmart_layout: 2
woodmart_sidebar: 1
woodmart_size_guide: 1
wp_global_styles: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

WooCommerce Monetico Paiement: par Monetico Paiement – 1.0.0
Contact Form 7: par Takayuki Miyoshi – 5.6.4
Elementor Pro: par Elementor.com – 3.8.0
Elementor: par Elementor.com – 3.8.0
EWWW Image Optimizer: par Exactement WWW – 6.9.2
Get a Quote Button for WooCommerce: par wpbean – 1.2.4
Google Listings and Ads: par WooCommerce – 2.2.1
Site Kit by Google: par Google – 1.88.0
Loco Translate: par Tim Whitlock – 2.6.3
Wordfence Security: par Wordfence – 7.7.1
WooCommerce AJAX Cart: par Moises Heberle – 1.3.24
WooCommerce: par Automattic – 7.1.0
Woodmart Core: par  – 1.0.35
Yoast SEO: par L’équipe Yoast – 19.10
WP-Optimize - Nettoyer, compresser, mettre en cache.: par David Anderson
Ruhani Rabin
équipe Updraft – 3.2.9

WPS Hide Login: par WPServeur
NicolasKulka
wpformation – 1.9.6

Yoast SEO : WooCommerce: par L’équipe Yoast – 13.9

### Inactive Plugins (2) ###

WooCommerce Measurement Price Calculator: par SkyVerge – 3.20.2
WooCommerce Product Bundles: par WooCommerce – 6.17.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base de la boutique: #10 - /shop/
Panier: #11 - /panier/
Commander: #12 - /commander/
Mon compte: #13 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.0.4
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-22 07:47:38 +00:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Annulé: 1
Oldest: 2022-10-31 10:37:07 +0000
Newest: 2022-10-31 10:37:07 +0000

Terminé: 1 208
Oldest: 2022-11-11 16:29:08 +0000
Newest: 2022-11-21 17:01:05 +0000

Échoué: 18
Oldest: 2022-09-28 18:16:43 +0000
Newest: 2022-11-11 17:06:19 +0000

En attente: 5
Oldest: 2022-11-22 03:00:00 +0000
Newest: 2022-11-28 16:10:49 +0000

### Status report information ###

Generated at: 2022-11-21 23:05:47 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
@nathanferla,

Thanks for the report. Can you please confirm that you're able to reproduce this issue when only the WooCommerce plugin is active? It appears that you may have several other plugins active. If you're still able to reproduce this issue with only WooCommerce active, could you please provide a list of steps that we may be able to follow to reproduce the issue?
