### ISSUE TITLE
WooCommerce Memberships - woo-nav-tab-wrapper set to display:none

### ISSUE THREAD

**Issue by Murphy1976** [woothemes/woocommerce#35673]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After a recent update to WooCommerce - Memberships, now the Tab Nav at the top of the Memberships section has an inline style of display:none. Unless I go into DevTools and manually remove that style I cannot access Membership Plans, Import/Export or Profile Fields.

It was driving me nuts trying to figure out what happened to all my membership plans even though I could still access them via each individual member. 

### Expected behavior

The ".woo-nav-tab-wrapper" should be visible, and not have a inline style of "display:none"

### Actual behavior

In Dev Tools, I see this:
<h2 class="nav-tab-wrapper woo-nav-tab-wrapper" style="display: none;">

### Steps to reproduce

I don't know if this is just MY instance of Woocommerce Memberships, but:

1. Log In
2. Click WooCommerce
3. Click Memberships

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://xxautumnivyxx.com
Site address (URL): https://xxautumnivyxx.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 516 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.86.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: ai_
Total Database Size: 28.86MB
Database Data Size: 24.68MB
Database Index Size: 4.18MB
ai_woocommerce_sessions: Data: 7.02MB + Index: 0.28MB + Engine InnoDB
ai_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ai_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ai_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
ai_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
ai_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_aiowps_failed_logins: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ai_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
ai_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ai_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ai_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
ai_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_options: Data: 5.33MB + Index: 0.19MB + Engine InnoDB
ai_postmeta: Data: 2.52MB + Index: 0.50MB + Engine InnoDB
ai_posts: Data: 3.50MB + Index: 0.22MB + Engine InnoDB
ai_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
ai_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_revslider_slides: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
ai_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
ai_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ai_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
ai_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ai_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ai_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ai_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ai_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ai_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ai_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fastmoney1: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fastmoney2: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fastmoney_1: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fastmoney_2: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fm_timer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
globals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
host: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
players: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__bookmark: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__central_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__column_info: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__designer_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__export_templates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__favorite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__navigationhiding: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__pdf_pages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__recent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__relation: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__savedsearches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pma__table_coords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__table_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__table_uiprefs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__userconfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__usergroups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pma__users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
puzzle1: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
puzzle10: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle2: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle3: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle4: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle5: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle6: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle7: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle8: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
puzzle9: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
question: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
roster: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
round1: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
round2: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
round3: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story01: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story02: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story03: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story04: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story05: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story06: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story07: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story08: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
story09: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
survey_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 629
br_products_of_day: 1
carousels: 1
custom_css: 1
customize_changeset: 20
mailpoet_page: 1
ml-slide: 14
ml-slider: 1
nav_menu_item: 76
page: 37
portfolio: 16
post: 11
product: 117
revision: 463
sa_slider: 2
seedprod: 1
shop_coupon: 1
shop_order: 2
testimonials: 4
ttshowcase: 4
vc_grid_item: 4
wc_membership_plan: 5
wc_user_membership: 5
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Redux: by Extendify – 4.3.0
360° Video Panorama for Visual Composer: by UsefulPixels – 1.0
Age Verification Popup: by KoalaApps – 1.0.3
Akismet Anti-Spam: by Automattic – 5.0.1
All In One WP Security: by All In One WP Security & Firewall Team – 5.1.1
Carousel Slider: by Sayful Islam – 2.1.1
Child Theme Configurator: by Lilaea Media – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.6.4
Default featured image: by Jan Willem Oostendorp – 1.7.2.1
Disable Gutenberg: by Jeff Starr – 2.8.1
Duplicator: by Snap Creek – 1.5.1
Google Listings and Ads: by WooCommerce – 2.3.1
Hide Categories and Products for Woocommerce: by N.O.U.S. Open Useful and Simple – 1.2.5
Social Feed Gallery: by QuadLayers – 3.4.8
Social Slider Feed: by creativemotion – 2.1.0
Jetpack: by Automattic – 11.5.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.7.0
MailPoet: by MailPoet – 4.0.1
Maintenance: by WebFactory Ltd – 4.06
MetaSlider: by MetaSlider – 3.27.14
Photo Sphere for Visual Composer: by UsefulPixels – 1.1
Pinterest for WooCommerce: by WooCommerce – 1.2.6
Slider Revolution: by ThemePunch – 5.4.7.3
Search Exclude: by Roman Pronskiy – 1.3.0
Spreaker Shortcode: by Spreaker – 1.8.0
Testimonials Showcase: by Carlos Moreira – 1.1.3
Twitter: by Twitter – 2.0.5
Ultimate Carousel For WPBakery Page Builder: by Nasir – 2.6
User Menus: by Code Atlantic – 1.3.1
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Memberships: by SkyVerge – 1.22.3
WooCommerce Payments: by Automattic – 5.0.3
WooCommerce Shipping & Tax: by WooCommerce – 2.0.0
WooCommerce: by Automattic – 7.1.0
WordPress Importer: by wordpressdotorg – 0.8
WP Fastest Cache: by Emre Vona – 1.0.8
WP User Avatars: by Triple J Software
Inc. – 1.4.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #613 - /shop/
Cart: #1746 - /cart/
Checkout: #1747 - /checkout/
My account: #1748 - /my-account/
Terms and conditions: #1806 - /terms/

### Theme ###

Name: Modo Child
Version: 1.1.4
Author URL: http://useful-pixels.com/
Child Theme: ✔
Parent Theme Name: Modo
Parent Theme Version: 2.2
Parent Theme Author URL: http://useful-pixels.com/
WooCommerce Support: ✔

### Templates ###

Overrides: modo/woocommerce/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0
modo/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Memberships ###

Restriction mode:: Redirect to page
Public content:: Products: 4 itemsPages: 1 item
Excluded from discounts:: –
Membership plans:: 4
Legion - Scribe Of The Naughty:: Members: 1Access method: Product(s) purchaseAccess length: Specific length (1 months)
Legion - God/dess:: Members: 1Access method: Product(s) purchaseAccess length: Specific length (1 years)
Legion - Tactician:: Members: 1Access method: Product(s) purchaseAccess length: Specific length (1 years)
Legion - Soldier:: Members: 1Access method: Product(s) purchaseAccess length: Specific length (1 months)

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://xxautumnivyxx.com
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Arizona

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-23 13:52:34 +00:00
Options: ✔
Notes: 93
Onboarding: completed

### WooCommerce Payments ###

Version: 5.0.3
Connected to WPCOM: Yes
Blog ID: 205486813
Account ID: acct_1Lpkg4CON6qeExfu

### Action Scheduler ###

Complete: 533
Oldest: 2022-10-22 17:55:51 +0000
Newest: 2022-11-22 14:24:04 +0000

Failed: 5
Oldest: 2022-11-04 13:36:10 +0000
Newest: 2022-11-15 04:36:45 +0000

Pending: 12
Oldest: 2022-11-22 15:24:04 +0000
Newest: 2023-11-22 00:00:00 +0000

### Status report information ###

Generated at: 2022-11-22 14:31:52 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Murphy1976 ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin WooCommerce Memberships.

Please contact the author of the plugin directly for further help.
