### ISSUE TITLE
AT Sites: Modal about Woocommerce Mobile App Shows Existing Connection Notice

### ISSUE THREAD

**Issue by igotdes** [woothemes/woocommerce#35682]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Clicking on “Get the free WooCommerce mobile app” on an AT site results in a "WooCommerce mobile app can currently only be registered to a single WordPress.com account" notice.

### Expected behavior

The messaging for AT site owners could perhaps be changed to something more relevant to their setup.

### Actual behavior

The notice shows up even if:

- There is only one user on the site
- Multiple admins and/or store managers can manage a single store from the WooCommerce mobile app:
  - [Multiple Store Admins on Android](https://woocommerce.com/document/android/#multiple-store-admins)
  - [Multiple Store Admins on iOS](https://woocommerce.com/document/woocommerce-ios/#multiple-store-admins)

### Steps to reproduce

1. On an AT site, go to WP Admin > WooCommerce > Home
2. Look for the “Things to do next” section
3. Click on "Get the free WooCommerce mobile app"

Alternatively, head to [AT_SITE_URL]/wp-admin/admin.php?page=wc-admin&mobileAppModal=true

A modal saying "WooCommerce mobile app can currently only be registered to a single WordPress.com account" will pop up:

![Markup on 2022-11-23 at 11:33:14](https://user-images.githubusercontent.com/74066241/203465887-f6b1e991-8f2d-460a-8d82-c1dd61a4e7a9.png)

### WordPress Environment

WordPress address (URL): https://[...].wpcomstaging.com
Site address (URL): https://[...].wpcomstaging.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by igotdes** [comment]
This was also reported on #5733621-zen and discussed in p1669169025831119-slack-C6H8C3G23.

The relevant code appears to be from [this PR](https://github.com/woocommerce/woocommerce/pull/34653).

**Comment by chihsuan** [comment]
Closing this. The mobile app modal has been updated in https://github.com/woocommerce/woocommerce/pull/40613 and notice is no longer used.
