### ISSUE TITLE
[Enhancement]: Make the last remaining fields 50% wide

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35686]
### Describe the solution you'd like

It's great that we've updated the width for most fields to 50%, but there are still a few that are 100%. Let's make them 50% to save space and make the UI feel "lighter".

<img width="760" alt="image" src="https://user-images.githubusercontent.com/79307566/203552390-1be1738c-5e6a-4b28-bcde-3cc6bf310655.png">

**Acceptance criteria**

- [ ] [Pricing] When the schedule sale toggle is on, the `From` and `To` fields are 50% wide.
- [ ] [Inventory] When quantity tracking is enabled, the `Current quantity` and `Email me when the quantity reaches` fields are 50% wide.

**Comment by jarekmorawski** [comment]
Can we prioritize this issue? It looks like an easy win. cc @pmcpinto @AnnaMag

**Comment by pmcpinto** [comment]
I'll include it in the next cycle for prioritization. Is this going to be affected by the visual changes?
