### ISSUE TITLE
[Fix] Remove double scroll in the form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35688]
**Bug Description:**

A second scroll bar appears after publishing a product. It's only present near the top and bottom of the form, forcing the user to do an extra scroll to move up and down the page. See the video below.

https://user-images.githubusercontent.com/79307566/203555952-869a8d68-0b94-426a-a70c-4418e44e2d02.mov

**Comment by pmcpinto** [comment]
Fixed in the new experience
