### ISSUE TITLE
[Enhancement]: Allow users to resize the summary and description fields

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35685]
### Describe the solution you'd like

The summary and description fields can become quite content-heavy, especially with all the blocks. Let's make them fixed height (current values), but let the users resize the fields as they see fit using a handle like the one below.

<img width="126" alt="image" src="https://user-images.githubusercontent.com/79307566/203551681-f3dec272-d734-4360-abe7-c0db65c76fb0.png">

**Acceptance criteria**

- [ ] Summary and Description fields have fixed heights.
- [ ] The user can resize the window vertically using a drag handle in the bottom right corner.

**Comment by pmcpinto** [comment]
I'll close this issue, as this is included in the AC of the summary/description epic created this week
