### ISSUE TITLE
New Order Notifications Failing

### ISSUE THREAD

**Issue by mshane8** [woothemes/woocommerce#35699]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello - 
I already started a ticket with Woo and was directed here. Ticket #(5728315).

New Order Notifications are failing to send to admin. ONLY New Order notifications. All other notifications are sending fine. 

I have a php mailer script outside of WordPress and it tests fine 100% of the time. 

https://www.latherandfizz.com/mail_test.php

I also receive site notifications fine outside of woocommerce - form entries, new user notifications, account notifications etc... 
So the issue ONLY resides in WP and in WOO for NEW ORDER NOTIFICATIONS. The error from WP Mail Log is ""failing to initiate mailer function"

This is important as we obviously need to be notified of new orders. Notifications were working fine no problem until this randomly started. No application updates were done prior to this stopping to work. 

### Expected behavior

WOO NEW ORDER notifications triggered and leaving site. 

### Actual behavior

Notifications fails to send with error "failing to initiate mailer function"

### Steps to reproduce

check mail log on site.

any new order that is processed fails to send with an alert. 

login credentials already sent to woo under ticket number above

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.latherandfizz.com
Site address (URL): https://www.latherandfizz.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.6 - There is a newer version of WordPress available (6.1.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.39-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 164.82MB
Database Data Size: 146.43MB
Database Index Size: 18.39MB
wp_woocommerce_sessions: Data: 36.06MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.27MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_fw_requests: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_banners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_comments: Data: 1.48MB + Index: 0.84MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fusion_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fusion_form_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fusion_form_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fusion_form_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.16MB + Index: 0.27MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.42MB + Index: 0.14MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_layerslider: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 11.09MB + Index: 2.08MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 4.22MB + Index: 0.50MB + Engine InnoDB
wp_relevanssi: Data: 4.52MB + Index: 5.55MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 53.26MB + Index: 0.84MB + Engine MyISAM
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_gc_cards: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 22.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 894
fusion_element: 1
nav_menu_item: 74
oembed_cache: 4
page: 11
post: 4
product: 412
product_variation: 381
revision: 171
shop_order: 1173
shop_order_refund: 15
slide: 3
wafs: 1
wpcf7_contact_form: 2
wphash_ntf_bar: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Gravity Forms: by Gravity Forms – 2.6.8
LayerSlider: by Kreatura Media – 7.2.4
All-in-One WP Migration Unlimited Extension: by ServMask – 2.47
All-in-One WP Migration: by ServMask – 7.68
Classic Widgets: by WordPress Contributors – 0.3
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.5
Avada Builder: by ThemeFusion – 3.3
Avada Core: by ThemeFusion – 5.3
GA Google Analytics: by Jeff Starr – 20221016
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.1
Health Check & Troubleshooting: by The WordPress.org community – 1.5.1
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.84
Really Simple SSL: by Really Simple Plugins – 5.3.5
Relevanssi: by Mikko Saari – 4.18.0
Slider Revolution: by ThemePunch – 5.4.8
Simple Banner: by Ryan Petersen – 2.12.1
UberMenu - Icons Extension: by Chris Mavricos
SevenSpark – 3.4.4

UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.7.2

Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.3
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.5
WooCommerce Gift Cards: by SomewhereWarm – 1.5.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.23
WooCommerce Square: by WooCommerce – 3.2.0 (update to version 3.3.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.12
WooCommerce: by Automattic – 7.0.0 (update to version 7.1.0 is available)
WP Mail Logging: by Wysija – 1.10.4
YITH Infinite Scrolling: by YITH – 1.5.3

### Inactive Plugins (9) ###

Ajax Load More: by Darren Cooney – 5.5.4.1
Akismet Anti-Spam: by Automattic – 5.0.1
Breeze: by Cloudways – 2.0.7
Contact Form 7: by Takayuki Miyoshi – 5.5.6.1
Revision Control: by Dion Hulse – 2.3.2
SeedProd Coming Soon Pro: by SeedProd – 3.14.1
Wordfence Security: by Wordfence – 7.7.1
WP Mail SMTP: by WPForms – 3.6.1
Yoast SEO: by Team Yoast – 19.4

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.8.1
installatron_hide_status_test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #16564 - /cart/
Checkout: #16586 - /checkout/
My account: #16576 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Lather & Fizz Custom Theme
Version: 1.0.0
Author URL: https:www.mskdigitalmedia.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.3
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 3.5.5 is out of date. The core version is 6.1.0
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌
					
					
						Learn how to update

### Gift Cards ###

Database Version: 1.5.1
Loopback Test: ✔
Task Queueing Test: ✔

### Square ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-24 19:02:02 +00:00
Options: ✔
Notes: 110
Onboarding: completed

### Action Scheduler ###

Complete: 257
Oldest: 2022-11-18 23:50:44 +0000
Newest: 2022-11-23 19:20:01 +0000

Pending: 3
Oldest: 2022-11-23 20:16:01 +0000
Newest: 2022-11-28 14:00:59 +0000

### Status report information ###

Generated at: 2022-11-23 19:29:48 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @mshane8,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/204458633-b6c8b06f-ee08-4b5d-9d49-952816d82530.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by peterfabian** [comment]
Since we were unable to reproduce and haven't heard from the OP in a long time, I'm closing this issue. In case of any new findings, feel free to comment and we can reopen the issue. Thanks!
