### ISSUE TITLE
pricing showes Nan

### ISSUE THREAD

**Issue by VikiBenDavid** [woothemes/woocommerce#35702]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

![image](https://user-images.githubusercontent.com/108429003/203656822-a8e3648b-1d7d-466b-9a82-d4e737232f5f.png)

pricing showes Nan 

### Expected behavior

show the real price of the product

### Actual behavior

showes "nan"

### Steps to reproduce

1. add price to the product 
2. shows "nan"

### WordPress Environment

nothing helped 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @VikiBenDavid 

Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

**Comment by brittanygray902** [comment]
Seeing similar case here hc-37114552 follow up zd-5891326

User sees "Nan" on products

<img width="1170" alt="Screen Shot 2023-01-23 at 5 48 35 PM" src="https://user-images.githubusercontent.com/80774825/214189289-ff28b6fe-c3ea-42ef-89b9-d1799d22c2a9.png">

We attempted troubleshooting plugins & their theme but neither helped. The issue still persists with WordPress themes set and with plugins deactivated.
