### ISSUE TITLE
[Enhancement]: move file picker by clicking card into the MediaUploader component

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#35714]
### Describe the solution you'd like

Move the logic to open the [file picker by clicking the card](https://github.com/woocommerce/woocommerce/blob/add/35183_open_file_picker_by_clicking_card/plugins/woocommerce-admin/client/products/sections/images-section.tsx#L188-L271) into the [`MediaUploader` component](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/media-uploader).

Since all media upload components will have the same behavior of file uploading by clicking the card, we want to move that logic into the component.

More details [here](https://github.com/woocommerce/woocommerce/pull/35358#discussion_r1028155142).

**Comment by AnnaMag** [comment]
Could you include the estimation @octaedro , please?
