### ISSUE TITLE
WooCommerce Product Editor - Product short description collapsed by default?

### ISSUE THREAD

**Issue by NarfArf** [woothemes/woocommerce#35713]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I think this was newly introduced with WooCommerce 7.1. "Product short description" tab seems to have new behavior that wasn't documented in the changelog as far as I can tell. 😅

### Expected behavior

Historically, the "Product Short Description" area has been able to save it's "state" as expanded or collapsed.

![image](https://user-images.githubusercontent.com/17137821/203801788-cb951d9e-e38f-4ae7-a048-20c494a4ac14.png)

### Actual behavior

When editing a product in the WooCommerce backend (post.php), the "Product short description" tab is now collapsed by default.

Furthermore, the tab is **not** saved as expanded for the user profile after editing a product. 

![image](https://user-images.githubusercontent.com/17137821/203801967-1614cd20-5d04-440e-8049-91e3a1e4a998.png)

Changing the tab order still works fine though. 😀

### Steps to reproduce

1. Go to products -> edit a product
2. Expand the "Product short description" tab, make an edit and save product
3. "Product short description" tab does not save the state of being expanded, requiring user to expand every time they use the field.

### WordPress Environment

`
### wp-core ###

version: 6.1.1
site_language: da_DK
user_language: da_DK
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/gaverogstil/public_html
wordpress_size: 55,10 MB (57778830 bytes)
uploads_path: /home/gaverogstil/public_html/wp-content/uploads
uploads_size: 168,93 MB (177131264 bytes)
themes_path: /home/gaverogstil/public_html/wp-content/themes
themes_size: 31,46 MB (32984366 bytes)
plugins_path: /home/gaverogstil/public_html/wp-content/plugins
plugins_size: 173,90 MB (182349233 bytes)
database_size: 75,33 MB (78987264 bytes)
total_size: 504,71 MB (529230957 bytes)

### wp-active-theme ###

name: Woodmart Child (woodmart-child)
version: 1.0.0
author: XTemos delte et par to
author_website: http://xtemos.com
parent_theme: Woodmart (woodmart)
theme_features: core-block-patterns, woocommerce, wc-product-gallery-zoom, widgets-block-editor, post-thumbnails, post-formats, automatic-feed-links, title-tag, html5, menus, editor-style, widgets
theme_path: /home/gaverogstil/public_html/wp-content/themes/woodmart-child
auto_update: Deaktiveret

### wp-parent-theme ###

name: Woodmart (woodmart)
version: 6.1.4
author: XTemos delte et par to
author_website: http://themeforest.net/user/xtemos
theme_path: /home/gaverogstil/public_html/wp-content/themes/woodmart
auto_update: Deaktiveret

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.0, author: af WordPress-holdet, Autoopdateringer er deaktiveret

### wp-plugins-active (25) ###

avecdo for WooCommerce: version: 1.5.2, author: Modified Solutions ApS, Autoopdateringer er deaktiveret
Classic Editor: version: 1.6.2, author: WordPress Contributors, Autoopdateringer er deaktiveret
Classic Widgets: version: 0.3, author: WordPress Contributors, Autoopdateringer er deaktiveret
Elementor: version: 3.8.1, author: Elementor.com, Autoopdateringer er deaktiveret
Elementor Pro: version: 3.8.2, author: Elementor.com, Autoopdateringer er deaktiveret
Email Log: version: 2.4.8, author: Sudar, Autoopdateringer er deaktiveret
Gift Wrapper for WooCommerce: version: 3.2, author: FantasticPlugins, Autoopdateringer er deaktiveret
LiteSpeed Cache: version: 5.3, author: LiteSpeed Technologies, Autoopdateringer er deaktiveret
Loco Translate: version: 2.6.3, author: Tim Whitlock, Autoopdateringer er deaktiveret
Nets Easy for WooCommerce: version: 2.2.0, author: Krokedil, Autoopdateringer er deaktiveret
PDF Invoices & Packing Slips for WooCommerce: version: 3.2.4, author: WP Overnight (latest version: 3.2.5), Autoopdateringer er deaktiveret
PW WooCommerce Gift Cards Pro: version: 1.413, author: Pimwick, LLC (latest version: 1.415), Autoopdateringer er deaktiveret
Safe SVG: version: 2.0.3, author: 10up, Autoopdateringer er deaktiveret
Slider Revolution: version: 6.6.7, author: ThemePunch, Autoopdateringer er deaktiveret
Smart Send Shipping for WooCommerce: version: 8.0.26, author: Smart Send ApS, Autoopdateringer er deaktiveret
Ultimate Dashboard: version: 3.7.1.5, author: David Vongries, Autoopdateringer er deaktiveret
Ultimate Dashboard PRO: version: 3.6.4, author: David Vongries, Autoopdateringer er deaktiveret
WooCommerce: version: 7.1.0, author: Automattic, Autoopdateringer er deaktiveret
WooCommerce Product CSV Import Suite: version: 1.10.46, author: WooCommerce, Autoopdateringer er deaktiveret
Woo Discount Rules: version: 2.5.2, author: Flycart, Autoopdateringer er deaktiveret
Woo Discount Rules PRO 2.0: version: 2.5.2, author: Flycart, Autoopdateringer er deaktiveret
Woodmart Core: author: (undefined), version: 1.0.29, Autoopdateringer er deaktiveret
Wordfence Security: version: 7.7.1, author: Wordfence, Autoopdateringer er deaktiveret
WP Mail SMTP: version: 3.6.1, author: WPForms, Autoopdateringer er deaktiveret
Yoast SEO: version: 19.10, author: Team Yoast, Autoopdateringer er deaktiveret

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-13 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 37500
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 4.18.0-348.20.1.lve.1.el7h.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.0.25 64bit
php_sapi: litespeed
max_input_variables: 10000
time_limit: 1000
memory_limit: 4097M
max_input_time: -1
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 7.86.0 OpenSSL/1.1.1s
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.37-MariaDB
client_version: mysqlnd 8.0.25
max_allowed_packet: 268435456
max_connections: 5000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/gaverogstil/public_html/wp-content
WP_PLUGIN_DIR: /home/gaverogstil/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 4097M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Udefineret
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 3.6.1
license_key_type: lite
debug: No debug notices found.
lite_install_date: okt 8, 2021 @ 8:46am

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senff** [comment]
37714209-HC

**Comment by DoggieBoat** [comment]
This new "Feature" is an absolute pain. Not only is the "Short Description" (which is actually the MAIN description) field collapsed by default, it also when opened is unusably small so you have to expand it. As soon as you update or save the product, it collapses again, which means you have to repeat the whole rigmarole again, which just wastes time unnecessarily.

This needs to be fixed as a matter of urgency.

**Comment by jonathansadowski** [comment]
This behavior was changed in #34619 and is slotted to be included in the 7.2 release planned for December 13.

**Comment by rwkyyy** [comment]
and I really thought users were minimising it, rofl
