### ISSUE TITLE
shipping costs

### ISSUE THREAD

**Issue by trash974** [woothemes/woocommerce#35735]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

shipping costs bug when modifying the basket. when updating the basket is up if the delivery should become free the shipping costs remain and if the basket is down the free delivery costs remain. thanks for your answer

### Expected behavior

the delivery costs must be updated when changing the quantities and the price when you are in the basket. I set that from 99 euros the delivery should be free

### Actual behavior

when updating the basket is up if the delivery should become free the shipping costs remain and if the basket is down the free delivery costs remain.

### Steps to reproduce

<img width="1148" alt="Capture d’écran 2022-11-26 à 05 56 46" src="https://user-images.githubusercontent.com/119087916/204068030-a826fc07-7d25-4322-9310-e6b0bb14fcdd.png">
<img width="1244" alt="Capture d’écran 2022-11-26 à 05 57 03" src="https://user-images.githubusercontent.com/119087916/204068031-264ad563-de18-41d1-a12c-1efbdd4b34c4.png">

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.robshop.fr
Site address (URL): https://www.robshop.fr
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 4 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 512 Mo
PHP Time Limit: 360
PHP Max Input Vars: 2000000
cURL Version: 7.86.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.18-MariaDB
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wpmmy7_
Taille totale de la base de données: 35.46MB
Taille de la base de données: 28.02MB
Taille de l’index: 7.44MB
wpmmy7_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_actionscheduler_actions: Données : 2.52MB + Index : 1.44MB + Moteur InnoDB
wpmmy7_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_actionscheduler_logs: Données : 1.52MB + Index : 1.81MB + Moteur InnoDB
wpmmy7_aioseo_cache: Données : 0.13MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_aioseo_notifications: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_aioseo_posts: Données : 0.09MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wpmmy7_gla_attribute_mapping_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_gla_budget_recommendations: Données : 0.22MB + Index : 0.14MB + Moteur InnoDB
wpmmy7_gla_merchant_issues: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_imagify_files: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wpmmy7_imagify_folders: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_jetpack_waf_blocklog: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_automations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_automation_runs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_automation_run_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_automation_triggers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_automation_versions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_newsletter_templates: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_scheduled_tasks: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_subscribers: Données : 0.02MB + Index : 0.13MB + Moteur InnoDB
wpmmy7_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_subscriber_tag: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_mailpoet_tags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_options: Données : 2.39MB + Index : 0.16MB + Moteur InnoDB
wpmmy7_postmeta: Données : 1.52MB + Index : 0.31MB + Moteur InnoDB
wpmmy7_posts: Données : 14.50MB + Index : 0.13MB + Moteur InnoDB
wpmmy7_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_usermeta: Données : 0.11MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wpmmy7_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbscrm_api_keys: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_admlog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_aka: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_zbs_companies: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_zbs_contacts: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_customfields: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_zbs_dbmigration_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_dbmigration_posts: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_zbs_events: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpmmy7_zbs_event_reminders: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_externalsources: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_zbs_forms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_invoices: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wpmmy7_zbs_lineitems: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_meta: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpmmy7_zbs_notifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_object_links: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_quotes: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wpmmy7_zbs_quotes_templates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_security_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_segments: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_segments_conditions: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_settings: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_sys_cronmanagerlogs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_sys_email: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_sys_email_hist: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpmmy7_zbs_tags: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_tags_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpmmy7_zbs_tax_table: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_temphash: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_tracking: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpmmy7_zbs_transactions: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB

### Post Type Counts ###

attachment: 141
custom_css: 1
customize_changeset: 74
et_body_layout: 5
et_footer_layout: 4
et_header_layout: 5
et_pb_layout: 8
et_template: 16
et_theme_builder: 8
jb_store_css: 11
mailpoet_page: 1
nav_menu_item: 30
page: 20
post: 2
product: 36
product_variation: 10
revision: 349
shop_coupon: 1
shop_order: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Akismet Anti-Spam: par Automattic – 5.0.1
All in One SEO Pack: par All in One SEO Team – 4.2.7.1
Alma - Paiement en plusieurs fois ou plus tard pour WooCommerce: par Alma – 3.2.0
Divi Shop Builder: par Divi Space – 1.1.31
Pixel Cat Lite: par Fatcat Apps – 2.6.6
Facebook for WooCommerce: par Facebook – 3.0.4
MonsterInsights - Google Analytics pour WordPress: par MonsterInsights – 8.10.1
Google Listings and Ads: par WooCommerce – 2.3.1
Site Kit by Google: par Google – 1.88.0
Imagify: par Imagify - Optimize Images & Convert WebP – 2.0
Jetpack Boost: par Automattic - Jetpack Site Speed team – 1.5.4
Jetpack Protect: par Automattic – 1.1.1
Jetpack: par Automattic – 11.5.1
MailPoet: par MailPoet – 4.0.1
Maintenance: par WebFactory Ltd – 4.07
WooCommerce PayPal Payments: par WooCommerce – 2.0.0
PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.2.5
WooCommerce: par Automattic – 7.1.0
Discussion sociale: par QuadLayers – 6.2.2
WPForms Lite: par WPForms – 1.7.8
Jetpack CRM: par Automattic - Jetpack CRM team – 5.4.4

### Inactive Plugins (5) ###

Checkout Fields Manager for WooCommerce: par QuadLayers – 6.3.5
Direct Checkout for WooCommerce: par QuadLayers – 2.7.2
OptinMonster: par OptinMonster Popup Builder Team – 2.11.0
QuadMenu: par Mega Menu – 2.3.3
WooCommerce Direct Checkout PRO: par QuadLayers – 2.4.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base de la boutique: #48 - /accueil/produits/
Panier: #563 - /panier/
Commander: #92 - /commander/
Mon compte: #94 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Divi
Version: 4.19.1
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: RE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-26 13:20:43 +04:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Complete: 5 699
Oldest: 2022-10-28 12:43:10 +0000
Newest: 2022-11-26 01:58:05 +0000

Failed: 14
Oldest: 2022-10-28 12:45:29 +0000
Newest: 2022-11-21 08:10:46 +0000

Pending: 11
Oldest: 2022-11-26 02:00:05 +0000
Newest: 2022-11-28 08:10:47 +0000

### Status report information ###

Generated at: 2022-11-26 06:00:14 +04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @trash974,

Thanks for your report. Would you be able to provide a set of steps that we can use to attempt to reproduce this issue? Also, can you confirm that the bug occurs when only the WooCommerce plugin is active?
