### ISSUE TITLE
If Gutenberg is enabled in product description, the new WooCommerce navigation experience is not compatible

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#35739]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In my Woocommerce stores I generally enable Gutenberg in product description to create beautiful product pages with accordions, columns, graphical elements etc in the product description.
Since Gutenberg in product description is not supported yet, I use a php snippet to enable it.
function activate_gutenberg_product( $can_edit, $post_type ) {
 ```
if ( $post_type == 'product' ) {
        $can_edit = true;
    }
    return $can_edit;
}
add_filter( 'use_block_editor_for_post_type', 'activate_gutenberg_product', 10, 2 );
// enable taxonomy fields for woocommerce with gutenberg on
function enable_taxonomy_rest( $args ) {
    $args['show_in_rest'] = true;
    return $args;
}
add_filter( 'woocommerce_taxonomy_args_product_cat', 'enable_taxonomy_rest' );
add_filter( 'woocommerce_taxonomy_args_product_tag', 'enable_taxonomy_rest' );
```

Unfortunately it is not compatible with the new WooCommerce navigation experience, which I particularly like and I'd love use.
In particular, the new WooCommerce navigation experience overlaps the Gutenberg interface. 

### Expected behavior

The Gutenberg canvas should resize to accomodate the new navigation experience.

The new navigation experience can be collapsed if you click on the Wordpress logo/site icon but the top bar is still partially hidden.

### Actual behavior

This is a photo that shows how the interface is actually displayed with Gutenberg enabled and the new WooCommerce navigation experience turned on.

<img width="1440" alt="Screenshot 2022-11-23 at 4 12 18 PM" src="https://user-images.githubusercontent.com/47855768/204132191-03590e2c-b60e-429e-bb5e-5b04d75436f2.png">

### Steps to reproduce

1. Add the php snippet I attached above in CodeSnippets or in the function.php file in the theme
2. Go to Woocommerce > Settings > Advanced > Features and the new WooCommerce navigation experience to the dashboard
3. Create a new product

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://3e263afc2c.nxcli.io/it
Site address (URL): https://3e263afc2c.nxcli.io/it
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 9.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.22
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 16384
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.5.17-MariaDB
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_2_
Total Database Size: 9.46MB
Database Data Size: 7.66MB
Database Index Size: 1.80MB
wp_2_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 5.06MB + Index: 0.06MB + Engine InnoDB
wp_2_postmeta: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_2_posts: Data: 1.23MB + Index: 0.06MB + Engine InnoDB
wp_2_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_spm_checkpoints: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 93
custom_css: 1
customize_changeset: 78
nav_menu_item: 25
page: 10
post: 52
product: 18
revision: 75
shop_order: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Kadence Blocks – Gutenberg Blocks for Page Builder Features: by Kadence WP – 2.4.22
Kadence Starter Templates: by Kadence WP – 1.2.16
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.0
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce: by Automattic – 7.1.0
Code Snippets: by Code Snippets Pro – 3.2.2
WooCommerce Blocks: by Automattic – 9.0.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.0

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 5.0.1
CDN Enabler: by KeyCDN – 2.0.5
Object Cache Pro: by Rhubarb Group – 1.17.0
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.33

WooCommerce Points and Rewards: by WooCommerce – 1.7.21
WooCommerce Sales Performance Monitor: by Nexcess – 1.0.1

### Dropin Plugins (1) ###

fatal-error-handler.php: fatal-error-handler.php

### Must Use Plugins (1) ###

Nexcess Managed Apps: by Nexcess – 1.35.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #958 - /shop/
Cart: #959 - /cart/
Checkout: #960 - /checkout/
My account: #968 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kadence
Version: 1.1.31
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-26 13:59:38 +01:00
Options: ✔
Notes: 34
Onboarding: completed

### Action Scheduler ###

Complete: 44
Oldest: 2022-11-26 14:00:59 +0000
Newest: 2022-11-27 10:01:59 +0000

Pending: 2
Oldest: 2022-11-27 13:59:39 +0000
Newest: 2022-11-27 21:15:03 +0000

### Status report information ###

Generated at: 2022-11-27 12:17:05 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AnnaMag** [comment]
We're closing the issue as we aren't actively working on the new navigation.
