### ISSUE TITLE
JS not enqueued when editing custom post types with HPOS

### ISSUE THREAD

**Issue by brucealdridge** [woothemes/woocommerce#35749]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to #35601 and open PR #35658

Using the [Custom Order Types HPOS Screens](https://github.com/woocommerce/woocommerce/pull/35658) PR when editing a custom order type the javascript for editing the order details is not included  `woocommerce/assets/js/admin/meta-boxes-order.min.js`

see also: https://github.com/Automattic/woocommerce-subscriptions-core/issues/309

### Expected behavior

The file `woocommerce/assets/js/admin/meta-boxes-order.min.js` is loaded and editing of the custom order is possible.

### Actual behavior

Javascript is not loaded for editing orders.

### Steps to reproduce

1. With HPOS on and enabled using PR https://github.com/Automattic/woocommerce-subscriptions-core/pull/297 and https://github.com/woocommerce/woocommerce/pull/35658
2. Click on 'Subscriptions' in wp-admin
3. Click to view a subscription
4. Clicking the edit icons, `Add Items` and `Apply coupon` buttons don't work.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @brucealdridge,

With these commits 311c1d78bf611cb85577dcd637e56098fbaa1ea8 and ed4bd5e21f60945f756c7eea1be50fff7c33294d in the working branch, the metabox JS should now be enqueued for custom order types as well.

I'm closing this issue for now, but please let me know if you encounter any trouble while testing. Thanks!
