### ISSUE TITLE
Bulk action form URL uses wrong value for page for filtering custom post types with HPOS

### ISSUE THREAD

**Issue by brucealdridge** [woothemes/woocommerce#35750]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to #35601 and open PR #35658

Using the [Custom Order Types HPOS Screens](https://github.com/woocommerce/woocommerce/pull/35658) PR when viewing a filtering a custom order type, the `page` hidden input attribute is using the wrong value.

![image](https://user-images.githubusercontent.com/57298/204402614-dc491a6d-a062-4ea7-834f-d95231dc54d5.png)

### Expected behavior

A user should be able to filter by date or customer of a custom order type and the relevant results would be shown.

### Actual behavior

The page is redirected and the filters are applied to the orders rather than the custom order type.

### Steps to reproduce

1. With HPOS on and enabled using PR https://github.com/Automattic/woocommerce-subscriptions-core/pull/297 and https://github.com/woocommerce/woocommerce/pull/35658
2. Click on 'Subscriptions' in wp-admin
3. Filter subscriptions by date or customer.
4. The results show orders instead.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Fixed in #35751.
