### ISSUE TITLE
Automatically generate variations from product options

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35778]
When at least one option is created, we should automatically create variations from all options.

Since doing this on the backend could affect existing (legacy) product flows, this should only occur on option changes within the new product management experience on the client-side.'

Blocked by https://github.com/woocommerce/woocommerce/issues/35770.

![Image](https://user-images.githubusercontent.com/10561050/204701137-eaa67d30-f776-46e1-98ab-12a48ffcf20e.png)

**Acceptance criteria**

* [ ] Adding a new option or value should automatically create all possible variations from the existing options
* [ ] Removing an option or option value should remove any variations with those options
* [ ] The following data should be copied from the parent product to each variations (if exists): regular price, sale price, weight, dimensions, shipping class, tax class, and manage stock options. The product should be transformed into a variable product.

**Comment by joshuatf** [comment]
Estimate: 3

We'll want to write some logic to track all possible permutations of options which should also take into account performance since it's possible many variations could exist.

@jarekmorawski @pmcpinto I'm estimating based on the assumption that this only creates or removes variations based on the newly added options and not regenerating all variations (non-inclusive of the newly added option) as that could be frustrating to users who intentionally removed them previously.

**Comment by pmcpinto** [comment]
> I'm estimating based on the assumption that this only creates or removes variations based on the newly added options and not regenerating all variations (non-inclusive of the newly added option) as that could be frustrating to users who intentionally removed them previously.

👍 I think that assumption makes sense.
