### ISSUE TITLE
Product variations card should have a fixed height

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35789]
To prevent jumpiness of the card as variations are loaded/added/removed, we should aim for a fixed height of the card variations live in.

Note that it's probably safer to use a `min-height` as opposed to actual height to prevent accidentally truncating information should something overflow.

Note that this issue should take into account pagination introduced in https://github.com/woocommerce/woocommerce/issues/35788.

**Design**

![Image](https://user-images.githubusercontent.com/10561050/204888014-6012fdba-6564-481c-902c-019c7c38d176.png)

**Acceptance criteria**

* [ ] Set a minimum card height that allows fitting all 5 items or more with pagination without expanding the card as items are added
* [ ] Increasing the content of the items or making them vertically taller should not truncate the items
* [ ] The card should look and work appropriately on mobile screens

**Comment by joshuatf** [comment]
@jarekmorawski Should the mobile version not have any required height?  I'm worried that the mobile version may be a lot of empty white card space if only 1 variation exists.

**Comment by joshuatf** [comment]
Estimate: 1

**Comment by jarekmorawski** [comment]
> Should the mobile version not have any required height? I'm worried that the mobile version may be a lot of empty white card space if only 1 variation exists.

I agree. Good call! 👍 One more note on this issue: when we've got multiple filters (#35792), the header will increase in height. It shouldn't eat into the variation list, so I guess that `min-height` should be applied to the list alone, and not the whole card element.

**Comment by octaedro** [comment]
Hey @jarekmorawski,

I'm seeing this design BaoQ3PGPnhAiJCsJtxgej3-fi-106%3A1922&t=CYzYrKIlzQhMBubn-0 and the variation list height is `488px`.

Is the `min-height` `488` pixels?

**Comment by octaedro** [comment]
Oh, the variation line height is bigger in the design. It seems like the `min-height` should be something like `310px`.

**Comment by joshuatf** [comment]
@octaedro Just a heads up that pagination may affect this so make sure to test with <25 items and <25 items.

**Comment by jarekmorawski** [comment]
Hiya @octaedro 👋 The whole variation list section is 608 px tall. The header is 84 px, the table title row is 36 px, each list item is 84 px, and the footer with pagination is 68 px. The section should have the same height whether there are 1 or 5 items in the list (note that when the number of items doesn't exceed 5, we don't show the pagination).

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/79307566/208091747-f5e99351-cb76-4a00-a741-f2e311e46f1f.png">

If the user changes the number of items shown in the table from 5 to something else, the list height should naturally expand (the selected in the footer defines how many items they can see per page). So, if the list is set to display 5 per page, it should be 608 px tall in total. If it's set to show 25 items, it should be 2288 px, etc. The goal is to give the list a rigid shape so it doesn't jump up and down as new items are added or removed, making the pagination in the footer the primary way to navigate it.

Let me know if this helps!
