### ISSUE TITLE
Typo in brandname

### ISSUE THREAD

**Issue by NekoJonez** [woothemes/woocommerce#35781]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=14639471&filters%5Btranslation_id%5D=99720497

TikTok isn't spelled correctly.

### Expected behavior

That it's spelled TikTok instead of Tiktok

### Actual behavior

See above

### Steps to reproduce

N/A

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@NekoJonez Thanks for reporting this. I checked using the link you provided and this has been fixed.

**Comment by rrennick** [comment]
Sorry, I should have looked closer.

**Comment by NekoJonez** [comment]
I fixed it in my translation but is it fixed 8n WooCommerce? @rrennick

**Comment by ecgan** [comment]
@NekoJonez , thanks for reporting this. I will look into fixing this issue.

**Comment by rrennick** [comment]
> I fixed it in my translation but is it fixed 8n WooCommerce?

@NekoJonez We don't maintain the translations in this repo. The link you provided is where the translations for all the locales are kept up to date.

**Comment by NekoJonez** [comment]
> > I fixed it in my translation but is it fixed 8n WooCommerce?
> 
> @NekoJonez We don't maintain the translations in this repo. The link you provided is where the translations for all the locales are kept up to date.

Hi there

I think you misunderstood. I fixed it in that translation for Dutch users. But I was asking if it was fixed in the WooCommerce core. Which happened already. :)

**Comment by rrennick** [comment]
> But I was asking if it was fixed in the WooCommerce core. Which happened already. :)

@NekoJonez Ah, sorry. The issue was closed when a PR to address it was merged above.

**Comment by NekoJonez** [comment]
> > But I was asking if it was fixed in the WooCommerce core. Which happened already. :)
> 
> @NekoJonez Ah, sorry. The issue was closed when a PR to address it was merged above.

No problemo my dude. Everyone makes mistakes or misunderstand things once in a while. Glad it was cleared up.
