### ISSUE TITLE
"SKU: N/A" is swown on Variation products

### ISSUE THREAD

**Issue by JakeDevLab** [woothemes/woocommerce#35782]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WooCommerce product meta shows “SKU: N/A” on Variation products with no SKU set on the Inventory tab. Simple products are OK, that’s only on Variation products type.

I use Divi theme but the problem appears on Twenty Twenty-Two theme as well. That means, that’s a general WooCommerce issue, I believe.

P.S.: I can not provide a link to the website, sorry, it’s on a localhost. But you can easily reproduce the issue on your test/stage setup.

### Expected behavior

Variation products should not display "SKU: N/A" when the parent product has no SKU filled in (the same way the Simple product behaves).

### Actual behavior

WooCommerce product meta shows “SKU: N/A” on Variation products with no SKU set on the Inventory tab. 

### Steps to reproduce

1. Create a Variation product with no any SKU.
2. Let WooCommerce product meta show product SKUs on the frontend.
3. See "SKU: N/A" instead of nothing (like it would be if it is a Simple product).

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://****.com
Site address (URL): http://****.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.32
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.16-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 37.06MB
Database Data Size: 20.88MB
Database Index Size: 16.18MB
wp_woocommerce_sessions: Data: 0.45MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_dgwt_wcas_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.52MB + Index: 0.45MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 0.58MB + Engine InnoDB
wp_posts: Data: 9.52MB + Index: 0.34MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_data: Data: 0.11MB + Index: 0.23MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 12.56MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 1
acoplw_prod_list: 1
attachment: 528
awl-labels: 10
ctct_forms: 2
ctct_lists: 25
custom_css: 2
customize_changeset: 13
et_body_layout: 21
et_footer_layout: 8
et_header_layout: 9
et_pb_layout: 1
et_template: 69
et_theme_builder: 7
nav_menu_item: 22
page: 17
post: 15
product: 80
product_variation: 67
revision: 700
wp_global_styles: 1
wpc_product_badge: 3
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (15) ###

Advanced Woo Labels: by ILLID – 1.56
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.21.0
Constant Contact Forms for WordPress: by Constant Contact – 1.13.0
Google Listings and Ads: by WooCommerce – 2.3.1
Redirection: by John Godley – 5.3.5
Trust Payments Gateway ( 3DS2 ): by Trust Payments – 1.3.1
Product Filter by WooBeWoo: by WooBeWoo – 2.2.3
WPC Product Timer for WooCommerce (Premium): by WPClever – 4.1.0
Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.3.13
Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 2.0.13
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.13
WooCommerce Amazon Pay: by WooCommerce – 2.3.0
WooCommerce Shipping & Tax: by WooCommerce – 2.0.0
WooCommerce: by Automattic – 7.1.0
YITH WooCommerce Product Bundles Premium: by YITH – 1.19.0

### Inactive Plugins (6) ###

Advanced Woocommerce Product Gallery Slider: by UnikInfotech – 1.0.0
Akismet Anti-Spam: by Automattic – 5.0.1
Constant Contact Forms by MailMunch: by MailMunch – 2.0.10
Super Payments: by Super Payments – 1.0.5
TP WooCommerce Product Gallery: by TP Plugins – 1.1.1
WooCommerce Product Bundles: by WooCommerce – 6.17.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bopobb (bopobb)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #9 - /shop/
Basket: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: #13 - /terms/

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: https://****.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.19.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: /home/u324079926/domains/****.com/public_html/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/home/u324079926/domains/****.com/public_html/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-10 09:12:42 +00:00
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Complete: 147
Oldest: 2022-10-04 22:53:35 +0100
Newest: 2022-11-21 10:14:46 +0000

Pending: 272
Oldest: 2022-11-21 14:14:47 +0000
Newest: 2022-11-29 17:09:43 +0000

### Status report information ###

Generated at: 2022-11-30 09:50:23 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @JakeDevLab,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screenshot for reference :

![#35782](https://user-images.githubusercontent.com/94531721/204988533-f018dd08-95ab-47df-b937-8cf2b7b543a3.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
@JakeDevLab Can you confirm this is still happening in the latest WooCommerce? I'm not seeing it with Twenty Twenty-Two.

**Comment by JakeDevLab** [comment]
We are able to reproduce the issue on our end using the WooCommerce 8.1.1 version and WordPress 6.4.3 version (can not use the latest version of the Woo at the moment, sorry).

Please find below the screenshot for reference:
<img width="798" alt="Screenshot 2024-02-27 at 15 17 12" src="https://github.com/woocommerce/woocommerce/assets/52824125/3a48d409-8967-43a1-b026-c33581c718f0">

**Comment by KreativeLabs** [comment]
I can also see that if I specify per-variation SKUs, they doesn't appear in the SKU field. I think there should be some JS that replaces the text field when a variation is selected but I have to investigate further.
