### ISSUE TITLE
Blog Post Feature removed from Wordpress 

### ISSUE THREAD

**Issue by jchantr** [woothemes/woocommerce#35796]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am no longer able to create blogs in Wordpress as the option to do so on the left toolbar has disappeared for me. The option to do this is normally by the pin icon which has now been replaced with groups. This only recently became a problem for me one week ago and no one else on my team has this problem. I have tried clearing cache and accessing the site in incognito mode but this hasn't resolved the issue. 
![image (2) (1)](https://user-images.githubusercontent.com/119550764/204947983-b67ebe1b-9655-45db-bcd5-22880966f3b3.png)

### Expected behavior

The word blog will be next to the pin icon and clicking this will allow me to create a blog. 

### Actual behavior

The word Groups appears next to the pin icon and this allows me to create a new group. 

### Steps to reproduce

1. Go to andeglobal.com
2. Click Howdy Jenny Chantratita on the Right
3. See the toolbar on the left that shows the pin icon with group

### WordPress Environment

Unfortunately, I don't have access to this and this has been disabled for me. 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @jchantr,

Thanks for your report. This issue looks like it might be unrelated to WooCommerce. Are you still able to reproduce this with only WooCommerce active? Does the issue go away if WooCommerce is deactivated?
