### ISSUE TITLE
Out of stock not showing after backorders turned off

### ISSUE THREAD

**Issue by dyamicdigitaldesign** [woothemes/woocommerce#35797]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Backorders were turned on for a product and the product is now in backorder.
Stock on hand is netative due to the backorders.
I have turned the ability to backorder this product off.
When viewing the product as a customer, the "Out of stock" notification does not show.
When adding the product to the cart, an warning appears: You cannot add that amount of "Product name" to the cart because there is not enough stock (-2 remaining).

### Expected behavior

Since the product is out of stock, the "Out of stock" text should show where the remaining quantity displays.

### Actual behavior

![image](https://user-images.githubusercontent.com/58131180/205008358-3f58cf7c-2395-4612-acf2-5969df558a8f.png)
No "Out of stock" text is shown.
The product can be added to cart (but fails).

### Steps to reproduce

Create a product and allow backorders
Purchase the product a few times so it is on backorder
Turn off backorders
View the product

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.rmga.com.au
Site address (URL): https://www.rmga.com.au
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 7.4.33
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: VBYwBRkM_
Total Database Size: 60.26MB
Database Data Size: 41.72MB
Database Index Size: 18.54MB
VBYwBRkM_woocommerce_sessions: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
VBYwBRkM_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VBYwBRkM_woocommerce_order_items: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_woocommerce_order_itemmeta: Data: 0.42MB + Index: 0.41MB + Engine InnoDB
VBYwBRkM_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
VBYwBRkM_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_woocommerce_payment_tokens: Data: 0.22MB + Index: 0.08MB + Engine InnoDB
VBYwBRkM_woocommerce_payment_tokenmeta: Data: 0.50MB + Index: 0.48MB + Engine InnoDB
VBYwBRkM_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_actionscheduler_actions: Data: 1.48MB + Index: 1.47MB + Engine InnoDB
VBYwBRkM_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_actionscheduler_logs: Data: 1.50MB + Index: 0.67MB + Engine InnoDB
VBYwBRkM_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_comments: Data: 0.42MB + Index: 0.41MB + Engine InnoDB
VBYwBRkM_etcpf_category_mappings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_custom_feed_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_etsy_configuration: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_etsy_product_count: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_etsy_sync: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_feedproducts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_image_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_listings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_listing_variations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_etcpf_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_resolved_product_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_shipping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_etcpf_variationupload_preparation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_et_social_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_mystickyelement_contact_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_options: Data: 7.08MB + Index: 1.19MB + Engine InnoDB
VBYwBRkM_postmeta: Data: 10.41MB + Index: 3.89MB + Engine InnoDB
VBYwBRkM_posts: Data: 2.45MB + Index: 0.36MB + Engine InnoDB
VBYwBRkM_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_usermeta: Data: 9.48MB + Index: 7.02MB + Engine InnoDB
VBYwBRkM_users: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
VBYwBRkM_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
VBYwBRkM_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
VBYwBRkM_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
VBYwBRkM_wc_rate_limits: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
VBYwBRkM_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
VBYwBRkM_yoast_indexable: Data: 2.52MB + Index: 0.44MB + Engine InnoDB
VBYwBRkM_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
VBYwBRkM_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
VBYwBRkM_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
VBYwBRkM_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1029
br_product_filter: 1
custom_css: 1
et_body_layout: 4
et_header_layout: 1
et_pb_layout: 7
et_template: 8
et_theme_builder: 1
nav_menu_item: 20
page: 10
post: 1
product: 64
revision: 276
shop_coupon: 7
shop_order: 403
shop_order_refund: 3
wwp_requests: 1
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Pixel Manager for WooCommerce: by SweetCode – 1.27.7
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.21.0
Dynamic Digital Upgrades: by Dynamic Digital Design – 1.1
Facebook for WooCommerce: by Facebook – 2.6.28
myStickyElements: by Premio – 2.0.6
User Role Editor: by Vladimir Garagulya – 4.63.1
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.5
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Square: by WooCommerce – 3.3.0
WooCommerce: by Automattic – 7.1.0
Yoast SEO: by Team Yoast – 19.11
YITH WooCommerce Ajax Product Filter: by YITH – 4.16.0

### Inactive Plugins (3) ###

Product Reviews Import Export for WooCommerce: by WebToffee – 1.4.8
WooCommerce Etsy Integration: by ExportFeed.com – 3.9.5
Zapier for WordPress: by Zapier – 1.0.4

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
flowers (flowers)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #206 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #5847 - /refund_returns/

### Theme ###

Name: Divi
Version: 4.18.0
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-02 08:51:04 +09:30
Options: ✔
Notes: 36
Onboarding: completed

### Action Scheduler ###

Complete: 4,981
Oldest: 2022-11-01 08:27:44 +0000
Newest: 2022-12-01 08:48:32 +0000

Failed: 1
Oldest: 2022-11-01 07:54:08 +0000
Newest: 2022-11-01 07:54:08 +0000

Pending: 4
Oldest: 2022-12-01 09:48:32 +0000
Newest: 2022-12-06 03:33:33 +0000

### Status report information ###

Generated at: 2022-12-01 18:24:12 +09:30
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dyamicdigitaldesign** [comment]
Note: Updating any attribute of the product changes its status to out of stock.

**Comment by swatipawarGS** [comment]
Hi @dyamicdigitaldesign,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/205232484-dd8833ff-5f7e-47ee-b602-ab4f52f5b37d.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by lsinger** [comment]
We have not been able to reproduce this issue and have not heard back from you. We are closing this issue for now. If we missed something, please leave a comment and we will take a second look.
