### ISSUE TITLE
[Enhancement]: Coupon: Free Product & Shipping For One Item - Other Items In Cart Have Shipping

### ISSUE THREAD

**Issue by billymitchell** [woothemes/woocommerce#35837]
### Describe the solution you'd like

I'd love the ability to create a coupon that allows the item to be free, both in cost and shipping. If multiple items are in the cart, the other items would still require payment for the cost and shipping. From what I can tell, the "Allow free shipping" coupon option makes the whole cart ship free. There should be an option to make free the shipping cost of only specific items that the coupon is applied. I still need to record the calculated shipping cost of that item for reporting, and I want the customer to see how much shipping I'm giving away (value added). I don't want to give away extra shipping if I don't have to. I don't want to force customers to put one item in their cat at a time.

https://woocommerce.com/document/coupon-management/

**Comment by barryhughes** [comment]
Thanks for the suggestion. This sounds valid and I can see the appeal in implementing this, but shipping is complex and there are many permutations to think through. For that reason, we're interested in gauging demand for this functionality before moving ahead and will apply our `needs: votes` workflow.
