### ISSUE TITLE
Errors adding custom billings fields on checkout 

### ISSUE THREAD

**Issue by HeikelV** [woothemes/woocommerce#35845]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i want to add this select as custom billing fields

```
$fields['billing_apisunat_document_type'] = array(
			'label'    => 'TIPO DE DOCUMENTO', // Add custom field label!
			'required' => true, // if field is required or not!
			'type'     => 'select', // add field type!
			'clear'    => false, // add clear or not!
			'class'    => array( 'form-row-wide' ), // add class name!
			'options'  => [
				'03'   => 'BOLETA DE VENTA',
				'01'   => 'FACTURA'
			],
			'priority' => 21,
		);
```

### Expected behavior

i was expecting that WC render a select with keys value '01' , '03' 

...
```
<option value="03">BOLETA DE VENTA</option>
<option value="01" selected="selected">FACTURA</option>
```
....

### Actual behavior

when i use a leading 0 key value string, WC use the same value for key and option

...
```
<option value="BOLETA DE VENTA">BOLETA DE VENTA</option>
<option value="FACTURA" selected="selected">FACTURA</option>
```
....

### Steps to reproduce
```

add_filter( 'woocommerce_billing_fields', array( $this, 'custom_woocommerce_billing_fields' ) );

public function custom_woocommerce_billing_fields( array $fields ): array {
$fields['billing_apisunat_document_type'] = array(
			'label'    => 'TIPO DE DOCUMENTO', // Add custom field label!
			'required' => true, // if field is required or not!
			'type'     => 'select', // add field type!
			'clear'    => false, // add clear or not!
			'class'    => array( 'form-row-wide' ), // add class name!
			'options'  => [
				'03'   => 'BOLETA DE VENTA',
				'01'   => 'FACTURA'
			],
			'priority' => 21,
		);
return $fields;
}
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/facturas
Site address (URL): http://localhost/facturas
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_PE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.28-0ubuntu4
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 3.53MB
Database Data Size: 2.06MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 7
post: 1
product: 1
revision: 1
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

APISUNAT - Facturación Electrónica: by APISUNAT – 1.2.1
Jetpack: by Automattic – 11.5.1
Openpay Cards Plugin: by Openpay – 2.7.8
Checkout Fields Manager for WooCommerce: by QuadLayers – 6.3.5
WooCommerce: by Automattic – 7.1.0
WP Crontrol: by John Blackbourn & crontributors – 1.14.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: PEN (S/)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /index.php/cart/
Checkout: #8 - /index.php/checkout/
My account: #9 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-06 20:07:43 -05:00
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Complete: 43
Oldest: 2022-11-12 15:04:28 +0000
Newest: 2022-12-06 02:55:45 +0000

Pending: 1
Oldest: 2022-12-07 02:55:45 +0000
Newest: 2022-12-07 02:55:45 +0000

### Status report information ###

Generated at: 2022-12-05 23:11:23 -05:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @HeikelV,

I took a look at this and modified the snippet you shared slightly, so it can run outside of a class:

```php
add_filter( 'woocommerce_billing_fields', 'custom_woocommerce_billing_fields' );

function custom_woocommerce_billing_fields( array $fields ): array {
	$fields['billing_apisunat_document_type'] = array(
		'label'    => 'TIPO DE DOCUMENTO', // Add custom field label!
		'required' => true, // if field is required or not!
		'type'     => 'select', // add field type!
		'clear'    => false, // add clear or not!
		'class'    => array( 'form-row-wide' ), // add class name!
		'options'  => [
			'03'   => 'BOLETA DE VENTA',
			'01'   => 'FACTURA'
		],
		'priority' => 21,
	);
	return $fields;
}
```

On the checkout page, this resulted in the following HTML:

```html
<select name="billing_apisunat_document_type" id="billing_apisunat_document_type" class="select " data-placeholder="">
	<option value="03">BOLETA DE VENTA</option>
	<option value="01">FACTURA</option>
</select>
```

Whereas it sounds like you are seeing:

```html
<select name="billing_apisunat_document_type" id="billing_apisunat_document_type" class="select " data-placeholder="">
	<option value="BOLETA DE VENTA">BOLETA DE VENTA</option>
	<option value="FACTURA" selected="selected">FACTURA</option>
</select>
```

I'm not sure why the discrepancy, but so far I cannot reproduce. Though I realize you already answered some of these questions via the **Isolating the Problem** section of your initial report, can I confirm:

- You still see this (ie, with the current stable version of WooCommerce)?
- Nothing else might be interfering (in addition to other plugins/themes, can you confirm you still see this if you reduce your custom code to the snippet I shared above—that is, for testing purposes, you eliminate any other code from the same class)?

Thanks!
