### ISSUE TITLE
[Enhancement] Scroll to the newly added item in the Add attributes modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35853]
When the user presses the Add another button in the Add attributes modal, it is added to the bottom of the list, but the user may not see that. To fix that, let's have the list scroll down, so the newly added item is visible.

https://user-images.githubusercontent.com/79307566/205939346-169f3461-3b42-4eac-b7d8-857b72142007.mov

**Acceptance criteria** 

- [ ] Users can see the newly added list item after pressing the `Add another` button.
- [ ] The `Attribute` field in the newly added item is immediately in focus.

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-
