### ISSUE TITLE
[Enhancement] Make the category trees open on click, rather than on hover

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35854]
When the category dropdown opens, the trees open automatically on hover rather than click. This creates confusion because the list changes without any user input.

We should remove that interaction and add a grey highlight to the hovered item to replace the current `font-weight`.

https://user-images.githubusercontent.com/79307566/205941129-646ca9fb-ba69-4b43-b949-f78878a5f784.mov

**Acceptance criteria**

- [ ] Users must click the arrow button to expand a tree (when searching, trees are expanded by default and only show relevant children).
- [ ] The font style doesn't change on hover. Instead, the whole list item changes the background to #F6F7F7.

**Comment by AnnaMag** [comment]
Assigning @mdperez86 since he is working on a fix.

**Comment by mattsherman** [comment]
> Assigning @mdperez86 since he is working on a fix.

@AnnaMag @mdperez86 Can we move this into "In Progress" then? And, is there a work-in-progress PR draft?

**Comment by AnnaMag** [comment]
@mattsherman @mdperez86's new component work will address it, afaiu. Moving to "in progress".

**Comment by pmcpinto** [comment]
Fixed with the new component
