### ISSUE TITLE
[Fix]: Update the validation message color for the sale price field

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35856]
I noticed that the validation error message for the sale price field is grey, instead of red and the field doesn't have the red outline.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/79307566/205943432-a18445c1-f296-4d57-9f12-e9a9a1c9558b.png">

**Acceptance criteria**

- [ ] The validation message is Gutenberg/Alert Red (#CC1818). `5sAIeTRd9Yp7nSCT33BAWz-fi-7606%3A405205&t=j5qFJ9J8WHeJKTyn-4`
- [ ] The sale field price field gets a Gutenberg/Alert Red (#CC1818) stroke (1.5 px, outside). The stroke disappears when the field is in focus.

**Comment by pmcpinto** [comment]
Fixed in the new experience
