### ISSUE TITLE
[Enhancement]: Cancel Automatic Emails for specific products when customers buy a digital product

### ISSUE THREAD

**Issue by ofivesounds** [woothemes/woocommerce#35863]
### Describe the solution you'd like

Hi, I’d like to cancel automatic emails from specific products when customer download digital products.

This will be so useful because I'd like to send a sequence of emails once a customer downloads a free product. The first email of the sequence is the download link of the product they've downloaded but they'll also receive an email from WooCommerce with the download link of the product so they might omit my custom email.

### Describe alternatives you've considered

It would be great to have an option to cancel emails from a specific product.

**Comment by barryhughes** [comment]
Thanks for the suggestion, @ofivesounds.

This feels like a very specific sort of task and something that is best solved through customization work, so I'm going to close the issue.

If helpful and if you are interested in coding a solution of your own, one strategy could be to identify the email class that manages the emails you are interested in. You could then identify the [hooks used to trigger the email](https://github.com/woocommerce/woocommerce/blob/7.1.1/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php#L43-L46) and register your own callbacks that runs a little earlier (this could then make a decision about unhooking the default trigger method, or leaving it in place, based on the contents of the current order).

Additionally, I wanted to note that the default email classes can be obtained via `WC()->mailer()->get_emails()` (which might be useful as a way of grabbing references to each instance that you are interested in).
