### ISSUE TITLE
Extension Generator error - Command `pnpm start` give error wp-scripts: not found

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#35861]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

From [this ticket](https://wordpress.org/support/topic/woocommerce-plugin-dev-cmd-pnpm-start-give-error-wp-scripts-not-found/).

The steps described in [this article](https://developer.woocommerce.com/extension-developer-guide/creating-your-first-extension/) that explain how to create a custom extension are not working anymore.

Summarizing the problem described [here](https://wordpress.org/support/topic/woocommerce-plugin-dev-cmd-pnpm-start-give-error-wp-scripts-not-found/), after running: `pnpm start` this error is visible

```
-> wp-scripts start
sh: 1: wp-scripts: not found
ELIFECYCLE  Command failed.
```

### Expected behavior

The Extension Generator should work correctly.

### Actual behavior

The Extension Generator is not working.

### Steps to reproduce

Try to create an extension following the steps described [here](https://developer.woocommerce.com/extension-developer-guide/creating-your-first-extension/).

### WordPress Environment

- WordPress v6
- WooCommerce v7.1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
While we're at it, lets fix up the blog post instructions too, e.g. there is no need to run this command from a subdir.
