### ISSUE TITLE
Business features step and marketing task - add new extension (Codisto)

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35871]
**Description:** we're going to test the promotions of multi-channel solutions through the setup experience by temporarily introducing Codisto. We'll place the Codisto extension in two locations: business features step and marketing task. We want to test this asap through the remote endpoint and WC 7.3 (code freeze: Dec 15).
Context here: pe2C5g-xg-p2

Copy: 
Business features step:
Sell on Amazon, eBay, Walmart and more directly from WooCommerce with [Codisto](https://href.li/?https://woocommerce.com/pt-br/products/amazon-ebay-integration/)
The pill should say "Free trial"

Marketing task:
Codisto
Sell on Amazon, eBay, Walmart and more directly from WooCommerce

Logo: 
![codisto_logo_screen_icon_fullcolour_rgb-1](https://user-images.githubusercontent.com/3380168/207044390-e1899421-a7b7-4dd7-a562-e5ed9c539999.png)
Download link: https://wordpress.org/plugins/codistoconnect/

**Acceptance criteria:**
- [ ] Add the Codisto extension to the business features step in the store profiler. The extension should be placed at the bottom of the "Grow your store" section.
- [ ] Add the Codisto extension to the marketing task. The extension should be placed at the bottom of the "Grow your store" section.

**Event tracking:**
We should use the tracking we have in place in the business features step and marketing task flows

**Comment by pmcpinto** [comment]
Issue description updated with copy and logo

**Comment by pmcpinto** [comment]
@adrianduffell can you confirm that it will be possible to include this in 7.3? Thanks

**Comment by adrianduffell** [comment]
Hey @pmcpinto, yes still on track to include in 7.3. Hoping to have it ready for testing tomorrow.

**Comment by pmcpinto** [comment]
I'll update this issue once it's ok to move forward with the inclusion through the remote endpoint.

**Comment by chihsuan** [comment]
Closed by
- https://github.com/woocommerce/woocommerce/pull/36009
- https://github.com/Automattic/woocommerce.com/pull/15486
