### ISSUE TITLE
[Enhancement]: Croatia entering Eurozone on Jan 1st, 2023

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#35872]
### Describe the solution you'd like

We need to change the settings for Croatia so that the default currency is EUR from Jan 1st and Croatian stores shouldn't be able to use HRK as their main currency after the first 2 weeks in January.

From Wikipedia:

> From 5 September 2022 until 31 December 2023 **display of all prices in dual currency is mandatory to prevent unjustified price increases**. The public can buy euro starter kits to familiarize themselves with the new currency since 1 December 2022. These coins are not to be used before 1 January 2023.[[10]](https://en.wikipedia.org/wiki/Croatia_and_the_euro#cite_note-Mint_3-11)[[72]](https://en.wikipedia.org/wiki/Croatia_and_the_euro#cite_note-Mint_4-91)

This one is handled by https://github.com/woocommerce/woocommerce/issues/34463 Thanks @rynaldos !

> Payments can be made **in both currencies during the first two weeks of January 2023** (with change being given in euro) and after then only in euro. 

### Additional context

Internal discussion: pbUcTB-1Q1-p2

**Comment by tpaksu** [comment]
One more thing, customers onboarding to WooCommerce with Croatia selected as the country should have their store currency set to EUR instead of HRK after Jan 1st, 2023.
