### ISSUE TITLE
Change default sorting behavior in revenue report to date_paid

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#35885]
**Overall project:** In the Revenue report of our Analytics, the payment date is assigned to the order creation date, regardless of when the payment was made. This approach can be misleading and lead to complications in terms of taxes and invoices. We'll change the default date used in this report and introduce the flexibility to use different dates: created, paid or completed.

For this issue we're simple changing the default sort order to `date_paid` instead of `date_created`. We'll also likely want to lay the foundation for toggling this date to `date_completed` as desired which will happen in a [subsequent issue](https://github.com/woocommerce/woocommerce/issues/35886).

See the [original issue](https://github.com/woocommerce/woocommerce/issues/35348) for more context.

**Acceptance criteria:**
- [ ] Change the default order date used in the Revenue report to `date_paid`

More info:
#32693
#6535
Slack: p1650010691719899-slack-C7U3Y3VMY
Reports: 4949047-zen

**Comment by joelclimbsthings** [comment]
I spent some time looking into this issue, although ran out of time before being able to implement a fix. The SQL queries and logic involve the [stats data store](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/DataStore.php) and the [reports data store](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Reports/DataStore.php) that it inherits from.

Two possible approaches:
- Insert a left join in `get_data` within the stats data store. This code can get convoluted pretty fast, though, as you'll have to touch multiple parts of the query that are built in various places. 
- Migrate the `date_paid` and `date_completed` unix timestamps to a fields within in the `wc_order_stats` table, which will greatly simplify the logic needed to toggle this within the data stores. There is already a `date_column_name` variable which would be instrumental.

I'd definitely recommend the second option as it's ultimately cleaner/simpler, but it will require a db update. 

I had already put together the queries for these options below, which might need refinement:
```sql
// Create columns
ALTER TABLE wp_wc_order_stats
ADD COLUMN date_paid DATETIME DEFAULT '0000-00-00 00:00:00',
ADD COLUMN date_completed DATETIME DEFAULT '0000-00-00 00:00:00';

// Populate data for date_paid
UPDATE wp_wc_order_stats AS order_stats
INNER JOIN wp_postmeta AS postmeta
	ON postmeta.post_id = order_stats.order_id
	and postmeta.meta_key = '_date_paid'
SET order_stats.date_paid = IFNULL(FROM_UNIXTIME(postmeta.meta_value), '0000-00-00 00:00:00');
```

If you're interested in the left join option, I experimented with having this logic in the `get_data` function:
```php
$date_fields_join = "LEFT JOIN (
				SELECT
					post_id,
					meta_key,
					meta_value AS date_paid
				FROM
					{$wpdb->prefix}postmeta
				) postmeta
				ON postmeta.post_id = {$wpdb->prefix}wc_order_stats.order_id
				and postmeta.meta_key = '_date_paid'";
```
Although there would be other logic that would need to change in this case^

**Comment by nathanss** [comment]
Hello @joelclimbsthings @pmcpinto 

I have PR #36492 opened, but with the way things are structured right now, the Revenue report is using the same Data Store as the Orders report. 

Is it a problem if we change the date behavior of the two reports at the same time or do we want to only change the Revenue report?

**Comment by joelclimbsthings** [comment]
Hey @nathanss , I didn't explore this fully but I believe you might be able to change the date field from the [Revenue reports query file](https://github.com/woocommerce/woocommerce/blob/3dd60322d5490d7d86ad33e7d732f276df73a12d/plugins/woocommerce/src/Admin/API/Reports/Revenue/Query.php).

That is, with the assumption that you can toggle [this field](https://github.com/woocommerce/woocommerce/blob/fe6ab3ea4e35acc1d3c1618634baab26e45815fd/plugins/woocommerce/src/Admin/API/Reports/DataStore.php#L45) from that query file, and that would do the trick? 

If that's not possible, I'd have to defer to @pmcpinto on the possibility of changing the Orders report as well.

**Comment by joelclimbsthings** [comment]
I also noticed that as implemented the setting doesn't specify that it's only impacting the Revenue report:

![image](https://user-images.githubusercontent.com/444632/213563409-271a8683-99b4-4c67-9082-066abcc13b9c.png)


If we do want to limit it to just that report, perhaps we should make that clear in the verbiage here?

**Comment by ROBERLANDIO** [comment]
https://store-digita.myshopify.com/

**Comment by nathanss** [comment]
@joelclimbsthings 

> That is, with the assumption that you can toggle [this field](https://github.com/woocommerce/woocommerce/blob/fe6ab3ea4e35acc1d3c1618634baab26e45815fd/plugins/woocommerce/src/Admin/API/Reports/DataStore.php#L45) from that query file, and that would do the trick?

I am not sure this assumption will be correct. I'll look into it further when I have the chance. I would just like to know if it's ok or undesirable for the behavior to change in Orders report as well. Then I can think of a solution.

> If we do want to limit it to just that report, perhaps we should make that clear in the verbiage here?

Of course. I agree. I was planning on doing this after we clear the previous doubt.

**Comment by joelclimbsthings** [comment]
Sounds great @nathanss , we'll just wait to confirm with @pmcpinto .

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by pmcpinto** [comment]
@joelclimbsthings @nathanss, sorry I missed this ping. Expanding this option to the Orders report is a good idea, as long as we inform the users about the change. We'll need to show the spotlight tour in the Orders and Overview reports. @jarekmorawski what do you think?

**Comment by nathanss** [comment]
Leaving this open as the default date has not changed yet with https://github.com/woocommerce/woocommerce/pull/36492

**Comment by nathanss** [comment]
I found some issues with #36492 and opened PR #36876 to address them.

**Comment by nathanss** [comment]
PR #36653 closes this issue.
