### ISSUE TITLE
Update post-release process to correctly update readme.

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#35884]
After releasing 7.1.1, the automation created #35881. Instead of adding the new changelog, the PR removed the previous changelog. I'm not sure if this has something to do with the formatting for the patch release, or if it's something else.

**Comment by roykho** [comment]
IIRC, we decided that for point releases, we will handle the changelog manually because of issues like this. It is also noted in the handbook. So I think the only thing we need to do is change the automation to not pick up on point releases?

**Comment by roykho** [comment]
Looking at this more, I thought I remember this. So the workflow that ran came from 7.1 branch which doesn't include the latest validation check to see if it is a patch release. Another words it is already changed in trunk. So I think we can close this.

**Comment by jonathansadowski** [comment]
Thanks. I always forget that about workflows. Perhaps we should make an effort to cherry-pick stuff like this in the future into recent releases, or make a note that it won't happen and that we need to manually address it if a fix release is performed.

It's difficult to keep track of which pieces are covered via automation versus a checklist item, and even more difficult to do that in the context of a fix release 😄
