### ISSUE TITLE
WooCommerce > Analytics > Revenue - broken custom date-range selector

### ISSUE THREAD

**Issue by rwkyyy** [woothemes/woocommerce#35896]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
from WC 6.8.2 (first noticed) to latest version (7.1 as of writing) the date range (custom) in Revenue section of WC Analytics is visually broken and unusable.
![Screenshot 2022-12-08 at 10 54 43](https://user-images.githubusercontent.com/13552349/206404347-28103b8a-71e1-4397-883f-4b0f835d20f3.png)

update: I have tested on two different configuration, same issue.

**Comment by rwkyyy** [comment]
**Describe the bug**
The custom date range filter is broken

**Steps to reproduce the behavior:**

Go to WooCommerce Admin
Click on Analytics
Click on Date Range selector (top left)
select "CUSTOM" range
See error

**Expected behavior**

to not be visually broken

**Isolating the problem (mark completed items with an [x]):**

[x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
[x]This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
[x] I can reproduce this bug consistently using the steps above.
**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://dev.nnnn.n.ro
Site address (URL): https://dev.nnnn.n.ro
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 5 GB
PHP Time Limit: 1200
PHP Max Input Vars: 10000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wpzy_
Total Database Size: 5.47MB
Database Data Size: 3.33MB
Database Index Size: 2.14MB
wpzy_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wpzy_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzy_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzy_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpzy_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpzy_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wpzy_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpzy_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wpzy_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpzy_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_options: Data: 2.05MB + Index: 0.08MB + Engine InnoDB
wpzy_postmeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wpzy_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wpzy_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpzy_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpzy_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzy_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpzy_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzy_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpzy_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzy_wpdatacharts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wpdatatables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wpdatatables_columns: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpzy_wpdatatables_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wpdatatable_1: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzy_wpdatatable_2: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
custom_css: 1
customize_changeset: 4
elementor_library: 1
page: 9
post: 2
postman_sent_mail: 2
product: 1
revision: 9
shop_order: 1
tm_global_cp: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.1.1

### Inactive Plugins (10) ###

Advanced Custom Fields: by WP Engine – 6.0.5
AnyWhere Elementor Pro (Premium): by WP Vibes – 2.24.1
Custom Post Type UI: by WebDevStudios – 1.13.2
Disable WP REST API: by Jeff Starr – 2.4.1
Elementor: by Elementor.com – 3.8.1
Elementor Pro: by Elementor.com – 3.8.2
Envato Elements: by Envato – 2.0.11
Password Protected: by WPExperts – 2.5.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.5
Post SMTP: by Post SMTP – 2.1.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #30 - /magazin/
Cart: #31 - /cos/
Checkout: #32 - /finalizare/
My account: #33 - /contul-meu/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-05 10:03:35 +03:00
Options: ✔
Notes: 40
Onboarding: skipped

### Action Scheduler ###

Complete: 8
Oldest: 2022-11-14 16:57:34 +0200
Newest: 2022-12-09 10:17:33 +0200

Pending: 1
Oldest: 2022-12-10 10:17:33 +0200
Newest: 2022-12-10 10:17:33 +0200


### Status report information ###

Generated at: 2022-12-09 10:18:08 +02:00
`

**Comment by kaushikasomaiya** [comment]
Duplicate of #35470 - @rwkyyy This will be fixed in 7.2 release.
