### ISSUE TITLE
Fix deprecated warning in wc-page-functions

### ISSUE THREAD

**Issue by PaulSchiretz** [woothemes/woocommerce#35903]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`PHP Deprecated:  strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated in xxxx\woocommerce\includes\wc-page-functions.php on line 141`

### Expected behavior

Check if $path or $query is empty and continue the loop before the call to strstr.

```
/**
 * Hide menu items conditionally.
 *
 * @param array $items Navigation items.
 * @return array
 */
function wc_nav_menu_items( $items ) {
	if ( ! is_user_logged_in() ) {
		$customer_logout = get_option( 'woocommerce_logout_endpoint', 'customer-logout' );

		if ( ! empty( $customer_logout ) && ! empty( $items ) && is_array( $items ) ) {
			foreach ( $items as $key => $item ) {
				if ( empty( $item->url ) ) {
					continue;
				}
				$path  = wp_parse_url( $item->url, PHP_URL_PATH );
				$query = wp_parse_url( $item->url, PHP_URL_QUERY );
				if( empty($path) || empty($query) ) {
					continue;
                                 }


				if ( strstr( $path, $customer_logout ) || strstr( $query, $customer_logout ) ) {
					unset( $items[ $key ] );
				}
			}
		}
	}

	return $items;
}
add_filter( 'wp_nav_menu_objects', 'wc_nav_menu_items', 10 );
```

### Actual behavior

Check is not performed and a warning is thrown...

### Steps to reproduce

Just review the code.

### WordPress Environment

WC 7.1.1 PHP 8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ahegyes** [comment]
A similar error is also happening inside `PageController.php`:

```
Deprecated: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in /www/kinsta/public/team51-donations/wp-content/plugins/woocommerce/src/Admin/PageController.php on line 128
```

This is the code at those lines in 7.1.1:

```
$current_query = wp_parse_url( $current_url, PHP_URL_QUERY );
parse_str( $current_query, $current_pieces );
$current_path  = empty( $current_pieces['page'] ) ? '' : $current_pieces['page'];
$current_path .= empty( $current_pieces['path'] ) ? '' : '&path=' . $current_pieces['path'];
```

I noticed this on any admin page with no query string. For example, the dashboard, or the plugins list.

**Comment by barryhughes** [comment]
Thanks for reporting! I'm closing this, however, as we will handle via #36325.
