### ISSUE TITLE
WP admin pages, whitespace under wpadminbar, after activating WooCommerce

### ISSUE THREAD

**Issue by stgoos** [woothemes/woocommerce#35919]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When WooCommerce is active I get a whitespace under the wpadminbar on the backend Admin pages of WordPress, see screenshot in the Actual behavior section.

I disabled all other plugins before disabling WooCommerce. After disabling WooCommerce the whitespace gap is gone. When I then re-activate WooCommerce the whitespace gap is back.

This happens already for a quite some months on all my WordPress + WooCommerce installations, can't remember when it first occurred but I only started looking for the cause of the whitespace gap today.

### Expected behavior

I don't expect this whitespace gap to be there.

### Actual behavior

![image](https://user-images.githubusercontent.com/16466116/206897347-b6ebfb41-877d-4aff-89d7-6053844a9435.png)

### Steps to reproduce

Install the latest version of WordPress and WooCommerce.

Setup multisite, and activate WooCommerce on one of the sites.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://---.com/shop
Site address (URL): https://---.com/shop
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.17-MariaDB-cll-lve-log
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_2_
Total Database Size: 619.75MB
Database Data Size: 565.30MB
Database Index Size: 54.45MB
wp_2_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Data: 9.52MB + Index: 8.03MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Data: 0.36MB + Index: 0.41MB + Engine InnoDB
wp_2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_2_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 10.52MB + Index: 9.09MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 1.48MB + Index: 0.17MB + Engine InnoDB
wp_2_postmeta: Data: 40.56MB + Index: 26.06MB + Engine InnoDB
wp_2_posts: Data: 5.52MB + Index: 1.47MB + Engine InnoDB
wp_2_scc_product_attributes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_termmeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_2_terms: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_2_term_relationships: Data: 0.44MB + Index: 0.23MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_2_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Data: 2.52MB + Index: 1.11MB + Engine InnoDB
wp_2_wc_order_stats: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_product_attributes_lookup: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_2_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_exported_csv_items: Data: 20.55MB + Index: 1.52MB + Engine InnoDB
wp_2_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmailsmtp_emails_log: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_2_wpmailsmtp_email_tracking_events: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wpmailsmtp_email_tracking_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_xyz_ihs_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 1.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.17MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

attachment: 1297
custom_css: 1
nav_menu_item: 30
page: 8
product: 440
revision: 237
shop_order: 9802
shop_order_refund: 0
user_request: 1
vc_grid_item: 1
vc4_templates: 8
vcv_templates: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (18) ###

Classic Editor: by WordPress Contributors – 1.6.2
Crocal Extension: by Euthemians Team – 2.0.6
Duplicate Page: by mndpsingh287 – 4.4.9
Imsanity: by Exactly WWW – 2.8.2
JSON REST API for Multisite: by Ryan McCue – 0.1
Product Customer List for WooCommerce: by Kokomo – 3.1.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.3
WooCommerce Product Dependencies: by SomewhereWarm – 1.2.7
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1
WooCommerce: by Automattic – 7.1.1
WP Mail Logging: by Wysija – 1.10.4
Members: by MemberPress – 3.2.2
Multisite User Management: by Brent Shepherd – 1.1
Password bcrypt: by Roots – 1.0.3
Nav Menu Roles: by Kathy Darling – 2.1.0
WP-Optimize - Clean, Compress, Cache: by David Anderson Ruhani Rabin Team Updraft – 3.2.9
WP Mail SMTP Pro: by WPForms – 3.6.1

### Inactive Plugins (39) ###

BBQ Pro: by Jeff Starr – 3.5.1
Duplicator Pro: by Snap Creek – 4.5.7
Enable Media Replace: by ShortPixel – 4.0.1
Redis Object Cache: by Till Krüss – 2.2.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Visual Composer: by visualcomposer.com – 45.1.1
WooCommerce External Product Embed: by Caleb Burks – 3.0.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
WP REST Cache: by Acato – 2022.2.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (2) ###

scc-mu-config.php: by Steven – 1.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #31577 - /all-products/
Cart: #8707 - /basket/
Checkout: #8708 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Crocal: 2-shop
Version: 2.0.5.1
Author URL: http://euthemians.com
Child Theme: ✔
Parent Theme Name: Crocal
Parent Theme Version: 2.0.5.1
Parent Theme Author URL: https://euthemians.com
WooCommerce Support: ✔

### Templates ###

Overrides: crocal/woocommerce/content-product.php
crocal/woocommerce/content-single-product.php
crocal/woocommerce/loop/loop-end.php
crocal/woocommerce/loop/loop-start.php
crocal/woocommerce/single-product/product-image.php
crocal/woocommerce/single-product/product-thumbnails.php
crocal/woocommerce/single-product/related.php
crocal/woocommerce/single-product/up-sells.php
crocal/woocommerce/single-product.php
crocal/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-11 15:05:20 +01:00
Options: ✔
Notes: 7
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 1
Next export: Not scheduled

### Action Scheduler ###

Complete: 1,021
Oldest: 2022-11-10 11:16:03 +0100
Newest: 2022-12-11 10:51:02 +0100

Failed: 1
Oldest: 2021-11-27 16:15:14 +0100
Newest: 2021-11-27 16:15:14 +0100

Pending: 7
Oldest: 2022-12-11 12:06:02 +0100
Newest: 2022-12-12 10:35:30 +0100

### Status report information ###

Generated at: 2022-12-11 11:04:00 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @stgoos,
Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.1.1 version and WordPress 6.1.1 version. 

Please find below the screenshot for reference :

![#35919](https://user-images.githubusercontent.com/94531721/207247430-646794bd-5310-4564-abab-d80181894c3e.jpg)

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by beaulebens** [comment]
@stgoos please reopen with additional information if you're still seeing this, but we're unable to reproduce on recent versions of WooCommerce. My guess is that your server is perhaps configured to output errors, and you're getting some kind of error on the page. If that's the case, you should also see the errors in your server's error_logs, so including them here would be useful.
