### ISSUE TITLE
[Enhancement]: Uniform Date sale price ends in CSV import and product update behaviours

### ISSUE THREAD

**Issue by roberto-annunziatella-purelab** [woothemes/woocommerce#35964]
### Describe the solution you'd like

I suggest to upgrade the importer about the Date sale price ends field to have the same behaviour as the product update in admin interface to avoid inconsistency of the data imported.

### Describe alternatives you've considered

The supported format by the importer is YYYY-MM-DD, i think is fine but need to save the timestamp as YYYY-MM-DD 23:59:59 just like on product update.

### Additional context

Importing the Date sale price field the format supported YYYY-MM-DD, the importer saves the date specified at time 00:00:00 inside the database.

In admin edit product side, editing the same product imported from CSV, after update converts the same date to 23:59:59 (like suggested from Woocommerce).

That behaviour is very inconsistent because managing to import from CSV a product with Date sale end at YYYY-MM-DD 00:00:00, as soon as the product will be updated from a user in admin the sale end is automatically shifted to YYYY-MM-DD 23:59:59.
At the same time can't managed  a import from CSV with a date YYYY-MM-DD 23:59:59 because the format is not datetime but date only.

A little example with numbers:
1. Import 100 products with the same date sale ends to 2022-10-10 
2. WooCommerce Importer save that date for the price sale end to all 100 products at 2022-10-10 00:00:00
3. Me or other user needs to edit a product in admin interface (for any reason, not necessary sales related) and inside the editing form is correctly filled 2022-10-10 as the date of the end of sale price.
4. On product save, WooCommerce save again the value of Date sales ends for the product at 2022-10-10 23:59:59
5. When the calendar and the clock in the real life reach 2022-10-10 00:00:00 99 products shows the original price but the edited keep showing the sale price until 23:59:59 of the same day

That can be avoided by checking the date before the save and change 2022-10-10 to 2022-10-09, but i don't think is reasonable, at least not reasonable for a programmer XD.
The other way is using a hook filter to change the timestamp saving on import, but why admin interface and importer must invalidate each other? I was struggling between post this in bug section or in enhancement.

---

If you need the steps to reproduce:

1. Install WooCommerce in a clean Wordpress installation
2. Create a product named "Test" with regular price to 10
3. Export the product with these columns (ID,Date sale price ends,Sale price)
4. Edit the exported CSV with the current day you are doing this below "Date sale price ends" column
5. Edit the exported CSV with 5 below "Sale price" column
6. Import the CSV to update "Test" product by ID
7. Visit the product in frontend, should be shown with the regular price 10 without any sale (because now the date is the 00:00:00 of today)
8. Enter inside the product edit in admin
9. Press Update button doing nothing else
10. Visit the product in frontend, should be shown with sale price (because now the date is the 23:59:59 of today)

Thanks for reading, i wanted to be more clear and specific as possible because are years now that i'm experiencing this and now i decided to write here.

**Comment by barryhughes** [comment]
Hi @roberto-annunziatella-purelab: this seems to be essentially the same issue as https://github.com/woocommerce/woocommerce/issues/35321 and so I will close this as a duplicate. Please feel free to monitor the other issue (and if you feel I'm mistaken, just let me know). Thanks!
