### ISSUE TITLE
[Enhancement] Fix the create button at the bottom of the dropdown list

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35969]
**Related to #35851 -- some work on #35851 deals with the AC in this issue**

We noticed in user testing that some people couldn't figure out how to add a new item in the dropdown component. In addition to the existing logic that allows users to type the name and select an option from the list to create a new item, we want to add a fixed button that will be visible at all times.

https://user-images.githubusercontent.com/79307566/207562708-5b87a0d5-40fd-4cdc-93fc-466cf5c875d6.mov

**Acceptance criteria**

- [ ] There's a new item fixed at the bottom of the list. It is visible to users as they scroll up and down the list.
- [ ] Users can quickly navigate to it using the `Tab` key.
- [ ] The button is `Gutenberg-Blue` (it's now `Gutenberg-900`) and says `+ Create new`.
- [ ] Clicking the button or pressing `Enter` opens the item creation modal.
- [ ] When users start typing, the button's label changes to `+ Create "[phrase]"` just like it does now.

**Comment by mdperez86** [comment]
> Newly created item is placed at the bottom of the list.

@jarekmorawski this is not possible if we apply some sorting criteria to the list like: by `name`, or anything different to the `id`

**Comment by octaedro** [comment]
Hey @jarekmorawski,
Considering [this comment](https://github.com/woocommerce/woocommerce/issues/35969#issuecomment-1369817160) is it ok if we remove that AC (_Newly created item is placed at the bottom of the list_)?

**Comment by jarekmorawski** [comment]
Removed. ✔️

**Comment by nathanss** [comment]
I created the issue https://github.com/woocommerce/woocommerce/issues/37043, I think we should migrate to the new TreeControl component before implementing this to avoid rework.

**Comment by nathanss** [comment]
Closed by #37479
