### ISSUE TITLE
Add random order to the filtering results in WooCommerce store[Enhancement]: 

### ISSUE THREAD

**Issue by mastix01** [woothemes/woocommerce#35972]
### Describe the solution you'd like

I would love to see that random order is considered as a filtering and search parameter to show results. I want that from the backend I can make the default value for showing products in random order. Also that the customer has the ability to show products in random order. That makes it great so that all the products in a shop have the opportunity to be seen, not only the most recent,popular etc.

### Describe alternatives you've considered

Until now the only alternative are code snippets to add that behavior but those are cumbersome for a number of reason, the most important one being I have no idea of programming and maintain up to date that code addition

### Additional context

I sell images, thousands of them and I want to surprise my customers with always new content and not always the same. I also want them to see a broad selection that random gives. If my last images uploaded are japanese plants photos of the XIX century searching for last for 99.9% of clients this will be of no interest at all. Giving random will make product rotation much better

**Comment by barryhughes** [comment]
Thanks, @mastix01. It's an interesting idea but we'd like to get a sense of how much demand there might be. So, I'm going to apply our 'votes needed' workflow (that does however mean the issue will be closed...more details will come in an automated follow-up post).

Additionally, you could consider posting a feature request [over here](https://woocommerce.com/feature-requests/woocommerce).
