### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by SKR2004** [woothemes/woocommerce#35974]
### Describe the solution you'd like

Proposal from Saudi Arabia
Because the majority of customers, when reaching order completion, want to know the value of the product before tax and the amount of the tax rate in a separate line
A word that includes tax makes customers wonder if it is with tax when paying or before tax
A word that includes tax that makes the customer confused in completing the order
Please take note into consideration, thank you

----------------
* Show prices while browsing cart / with tax only
And another section
----------------
* Offer upon completion of the order / without tax
It is on the order completion page/checkout page
line before the sum
* taxes
-------
Then the total order with tax
//////

I hope the explanation is sufficient, and I'm sorry, I'm new to this site
And if you need more pictures or explanation from me, I am at your service
![مع الضريبة](https://user-images.githubusercontent.com/99620052/207594784-1af1b5e8-1710-424a-9408-4cac9f4a7d80.jpg)

### Describe alternatives you've considered

[https://prnt.sc/lRcc5yw-qZt_](url)

Proposal from Saudi Arabia
Because the majority of customers, when reaching order completion, want to know the value of the product before tax and the amount of the tax rate in a separate line
A word that includes tax makes customers wonder if it is with tax when paying or before tax
A word that includes tax that makes the customer confused in completing the order
Please take note into consideration, thank you

----------------
* Show prices while browsing cart / with tax only
And another section
----------------
* Offer upon completion of the order / without tax
It is on the order completion page/checkout page
line before the sum
* taxes
-------
Then the total order with tax
//////

I hope the explanation is sufficient, and I'm sorry, I'm new to this site
And if you need more pictures or explanation from me, I am at your service

**Comment by SKR2004** [comment]
I also hope
in the shipping section

Include the names of the states and cities affiliated to the Kingdom of Saudi Arabia
I will help you with the names of the regions, states and cities affiliated to it
And the possibility of allocating a city that is not shipped to or has a special setting
Thank you

**Comment by barryhughes** [comment]
> I hope the explanation is sufficient, and I'm sorry, I'm new to this site
> And if you need more pictures or explanation from me, I am at your service

Welcome to GitHub—and to the WooCommerce project!

We are however just a little confused about the core request. Are you suggesting we add a new setting, and what would this setting do?

WooCommerce already has a range of capabilities relating to tax handling. If you haven't already done so, it could be worth reviewing [our documentation](https://woocommerce.com/document/setting-up-taxes-in-woocommerce/) on this subject, just in case this is something we already provide.

> Include the names of the states and cities affiliated to the Kingdom of Saudi Arabia

Please create a fresh issue for this and one of the team will be happy to look into it. I should also note that in these matters we generally follow the [CLDR standard](https://cldr.unicode.org/), which for example lists the states of each country.

**Comment by SKR2004** [comment]
I will explain with more pictures
Yes, I ask to add another section, which is
When the order is completed, the total products will appear without the tax
And a box or line showing the amount of tax
The last thing is the total including tax

**Comment by barryhughes** [comment]
Some more pictures would be great, thank you.

**Comment by SKR2004** [comment]
Hello guys after a long absence

The basic proposal to make the idea clear to everyone
--------------------------------------------
When determining prices, taxes are inclusive
It appears to the customer that the price includes tax
upon completion of the purchase
Shows total amount = $250
Underneath it appears writing (Value Added Included *****)
-------------------------------------------
My suggestion is to add an option in WooCommerce
determined by the merchant
- Does he want to show the value in and from the sum?
- Or a separate tax line appears
- The actual value of the product, excluding the separate tax
Then it will be on the client page
-
The line displays Total - Tax Inclusive
I hope my explanation is adequate, adequate and clear

**Comment by barryhughes** [comment]
I suppose I'm still a little confused. Let's say we have the following settings:

- A 10% tax that applies everywhere.
- Prices entered with tax: *Yes, I will enter prices inclusive of tax.*
- Display prices in the shop: *Including tax.*
- Display prices during cart and checkout: *Including tax.*

That seems like it would meet your goals, because:

> When determining prices, taxes are inclusive

So if a product costs `45.45` the tax will be `4.55` and the price displayed to the customer will be `50.00` ✅ 

> It appears to the customer that the price includes tax
upon completion of the purchase

In the cart, they will see a total and subtotal of `50.00` ✅ 

> Shows total amount = $250
> Underneath it appears writing (Value Added Included *****)

Below the total, it will display `(includes $4.55 Tax)` and something very similar can be seen in the checkout ✅

<div align="center"><img width="600" alt="cart-totals" src="https://github.com/woocommerce/woocommerce/assets/3594411/70b0b045-459f-4008-a22b-b6dce081d40b"></div>

**Comment by SKR2004** [comment]
What is meant here is that there is an option determined by the store owner
customer's final product
Without the word include or include
So that it appears to the customer in the table
Product price / 45.45
Tax / 4.55
Total including tax / 50.00
This is the destination
Customers be there when they see a word include
They write to us on WhatsApp, and the direct question now is how much is the price
Is the price shown with tax or will I pay the tax later?
And we got into a whirlpool because of this issue
That is why I suggest this amendment and adding this option to detail the schedule for the client more clearly

**Comment by barryhughes** [comment]
OK, understood—but I'm a little unsure how much need there is for this across our user-base (especially since, given the configuration I outlined in my last reply, it becomes clear that the total price includes tax).

This does however seem like a good candidate for customization work (WooCommerce is very flexible and, if this is something you need, it's certainly possible to make things work this way). Alternatively, you could post your suggestion [over here](https://woocommerce.com/feature-requests/woocommerce/), which will allow other users to 'up-vote' your idea. If it then becomes apparent that there is a lot of demand for this, we can definitely revisit.

Thanks again!

**Comment by SKR2004** [comment]
Thank you
I want another service from you
And now you understand me
I want you to write my proposal
In an arranged way, because I do not respond to writing in English better, because I use the translator and sometimes
The translator does the reverse
Will you serve me?
In writing my order neatly

**Comment by barryhughes** [comment]
Here's some text, and a screenshot: feel free to adjust as needed and post direct on the feature board (that way, if clarification is needed, the team can potentially reach out to you direct).

<div align="center"><img width="700" alt="unit-tax-subtotal" src="https://github.com/woocommerce/woocommerce/assets/3594411/577102de-caf4-401c-be1e-a9ab49c6c18a"></div>

> I use tax-inclusive pricing, and would like an option to display the cost before tax, and the tax amount, for each line item. This should happen within the cart and within the checkout.

When posting the request, you can supply the following URL if you want to link to the above screenshot:

`https://github.com/woocommerce/woocommerce/assets/3594411/577102de-caf4-401c-be1e-a9ab49c6c18a`
