### ISSUE TITLE
[Enhancement] Adding proper return management to WooCommerce

### ISSUE THREAD

**Issue by luissimo** [woothemes/woocommerce#35973]
### Discussed in https://github.com/woocommerce/woocommerce/discussions/35709

<div type='discussions-op-text'>

<sup>Originally posted by **luissimo** November 24, 2022</sup>
Hi,

I wanted to stir up a discussion about order return management for WooCommerce.

We are running a big WooCommerce store with over 120k order/years and we are at a point that we need an external partner to integrate a return management solution for us. However all these third parties only partially support WooCommerce because there is no return management system. Such a system needs the following functionality
- Register a return
- Apply different states to a return (eg. Expected, In Progress, Approved, Completed)
- Refund the return or create a coupon

All the other big E-commerce platforms already have this functionality.
- Shopify
- Lightspeed
- Magento 1 & Magento 2
- Shopware
- BigCommerce

The third parties(multiple) advise us explicitly to switch to a different platform. Which is something we are almost forced to do to keep everything running operationally.

Sure there are some plugins that can do this but third parties don't support plugin functionality but only core functionality. And this is an essential part for any e-commerce website.

Is this something that is planned or possible to integrate in the near future?

</div>

**Comment by barryhughes** [comment]
Thanks for posting this, @luissimo, and thank you for creating the post over on the discussion board.

For the time being, I think it's best to keep this in one spot so I'm going to close this issue and we can [keep the discussion going over there](https://github.com/woocommerce/woocommerce/discussions/35709). If anyone else is interested in developing this idea, please don't hesitate to add your thoughts to that thread.
