### ISSUE TITLE
Add single product variation General section

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35987]
On the new product variation screen, we need to add the General tab content.  This should include the "Variant Details" section and the "Images" sections.

Blocked by https://github.com/woocommerce/woocommerce/issues/35786

### Design

Figma: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/207727344-7fc32736-767f-4892-b758-3427e3fabc0b.png)

### Acceptance Criteria

* [ ] Opening a product variant should display the respective sections with the copy in Figma
* [ ] The images section should look and behave similarly to the parent product page's image section
* [ ] The variant details section should include a "Description" section
* [ ] The variant details section should include a visibility toggle that controls the `variable_enabled` property for the variation
* [ ] All fields should persist on refresh

**Comment by joshuatf** [comment]
Estimate: 2

Most of the groundwork for this has been completed as part of the initial product experience.  Those components should be mostly reusable with the exception of the "Variant Details" section which is new.

**Comment by jarekmorawski** [comment]
> Those components should be mostly reusable with the exception of the "Variant Details" section which is new.

`Variant details` is the same as `Product details` in the main product form but contains different fields. I've tweaked the design to include a single image, instead of a full gallery.

- Empty state: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=15Gzqs0okyuSYOxm-4
- Image uploaded: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A20506&t=15Gzqs0okyuSYOxm-4
