### ISSUE TITLE
Change per page picker options in pagination component

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#35984]
The pagination component does not has a way to change the options shown in the per page picker component.

It has a default set of options hardcoded inside of it.

https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/pagination/index.js#L12

#### Acceptance criteria
- [ ] The pagination component should receives a new set of options from the consumer
- [ ] The new options should be shown as items of the per page picket component
- [ ] If no new options were passed then the picker should shown the default ones

**Comment by joshuatf** [comment]
Estimate: 1

**Comment by pmcpinto** [comment]
@mdperez86 is this still something that should be implemented?

**Comment by mdperez86** [comment]
This was done already!!!
