### ISSUE TITLE
Product variations should inherit parent product properties

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35989]
Each variation should inherit data from its parent product.  For example, a description will contain the same description as its parent unless overwritten.

Blocked by https://github.com/woocommerce/woocommerce/issues/35786

### Design

Figma: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/207732313-e5965d8e-174d-47f8-8629-47a667d382fd.png)

### Acceptance Criteria

* [x] Pricing, stock status, sku, and dimensions should all inherit these properties from parents and show placeholders for these items
* [x] Before toggling the "Manage stock" property, the stock should follow the parent (omit it from the variation update if set to `parent`)
* [x] Updating any of these properties should use the newly added value, overriding the parent
* [x] The shipping class dropdown should include a "Same as parent" option that inherits the parent property when not changed
* [x] SKU field should not be included in update until overridden (defaults to parent SKU which causes a duplicate SKU error).

**Comment by joshuatf** [comment]
@pmcpinto @jarekmorawski I tweaked the above acceptance criteria slightly.  I just want to double check that those sound good before I mark this issue as ready.

I also wanted to clarify that if we directly inherit the parent's description (or any other properties), as soon as they save the variation, that description would be persisted even if the parent changed.  For example:
1. Parent description is 'X'
2. Variant description (inherited): 'X'
3. Variant saved
4. Parent description updated to 'Y'
5. Variant description is still 'X' since it was previously persisted

Is this the intent behind this?  Or is it to keep the variant identical to the parent until the user manually changes it?

**Comment by jarekmorawski** [comment]
> Or is it to keep the variant identical to the parent until the user manually changes it?

It's actually this. The fields should be synced until the user manually changes them. So, if the parent description changes from 'X' to 'Y', it should also change in the variant description. It reflects the user experience on the product page, which remains the same for all variations unless the merchant adds some extra information.

Not sure if this can be helpful from the code POV, but the way I imagined it, we could make the variant field values blank, meaning that the product page would show content default to the main product data as long as there's no custom information added manually to a single variation.

Only when the user enters an individual variation details screen, we will load the content from the parent product (it's okay to show a loader for a second), rather than keeping a record of several identical descriptions.

**Comment by joshuatf** [comment]
>Not sure if this can be helpful from the code POV, but the way I imagined it, we could make the variant field values blank, meaning that the product page would show content default to the main product data as long as there's no custom information added manually to a single variation.

After a brief Slack discussion, I think we might be aiming for placeholder text, what do you think?  Some fields have a "Same as parent" in the legacy experience, but others don't and the way it's designed we don't yet have any way of syncing those fields. 
 I'd recommend holding off on syncing fields that need values in order to operate.

* **Price** - Inherits from parent if not set.  Can show placeholder with the parent value here.
* **Dimensions** - Inherits from parent if not set.  Can show placeholder with the parent value here.
* **Shipping** - Has a "Same as parent" option.
* **Image** - In the legacy UI, only one image can be set and the REST API has the same schema.  I think we might need to tweak the design for images in variations.
* **Stock status** - If stock status is not set to manual, the variation needs to have a stock status set and cannot directly inherit from the parent.  
* **Description** - for variations is actually shown in a different place than the product description (depending on the theme) and might be weird if it matched the parent description.  I think leaving this blank is the right way forward.
![Image](https://user-images.githubusercontent.com/10561050/208154962-054362cd-f7f9-4a39-878f-8f847b07a9d9.png)

**Comment by pmcpinto** [comment]
> It's actually this. The fields should be synced until the user manually changes them. So, if the parent description changes from 'X' to 'Y', it should also change in the variant description. It reflects the user experience on the product page, which remains the same for all variations unless the merchant adds some extra information

+1. I think this also prevents us from creating more than 1 variation in the DB until the user edits a variation, right?

**Comment by joshuatf** [comment]
>I think this also prevents us from creating more than 1 variation in the DB until the user edits a variation, right?

By the point they've gotten to the variation page, the variation will already exist in the database (they'll get automatically generated on option creation).

@pmcpinto @jarekmorawski Can you confirm that the [above list and expectations](https://github.com/woocommerce/woocommerce/issues/35989#issuecomment-1355302215) are good?

**Comment by pmcpinto** [comment]
> By the point they've gotten to the variation page, the variation will already exist in the database (they'll get automatically generated on option creation).

I think we should avoid having more than one variation in the DB if the product data is the same across all variations. Suppose you have a product with 2 attributes: Color (Green, Blue, Red) Size (XL, L, S). You automatically create a variation for each combination in the front-end, but in the DB you only have one variation (Any color + Any size).
New variations should only be created in the DB when the user changes one or a group of variations. For example, if the user adds a sale price to all the variations with Green, we create a new variation in the DB (Green + Any size). Makes sense?

cc @jarekmorawski in case I'm missing anything as we chatted about this a couple of days ago.

**Comment by joshuatf** [comment]
We discussed briefly on our call, but typically variations will need a DB row per variation.  This is a legacy pattern and not one we'll easily be able to change, but we could look at more performant options if it becomes an issue (though this might have to be in the millions of variations before we see any detrimental effects).

Front-end performance generation could be something where perceived performance is an issue, but we can follow up on this later.

In the meantime for this issue, we should make sure that [this list](https://github.com/woocommerce/woocommerce/issues/35989#issuecomment-1355302215) seems adequate for inheriting parent properties.  It should mostly match what exists in the legacy products to avoid creating issues with stored schema on the backend.

**Comment by jarekmorawski** [comment]
> After a brief Slack discussion, I think we might be aiming for placeholder text, what do you think?

Yes! The goal of syncing the values is to:

1. to let people easily modify the parent product's data
2. give them a starting point for editing the variations
3. ensure them that they've not wasted time building the parent product (which is important because we no longer let them access the Pricing, Inventory, and Shipping tabs when the variations are added).

It sounds like placeholders are an easy way to get there. I've suggested a simple tweak below that could make them even more useful.

> Price - Inherits from parent if not set. Can show placeholder with the parent value here.

> Dimensions - Inherits from parent if not set. Can show placeholder with the parent value here.

LGTM! Can we make it so that when the user clicks the price or dimension field, we insert the parent's value and let them edit it? For example, if the parent is priced at $10.99, the user sees that price as a placeholder in the individual variation view. When they click the field, the price is set to $10.99, and they can change it to $11.99 using the keyboard instead of re-typing the number.

> Shipping - Has a "Same as parent" option.

Sounds good. We can add it to the shipping class dropdown like in the current UX.

> Image - In the legacy UI, only one image can be set and the REST API has the same schema. I think we might need to tweak the design for images in variations.

I agree. I've updated the designs and added a link to the respective issue.

> Stock status - If stock status is not set to manual, the variation needs to have a stock status set and cannot directly inherit from the parent.

Can we at least copy the value from the parent? For example, if the parent has tracking enabled and the quantity is 100, can we apply the same to the children?

> Description - for variations is actually shown in a different place than the product description (depending on the theme) and might be weird if it matched the parent description. I think leaving this blank is the right way forward.

Sounds good.

**Comment by pmcpinto** [comment]
> @pmcpinto @jarekmorawski Can you confirm that the https://github.com/woocommerce/woocommerce/issues/35989#issuecomment-1355302215 are good?

@joshuatf yes. I just want to clarify two things:
Price: are you including regular and sale price or just regular?
Image: let's stick with one image per variation for now.

**Comment by joshuatf** [comment]
>Price: are you including regular and sale price or just regular?

Good question.  We'll include both.


>Image: let's stick with one image per variation for now.

👍

**Comment by joshuatf** [comment]
>Can we at least copy the value from the parent? For example, if the parent has tracking enabled and the quantity is 100, can we apply the same to the children?

I think so.  I just checked and I think the default behavior is to use the stock quantity from the parent when the variation is created.  As long as the "Manage stock" option is not toggled in the variation, it will follow the parent.

**Comment by joshuatf** [comment]
I've updated the description of this PR with the correct AC and this should be ready to be worked on.

**Comment by joshuatf** [comment]
Estimate: 2

Most of this PR is converting parent items to placeholders which should be straightforward, but leaning on the safer side since there's some oddities around the SKU and `parent` values in the variation response.

**Comment by mdperez86** [comment]
@joshuatf With the current API implementation that we have anytime I change a product from simple to variable or create a variable directly the pricing props (regular_price and sale_price) are always blank whithout any numeric value. So I cannot use them as the placeholder in variation pricing section fileds. 
A prop called `price` contains the single product regular_price or sale_price but not both. So that prop is also not usefull.
What is the suggestion in that case?
cc: @pmcpinto @jarekmorawski

**Comment by mdperez86** [comment]
@joshuatf In case of dimensions (LxWxH) and weight, these props are been optained/inherited from the parent product on the server side, so these values are automatically returned in each variation request by default.
What to do in this case? 
cc: @pmcpinto @jarekmorawski

**Comment by joshuatf** [comment]
>A prop called price contains the single product regular_price or sale_price but not both. So that prop is also not usefull.
What is the suggestion in that case?

@mdperez86 I would argue that the product REST endpoint should return the original product prices when the `context` is set to `edit` to allow retrieving information, even when the product is variable.  However, this means you'll need to contact Proton or git blame whoever previously worked on these to make sure this won't break other functionality.

If that is not an option, we could include the parent prices as a part of the `meta_data` field when retrieving the variation in the `edit` context.

>In case of dimensions (LxWxH) and weight, these props are been optained/inherited from the parent product on the server side, so these values are automatically returned in each variation request by default.

Sounds like a bug in the API response again.  I would expect those numbers to be empty in the `edit` context.  These lines should be updated:

https://github.com/woocommerce/woocommerce/blob/7d32d553cf9748f04f866c1eb2c309f30601c62e/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php#L100-L102

Using `$object->get_length( $context )` where the context is `edit` should retrieve the expected (empty) value.

**Comment by mdperez86** [comment]
@joshuatf it's happening for sku also.

**Comment by mdperez86** [comment]
@joshuatf Also imagine we are creating a brand new variable product, the legacy UI does not have a place (Pricing section) to save those prices. From where we obtain those values to use tham as placeholders? What happen in that case?
cc: @pmcpinto @jarekmorawski

**Comment by joshuatf** [comment]
>it's happening for sku also.

Same comments as above regarding the `sku`.  It can either be included in the parent product or meta data if that's not acceptable for other teams.

>From where we obtain those values to use tham as placeholders? What happen in that case?

I would say if there's no price on the parent product, the variation should not have a placeholder price.  Let me know if you disagree @jarekmorawski or @pmcpinto but I would consider most solutions to that outside the scope of this issue and we could follow up with another.

**Comment by pmcpinto** [comment]
> I would say if there's no price on the parent product, the variation should not have a placeholder price. Let me know if you disagree @jarekmorawski or @pmcpinto but I would consider most solutions to that outside the scope of this issue and we could follow up with another.

Sounds good to me.
