### ISSUE TITLE
Product variations should prompt for unsaved changes

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35992]
If the product variation form is in a dirty state with unsaved changes, the user should be prompted before leaving the page.

Most of this should already be taken care of by `usePreventLeavingPage` which is utilized in the product form, but may or may not need minor tweaking to work with the variation.

Blocked by https://github.com/woocommerce/woocommerce/issues/35987 or https://github.com/woocommerce/woocommerce/issues/35988

### Design

Figma: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/207737091-56986b61-ae5b-43c5-968a-894c8b9b3519.png)

### Acceptance Criteria

* [ ] A confirmation modal should be shown to users who attempt to navigate away from a variation with unsaved changes
* [ ] Using the variation navigation component to switch between variations should trigger the same modal

**Comment by joshuatf** [comment]
Estimate: 1

This logic should already be in place in the product form which will probably be reused.  Hopefully only minor tweaks, if any, will be needed.

**Comment by mdperez86** [comment]
@joshuatf I was testing this in Pricing Inventory and Shipping tabs in Variations Page and it's working as expected so I'm 90% sure this issue is not required.

**Comment by joshuatf** [comment]
@mdperez86 Thanks for checking!  I just checked as well and it does appear to be working well as is.  Closing this issue.
