### ISSUE TITLE
Add product variation attributes to product header

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35990]
When entering the new product variation edit screen, we should add the variant options to the header to make it clear which variation we're currently editing.

Blocked by https://github.com/woocommerce/woocommerce/issues/35786

### Design

Figma: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/207735029-cf2dfb0e-73e1-4f82-9f08-606c4ac83f63.png)

### Acceptance Criteria

* [ ] The variation options should be SlotFilled into the header as the next level after the parent product name
* [ ] Multiple options should be comma separated
* [ ] Longer option combinations should be truncated with `...`. Users should be able to see the variation name in full on mouse hover.

**Comment by joshuatf** [comment]
@jarekmorawski What happens if a variation contains many attribute options.  Do we truncate this list in some way?  And would it still be useful to identify a variation if we did (i.e., should we include the variant ID)?

I currently set the acceptance criteria to comma separated for multiple values, but open to other forms if you feel there is a better design option.

**Comment by jarekmorawski** [comment]
Very good question, thanks for bringing it up. I agree that options should be comma separated. If they exceed the maximum number of characters (I'm not sure if we set any, but I wonder if it could be smart, considering the amount of available space in the header?), we should truncate the values with `...` and show the full variation name on mouse hover.

> (i.e., should we include the variant ID)?

Why do you think it would be useful?

**Comment by joshuatf** [comment]
~~Thanks for the info!  Will update the AC in this issue.~~ I see you beat me to it 😄 

>Why do you think it would be useful?

I'm not really sure how much store owners use them, but they are shown in the old experience.  If we had a long list of attributes, I know personally I would find it easier to both read and say "We need to update the price on variation 140" instead of "We need to update the price on the Shirt variation with the options Red, Medium, Slim, V-neck, Cotton, Logo on back."

But this really applies more to products with many options.

**Comment by joshuatf** [comment]
Estimate: 2

**Comment by jarekmorawski** [comment]
> I would find it easier to both read and say "We need to update the price on variation 140" instead of "We need to update the price on the Shirt variation with the options Red, Medium, Slim, V-neck, Cotton, Logo on back."

Good point. I have never heard merchants refer to variations by ID (even those with 1000s of options), but maybe I haven't listened for it. The new UX will have more robust filtering options in the near future, so I suspect IDs won't be that important. They'll be easy to add anyway, so I'd leave them out for now and focus on core functionality. 👍
