### ISSUE TITLE
Clunky word break of button text in notices on Twenty Twenty One theme

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#36027]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to some of my other tickets about notices on default themes... the twenty twenty one theme add to cart notice looks funky at mobile due to the flex layout:
![image](https://user-images.githubusercontent.com/507025/207934992-7356f44d-fdeb-4adc-a9f1-acc25c84422b.png)

I wouldn't be surprised if this problem occurred in the other default themes.

### Expected behavior

Line break at space, not word. 
Could either put the notice and the button on separate lines/rows... or shrinking padding and button text size might be enough.

### Actual behavior

Button text wraps mid-word

### Steps to reproduce

Activate Twenty Twenty-One theme
Add a product to the cart
View at small/mobile size

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by helgatheviking** [comment]
In general, it looks like the padding on the notice AND the padding on the button do not change. I think the ideal would be that the mobile padding is less than desktop padding.

I think it could also be an improvement to unify this across all the default themes and rely on the default theme sheets for adding color tweaks.

**Comment by swatipawarGS** [comment]
Hi @helgatheviking,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.2.0 version and WordPress 6.1.1 version. 

Please find below the screenshot for reference :
![#36027](https://user-images.githubusercontent.com/94531721/208042083-e2e24fdd-fc08-4152-bed9-2d1558846dab.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by helgatheviking** [comment]
Sure thing. It's obviously not critical, but I think it could be part of a bigger project:

1. unify the default styles... there's a stylesheet for each twenty twenty-ish theme and what if that could be done with just some css vars instead and allow the main woocommerce stylesheet to handle default notices. 

2. revisit all styles on mobile. I bet this isn't the only place that looks funky on a phone.
