### ISSUE TITLE
Notification for block list does not work

### ISSUE THREAD

**Issue by DChen810** [woothemes/woocommerce#36024]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Notification message for Blocked users setting in Anit Fraud does not work. When I set notification, it still shows "email account is block".

### Expected behavior

It suppose to show the notification I setted.

### Actual behavior

it still shows "email account is block".

### Steps to reproduce

go to Woocoomerce setting
go to Anti Fraud
go to general settings
go to Pre Purchase Assessment
enable checking
set the notification

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://fashionandfascinating.com
Site address (URL): https://fashionandfascinating.com
WC Version: 7.2.0
REST API Version: ✔ 7.2.0
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.0
WC Database Prefix: wp_
Total Database Size: 811.22MB
Database Data Size: 430.99MB
Database Index Size: 380.23MB
wp_woocommerce_sessions: Data: 3.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 8.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 68.59MB + Index: 69.69MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.34MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 22.06MB + Index: 23.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 13.03MB + Index: 12.03MB + Engine InnoDB
wp_aioseo_cache: Data: 2.11MB + Index: 2.55MB + Engine InnoDB
wp_aioseo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_links_suggestions: Data: 0.03MB + Index: 0.05MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 1.45MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_redirects: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_aioseo_redirects_404: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_redirects_404_logs: Data: 2.03MB + Index: 0.17MB + Engine InnoDB
wp_aioseo_redirects_hits: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_redirects_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_comments: Data: 56.58MB + Index: 31.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.45MB + Index: 0.88MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.11MB + Index: 0.33MB + Engine InnoDB
wp_e_submissions_values: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 3.03MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_customer_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_paymentmethod_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_payment_id_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_product_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_shipping_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_tax_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_variation_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_wq_cf_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.34MB + Index: 0.42MB + Engine InnoDB
wp_postmeta: Data: 162.69MB + Index: 185.95MB + Engine InnoDB
wp_posts: Data: 15.52MB + Index: 8.02MB + Engine InnoDB
wp_taxjar_record_queue: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 35.56MB + Index: 23.06MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 2.52MB + Index: 1.86MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 4.52MB + Index: 4.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 1.95MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_fraud_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.19MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
attachment: 1744
custom_css: 1
elementor_library: 9
hurrytimer_countdown: 1
jet-menu: 1
jet-smart-filters: 2
jet-woo-builder: 3
mc4wp-form: 1
nav_menu_item: 46
ocn-request: 438
oembed_cache: 4
page: 23
post: 10
product: 194
product_variation: 243
revision: 453
shop_coupon: 107
shop_order: 32613
shop_order_refund: 1044
us_content_template: 4
us_grid_layout: 8
us_header: 1
us_page_block: 11
wp_global_styles: 1
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

Advanced Cancel Order for WooCommerce: by FantasticPlugins – 1.6
Advanced Custom Fields: by WP Engine – 6.0.6
AIOSEO - Image SEO: by All in One SEO Team – 1.1.3
AIOSEO - Link Assistant: by All in One SEO Team – 1.0.11
AIOSEO - Redirects: by All in One SEO Team – 1.2.6.1
AIOSEO - REST API: by All in One SEO Team – 1.0.3
AIOSEO - Video Sitemap: by All in One SEO Team – 1.1.8
Akismet Anti-Spam: by Automattic – 5.0.2
All in One SEO Pro: by All in One SEO Team – 4.2.8
PublishPress Capabilities: by PublishPress – 2.6.1
Contact Form 7: by Takayuki Miyoshi – 5.7
Facebook for WooCommerce: by Facebook – 3.0.6
Facebook Chat Plugin - Live Chat Plugin for WordPress: by Meta – 2.5
WooCommerce FedEx Shipping Plugin with Print Label: by PluginHive – 4.6.8
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.11.0
Google Listings and Ads: by WooCommerce – 2.3.3
Jetpack: by Automattic – 11.7-a.3
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Klarna On-Site Messaging for WooCommerce: by krokedil
klarna – 1.10.0

Klarna Order Management for WooCommerce: by klarna
krokedil – 1.7.1

Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.12.1

Mailchimp for WooCommerce: by Mailchimp – 2.7.6
OptinMonster: by OptinMonster Popup Builder Team – 2.11.1
Pinterest for WooCommerce: by WooCommerce – 1.2.6
Super Product Variation Swatches: by Joe Iz – 2.0
SVG Support: by Benbodhi – 2.5.5
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
TikTok: by TikTok – 1.0.13
URL Coupons for WooCommerce: by WPFactory – 1.6.6
UpSolution Core: by UpSolution – 8.12.2
WooCommerce Additional Variation Images: by WooCommerce – 2.3.0
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.8
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.4.0
WooCommerce Payments: by Automattic – 5.1.2
WooCommerce PayPal Payments: by WooCommerce – 2.0.1
WooCommerce Product Bundles: by WooCommerce – 6.17.3
WooCommerce Shipping & Tax: by WooCommerce – 2.1.0
WooCommerce Shipment Tracking: by WooCommerce – 1.9.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce Smart Coupons: by StoreApps – 6.8.0
WooCommerce: by Automattic – 7.2.0
YITH Pre-Order for WooCommerce Premium: by YITH – 2.8.0
YITH WooCommerce Wishlist: by YITH – 3.16.0
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.8

### Inactive Plugins (5) ###

All in One SEO: by All in One SEO Team – 4.2.8
FileBird Lite: by Ninja Team – 5.1
HurryTimer: by Nabil Lemsieh – 2.7.3
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.12
WooCommerce Sync for QuickBooks Online - by MyWorks Software: by MyWorks Software – 2.7.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.2
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #265 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 8.12
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Impreza-child/woocommerce/emails/customer-new-account.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://fashionandfascinating.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — Texas

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

PayPal: refunds
Klarna Payments: products
refunds

### Product Bundles ###

Database Version: 6.17.3
Loopback Test: ✔
Template Overrides: –

### Klarna Payments Request Log ###

2022-12-01 17:04:35: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"SESSION_COMPLETED\",\n  \"error_messages\" : [ \"Session has already been completed\" ],\n  \"correlation_id\" : \"0cf57186-dd10-470f-a679-4e06f99400a1\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-28 12:40:25: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"6b2623b0-87ef-428d-9ebc-69ac59bd83b8\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-25 12:10:17: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"fa145845-9be1-4ad5-a7cc-a2e08c39f652\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-17 13:00:43: KP Place Order
Response code: 409
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Not matching fields: [order_amount
Incorrect number of items in the cart. Expected: 6
Actual: 4]\" ],\n  \"correlation_id\" : \"80b71dd3-7ffc-4e71-abe5-0808c5319aa8\"\n}","response":{"code":409,"message":"Conflict"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-14 23:25:30: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"bf9d19ae-e82b-4db1-997b-97cb290f2289\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-11 02:26:08: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"SESSION_COMPLETED\",\n  \"error_messages\" : [ \"Session has already been completed\" ],\n  \"correlation_id\" : \"23c10b43-76a1-4714-98aa-c3ad38318062\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-07 22:24:55: KP Create Session
Response code: 500
Response message: {"headers":[],"body":"<html>\r\n<head><title>500 Internal Server Error<\/title><\/head>\r\n<body>\r\n<center><h1>500 Internal Server Error<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n","response":{"code":500,"message":"Internal Server Error"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-07 22:24:50: KP Create Session
Response code: 500
Response message: {"headers":[],"body":"<html>\r\n<head><title>500 Internal Server Error<\/title><\/head>\r\n<body>\r\n<center><h1>500 Internal Server Error<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n","response":{"code":500,"message":"Internal Server Error"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-07 22:24:46: KP Create Session
Response code: 500
Response message: {"headers":[],"body":"<html>\r\n<head><title>500 Internal Server Error<\/title><\/head>\r\n<body>\r\n<center><h1>500 Internal Server Error<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n","response":{"code":500,"message":"Internal Server Error"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-07 22:24:42: KP Create Session
Response code: 500
Response message: {"headers":[],"body":"<html>\r\n<head><title>500 Internal Server Error<\/title><\/head>\r\n<body>\r\n<center><h1>500 Internal Server Error<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n","response":{"code":500,"message":"Internal Server Error"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-10-28 14:06:25: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"SESSION_COMPLETED\",\n  \"error_messages\" : [ \"Session has already been completed\" ],\n  \"correlation_id\" : \"a850f900-5b3f-41de-8030-f6555944d59b\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-10-28 13:58:17: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"9b5d72ea-44c3-49fc-869c-60e917b05304\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

### Klarna Countries ###

Production Countries: US
Test Countries: No countries selected

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-15 20:32:23 -07:00
Options: ✔
Notes: 129
Onboarding: completed

### WooCommerce Payments ###

Version: 5.1.2
Connected to WPCOM: Yes
Blog ID: 183335761
Account ID: acct_1HwgDr2Ht2C6u3L3

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Canceled: 378
Oldest: 2022-11-14 17:27:14 +0000
Newest: 2022-12-15 02:04:41 +0000

Complete: 56,568
Oldest: 2022-11-14 17:00:19 +0000
Newest: 2022-12-15 16:19:50 +0000

Failed: 85
Oldest: 2021-05-19 22:42:05 +0000
Newest: 2022-12-14 18:10:09 +0000

In-progress: 2
Oldest: –
Newest: –

Pending: 22
Oldest: 2022-12-15 16:28:07 +0000
Newest: 2023-02-06 18:40:06 +0000

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2022-12-15 09:20:47 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
This is not the correct channel to report on 3rd party extensions. If you bought your extension on WooCommerce.com, then I would suggest you create a ticket [here](https://woocommerce.com/my-account/create-a-ticket/) Otherwise contact the developer of whom you purchased the extension from.
