### ISSUE TITLE
Product variation order should be persisted on save

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36060]
On a parent product page, the variations list is sortable.  Currently sorting does not yet persist on save.

Note that https://github.com/woocommerce/woocommerce/pull/35980 introduces an endpoint to generate new variations.  I believe the sorting there does not break custom sorting, but this should be verified and fixed if necessary.

### Design

Figma: BaoQ3PGPnhAiJCsJtxgej3-fi-102%3A10092&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/208217294-c6a144ed-cb74-43b4-afce-605068953197.png)

### Acceptance Criteria

* [ ] Reordering product variations should persist on refresh
* [ ] Automatic generation of new variations should not break existing variation order

**Comment by joshuatf** [comment]
Estimate: 2

Tracking the sorting order in state has proven to be a little tricky.  That along with time to confirm that auto generation does not break this warrants a "2" IMO.

**Comment by joshuatf** [comment]
@mdperez86 noted that this issue will probably need batch updating added to the data store, so we're bumping this estimate to a "3".

**Comment by mdperez86** [comment]
@joshuatf 

> Currently sorting does not yet persist on save.

Do that means we are ONLY going to persist the variation orders on product save?

If the anwser is yes then:

> Reordering product variations should persist on refresh

only apply after saving the product right? Because if the user change any variation order locally and refresh the page without saving the product then the order will be lost.

**Comment by joshuatf** [comment]
Great question @mdperez86.  @jarekmorawski do you have a preference on this?

**Comment by jarekmorawski** [comment]
As discussed on yesterday's call, the sorting order should be stored locally and only applied to the product when the user saves, updates, or publishes the product. We should also remember the order across pages in the variation list so that the user won't have to update the product each time they use the pagination.
