### ISSUE TITLE
PHP Error on Wordpress/Woocommerce

### ISSUE THREAD

**Issue by Ladyglow** [woothemes/woocommerce#36098]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I have an issue with one of my websites. Tools > Site Health, I have this information : 

" Une session PHP active a été détectée Performance

Une session PHP a été créée par un appel de fonction session_start(). Cela interfère avec l’API REST et les requêtes de boucle (loopback). La session devrait être fermée par session_write_close() avant d’effectuer toute requête HTTP." 

I've desabled Woocommerce & the error is not available any more. But when I re install 
Woocommerce, I have this error. 

Do you know why & how can I solve this ? 
Thank you ! 

### Expected behavior

No PHP Error !

### Actual behavior

1 problème critique

Les anomalies critiques sont des éléments qui peuvent avoir un impact important sur les performances ou la sécurité de votre site, et la résolution de ces problèmes doit être une priorité.
Une session PHP active a été détectée Performance

Une session PHP a été créée par un appel de fonction session_start(). Cela interfère avec l’API REST et les requêtes de boucle (loopback). La session devrait être fermée par session_write_close() avant d’effectuer toute requête HTTP.

### Steps to reproduce

Go to TOOLS
Site health 
Performance problem

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://jane-hemphouse.com
Site address (URL): https://jane-hemphouse.com
WC Version: 7.2.1
REST API Version: ✔ 7.2.1
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 Mo
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1q-fips

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.1
WC Database Prefix: bvn_
Taille totale de la base de données: 279.27MB
Taille de la base de données: 232.51MB
Taille de l’index: 46.76MB
bvn_woocommerce_sessions: Données : 0.03MB + Index : 0.02MB + Moteur InnoDB
bvn_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
bvn_woocommerce_order_items: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
bvn_woocommerce_order_itemmeta: Données : 0.30MB + Index : 0.25MB + Moteur InnoDB
bvn_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
bvn_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_actionscheduler_actions: Données : 1.02MB + Index : 0.88MB + Moteur InnoDB
bvn_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_actionscheduler_logs: Données : 0.23MB + Index : 0.16MB + Moteur InnoDB
bvn_cli_cookie_scan: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_cli_cookie_scan_categories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_cli_cookie_scan_cookies: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_cli_cookie_scan_url: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_cli_scripts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_comments: Données : 0.14MB + Index : 0.09MB + Moteur InnoDB
bvn_computop_customer_oneclick_payment_card: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_customer_payment_recurring: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_merchant_account: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_payment_recurring: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_transaction: Données : 0.25MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_allow_countries: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
bvn_computop_xml_method: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_method_lang: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_parameter: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
bvn_computop_xml_parameter_set: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_paygate_action_code: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_paygate_category_code: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
bvn_computop_xml_paygate_detail_code: Données : 0.08MB + Index : 0.01MB + Moteur MyISAM
bvn_computop_xml_paygate_position: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
bvn_fusion_forms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_fusion_form_entries: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_fusion_form_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_fusion_form_submissions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_gla_budget_recommendations: Données : 0.22MB + Index : 0.14MB + Moteur InnoDB
bvn_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_gla_shipping_rates: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_grp_google_place: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_grp_google_review: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_grp_google_stats: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_imagify_files: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
bvn_imagify_folders: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_lpc_inward_label: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_lpc_outward_label: Données : 12.50MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_automations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_automation_runs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_automation_run_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_automation_triggers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_automation_versions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_mapping_to_external_entities: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_newsletters: Données : 1.48MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_newsletter_links: Données : 0.06MB + Index : 0.08MB + Moteur InnoDB
bvn_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_newsletter_templates: Données : 3.52MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_scheduled_tasks: Données : 0.09MB + Index : 0.09MB + Moteur InnoDB
bvn_mailpoet_scheduled_task_subscribers: Données : 1.52MB + Index : 0.34MB + Moteur InnoDB
bvn_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_sending_queues: Données : 2.47MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_statistics_newsletters: Données : 0.30MB + Index : 0.28MB + Moteur InnoDB
bvn_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
bvn_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
bvn_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_subscribers: Données : 0.23MB + Index : 0.44MB + Moteur InnoDB
bvn_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_subscriber_segment: Données : 0.14MB + Index : 0.16MB + Moteur InnoDB
bvn_mailpoet_subscriber_tag: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_mailpoet_tags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_netreviews_configuration: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_netreviews_products_average: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_netreviews_products_reviews: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_options: Données : 7.45MB + Index : 0.16MB + Moteur InnoDB
bvn_postmeta: Données : 7.52MB + Index : 2.67MB + Moteur InnoDB
bvn_posts: Données : 41.52MB + Index : 0.38MB + Moteur InnoDB
bvn_termmeta: Données : 0.08MB + Index : 0.09MB + Moteur InnoDB
bvn_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_term_relationships: Données : 0.08MB + Index : 0.06MB + Moteur InnoDB
bvn_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_tinvwl_analytics: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_tinvwl_items: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_tinvwl_lists: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_trustindex_google_reviews: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_usermeta: Données : 0.20MB + Index : 0.14MB + Moteur InnoDB
bvn_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wassup: Données : 145.66MB + Index : 36.61MB + Moteur InnoDB
bvn_wassup_meta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
bvn_wassup_tmp: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wc_admin_notes: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
bvn_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wc_order_product_lookup: Données : 0.06MB + Index : 0.06MB + Moteur InnoDB
bvn_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wc_product_meta_lookup: Données : 0.09MB + Index : 0.16MB + Moteur InnoDB
bvn_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wfblockediplog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wfconfig: Données : 0.09MB + Index : 0.00MB + Moteur InnoDB
bvn_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wffilemods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wfhits: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
bvn_wfknownfilelist: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wflogins: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
bvn_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
bvn_wfstatus: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_wpfm_backup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
bvn_yith_wcwl: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_yith_wcwl_lists: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_yoast_indexable: Données : 2.48MB + Index : 0.63MB + Moteur InnoDB
bvn_yoast_indexable_hierarchy: Données : 0.08MB + Index : 0.08MB + Moteur InnoDB
bvn_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
bvn_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
bvn_yoast_seo_links: Données : 0.17MB + Index : 0.13MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1312
cookielawinfo: 6
custom_css: 1
customize_changeset: 8
fusion_element: 13
fusion_form: 3
fusion_icons: 1
fusion_tb_layout: 9
fusion_tb_section: 14
fusion_template: 2
mailpoet_page: 1
nav_menu_item: 58
page: 37
post: 16
product: 284
product_variation: 130
revision: 1599
shop_coupon: 12
shop_order: 187
shop_order_refund: 2
wc_whsm: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Akismet Anti-Spam: par Automattic – 5.0.2
Chronopost: par Adexos – 1.2.3
Colissimo shipping methods for WooCommerce: par Colissimo – 1.7.3
Axepta Online BNP Paribas: par Quadra Informatique – 2.2.1
CookieYes | GDPR Cookie Consent: par CookieYes – 3.0.7
Disable Admin Notices Individually: par Creative Motion  – 1.3.1
Yoast Duplicate Post: par Enrico Battocchi & l’équipe Yoast – 4.5
Enable jQuery Migrate Helper: par L’équipe WordPress – 1.3.0
Avada Builder: par ThemeFusion – 3.4.1
Avada Core: par ThemeFusion – 5.4.1
Hide Shipping Method For WooCommerce: par theDotstore – 1.3.2
Imagify: par Imagify – Optimize Images & Convert WebP – 2.1
Mondial Relay - WordPress: par Rodolphe Cazemajou-Tournié – 2.3
Netreviews: par NetReviews SAS  – 2.3.12
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 3.1.5
Simple Banner: par Ryan Petersen – 2.12.2
W3 Total Cache: par BoldGrid – 2.2.9
WassUp Real Time Analytics: par Michele Marcucci
Helene Duncker – 1.9.4.5

Product Subtitle For WooCommerce: par Varun Sridharan – 4.6.2
Plugin for Google Reviews: par RichPlugins  – 2.2.4
WooCommerce Social Login: par WPWeb – 2.3.9
WooCommerce: par Automattic – 7.2.1
Wordfence Security: par Wordfence – 7.7.1
Yoast SEO: par L’équipe Yoast – 19.12
WP Fastest Cache: par Emre Vona – 1.0.9
Gestionnaire de fichiers WP: par mndpsingh287 – 7.1.7
Widgets d'avis Google: par Trustindex.io  – 9.7.1
WPFront Notification Bar: par Syam Mohan – 3.2.0

### Inactive Plugins (4) ###

Custom Product Tabs for WooCommerce: par YIKES
Inc. – 1.8.2

SiteGround Optimizer: par SiteGround – 7.2.9
TI WooCommerce Wishlist: par TemplateInvaders – 2.0.17
Under Construction: par WebFactory Ltd – 3.95

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la boutique: ❌ La visibilité de la page doit être publique
Panier: #585 - /panier/
Commander: ❌ La page ne contient pas le code court [woocommerce_checkout] ou le bloc woocommerce/checkout.
Mon compte: #587 - /mon-compte/
Conditions générales de vente et d’utilisation: #2684 - /conditions-generales-de-vente/

### Theme ###

Name: Avada
Version: 7.4.1
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 4.4.0 est obsolète. La version du noyau est 7.0.1
Avada/woocommerce/checkout/form-pay.php version 5.2.0 est obsolète. La version du noyau est 7.0.1
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 3.5.5 est obsolète. La version du noyau est 6.1.0
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-21 12:26:09 +01:00
Options: ✔
Notes: 34
Onboarding: completed

### Action Scheduler ###

Complete: 2 154
Oldest: 2022-11-19 13:56:17 +0100
Newest: 2022-12-20 13:20:33 +0100

Failed: 1
Oldest: 2022-12-20 04:29:09 +0100
Newest: 2022-12-20 04:29:09 +0100

Pending: 2
Oldest: 2022-12-21 04:00:00 +0100
Newest: 2022-12-21 10:58:16 +0100

### Status report information ###

Generated at: 2022-12-20 13:36:31 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
@Ladyglow because you're running other plugins its hard to know if this is a problem with WooCommerce or a conflict with another plugin or theme. You could try following the testing steps here first to isolate which plugin causes the problem: https://woocommerce.com/document/how-to-test-for-conflicts/

If after disabling other plugins you still experience this problem then please feel free to reopen the issue.
