### ISSUE TITLE
Unknown column 'wp_postmeta.post_id' in 'where clause' when installing v7.2.1

### ISSUE THREAD

**Issue by bazzik** [woothemes/woocommerce#36096]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Installing v7.2.1 over 7.2.0

See a bunch of entries in PHP Error log about _Unknown column 'wp_postmeta.post_id'_
```
[20-Dec-2022 09:40:44 UTC] WordPress database error Unknown column 'wp_postmeta.post_id' in 'where clause' for query SELECT meta_id FROM ired_postmeta,
					(SELECT DISTINCT post_id FROM ired_postmeta
					WHERE (meta_key = '_billing_country' OR meta_key='_shipping_country') AND meta_value='NZ')
					AS states_in_country
				WHERE (meta_key='_billing_state' OR meta_key='_shipping_state')
				AND meta_value='NL'
				AND wp_postmeta.post_id = states_in_country.post_id
				LIMIT 100 made by do_action('wp_ajax_as_async_request_queue_runner'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Async_Request->maybe_handle, ActionScheduler_AsyncRequest_QueueRunner->handle, do_action('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_Action->execute, do_action_ref_array('woocommerce_run_update_callback'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::run_update_callback, wc_update_721_adjust_new_zealand_states, Automattic\WooCommerce\Database\Migrations\MigrationHelper::migrate_country_states, Automattic\WooCommerce\Database\Migrations\MigrationHelper::migrate_country_states_for_orders
```

There is no `wp_postmeta` table in the database. The correct table name (with the prefix) should be `ired_postmeta` I guess.

### Expected behavior

Clean upgrade with no DB errors in PHP Error Log.

### Actual behavior

40 errors logged in the PHP Error log.

I've tried to attach the error log file but drag&drop is not allowing to do this. Not sure how to.

### Steps to reproduce

Install 7.2.1 over 7.2.0

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://domain.com
Site address (URL): https://domain.com
WC Version: 7.2.1
REST API Version: ✔ 7.2.1
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.26
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.86.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.40
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.1
WC Database Prefix: ired_
Total Database Size: 33.85MB
Database Data Size: 28.03MB
Database Index Size: 5.82MB
ired_woocommerce_sessions: Data: 10.52MB + Index: 0.27MB + Engine InnoDB
ired_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ired_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
ired_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
ired_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ired_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_actionscheduler_actions: Data: 0.03MB + Index: 0.13MB + Engine InnoDB
ired_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_comments: Data: 0.44MB + Index: 0.38MB + Engine InnoDB
ired_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
ired_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ired_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
ired_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ired_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ired_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_helpful: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_helpful_feedback: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_helpful_instances: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_odb_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_options: Data: 7.28MB + Index: 0.16MB + Engine InnoDB
ired_peachpay_abandonment_emails: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_peachpay_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_peachpay_cart_has_item: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_postmeta: Data: 4.52MB + Index: 1.92MB + Engine InnoDB
ired_posts: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
ired_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_usermeta: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
ired_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ired_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ired_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
ired_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
ired_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
ired_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
ired_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ired_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_woo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
ired_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ired_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ired_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ired_yoast_indexable: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
ired_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ired_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ired_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ired_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB

Custom views below
OrderComments_Recent: Data: 0.00MB + Index: 0.00MB + Engine
OrderComments_StatusDelivered: Data: 0.00MB + Index: 0.00MB + Engine
OrderComments_TrafficSource: Data: 0.00MB + Index: 0.00MB + Engine
Orders_UserAgent: Data: 0.00MB + Index: 0.00MB + Engine

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
attachment: 242
custom_css: 1
elementor_library: 44
elementor-hf: 1
frm_form_actions: 2
frm_styles: 1
hurrytimer_countdown: 1
mc4wp-form: 1
metform-entry: 1
metform-form: 1
nav_menu_item: 24
page: 27
post: 20
product: 3
shop_coupon: 7
shop_order: 238
shop_order_refund: 3
testimonials: 10
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Advanced Custom Fields: by WP Engine – 6.0.6
Astra Pro: by Brainstorm Force – 3.6.3
Cloudflare: by Cloudflare Inc. – 4.11.0
Custom Fonts: by Brainstorm Force – 1.3.7
Custom Post Type UI: by WebDevStudios – 1.13.4
Disable Gutenberg: by Jeff Starr – 2.8.1
Elementor Pro: by Elementor.com – 3.9.1
Elementor: by Elementor.com – 3.9.1
Helpful: by Pixelbart – 4.5.25
HurryTimer PRO: by Nabil Lemsieh – 2.8.0
Smash Balloon Instagram Feed: by Smash Balloon – 6.1
JetElements For Elementor: by Crocoblock – 2.6.8
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.20
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.12
Max Mega Menu: by megamenu.com – 3.0
MetForm: by Wpmet – 3.1.1
PeachPay Checkout for WooCommerce: Stripe, PayPal, Square, and more: by PeachPay Inc. – 1.83.0
Premium Addons for Elementor: by Leap13 – 4.9.44
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: by Retainful – 2.6.17
Optimize Database after Deleting Revisions: by CAGE Web Design | Rolf van Gelder Eindhoven The Netherlands – 5.0.110
Social Warfare: by Warfare Plugins – 4.3.0
Simple Sticky Add To Cart For WooCommerce: by Solution Box – 1.3.9
Ultimate Addons for Elementor: by Brainstorm Force – 1.35.1
WebP Express: by Bjørn Rosell – 0.25.5
Advanced Shipment Tracking for WooCommerce: by zorem – 3.5.1
WooCommerce Conversion Tracking: by weDevs – 2.0.10
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.18
WooCommerce PayPal Payments: by WooCommerce – 2.0.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.15
WooCommerce: by Automattic – 7.2.1
Yoast SEO: by Team Yoast – 19.12
Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.8.9
WP Mail SMTP: by WPForms – 3.7.0
WP Rocket: by WP Media – 3.12.3.3
WPForms Lite: by WPForms – 1.7.8

### Inactive Plugins (1) ###

Payment Gateway for PayPal on WooCommerce: by easypayment – 7.1.5

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #13 - /shop/
Cart: #1224 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #5320 - /terms-of-service/

### Theme ###

Name: iRed
Version: 1.0.220422
Author URL: 
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 3.9.4
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: ired/woocommerce/emails/customer-processing-order.php
ired/woocommerce/emails/plain/customer-processing-order.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-20 15:33:15 -08:00
Options: ✔
Notes: 71
Onboarding: completed

### Action Scheduler ###

Complete: 37
Oldest: 2022-12-18 15:48:00 -0800
Newest: 2022-12-20 01:40:44 -0800

Failed: 4
Oldest: 2022-12-14 09:58:05 -0800
Newest: 2022-12-20 01:40:44 -0800

Pending: 8
Oldest: 2022-12-20 05:57:11 -0800
Newest: 2022-12-26 06:26:11 -0800

### Status report information ###

Generated at: 2022-12-20 01:57:44 -08:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by bazzik** [comment]
Thus must be caused by/related to [#35967](https://github.com/woocommerce/woocommerce/pull/35967)

If that matters: we have 0 (zero) orders from UA or NZ

**Comment by EjayhanFernandes** [comment]
Just commenting that a user experienced this issue here: [5805963-zd](5805963-zd-woothemes) - Letting them know that a fix is coming out.
