### ISSUE TITLE
[Enhancement]: flexibility for payment handling

### ISSUE THREAD

**Issue by antondrob** [woothemes/woocommerce#36092]
### Describe the solution you'd like

I would like to have a condition in checkout.js file where nothing happens. For example, if I return "status" => "whateverCustomStatus" in process_payment() I would prefer that nothing happens and I handle everything in a [custom way](https://prnt.sc/oxLJm5MO5jck).

### Describe alternatives you've considered

Now to handle the described cases, we have to e.preventDefault() WooCommerce checkout.js and send a custom ajax request from the payment plugin JS file.

### Additional context

There are a lot of payment gateways of different types. The existing WooCommerce codebase doesn't support a clean way to handle the following cases:

1. JS SDK when we should popup a modal to enter credit card details. For example, if I click the place order button, process_payment() returns success. Then we can use a JS hook checkout_place_order_success to handle the ajax response in a custom way. On this JS hook we can return true or false. If true, the redirect will happen. If false we will see an error notice. But in our case, I want neither redirect nor notice. I want my JS SDK payment widget open. The customer then completes the payment process and we redirect them to thank you page.
2. Post the form with the order details. The same logic as in point 1: I want neither redirect nor notice, I want to generate a form by JS and send it with POST method to a separate payment page.

**Comment by ralucaStan** [comment]
Hello @antondrob, 
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply. While this is an interesting approach, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility). We'll revisit the list of suggestions like this one once our priorities are updated.
