### ISSUE TITLE
Analytics -> Products wrong when ordered by SKU

### ISSUE THREAD

**Issue by SimBotBiz** [woothemes/woocommerce#36103]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In analytics -> products when order by SKU results looks wrong, count for "sold items" and "net revenue" seem almost duplicated (almost!)

Also when selecting the single product data are shown as duplicated (2 rows), I think it may be related.

I did some screenshot, I can provide more info or do more testes if needed.

results
![order by sold items](https://user-images.githubusercontent.com/50404322/208717389-5b231667-58fe-493e-8d02-156a734ba542.png)
![order by sku](https://user-images.githubusercontent.com/50404322/208717401-2f2ce6e4-ac32-49cd-a7ad-de9003b64d29.png)

single product
![prodcut order by sold items](https://user-images.githubusercontent.com/50404322/208717395-0561803b-aeae-4a03-acd7-66bc4368d6bc.png)
![product order by sku](https://user-images.githubusercontent.com/50404322/208717397-c5df99c8-4830-4459-8aa3-c344a98674b4.png)

### Expected behavior

Statistics are correct.

### Actual behavior

Statistics are wrong when ordered by sku

### Steps to reproduce

Analytics -> Products
Select a date interval
Order result table by sku

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.23.2
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 1200
PHP Max Input Vars: 1000
cURL Version: 7.83.1
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Il tuo server non ha la classe SoapClient attiva - alcuni plugin gateway che usano SOAP potrebbero non funzionare correttamente.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Dimensione totale database: 303.65MB
Dimensione dati database: 171.13MB
Dimensione indice database: 132.52MB
wp_woocommerce_sessions: Dati: 5.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 1.52MB + indice: 0.36MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 12.52MB + indice: 12.00MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 9.02MB + indice: 10.27MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 7.06MB + indice: 6.41MB + motore InnoDB
wp_awb_critical_css: Dati: 0.13MB + indice: 0.02MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 5.03MB + indice: 7.25MB + motore InnoDB
wp_fusion_form_entries: Dati: 0.13MB + indice: 0.02MB + motore InnoDB
wp_fusion_form_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_fusion_form_submissions: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wp_fusion_forms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_gla_attribute_mapping_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_gla_budget_recommendations: Dati: 0.22MB + indice: 0.14MB + motore InnoDB
wp_gla_merchant_issues: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_gla_shipping_rates: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_gla_shipping_times: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_icl_content_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_icl_core_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_icl_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_icl_languages: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_icl_languages_translations: Dati: 0.20MB + indice: 0.17MB + motore InnoDB
wp_icl_locale_map: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_message_status: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_icl_mo_files_domains: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wp_icl_node: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_reminders: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_string_batches: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_string_packages: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_string_positions: Dati: 1.27MB + indice: 0.17MB + motore InnoDB
wp_icl_string_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_icl_string_translations: Dati: 6.52MB + indice: 4.03MB + motore InnoDB
wp_icl_strings: Dati: 7.52MB + indice: 14.09MB + motore InnoDB
wp_icl_translate: Dati: 15.25MB + indice: 0.23MB + motore InnoDB
wp_icl_translate_job: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
wp_icl_translation_batches: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_translation_downloads: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_icl_translation_status: Dati: 6.22MB + indice: 0.11MB + motore InnoDB
wp_icl_translations: Dati: 0.48MB + indice: 1.11MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_options: Dati: 7.08MB + indice: 0.22MB + motore InnoDB
wp_postmeta: Dati: 45.56MB + indice: 58.84MB + motore InnoDB
wp_posts: Dati: 21.44MB + indice: 3.05MB + motore InnoDB
wp_sib_model_contact: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_lang: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_users: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_term_relationships: Dati: 0.23MB + indice: 0.17MB + motore InnoDB
wp_term_taxonomy: Dati: 0.08MB + indice: 0.11MB + motore InnoDB
wp_termmeta: Dati: 0.23MB + indice: 0.30MB + motore InnoDB
wp_terms: Dati: 0.09MB + indice: 0.09MB + motore InnoDB
wp_usermeta: Dati: 5.47MB + indice: 6.92MB + motore InnoDB
wp_users: Dati: 0.27MB + indice: 0.23MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 1.25MB + indice: 0.27MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.09MB + indice: 0.13MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 1.52MB + indice: 1.39MB + motore InnoDB
wp_wc_order_stats: Dati: 1.02MB + indice: 0.25MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.09MB + indice: 0.13MB + motore InnoDB
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wdr_order_discounts: Dati: 0.09MB + indice: 0.00MB + motore InnoDB
wp_wdr_order_item_discounts: Dati: 0.06MB + indice: 0.05MB + motore InnoDB
wp_wdr_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_table_rates: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_yoast_indexable: Dati: 6.45MB + indice: 2.42MB + motore InnoDB
wp_yoast_indexable_hierarchy: Dati: 0.42MB + indice: 0.45MB + motore InnoDB
wp_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_yoast_seo_links: Dati: 0.19MB + indice: 0.14MB + motore InnoDB

### Post Type Counts ###

acf-field: 78
acf-field-group: 12
attachment: 5299
awb_off_canvas: 5
custom_css: 2
fusion_element: 38
fusion_form: 5
fusion_tb_layout: 9
fusion_tb_section: 59
mt_pp: 9
nav_menu_item: 130
page: 56
post: 259
product: 489
revision: 666
shop_coupon: 42
shop_order: 2254
shop_order_refund: 18
wp_global_styles: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.14
WPML SEO: by OnTheGoSystems – 2.1.0
Advanced Custom Fields Multilingual: by OnTheGoSystems – 1.10.4
Advanced Custom Fields PRO: by WP Engine – 6.0.6
Facebook for WooCommerce: by Facebook – 3.0.6
Avada Builder: by ThemeFusion – 3.8.2
Avada Core: by ThemeFusion – 5.8.2
Google Authenticator: by Ivan Kruchkoff – 0.54
Google Listings and Ads: by WooCommerce – 2.3.3
Site Kit by Google: by Google – 1.89.0
Health Check & Troubleshooting: by The WordPress.org community – 1.5.1
Cookie e Consent Solution per il GDPR e la direttiva ePrivacy: by iubenda – 3.3.3
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.54
User Profile Picture: by Cozmoslabs – 2.6.0
Trustpilot-reviews: by Trustpilot – 2.5.914
Woo Discount Rules PRO 2.0: by Flycart – 2.5.2
Woo Discount Rules: by Flycart – 2.5.2
WooCommerce Brands: by WooCommerce – 1.6.40
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.18
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
WooCommerce PayPal Payments: by WooCommerce – 2.0.1
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 3.0.2
WooCommerce Shipment Tracking: by WooCommerce – 1.8.0 (aggiornamento alla versione 1.9.0 disponibile)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.41 (aggiornamento alla versione 3.1.0 disponibile)
WooCommerce: by Automattic – 7.1.1 (aggiornamento alla versione 7.2.1 disponibile)
Yoast SEO: by Team Yoast – 19.12
WP Super Cache: by Automattic – 1.9.2
WPML Media: by OnTheGoSystems – 2.7.1
WPML String Translation: by OnTheGoSystems – 3.2.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
simple (simple)
simple (simple-fr)
simple (simple-de)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-de)
featured (featured-fr)
outofstock (outofstock)
outofstock (outofstock-de)
outofstock (outofstock-fr)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #35 - /negozio/
Carrello: #36 - /carrello/
Pagamento: #37 - /pagamento/
Il mio account: #38 - /mio-account/
Termini e condizioni: #50 - /termini-e-condizioni/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.8.2
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-21 12:51:44 +01:00
Options: ✔
Notes: 24
Onboarding: completed

### Action Scheduler ###

Completato: 14.417
Oldest: 2022-11-19 17:37:46 +0100
Newest: 2022-12-20 17:18:45 +0100

Operazione non riuscita: 8.092
Oldest: 2022-11-11 17:48:46 +0100
Newest: 2022-12-10 00:04:18 +0100

In attesa: 4
Oldest: 2022-12-21 04:00:00 +0100
Newest: 2022-12-21 16:31:49 +0100

### Status report information ###

Generated at: 2022-12-20 17:34:03 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @SimBotBiz,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.1.1 version and WordPress 6.1.1 version. 

Please find below the screenshots for reference :

![#36103(all product 1)](https://user-images.githubusercontent.com/94531721/208845012-97e8ca70-ea8a-4f04-9e80-4cebec071a33.jpg)

![#36103(all product 2)](https://user-images.githubusercontent.com/94531721/208845021-0dcbfe36-9243-48a0-b6ef-464d2eb2564a.jpg)

![#36103(single Product)](https://user-images.githubusercontent.com/94531721/208845023-35998da8-2b71-473a-8242-66898d65fe79.jpg)

![#36103(single Product2)](https://user-images.githubusercontent.com/94531721/208845024-1ba4717c-ac15-4ed1-ab38-0c937d6e7462.jpg)

Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by lsinger** [comment]
We have not been able to reproduce this issue and have not heard back from you. We are closing this issue for now. If we missed something, please leave a comment and we will take a second look.
