### ISSUE TITLE
[Enhancement]: Hide or Display Quantity Fields (A Necessary Feature for Digital Products/Service Sellers)

### ISSUE THREAD

**Issue by abqariyuh** [woothemes/woocommerce#36113]
### Describe the solution you'd like

I strongly suggest WooCommerce should add the feature of enabling and disabling the visibility of the quantity field in their next version. Since WooCommerce allows the selling of digital products, why does the quantity field still appear without the option to disable it?

The use of custom codes are conflicting with WooCommerce updates, it worked and doesn't work in some versions. It's better if WooCommerce includes this feature.

**Comment by davidhealey** [comment]
Actually the quantity field should be hidden when you set a product to be sold individually, but it appears since a recent update that is no longer the case. So this is a bug.

Ah someone else has made a bug report - https://github.com/woocommerce/woocommerce/issues/36007

**Comment by samueljseay** [comment]
Thanks @davidhealey I'll close this and you can track resolution via that bug report.

**Comment by markmmac** [comment]
The quantity field should be hidden when you set a product to be sold individually, but it appears this is no longer the case. So this is a bug. It is essential for stores selling digital goods.
