### ISSUE TITLE
Code Freeze: Automation broken

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36135]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Code Freeze action doesn't complete. This causes the release lead to have to make manual PRs introducing the potential for errors.

First, a `pnpm-lock.yaml` change caused a failure

https://github.com/woocommerce/woocommerce/actions/runs/3738934217/jobs/6345560765

I solved this in just the branch with a `git checkout pnpm-lock.yaml` and ran into the next error

https://github.com/woocommerce/woocommerce/actions/runs/3739098586/jobs/6345912026

I'm not sure why there was a conflict

**Comment by roykho** [comment]
I've tested this on my fork and I could not reproduce this. I did however added a [`git checkout pnpm-lock.yaml`](https://github.com/woocommerce/woocommerce/pull/36399/files#diff-305377beb31aab4ccc3ffbe29a11cd428b5a52460bc855ceba49c92faec46bf3R49) step just to alleviate the error you encountered in the first link. 

So I think we can just close this and monitor it to see if it happens again.
