### ISSUE TITLE
wp_postmeta.post_id should be updated to {$wpdb->prefix}postmeta.post_id

### ISSUE THREAD

**Issue by marknokes** [woothemes/woocommerce#36149]
https://github.com/woocommerce/woocommerce/blob/5b3f36068db759602c493e9122f880a40e520d1d/plugins/woocommerce/src/Database/Migrations/MigrationHelper.php#L208

**Comment by marknokes** [comment]
The migration fails with errors when the wordpress table prefix has been changed from the default.

**Comment by barryhughes** [comment]
Thanks for flagging, @marknokes—and apologies for the disruption. This should be addressed as of 7.2.2 (released yesterday).

https://github.com/woocommerce/woocommerce/blob/7.2.2/plugins/woocommerce/src/Database/Migrations/MigrationHelper.php#L208
