### ISSUE TITLE
[Fix] Opened dropdowns overlay other parts of the UI

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36148]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79307566/209130161-399c6292-3c64-4ff2-8d63-b38ad6f1b1a9.png">

**Issue Description:**
When opened, the dropdowns and flyouts overlay the top navigation and WordPress admin bar. Can we fix that?

**Acceptance criteria:**

- [ ] WordPress admin UI and the product form top bar have the highest z-index, and all else is shown beneath them.

**Comment by pmcpinto** [comment]
Not present in the new experience
