### ISSUE TITLE
Latest beta 7.30 b1 adds php-error class to body class in wp development version (6.2-alpha-55011).

### ISSUE THREAD

**Issue by BackuPs** [woothemes/woocommerce#36144]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Turning on woocommerce adds the php-error class to the body class in the admin arror and fills the error_get_last() function with this error 

`-:array(4) { ["type"]=> int(16384) ["message"]=> string(158) "The PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience." ["file"]=> string(65) "/var/docs/server.tst/public/wp-includes/Requests/src/Autoload.php" ["line"]=> int(171) } 
`
but no error is displayed.

### Expected behavior

The php-error class should not be added when no php warning error message shows.

### Actual behavior

the php-error class is added to the body classes causes the admin area beginning with a empty 2em margin at the top. But no error message is displayed.

### Steps to reproduce

Install development version (6.2-alpha-55011).  
Install woocommerce and activate woocommerce.  
In wp-config.php  turn on debug mode.

In the admin area header main screen the php-error class is added to the body.

If you modify admin-header.php and around line 213 add this code

`echo '- -------------------------------------:';
var_dump($error_get_last);`

You will see this error as last php error 

 `array(4) { ["type"]=> int(16384) ["message"]=> string(158) "The PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience." ["file"]=> string(65) "/var/docs/server.tst/public/wp-includes/Requests/src/Autoload.php" ["line"]=> int(171) } `

The moment i turn off woocommerce the issue is gone.

add the above code before this piece of code in the admin-header.php

`if ( $error_get_last && WP_DEBUG && WP_DEBUG_DISPLAY && ini_get( 'display_errors' )
	// Don't print the class for PHP notices in wp-config.php, as they happen before WP_DEBUG takes effect,
	// and should not be displayed with the `error_reporting` level previously set in wp-load.php.
	&& ( E_NOTICE !== $error_get_last['type'] || 'wp-config.php' !== wp_basename( $error_get_last['file'] ) )
) {
	$admin_body_class .= ' php-error';
}`

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://server.tst
Site address (URL): http://server.tst
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.2-alpha-55011
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.31-0ubuntu0.20.04.2
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.0
WC Database Prefix: wp_
Total Database Size: 15.90MB
Database Data Size: 13.38MB
Database Index Size: 2.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 3.48MB + Index: 0.61MB + Engine InnoDB
wp_posts: Data: 2.42MB + Index: 0.13MB + Engine InnoDB
wp_responsive_menu_pro: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 202
elementor_library: 3
nav_menu_item: 105
page: 114
portfolio: 28
post: 14
product: 18
product_variation: 7
revision: 112
slideshow: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0-beta.1

### Inactive Plugins (45) ###

Akismet Anti-Spam: by Automattic – 5.0.2
BackupBuddy: by iThemes – 8.7.4.0
bbPress: by The bbPress Contributors – 2.6.9
Champion Responsive Menu: by The ThemeBuilders – 3.1.35
Classic Editor: by WordPress Contributors – 1.6.2
Disable Author Pages: by Frank Staude – 0.11
Elementor: by Elementor.com – 3.9.2
Elementor Pro: by Elementor.com – 3.6.4
Element Pack Pro: by BdThemes – 6.10.0
ElementsKit Lite: by Wpmet – 2.8.0
ElementsKit Pro: by Wpmet – 3.0.0
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Envato Theme Check: by Scott Parry – 1.0.0
Essential Grid: by ThemePunch – 3.0.16
Fancy Product Designer: by fancyproductdesigner.com – 4.6.9
Fancy Product Designer: by fancyproductdesigner.com – 4.6.7
Fancy Product Designer Plus: by fancyproductdesigner.com – 1.3.0
Fancy Product Designer REST API: by fancyproductdesigner.com – 1.6.4
Flexible Elementor Panel: by WebMat – 2.3.8
Gravity Forms: by Gravity Forms – 2.6.7
Gutenberg: by Gutenberg Team – 14.8.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Multiflex Responsive Menu: by The Themebuilders – 3.1.35
OoohBoi Steroids for Elementor: by OoohBoi – 2.0.5
Performance Lab: by WordPress Performance Team – 1.8.0
PRO Elements: by PROElements.org – 3.8.0
QuadMenu: by Mega Menu – 2.3.5
QuadMenu PRO: by Mega Menu – 1.9.0
Quform: by ThemeCatcher – 2.14.2
Replace Google Fonts with Bunny Fonts: by antonioleutsch – 2.1.2
Responsive Menu: by ExpressTech – 4.2.1
Reveal IDs: by Oliver Schlöbe – 1.5.4
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.2

Slider Revolution: by ThemePunch – 6.6.8
Striking_R Framework Extension: by kaptinlin – 2.2.0
Super Elements for Elementor: by ThemeRevealed – 2.2.7
Test jQuery Updates: by The WordPress Team – 2.0.0
Widget Importer & Exporter: by ChurchThemes.com – 1.6
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.4

WordPress Importer: by wordpressdotorg – 0.8
WPML Media: by OnTheGoSystems – 2.7.0
WPML Multilingual CMS: by OnTheGoSystems – 4.5.10
WPML String Translation: by OnTheGoSystems – 3.2.2
Yoast SEO: by Team Yoast – 19.13

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5895 - /shop
Cart: #5896 - /cart
Checkout: #5897 - /checkout
My account: #5898 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-19 09:48:32 +00:00
Options: ✔
Notes: 46
Onboarding: completed

### Action Scheduler ###

Complete: 2
Oldest: 2022-12-22 10:26:07 +0000
Newest: 2022-12-22 10:26:14 +0000

Pending: 39
Oldest: -0001-11-30 00:00:00 +0000
Newest: 2022-12-21 12:23:33 +0000

### Status report information ###

Generated at: 2022-12-22 10:54:09 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by BackuPs** [comment]
see image

![afbeelding](https://user-images.githubusercontent.com/6078370/209120287-48a5d54b-e73a-4a75-8cd3-6137434d5db9.png)

**Comment by jorgeatorres** [comment]
Hi @BackuPs,

Thanks for the report. We'll be taking a look shortly.

**Comment by peterfabian** [comment]
I don't think this happens anymore, can you please confirm @BackuPs please?

![Screenshot 2023-05-22 at 14 15 01](https://github.com/woocommerce/woocommerce/assets/2207451/2b0c7def-7d14-4567-a42c-f26e5969f805)

**Comment by rrennick** [comment]
Closing this due to lack of feedback. If this is still occurring please let us know.
