### ISSUE TITLE
Pricing section: include tax options

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36164]
**Description:** we should introduce the tax options fields to ensure the new experience can be used in stores collexting taxes.
Target: WC 7.4 (code freeze: Jan 23)

**Acceptance criteria:**
- [x] Introduce a new section in the Pricing tab for the Tax options when the store has enabled the "Enable taxes" option.
- [x] This section is composed of two areas: 5sAIeTRd9Yp7nSCT33BAWz-fi-9960%3A598979&t=qR6Eh9IDGH5L0MWY-0
- [x] Charge sales tax on: includes two options (Product price and shipping fee): "Don’t charge tax" corresponds to "none" in the current experience; "Product and shipping" corresponds to "taxable" in the current experience; "Only shipping" corresponds to "shipping only" in the current experience.
- [x] Tax class: it should show all available classes (standard rates, etc).

**Event tracking:**
TBD

**Comment by joshuatf** [comment]
Estimate: 2

This should be pretty straightforward to implement with the exist product and product variations data stores, we just need to make sure it works as expected in both parent products and variations.

**Comment by mdperez86** [comment]
@jarekmorawski @pmcpinto 

Considering this design 

![Image](https://user-images.githubusercontent.com/13334210/210609195-34a5e771-2f29-491a-b550-251d602b5931.png)

What is the link url assosiated to the `Learn more` text?
Each `?` icon at the end of each tax class should show a tooltip right? What is the text we should show in each tooltip?

**Comment by mdperez86** [comment]
Since we need a bran new datastore for tax classes and the current crud implementation does not scale to object without id. I thing this issue is a 3.

**Comment by mdperez86** [comment]
@jarekmorawski @pmcpinto 
It's possible to unselect a tax class because if that is the case then the radio inputs are not the best fit for that?

**Comment by pmcpinto** [comment]
> What is the link url assosiated to the Learn more text?

I think it should be: https://woocommerce.com/document/setting-up-taxes-in-woocommerce/#shipping-tax-class
@jarekmorawski can you confirm this?

> Each ? icon at the end of each tax class should show a tooltip right? What is the text we should show in each tooltip?

@jarekmorawski I missed this detail when I reviewed the design. I'm not sure if we should have tooltips because users can create or modify classes.

> It's possible to unselect a tax class because if that is the case then the radio inputs are not the best fit for that?

Maikel can you clarify this? AFAIK the user always needs to select a tax class. Thanks

**Comment by jarekmorawski** [comment]
> can you confirm this?

That's correct.

> I'm not sure if we should have tooltips because users can create or modify classes.

Good point! I'm sorry, I missed this detail. I've removed the icons from the designs.

> It's possible to unselect a tax class because if that is the case then the radio inputs are not the best fit for that?

I don't think this should be possible. Standard is selected by default and the user can only switch to a different class, not deselect it altogether.

**Comment by mdperez86** [comment]
@pmcpinto 

> Maikel can you clarify this? 

you answered with 

> AFAIK the user always needs to select a tax class.

Thanks
