### ISSUE TITLE
Advanced setting option

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36163]
**Description:** we plan to start rolling out the beta version of the new experience to a small % of new users to validate that we're moving in the right direction. We should include an option in settings as a complement to the flows described in #36161 and #36162
We want to target WC 7.4 (code freeze: Jan 23)

**Acceptance criteria:**
- [x] Introduce a new setting in Settings - Advanced - Features: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A6666&t=npEAXmnjXwQbZ97A-0
- [x] The setting should be disabled by default, unless it was enabled through the flows described in #36161 and #36162
- [x] Include a tooltip to describe the new exp briefly.

**Event tracking:**
We should leverage the `wcadmin_settings_change` to track when the feature is enabled or disabled by the user.

**Comment by AnnaMag** [comment]
`wcadmin_settings_change` has a `settings` property. Let's use 'woocommerce_new_product_management' as its value to indicate a change this section, and add a property `enabled` with yes/no values to indicate the status.

This option is available for all users and disabled by default. In addition, it will be synchronized with the status of the **turn on/off** button shown to assigned new users. For others, it can be modified manually.

**Comment by octaedro** [comment]
Hey @pmcpinto,

I have a question related to this line:

> Include a tooltip to describe the new exp briefly.

Could you share the text that the tooltip will show?

**Comment by pmcpinto** [comment]
@jarekmorawski can you share the tooltip copy here? Thanks

**Comment by jarekmorawski** [comment]
Here you go! You'll also find it in Figma: `lj4AUMJnpMtUe7XqyvOONq-fi-501%3A6733&t=yUCHDMe5rKAmfUSo-4`

> Enable to try the new, simplified product editor (currently in development and only available for simple products).

**Comment by pmcpinto** [comment]
@jarekmorawski I think we should also include something to clarify that we still don't have extension support. Makes sense?

**Comment by jarekmorawski** [comment]
Updated to:

> Enable to try the new, simplified product editor (currently in development and only available for simple products). No extension support yet.
