### ISSUE TITLE
[CLI] Sync command does not accurately report progress

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#36194]
When HPOS are active and we are running command via CLI, then the sync command does not reports accurate progress and suddenly reports the progress at 100% after being stuck on a while.

**Comment by jorgeatorres** [comment]
Not sure if there's anything we can do about this while working in batches as we don't have enough resolution to update progress more granularly. Obviously smaller batch sizes will result in a smoother progress bar, but I think our current values are a good compromise.

Closing for now. We can revisit later if it becomes a problem.
