### ISSUE TITLE
Not possible change button text

### ISSUE THREAD

**Issue by cendelinla** [woothemes/woocommerce#36199]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi, I have problem with the plugin. It is not possible change button text when I have variable products on the button, can someone help me. I tried the normal way put there snippet but this solution not work. Thanks for help.

### Expected behavior

Hi, I have problem with the plugin. It is not possible change button text when I have variable products on the button, can someone help me. I tried the normal way put there snippet but this solution not work. Thanks for help.

### Actual behavior

Hi, I have problem with the plugin. It is not possible change button text when I have variable products on the button, can someone help me. I tried the normal way put there snippet but this solution not work. Thanks for help.

### Steps to reproduce

Hi, I have problem with the plugin. It is not possible change button text when I have variable products on the button, can someone help me. I tried the normal way put there snippet but this solution not work. Thanks for help.

### WordPress Environment

Hi, I have problem with the plugin. It is not possible change button text when I have variable products on the button, can someone help me. I tried the normal way put there snippet but this solution not work. Thanks for help.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi @cendelinla, thanks for the report.

Can you included steps to reproduce? I'm having trouble understanding the issue from what you've provided.

**Comment by cendelinla** [comment]
Hi @psealock, I solve it via translate plugin, When you put variables and product atributes and after I used shortcode on website to show products with button on button  were possibilities to choose products there it was worked but when you chose product the translation was not shown in last step of code. So I download loco translation and made change in translation in plugin.  So I hope if someone who had or have same problem this will help. Happy New Year
