### ISSUE TITLE
Sale start date and End date Not working.

### ISSUE THREAD

**Issue by Readbetweenthellime** [woothemes/woocommerce#36211]
### Discussed in https://github.com/woocommerce/woocommerce/discussions/36191

<div type='discussions-op-text'>

<sup>Originally posted by **Readbetweenthellime** December 27, 2022</sup>
Hi! I'm trying to upload the sale price via CSV file. However, the sale price date is not reflected on the product page and I think it is not working.  Can someone help me? Thank y
[Test.csv](https://github.com/woocommerce/woocommerce/files/10305666/Test.csv)
ou.</div>

**Comment by psealock** [comment]
Thanks for the report @Readbetweenthellime, could you add detailed reproduction steps?

**Comment by Readbetweenthellime** [comment]
> Thanks for the report @Readbetweenthellime, could you add detailed reproduction steps?

Hi @psealock what do you mean by detailed reproduction steps? I'm sorry this is the first time that I've posted here.

**Comment by psealock** [comment]
@Readbetweenthellime 

Can you add directions for someone with no context on how to see the bug you are experiencing? 

For instance:

1. Step one
2. Step two...
