### ISSUE TITLE
[Enhancement]: Add translation context to shipping prefix

### ISSUE THREAD

**Issue by MatzeKitt** [woothemes/woocommerce#36242]
### Describe the solution you'd like

To enhance translatability, please add a translation context to the shipping prefix:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L413

The "to" or "to the" is rather generic without a context and can lead to wrong translations elsewhere.

**Comment by psealock** [comment]
Thanks for the suggestion @MatzeKitt, thats seems useful. Do you have a context in mind that would be helpful?

Would you be interested in submitting a pull request?

**Comment by MatzeKitt** [comment]
I submitted a pull request and also talked to @Presskopp regarding his pull request to get the best result.
