### ISSUE TITLE
Special Characters not rendered in admin titles

### ISSUE THREAD

**Issue by emaildano** [woothemes/woocommerce#36246]
## Issue
On this line in the admin screen, the title does not render special characters.

https://github.com/woocommerce/woocommerce/blob/3fe3710c51f1abc57c5a887408f83715aee62c5a/plugins/woocommerce-admin/client/task-lists/progress-title/progress-title.tsx#L67

## Example

![Screenshot 2022-12-31 at 12 12 13 PM](https://user-images.githubusercontent.com/1872327/210150925-4f1e52e5-28ec-4aec-832d-79a72af1eb6c.png)

`Joe&#039;s` should render as `Joe's`

## Suggestions

1. Add `he` to encode and decode special characters
2. Add a simple html encode function that is browser native and add that function to the project

https://www.npmjs.com/package/he

**Comment by chihsuan** [comment]
I think we can use `dangerouslySetInnerHTML`+ `sanitizeHTML` like this:

https://github.com/woocommerce/woocommerce/blob/be9f09f2171432fb7341f3c1b8838b2637b32624/plugins/woocommerce-admin/client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Configure.js#L93

**Comment by emaildano** [comment]
@chihsuan Thanks for the rec; this function will work. I've submitted a PR for this. 👍🏻 

> I think we can use `dangerouslySetInnerHTML`+ `sanitizeHTML` like this:
> 
> https://github.com/woocommerce/woocommerce/blob/be9f09f2171432fb7341f3c1b8838b2637b32624/plugins/woocommerce-admin/client/tasks/fills/PaymentGatewaySuggestions/components/Setup/Configure.js#L93

https://github.com/woocommerce/woocommerce/pull/37546

**Comment by ilyasfoo** [comment]
PR: https://github.com/woocommerce/woocommerce/pull/37546
