### ISSUE TITLE
Add the ability to set an icon for the price

### ISSUE THREAD

**Issue by NimaBakhtiyari** [woothemes/woocommerce#36245]
### Describe the solution you'd like

The ability to set an icon for the price in the whole WeCommerce that can be accessed by the wc_price() function.
And the ability to replace this icon with the name of the currency, if any.
so that during the display, instead of the currency name, the special icon whose rate is set is displayed.

### Describe alternatives you've considered

also If it can be customized with Elementor icon packs, it will be great.

### Additional context

![image](https://user-images.githubusercontent.com/90132570/210134658-677df5a8-cfb9-4a70-91fd-f7fefa001783.png)

**Comment by rrennick** [comment]
> so that during the display, instead of the currency name, the special icon whose rate is set is displayed.

@NimaBakhtiyari WooCommerce core does not display the currency with the price. This sounds like it may be a feature of Elementor or another extension you have installed. 

Alternatively, you can use the [`woocommerce_get_price_html` filter](https://woocommerce.github.io/code-reference/files/woocommerce-includes-wc-template-functions.html#source-view.3599) to add the currency text or icon. I'll close the issue as a question.
