### ISSUE TITLE
Erro em produtos Semelhantes

### ISSUE THREAD

**Issue by JoseTNeto** [woothemes/woocommerce#36258]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Olá, meu site é o www.milblocos.net
depois da ultima atualização, começou a aparecer a seguinte situação, depois de cadastrar os itens na loja, salvei, e ok, funcionou tranquilo, porem na hora que fui incluir produtos semelhantes, para aparecer logo abaixo do item em tela, ao salvar , a pagina perde totalmente a configuração, ficando como se fosse em caixa e aparece somente os itens incluídos como semelhantes, toda a parte superior do item em tela desaparece.

### Expected behavior

não fiz a imagem, mas da maneira que esta, a loja busca itens variados ja cadastrados e mostra 4 opções, mas sem considerar que sejam itens do mesmo seguimento, busca aleatoriamente entre outros ja cadastrados, ao informar na tela especifica das variáveis , ao salvar ocorre o descrito acima

### Actual behavior

Ate mesmo como forma redundante de informação, usando o exemplo de dobradiças, que estão dentro da categoria de ferragens, como são vários modelos a intenção seria mostrar 3 ou 4 opções de modelos diferentes, sendo que originalmente como disse busca itens variados...e ao informar os itens da mesma categoria, ele quebra o código e perde a configuração da pagina do item

### Steps to reproduce

![image](https://user-images.githubusercontent.com/71400141/210269096-de940cf5-f2bf-4dd9-8a6d-d07b67bd7560.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://milblocos.net
Site address (URL): http://milblocos.net
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.32
PHP Post Max Size: 2 GB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Tamanho total do banco de dados: 156.72MB
Tamanho dos dados do banco de dados: 105.63MB
Tamanho do índice do banco de dado: 51.09MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 4.52MB + Índex: 3.55MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 3.52MB + Índex: 3.03MB + mecanismo InnoDB
wp_auto_updates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ce4wp_abandoned_checkout: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ce4wp_contacts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_duplicator_pro_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_duplicator_pro_packages: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ewwwio_images: Dados: 3.52MB + Índex: 1.80MB + mecanismo InnoDB
wp_ewwwio_queue: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_addon_feed: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_draft_submissions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_entry: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_entry_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_gf_entry_notes: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_form: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gf_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gf_form_revisions: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_form_view: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_rest_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gla_budget_recommendations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gla_shipping_rates: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_litespeed_avatar: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_litespeed_img_optm: Dados: 2.52MB + Índex: 0.55MB + mecanismo InnoDB
wp_litespeed_img_optming: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_litespeed_url: Dados: 0.23MB + Índex: 0.25MB + mecanismo InnoDB
wp_litespeed_url_file: Dados: 0.19MB + Índex: 0.41MB + mecanismo InnoDB
wp_login_redirects: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automation_runs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_automation_run_logs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_automation_triggers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automation_versions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_migrations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_templates: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_scheduled_tasks: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_bounces: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wp_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscriber_tag: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_tags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_micro_revisions: Dados: 3.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_campaign_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_campaign_logmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_conversions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_email_campaignmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_email_campaigns: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mo_optin_campaignmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_optin_campaigns: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_options: Dados: 7.52MB + Índex: 0.59MB + mecanismo InnoDB
wp_pmxi_files: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_hash: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_history: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_images: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_imports: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_posts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_templates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_postmeta: Dados: 51.56MB + Índex: 28.58MB + mecanismo InnoDB
wp_posts: Dados: 15.52MB + Índex: 3.72MB + mecanismo InnoDB
wp_rank_math_404_logs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_analytics_objects: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_internal_links: Dados: 0.39MB + Índex: 0.11MB + mecanismo InnoDB
wp_rank_math_internal_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rank_math_redirections: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_redirections_cache: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rg_form: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_form_view: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_rg_incomplete_submissions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rg_lead: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_rg_lead_detail: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_rg_lead_detail_long: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_lead_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_rg_lead_notes: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 1.52MB + Índex: 0.52MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_um_metadata: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_update_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_user_registration_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log_product: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log_product_rule: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_transient_cart_data: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 3.52MB + Índex: 2.52MB + mecanismo InnoDB
wp_wc_product_download_directories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 1.52MB + Índex: 1.36MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_webarx_event_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_webarx_firewall_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_webarx_logic: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_debug_events: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_yith_wcwl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yith_wcwl_lists: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbscrm_api_keys: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_admlog: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_aka: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_zbs_companies: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_contacts: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_customfields: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_dbmigration_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_dbmigration_posts: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_events: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_event_reminders: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_externalsources: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_zbs_forms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_invoices: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_zbs_lineitems: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_meta: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_zbs_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_object_links: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_quotes: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_zbs_quotes_templates: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_security_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_segments: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_segments_conditions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_settings: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_sys_cronmanagerlogs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_sys_email: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_sys_email_hist: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_tags: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_tags_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_zbs_tax_table: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_temphash: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_tracking: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_transactions: Dados: 0.02MB + Índex: 0.14MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 3207
custom_css: 3
customize_changeset: 100
foobar_notification: 1
foogallery: 94
mailpoet_page: 1
nav_menu_item: 42
oembed_cache: 2
page: 59
post: 1
product: 785
product_variation: 10324
revision: 909
shop_coupon: 1
shop_order: 35
um_directory: 1
um_form: 3
user_registration: 2
wp_block: 2
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Gravity Forms: por Gravity Forms – 2.5.16
Hostinger: por Hostinger – 1.0
Akismet Anti-Spam: por Automattic – 5.0.2
Editor clássico: por Colaboradores do WordPress – 1.6.2
Widgets Clássicos: por Colaboradores do WordPress – 0.3
Companion Auto Update: por Papin Schipper – 3.8.7.1
Creative Mail por Newfold Digital: por Newfold Digital – 1.6.6
EWWW Image Optimizer: por Exactly WWW – 6.9.3
Facebook para WooCommerce: por Facebook – 3.0.6
FooBar WordPress Notifications: por FooPlugins – 2.1.15
FooGallery (Premium): por FooPlugins – 2.1.28
Site Kit by Google: por Google – 1.90.1
Marketing com tecnologia de IA: por Kliken – 1.1.0
LiteSpeed Cache: por LiteSpeed Technologies – 5.3.1
Loco Translate: por Tim Whitlock – 2.6.3
Mailchimp para Woocommerce: por Mailchimp – 2.7.6
MailOptin - Lite: por MailOptin Popup Builder Team – 1.2.54.0
MailPoet: por MailPoet – 4.3.0
Media Deduper: por Cornershop Creative – 1.5.5
Microthemer: por Themeover – 7.1.6.4
Fonts Plugin | Google Fonts Typography: por Fonts Plugin – 3.2.6
MyPopUps: por Pop-ups – 1.1.9
Really Simple SSL: por Really Simple Plugins – 6.0.14
Importador RSS: por wordpressdotorg – 0.3
Side Cart WooCommerce: por XootiX – 2.1
Storefront Top Bar: por Wooassist – 1.1.1
Ultimate Social Media PLUS: por social share pro – 3.5.7
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.8.1
WooCommerce Parcelas Com e Sem Juros: por Leonardo Robles – 1.5.1
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2
Claudio Sanches - PagSeguro for WooCommerce: por Claudio Sanches – 2.14.0
WooCommerce Shipping & Tax: por WooCommerce – 2.1.0
WooCommerce: por Automattic – 7.2.2
Importador do WordPress: por wordpressdotorg – 0.8
WP Mail SMTP: por WPForms – 3.7.0
Multi-Step Checkout for WooCommerce: por SilkyPress – 2.22
Social Chat PRO: por QuadLayers – 2.6.9
Social Chat: por QuadLayers – 6.2.7
Importador do conversor de categorias em tags: por wordpressdotorg – 0.6
YITH WooCommerce Wishlist: por YITH – 3.16.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base da loja: #23 - /loja/
Carrinho: #24 - /carrinho/
Finalização de compra: #25 - /finalizar-compra/
Minha conta: ❌ A página não contém o shortcode [woocommerce_my_account].
Termos e condições: #23 - /loja/

### Theme ###

Name: Astra
Version: 3.9.4
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-03 17:44:55 -03:00
Options: ✔
Notes: 94
Onboarding: completed

### Action Scheduler ###

Canceled: 16
Oldest: 2022-12-17 12:23:58 -0300
Newest: 2022-12-21 12:54:31 -0300

Complete: 11.515
Oldest: 2022-12-04 14:56:06 -0300
Newest: 2023-01-02 15:33:32 -0300

Failed: 62
Oldest: 2021-04-15 12:44:28 -0300
Newest: 2022-12-21 20:15:25 -0300

Pending: 2
Oldest: 2023-01-03 08:32:44 -0300
Newest: 2023-01-06 07:25:57 -0300

### Status report information ###

Generated at: 2023-01-02 15:33:48 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @JoseTNeto,

Thanks for your report. Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back.

> Hello, my website is www.milblocos.net
after the last update, the following situation started to appear, after registering the items in the store, I saved, and ok, it worked fine, but when I went to include similar products, to appear just below the item on the screen, when saving, the page completely loses its configuration, becoming as if it were in a box and only the items included as similar appear, the entire upper part of the item on the screen disappears.
>
> Expected behavior
> I didn't make the image, but the way it is, the store searches for varied items already registered and shows 4 options, but without considering that they are items of the same segment, it searches randomly among others already registered, when informing the specific screen of the variables, when saving the above occurs
> 
> actual behavior
> Even as a redundant form of information, using the example of hinges, which are within the hardware category, as there are several models, the intention would be to show 3 or 4 different model options, and originally, as I said, it seeks varied items... and when informing the items of the same category, it breaks the code and loses the configuration of the page of the item

Are you able to provide a set of detailed steps that we can use to reproduce this issue?
