### ISSUE TITLE
Woocommerce page produit

### ISSUE THREAD

**Issue by emarzolf** [woothemes/woocommerce#36261]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Bonjour,
La page "produits" de woocommerce" ne comporte pas de bouton de validation ou d'enregistrement des modifications.
Impossible de modifier les pages produits.

### Expected behavior

Impossible de valider la page.

### Actual behavior

Lorsqu'on quitte la page, les modifications ne sont pas conservées.

### Steps to reproduce

4

### WordPress Environment

woocommerce / produits / ajout
woocommerce / produits / modification

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by emarzolf** [comment]
![image](https://user-images.githubusercontent.com/121830314/210278901-b18089fa-d0e7-4329-a60b-fe2b340ec5cc.png)

**Comment by psealock** [comment]
Looks like trouble saving changes to the Products page.

@emarzolf Have you deactivated all other plugins? Is there an error message on the console? Can you add your environment details from a [Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/)?
