### ISSUE TITLE
New variations flow: add feature flag

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36276]
**Description:** we plan to start testing the simple physical product MVP with users very soon. We should add a feature flag to hide all the variations that's currently in development, as it's still not ready for external testing. 

**Acceptance criteria:**
- [ ] Introduce a feature flag to hide the variations management flow in progress whenever we need it: options tab and all the features/fields in this tab.

**Comment by joshuatf** [comment]
Estimate: 2

We might also need to double check that the `getDerivedProductType` method returns the correct type when variations are not enabled.

**Comment by pmcpinto** [comment]
@joshuatf is it possible to have an option in the helper plugin to enable/disable the variations management features?
