### ISSUE TITLE
Add remote endpoint API support for shipping partners in shipping task

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#36281]
This is a follow-up to https://github.com/woocommerce/woocommerce/issues/36248.

The objective of this task is to add a remote API endpoint for displaying shipping partners in the marketing task. This is to be hosted on WooCommerce.com, similar to `obw-free-extensions`. The data hosted are as follows:

1. Shipping partner logo
1. Plugin name
1. Plugin slug
1. Countries supported
1. Learn more link
1. Other copies depending on the confirmed design

We'd also need the image to be hosted on WooCommerce.com

## Acceptance Criteria

1. Add the ability for a remote endpoint to enable or disable the featured partners (p73Jol-1C5-p2#comment-6419)

**Comment by moon0326** [comment]
Hey @ilyasfoo ✋ 

Should we also add an option to remove suggestions similar to the marketing suggestion option? Or could we use the same option to control shipping partner suggestion behavior 🤔 ?

Payment suggestions can be removed from `WooCommerce -> Settings -> Advanced -> Show Suggestions`.

![Screen Shot 2023-02-27 at 2 31 11 PM](https://user-images.githubusercontent.com/4723145/221700966-35a4eba4-c078-4952-ac59-8aa9afd8a170.jpg)

**Comment by ilyasfoo** [comment]
Great question, @moon0326! For simplicity's sake, let's use the same method with payment suggestions here. I don't think our use case is any different.
