### ISSUE TITLE
Order item metadata table coupon_data rows growing nearly half the total database size

### ISSUE THREAD

**Issue by seanconklin** [woothemes/woocommerce#36295]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reopening issue #19450 after an earlier fix became inadequate.

I'm looking at a client's site with Database Data Size = 1235.88MB and of that the coupon_data rows of wp_woocommerce_order_items are ~450MB.

I checked on the age of the orders for which this data is stored and see it includes orders from today and recently.

This client actively uses an older coupon code with the restriction "Usage limit per user" = 1.

I'll attach the unserialized data showing where 340 rows fit into the data and are redacted here for privacy.

```
Array
(
    [id] => 4626
    [code] => first15
    [amount] => 15
    [status] => publish
    [date_created] => __PHP_Incomplete_Class Object
        (
            [__PHP_Incomplete_Class_Name] => WC_DateTime
            [ * utc_offset] => 0
            [date] => 2020-08-05 09:58:00.000000
            [timezone_type] => 3
            [timezone] => America/Los_Angeles
        )

    [date_modified] => __PHP_Incomplete_Class Object
        (
            [__PHP_Incomplete_Class_Name] => WC_DateTime
            [ * utc_offset] => 0
            [date] => 2020-09-08 10:48:38.000000
            [timezone_type] => 3
            [timezone] => America/Los_Angeles
        )

    [date_expires] => 
    [discount_type] => percent
    [description] => Spin to Win - 1x use per customer
    [usage_count] => 7570
    [individual_use] => 1
    [product_ids] => Array
        (
        )

    [excluded_product_ids] => Array
        (
        )

    [usage_limit] => 0
    [usage_limit_per_user] => 1
    [limit_usage_to_x_items] => 
    [free_shipping] => 
    [product_categories] => Array
        (
        )

    [excluded_product_categories] => Array
        (
        )

    [exclude_sale_items] => 
    [minimum_amount] => 
    [maximum_amount] => 
    [email_restrictions] => Array
        (
        )

    [virtual] => 
    [meta_data] => Array
        (
            [0] => __PHP_Incomplete_Class Object
                (
                    [__PHP_Incomplete_Class_Name] => WC_Meta_Data
                    [ * current_data] => Array
                        (
                            [id] => 127599
                            [key] => itemlist_item_3711
                            [value] => Array
                                (
                                )

                        )

                    [ * data] => Array
                        (
                            [id] => 127599
                            [key] => itemlist_item_3711
                            [value] => Array
                                (
                                )

                        )

                )

...

            [339] => __PHP_Incomplete_Class Object
                (
                    [__PHP_Incomplete_Class_Name] => WC_Meta_Data
                    [ * current_data] => Array
                        (
                            [id] => 3195766
                            [key] => _maybe_used_by_1672260676_OGhoxS
                            [value] => email_redacted@gmail.com
                        )

                    [ * data] => Array
                        (
                            [id] => 3195766
                            [key] => _maybe_used_by_1672260676_OGhoxS
                            [value] => email_redacted@gmail.com
                        )

                )

        )

)
```

### Expected behavior

I expect to see only data related to an order stored within its order items. Wider coupon usage data belongs with the coupon.

### Actual behavior

We're storing data from 340 users of a coupon code into new orders where the coupon code was used just once.

### Steps to reproduce

1. Open WooCommerce > Status
2. Observe wp_woocommerce_order_itemmeta = Data 628.61MB and Database Data Size = 1235.88MB
3. Open PhpMyAdmin and select the store's database
5. Click SQL and run this query to see the largest order item meta rows with order IDs and dates: `SELECT p.ID, p.post_date, oim.meta_key, ROUND( LENGTH( oim.meta_value ) / 1024 ) as size FROM wp_woocommerce_order_itemmeta oim JOIN wp_woocommerce_order_items oi ON oim.order_item_id = oi.order_item_id JOIN wp_posts p ON oi.order_id = p.ID ORDER BY `size` DESC;`
6. Observe thousands of rows of coupon_data occupying up to 94KB each.

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.25
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 1830.49MB
Database Data Size: 1235.88MB
Database Index Size: 594.61MB
wp_woocommerce_sessions: Data: 26.05MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 12.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 628.61MB + Index: 68.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.50MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 83.14MB + Index: 103.44MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 60.61MB + Index: 47.14MB + Engine InnoDB
wp_commentmeta: Data: 4.52MB + Index: 4.02MB + Engine InnoDB
wp_comments: Data: 70.61MB + Index: 47.13MB + Engine InnoDB
wp_dgwt_wcas_index: Data: 0.42MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_page: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_post: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 26.55MB + Index: 30.06MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_page: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_post: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_page: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_post: Data: 0.45MB + Index: 0.30MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.39MB + Index: 0.06MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.17MB + Engine InnoDB
wp_postmeta: Data: 235.77MB + Index: 221.55MB + Engine InnoDB
wp_posts: Data: 18.52MB + Index: 10.06MB + Engine InnoDB
wp_redirection_404: Data: 3.02MB + Index: 0.70MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_redirection_logs: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.45MB + Index: 0.52MB + Engine InnoDB
wp_terms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wp_term_taxonomy: Data: 2.52MB + Index: 0.11MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 23.56MB + Index: 25.09MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 1.11MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 7.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 4.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.53MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 0.97MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.27MB + Index: 0.25MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_yoast_prominent_words: Data: 1.52MB + Index: 3.50MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.52MB + Index: 0.39MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 20
acf-field-group: 9
attachment: 1301
custom_css: 3
elementor_font: 1
elementor_library: 19
nav_menu_item: 101
oembed_cache: 19
page: 21
post: 94
product: 523
product_variation: 597
revision: 38
shop_coupon: 307
shop_order: 43577
shop_order_refund: 1391
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Advanced Custom Fields: by WP Engine – 6.0.6
FiboSearch - AJAX Search for WooCommerce (Pro): by FiboSearch Team – 1.21.1
Akismet Anti-Spam: by Automattic – 5.0.2
WP Engine Smart Plugin Manager: by WP Engine – 5.13.8
Code Snippets: by Code Snippets Pro – 3.2.2
Elementor Pro: by Elementor.com – 3.9.2
Elementor: by Elementor.com – 3.9.2
Facebook for WooCommerce: by Facebook – 3.0.7
Google Listings and Ads: by WooCommerce – 2.3.5
Google Tag Manager for WooCommerce PRO: by Handcraft Byte – 1.7.3
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.20
Klaviyo: by Klaviyo
Inc. – 3.0.6

Pinterest for WooCommerce: by WooCommerce – 1.2.8
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.38
Redirection: by John Godley – 5.3.6
Up-sell Trio for WooCommerce: by Coded Commerce
LLC – 1.2

User Role Editor: by Vladimir Garagulya – 4.63.2
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Address Validation: by SkyVerge – 2.10.0
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Multi-currency: by TIV.NET INC – 3.1.2
WooCommerce Quick View: by WooCommerce – 1.6.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce: by Automattic – 7.2.2
Yoast SEO Premium: by Team Yoast – 19.6
Yoast SEO: by Team Yoast – 19.13
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.10

Smush: by WPMU DEV – 3.12.4
Yoast SEO: WooCommerce: by Team Yoast – 15.4
Zoho Mail: by Zoho Mail – 1.4.9

### Inactive Plugins (2) ###

GoDaddy Payments: by GoDaddy – 1.3.4
Query Monitor: by John Blackbourn – 3.11.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.0
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #16485 - /products/
Cart: #122 - /cart/
Checkout: #123 - /checkout/
My account: #125 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-04 18:56:23 -08:00
Options: ✔
Notes: 8
Onboarding: completed

### Action Scheduler ###

Complete: 250,207
Oldest: 2022-12-04 09:48:10 -0800
Newest: 2023-01-04 09:42:41 -0800

Pending: 21
Oldest: 2023-01-04 09:44:55 -0800
Newest: 2023-01-10 11:25:18 -0800

### Status report information ###

Generated at: 2023-01-04 09:44:14 -08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks, we can see the same thing and it would seem there is potential to reduce the amount of data we are persisting in this area.

**Comment by michaelrimbach** [comment]
We are having the same issue but in a bigger dimension (because we have more orders and coupon usages).
Our table wp_woocommerce_order_itemmeta is 258,7 GiB(!) large and grows very fast.

Could you please prioritize this issue.

**Comment by hussong** [comment]
We are affected by this as well.

**Comment by michaelrimbach** [comment]
Our WooCommerce table is now over 300 GiB because of this issue. Any news here? Please escalate.

**Comment by michaelrimbach** [comment]
@mikejolley @claudiosanches

**Comment by rrennick** [comment]
@michaelrimbach We appreciate your sense of urgency. I've written the PR linked above which reduces the storage requirement for order coupons. We are still discussing further improvements which we may add before merging.

**Comment by martinhinrichs** [comment]
The main problem is really the _maybe_used_by_*** data. That is 95% of the data use of the order_items table in our case. I can see no reason at all to store a list of all email addresses of customers who have used the coupon previously every single time the coupon is used. That list grows longer and longer, leading to exponential growth of the database table size. The dehydration PR does not address this.

We have developed a custom script for removing the _maybe_used_by data. We have found no place in the woocommerce, plugin or API code where it is used and removing it has not lead to any issues whatsoever. It has merely reduced the size of our order items table from > 300 GB to currently ~13 GB. It would be great not to have to maintain this workaround any more.

**Comment by barryhughes** [comment]
There's a discussion happening [over here](https://github.com/woocommerce/woocommerce/discussions/41040) (which you are aware of, but linking to it in case useful for others) that outlines some possible solutions.

> We have found no place in the woocommerce, plugin or API code where it is used and removing it has not lead to any issues whatsoever.

That's great to hear.

So part of the reason for the discussion is that sometimes it appears to us that a given piece of data, or code, is unused—but then it causes unexpected disruption, because of the way it is consumed in third party applications (which we don't have any visibility into). So, the discussion is an attempt to sound the community before we roll anything out.
