### ISSUE TITLE
Change "return to the main product" logic 

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#36293]
**Describe the bug:**
When the user is editing a variation and clicks to return to the main product, he's redirected to the respective tab in the parent product. I think it makes more sense to redirect the user to the Options tab, where he has access to all variations. 

**Steps to reproduce:**
1. Create a new product using the new experience in the test store: pcQJnU-Lr-p2
2. Create at least one variation and edit the variation
3. Visit one of the tabs (Pricing, General, etc) and click "return to the main product"
4. Confirm that you're redirected to the respective tab in the parent product

**Comment by joshuatf** [comment]
Estimate: 1
