### ISSUE TITLE
[7.3 beta]: date_completed and date_modified queries does not work in HPOS

### ISSUE THREAD

**Issue by bjorntechTobbe** [woothemes/woocommerce#36307]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using WP_Order_Query in HPOS the parameters date completed and date_modified are ignored. This is because a bug in OrdersTableQuery maybe_remap_args.

In here the date_completed are remapped to date_completed_gmt and date_modified are remapped to date_modified_gmt.

Due to the fact that the section Translate from WC_Order_Query to table structure also holds date_completed_gmt and date_modified_gmt in the left side of the array the following loop will unset them both and the query will return all current orders instead of the wanted selection

The bug affects all order fetching.

### Expected behavior

// Get orders paid.
$args = array(
    'date_completed' => '2023-01-03',
);
$orders = wc_get_orders( $args );

Should only return orders having being completed 2023-01-03

### Actual behavior

All orders in the system will be returned

### Steps to reproduce

Use the code in expected behavior above.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.3
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: sv_SE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.30
PHP Post Max Size: 30 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Din server har inte klassen SoapClient aktiverad – vissa betalmoduler som använder SOAP kanske inte fungerar som förväntat.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total databasstorlek: 5.06MB
Datastorlek för databas: 3.27MB
Indexstorlek för databas: 1.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Motor InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Motor InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_options: Data: 2.05MB + Index: 0.08MB + Motor InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.06MB + Motor InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Motor InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Motor InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Motor InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 2
product_variation: 4
revision: 1
shop_coupon: 1
shop_order: 10
shop_order_refund: 3
swish: 21
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ❌Felmeddelanden ska inte visas för besökare.

### Active Plugins (14) ###

Action Scheduler: av Automattic – 3.5.3
Integration of Bjorn Lunden with WooCommerce: av BjornTech AB – 1.0.0
Code Profiler Pro: av Jerome Bruandet ~ NinTechNet Ltd. – 1.5.2
Gutenberg: av Gutenberg-teamet – 14.8.4
PW WooCommerce Gift Cards: av Pimwick
LLC – 1.221

Relative URL: av Tunghsiao Liu – 0.1.8
Transients Manager: av WPBeginner – 2.0.3
Integration of ready2order with WooCommerce: av BjornTech – 2.0.3
WooCommerce Accounting Report: av BjornTech – 5.5.1
WooCommerce Accounting Report: av BjornTech – 2.2.0
WooCommerce Fortnox Hub: av BjornTech – 5.5.1
WooCommerce Beta Tester: av WooCommerce – 2.1.0
WooCommerce Stripe Gateway: av WooCommerce – 7.0.1
WooCommerce: av Automattic – 7.3.0-rc.1

### Inactive Plugins (2) ###

Swish Donations: av BjornTech AB – 1.0.0
Woo Swish e-commerce: av BjornTech – 3.5.6

### Must Use Plugins (1) ###

Code Profiler (mu-plugin): av Jerome Bruandet – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Butikbas: #6 - /butik/
Varukorg: #7 - /varukorg/
Kassan: #8 - /kassan/
Mitt konto: #9 - /mitt-konto/
Villkor: ❌ Sida har inte valts

### Theme ###

Name: Twenty Twenty-Two
Version: 1.3
Author URL: https://sv.wordpress.org/
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-06 07:21:11 +01:00
Options: ✔
Notes: 65
Onboarding: skipped

### Action Scheduler ###

Complete: 103
Oldest: 2022-12-15 09:58:31 +0100
Newest: 2023-01-05 10:08:23 +0100

Failed: 1
Oldest: 2023-01-04 16:22:19 +0100
Newest: 2023-01-04 16:22:19 +0100

Pending: 2
Oldest: 2023-01-05 10:40:32 +0100
Newest: 2023-01-05 11:08:23 +0100

### Status report information ###

Generated at: 2023-01-05 10:12:10 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @bjorntechTobbe,

Thanks for the report. This isn't a problem anymore in the latest version. [A fix was added](https://github.com/woocommerce/woocommerce/pull/36843) recently which should make it into 7.6.0 (to be released mid-April).

A such I'm closing this for now. Let me know if you have any questions and thanks again!
