### ISSUE TITLE
[HPOS] Problems when ordering-by date via the REST API 

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#36313]
When working on https://github.com/woocommerce/woocommerce/pull/36308 I observed that a REST API query like the following (where we order by date, descending) may not work as expected when HPOS is authoritative:

```
# Implict
/wp-json/wc/v3/orders

# Explicit
/wp-json/wc/v3/orders?orderby=date&order=desc
```

This is because:

- HPOS order queries do not support passing multiple order-by values in a single string (example: `date ID`).
- The above is something we rely on, from within [WC_REST_CRUD_Controller](https://github.com/woocommerce/woocommerce/blob/7.2.2/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php).
- The reason it works with the CPT order store is that it is built on top of `WP_Query`, which *does* support this convention.

Internal discussion p1672952839476529-slack-C0E1AV8T0.

**Comment by vedanshujain** [comment]
This was also resolved by #36215
