### ISSUE TITLE
Enable new experience when new user selects "Physical product"

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#36319]
Enable the new experience when a new user selects the "Physical product" option in the "Add products" task.

**Acceptance criteria:**

- [ ] Enable the new experience after selecting "Physical product" in the "Add products" task.
- [ ] The rest of the users should get the current experience.
- [ ] Redirect the user to the new experience instead of the old one.
- [ ] Add Tracks events.

**Comment by octaedro** [comment]
Estimate: 1

**Comment by joshuatf** [comment]
@pmcpinto Are there any specific props or naming you want for this tracks event?
