### ISSUE TITLE
Show new survey when the user turns off the new experience

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#36324]
In the bottom bar, if the user selects "Turn it off", we should show a new survey before redirecting the user to the current experience. This survey should also be displayed when the user selects the "use the classic editor" option at the top bar.

![Screenshot 2023-01-06 at 15 53 57](https://user-images.githubusercontent.com/1314156/211079667-f9f42643-a889-4372-a189-0d258632fdad.png)

<img width="929" alt="Captura de ecrã 2022-10-17, às 16 29 58" src="https://user-images.githubusercontent.com/3380168/196220119-4850d6a3-a0aa-4360-abb8-e6a88ce1142f.png">

**Survey**
`Title`: `Tooltip` + "Thanks for trying out the new product editor!"
`Body`: We’re working on making it better, and your feedback will help improve the experience for thousands of merchants like you.
`Secondary button`: Skip
`Primary button`: Send feedback 
`Options title`: What made you switch back to the classic product editor? _(Check all that apply)_
`Options`: 
- Missing features
- Missing plugins
- It is difficult to use
- It is slow, buggy, or broken
- Other (describe below)

`Textarea`:
- Title: Additional comments
- Textarea placeholder: Optional, but much appreciated. We love reading your feedback!

`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A6362&t=7PveV6YsBsObVtis-1

**Notice**
After sending the survey, a notice will be shown with the text: 🌟  Thanks for the feedback. We’ll put it to good use!

<img width="599" alt="Screenshot 2023-01-06 at 15 48 59" src="https://user-images.githubusercontent.com/1314156/211078856-1e9b8a11-389f-41a8-af23-5164d3640f53.png">

**Acceptance criteria:**
- [ ] Show the new survey before redirecting the user to the current experience after pressing "Turn it off" in the bottom bar.
- [ ] Show the new survey after pressing "Use the classic editor" in the bottom bar.
- [ ] After sending the survey, show a notice with the text: 🌟  Thanks for the feedback. We’ll put it to good use!

**Comment by octaedro** [comment]
Estimate: 3

**Comment by joshuatf** [comment]
For showing the notice after redirecting to the old experience, we can use TransientNotices.

https://github.com/woocommerce/woocommerce/blob/04903118299ee7ffa3b599d3c4edffb9a70dd979/plugins/woocommerce/src/Admin/Features/TransientNotices.php#L85-L98

**Comment by octaedro** [comment]
Hey @pmcpinto and @jarekmorawski,

I'm working on this issue and would like to confirm if we will show this survey every time the user disables the new experience (through the mentioned buttons) or if it's something that will only be shown once.

I also want to confirm what happens when the user checks the box `Other (describe below)`. Should the user fill the text area shown below, or will we show another text area to fill out?

**Comment by jarekmorawski** [comment]
Hiya 👋

> if we will show this survey every time the user disables the new experience (through the mentioned buttons) or if it's something that will only be shown once.

We should show it each time.

> I also want to confirm what happens when the user checks the box Other (describe below). Should the user fill the text area shown below, or will we show another text area to fill out?

No, it concerns the text area below the form. This checkbox mainly serves as a way to categorize feedback.

**Comment by pmcpinto** [comment]
@octaedro can you confirm if we still need this issue?

**Comment by octaedro** [comment]
Hi @pmcpinto,
Thank you for the ping. We have already addressed the first two items in the acceptance criteria. However, we still need to implement the third one  (_After sending the survey, show a notice with the text: 🌟 Thanks for the feedback. We’ll put it to good use!_).
If it's alright with you, I'll create a new issue specifically for this task.
I will go ahead and close the current issue.
