### ISSUE TITLE
CSV Import Doubles Sub-Categories

### ISSUE THREAD

**Issue by ChrissiePollock** [woothemes/woocommerce#36336]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Categories are duplicated upon import, and an error is thrown when importing from CSV.

### Expected behavior

I expected the import to sync with existing products, including categories and child categories. 

### Actual behavior

Original product categories from secondary site:

![Annotation on 2023-01-08 at 10-17-47](https://user-images.githubusercontent.com/2545184/211204828-1361bbd2-602a-4b28-a8db-a7e4888184da.png)

**Export:**

<img width="700" alt="Screen Shot 2023-01-08 at 10 23 20" src="https://user-images.githubusercontent.com/2545184/211204883-bd9e1e15-6813-43ee-b19d-9d1e2918acce.png">

**Categories in CSV:**

<img width="763" alt="Screen Shot 2023-01-08 at 10 18 43" src="https://user-images.githubusercontent.com/2545184/211204913-9cd9410f-e82e-4b93-af13-e9a45d3b190b.png">

**Error after Import:**

<img width="577" alt="Screen Shot 2023-01-08 at 10 19 55" src="https://user-images.githubusercontent.com/2545184/211204942-1a6d6fc6-10c2-42e5-9d77-796de5a2f683.png">

**Duplicated Categories After Import:**

This is under Clothing>Accessories and shows more duplicates since I tested a few times (note that test2 is not checked, either):

<img width="213" alt="Screen Shot 2023-01-08 at 10 31 43" src="https://user-images.githubusercontent.com/2545184/211205191-636afaf3-ad21-4bec-9440-0bd45e9a08c1.png">

### Steps to reproduce

* Create a product with multiple child categories on a secondary test site. 
* Make sure the categories exist already on the primary test site.
* Create a product on each site, and make sure the skus match.
* Export products on the secondary site from All Products>Export -- Use default settings and include Meta.
* Import the CSV into the primary test site.

### WordPress Environment

Reported in #5815875-zen and replicated on personal test site. Different SSRs. 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ghost** [comment]
Also having this issue. I don't recall an error on import though. I just have hundreds of products under new subcategories with appended numerals. Very frustrating.

**Comment by rrennick** [comment]
@ChrissiePollock or @GordonZed Could you provide a small sample export file that reproduces this issue?
