### ISSUE TITLE
Analytics: Bypass scheduled actions for customer updates

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#36330]
### Description

In order to decrease the load on Action Scheduler and improve overall site performance, instead of scheduling actions when a customer is updated (via checkout or other means), we should directly update the Analytics customer data store. The updates to the Analytics data store are not performance intensive and the expected overall performance gains outweigh the slight increase in synchronous processing when customer updates are made.

### Acceptance criteria

- [ ] When a new customer is created (actions: `woocommerce_new_customer`), `CustomersDataStore::update_registered_customer` should be called
- [ ] When a customer is updated (actions: `woocommerce_update_customer`, `updated_user_meta`), `CustomersDataStore::update_registered_customer` should be called
- [ ] When a customer is deleted (actions `delete_user`, `remove_user_from_blog`), `CustomersDataStore::delete_customer_by_user_id()` should be called
- [ ] When personal data is removed from an order (action: `woocommerce_privacy_remove_order_personal_data`), `CustomersScheduler::anonymize()` should be called (see implementation detail below about moving this code)

### Implementation details (as long as AC is met, other approaches may also be valid... take these as suggestions)

- Actions listed above are currently hooked up in `CustomersScheduler` ([source](https://github.com/woocommerce/woocommerce/blob/4c236bdc37a8a8be81efe988f48a240041a86379/plugins/woocommerce/src/Internal/Admin/Schedulers/CustomersScheduler.php#L30))
- Should probably move where actions are hooked up to in `CustomersDataStore::init()` ([source](https://github.com/woocommerce/woocommerce/blob/1ab678c13fed5df393805f0000a8fd0db991772a/plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php#L86))
- Should probably move `CustomersScheduler::anonymize()` implementation to `CustomersDataStore::anonymize()` (not sure why this wasn't done initially)

### References 

- Original suggestion by @joshuatf: p7bje6-4BB-p2#comment-7613

**Comment by mattsherman** [comment]
Estimate: 1 (testing to ensure no regression will be the bulk of the effort; there is really no major implementation required, just some minor moving of code around)

@joshuatf I'd be interested in your thoughts on this issue, to make sure I didn't miss anything.

**Comment by jonathansadowski** [comment]
@AnnaMag Just a heads up on this one, I noticed this was in a milestone named `7.5`. We don't typically put issues in milestones numbered for the release, but I have nothing against the practice (so long as we continue to stick to code freeze). I'm going to move this into the `7.5.0` milestone though, as that's how we number our milestones for our automations tied to the release, and I want to delete the `7.5` milestone so that PRs don't get accidentally added to it and missed when 7.5 rolls around.

**Comment by samueljseay** [comment]
Hey folks, since 7.5.0 code freeze is gonna happen tomorrow, I'm just noting that I don't think you'll make it in for this release.
