### ISSUE TITLE
Error de Software Automatizado

### ISSUE THREAD

**Issue by h3l0s** [woothemes/woocommerce#36348]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

He intentado hacer que mi software de automatización haga las importaciones de archivos de inventario por mí en mi WooCommerce, y me aparece un error diciendo que "No tiene permisos para realizar esta acción", ¿Hay alguna forma de permitir el acceso? ¿Necesito desactivar alguna función de reconocimiento de Software Automatizado? Hemos invertido mucho en la implementación de este sistema, pero no conseguimos que pueda ser totalmente autónomo.
![Captura1](https://user-images.githubusercontent.com/122303684/211372427-f9dadef7-16c0-4401-82c1-5e9a4be301cc.PNG)

### Expected behavior

Se esperaba que funcionase e hiciese la importación csv sin impedirlo debido al software automatizado.

### Actual behavior

He intentado hacer que mi software de automatización haga las importaciones de archivos de inventario por mí en mi WooCommerce, y me aparece un error diciendo que "No tiene permisos para realizar esta acción", ¿Hay alguna forma de permitir el acceso? ¿Necesito desactivar alguna función de reconocimiento de Software Automatizado? Hemos invertido mucho en la implementación de este sistema, pero no conseguimos que pueda ser totalmente autónomo.
![Captura1](https://user-images.githubusercontent.com/122303684/211372427-f9dadef7-16c0-4401-82c1-5e9a4be301cc.PNG)

### Steps to reproduce

![Captura1](https://user-images.githubusercontent.com/122303684/211372660-9247fdda-430e-4184-b080-442f8129f7dd.PNG)
Al hacer la importación con el software automatizado deniega el acceso.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.inges-com.com
Site address (URL): http://www.inges-com.com
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 6 MB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.38-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wpap_
Tamaño total de la base de datos: 218.80MB
Tamaño de los datos de la base de datos: 176.66MB
Tamaño del índice de la base de datos: 42.14MB
wpap_woocommerce_sessions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wpap_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpap_woocommerce_order_items: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wpap_woocommerce_order_itemmeta: Datos: 0.22MB + Índice: 0.27MB + Motor InnoDB
wpap_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpap_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_actionscheduler_actions: Datos: 8.52MB + Índice: 12.08MB + Motor InnoDB
wpap_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_actionscheduler_logs: Datos: 5.52MB + Índice: 5.02MB + Motor InnoDB
wpap_cartflows_ca_cart_abandonment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_cartflows_ca_email_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_cli_cookie_scan: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_cli_cookie_scan_categories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_cli_cookie_scan_cookies: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_cli_cookie_scan_url: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_cli_scripts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_comments: Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
wpap_evf_entries: Datos: 0.08MB + Índice: 0.02MB + Motor InnoDB
wpap_evf_entrymeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpap_evf_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_ewwwio_images: Datos: 0.09MB + Índice: 0.08MB + Motor InnoDB
wpap_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_facto_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_facto_order_mp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_loginizer_logs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_options: Datos: 13.05MB + Índice: 1.14MB + Motor InnoDB
wpap_pmxi_files: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_hash: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_images: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_imports: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_posts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_pmxi_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_postmeta: Datos: 69.58MB + Índice: 10.31MB + Motor InnoDB
wpap_posts: Datos: 57.52MB + Índice: 4.56MB + Motor InnoDB
wpap_redirection_404: Datos: 0.28MB + Índice: 0.13MB + Motor InnoDB
wpap_redirection_groups: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_redirection_items: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wpap_redirection_logs: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpap_revslider_css: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wpap_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_revslider_sliders: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wpap_revslider_slides: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wpap_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_termmeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpap_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wpap_term_relationships: Datos: 0.47MB + Índice: 0.39MB + Motor InnoDB
wpap_term_taxonomy: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wpap_usermeta: Datos: 0.13MB + Índice: 0.06MB + Motor InnoDB
wpap_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpap_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wc_order_product_lookup: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wpap_wc_order_stats: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wpap_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wc_product_meta_lookup: Datos: 1.03MB + Índice: 0.95MB + Motor InnoDB
wpap_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wfblockediplog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpap_wfconfig: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wpap_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wffilemods: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wpap_wfhits: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpap_wfhoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wfissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpap_wfknownfilelist: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wpap_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wflogins: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpap_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpap_wfstatus: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpap_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_categories: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_category_maps: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_circles: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_maps: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_polygon: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_polylines: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_wpgmza_rectangles: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpap_yoast_indexable: Datos: 9.52MB + Índice: 4.30MB + Motor InnoDB
wpap_yoast_indexable_hierarchy: Datos: 1.52MB + Índice: 0.72MB + Motor InnoDB
wpap_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpap_yoast_primary_term: Datos: 0.14MB + Índice: 0.14MB + Motor InnoDB
wpap_yoast_seo_links: Datos: 0.28MB + Índice: 0.16MB + Motor InnoDB
wpap_yoast_seo_meta: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 10464
carousels: 1
cartflows_flow: 3
cartflows_step: 6
custom_css: 2
dflip: 1
elementor_library: 2
everest_form: 1
mc4wp-form: 1
nav_menu_item: 28
oembed_cache: 15
page: 44
post: 1749
product: 4796
productsliderwoo: 1
revision: 2933
shop_order: 105
shop_order_refund: 41
sp_wps_shortcodes: 1
wcpcsu-custom-post: 1
wcps: 1
wcps_layout: 1
woocarousel: 1
wp_global_styles: 3
wpcf7_contact_form: 2
wpephpcompat_jobs: 33
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Plantillas de inicio: por Brainstorm Force – 3.1.21
CartFlows: por CartFlows Inc – 1.11.8
Checkout Plugins - Stripe for WooCommerce: por Checkout Plugins – 1.4.10
CMP - Coming Soon & Maintenance Plugin: por NiteoThemes – 4.1.6
Elementor: por Elementor.com – 3.9.2
Essential Addons for Elementor: por WPDeveloper – 5.5.2
Happy Elementor Addons: por weDevs – 3.8.0
WE Invoice. Facturas para WooCommerce: por weinvoice – 1.2.3
Product Carousel Slider & Grid Ultimate for WooCommerce: por wpWax – 1.9.0
WooCommerce: por Automattic – 7.2.2

### Inactive Plugins (35) ###

Adapta RGPD: por Superadmin – 1.3.7
Akismet Anti-Spam: por Automattic – 5.0.2
Alfred, the Assistant: por 1&1 IONOS – 5.4.1
All-in-One WP Migration: por ServMask – 7.69
All-in-One WP Migration File Extension: por ServMask
Inc. – 1.8

Contact Form 7: por Takayuki Miyoshi – 5.7.2
CookieYes | GDPR Cookie Consent: por CookieYes – 3.0.7
Customer Reviews for WooCommerce: por CusRev – 5.14.0
Custom Product Tabs for WooCommerce: por YIKES
Inc. – 1.8.2

Everest Forms: por WPEverest – 1.9.7
Facebook for WooCommerce: por Facebook – 3.0.6
Flash Toolkit: por ThemeGrill – 1.2.4
Google Analytics for WordPress by MonsterInsights: por MonsterInsights – 8.11.0
Page Builder by SiteOrigin: por SiteOrigin – 2.20.3
Payin7 WooCommerce: por Dropwp – 2.0.5
PDF Invoices & Packing Slips for WooCommerce: por WP Overnight – 3.2.6
PHP Compatibility Checker: por WP Engine – 1.5.2
Really Simple CAPTCHA: por Takayuki Miyoshi – 2.1
Really Simple SSL: por Really Simple Plugins – 6.0.14
Redirection: por John Godley – 5.3.6
Redsys WooCommerce: por Redsys – 3.1.1
Return Refund and Exchange for WooCommerce: por WP Swings – 4.0.9
Revenue Generator: por Laterpay – 2.4.0
SiteOrigin Widgets Bundle: por SiteOrigin – 1.46.0
ThemeGrill Demo Importer: por ThemeGrill – 1.8.9
Variation Swatches for WooCommerce: por CartFlows – 1.0.6
Variation Swatches for WooCommerce: por Emran Ahmed – 2.0.16
WC - APG NIF/CIF/NIE Field: por Art Project Group – 1.7.4
WC - APG SMS Notifications: por Art Project Group – 2.25
WC - APG Weight Shipping: por Art Project Group – 2.5.0.3
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.21
WooCommerce Stripe Gateway: por WooCommerce – 7.0.1
WordPress Importer: por wordpressdotorg – 0.8
WPForms Lite: por WPForms – 1.7.9
Yoast SEO: por Team Yoast – 19.13

### Must Use Plugins (1) ###

1&1 Product Subdomain: por 1&1 – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la tienda: #10 - /shop-2/
Carrito: #210 - /shop/cart/
Finalizar compra: #12 - /checkout/
Mi cuenta: #13 - /my-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 3.9.4
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-10 09:33:10 +00:00
Options: ✔
Notes: 22
Onboarding: completed

### Action Scheduler ###

Completo: 25.211
Oldest: 2022-12-10 00:40:26 +0000
Newest: 2023-01-09 14:12:13 +0000

Pendiente: 4
Oldest: 2023-01-10 13:46:15 +0000
Newest: 2023-01-30 00:00:26 +0000

### Status report information ###

Generated at: 2023-01-09 17:44:31 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @h3l0s,

Thanks for your report. Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back.

> Describe the bug
> I've tried to get my automation software to do the inventory file imports for me in my WooCommerce, and I get an error saying "You don't have permissions to perform this action", is there a way to allow access? Do I need to disable any Automated Software recognition features? We have invested a lot in the implementation of this system, but we have not been able to make it fully autonomous.
> Capture1
>
> Expected behavior
> It was expected to work and do the csv import without preventing it due to automated software.
> 
> Actual behavior
> I've tried to get my automation software to do the inventory file imports for me in my WooCommerce, and I get an error saying "You don't have permissions to perform this action", is there a way to allow access? Do I need to disable any Automated Software recognition features? We have invested a lot in the implementation of this system, but we have not been able to make it fully autonomous.
>
> Steps to reproduce
> Doing the import with the automated software denies access.
