### ISSUE TITLE
Filter woocommerce_customer_taxable_address lacks parameters necessary for giving the correct result

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#36352]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The method `WC_Customer::get_taxable_address()` has the final line:

```
return apply_filters( 'woocommerce_customer_taxable_address', array( $country, $state, $postcode, $city ) );
```

Note that it does not pass any input parameters to the filter, only the output. Specifically, `$this` is not passed, nor anything equivalent (e.g. `$this->get_id()`).

Consequently, any user of the filter cannot know which customer's taxable address is being examined. It could be any customer on the system.

To fix this, the filter should have `$this` added as a parameter, so that code hooking the filter can know *which* customer's address is being requested.

Note that consequently, any existing code in the world using this filter is likely to be assuming that the customer to be examined is the current customer (i.e. the value of `WC()->customer`) - but that this is a false assumption, since the filter will be called whenever the method is for any customer.

As an example, consider this code:

```
$customer = new WC_Customer(123); // Get customer object for user ID 123

$taxable_address = $customer->get_taxable_address();
```

Any extension code that has hooked the filter will not know that it's specifically user ID 123 that it is being asked the result for. And if it consults `WC()->customer`, it will get the wrong customer.

**Comment by barryhughes** [comment]
Agreed, we should also supply the user ID. For anyone who is interested, we'd certainly be receptive to a pull request that addresses this.
