### ISSUE TITLE
Keeping WordPress Dependencies up to date

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36357]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As a result of pcShBQ-zd-p2 the Monorepo will switch to using [dist tags](https://href.li/?https://github.com/WordPress/gutenberg/issues/24376) such as `"@wordpress/components": "wp-6.1"` to keep WordPress dependencies in line with the `Requires at least` tag, which is bumped by the [Bump L-2 Support](https://github.com/woocommerce/woocommerce/actions/workflows/bump-wp-l-2-support.yml) action.

The following are discrete tasks that can be broken up into smaller issues if you desire.

- [ ] Update all WP dependencies to L-2. This will cause build errors. Notify teams owning the code for help fixing these errors.
- [ ] Centralise dependency declarations using `syncpack`
- [ ] Add bumping these versions to part of the [Bump L-2 Support](https://github.com/woocommerce/woocommerce/actions/workflows/bump-wp-l-2-support.yml) action.

**Comment by roykho** [comment]
This is still WIP and the PR is [here](https://github.com/woocommerce/woocommerce/pull/36493) After the updates to the packages I am seeing build errors which needs to be addressed. But it should be a good starting point.

**Comment by samueljseay** [comment]
I'm going to do some of the TS fixes for this and see how far I can get, otherwise I think we will struggle to move this forward as teams are quite busy with their own feature work right now. 

Maybe if/when I get stuck I can pull in teams to fix the remaining issues.

**Comment by samueljseay** [comment]
The TS fixes were not a problem, but any updates to the linting package seems to break linting across the repo. I'm blocking this for now, while I try diagnose how to update lint as a separate task.
