### ISSUE TITLE
[Enhancement] Update behavior in other tabs when variations are added

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36359]
There are some use cases when the parent product fields may still be useful when the variations are enabled (especially when it comes to extensions). To accommodate, we will backtrack (sorry, folks!) on the decision to block access to the `Pricing`, `Inventory`, and `Shipping` tabs.

Instead, we'll allow full access to these tabs and show a banner notice with an explanation.

**Design**

`BaoQ3PGPnhAiJCsJtxgej3/%5BFeature%5D-fi-796%3A158534&t=S0uVUax2hFrq2FQR-4`

<img width="715" alt="image" src="https://user-images.githubusercontent.com/79307566/214568711-28fca7fd-d111-4a62-bd92-50ff98192572.png">

**Acceptance criteria**

- [ ] Users can access all tabs when the variations are enabled.
- [ ] In each tab, we show a top-level notice reading: `This product has options, such as size or color. You should now manage each variation's price and other details individually.`.
- [ ] The button reads: `Go to Options` and takes people to the `Options` tab.
- [ ] The notice can be dismissed. When dismissed, it disappears from all other tabs. It cannot be brought back. We show it once per product. If someone dismissed it in the past, they'd see it again when they create a new product.

**Comment by pmcpinto** [comment]
cc @joshuatf

**Comment by jarekmorawski** [comment]
Tackled differently in the new block-based design.
