### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by mohammaddanish-cedcoss** [woothemes/woocommerce#36372]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Getting a warning message in the payment gateway setting

### Expected behavior

need to resolve the issue

### Actual behavior

the gateway setting is not showing right and layouts are getting bad

### Steps to reproduce

![screenshot-localhost_10113-2023 01 09-11_56_00](https://user-images.githubusercontent.com/76724269/211778786-e805e431-ed8d-4615-8b12-2eb1fb0760ea.png)

### WordPress Environment

this is coming on the woocommerce gateway setting page

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
thanks for the report @mohammaddanish-cedcoss 

Could you provide steps to reproduce like this:

1. ...
2. ...
