### ISSUE TITLE
[Enhancement]: Category data sent via `product.updated` webhook

### ISSUE THREAD

**Issue by radialmonster** [woothemes/woocommerce#36401]
### Describe the solution you'd like

On the webhook for product update, can you please add the product category to the data it sends? The product category is sent when a new product is created, but when a product is updated, the category does not seem to be sent. Even if the product category is not changed, we’d like to still be sent the product category.

**Comment by barryhughes** [comment]
Hi @radialmonster,

This is not something I can replicate. 

When a product is updated (and if that product has categories), the JSON payload looks something like the following—note the presence of the `categories` array. I've shortened and prettified things a little, to make it easier to digest, but this is otherwise actual output from a test I performed, capturing the payload sent via the `product.updated` webhook:

```json
{
  "id": 863,
  "name": "Test Product",
  "slug": "test-product",
  "permalink": "https:\\/\\/local.wp\\/product\\/test-product\\/",
  "date_created": "2023-01-20T11:01:49",
  "date_created_gmt": "2023-01-20T19:01:49",
  "date_modified": "2023-01-20T11:06:47",
  "date_modified_gmt": "2023-01-20T19:06:47",
  "type": "simple",
  "status": "publish",
  "categories": [
    {
      "id": 89,
      "name": "Automotive",
      "slug": "automotive"
    },
    {
      "id": 37,
      "name": "Bag",
      "slug": "bag"
    },
    {
      "id": 27,
      "name": "Bench",
      "slug": "bench"
    }
  ]
}
```

When reporting a bug, following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) is very much appreciated. For example, it would be valuable to know if you have carried out the troubleshooting steps in the "Isolating the Problem" section, and it could be informative to see your system status report.

Please do let us know if you still encounter this problem, and if there are specific steps-to-replicate we should follow. Thanks!

**Comment by radialmonster** [comment]
hmm it seems i have a plugin called WooCommerce Visibility that when enabled, and i update a product with a category that i have hidden, the webhook sends the product update, however the category is blank 

"categories": [],

is it intended to hide the category in such case?

https://codecanyon.net/item/woocommerce-products-visibility-hide-or-show-by-user-role/18587731?sso=1


thank you

**Comment by barryhughes** [comment]
Thanks for the update.

Since this seems to be the result of a plugin conflict, rather than a bug in WooCommerce itself, I'll go ahead and close the issue. For further guidance/support, it is probably best to reach out to the author of that other plugin (it's not something we maintain or are familiar with).

**Comment by radialmonster** [comment]
I'd like to revisit this please.  I have removed the plugin i thought was causing this issue, and im still seeing it.  The next clue I have is this *possibly* only occurs for Variations.  if the product is a variation, it does not include the category in the sent data on product update.  sorry im not expert, but this is what ive found from poking around.  maybe this will make sense for someone.  If there is something else i can test please let me know thx

If I have a type Variable product, the data sent includes categories:
The top part of that data sent is like this:
{
    "weight": "",
    "virtual": false,
    "variations": {
        "0": 8045,
        "1": 8046
    },
    "type": "variable",
    "total_sales": 0,
    "tax_status": "taxable",
    "tax_class": "",
    "stock_status": "onbackorder",
    "stock_quantity": 0,
    "status": "publish",
    "sold_individually": false,
    "slug": "the-fantasticks-2022",
    "sku": "The-Fantasticks-2022",
    "short_description": "",
    "shipping_taxable": true,
    "shipping_required": true,
    "shipping_class_id": 72,
    "shipping_class": "video-flat-rate-free",
    "sale_price": "",
    "reviews_allowed": true,
    "related_ids": {
        "0": 804,
        "1": 792,
        "2": 8542,
        "3": 742,
        "4": 786
    },
    "regular_price": "",
    "rating_count": 0,
    "purchase_note": "",
    "purchasable": true,
    etc etc
 and then it eventually gets to the category data

"categories": [
        {
            "slug": "videos",
            "name": "Videos",
            "id": 35
        }
    ],


But the Type "variation" for that product that are sent do not include that category section.  I'd like to see the Category sent along with the variation payload.
I'll include the entire data sent for the variation version, there is no category here.
    
{
    "weight": "",
    "virtual": false,
    "type": "variation",
    "total_sales": "0",
    "tax_status": "taxable",
    "tax_class": "",
    "stock_status": "instock",
    "stock_quantity": 2,
    "status": "publish",
    "sold_individually": false,
    "slug": "the-fantasticks-2022-blu-ray",
    "sku": "17017109",
    "short_description": "",
    "shipping_taxable": true,
    "shipping_required": true,
    "shipping_class_id": 72,
    "shipping_class": "video-flat-rate-free",
    "sale_price": "",
    "reviews_allowed": false,
    "regular_price": "31.95",
    "rating_count": 0,
    "purchase_note": "",
    "purchasable": true,
    "price_html": "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">$</span>31.95</bdi></span>",
    "price": "31.95",
    "post_password": "",
    "permalink": "https://dataforge.us/product/the-fantasticks-2022/?attribute_format=Blu-ray",
    "parent_id": 3047,
    "on_sale": false,
    "name": "The Fantasticks - 2022 - Blu-ray",
    "meta_data": {
        "0": {
            "value": "MNIP2NCPBJ5CSNYI3MT5TK5E",
            "key": "_square_item_variation_id",
            "id": 163272
        },
        "1": {
            "value": "1692893096658",
            "key": "_square_item_variation_version",
            "id": 163273
        }
    },
    "menu_order": 2,
    "manage_stock": true,
    "low_stock_amount": null,
    "jetpack_sharing_enabled": true,
    "images": [
        {
            "src": "https://dataforge.s3.amazonaws.com/dataforge.us/2022/08/06115052/the-fantasticks-cover-draft.jpg",
            "name": "the fantasticks cover draft",
            "id": 4443,
            "date_modified_gmt": "2022-10-06T15:50:52",
            "date_modified": "2022-10-06T07:50:52",
            "date_created_gmt": "2022-10-06T15:50:52",
            "date_created": "2022-10-06T07:50:52",
            "alt": ""
        }
    ],
    "id": 8046,
    "has_options": false,
    "featured": false,
    "external_url": "",
    "downloadable": false,
    "download_limit": -1,
    "download_expiry": -1,
    "dimensions": {
        "width": "",
        "length": "",
        "height": ""
    },
    "description": "",
    "date_on_sale_to_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_from": null,
    "date_modified_gmt": "2023-11-28T22:09:25",
    "date_modified": "2023-11-28T17:09:25",
    "date_created_gmt": "2023-07-26T20:54:48",
    "date_created": "2023-07-26T16:54:48",
    "catalog_visibility": "hidden",
    "button_text": "",
    "backorders_allowed": false,
    "backorders": "no",
    "backordered": false,
    "average_rating": "0.00",
    "attributes": [
        {
            "option": "Blu-ray",
            "name": "Format",
            "id": 0
        }
    ],
    "_links": {
        "up": [
            {
                "href": "https://dataforge.us/wp-json/wc/v3/products/3047"
            }
        ],
        "self": [
            {
                "href": "https://dataforge.us/wp-json/wc/v3/products/8046"
            }
        ],
        "collection": [
            {
                "href": "https://dataforge.us/wp-json/wc/v3/products"
            }
        ]
    }
}

**Comment by barryhughes** [comment]
Thanks, understood!

For backwards-compatibility reasons, I am a little unsure if we can change how the existing category field works in the case of product variables—but we could consider adding a `parent_categories` field. 

Alternatively, you could:

- Fetch the parent categories via a REST API request (since you will be supplied with the `parent_id`).
- Modify the webhook payload by using the `woocommerce_webhook_payload` filter hook (this way, you can customize it to best fit your needs).

**Comment by barryhughes** [comment]
Please ignore the `needs: vote` workflow. This is closed because I don't anticipate us having space to work on this, and because it seems that there are a range of viable alternatives available.

**Comment by radialmonster** [comment]
ok i see.  i will clarify i'm not asking to be able to set a different category for each variation.  i just want to see the parent product cateogry of a varitation and currenty unable to find it.  But i see i can get the product id of the variation, and then do another call to look up the parent product id and get its category, just will use a few extra api calls.  ok thank you.

**Comment by barryhughes** [comment]
> I will clarify i'm not asking to be able to set a different category for each variation.

Yep, understood—but it's not impossible there are extensions or customizations out there that *do* do this, and we wouldn't want to break those. So, as noted earlier, we would probably have to add an additional field (something like `parent_categories`) to the payload. This is something we'd consider, but it also isn't clear there is a widespread need for this.

**Comment by radialmonster** [comment]
parent_categories or something would be fine, but otherwise I can do the double lookup to find the parent info for the meantime thank you!

**Comment by radialmonster** [comment]
testing if i can reopen this
