### ISSUE TITLE
ProductReviews causes to get the parent comment when editing a child on wp-admin

### ISSUE THREAD

**Issue by lupus2k** [woothemes/woocommerce#36400]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using `wp-admin`, when editing a comment or review that has a parent, it is showing the parent on the editor.
This is caused because when translating the `Edit Comment` title, it is running `Automattic\WooCommerce\Internal\Admin\ProductReviews\Review:: edit_comments_screen_text` and it has when translating the `Edit Comments` title and it replaces the comment with the parent [here](https://github.com/Automattic/woocommerce.com/blob/e6e3a79c6a3565d42c4da5ead0bc425a5ce3a4ac/plugins/woocommerce/src/Internal/Admin/ProductReviews/Reviews.php#L538-L541).

### Expected behavior

Not replace the comment with the parent one.

### Actual behavior

It replaces the current comment with the parent one [here](https://github.com/Automattic/woocommerce.com/blob/e6e3a79c6a3565d42c4da5ead0bc425a5ce3a4ac/plugins/woocommerce/src/Internal/Admin/ProductReviews/Reviews.php#L538-L541)

### Steps to reproduce

1. On an Atomic site, go to a published post.
2. Post a comment there. Write something like "Parent comment".
3. Leave a reply to the "Parent comment".
4. Go to WP Admin > Comments section.
5. Click Edit on the reply to "Parent comment".
6. You will notice that it opens the parent comment in the editor instead of the reply you selected to edit (the URL is the correct one).

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://gdemichelisat6.wpcomstaging.com
Site address (URL): https://gdemichelisat6.wpcomstaging.com
WC Version: 7.2.3
REST API Version: ✔ 7.2.3
WC Blocks Version: ✔ 8.9.4
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.3
WC Database Prefix: wp_
Total Database Size: 4.69MB
Database Data Size: 2.75MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.22MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.28MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
jetpack_migration: 2
page: 9
post: 4
product: 1
revision: 23
wp_global_styles: 4
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Crowdsignal Forms: by Automattic – 1.6.6
WordPress.com Editing Toolkit: by Automattic – 3.52330
Gutenberg: by Gutenberg Team – 14.9.1
Jetpack: by Automattic – 11.7-a.10
Layout Grid: by Automattic – 1.8.2
Page Optimize: by Automattic – 0.5.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

WooCommerce: by Automattic – 7.2.3

### Inactive Plugins (22) ###

Classic Editor: by WordPress Contributors – 1.6.2
Facebook for WooCommerce: by Facebook – 3.0.8
Google Listings and Ads: by WooCommerce – 2.3.6
Pinterest for WooCommerce: by WooCommerce – 1.2.8
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
TikTok: by TikTok – 1.0.13
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.0
WooCommerce Back In Stock Notifications: by WooCommerce – 1.4.3
WooCommerce Brands: by WooCommerce – 1.6.41
WooCommerce Canada Post Shipping: by WooCommerce – 2.7.1
WooCommerce EU VAT Number: by WooCommerce – 2.8.0
WooCommerce Gift Cards: by WooCommerce – 1.15.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.19
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.6
WooCommerce Payments: by Automattic – 5.3.0
WooCommerce Product Add-ons: by WooCommerce – 5.0.3
WooCommerce Product Bundles: by WooCommerce – 6.17.3
WooCommerce Royal Mail: by WooCommerce – 2.7.0
WooCommerce Shipment Tracking: by WooCommerce – 2.0.0
WooCommerce Shipping & Tax: by WooCommerce – 2.1.1
WooCommerce UPS Shipping: by WooCommerce – 3.4.0
WooCommerce USPS Shipping: by WooCommerce – 4.6.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #34 - /shop/
Cart: #35 - /cart/
Checkout: #36 - /checkout/
My account: #32 - /mi-cuenta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Disco
Version: 1.0.3
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
navigation
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-13 04:30:43 -03:00
Options: ✔
Notes: 34
Onboarding: skipped

### Action Scheduler ###

Complete: 78
Oldest: 2023-01-10 20:05:44 -0300
Newest: 2023-01-12 15:52:47 -0300

Pending: 3
Oldest: 2023-01-12 16:52:47 -0300
Newest: 2023-01-13 01:32:33 -0300

### Status report information ###

Generated at: 2023-01-12 16:37:20 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @lupus2k!

Thanks for your report. This was also reported in #34344, and so I'm going to close this one as a duplicate. Please note that we have a PR open with a fix (#35888), but the author seems to no longer be responsive. I'm going to take over that PR. A fix should go out soon.
