### ISSUE TITLE
pnpm install fails when using Local based environment

### ISSUE THREAD

**Issue by hcw-rohan** [woothemes/woocommerce#36436]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is more of a tip in case anyone else encounters it but when running `pnpm install` I was getting an error on the `plugins/woocommerce-beta-tester postinstall$ composer install`:

`Problem 1
│     - phar-io/manifest is locked to version 1.0.3 and an update of this pack
│     - phar-io/manifest 1.0.3 requires ext-dom * -> it is missing from your s
│   Problem 2
`

This was solved by running the following commands:
`sudo apt-get install php-xml`

and then

` sudo apt-get install php-curl`

Not sure if this was unique to my environment but I'm running Pop!_OS 22.04 LTS and using Local 6.6.0+6231.

Hope this helps someone!

### Expected behavior

pnpm install runs correctly

### Actual behavior

Exits with Error code 2

### Steps to reproduce

1. Setup new Wordpress install using Local
2. Clone repo
3. cd into repo and run `pnpm install`

### WordPress Environment

Local 6.6.0+6231, WP 6.1.1, PHP 7.4.30

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @hcw-rohan,

Thanks for the report. I agree that our documentation could definitely be improved when it comes to the requirements. PHP can be compiled many ways, and on some systems its default package is compiled with all of the dependencies, while on others it's not.

I'd like to see us add some troubleshooting steps to our documentation for the latter case. Guidelines for installing the needed components. I'll leave this issue open until we can get those added.

**Comment by samueljseay** [comment]
I've added some instructions to hopefully make this clearer in https://github.com/woocommerce/woocommerce/pull/38239
