### ISSUE TITLE
[Enhancement]: Show placeholder in custom attribute title after deleting text from input

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#36448]
### Describe the solution you'd like

As a follow-up to #35904, there's an issue when the attribute name is filled and then deleted. In this case, we should not show a blank title, but something else. Perhaps show "Custom attribute" placeholder again.

EDIT: Show "New attribute" instead of "Custom attribute".

@jarekmorawski what do you think? There are video recordings of all the mentioned behaviors on PR #35904.

**Comment by jarekmorawski** [comment]
Hiya! I think something like `F.e. Material or Brand` could work. Can we also change the text that appears in the form's header? From `Custom attribute` to `New attribute`.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/79307566/223150019-2f55b2dd-1075-4dfb-ba2f-706c5a8f7f91.png">

**Comment by octaedro** [comment]
This bug is fixed by PR https://github.com/woocommerce/woocommerce/pull/37645
