### ISSUE TITLE
Analytics custom date range not custom at all

### ISSUE THREAD

**Issue by mtnairroasting** [woothemes/woocommerce#36451]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When in Analytics, "SELECT A DATE RANGE" does not allow one to select a date range outside of the limited presets.

### Expected behavior

I expect to be able to select a custom date range, as per the Woocommerce "Reports" section.

### Actual behavior

Only these are available to select from:

Custom
select a preset period

Today

Yesterday

Week to date

Last week

Month to date

Last month

Quarter to date

Last quarter

Year to date

Last year

### Steps to reproduce

click on analytics, click on "date range"

compare to reports custom date range

### WordPress Environment

seriously, this is obviously a global issue...

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

**Comment by mtnairroasting** [comment]
You don't need a status report to see the problem

**Comment by mtnairroasting** [comment]
nevermind. user error.
