### ISSUE TITLE
Checkout error message display is not horizontal

### ISSUE THREAD

**Issue by natko1** [woothemes/woocommerce#36452]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The error messages on checkout are displayed vertically instead of horzontally. This makes it very hard to read, especially on mobile.

### Expected behavior

The error messages should be displayed horizontally so it can be read on desktop and mobile easily.

### Actual behavior

The error messages are displayed vertically.

### Steps to reproduce

1. Go to checkout
2. Don't enter any required fields
3. Click place order/confirm

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://ezgiftcards.ca
Site address (URL): https://ezgiftcards.ca
WC Version: 7.2.3
REST API Version: ✔ 7.2.3
WC Blocks Version: ✔ 8.9.4
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.37-MariaDB-log-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.3
WC Database Prefix: ezgc_
Total Database Size: 22.39MB
Database Data Size: 20.97MB
Database Index Size: 1.42MB
ezgc_woocommerce_sessions: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
ezgc_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_actionscheduler_actions: Data: 0.32MB + Index: 0.13MB + Engine MyISAM
ezgc_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_actionscheduler_logs: Data: 0.22MB + Index: 0.16MB + Engine MyISAM
ezgc_bpspro_db_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_bpspro_login_security: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_bpspro_mscan: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_bpspro_seclog_ignore: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_comments: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
ezgc_email_log: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
ezgc_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_e_submissions: Data: 0.00MB + Index: 0.03MB + Engine MyISAM
ezgc_e_submissions_actions_log: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_e_submissions_values: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletters: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_scheduled_tasks: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
ezgc_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_settings: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_subscriber_tag: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_modify_profile_dashboard_fields__errors_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_options: Data: 3.90MB + Index: 0.16MB + Engine MyISAM
ezgc_postmeta: Data: 5.73MB + Index: 0.41MB + Engine MyISAM
ezgc_posts: Data: 8.23MB + Index: 0.12MB + Engine MyISAM
ezgc_rank_math_internal_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
ezgc_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_termmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
ezgc_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
ezgc_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
ezgc_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ezgc_usermeta: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
ezgc_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
ezgc_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woocommerce_square_customers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ezgc_woostify_attribute_index: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woostify_category_index: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ezgc_woostify_filter_index: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
ezgc_woostify_product_index: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woostify_sku_index: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_woostify_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ezgc_woostify_tag_index: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ezgc_woostify_tax_index: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
ezgc_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ezgc_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ezgc_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 217
callback: 4
custom_css: 1
customize_changeset: 20
elementor_font: 1
elementor_library: 6
mailpoet_page: 1
nav_menu_item: 8
page: 12
post: 6
product: 70
product_variation: 124
revision: 555
shop_order: 41
shop_order_refund: 1
uip-ui-template: 1
wp_global_styles: 1
wpt_product_table: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Address Autocomplete: by HighAddons – 1.0.6
Coinbase Commerce: by Coinbase Commerce – 1.2.1
Elementor Pro: by Elementor.com – 3.8.0
Elementor: by Elementor.com – 3.9.2
Email Log: by Sudar – 2.4.8
Email Verification for WooCommerce Pro: by WPFactory – 2.4.8
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.27
HappyFiles Pro: by Codeer – 1.7
Loco Translate: by Tim Whitlock – 2.6.3
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.38
Rank Math SEO: by Rank Math – 1.0.106
Trustpilot-reviews: by Trustpilot – 2.5.914
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.22.24

WooCommerce PayPal Payments: by WooCommerce – 2.0.1
WooCommerce: by Automattic – 7.2.3 (update to version 7.3.0 is available)
Woostify Pro: by Woostify – 1.7.5
WP Mail SMTP: by WPForms – 3.7.0

### Inactive Plugins (3) ###

BulletProof Security: by AITpro Website Security – 6.7
LiteSpeed Cache: by LiteSpeed Technologies – 5.3.2
WooCommerce Waitlist: by Neil Pie – 2.3.5 (update to version 2.3.6 is available)

### Must Use Plugins (1) ###

BPS MU Tools: by AITpro – 9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #9 - /shop
Cart: #10 - /cart
Checkout: #11 - /checkout
My account: #12 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: EZ Giftcards
Version: 1.3.1
Author URL: https://Yama.Digital
Child Theme: ✔
Parent Theme Name: Woostify
Parent Theme Version: 2.1.9
Parent Theme Author URL: https://woostify.com/about
WooCommerce Support: ✔

### Templates ###

Overrides: Arcadia-Theme/woocommerce/emails/customer-new-account.php
Arcadia-Theme/woocommerce/emails/customer-on-hold-order.php
Arcadia-Theme/woocommerce/emails/customer-reset-password.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-16 21:18:15 -04:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 1,045
Oldest: 2022-12-22 16:31:55 +0000
Newest: 2023-01-16 15:51:29 +0000

Failed: 15
Oldest: 2022-09-27 21:40:06 +0000
Newest: 2023-01-11 05:18:19 +0000

Pending: 2
Oldest: 2023-01-16 19:22:03 +0000
Newest: 2023-01-16 20:50:51 +0000

### Status report information ###

Generated at: 2023-01-16 12:35:00 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by natko1** [comment]
![error](https://user-images.githubusercontent.com/4186392/212728435-e80297e8-6608-4936-a8ad-44f7ea31a3a7.png)
![IMG_3618](https://user-images.githubusercontent.com/4186392/212729353-35d30d20-d0d5-47a3-a6d7-30af3ecb4b45.jpg)

**Comment by jonathansadowski** [comment]
Hi @natko1,

Thanks for your report. It looks like you're using a theme other than one of the default WordPress themes or [Storefront](https://woocommerce.com/storefront/). Does this issue still occur if you use one of the default themes or Storefront?
