### ISSUE TITLE
Twenty Twenty Three error notices

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#36458]
**Issue Description:**

Similar to some of my previous notice issues (ex: https://github.com/woocommerce/woocommerce/issues/29560 ) the twenty twenty three notices are all using the same coloring:

![image](https://user-images.githubusercontent.com/507025/212761977-1997d212-7d65-4e6e-a7e8-054cc8aabd8c.png)

Using an updated class for the buttons, does seem to get them styled

To test:
Add this snippet

```
add_action( 'woocommerce_before_main_content', 'test_notice_styles' );
function test_notice_styles() {
	if ( function_exists( 'wc_add_notice' ) ) {
		wc_add_notice( 'Error notice', 'error' );
		wc_add_notice( 'Another Error notice', 'error' );
		wc_add_notice( 'Message notice <a class="button wc-forward wp-element-button">Do the thing</a>', 'notice' );
		wc_add_notice( 'Info notice <a class="button wc-forward wp-element-button">Do the thing</a>', 'success' );
	}
}
```

I have been thinking that 
1. It might be nice to unify the notice styling in WooCommerce core? And then only change styles from the theme sheets. Though I think also the core styles are disabled/switched over to the theme stylesheet. 
2. Do error notices need to be styled on the `<li>` element? this is giving me a headache when I try to reuse the error notices in Mix and Match Products. My notice switches sizing as the padding changes when toggling between error/success states.

But that's just me thinking aloud... at a minimum Twenty Twenty Three stylesheet needs love for its notices.

**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Comment by barryhughes** [comment]
Thanks for flagging this, @helgatheviking!

It's nice that the notices currently mesh with the theme (in the sense that they use the `--wp--preset--color--primary` CSS var), but I agree it isn't ideal for them to share the same accent, as it makes it harder to differentiate between them.

> It might be nice to unify the notice styling in WooCommerce core? And then only change styles from the theme sheets. Though I think also the core styles are disabled/switched over to the theme stylesheet.

I agree, and you're correct regarding the way theme-specific styles (supplied by core) currently override the default stylesheet.  That said, if we wished, we could still have a set of common styles that are imported into each theme-specific stylesheet.

> Do error notices need to be styled on the &lt;li&gt; element?

Probably not; we could for example keep rules like this (keep them for back compat reasons):

```css
.woocommerce-error[role="alert"] li { display: inline-block; }
```

But augment them with additional rules like this (so long as we update the templates accordingly):

```css
.woocommerce-error[role="alert"] .individual-error { display: inline-block; }
```

**Comment by ralucaStan** [comment]
closing as it's not applicable any more
