### ISSUE TITLE
Extensibility: Free trial welcome texts

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#36463]
P2: pdibGW-1iQ-p2

![Image](https://user-images.githubusercontent.com/3747241/212793000-e153d6f2-c939-43b3-9098-299db17194bd.png)

The store’s welcome title and description is customized for free trial. We should use SlotFills for each of the text component.

Title is located [here](https://href.li/?https://github.com/woocommerce/woocommerce/blob/c3d62f113addbbf820ed5e8103a0a052092efc00/plugins/woocommerce-admin/client/task-lists/progress-title/progress-title.tsx#L65). 

Description is located [here](https://href.li/?https://github.com/woocommerce/woocommerce/blob/c3d62f113addbbf820ed5e8103a0a052092efc00/plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx#L55).

### Acceptance Criteria

1. An extension developer should be able to replace the title components
2. Extensibility point names should contain `experimental` keyword
2. Ideally, include sufficient documentation
1. Ideally, adhere to extensibility principles Pca54o-vO-p2 and pca54o-2ag-p2

**Comment by rjchow** [comment]
For this I think we can have a default (current) component, and if fills exist we can null the default. See how we can determine if fills exist [here](https://github.com/woocommerce/woocommerce/blob/87efd48ecf01897910ee0055f18fb3a440ffa8ae/plugins/woocommerce-admin/client/homescreen/header-banner-slot/header-banner-slot.tsx#L16)
