### ISSUE TITLE
[Enhancement]: security updates to be released separately to bug fix/feature updates

### ISSUE THREAD

**Issue by newtlabs** [woothemes/woocommerce#36471]
### Describe the solution you'd like

Please can we get security updates released separately to bug/feature updates? This has been a recurring issue where you release a lot of new features and bug fixes along with security fixes in any one update, so when the updates have issues we have to roll back and then the sites are not secure.

For example there is a security fix in the most recent update but the update itself is causing all kinds of bugs and CPU usage spikes so we have to rollback and wait for patches and in the meantime we have not got the security issues addressed.

**Comment by lsinger** [comment]
Hello @newtlabs,

Thank you for taking the time to share this idea — we appreciate your help. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

I am going to close this issue but am also pinging @woocommerce/developer-advocacy and @wcstaley for consideration.
