### ISSUE TITLE
Attributes control should be agnostic to attribute type

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36515]
Currently the `AttributesControl` component houses logic around variations.  We should remove this from the attribute control and allow consumers to control the type of attributes.

**Acceptance criteria**

* [ ] We should remove the `attributeType` prop
* [ ] Copy/text specific to variations should be modifiable via props
* [ ] `onEdit`, `onCancel` and any other events where consumers need to plug in to custom hooks should be available via props

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-
