### ISSUE TITLE
Tour kit should focus the first step after opening

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36512]
When opening the tour kit and viewing the first step, the first step is not focused.  For accessibility, it would be helpful if this modal was immediately focused if no `focusElement` was provided so that users can use a keyboard to navigate.

![Image](https://user-images.githubusercontent.com/10561050/213572715-2c9a068b-5f93-4ef4-8102-b94c1e20f232.png)

**Reproducing**

1. On a new site, navigate to the new product experience
2. Click “Show me around” in the modal that pops up
3. Note that you cannot use the keyboard to navigate immediately

**Acceptance criteria**

* [ ] On opening the tour kit, the step modal should be focused
* [ ] The keyboard should allow navigation to next/previous steps without needing to click
* [ ] If a `focusElement` is provided, it should still work and the modal should not be focused

**Comment by ROBERLANDIO** [comment]
https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml
