### ISSUE TITLE
New product experience should be responsive in smaller viewports

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36511]
On smaller screens the product form layout is not responsive and not very usable. 

We should add a few media queries to tweak this experience and make it better for all screen sizes. 

![Image](https://user-images.githubusercontent.com/10561050/213571867-9f0d42c0-c250-4d1b-990a-30c9ceafc880.png)

**Reproducing**

1. Open the new product management experience
2. Narrow your viewport to a smaller size
3. See that the form and section titles are side by side and too narrow for use

**Acceptance criteria**

* [ ] Sections should be responsive and collapse on mobile screens
* [ ] If any other sections don’t appear responsive should be fixed

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by AnnaMag** [comment]
Adding another responsiveness-related case: 
https://d.pr/v/rBblpP
This a follow-up to https://github.com/woocommerce/woocommerce/pull/39156.

**Comment by mattsherman** [comment]
Closing this as it refers to the old new product experience.
