### ISSUE TITLE
Task list list items should show spinner when busy

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36510]
When loading the task list product task, clicking the physical product can take some time to load the next page since we await a few async actions (checking experiment group, enabling the option, etc). 

We should introduce a spinner to indicate loading status and look at ways to optimize the flow of these async actions so that it takes less time. 

![Image](https://user-images.githubusercontent.com/10561050/213571580-95d2ac97-67ae-431a-880c-cfc399f5915a.png)

**Reproducing**

1. On a new site (unassigned to an experiment group), navigate to the task list on the homepage. 
2. Click the “products” task. 
3. Click “physical product”
4. Note the delay before being taken to a new page. 

**Acceptance criteria**

- [ ] A spinner should show while loading the next state
- [ ] Async actions should happen concurrently where possible to reduce delay

**Comment by yashitamittal11** [comment]
I am working on this task - "A spinner should show while loading the next state".
I have moved the other task, "Async actions should happen concurrently where possible to reduce delay", to a separate issue - https://github.com/woocommerce/woocommerce/issues/39333
