### ISSUE TITLE
wc_format_decimal and null (Deprecated warning in PHP 8)

### ISSUE THREAD

**Issue by seldimi** [woothemes/woocommerce#36528]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While using WooCommerce Product CRUD, there are many calls to "wc_format_decimal()". There is a line with a str_replace that says the following:

$number = str_replace( $decimals, '.', $number );

If $number is empty string (eg ''), it doesn't product any warning. If $number is null, it passed the !float if and the following error occurs:
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

Possible solution:
Change if statement to check for string/array 
if ( ! is_float( $number )  && is_string( $number ))

To this line
https://github.com/woocommerce/woocommerce/blob/7d8f7ad57c99fe1653b474bcc944eaf1b7e830b4/plugins/woocommerce/includes/wc-formatting-functions.php#L295

### Expected behavior

Prevent str_replace run on non string/array subject

### Actual behavior

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

### Steps to reproduce

1) Create a product with WooCommerce CRUD
```
$product=new WC_Product();
$product->set_regular_price("10");
$product->set_sale_price(null);
$product->save();

```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by aezazs-multidots** [comment]
Hello @seldimi 

I tried this case in my local but it is working properly there.

Please try installing the latest WooCommerce version once. If you are still getting that error, then could you please share a short video?

Thanks.

**Comment by seldimi** [comment]
I haven't said its working, I've said its giving a warning.

**Comment by aezazs-multidots** [comment]
> I haven't said its working, I've said its giving a warning.

According to these cases, when I am creating a product from CRUD, it is not giving me any warning.

**Comment by seldimi** [comment]
Use PHP 8.1 please :)

**Comment by seldimi** [comment]
Hello. Have you tested it on 8.1 ?

**Comment by Konamiman** [comment]
Fix for that and other similar functions: https://github.com/woocommerce/woocommerce/pull/38635
