### ISSUE TITLE
[HPOS] do not allow order table to be sorted based on custom columns (based on meta data)

### ISSUE THREAD

**Issue by rajeshsingh520** [woothemes/woocommerce#36522]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you add a custom column based on some meta data to Order table With HPOS enabled you can not do the sorting based on that custom column

 

### Expected behavior

Sorting of the order table should be allowd based on the custom columns

### Actual behavior

In the wp_post based orders this feature was working we could sort the orders based on meta data 

### Steps to reproduce

Steps to creae the issue:

You should have HPOS enabled on the site 

step 1: create a custom meta data for order in this we ahave a meta data random_date that stores random date

step 2: add this mata data as a column to order table and set this column as sortable

step 3: sorting do not work on this columns

here is the test code add this code in your theme functions.php file, after adding this code place 3 test order
this code will add custom meta data random_date to those order and it will add the column Random date to order table and make it sortable as well and you can see sorting do not work based on meta data value

[class-hops-sortable-bug.txt](https://github.com/woocommerce/woocommerce/files/10464572/class-hops-sortable-bug.txt)

I have found that this is hpening due to this function sanitize_order_orderby()  in src\Internal\DataStores\Orders\OrdersTableQuery.php

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/hotel
Site address (URL): http://localhost/hotel
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.10
PHP Version: 8.1.10
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 5.33MB
Database Data Size: 3.60MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
page: 7
post: 2
product: 19
product_variation: 7
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0

### Inactive Plugins (172) ###

24hr time comparison: by PI Websolution – 1.0
AAA production hour: by PI Websolution – 1.1
Adding Flat rate shipping in Woocommerce Role manager: by PI Websolution – 1.0
Add order note for Woocommerce App: by PI Websolution – 1.0
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 3.1.1
Advanced Flat Rate Shipping For WooCommerce: by theDotstore – 4.0.4
Advanced Free - Flat shipping WooCommerce: by PI Websolution – 1.6.3.92
Advanced Free - Flat shipping WooCommerce - Pro: by PI Websolution – 1.2.7.49.4
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.2
Afterpay Gateway for WooCommerce: by Afterpay – 3.0.2
Akismet Anti-Spam: by Automattic – 5.0.1
ApplePay for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Bayna - Deposits & Partial Payments for WooCommerce: by Codeixer – 1.2.7
Both shipping and billing should be in post code range: by PI Websolution – 1.0
Buy one get one free PRO: by PI Websolution – 1.4.27
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 5.0.1
Change position of delivery and pickup on checkout page: by PI Websolution – 1.0
Cities Shipping Zones for WooCommerce: by Condless – 1.0.7
Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.5
Combined time slot order limit: by PI Websolution – 1.0
Conditional discount rule for WooCommerce: by PI Websolution – 1.9.14
Conditional discount rule for WooCommerce - Pro: by PI Websolution – 1.2.7.31
Conditional extra fees for WooCommerce: by PI Websolution – 1.0.92
Conditional extra fees for WooCommerce PRO: by PI Websolution – 1.0.29.22
Conditional Payments for WooCommerce: by Lauri Karisola / WooElements.com – 2.2.4
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.2.3
Convert Order limit in to quantity limit per time slot: by PI Websolution – 1.0
Convert order limit to quantity limit: by PI Websolution – 1.0
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.1.22
Custom coupon rule for shipping: by PI Websolution – 1.0
Custom coupon rule for shipping: by PI Websolution – 1.0
Custom special date text field: by PI Websolution – 1.0
Debug Bar: by wordpressdotorg – 1.0.1
Delivery date and time shortcode pro: by Rajesh Singh – 1.0.0
Delivery days cutoff  master PRO: by PI Websolution – 1.0.6
Delivery pickup popup Pro: by PI Websolution – 1.1.3.19
Delivery pickup reminder email Woocommerce: by PI Websolution – 1.3.94
Delivery pickup reminder email Woocommerce Pro: by PI Websolution – 1.1.6
Deposits & Partial Payments for WooCommerce: by Acowebs – 1.0.10
Different date time for different Pickup and Delivery location PRO: by PI Websolution – 1.1.9.36
Different Delivery type for Dokan vendors: by PI Websolution – 1.0.0
Dining at restaurant pro: by PI Websolution – 1.1.7
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout - PRO: by PI Websolution – 1.3.9.16
Direct Checkout for WooCommerce: by QuadLayers – 2.4.2
Disable Comments: by Samir Shah – 1.10.2
Disable payment method / COD fees for Order for WooCommerce: by PI Websolution – 1.0.47
Disable payment method / COD fees for Order for WooCommerce (PRO): by PI Websolution – 1.0.39
Dokan: by weDevs – 3.0.5
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy Updates Manager: by Easy Updates Manager Team – 9.0.8
Elated CPT: by Elated Themes – 1.4
Elated Instagram Feed: by Elated Themes – 2.1
Elated Twitter Feed: by Elated Themes – 1.1
Elementor: by Elementor.com – 3.9.2
Email Log: by Sudar – 2.4.8
Empty Cart Button for WooCommerce: by ProWCPlugins – 1.2.8
Envato Market: by Envato – 2.0.7
Estimated Delivery for WooCommerce: by TaxarPro – 1.2.2
Estimate delivery date for Woocommerce Pro: by PI Websolution – 4.7.7.6
Everest Forms: by WPEverest – 1.7.2.2
Extend popup plugin: by PI Websolution – 1.0
Financial report: by PI Websolution – 1.0.4
Fix Time picker distorted by "Livemesh Addons for WPBakery Page Builder": by PI Websolution – 1.0
Flexible Refund and Return Order for WooCommerce: by WP Desk – 1.0.1
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.2
Fluid Checkout for WooCommerce: by Fluid Checkout – 1.4.3
Germanized for WooCommerce: by vendidero – 3.3.7
Hide payment option as per selected date: by PI Websolution – 1.0
Hide shipping on cart page: by PI Websolution – 1.0
Hide shipping on cart page: by PI Websolution – 1.0
Hyperpay Payment Gateway plugin for WooCommerce: by Hyperpay Team – 1.0
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.4.3
Increment decrement quantity: by  –
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.11

KingComposer: by King-Theme – 2.9.3
License manager: by PI Websolution – 1.0.4
Loco Translate: by Tim Whitlock – 2.6.2
Mada for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Mercado Lite - Revolutionize Your eCommerce Store into Multifaceted Sales Platform: by RedefiningTheWeb – 1.1.0
Mercado Pro - Revolutionize Your eCommerce Store into Multifaceted Sales Platform: by RedefiningTheWeb – 1.1.1
Min Purchase Amount for Delivery order Pro (Addon plugin): by PI Websolution – 1.0.6.7
Modify delivery / pickup date and time: by PI Websolution – 1.0.2
Multi-Step Checkout for WooCommerce (Pro): by ThemeHigh – 2.0.2
Multi step compatible with date and time plugin: by PI Websolution – 1.1
Optimize date and time plugin: by PI Websolution – 1.0
Order Calendar for WooCommerce: by PI Websolution – 1.4.93
Order Calendar for WooCommerce Pro: by PI Websolution – 1.2.2.22
Order date, Order pickup, Order date time, Pickup Location, delivery date  for WooCommerce: by PI Websolution – 3.0.10
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.10.2
Page Builder by SiteOrigin: by SiteOrigin – 2.10.11
Payment Gateway Based Fees and Discounts for WooCommerce: by Tyche Softwares – 2.8.0
PayPlug pour WooCommerce (Officiel): by PayPlug – 1.2.10
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.6
PHP Compatibility Checker: by WP Engine – 1.5.2
Pickup location by url: by PI Websolution – 1.0
PI WooCommerce order date time and type PRO: by PI Websolution – 3.3.9.36
PixelYourSite: by PixelYourSite – 7.2.1.1
Polylang: by WP SYNTEX – 3.1.2
Postcode in popup: by PI Websolution – 1.1
Post Types Order: by Nsp Code – 1.9.8
PPOM for WooCommerce by N-MEDIA: by Najeeb Ahmad – 24.8
Preparation time Master PRO: by PI Websolution – 1.2.6.17
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.5
PRO Order Deliver, date, time, pickup location: by PI Websolution – 1.3.1
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Query Monitor: by John Blackbourn – 3.11.1
Razorpay Payment Links for WooCommerce: by Sayan Datta – 1.1.5
Red color for date and time in Email: by PI Websolution – 1.0
Renewal reminder email v2: by PI Websolution – 1.0.2
Restaurant Menu using WooCommerce: by PI Websolution – 6.1.96
Restaurant Menu using WooCommerce Pro: by PI Websolution – 2.7.3
RestroPress: by MagniGenie – 2.8.3.2
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.1

Safe SVG: by 10up – 2.0.3
Save Checkout form details: by PI Websolution – 1.0
Save time in 12 hr format: by PI Websolution – 1.0
Script to block monday, once it is Saturday time gone past 12pm: by PI Websolution – 1.0
senangPay: by senangPay – 3.1.2
Shipment tracking option: by PI Websolution – 1.0
Shipping option for DTT plugin: by PI Websolution – 1.0.3
Side Cart WooCommerce: by XootiX – 2.1
Simple Custom Post Order: by Colorlib – 2.5.0
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.8
SO Page Builder Animate: by Dunhakdis – 0.5
Special Working date & Special Timing Pro: by PI Websolution – 1.0.7.7
STCPay for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Store Hours Manager for WooCommerce: by BizSwoop a CPF Concepts
LLC Brand – 4.0.4

Stripe Payment Gateway for WooCommerce ( Basic ): by WebToffee – 3.4.9
Support proto star: by PI Websolution – 1.3
SVG Support: by Benbodhi – 2.3.18
test-block — CGB Gutenberg Block Plugin: by mrahmadawais
maedahbatool – 1.0.0

Test jQuery Updates: by The WordPress Team – 1.0.1
User Role Editor: by Vladimir Garagulya – 4.53.1
Wallet Premium: by Hoicker – 2.8
wePOS - Point Of Sale (POS) for WooCommerce: by weDevs – 1.1.6
Woo Add Custom States: by Trusted Technology Solutions (TrusTech) – 1.8.5
WooCommerce Advance Cash On Delivery PRO: by CodeRockz – 1.0.7
WooCommerce Amazon Fulfillment: by Never Settle – 3.3.5
WooCommerce Attribute Stock (Lite): by Mewz – 1.7.10
WooCommerce AvaTax: by SkyVerge – 1.16.5
WooCommerce Blocks: by Automattic – 9.2.0
WooCommerce Checkout Manager: by QuadLayers – 4.9.9
WooCommerce Deposits: by WooCommerce – 2.1.1
WooCommerce Menu Cart: by WP Overnight – 2.12.0
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
WooCommerce Open Close: by Pluginbazar – 4.2.8
WooCommerce Order Test - WP Fix It: by WP Fix It – 2.1
WooCommerce Payments: by Automattic – 4.5.1 (update to version 5.3.0 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 2.0.0 (update to version 2.0.1 is available)
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels: by WebToffee – 2.7.5
WooCommerce Point of Sale: by Webkul – 3.5.0
WooCommerce Role Based Methods: by WPBackOffice – 2.4.2
WooCommerce Stripe Gateway: by WooCommerce – 6.2.0
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.22
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.8
Woo Discount Rules: by Flycart – 2.4.2
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.6.4
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.3

WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
WPC Composite Products for WooCommerce: by WPClever.net – 3.0.4
WPC Product Bundles for WooCommerce: by WPClever – 5.5.2
WPC Product Timer for WooCommerce: by WPClever – 3.3.0
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP Mail Logging: by Wysija – 1.10.4
WP Mail SMTP: by WPForms – 2.4.0
WPML Multilingual CMS: by OnTheGoSystems – 4.5.8
WPML String Translation: by OnTheGoSystems – 3.2.1
YayMail - WooCommerce Email Customizer: by YayCommerce – 2.8.3
YITH WooCommerce Deposits and Down Payments Premium: by YITH – 1.13.0
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITH – 1.6.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (1) ###

Loco Standalone Loader: by Tim Whitlock – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 2.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-21 08:53:18 +00:00
Options: ✔
Notes: 37
Onboarding: completed

### Action Scheduler ###

Complete: 49
Oldest: 2023-01-20 08:57:21 +0000
Newest: 2023-01-20 09:02:16 +0000

Pending: 4
Oldest: 2023-01-20 09:02:26 +0000
Newest: 2023-01-21 08:54:27 +0000

### Status report information ###

Generated at: 2023-01-20 09:02:51 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for flagging this, @rajeshsingh520.

If I first add a random date to each order, and then add your test code, sorting on column "Random Date" appears to work as expected. Screenshots:

| Descending | Ascending |
| --- | --- |
| <img width="501" alt="sort-1" src="https://user-images.githubusercontent.com/3594411/214723823-ffdc7ddb-6988-4e8c-aecd-8cf726916e1b.png"> | <img width="501" alt="sort-2" src="https://user-images.githubusercontent.com/3594411/214723819-49d36943-e510-4567-8c0d-7acceb42acbf.png"> |

This may simply be because I'm testing with the latest `trunk` code, rather than `7.3.0` (as in your system status report). Do you find the same? If so, you may have been experiencing a bug or oversight that has been resolved (but hasn't yet shipped in an official release).

**Comment by rajeshsingh520** [comment]
Thanks for cheking, I will try it out with the overnight trunk code and see if it works or not

**Comment by rajeshsingh520** [comment]
Hi @barryhughes you are correct it has been fixed in the  overnight trunk so I am closing this

**Comment by barryhughes** [comment]
Great, thank you for taking the time to confirm (and for working with/testing HPOS)—much appreciated and if you experience any other problems, definitely let us know by creating new issues as needed.
