### ISSUE TITLE
Add sale amount and sale percentage functions

### ISSUE THREAD

**Issue by NimaBakhtiyari** [woothemes/woocommerce#36533]
### Describe the solution you'd like

I have prepared codes to calculate discount based on onsale in amount and percentage in simple or variable products.
formated string or float and display or not display symbols as well as rounding precision, showing zero or null in the output can be set by arguments.

```
/**
 * Sort prices for variable product
 *
 * @param $product
 * @return array
 */
public function sort_variation_price( $product ) {
	$prices = $product->get_variation_prices( true );
	foreach ( $prices['price'] as $product_id => $price ) {
		$product_obj                    = wc_get_product( $product_id );
		$prices['price'][ $product_id ] = wc_get_price_to_display( $product_obj );
	}
	asort( $prices['price'] );
	asort( $prices['regular_price'] );
	return array(
		'sale_min'    => current( $prices['price'] ),
		'sale_max'    => end( $prices['price'] ),
		'regular_min' => current( $prices['regular_price'] ),
		'regular_max' => end( $prices['regular_price'] ),
	);
}

/**
 * Returns sale amount for current product
 *
 * @param	bool			$formated_amount			Should the sale amount be formated.
 * @param	bool			$return_zero_value			Should the zero value be returned or null for zero value.
 * @param	int				$precision					value round precision
 * @param	bool			$display_currency_symbol	Should the currency symbol be displayed.
 * @return	float|string	$result						Product sale amount result.
 */
public function get_sale_amount( $formated_amount = true, $return_zero_value = false, $precision = 0, $display_currency_symbol = true ) {
    global $product;
    if( ! is_a( $product, 'WC_Product' ) ) {
        return null;
    }
    $sale_amount = '';
    if( 'variable' === $product->get_type() ) {
        $prices = $this->sort_variation_price( $product );
        if( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
            $sale_min  = $prices['regular_min'] - $prices['sale_min'];
            $sale_max  = $prices['regular_max'] - $prices['sale_max'];
            if( $sale_min != $sale_max ) {
                $sale_amount = round($sale_min, $precision ) . '-' . round($sale_max, $precision );
            } else {
                $sale_amount = round($sale_max, $precision );
            }
        }
    } else {
        $regular_price = (float)$product->get_regular_price();
        $sale_price    = (float)$product->get_price();
        $sale_amount  = round($regular_price - $sale_price, $precision );
    }
	if( $formated_amount ){
		if( 'variable' === $product->get_type() ) {
			if ( $display_currency_symbol ) {
				if( $sale_min != $sale_max ) {
					$result = wc_price( round($sale_min, $precision ) ) . '-' . wc_price( round($sale_max, $precision ) );
				} else {
					$result = wc_price( $sale_amount );
				}
			} else {
				if( $sale_min != $sale_max ) {
						$result = number_format( round($sale_min, $precision ), wc_get_price_decimals(), wc_get_price_decimal_separator(), wc_get_price_thousand_separator() ) . '-' . number_format( round($sale_max, $precision ), wc_get_price_decimals(), wc_get_price_decimal_separator(), wc_get_price_thousand_separator() );
				} else {
						$result = number_format( $sale_amount, wc_get_price_decimals(), wc_get_price_decimal_separator(), wc_get_price_thousand_separator() );
				}
			}
		} else {
			if( $display_currency_symbol ) {
				$result = wc_price( $sale_amount );
			} else {
				$result =  number_format( $sale_amount, wc_get_price_decimals(), wc_get_price_decimal_separator(), wc_get_price_thousand_separator() );
			}
		}
	} else {
		$result = $sale_amount;
	}
	if( ! $return_zero_value ) {
		if( 'variable' === $product->get_type() ) {
			if( round( $sale_min, $precision ) == 0 && round( $sale_max, $precision ) == 0 ) {
				$result = null;
			}
		} else {
			if( $sale_amount == 0 ) {
				$result = null;
			}
		}
	}
	return $result;
}

/**
 * Returns sale percentage for current product
 *
 * @param	bool			$formated_amount			Should the currency symbol be displayed.
 * @param	bool			$return_zero_value			Should the zero value be returned or null for zero value.
 * @param	int				$precision					value round precision
 * @return	float|string	$result						Product sale percentage result.
 */
public function get_sale_percentage( $formated_amount = true, $return_zero_value = false, $precision = 0 ) {
    global $product;

    if ( ! is_a( $product, 'WC_Product' ) ) {
        return null;
    }

    $sale_percentage = '';
	$symbol = '&#37;';
    if ( 'variable' === $product->get_type() ) {
        $prices = $this->sort_variation_price( $product );
        if ( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
            $percentage_min  = round( 100 - ( $prices['sale_min'] / $prices['regular_min'] * 100 ), $precision );
            $percentage_max  = round( 100 - ( $prices['sale_max'] / $prices['regular_max'] * 100 ), $precision );
			if ( $formated_amount ) {
				if ($percentage_min != $percentage_max ){
					$sale_percentage = $percentage_min . $symbol . '-' . $percentage_max . $symbol;
				} else {
					$sale_percentage = $percentage_max . $symbol;
				}
			} else {
				if ($percentage_min != $percentage_max ){
					$sale_percentage = $percentage_min . '-' . $percentage_max;
				} else {
					$sale_percentage = $percentage_max;
				}
			}
        }
    } else {
        $regular_price = (float)$product->get_regular_price();
        $sale_price    = (float)$product->get_price();
		if ( $sale_price > 0 && $regular_price > 0 ) {
			if ( $formated_amount ) {
				$sale_percentage = round( 100 - ( $sale_price / $regular_price * 100 ), $precision ) . $symbol;
			} else {
				$sale_percentage = round( 100 - ( $sale_price / $regular_price * 100 ), $precision );
    		}
		}
    }
    $result = $sale_percentage;
	if( ! $return_zero_value ) {
		if( 'variable' === $product->get_type() ) {
			if(  $percentage_min == 0 && $percentage_max == 0 ) {
				$result = null;
			}
		} else {
			if( round( 100 - ( $sale_price / $regular_price * 100 ), $precision ) == 0 ) {
				$result = null;
			}
		}
	}
	
	return $result;
}
```

### Describe alternatives you've considered

I have tested these functions with elementor dynamic tags with different parameters.
And the tests have been successful, the codes are ready to be added to your plugin.

variable product:
get_sale_amount:
![image](https://user-images.githubusercontent.com/90132570/213810205-968a3b9a-e775-4821-b636-cdd2fc38dc8d.png)
![image](https://user-images.githubusercontent.com/90132570/213810414-c1722ee3-a798-4a5a-a194-e01c68da7985.png)
![image](https://user-images.githubusercontent.com/90132570/213810546-ed792ff9-6617-45c2-87d8-3de5da15e722.png)
get_sale_percentage:
![image](https://user-images.githubusercontent.com/90132570/213810972-d9a50198-c731-4c85-a9ac-ab00939ccd1d.png)
![image](https://user-images.githubusercontent.com/90132570/213810880-26ed7966-148c-4f2e-bf3b-8023c1c75ca8.png)
![image](https://user-images.githubusercontent.com/90132570/213811108-473b4e4c-f697-4249-b8d0-b226a385a7a5.png)

simpale product:
get_sale_amount:
![image](https://user-images.githubusercontent.com/90132570/213812058-85bea012-c960-4c14-b1d6-a722d2ded962.png)
![image](https://user-images.githubusercontent.com/90132570/213811922-af548723-7f10-40d1-9cca-e9ad7e88958f.png)
![image](https://user-images.githubusercontent.com/90132570/213812165-fd41e717-5ff8-4dd5-b3f1-703da4bbbf3e.png)

get_sale_percentage:
![image](https://user-images.githubusercontent.com/90132570/213811362-39f2c0a8-8bc3-4b9e-9faf-56e6c1de110d.png)
![image](https://user-images.githubusercontent.com/90132570/213811424-75fbe2eb-b589-4665-ad0b-0647d1c1b044.png)
![image](https://user-images.githubusercontent.com/90132570/213811514-0e8d56c9-c9ae-410a-b955-5e461ba06a65.png)
![image](https://user-images.githubusercontent.com/90132570/213811696-98d79c29-ab44-4ab9-a267-d0f47f864283.png)

**Comment by jorgeatorres** [comment]
Hi @NimaBakhtiyari,

Thanks for your contribution. We agree that some of this functionality would be useful to have either in existing functions or in new ones, as you're proposing, but we feel the proper channel to continue the discussion would be to open a PR with the code changes.
That way we can suggest changes, discuss details, etc.

If you're interested, feel free to open a PR with the suggested functions and we'll take it from there. We have some more information on how to contribute to the project here: https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md.

I'm going to close this issue in the mean-time, but feel free to re-open if you think I've misrepresented anything. Thanks again!

**Comment by NimaBakhtiyari** [comment]
> Hi @NimaBakhtiyari,
> 
> Thanks for your contribution. We agree that some of this functionality would be useful to have either in existing functions or in new ones, as you're proposing, but we feel the proper channel to continue the discussion would be to open a PR with the code changes. That way we can suggest changes, discuss details, etc.
> 
> If you're interested, feel free to open a PR with the suggested functions and we'll take it from there. We have some more information on how to contribute to the project here: https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md.
> 
> I'm going to close this issue in the mean-time, but feel free to re-open if you think I've misrepresented anything. Thanks again!

thanks but I don't have access to the open pull request and I don't have experience with how to do it
![image](https://user-images.githubusercontent.com/90132570/232826570-5c7b4814-0010-454a-9bd7-e2177de88548.png)
