### ISSUE TITLE
[HPOS] handle_order_update happens too late?

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#36537]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm not sure this qualifies as a bug, a concern, a software design issue, or just a non-sense from my head. Cope with me :-D

When NOT using HPOS, the `woocommerce_process_shop_order_meta` action happens in `WC_Admin_Meta_Boxes::save_meta_boxes()` which runs on a POST call that is after redirected again to the order edit screen.

![image](https://user-images.githubusercontent.com/6853605/213860812-4479505f-ee67-45dc-a281-150d5c4d57a4.png)

But when USING HPOS, the the `woocommerce_process_shop_order_meta` action happens in `...Internal\Admin\Orders\Edit::handle_order_update()` which runs a POST that is NOT redirected to the post edit screen. In fact, this happens in the middle of the HTML output, just before the order edit form is rendered.

![image](https://user-images.githubusercontent.com/6853605/213860878-060892b9-257a-4cef-b025-93fe7b0138d2.png)

Let's say I have a custom order action, in which I will call an external API to do something (in this case create an invoice).

<img width="365" alt="image" src="https://user-images.githubusercontent.com/6853605/213860906-dfe70a0d-c0d9-4bff-b6ad-47394774e5bb.png">

I need to do it later in the `woocommerce_process_shop_order_meta` action so I have all the order meta data updated and ready to be used on my action, as WooCommerce does, by the way.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/6853605/213860964-d2c63ee5-e8c5-4d7d-a772-3231bd561760.png">

When NOT using HPOS, i can add a admin notice with the result of the action. If all goes OK, that notice might not be important, but if there's an external API failure, I do need to properly warn the user about it. If I add a admin notice it won't show up to user in this page load, but rather when he moves away from this page to do something else.

As I stated before, this might just a non-sense from me, and I might need to find another way to alert users (although that's what admin notices were designed for), but even if that's the case, I still think this is way too late to be saving an object. At this point we are WAY into HTML rendering. I'm not saying this should be done on a POST call and then redirect (like it works for CPTs), but at least wouldn't it be safer to do it around  the [wp_loaded](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_loaded) or [wp](https://codex.wordpress.org/Plugin_API/Action_Reference/wp) actions?

### Expected behavior

Not limited to, but be able to output notices or apply redirects if needed.

### Actual behavior

Order oject is updated during HTML rendering

### Steps to reproduce

1. Activate HPOS
2. Hook into woocommerce_process_shop_order_meta
3. Do your thing

### WordPress Environment

Latest WordPress and WooCommerce nightlys 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
@webdados thanks for the report. just to verify, would you say a mechanism to add a notice to the edit page would be sufficient for your request (instead of having to do a redirect)?

**Comment by webdados** [comment]
For my request? Yes.

I still think that processing the submitted form should be handled as soon as possible on the page load. There are a lot of hooks other developers can be using right now where the order still hasn't been processed, as opposed to what is happening without HPOS where when the GET is called to the order edit screen, everything was taken care of on the previous POST call.

**Comment by webdados** [comment]
Any updates on this?

**Comment by vedanshujain** [comment]
It's on our queue, we are aiming to tackle this soon.

**Comment by webdados** [comment]
Any news?

I'm now back to adding HPOS support to several plugins and still hitting on this issue.
It makes no sense that `woocommerce_process_shop_order_meta` happens so late with the all page already loaded and after `admin_notices`:
<img width="784" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6853605/7cf1c041-6a02-43ad-805a-834f67ed10c0">

As a last resort, we should be able to pass a `$notice` or a `$message` to the `render_wrapper_start` method of the `Automattic\WooCommerce\Internal\Admin\Orders|Edit` class, using filters maybe.

The way it's built right now is completely impossible to give feedback to users.

**Comment by vedanshujain** [comment]
hey @webdados we have added a PR for this in https://github.com/woocommerce/woocommerce/pull/39193, can you also take a look and let us know if that will resolve your issue. thanks!

**Comment by webdados** [comment]
It does resolve it.
