### ISSUE TITLE
Analytics does not send statistics that belongs to the chosen currency

### ISSUE THREAD

**Issue by martincpt** [woothemes/woocommerce#36542]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Items sold analytics does not downloads the csv sheet with the right currency and datas, when using more than one currency and the selected currency is other than the default. Even though currency being sent in the payload.

Bug only occurs if currency is other than default and if selected date range requires to send the CSV via email instead of downloading directly.

### Expected behavior

Analytics sends statistics that belongs to the **chosen currency**.

### Actual behavior

Analytics sends statistics that belongs to the **default currency**.

### Steps to reproduce

0. Use multi-currency mode like WCML
1. Go to Analytics / Items sold
2. Select a larger date range that forces script logic to send CSV via email.
3. Check CSV in email received with default currency statistics.

### WordPress Environment ###

WordPress address (URL): https://localhost
Site address (URL): https://localhost
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.0.1 - There is a newer version of WordPress available (6.1.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.22
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.37-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 47.87MB
Database Data Size: 37.43MB
Database Index Size: 10.44MB
wp_woocommerce_sessions: Data: 0.98MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.10MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.55MB + Index: 0.39MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.07MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
wp_billingo_documents: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_billingo_partnerhash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartbounty: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.48MB + Index: 0.19MB + Engine MyISAM
wp_db7_forms: Data: 0.13MB + Index: 0.01MB + Engine MyISAM
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 2.08MB + Index: 3.61MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_icl_translate: Data: 1.44MB + Index: 0.05MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.09MB + Index: 0.27MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 1.17MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.40MB + Index: 0.66MB + Engine MyISAM
wp_postmeta: Data: 6.39MB + Index: 2.39MB + Engine MyISAM
wp_posts: Data: 4.46MB + Index: 0.19MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.28MB + Index: 0.18MB + Engine MyISAM
wp_users: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.08MB + Engine MyISAM
wp_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 739
mailpoet_page: 1
nav_menu_item: 62
page: 30
post: 8
product: 54
revision: 269
shop_coupon: 4
shop_order: 408
custom_portfolio: 75
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.8
Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
Árukereső for Woocommerce: by       Oaron – 2.6
Integration for Billingo & WooCommerce: by PWS Online Kft.  – 3.3.8
Classic Editor: by WordPress Contributors – 1.6.2
Contact Form 7: by Takayuki Miyoshi – 5.6.2
Contact Form CFDB7: by Arshid – 1.2.6.4
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Email Encoder - Protect Email Addresses: by Ironikus – 2.1.3
GDPR Cookie Compliance: by Moove Agency – 4.8.11
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
LiteSpeed Cache: by LiteSpeed Technologies – 5.1
Barion Payment Gateway for WooCommerce: by Peter Szel  – 3.4.0
custom Extra: by Custom – 1.1.4
custom Portfolio: by Custom – 1.0.0
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 7.1.2.6
WooCommerce Stripe Gateway: by WooCommerce – 6.9.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.13
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
WooCommerce: by Automattic – 6.6.1 (update to version 7.3.0 is available)
WP Mail SMTP: by WPForms – 3.5.1
WP Migrate Lite: by Delicious Brains – 2.3.2
SEOPress: by SEOPress – 5.8.0.5
WPML String Translation: by OnTheGoSystems – 3.2.1

### Inactive Plugins (7) ###

Demo Import: by Custom – 2.2.3
Google Listings and Ads: by WooCommerce – 2.0.3
Jetpack: by Automattic – 11.2
Mailchimp for WooCommerce: by Mailchimp – 2.7.2
MailPoet 3 (New): by MailPoet – 3.94.0
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.8

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #6020103 - /my-account/
Terms and conditions: #6020112 - /tac/

### Theme ###

Name: custom-child
Version: 1.0.0
Author URL: http://localhost/
Child Theme: ✔
Parent Theme Name: custom
Parent Theme Version: 1.3.6
Parent Theme Author URL: http://localhost/
WooCommerce Support: ✔

### Templates ###

Overrides: custom/woocommerce/archive-product.php
custom/woocommerce/cart/cart-empty.php
custom/woocommerce/cart/cart-shipping.php
custom/woocommerce/cart/cart-totals.php
custom/woocommerce/cart/cart.php
custom/woocommerce/cart/cross-sells.php
custom/woocommerce/cart/mini-cart.php
custom/woocommerce/cart/proceed-to-checkout-button.php
custom-child/woocommerce/checkout/form-billing.php
custom-child/woocommerce/checkout/form-checkout.php
custom/woocommerce/checkout/form-coupon.php
custom-child/woocommerce/checkout/form-login.php
custom/woocommerce/checkout/form-pay.php
custom/woocommerce/checkout/form-shipping.php
custom/woocommerce/checkout/payment-method.php
custom/woocommerce/checkout/payment.php
custom/woocommerce/checkout/review-order.php
custom/woocommerce/checkout/terms.php
custom-child/woocommerce/checkout/thankyou.php
custom/woocommerce/content-product.php
custom/woocommerce/content-single-product.php
custom/woocommerce/content-widget-product.php
custom-child/woocommerce/emails/customer-completed-order.php
custom-child/woocommerce/emails/email-addresses.php
custom/woocommerce/global/breadcrumb.php
custom/woocommerce/global/form-login.php
custom/woocommerce/global/wrapper-end.php
custom/woocommerce/loop/add-to-cart.php
custom/woocommerce/loop/loop-end.php
custom/woocommerce/loop/loop-start.php
custom/woocommerce/loop/no-products-found.php
custom/woocommerce/loop/orderby.php
custom/woocommerce/loop/pagination.php
custom/woocommerce/loop/sale-flash.php
custom/woocommerce/myaccount/dashboard.php
custom/woocommerce/myaccount/downloads.php
custom/woocommerce/myaccount/form-login.php
custom/woocommerce/myaccount/form-lost-password.php
custom/woocommerce/myaccount/form-reset-password.php
custom/woocommerce/myaccount/my-account.php
custom/woocommerce/myaccount/my-address.php
custom/woocommerce/myaccount/my-orders.php
custom/woocommerce/myaccount/navigation.php
custom/woocommerce/myaccount/orders.php
custom/woocommerce/myaccount/payment-methods.php
custom/woocommerce/notices/error.php
custom/woocommerce/notices/notice.php
custom/woocommerce/notices/success.php
custom/woocommerce/order/order-again.php
custom/woocommerce/order/order-details-customer.php
custom/woocommerce/order/order-details-item.php
custom/woocommerce/order/order-details.php
custom/woocommerce/order/order-downloads.php
custom/woocommerce/product-searchform.php
custom/woocommerce/single-product/add-to-cart/external.php
custom/woocommerce/single-product/add-to-cart/grouped.php
custom/woocommerce/single-product/add-to-cart/simple.php
custom/woocommerce/single-product/add-to-cart/variable.php
custom/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
custom/woocommerce/single-product/meta.php
custom/woocommerce/single-product/price.php
custom/woocommerce/single-product/product-attributes.php
custom/woocommerce/single-product/product-image.php
custom/woocommerce/single-product/product-thumbnails.php
custom/woocommerce/single-product/rating.php
custom/woocommerce/single-product/related.php
custom/woocommerce/single-product/review-meta.php
custom/woocommerce/single-product/review-rating.php
custom/woocommerce/single-product/review.php
custom/woocommerce/single-product/sale-flash.php
custom/woocommerce/single-product/share.php
custom/woocommerce/single-product/short-description.php
custom/woocommerce/single-product/tabs/additional-information.php
custom/woocommerce/single-product/tabs/description.php
custom/woocommerce/single-product/tabs/tabs.php
custom/woocommerce/single-product/title.php
custom/woocommerce/single-product/up-sells.php
custom/woocommerce/single-product-reviews.php
custom/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2023-01-22 10:46:02 +00:00
Options: ✔
Notes: 118
Onboarding: completed

### Action Scheduler ###

Complete: 183
Oldest: 2023-01-14 07:57:13 +0000
Newest: 2023-01-22 07:52:59 +0000

Pending: 2
Oldest: 2023-01-22 12:38:19 +0000
Newest: 2023-01-23 21:41:03 +0000

### Status report information ###

Generated at: 2023-01-22 08:10:25 +00:00

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @martincpt,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin WooCommerce Multilingual & Multicurrency. 

Please contact the author of the plugin directly for further help.
