### ISSUE TITLE
[Enhancement]: wc_help_tip filter

### ISSUE THREAD

**Issue by hojtfredrik** [woothemes/woocommerce#36543]
### Describe the solution you'd like

I need to be able to intercept and prevent the standard tooltips and replace them with my own code. 
It would be nice to have a hook for this.

### Describe alternatives you've considered

Today I need to maintain my own version of the wc_core_functions

**Comment by vedanshujain** [comment]
Thanks for the report, we can add a filter in the `wc_help_tip` function; marking this low priority for now as compared to other high prior issue we have open in the repo. Just curious, can you explain more about the use case what are you changing these messages to?

**Comment by hojtfredrik** [comment]
Sure,
I create my own tooltip handler with a bit different behavior, where the
help text will be permanently displayed, hovering displaying a "more info"
where I add links to our online manual, where we will explain more how to
use some fields/data in the context of our service.

*Med vänliga hälsningar / Best regards,*

*Fredrik Beckman*





Den tis 24 jan. 2023 kl 12:21 skrev Vedanshu Jain ***@***.***
