### ISSUE TITLE
Styling conflict on form-checkout.php when using Bootstrap 5

### ISSUE THREAD

**Issue by Dymirt** [woothemes/woocommerce#36586]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using Bootstrap 5 there is conflict of classes name: Since class='col-1' is Bootstrap registrated class for styling.

### Expected behavior

shows full with form

### Actual behavior

since Bootstrap understand class 'col-1' and 'col-2' form looks like 1/12 of width and 2/12 of width.

### Steps to reproduce

1. Install bootstrap
2. go to checkout page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://martabanaszek.pl
Site address (URL): https://martabanaszek.pl
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.75.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.33-36-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Całkowity rozmiar bazy danych: 73.49MB
Rozmiar bazy danych: 57.06MB
Rozmiar indeksu bazy danych: 16.43MB
wp_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_order_itemmeta: Dane: 0.09MB + Indeks: 0.11MB + Silnik InnoDB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_actions: Dane: 2.02MB + Indeks: 1.31MB + Silnik InnoDB
wp_actionscheduler_claims: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_groups: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_logs: Dane: 1.02MB + Indeks: 0.48MB + Silnik InnoDB
wp_alm: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_comments: Dane: 0.08MB + Indeks: 0.09MB + Silnik InnoDB
wp_gs_logo_slider: Dane: 0.06MB + Indeks: 0.00MB + Silnik InnoDB
wp_linguise_urls: Dane: 1.52MB + Indeks: 0.53MB + Silnik InnoDB
wp_links: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_options: Dane: 19.08MB + Indeks: 3.03MB + Silnik InnoDB
wp_postmeta: Dane: 17.55MB + Indeks: 7.38MB + Silnik InnoDB
wp_posts: Dane: 12.42MB + Indeks: 1.19MB + Silnik InnoDB
wp_termmeta: Dane: 0.22MB + Indeks: 0.22MB + Silnik InnoDB
wp_terms: Dane: 0.13MB + Indeks: 0.14MB + Silnik InnoDB
wp_term_relationships: Dane: 1.42MB + Indeks: 0.33MB + Silnik InnoDB
wp_term_taxonomy: Dane: 0.14MB + Indeks: 0.16MB + Silnik InnoDB
wp_usermeta: Dane: 0.14MB + Indeks: 0.13MB + Silnik InnoDB
wp_users: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_admin_notes: Dane: 0.08MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_admin_note_actions: Dane: 0.05MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_category_lookup: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_customer_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_coupon_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_product_lookup: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_wc_order_stats: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_order_tax_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_product_attributes_lookup: Dane: 0.13MB + Indeks: 0.08MB + Silnik InnoDB
wp_wc_product_download_directories: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_product_meta_lookup: Dane: 0.25MB + Indeks: 0.44MB + Silnik InnoDB
wp_wc_rate_limits: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_reserved_stock: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_tax_rate_classes: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_tpay: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_tpay_clients: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wptodo: Dane: 0.00MB + Indeks: 0.00MB + Silnik MyISAM
wp_wptodo_comments: Dane: 0.00MB + Indeks: 0.00MB + Silnik MyISAM
wp_wptodo_email: Dane: 0.00MB + Indeks: 0.00MB + Silnik MyISAM

### Post Type Counts ###

attachment: 3660
blog: 12
custom_css: 1
customize_changeset: 15
gs-logo-slider: 12
landing: 1
logoshowcase: 1
nav_menu_item: 29
page: 36
polylang_mo: 1
portfolio: 37
post: 176
product: 332
product_variation: 1214
revision: 968
shop_coupon: 45
shop_order: 222
shop_order_refund: 4
size-chart: 11
sp_lc_shortcodes: 4
sp_logo_carousel: 26
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Polylang: przez WP SYNTEX – 3.3.1
All-in-One WP Migration: przez ServMask – 7.70
Contact Form 7: przez Takayuki Miyoshi – 5.7.2
Duplicate Page: przez mndpsingh287 – 4.5
Facebook for WooCommerce: przez Facebook – 3.0.8
Jetpack: przez Automattic – 11.7.1
Lightbox with PhotoSwipe: przez Arno Welzel – 5.0.20
Linguise: przez Linguise – 1.9.13
Logo Carousel Pro: przez ShapedPlugin – 3.6.0
UpdraftPlus - Kopia/przywracanie: przez UpdraftPlus.Com
DavidAnderson – 1.22.24

WC Variations Radio Buttons: przez 8manos – 2.0.5
InPost dla WooCommerce: przez Inspire Labs – 1.3.7
WooCommerce Google Analytics Integration: przez WooCommerce – 1.5.19
WooCommerce Price Based on Country: przez Oscar Gare – 3.0.0
Tpay WooCommerce payment module: przez Tpay – 2.9.6
WooCommerce: przez Automattic – 7.3.0
WordPress Importer: przez wordpressdotorg – 0.8
WPS Hide Login: przez WPServeur
NicolasKulka
wpformation – 1.9.6

### Inactive Plugins (13) ###

Advanced Cron Manager: przez BracketSpace – 2.5.0
Akismet Anti-Spam: przez Automattic – 5.0.2
Evernote Sync: przez Gaowei Tang – 2.0.6
Furgonetka.pl: przez Furgonetka.pl – 1.1.5
Hyyan WooCommerce Polylang Integration: przez Hyyan Abo Fakher – 1.5.0
Logo Carousel: przez ShapedPlugin – 3.4.17
Product Feed Manager for WooCommerce: przez RexTheme – 7.2.25
SumoMe: przez SumoMe – 1.31
SumUp Payment Gateway For WooCommerce: przez SumUp – 1.2
WooCommerce Stripe Gateway: przez WooCommerce – 7.0.2
WP-Quiz: przez Tomasz Smykowski – 1.0
WP Logo Showcase Responsive Slider and Carousel: przez WP OnlineSupport
Essential Plugin – 3.2.2

WP To Do: przez Delower – 1.2.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Strona sklepu: #8 - /sklep/
Koszyk: #9 - /koszyk/
Zamówienie: #10 - /zamowienie/
Moje konto: #11 - /moje-konto/
Regulamin: #2 - /regulamin/

### Theme ###

Name: MB2022mk2
Version: 1.1.9
Author URL: http://pawelwnuk.pl
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.2.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mb2022mk2/woocommerce/checkout/cart-errors.php
mb2022mk2/woocommerce/checkout/form-billing.php
mb2022mk2/woocommerce/checkout/form-checkout.php
mb2022mk2/woocommerce/checkout/form-coupon.php wersja 3.4.4 jest nieaktualna. Bazowa wersja to 7.0.1
mb2022mk2/woocommerce/checkout/form-login.php
mb2022mk2/woocommerce/checkout/form-pay.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 7.0.1
mb2022mk2/woocommerce/checkout/form-shipping.php
mb2022mk2/woocommerce/checkout/order-receipt.php
mb2022mk2/woocommerce/checkout/payment-method.php
mb2022mk2/woocommerce/checkout/payment.php wersja 3.5.3 jest nieaktualna. Bazowa wersja to 7.0.1
mb2022mk2/woocommerce/checkout/review-order.php wersja 3.8.0 jest nieaktualna. Bazowa wersja to 5.2.0
mb2022mk2/woocommerce/checkout/terms.php
mb2022mk2/woocommerce/checkout/thankyou.php
mb2022mk2/woocommerce/loop/loop-start.php
mb2022mk2/woocommerce/single-product/add-to-cart/variable.php wersja 3.4.1 jest nieaktualna. Bazowa wersja to 6.1.0
mb2022mk2/woocommerce/single-product/product-image.php

Outdated Templates: ❌
					
					
						Dowiedz się jak zaktualizować

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 79.184.239.106
Real external IP: 2a01:110f:420e:aa00:b003:c53d:2c0:35f
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 3.0.0
Base location: PL
Base currency: PLN
Price Based On: shipping
Shipping: ✔
Test mode: –
Test country: –
Load products price in background: ✔
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: excl

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-25 10:35:06 +01:00
Options: ✔
Notes: 78
Onboarding: completed

### Action Scheduler ###

Zakończ: 3 800
Oldest: 2022-12-24 17:54:57 +0100
Newest: 2023-01-24 16:47:17 +0100

Oczekujące: 2
Oldest: 2023-01-24 17:53:01 +0100
Newest: 2023-01-25 11:40:36 +0100

### Status report information ###

Generated at: 2023-01-24 17:14:58 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Dymirt,

Thanks for the report. I'm not sure in this case that there's much that we'll be able to do to resolve this conflict, as updating the class name would potentially affect others who are targeting that class in their layouts. I'm going to request developer feedback on this issue, in case they disagree or have other suggestions, but you may need to [override your templates](https://woocommerce.com/document/template-structure/) to not use the conflicting class-name if you'd like to use the default Bootstrap classnames without conflict.

**Comment by barryhughes** [comment]
It feels like this one is best resolved on a case-by-case basis, which will allow individual developers to decide which set of CSS rules takes precedence on any given page.
