### ISSUE TITLE
Woocommerce importer doesn't update all the provided products

### ISSUE THREAD

**Issue by gvwines** [woothemes/woocommerce#36618]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Woocommerce importer doesn't work properly.
If I try to update 1,929 products using a basic csv file, whose columns are just SKU and Stock, after running the importer I get the message

Import complete! 1,920 products updated.

9 products are skipped without a valid reasons.
Note that 1,929 products are all in the database with their unique sku.

Woocommerce Plugin Support replicated the issue and suggested to report a bug here on GitHub.
Here is the thread https://wordpress.org/support/topic/import-issue-19/

### Expected behavior

I expect 1,929 products to be updated, with the message

Import complete! 1,929 products updated.

### Actual behavior

I get only 1,920 products updated, with the message

Import complete! 1,920 products updated.

### Steps to reproduce

First set up a csv file as explained above, than follow usual import steps
1. Go to Products > All Products > Import
3. Uplad your csv file
4. Check the checkbox labeled Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped
5. Click on Continue
6. Check that Column names are associated with their related Product Fields 
7. Click on Run the importer
8. Wait until the message Your products are now being imported... disappears.
9. You will now see the message Import complete! 1,920 products updated. as screenshot below

![import-screenshot](https://user-images.githubusercontent.com/123632125/214817608-3ebd20ea-1b22-43a3-a9fb-f1c55eadda5c.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.grandivinialba.it
Site address (URL): https://staging.grandivinialba.it
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 128 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp321_
Dimensione totale database: 25.43MB
Dimensione dati database: 14.28MB
Dimensione indice database: 11.15MB
wp321_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gestp_ric: Dati: 0.33MB + indice: 0.27MB + motore InnoDB
gestp_ris: Dati: 0.33MB + indice: 0.28MB + motore InnoDB
wp321_actionscheduler_actions: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
wp321_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp321_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_options: Dati: 1.50MB + indice: 0.06MB + motore InnoDB
wp321_postmeta: Dati: 4.52MB + indice: 4.03MB + motore InnoDB
wp321_posts: Dati: 1.52MB + indice: 0.36MB + motore InnoDB
wp321_snippets: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wp321_termmeta: Dati: 0.06MB + indice: 0.06MB + motore InnoDB
wp321_terms: Dati: 0.08MB + indice: 0.09MB + motore InnoDB
wp321_term_relationships: Dati: 1.52MB + indice: 1.52MB + motore InnoDB
wp321_term_taxonomy: Dati: 0.08MB + indice: 0.06MB + motore InnoDB
wp321_tm_taskmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_tm_tasks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_trp_dictionary_it_it_en_us: Dati: 0.05MB + indice: 0.05MB + motore InnoDB
wp321_trp_gettext_en_us: Dati: 1.52MB + indice: 0.64MB + motore InnoDB
wp321_trp_gettext_it_it: Dati: 1.52MB + indice: 1.88MB + motore InnoDB
wp321_trp_gettext_original_meta: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_trp_gettext_original_strings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_trp_original_meta: Dati: 0.05MB + indice: 0.05MB + motore InnoDB
wp321_trp_original_strings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_wcpt_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_admin_notes: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp321_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_product_meta_lookup: Dati: 0.23MB + indice: 0.47MB + motore InnoDB
wp321_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 61
custom_css: 2
language_switcher: 4
nav_menu_item: 45
page: 49
post: 2
product: 1930
revision: 1
wc_product_table: 3
wp_block: 2
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0

### Inactive Plugins (9) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Aruba HiSpeed Cache: by Aruba.it – 1.2.3
Code Snippets: by Code Snippets Pro – 3.2.2
Custom Payment Gateways for WooCommerce: by Imaginate Solutions – 1.6.6
Enable Media Replace: by ShortPixel – 4.0.2
Flexible Shipping: by Octolize – 4.18.3
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.3.9.4
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.4.5

WooCommerce Product Table PRO: by WC Product Table – 2.7.2

### Must Use Plugins (1) ###

Aruba WordPress checker: by http://www.aruba.it – 15

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Carrello: #6 - /cart/
Pagamento: #7 - /checkout/
Il mio account: #8 - /my-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-18 12:41:03 +01:00
Options: ✔
Notes: 25
Onboarding: completed

### Action Scheduler ###

In attesa: 1
Oldest: 2023-01-21 19:38:08 +0100
Newest: 2023-01-21 19:38:08 +0100

### Status report information ###

Generated at: 2023-01-21 20:37:19 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @gvwines,

Thank you for raising this issue. 

Looking at the forum discussion you linked, I can see that the issue has been reproduced using [this CSV file](https://www.grandivinialba.it/wp-content/uploads/AGG_GIACENZE_WOO_1929_KO.csv) (with "Magazzino" meaning stock in Italian). 

Apart from the potential bug in the importer, a useful enhancement here could also be listing any items that were skipped during the import process and, ideally, a reason for skipping them. 

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by gvwines** [comment]
Hi @lsinger,
thank you for your reply and for reading the forum discussion.

With reference to the skipped items, let me quote my explanation I provided on the support forum:

> So we have built a very simple csv file with just two columns, sku and Magazzino (stock in italian).
> When we try to update our catalog with a 1930 rows file (1929 products plus 1 header row), everything works without error messages or warnings, but only 1920 items are updated. **The last 9 items are skipped** without a valid reason. Of course the products with their skus are all in the database, in fact **if we put at the top of the csv file the 9 products that are skipped, they are updated and other 9 last items are skipped**.

So I don't think this is a "item code based" issue, since as I wrote the items are skipped randomly, if we consider their skus, whereas there is a logic based on their position: the items that are skipped are always the last 9 in the csv file.
I hope I have explained this behaviour in an understandable way.

Please  note also this detail from my statement of the issue

> But **if we add just 1 line** (with an additional item to update) to our csv file, **everything works fine and all the 1930 items are loaded and updated**.

That's why I think it's a treaky and sneaky issue. I hope you can reproduce it on your servers without any problems.

**Comment by coreymckrill** [comment]
I was also able to replicate this using the import files in the forum thread. It seems to happen when the file contains any number of products between 1921 and 1929, but not any other number. E.g. 1919 does not cause it to only import 1910 products. The only thing I can think of is that this has something to do with binary, i.e. 1920 is a multiple of 640. But that seems like a stretch. An interesting puzzle, but given that (so far anyway) this only seems to affect imports with a very small range of product counts, it seems like an edge case.

> a useful enhancement here could also be listing any items that were skipped during the import process and, ideally, a reason for skipping them.

Agreed. It would be nice if the importer showed skipped items and the reason.

**Comment by gvwines** [comment]
I looked into the files related to the importer and finally I think I found the bug.

IMHO this line in abstract-wc-product-importer.php should be fixed some way

`return absint( min( NumberUtil::round( ( $this->file_position / $size ) * 100 ), 100 ) );`

because it rounds the result so that in some few cases the last characters of the input stream are skipped.
If my debugging is correct, the importer fails every time get_percent_complete() is called when the importer has processed at least 99,5% of the input stream but not actually 100%. This finally makes the last call to read_file() function in class-wc-product-csv-importer.php not to be executed and the file not fully read. Nothing to do with items skipped at a record level and unfortunately not just an edge case.
I modified it like this

`$int_percent = absint( min( NumberUtil::round( ( $this->file_position / $size ) * 100 ), 100 ) );`
`if ( $int_percent == 100 && $this->file_position < $size ) {`
`	$int_percent = 99;`
`}`
`return $int_percent;`

It is not a fine or clean solution, but it works for me and it complies with woocommerce logic for all other cases.
Please have a look and find a better fix for the next woocommerce update, if you think my suggestion is correct.

**Comment by gvwines** [comment]
Hi @lsinger and @coreymckrill,
A week ago I added a comment. Can you take a look at it and let me know if my solution is correct? I am using my patch in a production environment waiting for woocommerce to release the update.

Thank you in advance

**Comment by coreymckrill** [comment]
@gvwines Sorry, I have been away for the past week. I'll take a closer look at this tomorrow.

**Comment by coreymckrill** [comment]
@gvwines Good catch with the `get_percent_complete` method! That is indeed the cause of the issue. I have created a pull request here to fix it: https://github.com/woocommerce/woocommerce/pull/36839

Hopefully this will make it into the next release.

**Comment by gvwines** [comment]
Great job! Thank you very much
