### ISSUE TITLE
Empty value for "excluded_product_ids" in post meta return a fatal error on coupons listing

### ISSUE THREAD

**Issue by MKlblangenois** [woothemes/woocommerce#36616]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we creating a coupon using `wp_insert_post` function with value `array()` for `exclude_product_ids`, this register an empty value in DB like this:

<img width="391" alt="Capture d’écran 2023-01-26 à 10 46 51" src="https://user-images.githubusercontent.com/42929225/214805537-fb372a36-18c6-49ca-ba0f-31c035bc5484.png">

In coupon listing, we got a fatal error when we try to display coupon.

### Expected behavior

Get the list of all coupon without fatal error

### Actual behavior

Got a fatal error on listing:

```
2023-01-26T09:32:06+00:00 CRITICAL Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:135
Stack trace:
#0 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php(135): explode(',', Array)
#1 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read(Object(WC_Coupon))
#2 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(134): WC_Data_Store->read(Object(WC_Coupon))
#3 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(122): WC_Coupon->read_object_from_database()
#4 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-coupons.php(102): WC_Coupon->__construct(7345)
#5 /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(254): WC_Admin_List_Table_Coupons->prepare_row_data(7345)
#6 /Users/loganblangenois/Local Sites/emassage/app/public/wp-includes/class-wp-hook.php(308): WC_Admin_List_Table->render_columns('coupon_code', 7345)
#7 /Users/loganblangenois/Local Sites/emassage/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#8 /Users/loganblangenois/Local Sites/emassage/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-posts-list-table.php(1363): do_action('manage_shop_cou...', 'coupon_code', 7345)
#10 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-list-table.php(1532): WP_Posts_List_Table->column_default(Object(WP_Post), 'coupon_code')
#11 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-posts-list-table.php(1397): WP_List_Table->single_row_columns(Object(WP_Post))
#12 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-posts-list-table.php(807): WP_Posts_List_Table->single_row(Object(WP_Post), 0)
#13 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-posts-list-table.php(783): WP_Posts_List_Table->_display_rows(Array, 0)
#14 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-list-table.php(1444): WP_Posts_List_Table->display_rows()
#15 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/includes/class-wp-list-table.php(1371): WP_List_Table->display_rows_or_placeholder()
#16 /Users/loganblangenois/Local Sites/emassage/app/public/wp-admin/edit.php(487): WP_List_Table->display()
#17 {main}
  thrown dans /Users/loganblangenois/Local Sites/emassage/app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php à la ligne 135

```

### Steps to reproduce

1. Create new coupon using `wp_insert_post`
```php
<?php
$expiration = strtotime('+90 days');
$expiration = date("Y-m-d", $expiration);

$data = array(
	'discount_type' => 'percent',
	'coupon_amount' => 25, // value
	'individual_use' => 'no',
	'product_ids' => $productsToCoupon,
	'exclude_product_ids' => array(),
	'usage_limit' => '1',
	'usage_limit_per_user' => '1',
	'limit_usage_to_x_items' => '',
	'usage_count' => '1',
	'expiry_date' => $expiration, // YYYY-MM-DD
	'free_shipping' => 'no',
	'product_categories' => array(),
	'exclude_product_categories' => array(),
	'exclude_sale_items' => 'no',
	'minimum_amount' => NULL,
	'maximum_amount' => NULL,
	'customer_email' => array($email)
);

$explode = explode("@", $email);
array_pop($explode);

$codeTitle = "FID-" . date("ymds") . "-" . strtoupper(join('@', $explode));

// Save the coupon in the database
$coupon = array(
	'post_title' => $codeTitle,
	'post_content' => '',
	'post_status' => 'publish',
	'post_author' => 1,
	'post_type' => 'shop_coupon'
);

$new_coupon_id = wp_insert_post($coupon);

// Write the $data values into postmeta table
foreach ($data as $key => $value) {
	update_post_meta($new_coupon_id, $key, $value);
}
```

2. Go to coupon listing

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://emassage.local
Site address (URL): https://emassage.local
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1 000 Mo
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Taille totale de la base de données: 81.12MB
Taille de la base de données: 55.56MB
Taille de l’index: 25.56MB
wp_woocommerce_sessions: Données : 0.17MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.20MB + Index : 0.08MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 2.52MB + Index : 1.92MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.33MB + Index : 0.47MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.20MB + Index : 0.20MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 1.52MB + Index : 0.88MB + Moteur InnoDB
wp_db7_forms: Données : 0.19MB + Index : 0.00MB + Moteur InnoDB
wp_itsec_bans: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_itsec_dashboard_events: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_itsec_distributed_storage: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_itsec_fingerprints: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_itsec_geolocation_cache: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_itsec_lockouts: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_itsec_logs: Données : 1.52MB + Index : 0.11MB + Moteur InnoDB
wp_itsec_mutexes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_itsec_opaque_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_itsec_temp: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_itsec_user_groups: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_ld_notifications_delayed_emails: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_category: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_form: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_learndash_pro_quiz_lock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_master: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_prerequisite: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_question: Données : 1.52MB + Index : 0.03MB + Moteur InnoDB
wp_learndash_pro_quiz_statistic: Données : 0.23MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_statistic_ref: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_learndash_pro_quiz_template: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_pro_quiz_toplist: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_learndash_user_activity: Données : 0.52MB + Index : 1.66MB + Moteur InnoDB
wp_learndash_user_activity_meta: Données : 1.52MB + Index : 1.92MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mollie_pending_payment: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_options: Données : 9.22MB + Index : 0.16MB + Moteur InnoDB
wp_postmeta: Données : 9.52MB + Index : 11.03MB + Moteur InnoDB
wp_posts: Données : 21.52MB + Index : 1.06MB + Moteur InnoDB
wp_sib_model_contact: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_sib_model_country: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_sib_model_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_sib_model_users: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_term_relationships: Données : 0.08MB + Index : 0.05MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 2.52MB + Index : 4.03MB + Moteur InnoDB
wp_users: Données : 0.16MB + Index : 0.14MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.08MB + Index : 0.00MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.08MB + Index : 0.06MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.09MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.09MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.06MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_zapier_history: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpr_rocket_cache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wpr_rucss_used_css: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_yoast_indexable: Données : 0.30MB + Index : 0.22MB + Moteur InnoDB
wp_yoast_indexable_hierarchy: Données : 0.05MB + Index : 0.05MB + Moteur InnoDB
wp_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_yoast_seo_links: Données : 0.08MB + Index : 0.03MB + Moteur InnoDB
wp_yoast_seo_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

acf-field: 35
acf-field-group: 6
attachment: 195
custom_css: 1
itsec-dash-card: 12
itsec-dashboard: 2
nav_menu_item: 21
oembed_cache: 122
page: 23
polylang_mo: 3
post: 9
product: 36
revision: 2676
sfwd-certificates: 18
sfwd-courses: 25
sfwd-lessons: 201
sfwd-question: 434
sfwd-quiz: 18
shop_coupon: 402
shop_order: 558
shop_subscription: 551
user_request: 4
wp_block: 6
wp_global_styles: 1
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Polylang Pro: par WP SYNTEX – 3.3.1
JSON Basic Authentication: par WordPress API Team – 0.1
ACF to REST API: par Aires Gonçalves – 3.3.3
Advanced Custom Fields PRO: par Delicious Brains – 5.12.2
Advanced Rich Text Tools for Gutenberg: par Ella Van Durpe – 1.2.0
Astra Pro: par Brainstorm Force – 3.0.1
Astra Widgets: par Brainstorm Force – 1.2.12
iThemes Security: par iThemes – 8.1.4
Booster Plus for WooCommerce: par Pluggabl LLC – 5.6.3
Contact Form 7: par Takayuki Miyoshi – 5.7.2
Contact Form CFDB7: par Arshid – 1.2.6.5
GTM4WP: par Thomas Geiger – 1.15.2
If Menu - Visibility control for menus: par Par couches – 0.16.3
Imsanity: par Exactly WWW – 2.8.2
Instant Images: par Darren Cooney – 5.0.1
LearnDash LMS - Notifications: par LearnDash – 1.5.4
LearnDash LMS - WooCommerce Integration: par LearnDash – 1.9.6
Loco Translate: par Tim Whitlock – 2.6.3
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: par Sendinblue – 3.1.56
Media File Renamer: par Jordy Meow – 5.5.2
Mollie Payments for WooCommerce: par Mollie – 7.3.4
Duplicateur de post: par Metaphor Creations – 2.28
Post Types Order: par Nsp Code – 1.9.9.2
LMS LearnDash: par LearnDash – 3.3.0.3
SVG Support: par Benbodhi – 2.5.5
Spectra: par Brainstorm Force – 2.3.0
User Role Editor: par Vladimir Garagulya – 4.63.2
User Switching: par John Blackbourn & les contributeurs – 1.7.0
WooCommerce EU VAT Number: par WooCommerce – 2.3.25
Sendinblue - WooCommerce Email Marketing: par Sendinblue – 3.0.3
Abonnements WooCommerce: par WooCommerce – 3.0.12
WooCommerce: par Automattic – 7.3.0
WordPress Importer: par wordpressdotorg – 0.8
Yoast SEO: par L’équipe Yoast – 19.14
WP Migrate: par WP Engine – 2.6.0
WP Rocket: par WP Media – 3.12.4

### Inactive Plugins (2) ###

Disable Emails: par WebAware – 1.8.1
Maintenance: par WebFactory Ltd – 4.06

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

LearnDash LMS Multisite: par LearnDash – 1.0.0
WP Migrate Compatibility: par Delicious Brains – 1.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: abonnement variable (abonnement-variable)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la boutique: #1118 - /boutique/
Panier: #1119 - /panier/
Commander: #1120 - /formation-massage-en-ligne/
Mon compte: #1121 - /mon-compte/
Conditions générales de vente et d’utilisation: #1607 - /conditions-generales-de-vente/

### Theme ###

Name: E-Massage
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.0.2
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: emassage/woocommerce/cart/cart-empty.php version 3.5.0 est obsolète. La version du noyau est 7.0.1
emassage/woocommerce/cart/cart-totals.php
emassage/woocommerce/cart/cart.php version 3.8.0 est obsolète. La version du noyau est 7.0.1
emassage/woocommerce/checkout/review-order.php version 3.8.0 est obsolète. La version du noyau est 5.2.0
emassage/woocommerce/checkout/thankyou.php
emassage/woocommerce/myaccount/dashboard.php
emassage/woocommerce/myaccount/form-edit-account.php version 3.5.0 est obsolète. La version du noyau est 7.0.1
emassage/woocommerce/myaccount/form-lost-password.php version 3.5.2 est obsolète. La version du noyau est 7.0.1
emassage/woocommerce/order/order-details-customer.php version 3.4.4 est obsolète. La version du noyau est 5.6.0
emassage/woocommerce/order/order-details-item.php version 3.7.0 est obsolète. La version du noyau est 5.2.0
emassage/woocommerce/order/order-details.php
emassage/single-product.php version - est obsolète. La version du noyau est 1.6.4

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Abonnements ###

WCS_DEBUG: ✔ Non
Subscriptions Mode: ✔ En direct
Subscriptions Live URL: https://emassage.local
Subscription Statuses: wc-active: 278
wc-expired: 182
wc-pending: 1
wc-cancelled: 90

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Oui
Cache Update Failures: ✔ 0 échecs

### Configuration de la boutique ###

Country / State: Belgique

### Abonnements par passerelle de paiement ###

Mollie - Bancontact: wc-expired: 58
wc-cancelled: 13
wc-active: 65

Mollie - Carte de crédit: wc-expired: 82
wc-cancelled: 57
wc-active: 134
wc-pending: 1

Mollie - PayPal: wc-expired: 42
wc-cancelled: 15
wc-active: 69

Mollie - SOFORT Banking: wc-cancelled: 5
wc-active: 1

### Prise en charge de la passerelle de paiement ###

Mollie - Carte de crédit: products
refunds
subscriptions
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Mollie - PayPal: products
refunds

Mollie - SOFORT Banking: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Mollie - Bancontact: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-26 11:19:23 +01:00
Options: ✔
Notes: 108
Onboarding: completed

### Action Scheduler ###

Complete: 731
Oldest: 2022-12-26 11:03:32 +0100
Newest: 2023-01-26 09:50:58 +0100

Failed: 1
Oldest: 2023-01-20 15:51:21 +0100
Newest: 2023-01-20 15:51:21 +0100

Pending: 279
Oldest: 2023-01-26 12:26:47 +0100
Newest: 2024-01-25 20:40:24 +0100

### Status report information ###

Generated at: 2023-01-26 10:59:53 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by MKlblangenois** [comment]
This update inside WooCommerce plugin solve the issue:

```diff
# ./includes/data-stores/class-wc-coupon-data-store-cpt.php:136

- 'excluded_product_ids'        => array_filter((array) explode(',', get_post_meta($coupon_id, 'exclude_product_ids', true))),
+ 'excluded_product_ids'        => get_post_meta($coupon_id, 'exclude_product_ids', true) ? array_filter((array) explode(',', get_post_meta($coupon_id, 'exclude_product_ids', true))) : array(),
```

**Comment by lsinger** [comment]
Hello @MKlblangenois,

Please do not use `wp_insert_post` to create a new coupon -- instead use the `WC_Coupon` class. It's [documented here](https://woocommerce.github.io/code-reference/classes/WC-Coupon.html). 

Example: 

```php
$coupon = new WC_Coupon();

$coupon->set_free_shipping( false );
$coupon->set_discount_type( 'percent' ); // one from wc_get_coupon_types()
$coupon->set_amount( 25 );
// ... use other set_ methods as desired

$coupon->save();
```

I'll close this issue for now. Please feel free to reopen if you see the above behavior using this method as well.
