### ISSUE TITLE
Update DEVELOPMENT.md to include tests setup

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36622]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

[`DEVELOPMENT.md`](https://github.com/woocommerce/woocommerce/blob/trunk/DEVELOPMENT.md) has all the useful information for setting up the Monorepo.

If your environment doesn't have [unit tests setup](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#initial-setup), then commands like `pnpm run test` fail without a useful error message.

- [ ] Update `DEVELOPMENT.md` with a link
- [ ] Determine if a check in Core is possible/feasible and add a pre-test check, including a useful error message if the check fails

**Comment by rrennick** [comment]
While following the unit tests setup instruction I got the following error:

```
# tests/bin/install.sh wc_tests root password 127.0.0.1
It looks as if svn is not installed. Please ensure it is installed and on the path.
```

Can we add installing svn to the setup instructions with the updates here?

**Comment by psealock** [comment]
This will be solved by the work in https://github.com/woocommerce/woocommerce/issues/32436, so closing
