### ISSUE TITLE
When variations are auto-created, product shows as both saved and unsaved

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#36628]
## To reproduce

With experimental new product management experience enabled:

1. Products > Add New
2. Add Options
3. Variations are auto-created
4. Note that
    - Header shows the product as both saved and unsaved
    - Product does not show up in All Products
    - If you leave the screen, you lose all your work -- it is gone
    - Slug is "used" though, so a new product with the same slug cannot be created

![Image](https://user-images.githubusercontent.com/2098816/214915852-4c367eb2-7638-4fcb-af6c-8ec58bea22f1.png)

**Comment by jarekmorawski** [comment]
No longer relevant to the new block-based design.
