### ISSUE TITLE
Post Release Automation: Ensure versions and stable tag copied to `trunk`

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36634]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The Post Release job should create PR to `trunk` to copy all version numbers from a release branch.

This includes Stable tag and other version updates such as "Requires at least". A PR that we can review will be created.

Note: With the possibility of overlapping releases, it's of high importance that this task not go backwards. In other words the action should fail or die if the stable tag is attempted to be decreased on trunk.

**Comment by ObliviousHarmony** [comment]
This was completed here: https://github.com/woocommerce/woorelease/pull/431
