### ISSUE TITLE
Auto-creating variations for a new product with the same SKU as an existing product results in spinning progress and uncaught error

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#36635]
## To reproduce

With the new product editor enabled:

1. Product > Add New
2. Enter a name that will result in the same default SKU as an existing product.
3. Add options.
4. When variations are auto-generated, note the never-ending spinner and uncaught error in the console:

![Image](https://user-images.githubusercontent.com/2098816/214929693-7e8bf298-13ce-43dd-a486-ef8819649301.png)

![Image](https://user-images.githubusercontent.com/2098816/214929749-f6ad1cee-4095-4bc6-a3e8-f98d1e976c03.png)

**Comment by octaedro** [comment]
I wasn't able to reproduce this error. I'll close the issue.
