### ISSUE TITLE
Estou com problemas na ativação do plug-in

### ISSUE THREAD

**Issue by AmmLobo** [woothemes/woocommerce#36647]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions`

### Expected behavior

problema na ativação do plug-in woocommerce

### Actual behavior

problema na ativação do plug-in woocommerce

### Steps to reproduce

Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions`
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions`

### WordPress Environment

Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='woocommerce_cleanup_draft_orders' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1
Erro no banco de dados do WordPress: [Table 'lobofo12_wp460.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @AmmLobo,

Please note that we reply to bug reports in English language only. 

Please fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
