### ISSUE TITLE
Disable `Used for variations` box

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#36657]
In the old experience, when creating a variable product.
The `Used for variations` box should be checked and disabled when:

- the product doesn't have any variations AND
- the product doesn't have any attributes with the `Used for variations` box checked AND
- the user navigates to the `Variations` tab

<img width="888" alt="image" src="https://user-images.githubusercontent.com/79307566/205013424-5011b44e-0c20-4f3b-91ce-380d7dfa3a82.png">

From issue [#35115](https://github.com/woocommerce/woocommerce/issues/35115). More context [here](https://github.com/woocommerce/woocommerce/issues/35115#issuecomment-1403910659).

## UPDATE
Maybe we should add another prop [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/class-wc-admin-assets.php#L357-L423) to know when we should [disable the checkbox](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js). 

**Acceptance criteria:**

- [ ] Disable `Used for variations` box.

**Comment by octaedro** [comment]
Hey @jarekmorawski,

I have a question related to this issue. The instructions say that the `Used for variations` box will be checked and disabled when (among other things):

> the user navigates to the `Variations` tab

Just to confirm, in order for the `Used for variations` box to be checked and disabled as per the instructions, the user needs to first navigate to the `Variations` tab, and then go to the `Attributes` tab. Is that correct?

**Comment by jarekmorawski** [comment]
Hiya! There might be a mistake in the original AC. The box should only be disabled when the user navigates to the `Variations` tab.

When there are **no attributes in the system**, the product type is `Variable`, and the user navigates to `Variations`, we should show the form with the box checked and disabled. When the user fills out the form and clicks `Create variations`, we add an attribute under `Attributes` and generate the variations.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/79307566/221879190-413a52fc-338f-4228-a54c-376875d57715.png">

When there are **no attributes in the system**, the product type is `Variable`, and the user navigates to `Attributes`, we should show the form with the box checked but enabled so it can be unchecked if needed.

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/79307566/221879501-46c499eb-90f3-492c-bd43-842239aa0253.png">

If the product type isn't `Variable`, we shouldn't show the box at all. Let me know if that helps!
