### ISSUE TITLE
[Enhancement]: WC_Admin_Notices bad performance impact

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#36652]
### Describe the solution you'd like

We have 42k products in our store and we noticed slow sql caused by following call chain:

```
WC_Admin_Notices::init() -> WC_Install::is_new_install() -> wp_count_posts( 'product' )
```

This affects all admin/ajax requests.

**Comment by barryhughes** [comment]
Thanks! We'll aim to review the pull request shortly.

**Comment by barryhughes** [comment]
I'm not sure what went wrong with the original PR, but I've created a new one (taking a slightly different approach).

Please note that this represents an incremental step forward, but doesn't solve the problem of `wp_count_posts( 'product' )` calls being triggered on each admin page completely, as this still seems to happen (at least in some cases, or until specific criteria is satisfied) via `Admin\Features\OnboardingTasks`.
