### ISSUE TITLE
Tax rate import - Items failed due to trailing space reported as success

### ISSUE THREAD

**Issue by duncanpt** [woothemes/woocommerce#36666]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When importing new tax rates from a CSV file, although I got a "success, 250 imported" message, most rates were NOT imported as there was a trailing space after the country code. It took me a few minutes of mystification to spot this.

Could you either amend the success criteria or remove the space and accept the records during import?

Note that I picked up the ISO country list from both the IBAN organisation and Wikipedia, checked them against each other before pasting into Excel to save as CSV with the other columns added. I admit that now I know about this, I'd be alert to trailing spaces. But the point is that WC seemed to think it had imported items that did not then show on its list of rates.

### Expected behavior

If a rate item isn't not properly imported to the list, I would expect an error message, such as "250 rows read, 3 imported successfully, 247 had format errors." Preferably adding "Errors were found in the County Code column" (or whichever column(s) were the problem).

### Actual behavior

See bug description. Failed rows do not appear in the tax rate list.

### Steps to reproduce

Got to tax rates
Import CSV file
Look at result.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://childtraumatherapycentre.com
Site address (URL): https://childtraumatherapycentre.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.27
PHP Post Max Size: 516 MB
PHP Time Limit: 180
PHP Max Input Vars: 1500
cURL Version: 7.87.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: sxA_
Total Database Size: 63.25MB
Database Data Size: 45.85MB
Database Index Size: 17.40MB
sxA_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
sxA_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sxA_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
sxA_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.75MB + Engine InnoDB
sxA_woocommerce_tax_rates: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
sxA_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_actionscheduler_actions: Data: 0.30MB + Index: 0.44MB + Engine InnoDB
sxA_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_actionscheduler_logs: Data: 0.30MB + Index: 0.20MB + Engine InnoDB
sxA_amelia_appointments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_coupons_to_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_coupons_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_customer_bookings: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_customer_bookings_to_events_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_customer_bookings_to_extras: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_custom_fields_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_custom_fields_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_custom_fields_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_events_periods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_events_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_events_to_providers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_extras: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_galleries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_locations_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_notifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_notifications_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_notifications_sms_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_packages_customers_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_packages_services_to_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_packages_services_to_providers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_packages_to_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_packages_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_providers_to_daysoff: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_google_calendar: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_outlook_calendar: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_periods_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_specialdays: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_specialdays_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_specialdays_periods_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_timeouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_to_weekdays: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_providers_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_amelia_services_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_amelia_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_bp_activity: Data: 0.06MB + Index: 0.16MB + Engine InnoDB
sxA_bp_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
sxA_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
sxA_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_bp_optouts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sxA_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
sxA_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_comments: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
sxA_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
sxA_e_notes_users_relations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_e_submissions: Data: 0.05MB + Index: 0.27MB + Engine InnoDB
sxA_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
sxA_e_submissions_values: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
sxA_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_mec_dates: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
sxA_mec_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sxA_mec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_mec_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_mlw_qm_audit_trail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_mlw_questions: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sxA_mlw_question_terms: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sxA_mlw_quizzes: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
sxA_mlw_quiz_theme_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_mlw_results: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
sxA_mlw_themes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_options: Data: 8.02MB + Index: 0.17MB + Engine InnoDB
sxA_postmeta: Data: 8.03MB + Index: 6.80MB + Engine InnoDB
sxA_posts: Data: 5.02MB + Index: 0.58MB + Engine InnoDB
sxA_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sxA_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
sxA_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_usermeta: Data: 2.45MB + Index: 2.92MB + Engine InnoDB
sxA_users: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
sxA_usin_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_usin_user_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_wcepp_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
sxA_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sxA_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wc_appointments_availability: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
sxA_wc_appointment_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
sxA_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
sxA_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
sxA_wc_order_tax_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
sxA_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
sxA_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sxA_wfconfig: Data: 1.31MB + Index: 0.00MB + Engine InnoDB
sxA_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wffilemods: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
sxA_wfhits: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
sxA_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sxA_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
sxA_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sxA_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sxA_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sxA_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sxA_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sxA_wfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
sxA_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 125
avada_portfolio: 12
bp-email: 38
custom_css: 1
elementor_library: 9
fusion_element: 11
fusion_form: 5
fusion_tb_section: 1
mec_calendars: 15
mec-events: 6
nav_menu_item: 31
page: 99
post: 26
product: 74
qmn_log: 1
qsm_quiz: 59
revision: 420
seedprod: 3
shop_coupon: 42
shop_order: 1486
shop_order_refund: 25
slide: 1
tribe_events: 1
usin_note: 5
wc_appointment: 946
woocustomemails: 1
wp_global_styles: 1
wpcf7_contact_form: 6
wpephpcompat_jobs: 37

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Bluehost: by Bluehost – 2.12.17
Contact Form 7: by Takayuki Miyoshi – 5.7.3
Creative Mail by Newfold Digital: by Newfold Digital – 1.6.7
Elementor Pro: by Elementor.com – 3.10.2
Elementor: by Elementor.com – 3.10.1
PHP Compatibility Checker: by WP Engine – 1.5.2
QSM - Reporting & Analysis: by QSM Team – 1.4.4
QSM - Certificate: by QSM Team – 1.0.13
Quiz And Survey Master: by ExpressTech – 8.0.9
The Plus Addons for Elementor: by POSIMYTH – 5.1.13
Users Insights: by Pexeto – 4.0.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.3
WooCommerce Appointments: by BookingWP – 4.14.7
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.8
WooCommerce Custom Payment Gateway Pro: by WPRuby – 2.2.1
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Shipping & Tax: by WooCommerce – 2.2.1
WooCommerce Xero Integration: by WooCommerce – 1.7.55
WooCommerce: by Automattic – 7.3.0
WP Crontrol: by John Blackbourn & contributors – 1.15.1

### Inactive Plugins (20) ###

AI Powered Marketing: by Kliken – 1.1.0
Akismet Anti-Spam: by Automattic – 5.0.2
Amelia: by TMS – 3.1.2
Avada Builder: by ThemeFusion – 3.3.1
Avada Core: by ThemeFusion – 5.3.1
Avada Custom Branding: by ThemeFusion – 1.2
BuddyPress: by The BuddyPress Community – 11.0.0
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.7
Duplicator: by Snap Creek – 1.5.2
Facebook for WooCommerce: by Facebook – 3.0.8
Jetpack: by Automattic – 11.7.1
Mailchimp for WooCommerce: by Mailchimp – 2.7.6
Modern Events Calendar: by Webnus – 5.17.1
NitroPack: by NitroPack LLC – 1.5.19
Smush: by WPMU DEV – 3.12.4
The Events Calendar: by The Events Calendar – 6.0.8
Wordfence Security: by Wordfence – 7.8.2
WPCal.io: by Revmakx – 0.9.5.4
WP Super Cache: by Automattic – 1.9.2
WP Test Email: by Boopathi Rajan – 1.1.6

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Page Cache: by Mike Hansen – 2.2
p3-profiler.php: by  –
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: appointment (appointment)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #12 - /shop/
Basket: #13 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #15 - /my-account/
Terms and conditions: ❌ Page ID is set
but the page does not exist

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-29 13:24:53 +00:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Complete: 802
Oldest: 2022-12-29 11:57:31 +0000
Newest: 2023-01-28 13:08:09 +0000

Failed: 11
Oldest: 2022-03-03 11:01:09 +0000
Newest: 2022-03-08 13:30:42 +0000

Pending: 299
Oldest: 2023-01-28 13:42:31 +0000
Newest: 2023-11-11 10:30:00 +0000

### Status report information ###

Generated at: 2023-01-28 13:42:56 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Thanks @duncanpt,

Could you provide a CSV file that shows that behavior for you so we can attempt to reproduce it?

**Comment by duncanpt** [comment]
After I'd found a fix, I cleaned up the csv file and completed the import.
I've attached a recreation which should show the same behaviour.

**Comment by lsinger** [comment]
Hello @duncanpt,

Do you have a CSV file that triggers the error that you can share? I cannot reproduce this issue just with the "Import CSV file" instruction. Thanks!
