### ISSUE TITLE
[Enhancement]: Add page controls at bottom of tax rates list

### ISSUE THREAD

**Issue by duncanpt** [woothemes/woocommerce#36664]
### Describe the solution you'd like

In WC Settings, Taxes, On the Standard Tax Rates list, it would be helpful to have the page forward/back controls at the bottom as well as at the top of screen. By the time you scroll to the bottom, if you have a lot of rates, the top has disappeared.

### Additional context

Background is that because I don't trust our website to properly enforce a country choice, I have the full list of 250 ISO countries in our list set explicitly rather than relying on the asterisk catchall for those we don't trade with.

**Comment by Konamiman** [comment]
Note to anyone willing to implement this: pagination is added in [html-settings-tax.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/settings/views/html-settings-tax.php), in an element with id `tmpl-wc-tax-table-pagination`.

**Comment by TarekNabil** [comment]
Would you assign this issue to me on Contributor Day?
