### ISSUE TITLE
[HPOS] Add compatibility for unit tests in WC_Admin tests with HPOS

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#36678]
Currently, some unit test in class `WC_Tests_Admin_Report`, `WC_Admin_Tests_API_Reports_Import`, `WC_Admin_Tests_Reports_Customer` and `WC_Tests_Report_sales_by_date` fails when run in HPOS context. This issue scopes fixing unit tests (or core code, as appropriate) so that they work with HPOS.

Please fork from #36650 for workflow to run tests in HPOS context.

Towards #36376

**Comment by Konamiman** [comment]
As part of working on this the `WC_Admin_Report` class will need changes as it's directly referencing the posts table in quite a few places.

**Comment by peterfabian** [comment]
If these are legacy reports, then we can probably just skip this.

**Comment by vedanshujain** [comment]
Fixed via #36650
