### ISSUE TITLE
Woocommerce and admin bar zero counter for comments

### ISSUE THREAD

**Issue by arashmesf** [woothemes/woocommerce#36670]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

hello 
recently after updating woocommerce i have noticed that the counter below the pending comments in the adminbar shows zero, even there are new comments pending approval. this issue only resolves after i disable woocommerce. i have tried downgrading woocommerce but it doesnt help at all.
please help me out, thanks

### Expected behavior

comments counter to show the new comments

### Actual behavior

but after activating woocommerce it shows number zero

### Steps to reproduce

![4y73y73](https://user-images.githubusercontent.com/64352091/215332331-de2aff21-7b63-4bad-bd52-f8d0bb866f0d.jpg)

### WordPress Environment

sdf

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by arashmesf** [comment]
*update*

after deleting this line :

// Count comments.
	add_filter( 'wp_count_comments', array( __CLASS__, 'wp_count_comments' ), 10, 2 );

in this file:

wp-content/plugins/woocommerce/includes/class-wc-comments.php

the counter works fine and displays correct unapproved comments.

**Comment by lsinger** [comment]
Hello @arashmesf,

Thank you for submitting this issue. However, we can’t reproduce it using the steps you provided. Please provide clear steps to follow on a fresh WooCommerce installation.

**Comment by arashmesf** [comment]
thank you for your response,
i understand but could you tell me what does the deleted line would do?
i have removed it and havent yet seen a problem.
thanks in advance,

**Comment by lsinger** [comment]
Hello @arashmesf,

GitHub should be treated as a place to report WooCommerce bugs only. For discussions such as those, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

I will close this issue now. Please feel free to create a new issue if you'd like to provide reproduction instructions as mentioned above.
