### ISSUE TITLE
after update of woocommerce I'm having problem with translation.

### ISSUE THREAD

**Issue by stl249** [woothemes/woocommerce#36672]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using Locotranslate for translating my website in to my language, and everything was okay. Till I update my woocommerce. Lable of cart now appears in english as "Your cart", and when i hover over cart it shows also in english "No products in the cart."
Also in my account section all the tabs translating correctly except tab "Addresses" its also showing in english.

By the way, when i reload the homepage, "Your cart" label appears in translated language as it supposed to be, but only for a second. Then it changes to "Your cart" in english.
I've checked all translation files in loco translate, all appears to be correct. As i describe above, it comes to show translated string for a second, then it changes in to the english language.

### Expected behavior

![Screenshot 2023-01-30 at 03 52 56](https://user-images.githubusercontent.com/36600821/215365280-cc32d662-a8a3-44fa-bc7d-96515f314cbe.png)
here i catch screenshot of the moment when it shows translated version for a second

### Actual behavior

![Screenshot 2023-01-30 at 03 52 47](https://user-images.githubusercontent.com/36600821/215365361-de34afda-290e-433d-9103-6a27f7a80be4.png)
and here when it loads the page, it shows in english

### Steps to reproduce

[here is the screen record link ](https://ru.files.fm/u/znuv3xpas)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://pixart.az
Site address (URL): https://pixart.az
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.37-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wpgr_
Total Database Size: 25.31MB
Database Data Size: 20.48MB
Database Index Size: 4.83MB
wpgr_woocommerce_sessions: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_actionscheduler_actions: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wpgr_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_actionscheduler_logs: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wpgr_aioseo_cache: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wpgr_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_aioseo_posts: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
wpgr_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpgr_css_js_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_defender_audit_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpgr_defender_email_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_defender_lockout: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_defender_lockout_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_defender_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_defender_scan_item: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wpgr_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_instock_email_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_loginizer_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_automations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_automation_runs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_automation_run_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_automation_triggers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_automation_versions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpgr_mailpoet_scheduled_tasks: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wpgr_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpgr_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wpgr_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_nbdesigner_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_mydesigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_options: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_user_designs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbdesigner_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_nbt_order_upload: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_nbt_users_social: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_netbase_invoice_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_netbase_invoice_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpgr_options: Data: 9.48MB + Index: 0.27MB + Engine InnoDB
wpgr_postmeta: Data: 2.52MB + Index: 0.59MB + Engine InnoDB
wpgr_posts: Data: 1.52MB + Index: 0.09MB + Engine InnoDB
wpgr_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_slides: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_say_what_strings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgr_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_ta_link_clicks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_ta_link_clicks_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wpgr_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpgr_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpgr_wc_order_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpgr_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpgr_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wplsl_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wplsl_configs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wplsl_countries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wplsl_markers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wplsl_storelogos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpgr_wplsl_stores: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_wplsl_stores_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpgr_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_yoast_indexable: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wpgr_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpgr_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpgr_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpgr_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 258
custom_css: 1
custom-css-js: 1
customize_changeset: 8
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 19
nbt_faq: 1
page: 46
polylang_mo: 4
popup: 1
popup_theme: 14
post: 7
product: 36
product_variation: 45
revision: 104
shop_order: 1
wp_global_styles: 1
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.10
All in One SEO: by All in One SEO Team – 4.2.9
Classic Widgets: by WordPress Contributors – 0.3
Əlaqə Forması 7: by Takayuki Miyoshi – 5.7.3
WooCommerce Coupon Generator: by Jeroen Sormani – 1.2.0
CSS JS Manager, Async JavaScript, Defer Render Blocking CSS: by Pi Websolution – 2.4.49.2
Simple Custom CSS and JS: by SilkyPress.com – 3.42
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 7.12.1
Site Kit by Google: by Google – 1.92.0
Head, Footer and Post Injections: by Stefano Lissa – 3.2.5
Jetpack: by Automattic – 11.7.1
WPBakery Səhifə Qurucusu: by Michael M - WPBakery.com – 6.7.0
Kapital Bank payment: by Kapital Bank – 1.0.5
Loco Translate: by Tim Whitlock – 2.6.3
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.0
MailPoet: by MailPoet – 4.5.2
Max Mega Menyu: by megamenu.com – 3.1
Netbase Elementləri: by NBTeam – 1.2.3
Netbase Framework: by NBTeam – 1.4.5
WooCommerce PDF Invoices Pro: by Truemart – 1.0.5
NetBase Solutions: by Netbase-Team – 1.9.7
Image optimization service by Optimole: by Optimole – 3.5.5
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.19.0
Really Simple SSL: by Really Simple Plugins – 6.1.1
Slider Revolution: by ThemePunch – 6.4.2
String Locator: by InstaWP – 2.6.1
NBDesigner: by NetbaseTeam – 2.8.3
WooCommerce: by Avtomatik – 7.3.0
Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.8.9
WP Fayl meneceri: by mndpsingh287 – 7.1.7
WP Rocket: by WP Media – 3.12.4
WPForms Lite: by WPForms – 1.7.9.1
YITH WooCommerce Compare: by YITH – 2.22.0
YITH WooCommerce Quick View: by YITH – 1.23.0
YITH WooCommerce Wishlist: by YITH – 3.17.0

### Inactive Plugins (4) ###

Netbase Dashboard: by Netbase Team – 1.2.5
WooCommerce Frontend Dashboard Manager: by NetBase Team – 1.2.7
WP Rollback: by GiveWP.com – 1.7.3
Yoast SEO: by Team Yoast – 20.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: AZN (₼)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #92 - /shop/
Cart: #93 - /cart-2/
Checkout: #94 - /checkout-2/
My account: #95 - /my-account/
Terms and conditions: #439 - /ictimai-oferta/

### Theme ###

Name: Printcart Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Printcart
Parent Theme Version: 5.6.3
Parent Theme Author URL: https://cmsmart.net
WooCommerce Support: ✔

### Templates ###

Overrides: printcart/woocommerce/archive-product.php
printcart/woocommerce/cart/cart-totals.php
printcart/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.0.1
printcart/woocommerce/cart/cross-sells.php
printcart/woocommerce/cart/mini-cart.php
printcart/woocommerce/cart/proceed-to-checkout-button.php version 2.4.0 is out of date. The core version is 7.0.1
printcart/woocommerce/checkout/form-checkout.php
printcart/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
printcart/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 7.0.1
printcart/woocommerce/content-product.php
printcart/woocommerce/content-single-product.php
printcart/woocommerce/content-widget-product.php
printcart/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.2.0
printcart/woocommerce/global/wrapper-end.php
printcart/woocommerce/global/wrapper-start.php
printcart/woocommerce/loop/add-to-cart.php
printcart/woocommerce/loop/loop-end.php
printcart/woocommerce/loop/loop-start.php
printcart/woocommerce/loop/pagination.php
printcart/woocommerce/loop/sale-flash.php
printcart/woocommerce/myaccount/form-login.php version 4.1.0 is out of date. The core version is 7.0.1
printcart/woocommerce/single-product/add-to-cart/variable.php
printcart/woocommerce/single-product/meta.php
printcart/woocommerce/single-product/product-image.php
printcart/woocommerce/single-product/product-thumbnails.php
printcart/woocommerce/single-product/rating.php
printcart/woocommerce/single-product/related.php
printcart/woocommerce/single-product/sale-flash.php
printcart/woocommerce/single-product/title.php
printcart/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-30 10:12:56 +04:00
Options: ✔
Notes: 76
Onboarding: completed

### Action Scheduler ###

Complete: 532
Oldest: 2022-12-30 13:55:19 +0000
Newest: 2023-01-30 00:03:05 +0000

Failed: 98
Oldest: 2023-01-25 09:52:52 +0000
Newest: 2023-01-29 23:30:01 +0000

Pending: 7
Oldest: 2023-01-30 01:21:09 +0000
Newest: 2023-02-03 10:28:05 +0000

### Status report information ###

Generated at: 2023-01-30 04:40:03 +04:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @stl249,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin Loco Translate. 

Please contact the author of the plugin directly for further help.
