### ISSUE TITLE
Display bug when editing a WooCommerce product

### ISSUE THREAD

**Issue by peneloperageau** [woothemes/woocommerce#36683]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Under "Add a new product", I have all the buttons on the same line. This line is bigger than the screen and prevent my client to click on buttons like "edit status"

![woocommerce-bug](https://user-images.githubusercontent.com/54311773/215441371-e4af6cc6-dcf8-4a86-be06-dfbbd6bc2eb0.png)

### Expected behavior

Buttons should insert a line break.

### Actual behavior

Buttons are on one line only.

### Steps to reproduce

-

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.lestherapiesdesophie.com
Site address (URL): https://www.lestherapiesdesophie.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.2
PHP Version: 7.4.33
PHP Post Max Size: 2 Go
PHP Time Limit: 180
PHP Max Input Vars: 6000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.39-google-log
Max Upload Size: 2 Go
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Taille totale de la base de données: 23.06MB
Taille de la base de données: 18.94MB
Taille de l’index: 4.12MB
wp_woocommerce_sessions: Données : 1.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.08MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.17MB + Index : 0.20MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.14MB + Index : 0.09MB + Moteur InnoDB
wp_bookly_appointments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_categories: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_customers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_customer_appointments: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_bookly_email_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_gift_cards: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_gift_card_services: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_gift_card_staff: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_holidays: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_mailing_campaigns: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_mailing_lists: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_mailing_list_recipients: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_mailing_queue: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_news: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_notifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_orders: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_payments: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_schedule_item_breaks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_sent_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_series: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_services: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_sessions: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_shop: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_staff: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_staff_categories: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_staff_preference_orders: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_staff_schedule_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_bookly_staff_services: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bookly_stats: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_bookly_sub_services: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_bw_pricing_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_cmplz_cookiebanners: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_cmplz_cookies: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_cmplz_services: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_commentmeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.09MB + Index : 0.09MB + Moteur InnoDB
wp_edd_customermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_edd_customers: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_edd_notifications: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_gla_budget_recommendations: Données : 0.22MB + Index : 0.14MB + Moteur InnoDB
wp_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_gla_shipping_rates: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_mapping_to_external_entities: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_templates: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_scheduled_tasks: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_subscribers: Données : 0.02MB + Index : 0.13MB + Moteur InnoDB
wp_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 3.02MB + Index : 0.14MB + Moteur InnoDB
wp_postmeta: Données : 1.52MB + Index : 0.27MB + Moteur InnoDB
wp_posts: Données : 3.45MB + Index : 0.16MB + Moteur InnoDB
wp_strong_views: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.11MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wcpdf_invoice_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wpmailsmtp_debug_events: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpmailsmtp_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpml_mails: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_yoast_indexable: Données : 1.47MB + Index : 0.23MB + Moteur InnoDB
wp_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_yoast_seo_links: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB

### Post Type Counts ###

attachment: 423
customize_changeset: 1
download: 1
mailpoet_page: 1
nav_menu_item: 32
page: 26
post: 42
product: 70
product_variation: 57
revision: 411
shop_order: 78
shop_order_refund: 20
subscribe-form: 1
wp_global_styles: 1
wpcf7_contact_form: 1
wpm-testimonial: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Antispam Bee: par pluginkollektiv – 2.11.1
BlossomThemes Email Newsletter: par blossomthemes – 2.2.1
BlossomThemes Social Feed: par blossomthemes – 2.0.4
BlossomThemes Toolkit: par blossomthemes – 2.2.4
Bookly Pro (Add-on): par Bookly – 5.8
Bookly Stripe (Add-on): par Bookly – 4.0
Bookly: par Bookly – 21.4
Boxtal Connect: par API Boxtal – 1.2.14
Complianz | GDPR/CCPA Cookie Consent: par Really Simple Plugins – 6.4.0
Contact Form 7: par Takayuki Miyoshi – 5.7.3
Flexible Checkout Fields: par WP Desk – 3.5.4
Flexible Shipping: par Octolize – 4.18.5
Loco Translate: par Tim Whitlock – 2.6.3
Cache serveur: par rtCamp – 2.2.2
Query Monitor: par John Blackbourn – 3.11.1
Strong Testimonials: par WPChill – 3.1.0
Trustpilot-reviews: par Trustpilot – 2.5.914
WooCommerce Stripe Gateway: par WooCommerce – 7.0.2
WooCommerce: par Automattic – 7.3.0
Yoast SEO: par L’équipe Yoast – 20.0
WP Mail Logging: par SendLayer – 1.10.5

### Inactive Plugins (2) ###

PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.3.1
Social Media and Share Icons (Ultimate Social Media): par UltimatelySocial – 2.8.0

### Must Use Plugins (1) ###

manager-plugin.php: par  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la boutique: #570 - /boutique/
Panier: #571 - /panier/
Commander: #572 - /commander/
Mon compte: ❌ La visibilité de la page doit être publique
Conditions générales de vente et d’utilisation: #1305 - /conditions-generales-de-vente-boutique/

### Theme ###

Name: Mon thème enfant
Version: 0.9.6
Author URL: 
Child Theme: ✔
Parent Theme Name: Seva Lite
Parent Theme Version: 1.1.1
Parent Theme Author URL: https://blossomthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: seva-lite-child/woocommerce/checkout/form-shipping.php
seva-lite-child/woocommerce/checkout/thankyou.php
seva-lite-child/woocommerce/emails/customer-completed-order.php
seva-lite-child/woocommerce/emails/customer-processing-order.php
seva-lite-child/woocommerce/emails/customer-refunded-order.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-31 06:33:07 +01:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Terminé: 86
Oldest: 2022-12-30 15:00:34 +0100
Newest: 2023-01-30 10:28:26 +0100

En attente: 1
Oldest: 2023-01-30 16:50:15 +0100
Newest: 2023-01-30 16:50:15 +0100

### Status report information ###

Generated at: 2023-01-30 10:42:46 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @peneloperageau,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin Bookly. 

Please contact the author of the plugin directly for further help.
