### ISSUE TITLE
 [Product Extensibility] Move Variations -> General tab content to slot fill components

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#36695]
Variant products (created through options tab on parent products) have a differing set of fields on the "General" tab within the product. These have no yet been converted to slot fill components to make them extensible. 

Similar to what is done in this PR: https://github.com/woocommerce/woocommerce/pull/36368 we want to move the variation -> general tab sections and fields out of the product form and have it added by a Slot fill instead.

The sections and fields should be added with staggered `order` values (ie 1, 3, 5) as was done with the other sections.

**Acceptance criteria**

- [ ] Variation -> General Slot and sections/fields should be re-implemented and be extensible via Slot fill.

**Comment by louwie17** [comment]
Closing as we are not using slot fills for tabs in the product block editor.
