### ISSUE TITLE
E2E: `Run smoke tests against pull request` workflow to use Playwright E2E and API tests.

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#36696]
### Describe the solution you'd like

`Run smoke tests against pull request` workflow still uses the Puppeteer tests. Need to update the `.github/workflows/pr-smoke-test.yml` workflow to use the Playwright ones.

**Comment by adimoldovan** [comment]
Closing as obsolete. pr-smoke-test.yml no longer exists, all Playwright tests are now running in a different CI setup.
