### ISSUE TITLE
[E2E]: Fix the reporting on Run daily tests in an environment with COT enabled 

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#36697]
### Describe the solution you'd like

Currently, the `publish-test-reports` job in `.github/workflows/cot-build-and-e2e-tests-daily.yml` is failing. This task will fix it.

**Comment by adimoldovan** [comment]
cot-build-and-e2e-tests-daily.yml no longer exists. COT tests are integrated in other CI jobs.
