### ISSUE TITLE
E2E: Use `waitUntil` instead of `waitForLoadState` in `page.goto()`

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#36698]
In our E2E tests, there are `page.goto()`'s that use `waitForLoadState` as an option.

<img width="448" alt="QsaNwwGWlg" src="https://user-images.githubusercontent.com/4509348/215694445-b1101f05-fe73-4ccc-b117-c13ffdcb9fae.png">

We must change them to `waitUntil` because that's the valid option according to the [Playwright docs](https://playwright.dev/docs/api/class-page#page-goto-option-wait-until).

**Comment by ravinderk** [comment]
@rodelgc 🤚 I would like to work on this

**Comment by rodelgc** [comment]
> @rodelgc 🤚 I would like to work on this

That's great @ravinderk 🙌 
Sure! I'll update the issue description to clarify that you'll be contributing to it. And let us know here if you got any questions 🥂

**Comment by nigeljamesstevenson** [comment]
Hi folks, not sure this issue should be closed- I have added a comment to the resolving [PR](https://github.com/woocommerce/woocommerce/pull/37831#issuecomment-1515512452) - If I have missed something then let me know 😊

**Comment by nigeljamesstevenson** [comment]
Closed based on @lanej0 comment in related [PR](https://github.com/woocommerce/woocommerce/pull/37831#issuecomment-1515512452)
