### ISSUE TITLE
[Product Extensibility] Move Options tab content to slot fill components

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#36694]
Similar to what is done in this PR: https://github.com/woocommerce/woocommerce/pull/36368 we want to move the options tab sections and fields out of the product form and have it added by a Slot fill instead.

The section slot should be added within the tab slot [here](https://github.com/woocommerce/woocommerce/blob/acdec3ad6c2678fd2b1bf97833c85025a564d888/plugins/woocommerce-admin/client/products/fills/product-form-fills.tsx#L110), with the fields added with staggered `order` values as was done with the other sections.

**Acceptance criteria**

- [ ] Options Slot and sections/fields should be reimplemented and be extensible via Slot fill.

**Comment by louwie17** [comment]
Closing as we are not using slot fills for tabs anymore in the product block editor.
