### ISSUE TITLE
E2E: Investigate and fix new causes of flakiness based on historical results in "Smoke test daily"  workflow

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#36709]
### Describe the solution you'd like

The _Smoke test daily_  workflow has been running for quite a while now, and we're seeing new causes of flakiness by looking at its historical results. This task will aim to address these new sources of flakiness.

**Comment by lanej0** [comment]
Going to call this one resolved for now.  I believe that since we moved to `wp-env` any flakiness in this run should be the same as on PR runs.
