### ISSUE TITLE
Move CES-related components and hooks to packages

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36722]
CES-related components and hooks should be moved to packages.

**Acceptance criteria**

Move the following to the `@woocommerce/customer-effort-score` package:

* [x] `useCustomerEffortScoreExitPageTracker` 
* [x] `ALLOW_TRACKING_OPTION_NAME`
* ~[ ] `CES_STORE_KEY`~ (removing from this issue as it there is no need to move it right now)

Move the following to the `@woocommerce/product-editor` package:

* [ ] `ProductMVPFeedbackModal`
* [ ] `useProductMVPCESFooter`
* [ ] `ProductMVPCESFooter`
* [ ] `ProductMVPFeedbackModalContainer`
* [ ] `NEW_PRODUCT_MANAGEMENT`

**Comment by mattsherman** [comment]
Based on pcQJnU-1jo-p2 I have updated the AC.

**Comment by mattsherman** [comment]
Split out some additional required package reorganization to: https://github.com/woocommerce/woocommerce/issues/37247
