### ISSUE TITLE
Move fills to product editor package

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36728]
All components under `plugins/woocommerce-admin/client/products/fills` should be moved to the `@woocommerce/product-editor` package for reuse.  The new folder name for these fills be `plugins` to more closely align with Gutenberg's folder naming.

**Comment by nathanss** [comment]
We should probably delete the fills that are not being used anymore instead of moving them.

**Comment by retrofox** [comment]
Let's close it for now. We can re-open if we consider it appropriate.
