### ISSUE TITLE
Create a @woocommerce/admin-layout package

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36721]
The header slots (`WooHeaderItem` and `WooHeaderPageTitle`) and footer slots (`WooFooterItem`) should be moved to a new package, `@woocommerce/admin-layout` so that they can be used across packages and within 3rd party plugins.

Eventually, it would be good to move other header and footer components into this package, but for now we can begin with just moving the slots so they can be filled in the product editor.

**Acceptance Criteria**
* [ ] A new package is created with the name `@woocommerce/admin-layout`
* [ ] `WooHeaderItem` is exposed via this package
* [ ] `WooHeaderNavigationItem` is exposed via this package
* [ ] `WooHeaderPageTitle` is exposed via this package
* [ ] `WooFooterItem` is exposed via this package

**Comment by mattsherman** [comment]
@joshuatf Taking this over, as I don't think you are actively working on this right now and I "need" it for some other work I'm doing!

Based on discussion in pcQJnU-1jo-p2, naming the package `@woocommerce/admin-layout` and also including `WooFooterItem`.
