### ISSUE TITLE
Move hooks to product editor package

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36725]
The hooks under `plugins/woocommerce-admin/client/products/hooks` should be moved to the `@woocommerce/product-editor` package for reuse.

After moving the hooks we'll need to hook up the components in the client products pages to the new hooks location.

**Acceptance criteria**

* [ ] All product hooks under `plugins/woocommerce-admin/client/products/hooks` should be moved to `@woocommerce/product-editor`
* [x] The `useProductHelper` hook should also be moved to the product editor package

**Comment by nathanss** [comment]
@joshuatf Is this still needed? It seems to be outdated.

**Comment by retrofox** [comment]
Let's close it for now. We can re-open if we consider it appropriate.
