### ISSUE TITLE
Move layout, section, and tour components to product editor package

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36727]
All components under `plugins/woocommerce-admin/client/products/layout`, `plugins/woocommerce-admin/client/products/sections`, and `plugins/woocommerce-admin/client/products/tour` should be moved to the `@woocommerce/product-editor` package for reuse.

All of these components will live under the a `components/` folder inside of `@woocommerce/product-editor`.

**Comment by nathanss** [comment]
Whoever picks this needs to analyze if each component should be moved to the new package or deleted, if it won't be used anymore.

**Comment by retrofox** [comment]
Let's close it for now. We can re-open if we consider it appropriate.
