### ISSUE TITLE
Move admin settings to settings package

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36724]
Currently, the `getAdminSetting` as well as some constants live under `client/utils`.   These can probably be safely moved to `@woocommerce/settings` so that they can be reused across other packages.

This is needed for the new product editing experience that's being moved into its own package.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/utils/admin-settings.js

**Acceptance criteria**

* [ ] `getAdminSetting` should be exposed in a package
* [ ] `setAdminSetting` should be exposed in a package
* [ ] All exposed constants, such as `ADMIN_URL`, `COUNTRIES`, etc. should be available in this package

**Comment by nathanss** [comment]
@joshuatf Do we still need this? It seems we're using `import { getSetting } from '@woocommerce/settings'; ` on some places. Is that a different thing?

**Comment by retrofox** [comment]
Let's close it for now. We can re-open if we consider it appropriate.
