### ISSUE TITLE
Possible filter name collision?

### ISSUE THREAD

**Issue by mikepollitt** [woothemes/woocommerce#36737]
Hi, thanks for WooCommerce, it's great!

I built some custom reports leveraging this filter:

https://github.com/woocommerce/woocommerce/blob/d0a2b582fe2da5cf628ace4f516eb7b18240372b/plugins/woocommerce/includes/admin/class-wc-admin-reports.php#L143

But they now seem to be broken, because there's another apply_filters call with the same filter name here:

https://github.com/woocommerce/woocommerce/blob/d0a2b582fe2da5cf628ace4f516eb7b18240372b/plugins/woocommerce/src/Admin/API/Reports/Controller.php#L154

and it uses a completely different array format. I mean, I know I can code around it by checking for the array format I'm expecting, but I just thought you ought to know.

Cheers,
-- Mike

**Comment by tomalec** [comment]
Hi @mikepollitt :)
Thank you for opening the issue.

I made a PR to prevent the Reports page from throwing an error. (Analytics pages already handle non-compliant entries silently)

This solves the problem on the WooCommerce end, but still leaves the problem on the extension level, as you will not know whether your callback was called by Reports or Analytics code. The cleanest solution would be to have distinct names in the first place, but changing that would break the backward compatibility.

Plus, most importantly, the Reports pages have been deprecated for years now. We are planning to start removing the related code. 

Technically, we could also add another parameter to the filter to help filter users distinguish the cases. But then, once we remove the Reports, we'll still have that param hanging there for no reason. Therefore, I'd leave the colliding names as they are, with a recommendation to migrate to Analytics :) Use the `woocommerce_admin_reports` to return `[[slug, description],...]` format. 
But for now, account for the fact that some non-migrated extensions can keep adding their legacy report entries there anyway.

**Comment by tomalec** [comment]
To make sure your filter callback code runs for the legacy reports you can check if you're on the WC admin screen with  `if( is_admin() )`, for the Analytics Controller, you may check is there is a REST request being processed with `if( wp_is_serving_rest_request() )`, like:

```php
// Legacy reports
add_filter(
	'woocommerce_admin_reports',
	function( $reports ) {
		if ( is_admin() ) {
			$reports['automatewoo'] = array(
				'title'   => 'AutomateWoo',
				'reports' => array(
					'runs_by_date' => array(
						'title'       => 'Workflow Runs',
						'description' => 'foo',
						'function'    => 'automatewoo_reports_get_runs_by_date',
					),
					'conversions' => array(
						'title'       => 'Conversions',
						'description' => 'bar',
						'hide_title'  => true,
					),
				),
			);
		}

		return $reports;
	}
);

// Analytics
add_filter(
	'woocommerce_admin_reports',
	function( $reports ) {
		if ( wp_is_serving_rest_request() ) {
			$reports[] = array(
				'slug' => 'aw-workflows',
				'description' => 'AutomateWoo Workflows',
				'url' => '/analytics/aw-workflows',
				'path' => '/automatewoo/v1/workflows',
			);
		}

		return $reports;
	}
);
```
