### ISSUE TITLE
Looking for Zelle payment gateway plugin for WooCommerce stores

### ISSUE THREAD

**Issue by harap** [woothemes/woocommerce#36733]
### Describe the solution you'd like

I searched the web and found nothing for Zelle payment plugin. The plugin need to be able to connect with Zelle payment gateway or bank for WooCommerce ecommcerce shopping cart payment solution like Paypal, Square...

Hope this plugin can be allowed and developed by someone expert. Please advise how much to develop this app.

Thanks in advance!

**Comment by lsinger** [comment]
Hello @harap,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs and enhancements only. 

You are proposing to develop an additional plugin. There are many developers and agencies available for hire for such an endeavor — [the Woo Experts marketplace](https://partners.woocommerce.com/English/marketplace/) for example might be a good way to start looking for such support.

**Comment by chiflyer** [comment]
Why is this closed if it is an enhancement request?  Seems very odd.  Good luck Woocommerce, this doesn't look good for you.
