### ISSUE TITLE
[Enhancement]: Out of stock products are set to not sync when ( Hide out of stock items from the catalog ) is enabled in woocommerce using  the Plugin facebook for Woocommerce

### ISSUE THREAD

**Issue by Harvito87** [woothemes/woocommerce#36738]
### Describe the solution you'd like

The **default behavior** for **products Facebook sync** is:
When are set to **in stock**: Sync and show in catalog
When are set to **out stock**: Sync and show in catalog

**_IMPORTANT_** The **behavior changes** for **products Facebook sync** when ( **Hide out of stock items from the catalog is enabled in woocommerce settings** ):

When are set to **in stock**: Sync and show in catalog
When are set to **out stock**: No sync

Facebook for woocommerce should include a control behavior for this situation, many people facing the same isue due to this. A lot of people use the hide out of stock products for woocommerce and dont want to show out of stock products in facebook catalog.

You can create a dropdown menu under Marketing - Facebook - Product sync
You can call this Instock behavior / out of stock behavior and let us choose which option we want when a product is out of stock. ( Remember when the option  ( **Hide out of stock items from the catalog is enabled in woocommerce settings**  is selected it force to not sync only.

Options to choose for the suggested tool will be: 
1-Default
2-Sync and show in catalog
3-Sync and hide in catalog
4- Not sync

In my personal case, Hide out of stock items from the catalog is enabled in woocommerce and i would like out of stock products goes to automatically hide and sync for facebook sync option.

### Describe alternatives you've considered

An alternative solution will be lettting us bulk select out of stock and choose between the 3 facebook sync options:
Sync and show in catalog
Sync and hide in catalog
Not sync

At this moment you can only  
Include in facebook sync
Exclude in facebook sync

### Additional context

Suggested tool to implement
I couldnt upload the image here is it
https://imgur.com/GcmKukA

**Comment by lsinger** [comment]
Hello @Harvito87,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs and enhancements only. 

Your proposal pertains to the Facebook for WooCommerce plugin, which is available [on the WooCommerce Marketplace here](https://woocommerce.com/products/facebook/). 

Please use the Feature Request function on that page to submit your request.
