### ISSUE TITLE
The Leaderboards in the Analytics > Dashboard report don't seem to be taking the correct currency formatting

### ISSUE THREAD

**Issue by daigo75** [woothemes/woocommerce#36748]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Notes**
1. This is a duplicate of the issue that [I already reported on the 17th September 2020 in the WooCommerce Admin issue tracker](https://github.com/woocommerce/woocommerce-admin/issues/5154). That issue was apparently ignored and it became stale, twice, and twice it was closed automatically. However, the bug is still there.
2. I left the checkbox "I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active" unchecked, because the currency filter comes from a plugin that I developed. Still, the issue is in the WooCommerce Admin, it seems to be a cosmetic issue of price formatting.

**Description**
I'm using a filter, written following your guidelines, to alter the currency formatting arguments depending on the currency selected on the reports. This ensures that amounts are formatted correctly on most reports, as well as most of the dashboard. However, the Leaderboards section doesn't seem to be taking the formatting arguments into account and always used the USD parameters (incidentally, USD is not even the shop's base currency).

**Screenshots**
1. Dashboard, amounts in the leaderboards are formatted incorrectly: https://prnt.sc/uitqwv
4. Orders report, correct: https://prnt.sc/uitp41
5. Products report, correct: https://prnt.sc/uitpib

### Expected behavior

The Leaderboards components should format the values using the selected currency, like all other components do.

### Actual behavior

The Leaderboards components format the values using the shop's base currency, regardless of the selected currency.

### Steps to reproduce

1. Implement a currency filter like the one described in your documentation (see [Extending WC-Admin Reports]
2. https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/)).
3. Go to the Dashboard report.
4. Select a currency.
5. The currency in the dashboard reflects the selected one, while the Leaderboard shows amounts formatted as the shop's base currency.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress_wc80
Site address (URL): http://localhost/wordpress_wc80
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.2
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.1q PHP/8.0.22
PHP Version: 8.0.22
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 52.46MB
Database Data Size: 28.54MB
Database Index Size: 23.92MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.27MB + Index: 0.36MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.44MB + Index: 1.17MB + Engine InnoDB
wp_postmeta: Data: 4.52MB + Index: 6.55MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wss_sell_messages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wss_service_notifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
def_reg_fields: 10
enr_subsc_plan: 1
nav_menu_item: 14
page: 36
post: 5
postman_sent_mail: 12
product: 84
product_variation: 166
revision: 61
shop_coupon: 11
shop_order: 291
shop_order_placehold: 3
shop_order_refund: 3
shop_subscription: 2
shopping-cart: 2
super_form: 1
user_request: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Loco Translate: by Tim Whitlock – 2.6.3
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.0.230202
Aelia Currency Switcher for WooCommerce: by Aelia – 4.15.0.220103
WooCommerce: by Automattic – 7.4.0-beta.2

### Inactive Plugins (15) ###
Post SMTP: by Post SMTP – 2.3.2
WooCommerce Beta Tester: by WooCommerce – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: 
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child
Version: 1.0.0.180829
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.3 – 4.2.0 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-04 11:51:20 +01:00
Options: ✔
Notes: 112
Onboarding: completed

### Action Scheduler ###

Complete: 127
Oldest: 2023-01-27 17:36:58 +0000
Newest: 2023-02-03 12:41:41 +0000

Failed: 27
Oldest: 2021-12-15 13:13:11 +0000
Newest: 2023-02-03 12:07:15 +0000

Pending: 11
Oldest: 2023-02-03 13:00:49 +0000
Newest: 2023-02-22 14:07:49 +0000

### Status report information ###

Generated at: 2023-02-03 13:58:55 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @daigo75,

Thank you for submitting this issue. To ensure we can properly reproduce it, would you mind sharing the filter you developed (or a modified / simplified version of it)?

**Comment by daigo75** [comment]
Unfortunately, unlike the "legacy" reports, extending the analytics reports to add a dropdown currency selector requires a ton of code (10X more code, more or less, compared to the old reports), which, in my case, is a combination of PHP, TypeScript and JavaScript (vs simple PHP for the legacy reports). Due to that, I can't extract it as a "simple" filter, because it's all but simple.

If you need a copy of the plugin I developed, I can forward it to you on Slack. Alternatively, someone else commented on the issue I reported originally, almost a year later. They indicate that the bug can be reproduced with the WooCommerce Payments plugin as well (see https://github.com/woocommerce/woocommerce-admin/issues/5154#issuecomment-887571939), but I haven't tested that myself.

**Comment by eason9487** [comment]
A simpler way to reproduce this issue:

1. Set up a store currency other than `NZD`, e.g. "Japanese yen (¥) — JPY"
2. Add the following PHP code snippet:
   ```php
   add_action( 'admin_enqueue_scripts', function () {
   	wp_add_inline_script( 'wp-hooks', <<<EOD
   	wp.hooks.addFilter( 'woocommerce_admin_report_currency', 'dev-blog-example', function() {
   		return {
   			code: "NZD",
   			decimalSeparator: ".",
   			precision: 2,
   			priceFormat: "%1\$s %2\$s",
   			symbol: "\$NZ",
   			symbolPosition: "left",
   			thousandSeparator: ",",
   		};
   	} );
   	EOD );
   } );
   ```
3. Go to **Analytics > Overview**

![1](https://github.com/woocommerce/woocommerce/assets/17420811/60adc750-4924-41b1-8501-5b50778e74a4)
