### ISSUE TITLE
put date_on_sale_from via api products does not enable dates in woocommerce editor product

### ISSUE THREAD

**Issue by emulsion-io** [woothemes/woocommerce#36751]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I put product via API with :

`date_on_sale_from `
`date_on_sale_to`

When I get the product via API I have : 

```
    public 'sale_price' -> string (2) "20"
    public 'date_on_sale_from' -> string (19) "2023-02-01T00:00:00"
    public 'date_on_sale_from_gmt' -> string (19) "2023-01-31T23:00:00"
    public 'date_on_sale_to' -> string (19) "2023-02-24T18:00:00"
    public 'date_on_sale_to_gmt' -> string (19) "2023-02-24T17:00:00"
    public 'on_sale' -> boolean true
```  

But, on editor woocommerce, 
I don't show the date.

![image](https://user-images.githubusercontent.com/1475705/216666193-3ecc88bb-2f0a-4dee-884c-320b310d5323.png)

### Expected behavior

I would show and edit the date in editor product admin

### Actual behavior

The sale date work on the product view, but not work in the admin product editor

### Steps to reproduce

Add product via API
Put product via API whit sale_date
Show product in editor product admin
And, voila, no date show.

### WordPress Environment

WooCommerce: 7.1.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@emulsion-io it looks like this was happening for you in WooCommerce version **7.1.0**, which is a few versions behind now. Do you still see this in the latest version? When I try in the latest version, the sale dates do appear in the admin UI.

Might also help if you could share the exact API request you are using.
