### ISSUE TITLE
Code Analyzer: Use of wp-env is problematic

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36750]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When running Code Analyzer we run into a lot of issues.

```
Command failed: wp-env start
```

wp-env is responsible for calling two functions vi WP CLI

https://github.com/woocommerce/woocommerce/blob/3828aabbef631b8e6ce1778ef8a1cee80e60b83f/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2321

https://github.com/woocommerce/woocommerce/blob/3828aabbef631b8e6ce1778ef8a1cee80e60b83f/plugins/woocommerce/bin/wc-get-schema.php#L12-L20

Calling `wp-env start` programatically appears to cause problems, especially with Docker. We need to either:

1. Find a safer way of handling wp-env
2. Find a replacement for wp-env
3. Determine a different way of detecting schema changes, perhaps through static analysis

**Comment by samueljseay** [comment]
Closing in favor of https://github.com/woocommerce/platform-private/issues/198
