### ISSUE TITLE
Fatal errors in PHP 8.0.25 in Square plugin

### ISSUE THREAD

**Issue by AaronSTAY** [woothemes/woocommerce#36757]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After my hosting provider Namecheap upgraded to PHP 8.0.25 I started getting fatal errors in the Square plugin. They currently downgraded me temporarily to PHP 7.4 which is no longer supported by them as it has security issues. 

```
2023/02/03 20:43:42 [error] 7541#7541: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function Core\Utils\php_uname() in /var/www/wptbox/wp-content/plugins/woocommerce-square/vendor/apimatic/core/src/Utils/CoreHelper.php:159  Stack trace:
#0 /var/www/wptbox/wp-content/plugins/woocommerce-square/vendor/apimatic/core/src/ClientBuilder.php(181): Core\Utils\CoreHelper::getOsInfo()
#1 /var/www/wptbox/wp-content/plugins/woocommerce-square/vendor/apimatic/core/src/ClientBuilder.php(195): Core\ClientBuilder->addUserAgentToGlobalHeaders()
#2 /var/www/wptbox/wp-content/plugins/woocommerce-square/vendor/square/square/src/SquareClient.php(172): Core\ClientBuilder->build()
#3 /var/www/wptbox/wp-content/plugins/woocommerce-square/includes/API.php(64): Square\SquareClient->__construct()
#4 /var/www/wptbox/wp-content/plugins/woocommerce-square/includes/Plugin.php(656): WooCommerce\Square\API->__construct()
#5 /var/www/wptbox/wp-content/plugins/woocommerce-square/includes/Settings.php(717): WooCommerce\Square\Plugin->get_api()
#6 /var/" while reading response header from upstream, client: 142.116.121.153, server: , request: "GET /wp-admin/admin.php?page=wc-settings&tab=square HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-default-one.sock:", host: "overgrowncanada.com", referrer: "http://overgrowncanada.com/wp-admin/admin.php?page=wc-settings "
```

### Expected behavior

No errors

### Actual behavior

Errors

### Steps to reproduce

Add the Square plugin to a WordPress instance running PHP 8.0.25

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://overgrowncanada.com
Site address (URL): https://overgrowncanada.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.12
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.73.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 9.50MB
Database Data Size: 7.55MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.50MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.30MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_sib_model_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_square_integration_deleted_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_square_integration_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 15
btf_builder: 1
custom_css: 1
customize_changeset: 17
elementor_library: 4
elementor-hf: 1
nav_menu_item: 6
page: 8
post: 3
revision: 35
wp_easy_pay: 2
wp_global_styles: 1
wpr_mega_menu: 2
wpr_templates: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Advanced Custom Fields: by WP Engine – 6.0.7
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.22.3
Easy WP SMTP: by Easy WP SMTP team – 1.5.3
Elementor: by Elementor.com – 3.10.2
ElementsKit Lite: by Wpmet – 2.8.1
Google Listings and Ads: by WooCommerce – 2.3.8
Happy Elementor Addons: by weDevs – 3.8.2
Jetpack Protect: by Automattic - Jetpack Security team – 1.2.0
Jetpack: by Automattic – 11.7.1
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.57
Pinterest for WooCommerce: by WooCommerce – 1.2.10
Premium Addons for Elementor: by Leap13 – 4.9.48
Royal Elementor Addons: by WP Royal – 1.3.62
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 3.0.3
WooCommerce Shipping & Tax: by WooCommerce – 2.2.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce Square: by WooCommerce – 3.5.0
WooCommerce: by Automattic – 7.3.0
Yoast SEO: by Team Yoast – 20.0

### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (1) ###

EasyWP Plugin: by Namecheap
Inc. – 1.0.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/wptbox/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/cart/cart.php version 3.8.0 is out of date. The core version is 7.0.1
/var/www/wptbox/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/cart/mini-cart.php
/var/www/wptbox/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/notices/error.php
/var/www/wptbox/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/notices/notice.php
/var/www/wptbox/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/notices/success.php

Outdated Templates: ❌
					
					
						Learn how to update

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-04 18:40:35 +00:00
Options: ✔
Notes: 45
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2023-02-03 18:55:10 +0000
Newest: 2023-02-03 18:55:10 +0000

Complete: 99
Oldest: 2023-01-23 18:46:49 +0000
Newest: 2023-02-04 15:16:16 +0000

Failed: 1
Oldest: 2023-02-03 16:14:21 +0000
Newest: 2023-02-03 16:14:21 +0000

Pending: 5
Oldest: 2023-02-04 15:56:57 +0000
Newest: 2023-02-11 01:36:56 +0000

### Status report information ###

Generated at: 2023-02-04 15:21:55 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @AaronSTAY,

Thank you for submitting this issue. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the Square plugin, which is available on the WooCommerce Marketplace. To get further technical support for it, please contact the support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
