### ISSUE TITLE
New Add Disable Class Prevents JS Prompt and Deletion of Payment Method.

### ISSUE THREAD

**Issue by Poocey** [woothemes/woocommerce#36769]
https://github.com/woocommerce/woocommerce/blob/bd6b137c9206076644bbcab0cb90790f5121ba90/plugins/woocommerce/client/legacy/js/frontend/add-payment-method.js#L36

When I remove this script, I am able to delete a payment method; otherwise, it just adds the disable class and does nothing.

**Comment by lsinger** [comment]
Hello @Poocey,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. To do so, please select the "Bug Report" template [when creating an issue here](https://github.com/woocommerce/woocommerce/issues/new/choose). I will now close this issue.
