### ISSUE TITLE
Woocommerce and ACF conflict when using SVG's

### ISSUE THREAD

**Issue by kristjankoppel** [woothemes/woocommerce#36764]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have partners section on my e-shop. Partners are a repeater field created via ACF. One sub field there is logo and it allows to add SVG logo for partner. This is regular image field in ACF. But when i output that SVG logo on website i get error message "Notice: Undefined index: width in /app/cms/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php on line 276 
Notice: Undefined index: height in /app/cms/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php on line 277"

What bug's me is that this is just a regular section that is no way related to Woocommerce. So why even Woocommerce try's to do something with my repeater field and image field? 

Only workaround is to change Return Format for that logo field from "Image Array" to "Image URL".

So two bugs here:
a) Why Woocommerce try's to interact images that are added via ACF and meta fields
b) function get_full_size_image_dimensions() should have check for SVG's since SVG's don't have 

Same issue on Woocommerce support forums at Wordpress.org: [https://wordpress.org/support/topic/woocommerce-regenerating-images-svg-error/](https://wordpress.org/support/topic/woocommerce-regenerating-images-svg-error/)

### Expected behavior

Clean image output without notice and without running Woocommerce get_full_size_image_dimensions() function.

### Actual behavior

Woocommerce runs get_full_size_image_dimensions() without reason and results creating notices since it try's to find width and height for SVG.

### Steps to reproduce

1. Install Woocommerce
2. Install Advanced Custom Fields Pro plugin
3. Create repeater field named Partners
4. For that repeater field add sub field Logo as image field
5. Try to echo image and see that notice is outputted

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: et
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.29
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Andmebaasi maht kokku: 4.81MB
Andmebaasi andmete maht: 3.21MB
Andmebaasi indeksi maht: 1.60MB

### Post Type Counts ###

acf-field: 13
acf-field-group: 1
attachment: 46
customize_changeset: 1
nav_menu_item: 3
page: 17
polylang_mo: 3
post: 2
product: 17
revision: 18

### Active Plugins (19) ###

Polylang Pro: - WP SYNTEX – 3.3.1
Advanced Custom Fields: Extended: - ACF Extended – 0.8.9
ACF Options for Polylang: - Be API – 1.1.10
Advanced Custom Fields PRO: - WP Engine – 6.0.7
The SEO Framework: - The SEO Framework Team – 4.2.7.1
BEA - Fix Loco Translate: - Be API Technical team – 1.1.1
BEA - Sanitize Filename: - Be API – 2.0.7
Classic Editor +: - <a href="https://so-wp.com">Pieter Bos</a>
<a href="https://gschoppe.com">Greg Schoppe</a> – 4.0.2

Cyr-To-Lat: - Sergey Biryukov
Mikhail Kobzarev
Igor Gergel – 5.4.0

Disable Comments: - WPDeveloper – 2.4.3
Disable Bloat for WordPress & WooCommerce: - Disable Bloat – 3.1.15
Disable Emojis (GDPR friendly): - Ryan Hellyer – 1.7.4
Disable REST API: - Dave McHale – 1.7
Disable XML-RPC: - Philip Erb – 1.0.1
Form Data Collector: - Klipper LLC – 2.2.3
Loco Translate: - Tim Whitlock – 2.6.3
No Category Base (WPML): - Marios Alexandrou – 1.3
Polylang for WooCommerce: - WP SYNTEX – 1.7.1
WooCommerce: - Automattic – 7.3.0

### Inactive Plugins (2) ###

Query Monitor: - John Blackbourn – 3.11.1
Stream: - XWP – 3.9.2

### Must Use Plugins (1) ###

autoload.php: -  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Poe alusaadress: #9 - /pood/
Ostukorv: #10 - /ostukorv/
Kassa: #11 - /kassa/
Minu konto: #12 - /minu-konto/
Müügitingimused: ❌ Lehte ei ole määratud

### Templates ###

Overrides: –

### WC Pages Translations ###

Shop base: ✔
Cart: ✔
Checkout: ✔
My account: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-07 14:32:48 +02:00
Options: ✔
Notes: 37
Onboarding: completed

### Action Scheduler ###

Täidetud: 23
Oldest: 2023-02-03 16:34:21 +0200
Newest: 2023-02-06 20:05:47 +0200

Ootel: 1
Oldest: 2023-02-07 20:05:47 +0200
Newest: 2023-02-07 20:05:47 +0200

### Status report information ###

Generated at: 2023-02-06 21:37:29 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kristjankoppel** [comment]
@werner-lemon haven't heard anything. This bug still exists i believe

**Comment by coreymckrill** [comment]
Hi @kristjankoppel I think this is the same as #33729. I agree that `WC_Regenerate_Images::maybe_resize_image` shouldn't throw notices when the meta data doesn't exist, as is the case for SVG's.

Closing as duplicate, but feel free to reopen if you think it's not.

**Comment by kristjankoppel** [comment]
@coreymckrill  Yes, it seems that these topics are same. And if we could just exclude SVG's from maybe_resize_image function then it would solve a problem/bug.
