### ISSUE TITLE
Return type of some shipping and discount getter methods are not proper

### ISSUE THREAD

**Issue by devAsadNur** [woothemes/woocommerce#36762]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The return type of some shipping and discount getter methods (`get_shipping_total()`, `get_shipping_tax()`, `get_discount_total()`, and `get_discount_tax()`) are not proper. So, those methods generate errors in some special cases. For example, if the `post_status` is `auto-draft`. Then, using those methods throw fatal errors.

Suppose, we have an order with `auto-draft` status. The order ID is 1347. By running the following code will generate fatal error.
```
$order   = wc_get_order( 1347 );
$earning = $order->get_total_shipping() - $order->get_total_shipping_refunded();

echo $earning;
```

### Expected behavior

The return type of the above-mentioned methods in the `WC_Abstract_Order` class should be `float`, instead of `string`. 
1. `get_shipping_total()`
2. `get_shipping_tax()`
3. `get_discount_total()`
4. `get_discount_tax()`

### Actual behavior

Right now, the return type of the following methods in the `WC_Abstract_Order` class is `string`, which may generate a fatal error in some specific cases.

### Steps to reproduce

1. Go to `WooCommerce` > `Orders` > `Add Order`.
2. It will generate an order with an ID.
3. Leave the order creation page without clicking the `Create` button. So, the order's `post_status` will be `auto-draft`.
4. Now, get the order using the `wc_get_order()` method.
5. Try to do some calculations using any of the above-mentioned methods as per below codes. It will throw fatal errors.
```
$order   = wc_get_order( 1347 );
$earning = $order->get_total_shipping() - $order->get_total_shipping_refunded();

echo $earning;
```

### WordPress Environment

`
WordPress address (URL): https://dokan-dev.test
Site address (URL): https://dokan-dev.test
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 8.0.27
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
(SecureTransport) OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 8.0.28
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 26.26MB
Database Data Size: 17.47MB
Database Index Size: 8.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.80MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.39MB + Index: 0.45MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.30MB + Index: 0.27MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_dokan_advertised_products: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_delivery_time: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_distance_rate_shipping: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_follow_store_followers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_orders: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_report_abuse_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_request_quote_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_request_quote_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_request_quotes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_reverse_withdrawal: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_tracking: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_table_rate_shipping: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 5.27MB + Index: 3.92MB + Engine InnoDB
wp_posts: Data: 3.08MB + Index: 0.28MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 13
post: 4
postman_sent_mail: 250
product: 24
product_variation: 7
revision: 3
shop_order: 517
shop_order_refund: 99
wc_booking: 162

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Dokan Pro: by weDevs – 3.7.13
Dokan: by weDevs – 3.7.10
WP OPcache: by nierdz – 4.2.0
WooCommerce: by Automattic – 7.3.0
WP Console: by Edi Amin – 2.3.1

### Inactive Plugins (9) ###

Another Show Hooks: by Exlac – 1.0.2
Automatic Translate Addon For Loco Translate: by Cool Plugins – 2.3.2
Hello Dolly: by Matt Mullenweg – 1.7.2
JSON Basic Authentication: by WordPress API Team – 0.1
Loco Translate: by Tim Whitlock – 2.6.3
Post SMTP: by Post SMTP – 2.3.2
Query Monitor: by John Blackbourn – 3.11.1
Show Current Template: by JOTAKI Taisuke – 0.4.6
WooCommerce Bookings: by WooCommerce – 1.15.69

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-07 10:10:20 +00:00
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Complete: 1,201
Oldest: 2023-01-09 04:34:01 +0000
Newest: 2023-02-06 10:54:43 +0000

Failed: 1
Oldest: 2023-01-04 10:13:31 +0000
Newest: 2023-01-04 10:13:31 +0000

Pending: 2
Oldest: 2023-02-07 03:17:59 +0000
Newest: 2023-02-15 04:53:30 +0000

### Status report information ###

Generated at: 2023-02-06 12:34:30 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Thanks for the report, unfortunately we have to close this one unfixed. see https://github.com/woocommerce/woocommerce/pull/36763#issuecomment-1443566302
