### ISSUE TITLE
[Enhancement] Update copy and layout of the inventory management fields

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36777]
Per some internal feedback (pbIJXs-3a-p2#comment-5862), we need to update the copy and tweak the logic of the inventory management section in the new form experience.

### Design

`AkVNGImLgSqCObTQ3idVn7-fi-1005-134963&mode=design&t=2s9bDVaOk72CLcB7-4`

<img width="383" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/4edb009d-b989-40a2-aa0c-5c35aadc827a">

```[tasklist]
### Acceptance criteria
- [ ] Track stock quantity for this product -> `Track inventory`
- [ ] Available quantity -> `Available stock`
- [x] Email me when quantity reaches -> `Email me when stock reaches`
- [x] The `Email me when stock reaches` field is now in the `Advanced` sub-section
```

cc @pmcpinto

**Comment by pmcpinto** [comment]
@jarekmorawski to review AC

**Comment by jarekmorawski** [comment]
AC reviewed and updated.

**Comment by Brianmitchtay** [comment]
Perhaps relevant to changes here, I just opened this slightly related issue. #39152

**Comment by pmcpinto** [comment]
@jarekmorawski are these UX copy changes aligned with the updates proposed by Laura?

**Comment by jarekmorawski** [comment]
Yup! This copy is up to date.
