### ISSUE TITLE
[Enhancement] Better error handling for variation SKUs

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36774]
When we generate variations, we currently duplicate the parent's SKU. This leads to an error when the user attempts to save either the parent product or a variation. The issue is only resolved when the user updates the SKU.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/79307566/217108023-6053e8f0-a088-4eaa-b1bd-e332999ff79c.png">

```[tasklist]
### Acceptance criteria
- [ ] When the parent product has an SKU, it is copied to the variations with a suffix that uses the combination of options. For example, if the parent product's SKU is `cotton-tshirt`, for a small/blue variation, the SKU would be `cotton-tshirt-small-blue`.
- [ ] When the parent product doesn't have an SKU, the variation is created with an SKU that consists of a combination of options and its unique ID. For example: `small-blue-1234`. When the user enters a custom SKU for the parent product, we apply the rule described above.
- [ ] If there are two variations with the same SKU, we add a -X suffix at the end of it. For example: `cotton-tshirt-small-blue-1` and `cotton-tshirt-small-blue-2`.
```
cc @pmcpinto

**Comment by AnnaMag** [comment]
Note: verify that https://github.com/woocommerce/woocommerce/issues/36585 is fixed.

**Comment by AnnaMag** [comment]
[[New Product Editor]: repeated error messaging.#39360](https://github.com/woocommerce/woocommerce/issues/39360) will likely be fixed by this change.

**Comment by octaedro** [comment]
Hi @jarekmorawski,
I'm trying to reproduce this problem, but I'm not able to do so. The parent product has an SKU, but the variations don't have one, so this error is not happening anymore. Am I missing something?
I suspect that this error has been fixed over these months.

If it's ok with you, I'll close this issue.

// CC @AnnaMag

**Comment by louwie17** [comment]
Closing this given @octaedro last response, feel free to re-open if needed.
