### ISSUE TITLE
[Fix] Make form header tabs selectable using keyboard

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36773]
We currently do not support keyboard navigation in the new tabbed form header. To ensure better accessibility, we should allow users to select, navigate, and activate tabs using the keyboard.

## Implementation notes

- [ARIA tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)

```[tasklist]
### Acceptance criteria
- [x] Users can press `Tab` to navigate between different page elements, including tabs.
- [x] Users can press `Tab` again to navigate to a different element outside the tabs (tabbing when inside the tabs takes you to the first focusable element inside the current tab's tab panel)
- [x] Users can press the left and right arrow keys to move between tabs.
- [x] Users can press `Space` or `Enter` to activate a tab.
- [x] Focus tab shows focus style
```

cc @pmcpinto

**Comment by pmcpinto** [comment]
@jarekmorawski should we keep this one in the backlog?

**Comment by jarekmorawski** [comment]
Yes! It's still very much needed.

**Comment by pmcpinto** [comment]
👍 I'll add it to the cycle 43 backlog for consideration.
