### ISSUE TITLE
[Enhancement] Update the default stock number from 0 to 10

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36776]
Instead of 0, the default stock number for any new product should be 10. This should apply to regular products and individual variations.

```[tasklist]
### Acceptance criteria
- [ ] The default product quantity is 10 when the user enables inventory tracking while creating a new product.
- [ ] If the parent product doesn't contain a value, all variations with inventory tracking enabled have the default quantity of 10.
```

cc @pmcpinto

**Comment by pmcpinto** [comment]
Why do you think it should be 10?

**Comment by jarekmorawski** [comment]
Honestly, it's an educated guess. 1 seems too little, and 100 is too much. 10 looks like a good starting point for both small-batch products and larger inventories. It's so obviously off that it may draw the user's attention to enter the actual value.

**Comment by pmcpinto** [comment]
I'm closing this as we're already defaulting to 1. We can revisit this in the future.
