### ISSUE TITLE
[Enhancement] New UX feedback prompt bar – visual refinements

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#36770]
I noticed that the bottom feedback prompt bar in the new experience doesn't have a hairline at the bottom, and the font style and color in the badge that says `Beta` differs from the one we use elsewhere.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/79307566/217103896-3e1fd103-3fb4-425e-be24-53a90a255b57.png">

```[tasklist]
### Acceptance criteria
- [ ] The bottom bar has a 1 px `border-top` line (`Gutenberg-400`)
- [ ] The `Beta` badge is the same as the one we use in the page header and other parts of the experience.
```

cc @pmcpinto

**Comment by mattsherman** [comment]
Closing this... addressed.
