### ISSUE TITLE
Woocoomerce problem

### ISSUE THREAD

**Issue by 1admxk** [woothemes/woocommerce#36787]
(PT-BR / Portuguese Brazillian)

WordPress versão 6.1.1
Tema atual: Blocksy (versão 1.8.72)
Plugin atual: WooCommerce (versão 7.3.0)
PHP versão 8.1.13
Agente de rede: NGINX 1.21.4
Sistema Operacional: CentOS 9 Stream (5.14.0-234)
Painel Instalado: AAPANEL

Detalhes do erro
================
Um erro do tipo E_ERROR foi causado na linha 52 do arquivo /www/wwwroot/KakumeiZero/wp-content/plugins/woocommerce/lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php. Mensagem de erro: Uncaught Automattic\WooCommerce\Vendor\League\Container\Exception\ContainerException: A service provider must be a fully qualified class name or instance of (\Automattic\WooCommerce\Vendor\League\Container\ServiceProvider\ServiceProviderInterface) in /www/wwwroot/KakumeiZero/wp-content/plugins/woocommerce/lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php:52
Stack trace:
#0 /www/wwwroot/KakumeiZero/wp-content/plugins/woocommerce/lib/packages/League/Container/Container.php(146): Automattic\WooCommerce\Vendor\League\Container\ServiceProvider\ServiceProviderAggregate->add()
#1 /www/wwwroot/KakumeiZero/wp-content/plugins/woocommerce/src/Container.php(89): Automattic\WooCommerce\Vendor\League\Container\Container->addServiceProvider()
#2 /www/wwwroot/KakumeiZero/wp-content/plugins/woocommerce/woocommerce.php(38): Automattic\WooCommerce\Container->__construct()
#3 /www/wwwroot/KakumeiZero/wp-settings.php(447): include_once('...')
#4 /www/wwwroot/KakumeiZero/wp-config.php(89): require_once('...')
#5 /www/wwwroot/KakumeiZero/wp-load.php(50): require_once('...')
#6 /www/wwwroot/KakumeiZero/wp-admin/admin-ajax.php(22): require_once('...')
#7 {main}
  thrown

**Comment by lsinger** [comment]
Hello @1admxk,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. Please use [the Bug Report template here](https://github.com/woocommerce/woocommerce/issues/new/choose).
