### ISSUE TITLE
The tax parameter is not used correctly in the "get_discount_to_display" method

### ISSUE THREAD

**Issue by rvola** [woothemes/woocommerce#36794]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I use the method [get_order_item_total()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order.php#L2255)
passing the $tax_display parameter to "excl"

I noticed that I get the tax excluded values table fine.

On the other hand for the call of the method [add_order_item_totals_discount_row()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L2159), this one will call the method [$this->get_discount_to_display()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L2131) with the parameter but this one will not be retained because of the double conditions in wc_price()

1. $tax_display parameter must be "excl"
2. get_option('woocommerce_tax_display_cart') should return "excl"

However, if this method is used with a parameter, it is precisely to "cancel" the release from the options

### Expected behavior

To be able to obtain a table of totals without taxes by the parameter.

### Actual behavior

Gets an array of ht values except for discounts

### Steps to reproduce

have an order with a discount (coupon)
```
$order = wc_get_order(XXX);
$output = $order->get_order_item_totals( 'excl' );
print_r( $output );
```

### WordPress Environment ###
```
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –
```
### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@rvola Thanks for the report. I'm not sure I understand the issue with the current steps to reproduce. Could you add some more step-by-step instructions and explain where the output is indicating a bug? Or even better, is there a way to demonstrate this using the admin interface?

**Comment by rvola** [comment]
Hello here is a concrete example of the command.

<img width="798" alt="order" src="https://user-images.githubusercontent.com/6870615/219956687-1a751c76-b7de-4b97-aaa1-6984eb45027f.png">

**My need is the following:**
Display prices including VAT throughout the store for customers, but to create a PDF invoice with French standards I need a precise display of VAT and not like the VAT mode: "_XXX € includes XXX€ TVA_" in voluntarily "excluding" taxes.

Here is my code which does not get the correct results :
```
$order = wc_get_order( XXXX );
$totals = $order->get_order_item_totals( 'excl' );
print_r( $totals ); 
die;
```

### Example 1:
_Correct display (discount) -18,50 €._
"Display prices during cart and checkout" = "including tax"
`get_option('woocommerce_tax_display_cart') = "incl"`
`$order->get_order_item_totals( 'incl' );`

```
Array
(
    [cart_subtotal] => Array
        (
            [label] => Subtotal:
            [value] => 171,00 €
        )

    [discount] => Array
        (
            [label] => Discount:
            [value] => -18,50 €
        )

    [shipping] => Array
        (
            [label] => Shipping:
            [value] => 10,00 € via Expédition
        )

    [payment_method] => Array
        (
            [label] => Payment method:
            [value] => Virement bancaire
        )

    [order_total] => Array
        (
            [label] => Total:
            [value] => 162,50 € (includes 27,09 € TVA 20%)
        )

)
```

### Example 2:
_Correct result except for the line containing the discount (display of the discount with the tax)._

"Display prices during cart and checkout" = "including tax"
`get_option('woocommerce_tax_display_cart') = "incl"`
`$order->get_order_item_totals( 'excl' );`
```
Array
(
    [cart_subtotal] => Array
        (
            [label] => Subtotal:
            [value] => 142,50 € (ex. VAT)
        )

    [discount] => Array
        (
            [label] => Discount:
            [value] => -18,50 €
        )

    [shipping] => Array
        (
            [label] => Shipping:
            [value] => 8,33 € (ex. VAT) via Expédition
        )

    [fr-tva-20] => Array
        (
            [label] => TVA 20%:
            [value] => 27,09 €
        )

    [payment_method] => Array
        (
            [label] => Payment method:
            [value] => Virement bancaire
        )

    [order_total] => Array
        (
            [label] => Total:
            [value] => 162,50 €
        )

)
```

### Example 3:
_Correct result (discount) and expected result however I have to modify the global settings (options) while the call to the method with the "excl" variable must override the WooCommerce options_

"Display prices during cart and checkout" = "excluding tax"
`get_option('woocommerce_tax_display_cart') = "excl"`
`$order->get_order_item_totals( 'excl' );`

```
Array
(
    [cart_subtotal] => Array
        (
            [label] => Subtotal:
            [value] => 142,50 € (ex. VAT)
        )

    [discount] => Array
        (
            [label] => Discount:
            [value] => -15,42 €
        )

    [shipping] => Array
        (
            [label] => Shipping:
            [value] => 8,33 € (ex. VAT) via Expédition
        )

    [fr-tva-20] => Array
        (
            [label] => TVA 20%:
            [value] => 27,09 €
        )

    [payment_method] => Array
        (
            [label] => Payment method:
            [value] => Virement bancaire
        )

    [order_total] => Array
        (
            [label] => Total:
            [value] => 162,50 €
        )

)
```

**Comment by vedanshujain** [comment]
Closing in favor of #37617
