### ISSUE TITLE
Postcodes with spaces are matched by wild card with no spaces

### ISSUE THREAD

**Issue by mouligreenlaw** [woothemes/woocommerce#36797]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you set up a postcode wild card in a shipping zone such as `PA67*` it matches postcodes such as `PA6 7LN`.
The merchant is using UK postcodes but I was able to replicate it using NZ.
It is likely to be related to this issue: [Postcodes with spaces do not match Zones for specific countries](https://github.com/woocommerce/woocommerce/issues/24369) but is not about different returns for different countries.

### Expected behavior

That the postcode filters and wild card behaviour respects spaces.
`PA6 7LN` should not match `PA67*`

### Actual behavior

It appears that the space is stripped causing the erroneous match. 

### Steps to reproduce

1. Set up a zone with a postcode filter: `PA67*`
2. Enable Shipping Debug
3. Use `PA6 7LN` in checkout
4. Check selected zone

### WordPress Environment ###

WordPress address (URL): https://duux.co.uk
Site address (URL): https://duux.co.uk
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1q-fips

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: euq_
Total Database Size: 611.24MB
Database Data Size: 438.57MB
Database Index Size: 172.67MB
euq_woocommerce_sessions: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
euq_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
euq_woocommerce_order_items: Data: 5.06MB + Index: 2.03MB + Engine InnoDB
euq_woocommerce_order_itemmeta: Data: 27.06MB + Index: 26.36MB + Engine InnoDB
euq_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
euq_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_actionscheduler_actions: Data: 2.02MB + Index: 3.55MB + Engine InnoDB
euq_actionscheduler_claims: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
euq_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_actionscheduler_logs: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
euq_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_braapf_product_stock_status_parent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_braapf_product_variation_attributes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_braapf_variation_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_commentmeta: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
euq_comments: Data: 13.02MB + Index: 17.31MB + Engine InnoDB
euq_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_options: Data: 8.31MB + Index: 1.16MB + Engine InnoDB
euq_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
euq_postmeta: Data: 90.61MB + Index: 83.02MB + Engine InnoDB
euq_posts: Data: 17.52MB + Index: 17.09MB + Engine InnoDB
euq_redirection_404: Data: 2.02MB + Index: 1.19MB + Engine InnoDB
euq_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
euq_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
euq_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
euq_term_relationships: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
euq_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
euq_usermeta: Data: 3.34MB + Index: 2.95MB + Engine InnoDB
euq_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
euq_wcpdf_invoice_number: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
euq_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
euq_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
euq_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wc_customer_lookup: Data: 3.34MB + Index: 2.47MB + Engine InnoDB
euq_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
euq_wc_order_product_lookup: Data: 3.05MB + Index: 4.39MB + Engine InnoDB
euq_wc_order_stats: Data: 2.02MB + Index: 2.38MB + Engine InnoDB
euq_wc_order_tax_lookup: Data: 2.02MB + Index: 2.20MB + Engine InnoDB
euq_wc_product_attributes_lookup: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
euq_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
euq_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_wfconfig: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
euq_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
euq_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
euq_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
euq_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
euq_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wlpr_points: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
euq_wlpr_point_logs: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
euq_wlpr_referral: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wlpr_user_point_actions: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
euq_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wpml_mails: Data: 248.52MB + Index: 0.00MB + Engine InnoDB
euq_wt_iew_action_history: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
euq_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
euq_yoast_indexable: Data: 2.52MB + Index: 1.63MB + Engine InnoDB
euq_yoast_indexable_hierarchy: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
euq_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
euq_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
euq_yoast_seo_links: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
euq_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2816
br_filters_group: 2
br_product_filter: 5
customize_changeset: 6
custom_css: 1
flamingo_contact: 1124
nav_menu_item: 42
oembed_cache: 323
page: 39
post: 15
product: 152
revision: 703
shipping_validation: 1
shop_coupon: 3063
shop_order: 9716
shop_order_refund: 62
vc4_templates: 4
vc_grid_item: 1
wpcf7_contact_form: 7
wpforms: 3
wp_amc_gallery: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Advanced Shipping Validation for WooCommerce: by Jeroen Sormani – 1.1.5
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.21.0
App Mockups Carousel Pro: by WP Online Support – 1.1
HTML Template for CF7: by Mário Valney – 2.1.1
Civic Cookie Control 8: by Civic Uk – 1.44
CMP - Coming Soon & Maintenance Plugin: by NiteoThemes – 4.1.6
Contact Form 7: by Takayuki Miyoshi – 5.7.2
Disable XML-RPC: by Philip Erb – 1.0.1
Facebook for WooCommerce: by Facebook – 3.0.4
Flamingo: by Takayuki Miyoshi – 2.3
Go Live Update Urls: by OnPoint Plugins – 6.4.1
Head, Footer and Post Injections: by Stefano Lissa – 3.2.5
Import Export Suite for WooCommerce: by WebToffee – 1.1.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.5
Kadence WooCommerce Email Designer: by Kadence WP – 1.3.12
WooCommerce Loyalty Points and Rewards: by Flycart – 1.2.16
Mailchimp for WooCommerce: by Mailchimp – 2.7.6
PixelYourSite: by PixelYourSite – 9.2.1
Plugins Garbage Collector (Database Cleanup) Old!: by Vladimir Garagulya – 0.14
Product Catalog Feed by PixelYourSite: by PixelYourSite – 2.0.1
Product Sales Report for WooCommerce: by Aspen Grove Studios – 1.5.1
Quick Empty Trash: by Hugh Lashbrooke – 1.0
Redirection: by John Godley – 5.3.6
reSmush.it Image Optimizer: by reSmush.it – 0.4.11
WooCommerce Estimated Shipping Date Per Product: by Magerips – 1.8
Safe SVG: by 10up – 2.0.3
SiteGround Optimizer: by SiteGround – 7.3.0
Trustpilot-reviews: by Trustpilot – 2.5.914
Twist - Product Gallery Slider for Woocommerce: by Niloy Sarker – 2.0.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.23

WPC Fly Cart for WooCommerce: by WPClever.net – 2.2.1
WooCommerce international phone input: by Alex Masliychuk (alex91ckua) – 2.0.3
WooCommerce Advanced Bulk Edit: by George Iron – 4.5
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.6.3.4
WooCommerce Chained Products: by WooCommerce – 2.6.0
WooCommerce Extra EAN Field: by PIXEL3. – 2.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.17
WooCommerce Multiple Free Gift: by lilmonkee – 1.2.3
WooCommerce PayPal Payments: by WooCommerce – 1.9.5 (update to version 2.0.2 is available)
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.4
xCore Rest API extension: by Dealer4Dealer – 1.8.2
WooCommerce: by Automattic – 7.1.0 (update to version 7.3.0 is available)
Wordfence Security: by Wordfence – 7.7.1
WordPress Importer: by wordpressdotorg – 0.8
Yoast SEO: by Team Yoast – 19.10
WP Duplicate Page: by Ninja Team – 1.3
WP Mail Logging: by Wysija – 1.10.4
WP Rollback: by GiveWP.com – 1.7.2
WP-SCSS: by Connect Think – 2.4.0
WPForms Lite: by WPForms – 1.7.8

### Inactive Plugins (7) ###

Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.2
GTM4WP: by Thomas Geiger – 1.16.2
iThemeland Free Gifts For Woo Lite: by iThemelandco – 1.8.6
JavaScript Inserter: by Space X-Chimp – 1.28
WooCommerce Order Search Admin powered by Algolia: by Raymond Rutjes – 1.13.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Product Stock Alert: by WC Marketplace – 1.7.5

### Must Use Plugins (1) ###

installatron_hide_status_test.php: by –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #239 - /store/
Basket: #240 - /cart/
Checkout: #241 - /checkout/
My account: #242 - /my-account/
Terms and conditions: #165 - /terms-conditions/

### Theme ###

Name:
Version: (update to version 0 is available)
Author URL:
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: skeleton/woocommerce/archive-product.php
skeleton/woocommerce/checkout/form-billing.php
skeleton/woocommerce/checkout/form-checkout.php
skeleton/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
skeleton/woocommerce/checkout/form-login.php
skeleton/woocommerce/checkout/form-shipping.php
skeleton/woocommerce/checkout/payment-method.php
skeleton/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 7.0.1
skeleton/woocommerce/checkout/review-order.php
skeleton/woocommerce/checkout/terms.php
skeleton/woocommerce/checkout/thankyou.php
skeleton/woocommerce/content-product.php
skeleton/woocommerce/content-single-product.php
skeleton/woocommerce/emails/admin-cancelled-order.php
skeleton/woocommerce/emails/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
skeleton/woocommerce/emails/customer-invoice.php
skeleton/woocommerce/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
skeleton/woocommerce/emails/customer-note.php
skeleton/woocommerce/emails/customer-on-hold-order.php
skeleton/woocommerce/emails/customer-processing-order.php
skeleton/woocommerce/emails/customer-refunded-order.php
skeleton/woocommerce/emails/customer-reset-password.php
skeleton/woocommerce/emails/email-footer.php version 2.3.0 is out of date. The core version is 3.7.0
skeleton/woocommerce/emails/email-header.php version 2.4.0 is out of date. The core version is 4.0.0
skeleton/woocommerce/emails/email-order-details.php
skeleton/woocommerce/emails/email-order-items.php
skeleton/woocommerce/emails/email-styles.php version 3.3.0 is out of date. The core version is 4.0.0
skeleton/woocommerce/loop/result-count.php
skeleton/woocommerce/myaccount/dashboard.php
skeleton/woocommerce/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 7.0.1
skeleton/woocommerce/myaccount/form-login.php version 4.1.0 is out of date. The core version is 7.0.1
skeleton/woocommerce/myaccount/my-account.php
skeleton/woocommerce/myaccount/my-address.php
skeleton/woocommerce/myaccount/my-orders.php
skeleton/woocommerce/myaccount/navigation.php
skeleton/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1
skeleton/woocommerce/myaccount/view-order.php
skeleton/woocommerce/order/order-details.php version 3.7.0 is out of date. The core version is 4.6.0
skeleton/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
skeleton/woocommerce/single-product/review.php
skeleton/woocommerce/single-product/tabs/additional-information.php
skeleton/woocommerce/single-product/tabs/tabs.php
skeleton/woocommerce/single-product-reviews.php
skeleton/woocommerce/single-product.php

Outdated Templates: ❌

Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-03 13:27:01 +00:00
Options: ✔
Notes: 97
Onboarding: completed

### Action Scheduler ###

Complete: 2,048
Oldest: 2023-01-02 17:45:50 +0000
Newest: 2023-02-02 15:27:46 +0000

Failed: 702
Oldest: 2022-08-13 11:32:34 +0100
Newest: 2023-02-02 14:04:54 +0000

Pending: 7
Oldest: -0001-11-29 23:58:45 -0001
Newest: 2023-02-09 14:05:18 +0000

### Status report information ###

Generated at: 2023-02-02 15:32:07 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholasjeberlin** [comment]
6012649-zen

**Comment by barryhughes** [comment]
Thanks for flagging. 

* For backwards-compatibility reasons, we probably don't want to make a change that impacts how existing rules are interpreted (we don't want to adversely impact merchants working with whitespace-insensitive post codes).
* We can probably introduce a flag of some kind that allows merchants to indicate that a `*` should match whitespace (or the inverse).

**Comment by kloon** [comment]
Looking at UK specifically and thinking about it from a mail carrier perspective, ie Royal Mail. It does not matter if a customer enters a postal code with or without the space, your package will still go through their sorting, which you can compare to the wildcard, and arrive at the correct destination.

The backwards compatibility consequences of a change like this as Barry also pointed out would also be immense, store owners have learned to use it the way it operates atm and if you now all of a sudden roll out changes affecting the default behaviour it would cause issues on a lot of stores.

Yes, adding a flag could overcome the backwards compatibility issue, but at the cost of making the interface and wildcard functionality more complicated.

I am going to close this as a won't implement, but want to also understand what the exact issue is you are experiencing with a match like this? If it is matching on postcode from different countries then you can overcome that by just set up different zones for each country you are experiencing the issue with. Ie if you happen to have a world wide zone rather remove UK and NZ from there and setup different zones for them.
