### ISSUE TITLE
[Enhancement]: Trigger Vanilla Javascript Events instead of jQuery only

### ISSUE THREAD

**Issue by gdarko** [woothemes/woocommerce#36809]
### Describe the solution you'd like

Hello,

We ditched jQuery from our plugins however, plugins like WooCommerce still only .trigger() events with jQuery and does not with native Javascript, which makes efforts to remove jQuery dependency from our code difficult.

Is it possible to add Javascript events too when triggering a jQuery event? One such example is: woocommerce_variations_loaded but there are a lot of other events that you are triggering with jQuery and not with native JS.

Thanks,
Best Regards,
Darko

### Describe alternatives you've considered

Maybe writing a pull request to add this compatibility?

**Comment by lkraav** [comment]
There are many "vanilla" efforts ongoing, such as https://github.com/woocommerce/woocommerce/pull/36332/

Every PR helps. These are not entirely trivial conversions.

**Comment by barryhughes** [comment]
Thanks! In general, I think this is also something for us to aim at. However, it is not something we can currently prioritize.

**Comment by nerrad** [comment]
Given the broad nature of the request in this issue, we will not be prioritizing a refactor of this scale. Even if we implemented triggering of the events in vanilla JS in existing files, jQuery would still be loaded unless we remove the dependency on jQuery in the scripts themselves. 

Our current investment is on utilizing newer APIs from WordPress (such as the Interactivity API) for building interactive experiences on the frontend.
