### ISSUE TITLE
[Enhancement]: Check if Note is already in the database in `possibly_add_note()`

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#36808]
### Describe the solution you'd like

[`possibly_add_note()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Notes/NoteTraits.php#L82-L90) in the NotesTrait.php seems like it could be more efficient if `can_be_added()` was checked first? Or pehraps just `note_exists()` ?

Looks like `get_note()` is called a few times (both in `possibly_add_note()` then again in `can_be_added()` and that can have some queries or who know what attached to it that are unnecessary if the note already exists. 

### Describe alternatives you've considered

Overriding `possibly_add_note()` in every Note I make. Seems redundant unless I've misunderstood how Notes work... which is entirely possibly given there's almost no docu on them... hint hint.

**Comment by barryhughes** [comment]
Leaving for Ghidorah/Mothra input.

**Comment by chihsuan** [comment]
> [possibly_add_note()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Notes/NoteTraits.php#L82-L90) in the NotesTrait.php seems like it could be more efficient if can_be_added() was checked first? Or pehraps just note_exists() ?

Closing this issue as we already added `can_be_added` check in `possibly_add_note` method. If I misunderstood the issue, please feel free to reopen it. Thanks!

https://github.com/woocommerce/woocommerce/blob/b4f1062783948211dd12b95547fe9c23a64e4179/plugins/woocommerce/src/Admin/Notes/NoteTraits.php#L82-L90
