### ISSUE TITLE
Attached images not showing as attached in media library

### ISSUE THREAD

**Issue by ntindicator** [woothemes/woocommerce#36811]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When an image is attached to a Woocommerce product as either the main image or a gallery image it doesn't show as attached in the media library. The reason appears to be that the post_parent of the attachment post is not set when the image is attached to the product. To view this in the media library the list view needs to be selected, as it doesn't show in the thumbnail view. There is a column "Uploaded To" that shows whether or not the image is attached. If an image is attached to a standard Wordpress post it will show as attached, but if it's attached to a product it doesn't show as attached. It would make managing of large media libraries easier if the post_parent is set for the attachment post, as it would be possible to filter and delete unattached images more easily. 

### Expected behavior

The image should show as attached in the "Uploaded To" column of the list view of the media library.

### Actual behavior

The image shows as "(Unattached)" in the media library.

### Steps to reproduce

1. Add images from the media library to a Woocommerce product and save
2. View the images in the media library using the list view
3. Locate the attached images in the library and check the status in the "Uploaded To" column

### WordPress Environment ###

WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.17
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.6.7-MariaDB
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 22.44MB
Database Data Size: 14.48MB
Database Index Size: 7.96MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.27MB + Index: 0.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ebayaffinity_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ebayaffinity_itemspecific_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebayaffinity_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ebayaffinity_pushtoken: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebayaffinity_shiprules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebayaffinity_titlerules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_access: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_12: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_02: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_03: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_04: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_05: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_06: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_07: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_08: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_09: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_10: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_11: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2022_12: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2023_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2023_02: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_invalidations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_numeric_2021_12: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_02: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_03: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_04: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_05: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_06: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_07: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_08: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_09: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_10: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_11: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_12: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2023_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2023_02: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_brute_force_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_changes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_custom_dimensions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_goal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_locks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_logger_message: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_log_action: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_conversion: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_conversion_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_link_visit_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_profiling: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_visit: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_matomo_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_plugin_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_privacy_logdata_anonymizations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_report_subscriptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_segment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_sequence: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_site: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_site_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_site_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_tagmanager_container: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_release: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_version: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_tagmanager_tag: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_trigger: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_variable: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tracking_failure: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_twofactor_recovery_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_user_dashboard: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_language: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_token_auth: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.44MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 4.52MB + Index: 2.84MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 1183
custom_css: 1
customize_changeset: 4
elementor_library: 2
frm_form_actions: 1
frm_styles: 1
mailpoet_page: 1
nav_menu_item: 9
oembed_cache: 5
page: 20
post: 9
product: 289
revision: 735
shop_order: 29
vcv_templates: 1
wp_global_styles: 4
wpcf7_contact_form: 1
wpephpcompat_jobs: 22
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Elementor: by Elementor.com – 3.10.2
Matomo Analytics - Ethical Stats. Powerful Insights.: by Matomo – 4.13.3
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels: by WebToffee – 4.0.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Variation Swatches for WooCommerce: by CartFlows – 1.0.6
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.4.0
WooCommerce Payments: by Automattic – 5.4.0
WooCommerce: by Automattic – 7.3.0
Yoast SEO: by Team Yoast – 20.1
WP Mail SMTP: by WPForms – 3.7.0
WPForms Lite: by WPForms – 1.7.9.1

### Inactive Plugins (5) ###

Advanced Ads: by Thomas Maier
Advanced Ads GmbH – 1.39.4

Akismet Anti-Spam: by Automattic – 5.0.2
MailPoet: by MailPoet – 4.6.1
Under Construction: by WebFactory Ltd – 3.96
W3 Total Cache: by BoldGrid – 2.2.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /cart/
Checkout: #60 - /checkout/
My account: #61 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra Child
Version: 1.0.0
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.0.2
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-12 05:10:06 +11:00
Options: ✔
Notes: 91
Onboarding: completed

### WooCommerce Payments ###

Version: 5.4.0
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 350
Oldest: 2023-01-12 15:34:15 +1100
Newest: 2023-02-12 11:17:00 +1100

Pending: 7
Oldest: 2023-02-12 18:57:26 +1100
Newest: 2023-02-13 15:38:39 +1100

### Status report information ###

Generated at: 2023-02-12 11:43:39 +11:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @ntindicator,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.3.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference : 

https://user-images.githubusercontent.com/94531721/218460821-9f2a00ca-d3e3-464c-ba70-97a387d2e0c1.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
This issue will be addressed by #40076.

**Comment by ntindicator** [comment]
I'm still finding that images don't show as attached when they're attached to products via CSV upload. The results are inconsistent. In one upload the main image was showing as attached and all the gallery images were not showing as attached. In a smaller upload to correct some incorrect images, 2 out of 3 gallery images showed as attached and 1 was not. They are all attached to the products.
