### ISSUE TITLE
[Enhancement] [WIKI]: Grammar and spelling on the Database-Description page

### ISSUE THREAD

**Issue by knutsenm** [woothemes/woocommerce#36818]
### Describe the solution you'd like

On this page,
https://github.com/woocommerce/woocommerce/wiki/Database-Description

these sentences:
> WooCommerce also add some of it's own custom tables. These are listed below.

should read:
> WooCommerce also adds some of its own custom tables. These are listed below.

**Comment by samueljseay** [comment]
Thank you @knutsenm I've updated the grammar with your suggestion 🙇🏻
