### ISSUE TITLE
configuration.output has an unknown property 'jsonpFunction'

### ISSUE THREAD

**Issue by Hasna-svg** [woothemes/woocommerce#36813]
I am trying to create an extension. when I run pnpm start, I got the error:

```
'configuration.output has an unknown property 'jsonpFunction'.
I fixed it through adding  code  " defaultConfig.output.chunkLoadingGlobal = defaultConfig.jsonpFunction
delete defaultConfig.output.jsonpFunction" - in webpack.config.js file.
```
After that, while I doing pnpm start again I got the error

`TypeError: Cannot read properties of undefined (reading 'tap')`
Any options to fix it??

to create woocommerce extension

[screenshot](https://pasteimg.com/image/screenshot-from-2023-02-13-15-28-15.GhQaO)

**Comment by lsinger** [comment]
Hello @Hasna-svg,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. Please use [the Bug Report template here](https://github.com/woocommerce/woocommerce/issues/new/choose).
