### ISSUE TITLE
[Enhancement]: Allow searching by users/customers phone

### ISSUE THREAD

**Issue by exonianp** [woothemes/woocommerce#36810]
### Describe the solution you'd like

We tend to get quite a lot of phone orders. 

We have tried various plugins but there is an inherent issue that rests on the default search of customers: the inability to search based on the customers phone number. 

So for repeat phone customers  or even for customers who want to learn about their order but dont have their order number handy, it will be great if we can search based on the telephone field. 

### Describe alternatives you've considered

https://wordpress.org/support/topic/search-user-by-cell/

https://woocommerce.com/products/phone-orders-payments/

**Comment by barryhughes** [comment]
Thanks, it's a good suggestion. 

✍🏼 For those who are interested in temporary solutions (besides those listed in the opening post), you may wish to explore the `woocommerce_shop_order_search_fields` filter hook which makes it possible to adjust the fields used during order search operations).

**Comment by infowprobo** [comment]
Hi @laurendavissmith,

Please assign this task to me. I am willing to start this task. 

Thank You,

**Comment by infowprobo** [comment]
Hi @nielslange,

Please remove my this account and assign the task to my other account that is @alishanvr.

Thank You,

**Comment by alishanvr** [comment]
Hi @nielslange,

Please assign this to me.

Thank You!

**Comment by nielslange** [comment]
Thanks for reaching out, @alishanvr. I've unassigned your other account `infowprobo` and assigne this account `alishanvr`.

**Comment by alishanvr** [comment]
I have few questions as follows:

1. From where the user/customer will search their Orders by providing the phone number?
- Do we need to create an input field in my account page for searching the orders?
- And I have the same question is for the admin?

Thank you,

**Comment by alishanvr** [comment]
What I think is that we need to filter the users on the WordPress admin side on the users.php.
So, admin can search the user by their phone number. 

Please confirm!
@nielslange

**Comment by exonianp** [comment]
Thank you for progressing with this. Usability wise it will be great if the default search also checks for the phone numbers (i.e. no need to add a separate input field).
Keep up the good work!

**Comment by louwie17** [comment]
> From where the user/customer will search their Orders by providing the phone number?

@exonianp would you be able to clarify this? Are you referring to the main search field `Search orders`?
Or did you want a separate filter for just phone numbers? Just like `registered user` filter?

I was able to filter orders by phone number using the `Search orders` search box.
![Screenshot 2023-04-19 at 1 25 01 PM](https://user-images.githubusercontent.com/2240960/233060763-fcec373a-1dbe-4baa-b440-7a6865e0287d.png)

> Do we need to create an input field in my account page for searching the orders?

I don't believe so, I believe this is only for the orders list screen.

> And I have the same question is for the admin?

Yes.

> What should we have to do if a user has multiple phone numbers.

The search should match any of the phone numbers that are part of the user.
In this case it would show any of the orders that match the user, if any phone number matches.

cc: @exonianp to confirm.

**Comment by louwie17** [comment]
Here is an example of me search by a phone number though and the correct order showing up:
![Screenshot 2023-04-19 at 1 31 04 PM](https://user-images.githubusercontent.com/2240960/233061957-1269de09-522a-447b-82aa-1e34ff7ea4dc.png)

But it does look like it has to match the format. If I update the number format to `902-999-9997` the search string `9029999997` doesn't match anything.

**Comment by exonianp** [comment]
I am referring to option 1. 
In default search does not include the phone number of the user or customer (clients that opted not to create a user account). 
I think it will suffice.

**Comment by louwie17** [comment]
Gotcha, so to summarize there may be two area's for improvement:
- Global order search should also match phone numbers of existing user accounts if linked to order ( it currently only matches phone numbers within the shipping or billing details, but not the linked user account ).
- Phone numbers should support any format? ( `9029999997` should still match `902-999-9997`) this one may be tricky the other way around, so we may only want to do this one way? (this one is probably optional as it wasn't originally mentioned).

**Comment by exonianp** [comment]
(When I had opened the ticket it was not matching the phone numbers at all of past shipping/billing details -it was only checking names and emails). I am not sure if this change was included in the interim. 

Yes it should match the phone numbers of existing clients - as they are stored in the database (no need to do regex for - etc). Just matching as it is saved by the user in the first place will do us.

Thank you.

**Comment by alishanvr** [comment]
Thank you for great discussion. 

I am on it.

**Comment by alishanvr** [comment]
@louwie17 

> Global order search should also match phone numbers of existing user accounts if linked to order ( it currently only matches phone numbers within the shipping or billing details, but not the linked user account ).

1. May you please provide more details, what do you mean when you said “but not the linked user account”.

2. I am able to search the user with the phone number provided in billing/shipping details with different formats as well.

Thank You,

**Comment by louwie17** [comment]
> May you please provide more details, what do you mean when you said “but not the linked user account”.

A user can have a phone number as part of there billing/shipping address in there user profile ( see first part of video ). That same user can be attached to an order `Customer` field. If the phone number in the order isn't set but is set in the user account the search doesn't match by the phone number.
Hope this and the video clarifies it.
Below is a video

https://user-images.githubusercontent.com/2240960/233083722-e944e8ec-68cb-49ca-bc12-8339ab1f9e38.mp4

> I am able to search the user with the phone number provided in billing/shipping details with different formats as well.

Great! I am not sure what I did for that to not work then, although I think this was of less concern anyhow :)
