### ISSUE TITLE
The en_GB translation for "Addresses" is missing

### ISSUE THREAD

**Issue by alexholsgrove** [woothemes/woocommerce#36823]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In `wc_get_account_menu_items()`, the label for `edit-address` is set to `_n( 'Address', 'Addresses', ( 1 + (int) wc_shipping_enabled() ), 'woocommerce' ),`. The singular "Address" text will display correctly in the my-account area, but if shipping is enabled, and hence _n() attempts to load the plural form of the word, then a blank string is returned.

### Expected behavior

The my account area should display the text "Addresses"

### Actual behavior

An empty string is returned, so no label is visible

### Steps to reproduce

Enable en_GB language
Enable WC Shipping
Visit my-account page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): REDACTED
Site address (URL): REDACTED
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.1.1s PHP/8.0.27
PHP Version: 8.0.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
(SecureTransport) OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.9
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wpress_
Total Database Size: 611.79MB
Database Data Size: 325.45MB
Database Index Size: 286.34MB
wpress_woocommerce_sessions: Data: 0.44MB + Index: 0.02MB + Engine InnoDB
wpress_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpress_woocommerce_order_items: Data: 9.52MB + Index: 3.52MB + Engine InnoDB
wpress_woocommerce_order_itemmeta: Data: 52.59MB + Index: 47.14MB + Engine InnoDB
wpress_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpress_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpress_woocommerce_shipping_zone_locations: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpress_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpress_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_actionscheduler_actions: Data: 13.52MB + Index: 13.61MB + Engine InnoDB
wpress_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_actionscheduler_logs: Data: 11.52MB + Index: 10.03MB + Engine InnoDB
wpress_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_comments: Data: 31.56MB + Index: 29.09MB + Engine InnoDB
wpress_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_options: Data: 2.22MB + Index: 0.06MB + Engine InnoDB
wpress_postmeta: Data: 139.69MB + Index: 124.39MB + Engine InnoDB
wpress_posts: Data: 17.52MB + Index: 9.06MB + Engine InnoDB
wpress_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpress_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wpress_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpress_usermeta: Data: 20.55MB + Index: 28.09MB + Engine InnoDB
wpress_users: Data: 2.52MB + Index: 2.08MB + Engine InnoDB
wpress_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpress_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpress_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpress_wc_customer_lookup: Data: 2.52MB + Index: 2.02MB + Engine InnoDB
wpress_wc_customer_lookup_meta: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
wpress_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_wc_order_product_lookup: Data: 7.52MB + Index: 7.06MB + Engine InnoDB
wpress_wc_order_stats: Data: 4.52MB + Index: 4.55MB + Engine InnoDB
wpress_wc_order_tax_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wpress_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wpress_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpress_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wpress_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpress_yoast_indexable: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wpress_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wpress_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpress_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpress_yoast_seo_links: Data: 0.11MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
attachment: 539
customize_changeset: 3
faq: 30
nav_menu_item: 55
page: 24
post: 329
product: 120
product_variation: 82
revision: 196
shop_order: 42235
shop_order_refund: 3
testimonial: 2
wp_block: 11
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (10) ###

Advanced Custom Fields PRO: by WP Engine – 6.0.7
Contact Form 7: by Takayuki Miyoshi – 5.7.3
Mailgun: by Mailgun – 1.9
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Google Analytics Pro: by SkyVerge – 1.13.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.2
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.8.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0
WooCommerce: by Automattic – 7.3.0
Yoast SEO: by Team Yoast – 20.0

### Inactive Plugins (3) ###

Pixel Manager for WooCommerce: by SweetCode – 1.30.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Rewrite Rules Inspector: by Automattic
Daniel Bachhuber – 1.3.1

### Must Use Plugins (1) ###

Must Use Plugins Autoloader: by WordPress Codex –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /basket/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Redacted
Version: (update to version 0 is available)
Author URL: REDACTED
Child Theme: ✔
Parent Theme Name: REDACTED
Parent Theme Version: – 0 is available
Parent Theme Author URL: REDACTED
WooCommerce Support: ✔

### Templates ###

Overrides: REDACTED/woocommerce/checkout/review-order.php
REDACTED/woocommerce/content-product.php
REDACTED/woocommerce/content-single-product.php
REDACTED/woocommerce/myaccount/my-account.php
REDACTED/woocommerce/myaccount/navigation.php
REDACTED/woocommerce/single-product/add-to-cart/variable.php

### WooCommerce Google Product Feed feeds ###

683414ba1d86ec28: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": Enabled
Expanded schema markup: -
Debug key: fa597a82-e1bd-4cc7-9309-4c747a1966b5

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed DB status ###

Database version: 16
Active database version: 16
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-GB): 5595 items

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-14 10:08:25 +00:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Complete: 50,629
Oldest: 2023-01-14 18:10:36 +0000
Newest: 2023-02-13 20:58:26 +0000

Failed: 1
Oldest: 2023-02-02 12:27:04 +0000
Newest: 2023-02-02 12:27:04 +0000

Pending: 1
Oldest: 2023-02-14 09:30:45 +0000
Newest: 2023-02-14 09:30:45 +0000

### Status report information ###

Generated at: 2023-02-13 22:38:16 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gilliancandle** [comment]
Hello, i am having the same problem. 

Here is my system statusreport: 

`
### WordPress Environment ###

WordPress address (URL): https://gilliancandle.be
Site address (URL): https://gilliancandle.be
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL_formal
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.23
PHP Post Max Size: 2 GB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.5.15-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Totale database grootte: 16.16MB
Database gegevens grootte: 13.67MB
Database index grootte: 2.49MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.08MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 5.19MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_gettext_nl_nl_formal: Data: 0.33MB + Index: 0.31MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
wp_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxcf_leads: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxcf_leads_detail: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_vxcf_leads_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 37
customize_changeset: 81
elementor_library: 1
flamingo_inbound: 5
language_switcher: 2
nav_menu_item: 15
oembed_cache: 1
page: 12
post: 5
product: 9
product_variation: 16
revision: 162
wp_global_styles: 2
wpcf7_contact_form: 1
wpforms: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Hostinger: door Hostinger – 1.0.2
All-in-One WP Migration: door ServMask – 7.70
Blocksy Companion: door CreativeThemes – 1.8.73
Contact Form 7: door Takayuki Miyoshi – 5.7.3
Contact Form Entries: door CRM Perks – 1.3.0
Elementor: door Elementor.com – 3.11.0
Essential Addons for Elementor: door WPDeveloper – 5.5.4
Flamingo: door Takayuki Miyoshi – 2.3
Flexible Shipping: door Octolize – 4.19.0
LiteSpeed Cache: door LiteSpeed Technologies – 5.3.2
Mollie Payments for WooCommerce: door Mollie – 7.3.5
Templately: door Templately – 2.1.0
Variation Swatches for WooCommerce: door CartFlows – 1.0.6
WooCommerce: door Automattic – 7.4.0
WP-Mail-SMTP: door WPForms – 3.7.0
WPForms Lite: door WPForms – 1.7.9.1

### Inactive Plugins (1) ###

Akismet Anti-Spam: door Automattic – 5.0.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #38 - /winkel/
Winkelwagen: #39 - /winkelwagen/
Afrekenen: #40 - /afrekenen/
Mijn account: #41 - /mijn-account/
Algemene voorwaarden: #42 - /algemene-voorwaarden/

### Theme ###

Name: Blocksy
Version: 1.8.73
Author URL: https://creativethemes.com
Child Theme: ❌ – Als u WooCommerce wijzigt op een hoofdthema dat u niet zelf gebouwd heeft
raden we u aan een subthema te gebruiken. Zie: Hoe maakt u een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: blocksy/woocommerce/cart/cart.php
blocksy/woocommerce/cart/mini-cart.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy/woocommerce/emails/customer-processing-order.php
blocksy/woocommerce/myaccount/my-account.php
blocksy/woocommerce/product-searchform.php
blocksy/woocommerce/single-product/tabs/tabs.php


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-15 11:51:13 +01:00
Options: ✔
Notes: 38
Onboarding: completed

### Action Scheduler ###

Afgerond: 186
Oldest: 2023-02-07 12:04:00 +0100
Newest: 2023-02-15 09:12:57 +0100

Mislukt: 1
Oldest: 2023-02-14 22:16:07 +0100
Newest: 2023-02-14 22:16:07 +0100

In afwachting: 6
Oldest: 2023-02-15 23:56:57 +0100
Newest: 2023-02-22 09:14:14 +0100


### Status report information ###

Generated at: 2023-02-15 10:06:38 +01:00
`

![Foutmelding mijn account](https://user-images.githubusercontent.com/125442099/218983046-ae1bd94b-85f8-4dcf-986c-5cf4f03be9d3.png)

**Comment by alexholsgrove** [comment]
@gilliancandle As a temporary solution, I added a CSS pseudo-element with the missing text. Far from ideal, as it doesn't handle the singular/plural text, but does at least work for now. Perhaps you can try something like this:

```
.woocommerce-MyAccount-navigation-link--edit-address a::after {
    content: 'Addresses';
}
```

You'll likely need some extra CSS to get that to display correctly for your theme, but hope it helps.

**Comment by gilliancandle** [comment]
> @gilliancandle As a temporary solution, I added a CSS pseudo-element with the missing text. Far from ideal, as it doesn't handle the singular/plural text, but does at least work for now. Perhaps you can try something like this:
> 
> ```
> .woocommerce-MyAccount-navigation-link--edit-address a::after {
>     content: 'Addresses';
> }
> ```
> 
> You'll likely need some extra CSS to get that to display correctly for your theme, but hope it helps.

Alex, it worked out perfect! Thank you so much for you help. Good luck with your problem fixing.

**Comment by kingyyyyyy** [comment]
Also missing for me. Guess it needs hotfixed.

**Comment by coreymckrill** [comment]
This appears to be the same issue as described in #36490. I'm going to close this in favor of that one.
