### ISSUE TITLE
Conflict with other FlexSliders in product content

### ISSUE THREAD

**Issue by jonmarkhall** [woothemes/woocommerce#36820]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If product content has other FlexSliders with thumbnail navigation besides the default WooCommerce product image gallery, some of the JavaScript functions in `plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js` may conflict with those other FlexSliders because the jQuery selectors used to locate the thumbnail navigation for the product image gallery are too broad and search the entire `.product` element for FlexSlider thumbnail navigation elements instead of being limited to the product gallery container.

### Expected behavior

Only the thumbnail navigation elements of the product gallery FlexSlider are targeted.

### Actual behavior

The first FlexSlider thumbnail navigation in the `.product` element is targeted, which may or may not correspond to the thumbnail navigation of the product gallery.

### Steps to reproduce

This behavior was reproduced on a user site using a third party plugin along with WooCommerce, and may not be reproducible with WooCommerce core alone.

### WordPress Environment

WordPress v6.1.1
WooCommerce v7.3.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@jonmarkhall Thanks for reporting this and submitting the related PR. Could you try and add some reproducible steps here, ideally with just WC Core, but even if it means installing another plugin? That'll really help with groking this issue and deciding if the solution in your PR is the way we want to proceed.

**Comment by jonmarkhall** [comment]
@coreymckrill here is a basic plugin I wrote to replicate the issue followed by replication steps:

```
/*
Plugin Name: Issue 36820 Demo
*/

add_action('init', function() {

	remove_all_actions('woocommerce_product_thumbnails');

	wp_enqueue_style('issue-36820-flexslider', 'https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.7.2/flexslider.min.css');

	add_shortcode('issue_36820', function() {
		echo('<div id="issue_36820" class="flexslider"><ul class="slides">');
		for ($i = 0; $i < 5; ++$i) {
			echo('<li data-thumb="https://s.w.org/style/images/about/WordPress-logotype-alternative.png">
					<img src="https://s.w.org/style/images/about/WordPress-logotype-alternative.png">
				</li>');
		}
		echo('</ul></div>');
		echo('<script>window.jQuery(document).ready(function($) { $(\'#issue_36820\').flexslider({ controlNav: \'thumbnails\' }); });</script>');
	});

});
```

Steps (after activating the above plugin):

1. Open a WooCommerce variable product with variation-based thumbnails (a good example is the Hoodie product from WooCommerce sample data).
2. Edit the product to add the `[issue_36820]` shortcode to the product description.
3. View the product; you should now have a product page with the product image gallery having the thumbnail nav disabled and a slider containing a WordPress logo image in the product description.
4. Change the variation attribute(s) to select a different variation. In the case of the Hoodie example product, change the Color dropdown and ensure that the Logo dropdown is set to "No".
5. The following should now be true: (a) the WooCommerce product gallery image has changed, and (b) the first image in the thumbnail nav belonging to the slider in the product description has also changed (incorrectly). This is because the JS code referenced in the pull request targets the first `.flex-direction-nav` in the product content rather than the `.flex-direction-nav` that actually belongs to the product gallery, meaning that in cases where the product gallery thumbnail nav is disabled and the product description has a `.flex-direction-nav` element, the latter element will be changed even though it is unrelated to the product gallery.

**Comment by coreymckrill** [comment]
As noted in the [associated PR](https://github.com/woocommerce/woocommerce/pull/36821#issuecomment-1439294980), the workaround here is that 3rd party instances of the flexslider script should specify a unique namespace in order to avoid collisions with the WC Core instance.
