### ISSUE TITLE
[Enhancement]: database prefix SSR concern

### ISSUE THREAD

**Issue by stoltzrx** [woothemes/woocommerce#36845]
### Describe the solution you'd like

A user came in with this request in the forums, and I would like clarity on whether this is a legitimate concern:

`1)does woocommerce think showing the prefix is a Security risk?`

`2) what is the use of it being in the rapport? Can you explain me why you need this specific prefix for support?`

Although this can be redacted/removed before sharing the SSR publicly, does this remain a security concern?

**Comment by peterfabian** [comment]
Hey, thanks for the question. We don't consider the database prefix to be sensitive information. If users prefer not to share it when getting support (or in any other context), they can remove it from the System Status Report before they share it with anyone. 

Please read more on https://www.wordfence.com/blog/2016/12/wordpress-table-prefix/

Cheers!

**Comment by peterfabian** [comment]
For future reference, please don't open issues related to security concerns in the public repository. Instead, please ping us in Slack when internal, or create an issue via https://hackerone.com/automattic/. 

Thanks!
