### ISSUE TITLE
Unexpected dark background color on badges

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#36849]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Badges in the task list header are showing with an unexpected dark background color.

### Expected behavior

![Screenshot 2023-02-16 at 08 15 17](https://user-images.githubusercontent.com/4344253/219225332-735ccb0b-5cba-4dcd-a40e-2dd7a1679105.png)

### Actual behavior

![Screenshot 2023-02-16 at 08 12 12](https://user-images.githubusercontent.com/4344253/219225022-36aba7bc-6a2e-44f6-954d-c49d6abfd8e7.png)

### Steps to reproduce

1. In trunk
2. Go to WooCommerce > Home
3. Observe that the badges background color are unexpected

### WordPress Environment

6.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Hey @woocommerce/mothra 👋   I’m seeing unexpected dark background color on task list badges in the trunk. I believe it’s related to https://github.com/woocommerce/woocommerce/pull/36517, which imports the `@wordpress/base-styles/colors.native`. Could someone take a look? 🙏 

I did a little digging. I found `colors.native` is for React Native and [`$gray-100`](https://github.com/WordPress/gutenberg/blob/b87e855fbc717e3a1badf8f6c2c802cb9d71cc1d/packages/base-styles/_colors.native.scss#L81) is different from the [_colors.scss](https://github.com/WordPress/gutenberg/blob/b87e855fbc717e3a1badf8f6c2c802cb9d71cc1d/packages/base-styles/_colors.scss#L16) that we previously used.

I think it also affects the new product editor.

![Screenshot 2023-02-16 at 08 28 28](https://user-images.githubusercontent.com/4344253/219226889-f0eed9f2-0b90-4b5f-bbee-5e3e39bd5c92.png)

cc @woocommerce/ghidorah

**Comment by rjchow** [comment]
I think it’s supposed to have been fixed https://github.com/woocommerce/woocommerce/pull/36718

**Comment by chihsuan** [comment]
Oh, I didn't notice that. Thanks @rjchow!
