### ISSUE TITLE
product variants - product fields with price

### ISSUE THREAD

**Issue by mojzesz777** [woothemes/woocommerce#36866]
product variants

if we add product fields with a price, the regular price is deleted and the promotional price is given as if it were higher.
![Screenshot_8](https://user-images.githubusercontent.com/109803899/217942654-72a6ae65-b991-4ce8-9ce7-220f188bc778.png)

**Comment by alexflorisca** [comment]
Is this specific to WooCommerce Blocks? I think this might be better asked in the main [WooCommerce repository](https://github.com/woocommerce/woocommerce)

**Comment by Aljullu** [comment]
Agree with @alexflorisca. Let's move this to WC core where it will be triaged by the relevant teams.

**Comment by rrennick** [comment]
@mojzesz777 This looks like it may be a translation issue as the price strings are placeholders in the translation string. Do you still see this in the latest version of WooCommerce? If so, switch your locale to US English then check to see if the prices are correct.
