### ISSUE TITLE
Pnpm install error

### ISSUE THREAD

**Issue by mytcdev** [woothemes/woocommerce#36884]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I tried with following steps:
```
nvm use

pnpm install
```
but it failed in `pnpm install` with ` ELIFECYCLE  Command failed with exit code 1.`

I also tried `pnpm run build` , it failed with `run failed: error preparing engine: found reference to unknown package: woocommerce/client/admin in task woocommerce/client/admin#turbo:build
`

more of the console message:

```
packages/js/date prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform. symfony/error-handler instead.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 107ms
└─ Failed in 336ms at /var/www/html/wp/wp-content/plugins/woocommerce-trunky/error-handler instead.
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform. symfony/error-handler instead.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 107ms
packages/js/explat prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform. symfony/error-handler instead.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 108ms
packages/js/navigation prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform. symfony/error-handler instead.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 92ms
packages/js/number prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform. symfony/error-handler instead.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 114ms
packages/js/tracks prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform.
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 98ms
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

Should be running out of the box.

### Actual behavior

I not using git pull to get the package, instead I downloaded the .zip to my local machine.
After extracted it and cd into the directory, I start with 
1. nvm use
2.  nvm install the required node js
3. pnpm install , then it failed here.

### Steps to reproduce

1. liked described above

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wp
Site address (URL): http://localhost/wp
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.1 - There is a newer version of WordPress available (6.1.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_CN
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.1.2-1ubuntu2.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.11-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 5.52MB
Database Data Size: 4.05MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vision: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
da_image: 4
page: 8
post: 1
product: 1
revision: 5
shop_coupon: 1
shop_order: 8
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Draw Attention: by N Squared – 2.0.4
Vision: by Avirtum – 1.5.5
WooCommerce Local Pickup Scheduler: by TC Kuan – 1.4.2
WooCommerce Local Pickup Time Select: by Tim Nolte – 1.4.2
WooCommerce: by Automattic – 7.2.2 (update to version 7.4.0 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-17 18:40:40 -03:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Complete: 22
Oldest: 2023-01-25 23:53:23 -0300
Newest: 2023-02-18 23:18:13 -0300

Pending: 1
Oldest: 2023-02-19 23:18:13 -0300
Newest: 2023-02-19 23:18:13 -0300

### Status report information ###

Generated at: 2023-02-18 23:18:32 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
@mytcdev if you're using a zip file rather than the git repo thats a use case we would not expect to work with the build scripts.

Whats your reason for not cloning the git repository? Is it a difficulty with mounting the plugin in your dev environment?

**Comment by mytcdev** [comment]
> @mytcdev if you're using a zip file rather than the git repo thats a use case we would not expect to work with the build scripts.
> 
> Whats your reason for not cloning the git repository? Is it a difficulty with mounting the plugin in your dev environment?

Ok, cloning the repo works. 
I doing it in a testing machine where I have limited access to the machine.

But there is another problem after successfully installed. I will open in a new ticket.
