### ISSUE TITLE
Re-Order

### ISSUE THREAD

**Issue by pete0011** [woothemes/woocommerce#36881]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The categorys are not going in the order you place them in. usually they would

### Expected behavior

they are just going in any random order

### Actual behavior

as above 

### Steps to reproduce

product catagories in woo then re arrange in order you like click apply and it does not work 

### WordPress Environment

No idea what this means

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
- I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- I can reproduce this bug consistently using the steps above.

@pete0011 Could you confirm you see this issue with the latest version of WooCommerce and all other plugins deactivated?

**Comment by pete0011** [comment]
Hi,

Which plugin is it and what do I need to do sorry?


Regards

*Pete*

Detail4Retail
Lytchetta House, 13 Freeland Park
Wareham Road, Poole
BH16 6FA

Tel: 0333 339 2279
Web: *Detail4Retail.net*
Web: Aromasuk.co.uk
One of our trading names is AromasUK, please mark all correspondents
including invoices and returns to Detail4Retail or Detail4Retail T/A
Aromas UK.

**Comment by rrennick** [comment]
> Which plugin is it and what do I need to do sorry?

Deactivate all plugins except the latest version of WooCommerce, switch to a default theme, and confirm you still see the issue.

**Comment by rrennick** [comment]
Closing for lack of feedback.
