### ISSUE TITLE
Reports (Old) exported CSV does not match data displayed in on-site reports.

### ISSUE THREAD

**Issue by Brianmitchtay** [woothemes/woocommerce#36898]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I know that the old reports are deprecated, so I'm not necessarily expecting a fix here. Still figured this may be worth noting.

When exporting report information from the `admin.php?page=wc-reports` page, for some values the exported information doesn't match what is displayed on the site's reports. 

For smaller shops who aren't looking to implement an entire tax season reporting/accounting workflow, the accuracy of these reports is vital, and differences/variations in these figures are perplexing, difficult if not impossible to track down, and erode trust in WooCommerce as a platform.

This issue was reported in 5952522-zen where a user is trying to get their tax reporting done for their small shop and have been vexed at how the WC reports (and the new Analytics) don't match their merchant account, or in this case of exports, don't even match their own data when exported.

### Expected behavior

Report exports should have the same values as the reports shown on the site.	

### Actual behavior

When exporting an annual report on a testing site of mine, `Net Sales Amount` and `Shipping Amount` differ from the amounts displayed in the on site report.
![PpNyI5.png](https://user-images.githubusercontent.com/45057772/220199905-1bb52e24-9338-473a-bbf1-84b5082899f9.png)

![CCF2bS.png](https://user-images.githubusercontent.com/45057772/220199919-83ac7b3d-8af5-4c74-89e0-f57d18435327.png)
Oddly enough, if you hover over the details for every month, and sum the values together, for Shipping amount, the on-site report adds up to match the CSV, despite displaying a different total number on the report sidebar.

For net sales amount, there are points on the chart which differ from the values in the CSV, but the difference in values does not add up to equal the difference shown between the reports.

I've taken considerable time exploring individual orders to try and ascertain what could be causing this disconnect between the reports and the export of the reports, and have yet to isolate a specific issue that causes this, either on the customer's site or my own.

### Steps to reproduce

1. On a site with a history of orders, head to **WP Admin → WooCommerce → Reports**
2. Select a date range to view the values for that range
3. Note the values displayed
4. Export the same report
5. Note the values in the CSV may be different. In the case of myself and this user, `Shipping Amount` and `Net Sales Amount` in the export do not match the values on the site report.

### WordPress Environment

System Status Report
<details>
`
### WordPress Environment ###

WordPress address (URL): https://woolivetesttesttest.mystagingwebsite.com
Site address (URL): https://woolivetesttesttest.mystagingwebsite.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 37.53MB
Database Data Size: 25.15MB
Database Index Size: 12.38MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.39MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.03MB + Index: 0.67MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.14MB + Index: 0.45MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.22MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.31MB + Engine InnoDB
wp_premmerce_bundles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_premmerce_bundles_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wpstg_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 216
aw_workflow: 28
bookable_person: 2
bookable_resource: 11
csp_rules: 1
efw_fees: 5
enr_subsc_plan: 2
event_ticket: 23
follow_up_email: 4
mailpoet_page: 1
nav_menu_item: 8
oembed_cache: 1
page: 20
post: 1
product: 150
product_variation: 296
revision: 48
shipping_package: 3
shop_coupon: 37
shop_order: 299
shop_order_refund: 7
shop_subscription: 61
wcpf_item: 4
wcpf_project: 1
wc_booking: 23
wc_order_status: 12
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0 (update to version 7.4.0 is available)

### Inactive Plugins (109) ###

Akismet Anti-Spam: by Automattic – 5.0.2
AutomateWoo: by WooCommerce – 5.6.4
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.7
Backup Duplicator & Migration - WP STAGING: by WP-STAGING
WPStagingBackup – 2.11.0

Bookings Helper: by WooCommerce – 1.0.3
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.9.1
Bulk Edit Products, Prices & Attributes for Woocommerce: by ELEXtensions – 1.1.0
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 3.2.2
Customer Email Verification: by zorem – 1.1.3 (update to version 2.1 is available)
Custom Start Date For WooCommerce Subscriptions: by Launch & Sell – 1.3.7
Enable Standard PayPal for WooCommerce: by Vik Cheema – 1.0.0
Enhancer for WooCommerce Subscriptions: by FantasticPlugins – 3.6
Extra Fees for WooCommerce: by FantasticPlugins – 4.0
Facebook for WooCommerce: by Facebook – 3.0.11
Follow-Up Emails: by WooCommerce – 4.9.34 (update to version 4.9.36 is available)
Frequently Bought Together: by Premmerce – 1.0.2
Google Listings and Ads: by WooCommerce – 2.3.8
Homepage Control: by WooThemes – 2.0.3
Import Export Suite for WooCommerce: by WebToffee – 1.0.4 (update to version 1.1.3 is available)
Jetpack: by Automattic – 11.9-a.3
Loco Translate: by Tim Whitlock – 2.6.3
MailPoet: by MailPoet – 4.5.2
Meks Quick Plugin Disabler: by Meks – 1.0
Payment Reminder for WooCommerce: by SKROTRON – 1.0.7
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
Product Bundles - Bulk Discounts: by SomewhereWarm – 1.3.9
Product Bundles - Variation Bundles: by franticpsyx – 1.1.3
Product Filters for WooCommerce: by WooCommerce – 1.3.2 (update to version 1.4.1 is available)
Product Prices by User Roles for WooCommerce Pro: by Tyche Softwares – 1.6.0
Query Monitor: by John Blackbourn – 3.11.1
Role and Customer Based Pricing by Meow Crew: by Meow Crew – 1.3.0
Role Based Pricing for WooCommerce: by Addify – 1.6.3
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.6.2
Storefront Pricing Tables: by WooCommerce – 1.1.0
Storefront Product Hero: by WooThemes – 1.2.13
String Locator: by InstaWP – 2.6.1
TikTok: by TikTok – 1.0.12
Transients Manager: by WPBeginner – 2.0.3
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.4.4

User Role Editor: by Vladimir Garagulya – 4.63.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.36 (update to version 1.1.37 is available)
WooCommerce Additional Variation Images: by WooCommerce – 2.3.0
WooCommerce Advanced Notifications: by WooCommerce – 1.3.1 (update to version 1.4.1 is available)
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.9 (update to version 1.1.10 is available)
WooCommerce Affirm Gateway: by WooCommerce – 2.0.0 (update to version 2.0.1 is available)
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.3 (update to version 4.0.4 is available)
WooCommerce AvaTax: by SkyVerge – 1.17.0 (update to version 2.1.0 is available)
WooCommerce Back In Stock Notifications: by WooCommerce – 1.4.0 (update to version 1.4.3 is available)
WooCommerce Blocks: by Automattic – 9.2.0
WooCommerce Bookings: by WooCommerce – 1.15.75
WooCommerce Bookings Availability: by WooCommerce – 1.1.20
WooCommerce Box Office: by WooCommerce – 1.1.45 (update to version 1.1.48 is available)
WooCommerce Brands: by WooCommerce – 1.6.41 (update to version 1.6.43 is available)
WooCommerce Chained Products: by StoreApps – 2.11.0 (update to version 2.13.0 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.3 (update to version 1.7.8 is available)
WooCommerce Composite Products: by WooCommerce – 8.4.2 (update to version 8.7.1 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.13.0 (update to version 1.14.4 is available)
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.10.4 (update to version 3.11.0 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.5 (update to version 5.4.0 is available)
WooCommerce Deposits: by WooCommerce – 1.5.10 (update to version 2.1.2 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.6.0 (update to version 3.6.1 is available)
WooCommerce Force Sells: by WooCommerce – 1.1.30 (update to version 1.2.0 is available)
WooCommerce Gift Cards: by WooCommerce – 1.15.1
WooCommerce GoCardless Gateway: by WooCommerce – 2.5.3
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.25 (update to version 4.0.6 is available)
WooCommerce Mix and Match Products: by Kathy Darling – 1.12.0 (update to version 2.4.1 is available)
WooCommerce Multi-currency: by TIV.NET INC – 3.1.2 (update to version 3.2.2 is available)
WooCommerce One Page Checkout: by Automattic – 1.9.7 (update to version 2.2.0 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.6.0 (update to version 1.6.3 is available)
WooCommerce Order Status Logger: by @billrobbins – 0.1
WooCommerce Order Status Manager: by SkyVerge – 1.13.3 (update to version 1.14.0 is available)
WooCommerce Payments: by Automattic – 5.4.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.1 (update to version 2.0.2 is available)
WooCommerce PDF Invoices: by Andrew Benbow – 4.15.6 (update to version 4.17.2 is available)
WooCommerce PDF Watermark: by WooCommerce – 1.4 (update to version 1.5.1 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.8 (update to version 1.7.26 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.8.0 (update to version 1.9.0 is available)
WooCommerce Product Add-ons: by WooCommerce – 5.0.2 (update to version 6.0.4 is available)
WooCommerce Product Bundles: by WooCommerce – 6.17.3 (update to version 6.18.1 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.55 (update to version 1.10.56 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.71 (update to version 2.1.74 is available)
WooCommerce Shipment Tracking: by WooCommerce – 2.0.0 (update to version 2.1.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.2 (update to version 2.2.3 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.18 (update to version 2.5.0 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.8.0 (update to version 3.8.2 is available)
WooCommerce Smart Coupons: by StoreApps – 6.5.0 (update to version 7.2.0 is available)
WooCommerce Square: by WooCommerce – 3.5.0
WooCommerce Square Helper: by WooCommerce – 1.1
WooCommerce Store Credit: by Themesquad – 4.0.5 (update to version 4.2.4 is available)
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Subscriptions: by WooCommerce – 4.7.0 (update to version 4.8.1 is available)
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0
WooCommerce UPS Shipping: by WooCommerce – 3.2.38 (update to version 3.4.1 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.6.1 (update to version 4.6.2 is available)
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.6
WooCommerce Xero Integration: by WooCommerce – 1.7.48 (update to version 1.7.55 is available)
WPC Order Notes for WooCommerce: by WPClever – 1.4.2
WP Crontrol: by John Blackbourn & crontributors – 1.15.0
WP Mail Logging: by SendLayer – 1.10.5
WP phpMyAdmin: by Puvox.software – 5.2.0.7
WP Rollback: by GiveWP.com – 1.7.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bookshop
Version: 1.0.20
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.2 – 4.2.0 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-20 22:26:28 +00:00
Options: ✔
Notes: 78
Onboarding: completed

### Action Scheduler ###

Canceled: 6
Oldest: 2023-01-23 23:33:27 +0000
Newest: 2023-02-16 17:19:30 +0000

Complete: 1,867
Oldest: 2023-02-16 00:56:31 +0000
Newest: 2023-02-01 02:49:43 +0000

Failed: 72
Oldest: 2022-05-23 19:43:49 +0000
Newest: 2023-01-03 20:43:12 +0000

Pending: 24
Oldest: 2023-02-20 21:20:07 +0000
Newest: 2024-02-09 20:33:28 +0000

### Status report information ###

Generated at: 2023-02-20 21:19:27 +00:00
`
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> I know that the old reports are deprecated, so I'm not necessarily expecting a fix here.

@Brianmitchtay Thanks for creating the detailed description. You are correct, these reports are deprecated. We only address security issues and fatal errors in deprecated functionality. I'll close this issue as won't fix.
