### ISSUE TITLE
Undismissable notice

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#36913]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We're seeing reports of undismissable notices relating to updates of payment gateways. In particular WooCommerce Payments and eWay
* https://wordpress.org/support/topic/action-required-please-update-woocommerce-payments-2
* 39927407-hc
* 5948453-zen
* 5965665-zen
The notices that suggest updating are present even with the latest version. In one case, the user was prompted to update WooCommerce Payments and they aren't using WooCommerce Payment.

![PBWi5t.png](https://user-images.githubusercontent.com/2127470/220484253-f1c382ee-cdf2-4149-b8a6-260595998de5.png)
https://user-images.githubusercontent.com/2127470/220253850-f94c07be-1534-4a29-90de-754a9aa1cf48.png

Also see https://github.com/Automattic/woocommerce-payments/issues/5587 

### Expected behavior

That the dismiss button dismisses the notice.

### Actual behavior

The notice is often spurious so it shouldn't be there to begin with. It can not be dismissed.

### Steps to reproduce

Unclear

### WordPress Environment ###

WordPress address (URL): https://replaced.domain/
Site address (URL): https://replaced.domain/
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 800
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 60.29MB
Database Data Size: 46.39MB
Database Index Size: 13.90MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 4.52MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.98MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.50MB + Index: 0.53MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mepr_corporate_accounts: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_mepr_events: Data: 0.22MB + Index: 0.56MB + Engine InnoDB
wp_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_members: Data: 0.16MB + Index: 0.73MB + Engine InnoDB
wp_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mepr_subscriptions: Data: 0.02MB + Index: 0.30MB + Engine InnoDB
wp_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mepr_transactions: Data: 0.22MB + Index: 0.95MB + Engine InnoDB
wp_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 6.23MB + Index: 0.16MB + Engine InnoDB
wp_postmark_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 9.50MB + Index: 2.84MB + Engine InnoDB
wp_posts: Data: 13.14MB + Index: 0.30MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 2.52MB + Index: 0.70MB + Engine InnoDB
wp_shortpixel_queue: Data: 0.33MB + Index: 0.09MB + Engine InnoDB
wp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 2.50MB + Index: 2.92MB + Engine InnoDB
wp_users: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_wc_activecampaign: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 424
custom_css: 2
customize_changeset: 25
et_body_layout: 7
et_footer_layout: 2
et_header_layout: 3
et_pb_layout: 41
et_template: 27
et_theme_builder: 2
mailpoet_page: 1
memberpressgroup: 2
memberpressproduct: 16
memberpressrule: 1
nav_menu_item: 35
oembed_cache: 19
page: 54
post: 89
product: 24
product_variation: 11
revision: 390
shop_order: 73
shop_order_refund: 1
tec_tc_ticket: 6
ticket-meta-fieldset: 2
tribe_events: 11
tribe_organizer: 3
tribe_rsvp_attendees: 49
tribe_rsvp_tickets: 3
tribe_venue: 8
tribe_wooticket: 75
wp_block: 2
wp_global_styles: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

ActiveCampaign for WooCommerce: by ActiveCampaign – 2.0.2
ActiveCampaign: by ActiveCampaign – 8.1.10
Breeze: by Cloudways – 2.0.16
Divi Events Calendar: by Pee-Aye Creative – 2.6
Divi Modules Pro: by Divi Life – 1.2.1
Event Tickets Plus: by The Events Calendar – 5.6.6.1
Event Tickets: by The Events Calendar – 5.5.7
Filester - File Manager Pro: by Ninja Team – 1.7.7
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.87
MemberPress Active Campaign - Tags Version: by Caseproof
LLC – 1.0.10

MemberPress Corporate Accounts: by Caseproof
LLC – 1.5.30

MemberPress Divi Content Protection: by Caseproof
LLC – 1.0.8

MemberPress Importer: by Caseproof
LLC – 1.6.14

MemberPress WooCommerce Plus: by HappyPlugins – 1.2.8
MemberPress Pro: by Caseproof
LLC – 1.10.4

ActiveCampaign Postmark (Official): by Andrew Yates & Matt Gibbs – 1.17.2
Rank Math SEO: by Rank Math – 1.0.108
ShortPixel Image Optimizer: by ShortPixel - Convert WebP/AVIF & Optimize Images – 5.2.0
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.36
Event Tickets Extension: Members Only Tickets: by The Events Calendar – 1.0.1
The Events Calendar: by The Events Calendar – 6.0.9
The Events Calendar Extension: Divi Compatibility: by Modern Tribe
Inc. – 1.2.1

UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.22.24

Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
WooCommerce Xero Integration: by WooCommerce – 1.7.49
WooCommerce: by Automattic – 7.4.0
WP-Memory-Usage: by Bernhard Kux – 1.2.8
WP Migrate Lite: by WP Engine – 2.6.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.12

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.17.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #65 - /events-training/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #301 - /my-account/
Terms and conditions: #94 - /terms-conditions/

### Theme ###

Name: CBNZ Child Theme
Version: 1.0.0
Author URL:
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.20.0
Parent Theme Author URL: http://www.elegantthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-22 02:28:42 +13:00
Options: ✔
Notes: 80
Onboarding: completed

### Action Scheduler ###

Complete: 2,962
Oldest: 2023-01-25 10:26:48 +1300
Newest: 2023-02-21 17:56:45 +1300

Failed: 4
Oldest: 2022-10-18 10:34:07 +1300
Newest: 2023-02-16 11:22:58 +1300

Pending: 2
Oldest: 2023-02-22 09:55:51 +1300
Newest: 2023-02-23 10:53:22 +1300

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by EjayhanFernandes** [comment]
Experienced here as well: 33629914-hc

**Comment by barryhughes** [comment]
Changing the focus, *seems* like a RemoteInbox issue.

**Comment by pmcpinto** [comment]
@octaedro can you take a look at this during the upcoming days?

**Comment by thisissandip** [comment]
6235645-zen

**Comment by CGA8C** [comment]
The Merchant in 6359475-zen reports that they still have an undismissable RIN related to the recent Stripe SIRT, after they've updated to 7.8.0.

**Comment by robcain** [comment]
i'd like to report i too have this same issue, even after updating to woo 7.8.0.

**Comment by pmcpinto** [comment]
@octaedro @nathanss is it possible to investigate what's happening? Thanks!

**Comment by addedlovely** [comment]
I see 'Unhandled Promise Rejection: Error' logged in the console after clicking dismiss, on line 115 of store-alerts.js

Latest WooCommerce version, across multiple sites.

**Comment by nathanss** [comment]
@robcain @addedlovely

This is hard to reproduce. I suspect that there may be inconsistency in the database. In that case, an error should be occurring on the endpoint that is supposed to update the note and note actions.

If someone could provide the following information, I think it would help the investigation:

Run the following SQL commands and provide the results:
```sql
SELECT * FROM wp_wc_admin_notes WHERE title = '<title of the note that is appearing>';  /*example title: 'Action required: Security update for WooCommerce Payments' */
``` 
With the note_id from the previous result:

```sql
SELECT * FROM wp_wc_admin_note_actions where note_id = <note_id>
```

Also, there should be two XHR requests when you click 'Dismiss', one to `/wp-json/wc-analytics/admin/notes/{note_id}/action/{action_id}?_locale=user` and other to `/wp-json/wc-analytics/admin/notes/86?_locale=user`. Can you also provide the response from these requests? Thanks a lot.

**Comment by addedlovely** [comment]
@nathanss When clicking dismiss I see the following 404 network request:

URL: https://www.domain.co.uk/wp-json/wc-analytics/admin/notes/340/action/undefined?_locale=user
Status: 404
Source: Network
Initiator: api-fetch.min.js:2:4557

The href on the button itself is set to:
https://www.domain.co.uk/wp-admin/#

For the 1st MySQL query:

<img width="1576" alt="wp_wc_admin_notes" src="https://github.com/woocommerce/woocommerce/assets/565669/4b1c0351-88bc-4fe6-931f-b5d8236085e8">

For the 2nd:

<img width="1308" alt="wp_wc_admin_note_actions" src="https://github.com/woocommerce/woocommerce/assets/565669/971f15cd-7f73-482a-8ecf-0122e2d7d1bf">

I assume status should not be 'actioned' for the 'dismiss' button.

Happy to assist further.

**Comment by nathanss** [comment]
@addedlovely Thanks a lot! 

The request is probably failing because it's providing an `undefined` action id. Let's try to find out why this is happening. 

Can you refresh WooCommerce > Home and search the fetch request similar to `/notes?page=1&per_page=25&type=error%2Cupdate&status=unactioned&_locale=user` in the network tab and send the response?

It also seems that the action_id numbers are really high. Can you check how many rows you have in the `wc_admin_note_actions` table?

> I assume status should not be 'actioned' for the 'dismiss' button.

That part is correct. This is the status that the note should transition to when the action is executed.

By the way, for those looking for a workaround, setting `status` to `actioned` in the `wp_wc_admin_notes` (not the `wp_wc_admin_note_actions` table) row should get rid of the message.

**Comment by addedlovely** [comment]
@nathanss `/notes` endpoint output is below:

`[{
	"id": 340,
	"name": "woocommerce-WCstripe-May-2023-updated-needed",
	"type": "update",
	"locale": "en_US",
	"title": "Action required: Security update of WooCommerce Stripe plugin",
	"content": "<strong>Your store requires a security update for the WooCommerce Stripe plugin<\/strong>. Please update the WooCommerce Stripe plugin immediately to address a potential vulnerability.",
	"content_data": {},
	"status": "unactioned",
	"source": "woocommerce.com",
	"date_created": "2023-06-01T21:57:30",
	"date_reminder": null,
	"is_snoozable": false,
	"actions": [{
		"name": "woocommerce-WCStripe-May-2023-updated-needed-Plugin-Settings",
		"label": "See available updates",
		"query": "https:\/\/www.domain.co.uk\/wp-admin\/plugins.php?plugin_status=all",
		"status": "unactioned",
		"actioned_text": "",
		"nonce_name": null,
		"nonce_action": null,
		"url": "https:\/\/www.domain.co.uk\/wp-admin\/plugins.php?plugin_status=all"
	}, {
		"name": "woocommerce-WCStripe-May-2023-updated-needed-Plugin-Settings-dismiss",
		"label": "Dismiss",
		"query": "#",
		"status": "actioned",
		"actioned_text": "",
		"nonce_name": null,
		"nonce_action": null,
		"url": "https:\/\/www.domain.co.uk\/wp-admin\/#"
	}],
	"layout": "plain",
	"image": "",
	"is_deleted": false,
	"is_read": false,
	"date_created_gmt": "2023-06-01T20:57:30",
	"date_reminder_gmt": null,
	"_links": {
		"self": [{
			"href": "https:\/\/www.domain.co.uk\/wp-json\/wc-analytics\/admin\/notes\/340"
		}],
		"collection": [{
			"href": "https:\/\/www.domain.co.uk\/wp-json\/wc-analytics\/admin\/notes"
		}]
	}
}, {
	"id": 5,
	"name": "wc-update-db-reminder",
	"type": "update",
	"locale": "en_US",
	"title": "WooCommerce database update done",
	"content": "WooCommerce database update complete. Thank you for updating to the latest version!",
	"content_data": {},
	"status": "unactioned",
	"source": "woocommerce-core",
	"date_created": "2020-04-17T05:56:07",
	"date_reminder": null,
	"is_snoozable": false,
	"actions": [{
		"id": 119793,
		"name": "update-db_done",
		"label": "Thanks!",
		"query": "https:\/\/www.domain.co.uk\/wp-admin\/admin.php?page=wc-settings&wc-hide-notice=update",
		"status": "actioned",
		"actioned_text": "woocommerce_hide_notices_nonce",
		"nonce_action": "woocommerce_hide_notices_nonce",
		"nonce_name": "_wc_notice_nonce",
		"url": "https:\/\/www.domain.co.uk\/wp-admin\/admin.php?page=wc-settings&wc-hide-notice=update&_wc_notice_nonce=04280d62d1"
	}],
	"layout": "plain",
	"image": null,
	"is_deleted": false,
	"is_read": true,
	"date_created_gmt": "2020-04-17T04:56:07",
	"date_reminder_gmt": null,
	"_links": {
		"self": [{
			"href": "https:\/\/www.domain.co.uk\/wp-json\/wc-analytics\/admin\/notes\/5"
		}],
		"collection": [{
			"href": "https:\/\/www.domain.co.uk\/wp-json\/wc-analytics\/admin\/notes"
		}]
	}
}]
`

Re the 'wc_admin_note_actions' has 189 records and and 'wc_admin_notes' has 155 records. Note this is not a new site, but has been running for at least 4-5 years.

Not sure if it's significant, but also to note the markup for the buttons on the note are both `<a>` links, but looks like in [/woocommerce-admin/client/layout/store-alerts/index.js](https://github.com/woocommerce/woocommerce/blob/f5a601d6e1427f774df8c709afd1a81fbddb3f61/plugins/woocommerce-admin/client/layout/store-alerts/index.js#LL73C5-L92C14) the function outputs a `<button>`

**Comment by nathanss** [comment]
@addedlovely Thanks for the information. There is a problem with the response from this endpoint. It should include the action_ids, which are 119763 and 119764, in your case. They are not being included, that's why the subsequent call to trigger the action has `undefined` in it. We were unable to reproduce this issue in our environments. In my tests, the ids for each action were included.  It may be related to a different behavior in a specific component, like PHP version, or the database version, or even a plugin conflict. At this point I can't be sure.

Can you provide your System Status Report (from WooCommerce > Status)?

**Comment by addedlovely** [comment]
@nathanss Thanks for the follow up, Is there a private way to send that to you?

Am experiencing this across multiple sites, on different hosting environments. In terms of commonality of plugins, ACF, Yoast SEO, WordFence, Classic Editor, WooCommerce and WP Rocket would be common across all. Will try and setup a development copy and disable all plugins.

**Comment by nathanss** [comment]
@addedlovely If you could provide me access to one of those environments (preferably a staging one, where it could be possible and harmless to perform tests), it would be great. You can use [QuickForget](https://quickforget.com/) for sensitive information and then drop me an email at nathan dot schneider at automattic dot com with the secret. Thanks a lot for collaborating!

**Comment by stuartduff** [comment]
I have a customer with WP v6.2.2, WC v7.8.1, Stripe v7.4.1 and PHP 8.1.18 installed that is also still unable to dismiss the Stripe vulnerability notice.

Request: 6463384-zen

I could also replicate this behaviour on one of my test sites that use WP v6.2.2, WC v7.8.1, and Stripe v7.4.1. The screenshots below are taken from my test site.

![Screen Shot on 2023-06-28 at 15:50:20](https://github.com/woocommerce/woocommerce/assets/1190565/1ca27f71-63d7-4c32-a77b-a3235fc5d9e2)

![Screen Shot on 2023-06-28 at 15:57:44](https://github.com/woocommerce/woocommerce/assets/1190565/74a4bd79-c83a-4134-93a0-51cbcc4bd643)

**Comment by paulostp** [comment]
Another report of this issue 6466877-zen

**Comment by stoltzrx** [comment]
6476733-zen

**Comment by stoltzrx** [comment]
6478417-zen

**Comment by Babylon1999** [comment]
zd-6478569

**Comment by paulostp** [comment]
Another report 6429738-zen

**Comment by darcie** [comment]
6531286-zen, let them know to look out for the fix in a future release.

**Comment by theabhig** [comment]
Looks like the same issue in 6528033-zen. Letting them know to look out for a future fix.

**Comment by stoltzrx** [comment]
Same issue in 6559177-zen. Have also let them know to look out for a future fix.

**Comment by maxlaf** [comment]
6573634-zen, let them know to look out for the fix in a future release.

**Comment by addedlovely** [comment]
Any update on when this is getting released, makes WooCommerce look very buggy with such a basic issue. Thanks!

**Comment by nathanss** [comment]
@addedlovely This will be released as part of 8.0 in August 8

**Comment by thisissandip** [comment]
6596322-zen

**Comment by NathalyaVides** [comment]
6608605-zen

**Comment by senff** [comment]
6614260-zen

**Comment by edwinho89** [comment]
6621632-zd-a8c

**Comment by salarion** [comment]
i have the same notice,
why is this marked as closed?

**Comment by addedlovely** [comment]
@salarion update WooCommerce the fix is included in the latest version.

**Comment by salarion** [comment]
> @salarion update WooCommerce the fix is included in the latest version.

I did but it was still there.

I'll test a bit later again and see. Will update this comment.

Ty

**Comment by salarion** [comment]
> > @salarion update WooCommerce the fix is included in the latest version.
> 
> I did but it was still there.
> 
> I'll test a bit later again and see. Will update this comment.
> 
> Ty

Ok so, i've updated the stripe plugin and the woocomerce plugin. the notifiction is still there. 
Any advice?

**Comment by antonyjsmith** [comment]
@salarion The issue persisted on WP 6.2.2 despite Stripe and Woocommerce being the latest but updating to 6.3 seems to have resolved

**Comment by salarion** [comment]
> @salarion The issue persisted on WP 6.2.2 despite Stripe and Woocommerce being the latest but updating to 6.3 seems to have resolved

I have installed 6.3WP

**Comment by addedlovely** [comment]
@nathanss This issue still persists for me but only with the 'Coupon management has moved!' message - running WordPress and WooCommerce latest versions. 

Upon clicking 'Remove legacy coupon menu', it's logging the following error in the console.

```
[Error] Unhandled Promise Rejection: Error
	(anonymous function) (store-alerts.js:1:2147)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

Related issues:
https://github.com/woocommerce/woocommerce/issues/38562
https://github.com/woocommerce/woocommerce/issues/37677

**Comment by csmcneill** [comment]
6732283-zen is running into this issue with the USPS Hazmat RIN that is related to [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038). They are running the latest stable version of WooCommerce (8.0.2) and WordPress (6.3.0), but they say:

> It will leave and then come back. Sometimes it won't let me dismiss it. It will just let me click it

Reopening.
