### ISSUE TITLE
[Enhancement]: Update grouped product template to remove linked products

### ISSUE THREAD

**Issue by rachelmcr** [woothemes/woocommerce#36923]
### Describe the solution you'd like

In the mobile app we're adding support for creating more product types with a template, using the `/onboarding/tasks/create_product_from_template` [endpoint](https://github.com/woocommerce/woocommerce/blob/7fdd0f496f5488bed4f3ad3404022980dcded2f7/plugins/woocommerce/src/Admin/API/OnboardingTasks.php#L350-L381). However, we noticed an issue with the current [grouped product template](https://github.com/woocommerce/woocommerce/blob/7fdd0f496f5488bed4f3ad3404022980dcded2f7/plugins/woocommerce/src/Admin/API/Templates/grouped_product.csv):

In the template data, it includes the following slugs as grouped (linked) products: `woo-hoodie-with-logo, woo-tshirt, woo-beanie`. If those products don't already exist, they are created as import placeholders (with an `importing` product status). These don't appear in the product list in wp-admin but they do increase the product count there.

Notice that there's a single product in the product list here, but the product count is 4 (including the 3 import placeholder products with the slugs listed above):

![image](https://user-images.githubusercontent.com/8658164/220870533-597c0c06-426d-4807-8ad1-33f81abadc44.png)

We've worked around this in the app (https://github.com/woocommerce/woocommerce-ios/pull/8940) but ideally the template data could be updated to avoid this situation. Probably it would be best to remove those linked product slugs from the template data entirely.

**Comment by barryhughes** [comment]
Applying the React Admin label: based on the code history, this looks like Ghidorah territory—but, if that's wrong, please feel free to re-route as needed.

**Comment by chihsuan** [comment]
We've removed the linked products and other attributes in https://github.com/woocommerce/woocommerce/pull/38343.
