### ISSUE TITLE
"Address" label in My Account area empty when the Site Language is set to English (United Kingdom).

### ISSUE THREAD

**Issue by BigSalami** [woothemes/woocommerce#36939]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The text for the _Address_ label in the My Account area is blank when the WordPress _Site Language_ is set to _English (United Kingdom)_.

**The issue:**._ 
HTML for the label renders, but the text is missing.
![image](https://user-images.githubusercontent.com/55036615/220949847-a678521f-3aa1-4a4f-a03d-75e5cd4285bf.png)

When I switch the _Site Language_ to _English (United States)_, the text is visible.
![image](https://user-images.githubusercontent.com/55036615/220950255-7425b4b2-9501-4e32-b0f5-63e2c6159979.png)

After some research, it seems that the language file may be missing an entry for the English UK.

### Expected behavior

The text for the label should be present, as it is for _English (United States)_
![image](https://user-images.githubusercontent.com/55036615/220950255-7425b4b2-9501-4e32-b0f5-63e2c6159979.png)

This is the HTML for _English (United States)_
```
<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--edit-address is-active">
    <a href="https://staging2.gardenimports.co.uk/shop/my-account/edit-address/">Addresses</a>
</li>
```

### Actual behavior

HTML for the label renders, but the text is missing.
![image](https://user-images.githubusercontent.com/55036615/220949847-a678521f-3aa1-4a4f-a03d-75e5cd4285bf.png)

This is the HTML for _English (United Kingdom)_
```
<li class="woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--edit-address is-active">
    <a href="..."></a>
</li>
```

### Steps to reproduce

Set WordPress _Site Language_ to _English (United Kingdom)_ in /wp-admin/options-general.php
Visit /my-account/ and view the _Address_ label.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.gardenimports.co.uk
Site address (URL): https://www.gardenimports.co.uk
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 7000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: pcp_
Total Database Size: 224.23MB
Database Data Size: 161.33MB
Database Index Size: 62.90MB
pcp_woocommerce_sessions: Data: 19.05MB + Index: 1.02MB + Engine InnoDB
pcp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pcp_woocommerce_order_items: Data: 0.48MB + Index: 0.19MB + Engine InnoDB
pcp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
pcp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pcp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_actionscheduler_actions: Data: 15.02MB + Index: 7.86MB + Engine InnoDB
pcp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_actionscheduler_logs: Data: 4.02MB + Index: 5.03MB + Engine InnoDB
pcp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_afwc_hits: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
pcp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_afwc_referrals: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
pcp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
pcp_automatewoo_customers: Data: 0.22MB + Index: 0.56MB + Engine InnoDB
pcp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pcp_automatewoo_guests: Data: 0.14MB + Index: 0.27MB + Engine InnoDB
pcp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pcp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
pcp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pcp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_commentmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
pcp_comments: Data: 5.52MB + Index: 5.83MB + Engine InnoDB
pcp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_mailchimp_carts: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
pcp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_options: Data: 4.23MB + Index: 0.09MB + Engine InnoDB
pcp_packlink_entity: Data: 16.52MB + Index: 0.00MB + Engine InnoDB
pcp_postmeta: Data: 36.47MB + Index: 25.84MB + Engine InnoDB
pcp_posts: Data: 15.23MB + Index: 3.25MB + Engine InnoDB
pcp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
pcp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_sliders: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
pcp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_slides: Data: 1.11MB + Index: 0.02MB + Engine InnoDB
pcp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_sgs_log_events: Data: 17.02MB + Index: 0.00MB + Engine InnoDB
pcp_sgs_log_visitors: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
pcp_termmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
pcp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
pcp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pcp_usermeta: Data: 3.50MB + Index: 3.98MB + Engine InnoDB
pcp_users: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
pcp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pcp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
pcp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wc_customer_lookup: Data: 0.31MB + Index: 0.22MB + Engine InnoDB
pcp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wc_order_bundle_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
pcp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_wc_order_product_lookup: Data: 0.28MB + Index: 0.25MB + Engine InnoDB
pcp_wc_order_stats: Data: 0.31MB + Index: 0.36MB + Engine InnoDB
pcp_wc_order_tax_lookup: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
pcp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
pcp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
pcp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pcp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
pcp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.14MB + Engine InnoDB
pcp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pcp_yoast_indexable: Data: 3.38MB + Index: 0.38MB + Engine InnoDB
pcp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
pcp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pcp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pcp_yoast_seo_links: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
pcp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_acr_carts: 3
addify_acr_emails: 1
addify_acr_logs: 6
attachment: 783
aw_workflow: 1
awb_off_canvas: 2
cwginstocknotifier: 1544
fusion_element: 14
fusion_form: 3
fusion_tb_layout: 8
fusion_tb_section: 12
fusion_template: 1
nav_menu_item: 215
oembed_cache: 32
page: 28
post: 1
product: 143
product_variation: 97
revision: 278
shop_coupon: 21
shop_order: 3961
shop_order_refund: 173
woocustomemails: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

ManageWP - Worker: by GoDaddy – 4.9.16
Affiliate For WooCommerce: by StoreApps – 6.3.1
AutomateWoo: by WooCommerce – 5.6.0
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 3.2
Add-on: Ban Emails - Back In Stock Notifier for WooCommerce: by codewoogeek – 1.0
Back In Stock Notifier for WooCommerce Add-on: Custom CSS: by codewoogeek – 1.3
Add-on: Export CSV - Back In Stock Notifier for WooCommerce: by codewoogeek – 1.1
Add-on: Unsubscribe - Back In Stock Notifier for WooCommerce: by codewoogeek – 1.2
Email Address Encoder ✪: by Till Krüss – 0.3.10
Avada Builder: by ThemeFusion – 3.9.2
Avada Core: by ThemeFusion – 5.9.2
Mailchimp for WooCommerce: by Mailchimp – 2.8
Packlink PRO Shipping: by Packlink Shipping S.L. – 3.2.13
Slider Revolution: by ThemePunch – 6.6.3
Search Exclude: by QuadLayers – 1.3.1
SiteGround Optimizer: by SiteGround – 7.3.1
SiteGround Security: by SiteGround – 1.4.1
Woo Custom Emails Per Product: by Alex Mustin – 2.2.9
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.3
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
WooCommerce Multi-currency: by TIV.NET INC – 3.2.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.4.0
WooCommerce Product Bundles: by WooCommerce – 6.18.1
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.8.3
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0
WooCommerce: by Automattic – 7.4.0
Yoast SEO: by Team Yoast – 20.1
WP Mail SMTP: by WPForms – 3.7.0

### Dropin Plugins (1) ###

object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #1176 - /shop/
Basket: #1177 - /shop/basket/
Checkout: #1178 - /shop/checkout/
My account: #1179 - /shop/my-account/
Terms and conditions: #1186 - /terms-conditions/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.9.2
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce Google Product Feed feeds ###

google: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -
googlelocalproductinventory: Google merchant centre local product inventory feed
  Type: googlelocalproductinventory
  Category filter: -
  Categories: -
5a7e3965d83c25ac: Google merchant centre product review feed
  Type: googlereview
  Category filter: -
  Categories: -
  Limit: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": -
Expanded schema markup: -
Debug key: 31245018-07ad-4e42-8483-2c41012c91fd

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Product description: Main product description (full preferred) plus variation description
Brand: 
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: 
Google Product Category: 
Size system: Defaults to "UK".
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".

### WooCommerce Google Product Feed DB status ###

Database version: 16
Active database version: 16
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-GB): 5595 items

### Product Bundles ###

Database Version: 6.18.1
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-24 10:25:51 +00:00
Options: ✔
Notes: 117
Onboarding: completed

### Multicurrency ###

admin_email: stephan@bigsalami.co.uk
allow_price_per_product: no
client_side_cookies: no
cookie_woocommerce_multicurrency_forced_currency: USD
currency_symbol_EUR: -
currency_symbol_GBP: -
currency_symbol_USD: -
customer_location_method: geolocation_ajax
enabled_currencies: a:3:{i:0;s:3:"EUR";i:1;s:3:"GBP";i:2;s:3:"USD";}
fallback_currency: GBP
fee_percent: 2.5
log_level: error
maxmind_license_set: yes
price_charm: 0.01
price_format_EUR: -
price_format_GBP: -
price_format_USD: -
rates: a:169:{s:3:"AED";d:3.6730000000000000426325641456060111522674560546875;s:3:"AFN";d:89.20240800000000...
rates_count: array(169)
rates_provider_id: OpenExchangeRates
rates_retrieval_status: 1
rates_timestamp: 1677081600
rates_update_schedule: daily
reporter_email: stephan@bigsalami.co.uk
reporter_name: Stephan
round_to: 1
selector_widgets: 
store_country_state: GB
switcher_conditions: no
update_error: a:2:{s:7:"message";s:0:"";s:9:"timestamp";i:1677081647;}
version: 3.2.2
woocommerce_prices_include_tax: yes
woocommerce_tax_display_cart: incl
woocommerce_tax_display_shop: incl

### Action Scheduler ###

Complete: 18,082
Oldest: 2023-01-24 11:55:42 +0000
Newest: 2023-02-23 15:11:47 +0000

Failed: 10
Oldest: 2022-09-26 14:37:15 +0000
Newest: 2023-02-19 11:20:06 +0000

Pending: 4
Oldest: 2023-02-23 15:13:45 +0000
Newest: 2023-02-23 19:59:46 +0000

### Status report information ###

Generated at: 2023-02-23 15:13:14 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Duplicates https://github.com/woocommerce/woocommerce/issues/36490.
