### ISSUE TITLE
Checkout: "Sorry, your session has expired." with pre-filled data

### ISSUE THREAD

**Issue by wdm-janis** [woothemes/woocommerce#36956]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I use pre-filled data for checkout fields and autocomplete, then I got Sorry, your session has expired. [Return to shop]. 

### Expected behavior

Pre-filled values need to work. 

### Actual behavior

When I write down each input field, like name, and email manually, I have no errors. 

No plugins, and a standard theme, but this not happening on a clean install. I also tried clear WC sessions via WooCommerce Tools. Nothing helped. 

### Steps to reproduce

Go to checkout and use pre-filled information for checkout fields. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hacksessionfix.lionssolution.com
Site address (URL): https://hacksessionfix.lionssolution.com
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/3.0.2
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.12-MariaDB-1:10.6.12+maria~ubu2204
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 2890.77MB
Database Data Size: 2809.97MB
Database Index Size: 80.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.44MB + Index: 1.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_addonlibrary_addons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_betterdocs_search_keyword: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_betterdocs_search_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.47MB + Index: 0.34MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_visits: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits_meta: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 4.52MB + Index: 3.77MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ewwwio_images: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lg_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lg_tools: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.48MB + Index: 0.20MB + Engine InnoDB
wp_postmeta: Data: 2374.66MB + Index: 52.16MB + Engine InnoDB
wp_posts: Data: 360.50MB + Index: 7.06MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.23MB + Index: 0.13MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rmp_analytics: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_slc_simple_login_captcha: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.25MB + Index: 0.16MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.47MB + Index: 0.39MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdi_themes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 13.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.45MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wow_button_generator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wow_fbtnp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wow_fmp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_creatives: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_impressions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_paypal_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens_purchase_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
amp_validated_url: 1
attachment: 2698
carousels: 2
cartflows_flow: 18
cartflows_step: 43
clients: 2
condition_group: 1
copy-to-clipboard: 1
custom-css-js: 1
customize_changeset: 9
custom_css: 4
docs: 8
elementor_font: 1
elementor_library: 138
elementor_snippet: 1
employees: 3
feedback: 99
foogallery: 1
frm_form_actions: 2
frm_styles: 1
gfw_report: 11
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
mc4wp-form: 2
ml-slide: 15
ml-slider: 4
nav_menu_item: 45
oembed_cache: 196
page: 107
popup: 6
popup_theme: 6
post: 224
postman_sent_mail: 19
product: 9
projects: 10
pys_event: 2
revision: 12473
ris_gallery: 2
services: 16
shop_coupon: 146
shop_order: 5543
shop_order_refund: 330
sidebar: 1
testimonial: 2
testimonials: 6
testimonial_rotator: 1
wcs_ruleset: 5
wdi_instagram: 1
wpcdt_countdown: 4
wpcode: 2
wpforms: 9
wp_global_styles: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.4.0

### Inactive Plugins (79) ###

Advanced Custom Fields PRO: by WP Engine – 6.0.7
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.1
Affiliatly Integration: by Affiliatly.com – 3.0.1
Akismet Anti-Spam: by Automattic – 5.0.1
All-in-One WP Migration: by ServMask – 6.77
Autoptimize: by Frank Goossens (futtta) – 3.1.4
Better Search Replace: by Delicious Brains – 1.4.1
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.8.0 (update to version 2.9.1 is available)
Carousel Slider: by Sayful Islam – 2.1.0
Change wp-admin login: by Nuno Morais Sarmento – 1.1.0
Checkout Field Editor for WooCommerce (Pro): by ThemeHigh – 3.1.6
Classic Editor: by WordPress Contributors – 1.6.2
Cloudflare: by Cloudflare
Inc. – 4.11.0

Code Snippets: by Code Snippets Pro – 3.2.1
Conditional Shipping for WooCommerce: by Lauri Karisola / WP Trio – 2.3.1
Copy Anything to Clipboard: by Mahesh M. Waghmare – 2.6.1
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout: by PI Websolution – 2.1.37
Disable "BIG image" Threshold: by Jonathan Desrosiers – 1.0
Download Plugin: by metagauss – 2.0.5
Drip for WooCommerce: by Drip – 1.1.2
Duplicate Menu: by Jonathan Christopher – 0.2.2
Duplicator Pro: by Snap Creek – 4.5.9
Elementor: by Elementor.com – 3.11.2
Elementor Addon Elements: by WPVibes – 1.12.1
Elementor Pro: by Elementor.com – 3.8.0
Error Notify Slack: by zenithtech – 1
EU/UK VAT for WooCommerce: by WPWhale – 2.9.3
Gallery with thumbnail slider: by Galaxy Weblinks – 4.0
GTM4WP: by Thomas Geiger – 1.16.1
Header Footer Code Manager: by 99robots – 1.1.27
Hello Dolly: by Matt Mullenweg – 1.7.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Hotjar: by Hotjar – 1.0.14
IcebergBuilder: by IcerbergBuilder – 2.1
Load More Anything: by Addon Master – 3.0.2
Maintenance: by WebFactory Ltd – 4.07
MainWP Child: by MainWP – 4.3
Make Column Clickable Elementor: by Fernando Acosta – 1.4.0
MalCare Security - Free Malware Scanner, Protection & Security for WordPress: by MalCare Security – 4.67
ManageWP - Worker: by GoDaddy – 4.9.16
Multi-Step Checkout for WooCommerce: by SilkyPress – 2.21.1
PayPal for WooCommerce: by Angell EYE – 3.0.40
PixelYourSite: by PixelYourSite – 9.2.2
Post SMTP: by Post SMTP – 2.4
Query Monitor: by John Blackbourn – 3.11.1
Rank Math SEO: by Rank Math – 1.0.93.1
Rate my Post - WP Rating System: by Blaz K. – 3.3.6
Really Simple SSL: by Really Simple Plugins – 5.3.5
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: by Retainful – 2.6.16
RocketCDN: by WP Media – 1.0.3
RunCloud Hub: by RunCloud – 1.2.1
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Simple Login Captcha: by Nikolay Nikolov – 1.3.3
SIP Cookie Check for WooCommerce: by ShopitPress <hello@shopitpress.com> – 1.0.3
Table of Contents Plus: by Michael Tran – 2212
Tawk.to Live Chat: by Tawkto – 0.7.2
Unlimited Elements for Elementor: by Unlimited Elements – 1.5.34
WebP Express: by Bjørn Rosell – 0.25.5
webp_upload: by  – 1.0
WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free ): by WebToffee – 1.7.6
WooCommerce - Active Campaign Integration: by Jason Kadlec: ActiveWoo.com – 2.0.2
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.19
WooCommerce Google Analytics Pro: by SkyVerge – 1.11.1 (update to version 1.13.0 is available)
Woocommerce Minimum and Maximum Quantity: by Ashok G – 2.1.8
WooCommerce PayPal Payments: by WooCommerce – 2.0.2
WooCommerce Price Based on Country: by Oscar Gare – 3.0.2
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
Woo Discount Rules: by Flycart – 2.4.5
Woo Discount Rules PRO 2.0: by Flycart – 2.4.5
WooSwipe: by Thrive Website Design – 2.0.1
Wordfence Security: by Wordfence – 7.7.1
WordPress Importer: by wordpressdotorg – 0.8
WPCode - Insert Headers, Footers, and Code Snippets: by WPCode – 2.0.3
WPForms Lite: by WPForms – 1.7.7.2
WP Mail SMTP: by WPForms – 3.6.1
WP Rollback: by GiveWP.com – 1.7.1
WProofreader: by WebSpellChecker – 2.6.7
WP Super Cache: by Automattic – 1.9.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.15.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: ❌ Page not set
Cart: #8503 - /cart/
Checkout: #8451 - /checkout/
My account: ❌ Page not set
Terms and conditions: #5843 - /terms-and-conditions-2/

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-25 06:30:04 +02:00
Options: ✔
Notes: 114
Onboarding: completed

### Action Scheduler ###

Complete: 3,125
Oldest: 2023-01-24 18:05:21 +0200
Newest: 2023-02-24 16:47:45 +0200

Pending: 2
Oldest: 2023-02-24 17:59:18 +0200
Newest: 2023-02-24 18:16:01 +0200

Failed: 35
Oldest: 2022-07-27 16:33:37 +0300
Newest: 2023-02-24 16:14:15 +0200

### Status report information ###

Generated at: 2023-02-24 17:58:26 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @wdm-janis,

Thanks for the report. I want to make sure I understand your issue correctly. Are you using information stored in the browser to pre-fill fields on the checkout page? If so, can you please include information about the browsers that you're using while running into this issue? Are you able to reproduce it in different browsers?

Are there any set of steps that we might be able to follow to reproduce the issue?

**Comment by rrennick** [comment]
Closing for lack of feedback.
