### ISSUE TITLE
Verify that all experimental product editor work is behind a feature flag

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#36989]
Now that our new editing experience using blocks is updated and working similar to what our previous experience was, we should swap the feature flags.

We should make use of the new feature flag already created by Proton: p7bje6-4kh-p2 similar to what was already done as part of this initial PR: https://github.com/woocommerce/woocommerce/pull/37122

We should add a condition to only allow users to enable it if they are on the latest WP version 6.2 and higher.
If users already had it enabled but where on lower version, we could keep it enabled ( it still seemed to work well on 6.0).

See the similar logic around WP version comparison here: https://github.com/woocommerce/woocommerce/blob/0d45b0f1078db0e11b89c91b05599156bc6942a1/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L643-L653

#### Acceptance criteria

* [ ] The experiment feature `New product editor` should be enabled again if users are on WP 6.2 or higher.
* [ ] The `New product editor` feature should enable the new block based editor ( `new_product_management` -> https://github.com/woocommerce/woocommerce/blob/0d45b0f1078db0e11b89c91b05599156bc6942a1/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L106 )
* [ ] The `product-block-editor` feature should be removed, or enabled by default, but toggled by the experimental feature in **WooCommerce > Settings > Features**

**Comment by joshuatf** [comment]
Estimate: 1

Beyond determining if this should be a new feature flag or not, this should be trivial to make sure the work is behind a flag.

**Comment by louwie17** [comment]
> The alternative is to create a new route and page for the "new new experience" and create a new feature flag for that while maintaining the first iteration of the new experience.

I propose using the same routes for the new experience, but creating a new route for the old experience. Something like `product-old` :)

**Comment by louwie17** [comment]
We should actually make use of the new Feature flag created by Proton for this: p7bje6-4kh-p2
I upped the estimate by 1 because of this.

**Comment by louwie17** [comment]
After discussion with @mdperez86, we are setting this issue to blocked for now until we have made more progress on the block editor and we will un-block it when the block editor is at-least useable. 

We will initially create an alternative issue to add a feature to the JSON feature flag file that we can toggle with the beta tester ( I will link the issue once created).
