### ISSUE TITLE
Error en WooComerce Ajustes

### ISSUE THREAD

**Issue by carlosalarrota** [woothemes/woocommerce#37012]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

En Ajustes de WooComerce, Ingreso opción ayuda , Selecciono asistente de configuración, Ingreso la información que solicita, al dar click en Seguir, No continua al paso 2 ,

Pregunta en ingles utilizando en google traductor 
In WooCommerce Settings, Enter help option, Select configuration wizard, Enter the information requested, by clicking on Continue, Do not continue to step 2

Este es el  estado del sistema.

### WordPress Environment ###

WordPress address (URL): https://www.lygservicios.com
Site address (URL): https://www.lygservicios.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_CO
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.9
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.28-0ubuntu0.20.04.3
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_tfxss9_
Tamaño total de la base de datos: 11.73MB
Tamaño de los datos de la base de datos: 10.12MB
Tamaño del índice de la base de datos: 1.61MB
wp_tfxss9_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_actions: Datos: 0.09MB + Índice: 0.11MB + Motor InnoDB
wp_tfxss9_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_logs: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_comments: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_tfxss9_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_easywpsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_easywpsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_ewwwio_images: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_ewwwio_queue: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_options: Datos: 6.41MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_postmeta: Datos: 2.11MB + Índice: 0.11MB + Motor InnoDB
wp_tfxss9_posts: Datos: 0.42MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_tfxss9_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_tfxss9_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_tfxss9_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 42
custom_css: 2
customize_changeset: 37
elementor_library: 3
nav_menu_item: 27
page: 25
post: 5
product: 1
revision: 75
shop_order: 2
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Plantillas de inicio: por Brainstorm Force – 3.1.27
Codisto Channel Cloud: por Codisto – 1.3.65
Joinchat: por Creame – 4.5.18
Docket Cache: por Nawawi Jamili – 22.07.03
DreamHost Panel Login: por DreamHost
danielbachhuber – 1.0.0

Elementor: por Elementor.com – 3.11.2
EWWW Image Optimizer: por Exactly WWW – 6.9.3
Spectra: por Brainstorm Force – 2.3.5
WooCommerce Stripe Gateway: por WooCommerce – 7.1.0
WooCommerce: por Automattic – 7.4.1
WP Mail SMTP: por WPForms – 3.7.0
WP Super Cache: por Automattic – 1.9.3
WPForms Lite: por WPForms – 1.8.0.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: por Automattic – 5.0.2
Click to Chat: por HoliThemes – 3.23
Hello Dolly: por Matt Mullenweg – 1.7.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Docket Cache Drop-in

### Settings ###

API Enabled: –
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la tienda: #64 - /productos-locales-on-line/
Carrito: ❌ La página no contiene el shortcode [woocommerce_cart] o el bloque woocommerce/cart.
Finalizar compra: ❌ Página sin definir
Mi cuenta: ❌ Página sin definir
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-01 21:05:26 -05:00
Options: ✔
Notes: 32
Onboarding: skipped

### Action Scheduler ###

Cancelada: 1
Oldest: 2023-02-27 18:39:35 -0500
Newest: 2023-02-27 18:39:35 -0500

Completo: 219
Oldest: 2023-02-26 15:16:41 -0500
Newest: 2023-02-28 19:56:13 -0500

Fallida: 5
Oldest: 2023-02-27 11:21:23 -0500
Newest: 2023-02-28 19:58:08 -0500

Pendiente: 7
Oldest: 2023-03-01 16:03:21 -0500
Newest: 2023-03-07 20:38:01 -0500

### Status report information ###

Generated at: 2023-02-28 22:05:20 -05:00

### Expected behavior

Debería pasar al segundo paso de ajustes para continuar con la configuración de WooComerce.
( You should move on to the second step of settings to continue with the WooCommerce setup. )

### Actual behavior

Pagina en blanco, No continua con la configuracion.
(Blank page, does not continue with the configuration)

### Steps to reproduce

1.  Seleccionar Escritorio
2. Seleccionar WooComerce
3. Seleccionar Ajustes
4. Click boton de Ayuda
5. Click Asistente de configuracion
6. Click Boton Asistente de Configuracion
7. Ingresar informacion
8. Click en boton Seguir

### WordPress Environment ###

WordPress address (URL): https://www.lygservicios.com
Site address (URL): https://www.lygservicios.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_CO
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.9
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.28-0ubuntu0.20.04.3
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_tfxss9_
Tamaño total de la base de datos: 11.73MB
Tamaño de los datos de la base de datos: 10.12MB
Tamaño del índice de la base de datos: 1.61MB
wp_tfxss9_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_actions: Datos: 0.09MB + Índice: 0.11MB + Motor InnoDB
wp_tfxss9_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_actionscheduler_logs: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_comments: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_tfxss9_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_easywpsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_easywpsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_ewwwio_images: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_ewwwio_queue: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_options: Datos: 6.41MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_postmeta: Datos: 2.11MB + Índice: 0.11MB + Motor InnoDB
wp_tfxss9_posts: Datos: 0.42MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_tfxss9_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_tfxss9_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_tfxss9_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tfxss9_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_tfxss9_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_tfxss9_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tfxss9_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 42
custom_css: 2
customize_changeset: 37
elementor_library: 3
nav_menu_item: 27
page: 25
post: 5
product: 1
revision: 75
shop_order: 2
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Plantillas de inicio: por Brainstorm Force – 3.1.27
Codisto Channel Cloud: por Codisto – 1.3.65
Joinchat: por Creame – 4.5.18
Docket Cache: por Nawawi Jamili – 22.07.03
DreamHost Panel Login: por DreamHost
danielbachhuber – 1.0.0

Elementor: por Elementor.com – 3.11.2
EWWW Image Optimizer: por Exactly WWW – 6.9.3
Spectra: por Brainstorm Force – 2.3.5
WooCommerce Stripe Gateway: por WooCommerce – 7.1.0
WooCommerce: por Automattic – 7.4.1
WP Mail SMTP: por WPForms – 3.7.0
WP Super Cache: por Automattic – 1.9.3
WPForms Lite: por WPForms – 1.8.0.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: por Automattic – 5.0.2
Click to Chat: por HoliThemes – 3.23
Hello Dolly: por Matt Mullenweg – 1.7.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Docket Cache Drop-in

### Settings ###

API Enabled: –
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la tienda: #64 - /productos-locales-on-line/
Carrito: ❌ La página no contiene el shortcode [woocommerce_cart] o el bloque woocommerce/cart.
Finalizar compra: ❌ Página sin definir
Mi cuenta: ❌ Página sin definir
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-01 21:05:26 -05:00
Options: ✔
Notes: 32
Onboarding: skipped

### Action Scheduler ###

Cancelada: 1
Oldest: 2023-02-27 18:39:35 -0500
Newest: 2023-02-27 18:39:35 -0500

Completo: 219
Oldest: 2023-02-26 15:16:41 -0500
Newest: 2023-02-28 19:56:13 -0500

Fallida: 5
Oldest: 2023-02-27 11:21:23 -0500
Newest: 2023-02-28 19:58:08 -0500

Pendiente: 7
Oldest: 2023-03-01 16:03:21 -0500
Newest: 2023-03-07 20:38:01 -0500

### Status report information ###

Generated at: 2023-02-28 22:05:20 -05:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @carlosalarrota,

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> Error in WooCommerce Settings

> In WooCommerce Settings, I enter help option, I select configuration assistant, I enter the information requested, by clicking on Continue, Do not continue to step 2,

Thanks for your report. I do not quite understand the steps that you're describing. Would you be able to provide a list of steps you took, and a description of what you expected to happen versus what actually happened?

**Comment by carlosalarrota** [comment]
Good afternoon, Jonnatan Sadowski. 

Thank you very much for time. 

I am attaching a file with the step by step of what is happening to me
and what I am waiting for to happen. 

let me know anything, thanks 

Att, 

Carlos

**Comment by jonathansadowski** [comment]
Hi @carlosalarrota,

It looks like you replied by email, but if you attached something, it didn't come through. Can you please reply to the issue on the web? https://github.com/woocommerce/woocommerce/issues/37012

**Comment by rrennick** [comment]
Closing due to lack of feedback.
