### ISSUE TITLE
Текст кнопки не сохраняет название

### ISSUE THREAD

**Issue by UliaKruglak** [woothemes/woocommerce#37022]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

В Каталоге магазина текст кнопки стоит "Выбрать", но когда выбираешь вариативный товар текст переводит на английский язык, это очень мешает

### Expected behavior

Как оставить текст кнопки на языке который мне нужен?

### Actual behavior

![Screenshot_3](https://user-images.githubusercontent.com/97180855/222251101-55df9f8f-1cc7-468b-89b7-fe752040d1bf.png)
![Screenshot_4](https://user-images.githubusercontent.com/97180855/222251108-59de20f8-a238-4050-b241-c9f1f2cf1da2.png)
На скриншотах видно как выглядит кнопка при входе в каталог и какой она становится при выборе вариации товара

### Steps to reproduce

я выше уже описала всю проблему

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://skal.com.ua
Site address (URL): https://skal.com.ua
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 ГБ
WP Debug Mode: –
WP Cron: ✔
Language: uk
External object cache: –

### Server Environment ###

Server Info: LiteSpeed/6.0.11 Enterprise
PHP Version: 7.4.26
PHP Post Max Size: 1 ГБ
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.80.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB
Max Upload Size: 1 ГБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Загальний розмір бази даних: 71.49MB
Розмір бази даних: 55.02MB
Розмір бази даних: 16.47MB
wp_woocommerce_sessions: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_woocommerce_api_keys: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_woocommerce_attribute_taxonomies: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_woocommerce_downloadable_product_permissions: Дані: 0.02MB + індекс: 0.06MB + двигун InnoDB
wp_woocommerce_order_items: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_woocommerce_order_itemmeta: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_woocommerce_tax_rates: Дані: 0.02MB + індекс: 0.06MB + двигун InnoDB
wp_woocommerce_tax_rate_locations: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_woocommerce_shipping_zones: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_woocommerce_shipping_zone_locations: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_woocommerce_shipping_zone_methods: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_woocommerce_payment_tokens: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_woocommerce_payment_tokenmeta: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_woocommerce_log: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_actionscheduler_actions: Дані: 0.05MB + індекс: 0.11MB + двигун InnoDB
wp_actionscheduler_claims: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_actionscheduler_groups: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_actionscheduler_logs: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_cartflows_ca_cart_abandonment: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_cartflows_ca_email_history: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_cartflows_ca_email_templates: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_cartflows_ca_email_templates_meta: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_commentmeta: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_comments: Дані: 0.02MB + індекс: 0.09MB + двигун InnoDB
wp_e_events: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_links: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_nova_poshta_city: Дані: 2.52MB + індекс: 0.00MB + двигун InnoDB
wp_nova_poshta_poshtomat: Дані: 10.45MB + індекс: 5.03MB + двигун InnoDB
wp_nova_poshta_region: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_options: Дані: 9.03MB + індекс: 0.13MB + двигун InnoDB
wp_postmeta: Дані: 12.23MB + індекс: 0.45MB + двигун InnoDB
wp_posts: Дані: 2.44MB + індекс: 0.13MB + двигун InnoDB
wp_termmeta: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_terms: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_term_relationships: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_term_taxonomy: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_uposhta_invoices: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_usermeta: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_users: Дані: 0.02MB + індекс: 0.05MB + двигун InnoDB
wp_wc_admin_notes: Дані: 0.05MB + індекс: 0.00MB + двигун InnoDB
wp_wc_admin_note_actions: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wc_category_lookup: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_wc_customer_lookup: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_wc_download_log: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_wc_order_coupon_lookup: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_wc_order_product_lookup: Дані: 0.02MB + індекс: 0.06MB + двигун InnoDB
wp_wc_order_stats: Дані: 0.02MB + індекс: 0.05MB + двигун InnoDB
wp_wc_order_tax_lookup: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_wc_product_attributes_lookup: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wc_product_download_directories: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wc_product_meta_lookup: Дані: 0.02MB + індекс: 0.09MB + двигун InnoDB
wp_wc_rate_limits: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wc_reserved_stock: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_wc_tax_rate_classes: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wc_ukr_shipping_np_areas: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_wc_ukr_shipping_np_cities: Дані: 2.52MB + індекс: 1.52MB + двигун InnoDB
wp_wc_ukr_shipping_np_warehouses: Дані: 14.58MB + індекс: 7.55MB + двигун InnoDB
wp_wc_webhooks: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_wpforms_logs: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_wpforms_tasks_meta: Дані: 0.02MB + індекс: 0.00MB + двигун InnoDB
wp_yoast_indexable: Дані: 0.05MB + індекс: 0.09MB + двигун InnoDB
wp_yoast_indexable_hierarchy: Дані: 0.02MB + індекс: 0.05MB + двигун InnoDB
wp_yoast_migrations: Дані: 0.02MB + індекс: 0.02MB + двигун InnoDB
wp_yoast_primary_term: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB
wp_yoast_seo_links: Дані: 0.02MB + індекс: 0.03MB + двигун InnoDB

### Post Type Counts ###

attachment: 204
cartflows_flow: 5
cartflows_step: 10
custom_css: 2
customize_changeset: 3
elementor_library: 6
nav_menu_item: 39
page: 15
post: 5
product: 12
product_variation: 22
revision: 271
shop_order: 2
wp_global_styles: 3
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

WooCommerce - WayForPay: автор support@wayforpay.com – 1.0
Starter Templates: автор Brainstorm Force – 3.1.27
Bulk remove posts from category: автор MasterNs – 3.3
CartFlows: автор CartFlows Inc – 1.11.9
Checkout Plugins - Stripe for WooCommerce: автор Checkout Plugins – 1.4.11
Customize My Account for WooCommerce: автор SysBasics – 1.3.3
Cyr to Lat enhanced: автор Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.7

Elementor: автор Elementor.com – 3.11.2
Jetpack: автор Automattic – 11.8.4
Спроби обмеження входу в систему перезавантаження: автор Спроби обмеження входу в систему перезавантаження – 2.25.12
To Top: автор Catch Plugins – 2.5.2
Variation Swatches for WooCommerce: автор CartFlows – 1.0.7
WC Ukraine Shipping: автор kirillbdev – 1.11.3
WooCommerce Cart Abandonment Recovery: автор CartFlows Inc – 1.2.23
Checkout Field Editor for WooCommerce: автор ThemeHigh – 1.8.1
Customizer for WooCommerce: автор SkyVerge – 2.7.7
WooCommerce: автор Automattic – 7.4.1
Yoast SEO: автор Команда Yoast – 20.2
WPForms Lite: автор WPForms – 1.8.0.2
WP Telegram: автор WP Socio – 4.0.3

### Must Use Plugins (1) ###

WordPress automation by Installatron: автор  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: UAH (₴)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Головна сторінка магазина: #4389 - /catalog/
Кошик: #4390 - /koshik/
Оформлення замовлення: #4391 - /oformlenya-zamovlenya/
Мій обліковий запис: #4392 - /my-account/
Правила та умови: #4795 - /publichna-oferta/

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Якщо ви модифікуєте WooCommerce на батьківській темі
яку ви не створювали особисто
ми рекомендуємо використовувати дочірні теми. Див .:  Як створити дочірню тему

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-02 12:59:03 +03:00
Options: ✔
Notes: 69
Onboarding: completed

### Action Scheduler ###

Виконано: 54
Oldest: 2023-01-29 19:57:10 +0000
Newest: 2023-03-01 19:22:29 +0000

Не вдалося: 2
Oldest: 2023-03-01 13:25:01 +0000
Newest: 2023-03-01 14:00:20 +0000

Очікує перевірки: 10
Oldest: 2023-03-01 22:57:32 +0000
Newest: 2023-03-27 20:28:04 +0000

### Status report information ###

Generated at: 2023-03-01 22:56:46 +03:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @UliaKruglak,

Thanks for the report. Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> Button text doesn't save title

> In the Store Catalog, the text of the button is "Select", but when you select a variable product, the text translates into English, this is very disturbing

> How can I leave the text of the button in the language I need?

> The screenshots show what the button looks like when you enter the catalog and what it becomes when you select a product variation

> I have already described the problem above.

**Comment by UliaKruglak** [comment]
> Hi @UliaKruglak,
> 
> Thanks for the report. Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back.
> 
> > Button text doesn't save title
> 
> > In the Store Catalog, the text of the button is "Select", but when you select a variable product, the text translates into English, this is very disturbing
> 
> > How can I leave the text of the button in the language I need?
> 
> > The screenshots show what the button looks like when you enter the catalog and what it becomes when you select a product variation
> 
> > I have already described the problem above.


Hello, your translation is correct and my problem is described correctly, can I get help?

**Comment by helgatheviking** [comment]
In the store catalog the screenshots are not of the Woo default interface. Woo does not change button text in the store catalog... a variable product would read "Select options" by default and redirect a customer to the single product page where they could make adjustments. I suspect this is a theme/plugin customization issue.
