### ISSUE TITLE
Send empty form when clicking "Save attribute"

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37021]
### Describe the bug

When creating a product, under the Attributes tab, we don't check if the form is empty when pressing the `Save attribute` button. So it's possible to send empty values to the action `woocommerce_save_attributes`.

We should add a check like [this](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js#L62-L64) to [this method](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js#L745-L829).

We should mark these fields as required, disable the Save button, and show a help message.

### Steps to reproduce

- Add a global attribute through the new dropdown
- Don't add any terms and click **Save attributes**
- The request is being sent after pressing **Save attributes**

![Screen Capture on 2023-03-01 at 16-46-28](https://user-images.githubusercontent.com/1314156/222249127-976c35ed-4573-4bbb-8ff9-f43013437949.gif)

**Acceptance criteria**
- [ ] Add a check like [this](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js#L62-L64) to [this method](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js#L745-L829).
- [ ] Mark these fields as required, disable the Save button, and show a help message.

**Comment by octaedro** [comment]
Hey @jarekmorawski,
I'm creating an issue that will include what we discussed in [this PR](https://github.com/woocommerce/woocommerce/pull/36957). Could you share the [help message](https://github.com/woocommerce/woocommerce/pull/36957#issuecomment-1450001696) we should add to the validation?

**Comment by jarekmorawski** [comment]
Hi @octaedro. Thanks for the ping. I'm working on a larger update to these flows. I think it's safe to put this on pause now and come back to it early next week.

**Comment by octaedro** [comment]
> I'm working on a larger update to these flows. I think it's safe to put this on pause now and come back to it early next week.

@jarekmorawski Thank you for taking care of this flow. Right now when we press the save button and the fields are empty, we execute the saving action with empty params, and that shouldn't happen. Just to avoid that behavior I created [this PR](https://github.com/woocommerce/woocommerce/pull/37046) that disables the save buttons (under `Attributes` and `Variations` tabs) until the fields `Name` and `Value(s)` have any value.

Maybe we can add a `title` attribute to the button when it's disabled with a text explaining that it will be reenabled as soon as the form fields have values.

If you hover the save button, it would look like this:

![Screenshot 2023-03-03 at 12 24 35](https://user-images.githubusercontent.com/1314156/222759327-a7b01df2-2634-4ac2-9be0-4986ef16b24c.png)

**Comment by jarekmorawski** [comment]
I added extra flows and designs to https://github.com/woocommerce/woocommerce/issues/37099.
