### ISSUE TITLE
woocommerce_order_list_table_prepare_items_query_args filter value is overriden by new filter in version 7.3.0

### ISSUE THREAD

**Issue by sarath-mozilor** [woothemes/woocommerce#37035]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Values return from the filter `woocommerce_order_list_table_prepare_items_query_args` are stored in `$order_query_args` variable. But the variable was overridden by the new filter introduced in version 7.3.0 

The new filter: `woocommerce_shop_order_list_table_prepare_items_query_args`

### Expected behavior

The return value from `woocommerce_order_list_table_prepare_items_query_args` filter must be supplied as argument for the new filter. So the value will not override.

### Actual behavior

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/42467480/222413425-b52d07c3-630b-484f-9f03-f3cdf2eb3e1c.png">
****
If I altered the query argument by adding `id` or `post__in` value. I am expecting the result will be based on the new argument.

### Steps to reproduce

1. Add a code snippet to filter `woocommerce_order_list_table_prepare_items_query_args`
2. Alter the $args argument by adding an `id` parameter to that array
3. Expecting the the query result will process the newly added parameter
4. But the parameter was overridden by the new filter just below the above filter.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.12 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.12
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 8.93MB
Database Data Size: 6.65MB
Database Index Size: 2.28MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mc_customize_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.45MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wb_mlr_data: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wt_abandonment_coupon: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_wt_sc_coupon_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_pos_register_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 9
post: 2
product: 28
product_variation: 12
revision: 13
shop_coupon: 82
shop_order: 25
yith-pos-receipt: 1
yith-pos-register: 1
yith-pos-store: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.11.2
Flexible Shipping PRO: by Octolize – 2.15.2
Flexible Shipping: by Octolize – 4.18.6
Wb Mail Logger: by Web Builder 143 – 1.0.2
WooCommerce: by Automattic – 7.3.0 (update to version 7.4.1 is available)
Smart Coupons for WooCommerce Pro: by WebToffee – 2.0.7

### Inactive Plugins (14) ###

Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.1.5
Akismet Anti-Spam: by Automattic – 5.0.1
Booster Plus for WooCommerce: by Pluggabl LLC – 6.0.0
CURCY - WooCommerce Multi Currency Premium: by VillaTheme – 2.2.2
Current Template Info: by spoot1986 – 1.0.0
Customize-Messages: by Ammukutty Pradeep – 1.0.0
DT WooCommerce Page Builder: by DawnThemes – 3.3.8.4
Hello Dolly: by Matt Mullenweg – 1.7.2
User Registration Customize My Account: by WPEverest – 1.1.9
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13
WooCommerce Tiered Price Table: by bycrik – 2.8.0
WooCommerce Tiered Price Table (Premium): by bycrik – 2.8.0
WP Hooks Finder: by Muhammad Rehman – 1.2.3
YITH Point of Sale for WooCommerce: by YITH – 2.0.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: .DS_Store

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-03-03 08:40:48 +05:30
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Complete: 100
Oldest: 2023-02-01 11:57:41 +0000
Newest: 2023-03-02 10:37:50 +0000

Pending: 1
Oldest: 2023-03-03 05:08:30 +0000
Newest: 2023-03-03 05:08:30 +0000

### Status report information ###

Generated at: 2023-03-02 16:49:36 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Hi, @sarathe4moz Thanks for reporting the issue. It was fixed in https://github.com/woocommerce/woocommerce/pull/36649.

**Comment by sarath-mozilor** [comment]
Thank you.
