### ISSUE TITLE
E2E: Fix skipped test: should display the choose payments task, and not the WC Pay task

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#37038]
The e2e test `should display the choose payments task, and not the WC Pay task` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/activate-and-setup/complete-onboarding-wizard.spec.js has been skipped 

This issue is track fixing and re-enabling this test.

**Comment by lanej0** [comment]
The OBW tests have been replaced by tests for core profiler.  Closing.
