### ISSUE TITLE
E2E: Fix skipped test: can unselect all business features and continue

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#37037]
The e2e test `can unselect all business features and continue` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/activate-and-setup/complete-onboarding-wizard.spec.js was skipped in https://github.com/woocommerce/woocommerce/pull/34790

This issue is track fixing and re-enabling this test.

**Comment by lanej0** [comment]
Marking complete because this test has been replaced by a series of tests for the core profiler (replacing the onboarding wizard).
