### ISSUE TITLE
7.5.0-beta.2 `ajaxComplete()` not triggering

### ISSUE THREAD

**Issue by JimmyAppelt** [woothemes/woocommerce#37066]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`ajaxComplete()` does not seem to be triggering anymore in 7.5 beta, for example when the update cart button is used or checkout country is changed, etc...

### Expected behavior

Should trigger when ajax request is done https://api.jquery.com/ajaxcomplete/

### Actual behavior

Not triggering

### Steps to reproduce

```js
jQuery(document).ajaxComplete(function () {
  console.log('ajax complete')
})
```

### WordPress Environment

WP 6.2 beta 4

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by neagugeorge** [comment]
Hello,

Same problem with ajaxComplete on checkout. On version 7.4 everything work good but now from version 7.5 ajaxComplete not working. This bug happens with Storefront theme and I have active only Woocommerce plugin.

Best regards
