### ISSUE TITLE
Add ajax event reduce_in_cart or ability to set exact amount of a product in cart

### ISSUE THREAD

**Issue by oglekler** [woothemes/woocommerce#37067]
### Describe the solution you'd like

woocommerce\includes\class-wc-ajax.php:103

Add in add_ajax_events() method action to reduce amount in cart or set exact amount. This amount can be returned in fragments via ajax as well.

**Comment by rrennick** [comment]
@OlaIola Thanks for submitting the issue. Could you edit your issue description and provide details on a use case for this enhancement?

**Comment by oglekler** [comment]
Hi @rrennick,
For example you have party hats (or any other items which can be needed in bunched and are buying with a lot of other stuff) in your store, and you want to give a user possibility to add amount of party hats he/she needs right from the catalog (archive page). Sometimes only in cart you as a user are realizing that there isn't enough of things you want, and you need to go and search for something else all over again. And of course when you can only add thing into the cart, you are not realizing how many are already there if you have multiple things in the cart already, and it isn't very convenient either. This way, the user will be able to manage the right amount on the spot. I imagine this scenario: User is adding something into a card, and instead of "Added in cart" button, we have ("-" 1 "+") when user can manage the amount in cart with these buttons. Script can use a delay to update data in the server and return exact amount of items for not to send updates as often or use a small update button, but it's a frontend implementation for this ability to manage cart items on the fly.

And I didn't come up with this idea myself, it was on a design I was provided )

**Comment by rrennick** [comment]
Hi @OlaIola, 

The cart already has [code that updates the quantity](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/cart.js#L558:L583). If you were to add a control elsewhere in the shop to adjust the cart quantity, you could use similar logic in the script for the control with the same ajax method that the cart uses.

I'm closing this as the server side ajax functionality already exists.
