### ISSUE TITLE
"wp_wc_orders does not exist" error when enabling HPOS

### ISSUE THREAD

**Issue by superbmario** [woothemes/woocommerce#37071]
When enabling HPOS on the Features page, the following error shows:

```
WordPress database error: [Table 'databasename.wp_wc_orders' doesn't exist]
SELECT( ( SELECT COUNT(1) FROM wp_posts posts LEFT JOIN wp_wc_orders orders ON posts.id=orders.id WHERE posts.post_type in ('shop_order', 'shop_order_refund', 'shop_subscription') AND posts.post_status != 'auto-draft' AND orders.id IS NULL) + (SELECT COUNT(1) FROM ( SELECT orders.id FROM wp_wc_orders orders JOIN wp_posts posts on posts.ID = orders.id WHERE posts.post_type IN ('shop_order', 'shop_order_refund', 'shop_subscription') AND orders.date_updated_gmt < posts.post_modified_gmt ) x) ) count
```

https://i.imgur.com/YX6sb1k.png

Possibly related to [#35902](https://github.com/woocommerce/woocommerce/issues/35902)

<details>
  <summary>System Details</summary>

### WordPress Environment ###
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 900
PHP Max Input Vars: 8000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.38-MariaDB-log-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 147.75MB
Database Data Size: 81.75MB
Database Index Size: 66.00MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.25MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 6.52MB + Index: 9.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.20MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 51.56MB + Index: 38.14MB + Engine InnoDB
wp_posts: Data: 5.52MB + Index: 3.73MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.30MB + Index: 0.25MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.23MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

ardor_email: 19
attachment: 1538
custom_css: 1
forum_post: 467
nav_menu_item: 10
oembed_cache: 1
page: 31
pd_event: 30
pd_monthly: 29
pd_push_notification: 17
pd_video: 382
post: 50
product: 2
product_variation: 9
revision: 7
shop_coupon: 54
shop_order: 9524
shop_order_refund: 11
shop_subscription: 961

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Manage Notification E-mails: by Virgial Berveling – 1.8.4
Meta Box AIO: by MetaBox.io – 1.18.1
Meta Box: by MetaBox.io – 5.6.17
WooCommerce Subscriptions: by WooCommerce – 4.9.1
WooCommerce: by Automattic – 7.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions-core Library Version: 5.4.0
Subscriptions Template Theme Overrides: 
Subscription Statuses: wc-active: 362
wc-pending-cancel: 13
wc-pending: 10
wc-on-hold: 219
wc-cancelled: 357

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

other: wc-active: 346
wc-cancelled: 355
wc-on-hold: 211
wc-pending: 9
wc-pending-cancel: 12

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-27 10:12:53 +00:00
Options: ✔
Notes: 15
Onboarding: skipped

### Action Scheduler ###

Canceled: 4
Oldest: -0001-11-29 23:58:45 -0001
Newest: -0001-11-29 23:58:45 -0001

Complete: 64
Oldest: 2023-02-28 19:25:50 +0000
Newest: 2023-03-06 09:45:34 +0000

Failed: 6
Oldest: 2023-02-28 19:25:49 +0000
Newest: 2023-03-06 09:45:20 +0000

Pending: 381
Oldest: 2023-03-06 09:50:39 +0000
Newest: 2024-02-25 03:25:26 +0000

### Status report information ###

Generated at: 2023-03-06 09:50:13 +00:00

</details>

**Comment by barryhughes** [comment]
Duplicates https://github.com/woocommerce/woocommerce/issues/35816.

**Comment by superbmario** [comment]
> Duplicates #35816.

In issue #35816 @coreymckrill comments "Noting that these errors only seem to occur once, on the page load right after HPOS is enabled. If you navigate to any other screen, the errors do not occur again, and the necessary tables seem to now exist.". However I do not experience this in my case. After reloading the page or returning to the page, the error message persists. So it may in fact be a different issue, or perhaps that comment is no longer accurate.
