### ISSUE TITLE
Re-enable Purchase unit tests

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#37081]
**Issue Description:**

In https://github.com/woocommerce/woocommerce/pull/36741 purchase tests were set to be skipped.

There was an issue on the wccom side which is now fixed which means I believe these tests can be re-enabled.

More context: peASUH-z-p2#comment-42

**Comment by rjchow** [comment]
Additional comment -

```
Perhaps OBW should be falling back to simply not display any prices rather than empty prices if something like this happens?
```
