### ISSUE TITLE
wp-cli wc customer list doesn´t let to show biling_address 

### ISSUE THREAD

**Issue by ibertrix** [woothemes/woocommerce#37085]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If I run this it works:

`wp wc customer list --field=billing --user=admin --format=csv`

but this isn´t:

`wp wc customer list --field=billing.postcode --user=admin --format=csv`

I searched in the documentation and the only information I found about how to access any field within billing was in the legacy:

https://github.com/woocommerce/woocommerce/wiki/Legacy-CLI-commands-(v2.6-and-below)

where it says these fields are accesable:

billing_address.first_name
billing_address.last_name
billing_address.company
billing_address.address_1
billing_address.address_2
billing_address.city
billing_address.state
billing_address.postcode
billing_address.country
billing_address.email
billing_address.phone

but neither billing_address.postcode or billing.postcode works

### Expected behavior

List of fields from billing array field

### Actual behavior

Doesn´t work

### Steps to reproduce

See above

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://brinzal.org
Site address (URL): https://brinzal.org
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 39.18MB
Tamaño de los datos de la base de datos: 25.08MB
Tamaño del índice de la base de datos: 14.10MB
wp_woocommerce_sessions: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.20MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 1.52MB + Índice: 1.89MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.09MB + Índice: 0.13MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 1.52MB + Índice: 0.55MB + Motor InnoDB
wp_comments: Datos: 0.45MB + Índice: 0.48MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_litespeed_img_optm: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_litespeed_url: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_litespeed_url_file: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_options: Datos: 3.38MB + Índice: 0.16MB + Motor InnoDB
wp_postmeta: Datos: 7.52MB + Índice: 8.03MB + Motor InnoDB
wp_posts: Datos: 7.20MB + Índice: 0.72MB + Motor InnoDB
wp_rank_math_404_logs: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_rank_math_internal_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_rank_math_internal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_rank_math_redirections: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_rank_math_redirections_cache: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_rank_math_sc_analytics: Datos: 0.11MB + Índice: 0.06MB + Motor InnoDB
wp_revslider_css: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_sliders: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_revslider_slides: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_tcp_addresses: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_countries: Datos: 0.02MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_currencies: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_orders: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_ordersmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_orders_costs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_orders_costsmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_orders_details: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_orders_detailsmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_rel_entities: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_taxes: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_tcp_tax_rates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 1.52MB + Índice: 0.64MB + Motor InnoDB
wp_users: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.03MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.03MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.14MB + Índice: 0.05MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 1236
nav_menu_item: 30
oembed_cache: 2
page: 13
portfolio: 12
post: 269
product: 36
product_variation: 152
products: 9
revision: 528
shop_order: 1303
shop_order_refund: 2
slider: 23
tcp_product: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: por Automattic – 5.0.2
Editor clásico: por Colaboradores de WordPress – 1.6.2
Widgets clásicos: por Colaboradores de WordPress – 0.3
Protección de datos del RGPD: por ClickDatos – 3.1.0
Contact Form 7: por Takayuki Miyoshi – 5.7.4
Disable WebP By Default: por David Baumwald – 0.7.0
GTM4WP: por Thomas Geiger – 1.16.2
Export media with selected content: por Joost de Keijzer – 2.1.4
FooTable: por Brad Vincent – 0.3.1
LiteSpeed Cache: por LiteSpeed Technologies – 5.3.3
Media Sync: por Erol Živina – 1.2.9
Metricool: por Metricool – 1.18
qTranslate support for WooCommerce: por Michel Weimerskirch – 1.1.0
qTranslate: por Qian Qin – 2.5.39
Slider Revolution: por ThemePunch – 5.4.8
Sepa Direct Debit: por Joern Bungartz – 1.6.8
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.22.24

WooCommerce Checkout Manager: por QuadLayers – 7.0.8
WooCommerce Redsys payment gateway: por Jesús Ángel del Pozo Domínguez – 1.2.10
WooCommerce: por Automattic – 7.4.1
WordPress Importer: por wordpressdotorg – 0.8
WP Mail SMTP: por WPForms – 3.7.0
YITH WooCommerce Name Your Price: por YITH – 1.3.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la tienda: #1625 - /tienda/
Carrito: #1626 - /carro/
Finalizar compra: #1653 - /finalizar-comprar/
Mi cuenta: ❌ Página sin definir
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: RT-Theme 17
Version: 2.9.9
Author URL: http://themeforest.net/user/stmcan
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: rttheme17/archive-product.php
rttheme17/content-product.php
La  version 2.6.1 de rttheme17/content-product_cat.php está obsoleta. La versión del núcleo es la 4.7.0

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-07 12:52:56 +01:00
Options: ✔
Notes: 40
Onboarding: completed

### Action Scheduler ###

Completo: 202
Oldest: 2023-02-10 18:09:46 +0000
Newest: 2023-03-06 18:47:01 +0000

Fallida: 1
Oldest: 2023-03-01 14:58:26 +0000
Newest: 2023-03-01 14:58:26 +0000

Pendiente: 1
Oldest: 2023-03-07 18:47:01 +0000
Newest: 2023-03-07 18:47:01 +0000

### Status report information ###

Generated at: 2023-03-06 20:00:37 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
The current WP CLI integration doesn't support this. We'd be open to a [feature request](https://woocommerce.com/feature-requests/woocommerce/), though, if you'd like to post one (and that would also help us to see how much demand there might be for this).
