### ISSUE TITLE
Customers Endpoint Errors

### ISSUE THREAD

**Issue by BenParr64** [woothemes/woocommerce#37089]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am building an app which hits the customers endpoint.

`{{baseUrl}}/wc/v3/customers?page=2&per_page=100
`
Please note I am using the page and per page parameter too. This endpoint works as expected for every page, a part from page 3.

I have tried on my staging server and have deactivated all plugins and tried with multiple themes

### Expected behavior

I should receive a 200 ok response with the customer json data

### Actual behavior

Receive a 500 internal server error. After checking wp logs I get this 

﻿ Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function getTimestamp() on null in /public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php
9:02 pm

### Steps to reproduce

Hit the customers api endpoint with page and per page parameter
Set page parameter to 3
See response

### WordPress Environment

`
### WordPress Environment ###

`
### WordPress Environment ###

WordPress address (URL): https://cms.staging.kegthat.com
Site address (URL): https://cms.staging.kegthat.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.0.3 - There is a newer version of WordPress available (6.1.1)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.30
PHP Post Max Size: 100 MB
PHP Time Limit: 6000
PHP Max Input Vars: 6000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: wpmlf_
Total Database Size: 178.74MB
Database Data Size: 104.12MB
Database Index Size: 74.62MB
wpmlf_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmlf_woocommerce_order_items: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wpmlf_woocommerce_order_itemmeta: Data: 8.52MB + Index: 9.03MB + Engine InnoDB
wpmlf_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmlf_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wpmlf_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpmlf_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_angelleye_paypal_for_divi_companies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_atum_product_data: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
wpmlf_barcode_scanner_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_barcode_scanner_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_barcode_scanner_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_barcode_scanner_posts_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_barcode_scanner_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_bv_ip_store: Data: 0.25MB + Index: 0.28MB + Engine InnoDB
wpmlf_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_comments: Data: 4.52MB + Index: 5.94MB + Engine InnoDB
wpmlf_ewwwio_images: Data: 2.52MB + Index: 2.84MB + Engine InnoDB
wpmlf_ewwwio_queue: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpmlf_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_litespeed_img_optm: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wpmlf_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmlf_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_mo_openid_linked_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_options: Data: 2.36MB + Index: 0.27MB + Engine InnoDB
wpmlf_phone_orders_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpmlf_postmeta: Data: 46.58MB + Index: 39.03MB + Engine InnoDB
wpmlf_posts: Data: 18.38MB + Index: 3.50MB + Engine InnoDB
wpmlf_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmlf_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_redirection_items: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpmlf_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmlf_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_sib_model_country: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpmlf_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpmlf_term_relationships: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wpmlf_term_taxonomy: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wpmlf_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_usermeta: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wpmlf_users: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wpmlf_vi_wbe_history: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpmlf_wcpdf_invoice_number: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wpmlf_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wcusage_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wcusage_clicks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wcusage_register: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpmlf_wc_customer_lookup: Data: 0.48MB + Index: 0.38MB + Engine InnoDB
wpmlf_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpmlf_wc_order_product_lookup: Data: 1.52MB + Index: 1.23MB + Engine InnoDB
wpmlf_wc_order_stats: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wpmlf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wc_product_meta_lookup: Data: 0.19MB + Index: 0.45MB + Engine InnoDB
wpmlf_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wt_iew_action_history: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpmlf_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmlf_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmlf_yoast_indexable: Data: 4.16MB + Index: 0.45MB + Engine InnoDB
wpmlf_yoast_indexable_bkup260620: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpmlf_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wpmlf_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmlf_yoast_primary_term: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpmlf_yoast_prominent_words: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wpmlf_yoast_seo_links: Data: 0.25MB + Index: 0.16MB + Engine InnoDB
wpmlf_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_a52pwt34ca_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_a52pwt34ca_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_a52pwt34ca_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_a52pwt34ca_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_a52pwt34ca_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_a52pwt34ca_yoast_indexable: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_a52pwt34ca_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_a52pwt34ca_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_a52pwt34ca_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_a52pwt34ca_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_a52pwt34ca_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.38MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field-group: 1
attachment: 1482
atum_supplier: 6
custom_css: 9
customize_changeset: 1
et_body_layout: 14
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 20
et_template: 45
et_theme_builder: 1
extra_product_tab: 1
gm_menu_block: 2
groovy_menu_preset: 1
json_consumer: 1
mailpoet_page: 1
nav_menu_item: 231
oembed_cache: 14
page: 16
post: 55
product: 1043
product_variation: 159
revision: 1060
shop_coupon: 28
shop_order: 6136
shop_order_refund: 197
tablepress_table: 1
wcpa_pt_forms: 1
wp_global_styles: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.4.1

### Inactive Plugins (17) ###

ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.26.2
Breeze: by Cloudways – 2.0.15
Bulky - Bulk Edit Products for WooCommerce Premium: by VillaTheme – 1.1.6
Customers Headless: by Ben Parr – 1.0.0
Groovy Menu: by Grooni – 2.6.3
Headless CMS: by Imran Sayed – 2.0.1
Metorik Helper: by Metorik – 1.5.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.4.0
Phone Orders for WooCommerce (Pro): by AlgolPlus – 3.6.3
Redirection: by John Godley – 5.3.9
REVIEWS.io for WooCommerce: by Reviews.co.uk – 0.4.6
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 3.0.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.18
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.4.1
WP File Manager: by mndpsingh287 – 7.1.7
WP GraphQL: by WPGraphQL – 1.13.7
Yoast SEO: by Team Yoast – 20.2.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #1308 - /shop/
Cart: #1309 - /basket/
Checkout: #1310 - /checkout/
My account: #1311 - /my-account/
Terms and conditions: #1846 - /term-of-service/

### Theme ###

Name: headless
Version: (update to version 0.9.2 is available)
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-07 11:49:52 +00:00
Options: ✔
Notes: 26
Onboarding: completed

### Action Scheduler ###

Complete: 74
Oldest: 2023-02-04 06:25:52 +0000
Newest: 2023-03-06 21:14:00 +0000

Failed: 25
Oldest: 2022-12-19 22:28:00 +0000
Newest: 2023-03-02 10:02:40 +0000

Pending: 4
Oldest: 2023-03-07 21:12:08 +0000
Newest: 2023-03-09 10:02:40 +0000

### Status report information ###

Generated at: 2023-03-06 21:22:27 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
I can't replicate using the provided steps, exactly, and suspect there is some 'bad' (or unexpected) data that you happen to be paging across. However, it does seem we could be more defensive in this area:

https://github.com/woocommerce/woocommerce/blob/7.5.0/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php#L58

**Comment by BenParr64** [comment]
Thanks @barryhughes, do you have any ideas how I could debug to find out what the unexpected data might be?

**Comment by BenParr64** [comment]
I have managed to trace the user down by reducing pagination for my website but as I am developing an app to handle any woocommerce user I am unsure on how to handle this, will be looking forward to the resolution. Cheers

**Comment by tyler-paulson** [comment]
I'm experiencing the same issue on a client's website.

Do we know what MYSQL table / column the unexpected data might be located in? That would help us out as we could likely clean up the data manually. We've been having issues with Salesforce syncing via the API that I think might be related to this. Our accounting team says it's happening with new customers mostly.

I can probably work on a PR this week to make that line more defensive if that would be helpful.
