### ISSUE TITLE
Multichannel Marketing page displays literal 0 when there are no registered channels or no recommended channels

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#37083]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the multichannel marketing page, when there are no registered channels or no recommended channels, users would see a literal `0` on the page.

The following screenshot shows an example of the `0` at the top of the page:

![image](https://user-images.githubusercontent.com/417342/223178341-99b38331-4d15-44ea-904e-6cf78e7e4a75.png)

This issue is reproducible in the trunk branch. It is introduced in [`177fc59` (#36541)](https://github.com/woocommerce/woocommerce/pull/36541/commits/177fc59deac5f5277ee4c8469cc5424bd2320912).

This issue happens because in the following code, we are using short-circuit evaluation on arrays. When the array lengths are 0, they will be rendered as literal `0` in the page.

https://github.com/woocommerce/woocommerce/blob/deb1d131add8d90fa4fda42ceaf573a38887d02a/plugins/woocommerce-admin/client/marketing/overview-multichannel/MarketingOverviewMultichannel.tsx#L47-L56

More references in the following links:

- https://reactjs.org/docs/jsx-in-depth.html?#booleans-null-and-undefined-are-ignored
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#short-circuit_evaluation
- [Why "0" is rendered on short-circuit evaluation of `array.length && ...`](https://stackoverflow.com/q/60652656/379641)

### Expected behavior

When there are no registered channels or recommended channels, there should be no literal `0` printed in the page.

### Actual behavior

When there are no registered channels or recommended channels, there is literal `0` printed in the page.

### Steps to reproduce

Pre-condition:

- Enable WooCommerce Multichannel Marketing experience in WooCommerce Settings > Advanced > Features (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`).

Setting up test data in code: 

- To ease testing, you can modify the following two hooks so that they return sample test data to reproduce the issue.

1. Replace this:

https://github.com/woocommerce/woocommerce/blob/deb1d131add8d90fa4fda42ceaf573a38887d02a/plugins/woocommerce-admin/client/marketing/hooks/useRecommendedChannels.ts#L22-L48

with this: 

```js
export const useRecommendedChannels = (): UseRecommendedChannels => {
	return {
		loading: false,
		data: [],
	};
};
```

2. Replace this: 

https://github.com/woocommerce/woocommerce/blob/deb1d131add8d90fa4fda42ceaf573a38887d02a/plugins/woocommerce-admin/client/marketing/hooks/useRegisteredChannels.ts#L62-L81

with this: 

```js
export const useRegisteredChannels = (): UseRegisteredChannels => {
	return {
		loading: false,
		data: [],
		refetch: () => {},
	};
};
```

Test steps: 

1. Go to Marketing page at `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing`.
2. You should see literal `0` (two `0`s if you modified both hooks) printed at the top of the page.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rawdreeg** [comment]
@ecgan. I'd like to have a look at this :-)

**Comment by ecgan** [comment]
@rawdreeg , sure, go ahead! 🙂 👍
