### ISSUE TITLE
Select all 'WooCommerce Endpoints' on 'Appearance → Menus' not working

### ISSUE THREAD

**Issue by burgerberg** [woothemes/woocommerce#37090]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On _Appearance → Menus_ the **Select All** option under the “WooCommerce Endpoints” section doesn't work.

![ksnip_20230306-200517](https://user-images.githubusercontent.com/22405364/223278031-6bf6cf2d-59fe-4289-8d7e-21de7d8347a4.png)

### Expected behavior

Clicking that link should auto select all WooCommerce endpoints.

### Actual behavior

Nothing happens.

### Steps to reproduce

1. Go to _Appearance → Menus_
2. Expand the “WooCommerce Endpoints” section under **Add menu items**
3. Click the **Select All** link

![ksnip_20230306-200517](https://user-images.githubusercontent.com/22405364/223276792-49311140-8dc3-40d5-8baa-f5146c130c4b.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://businessplan171484650.wpcomstaging.com
Site address (URL): https://businessplan171484650.wpcomstaging.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 11.29MB
Database Data Size: 9.22MB
Database Index Size: 2.07MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.08MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 1.39MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 2
attachment: 17
customize_changeset: 5
custom_css: 1
elementor_library: 1
jetpack_migration: 2
jp_img_sitemap: 5
jp_sitemap: 5
jp_sitemap_master: 5
nav_menu_item: 14
page: 19
post: 9
revision: 62
wp_block: 1
wp_global_styles: 18
wp_navigation: 1
wp_template: 1
wp_template_part: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 5.0.2
WordPress.com Editing Toolkit: by Automattic – 3.58296
Gutenberg: by Gutenberg Team – 15.2.4
Jetpack: by Automattic – 11.9-beta
WooCommerce: by Automattic – 7.4.1

### Inactive Plugins (13) ###

AMP: by AMP Project Contributors – 2.4.0
Classic Editor: by WordPress Contributors – 1.6.2
CoBlocks: by GoDaddy – 2.25.5
Crowdsignal Forms: by Automattic – 1.6.6
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

Elementor: by Elementor.com – 3.11.2
Google Listings and Ads: by WooCommerce – 2.3.10
Layout Grid: by Automattic – 1.8.2
Page Optimize: by Automattic – 0.5.2
Popups for Divi: by divimode.com – 3.0.5
Visual Composer: by visualcomposer.com – 45.1.2
WooCommerce Payments: by Automattic – 5.5.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #52 - /shop/
Cart: #53 - /cart/
Checkout: ❌ Page visibility should be public
My account: #55 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Lodestar
Version: 1.0.20-wpcom
Author URL: https://www.wordpress.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-07 19:06:11 -03:00
Options: ✔
Notes: 69
Onboarding: completed

### Action Scheduler ###

Complete: 577
Oldest: 2023-02-08 16:06:19 -0300
Newest: 2023-03-06 20:10:55 -0300

Failed: 3
Oldest: 2023-02-15 14:49:21 -0300
Newest: 2023-03-06 19:24:12 -0300

Pending: 1
Oldest: 2023-03-07 19:06:39 -0300
Newest: 2023-03-07 19:06:39 -0300

### Status report information ###

Generated at: 2023-03-06 20:13:10 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by carazo** [comment]
Good afternoon,

The problem is the last part of the DOM of the metabox.

You should use instead that should fix the problem.

`<p class="button-controls wp-clearfix" data-items-type="posttype-woocommerce-endpoints">
              <span class="list-controls hide-if-no-js">
                  <input type="checkbox" id="page-tab" class="select-all">
                  <label for="page-tab">Select All</label>
              </span>
              <span class="add-to-menu">
			<button type="submit" class="button-secondary submit-add-to-menu right" value="<?php esc_attr_e( 'Add to menu', 'woocommerce' ); ?>" name="add-post-type-menu-item" id="submit-posttype-clean-login-links"><?php esc_html_e( 'Add to menu', 'woocommerce' ); ?></button>
			<span class="spinner"></span>
		</span>
          </p>`

**Comment by samueljseay** [comment]
This menu is not available in core WooCommerce so I'm guessing this issue is specific to Wordpress.com or another plugin. I'll think about where we can move this report to.

**Comment by carazo** [comment]
@samueljseay,

Sorry but I think you are making a mistake.

You are not seeing that section in the menus because in "Screen options" you don't have it activated.

Regarding the code you have it here: https://plugins.trac.wordpress.org/browser/woocommerce/trunk/includes/admin/class-wc-admin-menus.php

Please check it.

**Comment by samueljseay** [comment]
@carazo apologies! Ok I'll take another look at this

**Comment by carazo** [comment]
Thanks :) 

I can do a PR but I thought it was easy to copy the code that fix the problem directly here.
