### ISSUE TITLE
Migrate the more menu to new skeleton using Gutenberg components

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37097]
### Description

Blocked until https://github.com/woocommerce/woocommerce/issues/37005 is merged.

We want to move the more menu (3 dots) with the **Share Feedback** and **Use classic editor** options to the new block editor header.

Make use of the existing more menu that comes with the Editor toolbar (slot fills?)

![Image](https://user-images.githubusercontent.com/2240960/223397063-0b3209ac-9746-4cdc-b75f-157500baae53.png)

### Design

![Image](https://user-images.githubusercontent.com/2240960/223398122-ff498d05-c63f-4506-8edd-773b52a205b1.png)

AkVNGImLgSqCObTQ3idVn7-fi-15%3A198

AkVNGImLgSqCObTQ3idVn7-fi-201%3A37558 (note this includes the **Welcome guide** option, that will be added in a future issue).

### Acceptance criteria

- [ ] More menu should be present in header
- [ ] More menu should include the **Share Feedback** and **Use the classic editor** options
- [ ] **Share Feedback** option should trigger CES
- [ ] **Use the classic editor** should direct users to the classic editor (similar to how it works in the current editor)

**Comment by joelclimbsthings** [comment]
@pmcpinto This PR includes adding the CES feedback option to the more menu. Do we want this event to include a flag indicating that it's the block editor now?

**Comment by pmcpinto** [comment]
Yes please. Thanks!
