### ISSUE TITLE
Edit lock on Woocommerce Order Page doesnt seem to work anymore on HPOS

### ISSUE THREAD

**Issue by herng77** [woothemes/woocommerce#37108]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Ever since switching to HPOS, our edit lock does not work anymore. 

I have tried to disable all plugins + changing to default theme but no avail.

### Expected behavior

When one user is editing the order in page for example: 

XXX.com/wp-admin/admin.php?page=wc-orders&id=2295628&action=edit

and another user wants to access, an error message will prompt showing that the user is currently editing.

### Actual behavior

Multiple users are able to enter and edit, no warning is shown.

### Steps to reproduce

1. Go to Woocommerce->Orders
2. Click on any post. 
3. Use another user account and go to the same post.
4. Both users able to edit the orders at the same time.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): --
Site address (URL): --
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.1
PHP Version: 8.0.25
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.5.18-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 36410.61MB
Database Data Size: 14563.05MB
Database Index Size: 21847.56MB

### Post Type Counts ###

attachment: 31376
attachment_order: 507
aw_workflow: 6
custom_css: 10
efbl_skins: 2
elementor_library: 61
elementor-hf: 1
ep-pointer: 1
ep-synonym: 7
feedback: 16
is_search_form: 1
mc4wp-form: 1
mif_skins: 1
ml-slide: 6
ml-slider: 4
nav_menu_item: 123
nf_sub: 2
oembed_cache: 46
page: 49
portfolio: 12
post: 14
postman_sent_mail: 250
product: 302
product_variation: 2105
revision: 201
shop_coupon: 22
shop_order: 1334678
shop_order_placehold: 8295
shop_order_refund: 22979
simple-pay: 1
um_directory: 1
um_form: 3
wc_conditional_fee: 1
wcp_ruleset: 2
wcpa_pt_forms: 143
wcsn_notification: 139
wp_global_styles: 1
wpforms: 5
wpshopcarts: 90
yith_refund_request: 1572
yith-wccos-ostatus: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.6.2
SEND SMS: by sonveer singh – 1.0.0
WooCommerce: by Automattic – 7.1.0 (update to version 7.4.1 is available)

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-2)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #5321 - /homepage/
Cart: #2856 - /shopping-cart/
Checkout: #7 - /checkout/
My account: #2858 - /account/
Terms and conditions: #5721 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 4.1.3 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-03-07 19:19:02 +08:00
Options: ✔
Notes: 16
Onboarding: completed

### Action Scheduler ###

Complete: 136
Oldest: 2023-02-05 14:12:18 +0800
Newest: 2023-03-07 23:39:52 +0800

Pending: 5
Oldest: 2023-03-08 21:31:39 +0800
Newest: 2023-03-13 08:28:38 +0800

### Status report information ###

Generated at: 2023-03-07 23:47:56 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by herng77** [comment]
Can I get any update on this matter?

**Comment by coreymckrill** [comment]
Hi @herng77, no update yet, but this is on our list.

**Comment by herng77** [comment]
Thanks @coreymckrill

**Comment by herng77** [comment]
any update on this?

**Comment by jorgeatorres** [comment]
Hi @herng77! I'm currently working on this. Once the PR is up, I'll post an update here. Thanks for your interest and sorry this is taking a bit longer than anticipated.
