### ISSUE TITLE
Add the summary field to the product form

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37103]
### Description

We should create a summary field and add this to the product form.
We will want to use the paragraph block for this field, because of the product form dependency this might require a new block that wraps around the Paragraph block.

#### Design

![Image](https://user-images.githubusercontent.com/2240960/223423302-b237222a-caf5-494d-916a-ee8bfa48dcb7.png)

AkVNGImLgSqCObTQ3idVn7-fi-202%3A20155

#### Acceptance criteria

* [ ] A summary field should be rendered in the product editor template within the basic details section (if the details section has been added already).
* [ ] The summary field should act the same as a Paragraph block.

**Comment by mdperez86** [comment]
@joshuatf @louwie17 How are we going to style such blocks like this one. Are we going to have global/per-block styles? Where should we place them? Are we going to re-use the already existing styles from prev experience?

**Comment by louwie17** [comment]
> How are we going to style such blocks like this one. Are we going to have global/per-block styles? Where should we place them? Are we going to re-use the already existing styles from prev experience?

Good question, and we should come to a conclusion for this relatively soon.
I think we should follow the current block pattern and have mostly per-block styles defined in the `style` & `editor` scss files and also makes use of the `supports` config for any styling that could be configured through a `theme.json`, but we can be conservative on this one.

The one thing I am currently not sure on is if the `scss` files require the `register_block_type_from_metadata` function to be triggered within php in order for the styles to be included. Although I see this being done in some blocks, but not others.
Maybe we want an alternate issue to tackle this?

I did create a draft issue to look into the use of a custom `theme.json` for the product editor.
