### ISSUE TITLE
wp-json/wp/v2/product no longer allows filtering on woocommerce taxonomies since 7.4.0

### ISSUE THREAD

**Issue by remcovg89** [woothemes/woocommerce#37105]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using wp-json to fetch product data the taxonomies from woocommerce are no longer available to filter the result

### Expected behavior

When a (taxonomy) filter is passed to wp-json it should filter the results

### Actual behavior

The (taxonomy) filter in wp-json/wp/v2/product is ignored. per_page, page & orderby etc. do seem to work. 

### Steps to reproduce

1. Create a custom product attribute (wp-admin/edit.php?post_type=product&page=product_attributes) with a custom sort order
2. Create Product, add it to a category and attach a custom product_attribute
3. Visit [your domain]/wp-json/wp/v2/product?per_page=9&page=1&orderby=title&order=asc
4. Add &product_cat=[any id]  or &[your_custom_product_attribute]=[any value] to the url. 
5. The values in step 4 no longer have any influence. This does work in woocommerce 7.3.0 but no longer works in 7.4.1

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://[redacted]
Site address (URL): https://[redacted]
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: tyvKxu_
Totale database grootte: 79.39MB
Database gegevens grootte: 51.76MB
Database index grootte: 27.63MB
tyvKxu_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
tyvKxu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tyvKxu_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
tyvKxu_woocommerce_order_itemmeta: Data: 7.52MB + Index: 6.03MB + Engine InnoDB
tyvKxu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tyvKxu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
tyvKxu_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_actionscheduler_logs: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
tyvKxu_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_comments: Data: 3.52MB + Index: 1.83MB + Engine InnoDB
tyvKxu_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_options: Data: 2.34MB + Index: 0.11MB + Engine InnoDB
tyvKxu_postmeta: Data: 19.55MB + Index: 16.06MB + Engine InnoDB
tyvKxu_posts: Data: 2.52MB + Index: 0.70MB + Engine InnoDB
tyvKxu_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
tyvKxu_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
tyvKxu_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tyvKxu_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tyvKxu_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_wc_customer_lookup: Data: 0.28MB + Index: 0.20MB + Engine InnoDB
tyvKxu_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_wc_order_product_lookup: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
tyvKxu_wc_order_stats: Data: 0.45MB + Index: 0.33MB + Engine InnoDB
tyvKxu_wc_order_tax_lookup: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
tyvKxu_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
tyvKxu_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_wc_product_meta_lookup: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
tyvKxu_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_wpml_mails: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
tyvKxu_wt_iew_action_history: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
tyvKxu_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tyvKxu_yoast_indexable: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
tyvKxu_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tyvKxu_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tyvKxu_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tyvKxu_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 175
nav_menu_item: 22
page: 14
post: 5
product: 106
product_variation: 508
revision: 36
shop_order: 4236
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

ManageWP - Worker: door GoDaddy – 4.9.16
Advanced Custom Fields PRO: door WP Engine – 6.0.7
Google Reviews Connector: door Lanthopus X – 1.0.0
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.7
LanthopusX UI Library editor: door Lanthopus X – 1.0.1
Mollie Payments for WooCommerce: door Mollie – 7.3.5
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 3.1.5
WooCommerce: door Automattic – 7.4.1
WordPress Importer: door wordpressdotorg – 0.8
Yoast SEO: door Team Yoast – 20.2.1
WP Mail Logging: door SendLayer – 1.10.5

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #46 - /winkel/
Winkelwagen: #47 - /winkelwagen/
Afrekenen: #48 - /afrekenen/
Mijn account: ❌ Pagina ID is aangegeven
maar de pagina bestaat niet

Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: [redacted]
Version: (update naar versie 0 is beschikbaar)
Author URL: 
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub thema aan. Zie: Hoe maak je eensub thema

WooCommerce Support: ✔

### Templates ###

Overrides: [redacted]theme/woocommerce/archive-product.php
[redacted]theme/woocommerce/cart/cart-empty.php versie 3.5.0 is verouderd. De hoofdversie is 7.0.1
[redacted]theme/woocommerce/cart/cart.php versie 3.8.0 is verouderd. De hoofdversie is 7.4.0
[redacted]theme/woocommerce/checkout/form-checkout.php
[redacted]theme/woocommerce/checkout/thankyou.php
[redacted]theme/woocommerce/content-product.php versie - is verouderd. De hoofdversie is 3.6.0
[redacted]theme/woocommerce/emails/email-addresses.php
[redacted]theme/woocommerce/emails/plain/email-addresses.php
[redacted]theme/woocommerce/loop/loop-end.php versie - is verouderd. De hoofdversie is 2.0.0
[redacted]theme/woocommerce/loop/loop-start.php versie - is verouderd. De hoofdversie is 3.3.0
[redacted]theme/woocommerce/loop/orderby.php
[redacted]theme/woocommerce/single-product.php versie - is verouderd. De hoofdversie is 1.6.4
[redacted]theme/woocommerce/taxonomy-product-cat.php versie 3.4.0 is verouderd. De hoofdversie is 4.7.0

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-08 11:45:48 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Afgerond: 273
Oldest: 2023-02-04 16:08:53 +0000
Newest: 2023-03-07 11:16:31 +0000

Mislukt: 27
Oldest: 2022-06-21 11:53:33 +0000
Newest: 2023-03-06 11:09:36 +0000

In afwachting: 1
Oldest: 2023-03-07 17:37:59 +0000
Newest: 2023-03-07 17:37:59 +0000

### Status report information ###

Generated at: 2023-03-07 14:45:14 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Thanks for the report! I'm going to close this in favor of #37291
