### ISSUE TITLE
[Enhancement]: RestAPI filter "FromID" -> Giving back items after the ID "12345"

### ISSUE THREAD

**Issue by frirari** [woothemes/woocommerce#37101]
### Describe the solution you'd like

We use the RestAPI, to get orders, products, customers, ... (i will name it "restitems") from WooCommerce to a customized order management program.
Now we want have a filter "AfterID" on the RestAPI, to get as axample all orders after the ID "12345".
To download all "restitems" and find out, in what page (pagination, offset) they requested IDs are, is very slow.

The RestAPI filter attribute should work like "per_page", "offset", and other filter attributes.

For example:
https://example.com/wp-json/wc/v3/orders?FromID=12345

The RestAPI now should give back all orders after the order ID 12345.

### Describe alternatives you've considered

Looking for the ID in the downloaded Items in the pagination.

**Comment by coreymckrill** [comment]
Hi @frirari, many of the rest api endpoints already have `before` and `after` [parameters](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders) available, which work similarly to what I think you're describing, except using creation date instead of ID. So for example, to get all orders that came after one with ID 12345, you would get the creation date of that order and then do a request like

`wc/v3/orders?after=2017-03-22T16:28:02`

Would that work for your use case?

**Comment by frirari** [comment]
Hello @coreymckrill  ,

Thanks for your feedback.
"after=" is not possible, because, "AfterID"  should work with all endpoints.

For example: 
If I try to read the date from products id 12345, to get the date for the
"after=" filter and products id is not existing, I will get back an error and
have to try, if products id 12346, 12347, 12348,... is existing.
For this, the "AfterID" filter will be the solution.

So the server should carry out the id resolve and not the client.
So this will save a lot of time.

**Comment by coreymckrill** [comment]
Hi @frirari,

Ok, I think I see what you're saying. It does seem like a bit of an edge case, though, as I would guess that the `before` and `after` parameters would work for most use cases. I suspect that this is not something we would consider adding to the current v3 of our REST API (could be a consideration for a future v4 though).

That said, you might be able to accomplish your goals using the [WP GraphQL](https://wordpress.org/plugins/wp-graphql/) plugin and its associated [WooGraphQL](https://github.com/wp-graphql/wp-graphql-woocommerce) add-on.
