### ISSUE TITLE
[Enhancement]: Show "Stock status" as a collection of radio buttons 

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37116]
The "Stock status" field is now displayed as a collection of radio buttons instead of a dropdown. However, if for any reason the number of items inside exceeds three, it should be displayed as a dropdown again.

<img width="547" alt="Screenshot 2023-03-08 at 17 02 53" src="https://user-images.githubusercontent.com/1314156/223835059-d4048b0f-f1e1-46af-be2d-d20b11be307d.png">

**Designs:**
[zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30925](https://href.li/?https://www.figma.com/file/zs56kcy53K7GoGhgyjcQ2R/?node-id=210%3A30925)

```[tasklist]
### Acceptance criteria
- [ ] Show "Stock status" as a collection of radio buttons.
- [ ] If the number of items inside exceeds three, it should be displayed as a dropdown again.
- [ ] Add a filter to verify whether the radio buttons will be shown.
```

**Comment by mattsherman** [comment]
We should add a filter to allow the dropdown rendering to be forced, in case a 3PD needs it for any reason.

**Comment by ninetyninew** [comment]
> We should add a filter to allow the dropdown rendering to be forced, in case a 3PD needs it for any reason.

Thank you for raising this, without it we would have needed to do lots of dev work due to this change.
