### ISSUE TITLE
[Enhancement]: Convert "Allow backorders?" into radio buttons

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37118]
Display "Allow backorders?" as a collection of radio buttons instead of a dropdown.

 ![screenshot-user-images githubusercontent com-2023 03 07-22_00_02 (3)](https://user-images.githubusercontent.com/1314156/223598221-8492ad0e-7653-4303-a6f5-2d2723807817.png)

**Designs:**
[zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30925](https://href.li/?https://www.figma.com/file/zs56kcy53K7GoGhgyjcQ2R/?node-id=210%3A30925)

```[tasklist]
### Acceptance criteria
- [ ] Convert "Allow backorders?" into radio buttons
- [ ] Add a filter to verify whether the radio buttons will be shown.
```

**Comment by mattsherman** [comment]
We should add a filter to allow the dropdown rendering to be forced, in case a 3PD needs it for any reason.
