### ISSUE TITLE
Hydrate product editor settings through API

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37124]
### Description

This is a follow up from #37120 where we are hydrating the editor settings through a localized script.
This is not a great approach as we can't load product specific settings. Due to the nature of our React router, this would only be possible by the use of an API endpoint.

There may already be an API endpoint available for this, or this data could be retrieved as part of some other endpoint, in my own research I only found the experimental API below:
Gutenberg does currently have an experimental API endpoint: https://github.com/WordPress/gutenberg/blob/trunk/lib/experimental/class-wp-rest-block-editor-settings-controller.php#L14
that this package makes a bit of use of `@wordpress/edit-site` -> https://github.com/WordPress/gutenberg/tree/trunk/packages/edit-site

We may actually want to create our own endpoint for this? As part of the WC REST api?

Here is an example of how the editor settings are currently hydrated: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/edit-form-blocks.php#L284
You can see that there are a lot of additional settings added to this list.

### Acceptance criteria

- [ ] Editor settings should be hydrated through an API call and data store
- [ ] Editor settings should be product specific (it should accept an product id).

**Comment by AnnaMag** [comment]
Note: the status here should be updated based on the cycle 39 work.

**Comment by pmcpinto** [comment]
@louwie17 do we still need this issue?

**Comment by louwie17** [comment]
> @louwie17 do we still need this issue?

Yes, this is still a good improvement, but not a priority.

**Comment by louwie17** [comment]
Closing this as it won't be relevant anymore.
