### ISSUE TITLE
[Enhancement]: Add tracks events to inventory layout

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37136]
Add tracks events to the inventory layout when:
- The [store settings link is displayed](https://github.com/woocommerce/woocommerce/issues/37115) when store-wide inventory tracking is disabled.
- The "Track stock quantity for this product" is toggled.
- The "Learn more" link in the message displayed at the top of the form (for variable products) [is clicked](https://github.com/woocommerce/woocommerce/issues/37119).

```[tasklist]
### Acceptance criteria
- [ ] The store settings link displayed when store-wide inventory tracking is disabled.
- [ ] The "Track stock quantity for this product" toggle.
- [ ] The "Learn more" link in the message displayed at the top of the form (for variable products).
```

**Comment by mattsherman** [comment]
@octaedro 

> The store settings link is displayed when store-wide inventory tracking is disabled.

I think we should actually track when the link is clicked, not when it is disabled. Do you agree?

**Comment by octaedro** [comment]
> I think we should actually track when the link is clicked, not when it is disabled. Do you agree?

Hey @mattsherman, I understood that the event intends to collect data from people who disabled the stock management, are creating a new product and using the inventory tab. 

But we can ask @jarekmorawski to confirm.

**Comment by mattsherman** [comment]
> > I think we should actually track when the link is clicked, not when it is disabled. Do you agree?
> 
> Hey @mattsherman, I understood that the event intends to collect data from people who disabled the stock management, are creating a new product and using the inventory tab.
> 
> But we can ask @jarekmorawski to confirm.

Ah, got it. Would be good to do both then. On a technical point, might be better to have a tracks event when the inventory tab is selected to track users using the inventory tab.

**Comment by jarekmorawski** [comment]
> I think we should actually track when the link is clicked, not when it is disabled. Do you agree?

100%. I agree that we should have both. The goal is to keep track of the number of people who go to settings from the updated inventory view (this will help us set better defaults in the future).
