### ISSUE TITLE
[Enhancement]: Option to disable update_api_key_last_access() function calls in REST API.

### ISSUE THREAD

**Issue by mindaugasbudreika** [woothemes/woocommerce#37144]
### Describe the solution you'd like

Personally I would love to see a constant which when defined would simply return without running $wpdb->update, e.g.

```
private function update_api_key_last_access( $key_id ) {
    if ( defined( 'WC_DISABLE_LAST_ACCESS_LOG' ) && WC_DISABLE_LAST_ACCESS_LOG ) {
        return;
    }

    global $wpdb;

    $wpdb->update(
        $wpdb->prefix . 'woocommerce_api_keys',
        array( 'last_access' => current_time( 'mysql' ) ),
        array( 'key_id' => $key_id ),
        array( '%s' ),
        array( '%d' )
    );
}
```

### Describe alternatives you've considered

- Alternative option could be a filter. 

- An option under settings (in my opinion would be an overkill)

### Additional context

I'm doing a lot of REST API requests and looking to reduce the request processing times and load on mysql as much as possible. 

I'm happy to create PR if this something that would be considered.

**Comment by jorgeatorres** [comment]
Hi @mch0lic,

Thanks for the report. We understand the need for better performance, more-so if you're performing lots of REST requests, but there's also a security aspect to the "last access" update, which can be used for logging/auditing purposes.

In our experience, writing this to the database is legible compared to the HTTP overhead of the request itself, but we might be missing something in your use-case. As such, would you mind expanding on what you're doing via REST? Maybe we just need to provide better support for batch operations of the kind you're doing. Why do you think this specific optimization will have a noticeable impact?

Looking forward to hearing back from you.

**Comment by mindaugasbudreika** [comment]
Im currently doing 100-200k rest api requests per day, mostly hitting products and orders end points.

I understand you have security concerns, but from my perspective, if I'm hitting an api once or twice a second the last access time has little value to me because all it shows is that we are processing the request using particular API key. It's useful feature when you doing a few requests, but simple monitoring tools can provide much more information (HTTP status, number of requests, request processing time, ip addresses, etc). Once again, I'm not asking to remove the feature, I'm only interested in a sensible opt out option here.

In terms of noticeable impact I don't expect to see a massive improvement, monitoring indicates average of around 30ms for this particular query, but it's a low hanging fruit worth picking.

<img width="1149" alt="Screenshot 2023-03-11 at 10 25 51" src="https://user-images.githubusercontent.com/1477518/224468970-1c4f9421-64c9-4f82-a095-103e7b4508cf.png">

**Comment by rrennick** [comment]
@mch0lic Thanks for the suggestion. This would be better implemented as a filter so that it can be enabled and disabled as needed during a request.

> I'm happy to create PR if this something that would be considered.

That sounds great. Could you use `woocommerce_disable_api_access_log` as the filter name?

**Comment by mindaugasbudreika** [comment]
Sure. Will create a PR on Monday/Tuesday and will follow up.

**Comment by mindaugasbudreika** [comment]
I've created a pull request https://github.com/woocommerce/woocommerce/pull/37332 for this issue.
