### ISSUE TITLE
Suggestion: Link to other core repos in readme (blocks, admin)

### ISSUE THREAD

**Issue by haszari** [woothemes/woocommerce#37156]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I came to this repo to investigate where a [WC core component (`Chip`)](https://woocommerce.github.io/woocommerce-blocks/?path=/story/woocommerce-blocks-base-components-chip--default) is used in the UI.

When I browse the readme, it gives a good meta-overview of the repo and tech, i.e. clone this repo and then install dependencies and then you will have all the code for WooCommerce.

It would be super helpful to include links to other key core repos in the readme, so GitHub users can browse their way to ALL the code that makes up WooCommerce. 

### Expected behavior

Links to WooCommerce Blocks and WooCommerce Admin repos (and any other relevant repos).

### Actual behavior

The only component/dependency linked is WooCommerce Core.

### Steps to reproduce

1. Go to repo homepage.
2. Scroll down to readme.
3. Try to find links to repos for all code that ships in WooCommerce package.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
I'll close this one as both WC Admin and Product blocks will be merged into this one by end of year.
