### ISSUE TITLE
[Enhancement]: Add tracks events to variations tab

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37150]
Add tracks events to the variations tab:

- The variations tab link (from any other tab or part of the product form).
- The "Attributes" link in the [new empty state](https://github.com/woocommerce/woocommerce/issues/37139) (when no attributes are added).
- The "Learn more" link in the [new empty state](https://github.com/woocommerce/woocommerce/issues/37139) (when no attributes are added).
- The "Generate variations" button in the [second new empty state](https://github.com/woocommerce/woocommerce/issues/37147) (when attributes are added, but the variations have not been generated yet).
- The "Add manually" button in the [second new empty state](https://github.com/woocommerce/woocommerce/issues/37147) (when attributes are added, but the variations have not been generated yet).
- The "Bulk actions" [dropdown](https://github.com/woocommerce/woocommerce/issues/37148).
- Each action selected in the "Bulk actions" [dropdown](https://github.com/woocommerce/woocommerce/issues/37148).

```[tasklist]
### Acceptance criteria
- [ ] The variations tab link (from any other tab or part of the product form).
- [ ] The "Attributes" link in the new empty state (when no attributes are added).
- [ ] The "Learn more" link in the new empty state (when no attributes are added).
- [ ] The "Generate variations" button in the second new empty state (when attributes are added, but the variations have not been generated yet).
- [ ] The "Add manually" button in the second new empty state (when attributes are added, but the variations have not been generated yet).
- [ ] The "Bulk actions" dropdown.
- [ ] Each action selected in the "Bulk actions" dropdown.
```

**Comment by mattsherman** [comment]
https://github.com/woocommerce/woocommerce/blob/93506388e34f7893691db4db0212b7b4d39cf9b0/plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts
