### ISSUE TITLE
Update button color in the Product and Orders empty state

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#37166]
**Description:** we need to update the button color in the Product and Orders pages' empty state to be aligned with the new color palette: p6riRB-8ox-p2

<img width="1276" alt="Captura de ecrã 2023-03-10, às 09 16 25" src="https://user-images.githubusercontent.com/3380168/224275663-71e4592c-b7a2-482f-a1bc-28de1af1b95e.png">
<img width="1249" alt="Captura de ecrã 2023-03-10, às 09 16 57" src="https://user-images.githubusercontent.com/3380168/224275666-a9ed335a-ffc3-4c32-8d24-c9a17ca49289.png">

**Acceptance criteria:**
- [ ] Update the button to the Woo 60 color in the Product and Orders pages' empty state

**Comment by pmcpinto** [comment]
@octaedro can you include this in the current cycle?

@jarekmorawski can you confirm that 60 is the right shade?

**Comment by jarekmorawski** [comment]
Yes, Woo 60 (#674399) for the resting state and Woo 70 (#533582) for the hover state.

However, I'd consider aligning these colors with the theme color. As you can see in the `Products` example, the pinkish button is displayed right next to another one. One follows the theme, and one doesn't.

Whatever changes we make here should extend to all empty states and parts of the core experience, including buttons and links.

**Comment by octaedro** [comment]
Hi @pmcpinto,

> can you include this in the current cycle?

Done! 🙂

**Comment by ecgan** [comment]
I was about to open an issue about button color (related to P2 post by @beaulebens: peapX7-1V3-p2) and I found this issue. 

@beaulebens mentioned that the button color should probably just use the WP primary color. 

@jarekmorawski mentioned the same thing in https://github.com/woocommerce/woocommerce/issues/37166#issuecomment-1463546357 as well:

> However, I'd consider aligning these colors with the theme color. As you can see in the `Products` example, the pinkish button is displayed right next to another one. One follows the theme, and one doesn't.

There are a few places where this color is used. Other than Product and Orders, we also have the following: 

Coupons page:

![image](https://user-images.githubusercontent.com/417342/224335455-cd1bc508-f868-435d-b8de-a84ff25b7c0a.png)

"Update WooCommerce database" button:

![image](https://user-images.githubusercontent.com/417342/224334891-f6ac111b-c2f6-4908-a54d-707131615b6c.png)

I'm thinking maybe there should just be one issue to remove all these purple button color and make use of the WP primary theme color? That would also be consistent with the use of `@wordpress/component`'s Button component in WooCommerce Admin.

**Comment by ecgan** [comment]
> I'm thinking maybe there should just be one issue to remove all these purple button color and make use of the WP primary theme color? That would also be consistent with the use of `@wordpress/component`'s Button component in WooCommerce Admin.

I have created issue https://github.com/woocommerce/woocommerce/issues/37172 for this.

**Comment by dlcallaway** [comment]
@beaulebens just wanted to check on the direction here, as we were JUST discussing updating these buttons within the Marketing team. We had talked about trying to get away from the pink buttons that feel a little too error-statey. Is it possible to use the newer Woo purples here, or does that have implications for core that we don't want to get into?

**Comment by beaulebens** [comment]
These colors are actually in core WC (not just on WP.com, which is where the pink color comes from).

I'll defer to whatever our design team ( @jarekmorawski ) want to do here. I tend to agree that going with matching WP's usage of color would be optimal (for a consistent experience throughout the entire wp-admin). 

We could separately consider shipping Woo with a WP color scheme (maybe even turning it on?) that would style the _entire_ wp-admin in a Woo color palette.

**Comment by jarekmorawski** [comment]
Let's ensure all buttons across wc-admin follow the WP color scheme and style (border, font size, padding). This will make them feel more consistent with wp-admin and reduce the overhead in the long term. We can devise other ways to introduce branding into the product experience.

**Comment by dougaitken** [comment]
Essentially this is a duplicate of #30829 so please double check that one for stale PR #30857 and anything else that's missing
