### ISSUE TITLE
[Enhancement]: Add tracks events to attributes tab

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37163]
Add tracks events to the attributes tab:

- The attributes tab link (from any other tab or part of the product form).
- The new "Add new" button in the empty state.
- The new "Add new" button when there's at least one attribute/form added.
- The new "Add existing" dropdown in the empty state.
- The new "Add existing" dropdown when there's at least one attribute/form added.
- The "Save attributes" button.

```[tasklist]
### Acceptance criteria
- [ ] The attributes tab link (from any other tab or part of the product form).
- [ ] The new "Add new" button in the empty state.
- [ ] The new "Add new" button when there's at least one attribute/form added.
- [ ] The new "Add existing" dropdown in the empty state.
- [ ] The new "Add existing" dropdown when there's at least one attribute/form added.
- [ ] The "Save attributes" button.

```

**Comment by AnnaMag** [comment]
@octaedro in case it is helpful, are you aware of https://github.com/woocommerce/woocommerce/pull/36858 and the 2 events we have in place for attributes management?

**Comment by octaedro** [comment]
Thank you @AnnaMag for the heads up. I didn't remember that PR 🙂
