### ISSUE TITLE
`useCampaigns` hook cannot be used with multiple instances

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#37177]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

This is a follow up to https://github.com/woocommerce/woocommerce/pull/37044#pullrequestreview-1330049691:

> 5. In the relevant processing of `getCampaigns` in wp-data store and `useCampaigns` hook, they don't include `perPage` as a part of the data key. It will lead to incorrect data and states if other implementations use a different `perPage` to request data someday.
>    - For example, when having more than 5 GLA campaigns, adding a line of code `useCampaigns( page, 10 );` to the `Campaigns` component could result in incorrect pagination.
> 
>       https://user-images.githubusercontent.com/17420811/223723790-bd981c12-431f-4816-868b-8afc49f393fd.mp4

In this issue, we should make `useCampaigns` hook able to be used multiple times with different `perPage` value. One way to achieve that is to make `perPage` value part of the data key in the wp.data redux store.

**Comment by eason9487** [comment]
Another point mentioned in https://github.com/woocommerce/woocommerce/pull/37044#pullrequestreview-1330049691 is highly relevant to this issue:

> 3. Although not causing actual problems at this moment, there is a concern about incorrect state caching within `useCampaigns`, which could lead to incorrect results in the future for standalone components like `Campaigns`.
> 
>    - `channels` was missed  in the [deps of `useSelect`](https://github.com/woocommerce/woocommerce/blob/97ed1d2a7d25a6511535e60edfb8edc26b066cc2/plugins/woocommerce-admin/client/marketing/overview-multichannel/Campaigns/useCampaigns.ts#L83).
>    - The potential problems could be simulated by returning the following code in the `MarketingOverviewMultichannel` component:
>      ```js
>      return (
>      	<div className="woocommerce-marketing-overview-multichannel">
>      		<Campaigns />
>      	</div>
>      );
>      ```
>    - The leading icons didn't appear:
>      ![image](https://user-images.githubusercontent.com/17420811/223717960-ee0ab991-364d-4d19-9482-ae4ba947b718.png)

I will adjust it together.

**Comment by ecgan** [comment]
@eason9487 , thank you so much for taking on this! 🙇
