### ISSUE TITLE
[HPOS] Order Query using two fields from operational data creates a duplicate join

### ISSUE THREAD

**Issue by mikkamp** [woothemes/woocommerce#37173]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using `wc_get_orders` with HPOS enabled allows us to perform a field query (implemented in #34533) and a date query (implemented in #34119).

However if we combine the two and make both of them compare data from the operational data table then we end up with a double join.

For example the following code:
```php
$orders = wc_get_orders(
	[
		'return'      => 'ids',
		'field_query' => [
			[
				'field'   => 'created_via',
				'value'   => 'rest-api',
				'compare' => '!=',
			],
		],
		'date_query'  => [
			[
				'column'    => 'date_paid_gmt',
				'after'     => '2020-01-01',
				'inclusive' => true,
			],
		],
	]
);
```

Results in the following query:
```
SELECT wp_wc_orders.id FROM wp_wc_orders
INNER JOIN `wp_wc_order_operational_data` ON ( `wp_wc_orders`.id = `wp_wc_order_operational_data`.order_id )
INNER JOIN wp_wc_order_operational_data ON ( wp_wc_orders.id = wp_wc_order_operational_data.order_id )
WHERE 1=1
AND (`wp_wc_order_operational_data`.`created_via` != 'rest-api')
AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed','wc-checkout-draft'))
AND (wp_wc_orders.type IN ('shop_order','shop_order_refund'))
AND ( ( 
  wp_wc_order_operational_data.date_paid_gmt >= '2020-01-01 00:00:00'
))
GROUP BY wp_wc_orders.id
ORDER BY wp_wc_orders.date_created_gmt DESC
LIMIT 0, 10
```

Notice the double JOIN and the difference in use of backticks. The difference in backticks isn't a deal breaker but the double join generates the DB error `WordPress database error Not unique table/alias` which unless DB errors are specifically surfaced just returns an empty set of results even though there are orders which match.

The double join seems to be caused by the difference in how the join is added to the array.

For the [field query it appends to the end of the array](https://github.com/woocommerce/woocommerce/blob/7.4.1/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableFieldQuery.php#L249):
```php
$this->join[] = $join;
```

Whereas for the [date query it uses the alias to add it to the array](https://github.com/woocommerce/woocommerce/blob/7.4.1/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php#L753):
```php
$this->join[ $alias ] = $sql_join;
```

The problem is resolved if I modify the field query to also use the same array index:
```php
$this->join[ $alias ] = $join;
```

I'd be happy to submit a oneliner PR to resolve this, however I wasn't sure if there are greater consequences by adjusting this code, and whether the inconsistent use of backticks could cause other problems. It also looks like a scenario which should be properly covered by a unit test.

### Expected behavior

A single JOIN to be performed regardless of which fields are queried

### Actual behavior

When two fields from the operational data are queried (one through a field query and the other through a date query) a duplicate join is done.

### Steps to reproduce

1. Create some orders where the date paid would be more recent than January 2020 and ensure they aren't created via the REST API
2. Run the following code snippet to confirm it returns an empty set of orders and generates a DB error:
```php
$orders = wc_get_orders(
	[
		'return'      => 'ids',
		'field_query' => [
			[
				'field'   => 'created_via',
				'value'   => 'rest-api',
				'compare' => '!=',
			],
		],
		'date_query'  => [
			[
				'column'    => 'date_paid_gmt',
				'after'     => '2020-01-01',
				'inclusive' => true,
			],
		],
	]
);

global $wpdb;
var_dump( $orders, $wpdb->last_query );
```

### WordPress Environment

Found the issue when testing with:
WooCommerce 7.4.1 (but also present in trunk)
WordPress 6.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Good catch, thank you for reporting :+1:
