### ISSUE TITLE
In the `Run tests on PR merge` Slack alert, change button blocks to markdown to remove warning notice

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#37187]
### Describe the solution you'd like

This is a follow-up task to address the review comment on https://github.com/woocommerce/woocommerce/pull/37033#discussion_r1132891687

To remove the "This app is not configured to handle interactive responses" warning, we could turn the link buttons to markdown blocks instead like shown [here](https://app.slack.com/block-kit-builder/T024FN1V2#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22API%20tests%20failed%20on%20%60test/pr-37033-trunk-lsinger%60%20after%20merging%20PR%20%3Chttps://github.com/woocommerce/woocommerce/pull/37073%7C#37073%3E%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22modification%20for%20reviewing%20a%20PR%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:pr-merged:%20View%20pull%20request%20%3Chttps://github.com/woocommerce/woocommerce/pull/37073%7C#37073%3E%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:alphabet-yellow-hash:%20View%20merge%20commit%20%3Chttps://github.com/woocommerce/woocommerce/commit/a41d880fcf94bd471165ce892df73041d4eeae70%7Ca41d880%3E%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:github:%20View%20GitHub%20run%20%3Chttps://github.com/woocommerce/woocommerce/actions/runs/4342292026%7C4342292026%3E%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:colorful-bar-chart:%20View%20test%20report%20%3Chttps://a8c-woo-test-reports.s3.amazonaws.com/public/pr-merge/37073/e2e/index.html%7Chere%3E%22%7D%7D,%7B%22type%22:%22divider%22%7D%5D%7D)

**Comment by adimoldovan** [comment]
This is obsolete, the workflow and the alert do not exist anymore, we moved to another CI setup in the meantime.
