### ISSUE TITLE
[Enhancement]: Add new action hook in `WC_Abstract_Order::remove_order_items`

### ISSUE THREAD

**Issue by melek** [woothemes/woocommerce#37219]
### Describe the solution you'd like

Add a `woocommerce_remove_order_items` action hook in `WC_Abstract_Order::remove_order_items`.

### Describe alternatives you've considered

Adding another instance of the `woocommerce_delete_order_items` action hook instead of introducing a new hook, but since the implementation and purpose of the `delete_order_items` function appears so different (it is used when an order is deleted, while `remove_order_items` is preparing an order for reuse at checkout), I'm anxious about possible side effects for plugins out there which may use the hook.

### Additional context

If an order is failed at checkout and then subsequently paid in the same session, `remove_order_items` is called on the existing, failed order to clear out the contents before it is refilled from the cart. I believe this flow is to cut down on noise, such as having a failed order for every failed payment attempt during the session, while making sure the order items match the current cart.

Applications which need to atomically track order changes use action hooks available when line items in orders are altered, but the `remove_order_items` function has no action hook which can be used. When tracking changes to an order, the result is that these initially failed orders end up with too many line items, since the removals are not able to be recorded, but the additions from the cart are.

p1678468401047469-slack-C7U3Y3VMY

**Comment by ashwinparthasarathi** [comment]
I would like to take this up during Contributor Day.
