### ISSUE TITLE
There is an 404 error on new Post/Page creation /wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-image-gallery.js

### ISSUE THREAD

**Issue by tatasha2004** [woothemes/woocommerce#37214]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is an 404 error on new Post/Page creation /wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-image-gallery.js

### Expected behavior

No errors

### Actual behavior

404 error
/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/product-image-gallery.js?ver=9.6.5 
![image](https://user-images.githubusercontent.com/30239355/225048108-79097fc5-d0e4-4ecd-b5a8-bd8527598c4a.png)

### Steps to reproduce

1. Install and activate Woo 7.5.0
2. Add a new post or page in the default editor and check the console

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://standalone.wordpress.test
Site address (URL): https://standalone.wordpress.test
WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 8.0.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.5.15-MariaDB-1:10.5.15+maria~focal
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.0
WC Database Prefix: muxee_
Total Database Size: 5.21MB
Database Data Size: 3.47MB
Database Index Size: 1.74MB
muxee_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
muxee_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
muxee_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
muxee_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
muxee_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
muxee_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
muxee_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_options: Data: 2.45MB + Index: 0.06MB + Engine InnoDB
muxee_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
muxee_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
muxee_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
muxee_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
muxee_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
muxee_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
muxee_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
muxee_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
muxee_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
muxee_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
muxee_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
muxee_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
muxee_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
muxee_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Query Monitor: by John Blackbourn – 3.11.2
WooCommerce: by Automattic – 7.5.0

### Inactive Plugins (19) ###

Advanced Custom Fields: by WP Engine – 6.0.7
Advanced Custom Fields: Extended: by ACF Extended – 0.8.9.2
Akismet Anti-Spam: by Automattic – 5.0.2
Classic Editor: by WordPress Contributors – 1.6.2
Custom Post Type UI: by WebDevStudios – 1.13.4
Custom_plugin: by YOUR NAME HERE – 0.1.0
Debug Bar: by wordpressdotorg – 1.1.4
Divi Builder: by Elegant Themes – 4.19.2
Easy Digital Downloads: by Easy Digital Downloads – 3.1.0.6
Elementor: by Elementor.com – 3.13.0-dev1
Elementor Beta (Developer Edition): by Elementor.com – 1.1.1
Elementor Pro: by Elementor.com – 3.11.4
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.9

Yoast SEO: by Team Yoast – 20.4-RC1
Yoast SEO: Local: by Team Yoast and Arjan Snaterse – 14.8
Yoast SEO: Video: by Team Yoast – 14.7
Yoast SEO: WooCommerce: by Team Yoast – 15.6
Yoast SEO premium (beta) | release/20.4 | 20.4-RC1 | 14-03-2023 11:26: by Team Yoast – 20.4-RC1
Yoast Test Helper: by Team Yoast – 1.17

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-15 15:09:57 +00:00
Options: ✔
Notes: 34
Onboarding: skipped

### Action Scheduler ###

Complete: 2
Oldest: 2023-03-14 15:11:09 +0000
Newest: 2023-03-14 15:11:09 +0000

Pending: 1
Oldest: 2023-03-15 15:11:09 +0000
Newest: 2023-03-15 15:11:09 +0000

### Status report information ###

Generated at: 2023-03-14 15:20:31 +00:00
`

### Status report information ###

Generated at: 2023-03-14 15:19:11 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
This has been fixed by https://github.com/woocommerce/woocommerce-blocks/pull/8445
