### ISSUE TITLE
[Enhancement]: LTR direction problem form RTL website

### ISSUE THREAD

**Issue by yekta-kalantary** [woothemes/woocommerce#37213]
### Describe the solution you'd like

all problem is on RTL webistes

i share some detail with image

1- first problem is on chooseing adress from searchable in setup wizard
- https://drive.google.com/file/d/1zZtM6B_gOz5pWA2-aIAFXmCnrZ_bUAOu/view?usp=sharing

2- email and mobile and postcode and password field must be left to right
all of field coniatn english charecter and number that have LTR direction
- https://drive.google.com/file/d/17fUWbAiVcVHcTQczibFE4GE_oflv4SAX/view?usp=sharing
- https://drive.google.com/file/d/1jm0CgkNjb4ZCkgvN-Lob82FdaXa__YVe/view?usp=sharing

**Comment by chihsuan** [comment]
Hey @yekta-kalantary Thanks for reporting this! Would you be able to provide the steps to reproduce this issue?

**Comment by adrianduffell** [comment]
I'll close this out as it pertains to the old setup wizard. @yekta-kalantary please re-open if it continues to be a problem in the newer wizard.
