### ISSUE TITLE
woocommerce-ro_RO.mo is triggering AddToCart Meta Pixel Event

### ISSUE THREAD

**Issue by vladvladau** [woothemes/woocommerce#37226]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I am using Meta Pixel in my website. I observed that even if I have registered only PageView pixel event, AddToCart is triggered as well when pressing Add to Cart button. Tracking down the issue I've identified that the woocommerce-ro_RO.mo is causing this behaviour.

Test scenario:

1. Have a default WooCommerce website
2. Install a Facebook/Meta Pixel only with PageView event
3. Press add to cart button (eg. on a variable product w/o choosing a variation) -> no additional event seen
4. Switch the website to Romanian language and update the translations
5. Repeat step 3 -> AddToCart event seen

I was not able to identify any strings which would lead to a fbq function call.
Let me know if other inputs are required.

**Comment by vladvladau** [comment]
This should be raised in other place.

**Comment by vladvladau** [comment]
Open issue as a reported bug: https://github.com/woocommerce/woocommerce/issues/37228

**Comment by psealock** [comment]
I will close this as a duplicate of https://github.com/woocommerce/woocommerce/issues/37228
