### ISSUE TITLE
woocommerce-ro_RO.mo is triggering AddToCart Meta Pixel Event

### ISSUE THREAD

**Issue by vladvladau** [woothemes/woocommerce#37228]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using Meta Pixel in my website. I observed that even if I have registered only PageView pixel event, AddToCart is triggered as well when pressing Add to Cart button. Tracking down the issue I've identified that the woocommerce-ro_RO.mo is causing this behaviour.

I was not able to identify any strings which would lead to a fbq function call.
Let me know if other inputs are required.

### Expected behavior

AddToCart pixel should not be sent unless explicity requested.

### Actual behavior

AddToCart pixel is sent without being triggered explicitly.

### Steps to reproduce

1. Have a default WooCommerce website
2. Install a Facebook/Meta Pixel only with PageView event
3. Press add to cart button (eg. on a variable product w/o choosing a variation) -> no additional event seen
4. Switch the website to Romanian language and update the translations
5. Repeat step 3 -> AddToCart event seen

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.origamiskates.com
Site address (URL): https://www.origamiskates.com
WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.36-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.0
WC Database Prefix: wpqp_
Total Database Size: 110.65MB
Database Data Size: 90.59MB
Database Index Size: 20.06MB
wpqp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wpqp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpqp_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wpqp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_actionscheduler_actions: Data: 11.02MB + Index: 6.27MB + Engine InnoDB
wpqp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_actionscheduler_logs: Data: 4.02MB + Index: 3.41MB + Engine InnoDB
wpqp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_atum_product_data: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_categorymeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wpqp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_litespeed_img_optm: Data: 0.34MB + Index: 0.17MB + Engine InnoDB
wpqp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqp_member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_options: Data: 10.39MB + Index: 0.45MB + Engine InnoDB
wpqp_order_dpd_address: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_order_dpd_courier: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_order_dpd_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_order_dpd_shipment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_order_dpd_tax_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_postmeta: Data: 18.41MB + Index: 5.92MB + Engine InnoDB
wpqp_posts: Data: 24.03MB + Index: 0.42MB + Engine InnoDB
wpqp_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqp_rank_math_analytics_inspections: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpqp_rank_math_analytics_objects: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpqp_rank_math_internal_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpqp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rank_math_redirections_cache: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_asset_seo_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_blocker_thumbnails: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_consent: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_rcb_presets: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_revision: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_revision_independent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_scan: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wpqp_rcb_scan_markup: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_stats_buttons_clicked: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_stats_custom_bypass: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_rcb_tcf_features: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_tcf_purposes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_tcf_special_features: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_tcf_special_purposes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_tcf_stacks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_rcb_tcf_vendors: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_real_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_slides: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_stock_log: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpqp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpqp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_term_relationships: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wpqp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpqp_usermeta: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wpqp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_vtprd_transient_cart_data: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpqp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpqp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpqp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_wc_euplatesc_trid: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wpqp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqp_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wpqp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wpqp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_wfconfig: Data: 1.28MB + Index: 0.00MB + Engine InnoDB
wpqp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wffilemods: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wpqp_wfhits: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wpqp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqp_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wpqp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wflogins: Data: 0.28MB + Index: 0.11MB + Engine InnoDB
wpqp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wpqp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpqp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wpqp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqp_wt_sc_coupon_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 698
custom_css: 1
customize_changeset: 1
elementor_library: 1
nav_menu_item: 47
oembed_cache: 10
page: 18
popup: 2
popup_theme: 8
porto_builder: 4
post: 10
product: 162
product_variation: 450
rcb-cookie: 3
revision: 382
seedprod: 1
shop_coupon: 38
shop_order: 193
shop_order_refund: 1
vtprd-rule: 1
wp_block: 6
wp_global_styles: 2
wpforms: 3
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

GTM4WP: by Thomas Geiger – 1.16.2
Elementor: by Elementor.com – 3.11.5
WPCode Lite: by WPCode – 2.0.8.1
Loco Translate: by Tim Whitlock – 2.6.4
Porto Theme - Functionality: by P-Themes – 2.8.2
Rank Math SEO: by Rank Math – 1.0.110
SmartBill WooCommerce: by Intelligent IT SRL – 1.4.12
WooCommerce Smart COD: by woosmartcod.com – 1.6.1
WooCommerce Euplatesc Gateway: by Zamfir Vladimir – 2.3.4
Ajax add to cart for WooCommerce: by QuadLayers – 2.0.2
Bulk Table Editor for WooCommerce: by Consortia – 2.2.16
Product Feed ELITE for WooCommerce: by AdTribes.io – 2.1.0
WooCommerce Checkout Manager: by QuadLayers – 7.0.8
WooCommerce: by Automattic – 7.5.0
Wordfence Security: by Wordfence – 7.9.1
WPForms Lite: by WPForms – 1.8.0.2
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.4.5
YITH WooCommerce Ajax Product Filter: by YITH – 4.20.0
YITH WooCommerce Wishlist: by YITH – 3.19.0

### Inactive Plugins (9) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.1.9
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 3.2
Duplicate Page: by mndpsingh287 – 4.5.1
Fast Velocity Minify: by Raul Peixoto – 3.4.0
LiteSpeed Cache: by LiteSpeed Technologies – 5.3.3
Real Cookie Banner: by devowl.io – 3.5.3
VarkTech Pricing Deals for WooCommerce: by Vark – 2.0.3.2
WPC Product Bundles for WooCommerce (Premium): by WPClever – 7.0.1
YITH WooCommerce Waitlist: by YITH – 2.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #8 - /magazin/
Cart: #9 - /cos/
Checkout: #10 - /checkout/
My account: #543 - /cont/
Terms and conditions: #669 - /termeni-si-conditii/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 6.8.2
Parent Theme Author URL: https://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details-customer.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-15 20:40:02 +02:00
Options: ✔
Notes: 119
Onboarding: completed

### Action Scheduler ###

Complete: 679
Oldest: 2023-02-12 11:23:44 +0000
Newest: 2023-03-15 00:33:19 +0000

Failed: 11,620
Oldest: 2022-09-14 12:33:25 +0000
Newest: 2023-03-14 15:15:44 +0000

Pending: 4
Oldest: 2023-03-15 04:42:10 +0000
Newest: 2023-03-19 22:14:09 +0000

### Status report information ###

Generated at: 2023-03-15 03:06:36 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vladvladau** [comment]
The events were triggered automatically due to automatic event detection configured on Meta Events Manager. There is no issue with the translation. of this language.

**Comment by coreymckrill** [comment]
Sounds like this is resolved, but feel free to reopen if there's still a problem here.
