### ISSUE TITLE
In the "Smoke test daily" workflow, run API tests against nightly build with plugins installed

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#37232]
### Describe the solution you'd like

In the "Smoke test daily" workflow, run API tests against nightly build with plugins installed. Currently, only the E2E tests were being ran.

**Comment by adimoldovan** [comment]
This is part of expanding the critical environments we run tests against and that is addressed in other projects. See https://github.com/orgs/woocommerce/projects/256
