### ISSUE TITLE
Wordpress Critical Error when activating

### ISSUE THREAD

**Issue by SK-Crow** [woothemes/woocommerce#37231]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Brand new website.  Latest wordpress.  No plugins installed.  Default 2023 theme.  No content.  Completely clean install.

I go to the plugin hub, install the plugin.  This works fine.

I then go activate the plugin, and wordpress throws a critical error.

PHP 8.2
Apache 2.4.55 (FreeBSD)

### Expected behavior

Expected install to work.

### Actual behavior

Critical error:

`Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderTableMigrator::$table_names is deprecated in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderTableMigrator.php on line 25

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderAddressTableMigrator::$table_names is deprecated in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderAddressTableMigrator.php on line 42

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderAddressTableMigrator::$table_names is deprecated in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderAddressTableMigrator.php on line 42

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderOpTableMigrator::$table_names is deprecated in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderOpTableMigrator.php on line 26

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostMetaToOrderMetaMigrator::$table_names is deprecated in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostMetaToOrderMetaMigrator.php on line 43

Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Blocks\Payments\Integrations\filter_var() in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Integrations/Cheque.php:49 Stack trace: #0 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(28): Automattic\WooCommerce\Blocks\Payments\Integrations\Cheque->is_active() #1 [internal function]: Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->Automattic\WooCommerce\Blocks\Payments\{closure}() #2 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(25): array_filter() #3 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(40): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_active_registered() #4 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(66): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_active_payment_method_script_dependencies() #5 /usr/local/www/apache24/data/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_dependencies() #6 /usr/local/www/apache24/data/wp-includes/plugin.php(205): WP_Hook->apply_filters() #7 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/Api.php(157): apply_filters() #8 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(130): Automattic\WooCommerce\Blocks\Assets\Api->register_script() #9 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/Cart.php(250): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->register_block_type_assets() #10 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(115): Automattic\WooCommerce\Blocks\BlockTypes\Cart->register_block_type_assets() #11 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(70): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->initialize() #12 /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypesController.php(64): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->__construct() #13 /usr/local/www/apache24/data/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\BlockTypesController->register_blocks() #14 /usr/local/www/apache24/data/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #15 /usr/local/www/apache24/data/wp-includes/plugin.php(517): WP_Hook->do_action() #16 /usr/local/www/apache24/data/wp-settings.php(617): do_action() #17 /usr/local/www/apache24/data/wp-config.php(181): require_once('...') #18 /usr/local/www/apache24/data/wp-load.php(50): require_once('...') #19 /usr/local/www/apache24/data/wp-admin/admin.php(34): require_once('...') #20 /usr/local/www/apache24/data/wp-admin/plugins.php(10): require_once('...') #21 {main} thrown in /usr/local/www/apache24/data/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Integrations/Cheque.php on line 49
There has been a critical error on this website. Please check your site admin email inbox for instructions.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)`

### Steps to reproduce

1. Install wordpress
2. Install WooCommerce
3. Activate

### WordPress Environment

No can do.  This is an issue while activating the plugin.  I don't have that option yet.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Hi @coolpick ! Thanks for this - as a matter of interest, can you let us know what WooCommerce version you were attempting to install?

**Comment by SK-Crow** [comment]
> Hi @coolpick ! Thanks for this - as a matter of interest, can you let us know what WooCommerce version you were attempting to install?

WooCommerceVersion 7.5.0 - Latest build on the Wordpress plugin hub.  
WordPress 6.1.1 - Latest on Wordpress.org

**Comment by SK-Crow** [comment]
Downgrading to PHP 8.1 resolved my issue.
