### ISSUE TITLE
Product template extensibility via PHP

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#37248]
It's currently possible to extend the product blocks template via PHP, but we should look into real use cases and patterns for how 3PDs might extend this.

```
function register_product_template() {
    $post_type_object = get_post_type_object( 'product' );
    $post_type_object->template = array(
        array( 'core/image' ),
    );
}
add_action( 'init', 'register_product_template', 100 );
```

Some things to think about while tackling this:

* If we extend by just looping over the template and finding/inserting blocks, what might that code look like?
* Are there wrapper functions we can use to make this easier for 3PDs?
* Should we introduce `plugin` namespaces to identify plugins inserting blocks into the new experience to improve merchant experience?

### Acceptance criteria

* [ ] Examples of how to create a new tab and section
* [ ] Examples of inserting custom blocks
* [ ] (Optional) Wrapper function for inserting blocks into various tabs/sections
* [ ] Documentation on how to extend the product template

**Comment by mattsherman** [comment]
Closing -- tempting is implemented already for the new product editor.
