### ISSUE TITLE
Create Block Editor Modal window for use in product description

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37266]
**Description**

We want users to have the ability to add a description field to a product and will allow users to use the block editor for this.
Instead of displaying the block editor within the product block form we will be displaying a modal instead (see screenshot below).

As mentioned by @jarekmorawski in the comments below, we currently have something [similar in P2](https://github.com/Automattic/p2/blob/18c0fcecde16ab20d2fc9c389ce8993ff7d97eb2/plugins/p2/src/client/core/editor/components/editor-core/index.js) ( private repo ) when selecting **New Post**.
It appears they are making use of the IsolatedBlockEditor: https://github.com/Automattic/isolated-block-editor/tree/trunk
Not sure if we want to make use of this because of the additional overhead, it will depend on how easily we can re-create out own version.

This issue will focus on creating this Modal component. The Modal should include a full version of the block editor without the preview, publish, save buttons.
We may want to limit the supported blocks for now to:
- Paragraph
- Image
- List
- Heading
- Quote
- Video

While we will be using this primarily for the description field this Modal should stay relatively abstract, so it can be re-used for other content based fields.

**Design**

![Image](https://user-images.githubusercontent.com/2240960/225607615-ef308cc9-a03b-49f1-b8db-1398453b7d73.png)

AkVNGImLgSqCObTQ3idVn7-fi-205-27251

**Acceptance criteria**

- [ ] Have a re-useable component that triggers a modal with the block editor, this should include its own `onChange` callbacks
- [ ] Add a story book (if possible) for testing the Modal (if not possible, maybe a way to trigger it from the console? )

**Comment by louwie17** [comment]
@jarekmorawski when working on these designs did you see if there is something similar available within Gutenberg at this moment? Or is Gutenberg working on something similar?

**Comment by jarekmorawski** [comment]
Not Gutenberg, but P2. You can see something very similar when you click `New post`.

**Comment by louwie17** [comment]
Hey @jarekmorawski we discussed this issue as a team yesterday and came to the conclusion that this will likely require a lot work, which may push the initial release of the product block editor if we are relying on the description field being ready.

We will do an initial spike ([#37290](https://github.com/woocommerce/woocommerce/issues/37290)) into exactly how much work this will take, but also curious if it seems reasonable to use an inline description field for now similar to what the product editor had prior to the block one?
We could then iterate on it by adding support for this Modal.

Let me know what you think? (cc: @pmcpinto )

**Comment by pmcpinto** [comment]
> We will do an initial spike (https://github.com/woocommerce/woocommerce/issues/37290) into exactly how much work this will take, but also curious if it seems reasonable to use an inline description field for now similar to what the product editor had prior to the block one?
> We could then iterate on it by adding support for this Modal

I'm ok with removing the modal from the initial release. It will be helpful to have the spike included in the cycle starting this week, to have more clarity on the time & effort required to implement the modal. Thanks
