### ISSUE TITLE
Add icon support to product section block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37264]
**Description**

Product sections also include an icon to the left side of the title as part of the design.
Currently we only support a title and description. This issue would be to add support for an icon, which can be added through the template config.

Have a look at the current implementation of GB for blocks, look at `BlockIcon`.

**Design**

![Image](https://user-images.githubusercontent.com/2240960/225605930-5df567ad-01cc-4a90-b0e4-ff25c9be2b59.png)

AkVNGImLgSqCObTQ3idVn7-fi-10-139

**Acceptance criteria**

- [ ] Product section block should render an icon next to the title if provided with one ( should be optional ).

**Comment by joshuatf** [comment]
Here's the Gutenberg BlockIcon for reference - https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/block-icon/README.md
