### ISSUE TITLE
[Enhancement]: Add PATCH-Method (for products)

### ISSUE THREAD

**Issue by sokratis1988** [woothemes/woocommerce#37262]
### Describe the solution you'd like

Currently, WooCommerce only supports the PUT method for updating resources. However, there are situations where a more granular update of a resource is required, without having to send the entire resource in the request. This is where the PATCH method comes in handy.

For example, let's say you have a product in WooCommerce with multiple attributes such as title, description, price, etc. If you wanted to update just the price of the product, you would have to send the entire product object in the request body using the PUT method. This can be inefficient, especially if the product object is large.

With the PATCH method, you can send only the fields that need to be updated in the request body, thus reducing the amount of data being sent over the network. This can lead to improved performance and reduced network latency.

In addition, the PATCH method allows for partial updates of a resource, which can be useful in scenarios where you need to update only certain fields of a resource, without affecting the others.

Therefore, adding support for the PATCH method in WooCommerce would provide more flexibility and efficiency in updating resources, and would align with RESTful best practices for API design.

### Describe alternatives you've considered

Using the PUT method with the entire resource: While not as efficient as the PATCH method, using the PUT method with the entire resource would still allow for updating of the resource. This method may be sufficient for smaller resources, but could be inefficient for larger resources.

Creating custom endpoints: Instead of using the existing endpoints in WooCommerce, custom endpoints could be created to support the PATCH method. This would require additional development effort but would provide more granular control over the API.

Using third-party plugins: There may be third-party plugins available that add support for the PATCH method in WooCommerce. However, using third-party plugins can introduce additional dependencies and potential security risks.

**Comment by coreymckrill** [comment]
Hi @sokratis1988, the WooCommerce rest api is built on top of the WordPress rest api, which supports all three of `POST`, `PUT`, and `PATCH` for updating entities (as seen [here](https://github.com/WordPress/WordPress/blob/1b393fbb15de13089b5c97a9c3975b642fbfbf7b/wp-includes/rest-api/class-wp-rest-server.php#L34-L40)).

Furthermore, I believe you can actually do a partial update of an entity (e.g. product) using the `PUT` method. If you make a request similar to the following (simplified for this example) it will update the SKU of the product without affecting any of the other product fields:

```
curl --request PUT \
  --url http://localhost:8888/wp-json/wc/v3/products/1376 \
  --data '{
	"id": 1376,
	"sku": "awesome-wooden-hat-123456"
}'
```
