### ISSUE TITLE
Shipping cost disabled on checkoutpage wc update 7.5

### ISSUE THREAD

**Issue by MIQvTRONIC** [woothemes/woocommerce#37274]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With Woocommerce 7.5  shipping methode on checkout page is disabled. 

+ I use Cartflow to manage checkout design and Order delivery date pro for my delivery system

### Expected behavior

Be able to people choose a shipping methode 

### Actual behavior

Shipping methode area is blank a.k.a shipping methode is disabled , only a little questionmark shows up wich contains the following:
 " there is currently no shipping methode availble "
While Im still able to change all my shipping methode settings in the Woocommerce settings. 
People can still order something but with no shipping cost calculated, nothing asked so nothing paid.
 
With downgrading Woocommerce back to 7.4.1 it works perfectly.
 
I also get no php error's or something like that. 

### Steps to reproduce

Updating Woocommerce to 7.5

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.la-vie-en-rosie.be
Site address (URL): https://www.la-vie-en-rosie.be
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: nl_BE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.17
PHP Post Max Size: 256 MB
PHP Time Limit: 30000
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: Ex6_
Totale databasegrootte: 110.60MB
Database datagrootte: 83.76MB
Database index grootte: 26.84MB
Ex6_woocommerce_sessions: Data: 0.34MB + Index: 0.02MB + Engine MyISAM
Ex6_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_order_items: Data: 0.52MB + Index: 0.32MB + Engine MyISAM
Ex6_woocommerce_order_itemmeta: Data: 7.60MB + Index: 4.02MB + Engine MyISAM
Ex6_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_actionscheduler_actions: Data: 0.28MB + Index: 0.16MB + Engine MyISAM
Ex6_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_actionscheduler_logs: Data: 0.22MB + Index: 0.17MB + Engine MyISAM
Ex6_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_cartflows_visits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_cartflows_visits_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_comments: Data: 1.99MB + Index: 0.81MB + Engine MyISAM
Ex6_cptslotsbk_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
Ex6_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Ex6_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
Ex6_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
Ex6_e_submissions_values: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
Ex6_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
Ex6_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_jetpack_waf_blocklog: Data: 0.28MB + Index: 0.02MB + Engine InnoDB
Ex6_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_mobileassistant_failed_login: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_mobileassistant_push_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_mobileassistant_session_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_mobileassistant_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_mollie_pending_payment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_mo_openid_linked_user: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_options: Data: 7.84MB + Index: 0.18MB + Engine MyISAM
Ex6_postmeta: Data: 17.26MB + Index: 7.29MB + Engine MyISAM
Ex6_posts: Data: 11.42MB + Index: 0.43MB + Engine MyISAM
Ex6_stream: Data: 2.52MB + Index: 1.48MB + Engine InnoDB
Ex6_stream_meta: Data: 5.52MB + Index: 7.55MB + Engine InnoDB
Ex6_tcp_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_ordersmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_orders_costs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_orders_costsmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_orders_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_orders_detailsmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_tcp_taxes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
Ex6_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_term_relationships: Data: 0.03MB + Index: 0.08MB + Engine MyISAM
Ex6_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_usermeta: Data: 0.99MB + Index: 0.46MB + Engine MyISAM
Ex6_users: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
Ex6_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
Ex6_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
Ex6_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_wc_customer_lookup: Data: 0.17MB + Index: 0.17MB + Engine MyISAM
Ex6_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
Ex6_wc_order_product_lookup: Data: 0.76MB + Index: 0.64MB + Engine MyISAM
Ex6_wc_order_stats: Data: 0.22MB + Index: 0.15MB + Engine MyISAM
Ex6_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
Ex6_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
Ex6_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Ex6_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
Ex6_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wffilemods: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
Ex6_wfhits: Data: 1.52MB + Index: 0.08MB + Engine InnoDB
Ex6_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Ex6_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
Ex6_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
Ex6_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Ex6_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Ex6_wfstatus: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
Ex6_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_woocommerce_kbccw_cc: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_woocommerce_kbccw_documents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_woocommerce_kbccw_ecc: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
Ex6_woocommerce_kbccw_schema_version: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Ex6_woocommerce_kbccw_storage: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_woocommerce_kbccw_transactions: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
Ex6_wpforms_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
Ex6_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Ex6_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
Ex6_wpstg_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_yoast_indexable: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
Ex6_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Ex6_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
Ex6_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Ex6_zbs_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_zbs_customfields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Ex6_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Ex6_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_externalsources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
Ex6_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Ex6_zbs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
Ex6_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_tags_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Ex6_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Ex6_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
Ex6_zp_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

astra_adv_header: 1
attachment: 188
br_sale_report: 1
cartflows_flow: 1
cartflows_step: 2
custom_css: 1
elementor-hf: 1
elementor_library: 5
extb_post_footer: 1
extb_post_header: 2
extb_post_json: 10
extb_post_main: 4
extb_post_sidebar: 2
gfw_report: 1
giftcard: 4
gift_card: 34
jb_store_css: 1
ml-slide: 9
ml-slider: 1
nav_menu_item: 20
oembed_cache: 11
omapi: 3
page: 22
post: 1
product: 77
product_variation: 35
revision: 242
shop_coupon: 291
shop_order: 2979
shop_order_refund: 10
tt_font_control: 1
wbcr-snippets: 4
wcpa_pt_forms: 3
wp-rest-api-log: 460
wpt_product_table: 1
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Add Customer for WooCommerce: door Dan's Art – 1.6.5
Akismet Anti-Spam: door Automattic – 5.0.2
Astra Pro: door Brainstorm Force – 4.0.1
CartFlows: door CartFlows Inc – 1.11.9
Elementor Pro: door Elementor.com – 3.11.6
Elementor: door Elementor.com – 3.11.5
Error Log Monitor: door Janis Elsts – 1.7.4
Elementor Header & Footer Builder: door Brainstorm Force
Nikhil Chavan – 1.6.13

Health Check & Troubleshooting: door The WordPress.org community – 1.5.1
WooCommerce Attribute Swatches by Iconic: door Iconic  – 1.14.2
Imagify: door Imagify – Optimize Images & Convert WebP – 2.1.1
Jetpack Boost: door Automattic - Jetpack Site Speed team – 1.7.0
Jetpack: door Automattic – 11.9.1
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.7
Maintenance: door WebFactory Ltd – 4.07
Mobile Assistant Connector: door eMagicOne – 2.2.4
Order Delivery Date Pro for WooCommerce: door Tyche Softwares – 10.2.1
Quttera Web Malware Scanner: door Quttera team – 3.4.0.80
Astra Customizer Reset: door Brainstorm Force – 1.0.6
SiteOrigin CSS: door SiteOrigin – 1.5.5
Stream: door XWP – 3.9.2
WooCommerce Custom Product Addons (Free): door Acowebs – 2.7.5
Checkout Field Editor for WooCommerce (Pro): door ThemeHigh – 3.4.0
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.4.0
WooCommerce: door Automattic – 7.4.1 (bijgewerkt naar versie 7.5.0 is beschikbaar)
WooCommerce KBCCw: door customweb GmbH – 3.0.77
Wordfence Security: door Wordfence – 7.9.1
Yoast SEO: door Team Yoast – 20.3
WP Rocket: door WP Media – 3.12.6.1
WP Rollback: door GiveWP.com – 1.7.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Endurance Page Cache: door Mike Hansen – 2.2
Ensure admin user isn't deleted: door  – 1.0
Health Check Troubleshooting Mode: door  – 1.7.2
installatron_hide_status_test.php: door  –
SSO: door Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: ❌ Pagina niet ingesteld
Winkelwagen: #965 - /winkelmandje/
Afrekenen: #159 - /checkout-2-2/
Mijn account: ❌ Pagina ID is aangegeven
maar de pagina bestaat niet

Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-16 15:58:07 +01:00
Options: ✔
Notes: 88
Onboarding: completed

### Action Scheduler ###

Complete: 447
Oldest: 2023-02-13 16:48:10 +0100
Newest: 2023-03-16 16:16:26 +0100

Failed: 134
Oldest: 2022-10-30 02:30:14 +0100
Newest: 2023-03-16 15:29:24 +0100

Pending: 7
Oldest: 2023-03-16 16:17:26 +0100
Newest: 2023-03-31 03:59:33 +0200

### Status report information ###

Generated at: 2023-03-16 16:17:57 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
>I use Cartflow to manage checkout design and Order delivery date pro for my delivery system

@MIQvTRONIC Can you confirm the problem still exists when Cartflow is temporarily disabled?

**Comment by MIQvTRONIC** [comment]
@psealock Somehow I did over see the cartflow plugin. Indeed it works perfectly if i disable cartflow. 
Is there a solution for this ? Or do I need to contact cartflow for this problem ?

**Comment by psealock** [comment]
>Or do I need to contact cartflow for this problem ?

Without diving into the Cartflow code I don't have a solution on hand unfortunately. I think the best course of action is to raise the issue with Cartflow.
