### ISSUE TITLE
`--shipping_class` parameter not working with `wp wc product list`

### ISSUE THREAD

**Issue by luboslives** [woothemes/woocommerce#37271]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`wp wc product list` takes a parameter of `--shipping_class` where we can specify a class by its name. I am assuming it's specified by name and not by the term ID, as there is also a table row named `shipping_class_id` in the default printout. 

The following query produces no result:

`wp wc product list --per_page=10 --shipping_class=<class-name> --user=1`

We can, however, print the shipping class names just fine with a command like this:

`wp wc product list --field=shipping_class --per_page=10 --user=1`

Can others replicate this problem?

### Expected behavior

A print out of products with the given shipping class. For example:

`wp wc product list --field=id --per_page=10 --shipping_class=cds --user=1`

Result:

```
52362
52274
52271
...
```

### Actual behavior

No result is printed and the operation exits.

### Steps to reproduce

1. cd to your website's home directory as the owning user.
2. Run the WP CLI command, using a real shipping class from your own site, and your own WP admin's user ID: `wp wc product list --per_page=10 --shipping_class=<class-name> --user=1`
3. Did it print a result?

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): staging area, hidden IP and port
Site address (URL): staging area, hidden IP and port
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 120 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.3.35-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 324.94MB
Database Data Size: 183.70MB
Database Index Size: 141.24MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 55.58MB + Index: 31.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_comments: Data: 14.52MB + Index: 13.09MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.50MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 64.59MB + Index: 64.22MB + Engine InnoDB
wp_posts: Data: 14.52MB + Index: 8.06MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_tinvwl_analytics: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_tinvwl_items: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wp_wccs_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wccs_condition_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.23MB + Index: 0.31MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 4.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.30MB + Index: 0.27MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.19MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_wdp_order_items: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woo_sales_country_region: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 4
acf-field: 2
acf-field-group: 1
attachment: 7640
awdp_pt_products: 1
awdp_pt_rules: 1
cdn_label_artist: 75
condition_group: 12
faq: 17
flamingo_contact: 2833
flamingo_inbound: 1210
hurrytimer_countdown: 1
ll_slider: 46
nav_menu_item: 20
oembed_cache: 1073
page: 16
post: 107
product: 7053
product_variation: 99
revision: 477
shop_coupon: 82
shop_order: 8523
shop_order_refund: 8
sidebar: 3
vtprd-rule: 8
wafs: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Advanced Custom Fields: by WP Engine – 6.0.7
WooCommerce Blacklister: by Aelia – 1.0.5.200727
Arconix FAQ: by Tyche Softwares – 1.9.2
Block List Updater: by pluginkollektiv – 1.0.0
CDN Records Label Artists: by luboslives – 1.0.0
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.7.4
Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.18.1
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Flamingo: by Takayuki Miyoshi – 2.3
Simple Store Sliders: by luboslives – 0.10.7
PayPal for WooCommerce: by Angell EYE – 3.1.6
Product Visibility by Country for WooCommerce Pro: by WP Wham – 1.4.8
Recent Posts Widget With Thumbnails: by Kybernetik Services – 7.1.1
Rank Math SEO: by Rank Math – 1.0.110.1
TI WooCommerce Wishlist: by TemplateInvaders – 2.3.6
Transients Manager: by WPBeginner – 2.0.3
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.1.230214
WooCommerce Weight Based Shipping +: by weightbasedshipping.com – 5.3.15
Woo Attributes Coupon: by Gaurav Nagpal – 2.2.0
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.38

WooCommerce Extended Coupon Features FREE: by Soft79 – 3.3.3
WooCommerce Brands: by WooCommerce – 1.6.2
WooCommerce Product Bundles: by WooCommerce – 6.14.0
WooCommerce Sort By Stock: by Brandon Yanofsky – 2.2.0
WooCommerce: by Automattic – 7.4.0 (update to version 7.5.0 is available)

### Inactive Plugins (14) ###

Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.3.0
Angell EYE Updater: by Angell EYE – 2.0.18
Duplicate Post Page Menu & Custom Post Type: by Inqsys Technology – 2.3.1
GDPR Cookie Compliance: by Moove Agency – 4.10.5
HurryTimer: by Nabil Lemsieh – 2.7.3
Inactive User Deleter: by Korol Yuriy aka Shra <to@shra.ru> – 1.58
LiteSpeed Cache: by LiteSpeed Technologies – 5.3.3
Login No Captcha reCAPTCHA (Google): by Robert Peake and Contributors – 1.7.1
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.5.6
Product Sales Report for WooCommerce: by WP Zone – 1.5.3
Query Monitor: by John Blackbourn – 3.11.2
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.4.3
Sales Report By Country for WooCommerce: by zorem – 1.6.5
WooCommerce Accounting Report: by BjornTech – 2.1.4

### Dropin Plugins (1) ###

install.php: install.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #25025 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Product Visibility by Country Settings ###

Product Visibility by Country: yes
License Key: (set)
Hide catalog visibility: no
Make non-purchasable: yes
Hide visibility in "WooCommerce Blocks": no
Modify query: no
Redirect URL.: 
Modify widget query: no
Hide price: no
Content: 
Info on single product page: yes
Content: This product does not ship to your current location.
Info on archives: no
Content: The product is not available in your country.
Admin products list column: no
Select box type: chosen_select
Hide product terms: yes
Hide products: 
Debug mode: 
Disable URL: 
Queries: 
Check post type: 
Use simple redirect: 

### Product Bundles ###

Database Version: 6.14.0
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-17 09:17:15 -04:00
Options: ✔
Notes: 30
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 621
Oldest: 2023-02-13 09:46:21 -0500
Newest: 2023-03-16 06:13:39 -0400

Pending: 3
Oldest: 2023-03-16 09:15:56 -0400
Newest: 2023-03-17 06:11:52 -0400

Failed: 7
Oldest: 2022-09-26 05:07:57 -0400
Newest: 2023-03-04 14:50:57 -0500

### Status report information ###

Generated at: 2023-03-16 09:15:59 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
> wp wc product list --field=id --per_page=10 --shipping_class=cds --user=1

Have you tried passing the shipping_class id instead of the name? You can see shipping classes and their id's with `wp wc product_shipping_class list --user=1`.

```
wp wc product list --help

...

[--shipping_class=<shipping_class>]
    Limit result set to products assigned a specific shipping class ID.
```

**Comment by luboslives** [comment]
Thanks @psealock, I must have skimmed that sentence. It print correctly when I use ids.

To be fair, the naming conventions appear to be `shipping_class` and `shipping_class_id`, as used in the default print out. This also involves the extra step of finding the ID as the WP admin area does not expose it, as it does the slug.

**Comment by rrennick** [comment]
You can use the slug this way:

```
wp wc product list --per_page=10 --shipping_class="$(wp wc product_shipping_class list --user=1 --fields=id --slug=YOUR_SLUG)" --user=1
```
