### ISSUE TITLE
[SPIKE] Investigate usage of standalone block editor within Modal

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37290]
**Description**

As part of #37266 and the new description field, we want to allow the user to add a description field using the full block editor.

This issue will be an investigation in how we can best handle this and how much time it will take ( will this be easy to do, or greatly affect our timeline? ).
As an alternative we should also check out the possibility of using the focused editing mode that Gutenberg uses for templates as [mentioned by Jarek below](https://github.com/woocommerce/woocommerce/issues/37290#issuecomment-1477402271).

As mentioned by @jarekmorawski in the other issue, [P2 is doing something similar](https://github.com/Automattic/p2/blob/18c0fcecde16ab20d2fc9c389ce8993ff7d97eb2/plugins/p2/src/client/core/editor/components/editor-core/index.js) ( private repo ) when selecting **New Post**.

It appears they are making use of the IsolatedBlockEditor: https://github.com/Automattic/isolated-block-editor/tree/trunk
Ideally we shouldn't need to make use of the isolated block editor as we already have everything available through WordPress. Could we even re-use our own version of the block editor with a different template?

Some items to consider when investigating this:
- How easy is it to spin up a new block editor? Does it have to be attached to an existing `post`? or can we just pass in blocks and retrieve blocks (as we are only editing the description field).
- Are there any limitations displaying the block editor within a Modal window?
- How easy is it to hide the save/publish/preview buttons?
- Can we limit the block selection?
- Is it easier/harder to implement the focused editing mode? Are there pro's/con's between both approaches?

**Design**

![Image](https://user-images.githubusercontent.com/2240960/225607615-ef308cc9-a03b-49f1-b8db-1398453b7d73.png)

AkVNGImLgSqCObTQ3idVn7-fi-205-27251

**Acceptance criteria**

- [ ] Have a demo branch ready with a tentative working version of the block editor (if feasible) and the focused editing mode option.
- [ ] Include a list of tasks that will need to be done in order to accomplish this ( including a rough time estimate would be a bonus ).

**Comment by jarekmorawski** [comment]
Thanks for making room for this spike, @louwie17. Can we explore using the focused editing mode as an alternative to the modal? It is currently used in Gutenberg for editing template parts, and I wonder if it could help us mitigate some of the issues.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/79307566/226545525-1654668b-12b7-4db4-9478-ff652b77f5ec.png">

**Comment by louwie17** [comment]
> Can we explore using the focused editing mode as an alternative to the modal? It is currently used in Gutenberg for editing template parts, and I wonder if it could help us mitigate some of the issues.

Yeah for sure, that is a great idea, I will update the description.

**Comment by joshuatf** [comment]
I'm going to close this as the spike is complete.  Below are my findings.  We'll continue the implementation of this in https://github.com/woocommerce/woocommerce/issues/37266.

## Usage

The above editor can be seen when editing a site that supports FSE under Appearance -> Editor.

This is done by essentially creating a new block-based editor in an iframe as seen here:

https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/block-editor/index.js#L193-L210

![Image](https://user-images.githubusercontent.com/10561050/229646875-f658b26a-417f-4404-bded-d1277d01607a.png)

## Implementing

The nested editor will need another `BlockEditorProvider`, in which the `useSubRegistry` property seems important to distinguish this editor's state with the parent's.

While this can be done without an iframe, the iframe was most likely chosen to wrap the new editor in Gutenberg to prevent any block selection or clearing with the parent editor and to avoid styling conflicts, particularly layering of toolbars and other slot-filled elements that may not play well with modal elements between the parent editor and child editor.

## Challenges

Unfortunately neither the `ResizableEditor` nor the `EditorCanvas` components are exported in Gutenberg.  Luckily, these are relatively simple components and in the short-term can be duplicated to allow us to quickly use these components.

It also seems that Gutenberg injects some base styles into the iframe which we'll need to figure out how to add in dynamically when creating this iframe.

https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.2/script-loader.php#L162-L171

**Comment by louwie17** [comment]
Nice, thanks @joshuatf for doing this spike!
I am fine with continuing the work as part of the other issue, but I do have a couple small follow up questions:

1. Is the above BlockEditor you referenced used for the focused editing mode? If so, I assume it can be used in either a similar manner as Focus editing mode, or in a Modal like the current wireframe?
2. Does the `useSubRegistry` prop allow us to only retrieve the block data for this particular editor state without it modifying our main product state? Meaning we can just make use of the `onChange` method that the `BlockEditorProvider` provides as well to only get the `description` block data?
3. Related to question one, did you notice if it was easier to implement the focused editing approach, versus displaying it in a Modal? Or did it not matter, as we would have to implement both from scratch?
4. In the screenshot you shared, I don't see any of the editor header items, is that something we have to add ourselves? Similar to our current product editor, or could we re-use a header component from GB?

**Comment by jarekmorawski** [comment]
If the effort is the same, I'd stick to the modal. Focused editing is currently reserved for template parts and may feel odd in this use case. Using a modal will be consistent with other parts of the UI, e.g. variation management.

**Comment by louwie17** [comment]
> If the effort is the same, I'd stick to the modal. Focused editing is currently reserved for template parts and may feel odd in this use case. Using a modal will be consistent with other parts of the UI, e.g. variation management.

cc: @joshuatf

**Comment by joshuatf** [comment]
Good questions, @louwie17.  I actually have an initial concept pushed [here](https://github.com/woocommerce/woocommerce/pull/37570) which implements a reusable nested editor and may be a good reference to see how this works.

>Is the above BlockEditor you referenced used for the focused editing mode? If so, I assume it can be used in either a similar manner as Focus editing mode, or in a Modal like the current wireframe?

It does use the focus editing mode classes, but I think that could be misconstrued as that mode simply highlights the area you're working on and reduces visibility on other fields.

The way the above actually works is a nested block editor in an iframe, which appears the safest way to handle this.

>Does the useSubRegistry prop allow us to only retrieve the block data for this particular editor state without it modifying our main product state? Meaning we can just make use of the onChange method that the BlockEditorProvider provides as well to only get the description block data?

Exactly.  If they are tied to the same registry, there are a lot of interactions with selection, removal, and addition of blocks that could interfere with the parent editor, all of which we'll try to avoid.

My initial PR mentions follow-ups that will include handler callbacks to include to get blocks from the new nested editor.

>Related to question one, did you notice if it was easier to implement the focused editing approach, versus displaying it in a Modal? Or did it not matter, as we would have to implement both from scratch?

It is easier to implement the focused only mode, but this really doesn't give us the flexibility we want in the editor or allow better placement.

>In the screenshot you shared, I don't see any of the editor header items, is that something we have to add ourselves? Similar to our current product editor, or could we re-use a header component from GB?

That was just a portion of the screen.  We can keep the existing header and layout (or hide it if we choose).

With the nested editor we're pretty flexible with the layout and design.  @jarekmorawski if you can provide some input on the preferred design, we can add to the above PR or in a follow-up PR.

**Comment by jarekmorawski** [comment]
@joshuatf We can use the new modal design from the link below. Do you need anything else?

> AkVNGImLgSqCObTQ3idVn7-fi-305-38549&t=JlYIUlb20K6LqJMC-4
