### ISSUE TITLE
[Enhancement]: Flag - acceptance of terms and conditions

### ISSUE THREAD

**Issue by CIPURTA** [woothemes/woocommerce#37292]
### Describe the solution you'd like

flag acceptance of the terms and conditions it should be before payment methods and that field should be a little more visible

**Comment by psealock** [comment]
Hi @CIPURTA Could you provide just a bit more information or a screenshot to make sure we know what you mean? Cheers

**Comment by CIPURTA** [comment]
accept terms and conditions checkbox 
it should be before payment methods and should be more visible
![Screenshot_20230320-212851_Chrome](https://user-images.githubusercontent.com/125870794/226458730-a4103780-ae30-4be4-9b16-46934c70d9a2.jpg)

**Comment by coreymckrill** [comment]
Hi @CIPURTA 

I think this deserves a bit more discussion before any code changes are implemented. Could you submit this over on our [feature requests board](https://woocommerce.com/feature-requests/woocommerce/)?
