### ISSUE TITLE
Call to undefined method stdClass::update_status()

### ISSUE THREAD

**Issue by 4n0n1mo** [woothemes/woocommerce#37315]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I always used $order->update_status('completed'); it hasnt been working since last Woocommerce update.

### Expected behavior

Update order status to complete.

### Actual behavior

Get error Call to undefined method stdClass::update_status()

### Steps to reproduce

1. Try to use method update_status in an order, it wont work.

### WordPress Environment

Woocommerce 7.5.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Hi @4n0n1mo

The `update_status` method is still working for me in WC 7.5. From the error message you're getting:

```
Call to undefined method stdClass::update_status()
```

It sounds like your `$order` variable is not actually an instance of the `WC_Order` class. That would explain why the `update_status` method is coming up as "undefined".
