### ISSUE TITLE
Product Category update clear the field description

### ISSUE THREAD

**Issue by felipehoffmann** [woothemes/woocommerce#37314]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm sending a json without the field "description" because my client is inputting this data directly into the WooCommerce's platform.

Every time I use the put method for product category, it's lose the content of the description.

This is an example of the json I'm sending.

{"name":"Confeitaria","slug":"familia-confeitaria-22"}

### Expected behavior

The content of the description should be altered only if I send that in the json.

### Actual behavior

The content of the description it's getting lost every time I use the put method without it.

### Steps to reproduce

Use the product category's put method sending, for example, just the name to alter a pre existing category that have an description.

### WordPress Environment

.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Hi @felipehoffmann 

I just tried updating a product category term with the JSON you supplied above, and it did not overwrite the term description 🤔 

Could you share the full request you are sending to the API and also the URI of the API endpoint that you're sending the request to?

Also, what version of WooCommerce are you experiencing this on?

**Comment by felipehoffmann** [comment]
Hi @coreymckrill 

I used:
- PUT Method;
- API version v3;
- URL: https://lupel.com.br/wp-json/wc/v3/products/categories/4368?consumer_key=$$$&consumer_secret=$$$
- JSON: {"menu_order":7,"name":"Confeitaria","slug":"familia-confeitaria-22"}

Category before I send:
![image](https://user-images.githubusercontent.com/4227817/226992264-980f01ff-229b-42a9-855c-ad6b6ae0a646.png)

Category after I send:
![image](https://user-images.githubusercontent.com/4227817/226992654-01fb82ab-a907-41aa-8ffb-d896540b7a74.png)

Where can I find the WooCommerce's version? I found only the core's version (wordpress), witch is 6.1.1.

**Comment by coreymckrill** [comment]
@felipehoffmann 

> Where can I find the WooCommerce's version?

You should be able to see the WooCommerce version on the Plugins screen.

**Comment by coreymckrill** [comment]
Also, could you update the issue to add the [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) under the WordPress environment header? That would give us an idea of other plugins that might be interfering. (You might also try disabling all other plugins and see if that makes a difference)

**Comment by rrennick** [comment]
@felipehoffmann Could you try adding the category id to the PUT data?

```
PUT https://wc.localhost/wp-json/wc/v3/products/categories/21
{"id":21,"menu_order":7,"name":"Accessories","slug":"accessories"}

// Response
{
  "id": 21,
  "name": "Accessories",
  "slug": "accessories",
  "parent": 18,
  "description": "Accessories",
  "display": "default",
  "image": null,
  "menu_order": 7,
  "count": 5,
....
}
```

**Comment by coreymckrill** [comment]
🤔 Looking at the screenshot above, I noticed that the Description field has a WYSIWYG editor on it, which I don't think exists in WooCommerce or WP core. Is that added by a plugin?

I tried adding the same markup (an `<img>` tag) to a description field in my test site, and it was stripped out when I saved changes (probably using `wp_kses_data()`). So, my theory here is that there's a plugin that's allowing image tags and other markup in the product category description, but only in WP Admin. When the REST API is used, the normal sanitization functions are used instead, so the markup gets stripped out.

@felipehoffmann does this problem still happen if the product category description only contains text (no HTML)?

**Comment by felipehoffmann** [comment]
@coreymckrill 

WooCommerce's version

![image](https://user-images.githubusercontent.com/4227817/227938069-6678b698-d370-4efb-b90c-bd678335bc20.png)

**Comment by felipehoffmann** [comment]
@coreymckrill

> 🤔 Looking at the screenshot above, I noticed that the Description field has a WYSIWYG editor on it, which I don't think exists in WooCommerce or WP core. Is that added by a plugin?
> 
> I tried adding the same markup (an `<img>` tag) to a description field in my test site, and it was stripped out when I saved changes (probably using `wp_kses_data()`). So, my theory here is that there's a plugin that's allowing image tags and other markup in the product category description, but only in WP Admin. When the REST API is used, the normal sanitization functions are used instead, so the markup gets stripped out.
> 
> @felipehoffmann does this problem still happen if the product category description only contains text (no HTML)?

The problem don't happen when the description only contains text.

**Comment by coreymckrill** [comment]
@felipehoffmann Ok, that would seem to confirm my suspicion that this is related to data sanitization. Do you know which plugin you're using that is enabling rich text in taxonomy term descriptions? If you can figure out which plugin it is, I would recommend reporting this problem to the developer.
