### ISSUE TITLE
The problem with variations

### ISSUE THREAD

**Issue by Sublifeby** [woothemes/woocommerce#37331]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a problem with variable products, the variation worked well and everything was set up correctly in the card settings too. But there was such a problem, tell me please what could be the reason.
The problem is with arbitrary variations, attributes work well.
![2023-03-20_12-56-18](https://user-images.githubusercontent.com/121217576/226545912-83faa496-c10d-4e1a-bb1a-391ea1c32097.png)

### Expected behavior

The problem appeared after the update

### Actual behavior

Doesn't show variations

### Steps to reproduce

![2023-03-20_12-56-18](https://user-images.githubusercontent.com/121217576/226547433-2a7e3593-6bfd-4f4c-a4f4-bd672a3df89d.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://sublife.by
Site address (URL): https://sublife.by
WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 МБ
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 МБ
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.41-cll-lve
Max Upload Size: 128 МБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.0
WC Database Prefix: wprl_
Общий размер базы данных: 108.06MB
Размер данных в базе данных: 80.04MB
Размер индекса базы данных: 28.02MB
wprl_woocommerce_sessions: Данные: 3.02MB + Индекс: 0.05MB + Движок InnoDB
wprl_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wprl_woocommerce_order_items: Данные: 0.06MB + Индекс: 0.02MB + Движок InnoDB
wprl_woocommerce_order_itemmeta: Данные: 0.23MB + Индекс: 0.25MB + Движок InnoDB
wprl_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wprl_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
woocs_statistic: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_actionscheduler_actions: Данные: 1.52MB + Индекс: 0.88MB + Движок InnoDB
wprl_actionscheduler_claims: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_actionscheduler_groups: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_actionscheduler_logs: Данные: 1.52MB + Индекс: 0.44MB + Движок InnoDB
wprl_commentmeta: Данные: 0.05MB + Индекс: 0.03MB + Движок InnoDB
wprl_comments: Данные: 0.25MB + Индекс: 0.09MB + Движок InnoDB
wprl_gla_attribute_mapping_rules: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_gla_budget_recommendations: Данные: 0.22MB + Индекс: 0.14MB + Движок InnoDB
wprl_gla_merchant_issues: Данные: 1.52MB + Индекс: 0.00MB + Движок InnoDB
wprl_gla_shipping_rates: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wprl_gla_shipping_times: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_litespeed_avatar: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_litespeed_url: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_litespeed_url_file: Данные: 0.02MB + Индекс: 0.08MB + Движок InnoDB
wprl_mailpoet_automations: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_automation_runs: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_automation_run_logs: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_automation_run_subjects: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_automation_triggers: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_automation_versions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_custom_fields: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_dynamic_segment_filters: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_feature_flags: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_forms: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_log: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_mapping_to_external_entities: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_migrations: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_newsletters: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_newsletter_links: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wprl_mailpoet_newsletter_option: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_newsletter_option_fields: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_newsletter_posts: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_newsletter_segment: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_newsletter_templates: Данные: 2.52MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_scheduled_tasks: Данные: 0.16MB + Индекс: 0.16MB + Движок InnoDB
wprl_mailpoet_scheduled_task_subscribers: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_segments: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_sending_queues: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_settings: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_statistics_bounces: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_mailpoet_statistics_clicks: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wprl_mailpoet_statistics_forms: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_statistics_newsletters: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_statistics_opens: Данные: 0.02MB + Индекс: 0.08MB + Движок InnoDB
wprl_mailpoet_statistics_unsubscribes: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wprl_mailpoet_statistics_woocommerce_purchases: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wprl_mailpoet_stats_notifications: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_subscribers: Данные: 0.11MB + Индекс: 0.16MB + Движок InnoDB
wprl_mailpoet_subscriber_custom_field: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_subscriber_ips: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_subscriber_segment: Данные: 0.08MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_subscriber_tag: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_mailpoet_tags: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_user_agents: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_mailpoet_user_flags: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_options: Данные: 32.45MB + Индекс: 1.56MB + Движок InnoDB
wprl_postmeta: Данные: 18.55MB + Индекс: 15.06MB + Движок InnoDB
wprl_posts: Данные: 7.52MB + Индекс: 1.23MB + Движок InnoDB
wprl_revslider_css: Данные: 0.13MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_css_bkp: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_layer_animations: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_revslider_layer_animations_bkp: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_revslider_navigations: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_revslider_navigations_bkp: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_revslider_sliders: Данные: 0.03MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_sliders_bkp: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_slides: Данные: 0.14MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_slides_bkp: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_static_slides: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_revslider_static_slides_bkp: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_simple_history: Данные: 0.28MB + Индекс: 0.17MB + Движок InnoDB
wprl_simple_history_contexts: Данные: 2.52MB + Индекс: 1.95MB + Движок InnoDB
wprl_termmeta: Данные: 0.16MB + Индекс: 0.14MB + Движок InnoDB
wprl_terms: Данные: 0.06MB + Индекс: 0.03MB + Движок InnoDB
wprl_term_relationships: Данные: 0.27MB + Индекс: 0.22MB + Движок InnoDB
wprl_term_taxonomy: Данные: 0.19MB + Индекс: 0.03MB + Движок InnoDB
wprl_usermeta: Данные: 1.52MB + Индекс: 0.59MB + Движок InnoDB
wprl_users: Данные: 0.09MB + Индекс: 0.05MB + Движок InnoDB
wprl_wc_admin_notes: Данные: 0.08MB + Индекс: 0.00MB + Движок InnoDB
wprl_wc_admin_note_actions: Данные: 0.05MB + Индекс: 0.02MB + Движок InnoDB
wprl_wc_category_lookup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wc_customer_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_wc_order_coupon_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_wc_order_product_lookup: Данные: 0.06MB + Индекс: 0.06MB + Движок InnoDB
wprl_wc_order_stats: Данные: 0.05MB + Индекс: 0.05MB + Движок InnoDB
wprl_wc_order_tax_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wprl_wc_product_attributes_lookup: Данные: 0.23MB + Индекс: 0.27MB + Движок InnoDB
wprl_wc_product_download_directories: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_wc_product_meta_lookup: Данные: 0.30MB + Индекс: 0.55MB + Движок InnoDB
wprl_wc_rate_limits: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_wc_reserved_stock: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_woocs_statistic: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_woodmart_wishlists: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_woodmart_wishlist_products: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_wpfm_backup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wpr_rucss_resources: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wprl_wpr_rucss_used_css: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wprl_wt_dates: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wt_excluded_dates_times: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wt_price_category_relation: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_wt_pricings: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wprl_yoast_indexable: Данные: 1.52MB + Индекс: 0.52MB + Движок InnoDB
wprl_yoast_indexable_hierarchy: Данные: 0.11MB + Индекс: 0.17MB + Движок InnoDB
wprl_yoast_migrations: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wprl_yoast_primary_term: Данные: 0.09MB + Индекс: 0.13MB + Движок InnoDB
wprl_yoast_prominent_words: Данные: 0.28MB + Индекс: 0.64MB + Движок InnoDB
wprl_yoast_seo_links: Данные: 0.34MB + Индекс: 0.30MB + Движок InnoDB

### Post Type Counts ###

attachment: 2598
cms_block: 19
custom_css: 1
itineraries: 2
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 153
page: 34
post: 59
product: 862
product_variation: 1542
revision: 75
shop_coupon: 1
shop_order: 144
shop_order_refund: 1
woodmart_layout: 4
woodmart_sidebar: 1
woodmart_size_guide: 23
woodmart_slide: 5
woodmart_woo_fbt: 12
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Contact Form 7: от Takayuki Miyoshi – 5.7.4
Cyr-To-Lat: от Сергей Бирюков
Михаил Кобзарёв
Игорь Гергель – 5.5.0

Express Payments: Internet-Acquiring MIR: от ООО «ТриИнком» – 1.0.5
Экспресс Платежи: Интернет-эквайринг: от ООО «ТриИнком» – 1.0.6
Экспресс Платежи: ЕРИП: от ООО «ТриИнком» – 1.0.5
Google Listings and Ads: от WooCommerce – 2.4.1
Конструктор страниц WPBakery: от Michael M - WPBakery.com – 6.10.0
Loco Translate: от Тим Уитлок (Tim Whitlock) – 2.6.4
MC4WP: Mailchimp for WordPress: от ibericode – 4.9.1
MailPoet: от MailPoet – 4.8.1
Product/Review CSV Import Export: от WebToffee – 3.8.3
Слайдер Революция: от ThemePunch – 6.6.10
Safe SVG: от 10up – 2.0.3
Saphali Woocommerce Russian: от Saphali – 1.8.13
Simple History: от Pär Thernström – 3.4.0
Tawk.to Живой чат: от Tawkto – 0.7.2
Shipping Method Description for WooCommerce: от Thomas Charbit – 1.2.6
WooCommerce международный ввод телефона: от Алексей Маслийчук (alex91ckua) – 2.1.3
Print Invoice & Delivery Notes for WooCommerce: от Программное обеспечение Tyche – 4.7.2
WooCommerce: от Automattic – 7.5.0
Woodmart Core: от  – 1.0.36
Yoast SEO Premium: от Команда Yoast – 20.3
Yoast SEO: от Команда Yoast – 20.3
WP Rocket: от WP Media – 3.11.2
Yml для Yandex Market: от Максим Глазунов – 3.10.6

### Inactive Plugins (1) ###

LiteSpeed Cache: от LiteSpeed Technologies – 5.3.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BYN (руб.)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Ссылка магазина: #8 - /shop/
Корзина: #9 - /cart/
Оформление заказа: #10 - /checkout/
Мой аккаунт: #11 - /my-account/
Правила и условия: #3 - /privacy-policy/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.1.4
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart-child/woocommerce/emails/admin-new-order.php
woodmart-child/woocommerce/emails/customer-completed-order.php
woodmart-child/woocommerce/emails/customer-invoice.php
woodmart-child/woocommerce/emails/customer-new-account.php
woodmart-child/woocommerce/emails/customer-note.php
Есть обновления для woodmart-child/woocommerce/emails/customer-on-hold-order.php версии 3.7.0. Версия ядра — 7.3.0
woodmart-child/woocommerce/emails/customer-processing-order.php
woodmart-child/woocommerce/emails/customer-reset-password.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Узнайте
как обновить

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-21 17:20:19 +03:00
Options: ✔
Notes: 52
Onboarding: completed

### Action Scheduler ###

Выполнено: 1 131
Oldest: 2023-02-18 11:29:12 +0000
Newest: 2023-03-21 08:00:55 +0000

Неудачно: 1 192
Oldest: 2022-07-31 03:00:29 +0000
Newest: 2023-03-21 05:57:17 +0000

В ожидании: 4
Oldest: 2023-03-21 08:01:55 +0000
Newest: 2023-03-22 03:00:00 +0000

### Status report information ###

Generated at: 2023-03-21 11:01:40 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Sublifeby** [comment]
![2023-03-21_12-07-38](https://user-images.githubusercontent.com/121217576/226561456-18bd3e3b-daf2-45bd-9543-73cb2a4e58db.png)
![2023-03-21_12-07-03](https://user-images.githubusercontent.com/121217576/226561460-3637b9d1-a2b0-4e5c-a77c-6ca8a4559085.png)
![2023-03-21_12-06-36](https://user-images.githubusercontent.com/121217576/226561463-493b93cf-dcad-4ea2-b086-394393921270.png)
![2023-03-21_12-06-02](https://user-images.githubusercontent.com/121217576/226561464-9fe8621a-c8d5-4144-9adf-9fd722d56b84.png)

**Comment by rrennick** [comment]
@Sublifeby Could you use Google translate to provide us with text instructions on how to reproduce this issue?
