### ISSUE TITLE
Two order mails since I started using FreePay instead of Stripe.

### ISSUE THREAD

**Issue by Roghatten** [woothemes/woocommerce#37349]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Customers that pay with MobilePay (Denmark) gets some times two order mails instead of one.
I have never seen this when I used Stripe. It happens after I have changed to FreePay which is a provider that allows payment via the danish MobilePay. It dos not happen every time.

Im using woo version 7.1.0 together with the booking module "Booking Addon for WooCommerce".

I can see two Pending in the Order status when it happens. When only one is pressent then its OK.

Copy of a transaction that provides two mails.

FreePay: Payment authorized. Transaction ID: b7c16567-9aea-48e1-8c1a-245e068ae117

21. March 2023 at 10:53 Delete note

Order status changed from Pending payment to Completed.

21. March 2023 at 10:53 Delete note

Order status changed from Pending payment to Completed.

21. March 2023 at 10:53 Delete note

FreePay: Payment authorized on Accept. Transaction ID: b7c16567-9aea-48e1-8c1a-245e068ae117

21. March 2023 at 10:53 Delete note

Booking #22132 status changed from “Unpaid” to “Paid”

Normal order with only one Pending results in only one mail:
Booking #22083 status changed from “Paid” to “Complete”

4. March 2023 at 0:10 Delete note

Order status changed from Pending payment to Completed.

2. March 2023 at 11:55 Delete note

Booking #22083 status changed from “Unpaid” to “Paid”

2. March 2023 at 11:55 Delete note

FreePay: Payment authorized on Accept. Transaction ID: ff9a416c-0936-410a-953a-84149267bbf7

2. March 2023 at 11:55 Delete note

### Expected behavior

One mail sent to the buyer with one order number and one booking number.

### Actual behavior

Two mails with two different bookings numbers are send but on the same order number.

### Steps to reproduce

Not possible to reproduce.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://escapetour.dk
Site address (URL): https://escapetour.dk
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 205 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-1:10.3.38+maria~ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 963.89MB
Database Data Size: 895.82MB
Database Index Size: 68.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 1.91MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
agh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
agh_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
agh_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
agh_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
agh_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
agh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
agh_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
agh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
EST_baner: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
EST_booking: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
EST_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ET_bruger: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
ET_highscore: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
ET_mellemresultater: Data: 1.52MB + Index: 3.50MB + Engine InnoDB
ET_opgave: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
ET_ordre: Data: 0.20MB + Index: 0.03MB + Engine InnoDB
ET_ordre_tur: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ET_rating: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ET_resultat: Data: 1.52MB + Index: 0.95MB + Engine InnoDB
ET_sprog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ET_tur: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
stg_4cfc9_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_chained_choices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_chained_completed: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_chained_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_chained_quizzes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_chained_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_chained_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_comments: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
stg_4cfc9_duplicator_packages: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
stg_4cfc9_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_4cfc9_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
stg_4cfc9_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
stg_4cfc9_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_lockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_login_fails: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_options: Data: 3.52MB + Index: 0.28MB + Engine InnoDB
stg_4cfc9_pantheon_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_postmeta: Data: 355.64MB + Index: 21.06MB + Engine InnoDB
stg_4cfc9_posts: Data: 80.45MB + Index: 4.98MB + Engine InnoDB
stg_4cfc9_signups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_usermeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
stg_4cfc9_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_wc_customer_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
stg_4cfc9_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_wc_order_product_lookup: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
stg_4cfc9_wc_order_stats: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
stg_4cfc9_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
stg_4cfc9_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
stg_4cfc9_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_4cfc9_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_woocommerce_order_itemmeta: Data: 2.52MB + Index: 1.91MB + Engine InnoDB
stg_4cfc9_woocommerce_order_items: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
stg_4cfc9_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
stg_4cfc9_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
stg_4cfc9_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_yoast_indexable: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
stg_4cfc9_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
stg_4cfc9_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
stg_4cfc9_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
stg_4cfc9_yoast_seo_links: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_chained_choices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_chained_completed: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_chained_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_chained_quizzes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_chained_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_chained_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_login_fails: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.05MB + Index: 0.25MB + Engine InnoDB
wp_pantheon_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 357.59MB + Index: 20.06MB + Engine InnoDB
wp_posts: Data: 72.58MB + Index: 4.89MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 1.25MB + Index: 0.17MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
www_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
www_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_lockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_login_fails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_options: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
www_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
www_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
www_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 451
audioplayer: 1
cue_playlist: 1
custom_css: 1
elementor_library: 35
fca_qc_quiz: 1
mvvwb_bookings: 1154
mvvwb_items: 14
nav_menu_item: 10
oembed_cache: 2
page: 427
post: 6
private-page: 1
product: 22
revision: 16290
shop_coupon: 115
shop_order: 1055
shop_order_refund: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Query Monitor: by John Blackbourn – 3.10.1
MVV WooCommerce Booking Addon (Free): by mvvapps – 4.1.0
Custom Permalinks: by Sami Ahmed Siddiqui – 2.5.2
Decorator - WooCommerce Email Customizer: by WebToffee – 1.2.2
Elementor Pro: by Elementor.com – 3.11.6
Elementor: by Elementor.com – 3.11.5
Essential Addons for Elementor: by WPDeveloper – 5.6.1
FreePay for WooCommerce: by Freepay – 1.7.4
Jetpack: by Automattic – 11.9.1
Login LockDown: by WebFactory Ltd – 1.83
one.com: by one.com – 4.2.2
Pages with category and tag: by YAHMAN – 0.9.0
Premium Addons for Elementor: by Leap13 – 4.9.51
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Shipping & Tax: by WooCommerce – 2.0.0 (update to version 2.2.4 is available)
WooCommerce: by Automattic – 7.1.0 (update to version 7.5.1 is available)
Yoast SEO: by Team Yoast – 20.3
WP Force SSL: by WebFactory Ltd – 1.65

### Inactive Plugins (3) ###

Performance Cache: by one.com – 3.0.9
Salcodes: by Salman Ravoof (Klaus Herborg) – 1.0
WP BrowserUpdate: by Marco Steinbrecher – 4.3.9

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #2073 - /shop/
Basket: #2074 - /basket/
Checkout: #8491 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #5487 - /terms-conditions/

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: hello-elementor/woocommerce/checkout/thankyou.php
hello-elementor/woocommerce/emails/customer-completed-order.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-03-22 12:14:34 +01:00
Options: ✔
Notes: 128
Onboarding: completed

### Action Scheduler ###

Complete: 96
Oldest: 2023-02-18 22:01:48 +0100
Newest: 2023-03-21 12:20:27 +0100

Pending: 1
Oldest: 2023-03-22 05:41:50 +0100
Newest: 2023-03-22 05:41:50 +0100

### Status report information ###

Generated at: 2023-03-21 20:59:00 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Since this bug is seen only with MobilePay, I'm inclined to think this is an issue with MobilePay, which is an extension we have no control over. If you update to the latest WooCommerce, does that help?

**Comment by rrennick** [comment]
Closing for lack of feedback.
