### ISSUE TITLE
WP updater > wrong url to changelog

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#37346]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The changelog displayed as detailed changelog is wrong

![image](https://user-images.githubusercontent.com/919332/226724420-01d76631-dc1d-4d4b-b6ef-e04e78b0ce74.png)

### Expected behavior

points to https://raw.githubusercontent.com/woocommerce/woocommerce/master/changelog.txt
should be https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt

### Actual behavior

Just try to update your Woo plugin, but first you want to check what's new in the release, to qualify if the upgrade could have potential impacts on third party woo plugins.

### Steps to reproduce

- I want to check if the update to 7.5 is risky 
- There is a 7.5.1 release, i only see the 7.5.1 release fixes
- To see what is shipped into 7.5.0, i need to click on "See changelog for all versions"
- But it points to the wrong files

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the report @Marc-pi 

I can't find reference to the wrong url in this repo, so I'm wondering where it might be. What is the url of the screenshot, or how do you get there?

**Comment by Marc-pi** [comment]
here you are !
1/ from wp-admin/plugins.php

Click on View Details of the WooCommerce plugin, then changelog tab

![image](https://user-images.githubusercontent.com/919332/227039278-6f9dee65-5237-4f69-ab05-1b8937e5997d.png)


![image](https://user-images.githubusercontent.com/919332/227039108-ac98af54-18d9-4675-ae06-df6d7a150ca5.png)


2/ the same from wp-admin/update-core.php
but it is a `View version xxxx details` link

**Comment by psealock** [comment]
On the latest WooCommerce, I am seeing the correct URL so I will close this issue. Its possibly wrong because you don't have the latest version. Thanks for raising the issue.

<img width="687" alt="Screen Shot 2023-03-27 at 11 06 02 AM" src="https://user-images.githubusercontent.com/1922453/227807635-bb3aa39c-ecbb-48d6-86b6-f0e419c0e4f5.png">

**Comment by Marc-pi** [comment]
yep, it was updated 1 week after the release !!!
https://developer.woocommerce.com/2023/03/14/woocommerce-7-5-released/
![image](https://user-images.githubusercontent.com/919332/227859926-c684f639-2119-4ec7-80d6-57e60bc1fed4.png)


seems to be a manual process ? 
maybe you need to update the package process ??
