### ISSUE TITLE
Standardize `"watch"` Command

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#37377]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

While various projects currently have a `"start"` command, I'd like to instead create more granular `"watch"` commands that can be ran independently. There are cases we're we have multiple types of builds and they are running concurrently in a less-than-ideal way. 

* We should create separate `watch:` prefixed commands for different builds and a `"watch"` command that runs those concurrently using `pnpm run --filter=$npm_package_name... --parallel --no-bail watch:*`. This gives really great output from PNPM on the concurrent tasks and will provider a better developer experience.
* We need to support the current `"start"` workflow. The reason this distinction matters is because `--filter=$npm_package_name...` above will run the watch commands on all of the dependencies in addition to the current project. This means if we changed the `"start"` command to an alias for `"watch"` it would result in a large number of concurrent `watch` commands across all of the dependencies multiple times.

**Comment by ObliviousHarmony** [comment]
One consideration here might be that using `--watch` options on build tools would technically bypass Turborepo's caching. Another option could be to use something like [nodemon](https://nodemon.io/) to watch for changes and re-run the standard build. This would be slower than watching a build tool, but, it would have a faster start-up time and subsequent watches could benefit from the populated cache.

I would be curious what performance of both options looks like. The other consideration would be the user experience. Running the watch command in parallel using PNPM gives a very easy to follow output for changes. We would want to make sure that the output is similar in quality.

**Comment by ObliviousHarmony** [comment]
When it comes to `nodemon`, one of the things worth considering is that `pnpm run build` will also build all of the dependencies for a project. If you tried to use `pnpm run --filter=@woocommerce/components... watch` with a `nodemon` implementation, every time you changed something it would rebuild many of the same packages. This would still utilize the cache, but, this duplication feels really silly.

Assuming that we configured `nodemon` to watch all of the workspace packages in their respective `node_modules`, editing some of the lower-level packages could have a really interesting impact:

* Watch `woocommerce/client/admin`. 
* Edit `@woocommerce/number`, `nodemon` rebuilds it.
* `@woocommerce/currency` detects a change and rebuilds it and `@woocommerce/number`.
* `@woocommerce/components` detects a change and rebuilds it and _all of its dependencies_.
* `woocommerce/client/admin` detects a change and rebuilds it, and again, all of its dependencies.

There _is_ an `--only` option available in Turborepo that we could try and make use of. That would let us populate the cache and avoid the above problem. We could also use the `--output-logs=error-only` option in order to suppress build output that doesn't contain any meaningful information. From a maintenance standpoint, this requires a separate `build` command as well that calls `turbo` with these flags.

**Comment by ObliviousHarmony** [comment]
The big question that remains, however, is how we should approach watching dependencies. If you run `watch` on a project, would you expect it to `watch` all of the dependencies too? Right now our `build` command will automatically build all of the dependencies; should we align with that and `watch` the children automatically? It's also worth noting that `lint` and `test` will only run on a single project (unless ran from the root), so, `build` is the outlier here.

If we only watch a single project, you would have to use `pnpm run --filter={package}... watch` in order to watch the package and all its dependencies. Given that we'd want to use `--only`, this also means that the build needs to run on every project before the watch starts (and does another build, but, only on the package in question). As an aside, I wonder what kind of mayhem might occur with builds triggering builds for other packages due to having been built (because we're watching the node_modules for changes to rebuild when dependencies change).

If we watch all of the projects, using `pnpm run --filter={package}... watch` would have a _really_ strange effect. It would individually watch each project and all of its dependencies, resulting in a huge mess of projects being watched several times over! For what it's worth, this isn't really that different from the current `"build"` since that would do rebuilds many times over across many different projects.

All this to say, should `pnpm run watch --filter=woocommerce/client/admin` watch _just_ the admin client for changes, or, should it watch all of the dependencies too? Should you need to run `pnpm run watch --filter=woocommerce/client/admin...` in order to watch them all?

**Comment by ObliviousHarmony** [comment]
After gathering some feedback, I've decided on the following:

* Add a `turbo:watch` pipeline that features a dependency on `"^turbo:build"` that is `"persistent": true`. This will let us run a build and watch conveniently using Turbo on any package or combination thereof.
* Add a `turbo:watch:*` script for `js`, `css`, and any other necessary types for the included tools. This will let us run a nice looking `pnpm run turbo:watch:* --parallel` for each package that will concurrently run all of the build scripts in an easy to read way.
  * **Example**: A `"turbo:watch:esm": "tsc --project tsconfig.json --watch"` script and a `"turbo:watch": "pnpm run turbo:watch:* --parallel"` script. When you call `turbo:watch` on the project it should concurrently run all of the sub-scripts in a way that looks nice in the CLI.
* Add a `watch` script in each project that runs `turbo:watch` for it.
* Add a `watch-deep` script in each project that watches the project and all of its dependencies.
* Add a root `watch` script that will run `turbo:watch` on all. There is no need for a `watch-deep` here because by default it will watch all of the dependencies anyway.

**Comment by samueljseay** [comment]
So there is just one problem with turbo watch + pnpm. It feels… kinda small, but I want to mention it anyway.

PNPM doesn’t have good SIGINT or SIGTERM handling: https://github.com/pnpm/pnpm/issues/2653 which means doing ctrl + c on watch for example, will report Command Failed when running a watch.

**Comment by samueljseay** [comment]
It also dumps the failure output into your terminal after completing. Which feels... not great:




![Image](https://user-images.githubusercontent.com/1281828/235409344-b918048f-8dc4-46ed-b0c7-6227981602dd.png)

**Comment by ObliviousHarmony** [comment]
For what it's worth, I _do_ think this is probably more related to the Turbo regression than any PNPM problem. The message seems like it's coming from Turbo rather than PNPM.

**Comment by samueljseay** [comment]
Ok thanks @ObliviousHarmony I'll investigate whether there is anything we can do about that.

**Comment by ObliviousHarmony** [comment]
Upstream PR if it's a Turbo problem @samueljseay! 😀

**Comment by samueljseay** [comment]
I was thinking that too @ObliviousHarmony seems like we're syncing up 😂

**Comment by samueljseay** [comment]
@ObliviousHarmony 

See latest comment from TurboRepo on this situation: https://github.com/vercel/turbo/issues/3711#issuecomment-1531734585

Yesterday I spent some time looking at whether I could trap the SIGINT by just using traps in the pnpm scripts as a hacky workaround, it does make the top level task exit 0, but still all the errors are shown in tasks (even if in the respective task scripts I trap SIGNINT as well) and also the problem where error messages are dumped into the output of terminal. As you said this is a TurboRepo issue anyway not a PNPM issue so traps probably can't be used here, but I just had to try for science lol.

I also looked at the code base before I saw the above comment and I saw a few barriers to making an upstream PR:

1.  I am still only learning rust I've made only a handful of examples with it, so it's going to take me time to be more productive in it and a lot of the code that was Go before and handled entrypoint running of Turbo has been converted to Rust or partially converted.

2. I got the sense there was no easy fix at that time that I could see as a free-win. It looked to me like signal handling has changed drastically since introduction of Rust.

I feel like based on the comment I linked my concerns are somewhat validated about me making a contribution upstream right now, but happy to hear your thoughts on it. 😃

**Comment by samueljseay** [comment]
I'm just marking this as blocked for organizational purposes 😄

**Comment by ObliviousHarmony** [comment]
How would you feel about moving forward with the weird behavior for now @samueljseay? Do you think this provides a better `watch` experience for developers, or, should we just revisit this when `turbo` has completed the migration?

**Comment by samueljseay** [comment]
🤔 it's tough.

While I see it does add some improvement to the watch experience, I feel like the dumping of output is going to annoy and distract people and we'll get support requests or bug reports or whatever because it "feels broken".

<opinion>
Based on the fact that watch is still possible right now (albeit not as good as it should be), I think we should wait for turbo.
</opinion> 😄

**Comment by ObliviousHarmony** [comment]
I agree, let's go ahead and put this back into the backlog for now.

Thanks for taking a look @samueljseay!

**Comment by samueljseay** [comment]
This would be good to revisit if https://github.com/woocommerce/woocommerce/pull/39504 gets merged.

**Comment by ObliviousHarmony** [comment]
We now have a `watch:build` in the monorepo and this has been completed.
