### ISSUE TITLE
Add advanced pricing menu with tax class field

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37398]
**Description**

This issue will cover moving over the Tax class field displayed within the advanced section in the pricing section.
We should be able to make use of previously created blocks for this, like the collapsable block and radio control block ( the latter is added as part of https://github.com/woocommerce/woocommerce/issues/37395 ).

**Design**

![Image](https://user-images.githubusercontent.com/2240960/227222586-c8f39662-a8d8-439d-8c47-ddc17ea0effc.png)

AkVNGImLgSqCObTQ3idVn7-fi-305-76929&t=EooGwacveG5ujPnt-4

**Acceptance criteria**

- [ ] Advanced section should be displayed in pricing section (default closed)
- [ ] When opening the advanced section the Tax class field should be present with 3 options.

**Comment by joelclimbsthings** [comment]
@louwie17 Do we have the "Charge sales tax on" field covered in a different issue?

![image](https://user-images.githubusercontent.com/444632/229626364-a0d73424-498a-40db-be17-546ec18c1128.png)

**Comment by joelclimbsthings** [comment]
It also looks like this may have already been knocked out by @joshuatf 's PR [here](https://github.com/woocommerce/woocommerce/pull/37529/files).

**Comment by louwie17** [comment]
> @louwie17 Do we have the "Charge sales tax on" field covered in a different issue?

Yeah, here: https://github.com/woocommerce/woocommerce/issues/37396 but looks like you already found it.
It does look like I forgot to add that this issue would be blocked by: https://github.com/woocommerce/woocommerce/issues/37395 that @joshuatf is working on, to make use of the Radio control block. I did add that to the other issue.

**Comment by joelclimbsthings** [comment]
This was completed by https://github.com/woocommerce/woocommerce/pull/37529
