### ISSUE TITLE
Create product SKU block and create inventory block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37399]
**Description**

This issue pertains to moving the SKU field over to the block based product editor.
This may warrant the creation of a new product sku block. I had a quick look and couldn't find a similar already existing block, but it would be worth having a re-look.

The product SKU block should work the same as it currently does within the product editor.

**Design**

![Image](https://user-images.githubusercontent.com/2240960/227223816-55154abe-f3b3-43a1-853f-4e3ebb73b7fc.png)

AkVNGImLgSqCObTQ3idVn7-fi-331-61736

**Acceptance criteria**

- [ ] Inventory section should be present within Inventory tab
- [ ] SKU field should be present within inventory section
- [ ] SKU should be auto generated from the product title, similar to how it works currently.

**Comment by joelclimbsthings** [comment]
Hey @jarekmorawski , do we have text for the "?" tooltip for the SKU field here?

**Comment by jarekmorawski** [comment]
> Hey @jarekmorawski , do we have text for the "?" tooltip for the SKU field here?

I don't think we need it after all. I've removed it from the design. ✅
