### ISSUE TITLE
Create product radio control field block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37395]
**Description**

We have several fields that are radio controls with several options ( Sales tax, Tax class, Stock status, Out of stock ).
We should have a re-usable radio control block that can be re-used for these fields.

**Demo**

![Image](https://user-images.githubusercontent.com/2240960/227187732-01cde567-9731-4ef6-8692-1599db9304bd.png)

AkVNGImLgSqCObTQ3idVn7-fi-332-51222&t=EooGwacveG5ujPnt-4

**Acceptance criteria**

- [ ] Radio control should have attribute name that updates the entity data store with the selected value.
- [ ] Radio control should have an `options` attribute with an array of label/value objects as radio control options.
- [ ] Radio control should support additional attributes like: title/label, secondary text

**Comment by joelclimbsthings** [comment]
I believe this was already closed by https://github.com/woocommerce/woocommerce/pull/37529
