### ISSUE TITLE
Create shipping fee field block and initial shipping section

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37406]
**Description**

We should create a **Fees & dimensions** section within the shipping tab and add the initial field to it - **Shipping fee**
We should be able to re-use the radio control block created as part of https://github.com/woocommerce/woocommerce/issues/37395.

This may require a new dropdown block for the Shipping class dropdown that shows up when **Follow class** is selected.

**Design**

![Image](https://user-images.githubusercontent.com/2240960/227235453-78fd4dc2-aed7-4fc3-9478-c044927ca48d.png)

AkVNGImLgSqCObTQ3idVn7-fi-305-38548

**Acceptance criteria**

- [x] **Fees & dimensions** section should be present within Shipping tab
- [x] **Shipping fee** field should be visible within **Fees & dimensions** section
- [x] Shipping class dropdown should be visible if **Follow class** is selected, but hidden when **Free shipping** is selected. This does not consider the shipping class creation modal.
- [x] The `How to get started?` link in the description takes the user to `https://woocommerce.com/posts/how-to-calculate-shipping-costs-for-your-woocommerce-store/`.

**Comment by mdperez86** [comment]
@jarekmorawski @louwie17 Do you know what is the url used for the link `How to get started?`?

**Comment by jarekmorawski** [comment]
Here's the URL:

`https://woocommerce.com/posts/how-to-calculate-shipping-costs-for-your-woocommerce-store/`
