### ISSUE TITLE
Emails not arriving - Soft bounce New order emails - non-ASCII characters problem

### ISSUE THREAD

**Issue by rocko2** [woothemes/woocommerce#37418]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With update to Version 7.5.1 New order email are not coming.
After hours of investigating, we found out it is a problem with non-ASCII characters inside email headers.
For Subject or for reply-to headers.

### Expected behavior

The emails should arrive.

### Actual behavior

The emails don't arrive, because email server bounces them. Producing:
550 Subject contains invalid characters.
550 Reply-To contains invalid characters.

### Steps to reproduce

Make an order with name of customer Ćiro Žamet, for example.
In the subject for New order email enter some tekst with non-ASCII characters,.. for example: Broj narudžbe

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.cooliee.si
Site address (URL): https://www.cooliee.si
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: sl_SI
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: mnl_
Total Database Size: 20.85MB
Database Data Size: 17.58MB
Database Index Size: 3.27MB
mnl_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mnl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mnl_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
mnl_woocommerce_order_itemmeta: Data: 0.42MB + Index: 0.28MB + Engine InnoDB
mnl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mnl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
mnl_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
mnl_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
mnl_cr_local_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
mnl_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mnl_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_options: Data: 3.13MB + Index: 0.16MB + Engine InnoDB
mnl_pmxe_exports: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
mnl_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
mnl_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxe_templates: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_imports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_postmeta: Data: 2.19MB + Index: 0.72MB + Engine InnoDB
mnl_posts: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
mnl_sgs_log_events: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
mnl_sgs_log_visitors: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
mnl_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
mnl_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mnl_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
mnl_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mnl_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mnl_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mnl_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
mnl_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_wpmailsmtp_attachment_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_wpmailsmtp_emails_log: Data: 6.52MB + Index: 0.06MB + Engine InnoDB
mnl_wpmailsmtp_email_attachments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wpmailsmtp_email_tracking_events: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_wpmailsmtp_email_tracking_links: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
mnl_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mnl_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
mnl_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mnl_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mnl_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mnl_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 7
acf-field-group: 2
attachment: 149
custom_css: 1
elementor_library: 1
gtw_custom_fields: 3
gtw_rules: 6
nav_menu_item: 7
page: 12
post: 5
product: 15
product_variation: 4
saswp: 1
shop_order: 103
wp_block: 1
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Advanced Custom Fields PRO: by WP Engine – 6.0.7
Classic Editor: by WordPress Contributors – 1.6.2
Admin Columns: by AdminColumns.com – 4.6.1
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.4.0
Customer Reviews for WooCommerce: by CusRev – 5.20.1
Disable Comments: by WPDeveloper – 2.4.3
Download Plugin: by metagauss – 2.0.5
Elementor: by Elementor.com – 3.11.5
Essential Addons for Elementor: by WPDeveloper – 5.6.2
Flexible Checkout Fields: by WP Desk – 3.5.7
Flexible Shipping: by Octolize – 4.19.1
Geolocation IP Detection: by Yellow Tree (Benjamin Pick) – 5.2.0
Gift Wrapper for WooCommerce: by FantasticPlugins – 4.5.1
Google Listings and Ads: by WooCommerce – 2.4.1
Jetpack: by Automattic – 11.9.1
Schema & Structured Data for WP & AMP: by Magazine3 – 1.11.1
SiteGround Optimizer: by SiteGround – 7.3.1
SiteGround Security: by SiteGround – 1.4.1
SVG Support: by Benbodhi – 2.5.5
WooCommerce Smart COD: by woosmartcod.com – 1.6.1
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.19
WooCommerce EU VAT Number: by WooCommerce – 2.7.0
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.6.2
WooCommerce PayPal Payments: by WooCommerce – 2.0.3
WooCommerce Price Based on Country: by Oscar Gare – 3.1.1
PS Dostavni modul: by Pošta Slovenije – 4.0.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.5.1
WordPress Importer: by wordpressdotorg – 0.8
Yoast SEO: by Team Yoast – 20.3
WP All Export Pro: by Soflyy – 1.8.3
WP All Import Pro: by Soflyy – 4.7.8
WP Mail SMTP Pro: by WPForms – 3.7.0
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.6
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4
WPForms Lite: by WPForms – 1.8.0.2

### Inactive Plugins (2) ###

Kadence WooCommerce Email Designer: by Kadence WP – 1.5.7
Pre-Orders for WooCommerce: by Bright Plugins – 1.2.11

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #112 - /shop/
Cart: #13 - /shop/cart/
Checkout: #14 - /shop/checkout/
My account: #15 - /shop/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: block-shop child theme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: block-shop
Parent Theme Version: – 0 is available
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: botiga-child/woocommerce/emails/customer-completed-order.php
botiga-child/woocommerce/emails/email-order-details.php
botiga-child/woocommerce/single-product/add-to-cart/simple.php
botiga-child/woocommerce/single-product/meta.php
botiga-child/woocommerce/single-product/short-description.php
botiga-child/woocommerce/single-product.php

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: 95.176.226.210
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 95.176.226.210
Real external IP: 95.176.226.210
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 3.1.1
Base location: SI
Base currency: EUR
Price Based On: billing
Shipping: –
Test mode: –
Test country: –
Load products price in background: ✔
Prices entered with tax: ✔
Calculate tax based on: billing
Display prices in the shop: incl

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: SI
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-25 07:47:39 +00:00
Options: ✔
Notes: 123
Onboarding: completed

### Action Scheduler ###

Complete: 244
Oldest: 2023-02-21 14:23:12 +0000
Newest: 2023-03-24 12:11:20 +0000

Failed: 14
Oldest: 2023-02-22 09:16:23 +0000
Newest: 2023-03-23 20:12:18 +0000

Pending: 5
Oldest: 2023-03-24 16:42:59 +0000
Newest: 2023-03-30 08:53:21 +0000

### Status report information ###

Generated at: 2023-03-24 12:28:29 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
It's not clear if this is a problem in WooCommerce, WordPress, or one or more email servers. Have you continued to experience this problem, and can you indicate if it consistently happens for all emails containing these characters in the subject field (or other headers)?
