### ISSUE TITLE
[Enhancement]: Address fields not required for virtual products (store offering physical products and virtual products)

### ISSUE THREAD

**Issue by Gilou24** [woothemes/woocommerce#37467]
### Describe the solution you'd like

Some sites offer both virtual and physical products.
In this case, the postal address fields are systematically required for the buyer.
But these fields aren't useful if the customer is only buying virtual products... and that hurts conversions.
So I think it would be interesting to add a feature to not ask for the address in the billing part of the order form if there is no shipment.
A few plugins allow this to be done, but all of the ones I've tried have an error (described here: https://wordpress.org/support/topic/undefined-text-on/#post-16600916) arising from expected behavior for digital products.

**Comment by vedanshujain** [comment]
Hey, @Gilou24 , I would say this is plugins territory and WC core. However, I could be wrong. Can you please submit this request to the feature request section here [WooCommerce Feature Requests](https://woocommerce.com/feature-requests/woocommerce/), this way other folks would be able to vote on it and we can consider it.

I am closing the issue for repo maintenance, but feel free to reply back if you have further questions.
