### ISSUE TITLE
order no skip issue

### ISSUE THREAD

**Issue by senthil1975** [woothemes/woocommerce#37471]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

if order status change from processing to refund , one order no are skipped
 

### Expected behavior

if order status change from processing to refund , one order no are skipped

### Actual behavior

if order status change from processing to refund , one order no are skipped

### Steps to reproduce

if order status change from processing to refund , one order no are skipped

### WordPress Environment

if order status change from processing to refund , one order no are skipped

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @senthil1975,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. Please use [the Bug Report template here](https://github.com/woocommerce/woocommerce/issues/new/choose).

**Comment by senthil1975** [comment]
u just change order status to refund and make new order and check no
