### ISSUE TITLE
E2E: Update "Store owner can complete onboarding wizard" test to include redirection to WC Home

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#37470]
e2e test `Store owner can complete onboarding wizard` currently does not verify we are redirected to WC Home which contains the task list after completing the onboarding wizard.

**Comment by tammullen** [comment]
https://github.com/woocommerce/woocommerce-admin/wiki/Smoke-Test-Checklist#welcome-modal

**Comment by lanej0** [comment]
OBW tests replaced by core profiler tests (and this check is part of one of the core profiler tests!)
