### ISSUE TITLE
Code from documentation doesn't work

### ISSUE THREAD

**Issue by AndyJAllen** [woothemes/woocommerce#37475]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Exact code, copied from:
https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-customer

`<?php
$data = [
    'email' => 'john.doe@example.com',
    'first_name' => 'John',
    'last_name' => 'Doe',
    'username' => 'john.doe',
    'billing' => [
        'first_name' => 'John',
        'last_name' => 'Doe',
        'company' => '',
        'address_1' => '969 Market',
        'address_2' => '',
        'city' => 'San Francisco',
        'state' => 'CA',
        'postcode' => '94103',
        'country' => 'US',
        'email' => 'john.doe@example.com',
        'phone' => '(555) 555-5555'
    ],
    'shipping' => [
        'first_name' => 'John',
        'last_name' => 'Doe',
        'company' => '',
        'address_1' => '969 Market',
        'address_2' => '',
        'city' => 'San Francisco',
        'state' => 'CA',
        'postcode' => '94103',
        'country' => 'US'
    ]
];

print_r($woocommerce->post('customers', $data));
?>`

### Expected behavior

Customer is created & Server responds with json data of new customer

### Actual behavior

500 Error with log entry:

> PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in \vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:411
Stack trace:
#0 \vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(455): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 \vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('customers', 'POST', Array)
#2 \test-api.php(59): Automattic\WooCommerce\Client->post('customers', Array)
#3 {main}
  thrown in \vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 411

### Steps to reproduce

Copy code
Execute using woocommerce rest api plugin

### WordPress Environment

6.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
hey @AndyJAllen , I am not able to repro on my local testing site, but looks like your server is returning invalid JSON response. You can inspect the error by wrapping it in a try...catch block like so:
```php
try {
	$response = $woocommerce->post('customers', $data);
} catch ( Exception $e ) {
	echo $e->getResponse();
}
```

Based on what the error message is, you will be able to further debug what's happening. I am closing the issue for repo maintenance, but don't hesitate to reply back and we can reopen and discuss.

**Comment by AndyJAllen** [comment]
hi @vedanshujain  -- I am using a try catch... and I can successfully read data from customers/orders/products just fine. 

So right before you posted I thought I would add in the $body content in the HttpClient.php file to the exception output and its getting back the string " Security violated " from the website... So it seems there's an issue for me writing content, but not reading content.... Not sure why when my API key has read/write access.

I was also able to use the put command to update order line meta data. Odd I cannot use the post function to create a new customer.

**Comment by AndyJAllen** [comment]
I can PUT customer data at endpoint customers/x where x is the customer id...but posting to just endpoint "customers" results in 
 
`[body:Automattic\WooCommerce\HttpClient\Response:private] => Security violated`
