### ISSUE TITLE
when user enter the exisiting coupon at the time the page is RENDERING 

### ISSUE THREAD

**Issue by vp9112** [woothemes/woocommerce#37486]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

when we enter the already created or new coupon coupon creataing page is redering
click the woo commerce click the marketing click the coupon click the add new coupon or exisiting coupon 

### Expected behavior

when we enter the coupon or new coupon creating page do not page was rendered

### Actual behavior

when user enter the exisitng created coupon  or new coupon creating page that page was rendering

### Steps to reproduce

1.click the woo commerce
2.click the marketing
3.cick the coupon option
4.click the add new coupon or click the already created coupon 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8000
Site address (URL): http://localhost:8000
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 8.0.28
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.41
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 50.93MB
Database Data Size: 39.73MB
Database Index Size: 11.20MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 15.47MB + Index: 2.78MB + Engine InnoDB
wp_posts: Data: 5.11MB + Index: 0.23MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wlr_bulk_action: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_wlr_bulk_action_job: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wlr_display_conditions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wlr_earn_campaign: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wlr_earn_campaign_transaction: Data: 1.52MB + Index: 1.78MB + Engine InnoDB
wp_wlr_expire_points: Data: 1.50MB + Index: 1.80MB + Engine InnoDB
wp_wlr_levels: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wlr_logs: Data: 3.52MB + Index: 0.69MB + Engine InnoDB
wp_wlr_points_ledger: Data: 1.52MB + Index: 1.05MB + Engine InnoDB
wp_wlr_referral: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wlr_rewards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wlr_reward_transactions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wlr_users: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wlr_user_rewards: Data: 0.02MB + Index: 0.11MB + Engine InnoDB

### Post Type Counts ###

attachment: 35
customize_changeset: 1
elementor_library: 1
page: 15
post: 5
postman_sent_mail: 250
product: 25
product_variation: 9
revision: 18
shop_coupon: 263
shop_order: 357
shop_order_refund: 7
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Elementor: by Elementor.com – 3.11.2
Post SMTP: by Post SMTP – 2.4.3
Smart coupon manager for WooCommerce: by Flycart – 1.0.0
WooCommerce: by Automattic – 7.4.0 (update to version 7.5.1 is available)

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Code Snippets: by Code Snippets Pro – 3.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Ocean Extra: by OceanWP – 2.1.4
WooCommerce Payments: by Automattic – 5.5.2 (update to version 5.6.2 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WPLoyalty - Bulk action: by WPLoyalty – 1.0.0
WPLoyalty - Bundle product compatibility: by Wployalty – 1.0.0
WPLoyalty - Customize reward page and conditions: by WPLoyalty – 1.0.0
WPLoyalty - WooCommerce Loyalty Points, Rewards and Referral: by Wployalty – 1.2.0
WPLoyalty - WooCommerce Loyalty Points, Rewards and Referral Lite: by Wployalty – 1.2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 38
Onboarding: completed

### Action Scheduler ###

Complete: 586
Oldest: 2023-03-17 04:52:15 +0000
Newest: 2023-03-29 08:08:23 +0000

Failed: 3
Oldest: 2023-03-17 04:52:15 +0000
Newest: 2023-03-28 05:01:19 +0000

Pending: 1
Oldest: 2023-03-30 04:12:10 +0000
Newest: 2023-03-30 04:12:10 +0000

### Status report information ###

Generated at: 2023-03-29 09:19:04 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @vp9112,

Thank you for submitting this issue. 

To clarify, creating a coupon does not work for you. Is that correct? 

If so, please try deactivating the plugin "Smart coupon manager for WooCommerce". If the issue is then resolved you will need to contact that plugin's support team.

**Comment by vp9112** [comment]
No when we enter the creating coupon page the page was rendering
see this video for reference
[video-convert-1680162748379.webm](https://user-images.githubusercontent.com/113898119/228768147-aa3ba4c0-d080-4e9c-bd7b-0667cecbe165.webm)

**Comment by lsinger** [comment]
HI @vp9112,

Thank you for the video. Unfortunately I'm still not able to figure out what behavior you believe to be a bug. Could you provide a clear textual description, with a step-by-step explanation of what to do as well as a) what you expect to happen and b) what happens instead?

**Comment by rrennick** [comment]
Closing due to lack of feedback.
