### ISSUE TITLE
test cards can not be used

### ISSUE THREAD

**Issue by deancook010** [woothemes/woocommerce#37482]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I had the test credit cards enable.  The field to enter the card was not visible.   I was using the Storefront temple. 

the html was on the page but unelectable.
 <div class="wcpay-upe-element" data-payment-method-type="card" style="position: relative; zoom: 1;"></div>

### Expected behavior

I expect a field to put in the test card number.

### Actual behavior

![card_field_missing](https://user-images.githubusercontent.com/122460256/228364126-dd41de42-8ecf-4238-8265-745dd8df964f.jpg)

### Steps to reproduce

Gi to WooCommerce plugin page settings
Under payments tab
In genteral area.
select enable test mode.

### WordPress Environment

`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /blog/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: production
site_count: 1
network_count: 1
user_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Storefront (storefront)
version: 4.2.0
author: Automattic
author_website: https://woocommerce.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, custom-logo, menus, html5, custom-background, custom-header, site-logo, title-tag, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-style, responsive-embeds, amp, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, starter-content, widgets
theme_path: /home/renew/public_html/wp/wp-content/themes/storefront
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty-One: version: 1.7, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (3) ###

ShareASale WooCommerce Tracker: version: 1.5.3, author: ShareASale.com, Inc., Auto-updates enabled
WooCommerce: version: 7.5.1, author: Automattic, Auto-updates enabled
WooCommerce Payments: version: 5.6.2, author: Automattic, Auto-updates disabled

### wp-plugins-inactive (8) ###

Akismet Anti-Spam: version: 5.0.2, author: Automattic (latest version: 5.1), Auto-updates disabled
Google Listings and Ads: version: 2.4.1, author: WooCommerce, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Jetpack: version: 11.9.1, author: Automattic, Auto-updates disabled
MailPoet: version: 4.10.0, author: MailPoet, Auto-updates disabled
Pinterest for WooCommerce: version: 1.2.16, author: WooCommerce, Auto-updates disabled
TikTok: version: 1.0.16, author: TikTok, Auto-updates disabled
WooCommerce Shipping & Tax: version: 2.2.4, author: WooCommerce, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-13 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 100M
max_effective_size: 8 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64 x86_64
httpd_software: Apache
php_version: 8.1.16 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 90
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 100M
php_post_max_size: 8M
curl_version: 7.88.0 OpenSSL/1.1.1t
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.5.19-MariaDB
client_version: mysqlnd 8.1.16
max_allowed_packet: 268435456
max_connections: 200

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/renew/public_html/wp/wp-content
WP_PLUGIN_DIR: /home/renew/public_html/wp/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @deancook010,

It looks as though this may specifically be a problem with [WooCommere Payments](https://woocommerce.com/document/woocommerce-payments/), rather than it being a core WooCommerce problem. The best place to get further guidance would be [over here](https://woocommerce.com/my-account/create-a-ticket/?select=5278104).

Thanks!
