### ISSUE TITLE
HPOS: WP_Screen is not consistent between post table views and order table views

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#37484]
Sometimes plugins use properties of `WP_Screen` to determine what part of the WP Admin they're in so they can, e.g. customize the UI. When the custom order tables are authoritative, we're using a custom admin page to display a list table of orders and the edit UI for single orders, since we can't use the standard screens that assume a post type. However, it seems like we are trying to make the change in UI seamless, even if the URL is different. The `WP_Screen` object for the custom admin pages betrays this though, because some key properties are different:

**Orders List Table screen**

| Prop | Posts | Orders |
|--------|--------|--------|
| `base` | `edit` | `woocommerce_page_wc-orders` |
| `id` | `edit-shop_order` | `woocommerce_page_wc-orders` |
| `post_type` | `shop_order` | _empty_ |

**Single Order screen**

| Prop | Posts | Orders |
|--------|--------|--------|
| `base` | `post` | `woocommerce_page_wc-orders` |
| `id` | `shop_order` | `woocommerce_page_wc-orders` |
| `post_type` | `shop_order` | _empty_ |

So the question is, **would it make sense to try and replicate the screen props on the respective custom admin pages?**

Here's an example of how `WP_Screen` might be used, where it seems like we should assume that the intended functionality would work regardless of which set of tables is authoritative:

```php
$current_screen = get_current_screen();
if ( 'shop_order' == $current_screen->post_type ) {
	// Do stuff.
}
```

Maybe it wouldn't make sense to modify the `base` property since it's related to the file name in `wp-admin`. But perhaps the `id` and `post_type` should be the same?

**Comment by barryhughes** [comment]
I happened on [this discussion](https://woocommercecommunity.slack.com/archives/C1KAZ91E3/p1681585523852179) in Community Slack. The link will expire, but it's basically a question about adding custom columns to the order list table, and this developer found their answer in our upgrade guide:

> It is called `manage_woocommerce_page_wc-orders_custom_column`. `woocommerce_page_wc-orders` value comes from `wc_get_page_screen_id( 'shop-order' )` explained here:
>
> https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book

I wanted to flag here, just as a way of saying we should be careful not to break some of these newly crafted integrations when we address this issue.

**Comment by coreymckrill** [comment]
At the very least, the `id` property should differ between the Orders list table screen and single order screen, like it does for the Order CPT.

**Comment by coreymckrill** [comment]
@vedanshujain I know there are some concerns here about side effects / unintended consequences if we set the `post_type` property. Any thoughts here about the suggestions above?

**Comment by vedanshujain** [comment]
It should be fine to set the `post_type` property, or any other new property that can help users identify whether this is a edit screen or not. But we can't change the screen IDs from what they are currently (even if that means they are same for both order list table screen and single order screen). wdyt?

**Comment by coreymckrill** [comment]
> But we can't change the screen IDs from what they are currently (even if that means they are same for both order list table screen and single order screen).

Is this because the IDs have already been established and this would break backcompat?

I will look into updating the `post_type` prop and also see if there are any others in WP_Screen that could help us here. Maybe we could also add some helper methods like `is_order_list_screen` and `is_order_edit_screen`...

**Comment by vedanshujain** [comment]
Yep, it's because ID's are already established. Utilities also seems like a good idea!
