### ISSUE TITLE
Add new Woo REST API tests to `api-core-tests` to ensure all CRUD operations have an associated test

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#37497]
### Describe the solution you'd like

Add tests for the following rest API endpoints to ensure there is coverage for all CRUD operations:

- Customers
- Orders
- Products
- Product categories
- Shipping zone locations
- Shipping zone methods

Additions should equate to those listed in [this post](https://solarisp2.wordpress.com/2023/03/29/wc-core-rest-api-test-coverage-audit/)

### Describe alternatives you've considered

n/a - this is adding test coverage

**Comment by lanej0** [comment]
Closing this out in favour of the individual issues referenced above.
