### ISSUE TITLE
Attribute used for variation is checked by default (attribute_variation checkbox)

### ISSUE THREAD

**Issue by seldimi** [woothemes/woocommerce#37508]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After the latest release (7.5.1), when you add an attribute to a variable product (eg Brand), the option "Used for variation" is checked by default. This was not checked by default on any other versions of WooCommerce.

### Expected behavior

The option "Used for variation" should not be checked by default.

### Actual behavior

The option "Used for variation" is checked by default.

### Steps to reproduce

1. Goto a variable product
2. Add an attribute via the select box
3. "Used for variations" options will popup pre-checked.

### WordPress Environment

none

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by sukafia** [comment]
Assigning the bug label as I can replicate it. The issue only occurs when several attributes exist on the site. 

**Few attributes on the site:**
 ![RA6VVo.png](https://user-images.githubusercontent.com/60121732/229061818-70f68acf-c0e9-41fb-aff0-11620a34be14.png)

Works as expected with this attribute selection interface.

**Several attributes on the site:**

![5G7G6l.png](https://user-images.githubusercontent.com/60121732/229061886-34a78335-bf03-4cfa-bac7-1a92561c23df.png)

Behaviour changes on this interface. 

- Reported in 40076502-hc

**Comment by thisissandip** [comment]
I can replicate this from WC 7.5 and so on..

**Comment by octaedro** [comment]
Hi @seldimi, thank you for reporting this.

This change has been introduced intentionally in PR #36606 as [part of some changes](https://github.com/woocommerce/woocommerce/issues/37099) to improve attribute management.

I'm going to close this issue. Please don't hesitate to reach out if you have any further concerns or questions.

**Comment by seldimi** [comment]
Hello.
As far as I can see, its not on 7.7 yet

**Comment by seldimi** [comment]
Hello
Any news about this? Still confusing customers.
