### ISSUE TITLE
woocommerce_new_product, woocommerce_delete_product, woocommerce_trash_product, woocommerce_update_product actions do not fire when creating, updating or deleting a product from admin.

### ISSUE THREAD

**Issue by SSagar7979** [woothemes/woocommerce#37507]
I'm experiencing with WooCommerce product hooks. Specifically, when I try to add products to a third-party app using the hooks `woocommerce_new_product`, `woocommerce_update_product`, `woocommerce_trash_product`, and `woocommerce_delete_product`, the hooks don't seem to be firing as expected.

Here are the hooks I'm using:

```
add_action( 'woocommerce_new_product', 'create_product_action_callback', 10, 1 );

function create_product_action_callback( $product_id, $product ) {
      // I want to do something here...
}

add_action( 'woocommerce_update_product', 'update_product_action_callback', 10, 1 );
function update_product_action_callback( $product_id, $product ) {
       // I want to do something here...
}

add_action( 'woocommerce_trash_product', 'delete_product_action_callback', 10, 1 );
add_action( 'woocommerce_delete_product', 'delete_product_action_callback', 10, 1 );

function delete_product_action_callback( $product_id ) {
       // I want to do something here...
}
```

I would expect that these hooks would trigger whenever a product is created, updated, trashed, or deleted in WooCommerce, but for some reason they're not firing when I try to sync products to the third-party app.

**Comment by lsinger** [comment]
Hello @SSagar7979,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. Please use [the Bug Report template here](https://github.com/woocommerce/woocommerce/issues/new/choose).
