### ISSUE TITLE
Affiliate For WooCommerce | WP Mail SMTP | Endless loader

### ISSUE THREAD

**Issue by Nathan-MacD** [woothemes/woocommerce#37515]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After filling the registration form and pressing the submit button, the loader gets stuck. It's endlessly loading. This also happens when clicking the 'accept affiliate' link in the user dashboard.

However, after clicking the submit button in the form, the user is actually being added for review, but no email is being send to the user.

### Expected behavior

After pressing submit, a message should show saying the user is pending for review and they should receive an email of this.

### Actual behavior

It gets stuck in an endless loading loop

### Steps to reproduce

1. Fill in the fields of the form
2. Press submit button

1. Go to user dashboard
2. Click Approve/Reject affiliate

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hs.levelupwebshops.nl
Site address (URL): https://hs.levelupwebshops.nl
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 8.1.14
PHP Post Max Size: 256 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.4.27-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Totale database grootte: 1827.69MB
Database gegevens grootte: 1002.29MB
Database index grootte: 825.40MB
wp_woocommerce_sessions: Data: 10.52MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 28.56MB + Index: 11.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 273.84MB + Index: 266.61MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 8.52MB + Index: 15.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.42MB + Index: 0.45MB + Engine InnoDB
wp_comments: Data: 93.63MB + Index: 63.19MB + Engine InnoDB
wp_dpdconnect_batches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dpdconnect_jobs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dpdconnect_labels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_et_bloom_stats: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 7.52MB + Index: 7.06MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 4.52MB + Index: 5.88MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 2.52MB + Index: 0.50MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.09MB + Index: 0.25MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lws_wr_achieved_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lws_wr_historic: Data: 12.52MB + Index: 4.03MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 20.50MB + Index: 0.47MB + Engine InnoDB
wp_postmeta: Data: 370.95MB + Index: 322.92MB + Engine InnoDB
wp_posts: Data: 26.56MB + Index: 13.06MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sc_delivery_methods: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sc_delivery_zones: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.31MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 47.58MB + Index: 43.14MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 2.55MB + Engine InnoDB
wp_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.30MB + Index: 0.33MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 32.56MB + Index: 36.09MB + Engine InnoDB
wp_wc_order_stats: Data: 7.52MB + Index: 6.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 6.52MB + Index: 5.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.28MB + Index: 0.52MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.27MB + Index: 0.53MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.38MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgmza_nominatim_geocode_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 3.52MB + Index: 3.41MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.27MB + Index: 0.52MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zettle_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zettle_woocommerce_id_map: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4608
br_product_tab: 1
br_tabs_location: 1
custom_css: 1
elementor_library: 1
footer: 13
fpf_fields: 1
itsec-dash-card: 6
itsec-dashboard: 1
lws-wre-event: 6
lws-wre-pool: 1
nav_menu_item: 170
oembed_cache: 8
ovic_menu: 9
page: 38
po_product_options: 1
popup: 3
popup_theme: 8
post: 14
product: 693
product_variation: 1761
revision: 104
seedprod: 1
shop_coupon: 58
shop_order: 61228
shop_order_refund: 715
vc_settings_preset: 1
wafs: 1
wapf_product: 5
waymark_map: 3
wpcf7_contact_form: 2
xlwcty_thankyou: 1
yaymail_template: 38

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (52) ###

ManageWP - Worker: door GoDaddy – 4.9.16
Advanced Product Fields Pro for WooCommerce: door StudioWombat – 2.6.1
Affiliate For WooCommerce: door StoreApps – 6.5.0
All-in-One WP Migration: door ServMask – 7.73
Classic Editor: door WordPress Contributors – 1.6.3
Complianz | GDPR/CCPA Cookie Consent: door Really Simple Plugins – 6.4.3
Contact Form 7: door Takayuki Miyoshi – 5.7.5.1
Disable Cart Fragments: door Optimocha – 2.2
YayMail Pro - WooCommerce Email Customizer: door YayCommerce – 3.2.3
Envato Market: door Envato – 2.0.8
EWWW Image Optimizer: door Exactly WWW – 6.9.3
MonsterInsights - eCommerce Addon: door MonsterInsights Team – 8.3.9
MonsterInsights Pro: door MonsterInsights – 8.12.1
Site Plugin for hondenshop.nl: door  –
OMGF: door Daan from Daan.dev – 5.5.6
WPBakery Page Builder: door Michael M - WPBakery.com – 6.10.0
Limit Login Attempts Reloaded: door Limit Login Attempts Reloaded – 2.25.13
Loco Translate: door Tim Whitlock – 2.6.4
Mailchimp for WooCommerce: door Mailchimp – 2.8.1
Mollie Payments for WooCommerce: door Mollie – 7.3.5
WooCommerce Thank You Page - NextMove Power Pack: door XLPlugins – 1.2.0
Ovic: Import Demo: door Ovic Team – 1.6.1
Ovic Toolkit: door Ovic Team – 1.6.0
Product Video for WooCommerce: door Addify – 1.4.7
reBusted!: door Simon Prosser – 1.1
Sendcloud | Smart Shipping Service: door Sendcloud B.V. – 2.2.18
Shortcodes Ultimate: door Vova Anokhin – 5.12.11
Sucuri Security - Auditing, Malware Scanner and Hardening: door Sucuri Inc. – 1.8.37
WooCommerce Thank You Page - NextMove: door XLPlugins – 1.17.0
WooCommerce Adres Validatie: door SkyVerge – 2.10.0
WooCommerce Advanced Free Shipping: door Jeroen Sormani – 1.1.5
WooCommerce Back In Stock Notifications: door WooCommerce – 1.4.3
WooCommerce Europees btw-nummer: door WooCommerce – 2.8.2
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.4.0
PDF Invoices & Packing Slips for WooCommerce - Professional: door WP Overnight – 2.13.8
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: door WP Overnight – 2.19.6
WooCommerce Product Bundles: door WooCommerce – 6.18.3
WooCommerce Social Login: door SkyVerge – 2.12.0
WooCommerce: door Automattic – 7.5.1
MyRewards: door Long Watch Studio – 5.0.7
Yoast SEO Premium: door Team Yoast – 20.2.1
Yoast SEO: door Team Yoast – 20.4
WP Mail SMTP: door WPForms – 3.7.0
WP-Optimize - Clean, Compress, Cache: door David Anderson
Ruhani Rabin
Team Updraft – 3.2.14

WPC Grouped Product for WooCommerce: door WPClever – 4.1.0
Yoast SEO: Video: door Team Yoast – 14.6
Yoast SEO: WooCommerce: door Team Yoast – 15.6
YayMail Addon for Affiliate For WooCommerce: door YayCommerce – 1.2
Custom Product Tabs for WooCommerce: door YIKES
Inc. – 1.8.2

YITH WooCommerce Quick View: door YITH – 1.25.0
YITH WooCommerce Wishlist: door YITH – 3.19.0
PayPal Zettle POS: door PayPal – 1.5.5

### Inactive Plugins (1) ###

Bloom: door Elegant Themes – 1.3.12

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0
Onderhoud: door Myfasthosting –
WordPress automation by Installatron: door  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosg (woosg)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #17 - /shop/
Winkelwagen: #8 - /winkelwagen/
Afrekenen: #10 - /checkout/
Mijn account: #232 - /mijn-account/
Algemene voorwaarden: #3 - /privacy-policy/

### Theme ###

Name: Biolife Child
Version: 1.0.0
Author URL: https://kutethemes.com/
Child Theme: ✔
Parent Theme Name: Biolife
Parent Theme Version: 1.1.3
Parent Theme Author URL: https://kutethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: biolife/woocommerce/content-product.php
biolife/woocommerce/global/quantity-input.php versie 5.2.0 is verouderd. De hoofdversie is 7.4.0

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Back In Stock ###

Database Version: 1.4.3
Loopback Test: ❌ Loopback test failed.

### Product Bundles ###

Database Version: 6.18.3
Loopback Test: ❌ Loopback-test mislukt.
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-30 02:20:46 +02:00
Options: ✔
Notes: 23
Onboarding: completed

### Address Validation ###

Active Provider: Postcode.nl
Configured: ✔
Debug mode: No
Geocode adressen: No
Classificeer adres: No
Verplicht de klant om het adres op te zoeken via Postcode: No

### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: Disabled
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Disqus: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Canceled: 20
Oldest: 2023-02-27 18:06:18 +0100
Newest: 2023-03-26 12:33:17 +0200

Complete: 28.429
Oldest: 2023-02-27 12:24:39 +0100
Newest: 2023-03-30 15:40:15 +0200

Failed: 1
Oldest: 2022-12-17 17:47:17 +0100
Newest: 2022-12-17 17:47:17 +0100

Pending: 3
Oldest: 2023-03-31 04:35:30 +0200
Newest: 2023-03-31 13:30:09 +0200

### PayPal Zettle POS ###

Onboarding state: onboarding-completed
Price sync: yes
Initial sync collision strategy: merge
First import: 23:12 11 maart 2022
Number of products syncing: 645
PayPal Zettle VAT: 21
PayPal Zettle currency: EUR
PayPal Zettle country: NL
PayPal Zettle language: nl
PayPal Zettle time zone: Europe/Amsterdam
PayPal Zettle contact email: info@hondenschool.online
PayPal Zettle taxation mode: INCLUSIVE
PayPal Zettle taxation type: VAT
PayPal Zettle customer mode: LimitedCompany

### Status report information ###

Generated at: 2023-03-30 16:03:29 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Nathan-MacD** [comment]
This report is from my test environment, but also happens in the live environment. With only WooCommerce and WP Mail SMTP activated

**Comment by lsinger** [comment]
@Nathan-MacD,

Please specify which form you are experiencing the issue with. Is this about the user registration [on the right side here](https://hs.levelupwebshops.nl/mijn-account/)? If so that seems to be working fine.

**Comment by Nathan-MacD** [comment]
Hi, I've had contact with support and eventually the problem has been fixed. I think it was due to the SMTP settings of the host that got changed over without me knowing.

Apologies for not updating the ticket.

Cheers,
Nathan
