### ISSUE TITLE
Not able to add Custom Button on Stack Layout page

### ISSUE THREAD

**Issue by faisal-alvi** [woothemes/woocommerce#37510]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We are currently working on an enhancement in the Bookings plugin and would like to add a new custom button on the stack layout page that was introduced in version 7.2: https://developer.woocommerce.com/2022/12/14/woocommerce-7-2-0-released/.

We have been attempting to find any documentation or resources on how to add a new custom button on the WooCommerce 7.2+ Product Creation Step (built in React), but unfortunately, we have been unable to find any such information. We have also searched through the codebase and could not locate any filters (though we may have missed some).

Given this, we kindly request your assistance in guiding us on how to achieve our requirement of adding a custom button on the WooCommerce 7.2+ Product Creation Step. Could you please provide us with any necessary documentation or resources that would help us achieve our goal?

![image](https://user-images.githubusercontent.com/25176325/228825081-6645d511-0b65-45b9-adcc-4e90ce718cf2.png)

**Comment by chihsuan** [comment]
Thanks for bringing this up! @faisal-alvi 

It's not achievable at this moment because the [options are hard-coded](
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/tasks/fills/products/constants.tsx
). We'll look into it and possibly add SlotFills for extensibility.

**Comment by chihsuan** [comment]
An option is to temporarily add a new button to Stack Layout page in WC Core for Booking. Let me know if need more information.

**Comment by faisal-alvi** [comment]
Thanks for the suggestion @chihsuan, but we don't want to add a new button to the Stack Layout page temporarily, we'll wait until a dynamic way is added.

**Comment by adrianduffell** [comment]
It would be great if this screen just by default automatically listed all of the additional product types registered with WooCommerce. That way, 3PDs wouldn't need to explicitly customize anything on this screen 🤔 

@verofasulo What do you think about adding all of the available product types to this screen, including ones added by extensions such as Bookings?

**Comment by verofasulo** [comment]
> What do you think about adding all of the available product types to this screen, including ones added by extensions such as Bookings?

@adrianduffell, it makes total sense to me! Looping also @jarekmorawski in as he's working on this flow.

**Comment by jeffpaul** [comment]
I assume the main quesstion there @adrianduffell would be where to pull the image/title/description in those additional product cards in a reliable way from other active extensions, thus having things be filterable/slotfilled would allow for reliable output on this screen from extensions intentionally targeting this design (though I do see the benefit in trying to support any active extension adding a new product type).

**Comment by faisal-alvi** [comment]
It's great to see https://developer.woo.com/2024/03/22/extending-product-onboarding-and-tour/

Not sure where the relative PR is to link with this ticket, but we can also simply close this out. :)

**Comment by adrianduffell** [comment]
Thanks @faisal-alvi , the PR is https://github.com/woocommerce/woocommerce/pull/44892 and indeed we can close this now!
