### ISSUE TITLE
Coupon is adding value of discounted product as opposed to subtracting it

### ISSUE THREAD

**Issue by justinlpratley** [woothemes/woocommerce#37512]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When user adds a product with an associated BOGO option using Advanced Coupons plugin, cost of free products are added to checkout price not subtracted.

### Expected behavior

Products should be free not added. 

### Actual behavior

Cost of Free products are added to the total and not subtracted or zeroed out. 

### Steps to reproduce

1. Add product eligible for BOGO to cart with the required conditions

![image](https://user-images.githubusercontent.com/129396225/228841970-afede27c-f679-4155-bb69-2051b51f5876.png)
![image](https://user-images.githubusercontent.com/129396225/228842120-83201c2d-c1e2-4e34-ae60-67b755120a5a.png)

2. Go to checkout
![image](https://user-images.githubusercontent.com/129396225/228842275-9607410f-3da4-49ce-b800-64117ff8b035.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.haircolours.co.za
Site address (URL): https://www.haircolours.co.za
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.38-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wpix_
Total Database Size: 49.50MB
Database Data Size: 41.54MB
Database Index Size: 7.96MB
wpix_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpix_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wpix_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpix_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_actionscheduler_actions: Data: 1.02MB + Index: 0.25MB + Engine InnoDB
wpix_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_actionscheduler_logs: Data: 1.50MB + Index: 0.55MB + Engine InnoDB
wpix_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpix_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_frmt_form_entry: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpix_frmt_form_entry_meta: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpix_frmt_form_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_frmt_form_views: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_options: Data: 4.05MB + Index: 0.14MB + Engine InnoDB
wpix_postmeta: Data: 23.38MB + Index: 4.63MB + Engine InnoDB
wpix_posts: Data: 9.27MB + Index: 0.34MB + Engine InnoDB
wpix_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpix_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpix_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpix_uap_action_log_meta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpix_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpix_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpix_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpix_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpix_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpix_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpix_uap_trigger_log_meta: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wpix_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpix_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpix_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpix_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpix_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpix_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpix_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpix_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wpix_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpix_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wpml_mails: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wpix_wpwhpro_authentication: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wt_iew_action_history: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpix_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpix_wt_sc_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 896
bp3d-model-viewer: 2
customize_changeset: 7
e-landing-page: 1
elementor_library: 2
forminator_forms: 3
nav_menu_item: 38
page: 22
popup: 4
popup_theme: 8
post: 5
product: 124
product_variation: 166
revision: 923
shop_coupon: 17
shop_order: 26
shop_order_refund: 1
uo-action: 1
uo-recipe: 3
uo-trigger: 6
wpforms: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

3D Viewer: by bPlugins LLC – 1.3.3
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.3
Advanced Custom Fields: by WP Engine – 6.0.7
Ajax Search Lite: by Ernest Marcinko – 4.11
Burger Companion: by burgersoftware – 6.5
Content Control: by Code Atlantic – 1.1.10
Easy Google Fonts: by Titanium Themes – 2.0.4
Elementor: by Elementor.com – 3.12.0
Enable Media Replace: by ShortPixel – 4.1.0
Forminator: by WPMU DEV – 1.22.1
Hide Categories and Products for Woocommerce: by N.O.U.S. Open Useful and Simple – 1.2.7
Hide Price Until Login: by CedCommerce – 1.1.1
Import and export users and customers: by codection – 1.22.1
Kadence Starter Templates: by Kadence WP – 1.2.19
Nav Menu Roles: by Kathy Darling – 2.1.2
Order Export & Order Import for WooCommerce: by WebToffee – 2.3.2
Popup Maker: by Popup Maker – 1.18.1
Product Import Export for WooCommerce: by WebToffee – 2.2.8
SKT Templates: by SKT Themes – 4.9.7
Sparkle Demo Importer: by sparklewpthemes – 1.3.8
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.4
Uncanny Automator: by Uncanny Automator
Uncanny Owl – 4.13.0.1

User Role Editor: by Vladimir Garagulya – 4.63.3
WooCommerce Peach Payments Gateway: by Peach Payments – 3.1.6
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
Product Slider and Carousel with Category for WooCommerce: by WP OnlineSupport
Essential Plugin – 2.8

Woo Shortcodes Kit: by Alberto G. – 2.0.2
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.6.2
WooCommerce: by Automattic – 7.5.1
ShopLentor – WooCommerce Builder for Elementor & Gutenberg: by HasThemes – 2.5.8
WP File Manager: by mndpsingh287 – 7.1.8
WP Mail Logging: by WP Mail Logging Team – 1.11.0
WP Mail SMTP: by WPForms – 3.7.0
WPForms Lite: by WPForms – 1.8.1.1
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.4.5

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 5.1
Automizely Popup - Email Pop Up, Sales Pop Up, Exit Intent Pop Up, Upsell Pop Up, Cart Abandonment Pop Up: by Automizely Marketing – 1.0.17
Hello Dolly: by Matt Mullenweg – 1.7.2
Product Feed PRO for WooCommerce: by AdTribes.io – 12.4.2
WPC Show Single Variations for WooCommerce: by WPClever – 2.2.2
WP Webhooks: by Ironikus – 3.3.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /our-products/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #10 - /refund_returns/

### Theme ###

Name: Kadence
Version: 1.1.35
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-31 08:34:52 +02:00
Options: ✔
Notes: 124
Onboarding: skipped

### Action Scheduler ###

Complete: 650
Oldest: 2023-03-17 13:42:21 +0000
Newest: 2023-03-30 12:45:17 +0000

Failed: 6
Oldest: 2023-03-17 13:44:14 +0000
Newest: 2023-03-26 10:01:19 +0000

Pending: 8
Oldest: 2023-03-30 12:51:02 +0000
Newest: 2023-04-06 02:45:32 +0000

### Status report information ###

Generated at: 2023-03-30 14:51:06 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @justinlpratley,

Thank you for submitting this issue. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the Advanced Coupons plugin. To get further technical support for it, please contact the developers of the plugin.
