### ISSUE TITLE
Product creation experience: keep regular and sale price fields for all product types. 

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#37528]
**Description:** when the user selects the variable or bundle product type, we remove the General tab where we display regular and sale prices. The absence of system status communication may cause the user to feel confused about what to do next to add the price.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/79307566/223413537-2eaa881b-0c7f-49b0-a227-46567277990c.png">

**Acceptance criteria:**

- [ ] We always show the regular and sale price fields. For product types that don't require them, like variable and grouped, we disable them, so the user cannot enter and edit values.
- [ ] When the fields are disabled, we change the cursor to `not-allowed;` to indicate the fields are not interactive. They also have 50% opacity (their state should be properly reflected in the code in line with accessibility guidelines).
- [ ] The fields are disabled even if they contain previously added values. 

**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Comment by mattsherman** [comment]
Closing this issue... merged into #33540, since it makes sense to tackle these both at the same time.
