### ISSUE TITLE
EU VAT plugin has loose `session_start()` call

### ISSUE THREAD

**Issue by planttheidea** [woothemes/woocommerce#37553]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the two sites I have this plugin active, I was receiving the classic "An active PHP session was detected" error. After grepping for all possible implementations, I discovered the call in `alg-wc-eu-vat-functions-general.php` that appeared naive. As an experiment, I changed the `session_start()` call to the safer `session_start([ 'read_and_close' => true ])` call, and the notification disappeared.

### Expected behavior

No loose remainder sessions

### Actual behavior

Loose session, resulting in the notification "A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests."

### Steps to reproduce

This one is tough, because it was just a matter of having the plugin installed. This issue has been present for months, I just finally was able to narrow in on the cause.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.ikonographia.com
Site address (URL): https://www.ikonographia.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.9.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2
PHP Version: 8.1.17
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.7.41
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 88.74MB
Database Data Size: 77.66MB
Database Index Size: 11.08MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.23MB + Index: 0.15MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.12MB + Engine MyISAM
wp_aioseo_cache: Data: 0.16MB + Index: 0.01MB + Engine MyISAM
wp_aioseo_notifications: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_aioseo_posts: Data: 0.94MB + Index: 0.04MB + Engine MyISAM
wp_as3cf_items: Data: 1.94MB + Index: 0.39MB + Engine MyISAM
wp_aws_cache: Data: 0.11MB + Index: 0.00MB + Engine MyISAM
wp_aws_index: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_blc_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_instances: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_blc_links: Data: 0.35MB + Index: 0.04MB + Engine MyISAM
wp_blc_synch: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_ac_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_connection_reports: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_no_cookie_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_sfw: Data: 0.23MB + Index: 0.43MB + Engine MyISAM
wp_cleantalk_sfw_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_spamscan_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cleantalk_ua_bl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
wp_gla_merchant_issues: Data: 0.26MB + Index: 0.01MB + Engine MyISAM
wp_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_capability: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_groups_group: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_group_capability: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_capability: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_group: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_monsterinsights_pageinsights_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 6.16MB + Index: 0.77MB + Engine MyISAM
wp_options_20130114: Data: 0.29MB + Index: 0.02MB + Engine MyISAM
wp_postmeta: Data: 26.18MB + Index: 1.05MB + Engine MyISAM
wp_posts: Data: 7.75MB + Index: 0.20MB + Engine MyISAM
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_404: Data: 0.70MB + Index: 0.14MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs: Data: 0.76MB + Index: 0.11MB + Engine MyISAM
wp_sib_model_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sib_model_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_auth_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_backuped_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_backups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_firewall_data: Data: 2.35MB + Index: 3.36MB + Engine MyISAM
wp_spbc_firewall_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_scan_frontend: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_scan_links_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_scan_results: Data: 3.83MB + Index: 1.05MB + Engine MyISAM
wp_spbc_scan_signatures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_traffic_control_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.05MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
wp_wfblocks7: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wfconfig: Data: 3.02MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 9.15MB + Index: 0.96MB + Engine MyISAM
wp_wfhits: Data: 0.76MB + Index: 0.12MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 6.90MB + Index: 0.29MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.16MB + Index: 0.06MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpbackitup_job_control: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpbackitup_job_items: Data: 1.25MB + Index: 0.14MB + Engine MyISAM
wp_wpbackitup_job_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpr_rocket_cache: Data: 0.15MB + Index: 0.18MB + Engine MyISAM
wp_wpr_rucss_used_css: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_yoast_indexable: Data: 1.02MB + Index: 0.17MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.07MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_links: Data: 1.77MB + Index: 0.30MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM

### Post Type Counts ###

attachment: 982
custom_css: 1
et_body_layout: 4
et_footer_layout: 1
et_pb_layout: 98
et_template: 7
et_theme_builder: 1
layout: 16
nav_menu_item: 11
oembed_cache: 20
page: 41
post: 34
product: 341
product_variation: 57
project: 2
revision: 8
shop_coupon: 7
shop_order: 81
shop_order_refund: 1
wpautoterms_page: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Query Monitor: by John Blackbourn – 3.12.1
Share This Image: by ILLID – 1.76
WooCommerce Checkout & Account Field Editor: by ThemeLocation – 1.2.8
All in One SEO: by All in One SEO Team – 4.3.4.1
WP Offload Media: by Delicious Brains – 3.2.1
Broken Link Checker: by WPMU DEV – 2.0.0
Anti-Spam by CleanTalk: by СleanTalk  – 6.7
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
EU VAT for WooCommerce Pro: by WPWhale – 1.8.0
FileBird: by Ninja Team – 5.1.5
Gelato Integration for WooCommerce: by Gelato – 1.0.6
MonsterInsights Pro: by MonsterInsights – 8.14.0
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.6.1
MonsterInsights - EU Compliance: by MonsterInsights Team – 2.2.5
MonsterInsights - Media Addon: by MonsterInsights Team – 1.0.7
MonsterInsights - Page Insights Addon: by MonsterInsights Team – 1.5.3
MonsterInsights - Performance Addon: by MonsterInsights Team – 1.7.3
OptinMonster: by OptinMonster Popup Builder Team – 2.13.0
PW WooCommerce Bulk Edit: by Pimwick
LLC – 2.113

Redirection: by John Godley – 5.3.10
SQLite Object Cache: by Oliver Jones – 1.2.3
Advanced Editor Tools: by Automattic – 5.9.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.3.26

Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.2
Digital Goods for WooCommerce Checkout: by theDotstore – 3.7.0
WooCommerce Blocks: by Automattic – 9.9.0
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.1.28
More Sorting Options for WooCommerce: by WP Wham – 3.2.9
WooCommerce Payments: by Automattic – 5.6.2
WooCommerce: by Automattic – 7.5.1
Wordfence Security: by Wordfence – 7.9.2
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Fastest Cache: by Emre Vona – 1.1.2
WP Mail SMTP: by WPForms – 3.7.0

### Inactive Plugins (4) ###

Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.58
WooCommerce Google Analytics Integration: by WooCommerce – 1.7.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.3
WP Rocket: by WP Media – 3.13

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: SQLite Object Cache (Drop-in)

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #3665 - /shop/
Cart: #3666 - /cart/
Checkout: #3667 - /checkout/
My account: #3668 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Extra
Version: 4.20.2
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### More Sorting Settings ###

More Sorting for WooCommerce: yes
Custom Sorting: yes
Sort by date (ascending): 
Sort by date (descending): 
Sort by title: A to Z: 
Sort by title: Z to A: 
Sort by slug: A to Z: 
Sort by slug: Z to A: 
Sort by SKU: low to high: Sort by SKU: low to high
Sort by SKU: high to low: Sort by SKU: high to low
Sort by SKU: no
Sort by stock quantity: low to high: Sort by stock quantity: low to high
Sort by stock quantity: high to low: Sort by stock quantity: high to low
Sort by total sales: low to high: 
Sort by total sales: high to low: 
Sort by last modified date: oldest to newest: 
Sort by last modified date: newest to oldest: 
Sort by author ID (ascending): 
Sort by author ID (descending): 
Sort by product ID (ascending): 
Sort by product ID (descending): 
Sort by number of comments (ascending): 
Sort by number of comments (descending): 
Random sorting: 
No sorting: 
Custom Meta Sorting: no
Total Options: 1
Enable/Disable: yes
Type: meta_value
Meta Key: 
Secondary Sorting: none
Order: asc
Parameter: custom_sorting_1
Title: Custom Meta Sorting #1
Default Sorting Options: no
Default sorting: Default sorting
Sort by popularity: Sort by popularity
Remove "Sort by popularity": no
Sort by average rating: Sort by average rating
Remove "Sort by average rating": no
Sort by newness: Sort by newness
Remove "Sort by newness": no
Sort by price: low to high: Sort by price: low to high
Remove "Sort by price: low to high": no
Sort by price: high to low: Sort by price: high to low
Remove "Sort by price: high to low": no
Rearrange Sorting: no
Rearrange Sorting: menu_order
popularity
rating
date
price
price-desc
date-asc
date-desc
title-asc
title-desc
name-asc
name-desc
sku-asc
sku-desc
stock_quantity-asc
stock_quantity-desc
total_sales-asc
total_sales-desc
modified-asc
modified-desc
author-asc
author-desc
product_id-asc
product_id-desc
comment_count-asc
comment_count-desc
rand
none
Remove All Sorting (Including WooCommerce Default): no
Enable/Disable: no
Theme: avada

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-03 13:09:28 +00:00
Options: ✔
Notes: 127
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.2
Connected to WPCOM: Yes
Blog ID: 157514044
Account ID: acct_1M1XWfFmUyn0056k

### Action Scheduler ###

Complete: 582
Oldest: 2023-03-03 17:14:29 +0000
Newest: 2023-04-03 00:48:41 +0000

Failed: 103
Oldest: 2022-03-15 18:00:21 +0000
Newest: 2023-04-02 23:05:16 +0000

Pending: 5
Oldest: 2023-04-03 01:03:41 +0000
Newest: 2023-04-05 21:11:22 +0000

### Status report information ###

Generated at: 2023-04-03 00:48:55 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hi @planttheidea,

Thank you for submitting this issue. You have checked the `I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.` option in your report, but from the description it sounds like you were able to pinpoint the issue to the EU VAT plugin. Could you let us know which one it is? Thanks!

**Comment by planttheidea** [comment]
Ah apologies, that is what I get for scanning; I stopped reading after "I have deactivated other plugins" haha. I did indeed confirm it was the EU VAT plugin.

**Comment by psealock** [comment]
Thanks for the confirmation @planttheidea. Since that plugin is owned by `WPWhale`, I'd suggest contacting them. Thanks
