### ISSUE TITLE
When using the WC CRUD `set_image_id()` method, the product image is still `Unattached` in Media Library

### ISSUE THREAD

**Issue by kanlukasz** [woothemes/woocommerce#37563]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the WC CRUD `set_image_id()` method, the product image is still `Unattached` in Media Library

![image](https://user-images.githubusercontent.com/30685349/229729604-e732d20a-bdc6-4be5-bb59-f69dc58dc3dd.png)

### Expected behavior

It seems to me that when I use this method, the image should be attached in the Media Library ?

### Actual behavior

The product image is still `Unattached` in Media Library

### Steps to reproduce

1. Add image

2. Copy image ID

3. Run CRUD:
    ```
    $product = new WC_Product_Simple();
    $product->set_sku('TEST');
    $product->set_name('TEST');
    $product->set_regular_price(111);
    $product->set_image_id(63740);
    $product->save();
    ```

### WordPress Environment

- PHP 8.0
- WP 6.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Addressed in #40076
