### ISSUE TITLE
Installing Woocommerce 7.5.1 Flagged by Windows Defender Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by Mjose99** [woothemes/woocommerce#37572]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I am unable to install woocommerce as it is being flagged as a virus Trojan:Win32/Emali.A!cl

How can it be fixed?

Thanks
Maria 

### Expected behavior

Expected to install woocommerce

### Actual behavior

unable to install

### Steps to reproduce

install via plugins install or by downloading the file

### WordPress Environment

Cant install it

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by xranto** [comment]
I have the same problem

**Comment by tammullen** [comment]
Thanks for flagging this
I was initially able to see the same thing with Windows Defender on Windows 11 with the definitions from 5th April.
![Screenshot 2023-04-06 at 01 08 37](https://user-images.githubusercontent.com/24649833/230354295-5f64c2f2-7a44-40a0-8f55-10f931d6e520.png)

We have reported this issue as a false positive to Microsoft and with the latest definitions from today 6th April `woocommerce.7.5.1.zip` no longer is being flagged by Windows Defender.

If you are still seeing it flagged please update your Windows Defender Definitions [https://www.microsoft.com/en-us/wdsi/defenderupdates](https://www.microsoft.com/en-us/wdsi/defenderupdates) and try scanning again.
