### ISSUE TITLE
Accessibility Improvements ‣ Mini-Cart Widget ‣ Item Removals

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37597]
When an item is removed from the mini-cart widget, screen readers are not informed of the results of the operation [(see original note)](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-514847308).

<div align="center"><img src="https://user-images.githubusercontent.com/3594411/230434363-50fb9401-80ab-4a76-b126-30dd67a7a0bf.gif" align="center" width="300px"></div>

The solution proposed in the original note was that we create divs such as `<div role=status class=screen-reader-text>` somewhere within the mini cart widget, using events such as `adding_to_cart`, `added_to_cart`, and `cart_page_refreshed` (or whatever events are triggered by the mini cart) to populate the div dynamically.

**Comment by jeffpaul** [comment]
Note that @Manussakis has a PR up for this that's going through review
