### ISSUE TITLE
get_options function is deprecated since version 3.1 on WooCommerce 7.5.1

### ISSUE THREAD

**Issue by mujuonly** [woothemes/woocommerce#37592]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[Thu Apr 06 16:47:33.151592 2023] [php:notice] [pid 10959] [client ::1:53943] The Automattic\\WooCommerce\\Admin\\API\\Options::get_options function is deprecated since version 3.1., referer: http://localhost/wordpress/wp-admin/post-new.php?post_type=product&tutorial=true

### Expected behavior

There should no be warning logged in for latest version

### Actual behavior

Warning logged in for latest version

### Steps to reproduce

1. Create product first time

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) PHP/8.2.4
PHP Version: 8.2.4
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.0.1
(SecureTransport) OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 10.4.18-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 3.95MB
Database Data Size: 2.51MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Import Export Suite for WooCommerce: by WebToffee – 1.1.4
WooCommerce: by Automattic – 7.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /index.php/shop/
Cart: #6 - /index.php/cart/
Checkout: #7 - /index.php/checkout/
My account: #8 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-07 11:06:23 +00:00
Options: ✔
Notes: 38
Onboarding: -

### Action Scheduler ###

Complete: 3
Oldest: 2023-04-06 11:07:45 +0000
Newest: 2023-04-06 11:17:17 +0000

Pending: 1
Oldest: 2023-04-07 11:07:45 +0000
Newest: 2023-04-07 11:07:45 +0000

### Status report information ###

Generated at: 2023-04-06 11:17:58 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by StSaens** [comment]
I'm seeing the same error, but different referer: /wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue

`Backend log: The Automattic\\WooCommerce\\Admin\\API\\Options::get_options function is deprecated since version 3.1.\n, referer: https://site.nl/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue`

**Comment by Luc45** [comment]
I'm also seeing this on QIT: `The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 6.3.`

Backtrace if it helps:
```
[{"file":"\/var\/www\/html\/wp-includes\/class-wp-hook.php","line":326,"function":"{closure}"},{"file":"\/var\/www\/html\/wp-includes\/class-wp-hook.php","line":348,"function":"apply_filters","class":"WP_Hook","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/plugin.php","line":517,"function":"do_action","class":"WP_Hook","type":"->"},{"file":"\/var\/www\/html\/wp-content\/plugins\/woocommerce\/includes\/wc-deprecated-functions.php","line":49,"function":"do_action"},{"file":"\/var\/www\/html\/wp-content\/plugins\/woocommerce\/src\/Admin\/API\/Options.php","line":115,"function":"wc_deprecated_function"},{"file":"\/var\/www\/html\/wp-content\/plugins\/woocommerce\/src\/Admin\/API\/Options.php","line":79,"function":"user_has_permission","class":"Automattic\\WooCommerce\\Admin\\API\\Options","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/rest-api.php","line":839,"function":"get_item_permissions_check","class":"Automattic\\WooCommerce\\Admin\\API\\Options","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/class-wp-hook.php","line":324,"function":"rest_send_allow_header"},{"file":"\/var\/www\/html\/wp-includes\/plugin.php","line":205,"function":"apply_filters","class":"WP_Hook","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/rest-api\/class-wp-rest-server.php","line":454,"function":"apply_filters"},{"file":"\/var\/www\/html\/wp-includes\/rest-api.php","line":424,"function":"serve_request","class":"WP_REST_Server","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/class-wp-hook.php","line":324,"function":"rest_api_loaded"},{"file":"\/var\/www\/html\/wp-includes\/class-wp-hook.php","line":348,"function":"apply_filters","class":"WP_Hook","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/plugin.php","line":565,"function":"do_action","class":"WP_Hook","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/class-wp.php","line":418,"function":"do_action_ref_array"},{"file":"\/var\/www\/html\/wp-includes\/class-wp.php","line":813,"function":"parse_request","class":"WP","type":"->"},{"file":"\/var\/www\/html\/wp-includes\/functions.php","line":1336,"function":"main","class":"WP","type":"->"},{"file":"\/var\/www\/html\/wp-blog-header.php","line":16,"function":"wp"},{"file":"\/var\/www\/html\/index.php","line":17,"args":["\/var\/www\/html\/wp-blog-header.php"],"function":"require"}]
```

GPT Analysis:
Here's a breakdown of the backtrace leading to the deprecation notice:

- The deprecated function is called from within the `Options` class of the WooCommerce Admin API ([Options.php on line 115](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Options.php#L115)).
- This call is part of a permission check (`user_has_permission` method on [line 79](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Options.php#L79) of the same file).
- The REST API infrastructure of WordPress is involved, as indicated by the inclusion of `wp-includes/rest-api.php` and related hooks and filters.
- The request is being served by the WP REST Server (class-wp-rest-server.php).
- Ultimately, the deprecation notice is generated during a REST API request to the WordPress site.

**Comment by Babylon1999** [comment]
one more zd-7353581

https://wordpress.org/support/topic/woocommerceblocksassetsapi-update_script_data_cache-set_transient/

**Comment by Babylon1999** [comment]
According to [this thread](https://wordpress.org/support/topic/wordpress-database-error-commands-out-of-sync-27/), the server performance is also affected, not sure if it's related.

**Comment by shopsat2008** [comment]
I also have this problem
Also, I saw a problem in the Cramp board on all sites, which does not work properly in WooCommerce. How can I report it? The problem is that the default branch doesn't work properly, it doesn't show the next branch, I must take a video so you can understand it.
