### ISSUE TITLE
Accessibility Improvements ‣ Shop ‣ Ajax Add-to-Cart

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37598]
It was reported that, when ajax add to cart functionality is used, screen readers are not informed of the operation's result (see [original note](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-514847308) and [related issue](https://github.com/woocommerce/woocommerce/issues/37597)).

<div align="center"><img src="https://user-images.githubusercontent.com/3594411/230436635-8979189b-60e4-4347-bb7f-61a37be2612f.gif" width="250px"></div>

The original proposal was that we create divs such as `<div role=status class=screen-reader-text>` after the add-to-cart button and use `adding_to_cart`, `added_to_cart`, `cart_page_refreshed`, and/or other suitable events to populate the div dynamically.

**Comment by jeffpaul** [comment]
Note that @Manussakis has a PR up for this that's going through review
