### ISSUE TITLE
Accessibility Improvements ‣ Cart ‣ Shipping Options Focus

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37606]
As originally noted [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-1114266579), it is possible to tab into and select shipping options via keyboard. However, on selecting the next shipping option (ie, using the cursor keys), the focus is lost.

<div align="center"><img src="https://user-images.githubusercontent.com/3594411/230459399-bc0f5de7-252d-4516-8824-dd8939c6927a.gif" width="440"></div>

This means the user has to tab back into the shipping options (at least in most cases, this is only one extra key-stroke, but it's still unnecessary/could be confusing).

**Comment by tarunvijwani** [comment]
I couldn't get enough time to work on this issue during the cooldown. I'll try to pick it up again in the next cooldown.

**Comment by Manussakis** [comment]
I have started working on this issue.
