### ISSUE TITLE
Accessibility Improvements ‣ Product Page ‣ Quantity Input

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37604]
As originally reported [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-873422417), the single product page quantity selector has a `title` attribute which we may wish to replace or remove.

<div align="center"><img width="240" alt="quantity-title-attr" src="https://user-images.githubusercontent.com/3594411/230450678-672d8029-698b-43e2-a851-0282a718320d.png"></div>

Notes:

- This sometimes gets in the way on hover (and can only be used on hover, so it requires a mouse).
- The title attribute sometimes is and sometimes is not read by screen readers.  
- On zoom, all text becomes really large, except for the tooltip on the title attribute. 

See the W3C HTML 5 recommendations here: https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute.

**Comment by Sidsector9** [comment]
@chihsuan I would live to work on this issue.
