### ISSUE TITLE
Accessibility Improvements ‣ Cart ‣ Update Cart Button

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37600]
As originally noted [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-779227823), when the **Update Cart** button is disabled the use of `aria-disabled="true"` is redundant, and may cause problems, as we already have a regular `disabled` attribute in place:

<img width="813" alt="cart-disabled-update-button" src="https://user-images.githubusercontent.com/3594411/230442890-5eb723be-684e-48f5-9cac-99835114058c.png">

**Comment by faisal-alvi** [comment]
Hi @chihsuan 👋🏻  I would like to work on this.
