### ISSUE TITLE
Accessibility Improvements ‣ Shop ‣ Tabulation

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37605]
As originally noted [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-873422417), if navigating through the product catalog via keyboard there are more tabs (at least two per product) than perhaps are strictly required (one per product).

<div align="center"><img src="https://user-images.githubusercontent.com/3594411/230452490-a41da6a0-7577-4cd2-8160-f41f7ac99db3.gif" width="700"></div>

Let's review and simplify if possible and practicable.

**Comment by CacheMeOwside** [comment]
Hi @barryhughes,

I would like to work on this improvement and I see two possible scenarios here:
    1. Customers wanting to directly add a product to cart.
    2. Customers wanting to navigate to the single-product page to view the product details.

If we implement a single tab per product, the user will either be able to add to cart or navigate to the single-product page, but not both.

Please let me know if you have any suggestions on how we can go about this.

**Comment by barryhughes** [comment]
Thanks for looking at this, @Kaav-notabot.

You are completely correct. In fact, I think the reality is that this problem has been solved. As my own screencast shows, there is only one container for the product image and product title, not two ... I just misunderstood when creating the issue.

On that basis, I think this can actually be closed—though let me know if you disagree. Sorry for the confusion!
