### ISSUE TITLE
Product quantity button disappears when using the latest version of WooCommerce with Astra Theme and Astra Pro addon

### ISSUE THREAD

**Issue by yssambare12** [woothemes/woocommerce#37615]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are the **team Astra theme** and we have discovered an issue related to your **latest version of WooCommerce.** 

We have found that when a user adds a product to their cart, the product quantity **[button disappears](https://d.pr/v/dfEPre)**. Upon further investigation, we have found that this issue only appears when using the latest version of WooCommerce. 

However, when we rolled back to the previous version of WooCommerce (v7.4.1), the issue was resolved. We believe this issue could impact other theme developers and their users who are using the latest version of WooCommerce. 

We would like to request that you investigate this issue to ensure that it does not impact the functionality of WooCommerce. 

Check The document for detailed explanation - [Document ](https://docs.google.com/document/d/1az0xtpnDU1QthIYVeBxGhGyqK200xtiHF2XZR6LTXaw/edit?usp=sharing)

PR where we resolved this issue - https://github.com/brainstormforce/astra/pull/5092

### Expected behavior

Expected behavior would be that when a user adds a product to their cart, the product quantity button should be visible and functional. The quantity button should allow the user to increase or decrease the quantity of the product in their cart. 

The functionality of the quantity button should not be affected by the version of WooCommerce being used or by the Astra theme or Astra Pro addon.

### Actual behavior

**Screenshot with issue explanation** - https://share.getcloudapp.com/NQuWN285

We have discovered an issue related to versions 7.5.0 and 7.5.1 of WooCommerce. When a user adds a product to their cart and tries to increase or decrease the quantity using the plus and minus buttons, the quantity button disappears. 

This behavior occurs only when using the latest version of WooCommerce and the Astra theme with the Astra Pro addon. However, when we rolled back to version 7.4.1 of WooCommerce, the issue was resolved.

We believe this issue could impact other theme developers and their users who are using the latest version of WooCommerce. We would like to request that you investigate this issue to ensure that it does not impact the functionality of WooCommerce.

We have created a PR - [](https://github.com/brainstormforce/astra/pull/5092) that fixes this issue, and we would like to ask for your review and feedback before releasing it in our next update.

### Steps to reproduce

1. Here are the steps to replicate the issue:
2. Install the Astra theme and the Astra Pro addon.
3. Install and activate the Woocommerce plugin.
4. Activate the Woocommerce Pro addon from the Astra Pro addons list (navigate from Dashboard > Astra menu)
5. From Customizer > Header Builder, add the cart to the header.
6. In the Woocommerce section of the Customizer, go to the Misc section and enable the "Quantity Plus Minus Option Toggle" option.
7. Check the frontend by adding a product to the cart and increasing the product count. The quantity button disappears. The same issue is observed on the cart page, slide-in cart, and dropdown cart.

### WordPress Environment

```
`
### wp-core ###

version: 6.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Users\yoges\Local Sites\astra-dev-test\app\public
wordpress_size: 50.27 MB (52710462 bytes)
uploads_path: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content/uploads
uploads_size: 42.82 MB (44897884 bytes)
themes_path: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content/themes
themes_size: 944.34 MB (990215621 bytes)
plugins_path: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content/plugins
plugins_size: 351.81 MB (368903487 bytes)
database_size: 6.42 MB (6733824 bytes)
total_size: 1.36 GB (1463461278 bytes)

### wp-active-theme ###

name: Astra (astra)
version: 4.1.3
author: Brainstorm Force
author_website: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
parent_theme: none
theme_features: core-block-patterns, astra_hooks, widgets-block-editor, align-wide, automatic-feed-links, title-tag, post-thumbnails, starter-content, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, rank-math-breadcrumbs, amp, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets, menus
theme_path: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content/themes/astra
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty-One: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.1, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (4) ###

Astra Pro: version: 4.1.4, author: Brainstorm Force, Auto-updates disabled
WooCommerce: version: 7.5.1, author: Automattic, Auto-updates disabled
WP Reset: version: 1.97, author: WebFactory Ltd, Auto-updates disabled
WP Rollback: version: 1.7.3, author: GiveWP.com, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: nginx/1.16.0
php_version: 8.1.9 64bit
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.77.0 OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.9
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content
WP_PLUGIN_DIR: C:\Users\yoges\Local Sites\astra-dev-test\app\public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by helgatheviking** [comment]
Isn't the problem more related to the fact that Astra adds the plus/minus buttons dynamically via Javascript? I believe the whole cart widget is re-rendered when the cart contents change and so the DOM will change and Astra may need to listen for a cart reloaded event (if that exists in the side cart?)

**Comment by jmslbam** [comment]
I also encountered this after updating Woocommerce to the latest version, but I'm using GeneratePress with GP Premium.

I will research if the HTML, CSS class or a hooks or so has changed in Woo itself, which results in 3rd parties not being able to run their enhancements.

**Comment by jmslbam** [comment]
I noticed the GPPremium plugin uses `$( document ).ajaxComplete()` method and then checks if there are quantity buttons and runs their code. I'm not seeing any HTML/CSS class adjustments from Woo core that changed the compatiblity with 3rd parties.

I replaced it this:
```
$( document ).ajaxComplete( function() {
		'use strict';

		if ( generateWooCommerce.quantityButtons ) {
			generateQuantityButtons();
		}
} );
```

with the `wc_fragments_refreshed` hook and it worked.

```
$( document.body ).on( 'wc_fragments_refreshed', function() {
        if ( generateWooCommerce.quantityButtons ) {
            generateQuantityButtons();
        }
    });
```


The thing is... it always worked. So was there a change in the code on how the Fragments HTML is being fetched?

**Comment by vedanshujain** [comment]
We did have a change for fetching fragments in 7.5, but it's being reverted in 7.6.1. Can you check if you can reproduce the issue on 7.6.1 please? See the relevant PR which introduced the bug: #36275  and it's revert #37463.

**Comment by jmslbam** [comment]
yupp original code works again 👍

**Comment by vedanshujain** [comment]
Awesome, thanks, going to close the issue now.
