### ISSUE TITLE
limit in attribute selectbox for adding a new variation to variable product in woocommerce

### ISSUE THREAD

**Issue by galaxyboy1988** [woothemes/woocommerce#37649]
We have a shop with few number of product which the main product is a variable product.<br>
The product is a part for vehicles and for any vehicle has a different price. <br>everything is fine and we add 647 variation to it but the problem came after that. new attributes not shown in the selectbox.

Here what we do until now:

1. increase memory_limit from 128 to 1024
2. increase max_input_vars from 1000 to 2000

but none of them resolve the problem
can anyone help me on that, really frostrated.
Best Regards.

**Comment by lsinger** [comment]
Hello @galaxyboy1988,

Thank you for submitting this issue. However, you did not fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we can take a look. Please use [the Bug Report template here](https://github.com/woocommerce/woocommerce/issues/new/choose).
