### ISSUE TITLE
Shipping to Brazil is always $0

### ISSUE THREAD

**Issue by orbian** [woothemes/woocommerce#37648]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've added a shipping zone for Brazil and set the shipping to flat rate $40. However, when someone enters a Brazil address in checkout. It always fails to add the fee. Shipping to some place like Poland, it works as expected.

### Expected behavior

The buyer should see the flat rate shipping fee when they enter their address in Barzil.

### Actual behavior

When a Brazilian address is added. The shipping just says, "flat rate" and no dollar value.

### Steps to reproduce

![byobmo](https://user-images.githubusercontent.com/7276885/231024921-38eba515-6fbf-4e5e-959c-54f8f4a9edc3.JPG)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://byobmo.com
Site address (URL): https://byobmo.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 5.9.5 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 516 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 8.0.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
Total Database Size: 47.67MB
Database Data Size: 45.32MB
Database Index Size: 2.35MB
wp_woocommerce_sessions: Data: 5.17MB + Index: 0.25MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.07MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
wp_commentmeta: Data: 0.14MB + Index: 0.08MB + Engine MyISAM
wp_comments: Data: 29.66MB + Index: 1.11MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lwzk_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lwzk_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lwzk_options: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_posts: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lwzk_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lwzk_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lwzk_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 8.82MB + Index: 0.23MB + Engine MyISAM
wp_postmeta: Data: 0.48MB + Index: 0.16MB + Engine MyISAM
wp_posts: Data: 0.58MB + Index: 0.06MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 180
nav_menu_item: 7
page: 14
post: 11
product: 21
revision: 178
shop_coupon: 1
shop_order: 57
shop_order_refund: 5
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack: by Automattic – 10.8
WooCommerce Payments: by Automattic – 4.0.2 (update to version 5.7.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.5.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.1
Bluehost: by Bluehost – 2.4.0

### Dropin Plugins (1) ###

install.php: install.php

### Must Use Plugins (1) ###

SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #321 - /shop/
Cart: #322 - /cart/
Checkout: #323 - /checkout/
My account: #324 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Ten
Version: 3.1 (update to version 3.8 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://byobmo.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

PayPal Standard: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-11 03:36:10 +00:00
Options: ✔
Notes: 129
Onboarding: completed

### WooCommerce Payments ###

Version: 4.0.2
Connected to WPCOM: Yes
Blog ID: 182027312
Account ID: acct_1JfdLm2ES4To5udh

### Action Scheduler ###

Complete: 121
Oldest: 2023-03-11 08:17:50 +0000
Newest: 2023-04-11 00:22:22 +0000

Failed: 5
Oldest: 2022-04-24 17:49:08 +0000
Newest: 2023-03-22 07:02:33 +0000

Pending: 1
Oldest: 2023-04-11 02:17:52 +0000
Newest: 2023-04-11 02:17:52 +0000

### Status report information ###

Generated at: 2023-04-11 00:31:43 +00:00
`
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @woocommerce/rubik 

I'm afraid I don't see the same thing.

<img width="1308" alt="Screenshot 2023-04-14 at 16 12 41" src="https://user-images.githubusercontent.com/3594411/232169133-bc504109-b376-43c7-97a8-f6af7b154503.png">

With a Flat Rate of $5 for Brazil (in the above screenshot, note that my shipping rules for Brazil come _above_ a set of 'catch-all' rules for customers everywhere else), it is successfully applied in the cart/checkout so long as it is known that the customer's shipping address is indeed in Brazil:

<img width="1054" alt="Screenshot 2023-04-14 at 16 13 14" src="https://user-images.githubusercontent.com/3594411/232169216-2bdcb87a-a4ea-4499-8a93-8fc0187728da.png">

However, I'm not sure how you have set things up locally. Can you share screenshots/details of your shipping rules? Can you confirm the products in question are not virtual, etc?

**Comment by orbian** [comment]
Thanks. I updated by database and made sure Brazil was listed up top. I had deleted it so people wouldn’t start ordering with $0 shipping. I thought is was up top before but one of those two changes fixed. It.

 

Thanks,

Bob

**Comment by barryhughes** [comment]
OK, so everything is fine now? I'll go ahead and close this issue, but if I'm mistaken (or if the problem comes back), just open a fresh issue. Thanks!
