### ISSUE TITLE
Typo in comment on email-styles.php: missing word in sentence about Gmail consistency

### ISSUE THREAD

**Issue by janez33** [woothemes/woocommerce#37658]
https://github.com/woocommerce/woocommerce/blob/50593c5257d4e7036280201d01cdf73469927706/plugins/woocommerce/templates/emails/email-styles.php#L237

**Comment by lsinger** [comment]
@janez33 the full sentence is:

>  Media queries are not supported by all email clients, however they do work on modern mobile Gmail clients and can help us achieve better consistency there.

Looking at the full sentence I don't think there's a typo. Would you agree?

**Comment by janez33** [comment]
I'm so sorry, I must have been looking at some different version before commit or so or I made an error in my file. Yes, everything is fine in that sentence. I'm closing it.
