### ISSUE TITLE
Invert the useValidation hook behavior to return an error instead of a boolean value.

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#37663]
### Description

The useValidation hook returns a boolean value currently. In order to better manage validation errors the hook should return the error when the validator fails.

Current

```typescript
const isValid = useValidation('product/name', function validator() {
  return Boolean(name);
});
```

Change request

```typescript
const validationError = useValidation('product/name', function validator() {
  if (!name) {
    return __('Required', 'woocommerce');
  }
  if (name.length < 3) {
    return __('Must be longer than 3 characters', 'woocommerce');
  }
  if (name.length > 10) {
    return __('Must be less than 10 characters long', 'woocommerce');
  }
});
```

**Comment by mdperez86** [comment]
@joshuatf @joelclimbsthings @louwie17 👆👆👆

**Comment by louwie17** [comment]
@mdperez86 that looks good to me. Although I do wonder if there would ever be a case where we did have a validation error with the actual field still being valid ( aka: it can be saved with invalid validation )? But maybe that is overthinking it a bit to much.
At the moment this seems relatively straightforward and we did probably want to keep it that way.

One suggestion though as I am looking at this, do you think it would be worth adding a dependency array ( similar to `useEffect` or `useSelect`, and have it work in a similar manner? ). We did have to wrap the `validate` function into a `useCallback` with those additional `deps`.

**Comment by mdperez86** [comment]
> One suggestion though as I am looking at this, do you think it would be worth adding a dependency array ( similar to useEffect or useSelect, and have it work in a similar manner? ). 

Since validations in this case are very light in term of computation I don't think we really need to cache the validator function.

But in case we really need it we can do 

```typescript
const heavyAsyncValidator = useCallback(async function validator() {
  ...
}, deps);

const validationError = useValidation('product/name', heavyAsyncValidator);
```

> We did have to wrap the validate function into a useCallback with those additional deps.

Yes, the idea is that we only use the cache when it is really needed and not for every validator.

**Comment by louwie17** [comment]
> Since validations in this case are very light in term of computation I don't think we really need to cache the validator function.

True, lets stick with the light version for now. If it does start to become a noticeable performance bottleneck we can always introduce the `dependency` array at a later time.
