### ISSUE TITLE
Firewall block payments gateway messages

### ISSUE THREAD

**Issue by alanrgon** [woothemes/woocommerce#37664]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I use the Mercado Pago Brasil payment gateway and their support reported that there is a failure in the communication between the platforms.

support
I captured the transaction notification response 56775553814 for you to pass on to those responsible for managing the servers your store is hosted on:

{"message":"ErrorBFNotificationRequest 9000 Bifrost_Notification error: unable to make request to Bifrost Notification","error":"418 i'm_a_teapot:

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
","status":502,"cause":[{"StatusCode":418,"Message":"

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
"}]}

It's happening too often in your transactions.

In all cases that the status code 500 or 502 is issued, there is always some barrier that the server that receives the message puts up.

### Expected behavior

I use the Mercado Pago Brasil payment gateway and their support reported that there is a failure in the communication between the platforms.

support
I captured the transaction notification response 56775553814 for you to pass on to those responsible for managing the servers your store is hosted on:

{"message":"ErrorBFNotificationRequest 9000 Bifrost_Notification error: unable to make request to Bifrost Notification","error":"418 i'm_a_teapot:

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
","status":502,"cause":[{"StatusCode":418,"Message":"

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
"}]}

It's happening too often in your transactions.

In all cases that the status code 500 or 502 is issued, there is always some barrier that the server that receives the message puts up.

### Actual behavior

I use the Mercado Pago Brasil payment gateway and their support reported that there is a failure in the communication between the platforms.

support
I captured the transaction notification response 56775553814 for you to pass on to those responsible for managing the servers your store is hosted on:

{"message":"ErrorBFNotificationRequest 9000 Bifrost_Notification error: unable to make request to Bifrost Notification","error":"418 i'm_a_teapot:

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
","status":502,"cause":[{"StatusCode":418,"Message":"

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
"}]}

It's happening too often in your transactions.

In all cases that the status code 500 or 502 is issued, there is always some barrier that the server that receives the message puts up.

### Steps to reproduce

4

### WordPress Environment

I use the Mercado Pago Brasil payment gateway and their support reported that there is a failure in the communication between the platforms.

support
I captured the transaction notification response 56775553814 for you to pass on to those responsible for managing the servers your store is hosted on:

{"message":"ErrorBFNotificationRequest 9000 Bifrost_Notification error: unable to make request to Bifrost Notification","error":"418 i'm_a_teapot:

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
","status":502,"cause":[{"StatusCode":418,"Message":"

{\"time\":\"2023-04-10T22:32:53.97222716\",\"message\":\"418 I_AM_A_TEAPOT \\\"Error on making POST request: Network is unreachable\\\"; nested exception is java.net.SocketException: Network is unreachable\",\"status\":\"I_AM_A_TEAPOT\"}
"}]}

It's happening too often in your transactions.

In all cases that the status code 500 or 502 is issued, there is always some barrier that the server that receives the message puts up.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @alanrgon,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are reporting seems to be caused by (possibly) network issues between your host and your payment gateway. Please reach out to those parties and / or the developer of the payment gateway extension.
