### ISSUE TITLE
Add support for pnpm 8

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#37679]
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

When [pnpm 8.0.0 was released](https://github.com/pnpm/pnpm/releases/tag/v8.0.0), [Actions broke](https://github.com/woocommerce/woocommerce/actions/runs/4543476368/jobs/8008209538?pr=37446) and local development also stopped working when simply installing pnpm via `npm i pnpm --global`. 

We fixed the Actions by hard-coding `pnpm@7`, but [the local development README](https://github.com/woocommerce/woocommerce/blob/trunk/README.md#getting-started) still doesn't mention this issue. 

Pinning `pnpm` to version 7 forever isn't a viable long-term strategy anyhow, so let's ensure the monorepo works with `pnpm` 8.

**Comment by samueljseay** [comment]
Duplicate of #37915
