### ISSUE TITLE
Remove legacy coupon display not disappearing. 

### ISSUE THREAD

**Issue by TamaraJoniec** [woothemes/woocommerce#37677]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The remove legacy coupon display is not disappearing and it's not letting me move on to personalise my store theme. Also my navbar is not appearing when the page loads.

### Expected behavior

That the nav bar appears and that I am allowed to personalise the store front, and change fonts.

### Actual behavior

I do not have any controls to edit the fonts or personalise my store

### Steps to reproduce

Go to SHOP

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.designrise.co.uk
Site address (URL): https://www.designrise.co.uk
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 150
PHP Max Input Vars: 1000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.5.19-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wppz_
Total Database Size: 102.38MB
Database Data Size: 95.45MB
Database Index Size: 6.93MB
wppz_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wppz_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_actionscheduler_actions: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wppz_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_actionscheduler_logs: Data: 0.39MB + Index: 0.30MB + Engine InnoDB
wppz_awb_critical_css: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppz_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wppz_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_newsletters: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wppz_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wppz_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_options: Data: 7.50MB + Index: 0.14MB + Engine InnoDB
wppz_postmeta: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wppz_posts: Data: 23.47MB + Index: 0.23MB + Engine InnoDB
wppz_pts_tables: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wppz_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wppz_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wppz_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wppz_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wppz_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wppz_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wppz_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppz_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_wfconfig: Data: 1.45MB + Index: 0.00MB + Engine InnoDB
wppz_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wffilemods: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
wppz_wfhits: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wppz_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wppz_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wppz_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppz_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_wfstatus: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wppz_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppz_yoast_indexable: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wppz_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppz_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppz_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppz_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpstg0_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpstg0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_awb_critical_css: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg0_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_options: Data: 3.28MB + Index: 0.03MB + Engine InnoDB
wpstg0_postmeta: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wpstg0_posts: Data: 19.52MB + Index: 0.22MB + Engine InnoDB
wpstg0_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wffilemods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wpstg0_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wpstg0_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wfstatus: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpstg0_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_yoast_indexable: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpstg0_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 68
avada_faq: 1
avada_portfolio: 6
awb_off_canvas: 2
customize_changeset: 4
custom_css: 1
fusion_element: 7
fusion_form: 5
fusion_icons: 2
fusion_tb_layout: 3
fusion_tb_section: 7
fusion_template: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mailpoet_page: 1
nav_menu_item: 19
page: 19
polylang_mo: 4
post: 10
product: 13
revision: 776
slide: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (15) ###

Deposits & Partial Payments for WooCommerce: by Acowebs – 1.1.9
Avada Builder: by ThemeFusion – 3.10.0
Avada Core: by ThemeFusion – 5.10.0
Google Listings and Ads: by WooCommerce – 2.4.2
Site Kit by Google: by Google – 1.98.0
Jetpack: by Automattic – 12.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.3

WooCommerce Payments: by Automattic – 5.7.0
WooCommerce Product Add-ons: by WooCommerce – 6.2.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Subscriptions: by WooCommerce – 5.0.1
WooCommerce: by Automattic – 7.5.1
Wordfence Security: by Wordfence – 7.9.2
Yoast SEO: by Team Yoast – 20.5
WP Mail SMTP: by WPForms – 3.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #2061 - /shop/
Basket: #2062 - /basket/
Checkout: #2063 - /checkout/
My account: #2064 - /my-account/
Terms and conditions: #1657 - /terms-and-conditions/

### Theme ###

Name: Avada
Version: 7.10.0
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.designrise.co.uk
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-12 18:06:22 +00:00
Options: ✔
Notes: 43
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Yes
Blog ID: 217553893
Account ID: acct_1Mtz88CGUxcVlgpg

### Action Scheduler ###

Complete: 567
Oldest: 2023-03-31 14:03:38 +0000
Newest: 2023-04-12 12:34:16 +0000

Failed: 951
Oldest: 2023-04-07 11:27:08 +0000
Newest: 2023-04-12 12:41:15 +0000

Pending: 8
Oldest: 2023-04-12 12:43:15 +0000
Newest: 2023-04-17 14:12:23 +0000

### Status report information ###

Generated at: 2023-04-12 12:41:15 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for reporting this, @TamaraJoniec.  However, on first try, I seem unable to reproduce ... but it's possible I'm not understanding where the problem lies:

- Can you confirm exactly which admin screen I need to visit to see this?
- There are a few different controls that could be described as nav bars: which do you mean—can you provide a screenshot?
- Last but not least, can you try [troubleshooting the problem](https://woocommerce.com/document/how-to-test-for-conflicts/)? Flagging this as your description immediately makes me think a Javascript error may be happening as the result of a conflict, and it seems you did not test with a default theme:

<div align="center"><img width="800" alt="testing-isolation-steps" src="https://user-images.githubusercontent.com/3594411/234609050-c409a887-0185-4035-beee-41353386abe7.png"></div>

**Comment by rrennick** [comment]
Closing due to lack of feedback.
