### ISSUE TITLE
Yoast SEO Analysis widget cannot read ACF fields on product category pages

### ISSUE THREAD

**Issue by cw-bravotransfers** [woothemes/woocommerce#37673]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Yoast SEO Analysis widget cannot read ACF fields on product category pages.

### Expected behavior

Yoast SEO Analysis widget can read ACF fields on regular posts and pages, but not product category pages.

### Actual behavior

Yoast SEO Analysis widget says "Text length: the text contains 0 words. This is far below the recommended minimum of 250 words. Add more content." despite content in ACF fields on product category pages.

### Steps to reproduce

This seems to be a general problem on product category pages, i.e. it never works.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.bravotransfers.com
Site address (URL): https://www.bravotransfers.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: fc_wp_
Total Database Size: 418.14MB
Database Data Size: 204.08MB
Database Index Size: 214.06MB
fc_wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
fc_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_woocommerce_order_itemmeta: Data: 2.02MB + Index: 1.06MB + Engine InnoDB
fc_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_actionscheduler_actions: Data: 1.02MB + Index: 8.17MB + Engine InnoDB
fc_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_actionscheduler_logs: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
fc_wp_automatewoo_abandoned_carts: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
fc_wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fc_wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_automatewoo_logs: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
fc_wp_automatewoo_log_meta: Data: 0.41MB + Index: 0.30MB + Engine InnoDB
fc_wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
fc_wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_followup_customer_carts: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fc_wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
fc_wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
fc_wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
fc_wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_options: Data: 5.23MB + Index: 1.13MB + Engine InnoDB
fc_wp_postmeta: Data: 44.58MB + Index: 30.50MB + Engine InnoDB
fc_wp_posts: Data: 10.52MB + Index: 2.78MB + Engine InnoDB
fc_wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_termmeta: Data: 7.52MB + Index: 11.06MB + Engine InnoDB
fc_wp_terms: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
fc_wp_term_relationships: Data: 3.19MB + Index: 3.09MB + Engine InnoDB
fc_wp_term_taxonomy: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
fc_wp_usermeta: Data: 0.31MB + Index: 0.19MB + Engine InnoDB
fc_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_vxcf_zoho: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_vxcf_zoho_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_vxcf_zoho_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
fc_wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
fc_wp_wc_category_lookup: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
fc_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fc_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fc_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_wc_product_attributes_lookup: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
fc_wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fc_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fc_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_woocommerce_bundled_itemmeta: Data: 109.66MB + Index: 138.36MB + Engine InnoDB
fc_wp_woocommerce_bundled_items: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
fc_wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fc_wp_wpr_rucss_used_css: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
fc_wp_yoast_indexable: Data: 5.20MB + Index: 4.00MB + Engine InnoDB
fc_wp_yoast_indexable_hierarchy: Data: 1.11MB + Index: 0.48MB + Engine InnoDB
fc_wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fc_wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fc_wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
fc_wp_zcwc_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 601
acf-field-group: 49
addify_acr_carts: 16
addify_acr_emails: 1
addify_acr_logs: 29
attachment: 1368
aw_workflow: 6
cookielawinfo: 39
elementor_library: 1
faqs: 118
follow_up_email: 2
global_product_addon: 1
igmap: 89
mapsvg: 177
nav_menu_item: 40
oembed_cache: 1
page: 32
polylang_mo: 3
post: 5
product: 7352
revision: 12
shop_coupon: 4
shop_order: 36
shop_order_refund: 34
tablepress_table: 1
zoho_flow_api_keys: 1
zoho_flow_webhooks: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Polylang Pro: by WP SYNTEX – 3.3.2
TablePress: by Tobias Bäthge – 2.1
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.0.1

Advanced Custom Fields PRO: by WP Engine – 6.0.7
AutomateWoo: by WooCommerce – 5.6.10
Classic Editor: by WordPress Contributors – 1.6.2
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.8
Delete Me: by Clinton Caldwell – 3.0
Elementor: by Elementor.com – 3.12.1
Enable Media Replace: by ShortPixel – 4.0.3
Google Listings and Ads: by WooCommerce – 2.4.1
Interactive Geo Maps PRO: by Carlos Moreira – 1.5.11
Loco Translate: by Tim Whitlock – 2.6.4
Nextend Social Login: by Nextendweb – 3.1.7
Nextend Social Login Pro Addon: by Nextendweb – 3.1.7
Polylang for WooCommerce: by WP SYNTEX – 1.7.2
Social Media Widget: by Martin Jordan – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Sassy Social Share: by Team Heateor – 3.3.49
Setup CPT: by Martin Jordan – 1.0.1
Transients Manager: by WPBeginner – 2.0.3
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.6.2
WooCommerce Multi-currency: by TIV.NET INC – 3.2.3 (update to version 3.3.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.18.3 (update to version 6.18.4 is available)
WooCommerce Smart Coupons: by StoreApps – 7.4.0 (update to version 7.5.0 is available)
WooCommerce Smart Refunder: by StoreApps – 1.8.0
WooCommerce: by Automattic – 7.5.1
Yoast SEO: by Team Yoast – 20.3
WP Headers And Footers: by WPBrigade – 2.0.1
Zoho Mail: by Zoho Mail – 1.4.9

### Inactive Plugins (8) ###

Email Log: by Sudar – 2.4.8
Facebook for WooCommerce: by Facebook – 3.0.16
Google One Tap Sign In: by TransferSystems – 1.0
Pixel Manager for WooCommerce: by SweetCode – 1.30.3
Query Monitor: by John Blackbourn – 3.12.0
Trustpilot-reviews: by Trustpilot – 2.5.914
WP Rocket: by WP Media – 3.11.3
Zoho Campaigns: by Zoho Campaigns – 2.0.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.2
WP Engine Seamless Login Plugin: by WP Engine – 1.6.0
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (EUR)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #31 - /
Basket: #36 - /cart/
Checkout: #37 - /checkout/
My account: #38 - /my-account/
Terms and conditions: #329 - /terms-conditions/

### Theme ###

Name: Bravo Transfers
Version: 1.0.0
Author URL: https://bravotransfers.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: fc-shop/woocommerce/archive-product.php
fc-shop/woocommerce/cart/cart-totals.php
fc-shop/woocommerce/cart/cart.php version 7.0.1 is out of date. The core version is 7.4.0
fc-shop/woocommerce/cart/mini-cart.php
fc-shop/woocommerce/checkout/form-billing.php
fc-shop/woocommerce/checkout/form-checkout.php
fc-shop/woocommerce/checkout/form-pay.php
fc-shop/woocommerce/checkout/thankyou.php
fc-shop/woocommerce/content-product.php
fc-shop/woocommerce/content-single-product.php
fc-shop/woocommerce/emails/customer-completed-order.php
fc-shop/woocommerce/emails/customer-new-account.php
fc-shop/woocommerce/emails/customer-reset-password.php
fc-shop/woocommerce/global/breadcrumb.php
fc-shop/woocommerce/global/form-login.php
fc-shop/woocommerce/global/sidebar.php
fc-shop/woocommerce/loop/add-to-cart.php
fc-shop/woocommerce/loop/loop-end.php
fc-shop/woocommerce/loop/loop-start.php
fc-shop/woocommerce/loop/pagination.php
fc-shop/woocommerce/loop/price.php
fc-shop/woocommerce/myaccount/dashboard.php
fc-shop/woocommerce/myaccount/form-add-payment-method.php
fc-shop/woocommerce/myaccount/form-edit-account.php
fc-shop/woocommerce/myaccount/form-edit-address.php
fc-shop/woocommerce/myaccount/form-login.php
fc-shop/woocommerce/myaccount/form-lost-password.php
fc-shop/woocommerce/myaccount/form-reset-password.php
fc-shop/woocommerce/myaccount/my-address.php
fc-shop/woocommerce/myaccount/navigation.php
fc-shop/woocommerce/myaccount/orders.php
fc-shop/woocommerce/myaccount/payment-methods.php
fc-shop/woocommerce/myaccount/view-order.php
fc-shop/woocommerce/notices/error.php
fc-shop/woocommerce/notices/notice.php
fc-shop/woocommerce/order/order-details-customer.php
fc-shop/woocommerce/order/order-details-item.php
fc-shop/woocommerce/order/order-details.php
fc-shop/woocommerce/product-searchform.php
fc-shop/woocommerce/single-product/related.php
fc-shop/woocommerce/single-product.php
fc-shop/woocommerce/taxonomy-product_cat.php
fc-shop/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update

### WC Pages Translations ###

Shop base: ✔
Cart: ✔
Checkout: ✔
My account: ✔

### Product Bundles ###

Database Version: 6.18.3
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-12 07:42:58 +02:00
Options: ✔
Notes: 127
Onboarding: completed

### Multicurrency ###

admin_email: support@bravotransfers.com
allow_price_per_product: no
client_side_cookies: no
cookie_woocommerce_multicurrency_forced_currency: EUR
currency_en: -
currency_es: -
currency_pt: -
currency_symbol_EUR: EUR
currency_symbol_GBP: GBP
currency_symbol_USD: USD
customer_location_method: 
enabled_currencies: a:3:{i:0;s:3:"EUR";i:1;s:3:"GBP";i:2;s:3:"USD";}
fallback_currency: EUR
fee_percent: 1
log_level: error
maxmind_license_set: no
price_charm: -
price_format_EUR: %2$s %1$s
price_format_GBP: %2$s %1$s
price_format_USD: %2$s %1$s
rates: a:169:{s:3:"AED";d:3.672365;s:3:"AFN";d:86.344444;s:3:"ALL";d:103.380684;s:3:"AMD";d:391.284;s:3:"AN...
rates_count: array(169)
rates_provider_id: OpenExchangeRates
rates_retrieval_status: 1
rates_timestamp: 1681218000
rates_update_schedule: daily
reporter_email: chris@transfersystems.com
reporter_name: admin-chris
round_to: 0.01
selector_widgets: 
store_country_state: ES:B
switcher_conditions: yes
update_error: a:2:{s:7:"message";s:0:"";s:9:"timestamp";i:1681218009;}
version: 3.2.3
woocommerce_prices_include_tax: no
woocommerce_tax_display_cart: excl
woocommerce_tax_display_shop: excl

### Action Scheduler ###

Complete: 953
Oldest: 2023-03-13 05:37:33 +0100
Newest: 2023-04-12 06:03:15 +0200

Failed: 58
Oldest: 2023-03-24 12:54:36 +0100
Newest: 2023-04-12 00:17:01 +0200

Pending: 5
Oldest: 2023-04-12 14:40:55 +0200
Newest: 2023-04-13 00:17:01 +0200

### Smart Coupons related settings ###

Number of coupons to show: 1
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: no
Printing coupons: no
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: no
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: no
Combined auto generated coupons email: no
Acknowledgement email: no
Enable taxes: no
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2023-04-12 07:58:24 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @cw-bravotransfers,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin Yoast SEO. 

Please contact the author of the plugin directly for further help.

**Comment by cw-bravotransfers** [comment]
Hi Leif,

Yoast said it was down to you guys (since Yoast works ok on regular posts
and pages). You say it's down to them.
Seems it'll never get fixed :(

Can you perhaps shed some light on why you think it's down to them to fix.
Then I can pass the message on to Yoast and hopefully they'll take a look.

FYI, your support team directed me to github.

Kind regards,
Chris Woodward

*BRAVO* <https://www.bravotransfers.com> *|* TransferSystems
Mobile: +34 622227717
***@***.***
LinkedIn

<https://es.linkedin.com/in/christopherjohnwoodward>

**Comment by lsinger** [comment]
Hello @cw-bravotransfers,

This seems to be an issue with Yoast, ACF, and WooCommerce not playing together perfectly. For us to understand why the issue would lie with WooCommerce, could you supply us some more background and very, very detailed reproduction steps, ideally in a new issue?
