### ISSUE TITLE
Local pickup page: add Tracks event

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#37699]
**Description:** we should add a Tracks event to the local pickup page to have a better understanding of how many users enabled or disabled this feature alongside the options picked by them. The page view is already covered by `wcadmin_settings_view`

Event name:
`wcadmin_local_pickup_save_changes`
The event should be fired when the user clicks "Save changes"

Event properties:
`local_pickup_enabled`: True|False (identify if the user enabled or disabled the option)
`title`: [string] (check if the title was changed by the user)
`price`: True|False (identify if the user enabled or disabled the option)
`cost`: [value] (track the cost added by the user)
`taxes`: Taxable | Non Taxable (identify the option picked by the user)
`total_pickup_locations`: [count] (number of pickup locations created by the user)
`pickup_locations_enabled`: [count] (number of pickup locations enabled by the user)

**Deadline:** we should target the WooCommerce 7.8 release.

**Comment by pmcpinto** [comment]
This will be handled by Team Rubik

**Comment by ralucaStan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sigma-Team-605211b24a30720013d5f43f/issues/woocommerce/woocommerce/37699?planning-poker) with Zenhub @senadir

**Comment by senadir** [comment]
@pmcpinto the code for this view lives in Woo Blocks, any reason this issue is here and not in our repo? I assume the tracking code will also live in our repo along side the view code.

**Comment by pmcpinto** [comment]
Oh sorry. Because it's an admin page I incorrectly assumed that it had been implemented directly in Core.

**Comment by ralucaStan** [comment]
closed via https://github.com/woocommerce/woocommerce-blocks/pull/10841
