### ISSUE TITLE
Local pickup page: add link to documentation

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#37702]
**Description:** currently, we don't offer easy access to the Local Pickup documentation from its page. We should fix this, as some users will want to learn more about the local pickup advantages, how it will behave in the front end, etc before enabling it.  

**Acceptance criteria:**
- [ ] Add a "Learn more" link in the "General" section that redirects the user to the [Local Pickup documentation](https://woocommerce.com/document/woocommerce-blocks-local-pickup/).

<img width="1275" alt="Captura de ecrã 2023-04-13, às 09 37 37" src="https://user-images.githubusercontent.com/3380168/231703873-c2b3cdcf-8765-4151-9040-7e3de0aeda67.png">

**Deadline:** we should target the WooCommerce 7.8 release.

**Comment by pmcpinto** [comment]
This will be handled by Rubik

**Comment by senadir** [comment]
This seems to have been solved.
