### ISSUE TITLE
Product Block Editor: Update current block names to reflect use case and avoid conflicts

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37704]
**Description**

We should better describe our product block editor block names to avoid conflicts with the blocks generated for FSE by WooCommerce Blocks.

As suggested by Darren here: p1679919055772809-slack-C01CMSA1VHS we should tag on `-field` ( ex: `woocommerce/product-summary` -> `woocommerce/product-summary-field` ) for most of these block names, as this is a more accurate representation of the block.
This issue covers updating the block names of all the blocks that we have currently written, that require this specification:
- Product name block
- Product summary block
- Product pricing block
- Product radio block
- Product images block
- Product section block
- Product tab block
- Product collapsible block

**Acceptance criteria**

- [ ] Block names mentioned in the above list should contain `-field` within the block name.
- [ ] Product template should be updated and still render correctly with the updated names.
- [ ] Move all created blocks to the `/blocks` folder.

**Comment by louwie17** [comment]
@nerrad we would appreciate some of you feedback around this issue, after we discussed it as a team:

Some of the team were not overly keen on making use of the `-field` postfix either, as the current use case is still very much focused towards the product block editor, and couldn't think of a specific reason on how these field blocks would be rendered on the front end (cc @joshuatf if I stated that correctly ).

Some additional suggestions were made on either adding an additional separator like `products`, so we would get `woocommerce/products/description` (although this may still expose the same conflict issues ). Another additional thought was to register our fields under the `woocommerce-admin` namespace, so it would become `woocommerce-admin/product-description`.

The more I ( @louwie17 ) think about it, the `-field` does still seem to be the best approach as we are rendering fields, and that we may want to re-consider once we have successfully create a block that works in all the contexts ( product editor and FSE ) and if in those circumstances we did still render fields or not.

**Comment by nerrad** [comment]
> Some of the team were not overly keen on making use of the -field postfix either, as the current use case is still very much focused towards the product block editor, and couldn't think of a specific reason on how these field blocks would be rendered on the front end (cc @joshuatf if I stated that correctly ).

It's less about where the blocks are rendered, and more about their function. The blocks render fields so having a name that describes that makes it easier to derive in things like usage tracking, pattern creation, human readable block syntax etc.

**Comment by louwie17** [comment]
In that case, I would say we should go ahead with the original intent of this issue and stick with `-field` where it seems appropriate.
