### ISSUE TITLE
WooCommerce Crashes Ver 6.2 Wordpress site with Storefront Theme

### ISSUE THREAD

**Issue by KeRFR** [woothemes/woocommerce#37709]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I Activate WooCommerce Plugin the entire site crashes.
I've tried with StoreFront theme as well as Evit - same happens with both.
I completely deleted and set up a totally new WP site and removed all plugins - that did not solve the problem

### Expected behavior

I expected WooCommerce to activate

### Actual behavior

Entire site crashes
Email with troubleshooting details does not arrive
Here's a video:
https://screencast-o-matic.com/watch/c0fI6vVaM2W

### Steps to reproduce

See video:
https://screencast-o-matic.com/watch/c0fI6vVaM2W

### WordPress Environment

The entire site crashes - so I cannot access anything - including that report.
Wordpress 6.2
Brand new installation.
Hosting is updated daily as required but may need some settings adjusted.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by KeRFR** [comment]
Wordpress 6.2 site

**Comment by KeRFR** [comment]
Hi,

 

MANY thanks.

 

However, I’ve managed to solve the problem – it was a memory issue on my host server.

 

Tanks all the same!

 

Kind regards,

 

Kerry

***@***.***

**Comment by adrianduffell** [comment]
Hi @KeRFR , thanks for reporting the issue and glad you were able to resolve it with your host! 

I'll close the issue out now.
