### ISSUE TITLE
Product Block Editor: add validation to the sale price field

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37707]
**Description**

This is dependant on: https://github.com/woocommerce/woocommerce/issues/37663
We should add validation to the product sale price field. 

Validation (see old implementation as well, but here is the gist):
- Sale price can't be equal to or more then the list price: `Sale price cannot be equal to or higher than list price.`

**Acceptance criteria**

- [ ] When sale price is equal to or more then the list price, the `Sale price cannot be equal to or higher than list price.` warning should show under the name field and the save buttons disabled.

**Comment by mdperez86** [comment]
This was covered [here](https://github.com/woocommerce/woocommerce/pull/37695/files#diff-5745b703ee2a7f2bda904937b65e533b9d6bebcc83095f0934e78353529fa1faR99)
