### ISSUE TITLE
edit_form_top action not firing when HPOS/COT function is enabled

### ISSUE THREAD

**Issue by lincetto** [woothemes/woocommerce#37715]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Action `edit_form_top` is not firing when entering in order edit page if COT is enabled 

### Expected behavior

Action is firing regardless the COT function enabled status

### Actual behavior

Action is not firing

### Steps to reproduce

Register an action like this

```
add_action( 'edit_form_top', function( $post ) {
    echo __( 'hello world' );
}, 10, 1 );
```

'hello world' is printed when COT is disabled, not printed when COT is enabled

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.xxx.it
Site address (URL): https://www.xxx.it
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 100 MB
PHP Time Limit: 1800
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.7.41-44-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Dimensione totale database: 86.95MB
Dimensione dati database: 69.38MB
Dimensione indice database: 17.57MB
wp_woocommerce_sessions: Dati: 0.30MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 1.02MB + indice: 0.11MB + motore InnoDB
wp_actionscheduler_claims: Dati: 5.52MB + indice: 3.52MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wp_addonlibrary_addons: Dati: 2.52MB + indice: 0.00MB + motore InnoDB
wp_addonlibrary_categories: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_cart_abandonment: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_cartflows_ca_email_history: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_email_templates_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 0.48MB + indice: 0.53MB + motore InnoDB
wp_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_e_notes: Dati: 0.02MB + indice: 0.17MB + motore InnoDB
wp_e_notes_users_relations: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_e_submissions: Dati: 0.02MB + indice: 0.27MB + motore InnoDB
wp_e_submissions_actions_log: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_e_submissions_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_ff_scheduled_actions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_entry_details: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_form_analytics: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_form_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_logs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_submissions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_fluentform_submission_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_giveasap_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_giveasap_entries: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_giveasap_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_myCRED_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_options: Dati: 3.45MB + indice: 0.19MB + motore InnoDB
wp_pmxi_files: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_hash: Dati: 2.52MB + indice: 0.00MB + motore InnoDB
wp_pmxi_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_images: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_pmxi_imports: Dati: 0.13MB + indice: 0.00MB + motore InnoDB
wp_pmxi_posts: Dati: 2.52MB + indice: 0.00MB + motore InnoDB
wp_pmxi_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_postmeta: Dati: 30.55MB + indice: 9.03MB + motore InnoDB
wp_posts: Dati: 5.52MB + indice: 0.52MB + motore InnoDB
wp_rafflepress_contestants: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_rafflepress_entries: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_rafflepress_giveaways: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_rafflepress_polls: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_redirection_404: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_redirection_groups: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_redirection_items: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_redirection_logs: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_revslider_css: Dati: 0.13MB + indice: 0.02MB + motore InnoDB
wp_revslider_css_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_revslider_layer_animations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_revslider_layer_animations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_revslider_navigations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_revslider_navigations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_revslider_sliders: Dati: 1.52MB + indice: 0.02MB + motore InnoDB
wp_revslider_sliders_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_revslider_slides: Dati: 5.52MB + indice: 0.02MB + motore InnoDB
wp_revslider_slides_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_revslider_static_slides: Dati: 1.52MB + indice: 0.02MB + motore InnoDB
wp_revslider_static_slides_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_smush_dir_images: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_term_relationships: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_usermeta: Dati: 0.09MB + indice: 0.03MB + motore InnoDB
wp_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_vi_woo_orders_tracking_track_info: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wcpdf_invoice_number: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 0.13MB + indice: 0.13MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wfblockediplog: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfblocks7: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfconfig: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wp_wfcrawlers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wffilechanges: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wffilemods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfhits: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfhoover: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wfissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wfknownfilelist: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wflivetraffichuman: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wflocs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wflogins: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wfls_2fa_secrets: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wfls_role_counts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfls_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfnotifications: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfpendingissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wfreversecache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfsnipcache: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfstatus: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wftrafficrates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfwafconfig: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wp_wof_optins: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wotv_woo_track_info: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpforms_tasks_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpf_filters: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpf_meta_keys: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wpf_meta_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wpf_meta_values_bk: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wpmailsmtp_debug_events: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpmailsmtp_emails_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wpmailsmtp_email_tracking_events: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wpmailsmtp_email_tracking_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wpmailsmtp_tasks_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpr_rocket_cache: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wpr_rucss_used_css: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wp_wt_iew_action_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wt_iew_mapping_template: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wt_sc_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_yith_wcwl: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yith_wcwl_lists: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_yith_ywpar_points_log: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_yoast_indexable: Dati: 0.06MB + indice: 0.09MB + motore InnoDB
wp_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_yoast_prominent_words: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_yoast_seo_links: Dati: 0.06MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

attachment: 1786
custom_css: 1
customize_changeset: 5
e-landing-page: 1
elementor_font: 1
elementor_library: 186
fortunewheel-stats: 2
giveasap: 2
groovy_menu_preset: 1
mb_woc_wheel: 2
mycred_fortunewheels: 1
mycred_rank: 1
nav_menu_item: 57
oembed_cache: 16
page: 74
plus-mega-menu: 10
post: 20
product: 12
product_variation: 6
qsm_quiz: 6
revision: 147
shop_coupon: 289
shop_order: 4
shop_order_refund: 55
shopengine-template: 5
wcapf-filter: 1
wp_global_styles: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Better Search Replace: by WP Engine – 1.4.2
Classic Editor: by Contributori WordPress – 1.6.3
EAN for WooCommerce: by WPFactory – 4.4.5
Elementor Pro: by Elementor.com – 3.10.3
Elementor: by Elementor.com – 3.12.1
Essential Addons for Elementor - Pro: by WPDeveloper – 5.3.1
Essential Addons for Elementor: by WPDeveloper – 5.7.0
JetProductGallery: by Crocoblock – 2.1.11
Stock Synchronization for WooCommerce: by Andrea Lincetto – 4.0.0
Redirection: by John Godley – 5.3.10
Slider Revolution Before/After Add-On: by ThemePunch – 3.1.0
Slider Revolution Bubblemorph AddOn: by ThemePunch – 3.0.7
Slider Revolution Lottie AddOn: by ThemePunch – 3.0.8
Slider Revolution Mousetrap Add-On: by ThemePunch – 3.0.8
Slider Revolution Paint-Brush Add-On: by ThemePunch – 3.0.4
Slider Revolution Particles Effect: by ThemePunch – 3.3.2
Slider Revolution Particle Wave Add-On: by ThemePunch – 1.1.0
Slider Revolution Scroll Video Add-On: by ThemePunch – 3.0.4
Slider Revolution Holiday Snow: by ThemePunch – 3.0.5
Slider Revolution The Cluster AddOn: by ThemePunch – 1.0.7
Slider Revolution Transitionpack Add-On: by ThemePunch – 1.0.6
Slider Revolution: by ThemePunch – 6.6.12
Templately: by Templately – 2.1.0
The Plus Addons for Elementor: by POSIMYTH – 5.2.0
The Plus Addons for Elementor - Pro: by POSIMYTH – 5.1.2
Timeline Widget For Elementor: by Cool Plugins – 1.4.3
Unlimited Elements for Elementor (Premium): by Unlimited Elements – 1.5.38
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.5
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.2
Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.3.16
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.19
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Conversion Tracking: by weDevs – 2.0.10
WooCommerce: by Automattic – 7.5.1 (aggiornamento alla versione 7.6.0 disponibile)
Wordfence Security: by Wordfence – 7.9.2
Yoast SEO: by Team Yoast – 20.5
WP Crontrol: by John Blackbourn e collaboratori – 1.15.2
WPC AJAX Add to Cart for WooCommerce: by WPClever – 1.5.7

### Inactive Plugins (1) ###

Geo Redirect: by Geo Targetly – 5.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.2
WP Engine Seamless Login Plugin: by WP Engine – 1.6.0
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #16 - /shop/
Carrello: ❌ La pagina non contiene lo shortcode [woocommerce_cart] o il blocco woocommerce/cart.
Pagamento: ❌ La pagina non contiene lo shortcode [woocommerce_checkout] o il blocco woocommerce/checkout.
Il mio account: #19 - /my-account/
Termini e condizioni: #95 - /terms-of-service/

### Theme ###

Name: Aiper
Version: 1.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.7.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: /nas/content/live/aiper/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/nas/content/live/aiper/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-14 06:31:47 +02:00
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Completato: 157
Oldest: 2023-03-14 02:45:32 +0100
Newest: 2023-04-13 19:08:58 +0200

Operazione non riuscita: 18
Oldest: 2023-03-15 03:24:08 +0100
Newest: 2023-04-11 12:35:45 +0200

In attesa: 3
Oldest: 2023-04-14 12:37:07 +0200
Newest: 2023-04-18 12:35:45 +0200

### Status report information ###

Generated at: 2023-04-13 21:29:41 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for contacting us, @lincetto.

We cannot add the same hook, because it is defined as supplying a post object to callbacks (which does not happen in the context of the HPOS order editor). However, might you be able to use the `order_edit_form_tag` hook instead?

If that's not suitable, mind summarizing what you are hoping to achieve?
