### ISSUE TITLE
Create SVG icons for product block editor sections and update template to use icon url

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37711]
**Description**

We are currently outputting a full `svg` string within the template data. The `icon` prop also supports a url, we should create these icons within the an assets directory within the `product-editor` package and update our Webpack plugin to move them to the assets folder (`plugins/woocommerce/assets`) on build and pass in the URL instead to the `icon` attribute.

**Acceptance criteria**

- [ ] Section icons should be loaded by `url` from the assets folder.

**Comment by joshuatf** [comment]
If we decide to keep these assets in the product editor package, we can copy over to the WooCommerce folder using `CopyWebpackPlugin`.  For example - https://github.com/woocommerce/woocommerce/blob/8a14afabbc35b9a4a4fc33ee5dc14bc109256fe9/plugins/woocommerce-admin/webpack.config.js#L187-L196
