### ISSUE TITLE
Allow Tree Select Control to render selected items as comma separated list

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37727]
**Description**

The Category block designs require the selected items to be listed as a comma separated list when in read only mode (or when the dropdown isn't open) - see screenshot.
We make use of the Tree Select Control for this, it would be nice to allow us to determine how the selected list should be rendered (or maybe provide an option to overwrite the selected list).

![Image](https://user-images.githubusercontent.com/2240960/232044769-400b86ae-d972-4aca-9edf-e4a99391adb7.png).

**Design:**

AkVNGImLgSqCObTQ3idVn7-fi-1005_134857

**Acceptance criteria**

- [ ] When select tree control is in read only list we should be able to render a comma separated list instead of the tags.

**Comment by louwie17** [comment]
@jarekmorawski one follow up question on this design:
- Should the tags show up as soon as the user has focus on the input field? Meaning they can still use the `x` within each tag to remove the tags? (Meaning the only time the comma separated list shows up is in read only when the field is neither in focus or the dropdown is not open).

**Comment by jarekmorawski** [comment]
> Should the tags show up as soon as the user has focus on the input field?

They should only show up when the dropdown is open. We should, however, open it when the field is focused, so if someone navigates around using a keyboard, they'd see the tags and the dropdown open.

**Comment by louwie17** [comment]
> They should only show up when the dropdown is open. We should, however, open it when the field is focused, so if someone navigates around using a keyboard, they'd see the tags and the dropdown open.

Ok, that is fine, but would there ever be a case then when a user focuses on the input field and the dropdown isn't open?
I am just thinking if we should worry about handling the deletion of tags by removing them from the comma separated list, or if that will not be allowed?

**Comment by jarekmorawski** [comment]
> we should worry about handling the deletion of tags by removing them from the comma separated list, or if that will not be allowed?

No, the dropdown is in a read-only mode when it is not open.
