### ISSUE TITLE
Logging of difference between HPOS datastore and legacy

### ISSUE THREAD

**Issue by jb510** [woothemes/woocommerce#37721]
### Describe the solution you'd like

I'm trying to figure out how to plan for the day that HPOS sync is no longer necessary because all my add-ons are finally compatible.

I read in the wiki on roll out policies https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#roll-out-policies

I understand that when an order is retrieved from HPOS it is checked against the legacy data and if there is a difference then the legacy order date would be used.  Is this event's occurnace logged? Something like a deprecated function log?  That we we could monitor for that and see if it's happening, as well as if it's stopped happening.

Similarly, if several add-ons do not affirmatively declare support for HPOS and/or declare incompatibility at the time HPOS with sync is enabled is there later a notification presented to the user if/when those add-ons have all affirmatively declared support?

If solutions to these cases aren't built in, I think they should be.  If they are built in already (I couldn't find evidence of that), then they should be documented so users know what to expect down the road.

**Comment by barryhughes** [comment]
Thanks for proposing this!

We definitely agree with your idea about logging instances where we need to (re-)sync the order. That's a great suggestion, and I'll add it to the enhancement queue.

> Similarly, if several add-ons do not affirmatively declare support for HPOS and/or declare incompatibility at the time HPOS with sync is enabled is there later a notification presented to the user if/when those add-ons have all affirmatively declared support?

There could be some utility in that, but we don't feel it's necessary and, depending on the store/merchant, may not be desirable. We're open to discussing it further, but at the moment I'd propose we move forward only with the suggestion re logging.
