### ISSUE TITLE
Product Block Editor: Create product attributes block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37728]
**Description**

This issue will cover the creation of the product attributes block as we had designed in the original implementation.
With a few small additional changes (these changes can be done within the component as we will be replacing the current implementation with the block editor soon):
- The add attribute modal contains a description below the title
- The `By default, new attributes are filterable and visible on the product page. You can change these settings for each attribute separately later.` notice shown at the top has been moved down.

**Items shown in the designs that aren't part of this issue**
- The entire right column in the add and edit modals (the preview)

![Image](https://user-images.githubusercontent.com/2240960/232050356-07773d1b-8997-4f4b-afee-b9b05fd533d1.png)

![Image](https://user-images.githubusercontent.com/2240960/232050338-694b111e-444c-4af0-a819-d7f422e2ef9c.png)

**Designs**

AkVNGImLgSqCObTQ3idVn7-fi-1005_169648

**Acceptance criteria**

- [ ] Include a new **Attributes** section with the correct icon and description that contains the attributes field.
- [ ] **Add attribute** button should be present rendering a Modal to allow users to add attributes ( same as old design )
- [ ] Once attributes are added they can be edited, ~~re-ordered~~, removed (same as the old design).

**Comment by joelclimbsthings** [comment]
So I'm currently uncertain how to handle the lack of dragging functionality here due to it being suppressed within blocks (same as images). For the Images block we're [removing dragging functionality temporarily](https://teammothra.wordpress.com/2023/03/01/project-thread-product-page-block-implementation/#comment-1666), but in this case that is the only method we have for reordering attributes. 

Any thoughts on the above @louwie17 @mdperez86 @joshuatf @jarekmorawski ?

**Comment by louwie17** [comment]
> So I'm currently uncertain how to handle the lack of dragging functionality here due to it being suppressed within blocks (same as images). For the Images block we're [removing dragging functionality temporarily](pcQJnU-1j6-p2#comment-1666), but in this case that is the only method we have for reordering attributes.

@joelclimbsthings as part of this issue, I would create the attributes block with the drag and drop removed/disabled if that is easily done? We can do a follow up issue to support drag & drop.
In the mean time @jarekmorawski would it be worth adding arrows for changing the order? Adding drag & drop support would have to be pushed to the following cycle (most likely), as it will require us turning the attributes into individual blocks within the list.
