### ISSUE TITLE
[Enhancement]: Dequeue wc-cart-fragments when Enable AJAX add to cart buttons on archives is inactive

### ISSUE THREAD

**Issue by RafaelFunchal** [woothemes/woocommerce#37729]
### Describe the solution you'd like

When unchecking the option `Enable AJAX add to cart buttons on archives` on `WooCommerce > Settings > Products > General`, the script `wc-cart-fragments` (`/woocommerce/assets/js/frontend/cart-fragments.min.js`) should be dequeue automatically.

### Describe alternatives you've considered

Adding some custom code to the site with Code Snippets or as an MU-Plugin to dequeue wc-cart-fragments.

### Additional context

`wc-cart-fragments` can cause performance issues on sites with high traffic because it loads `cart-fragments.min.js` on every single page, not only WooCommerce pages.

Although it is possible to dequeue the script with custom code, it would be great if the script could be linked to the AJAX option on `WooCommerce > Settings > Products > General`.

**Comment by rrennick** [comment]
@RafaelFunchal I believe this has been addressed. Are you still seeing this on the latest version of WC?

**Comment by RafaelFunchal** [comment]
@rrennick , I just tested it on WooCommerce 8.0.3. Everything is good now :)

**Comment by rrennick** [comment]
@RafaelFunchal Thanks for the follow up.
