### ISSUE TITLE
Code analyzer checkout isn't successful in temp directory

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#37743]
There may be a permissions issue with the checkout done by `cloneRepo` in `tools/cli-core/src/git.ts`.

When I was running the code-analyzer, I ran into issues with `wp-env` telling me that woocommerce did not exist:

```
✔ Making temporary clone of /Users/jonathan/woo/woocommerce/...... complete.
Temporary clone of /Users/jonathan/woo/woocommerce/ created at /var/folders/0f/lg3fnq4s4wvdzdmy6yfj7v5w0000gn/T/code-analyzer-tmp/1ace4b81-362f-479d-8e5f-3ce2a45725f0
Temporary clone of /Users/jonathan/woo/woocommerce/ created at /var/folders/0f/lg3fnq4s4wvdzdmy6yfj7v5w0000gn/T/code-analyzer-tmp/1ace4b81-362f-479d-8e5f-3ce2a45725f0
⠏ Generating schema diff......Command failed: wp-env start
✖ Error while running docker-compose command.
Container a1d97e6e0be58720475ffb16d2f2ce91-tests-mysql-1  Running
Container a1d97e6e0be58720475ffb16d2f2ce91-tests-wordpress-1  Running
Warning: The 'woocommerce' plugin could not be found.
Error: No plugins activated.

 ELIFECYCLE  Command failed with exit code 1.
```

But those issues went away if I temporarily hard-coded a path within my home directory:

```
export const cloneRepo = async ( repoPath: string ) => {
	const folderPath = join( '/Users/jonathan/nottemp','code-analyzer-tmp', v4() );
	// ...
```

This seems to suggest that there's an issue with the temporary path and perhaps permissions.

**Comment by lsinger** [comment]
This was fixed by @ObliviousHarmony upstream [here](https://github.com/WordPress/gutenberg/pull/49962); the version update was [merged into WooCommerce 7.8.0 here](https://github.com/woocommerce/woocommerce/pull/38223). Closing as fixed until we hear otherwise.
