### ISSUE TITLE
Uncaught (in promise) TypeError: r[e] is undefined

### ISSUE THREAD

**Issue by DarkAllMan** [woothemes/woocommerce#37782]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I have disabled all of my plugins. When I open my order list I get javascript breaking console error:

`Uncaught (in promise) TypeError: r[e] is undefined
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    30504 https://*/wp-content/plugins/woocommerce/assets/client/admin/chunks/504.js:1
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    promise callback*68033/< https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    68033 https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    79489 https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
index.js:2:654386
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    30504 https://*/wp-content/plugins/woocommerce/assets/client/admin/chunks/504.js:1
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    (Async: promise callback)
    68033 https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    68033 https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    79489 https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    a https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
    <anonymous> https://*/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=7.6.0:2
`
![image](https://user-images.githubusercontent.com/1582343/232704454-9f69d412-2dc2-4b6c-9ecf-222ce099e6bc.png)

PS, I was asked by woocommerce support chat to open this issue.

**Comment by AashikP** [comment]
Hi @DarkAllMan 👋 

I'm closing this as a duplicate.

* Originally reported in https://github.com/woocommerce/woocommerce/issues/37348
* This was fixed in https://github.com/woocommerce/woocommerce/pull/37350
* Included in [7.7.0 Milestone](https://github.com/woocommerce/woocommerce/milestone/212?closed=1) 

Please do let us know if I've missed something here.
