### ISSUE TITLE
[Test] Hello World

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#37793]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

I discovered that when reversing shipping during sandbox mode et pharetra pharetra massa massa ultricies mi quis hendrerit. 

Ut tortor pretium viverra suspendisse potenti nullam ac. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Donec massa sapien faucibus et molestie ac feugiat sed. Faucibus purus in massa tempor nec. Libero enim sed faucibus turpis in eu mi bibendum neque. Id ornare arcu odio ut sem nulla pharetra diam. Diam volutpat commodo sed egestas egestas fringilla.

Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. This is just a test, it can be deleted a little later on.

**Comment by oldumbrellas** [comment]
I am interested in helping to solve this.

**Comment by barryhughes** [comment]
You are assigned. Now go cook up an amazing PR.
