### ISSUE TITLE
dates_are_gmt don't work

### ISSUE THREAD

**Issue by ServitelLTD** [woothemes/woocommerce#37809]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using the switch dates_are_gmt on retrieve modified products don't work

### Expected behavior

I pass a date like this modified_after=2023-04-17T07:48:00 and the switch dates_are_gmt=true and I expect products modified before this date aren't dispalyed.
I have also tried dates_are_gmt=1 with the same results

All plugin disabled
Same issue appears on my 5 woocommerce installation

### Actual behavior

A product modified before this date is displayed
![Immagine 2023-04-19 072940](https://user-images.githubusercontent.com/94214224/232980589-63037fde-6c9d-4a76-832a-1c50ce0f2b8d.png)

### Steps to reproduce

wp-json/wc/v3/products/?consumer_key=ck_xxxxx&consumer_secret=cs_xxxx&modified_after=2023-04-17T07:48:00&status=publish&order=asc&per_page=100&dates_are_gmt=true

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://filateliadesimoni.com
Site address (URL): https://filateliadesimoni.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 8.0.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 5.7.42-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Dimensione totale database: 413.27MB
Dimensione dati database: 361.48MB
Dimensione indice database: 51.79MB
wp_woocommerce_sessions: Dati: 147.07MB + indice: 2.95MB + motore MyISAM
wp_woocommerce_api_keys: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_order_items: Dati: 0.71MB + indice: 0.21MB + motore MyISAM
wp_woocommerce_order_itemmeta: Dati: 3.59MB + indice: 2.02MB + motore MyISAM
wp_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_shipping_zone_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_actionscheduler_actions: Dati: 4.16MB + indice: 1.42MB + motore MyISAM
wp_actionscheduler_claims: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_actionscheduler_groups: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_actionscheduler_logs: Dati: 2.73MB + indice: 1.87MB + motore MyISAM
wp_aioseo_cache: Dati: 0.14MB + indice: 0.05MB + motore MyISAM
wp_aioseo_notifications: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_aioseo_posts: Dati: 0.32MB + indice: 0.02MB + motore MyISAM
wp_cmplz_cookiebanners: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_cmplz_cookies: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_cmplz_services: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_commentmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_comments: Dati: 2.08MB + indice: 0.58MB + motore MyISAM
wp_es_deliverreport: Dati: 1.62MB + indice: 0.17MB + motore MyISAM
wp_es_emaillist: Dati: 0.26MB + indice: 0.03MB + motore MyISAM
wp_es_notification: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_es_sentdetails: Dati: 0.03MB + indice: 0.00MB + motore MyISAM
wp_es_subscriber_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Customers: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Custom_Fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Fields_Meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Orders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Order_Statuses: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_EWD_OTP_Sales_Reps: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_e_events: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_actions: Dati: 2.51MB + indice: 6.20MB + motore MyISAM
wp_ig_blocked_emails: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_campaigns: Dati: 0.03MB + indice: 0.00MB + motore MyISAM
wp_ig_contactmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_contacts: Dati: 0.33MB + indice: 0.20MB + motore MyISAM
wp_ig_contacts_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_contact_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_custom_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_lists: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_lists_contacts: Dati: 0.13MB + indice: 0.07MB + motore MyISAM
wp_ig_mailing_queue: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wp_ig_queue: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_sending_queue: Dati: 3.82MB + indice: 0.28MB + motore MyISAM
wp_ig_temp_import: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_unsubscribe_feedback: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_wc_cart: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_wc_guests: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_workflows: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_ig_workflows_queue: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_logger_ginger: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_moove_activity_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_options: Dati: 22.02MB + indice: 1.12MB + motore MyISAM
wp_pantheon_sessions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_postmeta: Dati: 93.14MB + indice: 17.11MB + motore MyISAM
wp_postmeta2: Dati: 44.67MB + indice: 9.48MB + motore MyISAM
wp_posts: Dati: 12.04MB + indice: 3.08MB + motore MyISAM
wp_posts2: Dati: 9.52MB + indice: 0.00MB + motore MyISAM
wp_rafflepress_contestants: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_rafflepress_entries: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_rafflepress_giveaways: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_css: Dati: 0.09MB + indice: 0.01MB + motore MyISAM
wp_revslider_css_bkp: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_revslider_layer_animations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_layer_animations_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_navigations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_navigations_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_sliders: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_revslider_sliders_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_slides: Dati: 0.11MB + indice: 0.00MB + motore MyISAM
wp_revslider_slides_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_static_slides: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_revslider_static_slides_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_shortpixel_folders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_shortpixel_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_smush_dir_images: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_termmeta: Dati: 0.87MB + indice: 0.10MB + motore MyISAM
wp_terms: Dati: 0.02MB + indice: 0.05MB + motore MyISAM
wp_term_relationships: Dati: 0.43MB + indice: 0.78MB + motore MyISAM
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
wp_tm_taskmeta: Dati: 2.19MB + indice: 0.30MB + motore MyISAM
wp_tm_tasks: Dati: 1.77MB + indice: 0.23MB + motore MyISAM
wp_usermeta: Dati: 2.76MB + indice: 1.49MB + motore MyISAM
wp_users: Dati: 0.32MB + indice: 0.25MB + motore MyISAM
wp_vtprd_purchase_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_vtprd_purchase_log_product: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_vtprd_purchase_log_product_rule: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_admin_notes: Dati: 0.05MB + indice: 0.00MB + motore MyISAM
wp_wc_admin_note_actions: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wp_wc_category_lookup: Dati: 0.01MB + indice: 0.02MB + motore MyISAM
wp_wc_customer_lookup: Dati: 0.09MB + indice: 0.08MB + motore MyISAM
wp_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_order_coupon_lookup: Dati: 0.01MB + indice: 0.02MB + motore MyISAM
wp_wc_order_product_lookup: Dati: 0.45MB + indice: 0.36MB + motore MyISAM
wp_wc_order_stats: Dati: 0.11MB + indice: 0.07MB + motore MyISAM
wp_wc_order_tax_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
wp_wc_product_download_directories: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_wc_product_meta_lookup: Dati: 1.07MB + indice: 0.99MB + motore MyISAM
wp_wc_rate_limits: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_reserved_stock: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wdp_orders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wdp_order_items: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wdp_rules: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woodmart_wishlists: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woodmart_wishlist_products: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woo_shippment_provider: Dati: 0.05MB + indice: 0.01MB + motore MyISAM
wp_wpforms_tasks_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wpgdprc_access_requests: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wpgdprc_consents: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wpgdprc_delete_requests: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wpgdprc_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_xsg_sitemap_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yith_wcwl: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_yith_wcwl_lists: Dati: 0.01MB + indice: 0.02MB + motore MyISAM

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 14478
cms_block: 23
custom_css: 2
customize_changeset: 2
elementor_library: 1
es_template: 22
jetpack_migration: 2
nav_menu_item: 620
oembed_cache: 5
page: 24
popup_theme: 6
portfolio: 9
post: 12
product: 9238
rainmaker_form: 1
rainmaker_lead: 44
revision: 277
schema: 2
seedprod: 3
shop_coupon: 2
shop_order: 1535
shop_order_refund: 2
symbol_main_slider: 1
woodmart_layout: 3
woodmart_sidebar: 2
woodmart_size_guide: 1
woodmart_slide: 3
wp_global_styles: 1
wpcf7_contact_form: 2
yith_wcps_type: 1
yith-wcet-etemplate: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Autoptimize: by Frank Goossens (futtta) – 3.1.6
Code Snippets: by Code Snippets Pro – 3.3.0
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.4.3
Contact Form 7: by Takayuki Miyoshi – 5.7.5.1
Easy WooCommerce Tracking Code Free: by webrook – 1.0.3
Elementor: by Elementor.com – 3.12.1
Icegram Express - Email Subscribers, Newsletters and Marketing Automation Plugin: by Icegram – 5.6.2
Postepay Gateway per Woocommerce: by Martino Stenta – 5.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Slider Revolution: by ThemePunch – 6.6.12
Supplemento Contrassegno WooCommerce: by Giuseppe Manduca – 1.1
WooCommerce Smart COD: by woosmartcod.com – 1.6.1
Servitel Custom Code: by Servitel Ltd – 1.0.0
WooCommerce: by Automattic – 7.6.0
Woodmart Core: by  – 1.0.36
WP Fastest Cache: by Emre Vona – 1.1.4
Smart Image Resize PRO: by Nabil Lemsieh – 1.7.6.4

### Inactive Plugins (1) ###

WooCommerce Admin: by WooCommerce – 3.3.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: ❌ L'ID della pagina è impostato
ma la pagina non esiste

Carrello: #5 - /carrello/
Pagamento: #6 - /checkout/
Il mio account: #7 - /mio-account/
Termini e condizioni: #2405 - /condizioni/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.1.4
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart-child/woocommerce/emails/admin-new-order.php
woodmart-child/woocommerce/emails/customer-processing-order.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-19 15:47:26 +02:00
Options: ✔
Notes: 128
Onboarding: completed

### Action Scheduler ###

Completato: 640
Oldest: 2023-03-19 09:53:17 +0100
Newest: 2023-04-19 06:42:21 +0200

Operazione non riuscita: 77
Oldest: 2023-02-15 09:34:29 +0100
Newest: 2023-04-15 04:31:30 +0200

In attesa: 1
Oldest: 2023-04-20 06:42:21 +0200
Newest: 2023-04-20 06:42:21 +0200

### Status report information ###

Generated at: 2023-04-19 08:03:57 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Sirswatch I wasn't able to reproduce this with either a `UTC+` or `UTC-` time zone setting. Could you try to reproduce it with the latest version of WooCommerce having no other plugins active?

**Comment by ServitelLTD** [comment]
I don't use UTC but "Rome". Peraphs the problem is in the time zone ? With UTC the time don't change on daylight savings time

**Comment by rrennick** [comment]
> I don't use UTC but "Rome". 

@Sirswatch Sorry I wasn't clear. I meant I tested with both `UTC+N` and `UTC-N` timezones where `N` was 2+ hours.

**Comment by ServitelLTD** [comment]
At my end and on 5 different installations with all plugin disabled (just woocommerce enabled) I have the issue. This is very strange. In a few time I install a new woocommerce on another server and I try again. Peraphs the problem is on a PHP configuration ?

**Comment by rrennick** [comment]
> Peraphs the problem is on a PHP configuration ?

If all the installations having the issue are on the same server then it's quite possible it's a PHP / server configuration issue. If you do find that it's one of those please let us know.

**Comment by ServitelLTD** [comment]
installations are on 3 different servers all with WHM/cpanel

**Comment by rrennick** [comment]
@Sirswatch Same hosting company?

**Comment by ServitelLTD** [comment]
Servers are managed by me. I can modify every configuration

**Comment by rrennick** [comment]
I wish I had some suggestions on where to look in the server / PHP config, but I don't. I'll close the issue. If you do find something please let us know. If it is releated to something in WC, we'll be happy to re-open the issue.
