### ISSUE TITLE
Carriage return is preventing build in windows/linux (WSL) environments 

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37828]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `pnpm run build` command fails within a WSL Ubuntu environment, in particular when running the `e2e-core-tests` package build command with error: `/usr/bin/env: 'bash\r': No such file or directory`
See screenshot:
![image](https://user-images.githubusercontent.com/2240960/233048497-fd590964-9fef-4a6b-b955-77d7b7a58e2e.png)

This is because of the carriage return.

### Expected behavior

The `pnpm run build` should run successfully within a WSL Ubuntu environment.

### Actual behavior

When running the `pnpm run build` command it fails within a WSL Ubuntu environment, when attempting to build the `e2e-core-tests` package with error: `/usr/bin/env: 'bash\r': No such file or directory`

### Steps to reproduce

*only happens within a WSL environment.
1. Load this branch and run `pnpm i`
2. Run `pnpm run build`
3. Notice error

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
In https://github.com/woocommerce/woocommerce/pull/37843 I made a change that should prevent line ending mistakes in the future. We _did_ also fix the messed up line endings that caused the issue.
