### ISSUE TITLE
New Order emails missing

### ISSUE THREAD

**Issue by yarrowayfarm2** [woothemes/woocommerce#37824]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

50% of New Order emails are not being sent. Some come through, and some go missing.

### Expected behavior

All emails should come to the registered email addresses.

### Actual behavior

Only some come through.

### Steps to reproduce

Missing emails:
Example Order Number: 25901, 25983

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://yarrowayfarm.com
Site address (URL): https://yarrowayfarm.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.83.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_kkjychdv16_
Total Database Size: 198.01MB
Database Data Size: 118.80MB
Database Index Size: 79.21MB
wp_kkjychdv16_woocommerce_sessions: Data: 3.02MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_kkjychdv16_woocommerce_order_itemmeta: Data: 15.52MB + Index: 18.03MB + Engine InnoDB
wp_kkjychdv16_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_actionscheduler_actions: Data: 1.33MB + Index: 0.59MB + Engine InnoDB
wp_kkjychdv16_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_actionscheduler_logs: Data: 0.50MB + Index: 0.36MB + Engine InnoDB
wp_kkjychdv16_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_atum_product_data: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_commentmeta: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_kkjychdv16_comments: Data: 7.52MB + Index: 9.09MB + Engine InnoDB
wp_kkjychdv16_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_hustle_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_hustle_entries_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_hustle_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_hustle_modules_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_hustle_tracking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_login_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_mailchimp_carts: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_newsletter: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_newsletter_emails: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_newsletter_sent: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_newsletter_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_newsletter_user_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_optins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_optin_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_options: Data: 5.45MB + Index: 0.27MB + Engine InnoDB
wp_kkjychdv16_popover_ip_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_postmeta: Data: 26.56MB + Index: 19.06MB + Engine InnoDB
wp_kkjychdv16_posts: Data: 2.52MB + Index: 0.84MB + Engine InnoDB
wp_kkjychdv16_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_css_bkp: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_slides: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_slides_bkp: Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_sbi_feed_caches: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_sbi_instagram_feeds_posts: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_sbi_instagram_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_sg_fblike_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_html_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_image_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_popup_addons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_sg_popup_addons_connection: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_popup_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sg_shortCode_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_sm_advanced_search_temp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_stock_log: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_kkjychdv16_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_tm_taskmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_tm_tasks: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_usermeta: Data: 9.52MB + Index: 11.03MB + Engine InnoDB
wp_kkjychdv16_users: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_kkjychdv16_wcpdf_invoice_number: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wp_kkjychdv16_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wc_customer_lookup: Data: 0.15MB + Index: 0.09MB + Engine MyISAM
wp_kkjychdv16_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wc_order_product_lookup: Data: 1.37MB + Index: 1.10MB + Engine MyISAM
wp_kkjychdv16_wc_order_stats: Data: 0.18MB + Index: 0.12MB + Engine MyISAM
wp_kkjychdv16_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_kkjychdv16_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_kkjychdv16_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_wfconfig: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wffilemods: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wfissues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wflogins: Data: 0.47MB + Index: 0.16MB + Engine InnoDB
wp_kkjychdv16_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_kkjychdv16_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_wp_topbar_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_kkjychdv16_yith_wcwl: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_yith_wcwl_lists: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_yoast_indexable: Data: 1.08MB + Index: 0.13MB + Engine InnoDB
wp_kkjychdv16_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_kkjychdv16_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kkjychdv16_zbs_companies: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_zbs_contacts: Data: 0.36MB + Index: 0.17MB + Engine InnoDB
wp_kkjychdv16_zbs_customfields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_kkjychdv16_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_externalsources: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_kkjychdv16_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_invoices: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_kkjychdv16_zbs_lineitems: Data: 8.52MB + Index: 2.03MB + Engine InnoDB
wp_kkjychdv16_zbs_logs: Data: 3.52MB + Index: 0.63MB + Engine InnoDB
wp_kkjychdv16_zbs_meta: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_kkjychdv16_zbs_notifications: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_object_links: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_kkjychdv16_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_kkjychdv16_zbs_quotes_templates: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_kkjychdv16_zbs_tags: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_tags_links: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_kkjychdv16_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kkjychdv16_zbs_transactions: Data: 1.52MB + Index: 0.77MB + Engine InnoDB

### Post Type Counts ###

attachment: 1145
br_minmax_limitation: 1
custom_css: 2
mc4wp-form: 1
nav_menu_item: 74
oembed_cache: 1
page: 60
popup: 1
popup_theme: 8
post: 8
product: 199
product_variation: 152
puro_testimonial: 3
revision: 39
seedprod: 1
shop_coupon: 2
shop_order: 3210
shop_order_refund: 14
social_icon: 1
vc_settings_preset: 2
vtmam-rule: 1
wpcf7_contact_form: 2
wpephpcompat_jobs: 42
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

AccessPress iFeeds: by AccessPress Themes – 4.0.6
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.28
Cashfree: by devcashfree – 4.4.5
Classic Editor: by WordPress Contributors – 1.6.3
CoBlocks: by GoDaddy – 3.0.2
Code Snippets: by Code Snippets Pro – 3.3.0
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.2.2
Gecko Sample Data: by JanStudio – 1.0.0
Hide Content by User Role for WPBakery: by wpTerra – 1.2.3
Image Hover Effects - WPBakery Addon Free Version: by Labib Ahmed – 5.0
Image Widget: by The Events Calendar – 4.4.8
Smash Balloon Instagram Feed: by Smash Balloon – 6.1.3
Social Slider Feed: by creativemotion – 2.1.0
JanStudio Addons: by JanStudio – 1.2.3
Jetpack CRM Extension: MailChimp Connector: by Jetpack – 2.7
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.3
Mailchimp for WooCommerce: by Mailchimp – 2.8.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.3
MetaSlider: by MetaSlider – 3.29.1
Minimum Maximum quantity & Minimum Order amount for WooCommerce: by PI Websolution – 2.1.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Responsive Gallery Grid: by Jules Colle
BDWM – 2.3.10

Slider Revolution: by ThemePunch – 6.2.22
Smart Manager - WooCommerce Advanced Bulk Edit, Inventory Management & more...: by StoreApps – 8.0.0
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.2.11
Social Icons: by ThemeGrill – 1.7.4
Top Bar: by WP Darko – 3.0.4
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.2
Woocommerce Minimum Order Purchase: by smscentral – 1.1
Razorpay for WooCommerce: by Team Razorpay – 4.3.2
Table Rate Shipping for WooCommerce: by JEM Plugins – 2.28
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.1
WooCommerce Product Stock Alert: by WC Marketplace – 1.7.5
WooCommerce: by Automattic – 7.5.1 (update to version 7.6.0 is available)
Yoast SEO: by Team Yoast – 20.5
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.14

WP Rollback: by GiveWP.com – 1.7.3
WooCommerce Variation Swatch: by WPAddon – 1.1.0
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.8.2

YITH WooCommerce Ajax Product Filter: by YITH – 4.20.0
YITH WooCommerce Popup: by YITH – 1.25.0
YITH WooCommerce Wishlist: by YITH – 3.19.0
Jetpack CRM: by Automattic - Jetpack CRM team – 5.6.0

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 5.1
CMP - Coming Soon & Maintenance Plugin: by NiteoThemes – 4.1.7
Cmssuperheroes: by Luan Nguyen
Cong Nguyen – 1.0.9.2

Contact Form 7: by Takayuki Miyoshi – 5.7.5.1
Custom Post Type UI: by WebDevStudios – 1.13.5
Envato Market: by Envato – 2.0.7
MOJO Marketplace: by Mike Hansen – 1.6.2
The SEO Framework: by The SEO Framework Team – 4.2.8
WooCommerce Admin: by WooCommerce – 3.3.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php
object-cache.php: object-cache.php

### Must Use Plugins (4) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.2
Object Cache Pro (MU): by Rhubarb Group – 1.18.0
System Plugin: by  – 4.70.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: INR (₹)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #823 - /shop/
Cart: #824 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #2098 - /terms-conditions/

### Theme ###

Name: Gecko
Version: 1.7.5
Author URL: http://www.janstudio.net
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-18 01:42:02 +00:00
Options: ✔
Notes: 65
Onboarding: completed

### Action Scheduler ###

Complete: 672
Oldest: 2023-03-19 07:07:01 +0000
Newest: 2023-04-19 06:57:46 +0000

Failed: 891
Oldest: 2022-10-28 23:24:36 +0000
Newest: 2023-01-25 13:23:02 +0000

Pending: 5
Oldest: 2023-04-20 00:00:54 +0000
Newest: 2023-04-21 20:29:24 +0000

### Status report information ###

Generated at: 2023-04-19 09:58:32 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ronnyadsetts** [comment]
To add to this, I've had missing order emails reported to me since the upgrade of Woo to 7.6.0.

I've not yet done any further investigation but have confirmed that the new order emails are *not* being sent, neither to the customer nor the shop admin.

**Comment by ronnyadsetts** [comment]
In my case, the missing emails was caused by the woo-order-splitter plugin. I tracked this down using the wp-mail-logging plugin.

**Comment by yarrowayfarm2** [comment]
Any resolution for this please?
I still don't get all the order emails. Have the new woocommerce version
autoinstalled too.

Anjali

**Comment by rrennick** [comment]
@yarrowayfarm2 Could you provide the steps to reproduce the issue? I appreciate this is a significant issue for you but we can't be of much assistance without knowing how to reproduce the issue. As per this [comment](https://github.com/woocommerce/woocommerce/issues/37824#issuecomment-1534275629), I suggest you install the `wp-mail-logging` plugin to get a log of the mail being sent by your WP install. That might give you an indication of where the issue is coming from.
