### ISSUE TITLE
Add tests to store management tracks events fired through JS

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#37856]
Original issue: #34257

We should either increment existing tests or create new test files to test whether the following tracks events are being fired correctly:

List of JS tracks events from [this spreadsheet](https://docs.google.com/spreadsheets/d/12YlSbrEG2vbNHS5lMBkGnxn-g3QKI61VExwKOm0oM_Q/edit#gid=0):

- [x] wcadmin_page_view
- [x] wcadmin_inbox_note_view
- [x] wcadmin_inbox_action_click
- [x] wcadmin_analytics_filter
- [x] wcadmin_activity_panel_open
- [x] wcadmin_activity_panel_orders_orders_begin_fulfillment
- [x] wcadmin_activity_panel_stock_update_stock
- [ ] wcadmin_ces_feedback
- [ ] wcadmin_ces_view

**Comment by nathanss** [comment]
@pmcpinto Hey Pedro, I'm working on this issue right now. Are there any tracks event you think have more priority than the others? 

If so, can you edit the issue and prioritize them? We divided the issue into JS and PHP. The PHP issue is in https://github.com/woocommerce/woocommerce/issues/37857.

**Comment by pmcpinto** [comment]
Hey Nathan, I've made some tweaks to the list in the description to ensure it's prioritized.
