### ISSUE TITLE
Investigate cancelled labeling Actions

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#37881]
We have Actions that do the following: 

- **Label Pull Request Project:** label new PRs as belonging to specific sub-projects depending on what files they touch, e.g., as `plugin: woocommerce`
- **Add Community Label:** label new issues and PRs as community contributions if they're coming from users that only have read permissions on this repository, and then assign a reviewer to community PRs

During [Contributor Day](https://developer.woocommerce.com/2023/04/13/woocommerce-contributor-day-guide/) on 2023-04-19, @iyut opened #37817. The above three tasks did not happen as their associated Actions were cancelled. 

These are the runs: 
- [Label Pull Request Project](https://github.com/woocommerce/woocommerce/actions/runs/4741339551/attempts/1)
- [Add Community Label](https://github.com/woocommerce/woocommerce/actions/runs/4741339552/attempts/1)

These runs were cancelled because the `github.ref` variable that we use to assign a concurrency group was set to `refs/head/trunk` instead of the PR's actual branch ([the latter is what the docs say](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)). When another community PR was opened before these had finished, they were canceled because the concurrency group was the same. 

_Hypothesis:_ this is actually the case for all forks, and we only just now noticed this because Contributor Day was the first time we had community PRs being created so close together, temporally speaking, that the concurrency group mattered?

**Comment by adimoldovan** [comment]
This was fixed by https://github.com/woocommerce/woocommerce/pull/47355 and https://github.com/woocommerce/woocommerce/pull/45793
