### ISSUE TITLE
Code Freeze CLI: Migrate notify-slack

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#37904]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As part of https://github.com/woocommerce/woocommerce/issues/37353, convert the [notify-slack](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/release-code-freeze.yml#L133) code freeze action step to a CLI interface

**Comment by samueljseay** [comment]
Lets achieve https://github.com/woocommerce/woocommerce/issues/37947 before we do this
