### ISSUE TITLE
woocommerce_adjust_non_base_location_prices does not affect displayed prices for logged in users

### ISSUE THREAD

**Issue by GruberViktor** [woothemes/woocommerce#37939]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a user is logged in and they have a shipping address where the country differs from the shop's base country, the price is displayed is as if woocommerce_adjust_non_base_location_prices were not activated. 

### Expected behavior

The prices displayed should always be the same, as long as the user has to pay VAT

### Actual behavior

For example the normal price I enter is 7,90 € at 10% VAT in Austria. 

When a logged in user from Belgium is surfing, the price on the product page says 7,61€. 
This must be because 7,90€ / 1.10 = 7.18€. Belgium has 6% VAT --> the price is displayed as 7,18 * 1.06 = 7.61€. 

When the user puts the item into the cart, the prices in the cart and in the checkout are normalized to 7,90€ again. 

### Steps to reproduce

1. activate woocommerce_adjust_non_base_location_prices
2. create a customer account, set the shipping address to a country that differs from the stores base country
3. open the product page for a product that has different VAT rates in the two countries

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.luvifermente.eu
Site address (URL): https://www.luvifermente.eu
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - Es ist eine neuere Version von WordPress verfügbar (6.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.27-0ubuntu0.20.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 347.37MB
Datenbank-Datengröße: 231.27MB
Datenbank-Indexgröße: 116.10MB
wp_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 29.55MB + Index: 24.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
crypto_files: Daten: 0.02MB + Index: 0.31MB + Engine InnoDB
crypto_membership: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
crypto_payments: Daten: 0.02MB + Index: 0.31MB + Engine InnoDB
crypto_products: Daten: 0.02MB + Index: 0.25MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 14.02MB + Index: 10.64MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 6.02MB + Index: 6.03MB + Engine InnoDB
wp_atum_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cmplz_cookiebanners: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Daten: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_comments: Daten: 5.52MB + Index: 2.41MB + Engine InnoDB
wp_duplicator_packages: Daten: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_formmaker: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_backup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_blocked: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_display_options: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_formmaker_groups: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_query: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_sessions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_submits: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_themes: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_views: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailerlite_checkouts: Daten: 1.39MB + Index: 0.00MB + Engine InnoDB
wp_ml_data: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 5.47MB + Index: 1.45MB + Engine InnoDB
wp_oses_attachments: Daten: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_oses_emails: Daten: 67.02MB + Index: 0.20MB + Engine InnoDB
wp_oses_failures: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Daten: 31.55MB + Index: 20.02MB + Engine InnoDB
wp_posts: Daten: 25.52MB + Index: 1.31MB + Engine InnoDB
wp_pps_countries: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_modules: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pps_modules_type: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_popup: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pps_popup_show_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_popup_show_pages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_statistics: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pps_usage_stat: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pu_blocks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pu_layout_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pu_snapshots: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pu_wrappers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_folders: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_smush_dir_images: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Daten: 2.52MB + Index: 8.33MB + Engine InnoDB
wp_statistics_search: Daten: 1.52MB + Index: 2.20MB + Engine InnoDB
wp_statistics_useronline: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Daten: 14.52MB + Index: 21.63MB + Engine InnoDB
wp_statistics_visitor_relationships: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stock_log: Daten: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Daten: 3.52MB + Index: 3.73MB + Engine InnoDB
wp_users: Daten: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.27MB + Index: 0.23MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 2.52MB + Index: 1.45MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdi_feeds: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdi_themes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 4.52MB + Index: 3.97MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 1.52MB + Index: 1.17MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 3.52MB + Index: 2.84MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpo_wcpbn_batch_numbers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wss_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 2
attachment: 183
batch: 74
cfmemailverification: 1
custom_css: 2
cwginstocknotifier: 42
elementor_library: 3
et_pb_layout: 7
movies: 1
nav_menu_item: 20
oceanwp_library: 2
page: 29
polylang_mo: 2
popup: 1
popup_theme: 6
post: 3
postman_sent_mail: 250
product: 44
product_variation: 7
revision: 2214
rezept: 38
rezepte: 1
sa_notification: 10
shop_coupon: 468
shop_order: 3849
shop_order_refund: 38
spucpt: 2
wafs: 1
wcbd_archive_layout: 1
wpforms: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Query Monitor: von John Blackbourn – 3.11.1
EPC-QR-codes for banktransfer: von Viktor Gruber – 0.1
ACF to REST API: von Aires Gonçalves – 3.3.3
Advanced Custom Fields: von WP Engine – 6.0.7
Antispam Bee: von pluginkollektiv – 2.11.2
The SEO Framework: von Das SEO Framework Team – 4.2.7.1
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: von codewoogeek – 3.2
Classic Editor: von WordPress-Mitwirkende – 1.6.2
Cookie Notice & Compliance for GDPR / CCPA: von Hu-manity.co – 2.4.6
Flexible Shipping: von Octolize – 4.18.6
HTML Editor Syntax Highlighter: von James Bradford – 2.4.4
Kadence WooCommerce Email Designer: von Kadence WP – 1.5.7
Really Simple CAPTCHA: von Takayuki Miyoshi – 2.1
Responsive Lightbox & Gallery: von dFactory – 2.4.4
W3 Total Cache: von BoldGrid – 2.2.12
WC Variations Radio Buttons: von 8manos – 2.0.5
MailerLite - WooCommerce integration: von MailerLite – 1.8.2
Advanced Order Export For WooCommerce: von AlgolPlus – 3.3.3
WooCommerce Stripe-Gateway: von WooCommerce – 7.0.2
Germanized für WooCommerce: von vendidero – 3.11.3
Woocommerce Odoo Connector: von Viktor Gruber – 0.1
WooCommerce PDF Rechnungen Premium: von Bas Elbers – 1.6.13
Invoices for WooCommerce: von Bas Elbers – 3.1.9
WooCommerce Review Form: von Viktor Gruber – 0.1
Sequential Order Numbers for WooCommerce: von SkyVerge – 1.9.7
WooCommerce: von Automattic – 7.3.0 (Update auf Version 7.6.0 ist verfügbar)
WP Crontrol: von John Blackbourn & Mitwirkende – 1.15.1
WP Offload SES Lite: von Delicious Brains – 1.4.6
WPForms Lite: von WPForms – 1.7.9.1

### Inactive Plugins (9) ###

Duplicator: von Snap Creek – 1.5.2.1
Enable Media Replace: von ShortPixel – 4.0.2
Post SMTP: von Post SMTP – 2.3.2
ShortPixel Image Optimizer: von ShortPixel - Convert WebP/AVIF & Optimize Images – 5.1.6
Store Toolkit for WooCommerce: von Visser Labs – 2.3.8
WooCommerce Admin: von WooCommerce – 3.3.2
Woocommerce Batch Numbers: von Viktor Gruber – 0.1
WP-Optimize - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.2.12

WP Statistics: von VeronaLabs – 13.2.16

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #42 - /korb/
Kasse: #43 - /kassa/
Mein Konto: #44 - /account/
Allgemeine Geschäftsbedingungen: #125 - /agb/

### Theme ###

Name: LUVI
Version: 1.0.0
Author URL: http://underscores.me/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: luvi/woocommerce/checkout/payment.php Version 3.5.3 ist veraltet. Die Hauptversion ist 7.0.1
luvi/woocommerce/single-product/product-image.php

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-04-23 10:23:20 +02:00
Options: ✔
Notes: 138
Onboarding: completed

### Action Scheduler ###

Abgebrochen: 7
Oldest: 2023-03-29 08:19:31 +0000
Newest: 2023-04-14 08:25:24 +0000

Abgeschlossen: 22.778
Oldest: 2023-03-23 09:27:06 +0000
Newest: 2023-04-22 23:19:24 +0000

Ausstehend: 15
Oldest: 2023-04-22 23:24:24 +0000
Newest: 2023-04-29 20:08:24 +0000

### Status report information ###

Generated at: 2023-04-23 01:20:33 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@GruberViktor Thanks for creating the issue

> When a user is logged in and they have a shipping address where the country differs from the shop's base country

Taxes are calculated based on the billing address vs the shipping address. The reason for this is that the customer (billing address) is purchasing the products/shipping from the shop. In turn, the shop is purchasing shipping for the purchased products to a different tax jurisdiction. Because they are two separate transactions the tax rate/amount does not carry over between transactions.

Do you see the same behaviour with billing addresses?

**Comment by GruberViktor** [comment]
I tried to recreate this bug on a fresh install, but failed to do so. 

After digging once more thoroughly through my theme I found the problem, which was of course introduced by me. Apologies for wasting your time and thanks for the attention!

**Comment by rrennick** [comment]
@GruberViktor Glad you found it.
