### ISSUE TITLE
[Enhancement]: Personalize your store: Newly created homepage notification disappears.

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#37975]
### Describe the solution you'd like

Currently during the "Personalize your store" setup flow, once you create a homepage the link to customize this homepage is displayed in a popup as seen in the screenshot below. This feels like something to celebrate so it feels a little underwhelming to be displayed in a notification that could quite easily be missed.

<img width="1257" alt="Screenshot 2023-04-25 at 12 24 47" src="https://user-images.githubusercontent.com/8639742/234262715-1d4e26ec-415c-4bf8-b9e6-edce4c5e013a.png">

### Describe alternatives you've considered

* Display a link to this within the screen itself after its creation
* Find a more celebratory way of notifying the user this action has been completed. Feels like a big thing?

### Additional context

This was highlighted during our internal product walkthrough exercise.

**Comment by chihsuan** [comment]
We'll soon replace the Personalize your store task, so I think we probably don't need to fix this and can close it when CYS is launched in Core.

**Comment by adrianduffell** [comment]
I think we can close it now -- Personalize Your Store was replaced with Choose Your Theme a while ago too.
