### ISSUE TITLE
 wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php:157 - Undefined property: stdClass::$net_sales wp_dashboard, do_meta_boxes, WC_Admin_Dashboard->status_widget after updating 3.8.1 --> 6.9.4 

### ISSUE THREAD

**Issue by MECSBV** [woothemes/woocommerce#37974]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This message appears when we update our store in the dashboard section, Woo Commerce status.. 

wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php:157 - Undefined property: stdClass::$net_sales
wp_dashboard, do_meta_boxes, WC_Admin_Dashboard->status_widget
![Woocommerce status]

(https://user-images.githubusercontent.com/131761489/234239698-11451f65-9b40-4467-9e73-b31038a860a5.jpg)

We want to update our store to the latest version. 

The version we had was 3.8.1 and we went to 6.9.4  were this issue appeared. We still have to update to 7.6.0

Maybe someone can help us fixing this issue ? 

### Expected behavior

that it shows the data in a proper and normal way 

### Actual behavior

showing a bug

### Steps to reproduce

1.dashboard

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://testshop.mecs.nl
Site address (URL): https://testshop.mecs.nl
WC Version: 6.9.4
REST API Version: ✔ 6.9.4
WC Blocks Version: ✔ 8.3.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.68-MariaDB
Max Upload Size: 226 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: wp_
Totale database grootte: 527.96MB
Database gegevens grootte: 349.75MB
Database index grootte: 178.21MB
wp_woocommerce_sessions: Data: 11.52MB + Index: 0.52MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.52MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 6.52MB + Index: 7.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
export_file_offset: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
import_file_offset: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
import_meta_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.41MB + Index: 0.66MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.28MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_brizy_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_ddp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_EWD_OTP_Customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Custom_Fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Fields_Meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Order_Statuses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Sales_Reps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ezoic_endpoints: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_feed_status: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_feedmanager_product_feedmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_source: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fg_redirect: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_fme_rfq: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.34MB + Index: 0.22MB + Engine InnoDB
wp_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 12.52MB + Index: 21.09MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 16.55MB + Index: 24.06MB + Engine InnoDB
wp_icl_string_positions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 9.52MB + Index: 1.52MB + Engine InnoDB
wp_icl_translate_job: Data: 0.31MB + Index: 0.17MB + Engine InnoDB
wp_icl_translations: Data: 2.52MB + Index: 7.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 21.52MB + Index: 0.45MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 16.33MB + Index: 1.77MB + Engine InnoDB
wp_pay_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pay_option_subs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pay_processing: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pay_transactions: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_pmxe_exports: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 126.66MB + Index: 63.19MB + Engine InnoDB
wp_posts: Data: 15.52MB + Index: 8.06MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_swift_performance_image_optimizer: Data: 5.52MB + Index: 2.52MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_terms: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_toolset_associations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trade: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_usermeta: Data: 12.52MB + Index: 12.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_vertical_thumbnail_slider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpt_sessions: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 4.72MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfbadleechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.45MB + Index: 0.25MB + Engine InnoDB
wp_wfhoover: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_wfleechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfscanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wfvulnscanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wonderplugin_carousel: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_woos_search_trends: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.38MB + Index: 0.53MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yith_wcwl: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 2.52MB + Index: 1.78MB + Engine InnoDB
wp_yoast_indexable: Data: 11.52MB + Index: 8.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.36MB + Index: 0.27MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 32
acf-field-group: 4
amn_mi-lite: 1
apus_footer: 9
apus_megamenu: 3
attachment: 18381
brizy-project: 1
ct_template: 30
customize_changeset: 29
custom_css: 1
elementor_library: 2
mc4wp-form: 2
ml-slide: 1
ml-slider: 1
nav_menu_item: 186
oembed_cache: 1
page: 151
post: 1
product: 8319
revision: 465
shop_coupon: 1
shop_order: 1428
sp_faq: 30
tpt-global-rule: 1
ufaq: 18
um_directory: 1
um_form: 4
vc4_templates: 3
wc_afrsm: 7
wc_product_table: 14
wp-types-group: 3
wp-types-user-group: 1
wpcf7r_action: 2
wpforms: 2
wpr_templates: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (27) ###

Automatic Translator: door Pampa Dev – 1.5.4
Custom Order Numbers for WooCommerce Pro: door Algoritmika Ltd – 1000.2.3
Debug balk: door wordpresspuntorg – 1.1.4
Custom Functions Plugin: door Erwin van Houwelingen – 0.1
Flexible Shipping: door Octolize – 4.21.1
Gettext override translations: door Ramon Fincken – 2.0.2
Site Kit by Google: door Google – 1.98.0
Members: door MemberPress – 3.2.4
Oxygen Elements for WooCommerce: door Soflyy – 2.0
Oxygen: door Soflyy – 4.5
Premmerce Brands for WooCommerce: door premmerce – 1.2.12
Prevent Browser Caching: door Kostya Tereshchuk
ISRAEL IT – 2.3.4

Side Cart WooCommerce: door XootiX – 2.2
Tiered Price Table for WooCommerce: door U2Code – 5.2.0
WooCommerce Product Table PRO: door WC Product Table – 2.9.5
Checkout Field Editor for WooCommerce: door ThemeHigh – 1.8.2
Bulk Order Form for WooCommerce: door WP Overnight – 3.5.7
WooCommerce EU/UK VAT Compliance (Premium): door David Anderson – 1.27.2
PAY. Payment Methods for WooCommerce: door PAY. – 3.14.1
WooCommerce Role Based Methods: door WPBackOffice – 2.4.4
WooCommerce: door Automattic – 6.9.4 (update naar versie 7.6.0 is beschikbaar)
Yoast SEO: door Team Yoast – 20.5
WP All Import: door Soflyy – 3.7.2
Asset CleanUp: Page Speed Booster: door Gabe Livan – 1.3.9.1
Backup For WP: door Backup for WP – 6.2
WP Bestandsbeheer: door mndpsingh287 – 7.1.8
WP Rocket: door WP Media – 3.12.6.1

### Inactive Plugins (6) ###

Classic Editor: door WordPress Contributors – 1.6.3
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: door MalCare Security – 4.97
Smush: door WPMU DEV – 3.12.6
WooCommerce Email Customizer: door cxThemes – 3.33
WooCommerce EU VAT Compliance (Premium): door David Anderson – 1.14.7
WP All Export Pro: door Soflyy – 1.8.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock-en)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Winkelbasis: #749 - /shop/
Winkelwagen: #34242 - /winkelmand/
Afrekenen: #3 - /afrekenen/
Mijn account: #4 - /mijn-account/
Algemene voorwaarden: #24980 - /algemene-voorwaarden/

### Theme ###

Name: Yozi Child
Version: 1.1.7.1529405440
Author URL: https://apusthemes.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub-thema aan. Zie: Hoe maak je een sub-thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ❌ Niet ingepland
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Complete: 1.310
Oldest: 2023-04-20 11:42:12 +0200
Newest: 2023-04-25 11:47:51 +0200

Failed: 1
Oldest: 2023-04-20 11:47:26 +0200
Newest: 2023-04-20 11:47:26 +0200

Pending: 2
Oldest: 2023-04-25 11:48:51 +0200
Newest: 2023-04-26 10:18:21 +0200

### Status report information ###

Generated at: 2023-04-25 11:48:58 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @MECSBV,

Unfortunately, upgrading from 3.8.1 to 7.6.0 will likely be very difficult. You should make sure that you're using the latest version of each of your plugins and themes as well as WordPress to ensure that you're fully compatible. You might also make sure that the update was fully deployed and that you don't have any modified or partially-downloaded files. Since this is more of a support request rather than a bug with WooCommerce Core I am going to go ahead and close this issue. This repository is for reporting bugs or requesting enhancements for WooCommerce itself.
