### ISSUE TITLE
Product Export Issue: CSV Column Title Names Are Not Rendered Correctly in PHP 8.1

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#37988]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Based on the report in zd-6229859

When exporting products while the server is running PHP `8.1`, the column names have additional symbols. I was able to replicate this in Turkish, but it could be affecting more languages.

This was previously reported in #32878 and the culprit was in [the following file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php#L398:L403). 

[I can see the mentioned function is deprecated in PHP version](https://wiki.php.net/rfc/remove_utf8_decode_and_utf8_encode) `8.2`, not `8.1`. Can't tell if it's related.

<img src="https://d.pr/i/ecBBSz+" alt="">
Link to image: https://d.pr/i/ecBBSz

### Expected behavior

/

### Actual behavior

/

### Steps to reproduce

Navigate to All products > Export.

### WordPress Environment

```
`
### WordPress Environment ###

WordPress address (URL): https://xxxxxxxxxxxxxx.wpcomstaging.com
Site address (URL): https://xxxxxxxxxxxxxxxxxxx.wpcomstaging.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 10.0.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.18
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔


`
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Babylon1999 Thanks for reporting this. Could you provide a small product import CSV with one product in the Turkish language that we could use to investigate this issue?

**Comment by Babylon1999** [comment]
Hey @rrennick,

Sure, here you go:

`PHP 8.1`: https://d.pr/f/9sk8Qp

`PHP 8.0`: https://d.pr/f/SKbo2e

I should probably note I don't speak Turkish, but as you can see in PHP `8.1` the column names have `+` and `-` signs which don't seem right.

**Comment by rrennick** [comment]
@Babylon1999 Thank you for the quick follow up.

**Comment by Konamiman** [comment]
Seems related to this: https://github.com/php/php-src/issues/8279#issuecomment-1083613035
