### ISSUE TITLE
Product Block Editor: Fix validation behavior

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#37984]
**Description**

Currently each field validation happened at render time. It uses the locking editor feature to prevent the form from been submitted.
If at first render there is an invalid field value, the error message immediately arises, when that should happen only if the field is dirty or if it has been touched by the user.
If we don't run the validation at the very beginning we are not going to be able to disable the `Save` button and prevent the product creation.

**AC**

- [ ] We want to check whether the form is in a dirty/touched state to enable/disable the `Save` button.
- [ ] We need to check if a particular field that is being validated is dirty/touched to prevent the error message to be shown before it has been touched.

**Comment by louwie17** [comment]
This looks good, although does the entity data store support keeping track of `touched`? We may want to stick with `dirty` only for now? as that should be relatively easy to check.

**Comment by mdperez86** [comment]
> This looks good, although does the entity data store support keeping track of touched?

I don't think so!

> We may want to stick with dirty only for now?

Yep we can know when a particular field is dirty or not by checking the `edits` from the entity datastore.

But sometimes we want to show validation messages when the field is not dirty but touched like if you focus/blur an empty required field without changing its value. That's why a touched state exists in forms long ago.

**Comment by louwie17** [comment]
> But sometimes we want to show validation messages when the field is not dirty but touched like if you focus/blur an empty required field without changing its value. That's why a touched state exists in forms long ago.

But in this instance the `save` button would already be disabled correct even before the user touched the field? It is only to display the error message. Meaning `touched` could be handled on the block/field level only, or is there an edge case to this that I am not seeing.
The only case would be if something doesn't become required until it is touched, but that just seems like bad practice.

**Comment by joshuatf** [comment]
This is a little tricky because we should prevent saving prior to a field being touched, but only show error messages when a field has been touched or the save button has been clicked.  I think this should look something like this:

* [ ] Touched fields should show error messages if they exist and lock the save button
* [ ] Untouched fields should not show error messages
* [ ] The "Save" button should initially be enabled
* [ ] When clicking "Save" we should show error messages, even for untouched fields and lock the button

The logic for this could be written either as:
a. Saving forces all fields to be "touched"
b. Error message render logic looks like: `( isTouched || hasSaved ) && error`

**Comment by mdperez86** [comment]
> or the save button has been clicked

I think the Save button should be (a) always enabled or (b) only enabled when the form is valid, but not in between.

Having (a) also comes with other complex a11y stuff like focusing the first invalid field to let the screen reader read the error message of that particular field. Just imagine this case where we are making changes in tab `Pricing` but the error happened under tab `General` in the `Name` field, for this case we should be able to navigate to the `General` tab and focus the `Name` field on `Save` button click.

The option (b) is less accessible but easier to implement. We don't need to jump the focus to a different invalid field rather than the current that is being changed.

**Comment by joshuatf** [comment]
I'm good with the "Save" button always being enabled (with the exception of when a save request is in progress).  I think this provides the user with better information instead of forcing them to determine why the button is disabled.

This also means that we'll need to draw better attention to errors when saving, either by focusing errors in the form or by using toast notices or both (cc @jarekmorawski not sure if you have a preference).  If we use the latter, we may want to consider having a method to aggregate all the errors in one place instead of showing a bunch of different toast notices.

**Comment by joelclimbsthings** [comment]
> This also means that we'll need to draw better attention to errors when saving, either by focusing errors in the form or by using toast notices or both

I'm good with the above approach, although the UX gets a little tricky if we have more than one error on separate tabs. We could just focus the first one, and then on subsequent saves focus the next? 

Alternatively we could fire a series of persistent toast notices (or a single aggregated one) that includes the ability to click on a particular error and focus that field. They could be resolved one at a time.

**Comment by jarekmorawski** [comment]
Hiya! Thanks for the ping. What if we only lock the `Add` button until the name field is filled? It's the only required field in the whole form, and we need the name to generate the slug (and it doesn't make sense to publish a product without a name).

As for other errors, there are multiple solutions, and the final one is a mix of them all. We could:

1. Use a tab badge to highlight areas where the error occurred. The currently viewed tab would get the badge.
2. Show in-form error messages below the affected field.
3. Show a fixed indicator at the bottom of the screen in case the error happens below the fold.
4. Use Gutenberg's pre-publish panel to surface missing information and errors when the user clicks the `Add` button (copy and design are exemplary).

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/79307566/234616764-5afcdcf6-55e3-48a7-aefc-59d83cc5e966.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/79307566/234616656-5f561135-cd6e-42d9-b4da-69b481acc0f3.png">

Having them all would be great, but I know we have limited resources. 1, 2, and 4 seem the most impactful, and we already have most ingredients in place (assuming the pre-publish panel in Gutenberg is extensible).

**Comment by mdperez86** [comment]
In my experience toasts are more likely to be used for business validation message that are not related to a particular field and most of the time are being triggered due to a server error response.

It's better (for a11y) a 'per field' approach anytime the error is directly related to that particular field. So the user attention is better caught and redirected to the right field without adding an extra interaction.

Because of that I normally combine both approaches for both scenarios.

1. When we have a way to know which is the field the error belongs to then we should use the 'per field' approach. This includes client or server side, sync or async validation.
2.  When it's an error, that involves more than 2 fields or is not related to any of the field present in the form, then use the toast approach. This includes client or server side, sync or async validation.

If we are going to have the `Save` button always enabled then we are going to need the following:
1. Validations should be triggered on field blur
a. For this a global state is required so we can prevent the form submission when it's invalid
b. We need to listen each field onBlur event to run validation
2. Validations should be triggered on `Save` button click
a. All validations should be called at once meaning that we need to have all validations registered in one place or find a way to trigger all fields validations one by one.
b. The first field with an error should be focus when we have a `per field` errors, show the toast otherwise.

**Comment by mdperez86** [comment]
@jarekmorawski 

> 1. Use a tab badge to highlight areas where the error occurred. The currently viewed tab would get the badge.
> 3. Show a fixed indicator at the bottom of the screen in case the error happens below the fold.

These two points are beneficial for people that are able to see, not too much for others with poor vision or blind.

> Use Gutenberg's pre-publish panel to surface missing information and errors when the user clicks the Add button (copy and design are exemplary).

I like this approach but I think it should be complementary (it's another place to highlight the errors) because this adds an extra interaction for the user to fix them all.

**Comment by joshuatf** [comment]
Estimating implementation of the global attribute functionality as  a `3`, but may need a follow-up of a `2` to handle converting existing block validation to the new system.

**Comment by joshuatf** [comment]
@jarekmorawski Do you have any additional thoughts on the above comments by @mdperez86?

I'm also in favor of making sure this is accessible so I might lean towards the visual additions for another issue if we want to add those on, but wanted to get your view and thoughts on priority for those issues?
