### ISSUE TITLE
Product Block Editor: Tabs are re-ordering when first loading the product edit page

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38002]
**Description**

There is a bug in the tabs block where they are being re-ordered on render. See video:

https://user-images.githubusercontent.com/2240960/234542567-19cd90b9-3ac0-493a-ac85-0c845b9a47c5.mp4

**Acceptance criteria**

- [ ] Tabs should stay stationary when refreshing or loading the page initially.

**Comment by louwie17** [comment]
Digging into this a bit, it appears that the reason the tabs are being re-ordered is because the `Tab` edit component is being initially added, then removed, and added again. Causing the fill to be removed and added again, this happens for each tab in order which is why the tabs are being toggled through in this behaviour.

It appears this is happening because of the `templateLock='contentOnly'` flag within the `tab` inner blocks usage. If I remove this prompt things work as expected.

**Comment by louwie17** [comment]
I created an issue in Gutenberg around the dom rendering and removing again: https://github.com/WordPress/gutenberg/issues/50163
Hopefully this will shine more light on whether this is a bug or something is mis-configured.

**Comment by louwie17** [comment]
Depending on what comes out of the above issue, we could add `order` support to the tab slot fills, this should prevent the tabs from re-ordering as it won't be depended on render time.
This will likely be a good addition anyway, but figuring out the original cause of this bug would still be important.

**Comment by joelclimbsthings** [comment]
@louwie17 I'll likely start on adding an `order` prop since this will be a good addition in terms of extensibility anyways, even in lieu of a response on the GB issue you created. If you believe it better for more clarity first we can put this issue on hold and list the other as a dependency.

**Comment by louwie17** [comment]
@joelclimbsthings I agree that an `order` prop will indeed be a good to have.
I will add the re-render concern to the revisit doc you created, so we don't forget about this.
