### ISSUE TITLE
wc_nav_menu_items dies on null on PHP 8.1 (Works on 8.0)

### ISSUE THREAD

**Issue by pwsonline** [woothemes/woocommerce#38007]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

DEPRECATED: STRSTR(): PASSING NULL TO PARAMETER #1 ($HAYSTACK) OF TYPE STRING IS DEPRECATED IN /WP-CONTENT/PLUGINS/WOOCOMMERCE/INCLUDES/WC-PAGE-FUNCTIONS.PHP ON LINE 139

wp_parse_url needs a (string) cast in front.

### Expected behavior

Not to show the warning.

### Actual behavior

Shows the warning.

### Steps to reproduce

Only shows non-logged-in. 

### WordPress Environment

WP 6.2
WC 7.6.1
PHP 8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by astwinioenergy** [comment]
wp_parse_url function may return null or false in some cases so the result cannot be directly passed to strstr() in php8. 
Fixing by checking if $path and $query are string is sufficient. 

<code>if ( (is_string($path) && strstr( $path, $customer_logout )) || (is_string($query) && strstr( $query, $customer_logout )) </code>

**Comment by jorgeatorres** [comment]
Fixed by #38008.
