### ISSUE TITLE
calc_exclusive_tax() causes Unsupported operand types: string * float

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#38009]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`6232378-zen`

Some of the subscriptions of this merchant renews successfully however throws an error after renewal.

The error is triggered after the Self Service Dashboard plugin calls calculate_totals() function on the subscription object.

> 04-25-2023 @ 09:56:36 - scheduled action 737246 (subscription payment) failed to finish processing due to the following error: Uncaught TypeError: Unsupported operand types: string * float in /public_html/wp-content/plugins/woocommerce/includes/class-wc-tax.php:175

This issue occurs because $price may be blank for shipping line item but $rates might not be empty in all cases:

https://github.com/woocommerce/woocommerce/blob/856df0a3a63be2d3b38ccb22282a3fcd554dcf6c/plugins/woocommerce/includes/class-wc-tax.php#L166

### Steps to reproduce

To replicate:

1. Enable tax - everything inclusive 
2. Add a standard rate 10% for US, enable tax on shipping
4. Add a flat rate with a price $10 and order a product with a US address
5. Go to the order, edit line items and set Shipping rate to blank
6. Recalculate and see the error logged

![https://d.pr/i/8xoMza](https://d.pr/i/8xoMza+) 
Full Size: https://d.pr/i/8xoMza

### WordPress Environment

NA

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Adding a note that the same calculation occurs in the compound taxes section of the function as well. This will need to be addressed in both places.
