### ISSUE TITLE
[Enhancement]: Non-animated plugin logo

### ISSUE THREAD

**Issue by mondalaci** [woothemes/woocommerce#38013]
### Describe the solution you'd like

I've just updated to WooCommerce 7.6.1, and the plugin update screen contained an animated logo which I find very annoying. Imagine how distracting it would be if every plugin used animated logos. I think it's a bad practice, and I'd prefer a non-animated logo.

**Comment by barryhughes** [comment]
I appreciate you taking the time to share this feedback, @mondalaci. I've shared this with the team but, right at this moment, we don't plan on making a further change.
