### ISSUE TITLE
[Enhancement]: Replace legacy blocks with the Products block for the default WooCommerce homepage

### ISSUE THREAD

**Issue by danielwrobert** [woothemes/woocommerce#38014]
### Describe the solution you'd like

The default home page that is created with the "Personalize your store" setup step uses our legacy blocks. These should be replaced with the Products Block. This was highlighted in our internal product walkthrough exercise recently.

![legacy-products-block](https://user-images.githubusercontent.com/481776/234701188-20561737-c84d-4620-a430-6cdf607b0afe.png)

### Additional context

This was highlighted in our internal product walkthrough exercise recently.

**Comment by psealock** [comment]
The new Customize Your Store results in Product blocks instead of legacy ones. @danielwrobert I will close this one, but please reopen if I've made a mistake.

<img width="1111" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/1b60aa09-a911-4299-af07-84500bd9753b">
