### ISSUE TITLE
Error message strong text wrapping

### ISSUE THREAD

**Issue by egauvin** [woothemes/woocommerce#38016]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

<img width="1025" alt="Screenshot 2023-04-26 at 4 52 54 PM" src="https://user-images.githubusercontent.com/25772620/234701786-0887a988-6bd4-49a0-9a32-b38e08d4b488.png">

The <strong> text is wrapping.

I'm using the Blocksy theme and Blocksy companion.

### Expected behavior

I expected the message text to be one line.

### Actual behavior

the message text appears to wrap to block elements

### Steps to reproduce

1. on the My Account page
2. click on Payment Method
3. click on Delete payment method
4. see a red error message, "That payment method cannot be deleted because it is linked to an automatic subscription. Please add a payment method, before trying again."
5. The message is broken at the part that is in the <strong> tag

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://yankeetradesman.local
Site address (URL): https://yankeetradesman.local
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 47.18MB
Database Data Size: 41.35MB
Database Index Size: 5.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.31MB + Index: 0.28MB + Engine InnoDB
wp_burst_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_burst_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_burst_statistics: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_facetwp_index: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_frm_fields: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_payments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_subscriptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mepr_events: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_members: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mepr_subscriptions: Data: 0.02MB + Index: 0.30MB + Engine InnoDB
wp_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mepr_transactions: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
wp_options: Data: 10.50MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wp_posts: Data: 23.19MB + Index: 0.14MB + Engine InnoDB
wp_pts_tables: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 6
customize_changeset: 338
frm_display: 1
frm_form_actions: 7
frm_styles: 2
genesis_custom_block: 1
gravityview: 1
mailpoet_page: 1
memberpressgroup: 1
memberpressproduct: 3
memberpressrule: 2
nav_menu_item: 30
page: 20
post: 4
product: 2
revision: 259
shop_order: 4
shop_subscription: 4
wp_global_styles: 2
wp_navigation: 1
wpcode: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Blocksy Companion (Premium): by CreativeThemes – 1.8.84
Burst Statistics - Privacy-Friendly Analytics for WordPress: by Really Simple Plugins – 1.3.5
Complianz Privacy Suite (GDPR/CCPA) premium: by Really Simple Plugins – 6.4.4.1
Complianz - Terms and Conditions: by Really Simple Plugins – 1.2.1
Font Awesome: by Font Awesome – 4.3.2
Formidable Forms Pro: by Strategy11 – 6.2
Formidable Registration: by Strategy11 – 2.09
Formidable Stripe: by Strategy11 – 3.0
Formidable Visual Views: by Strategy11 – 5.4
Formidable Forms: by Strategy11 Form Builder Team – 6.2.3
Getwid: by MotoPress – 1.8.5
WPCode Lite: by WPCode – 2.0.10
Jetpack: by Automattic – 12.0
MailPoet: by MailPoet – 4.12.2
Stackable - Gutenberg Blocks: by Gambit Technologies
Inc – 3.7.2

User Menus: by Code Atlantic – 1.3.1
WooCommerce Payments: by Automattic – 5.7.0 (update to version 5.8.0 is available)
WooCommerce Subscriptions: by WooCommerce – 5.0.1
WooCommerce: by Automattic – 7.6.0 (update to version 7.6.1 is available)
Yoast SEO: by Team Yoast – 20.5

### Inactive Plugins (6) ###

Better Search Replace: by WP Engine – 1.4.2
Blocksy Companion: by CreativeThemes – 1.8.84
Custom Post Type UI: by WebDevStudios – 1.13.5
FacetWP: by FacetWP
LLC – 4.1.5

Post SMTP: by Post SMTP – 2.4.8
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

burst_rest_api_optimizer.php: by  –
WP Engine Cache Plugin: by WP Engine – 1.1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #2592 - /shop/
Cart: #2593 - /cart/
Checkout: #2594 - /checkout/
My account: #2595 - /my-account/
Terms and conditions: #2402 - /terms-and-conditions/

### Theme ###

Name: Blocksy
Version: 1.8.84
Author URL: https://creativethemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: blocksy/woocommerce/cart/cart.php
blocksy/woocommerce/cart/mini-cart.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy/woocommerce/myaccount/my-account.php
blocksy/woocommerce/product-searchform.php
blocksy/woocommerce/single-product/tabs/tabs.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://yankeetradesman.local
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-active: 3
wc-cancelled: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Connecticut

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 3
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-27 15:45:21 +00:00
Options: ✔
Notes: 62
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Yes
Blog ID: 217980339
Account ID: acct_1Mxw8tFhLC72xmpn

### Action Scheduler ###

Canceled: 1
Oldest: 2023-04-23 18:06:50 +0000
Newest: 2023-04-23 18:06:50 +0000

Complete: 1,384
Oldest: 2023-04-17 15:46:23 +0000
Newest: 2023-04-26 21:10:06 +0000

Failed: 6
Oldest: 2021-12-28 21:43:51 +0000
Newest: 2023-04-17 16:54:03 +0000

Pending: 5
Oldest: 2023-04-26 21:12:06 +0000
Newest: 2024-04-23 18:04:59 +0000

### Status report information ###

Generated at: 2023-04-26 21:10:06 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by egauvin** [comment]
appears to be the li with the flex property that may be causing the problem.

**Comment by rrennick** [comment]
Hi @egauvin,

We don't provide support for third party themes. Could you switch to a default WordPress theme or Storefront to see it occurs with the supported themes?

**Comment by egauvin** [comment]
Thanks, yes, it’s being caused by the theme.

I will mention it to Blocksy.

**Comment by rrennick** [comment]
@egauvin Thanks for the follow up.

**Comment by egauvin** [comment]
Hi,

A bit more info.

We fixed it in with a little css:

#wcs_delete_token_warning li {
  display: block;
}


However, creativethemes is saying the root cause may be with the “li” set as “display: flex” in the plugin.

Just passing on the info.

-Eric
