### ISSUE TITLE
Iframe Editor: incomplete content on modal close

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#38020]
When using the modal editor in the new product blocks editor, content doesn't always get completely saved and shown in the description state.

This seems like it may be partially due to our debouncing the `onChange` ( https://github.com/woocommerce/woocommerce/blob/66a10ee8ce821cab178dd6b8fa951135bd10bd22/packages/js/product-editor/src/components/iframe-editor/iframe-editor.tsx#L69-L76 ) but also because the Gutenberg `onChange` handler appears to be debounced as well.

Adding in buttons to "Save/Update" the description may also help remedy this by allowing more time for the debounce to complete prior to closing the modal.

### Screenshots

![Image](https://user-images.githubusercontent.com/10561050/234745256-852ac290-0ec6-4ac8-af0a-3df9a1367abe.png)

### Reproducing

1. Enable the product blocks experience
2. Navigate to "Add product"
3. Click "Add description"
4. Add some content and quickly close the modal
5. Note that the content is not always complete

### Acceptance criteria

* [ ] The content should show in its entirety when the modal editor is closed

**Comment by louwie17** [comment]
Re-opening this as it did come up during internal testing again:
https://github.com/woocommerce/woocommerce/assets/2240960/27f18d39-eb68-4982-a0d2-e2fbe21be828
