### ISSUE TITLE
Product Block Editor: Update shipping class block to match new designs

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38044]
**Description**

Some design updates have been made to the shipping class block ( see design ):

**Design**
![Screenshot 2023-05-09 at 1 49 13 PM](https://github.com/woocommerce/woocommerce/assets/2240960/539c6900-da98-4402-8c0d-64d5a7b5be64)
![Screenshot 2023-05-09 at 1 49 08 PM](https://github.com/woocommerce/woocommerce/assets/2240960/df4feedf-b009-4fe1-8e9c-27f365be54fb)

AkVNGImLgSqCObTQ3idVn7-fi-1005_134277

**Acceptance criteria**

- [x] Change the section title from `Shipping fee` to `Shipping class`.
- [x] Remove the `Free shipping` option.
- [x] Replace the radio buttons with a regular dropdown.
- [x] The dropdown has 50% width and matches the width of the dimensions fields below.
- [x] The dropdown lists all existing shipping classes created by the user.
- [ ] The dropdown uses the new appearance for the list (same as with use for categories, minus the checkboxes).
- [x] By default, `No shipping class` is selected. It has the first position on the list.
- [x] All other items are ordered alphabetically.
- [x] `Create new` should still be part of the dropdown list and open the create modal upon click.

**Sticky create new button will be part of another issue**
~~At the bottom of the list, fixed on scroll, there's an option `Create new`, which opens the shipping class creation modal.~~

**Comment by joshuatf** [comment]
@louwie17 @jarekmorawski I thought we had discussed a "No shipping" option via radio.  Did we decide to go back to the option in the dropdown approach?

**Comment by joshuatf** [comment]
Noting that the "No shipping class" option already exists, but validation issues occur:

![Image](https://user-images.githubusercontent.com/10561050/236272821-1fbebeec-45c9-426f-89e9-588a3755b925.png)

I think this also looks confusing and am in favor of adding a "No shipping class" radio option instead of a dropdown option.

**Comment by joshuatf** [comment]
Estimate: 1 for validation issue
Estimate: 2 for the radio option

Assuming we do both, let's open a separate issue for the radio option.

**Comment by jarekmorawski** [comment]
> I thought we had discussed a "No shipping" option via radio. Did we decide to go back to the option in the dropdown approach?

Yes. Here's how I think it could work:

- [ ] We change the section title from `Shipping fee` to `Shipping class`.
- [ ] We remove the `Free shipping` option.
- [ ] We replace the radio buttons with a regular dropdown.
- [ ] The dropdown has 50% width and matches the width of the dimensions fields below.
- [ ] The dropdown lists all existing shipping classes created by the user.
- [ ] The dropdown uses the new appearance for the list (same as with use for categories, minus the checkboxes).
- [ ] By default, `No shipping class` is selected. It has the first position on the list.
- [ ] All other items are ordered alphabetically.
- [ ] At the bottom of the list, fixed on scroll, there's an option `Create new`, which opens the shipping class creation modal.

In a future improvement, I'd like us to move the field to a separate section called `Shipping details`. At some point, we'll add there stuff like customs information and other details provided by us or 3PDs. cc @pmcpinto 

**Early design**

`AkVNGImLgSqCObTQ3idVn7-fi-1491-235303&t=CkE8K69ZtSLgHeX9-4`
