### ISSUE TITLE
Getting error CurlClient

### ISSUE THREAD

**Issue by devgeektech** [woothemes/woocommerce#38050]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am getting CurlClient error with the latest woocommerce v7.6.1 Wordpress 6.2 on PHP 8 and above version. However, it is working fine on PHP 7.4

Can any one suggest what can be the reason?anyone

### Expected behavior

I am getting CurlClient error with the latest woocommerce v7.6.1 Wordpress 6.2 on PHP 8 and above version. However, it is working fine on PHP 7.4

Can any one suggest what can be the reason?anyone

### Actual behavior

I am getting CurlClient error with the latest woocommerce v7.6.1 Wordpress 6.2 on PHP 8 and above version. However, it is working fine on PHP 7.4

Can any one suggest what can be the reason?anyone

### Steps to reproduce

I am getting CurlClient error with the latest woocommerce v7.6.1 Wordpress 6.2 on PHP 8 and above version. However, it is working fine on PHP 7.4

Can any one suggest what can be the reason?anyone

### WordPress Environment

I am getting CurlClient error with the latest woocommerce v7.6.1 Wordpress 6.2 on PHP 8 and above version. However, it is working fine on PHP 7.4

Can anyone suggest what can be the reason?

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ZeldOcarina** [comment]
Hi! Any hope to get an answer here on this? It happens for me as well..

**Comment by ObliviousHarmony** [comment]
Hello @devgeektech,

Unfortunately, as-is, this bug report doesn't have enough information to be actionable. Could you please provide more information about how to reproduce this bug?
