### ISSUE TITLE
Product Block Editor: Hitting escape seems to select and highlight parent blocks

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38062]
**Description**

There is some weird behaviour within the product block form when hitting the escape key several times.
It seems to navigate up the block tree and highlight each parent tree, but after doing so it is more difficult to select an input field again unless you click around a bit.

We should fix this, and have escape work like normal, and if possible disable the current functionality within the product block editor.

![Image](https://user-images.githubusercontent.com/2240960/235461941-1366d026-a6df-4357-89f5-f7df3918e7bc.png)

**To reproduce**

1. Enable the `product-block-editor` feature flag and go to **Products > Add New**
2. Select one of the input fields like product name and hit escape
3. Notice how it first selects the product name block
4. Hit escape again, and notice how the whole tab is selected now.

**Acceptance criteria**

- [ ] Hitting escape key should not select parent blocks
- [ ] Hitting escape key within input fields should do nothing.
- [ ] Hitting escape key within category block field should close the menu.

**Comment by joshuatf** [comment]
The default escape functionality will be fixed by [this PR](https://github.com/woocommerce/woocommerce/pull/38105).

> Hitting escape key within category block field should close the menu.

@louwie17 This behavior does not work and does not appear to be part of the old behavior either.  Given we have a discussion next week to look at consolidating dropdown behavior, I think it might be good to close this issue and address dropdown-specific behavior separately.  What do you think?

**Comment by louwie17** [comment]
> This behavior does not work and does not appear to be part of the old behavior either. Given we have a discussion next week to look at consolidating dropdown behavior, I think it might be good to close this issue and address dropdown-specific behavior separately. What do you think?

That sounds good with me, thanks for mentioning this.
