### ISSUE TITLE
Post publish time is recorded when the post is edited

### ISSUE THREAD

**Issue by thuautp** [woothemes/woocommerce#38075]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating to version 7.6.0 and 7.6.1, when starting a new post, the publish date and time is set to the time I write the post, not the time that the post is published. 

### Expected behavior

The publish time should be the time the post is actually published.

### Actual behavior

The publish time is set to the time the post is started. For example, if I add a new post at 1:30PM, edit it then publish at 2PM, the publish time is recorded as 1:30PM instead of 2PM.

### Steps to reproduce

1. Update WooCommerce to version 7.6.1
2. Add a new post, start editing the post. Wait for a few minutes before publishing the post
3. Publish the post, notice how the publish time is not the current time but when the post was started
4. Downgrade to 7.5.1 and confirm the issue doesn't persist

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://inc42.com
Site address (URL): https://inc42.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.0.1 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.3
PHP Version: 8.0.26
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.5.12-MariaDB-1:10.5.12+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: 42_
Total Database Size: 4724.90MB
Database Data Size: 3661.17MB
Database Index Size: 1063.73MB
42_woocommerce_sessions: Data: 3.02MB + Index: 0.08MB + Engine InnoDB
42_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
42_woocommerce_order_items: Data: 2.52MB + Index: 1.33MB + Engine InnoDB
42_woocommerce_order_itemmeta: Data: 18.55MB + Index: 17.02MB + Engine InnoDB
42_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
42_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_woocommerce_payment_tokenmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
42_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_actionscheduler_actions: Data: 17.02MB + Index: 17.13MB + Engine InnoDB
42_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_actionscheduler_logs: Data: 8.02MB + Index: 8.03MB + Engine InnoDB
42_ai_statistics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_automatewoo_abandoned_carts: Data: 0.44MB + Index: 0.08MB + Engine InnoDB
42_automatewoo_customers: Data: 1.52MB + Index: 2.88MB + Engine InnoDB
42_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
42_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
42_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_automatewoo_logs: Data: 0.08MB + Index: 0.16MB + Engine InnoDB
42_automatewoo_log_meta: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
42_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
42_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_cli_visitor_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_commentmeta: Data: 2.52MB + Index: 3.48MB + Engine InnoDB
42_comments: Data: 10.52MB + Index: 9.75MB + Engine InnoDB
42_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_fb3d_pages: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
42_gf_addon_feed: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
42_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_gf_entry: Data: 61.59MB + Index: 9.03MB + Engine InnoDB
42_gf_entry_meta: Data: 154.69MB + Index: 190.23MB + Engine InnoDB
42_gf_entry_notes: Data: 17.52MB + Index: 4.03MB + Engine InnoDB
42_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_gf_form_meta: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
42_gf_form_revisions: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
42_gf_form_view: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
42_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_lp_ip_blocker: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
42_options: Data: 127.39MB + Index: 3.52MB + Engine InnoDB
42_pmxe_exports: Data: 59.52MB + Index: 0.00MB + Engine InnoDB
42_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
42_pmxe_posts: Data: 37.56MB + Index: 0.00MB + Engine InnoDB
42_pmxe_templates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
42_postmeta: Data: 1113.00MB + Index: 427.56MB + Engine InnoDB
42_posts: Data: 1573.94MB + Index: 54.08MB + Engine InnoDB
42_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_rg_form_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
42_rg_form_view: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
42_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_rg_lead: Data: 2.52MB + Index: 0.38MB + Engine InnoDB
42_rg_lead_detail: Data: 19.55MB + Index: 21.16MB + Engine InnoDB
42_rg_lead_detail_long: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
42_rg_lead_meta: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
42_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_structuring_markup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_taxonomymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_termmeta: Data: 2.48MB + Index: 2.48MB + Engine InnoDB
42_terms: Data: 2.05MB + Index: 9.06MB + Engine InnoDB
42_term_relationships: Data: 31.13MB + Index: 24.11MB + Engine InnoDB
42_term_taxonomy: Data: 4.06MB + Index: 5.06MB + Engine InnoDB
42_usermeta: Data: 153.77MB + Index: 114.25MB + Engine InnoDB
42_users: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
42_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wcs_payment_retries: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
42_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
42_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
42_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wc_customer_lookup: Data: 3.02MB + Index: 3.03MB + Engine InnoDB
42_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
42_wc_order_product_lookup: Data: 2.52MB + Index: 1.44MB + Engine InnoDB
42_wc_order_stats: Data: 2.52MB + Index: 1.20MB + Engine InnoDB
42_wc_order_tax_lookup: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
42_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
42_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_wpdatacharts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wpdatatables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wpdatatables_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wpdatatables_columns: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
42_wpdatatables_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wt_iew_action_history: Data: 2.06MB + Index: 0.00MB + Engine InnoDB
42_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
42_wt_iew_mapping_template: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
42_yoast_indexable: Data: 121.61MB + Index: 40.44MB + Engine InnoDB
42_yoast_indexable_hierarchy: Data: 6.13MB + Index: 7.28MB + Engine InnoDB
42_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
42_yoast_primary_term: Data: 2.52MB + Index: 3.02MB + Engine InnoDB
42_yoast_prominent_words: Data: 20.55MB + Index: 42.61MB + Engine InnoDB
42_yoast_seo_links: Data: 42.58MB + Index: 28.92MB + Engine InnoDB
42_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

3d-flip-book: 1
acf-field: 1798
acf-field-group: 72
ai_galleries: 66
ajde_events: 1
amn_om: 3
amp_cta_bar: 1
amp_validated_url: 4
amp-cta: 9
amp-optin: 2
amppopup: 5
attachment: 99641
aw_workflow: 5
cp_popups: 11
custom_css: 7
datalabs: 81
dflip: 1
fast42: 84
flare: 6
foobar: 2
guide: 5
inc42-faq: 43
inc42-videos: 882
jetpack_migration: 2
mts_notification_bar: 1
nav_menu_item: 296
oembed_cache: 1706
omapi: 28
opanda-item: 8
optin: 6
option-tree: 1
page: 86
post: 37187
product: 7
product_variation: 36
review: 4
revision: 114139
safecss: 1
saswp: 5
schema: 2
schema_event_post: 4
sd2_custom_slide: 11
shop_coupon: 1361
shop_order: 13401
shop_order_refund: 50
shop_subscription: 14335
shortcoder: 9
sidebar: 4
slidedeck: 2
slidedeck_slide: 8
slidedeck2: 3
snp_popups: 19
sponsor: 1
squeezebar: 1
startup-essential: 27
startup-essentials: 4
startup-reports: 12
tfuse_gallery_group: 446
tribe_events: 886
tribe_organizer: 650
tribe_venue: 717
tshowcase: 4
wdca_custom_ad: 6
web-story: 73
wp_global_styles: 1
wp_router_page: 1
wp_stream_alerts: 4
wpcode: 4
yaymail_template: 45
yopress_subscribers: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (54) ###

Gravity Forms: by Gravity Forms – 2.7.4
JSON Basic Authentication: by WordPress API Team – 0.1
Inc42 Webhook: by Ashish Sharma – 1.0
Ad Inserter Pro: by Ad Inserter Pro – 2.7.25
Advanced Custom Fields PRO: by WP Engine – 6.0.7
AMP: by AMP Project Contributors – 2.4.1
Login by Auth0: by Auth0 – 4.5.0
AutomateWoo: by WooCommerce – 5.5.15
Autoptimize: by Frank Goossens (futtta) – 3.1.6
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Cloudflare: by Cloudflare
Inc. – 4.11.0

GTM4WP: by Thomas Geiger – 1.16.2
Easy WP SMTP: by Easy WP SMTP – 2.1.0
Featured Images in RSS for Mailchimp & More: by 5 Star Plugins – 1.6.1
Gravity Forms ActiveCampaign Add-On: by Gravity Forms – 2.0
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
Import Export Suite for WooCommerce: by WebToffee – 1.0.5
Inc42 Periodic Table: by Gautam Thapar – 1.0
Inc42 Post Types: by Gautam Thapar – 1.1
Inc42 Rest API: by Gautam Thapar – 1.0
Inc42 Tag Structure: by Ashish Sharma – 1.0
WPCode Lite: by WPCode – 2.0.10
Leaky Paywall - Article Countdown Nag: by Leaky Paywall – 3.7.4
Leaky Paywall - IP Blocker: by ZEEN101 – 1.4.0
Leaky Paywall - Lead In: by ZEEN101 – 1.1.0
Leaky Paywall - Multiple Levels: by Zeen101 Development Team – 1.3.0
Leaky Paywall - WooCommerce: by ZEEN101 – 1.3.0
Leaky Paywall: by Leaky Paywall – 4.19.7
Loggedin - Limit Active Logins: by Joel James – 1.3.1
Metorik Helper: by Metorik – 1.6.2
OptinMonster: by OptinMonster Popup Builder Team – 2.13.1
PDF Embedder: by WP PDF Embedder Team – 4.6.4
Publish to Apple News: by Alley – 2.4.0
Razorpay Subscriptions for WooCommerce: by Razorpay – 2.3.5
Schema & Structured Data for WP & AMP: by Magazine3 – 1.13
External Links: by Denis de Bernardy & Mike Koepke – 6.8.1
Shortcoder: by Aakash Chakravarthy – 6.2
User Role Editor Pro: by Vladimir Garagulia – 4.63.2
Web Stories: by Google – 1.31.0
Razorpay for WooCommerce: by Team Razorpay – 4.5.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.3
WooCommerce Conversion Tracking Pro: by weDevs – 1.0.7
WooCommerce Conversion Tracking: by weDevs – 2.0.10
WooCommerce Google Analytics Pro: by SkyVerge – 1.12.0
WooCommerce Subscriptions: by WooCommerce – 4.5.0
WooCommerce URL Coupons: by SkyVerge – 2.13.0
WooCommerce: by Automattic – 7.6.0 (update to version 7.6.1 is available)
Yoast SEO Premium: by Team Yoast – 19.3
Yoast SEO: by Team Yoast – 20.5
WP All Export Pro: by Soflyy – 1.8.3
WP Search with Algolia: by WebDevStudios – 2.5.0
wpDataTables: by TMS-Plugins – 5.4.1
Yoast SEO: News: by Team Yoast – 13.1

### Inactive Plugins (40) ###

Cache-Control: by Daniel Aleksandersen – 2.2.5
CF Image Resizing: by Mecanik – 1.3
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.2
Disable XML-RPC: by Philip Erb – 1.0.1
GDPR Cookie Consent: by markwt – 2.0.4
Gravity Forms Block Email Domains: by Road Warrior Creative – 1.0.2
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
Hubspot for Gravity Forms: by Big Sea – 4.2.1
Image Optimization For SEO: by Weblizar – 1.3.5
Inc42 Flipbook: by Gautam Thapar – 1.0
Inc42 Tag Mapping: by Gautam Thapar – 1.0
Inc42 Tag Restrict: by Gautam Thapar – 1.1
Jetpack: by Automattic – 12.0
Make, formerly Integromat Connector: by Celonis s.r.o. – 1.5.5
Mashshare - Google Analytics Integration: by René Hermenau – 1.0.9
Mashshare - Social Networks Add-On: by René Hermenau – 2.5.3
Mashshare Share Buttons: by WPChill – 3.8.8
MobiLoud Extension for Inc42: by Ashish Sharma – 1.0
MobiLoud News: by MobiLoud – 4.4.5
Nginx Helper: by rtCamp – 2.2.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.2
Pixel Caffeine: by AdEspresso – 2.3.3
S3 Uploads: by Human Made Limited – 2.2.2
Schema Pro: by Brainstorm Force – 2.7.2
Semrush SEO Writing Assistant: by Semrush – 1.2.1
Simple Local Avatars: by 10up – 2.7.4
Stream: by XWP – 3.9.2
SWE Country Code Field GF Add-On: by SanjayWebExpert – 2.1.0
Two Factor: by Plugin Contributors – 0.8.1
VaultPress: by Automattic – 2.2.3
WooCommerce Direct Checkout: by QuadLayers – 3.0.4
WooCommerce Email Customizer with Drag and Drop Email Builder: by Flycart Technologies LLP – 1.5.14
WooCommerce Order Status Control: by SkyVerge – 1.13.1
WooCommerce Stripe Gateway: by WooCommerce – 7.3.0
WordPress Importer: by wordpressdotorg – 0.8
WP All Export - ACF Export Add-On Pro: by Soflyy – 1.0.4
WP Image Size Limit: by Sean Butze – 1.0.4
YayMail Addon for AutomateWoo: by YayCommerce – 1.6
YayMail Premium Addon for WooCommerce Subscriptions: by YayCommerce – 1.9
YayMail Pro - WooCommerce Email Customizer: by YayCommerce – 2.9.4

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #296930 - /shop/
Cart: #296931 - /cart/
Checkout: #296932 - /checkout/
My account: #166099 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Inc42
Version: 1.0.0
Author URL: https://inc42.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: inc42/woocommerce/checkout/form-billing.php
inc42/woocommerce/checkout/thankyou.php
inc42/woocommerce/myaccount/dashboard.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://inc42.com
Subscription Statuses: trash: 3
wc-active: 3066
wc-expired: 8494
wc-pending-cancel: 55
wc-pending: 31
wc-on-hold: 2058
wc-cancelled: 628

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: India — DELHI

### Subscriptions by Payment Gateway ###

other: wc-active: 1242
wc-cancelled: 45
wc-expired: 163
wc-on-hold: 949
wc-pending-cancel: 13

### Payment Gateway Support ###

Razorpay: products
refunds

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-28 14:25:08 +05:30
Options: ✔
Notes: 102
Onboarding: completed

### Action Scheduler ###

Canceled: 2
Oldest: 2023-04-14 12:12:43 +0530
Newest: 2023-04-18 19:18:16 +0530

Complete: 26,096
Oldest: 2023-03-28 19:12:46 +0530
Newest: 2023-04-28 18:57:03 +0530

Failed: 49
Oldest: 2022-07-25 22:48:17 +0530
Newest: 2023-04-22 12:26:20 +0530

Pending: 3,546
Oldest: 2023-04-28 21:38:16 +0530
Newest: 2029-04-03 13:02:42 +0530

### Status report information ###

Generated at: 2023-04-28 19:13:16 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Via git bisect, this appears to be the commit that introduced this issue:
https://github.com/woocommerce/woocommerce/commit/970c1ef35237128b1807207bf327605902192c29

**Comment by claudiulodro** [comment]
We've also received a number of reports of this happening across our clients, and the timing coincides with WC 7.6.0.

**Comment by claudiulodro** [comment]
Confirmed that rolling back to WC 7.5.1 solves the problem. From my perspective this is a high priority bug because the issue is so disruptive to publisher workflows that we can't really run WC 7.6.0+ until this is fixed.
