### ISSUE TITLE
Product Block Editor: FreeForm block not working - Tinymce error

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38118]
**Description**

The FreeForm block is not working within the description block, causing any of the auto added product descriptions not to be editable, and thus also not backwards compatible. 
It looks like there is some missing scripts that TinyMCE is relying on, see this error created by the Gutenberg `FreeForm` block:

![Image](https://user-images.githubusercontent.com/2240960/236216776-3eb7dcd4-09a7-41e8-9dbc-d3c637d28180.png)

Related to this code:

![Image](https://user-images.githubusercontent.com/2240960/236216828-38066318-a985-45b9-92fb-3e0a9e891652.png)

`window.wpEditorL10n` seems to be missing.

**Acceptance criteria**

- [ ] Classic block should render correctly within the product description editor
- [ ] Product description editor modal should correctly render descriptions of imported products.

**Comment by joshuatf** [comment]
@louwie17 is this free form block a necessity?  I think it might be best if we just remove this from the modal editor.  What do you think?

**Comment by louwie17** [comment]
> @louwie17 is this free form block a necessity? I think it might be best if we just remove this from the modal editor. What do you think?

It is still supported in the post block editor, and it would break backwards compatibility with any existing products and imported products. So I would say it is necessary.

**Comment by joshuatf** [comment]
@louwie17 Do imported product descriptions get automatically converted into FreeForm blocks?

**Comment by louwie17** [comment]
> @louwie17 Do imported product descriptions get automatically converted into FreeForm blocks?

Yes it appears that way, but the `FreeForm` block shows a `Convert to blocks` option when editing:
![Screenshot 2023-05-09 at 12 19 34 PM](https://github.com/woocommerce/woocommerce/assets/2240960/f3e01843-2d66-4d74-ba60-adc4c1e50fdf)
