### ISSUE TITLE
WP FSE creates backups of the current Taxonomy

### ISSUE THREAD

**Issue by mranden** [woothemes/woocommerce#38119]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hey! :) 

Every time I edit my WooCommerce Category Template inside the FSE in WP, it creates a Taxonomy Product Cat {number}. 

This seems very odd for me, and have been a problem happening for quite a long time now.  

### Expected behavior

I am not sure, but now that it has 
- Taxonomy Product Cat 1
- Taxonomy Product Cat 2
- Taxonomy Product Cat 3
- Taxonomy Product Cat 4
- Taxonomy Product Cat 5
- Taxonomy Product Cat 6
- Taxonomy Product Cat 7
- (Etc... all the way up to 21...) 

There is a lot of templates and I can't really delete them. 

### Actual behavior

Just overwriting as we can do with other templates 

### Steps to reproduce

1. Simply edit the Taxonomy Category in WooCommerce

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://champagnekaelderen.ew-ob.dk
Site address (URL): https://champagnekaelderen.ew-ob.dk
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 205 MB
PHP Time Limit: 300
PHP Max Input Vars: 15000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: bowe_
Total databasestørrelse: 22.58MB
Database datastørrelse: 16.55MB
Database indexstørrelse: 6.03MB
bowe_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
bowe_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
bowe_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
bowe_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_actionscheduler_actions: Data: 0.31MB + Index: 0.39MB + Engine InnoDB
bowe_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_actionscheduler_logs: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
bowe_bowe_giftcards: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_bowe_giftcard_transections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
bowe_elfsight_instagram_feed_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_elfsight_instagram_feed_widgets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_options: Data: 1.09MB + Index: 0.09MB + Engine InnoDB
bowe_postmeta: Data: 3.45MB + Index: 2.98MB + Engine InnoDB
bowe_posts: Data: 9.48MB + Index: 0.39MB + Engine InnoDB
bowe_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
bowe_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_redirection_items: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
bowe_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
bowe_termmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
bowe_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
bowe_term_relationships: Data: 0.31MB + Index: 0.16MB + Engine InnoDB
bowe_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
bowe_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
bowe_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
bowe_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
bowe_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
bowe_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
bowe_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
bowe_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
bowe_wc_product_attributes_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
bowe_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
bowe_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
bowe_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bowe_wpml_mails: Data: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 5
acf-field-group: 3
attachment: 751
cases: 1
nav_menu_item: 33
page: 24
post: 24
producenter: 60
product: 466
qoutes: 1
revision: 696
shop_coupon: 2
shop_order: 11
wp_global_styles: 1
wp_navigation: 1
wp_template: 28
wp_template_part: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Advanced Custom Fields PRO: af WP Engine – 6.1.5
Bowe Blocks: af Bo-we – 1.0
Bowe Events: af Bo-we – 1.0
Bowe Features: af Bo-we – 1.0
Bowe GiftCard: af Bo-we – 1.0
Bowe WooCommerce: af Bo-we – 1.0
Yoast Duplicate Post: af Enrico Battocchi & Team Yoast – 4.5
Shipmondo til WooCommerce: af Shipmondo – 4.1.1
Redirection: af John Godley – 5.3.10
Reepay Checkout for WooCommerce: af reepay – 1.4.59
Regenerere miniaturebilleder: af Alex Mills (Viper007Bond) – 3.1.5
WooCommerce: af Automattic – 7.6.1
WP Mail Logging: af WP Mail Logging Team – 1.11.0

### Inactive Plugins (3) ###

Bowe Marketing: af Bo-we – 1.0
Bowe WooCommerce: af Bo-we – 1.0
Email Previewer for WooCommerce: af AspiringPlugins – 1.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bowe_events (bowe_events)
bowe_giftcard (bowe_giftcard)
external (external)
gift_card (gift_card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: ❌ Siden indeholder ikke [woocommerce_cart] shortcode eller woocommerce/cart blokken.
Checkout: ❌ Siden indeholder ikke [woocommerce_checkout] shortcode eller woocommerce/checkout blokken.
Min konto: #9 - /min-konto/
Vilkår og betingelser: #1207 - /handelsbetingelser/

### Theme ###

Name: Bowe-theme
Version: 1.0
Author URL: https://bo-we.dk
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: bowe-theme/woocommerce/cart/cart-shipping.php
bowe-theme/woocommerce/checkout/form-billing.php version - er udgået. Kerneversionen er 3.6.0
bowe-theme/woocommerce/checkout/form-checkout.php
bowe-theme/woocommerce/checkout/form-coupon.php version - er udgået. Kerneversionen er 7.0.1
bowe-theme/woocommerce/checkout/form-login.php
bowe-theme/woocommerce/checkout/form-shipping.php
bowe-theme/woocommerce/checkout/payment-method.php
bowe-theme/woocommerce/checkout/payment.php
bowe-theme/woocommerce/checkout/review-order.php
bowe-theme/woocommerce/checkout/terms.php
bowe-theme/woocommerce/content-product.php
bowe-theme/woocommerce/content-single-product.php
bowe-theme/woocommerce/emails/admin-cancelled-order.php
bowe-theme/woocommerce/emails/admin-failed-order.php
bowe-theme/woocommerce/emails/admin-new-order.php
bowe-theme/woocommerce/emails/customer-completed-order.php
bowe-theme/woocommerce/emails/customer-invoice.php
bowe-theme/woocommerce/emails/customer-new-account.php
bowe-theme/woocommerce/emails/customer-note.php
bowe-theme/woocommerce/emails/customer-on-hold-order.php
bowe-theme/woocommerce/emails/customer-processing-order.php
bowe-theme/woocommerce/emails/customer-refunded-order.php
bowe-theme/woocommerce/emails/customer-reset-password.php
bowe-theme/woocommerce/emails/email-addresses.php
bowe-theme/woocommerce/emails/email-footer.php
bowe-theme/woocommerce/emails/email-header.php
bowe-theme/woocommerce/emails/email-order-details.php
bowe-theme/woocommerce/emails/email-order-items.php
bowe-theme/woocommerce/emails/email-styles.php
bowe-theme/woocommerce/global/form-login.php
bowe-theme/woocommerce/global/quantity-input.php version 7.2.0 er udgået. Kerneversionen er 7.4.0
bowe-theme/woocommerce/global/wrapper-end.php version - er udgået. Kerneversionen er 3.3.0
bowe-theme/woocommerce/global/wrapper-start.php version - er udgået. Kerneversionen er 3.3.0
bowe-theme/woocommerce/loop/add-to-cart.php version - er udgået. Kerneversionen er 3.3.0
bowe-theme/woocommerce/loop/price.php
bowe-theme/woocommerce/loop/sale-flash.php
bowe-theme/woocommerce/myaccount/dashboard.php version - er udgået. Kerneversionen er 4.4.0
bowe-theme/woocommerce/myaccount/form-add-payment-method.php version - er udgået. Kerneversionen er 7.0.1
bowe-theme/woocommerce/myaccount/form-edit-account.php
bowe-theme/woocommerce/myaccount/form-edit-address.php
bowe-theme/woocommerce/myaccount/form-login.php version - er udgået. Kerneversionen er 7.0.1
bowe-theme/woocommerce/myaccount/form-lost-password.php version - er udgået. Kerneversionen er 7.0.1
bowe-theme/woocommerce/myaccount/form-reset-password.php
bowe-theme/woocommerce/myaccount/lost-password-confirmation.php version - er udgået. Kerneversionen er 3.9.0
bowe-theme/woocommerce/myaccount/my-account.php version - er udgået. Kerneversionen er 3.5.0
bowe-theme/woocommerce/myaccount/my-address.php
bowe-theme/woocommerce/myaccount/my-downloads.php
bowe-theme/woocommerce/myaccount/navigation.php
bowe-theme/woocommerce/myaccount/orders.php
bowe-theme/woocommerce/myaccount/payment-methods.php version - er udgået. Kerneversionen er 2.6.0
bowe-theme/woocommerce/myaccount/view-order.php
bowe-theme/woocommerce/notices/error.php
bowe-theme/woocommerce/notices/notice.php
bowe-theme/woocommerce/notices/success.php
bowe-theme/woocommerce/single-product/add-to-cart/simple.php
bowe-theme/woocommerce/single-product/add-to-cart/variable.php
bowe-theme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
bowe-theme/woocommerce/single-product/add-to-cart/variation.php
bowe-theme/woocommerce/single-product/product-image.php version - er udgået. Kerneversionen er 3.5.1
bowe-theme/woocommerce/single-product/product-thumbnails.php
bowe-theme/woocommerce/single-product/related.php version - er udgået. Kerneversionen er 3.9.0
bowe-theme/woocommerce/single-product/short-description.php
bowe-theme/woocommerce/single-product/up-sells.php version - er udgået. Kerneversionen er 3.0.0

Outdated Templates: ❌
					
					
						Lær hvordan man opdaterer

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-04 19:32:11 +02:00
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Gennemført: 933
Oldest: 2023-04-05 14:40:12 +0200
Newest: 2023-05-04 15:23:01 +0200

Mislykket: 2
Oldest: 2023-01-25 20:18:58 +0100
Newest: 2023-03-20 12:24:22 +0100

Igangværende: 1
Oldest: 2023-05-04 15:41:58 +0200
Newest: 2023-05-04 15:41:58 +0200

### Status report information ###

Generated at: 2023-05-04 15:34:06 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mranden** [comment]
For further understanding I have made a short 2 min loom video, showcasing some of the problems happening due to this 

https://www.loom.com/share/bcd345d6a1fb4e9ca6fca44a456889bf

**Comment by rrennick** [comment]
Hi @mranden,

I wasn't able to reproduce this with the Twenty Twenty-Three theme as it does not have a `Taxonomy Product Cat` template. Could you provide steps to reproduce this behaviour with Twenty Twenty-Three?

**Comment by mranden** [comment]
You are entirely right!
