### ISSUE TITLE
Automate Changelog Generation

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#38125]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In order to make working with changelogs easier, we should implement a feature for automatically generating them from the PR description. We should add a GitHub Action that:

- Validation
  - The PR description should have a section for entering the changelog.
  - If the changelog does not follow the correct format we can fail a PR check.
  - PRs should NOT require a changelog for things that won't ever be published. Markdown files, `.github`, configuration like ESLint, etc. Only code changes that are shipped to users should trigger it.
  - If there are already changelog files present we should validate them using the JP changelogger and error if they're invalid.
- Parsing
  - Any `push` or editing of the PR description should trigger this.
    - **Instead, only run prior to the merge taking place. This avoids conflicts with existing changelog files.**
  - Parse the format so we can construct a JP Changelogger command from it.
  - Scan for any projects that have been changed (we might even be able to use `pnpm --filter=trunk...HEAD`?) and check if they've got files that have changed that are valid.
  - If they do and there isn't already a changelog file from this PR, run the command we generated and add the one from the PR description.
- Remove local changelog check and make the generation optional outside of the PR checks.

As is standard now, we should put whatever makes sense into the `monorepo-utils` CLI tool. I might suggest it going as far as using GitHub's API to review the PR's description and avoid needing to do any parsing in the GitHub Action. Maybe instead of using the JP changelogger to make the changelog we can just use [this script](https://gist.github.com/rrennick/56285a3d3580aa1c5d38d50d9ba5a6cd).

Given the scope of this issue, it may even make sense to just remove the JP changelogger entirely? There's some meat to discuss here.

**Comment by ObliviousHarmony** [comment]
One of the caveats raised by @jonathansadowski is dealing with conflicts between changelog files made using the tool locally and the parsing in the GitHub Action. We can probably resolve that by not generating the changelog file until the PR is being merged, whatever that action is. Right before the PR gets merged it can generate the changelog and commit it to the PR.

I think the rest of the above still works with this change, we just have to move the parsing from the PR push/edit step to the merge step. We can then worry about the validation only during development and have that as a required check.

**Comment by samueljseay** [comment]
@ObliviousHarmony what if we just didn't run the tool (in CI) on packages that had a changelog entry generated? maybe we can determine via the diff of changes? Would that get around the problem?

**Comment by ObliviousHarmony** [comment]
Well @samueljseay, the issue already covers that we should only generate changelog files when one hasn't already been written for a given package. This is only for generating changelog files automatically in cases where one doesn't already exist.

If you're talking about the conflict with generating the files on `push` vs `merge`, this is because identifying the commit author and deciding when to generate changelog files is more complicated:

* PR Creation
  * Identify any project that has changed.
  * Check for a changelog file.
  * If no changelog file is present, generate one according to the PR description. Use a commit author associated with the GitHub bot.
* PR Update
  * If a new package has changed, generate a changelog file according to the PR description.
  * If a package has no longer changed, delete the changelog file (only if the latest author is the bot)
* Description Update
  * For all the packages that have changed, find the associated changelog entry.
  * If the latest author is the bot, update the changelog entry.
* When we say "latest author" here we are referencing the fact that a developer could modify the changelog file themselves. If we're scanning the diff, we need to pay close attention to the last person who edited the file and make sure it was the bot.
   * This also has nice UX imo because you won't see changelog files in the PR that you didn't make in it.

If however, we do it on merge:

* For all the packages that have changed, generate a changelog file if one does not already exist.

It's true that there aren't any problems that can't be worked through, but, it feels like doing it on merge might be simpler. With that said, we might not even be able to do it on merge. I don't _know_ that there is a GitHub Action hook we can use. I think we could make a commit _after_ the merge (on PR close if merged), but, that feels a lot harder to deal with in a PR revert because, with changelog files as-is, you can just delete the files that are in the PR. If we can't generate it before merge then we will have to take the more complicated approach anyway.

**Comment by samueljseay** [comment]
@ObliviousHarmony thanks for taking the time to dive into that, yes I can see where the complexity lies.

Yes my first thought after reading this was maybe we can run a job after the merge, but I think that has a lot of complexity too. 🤔 

If we foresee a lot of complexity, I wonder if it makes sense to step back a little and try something simpler first (still acknowledging we should do this later)

One idea I have (with naivety included lol), is what if we improved the CLI changelogger such that the git hook instead of complaining about changelogs you haven't added, just adds them for you? Or maybe its so interactive that it just prompts you: "whats the reason for your change"

Maybe with something like that in place we could evaluate if it reduces the friction enough?

Just a thought ❤️ 😄

**Comment by psealock** [comment]
>One idea I have (with naivety included lol), is what if we improved the CLI changelogger such that the git hook instead of complaining about changelogs you haven't added, just adds them for you? Or maybe its so interactive that it just prompts you: "whats the reason for your change"

That works, but doesn't satisfy the initial need for this: Anyone can add a changelog without our tooling, ie from the web.

This might be overkill but we could create a PR targeting the author's PR branch and tag them as reviewers. The timing of it all could get tedious and extra PRs creates noise.

Another step back we can take in complexity would be to simply provide a field and a checkbox for PR authors to use:

 - [ ] Generate change log entry automatically for all affected projects
``` 
Enter changelog here ( this is supposed to look like an input :) )
```
Then we remove all ambiguity. If the box is checked, we place that as the changelog for all affected projects regardless and we communicate that. Include further instructions if you want to used the CLI tool for finer control. I think this covers 100% of use cases where we want to add a changelog to PRs and using the CLI is too cumbersome, ie community contributions.

What do you think @ObliviousHarmony @samueljseay ?

**Comment by samueljseay** [comment]
> That works, but doesn't satisfy the initial need for this: Anyone can add a changelog without our tooling, ie from the web.

naturally, but I'm sidestepping by asking: would there still be a need for adding from web if it was frictionless to add changelogs when pushing a change? I guess maybe its not enough if for example the author adds a changelog with a poor description?

> Another step back we can take in complexity would be to simply provide a field and a checkbox for PR authors to use:

I like this idea but is it possible? Do we always have needed permission to push commits to a contributor PR?

**Comment by ObliviousHarmony** [comment]
> would there still be a need for adding from web if it was frictionless to add changelogs when pushing a change?

To be honest, I actually thing that the process is already painless. In the `git` hook it gives you a clear error about what has happened _and_ a command you can copy/paste to write the changelog. This is a _very_ small thing to have to do and I don't think that's the problem.

Based on the feedback we've received from Proton it appears that _many_ pull requests seem to be authored using the web editor instead of through a local clone. When they don't even use the local tools in the first place there isn't very much that we can do. The main reason that this issue exists is to solve the problem of adding changelogs to pull requests that don't have them without having to pull down the code and manually create one. This convenience ends up serving multiple audiences, though, and we can replace the local execution of the tool almost entirely.

> If the box is checked, we place that as the changelog for all affected projects regardless and we communicate that. Include further instructions if you want to used the CLI tool for finer control.

This is a neat idea, I like this.

---

One question too is whether or not the action can even make commits to the pull request? Technically the key is read-only, but, I wonder if it would be able to make commits to itself?

**Comment by psealock** [comment]
>One question too is whether or not the action can even make commits to the pull request?

The committer would need to check this box

<img width="360" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/d9280c38-8a0a-4604-9a54-ec06ea59659f">

I'm just not sure if Github Actions bot can as well, testing this out now.

EDIT:

Getting Error: [Author identity unknown](https://github.com/woocommerce/woocommerce/actions/runs/4953843430/jobs/8861760936) error while checking out the remote branch from Github Actions and authenticating git using `GITHUB_TOKEN`. At the very least we could make this a CLI tool for maintainers to easily add changelogs.

@ObliviousHarmony didn't the previous workflow (before Jetpack Changelogger) perform this task? Did it work on community contributions?

**Comment by psealock** [comment]
Ok, I've got this working. One just needs to sign in:

```js
await git.raw(
    'config',
    '--global',
    'user.email',
    'psealock@gmail.com'
);
await git.raw( 'config', '--global', 'user.name', 'paul sealock' );
```
I'll grab this issue

**Comment by ObliviousHarmony** [comment]
I've gone ahead and re-opened this issue. Technically https://github.com/woocommerce/woocommerce/pull/38510 is also part of the acceptance criteria, so, we will wait for that to get merged.

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/38510
