### ISSUE TITLE
Product Block Editor Tutorial: Create initial product block template

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38143]
## Description

We should create an initial product block template package, similar to the one Gutenberg provides [here](https://github.com/WordPress/gutenberg/tree/trunk/packages/create-block-tutorial-template).  We could mimic the one from Gutenberg mostly.

This should work by running `npx  @wordpress/create-block --template ./woocommerce-monorepo/packages/js/create-product-block-tutorial-template`.

See the `create-block` doc for further documentation around this: [create-block doc](https://github.com/WordPress/gutenberg/blob/trunk/packages/create-block/README.md). Specifically, see the `--template` param.

The `woocommerce_register_post_type_product` filter should be used to modify the `template` value for the `product` post type to add the the demo block to the product form at the end of the `Basic details` section.

The demo block should not be interactive. Adding interactivity and save support will be covered in a follow-up issue.

How the parameter for the `woocommerce_register_post_type_product` filter is structured can be seen in the `woocommerce/includes/class-wc-post-types.php` file.

## Acceptance criteria

- [ ]  running `npx  @wordpress/create-block --template ./woocommerce-monorepo/packages/js/create-product-block-tutorial-template` creates a demo block plugin project.
- [ ] The project is buildable with standard commands such as `npm run build`.
- [ ] The project has commands to allow `wp-env` to be used to quickly setup a local environment to test the project.
- [ ] The project output files should be PHP, TS, SCSS, and JSON. 
- [ ] The demo block is visible in the product block editor at the end of the `Basic details` section.
- [ ] The demo blocks renders a simple message to show that it is in the editor.

**Comment by mattsherman** [comment]
I'm grabbing this one.
