### ISSUE TITLE
updating order status but payment status get changed

### ISSUE THREAD

**Issue by manojlakhe2020** [woothemes/woocommerce#38145]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am updating order status using WooCommerce api, but payment status get update instead of order status.
Implemented as per the WooCommerce documents but not working for me.

### Expected behavior

order status must be changed

### Actual behavior

Order payment status get change instead of order status

### Steps to reproduce

NA

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://allindiacuisine.com
Site address (URL): https://allindiacuisine.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.41-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 31.77MB
Database Data Size: 26.87MB
Database Index Size: 4.90MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.42MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 3.42MB + Index: 2.75MB + Engine InnoDB
wp_posts: Data: 18.14MB + Index: 0.31MB + Engine InnoDB
wp_remove_menu_admin_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 465
custom_css: 2
customize_changeset: 1
et-event: 9
footer: 1
menu: 160
nav_menu_item: 44
page: 13
post: 31
product: 115
revision: 410
shop_coupon: 1
shop_order: 30
viwec_template: 14
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Contact Form 7: by Takayuki Miyoshi – 5.7.5.1
Date Time Picker for Contact Form 7: by Ruhul Amin – 1.1.1
Login/Signup Popup: by XootiX – 2.3
Enovathemes add-ons: by Enovathemes – 2.7
Food Store - Online Food Delivery & Pickup: by WP Scripts – 1.4.7.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Order Tip for WooCommerce: by Adrian Emil Tudorache – 1.3.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Remove admin menus by roles: by InfoD74 – 1.35
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.5
WooCommerce Stripe Gateway: by WooCommerce – 7.3.0
WooCommerce: by Automattic – 7.5.1 (update to version 7.6.1 is available)
WP Mail SMTP: by WPForms – 3.7.0
WPvivid Backup Plugin: by WPvivid Team – 0.9.86

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.1
Email Template Customizer for WooCommerce: by VillaTheme – 1.1.21
Woo Add Custom Fee: by wpexpertsio – 1.6

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: ❌ Page not set
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Goodresto Child
Version: 1.0
Author URL: https://enovathemes.com
Child Theme: ✔
Parent Theme Name: Goodresto
Parent Theme Version: 3.8
Parent Theme Author URL: https://enovathemes.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: /home/h82jsfd0p3nk/public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php version 4.1.0 is out of date. The core version is 7.0.1
/home/h82jsfd0p3nk/public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php version 4.1.0 is out of date. The core version is 7.0.1

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-06 05:24:19 -04:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Complete: 497
Oldest: 2023-04-05 03:30:50 +0000
Newest: 2023-05-05 15:44:29 +0000

Failed: 6
Oldest: 2023-03-13 05:27:30 +0000
Newest: 2023-05-01 15:20:15 +0000

Pending: 2
Oldest: 2023-05-05 17:27:44 +0000
Newest: 2023-05-08 20:18:23 +0000

### Status report information ###

Generated at: 2023-05-05 11:56:49 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @manojlakhe2020,

Thanks for the report. Could you please include the API calls that you're making, along with the data that you're passing so that we can better try to reproduce this issue?

**Comment by manojlakhe2020** [comment]
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://allindiacuisine.com/wp-json/wc/v3/orders/13733',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'PUT',
  CURLOPT_POSTFIELDS =>'{
  "status": "completed"
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json',
    'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Cookie: service_date=2023-04-27; service_time=1%3A15%20pm; service_type=pickup'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
$res = json_decode($response);

**Comment by manojlakhe2020** [comment]
Please fix this issue as per as possible because I stuck and project is pending.
Is there another way to change order status using api?

**Comment by rrennick** [comment]
Hi @manojlakhe2020,

I tested this with the latest version of WooCommerce. When I PUT `{"status":"completed"}`, the response shows that it was updated:

```
{
  "id": 3265,
  "parent_id": 0,
  "status": "completed",
...
```

Could you test with only WooCommerce active?

**Comment by softatechnologies** [comment]
"status": "completed" updated status is payment status.

Please check status is "accepted" using api then you will see it will update payment status not order status.

**Comment by rrennick** [comment]
> Please check status is "accepted" using api then you will see it will update payment status not order status.

@softatechnologies `accepted` is not a WooCommerce core order status. I suggest you follow up with support for the extension that's adding that status.

**Comment by rrennick** [comment]
> Could you test with only WooCommerce active?

Closing this for lack of feedback on original issue. If you cn provide steps to reproduce this with only WooCommerce active, please open a new issue.
