### ISSUE TITLE
Product Block Editor Tutorial: Add hook to include block in product template

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38144]
**Description**

This is a continuation of #38143. We should add a filter for the `woocommerce_register_post_type_product` to modify the `template` value to add the render the newly registered block within the product form. You can add it to the **Basic Details** section.

This issue will only handle the rendering of the new block within the forum, turning this into a field will be a follow up issue.

How `woocommerce_register_post_type_product` is structured can be seen in the `woocommerce/includes/class-wc-post-types.php` file.

**Acceptance criteria**

- [ ] The sample block generated as part of #38143 should be visible within the product block edit screen in the Basic Details section.

**Comment by mattsherman** [comment]
Closing this issue -- merged into #38143
