### ISSUE TITLE
Extension Example: Create sample block within example and add to product template

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38156]
**Description**

Follow up from #38155
This would be a follow up of the previous issue, where we will update the `add-new-product-field` example to register a new block and render it within the product block editor.
You can follow this tutorial to create a basic block: https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/

You may also want to look at some of our more basic blocks as an example within `product-editor` package, like the `collapsable` ([link](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/product-editor/src/blocks/collapsible)) block, but this issue is only to render it within the product block editor, so you can keep it simple.

You can render the block by adding it to the template config by modifying the `woocommerce_register_post_type_product` filter. You can add it to the **Basic Details** section.

This issue will only handle the rendering of the new block within the forum, turning this into a field will be a follow up issue.

How `woocommerce_register_post_type_product` is structured can be seen in the `woocommerce/includes/class-wc-post-types.php` file.

**Acceptance criteria**

- [ ] The sample block should be visible within the product block edit screen in the Basic Details section.

**Comment by octaedro** [comment]
To tackle this issue, we can add a link pointing to [these docs](https://github.com/woocommerce/woocommerce/issues/38143)

**Comment by louwie17** [comment]
Closing this in favour of using: https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/create-product-editor-block
