### ISSUE TITLE
Extension Example: Create initial product block example

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38155]
**Description**

We should create a new extension example that demos how to add a new field to the current product block editor.
This will cover the bootstrapping of this.
Currently users can generate an example by running `WC_EXT=add-task pnpm --filter=woocommerce/client/admin example` ( see `plugins/woocommerce-admin/docs/examples/extensions` for more info.

**Acceptance criteria**

- [ ] `WC_EXT=add-new-product-field pnpm --filter=woocommerce/client/admin example` should generate a new `add-new-product-field` folder within the `plugins` folder with the initial bootstrap code. Outputting a `console.log` with `Hello World` :)

**Comment by octaedro** [comment]
To tackle this issue, we can add a link pointing to [these docs](https://github.com/woocommerce/woocommerce/issues/38143)

**Comment by louwie17** [comment]
Closing this in favour of using: https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/create-product-editor-block
