### ISSUE TITLE
PHP 8.x Support Timeline

### ISSUE THREAD

**Issue by nickweisser** [woothemes/woocommerce#38162]
I couldn't find any official statement regarding PHP 8 support for WooCommerce. Only [minimum requirements](https://woocommerce.com/document/update-php-wordpress/) are mentioned. Since PHP 7.4 security updates ended in 2022, official PHP 8.x support for WooCommerce would be awesome. I heard something about unofficial PHP 8.0 support. Would be great if you could shed some light about the PHP 8.1 and 8.2 roadmap respectively, since the active support period for PHP 8.0 will end in [6 months](https://www.php.net/supported-versions.php), too.

**Comment by rrennick** [comment]
Hi @nickw108, Thanks for the bump.

> I couldn't find any official statement regarding PHP 8 support for WooCommerce. Only [minimum requirements](https://woocommerce.com/document/update-php-wordpress/) are mentioned.

WordPress offers [beta support](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) for all PHP 8.X versions. WooCommerce cannot commit to full compatibility / support until WordPress does. However, we work on adding support to the best of our capacity.

We are working on an update to our roadmap. I've added this issue to our task list.

**Comment by nickweisser** [comment]
Thanks!

**Comment by lkraav** [comment]
What PR was this closed by @barryhughes?

**Comment by barryhughes** [comment]
None: this specific issue isn't reporting a bug or asking for a technical fix, as I understand it.

**Comment by barryhughes** [comment]
To add some more to this: we're *always* striving to stay current with PHP (and other requirements like MySQL). At this stage, many of us are using PHP 8.x as our daily driver, and though it may certainly have been useful at an earlier point, I don't think any kind of further official statement is really going to be particularly useful.
