### ISSUE TITLE
Improve product_attributes_add tracks event

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#38171]
# Description

The Tracks event `product_attributes_add` that is called in the [product screen](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts#LL543C1-L543C1) has some issues on the way it's implemented right now.

We should remove the `local_attributes` attribute since arrays are not supported, and add the following attributes:

- total_attributes_count: the total number of attributes that were saved
- local_attributes_count: the total number of local attributes that were saved
- global_attributes_count: the total number of global attributes that were saved
- visible_product_page: track how many attributes were saved with the checkbox checked/unchecked. True/False or Null (when the attribute is created on the Attributes page)
- used_variations: track how many attributes were saved with the checkbox checked/unchecked. True/False or Null (when the attribute is created on the Attributes page or when the checkbox isn't visible in cases such as simple products).

**Comment by pmcpinto** [comment]
@octaedro do you think it will be possible to get this in 7.8?
