### ISSUE TITLE
Remove assertion in afterAll hook in create-post.spec

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#38195]
We can probably remove [this](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/create-post.spec.js#L30) assertion because:

- it looks like we're verifying the response of WP's "delete post" endpoint, which we shouldn't because we're not testing the WP endpoint anyway. We'll just have to trust that it would work, since it's an endpoint that we don't have control of.
- before and after hooks probably don't need any kind of assertions

**Comment by adimoldovan** [comment]
The `afterAll` hook mentioned in this issue no longer exists, the spec was refactored and currently uses fixtures. The fixture does not have the check on the delete api call response.

I will close this one.
