### ISSUE TITLE
Try using include dirs (as opposed to exclude) to speed up make-pot

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#38192]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently we're running `make-pot` with a series of `exclude` paths. This results in memory exhaustion if you do not increase your memory limit in `php.ini`. @rrennick suggested using `include` as opposed to `exclude` results in a quicker execution that doesn't exhaust lower memory limits.

- [ ] Look into previous attempt to use `include`, why was it rejected?
- [ ] Try switching to `include`.
- [ ] Ensure that there aren't any negative side-effects.

p1683642474849539-slack-C02GB41LGHM

**Comment by rrennick** [comment]
This was my [PR](https://github.com/woocommerce/woocommerce/pull/25984) that prompted the update.
