### ISSUE TITLE
Analytics are not showing correct data on 7.6.1 from 7.3.0

### ISSUE THREAD

**Issue by mrkrehman** [woothemes/woocommerce#38190]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I recently update to 7.6.1 and woocommerce analytics overview doesn't show the actual orders and their amount. I had staging server where I still used 7.3.0, then I placed and order there and it works fine. Then I update the plugin even on staging server and place another order and now it is showing 1 order.

### Expected behavior

Must show the actual order count and order value

### Actual behavior

Showing wrong order count

### Steps to reproduce

1. Update the plugin to 7.6.1
2. Place an order from website
3. Check the Analytics->overview

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://caliber.com.pk
Site address (URL): https://caliber.com.pk
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.32
PHP Post Max Size: 499 MB
PHP Time Limit: 899
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 499 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wpfa_
Total Database Size: 766.99MB
Database Data Size: 480.96MB
Database Index Size: 286.03MB
wpfa_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
wpfa_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB + Engine InnoDB
wpfa_woocommerce_order_itemmeta: Data: 44.58MB + Index: 38.13MB + Engine InnoDB
wpfa_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_actionscheduler_actions: Data: 2.02MB + Index: 2.33MB + Engine InnoDB
wpfa_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_actionscheduler_logs: Data: 2.02MB + Index: 1.31MB + Engine InnoDB
wpfa_bulkgate_module: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_bv_ip_store: Data: 0.33MB + Index: 0.31MB + Engine InnoDB
wpfa_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_cartflows_ca_cart_abandonment: Data: 10.56MB + Index: 0.28MB + Engine InnoDB
wpfa_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_cf_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_commentmeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wpfa_comments: Data: 17.55MB + Index: 16.00MB + Engine InnoDB
wpfa_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_acct_bills: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_bill_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_bill_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_cash_at_banks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_chart_of_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_currency_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_expenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_expense_checks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_expense_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_financial_years: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoice_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoice_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoice_details_tax: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoice_receipts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_invoice_receipts_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_journals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_journal_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_ledgers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_ledger_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_ledger_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_ledger_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_opening_balances: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_payment_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_pay_bill: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_pay_bill_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_pay_purchase: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_pay_purchase_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_people_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_people_trn: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_people_trn_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_product_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_product_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_product_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_purchase: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_purchase_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_purchase_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_taxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_tax_agencies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_tax_agency_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_tax_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_tax_cat_agency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_tax_pay: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_transfer_voucher: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_trn_status_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_acct_voucher_no: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_audit_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_erp_company_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_crm_activities_task: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_crm_contact_group: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_crm_contact_subscriber: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_erp_crm_customer_activities: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wpfa_erp_crm_customer_companies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_crm_save_email_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_crm_save_search: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_holidays_indv: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_announcement: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_erp_hr_dependents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_hr_depts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_designations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_education: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_hr_employees: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfa_erp_hr_employee_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_hr_employee_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_employee_performance: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_hr_holiday: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_leaves: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_hr_leave_entitlements: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_hr_leave_policies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_hr_leave_requests: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfa_erp_hr_work_exp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_peoplemeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpfa_erp_peoples: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpfa_erp_people_types: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_erp_people_type_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_user_leaves: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_erp_wc_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_erp_wc_order_product: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_mnp_courier: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpfa_mnp_courier_load_sheet: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_mnp_courier_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_mnp_courier_sheet: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_options: Data: 6.03MB + Index: 0.20MB + Engine InnoDB
wpfa_pm_activities: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_pm_assignees: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_pm_boardables: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_pm_boards: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_pm_capabilities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_category_project: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_pm_comments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_pm_files: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_pm_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_pm_projects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_roles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_role_project: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_role_project_capabilities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_pm_role_project_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_pm_role_user: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_pm_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_pm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_pm_task_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_pm_task_type_task: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_postmeta: Data: 165.30MB + Index: 135.05MB + Engine InnoDB
wpfa_posts: Data: 15.48MB + Index: 8.91MB + Engine InnoDB
wpfa_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_remove_menu_admin_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpfa_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfa_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpfa_uap_action_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpfa_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpfa_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpfa_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfa_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpfa_uap_trigger_log_meta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpfa_usermeta: Data: 14.52MB + Index: 16.03MB + Engine InnoDB
wpfa_users: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wpfa_viwebpos_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_customer_lookup: Data: 3.52MB + Index: 3.00MB + Engine InnoDB
wpfa_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpfa_wc_order_product_lookup: Data: 5.52MB + Index: 8.06MB + Engine InnoDB
wpfa_wc_order_stats: Data: 7.48MB + Index: 4.53MB + Engine InnoDB
wpfa_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_wc_point_of_sale_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_point_of_sale_sale_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_poin_of_sale_tabs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_poin_of_sale_tabs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpfa_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_woocommerce_pos_drawer_transaction: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_pos_invoice_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_pos_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_woocommerce_pos_outlets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_pos_outlet_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_pos_outlet_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_woocommerce_pos_payments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wpforms_entries: Data: 114.66MB + Index: 1.52MB + Engine InnoDB
wpfa_wpforms_entry_fields: Data: 56.59MB + Index: 43.64MB + Engine InnoDB
wpfa_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_wpforms_tasks_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpfa_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_wt_iew_action_history: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wpfa_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpfa_yoast_indexable: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpfa_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpfa_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpfa_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpfa_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
attachment: 508
cartflows_flow: 1
cartflows_step: 2
custom_css: 3
elementor_library: 2
elementor-hf: 1
is_search_form: 1
nav_menu_item: 23
page: 11
pos_outlet: 1
pos_receipt: 1
pos_register: 1
pos_session: 2
pos_temp_order: 1
post: 2
product: 63
product_variation: 183
revision: 838
shop_coupon: 1
shop_order: 35037
shop_order_refund: 3
uo-recipe: 1
wp_global_styles: 1
wpforms: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Starter Templates: by Brainstorm Force – 3.2.1
Joinchat: by Creame – 4.5.20
Creative Mail by Newfold Digital: by Newfold Digital – 1.6.7
Elementor: by Elementor.com – 3.13.0
Jetpack: by Automattic – 12.1
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.97
M&P Courier add-on for WooCommerce: by Team MatechCo – 1.5.7
Meta pixel for WordPress: by Facebook – 3.0.10
Remove admin menus by roles: by InfoD74 – 1.35
Rider Shipping: by Mean3 Pvt Ltd – 1.0.2
Trax Logistics: by Trax Logistics – 1.7
WebPOS – WooCommerce POS – Point of Sale: by VillaTheme – 1.0.7
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.24
XT Floating Cart for WooCommerce: by XplodedThemes – 2.7.3
WooCommerce: by Automattic – 7.6.1
Yoast SEO: by Team Yoast – 20.7
WPForms: by WPForms – 1.7.2

### Inactive Plugins (3) ###

Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.13

Hello Dolly: by Matt Mullenweg – 1.7.2
Tawk.to Live Chat: by Tawkto – 0.7.2

### Dropin Plugins (1) ###

object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.18.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: PKR (₨)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #38 - /store/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 1399.9.4
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-10 11:36:56 +05:00
Options: ✔
Notes: 110
Onboarding: completed

### Action Scheduler ###

Complete: 4,588
Oldest: 2023-04-08 17:58:32 +0500
Newest: 2023-05-09 15:32:45 +0500

Failed: 55
Oldest: 2021-04-21 15:59:44 +0500
Newest: 2023-04-29 20:38:05 +0500

Pending: 10
Oldest: 2023-05-10 01:53:50 +0500
Newest: 2023-05-13 20:38:12 +0500

### Status report information ###

Generated at: 2023-05-09 17:57:07 +05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@mrkrehman Could you let us know whether you are still seeing this with the latest version of WooCommerce with no other plugins active and a default theme?
