### ISSUE TITLE
[MVP QA #1] Visual: spacings

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38202]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to typography, spacing, and other small visual details throughout the form.

**Note** This should also be tested with the StoreFront theme as it adds some styling to the blocks, see this fix for the summary block for example: https://github.com/woocommerce/woocommerce/pull/38251

**Acceptance criteria**

- [x] We should update the margin-left on the buttons in the top bar from 16px to 8px.
- [x] Spacing between the last field and the next sub section or between field groups and the "Advanced" button should be 32 pixels.
- [x] The padding around the subsections should be 32px 0 0 0.
- [ ] We need 4 px of space between a subsection's title and the description.
- [x] In the feedback form, can we fix the buttons at the bottom or prevent the modal from scrolling?
- [x] On mobile, the left and right body margins should be 32 px.
- [x] All modals should now have 8 px window radius.
- [x] The help icon in checkboxes small, detached from the item label, and vertically misaligned. Left margin of 4 px, no vertical adjustment; somehow it has a -2px set for the top margin).
- [x] The inner padding in the tab in the top bar should be 12px, not 16px.
- [x] In the edit product link modal, let's set this modal’s width to 650 px and remove the line separating the header from the contents.
- [x] When the product is in a draft state, the button in the top bar should say `Add`, not `Save`. It should change into `Update` once it's published on the store.

cc @pmcpinto

**Comment by louwie17** [comment]
@jarekmorawski for the last item on the acceptance criteria, should we only show `Save` when a product status is published?

**Comment by jarekmorawski** [comment]
Yes, I updated the AC.

- If not published: `Add`
- If published: `Update`
