### ISSUE TITLE
[MVP QA #1] Inventory tab

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38209]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to the `Inventory` tab.

**Acceptance criteria**

- [x] Available quantity: users should be able to increase/decrease the number using arrow keys.
- [x] Threshold: it should be a number field not accepting letters.
- [x] Threshold: users should be able to increase/decrease the number using arrow keys.

cc @pmcpinto

**Comment by louwie17** [comment]
Closing this, fixed by this PR: https://github.com/woocommerce/woocommerce/issues/38244
And available quantity seems to allow for increasing/decreasing using arrow keys.
