### ISSUE TITLE
[MVP QA #1] General tab: Description

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38207]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to the `General` tab.

**Acceptance criteria**
- [x] https://github.com/woocommerce/woocommerce/issues/39189
- [x] Form: the preview strips most of the styling from the description, including fonts and formatting. If we can’t show it accurately, it’s better to remove it. **This should be fixed, we should re-check this**

Done as part of other issues:
- [ ] Form: we shouldn’t show the preview of the description when it’s empty (currently, it shows up, and the button changes to “Edit description” even if the user opens the description and closes it without taking action)
- [ ] Modal: When the user enters the editor for the first time, they should see the welcome message and the onboarding tour included in the current post editor.

cc @pmcpinto

![Image](https://github.com/woocommerce/woocommerce/assets/2240960/8198e48d-374e-4ce1-90a4-a110426d7b91)

**Comment by pmcpinto** [comment]
AC ordered by priority

**Comment by mattsherman** [comment]
Split the modal scrolling-related bits out into https://github.com/woocommerce/woocommerce/issues/39189
