### ISSUE TITLE
[MVP QA #1] General tab: Categories

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38205]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to the `General` tab.

**Acceptance criteria**
- [x] Dropdown: the dropdown covers the field when the dropdown is positioned near the bottom of the page. https://github.com/woocommerce/woocommerce/issues/39810
- [x] Create category modal: the parent category dropdown doesn’t open when I navigate to it using the keyboard. It only shows up when I start typing, but it doesn't match the field width (it should).
- [x] Dropdown: we duplicate the category’s name after creating it (the field should clear after the user closes the modal).
- [x] Dropdown: we don’t support all characters in our dropdown component (tested with `&`).
- [ ] Dropdown: when not selected, parent categories should have checkboxes in the `mixed` state to indicate that one of their children is selected.
- [x] Dropdown: the Create new button should be fixed at the bottom of the list.
- [x] Create category modal: the spacing between these fields should be 16 px.
- [ ] Create category modal: instead of the dropdown, we should show the parent category selection as a tree. Design: 5sAIeTRd9Yp7nSCT33BAWz-fi-175-116510&t=AGvUT8r7RUIqWJTk-4

**Comment by pmcpinto** [comment]
AC ordered by priority

**Comment by pmcpinto** [comment]
The 1st item in the AC can be prioritized for cycle 38. The dropdown has an odd behavior when it's positioned near the bottom. For example, it doesn't show the search option:


https://github.com/woocommerce/woocommerce/assets/3380168/314ed706-5dc1-4603-a120-01fff478f21d
https://github.com/woocommerce/woocommerce/assets/3380168/806a0905-87c5-4cbb-a6fa-9695224de8c7


The rest of the AC items can wait until 39/40

**Comment by nathanss** [comment]
@jarekmorawski 

>  Create category modal: instead of the dropdown, we should show the parent category selection as a tree.

There can only be one parent category, so I don't think showing the checkboxes (like the design) makes sense. We do have a bug regarding the tree structure not showing, which will be fixed soon. Are you OK with it looking like the below?

<img width="716" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13437655/8dbc8311-738a-4ed5-b868-076a368b5db4">


> Dropdown: when not selected, parent categories should have checkboxes in the mixed state to indicate that one of their children is selected.

The category field is unique in the sense that you can select a child without selecting the parent. I understand why we could benefit from the "mixed" state, but this can also create some confusion. Would there be any UI difference between the following selections?

<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13437655/ca80bfbc-6d1c-46dc-89d2-984f40fb5d39">

<img width="720" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13437655/9fcc649b-3772-4702-abe3-db49137a87dc">

I'm assuming that we don't want to change that behavior from the legacy editor. I'm not sure that's the case.

**Comment by nathanss** [comment]
cc'ing @pmcpinto since Jarek is away

**Comment by pmcpinto** [comment]
> Are you OK with it looking like the below?

This is a good solution. Can you share an example where the tree has 3 or 4 levels?

> I understand why we could benefit from the "mixed" state, but this can also create some confusion. Would there be any UI difference between the following selections?

Which one seems more confusing to you?

**Comment by nathanss** [comment]
@pmcpinto 

> Can you share an example where the tree has 3 or 4 levels?

<img width="680" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13437655/885c3dfc-f2b1-4504-ba00-adcc904a7cc4">

> Which one seems more confusing to you?

I'm not sure if I get the question. Do you mean between the two screenshots? I'm just trying to figure out how both would look after introducing the "mixed" state, since one possible interpretation is that they would look the same, but they are not the same. On the first screeshot, Parent is selected, and on the second one, the Parent is not selected.

**Comment by pmcpinto** [comment]
Thanks for the clarification. I agree that the experience displayed in the 1st screenshot is confusing if the user didn't select the parent category. What if we open the parent category by default when there's at least 1 child category selected?

**Comment by jarekmorawski** [comment]
> Would there be any UI difference between the following selections?

Yes, the parent would have a mixed state because 1) it's not added to the product 2) some of its children are added to the product. If the user specifically selected the parent as well, it'd receive the standard checked state and be added to the product.

Frankly, I'd keep the checkboxes since they help get an overview of added items and their structure (they also indicate that the user can select multiple items without closing the dropdown list).

> What if we open the parent category by default when there's at least 1 child category selected?

That'd work!

**Comment by pmcpinto** [comment]
@jarekmorawski I think we should close this one and open a new issue with the AC that needs to be completed. Does that make sense?

**Comment by jarekmorawski** [comment]
Makes sense! [Created a new issue](https://github.com/woocommerce/woocommerce/issues/41659).
