### ISSUE TITLE
Product Block Editor: Saving buttons stuck when clicking preview and saving failed

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38219]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Blocked by: https://github.com/woocommerce/woocommerce/issues/38215 and might be fixed by validation work: https://github.com/woocommerce/woocommerce/issues/37984

Saving buttons are locked in the product editor if trying to preview the product that has the same slug like any other existing product, like in this case I wanted to create new product with test slug and clicked preview button, infinite saving loop present.

![89P9QW.gif](https://github.com/woocommerce/woocommerce/assets/2240960/a9d2403e-eb15-404a-820e-b87281139886).

It looks like this happens when the product fails to save when attempting to preview the product.

**Acceptance criteria**

- [ ] Save buttons should re-enable after the failed to save notice showed up ( we may also want to show an additional notice around failed to preview, or replace the failed to save with failed to preview - depending on what was clicked ).

**Comment by joshuatf** [comment]
Tested and this will be resolved by https://github.com/woocommerce/woocommerce/pull/38307.
