### ISSUE TITLE
Product Block Editor: `Please enter valid date` warning after clicking reset

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38213]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When I click reset link in the scheduled sale popup, I see the warning “Please enter a valid date” for no reason, the date is valid of course. This is happening for the From field, but not for To field.
![buHClZ.png](https://github.com/woocommerce/woocommerce/assets/2240960/92a2092d-906b-495e-99da-ec01b4de7cab))

**Acceptance criteria**

- [ ] “Please enter a valid date” should not be present when clicking `reset` and a valid date is shown in the input.

**Comment by peterfabian** [comment]
Hey, assigned the focus labels to remove it from our filters, please adjust as necessary. Thanks!
