### ISSUE TITLE
Woocommerce product tab locked Version 7.7.0

### ISSUE THREAD

**Issue by TamasFelix** [woothemes/woocommerce#38216]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello, today I updated the woocommerce plugin Version 7.7.0, after the update I tried to add a new product to the site and product tab locked

![mywebsite](https://github.com/woocommerce/woocommerce/assets/50567469/7c6240be-1368-45f6-9e12-b39ff2208bf1)

### Expected behavior

also modified the product page, where is the short description
https://batoaneproteice.ro/produs/weider-l-carnitine-liquid-20-fiole/

### Actual behavior

I do not know

### Steps to reproduce

I do not know

### WordPress Environment

ok

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @TamasFelix,

Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

**Comment by TamasFelix** [comment]
Hello, thanks for help, 
find a solution here :
https://wordpress.org/support/topic/woocommerce-product-tab-locked-version-7-7-0/

**Comment by jonathansadowski** [comment]
Hi @TamasFelix,

Thanks for your response. I'm glad you were able to find a solution. I'm going to close this if you're still not experiencing an issue. If you're still having problems, please respond with the system status report so that we can try and reproduce.
