### ISSUE TITLE
[Spike] Product Block Editor: Research how to fix tabbing behavior through blocks

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#38228]
When tabbing through the new product block editor, it takes more presses of the tab key to focus the input fields we're interested in modifying.

While this is seemingly not focusing anything, it actually focuses each block individually as seen when you turn on focus highlighting in Chrome.

- Tabbing should take you to the next editable field or interactive element in the product editor
- Items that can't be manipulated should not be focused in the product editor form

### Screenshot

![Image](https://user-images.githubusercontent.com/10561050/237534422-383332e8-aba0-4d28-841d-bf896a0d9ac7.png)

### Reproducing

1. In Chrome, open preferences
2. Navigate to accessibility
3. Turn on "Show a quick highlight on the focused object"
4. Hit the tab key continuously to navigate through the product editor
5. Note that many blocks that are not directly editable are focused while tabbing through the page

### Acceptance criteria

- [ ] Summarize your findings in this issue ( or P2/Discussions if it requires a wider conversation ) 
- [ ] Create follow up issues for what is needed.

**Comment by louwie17** [comment]
This has been addressed already and fixed here: https://github.com/woocommerce/woocommerce/pull/41436
