### ISSUE TITLE
Show APMs in inbox notifications 

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#38236]
P2: pdibGW-1Q8-p2#comment-1332

**Issue Description:**

Have APMs show up in inbox notifications 30-60 days after store activation if a payment gateway is set up and there are any more available gateways.

- Title: `Add alternate payment options at checkout`
- Content: `Make sure your store offers the payment options customers are looking for in addition to your primary payment solution: mobile wallets, express checkout options and “buy now, pay later”. Shoppers choose these options for security, budget, or loyalty rewards, and often lead to higher value and repeat purchases.`
- CTA: `View more payment options`, link to APM in the tasklist

---
Dev note:

> We may need to implement these rules to show APMs if we need to link it to APM in a tasklist:
> 1. A payment gateway is set up, activated, and enabled.
> 2. If the currently enabled gateway is in the “Other” or “Additional” category.
> 3. We may also need to know if there are any more available gateways (I imagine there would be cases where all possible gateways for the site are already enabled).

**Comment by adrianduffell** [comment]
Closing this due to age
