### ISSUE TITLE
Product Block Editor: Publishing product in classic editor redirects back to new editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38243]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When make use of the classic editor when creating a new product while having the feature flag enabled, the page redirects back to the new editor after clicking publish. We should remain within the classic editor.

![pGNVgb.gif](https://github.com/woocommerce/woocommerce/assets/2240960/0b8a92ef-39b9-4222-9693-c8b911581f6c)

**Acceptance criteria**

- [ ] When user selects to use the classic editor and publishes a product, we should remain within the classic editor.

**Comment by louwie17** [comment]
@jarekmorawski related to this issue, once a user selects **Use classic editor** should this be a permanent switch, where we disable the feature flag and only load the classic editor from there on out?
Or do you expect it to only be for the individual product?

The latter approach seems a bit odd to both @mdperez86 and I, and it would make more sense to disable it from there on out. We did probably have to show an additional warning within the Modal if we go that route.

**Comment by jarekmorawski** [comment]
> where we disable the feature flag and only load the classic editor from there on out?

No, it should be permanent. Users can switch back to the new UX using a button at the top.

<img width="624" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/3d3fdbf8-2505-4faf-82fb-4916cd662aaf">

**Comment by joshuatf** [comment]
Noting that we discussed adding a flag to toggle any feature via URL since we don't currently have an endpoint for toggling features.

For example:

```
/wp-admin/post.php?post=1&action=edit&feature=feature_name&toggle=0
```
