### ISSUE TITLE
[Enhancement]: We seem to have lost the ability to mark a product out of stock with 7.7.0 and preserve its quantity.

### ISSUE THREAD

**Issue by SpottedPaint** [woothemes/woocommerce#38254]
### Describe the solution you'd like

We seem to have lost the ability to mark a product out of stock with 7.7.0 and preserve its quantity.
You have to know that you need to untick "Track stock quantity for this product" in order to be able to see the out of stock radio button. So its not very obvious.

Also when you do that you lose any stock number you had stored. A store owner may put an item out of stock temporarily and then put it back into stock a while later (holidays, temporary problem, marketing) that has become more difficult.
They would now have to go back to a shelf or a warehouse which may be a distance from them in order to learn the number of items available when putting the item back in stock.

It would seem like the solution is to:
- preserve the number of items in stock when the item is swapped from in stock to out of stock. 
- allow the toggling of in and out of stock without unticking "Track stock quantity for this product".

This is what happens at the moment
![Screenshot 2023-05-11 at 15 49 21](https://github.com/woocommerce/woocommerce/assets/1105757/a20f8207-f474-4ee0-ba1e-346f67f87ee3)
Then put it out of stock
![Screenshot 2023-05-11 at 15 50 11](https://github.com/woocommerce/woocommerce/assets/1105757/e3a9d585-8898-4756-9b33-d74c2a5d3271)
Then after if I put it back into stock the quantity has switched to 1
![Screenshot 2023-05-11 at 15 50 57](https://github.com/woocommerce/woocommerce/assets/1105757/8dea608a-d8ea-4042-8010-2739e052af8f)

This is related to https://github.com/woocommerce/woocommerce/pull/37890
and https://github.com/woocommerce/woocommerce/issues/37878
and @mattsherman @pmcpinto 

I can see the changes made were well intentioned trying to make it simpler for users and avoid clashing values entered but the world is messy and it seems like we have lost something in the process?

### Describe alternatives you've considered

I'm not sure how this would tie in with HPOS changes that may be in the works but this seems like it should be considered in any changes to the interface made there.

**Comment by pmcpinto** [comment]
Hi Adam, thanks for opening the issue and sharing an overview of a use case that doesn't work with this change. We'll explore how to improve the flow.

**Comment by pmcpinto** [comment]
Hi Adam, I've just double-checked how it worked before the change and it doesn't preserve the stock quantity. Here's a brief video:


https://github.com/woocommerce/woocommerce/assets/3380168/e608f4d3-6330-4025-8dc1-69083d423dc4

Let me know if I misunderstood your suggestion

**Comment by SpottedPaint** [comment]
Sorry, I must of got the stock quantity mixed up. I was a bit pulled in all directions yesterday.
Perhaps it used to a long time ago or I'm just mixing it up with something else.

Shall we close this?

**Comment by pmcpinto** [comment]
> Shall we close this?

Yes. I'll close the issue. Thanks for the follow-up.
