### ISSUE TITLE
Product Block Editor: Auto save edits when user redirects to legacy editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38252]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently when a user makes some edits in the new editor and decides to switch to the legacy editor, the edits are not being saved and the user has to make them again. We should save these edits so the user doesn't have to make them again.

This should probably work different for existing products versus a brand new product that is still in auto-draft. If possible we should follow this:
- If new product ( in auto-draft ) or a `draft` product we save the changes keeping the record as `auto-draft` if possible and load this record within the legacy editor.
- If the record is already in `publish` we should notify the user before redirecting to either save the product first or loose changes. I think it seems wrong here to auto-save. The alert should show up before the feedback modal.

**Acceptance criteria**

- [ ] When user made edits on new product or a draft product and clicks `User the classic editor` we should save these edits and redirect, but keeping the record as the same status either `auto-draft` or `draft`
- [ ] When user made edits on an already published product and clicks `User the classic editor` we should prompt the user the changes would be lost (before the feedback modal shows up)

**Comment by louwie17** [comment]
@jarekmorawski we made some slight modifications to this logic, and decided it would be ok for `draft` products to auto save as well, that only for `published` products we show the alert.
We would also show the alert before the feedback modal shows up.
Just wanted to double check with you to see if this is ok?

**Comment by jarekmorawski** [comment]
I think this looks good to me. Thanks for looking into it! 🙇

> When user made edits on an already published product and clicks Use the classic editor we should prompt the user the changes would be lost

To be clear, this should only happen if the user made changes since the last save. For example, if I update the price and save the product in the new form, then click the button to switch to the old UX, I shouldn't see the prompt.

Do we plan to use the browser's default prompt? I'm fine with it, just want to make sure.

<img width="300" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/b1ea52a4-aa0a-4c64-ae81-ac2fbd078a49">

**Comment by joshuatf** [comment]
>Do we plan to use the browser's default prompt? I'm fine with it, just want to make sure.

For the time being, yes.  Though we could update this in the future if we want to use our own modal.

**Comment by joshuatf** [comment]
@jarekmorawski @louwie17 I think this behavior may introduce some quirky bugs.  After beginning to work on this, I realized that we would also need to validate and surface errors within the draft before we can auto-save.

Even if we manage to surface errors in a better way, I think as a merchant I would be confused seeing errors suddenly when clicking "Use the classic editor."

I'm in favor of continuing to show the confirmation of unsaved changes modal for any changes made for published or auto-draft products.  What do you all think?

**Comment by louwie17** [comment]
> I'm in favor of continuing to show the confirmation of unsaved changes modal for any changes made for published or auto-draft products. What do you all think?

Hmm yeah this may be the best approach then, always leave it up to the user.

On a quick side note, this makes me wonder if should add support for silently checking validations? Instead of it auto triggering the errors? (cc @mdperez86 )

**Comment by joshuatf** [comment]
I think we can silently check validation if we wanted to without triggering errors, but would that be helpful in this case?  Or did you have another case in mind?

**Comment by jarekmorawski** [comment]
> I'm in favor of continuing to show the confirmation of unsaved changes modal for any changes made for published or auto-draft products. What do you all think?

Does this mean the user would see errors in the form when they dismiss the browser prompt? If so, can we disable validation when a product is in the draft state?

**Comment by joshuatf** [comment]
@jarekmorawski It doesn't really affect validation if we did it using my proposed way.  They either choose to stay on the page and continue editing as they were before or they leave the page, losing changes.

If the question is about disabling validation so we can temporarily save the product, we cannot do that since validation also happens on the server and that could create quite a few problems downstream.

**Comment by joshuatf** [comment]
@jarekmorawski Did you have any additional feedback on this?  If not, I'll go ahead and close this issue.

**Comment by jarekmorawski** [comment]
Let's leave it for now. We can test it in the product and make further changes if needed. Thanks for working on this!

**Comment by joshuatf** [comment]
No problem!  Thank you much for the feedback, @jarekmorawski!

Closing this for now and we can reopen if we need to tweak in the future.
