### ISSUE TITLE
[MVP QA #1] Visual: typography

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38260]
Hi there! I reviewed the latest build of the product editing experience and made some notes about changes we can make. In this issue, I outline improvements to typography, spacing, and other small visual details throughout the form.

**Acceptance criteria**

- [x] The heading font needs to be smaller and lighter. Let’s change it to 20 px / 500.
- [x] Let's remove icons from all section headers.
- [ ] In Pricing and Inventory, we should remove subheadings from sections and use regular field labels (examples attached below). If there's an existing space between a subheading an UI controls (like radio buttons), let's update it to 12 px.
- [ ] Section description text should be Gutenberg-700.
- [ ] The line height in the section description feels tight. Let’s change it to 1.5.
- [x] The help icon in checkboxes is small, detached from the item label, and vertically misaligned. It should be 16 px, not 14 px.

<img width="603" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/aff51d82-084b-48fd-ba80-9f26d52e6b16">
<img width="689" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/fa009398-f459-4869-a592-9dc6021c8870">

**Comment by jarekmorawski** [comment]
Updated AC to reflect some changes from the last design review: `p6riRB-8Cl-p2`.
