### ISSUE TITLE
Consider bleed of `theme.json` styles into the block-based product editor.

### ISSUE THREAD

**Issue by nerrad** [woothemes/woocommerce#38279]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The product editor is showing the background color from global styles in the editor. This is usually expected behaviour in a block editor instance because of the wysiwyg for layout previewing. However, with the design of the product editor being more form-based, the styles don't work.

However, we'll want to make sure the styles _are_ considered when editing the product description.

### Expected behavior

Frontend global styles are not applied to the product editor.

### Actual behavior

Frontend global styles **are** applied to the product editor.
<img width="906" alt="CleanShot 2023-05-12 at 10 05 26@2x" src="https://github.com/woocommerce/woocommerce/assets/1429108/96bea9fd-3709-4538-a72e-38c08402fbb6">

### Steps to reproduce

1. Activate a theme like Twenty Twenty Three.
2. Activate a style such as "Block out" via the Styles panel in the site editor.
3. View the experimental block-based product editor and see that the chosen styles are affecting the product editor.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by joshuatf** [comment]
This is related to https://github.com/woocommerce/woocommerce/pull/38168.

We may be able to move those `EditorStyles` to the preview and wrap that in an iframe to prevent these styles from bleeding into the main editor.
