### ISSUE TITLE
[Enhancement]: HPOS documentation clarity

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#38283]
### Describe the solution you'd like

https://developer.woocommerce.com/2023/03/07/high-performance-order-storage-is-soon-to-be-the-new-normal/ says: "Any extensions that are not marked compatible will no longer be able to be activated on new stores, starting in August.".

Does it mean to say "not marked compatible", or did it actually intend "marked not compatible" ?

If it really means what it says, I'm wondering how WooCommerce intends to detect which plugins on a site are WooCommerce extensions. (Parsing the plugin name for certain terms?).

**Comment by barryhughes** [comment]
Hi @DavidAnderson684,

Thanks for flagging this. The previous wording was misleading, and has now been updated to:

> Any extensions that are not marked compatible will display an incompatibility error message on new stores, starting in August. 

Also, in case of interest, the logic for determining which plugins are WooCommerce extensions can be seen in [Automattic\WooCommerce\Utilities\PluginUtil::is_woocommerce_aware_plugin()](https://github.com/woocommerce/woocommerce/blob/7.7.0/plugins/woocommerce/src/Utilities/PluginUtil.php#L103-L118) ... in essence, we look for the presence of the `WC tested up to` field in the plugin header.

I hope that clarifies things :-)

**Comment by vedanshujain** [comment]
Closing based on last comment for repo maintainence.
