### ISSUE TITLE
[Enhancement]: Add Saint Kitts and Nevis localizations for address entry

### ISSUE THREAD

**Issue by beaulebens** [woothemes/woocommerce#38280]
### Describe the solution you'd like

WC is currently missing the specifics for entering addresses in Saint Kitts and Nevis, which use named "Parishes".

Via support request (6272406-zd-woothemes), we received the following suggested addition:

 ```php
'KN' => array(
        'K' => __( 'Saint Kitts', 'woocommerce' ),
        'N' => __( 'Nevis', 'woocommerce' ),
        '01' => __( 'Christ Church Nichola Town', 'woocommerce' ),
        '02' => __( 'Saint Anne Sandy Point', 'woocommerce' ),
        '03' => __( 'Saint George Basseterre', 'woocommerce' ),
        '04' => __( 'Saint George Gingerland', 'woocommerce' ),
        '05' => __( 'Saint James Windward', 'woocommerce' ),
        '06' => __( 'Saint John Capisterre', 'woocommerce' ),
        '07' => __( 'Saint John Figtree', 'woocommerce' ),
        '08' => __( 'Saint Mary Cayon', 'woocommerce' ),
        '09' => __( 'Saint Paul Capisterre', 'woocommerce' ),
        '10' => __( 'Saint Paul Charlestown', 'woocommerce' ),
        '11' => __( 'Saint Peter Basseterre', 'woocommerce' ),
        '12' => __( 'Saint Thomas Lowland', 'woocommerce' ),
        '13' => __( 'Saint Thomas Middle Island', 'woocommerce' ),
        '15' => __( 'Trinity Palmetto Point', 'woocommerce' ),
    ),
```

We would also need to make a modification in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L791 to support this properly.

**Comment by beaulebens** [comment]
Ref for the ISO codes: https://en.wikipedia.org/wiki/ISO_3166-2:KN

**Comment by coreymckrill** [comment]
We typically use CLDR for our data source, rather than ISO 3166-2. However, it looks like the same data [exists there as well](https://github.com/unicode-org/cldr/blob/f9432b659df2259c473ae9a7d0801fef473c19ed/common/subdivisions/en.xml#L2788-L2804) (with a slight difference in the array keys from the suggestion above), so this seems like a good addition 👍

**Comment by igorradovanov** [comment]
I'd like to work on this issue.

**Comment by coreymckrill** [comment]
@igorradovanov [pull requests are welcome](https://github.com/woocommerce/woocommerce/blob/4e530ba2e2d647f9c3fc33ac00c4a2e62447ddb7/.github/CONTRIBUTING.md)!
