### ISSUE TITLE
[Enhancement]: Add Pinterest product page link to core profiler Free features step

### ISSUE THREAD

**Issue by oneillo** [woothemes/woocommerce#38298]
### Describe the solution you'd like

One of the extensions that you can opt to install in the `Free features` section is Pinterest for WooCommerce, but unlike the other items, it doesn’t explicitly mention the extension with a link to its product page.

Can we please update that entry to include a link to the product page?

Here is the suggested copy:

> Get in front of Pinners searching for ideas and things to buy with [Pinterest for WooCommerce](https://href.li/?https://woocommerce.com/products/pinterest-for-woocommerce/).

And here is the item that I'm referring to.

<img width="527" alt="pinterest-profiler-link" src="https://github.com/woocommerce/woocommerce/assets/730723/16e8e706-bf32-4271-ac81-23c6adcd100e">

**Comment by adrianduffell** [comment]
This has been fixed in the new Core Profiler

<img width="498" alt="Screen Shot 2023-09-07 at 4 37 04 pm" src="https://github.com/woocommerce/woocommerce/assets/9312929/2ba7ec66-a3cb-4b19-9d9b-80a062d24081">
