### ISSUE TITLE
PHP 8.1+ issue because of string value in function 'array_slice' in function 'woocommerce_upsell_display'

### ISSUE THREAD

**Issue by webr459g8s490ghw3** [woothemes/woocommerce#38292]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP 8.1+ incompatibility in function 'woocommerce_upsell_display' in file '/woocommerce/includes/wc-template-functions.php'.

The problem lies in that PHP 8 does not allow string values to be used in function 'array_slice'.

The first parameter, $limit, has a default **string** value of '-1' and is later used in function 'array_slice' to limit the amount of upsells. PHP 7 had no issue with this, but PHP 8+ does.

### Expected behavior

The upsells should work in PHP 8.1+.

For now I have done a hotfix: I changed the value to be an integer by adding '(int)' before the value to be used for variable '$limit'.

`$limit   = **(int)**apply_filters( 'woocommerce_upsells_total', isset( $args['posts_per_page'] ) ? $args['posts_per_page'] : $limit );`

### Actual behavior

A fatal error occurs on product pages due to PHP 8+ not accepting a string value in function 'array_slice' for the third argument.

### Steps to reproduce

1. Set PHP version to PHP 8.1+
2. Open a product page with upsells

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): X
Site address (URL): X
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.17
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 8.0.1
OpenSSL/1.1.1k-fips

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: 4de_
Totale database grootte: 249.75MB
Database gegevens grootte: 176.96MB
Database index grootte: 72.79MB
4de_woocommerce_sessions: Data: 1.94MB + Index: 0.05MB + Engine MyISAM
4de_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_order_items: Data: 2.52MB + Index: 1.29MB + Engine MyISAM
4de_woocommerce_order_itemmeta: Data: 17.79MB + Index: 11.59MB + Engine MyISAM
4de_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_actionscheduler_actions: Data: 6.98MB + Index: 2.37MB + Engine MyISAM
4de_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_actionscheduler_logs: Data: 4.00MB + Index: 2.85MB + Engine MyISAM
4de_aelia_dismissed_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_aelia_exchange_rates_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_automatewoo_abandoned_carts: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
4de_automatewoo_customers: Data: 1.52MB + Index: 1.64MB + Engine InnoDB
4de_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4de_automatewoo_guests: Data: 1.52MB + Index: 1.02MB + Engine InnoDB
4de_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4de_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4de_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_bv_activities_store: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_comments: Data: 6.83MB + Index: 2.45MB + Engine MyISAM
4de_dgwt_wcas_index: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
4de_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4de_dgwt_wcas_invindex_doclist: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
4de_dgwt_wcas_invindex_wordlist: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
4de_dgwt_wcas_tax_index: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4de_dgwt_wcas_var_index: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4de_feedmanager_channel: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_feedmanager_country: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
4de_feedmanager_feed_status: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_feedmanager_field_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_feedmanager_product_feed: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_feedmanager_product_feedmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_feedmanager_source: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4de_gf_entry: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
4de_gf_entry_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
4de_gf_entry_notes: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
4de_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_kiyoh: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_litespeed_img_optm: Data: 0.64MB + Index: 0.24MB + Engine MyISAM
4de_litespeed_img_optming: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
4de_litespeed_url: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
4de_litespeed_url_file: Data: 0.44MB + Index: 1.86MB + Engine InnoDB
4de_options: Data: 11.53MB + Index: 0.53MB + Engine MyISAM
4de_postmeta: Data: 88.12MB + Index: 35.38MB + Engine MyISAM
4de_posts: Data: 5.82MB + Index: 1.36MB + Engine MyISAM
4de_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
4de_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
4de_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
4de_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_slides: Data: 0.27MB + Index: 0.00MB + Engine MyISAM
4de_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_termmeta: Data: 0.13MB + Index: 0.03MB + Engine MyISAM
4de_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
4de_term_relationships: Data: 0.07MB + Index: 0.15MB + Engine MyISAM
4de_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
4de_tm_taskmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_usermeta: Data: 4.02MB + Index: 2.46MB + Engine MyISAM
4de_users: Data: 0.24MB + Index: 0.25MB + Engine MyISAM
4de_wcpdf_credit_note_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wcpdf_invoice_number: Data: 0.21MB + Index: 0.12MB + Engine MyISAM
4de_wcpdf_packing_slip_number: Data: 0.12MB + Index: 0.07MB + Engine MyISAM
4de_wcpdf_proforma_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
4de_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
4de_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_customer_lookup: Data: 0.84MB + Index: 0.82MB + Engine MyISAM
4de_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
4de_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_order_product_lookup: Data: 1.70MB + Index: 1.33MB + Engine MyISAM
4de_wc_order_stats: Data: 1.22MB + Index: 0.64MB + Engine MyISAM
4de_wc_order_tax_lookup: Data: 0.59MB + Index: 0.64MB + Engine MyISAM
4de_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
4de_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4de_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
4de_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
4de_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfblockediplog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfconfig: Data: 0.41MB + Index: 0.02MB + Engine MyISAM
4de_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wffilemods: Data: 6.39MB + Index: 0.72MB + Engine MyISAM
4de_wfhits: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
4de_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfknownfilelist: Data: 4.71MB + Index: 0.22MB + Engine MyISAM
4de_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wflocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wflogins: Data: 0.34MB + Index: 0.07MB + Engine MyISAM
4de_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4de_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_wfnotifications: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
4de_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_wfstatus: Data: 0.12MB + Index: 0.06MB + Engine MyISAM
4de_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
4de_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_woodmart_wishlists: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
4de_woodmart_wishlist_products: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
4de_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_wpmailsmtp_emails_log: Data: 3.52MB + Index: 0.48MB + Engine InnoDB
4de_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4de_yoast_indexable: Data: 0.33MB + Index: 0.13MB + Engine InnoDB
4de_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4de_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4de_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4de_yoast_seo_links: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
4de_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 991
br_labels: 5
cms_block: 42
custom_css: 1
custom-css-js: 17
cwginstocknotifier: 191
extra_product_tab: 4
gdprc_consent: 3
mc4wp-form: 1
nav_menu_item: 72
oembed_cache: 6
page: 34
post: 55
product: 170
revision: 77
shop_coupon: 1
shop_order: 13856
shop_order_refund: 509
wapf_product: 1
woo_mb_template: 10
woodmart_sidebar: 1
woodmart_slide: 4
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Gravity Forms: door Gravity Forms – 2.7.5
Advanced Product Fields Pro for WooCommerce: door StudioWombat – 2.7
FiboSearch - AJAX Search for WooCommerce (Pro): door FiboSearch Team – 1.23.0
AutomateWoo: door WooCommerce – 5.7.3
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: door codewoogeek – 3.2
Contact Form 7: door Takayuki Miyoshi – 5.7.6
Simple Custom CSS and JS: door SilkyPress.com – 3.43
Yoast Duplicate Post: door Enrico Battocchi & Team Yoast – 4.5
GTM4WP: door Thomas Geiger – 1.16.2
Envato Market: door Envato – 2.0.8
GDPR Consent: door WP Upgrader – 3.5.0
Gravity PDF: door Blue Liquid Designs – 6.5.5
Head, Footer and Post Injections: door Stefano Lissa – 3.2.5
WPBakery Page Builder: door Michael M - WPBakery.com – 6.11.0
KeenDelivery - WooCommerce Shipping plugin: door KeenDelivery BV – 1.0.7
Kiyoh Customerreview: door kiyoh – 1.0.30
LiteSpeed Cache: door LiteSpeed Technologies – 5.4
Loco Translate: door Tim Whitlock – 2.6.4
MC4WP: Mailchimp for WordPress: door ibericode – 4.9.4
PW WooCommerce Bulk Edit Pro: door Pimwick
LLC – 2.356

Safe SVG: door 10up – 2.1.1
WooCommerce Sisow betaalmethoden: door Sisow – 5.5.8
Tiered Price Table for WooCommerce: door U2Code – 5.2.0
WooCommerce NL Postcode Checker: door WP Overnight – 2.9.2
WebP Express: door Bjørn Rosell – 0.25.6
Premmerce Permalink Manager for WooCommerce: door Premmerce – 2.3.8
Woocommerce Product Tab Pro: door Proword – 4.2
WooCommerce Advanced Product Labels: door BeRocket – 3.2.5.3
WooCommerce Cost of Goods: door SkyVerge – 2.12.0 (update naar versie 2.13.0 is beschikbaar)
WooCommerce EU BTW Assistent: door Aelia – 2.0.39.230214
WooCommerce Measurement Price Calculator: door SkyVerge – 3.21.1
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.5.2
PDF Invoices & Packing Slips for WooCommerce - Professional: door WP Overnight – 2.14.1
Sequential Order Numbers for WooCommerce: door SkyVerge – 1.9.7
WooCommerce: door Automattic – 7.6.1 (update naar versie 7.7.0 is beschikbaar)
Woodmart Core: door  – 1.0.37
Yoast SEO: door Team Yoast – 20.7
WP Mail SMTP Pro: door WP Mail SMTP – 3.8.0
WooCommerce product feed Manager: door Michel Jongbloed – 2.39.2
WPS Hide Login: door WPServeur
NicolasKulka
wpformation – 1.9.8

### Inactive Plugins (1) ###

Hide Admin Notices: door PontetLabs – 1.2.2

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Must Use Plugins (2) ###

GDPR Consent Plugin Controller: door WP Upgrader – 3.5.0
installatron_hide_status_test.php: door  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #9 - /winkel/
Winkelwagen: #10 - /winkelmand/
Afrekenen: #11 - /afrekenen/
Mijn account: #12 - /mijn-account/
Algemene voorwaarden: #2564 - /algemene-voorwaarden/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.2.2 – 7.2.4 is beschikbaar
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### Pimwick Plugins ###

PW WooCommerce Bulk Edit Pro: License key: 
Result: success
Cached: 2023-05-15

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-15 08:13:09 +02:00
Options: ✔
Notes: 152
Onboarding: completed

### Action Scheduler ###

Afgerond: 20.069
Oldest: 2023-04-14 09:09:53 +0200
Newest: 2023-05-15 09:01:58 +0200

In afwachting: 5
Oldest: 2023-05-15 09:06:58 +0200
Newest: 2023-05-22 05:27:58 +0200

Mislukt: 11
Oldest: 2023-02-20 16:33:53 +0100
Newest: 2023-05-08 14:24:49 +0200

### Status report information ###

Generated at: 2023-05-15 09:06:31 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dsmithweb-a8c** [comment]
6291015-zen

**Comment by rrennick** [comment]
@webr459g8s490ghw3 Thanks for reporting the issue. I have updated the issue to reflect that this is an incompatibility with 8.1+ vs 8+. 

```
# php -r 'echo json_encode(array_slice( [1,2,3,4], "1" ,"2") );' 
[2,3]% 
# php -v
PHP 8.0.28 (cli) (built: Feb 14 2023 15:42:52) ( NTS )
```
