### ISSUE TITLE
[Enhancement]: Update UTM tags in Product Types step in core profiler

### ISSUE THREAD

**Issue by oneillo** [woothemes/woocommerce#38300]
### Describe the solution you'd like

In order to better track traffic from different parts of Woo core, can you please update the UTM tags on the product links in the `Product Types` step of the core profile to:

`?utm_source=storeprofiler&utm_medium=product&utm_campaign=producttyperecs`

The current tags make it look like any traffic from that page is coming from the Marketplace instead.

The links are in the popups that come up when you hover over the Ⓘ next to the recommendations.

<img width="849" alt="product-types-links" src="https://github.com/woocommerce/woocommerce/assets/730723/48a25758-2cce-43af-873d-e9634c93f5dc">

Thanks!

**Comment by adrianduffell** [comment]
Closing this out as these links are no longer shown.
