### ISSUE TITLE
Why is anything WooCommerce Admin loaded front-end?

### ISSUE THREAD

**Issue by kimmenbert** [woothemes/woocommerce#38308]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While developing an autoloader I noticed a lot of WooCommerce Admin classes mentioned front-end.
It's not classes that's getting loaded, but I wonder why they are there at all, in the end there is logic front end that I would think is exclusively for admin. Examples:

```
Automattic\WooCommerce\Admin\Features\Navigation
Automattic\WooCommerce\Admin\Features\ImportProductsTask
Automattic\WooCommerce\Admin\Features\ImportProductsTask\Init
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts\Init
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults\Init
Automattic\WooCommerce\Admin\Features\ShippingSettingTour
Automattic\WooCommerce\Admin\Features\ShippingSettingTour\Init
Automattic\WooCommerce\Admin\Features\OnboardingTasks
Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions
Automattic\WooCommerce\Admin\Features\PaymentGatewaySuggestions
Automattic\WooCommerce\Admin\Features\Subscriptions
Automattic\WooCommerce\Admin\Features\Subscriptions\Init
Automattic\WooCommerce\Admin\Features\StoreAlerts
Automattic\WooCommerce\Admin\Features\StoreAlerts\Init
Automattic\WooCommerce\Admin\Features\WooMobileWelcome
Automattic\WooCommerce\Admin\Features\WooMobileWelcome\Init
Automattic\WooCommerce\Admin\Features\WcPayPromotion
```

I would think wrapping this in some admin check would be a good practise?
https://github.com/woocommerce/woocommerce/blob/06006619b36840e4cacaa8d7f47ef328725f2926/plugins/woocommerce/src/Packages.php#L64

### Expected behavior

Avoid parsing admin only code front-end

### Actual behavior

Unknown consequences performance wise, but there is a lot of checks for WooCommerce Admin features and if they are enabled or not.

### Steps to reproduce

Check the code linked in issue. Follow the init() function and especially look at the `$feature_plugin_instance = FeaturePlugin::instance();` 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://project-boiler.local
Site address (URL): http://project-boiler.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 6.53MB
Database Data Size: 4.88MB
Database Index Size: 1.65MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
page: 8
post: 3
product: 9
revision: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.7.0

### Inactive Plugins (1) ###

Project Name Customizations: by Maksimer – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-16 16:57:39 +00:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 18
Oldest: 2023-05-15 16:57:40 +0000
Newest: 2023-05-15 17:16:13 +0000

Pending: 2
Oldest: 2023-05-15 22:04:13 +0000
Newest: 2023-05-16 16:57:40 +0000

Failed: 1
Oldest: 2023-05-15 17:00:41 +0000
Newest: 2023-05-15 17:00:41 +0000

### Status report information ###

Generated at: 2023-05-15 22:03:15 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lkraav** [comment]
Perhaps somewhat related to https://github.com/woocommerce/woocommerce-blocks/discussions/8166

**Comment by ilyasfoo** [comment]
Hey, @kimmenbert!

~~Thanks for raising this, I get your concern about prematurely loading unnecessary classes. I believe most of the classes you mentioned may load API controllers. May I know what's the example use case that you're trying to do with your autoloader?~~

Sorry, I misunderstood earlier. Thanks for raising this issue, I think it makes sense to only load the classes on admin pages.

Also, I can't find some of the classes like `Automattic\WooCommerce\Admin\Features\ImportProductsTask` in my `WooCommerce 7.7.0` copy. May I know where did you get your list?

**Comment by kimmenbert** [comment]
Hey,

Sorry for the late feedback.
You can find `ImportProductTask` if you do:

```
spl_autoload_register(
	function( $classname ) {
		print_r( $classname );
	}
);
```

**Comment by adrianduffell** [comment]
It looks like the admin features are automatically loaded on the `init` hook, if a matching class exists for an enabled feature flag.

https://github.com/woocommerce/woocommerce/blob/95a32efb2a3cb40fda1657deff94c9a0a1330443/plugins/woocommerce/src/Admin/Features/Features.php#L113-L127

As a result, a number of non-exists classes are checked for, such as `ImportProductsTask`.  If this is considered a bug, it might be better to maintain a static map / array of feature flags to class names.

I believe the reason this loads on the front-end is because the features class instantiates classes on the `init` hook.

https://github.com/woocommerce/woocommerce/blob/95a32efb2a3cb40fda1657deff94c9a0a1330443/plugins/woocommerce/src/Admin/Features/Features.php#L62

https://github.com/woocommerce/woocommerce/blob/95a32efb2a3cb40fda1657deff94c9a0a1330443/plugins/woocommerce/src/Admin/Features/Features.php#L132-L141

ChatGPT [suggests](https://chat.openai.com/share/86b1833b-31c2-460f-985c-ba2381c282db) we could prevent front-end loading by checking it's not other types of requests -- admin, ajax or WP CLI. We could possibly wrap the `init` hook like so:

```
if ( is_admin() || ( defined( 'DOING_AJAX' ) && DOING_AJAX ) || ( defined( 'WP_CLI' ) && WP_CLI ) ) {
    add_action( 'init', array( __CLASS__, 'load_features' ), 4 );
}

```

**Comment by adrianduffell** [comment]
I think it would also need a check for REST API requests 🤔
