### ISSUE TITLE
Uncaught error when calling wc_get_orders (no other plugins active)

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#38304]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I encountered this after setting up a test site on which I deactivated all plugins except WooCommerce. In summary: having an inactive (or obsolete+deleted) plugin that had stored an object in metadata can result in WC triggering an uncaught PHP fatal error when calling `wc_get_orders()`.

N.B. HPOS is active (I don't know whether this is related).

```
% php -a
php > echo PHP_VERSION; // By the way, 
8.2.5
php > require 'wp-load.php'; // Lots of PHP deprecation notices for dynamic properties in WC, but this issue is about something else. 
php > echo WOOCOMMERCE_VERSION;
7.7.0
php > $order_results = wc_get_orders(array('limit' => 300, 'offset' => 0, 'order' => 'DESC',
'order_by' => 'ID', 'return' => 'objects', 'meta_key' => '_openinghours_time', 'meta_value' => '', 'meta_compare' => '!='));

Warning: Uncaught Error: The script tried to modify a property on an incomplete object. Please ensure that the class definition "geoiprecord" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in wp-includes/formatting.php:5035
Stack trace:
#0 wp-includes/formatting.php(5030): map_deep(Object(__PHP_Incomplete_Class), 'stripslashes_fr...')
#1 wp-includes/formatting.php(5030): map_deep(Array, 'stripslashes_fr...')
#2 wp-includes/formatting.php(2810): map_deep(Array, 'stripslashes_fr...')
#3 wp-includes/formatting.php(5688): stripslashes_deep(Array)
#4 wp-includes/meta.php(53): wp_unslash(Array)
#5 wp-includes/post.php(2446): add_metadata('post', 70, 'vat_compliance_...', Array, false)
#6 wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(623): add_post_meta(70, 'vat_compliance_...', Array, false)
#7 wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(560): Abstract_WC_Order_Data_Store_CPT->update_order_meta_from_object(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#8 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(549): Abstract_WC_Order_Data_Store_CPT->update_order_from_object(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#9 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2156): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->backfill_post_record(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#10 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2489): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->maybe_backfill_post_record(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#11 wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->update_meta(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Meta_Data))
#12 wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(681): WC_Data_Store->__call('update_meta', Array)
#13 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1232): WC_Data->save_meta_data()
#14 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1317): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->migrate_meta_data_from_post_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#15 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1120): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->migrate_post_record(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#16 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1026): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->maybe_sync_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#17 wp-content/plugins/woocommerce/includes/class-wc-data-store.php(171): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read_multiple(Array)
#18 wp-content/plugins/woocommerce/includes/class-wc-order-factory.php(123): WC_Data_Store->read_multiple(Array)
#19 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2316): WC_Order_Factory::get_orders(Array)
#20 wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->query(Array)
#21 wp-content/plugins/woocommerce/includes/class-wc-order-query.php(87): WC_Data_Store->__call('query', Array)
#22 wp-content/plugins/woocommerce/includes/wc-order-functions.php(69): WC_Order_Query->get_orders()
#23 php shell code(1): wc_get_orders(Array)
#24 {main}
  thrown in wp-includes/formatting.php on line 5035
```

Looks similar in concept to (fixed) https://github.com/woocommerce/woocommerce/issues/34913 - WC is running metadata through formatting functions, and those formatting functions can end up loading objects, resulting in uncaught errors. In this specific case the thing it was trying to operate on was:

```
O:11:"geoiprecord":14:{s:12:"country_code";s:2:"BE";s:13:"country_code3";s:3:"BEL";s:12:"country_name";s:7:"Belgium";s:6:"region";s:3:"BRU";s:4:"city";s:8:"Brussels";s:11:"postal_code";s:4:"1000";s:8:"latitude";d:50.833300000000001;s:9:"longitude";d:4.3333000000000004;s:9:"area_code";N;s:8:"dma_code";N;s:10:"metro_code";N;s:14:"continent_code";s:2:"EU";s:11:"region_name";s:16:"Brussels Capital";s:8:"timezone";s:15:"Europe/Brussels";}}
```

### Expected behavior

Handled nicely, no crash. (e.g. catch the error).

### Actual behavior

PHP uncaught error, crash.

### Steps to reproduce

See above.

### WordPress Environment

WP 6.2, other versions as above.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

**Comment by DavidAnderson684** [comment]
Given the contents of the report above, it is already clear that you will be able to reproduce this bug on any environment whatsoever (as I say, without any other plugins active) using the current WC release with custom order tables active. You just need a serialized object of a non-present class in an order meta field. I have reported my WP + PHP versions.

**Comment by psealock** [comment]
> In summary: having an inactive (or obsolete+deleted) plugin that had stored an object in metadata can result in WC triggering an uncaught PHP fatal error when calling wc_get_orders().

>You just need a serialized object of a non-present class in an order meta field

Thanks for the details. Could you include step by step instructions on how to achieve this scenario?

**Comment by DavidAnderson684** [comment]
It's already above.

1. Insert an order meta item that includes a serialized object of a defined class (not stdClass) - such as the one given above.
2. Disable the code that defines the class for that object.
3. Activate HPOS if it was not already active.
4. Use `wc_get_orders()` to fetch the associated order.

**Comment by DavidAnderson684** [comment]
For what it's worth, I can confirm this issue is still present on WooCommerce 7.8.2 (I just hit it again whilst coding on a different plugin).

**Comment by DavidAnderson684** [comment]
As you might expect from the stack trace, "Keep the posts table and the orders tables synchronized" has to be checked in WooCommerce -> Settings -> Advanced ->  Custom data stores in order to trigger this error.

**Comment by jorgeatorres** [comment]
Related to 7249537-zd-a8c.
