### ISSUE TITLE
Product Block Editor: Show notification message when the user try to save the form in a non dirty state

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#38329]
**Description**

When the form is not dirty if the user click the save button, nothing happens.

See https://github.com/woocommerce/woocommerce/pull/38194#pullrequestreview-1429530056

**ACs**

- [ ]  Clicking the save button when the form is not dirty shows "Product updated. [ View in store]" message

**Comment by jarekmorawski** [comment]
Thanks, Maikel. I updated the ACs with a different copy for the message. It should look at same as the one below, but with `updated` instead of `published`.

<img width="377" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/e472d3ea-292a-4957-8fa0-77aaec3d25e6">

**Comment by nathanss** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce/issues/39991
