### ISSUE TITLE
functions.php executing more than once

### ISSUE THREAD

**Issue by jaykeny** [woothemes/woocommerce#38331]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is probably minor, as I haven't dug deep into it yet, but just happened to come across this issue when debugging a slow site. I believe this may be some sort of redirect that happens behind the scenes, because it doesn't happen when echoing. I noticed when just spitting out data from within functions.php using the file_put_contents() function that it was adding the data twice. Upon reverting to twenty-twenty-two and deactivating all plugins the issue no longer occurred. It wasn't until activating WooCommerce that the issue arose again.

### Expected behavior

file_put_contents() should not run more than once.

### Actual behavior

file_put_contents() runs twice.

### Steps to reproduce

Add the following to the twenty-twenty-two theme with WooCommerce activated
file_put_contents('test.log', 'test' . PHP_EOL, FILE_APPEND);

Check root directory of WordPress for the log file.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://sandbox.local
Site address (URL): http://sandbox.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.1l PHP/7.4.25
PHP Version: 7.4.25
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 7.21MB
Database Data Size: 5.26MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.47MB + Index: 0.34MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_categorymeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.06MB + Engine InnoDB
wp_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
faq: 7
nav_menu_item: 10
page: 8
post: 3
product: 2
revision: 3
shop_order: 1
shop_subscription: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.7.0

### Dropin Plugins (1) ###

object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.18.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-18 07:42:04 +00:00
Options: ✔
Notes: 68
Onboarding: -

### Action Scheduler ###

Complete: 17
Oldest: 2023-05-17 05:16:05 +0000
Newest: 2023-05-17 07:42:06 +0000

Failed: 1
Oldest: 2023-05-17 05:42:00 +0000
Newest: 2023-05-17 05:42:00 +0000

Pending: 2
Oldest: 2023-05-18 05:16:05 +0000
Newest: 2023-06-17 05:55:55 +0000

### Status report information ###

Generated at: 2023-05-17 07:54:57 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> functions.php executing more than once

@jaykeny If a site loads the TwentyTwenty-Two theme `functions.php` a second time it will produce a fatal 500 error.

> I believe this may be some sort of redirect that happens behind the scenes, because it doesn't happen when echoing

This is the most likely case for the site you are investigating. You have not indicated how this issue is related to WooCommerce. While WooCommerce does enqueue CSS for default WordPress themes, it does not attempt to run any default themes' code.

I'll close this issue for now. If you can provide steps to reproduce this issue that do involve WooCommerce, let us know and we can re-open the issue.

**Comment by jaykeny** [comment]
> > functions.php executing more than once
> 
> @jaykeny If a site loads the TwentyTwenty-Two theme `functions.php` a second time it will produce a fatal 500 error.
> 
> > I believe this may be some sort of redirect that happens behind the scenes, because it doesn't happen when echoing
> 
> This is the most likely case for the site you are investigating. You have not indicated how this issue is related to WooCommerce. While WooCommerce does enqueue CSS for default WordPress themes, it does not attempt to run any default themes' code.
> 
> I'll close this issue for now. If you can provide steps to reproduce this issue that do involve WooCommerce, let us know and we can re-open the issue.

Executes more than once is probably a poor choice of words. The below is better explained.
https://stackoverflow.com/questions/26058094/php-file-put-contents-writes-content-multiple-times

This only happens with WooCommerce activated.

**Comment by rrennick** [comment]
@jaykeny I completed the following testing steps:

- Deactivated all plugins except WooCommerce
- Switch to Twenty Twenty-Two
- Add the following to the theme `functions.php`
```
error_log( $_SERVER['REQUEST_URI'] );
```
- Load the home page to ensure the broswer has cached all assets
- Ran `rm debug.log` in the `wp-content` folder
- Refresh the home page
```
# cat debug.log
[19-May-2023 13:49:48 UTC] /
[19-May-2023 13:49:48 UTC] /wp-cron.php?doing_wp_cron=1684504188.5752971172332763671875
```
- Deactivated WooCommerce
- Ran `rm debug.log` again
- Refresh the home page
```
# cat debug.log
[19-May-2023 13:49:48 UTC] /
```

WordPress randomly adds the `wp-cron.php` request to a percentage of requests whether or not any plugins are active. Logging `$_SERVER['REQUEST_URI']` instead of a static string may give you an indication of where the second request is coming from.
