### ISSUE TITLE
PHP 8.2 Compatibility issue with 'Migrations'

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#38349]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Minor issue, but on my development server I like to print out PHP error messages during testing. After upgrading to the latest PHP 8.2 version recently, my WordPress dashboard could not load because the following messages were generated before the output:

`Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderTableMigrator::$table_names is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderTableMigrator.php on line 25

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderAddressTableMigrator::$table_names is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderAddressTableMigrator.php on line 42

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostToOrderOpTableMigrator::$table_names is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostToOrderOpTableMigrator.php on line 26

Deprecated: Creation of dynamic property Automattic\WooCommerce\Database\Migrations\CustomOrderTable\PostMetaToOrderMetaMigrator::$table_names is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostMetaToOrderMetaMigrator.php on line 43`

The frontend successfully loads, but is plastered in messages like these:

`Deprecated: Creation of dynamic property WC_Countries::$countries is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php on line 51

Deprecated: Creation of dynamic property WC_Cart::$coupon_discount_totals is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-cart.php on line 266

Deprecated: Creation of dynamic property WC_Cart::$coupon_discount_tax_totals is deprecated in /home/customer/www/public_html/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-cart.php on line 266`

There are numerous others depending on which installation I'm looking at so it seems you just need a good sweep of these dynamic class variables to be fully compatible with the new PHP requirement. Thanks!

### Expected behavior

I expect no messages to print out when upgrading my PHP version.

### Actual behavior

Simple notices start appearing due to class variables being created that aren't predefined.

### Steps to reproduce

Upgrade PHP version to 8.2 (my version is 8.2.6). Visit both the frontend and dashboard with error reporting and printing on (or check the PHP error log).

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.1
WP Multisite: ✔
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.6
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wptest_8_
Total Database Size: 26.85MB
Database Data Size: 15.97MB
Database Index Size: 10.88MB
wptest_8_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_8_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wptest_8_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wptest_8_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_8_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wptest_8_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_be_compare_products_shares: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_product_alert_favorites: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_product_alert_favorites_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_product_alert_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_product_alert_signups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_save_later_products: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wptest_8_be_save_later_purchases: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wptest_8_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_email_log: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_icl_languages_translations: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wptest_8_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_icl_mo_files_domains: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_strings: Data: 4.52MB + Index: 6.75MB + Engine InnoDB
wptest_8_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_string_translations: Data: 2.52MB + Index: 0.83MB + Engine InnoDB
wptest_8_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_8_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_icl_translation_status: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wptest_8_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_options: Data: 4.25MB + Index: 0.16MB + Engine InnoDB
wptest_8_postmeta: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wptest_8_posts: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wptest_8_pv_commission: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wptest_8_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_8_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wptest_8_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wptest_8_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_8_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_8_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_8_yith_wapo_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptest_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptest_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptest_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptest_sitemeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wptest_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wptest_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 33
custom_css: 1
customer_groups: 1
nav_menu_item: 5
page: 30
polylang_mo: 2
post: 2
product: 23
product_variation: 18
revision: 20
shipping_option: 2
shop_coupon: 5
shop_order: 115
shop_order_vendor: 4
tm_global_cp: 1
wc_product_tab: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Query Monitor: by John Blackbourn – 3.12.3
WPML Multilingual CMS: by OnTheGoSystems – 4.6.3
Extra Fee for BETRS: by Bolder Elements – 1.0
Classic Editor: by WordPress Contributors – 1.6.3
Email Log: by Sudar – 2.4.8
Multilingual Tools: by OnTheGoSystems – 2.2.3
Multiple Packages for WooCommerce: by Erica Dion – 1.1
Bolder Fees for WooCommerce: by Bolder Elements – 1.5.1
Cart Based Shipping for WooCommerce: by Bolder Elements – 3.4 (modified)
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.1.3
WooCommerce Product Bundles: by WooCommerce – 6.17.3
Save for Later in WooCommerce: by Bolder Elements – 1.2 (modified)
Shipping Cost Limitations for BETRS: by Bolder Elements – 1.0
WooCommerce Table Rate Shipping: by Bolder Elements – 4.3.7
WooCommerce: by Automattic – 7.7.0
WPML Media: by OnTheGoSystems – 2.7.2
WPML String Translation: by OnTheGoSystems – 3.2.5
Extra Fee for BETRS: by Bolder Elements – 1.0
WooCommerce Table Rate Shipping: by Bolder Elements – 4.3.7
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.3.7

### Inactive Plugins (32) ###

Akismet Anti-Spam: by Automattic – 5.1
Bolder Fees for WooCommerce: by Bolder Elements – 1.4.18
Bolder Surveys: by Bolder Elements – 1.1
Contact Form 7: by Takayuki Miyoshi – 5.7.6
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.1.30
Dokan: by weDevs – 3.7.18
Dokan Pro: by weDevs – 3.0.1
Envato Market: by Envato – 2.0.8
Estimate delivery date for WooCommerce: by PI WebSolution – 4.10.11
Flat Fee Option for BETRS: by Bolder Elements – 1.0
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.0
Germanized for WooCommerce: by vendidero – 3.12.2
Multiple Packages for WooCommerce: by Erica Dion – 1.1
OTGS Installer: by OnTheGoSystems – 3.0.0
Polylang: by WP SYNTEX – 3.3.3
Product Alerts for WooCommerce: by Bolder Elements – 2.3.4
Shipping by City for BETRS: by Bolder Elements – 1.2.2
Shipping Per Category for BETRS: by Bolder Elements – 1.0
User Role Editor: by Vladimir Garagulya – 4.63.3
WC Vendors Marketplace: by WC Vendors – 2.4.6
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.7
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Beta Tester: by Mike Jolley – 1.0.3
WooCommerce Blocks: by Automattic – 10.2.0
WooCommerce Extra Shipping Options: by Jeroen Sormani – 1.1.3
WooCommerce Multi Currency Premium: by VillaTheme – 2.1.22.4
WooCommerce Product Bundles Premium: by WPclever.net – 2.8.5
WooCommerce Product Comparison: by Bolder Elements – 2.1
WooCommerce TM Extra Product Options: by themeComplete – 5.0.12.10
WordPress Importer: by wordpressdotorg – 0.8.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2.1
WPC Product Bundles for WooCommerce: by WPClever – 7.1.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #415 - /terms/

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.2.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Product Bundles ###

Database Version: 6.17.3
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-19 12:13:02 -04:00
Options: ✔
Notes: 19
Onboarding: completed

### Action Scheduler ###

Complete: 8
Oldest: 2023-05-18 14:37:10 +0000
Newest: 2023-05-18 14:37:18 +0000

Failed: 10
Oldest: 2023-03-07 13:44:09 +0000
Newest: 2023-05-18 14:37:10 +0000

Pending: 1
Oldest: 2023-05-19 14:37:10 +0000
Newest: 2023-05-19 14:37:10 +0000

### Status report information ###

Generated at: 2023-05-18 10:37:51 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks, we're planning to work on this and some similar issues shortly (and already have some [work in progress](https://github.com/woocommerce/woocommerce/pull/37063)).

**Comment by jorgeatorres** [comment]
Hi,

The specific warnings mentioned here have already been addressed in https://github.com/woocommerce/woocommerce/pull/38565, https://github.com/woocommerce/woocommerce/pull/38569 and https://github.com/woocommerce/woocommerce/pull/38589.
