### ISSUE TITLE
Add a new free extension list for the core profiler

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#38341]
In https://github.com/woocommerce/team-ghidorah/issues/211 page, we have a new set of extensions to render in the new core profiler extensions page.

In order to support a new set of extensions on the new core profiler, add a new list to the API endpoint.

## Acceptance Criteria

Add `obw/core-profiler` to `/wp-admin/wc-admin/onboarding/free-extensions` endpoint. Code is located [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/OnboardingFreeExtensions.php).

`obw/core-profiler` should contain the following extensions:

1. WooCommerce Payments
2. WooCommerce Shipping
3. Jetpack
4. Pinterest
5. MailPoet
6. TikTok
7. Googld Listing and Ads
8. WooCommerce Tax

**Comment by rjchow** [comment]
I think this is done? https://github.com/woocommerce/woocommerce/pull/38418

**Comment by moon0326** [comment]
> I think this is done? #38418

Yup! Closing it as done
