### ISSUE TITLE
Stats overview -> Total sales thousand separator bug

### ISSUE THREAD

**Issue by Estalhun** [woothemes/woocommerce#38361]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Wrong display of the thousand separator in the field Total sales on the WC Home page if the thousand separator is `&#160;`

### Expected behavior

Show a no-break-space instead of the code.

### Actual behavior

It shows `116&#160;520 Ft` instead of 116&nbsp;520 Ft.

### Steps to reproduce

1. Set `&#160;` as thousand separator
2. Go to WC's home page.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://gallmet.hu
Site address (URL): https://gallmet.hu
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.6.0
Log Directory Writable: ✔
WP Version: 6.2.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: hu_HU
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 1200
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.5.19-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wpmy_
Total Database Size: 540.29MB
Database Data Size: 358.86MB
Database Index Size: 181.43MB
****_woocommerce_sessions: Data: 60.09MB + Index: 2.23MB + Engine InnoDB
****_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
****_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
****_woocommerce_order_itemmeta: Data: 19.16MB + Index: 12.23MB + Engine InnoDB
****_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
****_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_actionscheduler_actions: Data: 4.27MB + Index: 1.55MB + Engine InnoDB
****_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_actionscheduler_logs: Data: 10.52MB + Index: 0.91MB + Engine InnoDB
****_aiowps_audit_log: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
****_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_aiowps_login_activity: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
****_aiowps_login_lockdown: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
****_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_cartbounty_pro: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
****_cartbounty_pro_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_cartbounty_pro_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_collabnotes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
****_comments: Data: 12.58MB + Index: 17.47MB + Engine InnoDB
****_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_eum_logs: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
****_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
****_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
****_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
****_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
****_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_generalnotes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_gens_raf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_gens_rafmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
****_is_inverted_index: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
****_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_litespeed_img_optm: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
****_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
****_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_litespeed_url: Data: 1.52MB + Index: 1.64MB + Engine InnoDB
****_litespeed_url_file: Data: 3.52MB + Index: 8.91MB + Engine InnoDB
****_loginizer_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_mailerlite_checkouts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
****_mailerlite_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_ml_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_odb_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_options: Data: 26.16MB + Index: 15.05MB + Engine InnoDB
****_plugin_notes_plus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_pmr_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_postexpirator_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_postmeta: Data: 59.16MB + Index: 67.66MB + Engine InnoDB
****_posts: Data: 17.47MB + Index: 5.86MB + Engine InnoDB
****_rp4wp_cache: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
****_scheduled_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_seopress_significant_keywords: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
****_termmeta: Data: 0.09MB + Index: 0.23MB + Engine InnoDB
****_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
****_term_relationships: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
****_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
****_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_trp_dictionary_hu_hu_de_de: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
****_trp_dictionary_hu_hu_en_gb: Data: 9.52MB + Index: 3.36MB + Engine InnoDB
****_trp_dictionary_hu_hu_pl_pl: Data: 13.58MB + Index: 9.50MB + Engine InnoDB
****_trp_dictionary_hu_hu_ro_ro: Data: 9.52MB + Index: 3.25MB + Engine InnoDB
****_trp_dictionary_hu_hu_sk_sk: Data: 8.52MB + Index: 3.23MB + Engine InnoDB
****_trp_gettext_de_de: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
****_trp_gettext_en_gb: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
****_trp_gettext_hu_hu: Data: 2.52MB + Index: 0.92MB + Engine InnoDB
****_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
****_trp_gettext_original_strings: Data: 7.58MB + Index: 2.52MB + Engine InnoDB
****_trp_gettext_pl_pl: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
****_trp_gettext_ro_ro: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
****_trp_gettext_sk_sk: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
****_trp_original_meta: Data: 2.52MB + Index: 3.47MB + Engine InnoDB
****_trp_original_strings: Data: 5.52MB + Index: 2.52MB + Engine InnoDB
****_trp_original_strings_bak: Data: 8.52MB + Index: 5.55MB + Engine InnoDB
****_usermeta: Data: 1.52MB + Index: 4.55MB + Engine InnoDB
****_users: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
****_viwcr_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_vp_woo_pont_mpl_shipments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
****_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
****_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wc_customer_lookup: Data: 0.33MB + Index: 0.19MB + Engine InnoDB
****_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
****_wc_order_product_lookup: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
****_wc_order_stats: Data: 0.52MB + Index: 0.33MB + Engine InnoDB
****_wc_order_tax_lookup: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
****_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
****_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wdr_order_item_discounts: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
****_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_csv_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_csv_uploads_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_csv_uploads_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_csv_uploads_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_logging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_logging_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_logging_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_logging_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_media_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_media_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_media_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_menus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_menus_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_menus_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_menus_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wpda_project_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wpda_project_page_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_page_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_page_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_table_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_table_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_project_table_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_publisher: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wpda_publisher_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_publisher_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_publisher_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_design: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_design_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_design_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_design_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_settings_BACKUP_20230321134756: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_settings_BACKUP_20230321134804: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpda_table_settings_BACKUP_20230411125941: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wpml_mails: Data: 33.52MB + Index: 0.00MB + Engine InnoDB
****_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
****_wps_woocommerce_simplepay_payment_gateway_ipn: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
****_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

astra_adv_header: 6
astra-advanced-hook: 20
attachment: 1088
bsf-sidebar: 11
cartflows_flow: 1
cartflows_step: 2
custom_css: 2
customize_changeset: 72
elementor_library: 113
is_search_form: 2
language_switcher: 6
nav_menu_item: 206
oembed_cache: 337
page: 93
pi_dpmw_rules: 2
popup: 2
popup_theme: 8
post: 488
product: 44
pt_view: 1
revision: 722
rp4wp_link: 1386
sa_slider: 2
seopress_404: 1400
seopress_bot: 4
seopress_schemas: 1
shop_coupon: 51
shop_order: 3418
shop_order_refund: 1
testimonials: 3
wc_afrsm: 2
wc_dynamic_pricing: 13
woo_coupon_reminder: 2
woo_mb_template: 23
wp_show_posts: 1
wpforms: 1
ywrac_cart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (90) ###

Action Scheduler: by Automattic – 3.6.0
Ivory Search: by Ivory Search – 5.5.1
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout: by PI Websolution – 2.1.62
Advanced Google reCAPTCHA: by WP Concern – 1.0.14
All In One WP Security: by All In One WP Security & Firewall Team – 5.1.8
Application Passwords: by George Stephanis – 0.1.3
Astra Pro: by Brainstorm Force – 4.1.5
Astra Widgets: by Brainstorm Force – 1.2.12
Better Plugin Compatibility Control: by Oliver Schlöbe – 6.0.0
Booster Plus for WooCommerce: by Pluggabl LLC – 6.0.5
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Come Back!: by Sanjeev Aryal – 1.3.4
Currency Exchange for WooCommerce: by BeRocket – 3.5.7.8
Customiser Search: by Brainstorm Force – 1.1.6
Disable Feeds: by Samir Shah
BBpress support by Matthew Sigley – 1.4.4

Display Order Details for WooCommerce: by Pinal Shah – 1.0
Display Posts: by Bill Erickson – 3.0.2
Download Plugins and Themes from Dashboard: by WPFactory – 1.8.2
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Easy WP SMTP: by Easy WP SMTP – 2.1.0
Elementor Pro: by Elementor.com – 3.13.1
Elementor: by Elementor.com – 3.13.2
Email Address Encoder: by Till Krüss – 1.0.22
Faster Updates: by WP Core Contributors – 0.3.2
GDPR Cookie Compliance: by Moove Agency – 4.12.2
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
HelloPack: by HelloWP Ltd – 1.2.20
Hungarian Pickup Points & Shipping Labels for WooCommerce: by Viszt Péter – 2.5.0.2
Image Regenerate & Select Crop: by Iulia Cazan – 7.1.0
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.12

Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 5.7.4
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.10
LH Add Media from URL: by Peter Shaw – 1.22
List category posts: by Fernando Briano – 0.88.1
LiteSpeed Cache: by LiteSpeed Technologies – 5.4
Loco Translate: by Tim Whitlock – 2.6.4
Loginizer: by Softaculous – 1.7.9
Media Sync: by Erol Živina – 1.3.1
Menu Duplicator: by Jeremy Ross – 0.6
Meta Box: by MetaBox.io – 5.6.18
My Custom Functions: by Space X-Chimp – 4.51
MailerLite - Signup forms (official): by MailerLite – 1.6.7
Pages with category and tag: by YAHMAN – 0.9.0
WooCommerce Partial COD - Payment Gateway Restrictions & Fees: by zendcrew – 1.2
Peter's Post Notes: by Peter Keung – 1.6.5
Phoenix Media Rename: by crossi72 – 3.10.5
PixelYourSite: by PixelYourSite – 9.3.7
Plugin Notes Plus: by Jamie Bergen – 1.2.6
PowerPack Lite for Elementor: by IdeaBox Creations – 2.7.5
Print-O-Matic: by twinpictures – 2.1.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Related Posts for WordPress: by Never5 – 2.1.4
Rollback Update Failure: by WP Core Contributors – 5.2.0
Search Regex: by John Godley – 3.0.6
Sidebar Manager: by Brainstorm Force – 1.1.7
OTP SimplePay Gateway for WooCommerce: by Cone Development – 2.5.6
Slide Anything - Responsive Content / HTML Slider and Carousel: by  – 2.4.9
Tag Groups: by TaxoPress – 2.0.2
TranslatePress - Business: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.2.6

TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.5.3

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.4.26

User Role Editor: by Vladimir Garagulya – 4.63.3
Visibility Logic for Elementor: by StaxWP – 2.3.4
Pont shipping for Woocommerce: by szathmari.hu – 7.4
Webshippy Order Sync: by Webshippy Ltd. – 1.7.1
Conditional Display for Mobile by WonderPlugin: by Magic Hills Pty Ltd – 1.2
WooCommerce Cancel Abandoned Order: by studio RVOLA – 2.0.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.2
Combo Offers WooCommerce: by QuanticEdge – 2.9
Woo Discount Rules PRO 2.0: by Flycart – 2.6.0
Woo Discount Rules: by Flycart – 2.6.0
MailerLite - WooCommerce integration: by MailerLite – 1.8.4
CartBounty Pro - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 9.10
Booster for WooCommerce: by Pluggabl LLC – 6.0.5
WooCommerce PayPal Payments: by WooCommerce – 2.0.4
WooCommerce: by Automattic – 7.6.1 (update to version 7.7.0 is available)
Woocommerce Wintax Integration: by Novitax Kft. – 1.0.2
WordPress Importer: by wordpressdotorg – 0.8.1
WP BrowserUpdate: by Marco Steinbrecher – 4.6
WP Crontrol: by John Blackbourn & contributors – 1.15.2
WP IE Buster: by Qrac – 1.4.1
WP Last Modified Info: by Sayan Datta – 1.8.7
WP Mail Logging: by WP Mail Logging Team – 1.11.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.7
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.15

WP-Matomo Integration: by André Bräkling – 1.0.27
SEOPress PRO: by The SEO Guys at SEOPress – 6.6.1
SEOPress: by The SEO Guys at SEOPress – 6.6.3
Refer a Friend for WooCommerce PREMIUM: by WPGens – 2.3.18

### Inactive Plugins (21) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.1.1
All-in-One WP Migration: by ServMask – 7.74
Change Prices with Time for WooCommerce: by Igor Benić – 1.9.1
Conditional Discount Rules For WooCommerce Checkout Premium: by theDotstore – 2.0.9
Database Collation Fix: by Dave Jesch – 1.2.9
Easy Updates Manager: by Easy Updates Manager Team – 9.0.15
Min Max Default Quantity for WooCommerce: by WPFactory – 4.5.7
Popup Maker: by Popup Maker – 1.18.1
Query Monitor: by John Blackbourn – 3.12.2
Recent Posts Widget Extended: by Ga Satrya – 2.0.2
SMNTCS Quantity Increment Buttons for WooCommerce: by Niels Lange – 2.3
Transients Manager: by WPBeginner – 2.0.3
TranslatePress - Front-end translation using admin-ajax: by Cozmoslabs
Razvan Mocanu – 1.0.0

Utánvét Ellenőr: by Utánvét Ellenőr – 1.9.1
WooCommerce Direct Checkout: by QuadLayers – 3.1.0
WooCommerce SimplePay Gateway (3DS, SDK2): by Transgate – 2.5.5
Woo Total Sales: by Sh Shanker – 3.1.4
WP Data Access Premium: by Passionate Programmers B.V. – 5.3.9
WP File Manager: by mndpsingh287 – 7.1.9
YITH WooCommerce Product Bundles: by YITH – 1.23.0

### Dropin Plugins (2) ###

maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Must Use Plugins (3) ###

Elementor Safe Mode: by Elementor.com – 1.0.0
Health Check Troubleshooting Mode: by  – 1.8.1
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.11

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wooco (wooco)
woosg (woosg)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #9538 - /shop/
Basket: #33 - /cart/
Checkout: #9493 - /checkout/
My account: #35 - /my-account/
Terms and conditions: #1985 - /aszf/

### Theme ###

Name: Astra
Version: 4.1.4 (update to version 4.1.5 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Számlázz.hu ###

PRO version: ✔
Path: /wp-content/uploads/wc_szamlazz
IPN URL: *****************************
Payment methods: Array
(
    [bacs] => Array
        (
            [deadline] => 
            [complete] => 
            [proform] => 1
            [deposit] => 
            [name] => 
            [auto_disabled] => 
        )

    [simplepay-gateway] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 
            [name] => 
            [auto_disabled] => 
        )

    [ppcp-gateway] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 
            [name] => 
            [auto_disabled] => 
        )

    [cod] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 
            [name] => 
            [auto_disabled] => 
        )

)

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: HU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-20 07:41:34 +02:00
Options: ✔
Notes: 156
Onboarding: completed

### Action Scheduler ###

Complete: 4,974
Oldest: 2023-05-12 10:57:34 +0200
Newest: 2023-05-19 10:48:06 +0200

Failed: 587
Oldest: 2023-03-10 04:02:04 +0100
Newest: 2023-05-08 08:52:06 +0200

Pending: 17
Oldest: 2023-05-19 10:53:06 +0200
Newest: 2023-05-20 08:20:49 +0200

### Status report information ###

Generated at: 2023-05-19 10:53:34 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Show a no-break-space

@Estalhun Using a [unicode non-breaking space](https://unicode-explorer.com/c/00A0) works with both the shop and the analytics screens. I'll close the issue as the unicode character will work. If you feel there is a significant reason why html encoded charaters should be supported please let us know.

**Comment by Estalhun** [comment]
Hi @rrennick ,

Just copy & paste the character (not the HTML or Unicode entity) from [https://unicode-explorer.com/c/00A0](https://unicode-explorer.com/c/00A0) to the "Thousand Separator" field. It has the same effect.

Regards,
@Estalhun

**Comment by rrennick** [comment]
> It has the same effect.

@Estalhun If you add **any** html encoded entity to the field you will see the same effect. The analytics screens are written react which doesn't support html encoded entities unless you use the [dangerouslySetInnerHTML](https://legacy.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) which isn't used in WC analytics due to the security risk.

**Comment by Estalhun** [comment]
@rrennick So, if I would like to use no-break-space as thousand separator, I have to use unicode entity because neither ` ` character nor any HMTL entity will not work?
The space is the default thousand separator in the EU, but the breaking space looks ugly at the end of line because the line can break at the space:
Correct: `1 234 567`
Ugly: 1<br/>234 567

I think this 'feature' should be documented or every number should be in `<span style="white-space: nowrap;">1 234 567</span>`.

Regards,
@Estalhun

**Comment by rrennick** [comment]
> if I would like to use no-break-space as thousand separator, I have to use unicode entity because neither   character nor any HMTL entity will not work?

That's correct.
