### ISSUE TITLE
[Enhancement]: Show Delivery Checkbox unchecked by default

### ISSUE THREAD

**Issue by lgdelai** [woothemes/woocommerce#38360]
### Describe the solution you'd like

Hello.

I found a usability or UX issue that I would like to resolve.

When a customer’s address is not part of the delivery coverage area.
**And** when this address allows “local pickup” this option “**local pickup**” is automatically checked at checkout.

This way, inattentive customers, who live in other cities, can buy on the site, believing that they received the product at home, when in fact they should pick it up at the site.

**To improve the user experience, wouldn’t it be interesting that:**

Instead of one of the delivery options being **always** checked, the customer should **manually choose** which delivery method he wants (_even if there is only 1 method available_).  

This way, as soon as the customer tries to send the order, he will receive an alert asking him to choose the desired shipping method.  
Not taking the risk if you buy thinking you will receive it at home, when in fact you will have to pick up the product.

Avoiding in this way, later problems of cancellation of purchases.

Thanks.

**Comment by barryhughes** [comment]
@lgdelai,

Have you tried reordering your shipping methods to place Local Pickup last in the list?

<div align="center"><img width="600" alt="Screenshot 2023-05-29 at 09 54 21" src="https://github.com/woocommerce/woocommerce/assets/3594411/e14b6f0e-6090-4294-8bfd-9bd01cefef98"></div>

The first matching method is the one that is selected by default.

**Comment by rrennick** [comment]
Closing for lack of feedback.
