### ISSUE TITLE
Build Initial Documentation Manifest Generation Tool

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#38377]
### Prerequisites

* https://github.com/woocommerce/woocommerce/issues/38376: Once we have a preliminary plugin that is able to import a manifest file we can start to build the tool that generates it.

### Description

We will need a tool that can be used in a repository to generate a manifest file for the documentation ingestion plugin. This tool is intended to be published to NPM and used in other repositories, so, keep that in mind. It is likely that this task will cause further iteration on the ingestion plugin itself. Don't feel like you need to stick strictly to the existing manifest and make improvements where it makes sense.

### Acceptance Criteria

* A CLI tool written in TS that can be used both locally and from a GitHub Action. It should make use of the existing Cli core infrastructure we have written.
  * One consideration with respect to the CLI core is that we want to publish this tool. As a dependency that isn't published, we may run into problems using it. This may mean not using it, or, it may mean publishing it. Let's figure out what makes sense here. As a good rule we should try to avoid unnecessarily publishing NPM packages that only provide very specific internal value though.
* It will generate a JSON manifest that describes basic information architecture for WordPress posts that correspond to documentation within a directory. The directory structure should define the basic IA for the docs.
* The manifest file will also include absolute URLs to content that must be downloaded. It should identify pages in a way that can cross-link and the manifest should provide mapping so that the plugin can generate the links correctly.
  * One consideration here is this may actually not be necessary. Technically the manifest contains all of the markdown files that are linked to, and if we're storing the directory structure in the manifest, it can use that to generate the links without any conversion.
* The formatter should consider including a version number early-on so that there is backward compatibility if we want to add versioned documentation support.
* It should support extracting media files from the markdown and generating absolute URLs using the commonly used `![some text](path-to-some-file.ext)` format. Supporting both absolute and relative URLs here can support flexibility.
  * One consideration here is that, if we're just having people upload media externally, it might make sense to forgo this entirely. If we don't let them parse media in this way and give an error in the plugin then we can discourage a use-case we don't want to support.

**Comment by samueljseay** [comment]
I didn't notice this wasn't in the cycle. This is done.
