### ISSUE TITLE
Investigate Unnecessary Pull Request Check Execution

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#38375]
### Description

While we know that we are running pull request checks unnecessarily, there is a very large body of possible definitions of "necessity" here. Some are easy, for instance, not running them on markdown file changes. There are more complicated opportunities though, such as using caching to avoid re-running unnecessary checks in future updates to PRs. Given how touchy some of these improvements could be we need to look at our checks and consider what improvements can be made to minimize how frequently we are running checks that we don't need to. Some ideas:

* Do we need to run unit tests for _everything_ all the time?
* Do we need to run PHPUnit tests for JS-only changes that won't impact them?
* Do we need to run E2E tests all the time?
* What other slow checks could we avoid running unnecessarily? When can we avoid them?

### Acceptance Criteria

Before we can begin working on this we need to collectively decide what is and isn't worth doing. The output of this should be a proposal that we can use to then create specific issues to add to this project.

**Comment by ObliviousHarmony** [comment]
We have other plugins in the monorepo that don't need their unit tests run too.

Something else to consider is that it might be good for this to be configurable rather than hardcoded. Like a YAML file that says what workflows to run on what situation, who knows!

**Comment by psealock** [comment]
Draft p2 https://wordpress.com/post/wooengineering.wordpress.com/3904

**Comment by ObliviousHarmony** [comment]
I've gone through all of the PR checks and categorized them to help inform this work:

## Categories

### Labeling
* `pr-project-label.yml`: Labels the pull requests according to the `.github/project-pr-labeler.yml` config file. This assigns labels depending on the directory that was being edited in the PR.
* `community-label.yml`: Labels the pull request depending on whether or not the user is a community contributor.
Unit Testing
* `pr-unit-tests.yml`: Runs the PHPUnit test matrix for WooCommerce Core. This is sharded for performance.
* `pr-test-other-plugins.yml`: Runs the unit tests for the WooCommerce Docs plugin.
* `pr-test-js.yml`: Run the unit tests for the WooCommerce Admin client and dependencies.

### E2E Testing
* `pr-smoke-test.yml`: Runs the smoke tests when a PR is labeled to run them.
* `pr-build-and-e2e-tests.yml`: Runs the E2E tests, API tests, and performance tests.
* `cot-pr-build-and-e2e-tests.yml`: Runs the E2E tests with COT enabled.

### Linting
* `pr-lint-js.yml`: Lints all of the JS packages and annotates the code.
* `pr-lint-monorepo.yml`: Checks for changelog files.
* `pr-code-sniff.yml`: Runs PHPCS on WooCommerce Core.
* `pr-lint-markdown.yml`: Lints markdown files in the monorepo.

### Miscellaneous
* `test-assistant-pr-scrub.yml`: Notifies the appropriate Slack channel of new PRs and the associated SLA for reviewing them.
* `pr-build-live-branches.yml`: Builds the WooCommerce plugin and sends it to Jetpack so that it can be used on Jurassic.ninja.
* `changelog-auto-add.yml`: Automatically adds a changelog file based on the PR description template.
* `pr-highlight-changes.yml`: Runs the Code Analyzer and highlights changes to template files.

As far as I can tell there are a few boundaries we can use to decide when to execute workflows:

* **Plugins**: The monorepo currently contains a number of different plugins that all need their own linting and tests. We shouldn’t be running checks for plugins other than the one being modified in a PR. This will help us better support the development of plugins like WooCommerce AI that don’t require Core’s expensive tests to run. There are also some plugin-specific workflows like Live Branches that we can avoid executing unnecessarily.
* **Build Input File Changes**: As far as I can tell, unless a PR changes a file that results in a different build output, there is no reason to run linting and tests. This is important for supporting documentation efforts because there’s no reason to wait on expensive tests that are already known to be passing.
* **Untouched Dependencies**: When a project is changed we don’t really need to run checks against any of its dependencies. We only need to lint and test the project that changed, but we do need to run tests in everything downstream in the dependency graph. I don’t think we need to lint downstream projects though since their code wasn’t changed.
* **Programming Language**: This one requires a bit more investigation, but do we need to run the expensive PHPUnit tests when only JS files have changed? Do we need to run the JS tests when only PHP files have changed? In my experience unit tests don’t cross the frontend/backend divide and we can definitely save time if that assumption is true.

With this and the above workflows in mind I'm going to think about this a little bit more and then create a new GitHub issue to move forward with any specific proposed changes. I wager this will come as part of a larger workflow refactoring too.
