### ISSUE TITLE
[Enhancement]: Remove the sticky admin header

### ISSUE THREAD

**Issue by mondalaci** [woothemes/woocommerce#38385]
### Describe the solution you'd like

When editing orders, there’s a sticky header featuring the “Edit Order” title and an “Activity” button, which occupies precious vertical space for no good reason.

![Screenshot from 2023-05-21 11-57-42](https://github.com/woocommerce/woocommerce/assets/300402/2acf1594-b599-4391-88a6-6187e23ee3f5)

I strongly believe that this header is a misfeature, it shouldn’t exist to begin width, and at the very least, users should be able to disable it without any custom code.

Related forum posts:
- https://wordpress.org/support/topic/how-to-remove-the-sticky-admin-header-natively/
- https://wordpress.org/support/topic/sticky-admin-headers/

**Comment by pmcpinto** [comment]
Hi László,

Thank you for taking the time to share this feedback. 

Regarding the Admin header, we plan to reassess its utility and purpose. However, we currently cannot provide a specific timeline for this review. Therefore, we'll close this issue for the time being. Your input is highly appreciated, and we thank you for your patience and understanding.
