### ISSUE TITLE
ArgumentCountError: 2 arguments are required, 1 given in class-wc-report-customer-list.php on line 56

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#38384]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When clicking the icon to link customer to orders, the action fails with "Your Site is Experiencing a Technical Issue", although the action seems to be carried out.

### Expected behavior

The page should be updated without error.

### Actual behavior

```
An error of type E_ERROR was caused in line 56 of the file /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php. Error message: Uncaught ArgumentCountError: 2 arguments are required, 1 given in /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php:56
Stack trace:
#0 /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php(56): sprintf()
#1 /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php(177): WC_Report_Customer_List->output_report()
#2 /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php(81): WC_Admin_Reports::get_report()
#3 /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php(36): include_once('/home/behappyin...')
#4 /home/behappyinlife/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(284): WC_Admin_Reports::output()
#5 /home/behappyinlife/public_html/wp-includes/class-wp-hook.php(308): WC_Admin_Menus->reports_page()
#6 /home/behappyinlife/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /home/behappyinlife/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/behappyinlife/public_html/wp-admin/admin.php(259): do_action()
#9 {main}
  thrown
```

### Steps to reproduce

1. Go to Reports > Customers > Customer List
2. Click the chain/link icon to link a customer to their (guest) orders

### WordPress Environment ###

WordPress address (URL): https://www.behappyinlife.com
Site address (URL): https://www.behappyinlife.com
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.6.0
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.13-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wpbhil_
Total Database Size: 298.78MB
Database Data Size: 184.72MB
Database Index Size: 114.06MB
wpbhil_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wpbhil_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_woocommerce_downloadable_product_permissions: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wpbhil_woocommerce_order_items: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wpbhil_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wpbhil_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbhil_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbhil_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_actionscheduler_actions: Data: 3.28MB + Index: 3.28MB + Engine InnoDB
wpbhil_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_actionscheduler_logs: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wpbhil_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_blc_instances: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wpbhil_blc_links: Data: 0.44MB + Index: 0.13MB + Engine InnoDB
wpbhil_blc_synch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_comments: Data: 0.38MB + Index: 0.41MB + Engine InnoDB
wpbhil_et_bloom_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_ewwwio_images: Data: 2.52MB + Index: 1.67MB + Engine InnoDB
wpbhil_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_itsec_bans: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wpbhil_itsec_dashboard_events: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wpbhil_itsec_distributed_storage: Data: 10.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_itsec_lockouts: Data: 0.30MB + Index: 0.08MB + Engine InnoDB
wpbhil_itsec_logs: Data: 3.02MB + Index: 0.47MB + Engine InnoDB
wpbhil_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_iwp_file_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_iwp_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_mclean_refs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpbhil_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_options: Data: 6.50MB + Index: 0.20MB + Engine InnoDB
wpbhil_postmeta: Data: 26.56MB + Index: 10.03MB + Engine InnoDB
wpbhil_posts: Data: 12.52MB + Index: 1.52MB + Engine InnoDB
wpbhil_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_rank_math_analytics_adsense: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_rank_math_analytics_ga: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wpbhil_rank_math_analytics_gsc: Data: 31.56MB + Index: 50.19MB + Engine InnoDB
wpbhil_rank_math_analytics_inspections: Data: 0.50MB + Index: 0.11MB + Engine InnoDB
wpbhil_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_rank_math_analytics_objects: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wpbhil_rank_math_internal_links: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wpbhil_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpbhil_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_redirection_404: Data: 36.56MB + Index: 15.66MB + Engine InnoDB
wpbhil_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_redirection_items: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpbhil_redirection_logs: Data: 1.50MB + Index: 0.22MB + Engine InnoDB
wpbhil_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbhil_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_term_relationships: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
wpbhil_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_usermeta: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wpbhil_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpbhil_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpbhil_wc_download_log: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbhil_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wpbhil_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpbhil_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbhil_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpbhil_wpmlautoresponderemails: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wpmlautoresponders: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wpmlautorespondersforms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlautoresponderslists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlbounces: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlclicks: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wpmlcontents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlcountries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlemails: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wpbhil_wpmlfields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbhil_wpmlfieldsforms: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbhil_wpmlfieldslists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlforms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlgroups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wpmlhistoriesattachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlhistorieslists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlhistory: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wpmllatestposts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmllatestpostssubscriptions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmllinks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wpmlmailinglists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmloptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlorders: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wpmlposts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlsubscribermetas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlsubscribers: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wpbhil_wpmlsubscriberslists: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wpbhil_wpmlsubscribersoptions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbhil_wpmltemplates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wpmlthemes: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wpbhil_wpmlunsubscribes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbhil_wptc_activity_log: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wpbhil_wptc_backups: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpbhil_wptc_current_process: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wptc_inc_exc_contents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbhil_wptc_options: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpbhil_wptc_processed_files: Data: 34.58MB + Index: 22.16MB + Engine InnoDB
wpbhil_wptc_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbhil_wptc_processed_restored_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 396
flamingo_contact: 1184
flamingo_inbound: 1389
home_page: 4
itsec-dash-card: 5
itsec-dashboard: 1
iwp_log: 4021
nav_menu_item: 96
newsletter: 4
oembed_cache: 13
page: 80
portfolio: 1
post: 41
product: 6
product_variation: 39
products: 1
revision: 182
shop_coupon: 3
shop_order: 564
shop_order_refund: 14
slider: 3
taxopress_logs: 3
testimonial: 311
wpcf7_contact_form: 5
wpsc-product: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Backup and Staging by WP Time Capsule: by Revmakx – 1.22.14
InfiniteWP - Client: by Revmakx – 1.11.1
Akismet Anti-Spam: by Automattic – 5.1
Angell EYE Updater: by Angell EYE – 2.0.18
iThemes Security: by iThemes – 8.1.6
Broken Link Checker: by WPMU DEV – 2.1.0
CAOS Pro: by Daan from Daan.dev – 2.3.1
CF7 Google Captcha Load After Page: by Amit Bhalani – 3.0.1
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7 - Dynamic Text Extension: by SevenSpark
AuRise Creative – 3.2

Honeypot for Contact Form 7: by Nocean – 2.1.1
Contact Form 7: by Takayuki Miyoshi – 5.7.6
Currency Switcher for WooCommerce: by WP Wham – 2.15.1
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.2.4
Disable Genesis Schema: by Bill Erickson – 1.0
Easy Testimonials: by Gold Plugins – 3.9.5
EWWW Image Optimizer: by Exactly WWW – 7.0.0
Flamingo: by Takayuki Miyoshi – 2.4
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 8.3.10
Get Business Online Customisations: by Get Business Online Consulting – 3.54
Genesis Shortcode Generator: by Josh Mallard – 2.0.1
MonsterInsights Pro: by MonsterInsights – 8.14.1
CAOS: by Daan from Daan.dev – 4.5.0
OMGF: by Daan from Daan.dev – 5.5.6
Image Regenerate & Select Crop: by Iulia Cazan – 7.1.0
Jetpack: by Automattic – 12.1
Linear Checkout for WooCommerce by Cartimize: by Cartimize – 1.1.7
LuckyWP Table of Contents: by LuckyWP – 2.1.4
Media File Renamer: Rename Files (Manual, Auto & AI): by Jordy Meow – 5.6.2
Newsletters - Embedded Images: by Tribulant Software – 1.7
Newsletters - Google Analytics: by Tribulant Software – 1.5
Newsletters - WooCommerce Subscribers: by Tribulant – 1.7
PayPal for WooCommerce: by Angell EYE – 4.0.13
Redirection: by John Godley – 5.3.10
Rank Math SEO PRO: by Rank Math – 3.0.36
Rank Math SEO: by Rank Math – 1.0.115
TaxoPress: by TaxoPress – 3.7.4
SMTP Mailer: by naa986 – 1.1.6
Product Feed PRO for WooCommerce: by AdTribes.io – 12.6.4
WooCommerce Stripe Gateway: by WooCommerce – 7.4.0
WooCommerce: by Automattic – 7.6.1 (update to version 7.7.0 is available)
WP Accessibility: by Joe Dolson – 2.0.1
WP Fastest Cache Premium: by Emre Vona – 1.6.8
WP Fastest Cache: by Emre Vona – 1.1.5
Newsletters: by Tribulant – 4.8.9
WPMU DEV Dashboard: by WPMU DEV – 4.11.18

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (2) ###

InfiniteWP - Client Loader: by Revmakx – 1.0.1
WP Time Capsule: by Revmakx –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #937 - /books-products/
Cart: #1129 - /cart/
Checkout: #1130 - /checkout/
My account: #1132 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Beautiful Pro Theme
Version: 1.1
Author URL: https://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.4.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: beautiful-pro/woocommerce/emails/email-styles.php version 4.0.0 is out of date. The core version is 7.4.0
Outdated Templates: ❌
					
					
						Learn how to update

### Currency Switcher Settings ###

WooCommerce Currency Switcher Plugin: yes
Currency switcher on per product basis: yes
Revert to shop's default currency on checkout: no
Apply currency conversion to fixed amount coupons: yes
Add currency selector for fixed amount coupons: no
Apply currency conversion to shipping amount: 
Apply currency conversion to minimum order amount required for free shipping: yes
Apply currency conversion to cart fees: yes
Apply currency conversion to WooCommerce Price Filter Widget: 
Switcher placement: Array
(
    [0] => single_page_after_price_select
)
Switcher wrapper: %currency_switcher%
Switcher item format: %currency_code%
Link list switcher separator: 
Reposition page after currency switch: yes
Rounding: round_up
Number of decimals: 2
Make "pretty price": yes
Apply rounding and "pretty price" to shipping rates: yes
Apply rounding and "pretty price" to shop's default currency: no
Order currency: yes
Format price: yes
Currencies: 
Currency (shop's default): [AUD] Australian dollar
Total additional currencies: 1
Additional currency #1: yes
alg_currency_switcher_currency_1: USD
Exchange Rates: 
Exchange rates updates: daily
Exchange rates server: georgia
Free Currency Converter API Key: not set
CoinMarketCap API Key: 
Exchange rates offset: 3
#1 AUD/USD (United States (US) dollar): 0.720091128
alg_currency_switcher_exchange_rate_server_AUD_USD: default
alg_currency_switcher_exchange_rate_offset_type_AUD_USD: default
percent: 0
Currency Countries (by IP): 
Currency Countries (by IP): 
Enter countries as comma separated text: 
Override country: 
#1 [USD] United States (US) dollar: Array
(
    [0] => 
)
Currency Languages (Locales): 
Currency Languages (Locales): 
Enter locales as comma separated text: 
Always use locale to assign currency: 
#1 [USD] United States (US) dollar: Array
(
    [0] => 
)
Price Formats: yes
#0 [AUD] Australian dollar: left
Additional currency code position (optional): none
Thousand separator: ,
Decimal separator: .
Number of decimals: 2
Currency Symbol: AUD
#1 [USD] United States (US) dollar: left
Additional currency code position (optional): none
Thousand separator: ,
Decimal separator: .
Number of decimals: 2
Currency Symbol: USD
Flags: 
#0 [AUD] Australian dollar: 
#1 [USD] United States (US) dollar: 
Price conversion method: simple
Fix mini cart: yes
Disable on URI: 
Additional price filters: 
Price filters to remove: 
Session save path: 

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-21 03:29:47 +10:00
Options: ✔
Notes: 27
Onboarding: completed

### Action Scheduler ###

Complete: 648
Oldest: 2023-04-20 21:40:16 +1000
Newest: 2023-05-21 04:10:05 +1000

Pending: 3
Oldest: 2023-05-22 04:10:05 +1000
Newest: 2023-05-26 15:10:08 +1000

### Status report information ###

Generated at: 2023-05-21 11:32:06 +10:00

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@galbaras Do you still see this issue with the latest version of WooCommerce? If so, could you provide a screenshot showing the icon you are clicking on?

**Comment by galbaras** [comment]
Just checked. This still happens :(

**Comment by jonathansadowski** [comment]
Thanks for following up @galbaras. Are you able to provide the screenshot showing the icon you were clicking on when you received this error as previously requested?

Also, can you confirm that you're able to reproduce this issue with other plugins deactivated and only WooCommerce active?

**Comment by galbaras** [comment]
The icon I'm clicking is ![image](https://github.com/woocommerce/woocommerce/assets/7981897/5d9f8b86-f5b1-4a99-bb24-26329bcb5439).

Yes, I can confirm this still happens with only WooCommerce active.

**Comment by mikkamp** [comment]
I just wanted to log some additional reproduction steps (as it took a bit of effort to reproduce):

- Make sure this is tested on a site with HPOS disabled (the status isn't filtered correctly with HPOS so the button never shows up)
- Create a guest order with a specific customer email
- Create a second order but this time use a registered account with the same email address as the one from the guest order
- Go to WooCommerce > Reports > Customers > Customers list and view the link previous orders button
![image](https://github.com/woocommerce/woocommerce/assets/11388669/add5cf6c-fa74-4c93-b46e-cb934bb58126)
- Click the action and confirm the PHP error
![image](https://github.com/woocommerce/woocommerce/assets/11388669/30ded1ba-58fb-4b41-9f24-0d2541ac3977)
- Go to WooCommerce > Status > Logs > Fatal Error Log to view the details of the error
```
2024-07-05T12:19:04+00:00 Critical Uncaught ArgumentCountError: 2 arguments are required, 1 given in wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php:56  
Additional context
{
    "error": {
        "type": 1,
        "file": "wp-content\/plugins\/woocommerce\/includes\/admin\/reports\/class-wc-report-customer-list.php",
        "line": 56
    },
    "backtrace": [
        "",
        "#0 wp-content\/plugins\/woocommerce\/includes\/admin\/reports\/class-wc-report-customer-list.php(56): sprintf()",
        "#1 wp-content\/plugins\/woocommerce\/includes\/admin\/class-wc-admin-reports.php(177): WC_Report_Customer_List->output_report()",
        "#2 wp-content\/plugins\/woocommerce\/includes\/admin\/views\/html-admin-page-reports.php(81): WC_Admin_Reports::get_report()",
        "#3 wp-content\/plugins\/woocommerce\/includes\/admin\/class-wc-admin-reports.php(36): include_once('...')",
        "#4 wp-content\/plugins\/woocommerce\/includes\/admin\/class-wc-admin-menus.php(343): WC_Admin_Reports::output()",
        "#5 wp-includes\/class-wp-hook.php(324): WC_Admin_Menus->reports_page()",
        "#6 wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()",
        "#7 wp-includes\/plugin.php(517): WP_Hook->do_action()",
        "#8 wp-admin\/admin.php(259): do_action()",
        "thrown"
    ]
}
```

Note:
For HPOS the status filtering isn't done correctly. In [this code](https://github.com/woocommerce/woocommerce/blob/release/9.1/plugins/woocommerce/includes/admin/reports/class-wc-report-customer-list.php#L176) we should filter for the `wc_get_is_paid_statuses` directly without mapping them through `wc_get_order_status_name`.

**Comment by rrennick** [comment]
@mikkamp I updated the labels on this to reflect that the issue is with the legacy reports vs WC Analytics. I'll leave the team labels but this issue should have been forwarded to @woocommerce/proton .
