### ISSUE TITLE
Incorrect conversion of foreign currency sales back to default currency

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#38382]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the WCPay native currency switching, the results for South African Rand (ZAR), are significantly off from what they should be in the analytics. 

* Enable ZAR as currency
* Pay for an item in another gateway different from WCPay, e.g. Stripe.
* Check in Analytics

10 USD should be about 180 ZAR. 

This album is 15 EUR on a site, so R290 is fairly on point. The checkout then is 580 ZAR (the equivalent of 30 EUR):
 
![Screenshot 2023-02-20 at 15 07 20](https://user-images.githubusercontent.com/8783673/220117315-77c149f9-4a3d-4650-86f8-b8acbb7ea743.png)

However, after going to Analytics > Orders, the corresponding order is showing 542.42 EUR.

![Screenshot 2023-02-20 at 15 09 53](https://user-images.githubusercontent.com/8783673/220117866-1ab4ad40-fae3-4edc-bdc3-cb6be46688f4.png)

_More context [here](https://github.com/Automattic/woocommerce-payments/issues/5584#issuecomment-1438036317)._

### Expected behavior

The currency conversion in Analytics should correctly reflect the original transaction amount.

### Actual behavior

The currency conversion under Analytics doesn't work when WCPay is installed and activated.

### Steps to reproduce

1. Install and activate WooCommerce Payments and WooCommerce Stripe Gateway.
2. Go to WooCommerce > Settings > Multi-currency and add a currency.
3. Create an order using the newly added currency.
4. Run the `wc_admin_daily` job.
5. Go to Analytics > Revenue.
6. Verify that the `Total sales` value for the order does not accurately reflect the original transaction amount.

### WordPress Environment

- WooCommerce 7.7
- WooCommerce Payments 5.9
- WooCommerce Stripe Gateway 7.4

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by brucealdridge** [comment]
@octaedro Is this complete now? Was there any PR related to this?
