### ISSUE TITLE
Product Block Editor: Editor only blocks not being registered in product block editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38394]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There seems to be an issue where any custom blocks require the [`script` config](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#script) to be set in order for the block to be shown within the product block editor. This should not be necessary. See this [PR and comment](https://github.com/woocommerce/woocommerce/pull/38263#discussion_r1198270896) for extra context.

In addition there was an issue where it failed to register in WP 6.3, which may relate to this bug.
p1684265248942519-slack-C01CMSA1VHS

With the `script` line removed from the `block.json`:
![Screenshot 2023-05-22 at 12 24 46 PM](https://github.com/woocommerce/woocommerce/assets/2240960/3e54567a-bf2d-4bd7-ae36-2516a6146ef2)

**To reproduce**

1. Pull down this PR: https://github.com/woocommerce/woocommerce/pull/38263 and follow the test instructions within.
2. After successfully rendering remove the `script` line from the `block.json` file and re-build the test extension
3. Refresh the **Product > Add New** page and notice how the block is not being rendered anymore.

**Acceptance criteria**

- [ ] Custom blocks should be rendered with the product block editor without the need for the `script` config

**Comment by louwie17** [comment]
In the Slack thread above some suggestions where made in making use of the `is_block_editor` function that the `site-editor` uses for example:
```
$current_screen = get_current_screen();
$current_screen->is_block_editor( true );
```
This may or may not help, although not sure where to exactly trigger this given our react injection.

**Comment by mattsherman** [comment]
I've created a follow up issue for this to update the`@woocommerce/create-product-editor-block` package: https://github.com/woocommerce/woocommerce/issues/38426
