### ISSUE TITLE
Woocommerce sends password was reset emails for some users

### ISSUE THREAD

**Issue by phillipswdc** [woothemes/woocommerce#38424]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For some customers on completed order a password was reset email is sent. After this email is received the user will also get the order email. 

### Expected behavior

No password reset email sent

### Actual behavior

Password email is sent then the order processing email sent.

### Steps to reproduce

this is difficult but on our system we stripped everything out and are only using our database and a new install of WordPress default theme Woocommerce, Woocommerce Stripe and an SMTP mail plugin we have tried a couple.

Placing an order with the affected user accounts will always send the email.

### WordPress Environment

We have resolved the issue not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by phillipswdc** [comment]
This is what we found…

On checkout, while “placing order” WooCommerce is doing also customer update with data you input in form.
This runs wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php line 190 update method which runs ->
wp_update_user ( wp-includes/user.php) for some reason it runs code block for password  or email change

the fix for us was…

  ```
/**
   * Prevents mail send on checkout
   *
   * @param boolean $send
   * @return boolean
   */
function preventMailSendOnCheckout($send): bool
  {
    if (isset($_REQUEST['woocommerce-process-checkout-nonce'])) {
      $send = false;
    }

    return $send;
  }

add_filter('send_password_change_email', 'preventMailSendOnCheckout', 10, 1);
```

**Comment by psealock** [comment]
@phillipswdc Great work figuring out the solution and thanks for letting us know. Since you've found the source of the problem, would you like to open a pull request?

**Comment by vedanshujain** [comment]
Note that we do send an account-created mail if the customer has created an account which is expected. I am not able to reproduce this issue with password reset mail. Can you share an example SMTP plugin you have been using?
