### ISSUE TITLE
[Optimize Product Name] - Improvements to the alternative suggestions

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#38425]
@tommyshellberg suggested a number of improvements we can make on the alternative suggestions generated for the product title:

At the moment the "suggest alternatives" button works exactly the same as the "Get Suggestions" button but perhaps there are some improvements we could make.

- If we don't pass any new data when suggesting alternatives could we save some API calls by just asking GPT for like 12 product titles within the first attempt, cache them in component state, and then rotate through them locally? Then we wouldn't have to make another API call to get a few more product titles. I can foresee users wanting to see quite a few recommendations.

- Should we set a limit for the number of times we try to generate a product title? At the very least, I think it makes sense to not allow someone to generate dozens of recommendations without changing something (the description, base title, categories, etc) as the recommendations will get stale pretty quickly without new/better information.

- It seems like we'll want some kind of caching for the responses to make sure we don't offer the same product titles over and over again. I got a few duplicates in my tests which would be frustrating from a user perspective. 
I'm not sure if there is an easy answer for this issue within this PR or if we should wait until we have a dedicated endpoint for this on WPCOM which can take care of the caching. 
Within this PR, perhaps we could have the "Suggest Alternatives" functionality make a different API call than "Get Suggestions". It could send in its request the previous recommendations as part of the prompt and ask GPT to not recommend those again?

_Originally posted by @tommyshellberg in https://github.com/woocommerce/woocommerce/pull/38392#discussion_r1201976493_

**Comment by tommyshellberg** [comment]
Thanks for making a new issue for this 👍 
Writing some thoughts down while I have them, obviously this is geared towards enhancements.

### Output performance

> If we don't pass any new data when suggesting alternatives could we save some API calls by just asking GPT for like 12 product titles within the first attempt, cache them in component state, and then rotate through them locally? Then we wouldn't have to make another API call to get a few more product titles. I can foresee users wanting to see quite a few recommendations.

It does appear that ChatGPT's output runtime complexity is something close to linear - I tested a few different prompts to get more product titles back (3, 6, 9, 12) and the average response time was somewhere around 15, 30, 45, and 60 seconds. Of course, I only tested a couple of times each so it's nothing to make sweeping changes from.
Given this, we definitely would want to be cognizant of the time it takes to generate a response.
I suppose it comes down to finding a "sweet spot" between the first latency time (generating the first few titles) and the _total_ latency time (average number of titles generated until someone stops trying).

### Input performance

#### Shorten prompt
One other thing I think we should consider is that the complexity of a transformer model is quadratic O(n²), meaning the length of the **prompt** also heavily influences the latency. 
We could probably trim down the existing prompts and get similar results, but it will require some testing.
Another interesting experiment would be to ask ChatGPT itself if it could compress our prompt and see if we get performance gains without sacrificing quality. 🤔 

I asked it to do that for part of our existing prompt and it spit out this(53 tokens):

>You're a WooCommerce SEO pro. Given the product's title, description, tags, and categories, provide six optimized title alternatives. Return only the optimized value in JSON response "content". Give a concise seven-word reason in "reason". Product properties are:

The original prompt, starting with `You are a SEO and marketing expert specializing in e-commerce stores built using WooCommerce.` is 193 tokens.

#### Experiment without JSON response
The other thing we could try out is to get rid of the prompt asking for a JSON response. It seems to me that GPT is very reliable at returning lists of items but isn't very reliable with very structured responses like JSON. I would be curious if we could just ask GPT to return a list like so:
```
Product Title: {title}
Reason: {reason}
Product Title: {title}
Reason: {reason}
Product Title: {title}
Reason: {reason}
```
If it does that perfectly every time, we could just do some string splitting to get the array of product titles and reasons. 🤷 
It may not be a huge improvement if GPT returns JSON structure somewhat reliably, but, the prompt asking for a JSON response is 163 tokens which could be chopped off from the input prompt. We'd have to test to see what kind of effect that has on latency.

**Comment by peterfabian** [comment]
Closing down as the feature is being sunset.
