### ISSUE TITLE
Core Profiler - additional changes for the plugins page

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#38436]
**Issue Description:**

There is an open [PR](https://github.com/woocommerce/woocommerce/pull/38405) for the plugin page already, but it requires additional changes that depend on other in-progress issues. 

Please work on the following changes:

1. Test the installation process further, especially with large plugins like Jetpack. 
2. Refactor [InstallAndActivatePlugins](https://github.com/woocommerce/woocommerce/pull/38405/files#diff-cb652db0708acedc660f9bbad201e2546aaa856290d466b086200f265c5dfbc8) and extract it to a state
3. Use `install-activate-plugins from https://github.com/woocommerce/woocommerce/pull/38434
4. `free-extensions` feed has been updated to add `label` and `learn_more` link in https://github.com/woocommerce/woocommerce/pull/38418. Use both values.
5. Confirm tracks
6. Redirect to the existing Jetpack connection page on WPCOM
7. Add installation_priority and use it in the frontend.

**Comment by rjchow** [comment]
I noticed that jetpack and wcpay together take up almost all the 30s allocated, most of the time - on my local wp-env. The other plugins take another 30-50s in total if I allow them to continue installing synchronously.

I think we might have to set a priority list for the installation if we're going to redirect out for the jetpack login

**Comment by moon0326** [comment]
> I noticed that jetpack and wcpay together take up almost all the 30s allocated, most of the time - on my local wp-env. The other plugins take another 30-50s in total if I allow them to continue installing synchronously.
> 
> I think we might have to set a priority list for the installation if we're going to redirect out for the jetpack login

Sounds good. I'll include the change in this issue.
