### ISSUE TITLE
Updating language in WordPress Settings does not show the Update (circular arrows) button with WC7.8 (and does with WC7.7)

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#38445]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Updating the language in the WordPress Settings page does not show the Update (circular arrows) button with WC7.8 installed (whereas it does with WC7.7). 
e.g. if I change the language from English to Espanol, the button does not display.

However, if I then change the language back to English (or change to any other language) then it displays successfully:
![image](https://github.com/woocommerce/woocommerce/assets/105309450/0502baf8-698e-40c1-89a3-43d5038ce9f0)

### Expected behavior

With WC7.8 installed, Updating the language in the WordPress Settings page should display the Update 'arrows' button to allow navigation to the core update page.

### Actual behavior

Updating the language in the WordPress Settings page does not show the Update (circular arrows) button with WC7.8 installed

### Steps to reproduce

1. Create WP with WC7.8 or newer installed
2. navigate to /wp-admin/
3. Perform any pending updates i.e. Update Akismet (or any other plugins that require update) in order to remove the pending update arrows
4. click on WP Settings->General
5. ![image](https://github.com/woocommerce/woocommerce/assets/105309450/bb72bdee-322f-4b8d-b24b-346c5f6e27f0)
6. Change Site Language to Espanol
7. Click Save Changes button
8. Update button does not display:
9. ![image](https://github.com/woocommerce/woocommerce/assets/105309450/43f1d27b-bc0c-45a7-99bf-7330857bbe38)
10. change the language back to English (or change to any other language) and the button displays:
11. ![image](https://github.com/woocommerce/woocommerce/assets/105309450/73ee0e4e-7d95-4f68-a3c8-ccdbe4cd9059)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://intermediate-beetle.jurassic.ninja
Site address (URL): https://intermediate-beetle.jurassic.ninja
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 4.89MB
Database Data Size: 3.45MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.29
Jetpack: by Automattic – 12.1
WooCommerce: by Automattic – 7.8.0-beta.1-pulls-270
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-05-26 12:01:33 +00:00
Options: ✔
Notes: 64
Onboarding: -

### Action Scheduler ###

Complete: 2
Oldest: 2023-05-25 12:02:48 +0000
Newest: 2023-05-25 12:02:48 +0000

Pending: 1
Oldest: 2023-05-26 12:02:48 +0000
Newest: 2023-05-26 12:02:48 +0000

### Status report information ###

Generated at: 2023-05-25 12:06:50 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@nigeljamesstevenson Do you still see this in the latest version of WC?

**Comment by nigeljamesstevenson** [comment]
Hi @rrennick - I just tested with WC 8.0.3 and WC 8.1.0-a.5 and I still see the same issue.


https://github.com/woocommerce/woocommerce/assets/105309450/2f2eb39b-d174-440a-a447-eb394b3bd0fd

**Comment by rrennick** [comment]
> I just tested with WC 8.0.3 and WC 8.1.0-a.5 and I still see the same issue.

Thanks @nigeljamesstevenson . I updated the issue reproductions steps to reflect that this isn't specific to WC 7.8.0.

For further investigation: I had inconsistent results with trying to reproduce this where I was only able to reproduce it once. Subsequent tests consistently showed the icon whether WC was active or not. It seems this might be a caching issue.

**Comment by nigeljamesstevenson** [comment]
Thanks for the investigation on this @rrennick !

I just realised that an extra step is now required in the steps to reproduce. We need to perform any pending updates in order to remove the pending update arrows (step 2 below) which may be why this was tricky to reproduce. 

The steps should be:

1. Fresh new Jurassic Ninja WP install 
2. Perform any pending updates i.e. Update Akismet (or any other plugins that require update) in order to remove the pending update arrows
4. 0 updates should be showing at this point
5. Switch to Espanyol (or any other language)
6. 0 updates show (although an update for your chosen language should now be available)
7. Switch back to English
8. 1 update is now showing

I have added a video of the updated steps and I have added the extra step above also:

https://github.com/woocommerce/woocommerce/assets/105309450/37c039f0-d150-4ee0-8614-c04a83a11b79

As you mention, WC does not have to be installed/active. 
I repeated this on localhost and JNs in regular and incognito modes.

I confirmed with @veljkho and @alopezari and they see the same.

However, this is clearly not a WC-related issue, this is a WP issue.

**Comment by rrennick** [comment]
@nigeljamesstevenson Thanks for adding the detail. Just for clarity, my note was that when I switched back to English then to another language that hadn't been previously installed, I did get the icon.

> However, this is clearly not a WC-related issue, this is a WP issue.

I'll close this and label it as WP.
