### ISSUE TITLE
[Woo AI] Create a `build` script for the plugin to package it as a ZIP file

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#38446]
We should be able to run `pnpm run build` and get a .ZIP file containing a fully-compatible WordPress.org plugin folder.

- [x] [Create a basic script](https://github.com/woocommerce/woocommerce/blob/add/woo-ai-plugin/plugins/woo-ai/bin/build-zip.sh) to build the ZIP plugin.
- [x] Verify that it's not missing anything required (you should be able to install it on a Jetpack-powered site).
- [x] Remove any extraneous dev files (.scss, *.ts, *.tsx, dev composer dependencies).
- [x] Create a changelog file.
- [x] Create a README file.
- [x] Make sure the main plugin file has plugin headers that satisfy WordPress.org plugin requirements.

Requirements:

>For Github repositories releases must be built and the zip files must be laid out like the dotorg repo generated zip files
Generally speaking this means inside your zipfile for your plugin named “myplugin” all of your repository files should be in a “myplugin” folder.

**Comment by joelclimbsthings** [comment]
@tommyshellberg  Just curious, is this similar to the `build:zip` that exists in the plugin already?

**Comment by tommyshellberg** [comment]
> @tommyshellberg Just curious, is this similar to the `build:zip` that exists in the plugin already?

Yep, we might as well use what's already there, but we'll want to make sure the ZIP file contains a legit WordPress plugin and doesn't have dev files, has proper plugin headers, etc.

**Comment by tommyshellberg** [comment]
Draft PR here: https://github.com/woocommerce/woocommerce/pull/38528
Will need to wait to find out what the Woo AI plugin will actually be called so we can update the Plugin headers.

**Comment by tommyshellberg** [comment]
Created a PR #38528 which is ready for review, assuming we're sticking with Woo AI as the plugin name.
