### ISSUE TITLE
Use Jetpack AI endpoints for generating text

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#38451]
Modify the completion service used in https://github.com/woocommerce/woocommerce/pull/38392 to use the [Jetpack AI endpoint](https://github.com/Automattic/jetpack/blob/3be4a6e0afa8b267897dc18afd4e8163754df333/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-ai.php#L52).

**Comment by tommyshellberg** [comment]
Closed by #38452
