### ISSUE TITLE
[Optimize Product Name] Imrove the prompt to get a faster response from the model

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#38458]
It takes 10 to 15 seconds (and sometimes 20s) to generate three suggestions for the product title. Most of the waiting time is due to the completions API processing the prompt and returning the suggestions. We should think of ways to reduce this waiting time.

**Comment by tommyshellberg** [comment]
One of the things that came up when reviewing #38930:

> One thing I noticed is that the new prompt will send quite a lot of product data that doesn't seem like it would help an LLM write a description or title for a product:

- product ID (an integer)
- published status ('draft', 'published')

https://github.com/woocommerce/woocommerce/pull/38930#issuecomment-1612832813

We'll want to really try to compress the prompt length as much as possible as it will influence the latency.

**Comment by nima-karimi** [comment]
Good catch. Yeah, those two were mistakenly added in https://github.com/woocommerce/woocommerce/pull/38902 and should be removed.

**Comment by nima-karimi** [comment]
Just a quick update, It looks like we don’t include this data in the prompt in the current release, as we have a set of predefined attributes on the PHP side:

https://github.com/woocommerce/woocommerce/blob/8b1d5769180a2c40b3b1ec23d10b98dd5e6029a9/plugins/woo-ai/includes/product-data-suggestion/class-product-data-suggestion-prompt-generator.php#L98-L137

So it seems this issue was introduced in https://github.com/woocommerce/woocommerce/pull/38930 and should be resolved there.

To avoid any confusion, though, we may want to limit the product data that we send in the request, so it might be worth fixing that part in the front end:

https://github.com/woocommerce/woocommerce/blob/8b1d5769180a2c40b3b1ec23d10b98dd5e6029a9/plugins/woo-ai/src/product-name/product-name-suggestions.tsx#L197

**Comment by joelclimbsthings** [comment]
Thanks @nima-karimi , I've addressed this in [that PR](https://github.com/woocommerce/woocommerce/pull/38930) 👍🏻

**Comment by peterfabian** [comment]
Closing down as the feature is being sunset.
