### ISSUE TITLE
[Optimize Product Name] Update product slug based on the selected suggestion (only new products)

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#38483]
When the user selects a product name suggestion on a new product, their product slug remains the same and, even in some cases, will be set to the value they were typing to get the list of suggestions. We need to have a way to update the product URL slug whenever the user selects a suggestion, but this should only apply to new products because, on existing products, we may break the link by unintentionally changing the existing URL.

**Comment by tommyshellberg** [comment]
>but this should only apply to new products because, on existing products, we may break the link by unintentionally changing the existing URL.

@nima-karimi I think WordPress automatically creates a 301 redirect if you change the product slug and the post is already published. I tested this on my Woo Express site and verified it:

![Image](https://github.com/woocommerce/woocommerce/assets/6723003/6913e6fc-f072-40bc-a7f5-ce71503dbb83)

With that in mind, I think it simplifies the work here in that we can safely just always update the slug and let WordPress take care of the 301 redirect.

**Comment by nima-karimi** [comment]
Ah, good call. I thought that only worked on WPCOM, but I could also verify it on my local WP. This should make things much more straightforward.
