### ISSUE TITLE
some of my orders missing from dashboard and from database how is it possible ? 

### ISSUE THREAD

**Issue by KundanSonawane** [woothemes/woocommerce#38497]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

we received order and payment but it is missing from our dashboard and also database. customer received mail for order but we dont get any mail regarding order

### Expected behavior

we want our order to show in dashboard as usual.

### Actual behavior

please refer description

### Steps to reproduce

I dont know

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://elica.in
Site address (URL): https://elica.in
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - There is a newer version of WordPress available (6.2.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Microsoft-IIS/10.0
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.39-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Post Type Counts ###

attachment: 148
cartflows_flow: 1
cartflows_step: 2
custom_css: 6
elementor_library: 3
nav_menu_item: 18
page: 10
post: 3
product: 86
revision: 92
shop_order: 205
shop_order_refund: 2
wp_global_styles: 2
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

WooCommerce Multi-Currency PayUBiz: by PayUBiz – 3.8.1
Starter Templates: by Brainstorm Force – 3.2.0
CartFlows: by CartFlows Inc – 1.11.9
Checkout Plugins - Stripe for WooCommerce: by Checkout Plugins – 1.4.12
Contact Form 7: by Takayuki Miyoshi – 5.7.6
Elementor: by Elementor.com – 3.12.2
Jetpack: by Automattic – 11.9.1
Pop-up Notices for WooCommerce: by WPFactory – 1.4.1
Variation Swatches for WooCommerce: by CartFlows – 1.0.7
WooCommerce: by Automattic – 7.7.0
WP Mail SMTP: by WPForms – 3.7.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Custom Order Status Manager for WooCommerce: by Bright Plugins – 0.12
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #401 - /index.php/shop/
Cart: #97 - /index.php/cart/
Checkout: #98 - /index.php/checkout/
My account: #99 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 4.0.2 (update to version 4.1.5 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-27 12:42:57 +00:00
Options: ✔
Notes: 79
Onboarding: completed

### Action Scheduler ###

Complete: 293
Oldest: 2023-04-26 13:08:31 +0000
Newest: 2023-05-27 05:13:58 +0000

Failed: 7
Oldest: 2023-03-24 12:43:56 +0000
Newest: 2023-05-22 06:54:35 +0000

Pending: 4
Oldest: 2023-05-27 13:37:51 +0000
Newest: 2023-05-30 00:02:57 +0000

### Status report information ###

Generated at: 2023-05-27 05:47:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the report @KundanSonawane.

Is it happening all the time? If so, what are the steps to reproduce? Have you tried deactivating all the plugins besides WooCommerce and seeing if the behaviour persists?

**Comment by rrennick** [comment]
Marking this as a support request due to lack of feedback.
