### ISSUE TITLE
Investigate Weekly Release Versioning Strategy

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#38490]
### Description

We currently maintain an _x_._y_._z_-dev versioning scheme within `trunk`. If we'll be expecting code in `trunk` to be ready for a weekly release cut from the nightly, we'll either need to update the nightly to generate a new versioning scheme, or adopt that scheme directly in `trunk`.

### Acceptance Criteria

* Reach out to Jetpack Crew to understand why they choose to skip even numbers in Jetpack.
* Evaluate whether or not we will follow the same process; or develop our own scheme.
* Publish a proposal for how to version for weekly releases, and create any issues needed to complete said proposal.

**Comment by juliaamosova** [comment]
This has been resolved in pf59Ax-3d-p2.
