### ISSUE TITLE
Product Editor Onboarding: Show feedback bar in footer

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38519]
**Description**

We want to allow users to share feedback and/or turn the editor off easily. We will do this by showing a bar at the bottom.

This bar will show up in two scenarios:
- Once a user completes or closes the spotlight tour - see https://github.com/woocommerce/woocommerce/issues/38516
- Or if a user publishes or updates a product

**NOTE:** We had already implemented a very similar footer in the previous version of the product editor, you should be able to re-use that component, see: https://github.com/woocommerce/woocommerce/blob/28c72e81c48d85affdeef8a98408d8e60a6934eb/packages/js/product-editor/src/components/product-mvp-ces-footer/product-mvp-ces-footer.tsx

**Design**

lj4AUMJnpMtUe7XqyvOONq-fi-1334_117673

**Acceptance criteria**

- [ ] The bar is shown to all users after they publish or save a product in the new product editing UX.
- [ ] The bar should be displayed permanently unless it's closed by the user.
- [ ] If the user selects "share feedback," we should enable the regular CES and hide the bar. 
- [ ] If the user selects "turn it off" it should redirect to the old experience and turn the feature flag off. ~~we should show a new survey before redirecting the user to the old experience: lj4AUMJnpMtUe7XqyvOONq-fi-1334_116373  This survey should be the same as the one displayed when the user selects the "use the classic editor" option at the topbar ( CES changes are part of: https://github.com/woocommerce/woocommerce/issues/38502 )~~ The new survey will modal will be part of a separate issue.
- [ ] If the user selects "turn it off" we should disable the product block editor feature flag.
- [ ] Add necessary tracks as listed below.

**Tracking**

- User clicks share feedback in bar - `product_editor_feedback_bar_share_feedback_click`
- User dismisses feedback bar - `product_editor_feedback_bar_dismiss_click`
- User clicks turn it off - `product_editor_feedback_bar_turnoff_editor_click` ( include product type as property )

**Comment by pmcpinto** [comment]
Tracking looks good. Same suggestion: we should also tweak all the event names to make it clearer that they're focused on the new experience: new_product_...
