### ISSUE TITLE
Product Editor Onboarding: Add "tell me more" button to wc.com page

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38518]
**Description**

Blocked by: https://github.com/woocommerce/woocommerce/issues/38516 and having a wc.com link.

We want to allow users to read more about the new product editor on an external documentation page, we will allow users to link to this on the 4th step of the feature tour by clicking "Tell me more".
This work will be dependant on https://github.com/woocommerce/woocommerce/issues/38516

**Design**

lj4AUMJnpMtUe7XqyvOONq-fi-1335_125284

**Acceptance criteria**

- [ ] "Tell me more" primary button should be displayed in tour on last (4th) step.
- [ ] Clicking "Tell me more" should link to wc.com page: 
https://woocommerce.com/product-form-beta
- [ ] Add tracking (see below for tracks)

**Tracking**

- User clicks tell me more - `product_editor_spotlight_tell_me_more_click`

**Comment by pmcpinto** [comment]
Tracking looks good. Same suggestion: we should also tweak all the event names to make it clearer that they're focused on the new experience: new_product_...

**Comment by pmcpinto** [comment]
> Clicking "Tell me more" should link to wc.com page (TBD)

Description update with the final link.
