### ISSUE TITLE
Product Editor Onboarding: Show spotlight for first time visitors

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38516]
**Description**

We want to show a spotlight for first time visitors of the new product block editor, to highlight some of the important changes.
This is part of a wider initiative to tackle the onboarding/offboarding flows for new users: https://github.com/woocommerce/woocommerce/issues/36161

For the spotlight we can use the `TourKit` component from `@woocommerce/components`, not adding the `referenceElements` property should render it in the bottom left corner without the arrow (as seen in the wireframes).

For the 4 step tour we should make use of the Gutenberg `Guide` component (`@wordpress/components`), see example of usage here: https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/welcome-guide/default.js#L19 and storybook here: https://wordpress.github.io/gutenberg/?path=/story/components-guide--default )

**Note:** The 4 step tour should be easily toggle able from other places within the application as we do have a follow up issue to trigger this from the editor option menu: https://github.com/woocommerce/woocommerce/issues/38522

**Design**

lj4AUMJnpMtUe7XqyvOONq-fi-1335_125302

Tour:
lj4AUMJnpMtUe7XqyvOONq-fi-1335_125248

**Acceptance criteria**

- [x] User should see **Meet a streamlined product form** spotlight when **first** navigating to the new product block editor page.
- [x] Spotlight should not show up anymore after interaction ( either by clicking the `x` top right or `View highlights` )
- [x] Clicking view highlights should show the 4 step tour 
- [x] "Tell me more" on step 4 should say "Close" or "Done" for now, there will be a follow up to link this to a blog post.
- [ ] Add the necessary tracks (see below)

**Tracking**
*add additional properties if needed.
- [ ] Upon view of of spotlight - `block_product_editor_spotlight_view`
- [ ] Upon **Show highlights** - `block_product_editor_spotlight_show_highlights`
- [ ] Upon spotlight dismiss - `block_product_editor_spotlight_dismiss`
- [ ] Upon tour dismiss - `block_product_editor_spotlight_dismiss` ( include `step_name` )
- [ ] Upon tour finish - `block_product_editor_spotlight_completed` ( when user clicks done, or dismiss on this last step )

**Comment by pmcpinto** [comment]
Overall, the tracking looks good to me. Just a couple of details:
- The `product_tour_completed` will be fired when the user clicks in one of the actions available in the last step, right?
- We should keep the events' names consistent. So the two `product_tour...` events should be renamed `product_spotlight...`
- We should also tweak all the event names to make it clearer that they're focused on the new experience: `new_product_...`

**Comment by louwie17** [comment]
> The product_tour_completed will be fired when the user clicks in one of the actions available in the last step, right?

Yes!

> We should also tweak all the event names to make it clearer that they're focused on the new experience: new_product_...

We chatted about this yesterday, instead of using `new_product` we decided with `product_editor`, as using `new` felled a little arbitrary, and doesn't age well.
