### ISSUE TITLE
Product Editor Onboarding: Add `About the editor...` option the more menu in product block editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38522]
**Description**

Blocked by: #38516

We should give users the option to show the 4 step feature tour again as is implemented in #38516. We will do this by adding a **About the from...** button within the more menu (3 dot menu).

**Designs**

lj4AUMJnpMtUe7XqyvOONq-fi-1334_117673

**Acceptance criteria**

- [ ] More menu in product editor should include a **About the editor...** option
- [ ] If user clicks **About the editor...** it should open and re-trigger the 4 step feature tour as was implemented in #38516
- [ ] Add tracking (see below)

**Tracking**

- User clicks **About the editor...** - `product_editor_more_menu_about_editor_click`

**Comment by pmcpinto** [comment]
Tracking looks good. Same suggestion: we should also tweak all the event names to make it clearer that they're focused on the new experience: new_product_...
