### ISSUE TITLE
Product Editor Onboarding: Add email address field to product editor CES modal

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38521]
**Description**

We want to provide an additional option in the CES feedback modal for the product editor for users to enter their email address as well. This is totally optional.
~~In WooExpress, the email field should be replaced by a checkbox that says `I want to participate in further discussion and future user research`. If not checked, the user's email address isn't shared with the rest of the feedback. ( I am not sure if there is an easy way to check if we are in WooExpress, we may want to double check when implementing ).~~ WooExpress support will be done in another issue.

**Design**

lj4AUMJnpMtUe7XqyvOONq-fi-1334_117723

**Acceptance criteria**

- [ ] `Your Email Address` field should be present with the product form CES modal as the last field.
- [ ] Email address field should be validated if user has entered a value.
- [ ] If user added email we should add this to the `ces_feedback` event as one of the properties: `email`

**Comment by pmcpinto** [comment]
@louwie17 can you confirm if we still need this issue?

**Comment by louwie17** [comment]
@pmcpinto no, this appears to be implemented already. Done as part of some of this work: https://github.com/woocommerce/woocommerce/pull/38643
