### ISSUE TITLE
cant select country in setup wizard

### ISSUE THREAD

**Issue by vivekzade1137** [woothemes/woocommerce#38550]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i cant select country or region option in setup wizard of woocommerese

### Expected behavior

cant select country 

### Actual behavior

when i start to setup wizard

### Steps to reproduce

country option

### WordPress Environment

its okay 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by MaveCritDev** [comment]
I experienced the same issue. Is your current permalink setting set to "simple"? 
I changed it to "post name" which solved the problem for me.

**Comment by psealock** [comment]
@vivekzade1137 Could you provide steps to reproduce? What steps to take and specifically which country?

**Comment by rrennick** [comment]
Closing due to lack of feedback.
