### ISSUE TITLE
Standard CSV Product Import Tool has lost it's column mapping options 

### ISSUE THREAD

**Issue by Knickerless610** [woothemes/woocommerce#38557]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the left side of the column mapping tool, there is no drop down menus to choose from for standard woocommerce product information to sync to CSV file. This has only happened recently. 

### Expected behavior

I want to upload CSV data into woocommerce to update stock quanitities etc.

### Actual behavior

there is no drop down menus to choose from for standard woocommerce product information to sync to CSV file

### Steps to reproduce

1. Go to Tools menu 
2. Click on Import product tab 
3. insert a CSV file 
4. Click through to next page 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://nickspetneeds.com
Site address (URL): https://nickspetneeds.com
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 665.61MB
Database Data Size: 535.16MB
Database Index Size: 130.45MB
wp_woocommerce_sessions: Data: 3.52MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.30MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.39MB + Index: 0.38MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 33.56MB + Index: 45.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 31.56MB + Index: 26.06MB + Engine InnoDB
wp_amazon_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_btg: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_amazon_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_amazon_feeds: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_amazon_feed_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_feed_tpl_data: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_amazon_feed_tpl_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_amazon_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_listings: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_amazon_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_amazon_markets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_orders: Data: 5.52MB + Index: 0.06MB + Engine InnoDB
wp_amazon_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_reports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_amazon_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_amazon_stock_log: Data: 77.61MB + Index: 0.00MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_ebay_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_auctions: Data: 7.52MB + Index: 0.61MB + Engine InnoDB
wp_ebay_categories: Data: 2.52MB + Index: 3.23MB + Engine InnoDB
wp_ebay_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_log: Data: 132.55MB + Index: 0.50MB + Engine InnoDB
wp_ebay_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_orders: Data: 81.52MB + Index: 0.27MB + Engine InnoDB
wp_ebay_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_shipping: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ebay_sites: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_ebay_stocks_log: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_ebay_store_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ebay_transactions: Data: 84.52MB + Index: 0.48MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 31.56MB + Index: 32.13MB + Engine InnoDB
wp_posts: Data: 6.52MB + Index: 2.42MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.30MB + Index: 0.42MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_term_taxonomy: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 7.52MB + Index: 6.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.30MB + Index: 0.33MB + Engine InnoDB
wp_wc_order_stats: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wpfb_post_templates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfb_reviews: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wpfb_total_averages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 1.20MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.25MB + Index: 0.39MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.25MB + Index: 0.33MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.39MB + Index: 0.31MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3040
blocks: 8
custom_css: 1
custom_order_status: 2
featured_item: 8
nav_menu_item: 213
oembed_cache: 1
page: 55
post: 3
product: 3480
product_variation: 419
shop_coupon: 88
shop_order: 860
shop_order_refund: 27
ux_template: 11
wafs: 2
wp_global_styles: 1
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Afterpay Gateway for WooCommerce: by Afterpay – 3.5.3
Australia Post WooCommerce Extension: by WPRuby – 1.10.0
Contact Form 7: by Takayuki Miyoshi – 5.7.6
Custom Order Status for WooCommerce: by Tyche Softwares – 2.2.1
Facebook for WooCommerce: by Facebook – 3.0.23
Flexible Shipping PRO: by Octolize – 2.15.5
Flexible Shipping: by Octolize – 4.21.2
Google Listings and Ads: by WooCommerce – 2.4.5
Max Mega Menu: by megamenu.com – 3.2.2
Nextend Social Login: by Nextendweb – 3.1.8
Perfect Brands WooCommerce: by QuadLayers – 3.0.9
Redirection: by John Godley – 5.3.10
SiteGround Optimizer: by SiteGround – 7.3.1
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.5
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.1
WooCommerce PayPal Payments: by WooCommerce – 2.0.4 (update to version 2.0.5 is available)
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.4
WooCommerce: by Automattic – 7.7.0 (update to version 7.7.2 is available)
WooSidebars: by WooCommerce – 1.4.6
Yoast SEO: by Team Yoast – 20.7
WP Google Review Slider: by LJ Apps – 12.4
WP-Lister Lite for eBay: by WP Lab – 3.4.2
YITH WooCommerce Wishlist: by YITH – 3.21.0

### Inactive Plugins (5) ###

Product Import Export for WooCommerce: by WebToffee – 2.3.0
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Square: by WooCommerce – 3.8.1 (update to version 3.8.2 is available)
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6
WP Rollback: by Impress.org – 1.7.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #61 - /shop/
Cart: #60 - /cart/
Checkout: #59 - /checkout/
My account: #58 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome
Version: 3.15.7
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php version 3.5.0 is out of date. The core version is 7.0.1
flatsome/woocommerce/cart/cart-shipping.php version 3.6.0 is out of date. The core version is 7.3.0
flatsome/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.4.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.4.0
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php version 4.1.0 is out of date. The core version is 7.0.1
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-01 19:34:41 +10:00
Options: ✔
Notes: 161
Onboarding: completed

### Action Scheduler ###

Complete: 122,405
Oldest: 2023-05-01 16:15:16 +1000
Newest: 2023-06-01 15:25:20 +1000

Pending: 3,833
Oldest: 2023-06-01 09:04:04 +1000
Newest: 2023-06-01 15:20:02 +1000

In-progress: 1
Oldest: –
Newest: –

Failed: 12,172
Oldest: 2020-04-02 18:13:17 +1000
Newest: 2023-06-01 10:32:37 +1000

### Status report information ###

Generated at: 2023-06-01 15:27:18 +10:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Knickerless610 Thanks for reporting the issue. Are you still experiencing it? If so, could you create a screen record for us?
