### ISSUE TITLE
Remove Legacy Promo Code Menu

### ISSUE THREAD

**Issue by KalyanaShop** [woothemes/woocommerce#38562]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Good morning,

The banner "Promo code management has moved location!" doesn't go away despite I click the "Remove Legacy Promo Code Menu" button.

The banner goes away... then comes back!

Could you do something?

A big thank-you
Thomas

### Expected behavior

normally the banner should definitely disappear after I clicked on the button.

### Actual behavior

The banner goes away... then comes back!

### Steps to reproduce

as soon as I am in the wordpress administration, the banner appears at the top of the page.
![image](https://github.com/woocommerce/woocommerce/assets/135236400/77fa0f5c-841f-40e7-a903-50e2226c7f3c)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kalyanashop.fr
Site address (URL): https://kalyanashop.fr
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.18
PHP Post Max Size: 128 Mo
PHP Time Limit: 600
PHP Max Input Vars: 200000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.5.20-MariaDB
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.2
WC Database Prefix: wp_
Taille totale de la base de données: 6.94MB
Taille de la base de données: 6.17MB
Taille de l’index: 0.77MB
wp_woocommerce_sessions: Données : 0.40MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_api_keys: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_order_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_order_itemmeta: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_tax_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
noc_autologin: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_actions: Données : 0.13MB + Index : 0.05MB + Moteur MyISAM
wp_actionscheduler_claims: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_groups: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_actionscheduler_logs: Données : 0.09MB + Index : 0.06MB + Moteur MyISAM
wp_burst_goals: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_burst_goal_statistics: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_burst_sessions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_burst_statistics: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
wp_commentmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_comments: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_e_events: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_links: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_litespeed_img_optming: Données : 0.02MB + Index : 0.03MB + Moteur MyISAM
wp_options: Données : 3.03MB + Index : 0.09MB + Moteur MyISAM
wp_postmeta: Données : 1.09MB + Index : 0.23MB + Moteur MyISAM
wp_posts: Données : 1.08MB + Index : 0.04MB + Moteur MyISAM
wp_revslider_css: Données : 0.09MB + Index : 0.01MB + Moteur MyISAM
wp_revslider_layer_animations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_navigations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_sliders: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_slides: Données : 0.02MB + Index : 0.00MB + Moteur MyISAM
wp_revslider_static_slides: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur MyISAM
wp_terms: Données : 0.01MB + Index : 0.02MB + Moteur MyISAM
wp_term_relationships: Données : 0.02MB + Index : 0.04MB + Moteur MyISAM
wp_term_taxonomy: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_tm_taskmeta: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_tm_tasks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_usermeta: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_users: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wcpdf_invoice_number: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_admin_notes: Données : 0.03MB + Index : 0.00MB + Moteur MyISAM
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_wc_category_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_customer_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_order_coupon_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_order_product_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_stats: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_tax_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_product_attributes_lookup: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_wc_product_download_directories: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_product_meta_lookup: Données : 0.01MB + Index : 0.02MB + Moteur MyISAM
wp_wc_rate_limits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_reserved_stock: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpmailsmtp_debug_events: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpmailsmtp_tasks_meta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wpstg_queue: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 87
block: 7
elementor_library: 3
nav_menu_item: 37
page: 53
pls_size_chart: 4
portfolio: 9
post: 15
product: 56
shop_order: 9
shop_order_refund: 1
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Free Shipping Label: par Devnet – 2.6.9
Burst Statistics - Statistiques respectueuses de la confidentialité pour WordPress: par Really Simple Plugins – 1.4.0
Contact Form 7: par Takayuki Miyoshi – 5.7.7
Duplicate Page: par mndpsingh287 – 4.5.2
Elementor: par Elementor.com – 3.13.4
Fluid Checkout pour WooCommerce - Lite: par Fluid Checkout – 2.5.1
Force Regenerate Thumbnails: par Exactly WWW – 2.1.2
Loco Translate: par Tim Whitlock – 2.6.4
PressMart Core: par PressLayouts – 1.5
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.23.4

Thank You Page Customizer for WooCommerce: par VillaTheme – 1.0.14
WooCommerce Stripe Gateway: par WooCommerce – 7.4.1
WooCommerce PayPal Payments: par WooCommerce – 2.0.5
PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.5.4
WooCommerce: par Automattic – 7.7.2
WP Mail SMTP: par WP Mail SMTP – 3.8.0
WP-Optimize - Nettoyer, compresser, mettre en cache.: par David Anderson
Ruhani Rabin
équipe Updraft – 3.2.15

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

burst_rest_api_optimizer.php: par  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #18 - /boutique/
Panier: #1089 - /panier/
Commander: #1090 - /paiement/
Mon compte: #1091 - /account/
Conditions générales de vente et d’utilisation: #1237 - /conditions-generales-de-vente/

### Theme ###

Name: PressMart Child
Version: 1.0
Author URL: https://www.presslayouts.com/
Child Theme: ✔
Parent Theme Name: PressMart
Parent Theme Version: 1.2.0
Parent Theme Author URL: https://presslayouts.com
WooCommerce Support: ✔

### Templates ###

Overrides: pressmart/woocommerce/cart/cross-sells.php
pressmart/woocommerce/cart/mini-cart.php
pressmart/woocommerce/checkout/form-checkout.php
pressmart/woocommerce/checkout/review-order.php
pressmart/woocommerce/content-product.php
pressmart/woocommerce/content-single-product.php
pressmart/woocommerce/content-widget-product.php
pressmart/woocommerce/loop/loop-end.php
pressmart/woocommerce/loop/loop-start.php
pressmart/woocommerce/loop/pagination.php
pressmart/woocommerce/loop/result-count.php
pressmart/woocommerce/myaccount/form-login.php
pressmart/woocommerce/single-product/add-to-cart/variable.php
pressmart/woocommerce/single-product/product-image.php
pressmart/woocommerce/single-product/product-thumbnails.php
pressmart/woocommerce/single-product/related.php
pressmart/woocommerce/single-product/short-description.php
pressmart/woocommerce/single-product/tabs/tabs.php
pressmart/woocommerce/single-product/up-sells.php
pressmart/woocommerce/single-product-reviews.php
pressmart/woocommerce/content-product_cat.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: FR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-01 18:18:11 +02:00
Options: ✔
Notes: 84
Onboarding: completed

### Action Scheduler ###

Terminé: 478
Oldest: 2023-05-01 17:16:33 +0200
Newest: 2023-05-31 20:40:34 +0200

Échoué: 21
Oldest: 2023-02-27 22:56:17 +0100
Newest: 2023-06-01 09:00:43 +0200

En attente: 2
Oldest: 2023-06-01 20:40:34 +0200
Newest: 2023-06-06 14:38:40 +0200

### Status report information ###

Generated at: 2023-06-01 14:58:48 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by msjoker** [comment]
"While we wait for the correction, you can fix it through phpMyAdmin. Go to the 'wc_admin_notes' table and locate the field named 'wc-admin-coupon-page-moved'. Finally, change the 'status' field from 'unactioned' to 'actioned'."

**Comment by KalyanaShop** [comment]
Ok. Thanks !

**Comment by rrennick** [comment]
This should have been addressed in https://github.com/woocommerce/woocommerce/pull/39913. Please let us know if that is not the case.
