### ISSUE TITLE
Product Editor Onboarding: Create new CES modal

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38576]
**Description**

When a user turns off the new product editor we want to show a CES modal to get the users feedback. This CES modal is a little different from the one we are currently using and includes a list of check boxes instead of ratings (see design ).

**Implementation notes**

**We already have [`ProductMVPFeedbackModal`](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/product-editor/src/components/product-mvp-feedback-modal/product-mvp-feedback-modal.tsx), which appears to be basically what we want, with a few style tweaks.**

We should create this version, but as part of this it might be worth creating some re-usable components within the CES modal incase we have to create an alternate version in the future as well. Maybe just adding support in the config for the new question type would be enough?

**Design**

![Image](https://user-images.githubusercontent.com/2240960/242844900-499e3bae-de0f-461c-9af3-0db47288e8a4.png)

lj4AUMJnpMtUe7XqyvOONq-fi-1338_138709

**Acceptance criteria**

- [ ] Add support for new CES modal with a checkbox field as shown in the design
- [ ] Show new CES modal when user clicks **use classic editor** or **turn it off** within the old product editor. We could just expose a query param?
- [ ] **What made you turn off the new product form?** should be required
- [ ] New CES modal should act the same as the current one and trigger a `ces_feedback` track when user clicks `Send` 
- [ ] `ces_feedback` track should include **What made you turn off the new product form?** values as a property (creating unique keys for this is fine)

**Comment by louwie17** [comment]
> ces_feedback track should include What made you turn off the new product form? values as a property (creating unique keys for this is fine)

@pmcpinto we can pass this in as an array to tracks right?

**Comment by mattsherman** [comment]
Important note...

**We already have [`ProductMVPFeedbackModal`](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/product-editor/src/components/product-mvp-feedback-modal/product-mvp-feedback-modal.tsx), which appears to be basically what we want, with a few style tweaks.**

**Comment by pmcpinto** [comment]
> @pmcpinto we can pass this in as an array to tracks right?

Hey @louwie17 just to clarify how it will work: if the user selects "missing features" and "missing plugins" the prop value will be: missing-features, missing-plugins. Correct?

**Comment by louwie17** [comment]
> Hey @louwie17 just to clarify how it will work: if the user selects "missing features" and "missing plugins" the prop value will be: missing-features, missing-plugins. Correct?

Your partially correct, although instead of these being individual boolean prop values, it would be an array/list: `checked: [ 'missing-features', 'missing-plugins' ]`.
Would that still be queryable or usable within the track funnels?

**Comment by pmcpinto** [comment]
Yes. I think that will work well.

**Comment by louwie17** [comment]
> We already have [ProductMVPFeedbackModal](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/product-editor/src/components/product-mvp-feedback-modal/product-mvp-feedback-modal.tsx), which appears to be basically what we want, with a few style tweaks.

@mattsherman could we update the ces feedback track name though to be more generic instead of `product_mvp_feedback`. See your Slack thread for more context: p1685707857873529-slack-C01CMSA1VHS
