### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_gallery_image_ids()

### ISSUE THREAD

**Issue by Dbinformatique69** [woothemes/woocommerce#38588]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Il logs file i have this bug :

Fatal error: Uncaught Error: Call to a member function get_gallery_image_ids() on bool in /home/bricolinbh/www/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-images.php:37

Best regards

### Expected behavior

See and morify image Gallery in admin

### Actual behavior

Error message, 

### Steps to reproduce

In admin product page->image gallery

### WordPress Environment

My thème is DIDI

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Thanks for the report @Guinness8544. Could you confirm the problem still exists when all other plugins are disabled? How about with just the storefront theme?

Thanks

**Comment by rrennick** [comment]
Closing due to lack of feedback.
