### ISSUE TITLE
[GlobalStep] Analytics > Orders page does not filter by Attribute

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#38582]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Creating this issue on behalf of GlobalStep. For reference: p1685626889923499-slack-C011ENB20Q1

In the Analytics > Orders page, when you attempt to filter by attribute, the filter disappears, and the orders list isn't being filtered.

### Expected behavior

1. The order list is filtered correctly.
2. The filter "Color=Blue" should be saved in the Filter list section.

### Actual behavior

1. The order list was not filtered correctly.
2. The filter "Color=Blue" was not  saved in the Filter list section.

### Steps to reproduce

1. Install WC 7.8 beta 2.
1. Create a variable product that has 1 custom product attribute with 2 values. In my test, I set up the product with the following values:
    - Product name: Hoodie
    - Product data: Variable product
    - Custom product attribute name: Color
    - Attribute values: Blue | Red
    - Set the price of both Blue and Red variations to $10
1. Go to WooCommerce > Orders.
1. Create a new order with "Hoodie - Blue" as the product. Make sure that the "Date created" field is set to today's date. Set its status to "Completed".
1. Create another order with "Hoodie - Red" as the product. Again, make sure that the "Date created" value is today's date. Set its status to "Completed".
1. Go to Analytics > Orders.
1. In the "Date range" menu, select "Today" and click "Update".
1. In the "Show" menu, select "Advanced filters".
1. Click "Add a Filter", then "Attribute".
1. In the "Attribute name" field, type "Color". An auto-suggest list will show up containing "Color". Click it.
1. Click on the "Attribute value" field, and select "Blue" from the auto-suggest list.
1. Your screen should now look like this:
   <img width="814" alt="VNEnwxYdOS" src="https://github.com/woocommerce/woocommerce/assets/4509348/51f44766-2e1f-406b-a702-c7c701482bdf">
1. Click on the blue "Filter" button.
1. Notice that the filter you added is gone.
1. Also, notice that the "Orders" panel still lists both the Blue and Red variations.
   <img width="814" alt="4KZjwsH4fi" src="https://github.com/woocommerce/woocommerce/assets/4509348/4b2cdad8-e52c-4a9a-9335-0de6a99ad185">
1. Open a separate browser tab, and downgrade WooCommerce to 7.7.2 there.
2. Go back to the first browser tab (the one with Analytics > Orders opened) and reload the page.
3. Notice that the bug doesn't happen in 7.7.2. The filter was shown as successfully added, and the order list was successfully filtered (only shows the Blue order).
   <img width="814" alt="5pH38j52fT" src="https://github.com/woocommerce/woocommerce/assets/4509348/84a8f344-7a6e-4585-8c6c-61bdb9cc07e3">

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.19
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 2.43MB
Database Data Size: 0.99MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 1
product_variation: 2
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 7.8.0-beta.2-pulls-270
WP Reset: by WebFactory Ltd – 1.97

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 5.1
Code Snippets: by Code Snippets Pro – 3.4.0
Gutenberg: by Gutenberg Team – 15.5.1
Jetpack: by Automattic – 12.2-beta
MailPoet: by MailPoet – 4.11.1
Pressable OnePress Login: by Pressable – 1.3.1
Query Monitor: by John Blackbourn – 3.12.3
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce Payments: by Automattic – 5.9.0
WooCommerce Smooth Generator: by Automattic – 1.1.0
WP Mail Logging: by WP Mail Logging Team – 1.11.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 3
Onboarding: -

### Action Scheduler ###

Complete: 47
Oldest: 2023-06-02 11:33:01 +0000
Newest: 2023-06-02 12:50:43 +0000

Pending: 2
Oldest: 2023-06-02 12:51:43 +0000
Newest: 2023-06-03 11:33:01 +0000

Failed: 1
Oldest: 2023-06-02 11:34:10 +0000
Newest: 2023-06-02 11:34:10 +0000

Canceled: 2
Oldest: 2023-06-02 11:38:35 +0000
Newest: 2023-06-02 12:28:49 +0000

### Status report information ###

Generated at: 2023-06-02 12:51:15 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by tomalec** [comment]
It seems the issue was introduced in https://github.com/woocommerce/woocommerce/pull/35128#issuecomment-1297769716 as 
the native `URLSearchParams` uses different convention for arrays than `qs` library.

I cannot find a quick and easy fix.

I was thinking of changing the way [we handle 'allowMultiple' in advanced filters](https://github.com/woocommerce/woocommerce/blob/release/7.8/packages/js/navigation/src/filters.js#L67-L85) to something like:
```js
if ( filter.allowMultiple ) {
	// If rules were found in the query string, and this filter supports
	// multiple instances, add all matches to the active filters array.
	matches.forEach( ( match ) => {
		const value =
			query.getAll( getUrlKey( configKey, match.value ) ); // <----
			// …
		} );
	} );
} else {
	// If the filter is a single instance, just process the first rule match.
	const value =
		query.get( getUrlKey( configKey, matches[ 0 ].value ) ); // <----
	// …
}
```

but that would require passing URLSearchParams all the way as a prop, which is quite a refactoring (regardless if we pass it as a `previous `query` or a new `queryParams`).

So I think the safest approach, especially in the "release candidate" period, is to revert https://github.com/woocommerce/woocommerce/pull/35128. Then try a more gradual approach to `qs` switch in the next release
