### ISSUE TITLE
La gestion des codes promo a changé d’emplacement ! Vous gérez désormais les codes promo dans Marketing > Codes promo. Cliquez sur le bouton ci-dessous pour supprimer l’élément de menu hérité WooCommerce > Codes promo. Retirer le menu de code promo hérité

### ISSUE THREAD

**Issue by dansafran** [woothemes/woocommerce#38602]
![Capture d’écran 2023-06-04 164209](https://github.com/woocommerce/woocommerce/assets/14239418/b1eeb9f4-5bfb-4ec0-940c-0c677b03a939)

https://github.com/woocommerce/woocommerce/assets/14239418/56c2718e-e28b-4b19-b591-2adf2bbaafeb

**Comment by rrennick** [comment]
This has also been reported in https://github.com/woocommerce/woocommerce/issues/34731. Closing as a duplicate.
