### ISSUE TITLE
Visual changes for Intro, guided setup, and skipped guided setup pages

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#38626]
Veronica noticed visual differences on the intro, guided setup, and skipped-guided setup pages of the core profiler.

You can see the list of change requests on Y5pUYSJPsGEud1vknUZhi8-fi-1698-36100

Please update the changes on the pages.

**Comment by rjchow** [comment]
Let's add this visual issue noticed by @ilyasfoo too

![image](https://github.com/woocommerce/woocommerce/assets/27843274/e1e8e351-9411-4c4a-b28c-2046a40634fc)

https://github.com/woocommerce/woocommerce/pull/38606#pullrequestreview-1465062995

**Comment by ilyasfoo** [comment]
Sorry hugely off-topic, but @moon0326 your Figma link isn't highlighted to my browser with Tampermonkey's script. I wonder if we're using the same version? I'm using 7.7.1. Do you see my link highlighted? 

Yours: Y5pUYSJPsGEud1vknUZhi8-fi-1698-36100
Mine: Y5pUYSJPsGEud1vknUZhi8-fi-739_54680

**Comment by ilyasfoo** [comment]
It seems there's a difference in padding between selected/not selected. If you notice there is a slight movement in the labels and button positioning:

<img src="https://github.com/woocommerce/woocommerce/assets/3747241/294b1882-f76b-4ad2-af78-0fbbe7c41df6" width="450">

**Comment by moon0326** [comment]
@ilyasfoo  Yup! I see your link highlighted, but I don't see mine as a link though. ~I'm on 7.7.0. Where do you get the latest script?~

Found it https://github.com/Automattic/tampermonkey-highlighter

**Comment by moon0326** [comment]
> It seems there's a difference in padding between selected/not selected. If you notice there is a slight movement in the labels and button positioning:
> 
> <img alt="" width="450" src="https://user-images.githubusercontent.com/3747241/245158461-294b1882-f76b-4ad2-af78-0fbbe7c41df6.gif">

I think it's because of the border size difference. The normal state has 1px border, whereas selected state has 2px border size.
