### ISSUE TITLE
Simple product rollout - phase 2

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#38624]
**Description:** We will repeat the experiment released in July (WC 7.9) to understand if the improvements included with 8.1 have a positive impact on the new experience. This experiment should be launched alongside WC 8.1

**Acceptance criteria:**

- [x] The new experience is enabled for 50% of new users who select the "Physical product" option in the "Add products" task. Any new user will see the onboarding flow implemented in #36161. Ideally, this should be implemented using ExPlat to ensure we have more control over when phase 2 should be enabled or disabled (in case something goes wrong).
- [x] Update the current `woocommerce_product_creation_experience_202306_v2` experiment name, you can probably use `v3`
- [x] Create a new Abacus experiment setting 50% of users to `treatment`
- [x] Create a new P2 within the experimentation platform
- [x] Update the WooCommerce.com segment

**Comment by pmcpinto** [comment]
The AC will be reviewed in the upcoming days.

**Comment by pmcpinto** [comment]
AC updated

**Comment by louwie17** [comment]
Closing this, as this finished!
