### ISSUE TITLE
Update Jetpack AI endpoints to accept and pass a $feature string

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#38625]
We will be able to track Woo AI feature usage if we can pass in `woo_ai_plugin` as the `$feature` when the `OpenAI` library is instantiated. Since we are using Jetpack AI endpoints, these endpoints would have to be updated to accommodate this `$feature` argument.

Here:
https://github.com/Automattic/jetpack/blob/b63ab9d3b950291e51e2a026c70c623becda44de/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-ai.php#L127

and here:
https://github.com/Automattic/jetpack/blob/b63ab9d3b950291e51e2a026c70c623becda44de/projects/plugins/jetpack/_inc/lib/class-jetpack-ai-helper.php#L135

**Comment by tommyshellberg** [comment]
Once those endpoints have been updated and shipped as part of Jetpack, we can update the code here to pass the `$feature` as `woo_ai_plugin`:
https://github.com/woocommerce/woocommerce/blob/add/woo-ai-plugin/plugins/woo-ai/includes/product-data-suggestion/class-product-data-suggestion-service.php#L58

**Comment by joelclimbsthings** [comment]
Note that the above part, passing the feature on our side, is done. Just need the Jetpack changes to go through for this to take effect.
