### ISSUE TITLE
Fix instrumentation gaps for phase 1

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#38637]
**Description:** some instrumentation gaps should be fixed in time of being included in WC 7.9, as they're critical to develop a better understanding of how users interact with the new experience.

**Acceptance criteria:**

- [ ] We’re not firing `wcadmin_product_add_publish` when the product is created, we’re firing `wcadmin_product_update`, which can be misleading. We should fire `wcadmin_product_add_publish` with a new prop called `new_product_page`. We should also record all the props already included in the event: `product_image`, `product_type`, `sale_price`, `short_description`, `product_gallery`, etc.
- [ ] `wcadmin_product_update` is fired when the product is updated, but several props aren’t recorded when the product update happens in the new experience: `product_image`, `sale_price`, `categories`, `weight`, etc. This should be fixed.
- [ ] We’re not tracking the tab clicks, which is useful to understand if users explore all the tabs. Let’s leverage the existing `wcadmin_product_tab_click` and add a new prop called `new_product_page`. The tab name should be recorded in the product_tab prop.
- [ ] The preview button doesn’t fire any event. We should leverage the `wcadmin_product_preview_changes` event and add a new prop called `new_product_page`. It should be an `enum` to handle different versions.
- [ ] We should also add tracking to understand if the user interacts with the main buttons within the form:
`wcadmin_product_add_description_button`
`wcadmin_product_add_attribute_button`
`wcadmin_product_add_image_button`
- [ ] And we should also understand how many users interact with the dropdown (I’m not sure if using dropdown is the best option for the event name):
`wcadmin_product_dropdown_click`
`wcadmin_product_dropdown_option`
`selected_option`: `share feedback` | `classic editor`

**Comment by pmcpinto** [comment]
@octaedro as mentioned in the description, we need to address these instrumentation gaps before the 7.9 code freeze. Let me know if you have any questions.

**Comment by joshuatf** [comment]
@pmcpinto Since this new experience has not been released yet, can we use `source: 'product-blocks-editor-v1` or something similar instead of `new_product_page: true`?

This gives us a little more flexibility if we change or update in the future and reduces the number of props we need to send as well going forward.

**Comment by pmcpinto** [comment]
I've suggested using `new_product_page` because we already have that prop in the `wcadmin_product_update` event. But I'm ok with changing it, as long as it's consistent across all the product-related events.

Let me know which property will be used. Thanks
