### ISSUE TITLE
Prefill the form with some data when creating a "Physical product"

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#38636]
When the user selects "Physical product" in the "Add products" task, we prefill the form with some data (price, image, description, summary, category).

![Screenshot 2023-06-07 at 11 51 27](https://github.com/woocommerce/woocommerce/assets/1314156/0b624b82-d022-4d0a-91ce-7dc9f9909ecb)

We should do the same in the new experience to ensure users start on equal footing.

**Acceptance criteria**

- [ ] The product status will be `draft`.
- [ ] The fields to fill are:
  - [ ] Product description
  - [ ] Regular price
  - [ ] Product image
  - [ ] Product category
- [ ] The data to fill the fields will come from [here](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/woocommerce/src/Admin/API/Templates/physical_product.csv). 

//cc @pmcpinto

**Comment by pmcpinto** [comment]
@octaedro was this implemented? Ideally, we should release it with the 1st split test

**Comment by octaedro** [comment]
Hi @pmcpinto,

> @octaedro was this implemented? Ideally, we should release it with the 1st split test

Not yet. Based on the estimation, it seems like this change will require some significant effort, approximately a week. Should we consider a code freeze exception to include this addition?

//cc @louwie17

**Comment by pmcpinto** [comment]
@octaedro thanks for the update

> Based on the estimation, it seems like this change will require some significant effort, approximately a week.

Why does it take so long to implement this change?

> Should we consider a code freeze exception to include this addition?

Ideally, we should have this included in 7.9, as it's the best way to have comparable data with the current experience.

**Comment by pmcpinto** [comment]
@octaedro @louwie17  just a friendly reminder to give it a look to my comment

**Comment by mattsherman** [comment]
We need to modify the `useCreateProductByType` hook currently implemented in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/task-lists/fills/products/use-create-product-by-type.ts so that `createProductFromTemplate()` is called when the new product editor is enabled.

I estimate this as a 1... it looks pretty simple. Though, the sample data was actually recently removed from the default templates, so I don't know if we want to prioritize this change right now (started a conversation in Slack p1688431103317129-slack-C01CMSA1VHS).

**Comment by pmcpinto** [comment]
> Though, the sample data was actually recently removed from the default templates, so I don't know if we want to prioritize this change right now (started a conversation in Slack p1688431103317129-slack-C01CMSA1VHS).

We can close the issue, considering that the sample date was removed from the "start with a template" flow. Thanks
