### ISSUE TITLE
Fatal error on php8 at read_children function

### ISSUE THREAD

**Issue by ninoort** [woothemes/woocommerce#38642]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi guys!

After speaking with customer service, they encourage me to report this bug here :)

I am getting this error on product category pages:

Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/xxxxx/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php:150

I have been checking the code and it looks that php8 is throwing an error because "$children" variable is not initialized in the line 150:

$children['all'] = get_posts( apply_filters( 'woocommerce_variable_children_args', $all_args, $product, false ) );

I have added this line just before:

$children = array();

and it looks to solve the problem, but I don't want to be overriden on next updates :)

### Expected behavior

Not getting a fatal error :)

### Actual behavior

I am getting this error on product category pages:

Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/xxxxx/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php:150

### Steps to reproduce

1.- Install php 8.2
2.- Use wordpress/woocommerce 
3.- Try to get into a product category with variable products 
(I can't isolate in what cases exactly, because I was getting the error just in some of the product category pages)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://pinanson.eu
Site address (URL): https://pinanson.eu
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.6
PHP Post Max Size: 24 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.3.14-MariaDB-1:10.3.14+maria~bionic
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.2
WC Database Prefix: wp3_
Tamaño total de la base de datos: 578.11MB
Tamaño de los datos de la base de datos: 461.36MB
Tamaño del índice de la base de datos: 116.75MB
wp3_woocommerce_sessions: Datos: 0.20MB + Índice: 0.01MB + Motor MyISAM
wp3_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_attribute_taxonomies: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp3_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor MyISAM
wp3_woocommerce_order_itemmeta: Datos: 0.26MB + Índice: 0.14MB + Motor MyISAM
wp3_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp3_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_actionscheduler_actions: Datos: 33.20MB + Índice: 29.91MB + Motor InnoDB
wp3_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_actionscheduler_logs: Datos: 23.56MB + Índice: 22.06MB + Motor InnoDB
wp3_aelia_dismissed_messages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_aelia_exchange_rates_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_ahm_download_stats: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_ahm_emails: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_ajaxsearchpro: Datos: 0.11MB + Índice: 0.00MB + Motor InnoDB
wp3_ajaxsearchpro_priorities: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_ajaxsearchpro_statistics: Datos: 0.17MB + Índice: 0.00MB + Motor InnoDB
wp3_akeeba_common: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_ak_params: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_ak_profiles: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_ak_stats: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_ak_storage: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_ak_users: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_apto_sort_list: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp3_asp_index: Datos: 5.52MB + Índice: 8.03MB + Motor InnoDB
wp3_asp_synonyms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_cmplz_cookiebanners: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_cmplz_cookies: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp3_cmplz_services: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_commentmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_comments: Datos: 0.06MB + Índice: 0.04MB + Motor MyISAM
wp3_duplicator_packages: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_ewwwio_images: Datos: 0.13MB + Índice: 0.11MB + Motor InnoDB
wp3_frm_fields: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp3_frm_forms: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_frm_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_frm_item_metas: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_fusion_forms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_fusion_form_entries: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_fusion_form_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_fusion_form_submissions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_gdbc_attempts: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_gdpr_cc_options: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_glossary_database_cache: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_glossary_related: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_background_task: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_icl_languages_translations: Datos: 0.19MB + Índice: 0.11MB + Motor InnoDB
wp3_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_icl_mo_files_domains: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_strings: Datos: 11.52MB + Índice: 19.09MB + Motor InnoDB
wp3_icl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_string_packages: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_string_pages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_icl_string_positions: Datos: 1.52MB + Índice: 0.28MB + Motor InnoDB
wp3_icl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_string_translations: Datos: 1.52MB + Índice: 0.41MB + Motor InnoDB
wp3_icl_string_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_icl_translate: Datos: 37.55MB + Índice: 2.52MB + Motor InnoDB
wp3_icl_translate_job: Datos: 0.23MB + Índice: 0.11MB + Motor InnoDB
wp3_icl_translations: Datos: 1.52MB + Índice: 3.94MB + Motor InnoDB
wp3_icl_translation_batches: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_translation_downloads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_icl_translation_status: Datos: 21.52MB + Índice: 0.16MB + Motor InnoDB
wp3_ju_queue: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_litespeed_img_optm: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp3_litespeed_optimizer: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_mailchimp_jobs: Datos: 74.61MB + Índice: 0.00MB + Motor InnoDB
wp3_nm_checkoutmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_options: Datos: 106.41MB + Índice: 1.49MB + Motor MyISAM
wp3_pmxe_exports: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxe_google_cats: Datos: 0.39MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxe_posts: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxe_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_files: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_hash: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_images: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_imports: Datos: 0.47MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_posts: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp3_pmxi_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_postmeta: Datos: 23.84MB + Índice: 7.02MB + Motor MyISAM
wp3_posts: Datos: 70.88MB + Índice: 1.08MB + Motor MyISAM
wp3_realmedialibrary: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_realmedialibrary_debug: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_realmedialibrary_icl_count: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_realmedialibrary_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_realmedialibrary_posts: Datos: 0.33MB + Índice: 0.33MB + Motor InnoDB
wp3_realmedialibrary_tmp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_redirection_404: Datos: 0.36MB + Índice: 0.17MB + Motor InnoDB
wp3_redirection_groups: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_redirection_items: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp3_redirection_logs: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp3_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_termmeta: Datos: 0.28MB + Índice: 0.22MB + Motor MyISAM
wp3_terms: Datos: 0.14MB + Índice: 0.24MB + Motor MyISAM
wp3_term_relationships: Datos: 0.15MB + Índice: 0.31MB + Motor MyISAM
wp3_term_taxonomy: Datos: 0.17MB + Índice: 0.14MB + Motor MyISAM
wp3_usermeta: Datos: 8.95MB + Índice: 6.57MB + Motor MyISAM
wp3_users: Datos: 0.53MB + Índice: 0.55MB + Motor MyISAM
wp3_wc_admin_notes: Datos: 0.11MB + Índice: 0.00MB + Motor InnoDB
wp3_wc_admin_note_actions: Datos: 0.08MB + Índice: 0.02MB + Motor InnoDB
wp3_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wc_customer_lookup: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp3_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_wc_order_composite_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp3_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp3_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp3_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_wc_product_attributes_lookup: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
wp3_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wc_product_meta_lookup: Datos: 0.14MB + Índice: 0.31MB + Motor InnoDB
wp3_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wfblockediplog: Datos: 0.20MB + Índice: 0.00MB + Motor InnoDB
wp3_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp3_wfconfig: Datos: 0.48MB + Índice: 0.00MB + Motor InnoDB
wp3_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wffilemods: Datos: 11.55MB + Índice: 0.00MB + Motor InnoDB
wp3_wfhits: Datos: 1.52MB + Índice: 0.23MB + Motor InnoDB
wp3_wfhoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wfissues: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wp3_wfknownfilelist: Datos: 8.52MB + Índice: 0.00MB + Motor InnoDB
wp3_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wflogins: Datos: 0.38MB + Índice: 0.16MB + Motor InnoDB
wp3_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_wfls_role_counts: Datos: 0.00MB + Índice: 0.00MB + Motor MEMORY
wp3_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp3_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp3_wfstatus: Datos: 0.22MB + Índice: 0.09MB + Motor InnoDB
wp3_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wfwaffailures: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_woocommerce_bundled_itemmeta: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp3_woocommerce_bundled_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_wpfd_statistics: Datos: 2.52MB + Índice: 7.58MB + Motor InnoDB
wp3_wpfd_tokens: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wpfm_backup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wpmelon_advbedit_temp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp3_wt_iew_action_history: Datos: 0.30MB + Índice: 0.00MB + Motor InnoDB
wp3_wt_iew_cron: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wt_iew_ftp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_wt_iew_mapping_template: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp3_yoast_indexable: Datos: 1.52MB + Índice: 1.05MB + Motor InnoDB
wp3_yoast_indexable_hierarchy: Datos: 0.16MB + Índice: 0.25MB + Motor InnoDB
wp3_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp3_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp3_yoast_seo_links: Datos: 0.36MB + Índice: 0.23MB + Motor InnoDB
wp3_yoast_seo_meta: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

acf-field: 5
acf-field-group: 1
apto_sort: 86
attachment: 5842
avada_faq: 47
avada_portfolio: 98
custom_css: 2
extra_product_tab: 3
frm_form_actions: 1
frm_styles: 1
fusion_element: 8
fusion_tb_layout: 2
fusion_tb_section: 9
fusion_template: 10
global_product_addon: 1
glossary: 192
mailpoet_page: 1
mc4wp-form: 2
nav_menu_item: 267
oembed_cache: 11
page: 81
post: 84
product: 664
product_variation: 126
revision: 1629
shop_coupon: 3
shop_order: 154
shop_order_refund: 1
slide: 6
tablepress_table: 203
tm_global_cp: 2
wc_product_tab: 234
wpcf7_contact_form: 6
wpdmpro: 12
wpfd_file: 366
wplp-news-widget: 1
wp_navigation: 1
ywctm-button-label: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

WPML Multilingual CMS: por OnTheGoSystems – 4.6.3
CM Tooltip Glossary Pro+: por CreativeMindsSolutions – 3.8.5
Advanced Custom Fields Multilingual: por OnTheGoSystems – 2.0.5
Advanced Custom Fields PRO: por WP Engine – 6.1.6
Advanced Post Types Order: por Nsp Code – 4.8.3
Ajax Search Pro: por Ernest Marcinko – 4.14.2
Better Search Replace: por WP Engine – 1.4.2
Complianz | GDPR/CCPA Cookie Consent: por Really Simple Plugins – 6.4.6
Contact Form 7 Multilingual: por OnTheGoSystems – 1.2.1
Contact Form 7: por Takayuki Miyoshi – 5.7.7
Joinchat: por Creame – 4.5.20
Flexible Checkout Fields: por WP Desk – 3.5.9
Avada Builder: por ThemeFusion – 3.10.1
Avada Core: por ThemeFusion – 5.10.1
Health Check & Troubleshooting: por La comunidad de WordPress.org – 1.6.0
Improved Variable Product Attributes for WooCommerce: por Mihajlovic Nenad – 4.4.1
WooCommerce Load More Products: por BeRocket – 1.1.9.8
Mailchimp for WooCommerce: por Mailchimp – 2.8.3
MC4WP: Mailchimp for WordPress: por ibericode – 4.9.4
Manage Notification E-mails: por Virgial Berveling – 1.8.5
Real Media Library: por devowl.io – 4.20.4
Redirection: por John Godley – 5.3.10
TablePress: por Tobias Bäthge – 2.1.4
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.23.4

W3 Total Cache: por BoldGrid – 2.3.2
Aelia Foundation Classes for WooCommerce: por Aelia – 2.4.8.230524
Converter for Media: por matt plugins – 5.9.1
WooCommerce Additional Variation Images: por WooCommerce – 2.0.0 (la actualización a la versión 2.3.2 está disponible)
WooCommerce Advanced Bulk Edit: por George Iron – 5.0.1
WooCommerce Composite Products: por WooCommerce – 8.4.3 (la actualización a la versión 8.8.1 está disponible)
WooCommerce EU VAT Assistant: por Aelia – 2.0.43.230518
WooCommerce Servired/RedSys Spain Gateway: por José Conti – 4.4.2 (la actualización a la versión 21.0.0 está disponible)
WooCommerce Multilingual & Multicurrency: por OnTheGoSystems – 5.1.3
WooCommerce Tab Manager: por SkyVerge – 1.15.0
WooCommerce TM Extra Product Options: por themeComplete – 5.2
WooCommerce: por Automattic – 7.7.2
WooCommerce Conditional Shipping: por RightPress – 1.4.1
Wordfence Security: por Wordfence – 7.9.3
Yoast SEO: por Equipo Yoast – 20.8
WP File Download: por Joomunited – 5.6.10
MailChimp for WordPress Multilingual: por OnTheGoSystems – 0.0.3
WPML String Translation: por OnTheGoSystems – 3.2.5

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: por  – 1.9.0
ju-libraries.php: por Joomunited – 1.0.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #20536 - /tienda/
Carrito: #5 - /cart/
Finalizar compra: #6 - /checkout/
Mi cuenta: #7 - /acc/
Términos y condiciones: #22750 - /condiciones-generales-de-contratacion/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.10.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Composite Products ###

Database Version: 8.4.3
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-08 11:21:48 +02:00
Options: ✔
Notes: 155
Onboarding: completed

### Action Scheduler ###

Canceled: 31
Oldest: 2023-05-23 13:19:28 +0200
Newest: 2023-06-07 10:55:51 +0200

Complete: 109.854
Oldest: 2023-05-07 21:36:33 +0200
Newest: 2023-06-07 21:36:21 +0200

Failed: 24
Oldest: 2021-04-20 14:49:12 +0200
Newest: 2023-06-06 13:44:02 +0200

In-progress: 1
Oldest: –
Newest: –

Pending: 39
Oldest: 2023-06-07 21:35:52 +0200
Newest: 2023-06-08 16:09:11 +0200

### Status report information ###

Generated at: 2023-06-07 21:36:29 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> but I don't want to be overriden on next updates :)

@ninoort Thanks for reporting the issue. This is too late for the fix to be included in WC 7.8 but you should see it fixed in WC 7.9.
