### ISSUE TITLE
Inject Personality into the prompts

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#38655]
We could accept some content examples through a settings page (prompt the user while they're generating a title), then, perform some basic "sentiment analysis" (cheery, professional, casual, neutral, youthful, humorous) to get a very basic tone for the store.
We can then inject that simple tone adjective into the prompt when generating descriptions and titles.

**Comment by DavidAnderson684** [comment]
Please strongly consider not doing this. Across WordPress, the experience of non-US English speakers is that what presumably the US English developers considered as being a clever, funny or whatever tone, frequently comes across as unprofessional, patronising or just plain irritating. Please instead just implement language that is professional and understandable. If someone wants their store to be cutsey and have "personality" then that can be implemented as an extension....
