### ISSUE TITLE
Spike: Look into controls around user abusing completion services

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#38654]
Look into capabilities around cutting off users that exceed a certain quota, and are abusing the service in any way.

**Comment by joelclimbsthings** [comment]
We _do_ have logging and caps on a per-blog basis with the following in mind:

- [_Not_ enabled for blogs on Atomic](https://code.a8c.com/source/wpcom-git/browse/trunk/wp-content/rest-api-plugins/endpoints/jetpack-ai-query.php$150). 
- Only enabled for Jetpack sites (as per `is_blog_jetpack()`)
- Even when enabled, sites with `WPCOM_Features::AI_ASSISTANT` enabled are not limited.
- Other sites have a [max of 20 requests](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sbcranv%2Sbcranv%2Qyvzvg%2Qhfntr.cuc%3Se%3Q6sn27rpr%2313-og). (defined directly in class)

In short, blogs that are not Jetpack sites (little uncertain where this would fall), on Atomic, or have the AI Assistant feature enabled are not capped.

With this in mind, we need to decide what we want our limits should be, and how compatible they are with the above. Assuming they are not compatible, this may be an enhancement dependent on creating our own endpoint. Even then we may need to modify the `OpenAI_Limit_Usage` class as it's hard-coded to the 20 requests.

**Open Questions**
- I'm a little unsure if any requests could originate from what would not be considered a "jetpack" site as per the above logic, since a valid token must be present anyways. [The logic](fbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sshapgvbaf.cuc%3Se%3Q0717p84q%237-og) for `is_blog_jetpack()` checks the site_id in the blog details, but I'm still unsure of where this originates or if it's something we need to worry about.

That said, it may be fairly moot if we need to create our own endpoint anyways. 

Any thoughts @woocommerce/singularity ?

**Comment by tommyshellberg** [comment]
> With this in mind, we need to decide what we want our limits should be, and how compatible they are with the above. Assuming they are not compatible, this may be an enhancement dependent on creating our own endpoint. Even then we may need to modify the `OpenAI_Limit_Usage` class as it's hard-coded to the 20 requests.
> That said, it may be fairly moot if we need to create our own endpoint anyways.

Since we're creating our own endpoint, we could create our own usage class with its own enforcements rather than be beholden to a hard-coded 20 request limit. Once we are instantiating our own WooAI class rather than OpenAI directly, we could roll our own usage tracking and enforcement functionality. That would certainly move things along faster for us.

Is there an opportunity to refactor the `OpenAI_Limit_Usage` class to allow for feature-specific limits that could be backward-compatible?

**Comment by joelclimbsthings** [comment]
Right, good thoughts @tommyshellberg . When I looked at this last week it appeared that the `OpenAI_Limit_Usage` class was only referenced from the Jetpack code directly -- not the OpenAI class itself -- so we could safely ignore it and roll our own. 

The fact that Jetpack colocated it with the OpenAI class suggested that they intended it to be more general, so refactoring might be an option. It would make sense to have some support for this more central to the `OpenAI` class that all consumers could benefit from.

**Comment by laurendavissmith** [comment]
@joelclimbsthings To create another issue more automation around user abuse
@joelclimbsthings To create another issue for getting the Woo AI extension to use the Woo generic endpoint
