### ISSUE TITLE
jet_header doesn't load on woocommerce cart in safari

### ISSUE THREAD

**Issue by Waves99** [woothemes/woocommerce#38667]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I use jet plugins, and I belive jet_header doesn't load correctly in Safari v 15.6 ( only version I tested )

### Expected behavior

This is how it should look and it does in any other browser.
<img width="1716" alt="Screenshot 2023-06-09 at 20 41 20" src="https://github.com/woocommerce/woocommerce/assets/136117932/05047c85-4af6-43db-b664-5a7ff7a50c3c">

### Actual behavior

This is the displayed view of the header in Safari v15.6 on macbook

<img width="1721" alt="Screenshot 2023-06-09 at 20 40 45" src="https://github.com/woocommerce/woocommerce/assets/136117932/c3079dbb-a428-4d25-9cf8-b8b0a9610181">

### Steps to reproduce

This bug only happends when I open the Cart page in Safari on macbook. Havent tried on Safari in Iphone

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://lns.si
Site address (URL): https://lns.si
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.2.1 - Na voljo je nova različica WordPress-a (6.2.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: sl_SI
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wpkc_
Skupna velikost podatkovne zbirke: 177.07MB
Velikost podatkov podatkovne zbirke: 154.92MB
Velikost kazala podatkovne zbirke: 22.15MB
wpkc_woocommerce_sessions: Podatki: 0.11 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_woocommerce_api_keys: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_woocommerce_attribute_taxonomies: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_woocommerce_downloadable_product_permissions: Podatki: 0.02 MB + Kazalo: 0.06 MB + Pogon InnoDB
wpkc_woocommerce_order_items: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_woocommerce_order_itemmeta: Podatki: 0.11 MB + Kazalo: 0.09 MB + Pogon InnoDB
wpkc_woocommerce_tax_rates: Podatki: 0.02 MB + Kazalo: 0.06 MB + Pogon InnoDB
wpkc_woocommerce_tax_rate_locations: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_woocommerce_shipping_zones: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_woocommerce_shipping_zone_locations: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_woocommerce_shipping_zone_methods: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_woocommerce_payment_tokens: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_woocommerce_payment_tokenmeta: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_woocommerce_log: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_actionscheduler_actions: Podatki: 5.03 MB + Kazalo: 3.41 MB + Pogon InnoDB
wpkc_actionscheduler_claims: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_actionscheduler_groups: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_actionscheduler_logs: Podatki: 1.52 MB + Kazalo: 1.84 MB + Pogon InnoDB
wpkc_commentmeta: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_comments: Podatki: 0.02 MB + Kazalo: 0.09 MB + Pogon InnoDB
wpkc_e_events: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_gla_attribute_mapping_rules: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_gla_budget_recommendations: Podatki: 0.22 MB + Kazalo: 0.14 MB + Pogon InnoDB
wpkc_gla_merchant_issues: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_gla_shipping_rates: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_gla_shipping_times: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_jet_smart_filters_indexer: Podatki: 0.14 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_links: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_litespeed_avatar: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_litespeed_crawler: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_litespeed_crawler_blacklist: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_litespeed_img_optming: Podatki: 1.52 MB + Kazalo: 0.53 MB + Pogon InnoDB
wpkc_litespeed_url: Podatki: 0.09 MB + Kazalo: 0.09 MB + Pogon InnoDB
wpkc_litespeed_url_file: Podatki: 0.02 MB + Kazalo: 0.08 MB + Pogon InnoDB
wpkc_mailpoet_automation_run_logs: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_automation_run_subjects: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_automation_runs: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_automation_triggers: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_automation_versions: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_automations: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_custom_fields: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_dynamic_segment_filters: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_feature_flags: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_forms: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_log: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_mapping_to_external_entities: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_migrations: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_links: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_option: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_option_fields: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_posts: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_segment: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_newsletter_templates: Podatki: 2.52 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_newsletters: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_scheduled_task_subscribers: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_scheduled_tasks: Podatki: 0.08 MB + Kazalo: 0.06 MB + Pogon InnoDB
wpkc_mailpoet_segments: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_sending_queues: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_settings: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_statistics_bounces: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_mailpoet_statistics_clicks: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_mailpoet_statistics_forms: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_statistics_newsletters: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_statistics_opens: Podatki: 0.02 MB + Kazalo: 0.08 MB + Pogon InnoDB
wpkc_mailpoet_statistics_unsubscribes: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_mailpoet_statistics_woocommerce_purchases: Podatki: 0.02 MB + Kazalo: 0.06 MB + Pogon InnoDB
wpkc_mailpoet_stats_notifications: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_subscriber_custom_field: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_subscriber_ips: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_subscriber_segment: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_subscriber_tag: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_mailpoet_subscribers: Podatki: 0.02 MB + Kazalo: 0.13 MB + Pogon InnoDB
wpkc_mailpoet_tags: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_user_agents: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_mailpoet_user_flags: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_options: Podatki: 8.45 MB + Kazalo: 0.13 MB + Pogon InnoDB
wpkc_postmeta: Podatki: 77.17 MB + Kazalo: 10.67 MB + Pogon InnoDB
wpkc_posts: Podatki: 51.16 MB + Kazalo: 0.78 MB + Pogon InnoDB
wpkc_revslider_css: Podatki: 0.13 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_css_bkp: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_layer_animations: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_revslider_layer_animations_bkp: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_revslider_navigations: Podatki: 0.06 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_revslider_navigations_bkp: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_revslider_sliders: Podatki: 0.09 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_sliders_bkp: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_slides: Podatki: 1.52 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_slides_bkp: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_static_slides: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_revslider_static_slides_bkp: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_smartcrawl_redirects: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_smush_dir_images: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_term_relationships: Podatki: 0.22 MB + Kazalo: 0.13 MB + Pogon InnoDB
wpkc_term_taxonomy: Podatki: 0.06 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_termmeta: Podatki: 0.28 MB + Kazalo: 0.39 MB + Pogon InnoDB
wpkc_terms: Podatki: 0.05 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_usermeta: Podatki: 0.09 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_users: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_wc_admin_note_actions: Podatki: 0.05 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_wc_admin_notes: Podatki: 0.08 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_wc_category_lookup: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_wc_customer_lookup: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_wc_download_log: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_wc_order_coupon_lookup: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_wc_order_product_lookup: Podatki: 0.02 MB + Kazalo: 0.06 MB + Pogon InnoDB
wpkc_wc_order_stats: Podatki: 0.02 MB + Kazalo: 0.05 MB + Pogon InnoDB
wpkc_wc_order_tax_lookup: Podatki: 0.02 MB + Kazalo: 0.03 MB + Pogon InnoDB
wpkc_wc_product_attributes_lookup: Podatki: 0.25 MB + Kazalo: 0.09 MB + Pogon InnoDB
wpkc_wc_product_download_directories: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_wc_product_meta_lookup: Podatki: 0.16 MB + Kazalo: 0.33 MB + Pogon InnoDB
wpkc_wc_rate_limits: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_wc_reserved_stock: Podatki: 0.02 MB + Kazalo: 0.00 MB + Pogon InnoDB
wpkc_wc_tax_rate_classes: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_wc_webhooks: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_yoast_indexable: Podatki: 1.52 MB + Kazalo: 0.45 MB + Pogon InnoDB
wpkc_yoast_indexable_hierarchy: Podatki: 0.08 MB + Kazalo: 0.14 MB + Pogon InnoDB
wpkc_yoast_migrations: Podatki: 0.02 MB + Kazalo: 0.02 MB + Pogon InnoDB
wpkc_yoast_primary_term: Podatki: 0.08 MB + Kazalo: 0.09 MB + Pogon InnoDB
wpkc_yoast_seo_links: Podatki: 0.30 MB + Kazalo: 0.27 MB + Pogon InnoDB

### Post Type Counts ###

attachment: 2378
customize_changeset: 3
custom_css: 1
elementor_library: 31
jet-menu: 2
jet-page-template: 2
jet-popup: 5
jet-smart-filters: 10
jet-theme-core: 9
jet-woo-builder: 12
mailpoet_page: 1
nav_menu_item: 215
page: 80
post: 18
product: 868
product_variation: 222
revision: 49
shop_coupon: 10
shop_order: 25
wpcf7_contact_form: 3
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Beehive Pro: od WPMU DEV – 3.4.5
Contact Form 7: od Takayuki Miyoshi – 5.7.6
Disable Thumbnails, Threshold and Image Options: od KGM Servizi – 0.4
Duplicate Page: od mndpsingh287 – 4.5.2
GTM4WP: od Thomas Geiger – 1.16.2
Elementor: od Elementor.com – 3.13.4
JetBlocks For Elementor: od Crocoblock – 1.3.2
JetBlog For Elementor: od Crocoblock – 2.3.1
JetCompareWishlist For Elementor: od Crocoblock – 1.5.1
JetElements For Elementor: od Crocoblock – 2.6.6
JetMenu: od Crocoblock – 2.2.2
JetPopup: od Crocoblock – 1.5.6
JetSmartFilters: od Crocoblock – 2.3.13
JetTabs For Elementor: od Crocoblock – 2.1.18
JetThemeCore: od Crocoblock – 2.0.5
JetWooBuilder For Elementor: od Crocoblock – 2.0.1
JetProductGallery: od Crocoblock – 2.1.5
LiteSpeed Cache: od LiteSpeed Technologies – 5.4
Markup by Attribute for WooCommerce: od MarkTomlinson – 3.11.1
Slider Revolution: od ThemePunch – 6.5.24
WooCommerce Weight Based Shipping: od weightbasedshipping.com – 5.5.1
WooCommerce PayPal Payments: od WooCommerce – 2.0.4 (razpoložljiva je nadgradnja na različico 2.0.5)
WooCommerce: od Automattic – 7.6.1 (razpoložljiva je nadgradnja na različico 7.7.2)
Smush Pro: od WPMU DEV – 3.13.0
SmartCrawl Pro: od WPMU DEV – 3.6.3
WPMU DEV Dashboard: od WPMU DEV – 4.11.18

### Inactive Plugins (7) ###

Facebook for WooCommerce: od Facebook – 3.0.22
Google Listings and Ads: od WooCommerce – 2.4.4
Jet Data Importer: od Zemez – 1.2.2
Jetpack: od Automattic – 11.7.2
Jet Plugins Wizard: od Zemez – 1.2.9
JetTricks: od Crocoblock – 1.4.2
MailPoet: od MailPoet – 4.14.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Osnova trgovine: #3370 - /trgovina/
Košarica: ❌ Stran ne vsebuje kratke kode [woocommerce_cart] ali bloka woocommerce/cart.
Zaključek nakupa: #11 - /checkout/
Moj račun: #12 - /my-account/
Pogoji poslovanja: #532 - /pogoji-poslovanja/

### Theme ###

Name: Cosmetro
Version: 4.0.6
Author URL: http://Zemez.io
Child Theme: ❌ – Če spreminjate WooCommerce na nadrejeni temi
ki je niste zgradili sami
svetujemo
da uporabite podrejeno temo. Kako ustvariti podrejeno temo

WooCommerce Support: ✔

### Templates ###

Overrides: cosmetro/woocommerce/emails/plain/admin-new-order.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: SI
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-09 23:25:44 +02:00
Options: ✔
Notes: 117
Onboarding: completed

### Action Scheduler ###

Zaključi: 7.698
Oldest: 2023-05-09 20:39:10 +0200
Newest: 2023-06-09 17:28:06 +0200

Spodletelo: 39
Oldest: 2022-12-11 19:52:14 +0100
Newest: 2023-06-09 17:28:06 +0200

V obdelavi: 2
Oldest: 2023-06-10 17:28:06 +0200
Newest: 2023-06-10 17:28:06 +0200

### Status report information ###

Generated at: 2023-06-09 20:38:47 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
@Waves99 Thanks for the report. I'm not familiar with Jet plugins, but it seems like the header not working in Safari problem would be better alerted to the authors of the plugin.

**Comment by rrennick** [comment]
Closing due to lack of feedback.
