### ISSUE TITLE
A product is added to the Cart when reloading the single page product

### ISSUE THREAD

**Issue by tarhi-saad** [woothemes/woocommerce#38692]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Each time we reload the page after adding a product from the single page product to the Cart, another item will be added.

### Expected behavior

An item should only be added to the Cart when the `Add to cart` button is clicked. Reloading the single page product shouldn't have any side effects.

### Actual behavior

When we reload the page after adding an item from the single page product to the cart, another item will be added.

### Steps to reproduce

1. Go to the shop page
2. Click on a product to go to its specific page (single page product)
3. Add the item to the Cart
4. Keep this page open, and open the cart page in a new tab to check that the item was added
5. Go back to the previous tab (the single page product) and reload the page
6. Go to the Cart page again and reload. Ensure that an additional item was added to the Cart.
7. Repeat steps 5 & 6. Ensure that an additional item is added to the Cart each time we reload the single page product

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://dev-store.local
Site address (URL): http://dev-store.local
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.5.0-dev
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.87.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 13.64MB
Database Data Size: 10.50MB
Database Index Size: 3.14MB
wp_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 5.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.30MB + Index: 0.22MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_en_us_fr_fr: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 0.41MB + Index: 0.47MB + Engine InnoDB
wp_trp_gettext_fr_fr: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
language_switcher: 4
page: 16
post: 5
product: 21
product_variation: 11
revision: 109
shop_coupon: 2
shop_order: 30
wc_booking: 2
wo_client: 1
wp_global_styles: 3
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Code Snippets: by Code Snippets Pro – 3.4.0
Multiple Packages for WooCommerce: by Erica Dion – 1.1
WP OAuth Server - CE: by WP OAuth Server – 4.3.3
SMNTCS Show Symlinked Plugins: by Niels Lange – 1.0
WooCommerce Bookings: by WooCommerce – 1.16.01
WooCommerce: by Automattic – 7.9.0-dev
WooCommerce Blocks: by Automattic – 10.5.0-dev

### Inactive Plugins (24) ###

Add to Cart Form Shortcode for WooCommerce: by helgatheviking – 3.0.2
Block Manager: by Darren Cooney – 1.2.4
Debug Bar: by wordpressdotorg – 1.1.4
Enable Standard PayPal for WooCommerce: by Vik Cheema – 1.0.0
Gutenberg: by Gutenberg Team – 14.8.0-rc.1
IDPay payment gateway for Woocommerce: by IDPay – 2.2.3
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.0.6

Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.40

Query Monitor: by John Blackbourn – 3.12.2
Test Extension Compatibility: by The WordPress Contributors – 0.1.0
Test Plugine: by The WordPress Contributors – 0.1.0
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.5.2

Weglot Translate: by Weglot Translate team – 4.0.1
WooCommerce Amazon Pay: by WooCommerce – 2.4.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.4
WooCommerce EU VAT Number: by WooCommerce – 2.4.3
WooCommerce Mix and Match Products: by Kathy Darling – 2.1.1
WooCommerce Name Your Price: by Kathy Darling – 3.4.0
WooCommerce One Page Checkout: by Automattic – 2.3.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.4 (update to version 2.0.5 is available)
WooCommerce Stripe Gateway: by WooCommerce – 7.4.0
WooCommerce Stripe Gateway (dev): by WooCommerce – 7.0.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Rollback: by GiveWP.com – 1.7.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #60 - /cart/
Checkout: #62 - /checkout-block/
My account: #9 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Storefront
Version: 4.3.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/saad/Plugins/woocommerce-gutenberg-products-block/templates/notices/error.php
/Users/saad/Plugins/woocommerce-gutenberg-products-block/templates/notices/notice.php
/Users/saad/Plugins/woocommerce-gutenberg-products-block/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-13 21:27:34 +00:00
Options: ✔
Notes: 122
Onboarding: skipped

### Action Scheduler ###

Complete: 60
Oldest: 2023-05-15 14:35:26 +0000
Newest: 2023-06-13 13:51:22 +0000

Failed: 23
Oldest: 2023-02-06 15:17:03 +0000
Newest: 2023-05-08 13:43:17 +0000

Pending: 2
Oldest: 2023-06-14 13:51:22 +0000
Newest: 2023-07-09 21:06:52 +0000

### Status report information ###

Generated at: 2023-06-13 14:25:29 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
I went ahead and triaged this issue as part of monitoring WC 7.8 issues. I'm able to encounter this issue as far back as WC version 7.6.1. 

<img width="779" alt="KkmnH4ti53" src="https://github.com/woocommerce/woocommerce/assets/4509348/0381ef1a-a10e-4153-9a1c-a78624e93798">

I'm noting though, that this only happens when I click 'Continue' on this confirmation prompt:
<img width="363" alt="Ti6FECpYaR" src="https://github.com/woocommerce/woocommerce/assets/4509348/6d2362ad-16a5-4163-9c2d-5990a37630a0">

Clicking Cancel won't update the cart quantity.

**Comment by nerrad** [comment]
This is expected because the form action is being reloaded, and as @rodelgc noted, most browsers will throw up an AYS confirmation in this scenario.  

Since this is something that will be solved by the block being powered by the Interactive API and only impacts shoppers who explicitly confirm the action, I'm closing this issue.
