### ISSUE TITLE
Core profiler UI issues from design call

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#38731]
### Issue description

Core profiler UI issues were identified during a call pdibGW-255-p2:

1. Checkbox styling of tracking consent is not exactly following design. In particular, the borders.
2. ~~The color when hovering dropdown (ex: Selling online), the hover color is different~~(https://github.com/woocommerce/woocommerce/pull/38724)
3. Heading letters spacing looks a bit too compressed
4. Subheading color is different
5. `#FunWooFact` copy is repeated twice in one of the loading messages 
7. “Installed” label is not vertically center in its small box (slightly shifted up)

Partial UI issues from Figma Y5pUYSJPsGEud1vknUZhi8-fi-1911_37790: 

1. In the warning message (2nd profiler question), the link doesn’t follow the color scheme. Could we please align? ([screenshot](https://github.com/woocommerce/woocommerce/assets/3747241/90d9a4d1-dd3d-4faa-997c-0d006ccac9c6))

### Acceptance Criteria

1. Fix all issues mentioned above

**Comment by chihsuan** [comment]
> The color when hovering dropdown (ex: Selling online), the hover color is different

Related to 
- https://github.com/woocommerce/woocommerce/pull/38724

**Comment by ilyasfoo** [comment]
Thanks for highlighting that! I'll update the description
