### ISSUE TITLE
Analytics categories is broken when the user does not have manage_product_terms cap

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#38741]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a user role has the `view_woocommerce_reports` capability but not `manage_product_terms` they still have access to the `Categories` analytics screen. For users with that role the screen is broken with spinners in the `Category` column. Likewise, the `Products` analytics screen has an empty `Categories` column.

### Expected behavior

Given that product categories are publicly accessible on the from end of the site, the `view_woocommerce_reports` capability should give the user role read access to categories in the analytics screens.

### Actual behavior

See description above.

### Steps to reproduce

1. Install a role manager plugin
2. Create a test role
3. Grant the role the capabilities in the screenshot below
4. Create a test user with the above role
5. Log into the dashboard
6. Navigate to Analytics -> Products and Analytics -> Categories

<img width="230" alt="Screenshot 2023-06-15 at 10 24 26 AM" src="https://github.com/woocommerce/woocommerce/assets/343847/44dc6ec8-3963-4b1c-affb-6f00a3c6a2fa">

### WordPress Environment

Tested with WC `trunk` and latest WP.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by puntope** [comment]
I was testing this issue. What i see is just the category name with the spinner. The page is not broken.

<img width="792" alt="Screenshot 2024-07-04 at 14 31 47" src="https://github.com/woocommerce/woocommerce/assets/5908855/623cf9b0-75da-4718-9636-d8a65e8b552e">

Also, the [REST API from WC to product/categories](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories) also requires the same permissions for reading.

<img width="681" alt="Screenshot 2024-07-04 at 14 28 21" src="https://github.com/woocommerce/woocommerce/assets/5908855/c1da83ff-dc14-416f-a432-e338135c846a">

[Also, Checking the Woo Core it seems like manage_terms is what they use for reading permissions](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-rest-functions.php#L296).
