### ISSUE TITLE
[Enhancement]: Task List progress bar should show some bar at 0%

### ISSUE THREAD

**Issue by crunnells** [woothemes/woocommerce#38752]
### Describe the solution you'd like

In the task list for store setup, when the progress bar is at 0% it looks like an empty element or broken UI because there is no other visual indication of what this element is for. I think something as simple as pre-filling a small amount of the progress bar might indicate what it is: 

**Before**
<img width="712" alt="Screen Shot 2023-06-15 at 2 40 35 PM" src="https://github.com/woocommerce/woocommerce/assets/4297811/c965f666-ba48-492e-9013-36bade62b29e">

**After**
<img width="703" alt="Screen Shot 2023-06-15 at 2 44 34 PM" src="https://github.com/woocommerce/woocommerce/assets/4297811/94b79f64-4d0a-44ab-84dc-0e83f4b0113f">

### Describe alternatives you've considered

Alternatively, we could drop the progress bar completely to simplify the UI.

**Comment by verofasulo** [comment]
> when the progress bar is at 0% it looks like an empty element or broken UI because there is no other visual indication of what this element is for.

@crunnells yes 💜 This was on my optimizations list. The 0% doesn't make much sense and it's not encouraging and gratifying at all, especially after going through the profiler. Please let's move on with your proposal and pre-fill it a bit more 🙏

![image](https://github.com/woocommerce/woocommerce/assets/98944206/f372d495-7b26-4a90-9e15-a6ff6a2ab2a9)

Could we also update the copy, please? Thank you!

**Comment by crunnells** [comment]
> Could we also update the copy, please? Thank you!

Hi @verofasulo which copy did you want to update?

**Comment by verofasulo** [comment]
> which copy did you want to update?

@crunnells heading and subheading:

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/98944206/af777188-2cb6-4097-82d4-51a039908aac">

If the user hasn't added any store name yet, please default to "Welcome to your new store".  

Thank you 🙏 

cc @lauroraa
