### ISSUE TITLE
Fix Jetpack redirection error when Auth endpoint return an invalid URL

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#38758]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In the core profiler, the code does not account for a scenario where the authentication endpoint returns an invalid URL.

Please add a condition to verify the success flag of the endpoint and redirect users to the WooCommerce Home if the value is false.

**Comment by AndrewJDawes** [comment]
Disregard above commits and mentions for #38757 - I accidentally fat fingered an issue id! Sorry.
