### ISSUE TITLE
"Adding new attribute failed."

### ISSUE THREAD

**Issue by cbartosz** [woothemes/woocommerce#38755]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating to the newest version every time I go to the "Products" section in the admin I keep getting a popup saying "Adding new attribute failed." ... I've tried everything to fix it, wordpress, Avada, Woocommerce and all plugins are in the newest version, I cleared all the caches and used all of the woocommerce tools, also tried most of the troubleshooting tools.

### Expected behavior

NA

### Actual behavior

Everything is working normally apart from the warming window that keeps popping up.

### Steps to reproduce

1. wordpress Dashboard  2. Products 3. no matter what I click I get a popup saying "Adding new attribute failed."

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://book.alps2go.eu
Site address (URL): https://book.alps2go.eu
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_TW
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.2d

SUHOSIN Installed: –
MySQL Version: 5.7.33-36-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: q0sz_
Total Database Size: 40.60MB
Database Data Size: 32.79MB
Database Index Size: 7.81MB
q0sz_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
q0sz_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
q0sz_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
q0sz_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
q0sz_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_actionscheduler_actions: Data: 3.13MB + Index: 1.63MB + Engine InnoDB
q0sz_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_actionscheduler_logs: Data: 2.31MB + Index: 1.83MB + Engine InnoDB
q0sz_china_payments_stripe_customers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
q0sz_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_log: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_scheduled_tasks: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
q0sz_mailpoet_scheduled_task_subscribers: Data: 0.30MB + Index: 0.14MB + Engine InnoDB
q0sz_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
q0sz_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
q0sz_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_subscribers: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
q0sz_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_options: Data: 7.36MB + Index: 0.16MB + Engine InnoDB
q0sz_postmeta: Data: 2.45MB + Index: 0.88MB + Engine InnoDB
q0sz_posts: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
q0sz_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_usermeta: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
q0sz_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
q0sz_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
q0sz_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
q0sz_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
q0sz_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
q0sz_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
q0sz_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
q0sz_wpml_mails: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
q0sz_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
q0sz_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 227
awcdp_payment: 34
br_product_tab: 2
br_tabs_location: 1
custom_css: 1
customize_changeset: 6
mailpoet_page: 1
nav_menu_item: 7
page: 12
post: 2
product: 24
product_variation: 44
revision: 9
shop_coupon: 3
shop_order: 122
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Avada Builder: by ThemeFusion – 3.10.1
Avada Core: by ThemeFusion – 5.10.1
Jetpack Protect: by Automattic - Jetpack Security team – 1.4.0
Jetpack: by Automattic – 12.2.1
MailPoet: by MailPoet – 4.18.1
Slider Revolution: by ThemePunch – 6.6.14
Safe SVG: by 10up – 2.1.1
Simple Admin Language Change: by Karolína Vyskočilová – 2.0.4
WooCommerce: by Automattic – 7.8.0

### Inactive Plugins (15) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
All-in-One WP Migration With Import: by ServMask – 6.77
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
China Payments Plugin: by Gaucho Plugins – 3.2.3
Code Snippets: by Code Snippets Pro – 3.4.0
Currency per Product for WooCommerce: by Tyche Softwares – 1.5.0
Currency per Product for WooCommerce Pro: by Tyche Softwares – 1.9.0
Deposits & Partial Payments for WooCommerce - Pro: by Acowebs – 3.1.3
Invoices for WooCommerce: by Bas Elbers – 3.1.9
Payment Gateway Based Fees and Discounts for WooCommerce: by Tyche Softwares – 2.9.0
Product Tabs Manager for WooCommerce: by BeRocket – 1.1.5.8
WeChat & Alipay for WordPress (Premium) (Premium): by WP Stripe Global – 1.3.1
WooCommerce Direct Checkout: by QuadLayers – 3.1.2
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WP Mail Logging: by WP Mail Logging Team – 1.11.2

### Must Use Plugins (1) ###

WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #10032 - /terms-conditions/

### Theme ###

Name: Avada
Version: 7.10.1
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/emails/customer-completed-order.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-16 15:32:08 +00:00
Options: ✔
Notes: 114
Onboarding: completed

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Current sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://book.alps2go.eu?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 7,278
Oldest: 2023-05-16 03:16:51 +0000
Newest: 2023-06-16 02:45:07 +0000

Pending: 3
Oldest: 2023-06-16 02:45:46 +0000
Newest: 2023-06-16 17:56:13 +0000

Failed: 27
Oldest: 2023-06-06 04:58:52 +0000
Newest: 2023-06-15 06:25:56 +0000

### Status report information ###

Generated at: 2023-06-16 02:45:21 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Zealth57** [comment]
This happens to me as well. If I navigate to the product list page in the admin and then try to navigate away from there to any other page (editing a product, refreshing the page, going to a different admin page) I get this popup. There's also console errors which may be related:

Uncaught (in promise) 
Object { code: "fetch_error", message: "You are probably offline." }
6 meta-boxes-product.min.js:1:7253

Uncaught (in promise) 
Object { jqXHR: {…}, textStatus: "error", errorThrown: "" }
meta-boxes-product.min.js:1:7380

Downgrading to 7.7.2 fixes the popup but I still get one of the console errors:
Uncaught (in promise) 
Object { jqXHR: {…}, textStatus: "error", errorThrown: "" }
meta-boxes-product.min.js:1:7380

**Comment by kurtgschumacher** [comment]
Just started happening, immediately after updating to WooCommerce 7.8.0. No other updates were done, just WooCommerce.

**Comment by cbartosz** [comment]
Just a comment that the problem started after updating to v7.8.0, same as in the case of others commenting here.

tried disabling all the plugins but Woocommerce, removing all the products with attributes, problem is still there.

**Comment by ghost** [comment]
We are facing the exact same problem. Version 7.8.0

**Comment by SirRahikkala** [comment]
I can confirm that when clicking the product, the popup is triggered and console says "Uncaught (in promise) 
Object { code: "fetch_error", message: "You are probably offline." }"

**Comment by smakhalov** [comment]
"Adding new attribute failed." - Same for me, WooCommerce 7.8.0

**Comment by walkinverse** [comment]
I have the same issue on two sites. When I roll back to woo Version 7.7.2 the issue goes away. So its tied to 7.8.0. Also, I have no attributes on one of my sites. Yet get the error with the current version saying error adding attributed popup even when no attributes exists.

**Comment by mattsherman** [comment]
I can reproduce this in Firefox and am working on a fix in #38815

**Comment by freebeans** [comment]
I've seen someone mention disabling WooCommerce Analytics fixed it for them. I did not investigate any further, but disabling then re-enabling it solved the issue for me.

**Comment by GSQweb** [comment]
I have also been having this "Failed Attributes" error occurring since we upgraded to V7.8, plus now with V7.9 getting constant 503 Error messages. Host has said nothing wrong at their end, and only occurs with new or editing products or any sort of attempt to get into WooCommerce to update ticket sales. This is vital for us that we find a solution please as cannot keep this going it is affecting our website producation. All other pages working ok with no errors. Host suggested we install litespeed cache plug in of which we have, they run litespeed server, improvement in website but has not stopped the errors in WooCommerce. Please I am getting very very desperate to get this solved.
