### ISSUE TITLE
Consider replacing "To do's" with "Tasks" in the admin home screen

### ISSUE THREAD

**Issue by costdev** [woothemes/woocommerce#38767]
In [the admin home screen](https://github.com/woocommerce/woocommerce/blob/1f3022e9e8d5f5a0516f432d09fdda0358d73fbc/plugins/woocommerce-admin/client/homescreen/layout.js#L109), the following string is used:

> To do's, tips, and insights for your business

There are several variations of "To do" - such as "Todo", "To-do" - and using `'s` for a plural, while arguably accepted in certain circumstances, may look grammatically incorrect to users.

For clarity, it may be worth replacing this with "Tasks".

**Comment by adrianduffell** [comment]
Thanks for the issue @costdev!

This can be reproduced by viewing the homescreen with the main task list completed / disabled. <img width="1099" alt="Screen Shot 2023-09-04 at 11 29 31 am" src="https://github.com/woocommerce/woocommerce/assets/9312929/e430c870-6295-4e43-a5ab-2093df193129">

I'd agree the apostrophe is incorrect. Out of the options, I have a slight preference for "To-dos".  I believe the sentence refers to store management jobs such as fulfilling orders or replenishing stock. I'd choose "to-dos" over "tasks" to avoid confusion with the main task list items.

@jarekmorawski Do you have thoughts on the best wording for this?
