### ISSUE TITLE
Core profiler loader screen layout shifts

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#38762]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Seems like there are some layout shifts during progression of the new core profiler loader:

https://github.com/woocommerce/woocommerce/assets/27843274/08e786d4-dc59-41ff-b09e-0919105dda21

**Comment by ilyasfoo** [comment]
There are multiple ways to fix this. I suggest we set a minimum size for each element.

**Comment by ilyasfoo** [comment]
There are multiple ways to fix this, I suggest we set a minimum size for each element.

**Comment by rjchow** [comment]
@crunnells I think https://github.com/woocommerce/woocommerce/pull/39735 will affect your progress on this task! Probably branch off my branch until it's merged so that you don't need to rework!

Good news is that you can use Storybook to work on this so that you can see the changes as you make them rather than having to go back and forth to trigger the loading screen 😁

**Comment by crunnells** [comment]
@rjchow Thanks for the heads up. Turns out the shift was due to a couple of things, but the biggest culprit is that the fun fact text changes from 3 lines on the first loading screen to two lines in the subsequent loading screens. Also the SVG images were all slightly different sizes.
