### ISSUE TITLE
Shipping Address missing on New Order email

### ISSUE THREAD

**Issue by mgswetnam** [woothemes/woocommerce#38770]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When New Order emails are received they include the Billing Address, but not the Shipping Address. This behavior began on or around May 23, 2023.

### Expected behavior

New Order email should include both the Billing Address and the Shipping Address. 

### Actual behavior

When a New Order email is received, it includes the Billing Address only. No Shipping Addres is included on the email.

### Steps to reproduce

1. Go to the New Order email
2. Scroll to the customer details
3. Note the absence of Shipping Address

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://payment.lindstromair.com
Site address (URL): https://payment.lindstromair.com
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wpkm_
Total Database Size: 72.39MB
Database Data Size: 40.72MB
Database Index Size: 31.67MB
wpkm_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpkm_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkm_woocommerce_order_items: Data: 0.44MB + Index: 0.19MB + Engine InnoDB
wpkm_woocommerce_order_itemmeta: Data: 4.52MB + Index: 4.00MB + Engine InnoDB
wpkm_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkm_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_actionscheduler_actions: Data: 5.39MB + Index: 4.16MB + Engine InnoDB
wpkm_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_actionscheduler_logs: Data: 2.25MB + Index: 1.81MB + Engine InnoDB
wpkm_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_comments: Data: 2.52MB + Index: 1.28MB + Engine InnoDB
wpkm_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_followup_customer_carts: Data: 0.44MB + Index: 0.11MB + Engine InnoDB
wpkm_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_followup_customer_orders: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_customers: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpkm_followup_email_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkm_followup_email_order_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_email_orders: Data: 3.52MB + Index: 0.69MB + Engine InnoDB
wpkm_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpkm_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpkm_followup_order_categories: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_order_items: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpkm_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpkm_options: Data: 3.36MB + Index: 0.17MB + Engine InnoDB
wpkm_postmeta: Data: 11.52MB + Index: 13.03MB + Engine InnoDB
wpkm_posts: Data: 1.50MB + Index: 0.55MB + Engine InnoDB
wpkm_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wpkm_users: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wpkm_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpkm_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_wc_customer_lookup: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wpkm_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_wc_order_product_lookup: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
wpkm_wc_order_stats: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wpkm_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkm_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpkm_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkm_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkm_wcs_payment_retries: Data: 0.23MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

acf: 1
attachment: 13
custom_css: 1
et_pb_layout: 4
follow_up_email: 9
nav_menu_item: 3
page: 7
post: 3
product: 3
product_variation: 20
shop_order: 2000
shop_order_refund: 3
shop_subscription: 979

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Better Search Replace: by WP Engine – 1.4.2
Bootstrap one page woocommerce checkout: by mahabub hasan – 1.1.1
CSA Checkout Helper: by Matthew Swetnam on behalf of Cornerstone Advertising – 1.0.0
Easy WP SMTP: by Easy WP SMTP – 2.1.0
Flexible Checkout Fields: by WP Desk – 3.5.9
LiteSpeed Cache: by LiteSpeed Technologies – 5.4
Mailgun: by Mailgun – 1.9.4
Shortcodes Ultimate: by Vova Anokhin – 5.13.0
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.5
Woo Custom Emails Per Product: by Alex Mustin – 2.2.9
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.2
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Email Test: by RaiserWeb – 1.10
Follow-Up Emails: by WooCommerce – 4.9.51
WP Menu Cart: by WP Overnight – 2.14.0
WooCommerce Product Add-ons: by WooCommerce – 6.4.0
WooCommerce SecureSubmit Gateway: by SecureSubmit – 2.2
WooCommerce Subscriptions: by WooCommerce – 5.1.3
WooCommerce: by Automattic – 7.8.0

### Inactive Plugins (1) ###

Admin Menu Editor Pro: by Janis Elsts – 2.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #246 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #7 - /my-account/
Terms and conditions: #394 - /terms-conditions/

### Theme ###

Name: Divi
Version: 4.21.0
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://payment.lindstromair.com
Subscriptions-core Library Version: 5.7.2
Subscription Statuses: wc-active: 514
wc-pending: 39
wc-on-hold: 163
wc-cancelled: 263

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Florida

### Subscriptions by Payment Gateway ###

SecureSubmit: wc-cancelled: 262
wc-pending: 39
wc-on-hold: 163
wc-active: 514

### Payment Gateway Support ###

SecureSubmit: products
refunds
subscriptions
subscription_cancellation
subscription_reactivation
subscription_suspension
subscription_amount_changes
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_date_changes
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-16 18:59:23 +00:00
Options: ✔
Notes: 143
Onboarding: completed

### Action Scheduler ###

Complete: 672
Oldest: 2023-05-16 15:02:42 +0000
Newest: 2023-06-16 13:19:52 +0000

Failed: 9
Oldest: 2023-02-15 06:04:47 +0000
Newest: 2023-06-01 06:00:15 +0000

Pending: 517
Oldest: 2023-06-17 00:00:00 +0000
Newest: 2024-06-15 21:10:16 +0000

### Status report information ###

Generated at: 2023-06-16 13:50:05 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@mgswetnam Apologies in the delay in following up here. We were not able to reproduce this issue. Do you still see it in the latest version of WooCommerce?

**Comment by mgswetnam** [comment]
Yes, the Shipping Address is still missing on the New Subscription emails.
I'll include a screen shot of what I'm seeing. You can see in the screen
shot that the Billing Address is included, but not the Shipping Address.

Thank you for the reply.

--Matt Swetnam

**Comment by lsinger** [comment]
Hello @mgswetnam,

It seems the screenshot you mentioned wasn't attached. Are you still able to produce that? 

It also seems you have several plugins installed that might modify the emails that WooCommerce is sending. Can you confirm for us that the issue appears even when those are deactivated? 

Thanks in advance!
