### ISSUE TITLE
Adding new attribute failed popup

### ISSUE THREAD

**Issue by dande1st** [woothemes/woocommerce#38784]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since updating to the latest version of WooCommerce (7.8.0) I have found the following issue.

When you click on WooCommerce products to edit a popup appears that says - Adding new attribute failed. This only stays for 3-4 seconds then disappears.
![Screenshot](https://github.com/woocommerce/woocommerce/assets/136938740/58d46cb6-9050-46cc-bf92-2aad7deec687)

### Expected behavior

Since updating there should be no issues

### Actual behavior

But I get a popup now that lasts for 3 seconds - see screenshot
![Screenshot](https://github.com/woocommerce/woocommerce/assets/136938740/9f5fe951-4457-47a4-a0bf-068a6400879e)

### Steps to reproduce

![Screenshot](https://github.com/woocommerce/woocommerce/assets/136938740/ec512726-9ea1-44ce-acd1-95e34d3b0b0c)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.chess.co.nz
Site address (URL): https://www.chess.co.nz
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.84.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.4.24-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 76.94MB
Database Data Size: 50.48MB
Database Index Size: 26.46MB
wp_woocommerce_sessions: Data: 0.74MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 1.08MB + Index: 0.57MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 5.53MB + Index: 4.47MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_apto_sort_list: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 3.40MB + Index: 1.53MB + Engine MyISAM
wp_eshop_base_products: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_countries: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_eshop_discount_codes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_downloads: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_download_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_option_names: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_option_sets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_orders: Data: 0.22MB + Index: 0.06MB + Engine MyISAM
wp_eshop_order_items: Data: 0.18MB + Index: 0.06MB + Engine MyISAM
wp_eshop_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eshop_states: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_eshop_stock: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.25MB + Index: 0.04MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.37MB + Index: 0.39MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.17MB + Index: 0.05MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.20MB + Index: 0.09MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.67MB + Index: 0.14MB + Engine MyISAM
wp_postmeta: Data: 25.75MB + Index: 13.86MB + Engine MyISAM
wp_posts: Data: 2.88MB + Index: 0.80MB + Engine MyISAM
wp_revslider_css: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 3.13MB + Index: 2.06MB + Engine MyISAM
wp_users: Data: 0.13MB + Index: 0.14MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.04MB + Index: 0.06MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.42MB + Index: 0.02MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 0.85MB + Index: 0.19MB + Engine MyISAM
wp_wfHits: Data: 1.07MB + Index: 0.23MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 0.41MB + Index: 0.06MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.12MB + Index: 0.03MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_extra_flat_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.47MB + Index: 0.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.06MB + Engine MyISAM

### Post Type Counts ###

aoc_popup: 1
apto_sort: 44
attachment: 1423
custom_css: 4
easycontactform: 1
et_pb_layout: 6
ml-slide: 7
ml-slider: 2
nav_menu_item: 34
oembed_cache: 2
page: 16
post: 4
product: 533
product_variation: 13
revision: 27
shop_order: 7442
wa_wps: 1
woo_mb_template: 10
wpcode: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Gravity Forms: by rocketgenius – 2.4.16
Advanced Post Types Order: by Nsp Code – 4.7.7
Disable Gutenberg: by Jeff Starr – 2.9
Disable All WordPress Updates: by Oliver Schlöbe – 1.7.1
Divi Plus: by Elicus – 1.9.10
File Media Renamer: by Bradley B. Dalina – 1.3
WPCode Lite: by WPCode – 2.0.12
Really Simple SSL: by Really Simple Plugins – 7.0.3
Show User Registration Date: by Carlos Martínez Romero – 1.0.0
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.7
Checkout Field Editor for WooCommerce (Pro): by ThemeHigh – 3.5.0
Table Rate Shipping for WooCommerce: by JEM Plugins – 2.28
WooCommerce: by Automattic – 7.8.0
Yoast SEO: by Team Yoast – 20.9
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.15

### Inactive Plugins (18) ###

BAW Login/Logout menu: by Juliobox – 1.3.3
Breadcrumb NavXT: by John Havlik – 7.2.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
Easy Accept Payments for PayPal: by Tips and Tricks HQ – 4.9.10
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.9.2
Easy WP SMTP: by Easy WP SMTP – 2.1.0
Holiday Message: by Simon North – 1.1
Lazy Load for Videos: by Kevin Weber – 2.17.0
LiteSpeed Cache: by LiteSpeed Technologies – 5.4
Popup Anything - A Marketing Popup: by WP OnlineSupport
Essential Plugin – 2.6

Post Types Order: by Nsp Code – 2.0.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Revolution Slider: by ThemePunch – 4.6.9
Under Construction: by Noah Kagan – 1.21
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Product Slider: by subhansanjaya – 1.5
Wordfence Security: by Wordfence – 7.9.3
WordPress Importer: by wordpressdotorg – 0.8.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #3485 - /online-shop
Cart: #3486 - /cart
Checkout: #3487 - /checkout
My account: #3488 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: https://www.dande1st.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.21.0
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: divi-child/woocommerce/emails/admin-new-order.php
divi-child/woocommerce/emails/customer-invoice.php
divi-child/woocommerce/order/order-details-customer.php
divi-child/woocommerce/order/order-details.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-05-23 10:59:48 +12:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 528
Oldest: 2023-05-18 14:29:31 +1200
Newest: 2023-06-18 11:56:39 +1200

Failed: 4
Oldest: 2023-05-01 22:59:56 +1200
Newest: 2023-06-08 14:37:40 +1200

Pending: 3
Oldest: 2023-06-19 11:56:38 +1200
Newest: 2023-06-19 11:56:39 +1200

### Status report information ###

Generated at: 2023-06-18 12:20:13 +12:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by Patmillan** [comment]
I have de same problem!

**Comment by SirRahikkala** [comment]
I have same issue.

**Comment by mattsherman** [comment]
@dande1st @Patmillan @SirRahikkala Thanks for reporting this. Can you please check in the browser console and copy any error messages that appear there when you encounter this error?

**Comment by walkinverse** [comment]
I am having the same issue on two sites.   When I roll back to woo version Version 7.7.2  the issue goes away. So its tied to 7.8.0.  Also, I have no attributes on one of my sites.  Yet get the error with the current version saying error adding attributed popup.

**Comment by mattsherman** [comment]
I can reproduce this with Firefox.

**Comment by mattsherman** [comment]
I just noticed there is an older issue for this, #38755, so closing this one.

**Comment by Lupul** [comment]
The older related issue is at #38755

**Comment by mattsherman** [comment]
> The older related issue is at #38755

Thanks -- I mistakenly linked to this same issue in my comment above (edited)! 🥲
