### ISSUE TITLE
Erro na tela de fechamento de vendas

### ISSUE THREAD

**Issue by JoseTNeto** [woothemes/woocommerce#38782]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Na tela de Fechamento , xiste o campo onde deve ser selecionado se o cliente é pessoa fisica ou juridica, porem este campo esta pequeno a ponto de nao aparecer nem o texto dele, e nem a seta do menu dropdowm para seleção, conforme imagem
![tipo de pessoa](https://github.com/woocommerce/woocommerce/assets/71400141/c6178779-a08e-4287-9b19-fe80e963852c)
![tipo de pessoa](https://github.com/woocommerce/woocommerce/assets/71400141/4218be4b-fa2e-4deb-86b7-b0d094b06b46)

### Expected behavior

mostrar o botao de forma correta, e quando houver o plugin especifico deve se mostrar apenas os valores de cada condição variavel ao cliente, ou seja cliente pessoa fisica deve visualizar somente produtos disponiveis na variavel pessoa fisica, e cliente pessoa jurica, da mesma forma tem acesso somente a produtos com esta variavel,... alias estou a procura de um plugin com este recurso, se souberem informar agradeço.

### Actual behavior

mostrar o botao de forma correta, e quando houver o plugin especifico deve se mostrar apenas os valores de cada condição variavel ao cliente, ou seja cliente pessoa fisica deve visualizar somente produtos disponiveis na variavel pessoa fisica, e cliente pessoa juridica, da mesma forma tem acesso somente a produtos com esta variavel,... alias estou a procura de um plugin com este recurso, se souberem informar agradeço.

### Steps to reproduce

mostrar o botao de forma correta, e quando houver o plugin especifico deve se mostrar apenas os valores de cada condição variavel ao cliente, ou seja cliente pessoa fisica deve visualizar somente produtos disponiveis na variavel pessoa fisica, e cliente pessoa juridica, da mesma forma tem acesso somente a produtos com esta variavel

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://milblocos.net
Site address (URL): http://milblocos.net
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 3 GB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.19-MariaDB-cll-lve
Max Upload Size: 3 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 195.91MB
Tamanho dos dados do banco de dados: 135.71MB
Tamanho do índice do banco de dado: 60.20MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 2.36MB + Índex: 1.63MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 1.34MB + Índex: 0.80MB + mecanismo InnoDB
wp_auto_updates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ce4wp_abandoned_checkout: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ce4wp_contacts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_cmplz_cookiebanners: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cmplz_cookies: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cmplz_services: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.08MB + Índex: 0.09MB + mecanismo InnoDB
wp_duplicator_pro_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_duplicator_pro_packages: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ewwwio_images: Dados: 4.52MB + Índex: 2.94MB + mecanismo InnoDB
wp_ewwwio_queue: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_addon_feed: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_draft_submissions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_gf_entry: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_entry_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_gf_entry_notes: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_form: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gf_form_meta: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_gf_form_revisions: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_form_view: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wp_gf_rest_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_gla_budget_recommendations: Dados: 0.22MB + Índex: 0.14MB + mecanismo InnoDB
wp_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_gla_shipping_rates: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_jetpack_waf_blocklog: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_litespeed_avatar: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_litespeed_img_optm: Dados: 0.48MB + Índex: 0.28MB + mecanismo InnoDB
wp_litespeed_img_optming: Dados: 2.52MB + Índex: 2.20MB + mecanismo InnoDB
wp_litespeed_url: Dados: 0.42MB + Índex: 0.53MB + mecanismo InnoDB
wp_litespeed_url_file: Dados: 0.42MB + Índex: 1.09MB + mecanismo InnoDB
wp_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automation_runs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_automation_run_logs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_automation_triggers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_automation_versions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_migrations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_newsletter_templates: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_scheduled_tasks: Dados: 0.16MB + Índex: 0.19MB + mecanismo InnoDB
wp_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_bounces: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wp_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_subscriber_tag: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_mailpoet_tags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_micro_revisions: Dados: 6.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_campaign_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_campaign_logmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_conversions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_email_campaignmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_email_campaigns: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mo_optin_campaignmeta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mo_optin_campaigns: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_options: Dados: 19.41MB + Índex: 1.17MB + mecanismo InnoDB
wp_pmxi_files: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_hash: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_history: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_images: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_imports: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_posts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pmxi_templates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_postmeta: Dados: 58.59MB + Índex: 31.05MB + mecanismo InnoDB
wp_posts: Dados: 23.52MB + Índex: 6.70MB + mecanismo InnoDB
wp_prflxtrflds_fields_meta: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_404_logs: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_analytics_objects: Dados: 0.08MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_internal_links: Dados: 0.39MB + Índex: 0.16MB + mecanismo InnoDB
wp_rank_math_internal_meta: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_rank_math_redirections: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rank_math_redirections_cache: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rg_form: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_form_view: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_rg_incomplete_submissions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_rg_lead: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_rg_lead_detail: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_rg_lead_detail_long: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rg_lead_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_rg_lead_notes: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_taxjar_record_queue: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_termmeta: Dados: 0.13MB + Índex: 0.16MB + mecanismo InnoDB
wp_terms: Dados: 0.11MB + Índex: 0.13MB + mecanismo InnoDB
wp_term_relationships: Dados: 2.52MB + Índex: 1.52MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
wp_um_metadata: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_update_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_usermeta: Dados: 0.11MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_user_registration_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log_product: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_purchase_log_product_rule: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vtprd_transient_cart_data: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.11MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 3.52MB + Índex: 2.52MB + mecanismo InnoDB
wp_wc_product_download_directories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 1.52MB + Índex: 2.75MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_webarx_event_log: Dados: 0.19MB + Índex: 0.00MB + mecanismo InnoDB
wp_webarx_firewall_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_webarx_logic: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_debug_events: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_yith_wcwl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yith_wcwl_lists: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbscrm_api_keys: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_admlog: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_aka: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_zbs_companies: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_contacts: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_customfields: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_zbs_dbmigration_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_dbmigration_posts: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_events: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_zbs_event_reminders: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_externalsources: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_zbs_forms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_invoices: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_zbs_lineitems: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_logs: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_meta: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_zbs_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_object_links: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_quotes: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_zbs_quotes_templates: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_security_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_segments: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_segments_conditions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_settings: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_sys_cronmanagerlogs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_sys_email: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_sys_email_hist: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_zbs_tags: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_tags_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_zbs_tax_table: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_temphash: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_tracking: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_zbs_transactions: Dados: 0.02MB + Índex: 0.14MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 4798
custom_css: 3
customize_changeset: 8
foobar_notification: 1
foogallery: 119
mailpoet_page: 1
nav_menu_item: 70
oembed_cache: 4
page: 63
post: 2
product: 1143
product_variation: 12089
revision: 1673
shop_order: 75
um_directory: 2
um_form: 3
user_registration: 2
wp_block: 2
wp_global_styles: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Mensagens de erro não devem ser mostradas para visitantes.

### Active Plugins (29) ###

Gravity Forms: por Gravity Forms – 2.5.16
Editor clássico: por Colaboradores do WordPress – 1.6.3
Widgets Clássicos: por Colaboradores do WordPress – 0.3
Companion Auto Update: por Papin Schipper – 3.8.7.1
EWWW Image Optimizer: por Exactly WWW – 7.0.2
Facebook para WooCommerce: por Facebook – 3.0.25
FooGallery (Premium): por FooPlugins – 2.1.28
Site Kit by Google: por Google – 1.102.0
LiteSpeed Cache: por LiteSpeed Technologies – 5.4
Loco Translate: por Tim Whitlock – 2.6.4
Mailchimp para Woocommerce: por Mailchimp – 2.8.3
Microthemer: por Themeover – 7.2.2.6
Fonts Plugin | Google Fonts Typography: por Fonts Plugin – 3.4.1
Really Simple SSL: por Really Simple Plugins – 7.0.5
Side Cart WooCommerce: por XootiX – 2.2
TaxJar - Sales Tax Automation for WooCommerce: por TaxJar – 4.1.5
Ultimate Member: por Ultimate Member – 2.6.3
Ultimate Social Media PLUS: por social share pro – 3.5.7
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.9.0
Brazilian Market on WooCommerce: por Claudio Sanches – 3.8.2
Mercado Pago payments for WooCommerce: por Mercado Pago – 6.9.1
WooCommerce Shipping & Tax: por WooCommerce – 2.2.5
WooCommerce: por Automattic – 7.8.0
Importador do WordPress: por wordpressdotorg – 0.8.1
WP Mail SMTP: por WP Mail SMTP – 3.8.0
Multi-Step Checkout for WooCommerce: por SilkyPress – 2.24.1
Social Chat: por QuadLayers – 7.1.2
Importador do conversor de categorias em tags: por wordpressdotorg – 0.6.1
YITH WooCommerce Wishlist: por YITH – 3.22.0

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Must Use Plugins (1) ###

burst_rest_api_optimizer.php: por  –

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base da loja: #23 - /loja/
Carrinho: #24 - /carrinho/
Finalização de compra: #25 - /finalizar-compra/
Minha conta: ❌ A visibilidade da página deve ser pública
Termos e condições: #23 - /loja/

### Theme ###

Name: Astra
Version: 4.1.5
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-17 17:44:55 -03:00
Options: ✔
Notes: 143
Onboarding: completed

### Action Scheduler ###

Canceled: 14
Oldest: 2023-05-17 17:51:05 -0300
Newest: 2023-06-17 09:56:08 -0300

Complete: 4.621
Oldest: 2023-05-17 12:40:01 -0300
Newest: 2023-06-17 12:26:06 -0300

Failed: 769
Oldest: 2021-04-15 12:44:28 -0300
Newest: 2023-06-01 08:15:31 -0300

Pending: 4
Oldest: 2023-06-17 12:40:47 -0300
Newest: 2023-06-20 11:47:55 -0300

### Status report information ###

Generated at: 2023-06-17 12:30:18 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
Hi @JoseTNeto ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The custom checkout field does not come as part of core WooCommerce. The issue you are having seems to be caused by the 3rd party plugin.

Please contact the author of the plugin directly for further help.
