### ISSUE TITLE
Uncorrect menu cart view

### ISSUE THREAD

**Issue by francescocimo** [woothemes/woocommerce#38783]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After adding a product to your cart, it appears correctly in the pop-up menu when you click on the cart icon. But if I visit any page of the site the pop-up menu does not show the products and the buttons view the cart and go to payment.

### Expected behavior

Clicking menu cart button i can see product added every time, also after navigate other pages

### Actual behavior

on clicking menu cart button after visit any page i would see product added

### Steps to reproduce

1. click on menu cart icon
2. visit any pages

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.licoagricola.it
Site address (URL): https://www.licoagricola.it
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.27
PHP Post Max Size: 128 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.76.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.33-36-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Dimensione totale database: 24.14MB
Dimensione dati database: 21.54MB
Dimensione indice database: 2.60MB
wp_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 0.17MB + indice: 0.14MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 0.09MB + indice: 0.06MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_e_submissions: Dati: 0.02MB + indice: 0.27MB + motore InnoDB
wp_e_submissions_actions_log: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_e_submissions_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_gla_attribute_mapping_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_gla_budget_recommendations: Dati: 0.22MB + indice: 0.14MB + motore InnoDB
wp_gla_merchant_issues: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_gla_shipping_rates: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_gla_shipping_times: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_options: Dati: 4.20MB + indice: 0.09MB + motore InnoDB
wp_postmeta: Dati: 9.34MB + indice: 0.38MB + motore InnoDB
wp_posts: Dati: 6.47MB + indice: 0.13MB + motore InnoDB
wp_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

acf-field: 10
acf-field-group: 1
attachment: 99
custom_css: 1
customize_changeset: 9
elementor_library: 12
elementor_snippet: 4
nav_menu_item: 4
page: 20
post: 4
product: 4
revision: 472
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Advanced Custom Fields PRO: by WP Engine – 6.1.6
Elementor Pro: by MrCode.ir – 3.13.2
Elementor: by Elementor.com – 3.13.4
Flexible Shipping: by Octolize – 4.21.3
Jetpack: by Automattic – 12.2.1
Maintenance: by WebFactory Ltd – 4.07
OSM Map Widget for Elementor: by Plugin Contributors – 1.1
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce: by Automattic – 7.8.0

### Inactive Plugins (1) ###

Hello Dolly: by Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #456 - /shop/
Carrello: ❌ La pagina non contiene lo shortcode [woocommerce_cart] o il blocco woocommerce/cart.
Pagamento: ❌ La pagina non contiene lo shortcode [woocommerce_checkout] o il blocco woocommerce/checkout.
Il mio account: #176 - /my-account/
Termini e condizioni: #672 - /condizioni-generali-di-vendita/

### Theme ###

Name: Hello Elementor Child
Version: 1.0.0
Author URL: https://childthemewp.com
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.7.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-18 16:36:14 +02:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Completato: 223
Oldest: 2023-06-05 18:37:26 +0200
Newest: 2023-06-17 20:47:26 +0200

Operazione non riuscita: 108
Oldest: 2023-06-05 18:46:25 +0200
Newest: 2023-06-17 21:53:52 +0200

In attesa: 4
Oldest: 2023-06-17 22:53:52 +0200
Newest: 2023-06-18 20:47:26 +0200

### Status report information ###

Generated at: 2023-06-17 21:54:31 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Visiting your site, I'm not sure I can see the problem. Is this the feature (see screenshot) you are referring to?

<div align="center"><img width="400" alt="Screenshot 2023-07-06 at 11 59 14" src="https://github.com/woocommerce/woocommerce/assets/3594411/97dcb3ba-dfc8-4538-b749-6167e8abf2b1"></div>

If it is, I'd also note that it is generated by Elementor and not by WooCommerce—so it is probably worth speaking with their team if you need help. Alternatively, if you are referring to something else, please let us know.

Thanks!

**Comment by rrennick** [comment]
Closing this due to lack of feedback.
