### ISSUE TITLE
Wrong Tax Calculation for Fees after "Recalculate button" pressed

### ISSUE THREAD

**Issue by danielbarenkamp** [woothemes/woocommerce#38798]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Wrong Tax Calculation for Fees after "Recalculate button" pressed.

Before the tax for fee "Pfand" -> 0,19€ (see bottom right)
<img width="2189" alt="After" src="https://github.com/woocommerce/woocommerce/assets/3169388/cd8b1c01-7a93-4b32-ac40-39c6070bd455">

After pressing recaulcuate: 0,77€
<img width="2183" alt="Before" src="https://github.com/woocommerce/woocommerce/assets/3169388/727171ea-c76b-4a8b-a8d6-694cbc9b2251">

No product data has been changed. Fees are added via:

$woocommerce->cart->add_fee('Pfand', 4.03, true, $depositData['tax_class'] );

Tax class before: 19%
Tax class after: 7%

The tax class is changing. Why?

### Expected behavior

Taxes for fees stay the same

### Actual behavior

Taxes change.

### Steps to reproduce

Add product to cart, purchase, click on recalculate

### WordPress Environment

latest

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by danielbarenkamp** [comment]
Do you have any update here?

**Comment by Lieferkoop** [comment]
Hi
René Organizer from Lieferkoop.org writes here.
Daniel is working on the topic for us.
Since nothing is moving on this topic, I am now writing to you as an organizer.
When can I expect the bugs to be fixed?
It's urgent.
Thanks

**Comment by rrennick** [comment]
@danielbarenkamp @Lieferkoop Apologies for the delay in responding. The information you have provided does not have enough info to reproduce this issue. Could you please provide the details needed to reproduce this issue in a development/test install?

**Comment by danielbarenkamp** [comment]
@rrennick can you let me know what exact test data you need?

**Comment by rrennick** [comment]
> can you let me know what exact test data you need?

@danielbarenkamp If I start with a blank install, what settings, products, taxes, etc. need to be created. Secondly, a complete code snippet to implement the code in the description:

```
$woocommerce->cart->add_fee('Pfand', 4.03, true, $depositData['tax_class'] );
```

**Comment by danielbarenkamp** [comment]
@rrennick Can I send you my full plugin via Email? Then I can better explain you the issue. I can also give you admin & FTP access to my staging site if you prefer that.

**Comment by rrennick** [comment]
> Can I send you my full plugin via Email?

@danielbarenkamp Thanks for the follow up. Does this issue occur without your plugin active? 

Github is not for support and we don't investigate issues in other plugins and don't troubleshoot sites. If this is a plugin that was written by someone else, could you contact them to provide the info I asked for?

**Comment by danielbarenkamp** [comment]
@rrennick well I am the author. But let me do some tests in my staging first again and I will come back to you.

**Comment by danielbarenkamp** [comment]
Case closed. It was an issue with German market plugin and their support fixed it.
