### ISSUE TITLE
[Enhancement]: Consider moving core profiler consent checkbox above "Set up my store" button

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#38792]
### Describe the solution you'd like

In a recent internal demo of the new core profiler, it was observed the consent checkbox is distant from the "Set up my store" button on large screens because it anchors to the bottom of the window. 

It was suggested in the demo to bring the consent box above, or closer to, the "Set up my store" button.

### Additional context

Core Profiler at 3072 × 1920 screen resolution:

![image](https://github.com/woocommerce/woocommerce/assets/9312929/58035c82-c432-4cf8-b64c-8e952ec89f6a)

**Comment by rjchow** [comment]
I think this requires @verofasulo 's input

**Comment by verofasulo** [comment]
> It was suggested in the demo to bring the consent box above, or closer to, the "Set up my store" button.

This is something we discussed internally before the launch as well, and we decided to move it to the bottom (but always above the fold) to avoid creating a wall of text as well as putting too much focus on the data opt-in. Please let's keep it as is 😊 It's performing well.

**Comment by chihsuan** [comment]
> Please let's keep it as is 😊 It's performing well.

Closing this.
