### ISSUE TITLE
Can't create attributes message in WooCommerce screens

### ISSUE THREAD

**Issue by wireinet** [woothemes/woocommerce#38800]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

woocommerce 7.8.0 (from wp repositories) have error  (7.7 – not (i tested)) – in all screens from woocommerce i have the alert message (can't create attributes)
[https://disk.yandex.ru/i/K_PgqafxacQVAw](url) and after deactivate and again activate i have some errors in admin:
[https://disk.yandex.ru/i/RO-1Hdlom_O7Lg](url) 
errors appear: after open all products in admin, after go to settings WooCommerce, after click on stars (featured product), after publish / update product

p.S
i tryed to change themes,
i tryed to deactivate all plugins,
i recreated my project with new fresh database and install only woocommerce 7.8.0  from repositoriesand again i have this error!

### Expected behavior

The message should not appear

### Actual behavior

alert error

### Steps to reproduce

Open any WooCommerce screen

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://alliance-greenlife-dev.ru
Site address (URL): http://alliance-greenlife-dev.ru
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 ГБ
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.22
PHP Post Max Size: 50 МБ
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.39-log
Max Upload Size: 50 МБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Общий размер базы данных: 6.23MB
Размер данных в базе данных: 4.43MB
Размер индекса базы данных: 1.80MB
wp_woocommerce_sessions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_order_items: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_order_itemmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_actions: Данные: 0.02MB + Индекс: 0.11MB + Движок InnoDB
wp_actionscheduler_claims: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_groups: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_logs: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_berocket_termmeta: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_braapf_product_stock_status_parent: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_braapf_product_variation_attributes: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_braapf_term_taxonomy_hierarchical: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_braapf_variable_attributes: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_commentmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_comments: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_fbv: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_fbv_attachment_folder: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_options: Данные: 3.03MB + Индекс: 0.06MB + Движок InnoDB
wp_podsrel: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_postmeta: Данные: 0.13MB + Индекс: 0.03MB + Движок InnoDB
wp_posts: Данные: 0.08MB + Индекс: 0.06MB + Движок InnoDB
wp_realmedialibrary: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_realmedialibrary_meta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_realmedialibrary_posts: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_realmedialibrary_tmp: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_termmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_terms: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_term_relationships: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_term_taxonomy: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_usermeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_users: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_admin_notes: Данные: 0.06MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_admin_note_actions: Данные: 0.05MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_category_lookup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_customer_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_coupon_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_product_lookup: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wc_order_stats: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_order_tax_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_product_attributes_lookup: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_product_download_directories: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_product_meta_lookup: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_wc_rate_limits: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_reserved_stock: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wpmfs_queue: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB

### Post Type Counts ###

attachment: 39
nav_menu_item: 16
page: 12
post: 2
product: 8

### Security ###

Secure connection (HTTPS): ❌
					В вашем магазине не используется HTTPS. Подробнее об HTTPS и SSL-сертификатах.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Webcraftic Clearfy - плагин оптимизации для Wordpress: от Creative Motion  – 2.1.9
WooCommerce: от Automattic – 7.8.0

### Inactive Plugins (10) ###

Advanced AJAX Product Filters for WooCommerce: от BeRocket – 1.6.4.2
Advanced Database Cleaner: от Younes JFR. – 3.1.2
Aquila Admin Theme: от Guy Primavera – 3.1.1
Easy Auto SKU Generator for WooCommerce: от Dan Zakirov – 1.1.2
Kadence Blocks – Gutenberg Blocks for Page Builder Features: от Kadence WP – 3.0.41
Pods - Custom Content Types and Fields: от Pods Framework Team – 2.9.16
Post List With Featured Image: от Dharmesh Patel – 1.2
Real Media Library (Free): от devowl.io – 4.20.4
Safe SVG: от 10up – 2.1.1
Show Current Template: от JOTAKI Taisuke – 0.4.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (₽)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Ссылка магазина: #6 - /catalog/
Корзина: #7 - /cart/
Оформление заказа: #8 - /checkout/
Мой аккаунт: #9 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Alliance Greenlife
Version: 1.0
Author URL: 
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: alliance-greenlife/woocommerce/archive-product.php
alliance-greenlife/woocommerce/content-product.php
Есть обновления для alliance-greenlife/product-searchform.php версии -. Версия ядра — 7.0.1

Outdated Templates: ❌
					
					
						Узнайте
как обновить

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-19 17:08:03 +03:00
Options: ✔
Notes: 72
Onboarding: -

### Action Scheduler ###

Выполнено: 26
Oldest: 2023-05-30 17:09:15 +0000
Newest: 2023-06-19 13:10:13 +0000

Неудачно: 1
Oldest: 2023-06-18 16:21:07 +0000
Newest: 2023-06-18 16:21:07 +0000

В ожидании: 1
Oldest: 2023-06-20 09:48:03 +0000
Newest: 2023-06-20 09:48:03 +0000

### Status report information ###

Generated at: 2023-06-19 17:18:56 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
@wireinet Thanks for reporting this issue. I believe this to be the same issue as #38784, so I'm going to close this issue.
