### ISSUE TITLE
[AI Modal] Basic modal template and navigation

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#38810]
As a first step, adding a basic modal with support for dragging, basic navigation, and about your product text box.

![Image](https://github.com/woocommerce/woocommerce/assets/444632/345f408f-ba8d-4c32-a752-eda35bfd8dc7)

Acceptance Criteria:
- [ ] Button triggers modal
- [ ] Modal is draggable
- [ ] "About your product" text box
- [ ] Write button that triggers streaming response

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
