### ISSUE TITLE
Analytics miscalculates

### ISSUE THREAD

**Issue by memolivip** [woothemes/woocommerce#38824]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm having the same problem on several sites. It makes it look like they have orders without Woocommerce analytics tool. It shows that 8 orders were placed in 1 day, but when I checked, it shows 1 order. I can't quite get it. Maybe there are orders made for testing purposes. Even so, it shouldn't show deleted orders in analytics either.

### Expected behavior

Deleted or canceled orders should not appear in the analysis.

### Actual behavior

I guess it also includes orders that are moved to the trash and deleted permanently.

### Steps to reproduce

![2023-06-20_162021](https://github.com/woocommerce/woocommerce/assets/137183527/2e067c8b-35fc-4c0d-9551-0ea2082d5e64)
![2023-06-20_162103](https://github.com/woocommerce/woocommerce/assets/137183527/43e1b1ec-24aa-4f3b-9374-780a6535e01f)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://enuygunlisans.com.tr
Site address (URL): https://enuygunlisans.com.tr
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.4
PHP Version: 8.2.1
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.11-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wpa4_
Total Database Size: 13.24MB
Database Data Size: 11.03MB
Database Index Size: 2.21MB
wpa4_woocommerce_sessions: Data: 1.78MB + Index: 0.06MB + Engine MyISAM
wpa4_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpa4_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_actionscheduler_actions: Data: 0.11MB + Index: 0.04MB + Engine MyISAM
wpa4_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_actionscheduler_logs: Data: 0.19MB + Index: 0.13MB + Engine MyISAM
wpa4_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_atum_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_atum_product_data: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_cartbounty_pro: Data: 0.50MB + Index: 0.02MB + Engine MyISAM
wpa4_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_comments: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wpa4_energyplus_daily: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpa4_energyplus_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_energyplus_requests: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpa4_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_e_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_e_submissions_actions_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_e_submissions_values: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_feedmanager_channel: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_feedmanager_country: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpa4_feedmanager_feed_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_feedmanager_field_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_feedmanager_product_feed: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_feedmanager_product_feedmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_feedmanager_source: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_fsmpt_email_logs: Data: 0.33MB + Index: 0.00MB + Engine MyISAM
wpa4_imagify_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_imagify_folders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_litespeed_avatar: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpa4_litespeed_img_optm: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wpa4_litespeed_img_optming: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_litespeed_url: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wpa4_litespeed_url_file: Data: 0.05MB + Index: 0.09MB + Engine MyISAM
wpa4_mobileassistant_failed_login: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_mobileassistant_push_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_mobileassistant_session_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_mobileassistant_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_options: Data: 4.04MB + Index: 0.11MB + Engine MyISAM
wpa4_postmeta: Data: 2.96MB + Index: 0.93MB + Engine MyISAM
wpa4_posts: Data: 0.60MB + Index: 0.09MB + Engine MyISAM
wpa4_rank_math_internal_links: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpa4_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpa4_terms: Data: 0.01MB + Index: 0.04MB + Engine MyISAM
wpa4_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpa4_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpa4_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_usermeta: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wpa4_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpa4_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_product_meta_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpa4_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpa4_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpa4_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wpa4_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpa4_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

acf-field: 77
acf-field-group: 9
attachment: 278
br_product_tab: 1
br_tabs_location: 1
custom_css: 2
elementor_library: 10
mc4wp-form: 1
nav_menu_item: 161
page: 14
post: 2
product: 92
product_variation: 6
product-feed: 1
revision: 18
shop_order: 34
shopengine-template: 1
woo_product_tab: 1
yith_wcan_preset: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.29.1
Bdevs Element: by Nasir Uddin Mandal – 1.1.5
Bdevs Toolkit: by BDevs – 1.0.6
Classic Editor: by WordPress Contributors – 1.6.3
Cookie Bar: by Brontobytes – 2.0
Cost of Goods for WooCommerce: by WPFactory – 3.0.1
Easy Auto SKU Generator for WooCommerce: by Dan Zakirov – 1.1.2
Elementor Pro: by Elementor.com – 3.9.2
Elementor: by Elementor.com – 3.13.4
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.4
Fluid Checkout for WooCommerce - Lite: by Fluid Checkout – 2.5.1
GA Google Analytics: by Jeff Starr – 20230306
Kirki Customizer Framework: by Themeum – 4.2.0
Loco Translate: by Tim Whitlock – 2.6.4
Mobile Assistant Connector: by eMagicOne – 2.2.4
One Click Close Comments: by Scott Reilly – 2.7.1
Paymax Ortak Ödeme Sistemleri: by Paymax.com.tr – 1.5
Product Tabs Manager for WooCommerce: by BeRocket – 1.1.5.8
Really Simple SSL: by Really Simple Plugins – 7.0.5
Repeat Order for Woocommerce: by polyres – 1.2.0
Rank Math SEO: by Rank Math – 1.0.117.1
Tawk.to Live Chat: by Tawkto – 0.8.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
CartBounty Pro - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 9.7.2
WooCommerce: by Automattic – 7.8.0
WP Product Feed Manager: by Michel Jongbloed – 1.49.1
WPForms Lite: by WPForms – 1.8.2.1
YellowPencil: by WaspThemes – 7.6.0

### Inactive Plugins (6) ###

Cancel order request for WooCommerce: by PI Websolution – 1.3.3.9
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.8.2

Product Feed Manager for WooCommerce: by RexTheme – 7.3.1
Query Monitor: by John Blackbourn – 3.12.3
Sticky Product Add to Cart and Checkout Bar for WooCommerce: by OneTeamSoftware – 1.0.44
WP 2FA - Two-factor authentication for WordPress: by WP White Security – 2.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #13 - /magaza-2/
Cart: #14 - /sepet/
Checkout: #15 - /odeme/
My account: #16 - /hesabim/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Markite Child
Version: 1.0.0
Author URL: https://themepure.net/wp/markite/
Child Theme: ✔
Parent Theme Name: Markite
Parent Theme Version: 1.2.6
Parent Theme Author URL: https://themeforest.net/user/theme_pure
WooCommerce Support: ✔

### Templates ###

Overrides: markite/woocommerce/archive-product.php
markite/woocommerce/cart/cart.php
markite/woocommerce/cart/mini-cart.php version 6.2.0 is out of date. The core version is 7.8.0
markite/woocommerce/cart/proceed-to-checkout-button.php
markite/woocommerce/checkout/form-checkout.php
markite/woocommerce/content-product.php
markite/woocommerce/content-single-product.php
markite/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.8.0
markite/woocommerce/global/wrapper-end.php
markite/woocommerce/global/wrapper-start.php
markite/woocommerce/loop/add-to-cart.php
markite/woocommerce/loop/loop-end.php
markite/woocommerce/loop/loop-start.php
markite/woocommerce/loop/orderby.php
markite/woocommerce/loop/pagination.php
markite/woocommerce/loop/price.php
markite/woocommerce/loop/rating.php
markite/woocommerce/loop/result-count.php
markite/woocommerce/single-product/add-to-cart/external.php
markite/woocommerce/single-product/add-to-cart/grouped.php
markite/woocommerce/single-product/add-to-cart/simple.php
markite/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
markite/woocommerce/single-product/price.php
markite/woocommerce/single-product/product-image.php version 4.5.1 is out of date. The core version is 7.8.0
markite/woocommerce/single-product/product-thumbnails.php
markite/woocommerce/single-product/related.php
markite/woocommerce/single-product/review-meta.php
markite/woocommerce/single-product/review-rating.php
markite/woocommerce/single-product/review.php
markite/woocommerce/single-product/tabs/additional-information.php
markite/woocommerce/single-product/tabs/description.php
markite/woocommerce/single-product/tabs/tabs.php
markite/woocommerce/single-product/title.php
markite/woocommerce/single-product-reviews.php
markite/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-21 08:26:51 +03:00
Options: ✔
Notes: 93
Onboarding: completed

### Action Scheduler ###

Complete: 219
Oldest: 2023-05-21 02:14:54 +0000
Newest: 2023-06-20 13:22:23 +0000

Failed: 77
Oldest: 2022-12-27 22:39:27 +0000
Newest: 2023-06-01 15:51:46 +0000

Pending: 7
Oldest: 2023-06-20 23:38:55 +0000
Newest: 2023-06-21 18:45:02 +0000

### Status report information ###

Generated at: 2023-06-20 16:23:36 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by memolivip** [comment]
I forgot to write. While the first picture shows 6 orders on May 13, there is actually only 1 order. No order was thrown away.

**Comment by Babylon1999** [comment]
zd-6398765 might be affected

**Comment by anastas10s-afk** [comment]
6534822-zen perhaps
