### ISSUE TITLE
User is redirected back to the beginning of the Core Profiler flow after clicking "Skip the guide" 

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#38843]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In Core Profiler internal call for testing

> If I change the store name while in the flow. I will be redirected back to the beginning in the end. [Please check this GIF](https://github.com/woocommerce/woocommerce/assets/4344253/334e5580-9858-4172-a444-c55e08f5e68e). - pdibGW-26P-p2#comment-1517

> I am seeing an issue where I have to Skip and select country twice before being able to return to /wp-admin. JN Site - pdibGW-26P-p2#comment-1532

### Expected behavior

Should redirect to home screen

### Actual behavior

Redirected back to "Welcome to Woo" screen

### Steps to reproduce

1. Go to Core Profiler flow
2. Change store name in `Tell us a bit about your store` step
3. Click on "Continue" button
4. Click on `Skip this step` button
5. Observe that you're redirected to  "Welcome to Woo" screen

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
Note: The root cause of the issue is that the Homescreen component doesn't get the updated profile values from the core profile since it [fetches](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/homescreen/index.tsx#L46) the profile values from the admin settings
