### ISSUE TITLE
Variations - performance analysis

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#38845]
**Description:** in the new experience, we aim to default the attributes created for variations as global (see #36286). Eventually, this will negatively impact the performance after a certain number of attributes. The team should make an analysis to understand at what point we can start having performance issues. This data will influence our decision to use global as the default option.

**Comment by louwie17** [comment]
Closing in favour of: https://github.com/woocommerce/mothra-private/issues/84
