### ISSUE TITLE
Unable to close the Core Profiler dropdowns by clicking the dropdown

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#38842]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

pdibGW-26P-p2#comment-1512

> On mobile only, when [I try to close the dropdown by clicking the dropdown, I don’t see it closed](https://github.com/woocommerce/woocommerce/assets/4344253/6e22d275-2f6a-457b-ac34-c54ba04981c3) Nothing happens. The only way to close it is by clicking somewhere outside.

### Expected behavior

Dropdown can be closed by clicking the dropdown

### Actual behavior

Dropdown is not closed

### Steps to reproduce

1. Turn on the mobile view
2. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-info
3. Click on `WHICH INDUSTRY IS YOUR BUSINESS IN?` dropdown
4. Click on the dropdown (down arrow icon)
5. Observe that the dropdown is still opened.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
While I think this is a good addition, I don't think we have to work on it now. This is how all the other SelectControl components have been behaving in WooCommerce. We should be careful about updating the behavior.

**Comment by chihsuan** [comment]
> While I think this is a good addition, I don't think we have to work on it now. This is how all the other SelectControl components have been behaving in WooCommerce. We should be careful about updating the behavior.

Agreed that we don't have to work on it now! 

I fixed a similar issue on NUX. I think we can apply the same fix.

- https://github.com/Automattic/woocommerce.com/pull/15579

**Comment by moon0326** [comment]
@chihsuan I wasn't aware of the fix. If we can apply the same fix, that would be cool!
