### ISSUE TITLE
E2E: Fix skipped test: can email invoice/order details to customer

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#38856]
The e2e test `can email invoice/order details to customer` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/merchant/order-emails.spec.js has been skipped

This issue is track fixing and re-enabling this test.

**Comment by rodelgc** [comment]
Closing this because https://github.com/woocommerce/woocommerce/pull/38862 has already been merged.
A separate PR will be submitted to update the locators in the `order-emails` spec and update WP Mail Logging to the latest version.
