### ISSUE TITLE
RIN (Remote Inbox Notification) duplicate buttons when navigating between notices

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#38850]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When navigating between RINs the number of CTA buttons increases. Refreshing the page fixes the issue. 

### Expected behavior

The button's number on a RIN should not change when I navigate between them.

### Actual behavior

It seems that the number of buttons is related to the number of times the next arrow was clicked.

### Steps to reproduce

- On the `wp-admin/admin.php?page=wc-admin` page I see 2 RINs prompting me to update two plugins. 
- 1st RIN is showing the correct number of buttons
<img width="991" alt="Screenshot 2023-06-21 at 17 52 21" src="https://github.com/woocommerce/woocommerce/assets/1628454/51af8a1b-34d6-4262-a902-c11d4379324b">

- When I navigate to the 2nd RIN it has a duplicated CTA button

- When I return to the 1st RIN it also has a duplicated CTA button
<img width="999" alt="Screenshot 2023-06-21 at 17 49 12" src="https://github.com/woocommerce/woocommerce/assets/1628454/978331b4-3b17-484d-9cec-fab19ff31bc7">

- When I go back to the 2nd RIN it has 3 CTA buttons
<img width="738" alt="Screenshot 2023-06-21 at 18 08 02" src="https://github.com/woocommerce/woocommerce/assets/1628454/8ecb99b2-9151-4b69-8010-8c86fcdb9864">
- Refreshing the page fixes the issue.

### WordPress Environment

Tested on my local env with WordPress 2.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Closing this. I confirmed the issue has been fixed in the trunk.
