### ISSUE TITLE
Allow the user to delete the description

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#38853]
**Description:** currently, we don't offer a way to delete the description. The description tab remains visible on the product page even after deleting all the content

**Steps to reproduce:**
1. Open the new product creation experience
2. Fill the title
3. Add description content
4. Save the product and confirm that the description tab is visible on the product page
5. Delete the description content
6. Save the product and check that the description tab is visible on the product page without content

The tab should be removed if the description content is blank.

**Comment by Abdalsalaam** [comment]
@pmcpinto I would like to work on this issue, but I couldn't reproduce it : ( Storefront theme )

1.
<img width="722" alt="image" src="https://github.com/woocommerce/woocommerce/assets/19236737/ea2e6973-d689-41a8-b5c3-75dad7a3311a">

2. After removing the description, its hidden : 
<img width="776" alt="image" src="https://github.com/woocommerce/woocommerce/assets/19236737/bed8b834-aba2-4c85-ba8f-623fe4cc9a34">

**Comment by pmcpinto** [comment]
Hey Abdalsalaam, thanks for testing this. It refers to the new experience we're building.
