### ISSUE TITLE
[ Product Block Editor ] Create Variation options block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38882]
**Description:**

This issue is part of https://github.com/woocommerce/woocommerce/issues/36286 epic.

If an existing product has at least 1 local or global attribute with "Used for variations" enabled (this logic will be handled by a parent block, but we can display an empty state), display the Options section with a list including the available attributes + values. This section will behave exactly as the Attributes section (drag and drop is not part of this issue).
We should be able to re-use the existing `Options` component: https://github.com/woocommerce/woocommerce/blob/532f3ca3f8e98a9f5c5f8fd9ee85ff986fe3abb2/plugins/woocommerce-admin/client/products/fields/options/options.tsx#L41-L42
It will just have to be moved to the product editor package.

**Note**
I suggested creating a new block versus modifying the attributes block to support this view also as their do appear to be some minor design differences like the **Add new** button moving to the right of the title.
cc: @jarekmorawski incase we want to consolidate this, but this can always be something done in the future also.

The **Add New** button location will be tackled in a separate issue, for now we can render it in the same way as the attributes field below the title.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1641_226803

<img width="542" alt="Screenshot 2023-06-22 at 11 22 57 AM" src="https://github.com/woocommerce/woocommerce/assets/2240960/4ca27c19-6dce-4605-b36e-8e1860a807fb">

**Acceptance criteria**

- [ ] Have the variation options block rendered within the **Variations** tab (see https://github.com/woocommerce/woocommerce/issues/38880 )
- [ ] Render any local or global attributes with "Used for variations" enabled in the same way the attributes field looks (drag and drop is not part of this)

**Comment by jarekmorawski** [comment]
Thanks, @louwie17. It makes sense to make variation options a separate block. They may share the design DNA, but in the future, they may grow in different directions. As for the layout, we will move the buttons to the right side of the title across the whole form. It's okay to leave it out for now and use the current layout in the form. Unless you think we can update this in other sections, too?

**Comment by louwie17** [comment]
> Unless you think we can update this in other sections, too?

We will move the button location support to a separate issue, where we can change it for all sections if needed.
