### ISSUE TITLE
[Product Block Editor] Add slot fill support to section header

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38888]
**Issue Description:**

In the new design we will be displaying the **Add new** type buttons to the right of the section title. This is currently not possible and would en-force each block to move the title to the unique block.
To prevent this we could allow sections to have a slot fill location that would allow us to add action buttons.

Some questions around this:
- Is there a way to limit the slot fills to only be used by inner blocks?

**Design**

<img width="403" alt="Screenshot 2023-06-22 at 3 27 20 PM" src="https://github.com/woocommerce/woocommerce/assets/2240960/53bcb276-9e9d-4fdf-8b53-a250506bb94b">

AkVNGImLgSqCObTQ3idVn7-fi-1641_226803 ( similar in variations options list )

**Acceptance criteria**

- [ ] Allow nested inner blocks to slot fill buttons within the section header.

**Comment by mattsherman** [comment]
This has beeb implemented.
