### ISSUE TITLE
Only run cherry-pick workflow on PRs targeting trunk.

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#38896]
### Description
The cherry-pick workflow runs whenever a milestone is added to a PR or if a PR that already had a milestone is merged, whenever the selected milestone isn't the ongoing release. This happens regardless of the base branch, which can cause issues when a PR is merged that targets another branch, such as happened with p1687463971495799-slack-C01DT6U03HC.

### Acceptance criteria

* If a PR is merged with a milestone (or a milestone is added to a PR after it's merged) that targets a branch other than trunk, we shouldn't run the cherry-pick workflow.

**Comment by nigeljamesstevenson** [comment]
https://github.com/woocommerce/woocommerce/pull/39867/files might be useful as a reference
