### ISSUE TITLE
Refactor logic when adding new attribute on product page load

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38917]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There has been a couple back to back issues in relation to some code that auto adds an attribute to new products. See [this last issue](https://github.com/woocommerce/woocommerce/issues/38755) and [the fix](https://github.com/woocommerce/woocommerce/pull/38815).
One problem is that if the attribute creation request fails for any reason we get a `alert` that the attribute failed to create, this can be confusing for the user if they just loaded the product add new page. We would only want to limit this to when a user manually adds an attribute.

The main goal of the issue is to look at the code, see if things could be simplified, in order to prevent more edge cases for bugs.

**Comment by nathanss** [comment]
We discussed and decided not to move forward with this for now, since the related code was touched recently and the alert issue shouldn't happen anymore in totally unrelated scenarios.
