### ISSUE TITLE
Add a discovery link to the Woo AI Settings screen

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#38915]
Prerequisite: https://github.com/woocommerce/woocommerce/issues/38746
Once the Woo AI Settings screen is merged and usable, let's create a way to discover that settings screen beyond just finding it within the WooCommerce Settings area.

One idea is to add a new item to the list of rotating messages that show up when generating a product title:

![Image](https://user-images.githubusercontent.com/6723003/248238028-5597c076-f3a1-4462-94a3-1619ca8a6da5.png)

It could say something like, `Select a store-wide tone and style to match your brand` with a link to the settings page.

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
