### ISSUE TITLE
Create a reusable screen loading screen component

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#38935]
## Issue Description:

Create a reusable loading screen component that can be used across different projects and even repositories.

<img src="https://user-images.githubusercontent.com/3747241/246136804-bd0c3de9-b3f9-42c2-86e8-b04f4e72ab74.png" />

## Acceptance criteria

1. Implement a loading screen component in `@woocommerce/components` package.
2. `image`, `title`, `progress`, `label`, `text` should be configurable via props

**Comment by rjchow** [comment]
Closing this as it's been completed in https://github.com/woocommerce/woocommerce/pull/39735

To be followed up with: https://github.com/woocommerce/team-ghidorah/issues/259
