### ISSUE TITLE
[Enhancement]: Order cancellation email to client

### ISSUE THREAD

**Issue by dannydesign** [woothemes/woocommerce#38937]
### Describe the solution you'd like

Send an Order cancellation email to client and admin at the same time, not only admin.

### Describe alternatives you've considered

Custom code which is kind of silly and does not solve completely.
Paid addons. Those shouldn't be necessary as this is a fairly simple and straightforward option present in any other ecommerce platform.

**Comment by natko1** [comment]
I've made a report here as well: https://github.com/woocommerce/woocommerce/issues/36692

**Comment by rrennick** [comment]
@natko1 Thanks for posting the link. I'll close this as a duplicate.
