### ISSUE TITLE
PHP 8.x deprecation notices

### ISSUE THREAD

**Issue by mbio1986** [woothemes/woocommerce#38940]
### Describe the solution you'd like

Hello

I identified various PHP incompatiblity issues, including some related to Woocommerce. Those appeared following my migration to PHP 8.2 from 7.4.

You can find the full list on the below link. Feel free to ask access and I will give it to you. Or kindly tell me if there is another way to sahre and Excel file with you.

[https://docs.google.com/spreadsheets/d/1uhKWvPb1t1wTA6HMaJtsa-rMn5mhG_bz/edit?usp=drive_link&ouid=101787929139592943569&rtpof=true&sd=true](url)

Is it something you can do to solve them ?

Thanks

**Comment by samueljseay** [comment]
@woocommerce/proton I've labelled performance in lieu of a better label for this. 🙇🏻

**Comment by barryhughes** [comment]
Hi @mbio1986, I requested access. To confirm, are these issues you experienced with our current production build, or that you could replicate using `trunk`? Asking primarily because we've resolved a number of PHP 8.x issues recently (though they may not have yet made it to the public release).

**Comment by mbio1986** [comment]
Hello

Thanks a lot. I granted you access. not that some of the elements in
excel file are nto woocommerce related. but I am sure you can filter.

I am talking about issues identified in the current version made
available to the public. so indeed maybe some of those elements have
been fixed already by you guys and will be pushed to new release but
It would be great if you can cross-check.

Thanks a million in advance.

KR

Gaetan Bio

**Comment by barryhughes** [comment]
Most of these appear to have been addressed in `trunk`. However, if we inadvertently missed any please do feel free to follow-up with more specific issues. Thanks!
