### ISSUE TITLE
[Fix] Update label styling for feedback form fields

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38952]
While reviewing the feedback form, I noticed that the sentiment field labels (the ones with emojis) do not match other fields in terms of styling. Updating them should also help make the modal more compact. On top of that, let's update its title.

<img width="764" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/68625878-8dd4-4ae4-a4c8-196bac17721a">

**Acceptance criteria**
- [ ] Styling of the sentiment field labels matches all other fields in the form (14px, 600, 20px > 11px, 500, 16px)
- [ ] The modal has a new title: `What do you think of the new product form?`

**Comment by j111q** [comment]
Based on what I can see in my test store, I think this has already been done so I'm going to close for y'all. 😅
