### ISSUE TITLE
[Fix] Reorganize items in the dropdown menu

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38951]
I noticed that items in the `...` dropdown menu in the new product editor do not match the design.

**Design**

`lj4AUMJnpMtUe7XqyvOONq-fi-1334-117673&mode=design&t=03TjVe6hhM2BhCfz-4`

**Current state**

<img width="314" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/48614dff-da6e-4dae-8c21-b3aa992aa418">

**Desired state**

<img width="570" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/4fa9673a-5760-482c-a848-9374355892b2">

**Acceptance criteria**
- [ ] The dropdown has a header that says `New product form (Beta)`
- [ ] Label change: `About the editor...` > `About the product form...`
- [ ] There's a thin line separating `Share feedback` and `About the form...` from `Turn off the new product form`.

**Comment by pmcpinto** [comment]
I'm closing this issue as the changes were already implemented
