### ISSUE TITLE
[Fix] Remove periods at the end of section descriptions

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38958]
Some section descriptions in Pricing and Inventory end with periods that shouldn't be there. Let's remove them to boost consistency and avoid possible confusion.

<img width="619" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/44840815-69ef-4ea9-a0c0-8f7ec9afd0a6">

<img width="835" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/4e47552a-ec4c-4b71-a5c2-ab0ce7f42a6b">

**Comment by octaedro** [comment]
Hi @jarekmorawski,

I'm working on this issue now. I [removed the extra periods](https://github.com/woocommerce/woocommerce/pull/46346/files) from the `Fees & dimensions` section, and I wanted to ask you whether it is also expected to remove every period after a link.

<img width="619" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/44840815-69ef-4ea9-a0c0-8f7ec9afd0a6">

From this image in the description, I understand that it's an AC for this issue.

**Comment by jarekmorawski** [comment]
Hi @octaedro! Yes, I think we should remove them all. The screenshots show two places where I'd found the unnecessary periods, but ideally, we'd delete them from the whole interface.

**Comment by octaedro** [comment]
Thank you @jarekmorawski!
I just created [a PR to remove](https://github.com/woocommerce/woocommerce/pull/46346) the unnecessary periods.
