### ISSUE TITLE
Bulk action Order status change and delete not working

### ISSUE THREAD

**Issue by darkopeter19** [woothemes/woocommerce#38992]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I Use the WooCommerce orders tables, any bulk delete or order status change on affects one order and not the selected ones.

### Expected behavior

Bulk actions affect selected orders.

### Actual behavior

Bulk actions does not affect seleceted items but rather just one out of all the selected items.

### Steps to reproduce

1. Use the WooCommerce orders tables
2. Click on orders from the woocomerce dropdown list.
3. Click on any status e.g. processing or bin.
4. Select more than five orders
5. Select a bulk action e.g. Change status to on hold or Delete permanently.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Post Type Counts ###

attachment: 174
bookable_resource: 14
cms_block: 22
cookielawinfo: 6
csp_rules: 2
e-landing-page: 3
elementor_library: 5
es_slider: 1
mailpoet_page: 1
mc4wp-form: 1
ml-slide: 4
ml-slider: 1
nav_menu_item: 33
order_status: 8
page: 38
post: 6
product: 15
product_variation: 8
revision: 237
seedprod: 2
shop_order: 476340
shop_order_refund: 7167
wallet_withdrawal: 110
wc_booking: 73
wc_googlespreadsheet: 1
wc_order_status: 22
woodmart_sidebar: 1
woodmart_size_guide: 1
woodmart_slide: 5
wp_global_styles: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: GHS (₵)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.2.4
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-28 08:35:32 +00:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Complete: 398,367
Oldest: 2023-05-28 08:13:17 +0000
Newest: 2023-06-28 07:56:18 +0000

Pending: 116
Oldest: 2023-06-28 08:13:04 +0000
Newest: 2023-06-28 17:28:57 +0000

### Status report information ###

Generated at: 2023-06-28 08:13:35 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by markakk** [comment]
I faced the same problem. After investigating the problem, I found that $_REQUEST returns only one "order" value, even though there are multiple "order" elements specified in the request URL. I noticed the problem on Woocommerce 7.8.2 with enabled HPOS.
![paveikslas](https://github.com/woocommerce/woocommerce/assets/71830881/cd113906-9bb4-4837-b524-a69e1bb56f11)
![paveikslas](https://github.com/woocommerce/woocommerce/assets/71830881/64219814-359e-4fa5-a115-2656bfe977d8)
File `woocommerce/src/Internal/Admin/Orders/ListTable.php` _(culog() is a function I created for easer variables output to log file)_:
![paveikslas](https://github.com/woocommerce/woocommerce/assets/71830881/ee7a418c-021a-47a7-b38c-2f8795ee4a06)
![paveikslas](https://github.com/woocommerce/woocommerce/assets/71830881/257cc621-6e90-4e6b-9a33-6ad22e418ec3)

**Comment by darkopeter19** [comment]
Hi,
The issue has been resolved in the current update.
Thanks.

**Comment by darkopeter19** [comment]
Hi,
The issue has been resolved in the current update.
Thanks.

**Comment by rrennick** [comment]
@darkopeter19 Thanks for the follow up.
