### ISSUE TITLE
[ Product Block Editor ] Add support for multiple product types

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#39003]
**Issue Description:**

At the moment the product block editor only supports simple products, but we will want to add support for all product types like variable, grouped, external, etc...
This is an overarching issue to keep track of the progress of supporting multiple product types.

Support for:

- [x] Simple products
- [ ] Variable products
- [ ] Grouped products
- [ ] External/Affiliate product
- [ ] Digital product

**Comment by pmcpinto** [comment]
I'll close this issue as we're already tracking this
