### ISSUE TITLE
WooCommerce REST API using deprecated code

### ISSUE THREAD

**Issue by KevinPlusPlus** [woothemes/woocommerce#39006]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Built-in WooCommerce REST API code is using a deprecated accessor and needs to be updated.

In /woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php

Around like 324, change:

				'code'         => $coupon_item['name'],
				'discount'     => wc_format_decimal( $coupon_item['discount_amount'], $dp ),
				'discount_tax' => wc_format_decimal( $coupon_item['discount_amount_tax'], $dp ),
TO:

				'code'         => $coupon_item->get_name(),
				'discount'     => wc_format_decimal( $coupon_item->get_discount(), $dp ),
				'discount_tax' => wc_format_decimal( $coupon_item->get_discount_tax(), $dp ),
The name, discount amount, and discount amount tax should not be accessed using the array parameters, but rather with getters.

This will remove the deprecation warning when accessing coupon information in REST API v1.

Thank you!

Kevin

### Expected behavior

WooCommerce REST API v1 will no longer throw a deprecated function warning when accessing coupons

### Actual behavior

"WC_Order_Item_Coupon::offsetGet deprecated since 4.4.0" warning thrown when accessing coupon data from REST API v1

### Steps to reproduce

Access coupon data from REST API v1

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.7
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 8.1.2
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Status report information ###

Generated at: 2023-06-28 14:49:34 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by KevinPlusPlus** [comment]
Thank you! I should have mentioned that I am using WooCommerce 7..8.1.

**Comment by Babylon1999** [comment]
Same story in zd-6770845

- https://wordpress.org/support/topic/issue-with-the-address-fields-on-check-out/#post-17060148

**Comment by lynnjat7** [comment]
Another report here from a HVC - 7682554-zd-a8c
