### ISSUE TITLE
Cart Fly-out has no products

### ISSUE THREAD

**Issue by thomasvbe** [woothemes/woocommerce#39015]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When updating to WooCommerce 7.8.0, the Elementor cart fly-out has no products, when there are some products in the cart.

### Expected behavior

That there are products in the cart fly-out.

### Actual behavior

There are no products in the cart fly-out.

### Steps to reproduce

Install WooCommerce together with Elementor PRO.
Put some products in the cart.
Click the cart menu button.
Fly-out becomes visible without products.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://cursist-courses.com
Site address (URL): https://cursist-courses.com
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: wp_
Total Database Size: 397.43MB
Database Data Size: 367.41MB
Database Index Size: 30.02MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 1.98MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 25.52MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.52MB + Index: 1.09MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_aft_cc: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 4.52MB + Index: 6.69MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.38MB + Index: 0.11MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.23MB + Index: 0.48MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 10.50MB + Index: 0.34MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 187.55MB + Index: 8.03MB + Engine InnoDB
wp_posts: Data: 61.52MB + Index: 0.83MB + Engine InnoDB
wp_post_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_associations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_toolset_connected_elements: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_activecampaign: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 27.58MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.39MB + Index: 0.13MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpgmza: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_admin_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpgmza_datasets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_image_overlays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps_has_custom_fields_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_markers_has_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_markers_has_custom_fields: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_point_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.13MB + Index: 0.28MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.22MB + Index: 0.20MB + Engine InnoDB

### Post Type Counts ###

acf-field: 115
acf-field-group: 3
ae_global_templates: 2
attachment: 2929
custom_css: 1
custom-css-js: 4
elementor_font: 2
elementor_library: 102
elementor_snippet: 2
mailpoet_page: 1
nav_menu_item: 20
oembed_cache: 4
page: 57
post: 189
product: 27
product_variation: 35
revision: 1215
shop_coupon: 7
shop_order: 1182
shop_subscription: 145
wp_global_styles: 2
wp-types-group: 10
wpcode: 2
yith_wcan_preset: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (61) ###

Advanced Custom Fields Multilingual: by OnTheGoSystems – 2.0.5
ActiveCampaign for WooCommerce: by ActiveCampaign – 2.2.4
ActiveCampaign: by ActiveCampaign – 8.1.12
Advanced Custom Fields PRO: by WP Engine – 6.1.6
Akismet Anti-Spam: by Automattic – 5.1
All-in-One WP Migration Unlimited Extension: by ServMask – 2.47
All-in-One WP Migration: by ServMask – 7.75
Code Snippets: by Code Snippets Pro – 3.4.0
Complianz Privacy Suite (GDPR/CCPA) premium: by Really Simple Plugins – 6.4.8
Simple Custom CSS and JS: by SilkyPress.com – 3.44
Download Plugins and Themes from Dashboard: by WPFactory – 1.8.2
GTM4WP: by Thomas Geiger – 1.16.2
Dynamic.ooo - Dynamic Content for Elementor: by Dynamic.ooo – 2.10.3
Ele Custom Skin Pro: by Dudaster.com – 3.2.4
Ele Custom Skin: by Dudaster.com – 3.1.7
Elementor Pro: by Elementor.com – 3.13.2
Elementor: by Elementor.com – 3.13.4
Essential Addons for Elementor - Pro: by WPDeveloper – 5.4.11
Essential Addons for Elementor: by WPDeveloper – 5.8.0
Google Listings and Ads: by WooCommerce – 2.4.10
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
WPCode Lite: by WPCode – 2.0.12
Jetpack: by Automattic – 12.2.1
Mollie Payments for WooCommerce: by Mollie – 7.3.9
WooCommerce Easy Checkout Fields Editor: by WooMatrix – 2.6.2
Pinterest for WooCommerce: by WooCommerce – 1.3.3 (update to version 1.3.5 is available)
Premium Addons for Elementor: by Leap13 – 4.9.57
Premium Addons PRO: by Leap13 – 2.8.27
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 2.1.0

Simple File List: by Mitchell Bennis – 6.1.8
WPML Multilingual CMS: by OnTheGoSystems – 4.6.3
String Locator: by InstaWP – 2.6.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.39
The Plus Addons for Elementor: by POSIMYTH – 5.2.8
The Plus Addons for Elementor - Pro: by POSIMYTH – 5.1.6
Toolset Types: by OnTheGoSystems – 3.4.19
User Switching: by John Blackbourn & contributors – 1.7.0
Woo Discount Rules PRO 2.0: by Flycart – 2.6.0
Woo Discount Rules: by Flycart – 2.6.0
Premmerce Permalink Manager for WooCommerce: by Premmerce – 2.3.8
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.2
WooCommerce EU VAT Number: by WooCommerce – 2.8.4
WooCommerce Gift Cards: by WooCommerce – 1.16.2
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.1.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.5
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.14.2
WooCommerce Product Bundles: by WooCommerce – 6.20.0 (update to version 6.21.1 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce Zapier: by OM4 Software – 2.6.0
WooCommerce: by Automattic – 7.7.2 (update to version 7.8.1 is available)
Wordfence Security: by Wordfence – 7.10.0
Yoast SEO Premium: by Team Yoast – 20.9
Yoast SEO: by Team Yoast – 20.9
WP Google Maps - Pro Add-on: by WP Google Maps – 8.1.20
WP Go Maps (formerly WP Google Maps): by WP Go Maps – 9.0.19
WP Mail Logging: by WP Mail Logging Team – 1.11.2
WPML SEO: by OnTheGoSystems – 2.1.0
WPML CMS Nav: by OnTheGoSystems – 1.5.5
WPML Media: by OnTheGoSystems – 2.7.2
WPML String Translation: by OnTheGoSystems – 3.2.5

### Inactive Plugins (15) ###

Advanced Custom Fields: by WP Engine – 6.1.6
AnyWhere Elementor Pro (Premium): by WP Vibes – 2.25.1
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
CoDesigner: by Codexpert – 3.11
CookiePro: by OneTrust
Llc – 1.0.4

Import Export for WooCommerce Wrapper: by WebToffee – 1.1.4
Order Import Export for WooCommerce Add-on: by WebToffee – 1.1.0
OTGS Installer: by OnTheGoSystems – 3.0.0
Post Views Counter: by Digital Factory – 1.3.13
WooCommerce Payments: by Automattic – 6.0.0 (update to version 6.1.0 is available)
WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Subscriptions: by WooCommerce – 5.0.1 (update to version 5.1.3 is available)
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.5
WP Rocket: by WP Media – 3.13.0.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Ensure admin user isn't deleted: by  – 1.0
Health Check Troubleshooting Mode: by  – 1.8.1
WP CLI Login Command Server: by Evan Mattson – 1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1705 - /winkel/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #1708 - /mijn-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Cursist Courses
Version: 1.0.0
Author URL: https://webdude.be
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.1.5
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Gift Cards ###

Database Version: 1.16.2
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.20.0
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-29 14:01:16 +00:00
Options: ✔
Notes: 146
Onboarding: completed

### Action Scheduler ###

Canceled: 2
Oldest: 2023-06-01 11:14:14 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 4,807
Oldest: 2023-05-29 10:31:09 +0000
Newest: 2023-06-29 10:02:43 +0000

Failed: 66
Oldest: 2022-11-03 03:54:56 +0000
Newest: 2023-06-29 03:00:33 +0000

Pending: 8
Oldest: 2023-06-29 10:11:37 +0000
Newest: 2023-06-30 10:02:42 +0000

### WooCommerce Zapier ###

Database Version: ✔ 15
Detailed Logging Enabled: No
Legacy Mode Disabled: ✔ Yes
SSL: ✔ Yes
REST API Authentication Key(s): ✔ 2
Task History Record Count: ✔ 1361
Webhook #41: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 297
- User: Nele
Webhook #38: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 301
- User: Nele
Webhook #37: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 310
- User: Nele
Webhook #35: WooCommerce Zapier
- Status: active
- Trigger: order.paid
- Delivery Count: 320
- User: Nele
Webhook #25: WooCommerce Zapier
- Status: active
- Trigger: 
- Delivery Count: 0
- User: Nele
Deleted Webhook Delivery Count: 133

### Status report information ###

Generated at: 2023-06-29 10:07:29 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@thomasvbe Have you contacted Elementor support to verify that this is an issue with WooCommerce? If so, do you still see the issue with the latest version of WC?
