### ISSUE TITLE
[7.9] Fatal Error: GenericController not found in API/Reports/Controller.php

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#39036]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On an existing Atomic site with products and orders when upgrading to 7.9.0.x from a previous version of WooCommerce I get a fatal error:

```
CRITICAL Uncaught Error: Class 'Automattic\WooCommerce\Admin\API\Reports\GenericController' not found in /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/Reports/Controller.php:20
```
I haven't been able to reproduce this elsewhere yet.

I suspect it could be related to https://github.com/woocommerce/woocommerce/pull/38048

### Expected behavior

No fatals on upgrade

### Actual behavior

when upgrading to WooCommerce 7.9.0.x from a previous version of WooCommerce (i.e. wp-admin/update.php?action=upload-plugin&package=45618&overwrite=update-plugin&_wpnonce= ) I get the following fatal error:

```
CRITICAL Uncaught Error: Class 'Automattic\WooCommerce\Admin\API\Reports\GenericController' not found in /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/Reports/Controller.php:20
Stack trace:
#0 /wordpress/plugins/jetpack/12.3-beta/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ12_3_beta\PHP_Autoloader::load_class('Automattic\\WooC...')
#2 /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/Orders.php(47): spl_autoload_call('Automattic\\WooC...')
#3 /srv/htdocs/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php(74): Automattic\WooCommerce\Admin\API\Orders->get_collection_params()
#4 /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/Init.php(145): WC_REST_Orders_V2_Controller->register_routes()
#5 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Admin\API\Init->rest_api_init(Object(WP_REST_Server))
#6 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/core/6.2.2/wp-includes/rest-api.php(577): do_action('rest_api_init', Object(WP_REST_Server))
#9 /wordpress/core/6.2.2/wp-includes/rest-api.php(535): rest_get_server()
#10 /wordpress/core/6.2.2/wp-includes/rest-api.php(2889): rest_do_request(Object(WP_REST_Request))
#11 [internal function]: rest_preload_api_request(Array, '/wc-analytics/r...')
#12 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Admin/Settings.php(146): array_reduce(Array, 'rest_preload_ap...')
#13 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Internal\Admin\Settings->add_component_settings(Array)
#14 /wordpress/core/6.2.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#15 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Admin/WCAdminSharedSettings.php(61): apply_filters('woocommerce_adm...', Array)
#16 /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(282): Automattic\WooCommerce\Internal\Admin\WCAdminSharedSettings->Automattic\WooCommerce\Internal\Admin\{closure}()
#17 /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(383): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->execute_lazy_data()
#18 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('')
#19 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#20 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#21 /wordpress/core/6.2.2/wp-admin/admin-footer.php(95): do_action('admin_print_foo...')
#22 /wordpress/core/6.2.2/wp-admin/update.php(182): require_once('/wordpress/core...')
#23 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/Reports/Controller.php on line 20
```

No functionality appears to be affected by this.

### Steps to reproduce

1. On an existing Atomic site with products and orders
2. Upgrade to 7.9.0 Beta 2 from a previous version of WooCommerce
3. See fatal error logs for this error.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.4.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 283.29MB
Database Data Size: 134.64MB
Database Index Size: 148.65MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.08MB + Index: 3.25MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 6.36MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 6.08MB + Index: 5.58MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 8.09MB + Index: 1.17MB + Engine InnoDB
wp_postmeta: Data: 76.25MB + Index: 76.27MB + Engine InnoDB
wp_posts: Data: 9.17MB + Index: 6.73MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.03MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 3.52MB + Index: 9.59MB + Engine InnoDB
wp_wc_orders_meta: Data: 9.52MB + Index: 21.17MB + Engine InnoDB
wp_wc_order_addresses: Data: 5.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 3.52MB + Index: 3.00MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.30MB + Index: 0.34MB + Engine InnoDB
wp_wc_order_stats: Data: 3.08MB + Index: 3.64MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.45MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 3
attachment: 28
jetpack_migration: 2
jp_img_sitemap: 6
jp_sitemap: 6
jp_sitemap_master: 6
nav_menu_item: 2
page: 8
post: 1
product: 1855
revision: 4
shop_coupon: 1
shop_order: 22466
shop_order_placehold: 12
wp_global_styles: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

JSON Basic Authentication: by WordPress API Team – 0.1
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Code Snippets: by Code Snippets Pro – 3.4.1
Jetpack: by Automattic – 12.3-beta
WooCommerce: by Automattic – 8.0.0-dev

### Inactive Plugins (9) ###

AMP: by AMP Project Contributors – 2.4.1
Classic Editor: by WordPress Contributors – 1.6.3
CoBlocks: by GoDaddy – 3.0.4
Crowdsignal Forms: by Automattic – 1.7.0
Gutenberg: by Gutenberg Team – 16.0.0
Layout Grid: by Automattic – 1.8.3
Page Optimize: by Automattic – 0.5.3
WordPress.com Editing Toolkit: by Automattic – 3.70315
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #23 - /shop/
Cart: #24 - /cart/
Checkout: #25 - /checkout/
My account: #26 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.3.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-30 03:34:46 +00:00
Options: ✔
Notes: 151
Onboarding: completed

### Action Scheduler ###

Complete: 4,992
Oldest: 2023-05-30 03:39:45 +0000
Newest: 2023-06-29 19:05:09 +0000

Failed: 22
Oldest: 2023-01-21 03:54:51 +0000
Newest: 2023-04-19 03:33:17 +0000

Pending: 3
Oldest: 2023-06-29 20:05:09 +0000
Newest: 2023-06-30 03:47:41 +0000

### Status report information ###

Generated at: 2023-06-29 19:05:29 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
Closing this because of the solution mentioned here: p1688646794522989/1688579858.037389-slack-C8X6Q7XQU 
 related to updating Atomic sites and having similar issues in the past.
