### ISSUE TITLE
Coupon management has moved, route does not exist

### ISSUE THREAD

**Issue by Lutex** [woothemes/woocommerce#39041]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After the last plugin update, the message to delete the coupon button from the previous location appeared. But when I click, apparently nothing happens.

But when inspecting the browser console, I find that there is no defined route to execute

![image](https://github.com/woocommerce/woocommerce/assets/774798/6d18ab09-b201-4107-80ce-aa815ec71a04)

### Expected behavior

expected behavior is to process the route and perform the delete as indicated.

### Actual behavior

the console in the picture shows the problem. and below I leave the return obtained

![image](https://github.com/woocommerce/woocommerce/assets/774798/b758716e-a4f6-4750-8a8e-1a9235b56bee)

![image](https://github.com/woocommerce/woocommerce/assets/774798/f6f44acb-f838-47a8-974a-856170e511d0)

```
{
    "code": "rest_no_route",
    "message": "Nenhuma rota foi encontrada que corresponde com o URL e o m\u00e9todo de requisi\u00e7\u00e3o.",
    "data": {
        "status": 404
    }
}
```

### Steps to reproduce

to play, just update the plugin and open the home page to find the message with the button. and when clicking the described behavior is what happens

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 150
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.13-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: wp_
### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Lutex Thanks for creating this issue. It's related to https://github.com/woocommerce/woocommerce/issues/32187. I'll close this as a duplicate as the other issue has quite a bit of discussion on it.
