### ISSUE TITLE
Advanced settings > HPOS > Features vs Custom Data Store inconsistencies

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#39058]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I wanted to activate HPOS on a new project (september deployment)
so i checked the dedicated feature option.
but what about the custom date stores ?
seem activating the HPOS feature flag does not have an impact on the custom order tables option : it is still set to "use the wordpress posts table".

### Expected behavior

Should'nt this page to be set to the "user woocommerce orders tables" option instead ??

### Actual behavior

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/f7ca345c-8ec5-4f69-bd10-ab90b2f2fb96)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/b1f1390c-8d08-4149-8f0b-e0f9b70c0fac)

### Steps to reproduce

just go to WooCommerce > Settings > Avanced > Features and Custom data stores

### WordPress Environment

WooCommerce 7.8.1
Woo Blocks 10.5.0
WP 6.2.2.
Gutenberg 16.1.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Marc-pi** [comment]
https://github.com/woocommerce/woocommerce/pull/38993

@vedanshujain, seems you are working on this

**Comment by vedanshujain** [comment]
@Marc-pi Hey yes, this would be addressed in #38993

**Comment by vedanshujain** [comment]
Closing this as this was addressed in #38993 and the separate setting screen was folded in to the main screen.
