### ISSUE TITLE
Woocommerce 7.8.1 causes the REST API call for new product creation to fail with error "internal_server_error"",""message"":"There has been a critical error on this website"

### ISSUE THREAD

**Issue by BasitBulbulia** [woothemes/woocommerce#39061]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using 7.8.0 this error does not occur - when using 7.8.1 there error occurs this is my code:
```
  Try
                            Dim p As WooCommerceNET.WooCommerce.v3.Product = New WooCommerceNET.WooCommerce.v3.Product() With {
                        .name = name.Trim(),
                        .regular_price = regular_price,
                        .sale_price = sale_price,
                        .price = sale_price,
                        .sku = sku,
                        .stock_quantity = Val(stock_quantity),
                        .categories = ProductCategory,
                        .manage_stock = True,
                        .type = "variable",
                        .attributes = Productattributes,
                        .images = ProductImages
                        }
                            Dim ProductId = Await wc.Product.Add(p)

                        Catch ex As Exception
                            MsgBox(ex.Message)
                        End Try
```

### Expected behavior

The product should update and it does not !

### Actual behavior

The error is generated as desrcibed in the Title

### Steps to reproduce

See code .net VB

### WordPress Environment

woocommerce 7.8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pulstar** [comment]
I am experiencing the same issue on version 7.8.1, but the 7.8.0 is working fine.

[03-Jul-2023 17:49:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_default_product_type_options() in /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php:242
Stack trace:
#0 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(259): WC_Products_Tracking::get_possible_product_type_options_ids()
#1 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(311): WC_Products_Tracking::get_product_type_options()
#2 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(308): WC_Products_Tracking->track_product_published()
#3 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/u689081133/domains/mydomain.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/u689081133/domains/mydomain.com/public_html/wp-includes/post.php(5436): do_action()
#6 /home/u689081133/domains/mydomain.com/public_html/wp-includes/post.php(4729): wp_after_insert_post()
#7 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(135): wp_insert_post()
#8 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(186): WC_Product_Data_Store_CPT->create()
#9 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(1431): WC_Data_Store->create()
#10 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(169): WC_Product->save()
#11 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(191): WC_REST_CRUD_Controller->save_object()
#12 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1181): WC_REST_CRUD_Controller->create_item()
#13 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request()
#14 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch()
#15 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api.php(410): WP_REST_Server->serve_request()
#16 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(308): rest_api_loaded()
#17 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /home/u689081133/domains/mydomain.com/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#19 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp.php(399): do_action_ref_array()
#20 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp.php(780): WP->parse_request()
#21 /home/u689081133/domains/mydomain.com/public_html/wp-includes/functions.php(1334): WP->main()
#22 /home/u689081133/domains/mydomain.com/public_html/wp-blog-header.php(16): wp()
#23 /home/u689081133/domains/mydomain.com/public_html/index.php(17): require('/home/u68908113...')
#24 {main}
  thrown in /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php on line 242
[03-Jul-2023 17:55:37 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_default_product_type_options() in /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php:242
Stack trace:
#0 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(259): WC_Products_Tracking::get_possible_product_type_options_ids()
#1 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(311): WC_Products_Tracking::get_product_type_options()
#2 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(308): WC_Products_Tracking->track_product_published()
#3 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/u689081133/domains/mydomain.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/u689081133/domains/mydomain.com/public_html/wp-includes/post.php(5436): do_action()
#6 /home/u689081133/domains/mydomain.com/public_html/wp-includes/post.php(4729): wp_after_insert_post()
#7 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(135): wp_insert_post()
#8 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(186): WC_Product_Data_Store_CPT->create()
#9 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(1431): WC_Data_Store->create()
#10 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(169): WC_Product->save()
#11 /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(191): WC_REST_CRUD_Controller->save_object()
#12 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1181): WC_REST_CRUD_Controller->create_item()
#13 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request()
#14 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch()
#15 /home/u689081133/domains/mydomain.com/public_html/wp-includes/rest-api.php(410): WP_REST_Server->serve_request()
#16 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(308): rest_api_loaded()
#17 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /home/u689081133/domains/mydomain.com/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#19 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp.php(399): do_action_ref_array()
#20 /home/u689081133/domains/mydomain.com/public_html/wp-includes/class-wp.php(780): WP->parse_request()
#21 /home/u689081133/domains/mydomain.com/public_html/wp-includes/functions.php(1334): WP->main()
#22 /home/u689081133/domains/mydomain.com/public_html/wp-blog-header.php(16): wp()
#23 /home/u689081133/domains/mydomain.com/public_html/index.php(17): require('/home/u68908113...')
#24 {main}
  thrown in /home/u689081133/domains/mydomain.com/public_html/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php on line 242

**Comment by pulstar** [comment]
I tryed the version 7.9.0-beta.2 and now nothing is working anymore, neither after I rollback to the version 7.8.0. It is displaying the error:

Error: ID inválido. [woocommerce_rest_product_invalid_id]

**Comment by BasitBulbulia** [comment]
Try using 7.8.2 it seem to be working !

**Comment by BasitBulbulia** [comment]
Try using 7.8.2

**Comment by pulstar** [comment]
> Try using 7.8.2 it seem to be working !

Thank you! It's working as a charm now.

**Comment by WillBrubaker** [comment]
6482154-zen

**Comment by barryhughes** [comment]
Closing, as it sounds like the root of the problem was the same as described in https://github.com/woocommerce/woocommerce/issues/38996, which was fixed via https://github.com/woocommerce/woocommerce/pull/39030.
