### ISSUE TITLE
'woocommerce_cart_item_name' was called twice

### ISSUE THREAD

**Issue by dunghv26** [woothemes/woocommerce#39080]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In some recently updated versions, the filter hook 'woocommerce_cart_item_name' was called twice https://app.screencast.com/jxHDhzzzP9apu, so other plugins that used this hook will cause the duplicate content https://app.screencast.com/wEoXPBinsUTTX

### Expected behavior

Add more text to the cart item name

### Actual behavior

The text was duplicated

### Steps to reproduce

1. Add a snippet using the filter hook 'woocommerce_cart_item_name'
2. Go to the cart page to see the duplicate content

### WordPress Environment

WordPress 6.2.2 and WooCommerce 7.8.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for reporting, however I'm going to close it as it duplicates https://github.com/woocommerce/woocommerce/issues/38744 and https://github.com/woocommerce/woocommerce/pull/39067 (and should be solved by https://github.com/woocommerce/woocommerce/pull/38999).
