### ISSUE TITLE
Introduce the add and edit view Tracks events in the new form

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#39089]
**Description:** we should trigger two additional events to match the existing tracking in the current experience a develop a better understanding of when the user is creating or editing a product.

**Acceptance criteria:**
- [x] Fire `wcadmin_product_add_view` when the user is creating a product, replicating what exists in the current experience. Include a new event property to identify the new form ( new property can be `source` see [comment below](https://github.com/woocommerce/woocommerce/issues/39089#issuecomment-1623682755) )
- [x] Fire `wcadmin_product_edit_view` when the user is editing a product, replicating what exists in the current experience. Include a new event property to identify the new form ( new property can be `source` see [comment below](https://github.com/woocommerce/woocommerce/issues/39089#issuecomment-1623682755) )

**Target release:** these changes should be included in WC 8.0

**Comment by pmcpinto** [comment]
cc @louwie17

**Comment by louwie17** [comment]
We may want to follow the `source` property that `wcadmin_product_add_publish` uses as well.
I know it is currently set to `product-block-editor-v1` when triggered from the new editor, not sure where that is set though (apparently in a constants file as `TRACKS_SOURCE` ).

**Comment by AnnaMag** [comment]
@louwie17 I believe it is [here](https://github.com/woocommerce/woocommerce/blob/19b3d40595462a430f06cb8f7ddba0df2d92384c/plugins/woocommerce/src/Admin/Features/ProductBlockEditor/Tracks.php#L46), so the property would be included by default.
