### ISSUE TITLE
[7.9 rc beta]: Lossing attribute data on product update

### ISSUE THREAD

**Issue by drosendo** [woothemes/woocommerce#39104]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When updating a Variable product, the attributes information is lost, and the checkbox "used for variations" becomes locked.

It still shows on the product back-office but nothing on the front-end also in the the back-end its wierd.

### Expected behavior

Correctly work and manage it.

### Actual behavior

When updating a Variable product, the attributes information is lost, and the checkbox "used for variations" becomes locked.

It still shows on the product back-office but nothing on the front-end also in the the back-end its wierd.

### Steps to reproduce

1. go to variable product
2. edit something
3. save
4. watch the result

### WordPress Environment

Latest version
WooCommerce
Storefront

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @drosendo! Thank you for submitting this issue. This seems very identical to https://github.com/woocommerce/woocommerce/issues/39105 so I'll go ahead and close this one in favor of that. We already got a pull request to resolve it.

Feel free to reopen this issue if you think your issue is different from the one I mentioned above.
