### ISSUE TITLE
[Product Block Editor] Add tags (or general taxonomy ) block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#39126]
As part of [#38823](https://github.com/woocommerce/woocommerce/issues/38823) we are creating a new tab that includes the product tags field
We should create a block to handle tags as we don't currently support this. We should have everything in place for this:
- Tags data store
- Typeahead field ( mimic implementation of categories )

**Note:**
Creating tags will be done in a separate issue.

~~We could also re-use the `PostTaxonomies` component from Gutenberg: https://github.com/WordPress/gutenberg/tree/1b82cbf757fbce04f21f2cf317d7367581e706e4/packages/editor/src/components/post-taxonomies~~ (see [comment](https://github.com/woocommerce/woocommerce/issues/39126#issuecomment-1623872625))

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-3301_400762

<img width="413" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/56c8aaae-5d27-4930-ad65-8eb4f26adbd8">

**Acceptance criteria**

- [ ] Tags dropdown should be visible underneath the category field
- [ ] Dropdown should allow us to search for and select existing tags ( same functionality as the category field )

**Comment by louwie17** [comment]
@jarekmorawski question on the tags field, could we re-use the `PostTaxonomies` component from Gutenberg -> https://github.com/WordPress/gutenberg/tree/1b82cbf757fbce04f21f2cf317d7367581e706e4/packages/editor/src/components/post-taxonomies
That is used for the tags field in the sidebar within post editor for example?

**Comment by jarekmorawski** [comment]
That component offers a different UX (`add` instead of `select`), and parts of it feel dated. I prefer to use our dropdown component since it has all features we need. Would there be a significant different in effort?
