### ISSUE TITLE
[Product Block Editor] Show onboarding tour within description block editor

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#39131]
**Description**

When the user enters the editor for the first time, they should see the welcome message and the onboarding tour included in the current post editor.

**Design**
(screenshot of the block editor tour within the post editor)
![Image](https://user-images.githubusercontent.com/2240960/251529296-35febea4-7be4-46d4-80ab-b489549c6b5b.png)

WP core implementation: https://github.com/WordPress/gutenberg/blob/b23e049459dcab00bb65e505a4b42c3904f81144/packages/edit-post/src/components/welcome-guide/index.js#L0-L1

**Acceptance criteria**

- [ ] When user visits the block editor for the first time in the description modal the onboarding tour should be present. This should respect the same option as the block editor in posts and other areas. If a user has already seen the tour there, we don't need to show it here.

**Comment by louwie17** [comment]
cc: @jarekmorawski I created this as a separate issue from https://github.com/woocommerce/woocommerce/issues/38207 
Could you double check if this looks good, and also do we have any specific designs for this?

I also noted in the acceptance criteria to respect if a user see the popup before in other contexts (like the post editor), and not display it in that case. Is this something you want? or should this only pertain to the product description editor?

**Comment by jarekmorawski** [comment]
> Could you double check if this looks good, and also do we have any specific designs for this?

No specific designs, let's use what exists in Gutenberg core.

> I also noted in the acceptance criteria to respect if a user see the popup before in other contexts (like the post editor), and not display it in that case. Is this something you want?

Yes! Great call. There are people who are already using blocks, so there's no need to show the intro message again.
