### ISSUE TITLE
woocommerce tour kit step issue on mobile device.

### ISSUE THREAD

**Issue by sumitsinghwp** [woothemes/woocommerce#39137]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have set up a site with WooCoomerce on my Desktop and everything working fine tour kit step and highlightings fields (Like Title, feature image, etc.) for each step. but the mobile devices on not look like this. It should highlight fields on each next step on mobile too.

For more information, you can see mentioned both quick videos.

https://github.com/woocommerce/woocommerce/assets/23701579/a2b6d65b-38f2-485e-a1ef-af4ff0795a49

https://github.com/woocommerce/woocommerce/assets/23701579/8c32af5d-ecfe-4909-bd03-5281d059a45a

### Expected behavior

as per my expectation, It should highlight fields on each next step on mobile too similar to desktop.

### Actual behavior

 It does not highlight fields on each next step on mobile too similar to desktop.

### Steps to reproduce

Setup a new WC plugin and try to add a new product first time on the admin side.Set upSet up

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://192.168.1.104/wpextended-pro
Site address (URL): http://192.168.1.104/wpextended-pro
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.2 - There is a newer version of WordPress available (6.2.3-alpha-55925)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3-4ubuntu2.19
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.33-0ubuntu0.20.04.2
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 4.56MB
Database Data Size: 3.10MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpext_login_attempt: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpext_login_failed: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 10
page: 15
post: 4
product: 6
revision: 15
sell_media_item: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.12.3
Admin Login Notification: by Sumit Singh – 1.0
Contact Form 7: by Takayuki Miyoshi – 5.7.7
Sell Media: by Graph Paper Press – 2.5.7.4
WooCommerce: by Automattic – 7.8.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.1
WP Extended Pro: by NRCM Web Design – 2.1.0

### Inactive Plugins (35) ###

ACF Photo Gallery Field: by Navneil Naicker – 1.9
Admin and Site Enhancements: by Bowo – 5.2.11
Admin Columns: by AdminColumns.com – 4.6.1
Advanced Custom Fields: by WP Engine – 6.1.7
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Breakdance: by Breakdance – 1.1
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.7
Change wp-admin login: by wpexpertsio – 1.1.3
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Classic Widgets and Editor: by WP Lovers – 0.1
Core Rollback: by Andy Fragen – 1.3.4
Custom fields Postal code in WP Registration: by IIH Global – 0.1
Custom fields Postal code in WP Registration: by Sumit Singh – 0.1
Custom Post Type UI: by WebDevStudios – 1.13.6
Duplicate Page: by mndpsingh287 – 4.5.2
Elementor: by Elementor.com – 3.14.1
Elite Notification: by Appsbd – 1.5
Hello Dolly: by Matt Mullenweg – 1.7.2
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.4.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.25.20
Maintenance: by WebFactory Ltd – 4.07
Media Replace: by Sumit Singh – 1.0.0
NotificationX: by WPDeveloper – 2.7.2
Oxygen: by Soflyy – 3.8.1
PixelYourSite: by PixelYourSite – 9.4.0.1
Post Types Order: by Nsp Code – 2.0.9
User Role Editor: by Vladimir Garagulya – 4.63.3
User Switching: by John Blackbourn & contributors – 1.7.0
Visual Composer: by visualcomposer.com – 45.3.0
WPCode Lite: by WPCode – 2.0.13
WP Feedback: by WP Feedback – 1.1.8
WP Rollback: by GiveWP.com – 1.7.3
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.8

WPS Limit Login: by WPServeur
NicolasKulka
wpformation – 1.5.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #56 - /index.php/shop/
Cart: #57 - /index.php/cart/
Checkout: #58 - /index.php/checkout/
My account: #59 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-08 06:08:19 +00:00
Options: ✔
Notes: 65
Onboarding: skipped

### Action Scheduler ###

Complete: 3
Oldest: 2023-07-07 06:09:22 +0000
Newest: 2023-07-07 06:11:37 +0000

Pending: 1
Oldest: 2023-07-08 06:09:22 +0000
Newest: 2023-07-08 06:09:22 +0000

### Status report information ###

Generated at: 2023-07-07 06:25:14 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea, we really appreciate your help.

While this is clearly a good improvement we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog, where it will be considered for future releases.

Stay tuned for updates.

cc @adrianduffell as the tour was implemented by Ghirodah
