### ISSUE TITLE
Cannot import the csv format product file

### ISSUE THREAD

**Issue by paaaatricia** [woothemes/woocommerce#39141]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I export the product list csv. as the template from Woocommerce. But after I fill in my product info, I tried to import the CSV. format to my Woocommerce, it said "Sorry, you are not allowed to upload this file type." And I tried TXT as well. It failed,either.

### Expected behavior

please help me or tell me which format can import the products.

### Actual behavior

#impo

### Steps to reproduce

#impo

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://garamer.com
Site address (URL): https://garamer.com
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.9

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: jof_
Total Database Size: 127.88MB
Database Data Size: 113.56MB
Database Index Size: 14.32MB
jof_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
jof_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
jof_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
jof_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
jof_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_actionscheduler_actions: Data: 5.02MB + Index: 3.00MB + Engine InnoDB
jof_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_actionscheduler_logs: Data: 0.39MB + Index: 0.31MB + Engine InnoDB
jof_ac_abandoned_cart_history_lite: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
jof_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_aioseo_cache: Data: 2.52MB + Index: 2.84MB + Engine InnoDB
jof_aioseo_links: Data: 1.31MB + Index: 0.09MB + Engine InnoDB
jof_aioseo_links_suggestions: Data: 5.25MB + Index: 0.48MB + Engine InnoDB
jof_aioseo_notifications: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
jof_aioseo_posts: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
jof_aioseo_redirects: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
jof_aioseo_redirects_404: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_aioseo_redirects_404_logs: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
jof_aioseo_redirects_hits: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_aioseo_redirects_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
jof_aioseo_revisions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_aioseo_search_statistics_objects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_aioseo_terms: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
jof_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
jof_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
jof_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
jof_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
jof_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
jof_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_feedmanager_feed_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_feedmanager_source: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
jof_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_ipanorama: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_options: Data: 6.03MB + Index: 0.23MB + Engine InnoDB
jof_parcelpanel_courier: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
jof_parcelpanel_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_parcelpanel_tracking: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
jof_parcelpanel_tracking_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
jof_postmeta: Data: 39.41MB + Index: 1.81MB + Engine InnoDB
jof_posts: Data: 44.09MB + Index: 0.30MB + Engine InnoDB
jof_sgs_log_events: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
jof_sgs_log_visitors: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
jof_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
jof_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
jof_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_userfeedback_surveys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_userfeedback_survey_responses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
jof_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
jof_viwec_clicked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
jof_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
jof_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
jof_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
jof_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
jof_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
jof_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
jof_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
jof_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
jof_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
jof_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1114
custom_css: 1
customize_changeset: 5
e-landing-page: 1
elementor_icons: 1
elementor_library: 9
etheme_portfolio: 1
mc4wp-form: 2
nav_menu_item: 21
oembed_cache: 1
page: 23
post: 53
product: 132
product_variation: 161
revision: 1767
shop_coupon: 19
shop_order: 17
staticblocks: 33
viwec_template: 14
wp_block: 8
wpcode: 2
wptb-tables: 1
wpvr_item: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

AIOSEO - Image SEO: by All in One SEO Team – 1.1.7
AIOSEO - IndexNow: by All in One SEO Team – 1.0.10
AIOSEO - Link Assistant: by All in One SEO Team – 1.0.15
AIOSEO - Redirects: by All in One SEO Team – 1.2.11
AIOSEO - REST API: by All in One SEO Team – 1.0.5
AIOSEO - Video Sitemap: by All in One SEO Team – 1.1.13
All in One SEO Pro: by All in One SEO Team – 4.4.0.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Elementor Pro: by Elementor.com – 3.14.1
Elementor: by Elementor.com – 3.14.1
Envira Gallery Lite: by Envira Gallery Team – 1.8.6.2
XStore Core: by 8theme – 5.1.8
Facebook for WooCommerce: by Facebook – 3.0.26
FileBird: by Ninja Team – 5.0.8
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.17
Google Listings and Ads: by WooCommerce – 2.4.10
WPCode Lite: by WPCode – 2.0.13
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.5
OptinMonster: by OptinMonster Popup Builder Team – 2.13.5
Parcel Panel Order Tracking for WooCommerce: by Parcel Panel – 3.1.3
Pinterest for WooCommerce: by WooCommerce – 1.3.5
WooCommerce Infinite Scroll and Ajax Pagination: by sbthemes – 1.6.2
SiteGround Security: by SiteGround – 1.4.5
Subscriptio: by RightPress – 3.0.7
Trustpilot-reviews: by Trustpilot – 2.5.922
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.6

UserFeedback Lite: by UserFeedback Team – 1.0.6
W3 Total Cache: by BoldGrid – 2.3.3
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
WPC Product Bundles for WooCommerce: by WPClever – 7.2.4
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.15.2
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce PDF Invoice: by RightPress – 3.2.1
WooCommerce: by Automattic – 7.8.1 (update to version 7.8.2 is available)
WordPress Importer: by wordpressdotorg – 0.8.1
WP Product Feed Manager: by Michel Jongbloed – 1.49.1
WP Table Builder: by WP Table Builder – 1.4.9
WPForms Lite: by WPForms – 1.8.2.2
WP VR: by Rextheme – 8.3.2
YITH WooCommerce Wishlist: by YITH – 3.22.0

### Inactive Plugins (2) ###

WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
XStore AMP: by 8theme – 1.0.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: easy_product_bundle (easy_product_bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #2518 - /terms-of-use/

### Theme ###

Name: XStore Child
Version: 1.0
Author URL: http://8theme.com
Child Theme: ✔
Parent Theme Name: XStore
Parent Theme Version: 9.1.8
Parent Theme Author URL: http://www.8theme.com
WooCommerce Support: ✔

### Templates ###

Overrides: xstore/woocommerce/archive-product.php
xstore/woocommerce/cart/cart-empty.php
xstore/woocommerce/cart/cart-item-data.php
xstore/woocommerce/cart/cart-shipping.php
xstore/woocommerce/cart/cart.php
xstore/woocommerce/cart/cross-sells.php
xstore/woocommerce/cart/mini-cart.php
xstore/woocommerce/cart/proceed-to-checkout-button.php
xstore/woocommerce/checkout/form-billing.php
xstore/woocommerce/checkout/form-checkout.php
xstore/woocommerce/checkout/form-shipping.php
xstore/woocommerce/checkout/review-order.php
xstore/woocommerce/checkout/thankyou.php
xstore/woocommerce/content-product-cat.php
xstore/woocommerce/content-product.php
xstore/woocommerce/content-single-product.php
xstore/woocommerce/content-widget-product.php
xstore/woocommerce/content-widget-reviews.php
xstore/woocommerce/global/breadcrumb.php
xstore/woocommerce/global/form-login.php
xstore/woocommerce/global/wrapper-end.php
xstore/woocommerce/global/wrapper-start.php
xstore/woocommerce/loop/loop-end.php
xstore/woocommerce/loop/loop-start.php
xstore/woocommerce/loop/no-products-found.php
xstore/woocommerce/loop/result-count.php
xstore/woocommerce/myaccount/dashboard.php
xstore/woocommerce/myaccount/form-login.php
xstore/woocommerce/myaccount/navigation.php
xstore/woocommerce/single-product/add-to-cart/simple.php
xstore/woocommerce/single-product/meta.php
xstore/woocommerce/single-product/product-image.php
xstore/woocommerce/single-product/related.php
xstore/woocommerce/single-product/tabs/tabs.php
xstore/woocommerce/single-product/title.php
xstore/woocommerce/single-product/up-sells.php
xstore/woocommerce/single-product-reviews.php
xstore/woocommerce/single-product.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-07 10:10:44 -04:00
Options: ✔
Notes: 114
Onboarding: completed

### Action Scheduler ###

Complete: 7,639
Oldest: 2023-06-06 04:36:37 -0400
Newest: 2023-07-07 04:34:28 -0400

Failed: 16
Oldest: 2023-02-21 02:57:25 -0500
Newest: 2023-06-01 06:57:36 -0400

Pending: 18
Oldest: 2023-07-07 04:37:49 -0400
Newest: 2023-07-16 04:59:30 -0400

### Status report information ###

Generated at: 2023-07-07 04:36:42 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
This sounds related to https://github.com/woocommerce/woocommerce/issues/32816 

Can you please check your CSV and confirm if you see `<a>` tags there?
