### ISSUE TITLE
CSV importer doesn't work with product filter widget.

### ISSUE THREAD

**Issue by TZubiri** [woothemes/woocommerce#39158]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When one uses the built in csv import functionality, attributes can be specified, but they are not loaded correctly, they are loaded as "text". And typed attributes are not created.

This causes search widgets to not function.

### Expected behavior

Upon importing a csv with attributes, attributes should be created so that filter widgets can use them to filter.

Additionally, if filters are already created, importing should load them as typed attributes, not text attributes.

### Actual behavior

Attributes loaded as text. You can see the details on product pages, but not when using a filter widget.

### Steps to reproduce

1. create a csv with a couple of products and attributes.
2. load with csv import feature
3. Add a filter widget to the product catalogue page.
4. Filter won't appear because there are no attributes.
5. Manually add attributes through the Product>attributes page.
6. Manually add an attribute to a sample product, through the Products list.
7. Load more products through the importer again, and verify that the attributes that were loaded manually are not matched with the csv attributes.

### WordPress Environment

WooComerce 7.8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@TZubiri Can you provide a sample import CSV with the attribute properties you are using?

**Comment by TZubiri** [comment]
> @TZubiri Can you provide a sample import CSV with the attribute properties you are using?

[Uploading Woocommerce.xlsx…]()
