### ISSUE TITLE
[Enhancement] Do not show feedback prompts when the user dismisses them manually

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39167]
[Current product editor] We've received reports from unhappy users who keep seeing feedback prompts after dismissing them using the X button. Ideally, we'd respect that and stop showing product prompts altogether.

We show the notice when the user sees and chooses to ignore it. We've also heard from a user who noticed that the prompt keeps showing up even after it's manually dismissed, but we couldn't reproduce it.

**Steps to reproduce**

- Create a new Woo store or delete CES-related settings in the TH tool
- Go to Add product and enter product details
- Publish a product
- Notice a feedback prompt, but don't interact with it
- Add or change some product details and update
- See how the feedback prompt re-appears
- Repeat

**Acceptance criteria**

- [ ] We only show each feedback prompt once, no matter if the user interacts with it (clicks 'Share feedback' or the X button).
- [ ] We don't show feedback prompts when the user dismisses them using the X button or clicks the link to open the modal (they don't need to submit feedback).
- [ ] This only concerns specific site areas, e.g., product editing. When the user dismisses 1 snackbar while adding or editing a product, we shouldn't show them again the next time they visit the product editor. However, they'll see it when they update an order or settings.

**Comment by mattsherman** [comment]
The current implementation has the possibility to not mark the action as shown, which would result in the snackbar being re-shown. This is likely rare, but if the `recordEvent()` call in `onNoticeDismissed()` threw an error, the `addActionToShownOption()` call would not be made.

I suggest we wrap the `recordEvent()` call in a try/finally, calling the `addActionToShownOption()` in the finally.

https://github.com/woocommerce/woocommerce/blob/1cd947a32064bf3b716521110eae2856711ab775/packages/js/customer-effort-score/src/components/customer-effort-score-tracks/index.js#L105-L114

/cc @louwie17
