### ISSUE TITLE
[Enhancement]: Enable wc_checkout Terms section to be hookable

### ISSUE THREAD

**Issue by solaceten** [woothemes/woocommerce#39162]
### Describe the solution you'd like

I am not an expert, but came across this issue

In woocommerce checkout, it appears to be very difficult to move the terms and conditions entire div.  I had a need to move the entire div: woocommerce-terms-and-conditions-wrapper  to be above the Payment Method (wc_payment_methods payment_methods methods)

In doing so, I encountered a few odd things:

1) In terms.php there is 
@hooked wc_checkout_privacy_policy_text() Shows custom privacy policy text. Priority 20.
@hooked wc_terms_and_conditions_page_content() Shows t&c page content. Priority 30.

But there is no hook for the "I confirm" checkbox - so you can move the first two ok, but not easily move the checkbox that ordinarily should be together with the terms.

2) In the checkout Payment section, there is no hook for payment-methods.  While there is the following hook "woocommerce_review_order_before_payment" - that does not target just the methods.

I would like to propose a way to be able to move the entire terms section "div: woocommerce-terms-and-conditions-wrapper "

In the end I did it with jQuery, but it is messy.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help.

Our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility), and moving the Terms section is possible directly in the Block editor. 

We'll close the issue, as it doesn't fit our current priorities. We'll revisit the list of suggestions like this one once our priorities are updated. Don’t be alarmed if you don’t see any activity on this issue for a while.
