### ISSUE TITLE
[ Product Block Editor ] Add support for third-party plugin metaboxes/sidebars

### ISSUE THREAD

**Issue by arnaudbroes** [woothemes/woocommerce#39163]
### Describe the solution you'd like

The new Product Block Editor, which is currently in beta and still under development, does not support metaboxes and Block Editor sidebars from third-party plugins like All in One SEO (AIOSEO) at all.

Are there any plans for the team to add support for these inside your custom editor?

**Comment by pmcpinto** [comment]
Hey @arnaudbroes, thank you for taking the time to create this issue. We appreciate your help. 

The team is exploring the best ways to add extensibility support to the new product creation experience. See this post in the WooCommerce Developer blog and feel free to add your feedback/comments: https://developer.woocommerce.com/2023/06/28/introducing-a-brand-new-product-creation-experience-powered-by-blocks/
