### ISSUE TITLE
Issue while adding product to cart using ajax

### ISSUE THREAD

**Issue by ankitlogicsofts** [woothemes/woocommerce#39174]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi There,

I am using WC()->cart->add_to_cart function to add product to the cart using ajax like this 

WC()->cart->add_to_cart($productid, $productquantity, $proddata['variationid'], array(
'attribute_type' => 'Square',
), $cartcustomdata);

This code is working fine for PHP 7.4 but not working on PHP 8.0 and above and also works when there is any item in the cart. But not working when I am adding this product as the first item in the cart.

My variation has 'any' selected in the admin area but when I change it to any fixed attribute like Oval my code is working fine. 

I need this code to also work when 'any' is selected in the admin area

### Expected behavior

I need this code to also work when 'any' is selected in the admin area

### Actual behavior

This code is working fine for PHP 7.4 but not working on PHP 8.0 and above and also works when there is any item in the cart. But not working when I am adding this product as the first item in the cart.

My variation has 'any' selected in the admin area but when I change it to any fixed attribute like Oval my code is working fine. 

### Steps to reproduce

[https://drive.google.com/file/d/13vOi_ip3grfGCfIT2JSlUweYnTfBbgej/view?usp=sharing](url)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
@ankitlogicsofts the link for the testing steps is an image. Could you share some detailed testing steps?

**Comment by ralucaStan** [comment]
I will close this issue as there has been no answer since August.
