### ISSUE TITLE
[Enhancement]: wp cli command to reset all woocommerce stored data (orders, coupons, comments, etc.)

### ISSUE THREAD

**Issue by rwkyyy** [woothemes/woocommerce#39170]
### Describe the solution you'd like

As the title suggests, it would be nice to have a one-stop-shop command in cli that would clean woocommerce of all the following data:
- orders (post type)
- orders meta-data (wp_postmeta)
- order comments (wp_comments)
- order analytics (separate multiple tables)
- users (just customer role type)
- user metadata (orphaned)
- coupons
- probabbly more, can't remember them all.

Right now if you want to clean them, you have to do a lot of work and go back and forth through SQLs and CLIs to clean the them

### Describe alternatives you've considered

multiple manual CLIs or SQLs

### Additional context

I had to duplicate a store as the client is preparing to launch for another country/market; solutions like wpml/similar + currency switchers were not a desired solution; this is not my first experience, in all the times the products and pages stay, just the order data is getting removed.

**Comment by rrennick** [comment]
@rwkyyy This tool sounds like a great idea for developers working on development/testing sites. But it isn't something that a merchant would need for a live shop. Including it in WooCommerce could have negative consequences for some live shops. Instead this tool should be written as a separate plugin. I'll close the issue.
