### ISSUE TITLE
Unable to login at first attempt for new user (second attempt is successful)

### ISSUE THREAD

**Issue by viktorvanecek** [woothemes/woocommerce#39185]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi

I am testing login process on my website on which the user is created after ordering a membership. After the order is completed I (as a customer) receive the email with link to reset the password. After the password is set to new one I should be able to login with the password I just created, but after I press the login button (register button in the video) I end up at the same page again with no error messages and only after second attempt I am able to login.

I also created a video about this issue.

[`https://issue-4.wistia.com/medias/7eh9nz4ix1`](https://issue-4.wistia.com/medias/7eh9nz4ix1)

After 2 days of trial and error I have found, someone here on github with exactly the same problem, but this thread is already closed so I created new one. I tried to implement the code from this thread to class-wc-form-handler.php but the problem still persists. Either I do something wrong or the code is outdated somehow.

https://github.com/woocommerce/woocommerce/issues/34127

Does anybody know how to resolve this issue?

### Expected behavior

I want to accomplish the customer can login to the website at first try directly after he successfully reseted the password and after the login he is redirected to the "my account" page.

### Actual behavior

After setting the new password and opening the login page, I am unable to login at first try. There are no error messages, the login page do nothing after I press the login button. Only after I fill the email and password again, Im finnaly redirected to the "my account" page. So its working at second try.

### Steps to reproduce

The issue can be seen in this video [https://issue-4.wistia.com/medias/7eh9nz4ix1](url)

### WordPress Environment

`
`
### WordPress Environment ###

WordPress address (URL): https://www.handrailab.com
Site address (URL): https://www.handrailab.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 10.3.7-MariaDB-1:10.3.7+maria~xenial-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: srjlnh_
Total Database Size: 26.51MB
Database Data Size: 24.07MB
Database Index Size: 2.44MB
srjlnh_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
srjlnh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
srjlnh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
srjlnh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
srjlnh_ewwwio_images: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
srjlnh_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_options: Data: 3.42MB + Index: 0.06MB + Engine InnoDB
srjlnh_postmeta: Data: 3.52MB + Index: 0.14MB + Engine InnoDB
srjlnh_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
srjlnh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_usermeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
srjlnh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
srjlnh_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
srjlnh_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
srjlnh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
srjlnh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
srjlnh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
srjlnh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
srjlnh_wfconfig: Data: 1.34MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfhits: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
srjlnh_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
srjlnh_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
srjlnh_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wflogins: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
srjlnh_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
srjlnh_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
srjlnh_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
srjlnh_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
srjlnh_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
srjlnh_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
srjlnh_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
srjlnh_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
srjlnh_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
srjlnh_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 31
ct_template: 2
page: 8
post: 13
product: 1
revision: 17
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

BBQ Firewall: by Jeff Starr – 20230303
EWWW Image Optimizer: by Exactly WWW – 7.1.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.17
Loco Translate: by Tim Whitlock – 2.6.4
MyThemeShop Theme & Plugin Updater: by MyThemeShop – 3.0.7
Oxygen Elements for WooCommerce: by Soflyy – 2.0
Oxygen: by Soflyy – 4.6.2
Recoda Workspace: by Renato Corluka – 0.9.8 P1
SVG Support: by Benbodhi – 2.5.5
WooCommerce: by Automattic – 7.8.2
Wordfence Security: by Wordfence – 7.10.0
Yoast SEO: by Tím Yoast – 20.11
WP Review Pro: by MyThemeShop – 3.4.5

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0
DCO Comment Attachment: by Denis Yanchevskiy – 2.4.0
W3 Total Cache: by BoldGrid – 2.2.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #14 - /obchod/
Cart: #15 - /kosik/
Checkout: #16 - /kontrola-objednavky/
My account: #17 - /moj-ucet/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Refur
Version: 1.1.0
Author URL: https://crocoblock.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-12 15:06:14 +02:00
Options: ✔
Notes: 106
Onboarding: skipped

### Action Scheduler ###

Complete: 48
Oldest: 2023-06-11 17:05:02 +0200
Newest: 2023-07-11 18:09:28 +0200

Pending: 1
Oldest: 2023-07-12 13:04:44 +0200
Newest: 2023-07-12 13:04:44 +0200

### Status report information ###

Generated at: 2023-07-11 18:48:05 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by SavPhill** [comment]
@viktorvanecek Does the bug occur with a default WordPress theme or Storefront theme?
Also, there's no video in the link you provided.

**Comment by viktorvanecek** [comment]
> 

I have fixed the link and it should be correct now. https://issue-4.wistia.com/medias/7eh9nz4ix1
I am using oxygen builder so dont have any theme

**Comment by bogdanarizancu** [comment]
Hi, @SavPhill! I also tested this with  WooCommerce version 7.9.0 on the Storefront theme on my local, please check my screencast below

https://github.com/woocommerce/woocommerce/assets/11241985/c2dd1718-8944-414c-b439-cba919ac779d

### WordPress Environment ###

WordPress address (URL): https://test-shop.test
Site address (URL): https://test-shop.test
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.1
PHP Version: 8.0.29
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.1.2
(SecureTransport) OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 5.23MB
Database Data Size: 3.57MB
Database Index Size: 1.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce: by Automattic – 7.9.0
WP Mail SMTP: by WP Mail SMTP – 3.8.0
WPForms Lite: by WPForms – 1.8.2.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.4.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-19 08:10:16 +00:00
Options: ✔
Notes: 66
Onboarding: skipped

### Action Scheduler ###

Complete: 11
Oldest: 2023-07-18 08:11:18 +0000
Newest: 2023-07-18 21:01:01 +0000

Failed: 1
Oldest: 2023-07-18 08:11:42 +0000
Newest: 2023-07-18 08:11:42 +0000

Pending: 4
Oldest: 2023-07-19 08:11:18 +0000
Newest: 2023-07-24 14:00:00 +0000


### Status report information ###

Generated at: 2023-07-18 21:09:25 +00:00

**Comment by rrennick** [comment]
@bogdanarizancu Thanks for creating the issue. I didn't realize I had accidentally closed that issue I have re-opened it and will close this one as a duplicate.
