### ISSUE TITLE
MONOREPO_ROOT should be removed from the monorepo CLI tools package in prep to package it for release to other teams.

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#39192]
**Issue Description:**

The [monorepo utils CLI tools](https://github.com/woocommerce/woocommerce/blob/714e50bf4c26156e487f48447a119df7d89a1ff8/tools/monorepo-utils) will eventually need to be release on npm and the assumption that it always runs from monorepo root will no longer hold. We need to remove references to MONOREPO_ROOT from the tool and test that it can be run from any project.

**Comment by rrennick** [comment]
> We need to remove references to MONOREPO_ROOT from the tool and test that it can be run from any project.

I checked both of these and they have been addressed.
