### ISSUE TITLE
Add *.md linting to enforce style guide for docs

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#39202]
### Describe the solution you'd like

In https://github.com/woocommerce/woocommerce/pull/39176#issuecomment-1632451111, @nerrad suggested adding *.md linting to the Woo core repo so that we can enforce the style guide for docs as described in [Technical documentation style guide](https://github.com/woocommerce/woodocs/blob/trunk/style-guide.md) and [WooCommerce grammar, punctuation and capitalization guide](https://github.com/woocommerce/woodocs/blob/trunk/code-quality-and-best-practices/grammar-punctuation-capitalization.md).

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by samueljseay** [comment]
Finished in https://github.com/woocommerce/woocommerce/pull/39707
