### ISSUE TITLE
[Enhancement] Show the additional comment field for all sentiments in the feedback form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39201]
We don't show the comment input field when the user selects a positive sentiment. We made this decision a while ago but realized it prevents us from collecting positive feedback, which is as important as the negative one.

**Design**

`lj4AUMJnpMtUe7XqyvOONq-fi-1334-117723&mode=design&t=Y6uvHEmT8qWb0lmk-4`

<img width="751" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/8d7d1bfa-6435-4f88-aa50-dac0283d5734">

**Acceptance criteria**

- [ ] We show the `Additional thoughts (optional)` and the email fields no matter the selected sentiment.
- [ ] The fields are not visible until at least one sentiment is selected.
- [ ] This change impacts all feedback forms we use in the experience, e.g., those triggered in settings, orders, products, etc.

**Comment by mattsherman** [comment]
Already implemented
