### ISSUE TITLE
wocommerce product shipping issue

### ISSUE THREAD

**Issue by aliasgar2811** [woothemes/woocommerce#39218]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
i have added shipping options to my store i,e flat rate, but will all my product, +free sheeping is coming near their price. i dont know how to solve it. please check th image, i wanna remove this +free sheeping
![Capture66](https://github.com/woocommerce/woocommerce/assets/139467346/2674b23c-bbcb-4af1-8a7b-46f7d9906704)

**Comment by SavPhill** [comment]
@aliasgar2811 This appears to be more of a theme/conflict issue or support request. Have you tried switching to Storefront or a Default WordPress theme to see if the issue still occurs?

You can try posting on the WooCommerce Support Forum and close the issue if it is resolved: https://wordpress.org/support/plugin/woocommerce/
