### ISSUE TITLE
[Fix] Remove backdrop-filter from the feedback bar in the product form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39220]
As introduced a translucent background to the feedback bar in the product form as part of https://github.com/woocommerce/woocommerce/pull/39055. It made sense at the time, but now I see that it stands apart from the rest of the design language and should be replaced with a solid white background.

cc @mdperez86 

**Acceptance criteria**

- [ ] The feedback bar has a solid white background without additional CSS props.

**Comment by mattsherman** [comment]
Already implemented.
