### ISSUE TITLE
Woocommerce cart and deprecated function error

### ISSUE THREAD

**Issue by REDITADO** [woothemes/woocommerce#39236]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i'm using the latest avalible stable woocommerce in my wordpress project and this versiong is generatin an error in elementor pro and in cart with  deprecated function issue
![WhatsApp Image 2023-07-13 at 16 25 22](https://github.com/woocommerce/woocommerce/assets/56317476/473f3458-8494-4a50-9a33-76de18b942c2)

### Expected behavior

an correction

### Actual behavior

Actually nothing

### Steps to reproduce

Install the last  estable version of woocommerce 

### WordPress Environment

6.2.2

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@REDITADO Thanks for reporting the issue. This had already been reported and was addressed in #38008.
