### ISSUE TITLE
High Memory and CPU consumption in Woocommerce

### ISSUE THREAD

**Issue by no7r3k** [woothemes/woocommerce#39247]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I manage multiple WooCommerce sites hosted on different providers with shared hosting plans. Whenever I access the WooCommerce Dashboard or update orders, all of them experience high CPU and memory usage. This issue persists regardless of the WordPress themes or plugins being used.

When only WooCommerce is activated, the CloudLinux LVE parameters reach 100% usage, causing significant disruption. By inspecting the Dev Tools console at the following address: ../wp-admin/admin.php?page=wc-admin, I noticed numerous simultaneous requests, such as /wp-json/jetpack/* or /wp-json/wc-admin/*, which take more than 15 seconds to load.

Here is a screenshot: https://prnt.sc/_wFPReF6-RkL

This excessive resource consumption ultimately leads to some requests receiving an Internal Server Error 500.

To investigate this matter further, I conducted tests on fresh WordPress installations with only WooCommerce and without any additional plugins. I used the default WordPress theme, and there were no search engine indexing bots or regular visitors to the site. Surprisingly, even with a shared hosting plan offering 2.5 GB of memory, which should be sufficient, the issue persisted.

I observed this situation on WordPress core version 6.2.2 and WooCommerce version 7.8 or older, despite having the latest updates. 

Although the situation improves slightly with older versions, such as WordPress core 5.8.7 and WooCommerce 5.9.1, it is crucial for us to use the latest versions, right?

I would greatly appreciate it if we have a better explanation of why the plugin requires such significant memory resources to navigate the Dashboard in the newer versions, and offer guidance on how to address this issue. Could WooCommerce even function properly on shared hosting anymore, and what are the recommended server requirements in terms of memory and CPU cores?

Additionally, do we have any bug reports regarding memory leaks, and if so, are you actively working on resolving them, as I haven't found such queries?

Please keep in mind that I conducted these tests on fresh installations without any activated plugins, using the default WP themes (2023), and a perfectly functional hosting server. The tests are conducted on multiple hosting providers and the results are comparable. 

### Expected behavior

For an empty WordPress + WooCommerce configuration, we expect minimal memory and CPU usage overall.

### Actual behavior

When we set up a new and empty WooCommerce instance, tested on various hosting providers and environments, we notice elevated memory and CPU consumption. Additionally, approximately 10 PHP processes are created, each consuming around 150MB.

### Steps to reproduce

1. Install WordPress + WooCommerce.
2. Access the dashboard.
3. Open the Dev Tools console to observe the requests and monitor the hosting environment's load.

### WordPress Environment

WordPress Environment

WordPress address (URL): https://wptest.fatanasov.tk
Site address (URL): https://wptest.fatanasov.tk
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

Server Environment

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 8.1.2
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.14-MariaDB-log
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Database

WC Database Version: 7.8.0
WC Database Prefix: wpzz_
Total Database Size: 3.61MB
Database Data Size: 3.27MB
Database Index Size: 0.34MB
wpzz_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpzz_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_gla_budget_recommendations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
wpzz_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automation_runs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automation_run_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automation_run_subjects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automation_triggers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_automation_versions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_mailpoet_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_scheduled_tasks: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_subscribers: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpzz_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_subscriber_tag: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_options: Data: 2.07MB + Index: 0.04MB + Engine MyISAM
wpzz_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpzz_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpzz_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzz_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzz_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

Post Type Counts

attachment: 1
mailpoet_page: 1
page: 7
post: 2

Security

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

Active Plugins (1)

WooCommerce: by Automattic – 7.8.0

Inactive Plugins (6)

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Google Listings and Ads: by WooCommerce – 2.4.10
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet: by MailPoet – 4.18.1
Pinterest for WooCommerce: by WooCommerce – 1.3.3
WooCommerce Payments: by Automattic – 6.0.0

Settings

API Enabled: –
Force SSL: –
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator:
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

WC Pages

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

Theme

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

Templates

Overrides: –

Admin

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-20 10:21:29 +00:00
Options: ✔
Notes: 57
Onboarding: completed

Action Scheduler

Complete: 10
Oldest: 2023-06-19 10:22:29 +0000
Newest: 2023-06-19 10:52:05 +0000

Failed: 1
Oldest: 2023-06-19 11:23:32 +0000
Newest: 2023-06-19 11:23:32 +0000

Pending: 3
Oldest: 2023-06-19 12:23:32 +0000
Newest: 2023-06-20 10:23:32 +0000

Status report information

Generated at: 2023-06-19 11:30:56 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by BluByte** [comment]
Same problem here.
Fresh WC installation. No products, no orders, no sells, no plugins. Storefront Theme.
Vultr HF VPS.
WC dashboard takes ages to load and consume the FULL cpu (and memory).
Moving to 2 core CPU and 4GB RAM VPS (a bit overkill for an empty store, right?) makes things a bit faster.

All the asynchronous information loaded in the WC dashboard takes ages sto be loaded.
SQL queries are fast and these are not the problem.

**Comment by rrennick** [comment]
Hi @no7r3k @BluByte , I suggest you join the [Community Slack](https://woocommerce.com/community-slack/) and ask about the hosts in question. There may be some configuration settings, etc. that are causing the resource consumption you are describing. I'm marking this issue as a support request as you haven't identified a specific issue that we could look at.
