### ISSUE TITLE
Coupon discount on sort_by_price is sorting high to low rather than low to high

### ISSUE THREAD

**Issue by mhodge** [woothemes/woocommerce#39248]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When applying discounts to items in the cart using coupons the logic currently is sorting price high to low rather than low to high

If we were to apply a 30% discount with a usage limit of 1 for example to an item in the cart, as a store owner I would like the 30% discount applied to the item with the least cost and not the current implementation as it applies the discount to the highest cost.

My suggestion would be to alter the sort_by_price function inside the woocommerce/includes/class-wc-discounts.php class 

CURRENT:
```
	/**
	 * Sort by price.
	 *
	 * @since  3.2.0
	 * @param  array $a First element.
	 * @param  array $b Second element.
	 * @return int
	 */
	protected function sort_by_price( $a, $b ) {
		$price_1 = $a->price * $a->quantity;
		$price_2 = $b->price * $b->quantity;
		if ( $price_1 === $price_2 ) {
			return 0;
		}
		return ( $price_1 < $price_2 ) ? 1 : -1;
	}
```

SUGGESTION:
```
	/**
	 * Sort by price.
	 *
	 * @since  3.2.0
	 * @param  array $a First element.
	 * @param  array $b Second element.
	 * @return int
	 */
	protected function sort_by_price( $a, $b ) {
		$price_1 = $a->price * $a->quantity;
		$price_2 = $b->price * $b->quantity;
		if ( $price_1 === $price_2 ) {
			return 0;
		}
		return ( $price_1 < $price_2 ) ? -1 : 1;
	}
```

The logic on the return should be altered

### Expected behavior

I would expect the coupon discount would apply to the product with the smallest price so as to save the store owner monies regarding discounts

### Actual behavior

It currently is applying the discount to the most expensive item resulting in less revenue for the store owner

### Steps to reproduce

1. Add a coupon with 30% discount, limit this coupon to items in a woocommerce product category with a usage limit of 1
2. Add two different products to the cart (belonging to the assigned product category for the coupon) one with a higher pricing than than that other
3. Proceed to checkout and a apply the coupon and the 30% will apply to the product with the larger price
4. Alter the order of the items in the cart by removing the products and adding them back in a different order than step 2
5. Proceed to the checkout and apply the coupon and the 30% still applies to the product with the larger price

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://domain.local
Site address (URL): https://domain.local
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.0.1 - There is a newer version of WordPress available (6.2.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_ZA
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.0
PHP Version: 7.4.30
PHP Post Max Size: 40 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.22-log
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: fl_
Total Database Size: 79.65MB
Database Data Size: 70.30MB
Database Index Size: 9.35MB
fl_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
fl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fl_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_actionscheduler_actions: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
fl_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_actionscheduler_logs: Data: 0.41MB + Index: 0.33MB + Engine InnoDB
fl_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fl_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
fl_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
fl_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
fl_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
fl_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
fl_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
fl_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fl_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
fl_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_options: Data: 6.08MB + Index: 0.36MB + Engine InnoDB
fl_postmeta: Data: 23.55MB + Index: 3.03MB + Engine InnoDB
fl_posts: Data: 32.52MB + Index: 0.56MB + Engine InnoDB
fl_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_sbi_feed_caches: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
fl_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_sbi_instagram_posts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
fl_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_termmeta: Data: 0.09MB + Index: 0.19MB + Engine InnoDB
fl_terms: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
fl_term_relationships: Data: 0.30MB + Index: 0.20MB + Engine InnoDB
fl_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
fl_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
fl_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
fl_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
fl_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fl_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_wc_product_attributes_lookup: Data: 0.34MB + Index: 0.38MB + Engine InnoDB
fl_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
fl_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fl_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_yoast_indexable: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
fl_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fl_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fl_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fl_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1127
customize_changeset: 8
elementor_icons: 2
elementor_library: 10
mailpoet_page: 1
makeup: 1
member: 3
nav_menu_item: 121
page: 32
popup: 2
popup_theme: 8
porto_builder: 8
post: 6
product: 307
product_variation: 112
revision: 974
shop_coupon: 1
shop_order: 8
whatsapp-accounts: 3
wp_global_styles: 1
yith_wcan_preset: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Gravity Forms: by Gravity Forms – 2.6.3
Akismet Anti-Spam: by Automattic – 5.0
Elementor Pro: by Elementor.com – 3.7.1
Elementor Product Attribute: by Flicker Leap – 1.0.0
Elementor: by Elementor.com – 3.6.5
Google Listings and Ads: by WooCommerce – 1.13.6
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.1
Instagram Feed Pro Business: by Smash Balloon – 6.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.6.2
Payflex Payment Gateway: by Payflex – 2.3.7
Perfect Brands for WooCommerce: by QuadLayers – 2.1.5
Porto Theme - Functionality: by P-Themes – 2.4.1
WhatsApp Chat by NinjaTeam: by NinjaTeam – 3.1.8
Additional Variation Images Gallery for WooCommerce - Pro: by Emran Ahmed – 1.3.5
WooCommerce PayFast Gateway: by WooCommerce – 1.4.22
WooCommerce: by Automattic – 6.5.1
Yoast SEO: by Team Yoast – 19.4
YITH WooCommerce Wishlist: by YITH – 3.9.0

### Inactive Plugins (6) ###

Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.3.7
Popup Maker: by Popup Maker – 1.16.7
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.1
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.1
WP All Import Pro: by Soflyy – 4.7.3
YITH WooCommerce Ajax Product Filter: by YITH – 4.10.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop
Basket: #8 - /cart
Checkout: #9 - /checkout
My account: #10 - /my-account
Terms and conditions: #1817 - /terms-of-use

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 6.4.1
Parent Theme Author URL: https://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto-child/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details-customer.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 1,690
Oldest: 2022-07-12 14:54:35 +0200
Newest: 2022-07-28 09:11:10 +0200

Pending: 3
Oldest: 2022-07-29 08:52:45 +0200
Newest: 2022-09-21 10:55:34 +0200

### Status report information ###

Generated at: 2023-07-14 11:30:21 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> If we were to apply a 30% discount with a usage limit of 1 for example to an item in the cart

@mhodge The usage limit on coupons is for the number of orders not products. Coupons do allow you to limit them to specific products and customers can add more that one coupon to an order. You may be able to use those setting to achieve your goal. I'll close this as a support question.
