### ISSUE TITLE
Fatal error when importing products, solved easily by additional if check.

### ISSUE THREAD

**Issue by gdarko** [woothemes/woocommerce#39262]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Fatal error happened when importing products. Easily fixed by adding `is_countable()` check.

### Expected behavior

No errors should be thrown

### Actual behavior

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/app/current/web/app/plugins/woocommerce/includes/admin/class-wc-admin-importers.php:297
Stack trace:
#0 /var/app/current/web/wp/wp-includes/class-wp-hook.php(308): WC_Admin_Importers->do_ajax_product_import('')
#1 /var/app/current/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /var/app/current/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /var/app/current/web/wp/wp-admin/admin-ajax.php(188): do_action('wp_ajax_woocomm...')
#4 {main}
  thrown in /var/app/current/web/app/plugins/woocommerce/includes/admin/class-wc-admin-importers.php on line 297

### Steps to reproduce

Not easy to reproduce, if you need help contact me at dg@darkog.com. However the error should be obvious, you shouldn't use count() without checking if it is of type Countable / is_countable / is_array.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://site.com/wp
Site address (URL): https://site.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ❌ To allow logging
make /var/app/current/web/app/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 6.2.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 8.1.20
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 8.0.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 8.0.23
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 28145.72MB
Database Data Size: 7322.74MB
Database Index Size: 20822.98MB
wp_woocommerce_sessions: Data: 267.47MB + Index: 11.38MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 112.66MB + Index: 168.94MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2691.00MB + Index: 3837.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 14.55MB + Index: 16.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 8.52MB + Index: 6.86MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.52MB + Index: 7.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aws_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 141.69MB + Index: 141.39MB + Engine InnoDB
wp_comments: Data: 380.00MB + Index: 470.42MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 13.47MB + Index: 0.30MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_postmeta: Data: 2576.00MB + Index: 15053.86MB + Engine InnoDB
wp_posts: Data: 183.73MB + Index: 275.17MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.47MB + Index: 1.27MB + Engine InnoDB
wp_term_taxonomy: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_termmeta: Data: 0.16MB + Index: 0.33MB + Engine InnoDB
wp_terms: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_tinvwl_analytics: Data: 75.73MB + Index: 57.77MB + Engine InnoDB
wp_tinvwl_items: Data: 71.61MB + Index: 72.19MB + Engine InnoDB
wp_tinvwl_lists: Data: 9.52MB + Index: 7.52MB + Engine InnoDB
wp_usermeta: Data: 383.94MB + Index: 330.92MB + Engine InnoDB
wp_users: Data: 15.55MB + Index: 15.55MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 20.55MB + Index: 16.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 151.70MB + Index: 161.38MB + Engine InnoDB
wp_wc_order_stats: Data: 35.58MB + Index: 37.09MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 7.52MB + Index: 6.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 2.09MB + Index: 1.22MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.38MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 11.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.48MB + Index: 0.14MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfnotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.39MB + Index: 0.20MB + Engine InnoDB
wp_wftrafficrates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 91.64MB + Index: 97.44MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 6.52MB + Index: 8.55MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_yoast_seo_links: Data: 2.52MB + Index: 1.98MB + Engine InnoDB
wp_yoast_seo_meta: Data: 8.52MB + Index: 3.52MB + Engine InnoDB

### Post Type Counts ###

acf-field: 51
acf-field-group: 10
afterpay_quote: 29
aiosrs-schema: 3
attachment: 11977
banner: 1
custom_css: 1
nav_menu_item: 78
oembed_cache: 2
page: 13
post: 2
product: 882
product_variation: 6
revision: 441
shop_coupon: 442338
shop_order: 320611
shop_order_refund: 8043
user_request: 1
wpcf7_contact_form: 1
wp_global_styles: 1
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (54) ###

Afterpay Gateway for WooCommerce: by Afterpay – 3.5.3
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.4.0
GTM4WP: by Thomas Geiger – 1.16.2
Klaviyo: by Klaviyo
Inc. – 3.0.10

PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.438

Simple Page Ordering: by 10up – 2.4.4
TI WooCommerce Wishlist: by TemplateInvaders – 2.3.6
WooCommerce Address Book: by CrossPeak – 2.4.1
Product Feed PRO for WooCommerce: by AdTribes.io – 12.4.9
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.8.1 (update to version 3.9.3 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.8.0 (update to version 2.3.1 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.3.2 (update to version 3.5.0 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.5.1 (update to version 4.7.1 is available)
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.6 (update to version 4.3.7 is available)
WooCommerce: by Automattic – 7.8.2
WP Search with Algolia: by WebDevStudios – 2.3.1
YITH PayPal Express Checkout for WooCommerce: by YITH – 1.24.0
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.21.0
YITH WooCommerce Points and Rewards Premium: by YITH – 3.19.0
WooCommerce: by Automattic – 7.8.2
Soil: by Roots – 4.1.1
The SEO Framework: by The SEO Framework Team – 4.2.8
Safe Redirect Manager: by 10up – 1.11.1

### Dropin Plugins (1) ###

db.php: LudicrousDB (Database)

### Must Use Plugins (14) ###

app.php: by  –
Bedrock Autoloader: by Roots – 1.0.3
blog-images.php: by  –
comments.php: by  –
development-media.php: by  –
Disable Attachment Pages: by Greg Schoppe – 1.0.0
endpoint-customer-validate.php: by  –
helpers.php: by  –
php-deprecation-errors.php: by  –
redirects.php: by  –
search.php: by  –
seo.php: by  –
site-icon.php: by  –
user-fields.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Mira Suite
Version: (update to version 0 is available)
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: mira-suite/resources/views/woocommerce/archive-product.blade.php version - is out of date. The core version is 3.4.0
mira-suite/resources/views/woocommerce/cart/cart-empty.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/cart/cart-shipping.blade.php version - is out of date. The core version is 7.3.0
mira-suite/resources/views/woocommerce/cart/cart-totals.blade.php version - is out of date. The core version is 2.3.6
mira-suite/resources/views/woocommerce/cart/cart.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/cart/proceed-to-checkout-button.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/checkout/form-billing.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/checkout/form-checkout.blade.php version - is out of date. The core version is 3.5.0
mira-suite/resources/views/woocommerce/checkout/form-login.blade.php version - is out of date. The core version is 3.8.0
mira-suite/resources/views/woocommerce/checkout/form-shipping.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/checkout/payment.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/checkout/review-order.blade.php version - is out of date. The core version is 5.2.0
mira-suite/resources/views/woocommerce/checkout/thankyou.blade.php version - is out of date. The core version is 3.7.0
mira-suite/resources/views/woocommerce/content-product.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/content-single-product.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/emails/email-footer.blade.php version - is out of date. The core version is 7.4.0
mira-suite/resources/views/woocommerce/emails/email-header.blade.php version - is out of date. The core version is 7.4.0
mira-suite/resources/views/woocommerce/global/breadcrumb.blade.php version - is out of date. The core version is 2.3.0
mira-suite/resources/views/woocommerce/loop/add-to-cart.blade.php version - is out of date. The core version is 3.3.0
mira-suite/resources/views/woocommerce/loop/orderby.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/loop/pagination.blade.php version - is out of date. The core version is 3.3.1
mira-suite/resources/views/woocommerce/loop/price.blade.php version - is out of date. The core version is 1.6.4
mira-suite/resources/views/woocommerce/myaccount/dashboard.blade.php version - is out of date. The core version is 4.4.0
mira-suite/resources/views/woocommerce/myaccount/form-add-payment-method.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/myaccount/form-edit-account.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/myaccount/form-edit-address.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/myaccount/form-login.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/myaccount/form-lost-password.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/myaccount/my-account.blade.php version - is out of date. The core version is 3.5.0
mira-suite/resources/views/woocommerce/myaccount/my-address.blade.php version - is out of date. The core version is 2.6.0
mira-suite/resources/views/woocommerce/myaccount/navigation.blade.php version - is out of date. The core version is 2.6.0
mira-suite/resources/views/woocommerce/myaccount/orders.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/myaccount/payment-methods.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/myaccount/view-order.blade.php version - is out of date. The core version is 3.0.0
mira-suite/resources/views/woocommerce/notices/error.blade.php version - is out of date. The core version is 3.9.0
mira-suite/resources/views/woocommerce/notices/notice.blade.php version - is out of date. The core version is 3.9.0
mira-suite/resources/views/woocommerce/notices/success.blade.php version - is out of date. The core version is 3.9.0
mira-suite/resources/views/woocommerce/single-product/add-to-cart/simple.blade.php version - is out of date. The core version is 7.0.1
mira-suite/resources/views/woocommerce/single-product/price.blade.php version - is out of date. The core version is 3.0.0
mira-suite/resources/views/woocommerce/single-product/product-attributes.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/single-product/product-image.blade.php version - is out of date. The core version is 7.8.0
mira-suite/resources/views/woocommerce/single-product/rating.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/single-product/review-meta.blade.php version - is out of date. The core version is 3.4.0
mira-suite/resources/views/woocommerce/single-product/review-rating.blade.php version - is out of date. The core version is 3.6.0
mira-suite/resources/views/woocommerce/single-product/review.blade.php version - is out of date. The core version is 2.6.0
mira-suite/resources/views/woocommerce/single-product/short-description.blade.php version - is out of date. The core version is 3.3.0
mira-suite/resources/views/woocommerce/single-product/tabs/description.blade.php version - is out of date. The core version is 2.0.0
mira-suite/resources/views/woocommerce/single-product/tabs/tabs.blade.php version - is out of date. The core version is 3.8.0
mira-suite/resources/views/woocommerce/single-product/title.blade.php version - is out of date. The core version is 1.6.4
mira-suite/resources/views/woocommerce/single-product-reviews.blade.php version - is out of date. The core version is 4.3.0
mira-suite/resources/views/woocommerce/single-product.blade.php
mira-suite/resources/views/woocommerce/taxonomy-product-cat.blade.php version - is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### Pimwick Plugins ###

PW WooCommerce Gift Cards Pro: License key: PW-5e091ed020e73
Result: success
Cached: 2023-07-14

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-15 17:03:30 -07:00
Options: ✔
Notes: 32
Onboarding: completed

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ✔

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2,797
Oldest: 2023-07-02 12:58:13 -0700
Newest: 2023-07-14 15:54:49 -0700

Failed: 17,897
Oldest: 2022-03-31 10:09:19 -0700
Newest: 2023-07-14 15:54:49 -0700

Pending: 4
Oldest: 2023-07-15 15:54:49 -0700
Newest: 2023-07-15 15:54:49 -0700

### Status report information ###

Generated at: 2023-07-14 16:06:08 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Not easy to reproduce, if you need help contact me at [dg@darkog.com](mailto:dg@darkog.com).

@gdarko Thanks for creating the issue. Could you provide a sample CSV that produces this error?
