### ISSUE TITLE
class-wc-bookings-calendar.php: Uncaught Error: Call to a member function get_order_id() on null

### ISSUE THREAD

**Issue by BT-Webdesign** [woothemes/woocommerce#39264]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am in "Bookings Calendar View" in the month view and want to see the next month. The next month is not displayed, I get an error message: 

"There has been a critical error on this website. Please check your site admin email inbox for instructions."

Wordpress Debug.log:

[16-Jul-2023 08:56:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_order_id() on null in /www/htdocs/w01cd789/stay-bonny.com/wp-content/plugins/woocommerce-bookings/includes/admin/class-wc-bookings-calendar.php:333
Stack trace:
#0 /www/htdocs/w01cd789/stay-bonny.com/wp-content/plugins/woocommerce-bookings/includes/admin/views/html-calendar-month.php(83): WC_Bookings_Calendar->list_bookings('01', '08', '2023')
#1 /www/htdocs/w01cd789/stay-bonny.com/wp-content/plugins/woocommerce-bookings/includes/admin/class-wc-bookings-calendar.php(164): include('/www/htdocs/w01...')
#2 /www/htdocs/w01cd789/stay-bonny.com/wp-content/plugins/woocommerce-bookings/includes/admin/class-wc-bookings-menus.php(201): WC_Bookings_Calendar->output()
#3 /www/htdocs/w01cd789/stay-bonny.com/wp-includes/class-wp-hook.php(308): WC_Bookings_Menus->calendar_page('')
#4 /www/htdocs/w01cd789/stay-bonny.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /www/htdocs/w01cd789/stay-bonny.com/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /www/htdocs/w01cd789/stay-bonny.com/wp-admin/admin.php(259): do_action('wc_booking_page...')
#7 /www/htdocs/w01cd789/stay-bonny.com/wp-admin/edit.php(10): require_once('/www/htdocs/w01...')
#8 {main}
  thrown in /www/htdocs/w01cd789/stay-bonny.com/wp-content/plugins/woocommerce-bookings/includes/admin/class-wc-bookings-calendar.php on line 333

### Expected behavior

The monthly overview should appear.

### Actual behavior

The month that is not displayed under "Bookings Calendar View" starts with an appointment that is entered in Google Calendar.

### Steps to reproduce

![Error Woo Booking 20230716](https://github.com/woocommerce/woocommerce/assets/139679518/c16a08f6-093b-48fd-9523-4cdd74f08659)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://stay-bonny.com
Site address (URL): https://stay-bonny.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.5.19-MariaDB-1:10.5.19+maria~ubu2004-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: nvkoy_
Total Database Size: 19.54MB
Database Data Size: 14.74MB
Database Index Size: 4.80MB
nvkoy_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_actionscheduler_actions: Data: 1.53MB + Index: 0.45MB + Engine MyISAM
nvkoy_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nvkoy_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_actionscheduler_logs: Data: 0.76MB + Index: 0.54MB + Engine MyISAM
nvkoy_borlabs_cookie_consent_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_borlabs_cookie_content_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_borlabs_cookie_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_borlabs_cookie_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_borlabs_cookie_script_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_borlabs_cookie_statistics: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_comments: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
nvkoy_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
nvkoy_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nvkoy_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
nvkoy_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_subscribers: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
nvkoy_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_options: Data: 4.35MB + Index: 0.16MB + Engine MyISAM
nvkoy_postmeta: Data: 1.87MB + Index: 0.16MB + Engine MyISAM
nvkoy_posts: Data: 0.90MB + Index: 0.05MB + Engine MyISAM
nvkoy_storeabill_documentmeta: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
nvkoy_storeabill_documents: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_storeabill_document_itemmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
nvkoy_storeabill_document_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_storeabill_document_noticemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_storeabill_document_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_storeabill_journals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nvkoy_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_usermeta: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
nvkoy_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
nvkoy_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
nvkoy_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
nvkoy_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_wpcf7pdf_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nvkoy_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
nvkoy_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
nvkoy_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nvkoy_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nvkoy_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nvkoy_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

astra-advanced-hook: 4
attachment: 29
bookable_resource: 2
custom_css: 1
customize_changeset: 41
document_template: 5
elementor_library: 8
elementor-hf: 2
mailpoet_page: 1
nav_menu_item: 12
page: 15
post: 3
product: 5
revision: 147
shop_order: 21
wc_booking: 20
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Antispam Bee: by pluginkollektiv – 2.11.3
Astra Pro: by Brainstorm Force – 4.1.6
BackWPup: by Inpsyde GmbH – 4.0.0
Borlabs Cookie - Cookie Opt-in: by Borlabs GmbH – 2.2.64
BT Anamnese: by Benedicta Thölke – 1.0.0
BT Custom Functions: by Benedicta Thölke – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.7.7
Digital Signature For Contact Form 7: by  – 1.0
Elementor: by Elementor.com – 3.14.1
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.14

Loco Translate: by Tim Whitlock – 2.6.4
Custom Login Page Customizer: by Hardeep Asrani – 2.2.2
Send PDF for Contact Form 7: by Florent Maillefaud – 0.9.9.4
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.17
Converter for Media: by matt plugins – 5.9.4
WooCommerce Bookings: by WooCommerce – 2.0.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
Germanized for WooCommerce Pro: by vendidero – 3.7.1
Germanized for WooCommerce: by vendidero – 3.13.3
WooCommerce Payments: by Automattic – 6.1.1
WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.8.2
Yoast SEO: by Team Yoast – 20.11

### Inactive Plugins (7) ###

Google Listings and Ads: by WooCommerce – 2.4.11
Jetpack: by Automattic – 12.3
MailPoet: by MailPoet – 4.20.2
Pinterest for WooCommerce: by WooCommerce – 1.3.5
WooCommerce Shipping & Tax: by WooCommerce – 2.3.0
WP Fastest Cache: by Emre Vona – 1.1.7
WP Mail SMTP: by WP Mail SMTP – 3.8.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #772 - /shop/
Basket: #773 - /warenkorb/
Checkout: #774 - /kasse/
My account: #775 - /mein-konto/
Terms and conditions: #56 - /agb/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: https://www.bt-webdesign.de/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.1.6
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-16 13:23:00 +02:00
Options: ✔
Notes: 52
Onboarding: completed

### WooCommerce Payments ###

Version: 6.1.1
Connected to WPCOM: Yes
Blog ID: 219963027
Account ID: acct_1NH06fFqEyUR4O5l

### Action Scheduler ###

Complete: 3,770
Oldest: 2023-06-15 11:31:02 +0200
Newest: 2023-07-16 11:01:20 +0200

Failed: 311
Oldest: 2023-06-05 15:26:27 +0200
Newest: 2023-07-16 10:35:14 +0200

Pending: 9
Oldest: 2023-07-16 11:06:20 +0200
Newest: 2023-07-21 15:26:40 +0200

### Status report information ###

Generated at: 2023-07-16 11:06:30 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@BT-Webdesign Thanks for reporting the issue. This issue has already been reported to the team that maintains WooCommerce Bookings. In the future, use [WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) issues with extensions purchased through the marketplace. I'll close this issue.
