### ISSUE TITLE
[Enhancement]: add toggle to enable/disable coupons 

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#39269]
### Describe the solution you'd like

I handle quite a few coupons dedicated to specific events (Christmas, summer, mother's day, etc) and to specific products, that I often manually turn on or off.
I'd love to have a toggle that allows to temporary turn off a coupon without having to move it to the trash, and also allows visually see the coupons that are currently active.

**Comment by rrennick** [comment]
> I'd love to have a toggle that allows to temporary turn off a coupon without having to move it to the trash

@tomxygen If you edit the coupon you can change it to draft or set it to private in the `Publish` metabox. I'll close this as a support request.
