### ISSUE TITLE
"Used for variations" default value changed from FALSE to TRUE

### ISSUE THREAD

**Issue by or128** [woothemes/woocommerce#39265]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The default value of attributes for  "Used for variations" is now TRUE and it should be FALSE.
This is new, it was not like this for all the years I've used WooCommerce. 

If you create a simple product and assign attributes to it, their  "Used for variations" value is TRUE now.
You do not see this, as the checkbox is not visible to you unless you switch the product into a variable product, but even on simple product data for "Used for variations" is saved to the DB, and now it is TRUE to all attributes by default. 

This breaks plugins that depend on that data, it makes them think the attributes is a special one that is used to select a variation on the product, even if the product is actually a simple product with no variation at all.

### Expected behavior

The default value of attributes for  "Used for variations" should be FALSE.

### Actual behavior

The default value of attributes for  "Used for variations" is now TRUE.

### Steps to reproduce

1. create some attributes and values for these attributes.
2.  create a new product.
3. Give it attributes and give them a value.
4. save product.
5. turn the product type to "Variable product" (do not save).
6. observe the attributes and you will see that all of their Used for variations checkboxes are checked (value was saved as TRUE to DB).

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.japanese-knives.co.il
Site address (URL): https://www.japanese-knives.co.il
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: he_IL
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 8.1.2
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 10.6.14-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: hks_
Total Database Size: 2081.92MB
Database Data Size: 1936.37MB
Database Index Size: 145.55MB
hks_woocommerce_sessions: Data: 0.25MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_order_items: Data: 5.52MB + Index: 1.52MB + Engine InnoDB
hks_woocommerce_order_itemmeta: Data: 38.56MB + Index: 23.06MB + Engine InnoDB
hks_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 1656.98MB + Index: 5.52MB + Engine InnoDB
hks_actionscheduler_actions: Data: 5.06MB + Index: 8.73MB + Engine InnoDB
hks_actionscheduler_claims: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
hks_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_logs: Data: 43.56MB + Index: 24.06MB + Engine InnoDB
hks_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_atum_product_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_cerber_sets: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
hks_cerber_uss: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_commentmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
hks_comments: Data: 14.52MB + Index: 9.09MB + Engine InnoDB
hks_duplicator_packages: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_detail_new: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_enquiry_quotation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_enquiry_thread: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_gcb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_params: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
hks_imagify_files: Data: 0.22MB + Index: 0.28MB + Engine InnoDB
hks_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_itbbc_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_itbbc_history_items: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
hks_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_mclean_scan: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_slides: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_options: Data: 27.50MB + Index: 0.25MB + Engine InnoDB
hks_postmeta: Data: 93.63MB + Index: 53.14MB + Engine InnoDB
hks_posts: Data: 9.52MB + Index: 3.88MB + Engine InnoDB
hks_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_post_smtp_logs: Data: 10.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
hks_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
hks_revslider_sliders_bkp: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides: Data: 0.30MB + Index: 0.02MB + Engine InnoDB
hks_revslider_slides_bkp: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_termmeta: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
hks_terms: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
hks_term_relationships: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
hks_term_taxonomy: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
hks_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tqb_event_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_users: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_variations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
hks_ukuu_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_usermeta: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
hks_users: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
hks_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wcsc_logs: Data: 1.02MB + Index: 0.30MB + Engine InnoDB
hks_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wc_customer_lookup: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
hks_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_bundle_lookup: Data: 0.16MB + Index: 0.28MB + Engine InnoDB
hks_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_product_lookup: Data: 2.52MB + Index: 1.23MB + Engine InnoDB
hks_wc_order_stats: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
hks_wc_order_tax_lookup: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
hks_wc_product_attributes_lookup: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
hks_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_product_meta_lookup: Data: 0.14MB + Index: 0.30MB + Engine InnoDB
hks_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_theme: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_bundled_itemmeta: Data: 2.52MB + Index: 2.66MB + Engine InnoDB
hks_woocommerce_bundled_items: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
hks_wpr_rocket_cache: Data: 0.16MB + Index: 0.23MB + Engine InnoDB
hks_wpr_rucss_used_css: Data: 1.52MB + Index: 0.81MB + Engine InnoDB
hks_yoast_indexable: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
hks_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
hks_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_yoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
hks_yoast_prominent_words: Data: 0.52MB + Index: 0.73MB + Engine InnoDB
hks_yoast_seo_links: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
hks_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_smtp: 1
attachment: 5174
clients: 1
content_block: 182
decision_tree: 1
follow_up_email: 8
klaviyo_shop_cart: 1
nav_menu_item: 405
oembed_cache: 67
optionsframework: 12
page: 59
post: 55
product: 697
product_variation: 388
pys_event: 6
revision: 14
shop_coupon: 583
shop_order: 11918
shop_order_refund: 11
slide: 1
sp_wpsp_shortcodes: 1
thrive_image: 5
tqb_quiz: 4
tqb_results: 3
tqb_splash: 1
vc_grid_item: 1
wcct-deal-shortcode: 2
wcct_countdown: 32
wcst_trigger: 11
wc_zapier_feed: 2
wp-type-contacts: 2
wpb-rs-global: 7
wpcf7_contact_form: 1
wp_quiz: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (60) ###

Query Monitor: by John Blackbourn – 3.13.1
Add Admin CSS: by Scott Reilly – 2.0.1
Cargo Shipping Location for WooCommerce: by Astraverdes – 3.6
העורך הקלאסי: by מפתחי וורדפרס שנרתמו לפרוייקט – 1.6.3
טפסי צרו קשר 7: by טקאיוקי מיושי – 5.7.7
Content Blocks (Custom Post Widget): by יוהן ואן דר וואג – 3.2.5
Disable Cart Fragments: by Optimocha – 2.3
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.2.9
Duplicate Menu: by Jonathan Christopher – 0.2.2
GTM4WP: by Thomas Geiger – 1.16.2
Envato Market: by Envato – 2.0.8
Finale WooCommerce Deal Pages: by XLPlugins – 1.4.1
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.20.1
Global Content Blocks: by Dave Liske – 2.1.5
WhatsApp Chat for WordPress / WooCommerce: by idnovate.com – 1.3.9
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
Klaviyo: by Klaviyo
Inc. – 3.2.1

Loco Translate: by Tim Whitlock – 2.6.4
One Time Login: by Daniel Bachhuber – 0.4.0
Perfmatters: by forgemedia – 2.1.3
PixelYourSite PRO: by PixelYourSite – 9.8.0
PixelYourSite Super Pack: by PixelYourSite – 3.3.1
plugin load filter: by enomoto@celtislab – 4.0.13
Post SMTP: by Post SMTP – 2.5.8
Product Filter for WooCommerce: by XforWooCommerce – 8.3.0
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 5.3.3
Redis Object Cache: by Till Krüss – 2.4.3
Slider Revolution: by ThemePunch – 6.6.14
snip pro - Structured Data: by floriansimeth – 2.31.1
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.7.2

Shortcode Empty Paragraph Fix: by  – 0.2
Hide SEO Bloat: by SO WP – 4.0.0
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.2.13
WooCommerce Thank You Page - NextMove: by XLPlugins – 1.17.1
TWB Woocommerce Reviews: by Abu Bakar – 1.7.5
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.8.1

CardCom Payment Gateway: by CardCom LTD – 3.4.8.2
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.8
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.5.1
WooCommerce - Pipedrive CRM - Integration: by itgalaxycompany – 1.32.0
WooCommerce Product Bundles: by ווקומרס – 6.22.1
WooCommerce Product Primary Category: by BeoCode.d.o.o. – 0.1.2
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4
ווקומרס: by חברת אוטומטיק – 7.8.2
יואסט SEO פרימיום: by צוות Yoast – 20.11
יוסט SEO: by צוות Yoast – 20.11
עוזר נגישות WP: by אלכס וולקוב – 0.6.2.4
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 9.5.4
WP-Cron Status Checker: by Webhead LLC – 1.2.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.16

WP Rocket | Ignore Query Strings: by WP Rocket Support Team –
WP Rocket | Set Tablets As Mobile: by WP Rocket Support Team –
WP Rocket | Change Preload Parameters: by WP Rocket Support Team –
WP Rocket | Change Remove Unused CSS Parameters: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.14.1
WP-RTL: by Fahad Alduraibi – 1.0
WP User Avatars: by Triple J Software
Inc. – 1.4.1

WPX Cron Manager Light: by Giovambattista Fazioli – 2.4.0
XL WooCommerce Sales Triggers: by XLPlugins – 2.12.1.fix.63
Embed Plus YouTube WordPress Plugin Pro: by Embed Plus for YouTube Team – 14.1.6.3

### Inactive Plugins (26) ###

Cargo Express Shipping method for WooCommerce: by WebSolution – 1.0.9.1
Duplicator: by Duplicator – 1.5.5
Enable Media Replace: by ShortPixel – 4.1.2
Finale Email Countdown Timer: by XLPlugins – 1.2.0
iThemeland bulk bundle core: by iThemelandco – 1.6.1
iThemeland WooCommerce Bulk Product Editing: by iThemelandco – 2.9.1
Media Cleaner: by Jordy Meow – 6.6.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Search & Replace: by Inpsyde GmbH – 3.2.1
SOFT79 Cart Links for WooCommerce: by Soft79 – 1.1.4
Stock Exporter for WooCommerce: by PT Woo Plugins (by Webdados) – 1.2.0
ThumbPress - Stop Generating Unnecessary Thumbnails: by Codexpert
Inc – 4.0.5

What The File: by Never5 – 1.6.0
Widget CSS Classes: by Jory Hogeveen – 1.5.4.1
Widget Options: by Widget Options Team – 3.9.3
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
WooCommerce - Frontend Inventory: by Mirko Grewing – 0.7
Woocommerce Baldar Delivery: by Amit Matat – 1.5.0
WooCommerce Blocks: by Automattic – 10.6.0
WooSidebars: by WooCommerce – 1.4.6
Woo Zap Mirror: by Ido Friedlander – 1.4.6
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.8
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
WP Rocket | WooCommerce Recently Viewed Products Widget Integration: by WP Rocket Support Team –
WP Server Stats: by Saumya Majumder – 1.7.3
Yoast Test Helper: by Team Yoast – 1.17

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (2) ###

aaa-wp-cerber.php: by Cerber Tech Inc. – 1.0
plugin load filter [plf-filter]: by enomoto@celtislab – 4.0.12

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1812 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /order/
My account: #7 - /my-account/
Terms and conditions: #605 - /legal/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.17.4
Parent Theme Author URL: https://uxthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.22.1
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-17 06:39:43 +03:00
Options: ✔
Notes: 20
Onboarding: completed

### Action Scheduler ###

Complete: 19,187
Oldest: 2023-07-11 19:44:05 +0300
Newest: 2023-07-16 17:23:28 +0300

Failed: 201
Oldest: 2022-12-28 13:32:50 +0200
Newest: 2023-06-13 21:48:35 +0300

Pending: 2
Oldest: 2023-07-17 14:53:05 +0300
Newest: 2023-07-21 20:07:20 +0300

### Status report information ###

Generated at: 2023-07-16 17:39:16 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thuautp** [comment]
also reported in 6549436-zen. They downgraded to 7.8.2 for now

**Comment by rrennick** [comment]
@thuautp @or128 This change was intentional. See #38778 and linked discussions.

**Comment by or128** [comment]
> @thuautp @or128 This change was intentional. See #38778 and linked discussions.

It was not, it was actually fixed in the last update, it was in the patch notes.
I believe that #38778 was meant to make the "Used for variations" default value TRUE on **Variable products**.
I don't understand why, this should be something that people choose and check, most attributes will not be the basis for variation, it the wrong thing to do. But I see the #38778 was indeed implemented which I believe is wrong.

I was talking about simple products, and that in simple products the "Used for variations" default value was changed to TRUE. This broke a plugin which I was using and relied on that info to make a decision.

Now hen I create a new simple product, add attributes, save, then make it a variable product and take a look at the attributes, the "Used for variations" is not mark, the default value is FALSE. This is good.

I hope #38778 will also be rolled back, it doesn't make sense for me (even for variable products)

**Comment by AnnaMag** [comment]
Thank you for your contribution @or128. I will close this issue as it is related to another report.

**Comment by mattsherman** [comment]
This will be addressed in #39502
