### ISSUE TITLE
On Stock Product update (variances) on first attempt fails - second or third attempt works. - (deserializing)

### ISSUE THREAD

**Issue by BasitBulbulia** [woothemes/woocommerce#39263]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

0

WordPress 6.2.2 WooCommerce 7.8.2 WooCommerce.NET 0.8.6

I have the code below which is in .net vb ; on update I sometimes get this random errror:-

"There was an error deserializing the object of type WooCommerceNET.WooCommerce.v3.Variation. Encountered unexpected character '<'."

The code below searches for a size in the variances and then updates it.

I used "goto statement" to simulate a repeat try of the update when and error occurs.
` Dim lp As Short = 0
                Dim lpp As Short = 0

                'sizing variations <------
                Dim NumE3 As Short = 0

                Try

ErrLoop3:

                   For lpp = 0 To SizeMatrixSplitList.Count - 1

                        For lp = 0 To Allvariation.Count - 1
                           
                            Dim size2find As String = Allvariation.ElementAt(lp).permalink
                            size2find = Mid(size2find, InStr(size2find, "size=") + 5, 100)

                            Dim item As String = SizeMatrixSplitList(lpp)

                            If Trim(size2find) = Trim(item) Then
                                ' MsgBox(size2find & "<>" & item)

                                Dim variationID As Int32 = Allvariation.ElementAt(lp).id

                                Dim ExistproductStockVariation = Allvariation.ElementAt(lp).stock_quantity

                                Dim totalstockVariation As Integer

                                If WebInfoUpdate = True Then
                                    totalstockVariation = ExistproductStockVariation + Convert.ToInt32(StockMatrixSplit(lpp) * DocumentUpdate)
                                Else
                                    totalstockVariation = Convert.ToInt32(StockMatrixSplit(lpp))
                                End If

                                If UpdateQuantityOnly = True Then
                                    
                                    
                                    Await wc.Product.Variations.Update(variationID, New WooCommerceNET.WooCommerce.v3.Variation With {
                                    .manage_stock = True,
                                                                      .stock_quantity = totalstockVariation
                                                                      }, Existproduct.id)
                                    
                                Else
                                    
                                    If WebInfoUpdate = True And DocumentvvT <> 19 Then
                                    
                                        Await wc.Product.Variations.Update(variationID, New WooCommerceNET.WooCommerce.v3.Variation With {
                                        .manage_stock = True,
                                                                      .stock_quantity = totalstockVariation
                                                                      }, Existproduct.id)
                                    
                                    Else
                                    
                                        Await wc.Product.Variations.Update(variationID, New WooCommerceNET.WooCommerce.v3.Variation With {
                                                                      .regular_price = regular_price,
                                                                      .sale_price = sale_price,
                                                                      .price = sale_price,
                                                                      .manage_stock = True,
                                                                      .stock_quantity = totalstockVariation
                                                                      }, Existproduct.id)
                                    
                                    End If
                                End If
                            End If

                        Next lp

                    Next lpp

                Catch ex As Exception
                    If NumE3 < 2 Then
                        NumE3 = NumE3 + 1
                        LstFiles.Items.Add("Re-TRY -(3)--> " & sku & " Tries : " & NumE3)
                        Thread.Sleep(3000)
                        GoTo ErrLoop3
                        'GoTo starttop
                    End If
                    LstFiles.Items.Add("Failed -(3)--> " & sku & " Error : " & ex.Message)                        
                End Try`

### Expected behavior

Should work on First attempt at Update ! 

### Actual behavior

Works randomly ; sometimes at first attempt sometimes at second or third attempt ! 

### Steps to reproduce

See coode

### WordPress Environment

Woocommerce 7.8.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@BasitBulbulia This repo is for reporting bugs with WooCommerce. I suggest you contact the folks who maintain/support the WooCommerce.Net software.
