### ISSUE TITLE
[Enhancement]: Add data point to show Author information of Coupons

### ISSUE THREAD

**Issue by syhussaini** [woothemes/woocommerce#39266]
### Describe the solution you'd like

In the **Publish Details** of the coupon editor, we have _Status, Visibility, and Published on_ data points. Including _Author_ information here could be useful to locate the author's details when needed. 

### Describe alternatives you've considered

As of now, I considered [Import Export Suite](https://woocommerce.com/document/import-and-export-of-woocommerce-coupons/) to export the coupon data.

### Additional context

6535580-zen

**Comment by rrennick** [comment]
@syhussaini You can enable the author field on coupons with the snippet below. I'll close this issue as it's something we would not enable by default.

```
add_filter( 'woocommerce_register_post_type_shop_coupon', function( $args ) {
	If ( isset( $args['supports'] ) && is_array( $args['supports'] ) ) {
		$args['supports'][] = 'author';
	} else {
		$args['supports'] = ['author'];
	}
	return $args;
} );
```
