### ISSUE TITLE
Manual (Admin) Orders Calculate Discounts After Tax

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#39260]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in zd-6518419

When applying a coupon in a manual order, the discount is calculated after tax, which is not the expected behaviour per the docs: https://woocommerce.com/document/coupon-management/#how-do-coupons-affect-tax-calculations

### Expected behavior

To be calculated before the tax

### Actual behavior

The tax rate is included in the discount.

### Steps to reproduce

1. Go to WooCommerce → Orders.
2. Create a new order for a customer.
3. Add a product, then recalculate to populate the tax.
4. Add a discount, in the example below it's `30%`.
5. The tax is included in the equation, as you can see in the screenshot.

<img src="https://d.pr/i/42HhRG+" alt="">
Link to image: https://d.pr/i/42HhRG

This applies only to manual orders.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://#################.wpcomstaging.com
Site address (URL): https://##################.wpcomstaging.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.6.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Babylon1999** [comment]
#37972 might be related

**Comment by rrennick** [comment]
@Babylon1999 Thanks for creating the issue. As an interim work around you can remove the coupon and re-apply it after you have added products.

**Comment by rrennick** [comment]
@Babylon1999 Two of us tried to reproduce this without success. Can you check the latest version of WooCommerce? Also, please fill out all the info requested in the issue template (eg. full system status report, include the relevant store settings in the testing instructions, etc.

**Comment by Babylon1999** [comment]
I can't replicate it as well with 8.2.1, @rrennick. :‎)

<img src="https://d.pr/i/IvleRZ+" alt="">
Link to image: https://d.pr/i/IvleRZ

This was the original thread in case I'm missing something: https://wordpress.org/support/topic/manual-order-fee-bug/#post-16896151

**Comment by rrennick** [comment]
@Babylon1999 Thanks for the follow up. I'll close the issue.
