### ISSUE TITLE
WOO COMMERCE VARIABLE STOCK QUANTITIES BUG

### ISSUE THREAD

**Issue by adminatsomethingsocial** [woothemes/woocommerce#39276]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using Elementor Pro & WooCommerce to create my client's EComm website. For simple products, the stock quantity shows correctly but for variable products, it doesn't show any of the individual product's stock quantities:
![Plush Pethouse B_Operated • The Toy Factory Shop (1)](https://github.com/woocommerce/woocommerce/assets/139792986/60bb991a-b5dc-4b40-b952-cb07f00d9294)

I have all the individual variation's quantities stock management settings turned on and the quantities put in but I haven't turned on stock management for the individual product:
![Edit product “Plush Pethouse B_Operated” ‹ The Toy Factory Shop — WordPress (1)](https://github.com/woocommerce/woocommerce/assets/139792986/e4bcb44f-439e-4015-9a5f-3fba5d1b1e37)

If I turn on the individual product stock management, it shows as out of stock when I set to remove the quantity or whatever number is set for the individual product, it doesn't show the variation's quantities:
![Edit product “Sponge _ Stress Balls Assorted” ‹ The Toy Factory Shop — WordPress](https://github.com/woocommerce/woocommerce/assets/139792986/65362ea6-98c5-4815-991d-cba881fbd894)
![Plush Pethouse B_Operated • The Toy Factory Shop (2)](https://github.com/woocommerce/woocommerce/assets/139792986/cf1ba21c-697f-45ae-b17b-8980648cda36)

Not sure what to do - I've searched every forum for an answer...

### Expected behavior

I expect to be able to see the stock quantities of variable products similar to simple products

### Actual behavior

I'm using Elementor Pro & WooCommerce to create my client's EComm website. For simple products, the stock quantity shows correctly but for variable products, it doesn't show any of the individual product's stock quantities:
![Plush Pethouse B_Operated • The Toy Factory Shop (1)](https://github.com/woocommerce/woocommerce/assets/139792986/60bb991a-b5dc-4b40-b952-cb07f00d9294)

I have all the individual variation's quantities stock management settings turned on and the quantities put in but I haven't turned on stock management for the individual product:
![Edit product “Plush Pethouse B_Operated” ‹ The Toy Factory Shop — WordPress (1)](https://github.com/woocommerce/woocommerce/assets/139792986/e4bcb44f-439e-4015-9a5f-3fba5d1b1e37)

If I turn on the individual product stock management, it shows as out of stock when I set to remove the quantity or whatever number is set for the individual product, it doesn't show the variation's quantities:
![Edit product “Sponge _ Stress Balls Assorted” ‹ The Toy Factory Shop — WordPress](https://github.com/woocommerce/woocommerce/assets/139792986/65362ea6-98c5-4815-991d-cba881fbd894)
![Plush Pethouse B_Operated • The Toy Factory Shop (2)](https://github.com/woocommerce/woocommerce/assets/139792986/cf1ba21c-697f-45ae-b17b-8980648cda36)

Not sure what to do - I've searched every forum for an answer...

### Steps to reproduce

1. Go to a variable product
2. Try selecting a variable of the product
3. No quantity in stock shows

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.toyfactoryshop.co.za
Site address (URL): http://www.toyfactoryshop.co.za
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.20
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 3500
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-1:10.5.21+maria~deb10
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 476.17MB
Database Data Size: 334.80MB
Database Index Size: 141.37MB
wp_woocommerce_sessions: Data: 1.94MB + Index: 0.05MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 7.22MB + Index: 3.32MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 58.58MB + Index: 35.52MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 10.52MB + Index: 13.02MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 9.52MB + Index: 6.03MB + Engine InnoDB
wp_aws_cache: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 6.50MB + Index: 3.84MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_ac_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_connection_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_no_cookie_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_sfw: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_ua_bl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cleantalk_wc_spam_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.47MB + Index: 0.45MB + Engine InnoDB
wp_comments: Data: 26.56MB + Index: 15.08MB + Engine InnoDB
wp_crw_crosswords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_crw_editors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_crw_projects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dxgames: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_dxservers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_edd_customermeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_edd_customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_enquiry_detail_new: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_enquiry_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_enquiry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_enquiry_quotation: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_enquiry_thread: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.09MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_fmepco_poptions_table: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fmepco_rowoption_table: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fmepco_temp_table: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_gf_entry_meta: Data: 2.52MB + Index: 3.39MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.47MB + Index: 0.14MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ghostmonitor_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmwd_circles: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_maps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_mapstyles: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_markercategories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_markers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_polygons: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_polylines: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_rectangles: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_shortcodes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmwd_themes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_huge_itslider_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_huge_itslider_params: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_huge_itslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_font_family: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_gallery_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_video_effdb: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_video_link: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_video_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect1: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect2: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect3: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect4: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect5: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_juna_it_v_effect6: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Data: 1.18MB + Index: 0.88MB + Engine MyISAM
wp_newsletter_emails: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_sent: Data: 0.22MB + Index: 0.37MB + Engine MyISAM
wp_newsletter_stats: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wp_newsletter_user_logs: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_image_storage: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_section_storage: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_nm_personalized: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_omega_sync_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 7.88MB + Index: 0.39MB + Engine MyISAM
wp_postmeta: Data: 69.90MB + Index: 24.74MB + Engine MyISAM
wp_posts: Data: 10.81MB + Index: 1.49MB + Engine MyISAM
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.22MB + Index: 0.08MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_slp_extendo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_spbc_auth_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_backuped_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_backups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_bfp_blocked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall_data: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_firewall_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall__personal_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall__personal_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_monitoring_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_scan_frontend: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_links_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_spbc_scan_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_scan_results_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_signatures: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_spbc_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_traffic_control_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_store_locator: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_termmeta: Data: 0.20MB + Index: 0.15MB + Engine MyISAM
wp_terms: Data: 0.10MB + Index: 0.19MB + Engine MyISAM
wp_term_relationships: Data: 0.22MB + Index: 0.46MB + Engine MyISAM
wp_term_taxonomy: Data: 0.13MB + Index: 0.17MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 39.91MB + Index: 8.97MB + Engine MyISAM
wp_users: Data: 1.07MB + Index: 0.97MB + Engine MyISAM
wp_vtprd_purchase_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtprd_purchase_log_product: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtprd_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.74MB + Index: 0.63MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 9.30MB + Index: 6.82MB + Engine MyISAM
wp_wc_order_stats: Data: 0.90MB + Index: 0.48MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.41MB + Index: 0.45MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.31MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 3.77MB + Index: 0.02MB + Engine MyISAM
wp_wfCrawlers: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 25.35MB + Index: 3.43MB + Engine MyISAM
wp_wfHits: Data: 2.65MB + Index: 0.60MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 20.55MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.40MB + Index: 0.10MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wfReverseCache: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfSecurityEvents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Data: 0.45MB + Index: 0.19MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfWafFailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_extra_flat_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 1.52MB + Index: 4.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_yith_wapo_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wapo_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 5.94MB + Index: 1.20MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.16MB + Index: 0.35MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM

### Post Type Counts ###

attachment: 3473
custom_css: 2
customize_changeset: 12
elementor_library: 46
elementor_snippet: 3
et_pb_layout: 37
ig_message: 6
jet-menu: 2
jet-smart-filters: 4
layout: 2
location: 3
nav_menu_item: 64
page: 28
phoen_ticket_systems: 1
popup: 1
popup_theme: 6
post: 28
product: 974
product_variation: 693
project: 2
revision: 1226
seedprod: 1
shop_coupon: 10
shop_order: 11152
shop_quote: 95
sliced_invoice: 1
vtprd-rule: 1
wcct_countdown: 2
woocarousel: 1
wp_global_styles: 3
wp_navigation: 1
wpcode: 3
yith_wcan_preset: 1
ywrac_cart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Gravity Forms: by Gravity Forms – 2.7.10
Advanced Woo Search: by ILLID – 2.83
Beautiful and responsive cookie consent: by Beautiful Cookie Banner – 2.13.2
Anti-Spam by CleanTalk: by СleanTalk  – 6.13
Elementor Pro: by Elementor.com – 3.14.1
Elementor: by Elementor.com – 3.14.1
ElementsKit Lite: by Wpmet – 2.9.0
ElementsKit Pro: by Wpmet – 3.3.0
Facebook for WooCommerce: by Facebook – 3.0.28
Google Listings and Ads: by WooCommerce – 2.4.11
Site Kit by Google: by Google – 1.104.0
WPCode Lite: by WPCode – 2.0.13.1
Integration for Elementor forms - Sendinblue: by Webtica – 1.5.4
WooCommerce - PayU MEA Payment Gateway (Redirect): by PayU MEA – 1.3.1
Really Simple SSL: by Really Simple Plugins – 7.0.6
Rank Math SEO: by Rank Math – 1.0.118
ShopEngine: by Wpmet – 4.2.2
Side Cart For Woocommerce Pro: by  – 1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.7

Converter for Media: by matt plugins – 5.9.4
Ajax add to cart for WooCommerce: by QuadLayers – 2.2.1
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.1
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.8
WooCommerce: by Automattic – 7.8.2
Wordfence Security: by Wordfence – 7.10.1
WP Activity Log: by WP White Security – 4.5.3
YITH WooCommerce Wishlist: by YITH – 3.23.0

### Inactive Plugins (1) ###

reCAPTCHA for WooCommerce: by Elliot Sowersby
RelyWP – 1.3.0

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #24718 - /shop/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #16544 - /my-account/
Terms and conditions: #17096 - /terms-and-conditions/

### Theme ###

Name: Hello Elementor
Version: 2.8.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-18 12:54:03 +02:00
Options: ✔
Notes: 150
Onboarding: completed

### Action Scheduler ###

Complete: 1,864
Oldest: 2023-06-16 17:34:36 +0000
Newest: 2023-07-17 16:34:54 +0000

Failed: 25,421
Oldest: 2022-10-10 17:35:05 +0000
Newest: 2023-07-17 14:13:53 +0000

Pending: 5
Oldest: 2023-07-17 17:52:01 +0000
Newest: 2023-07-18 07:03:01 +0000

### Status report information ###

Generated at: 2023-07-17 18:43:14 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> I'm using Elementor Pro & WooCommerce to create my client's EComm website.

@adminatsomethingsocial Can you reproduce the issue you are describing with just WooCommerce and a default theme or Storefront active?

**Comment by pmcpinto** [comment]
Hey @adminatsomethingsocial we'd like to know you already had time to test the following:

> @adminatsomethingsocial Can you reproduce the issue you are describing with just WooCommerce and a default theme or Storefront active?

Thanks
