### ISSUE TITLE
HPOS woocommerce_order_list_table_restrict_manage_orders action not called in same place as restrict_manage_posts

### ISSUE THREAD

**Issue by ninetyninew** [woothemes/woocommerce#39271]
### Describe the solution you'd like

In HPOS a new hook was added: `woocommerce_order_list_table_restrict_manage_orders`, this can be used to add a custom filter field to the orders list, it is effectively the equivalent of using `restrict_manage_posts` before HPOS was a thing.

However, if you display a field via `woocommerce_order_list_table_restrict_manage_orders` those fields appear after the customer filter field.

Previously if you are using `restrict_manage_posts` the fields appear before the customer filter field.

This appears to be because the do_action in `extra_tablenav()` is happening after the customer field.

For consistency with the older method, we recommend this is changed so the `do_action` is called before the customer filter.

### Additional context

You can test this by using the following code and then switching between the data storage and looking at the orders list for both scenarios, you'll see the filter added is before/after the customer filter:

```
function orderslisttest1() {

	echo '<select><option>this was added via restrict_manage_posts</option></select>';

}
add_action( 'restrict_manage_posts', 'orderslisttest1' );

function orderslisttest2() {

	echo '<select><option>this was added via woocommerce_order_list_table_restrict_manage_orders</option></select>';

}
add_action( 'woocommerce_order_list_table_restrict_manage_orders', 'orderslisttest2' );
```

**Comment by jorgeatorres** [comment]
I can replicate. Thanks for the report @ninetyninew! We'll take care of this.
