### ISSUE TITLE
Changelogger from PR description: Permissions not working with forks

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#39285]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When creating a changefile from PR description for a community contribution, Github Actions Bot fails in committing code due to authentication errors.

See https://github.com/woocommerce/woocommerce/pull/39074

**Comment by tammullen** [comment]
Done in https://github.com/woocommerce/woocommerce/pull/39290
