### ISSUE TITLE
New Product Editor Beta - Issue with Navigation Blocks

### ISSUE THREAD

**Issue by FunkyCss** [woothemes/woocommerce#39295]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is no way to scroll the blocks on the left side, but you can only search them, you can take a look at the image 

![Untitled-1](https://github.com/woocommerce/woocommerce/assets/62518751/f026044f-4c36-48f5-a9a8-9fee77a9d0f6)

### Expected behavior

To be scroll like the typical gutenberg on pages.

### Actual behavior

There is missing a scroll to navigate the blocks 

### Steps to reproduce

1. Enable new product editor
2. Go add a new product
3. Add the long description
4. Try to scroll left the blocks

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): -
Site address (URL): -
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: el
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.1.21
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 8.1.2
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: D1AlfQ40_
Συνολικό μέγεθος βάσης δεδομένων: 14.04MB
Μέγεθος βάσης δεδομένων: 10.72MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 3.32MB
D1AlfQ40_woocommerce_sessions: Δεδομένα: 0.16MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_api_keys: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_attribute_taxonomies: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_downloadable_product_permissions: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_order_items: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_order_itemmeta: Δεδομένα: 0.09MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_tax_rates: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_tax_rate_locations: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_shipping_zones: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_shipping_zone_locations: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_shipping_zone_methods: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_payment_tokens: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_payment_tokenmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_woocommerce_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_actionscheduler_actions: Δεδομένα: 0.30MB + Ευρετήρια: 0.45MB + Μηχανή InnoDB.
D1AlfQ40_actionscheduler_claims: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_actionscheduler_groups: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_actionscheduler_logs: Δεδομένα: 0.34MB + Ευρετήρια: 0.22MB + Μηχανή InnoDB.
D1AlfQ40_commentmeta: Δεδομένα: 0.05MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_comments: Δεδομένα: 0.13MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
D1AlfQ40_links: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_options: Δεδομένα: 3.42MB + Ευρετήρια: 0.08MB + Μηχανή InnoDB.
D1AlfQ40_postmeta: Δεδομένα: 2.52MB + Ευρετήρια: 0.73MB + Μηχανή InnoDB.
D1AlfQ40_posts: Δεδομένα: 2.48MB + Ευρετήρια: 0.14MB + Μηχανή InnoDB.
D1AlfQ40_term_relationships: Δεδομένα: 0.05MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_term_taxonomy: Δεδομένα: 0.05MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_termmeta: Δεδομένα: 0.08MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_terms: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_tm_taskmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_tm_tasks: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_usermeta: Δεδομένα: 0.03MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_users: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
D1AlfQ40_wc_admin_note_actions: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wc_admin_notes: Δεδομένα: 0.05MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_wc_category_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_wc_customer_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_download_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_addresses: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_coupon_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_operational_data: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_product_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_stats: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
D1AlfQ40_wc_order_tax_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_orders: Δεδομένα: 0.05MB + Ευρετήρια: 0.11MB + Μηχανή InnoDB.
D1AlfQ40_wc_orders_meta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
D1AlfQ40_wc_product_attributes_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wc_product_download_directories: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wc_product_meta_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
D1AlfQ40_wc_rate_limits: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wc_reserved_stock: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_wc_tax_rate_classes: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wc_webhooks: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
D1AlfQ40_wpmailsmtp_debug_events: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_wpmailsmtp_tasks_meta: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
D1AlfQ40_wpr_rocket_cache: Δεδομένα: 0.05MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
D1AlfQ40_wpr_rucss_used_css: Δεδομένα: 0.09MB + Ευρετήρια: 0.13MB + Μηχανή InnoDB.

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 447
custom_css: 3
gp_elements: 5
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 32
oembed_cache: 27
page: 19
post: 67
product: 102
shop_order: 51
wp_global_styles: 1
wp_navigation: 1
wp_show_posts: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Advanced Custom Fields: από τον/την WP Engine – 6.1.7
The SEO Framework: από τον/την The SEO Framework Team – 4.2.8
Facebook for WooCommerce: από τον/την Facebook – 3.0.28
GenerateBlocks Pro: από τον/την Tom Usborne – 1.5.2
GenerateBlocks: από τον/την Tom Usborne – 1.7.3
GP Premium: από τον/την Tom Usborne – 2.3.1
WooCommerce Stripe Gateway: από τον/την WooCommerce – 7.4.1
WooCommerce: από τον/την Automattic – 7.9.0
WP Mail SMTP: από τον/την WP Mail SMTP – 3.8.0
WP Rocket: από τον/την WP Media – 3.14.1

### Inactive Plugins (1) ###

WooCommerce PayPal Payments: από τον/την WooCommerce – 2.2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Βάση καταστήματος: #3691 - /shop/
Καλάθι: #3692 - /cart/
Ταμείο: #3693 - /checkout/
Ο λογαριασμός μου: #3695 - /my-account/
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.3.0
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: generatepress_child/woocommerce/emails/admin-new-order.php
generatepress_child/woocommerce/emails/plain/admin-new-order.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-18 23:01:46 +03:00
Options: ✔
Notes: 38
Onboarding: completed

### Action Scheduler ###

Ολοκληρωμένη: 982
Oldest: 2023-06-17 11:20:00 +0300
Newest: 2023-07-18 11:06:44 +0300

Σε αναμονή: 1
Oldest: 2023-07-19 01:50:00 +0300
Newest: 2023-07-19 01:50:00 +0300

### Status report information ###

Generated at: 2023-07-18 11:08:59 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
Thanks for spotting this issue.

@AnnaMag do you think it's possible to fix this in time to be included in 8.0?
