### ISSUE TITLE
Snyk report showing security vulnerabilities-Vulnerability Audit of the WooCommerce Plugin

### ISSUE THREAD

**Issue by sinhabit** [woothemes/woocommerce#39303]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi WooCommerce Support Team, 

I am Susan Blizzard, the Head of Digital Marketing Services for Inhabit, a global PropTech software company serving the residential and vacation property management industries. We have over 2,000 websites in-house that our multiple digital agencies manage for customers.

Q4Launch, one of the digital marketing and website providers within Inhabit, has been conducting a plugin review process for all listed within their website platform, including WooCommerce. The audit was conducted through Synk, a developer security platform, and revealed several “High” issues for overall platform security and vulnerability. The details of the audit have been attached, and a high-level of the issues have been articulated below, including: 
•	Cross-site Scripting (XSS).
•	Hardcoded Secret.

Has your team been aware of these platform improvements and actively working toward a solution for Cross-site Scripting and Hardcoded Secret instances noted in the audit? 

Looking forward to hearing your response and understanding the next steps for an effective resolution so that our IT dept can be satisfied with the safety and security of the Woocommerce plugin.

[Woocommerce failed security Snyk test report.pdf](https://github.com/woocommerce/woocommerce/files/12087569/Woocommerce.failed.security.Snyk.test.report.pdf)

### Expected behavior

We would expect at least that none of the 15 high security issues would be present with Woocommerce.

### Actual behavior

Failed security test

### Steps to reproduce

See report

### WordPress Environment

[Woocommerce failed security Snyk test report.pdf](https://github.com/woocommerce/woocommerce/files/12087811/Woocommerce.failed.security.Snyk.test.report.pdf)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Hi @sinhabit, please see our [security policy](https://github.com/woocommerce/woocommerce#reporting-security-issues) for reporting security issues.
