### ISSUE TITLE
PHP Deprecated:  strstr(): Passing null to parameter #1 ($haystack)

### ISSUE THREAD

**Issue by betayazilim** [woothemes/woocommerce#39311]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have hundreds of these lines in my debug.log file.
PHP Deprecated:  strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated in /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-page-functions.php on line 139

### Expected behavior

No error or warning

### Actual behavior

Gives this error.
PHP Deprecated:  strstr(): Passing null to parameter #1 ($haystack)

### Steps to reproduce

Php 8.1
Latest woocommerce

### WordPress Environment

Woocommerce and wordpress are latest.
Hosting : Pressable
Php 8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@bashin Can you confirm that you have WooCommerce 7.9.0 installed? This issue was addressed in #38008.

**Comment by Bashin** [comment]
@rrennick You tagged the wrong person. ;-) Let me fix that @bsahins

**Comment by betayazilim** [comment]
You are right.
Now it is gone.

**Comment by rrennick** [comment]
@Bashin Oops & thank you for following up with the ping.
