### ISSUE TITLE
[Enhancement]: Use application/x-www-form-urlencoded rather than multipart/form-data 

### ISSUE THREAD

**Issue by xbb123** [woothemes/woocommerce#39318]
### Describe the solution you'd like

Hi all,

  Is there a specific reason for using 'multipart/form-data' on '/checkout/order-received/' endpoint?
  The page asks the customer to provide his email address to verify his identify; but the content type of the POST request is using 'multipart/form-data' which does not seem to be necessary and our WAF keeps blocking the requests.
  "application/x-www-form-urlencoded" seems to be sufficient to submit email and checksum.
  Thank you!

**Comment by mi5t4n** [comment]
@xbb123 Could you provide us a screenshot/recording of the issue? It will help me to fix the issue as soon as possible.
