### ISSUE TITLE
"Variations" disappeared from custom variable product. "Used for variations" checkbox became disabled and unchecked. WC 7.9.0

### ISSUE THREAD

**Issue by tinboyko** [woothemes/woocommerce#39338]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Variations" disappeared from the custom variable product. "Used for variations" checkbox became disabled and unchecked. This happened after updating WC to the 7.9.0 version

### Expected behavior

Variations should persist for custom variable product.  "Used for variations" checkbox should be enabled.

### Actual behavior

"Variations" disappeared from the custom variable product. "Used for variations" checkbox became disabled and unchecked. This happened after updating WC to the 7.9.0 version

### Steps to reproduce

1. Register custom variable product
2. Go to the custom variable product edit page
3. Check "Variations" and "Attributes" tabs

### WordPress Environment

can't post it due to sensitive data. But all requirements were met and was working ok on the 7.8.2 version before the update

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by azarif** [comment]
I have found this issue also and it is a problem. There were a lot of changes to these two files:
woocommerce/assets/js/admin/meta-boxes-product.js
woocommerce/assets/js/admin/meta-boxes-product-variation.js

The main noticeable function added is disable_or_enable_fields()

I have tried CSS tweaks to reenable the checkboxes on the frontend. However when I save the attributes it is switching back to a Variable product type, Variations are disappearing and the checkboxes are disabled.

**Comment by azarif** [comment]
So far I've got it working again with this JavaScript:

```(function ($) {
    $(document).ready(function () {

        const initClasses = () => {
            // Add Classes to Product Data Tabs
            $('#general_product_data .show_if_variable').addClass('show_if_customtype');
            $('#general_product_data .hide_if_variable').addClass('hide_if_customtype');

            $('#inventory_product_data .show_if_variable').addClass('show_if_customtype');
            $('#inventory_product_data .hide_if_variable').addClass('hide_if_customtype');
        }

        const initProductAttributes = () => {
            // Add classes to the product attributes
            $('#product_attributes .enable_variation').addClass('show_if_customtype');
            $('#product_attributes .enable_if_variable').addClass('enable_if_customtype');
        }

        const maybeShow = () => {
            const product_type = $('select#product-type').val();
            // Show the product attributes
            $(`.show_if_${product_type}`).each(function () {
                $(this).show();
            });

            $('input#_manage_stock').trigger('change');
        }

        const maybeEnable = () => {
            const product_type = $('select#product-type').val();
            // Enable the product attributes
            $(`.enable_if_${product_type}`).each(function () {
                $(this).removeClass('disabled');
                if ($(this).is('input')) {
                    $(this).prop('disabled', false);
                }
            });
        }

        initClasses();
        initProductAttributes();
        maybeShow();
        maybeEnable();

        // Fires before disable_or_enable_fields();
        $('body').on('wc-enhanced-select-init', () => {
            initProductAttributes();
            maybeShow();
        });

        $('body').on('woocommerce-product-type-change', () => {
            maybeShow();
            maybeEnable();
        });

        $('body').on('woocommerce_variations_loaded', () => {
            maybeEnable();
        });
    });

})(jQuery);

**Comment by lvvvvvl** [comment]
I'm also experiencing this bug after the 7.9.0 version update. It has made all my variable subscription products unpurchasable. 

The Attributes still appear, but the ‘Used for Variations’ checkbox has become unticked, and the Variations tab in the Products section now shows the message: “Add some attributes in the Attributes tab to generate variations. Make sure to check the Used for variations box. Learn more” (even though there are two Attributes.)

**Comment by MarcCeleiro** [comment]
I have the same problem here. In my case, the variations have only been affected in products created or edited after the update, and it is fixed by activating the 'Used for Variations' checkbox.

**Comment by sillyForeigner** [comment]
Fixing this would be highly appreciated. The "Used for Variations" checkbox is disabled and variations are not showing on my WC subscription product page. The script shared above didn't work for me. Reverted back to WooCommerce 7.8.2. to make it work.

**Comment by relima** [comment]
Same problem here

**Comment by relima** [comment]
> Fixing this would be highly appreciated. The "Used for Variations" checkbox is disabled and variations are not showing on my WC subscription product page. The script shared above didn't work for me. Reverted back to WooCommerce 7.8.2. to make it work.

how did you revert?

**Comment by sillyForeigner** [comment]
Via WP Rollback plugin :)

Vít Aora
aoravit.cz
***@***.***
Kniha Detox hlavy
7denní očistná výzva
Podcast Svojí cestou
Instagram

**Comment by AnnaMag** [comment]
WooCommerce Subscriptions 5.3.1 includes a fix for its custom products cc @mattallan.

Has anyone reporting here used another custom type?
@tinboyko could you expand on the detail of `1. Register custom variable product`?

**Comment by smachi** [comment]
The same thing happening to us. We have some custom variable products and the "show_if_variable", "enable_if_variable", etc classes cannot be filtered here as used to be for this kind of utility classes in other places.

**Comment by AnnaMag** [comment]
[As mentioned earlier,](https://github.com/woocommerce/woocommerce/issues/39338#issuecomment-1651564955) this issue was fixed for WC Subscriptions. 

Are you using any specific extensions that affect this part of the flow? cc @smachi @braveanthony

**Comment by smachi** [comment]
@AnnaMag Indeed. We are using custom variable types on our own plugins.

[This one](https://stockmanagementlabs.com/addons/atum-product-levels/), for example.

**Comment by azarif** [comment]
@AnnaMag I have two custom variable product types which are extending the `WC_Product_Variable` class. Currently it is working again and I have no issues since the JS tweak.

**Comment by AnnaMag** [comment]
Thank you for the extra context-- we will work on a solution. 

Related: https://github.com/woocommerce/woocommerce/issues/39265.

**Comment by omarsaaeed** [comment]
I have this issue as well, has it been resolved yet? I can't select Used for Variations see pic below:

![woo](https://github.com/woocommerce/woocommerce/assets/49376549/fb91ebe3-9847-4352-9d42-c91b1bdb8f28)
![woo2](https://github.com/woocommerce/woocommerce/assets/49376549/d5437b34-012e-49bb-9436-35241c0369da)

**Comment by AnnaMag** [comment]
@omarsaaeed [for your use case, yes](https://github.com/woocommerce/woocommerce/issues/39338#issuecomment-1651564955).

**Comment by mattsherman** [comment]
> @omarsaaeed [for your use case, yes](https://github.com/woocommerce/woocommerce/issues/39338#issuecomment-1651564955).

You need to upgrade to WooCommerce Subscriptions 5.3.1 in order to have this fixed.

**Comment by partekitsolutions** [comment]
This issue is currently occurring on our website. We are not using Woo Subscriptions.

**Comment by Nalci** [comment]
I try to create a custom variable product type, extended from the WC_Product_Variable. 

Unfortunately the checkbox "use this for variation" is missing and when I save attributes, the attributes tab shows "add some attributes to generate variations. 

I tried many codes on the web and asked AI but nothing helped. I don't use the subscription plugin, only standalone WooCommerce.
