### ISSUE TITLE
[HPOS] Settings broken when woocommerce_custom_orders_table_created option is not yes

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#39349]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If the HPOS tables already exist and `woocommerce_custom_orders_table_created` is not `yes` then the settings screen shows the current number of orders/refunds in the posts table as pending sync regardless of the number that are pending sync. This disables changing the settings. 

### Expected behavior

The synchronizer should check for the existence of the HPOS tables before counting the posts. 

### Actual behavior

Settings are disabled.

### Steps to reproduce

1. Ensure you have orders in the posts table
2. Run `wp option update woocommerce_custom_orders_table_created no`
3. Go to WooCommerce -> Settings -> Advanced -> Features

### WordPress Environment

Dev install with trunk

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Fixed via #39616
