### ISSUE TITLE
Possible fatal error in order edit lock 'heartbeat_received' AJAX

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#39353]
**Issue Description:**

Even though our code seems to be fine, there might be other plugins causing errors and given the signature for our `WC_AJAX::order_refresh_lock()` is quite strict, it can result in fatal errors that would otherwise not be noticed.

> Some plugins seems to be setting the $response variable in WP Heartbeat as a non array which is causing errors:

> [08-Jul-2023 02:06:03 UTC] PHP Fatal error: Uncaught TypeError: Return value of WC_AJAX::order_refresh_lock() must be of the type array, null returned in /woocommerce/includes/class-wc-ajax.php:3475

Related: https://wordpress.org/support/topic/e_error-27/, 6545417-zd-woothemes, 6431713-zd-woothemes, 6427042-zd-woothemes

**Comment by EjayhanFernandes** [comment]
Another instance here: 6563116-zen
