### ISSUE TITLE
[New Product Editor]: repeated error messaging.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#39360]
Error messages in the new product editor are repeated. 

I have observed the one related to SKU, where every save/add action adds a new component. We should verify if that is the only instance.

![Image](https://user-images.githubusercontent.com/13561163/255153300-20990e7d-41ad-4f87-a9a2-af5d1c767c15.png)

**Comment by AnnaMag** [comment]
Related https://github.com/woocommerce/woocommerce/issues/36774.

**Comment by octaedro** [comment]
Hey @AnnaMag,
I'm trying to reproduce this error, but I can't. I believe it has been fixed.
I'll close this issue.
