### ISSUE TITLE
Duplicate Customer Note Emails

### ISSUE THREAD

**Issue by unitv** [woothemes/woocommerce#39371]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Customers are receiving duplicate emails when Customer Note is enable.

### Expected behavior

Customers need to received only one Customer Note email.

### Actual behavior

Customers are receiving duplicate emails when Customer Note is enable.

### Steps to reproduce

![woocommerce_email_error](https://github.com/woocommerce/woocommerce/assets/98430442/ede2020a-8fb5-4096-a150-6b3efe08df14)

### WordPress Environment ###

WordPress address (URL): https://recarregabox.com
Site address (URL): https://recarregabox.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.4
PHP Version: 7.4.33
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 8.0.24
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 33.07MB
Tamanho dos dados do banco de dados: 28.62MB
Tamanho do índice do banco de dado: 4.45MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 0.09MB + Índex: 0.11MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 0.08MB + Índex: 0.03MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_cwmp_cart_abandoned: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_cart_abandoned_msg: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_cart_abandoned_relation: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_events_pixel_facebook: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_newsletter_campanha: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_newsletter_remove: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_newsletter_send: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_order_bump: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_orders_buy: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_pending_payment_msg: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_pending_payment_status: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_pixel_thank: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_recupera_pedidos: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_send_thank: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_template_emails: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_template_emails_produto: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_template_msgs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cwmp_transportadoras: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_e_events: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_e_submissions: Dados: 0.02MB + Índex: 0.23MB + mecanismo InnoDB
wp_e_submissions_actions_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_e_submissions_values: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ewwwio_images: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ewwwio_queue: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_fc_campaign_emails: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_fc_campaign_url_metrics: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_fc_campaigns: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_contact_relation_items: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_fc_contact_relations: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_funnel_metrics: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_fc_funnel_sequences: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_fc_funnel_subscribers: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_fc_funnels: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_lists: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fc_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_sequence_tracker: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_fc_subscriber_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_fc_subscriber_notes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_subscriber_pivot: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_subscribers: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_fc_tags: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fc_url_stores: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ff_scheduled_actions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_draft_submissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_entry_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_form_analytics: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_logs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_order_items: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_submission_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_submissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_subscriptions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_transactions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fsmpt_email_logs: Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_lic_key_tbl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_lic_reg_domain_tbl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_lmfwc_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_lmfwc_generators: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_lmfwc_licenses: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_lmfwc_licenses_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_options: Dados: 4.02MB + Índex: 0.13MB + mecanismo InnoDB
wp_postmeta: Dados: 8.48MB + Índex: 0.27MB + mecanismo InnoDB
wp_posts: Dados: 9.48MB + Índex: 0.11MB + mecanismo InnoDB
wp_snippets: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_uap_action_log: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_uap_action_log_meta: Dados: 1.52MB + Índex: 0.19MB + mecanismo InnoDB
wp_uap_action_logs_view: Dados: 0.00MB + Índex: 0.00MB + mecanismo
wp_uap_api_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_uap_api_log_response: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_uap_api_logs_view: Dados: 0.00MB + Índex: 0.00MB + mecanismo
wp_uap_closure_log: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_uap_closure_log_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_uap_recipe_log: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_uap_recipe_log_meta: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_uap_recipe_logs_view: Dados: 0.00MB + Índex: 0.00MB + mecanismo
wp_uap_tokens_log: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
wp_uap_trigger_log: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_uap_trigger_log_meta: Dados: 0.06MB + Índex: 0.08MB + mecanismo InnoDB
wp_uap_trigger_logs_view: Dados: 0.00MB + Índex: 0.00MB + mecanismo
wp_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_ld_license_codes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_order_addresses: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_operational_data: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_orders: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_wc_orders_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_download_directories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wpfm_backup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpforms_payment_meta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wpforms_payments: Dados: 0.02MB + Índex: 0.14MB + mecanismo InnoDB
wp_wpforms_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_debug_events: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpmailsmtp_emails_log: Dados: 0.41MB + Índex: 0.03MB + mecanismo InnoDB
wp_wpmailsmtp_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpml_mails: Dados: 0.33MB + Índex: 0.02MB + mecanismo InnoDB
wp_wpr_rucss_resources: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wpr_rucss_used_css: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 84
elementor_library: 15
nav_menu_item: 11
page: 12
post: 2
product: 6
revision: 308
shop_order: 3
uo-action: 7
uo-recipe: 9
uo-trigger: 7
viwec_template: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Allow only 1 product in Cart: por MohammedYasar Khalifa – 1.2
Code Snippets: por Code Snippets Pro – 3.4.2
Elementor Pro: por Elementor.com – 3.14.1
Elementor: por Elementor.com – 3.14.1
FluentCRM - Marketing Automation For WordPress: por WP Email Newsletter Team - FluentCRM – 2.8.20
FluentCRM Pro: por Fluent CRM – 2.8.20
License Manager for WooCommerce (Free): por LicenseManager – 2.2.9
WebP Express: por Bjørn Rosell – 0.25.6
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.9.0
Mercado Pago payments for WooCommerce: por Mercado Pago – 6.9.3
WooCommerce: por Automattic – 7.9.0
WP Mail Logging: por WP Mail Logging Team – 1.12.0
WP Mail SMTP Pro: por WP Mail SMTP – 3.8.2
WP Rocket: por WP Media – 3.11.4.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base da loja: #285 - /store/
Carrinho: #9 - /carrinho/
Finalização de compra: ❌ Página não contém o shortcode [woocommerce_checkout] ou o bloco woocommerce/checkout.
Minha conta: #11 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Hello Elementor
Version: 2.8.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: hello-elementor/woocommerce/emails/customer-completed-order.php
hello-elementor/woocommerce/emails/customer-note.php
hello-elementor/woocommerce/emails/customer-on-hold-order.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-22 18:12:47 -03:00
Options: ✔
Notes: 75
Onboarding: skipped

### Action Scheduler ###

Concluído: 246
Oldest: 2023-07-10 13:49:41 -0300
Newest: 2023-07-22 11:35:01 -0300

Malsucedido: 1
Oldest: 2023-07-20 13:49:43 -0300
Newest: 2023-07-20 13:49:43 -0300

Pendente: 4
Oldest: 2023-07-23 03:10:23 -0300
Newest: 2023-07-24 14:00:00 -0300

### Status report information ###

Generated at: 2023-07-22 11:35:16 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
Hi there!

Can you please share the exact steps to replicate the behavior you're seeing?

I test with a product that has a Purchase note. I also tried with an order where I included order notes on the checkout page. I finally tested the customer note option on the Order details page. None of them triggered a duplicate email.

**Comment by unitv** [comment]
In a fresh wordpress instalation, I just instaled woocommerce and mercado pago plugin for payment gateway.
Create a single product and enable only complete orders and customer notes emails.

![image](https://github.com/woocommerce/woocommerce/assets/98430442/23845eea-069b-44e8-a3b5-7c7ceafccb39)


Using payment gateway in test mode, or in production, the customer notes emails cames duplicated

![image](https://github.com/woocommerce/woocommerce/assets/98430442/17422b22-aee5-4c30-9bd2-22b996d6513c)


This is the Source emails from WP SMTP

WooCommerce /www/wwwroot/recarregabox.com/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php:704

![image](https://github.com/woocommerce/woocommerce/assets/98430442/d8c51b54-3707-490b-ae4c-144175cfdf8a)

**Comment by AashikP** [comment]
@unitv  What happens if you use one of the core payment methods like COD / Bank Transfer?

**Comment by rrennick** [comment]
Closing due to lack of feedback.
