### ISSUE TITLE
Inconsistency With How Order Names Are Displayed

### ISSUE THREAD

**Issue by nicholasjeberlin** [woothemes/woocommerce#39389]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When viewing orders at WooCommerce > Orders, they are listed with the Billing Address Name
![image](https://github.com/woocommerce/woocommerce/assets/18408583/8a503440-8dca-46e9-9260-c38b578dc2b2)

When viewing orders at WooCommerce > Home > Orders Module, they are listed with the User Account Name
![image](https://github.com/woocommerce/woocommerce/assets/18408583/a8d8d7d0-b3f9-49bc-be06-8992fc19a7cc)

### Expected behavior

I expect these two areas and any other areas that show the name of the customer (such as in analytics) to consistently use the same values, either the billing name or the account name.

Personally, I would suggest the Billing Name to account for guest orders as these won't have a user account to fetch a name from.

### Actual behavior

Instead, there appears to be a mismatch and the customer name is displayed inconsistently across WooCommerce.

### Steps to reproduce

1. Place a couple of test orders using different billing names, but while logged in to the same user account.
2. Notice that the name next to the order differs when looking at `WooCommerce > Orders` vs `WooCommerce > Home > Orders Module Uses`

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply.

While this is very helpful, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
