### ISSUE TITLE
"woocommerce_order_email_verification_required" hook useless since code exits earlier

### ISSUE THREAD

**Issue by pabloivars** [woothemes/woocommerce#39399]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Method "guest_should_verify_email" exists at line 384, before filter is applied, therefore filter "woocommerce_order_email_verification_required" does not work. 

### Expected behavior

guest_should_verify_email() should evaluate the result through the "woocommerce_order_email_verification_required" filter.

### Actual behavior

Method exits when email is not verified:
`
if ( ! empty( $_POST ) && ! wp_verify_nonce( $_POST['check_submission'] ?? '', 'wc_verify_email' ) ) {
	return true;
}
`

### Steps to reproduce

Place order as guest

### WordPress Environment

WC 7.9.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
cc @coreymckrill since you are working on related flow

**Comment by coreymckrill** [comment]
@pabloivars the line you reference is not actually verifying the email address, it's just verifying the [nonce](https://developer.wordpress.org/apis/security/nonces/) used in conjunction with the email verification form. Furthermore, it only checks the nonce if the `$_POST` global contains something (indicating the email verification form has been submitted). So this shouldn't prevent the `guest_should_verify_email()` method from reaching the hook unless the nonce check fails (i.e. it has expired) after the email verification form has been submitted.

If you're running into a situation where the nonce is failing verification, and it's not the above scenario, can you please describe the details of your situation? Any payment gateways or other plugins that might be customizing the thankyou page?

**Comment by pabloivars** [comment]
@coreymckrill Apologies for the misunderstanding, I didn't mean that the cause was the email verification itself, but rather that it was in the flow of verifying the email.

The exact issue is that the nonce is being checked as long as there is ANY data in $_POST (which is my case), and then if the key doesn't exist an empty string is passed to wp_verify_nonce (making it fail every time).

Perhaps something like this would suffice?
`if ( ! empty( $_POST['check_submission'] ) && ! wp_verify_nonce( $_POST['check_submission'], 'wc_verify_email' ) ) {`

Thanks

**Comment by coreymckrill** [comment]
@pabloivars ok, I think I see what you mean now! Do you think this change will fix the issue?

https://github.com/woocommerce/woocommerce/pull/39479

**Comment by pabloivars** [comment]
@coreymckrill That works just fine for me. Thanks!

**Comment by coreymckrill** [comment]
Let's keep this open until the PR gets merged.
