### ISSUE TITLE
[Epic] Product form template PHP API

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#39391]
## Description

A PHP API for product form template extensibility will be implemented that supports:

- Adding blocks to templates
    - With support for placing in a specific parent (such as section or tab)
    - With ordering (to position in relation to other blocks under the same parent)
- Removing blocks from templates
- Replacing blocks in templates (this might be accomplished simply through removing and adding, as separate actions)
- Hiding blocks in templates conditionally at runtime, based on:
    - Product entity properties

## Issues

In general, issues are dependent/blocked by the issues above them.

### Phase 1: Adding blocks to templates (estimate: 4)

- [x] #39418 (estimate: 3)
- [x] #39421 (estimate: 1)

### Phase 2: Product form template (estimate: 4)

- [x] #39515 (estimate: 2)
- [x] #39516 (estimate: 2)

### Phase 3: Removing blocks from templates (estimate: 3)

- [x] #39420 (estimate: 2)
- [x] #39916 (estimate: 1)

### Phase 3.5: Improving block dependencies (estimate: 5)

- [x] #40022 (estimate: 2)
- [x] #40149 (estimate: 3)

### Phase 4: Documentation (estimate: 6)

- [x] #39536 (estimate: 1)
- [x] #39538 (estimate: 3)

## References

- Project thread: pcQJnU-1FR-p2

**Comment by joshuatf** [comment]
>It seems a little confusing to have both block and field... maybe we could just allow for custom validation in implementations to check for parent when calling add_block()

One option is to protect the `add_block` or any `x_block` methods initially and let the form template make use of these internally while not allowing these methods to be publicly used.

This makes the template as a whole much more guarded, but on the downside might be too restrictive.  I can see cases where blocks are warranted outside of the default "sections" or "groups."

**Comment by mattsherman** [comment]
Removing phase 5 since it is now handled by a separate epic:

- #39434 

Closing this epic as it is complete (it was a few weeks ago!).
