### ISSUE TITLE
Setup Wizard button seems to be not responding

### ISSUE THREAD

**Issue by abiyyuan611** [woothemes/woocommerce#39405]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Setup Wizard button seems to be not responding, not loading anything

### Expected behavior

go to the next step

### Actual behavior

Setup Wizard button seems to be not responding

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/140532901/445de448-9c8d-4549-80c7-6e7ef8df9e53)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://cloudkonveksi.com
Site address (URL): https://cloudkonveksi.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: id_ID
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.21
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 8.0.33-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Server Anda tidak memiliki kelas SoapClient aktif - beberapa plugin yang memakai SOAP mungkin tidak bekerja baik.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wpfh_
Total Ukuran Database: 4.87MB
Ukuran Data Database: 3.44MB
Ukuran Indeks Database: 1.43MB
wpfh_woocommerce_sessions: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_woocommerce_api_keys: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_woocommerce_attribute_taxonomies: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Indeks: 0.06MB + Mesin InnoDB
wpfh_woocommerce_order_items: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_woocommerce_order_itemmeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_woocommerce_tax_rates: Data: 0.02MB + Indeks: 0.06MB + Mesin InnoDB
wpfh_woocommerce_tax_rate_locations: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_woocommerce_shipping_zones: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_woocommerce_shipping_zone_locations: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_woocommerce_shipping_zone_methods: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_woocommerce_payment_tokens: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_woocommerce_payment_tokenmeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_woocommerce_log: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_actionscheduler_actions: Data: 0.02MB + Indeks: 0.11MB + Mesin InnoDB
wpfh_actionscheduler_claims: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_actionscheduler_groups: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_actionscheduler_logs: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_commentmeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_comments: Data: 0.02MB + Indeks: 0.08MB + Mesin InnoDB
wpfh_e_events: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_links: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_options: Data: 2.52MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_postmeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_posts: Data: 0.02MB + Indeks: 0.06MB + Mesin InnoDB
wpfh_term_relationships: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_term_taxonomy: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_termmeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_terms: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_usermeta: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_users: Data: 0.02MB + Indeks: 0.05MB + Mesin InnoDB
wpfh_wc_admin_note_actions: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_wc_admin_notes: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_wc_category_lookup: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_wc_customer_lookup: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_wc_download_log: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_wc_order_coupon_lookup: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_wc_order_product_lookup: Data: 0.02MB + Indeks: 0.06MB + Mesin InnoDB
wpfh_wc_order_stats: Data: 0.02MB + Indeks: 0.05MB + Mesin InnoDB
wpfh_wc_order_tax_lookup: Data: 0.02MB + Indeks: 0.03MB + Mesin InnoDB
wpfh_wc_product_attributes_lookup: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_wc_product_download_directories: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_wc_product_meta_lookup: Data: 0.02MB + Indeks: 0.09MB + Mesin InnoDB
wpfh_wc_rate_limits: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_wc_reserved_stock: Data: 0.02MB + Indeks: 0.00MB + Mesin InnoDB
wpfh_wc_tax_rate_classes: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB
wpfh_wc_webhooks: Data: 0.02MB + Indeks: 0.02MB + Mesin InnoDB

### Post Type Counts ###

attachment: 6
customize_changeset: 1
elementor_library: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Blocksy Companion: oleh CreativeThemes – 1.8.97
WooCommerce: oleh Automattic – 7.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Basis toko: #15 - /shop/
Keranjang: #16 - /cart/
Checkout: #17 - /checkout/
Akun saya: #18 - /my-account/
Syarat dan ketentuan: ❌ Halaman belum diatur

### Theme ###

Name: Blocksy
Version: 1.8.97
Author URL: https://creativethemes.com
Child Theme: ❌ – Jika Anda memodifikasi WooCommerce pada tema induk yang tidak Anda buat secara pribadi
kami sarankan untuk menggunakan tema turunan. Lihat: Cara membuat tema turunan

WooCommerce Support: ✔

### Templates ###

Overrides: blocksy/woocommerce/cart/cart.php
blocksy/woocommerce/cart/mini-cart.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy/woocommerce/myaccount/my-account.php
blocksy/woocommerce/product-searchform.php
blocksy/woocommerce/single-product/tabs/tabs.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-26 15:16:24 +07:00
Options: ✔
Notes: 1
Onboarding: -

### Action Scheduler ###

Selesai: 2
Oldest: 2023-07-25 15:16:30 +0000
Newest: 2023-07-25 15:17:35 +0000

Gagal: 1
Oldest: 2023-07-25 15:18:52 +0000
Newest: 2023-07-25 15:18:52 +0000

Menunggu Persetujuan: 1
Oldest: 2023-07-26 15:16:30 +0000
Newest: 2023-07-26 15:16:30 +0000

### Status report information ###

Generated at: 2023-07-25 22:39:36 +07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
Hi, @abiyyuan611!

I've tried to reproduce this but wasn't able to. Can you confirm if this is still occurring?

If it does, would you be able to open up your browser's developer's console and see if there is any error messages? If so, it would be helpful to share them with us. Thank you so much!

https://github.com/woocommerce/woocommerce/assets/3747241/da8b3f65-9718-43f3-8da6-2efe35757c3e

**Comment by adrianduffell** [comment]
I'll close this out due to inactivity. 

@abiyyuan611, please feel free to-reopen the issue if you are able to provide more information.
