### ISSUE TITLE
[Product Block Editor] Many types of blocks not shown in the product description preview

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39404]
**Description**

After adding many types of blocks using the product description editor modal, the block is not being shown as part of the description preview. Some examples:

* Column ( shows nothing )
* Calendar (shows nothing)
* Single Product (shows nothing)
* WordPress (shows embed URL)
* YouTube (shows embed URL)

**Also when adding only one such block that block does not persist if we try to edit the description the block is not present anymore.**

These blocks **do** appear correctly on the product front end page.

Original report can be found in pb22l9-2eF-p2#comment-2498

**AC**

- [ ] Blocks should persist in the product description when it is the only one block
- [ ] Blocks should be shown in the product description preview after it has been added to the product description

**Comment by mattsherman** [comment]
Updated description to note that this happens for many types of blocks

**Comment by mattsherman** [comment]
This also happens with Columns (see #41176). I'm re-classifying this as a `type: bug` and raising the priority.

**Comment by louwie17** [comment]
Closing this, as this has been fixed by https://github.com/woocommerce/woocommerce/pull/42019
