### ISSUE TITLE
[Product Block Editor] Each product option should be saved as a global attribute used for variations

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39410]
**Description**

Each product option should be saved as a global attribute used for variations. By default, all attributes are created globally. We inform the user about this in the add attributes modal.

AkVNGImLgSqCObTQ3idVn7-fi-1005_134277

Blocked by https://github.com/woocommerce/woocommerce/issues/39231

Epic #36286

**ACs**

- [ ] Each product option should be saved as a global attribute used for variations
- [ ] By default, all attributes are created globally
- [ ] Inform the user about this in the add attributes modal

**Comment by louwie17** [comment]
Done as part of: https://github.com/woocommerce/woocommerce/pull/39548
