### ISSUE TITLE
CSV Export > Import to new site can fail due to reserved slug names

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#39447]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For background, go to the WooCommerce attributes screen and attempt to add an attribute named "Category" and leaving the slug field empty or entering what it will default to anyhow, i.e. `category` and try to save the attribute. You'll be met with a warning and might be inclined to enter a unique string that will bypass this error, e.g. enter `categoryy` and save the attribute.

When the CSV exporter exports products, it uses the attribute name as opposed to the slug. If the exporting from a source site with products with this attribute configured as above, the import will fail

### Expected behavior

Probably for both the name and slug to be included in the exported data to prevent things like this.

### Actual behavior

The import fails

### Steps to reproduce

1. On the attributes screen, an attribute exists with name `Category` and slug `categoryy` and at least one term
2. At least one product has this attribute
3. Export your products
4. Import into a fresh WooCommerce install
5. Experience error

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://import.local
Site address (URL): https://import.local
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 171.20MB
Database Data Size: 123.05MB
Database Index Size: 48.15MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 4.66MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.08MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 25.19MB + Index: 18.06MB + Engine InnoDB
wp_posts: Data: 53.41MB + Index: 2.19MB + Engine InnoDB
wp_term_relationships: Data: 2.02MB + Index: 2.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 29.63MB + Index: 15.58MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.16MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 4052
page: 7
post: 2
product: 650
product_variation: 345

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

WooCommerce Composite Products: by WooCommerce – 8.10.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 6.2.0
WooCommerce Product Add-ons: by WooCommerce – 6.4.4
WooCommerce: by Automattic – 7.9.0

### Inactive Plugins (24) ###

Action Scheduler: by Automattic – 3.6.1
All-in-One WP Migration: by ServMask – 7.76
AutomateWoo: by WooCommerce – 5.8.5
Bookings Generator: by WooCommerce – 1.0.0
Bookings Helper: by WooCommerce – 1.0.3
Cannot Purchase Message Modifier: by Hiro – 0.1b
QM Persist: by  –
Query Monitor: by John Blackbourn – 3.12.3
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.2
WooCommerce Bookings: by WooCommerce – 2.0.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.4.1
WooCommerce Eway Payment Gateway: by WooCommerce – 3.6.2 (update to version 3.6.3 is available)
WooCommerce Mix and Match - Variable Mix and Match: by Kathy Darling – 1.0.0-rc.8
WooCommerce Product Bundles: by WooCommerce – 6.22.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.60
WooCommerce Square: by WooCommerce – 4.0.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Subscription Downloads: by WooCommerce – 1.4.1
WooCommerce Subscriptions: by WooCommerce – 5.3.0
WooCommerce Xero Integration: by WooCommerce – 1.7.58
WordPress Importer: by wordpressdotorg – 0.8.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Migrate DB Anonymization: by Delicious Brains – 0.3.4
WP Migrate Lite: by WP Engine – 2.6.7

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (1) ###

My Muplugin: by Ghost in the machine – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Composite Products ###

Database Version: 8.10.1
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-27 05:15:01 +00:00
Options: ✔
Notes: 74
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.2.0
Connected to WPCOM: Yes
Blog ID: 221497252
Account ID: acct_1NWBiMCHuk7BmOEA

### Action Scheduler ###

Complete: 11,689
Oldest: 2023-07-21 05:16:17 +0000
Newest: 2023-07-27 04:17:42 +0000

Failed: 10
Oldest: 2023-07-24 01:33:52 +0000
Newest: 2023-07-27 04:13:58 +0000

Pending: 31
Oldest: 2023-07-27 04:17:48 +0000
Newest: 2023-07-28 02:46:33 +0000

### Status report information ###

Generated at: 2023-07-27 04:17:51 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@WillBrubaker Thanks for creating the issue. This occurs with both `Tag` and `Category`. 

> Slug "tag" is not allowed because it is a reserved term. Change it, please.
> Slug "category" is not allowed because it is a reserved term. Change it, please.

Products already have tag and category fields and the store admin has been warned that these terms are reserved so very few will use them. For the exceptions who do bypass the warning, the products can be imported by creating the attribute before running the import.

Since this is an edge case and there is an easy work around, I'm going to close the issue.
