### ISSUE TITLE
[Product Block Editor] Use attributes as filter

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39443]
**Description**

Local attributes and global attributes with the Use as filter box unchecked are marked with a small filter icon. It is displayed in the Attributes and Options lists. When the user hovers over the icon, they will see a tooltip explaining that a local attribute will not be used for filtering, etc.

In Attributes, those with the `Use as filter` box unchecked are marked with a small filter icon displayed in the list. When the user hovers over the icon, they will see a tooltip.

In Attributes, those with the `Show in product details` box unchecked are marked with a small eye icon displayed in the list. When the user hovers over the icon, they will see a tooltip.

AkVNGImLgSqCObTQ3idVn7-fi-2780_272991

**Epic**

#36286

**ACs**

- [ ] Create the `Use as filter` in the modal
- [ ] All attributes with the `Use as filter` box unchecked are marked with a small filter icon
- [ ] Display the filter icon in the Attributes and Options lists
- [ ] When the user hovers over the icon, they will see a tooltip explaining that a local attribute will not be used for filtering
- [ ] Attributes with the `Show in product details` box unchecked are marked with a small eye icon displayed in the list. 
- [ ] When the user hovers over the eye icon, they will see a tooltip

**Comment by mdperez86** [comment]
@jarekmorawski I'm a little confuse here.

> Local attributes and global attributes with the Use as filter box unchecked are marked with a small filter icon

Local attributes can be filterable? What should happen if the user uncheck the `Use as filter` on a global attribute? Should we convert it into a local attribute? If that is the case then the list should contains global attributes with the `Not filterable` icon. What is a custom attribute? Is it the same as local attribute?

**Comment by jarekmorawski** [comment]
> Local attributes can be filterable?

**Comment by jarekmorawski** [comment]
> Local attributes can be filterable?

Nope. This is for existing products that may use local attributes for variations. We must show them in the list and let the users know they're not filterable. We should also show this message: AkVNGImLgSqCObTQ3idVn7-fi-1642_218064

> What should happen if the user uncheck the Use as filter on a global attribute?

It shouldn't be displayed in filters on the catalog/shop all page or anywhere else where the product grid is displayed. Note that it's nice to have because I don't think this functionality exists in the current experience. Nothing else would change about such attribute—it'd still be shown in the list and used to create variations.

> What is a custom attribute? Is it the same as local attribute?

Yes. In Figma, attributes are called `Global` and `Custom`, but we're waiting for the final UX copy review to settle on naming.

**Comment by louwie17** [comment]
> It shouldn't be displayed in filters on the catalog/shop all page or anywhere else where the product grid is displayed. Note that it's nice to have because I don't think this functionality exists in the current experience. Nothing else would change about such attribute—it'd still be shown in the list and used to create variations.

@jarekmorawski in relation to this, if I understand correctly when users un-select this it should removed it from one of the attribute options within the `Filter by Attribute` block?

If so, I think this ends up being a bit more complicated, as the filter by attribute block makes you pick a specific attribute whenever you use it, so we could have several instances across multiple pages. I am not sure if this is being filtered on render and we can add a specific config to toggle this, we did have to check with the blocks team for this.

For now I will just add the tooltip for local attributes.

**Comment by louwie17** [comment]
For extra context it looks like it sets/gets its attributes here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/AttributeFilter.php#L26 using the `wc_get_attribute_taxonomies` function. 

Which uses the `woocommerce_attribute_taxonomies` filter incase we did want to filter some of these out by this setting.

**Comment by jarekmorawski** [comment]
> if I understand correctly when users un-select this it should removed it from one of the attribute options within the Filter by Attribute block?

That's correct.

> I am not sure if this is being filtered on render and we can add a specific config to toggle this, we did have to check with the blocks team for this.

It may not yet, but AFAIK, the team is looking into it. It'd be nice to have this logic in place on our side for when it becomes possible in the site editor. If that isn't feasible at the moment, we can skip this AC and return to it in the future. In that case, the box would be checked and disabled by default for global attributes, and not visible at all for local/custom attributes.
