### ISSUE TITLE
[Product Block Editor] Disable tabs in parent product page with variations

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39459]
**Description**

When the user visits the Pricing, Inventory, or Shipping tabs when variations are added, we show a message reading:

`This product has options, such as size or color. You can now manage each variation's price and other details individually. [Go to Variations]`

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-2780_278412

**Epic**

#36286

**ACs**

- [ ] When a product has at least one variation, show a message at the top of the form inside the Pricing, Inventory, and Shipping tabs.
- [ ] The message reads: `This product has options, such as size or color. You can now manage each variation's price and other details individually. [Go to Variations]`
- [ ] The `Go to Variations` button takes the user to the `Variations` tab.
- [ ] The message is not dismissible.

**Comment by mdperez86** [comment]
@jarekmorawski 

`Manage individual variation details in the Options tab` is outdated, now the tab name is `Variations`, could you check if the new message is correct for the AC2 please?

Also, what are the disable tabs? Do you have a figma reference link to share?

**Comment by jarekmorawski** [comment]
Sure thing! Just updated the description and added a Figma link.
