### ISSUE TITLE
[Product Block Editor] Create several global attributes with the same name

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39452]
**Description**

Users can create several global attributes with the same name. We’d generate a unique slug for each based on its name. For example, the slugs for Color and Color would be ‘color’ and ‘color-2’.

**Epic**

#36286

**ACs**

- [ ] User can create several global attributes with the same name
- [ ] Attributes with the same name should have an auto generated unique slug like ‘color’ and ‘color-2’

**Comment by mdperez86** [comment]
@jarekmorawski Do we have a design for the use case where the user creates multiple global attributes with the same name?

**Comment by jarekmorawski** [comment]
No. Can it be an issue? We'd just show `Color` and `Color` in the list. Later on, we'd consider adding slugs or some other kind of ID to help tell them apart.

**Comment by mdperez86** [comment]
@jarekmorawski 

Due to the way the attributes dropdown is being implemented we don't have a way to add a new Attribute with an existing name. It's the same thing for the terms.

<img width="921" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/b042d6f6-f1a1-4c13-a68f-f56dcc916bc6">

We can create a different one but not the same.

<img width="928" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/c5e4693b-f777-4813-9434-c320b9b64598">

**Comment by jarekmorawski** [comment]
Alrighty. Can we add it, then? In my previous comment, I suggested using slugs to differentiate attributes with the same name. We could then show the slug on hover to help the user tell attributes apart.

**Comment by mdperez86** [comment]
> Alrighty. Can we add it, then? In my previous comment, I suggested using slugs to differentiate attributes with the same name. We could then show the slug on hover to help the user tell attributes apart.

@jarekmorawski are you saying that, we should remove the restriction to let the user adds as many attributes as they want with the same name, right? Of course slugs should be autogenerated without conflicting

**Comment by jarekmorawski** [comment]
~~Yes! It even says so in the ACs. 🙂~~ Sorry, I misunderstood. Nope, we should let users add as many attributes with the same name as they want.
