### ISSUE TITLE
[Product Block Editor] Show an overlay in the Pricing, Inventory, and Shipping tabs

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39457]
**Description**

When the variations are created show an overlay in the Pricing, Inventory, and Shipping tabs of the parent product.
AkVNGImLgSqCObTQ3idVn7-fi-2780_278432

**Epic**

#36286

**ACs**

- [ ] When the variations are created show an overlay in the Pricing tab
- [ ] When the variations are created show an overlay in the Inventory tab
- [ ] When the variations are created show an overlay in the Shipping tab

**Comment by mdperez86** [comment]
@jarekmorawski could you provide a design for this please? I could not find anything about the tabs overlay in the shared link. Is this the same thing described as part of this issue https://github.com/woocommerce/woocommerce/issues/39459?

cc: @louwie17 @AnnaMag

**Comment by jarekmorawski** [comment]
Correct. It's the same notice/overlay. Would it make sense to close one of the issues?
