### ISSUE TITLE
Stock Quantity field is defaulting to value of `1`. 

### ISSUE THREAD

**Issue by jdamner** [woothemes/woocommerce#39475]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a product is inserted via the REST API and has stock management enabled and no stock value is provided, the default value shown in the editing interface is 1, where the value shown in any other area is zero. 

This can cause unexpected behaviour, such as if a product is inserted via the API then a user goes in to modify the content and saves, the stock automatically increases to one without any user interaction. 

The change was made in https://github.com/woocommerce/woocommerce/pull/37304
The PR isn't clear what issue it was addressing, but changing the default field output doesn't feel like the most robust way to resolve any issues where stock value is null. 

### Expected behavior

I expect that either when the rest API receives the request to add a product and the stock management is enabled but no stock value is provided that: 
 - The REST API rejects the request as bad-input
 - The Product is inserted with a `0` stock value (instead of `null`) when a product is created via the API with the stock management enabled but without a stock quantity value.

Alternatively, when the stock quantity input field is output in the admin and a `null` value is encountered, the default should be `0` or blank. Defaulting to `1` seems like a bad translation of `null`. I assume there's a sensible reason why the changes in #37304 was made so that's why this didn't make the list above :) 

### Actual behavior

The quantity input field in the product editor defaults to `1` when the value is `null`. 

### Steps to reproduce

1. Insert a product via the REST API omitting the stock amount - POST /wp-json/wc/v3/products:
```json
{
  "name": "Stock Quantity Input Test",
  "type": "simple",
  "regular_price": "21.99",
  "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
  "manage_stock": true
}
```

2. Visit the newly created product in the admin area. In the product list-screen it shows as "Out-Of-Stock (0)". Click to edit the product
3. Change the title of the product
4. In the product list screen it now shows as "In Stock (1)" despite no interaction with the stock input.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888
Site address (URL): http://localhost:8888
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Debian)
PHP Version: 8.0.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 11.0.2-MariaDB-1:11.0.2+maria~ubu2204
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 3.84MB
Database Data Size: 2.40MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.9.0

### Inactive Plugins (1) ###

Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-28 15:36:18 +00:00
Options: ✔
Notes: 2
Onboarding: skipped

### Action Scheduler ###

Pending: 3
Oldest: 2023-07-28 15:36:19 +0000
Newest: 2023-07-28 15:40:32 +0000

### Status report information ###

Generated at: 2023-07-28 15:42:16 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@octaedro do you recall why the default stock quantity was set to `1` here?
https://github.com/woocommerce/woocommerce/pull/37304/files#diff-c22a708717c32aa910d9724f6abb81f001d1c3166323ad7ced296e2bd828e82bR53

**Comment by octaedro** [comment]
Hi @coreymckrill,
That change was part of an epic aimed at [improving the layout of the inventory fields](https://github.com/woocommerce/woocommerce/issues/37102). I don't remember exactly why we set that value to 1. Here is the design: [zs56kcy53K7GoGhgyjcQ2R-fi-210%3A30925](https://href.li/?https://www.figma.com/file/zs56kcy53K7GoGhgyjcQ2R/?node-id=210%3A30925).

This is also expected in the new product editor:

![Screenshot 2023-08-22 at 15 28 36](https://github.com/woocommerce/woocommerce/assets/1314156/edefda3a-ed21-4463-a8c9-9ec75dd054f8)


//CC: @jarekmorawski @AnnaMag

**Comment by jdamner** [comment]
Since finding this I've found a few other occasions that sets the stock quantity to `null`, such as if a product is changed from simple to external, and then back to simple. Changing to external sets the stock null, and isn't changed when set to simple.

**Comment by barryhughes** [comment]
> When stock tracking is enabled for the first time, we default to quantity=1 (now we default to 0, which creates lots of issues).

@jarekmorawski given the feedback, is there a different way we could handle this—for instance, what if we only default to `1` if the product has not yet been saved?

Otherwise, things are both inconsistent (because, the inventory shows as `1` unit in the editor but `Out of stock (0)` in the list table) and, perhaps more importantly, it means that products being created programmatically (where we want to manage stock, but the level has not been ascertained yet) might accidentally be set to inventory of 1.

**Comment by AnnaMag** [comment]
related https://github.com/woocommerce/woocommerce/issues/39862

**Comment by jarekmorawski** [comment]
Makes sense! Frankly, I had no idea we're still treating the new value as `null`. This change should only affect the admin experience, so Barry's suggestion above makes sense. We'd limit the change only to the admin UI, meaning that we'd default to 1 when the user first flips the inventory tracking toggle and saves the product. Before that (and in all API-related requests), we should default to `null`. cc @pmcpinto

**Comment by pmcpinto** [comment]
I agree. @louwie17 I've added this to the current cycle backlog-

**Comment by octaedro** [comment]
Hi @jarekmorawski and @pmcpinto,

> Makes sense! Frankly, I had no idea we're still treating the new value as null. This change should only affect the admin experience, so Barry's suggestion above makes sense. We'd limit the change only to the admin UI, meaning that we'd default to 1 when the user first flips the inventory tracking toggle and saves the product. Before that (and in all API-related requests), we should default to null.

I'm not clear about this issue. We're setting the [value to 1](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-inventory.php#L59) only when presenting the form (in the view), and that value is only being saved when pressing `Publish`. Should we change that behavior?

**Comment by pmcpinto** [comment]
Hey @octaedro IIUC, the problem happens when a product is created via the REST API with no stock value. When it's edited/saved in the admin UI, it defaults to 1. Do you think the easiest way to solve this is to revert the change and default to 0?

**Comment by barryhughes** [comment]
☝🏼 That matches my understanding.

Always defaulting to `0` would be one solution. Defaulting to `1` (current behavior) *only for new products* would be another, perhaps.

**Comment by octaedro** [comment]
Thank you @pmcpinto and @barryhughes for your feedback.

What you mentioned sounds good to me. I think that it's a good idea to revert [the PR](https://github.com/woocommerce/woocommerce/pull/37304) that sets the quantity value to 1 when the stock tracking is enabled.

I'll create an issue for that.

**Comment by octaedro** [comment]
I just created the issue https://github.com/woocommerce/woocommerce/issues/46342 to tackle this error.

**Comment by octaedro** [comment]
Closing this issue in favor of https://github.com/woocommerce/woocommerce/issues/46342.
