### ISSUE TITLE
[Woo AI]Use the site's saved language rather than detect the language.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#39488]
The Woo AI plugin, when generating product descriptions, will attempt to determine the language of the content and will generate a product description in the same language, however, it's not perfect.
We sometimes get some language output hallucination when generating content via the Woo AI plugin. For example, the title could be written in English but the product description output could be generated using Spanish. 
The assumption we made previously was that multilingual plugins like WPML created duplicate posts for products (one for each supported language) and that we couldn't always use the site language.
However, this assumption may be wrong; perhaps it's worth spending a bit of time researching alternatives.

**Comment by tommyshellberg** [comment]
It seems like this is still true:
https://wpml.org/forums/topic/i-dont-want-to-duplicate-pages/

> WPML will always create another post ID for any translation or duplicate you create.

But, I haven’t tested it myself yet.

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
