### ISSUE TITLE
Additional track changes on Core Profiler extensions step

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#39484]
### Issue description

Based on the design call on 26th July, we need to add these tracks in order to understand the extensions step better:

1. Track what plugins are selected and not selected when continuing the extension step
2. Track individual plugin installation
3. Optionally, track plugin installation completion from `wc_admin_daily` cronjob. Note that we may need to "save" users' ID or anonID in order to be able to properly make funnels.

### Acceptance criteria

1. Add track `wcadmin_coreprofiler_store_extensions_continue` with props `selected: {array_of_plugin_slug}` and `unselected:   {array_of_plugin_slug}` arrays to list extensions that are selected and otherwise.
1. Add track `wcadmin_coreprofiler_store_extensions_installed_single` with props `extension: {plugin_slug}` and `success: {true/false}`
1. Optionally, add track `wcadmin_coreprofiler_extensions_cronjob` with props `installed_extensions: {array_of_plugin_slug}`, `failed_extensions: {array_of_plugin_slug}`

Edit: On the array of plugin slugs, I think it'll be good if we sort it in a way that's consistent in all our tracks which might make some types of analysis easier.

**Comment by ilyasfoo** [comment]
Hey, @moon0326 and @verofasulo, can you look at the tracks I've proposed here and see if they're alright?

**Comment by moon0326** [comment]
Thank you for creating the issue 👍 

LGTM!

**Comment by ilyasfoo** [comment]
> Add track wcadmin_coreprofiler_store_extensions_installed_single with props extension: {plugin_slug} and success: {true/false}

Actually, `wcadmin_coreprofiler_store_extensions_installed_and_activated` already exists and serves a redundant purpose of the proposed `wcadmin_coreprofiler_store_extensions_installed_single`. Skipping this unless @adrianduffell if I've missed something since you've floated the original idea of tracking individual installs as and when it's installed.

> Optionally, add track wcadmin_coreprofiler_extensions_cronjob with props installed_extensions: {array_of_plugin_slug}, failed_extensions: {array_of_plugin_slug}

It seems the backend tracks utility doesn't support non-user [request origin](https://github.com/woocommerce/woocommerce/blob/4d685c361ac3d045013331d572226bced459dae8/plugins/woocommerce/includes/tracks/class-wc-tracks.php#L87C1-L90). I'm skipping this one since supporting non-user request seems to be too much to add in this scope.
