### ISSUE TITLE
Method get_type() on class WC_Product is returning incorrect product type on variable product

### ISSUE THREAD

**Issue by heymarvinsantos** [woothemes/woocommerce#39480]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using WC_Product get_type() method, the returned value is "simple" for any product type

### Expected behavior

Return "variable" string

### Actual behavior

Returns "simple" string

### Steps to reproduce

1. Create a variable product
2. Add a couple of parameters that can be used for variables (like "test" for the name and "test 1|test2" for the value )
3. Create variation from parameters and set prices (like 10 for one and 20 for the other)
4. Save product and copy product ID generated.
5. Try printing the product type on another page using class WC_Product as below:

```
// Test
$product_id = 123; // your product ID
$product    = new WC_Product($product_id);
echo '<pre>WC_Product: '. $product->get_type().'</pre>'; // returns "simple"

// Workaround
$factory    = new WC_Product_Factory();
$product2   = $factory->get_product($product_id);
echo '<pre>WC_Product_Factory: '.$product2->get_type().'</pre>'; // returns "variable"
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): ****
Site address (URL): ****
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/5.1.0
PHP Version: 8.2.7
PHP Post Max Size: 300 MB
PHP Time Limit: 178
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.42-google
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_gdh2hgyacg_
Total Database Size: 4.70MB
Database Data Size: 3.20MB
Database Index Size: 1.50MB
wp_gdh2hgyacg_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_gdh2hgyacg_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gdh2hgyacg_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_postmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gdh2hgyacg_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gdh2hgyacg_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdh2hgyacg_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_gdh2hgyacg_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gdh2hgyacg_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdh2hgyacg_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gdh2hgyacg_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdh2hgyacg_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdh2hgyacg_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 2
product_variation: 6
revision: 1
shop_order: 17
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WPIDE - File Manager & Code Editor: by XplodedThemes – 3.4.7
WooCommerce: by Automattic – 7.9.0

### Inactive Plugins (2) ###

Classic Editor: by WordPress Contributors – 1.6.3
WooCommerce Product Add-ons: by WooCommerce – 5.0.3

### Dropin Plugins (2) ###

db-error.php: db-error.php
fatal-error-handler.php: fatal-error-handler.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.4.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-30 07:42:45 -04:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Complete: 55
Oldest: 2023-07-25 03:43:57 -0400
Newest: 2023-07-29 05:18:09 -0400

Failed: 1
Oldest: 2023-07-25 03:53:48 -0400
Newest: 2023-07-25 03:53:48 -0400

Pending: 1
Oldest: 2023-07-30 03:26:52 -0400
Newest: 2023-07-30 03:26:52 -0400

### Status report information ###

Generated at: 2023-07-29 05:20:43 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
```
$product_id = 123; // your product ID
$product    = new WC_Product();
```

@heymarvinsantos The `WC_Product` constructor does not have access to the `$product_id` variable and does not load an existing product unless the ID is passed as a parameter. To load an existing product you should use `wp_get_product( $product_id )`. I'll close this issue as a question.

**Comment by heymarvinsantos** [comment]
@rrennick there was a mistake on my example. However the issue still persists with the ID passed as a parameter

**Comment by rrennick** [comment]
@heymarvinsantos Here's the documentation on the [WC_Product constructor](https://woocommerce.github.io/code-reference/classes/WC-Product.html#method___construct).

**Comment by heymarvinsantos** [comment]
I will wait for someone else willing to either test what I sent or report as another ticket.  Thank for your time...
