### ISSUE TITLE
 Vulnerability Audit of the WooCommerce Plugin 

### ISSUE THREAD

**Issue by laoquanshi** [woothemes/woocommerce#39505]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 Stored xss exists in the product review function module. Attackers can use this API to construct malicious xsspyload without authorization to attack the store and steal administrator cookies to report to cve 

### Expected behavior

<img width="416" alt="image" src="https://github.com/woocommerce/woocommerce/assets/110451039/d3fef916-7283-4f14-b749-f409b62304cd">

### Actual behavior

<img width="415" alt="image" src="https://github.com/woocommerce/woocommerce/assets/110451039/22a9e6ed-2c36-4fcc-9ba4-7b58e859f914">

### Steps to reproduce

<img width="415" alt="image" src="https://github.com/woocommerce/woocommerce/assets/110451039/fa7ca76c-7bc5-431d-9e17-cf0e3fad8f0b">

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_CN
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Win64) OpenSSL/1.1.1b mod_fcgid/2.3.9a mod_log_rotate/1.02
PHP Version: 7.3.4
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ 您的服务器未启用 SoapClient 类 - 某些使用SOAP的支付网关插件可能会罢工。
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
数据库总的大小: 3.67MB
数据库数据大小: 3.34MB
数据库索引大小: 0.33MB
wp_woocommerce_sessions: 数据：0.01MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_api_keys: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_attribute_taxonomies: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_downloadable_product_permissions: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_order_items: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_order_itemmeta: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_tax_rates: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_tax_rate_locations: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_shipping_zones: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_shipping_zone_locations: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_shipping_zone_methods: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_payment_tokens: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_payment_tokenmeta: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_woocommerce_log: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_actionscheduler_actions: 数据：0.02MB + 索引：0.02MB + 引擎 MyISAM
wp_actionscheduler_claims: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_actionscheduler_groups: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_actionscheduler_logs: 数据：0.01MB + 索引：0.01MB + 引擎 MyISAM
wp_commentmeta: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_comments: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_links: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automations: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automation_runs: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automation_run_logs: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automation_run_subjects: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automation_triggers: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_automation_versions: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_custom_fields: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_dynamic_segment_filters: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_feature_flags: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_forms: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_log: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_migrations: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_mailpoet_newsletters: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_newsletter_links: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_newsletter_option: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_newsletter_option_fields: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_mailpoet_newsletter_posts: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_newsletter_segment: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_newsletter_templates: 数据：1.05MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_scheduled_tasks: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_mailpoet_scheduled_task_subscribers: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_segments: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_mailpoet_sending_queues: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_settings: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_bounces: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_clicks: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_forms: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_newsletters: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_opens: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_unsubscribes: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_statistics_woocommerce_purchases: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_stats_notifications: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_subscribers: 数据：0.00MB + 索引：0.02MB + 引擎 MyISAM
wp_mailpoet_subscriber_custom_field: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_subscriber_ips: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_subscriber_segment: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_subscriber_tag: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_tags: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_user_agents: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_mailpoet_user_flags: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_options: 数据：2.11MB + 索引：0.05MB + 引擎 MyISAM
wp_postmeta: 数据：0.02MB + 索引：0.02MB + 引擎 MyISAM
wp_posts: 数据：0.06MB + 索引：0.02MB + 引擎 MyISAM
wp_termmeta: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_terms: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_term_relationships: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_term_taxonomy: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_usermeta: 数据：0.01MB + 索引：0.01MB + 引擎 MyISAM
wp_users: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_admin_notes: 数据：0.03MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_admin_note_actions: 数据：0.02MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_category_lookup: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_customer_lookup: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_download_log: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_order_coupon_lookup: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_order_product_lookup: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_order_stats: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_order_tax_lookup: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_product_attributes_lookup: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_product_download_directories: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_product_meta_lookup: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_rate_limits: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_reserved_stock: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM
wp_wc_tax_rate_classes: 数据：0.00MB + 索引：0.01MB + 引擎 MyISAM
wp_wc_webhooks: 数据：0.00MB + 索引：0.00MB + 引擎 MyISAM

### Post Type Counts ###

attachment: 6
guest_author: 1
mailpoet_page: 1
page: 8
post: 19
product: 7
revision: 88
shop_coupon: 1
shop_order: 2
wp_global_styles: 1
wpcode: 7

### Security ###

Secure connection (HTTPS): ❌
					您的站点当前未使用HTTPS。了解HTTPS和SSL证书。
Hide errors from visitors: ✔

### Active Plugins (5) ###

WPCode Lite: 来自 WPCode – 2.1.0
MailPoet: 来自 MailPoet – 4.22.0
Pinterest for WooCommerce: 来自 WooCommerce – 1.3.6
WooCommerce PayPal Payments: 来自 WooCommerce – 2.2.0
WooCommerce: 来自 Automattic – 7.9.0

### Inactive Plugins (3) ###

Jetpack: 来自 Automattic – 12.3
Media Library Categories: 来自 Jeffrey-WP – 2.0.1
Molongui Authorship: 来自 Molongui – 4.6.19

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

商店基础链接: #15 - /shop/
购物车: #16 - /cart/
结账: #17 - /checkout/
我的帐户: #18 - /my-account/
条款和条件: ❌ 页面没有设置

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://cn.wordpress.org
Child Theme: ❌ – 如果您正在修改WooCommerce时没有创建个性化的父主题，我们建议您使用一个子主题，请参阅：如何创建一个子主题
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: CN
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-01 08:06:54 +08:00
Options: ✔
Notes: 66
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: http://localhost/wordpress?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

完成: 57
Oldest: 2023-07-31 16:08:22 +0800
Newest: 2023-08-01 15:27:14 +0800

已失败: 2
Oldest: 2023-08-01 13:21:47 +0800
Newest: 2023-08-01 14:27:26 +0800

即将进行的: 4
Oldest: 2023-08-01 15:27:26 +0800
Newest: 2023-08-01 16:08:23 +0800

### Status report information ###

Generated at: 2023-08-01 15:27:24 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@laoquanshi Please see our policy on [reporting security issues](https://github.com/woocommerce/woocommerce#reporting-security-issues).
