### ISSUE TITLE
[Bug] Can't turn off the new product form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39512]
We've received reports from users who cannot turn off the new product editing UX. They tried restarting the machine and clearing the cache. Every time they click turn-off button in the ellipsis menu, they see the following error:

> Action failed. Please refresh the page and retry.

**Comment by AnnaMag** [comment]
@jarekmorawski it is a known issue and [was fixed](https://github.com/woocommerce/woocommerce/pull/39317) in 8.0.
