### ISSUE TITLE
Register SimpleProductTemplate and add hook to allow for registered templates to be modified

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#39516]
Blocked by #39814

## Description

The `SimpleProductTemplate` template implemented in #39814 will be registered via `BlockTemplateRegistry::register()`.

The `Automattic\WooCommerce\Internal\Admin\BlockTemplateRegistry\BlockTemplateRegistry` class will have a filter added to it that allows for templates to be modified by plugins when a template is registered.

```php
// called in BlockTemplateRegistry::register()
do_action( 'woocommerce_block_template_register', &$template );

// in plugin
function MY_PREFIX_on_register_template( BlockTemplateInterface &$template ) {
    // modify $template using API
}

add_action( 'woocommerce_block_template_register', 'MY_PREFIX_on_register_template', 10, 1 );
```

## Acceptance criteria

- [ ] The `SimpleProductTemplate` template is registered via `BlockTemplateRegistry::register()`
- [ ] The `woocommerce_block_template_register` action is called whenever a template is registered via `BlockTemplateRegistry::register()`
- [ ] The hook can be used to modify the templates, using the API.

**Comment by mattsherman** [comment]
@joshuatf @louwie17 This is the issue where we will register the `SimpleProductTemplate` from #39814 and also introduce an action that will allow plugins to modify templates when they are registered.

I'm thinking that we introduce a `woocommerce_block_template_registry_on_register` action that gets called in `BlockTemplateRegistry::register()`. The template bring registered gets passed via reference to the action hooks, allowing for the template to be modified via the API.

Any thoughts or concerns about this approach?

**Comment by louwie17** [comment]
> Any thoughts or concerns about this approach?

@mattsherman that approach sounds good to me, no issues on my end.
Although I do wonder if we want to expose another hook at time of retrieval that exposes some additional information that may impact how a plugin would modify the template. But at the moment we don't even do that, so I may be overthinking this.

In terms of the hook, the `on_register` sounds kinda strange, could you just do: `woocommerce_block_template_register` or `woocommerce_register_block_template`?

Also is there much benefit of passing the template by reference explicitly? I thought if we pass a class instance around we pass the reference by default anyway.
So there is technically no difference between `&$template` and `$template`, but maybe I am confused on how references work in PHP.

**Comment by mattsherman** [comment]
> @mattsherman that approach sounds good to me, no issues on my end. Although I do wonder if we want to expose another hook at time of retrieval that exposes some additional information that may impact how a plugin would modify the template. But at the moment we don't even do that, so I may be overthinking this.

I'm not sure what that would look like or what the scenarios would be where that would be needed vs modifying the template at registration time. I'd say let's leave that out for now and if we determine a need later on it could be added.

> In terms of the hook, the `on_register` sounds kinda strange, could you just do: `woocommerce_block_template_register` or `woocommerce_register_block_template`?

Yeah, either of those would work. I'm a fan of "on", "after", "before" sort of naming, to be clear, but it can be wordy or not really add value. By using "on_register" I was attempting to make it clear that the action wasn't used to register templates, but rather called when templates were registered.

> Also is there much benefit of passing the template by reference explicitly? I thought if we pass a class instance around we pass the reference by default anyway. So there is technically no difference between `&$template` and `$template`, but maybe I am confused on how references work in PHP.

Objects are passed by identifier by default, which in practicality is similar to "by reference", so I think you are right... we don't need to pass by reference in this case.

https://www.php.net/manual/en/language.oop5.references.php
