### ISSUE TITLE
[Enhancement]: HPOS ListTable hook to insert custom order results

### ISSUE THREAD

**Issue by jitman** [woothemes/woocommerce#39519]
### Describe the solution you'd like

In `/woocommerce/src/Internal/Admin/Orders/ListTable.php` I appreciate the two hooks on lines 389 and 398 to add custom query args, but I'd appreciate a hook right around 403 that let's others return a custom set of orders. 

### Describe alternatives you've considered

I can use the `woocommerce_order_query` hook in the `class-wc-order-query.php`:88 in the mean time and limit where it's overridden, but I'd appreciate a hook within the specific ListTable context.

### Additional context

I have my own custom order table I'd like to use for queries so I can load a customized list of results.

**Comment by Konamiman** [comment]
Closing because there's already an existing filter that does the job (see  https://github.com/woocommerce/woocommerce/pull/40392#issuecomment-1735814138).
