### ISSUE TITLE
[Customize Your Store] Intro screen components

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39528]
## User Story

As a new merchant, I want to be presented with simple flows to customize my store, so that I can start selling sooner.

## Design

Mrk6SERPZ4KrFHSjM0a8TK-fi-2631%3A250549

![Image](https://user-images.githubusercontent.com/9312929/257667942-173a603b-db83-4e19-b371-0a87c667effb.png)

## Acceptance Criteria

```
Feature: Customize Your Store

  Scenario: User opens the Customize Your Store Task
    When the User opens the Customize Your Store Task
    Then two options are presented: "Design with AI" and "Select a professionally designed theme"

  Scenario: Design with AI is selected
    Given the Customize Your Store Task is open
    When the User presses the "Design with AI" button
    Then proceed to the next step in the wizard

  Scenario: Professionally designed theme is selected
    Given the Customize Your Store Task is open
    When the User presses the "Browse all themes" button
    Then proceed to Appearance > Themes

```

**Comment by chihsuan** [comment]
Hey @crunnells 👋  Do you think you will be able to work on it this week? 🙂

**Comment by crunnells** [comment]
Yep, I'm on it

**Comment by moon0326** [comment]
Hey @chihsuan @adrianduffell ✋ 

I'm working on implementing the new design and a few missing interactions. What should happen when a user clicks on a theme?
