### ISSUE TITLE
CRUD: Changes to existing options with `set_attributes()` are not stored when calling `save()`

### ISSUE THREAD

**Issue by kanlukasz** [woothemes/woocommerce#39532]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have an global attribute `pa_status` with values such as `new`, `old`, `custom`. This attribute is used in my products.
I would like to remove the `old` value from a particular product.

So I'm trying to use CRUD in this way:

```PHP
$id_product = 73886;
$attribute_name = 'pa_status';
$id_attribute_value_to_remove = 1330;  // name: old

$product = wc_get_product($id_product);
$attributes = $product->get_attributes();

if (isset($attributes[$attribute_name])) {
    $attributes[$attribute_name]['options'] = array_filter(
        $attributes[$attribute_name]['options'],
        function ($value) use ($id_attribute_value_to_remove) {
            return $value !== $id_attribute_value_to_remove;
        }
    );
}
$product->set_attributes($attributes);
$product->save();
```

### Expected behavior

The attribute in the product should be updated. The value `old` should be removed

### Actual behavior

As you can see, I use the `save()` method at the end, but nothing changes in the product. The attributes are not updated

### Steps to reproduce

See `Describe the bug`

### WordPress Environment

```
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.0.29
PHP Post Max Size: 64 MB
PHP Time Limit: 200
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@kanlukasz Github is for reporting bugs or enhancement requests not support. In the future I'd suggest asking this type of question in the Community Slack. I'll mark this as a support question which will post some useful links and close it. 

You are most likely seeing the issue because the attribute name in the code includes `pa_`. You should use the attribute slug that is shown when you edit the attribute in the dashboard.

**Comment by kanlukasz** [comment]
> @kanlukasz Github is for reporting bugs or enhancement requests not support. In the future I'd suggest asking this type of question in the Community Slack. I'll mark this as a support question which will post some useful links and close it.

@rrennick I know what Github is used for. I'm reporting this as a bug because it's not working properly.
I understand that I may be the one who is wrong, but have you even tried to replicate this scenario at your environment?

> You are most likely seeing the issue because the attribute name in the code includes `pa_`. You should use the attribute slug that is shown when you edit the attribute in the dashboard.

In my opinion, you are wrong, because:
- if you dump it using `var_dump`, you will see the key has `pa_`
- If you dump `$attributes = $product->get_attributes()` using `var_dump`, before and after the `if` statement, you will see that the value is properly removed.

So the conclusion is the `save()` or `set_attributes()` method has some kind of problem.

**Comment by rrennick** [comment]
> I know what Github is used for. I'm reporting this as a bug because it's not working properly.

@kanlukasz Let me clarify. Please create a global product attribute as follows

- Name: `PA Example`
- Slug: `pa_example`

Now edit the attribute you just created and see that the slug is `example`. If you prefix an attribute slug with `pa_`, WooCommerce removes the prefix.

Using WP shell I ran the following
```
wp> $product = wc_get_product($id_product);
...
wp> $attributes = $product->get_attributes();
array(2) {
  'size' =>
  class WC_Product_Attribute#6144 (1) {
    protected $data =>
    array(6) {
      'id' =>
      int(0)
      'name' =>
      string(4) "Size"
      'options' =>
      array(1) {
        ...
      }
      'position' =>
      int(0)
      'visible' =>
      bool(true)
      'variation' =>
      bool(true)
    }
  }
  'weight' =>
  class WC_Product_Attribute#6145 (1) {
    protected $data =>
    array(6) {
      'id' =>
      int(0)
      'name' =>
      string(6) "Weight"
      'options' =>
      array(1) {
        ...
      }
      'position' =>
      int(1)
      'visible' =>
      bool(true)
      'variation' =>
      bool(true)
    }
  }
}
```

Note that the array keys do not have the `pa_` prefix that you see in the database.

**Comment by kanlukasz** [comment]
> Now edit the attribute you just created and see that the slug is example. If you prefix an attribute slug with pa_, WooCommerce removes the prefix.

That's true, but if I dump `get_attributes()`, I see something different from you.
I will show a new step-by-step example below:

1. Create new attribute with name: `Cars`

2. Add terms: `honda`, `ford`, `dodge`

3. Now it looks like this:
![image](https://github.com/woocommerce/woocommerce/assets/30685349/a476a3db-307f-47ad-b3bb-75caf536fdd0)
![image](https://github.com/woocommerce/woocommerce/assets/30685349/b74d5bc2-ec59-4cce-95d5-72d738baafd5)

4. Now I create a new product and specify this attribute:
![image](https://github.com/woocommerce/woocommerce/assets/30685349/057221a1-a684-4a90-89d9-e9fb217d2105)

5. Now let's dump the `get_attributes()` method for this product:
	```
	function example_test(): void
	{
		$product_atts = wc_get_product(73942)->get_attributes();
		echo '<pre>', var_dump($product_atts), '</pre>';
		exit;
	}
	add_action('template_redirect', 'example_test');  // use this for a simple output dump
	```

6. Output:
	```
	array(1) {
	  ["pa_cars"]=>
	  object(WC_Product_Attribute)#17185 (1) {
		["data":protected]=>
		array(6) {
		  ["id"]=>
		  int(31)
		  ["name"]=>
		  string(7) "pa_cars"
		  ["options"]=>
		  array(3) {
			[0]=>
			int(1338)
			[1]=>
			int(1337)
			[2]=>
			int(1336)
		  }
		  ["position"]=>
		  int(0)
		  ["visible"]=>
		  bool(true)
		  ["variation"]=>
		  bool(true)
		}
	  }
	}
	```

Here, as you can see, is `pa_`. 

---

**Now let's go back to the main issue and try again to remove one attribute value from this new product. Let's try to remove the value `dodge` (id: 1338).**

1. Run my code **with** `pa_` (after using this code, the value of `dodge` is not removed)
	```
	function example_test(): void
	{
		$id_product = 73942;
		$attribute_name = 'pa_cars';
		$id_attribute_value_to_remove = 1338;  // name: dodge

		$product = wc_get_product($id_product);
		$attributes = $product->get_attributes();

		if (isset($attributes[$attribute_name])) {
			$attributes[$attribute_name]['options'] = array_filter(
				$attributes[$attribute_name]['options'],
				function ($value) use ($id_attribute_value_to_remove) {
					return $value !== $id_attribute_value_to_remove;
				}
			);
		}
		$product->set_attributes($attributes);
		$product->save();
	}
	add_action('template_redirect', 'example_test');
	```

2. Run the same code but **without** `pa_` (after using this code, the value of `dodge` is not removed too)
	```
	function example_test(): void
	{
		$id_product = 73942;
		$attribute_name = 'cars';
		$id_attribute_value_to_remove = 1338;  // name: dodge

		$product = wc_get_product($id_product);
		$attributes = $product->get_attributes();

		if (isset($attributes[$attribute_name])) {
			$attributes[$attribute_name]['options'] = array_filter(
				$attributes[$attribute_name]['options'],
				function ($value) use ($id_attribute_value_to_remove) {
					return $value !== $id_attribute_value_to_remove;
				}
			);
		}
		$product->set_attributes($attributes);
		$product->save();
	}
	add_action('template_redirect', 'example_test');
	```

What do you think about it?

**Comment by kanlukasz** [comment]
@rrennick did you test it?

**Comment by rrennick** [comment]
> That's true, but if I dump get_attributes(), I see something different from you.

Right, you are dumping the attribute object on the front end of the site (`view` context). I was outputting the `edit` context. I appreciate that it's confusing. However, your last code snippet should do what you described it doing.

**Comment by kanlukasz** [comment]
> However, your last code snippet should do what you described it doing.

It should, but it doesn't work.
I'll show you step-by-step how to reproduce this bug on a fresh new WP+Woo installation

# Steps to reproduce:

## 1. Install Wordpress:
Note: replace the following sample values such as db, url etc. with your own.
```
wp core download
wp config create --dbname=sandbox_woo --dbuser=sandbox_woo --dbpass='ZZZZZZZZZZ' --dbcharset=utf8mb4 --dbprefix=sandbox_ --dbhost='ZZZZZZZZZZ'
wp config delete WP_CACHE_KEY_SALT
wp config shuffle-salts 
wp config set WP_DEBUG true --raw 
wp config set WP_DEBUG_LOG true --raw
wp config set WP_DEBUG_DISPLAY true --raw
wp core install --url=https://ZZZZZZZZZZ.com --title="Sandbox Test" --admin_user='ZZZZZZZZZZ' --admin_password='ZZZZZZZZZZ' --admin_email=test@test.test --skip-email
```


## 2. Install/Remove/Activate plugins:
```
wp plugin uninstall hello
wp plugin uninstall akismet
wp plugin install woocommerce
wp plugin activate woocommerce
```
So currently the only existing and active plugin is `WooCommerce`

## 3. Add/Remove themes:
```
 wp theme delete --all
```
So currently the only existing and active theme is `Twenty Twenty-Three`

## 4. Prepare WooCoommerce via wp-admin:
- Skip WooCommerce Wizard
- Go to `Products > Start Import`
- Use default import file from `/wp-content/plugins/woocommerce/sample-data/sample_products.csv`
- Next go to `Attributes` and add new one `Car`
- Then go to `Configure terms` and add new terms `Honda, Ford, Dodge`
- Now it looks like this:
    ![image](https://github.com/woocommerce/woocommerce/assets/30685349/362597a3-57f0-4bac-9a34-6903dc7dfac1)
    ![image](https://github.com/woocommerce/woocommerce/assets/30685349/15c8a417-92a4-43cc-a6c2-6aefa0463417)

## 5. Create a new product and specify this attribute:
- ![image](https://github.com/woocommerce/woocommerce/assets/30685349/08529c0e-4e06-49b4-a6f0-8d614437db33)
- ![image](https://github.com/woocommerce/woocommerce/assets/30685349/712702db-85de-4999-a85d-0a2cd7187934)
- ![image](https://github.com/woocommerce/woocommerce/assets/30685349/07082ea3-2c9c-46b9-b881-93b61d95cbcc)

## 6. Create and active a simple plugin in which we try to use CRUD operations:
```
wp scaffold plugin wpcli-demo-plugin --plugin_name="WP-CLI Demo Plugin" --plugin_description="This is a wp-cli demo plugin" --plugin_author=wp-cli --plugin_author_uri="https://wp-cli.org" --plugin_uri="https://plugins.wp-cli.org/demo-plugin"
wp plugin activate wpcli-demo-plugin
```

## 7. Add our CRUD snippet to the plugin
- File: `wp-content/plugins/wpcli-demo-plugin/wpcli-demo-plugin.php`
- So now code looks like this:
```PHP
<?php
/**
 * Plugin Name:     WP-CLI Demo Plugin
 * Plugin URI:      https://plugins.wp-cli.org/demo-plugin
 * Description:     This is a wp-cli demo plugin
 * Author:          wp-cli
 * Author URI:      https://wp-cli.org
 * Text Domain:     wpcli-demo-plugin
 * Domain Path:     /languages
 * Version:         0.1.0
 *
 * @package         Wpcli_Demo_Plugin
 */

// Your code starts here.


function example_test(): void
{
    $id_product = 61;   // remember to change ID
    $attribute_name = 'car';      // without `pa_`
    $id_attribute_value_to_remove = 32;       // (name: dodge), remember to change ID

    $product = wc_get_product($id_product);
    $attributes = $product->get_attributes();

    if (isset($attributes[$attribute_name])) {
        $attributes[$attribute_name]['options'] = array_filter(
            $attributes[$attribute_name]['options'],
            function ($value) use ($id_attribute_value_to_remove) {
                return $value !== $id_attribute_value_to_remove;
            }
        );
    }
    $product->set_attributes($attributes);
    $product->save();
}
add_action('template_redirect', 'example_test');
```

## 7. Conclusions after tests:
- After testing, the car attributes are still the same. The name `Dodge` should no longer be associated with this product, but yet it still is.

- If you test with `pa_` the effect is the same.
    By the way, note that without `pa_` it can't work, because `isset($attributes[$attribute_name])` returns false.

- Anyway, I have tested it in several ways and the conclusion is only one - **it does not work**

---

Do you still think I'm wrong?

**Comment by rrennick** [comment]
@kanlukasz The best place to ask for help with custom code is the Community Slack. Your code does not work because `$attributes[$attribute_name]` is an `object` not an `array`. The `WC_Product_Attribute` options property is an array of strings. Your sample code is trying to compare the string `dodge` to the number `32`.
