### ISSUE TITLE
Woocommerce setupwizard not working

### ISSUE THREAD

**Issue by mrjjperry** [woothemes/woocommerce#39546]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I installed the woocommerce plugin. When I try to run the setup wizard, I keep getting a blank page or a long time before the setup page appears.  When the setup screen appears, it doesn't let met continue to the next page when I click the start button.  I also tried to manually set up woocommerce manually through the settings and got an error when I click on the button to install woopayments.

### Expected behavior

I expected the setup wizard to allow me to setup woocommerce payments on my website

### Actual behavior

The setup wizard is not running or allowing to complete woocommerce setup

### Steps to reproduce

![Screenshot 2023-08-02 114852 woocommerce setup wizard](https://github.com/woocommerce/woocommerce/assets/141256290/1ded20fd-4036-4e01-8d32-4eaeb8e93a71)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://clewistonpride.com
Site address (URL): https://clewistonpride.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 20 MB
PHP Time Limit: 60
PHP Max Input Vars: 8000
cURL Version: 7.71.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp2i_
Total Database Size: 2.66MB
Database Data Size: 2.50MB
Database Index Size: 0.16MB
wp2i_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp2i_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_options: Data: 2.44MB + Index: 0.04MB + Engine MyISAM
wp2i_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp2i_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp2i_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp2i_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp2i_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1
elementor_library: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Livemesh Addons for Elementor: by Livemesh – 7.9.1
Elementor: by Elementor.com – 3.15.1
ElementsKit Lite: by Wpmet – 2.9.0
Ocean Extra: by OceanWP – 2.1.8
Ocean Product Sharing: by OceanWP – 2.0.6
Ocean Social Sharing: by OceanWP – 2.0.4
Premium Addons for Elementor: by Leap13 – 4.10.3
Sticky Header OceanWP: by Oren Hahiashvili – 1.0.8
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.24
WooCommerce: by Automattic – 7.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: OceanWP
Version: 3.4.7
Author URL: https://oceanwp.org/about-oceanwp/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-03 15:12:27 -04:00
Options: ✔
Notes: 63
Onboarding: -

### Action Scheduler ###

Complete: 2
Oldest: 2023-08-02 11:12:45 -0400
Newest: 2023-08-02 11:14:13 -0400

Pending: 1
Oldest: 2023-08-03 11:12:45 -0400
Newest: 2023-08-03 11:12:45 -0400

### Status report information ###

Generated at: 2023-08-02 11:52:40 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
Hey, @mrjjperry! Thanks for your report. Unfortunately, I couldn't reproduce your issue in a fresh WooCommerce site.

You mentioned you saw an error, could you paste your error here please? Also, don't forget to redact any sensitive information if any.

Another way to debug this is to do a conflict test. Here's how:
<ul>
<li>Temporarily switch your theme to <a href="https://www.woocommerce.com/storefront/" target="_blank">Storefront</a></li>
<li>Disable all plugins except for WooCommerce</li>
<li>Repeat the action that is causing the problem</li>
</ul>

If you’re not seeing the same problem after completing the conflict test, then you know the problem was with the plugins and/or theme you deactivated. To figure out which plugin is causing the problem, reactivate your other plugins one by one, testing after each, until you find the one causing conflict. <a href="https://docs.woocommerce.com/document/how-to-test-for-conflicts/">You can find a more detailed explanation on how to do a conflict test here.</a>

**Comment by rrennick** [comment]
Closing for lack of feedback.

**Comment by HoussamADIB** [comment]
I have the same issue, the solution suggested above does not work

**Comment by JeremLeOuf** [comment]
I also get stuck on the 'Woo! Let's get your features ready' screen, which makes my website inaccessible totally. I have to reboot my EC2 instance and can't even access it via SSH!

**Comment by Austin-Olacsi** [comment]
I was actually stuck forever at the loading screen, unable to use the setup wizard, and this is what fixed it for me (on nginx):
https://stackoverflow.com/a/61837294

**Comment by toomanyairmiles** [comment]
Googling WooCommerce setup wizard blank page leads to hundreds of wordpress.org posts describing this issue along with a panoply of YouTube videos outlining proposed workarounds.

It seems to me the problem is Nginx, at least in my case. What I see in console is 

Uncaught (in promise) Object { code: "invalid_json", message: "The response is not a valid JSON response." }

I'm currently running a default theme and no other plugins than WooCommerce. 

What is truly silly is there isn't any way to access settings without this cursed wizard, so maybe do that and go from there, or don't gum up the works with needlessly overcomplicated wizards.
​

**Comment by ohmdrop** [comment]
> Googling WooCommerce setup wizard blank page leads to hundreds of wordpress.org posts describing this issue along with a panoply of YouTube videos outlining proposed workarounds.
> 
> It seems to me the problem is Nginx, at least in my case. What I see in console is
> 
> Uncaught (in promise) Object { code: "invalid_json", message: "The response is not a valid JSON response." }
> 
> I'm currently running a default theme and no other plugins than WooCommerce.
> 
> What is truly silly is there isn't any way to access settings without this cursed wizard, so maybe do that and go from there, or don't gum up the works with needlessly overcomplicated wizards.​

I agree with every point made above. 
I found the same problem while trying to install WooCommerce plugin with Apache and Avada theme - not impressed.
