### ISSUE TITLE
Missing `priority` column in Action Scheduler Actions table causes fatal error

### ISSUE THREAD

**Issue by nicdwilson** [woothemes/woocommerce#39552]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the `priority` column is missing from `wp_actionscheduler_actions` a fatal error occurs when adding an action.

```
2023-07-24T00:26:27+00:00 CRITICAL Uncaught RuntimeException: Error saving action: Unknown column 'priority' in 'field list' in /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:126
Stack trace:
[#0](0-zd-woothemes) /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(69): ActionScheduler_DBStore->save_action_to_db()
[#1](1-zd-woothemes) /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(327): ActionScheduler_DBStore->save_action()
[#2](2-zd-woothemes) /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(315): ActionScheduler_ActionFactory->store()
[#3](3-zd-woothemes) /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(175): ActionScheduler_ActionFactory->create()
[#4](4-zd-woothemes) /home/uid/public_html/wp-content/plugins/pinterest-for-woocommerce/src/FeedRegistration.php(63): as_ in /home/uid/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 126
```

This is an extension of [34497 here](https://github.com/woocommerce/woocommerce/issues/34497), where missing action scheduler tables cause fatal errors.

Here, a missing `priority` column, can cause a fatal error. Since the `priority` column is newly added, it was decided to add this report separately.

### Expected behavior

It's not entirely clear to me if
a - WooCommerce needs to better handle this error
or
b - Action Scheduler needs to better handle database updates and repairs.
Possibly both?

RankMath, for example, has built in an Action Scheduler database repair class, something like this could be triggered by the exception in `ActionScheduler_DBStore`

### Actual behavior

A missing column causes a fatal error in WooCommerce

### Steps to reproduce

1. Remove the `priority` column from `wp_actionscheduler_actions`

### WordPress Environment

Reported [in the forums here](https://wordpress.org/support/topic/woocommerce-error-when-pintrest-for-woocomemrce-enabled/#post-16940416), replicated on a local install.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@nicdwilson Thanks for creating the issue. It was also reported in https://github.com/woocommerce/action-scheduler/issues/973. I'll close this as a duplicate.
