### ISSUE TITLE
A fatal error was received with varible product.

### ISSUE THREAD

**Issue by apeksha10** [woothemes/woocommerce#39579]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A Fatal error was received when I try to place an order with WP 6.3 RC-3

### Expected behavior

No error must be from WC. 

### Actual behavior

The WC throws a fatal error on the Order Received page. 

### Steps to reproduce

Steps for reproducing the above issue 
1. Variable product 
2. WP 6.3 RC-3 activate 
3. WC -7.9.0
4. Add the product 
5. Try to place an order 
6. On the order received page got the below error. 

2023-08-04T11:21:12+00:00 CRITICAL Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\class-wc-product-variation.php:174
Stack trace:
#0 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\class-wc-product-variation.php(174): array_filter('medium', 'wc_array_filter...')
#1 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\templates\order\order-details-item.php(31): WC_Product_Variation->get_permalink(Object(WC_Order_Item_Product))
#2 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\wc-core-functions.php(345): include('C:\\Users\\User\\L...')
#3 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\templates\order\order-details.php(71): wc_get_template('order/order-det...', Array)
#4 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\wc-core-functions.php(345): include('C:\\Users\\User\\L...')
#5 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\wc-template-functions.php(2724): wc_get_template('order/order-det...', Array)
#6 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\class-wp-hook.php(310): woocommerce_order_details_table(316)
#7 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#8 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#9 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\templates\checkout\thankyou.php(80): do_action('woocommerce_tha...', 316)
#10 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\wc-core-functions.php(345): include('C:\\Users\\User\\L...')
#11 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\shortcodes\class-wc-shortcode-checkout.php(322): wc_get_template('checkout/thanky...', Array)
#12 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\shortcodes\class-wc-shortcode-checkout.php(63): WC_Shortcode_Checkout::order_received(316)
#13 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output('')
#14 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, '')
#15 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\shortcodes.php(395): WC_Shortcodes::checkout('', '', 'woocommerce_che...')
#16 [internal function]: do_shortcode_tag(Array)
#17 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\shortcodes.php(235): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')
#18 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\class-wp-hook.php(310): do_shortcode('[woocommerce_ch...')
#19 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\plugin.php(205): WP_Hook->apply_filters('[woocommerce_ch...', Array)
#20 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\post-template.php(256): apply_filters('the_content', '<!-- wp:shortco...')
#21 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\themes\storefront\inc\storefront-template-functions.php(352): the_content()
#22 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\class-wp-hook.php(310): storefront_page_content('')
#23 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#24 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#25 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\themes\storefront\content-page.php(18): do_action('storefront_page')
#26 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\template.php(787): require('C:\\Users\\User\\L...')
#27 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\template.php(720): load_template('C:\\Users\\User\\L...', false, Array)
#28 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\general-template.php(206): locate_template(Array, true, false, Array)
#29 C:\Users\User\Local Sites\beta-tester\app\public\wp-content\themes\storefront\page.php(24): get_template_part('content', 'page')
#30 C:\Users\User\Local Sites\beta-tester\app\public\wp-includes\template-loader.php(106): include('C:\\Users\\User\\L...')
#31 C:\Users\User\Local Sites\beta-tester\app\public\wp-blog-header.php(19): require_once('C:\\Users\\User\\L...')
#32 C:\Users\User\Local Sites\beta-tester\app\public\index.php(17): require('C:\\Users\\User\\L...')
#33 {main}
  thrown in C:\Users\User\Local Sites\beta-tester\app\public\wp-content\plugins\woocommerce\includes\class-wc-product-variation.php on line 174

### WordPress Environment

[SystemStatusReport_beta-tester.local_2023-08-04T11-41-32.txt](https://github.com/woocommerce/woocommerce/files/12260287/SystemStatusReport_beta-tester.local_2023-08-04T11-41-32.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@apeksha10 Can you confirm you still see this issue with WP 6.3, the latest version of WooCommerce, and a default theme? If so, could you provide instruction on creating the variable product.

**Comment by apeksha10** [comment]
Hello @rrennick ,
With WP 6.3 and the latest version of WooCommerce the above issue is not replicated. 
Using Storefront theme.

**Comment by rrennick** [comment]
@apeksha10 Thanks for the follow up. I'll close the issue.
