### ISSUE TITLE
Indian stores incorrectly label single-total tax 'VAT' instead of generic 'Tax' or GST

### ISSUE THREAD

**Issue by melek** [woothemes/woocommerce#39595]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the store location is set to India and the 'Display tax total' setting is set to 'As a single total', VAT is displayed instead of GST - but GST replaced VAT in 2017. 

According to [Indian GST Council](https://gstcouncil.gov.in/about-us): 
> [In 2017] GST replaced multiple indirect taxes levied by the Central and State Governments, such as excise duty, service tax, value-added tax (VAT), and others. It brought uniformity in the tax structure across India, eliminating the cascading effect of taxes.

### Expected behavior

When 'Display tax total' setting is set to 'As a single total', Indian stores should display GST instead of VAT.

Alternatively, it should use the generic 'Tax' label, as this would be fast to implement (removing "IN" from `get_vat_countries()`).

### Actual behavior

VAT is shown as the label for the single tax total.

### Steps to reproduce

1. Set store location to any Indian state. 
2. Enable taxes and add a tax rate.
3. Set 'Display tax total' setting is set to 'As a single total'.
4. Add an item to the cart - observe "VAT" as the tax row label in cart and checkout.

The logic which includes India (IN) is in the `get_vat_countries()` method:
https://github.com/woocommerce/woocommerce/blob/bf174f314e7f312c2986febaddfc9afe69e92101/plugins/woocommerce/includes/class-wc-countries.php

### WordPress Environment

WooCommerce 7.9.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
@melek thank you for reaching out.

A tax label can be defined when declaring the Tax Rates, you can see the Tax Label column.


<img width="1024" alt="Screenshot 2023-09-06 at 18 35 11" src="https://github.com/woocommerce/woocommerce/assets/1628454/4f3e03b0-90af-48fc-a426-a1c72d4bac01">

**Comment by rrennick** [comment]
@ralucaStan Thanks. I'll close this as a support question.

**Comment by melek** [comment]
> @melek thank you for reaching out.
> 
> A tax label can be defined when declaring the Tax Rates, you can see the Tax Label column.
> 
> 
> <img width="1024" alt="Screenshot 2023-09-06 at 18 35 11" src="https://github.com/woocommerce/woocommerce/assets/1628454/4f3e03b0-90af-48fc-a426-a1c72d4bac01">
> 

This report is addressing incorrect behavior, I don't think it should be closed unless I'm wrong about India's tax type.

India is included in a list of countries which have the VAT label applied when selected as a store country, but India does not use VAT, causing friction for configurations which combine tax into a single total.

Setting a specific label on the tax doesn't change the incorrect behavior when one sets 'Display tax total' to 'As a single total' like in the reproduction instructions.

The bug is the continued inclusion of India in [this array](https://github.com/woocommerce/woocommerce/blob/bf174f314e7f312c2986febaddfc9afe69e92101/plugins/woocommerce/includes/class-wc-countries.php#L438):

```
        public function countries_using_vat() { 
                 wc_deprecated_function( 'countries_using_vat', '4.0', 'WC_Countries::get_vat_countries' ); 
                 $countries = array( 'AE', 'AL', 'AR', 'AZ', 'BB', 'BH', 'BO', 'BS', 'BY', 'CL', 'CO', 'EC', 'EG', 'ET', 'FJ', 'GH', 'GM', 'GT', 'IL', 'IN', 'IR', 'KN', 'KR', 'KZ', 'LK', 'MD', 'ME', 'MK', 'MN', 'MU', 'MX', 'NA', 'NG', 'NP', 'PS', 'PY', 'RS', 'RU', 'RW', 'SA', 'SV', 'TH', 'TR', 'UA', 'UY', 'UZ', 'VE', 'VN', 'ZA' ); 
  
                 return apply_filters( 'woocommerce_countries_using_vat', $countries );
```

If I've made a mistake about India's use of VAT  or there is another reason not to fix this I understand, but the goal of the issue is to address incorrect code in the plugin, not receive support (I provided the workaround you all suggested to the customer before I ever filed this report when I found other customers had experienced this issue in the past).
