### ISSUE TITLE
[Enhancement]: On state change we cant get old status and if the request was manual or automated data

### ISSUE THREAD

**Issue by rajeshsingh520** [woothemes/woocommerce#39602]
### Describe the solution you'd like

Hi,

We want to perform some action based on old order status and new order status 

and we want to add this processed data in the outgoing status notification email as well 

but we cant use the hook 'woocommerce_order_status_changed'  as this hook is fired after the email are send 

so we used the hook 'woocommerce_order_status_'.$status_transition['to']
woocommerce\includes\class-wc-order.php line : 395

but this hook do not provide us with previous order status (which we managed to solve with some custom code)

but still we can't know if the request is auto request or manual request 

if you modify this hook to be like this then it will solve the issue 

do_action( 'woocommerce_order_status_' . $status_transition['to'], $this->get_id(), $this, $status_transition );

as the status transition will be having all the data that we need like old status and request is manual or automated

**Comment by barryhughes** [comment]
Thanks! This seems like a reasonable idea, and should not pose any backwards-compatibility issues. From our perspective it is a low priority, but we'd be amenable to reviewing a PR if you wish to submit one (it looks like perhaps you already tried, but something went wrong?).
