### ISSUE TITLE
Documentation for WC Order Query out of date

### ISSUE THREAD

**Issue by EdithAllison** [woothemes/woocommerce#39617]
https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#customer

The query args "customer" accepts an array of user IDs. This is a common use case but not documented.

the old cpt way of doing things:

```
$query->set( 'meta_query', array(
		array(
			'key'     => '_customer_user',
			'compare' => 'IN',
			'value'   => array(1,2,3),
		)
	) );
```

new HPOS way:

```
$args['customer'] = array(1,2,3);
```

It would also be helpful to document that the customer_id field in the new wc_orders table is NOT the woo customer_id from the wc_customer_lookup table but the WP user_id. The naming convention makes this confusing, 

Please update the documentation to include array of user_id as valid input

**Comment by jorgeatorres** [comment]
Hi @EdithAllison!

Thanks for reaching out. It is true that in HPOS you can use `customer` (which accepts both user IDs and e-mail addresses) and `customer_id` but this is also true for the posts datastore. In fact, the documentation you've linked above seems correct to me.

Could you please clarify what needs to be updated? Are you just referring to the fact that you can use an array of IDs?
