### ISSUE TITLE
HPOS data sync is not re-triggered if orders are manually deleted from destination table

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#39626]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If sync is enabled and posts is authoritative, manually deleting orders from the destination table (i.e. the `wc_orders` table) doesn't trigger the sync again for those orders.

While this is a bit of an edge case, it wouldn't hurt to either periodically check if sync needs to be triggered or maybe trigger it automatically on the WC > Settings > Advanced > Features screen, particularly since the pending sync count is displayed but there's no way to do anything about it (other than disabling & re-enabling sync).

### Expected behavior

If sync is enabled, it'd get triggered appropriately without user intervention.

### Actual behavior

Sync doesn't get triggered again until after it is turned on and off from the WC > Settings screen.

### Steps to reproduce

1. Enable HPOS and set posts as authoritative.
2. Make sure data sync is enabled and wait until things have synced up if necessary.
3. If you don't have any orders, create a few and take note of the ID of one of those.
4. Enable data sync in WC > Settings > Advanced > Features.
5. Run the following SQL queries on your site (adjust table names for WP prefix):
   ```sql
   DELETE FROM wc_orders WHERE id = XXX;
   ```
   Replace `XXX` with the ID from step 3.
6. Go to WC > Settings > Advanced > Features. Confirm that the screen indicates that some orders need to be synced, yet no sync is happening.
7. Double check in Tools > Scheduled Actions > Pending that there's no action related to sync waiting to be executed.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
> Run the following SQL queries on your site:

@jorgeatorres it looks like part of the testing instructions are missing here...

**Comment by jorgeatorres** [comment]
@coreymckrill: 🤦‍♂️ I've updated the instructions. Thanks for the nudge.

**Comment by coreymckrill** [comment]
I changed step 4 of the instructions to read "**Enable** data sync in WC > Settings > Advanced > Features" because I think it would be expected for the data to not sync when it's disabled. With data sync enabled, I can confirm that it works as described, and syncing does not initiate automatically.

**Comment by coreymckrill** [comment]
> it wouldn't hurt to either periodically check if sync needs to be triggered or maybe trigger it automatically on the WC > Settings > Advanced > Features screen

I think the former is the better solution. Most site owners probably aren't going to go to the Settings > Features screen very often, so it lots of changes are piling up somehow and not getting synced until that screen is loaded, that could be problematic for data integrity.

So the way to do this is probably:
* Add an Action Scheduler event to check the data synchronizer for the state where there are pending orders and no current sync process happening. Daily? Or maybe hourly?
* When that state is detected, spawn another event to run the sync process

We could still run into the situation where we load the Features screen and there are pending orders, and the only way to trigger the sync right away would be to disable the sync option and then re-enabled it. So perhaps we should also add a button there to manually trigger a sync when there are pending orders?
