### ISSUE TITLE
Simplify the description editing UX

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39622]
User research and data suggest that people struggle with the current description editing in the new experience. We've heard from people who would prefer a standard text input field to a fully-featured visual editor.

**Designs:**
AkVNGImLgSqCObTQ3idVn7-fi-3301_354605

**Acceptance criteria:**

- [x] Description is no longer a separate section. It's now displayed in the `Product details` section below the Summary field.
- [x] Description field uses the same component as the summary.
- [x] The toolbar contains basic text formatting options, such as alignment, bold, italic, link, highlight, code, etc.
- [x] We add a new button: 'Full editor' that's always displayed no matter what block is selected.
- [ ] Clicking ‘Full editor’ opens the existing description editing modal.
- [ ] When the description is added using the full editor, it changes height from 240 to 320 px to make room for the more complex blocks.
- [ ] When the description is added using the full editor, the field’s contents are no longer selectable in the form.
- [ ] When the user clicks anywhere inside the field, we show the toolbar with a link to the full editor. AkVNGImLgSqCObTQ3idVn7-fi-4791_518117
- [ ] Users can use a handle in the bottom right corner to resize the input field.

**Additional context:**

p1690968071488439-slack-C01CMSA1VHS

**Comment by mdperez86** [comment]
> How much time would it take to build a mini version of the visual editor we currently use in the Add description modal in the product form? (take into account showing paragraph block controls by default, supporting all possible blocks, limiting the toolbar options for certain blocks, making the transition between the field and the modal smooth, etc).

If we are going to use the contextual toolbar, the default one used in the modal (NOT the fixed one that shares functionality across blocks) then I think it could take one or two weeks without any distraction or blocker.

Dealing with the toolbar is a long term implementation if we are going to use it in a different way it was created for. The blocks toolbar is a totally different thing in comparison with the RichText Toolbar. The blocks one changes depending on the block the user selects, so it's contextual. But in the case of the RichText Toolbar it does not change at all and it's global for all the content within the RichText editor. So if we want to apply the same or similar behavior to the blocks Toolbar, that means we are going to need to rewrite a lot the logic made for the blocks toolbar on our own, especially because most of the feature already implemented for the toolbar, like formatters, shortcuts, ally, are not being exported out from the core for us to reuse. 

> How much time would it take to reuse the Summary editor for Description without any changes?

In this case, it could be only one issue.

**Comment by jarekmorawski** [comment]
> So if we want to apply the same or similar behavior to the blocks Toolbar, that means we are going to need to rewrite a lot the logic made for the blocks toolbar on our own, especially because most of the feature already implemented for the toolbar, like formatters, shortcuts, ally, are not being exported out from the core for us to reuse.

Gotcha. An MVP of this effort could be to default to the RichText Toolbar no matter what block is selected and let users access the full editing experience in a modal.

**Designs:**
AkVNGImLgSqCObTQ3idVn7-fi-3301_354605

**Acceptance criteria:**

- [ ] Description modal uses the same component as the summary.
- [ ] The toolbar contains basic text formatting options, such as alignment, bold, italic, link, highlight, code, etc.
- [ ] We add a new button: 'Full editor' that's always displayed no matter what block is selected.
- [ ] Clicking ‘Full editor’ opens the existing description editing modal.
- [ ] When the description is added using the full editor, it changes height from 240 to 320 px to make room for the more complex blocks.
- [ ] When the description is added using the full editor, the field’s contents are no longer selectable in the form.
- [ ] When the user clicks anywhere inside the field, we show the toolbar with a link to the full editor. AkVNGImLgSqCObTQ3idVn7-fi-4791_518117
- [ ] Users can use a handle in the bottom right corner to resize the input field.

UPDATED THE ORIGINAL ISSUE

**Comment by retrofox** [comment]
## Development process

_(I'll edit this comment as long as we develop the implementation)_

### Description modal uses the same component as the summary.

Two simple comments. First, we discuss the `description` field. `summary` is another field. Also, we should refer to it like a `block`. Please take this as a side note. Nothing very relevant

### The toolbar contains basic text formatting options, such as alignment, bold, italic, link, highlight, code, etc.

For this, we need to restructure the current template lock system.

### We add a new button: 'Full editor' that's always displayed no matter what block is selected.

It will be doable by extending the toolbar button of the `Section` block

### Clicking ‘Full editor’ opens the existing description editing modal.

### When the description is added using the full editor, it changes height from 240 to 320 px to make room for the more complex blocks.

This is something that may not make sense. Let's see how the app behaves after these changes.

###  When the description is added using the full editor, the field’s contents are no longer selectable in the form.

It will probably require creating a new Preview block or something like that.

### When the user clicks anywhere inside the field, we show the toolbar with a link to the full editor. [AkVNGImLgSqCObTQ3idVn7-fi-4791_518117](https://href.li/?https://www.figma.com/file/AkVNGImLgSqCObTQ3idVn7/?node-id=4791-518117)

Related to the previous point

### Users can use a handle in the bottom right corner to resize the input field.

😬

**Comment by jarekmorawski** [comment]
> Two simple comments. First, we discuss the description field. summary is another field. Also, we should refer to it like a block. Please take this as a side note. Nothing very relevant

Sorry for the confusion, I meant the _description field_. I updated the ACs.

> For this, we need to restructure the current template lock system.

Why is that? We already have the Summary field. Can we use it for the Description field?

> 😬

What do you mean by this?

**Comment by retrofox** [comment]
> > For this, we need to restructure the current template lock system.

> Why is that? We already have the Summary field. Can we use it for the Description field?

Yes, we could. But also  I would like to propose a different approach that allows users to utilize additional blocks for editing the `description`. However, for this to work effectively, we might need to make some adjustments to the locking system of the templates. 

> What do you mean by this?

I'm sorry I'm going to edit this comment once we have a PR to test the implementation. My bad.

Anyway and in short, currently, the Description block will have to switch its representation/behavior once its content is edited by using the modal editor. Under the hood, it issues a Preview component and I'm not sure how it will behave when resizing.
Maybe it isn't a big deal :-)

**Comment by retrofox** [comment]
> > For this, we need to restructure the current template lock system.
> 
> Why is that? We already have the Summary field. Can we use it for the Description field?
> 

Let me add a few comments here. While reusing the `Summary` block for the `Description` field might seem straightforward, it presents several challenges.

<img width="694" alt="image" src="https://github.com/woocommerce/woocommerce/assets/77539/43ab67d4-8e04-4a87-822c-9426d1a841e8">

Here, we have three distinct block types:
1. **Name** (`woocommerce/product-name-field`)
2. **Summary** (`woocommerce/product-summary-field`)
3. **Description** (`woocommerce/product-description-field`).

The `Description` block, which we focus on, has unique behavioral requirements in specific scenarios. For example, when content is added through the full editor, it can no longer be selected in the form. This specificity makes reusing the `Summary` block in the `Description` field less feasible than it appears.

Moreover, it's crucial to understand that blocks function differently than components. They have distinct usage and implementation methods. Hence, applying the `Summary` block's functionality to the `Description` field is challenging and could lead to complications, possibly becoming an anti-pattern in our development process.
