### ISSUE TITLE
[8.0.0] The "Payments" menu is inaccessible in some instances

### ISSUE THREAD

**Issue by csmcneill** [woothemes/woocommerce#39633]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When Woo 8.0.0 is in use, the `Payments` menu item is inaccessible, including all of the sub menu items (e.g., Deposits, Transactions, Settings). This happens no matter what state WooPayments is in (installed, not installed but with the incentive active, deactivated,  activated, not onboarded, connected via Jetpack, not connected via Jetpack, onboarded, etc.).

This is related to some console errors:

```
index.js?ver=8.0.0:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getSetting')
    at index.js?ver=8.0.0:1:4434
    at index.js?ver=8.0.0:1:4643
(anonymous) @ index.js?ver=8.0.0:1
(anonymous) @ index.js?ver=8.0.0:1
index.js?ver=8.0.0:2 Uncaught TypeError: Cannot read properties of undefined (reading 'CurrencyFactory')
    at index.js?ver=8.0.0:2:638484
    at index.js?ver=8.0.0:2:767026
    at index.js?ver=8.0.0:2:767069
(anonymous) @ index.js?ver=8.0.0:2
(anonymous) @ index.js?ver=8.0.0:2
(anonymous) @ index.js?ver=8.0.0:2
index.js?ver=8.0.0:2 Uncaught TypeError: Cannot read properties of undefined (reading 'getSetting')
    at 73463 (index.js?ver=8.0.0:2:364293)
    at i (index.js?ver=8.0.0:2:472913)
    at index.js?ver=8.0.0:2:477755
    at index.js?ver=8.0.0:2:583071
    at index.js?ver=8.0.0:2:583107
```

Reverting to 7.9.0 resolves the issue. Reinstalling Woo and/or WooPayments did not resolve the issue.

### Expected behavior

The `Payments` menu should be accessible in 8.0.0. This will highly impact a number of merchants.

### Actual behavior

WooPayments is inaccessible and cannot be managed while Woo 8.0.0 is active in some cases.

### Steps to reproduce

1. Create a new site.
2. Install WooPayments 8.0.0 and the latest stable version of WooPayments.
4. Navigate to the `Payments` menu.
5. The page will be blank or mostly blank.
6. Check the console for errors.
7. Revert to 7.9.0.
8. Repeat step 3.
9. The `Payments` menu and the sub menu items are accessible.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://satisfactory-killer.jurassic.ninja
Site address (URL): https://satisfactory-killer.jurassic.ninja
WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 6.27MB
Database Data Size: 4.57MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 6.2.2
WooCommerce: by Automattic – 8.0.0

### Inactive Plugins (4) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.4
WooCommerce Payments Dev Tools: by Automattic –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/users/userf1aeb2bd/apps/userf1aeb2bd/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/users/userf1aeb2bd/apps/userf1aeb2bd/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/users/userf1aeb2bd/apps/userf1aeb2bd/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-09 20:55:35 +00:00
Options: ✔
Notes: 70
Onboarding: -

### WooCommerce Payments ###

Version: 6.2.2
Connected to WPCOM: Yes
Blog ID: 222165404
Account ID: acct_1NcxGOFjrlDWae2l

### Action Scheduler ###

Complete: 6
Oldest: 2023-08-08 20:56:29 +0000
Newest: 2023-08-08 21:37:33 +0000

Failed: 1
Oldest: 2023-08-08 20:58:47 +0000
Newest: 2023-08-08 20:58:47 +0000

Pending: 2
Oldest: 2023-08-08 21:38:33 +0000
Newest: 2023-08-09 20:56:29 +0000

### Status report information ###

Generated at: 2023-08-08 21:38:09 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by csmcneill** [comment]
I removed the `priority: critical` label as I'm only able to reproduce this on a fresh JN site. Further testing on an established AT site and an established self-hosted site yield different results.

**Comment by daquinons** [comment]
I'm putting back the critical label after discovering that this is reproducible in other fresh sites like Woo Express.

Doing rolldowns, we've identified that the breaking changes were introduced in RC2.

**Comment by Jinksi** [comment]
Linking slack discussion: p1691529017734519-slack-CGGCLBN58

**Comment by tammullen** [comment]
> we've identified that the breaking changes were introduced in RC2.

Update: the bug was introduced here https://github.com/woocommerce/woocommerce/pull/39144 available since Beta 1
