### ISSUE TITLE
[Enhancement] Remove 'List price' and 'Sale price' fields from the General tab

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39644]
User research has shown that people find it confusing to see the pricing fields in two places in the form. Let's remove them from the `General` tab, so they're only available in the `Pricing` tab.

**Acceptance criteria**

- [x] List price and sale price fields are no longer visible in the `Basic details` section in the `General` tab.
- [x] Pricing fields should not be visible in `General` tab for all the templates ( Standard, Grouped, Affiliate ).

**Comment by j111q** [comment]
Leaving a comment here to link it to this P2 post (peCask-Ey-p2) -- IMO this is one of the key changes we should prioritise before the Gift Card work. cc @pmcpinto
