### ISSUE TITLE
[Fix] Update the validation message for the name field

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39647]
We currently show a pretty unspecific validation message when the name field is missing and the user attempts to preview or publish a product. Let's update it to something more descriptive.

**Acceptance criteria**

- [ ] The name field's validation message reads: `Product name is required.`

**Comment by pmcpinto** [comment]
@jarekmorawski we display: Name field is required.

Should we close it or do you want to update the copy?

**Comment by jarekmorawski** [comment]
We've certainly made progress, but I'd still update the copy to remove the reference to the "field". The message appears right below the field, so it isn't needed.
