### ISSUE TITLE
[Fix] Update the front-end behavior when the product is password-protected

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39648]
I'm not sure the password protection feature is fully finished yet, but it doesn't seem to work on the front-end. It's different from how this behavior is currently handled in WordPress/Woo core, so we should do our best to align.

**Currently**

<img width="1222" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/e7453d27-3b25-4c91-8e4f-882349638ab5">

**Expected**

<img width="779" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/6c068c9b-e87f-48e2-8b5e-203c0c83d379">

**Acceptance criteria**

- [ ] When a product is protected with a password, the front-end matches what currently exists in WordPress and Woo (i.e. it asks for a password).

**Comment by louwie17** [comment]
This issue appears to be block based theme dependant.
If I enable the store front theme the password protection works fine, but on a block based theme it loads another template that doesn't seem to respect the password protection. Maybe this is WooCommerce Blocks related?

**Comment by louwie17** [comment]
Can we actually move it to WooCommerce Blocks?
It looks like this happens as soon as you convert the classic single product template block to individual blocks.
The whole template should adhere to the password protection.

**Comment by pmcpinto** [comment]
@louwie17 should we close this? It doesn't seem to be related to the new editor work

**Comment by louwie17** [comment]
Yeah this can be closed as this was a theme issue and fixed as part of https://github.com/woocommerce/woocommerce-blocks/issues/10939
