### ISSUE TITLE
Old database records aren't deleted after HPOS migration

### ISSUE THREAD

**Issue by mondalaci** [woothemes/woocommerce#39656]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Duplicate database records, such as the ones in the `wp_postmeta` table, are not removed after HPOS migration.

Removing such redundant records would free up space and make the database more performant.

### Expected behavior

I'd expect WooCommerce to remove the old, duplicate records or provide a way to remove them explicitly.

### Actual behavior

The old, duplicate records are not removed, and I can't see a way of removing them.

### Steps to reproduce

1. Go to WooCommerce -> Advanced -> Features
2. Enable the "Keep the posts and orders tables in sync (compatibility mode)" option.
3. Enable the "High performance order storage (new)" option
4. Disable the "Keep the posts and orders tables in sync (compatibility mode)" option

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost
WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.1.21
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 100000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.33-0ubuntu0.22.04.4
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 535.23MB
Database Data Size: 300.52MB
Database Index Size: 234.71MB
wp_woocommerce_sessions: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 40.58MB + Index: 52.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.42MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aepc_logs: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aryo_activity_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_awb_critical_css: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_comments: Data: 16.55MB + Index: 15.09MB + Engine InnoDB
wp_contact_form_log: Data: 2.01MB + Index: 0.05MB + Engine MyISAM
wp_contact_form_log_orig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dhl_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_eum_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jckpc_inventory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_auto: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_log: Data: 2.52MB + Index: 0.47MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mc4wp_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_moove_activity_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 9.52MB + Index: 0.30MB + Engine InnoDB
wp_oses_attachments: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 10.52MB + Index: 0.11MB + Engine InnoDB
wp_oses_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 94.64MB + Index: 104.34MB + Engine InnoDB
wp_posts: Data: 45.55MB + Index: 7.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_refersion_cart_tracking: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 0.33MB + Index: 0.30MB + Engine InnoDB
wp_shortpixel_queue: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_subscribe_reloaded_subscribers: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.22MB + Index: 0.30MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 35.58MB + Index: 42.16MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_customer_contexts: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_saferpaycw_documents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_ecc: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_schema_version: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_storage: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_transactions: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 2.52MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1225
custom_css: 1
e-landing-page: 1
elementor_library: 5
elementor_snippet: 1
fusion_element: 2
mc4wp-form: 4
nav_menu_item: 7
oembed_cache: 4
page: 237
post: 170
product: 47
product_variation: 9
revision: 4321
shop_coupon: 1277
shop_order: 15932
shop_order_refund: 816
stc: 2
vpc-config: 1
wcct_countdown: 1
wp_global_styles: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (19) ###

Elementor Pro: by Elementor.com – 3.15.0
Elementor: by Elementor.com – 3.15.2
Avada Builder: by ThemeFusion – 3.11.2
Avada Core: by ThemeFusion – 5.11.2
WooCommerce Attribute Swatches by Iconic: by Iconic  – 1.16.3
WooCommerce Product Configurator by Iconic: by Iconic – 1.19.1
Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 2.1.2
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.11.230721
Aelia Currency Switcher for WooCommerce: by Aelia – 5.0.9.230804
WooCommerce EU VAT Number: by WooCommerce – 2.8.6
Sequential Order Numbers for WooCommerce: by SkyVerge – 1.10.0
WooCommerce: by Automattic – 8.0.0
WordSnippets: by László Monda – 1.0.0
WP Fastest Cache Premium: by Emre Vona – 1.6.9
WP Fastest Cache: by Emre Vona – 1.1.8
WP Mail SMTP Pro: by WP Mail SMTP – 3.8.2
UGL DHL Shipping: by UGL – 1.0.0
UGL Knowledgebase: by UGL – 1.0.0
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.8

### Inactive Plugins (5) ###

Aelia Tax Display by Country for WooCommerce: by Aelia – 1.15.10.210406
mame Saferpay for WooCommerce: by mame webdesign hüttig – 1.4.0
Rollbar: by Rollbar – 2.6.3
ShortPixel Image Optimizer: by ShortPixel - Convert WebP/AVIF & Optimize Images – 5.4.0
WooCommerce Nested Category Layout: by SkyVerge – 1.18.1 (update to version 1.19.0 is available)

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #4622 - /shop
Cart: #4623 - /cart
Checkout: #4624 - /checkout
My account: #4625 - /my-account
Terms and conditions: #5610 - /terms-of-service

### Theme ###

Name: Avada-UHK
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.11.2
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
avada-uhk/woocommerce/emails/customer-invoice.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-09 21:32:00 +02:00
Options: ✔
Notes: 112
Onboarding: completed

### Action Scheduler ###

Complete: 990
Oldest: 2023-07-09 16:59:54 +0200
Newest: 2023-08-09 15:35:16 +0200

Failed: 16
Oldest: 2019-05-28 19:17:32 +0200
Newest: 2023-08-09 14:10:55 +0200

Pending: 7
Oldest: 2023-08-09 17:55:35 +0200
Newest: 2023-08-14 05:53:07 +0200

### Status report information ###

Generated at: 2023-08-09 15:56:31 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Merging with #40714.
