### ISSUE TITLE
Over 40 unnecesary "wc-blocks-style-*" loaded in the website in any page

### ISSUE THREAD

**Issue by hogash** [woothemes/woocommerce#39658]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The stylesheets below are loaded in the website:
```
wc-blocks-style-css
wc-blocks-style-active-filters-css
wc-blocks-style-add-to-cart-form-css
wc-blocks-packages-style-css
wc-blocks-style-all-products-css
wc-blocks-style-all-reviews-css
wc-blocks-style-attribute-filter-css
wc-blocks-style-breadcrumbs-css
wc-blocks-style-catalog-sorting-css
wc-blocks-style-customer-account-css
wc-blocks-style-featured-category-css
wc-blocks-style-featured-product-css
wc-blocks-style-mini-cart-css
wc-blocks-style-price-filter-css
wc-blocks-style-product-add-to-cart-css
wc-blocks-style-product-button-css
wc-blocks-style-product-categories-css
wc-blocks-style-product-image-css
wc-blocks-style-product-image-gallery-css
wc-blocks-style-product-query-css
wc-blocks-style-product-results-count-css
wc-blocks-style-product-reviews-css
wc-blocks-style-product-sale-badge-css
wc-blocks-style-product-search-css
wc-blocks-style-product-sku-css
wc-blocks-style-product-stock-indicator-css
wc-blocks-style-product-summary-css
wc-blocks-style-product-title-css
wc-blocks-style-rating-filter-css
wc-blocks-style-reviews-by-category-css
wc-blocks-style-reviews-by-product-css
wc-blocks-style-product-details-css
wc-blocks-style-single-product-css
wc-blocks-style-stock-filter-css
wc-blocks-style-cart-css
wc-blocks-style-checkout-css
wc-blocks-style-mini-cart-contents-css
storefront-gutenberg-blocks-css
```

### Expected behavior

Not to load all these styles.

### Actual behavior

-

### Steps to reproduce

Install Storefront and WooCommerce and check the frontend source page in the <head>

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.4
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.88.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 8.91MB
Database Data Size: 6.84MB
Database Index Size: 2.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 171
custom_css: 1
elementor_library: 1
nav_menu_item: 71
page: 23
post: 10
product: 35
product_variation: 209
revision: 5
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.0.0

### Inactive Plugins (2) ###

Elementor: by Elementor.com – 3.15.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #205 - /my-account-2/
Terms and conditions: #196 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 4.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-10 15:26:18 +00:00
Options: ✔
Notes: 69
Onboarding: -

### Action Scheduler ###

Complete: 21
Oldest: 2023-07-21 10:50:55 +0000
Newest: 2023-08-09 15:40:12 +0000

Pending: 1
Oldest: 2023-08-10 15:28:03 +0000
Newest: 2023-08-10 15:28:03 +0000

### Status report information ###

Generated at: 2023-08-09 15:48:26 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
Thank you for reaching out @hogash 

I tested with some classes with the latest WooCommerce and WooCommerce Blocks and I could not find them in the My account page. I think this might have been fixed in this PR https://github.com/woocommerce/woocommerce-blocks/pull/9831 . @Aljullu maybe you can also confirm this?

**Comment by badfeather** [comment]
I am experiencing the same issue as @hogash .

**Comment by benoitfouc** [comment]
Hello there, i have the same problem on my 7 woocommerce websites since the last 8.x update.
There is some informations about this issue here : https://wordpress.org/support/topic/dequeue-styles-files-not-working/
Google PageSpeed Insights is not happy

**Comment by tjcafferkey** [comment]
I have just tested this with version 8.0.1 of WooCommerce which was released yesterday and I'm only loading specific stylesheets based on what Woo block is being used.

Can you please confirm that you're using the latest version of WooCommerce (8.0.1) @hogash @benoitfouc @badfeather because this comes with WooCommerce Blocks 10.6.5 and [WooCommerce Blocks 10.6.2 included “Only load styles required by the blocks rendered on the page.“](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/pull/10407)

Thank you.

**Comment by benoitfouc** [comment]
Hello there, @tjcafferkey as you can see i'm in WooC 8.0.1
![image](https://github.com/woocommerce/woocommerce/assets/10956350/d1f5e091-3cb5-4e59-b1be-327e17a90900)

i install individualy and manualy the plugins of WC BLocks ( version 10.8.2) and that fix the issue

The "Only load styles required by the blocks rendered on the page" was finaly implemented version 10.7.0 – 2023-07-17
https://fr.wordpress.org/plugins/woo-gutenberg-products-block/#developers

regards

**Comment by tjcafferkey** [comment]
>The "Only load styles required by the blocks rendered on the page" was finaly implemented version 10.7.0 – 2023-07-17

Yep this is correct that it was released in 10.7.0 but it was also included in 10.6.5 so in theory _should_ be in the latest WooCommerce version. You can see the 10.6.5 release notes [here](https://github.com/woocommerce/woocommerce-blocks/pull/10407) which mentions it.

**Comment by PaulSchiretz** [comment]
Just installed 8.0.1 (WooCommerce Blocks-Paket: 10.6.5) and i have the same issue. Any workaround for this?

**Comment by benoitfouc** [comment]
> > The "Only load styles required by the blocks rendered on the page" was finaly implemented version 10.7.0 – 2023-07-17
> 
> Yep this is correct that it was released in 10.7.0 but it was also included in 10.6.5 so in theory _should_ be in the latest WooCommerce version. You can see the 10.6.5 release notes [here](https://github.com/woocommerce/woocommerce-blocks/pull/10407) which mentions it.

I agree this is strange. But i manage 7 woocommerce websites, and after update them to WC 8.0.1 i have the issue on all my 7 websites. Some of them are slow down by these files

**Comment by PaulSchiretz** [comment]
Not the nicest of all solutions but till the woocommerce team comes back to this you can simply add this to your functions.php:

NOTE: this requires at least php 8.0!

```
add_action( 'wp_enqueue_scripts', 'custom_temp_remove_woo_block_styles', 98 );
function custom_temp_remove_woo_block_styles() {
    global $wp_styles;
    if(!is_admin())
    {    
        wp_dequeue_style( 'wc-blocks-style' ); // Remove WooCommerce block CSS
        wp_dequeue_style( 'wc-blocks-vendors-style' ); // Remove WooCommerce block vendors CSS
        wp_dequeue_style( 'wc-blocks-packages-style' ); // Remove WooCommerce block packages CSS

        // Remove WooCommerce block styles after v8.0.1 update
        foreach($wp_styles->registered as $registered) {
           if( str_starts_with($registered->handle, 'wc-blocks-style-') ) {
                   wp_dequeue_style( $registered->handle );
           }
        }
    }
}
```

**Comment by tjcafferkey** [comment]
Hi all,

Just an update on this. We're currently working on a fix and will put out a patch release either for WooCommerce Blocks, or WooCommerce which will resolve this.

Once we have done that, I'll update this issue with some steps forward.

**Comment by tjcafferkey** [comment]
We have just released [WooCommerce Blocks 10.8.3](https://wordpress.org/plugins/woo-gutenberg-products-block/) which includes only a fix specifically for this issue. I'd recommend to [installing or updating the plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) (which has a previous version bundled into WooCommerce core) to fix this issue.

**Comment by namzzz** [comment]
> We have just released [WooCommerce Blocks 10.8.3](https://wordpress.org/plugins/woo-gutenberg-products-block/) which includes only a fix specifically for this issue. I'd recommend to [installing or updating the plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) (which has a previous version bundled into WooCommerce core) to fix this issue.

I don't use any blocks at all at my website.

I suppose there should be a more simple way to fix it without any plugin install. Will you do it?

**Comment by namzzz** [comment]
> Not the nicest of all solutions but till the woocommerce team comes back to this you can simply add this to your functions.php:
> 
> NOTE: this requires at least php 8.0!
> 
> ```
> add_action( 'wp_enqueue_scripts', 'custom_temp_remove_woo_block_styles', 98 );
> function custom_temp_remove_woo_block_styles() {
>     global $wp_styles;
>     if(!is_admin())
>     {    
>         wp_dequeue_style( 'wc-blocks-style' ); // Remove WooCommerce block CSS
>         wp_dequeue_style( 'wc-blocks-vendors-style' ); // Remove WooCommerce block vendors CSS
>         wp_dequeue_style( 'wc-blocks-packages-style' ); // Remove WooCommerce block packages CSS
> 
>         // Remove WooCommerce block styles after v8.0.1 update
>         foreach($wp_styles->registered as $registered) {
>            if( str_starts_with($registered->handle, 'wc-blocks-style-') ) {
>                    wp_dequeue_style( $registered->handle );
>            }
>         }
>     }
> }
> ```

Thank you. I'll use it for the present moment.

**Comment by tjcafferkey** [comment]
@namzzz sorry for not being clear. For the time being the plugin includes the fix but it will only be _required_ until the next WooCommerce update (8.1 I believe) which will also include this fix.

**Comment by namzzz** [comment]
@tjcafferkey, awesome! Thank you.
