### ISSUE TITLE
Add a way to discover the Woo AI Settings section to add branding details.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#39655]
Now that Woo AI has a settings page and now that the product descriptions will be generated using these "branding" settings, we should make the settings page more discoverable.

- [ ] Create a nudge when generating product titles by adding an informational message to the[ list of random messages shown](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woo-ai/src/components/random-loading-message/random-loading-message.tsx#L19) while waiting for a product title to be generated by AI.
- [ ] Add some kind of nudge when generating product descriptions? Since product description output is streamed, there isn't a waiting period to take advantage of.
- [ ] Add some kind of Popover component when hovering over the product description "write with AI" button which has a link to the Woo AI Settings page?

**Comment by nima-karimi** [comment]
More of a design decision but just my two cents:

One thing to consider is whether we want to treat the branding settings as a "set it and forget" option or we want the user to be constantly reminded they can (or should) change that setting to get better results. If we include a nudge on the product edit page and the user sees it every time they create/edit a product, it may be interpreted as a suggestion to change it more frequently (or per product). On the other hand, if we add a note or a notice when the plugin is updated, we can let the user know about the settings page once.

If the settings page only had the store description, it would be a "set it and forget it" type of setting. However, the tone of voice option is also available there and may require more frequent changes depending on the user's preference.

Once we implement the AI modal (https://github.com/woocommerce/woocommerce/issues/38810), the users can set the tone of voice directly on the page, and I think then we won't need to include it in the branding settings.

**Comment by tommyshellberg** [comment]
> we include a nudge on the product edit page and the user sees it every time they create/edit a product, it may be interpreted as a suggestion to change it more frequently (or per product). 

Good point, and I was thinking about this as well. I think we'd only want to show the nudge if the branding settings are empty (they're accessible via the React app so certainly we could check if it exists). So, once someone has branding settings set, we would not show the nudge.

> Once we implement the AI modal (https://github.com/woocommerce/woocommerce/issues/38810), the users can set the tone of voice directly on the page, and I think then we won't need to include it in the branding settings.

I am actually not certain that adding a "tone of voice" setting in a modal is a given. I don't personally see a use case for someone wanting to change the tone often; it seems to me like a site has a given tone of voice, and once it's set, you want all of your content to be consistent with that tone of voice.

But, having a really intuitive and fast feedback loop for testing the tone of voice seems like a useful feature.
Meaning, give the store owner a fast and easy way to generate content with various tones of voice, compare them, and then pick one for the store, removing the tone of voice from the UI from that point on.
Perhaps the Settings page could be improved by showing samples of product descriptions generated with various tones of voice.
The biggest thing I worry about is bloating the UI and making the UX more complex without a real benefit.

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
