### ISSUE TITLE
Fatal Error with PayPal Standard and new PayPal

### ISSUE THREAD

**Issue by joakim-tldr** [woothemes/woocommerce#39669]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've tried Standard PayPal and new PayPal with both sandbox and production. The payment goes through and is processed in WooCommerce orders, i get the confirmation email and can refund. But the thank you page get a fatal error. And this error will be displayed for any other payment gateway while processing.

Fatal error: Uncaught Error: Call to a member function get_payment_method() on string
in /home/jhemsi12/public_html/stage/wp-content/plugins/woocommerce/includes/gateways/paypal/class-wc-gateway-paypal.php on line 509

Call stack:

WC_Gateway_Paypal::order_received_text()
wp-includes/class-wp-hook.php:310
WP_Hook::apply_filters()
wp-includes/plugin.php:205
apply_filters()
wp-content/themes/realm/page.php:31
include()
wp-includes/template-loader.php:106
require_once()
wp-blog-header.php:19
require()
index.php:17

### Expected behavior

display the thank you page with order details

### Actual behavior

Error message, nothing else.

### Steps to reproduce

1. Install Standard PayPal or new PayPal
2. Make a payment with either sandbox or production

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://j4277.hemsida.eu/stage
Site address (URL): https://j4277.hemsida.eu/stage
WC Version: 8.0.1
REST API Version: ✔ 8.0.1
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: sv_SE
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.29
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 15000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.1
WC Database Prefix: wp0h_
Total databasstorlek: 181.04MB
Datastorlek för databas: 105.46MB
Indexstorlek för databas: 75.58MB
wp0h_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp0h_woocommerce_order_items: Data: 1.52MB + Index: 0.33MB + Motor InnoDB
wp0h_woocommerce_order_itemmeta: Data: 8.52MB + Index: 10.03MB + Motor InnoDB
wp0h_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp0h_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_actionscheduler_actions: Data: 1.02MB + Index: 0.11MB + Motor InnoDB
wp0h_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_actionscheduler_logs: Data: 1.36MB + Index: 0.59MB + Motor InnoDB
wp0h_commentmeta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_comments: Data: 5.52MB + Index: 3.70MB + Motor InnoDB
wp0h_links: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_litespeed_img_optm: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Motor InnoDB
wp0h_litespeed_url: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Motor InnoDB
wp0h_mail_catcher_logs: Data: 1.02MB + Index: 0.00MB + Motor InnoDB
wp0h_options: Data: 4.23MB + Index: 1.13MB + Motor InnoDB
wp0h_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxe_posts: Data: 0.09MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_files: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_hash: Data: 0.16MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_history: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_images: Data: 0.11MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_posts: Data: 0.13MB + Index: 0.00MB + Motor InnoDB
wp0h_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_postmeta: Data: 37.56MB + Index: 27.42MB + Motor InnoDB
wp0h_posts: Data: 7.08MB + Index: 2.22MB + Motor InnoDB
wp0h_product_price_history: Data: 2.52MB + Index: 0.00MB + Motor InnoDB
wp0h_realm_follow_up_email_log: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_realm_follow_up_email_schedule: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_rtg_attachments: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_termmeta: Data: 0.52MB + Index: 0.39MB + Motor InnoDB
wp0h_terms: Data: 0.13MB + Index: 0.14MB + Motor InnoDB
wp0h_term_relationships: Data: 0.27MB + Index: 0.19MB + Motor InnoDB
wp0h_term_taxonomy: Data: 0.09MB + Index: 0.14MB + Motor InnoDB
wp0h_usermeta: Data: 22.56MB + Index: 23.09MB + Motor InnoDB
wp0h_users: Data: 2.52MB + Index: 2.55MB + Motor InnoDB
wp0h_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_download_log: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_orders: Data: 0.02MB + Index: 0.11MB + Motor InnoDB
wp0h_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp0h_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp0h_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Motor InnoDB
wp0h_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_wc_product_attributes_lookup: Data: 0.27MB + Index: 0.23MB + Motor InnoDB
wp0h_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_wc_product_meta_lookup: Data: 0.34MB + Index: 0.66MB + Motor InnoDB
wp0h_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wpml_mails: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp0h_yith_ywpar_points_log: Data: 3.52MB + Index: 0.00MB + Motor InnoDB
wp0h_yoast_indexable: Data: 2.47MB + Index: 0.89MB + Motor InnoDB
wp0h_yoast_indexable_hierarchy: Data: 0.30MB + Index: 0.47MB + Motor InnoDB
wp0h_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp0h_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp0h_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Motor InnoDB
wp0h_ywdpd_exclusion_list_table: Data: 0.02MB + Index: 0.03MB + Motor InnoDB

### Post Type Counts ###

acf-field: 123
acf-field-group: 14
attachment: 3165
customize_changeset: 4
mailmunch_page: 1
nav_menu_item: 290
oembed_cache: 18
page: 26
post: 2
postman_sent_mail: 8
product: 305
product_variation: 469
revision: 880
shop_coupon: 20
shop_order: 3100
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
ywdpd_discount: 10
ywpar-redeeming-rule: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Query Monitor: av John Blackbourn – 3.13.1
ACF Content Analysis for Yoast SEO: av Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Advanced Custom Fields PRO: av WP Engine – 6.1.8
Custom Post Type UI: av WebDevStudios – 1.14.0
GTM Kit: av TLA Media – 1.12.1
IT-Stöd WooCommerce: av Robert Siik – 1.0.0
JWT Authentication for WP-API: av Enrique Chavez – 1.3.2
Klarna Checkout for WooCommerce: av Krokedil – 2.11.4
Klarna Shipping Assistant for WooCommerce: av Krokedil – 1.2.0
LiteSpeed Cache: av LiteSpeed Technologies – 5.5.1
Shipmondo för WooCommerce: av Shipmondo – 4.1.1
Payment Plugins for PayPal WooCommerce: av Payment Plugins
support@paymentplugins.com – 1.0.36

Trustpilot-reviews: av Trustpilot – 2.5.925
WebP Express: av Bjørn Rosell – 0.25.6
Premmerce Permalink Manager for WooCommerce: av Premmerce – 2.3.9
Woo Swish e-commerce: av BjornTech – 3.5.9
Store Toolkit for WooCommerce: av Visser Labs – 2.3.9
WooCommerce: av Automattic – 8.0.1
Yoast SEO: av Team Yoast – 20.13
WP All Export Pro: av Soflyy – 1.8.4
WP All Import Pro: av Soflyy – 4.8.1
Mail logging - WP Mail Catcher: av James Ward – 2.1.3
WP Mail SMTP: av WP Mail SMTP – 3.8.2
WP All Export - WooCommerce Export Add-On Pro: av Soflyy – 1.0.7
WP All Import - WooCommerce Import Add-On Pro: av Soflyy – 3.3.7
YITH WooCommerce Bulk Product Editing Premium: av YITH – 2.6.0

### Dropin Plugins (2) ###

db.php: Query Monitor Database Class (Drop-in)
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Butikbas: ❌ Sida har inte valts
Varukorg: #15 - /varukorg/
Kassan: #16 - /kassan/
Mitt konto: #17 - /mitt-konto/
Villkor: #105 - /allmanna-villkor/

### Theme ###

Name: Realm
Version: 11.0.0
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: realm/woocommerce/archive-product.php
realm/woocommerce/auth/footer.php
realm/woocommerce/auth/form-grant-access.php
realm/woocommerce/auth/form-login.php
realm/woocommerce/auth/header.php
realm/woocommerce/cart/cart-empty.php
realm/woocommerce/cart/cart-item-data.php
realm/woocommerce/cart/cart-shipping.php
realm/woocommerce/cart/cart-totals.php
realm/woocommerce/cart/cart.php
realm/woocommerce/cart/cross-sells.php
realm/woocommerce/cart/mini-cart.php
realm/woocommerce/cart/proceed-to-checkout-button.php
realm/woocommerce/cart/shipping-calculator.php
realm/woocommerce/checkout/cart-errors.php
realm/woocommerce/checkout/form-billing.php
realm/woocommerce/checkout/form-checkout.php
realm/woocommerce/checkout/form-coupon.php
realm/woocommerce/checkout/form-login.php
realm/woocommerce/checkout/form-pay.php
realm/woocommerce/checkout/form-shipping.php
realm/woocommerce/checkout/order-receipt.php
realm/woocommerce/checkout/payment-method.php
realm/woocommerce/checkout/payment.php
realm/woocommerce/checkout/review-order.php
realm/woocommerce/checkout/terms.php
realm/woocommerce/checkout/thankyou.php
realm/woocommerce/content-product-cat.php
realm/woocommerce/content-product.php
realm/woocommerce/content-single-product.php
realm/woocommerce/content-widget-price-filter.php
realm/woocommerce/content-widget-product.php
realm/woocommerce/content-widget-reviews.php
realm/woocommerce/emails/admin-cancelled-order.php
realm/woocommerce/emails/admin-failed-order.php
realm/woocommerce/emails/admin-new-order.php
realm/woocommerce/emails/customer-completed-order.php
realm/woocommerce/emails/customer-invoice.php
realm/woocommerce/emails/customer-new-account.php
realm/woocommerce/emails/customer-note.php
realm/woocommerce/emails/customer-on-hold-order.php
realm/woocommerce/emails/customer-processing-order.php
realm/woocommerce/emails/customer-refunded-order.php
realm/woocommerce/emails/customer-reset-password.php
realm/woocommerce/emails/email-addresses.php
realm/woocommerce/emails/email-customer-details.php
realm/woocommerce/emails/email-downloads.php
realm/woocommerce/emails/email-footer.php
realm/woocommerce/emails/email-header.php
realm/woocommerce/emails/email-mobile-messaging.php
realm/woocommerce/emails/email-order-details.php
realm/woocommerce/emails/email-order-items.php
realm/woocommerce/emails/email-styles.php
realm/woocommerce/emails/plain/admin-cancelled-order.php
realm/woocommerce/emails/plain/admin-failed-order.php
realm/woocommerce/emails/plain/admin-new-order.php
realm/woocommerce/emails/plain/customer-completed-order.php
realm/woocommerce/emails/plain/customer-invoice.php
realm/woocommerce/emails/plain/customer-new-account.php
realm/woocommerce/emails/plain/customer-note.php
realm/woocommerce/emails/plain/customer-on-hold-order.php
realm/woocommerce/emails/plain/customer-processing-order.php
realm/woocommerce/emails/plain/customer-refunded-order.php
realm/woocommerce/emails/plain/customer-reset-password.php
realm/woocommerce/emails/plain/email-addresses.php
realm/woocommerce/emails/plain/email-customer-details.php
realm/woocommerce/emails/plain/email-downloads.php
realm/woocommerce/emails/plain/email-order-details.php
realm/woocommerce/emails/plain/email-order-items.php
realm/woocommerce/global/breadcrumb.php
realm/woocommerce/global/form-login.php
realm/woocommerce/global/quantity-input.php
realm/woocommerce/global/sidebar.php
realm/woocommerce/global/wrapper-end.php
realm/woocommerce/global/wrapper-start.php
realm/woocommerce/loop/add-to-cart.php
realm/woocommerce/loop/loop-end.php
realm/woocommerce/loop/loop-start.php
realm/woocommerce/loop/no-products-found.php
realm/woocommerce/loop/orderby.php
realm/woocommerce/loop/pagination.php
realm/woocommerce/loop/price.php
realm/woocommerce/loop/rating.php
realm/woocommerce/loop/result-count.php
realm/woocommerce/loop/sale-flash.php
realm/woocommerce/myaccount/dashboard.php
realm/woocommerce/myaccount/downloads.php
realm/woocommerce/myaccount/form-add-payment-method.php
realm/woocommerce/myaccount/form-edit-account.php
realm/woocommerce/myaccount/form-edit-address.php
realm/woocommerce/myaccount/form-login.php
realm/woocommerce/myaccount/form-lost-password.php
realm/woocommerce/myaccount/form-reset-password.php
realm/woocommerce/myaccount/lost-password-confirmation.php
realm/woocommerce/myaccount/my-account.php
realm/woocommerce/myaccount/my-address.php
realm/woocommerce/myaccount/my-downloads.php
realm/woocommerce/myaccount/my-orders.php
realm/woocommerce/myaccount/navigation.php
realm/woocommerce/myaccount/orders.php
realm/woocommerce/myaccount/payment-methods.php
realm/woocommerce/myaccount/view-order.php
realm/woocommerce/notices/error.php
realm/woocommerce/notices/notice.php
realm/woocommerce/notices/success.php
realm/woocommerce/order/form-tracking.php
realm/woocommerce/order/order-again.php
realm/woocommerce/order/order-details-customer.php
realm/woocommerce/order/order-details-item.php
realm/woocommerce/order/order-details.php
realm/woocommerce/order/order-downloads.php
realm/woocommerce/order/tracking.php
realm/woocommerce/product-searchform.php
realm/woocommerce/single-product/add-to-cart/external.php
realm/woocommerce/single-product/add-to-cart/grouped.php
realm/woocommerce/single-product/add-to-cart/simple.php
realm/woocommerce/single-product/add-to-cart/variable.php
realm/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
realm/woocommerce/single-product/add-to-cart/variation.php
realm/woocommerce/single-product/meta.php
realm/woocommerce/single-product/photoswipe.php
realm/woocommerce/single-product/price.php
realm/woocommerce/single-product/product-attributes.php
realm/woocommerce/single-product/product-image.php
realm/woocommerce/single-product/product-thumbnails.php
realm/woocommerce/single-product/rating.php
realm/woocommerce/single-product/related.php
realm/woocommerce/single-product/review-meta.php
realm/woocommerce/single-product/review-rating.php
realm/woocommerce/single-product/review.php
realm/woocommerce/single-product/sale-flash.php
realm/woocommerce/single-product/share.php
realm/woocommerce/single-product/short-description.php
realm/woocommerce/single-product/stock.php
realm/woocommerce/single-product/tabs/additional-information.php
realm/woocommerce/single-product/tabs/description.php
realm/woocommerce/single-product/tabs/tabs.php
realm/woocommerce/single-product/title.php
realm/woocommerce/single-product/up-sells.php
realm/woocommerce/single-product-reviews.php
realm/woocommerce/single-product.php
realm/woocommerce/taxonomy-product-cat.php
realm/woocommerce/taxonomy-product-tag.php

Outdated Templates: ❌
					
					
						Lär dig hur man uppdaterar

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
1536x1536: 
2048x2048: 
woocommerce_thumbnail: 
woocommerce_single: 
woocommerce_gallery_thumbnail: 

### Klarna Checkout Request Log ###

2023-02-13 14:56:41: KCO update order
Response code: 401
Response message: 
Correlation ID:

2023-02-13 14:56:36: KCO update order
Response code: 401
Response message: 
Correlation ID:

2023-02-13 14:56:23: KCO update order
Response code: 401
Response message: 
Correlation ID:

2023-02-13 13:53:04: KCO get order
Response code: 401
Response message: 
Correlation ID:

2023-02-09 17:58:35: KCO update order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 17:58:35: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 17:58:35: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 16:21:09: KCO update order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 16:21:09: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 16:21:09: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 14:29:05: KCO update order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 14:29:05: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 14:29:05: KCO get order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 14:26:37: KCO update order
Response code: 404
Response message: 
Correlation ID:

2023-02-09 14:26:37: KCO get order
Response code: 404
Response message: 
Correlation ID:

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-11 08:48:34 +02:00
Options: ✔
Notes: 7
Onboarding: skipped

### Action Scheduler ###

Färdigbehandlad: 132
Oldest: 2023-07-10 15:35:10 +0200
Newest: 2023-08-10 11:29:38 +0200

Misslyckades: 111
Oldest: 2023-02-17 15:58:36 +0100
Newest: 2023-08-10 11:30:39 +0200

Väntar: 2
Oldest: 2023-08-10 16:02:28 +0200
Newest: 2023-08-12 11:29:53 +0200

### Status report information ###

Generated at: 2023-08-10 11:58:13 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by joakim-tldr** [comment]
Ah lol, i didnt understand the reference, but i solved it now. Sorry.

**Comment by ralucaStan** [comment]
@joakim-tldr is your problem fixed? can this ticket be closed?

**Comment by joakim-tldr** [comment]
> @joakim-tldr is your problem fixed? can this ticket be closed?

Yes sorry, it is solved.

**Comment by ralucaStan** [comment]
Happy to hear that. I'll close the issue then
