### ISSUE TITLE
Remove minimum character limit from attribute selection

### ISSUE THREAD

**Issue by inqrt** [woothemes/woocommerce#39667]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Suddenly, entering three characters minimum is mandatory when selecting a product attribute - which is nonsense since a lot of attributes can be shorter (e.g. clothing sizes S,M,L,XL,...) and renders product attribute management for users difficult.

### Expected behavior

Not having a minimum character limit for select fields in product management screen

### Actual behavior

Attributes with less than three characters cannot be found / autocomplete does not produce results

### Steps to reproduce

1. Products -> edit product
2. Attributes -> try to add attribute with a name like "S", "M", "L" or "XL"
3. Fail :)

### WordPress Environment

Latest WP and woocommerce

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by emesepocsik** [comment]
Same. Tried shoe size 36,37...43
I switched back to version 7.9

**Comment by alopezari** [comment]
Hi! Sorry to hear that you are having problems with this.

This issue is fixed by [this PR](https://github.com/woocommerce/woocommerce/pull/39686), which we will release soon in an 8.0.2 patch release.

**Comment by rrennick** [comment]
@alopezari Closing this as addressed.
