### ISSUE TITLE
Calling`WC_Cart::add_to_cart()` multiple time can generate invalid http response

### ISSUE THREAD

**Issue by plabadille** [woothemes/woocommerce#39670]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Everytime `WC_Cart::add_to_cart()` is used successfully during the same http request it add two new `set-cookie` http headers.

If during the same request it's called lets say 5 time then the http response is going to contain 10 set-cookie http headers.
This can cause some http proxy to consider the response is invalid (depending on how many headers is there ; for mine it was around 50).

This a hard to debug error because it's a `502 Bad Gateway : Upstream closed connection unexpectedly` and it's not generating error log.

Here's the problematic part of a response header example :
```
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=cde21498dd9b180e9fb5e592a1593f66; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=5d9aa3ef77237d6fb50537d75f381d03; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=a06ae67719e70cd77a16245bc0b84b47; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=d3a645ce950d5949e7734bf0bd3fa558; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=aac0da0a58042b485dda35024aedc2e2; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=a2a5cbb74fb524eafa1cb300daa8a02b; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
set-cookie: woocommerce_items_in_cart=1; path=/
set-cookie: woocommerce_cart_hash=a2caae7ea51e48a67d4a177af4c57c6f; path=/
set-cookie: wp_woocommerce_session_aaaba6bc97786721637004c4869a395c=1%7C%7C1691673299%7C%7C1691669699%7C%7C8c6e10fe7ee4974e68490e07d2c6c2a5; expires=Thu, 10-Aug-2023 13:14:59 GMT; Max-Age=172800; path=/; secure; HttpOnly
```

### Expected behavior

We should only have one `set-cookie` header directive by cookie (here two)

### Actual behavior

We got two `set-cookie` header for each time we called `WC_Cart::add_to_cart()`. If we call it 50 time then we will have 100 set-cookie headers in the response.

I think this is due to something wrong in your private method `WC_Cart_Session::set_cart_cookies()`. You check for existence of a previous cookie in the php super global `$_COOKIE`. But this global will only contain cookies after the http response is sent. So you keep adding some...

You should instead check if current http headers contain the set-cookie directive.

### Steps to reproduce

1. Make sure you have 5 buyable simple products in your demo site
2. Add the following custom php to a page (not the home page) :
```
$products = wc_get_products( [ 'posts_per_page' => 5, 'status' => 'publish', 'type' => 'simple', ] );
WC()->cart->empty_cart();
foreach ( $products as $product ) {
  WC()->cart->add_to_cart( [
    'product_id' => $product->get_id(),
    'quantity' => 1,
  ] );
}
wp_redirect( get_site_url() );
```
3. Open your devtools and go to the network section
4. Access the page (you will be redirect to the home page with 5 products in your cart)
5. checkout the response (302) in your devtools. You should see 10 set-cookie directives

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://***-wp.localhost
Site address (URL): https://***.localhost
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.2.2 - Une nouvelle version de WordPress est disponible (6.3)
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Debian)
PHP Version: 8.0.29
PHP Post Max Size: 64 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.17-MariaDB-1:10.4.17+maria~focal
Max Upload Size: 64 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Taille totale de la base de données: 1202.92MB
Taille de la base de données: 646.93MB
Taille de l’index: 555.99MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 20.55MB + Index : 6.52MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 262.83MB + Index : 266.77MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 39.58MB + Index : 36.16MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 37.58MB + Index : 30.08MB + Moteur InnoDB
wp_ac_segments: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_admin_columns: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 9.52MB + Index : 9.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 5.33MB + Index : 0.30MB + Moteur InnoDB
wp_pmxe_exports: Données : 0.22MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_google_cats: Données : 0.39MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_posts: Données : 1.52MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_templates: Données : 0.11MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_files: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_hash: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_history: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_images: Données : 0.31MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_imports: Données : 0.36MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_posts: Données : 1.52MB + Index : 0.00MB + Moteur InnoDB
wp_pmxi_templates: Données : 0.08MB + Index : 0.00MB + Moteur InnoDB
wp_postmeta: Données : 202.75MB + Index : 155.52MB + Moteur InnoDB
wp_posts: Données : 18.55MB + Index : 14.06MB + Moteur InnoDB
wp_termmeta: Données : 0.50MB + Index : 0.52MB + Moteur InnoDB
wp_terms: Données : 0.09MB + Index : 0.09MB + Moteur InnoDB
wp_term_relationships: Données : 0.22MB + Index : 0.17MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.11MB + Index : 0.13MB + Moteur InnoDB
wp_usermeta: Données : 14.52MB + Index : 7.02MB + Moteur InnoDB
wp_users: Données : 0.19MB + Index : 0.17MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.11MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.11MB + Index : 0.06MB + Moteur InnoDB
wp_wc_cvo_cache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 1.52MB + Index : 0.59MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 23.56MB + Index : 24.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 1.52MB + Index : 0.63MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 2.52MB + Index : 3.42MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woof_query_cache: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wpmailsmtp_debug_events: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpmailsmtp_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

amn_smtp: 1
attachment: 11843
client_estimate: 2
client_visitor_order: 441
client_warranty: 5
client_warranty_item: 458
ct_guest_estimate: 3
nav_menu_item: 10
oembed_cache: 82
page: 28
pair_brand_category: 5
post: 158
product: 865
product_variation: 7448
revision: 5569
shop_coupon: 30883
shop_order: 9503
styleguide: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (13) ###

Advanced Custom Fields PRO: par WP Engine – 6.1.7
Wp starter tools: par Imagile – 2.39.1
WooCommerce: par Automattic – 7.9.0 (une mise à jour de la version 8.0.1 est disponible)
Imagile Woocommerce: par Imagile – 1.13.6
Imagile Flexible Content (IFC): par Imagile – 4.4.0
Admin Columns Pro: par AdminColumns.com – 6.2.2
Advanced Custom Fields: Table Field: par Johann Heyne – 1.3.20
Custom Post Type UI: par WebDevStudios – 1.13.7
Désactiver les emojis (compatible RGPD): par Ryan Hellyer – 1.7.5
Enable Media Replace: par ShortPixel – 4.1.2
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 3.1.5
WP Mail SMTP: par WP Mail SMTP – 3.8.2
Client - Custom elements: par Imagile –

### Inactive Plugins (2) ###

Bugsnag Error Monitoring: par Bugsnag Inc. – 1.6.3
WP Fastest Cache: par Emre Vona – 1.1.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #124310 - /boutique/
Panier: ❌ La page ne contient pas le code court [woocommerce_cart] ou le bloc woocommerce/cart.
Commander: ❌ La page ne contient pas le code court [woocommerce_checkout] ou le bloc woocommerce/checkout.
Mon compte: ❌ La page ne contient pas le code court [woocommerce_my_account].
Conditions générales de vente et d’utilisation: #1339 - /espace-pro/cgv/

### Theme ###

Name: 
Version: (une mise à jour de la version 0 est disponible)
Author URL: 
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: wp-starter/woocommerce/archive-product.php
wp-starter/woocommerce/cart/cart-totals.php
wp-starter/woocommerce/cart/cart.php
wp-starter/woocommerce/cart/mini-cart.php
wp-starter/woocommerce/cart/proceed-to-checkout-button.php
wp-starter/woocommerce/checkout/form-checkout.php
wp-starter/woocommerce/checkout/form-coupon.php
wp-starter/woocommerce/checkout/form-shipping.php
wp-starter/woocommerce/checkout/review-order.php
wp-starter/woocommerce/emails/customer-on-hold-order.php
wp-starter/woocommerce/emails/email-order-details.php
wp-starter/woocommerce/global/wrapper-end.php
wp-starter/woocommerce/global/wrapper-start.php
wp-starter/woocommerce/myaccount/dashboard.php
wp-starter/woocommerce/myaccount/navigation.php
wp-starter/woocommerce/myaccount/orders.php
wp-starter/woocommerce/order/order-details-customer.php
wp-starter/woocommerce/order/order-details-item.php
wp-starter/woocommerce/order/order-details.php
wp-starter/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-11 08:32:22 +02:00
Options: ✔
Notes: 175
Onboarding: completed

### Action Scheduler ###

Terminé: 124 834
Oldest: 2023-06-16 00:19:07 +0200
Newest: 2023-08-09 17:23:28 +0200

Échoué: 3
Oldest: 2023-03-07 14:44:35 +0100
Newest: 2023-03-31 15:04:58 +0200

En attente: 1
Oldest: 2023-08-10 16:05:27 +0200
Newest: 2023-08-10 16:05:27 +0200

### Status report information ###

Generated at: 2023-08-10 12:13:58 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
For some reason the dev tools in Safari are either smarter or Safari just ignores the extra headers, but I was able to reproduce this in Chrome:

![screenshot_2023-09-22_at_09 36 09_720](https://github.com/woocommerce/woocommerce/assets/184724/bafed431-2eac-43e0-bad2-40ebb05839f5)
