### ISSUE TITLE
[Enhancement] Add a featured product button

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39679]
We need a way to mark a product as featured. I thought we could have a button in the name field and use a star icon to convey its meaning.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1005_134951

AkVNGImLgSqCObTQ3idVn7-fi-7001_308034 ( updated design link )

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/ed19f178-f513-45c6-95cc-a5201d1095b3">

**Acceptance criteria**

- [x] There's a star button on the right side of the name field. It's centered vertically.
- [x] Clicking it marks the product as featured.
- [x] When hovered, we show a tooltip that reads: `Mark as featured`
- [x] When clicked, the icon changes from `star-outline` to `star-filled`. Clicking it again reverts to the original icon.

**Comment by Marc-pi** [comment]
related to https://github.com/woocommerce/woocommerce/issues/34628 that @pmcpinto closed too early (marked as done but not done at all)
