### ISSUE TITLE
Show a summary when adding or removing variation option values

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#39688]
It'd be handy to display a simple summary when the user adds or removes values in the edit variation option modal.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-3301_326789 (temporary link)

<img width="927" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/2a358576-372e-4cdb-96e0-016bab007aca">

**Acceptance criteria**

- [ ] When the user adds values, the message should say: `X variations will be added`.
- [ ] When the user removes values, the message should say: `Y variations will be removed`.
- [ ] When the user does both, the message should say: `X variations will be added, Y variations will be removed`.
- [ ] We calculate the numbers dynamically. If necessary, we show a spinner inside the message area (and hide the text).
- [ ] The message is not shown when there are no changes to the option's values.

**Comment by mdperez86** [comment]
I'm not sure about this logic here. @louwie17 what is the actual logic of generating variations? Are we generating all variations anytime an attribute term is added or deleted? Or we just add/removes a specific set of variations depending on the selected term?

**Comment by louwie17** [comment]
> what is the actual logic of generating variations? Are we generating all variations anytime an attribute term is added or deleted? Or we just add/removes a specific set of variations depending on the selected term?

Good question, let me see if I can sum it up, although some of the logic could change, if we support the editing existing variations if all we are doing is adding an additional option.

At the moment, whenever we add a brand new variation option
- We delete all existing variations and generate all the new ones ( term count * term count * term count ) (ex: if we initially added 1 option with 3 terms and then another option with 4 terms it will generate 12 new variations, but delete the 3 that were initially added )

Whenever we edit a variation option:
- Adding new terms: Only creates the additional new variations and doesn't delete any ( the amount of new ones = the number of terms for all **other** options multiplied together )
- Removing a term: Will only remove variations ( the amount of removed ones = the number of terms for all **other** options multiplied together )

I think that basically sums it up, hope that makes sense?

**Comment by mdperez86** [comment]
@louwie17 Thanks, with that behavior and according to the ACs described in this issue I think it is possible to implement with the current logic we have when generating variations at the server side.

**Comment by jarekmorawski** [comment]
Makes sense. However, I find this part of Lourens's message concerning:

> We delete all existing variations and generate all the new ones ( term count * term count * term count )

Does this mean that the merchant loses the transaction details and sales history? If so, we should definitely avoid that.

**Comment by louwie17** [comment]
> Does this mean that the merchant loses the transaction details and sales history? If so, we should definitely avoid that.

They won't loose their sale history, not the most important transaction details.
They would only loose the reference to the original product variation that was sold. 
Which is only really noticeable in the Analytics orders table, where products show blank. 
<img width="1190" alt="Screenshot 2023-09-27 at 9 33 51 AM" src="https://github.com/woocommerce/woocommerce/assets/2240960/ad2c29f2-c0d9-4d95-ae1f-766f5cbca3b6">

**Comment by louwie17** [comment]
Currently the logic is quite simple though, and as discussed in the P2 thread for one of the bugs, we could optimize this a bit, that when adding a new variation we always just update the existing one's first and generate all the additional variations.

Which will mean that when adding any new variation option we only ever add ( which does make sense ).

**Comment by jarekmorawski** [comment]
> Currently the logic is quite simple though, and as discussed in the P2 thread for one of the bugs, we could optimize this a bit, that when adding a new variation we always just update the existing one's first and generate all the additional variations.

I'd vote for this. Would you mind creating an issue for this, Lourens? I'm sure you'll describe the technical intricacies better than I can.
