### ISSUE TITLE
Rest API: COD and BACS orders can't be refunded via `/wp-json/wc/v3/orders`

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#39695]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in zd-6596986 

Seems like orders paid via BACS or COD cannot be refunded using the REST API. 

Although there is no payment gateway involved (there's nothing to refund), you can still refund the order's net payment from `WooCommerce → Orders`. Therefore, shouldn't the API also have the capability to process the refund?

Not sure if this should be labelled as a bug or enhancement.

### Expected behavior

The order net payment and other field to be updated.

### Actual behavior

<img src="https://d.pr/i/9KD0PF+" alt="">
Link to image: https://d.pr/i/9KD0PF

### Steps to reproduce

1. Create an order via site or API
2. Try to refund it using `POST /wp-json/wc/v3/orders/<id>/refunds`

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://test.wpcomstaging.com
Site address (URL): https://test.wpcomstaging.com
WC Version: 8.0.1
REST API Version: ✔ 8.0.1
WC Blocks Version: ✔ 10.8.2
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@Babylon1999 apologies for the late reply here. You can create refunds for COD and BACS orders if you add the [`api_refund` property](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-refund-properties) to your request payload and set it to `false`. Example:

```
{
  "amount": "16.50",
  "line_items": [
    {
      "id": 66,
      "refund_total": "15",
      "refund_tax": [
        {
          "id": 4,
          "refund_total": "1.5"
        }
      ]
    }
  ],
  "api_refund": false
}
```
