### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by MChaban47** [woothemes/woocommerce#39708]
This line 136:
"$specs_group            = get_transient( $this->args['transient_name'] ) ?? array();"
https://github.com/woocommerce/woocommerce/blob/e8d0a081ad32d39b742bc470103c176cde7e1821/plugins/woocommerce/src/Admin/DataSourcePoller.php#L136C3-L136C3
will cause "Deprecated: Automatic conversion of false to array is deprecated" error on line 138.
Better to use "?:".
Like: "$specs_group            = get_transient( $this->args['transient_name'] ) ?: array();"

**Comment by puntope** [comment]
The mentioned file is deprecated since 8.8.0. [The new class RemoteSpecs/DataSourcePoller.php doesn't produce the warning anymore. ](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L114)
