### ISSUE TITLE
[Customize Your Store] AI Wizard Business Info Step

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39709]
## User Story
> As a new merchant, I would like AI to design my site, so I can sell sooner.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=3076%3A289828&mode=dev)

Acceptance Criteria

```Scenario: User enters the screen
    Given the user starts the AI Wizard
    Then the input should show a placeholder
    And the continue button should be disabled

Scenario: User provides business info
    Given the user provides text input
    Then the continue button should be enabled
    And an AI suggestion should be stored in state for the look: contempory, classic, bold
    And an AI suggestion should be stored in state for the sound: informal, neautral, formal

Scenario: User continues
    Given the user presses the continue button
    Then the next screen should be shown
```

**Comment by moon0326** [comment]
@adrianduffell 

>  And an AI suggestion should be stored in state for the look: contempory, classic, bold
    And an AI suggestion should be stored in state for the sound: informal, neautral, formal

Hey Adrian ✋ It sounds like we'll need to call an API to get the look and sound from the user input. Or do we have a set of rules to determine look and sound values?

**Comment by adrianduffell** [comment]
@moon0326 Yep we'll need to make an API request for this. @chihsuan how do you think it would be best handled?

To explain it a bit more, once the business info has been entered, we should use AI to return a look and sound. We'll use those values as the default suggestion on the next screens.

**Comment by chihsuan** [comment]
> how do you think it would be best handled?

Let's call the AI API on the client side since we'll need to use the suggestion on the next screens. 🙂 

To do that, we'll need to improve the Woo AI package to have non-streaming (p1690982687707709/1690933535.678249-slack-C056QSJJQ91).

https://github.com/woocommerce/woocommerce/blob/566d5092b2d18f3127b5814635b86314a608bec7/packages/js/ai/src/utils/text-completion.ts#L93-L105


- non-streaming endpoint https://public-api.wordpress.com/wpcom/v2/text-completion
- source code (uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Snv%2Qgrkg%2Qpbzcyrgvba.cuc%3Se%3Qs7904rq8-og)
- Related spike https://github.com/woocommerce/woocommerce/issues/39527

**Comment by moon0326** [comment]
@chihsuan @adrianduffell  It looks like `requestJetpackToken()` requires Jetpack plugin. Should we skip calling the API when Jetpack isn't installed?

FYI, https://public-api.wordpress.com/wpcom/v2/text-completion returns 404 🤔

**Comment by chihsuan** [comment]
> @chihsuan @adrianduffell It looks like `requestJetpackToken()` requires Jetpack plugin. Should we skip calling the API when Jetpack isn't installed?
> 
> FYI, https://public-api.wordpress.com/wpcom/v2/text-completion returns 404 🤔

Hey @moon0326, Good question! If the site does not meet the conditions for a completed AI wizard, we will display an error message on the intro page (Mrk6SERPZ4KrFHSjM0a8TK-fi-2631_250547), and the store editing team is also investigating getting the token without the Jetpack plugin (using Jetpack connection package). So, I think for now you can assume that Jetpack will exist.

> FYI, https://public-api.wordpress.com/wpcom/v2/text-completion returns 404 🤔

Did you send a POST request? It returns 400 on my side.  🤔 

![Screenshot 2023-08-31 at 11 29 23](https://github.com/woocommerce/woocommerce/assets/4344253/2d135321-fd7c-4353-ae27-2f99acf26b84)


Thank you!

I should have tried POST :) Thank you!

**Comment by chihsuan** [comment]
https://github.com/woocommerce/woocommerce/pull/39979
