### ISSUE TITLE
[Customize Your Store] Loading

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39712]
## User Story
> As a new merchant, I would like AI to design my site, so I can sell sooner.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2748%3A260988&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/1ead0a24-c537-4b60-a5bf-377c44162ee4)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/8f3baa8c-f380-41c5-9c8f-a74bc67cc4ac)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/ca01a079-3c7a-4b7b-bd81-967064a84c39)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/133c75f8-a3b2-4706-a0ed-4f9617ebd53b)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/63b845f6-93a5-4ea9-857b-16c0c86777b2)

## Acceptance Criteria

```
Scenario: User completes AI wizard
    Given the user completes the AI Wizard
    Then AI should design the site in the background
    And a progress bar should increment over the duration
    And different messages should appear at evenly timed intervals


Scenario: AI designs the store in the background
    Given AI designs the store in the background
    Then AI should select a homepage template
    And AI should populate the homepage template with images
    And AI should populate the homepage template with welcome text
    And AI should select a color pair
    And AI should select a font
```

**Comment by chihsuan** [comment]
### Dev notes

About how to use AI API:

- https://github.com/woocommerce/woocommerce/issues/39527

**Comment by chihsuan** [comment]
We'll need to coordinate with the Store Editing team to populate patterns.

- https://github.com/woocommerce/woocommerce-blocks/issues/10503
- https://github.com/woocommerce/woocommerce/issues/39529

**Comment by chihsuan** [comment]
> Scenario: AI designs the store in the background
    Given AI designs the store in the background
    Then AI should select a homepage template
    And AI should populate the homepage template with images
    And AI should populate the homepage template with welcome text
    And AI should select a color pair
    And AI should select a font

Hey @adrianduffell 👋  In this step, I think we will also install and activate the Creatio theme, right? It seems that Creatio theme is only available in DotCom. Do you know if we need to publish it to DotOrg?

I expected in this loading screen, we would need to do:

1. Update ['woo_ai_describe_store_description'](https://github.com/woocommerce/woocommerce/blob/9418072a472b53bd4519086bc1958145600c42ae/plugins/woo-ai/includes/class-woo-ai-settings.php#L39) option.
2. Call `/wc/store/v1/patterns ` endpoint https://github.com/woocommerce/woocommerce-blocks/issues/10658 to update patterns with AI-generated content
3. AI requests to select patterns / templates
4. AI requests to choose a color palette
5. AI requests to choose a font pairing
6. Install and activate the Creatio theme
7. Update block theme global styles and block template data with AI response data.

Am I missing something? 

cc @nefeline

**Comment by adrianduffell** [comment]
> Hey @adrianduffell 👋 In this step, I think we will also install and activate the Creatio theme, right? It seems that Creatio theme is only available in DotCom. Do you know if we need to publish it to DotOrg?

@chihsuanFor dotOrg, I think the approach will be that the assembler should work with any block theme.

I think - for the AI in Woo Express let's see if the default theme (Tsubaki) is suitable, otherwise we could use Creatio. However, if we use Creatio I think we would need to add `theme_support` [flags](https://woocommerce.com/document/woocommerce-theme-developer-handbook/#section-6) to make it compatible with WooCommerce.

**Comment by nefeline** [comment]
Hey @chihsuan ! This sounds like a great plan to me. Regarding:

> AI requests to select patterns / templates

I suspect we won't need AI to do this job for us, considering the content of the patterns will already be AI-managed: is there a scenario in particular where you see this being useful?

**Comment by nefeline** [comment]
Regarding switching themes (step 6) & also @adrianduffell 's comment on:

> I think the approach will be that the assembler should work with any block theme.

Should we, at some point during the onboarding flow, inform the users that a block theme is required for them to take full advantage of these features? Switching themes on any site outside Woo Express could be dangerous, considering someone could have a consolidated blog that they decided to use to also sell products & install the WooCommerce plugin at some point: there could be some bad repercussions in such cases.

cc: @verofasulo

**Comment by adrianduffell** [comment]
> Should we, at some point during the onboarding flow, inform the users that a block theme is required for them to take full advantage of these features? 

Yes, definitely! These are the type of use cases that need to be explored in Core next.

**Comment by adrianduffell** [comment]
> > AI requests to select patterns / templates

> I suspect we won't need AI to do this job for us, considering the content of the patterns will already be AI-managed: is there a scenario in particular where you see this being useful?

The concept is for AI to assemble a starting layout. As an example - it would choose a header pattern based on what it knows about the site. If it makes a bad choice, the user would personalize it with something better via the pattern assembler.

**Comment by nefeline** [comment]
> it would choose a header pattern based on what it knows about the site. If it makes a bad choice, the user would personalize it with something better via the pattern assembler.

Thanks Adrian! Interesting! Is this expected to be part of the MVP as well? I was assuming the initial patterns in the templates would always be the same but with different images and texts depending on what the user added as a description for their store. Out of curiosity: Do we have a few designs for the expected templates depending on the business description?

**Comment by chihsuan** [comment]
> I think - for the AI in Woo Express let's see if the default theme (Tsubaki) is suitable, otherwise we could use Creatio. However, if we use Creatio I think we would need to add theme_support [flags](https://woocommerce.com/document/woocommerce-theme-developer-handbook/#section-6) to make it compatible with WooCommerce.

Thanks @adrianduffell, gotcha, sounds good to me!

> Is this expected to be part of the MVP as well? 

Yes, it's expected to be part of the MVP. @nefeline 

Ghidorah will do:

> - Ask AI which header and footer to choose according to the answers in the wizard
> - Ask AI to classify whether the site is a small or large business. Then choose the template designated for small or large business.
> -  Adrian p1694152550425039/1694134803.800619-slack-C01SFMVEYAK

**Comment by chihsuan** [comment]
We can refer to wpcom's assemble_site (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Q68osn0ns%2399%2Q111-og) API to learn how to store the results of AI selection.

**Comment by nefeline** [comment]
> Call /wc/store/v1/patterns  endpoint https://github.com/woocommerce/woocommerce-blocks/issues/10658 to update patterns with AI-generated

Hi @chihsuan! This endpoint is already in code review on https://github.com/woocommerce/woocommerce-blocks/pull/10881. If you need it to unblock any work here right away, feel free to checkout to that branch, or download the zip file from the testing instructions on that PR and use it to install/activate WooCommerce blocks on your site.

**Comment by chihsuan** [comment]
Awesome, thank you! @nefeline

**Comment by rjchow** [comment]
Made two follow up issues:

https://github.com/woocommerce/woocommerce/issues/40162
https://github.com/woocommerce/woocommerce/issues/40163
