### ISSUE TITLE
[Customize Your Store] Logo

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39715]
## User Story

> As a new merchant, I would like a to fine tune the AI design, so I can add my personal touch.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2631%3A256540&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/85161d02-4c68-4365-9281-f7ad24c18524)

## Acceptance Criteria

```
Scenario: Logo panel is opened
    Given the user opens the logo panel
    Then a logo upload field is shown
    And logo settings are shown

Scenario: User uploads an image 
    Given the user uploads an image
    Then the logo should be populated in the preview pane
    
Scenario: User changes a setting
    Given the makes a settings change
    Then the settings should be reflected in the preview pane

Scenario: Save
    Given the user presses the save button
    Then the rendered preview should be saved permanently
```

**Comment by chihsuan** [comment]
### Dev notes

For how to upload Logo and how to update settings, please refer to https://github.com/woocommerce/team-ghidorah/issues/242#issuecomment-1680154693.
