### ISSUE TITLE
[Customize Your Store] Footer

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39719]
## User Story

> As a new merchant, I would like a to fine tune the AI design, so I can add my personal touch.

## Dev

Should be similar to header implementation, please refer to:

- https://github.com/woocommerce/woocommerce/issues/39718

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2631%3A255291&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/9dac2233-ed13-4850-af22-915088a31b9c)

## Acceptance Criteria

```
Scenario: Footer panel is opened
    Given the user opens the header panel
    Then available footer patterns are shown

Scenario: User changes the footer 
    Given the changes the footer
    Then the footer should be updated in the preview pane

Scenario: Save
    Given the user presses the save button
    Then the rendered preview should be saved permanently
```

**Comment by chihsuan** [comment]
We'll only need to show these three footers:


| Title                               | Slug                                          | Screenshot (as implemented) | Type                         |
| ----------------------------------- | --------------------------------------------- | ---------- | ---------------------------- |
| [Large Footer](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-large.php)                        | woocommerce-blocks/footer-large               |  <img width="999" alt="Screenshot 2023-07-04 at 15 35 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/170bbdba-f0a9-47c1-93ee-fc01e0122d02"> |  Opinionated: custom font size                            |
| [Footer with Simple Menu and Cart](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-simple-menu-and-cart.php)    | woocommerce-blocks/footer-simple-menu-and-cart|   <img width="1001" alt="Screenshot 2023-07-04 at 15 37 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/0d6a4c2b-721a-4f77-b7e8-489c14958af7"> |   Opinionated: custom font size                           |
| [Footer with 3 Menus](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-with-3-menus.php)                 | woocommerce-blocks/footer-with-3-menus        |  <img width="997" alt="Screenshot 2023-07-04 at 15 41 28" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/69d609b7-6ffd-4c5f-8eea-c78d1b97edd4"> |  Opinionated: custom font size                            |
