### ISSUE TITLE
[Customize Your Store] Colors

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39716]
## User Story

> As a new merchant, I would like a to fine tune the AI design, so I can add my personal touch.

## Design

* Mrk6SERPZ4KrFHSjM0a8TK-fi-2631%3A258874

## Acceptance Criteria

```
Scenario: Colors panel is opened
    Given the user opens the color panel
    Then available color palettes are shown
    And a section for the user to create their own is collapsed 

Scenario: User changes the color palette
    Given the user uploads an image
    Then the colors should be populated in the preview pane

Scenario: Save
    Given the user presses the save button
    Then the rendered preview should be saved permanently
```

**Comment by chihsuan** [comment]
### Dev notes

Here are available color palettes: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Stybony%2Qfglyrf%2Qinevngvba%2Sgurzrf%2Scho%2Sperngvb%2Spbybe%2Qcnyrggrf%2S-og

To change/save color palette, please refer to https://github.com/woocommerce/team-ghidorah/issues/240#issuecomment-1680185080
