### ISSUE TITLE
[Customize Your Store] Assembler Onboarding

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39713]
## User Story
> As a new merchant, I would like a tour of the pattern assembler, so I can understand it quickly.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2631%3A253787&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/7ffa6a2d-13c7-4bdf-a7c0-73d80d11e30d)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/b6f0fcce-1fe5-413e-a6df-f200b8a558d4)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/95160ef4-9cc4-4855-bff0-da2135442a15)

## Acceptance Criteria

```
Scenario: Pattern assembler shown for the first time
    Given the user views the pattern assembler for the first time
    Then a spotlight tour should be shown

```

**Comment by chihsuan** [comment]
### Dev notes

To make a resizable bar visible and show a `Drag to size` label during the onboarding tour, I think we'll need to fork the [`ResizableFrame`](packages/edit-site/src/components/resizable-frame/index.js) component, which is used in Gutenberg FSE.

Once we complete this task, we should create a follow-up task to contribute it back upstream.
