### ISSUE TITLE
Woo AI Image Background Removal - Featured Image Editor

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#39727]
~Do we want background removal to happen automatically? If so, we should probably do this:~

- [ ] Grab the image URL after an image is uploaded.
- [ ] Call the Background Removal API endpoint, passing in the image URL.
- [ ] Get the image from the response, which can either be a PNG file to download or a base64 representation of the image.
- [ ] Upload the image to the site via the Media Library, ensuring that the user can see the image without needing to manually refresh the page.

Otherwise, we may want to have background removal manually initiated.

- [ ] Hook into the sidebar of the Media Library editor, adding a React component to remove the background.
- [ ] Call the Background Removal API endpoint using the hook created in #40037. The WPCOM REST API endpoint requires a multipart/form-data request with the image file itself as a piece of the request (not the URL to the image).
- [ ] Get the image from the response, which can either be a PNG or a JPG file (prefer JPG).
- [ ] Upload the image to the site via the Media Library, ensuring that the user can see the image without needing to manually refresh the page. If we need to force refresh because there's no other option, so be it.

**Comment by tommyshellberg** [comment]
Let's opt for the latter option to not disrupt the normal image editing flow path and make it more of a cognizant "opt in" flow for the first iteration.

**Comment by joelclimbsthings** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce/issues/40440
