### ISSUE TITLE
[Customize Your Store] Transitional Page

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39721]
## User Story

> As a new merchant, I would like a to fine tune the AI design, so I can add my personal touch.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2631%3A262335&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/ee59b1e9-992a-4ef0-8323-bbb4da1ea557)

## Acceptance Criteria

```
Scenario: Design hub is closed
    Given the user closes the design hub
    Then a transitional page is shown
    And a static (non-clickable) preview of the site is shown
    And a button to preview the store is shown
    And a link to the full site editor is shown
    And a link back to the Woo Home Screen is shown

Scenario: User previews the store
    Given the user previews the store
    Then the store front end should open in a new tab

Scenario: User chooses the full site editor
    Given the user chooses the full site editor
    Then the user should be redirected to the Site Editor

Scenario: User chooses home
    Given the user chooses to go home
    Then the user should be redirected to the Woo homescreen

```

**Comment by ilyasfoo** [comment]
@adrianduffell In Figma, there's a comment (Mrk6SERPZ4KrFHSjM0a8TK-fi-2748:260698#523686665) that mentioned it requires a generated static image for the preview. Is this something that already exists, or do we need to build it into core?

**Comment by adrianduffell** [comment]
@ilyasfoo We'll need to build it into Core. @chihsuan do you have ideas which package to use?

**Comment by chihsuan** [comment]
We have an internal tool for this: https://github.com/Automattic/mShots
(example: https://github.com/Automattic/wp-calypso/blob/6923bed938911a931e722a1efa6fcbbf942677a9/packages/onboarding/src/mshots-image/index.tsx)

**Comment by ilyasfoo** [comment]
@chihsuan Not sure if I understand this correctly, but is mShots service hosted by Automattic, not something that's packaged along with the plugin? I imagine it would be super complicated if it's the latter.

Also, if it's a hosted service, I think there would be cost incurred, do we need to ask around? And also we need to assume the user's site is online.

I wonder why we don't use a live preview instead? 🤔

**Comment by chihsuan** [comment]
> @chihsuan Not sure if I understand this correctly, but is mShots service hosted by Automattic, not something that's packaged along with the plugin? I imagine it would be super complicated if it's the latter.

> Also, if it's a hosted service, I think there would be cost incurred, do we need to ask around? And also we need to assume the user's site is online.

@ilyasfoo Good questions. It's actually a public WP API for everyone, so I don't think we need to ask before using it. 🙂 
- https://thewpx.com/wordpress-display-screenshot-of-website/


> I wonder why we don't use a live preview instead? 🤔

I think that's okay too. I don't have a strong preference. However, we'll still need to generate a thumbnail for the theme page. (Mrk6SERPZ4KrFHSjM0a8TK-fi-3625%3A280491)

**Comment by ilyasfoo** [comment]
@chihsuan  Ah, gotcha, thanks for the details! Sounds good to me then 👍
