### ISSUE TITLE
WcPayWelcomePage causing all admin pageviews to be slow

### ISSUE THREAD

**Issue by scottbuscemi** [woothemes/woocommerce#39742]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WcPayWelcomePage is running a database query on every admin page despite WooCommerce Payments not being enabled on the site.

<img width="1329" alt="Screenshot 2023-08-14 at 7 48 02 PM" src="https://github.com/woocommerce/woocommerce/assets/4336848/b9c55b54-6af5-490b-8519-e35ad56fb9b9">

```WP_Query->get_posts
WP_Query->query
WP_Query->__construct
WC_Order_Data_Store_CPT->query
WC_Data_Store->__call
WC_Order_Query->get_orders
wc_get_orders
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->get_incentive
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->must_be_visible
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->register_payments_welcome_page
do_action('admin_menu')
require_once('wp-admin/includes/menu.php')
require('wp-admin/menu.php')
require_once('wp-admin/admin.php')```

### Expected behavior

Opting out of WooCommerce Payments and its associates upsells should not affect site speed.

### Actual behavior

Not opting into WooCommerce Payments causes the admin pages to be slow to show upsells.

### Steps to reproduce

1. Go to the `/wp-admin` of a WooCommerce store
2. View the Query Monitor database queries


### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.0.1
REST API Version: ✔ 8.0.1
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.1
WC Database Prefix: wp_
Total Database Size: 2338.35MB
Database Data Size: 1095.67MB
Database Index Size: 1242.68MB


### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by thoughtspacewebsites** [comment]
Weighing in here to say I'm seeing this exact same behavior, diagnosed through query monitor as being from the WCPayWelcomePage portion, and again, also not using WooCommerce payments at all. This has crippled our ability to upgrade and attempt to use HPOS. It's ha the exact opposite effect of slowing down site speed so far that I'm not even sure if HPOS background cron DB updates will be able to complete in a reasonable timeframe. Our site has over 2,000,000 records in the post table, so this slow query is really confounded on our site, with every admin page load taking almost a full minute. Can provide any required debug information. In the meantime, anyone know how to completely disable WCPayWelcomePage?

**Comment by beaulebens** [comment]
Looks like the query is being [triggered here](https://github.com/woocommerce/woocommerce/blob/dc9272946df5111be618096233d95369feb6aa1a/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L277-L283).

@vladolaru can you please look at revising this logic -- we probably need to cache the result of that query vs doing it every time. Also please make sure we're bailing out from this entire codepath as early as possible if someone has explicitly opted out already.

**Comment by thoughtspacewebsites** [comment]
Related:
https://github.com/woocommerce/woocommerce/issues/39668

**Comment by thoughtspacewebsites** [comment]
I'm trying to simply remove the hooked function with `remove_action('admin_menu', array('WcPayWelcomePage', 'register_payments_welcome_page'));`, but it doesn't appear to be working. I suspect it's because I'm using the wrong class name but I can't actually find where this class is being instantiated and what the proper name would be. This could be a sufficient temporary holdover for users experiencing this bug on large sites that want to simply disable the welcome page completely to circumvent the issue.

**Comment by thoughtspacewebsites** [comment]
Found it, there's a filter to bypass the function within the updated code.

For anyone else finding this, the answer to temporarily work around this and remove the admin page / slow query is to add the following in to your code anywhere (functions.php, custom plugin, etc):

`add_filter('woocommerce_allow_marketplace_suggestions', '__return_false');`

**Comment by vbelolapotkov** [comment]
Please note that `has_wcpay` is causing the same problem, see #40053 for more details.

@vladolaru it looks like #39958 fixes this one. Could you please confirm, mention target WC release with the fix, and close the issue if this is the case?

**Comment by daquinons** [comment]
@vbelolapotkov 8.0.3 included a temporary solution: https://github.com/woocommerce/woocommerce/pull/39882

8.1.0 will include https://github.com/woocommerce/woocommerce/pull/39958
