### ISSUE TITLE
Woocommerce attribute value needs to be atleast 3 characters long

### ISSUE THREAD

**Issue by koonda** [woothemes/woocommerce#39763]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I am using attribute called Size (Velikost) and assigning it single character sizes like S, M, L, XL, etc...

However after recent update, I am not able to enter single character sizes as woocommerce wants me to write at least 3 characters:
![image](https://github.com/woocommerce/woocommerce/assets/32578781/99043338-05d7-4be5-b10e-3b1ef4aa3b22)

### Expected behavior

I should be able to write single character sizes in the attribute table.

### Actual behavior

I am not able to assign correct single character size to my product attribute.

### Steps to reproduce

1. Create new product
2. Go to attributes tab
3. Add attribute Size 
4. Try to add single character size - for example S

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://heritagehome.cz
Site address (URL): https://heritagehome.cz
WC Version: 8.0.1
REST API Version: ✔ 8.0.1
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.1
WC Database Prefix: vfkh_
Celková velikost databáze: 239.52MB
Velikost dat databáze: 194.90MB
Velikost indexu databáze: 44.62MB
vfkh_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
vfkh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
vfkh_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.38MB + Engine InnoDB
vfkh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_actionscheduler_actions: Data: 2.02MB + Index: 0.17MB + Engine InnoDB
vfkh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_actionscheduler_logs: Data: 2.02MB + Index: 1.08MB + Engine InnoDB
vfkh_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_aepc_logs: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
vfkh_aiowps_audit_log: Data: 1.38MB + Index: 0.06MB + Engine InnoDB
vfkh_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_aiowps_message_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_comments: Data: 0.30MB + Index: 0.31MB + Engine InnoDB
vfkh_energyplus_daily: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
vfkh_energyplus_events: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
vfkh_energyplus_requests: Data: 12.52MB + Index: 5.55MB + Engine InnoDB
vfkh_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
vfkh_e_notes_users_relations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
vfkh_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vfkh_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_mainwp_stream: Data: 0.23MB + Index: 0.38MB + Engine InnoDB
vfkh_mainwp_stream_meta: Data: 1.52MB + Index: 2.08MB + Engine InnoDB
vfkh_mergado_news: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_ml_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_options: Data: 9.02MB + Index: 0.27MB + Engine InnoDB
vfkh_postmeta: Data: 83.41MB + Index: 10.11MB + Engine InnoDB
vfkh_posts: Data: 17.16MB + Index: 4.70MB + Engine InnoDB
vfkh_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vfkh_rank_math_analytics_objects: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
vfkh_rank_math_internal_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vfkh_rank_math_internal_meta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
vfkh_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_slides: Data: 1.16MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_shortpixel_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_shortpixel_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_shortpixel_postmeta: Data: 4.41MB + Index: 5.13MB + Engine InnoDB
vfkh_shortpixel_queue: Data: 9.52MB + Index: 1.72MB + Engine InnoDB
vfkh_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_swift_performance_image_optimizer: Data: 31.56MB + Index: 8.48MB + Engine InnoDB
vfkh_swift_performance_warmup: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
vfkh_termmeta: Data: 0.41MB + Index: 0.16MB + Engine InnoDB
vfkh_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vfkh_term_relationships: Data: 0.38MB + Index: 0.23MB + Engine InnoDB
vfkh_term_taxonomy: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
vfkh_usermeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
vfkh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vfkh_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vfkh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vfkh_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vfkh_wc_product_attributes_lookup: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
vfkh_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wc_product_meta_lookup: Data: 0.19MB + Index: 0.33MB + Engine InnoDB
vfkh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_wfconfig: Data: 1.27MB + Index: 0.00MB + Engine InnoDB
vfkh_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
vfkh_wfhits: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
vfkh_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vfkh_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wflogins: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
vfkh_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vfkh_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vfkh_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
vfkh_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_wml_entries: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vfkh_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vfkh_wpr_rocket_cache: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
vfkh_wpr_rucss_used_css: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vfkh_zasilkovna_dopravci: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
vfkh_zasilkovna_log: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
vfkh_zasilkovna_pobocky: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vfkh_zasilkovna_staty: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 15185
cms_block: 25
custom_css: 1
elementor_library: 2
elementor_snippet: 1
jet-engine: 1
mc4wp-form: 1
nav_menu_item: 24
oembed_cache: 1
page: 14
portfolio: 9
post: 2
product: 612
recenze: 22
revision: 1089
shop_coupon: 1
shop_order: 246
woodmart_sidebar: 1
woodmart_slide: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

All In One WP Security: Autor: All In One WP Security & Firewall Team – 5.2.3
České služby pro WordPress: Autor: Pavel Hejn – 0.6-alpha
Elementor Pro: Autor: Elementor.com – 3.15.1
Elementor: Autor: Elementor.com – 3.15.2
Energy+: Autor: EN.ER.GY – 1.2.4
Flexible Shipping: Autor: Octolize – 4.21.7
JetEngine: Autor: Crocoblock – 3.2.3.2
Limit Login Attempts Reloaded: Autor: Limit Login Attempts Reloaded – 2.25.22
Loco Translate: Autor: Tim Whitlock – 2.6.4
PixelYourSite: Autor: PixelYourSite – 9.4.2
Safe SVG: Autor: 10up – 2.1.1
Rank Math SEO: Autor: Rank Math – 1.0.121.1
ShortPixel Image Optimizer: Autor: ShortPixel - Convert WebP/AVIF & Optimize Images – 5.4.0
Toret Zásilkovna: Autor: Toret.cz – 5.18.4
UpdraftPlus - Backup/Restore: Autor: UpdraftPlus.Com
DavidAnderson – 1.23.9

WebP Express: Autor: Bjørn Rosell – 0.25.6
Checkout Field Editor for WooCommerce: Autor: ThemeHigh – 1.9.0
Product Feed PRO for WooCommerce: Autor: AdTribes.io – 12.8.1
Payment Plugins for Stripe WooCommerce: Autor: Payment Plugins
support@paymentplugins.com – 3.3.45

PDF Invoices & Packing Slips for WooCommerce: Autor: WP Overnight – 3.5.6
WooCommerce: Autor: Automattic – 8.0.1 (aktualizace na verzi 8.0.2 je dostupná)
Woodmart Core: Autor:  – 1.0.34
wp_mail return-path: Autor: Barnaby Puttick – 1.1.0
WP Rocket: Autor: WP Media – 3.14.3
WPS Hide Login: Autor: WPServeur
NicolasKulka
wpformation – 1.9.8

### Inactive Plugins (6) ###

Disable Bloat for WordPress & WooCommerce: Autor: Disable Bloat – 3.2.11
Hide Admin Notices: Autor: PontetLabs – 1.2.2
MailerLite - WooCommerce integration: Autor: MailerLite – 1.8.7
WC Featured Products: Autor: itzmekhokan – 1.0.2
White Label CMS: Autor: www.videousermanuals.com – 2.6
Woo Discount Rules: Autor: Flycart – 2.6.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: Autor:  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Obchod: #8 - /eshop/
Košík: #9 - /kosik/
Pokladna: #10 - /pokladna/
Můj účet: #11 - /muj-ucet/
Obchodní podmínky: ❌ Stránka není zvolena

### Theme ###

Name: Woodmart
Version: 7.2.5
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-16 12:44:58 +02:00
Options: ✔
Notes: 105
Onboarding: completed

### Action Scheduler ###

Complete: 401
Oldest: 2023-07-16 11:38:57 +0200
Newest: 2023-08-16 02:18:56 +0200

Pending: 4
Oldest: 2023-08-16 08:59:11 +0200
Newest: 2023-08-20 11:56:17 +0200

Failed: 9
Oldest: 2022-09-28 22:53:28 +0200
Newest: 2023-07-10 11:18:47 +0200

### Status report information ###

Generated at: 2023-08-16 08:59:09 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by limewebdevelopment** [comment]
I've just come to post the exact same issue reported by one of my customers.

Another use case is shown below.

![image](https://github.com/woocommerce/woocommerce/assets/22960478/e49c4a8d-dcfe-4035-8a18-7d0e690b4d83)

You can enter 1 character followed by two spaces and it seems to find the attributes, however this isn't intuitive to many store owners.
Perhaps we could have a filter to override this as required on a per store basis?

**Comment by rrennick** [comment]
@koonda Thanks for reporting the issue. It was addressed in #39686.
