### ISSUE TITLE
[Enhancement]: When updating product via api, not require Status

### ISSUE THREAD

**Issue by radialmonster** [woothemes/woocommerce#39774]
### Describe the solution you'd like

I am trying to use the update via rest function from a service like ifttt.  I would like to update the inventory and pricing of an existing product.  I woudl like to not change the status, i would like the status on woocommerce to stay at whatever status that item is.  However if in our call we leave the status blank, we get an error:
status is not one of draft, pending, private, publish, future, auto-draft, and trash.

thanks

### Describe alternatives you've considered

this requires us to lookup the status of the product first, and then publish an update with that same status, which we can.  But it would be easier to just keep the existing values when no value is being passed.

**Comment by rrennick** [comment]
> However if in our call we leave the status blank, we get an error:
status is not one of draft, pending, private, publish, future, auto-draft, and trash.

@radialmonster When you update a product, order, or coupon with the REST API you should only include the fields you want to change. I'll close the issue as a support question.
