### ISSUE TITLE
Add Pricing item to the Quick Actions menu per Variation item

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39788]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

User needs a way to modify each variation quickly under the Variations tab.

**Epic**

#35670

**ACs**

- [ ] Add `Pricing` item to the dropdown menu AkVNGImLgSqCObTQ3idVn7-fi-1761_414364
- [ ] Add the dropdown submenu from the `Pricing` item AkVNGImLgSqCObTQ3idVn7-fi-1641_215261
- [ ] Add `List price` and `Sale price` groups to the dropdown menu AkVNGImLgSqCObTQ3idVn7-fi-1641_215261
- [ ] Add `Set list price`, `Set sale price`, `Increase`, `Decrease` items to each group and `Schedule sale`. When the user click on each item a modal (`window.prompt`) should be shown to ask for the new vale AkVNGImLgSqCObTQ3idVn7-fi-1641_218691 see https://github.com/woocommerce/woocommerce/issues/39788#issuecomment-1682515221 for more details.
- [ ] Save the price values of the selected variation
- [ ] Show a snackbar informing users that the variations were updated AkVNGImLgSqCObTQ3idVn7-fi-1641_218705
- [ ] Track all the quick actions behavior, including the modal to add/update values

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag Could you share the tracking event names and properties related to this issue please?

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag Could you describe a little more what should happen if the user clicks the items `Increase`, `Decrease` and `Schedule` from AkVNGImLgSqCObTQ3idVn7-fi-1641_215261. 
If more than one field is required like for `Schedule` we are not going to be able to use the normal prompt as shown in AkVNGImLgSqCObTQ3idVn7-fi-1641_218691. So for cases like this a custom modal will be required

**Comment by jarekmorawski** [comment]
Sure thing! All actions in `Quick actions` already exist in the current experience and are tucked away in the dropdown in the top left. We should re-use their behavior, so if the user selects `Increase` or Decrease, they'll see a browser dialog window.

https://github.com/woocommerce/woocommerce/assets/79307566/1b52096e-25fa-4f2d-b612-9e47f72d41ab

> So for cases like this a custom modal will be required

The current experience shows something like this, which is far from perfect, but good enough for the MVP.

<img width="480" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/dc07b9be-7d36-4b39-a304-3ed92f4c44a4">
