### ISSUE TITLE
Add quick actions dropdown menu per variation item

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39787]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

User needs a way to modify each variation quickly under the Variations tab.

**Epic**

#35670

**ACs**

- [x] Remove the `Edit` button from each variation row within the Variations list under the Variations Tab
- [x] Add a dropdown menu to the end of each variation row AkVNGImLgSqCObTQ3idVn7-fi-1641_225719
- [x] Add the Variation ID to the dropdown menu AkVNGImLgSqCObTQ3idVn7-fi-1641_225719
- [x] Add the Preview item to the dropdown menu AkVNGImLgSqCObTQ3idVn7-fi-1641_225719
- [x] Add the Delete item to the dropdown menu AkVNGImLgSqCObTQ3idVn7-fi-1641_225719
- [x] Track all the quick actions behavior, including the modal to add/update values

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag Could you share the tracking event names and properties related to this issue please?

**Comment by mdperez86** [comment]
@jarekmorawski I was taking a look at [the endpoint ](https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-product-variation)we have to delete variations and it does not support trashing. So because of that I changed the menu item from `Trash` to `Delete` to avoid confusion. 
What to you think about? Should we use another label there or do you want me to keep the original one `Trash`?

**Comment by jarekmorawski** [comment]
No, `Delete` is fine. 👍 I've actually made the same change in Figma a few days ago. Thanks for bringing it up!

**Comment by AnnaMag** [comment]
@mdperez86 I will answer on the PR. Thanks for the ping!
