### ISSUE TITLE
Add multiselection to the Variations table under Variations tab

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#39791]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The users want to select one or many variations under `Variations` tab, so they can make quick editions to the selected ones

**Epic**

#35660

**ACs**

- [x] Add a checkbox to each variation row to select the current variation AkVNGImLgSqCObTQ3idVn7-fi-1761_322634
- [x] Add an indeterminate checkbox to the header of the variations table AkVNGImLgSqCObTQ3idVn7-fi-1761_323614
- [x] When at least one variation is selected the header checkbox should become indeterminate
- [x] When all variations are selected the header checkbox should be checked
- [x] If clicking the header checkbox when it is in indeterminate state then select all variation AkVNGImLgSqCObTQ3idVn7-fi-1810_253809
- [x] If clicking the header checkbox when it is checked then clear all the selected variations and the checkbox becomes unchecked
- [x] Add `Select all` and `Clear selection` buttons next to the header checkbox AkVNGImLgSqCObTQ3idVn7-fi-1761_250784
- [x] Disable the `Select all` button when all variations are selected AkVNGImLgSqCObTQ3idVn7-fi-1640_214140
- [x] Clicking the `Select all` button select all variations
- [ ] `Select all` button as well as the header checkbox select all the variations across all the pages
- [x] Disable the `Clear selection` button when non variation is selected
- [x] Clicking the `Clear selection` button deselect all variations

**Comment by mdperez86** [comment]
@jarekmorawski @pmcpinto @AnnaMag I know we talk about this already, but I just wanted to double check.
Checking the checkbox from the header of the variations table selects all the variations from the page 1 and from all other pages right? I mean, if we have 13 variations and a page size of 5, we should select the whole 13 items if we click the global checkbox right?

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag Could you share the tracking event names and properties related to this issue please?

**Comment by jarekmorawski** [comment]
> Checking the checkbox from the header of the variations table selects all the variations from the page 1 and from all other pages right? I mean, if we have 13 variations and a page size of 5, we should select the whole 13 items if we click the global checkbox right?

That's correct. The user should be able to see selected items while switching between pages.
