### ISSUE TITLE
[Woo AI] Add new Product Category automatically and refresh categories list.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#39800]
Within the product editor, clicking 'add new category' will fire an AJAX action named `add-product_cat` which will in turn send a request to the WooCommerce REST API to create a new category.
The return of this AJAX action is XML which makes it tricky to re-render the categories list within our React app.
For some inspiration, take a look at how the AJAX action works here:
https://github.com/woocommerce/woocommerce/blob/ffb38055a051d297620a1b9b4a6eda3c66c2827f/plugins/woocommerce-admin/client/wp-admin-scripts/product-category-metabox/category-add-new.tsx

**Comment by peterfabian** [comment]
@nima-karimi Has this been already done since the categories work has been shipped in version 0.4? If not relevant anymore, is it fine to close it? Thx!

**Comment by nima-karimi** [comment]
Yes, this is done. Closing the issue.
