### ISSUE TITLE
[Enhancement]: Variable product decrease character <2 please?

### ISSUE THREAD

**Issue by sanskritkm** [woothemes/woocommerce#39802]
### Describe the solution you'd like

<img width="760" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17005582/5458b56f-faf3-4695-b402-d8d9d7b734f4">

In above variable product could how could I decrease it lower to 2 characters? Ex: Brand -> LG?

**Comment by rrennick** [comment]
Hi @williamgh2019, Using your example you can type `LG ` (add a space). If it were a size with a single letter add two spaces. I'll close this as a question.

**Comment by sanskritkm** [comment]
It's working.
Thanks,
