### ISSUE TITLE
The Customer analytics screen shows the name as empty for guest customer

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#39813]
The `Customer` analytics screen is currently displaying the name as empty for guest customers, which is leading to confusion. To address this issue, we should add a pill with the text `Guest` under the `Name` column.

To reproduce:
1. Go to `WooCommerce` -> `Orders` -> `Add Order` -> `Create`.
2. Create an order with a `Guest` customer and status `Processing`.
3. Go to `WooCommerce` -> `Customers`.
4. Notice that a new, empty customer was added to the list.

![Screenshot 2023-08-18 at 16 17 22](https://github.com/woocommerce/woocommerce/assets/1314156/c393c056-9943-48a4-9cb3-5fadfcc546f5)

Design:
![customers](https://github.com/woocommerce/woocommerce/assets/1314156/8deea0f8-ee8c-4b50-80bc-741b4ed943c1)

**Comment by neilmccreadie** [comment]
6672953-zen
