### ISSUE TITLE
[Task | HPOS] Create order tables as standard

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#39826]
Stemming from [this discussion](https://github.com/woocommerce/woocommerce/pull/39682#discussion_r1291602474): with HPOS soon to be the new normal, we should create the new order tables as standard (ie, when WooCommerce is first installed, rather than conditionally).

**Comment by jorgeatorres** [comment]
I think this can be considered part of #33021, given we've already enabled HPOS for _new_ installs. Let me know if you feel otherwise @barryhughes!

**Comment by barryhughes** [comment]
I think that's fine, this is probably non-essential.

Part of my original thought was that it would just be easier to read if the table definitions were listed alongside all the other tables, rather than being [pulled in like this](https://github.com/woocommerce/woocommerce/blob/8.2.0-rc.2/plugins/woocommerce/includes/class-wc-install.php#L1215-L1220), but whether that would truly be an improvement or not is subjective.
