### ISSUE TITLE
Update the api-core-tests to be able to run locally with the `.env` file

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#39879]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
The `api-core-tests` should be able to be executed locally using a .env file to switch the environent as per the [Environment Variables](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests/api-core-tests#environment-variables) section in the readme.

More context https://github.com/woocommerce/woocommerce/pull/39858#issuecomment-1691345635

**Comment by adimoldovan** [comment]
This is obsolete, I will close it. The api core tests have since then been moved into the e2e project via https://github.com/woocommerce/woocommerce/pull/50024 and running them via the local .env file is now possible.
