### ISSUE TITLE
Components: Select Control dropdown styling issues.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#39875]
There are two issues with the component used for generating variations options.
The sizing of the dropdown has been reported in: https://github.com/woocommerce/woocommerce/pull/39770#discussion_r1297214785.

There is also an issue, likely related, of misplaced items when the length of those is greater then a single line:
![Image](https://user-images.githubusercontent.com/13561163/262790396-7f35230a-e23d-4226-800b-833290925c74.png)

**Comment by AnnaMag** [comment]
cc @mdperez86

**Comment by mdperez86** [comment]
Hey @AnnaMag do you have the design link or something to compare to see what is the issue I have to solve here

> There is also an issue, likely related, of misplaced items when the length of those is greater then a single line:

Or could you be more specific? Thanks

**Comment by AnnaMag** [comment]
@mdperez86  
Editing on the side of the main dropdown input field, with unlimited characters, seems off:

<img width="774" alt="Screenshot 2023-09-04 at 16 23 51" src="https://github.com/woocommerce/woocommerce/assets/13561163/07dcf912-acc0-47a1-a2fd-55a75ff0ddea">

Let's close https://github.com/woocommerce/woocommerce/pull/39989 and wait for @jarekmorawski to share his thoughts on ☝️
