### ISSUE TITLE
[E2E test coverage]: validate display of variations warning

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#39887]
Add E2E tests to ensure the proper display of a warning message under the `Pricing`, `Inventory`, and `Shipping` tabs after variations are created.

![Screenshot 2023-08-24 at 10 45 59](https://github.com/woocommerce/woocommerce/assets/1314156/ac271939-543e-418b-b210-0203e082c0f6)

The tests will cover the following scenarios:

- Checking if the variations warning is visible under the `Pricing` tab after creating variations.
- Checking if the variations warning is visible under the `Inventory` tab after creating variations.
- Checking if the variations warning is visible under the `Shipping` tab after creating variations.
- Verifying that the `Go to Variations` button correctly redirects to the variations section.

**Comment by nathanss** [comment]
Currently blocked, we need to either enable the variations feature flag or remove it before we're able to test this
