### ISSUE TITLE
[E2E test coverage]: create Variations

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#39886]
Add E2E tests that validate various aspects of the variation creation process.

The tests will specifically cover the following scenarios:

- Testing the feasibility of creating variations.
- Testing the capability to edit an attribute associated with a variation.
- Testing the functionality of hiding a variation.
- Testing the ability to delete a variation.
- Testing the ability to delete an attribute.

**Comment by nathanss** [comment]
We need to either remove the feature flag or add a plugin to enable it on tests before this issue is ready to develop.
