### ISSUE TITLE
Track individual plugin installation success/failure

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#39919]
We track the success of plugin installations through the `coreprofiler_store_extensions_installed_and_activated` track. However, we've realized that counting the number of successfully installed plugins is hard since we set an array to `installed_extensions` property.

To accurately track the success count of individual plugin installations, create a new track.

#### Acceptance Criteria

- Track individual plugin installation to `coreprofiler_store_extension_installed_and_activated`.

The track should have the following properties.

```
{
    success: boolean,
    installed_extension: string;
    install_time: string;
}
```

**Comment by chihsuan** [comment]
Hey @moon0326 Do we need to remove the existing track `coreprofiler_store_extensions_installed_and_activated`?
