### ISSUE TITLE
Update the CI checks that happen for documentation PRs

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#39920]
Now that we're working on making the [docs folder](https://github.com/woocommerce/woocommerce/tree/4dc745cc37e6fd77915d07834020bb35e97ec355/docs) the main location for storing technical documentation, it would be great if we could streamline the CI process for PRs that only affect the docs, and not any code. I'm not really sure what's possible with GitHub workflows, but I'm thinking something along the lines of:

1. If the PR changeset only includes Markdown files:
    * Skip unit tests and e2e tests
    * Only run the Markdown linter, not PHP or JS linters
2. Add something to the changelog form to indicate that this only updates docs. I know you can just mark it as a "patch" and add a comment instead of a message, but this might not be very intuitive to community contributors.

**Comment by barryhughes** [comment]
I may be wrong but, when the only changes are to the docs folder, I don't think the changelog requirements are enforced. [Example](https://github.com/woocommerce/woocommerce/pull/39849).

That said, we could make this clearer to contributors.

**Comment by coreymckrill** [comment]
Switching this to Solaris since it's focused on the monorepo.

**Comment by lanej0** [comment]
I looked at the latest PR I could find on the docs folder, and it looks like an appropriate set of checks are being run (no e2e/api/unit tests, markdown linting, changelog not required).  Going to close this for now.
