### ISSUE TITLE
Core Profiler - Create A/B test for MailChimp opt-in

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#39939]
Figma: Y5pUYSJPsGEud1vknUZhi8-fi-2695_12214

Related P2 comments: pdibGW-26P-p2#comment-1725 pdibGW-26P-p2#comment-1782

In the new core profiler, we've removed the email subscription checkbox. 

In order to send helpful information and tips to new customers, add a new checkbox and email address on the "Tell us a bit about your store" page to get an agreement. We'll run an A/B/C test.

### Control

No Change

### Variant A

Variant A has a pre-populated email input and checkbox. The email address is editable but can't be empty.

![th_a](https://github.com/woocommerce/woocommerce/assets/4723145/df4d846d-ab1f-49ab-a21e-eb9a189a2906)

#### Acceptance Criteria

- Add a pre-populated email input box and checkbox
- Checkbox is not checked by default. 

### Variant B

Variant B has only a checkbox.

![th_b](https://github.com/woocommerce/woocommerce/assets/4723145/9f7dbf95-1da8-4e41-a966-a374813f292a)

#### Acceptance Criteria

- Add a checkbox with the copy.
- The checkbox is not checked by default.

### Tracks (both variants A and B)

- % of users that change the email address on Variant A
- % of users that opt-in on Variant A vs. Variant B
- Dropoff

**Comment by rjchow** [comment]
Hey @verofasulo ! I was looking into this task and I realised there's an issue with variant B - for WC Core installations its quite likely that the merchant hasn't filled in an email address. There's a default that's provided which won't really be helpful:

![image](https://github.com/woocommerce/woocommerce/assets/27843274/beece466-1026-4c5c-83e4-e7608d943258)

I'm not sure its a workable option to not have an email field at all in the flow?

Edit:

Could possibly obtain the email at the point they log into Jetpack, but that's a few steps later and no guarantees that they will

**Comment by verofasulo** [comment]
Hey @rjchow 👋

Thanks for bringing this up! 

> I was looking into this task and I realised there's an issue with variant B - for WC Core installations its quite likely that the merchant hasn't filled in an email address. There's a default that's provided which won't really be helpful

@SamratBiswas1, could you please clarify? I was under the assumption that we always get the email address, and that's why we wanted to test this option too. Is there anyone from marketing that can help shed some light? cc @juliacallicrate 

Thanks!

**Comment by juliacallicrate** [comment]
@verofasulo @SamratBiswas1 From what I recall, we initially took out the marketing opt-in email (mainly because I thought the legal checkbox was going to cover both but then we never aligned on whether that was the case, in Figma). We looked at how much impact the marketing opt-in has through the OBW when we realized the gap. Initially, we thought it was <1% but then our Growth team said that this percentage was off and the OBW signups are a significant portion of our marketing signup list. I think last we chatted, I thought this would get implemented back in. So yes, we need an email in there 👍 

I realize that this discussion is beyond just the marketing opt-in but providing some of what I remember and the conversations we had :) Let me know if this helps at all.

**Comment by rjchow** [comment]
@verofasulo I was wondering if we have a misunderstanding here - for WC Core standalone installations they would not have gone through the NUX, and would not have a wpcom or jetpack account associated (at this point). 

I don't think they would have had any opportunity to provide an email address if they're seeing the core profiler, except in the niche case where they installed WC onto a existing WordPress installation that's been fully set up beforehand

**Comment by verofasulo** [comment]
Thanks, @juliacallicrate! 🙏 Appreciate you jumping in and adding some context 🌟

> I don't think they would have had any opportunity to provide an email address if they're seeing the core profiler, except in the niche case where they installed WC onto a existing WordPress installation that's been fully set up beforehand 

 Thanks, @rjchow! 💜 If this is not a real use case, I think we can skip the initial idea of having an A/B/C testing (control, email + checkbox, checkbox only) and go back to a more traditional A/B test that includes:

- Version A: control (no email address/marketing opt-in)
- Version B: experiment (marketing opt-in with email filed and checkbox)

@juliacallicrate @SamratBiswas1 are you okay with the above proposal?

**Comment by SamratBiswas1** [comment]
Yes! Let's implement what we had in the old profiler with A/B test proposed.

**Comment by rjchow** [comment]
I've implemented the feature, the next bit is to create the experiment but I realised I might need some input on the experiment parameters: https://github.com/woocommerce/team-ghidorah/issues/270

- Locale/Countries (I assume all?)
- Variation proportion: 50/50 ?
- Sample size
- Start/End dates (how long?)

**Comment by SamratBiswas1** [comment]
Hi @rjchow Let's not do an A/B test. We need to have the emails from the users for guiding them after onboarding and also targetign them about Woo Express (14 day trial, $1 promo). 
cc @verofasulo

**Comment by verofasulo** [comment]
> Let's not do an A/B test. We need to have the emails from the users for guiding them after onboarding and also targetign them about Woo Express (14 day trial, $1 promo).

@SamratBiswas1, I'm confused — This is not a Woo Express flow; it's the Core profiler. What am I missing?

**Comment by SamratBiswas1** [comment]
We are contemplating of targeting Woo Core users with Woo Express offers. Basically, target other hosts and get the users on dotcom hosting. For that we need their emails.

**Comment by verofasulo** [comment]
> We are contemplating of targeting Woo Core users with Woo Express offers. Basically, target other hosts and get the users on dotcom hosting. For that we need their emails.

Ha, interesting! Nonetheless, I would still run an a/b test—it's ready, and I think it's still important to know if and how this change affects our main onboarding flow.

**Comment by rjchow** [comment]
The code freeze is tomorrow so I'm going to merge the code that implements the experiment for now, so the experiment can run for any duration between 14 Nov (8.3 release) - 12 Dec (8.4 release). If we decide against it, then we can change it to 99/1 allocation, then remove the experiment in 8.4 with this decision being made before 22 Nov (8.4 code freeze).

**Comment by SamratBiswas1** [comment]
Let's go ahead and do the 50/50 test. It will good to know the impact of adding additional fields. Thanks!
