### ISSUE TITLE
Product summary block not formatted, after upgrading to WordPress 6.3

### ISSUE THREAD

**Issue by anastas10s-afk** [woothemes/woocommerce#39934]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Starting with WooCommerce 8.0.1, and WordPress 6.3, formatted copy in the product summary block (like bold or line breaks) are not rendered anymore on the front end. Works as expected when reverting to WordPress version 6.2.2.

The backend, with the short description field:
![Screenshot 2023-08-28 at 14 21 23](https://github.com/woocommerce/woocommerce/assets/73900974/42fd01b9-ae6a-4ccd-a6ec-ffb2d34c412c)

![Screenshot 2023-08-28 at 14 19 25](https://github.com/woocommerce/woocommerce/assets/73900974/444af125-0f93-41ab-9c27-a750382230e8)

Screenshot from the Editor, with TT3 active:
![Screenshot 2023-08-28 at 11 49 06](https://github.com/woocommerce/woocommerce/assets/73900974/b4ea09e5-ddc9-48bb-a34b-70cc3930df48)

With TT3 theme active, and WordPress 6.3:
![Screenshot 2023-08-28 at 14 19 39](https://github.com/woocommerce/woocommerce/assets/73900974/eee1d28b-f6de-4443-b958-ba3cfc79e2c9)

With TT3 theme active, and WordPress 6.2.2:
![Screenshot 2023-08-28 at 14 21 37](https://github.com/woocommerce/woocommerce/assets/73900974/45501c57-eba8-41e8-beda-3f64ded7690a)

With TT2 active:
![Screenshot 2023-08-28 at 14 25 08](https://github.com/woocommerce/woocommerce/assets/73900974/b44118e0-7ba6-4d6e-8993-219a09cf3175)

With Storefront active:
![Screenshot 2023-08-28 at 14 22 21](https://github.com/woocommerce/woocommerce/assets/73900974/9557267f-06d3-4fb4-963b-11c0e4e8ce78)

### Expected behavior

Expected behavior is for line breaks (`</br>`) and other formatting to render on the front end, as it happens when on WordPress version 6.2.2.

### Actual behavior

The copy formatting is lost, and not rendered in the front-end.

### Steps to reproduce

1. Start with a test setup having WordPress 6.2.2, the TT3 theme active, and WooCommerce installed.
2. Create a simple product, and include line breaks in its short description
3. See it rendering as expected
4. Now switch to WordPress version 6.3
5. Formatting is lost

### WordPress Environment

`
WordPress address (URL): https://...mystagingwebsite.com
Site address (URL): https://...mystagingwebsite.com
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.2.2 - There is a newer version of WordPress available (6.3)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.22
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 12.76MB
Database Data Size: 8.29MB
Database Index Size: 4.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.31MB + Index: 1.28MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.41MB + Index: 0.75MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.22MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 8
aw_workflow: 1
customize_changeset: 2
custom_css: 1
global_product_addon: 1
jp_pay_product: 3
nav_menu_item: 7
page: 17
post: 9
product: 26
product_variation: 66
revision: 44
shop_coupon: 1
shop_order: 12
shop_order_refund: 1
shop_subscription: 2
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Jetpack Protect: by Automattic - Jetpack Security team – 1.4.1
Jetpack: by Automattic – 12.5-beta
WooCommerce: by Automattic – 8.0.2

### Inactive Plugins (18) ###

AutomateWoo: by WooCommerce – 6.0.2
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.4
Code Snippets: by Code Snippets Pro – 3.4.2
Google Listings and Ads: by WooCommerce – 2.5.3
Price By Country: by HighAddons – 1.0.6
Storefront Powerpack: by WooCommerce – 1.6.2
WooCommerce Blocks: by Automattic – 10.9.3
WooCommerce Deposits: by WooCommerce – 2.1.7 (update to version 2.1.8 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.4
WooCommerce Payments: by Automattic – 6.3.2
WooCommerce Product Add-ons: by WooCommerce – 6.4.5
WooCommerce Product Bundles: by WooCommerce – 6.22.2
WooCommerce Shipping & Tax: by WooCommerce – 2.3.3
WooCommerce Square: by WooCommerce – 4.2.0
WooCommerce Stripe Gateway: by WooCommerce – 7.5.0
WooCommerce Subscriptions: by WooCommerce – 5.4.0
WooCommerce UPS Shipping: by WooCommerce – 3.5.3
WP Crontrol: by John Blackbourn & crontributors – 1.15.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-29 07:33:28 +00:00
Options: ✔
Notes: 40
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2023-08-07 09:28:11 +0000
Newest: 2023-08-07 09:28:11 +0000

Complete: 3,964
Oldest: 2023-07-31 09:18:29 +0000
Newest: 2023-08-28 11:19:28 +0000

Failed: 17
Oldest: 2023-06-08 10:06:57 +0000
Newest: 2023-08-25 12:38:54 +0000

Pending: 3
Oldest: 2023-08-29 03:00:00 +0000
Newest: 2023-10-18 14:29:39 +0000

### Status report information ###

Generated at: 2023-08-28 11:20:39 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Marc-pi** [comment]
same as https://github.com/woocommerce/woocommerce-blocks/issues/10653, that will bring you to https://github.com/WordPress/gutenberg/issues/15117

;-)

**Comment by CooperatusTeam** [comment]
This bug is frustrating us as well, we've had to roll back some sites to WP 6.2.x as a workaround.

**Comment by nerrad** [comment]
Thanks @Marc-pi for linking the issues. I can confirm this is definitely something that needs to be addressed in the WordPress core post-excerpt block.
