### ISSUE TITLE
Core profiler - Make MailChimp job for the core profiler

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#39940]
Related issue: https://github.com/woocommerce/woocommerce/issues/39939

Issue https://github.com/woocommerce/woocommerce/issues/39939 is adding MailChimp subscription opt-in checkbox.

We previously had a [MailchimpScheduler](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Schedulers/MailchimpScheduler.php) that subscribes customers to MailChimp when they're opted-in. We need to make sure the class works for the core profiler.

### Acceptance Criteria

- Change this [line](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Events.php#L159) to `core-profiler`
- Update  [MailchimpScheduler](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Schedulers/MailchimpScheduler.php) to make it work with the core profiler.

**Comment by rjchow** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/40869
