### ISSUE TITLE
[DOC-BUG] Broken link for PhpUnit test instructions

### ISSUE THREAD

**Issue by r-martins** [woothemes/woocommerce#39956]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.

https://developer.woocommerce.com/testing-extensions-and-maintaining-quality-code/test-runners-frameworks-and-libraries/#php-unit

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

The link to check out the [instructions](https://github.com/woocommerce/woocommerce/tree/trunk/tests#woocommerce-tests). is broken.

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

Because I'm struggling for days to create unit tests for a woocommerce plugin, and the available documentation is not helping. :(

## Additional Context

> Add any other context, references, or screenshots that support your suggestion.

<img width="931" alt="image" src="https://github.com/woocommerce/woocommerce/assets/191149/afc5c03b-1168-425a-b83f-f028d572eec6">

**Comment by ambikesh-cedcommerce** [comment]
Hi @r-martins , 
Here you can checkout my tutorial here https://github.com/ambikesh-cedcommerce/woocommerce-lint to manage WooCommerce plugin standard testing. 

Let me know If this help you to check the plugin standard. 

Thanks

**Comment by r-martins** [comment]
Thank you @ambikesh-cedcommerce. The instructions I was looking for go way beyond the code sniffing thing.
I was looking for how to perform unit tests, mocking objects and classes, etc. Specially how to mock woocommerce classes, i.e. creating a faking order for my phpunit tests.

I struggled a lot to realize that I would need to install a special version of wordpress, and also manually copy and paste a lot of folders here and there in order to make some classes available. I'm pretty sure I didn't it all right, but I hope they can provide a better tutorial and correct links some day.

Thanks for the article anyway.

**Comment by coreymckrill** [comment]
Thanks for the report @r-martins. This should be fixed now, the correct link is:

https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#woocommerce-tests
