### ISSUE TITLE
[Enhancement]: Persist progmatically added fees in WC_Cart

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#39960]
### Describe the solution you'd like

I have just had an issue where I progmatically added a fee on the Cart page.  The fee did not appear on the checkout page and I could not understand why.  It took me a while to realise I add to add the fee on the checkout page as well.  I think it would make more sense for the WC_Cart class to persist the fee on to the checkout page.

### Describe alternatives you've considered

I currently have to add the fee on the checkout page as well as the cart page.

**Comment by mikejolley** [comment]
Thanks for this feedback. 

This is only documented inline where `woocommerce_cart_calculate_fees` hook is recommended, and its stated that fees do not persist. Fees should be added anytime the `woocommerce_cart_calculate_fees` hook runs. 

[I couldn't find public facing docs, but I did however find some snippets.](https://woocommerce.com/document/add-a-surcharge-to-cart-and-checkout-uses-fees-api/?quid=0cd5cfe901b3cbefad38c4dd09098a92)

I think it would be problematic at this point to make fees persist, and potentially dangerous to hold these in session with no underlying data object behind them. It could result in fees being added with no way to remove them.

I understand this lacks proper documentation so I've put in a report to have this updated on the docs site, so thanks for the report. I will mark this issue closed.
