### ISSUE TITLE
Error with empty transient used as an array

### ISSUE THREAD

**Issue by timotheemoulin** [woothemes/woocommerce#39997]
https://github.com/woocommerce/woocommerce/blob/6e608ec4187b6c8106ceab506ffe8beaccb99e1a/plugins/woocommerce/src/Admin/DataSourcePoller.php#L136

[From the doc](https://developer.wordpress.org/reference/functions/get_transient/#description)
> If the transient does not exist, does not have a value, or has expired, then the return value will be false.

False is considered as a defined value, so `??` will not set a default value in this case which leads to a notice on the next line when trying to access `$specs_group[ $locale ]` as it tries to access `false[ $locale ]`.

Can we switch to `$specs_group = get_transient( $this->args['transient_name'] ) ?: array();` which checks for an empty value instead?

**Comment by rrennick** [comment]
@timotheemoulin Thanks for reporting the issue. It was already reported in #39708. Closing this as a duplicate.
