### ISSUE TITLE
activate hpos create an database error 1000byte exeeded

### ISSUE THREAD

**Issue by Avatarsia** [woothemes/woocommerce#39990]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

CREATE TABLE wp_wc_orders_meta ( id bigint(20) unsigned auto_increment primary key, order_id bigint(20) unsigned null, meta_key varchar(255), meta_value text null, KEY meta_key_value (meta_key, meta_value(100)), KEY order_id_meta_key_meta_value (order_id, meta_key, meta_value(100)) ) DEFAULT CHARACTER
SET utf8

Specified key was too long; max key length is 1000 bytes

Automattic\W\I\U\DatabaseUtil->dbdelta()
wp-content/plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php:26
Automattic\W\I\D\O\DataSynchronizer->create_database_tables()
wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/DataSynchronizer.php:157
Automattic\W\I\D\O\CustomOrdersTableController->handle_data_sync_option_changed()
wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:368
Automattic\W\I\D\O\CustomOrdersTableController->__call()
wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php:158
do_action('woocommerce_feature_enabled_changed')
wp-includes/plugin.php:517
Automattic\W\I\F\FeaturesController->process_updated_option()
wp-content/plugins/woocommerce/src/Internal/Features/FeaturesController.php:532
Automattic\W\I\F\FeaturesController->__call()
wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php:158
do_action('updated_option')
wp-includes/plugin.php:517
update_option()
wp-includes/option.php:592
WC_Admin_Settings::save_fields()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php:934
WC_Settings_Page->save_settings_for_current_section()
wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php:233
WC_Settings_Advanced->save()
wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-advanced.php:478
do_action('woocommerce_settings_save_advanced')
wp-includes/plugin.php:517
WC_Admin_Settings::save()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php:77
WC_Admin_Menus->save_settings()
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php:151
do_action('wp_loaded')
wp-includes/plugin.php:517

### Expected behavior

so far i understand it should create the database for hops

### Actual behavior

it wont create the database 
'*.wp_wc_orders_meta' doesn't exist

### Steps to reproduce

activate "Keep the posts and orders tables in sync (compatibility mode)." (hpos is greyed out)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://partner-3d.de
Site address (URL): https://partner-3d.de
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.22
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.14-MariaDB-cll-lve-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 332.64MB
Database Data Size: 279.60MB
Database Index Size: 53.04MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 5.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_actions: Data: 0.47MB + Index: 0.63MB + Engine InnoDB
wpstg0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_logs: Data: 8.52MB + Index: 4.03MB + Engine InnoDB
wpstg0_apcm_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg0_commentmeta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_options: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wpstg0_p3dlite_coatings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_p3dlite_infills: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg0_p3dlite_materials: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_p3dlite_price_requests: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpstg0_p3dlite_printers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_postmeta: Data: 63.52MB + Index: 10.03MB + Engine InnoDB
wpstg0_posts: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wpstg0_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rank_math_analytics_adsense: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rank_math_analytics_ga: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rank_math_internal_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpstg0_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_usermeta: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_product_lookup: Data: 0.28MB + Index: 0.30MB + Engine InnoDB
wpstg0_wc_order_tax_lookup: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpstg0_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg0_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wpstg0_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 1.73MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 28.06MB + Index: 17.38MB + Engine InnoDB
wp_apcm_details: Data: 0.26MB + Index: 0.14MB + Engine MyISAM
wp_apcm_statistics: Data: 0.26MB + Index: 0.06MB + Engine MyISAM
wp_borlabs_cookie_consent_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_content_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_borlabs_cookie_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_script_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_statistics: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_comments: Data: 3.52MB + Index: 1.44MB + Engine InnoDB
wp_email_log: Data: 0.30MB + Index: 0.00MB + Engine MyISAM
wp_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_budget_recommendations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
wp_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.39MB + Index: 0.16MB + Engine InnoDB
wp_p3dlite_coatings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_p3dlite_infills: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_p3dlite_materials: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_p3dlite_price_requests: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_p3dlite_printers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 62.52MB + Index: 7.03MB + Engine InnoDB
wp_posts: Data: 2.45MB + Index: 0.47MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_adsense: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stock_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_swift3_warmup: Data: 0.08MB + Index: 0.07MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.27MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_stats: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 88.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

advgb_profiles: 1
attachment: 156
custom_css: 2
e-landing-page: 1
elementor_library: 1
nav_menu_item: 18
page: 38
post: 6
product: 101
product_variation: 49
revision: 118
shop_coupon: 2
shop_order: 1680
shop_order_refund: 25
user_request: 1
wp_block: 3
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 4
wphtmlmail_mail: 26
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Query Monitor: by John Blackbourn – 3.13.1
3DPrint Lite: by Sergey Burkov – 2.0.3.4
PublishPress Blocks: by PublishPress – 3.1.6
APCu Manager: by Pierre Lannoy / PerfOps One – 3.6.0
Atomion WooCommerce Blocks: by MarketPress – 1.0.13
Borlabs Cookie - Cookie Opt-in: by Borlabs GmbH – 2.2.66
Contact Form 7: by Takayuki Miyoshi – 5.8
Custom Layouts - Post + Product grids made easy: by Code Amp – 1.4.9
DHL Shipping Germany for WooCommerce: by DHL – 3.5.4
Email Log: by Sudar – 2.4.8
Rank Math SEO: by Rank Math – 1.0.122
Simple Image Sizes: by Rahe – 3.2.2
Swift Performance AI: by SWTE – 0.5.8
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.5.7
NextMove Lite - Thank You Page for WooCommerce: by XLPlugins – 2.17.0
German Market: by MarketPress – 3.27
Stock Manager for WooCommerce: by StoreApps – 3.0.0
WooCommerce: by Automattic – 8.0.3
Backup Duplicator & Migration - WP STAGING: by WP-STAGING
WPStagingBackup – 3.0.3

### Inactive Plugins (2) ###

Lightbox with PhotoSwipe: by Arno Welzel – 5.0.43
Product Questions & Answers for WooCommerce: by ExpressTech Software Solutions Pvt. Ltd. – 1.2.2

### Dropin Plugins (3) ###

db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: APCu Objects Cache Handler

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #2557 - /shop/
Cart: #2558 - /warenkorb/
Checkout: #2559 - /kasse/
My account: #2560 - /mein-konto/
Terms and conditions: #15 - /allgemeine_geschaeftsbedingungen/

### Theme ###

Name: WordPress Child Theme Atomion
Version: 1.0
Author URL: https://marketpress.de
Child Theme: ✔
Parent Theme Name: WordPress Theme Atomion
Parent Theme Version: 1.3.13
Parent Theme Author URL: https://marketpress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: wordpress-theme-atomion/woocommerce/archive-product.php
wordpress-theme-atomion/woocommerce/cart/cart-shipping.php
wordpress-theme-atomion/woocommerce/cart/cart.php
wordpress-theme-atomion/woocommerce/cart/cross-sells.php
wordpress-theme-atomion/woocommerce/cart/mini-cart.php
wordpress-theme-atomion/woocommerce/checkout/review-order.php
wordpress-theme-atomion/woocommerce/checkout/thankyou.php
wordpress-theme-atomion/woocommerce/content-product.php
wordpress-theme-atomion/woocommerce/global/breadcrumb.php
wordpress-theme-atomion/woocommerce/global/wrapper-end.php
wordpress-theme-atomion/woocommerce/global/wrapper-start.php
wordpress-theme-atomion/woocommerce/loop/loop-start.php
wordpress-theme-atomion/woocommerce/myaccount/form-edit-account.php
wordpress-theme-atomion/woocommerce/myaccount/form-login.php
wordpress-theme-atomion/woocommerce/myaccount/my-address.php
wordpress-theme-atomion/woocommerce/myaccount/navigation.php
wordpress-theme-atomion/woocommerce/myaccount/orders.php
wordpress-theme-atomion/woocommerce/myaccount/view-order.php
wordpress-theme-atomion/woocommerce/product-searchform.php
wordpress-theme-atomion/woocommerce/single-product/meta.php
wordpress-theme-atomion/woocommerce/single-product/product-attributes.php
wordpress-theme-atomion/woocommerce/single-product/related.php
wordpress-theme-atomion/woocommerce/single-product/review-meta.php
wordpress-theme-atomion/woocommerce/single-product/review.php
wordpress-theme-atomion/woocommerce/single-product/tabs/additional-information.php
wordpress-theme-atomion/woocommerce/single-product/tabs/description.php
wordpress-theme-atomion/woocommerce/single-product/tabs/tabs.php
wordpress-theme-atomion/woocommerce/single-product/up-sells.php
wordpress-theme-atomion/woocommerce/single-product-reviews.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-01 15:15:26 +02:00
Options: ✔
Notes: 27
Onboarding: completed

### Action Scheduler ###

Complete: 4,728
Oldest: 2023-08-31 06:51:33 +0000
Newest: 2023-08-31 16:08:29 +0000

Pending: 2
Oldest: 2023-08-31 20:54:03 +0000
Newest: 2023-09-01 03:39:15 +0000

### Status report information ###

Generated at: 2023-08-31 18:13:46 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
- Expected to be solved by https://github.com/woocommerce/woocommerce/pull/39250 
- Fix should be available in WooCommerce 8.1, provisionally scheduled for release on 2023-09-12.
