### ISSUE TITLE
[E2E test coverage]: Create a new Playwright project for the new experience

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#40009]
Separate the legacy and the new product experiences into two different Playwright projects.

Currently, our E2E tests are all within a single project. We need to have a second project to only run the new product editor tests. The second project will depend on the first one (the one with the rest of the E2E tests) using [Playwright project dependencies](https://playwright.dev/docs/test-projects#dependencies).

This ensures the two experiences won't run in parallel in CI. Also, this approach could be a good precedent for upcoming experimental features.

**Comment by louwie17** [comment]
We talked about this a bit more yesterday, and discussed the possibility of creating a separate GH action for just running the product editor E2E tests.
This way we can run them as multiple workers and we avoid conflicts.

**Comment by louwie17** [comment]
Closing this given the feedback on this PR https://github.com/woocommerce/woocommerce/pull/41601, as we don't need this anymore because the issue that this was suppose to solve is not present anymore.
