### ISSUE TITLE
[SPIKE] Woo AI - Look up ways to test our prompts for regressions + improvements.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#40000]
There appears to be a couple of options:

https://github.com/mshumer/gpt-prompt-engineer
https://github.com/promptfoo/promptfoo

**Comment by joelclimbsthings** [comment]
From peGwbA-Ya-p2:
> David was suggesting we vectorize outputs and write integration tests that compare output to previous vectorized ones and detect the drift. I love this idea

This might be a good way to track any dramatic changes to our prompt outputs^

**Comment by peterfabian** [comment]
The desired output of this is probably an RFC with a proposal of the most reasonable approach.

**Comment by nima-karimi** [comment]
P2 published: pf8sIm-9O-p2
