### ISSUE TITLE
Storybook build command isn't working

### ISSUE THREAD

**Issue by andfinally** [woothemes/woocommerce#40005]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I found these two commands for building and running Storybook in a [PR](https://github.com/woocommerce/woocommerce/pull/36517):

```bash
# Build storybook
 
pnpm --filter=@woocommerce/storybook build-storybook
 
# Run storybook
 
pnpm --filter=@woocommerce/storybook storybook
```

The run command works fine, but the build command doesn't complete.

### Expected behavior

Build command completes, and newly added components appear in Storybook when you use the run command.

### Actual behavior

Build command fails. Judging by these errors, the build can't find `@wordpress/element` or `guided-tours/variable-product-tour`: 

```
92% sealing asset processing copy-webpack-plugininfo => Manager built (15 s)
ERR! => Failed to build the preview
ERR! TS2307: Cannot find module '@wordpress/element' or its corresponding type declarations.
ERR!     2 |  * External dependencies
ERR!     3 |  */
ERR!   > 4 | import { render } from '@wordpress/element';
ERR!       |                        ^^^^^^^^^^^^^^^^^^^^
ERR!     5 |
ERR!     6 | /**
ERR!     7 |  * Internal dependencies
ERR! TS2307: Cannot find module '../../guided-tours/variable-product-tour' or its corresponding type declarations.
ERR!      7 |  * Internal dependencies
ERR!      8 |  */
ERR!   >  9 | import { VariableProductTour } from '../../guided-tours/variable-product-tour';
ERR!        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERR!     10 |
ERR!     11 | const root = document.createElement( 'div' );
ERR!     12 | root.setAttribute( 'id', 'variable-product-tour-root' );
ERR! TS2307: Cannot find module '@wordpress/element' or its corresponding type declarations.
ERR!     2 |  * External dependencies
ERR!     3 |  */
ERR!   > 4 | import { render } from '@wordpress/element';
ERR!       |                        ^^^^^^^^^^^^^^^^^^^^
ERR!     5 |
ERR!     6 | /**
ERR!     7 |  * Internal dependencies
ERR! TS2307: Cannot find module '../../guided-tours/wc-addons-tour/index' or its corresponding type declarations.
ERR!      7 |  * Internal dependencies
ERR!      8 |  */
ERR!   >  9 | import WCAddonsTour from '../../guided-tours/wc-addons-tour/index';
ERR!        |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERR!     10 |
ERR!     11 | const root = document.createElement( 'div' );
ERR!     12 | root.setAttribute( 'id', 'wc-addons-tour-root' );

// etc. 

 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @woocommerce/storybook@ build-storybook: `build-storybook  -c ./.storybook`
Exit status 1
```

### Steps to reproduce

1. Set up your WooCommerce local project following the instructions in the [README](https://github.com/woocommerce/woocommerce/#getting-started).
2. From the project root, run the build command `pnpm --filter=@woocommerce/storybook build-storybook`.
3. Note the results.

### WordPress Environment

wp-env in my local WooCommerce environment

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kdevnel** [comment]
I can confirm I saw the same behaviour and can use the run command but not the build command.
