### ISSUE TITLE
Woocommerce "List all Categories" encoding ampersand in category name

### ISSUE THREAD

**Issue by AumCoin** [woothemes/woocommerce#40029]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

_(possibly related to 2 other issues: https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+is%3Aopen+ampersand)_

-----------------

I make a GET request to retrieve all categories as described at https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories.  I have a category called "Axis & Allies" but I get back this category object with the name encoded:

`=> {"id"=>51, "name"=>"Axis &amp; Allies", "slug"=>"axis-allies", "parent"=>0, "description"=>"", "display"=>"default", "image"=>nil, "menu_order"=>0, "count"=>0, "_links"=>{"self"=>[{"href"=>"https://example.com/wp-json/wc/v3/products/categories/51"}], "collection"=>[{"href"=>"https://example.com/wp-json/wc/v3/products/categories"}]}}`

### Expected behavior

I expect the API to return the same category names as were in the original POST data from which the categories were created, meaning that the ampersand should not be encoded.

### Actual behavior

The name I receive back is not the same as what I posted.  `Axis & Allies` is being returned as `Axis &amp; Allies`, which is not correct.

### Steps to reproduce

1. Upload a category with an ampersand in the name via the WC API.
2. Retrieve a list of all categories via the WC API.
3. The ampersand has been encoded
------------------------

**Steps to Reproduce in Ruby:**

```
require "json"
require 'net/http'
require 'uri'

# CREATE THE CATEGORIES
uri = URI.parse("https://example.com/wp-json/wc/v3/products/categories/batch")
request = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
request.basic_auth(WC_KEY, WC_SECRET)
request.body = {"create"=>[{"name"=>"Akora TCG"}, {"name"=>"Alternate Souls"}, {"name"=>"Architect TCG"}, {"name"=>"Argent Saga TCG"}, {"name"=>"Axis & Allies"}, {"name"=>"Bakugan TCG"}, {"name"=>"Battle Spirits Saga"}, {"name"=>"Boardgames"}, {"name"=>"Books"}, {"name"=>"Bulk Lots"}, {"name"=>"Card Sleeves"}]}.to_json

response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https") do |http|
    http.request(request)
end

# RETRIEVE THE CATEGORIES
uri = URI.parse("https://example.com/wp-json/wc/v3/products/categories")
request = Net::HTTP::Get.new(uri)
request.basic_auth(WC_KEY, WC_SECRET)
response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https") do |http|
    http.request(request)
end
```

```
 "[{\"id\":47,\"name\":\"Akora TCG\",\"slug\":\"akora-tcg\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/47\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":48,\"name\":\"Alternate Souls\",\"slug\":\"alternate-souls\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/48\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":49,\"name\":\"Architect TCG\",\"slug\":\"architect-tcg\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/49\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":50,\"name\":\"Argent Saga TCG\",\"slug\":\"argent-saga-tcg\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/50\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":51,\"name\":\"Axis &amp; Allies\",\"slug\":\"axis-allies\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/51\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":52,\"name\":\"Bakugan TCG\",\"slug\":\"bakugan-tcg\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/52\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":53,\"name\":\"Battle Spirits Saga\",\"slug\":\"battle-spirits-saga\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/53\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":54,\"name\":\"Boardgames\",\"slug\":\"boardgames\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/54\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":55,\"name\":\"Books\",\"slug\":\"books\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/55\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}},{\"id\":56,\"name\":\"Bulk Lots\",\"slug\":\"bulk-lots\",\"parent\":0,\"description\":\"\",\"display\":\"default\",\"image\":null,\"menu_order\":0,\"count\":0,\"_links\":{\"self\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\\/56\"}],\"collection\":[{\"href\":\"https:\\/\\/example.com\\/wp-json\\/wc\\/v3\\/products\\/categories\"}]}}]"
irb(main):198:0>
```

Note that the encoded JSON being posted is this (without an encoded ampersand):
```
"{\"create\":[{\"name\":\"Akora TCG\"},{\"name\":\"Alternate Souls\"},{\"name\":\"Architect TCG\"},{\"name\":\"Argent Saga TCG\"},{\"name\":\"Axis & Allies\"},{\"name\":\"Bakugan TCG\"},{\"name\":\"Battle Spirits Saga\"},{\"name\":\"Boardgames\"},{\"name\":\"Books\"},{\"name\":\"Bulk Lots\"},{\"name\":\"Card Sleeves\"}]}"
```
Note also that the category displays correctly in the WP Admin UI.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://example.com
Site address (URL): http://example.com
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Debian)
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.5.19-MariaDB-0+deb11u2
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_example
Total Database Size: 6.74MB
Database Data Size: 5.27MB
Database Index Size: 1.47MB
wp_examplewoocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_examplewoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_examplewoocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewoocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_examplewoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_examplewoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_examplewoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_exampleactionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_exampleactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_exampleactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_exampleactionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_examplecommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplecomments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_examplelinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_exampleoptions: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
wp_examplepostmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_exampleposts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_exampletermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_exampleterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_exampleterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_exampleterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_exampleusermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_exampleusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_examplewc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_examplewc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_examplewc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_examplewc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_examplewc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_examplewc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_examplewc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_examplewc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_examplewc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_examplewc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 13
custom_css: 1
customize_changeset: 7
page: 9
post: 3
product: 4
revision: 10
wp_global_styles: 1
wp_navigation: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Jetpack: by Automattic – 12.1.1
Change Storefront Footer Copyright Text: by QuadLayers – 2.0.7
WooCommerce Payments: by Automattic – 5.9.2 (update to version 6.4.0 is available)
WooCommerce PayPal Payments: by WooCommerce – 2.0.4 (update to version 2.2.2 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5 (update to version 2.3.3 is available)
WooCommerce: by Automattic – 7.7.0 (update to version 8.0.3 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.3.0 (update to version 4.5.2 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://example.com
Subscriptions-core Library Version: 5.7.2
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-09-06 01:44:01 +00:00
Options: ✔
Notes: 109
Onboarding: completed

### WooCommerce Payments ###

Version: 5.9.2
Connected to WPCOM: Yes
Blog ID: 219365816
Account ID: acct_1NB7N6CBJkqIV529

### Action Scheduler ###

Complete: 87
Oldest: 2023-08-05 11:38:32 +0000
Newest: 2023-09-05 03:37:09 +0000

Failed: 1
Oldest: 2023-05-24 02:19:00 +0000
Newest: 2023-05-24 02:19:00 +0000

Pending: 1
Oldest: 2023-09-05 13:22:57 +0000
Newest: 2023-09-05 13:22:57 +0000

### Status report information ###

Generated at: 2023-09-05 04:23:19 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
This is actually due to a longstanding issue in WordPress core: https://core.trac.wordpress.org/ticket/11311

WooCommerce isn't doing anything special here, it's just how WP Core stores and returns ampersands in certain contexts. This happens with post category names too (and a bunch of other places, if you look at the core ticket).

I can see how this isn't great, but it's an issue that should get fixed upstream, rather than in WooCommerce.
