### ISSUE TITLE
[Product Block Editor] Calendar styling when scheduling sales.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#40041]
Enable the new editor and try to schedule a sale under the Inventory tab when creating/editing a product.

![Image](https://user-images.githubusercontent.com/13561163/265693812-c20e50f0-85b0-4634-bb27-2fa3eb510f32.png)

- Enable the new editor 
- go to `wp-admin/admin.php?page=wc-admin&path=%2Fadd-product&tab=pricing`
- add list and sales price, and enable the Schedule sale toggle
<img width="628" alt="Screenshot 2023-11-13 at 18 51 52" src="https://github.com/woocommerce/woocommerce/assets/13561163/00b48ff0-f611-4374-9c7b-98568ff45cf1">

- verify the design of the Calendar 

Reported for Chrome.
Works well on FF.

**Comment by retrofox** [comment]
I'm not able to reproduce the issue. Let's close for now

https://github.com/woocommerce/woocommerce/assets/77539/da7b6d59-2df7-47b9-bd0d-37de2421d8d5
