### ISSUE TITLE
Error: Don't permission to delete a category.

### ISSUE THREAD

**Issue by wkeane25** [woothemes/woocommerce#40056]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On my products page, I have one category that I am unable to update or remove. The category is Aromatherapy. When I try to update the category wordpress puts a message at the top of the screen stating "Sorry, you can't do that". When I try to delete the category I am brought to a new page that reads "You don't have a the level of permission to do that". I am the only admin on the site. 

### Expected behavior

I should have the access to perform any edits on my site. 

### Actual behavior

When I try to update the category wordpress puts a message at the top of the screen stating "Sorry, you can't do that". When I try to delete the category I am brought to a new page that reads "You don't have a the level of permission to do that". 

### Steps to reproduce

<img width="1440" alt="Screen Shot 2023-09-05 at 3 51 00 PM" src="https://github.com/woocommerce/woocommerce/assets/144260436/1f3d9995-d049-4a19-8068-792f551abcae">
![Image 9-1-23 at 10 56 AM](https://github.com/woocommerce/woocommerce/assets/144260436/129bb4fe-f547-4dc3-9fe8-3de0a76849ec)
![Image 8-31-23 at 2 21 PM](https://github.com/woocommerce/woocommerce/assets/144260436/7e809388-7fa4-4a62-9303-8466378c9707)
![Image 8-31-23 at 2 21 PM](https://github.com/woocommerce/woocommerce/assets/144260436/2d04857b-f04b-4304-a02c-7a396b876f8b)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://vibrantlivingpicks.com
Site address (URL): https://vibrantlivingpicks.com
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.9
PHP Post Max Size: 516 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 8.2.1
OpenSSL/1.1.1v

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: 8t3_
Total Database Size: 163.22MB
Database Data Size: 126.33MB
Database Index Size: 36.89MB
8t3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_woocommerce_attribute_taxonomies: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
8t3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
8t3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
8t3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_actionscheduler_actions: Data: 0.30MB + Index: 0.41MB + Engine InnoDB
8t3_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_actionscheduler_logs: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
8t3_amz_amazon_cache: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
8t3_amz_amzkeys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
8t3_amz_assets: Data: 12.41MB + Index: 0.67MB + Engine MyISAM
8t3_amz_cross_sell: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
8t3_amz_import_stats: Data: 7.52MB + Index: 0.92MB + Engine InnoDB
8t3_amz_locale_reference: Data: 0.18MB + Index: 0.06MB + Engine MyISAM
8t3_amz_products: Data: 0.45MB + Index: 0.29MB + Engine MyISAM
8t3_amz_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
8t3_amz_report_log: Data: 0.94MB + Index: 0.00MB + Engine MyISAM
8t3_amz_search: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
8t3_amz_sync_widget: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
8t3_amz_sync_widget_asins: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
8t3_automatic_amazon_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_articles_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_articles_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_cached: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_automatic_camps: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
8t3_automatic_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_automatic_clickbank_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_general: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_keywords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_automatic_log: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
8t3_automatic_youtube_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_cegg_autoblog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_cegg_price_alert: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_cegg_price_history: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
8t3_cegg_product: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
8t3_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_options: Data: 3.27MB + Index: 0.13MB + Engine InnoDB
8t3_postmeta: Data: 71.59MB + Index: 13.47MB + Engine InnoDB
8t3_posts: Data: 19.45MB + Index: 8.84MB + Engine InnoDB
8t3_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_sliders_bkp: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_slides: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_slides_bkp: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_sfba_subscribers_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_sfba_subscription_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_termmeta: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
8t3_terms: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
8t3_term_relationships: Data: 1.34MB + Index: 1.34MB + Engine InnoDB
8t3_term_taxonomy: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
8t3_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
8t3_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
8t3_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
8t3_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
8t3_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
8t3_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
8t3_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
8t3_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
8t3_wc_product_attributes_lookup: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
8t3_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_wc_product_meta_lookup: Data: 0.22MB + Index: 0.42MB + Engine InnoDB
8t3_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
8t3_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
8t3_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 14002
custom_css: 1
elementor_library: 2
nav_menu_item: 56
page: 12
post: 27
product: 1908
revision: 1
sfba_subscribe_form: 1
shortcoder: 1
wp_automatic: 4
wp_block: 10
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Ad Inserter: by Igor Funa – 2.7.30
Classic Editor: by WordPress Contributors – 1.6.3
Elementor: by Elementor.com – 3.15.3
Site Kit by Google: by Google – 1.108.0
REHub Framework: by Wpsoul – 18.7
Slider Revolution: by ThemePunch – 6.6.15
Shortcoder: by Aakash Chakravarthy – 6.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.4
WooCommerce: by Automattic – 8.0.2 (update to version 8.0.3 is available)
WZone - WooCommerce Amazon Affiliates: by AA-Team – 14.0.6
Wordpress Automatic Plugin: by ValvePress – 3.54.2
WP Rocket: by WP Media – 3.8.8
Subscribe Forms: by Premio – 1.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.2
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Rehub theme
Version: 19.0.5
Author URL: https://wpsoul.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: rehub-theme/woocommerce/archive-product.php
rehub-theme/woocommerce/cart/cross-sells.php
rehub-theme/woocommerce/content-product.php
rehub-theme/woocommerce/global/wrapper-end.php
rehub-theme/woocommerce/global/wrapper-start.php
rehub-theme/woocommerce/loop/add-to-cart.php
rehub-theme/woocommerce/loop/loop-end.php
rehub-theme/woocommerce/loop/loop-start.php
rehub-theme/woocommerce/loop/rating.php
rehub-theme/woocommerce/loop/sale-flash.php
rehub-theme/woocommerce/myaccount/my-account.php
rehub-theme/woocommerce/product-searchform.php
rehub-theme/woocommerce/single-product/add-to-cart/external.php
rehub-theme/woocommerce/single-product/meta.php
rehub-theme/woocommerce/single-product/product-image.php
rehub-theme/woocommerce/single-product/sale-flash.php
rehub-theme/woocommerce/single-product/share.php
rehub-theme/woocommerce/single-product/tabs/additional-information.php
rehub-theme/woocommerce/single-product/tabs/description.php
rehub-theme/woocommerce/single-product-reviews.php
rehub-theme/woocommerce/single-product.php
rehub-theme/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-07 09:16:53 +00:00
Options: ✔
Notes: 77
Onboarding: completed

### Action Scheduler ###

Complete: 866
Oldest: 2023-08-27 08:35:55 +0000
Newest: 2023-09-06 15:50:17 +0000

Failed: 4
Oldest: 2023-03-19 08:52:49 +0000
Newest: 2023-08-27 09:15:50 +0000

Pending: 1
Oldest: 2023-09-07 15:50:17 +0000
Newest: 2023-09-07 15:50:17 +0000

### Status report information ###

Generated at: 2023-09-06 16:04:10 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
> - [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> - [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
> - [ ] I can reproduce this bug consistently using the steps above.

You didn't initially populate these fields, but this isn't something I can replicate, and I'm curious if it is in fact the result of a conflict of some kind—with your theme or with another plugin.

Can you confirm?
