### ISSUE TITLE
Check for empty value in get_order_id_by_order_key()

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#40055]
See C0E1AV8T0-slack-p1693994820601269

I was looking into slow backend issues for a friend, and noticed the following query stuck in server:

> SELECT post_id FROM wp_postmeta WHERE meta_key = '_order_key' AND meta_value = ''

I noticed a 3PD plugin wasn't checking for empty order key value before calling `wc_get_order_id_by_order_key()` which likely resulted in a slow query and made the site unresponsive. The site's postmeta table is considerably large.

https://github.com/woocommerce/woocommerce/blob/5a8ed71edc380ac755e1d7e65335897023d01e15/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L449

While plugins should always be careful about this, I am just opening this issue to see if we can do a check before firing the SQL.

Or did I miss anything? Is the empty value already checked in core somewhere?

**Comment by ambikesh-cedcommerce** [comment]
Hi @kaushikasomaiya ,
I'm not sure if this will help you, but I have looked into your query in depth. Please correct me if I'm wrong. If you look closely at that function, the values are already required to get the order ID using the order key so you can't pass empty value. Or you can try the get_posts() function to get the post with the help of the meta key. You can see an example here: [Using get_posts with arguments found in meta keys]. [https://wordpress.stackexchange.com/questions/30970/using-get-posts-with-arguments-found-in-meta-keys](here)

**Comment by kaushikasomaiya** [comment]
@ambikesh-cedcommerce Thanks for your input.

The function can be used directly: `wc_get_order_id_by_order_key('wc_order_cAiGIVS0kb7nk')` and the key here can be dynamic and empty sometimes if plugins are poorly coded.

**Comment by masteradhoc** [comment]
@kaushikasomaiya @ambikesh-cedcommerce I made a PR for your issue. Please check if you can :)
