### ISSUE TITLE
HPOS - Unable to add custom order bulk actions

### ISSUE THREAD

**Issue by vaclavgreif** [woothemes/woocommerce#40054]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There's no filter available to add custom bulk actions to the orders screen with HPOS enabled:

```
protected function get_bulk_actions() {
		$selected_status = $this->order_query_args['status'] ?? false;

		if ( array( 'trash' ) === $selected_status ) {
			$actions = array(
				'untrash' => __( 'Restore', 'woocommerce' ),
				'delete'  => __( 'Delete permanently', 'woocommerce' ),
			);
		} else {
			$actions = array(
				'mark_processing' => __( 'Change status to processing', 'woocommerce' ),
				'mark_on-hold'    => __( 'Change status to on-hold', 'woocommerce' ),
				'mark_completed'  => __( 'Change status to completed', 'woocommerce' ),
				'mark_cancelled'  => __( 'Change status to cancelled', 'woocommerce' ),
				'trash'           => __( 'Move to Trash', 'woocommerce' ),
			);
		}

		if ( wc_string_to_bool( get_option( 'woocommerce_allow_bulk_remove_personal_data', 'no' ) ) ) {
			$actions['remove_personal_data'] = __( 'Remove personal data', 'woocommerce' );
		}

		return $actions;
	}

```

### Expected behavior

Have the possibility to add custom bulk actions.

### Actual behavior

No filter available to add custom bulk actions to the orders screen with HPOS enabled:

### Steps to reproduce

Check code

### WordPress Environment

Latest

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @vaclavgreif,

WordPress itself provides the filter we need to do this. Here is a basic example of adding and handling a bulk action:

```php
// Utilizing the bulk_actions-<SCREEN_ID> hook to add the new bulk action:
add_filter( 'bulk_actions-woocommerce_page_wc-orders', function( $bulk_actions ) {
	$bulk_actions['do_foo_bar'] = 'Foo then bar these orders';
	return $bulk_actions;
} );

// Utilizing the handle_bulk_actions-<SCREEN_ID> hook to handle the new bulk action:
add_filter( 'handle_bulk_actions-woocommerce_page_wc-orders', function ( $redirect_to, $action, $ids ) {
	if ( $action !== 'do_foo_bar' ) {
		return $redirect_to;
	}

	foreach ( $ids as $id ) {
		$order = wc_get_order( $id );
		$order->set_billing_first_name( 'Foo ' . $order->get_billing_first_name() );
		$order->set_billing_last_name( 'Bar ' . $order->get_billing_last_name() );
		$order->save();
	}

	return add_query_arg( 'foo-bar', '1', $redirect_to );
}, 10, 3 );
```

**Comment by vaclavgreif** [comment]
Thanks, I tried every other combination, but this indeed worked!

**Comment by barryhughes** [comment]
💪🏼 Awesome!
