### ISSUE TITLE
[Variation options]: Icon appears on top of term

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#40057]
## Description

For certain scenarios, like a variation option with a lot of terms and long names, there is not enough space for the icon to appear:

![Image](https://user-images.githubusercontent.com/13437655/266078385-35835e34-ee4b-4ddb-ad40-3c2ce9543c02.png)

The icon should not appear on top of the "+(x) more" pill.

## Acceptance criteria

- [ ] When I add a variation option with a lot of terms and long term names, with the "Show in product details" unchecked, the icon should not appear on top of the "+(x) more" pill. The horizontal space should be correctly distributed between the items.

**Comment by pmcpinto** [comment]
This is showing up in the blocked column. Is it blocked by something?

**Comment by pmcpinto** [comment]
> This is showing up in the blocked column. Is it blocked by something?

@nathanss can you clarify this? Thanks!

**Comment by mdperez86** [comment]
Fixed
