### ISSUE TITLE
WooPayments slow down every admin page load

### ISSUE THREAD

**Issue by jonathan-dejong** [woothemes/woocommerce#40066]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I ran some Blackfire profiling and there's some stuff happening from the WooPayments plugin even when I don't even have that thing installed!
This does not seem right?
I checked the changelog for WC and there's a line about WooPayments queries but that doesn't seem to actually fix this particular issue.
The problem here being that this line is very expensive:
https://github.com/woocommerce/woocommerce/blob/ae42e9382b37027fa845bb520c229f55422c5075/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L82
Either way, it's ludicrous that this would run on every single admin page load

### Expected behavior

WooPayments should not affect any unrelated admin pages, especially not when the gateway is not even installed on a site.

### Actual behavior

The `register_payments_welcome_page()` does not happen on any unrelated admin page load and does not take an excessive amount of time to execute.
https://github.com/woocommerce/woocommerce/blob/ae42e9382b37027fa845bb520c229f55422c5075/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L97

### Steps to reproduce

1. Go to any admin page and do a profile of the request (Blackfire is my tool).
2. See that register_payments_welcome_page is executed and that it is not very fast
3. Note that you cannot have set woocommerce_allow_marketplace_suggestions to false because that shortcircuits the method making it quick (but still loading on every page)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://equestrianstockholm.com.qa.synot.io
Site address (URL): https://equestrianstockholm.com.qa.synot.io
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.1.3 - There is a newer version of WordPress available (6.3.1)
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 ()
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 100
PHP Max Input Vars: 5000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 8.0.32-24
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_2_
Total Database Size: 4906.11MB
Database Data Size: 3432.67MB
Database Index Size: 1473.44MB
wp_2_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Data: 35.56MB + Index: 14.55MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Data: 1501.00MB + Index: 364.94MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Data: 0.33MB + Index: 0.36MB + Engine InnoDB
wp_2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Data: 5.05MB + Index: 5.17MB + Engine InnoDB
wp_2_actionscheduler_claims: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Data: 5.52MB + Index: 3.03MB + Engine InnoDB
wp_2_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_amwscp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_amwscp_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_amwscp_template_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cmplz_cookies: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_2_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_cmplz_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 54.58MB + Index: 40.09MB + Engine InnoDB
wp_2_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_groups_user_group: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 13.19MB + Index: 2.53MB + Engine InnoDB
wp_2_pmxe_exports: Data: 15.52MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxe_posts: Data: 18.55MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxe_templates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_files: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_hash: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_history: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_images: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_imports: Data: 16.52MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_posts: Data: 28.56MB + Index: 0.00MB + Engine InnoDB
wp_2_pmxi_templates: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_2_postmeta: Data: 899.00MB + Index: 761.00MB + Engine InnoDB
wp_2_posts: Data: 51.58MB + Index: 30.13MB + Engine InnoDB
wp_2_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_simple_history: Data: 3.02MB + Index: 1.70MB + Engine InnoDB
wp_2_simple_history_contexts: Data: 16.05MB + Index: 12.25MB + Engine InnoDB
wp_2_term_relationships: Data: 2.34MB + Index: 1.48MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.22MB + Index: 0.03MB + Engine InnoDB
wp_2_termmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_2_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
wp_2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Data: 35.58MB + Index: 38.09MB + Engine InnoDB
wp_2_wc_order_stats: Data: 11.52MB + Index: 10.55MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_2_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_wc_product_attributes_lookup: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_2_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Data: 0.42MB + Index: 0.67MB + Engine InnoDB
wp_2_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_reserved_stock: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wcpdf_invoice_number: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_2_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wdr_order_item_discounts: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wp_2_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_2_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_exported_csv_items: Data: 48.58MB + Index: 1.52MB + Engine InnoDB
wp_2_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpml_mails: Data: 469.52MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wt_iew_action_history: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_2_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wt_iew_mapping_template: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_2_yoast_indexable: Data: 3.03MB + Index: 0.31MB + Engine InnoDB
wp_2_yoast_indexable_hierarchy: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_2_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_yoast_primary_term: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_2_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_yoast_seo_links: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wp_2_yoast_seo_meta: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 2.09MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 139.69MB + Index: 146.36MB + Engine InnoDB
wp_users: Data: 8.52MB + Index: 8.55MB + Engine InnoDB

### Post Type Counts ###

acf-field: 140
acf-field-group: 6
attachment: 9248
cookielawinfo: 6
custom_css: 1
customize_changeset: 2
cwginstocknotifier: 45611
nav_menu_item: 86
oembed_cache: 19
page: 178
post: 52
product: 1114
product_variation: 2331
revision: 3114
seedprod: 1
shop_coupon: 1050
shop_order: 93341
shop_order_refund: 3599
woo_discount: 3
woo_discount_cart: 1
wp_global_styles: 1
wp_template_part: 2
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (62) ###

Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 4.0.0
Disable Gutenberg Blocks - Block Manager: by Danny Cooper – 1.0.9
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
EQ Checkout Redirect: by Angry Creative – 0.1.0
Ingrid Delivery Checkout: by Ingrid – 2.0.4
Klarna Checkout for WooCommerce: by Krokedil – 2.11.4
Klarna Order Management for WooCommerce: by klarna
krokedil – 1.8.1

Klaviyo: by Klaviyo
Inc. – 3.2.1

Perfmatters: by forgemedia – 2.1.3
PixelYourSite PRO: by PixelYourSite – 9.6.3
Qala Blocks: by Angry Creative – 1.3.0
Qala Buy: by Angry Creative – 0.2.2
Qala Depict: by Angry Creative – 1.8.1
Qala Global Cart: by Angry Creative – 0.2.5
Qala Labels: by Angry Creative – 1.4.1
Qala Minicart: by Angry Creative – 4.3.0
Qala Order Numbers: by Angry Creative – 0.1.0
Qala WC Rest Improvements: by Angry Creative – 0.9.0
Qala Wishlist: by Angry Creative – 1.1.2
Redirection: by John Godley – 5.3.10
Simple History: by Pär Thernström – 4.3.0
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.7
Trustpilot-reviews: by Trustpilot – 2.5.925
Woo Discount Rules PRO 2.0: by Flycart – 2.4.4
Woo Discount Rules: by Flycart – 2.6.1
Aelia Currency Switcher for WooCommerce: by Aelia – 4.12.12.211208
WooCommerce Back In Stock Notifications: by SomewhereWarm – 1.1.0
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.4
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0
Woosa - Adyen for WooCommerce: by Woosa – 1.4.0
Yoast SEO Premium: by Team Yoast – 20.12
Yoast SEO: by Team Yoast – 20.12
WP All Export Pro: by Soflyy – 1.8.1
WP All Import Pro: by Soflyy – 4.7.8
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.8
WordPress Sentry: by Alex Bouma – 3.10.0
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.6
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4
Yoast SEO: WooCommerce: by Team Yoast – 15.6
YITH WooCommerce Bulk Product Editing Premium: by YITH – 1.6.0
Advanced Custom Fields PRO: by WP Engine – 6.1.7
Safe SVG: by 10up – 2.1.1
WooCommerce: by Automattic – 7.9.0
MultilingualPress: by Inpsyde GmbH – 4.3.0
WP fail2ban: by Charles Lecklider – 5.1.1
Aelia Foundation Classes for WooCommerce: by Aelia – 2.1.21.211102
WooCommerce Smart Coupons: by StoreApps – 7.10.0
Unhook Admin Notices: by Angry Creatives – 0.2.2
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.18.0
Proxy Cache Purge: by Mika Epstein – 5.1.3
AC Varnish Enhancements: by Angry Creative – 0.5.0
Qala Img Proxy: by Angry Creative – 2.1.6
Qala Multimarket: by Angry Creative – 2.5.0
Qala Multimarket Product Connector: by Angry Creative – 1.0.5
Qala Global Cart: by Angry Creative – 0.2.5
ManageWP - Worker: by GoDaddy – 4.9.17
Angry Active Directory: by Angry Creative – 2.1.1
User Switching: by John Blackbourn & contributors – 1.7.0
Loco Translate: by Tim Whitlock – 2.6.4
Simple History: by Pär Thernström – 4.3.0
Complianz Privacy Suite (GDPR/CCPA) premium multisite: by Really Simple Plugins – 6.5.0
Qala Single Stock: by Angry Creative – 0.4.6

### Inactive Plugins (24) ###

Action Scheduler: by Automattic – 3.6.1
Complianz Privacy Suite (GDPR/CCPA) premium: by Really Simple Plugins – 6.4.0
Force Login: by Kevin Vess – 5.6.3
GTM4WP: by Thomas Geiger – 1.16.2
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.11
Ninja Forms: by Saturday Drive – 3.6.28
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.6
Qala Bulk Order: by Angry Creative – 1.1.1
Qala Checkout: by Angry Creative – 0.2.2
Qala EU VAT Compliance: by Angry Creative – 1.3.11
Qala Mixshake: by Angry Creative – 0.1.4
Qala Network Reports: by Angry Creative – 0.5.5
Quantity Plus Minus Button for WooCommerce by CodeAstrology: by CodeAstrology Team – 1.1.7
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.27
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce EU VAT Number: by WooCommerce – 2.3.26
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.7.5
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.15.0
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.14.3
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.21.1
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.8
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.5
WP All Export - User Export Add-On Pro: by Soflyy – 1.0.7
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.8

### Must Use Plugins (1) ###

mu-require.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD (USD)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #14918 - /my-account/
Terms and conditions: #4592 - /terms-and-conditions/

### Theme ###

Name: Equestrianstockholm
Version: 3.2.1
Author URL: https://angrycreative.se/
Child Theme: ✔
Parent Theme Name: Qala
Parent Theme Version: 3.3.23
Parent Theme Author URL: https://angrycreative.se/
WooCommerce Support: ✔

### Templates ###

Overrides: qala-theme/woocommerce/cart/cart.php version 7.0.1 is out of date. The core version is 7.9.0
qala-theme/woocommerce/cart/mini-cart.php version 5.2.0 is out of date. The core version is 7.9.0

Outdated Templates: ❌
					
					
						Learn how to update

### Back In Stock ###

Database Version: 1.1.0
Loopback Test: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-07 09:14:21 +02:00
Options: ✔
Notes: 154
Onboarding: completed

### Action Scheduler ###

Complete: 11,608
Oldest: 2023-08-07 18:54:23 +0200
Newest: 2023-09-07 03:44:23 +0200

Failed: 131
Oldest: 2021-05-04 09:15:41 +0200
Newest: 2021-05-05 07:26:23 +0200

Pending: 1
Oldest: 2023-09-08 03:44:23 +0200
Newest: 2023-09-08 03:44:23 +0200

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 8
Valid order status for auto-generating coupon: completed
Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: no
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: yes
Rounding: no
Display prices in the shop: incl
Display prices during cart and checkout: incl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2023-09-07 11:27:11 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathan-dejong** [comment]
Some BF screenshots showing what is happening:
![Screenshot 2023-09-07 at 10 37 07](https://github.com/woocommerce/woocommerce/assets/1508751/f3505464-2112-452c-83b2-cb9b27785db9)
![Screenshot 2023-09-07 at 10 51 10](https://github.com/woocommerce/woocommerce/assets/1508751/25c691d8-c2b7-413a-941d-1bd54a1271ba)

**Comment by ismaeldcom** [comment]
Hey @jonathan-dejong! Thanks for the detailed report 🙂 This should be fixed by #39958, which is part of WooCommerce 8.0.3, so updating it should solve the issue.

I'm going to close this for now, but please re-open it if the issue persists after the update.

**Comment by jonathan-dejong** [comment]
Oh that is great to hear @ismaeldcom 

I did not see that PR referenced in the changelog though?
https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt

**Comment by ismaeldcom** [comment]
>I did not see that PR referenced in the changelog though?

Oh! Yes, 8.0.3 includes a temporary solution (#39882) that also fixes the performance issue, and 8.1.0 will include the aforementioned PR with the final solution.
