### ISSUE TITLE
Changelog for 8.1 has wrong PR numbers

### ISSUE THREAD

**Issue by benignant** [woothemes/woocommerce#40063]
## Link to the Page/Section

https://github.com/woocommerce/woocommerce/blob/f2bf7cacafe9f016b5108d101cb4c58a6c566e5c/plugins/woocommerce/readme.txt#L171-L252

## Description of the Suggestion

All those PR numbers are the same.

**Comment by lsinger** [comment]
This has been fixed by #40097 and is not present in the 8.1.0 release ZIP.
