### ISSUE TITLE
Change the toggle visibility eye icon from the variations table to be the same used in the options table

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#40072]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We no longer have the turn visibility on/off button in the variations list

The following 
<img width="696" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/436509e6-0754-49f8-9e46-8eda648289c3">

needs to be change by 
<img width="678" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/1ec8b3cf-9069-4556-aae8-da8c688bf51a">

**Epic**

#35660

**ACs**

- [ ] Change the toggle visibility eye icon from the variations table to be the same used in the options table AkVNGImLgSqCObTQ3idVn7-fi-4951_450437
- [ ] The eye icon is not functional, it's only an indicator

**Comment by louwie17** [comment]
@mdperez86 just a note that this does mean that a user can currently not enable/disable the visibility within the new product editor, only in the old editor.
@jarekmorawski do we plan on adding this as part of the quick actions in the future? Or in some other way.

**Comment by jarekmorawski** [comment]
Yes! It'll be a quick action and part of the new individual variation details view. They'll be ready soon.

**Comment by jarekmorawski** [comment]
Additional context in https://github.com/woocommerce/woocommerce/issues/40196 (now closed as duplicate).
