### ISSUE TITLE
[Enhancement]: Avoid running the query in WC_REST_CRUD_Controller::get_objects() twice

### ISSUE THREAD

**Issue by prettyboymp** [woothemes/woocommerce#40075]
### Describe the solution you'd like

The WP_Query run in `WC_REST_CRUD_Controller::get_objects()` is run a second time if no results are found to make sure the total isn't incorrect simply because the offset in the query was too high.

https://github.com/woocommerce/woocommerce/blob/60fa13e21b385f78b77d400f1b965ade2cf2f013/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php#L356-L362

This second query should be avoided if there are no paging parameters set within the query_vars as meta queries to retrieve orders for users is already a scaling concern without HPOS, this doubles the time needed for the API request.

Changing the check to something like the below should solve the issue:

```
if ( $total_posts < 1 && isset( $query_args['paged'] ) && absint( $query_args['paged'] ) > 1 ) {
```

**Comment by barryhughes** [comment]
Thanks for flagging, great catch 🖖🏼
