### ISSUE TITLE
Not showing product categories on the site

### ISSUE THREAD

**Issue by hwarldjdjd** [woothemes/woocommerce#40102]

**Comment by lsinger** [comment]
@hwarldjdjd when I create a new store, import some products, and then set one of the categories as the default, I cannot reproduce the problem you're experiencing. 

Please deactivate all plugins other than WooCommerce and use a default WordPress theme or Storefront. Can you still reproduce the issue? If not it will likely lie with one of the plugins or the theme you're using.
