### ISSUE TITLE
Cannot add or modify shipping methods in Settings

### ISSUE THREAD

**Issue by CryptoChris69** [woothemes/woocommerce#40105]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I cannot not add or modify and expedition method anymore (in the woo commerce settings).

### Expected behavior

I cannot not add or modify and expedition method anymore (in the woo commerce settings).

### Actual behavior

I cannot not add or modify and expedition method anymore (in the woo commerce settings).

### Steps to reproduce

1. Go to settings
2. Add or modify an expedition method

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kalolacreations.ch
Site address (URL): https://kalolacreations.ch
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 640 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 300 Mo
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.4.24-MariaDB-1:10.4.24+maria~stretch-log
Max Upload Size: 300 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_915047_
Taille totale de la base de données: 70.80MB
Taille de la base de données: 50.98MB
Taille de l’index: 19.82MB
wp_915047_woocommerce_sessions: Données : 1.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_915047_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_915047_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_actionscheduler_actions: Données : 10.02MB + Index : 7.53MB + Moteur InnoDB
wp_915047_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_actionscheduler_logs: Données : 6.02MB + Index : 5.03MB + Moteur InnoDB
wp_915047_aioseo_cache: Données : 0.11MB + Index : 0.03MB + Moteur InnoDB
wp_915047_aioseo_notifications: Données : 0.03MB + Index : 0.06MB + Moteur InnoDB
wp_915047_aioseo_posts: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
wp_915047_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_915047_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_e_notes: Données : 0.03MB + Index : 0.17MB + Moteur InnoDB
wp_915047_e_notes_users_relations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_e_submissions: Données : 0.03MB + Index : 0.27MB + Moteur InnoDB
wp_915047_e_submissions_actions_log: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_915047_e_submissions_values: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_gla_attribute_mapping_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_gla_budget_recommendations: Données : 0.22MB + Index : 0.14MB + Moteur InnoDB
wp_915047_gla_merchant_issues: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_915047_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_litespeed_url: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_litespeed_url_file: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_915047_mailpoet_automations: Données : 0.03MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_automation_runs: Données : 0.03MB + Index : 0.08MB + Moteur InnoDB
wp_915047_mailpoet_automation_run_logs: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_mailpoet_automation_run_subjects: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_automation_triggers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_automation_versions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_newsletter_templates: Données : 2.06MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_scheduled_tasks: Données : 0.08MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_915047_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_915047_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_subscribers: Données : 0.02MB + Index : 0.23MB + Moteur InnoDB
wp_915047_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_subscriber_tag: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_mailpoet_tags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_options: Données : 8.02MB + Index : 0.17MB + Moteur InnoDB
wp_915047_postmeta: Données : 12.42MB + Index : 2.59MB + Moteur InnoDB
wp_915047_posts: Données : 8.42MB + Index : 0.30MB + Moteur InnoDB
wp_915047_snippets: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_usermeta: Données : 0.11MB + Index : 0.03MB + Moteur InnoDB
wp_915047_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_wc_admin_notes: Données : 0.08MB + Index : 0.00MB + Moteur InnoDB
wp_915047_wc_admin_note_actions: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_915047_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_915047_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_915047_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wc_product_meta_lookup: Données : 0.06MB + Index : 0.09MB + Moteur InnoDB
wp_915047_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_wpforms_payments: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB
wp_915047_wpforms_payment_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_915047_yoast_indexable: Données : 0.11MB + Index : 0.09MB + Moteur InnoDB
wp_915047_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_915047_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_915047_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_915047_yoast_seo_links: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB

### Post Type Counts ###

attachment: 312
customize_changeset: 6
elementor_library: 2
mailpoet_page: 1
nav_menu_item: 8
page: 12
post: 3
product: 70
product_variation: 72
revision: 850
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Customer Reviews for WooCommerce: par CusRev – 5.34.0
Elementor Pro: par Elementor.com – 3.15.1
Elementor: par Elementor.com – 3.15.3
Essential Addons for Elementor: par WPDeveloper – 5.8.8
Facebook for WooCommerce: par Facebook – 3.0.33
MonsterInsights - Google Analytics pour WordPress: par MonsterInsights – 8.19
Google Listings and Ads: par WooCommerce – 2.5.5
WP Armour - Honeypot Anti Spam: par Dnesscarkey – 2.1.5
Easy HTTPS (SSL) Redirection: par Tips and Tricks HQ – 1.9.2
Jetpack: par Automattic – 12.5
LiteSpeed Cache: par Technologies LiteSpeed – 5.6
Ocean Extra: par OceanWP – 2.2.0
Pinterest pour WooCommerce: par WooCommerce – 1.3.9
Printify Shipping Method: par Printify – 2.7
Temporaire Login Without Password: par StoreApps – 1.8.2
Paiements WooCommerce: par Automattic – 6.4.1
WooCommerce PayPal Payments: par WooCommerce – 2.2.2
WooCommerce: par Automattic – 8.0.3
Yoast SEO: par L’équipe Yoast – 21.1
WP Super Cache: par Automattic – 1.10.0

### Inactive Plugins (5) ###

Code Snippets: par Code Snippets Pro – 3.4.2
Instant Images: par Darren Cooney – 6.0.0
OptinMonster: par OptinMonster Popup Builder Team – 2.13.8
WordPress Importer: par wordpressdotorg – 0.8.1
WPForms Lite: par WPForms – 1.8.3.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #53 - /boutique/
Panier: #54 - /panier/
Commander: #55 - /boutique/commander/
Mon compte: #56 - /mon-compte/
Conditions générales de vente et d’utilisation: #765 - /conditions-generales-de-vente/

### Theme ###

Name: OceanWP
Version: 3.5.0
Author URL: https://oceanwp.org/about-oceanwp/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/product-image.php
oceanwp/woocommerce/single-product/title.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CH
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-11 19:38:51 +02:00
Options: ✔
Notes: 115
Onboarding: completed

### WooCommerce Payments ###

Version: 6.4.1
Connected to WPCOM: Oui
Blog ID: 217157412
Account ID: acct_1MpzXRCLKDOGS5F7

### Action Scheduler ###

Annulé: 12
Oldest: 2023-08-15 10:26:53 +0200
Newest: 2023-08-28 11:03:53 +0200

Terminé: 9 318
Oldest: 2023-08-11 10:57:29 +0200
Newest: 2023-09-11 10:54:10 +0200

Échoué: 7 765
Oldest: 2023-03-26 21:56:52 +0200
Newest: 2023-09-06 21:17:27 +0200

En attente: 11
Oldest: 2023-09-11 10:56:27 +0200
Newest: 2023-09-12 05:16:15 +0200

### Status report information ###

Generated at: 2023-09-11 10:56:33 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by CryptoChris69** [comment]
<img width="1063" alt="Capture d’écran 2023-09-11 à 11 16 54" src="https://github.com/woocommerce/woocommerce/assets/102867122/6cabf3f8-6feb-482d-925e-933b51a076fd">

**Comment by CryptoChris69** [comment]
The wheel won't stop turning, and the settings will not be saved.

**Comment by CryptoChris69** [comment]
No Answer !? 
Is this the right place to talk about an issue ?

**Comment by lsinger** [comment]
@CryptoChris69 I've renamed the issue to "Cannot add or modify shipping methods in Settings" as this seems to more closely describe what you're running into. 

You have quite a few plugins active. To figure out whether the issue stems from WooCommerce you should try to reproduce this issue with the non-WooCommerce plugins deactivated. On a fresh install, adding and editing shipping methods does work for me -- it seems like we're going to need more information.

**Comment by CryptoChris69** [comment]
Hi, thank you for your message. In fact I started having problem some weeks ago, and I suspect this has to do with the fact that the new PHP version changed its version of the strlen() function. Since then, I keep having problem with my site, depending on the update of some plugins. What I found each time, for different plugins, is the fact that a file with the .oti extension is causing a problem. Each time I renamed this file in (.oti__) and this solve the problem, as the file cannot be used anymore.. This is also the case here. And again I solved the problem by renaming the .oti file. The only problem : I do not know what is the purpose of those .oti files. Any ideas ? Many thanks. Problem solved.

**Comment by lsinger** [comment]
@CryptoChris69 thank you for your response. While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only, and what you're describing does not sound like one. I'm not aware of any .oti files, and as long as WooCommerce is running on the recommended versions of PHP, the PHP version shouldn't be a problem. 

You could try one of the following: 

- contact WooCommerce support by [[opening a ticket or starting a live chat](https://woocommerce.com/contact-us/)](https://woocommerce.com/contact-us/) (if you are a paying customer of WooCommerce)
- ask a question in the [[WooCommerce Community Slack](https://woocommerce.com/community-slack/)](https://woocommerce.com/community-slack/)
- post to the [[WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)](https://wordpress.org/support/plugin/woocommerce/), or 
- hire a developer to look into this further.
