### ISSUE TITLE
Duplicate wc-admin_import_orders hook

### ISSUE THREAD

**Issue by truchosky** [woothemes/woocommerce#40115]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Every time I receive an order this hook (wc-admin_import_orders) is created multiple times, this also causes my webhooks to repeat over and over again never ending, when those are completed they are created again, the only way to avoid this is in analytics -> settings, stop import, but as soon as I receive an order it happens again, so I have to hit again the "stop import" button
<img width="1255" alt="Captura de pantalla 2023-09-11 a la(s) 14 19 04" src="https://github.com/woocommerce/woocommerce/assets/9977546/fb6fa8a5-7dc4-453b-a49d-d2e74818dbd4">
<img width="1255" alt="Captura de pantalla 2023-09-11 a la(s) 14 20 56" src="https://github.com/woocommerce/woocommerce/assets/9977546/29c25468-952e-43f3-8644-ddefcc56910c">

### Expected behavior

the hook should be triggered only once

### Actual behavior

duplicate hooks

### Steps to reproduce

receive and order
go to woocommerce->status->scheduled actions

### WordPress Environment ###

WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.15-MariaDB-1:10.6.15+maria~ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Tamaño total de la base de datos: 1458.93MB
Tamaño de los datos de la base de datos: 859.79MB
Tamaño del índice de la base de datos: 599.14MB
wp_woocommerce_sessions: Datos: 13.02MB + Índice: 0.13MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 9.52MB + Índice: 3.52MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 91.64MB + Índice: 99.28MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cerber_acl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cerber_blocks: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cerber_countries: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
cerber_lab: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cerber_lab_ip: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cerber_lab_net: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
cerber_log: Datos: 3.52MB + Índice: 2.20MB + Motor InnoDB
cerber_qmem: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cerber_traffic: Datos: 5.52MB + Índice: 0.22MB + Motor InnoDB
wp_abandoned_cart_aelia_currency: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 2.52MB + Índice: 2.38MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 66.13MB + Índice: 49.14MB + Motor InnoDB
wp_ac_abandoned_cart_history: Datos: 0.08MB + Índice: 0.02MB + Motor InnoDB
wp_ac_atc_rules: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ac_connector_sync: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ac_guest_abandoned_cart_history: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ac_link_clicked_notifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ac_notifications_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ac_notification_templates: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
wp_ac_opened_notifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ac_sent_history: Datos: 0.03MB + Índice: 0.02MB + Motor InnoDB
wp_ac_statistics: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ac_tiny_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_aelia_dismissed_messages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_as3cf_items: Datos: 3.52MB + Índice: 4.55MB + Motor InnoDB
wp_bwfan_abandonedcarts: Datos: 1.50MB + Índice: 0.31MB + Motor InnoDB
wp_bwfan_automationmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_automations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_automation_complete_contact: Datos: 4.52MB + Índice: 0.30MB + Motor InnoDB
wp_bwfan_automation_contact: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
wp_bwfan_automation_contact_claim: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bwfan_automation_contact_trail: Datos: 1.52MB + Índice: 1.34MB + Motor InnoDB
wp_bwfan_automation_step: Datos: 0.16MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_broadcast: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_bulk_action: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_contact_note: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_bwfan_conversions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_bwfan_engagement_tracking: Datos: 0.22MB + Índice: 0.31MB + Motor InnoDB
wp_bwfan_engagement_trackingmeta: Datos: 3.52MB + Índice: 0.05MB + Motor InnoDB
wp_bwfan_fields: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_bwfan_field_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bwfan_form_feeds: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_import_export: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwfan_link_triggers: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_bwfan_message: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_bwfan_message_unsubscribe: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_bwfan_templates: Datos: 0.23MB + Índice: 0.05MB + Motor InnoDB
wp_bwfan_terms: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_bwf_actions: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_bwf_action_claim: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_bwf_contact: Datos: 1.52MB + Índice: 0.44MB + Motor InnoDB
wp_bwf_contact_fields: Datos: 0.41MB + Índice: 1.22MB + Motor InnoDB
wp_bwf_contact_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_bwf_conversion_tracking: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_bwf_funnelmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwf_funnels: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_bwf_optin_entries: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwf_options: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_bwf_wc_customers: Datos: 0.20MB + Índice: 0.06MB + Motor InnoDB
wp_cartflows_ca_cart_abandonment: Datos: 9.56MB + Índice: 0.52MB + Motor InnoDB
wp_cartflows_ca_email_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cerber_files: Datos: 6.55MB + Índice: 0.00MB + Motor InnoDB
wp_cerber_ms: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_cerber_ms_lists: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_cerber_sets: Datos: 9.52MB + Índice: 0.00MB + Motor InnoDB
wp_cerber_uss: Datos: 0.22MB + Índice: 0.05MB + Motor InnoDB
wp_commentmeta: Datos: 0.16MB + Índice: 0.17MB + Motor InnoDB
wp_comments: Datos: 81.63MB + Índice: 36.09MB + Motor InnoDB
wp_cron_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_litespeed_img_optm: Datos: 0.50MB + Índice: 0.25MB + Motor InnoDB
wp_litespeed_img_optming: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_litespeed_url: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_litespeed_url_file: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_mwai_chats: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 26.44MB + Índice: 14.33MB + Motor InnoDB
wp_postmark_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_postmeta: Datos: 386.95MB + Índice: 314.83MB + Motor InnoDB
wp_posts: Datos: 24.55MB + Índice: 13.98MB + Motor InnoDB
wp_pys_stat_landing: Datos: 0.45MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_order: Datos: 4.52MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_product_order: Datos: 8.52MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_traffic: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_utm_campaing: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_utm_content: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_utm_medium: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_utm_source: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_pys_stat_utm_term: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shopmagic_automation_outcome: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shopmagic_automation_outcome_logs: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_shopmagic_cart: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_shopmagic_guest: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shopmagic_guest_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_shopmagic_marketing_lists: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shopmagic_optin_email: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_shopmagic_tracked_emails: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_shopmagic_tracked_emails_clicks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_social_users: Datos: 0.33MB + Índice: 0.33MB + Motor InnoDB
wp_termmeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.09MB + Índice: 0.08MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_transbank_inscriptions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_usermeta: Datos: 44.47MB + Índice: 33.70MB + Motor InnoDB
wp_users: Datos: 3.25MB + Índice: 2.42MB + Motor InnoDB
wp_vexpe_pagoefectivo: Datos: 0.23MB + Índice: 0.00MB + Motor InnoDB
wp_viwec_clicked: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_fs_licensed_products: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_fs_license_key_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_fs_product_licenses_keys: Datos: 0.50MB + Índice: 0.00MB + Motor InnoDB
wp_wc_fs_product_licenses_keys_generator_rules: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_fs_queue: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 8.02MB + Índice: 7.09MB + Motor InnoDB
wp_wc_order_stats: Datos: 9.02MB + Índice: 5.83MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.09MB + Índice: 0.08MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_webpay_rest_transactions: Datos: 17.55MB + Índice: 0.00MB + Motor InnoDB
wp_wfacp_stats: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wfblockediplog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wfconfig: Datos: 0.48MB + Índice: 0.00MB + Motor InnoDB
wp_wfco_connectormeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wfco_connectors: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wfco_report_views: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wffilemods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wfhits: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wfhoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wfissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wfknownfilelist: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
wp_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wflogins: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wfstatus: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_emails_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wp_phpmyadmin_extension__errors_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yith_wcwl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yith_wcwl_lists: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_yith_ywrac_email_log: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
wp_yoast_indexable: Datos: 0.28MB + Índice: 0.13MB + Motor InnoDB
wp_yoast_indexable_hierarchy: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yoast_primary_term: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_yoast_prominent_words: Datos: 0.13MB + Índice: 0.23MB + Motor InnoDB
wp_yoast_seo_links: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_yoast_seo_meta: Datos: 0.39MB + Índice: 0.00MB + Motor InnoDB
wp_ywrr_email_blocklist: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ywrr_email_schedule: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 3920
aw_workflow: 1
blocks: 13
codeswholesale_email: 6
custom_css: 1
docs: 21
epkb_post_type_1: 18
muzaara-woopf-bing: 1
nav_menu_item: 16
oembed_cache: 64
page: 19
post: 1
product: 233
product_variation: 50
product-feed: 1
revision: 86
shop_coupon: 155
shop_order: 61930
shop_order_refund: 561
shopmagic_automation: 2
viwec_template: 14
viwec_template_block: 2
woo_mb_template: 10
wp_global_styles: 1
wpcf7_contact_form: 5
yith-wcet-etemplate: 4
ywar_reviews: 1
ywrac_cart: 41
ywrac_email: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Query Monitor: por John Blackbourn – 3.13.1
FS License Manager: por Firas Saidi – 5.0.4
Woocommerce Chek: por Mariano A. Martinez – 1.0.0
Protección Anti-Spam Akismet: por Automattic - Equipo Anti Spam – 5.2
Payment Gateway Based Fees and Discounts for WooCommerce Pro: por Tyche Softwares – 2.9.0
Contact Form 7: por Takayuki Miyoshi – 5.8
Pasarela de pago PayPal Express Checkout para WooCommerce: por WebToffee – 1.4.3
Flow Payment: por Flow – 3.0.0
Judge.me Product Reviews for WooCommerce: por Judge.me – 1.3.22
LiteSpeed Cache: por LiteSpeed Technologies – 5.6
Nextend Social Login: por Nextendweb – 3.1.9
Nextend Social Login Pro Addon: por Nextendweb – 3.1.9
ABC Crypto Checkout: por payerurl team – 1.3.4
WooCommerce payku (Multicaja Efectivo): por Payku – 3.0.4
PixelYourSite Microsoft UET (Bing): por PixelYourSite – 3.1.2
PixelYourSite PRO: por PixelYourSite – 9.10.2
PixelYourSite Super Pack: por PixelYourSite – 4.0.0
ActiveCampaign Postmark (Official): por Andrew Yates & Matt Gibbs – 1.19.1
Product Catalog Feed Pro by PixelYourSite: por PixelYourSite – 5.3.4
Transbank Webpay REST: por TransbankDevelopers – 1.6.8
PagoEfectivo: por Vex Soluciones – 1.2.2
Aelia Foundation Classes for WooCommerce: por Aelia – 2.4.15.230905
Izipay for WooCommerce: por Lyra Network – 1.10.8
Aelia Currency Switcher for WooCommerce: por Aelia – 5.0.10.230809
Checkout Field Editor for WooCommerce (Pro): por ThemeHigh – 3.5.0
WooCommerce Email Template Customizer Premium: por VillaTheme – 1.2.0
Wompi Plugin para WooCommerce: por Vlipco SAS – 0.2.0
WooCommerce khipu Gateway: por khipu – 3.5
WooCommerce Mach Gateway: por Jovan Turing – 0.1.0
Zoho SalesIQ-Woocommerce: por Zoho SalesIQ Team – 1.0.8
WooCommerce: por Automattic – 8.0.3
WooSidebars: por WooCommerce – 1.4.6
Yoast SEO Premium: por Equipo Yoast – 21.0
Yoast SEO: por Equipo Yoast – 21.1
WP Cerber Security, Anti-spam & Malware Scan: por Cerber Tech Inc. – 9.5.7
FunnelKit Automations Connectors: por FunnelKit – 2.5.0
FunnelKit Automations Pro: por FunnelKit – 2.5.0
FunnelKit Automations: por FunnelKit – 2.5.1
Yoast SEO: WooCommerce: por Equipo Yoast – 15.8

### Dropin Plugins (2) ###

db.php: Query Monitor Database Class (Drop-in)
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

aaa-wp-cerber.php: por Cerber Tech Inc. – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CLP (CLP)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #7 - /shop/
Carrito: #8 - /cart/
Finalizar compra: #9 - /checkout/
Mi cuenta: #10 - /mi-cuenta/
Términos y condiciones: #352 - /terms/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.17.6
Parent Theme Author URL: https://uxthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-12 13:20:47 -03:00
Options: ✔
Notes: 14
Onboarding: completed

### Action Scheduler ###

Cancelada: 11
Oldest: 2023-09-11 13:35:42 -0300
Newest: 2023-09-11 14:07:33 -0300

Completo: 8.260
Oldest: 2023-09-11 12:38:19 -0300
Newest: 2023-09-11 14:20:23 -0300

Pendiente: 1
Oldest: 2023-09-11 17:19:38 -0300
Newest: 2023-09-11 17:19:38 -0300

### Status report information ###

Generated at: 2023-09-11 14:23:35 -03:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rafwlaz** [comment]
@truchosky

A temporary solution to turn off synchronization is on file:
`wp-content/plugins/woocommerce/src/Internal/Admin/Schedulers/OrdersScheduler.php` and in the `possibly_schedule_import` method, comment out adding actions

```
	public static function possibly_schedule_import( $order_id ) {
		if ( ! OrderUtil::is_order( $order_id, array( 'shop_order' ) ) && 'woocommerce_refund_created' !== current_filter() ) {
			return;
		}

//		self::schedule_action( 'import', array( $order_id ) );
	}
```

**Comment by truchosky** [comment]
I just disabled the entirely analytics option, problem solved, I now have to use an external service like putler to handle metrics but the server now runs even better

**Comment by rafwlaz** [comment]
@truchosky how do You disable entirely analytics option?

**Comment by truchosky** [comment]
admin.php?page=wc-settings&tab=advanced&section=features

**Comment by truchosky** [comment]
sorry, was a bug from pixel your site plugin
