### ISSUE TITLE
Customize Your Store UI issues 

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#40123]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Customize Your Store UI issues identified by Veronica: Mrk6SERPZ4KrFHSjM0a8TK-fi-4907%3A192443

## Acceptance Criteria

Fix all issues mentioned above

**Comment by rjchow** [comment]
closed by https://github.com/woocommerce/woocommerce/pull/40155
