### ISSUE TITLE
WC Developer Blog > Mobile > responsiveness : missing margin/padding

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#40154]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

the left margin is missing. Apparently deals with body .is-layout-flex, but the nested classes have to be fixed

![image](https://github.com/woocommerce/woocommerce/assets/919332/90529124-f194-4718-9fec-3203e1fbb4e5)

### Expected behavior

missing some space on the left

### Actual behavior

content is sticked to the left border

### Steps to reproduce

Have a look at https://developer.woocommerce.com/blog/ on your mobile device

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by brentmackinnon** [comment]
Thanks! I've adjusted the margin on this page and it should fix the lack of space for this content.
