### ISSUE TITLE
[Product Block Editor] List and sale price disappear once variations are added

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#40167]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently once a user adds variations to a product the list and sale price show up blank, as variable products don't include pricing fields as the individual variations include them.

We should probably go ahead with our original design and either disable these or remove them from the template.

cc: @jarekmorawski thoughts on the above, do you have a preference?

See GIF with issue:
![WaWmSZ.gif](https://github.com/woocommerce/woocommerce/assets/2240960/c262e8c0-b10c-4c24-8178-8bfb96d7bdf5)

**Reproduction steps:**

1. Enable the variations feature flag and the new product block editor
2. Go to **Products > Add new**
3. Add a name and price, but don't save yet
4. Go to the variations tab and add a couple variation options (this converts the product to a variable product )
5. Variations should be auto created
6. Now hit **Save draft** or **Add** ( to publish )
7. Go back to the **General** tab and notice how the list and sale price are blank
8. Go back to variations and remove all of them
9. Go back to **General** tab and add the list/sale price and save it, notice how prices do stay now.

**Comment by jarekmorawski** [comment]
We plan to remove the price fields from the general tab and only keep them in the Pricing tab, but the issue remains. When variations are added, we currently show a notice, but it might be better to remove the Pricing, Inventory, and Shipping tabs altogether to reduce confusion.

@pmcpinto We've discussed this in the past, but I think it's worth another thought.

**Comment by pmcpinto** [comment]
> @pmcpinto We've discussed this in the past, but I think it's worth another thought.

Do you think removing the tabs is intuitive for users? They may not realize that this data is now managed at the variation level.

**Comment by jarekmorawski** [comment]
I agree. Maybe we could do both? Remove the fields and display the non-dismissible notice at the top of the tab? This would prevent users from entering information that will not be used while guiding them to where they can manage additional details.

**Comment by pmcpinto** [comment]
Can you share a screenshot or link to the Figma file with this proposal? Thanks

**Comment by jarekmorawski** [comment]
Here's what I have in mind. We'd fade the fields similarly to how we'll do it in the shipping tab when the physical/virtual toggle is off.

https://github.com/woocommerce/woocommerce/assets/79307566/d0dac310-3c61-4266-82b6-bcbb1e43338d

**Update**
We'll go in this direction. Here's the design: AkVNGImLgSqCObTQ3idVn7-fi-2780_278432

**Acceptance criteria**
- [ ] When variations are enabled, we show notices in the Pricing, Inventory, and Shipping tabs. The notices have different copy.
   - [ ] Pricing: `This product has variation options, such as size or color. You can now manage each variation's price and other details individually.`
   - [ ] Inventory: `This product has variation options, such as size or color. You can now manage each variation's stock and other details individually.`
   - [ ] Shipping: `This product has variation options, such as size or color. You can now manage each variation's shipping dimensions and other details individually.`
- [ ] Fields in each tab are disabled and faded (40% opacity).
- [ ] When the user deletes all variations, fields become active again.

cc @octaedro

**Comment by pmcpinto** [comment]
@jarekmorawski this approach is a good starting point as it informs the user about what has changed in the UI without removing the tabs.

BTW, do we already have a GH issue for the spotlight when variations are created? I'm not finding it.

**Comment by jarekmorawski** [comment]
We didn't because we cut it out of the scope in the MVP. It'd be a fine addition, though. Added it here: https://github.com/woocommerce/woocommerce/issues/40306.

**Comment by pmcpinto** [comment]
@louwie17 do you think we should close this one, considering that we have #44761 ?

**Comment by louwie17** [comment]
> @louwie17 do you think we should close this one, considering that we have #44761 ?

Yes, I think that be good. I will do it as part of this comment.
Closing this in favour of #44761
