### ISSUE TITLE
[Customize Your Store] Loading - AI completion API call

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#40162]
Splitting https://github.com/woocommerce/woocommerce/issues/39712 into more granular issues since there's a bit of work to be done

Other issue: https://github.com/woocommerce/woocommerce/issues/40163

After some discussion this is the scope of remaining work on #39712 :

1. Save business description to `woo_ai_describe_store_description` option
2. Call  `/wc/store/v1/patterns`  endpoint to populate pattern contents/images (Store Editing is still working on it and should be done by the end of this week.)
3. Ask AI to classify whether the site is a small or large business. Then choose a F5AAbRJOGbTeEweXPFtHgf-fi-2283_33975.
4. AI requests to choose a header and footer
5. AI requests to Mrk6SERPZ4KrFHSjM0a8TK-fi-2631:256887#547270745 and one for the default color.
6. AI requests to choose a font pairing
7. Save AI response to the option

9. Update block theme global styles and block template data with AI response data. (need to create a new method or endpoint)

This issue will cover 1-7

Some preliminary work on the prompts here: https://github.com/woocommerce/woocommerce/issues/39529

**Comment by chihsuan** [comment]
> Call  /wc/store/v1/patterns  endpoint to populate pattern contents/images (Store Editing is still working on it and should be done by the end of this week.)


The pattern image part has been merged into the trunk. We can install woocommerce-blocks [Nightly build](https://github.com/woocommerce/woocommerce-blocks/releases) for development.

See https://github.com/woocommerce/woocommerce-blocks/pull/10881
