### ISSUE TITLE
[Customize Your Store] Loading - Persisting AI assembled site

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#40163]
Splitting https://github.com/woocommerce/woocommerce/issues/39712 into more granular issues since there's a bit of work to be done

Other issue: https://github.com/woocommerce/woocommerce/issues/40162

After some discussion this is the scope of remaining work on #39712 :

1. Save business description to `woo_ai_describe_store_description` option
2. Call  `/wc/store/v1/patterns`  endpoint to populate pattern contents/images (Store Editing is still working on it and should be done by the end of this week.)
3. Ask AI to classify whether the site is a small or large business. Then choose a F5AAbRJOGbTeEweXPFtHgf-fi-2283_33975.
4. AI requests to choose a header and footer
5. AI requests to Mrk6SERPZ4KrFHSjM0a8TK-fi-2631:256887#547270745 and one for the default color.
6. AI requests to choose a font pairing
7. Save AI response to the option

9. Update block theme global styles and block template data with AI response data. (need to create a new method or endpoint)

This issue covers 8

The work on this should involve defining a endpoint along with the expected payload, and this payload schema will be used as input to the earlier AI API call in order to inform the schema that the AI is expected to respond with.

**Comment by chihsuan** [comment]
## Payload schema


```ts
Payload {
  color_palette: 'Ancient Bronze' | 'Crimson Tide' | ...
  font: 'Bodoni Moda + Overpass' | 'Commissioner + Crimson Pro' | ...
  header: string // slug of header pattern
  home_template: string // name of home template
  footer: string // slug of footer pattern
}
```

We still need to give each home template a unique name/id. See https://github.com/woocommerce/woocommerce/pull/40140/files#diff-3492e319ced15b4e770c372c91a8f44cd3ecc0c164a7795f4b48920b358a62acR16-R74 for home template list

**Comment by chihsuan** [comment]
I've spent some time looking into the API implementation, and I think we it would probably be easier to call the relevant WP APIs directly on the front end. Will continue with this tomorrow.
