### ISSUE TITLE
[Fix] Update the visibility icon

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40174]
I noticed that the visibility icon we show in the variation options list contains the question mark, which I only added in Figma to illustrate the cursor change when the user hovers over it.

Let's update it to a proper icon without the cursor and change the cursor behavior to match the design.

<img width="165" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/44667d35-2103-4bdb-b191-5b0b684f6e07">

<img width="106" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/5d1015b8-4600-4f90-ba2e-0435c5a2a137">

**Acceptance criteria**

- [ ] The visibility icon matches the design.
- [ ] The cursor changes to a question mark when the user hovers over the icon, then displays the tooltip.

**Comment by louwie17** [comment]
> which I only added in Figma to illustrate the cursor change when the user hovers over it.

Oooh really?? Is there a better way to differentiate this in Figma in the future?
I did initially think it was odd, but now have grown to kinda like it, also cause I worked on it I suppose.

**Comment by jarekmorawski** [comment]
I'm not aware of a better way to signal this. Next time I'll make sure to mention it in the AC.
