### ISSUE TITLE
Shipping Settings: Update Post Codes entry UI

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#40186]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The Post Codes entry UI needs to be updated.

Designs are needed and can make use of Gutenberg design library as this interaction will be created using React.

<img width="572" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/03c7a524-2750-4dbd-9ea6-5362285291c0">

**Comment by FlorianBru** [comment]
Hello @psealock, please find the requested design below

<img width="1378" alt="image" src="https://github.com/woocommerce/woocommerce/assets/111048810/fa326ac7-1f24-43c8-bfd0-26b7e6b86fa9">

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/40554
