### ISSUE TITLE
Remove the visibility icon from the variations table

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40196]
There's currently a clickable visibility icon in the variations table. I think it's a remnant of the old design where the user could turn variations on and off from within the table. That is no longer present in the new design, so we can remove it.

<img width="196" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/88dd44e8-59be-4731-a2ab-111a9070a928">

However, the icon should still appear if the variation is toggled off on an individual variation level. Related issue: https://github.com/woocommerce/woocommerce/issues/40215

**Acceptance criteria**

- [ ] The visibility icon is only shown when a variation is set to be hidden from the store (the visibility toggle is off).
- [ ] The visibility icon is read-only and non-interactive. When the user hovers over the icon, we show a tooltip that reads: `Not visible`. Design: AkVNGImLgSqCObTQ3idVn7-fi-1639_217612

**Comment by louwie17** [comment]
@jarekmorawski this is a duplicate off https://github.com/woocommerce/woocommerce/issues/40072 isn't it?

**Comment by jarekmorawski** [comment]
Correct. Wasn't aware! I'll close this one, but link to it in the original issue for additional context.
