### ISSUE TITLE
Shipping Settings: Add a "Learn more" link to Shipping Classes

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#40191]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Add "Learn more" link.

<img width="528" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/66aefb5d-bce1-4194-99cf-b4aa0992a67e">

**Needed:** url for link

**Comment by laurajohnsonwoo** [comment]
Here you go! https://woocommerce.com/document/product-shipping-classes/

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/40893
