### ISSUE TITLE
Variations table is cut off on the sides

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40201]
The variations table is cut off on the sides, which is clearly visible when the user checks a box. Let's fix that to make sure the table content is displayed properly no matter the width.

<img width="196" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/be1960a2-205f-432b-8438-f21b163abbc1">

**Comment by octaedro** [comment]
This issue has been solved by the PR https://github.com/woocommerce/woocommerce/pull/40220
