### ISSUE TITLE
Update the section header design

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40213]
We have a new design for the section/block header. It hides the help text behind a [ ? ] button and moves the contextual buttons (such as "Add new") in the same line to save vertical space. As part of this issue, we should update it for all sections in the form.

Related to https://github.com/woocommerce/woocommerce/issues/40200

<img width="468" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/eb0cfea3-89a2-48b9-b6a0-3ca649db7cbd">

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1005_134277

**Acceptance criteria**

- [ ] All sections use the new header design.
- [ ] Have popup show up on click and hover

**Comment by louwie17** [comment]
@jarekmorawski do we want to show this tooltip to show on hover as well?

**Comment by jarekmorawski** [comment]
No, I think it should be shown on click. We don't need a tooltip. Please make sure to change the cursor to `pointer` to indicate it's clickable and wrap the ( ? ) in a `<button>` to ensure basic accessibility (the label can be `View helper text`). More details [here](https://techservicesillinois.github.io/accessibility/examples/popover.html). Thank you!
