### ISSUE TITLE
Remove the confirmation modal for dismissing unsaved attributes/variation options

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40216]
I noticed we added a confirmation modal when the user attempts to close the add attributes/variation options modal. It's handy and I appreciate the initiative, but all of this information can be easily added again after the modal is closed, so I'm not sure the confirmation is needed. Let's remove it for now and bring it back if needed.

<img width="620" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/428b0398-b3da-4795-8cff-11512fc0197c">

**Comment by mdperez86** [comment]
@louwie17 what do you think about this? I can not recall what was the reason we added this.

**Comment by louwie17** [comment]
> @louwie17 what do you think about this? I can not recall what was the reason we added this.

I think I added it, this may of been a requirement in the old design? But I agree with Jarek, that removing it makes sense.
