### ISSUE TITLE
The variations table should match the height of number of rows selected

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40211]
Currently, even if 10 or 25 items per page are selected in the variations table, it has a fixed height, which forces the user to scroll. Let's change that so the table matches the selected number of rows.

This means that if the user selects 25 items per page, the table's height will change from 360 to 1800. If there are fewer items than the selected value, the table with wrap around the last one (for example, if 25 items per page is selected, but there are only 9, the table will be 648 px high instead of 1800 px).

<img width="884" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/b0a2a4fb-497a-4516-bbe6-9054a15c3e0e">

**Comment by mdperez86** [comment]
@louwie17 It was a reason why we fixed the height of the table right!? Does it was the loading box, the spotlight help box or both? I can remember that you where having troubles with it.
Now this is being requested here and also must be applied to any lazy/paginated table that we have.

cc: @jarekmorawski

**Comment by jarekmorawski** [comment]
It's a worthwhile effort, even if it means spending a little more time figuring it out. This issue came up a few times during internal testing and I'm sure it'll be a meaningful UX improvement.
