### ISSUE TITLE
Update copy in the add variation options modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40246]
We've received feedback that the link in the add variation options modal isn't very helpful and can be a distraction for users. Let's update the copy to remove it.

Acceptance criteria

- [ ] There's a new description in the "Add variation options" modal that reads: `Select from existing attributes or create new ones to add new variations for your product. You can change the order later.`

**Comment by octaedro** [comment]
Hi @jarekmorawski,

Does the new copy have any links?

The old one has one pointing to [this article](https://woocommerce.com/document/variable-product/#add-attributes-to-use-for-variations).

![Screenshot 2023-09-18 at 13 09 00](https://github.com/woocommerce/woocommerce/assets/1314156/97fc8122-12dd-42a6-a07a-cc93c5efaed6)

**Comment by jarekmorawski** [comment]
Hiya! There are no links in the new copy.
