### ISSUE TITLE
Incorrect description of function is_checkout() in includes/wc-conditional-functions.php

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#40257]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The docblock for the function `is_checkout()` in the file `includes/wc-conditional-functions.php` states "Is_checkout - Returns true when viewing the checkout page.".

However, the function itself will also return true if `Constants::is_defined( 'WOOCOMMERCE_CHECKOUT' )` is true, which is the case when updating or processing a new order via a background AJAX request also.

I suppose that in that case the customer is technically "viewing the checkout page", but a developer is likely to misunderstand it as meaning "this current PHP process is generating the checkout page".

I suggest changing the wording to "Returns true when viewing the checkout page or performing an AJAX request that updates or processes the order at the checkout".

### Expected behavior

The docblock description should be more precise.

### Actual behavior

The docblock description is ambiguous ("viewing the page" includes AJAX requests).

### Steps to reproduce

n/a

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Agree! If you have time, please feel free to submit a PR (and if not, we'll do our best to get to it).

**Comment by DavidAnderson684** [comment]
PR: https://github.com/woocommerce/woocommerce/pull/40258
