### ISSUE TITLE
Add virtual- and downloads-related controls to variation management flows

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40250]
Since we're adding digital and downloadable product features to the main form, we should make sure they're also supported by the current variation management flows. Let's add missing quick actions to the global `Quick update` menu and the individual variation controls (menus opened through the ... button).

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1641_216594

<img width="512" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/aaac5512-0f79-4ebd-a407-fa66b6a7549c">

**Acceptance criteria**

- [x] We add new items to the `Quick update` menu:
   - [x] Shipping -> `Toggle shipping` (does what `Toggle "Virtual"` does in the current UX)
   - [x] Downloads -> `Upload files` (doesn't exist in the current UX, opens a file picker. If multiple variations are selected and the user selects a file, it'll be added to all of them; files are then uploaded individually, so they have unique IDs)
   - [x] Downloads -> `Set download limit` (does what `Download limit` does in the current UX)
   - [x] Downloads -> `Set download expiry` (does what `Download expiry` does in the current UX)
- [x] When at least 1 file is added to a variation, it automatically receives the "Downloadable" trait.
- [x] The changes above apply to both the `Quick update` menu and the individual variation actions.

**Comment by pmcpinto** [comment]
> Shipping -> Toggle shipping (does what Toggle "Virtual" does in the current UX)

I'm not sure if this copy is intuitive. What if the change it Enable/Disable shipping, depending on the current state?

The rest of the AC looks great 👌

**Comment by jarekmorawski** [comment]
> I'm not sure if this copy is intuitive. What if the change it Enable/Disable shipping, depending on the current state?

The state can be mixed if you select some variations that have the trait enabled, and some that don't. 🤔 Toggle X is how we're currently handling this in the classic UX and though I spent time thinking about it, I couldn't come up with anything better.

**Comment by mdperez86** [comment]
Hey @jarekmorawski 

>Downloads -> Upload files (doesn't exist in the current UX, opens a file picker. If multiple variations are selected and the user selects a file, it'll be added to all of them; files are then uploaded individually, so they have unique IDs)

<s>Since variations do not support multiple images for now. I'm going to change this to upload only one image. We can tackle multiple images in a different story since this is a pretty big change considering that the server side needs to be changed.</s>

Sorry about my confusion here. I thought it was the variation image. But here we are talking about the downloadable files. So ignore this comment.
