### ISSUE TITLE
Refactor JWT creation to use Jetpack AI JWT package

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#40299]
We now have access to the Jetpack AI JWT library:

https://github.com/Automattic/jetpack-ai-client/blob/trunk/src/jwt/Readme.md

`npm install --save @automattic/jetpack-ai-client`

```
import { requestJwt } from '@automattic/jetpack-ai-client';

const tokenData = await requestJwt();
```

**Comment by joelclimbsthings** [comment]
https://github.com/Automattic/jetpack/blob/trunk/projects/js-packages/ai-client/src/jwt/Readme.md

**Comment by peterfabian** [comment]
Closing down [this issue] as the feature is being sunset
