### ISSUE TITLE
Show a guide when variations are first created

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40306]
When the user creates product variations for the first time, we'd show a spotlight-like guide to let them know that they can now manage pricing, stock, and shipping for individual variations.

Related to https://github.com/woocommerce/woocommerce/issues/40167.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-1639_214803

https://github.com/woocommerce/woocommerce/assets/79307566/d0dac310-3c61-4266-82b6-bcbb1e43338d

**Acceptance criteria**

- [ ] When the user creates product variations for the first time, we show a spotlight message highlighting the variations table.
- [ ] The message appears with a slight fade or dissolve effect. There's a 600ms delay from the moment the variations are first created. The variations table smoothly transitions into the highlight.
- [ ] When the message is shown on the screen, the user cannot scroll or interact with the table.
- [ ] The message is only shown once. When the user creates another product with variations, they won't see it again.
- [ ] The message's title reads: `⚡️ This product now has variations`. The content reads: `From now on, you’ll manage pricing, shipping, and inventory for each variation individually—just like any other product in your store.`
- [ ] The message is displayed until dismissed by the user.
- [ ] Clicking the "Got it" button or the X button in the corner dismisses the message.

**Comment by nathanss** [comment]
Let's make sure to prevent overlap between the initial wizard (if it wasn't closed) and this one.
