### ISSUE TITLE
Fatal error in class-wc-helper-updater.php when going to admin Plugins tab

### ISSUE THREAD

**Issue by lcutshall** [woothemes/woocommerce#40319]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I try to go to the Plugins tab in the WordPress admin, I get a fatal error.  This is the error in the log file:

{
  "installName": "glrv",
  "environment": "PROD",
  "type": "error",
  "date": "2023-09-20T20:39:20.075Z",
  "severity": null,
  "client": null,
  "message": "PHP Fatal error:  Uncaught Error: Attempt to assign property \"translations\" on null in /nas/content/live/glrv/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81#012Stack trace:#012#0 /nas/content/live/glrv/wp-includes/class-wp-hook.php(312): WC_Helper_Updater::transient_update_plugins(NULL)#012#1 /nas/content/live/glrv/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)#012#2 /nas/content/live/glrv/wp-includes/option.php(2053): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins')#012#3 /nas/content/live/glrv/wp-includes/update.php(393): set_site_transient('update_plugins', Object(stdClass))#012#4 /nas/content/live/glrv/wp-includes/class-wp-hook.php(310): wp_update_plugins('')#012#5 /nas/content/live/glrv/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)#012#6 /nas/content/live/glrv/wp-includes/plugin.php(517): WP_Hook->do_action(Array)#012#7 /nas/content/live/glrv/wp-admin/admin.php(385): do_action('load-plugins.ph...')#012#8 /nas/content/live/glrv/wp-admin/plugins.php(10): require_once('/nas/content/li...')#012#9 {main}#012  thrown in /nas/content/live/glrv/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php on line 81",
  "uuid": "1d27af1b-8bc2-4edf-854e-f1bc0aee70b9"
}

### Expected behavior

I expect to get the list of plugins.

### Actual behavior

I get a fatal error.

### Steps to reproduce

1. Log in to the admin
2. Click on the Plugins tab on the left
3. I get a fatal error message

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.glrv.com
Site address (URL): https://www.glrv.com
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: ❌ 6.3 - There is a newer version of WordPress available (6.3.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.8
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.7.42-46-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_33uxxoda_
Total Database Size: 1362.71MB
Database Data Size: 864.44MB
Database Index Size: 498.27MB
wp_33uxxoda_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_33uxxoda_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_33uxxoda_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
smackcsv_line_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
smackcsv_pie_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_actionscheduler_actions: Data: 8.02MB + Index: 12.86MB + Engine InnoDB
wp_33uxxoda_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_actionscheduler_logs: Data: 7.02MB + Index: 5.48MB + Engine InnoDB
wp_33uxxoda_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_33uxxoda_cp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_cubiq_add_to_home: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_33uxxoda_facetwp_index: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_gf_entry: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_33uxxoda_gf_entry_meta: Data: 2.52MB + Index: 5.55MB + Engine InnoDB
wp_33uxxoda_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_gf_form_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_gf_form_view: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_33uxxoda_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_layerslider: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_options: Data: 5.50MB + Index: 0.14MB + Engine InnoDB
wp_33uxxoda_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_postmeta: Data: 488.00MB + Index: 145.09MB + Engine InnoDB
wp_33uxxoda_posts: Data: 55.59MB + Index: 73.52MB + Engine InnoDB
wp_33uxxoda_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_rg_form_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_rg_form_view: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_33uxxoda_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_rg_lead: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_33uxxoda_rg_lead_detail: Data: 2.52MB + Index: 7.06MB + Engine InnoDB
wp_33uxxoda_rg_lead_detail_long: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_termmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_33uxxoda_terms: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_33uxxoda_term_relationships: Data: 2.52MB + Index: 2.36MB + Engine InnoDB
wp_33uxxoda_term_taxonomy: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_33uxxoda_usermeta: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wp_33uxxoda_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_33uxxoda_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_33uxxoda_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_33uxxoda_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_wc_product_attributes_lookup: Data: 2.50MB + Index: 2.36MB + Engine InnoDB
wp_33uxxoda_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wc_product_meta_lookup: Data: 0.33MB + Index: 0.61MB + Engine InnoDB
wp_33uxxoda_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_wfConfig: Data: 4.42MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfFileMods: Data: 40.58MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfHits: Data: 4.02MB + Index: 0.23MB + Engine InnoDB
wp_33uxxoda_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wfIssues: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_33uxxoda_wfKnownFileList: Data: 17.52MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfLogins: Data: 0.44MB + Index: 0.16MB + Engine InnoDB
wp_33uxxoda_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfNotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfPendingIssues: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_33uxxoda_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfSecurityEvents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_33uxxoda_wfStatus: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_33uxxoda_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfwafconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wfWafFailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_WP_SEO_404_links: Data: 170.67MB + Index: 190.00MB + Engine InnoDB
wp_33uxxoda_WP_SEO_Cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_WP_SEO_Redirection: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_WP_SEO_Redirection_LOG: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wsal_metadata: Data: 11.52MB + Index: 20.09MB + Engine InnoDB
wp_33uxxoda_wsal_occurrences: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
wp_33uxxoda_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_33uxxoda_yarpp_related_cache: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_33uxxoda_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_yoast_indexable: Data: 4.52MB + Index: 7.05MB + Engine InnoDB
wp_33uxxoda_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_33uxxoda_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_33uxxoda_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_33uxxoda_yoast_prominent_words: Data: 0.20MB + Index: 0.48MB + Engine InnoDB
wp_33uxxoda_yoast_seo_links: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_33uxxoda_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 1
acf-field: 7
acf-field-group: 4
attachment: 179978
custom_css: 1
fh_slides: 3
fh_team_member: 1
hs-action: 25
nav_menu_item: 10
oembed_cache: 113
page: 74
post: 226
product: 356
product_variation: 2
review: 16
revision: 27
rv_resources: 28
vc_grid_item: 3
vc4_templates: 3
wp_global_styles: 1
wpgae_click_event: 28
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (60) ###

Gravity Forms: by Gravity Forms – 2.7.14
LayerSlider WP: by Kreatura Media – 5.0.2
Advanced Custom Fields PRO: by WP Engine – 6.2.1.1
WP Engine Smart Plugin Manager: by WP Engine – 5.17.27
BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce (Premium): by Pagup – 1.4.7.2
Cache Enabler: by KeyCDN – 1.8.13
CalculatorPro Calculators: by jgadbois – 1.1.7
Category Tag Pages: by Marzio Carro – 1.0
FH Custom Fields Revisions: by Marek Vavrecan (vavrecan@gmail.com) – 1.3
Custom Sidebars: by WPMU DEV – 3.1.6
Custom Taxonomy Order: by Marcel Pol – 3.4.4
Display Widgets: by Strategy11 – 2.7
Disqus for WordPress: by Disqus – 3.0.23
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
FeedWordPress: by C. Johnson – 2022.0222
FH Browser Check: by Flying Hippo – 1.0
FH Featured Post: by Flying Hippo – 1.0.1
FH AJAX Pagination: by Flying Hippo – 1.0.5
FH React Archives: by Flying Hippo – 2.1
FH React WooCommerce: by Flying Hippo – 1.0
FH Related Posts: by Flying Hippo – 5.1.0
FH Reviews: by Flying Hippo – 1.1
FH Utilities: by Flying Hippo – 1.2
GLRV XML Feed (FH Customized): by Mudd Advertising – 1.0.1
Goal Tracker: by pinewise – 1.0.13
Gravity Forms Math Captcha: by Mandi Wise – 1.0.1
Header and Footer Scripts: by Digital Liberation – 2.2.1
iframe: by webvitaly – 4.6
WPBakery Page Builder: by Michael M - WPBakery.com – 7.0
Members: by MemberPress – 3.2.7
Metal: by David Woolf – 1.5.11
Official Add to Homescreen: by Matteo Spinelli – 1.1.3
SOGO Add Script Header Footer: by orenhav (SOGO) – 3.9
Quick Page/Post Redirect Plugin: by anadnet – 5.2.3
Rich Text Tags, Categories, and Taxonomies: by Katz Web Services
Inc. – 1.8

Webster RV PDF: by TargetClick Powered By Mudd – 1.0.0
WooCommerce Webster RV: by TargetClick Powered By Mudd – 1.0.0
SEO Redirection: by wp-buy – 9.5
Simple Custom CSS: by John Regan – 4.0.6
Code Embed: by David Artiss – 2.3.5
Simple Page Ordering: by 10up – 2.5.1
User Switching: by John Blackbourn & contributors – 1.7.0
CTX Feed: by WebAppick – 6.0.8
WooCommerce MSRP Pricing: by Lee Willis – 1.5
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.0.4
WooCommerce Video Product Tab - FH Customized: by Sebs Studio – 2.3.1
WooCommerce: by Automattic – 8.1.1
Wordfence Security: by Wordfence – 7.10.3
WordPress Importer: by wordpressdotorg – 0.8.1
Yoast SEO Premium: by Team Yoast – 21.1
Yoast SEO: by Team Yoast – 21.2
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
Math Captcha: by dFactory – 1.2.10
WP Robots Txt: by George Pattihis – 1.2
WP Activity Log: by WP White Security – 4.5.3
WP SEO Structured Data Schema Pro: by WPSEMPlugins – 1.4.6
WPMU DEV Dashboard: by WPMU DEV – 4.11.21
YITH WooCommerce Compare: by YITH – 2.31.0
YITH WooCommerce Wishlist: by Your Inspiration Themes (customized by Flying Hippo) – 999

### Inactive Plugins (18) ###

Auto Featured Image (Auto Post Thumbnail): by Creative Motion <support@cm-wp.com> – 3.9.18
Better Search Replace: by WP Engine – 1.4.3
Better WordPress Minify: by Khang Minh – 1.3.3
Disable Gutenberg: by Jeff Starr – 3.0
ElasticPress: by 10up – 4.7.1
Enhanced Media Library: by wpUXsolutions – 2.8.9
FH Site Admin: by Flying Hippo Web Creations – 1.0
FH Site Maintenance: by Flying Hippo – 0.0.5
FH Staff Directory: by Flying Hippo – 1.0.0
Get Permalink: by Justin Tadlock – 0.1
Gravity Forms Zapier Add-on: by rocketgenius – 2.1
IM8 Box Hide: by intermedi8 – 2.4.1
Image Watermark: by dFactory – 1.7.3
Lock Pages: by Steve Taylor – 0.3.1
WooCommerce - Store Exporter: by Visser Labs – 2.7.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WooCommerce Product CSV Import Suite: by Mike Jolley / WooThemes – 1.9.15
WP Ultimate CSV Importer: by Smackcoders – 7.9.10.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (7) ###

fh-developers-custom-fields.php: by  –
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
Stage Fright: by Flying Hippo – 1.2
WP Engine Cache Plugin: by WP Engine – 1.1.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.0.11
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Webster City RV
Version: 2.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: webster-city-rv/woocommerce/archive-product.php
webster-city-rv/woocommerce/global/breadcrumb.php
webster-city-rv/woocommerce/single-product/price.php
webster-city-rv/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-21 19:44:18 -05:00
Options: ✔
Notes: 180
Onboarding: completed

### Action Scheduler ###

Complete: 29,985
Oldest: 2023-08-20 20:23:26 -0500
Newest: 2023-09-20 15:49:57 -0500

Pending: 2
Oldest: 2023-09-20 15:49:58 -0500
Newest: 2023-09-20 20:36:40 -0500

### Status report information ###

Generated at: 2023-09-20 15:50:00 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rwkyyy** [comment]
I am also getting this error in 7.9.0

LE: Apparently it got fixed in 8.3.0
https://github.com/woocommerce/woocommerce/blob/8.3.0/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L81
