### ISSUE TITLE
[Customize Your Store] Intro page when task is completed

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#40327]
## User Story
As a new merchant, I want to be presented with simple flows to customize my store, so that I can start selling sooner.

## Design

Mrk6SERPZ4KrFHSjM0a8TK-fi-3913%3A288836

## Acceptance Criteria

```
Feature: Customize Your Store Intro page when the task is completed

  Scenario: Theme is generated by AI and choose "Customize"
    Given the Customize Your Store Task is completed and custom theme is generated by AI
    Then it should display `Customize your custom theme` banner
    When the User presses the "Customize" button
    Then proceed to the assembler hub

  Scenario: Theme is generated by AI and choose "Customize"
    Given the Customize Your Store Task is completed and custom theme is generated by AI
    When the User presses the "Create a new one" button
    Then pop up `Are you sure you want to start over?` modal Mrk6SERPZ4KrFHSjM0a8TK-fi-3616%3A278871
    When the User presses the "Start again'
    Then proceed to the AI wizard

  Scenario: Theme is NOT generated by AI and choose "Design with AI"
    Given the Customize Your Store Task is completed and custom theme is NOT generated by AI
    When the User presses the "Design with AI" button
    Then pop up `Are you sure you want to start a new design?` modal Mrk6SERPZ4KrFHSjM0a8TK-fi-3616%3A278871
    When the User presses the "Start again'
    Then proceed to the AI wizard
```

**Comment by rjchow** [comment]
How do we detect whether the AI generated theme is being used?

After some thinking, the most obvious way to me is to query the `woocommerce_customize_store_ai_suggestions` option and then re-run the code [here](https://github.com/woocommerce/woocommerce/blob/0091fada88e4c305ea80f7c4b86e2d420b757e87/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L291) and [here](https://github.com/woocommerce/woocommerce/blob/0091fada88e4c305ea80f7c4b86e2d420b757e87/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L248) to generate the parameters and match it against the entity records for `globalStyles` and `currentTemplate.type` to see if they are identical?

**Comment by chihsuan** [comment]
> How do we detect whether the AI generated theme is being used?

> After some thinking, the most obvious way to me is to query the woocommerce_customize_store_ai_suggestions option and then re-run the code [here](https://github.com/woocommerce/woocommerce/blob/0091fada88e4c305ea80f7c4b86e2d420b757e87/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L291) and [here](https://github.com/woocommerce/woocommerce/blob/0091fada88e4c305ea80f7c4b86e2d420b757e87/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L248) to generate the parameters and match it against the entity records for globalStyles and currentTemplate.type to see if they are identical?

That sounds good to me! Another way I thought of is to set a flag when a theme is generated and then clear that flag when after theme is switched.

**Comment by rjchow** [comment]
Depending on the definition of 'ai generated theme', I think my proposed solution for recomputing the params won't cut it.

If the definition is "purely what was generated without any modifications in site-assembler" then yea it would work, but I don't think that's the case? I assume it would include the mods too?

My next approach would be to save the current template ID in an option upon finishing customization, then comparing that inside `fetchIntroData` to see if it's changed. Would that work?

**Comment by chihsuan** [comment]
> If the definition is "purely what was generated without any modifications in site-assembler" then yea it would work, but I don't think that's the case? I assume it would include the mods too?

> My next approach would be to save the current template ID in an option upon finishing customization, then comparing that inside fetchIntroData to see if it's changed. Would that work?

Yeah, I think that would work. 👍
