### ISSUE TITLE
Extreme CPU bottleneck from product-details-listing.php

### ISSUE THREAD

**Issue by paulcee** [woothemes/woocommerce#40325]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hey guys. Thanks for your nice shop product. BUT: my client experienced some total horror in the last two days (I guess this must have been a Woo update) where our Apache server would stall within MINUTES of rebooting the machine. The symptom was running out of MaxRequestWorkers (Apache setting), but the actual problem was WooCommerce. Specifically, let me share one example of a stack trace:

[19-Sep-2023 14:21:15 UTC] WordPress database error Server shutdown in progress for query 
SELECT   wp_n9qwinposts.ID
FROM wp_n9qwinposts  LEFT JOIN wp_n9qwinterm_relationships ON (wp_n9qwinposts.ID = wp_n9qwinterm_relationships.object_id)
WHERE 1=1  AND ( 
  wp_n9qwinterm_relationships.term_taxonomy_id IN (2,3,4,5)
) AND wp_n9qwinposts.post_type = 'product' AND ((wp_n9qwinposts.post_status = 'publish'))
GROUP BY wp_n9qwinposts.ID
ORDER BY wp_n9qwinposts.post_date DESC
LIMIT 0, 1
made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Blocks\BlockPatterns->register_block_patterns, include('/plugins/woo-gutenberg-products-block/patterns/product-details-listing.php'), WC_Product_Query->get_products, WC_Data_Store->__call, WC_Product_Data_Store_CPT->query, WP_Query->__construct, WP_Query->query, WP_Query->get_posts

We have a very large shop (about 60,000 or 70,000 images) -- however, it was never a problem before. What I discovered was that this "product-details-listing.php" seemed to be generating some VERY expensive queries, even though we weren't using it (lol? is it some kind of Gutenberg "block"?) -- I want to report this, because it's the kind of issue that might accidentally not cause any harm on a small shop (100 products), but it literally KILLED our server. And we aren't even using your Gutenberg block. So you see the problem. It took me about four hours to work out the problem -- digging through various Linux and MySQL logs. I partly wonder why the hell you are running this query on every page load (???) or, if not, why you are running it at all, when we aren't using your Gutenberg block. I think at the very least there is some sort of performance bottleneck problem here -- and it's even worse if you're running code we don't need to run.

Thanks for listening. -- a British nonprofit charity who lost half a day over this.

### Expected behavior

We expect to be able to run our WordPress site on a Linux/Apache environment without too much pain.

### Actual behavior

Actually (as described above) if we run your latest Woo release, the site becomes inaccessible (timeouts) within about two minutes, even after a reboot.  I have tried to debug this, and I am pretty sure that my explanation above says where the problem is. -- By the way, our temporary workaround is commenting out some PHP code in product-details-listing.php  (replacing array(...) with empty array) -- clearly the next update will stomp over this.

### Steps to reproduce

I can't create steps because I would have to set up a new test WordPress, I apologise, but I don't have time.
However: if you set up a large shop like ours (let's say, 70,000 products, with images and metadata), I think you are gonna see the same problem. -- Remember, it's product-details-listing.php, that's a quite short piece of code (yours) and you can trace that API call.

### WordPress Environment

Latest WordPress, kept up to date
Running on CentOS Linux

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
I'm sorry that you are having some issues. 

I tried on a store with 19000 products and I didn't have any issue. Could you share some steps to reproduce this issue?

**Comment by gigitux** [comment]
Also, we are updating how we retrive the product. Most probably, it should fix your issue: https://github.com/woocommerce/woocommerce-blocks/pull/11138

**Comment by gigitux** [comment]
Now that the pull request https://github.com/woocommerce/woocommerce-blocks/pull/11138 has successfully merged, I'd like to invite you to test the upcoming build. Please share your experience and let us know if the issue you encountered has been resolved. At this moment, I will proceed to close the issue. If you have any feedback, don't hesitate to provide it, and we will promptly reopen the issue for further discussion.
