### ISSUE TITLE
HPOS Problem when Taking Control of Orders

### ISSUE THREAD

**Issue by Sn00z389** [woothemes/woocommerce#40331]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There seems to be a problem when one user is editing an order and another one is trying to take over the control.

The problem is only presented with HPOS enabled.

The system just trows a go back text and does not take over the control by the user who is trying to do so.

### Expected behavior

The control must be taken by the admin that is trying to get it.

### Actual behavior

The control is not being taken by the admin.

### Steps to reproduce

1. Turn HPOS on without compatibility mode
2. Go to Orders tab with one admin account
3. Start editing an order
4. Try to take control with another admin account for this order

### WordPress Environment

Wordpress 6.3.1
Woocommerce 8.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
@Sn00z389 thank you for reporting. I'm able to reproduce this on `trunk`. Here's a video: 

https://github.com/woocommerce/woocommerce/assets/23619/3b9d8ffc-8db5-4421-8c40-db38d3532838

The issue is not present with HPOS disabled. 

For now I've assigned `priority: low` as there doesn't seem to be a risk of systematic data loss or a feature becoming unaccessible.

**Comment by Sn00z389** [comment]
Yes, still very frustrating and must be fixed when HPOS becomes the "new normal" :)
