### ISSUE TITLE
Display an alert icon for variations that contains "any" values

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40346]
We don't plan to support the "any" variation values in the new product editing experience. However, some users may already have them in their products, so we must find a way to handle them. I thought we'd show an alert icon and display additional text on hover. If such a variation is deleted, users won't be able to add it back.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-1639_217612

**Acceptance criteria**
- [ ] When the variation contains at least 1 "any" value, we display the red alert icon on the left side of the table.
- [ ] When clicked, we show a popover with a link to docs [link TBD]

**Comment by nathanss** [comment]
If there is no term from a particular attribute, it is considered "any" (that's how we can detect it on the front end)
