### ISSUE TITLE
Enable inline actions in the variations table

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40351]
We want to give merchants as much flexibility as possible when it comes to editing variation details. Let's enable them to change prices and stock directly from within the table. This may come in handy for quick updates and elevate the overall user experience (also aligning it with WP core's new direction).

**Design (temporary link)**
AkVNGImLgSqCObTQ3idVn7-fi-7048_441807

<img width="418" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/3706735a-7836-4434-a51f-d1852ded11f5">

**Acceptance criteria**

- [ ] Image, Prices (the whole element, regular price + sale price) and Stock are buttons. Clicking each opens a popover with contextual options.
- [x] Image (estimation: 3)
   - [x] User can click the rectangle with the + icon to reveal options.
   - [x] Upload -> Opens the system file picker
   - [x] Media library -> Opens the library
   - [x] <s>Openverse -> Opens the Openverse browser (nice to have)</s>
   - [x] When the image is being uploaded, we show a spinner inside the rectangle (same as in the Images section in the General tab).
   - [x] When an image exists, clicking it will reveal the same options. Uploading or choosing a new image will replace the old one.
   - [x] We don't show the "1 variation updated" snackbar after adding/editing an image.
- [x] Prices (We should consider the extensibility limitations. Estimation: 3)
   - [x] User can click the price to reveal options.
   - [x] User can enter regular price and sale in the fields.
   - [x] We validate the pricing fields the same as in the main product form.
   - [x] User can click Cancel to discard changes.
   - [x] User can click Save to apply changes. We show the "1 variation updated" snackbar.
   - [x] If the sale price is higher than the regular price, an error message should be shown.
- [x] Stock (estimation: 3)
   - [x] User can click the stock status/quantity to reveal options.
   - [x] User can flip the "Track inventory" toggle to enable inventory tracking for this variation.
   - [x] When inventory tracking is enabled, user can enter available quantity.
   - [x] When inventory tracking is disabled, user can select a stock status.
   - [x] We validate the quantity field the same as in the main product form.
   - [x] User can click Cancel to discard changes.
   - [x] User can click Save to apply changes. We show the "1 variation updated" snackbar.
- [ ] User can only open 1 editing window at a time (when they click another without closing the previous one, we close it for them).

**Comment by louwie17** [comment]
@j111q I blocked this issue for now, and just wanted to push this past you again to see if the design still aligns with your vision around this. As I know we semi recently talked about this in Slack after some community feedback.

**Comment by pmcpinto** [comment]
@j111q can you double-check the acceptance criteria? We want to include this in the next cycle. Thanks

**Comment by j111q** [comment]
Double checked ✅ I added one AC around the error state for the Sale price so it matches the Pricing tab. 
<img width="637" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/fbfcc668-c4a7-4acb-ada2-40871b5b473a">


I tidied up the Figma file as well a bit (just updating components) but all other ACs are the same. Thanks for checking! 🙏
