### ISSUE TITLE
[Enhancement]: Sugerencia de mejora para la generación de productos no variables

### ISSUE THREAD

**Issue by Camille-Lopez** [woothemes/woocommerce#40354]
### Describe the solution you'd like

Al querer crear un producto que no es de tipo variable sigue apareciendo la pestaña de atributos, la cual permite crear atributos pero no generar las variaciones para personalizar justamente por no ser un producto variable. Dependiendo del tipo de producto algunas pestañas se deshabilitan ya que no tienen función alguna para no confundir al administrador del panel, pero la pestaña de atributos es constante a pesar de que solo es funcional en el tipo variable. Lo ideal sería que esta pestaña también se habilitara únicamente en el tipo de producto en el que es funcional para no dar lugar a confusiones.

**Comment by rrennick** [comment]
Hi @Camille-Lopez, I used Google Translate to translate your issue description:

> When you want to create a product that is not of a variable type, the attributes tab continues to appear, which allows you to create attributes but not generate the variations to customize precisely because it is not a variable product. Depending on the type of product, some tabs are disabled since they have no function so as not to confuse the panel administrator, but the attributes tab is constant even though it is only functional in the variable type. Ideally, this tab would also only be enabled on the type of product for which it is functional to avoid confusion.

Attributes can be used with non-variable products. I have provided screenshots below. I'll close this as a question.

<img width="992" alt="Screenshot 2023-09-27 at 4 21 09 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/2c43c5b0-6532-4883-9725-357ad60b21fe">
<img width="1334" alt="Screenshot 2023-09-27 at 4 20 54 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/ac2572a6-bd7e-4cad-a8fb-a538d6be9315">
