### ISSUE TITLE
Leaving flat rate cost empty removes shipping method from rates array

### ISSUE THREAD

**Issue by UVLabs** [woothemes/woocommerce#40360]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a flat rate shipping method has a cost thats empty/blank like this:

<img width="1037" alt="image" src="https://github.com/woocommerce/woocommerce/assets/10324144/26227333-9f4c-4649-87b5-334f8bdf164f">

That shipping rate isn't present inside the rates array. So if you try to use the filter `woocommerce_package_rates` the shipping method isn't available:

<img width="558" alt="image" src="https://github.com/woocommerce/woocommerce/assets/10324144/e000bc7b-8217-478f-b37c-57b5a47d78d0">

With any other value, it shows up in the rates array. This includes "0":

<img width="576" alt="image" src="https://github.com/woocommerce/woocommerce/assets/10324144/3be72917-db5f-4887-9eaf-fe6ad94d441c">

### Expected behavior

The shipping method should still show inside the shipping rates, a blank flat rate cost should be synonymous with "0".

### Actual behavior

The shipping method is not present in the rates array if the cost is blank/empty

### Steps to reproduce

1) Create a shipping zone
2) Create a flat rate shipping method inside that zone and empty the cost field (make it blank)
3) Use the `woocommerce_package_rates` filter and check the `rates` array, you will see that it doesn't contain your created shipping method.
4) Edit the shipping method and now set the cost shipping cost as `0`, you will now see the shipping method show inside the rates array.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@UVLabs Could you provide a use case where using the free shipping rate does not work?
