### ISSUE TITLE
 Post tables and HPOS not fully synchronising

### ISSUE THREAD

**Issue by CameronD73** [woothemes/woocommerce#40364]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

followup from issue #40236
With sync enabled,  some important parameters are not updated during sync.

This seem to occur with either HPOS or Post tables as authoritative, but worse in the latter case. I have switched between auth settings at various times keeping the site up because of various bugs.

I have identified in the current state:
###  column errors
__billing_email_: 4 counts - look like "correct" values are in hpos tables - they were all recently updated.
__recorded_coupon_usage_counts_ : 1 count post false, hpos true. I don't use coupons so I have no idea.
__download_permissions_granted_ : count 1 - post true, hpos false.  Likewise we don't use this at all, so have no idea when or why it changed.

### meta_key errors
"__completed_date_" :  93 counts - one or other is blank.  Curiously, all the dates before April this year only have a value in the hpos table, even though we had not activated hpos at that stage.
"__edit_lock_" :  51 counts
"__paid_date_" : 91 counts (usually the same order ID as completed-date error. Same symptom
"**__schedule_next_payment_**" : This is the crucial one for us. There were one or two more, but if I went to the subscription edit page and adjusted the next payment date by one minute, then the hpos table got updated.  I will need to investigate these a bit further and report back.
"__shipping_address_index_" : 61 counts - the hpos value is empty string, while posts table is just a string of 9 spaces.  We have shipping address disabled, so don't really care.
"__subscription_renewal_order_ids_cache_" :  14 counts - usually one has "a:0{}", but two instances have the post table missing the latest  renewal
"__subscription_resubscribe_order_ids_cache_" : 5 counts - posts  has  "a:0{}", while hpos is blank
"__subscription_switch_order_ids_cache_" :  2 counts - same as line above

### Expected behavior

When the system tells me that the tables are in sync, then they should be.

### Actual behavior

each day the output of ` wp wc cot  verify_cot_data ` increases in size.

Many of these may be somewhat transient (such as "_edit_lock" ?) , but in that case the code should not list them as an error.

### Steps to reproduce

1. wait for a few days after activating HPOS.
2. run ` wp wc cot  verify_cot_data 2>sync_errors.txt`
3. tediously identify problem values, perhaps start with `grep -E 'column|meta_key' sync_errors.txt | sort | uniq`

### WordPress Environment

See  #40236

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by CameronD73** [comment]
the errors where _**_schedule_next_payment**_ was not being updated happened after I set post tables as auth as a workaround for the bug in issue #40236.
Each customer had selected early renewal of their subscription _after_ the post tables were set auth. There were different payment methods - paypal or BACS.

The _completed_date and _paid_date entries all apply to IDs that are orders rather than subscriptions.

**Comment by jorgeatorres** [comment]
Hi @CameronD73!

Thanks again for the report. Just wanted to give you an update.

Even though most of the issues you've found are with Subscriptions plugin (and thus should not core's), I've contacted the Subscriptions team with your findings and the discrepancies should be addressed in an upcoming version. If you're still seeing issues with Subscriptions, I'd suggest getting in touch with Subscriptions support as the plugin should be HPOS-compatible, but there might still be a few wrinkles to iron out.

As for the issues with metadata/properties in core, we've submitted fixes for those. They should go out with 8.2. That won't retroactively address missing data (such as for the billing/shipping address indexes) but will make sure new orders have the data right. In any case, empty indexes are safe to ignore (as you yourself have guessed). Even data such as `_paid_date` can be ignored as that's a deprecated metadata that neither HPOS nor posts really use (but posts still sets). The version of the verification tool in 8.2 will ignore that.

We're also working on other improvements to make the verification tool more robust overall.

**Comment by CameronD73** [comment]
Thanks for the update.
It is not always obvious to me what is core and what is subscriptions, so I am glad you have organised that.
I did have contact with subscriptions support on another bug and pointed them to this issue, to explain why their suggestion of switching back to Posts as auth was not a good idea.

**Comment by jorgeatorres** [comment]
@CameronD73: No worries. I've asked the Subscriptions team to double check that things are working ok, particularly in relation with the metadata keys you've indicated above as problematic.

In the meantime, I'm going to close this issue as the core part of the report has been addressed. Feel free to re-open or create a new one if I've missed something.
