### ISSUE TITLE
Add menu item to publish button to schedule product updates

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40376]
In the current experience, users can schedule when a product is published. We must add it to the new one to achieve feature parity and support existing products. Part of this task is already handled by https://github.com/woocommerce/woocommerce/issues/40371, but we need a dedicated flow for setting up and editing scheduled posts in the form.

**Design (temporary link)**
AkVNGImLgSqCObTQ3idVn7-fi-3427_305029

<img width="531" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/bd10279b-af99-444a-a2b1-9adc18b0b146">
<img width="1105" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/cd96bf51-d560-4124-a6ea-03af00b572af">

**Acceptance criteria**

- [x] We add `Schedule publish` to the `More actions` menu in the new `Publish` button (https://github.com/woocommerce/woocommerce/issues/40374).
- [x] When clicked, it opens a new modal where the user can select the date and time when the product will be published. It is the same component we use for scheduling sales.
- [x] The calendar format and layout respect the store’s locale settings.
- [x] The date defaults to today's date. The time is set to current time + 2 hours.
- [x] Clicking `Now` resets the time and date. When the user clicks `Save` without changing the time and date, or after they click `Now`, we treat the product as not scheduled.
- [x] When the user clicks `Save`, we show a snackbar notification that reads: `Product scheduled for [date][time]. Edit`. The Edit button re-opens the `Schedule` modal.
- [x] The add button in the top right corner changes to `Schedule` (the product is saved as draft and set to be published).
- [x] When the user clicks the arrow in the split button and reveals the menu:
   - [x] Edit schedule time -> Opens the schedule modal. We also show the selected date and time as the button's description.
 - [x] When the user clicks `Schedule` button -> Also opens the schedule modal.

**Comment by j111q** [comment]
Updated the main issue ☝️ to add some tweaks after feedback from @louwie17.
