### ISSUE TITLE
Product Add-ons: Number of Fields Allowed

### ISSUE THREAD

**Issue by lemjunsan630** [woothemes/woocommerce#40385]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**### Product Add-ons: $4.92Per month / month... 
Hi good day Woocommerce,

I have like a total of 22 add-on fields in a product and I can only add 15 of them and when I added the rest and Update it, It will not be saved and it keeps on deleting the records. It says that the add-ons feature has unlimited add-ons. How do I fix this? Is there a limit to the number of fields used on the add-ons?

Attached are photos of the fields(1st pic) and the result of the rest of the field that wont save its values(2nd pic):**

<img width="831" alt="saved_fields" src="https://github.com/woocommerce/woocommerce/assets/42336323/72eff721-96e7-4666-b68e-f8331b783828">
<img width="637" alt="unsaved_fields" src="https://github.com/woocommerce/woocommerce/assets/42336323/99e524fa-fe40-4f69-b2f1-55fcc55be9cd">

**Comment by rrennick** [comment]
Hi @lemjunsan630 , We do not provide support for WooCommerce extensions in this repo. I'll mark this as a supprt request which will add a comment with instructions.
