### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by vihertukku** [woothemes/woocommerce#40387]
### Describe the solution you'd like

Woocommerce is online sales platform.
Woocommerce should automatically add the company/sellers details into the emails when the email is sent to the customer after sale. So all the company name, address, and also registration number if its been added to the seller details. So basically the email ofter order would be like legal invoice when it includes those details. Now every user needs to add those details to email section and customise the email they send.

### Additional context

Automatic invoice email for customers including sellers name, address, and details....

**Comment by rrennick** [comment]
@vihertukku This sounds like it might be an enhancement request for a WooCommerce extension. I'll mark this as a support request which with post instructions on contacting support.
