### ISSUE TITLE
"Pointer-events: none" in produts doesnt let me cick to edit categories

### ISSUE THREAD

**Issue by JPbjj** [woothemes/woocommerce#40381]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The propriety "Pointer-events: none" in "div class :name" on Produts doesnt let me cick to edit categories i dont know if is a bug or not, but with the Devtools I unchecked the box and only that way I could edit.

### Expected behavior

The pointer should appear when I hover the options to edit categories

### Actual behavior

The pointer doesnt appear when I hover the options to edit categories

### Steps to reproduce

1. Go to prodcuts category
2. Have a category listed
3. Hover to edit, quick edit or see
4. Wont work

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://suplementosfp.com.br
Site address (URL): http://suplementosfp.com.br
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.22
PHP Post Max Size: 2 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Tamanho total do banco de dados: 6.41MB
Tamanho dos dados do banco de dados: 4.56MB
Tamanho do índice do banco de dado: 1.85MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_e_events: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_litespeed_url: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_litespeed_url_file: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_options: Dados: 3.44MB + Índex: 0.08MB + mecanismo InnoDB
wp_postmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_posts: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_orders: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_wc_orders_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_addresses: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_operational_data: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_attributes_lookup: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_download_directories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_rate_limits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 1
elementor_library: 1
page: 5
post: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Elementor: por Elementor.com – 3.16.4
IA Assistente da Hostinger: por Hostinger – 1.4.3
Hostinger: por Hostinger – 1.7.2
LiteSpeed Cache: por LiteSpeed Technologies – 5.6
Pinterest para WooCommerce: por WooCommerce – 1.3.10
WooCommerce: por Automattic – 8.1.1

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: por Automattic - Anti-spam Team – 5.3
Hello Dolly: por Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base da loja: #23 - /loja/
Carrinho: #24 - /carrinho/
Finalização de compra: #25 - /finalizar-compra/
Minha conta: #26 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Hello Elementor
Version: 2.8.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-23 00:14:19 -03:00
Options: ✔
Notes: 62
Onboarding: completed

### Action Scheduler ###

Concluído: 9
Oldest: 2023-09-21 21:26:49 -0300
Newest: 2023-09-22 17:48:28 -0300

Pendente: 3
Oldest: 2023-09-22 18:48:28 -0300
Newest: 2023-09-22 21:59:51 -0300

### Status report information ###

Generated at: 2023-09-22 18:10:44 -03:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> The propriety "Pointer-events: none" in "div class :name" on Produts doesnt let me cick to edit categories i dont know if is a bug or not, but with the Devtools I unchecked the box and only that way I could edit.

@JPbjj Could you provide a screenshot of the CSS in your developer console? The hover event works fine in my dev install

<img width="346" alt="Screenshot 2023-09-27 at 4 28 12 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/4009cdac-95c2-4c02-b7d5-2708c8104ef5">

**Comment by JPbjj** [comment]
Yes, I can. Sorry for the delay
file:///home/jp/Imagens/Screenshot%20from%202023-10-01%2023-11-02.png

**Comment by JPbjj** [comment]
Yes, I can. Sorry for the delay
![Screenshot from 2023-10-01 23-11-02](https://github.com/woocommerce/woocommerce/assets/82000265/acb12f6f-8860-4b12-a325-a2cd396ec5a5)
![Screenshot from 2023-10-01 23-16-35](https://github.com/woocommerce/woocommerce/assets/82000265/a2a7b16f-02a8-4041-9fec-665798e04732)

**Comment by barryhughes** [comment]
Thanks, @JPbjj.

We were hoping to see the CSS rules that are being applied, via your browser's developer console. Again, we are unable to replicate on our side.

> - [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> - [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
> - [ ] I can reproduce this bug consistently using the steps above.

Can I also just confirm you ran through these steps?

**Comment by JPbjj** [comment]
Good night, thanks for the support. So in this first img I have the propriety pointer even checked and cant edit.
![Screenshot from 2023-10-03 20-41-27](https://github.com/woocommerce/woocommerce/assets/82000265/09f20dcf-c0fe-46cb-b448-5352b9f1490f)

However when I uncheck the box I can acess the editing tools.
![Screenshot from 2023-10-03 20-42-11](https://github.com/woocommerce/woocommerce/assets/82000265/7b21ef27-5a0c-408d-98da-b9187f3200bb)

**Comment by coreymckrill** [comment]
Hi @JPbjj, from your screenshots, it does look like you have some extensions active that are modifying the behavior of that particular screen. Given that we haven't been able to replicate the issue using a test install of just WooCommerce, it seems quite possible this problem is due to one of those extensions. What happens if you temporarily disable all the other extensions besides WooCommerce?

**Comment by JPbjj** [comment]
So I disable some extensions from Chrome and found out that the Color Finder extension was cause the issue for some reason. 
It works out perfectly now, thanks for the help.
