### ISSUE TITLE
[CYS] Remove SMB and Large business logic from the AI wizard

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#40426]
**Issue Description:**

p2: pdnLyh-4it-p2

We've decided to remove the logic for different layouts to simplify the MVP scope

See also p1695643189905859/1695637849.236469-slack-C01SFMVEYAK

**Comment by moon0326** [comment]
@chihsuan Do we want to set one of the six templates as a default homepage template? Or should we leave it empty and let users choose one?

**Comment by chihsuan** [comment]
> @chihsuan Do we want to set one of the six templates as a default homepage template? Or should we leave it empty and let users choose one?

Hey @moon0326, Good question! We want to set one of the six templates as a default homepage template. Let's set the first template as default for now. 🙂

**Comment by moon0326** [comment]
> Hey @moon0326, Good question! We want to set one of the six templates as a default homepage template. Let's set the first template as default for now. 🙂

Thanks! I'll make the change in the PR.
