### ISSUE TITLE
WooSubscriptionNotes has incorrect usage of `continue`, it should use `break` instead.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#40455]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in 7085329-zen.

In the following line https://github.com/woocommerce/woocommerce/blob/60c4807/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php#L296, we are using `continue` statement. However, just in the previous line, we have set the `$note` to false, so in cases where the count of `$bump_thresholds` is more than one, then in the second iteration of the loop, the line `$note->delete();` will result in an error, because it would have been set to false in the previous iteration of the loop.

Stack trace for the error:

```log
/var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:321
Stack trace:
#0 /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php(467): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->add_or_update_subscription_expiring()
#1 /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php(109): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->refresh_subscription_notes()
#2 /var/www/redacted/www/wp-includes/class-wp-hook.php(310): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->admin_head()
#3 /var/www/redacted/www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 /var/www/redacted/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /var/www/redacted/www/wp-admin/admin-header.php(163): do_action()
#6 /var/www/redacted/www/wp-admin/edit.php(407): require_once('/var/www/...')
#7 {main}
thrown i /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php på linje 321
```

### Expected behavior

No errors.

### Actual behavior

There is an error with stack strace as described above in some cases.

### Steps to reproduce

Unfortunately we only have the stack trace, no reliable steps to reproduce.

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by adrianduffell** [comment]
@mcliwanow Is this something Desire can take? 🙏 While Ghidorah maintains the inbox system, we don't normally work on the individual notes.

**Comment by mcliwanow** [comment]
@adrianduffell, I see that we didn't work on this part (at least based on file history) in the past 🤔 We'll see if we can put it into our roadmap in the upcoming weeks. The proposed change seems to be straightforward enough and makes sense.

**Comment by adrianduffell** [comment]
@mcliwanow That's great, thank you! Let me know if any questions pop up about it!

**Comment by andfinally** [comment]
We could use `break` instead of `continue`.
