### ISSUE TITLE
Product name field design updates

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40459]
The product name is important, so it makes sense to make it more prominent in the form. It's also an opportunity to add missing functionality and let people mark a product as featured.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-7001_308034

<img width="566" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/6d7799e1-89c6-4424-9740-624d638888aa">

**Acceptance criteria**

- [ ] Product name field has a fixed height of 48 px.
- [ ] Text size (placeholder and input) is 16 px. Gutenberg-700 for the placeholder, Gutenberg-900 for the input text.
- [x] We add a star icon button on the right side of the field.
- [x] Hovering over it changes the cursor to `pointer` and reveals a tooltip reading: Mark as featured.
- [x] When inactive, the icon's color is Gutenberg-600. It changes to accent/primary color on hover.
- [x] When active, the icon changes from `starEmpty` to `starFilled` and takes on the accent/primary color.
- [x] The user can click the icon button again to deactivate it.
- [x] Clicking the icon button marks the product as featured, the same as in the current UX.

**Comment by mdperez86** [comment]
@pmcpinto @j111q this issues was partially covered in https://github.com/woocommerce/woocommerce/issues/39679

**Comment by pmcpinto** [comment]
> @pmcpinto @j111q this issues was partially covered in https://github.com/woocommerce/woocommerce/issues/39679

@mdperez86 thanks for the heads up. Will that be included in 8.6 or 8.7?

**Comment by mdperez86** [comment]
> > @pmcpinto @j111q this issues was partially covered in #39679
> 
> @mdperez86 thanks for the heads up. Will that be included in 8.6 or 8.7?

It looks like in 8.6

**Comment by pmcpinto** [comment]
👍 thanks for the clarification.

**Comment by pmcpinto** [comment]
Created a new issue with the missing AC: #47478
