### ISSUE TITLE
invalid argument in woocommerce-services.php on checkout

### ISSUE THREAD

**Issue by ExchequerNL** [woothemes/woocommerce#40463]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On checkout there is an abnormal system load and an error is generated in the logs:

`[proxy_fcgi:error] [pid 2141078:tid 139808324069120] [remote x:50185] AH01071: Got error 'PHP message: PHP Warning: Invalid argument supplied for foreach() in /home/x/domains/x.com/private_html/voorstellingen/wp-content/plugins/woocommerce-services/woocommerce-services.php on line 1115', referer: https://www.x.com/voorstellingen/afrekenen/`

Line 1115:
`foreach ( $shipping_rates as $rate ) {`

part of

```
public function track_completed_order( $order_id, $data, $order ) {
			$logger   = $this->get_logger();
			$services = array();
			$packages = WC()->cart->get_shipping_packages();

			foreach ( $packages as $package ) {
				$shipping_methods  = WC()->shipping()->load_shipping_methods( $package );
				$shipping_packages = WC()->shipping()->calculate_shipping_for_package( $package );
				$shipping_rates    = $shipping_packages['rates'];

				$shipping_method_ids = array();
				foreach ( $shipping_rates as $rate ) {
					if ( ! in_array( $rate->method_id, $shipping_method_ids, true ) ) {
						$shipping_method_ids[] = $rate->method_id;
					}
				}

```

### Expected behavior

No invalid argument

### Actual behavior

invalid argument produced on checkout

### Steps to reproduce

Add item to basked
Finalize checkout
Error is generated

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.deschelleboom.nl/voorstellingen
Site address (URL): https://www.deschelleboom.nl/voorstellingen
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 2000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.15-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: giaq_
Totale database grootte: 64.57MB
Database gegevens grootte: 43.87MB
Database index grootte: 20.70MB
giaq_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
giaq_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
giaq_woocommerce_order_items: Data: 0.34MB + Index: 0.11MB + Engine InnoDB
giaq_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
giaq_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
giaq_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_actionscheduler_actions: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
giaq_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_actionscheduler_logs: Data: 0.50MB + Index: 0.30MB + Engine InnoDB
giaq_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_comments: Data: 2.52MB + Index: 1.42MB + Engine InnoDB
giaq_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
giaq_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
giaq_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
giaq_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
giaq_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_options: Data: 7.17MB + Index: 0.11MB + Engine InnoDB
giaq_postmeta: Data: 20.55MB + Index: 11.03MB + Engine InnoDB
giaq_posts: Data: 5.52MB + Index: 1.17MB + Engine InnoDB
giaq_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_term_relationships: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
giaq_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
giaq_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
giaq_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
giaq_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
giaq_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_wc_customer_lookup: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
giaq_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
giaq_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
giaq_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
giaq_wc_order_product_lookup: Data: 0.33MB + Index: 0.30MB + Engine InnoDB
giaq_wc_order_stats: Data: 0.28MB + Index: 0.20MB + Engine InnoDB
giaq_wc_order_tax_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
giaq_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
giaq_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
giaq_wpforms_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
giaq_wpforms_entry_fields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
giaq_wpforms_entry_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
giaq_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
giaq_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
giaq_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 305
elementor_library: 4
nav_menu_item: 3
oembed_cache: 1
page: 21
post: 1
product: 147
revision: 613
seedprod: 1
shop_coupon: 323
shop_order: 2231
shop_order_refund: 8
tc_api_keys: 121
tc_discounts: 2
tc_events: 148
tc_form_fields: 11
tc_forms: 2
tc_orders: 82
tc_seat_charts: 140
tc_templates: 1
tc_tickets: 28
tc_tickets_instances: 5434
wpforms: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Tickera (Premium): door Tickera.com – 3.5.1.6
All-in-One WP Migration File Extension: door ServMask
Inc. – 1.8

All-in-One WP Migration: door ServMask – 7.78
Tickera Bridge for WooCommerce: door Tickera – 1.4.3
Tickera Check-in App Translation: door Tickera.com – 1.1.2
Tickera Check-in Notifications: door Tickera.com – 1.1.7
Checkin apps - redirect to attendee screen: door Tickera – 1.0
Checkinera: door Tickera – 1.3.7
Classic Editor: door WordPress Contributors – 1.6.3
Tickera CSV Export: door Tickera.com – 1.2.7.0
Enable on-hold orders in Checkinera: door Tickera – 1.0
Tickera - Custom Forms: door Tickera.com – 1.2.7
Yoast Duplicate Post: door Enrico Battocchi & Team Yoast – 4.5
Elementor Pro: door Elementor.com – 3.15.1
Elementor: door Elementor.com – 3.16.4
Hide featured image on all single page/post: door TylerTork – 1.0
Jetpack: door Automattic – 12.6.1
Limit Login Attempts Reloaded: door Limit Login Attempts Reloaded – 2.25.25
Tickera Mailchimp: door Tickera.com – 1.4.3
Mollie Payments for WooCommerce: door Mollie – 7.4.0
Tickera Seating Charts: door Tickera.com – 0.80
Tickera - Resend Attendees Emails: door Tickera.com – 1.5
Event Calendar for Tickera: door Tickera.com – 1.3.2
Tickera - Events Listing: door Tickera.com – 1.1.5
Tickera - Event Category List shortcode: door Tickera.com – 1.0
WooCommerce Checkout Field Editor: door WooCommerce – 1.7.10
WooCommerce Shipping & Tax: door WooCommerce – 2.3.5
WooCommerce Store Credit: door Themesquad – 4.4.0
WooCommerce: door Automattic – 8.1.1
WP Fastest Cache: door Emre Vona – 1.1.9
WP Bestandsbeheer: door mndpsingh287 – 7.2
WPForms: door WPForms – 1.8.4

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: door Automattic - Anti-spam Team – 5.3
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: door SeedProd – 6.15.15.3
Mollie for Tickera: door Tickera.com – 1.7
WPForms Lite: door WPForms – 1.8.3.1

### Must Use Plugins (2) ###

Elementor Safe Mode: door Elementor.com – 1.0.0
WordPress automation by Hostdeko Easy Apps: door  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Winkelbasis: #6913 - /winkel/
Winkelwagen: #6914 - /winkelwagen/
Afrekenen: #6915 - /afrekenen/
Mijn account: #6916 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: the7dtchild
Version: 1.0.0
Author URL: http://dream-theme.com/
Child Theme: ✔
Parent Theme Name: The7
Parent Theme Version: 11.9.1
Parent Theme Author URL: https://dream-theme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/cart/mini-cart.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php versie 3.7.0 is verouderd. De hoofdversie is 8.1.0
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-widget-product.php
dt-the7/woocommerce/content-widget-reviews.php
dt-the7-child/woocommerce/emails/customer-completed-order.php
dt-the7-child/woocommerce/emails/customer-invoice.php
dt-the7-child/woocommerce/emails/customer-on-hold-order.php versie 3.7.0 is verouderd. De hoofdversie is 7.3.0
dt-the7-child/woocommerce/emails/customer-processing-order.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php
dt-the7/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-28 08:33:45 +02:00
Options: ✔
Notes: 184
Onboarding: completed

### Action Scheduler ###

Afgerond: 2.094
Oldest: 2023-08-27 15:58:14 +0000
Newest: 2023-09-27 09:58:29 +0000

Mislukt: 67
Oldest: 2022-03-22 13:58:01 +0000
Newest: 2023-09-08 06:22:19 +0000

In afwachting: 7
Oldest: 2023-09-27 13:55:23 +0000
Newest: 2023-10-02 23:11:46 +0000

### Store Credit ###

Prices entered with tax: yes
Show My Account: yes
Delete after use: no
Individual use: no
Include tax: no
Apply to shipping: no
Coupon code format: {coupon_code}
Overrides: dt-the7-child/woocommerce/emails/customer-store-credit.php

### Status report information ###

Generated at: 2023-09-27 14:32:35 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@ExchequerNL Please contact WooCommerce support for extension support. I'll mark this as a supprt request which will post a comment with instructions for contacting support.
