### ISSUE TITLE
is there a way so i can make this in woocommerce ?

### ISSUE THREAD

**Issue by achrafahmadi** [woothemes/woocommerce#40471]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi im using this code so i can embed my website on other website that also mine , but the checkout page have a restriction that cannot appear correctly

Here is the code that im using :
```
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Checkout</title>
  <style>
    body {
      margin: 0;
      background-color: #191C26;
    }

    /* Apply custom styles to iframe based on screen width */
    iframe {
      border: 0; /* Remove the iframe border */
      padding: 0; /* Remove any padding around the iframe */
      width: 100%;
      height: 100%;
    }

    /* Media query for screens with a minimum width of 768px (adjust as needed) */
    @media (min-width: 768px) {
      iframe {
        overflow: auto; /* Add a scroll bar when content overflows on larger screens */
      }
    }
  </style>
</head>
<body>
  <iframe src="https://hostbesto.us/quick-buy/7571/1/"></iframe>
</body>
</html>
```

this is the link that i created on my first website : https://hostbesto.com/payment-order67/

and its not sending to checkout like normal : https://hostbesto.us/quick-buy/7571/1/

i hope that someone is understanded what im trying to do , and provide me a solution because i think that woocommerce is blocking something in the coding , and im not an a person who knows java and coding…

### Expected behavior

i want the checkout page to appear but its not

### Actual behavior

i hope that someone is understanded what im trying to do , and provide me a solution because i think that woocommerce is blocking something in the coding , and im not an a person who knows java and coding…

### Steps to reproduce

i hope that someone is understanded what im trying to do , and provide me a solution because i think that woocommerce is blocking something in the coding , and im not an a person who knows java and coding…

### WordPress Environment

please i want a fix

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Hi im using this code so i can embed my website on other website that also mine , but the checkout page have a restriction that cannot appear correctly

@achrafahmadi Most payment gateways require this restriction. You could consider using external products on the second website. If you have further questions please contact WooCommerce  support.
