### ISSUE TITLE
[Enhancement]: Add rewrite rules to filter product categories by tag or by attribute

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#40481]
### Describe the solution you'd like

Logically speaking, product categories split the shop vertically, while tags cut across horizontally, and so do attributes. For example, dress categories may include "Wedding dresses", "Evening dresses" and "Casual dress", which are mutually exclusive, but have tags like "V neck" or "Minimalist style" and attributes like "Color: Blue" "Fabric: Satin".

Right now, WooCommerce provides automatic archive pages for each taxonomy by itself. When using attribute filters (or tag filters via a plugin), URL parameters are added, but the canonical URL is still set without those parameters.

So if I want to construct a page that targets the (hypothetical) search "minimalist satin wedding dress", it's currently impossible to get such a page into the Google index without manually adding pages with shortcodes, building templates for them and manually controlling all of their SEO attributes.

What would be great instead is to provide a filtering URL structure like this:

`domain.com/product-category/wedding-dresses/tag/minimalist/fabric/satin/`

On such a page, the page URL will also be the canonical URL, instead of the URL of the infiltered product category.

In fact, Shopify supports `domain.com/collections/wedding-dresses/minimalist`, which is more than halfway there, so providing tag filtering without the `tag/` bit is preferable.

### Describe alternatives you've considered

I've considered using the `[products]` shorcode, but it requires a lot of manual "double dealing" and custom code.

I've considered using custom rewrite rules, and this quickly became complicated for me, which is what plugins are meant to prevent.

**Comment by galbaras** [comment]
The following code uses filters and actions to implement my idea with the current plugin. It's an example from a site that sells dresses. Adding it to the plugin itself in a more generic way will make it easier for others to use:

```
add_filter( 'woocommerce_page_title', 'custom_attribute_term_title' );
function custom_attribute_term_title( $title ) {
	if ( ! is_tax() || ! function_exists( 'taxonomy_is_product_attribute') ) {
		return $title;
	}

    $tax_obj = get_queried_object();
    if ( ! taxonomy_is_product_attribute( $tax_obj->taxonomy ) ) {
		return $title;
    }
	
	return $title . ' Dresses';
}

function custom_product_tag_rewrite_rules( $tag ) {
	add_rewrite_rule(
		"product-category/(.+?)/$tag/?\$",
		"index.php?product_cat=\$matches[1]&product_tag=$tag",
		'top'
	);
	add_rewrite_rule(
		"product-category/(.+?)/$tag/page/?([0-9]{1,})/?\$",
		"index.php?product_cat=\$matches[1]&product_tag=$tag&paged=\$matches[2]",
		'top'
	);
}

function custom_product_attribute_rewrite_rules( $att ) {
	add_rewrite_rule(
		"product-category/(.+?)/$att/([^/]+)/?\$",
		"index.php?product_cat=\$matches[1]&filter_$att=\$matches[2]",
		'top'
	);
	add_rewrite_rule(
		"product-category/(.+?)/$att/([^/]+)/page/?([0-9]{1,})/?\$",
		"index.php?product_cat=\$matches[1]&filter_$att=\$matches[2]&paged=\$matches[3]",
		'top'
	);
}

add_action( 'init', 'custom_rewrite_rules' );
function custom_rewrite_rules() {
	if ( ! function_exists( 'wc_get_attribute_taxonomies' ) ) {
		return;
	}

	$product_tags = get_terms( 'product_tag' );
	if ( ! empty( $product_tags ) && ! is_wp_error( $product_tags ) ){
		foreach ( $product_tags as $tag ) {
			custom_product_tag_rewrite_rules( $tag->slug );
		}
	}
	
	$product_attributes = wc_get_attribute_taxonomies();
	if ( ! empty( $product_attributes ) && ! is_wp_error( $product_attributes ) ){
		foreach ( $product_attributes as $att ) {
			custom_product_attribute_rewrite_rules( $att->attribute_name );
		}
	}
}

add_filter( 'rank_math/frontend/canonical', 'custom_canonical_urls' );
function custom_canonical_urls( $canonical ) {
	global $wp_query;

	if ( ! $wp_query->get( 'product_cat' ) ) {
		return $canonical;
	}

	if ( $wp_query->get( 'product_tag' ) ) {
		return $canonical . $wp_query->get( 'product_tag' ) . '/' ;
	}

	$product_attributes = wc_get_attribute_taxonomies();
	if ( ! empty( $product_attributes ) && ! is_wp_error( $product_attributes ) ){
		foreach ( $product_attributes as $att ) {
			$value = $wp_query->get( 'filter_' . $att->attribute_name );
			if ( $value ) {
				return $canonical . $att->attribute_name . '/' . $value . '/';
			}
		}
	}

	return $canonical;
}

add_filter( 'rank_math/frontend/title', 'custom_archive_title' );
add_filter( 'woocommerce_page_title', 'custom_archive_title' );
function custom_archive_title( $title ) {
	global $wp_query;

	if ( ! $wp_query->get( 'product_cat' ) ) {
		return $title;
	}

	$title .= ' Dresses';
	if ( $wp_query->get( 'product_tag' ) ) {
		$term = get_term_by( 'slug', $wp_query->get( 'product_tag' ), 'product_tag' );
		return ucwords( $term->name ) . " $title";
	}

	$product_attributes = wc_get_attribute_taxonomies();
	if ( ! empty( $product_attributes ) && ! is_wp_error( $product_attributes ) ){
		foreach ( $product_attributes as $att ) {
			$value = $wp_query->get( 'filter_' . $att->attribute_name );
			if ( $value ) {
				$term = get_term_by( 'slug', $value, 'pa_' . $att->attribute_name );
				return ucwords( $term->name ) . " $title";
			}
		}
	}

	return $title;
}

add_action( 'parse_request', 'custom_rewrite_get_filters', 10, 1 );
function custom_rewrite_get_filters( $wp ) {
	global $_GET;
	
	if ( ! isset( $wp->query_vars['product_cat'] ) ) {
		return;
	}

	$product_attributes = wc_get_attribute_taxonomies();
	if ( ! empty( $product_attributes ) && ! is_wp_error( $product_attributes ) ) {
		foreach ( $product_attributes as $att ) {
			$filter = 'filter_' . $att->attribute_name;
			if ( isset( $wp->query_vars[$filter] ) && ! isset( $_GET[$filter] ) ) {
				$_GET[$filter] = $wp->query_vars[$filter];
			}
		}
	}
}
```

The `parse_request` filter can be avoided entirely by changing the function `get_layered_nav_chosen_attributes()` from using `$_GET` to using `$wp->query_vars`.

**Comment by rrennick** [comment]
> domain.com/product-category/wedding-dresses/tag/minimalist/fabric/satin/

> In fact, Shopify supports domain.com/collections/wedding-dresses/minimalist, which is more than halfway there, so providing tag filtering without the tag/ bit is preferable.

@galbaras What you are asking for conflicts with permalink structures that already work. For example, `/collections/wedding-dresses/minimalist`:

- In a dev install, set your product category base to `collections`
- Create a `Wedding dresses` product category
- Create a `Minimalist` product category and set its parent to be `Wedding dresses`
- Create a product & set its category to be `Minimalist`
- Go to the product categories listing and view the `Minimalist` category

The same can be done with the longer URL above. So this is not something that we can implement in WC core. However, if you do not use child categories on your site then you can add rewrite rules to implement the URLs you have described. I'll close this as won't fix.

**Comment by galbaras** [comment]
@rrennick This completely misses my intention. To achieve what I wanted, I'd have to create the same sub-category (e.g. Minimalist) for EVERY parent category, and there would still be no way of listing all the products in it ACROSS parent categories.

Also, there's really no conflict. I have this running successfully on 2 live websites already, and Google LOVES it!

I get that you probably read many issues every day, but please re-read the original post in this one when you can take the time to understand its potential value for the plugin and its users.

**Comment by rrennick** [comment]
> there's really no conflict. I have this running successfully on 2 live websites already, and Google LOVES it!

Right, there is no conflict for your site.

> To achieve what I wanted, I'd have to create the same sub-category (e.g. Minimalist) for EVERY parent category, and there would still be no way of listing all the products in it ACROSS parent categories.

Sorry for the misunderstanding. I was not suggesting that you create child product categories. IMy example was to illustrate that the rewrite rules you are requesting in this issue conflict with the way heirarchical taxonomies work in WordPress (in this case product categories). 

However, you can add rewrite rules to your site that will work as you have described.

**Comment by galbaras** [comment]
The only conflict is when the very same term is used as a sub-category and a tag or attribute. Otherwise, there is none.

Doing this, even if in a slightly different way, provides HUGE search advantage to WooCommerce sites and makes it far easier for potential customers to find exactly what they want without navigation, so should also bring a conversion benefit. I fail to understand the resistence.

**Comment by rrennick** [comment]
> The only conflict is when the very same term is used as a sub-category and a tag or attribute.

Right. As I have mentioned in my previous comments, your use case requires adding to default the WordPress rewrite configuration. It does not require any changes to WooCommerce. Your site may not have any of these conflicts but you are asking to have your use case apply to all existing (X million) shops. **Some of those shops are going to have conflicts which  would break those shops. That is the reason this issue is marked as won't fix.**

**Comment by galbaras** [comment]
So first, WooCommerce adds its own rewrite rules already for the base shop URL and product taxonomies.

In WordPress, it's impossible to add the same term more than once within each taxonomy's namespace. Therefore, the only possible conflicts occur if a product subcategory, a product tag and/or a product attribute have the same name (after removing the leading "pa_" from the attribute). This is highly unlikely, but can also be expressly prevented with code when taxonomies are being updated.

**Comment by rrennick** [comment]
> In WordPress, it's impossible to add the same term more than once within each taxonomy's namespace.

@galbaras Right. The conflict comes from the fact that you can have a product tag `example`, product category `example`, product attribute `example` (stored as `pa_`).

In your description you requested being able to have a category `Wedding dresses` and a tag `Minimalist`. In my [first comment](https://github.com/woocommerce/woocommerce/issues/40481#issuecomment-1941795324), I provided the steps to demonstrate that with the setup you describe the tag `Minimalist` would conflict with a `Minimalist` sub-category. 

> This is highly unlikely, 

I have been responding to issues in this repository for 5+ years and the conflicts I described do exist in a significant number.

> but can also be expressly prevented with code when taxonomies are being updated.

This would involve writing an update routine that updated existing taxonomies. What you described on the issue looks like a great idea to implement in shops on a voluntary basis. It would make a great extension, but due to the restrictions it would impose on existing shops, it is not suitable for WC core. I am closing this issue to further discussion.
