### ISSUE TITLE
PLease assist ASAP please help

### ISSUE THREAD

**Issue by dhanush732** [woothemes/woocommerce#40483]
if (
    in_array(
        "woocommerce/woocommerce.php",
        apply_filters("active_plugins", get_option("active_plugins"))
    )
) {
    function shipsmart_rates()
    {
        if (!class_exists("ShipSmart_Shipping_Rates")) {
            class ShipSmart_Shipping_Rates extends WC_Shipping_Method
            {
                /**
                 * Constructor for your shipping class
                 *
                 * @access public
                 * @return void
                 */
                public function __construct()
                {
                    $this->id = "ShipSmart Rates";
                    $this->method_title = __("ShipSmartRates", "Rates");
                    $this->method_description = __(
                        "Least Rates From Our Server",
                        "Rates"
                    );
                    $this->enabled = "yes";
                    $this->title = "Carrier rate (TMS)";
                    $this->init();
                }
                /**
                 * Init your settings
                 *
                 * @access public
                 * @return void
                 */
                function init()
                {
                    $this->init_form_fields();
                    $this->init_settings();

                    // Save settings in admin if you have any defined
                    add_action(
                        "woocommerce_update_options_shipping_" . $this->id,
                        [$this, "process_admin_options"]
                    );
                }

                /**
                 * calculate_shipping function.
                 *
                 * @access public
                 * @param array $package
                 * @return void
                 */
                public function calculate_shipping($package = [])
                {
                    //Destination Details
                    $destination_country = $package["destination"]["country"];
                    $destination_state = $package["destination"]["state"];
                    $destination_city = $package["destination"]["city"];
                    $destination_address = $package["destination"]["address"];
                    $destination_zipcode = $package["destination"]["postcode"];
                    $destination_address2 =
                        $package["destination"]["address_2"];

                    //Delivery Details
                    $pickup_date = $package["pickup_date"];

                    //Extra Information

                    $cartTotal = $package["cart_subtotal"];

                    //Item Details

                    $newArray = [];

                    foreach ($package["contents"] as $item_id => $item) {
                        $product = $item["data"];
                        $quantity = $item["quantity"];
                        $weight = floatval($product->get_weight());
                        $height = floatval($product->get_height());
                        $length = floatval($product->get_length());
                        $width = floatval($product->get_width());
                        $Description = preg_replace("/[^a-zA-Z0-9\s]/", "", $product->get_name());
                        $productKey = (string) $item["product_id"];

                        $totalWeight = $quantity * $weight;

                        $newArray[] = [
                            "Description" => $Description,
                            "Qty" => $quantity,
                            "Weight" => $totalWeight,
                            "Length" => $length,
                            "Width" => $width,
                            "Height" => $height,
                            "ItemCode" => $productKey,
                            "itemClass" => "70",
                        ];
                    }

                    $requestArray = [
                        "Destination" => [
                            "Street" => $destination_address,
                            "Street2" => $destination_address2,
                            "City" => $destination_city,
                            "State" => $destination_state,
                            "Zip" => $destination_zipcode,
                            "CountryCode" => $destination_country,
                        ],
                        "Items" => $newArray,
                        "SheduleDateTime" => [
                            "PickupByDate" => $pickup_date,
                        ],
                        "Reference3" => $cartTotal,
                    ];

                    $data = json_encode($requestArray, true);

                    //Login API Call
                    $auth_url =
                        "************";

                    $credentials = [
                        "username" => "**********",
                        "password" => "1234567890",
                    ];

                    $ch = curl_init($auth_url);

                    curl_setopt($ch, CURLOPT_POST, true);
                    curl_setopt(
                        $ch,
                        CURLOPT_POSTFIELDS,
                        json_encode($credentials)
                    );
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                        "TLXDEVKEY: TLXIT",
                        "Content-Type: application/json",
                    ]);

                    $mh = curl_multi_init();
                    curl_multi_add_handle($mh, $ch);

                    $running = null;
                    do {
                        curl_multi_exec($mh, $running);
                    } while ($running);

                    $response = curl_multi_getcontent($ch);

                    curl_multi_remove_handle($mh, $ch);
                    curl_multi_close($mh);

                    $token = str_replace('"', "", $response);

                    curl_close($ch);

                    $apiUrl =
                        "*********************";

                    $ch1 = curl_init($apiUrl);

                    // Set cURL options
                    curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, "POST");
                    curl_setopt($ch1, CURLOPT_POSTFIELDS, $data);
                    curl_setopt($ch1, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_ENCODING, '');
                    curl_setopt($ch1, CURLOPT_HTTPHEADER, [
                        "Authorization: Bearer " . $token,
                        "Content-Type: application/json",
                    ]);

                    $mh1 = curl_multi_init();
                    curl_multi_add_handle($mh1, $ch1);

                    $running1 = null;
                    do {
                        curl_multi_exec($mh1, $running1);
                    } while ($running1);

                    $response2 = curl_multi_getcontent($ch1);

                    curl_multi_remove_handle($mh1, $ch1);
                    curl_multi_close($mh1);

                    $response2 = json_decode($response2, true);

                    $carrierName = $response2["CarrierName"];
                    $amount = $response2["Amount"];

                    $rate = [
                        "label" => $carrierName,
                        "cost" => $amount,
                        "calc_tax" => "per_item",
                    ];
                    $this->add_rate($rate);
                }
            }
        }
    }
    add_filter('woocommerce_defer_transactional_emails', '__return_true');

    add_action("woocommerce_shipping_init", "shipsmart_rates");

    function RatestoCheckout($methods)
    {
        $methods["rates"] = "ShipSmart_Shipping_Rates";
        return $methods;
    }

    add_filter("woocommerce_shipping_methods", "RatestoCheckout");
}
?>

`

This is my woocommerce plugin code i used in my wordpress site but it shows endless loading when i change shipping address but the dev tools network get response but it still loading please advise

_Originally posted by @dhanush732 in https://github.com/woocommerce/woocommerce/issues/6603#issuecomment-1738614880_

**Comment by rrennick** [comment]
Hi @dhanush732

Github is for reporting bugs or requestiong enhancements. For custom coding questions your best bet is The [WooCommerce Community Slack](https://woocommerce.com/community-slack/).
