### ISSUE TITLE
Recommended Themes REST API Endpoint Stub

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40482]
## User Story

> As a new merchant, I want professionally designed themes recommended to me, so I have an alternative to using the pattern assembler.

## Acceptance Criteria

```
Scenario: Endpoint request paramaters
    Given there is a REST API endpoint
    And the available parameters are
      industry (string): limits the results to themes relevant for this industry (optional)
      currency (enum: USD, AUD, CAD, EUR, GBP): returns pricing in this currency (optional, default: USD)

Scenario: Endpoint response format
    Given there is a REST API endpoint
    And the response should return static content for the following 4 themes: Tsubaki, Tazza, Amulet, Zaino (note: these are Dotcom themes)
    And each theme should include fields for
       Theme Name (string): The name of the theme.
       Price: (string): Human readable price. Examples: Free, $49 / per year, €49 / per year.
       Color Palettes (array): Array of color palette objects, each containing primary, secondary, and background colors.
       Thumbnail URL (string): URL of the thumbnail image.
       Link URL: URL for the theme.

Scenario: Endpoint fallback content
    Given there is a REST API endpoint
    And the user has marketplace suggestions disabled
    Then return 0 themes

Scenario: 3PD Extensibility
    Given there is a REST API endpoint
    And the response should be filterable to allow the theme collection to be customized by third parties.
    And the response should be filterable to allow the "Browse All" URL to be customized by third parties.
    
Scenario: Browse All URL
    Given there is a REST API endpoint
    And the "Browse All" URL should be provided in the _links response

```

## Additional Info

* This is just a "stub" containing static content. A follow-up issue will be created to hook it up with live data from [WooCommerce.com Theme Store](https://woocommerce.com/product-category/themes/?categoryIds=1033&collections=theme&page=1) (marketplace)
* Woo Express will utilize the 3PD filter to provide themes relevant for that environment.

**Comment by chihsuan** [comment]
>  And each theme should include fields for
>        Theme Name (string): The name of the theme.
>        Price: (string): Human readable price. Examples: Free, $49 / per year, €49 / per year.
>        Color Palettes (array): Array of color palette objects, each containing primary, secondary, and background colors.
>        Thumbnail URL (string): URL of the thumbnail image.
>        Link URL: URL for the theme.

Thanks @adrianduffell, I think it would be great to include the following fields in response:

- theme slug (string)
- isActive (boolean): Whether theme is active

**Comment by moon0326** [comment]
Thanks @adrianduffell! 

For the theme data, we should also consider adding `primary_border` and `secondary_border` (optional) as the color palettes have borders that are different from primary or secondary.

**Comment by adrianduffell** [comment]
> For the theme data, we should also consider adding primary_border and secondary_border (optional) as the color palettes have borders that are different from primary or secondary.

Good callout! I wonder if we might be able to use a semi-transparent black in CSS to apply the correct border color. It looks like calypso does this with `box-shadow` to achieve the effect in the theme cards:

```
border: none;
border-radius: 50%;
box-shadow: inset 0 0 0 1px #0003;
```

<img width="448" alt="Screen Shot 2023-09-29 at 4 10 57 pm" src="https://github.com/woocommerce/woocommerce/assets/9312929/1c7a34d8-e2d4-479a-93a6-d7843f559947">
