### ISSUE TITLE
Apple Pay I want to Enable from Processed to check out  its seeing 

### ISSUE THREAD

**Issue by developerindian** [woothemes/woocommerce#40480]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have enabled the Apple Pay button on my website, but it's appearing on the Add to Cart button. I want to remove it from there and instead, display the Apple Pay button on the checkout page.

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/115354938/66db9554-ce93-47ab-acf3-5d8ab8b07fef)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.thesallymorris.com
Site address (URL): https://www.thesallymorris.com
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: ❌ 6.2.2 - There is a newer version of WordPress available (6.3.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 1 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 153.21MB
Database Data Size: 143.20MB
Database Index Size: 10.01MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.44MB + Index: 0.72MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.48MB + Index: 0.41MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.38MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 13.52MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 77.52MB + Index: 2.92MB + Engine InnoDB
wp_posts: Data: 43.52MB + Index: 0.64MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tutor_earnings: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_attempt_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_question_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_withdraws: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.47MB + Index: 0.41MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 120
course: 7
courses: 3
custom_css: 2
customize_changeset: 5
elementor_library: 1
elementor-hf: 2
events: 4
layout_block: 3
lesson: 70
mailpoet_page: 1
msm_mega_menu: 3
nav_menu_item: 13
oembed_cache: 4
page: 23
post: 1
product: 3
question: 39
quiz: 44
revision: 3174
sa_slider: 2
shop_coupon: 8
shop_order: 105
shop_order_refund: 1
sl-insta-account: 1
teacher: 4
timetable_weekdays: 7
topics: 19
tribe_events: 3
tribe_organizer: 3
tribe_venue: 6
tutor_enrolled: 181
vc_grid_item: 8
vc_settings_preset: 13
videoplayer: 1
wp_global_styles: 3
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

LayerSlider: by Kreatura Media – 7.2.4
Code Snippets: by Code Snippets Pro – 3.4.2
Contact Form 7: by Takayuki Miyoshi – 5.8
Joinchat: by Creame – 5.0.10
Elementor: by Elementor.com – 3.16.4
Essential Addons for Elementor: by WPDeveloper – 5.8.9
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.15

Spotlight - Social Media Feeds: by RebelCode – 1.6.1
Subscriptions For WooCommerce: by WP Swings – 1.5.3
Tutor LMS Elementor Addons: by Themeum – 2.1.2
Tutor LMS: by Themeum – 2.3.0
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.48

WooCommerce Stripe Gateway: by WooCommerce – 7.5.0
WooCommerce: by Automattic – 8.1.1

### Inactive Plugins (7) ###

AWeber for WordPress: by AWeber – 7.3.9
Deposits & Partial Payments for WooCommerce: by Acowebs – 1.1.13
Plugins Garbage Collector (Database Cleanup) Old!: by Vladimir Garagulya – 0.14
StoreCustomizer: by Kaira – 2.5.3
W3 Total Cache: by BoldGrid – 2.4.1
WooCommerce Direct Checkout: by QuadLayers – 3.2.2
WooCommerce PayPal Payments: by WooCommerce – 2.3.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #1148 - /cart/
Checkout: #1151 - /checkout/
My account: #1155 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Astra
Version: 4.1.5 (update to version 4.3.1 is available)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra/woocommerce/emails/customer-invoice.php
/home/u204992257/domains/thesallymorris.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/u204992257/domains/thesallymorris.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/u204992257/domains/thesallymorris.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-29 00:20:08 +00:00
Options: ✔
Notes: 141
Onboarding: completed

### Action Scheduler ###

Complete: 2,633
Oldest: 2023-08-28 04:31:11 +0000
Newest: 2023-09-28 03:55:01 +0000

Failed: 44
Oldest: 2022-10-10 02:51:28 +0000
Newest: 2023-09-11 11:44:52 +0000

Pending: 6
Oldest: 2023-09-28 04:25:01 +0000
Newest: 2023-09-28 12:08:10 +0000

### Status report information ###

Generated at: 2023-09-28 04:04:58 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
@developerindian Thank you for reaching out. From what I can tell you are using the `Payment Plugins for Stripe WooCommerce: by Payment Plugins` plugin. This is not something maintained by WooCommerce and I recommend reaching out to its developers for support.

I will be closing this issue as there is nothing actionable on our end.
