### ISSUE TITLE
Having issues with WooCommerce order processing count

### ISSUE THREAD

**Issue by ijasdev** [woothemes/woocommerce#40488]
Having issues with WooCommerce order processing count, the processing tab shows one value (say 56) and when clicked the pagination section shows another value (64). Upon checking the individual order status, almost 21 orders in this section (with  processing label) are completed orders. The count varies on time.

**Comment by ijasdev** [comment]
I'm having the same issue on another website, the processing tab shows 30 orders and when clicked we have only 16 orders in the list.

**Comment by ijasdev** [comment]
Both sites using the latest WooCommerce version (8.1.1).

**Comment by rrennick** [comment]
@ijasdev Could you provide your System Status report?
