### ISSUE TITLE
[DOC-BUG] Option to enable HPOS has changed

### ISSUE THREAD

**Issue by dgwatkins** [woothemes/woocommerce#40485]
## Link to the Page/Section

https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#using-wp-cli

## Description of the Suggestion

The doc says this command will enable HPOS, but it doesn't:
`wp option set woocommerce_feature_custom_order_tables_enabled yes`

## Reason for the Suggestion

After looking at the source code, I noticed the option name changed to `woocommerce_custom_orders_table_enabled`.

It should be `wp option set woocommerce_custom_orders_table_enabled yes`

**Comment by jorgeatorres** [comment]
Hi @dgwatkins!

Thanks for bringing attention to this. I've updated the wiki accordingly.
