### ISSUE TITLE
Analytics date range tools broken in latest version of Gutenberg

### ISSUE THREAD

**Issue by ryanr14** [woothemes/woocommerce#40518]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If using the latest version of the Gutenberg plugin on your site, this causes functional and visual issues with the Date range tools in any of the Analytics screens in WooCommerce.

Mainly if you were seleting the Custom range option and trying to navigate months using the arrows. The pop-over window closes with no dates being chosen.

![https://d.pr/i/0U04qz](https://d.pr/i/0U04qz+)
Image link: https://d.pr/i/0U04qz

### Expected behavior

To have a clean UI and functional tools to help set date ranges to filter my analytics by.

### Actual behavior

Hard to see and non-functional filtering options. :)

### Steps to reproduce

1. Activate Gutenberg and Woo
2. Head to Analytics and use the Date range tool to first the visual issues.
3. Try to set a custom range and select the arrows to view a previous month.
4. See issues

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://beta.local
Site address (URL): https://beta.local
WC Version: 8.2.0
REST API Version: ✔ 8.2.0
WC Blocks Version: ✔ 11.1.1
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.4-beta1-56741
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Total Database Size: 7.03MB
Database Data Size: 5.32MB
Database Index Size: 1.71MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.13MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
nav_menu_item: 8
page: 11
post: 2
product: 5
revision: 7
shop_order: 1
wp_global_styles: 3
wp_navigation: 1
wp_template: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Gutenberg: by Gutenberg Team – 16.7.0
WooCommerce Beta Tester: by WooCommerce – 2.2.0
WooCommerce: by Automattic – 8.2.0-beta.1
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.4

### Inactive Plugins (1) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-29 19:29:20 +00:00
Options: ✔
Notes: 117
Onboarding: completed

### Action Scheduler ###

Complete: 16
Oldest: 2023-09-01 12:26:15 +0000
Newest: 2023-09-29 16:22:14 +0000

Failed: 1
Oldest: 2023-04-04 06:54:59 +0000
Newest: 2023-04-04 06:54:59 +0000

Pending: 1
Oldest: 2023-09-30 16:22:14 +0000
Newest: 2023-09-30 16:22:14 +0000

### Status report information ###

Generated at: 2023-09-29 16:22:49 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by davidhealey** [comment]
Just wanted to say I'm having the same issue

![Peek 2023-11-06 17-56](https://github.com/woocommerce/woocommerce/assets/14021202/60e70c34-d880-484f-9394-b0de0f609486)

**Comment by davidhealey** [comment]
Also just noticed these buttons don't work either (I suspect it's the same in all of these popup style windows).

![image](https://github.com/woocommerce/woocommerce/assets/14021202/407c0fab-2696-4803-9319-8ddc465208c7)

**Comment by martynmjones** [comment]
Noting that this is an issue without the Gutenberg plugin installed with WordPress 6.4.

**Comment by jp-imagines** [comment]
Reported by a customer in 7306000-zd-a8c on iOS as well (and replicated on desktop, as above). I believe https://github.com/woocommerce/woocommerce/issues/41502 is the same issue.

In my tests, it's not possible to use the arrows to navigate between months, but you _can_ select a start and end date – the calendar just closes after each click.


https://user-images.githubusercontent.com/5630717/283577327-00a8462f-4d3c-452a-8657-21e2770bb991.mp4

**Comment by mattiadesiderio** [comment]
Hi, it's now fixed with version 8.3.0 of WooCommerce

**Comment by davidhealey** [comment]
> Hi, it's now fixed with version 8.3.0 of WooCommerce

Confirmed the issue with the custom date range is fixed for me too.

The issue with the popup remains, should I open a new issue for that?

![Peek 2023-11-17 11-20](https://github.com/woocommerce/woocommerce/assets/14021202/170de357-243c-4615-8fd1-998fdb5eac5f)

**Comment by sawwd** [comment]
Can someone link the commits were made to fix this? I'm facing the same problem on WP 6.4.3 and WooCommerce 7.3.0

**Comment by mikkamp** [comment]
As mentioned in this issue, this has been resolved in WooCommerce 8.3, so I'll go ahead and close this issue.

> Can someone link the commits were made to fix this? I'm facing the same problem on WP 6.4.3 and WooCommerce 7.3.0

The specific changes can be found in PR #41372 
If you'd like to look up the PR's which go into a specific release this can be done by looking through [the milestone](https://github.com/woocommerce/woocommerce/milestone/224?closed=1).
