### ISSUE TITLE
Logging: Add settings UI to configure the logger

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#40527]
The debug logger has several different configuration settings, but currently they can only be set via PHP constants or filter hooks (depends on the setting). In order to make the logging system more accessible and useful to store owners, and to better facilitate accessing logs while troubleshooting issues, we should add some setting controls to the admin UI. These could either be added somewhere to an existing settings screen, or to a new settings screen under the Logs tab (WooCommerce > Status > Logs).

My initial idea here would be to follow the same Page/Tab/Section pattern used elsewhere for WC Settings and make the logging configuration a _section_ called "Configure", and the existing Logs screen would become the default section under the Logs tab called "View logs".

On this section we could have the following settings:

* Global toggle to enable/disable all logging (AFAIK right now file logging is always turned on)
* Log handler (probably with a better name) for choosing between storing logs in the database or the filesystem (also see #40525)
* Severity threshold, a global setting for all logs
* Log retention period, a global setting for all logs

Additionally, we could add things like:

* Setting up email notifications for logs of a certain severity threshold
* A section for extensions to hook into to add their own log settings (e.g. enable/disable, different thresholds or retention periods based on log source)

**Comment by barryhughes** [comment]
Nice!

> Log handler (probably with a better name) for choosing between storing logs in the database or the filesystem

- What are your thoughts on also allowing plugins to list their own log handler here?
- Should we support enabling multiple loggers (as is currently possible) via this UI, or keep it simple?

**Comment by coreymckrill** [comment]
🤔 I think it could make sense to allow listing other custom handlers here (so it would probably be a `<select>` element), via a separate filter hook. I don't think we'd want to include every existing handler in that choice, since some of them (like the email handler) have more complex configurations and more limited use cases.

In terms of supporting multiple handlers in the UI, it's kind of on a case-by-case basis. It probably doesn't make sense to use both the file and database handlers at the same time (thus using a `<select>` to choose between the two), but combining email with either one of those does. So adding some separate setting controls for the email handler is definitely something I'd want to implement, probably a checkbox toggle to turn it on/off, plus a field to add recipients and a dropdown to choose the severity threshold. Other custom handlers could do something similar, where the developer would have to decide whether the handler was a "main" handler or a "companion" handler.
