### ISSUE TITLE
Continuing to charge customer after customer's subscription is canceled. 

### ISSUE THREAD

**Issue by kaserarts1** [woothemes/woocommerce#40555]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have canceled all of the woocommerce subscriptions that we have on our website. We are no longer using the subscription model at all. However, one customer is continuing to be charged monthly. I have 100% canceled her subscription but it continues to charge her. 

This is very frustrating and there is no support line that I can call and easily get this resolved on. 

Please help! This customer is not easy to deal with. 

### Expected behavior

I expected the subscription to cancel and for the system to stop charging this customer. 

### Actual behavior

It is continuing to charge the customer $94 dollars a month. 

### Steps to reproduce

I do not want to reproduce this! 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kaserarts.com
Site address (URL): https://kaserarts.com
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.9

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 38.27MB
Database Data Size: 33.48MB
Database Index Size: 4.79MB
wp_woocommerce_sessions: Data: 1.49MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.26MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.62MB + Index: 0.17MB + Engine MyISAM
wp_content_tabs_ultimate_import: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_content_tabs_ultimate_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_content_tabs_ultimate_style: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_etn_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_etn_trans_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_evf_entries: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_evf_entrymeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_evf_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 5.11MB + Index: 0.22MB + Engine MyISAM
wp_oxi_div_import: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 18.32MB + Index: 1.79MB + Engine MyISAM
wp_posts: Data: 5.81MB + Index: 0.26MB + Engine MyISAM
wp_sgs_log_events: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_sgs_log_visitors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.10MB + Index: 0.08MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 286
cartflows_flow: 1
cartflows_step: 1
custom_css: 1
elementor_library: 18
etn: 1
everest_form: 6
nav_menu_item: 34
oembed_cache: 10
page: 66
post: 6
product: 84
revision: 1853
shop_order: 605
shop_order_refund: 24
shop_subscription: 45
shopengine-template: 3
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
woolentor-template: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Typing Effect: by 93digital – 1.5
Total Upkeep: by BoldGrid – 1.15.7
CartFlows: by CartFlows Inc – 1.11.15
Elementor Pro: by Elementor.com – 3.15.1
Elementor: by Elementor.com – 3.15.3
Everest Forms: by WPEverest – 2.0.3
Jetpack: by Automattic – 12.5
SiteGround Optimizer: by SiteGround – 7.4.0
SiteGround Security: by SiteGround – 1.4.5
ShopEngine Pro: by Wpmet – 2.2.2
ShopEngine: by Wpmet – 4.3.0
Tabs – Responsive Tabs with WooCommerce Product Tab Extension: by Biplob Adhikari – 4.0.6
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.2
WooCommerce Checkout Manager PRO: by QuadLayers – 7.2.0
WooCommerce Checkout Manager: by QuadLayers – 7.2.3
WooCommerce Payments: by Automattic – 6.3.2 (update to version 6.5.1 is available)
WooCommerce Square: by WooCommerce – 4.2.0 (update to version 4.2.1 is available)
WooCommerce: by Automattic – 8.0.3 (update to version 8.1.1 is available)
ShopLentor – WooCommerce Builder for Elementor & Gutenberg: by HasThemes – 2.6.8
WordPress HTTPS: by Mike Ems – 3.4.0
WP File Manager: by mndpsingh287 – 7.2
WP Mail SMTP: by WP Mail SMTP – 3.9.0
WP Social Widget: by catchsquare – 2.2.5
WPForms Lite: by WPForms – 1.8.3.1
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.8.4

### Inactive Plugins (3) ###

Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.46

Protect Uploads: by alticreation – 0.5.2
W3 Total Cache: by BoldGrid – 2.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page not set
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Neve
Version: 2.6.1 (update to version 3.7.0 is available)
Author URL: https://themeisle.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: neve/woocommerce/emails/admin-cancelled-order.php
neve/woocommerce/emails/admin-failed-order.php
neve/woocommerce/emails/admin-new-order.php
neve/woocommerce/emails/customer-invoice.php
neve/woocommerce/emails/customer-processing-order.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://kaserarts.com
Subscriptions-core Library Version: 6.0.0
Subscription Statuses: trash: 45
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooPayments: trash: 45

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-03 04:39:23 +00:00
Options: ✔
Notes: 138
Onboarding: completed

### WooCommerce Payments ###

Version: 6.3.2
Connected to WPCOM: Yes
Blog ID: 173117903
Account ID: acct_1LQ2Xq2HEYWC7duA

### Action Scheduler ###

Complete: 312
Oldest: 2023-09-02 20:53:49 +0000
Newest: 2023-10-02 23:10:43 +0000

Failed: 5
Oldest: 2022-08-16 00:31:12 +0000
Newest: 2023-05-23 12:47:28 +0000

Pending: 9
Oldest: 2023-10-03 07:39:44 +0000
Newest: 2023-10-28 00:44:31 +0000

### Status report information ###

Generated at: 2023-10-02 23:15:32 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi! I'm sorry to hear you've been having difficulties, but this is the bug tracker for WooCommerce Core. For help with [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/), you should [reach out to the Subscriptions team](https://woocommerce.com/my-account/contact-support/).
