### ISSUE TITLE
Product Editor API: Select field block

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#40550]
## Description

Similar to the `woocommerce_wp_select` function, we should create a block that provides select field functionality in the new product editor.

It should be able to persist information in the product, both as a regular field and in the meta_data array, using the `useProductEntityProp` hook.

It should contain at least the following attributes:

- label (string)
- property (string)
- help (string)
- **tooltip (string)**
- options (array): array containing the possible label and values

**Tooltip is the only one left.**

## Acceptance criteria

- [ ] I can use the woocommerce/product-select-field to persist a custom field in the product editor

**Comment by NTShop** [comment]
Just saw this, it would be great to have a select field available! That would save a ton of development work creating a custom block just for a basic HTML field.

**Comment by NTShop** [comment]
This field should support multi-select.

**Comment by mattsherman** [comment]
There have also been requests to support searching and dynamic values (retrieved via API calls, for example).

Moving this back to prioritization until we nail down the requirements!

**Comment by NTShop** [comment]
Somewhat related: What about something similar to how Select2 works, which helps tremendously for very long lists because it allows searching the list by typing into the input field?

**Comment by mattsherman** [comment]
Blocking this for now, as we should first complete the work on the updated select component in #38226.

**Comment by helgatheviking** [comment]
>This field should support multi-select.

:100: 

>There have also been requests to support searching and dynamic values (retrieved via API calls, for example).

:100 personally, i need a product/variation selector very much like Select2 currently works.

**Comment by leewillis77** [comment]
Just dropping a comment here to log the fact that the lack of a SELECT-style component pretty much blocks us building support for the new Product Editor into at least one of our Woo extensions.

**Comment by mattsherman** [comment]
Note that we have a basic select block available now (thanks @mdperez86!): 

https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/product-editor/src/blocks/generic/select

We need to take a look at this and see what things still need to be added.

**Comment by NTShop** [comment]
@mattsherman - Any chance of having it support Select2 (includes Ajax search), or at least being able to assign a class name to it so we can hook up Select2 ourselves?

**Comment by helgatheviking** [comment]
@mattsherman this looks like a great start. But to echo @NTShop I think we would also need search and ajax sources... So parity with selectWoo/Select2.

**Comment by leewillis77** [comment]
@mattsherman That's great - thanks! As others have said selectWoo behaviour and ajax hookup would be nice, but this is a good start

**Comment by mattsherman** [comment]
Searching/filtering and dynamic sources will definitely be coming in the future. There are some larger architectural pieces that need to be in place first, but we recognize that these are important needs for WooCommerce developers!
