### ISSUE TITLE
[CYS] Font inconsistencies between Assembler & Site Editor (Core only)

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#40587]
When exposing the new CYS flow in Core there is inconsistencies with the font between the Assembler & Site Editor. This is down to us not registering Google Fonts in WC Core by default.

More context on the issue and possible solutions can be found here p1696411326058159-slack-C053716F2H2

| Assembler | Site Editor |
| ------ | ----- |
| ![Screenshot 2023-10-04 at 11 19 17](https://github.com/woocommerce/woocommerce/assets/8639742/5d7a2d0d-1e4e-44a3-90a6-f3f8dae3c91f) | ![Screenshot 2023-10-04 at 11 25 19](https://github.com/woocommerce/woocommerce/assets/8639742/69fa71e2-615c-4c32-bb49-5bb48dba2f93) |

**Comment by adrianduffell** [comment]
Closing ths, the inconsistencies are now resolved.
