### ISSUE TITLE
Create variation switching

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#40591]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

From the single variation feature, is required to have a simple way to change across all the variations generated for a particular product, so the users don't need to go back and forth between pages to edit another variation.

AkVNGImLgSqCObTQ3idVn7-fi-7819_508730

**Epic**

https://github.com/woocommerce/woocommerce/issues/40304

**ACs**

- [ ] Display a variation switching bar at the bottom of the page. It's fixed and remains in place when the user scrolls.
- [ ] The bar has a subtle shadow and a 1px top border (Gutenberg-100) on the scroll. When the user scrolls to the bottom of the page, we remove the shadow and the border. AkVNGImLgSqCObTQ3idVn7-fi-7819_444061
- [ ] The left button links to the previous variation. If there isn't one, we don't show anything. On hover, it changes color to primary and displays a tooltip that reads: `Edit previous variation`. If there are unsaved changes, we show the browser confirmation dialog.
- [ ] If a variation doesn't have an image, we show a placeholder. AkVNGImLgSqCObTQ3idVn7-fi-7819_444685
- [ ] We don't show the bar if there are no previous and next variations to show.

**Comment by louwie17** [comment]
@jarekmorawski how should the variation switcher in the footer look like when other items are present in the footer, like the Share feedback bar for example? (btw the below screenshot doesn't contain the full styling yet ).
<img width="1227" alt="Screenshot 2023-10-10 at 5 02 09 PM" src="https://github.com/woocommerce/woocommerce/assets/2240960/03192232-1e54-42ca-b31e-12d7592679cf">

**Comment by jarekmorawski** [comment]
Hi @louwie17. As discussed here: https://github.com/woocommerce/woocommerce/issues/40304#issuecomment-1744815186, the feedback bar shouldn't be visible in the variation details screen.
