### ISSUE TITLE
Add Pricing tab to the single variation page

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#40593]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Single variation should has a way to modify pricing related fields independently.

AkVNGImLgSqCObTQ3idVn7-fi-7819_444392

**Epic**

https://github.com/woocommerce/woocommerce/issues/40304

**ACs**

- [ ] Everything works the same as in the main form.
- [ ] We remove the advanced section and bring out the tax class radio buttons.
- [ ] We don't show the `Charge sales tax on` section.
- [ ] We add a new option to the tax class section: `Same as main product`. It copies the tax class set on the parent.
- [ ] The tax class is automatically set to the same as the parent. The user can change it to something else.

**Comment by louwie17** [comment]
> We remove the advanced section and bring out the tax class radio buttons.

@jarekmorawski in the design the pricing tab only contains the `Charge sales tax on` radio button. But per the above acceptance criteria we should also show the tax class, like such?

<img width="758" alt="Screenshot 2023-10-06 at 11 10 58 AM" src="https://github.com/woocommerce/woocommerce/assets/2240960/08b460b7-892a-4188-ba90-273bd13c6cba">

**Comment by jarekmorawski** [comment]
Right! I forgot to add it back in after we pivoted from the modal design. We should show the tax class with a new option (`Same as main product`) and hide the `Charge sales tax on` buttons. The design is now updated. 👍
