### ISSUE TITLE
Add Delete variation item to the editor actions menu

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#40598]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Deleting a variation from the single variation page is required

AkVNGImLgSqCObTQ3idVn7-fi-7843_549988

**Epic**

https://github.com/woocommerce/woocommerce/issues/40304

**ACs**

- [ ] Choosing it launches the delete confirmation modal. AkVNGImLgSqCObTQ3idVn7-fi-8208_335309
- [ ] If the currently viewed variation is deleted, we automatically move on to the next one and show a snackbar message that reads: `[Variation name] deleted.`

**Out of the scope**

- The snackbar has a `Undo` button. Clicking it restores the previously deleted variation.

**Comment by mdperez86** [comment]
Hey @jarekmorawski please, can you confirm what should be the title and the message to show in the delete variation confirmation modal. AkVNGImLgSqCObTQ3idVn7-fi-1639_216855

**Comment by jarekmorawski** [comment]
Good question! Thanks for keeping an eye out for details, Maikel. Here's the design and the copy. I updated the ACs.

AkVNGImLgSqCObTQ3idVn7-fi-8208_335309
