### ISSUE TITLE
Download permissions granted not working Woo v8.1.1

### ISSUE THREAD

**Issue by BonnieBeeman** [woothemes/woocommerce#40621]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Granting Downloadable Permission in WooCommerce v.8.1.1 not working.  Customers granted access to a free downloadable product don't see the product in "My Account" | Downloads.   No email is sent to user.   

It seems this feature seems to conflict several WooCommerce settings such as: 
- WooCommerce order status (purchased vs. free)
- login status (logged on before new product added to order)
- database updates and synch (permissions seem to be based on email, but there is no report to view products associated with email)
- User and Product Download Permissions settings

### Expected behavior

Grant a new Download Permission to an existing order
Go to Order Actions and use drop-down to select "Regenerate Download Permission" 
Select "Update"
Customer is sent an email with the new product granted for download (for free, no charge)
Customer clicks on link in email and downloads new product

### Actual behavior

Customer has to be notified by separate email that a download is in their "My Downloads" directory
Customer logs on to account, but does not see the new granted Download

### Steps to reproduce

Steps to resolve the problem (unsuccessfully)
- Regenerate Download Permissions in both the Product page and the Order page  (0 orders updated)
- WooCommerce | Status | Tools | Run Synchronize approved download directories
- WooCommerce | Status | Tools | Run Update Database

### WordPress Environment

Wordpress v6.3.1
WooCommerce v8.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@BonnieBeeman Thanks for reporting the issue. Could you provide your System Status Report?
