### ISSUE TITLE
Adding cross-sell products to cart doesn't disappear before reloading the page

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#40654]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When having one or two cross-sell products and while in the cart with some product added already, then trying to add those cross-sell products to the cart doesn't hide them instantly but only after reloading the page.

### Expected behavior

Instantly hides cross-sell product after adding to cart

### Actual behavior

Cross-sell products still present after adding to cart, but disappear after reloading the page

### Steps to reproduce

1. Add a new simple product
2. Add 2 new simple products
3. Edit the 1st simple product from the 1st step and add the 2 new products as cross-sell
4. Save and go to the shop page
5. Add the 1st simple product to cart (the one from the 1st step)
6. Click on Add to cart button on the cross-sell product (the one under You may also like... section)
7. Observe issue
8. Check video: https://d.pr/i/lIqn3b

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@veljkho This seems like an expected behavior of the shortcode Cart page. We'll appreciate it if you try out the Cart and Checkout blocks for a better experience.

**Comment by veljkho** [comment]
Hi @tarunvijwani thanks for the feedback

How do you mean this seems like expected behavior for the shortcode version? Is there any other way I could test the same but with the WooCommerce Blocks plugin? I have one more issue to report but not using WCB plugin, but the Core and adding a new page with /cart block.
