### ISSUE TITLE
There's no auto scrolling when on the cart page and having some warnings on the top

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#40655]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Bad UX not to see auto-scrolling to the warning on the top after having some issues in the cart.

After trying to enter wrong zip code to calculate shipping, I was confused what was wrong... but then after some time and attempts to enter wrong zip code again and again.. that on the top is a warning message about wrong zip code entered.

Can we update this with auto-scrolling to the warning message?

### Expected behavior

Auto-scrolling to warning message in the cart

### Actual behavior

No auto-scrolling, the user don't see warning after entering wrong zip

### Steps to reproduce

1. Add some product to cart
2. Try to enter wrong zip to calculate shipping: USA, New York, 100AA
3. Click Update and observe issue
Check video: https://d.pr/i/Du188w

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@veljkho Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply. While this is very helpful, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility). We'll revisit the list of suggestions like this one once our priorities are updated. In the meantime, we'll appreciate it if you try out the Cart and Checkout blocks for a better experience.
