### ISSUE TITLE
Tracking cookie (`tk_ai`) is being set even when tracking is disabled.

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#40688]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

According to the [WooCommerce Cookies](https://woocommerce.com/document/woocommerce-cookies/) guide, the `tk_ai` cookie should only be set when usage tracking in enabled, however, that's not the case on all of my test sites. 

### Expected behavior

The cookie to be stored only when the merchant opt-in for tracking. 

### Actual behavior

The cookie being set regardless.

### Steps to reproduce

1. Navigate to any admin page while disabling usage tracking from `WooCommerce > Settings > Advance > WooCommerce.com`.

<img src="https://d.pr/i/sgWJlT+" alt="">
Link to image: https://d.pr/i/sgWJlT

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woo-cookie-test.local
Site address (URL): http://woo-cookie-test.local
WC Version: 8.2.0
REST API Version: ✔ 8.2.0
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.1.2
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Total Database Size: 5.26MB
Database Data Size: 3.60MB
Database Index Size: 1.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.52MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: JOD (د.ا)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 3
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-11 22:38:19 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Complete: 2
Oldest: 2023-10-10 22:39:54 +0000
Newest: 2023-10-10 22:39:54 +0000

Pending: 1
Oldest: 2023-10-11 22:39:54 +0000
Newest: 2023-10-11 22:39:54 +0000

### Status report information ###

Generated at: 2023-10-10 22:53:30 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Thanks for reporting! We'll look into fixing this.

**Comment by MorgusLethe** [comment]
I came here through google, trying to find out what the tk_ai is used for. I too was surprised that it popped up even from a private browsing window where the user is not signed in to a wordpress account (after adding an item to cart). I'm trying to find a way to disable it natively. I found [this post ](https://wordpress.org/support/topic/how-to-remove-cookies-tk_ai-cookie/) saying it's not possible.

**Comment by dartrax** [comment]
I have the same problem.

The file `class-jetpack-tracks-client.php` in `woocommerce/vendor/automattic/jetpack-connection/legacy` contains public function `get_anon_id()` that calls `setcookie( 'tk_ai', ...`.

- This function does not use `wc_setcookie(...)`, so there is no way to hook that with a filter and to filter the tk_ai cookie the easy way.
- This function gets called for example by `class-woopay-tracker.php` which comes with WooPayments.
- There may be other places or plugins that call this function.

Until this is fixed I'll have to delete the setcookie line from code and see if there are any negative side effects. Of course that will be need to redone with every woocommerce plugin update. I would prefer using `wc_setcookie(...)` so I can apply a filter in functions.php

**Comment by barryhughes** [comment]
> This function does not use wc_setcookie(...), so there is no way to hook that with a filter and to filter the tk_ai cookie the easy way.

This comes from a Jetpack library we are using, so `wc_setcookie` is not an option here. For this particular instance, we'll need to find another way.

**Comment by barryhughes** [comment]
I've prepared some changes that might help to reduce the potential for this, but actually I'm also struggling to replicate the conditions needed to see it when using WooCommerce alone.

> This function gets called for example by class-woopay-tracker.php which comes with WooPayments.

@dartrax can you confirm if you are also using Jetpack, and if so did you agree to their terms-of-service?

**Comment by barryhughes** [comment]
Removing from the high priority backlog, as it is not clear that this is a (currently) a bug in WooCommerce Core itself.

**Comment by dartrax** [comment]
> @dartrax can you confirm if you are also using Jetpack, and if so did you agree to their terms-of-service?

No, I don‘t use Jetpack, I don’t have that plug-in installed and I don‘t want it.

**Comment by barryhughes** [comment]
That's perfectly fine, I was asking as that may have been one of the reasons you were experiencing this. 

One further question, if I may: with tracking disabled via the WooCommerce settings, have you tried deleting the `tk_ai` cookie manually, via your browser's dev tools? If so, does that solve the problem or does the cookie simply get restored on the next request?

Asking this as I do notice that, in an environment where only WooCommerce is present (no WooPayments), the cookie will not automatically be cleaned up if you switch from tracking enabled to tracking disabled. However, it also will not automatically be restored if you do remove it.

**Comment by dartrax** [comment]
Yes, I‘ve deleted that cookie several times manually with the dev console, and it appears again. I know it exactly because I tried to understand where that comes from and how I could prevent it from happening, so I removed it several times, commented out some code lines and reloaded to see if it comes again.

**Comment by barryhughes** [comment]
So the original report describes a problem that could be seen in the admin environment. 

Do you also see this problem there, or is it only within the storefront/frontend? If the latter, and because it sounds like you are using WooPayments, I would draw your attention toward [this guidance](https://woocommerce.com/usage-tracking) (and the final bullet points for WooPayments specifically).

**Comment by barryhughes** [comment]
Checking in again, @dartrax and @Babylon1999. As I noted earlier, it doesn't seem possible to replicate this using WooCommerce Core alone. If I'm missing something, definitely let me know (and if the problem is triggered by a different plugin—a payment gateway or really any other extension—it would be best to report the bug on the appropriate issue tracker etc).

**Comment by dartrax** [comment]
I don't see this in the admin environment, only on storefront. It may be related to WooPayments since I'm using that.

However, the code that can set the cookie using `setcookie(...)` instead of `wc_setcookie(...)` is part of WooCommerce (see my first post in this report), and in my opinion, this should either be deleted if not used anymore (probably not a good option since it could break other plugins relying on that function) or being updated to use `wc_setcookie(...)`. 
But I've already reported that issue in #44116.

**Comment by Babylon1999** [comment]
Hey @barryhughes!

I'm still able to replicate this on a fresh installation of WordPress with WooCommerce only. 

https://github.com/woocommerce/woocommerce/assets/67080558/2897b271-7a7f-4c69-a024-8c5d06d92163

**Comment by nickpagz** [comment]
I can also replicate what @Babylon1999 is showing in the screencast.
For reference, I'm using a fresh/new site on Local by Flywheel for testing (same results on Studio), and WooCommerce 9.0.0 is the only installed plugin, without any setup - ie no payment gateways installed or setup.
The cookie won't appear on the front-end (even if logged in as an admin) except in cases where the cookie is already set. Visiting any admin page will cause the cookie to set.
I've also tested with disabling Analytics, Order Attribution, and Marketplace suggestions - the cookie is still set while on wp-admin pages.

**Comment by nickpagz** [comment]
@barryhughes The cookie is getting set [here](https://github.com/woocommerce/woocommerce/blob/c74015c5cb4c84af8accde4c9f00214ec1e62de5/plugins/woocommerce/includes/tracks/class-wc-tracks-client.php#L76) without any conditional check for the allow tracking option. The class is unconditionally loaded [here](https://github.com/woocommerce/woocommerce/blob/c74015c5cb4c84af8accde4c9f00214ec1e62de5/plugins/woocommerce/includes/class-woocommerce.php#L654). 
We either need to conditionally load the class like what is done [here](https://github.com/woocommerce/woocommerce/blob/c74015c5cb4c84af8accde4c9f00214ec1e62de5/plugins/woocommerce/includes/class-woocommerce.php#L683-L686), or check for the option with something like this in the `maybe_set_identity_cookie()` method:

```
if ( ! Constants::is_true( 'REST_REQUEST' ) && ! Constants::is_true( 'XMLRPC_REQUEST' ) ) {
	if ( 'yes' === get_option( 'woocommerce_allow_tracking' ) ) {
		wc_setcookie( 'tk_ai', $anon_id );
	}
}
```

or maybe even better something like this after the existing cookie check on [line 55](https://github.com/woocommerce/woocommerce/blob/c74015c5cb4c84af8accde4c9f00214ec1e62de5/plugins/woocommerce/includes/tracks/class-wc-tracks-client.php#L55):

```
// Bail if tracking is not allowed.
if ( 'yes' !== get_option( 'woocommerce_allow_tracking' ) ) {
	return;
}
```

I'm not familiar with the code base, so I'll leave it up to you to decide the best way to fix that.

Cheers!

**Comment by barryhughes** [comment]
Thanks, both. I can see it now (a little unsure why I couldn't earlier, however). We'll get a fix in place.

**Comment by bekihm** [comment]
@barryhughes We also facing this issue on our website and we need the fix because of an external audit of our website. Do you have a date for us when the fix will be released?

Thank you :-)

**Comment by barryhughes** [comment]
A fix is [under review](https://github.com/woocommerce/woocommerce/pull/47863) and, if it is merged soon, it should make it into the 9.2 release (provisionally scheduled for July 30).

**Comment by bekihm** [comment]
@barryhughes Is there already an update for version 9.2? I see only 9.1 is released.

**Comment by barryhughes** [comment]
Hi @bekihm: 9.2 should be available on August 13 (in just under one week).

https://developer.woocommerce.com/2024/07/26/woocommerce-9-2-pre-release-updates/
