### ISSUE TITLE
Remote inbox notification ad UI shifts/deletes rules unexpectedly

### ISSUE THREAD

**Issue by pierorocca** [woothemes/woocommerce#40693]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a series of rules setup in the AD UI on wooccommerce.com/admin in a remote inbox notification:

Active plugin
Store location
Plugin version
Custom 1
Custom 2
Custom 3

Removing the Active plugin rule caused Custom 3 to be overwritten by custom 2. It's almost like there's a bug in an array stack.

### Expected behavior

Deleting one rule should have no impact to the other rules

### Actual behavior

Deleting a rule impacts the other rules

https://github.com/woocommerce/woocommerce/assets/109928953/4d79a0b9-3d50-4c9c-ad46-c2318cd82579

### Steps to reproduce

Setup rules in a marketing RIN as described above. Delete the Active Plugin rule. Note the impact to the custom json.

### WordPress Environment

woocommerce.com/admin

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by pierorocca** [comment]
Given there's the possibility someone is going to publish a RIN with the wrong targeting criteria and not notice it, I'd recommend a 'high' priority.

**Comment by rrennick** [comment]
> woocommerce.com/admin

@pierorocca This repo is for issues with the WooCommerce plugin. I'll mark this as a support request which will add a comment including instructions for contacting support.
