### ISSUE TITLE
Attributes items are added automatically when adding an attribute

### ISSUE THREAD

**Issue by chrism245** [woothemes/woocommerce#40712]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The attribute section add all the items automatically, instead of letting you add the items you need to add to the attribute.

### Expected behavior

With previous WooCommerce version it let you add the attribute, and you need to manually add the items that you need, or you can add the items at once, but it doesn't force adding all the items.
![Screen Capture on 2023-10-11 at 07-41-42](https://github.com/woocommerce/woocommerce/assets/47186013/e75dd969-424d-4c63-abc4-867326ecc165)

### Actual behavior

The issue is with the recent WooCommerce 8.2 version. When you add an attribute, it automatically adds all the items on that attribute. This is not a problem when you have few items on it, but it is when you have multiple items, as it takes time and you need to manually delete those that are not needed.

![Markup on 2023-10-11 at 07_46_55](https://github.com/woocommerce/woocommerce/assets/47186013/50d07e00-a166-411f-9532-291c103fa5fc)

### Steps to reproduce

1. Create or edit a product.
2. Go to the attributes tab.
3. Add an attribute, and it will add all the attributes on it.

7152436- zen

### WordPress Environment

`

WordPress address (URL): https://woocommerce-1037968-3974242.cloudwaysapps.com/

Site address (URL): https://woocommerce-1037968-3974242.cloudwaysapps.com/

WC Version: 8.2.0

REST API Version: ✔ 8.2.0

WC Blocks Version: ✔ 11.1.2

Action Scheduler Version: ✔ 3.6.3

Log Directory Writable: ✔

WP Version: 6.3.1

WP Multisite: –

WP Memory Limit: 256 MB

WP Debug Mode: –

WP Cron: ✔

Language: en_US

External object cache: –

 

### Server Environment ###

 

Server Info: Apache/2.4.57 (Debian)

PHP Version: 7.4.33

PHP Post Max Size: 100 MB

PHP Time Limit: 300

PHP Max Input Vars: 10000

cURL Version: 7.64.0

OpenSSL/1.1.1n

 

SUHOSIN Installed: –

MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log

Max Upload Size: 100 MB

Default Timezone is UTC: ✔

fsockopen/cURL: ✔

SoapClient: ✔

DOMDocument: ✔

GZip: ✔

Multibyte String: ✔

Remote Post: ✔

Remote Get: ✔

 

### Database ###

 

WC Database Version: 7.8.2

WC Database Prefix: wp_

Total Database Size: 5.70MB

Database Data Size: 3.81MB

Database Index Size: 1.89MB

wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB

wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_bv_ip_store: Data: 0.28MB + Index: 0.22MB + Engine InnoDB

wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB

wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_options: Data: 2.44MB + Index: 0.03MB + Engine InnoDB

wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB

wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB

wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB

wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

 

### Post Type Counts ###

 

attachment: 1

page: 7

post: 2

product: 3

revision: 1

 

### Security ###

 

Secure connection (HTTPS): ✔

Hide errors from visitors: ✔

 

### Active Plugins (3) ###

 

Breeze: by Cloudways – 2.0.30

MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 5.25

WooCommerce: by Automattic – 8.2.0

 

### Inactive Plugins (2) ###

 

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3

Hello Dolly: by Matt Mullenweg – 1.7.2

 

### Dropin Plugins (1) ###

 

advanced-cache.php: advanced-cache.php

 

### Settings ###

 

API Enabled: –

Force SSL: –

Currency: USD ($)

Currency Position: left

Thousand Separator: ,

Decimal Separator: .

Number of Decimals: 2

Taxonomies: Product Types: external (external)

grouped (grouped)

simple (simple)

variable (variable)

 

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)

exclude-from-search (exclude-from-search)

featured (featured)

outofstock (outofstock)

rated-1 (rated-1)

rated-2 (rated-2)

rated-3 (rated-3)

rated-4 (rated-4)

rated-5 (rated-5)

 

Connected to WooCommerce.com: –

Enforce Approved Product Download Directories: ✔

HPOS feature screen enabled: –

HPOS feature enabled: –

Order datastore: WC_Order_Data_Store_CPT

HPOS data sync enabled: –

 

### WC Pages ###

 

Shop base: 6-zd-a8c - /shop

Cart: 7-zd-a8c - /cart

Checkout: 8-zd-a8c - /checkout

My account: 9-zd-a8c - /my-account

Terms and conditions: ❌ Page not set

 

### Theme ###

 

Name: Storefront

Version: 4.3.0 (update to version 4.5.3 is available)

Author URL: https://woocommerce.com/

Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

 

### Templates ###

 

Overrides: –

 

### Admin ###

 

Enabled Features: activity-panels

analytics

product-block-editor

coupons

core-profiler

customer-effort-score-tracks

import-products-task

experimental-fashion-sample-products

shipping-smart-defaults

shipping-setting-tour

homescreen

marketing

mobile-app-banner

navigation

onboarding

onboarding-tasks

product-variation-management

remote-inbox-notifications

remote-free-extensions

payment-gateway-suggestions

shipping-label-banner

subscriptions

store-alerts

transient-notices

woo-mobile-welcome

wc-pay-promotion

wc-pay-welcome-page

 

Disabled Features: customize-store

minified-js

new-product-management-experience

settings

async-product-editor-category-field

 

Daily Cron: ✔ Next scheduled: 2023-10-12 16:52:02 +00:00

Options: ✔

Notes: 63

Onboarding: -

 

### Action Scheduler ###

 

Complete: 4

Oldest: 2023-10-11 16:52:09 +0000

Newest: 2023-10-11 17:29:57 +0000

 

Pending: 3

Oldest: 2023-10-11 17:30:04 +0000

Newest: 2023-10-12 16:52:09 +0000

 

 

### Status report information ###

 

Generated at: 2023-10-11 17:30:45 +00:00

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by srj-github** [comment]
I second this!
Our site has a lot of attributes and this is slowing everybody down or even stopping  when creating a new product.
I rollbacked to previous version until this is resolved.

**Comment by mustardBees** [comment]
We're seeing this across our sites too. Client attempting to associate an attribute with 5k+ terms—doesn't make for a happy browser 💀

**Comment by jimjasson** [comment]
Hey everyone! 

Automatically selecting all the terms when adding a new global attribute to a product was a feature that was requested here: https://github.com/woocommerce/woocommerce/issues/37839

However, we are indeed seeing some performance issues in sites that have global attributes with a large amount of attribute terms. Behind the scenes, the code that automatically selects all terms triggers a click on the "Select all" button. It is likely that in the affected sites, clicking the "Select all" button on its own would lead to similar issues. 

We are still brainstorming the best way to move forward with this, but in the meantime, I will open a PR rolling back this feature in case we decide to follow that route.

**Comment by mustardBees** [comment]
@jimjasson 

> Automatically selecting all the terms when adding a new global attribute to a product was a feature that was requested here: [37839](https://github.com/woocommerce/woocommerce/issues/37839)

Thanks for the context. We agree a rethink is called for. For example, when adding a "brand" attribute, it seems counterintuitive to have all possible brands preselected. The "Select all" and "Select none" buttons should work perfectly in cases where you would want to bulk populate the values. However, we feel the default should be to select none.

**Comment by sharp1331** [comment]
It's a huge problem. Our team did not make a single product in 48 hours. Please fix it as soon as possible. We are losing money.

**Comment by daveloodts** [comment]
Hi, can i also make a request to make a better changelog listing please.
This exact features was announced as "Enhancement – Design enhancements for the Attributes tab" in the changelog. I assumed it was just "design", so reading that ticket was not on my list as the changelog list is already very lenghty.

**Comment by MrOizo79** [comment]
And you call this a FEATURE? aahahah
Man,  we got like 200 different colors attribute and now the system get frozen when we try to add an attribute to our product. It's a HUGE mistake and you should roll back immediately. I had to downgrade Woocommerce.

**Comment by MrOizo79** [comment]
This looks more a bug than a feature.
We got like 200 different colors attribute and now the system get frozen when we try to add an attribute to our product. It's a HUGE mistake and you should roll back immediately. I had to downgrade Woocommerce.
Make an option that you can decide if you want or not to add all attributes... like this is literally a bug.

**Comment by sharp1331** [comment]
Will you be looking into adding attributes automatically? Or do you not care about the opinion of users?

**Comment by philipdepalo** [comment]
We will also add this feature crashes our site.  For retail we use a Brands attribute and you can imagine there are thousands of Brands out there...that's a lot to load.  I can see the pros of automatically adding attributes that are small and used all the time. For example maybe you have a Mens Shirt Size attribute and you always load, XS, S, M, L, XL, XXL, XXXL.  And that's fast to load and if it doesn't come in an XXXL sometimes, you click X.  However, in our Brand example...that isn't helpful.

**Comment by uptowngeeks** [comment]
Same issue here. With several attributes with 100's of terms, we simply can't delete all of them, except for one. Whole day of production, lost. Not happy. Contemplating downgrading back to v8.1.1

**Comment by JessieBee3** [comment]
@jimjasson hit the nail on the head!

His suggestion sounds like the perfect fix. This is terrible UI for sites with tons of attributes. The default definitely needs to be none or add manually. My clients aren't adding any new products because it is tedious to remove everything before adding the needed terms. Please, please, please make this a high priority and fix it as soon as possible!

**Comment by seb2086** [comment]
Same issue here and my client is stuck and it's impossible for him to enter new products.
Please fix this issue quickly.
Thanks.

**Comment by rmbadaro** [comment]
Same problem here.

Stores with large variations in quantity are having their performance affected.

Please roll back this new feature. If anyone needs all variations to be created automatically, press the "select all" button.

**Comment by theo-gk** [comment]
Thanks for the fix. 

I really wonder if it was a good idea in the first place to add all attributes automatically. Typically, there are lots of terms in each attribute, which creates a major performance problem. 

Also, I can't think of a real-world scenario where adding all terms automatically is needed. I have set up over 200 e-shops and it hasn't occurred yet , not even once. Even if such a case exists, in most cases it's not useful and the shop manager will have to remove all the extra terms.
