### ISSUE TITLE
Create WCA Test Helper tool to reset Customize Your Store task

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40723]
Create a tool to enable testers to reset the Customize Your Store task back to an un-used state.

Delete the following options:

* woocommerce_customize_store_onboarding_tour_hidden
* woocommerce_admin_customize_store_completed
* wc_blocks_patterns_content

Execute the following SQL:

* `DELETE FROM wp_posts WHERE post_type = 'revision' and post_title = 'Custom Styles'`

**Comment by rjchow** [comment]
As investigated (p1697006582361329/1696918168.345359-slack-C01SFMVEYAK), this is insufficient

The tool will also need to reset the customisations made to the theme manually using the Site Editor
`Site Editor -> Templates -> Blog Home -> Clear customizations`

Ideally this tool should also reverse engineer the codepath that's executed through this manual workflow and include it as well
