### ISSUE TITLE
Shipping Settings: Handle long help tip text

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#40741]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

After a Shipping Class is added, configuring a Flat Rate method includes new fields. Since we programatically append the help text underneath the input, these look off since they are so long. Should we go back to the help tooltip for these or simply change the text?

<img width="565" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/1c18535f-cb8d-4a5b-8ef5-010e77aa8872">

For context, this help text is seen as a tooltip here in the legacy design:

<img width="1174" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/2092ce12-2cd8-4124-a757-9ed21ebc7eff">

**Comment by FlorianBru** [comment]
Hi @psealock, do you think it will take a lot of time to update the current form fields to our new react form fields as well? Because if that's the case, we definitely have other options regarding displaying help text. If not, I think we have options in terms of help text in the context of the current experience:
A) Use the tooltip
B) Dissolve the tooltip and display some sort of help text next to the label

**Comment by laurajohnsonwoo** [comment]
@FlorianBru updating to the form fields will cause breaking changes, so we need to introduce a "legacy" view to account for that, which isn't in scope. If possible, it would be good to dissolve the tooltip so the user knows what their options are without additional exploration.

**Comment by FlorianBru** [comment]
@laurajohnsonwoo @psealock What about this solution? I also tried to position the explanation of the formula directly below the input field, but that just takes too much space. So I would direct the merchants to a dedicated page where they learn how to enter advanced costs. 

URL: https://woocommerce.com/de-de/document/flat-rate-shipping/#advanced-costs

<img width="1440" alt="Group" src="https://github.com/woocommerce/woocommerce/assets/111048810/552033ee-9df1-43ea-b0de-18a098e82f47">

**Comment by laurajohnsonwoo** [comment]
@FlorianBru could you also please add a tooltip (or maybe instead) so the user can figure out what to do without leaving the screen?

**Comment by psealock** [comment]
We have a slight issue here which is we can't add text outside of the settings API `description` property which is used to populate the tooltip. This is because the JavaScript isn't setup to run translations. Here, I keep the tooltips as they are for cost related inputs and add Florian's link to the Shipping class costs description. What do you think?

<img width="641" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/5aa573bd-43d5-4a1d-bdb2-2471ad9b230b">

**Comment by FlorianBru** [comment]
As for the tooltip, maybe @lauroraa can look into that to create a more helpful copy guidance?

>We have a slight issue here which is we can't add text outside of the settings API description property which is used to populate the tooltip. This is because the JavaScript isn't setup to run translations. Here, I keep the tooltips as they are for cost related inputs and add Florian's link to the Shipping class costs description. What do you think?

@psealock Unfortunately that's a tricky one, since this copy also applies to the cost field above. Do we have other options somewhere else to display general guidance around the cost formula?

**Comment by lauroraa** [comment]
Is there somewhere I can find more info about how to calculate these shipping costs? It is very long, but without linking out I'm not sure how you'd get that formula info in to be any shorter than it is. The issue that I have here is that it's not clear _why_ you need to use a formula, or what terms like "percentage based fees" means. But there's also not really room to include that.

**Comment by psealock** [comment]
>@psealock Unfortunately that's a tricky one, since this copy also applies to the cost field above. Do we have other options somewhere else to display general guidance around the cost formula?

@FlorianBru I managed to find a place to generate the string in PHP then move it to the correct place using PHP. Its a bit dirty, but will work:

<img width="633" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/7eb72e3f-7aa2-4ccf-8f59-eb7b12362b69">

>The issue that I have here is that it's not clear why you need to use a formula, or what terms like "percentage based fees" means. But there's also not really room to include that.

@lauroraa With the text strings and their placement above, could we work in guidance on the why and rely on the link for further information?

**Comment by psealock** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/41035
