### ISSUE TITLE
Do not add all values when adding new attributes or variation options

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40747]
We've received feedback that adding all attribute values by default causes performance issues in larger stores. Let's change that behavior so the user can select attribute values manually. However, to help speed up the process, we can move the focus to the values field the moment the user selects or creates an attribute in the first dropdown.

Affects attributes and variation option management flows in the **new product editing experience**.

**Context**

pf59Ax-8w-p2

**Acceptance criteria**

- [ ] We update the behavior to only add all existing values at once if the attribute has fewer than 10 values.
- [ ] If the attribute has more values, we don't add any values automatically and let the user select them manually.

**Comment by dcgavril** [comment]
Having the same issue with the latest WC update on large shops that have 500+ attributes, when we want to add an attribute it preselects all the attributes automatically and it's completely blocking the page. Previously it was working fine, we would have the possibility to chose one or multiple attributes from the list. I will need to revert to the previous version of WC until this will be fixed because it's unusable. Please fix it. Thank you.

PS: it seems to be related to the changes done here:
"It automatically selects all the terms when a global Attribute is chosen." > #39987 @jimjasson

**Comment by d-solution-nl** [comment]
Having the same issue and negative impact on alot of customers which are not happy with this change. Cool feature if its optional or even per attribute. It's not workable when having a lot of global attribute and is having negative impact on peformance when adding unnecessary queries

**Comment by jimjasson** [comment]
Hey @jarekmorawski, 

This issue has already been resolved by: https://github.com/woocommerce/woocommerce/pull/40729 and the fix is included in v8.2.1.

**Comment by jarekmorawski** [comment]
Hi @jimjasson! I'm reopening it because it refers to the new product editing experience which uses the same behavior. We want to fix it there, too. I'll update the ACs to make that clearer.

**Comment by jimjasson** [comment]
Oh I see -- apologies!

**Comment by mdperez86** [comment]
> We update the behavior to only add all existing values at once if the attribute has fewer than 10 values.
 If the attribute has more values, we don't add any values automatically and let the user select them manually.

@jarekmorawski @pmcpinto @louwie17  This behavior can be perceived like a bug for the end user. I feel like it's a little confusing because some attribute will have auto select and others won't.

I think we should not have auto select or, if we have it, then the auto select can be capped to just a fixed number.

**Comment by pmcpinto** [comment]
> if we have it, then the auto select can be capped to just a fixed number.

@mdperez86 can you explain this option? Thanks.

**Comment by louwie17** [comment]
> @mdperez86 can you explain this option? Thanks.

My guess is what @mdperez86 means, is that we always add the first 10 of any attribute.
So if an attribute has 5 terms, we just auto add those 5. But if an attribute has 80 terms, we just add the first 10.

**Comment by pmcpinto** [comment]
Thanks for the clarification. 

> But if an attribute has 80 terms, we just add the first 10.

This would still be a confusing experience for merchants. To have a smooth experience, I think we should include a select all option to accommodate this use case. cc @jarekmorawski @j111q for feedback.

**Comment by jarekmorawski** [comment]
I agree. Imho, we should have a `Select all` button in the dropdown, similar to the `Create new` button. It should be fixed, so it's always in reach when the user scrolls through the list.

<img width="688" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/6927e9da-2ea9-4c1f-a7ef-5f2154e92c01">

**Comment by octaedro** [comment]
Hey @jarekmorawski,

The `Select all` button sounds good to me. I also noticed that in the design you shared we show the `Create new` button when the terms list is not empty.

Currently, we're only showing the `Create new` button when the user starts typing the new term name in the input.
Is it expected to show that button with the list populated? In that case, we should consider how to add the new term name, perhaps using a modal or something similar.

**Comment by jarekmorawski** [comment]
> In that case, we should consider how to add the new term name, perhaps using a modal or something similar.

Yup! We already have a category creation modal: AkVNGImLgSqCObTQ3idVn7-fi-3301_304911

**Comment by ramyBns** [comment]
Hello, did you guys fix the issue ?

**Comment by pmcpinto** [comment]
> Hello, did you guys fix the issue ?

Hey @ramyBns the fix in the classic experience was included in v8.2.1. This issue refers to the changes to the new experience.

**Comment by nathanss** [comment]
Closing the issue, as we currently have pagination for attributes and only load 10 entries, so it doesn't apply anymore.
