### ISSUE TITLE
🐞 woocoomerce 8.2.0 bug (Automatic selection of attributes)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#40788]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team,

I'm not sure if anyone has reported this before. But after updating WooCommerce to the new version, when we add an attribute, all the values ​​of that attribute (which we previously defined in the attributes section) are added automatically. This was reported by several other users in a WooCommerce group.

### Expected behavior

When we add an attribute, it should not add any value by default. But we have to choose them.

### Actual behavior

But in the new version, immediately after adding an attribute, all its options are automatically added.

### Steps to reproduce

Sorry, the video below is not in English. But the bug is completely detectable.

https://github.com/woocommerce/woocommerce/assets/77163248/f7a75f84-72a2-4bc1-97a6-82515e2eaed0

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kepo123** [comment]
https://github.com/woocommerce/woocommerce/assets/17118210/0bd6d844-a24a-4e05-b445-dfb620d885fe

I can confirm this bug. It happens after updating it to the latest version. It automatically adds all values that are in the attribute.

**Comment by jorgeatorres** [comment]
Thanks for reaching out! This was already reported in #40712. We have a fix and should be released very soon.
