### ISSUE TITLE
Customize Your Store color palette not restricted on Woo Express

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40822]
This affects Woo Express, but ideally the fix should be generalized in Core

On a Jurassic Ninja site, the color palette is restricted as expected:

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/c4380585-f3ac-4ec0-9aae-ea864d2f49b8)

However, on Woo Express, it contains additional options:

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/0d84a4c8-62b1-42bf-a1ac-8decb626bb34)

**Comment by moon0326** [comment]
@adrianduffell I was able to reproduce it yesterday, but I can't anymore for some reason 🤔 

I've tested both the latest trunk and WC version.

Could you please confirm?

**Comment by adrianduffell** [comment]
Hey @moon0326 , yes I still see it on Woo Express by installing the [nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly) of WC.


![Image](https://github.com/woocommerce/woocommerce/assets/9312929/fcb162e8-9933-4c0a-aa4e-0c6a80943676)

**Comment by moon0326** [comment]
> Hey @moon0326 , yes I still see it on Woo Express by installing the [nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly) of WC.
> 
> ![Image](https://user-images.githubusercontent.com/9312929/277877998-fcb162e8-9933-4c0a-aa4e-0c6a80943676.png)

Sorry for the delay in response and thanks for the info. I'll re-test it.
