### ISSUE TITLE
[DOC-BUG]

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [woothemes/woocommerce#40836]
## Link to the Page/Section
https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions

## Description of the Suggestion
This code from the HPOS recipe book:
```php
$screen = wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';
```

could trigger this error in some cases:
```php
PHP Fatal error: Uncaught Automattic\WooCommerce\Vendor\League\Container\Exception\NotFoundException: Alias (Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController) is not being managed by the container or delegates
```

## Solution
Just check for the `\Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController` class first:
```php
$screen = class_exists( '\Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController' ) && wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';
```

**Comment by evgen77** [comment]
Hi, have you solved this problem?

**Comment by pablo-sg-pacheco** [comment]
Kind of :)

You just have to check if the class exists:
```php
class_exists( '\Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController' )
```

In the end it could be like this:

From:
```php
$screen = wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';
```

To:
```
$screen = class_exists( '\Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController' ) && wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';
```

**Comment by evgen77** [comment]
Cool! its work ty!

**Comment by pablo-sg-pacheco** [comment]
;)

**Comment by jorgeatorres** [comment]
Hi @pablo-sg-pacheco!

Thanks for the report 💯. Would you mind clarifying what the cases where you've seen that error being triggered are? Depending on where or when you're calling the code, it is true that you might need to check that the class exists, but that'd be true for other libraries or WP itself.

In the specific context (`add_meta_boxes`) of the example we have on our recipe book, everything that the code snippet uses should be available, though.

We could add some clarification that the class needs to exist to be used (i.e. initialization of HPOS should've happened), but I'm curious to see what your use case was. Thanks again!

**Comment by pablo-sg-pacheco** [comment]
Hi @jorgeatorres ,

I'm a WP/WC plugin developer. After adding the code you have suggested in one of my plugins in the context of `add_meta_boxes`, one customer of ours returned to us about that error:
```
PHP Fatal error: Uncaught Automattic\WooCommerce\Vendor\League\Container\Exception\NotFoundException: Alias (Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController) is not being managed by the container or delegates 
```

Actually, I couldn't reproduce the error myself, but I know my suggestion fixes it because it simply checks if the file exists and the customer also said the error was gone, so I thought it could be a good idea to suggest it here for you guys. Most probably, other developers will copy the code from your HPOS upgrade recipe book and the error should trigger for someone else.

**Comment by jorgeatorres** [comment]
Hi @pablo-sg-pacheco! I've added your suggestion to the wiki page, though we're planning to revamp the whole document with a few more details and also migrate it to the new docs site. We're still using the wiki as source, so this edit will be preserved. Thanks again for reaching out!
