### ISSUE TITLE
Update the URLs in the Orders related `e2e-pw` tests to use the HPOS URLs

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#40846]
### Describe the solution you'd like

As HPOS is now the default for new installs, we can update the orders-related URLs to use the new format

e.g. 
`wp-admin/edit.php?post_type=shop_order`
can become
`wp-admin/admin.php?page=wc-orders`

`wp-admin/post.php?post=${ orderId }&action=edit`
can become
`wp-admin/admin.php?page=wc-orders&action=edit&id=${ orderId }`
etc

### Describe alternatives you've considered

N/A

### Additional context

Example orders test locations:
`plugins/woocommerce/tests/e2e-pw/tests/merchant`
such as:
`plugins/woocommerce/tests/e2e-pw/tests/merchant/order-coupon.spec.js`
`plugins/woocommerce/tests/e2e-pw/tests/merchant/order-edit.spec.js`
etc

**Comment by rrennick** [comment]
@lanej0 Is there anything left to do with this one?

**Comment by nigeljamesstevenson** [comment]
Looking at the scripts mentioned in the example, they are still referencing the old URLs

E.g. `/wp-admin/post-new.php?post_type=shop_order` - however, when we input this URL manually on a site with HPOS enabled then it redirects to the HPOS format `/wp-admin/admin.php?page=wc-orders&action=new`

**Comment by lanej0** [comment]
Got a PR open to make these updates now.  Thanks @nigeljamesstevenson
