### ISSUE TITLE
wc_customer_bought_product() function causes excessive page load time

### ISSUE THREAD

**Issue by MKJJJ** [woothemes/woocommerce#40841]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The wc_customer_bought_product() function slows down product pages massively. It can take up to 60 seconds (!!!) to load the page, which is absolutely inacceptable. It took me ages to find out what was going on. This problem appeared some weeks ago for the first time.

A similar issue was reported on [Github](https://github.com/woocommerce/woocommerce/issues/8458). It was tagged as resolved, but it is not resolved at all. The problem does not occur if the user is not logged in.

I ran all conflict tests on a staging server, but couldn't find any conflicts. I used the same (huge) database. So, this is not the issue

The only pattern I can see is that this database query does not show, if page load time is ok. Again, it DOES NOT SHOW at all. Why is that? Why would this database query sometimes run and sometimes not, if everything else is exactly the same?

Removing the function from the Woocommerce core (or better: emptying it) seems to fix the problem.

### Expected behavior

The product page should load faster.

### Actual behavior

The product page loads extremely slow after logging in.

### Steps to reproduce

![woo](https://github.com/woocommerce/woocommerce/assets/59731099/e4e86a8c-2353-4c6c-97c5-0dee025ffcf2)

### WordPress Environment

WordPress address (URL): https://www.
Site address (URL): https://www.
WC Version: 8.2.0
REST API Version: ✔ 8.2.0
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.22
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.5.22-MariaDB-1:10.5.22+maria~ubu2004-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 3603.80MB
Datenbank-Datengröße: 2147.57MB
Datenbank-Indexgröße: 1456.23MB
wp_woocommerce_sessions: Daten: 13.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 90.61MB + Index: 30.56MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 796.98MB + Index: 569.86MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 4.36MB + Index: 4.69MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 4.28MB + Index: 3.13MB + Engine InnoDB
wp_adtribes_my_conversions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aepc_custom_audiences: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aepc_logs: Daten: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Daten: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_ayssurvey_answers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_popup_surveys: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_questions: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_question_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_sections: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_submissions: Daten: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_submissions_questions: Daten: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_surveys: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_ayssurvey_survey_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_borlabs_cookie_statistics: Daten: 4.03MB + Index: 4.99MB + Engine MyISAM
wp_bounced_email_logs: Daten: 13.52MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cmplz_cookies: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_cmplz_services: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Daten: 11.52MB + Index: 10.03MB + Engine InnoDB
wp_comments: Daten: 130.66MB + Index: 89.25MB + Engine InnoDB
wp_cr_local_forms: Daten: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_index: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Daten: 1.17MB + Index: 1.41MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Daten: 0.45MB + Index: 0.28MB + Engine InnoDB
wp_dgwt_wcas_stats: Daten: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_var_index: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_email_log: Daten: 24.52MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fql_logs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_iconic_wssv_index: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_opaque_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg6_database_475011: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg6_database_570: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg6_maps: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_mapsvg6_r2o: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_mapsvg6_regions_475011: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg6_regions_570: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg6_schema: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mapsvg6_settings: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mapsvg_database_475011: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg_database_570: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg_r2d: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mapsvg_regions_475011: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg_regions_570: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mapsvg_schema: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mclean_refs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mclean_scan: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mlw_qm_audit_trail: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlw_questions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlw_question_terms: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mlw_quizzes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlw_quiz_theme_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlw_results: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlw_themes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Daten: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_newsletter_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Daten: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_user_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 9.25MB + Index: 1.41MB + Engine InnoDB
wp_postmeta: Daten: 700.98MB + Index: 524.80MB + Engine InnoDB
wp_posts: Daten: 115.59MB + Index: 76.83MB + Engine InnoDB
wp_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Daten: 2.16MB + Index: 0.37MB + Engine MyISAM
wp_redirection_groups: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Daten: 0.17MB + Index: 0.13MB + Engine MyISAM
wp_redirection_logs: Daten: 0.28MB + Index: 0.06MB + Engine MyISAM
wp_spbc_auth_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_backuped_files: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_backups: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall_data: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_firewall_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_frontend: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_links_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_spbc_scan_results: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_scan_signatures: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_traffic_control_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_storeabill_documentmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_storeabill_documents: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_storeabill_document_itemmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_storeabill_document_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_storeabill_document_noticemeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_storeabill_document_notices: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_storeabill_journals: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sumo_tbl_user_earned_coupon: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Daten: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_updraftcentral_sitemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_updraftcentral_sites: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_site_temporary_keys: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_user_cron: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 40.56MB + Index: 30.11MB + Engine InnoDB
wp_users: Daten: 3.52MB + Index: 1.22MB + Engine InnoDB
wp_usin_events: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usin_user_data: Daten: 0.31MB + Index: 0.26MB + Engine MyISAM
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 25.55MB + Index: 13.06MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 29.55MB + Index: 21.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 21.55MB + Index: 13.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 12.55MB + Index: 10.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Daten: 0.09MB + Index: 0.04MB + Engine MyISAM
wp_wdp_order_items: Daten: 0.06MB + Index: 0.06MB + Engine MyISAM
wp_wdp_persistent_rules_cache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdp_rules: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_discounts: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_item_discounts: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wdr_rules: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Daten: 0.27MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Daten: 5.52MB + Index: 3.03MB + Engine InnoDB
wp_wftrafficrates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_amazon_buyer_index: Daten: 0.04MB + Index: 0.06MB + Engine MyISAM
wp_woocommerce_gpf_google_taxonomy: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_packagingmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_shipmentmeta: Daten: 32.56MB + Index: 12.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 7.52MB + Index: 4.55MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 16.55MB + Index: 16.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 4.52MB + Index: 6.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_shipment_labels: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpr_rocket_cache: Daten: 0.07MB + Index: 0.07MB + Engine MyISAM
wp_wpr_rucss_used_css: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_action_history: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_mapping_template: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Daten: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Daten: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_bans: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_elements: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_other_answers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_polls: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_skins: Daten: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_subelements: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_votes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 3
attachment: 1923
ays-survey-maker: 6
blocks: 12
boxzilla-box: 1
br_notice: 2
custom_css: 2
customerstory: 1
document_template: 11
gp_elements: 6
invoice: 2
jetpack_migration: 2
kundenstory: 79
mailpoet_page: 1
mapsvg: 2
mc4wp-form: 1
ml-slide: 23
ml-slider: 8
nab_experiment: 7
nav_menu_item: 53
oembed_cache: 25
page: 52
post: 1
product: 81
product_variation: 68
qsm_quiz: 1
revision: 2
schema: 4
shop_coupon: 286
shop_order: 167353
shop_order_refund: 2287
wafs: 1
was: 15
wll_records: 1708
wp-rest-api-log: 2315
wpcf7_contact_form: 2
wpsl_stores: 71
ywrfd-discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Query Monitor: von John Blackbourn – 3.13.1
Advanced Custom Fields PRO: von WP Engine – 6.2.1.1
FiboSearch - AJAX Search for WooCommerce (Pro): von FiboSearch Team – 1.25.0
Cache Enabler: von KeyCDN – 1.8.13
Complianz | GDPR/CCPA Cookie Consent: von Really Simple Plugins – 6.5.5
Contact Form 7: von Takayuki Miyoshi – 5.8.1
Customer Reviews for WooCommerce: von CusRev – 5.36.3
GTM4WP: von Thomas Geiger – 1.18.1
Fluent Query Logger: von techjewel – 1.0.0
GP Premium: von Tom Usborne – 2.3.2
Rechtstexte-Schnittstelle der IT-Recht Kanzlei: von IT-Recht Kanzlei – 1.0.6
Min and Max Quantity for WooCommerce: von BeRocket – 1.3.3
Newsletter: von Stefano Lissa & Das Newsletter Team  – 7.9.9
Payment Plugins for PayPal WooCommerce: von Payment Plugins
support@paymentplugins.com – 1.0.39

Redirection: von John Godley – 5.3.10
WooCommerce Show Single Variations by Iconic: von Iconic – 1.15.2
Side Cart WooCommerce: von XootiX – 2.4.4
Survey Maker: von Survey Maker team – 3.7.9
Advanced Editor Tools: von Automattic – 5.9.2
vendidero Helper: von vendidero – 2.2.1
Woo Discount Rules: von Flycart – 2.6.2
WooCommerce Permalink Manager (Premium): von premmerce – 2.0.1
Product Feed PRO for WooCommerce: von AdTribes.io – 13.0.4
Payment Plugins for Stripe WooCommerce: von Payment Plugins
support@paymentplugins.com – 3.3.50

WooCommerce Advanced Shipping: von Jeroen Sormani – 1.0.14
WooCommerce Color or Image Variation Swatches: von sysbasics – 3.8.3
WooCommerce Amazon Pay: von WooCommerce – 2.5.0
Germanized für WooCommerce Pro: von vendidero – 3.7.3
Germanized für WooCommerce: von vendidero – 3.13.5
WooCommerce Product Dependencies: von SomewhereWarm – 1.2.8
WooCommerce Price Based on Country: von Oscar Gare – 3.3.0
Sofort Banking for WooCommerce: von Sven Wagener – 1.5.1
WooCommerce Sponsor a Friend Plugin: von MB Création – 2.3.2
WooCommerce: von Automattic – 8.2.0
Yoast SEO: von Team Yoast – 21.3
WP Store Locator: von Tijmen Smit – 2.2.241

### Inactive Plugins (6) ###

Email Log: von Sudar – 2.4.8
heidelpay WooCommerce: von heidelpay – 1.6.0
Invisible reCaptcha: von Mihai Chelaru – 1.2.3
Nelio A/B Testing: von Nelio Software – 6.0.9
WooSwatches Mod - Woocommerce Color or Image Variation Swatches: von woomatrix – 2.8.5 (Pixelpulli Mod)
WP Rocket: von WP Media – 3.15.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #503048 - /alle-ago-produkte/
Warenkorb: #72 - /warenkorb/
Kasse: #12 - /kasse/
Mein Konto: #70 - /mein-konto/
Allgemeine Geschäftsbedingungen: #688 - /allgemeine_geschaeftsbedingungen/

### Theme ###

Name: GeneratePress Child Theme
Version: 1.0
Author URL: https://my-blog-shop.de
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.3.1
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: generatepress_child/woocommerce/cart/cart.php
generatepress_child/woocommerce/emails/customer-note.php
generatepress_child/woocommerce/emails/customer-processing-order.php
generatepress_child/woocommerce/single-product/add-to-cart/variation.php

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 46.223.162.111
Real external IP: 2a02:8071:3e82:9580:4412:29d6:a5c1:5813
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 3.3.0
Base location: DE:DE-NW
Base currency: EUR
Price Based On: shipping
Shipping: –
Test mode: –
Test country: –
Load products price in background: –
Prices entered with tax: ✔
Calculate tax based on: shipping
Display prices in the shop: incl

### Zone Pricing Drittländer ###

zone_id: drittlaender
enabled: yes
name: Drittländer
countries: CH
currency: EUR
exchange_rate: 0.840336134454
auto_exchange_rate: no
disable_tax_adjustment: no
order: 9999

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-12 10:42:20 +02:00
Options: ✔
Notes: 17
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 10.292
Oldest: 2023-09-11 07:01:39 +0000
Newest: 2023-10-12 06:59:48 +0000

Fehlgeschlagen: 861
Oldest: 2022-04-02 12:42:30 +0000
Newest: 2023-10-11 11:15:14 +0000

Ausstehend: 6
Oldest: 2023-10-12 08:09:18 +0000
Newest: 2023-10-13 05:38:36 +0000

### Status report information ###

Generated at: 2023-10-12 09:01:17 +02:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Thanks for reaching out, @MKJJJ! We'll be looking into this. We believe there are better alternatives that we could use here such as storing this in user meta or directly as metadata in review comments.

**Comment by MKJJJ** [comment]
This is a suggestion from the Woocommerce support forum on wordpress.org

`remove_action( 'woocommerce_after_single_product_summary', 'wc_customer_bought_product', 10, 1 );`

Unfortunately, it does not work at all. The function is still running on the product page, if the user is logged in.

**Comment by jorgeatorres** [comment]
Hi @MKJJJ!

I don't think that really does the trick. Until we properly fix this, I'd just suggest disabling purchase verification for product reviews under WC > Settings > Products > Reviews.
That said, it does mean someone can post a review even without having purchased the product.

<img width="620" alt="Screenshot 2023-11-06 at 14 59 11" src="https://github.com/woocommerce/woocommerce/assets/184724/d47f8c87-d11f-4bb9-ae93-985919ce5daf">

If that's an option for your site, I believe that should remediate the performance impact.

**Comment by MKJJJ** [comment]
Awesome! Thank you! I think, that did the trick. For us, that's an acceptable workaround. We approve all reviews manually. However, this might not be a solution for other users.

**Comment by shaunek-hero** [comment]
We have this same perf issue, in our case it takes the query about 15-19 seconds to run. It is a huge annoyance for logged in customers and also logged in administrators. 

In our case we *really strongly* prefer to have reviews only be left by verified owners though, so we are hopeful that Woocommerce will fix the underlying perf problem.

Is this issue being worked on for the next release of Woocommerce? Is this ticket tracking it or is there another Github issue I should be following for updates on this.

**Comment by shaunek-hero** [comment]
FYI to others coming across this issue, the `Reviews can only be left by "verified owners"` setting is the one to disable, at least for me it was the one that caused the slow query. The `Show "verified owner" label on customer reviews` setting does not have a perf impact, so you can leave it enabled if you want.

**Comment by MKJJJ** [comment]
Thanks for the info. However, this needs to be fixed. This bug will make the function unusable for larger shops. It is a known problem that Woocommerce does not scale up very well. We have around 100.000 orders in the database which is not THAT much. This leads to millions of rows in the postmeta table, that causes the problem.

**Comment by vedanshujain** [comment]
Note that this query is about 10x (or more, depending upon the number of orders for customers) faster with HPOS as it doesn't need the dual join on postmeta table for billing email and customer ID. Additionally, we can explore making it faster by adding a combined an index on order_item_id, meta_key in the items table. We'd highly recommend switching if possible.

On HPOS:
<img width="1454" alt="Screenshot 2024-06-04 at 4 01 17 PM" src="https://github.com/woocommerce/woocommerce/assets/7571618/3cfeb5fb-c96e-4473-8781-542ee8a6f585">


On Posts:
<img width="1427" alt="Screenshot 2024-06-04 at 4 02 11 PM" src="https://github.com/woocommerce/woocommerce/assets/7571618/954cef62-c535-4bbb-a9dd-c58c624a8293">

We are also adding a micro-optimization for #48139, but let us know if it's still slow and we can make further improvements.

**Comment by MKJJJ** [comment]
Thanks for the valuable contribution!

**Comment by shaunek-hero** [comment]
@vedanshujain this is very helpful information, indeed. This one site wasn't able to migrate over to HPOS last fall due to some plugins that were incompatible at the time, this is a great reminder to check on the possibility of migrating again.
