### ISSUE TITLE
Transparent images render with black background in pattern assembler

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40878]
![Image](https://github.com/woocommerce/woocommerce/assets/9312929/bcf01f94-00b6-4a54-ad2a-94a4d9fb17d9)

**Comment by moon0326** [comment]
@adrianduffell  I wasn't able to reproduce it on a JN site. Could you upload your png file? 

I've attached my test png file for your tests.
![kisspng-word-drawing-clip-art-sample-ballot-5b20b6f06b3865 3291979315288706404392](https://github.com/woocommerce/woocommerce/assets/4723145/32bf80dd-0b7d-42e7-b3c5-e40bfdaa3833)


![Screen Shot 2023-10-19 at 4 27 09 PM](https://github.com/woocommerce/woocommerce/assets/4723145/94ccb74f-b4ba-406c-ad56-3e3fffeff3f2)

**Comment by chihsuan** [comment]
This issue has been fixed in https://github.com/woocommerce/woocommerce/pull/41017/files#diff-d23361f8bdcc391d5b62b8b21b32f2f44497df7a4e86caa43805913e653467e3R25-R32
