### ISSUE TITLE
[External products] Create the ExternalAffiliateProduct template

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#40873]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Before starting with this kind of product a new template is required, also loading the right template given the product type to successfully load the editor.

**ACs**

- [ ] Create the ExternalAffiliateProductTemplate (Copy the SimpleProductTemplate)
- [ ] Change the logic to load that template before rendering the editor

**Comment by nathanss** [comment]
We decided to use conditional visibilities instead of creating a separate Template for now, since this type of product is very similar to Simple.
