### ISSUE TITLE
WcPayWelcomePage Slow Query (Similiar to 8.0.3 fix)

### ISSUE THREAD

**Issue by Raydelta** [woothemes/woocommerce#40889]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A slow Query is now appearing on multiple sites using Woocommerce 8.1.1 to 8.2.1, on Wordpress 6.3.2 (and the version before).~

**The Query is:**

SELECT wp_posts.ID
FROM wp_posts
WHERE 1=1
AND ( wp_posts.post_date_gmt >= '2023-07-21 23:11:04' )
AND wp_posts.post_type IN ('shop_order', 'shop_order_refund')
AND ((wp_posts.post_status = 'wc-processing'
OR wp_posts.post_status = 'wc-completed'))
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1

**The Caller information is:**

WP_Query->get_posts
WP_Query->query
WP_Query->__construct
WC_Order_Data_Store_CPT->query
WC_Data_Store->__call
WC_Order_Query->get_orders
wc_get_orders
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->get_incentive
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->must_be_visible
Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->register_payments_welcome_page
do_action('admin_menu')
require_once('wp-admin/includes/menu.php')
require('wp-admin/menu.php')

**Time: 0.6804s**

As you can see, this seems to be linked to woocommerce payments incentive, which was fixed in version 8.0.3 (29th August). This slow query runs on every single admin backend page, similiar to the previous issue patched in 8.0.3.

### Expected behavior

On version 8.0.3 on 3 different sites, there are no slow querys. After updating to 8.1.1 or 8.2.1 the slow query is present on every single loading of the backend, orders, updates, settings pages etc.

### Actual behavior

Slow query appears as above.

### Steps to reproduce

Update to 8.2.1 and install query monitor, navigate to orders and look at the slow query.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://mysite.co.uk
Site address (URL): https://mysite.co.uk
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: wp_
Total Database Size: 6444.89MB
Database Data Size: 4200.05MB
Database Index Size: 2244.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 50.58MB + Index: 15.55MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 549.00MB + Index: 582.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 48.58MB + Index: 54.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 54.59MB + Index: 32.08MB + Engine InnoDB
wp_adl_lp_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 1.52MB + Index: 0.08MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.39MB + Index: 0.09MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.33MB + Index: 0.27MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 234.78MB + Index: 137.41MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.05MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mdf_stat_buffer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mdf_stat_tmp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myarcadegames: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_myarcadehighscores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myarcademedals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myarcadescores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myarcadeuser: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myarcade_plays: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 10.23MB + Index: 1.22MB + Engine InnoDB
wp_patchstack_event_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_patchstack_firewall_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_patchstack_logic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pimwick_affiliate: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pmxe_exports: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 2318.58MB + Index: 1125.88MB + Engine InnoDB
wp_posts: Data: 343.66MB + Index: 66.14MB + Engine InnoDB
wp_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_product_order: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_contestants: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_giveaways: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rafflepress_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_adsense: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 1.27MB + Index: 0.33MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_referal_product_commission: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_referal_program: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_referal_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.31MB + Index: 0.41MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_usermeta: Data: 117.66MB + Index: 102.27MB + Engine InnoDB
wp_users: Data: 6.52MB + Index: 5.55MB + Engine InnoDB
wp_vivawallet_data: Data: 25.56MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_lottery_log: Data: 146.20MB + Index: 0.00MB + Engine InnoDB
wp_wc_lottery_pn_log: Data: 157.22MB + Index: 0.00MB + Engine InnoDB
wp_wc_lottery_pn_reserved: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 70.61MB + Index: 76.19MB + Engine InnoDB
wp_wc_order_stats: Data: 39.58MB + Index: 30.61MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.55MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.22MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwafconfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.27MB + Index: 0.02MB + Engine InnoDB
wp_wpdatacharts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpdatatables_rows: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsal_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 2
attachment: 11703
custom_css: 2
elementor_font: 1
elementor_library: 15
elementor_snippet: 3
GOTMLS_quarantine: 1
lty_lottery_ticket: 47
mt_pp: 106
nav_menu_item: 8
oembed_cache: 45
page: 16
post: 1866
product: 1998
revision: 6741
seedprod: 1
shop_coupon: 1328
shop_order: 335840
shop_order_refund: 166
user_request: 36
wmc-banner: 8
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
lottery (lottery)
simple (simple)
store_credit (store_credit)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block. (using elementor basket widget)
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #133 - /terms-and-conditions/

### Theme ###

Name: CC Astra
Version: 1.0.0
Author URL: mysite
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.3.1
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-20 11:56:31 +01:00
Options: ✔
Notes: 179
Onboarding: completed

### Action Scheduler ###

Complete: 2,086
Oldest: 2023-09-23 21:38:18 +0100
Newest: 2023-10-20 00:32:04 +0100

Failed: 15
Oldest: 2022-12-01 14:44:33 +0000
Newest: 2023-06-14 11:30:01 +0100

Pending: 1
Oldest: 2023-10-21 00:05:03 +0100
Newest: 2023-10-21 00:05:03 +0100

### Status report information ###

Generated at: 2023-10-20 01:21:12 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by amElnagdy** [comment]
Had the same issue and disabling the option `Display suggestions within WooCommerce` under WooCommerce → Settings → Advanced → WooCommerce.com helped with fixing the issue.

Direct link: wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com

**Comment by vbelolapotkov** [comment]
@woocommerce/moltres could you please take a look? I see that there were fixes shipped before in 8.0.3 and 8.1.0 (https://github.com/woocommerce/woocommerce/issues/39742#issuecomment-1715509714) but SSR here is for Woo 8.2.1.

**Comment by saeedsohrabi71** [comment]
> Had the same issue and disabling the option `Display suggestions within WooCommerce` under WooCommerce → Settings → Advanced → WooCommerce.com helped with fixing the issue.
> 
> Direct link: wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com



> Had the same issue and disabling the option `Display suggestions within WooCommerce` under WooCommerce → Settings → Advanced → WooCommerce.com helped with fixing the issue.
> 
> Direct link: wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com

thanks Bro it works! :)

**Comment by vladolaru** [comment]
We have https://github.com/woocommerce/woocommerce/pull/41466 by implementing transient caching for the DB query to avoid it as much as possible. The fix will be included in the WooCommerce 8.4.0 release (or maybe in an 8.3.x patch release if that is possible).

Thank you for reporting the issue and providing the details.
