### ISSUE TITLE
Shipping Settings: Consider removing slug from table and class create/edit modal

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#40892]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Consider removing the `slug` from the UI altogether - if its not included it gets auto-generated and isn't really relevant to any other UI (I think).

<img width="190" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/65a17f56-9a19-4357-a745-6c07154a61ba">

<img width="566" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/c6a34d6f-db26-4c85-959f-0e3c9c4f5ec3">

**Comment by laurajohnsonwoo** [comment]
I'm not sure if other extensions / developers use the slug, so we should keep it in the UI for the time being. I think the copy improvements will help make it less of a mystery for people who don't use the slug for anything.

**Comment by psealock** [comment]
Closing for now, we can reopen if there is desire to remove the slug.
