### ISSUE TITLE
Deployment of WooAI with woorelease

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#40894]
Currently, the Woo AI's plugin procedure is manual. We should switch it to an automated script and since we have [woorelease](https://github.com/woocommerce/woorelease), it would be nice to use it.

**Comment by joelclimbsthings** [comment]
I'm not sure the woorelease package listed will work given we're housed in the monorepo. [This P2](https://woomonorepo.wordpress.com/2023/10/23/rfc-production-repositories-for-releases-within-monorepo/) just popped up which is relevant to what we're needing.

**Comment by tommyshellberg** [comment]
I will take a look at this to confirm, but, I think we'd have to reference the Woo AI production(read-only) repository instead of the monorepo.

**Comment by joelclimbsthings** [comment]
Right, although the most effort in our current process is just syncing the files/etc to the production repo. Does using woorelease help us much, if it doesn't address that issue?

**Comment by tommyshellberg** [comment]
These are the tasks I've come up with after my initial research:

- [ ] Create a PR for the WooRelease tool to add something like a `--plugin` parameter which could accept a sub-project (plugin) within a repository. This would apply to the `release` command.
- [ ] Validate that the plugin exists within the /plugins/ folder of the repository.
- [ ] When generating a changelog through WooRelease, generate the changelog for the selected plugin.
- [ ] When bumping versions through WooRelease, only modify the files of the selected plugin.
- [ ] Figure out where we can store the plugin production repository URL (package.json, composer.json).
- [ ] Lookup the selected plugin production repository URL and generate the release using that repository.

**Comment by peterfabian** [comment]
Closing down as the Woo AI is being sunset.
