### ISSUE TITLE
Customize existing theme panel should include render of the site

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40902]
The panel should include a render of the site, not a pre-made image. It should be like the render on the transitional page.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/b067ca7b-427e-46a6-bf78-d0e003f78861)

**Comment by crunnells** [comment]
Looks like a job for mshots!

**Comment by adrianduffell** [comment]
@crunnells , unfortunately we can't use mshots because it is WPCOM based -- we're unable to make external server requests without first gaining user consent 😅 

Also I think it can only take screenshots of the public version of the site -- so for Woo X sites would capture a "coming soon" page until the site has been launched.

We can do a Gutenberg render of the homepage, hopefully. The transitional page has some prior art 🤞

**Comment by crunnells** [comment]
> unfortunately we can't use mshots because it is WPCOM based -- we're unable to make external server requests without first gaining user consent

What if they're on Woo Express? ;-)

> We can do a Gutenberg render of the homepage, hopefully. The transitional page has some prior art 🤞

Got it, I'll look for that.
