### ISSUE TITLE
Add loading state for product images

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40941]
There's no visual feedback when product images are being uploaded to the new product form. Let's fix that by adding a loading state for each uploaded image.

**Related to:** https://github.com/woocommerce/woocommerce/issues/38398

**Design**

<img width="710" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/7e30fa4a-c53e-489d-9ed2-eca6714efcc0">

**Acceptance criteria**

- [ ] We show a loading state for each uploaded image.
- [ ] The user can hover over an image and click X to cancel the upload. When the user hovers over the X icon, we show a tooltip that reads: `Cancel upload`.

**Comment by louwie17** [comment]
Note: this overlaps with https://github.com/woocommerce/woocommerce/issues/38398

**Comment by mdperez86** [comment]
This should be covered as part of https://github.com/woocommerce/woocommerce/issues/38398
