### ISSUE TITLE
Make "Select all" actually select all items

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40943]
Currently, the "Select all" button in the variations table in the new product form only selects items visible on the page. I understand why it's done that way, but the UX isn't great and may confuse merchants. We should look into changes on the backend that would let the button select all existing items across all table pages.

**Acceptance criteria**

- [ ] Clicking "Select all" in the variations table selects all existing items.

**Comment by louwie17** [comment]
@mdperez86 we can close this right, as you addressed this with some of your latest variation changes?
