### ISSUE TITLE
[Enhancement]: Product editor error handling

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#40958]
This is a follow-up for the [issue 40371](https://github.com/woocommerce/woocommerce/issues/40371).

When someone attempts to publish a product with variations without prices, we should take them to the Variations tab and scroll to the Variations table, so the notice is clearly visible.

- the snackbar mustn't dismiss automatically; the user should be able to click it to go to the Pricing tab. Only then the snackbar can disappear.
- If the user is already in the Pricing tab, we should show the error message directly below the reg. price field. There, the snackbar can disappear automatically after 1000ms.
- If there are more error messages, we'd stack them. Each should work as described above and link to respective tabs/sections.
- The snackbar should only appear in the variation details screen. The main product form may have its own share of errors that should be handled separately.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/46765
- [ ] https://github.com/woocommerce/woocommerce/issues/46768
```

**Comment by pmcpinto** [comment]
@octaedro this issue has a needs design label. What design input do you need? cc @j111q

**Comment by pmcpinto** [comment]
Also, do you plan to work on this during the current week or should we move it to the next cycle?

**Comment by octaedro** [comment]
Hi @pmcpinto,

> Also, do you plan to work on this during the current week or should we move it to the next cycle?

No, we won't tackle this issue during cycle 44 (this cycle). I just moved it to the next cycle.

**Comment by pmcpinto** [comment]
👍 thanks for the clarification.

**Comment by pmcpinto** [comment]
@octaedro this issue has a needs:design label. Do you need feedback from @j111q ?

**Comment by octaedro** [comment]
Hi @pmcpinto,

We are analyzing the way we're validating the form (p1712674345456069-slack-C01CMSA1VHS), and it will probably change. However some of the modifications described here will be good improvements for the current experience until we have the new validation.

I split the tasks I mentioned above and created a couple of issues to tackle them.

- https://github.com/woocommerce/woocommerce/issues/46765
- https://github.com/woocommerce/woocommerce/issues/46768

Since we know this will be different, I didn't create an issue for this point.

> The snackbar should only appear in the variation details screen. The main product form may have its own share of errors that should be handled separately.
