### ISSUE TITLE
Product Editor: Translations are not loaded for product editor UI elements

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#40968]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Snackbar on the Block Product editor is not being translated for non-English sites.

![image](https://github.com/woocommerce/woocommerce/assets/105309450/eabd64ed-d93b-4145-ba29-443a45ac0ca8)

### Expected behavior

The Snackbar on the Block Product editor should be translated for non-English sites.

### Actual behavior

The Snackbar on the Block Product editor should be translated for non-English sites.

### Steps to reproduce

1. Create a WC site e.g. use JN
2. Ensure Block Product Editor is enabled at `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`
3. Change site language to something non-English e.g. Espanol at Settings > General > Site Language and save changes:
4. image
6. Update translations at /wp-admin/update-core.php - In Spanish language, this will be clicking the Actualizar las traducciones button
8. Click Products > Add New or navigate to /wp-admin/admin.php?page=wc-admin&path=%2Fadd-product
9. Add product details and click Add button
10. See snackbar stating `Product added.` as in screenshot above
11. Update product and click update button (this is `Actualizar` in Spanish)
12. See snackbar stating `Product updated.` as in screenshot below
![image](https://github.com/woocommerce/woocommerce/assets/105309450/7c04cd16-30b7-4953-9fff-b5224033b269)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://colorful-lava.jurassic.ninja
Site address (URL): https://colorful-lava.jurassic.ninja
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 5.16MB
Tamaño de los datos de la base de datos: 3.46MB
Tamaño del índice de la base de datos: 1.70MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 2.38MB + Índice: 0.06MB + Motor InnoDB
wp_postmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_posts: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (5) ###

Companion Plugin: por Osk – 1.30
Jetpack: por Automattic – 12.7
WooCommerce Beta Tester: por WooCommerce – 2.2.4
WooCommerce: por Automattic – 8.2.1
WP Downgrade | Specific Core Version: por Reisetiger – 1.2.6

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: por Automattic - Anti-spam Team – 5.3
Hello Dolly: por Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #6 - /shop/
Carrito: #7 - /cart/
Finalizar compra: #8 - /checkout/
Mi cuenta: #9 - /my-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://es.wordpress.org
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2023-10-24 14:31:16 +00:00
Options: ✔
Notes: 69
Onboarding: -

### Action Scheduler ###

Completo: 6
Oldest: 2023-10-18 14:31:27 +0000
Newest: 2023-10-24 09:26:13 +0000

Pendiente: 1
Oldest: 2023-10-25 09:26:13 +0000
Newest: 2023-10-25 09:26:13 +0000

### Status report information ###

Generated at: 2023-10-24 09:28:10 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
As the screenshot shows, there are actually a number of labels that aren't being translated.

We should verify that our translation strings are being processed correctly.
