### ISSUE TITLE
[CYS] Design with AI - Modal

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#41019]
- Copy needs to be updated — Store Designer.
- Spacing between buttons is not correct — please double-check the design [here](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=3616-276551&mode=design).

![Image](https://user-images.githubusercontent.com/98944206/278072481-d2e00f8e-b926-4eaf-a144-f197bf557078.png)

**Comment by adrianduffell** [comment]
@chihsuan Just re-opening this. I think we need to have 20px padding on the Cancel button too.

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=7133%3A131237&mode=dev)

<img width="576" alt="Screen Shot 2023-10-31 at 11 49 13 am" src="https://github.com/woocommerce/woocommerce/assets/9312929/188c8fb8-5c56-459a-a3ce-0b98ab910184">
