### ISSUE TITLE
[CYS] Survey

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#41029]
Please add [this item](https://woofse.wordpress.com/2023/10/23/cys-mvp-woo-express-design-with-ai-survey/).

**Comment by chihsuan** [comment]
@verofasulo 👋 Do we need to have this ready for MVP or we can add it after the launch? 🙂

**Comment by verofasulo** [comment]
Hey @chihsuan 👋

We agreed with @adrianduffell to squeeze it in and have it ready for the MVP 😊

**Comment by adrianduffell** [comment]
@chihsuan I'll take care of this one as my HACK week project 😄
