### ISSUE TITLE
[CYS] Performance issues - Assembler

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#41021]
Loading in the frame shouldn't happen. 

![Image](https://user-images.githubusercontent.com/98944206/278064381-00a6a455-4706-4f12-87f4-1d0f6ab28873.png)

**Comment by chihsuan** [comment]
See https://github.com/woocommerce/woocommerce/pull/40936

**Comment by adrianduffell** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/40936
