### ISSUE TITLE
[GlobalStep] Unable to select the values from the dropdown menu on the "Products > Add New > Product Catalog" page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#41049]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unable to select the values from the dropdown menu on the "Products > Add New > Product Catalog" page.

### Expected behavior

The values should be selected after clicking from the dropdown menu on the "Products > Add New > Product Catalog" page.

### Actual behavior

Unable to select the values from the dropdown menu on the "Products > Add New > Product Catalog" page.

### Steps to reproduce

1. Create test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce  8.3.0.30 plugins.
4. Enable the new product editor under WooCommerce > settings > advanced > features.
5. Go to Products > Add new.
6. Go to the "Organization" Tab.
6. Click on the dropdown menu. 
7. Try clicking on the value of the dropdown menu.
8. Observe that, unable to select the values from the dropdown menu on the "Products > Add New > Product Catalog" page.

### Screencast:

https://github.com/woocommerce/woocommerce/assets/41110392/d05a6dbf-dd21-4bc4-a609-b4b41e3de804

### WordPress Environment

Environment:
Woocommerce Version: 8.3.0.30
WordPress version: 6.3.2
PHP version: 8.0.30

PC:
Windows 10
Chrome(Version 118.0.5993.89)
Firefox (Version 119.0)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
`
### WordPress Environment ###
WC Version: 8.3.0.30
REST API Version: ✔ 8.3.0.30
WC Blocks Version: ✔ 11.4.1
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0.30
WC Database Prefix: wp_
Total Database Size: 4646.54MB
Database Data Size: 2657.30MB
Database Index Size: 1989.24MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.34MB + Index: 0.47MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1604.97MB + Index: 1304.81MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1029.98MB + Index: 677.89MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.50MB + Index: 1.69MB + Engine InnoDB
wp_posts: Data: 2.31MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpml_mails: Data: 8.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 71
jetpack_migration: 2
jp_img_sitemap: 9
jp_pay_product: 2
jp_sitemap: 9
jp_sitemap_master: 9
mailpoet_page: 1
page: 21
post: 8
product: 44
product_variation: 7
revision: 135
shop_coupon: 31
shop_order: 196
shop_order_placehold: 5
wp_global_styles: 3
wp_navigation: 2
wp_template: 2
wp_template_part: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Query Monitor: by John Blackbourn – 3.14.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
AutomateWoo: by WooCommerce – 6.0.7
Crowdsignal Forms: by Automattic – 1.7.0
Facebook for WooCommerce: by Facebook – 3.1.2
WordPress.com Editing Toolkit: by Automattic – 4.1679
Google Listings and Ads: by WooCommerce – 2.5.10
Gutenberg: by Gutenberg Team – 16.9.0
Jetpack: by Automattic – 12.8-a.1
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.4
Pinterest for WooCommerce: by WooCommerce – 1.3.12
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.11

TikTok: by TikTok – 1.2.1
Woo AI: by WooCommerce – 0.5.0
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.5
WooCommerce Beta Tester: by WooCommerce – 2.2.4
WooCommerce Brands: by WooCommerce – 1.6.61
WooCommerce Gift Cards: by WooCommerce – 1.16.6
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.8
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 6.6.2
WooCommerce Product Add-ons: by WooCommerce – 6.5.0
WooCommerce Product Bundles: by WooCommerce – 6.22.4
WooCommerce Product Recommendations: by WooCommerce – 3.0.3
WooCommerce Shipping & Tax: by WooCommerce – 2.3.7
WooCommerce Shipment Tracking: by WooCommerce – 2.4.1
WooCommerce: by Automattic – 8.3.0.30
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (12) ###

Avalara AvaTax: by Avalara – 2.6.1
Classic Editor: by WordPress Contributors – 1.6.3
MailPoet: by MailPoet – 4.34.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.7
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.4
WooCommerce EU VAT Number: by WooCommerce – 2.8.8
WooCommerce FedEx Shipping: by WooCommerce – 3.8.5
WooCommerce Royal Mail: by WooCommerce – 3.0.1
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.5
WP Crontrol: by John Blackbourn & crontributors – 1.16.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #45 - /shop/
Cart: #46 - /cart/
Checkout: #47 - /checkout/
My account: #48 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.2.2
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### WooPayments ###

Version: 6.6.2
Connected to WPCOM: Yes
WPCOM Blog ID: 220476338
Account ID: acct_1NiurqC6NFOedpRk
Payment Gateway: Enabled
Test Mode: Enabled
UPE: Enabled (deferred_intent_upe_without_fallback)
UPE Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Back In Stock ###

Database Version: 1.6.5
Loopback Test: ✔

### Gift Cards ###

Database Version: 1.16.6
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.22.4
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
navigation
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2023-10-27 07:02:47 +01:00
Options: ✔
Notes: 88
Onboarding: skipped

### Action Scheduler ###

Canceled: 6
Oldest: 2023-09-27 09:36:07 +0100
Newest: 2023-10-26 12:56:13 +0100

Complete: 4,857,602
Oldest: 2023-08-17 08:42:57 +0100
Newest: 2023-10-26 16:16:22 +0100

Failed: 1,374
Oldest: 2023-06-28 21:10:01 +0100
Newest: 2023-10-26 14:58:51 +0100

Pending: 17
Oldest: 2023-10-26 16:17:00 +0100
Newest: 2023-10-27 10:36:19 +0100

### Product Recommendations ###

Database Version: 3.0.3
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: No cache detected

### Status report information ###

Generated at: 2023-10-26 16:16:41 +01:00
`
</details>

**Comment by AnnaMag** [comment]
verified on WooExpress sites

**Comment by PanosSynetos** [comment]
Seems to be related to Gutenberg. Once I deactivate Gutenberg 16.9.0 , the issue is resolved
