### ISSUE TITLE
Shipping Options stay hidden when selecting "only show once address entered"

### ISSUE THREAD

**Issue by FireRedDev** [woothemes/woocommerce#41074]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With Shipping Target set to "billing address as default" and "only show shipping cost once address was entered" selected/ticked, the shipping cost doesnt ever show up and i get forwarded to paypal with the wrong (lower) total.

### Expected behavior

The shipping cost shows up after i entered my billing address 

### Actual behavior

The shipping cost never shows up and i can click on e.g. Pay with Paypal and get forwarded to Paypal(it doesnt even show up when selecting different ship address and entering that)

### Steps to reproduce

Choose the mentioned settings. I only have one shipping zone with a fixed tarif that is 0 and something else for 1 shipping class.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wear-together.at
Site address (URL): https://wear-together.at
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.2.3 - Es ist eine neuere Version von WordPress verfügbar (6.3.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/3.0.2
PHP Version: 7.4.33
PHP Post Max Size: 10 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.15-MariaDB-1:10.6.15+maria~ubu2204
Max Upload Size: 6 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 563.61MB
Datenbank-Datengröße: 350.45MB
Datenbank-Indexgröße: 213.16MB
wp_woocommerce_sessions: Daten: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 50.59MB + Index: 27.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 24.11MB + Index: 16.14MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 11.03MB + Index: 9.06MB + Engine InnoDB
wp_asre_sales_report: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Daten: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Daten: 1.52MB + Index: 1.80MB + Engine InnoDB
wp_automatewoo_customer_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Daten: 1.52MB + Index: 1.23MB + Engine InnoDB
wp_automatewoo_guest_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Daten: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_automatewoo_log_meta: Daten: 0.28MB + Index: 0.30MB + Engine InnoDB
wp_automatewoo_queue: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 7.52MB + Index: 9.09MB + Engine InnoDB
wp_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Daten: 0.06MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Daten: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_fc_campaigns: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_campaign_emails: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_fc_campaign_url_metrics: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fc_companies: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fc_contact_relations: Daten: 0.38MB + Index: 0.36MB + Engine InnoDB
wp_fc_contact_relation_items: Daten: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_fc_funnels: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_funnel_metrics: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fc_funnel_sequences: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_fc_funnel_subscribers: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_fc_lists: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_meta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_sequence_tracker: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_fc_subscribers: Daten: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_fc_subscriber_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_notes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_subscriber_pivot: Daten: 0.44MB + Index: 0.50MB + Engine InnoDB
wp_fc_tags: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_url_stores: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ff_scheduled_actions: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_draft_submissions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Daten: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Daten: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_order_items: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Daten: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_subscriptions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_transactions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fsmpt_email_logs: Daten: 15.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_activities: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fs_attachments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_conversations: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_fs_data_metrix: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_mail_boxes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_meta: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_fs_persons: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_products: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_saved_replies: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_taggables: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_tag_pivot: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_tickets: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_fs_workflows: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_workflow_actions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_consent: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_userlogs: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_jet_post_types: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 12.06MB + Index: 1.19MB + Engine InnoDB
wp_podsrel: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Daten: 89.47MB + Index: 57.11MB + Engine InnoDB
wp_posts: Daten: 11.47MB + Index: 4.91MB + Engine InnoDB
wp_snippets: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_visit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor_relationships: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_documentmeta: Daten: 24.56MB + Index: 22.06MB + Engine InnoDB
wp_storeabill_documents: Daten: 2.52MB + Index: 1.09MB + Engine InnoDB
wp_storeabill_document_itemmeta: Daten: 43.58MB + Index: 30.11MB + Engine InnoDB
wp_storeabill_document_items: Daten: 4.52MB + Index: 4.53MB + Engine InnoDB
wp_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_notices: Daten: 3.52MB + Index: 0.47MB + Engine InnoDB
wp_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.27MB + Index: 0.19MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_credit_note_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.45MB + Index: 0.38MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 2.52MB + Index: 2.58MB + Engine InnoDB
wp_wc_order_stats: Daten: 1.52MB + Index: 0.92MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 1.52MB + Index: 1.42MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.25MB + Index: 0.44MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 10.52MB + Index: 6.02MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 2.52MB + Index: 0.75MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 7.52MB + Index: 4.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 2.52MB + Index: 2.70MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_payments: Daten: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_options: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

_pods_field: 13
_pods_group: 2
_pods_pod: 2
attachment: 3877
aw_workflow: 3
br_sale_report: 3
cool_timeline: 1
custom_css: 1
document_template: 5
elementor_library: 552
jet-engine: 1
modula-gallery: 1
nav_menu_item: 78
oceanwp_library: 1
organisation: 2
page: 45
post: 2
product: 408
product_variation: 1468
revision: 400
schule: 94
shop_coupon: 260
shop_order: 12675
shop_order_refund: 285
wp_global_styles: 1
wpforms: 1
wppb-roles-editor: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

The SEO Framework: von The-SEO-Framework-Team – 4.2.8
AutomateWoo: von WooCommerce – 6.0.5
Autoptimize: von Frank Goossens (futtta) – 3.1.8.1
Borlabs Font Blocker: von Borlabs GmbH – 1.0.5
Code Snippets: von Code Snippets Pro – 3.5.0
DynamicConditions: von RTO GmbH – 1.6.2
DynamicTags: von RTO GmbH – 1.2.2
Ele Custom Skin: von Dudaster.com – 3.1.7
Elementor Pro: von Elementor.com – 3.16.2
Elementor: von Elementor.com – 3.16.4
FluentCRM - Marketing-Automatisierung für WordPress: von WP Email Newsletter Team - FluentCRM – 2.8.31
FluentSMTP: von FluentSMTP & WPManageNinja Team – 2.2.6
Fluent Support Pro: von WPManageNinja LLC – 1.7.3
Fluent Support: von WPManageNinja LLC – 1.7.3
FluentCRM Pro: von FluentCRM – 2.8.30
Fluent Forms: von Contact Form - WPManageNinja LLC – 5.0.12
Fluent Forms Pro Add-On-Paket: von Fluent Forms – 5.0.10
Fluent Forms PDF Generator: von WPManageNinja LLC – 1.1.7
The GDPR Framework: von Data443 – 2.0.4
Make Connector: von Celonis s.r.o. – 1.5.8
Modula: von WPChill – 2.7.7
Ocean Custom Sidebar: von OceanWP – 1.1.2
Ocean Extra: von OceanWP – 2.2.0
Ocean Product Sharing: von OceanWP – 2.0.7
Ocean Social Sharing: von OceanWP – 2.0.5
Ocean Stick Anything: von OceanWP – 2.0.7
One Stop Shop für WooCommerce: von vendidero – 1.4.0
DSGVO Pixelmate: von Christian Wedel – 4.3.4
Pods - Custom Content Types and Fields: von Pods Framework Team – 3.0.4
Product Input Fields for WooCommerce: von Tyche Softwares – 1.6.0
Profile Builder: von Cozmoslabs – 3.9.9
reSmush.it Image Optimizer: von reSmush.it – 0.4.13
WooCommerce - Show only lowest prices in variable products: von Fernando Tellado – 1.0.4
Converter for Media: von matt plugins – 5.11.0
Sales Report Email for WooCommerce: von zorem – 2.8
Advanced Order Export For WooCommerce: von AlgolPlus – 3.4.2
WooCommerce Checkout Manager: von QuadLayers – 7.2.7
WooCommerce Stripe-Gateway: von WooCommerce – 7.6.1
Germanized für WooCommerce Pro: von vendidero – 3.7.4
Germanized für WooCommerce: von vendidero – 3.13.5
WooCommerce Google Analytics Integration: von WooCommerce – 1.8.7
WooCommerce PayPal Payments: von WooCommerce – 2.3.1
WooCommerce: von Automattic – 7.9.0 (Update auf Version 8.2.1 ist verfügbar)
Super Page Cache for Cloudflare: von Optimole – 4.7.4
WP Rollback: von GiveWP.com – 1.7.3

### Inactive Plugins (3) ###

Plugin Compatibility Checker: von Dinesh Pilani – 2.5.7
Slim Maintenance Mode: von Johannes Ries – 1.4.3
vendidero Helper: von vendidero – 2.2.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #7 - /shop/
Warenkorb: #8 - /cart/
Kasse: #9 - /checkout/
Mein Konto: #10 - /my-account/
Allgemeine Geschäftsbedingungen: #743 - /agb/

### Theme ###

Name: OceanWP
Version: 3.5.0
Author URL: https://oceanwp.org/about-oceanwp/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/product-image.php
oceanwp/woocommerce/single-product/title.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-28 13:24:55 +00:00
Options: ✔
Notes: 195
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 42.592
Oldest: 2023-09-26 16:46:12 +0000
Newest: 2023-10-27 16:28:47 +0000

Fehlgeschlagen: 312
Oldest: 2023-04-03 22:04:37 +0000
Newest: 2023-04-23 15:31:48 +0000

Ausstehend: 17
Oldest: 2023-10-27 16:30:47 +0000
Newest: 2023-10-29 10:53:40 +0000

### Status report information ###

Generated at: 2023-10-27 16:29:15 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by vbelolapotkov** [comment]
That seems to be shipping related. @woocommerce/escargot could you please take a look?

**Comment by kloon** [comment]
Hey @vbelolapotkov I ran some tests using WooCommerce 8.2.2 and I was not able to recreate this as an issue with the shipping settings.

![0QR5eD.png](https://github.com/woocommerce/woocommerce/assets/271630/299e4736-ce70-4b8b-963b-bb4e4fd4df76)

Screencast https://d.pr/i/xmBulH

**Comment by FireRedDev** [comment]
Hey @kloon, i did not have the calculator active, so this option would be disabled. Only hide shipping costs would be ticked.

**Comment by kloon** [comment]
Hey @FireRedDev, I retested this with the option disabled now and still not able to replicate.

![](https://d.pr/i/AeX4Vd+)

Screen Recording: https://d.pr/i/NTMNfJ

The only suggestion I have is that if you have a staging site, try it on there and one by one disable all plugins to see if there's interference, testing after disabling each one. Leave Paypal for last, and if still getting this behaviour try disabling Paypal and see if this give the rates. If this is the case the issue lies with the Paypal extension.
