### ISSUE TITLE
[Enhancement]: check if $data['billing_email'] is set in create_order function

### ISSUE THREAD

**Issue by zigasancin** [woothemes/woocommerce#41097]
### Describe the solution you'd like

This is a very tiny enhancement proposal. We're not using the WooCommerce billing checkout fields, so the `billing_email` array key isn't present when we reach [this line](https://github.com/woocommerce/woocommerce/blob/6ecf096d1c654e917c7052543b0811acebadc4bc/plugins/woocommerce/includes/class-wc-checkout.php#L424) of the `create_order` function in the `WC_Checkout` class and that creates a lot of php warnings in the logs. It would be awesome if we could wrap that line with an `isset` check.

**Comment by rrennick** [comment]
> This is a very tiny enhancement proposal.

@zigasancin Thanks for creating the issue. In future if you are reporting PHP warnings in your error logs, use the bug template.

**Comment by opr** [comment]
Hey @zigasancin ,

Thank you for taking the time to share this idea. We appreciate your help. While this would be helpful, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility?rgh-link-date=2023-08-04T11%3A35%3A35Z). We'll revisit the list of suggestions like this one once our priorities are updated. In the meantime, we'll review this behavior in the blocks experience.

In the meantime, if you feel strongly about this we welcome you to open a PR with the changes you'd like to see.

Thanks again for taking the time to suggest this.

**Comment by zigasancin** [comment]
> > This is a very tiny enhancement proposal.
> 
> @zigasancin Thanks for creating the issue. In future if you are reporting PHP warnings in your error logs, use the bug template.

@rrennick Oh, sorry, it was very difficult to decide whether this is a bug or an enhancement, because a default instance of WooCommerce with Storefront doesn't trigger the php warning (you'd need to create a custom & old non-blocks checkout experience to trigger the php warning).

**Comment by zigasancin** [comment]
> Hey @zigasancin ,
> 
> Thank you for taking the time to share this idea. We appreciate your help. While this would be helpful, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility?rgh-link-date=2023-08-04T11%3A35%3A35Z). We'll revisit the list of suggestions like this one once our priorities are updated. In the meantime, we'll review this behavior in the blocks experience.
> 
> In the meantime, if you feel strongly about this we welcome you to open a PR with the changes you'd like to see.
> 
> Thanks again for taking the time to suggest this.

@opr Thanks for your thorough comment. We're fully aware of the cart & checkout blocks feature (we tested it late last year and it was great!), but we couldn't switch just yet because we're waiting on further improvements to one of the official payment gateway plugins. I've already opened a PR, but I totally understand the priorities, etc.

**Comment by rrennick** [comment]
> you'd need to create a custom & old non-blocks checkout experience to trigger the php warning

@zigasancin For non-blocks issues you can specify switching to the Twenty Twenty theme in your steps to reproduce.
