### ISSUE TITLE
Incorrect "Drag to resize" styling when spotlight tour is present

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#41116]
* Color should be white text on black
* Text is not centered

## Actual

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/1d8ddf86-1e7f-477e-87a2-de288d072523)

## Expected

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/1c9d8aa1-2d39-4541-a310-4f6debfbcd8f)

**Comment by chihsuan** [comment]
> Color should be white text on black

Hey @adrianduffell I think color should be theme color. 🙂 

Mrk6SERPZ4KrFHSjM0a8TK-fi-2786%3A280142

**Comment by adrianduffell** [comment]
Hey @chihsuan , thanks for double-checking ✨ 

You're right -- the black version is originally a bug, but @verofasulo saw it recently and now prefers it. Sorry, I should have mentioned it in the issue. We should make all instances black now. 

@verofasulo could you please update the Figma too? 🙏

**Comment by verofasulo** [comment]
> the black version is originally a bug, but @verofasulo saw it recently and now prefers it. 

@adrianduffell just to clarify: it's not a bug — it's the default Gutenberg label, and we decided to go with it 😊

> could you please update the Figma too? 

Yep!
