### ISSUE TITLE
Package release workflow is not working

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#41129]
The [Package Release workflow](https://github.com/woocommerce/woocommerce/actions/workflows/package-release.yml) is not working - I believe this is to do with `npm` requiring 2fa. See thread: p1697554592761099-slack-C03CPM3UXDJ

Logging the issue here as it doesn't look like it has been saved as an issue yet.

**Comment by psealock** [comment]
The error message indicates an unclean working tree. I'm wondering if a pnpm lock file change has been created as a result of the Setup WooCommerce Monorepo step.

```
ERR_PNPM_GIT_UNCLEAN  Unclean working tree. Commit or stash changes first.
```

**Comment by psealock** [comment]
See https://github.com/woocommerce/woocommerce/pull/41416
