### ISSUE TITLE
New Product Editor: product description disappears if the first block is not a text paragraph

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#41176]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the product description, if the first block is a Group block or a column block, whatever content has been added to the product description, will be lost.

### Expected behavior

The product description should be savable regardless of its content 

### Actual behavior

The product description disappears when the first block is not a paragraph.

### Steps to reproduce

Go to WooCommece > product
add a new product.
in the product editor, open the deacription field
add a paragraph and save. You will see a oreview. 
Reopen the description field and now set as a first block a column block
Then save the changes.
The product description will be gone.

### WordPress Environment

WP6.4
Woo nightly 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
I can reproduce this.

One scenario is if columns are the only blocks in the description.

If you then add a paragraph after the columns, things seems okay.

There may be other scenarios/blocks that cause this. There is definitely something up with how the description is getting set.

**Comment by mattsherman** [comment]
Closing this in favor of #39404, which actually describes the same bug, though slightly differently.

@tomxygen Thanks for reporting this! I'm going to work with the team to get this addressed.

**Comment by mattsherman** [comment]
Duplicate of #39404

**Comment by ResponsiveFlow** [comment]
hey @mattsherman, I see that this PR is a duplicate of #39404 which has been closed because fixed with PR #42019
Unfortunately tho, this issue is still present as of today.
