### ISSUE TITLE
Wrong quotes

### ISSUE THREAD

**Issue by mrleemon** [woothemes/woocommerce#41179]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following strings are using the wrong quotes in `target` attribute:

https://github.com/woocommerce/woocommerce/blob/9572bf2a120ce4ae0cb22f78fc90ecfeb0f2777e/plugins/woocommerce/includes/admin/settings/class-wc-settings-advanced.php#L398

https://github.com/woocommerce/woocommerce/blob/9572bf2a120ce4ae0cb22f78fc90ecfeb0f2777e/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L169

https://github.com/woocommerce/woocommerce/blob/9572bf2a120ce4ae0cb22f78fc90ecfeb0f2777e/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L150

### Expected behavior

It should be `target="_blank"` instead of `target=”_blank”`

### Actual behavior

Right now it's `target=”_blank”`

### Steps to reproduce

Check the source code in those files

### WordPress Environment

WordPress 6.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
cc @Konamiman

**Comment by Konamiman** [comment]
Thanks for the ping, https://github.com/woocommerce/woocommerce/pull/41320 fixes this.
