### ISSUE TITLE
[HPOS] Reconcile sync problems

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#41172]
When data synchronization is enabled, we essentially have two versions of the same order (one in the authoritative store, one in the back-up store). It's possible for these to fall out of sync. For example:

- An extension may add, modify or delete meta data from one store and not the other, via a direct query, and it may not change the value of the `updated` field.
- Or, an individual update, insert or delete query used during the HPOS sync process may fail for some unexpected reason (assume transactions disabled).

In these cases, the anomaly can be detected by running `wp wc cot verify_cot_data`, which may yield results like these:

```
Order Data Verification  100% [======================================] 0:03 / 0:03
Verification completed.
Error: 8000 orders were verified in 2 seconds. 1 error found: {
    "12345": [
        {
            "order_id": 12345,
            "meta_key": "is_vat_exempt",
            "orig_meta_values": [
                "no"
            ],
            "new_meta_values": [
                "yes"
            ]
        }
    ]
}. Please review the error above.
```

In the above example, only one order is impacted—but, in reality, it is possible that many orders will be impacted. Things we may wish to consider:

- Providing a tool that will help merchants to reconcile the differences.
- Making any tooling we create (plus the verification tool—see also https://github.com/woocommerce/woocommerce/issues/40702 and https://github.com/woocommerce/woocommerce/issues/39696) available in the UI. 

A possible alternative, though it seems a little less palatable, would be for merchants/developers to reconcile through manual db intervention.

**Comment by jorgeatorres** [comment]
Closing in favor of enhancing docs on how to use the CLI tools available for this: https://github.com/woocommerce/woocommerce/issues/41910, https://github.com/woocommerce/woocommerce/issues/41909. Happy to re-assess if necessary.
