### ISSUE TITLE
Deprecated Message in PHP 8.2

### ISSUE THREAD

**Issue by BackuPs** [woothemes/woocommerce#41184]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I get this message the moment i install php 8.2

Deprecated: Automatic conversion of false to array is deprecated in /var/docs/server.tst/public/wp-content/plugins/woocommerce/src/Admin/DataSourcePoller.php on line 138

### Expected behavior

check for array should be added.

### Actual behavior

dont know  i am no programmer

### Steps to reproduce

Just install woocommerce and php 8.2

### WordPress Environment

Status report irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mikkamp** [comment]
This error is coming from the following code: https://github.com/woocommerce/woocommerce/blob/8.2.3/plugins/woocommerce/src/Admin/DataSourcePoller.php#L136-L138
Where `get_transient` could return the value `false` (the null coalescing operator only turns it into an array if a null is returned).

This issue got resolved in WooCommerce 8.8 PR #45547 

In that PR the code was changed to actually check if the returned value is an array, see the code here: https://github.com/woocommerce/woocommerce/pull/45547/files#diff-bad8bffd72b825a2a6fae278ab9399e504efd4c444c4204ea9f572d01a6c4026R113-R114

So closing this issue as completed.

**Comment by BackuPs** [comment]
I am using woocommerce 9.3.2  so it is not at all resolved in 8.8

**Comment by mikkamp** [comment]
Thanks for the additional report @BackuPs 

The original issue mentions a line that is only available in 8.2.3 (which would have roughly been the latest version at the time this issue was created). 

> Deprecated: Automatic conversion of false to array is deprecated in /var/docs/server.tst/public/wp-content/plugins/woocommerce/src/Admin/DataSourcePoller.php on line 138

If you are still experiencing the deprecated warning with the latest version of WooCommerce, could you provide the exact deprecation message you are getting so we can confirm where it is coming from?

**Comment by BackuPs** [comment]
I am sorry for the mixup. I submitted this yesterday and thought your answer was about that deprecation message.  

https://github.com/woocommerce/woocommerce/issues/51542

So i replied with that in my mind.  The one you are replying to is from 2023. LOL.  that is a good mixup. I am not thinking clear. Got hit by c-19 this week.  So forgive me.

This one is closed.

**Comment by mikkamp** [comment]
Thanks for the clarification, that makes sense.
