### ISSUE TITLE
date_updated_gmt gets updated even though no update

### ISSUE THREAD

**Issue by Mingendahl** [woothemes/woocommerce#41226]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

See also here: https://wordpress.org/support/topic/bug-with-order-date_updated_gmt/

The timestamp date_updated_gmt in table wc_orders get's updated to 'now' not only when you modify an order, but also when you just open it for viewing.

This renders every logic regarding the modification date useless, as soon as HPOS is enabled.
E.g. when using the REST services, /wp-json/wc/v3/orders?per_page=20&page=1&orderby=modified&order=desc will (semantically) return a nonsensical order depending on which order has been last opened for viewing, without any modification.

When disabling HPOS, the modification order works as expected.

### Expected behavior

date_updated_gmt in table wc_orders must not be updated upon viewing an order, just on updates / real modifications.

### Actual behavior

date_updated_gmt in table wc_orders gets updated also when just viewing an order if HPOS is enabled

### Steps to reproduce

1. check the data in wc_order for an arbitrary existing order and note the date_updated_gmt timestamp
2. open that order in WP-Admin
3. check the date_updated_gmt timestamp for that order

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.oursecreturl.de
Site address (URL): https://www.oursecreturl.de
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.1.21
PHP Post Max Size: 2 GB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.11.4-MariaDB-1:10.11.4+maria~ubu2204
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: co1uw_
Datenbank-Gesamtgröße: 706.10MB
Datenbank-Datengröße: 371.17MB
Datenbank-Indexgröße: 334.93MB
co1uw_woocommerce_sessions: Daten: 2.02MB + Index: 0.02MB + Engine InnoDB
co1uw_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
co1uw_woocommerce_order_items: Daten: 2.52MB + Index: 1.52MB + Engine InnoDB
co1uw_woocommerce_order_itemmeta: Daten: 31.56MB + Index: 29.09MB + Engine InnoDB
co1uw_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
co1uw_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_actionscheduler_actions: Daten: 13.02MB + Index: 15.05MB + Engine InnoDB
co1uw_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_actionscheduler_logs: Daten: 26.38MB + Index: 17.16MB + Engine InnoDB
co1uw_atum_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_atum_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_atum_product_data: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_automatewoo_abandoned_carts: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
co1uw_automatewoo_customers: Daten: 0.38MB + Index: 0.88MB + Engine InnoDB
co1uw_automatewoo_customer_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_automatewoo_guests: Daten: 0.31MB + Index: 0.56MB + Engine InnoDB
co1uw_automatewoo_guest_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_automatewoo_logs: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
co1uw_automatewoo_log_meta: Daten: 0.25MB + Index: 0.25MB + Engine InnoDB
co1uw_automatewoo_queue: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_automatewoo_queue_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_berocket_termmeta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_cartflows_ca_cart_abandonment: Daten: 3.52MB + Index: 0.06MB + Engine InnoDB
co1uw_cartflows_ca_email_history: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_cartflows_ca_email_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_cartflows_ca_email_templates_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_cli_cookie_scan: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_cli_cookie_scan_categories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_cli_cookie_scan_cookies: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_cli_cookie_scan_url: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_cli_scripts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_commentmeta: Daten: 0.11MB + Index: 0.33MB + Engine InnoDB
co1uw_comments: Daten: 10.52MB + Index: 14.13MB + Engine InnoDB
co1uw_content_tabs_ultimate_list: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_content_tabs_ultimate_style: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_csp3_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_css_js_manager: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_ewwwio_images: Daten: 1.52MB + Index: 1.78MB + Engine InnoDB
co1uw_ewwwio_queue: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_e_notes: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
co1uw_e_notes_users_relations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_e_submissions: Daten: 0.02MB + Index: 0.27MB + Engine InnoDB
co1uw_e_submissions_actions_log: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
co1uw_e_submissions_values: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_feedmanager_channel: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_feedmanager_country: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_feedmanager_feed_status: Daten: 0.02MB + Index: 0.16MB + Engine InnoDB
co1uw_feedmanager_field_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_feedmanager_product_feed: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_feedmanager_product_feedmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
co1uw_feedmanager_source: Daten: 0.02MB + Index: 0.16MB + Engine InnoDB
co1uw_followup_coupons: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_followup_coupon_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_followup_customers: Daten: 0.31MB + Index: 0.48MB + Engine InnoDB
co1uw_followup_customer_carts: Daten: 5.52MB + Index: 0.38MB + Engine InnoDB
co1uw_followup_customer_notes: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_followup_customer_orders: Daten: 0.27MB + Index: 0.11MB + Engine InnoDB
co1uw_followup_email_excludes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_followup_email_logs: Daten: 1.52MB + Index: 0.44MB + Engine InnoDB
co1uw_followup_email_orders: Daten: 3.52MB + Index: 1.00MB + Engine InnoDB
co1uw_followup_email_tracking: Daten: 1.52MB + Index: 0.61MB + Engine InnoDB
co1uw_followup_followup_history: Daten: 2.52MB + Index: 0.38MB + Engine InnoDB
co1uw_followup_order_categories: Daten: 0.30MB + Index: 0.31MB + Engine InnoDB
co1uw_followup_order_items: Daten: 1.52MB + Index: 0.75MB + Engine InnoDB
co1uw_followup_subscribers: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_followup_subscribers_to_lists: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_followup_subscriber_lists: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_kbp_countdown_entry: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_kbp_form_entry: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_kbp_form_entrymeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_newsletter_templates: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
co1uw_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_segments: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
co1uw_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
co1uw_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_subscribers: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
co1uw_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_newsletter: Daten: 0.16MB + Index: 0.08MB + Engine InnoDB
co1uw_newsletter_emails: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB
co1uw_newsletter_sent: Daten: 0.23MB + Index: 0.19MB + Engine InnoDB
co1uw_newsletter_stats: Daten: 0.31MB + Index: 0.20MB + Engine InnoDB
co1uw_newsletter_user_logs: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
co1uw_newsletter_user_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_options: Daten: 17.06MB + Index: 0.97MB + Engine InnoDB
co1uw_oxi_div_import: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_postmeta: Daten: 74.67MB + Index: 120.30MB + Engine InnoDB
co1uw_posts: Daten: 31.39MB + Index: 6.00MB + Engine InnoDB
co1uw_rank_math_404_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_rank_math_analytics_adsense: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_rank_math_analytics_ga: Daten: 0.28MB + Index: 0.17MB + Engine InnoDB
co1uw_rank_math_analytics_gsc: Daten: 3.34MB + Index: 4.44MB + Engine InnoDB
co1uw_rank_math_analytics_inspections: Daten: 0.09MB + Index: 0.11MB + Engine InnoDB
co1uw_rank_math_analytics_keyword_manager: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
co1uw_rank_math_analytics_objects: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_rank_math_internal_links: Daten: 0.17MB + Index: 0.06MB + Engine InnoDB
co1uw_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_rank_math_redirections: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
co1uw_rank_math_redirections_cache: Daten: 1.52MB + Index: 0.17MB + Engine InnoDB
co1uw_shortpixel_folders: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_shortpixel_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_shortpixel_postmeta: Daten: 4.52MB + Index: 3.98MB + Engine InnoDB
co1uw_shortpixel_queue: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
co1uw_storeabill_documentmeta: Daten: 22.56MB + Index: 18.06MB + Engine InnoDB
co1uw_storeabill_documents: Daten: 2.52MB + Index: 1.27MB + Engine InnoDB
co1uw_storeabill_document_itemmeta: Daten: 40.58MB + Index: 32.11MB + Engine InnoDB
co1uw_storeabill_document_items: Daten: 5.52MB + Index: 5.55MB + Engine InnoDB
co1uw_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_storeabill_document_notices: Daten: 1.52MB + Index: 0.34MB + Engine InnoDB
co1uw_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_termmeta: Daten: 0.16MB + Index: 0.41MB + Engine InnoDB
co1uw_terms: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
co1uw_term_relationships: Daten: 0.13MB + Index: 0.11MB + Engine InnoDB
co1uw_term_taxonomy: Daten: 0.06MB + Index: 0.08MB + Engine InnoDB
co1uw_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_usermeta: Daten: 2.50MB + Index: 8.03MB + Engine InnoDB
co1uw_users: Daten: 0.14MB + Index: 0.20MB + Engine InnoDB
co1uw_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wc_customer_lookup: Daten: 0.45MB + Index: 0.41MB + Engine InnoDB
co1uw_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_wc_orders: Daten: 2.52MB + Index: 1.92MB + Engine InnoDB
co1uw_wc_orders_meta: Daten: 7.52MB + Index: 15.11MB + Engine InnoDB
co1uw_wc_order_addresses: Daten: 1.52MB + Index: 1.39MB + Engine InnoDB
co1uw_wc_order_coupon_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
co1uw_wc_order_operational_data: Daten: 1.52MB + Index: 0.56MB + Engine InnoDB
co1uw_wc_order_product_lookup: Daten: 2.52MB + Index: 3.61MB + Engine InnoDB
co1uw_wc_order_stats: Daten: 1.52MB + Index: 0.61MB + Engine InnoDB
co1uw_wc_order_tax_lookup: Daten: 0.42MB + Index: 0.34MB + Engine InnoDB
co1uw_wc_product_attributes_lookup: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
co1uw_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wc_product_meta_lookup: Daten: 0.14MB + Index: 0.22MB + Engine InnoDB
co1uw_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wfblockediplog: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wfblocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_wfconfig: Daten: 0.47MB + Index: 0.00MB + Engine InnoDB
co1uw_wfcrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wffilechanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wffilemods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wfhits: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_wfhoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wfissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
co1uw_wfknownfilelist: Daten: 3.52MB + Index: 0.00MB + Engine InnoDB
co1uw_wflivetraffichuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wflocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wflogins: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wfnotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wfpendingissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
co1uw_wfreversecache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wfsnipcache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
co1uw_wfstatus: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_wftrafficrates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_woocommerce_bis_activity: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
co1uw_woocommerce_bis_notifications: Daten: 0.05MB + Index: 0.09MB + Engine InnoDB
co1uw_woocommerce_bis_notificationsmeta: Daten: 0.11MB + Index: 0.11MB + Engine InnoDB
co1uw_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_gzd_dhl_labelmeta: Daten: 0.33MB + Index: 0.33MB + Engine InnoDB
co1uw_woocommerce_gzd_dhl_labels: Daten: 0.13MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_woocommerce_gzd_shipmentmeta: Daten: 6.52MB + Index: 5.03MB + Engine InnoDB
co1uw_woocommerce_gzd_shipments: Daten: 1.52MB + Index: 0.45MB + Engine InnoDB
co1uw_woocommerce_gzd_shipment_itemmeta: Daten: 5.52MB + Index: 6.03MB + Engine InnoDB
co1uw_woocommerce_gzd_shipment_items: Daten: 1.52MB + Index: 1.13MB + Engine InnoDB
co1uw_woocommerce_gzd_shipment_labelmeta: Daten: 3.52MB + Index: 4.03MB + Engine InnoDB
co1uw_woocommerce_gzd_shipment_labels: Daten: 1.52MB + Index: 0.22MB + Engine InnoDB
co1uw_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wpmailsmtp_debug_events: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
co1uw_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_wpr_rocket_cache: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
co1uw_wpr_rucss_used_css: Daten: 0.08MB + Index: 0.13MB + Engine InnoDB
co1uw_wsal_metadata: Daten: 0.17MB + Index: 0.19MB + Engine InnoDB
co1uw_wsal_occurrences: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
co1uw_xyz_ics_countries: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_yoast_indexable: Daten: 1.52MB + Index: 0.28MB + Engine InnoDB
co1uw_yoast_indexable_hierarchy: Daten: 0.06MB + Index: 0.08MB + Engine InnoDB
co1uw_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_yoast_seo_links: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
co1uw_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_ywrr_email_blocklist: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_ywrr_email_schedule: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
co1uw_zettle_queue: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
co1uw_zettle_woocommerce_id_map: Daten: 0.16MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
attachment: 1402
aw_workflow: 1
br_labels: 5
custom_css: 6
customize_changeset: 24
cwginstocknotifier: 74
document_template: 6
elementor_library: 30
elementor-hf: 1
follow_up_email: 1
invoice: 12
kadence_element: 15
mailpoet_page: 1
nav_menu_item: 22
oembed_cache: 15
page: 28
post: 3
product: 209
product_variation: 632
revision: 2016
saswp: 2
seedprod: 4
shop_coupon: 4
shop_order: 5852
shop_order_refund: 417
sp_wcslider: 2
wcpa_pt_forms: 1
wp_block: 6
wp_global_styles: 2
wpcode: 47
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Admin Menu Editor: von Janis Elsts – 1.12
Advanced Custom Fields: von WP Engine – 6.2.2
Antispam Bee: von pluginkollektiv – 2.11.5
AutomateWoo: von WooCommerce – 6.0.7
Delete Me: von Clinton Caldwell – 3.0
GTM4WP: von Thomas Geiger – 1.18.1
Sofortige Indizierung: von Rank Math – 1.1.17
Flexible Shipping PRO: von Octolize – 2.16.6
Flexible Shipping: von Octolize – 4.23.0
WPCode Lite: von WPCode – 2.1.4.1
Kadence Blocks - PRO Extension: von Kadence WP – 2.0.16
Kadence Blocks - Gutenberg Blöcke für Page Builder Features: von Kadence WP – 3.1.23
Kadence Pro - Premium addon for the Kadence Theme: von Kadence WP – 1.0.14
Kadence Shop Kit: von Kadence WP – 2.0.24
Loco Translate: von Tim Whitlock – 2.6.6
Newsletter: von Stefano Lissa &
Das Newsletter Team – 8.0.2
One Stop Shop für WooCommerce: von vendidero – 1.4.0
Rank Math SEO PRO: von Rank Math – 3.0.48
Rank Math SEO: von Rank Math – 1.0.205
ShortPixel Image Optimizer: von ShortPixel - Convert WebP/AVIF & Optimize Images – 5.4.3
WooCommerce Custom Product Addons Free: von Acowebs – 3.0.4
WooCommerce Back In Stock Notifications: von WooCommerce – 1.6.6
Germanized für WooCommerce Pro: von vendidero – 3.8.2
Germanized für WooCommerce: von vendidero – 3.14.1
WooCommerce PayPal Payments: von WooCommerce – 2.3.1 (Update auf Version 2.4.0 ist verfügbar)
WooCommerce: von Automattic – 8.2.1
WP Admin Styling: von MI – 1.0
Asset CleanUp Pro: Page Speed Booster: von Gabe Livan – 1.2.4.6
WP Crontrol: von John Blackbourn & Mitwirkende – 1.16.0
WP Mail SMTP: von WP Mail SMTP – 3.9.0
WooCommerce Product Feed Manager: von Michel Jongbloed – 2.41.0
WP Rocket | Deactivate WooCommerce Refresh Cart Fragments Cache: von WP Rocket Support Team –
WP Rocket: von WP Media – 3.15.3
WPC Komposite-Produkte für WooCommerce: von WPClever – 7.1.5
PayPal Zettle POS: von PayPal – 1.5.7

### Inactive Plugins (1) ###

Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: von SeedProd – 6.15.15.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Asset CleanUp Pro: Plugin Filtering: von Gabriel Livan – 1.0
p3-profiler.php: von  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop-Basis: #401 - /produkte/
Warenkorb: #97 - /warenkorb/
Kasse: #98 - /zur-kasse/
Mein Konto: #99 - /konto/
Allgemeine Geschäftsbedingungen: #2079 - /agb/

### Theme ###

Name: Kadence
Version: 1.1.48
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: /home/wp/disk/wordpress/wp-content/plugins/kadence-woo-extras/lib/gallery/product-image.php

### Back In Stock ###

Database Version: 1.6.6
Loopback Test: ✔

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-06 09:08:35 +01:00
Options: ✔
Notes: 15
Onboarding: completed

### Action Scheduler ###

Canceled: 36
Oldest: 2023-10-31 21:27:28 +0100
Newest: 2023-11-05 12:56:02 +0100

Complete: 27.701
Oldest: 2023-10-30 12:40:11 +0100
Newest: 2023-11-05 16:19:08 +0100

Pending: 18
Oldest: 2023-11-05 16:20:02 +0100
Newest: 2023-11-08 12:40:02 +0100

### PayPal Zettle POS ###

Onboarding state: onboarding-completed
Price sync: yes
Initial sync collision strategy: merge
First import: 17:12 20. April 2022
Number of products syncing: 138
PayPal Zettle VAT: 19
PayPal Zettle currency: EUR
PayPal Zettle country: DE
PayPal Zettle language: de
PayPal Zettle time zone: Europe/Berlin
PayPal Zettle contact email: mail@oursecreturl.de
PayPal Zettle taxation mode: INCLUSIVE
PayPal Zettle taxation type: VAT
PayPal Zettle customer mode: LimitedCompany

### Status report information ###

Generated at: 2023-11-05 16:19:32 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @Mingendahl!

Thanks for the report 💯. This was fixed in #40516, which was included in 8.3.0, which went out yesterday. Please give it a go!
Feel free to re-open this issue if you are still encountering problems with this.

Thanks again!
