### ISSUE TITLE
Fix bug with initial pattern population

### ISSUE THREAD

**Issue by nerrad** [woothemes/woocommerce#41229]
As a result of testing, there is a bug popping up in the Woo Express environment where the first generated results is pulling up something like this:

![CleanShot 2023-11-03 at 14 07 28@2x](https://github.com/woocommerce/woocommerce-blocks/assets/1429108/270a86c2-e723-4230-95ce-75a6e7cafd33)

Some conversation in a Slack thread has suggested this may be a result of patterns being applied to the active Tsubaki theme _before_ the theme switch has occurred (and appears that the theme may not be switching?). 

Not sure which team should handle this but wanted to make sure it was reported.

cc @adrianduffell  and @chihsuan  as well in case this is something that would be better handled by Ghidorah.

**Comment by chihsuan** [comment]
> Some conversation in a Slack thread has suggested this may be a result of patterns being applied to the active Tsubaki theme before the theme switch has occurred (and appears that the theme may not be switching?).

I suspect some global state doesn't refresh after the theme switch. I'll look into it deeply today. 

> cc @adrianduffell and @chihsuan as well in case this is something that would be better handled by Ghidorah.

Thanks @nerrad, Ghidorah can fix it. Transfering this issue to Core.
