### ISSUE TITLE
REST API: Updating a category removes HTML from the description

### ISSUE THREAD

**Issue by redelschaap** [woothemes/woocommerce#41240]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I experience two issues regarding HTML in the product category description when using the REST API.

When creating or updating a product category using the REST API, most HTML is removed from the category description. However, the description supports more HTML when creating or editing a product category in the WordPress Admin, so I would say that the description field in the REST API should also support the same HTML options.

HTML is also removed from the category description when the description field is not included in the update request. In that case, I would expect that the description field remains unchanged.

### Expected behavior

HTML in category description is supported when creating/updating a product category using the REST API. At least on the same level as in the WP Admin product category create/edit page.

### Actual behavior

Most of the HTML is removed from the category description when creating/updating a product category using the REST API. Even when the category description field is not included in the update request.

### Steps to reproduce

1. Given the current state of the description:
![image](https://github.com/woocommerce/woocommerce-rest-api/assets/6915990/c8a391e1-c90c-486c-862a-46c76b4ca028)
2. After updating the category (with or without the description field present):
![image](https://github.com/woocommerce/woocommerce-rest-api/assets/6915990/b1279a9d-3ce5-4305-9002-039d8c26bf66)
3. The description is stripped from most HTML:
![image](https://github.com/woocommerce/woocommerce-rest-api/assets/6915990/2bf9273f-4a93-45ce-ab2d-bc0ad191d9eb)

Tested on different stores, with and without additional plugins.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://***
Site address (URL): https://***
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.28
PHP Post Max Size: 32 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 8.0.33-0ubuntu0.20.04.2
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: wp_
Totale database grootte: 35.65MB
Database gegevens grootte: 18.82MB
Database index grootte: 16.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.39MB + Index: 0.92MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.41MB + Index: 0.28MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 5.33MB + Index: 4.19MB + Engine InnoDB
wp_posts: Data: 2.06MB + Index: 1.22MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 2.52MB + Index: 5.66MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 2.02MB + Index: 2.33MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.23MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 885
page: 8
post: 5
product: 25
product_variation: 82
product-feed: 1
revision: 16
shop_coupon: 1
shop_order: 69
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Query Monitor: door John Blackbourn – 3.14.1
Redux Framework: door Team Redux – 4.4.9
Product Feed Manager for WooCommerce: door RexTheme – 7.3.16
Debug balk: door wordpresspuntorg – 1.1.4
EAN for WooCommerce Pro: door Algoritmika Ltd – 1.0.3
MainWP Child: door MainWP – 4.5.2
Mollie Payments for WooCommerce: door Mollie – 7.4.0
Storefront Sticky Add to Cart: door WooThemes – 1.1.8
UpdraftPlus - Backup/Restore: door UpdraftPlus.Com
DavidAnderson – 1.23.10

WC API Custom Meta: door Jason Judge – 0.7.1
WooCommerce Brands: door WooCommerce – 1.6.4
WooCommerce Cart Tab: door jameskoster – 1.1.2
WooCommerce Product Bundles: door WooCommerce – 6.22.4
Woocommerce upcoming Products: door Mohaiminul Islam – 1.5.9.2
WooCommerce: door Automattic – 8.2.1
Yoast SEO: door Team Yoast – 21.5
WP phpMyAdmin: door Puvox.software – 5.2.1.02
Yoast SEO: WooCommerce: door Team Yoast – 14.1

### Inactive Plugins (3) ###

Classic Editor: door WordPress Contributors – 1.6.3
Product GTIN (EAN, UPC, ISBN) for WooCommerce: door Emanuela Castorina – 1.1.1
WooCommerce Single Variations: door weLaunch – 1.3.18

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Winkelbasis: #4 - /winkel/
Winkelwagen: #5 - /winkelmand/
Afrekenen: #6 - /afrekenen/
Mijn account: #7 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Storefront Child
Version: 1.0
Author URL: https://webwhales.nl
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/single-product/add-to-cart/simple.php versie 3.0.0 is verouderd. De hoofdversie is 7.0.1
storefront-child/woocommerce/single-product/add-to-cart/variable.php versie 3.0.0 is verouderd. De hoofdversie is 6.1.0

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Product Bundles ###

Database Version: 6.22.4
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-06 13:42:50 +00:00
Options: ✔
Notes: 191
Onboarding: completed

### Action Scheduler ###

Afgerond: 2.476
Oldest: 2023-10-06 10:20:26 +0000
Newest: 2023-11-06 09:50:32 +0000

Mislukt: 10
Oldest: 2021-10-22 14:57:29 +0000
Newest: 2023-10-24 18:57:31 +0000

In afwachting: 5
Oldest: 2023-11-06 10:47:08 +0000
Newest: 2023-11-07 19:04:23 +0000

### Status report information ###

Generated at: 2023-11-06 10:18:25 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by redelschaap** [comment]
Any idea when this can be on the roadmap?

**Comment by shamimmoeen** [comment]
Hi @redelschaap,

I noticed you're using WooCommerce version 8.2.1. In your screenshot, the category description field appears as an HTML editor. However, in the latest version (8.7.0), the field is a plain textarea (when tested with only WooCommerce active and the Storefront theme).

<img width="1512" alt="Screenshot 2024-04-09 at 2 41 40 PM" src="https://github.com/woocommerce/woocommerce/assets/7997852/fb845f96-41b8-42a9-bbca-dda324560cd2">


Have you had a chance to test this behavior with WooCommerce 8.7.0 to see if the category description field remains a plain textarea even after deactivating other plugins and using either the WordPress default theme or the Storefront theme?

This would help us understand if the change is related solely to WooCommerce updates or interacts with other plugins/themes.

Thanks!

**Comment by naman03malhotra** [comment]
Hey @redelschaap, thanks for logging this issue.

**Here is what I did to test the issue and what I found:**

- I tried updating the description field from both the admin page and using the REST APIs in WC 8.2.1 and the latest version.
- I found the behavior to be consistent using both methods in both versions.
- This behavior is governed by how WordPress core sanitizes taxonomy fields.
- The rich text editor you are using is not an box feature of WooCommerce or Wordpress; probably that is coming from an plugin.

So here is the breakdown of what's happening under the hood.

- Both the methods (REST and WP Admin) uses the same [update_metadata](https://developer.wordpress.org/reference/functions/update_metadata/) function to update the values
- A few functions down, [`sanitizes_term_field` ](https://github.com/WordPress/WordPress/blob/a3f1555919d1ba66c1133230be610f42b705cda7/wp-includes/taxonomy.php#L1808) function applies a filter to sanitize the description value.
- A default set of filters then hooks into [`pre_term_description`](https://github.com/WordPress/WordPress/blob/a3f1555919d1ba66c1133230be610f42b705cda7/wp-includes/default-filters.php#L39) which uses `wp_filter_kses` function to sanitize the values.
- You can read more about it [here](https://developer.wordpress.org/reference/functions/wp_kses/).

I wrote a custom script to identify which tags are allowed here:

```php
echo '<pre>';
print_r( wp_kses_allowed_html( 'description' ) );
echo '</pre>';
```
output of which is

```
Array
(
    [a] => Array
        (
            [href] => 1
            [title] => 1
        )

    [abbr] => Array
        (
            [title] => 1
        )

    [acronym] => Array
        (
            [title] => 1
        )

    [b] => Array
        (
        )

    [blockquote] => Array
        (
            [cite] => 1
        )

    [cite] => Array
        (
        )

    [code] => Array
        (
        )

    [del] => Array
        (
            [datetime] => 1
        )

    [em] => Array
        (
        )

    [i] => Array
        (
        )

    [q] => Array
        (
            [cite] => 1
        )

    [s] => Array
        (
        )

    [strike] => Array
        (
        )

    [strong] => Array
        (
        )

)
```

The values mentioned in the keys of the object are allowed HTML tags via both REST API and WP Admin dashboard.

As this behavior is consistent with Wordpress, I will close this issue. If you'd like to suggest changing the default behavior on how we santize taxonomy fields, please raise an issue in WordPress repository.

**Comment by naman03malhotra** [comment]
Screen casts:

https://github.com/woocommerce/woocommerce/assets/15019298/1ea7c036-ea4d-4bd7-b876-3980407403b6


https://github.com/woocommerce/woocommerce/assets/15019298/ec149008-85a7-4143-8e3a-c23f2701a032

**Comment by redelschaap** [comment]
I'm pretty sure I tested this with all plugins disabled as well. However, I don't see the wysiwyg editor anymore when I test this again on a recently created WooCommerce store. Perhaps I was wrong about the plugins.

**Comment by naman03malhotra** [comment]
@redelschaap, you can still use HTML tags via APIs, but they are [limited](https://github.com/woocommerce/woocommerce/issues/41240#issuecomment-2075127598).
