### ISSUE TITLE
Multiple bugs seen in error log.

### ISSUE THREAD

**Issue by paaljoachim** [woothemes/woocommerce#41255]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Over the last few weeks I have noticed glitches and fatal errors which seems random. These go away on a browser refresh.
The error log lists a bunch of errors related to WooCommerce.

Error log errors.
[Mon Nov 06 21:41:51.275648 2023] [lsapi:error] [pid 181296] [client 82.134.65.206:50601] [host labhuset.no] Backend fatal error: PHP Fatal error:  Uncaught Error: Failed opening required '/home/L/labhusetno/www/wp-content/plugins/woocommerce/src/Admin/API/Reports/Coupons/Stats/

Controller.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90\nStack trace:\n#0 /home/L/labhusetno/www/wp-content/plugins/woocommerce/src/Admin/API/Init.php(146): 
Automattic\\Jetpack\\Autoloader\\jp865e0ff1636ff8bf9d922e869851562a\\PHP_Autoloader::load_class()\n#1 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(310): Automattic\\WooCommerce\\Admin\\API\\Init->rest_api_init()\n#2 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()\n#3 /home/L/labhusetno/www/wp-includes/plugin.php(517): WP_Hook->do_action()\n#4 /home/L/labhusetno/www/wp-includes/rest-api.php(587): do_action()\n#5 /home/L/labhusetno/www/wp-includes/rest-api.php(411): rest_get_server()\n#6 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(310): rest_api_loaded()\n#7 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()\n#8 /home/L/labhusetno/www/wp-includes/plugin.php(565): WP_Hook->do_action()\n#9 /home/L/labhusetno/www/wp-includes/class-wp.php(398): do_action_ref_array()\n#10 /home/L/labhusetno/www/wp-includes/class-wp.php(779): WP->parse_request()\n#11 /home/L/labhusetno/www/wp-includes/functions.php(1335): WP->main()\n#12 /home/L/labhusetno/www/wp-blog-header.php(16): wp()\n#13 /home/L/labhusetno/www/index.php(17): require('/home/L/labhuse...')\n#14 {main}\n  thrown in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90\n, referer: https://labhuset.no/wp-admin/post.php?post=3298&action=edit&classic-editor

Basic info:
Web site: https://labhuset.no/

### Expected behavior

Smooth transitions between various sections in the backend of the WordPress site. 

### Actual behavior

Going between various areas of the backend a glitch or a fatal error often shows up.

Example
![Screenshot 2023-11-06 at 22 29 08](https://github.com/woocommerce/woocommerce/assets/5323259/0ee21674-1824-470c-b046-b7b8e2124902)
As well as other similar errors show up way too often.

![Screenshot 2023-11-06 at 22 40 15](https://github.com/woocommerce/woocommerce/assets/5323259/3fca826d-436d-46b3-81d0-133b774b3d67)

There is also a slowness in the backend with Enfold and WooCommerce when going to edit products.

### Steps to reproduce

I do not know how to reproduce this one.

### WordPress Environment

System Status.

`
### WordPress Environment ###

WordPress address (URL): https://labhuset.no
Site address (URL): https://labhuset.no
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 896 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 (CloudLinux) OpenSSL/1.0.2k-fips
PHP Version: 8.1.13
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 2000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: dwew_
Total Database Size: 28.63MB
Database Data Size: 24.60MB
Database Index Size: 4.03MB
dwew_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dwew_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dwew_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_actionscheduler_actions: Data: 0.27MB + Index: 0.31MB + Engine InnoDB
dwew_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_actionscheduler_logs: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
dwew_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_cmplz_cookies: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
dwew_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
dwew_dgwt_wcas_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_hidemysiteSecure: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_dashboard_lockouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_itsec_firewall_rules: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
dwew_itsec_logs: Data: 0.52MB + Index: 0.33MB + Engine InnoDB
dwew_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dwew_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_itsec_vulnerabilities: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_itsec_webauthn_credentials: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_itsec_webauthn_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_koko_analytics_dates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
dwew_koko_analytics_post_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_koko_analytics_referrer_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_koko_analytics_referrer_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_koko_analytics_site_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
dwew_options: Data: 7.05MB + Index: 0.14MB + Engine InnoDB
dwew_postmeta: Data: 7.50MB + Index: 0.31MB + Engine InnoDB
dwew_posts: Data: 5.27MB + Index: 0.06MB + Engine InnoDB
dwew_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
dwew_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
dwew_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
dwew_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
dwew_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
dwew_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
dwew_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dwew_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dwew_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
dwew_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dwew_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_wpr_rucss_used_css: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
dwew_yoast_indexable: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
dwew_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dwew_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dwew_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dwew_yoast_prominent_words: Data: 0.08MB + Index: 0.17MB + Engine InnoDB
dwew_yoast_seo_links: Data: 0.09MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 107
avia_framework_post: 59
flamingo_contact: 7
itsec-dash-card: 10
itsec-dashboard: 1
nav_menu_item: 30
oembed_cache: 2
page: 24
portfolio: 6
post: 3
product: 58
revision: 23
wp_global_styles: 2
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

ManageWP - Worker: by GoDaddy – 4.9.17
Polylang: by WP SYNTEX – 3.5.2
Koko Analytics: by ibericode – 1.3.2
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.26.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.5
Contact Form 7: by Takayuki Miyoshi – 5.8.2
Disable Gutenberg: by Jeff Starr – 3.1
Discourage Search Engines Notifier: by <a href="http://ragu.cz">Ragu.cz</a> – 2.0
Duplicator Pro: by Duplicator – 4.5.13.3
Email Encoder - Protect Email Addresses: by Jannis Thuemmig – 2.1.8
Flamingo: by Takayuki Miyoshi – 2.4
Glow: by Glow – 3.2.0
Site Kit by Google: by Google – 1.111.1
Imsanity: by Exactly WWW – 2.8.3
Solid Security Pro: by SolidWP – 8.0.3
WooCommerce: by Automattic – 8.2.1
Yoast SEO Premium: by Team Yoast – 21.5
Yoast SEO: by Team Yoast – 21.5
WP Rocket: by WP Media – 3.15.3

### Inactive Plugins (7) ###

Autoptimize: by Frank Goossens (futtta) – 3.1.9
Code Snippets Pro: by Code Snippets Pro – 3.5.1
LiteSpeed Cache: by LiteSpeed Technologies – 5.7.0.1
Query Monitor: by John Blackbourn – 3.14.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.10

WP Fastest Cache: by Emre Vona – 1.2.1
WP WooCommerce Mailchimp: by Saint Systems – 2.4.12

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

ManageWP - Worker Loader: by GoDaddy – 1.0.0
WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Enfold
Version: 5.6.8
Author URL: https://kriesi.at
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-07 19:48:21 +00:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2023-10-26 15:02:25 +0000
Newest: 2023-10-26 15:02:25 +0000

Complete: 744
Oldest: 2023-10-07 20:39:19 +0000
Newest: 2023-11-06 21:15:50 +0000

Failed: 21
Oldest: 2023-09-07 20:53:31 +0000
Newest: 2023-10-31 15:35:26 +0000

In-progress: 1
Oldest: –
Newest: –

Pending: 43
Oldest: 2023-11-06 21:05:10 +0000
Newest: 2023-11-07 05:47:33 +0000

### Status report information ###

Generated at: 2023-11-06 21:29:13 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@paaljoachim I'd recommend re-installing WooCommerce by uploading the plugin zip. It doesn't happen very often but sometimes the WP installer misses installing/replacing a file. I'm going to mark this as a support request. If this were an issue with the latest release of WC our support team would definitely have received reports by now.

**Comment by paaljoachim** [comment]
Hi @rrennick Ron.
I went ahead and uploaded another version of WooCommerce. It did not seem to make any difference.
I made an issue here: https://wordpress.org/support/topic/recovery-mode-mentions-these-errors/

**Comment by rrennick** [comment]
@paaljoachim I'm not sure if you can edit your post but it would help others help you if you included which version of WC you are uploading and if it's only that specific version.

**Comment by paaljoachim** [comment]
Thanks @rrennick Ron. I made a followup to the above wp.org support issue.

**Comment by paaljoachim** [comment]
One more comment @rrennick Ron.
Going through the WooCommerce -> Status -> Logs 16 Nov entries.
I see perhaps 25-30 error "CRITICAL Uncaught Error:"..... entries for WooCommerce. I believe it has to do with PHP version 8.1 and perhaps also 8.0. If someone wants me to send them the error log let me know. I am also reachable through Making WordPress on Slack with my user name paaljoachim.

**Comment by paaljoachim** [comment]
Over and over again I see a problem with WooCommerce. 
I deactivated all plugins and downgraded the PHP from 8.1 to 8.0. Activated various plugins and WooCommerce and Solid Security both throws a fatal error to where I have to change the PHP back to 8.1.

I deactivated all plugins and downgraded the PHP from 8.1 to 7.4. Activated various plugins and WooCommerce added a fatal error to where I have to change the PHP back to 8.1.

**Comment by rrennick** [comment]
@paaljoachim I'm running the latest PHP 8.3 RC in my dev install and don't have any autoloader errors. Could you check to see if the file(s) the error `Failed opening required` exist and if they do, are the permissions the same as the other PHP files in WC?

**Comment by paaljoachim** [comment]
Hi @rrennick Ron.

I am searching through the debug log and will paste in just a few of the errors that mention Failed opening required.
In regards to permissions that I do not know.

Here is the full debug log: https://www.dropbox.com/scl/fi/avlduplv9nklwotkfium1/debug-2.log?rlkey=vyvdewevprc3gqvtyhz8w0nmy&dl=0


PHP Fatal error:  Uncaught Error: Failed opening required '/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCartContents.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90
Stack trace:
#0 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypesController.php(249): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\PHP_Autoloader::load_class()
#1 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypesController.php(61): Automattic\WooCommerce\Blocks\BlockTypesController->get_block_types()
#2 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\BlockTypesController->register_blocks()
#3 /home/L/labhusetno/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /home/L/labhusetno/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/L/labhusetno/www/wp-settings.php(643): do_action()
#6 /home/L/labhusetno/www/wp-config.php(97): require_once('/home/L/labhuse...')
#7 /home/L/labhusetno/www/wp-load.php(50): require_once('/home/L/labhuse...')
#8 /home/L/labhusetno/www/wp-admin/admin-ajax.php(22): require_once('/home/L/labhuse...')
#9 {main}
  thrown in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90

[17-Nov-2023 13:38:18 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CheckoutSchema.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90
Stack trace:
#0 [internal function]: Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\PHP_Autoloader::load_class()
#1 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/deprecated.php(73): class_alias()
#2 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-version-loader.php(89): require_once('/home/L/labhuse...')
#3 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-autoloader-handler.php(124): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Version_Loader->load_filemap()
#4 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-autoloader.php(80): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Autoloader_Handler->activate_autoloader()
#5 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/autoload_packages.php(13): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Autoloader::init()
#6 /home/L/labhusetno/www/wp-content/plugins/woocommerce/src/Autoloader.php(37): require('/home/L/labhuse...')
#7 /home/L/labhusetno/www/wp-content/plugins/woocommerce/woocommerce.php(27): Automattic\WooCommerce\Autoloader::init()
#8 /home/L/labhusetno/www/wp-settings.php(473): include_once('/home/L/labhuse...')
#9 /home/L/labhusetno/www/wp-config.php(97): require_once('/home/L/labhuse...')
#10 /home/L/labhusetno/www/wp-load.php(50): require_once('/home/L/labhuse...')
#11 /home/L/labhusetno/www/wp-blog-header.php(13): require_once('/home/L/labhuse...')
#12 /home/L/labhusetno/www/index.php(17): require('/home/L/labhuse...')
#13 {main}
  thrown in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90

[17-Nov-2023 13:53:47 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/ProductSchema.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90
Stack trace:
#0 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/ItemSchema.php(7): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\PHP_Autoloader::load_class()
#1 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php(90): require('/home/L/labhuse...')
#2 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CartItemSchema.php(10): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\PHP_Autoloader::load_class()
#3 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php(90): require('/home/L/labhuse...')
#4 [internal function]: Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\PHP_Autoloader::load_class()
#5 /home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/deprecated.php(73): class_alias()
#6 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-version-loader.php(89): require_once('/home/L/labhuse...')
#7 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-autoloader-handler.php(124): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Version_Loader->load_filemap()
#8 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-autoloader.php(80): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Autoloader_Handler->activate_autoloader()
#9 /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/autoload_packages.php(13): Automattic\Jetpack\Autoloader\jpb66f0c116f87680df45402a303db6f40\Autoloader::init()
#10 /home/L/labhusetno/www/wp-content/plugins/woocommerce/src/Autoloader.php(37): require('/home/L/labhuse...')
#11 /home/L/labhusetno/www/wp-content/plugins/woocommerce/woocommerce.php(27): Automattic\WooCommerce\Autoloader::init()
#12 /home/L/labhusetno/www/wp-settings.php(473): include_once('/home/L/labhuse...')
#13 /home/L/labhusetno/www/wp-config.php(97): require_once('/home/L/labhuse...')
#14 /home/L/labhusetno/www/wp-load.php(50): require_once('/home/L/labhuse...')
#15 /home/L/labhusetno/www/wp-blog-header.php(13): require_once('/home/L/labhuse...')
#16 /home/L/labhusetno/www/index.php(17): require('/home/L/labhuse...')
#17 {main}
  thrown in /home/L/labhusetno/www/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90

**Comment by rrennick** [comment]
> In regards to permissions that I do not know.

@paaljoachim Do the files exist? 

```
// from the 3 messages above

/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCartContents.php
/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CheckoutSchema.php
/home/L/labhusetno/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/ProductSchema.php
```

If those files exist then there's an issue in your server.

**Comment by paaljoachim** [comment]
Thanks @rrennick Ron!

I just checked and yes the files you mentioned do exist.
I have asked the web host earlier to check but they do not know what to check or what is wrong, so I need to figure out the correct questions/comments to help give them a direction of what to check.

**Comment by SANBOR20** [comment]
i have this error

how fix it
