### ISSUE TITLE
WP 6.4 - Order details look misaligned in Checkout page in the Twenty Twenty-Four theme

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#41266]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `Order details` info looks misaligned in stores with WordPress 6.4-RC4 and the Twenty Twenty-Four theme.

This is what it looks like in 6.3 with Twenty Twenty-Three:
![image](https://github.com/woocommerce/woocommerce/assets/45979455/b769fd6f-1283-45a7-ba3e-bdb9fc45c02e)

This is what it looks like in 6.4-RC4 with Twenty Twenty-Four:
![image](https://github.com/woocommerce/woocommerce/assets/45979455/5696dea9-078a-4a26-ad53-824174dffa78)

As you can see, the elements highlighted in red are aligned to the left, falling out of their respective columns:
![image](https://github.com/woocommerce/woocommerce/assets/45979455/5513e93b-c174-4858-b27c-573715451a46)

### Expected behavior

All elements should be aligned properly within their respective columns, like in the Twenty Twenty-Three screenshot shared above but following the Twenty Twenty-Four design.

### Actual behavior

The elements marked in red in the screenshot above are not aligned properly.

### Steps to reproduce

1. Make sure you're using the latest WooCommerce version in a site with WordPress 6.4-RC4 or later and the Twenty Twenty-Four theme.
1. Create a product.
2. Enable `Cash on delivery` or `Direct bank transfer` payment methods.
3. As a shopper, attempt to buy the product and complete all required forms and flows until you reach the `Order Confirmation` page (`/checkout/order-received/{orderId}/`).

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
This issue should wait for https://github.com/woocommerce/woocommerce-blocks/pull/11624 as that will change OC page

**Comment by wavvves** [comment]
I tested this and I can confirm this issue will be resolved when 11.4.4 gets included in Core

<img width="1360" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/4bf4ef03-5251-4947-a722-846720f13b61">

**Comment by wavvves** [comment]
Closed by https://github.com/woocommerce/woocommerce-blocks/pull/11615
Merged in https://github.com/woocommerce/woocommerce/pull/41276
