### ISSUE TITLE
WP 6.4 - Highlighted text through the <mark> HTML tag is not accessible in Twenty Twenty-Four

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#41268]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We used the <mark> HTML tag to highlight text in WooCommerce, for example, in the `/my-account/view-order/{order}` page.

In Twenty Twenty-Three, the highlighted text with the <mark> tag is styled in bold, but in Twenty Twenty-Four is just highlighted in yellow. This harms the UX in terms of accessibility and can be also quite confusing as the highlighted text looks quite similar to how the browsers highlight occurrences when you search for a word:
![image](https://github.com/woocommerce/woocommerce/assets/45979455/69d67bf5-7892-41ed-aa54-7e947fb984f2)

It would be great if we could find another way to highlight text in this theme.

### Expected behavior

Highlighted text should be accessible. Like, for example, bold.

### Actual behavior

Highlighted text is not accessible, as the only thing that changes is the background colour to yellow. This didn't happen in Twenty Twenty-Three, for example.

### Steps to reproduce

1. Make sure you're using the latest WooCommerce version in a site with WordPress 6.4-RC4 or later and the Twenty Twenty-Four theme.
2. Create a product.
3. Enable Cash on delivery or Direct bank transfer payment methods.
4. As a shopper, buy the product.
5. As a shopper, go to `My Account -> Orders` and click the `View` button for the order you just bought.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
I'm not sure this is a high priority but agree it should be addressed.
