### ISSUE TITLE
Enable GPT-4 Turbo on generic text completion endpoint

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#41261]
![Image](https://github.com/woocommerce/woocommerce/assets/6723003/4ec56a7b-61fe-4d6e-ae90-249a38635241)

**Comment by tommyshellberg** [comment]
This isn't widely available yet, as we're heavily rate limited to 100 queries a day, should be available in December.

**Comment by nima-karimi** [comment]
Ready for review: D144060

**Comment by tommyshellberg** [comment]
Thanks for doing this @nima-karimi - as mentioned in the diff, this looks totally fine for Woo AI but we'll want to check with any teams using this endpoint as it looks like GPT 4 Turbo might often be slower than 3.5 Turbo, so, if performance is paramount, some teams might want to stick with 3.5 Turbo.

**Comment by nima-karimi** [comment]
Thanks. I posted a request for comments to hear from the other teams (pf8sIm-oo-p2). We could also add an option to use either model and default to 3.5 to prevent any side effects. That way, we could use it for Woo AI, and other teams could opt for it for new features and migrate the previous ones gradually.

**Comment by nima-karimi** [comment]
Merged D144060 with GPT-4-Turbo as default and an optional `model` parameter for the API.
