### ISSUE TITLE
[GlobalStep] PHP error warning (Undefined array key "blockName" and Undefined array key "innerBlocks") triggered on Checkout page after clicking "Proceed to checkout" button on test page with “Cart Block”. 

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#41273]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP error warning (Undefined array key "blockName" and Undefined array key "innerBlocks") triggered on Checkout page after clicking "Proceed to checkout" button on test page with “Cart Block”. 

### Expected behavior

No PHP error warning should be triggered on Checkout page after clicking "Proceed to checkout" button on test page with “Cart Block”. 

### Actual behavior

PHP error warning (Undefined array key "blockName" and Undefined array key "innerBlocks") triggered on Checkout page after clicking "Proceed to checkout" button on test page with “Cart Block”. 

### Steps to reproduce

1. Create test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce 8.3.0.40 plugins.
4. Go to the Cart page and then proceed to the Checkout page.
5. Observe that, PHP error warning (Undefined array key "blockName" and Undefined array key "innerBlocks") triggered on Checkout page after clicking "Proceed to checkout" button.

### Stack Trace:

[Undefined array key blockName.txt](https://github.com/woocommerce/woocommerce/files/13283339/Undefined.array.key.blockName.txt)
[Undefined array key innerBlocks.txt](https://github.com/woocommerce/woocommerce/files/13283341/Undefined.array.key.innerBlocks.txt)

### Screenshot:

![#41273](https://github.com/woocommerce/woocommerce/assets/41110392/ce930b45-c7d6-40ec-9d9a-f2dfdec15fe2)

### WordPress Environment

Woocommerce Version: 8.3.0.40
WordPress version: v6.4-RC3
PHP version: 8.1.25

PC:
Windows 10
Chrome(Version 119.0.6045.106)
Firefox (Version 119.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.3
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 6.4-RC3 - There is a newer version of WordPress available (6.4-RC4)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0.30
WC Database Prefix: wp_
Total Database Size: 4649.01MB
Database Data Size: 2658.91MB
Database Index Size: 1990.10MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.34MB + Index: 0.59MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1604.97MB + Index: 1304.81MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1029.98MB + Index: 677.89MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 2.50MB + Index: 1.80MB + Engine InnoDB
wp_posts: Data: 3.30MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.22MB + Index: 0.48MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpml_mails: Data: 8.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 70
jetpack_migration: 2
jp_img_sitemap: 8
jp_pay_product: 2
jp_sitemap: 8
jp_sitemap_master: 8
mailpoet_page: 1
page: 22
post: 6
product: 39
product_variation: 11
revision: 156
shop_coupon: 42
shop_order: 272
shop_order_placehold: 5
wp_global_styles: 3
wp_navigation: 2
wp_template: 2
wp_template_part: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Query Monitor: by John Blackbourn – 3.14.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
AutomateWoo: by WooCommerce – 6.0.8
Crowdsignal Forms: by Automattic – 1.7.0
Facebook for WooCommerce: by Facebook – 3.1.2
WordPress.com Editing Toolkit: by Automattic – 4.2608
Google Listings and Ads: by WooCommerce – 2.5.11
Gutenberg: by Gutenberg Team – 16.9.0
Jetpack: by Automattic – 12.8-beta
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.4
Pinterest for WooCommerce: by WooCommerce – 1.3.13
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.11

TikTok: by TikTok – 1.2.1
Woo AI: by WooCommerce – 0.5.0
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.6
WooCommerce Beta Tester: by WooCommerce – 2.2.4
WooCommerce Brands: by WooCommerce – 1.6.62
WooCommerce Gift Cards: by WooCommerce – 1.16.6
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.9
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 6.7.1
WooCommerce Product Add-ons: by WooCommerce – 6.5.0
WooCommerce Product Bundles: by WooCommerce – 6.22.4
WooCommerce Product Recommendations: by WooCommerce – 3.0.3
WooCommerce Shipping & Tax: by WooCommerce – 2.4.0
WooCommerce Shipment Tracking: by WooCommerce – 2.4.1
WooCommerce: by Automattic – 8.3.0.40
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (12) ###

Avalara AvaTax: by Avalara – 2.6.1
Classic Editor: by WordPress Contributors – 1.6.3
MailPoet: by MailPoet – 4.35.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.7
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.4
WooCommerce EU VAT Number: by WooCommerce – 2.8.8
WooCommerce FedEx Shipping: by WooCommerce – 3.8.5
WooCommerce Royal Mail: by WooCommerce – 3.0.1
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.5
WP Crontrol: by John Blackbourn & crontributors – 1.16.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #45 - /shop/
Cart: #201 - /test-cart/
Checkout: #47 - /checkout/
My account: #48 - /my-account/
Terms and conditions: #22 - /blog/

### Theme ###

Name: Tsubaki
Version: 1.2.2
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### WooPayments ###

Version: 6.7.1
Connected to WPCOM: Yes
WPCOM Blog ID: 220476338
Account ID: acct_1NiurqC6NFOedpRk
Payment Gateway: Enabled
Test Mode: Enabled
UPE: Enabled (deferred_intent)
UPE Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Back In Stock ###

Database Version: 1.6.6
Loopback Test: ✔

### Gift Cards ###

Database Version: 1.16.6
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.22.4
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
navigation
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2023-11-08 07:02:47 +00:00
Options: ✔
Notes: 93
Onboarding: skipped

### Action Scheduler ###

Canceled: 12
Oldest: 2023-10-10 21:52:54 +0100
Newest: 2023-11-07 15:15:17 +0000

Complete: 4,839,138
Oldest: 2023-08-17 08:46:03 +0100
Newest: 2023-11-07 16:22:18 +0000

Failed: 1,374
Oldest: 2023-06-28 21:10:01 +0100
Newest: 2023-10-26 14:58:51 +0100

Pending: 20
Oldest: 2023-11-07 16:24:16 +0000
Newest: 2024-01-28 14:54:17 +0000

### Product Recommendations ###

Database Version: 3.0.3
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: No cache detected

### Status report information ###

Generated at: 2023-11-07 16:23:09 +00:00
`

</details>

**Comment by nerrad** [comment]
@senadir would this be related to tracking data that was added? It _looks_ like the screenshot is of the classic checkout shortcode. However, I'm unable to reproduce this error for either checkout block or shortcode so I'm guessing this already got fixed?

**Comment by senadir** [comment]
Yes, this was solved here
https://github.com/Automattic/jetpack/pull/33947
