### ISSUE TITLE
Add a Grafana Alert notification

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#41299]
We have Grafana views which track errors for AI requests, however, we don't have any alerts set up. 
We can do this by setting an Alert through Grafana, but, we'll need to create a Slack app, invite it to the Slack channel, get a webhook URL, etc in order to send alerts to a Slack channel.

See here:
PCYsg-imO-p2

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
