### ISSUE TITLE
Analytics UI issue: The date range picker UI seems broken

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#41297]
The date range picker UI seems broken on every Analytic page, this also includes the calendar under the `custom` tab. One has to click the date range picker multiple items to select a date range as the calendar auto closes upon click.

![Screenshot 2023-11-08 at 12 04 15](https://github.com/woocommerce/woocommerce/assets/1314156/0fcb09c9-3291-4f5d-9de6-788387b6d091)

### Steps to reproduce

1. Using WP 6.4 and WC 8.2.1 go to Analytics > Revenue.
2. Press the date range picker.
3. The UI is broken.

### WordPress Environment

WP 6.4
WooCommerce 8.2.1

**Comment by nerrad** [comment]
This is a breaking bug. Why is it not being worked on?
