### ISSUE TITLE
[Product Editor] Page freeze when hitting preview after editing variation

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#41296]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The page freezes on a variation page after navigating to an individual variation and back to the main product within the new editor.

**How to reproduce:**

1. Enable the new product editor under **WooCommerce > Settings > Advanced > Features**
2. Create a new variable product with the new editor with some variations
3. Click edit on one of the variations
4. Go back to Main product using the header link
5. Click Preview button
6. Watch the page do nothing and freeze instead

https://github.com/woocommerce/woocommerce/assets/2240960/97044379-93f6-45ed-9611-b9f71632ff51

**Comment by retrofox** [comment]
I'm not able to reproduce the issue. However, I've seen erratic behavior when clicking on the Preview button :-/


https://github.com/woocommerce/woocommerce/assets/77539/6f0c8df1-84bb-408d-b876-6670e5059a3d

**Comment by louwie17** [comment]
> I'm not able to reproduce the issue. However, I've seen erratic behavior when clicking on the Preview button :-/

Hmm yeah I can't reproduce it anymore either, I will close this issue.
I don't see the erratic behaviour as you mention, for me it just opens up a new tab for the preview, what browser are you using?

Also I did notice that clicking `edit` on a variation does a full page refresh which is less then ideal. Using react router would be better there.
