### ISSUE TITLE
Home screen grey background to disappear

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#41308]
Navigating to the new product editor and back to the WooCommerce home screen causes the grey background to disappear and show a white background instead.

### Expected behavior

The grey background shouldn't disappear.

### Steps to reproduce

1. Enable the new product editor at wp-admin/admin.php?page=wc-settings&tab=advanced&section=features.
2. Go to Products > Add new.
3. Go back to the WooCommerce home screen.
4. The grey background disappeared.

### WordPress Environment

- WP 6.4
- WooCommerce 8.3.0 RC 1

**Comment by pmcpinto** [comment]
@octaedro can you confirm this is still valid? I'm not finding a way to replicate this with the latest WC version. Thanks

**Comment by octaedro** [comment]
Hi @pmcpinto,
Yes, the error is still there. I just created a brand new JN using the latest `trunk` and I reproduced the bug

![Screen Recording on 2024-02-26 at 11-08-05](https://github.com/woocommerce/woocommerce/assets/1314156/3ed46dd8-5cfe-46de-81cc-3cc449e75c06)

**Comment by pmcpinto** [comment]
Thanks for checking this.
