### ISSUE TITLE
Message toast looks off

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#41313]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the classic editor, this message toast looks off. This is happening to every toast.

![Screenshot 2023-11-08 at 17 45 38](https://github.com/woocommerce/woocommerce/assets/1314156/9bce18bb-8087-416e-954b-56c73602934c)

### Expected behavior

Every message toast should be displayed correctly.

### Actual behavior

The message toasts alignment is broken.

### Steps to reproduce

0. In the legacy product experience.
1. Go to Products > Add new.
2. Under Product data, select `Variable product`.
3. Go to Attributes and create an attribute with at least one value.
4. Go to Variations and press `Generate variations`.
5. The toast shown after generating the variations is broken.

### WordPress Environment

- WP 6.4
- WooCommerce 8.2.1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
Being addressed as part of https://github.com/woocommerce/woocommerce/pull/41399
