### ISSUE TITLE
[Enhancement]: Filter for checkout whilest cart empty string

### ISSUE THREAD

**Issue by gsg-thomas** [woothemes/woocommerce#41340]
### Describe the solution you'd like

I’ve had a request to change this string ("Checkout is not available whilst your cart is empty") but found it’s untouchable without a filter.

Thank you

### Describe alternatives you've considered

String translation

**Comment by tarunvijwani** [comment]
@gsg-thomas Thank you for reaching out. We're removing that string in https://github.com/woocommerce/woocommerce/pull/41504 PR. Please let us know if you still need any help with it.

**Comment by ralucaStan** [comment]
closing this, @gsg-thomas feel free to continue the discussion in the future if needed
