### ISSUE TITLE
WC REST API - Variations endpoints ignores the parent id: /wc/v3/products/<product_id>/variations/<variation_id>

### ISSUE THREAD

**Issue by jorgemd24** [woothemes/woocommerce#41373]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When making the following REST API call: /`wp-json/wc/v3/products/<product_id>/variations/<id>`, the parent id (product_id) is ignored, and it will retrieve the variation independently if the parent id is correct or if exists.

A similar issue happened when updating the variation. See here: https://github.com/woocommerce/woocommerce/issues/18933

In this case, simply fetching the variation data doesn't create any risk, but it can be misleading, considering that the documentation specifies that product_id should be the parent ID.

### Expected behavior

When sending the following request: `wp-json/wc/v3/products/NOT_EXISTING_PRODUCT_ID/variations/REAL_VARIATION_ID`, it should return a 404 error since the parent does not include that variation ID and the parent does not exist.

### Actual behavior

When making the following request: `wp-json/wc/v3/products/NOT_EXISTING_PRODUCT_ID/variations/REAL_VARIATION_ID`
it returns the data from the "REAL_VARIATION_ID". 

### Steps to reproduce

1. Make this request: GET `wp-json/wc/v3/products/NOT_EXISTING_PRODUCT_ID/variations/REAL_VARIATION_ID`
2. See that the API response with the data from the variation id.

### WordPress Environment

WC 8.3.0
WP 6.4.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@jorgemd24 Could you pick which of #41373 and #41374 you would like to keep open and close the other one?

**Comment by jorgemd24** [comment]
Hi @rrennick, each issue affects different endpoints:

- ` /wp-json/wc/v3/products/<product_id>/variations/<id>`
-  `/wp-json/wc/v3/products/<product_id>`

Even though both are related to variations. Do you prefer to "merge" both issues into one? If so, we can keep this one, https://github.com/woocommerce/woocommerce/issues/41373, open and simply reference the other issue.

**Comment by rrennick** [comment]
@jorgemd24 Thanks for the follow up. We'll leave them both open on the chance that they are not the result of the same root issue.
