### ISSUE TITLE
[Enhancement]: Usage tracking under the Advanced tab still refers to WooCommerce.com

### ISSUE THREAD

**Issue by jacoswan** [woothemes/woocommerce#41381]
### Describe the solution you'd like

Under WooCommerce > Settings > Advanced, there's still a reference to WooCommerce.com instead of Woo.com.

The link under that tab also points to `https://woocommerce.com/usage-tracking` instead of `https://woo.com/usage-tracking/`.

**Comment by lsinger** [comment]
Thank you @jacoswan! Are you seeing this in `trunk` or in the latest release? This should have been resolved already with #41241 that was merged yesterday. It will likely be released with 8.4.0, so it wouldn't be available in an official release yet. 

Closing as I can't find it in `trunk` anymore, but please feel free to re-open if I overlooked anything.
