### ISSUE TITLE
Sidebar search button custom text option without coding

### ISSUE THREAD

**Issue by shop-developer** [woothemes/woocommerce#41380]
### Describe the solution you'd like

How to change the WooCommerce product search sidebar widget button text from “SEARCH” to “FIND” without coding?

Suggest new add front end feature

### Describe alternatives you've considered

Coding overwritten by WooCommerce updates/funtionality risk

**Comment by rrennick** [comment]
@shop-developer Could you edit the issue description and provide a more detailed description of what you are requesting?

**Comment by shop-developer** [comment]
WooCommerce search box action button reads SEARCH

Example https://kereta.madrasthemes.com/

Can't change text without coding?

Should be in WooCommerce customization settings

**Comment by kmanijak** [comment]
Hi @shop-developer,

It would be great if you could provide more details regarding this issue. I'd be most interested in:

- what theme you're using (classic or block theme)
- what's the widget's or block's name

I think you're using Product Search block. In that case you should be able to go to **Appearance -> Widgets** (if it's a classic theme) find the usage of Product Search and simply edit the button text:

https://github.com/woocommerce/woocommerce/assets/20098064/dc185b75-c3b6-4cc7-ad40-a886e7336d6d

Let me know if that helps! 🙏 If not please provide more info so we can help you better.

**Comment by gigitux** [comment]
Closing this issue as it primarily pertains to a support request.
