### ISSUE TITLE
Tree Select Control: Enter button should select/unselect

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#41420]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The `Enter` button should select and unselect options when focus is on an option.

**Comment by rrennick** [comment]
@psealock Can you label this one? It doesn't have enough info in it for me to determine who it belongs to.
