### ISSUE TITLE
[?] icon should be in-line with the text, and tooltip should have a max-width

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#41447]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Under `Inventory` > `Restrictions`, the [?] icon appears underneath the checkbox. 
The tooltip is also very long and does not appear to have a max-width. 

<img width="736" alt="Screenshot 2023-11-15 at 1 49 10 PM" src="https://github.com/woocommerce/woocommerce/assets/65582817/580ef6e0-ff6c-49a1-bffe-15c7c01fd6dc">
<img width="1051" alt="Screenshot 2023-11-15 at 1 49 51 PM" src="https://github.com/woocommerce/woocommerce/assets/65582817/c9ef0077-44a6-4cd8-9459-c5c03ba79ccc">

### Expected behavior

- The [?] icon should appear on the right of the text `Limit purchases to 1 item per order`
- The tooltip that appears on hover should have a max-width that is the same as the max-width of all other tooltips.

### Actual behavior

Under `Inventory` > `Restrictions`, the [?] icon appears underneath the checkbox. 
The tooltip is also very long and does not appear to have a max-width. 

### Steps to reproduce

Add new product > Inventory > Advanced 

### WordPress Environment

New Product Form Demo

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@louwie17 we should include this fix in the current cycle. Thanks

**Comment by octaedro** [comment]
Hi @j111q,
Thank you for reporting this.

> Under Inventory > Restrictions, the [?] icon appears underneath the checkbox.

I'm testing it on a JN site using WP 6.4.1 and WC 8.4.0.20, but I couldn't reproduce the error. Are you using any particular plugin? Also, which version of WP did you use?
