### ISSUE TITLE
[Enhancement]: Enable HPOS, I got very slow queries in a more than 400,000 orders store

### ISSUE THREAD

**Issue by tinashe2015** [woothemes/woocommerce#41454]
### Describe the solution you'd like

before enable HPOS, I search a order need 6 seconds, the slow query is about 3-5s, then afte i enable HPOS in test site, i got slow query recored more than 10 seconds, 
the mysql sql is 
```
SELECT wp_wc_orders.id
FROM wp_wc_orders
LEFT JOIN wp_woocommerce_order_items AS search_query_items
ON search_query_items.order_id = wp_wc_orders.id
WHERE 1=1
AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed','wc-partial-payment'))
AND (wp_wc_orders.type = 'shop_order')
AND ( ( `wp_wc_orders`.id = 672253
OR search_query_items.order_item_name LIKE '%672253%'
OR `wp_wc_orders`.id IN (
SELECT search_query_meta.order_id
FROM wp_wc_orders_meta as search_query_meta
WHERE search_query_meta.meta_key IN ( '_billing_address_index','_shipping_address_index' )
AND search_query_meta.meta_value LIKE '%672253%'
GROUP BY search_query_meta.order_id ) ) )
GROUP BY wp_wc_orders.id
ORDER BY wp_wc_orders.date_created_gmt DESC
LIMIT 0, 20
```
here is Query Monitor result,
<a href="https://ibb.co/FK9GmqP"><img src="https://i.ibb.co/xDyVX84/slow-query.jpg" alt="slow-query" border="0"></a>
So can this mysql statement still be optimized?

-----------------
update

I try to test some different queries

first, original mysql statement
```
SELECT
	wp_wc_orders.id 
FROM
	wp_wc_orders
	LEFT JOIN wp_woocommerce_order_items AS search_query_items ON search_query_items.order_id = wp_wc_orders.id 
WHERE
	1 = 1 
	AND (
	wp_wc_orders.STATUS IN ( 'wc-pending', 'wc-processing', 'wc-on-hold', 'wc-completed', 'wc-cancelled', 'wc-refunded', 'wc-failed', 'wc-partial-payment' )) 
	AND ( wp_wc_orders.type = 'shop_order' ) 
	AND (
		(
			`wp_wc_orders`.id = 672253 
			OR search_query_items.order_item_name LIKE '%672253%' 
			OR `wp_wc_orders`.id IN (
			SELECT
				search_query_meta.order_id 
			FROM
				wp_wc_orders_meta AS search_query_meta 
			WHERE
				search_query_meta.meta_key IN ( '_billing_address_index', '_shipping_address_index' ) 
				AND search_query_meta.meta_value LIKE '%672253%' 
			GROUP BY
				search_query_meta.order_id 
			) 
		) 
	) 
GROUP BY
	wp_wc_orders.id 
ORDER BY
	wp_wc_orders.date_created_gmt DESC 
	LIMIT 0,
	20
> OK
> Time: 14.046s
```

second, delete the parts related to wp_woocommerce_order_items table
```
SELECT
    wp_wc_orders.id
FROM
    wp_wc_orders
WHERE
    1 = 1
    AND wp_wc_orders.status IN ('wc-pending', 'wc-processing', 'wc-on-hold', 'wc-completed', 'wc-cancelled', 'wc-refunded', 'wc-failed', 'wc-partial-payment')
    AND wp_wc_orders.type = 'shop_order'
    AND (
        wp_wc_orders.id = 672253
        OR wp_wc_orders.id IN (
            SELECT
                search_query_meta.order_id
            FROM
                wp_wc_orders_meta AS search_query_meta
            WHERE
                search_query_meta.meta_key IN ('_billing_address_index', '_shipping_address_index')
                AND search_query_meta.meta_value LIKE '%672253%'
            GROUP BY
                search_query_meta.order_id
        )
    )
GROUP BY
    wp_wc_orders.id
ORDER BY
    wp_wc_orders.date_created_gmt DESC
LIMIT 0, 20
> OK
> Time: 31.381s
```
3th, delete the parts related to wp_woocommerce_order_items and wp_wc_orders_meta table
```
SELECT
    wp_wc_orders.id
FROM
    wp_wc_orders
WHERE
    wp_wc_orders.status IN ('wc-pending', 'wc-processing', 'wc-on-hold', 'wc-completed', 'wc-cancelled', 'wc-refunded', 'wc-failed', 'wc-partial-payment')
    AND wp_wc_orders.type = 'shop_order'
    AND wp_wc_orders.id = 672253
GROUP BY
    wp_wc_orders.id
ORDER BY
    wp_wc_orders.date_created_gmt DESC
LIMIT 0, 20
> OK
> Time: 0.174s
```
Woocommerce's default order search function is very convenient for a small number of orders. It can search for any content, including but not limited to order number, email, name, address, etc. 
But for customers with a large number of orders, this A combined search will make the search very slow. Even if the server configuration is improved and the database is optimized, the degree of improvement is limited. Both the previous database table and the current HPOS have the same problem. 
So can you add some new functions (such as selecting elements) to the search place? We can choose to search all data, or specified data fields, such as order id, email, etc.

**Comment by coreymckrill** [comment]
This looks like a duplicate of #38675. I'm going to close this in favor of that one, but feel free to open it back up if there's something here that isn't captured in the other one.

**Comment by tinashe2015** [comment]
> This looks like a duplicate of #38675. I'm going to close this in favor of that one, but feel free to open it back up if there's something here that isn't captured in the other one.

Woocommerce version 8.4.0
test again,

SELECT wp_wc_orders.id
FROM wp_wc_orders
LEFT JOIN wp_woocommerce_order_items AS search_query_items
ON search_query_items.order_id = wp_wc_orders.id
WHERE 1=1
AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed'))
AND (wp_wc_orders.type = 'shop_order')
AND ( ( `wp_wc_orders`.id = 672253
OR search_query_items.order_item_name LIKE '%672253%'
OR `wp_wc_orders`.id IN (
SELECT search_query_meta.order_id
FROM wp_wc_orders_meta as search_query_meta
WHERE search_query_meta.meta_key IN ( '_billing_address_index','_shipping_address_index' )
AND search_query_meta.meta_value LIKE '%672253%'
GROUP BY search_query_meta.order_id ) ) )
GROUP BY wp_wc_orders.id
ORDER BY wp_wc_orders.date_created_gmt DESC
LIMIT 0, 20

Time:70s

still long time

**Comment by tinashe2015** [comment]
> > This looks like a duplicate of #38675. I'm going to close this in favor of that one, but feel free to open it back up if there's something here that isn't captured in the other one.
> 
> Woocommerce version 8.4.0 test again,
> 
> SELECT wp_wc_orders.id FROM wp_wc_orders LEFT JOIN wp_woocommerce_order_items AS search_query_items ON search_query_items.order_id = wp_wc_orders.id WHERE 1=1 AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed')) AND (wp_wc_orders.type = 'shop_order') AND ( ( `wp_wc_orders`.id = 672253 OR search_query_items.order_item_name LIKE '%672253%' OR `wp_wc_orders`.id IN ( SELECT search_query_meta.order_id FROM wp_wc_orders_meta as search_query_meta WHERE search_query_meta.meta_key IN ( '_billing_address_index','_shipping_address_index' ) AND search_query_meta.meta_value LIKE '%672253%' GROUP BY search_query_meta.order_id ) ) ) GROUP BY wp_wc_orders.id ORDER BY wp_wc_orders.date_created_gmt DESC LIMIT 0, 20
> 
> Time:70s
> 
> still long time

i check the database
**Table 'wp_wc_orders_meta' field 'meta_key' length is 255**
check max length fot meta_key  'SELECT max(LENGTH(meta_key)) FROM wp_wc_orders_meta'
value is 45, it is mean for a store with a particularly large number of orders, the max length of this field is only 45, but the default length is 255, and this field no index
**i change meta_key length to 191, and add index for meta_key,**
then test again
for a new any other order id (the reason for using a new order id is to exclude caching)

SELECT wp_wc_orders.id
FROM wp_wc_orders
LEFT JOIN wp_woocommerce_order_items AS search_query_items
ON search_query_items.order_id = wp_wc_orders.id
WHERE 1=1
AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed'))
AND (wp_wc_orders.type = 'shop_order')
AND ( ( `wp_wc_orders`.id = 672135
OR search_query_items.order_item_name LIKE '%672135%'
OR `wp_wc_orders`.id IN (
SELECT search_query_meta.order_id
FROM wp_wc_orders_meta as search_query_meta
WHERE search_query_meta.meta_key IN ( '_billing_address_index','_shipping_address_index' )
AND search_query_meta.meta_value LIKE '%672135%'
GROUP BY search_query_meta.order_id ) ) )
GROUP BY wp_wc_orders.id
ORDER BY wp_wc_orders.date_created_gmt DESC
LIMIT 0, 20

**Times: 8.4465s**

query time is reduced significantly
so **there are the same problems as the old version (Before HOPS)
meta_key no index**
(Before HOPS, all data are in wp_postmeta and also no index in meta_key)

but 8.4465s is still long time

**Comment by Ekliptor** [comment]
I can confirm that the default compound index on `wp_wc_orders_meta` is a lot slower than adding an index for the `meta_key` column myself. I also have queries taking 80 seconds on MariaDB 11.2

**Comment by vedanshujain** [comment]
I tested these queries on my shop with 2.5 million orders. The performance of this query can be evenly split into performance in order items meta table for product name and orders meta table for address.

Allowing user to select where to search is a pretty good idea, I suppose whoever is searching something would almost always know whether they are searching for a product name, vs when they are searching for a customer name and address. 

Additionally, the query for searching customer address can be optimized by adding a limit to it. In my testing, performance of that part of query improved from 2.38 seconds to 0.0007 seconds when I added a limit, and there where results for the query. When there were no results, query still took 2.38, but we will be able to optimize in most cases.

One of the goals for HPOS is to add FTS indexes for customer addresses, we can explore that as part of this issue as well.

So going to split this work into three different tasks:

- [x] Modify admin interface to specify which field user would like to search (egs, customer address, email, product name etc)
- [ ] Add limits to customer address search query 
- [ ] Add FTS indexes to customer addresses columns in HPOS tables (and stop using billing and shipping meta)

**Comment by tinashe2015** [comment]
Yes, I want to try adding some new search boxes to the search form myself.
Most of the time, we can only search for order id, order email,
I try to only search order id in database, it is very very fast
maybe can add a search select box like this
![image](https://github.com/woocommerce/woocommerce/assets/150897370/7391793c-cae3-4cea-b0c5-dc2b4e6f4a2c)
I just saw your update #43356, thank you very much for your efforts and looking forward to new updates

**Comment by DavidAnderson684** [comment]
For a good number of search terms, it would be possible to limit what is searched just by matching the search term. e.g. if the search term is an email address, search only fields that are email addresses. If the field is an integer, search only relevant fields for that (e.g. order ID).

**Comment by mouligreenlaw** [comment]
Another instance: 7591521-zen

**Comment by vedanshujain** [comment]
> it would be possible to limit what is searched just by matching the search term. e.g. if the search term is an email address, search only fields that are email addresses. If the field is an integer, search only relevant fields for that (e.g. order ID).

Makes sense, I think we can add couple of new filters to support searching by ID and Email directly, that would be superfast.

**Comment by hagedigital** [comment]
When will the FTS indexes be actioned for the addresses? This seems to be the main issue
