### ISSUE TITLE
Digital and Downloads - introduce a new ExPlat experiment in 8.4

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#41460]
**Description:** as we prepare the release of the digital and download flows, we keep the incremental approach and introduce a new experiment in 8.4 to release the feature to a small subset of users. 

**Acceptance criteria:**

- [x] Replicate the experiment running in 8.3. The only difference is that new users who select the digital product option should also be exposed to the experiment. In sum, we should expose users who select one of the following options in the "Add products" task: Physical product, Variable product, and Digital product.
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.
- [x] Take into account that the experiment will be released a few days before in the Atomic weekly release.

**Comment by pmcpinto** [comment]
cc @jarekmorawski

**Comment by pmcpinto** [comment]
cc @louwie17

**Comment by AnnaMag** [comment]
> Create the experiment P2. 

done, pending adding user target %s.

**Comment by AnnaMag** [comment]
> Take into account that the experiment will be released a few days before in the Atomic weekly release.

@louwie17 Just an FYI in case it is helpful. The above item translates to manually starting the test on the 28th of November ( assuming this PR is merged before 2359 UTC next Wednesday).

**Comment by louwie17** [comment]
Closing this, as everything is set up for the experiment to launch next week.
