### ISSUE TITLE
Switch from squizlabs/php_codesniffer to its fork replacement

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#41475]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The fork hasn't been announced yet but the squizlabs/php_codesniffer composer package has been abandoned. We should update to the fork once it has been announced.

Ref: p1699460101946809-slack-C02ECE3ML

**Comment by adimoldovan** [comment]
Reopening because the change was reverted with https://github.com/woocommerce/woocommerce/pull/46524

**Comment by kalessil** [comment]
@rrennick @adimoldovan: no change is needed, as https://github.com/woocommerce/woocommerce/pull/45533 indirectly updated the package to the proper one (as a transitive dependency).

See https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/bin/composer/phpcs/composer.lock: for `"name": "squizlabs/php_codesniffer",` we already have `"url": "https://github.com/PHPCSStandards/PHP_CodeSniffer.git",`.
