### ISSUE TITLE
Utilize Playwright Sharding

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#41488]
One of the neat features of Playwright is [the ability to shard tests into multiple processes](https://playwright.dev/docs/test-sharding). Although Playwright already supports the use of workers, by sharding tests, we can also better utilize multiple environments.

## Acceptance Criteria

* Playwright tests can be ran with the `--shard` parameter.
* E2E tests automatically select a different multisite path based on the shard given (if one is, otherwise assume single site)

**Comment by ObliviousHarmony** [comment]
From a cursory glance I think we can edit `playwright.config.js` and have it change the `BASE_URL` environment variable. We can detect the number of shards and change the url to something like `{domain}/shard{shard}`. We should create these sites as part of the test bootstrapping process.

**Comment by rrennick** [comment]
@lanej0 Could we call this one addressed?

**Comment by lanej0** [comment]
Yeah! We haven't done it universally in all workflows yet, but that's changing over time and the foundation is there.
