### ISSUE TITLE
Date Navigation arrow button doesn't work anymore in Analysed data

### ISSUE THREAD

**Issue by mattiadesiderio** [woothemes/woocommerce#41502]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With Wordpress 6.4.1 on Woocommerce, the selector allowing the setting of a custom date in the analysed data stopped working.

If one clicks on the arrows to change the month, the date selector is closed.

### Expected behavior

One should be able to change months and go forward or backward in months to change the period of analysed data.

### Actual behavior

The window for selecting the date range closes if a person clicks the arrows. In addition, there are UI problems

### Steps to reproduce

Analysed data > Panorama > Date range > Custom > Click an arrow to go back a month

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.12
PHP Post Max Size: 16 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: 7s1vOy_
Dimensione totale database: 4.86MB
Dimensione dati database: 3.15MB
Dimensione indice database: 1.71MB
7s1vOy_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_actions: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
7s1vOy_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_cfw_acr_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_comments: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
7s1vOy_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_options: Dati: 2.08MB + indice: 0.08MB + motore InnoDB
7s1vOy_postmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_posts: Dati: 0.05MB + indice: 0.06MB + motore InnoDB
7s1vOy_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
7s1vOy_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
7s1vOy_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
7s1vOy_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
7s1vOy_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 1
cfw_pickup_location: 1
customize_changeset: 1
page: 7
post: 2
product: 2
product_variation: 4
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 7.9.0 (aggiornamento alla versione 8.2.2 disponibile)
WP Rollback: by GiveWP.com – 1.7.3

### Inactive Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
CheckoutWC: by Objectiv – 8.2.17
Classic Widgets: by WordPress Contributors – 0.3
Fake Pay For WooCommerce: by Anthony Graddy – 1.1.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Sequential Order Numbers for WooCommerce: by WebToffee – 1.5.6

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /negozio/
Carrello: #8 - /carrello/
Pagamento: #9 - /pagamento/
Il mio account: #10 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Twenty Twenty-One
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-17 08:55:38 +00:00
Options: ✔
Notes: 56
Onboarding: skipped

### Action Scheduler ###

Completato: 36
Oldest: 2023-10-27 08:56:48 +0000
Newest: 2023-11-16 10:32:16 +0000

Operazione non riuscita: 1
Oldest: 2023-10-27 09:04:23 +0000
Newest: 2023-10-27 09:04:23 +0000

In attesa: 1
Oldest: 2023-11-16 13:44:30 +0000
Newest: 2023-11-16 13:44:30 +0000

### Status report information ###

Generated at: 2023-11-16 10:49:12 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattiadesiderio** [comment]
https://github.com/woocommerce/woocommerce/assets/28004802/b5071ee4-de6c-4473-8f5c-0a9d1fdc0bb5

Here is a video of the bug. Quite serious and urgent....

**Comment by sverleis** [comment]
User experiencing this on Woo.com - 7320419-zen
