### ISSUE TITLE
Remove Media Library from the "Add new" dropdown in Downloads

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#41501]
~~**On hold** until https://github.com/woocommerce/woocommerce/issues/41643 is done.~~

We currently allow users to pick a file from the Media Library to attach to a downloadable product in the new product form. There are disadvantages to that. For example, the types of files supported by the Media Library are limited and the user cannot choose a non-media file stored anywhere on the server. Moreover, all Media Library files are public, which defeats the purpose of a paid downloadable product.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-3301_391468

**Acceptance criteria**

- [ ] There's no Media Library option in the Add new dropdown in the Downloads section.

**Comment by pmcpinto** [comment]
@louwie17 is this still blocked?

**Comment by louwie17** [comment]
> @louwie17 is this still blocked?

No, not blocked anymore.
