### ISSUE TITLE
Local Pickup: simplify flow and improve guidance when the block-based local pickup feature is available

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#41534]
**Description:** the introduction of a new Local Pickup experience in the block-based checkout experience creates a fragmented experience, as users have two distinct ways of managing local pickup options. This change also affects the “Hide shipping costs until an address is entered” setting. 

We have a notice in the Local Pickup tab:

![local-pickup](https://github.com/woocommerce/woocommerce/assets/3380168/e3d365d8-d98c-408b-8418-61ceebd6ac55)

And a message in Shipping options:

<img width="1743" alt="Captura de ecrã 2023-11-17, às 06 51 35" src="https://github.com/woocommerce/woocommerce/assets/3380168/ebd5ba90-2e17-428c-8324-e17b6f450f8d">

However, we need more than this as we don't include anything in the Core Local Pickup flow. More info about this topic here: pevPIe-l8-p2.  Doing an entire workflow overhaul is out of scope, so we should implement low-effort changes to decrease ambiguity.

**Acceptance criteria:**
- [ ] Core local pickup flow: the easiest way to decrease ambiguity seems to be:
- If Checkout Block is enabled and there are no currently Core local pickup methods configured: hide the Core local pickup method and include the following message in the modal informing the user where it's possible to add local pickup options: Local pickup: set up pickup locations in the [Local pickup settings page] (link to: wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location)
- If Checkout Block is enabled and there are currently Core local pickup methods configured: include the following message in the modal informing the user that there's an alternative local pickup feature:  Explore a new enhanced delivery method that allows you to easily offer one or more pickup locations to your customers in the [Local pickup settings page] (link to: wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location)

- [x] Shipping options - calculations: change the copy to (Not available when using the [Local pickup options powered by the Checkout block](https://woo.com/document/woocommerce-blocks-local-pickup/))
- [x] Local pickup tab - notice copy: change the copy to By enabling Local Pickup with more valuable features for your store, it's recommended that you remove the legacy Local Pickup option from your [shipping zones](link to: wp-admin/admin.php?page=wc-settings&tab=shipping&section).

**Comment by elizaan36** [comment]
> If Checkout Block is enabled and there are no currently Core local pickup methods configured: hide the Core local pickup method and include a message in the modal informing the user where it's possible to add local pickup options.

I mentioned this on p2 already but I think this solution makes sense.

> What if users prefer to use the Core local pickup with the checkout block?

I don't see much possibility for this considering that the blocks version allows for skipping the address entry and more pickup locations.

**Comment by pmcpinto** [comment]
Thanks for your feedback.

> I don't see much possibility for this considering that the blocks version allows for skipping the address entry and more pickup locations.

Good point. We can always revisit this in case we receive requests from users.

**Comment by pmcpinto** [comment]
@elizaan36 can you also review the rest of the acceptance criteria?

**Comment by elizaan36** [comment]
Sure, questions so I can clarify these points.

> Shipping options: review copy, as many users don't know what blocks are. We should also evaluate if it makes sense to include link to documentation.

Is this referring to the merchant experience in the editor or the shopper experience? 

> Local pickup tab: review copy and explore if we should guide the user to migrate to this feature.

Is this referring to migrating existing users of the core local pickup feature?

**Comment by psealock** [comment]
Solved by pevPIe-l8-p2

**Comment by pmcpinto** [comment]
> Solved by pevPIe-l8-p2

I'm reopening this, as it hasn't been implemented yet.

**Comment by pmcpinto** [comment]
@elizaan36 here's the additional context:

> Shipping options: review copy, as many users don't know what blocks are. We should also evaluate if it makes sense to include link to documentation.
> Is this referring to the merchant experience in the editor or the shopper experience?

This refers to this copy in the Shipping Options setting, but it seems that it was removed: https://private-user-images.githubusercontent.com/3380168/283706776-ebd5ba90-2e17-428c-8324-e17b6f450f8d.png

> Is this referring to migrating existing users of the core local pickup feature?

Yes. Do you think this message at the top of the screen provides enough guidance? https://private-user-images.githubusercontent.com/3380168/283706669-e3d365d8-d98c-408b-8418-61ceebd6ac55.png

**Comment by elizaan36** [comment]
I'm not seeing either of those images :(
<img width="749" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5121465/fee6af40-ef92-4d3b-8d39-82dd21c1f1df">


> This refers to this copy in the Shipping Options setting, but it seems that it was removed

We should keep the Local pickup settings link from the editor. In terms of the references to blocks in the Local pickup settings, it's a good idea to remove references to based checkout. That could be confusing.

> Yes. Do you think this message at the top of the screen provides enough guidance?

The notice is a warning for users who have the legacy local pickup enabled, but I can see your point about making it more of a selling point vs warning. I'd leave it as-is mainly to get the point across that it could produce a subpar experience but I'm sure there's better copy that could be used.

**Comment by elizaan36** [comment]
Based on recent feedback, I think the notice copy could change to something like, 

> By enabling Local Pickup with more valuable features for your store, it's recommended that you remove the legacy Local Pickup option from your _shipping zones_.

**Comment by pmcpinto** [comment]
Acceptance criteria updated with the UI/copy changes. @elizaan36 can you do a final review of the AC?

**Comment by elizaan36** [comment]
Looks good to me!

**Comment by pmcpinto** [comment]
@nielslange do you plan to include the changes in WC 8.8?

**Comment by nielslange** [comment]
> @nielslange do you plan to include the changes in WC 8.8?

I do, @pmcpinto. I pushed some final changes earlier today, and I'm currently waiting for the CI pipeline to kick in. Once all tests passed, I'll ask @wavvves to do another review.

**Comment by pmcpinto** [comment]
@nielslange I've just tested the flow and it's almost perfect. Great work! There's only one thing that's not right.

> Shipping options - calculations: change the copy to (Not available when using the [Local pickup options powered by the Checkout block](https://woo.com/document/woocommerce-blocks-local-pickup/))

The objective of this item was just to replace the content inside the parentheses, but you replaced all the content. Sorry if I wasn't clear.

<img width="1027" alt="Captura de ecrã 2024-03-27, às 15 18 23" src="https://github.com/woocommerce/woocommerce/assets/3380168/08ca582f-aae5-4a0f-8f90-56cc48888c3b">

Can you fix it?

@elizaan36 we missed 1-2 details in the shipping zone empty state that could be improved:

![Annotation on 2024-03-27 at 15-28-13](https://github.com/woocommerce/woocommerce/assets/3380168/83be3c90-7f93-4202-9908-fe51ec6109fc)
 
Let me know if you think we should proceed with what I mentioned in the screenshot. Thanks

**Comment by nielslange** [comment]
> @nielslange I've just tested the flow and it's almost perfect. Great work! There's only one thing that's not right.
> 
> > Shipping options - calculations: change the copy to (Not available when using the [Local pickup options powered by the Checkout block](https://woo.com/document/woocommerce-blocks-local-pickup/))
> 
> The objective of this item was just to replace the content inside the parentheses, but you replaced all the content. Sorry if I wasn't clear.

Thanks for reaching out, @pmcpinto, and sorry for implementing it wrong. By _"change the copy to"_, I understood that the whole text should be replaced. I'll spin up an additional PR for that. As this change is purely related to wording and non-mission-critical for merchants, would you agree that it's safe if this additional PR lands in 8.9, or would you suggest creating a CFE so that it still can be shipped with 8.8? (Personally, I'm leaning towards 8.9 to avoid adding stress to the testing teams.)

**Comment by pmcpinto** [comment]
@nielslange no worries. It's ok to wait until 8.9. Thanks

**Comment by nielslange** [comment]
> @nielslange no worries. It's ok to wait until 8.9. Thanks

Thanks for confirming this, @pmcpinto. 🙌

**Comment by elizaan36** [comment]
> @elizaan36 we missed 1-2 details in the shipping zone empty state that could be improved
> Let me know if you think we should proceed with what I mentioned in the screenshot. Thanks

I just tested and looks good! I agree with what you mentioned in the screenshot.

The "Local zone..." text should be removed from shipping zones since it's not relevant to the user.

For the explainer text on the empty state screen, we could add, "Set pickup locations in the [local pickup settings]."

**Comment by nielslange** [comment]
Thanks for your reply, @elizaan36. 

> For the explainer text on the empty state screen, we could add, "Set pickup locations in the [local pickup settings]."

May I ask what you mean by empty state screen? I'm asking as the text, that is seen in https://github.com/woocommerce/woocommerce/issues/41534#issuecomment-2023083159, independent if the merchant has created shipping zones or not:

<table>
<tr>
<td valign="top">Without shipping zones:
<br><br>
<img width="1120" alt="Screenshot 2024-04-04 at 12 18 09" src="https://github.com/woocommerce/woocommerce/assets/3323310/52e8d50a-5075-4bb5-8f08-18d0ecf5e8f1">

</td>
<td valign="top">With shipping zones:
<br><br>
<img width="1120" alt="Screenshot 2024-04-04 at 12 17 43" src="https://github.com/woocommerce/woocommerce/assets/3323310/a4331215-4584-45ff-b93e-90b137c300ad">

</td>
</tr>
</table>

As for the text, adding "Set pickup locations in the [local pickup settings]." to the end of the existing text, might read a bit strange. Here's what I mean:

> A shipping zone consists of the region(s) you'd like to ship to and the shipping method(s) offered. A shopper can only be matched to one zone, and we'll use their shipping address to show them the methods available in their area. Set pickup locations in the [local pickup settings].

What are your thoughts on this slightly adjusted version:

> A shipping zone consists of the region(s) you'd like to ship to and the shipping method(s) offered. A shopper can only be matched to one zone, and we'll use their shipping address to show them the methods available in their area. To offer local pickup, configure your pickup locations in the [local pickup settings].

**Comment by elizaan36** [comment]
> May I ask what you mean by empty state screen? I'm asking as the text, that is seen in https://github.com/woocommerce/woocommerce/issues/41534#issuecomment-2023083159, independent if the merchant has created shipping zones or not

Yes, correct. It's the body text for the Shipping Zones screen. Not specific to the empty state.

> What are your thoughts on this slightly adjusted version

That sounds way better! Thanks @nielslange . I think it's a good fallback to provide the direct link to local pickup settings in case merchants don't see the tab.

**Comment by nielslange** [comment]
> Yes, correct. It's the body text for the Shipping Zones screen. Not specific to the empty state.

Thanks for confirming this, @elizaan36.

> That sounds way better! Thanks @nielslange . I think it's a good fallback to provide the direct link to local pickup settings in case merchants don't see the tab.

I agree that providing a direct link is very helpful. And thanks for confirming the improved text, I suggested. I'll handle these changes in #46209.
