### ISSUE TITLE
Update CYS based on DevDay announcements

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#41542]
Aims to answer the question of

> How would we have technically implemented this had the features OpenAI announced at their dev day been available from day one?

current implementation details: pcShBQ-1dV-p2

**Comment by tommyshellberg** [comment]
Just noting here that I've already shipped code to the generic text completion endpoint such that it accepts the `response_format` parameter which will help with forcing the response to be in valid JSON.
D128041-code

The other major update was the opening of the Assistants API which CYS could absolutely take advantage of, but, it requires a non-trivial amount of effort to switch over. I think the team working on CYS should be working with Applied AI to determine if BigSky can handle CYS or at the very least, how they could copy it into their own assistant and copy the implementation.

**Comment by peterfabian** [comment]
Probably no longer relevant, as the AI part has been shipped including the updates from the dev day.
