### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in includes/wc-cart-functions.php

### ISSUE THREAD

**Issue by mdbitz** [woothemes/woocommerce#41546]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Within the function [wc_get_chosen_shipping_method_for_package](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-cart-functions.php#L425) $chosen_method is being used to access an array key without first validating its type. It is possible for $chosen_method to be an array or other invalid type which will trigger the following php fatal error.

```
PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /wordpress/plugins/woocommerce/8.3.0/includes/wc-cart-functions.php:425
Stack trace:
#0 /wordpress/plugins/woocommerce/8.3.0/includes/class-wc-cart.php(1461): wc_get_chosen_shipping_method_for_package(0, Array)
#1 /wordpress/plugins/woocommerce/8.3.0/includes/class-wc-cart.php(1430): WC_Cart->get_chosen_shipping_methods(Array)
#2 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Debug/CartCalculatorListener.php(280): WC_Cart->calculate_shipping()
#3 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Debug/CartCalculatorListener.php(68): ADP\BaseVersion\Includes\Debug\CartCalculatorListener->fetchWcCartData(Object(WC_Cart), Object(WC_Session_Handler))
#4 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/CartProcessor/CartProcessor.php(326): ADP\BaseVersion\Includes\Debug\CartCalculatorListener->processStarted(Object(WC_Cart), Object(WC_Session_Handler))
#5 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Engine.php(192): ADP\BaseVersion\Includes\CartProcessor\CartProcessor->process(true)
#6 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Engine.php(164): ADP\BaseVersion\Includes\Engine->process(true)
#7 /wordpress/core/6.4.1/wp-includes/class-wp-hook.php(324): ADP\BaseVersion\Includes\Engine->firstTimeProcessCart('')
#8 /wordpress/core/6.4.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#9 /wordpress/core/6.4.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /wordpress/core/6.4.1/wp-settings.php(665): do_action('wp_loaded')
#11 /srv/htdocs/wp-config.php(76): require_once('/wordpress/core...')
#12 /wordpress/core/6.4.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#13 /wordpress/core/6.4.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#14 /wordpress/core/6.4.1/index.php(17): require('/wordpress/core...')
#15 {main}
  thrown in /wordpress/plugins/woocommerce/8.3.0/includes/wc-cart-functions.php on line 425
```

### Expected behavior

If the $chosen_method type is invalid it should use the default shipping method.

### Actual behavior

Fatal error is triggered

### Steps to reproduce

This can be tested by calling wc_get_chosen_shipping_method_for_package after setting the chosen_shpping_methods to an array.

WC()->session->set( 'chosen_shipping_methods', $chosen_methods );

### WordPress Environment

N/A -> issue is not validating the variable type before usage.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @mdbitz, thank you for reporting this. I opened PR https://github.com/woocommerce/woocommerce/pull/45233  introducing a check to make sure the variable type is valid to be used as an array key.

Can you please share more details on how you found the issue? A real use case would be great to evaluate impact and have some reliable testing steps. Thanks.

**Comment by wavvves** [comment]
Removing the wrongly added community contribution label.

**Comment by wavvves** [comment]
Closing this as not reproducible anymore, thanks @mdbitz for helping out!
