### ISSUE TITLE
Clicking subscription product in the product task redirects to the new editor when it shouldn't

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#41543]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Clicking subscription product in the product task redirects to the new editor when it shouldn't

https://github.com/woocommerce/woocommerce/assets/2240960/593479ef-e1b0-4459-812c-056c4545b9ef

**How to reproduce**

1. Create a new WooCommerce store and set the address to an American address ( Ex: California )
2. Install WooPayments and activate it ( you don't need to finish the set up ).
3. Go to **WooCommerce > Settings > Advanced > Features** and enable the new product editor.
4. Go to **WooCommerce > Home** and click the **Add products** in the task list
5. Click **View more product types** and click on **Subscription product**
6. Watch it redirect to the new editor ( it should redirect to the old editor ).

**Acceptance criteria**

- [ ] Clicking **Subscription product** should redirect to the old editor ( similar to what Grouped product does now ).

**Comment by pmcpinto** [comment]
@louwie17 I think it makes more sense to close this issue, as the Subs options will be removed: https://github.com/woocommerce/woocommerce/issues/41606

**Comment by louwie17** [comment]
Thanks @pmcpinto, yeah I will close this as this https://github.com/woocommerce/woocommerce/pull/41778 has been merged.
