### ISSUE TITLE
Scheduling issue

### ISSUE THREAD

**Issue by markhatwood** [woothemes/woocommerce#41569]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I schedule a 'sale' in my woocommerce shop. When the sale goes live, it doesn';t show the sale price (even though I've added it to the 'sale' field, but it still shows the normal price. As soon as I switch off the scheduling though, it shows the sale price.

Images available here:
https://we.tl/t-I7yUGSz78b

Mark

### Expected behavior

Should show sale price

### Actual behavior

Doesn't

### Steps to reproduce

list an item
put a sale price in
Schedule it
When live, it shows now scheduled sale price

### WordPress Environment

Shop

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dpash** [comment]
The issue is related to #39948. If I run `wc_scheduled_sales()` in wp-cli, it runs through all the products correctly, but the sale price is not saved. If I revert the change in that PR and run the function by hand, the sale price is correctly updated.

**Comment by markhatwood** [comment]
Hi DavidThanks for your email. I’m sorry to say it’s a bit gobbledygook for me. Can you give me more of a layman’s insight into fixing the issues?Best wishes and thanksMarkOn 22 Nov 2023, at 11:29, David Pashley ***@***.***> wrote:﻿
The issue is related to #39948. If I run wc_scheduled_sales() in wp-cli, it runs through all the products correctly, but the sale price is not saved. If I revert the change in that PR and run the function by hand, the sale price is correctly updated.

**Comment by webdados** [comment]
@dpash The problem and a possible solution is explained here: https://github.com/woocommerce/woocommerce/pull/39948#issuecomment-1822874419

**Comment by namiokuzono** [comment]
7346430-zen

**Comment by Babylon1999** [comment]
one more: https://wordpress.org/support/topic/issue-with-scheduling-sale-prices/#post-17241327

**Comment by ryanr14** [comment]
7397955-zen

**Comment by ncsramona** [comment]
Another 7391701-zen

**Comment by xue28** [comment]
Another issue here: https://wordpress.org/support/topic/sales-price-not-showing
Internal: 7389100-zen

**Comment by Babylon1999** [comment]
One more: https://wordpress.org/support/topic/schedule-prices-show-same-normal-price/#post-17300947

**Comment by beezwings** [comment]
Happening for me too.

**Comment by Brianmitchtay** [comment]
We're seeing this in the community FB group as well - https://www.facebook.com/groups/woocommunity/permalink/7739336982747320/

**Comment by darcie** [comment]
7541776-zen

**Comment by shohanhossainnab** [comment]
7556518-zen

**Comment by cardehngeh** [comment]
7563841 - zen
