### ISSUE TITLE
Product Description not showing

### ISSUE THREAD

**Issue by houdayec** [woothemes/woocommerce#41563]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using TheRetailer 3.7 theme and upgraded to latest version of WooCommerce this morning (8.3.0).

Since then, the product description is not showing anymore on any product page.

You can find an example following this [product link](https://font-station.com/fonts/godzilla-font-dinosaur-monster-movie-font/).

I can see by inspecting the source code and css that #tab-description has a style being applied :

`display: none;` taking over default `default: block;`

However, it does have the `current` class, meaning that it is the default tab that should be displayed.

<img width="518" alt="Screenshot 2023-11-18 at 19 23 33" src="https://github.com/woocommerce/woocommerce/assets/17120398/9ff7f8bb-6bb0-4a58-9bd2-80028e99c583">

I have tried many things, including manipulating CSS and loading JS through scripts and PHP functions but the style is being override.

Example of PHP:
`wc_enqueue_js("jQuery('#tab-description').removeAttr('style');");
wc_enqueue_js("jQuery('#tab-description').css('display', 'block');");`

### Expected behavior

Product Description being visible by default.

Expected result:

<img width="1169" alt="Screenshot 2023-11-18 at 19 28 09" src="https://github.com/woocommerce/woocommerce/assets/17120398/55f8f7da-7af1-4622-81b0-f35dbf3773f1">

### Actual behavior

Product Description not visible.

Current result:

<img width="1177" alt="Screenshot 2023-11-18 at 19 27 44" src="https://github.com/woocommerce/woocommerce/assets/17120398/7856abc8-150c-41c2-8ae8-a36eb2f53e87">

### Steps to reproduce

Read bug report.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://font-station.com
Site address (URL): https://font-station.com
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total Database Size: 38.61MB
Database Data Size: 26.66MB
Database Index Size: 11.95MB
wp_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 7.03MB + Index: 4.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.22MB + Index: 2.89MB + Engine InnoDB
wp_aioseo_cache: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_betterdocs_analytics: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_betterdocs_search_keyword: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_betterdocs_search_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fontsampler_fonts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fontsampler_sets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fontsampler_sets_x_fonts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fontsampler_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.45MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 1.33MB + Index: 0.25MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.09MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_realmedialibrary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_realmedialibrary_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_realmedialibrary_tmp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_userfeedback_surveys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_userfeedback_survey_responses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 165
custom_css: 4
customize_changeset: 21
jb_store_css: 10
mailpoet_page: 1
nav_menu_item: 12
oembed_cache: 8
page: 29
post: 1
product: 38
product_variation: 7
revision: 109
shop_order: 3
sp_wp_carousel: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpcode: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Admin Menu Editor: by Janis Elsts – 1.12
All-in-One WP Migration: by ServMask – 7.79
Code Snippets: by Code Snippets Pro – 3.6.2
Customer Reviews for WooCommerce: by CusRev – 5.38.1
Customizer Export/Import: by The Beaver Builder Team – 0.9.6
Duplicate Page: by mndpsingh287 – 4.5.3
Envato Market: by Envato – 2.0.10
FileBird Lite: by Ninja Team – 5.5.5
Google Listings and Ads: by WooCommerce – 2.5.11
Gutenberg: by Gutenberg Team – 17.0.2
WooCommerce HookMeUp: by Get Bowtied – 2.3
Hostinger: by Hostinger – 1.8.3
WPCode Lite: by WPCode – 2.1.5
Jetpack Boost: by Automattic - Jetpack Site Speed team – 2.2.0
Jetpack Protect: by Automattic - Jetpack Security team – 1.4.2
Jetpack: by Automattic – 12.8.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.12
LiteSpeed Cache: by LiteSpeed Technologies – 5.7.0.1
One Click Demo Import: by OCDI – 3.1.2
Performance Lab: by WordPress Performance Team – 2.7.0
Pinterest for WooCommerce: by WooCommerce – 1.3.14
Product Blocks for WooCommerce: by GetBowtied – 1.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Rank Math SEO: by Rank Math – 1.0.206
The Retailer Extender: by GetBowtied – 1.5.7
The Retailer Portfolio Addon: by GetBowtied – 1.2.7
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.6
WooPayments: by Automattic – 6.8.0
WooCommerce PayPal Payments: by WooCommerce – 2.4.1
WooCommerce Shipping & Tax: by WooCommerce – 2.4.0
WooCommerce: by Automattic – 8.3.0
WP 2FA - Two-factor authentication for WordPress: by Melapress – 2.5.0
WP Carousel: by ShapedPlugin LLC – 2.5.10

### Inactive Plugins (15) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
All in One SEO: by All in One SEO Team – 4.5.0
BetterDocs: by WPDeveloper – 3.0.0
Customer Reviews for WooCommerce: by Trustindex.io <support@trustindex.io> – 3.2.1
Folders: by Premio – 2.9.8
Fontsampler: by Underscore – 0.4.14
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.21.0
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet: by MailPoet – 4.36.0
OptinMonster: by OptinMonster Popup Builder Team – 2.15.0
Real Media Library (Free): by devowl.io – 4.21.17
UserFeedback Lite: by UserFeedback Team – 1.0.11
WooCommerce Custom Product Addons Free: by Acowebs – 3.0.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.11.0
WPForms Lite: by WPForms – 1.8.4.1

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #222 - /shop/
Cart: #223 - /cart/
Checkout: #224 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #467 - /terms-and-conditions/

### Theme ###

Name: The Retailer Child
Version: 3.7
Author URL: https://www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: The Retailer
Parent Theme Version: 3.7
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: theretailer/woocommerce/archive-product.php
theretailer/woocommerce/content-product.php
theretailer/woocommerce/content-single-product.php
theretailer-child/woocommerce/emails/customer-completed-order.php
theretailer-child/woocommerce/emails/email-downloads.php
theretailer-child/woocommerce/order/order-downloads.php
theretailer/woocommerce/single-product/related.php
theretailer/woocommerce/single-product/tabs/tabs.php
theretailer/woocommerce/single-product/up-sells.php
theretailer/woocommerce/single-product.php

### WooPayments ###

Version: 6.8.0
Connected to WPCOM: Yes
WPCOM Blog ID: 219980044
Account ID: acct_1NH8jjCBLoaxsYFd
Payment Gateway: Enabled
Test Mode: Disabled
UPE: Enabled (deferred_intent)
UPE Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-19 16:34:16 +00:00
Options: ✔
Notes: 113
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2023-11-09 17:24:37 +0000
Newest: 2023-11-09 17:24:37 +0000

Complete: 13,571
Oldest: 2023-10-18 19:37:16 +0100
Newest: 2023-11-18 18:23:24 +0000

Failed: 24
Oldest: 2023-06-09 18:48:21 +0100
Newest: 2023-11-16 21:08:24 +0000

Pending: 12
Oldest: 2023-11-18 18:33:24 +0000
Newest: 2023-11-21 23:37:00 +0000

### Status report information ###

Generated at: 2023-11-18 18:29:19 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Read bug report.

@houdayec We need the steps to reproduce this issue with a default theme and no other plugins active.
