### ISSUE TITLE
Investigate a disappearing product description

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#41572]
As evidenced in [this public review of the new product editing UX](https://youtu.be/YCUpws5CjwQ?si=wZSfIt9NmBiEuqYs&t=521), the body text (including the placeholders), the description sometimes doesn't get added when the user clicks `Done` in the description editor. Let's investigate possible causes and find a fix.

**Acceptance criteria**
- [ ] Product description is added always when the user clicks `Done` in the modal.

**Comment by louwie17** [comment]
I can't seem to reproduce this, lets close this, we can re-open again.
