### ISSUE TITLE
[Bug] Description body text inherits the admin theme's primary color

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#41571]
As evidenced in [this public review of the new product editing UX](https://youtu.be/YCUpws5CjwQ?si=kPO24UXgm2Rkf1ev&t=447), the body text (including the placeholders) inherits the primary color of the admin UI theme both in the editor and on the front-end. Let's try to fix that!

**Admin UI/form**
<img width="664" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/82b7136d-c83c-42df-b894-19a65cfe520f">

**Front-end**
<img width="358" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/707f41fb-517c-4b40-aecb-6bb20dc3855b">

**Acceptance criteria**
- [ ] Texts in the description editor inherit styles from the Global Styles/front-end. While creating a description, the user should always see what the shopper will see on the product page.
- [ ] If no Global Styles are set (or the site doesn't use a block theme), we use default colors.

**Comment by louwie17** [comment]
@jarekmorawski I am slightly confused with this bug, the placeholder colour shows up as the same colour in the page/post/site editor as well, so that seems to be expected ( or potentially a bug on WP end ).

**Comment by jarekmorawski** [comment]
Got it! I thought we were not respecting the Global Styles and the color in the example was randomly assigned from another element. I'll close this issue.
