### ISSUE TITLE
Misaligned emoji in the post-publish snackbar

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#41573]
The emoji shown in the snackbar message after a product is published/updated can be misaligned in some browsers.

<img width="505" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/9bdf2e35-09d5-4d1d-b6f6-f1211bd84fe2">

**Acceptance criteria**

- [ ] The emoji is displayed properly across all browsers.
- [ ] We apply the fix to all snackbar messages.

**Comment by mdperez86** [comment]
Fixed
