### ISSUE TITLE
Introduce a product type selection within the new experience

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#41586]
**Description:** currently, we don't offer a product type or treat selection. Instead, all implemented features are considered integral components of a "standard product" and seamlessly integrate into the product creation workflow: if the user wants a virtual product, it's enough to turn off shipping; if he wants a downloadable product, he just needs to upload a file to sell; if he needs a product with variations, he just needs to define the attributed and generate them. 
However, this approach doesn't work well for Core types such as external products, or types introduced by extensions. We should introduce a product type/treat selection for niche use cases.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-3359_349088

<img width="615" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/779e6e04-e79c-43f2-ad63-07a7d3be40f9">

**Acceptance criteria:**
- [x] We'll include a product type selector in General > Product details. This section should also include the product type that was selected. It displays the name of the currently selected product type, e.g., “This is x x x”. The product type name is always lowercase. AkVNGImLgSqCObTQ3idVn7-fi-3359_349088
- [x] The “Change product type” opens a dropdown menu based on [this WP component](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-dropdownmenu-v2-ariakit--with-submenu).
- [x] Product types compatible with the new UX are immediately visible. All others are nested in a `More` menu.
- [x] The currently selected product type is marked as such in the list. Clicking an item will change the product type (or display a confirmation modal for the unsupported types).
- [x] After the users change the product type, we display a snackbar that says `Product type changed`.
- [x] When users choose a product type that isn’t supported by the new UX, we show a confirmation modal. AkVNGImLgSqCObTQ3idVn7-fi-12060_198205
- [x] We automatically save all changes so the change from the new UX to the classic UX is smooth and no data is lost.
- [x] We display a loading state on the button while the user is being redirected to the classic UX.
- [x] All elements of this flow should be extended by 3PDs. Ideally, when a 3PD creates an extension that introduces a new product type (eg: Bookings) or a new product trait (eg: Gift Cards), it should automatically be displayed in the appropriate list (the default list for types compatible with the new UX, the `More` list for others).
- [x] If a product type doesn't have an icon, we show empty space to make sure its name and description (if it exists) is aligned with others).

**Event tracking:**
We should include Tracks events in all the user actions, to understand how users interact with this flow.

**Comment by pmcpinto** [comment]
@jarekmorawski can you update the issue with the link to the right Figma file? Do you think we should move forward with the modal in the first iteration? I'm not sure if we should include a preview in this iteration.

**Comment by pmcpinto** [comment]
@louwie17 this should be included in cycle 42 as it's a blocker to release affiliate and grouped products.

**Comment by jarekmorawski** [comment]
Here's the latest exploration where I accounted for the different features and extension support between the new and the classic experience. It also shows how we could handle switching between experiences when the user selects a product type unsupported by the new UX.

https://github.com/woocommerce/woocommerce/assets/79307566/72cc5276-1cf9-4fb2-8368-d5d5970c0de6

**Comment by pmcpinto** [comment]
Jarek, thanks for exploring this problem space. Displaying icons instead of an abstracted preview is a good option.

The "next-gen products" is an interesting idea, but I think we should avoid introducing a new concept that could confuse users, as the product created using the new form are "regular" products. Also, this can lead to a "paradox of choice" situation, considering that the Classic product types are also available in the new form.

**Comment by pmcpinto** [comment]
@louwie17 this issue should be included in the current cycle, as it can unblock access to the affiliate and grouped product types.

**Comment by mdperez86** [comment]
@jarekmorawski @louwie17 the description of the section block was moved from the bottom to the Popover/Tooltip right next to the block's title.

What are we going to do here, since now it looks like we are going to need both, the bottom description and the popover description? Any thoughts on this?

**Comment by mdperez86** [comment]
Also, the section description will be very custom since now it will need to know about a dropdown menu, meaning that is not going to be generic anymore. Should we need to create a brand new section block just to manage this feature? Or what else do you think we can do?

**Comment by mdperez86** [comment]
In this AC: `Product types compatible with the new UX are immediately visible` is being mentioned the term `product type compatibility` which I'm sure we are not managing at that way in our current implementation. How are we going to handle it? We don't have a place where the list of product types are related to their corresponding product editor compatibility or feature flag. Also how are we going to mark a new 3rd party product type as a product editor compatible type (or let them do it)?

cc: @pmcpinto @jarekmorawski @louwie17

**Comment by louwie17** [comment]
> How are we going to handle it? We don't have a place where the list of product types are related to their corresponding product editor compatibility or feature flag. Also how are we going to mark a new 3rd party product type as a product editor compatible type (or let them do it)?

We did have to create a list of supported product types that match to a product template.
We did know from that list if the product type is supported or not.
If a plugin registers a new product type and it doesn't match a product template ( as part of the new product form ), then we can safely assume its only supported in the legacy editor.

We don't need to mess around with specific logic around whether a plugin is compatible or not, and what types that plugin is registering. That is plugin specific.

> What are we going to do here, since now it looks like we are going to need both, the bottom description and the popover description? Any thoughts on this?

Yeah, we kinda shot ourselves in the foot by keeping the `description` name the same, we should of really altered that to `helpText` or something like that. Although I suppose that may be to UI binding.

> Also, the section description will be very custom since now it will need to know about a dropdown menu, meaning that is not going to be generic anymore. Should we need to create a brand new section block just to manage this feature? Or what else do you think we can do?

We could add slot fill support in the section block description area, so we can just slot fill this part in ( my preferred option ).
Another option is to just add this as a nested block, but that would mean we have to alter the styling of the section header a bit.

**Comment by pmcpinto** [comment]
> @jarekmorawski @louwie17 the description of the section block was moved from the bottom to the Popover/Tooltip right next to the block's title.
> What are we going to do here, since now it looks like we are going to need both, the bottom description and the popover description? Any thoughts on this?

Would it help if we moved the product type selection localization somewhere else?

**Comment by jarekmorawski** [comment]
I'd keep it like it is in the design. There are other cases where we may need both the clickable tooltip and the description. 3PDs may benefit from it, too.

**Comment by louwie17** [comment]
This may of been closed by accident, re-opening.
