### ISSUE TITLE
[CYS] Update copy and make sure more fonts are displayed

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41620]
Update the copy and display more font options if AI is temporarily unavailable.

| AI Unavailable | AI Available |
| ------ | ----- |
| <img width="221" alt="Screenshot 2023-12-06 at 11 51 55" src="https://github.com/woocommerce/woocommerce/assets/15730971/10c8d1d0-a52b-40f9-ad1a-5d2791034db7"> | <img width="324" alt="Screenshot 2023-11-21 at 21 32 51" src="https://github.com/woocommerce/woocommerce/assets/15730971/c072f459-1f34-4557-9305-3af66272e6ea"> |

## Identifying if AI is available

Make a GET request to `https://status.openai.com/api/v2/status.json` to check its status. If the returned indicator is set as "major" or "critical," we can consider AI is down. For more details about the response format for this API, please refer to the documentation on https://status.openai.com/api/v2#status 

## Design

Mrk6SERPZ4KrFHSjM0a8TK-fi-7675_11065

## Updated font pairings

* Inter | Inter
* Bodoni Moda | Overpass
* Libre Baskerville | DM Sans
* Montserrat | Arvo
* Rubik | Inter
* Playfair Display | Fira Sans

## Updated copy
`AI has selected a font pairing that's the best fit for your business. If you'd like to change them, select a new option below now, or later in Editor | Styles.`
->
`Select the pair of fonts that best suits your brand. The larger font will be used for headings, and the smaller for supporting content. You can change your font at any time in Editor | Styles.`

`Editor | Styles` links to `*wp-admin/site-editor.php?path=%2Fwp_global_styles`

**Comment by nefeline** [comment]
I am temporarily marking this issue as on hold until the proposed implementation is discussed with the engineering teams.

**Comment by nefeline** [comment]
The team agreed on the proposed implementation, so the `on hold` label was removed.

**Comment by nefeline** [comment]
@verofasulo can you please confirm if the 8 fonts we see on the "AI Unavailable" column are the ones we wanna have available as the default when AI is unavailable and also on core? Thanks!

**Comment by jarekmorawski** [comment]
The font pairings in the Figma file are slightly different:

* Inter | Inter
* Bodoni Moda | Overpass
* Libre Baskerville | DM Sans
* Montserrat | Arvo
* Rubik | Inter
* Playfair Display | Fira Sans

I updated the OP with a link and an updated screenshot.

**Comment by verofasulo** [comment]
Hey @nefeline, thanks for working on this!

Due to the latest changes to the Dotcom style library, do you mind making the following updates to the font pairings, please? 🙏

![image](https://github.com/woocommerce/woocommerce/assets/98944206/fa08dfac-9ca8-4a4b-a10e-b880bac82ffe)

1. 8 font pairings instead of 6
2. Font pairings:

- Inter | Inter
- Bodoni Moda | Overpass
- Albert Sans | Lora
- Montserrat | Arvo
- Rubik | Inter
- Newsreader | Newsreader
- Cormorant | Work Sans
- Raleway | Cormorant

All of the above are already included in the Dotcom style library. 

Let me know if you have any concerns, thank you 🙏

**Comment by nefeline** [comment]
> Due to the latest changes to the Dotcom style library, do you mind making the following updates to the font pairings, please?

My only concern is similar to what I've flagged regarding color palettes on https://github.com/woocommerce/woocommerce/issues/41619#issuecomment-1832715085 : if we don't have any licensing restrictions for using these fonts on open-source, we can certainly make those changes. Tagging @nerrad @ianstewart to confirm.

**Comment by nefeline** [comment]
@ianstewart confirmed both on p1701369301126359/1701368041.217139-slack-C053716F2H2 and on https://github.com/woocommerce/woocommerce/issues/41619#issuecomment-1834342640 that we can use fonts from WP.com without any problems (thanks!).

cc: @woocommerce/ghidorah
