### ISSUE TITLE
[CYS] Make sure patterns with default content are displayed in case AI is unavailable.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41623]
Make sure the user is still sent to the Assembler page with the default patterns content if AI is temporarily unavailable.

### 1. Identifying if AI is available

Make a GET request to `https://status.openai.com/api/v2/status.json` to check its status. If the returned indicator is set as "major" or "critical," we can consider AI is down. For more details about the response format for this API, please refer to the documentation on https://status.openai.com/api/v2#status 

### 2. On failure, reset all patterns content

If AI is down, make a DELETE request to the `ai/patterns` endpoint on Store API to ensure all patterns are reset to the default content on the client side whenever AI is unavailable. 

PS: the DELETE request for `ai/patterns` doesn't exist yet - it is planned to be implemented by the Store Editing team soon. Relevant issue is available here: https://github.com/woocommerce/woocommerce-blocks/issues/11873

### 3. On failure, direct the users to the Assembler. Create a modal as demonstrated in the following video

Video with the complete walkthrough:

https://github.com/woocommerce/woocommerce/assets/15730971/4e40b313-16bb-425a-a129-ba4b0fbe1c3d

Screenshots of the modals displayed in the video:

| Modal 1 | Modal 2 | Modal 3 |
| ------ | ----- | ----- |
| <img width="432" alt="Screenshot 2023-11-21 at 21 45 28" src="https://github.com/woocommerce/woocommerce/assets/15730971/1fb3bc3a-3f08-420a-a8c6-028916582ec6"> Mrk6SERPZ4KrFHSjM0a8TK-fi-7573_46973 | <img width="321" alt="Screenshot 2023-11-21 at 21 46 51" src="https://github.com/woocommerce/woocommerce/assets/15730971/680e5afe-90cd-488d-8bf1-8c5e6a5a7eb8"> Mrk6SERPZ4KrFHSjM0a8TK-fi-7573_112782 | <img width="308" alt="Screenshot 2023-11-21 at 21 47 06" src="https://github.com/woocommerce/woocommerce/assets/15730971/c592d2ad-f656-4a0d-80a0-0554b3961477"> Mrk6SERPZ4KrFHSjM0a8TK-fi-7573_112760 |

**Comment by nefeline** [comment]
I am temporarily marking this issue as on hold until the proposed implementation is discussed with the engineering teams.

**Comment by nefeline** [comment]
@moon0326 FYI, the endpoint with the DELETE request for patterns was already implemented by @gigitux on https://github.com/woocommerce/woocommerce-blocks/pull/11890 (planned to be released on Dec 4th).

Regarding your question on Slack ref. the presence of the “Which writing style do you prefer?” screen, it looks like the goal is to remove it completely when AI is not available (ref. p1700734595071889/1700660300.345799-slack-C053716F2H2 ) , even though it is displayed on the video shared with us over here: p1700155371628469/1700154883.533759-slack-C053716F2H2

Let's wait to get the confirmation from the design team regarding this scope and designs to make sure we are all on the same page before proceeding.

**Comment by jarekmorawski** [comment]
I reviewed the scope and added Figma links.

**Comment by verofasulo** [comment]
Thanks, @nefeline — and @jarekmorawski for reviewing!

> Screenshots of the modals displayed in the video:

Modals 2 and 3 are still the same. There's no difference between the two flows. 🙂
I'd love @lauroraa to review the copy of Modal 1 when she's back from afk to ensure it's aligned with the rest of the experience. 🙂 Thanks, Laura! cc @dlcallaway

**Comment by lauroraa** [comment]
Hi folks, I believe I've addressed this request ([see this P2](https://woomarketingstudio.wordpress.com/2023/11/15/studio-request-ux-copy-project-name-2/#comment-17866)) — the info shared there appears to be the same as here? It's getting a bit confusing having the same/similar requests in multiple places 😅

If I've misunderstood and something different is required here, please let me know. Thanks!
