### ISSUE TITLE
[CYS] Update the copy on the homepage

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41635]
Update the copy for the homepage on the CYS experience based on updated content provided by the design team:

| Before | After |
| ------ | ----- |
| <img width="578" alt="Screenshot 2023-11-22 at 12 25 40" src="https://github.com/woocommerce/woocommerce/assets/15730971/988ab620-089d-448d-82f5-f274857c3c21"> | <img width="618" alt="Screenshot 2023-11-22 at 12 25 57" src="https://github.com/woocommerce/woocommerce/assets/15730971/667e7100-881b-4db8-b5cf-d2cb1b96d892"> |

**Comment by nefeline** [comment]
@verofasulo can you please clarify here what will be the displayed text if, for some reason, the user didn't set a name for their store yet? Instead of "Welcome to {Store Name}", should we display just "Welcome" instead? Any other alternative proposal?

Also, can you please confirm that these are all the copy changes we have to make on the homepage? Wanna confirm I didn't miss anything while porting those over from Figma. Thanks in advance!

**Comment by jarekmorawski** [comment]
> Any other alternative proposal?

To be on the safe side, we could default to `Welcome to your store!` whenever the store name is unavailable.

> can you please confirm that these are all the copy changes we have to make on the homepage? Wanna confirm I didn't miss anything while porting those over from Figma. Thanks in advance!

Looks like everything is in place. We're only changing the subheading copy.

**Comment by verofasulo** [comment]
> To be on the safe side, we could default to Welcome to your store! whenever the store name is unavailable.

@nefeline, yes, that's correct 🙂 This is the current experience — tagging @adrianduffell for confirming. 

And this is the task copy:

Heading: Start customizing your store 
Subheading: Quickly create a beautiful looking store using our built-in store designer, or select a pre-built theme and customize it to fit your brand.
Cta: Start customizing

Let me know if you have any other questions 🙂

**Comment by adrianduffell** [comment]
> > To be on the safe side, we could default to Welcome to your store! whenever the store name is unavailable.

> This is the current experience — tagging @adrianduffell for confirming.

Yes, can confirm this is the current experience. Note the "welcome" copy will only display when no tasks have been viewed, or the task list is complete.

https://github.com/woocommerce/woocommerce/blob/0e0556ea76976310efdc41aef456f84c661c67bf/plugins/woocommerce-admin/client/task-lists/progress-title/default-progress-title.tsx#L48-L57
