### ISSUE TITLE
[CYS] Alternative short-term approach for updating the content in case AI is unavailable

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41638]
This is an optional task that should be worked on only if we verify that implementing the regular flow is too time-consuming and we won't be able to finish it before Dec 6th.

### 1. Identifying if AI is available
Make a GET request to https://status.openai.com/api/v2/status.json to check its status. If the returned indicator is set as "major" or "critical," we can consider AI is down. For more details about the response format for this API, please refer to the documentation on https://status.openai.com/api/v2#status

### 2. In case AI is down, instead of directing the user to the Pattern Assembler, direct them to one of the following pages instead:

<img width="691" alt="Screenshot 2023-11-22 at 14 03 05" src="https://github.com/woocommerce/woocommerce/assets/15730971/7104bca9-14c2-46c6-bd79-b0224784ab55">

<img width="699" alt="Screenshot 2023-11-22 at 14 02 38" src="https://github.com/woocommerce/woocommerce/assets/15730971/3eb92c09-d1cd-40fb-b506-c0c36a6994d4">

**Comment by nefeline** [comment]
@verofasulo can you please confirm which of the two designs should be used in this case? Both of them were listed on Figma so I'm not sure what's the preference. Thanks!

**Comment by adrianduffell** [comment]
Closing this out -- the regular flow was implemented.
