### ISSUE TITLE
[CYS] Temporarily remove the survey button

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41637]
Temporarily remove the survey button if the AI service is unavailable: we still wanna keep the button in place if AI is up and running. 

Not part of this issue, but FYI: later on, the questionnaire will be updated so it is expected the content in the modal will conditionally change depending on whether the AI feature is enabled.

Button to be removed:

<img width="540" alt="Screenshot 2023-11-22 at 12 44 52" src="https://github.com/woocommerce/woocommerce/assets/15730971/8f4a5c71-5b2f-44ea-b4fc-baa07c501ad7">

**Comment by nefeline** [comment]
@verofasulo can you please take a quick look here and confirm this is the button we want to conditionally remove if AI is unavailable? Thanks.

**Comment by jarekmorawski** [comment]
I confirm. This is the result we want to achieve:

<img width="806" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/9edc9579-06c8-4997-9a30-3026713f62c2">

**Comment by verofasulo** [comment]
Thanks, @jarekmorawski! @nefeline yes, that's correct. 🙂
