### ISSUE TITLE
Currency symbol overlap with product value on cart page ( on 100% screen size )

### ISSUE THREAD

**Issue by ashish-wps** [woothemes/woocommerce#41658]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 Description - Currency symbol overlap with product value on cart page on 100% screen size

### Expected behavior

It's should in proper way Ex. -  $16

### Actual behavior

Currency symbol overlap the value on cart page in on 100% screen size

### Steps to reproduce

1. Add a product
2. Go to the cart page
3. Verify the result.

### WordPress Environment

[scrnli_23_11_2023_13-14-33.webm](https://github.com/woocommerce/woocommerce/assets/105413021/3397b115-037b-47c3-8132-bf4b4c3bc0f8)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@ashish-wps You steps to reproduce do not include which default theme to use, which cart to set up, or describe a test product to use.
