### ISSUE TITLE
Add to card button not display on product single page

### ISSUE THREAD

**Issue by EkachaiWongsiri** [woothemes/woocommerce#41667]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 WooCommerce upgrade (from version 8.3.0 to 8.3.1) my add to cart button dose not display on the product single page

### Expected behavior

need the button "add to cart" 

### Actual behavior

No "add to cart" button display

### Steps to reproduce

![Screenshot 2023-11-24 112044](https://github.com/woocommerce/woocommerce/assets/87170914/81678beb-e87a-46d4-98dc-175d62829221)

### WordPress Environment

Just visit any product page you will see the problem

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@EkachaiWongsiri Thanks for reporting the issue. 

Several developers tried to reproduce this and were not able to. Could you provide the steps to reproduce this issue in a dev or new install with only WooCommerce active and a default theme?
