### ISSUE TITLE
woocommerce_scheduled_sales cron runs one 1 hour too early

### ISSUE THREAD

**Issue by mikkelaveo** [woothemes/woocommerce#41672]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This refers to an ongoing problem from years back. But it seems still to be an issue in some cases.

We have multiple WooCommerce webshops where the administrator sets sale price on the products with a schedule. The sale price doesn't get correctly updated on the date which it should. It seems that it runs on the cron event "woocommerce_scheduled_sales" which is triggered once a day. But at the moment in Denmark (GMT+1) we are having "winter time" which means that we from Sunday, Oct 29, 2023 – Sunday, Mar 31, 2024 have set the clock 1 hour ahead than in the "summer time". I don't know if the issue has anything to do with this.. But the event "woocommerce_scheduled_sales" at the moment is only running once a day at 23:00 (11:00 PM) which mean that it is 23 hours behind each day on updating the sale price after the schedule. It should be set to run in the beginning of each day at 00:00 (00:00 AM).

Are you aware of the problem and do you have a solution?

The only solution I have found at the moment is to change it with a plugin like: WP Crontrol or with some PHP code.

### Expected behavior

The sale prices cron event ("woocommerce_scheduled_sales") should be running at the start of the day at 00:00 (00:00 AM) and not at 23:00 (11:00 PM).

### Actual behavior

The sale prices cron event ("woocommerce_scheduled_sales") should be running at the start of the day at 00:00 (00:00 AM) and not at 23:00 (11:00 PM).

### Steps to reproduce

1. Go to a WooCommerce product and set a sales price with a schedule
2. Check if the sale price gets updated correct at the next day

### WordPress Environment

It's a general problem with our WooCommerce installations on the newest versions and with the Danish timezone (København).-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mikkelaveo** [comment]
Hi @rrennick,

Why is this not a issue/bug? The problem appears on every WooCommerce webshop which has a Danish timezone (haven't testet with others) and if we use the product sale schedule it's useless at the moment because the cronjob only updates the prices at 23:00 (11:00 PM)? :)

**Comment by rrennick** [comment]
> This refers to an ongoing problem from years back.
> every WooCommerce webshop which has a Danish timezone

@mikkelaveo For clarification, you are referring to WC shops that you administer vs all the WC shops with a Danish TZ. The text time zones are aliases (ie. Copenhagen is UTC+1:00). The issue you are describing could be caused by server configuration or custom code. If there were an ongoing problem with UTC+1:00, our support team would be getting reports from other WC merchants in that TZ.

Here's what I tested (and works as expected):
```
# wp shell
wp> get_option( 'timezone_string' );
=> string(17) "Europe/Copenhagen"
wp> $product = get_product(5714);
// snip
wp> $product->set_date_on_sale_from( '2023-12-01' );
=> NULL
wp> $product->get_date_on_sale_from();
=> object(WC_DateTime)#24956 (4) {
  ["utc_offset":protected]=>
  int(0)
  ["date"]=>
  string(26) "2023-12-01 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(17) "Europe/Copenhagen"
}
```

**Comment by mikkelaveo** [comment]
@rrennick Ok thanks. Maybe it has something to with our server setup then, we will try debugging this from our end so.

Thanks for getting back to me :)

**Comment by mikkelaveo** [comment]
@rrennick Hi again.

The timezone for the servers we are using is "UTC". But in WordPress settings we have set the timezone to "Copenhagen", shouldn't your cronjob use the WordPress settings timezone instead of the servers?

**Comment by rrennick** [comment]
> shouldn't your cronjob use the WordPress settings timezone instead of the servers?

It does. In your description you said it was 23 hours off, not 1 hour off. If WP cron was running on UTC it would be 1 hour off.

**Comment by mikkelaveo** [comment]
Hi Rrennick,
The cronjob gets executed at 23:00 // 11 PM. The copenhagen timezone is UTC+1, so if it was using the Copenhagen timezone it should use 00:00 / 00 AM so from my point of view it is just 1 hour behind.
But as i can see from your answers it seems to be some kind of server problem from our side...

**Comment by rrennick** [comment]
> The copenhagen timezone is UTC+1, so if it was using the Copenhagen timezone it should use 00:00 / 00 AM so from my point of view it is just 1 hour behind.

Sorry, I misunderstood. I thought you meant it was running at 11PM the day of vs the day before. You can test to see if WP Cron is running an hour off by scheduling a test post to publish in 1 hour + 15 minutes. If it publishes in 15 minutes the WP cron is running an hour off.
