### ISSUE TITLE
Create a product category Api doesn't return value but is created successfully!

### ISSUE THREAD

**Issue by senatormas** [woothemes/woocommerce#41688]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

curl --location 'https://XXXX.com/wp-json/wc/v3/products/categories' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic Y2tfOTdkZTVkODdjZjE5NDU4YzRlODhlNzQ4M2ViOGRkZmMyZWE2MDY5ZDpjc183MWQxMWY2YjA2ZDllNmNmZTZkMTJmOTBlNGJlNThhMDY4MmY1MTEx' \
--data '{
    "name": "test",
    "image": {
        "src": ""
    }
}'

ran this cat is created successfully but nothing is returned ?!

### Expected behavior

expect returning id at least!

### Actual behavior

empty string is returned!

### Steps to reproduce

curl such a req:
curl --location 'https://XXXX.com/wp-json/wc/v3/products/categories' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic Y2tfOTdkZTVkODdjZjE5NDU4YzRlODhlNzQ4M2ViOGRkZmMyZWE2MDY5ZDpjc183MWQxMWY2YjA2ZDllNmNmZTZkMTJmOTBlNGJlNThhMDY4MmY1MTEx' \
--data '{
    "name": "test",
    "image": {
        "src": ""
    }
}'

### WordPress Environment

Latest version: 8.3.1  is being used
PHP 7.4
Wordpress: 6.4.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@senatormas We don't provide support through the Github repository so I'll close this as a support request. However, the first thing I see is that your request is a GET instead of a POST. If you are still having issues, I suggest the [community Slack](https://woo.com/community-slack/).
