### ISSUE TITLE
[CYS] Switch the default theme from Twenty-twenty three to Twenty-twenty four

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41697]
As part of the scope for releasing the CYS flow on core, let's switch the default theme in the Assembler from TT3 to [TT4](https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/).

While making this change, please make sure that:

- All patterns are fully functional, and no changes in design should be visible.
- The user should still be able to change colors and fonts for all patterns.

**Comment by nefeline** [comment]
For reference, this is the PR that introduced the switch to the TT3 theme in the Assembler: https://github.com/woocommerce/woocommerce/pull/40486/files

It might be as simple as updating the slug in this constant: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L443

**Comment by albarin** [comment]
@verofasulo these are the 3 homepages after switching the assembler theme to TT4, could you check the videos and confirm if it's ok or if we need to make some more adjustments to patterns? Thanks!

### Homepage 1
https://github.com/woocommerce/woocommerce/assets/186112/d2ea4824-d572-4866-9c93-6c6d6d91ec0f

### Homepage 2
https://github.com/woocommerce/woocommerce/assets/186112/df68d400-4f25-4ed9-8b5c-137b946c3c04

### Homepage 3
https://github.com/woocommerce/woocommerce/assets/186112/7c71b4e2-e92b-4079-b34c-f53051051b94

**Comment by jarekmorawski** [comment]
Thanks for sharing, @albarin! Most of them look good. I have some thoughts:

1. The left padding on the hero pattern (the one right below the header) should match the width of the new arrivals pattern so that the heading and the button are positioned in the same vertical line as the first product image.
2. Ideally, the testimonials pattern would have the same width as the product grid patterns.
3. Can we add the same space between the new arrival pattern's title and the products as between the products and the Shop all button?
4. Same for the "Discover the freshest oranges!" pattern. I'd also make the title shouldn't be centered to maintain consistency.
5. In the footer, the `Powered by WordPress and WooCommerce` bit should have a smaller font. Let's use the one we use for the product titles in the 3-product grid pattern.
6. The subheadings in the second part of the chessboard pattern ("Perfectly ripe and juicy") should follow the theme's font and have a heading styling (H3, maybe?).
7. The icons in the social media pattern are misaligned. They should always align to the right edge of the container, but it seems that they currently extend beyond it.

**Comment by albarin** [comment]
Hey @jarekmorawski! I'm replying to your feedback👇 I've left a question on point 4. 

> 1. The left padding on the hero pattern (the one right below the header) should match the width of the new arrivals pattern so that the heading and the button are positioned in the same vertical line as the first product image.

I don't think we can do that 🤔 The position of the first product depends on the screen size, and the left padding on the hero pattern has to be fixed (it's a limitation in GB, we cannot set different padding depending on the screen size).
![CleanShot 2023-12-04 at 11 36 25](https://github.com/woocommerce/woocommerce/assets/186112/2bb75478-050b-44f7-b195-51a207fffd48)

> 2. Ideally, the testimonials pattern would have the same width as the product grid patterns.

That is weird, both patterns have the same width in code and when inserted on a page they have the same width, but not in the assembler 🤷‍♀️ I'm opening an issue to investigate it further: https://github.com/woocommerce/woocommerce-blocks/issues/12025

> 3. Can we add the same space between the new arrival pattern's title and the products as between the products and the Shop all button?

That makes sense, created this issue to fix it: https://github.com/woocommerce/woocommerce-blocks/issues/12026

> 4. Same for the "Discover the freshest oranges!" pattern. I'd also make the title shouldn't be centered to maintain consistency.

It doesn't have a title anymore. @jarekmorawski what do you mean? Should we align left product titles & prices??

> 5. In the footer, the Powered by WordPress and WooCommerce bit should have a smaller font. Let's use the one we use for the product titles in the 3-product grid pattern.

We decided not to hard-code any text sizes in these patterns so they are wireframed and work with any theme (for more context: https://github.com/woocommerce/woocommerce-blocks/issues/11276#issuecomment-1766175865)

> 6. The subheadings in the second part of the chessboard pattern ("Perfectly ripe and juicy") should follow the theme's font and have a heading styling (H3, maybe?).

This was changed from an h4 to an h6 in https://github.com/woocommerce/woocommerce-blocks/pull/11545. Below you can find some tests I have done with h4, h5, and h6 in TT3 and TT4. Which heading size would you prefer?

| | TT3 | TT4 |
|--------|--------|--------|
| H4 | <img width="759" alt="h4-tt3" src="https://github.com/woocommerce/woocommerce/assets/186112/59d875e5-fd18-4617-b583-49867185fbec">| <img width="698" alt="h4-tt4" src="https://github.com/woocommerce/woocommerce/assets/186112/f74e635e-d527-4bbe-bf38-4bb2f92b48b7"> |
| H5 | <img width="706" alt="h5-tt3" src="https://github.com/woocommerce/woocommerce/assets/186112/f90dd4bc-a3bb-4418-8ceb-2130aa2cd27f"> | <img width="681" alt="h5-tt4" src="https://github.com/woocommerce/woocommerce/assets/186112/d23e7c54-3fb2-4792-8eb3-5a1493c10120"> |
| H6 | <img width="695" alt="h6-tt3" src="https://github.com/woocommerce/woocommerce/assets/186112/eed094c6-742b-4bc9-b7cf-62d0569bfb8b"> | <img width="659" alt="h6-tt4" src="https://github.com/woocommerce/woocommerce/assets/186112/48bbc253-ca1f-449e-96f9-333c0afbd554"> |

> 7. The icons in the social media pattern are misaligned. They should always align to the right edge of the container, but it seems that they currently extend beyond it.

Issue to fix it: https://github.com/woocommerce/woocommerce-blocks/issues/12027
