### ISSUE TITLE
[Woo AI] Add prompt testing

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#41718]
Based on pf8sIm-9O-p2, it seems [Promptfoo](https://github.com/promptfoo/promptfoo) is a decent tool for testing the prompts in our code. 

**Extracting the prompts**
Since Promptfoo only accepts the prompts as a text file, we need a way to extract the prompts from the code and store them in text files to pass into Promptfoo as input. Another way would be to use the [custom scripts](https://www.promptfoo.dev/docs/providers/custom-script/) feature and define scripts that will run our prompts and output the results.

**Defining tests and assertions**
Define [tests and assertions](https://www.promptfoo.dev/docs/configuration/expected-outputs/) for the outputs of each feature (and prompt). We could use the following directory structure to define tests for each feature:
- tests
  - prompts
      -  feature1
          -  prompts.txt
          -  promptfooconfig.yaml
      -  feature2
          -  prompts.txt
          -  promptfooconfig.yaml

**Set up automated tests on GitHub**
Set up automated tests on our repo using a [GitHub Action](https://www.promptfoo.dev/docs/integrations/github-action/#using-the-github-action) to run the tests for every release. Might be a good idea to run on every PR as well if the PR changes a prompt.

**Comment by nima-karimi** [comment]
This PR would be a good use case for implementing prompt testing: https://github.com/woocommerce/woocommerce/pull/39200

**Comment by peterfabian** [comment]
Closing down as the plugin is being sunset.
