### ISSUE TITLE
[DOC-BUG] Docs page for woocommerce conditional tags has disappeared

### ISSUE THREAD

**Issue by nickihastings** [woothemes/woocommerce#41748]
## Link to the Page/Section

https://woo.com/document/conditional-tags/

## Description of the Suggestion

I've had this page bookmarked for an age, now it takes me to git rather than to the docs site. Searching in google for 'woocommerce conditional tags' also has the same link which also takes me to git. Pretty sure this is incorrect.

## Reason for the Suggestion
Needs fixing, I guess something has been updated in the docs and there's no redirect in place.

**Comment by rrennick** [comment]
@nickihastings Thanks for reporting the issue. The docments on woo.com are not managed from this repo. Could you [contact support](https://woo.com/my-account/contact-support/)?
