### ISSUE TITLE
Some important Hooks are not working in Latest Version WooCommerce

### ISSUE THREAD

**Issue by bdgreenweb** [woothemes/woocommerce#41763]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Dear WooCommerce Team,
Unfortunately, the following hooks have stopped working in the latest WooCommerce. I have tried in several hosting, including InstaWP, but unfortunately, these blocks do not work in any of the hosting. But if I setup the old version of WooCommerce, these hooks start working again. If i previously use woocommerce and update to new version this problem not happen. This problem happen with the new default checkout theme
woocommerce_checkout_process
woocommerce_review_order_after_submit
woocommerce_pay_order_before_submit
woocommerce_after_checkout_validation

Tested Version:
WooCommerce version: |   | 8.2.0
WooCommerce REST API package: |   | 8.2.0 
WooCommerce Blocks package: |   | 11.1.2 
Action Scheduler package: |   | 3.6.3

I have put these hooks in theme functions and inside a plugin. But nothing worked. 

### Expected behavior

Hooks must trigger after/while placing a new order.

### Actual behavior

Nothing happened. I have tried to echo, mail, logs and dump nothing. just ignore these hooks. 

### Steps to reproduce

Install wordpress latest version
Install woocommerce version
put action hooks inside functions file or in a plugin.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://cute-chimpanzee-wgjyc.instawp.xyz
Site address (URL): https://cute-chimpanzee-wgjyc.instawp.xyz
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
PHP Version: 8.0.29
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.2-MariaDB-1:10.11.2+maria~ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: iwpa593_
Total Database Size: 2.80MB
Database Data Size: 1.13MB
Database Index Size: 1.67MB
iwpa593_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iwpa593_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iwpa593_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwpa593_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwpa593_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
iwpa593_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
iwpa593_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
iwpa593_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
iwpa593_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iwpa593_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwpa593_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwpa593_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
iwpa593_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iwpa593_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iwpa593_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iwpa593_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iwpa593_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
iwpa593_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwpa593_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwpa593_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/gunavosose2905/web/cute-chimpanzee-wgjyc.instawp.xyz/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/gunavosose2905/web/cute-chimpanzee-wgjyc.instawp.xyz/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/gunavosose2905/web/cute-chimpanzee-wgjyc.instawp.xyz/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-29 18:06:55 +00:00
Options: ✔
Notes: 61
Onboarding: -

### Action Scheduler ###

Pending: 2
Oldest: 2023-11-28 18:07:21 +0000
Newest: 2023-11-28 18:08:20 +0000

### Status report information ###

Generated at: 2023-11-28 18:07:43 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ron273** [comment]
I have the same problem. I am writing a plugin that calculates the number of items in the cart. If the number of items is not a multiple of X, I use a hook above the cart table to show a notice and I remove the checkout button until the conditions match. That does not work any more.
I have recently learned that this has to do with the fact that since WC8.3 the default for cart and checkout page is using blocks and not the old shortcode. The hooks on cart and checkout page are no longer available. 
Developer documentation is seriously lacking, so I am not able to show notices on the cart and checkout page, or manipulate  elements using add_action or remove_action. For now I am reverting back to the old cart an checkout page using shortcode, but obviously that is a temporary solution. Any pointer from the dev team to solve this issue would be greatly appreciated.

https://wptavern.com/woocommerce-8-3-makes-cart-checkout-and-order-confirmation-blocks-default-on-new-installations?fbclid=IwAR1HN6pRMSP83dOy6Unk4xHGwiAzVInn-e3ONim7y0fXGFY48XCxtXCwN2Q

**Comment by bdgreenweb** [comment]
> I have the same problem. I am writing a plugin that calculates the number of items in the cart. If the number of items is not a multiple of X, I use a hook above the cart table to show a notice and I remove the checkout button until the conditions match. That does not work any more. I have recently learned that this has to do with the fact that since WC8.3 the default for cart and checkout page is using blocks and not the old shortcode. The hooks on cart and checkout page are no longer available. Developer documentation is seriously lacking, so I am not able to show notices on the cart and checkout page, or manipulate elements using add_action or remove_action. For now I am reverting back to the old cart an checkout page using shortcode, but obviously that is a temporary solution. Any pointer from the dev team to solve this issue would be greatly appreciated.
> 
> https://wptavern.com/woocommerce-8-3-makes-cart-checkout-and-order-confirmation-blocks-default-on-new-installations?fbclid=IwAR1HN6pRMSP83dOy6Unk4xHGwiAzVInn-e3ONim7y0fXGFY48XCxtXCwN2Q

Yes. You're right. I just discovered it yesterday. My plugin also depends on WooCommerce hooks and suddenly they have stopped working on the new version. 
After reverting back to old checkout page using shortcode everything started working again.

**Comment by tarhi-saad** [comment]
Thank you, @ron273, @bdgreenweb, for reaching out! 🙌 We have several hooks that extensions can use; some are new, and some are hooks that already exist in WooCommerce core:

- [Filters](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md)
- [Actions](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md)

We also have a list of hooks that have been migrated from WooCommerce Core but have been renamed:

- [Migrated Legacy Hooks](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/migrated-hooks.md)

**Comment by ron273** [comment]
@tarhi-saad I've seen the filter, actions and migrated hooks. There are however no hooks available, new of migrated, that will allow you to add content at specific locations (for instance a notice above the cart items) on the cart page or checkout page.  Perhaps this needs to be done a different way in the blocks structure, but the documentation on that is seriously lacking. I would like to see a code example on showing a notice above the cart, based on some conditional logic.

**Comment by bdgreenweb** [comment]
I need a hook equivalent to woocommerce_review_order_after_submit

I want to prevent checkout after submitting the form and initiate a otp verification before placing order. 

I dont see any option or equivalent hooks available in new version.
