### ISSUE TITLE
[Enhancement]: reopen a previous enhancement please https://github.com/woocommerce/woocommerce/issues/36401

### ISSUE THREAD

**Issue by radialmonster** [woothemes/woocommerce#41767]
### Describe the solution you'd like

I opened an enhancement issue before, and it was closed.  i just added new info to it, can it be reopened please thank you
https://github.com/woocommerce/woocommerce/issues/36401

### Describe alternatives you've considered

opening a new issue, but seems it would be best to keep info in one issue

**Comment by jorgeatorres** [comment]
I've reopened the original instance of your issue @radialmonster. Someone from the team should be taking a look soon.
