### ISSUE TITLE
Remove hardcoded colors from the product tabs in the single product page when using a block theme

### ISSUE THREAD

**Issue by xristos3490** [woothemes/woocommerce#41775]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Currently, the product tabs use hardcoded gray colors, which creates inconsistencies with the store's color palette.

Screenshot on TT4:
<img width="1393" alt="Screenshot 2023-11-29 at 2 07 39 PM" src="https://github.com/woocommerce/woocommerce/assets/1105590/9eb586a3-f5bf-4a3d-ab6a-51cf1e7dba38">

### Expected behavior

The purpose of this issue is to improve the default setting of the tab based on the foreground text color and the background color of the store. The design can remain the same, but the foreground color will be used for borders, and the background color will be used for the tab's background. This change will allow users to interact with the colors and change the color palette as per their preference. 

The CSS priorities should be maintained while implementing the fixes to ensure that existing theme overrides continue to work as intended.

Here's how a store might look like after these changes (taken from a WX site): 

<img width="1049" alt="Screenshot 2023-11-29 at 2 02 24 PM" src="https://github.com/woocommerce/woocommerce/assets/1105590/cf14c515-1271-4bea-bc24-7a817bbd2e77">

### Actual behavior

Using hardcoded values can result in colors that appear "muddy" in certain situations.

### Steps to reproduce

1. Use a store with a block theme.
2. Visit a product's single page.
3. Notice the tabs. 

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
We could probably keep the hardcoded colors for classic themes?

**Comment by xristos3490** [comment]
Yes! This modification is intended only to apply to block themes. To avoid changing the CSS priorities and still target only block themes we can use the `:where()` operator (e.g., https://github.com/woocommerce/woocommerce/blob/b6b1f61807917cb23cdbc46d02b2162da3978671/plugins/woocommerce/client/legacy/css/woocommerce.scss#L1730)
