### ISSUE TITLE
[Enhancement]: new phone field in "Ship to a different address?"

### ISSUE THREAD

**Issue by rwkyyy** [woothemes/woocommerce#41779]
### Describe the solution you'd like

An additional phone number for shipping to a different address would be much appreciated for gifting situations / similar.

### Describe alternatives you've considered

inserting field in checkout via functions + updating integration with shipping provider (3rd party, not needed).

### Additional context

I have multiple scenarios with **orders as gift**, the user enters their billing address and wants to **ship the order to a different address**, the problem is that natively there is **no way** for them to **provide a phone number** in the shipping details; this means that (in most cases) if you create a tracking number the shipping couriers use the billing phone number from the order.
Hoping this will change in the future, if this gets approved and updated.

L.E. removed mandatory proposal since sometimes the user wants the order delivered to his office, not home.

**Comment by tarhi-saad** [comment]
Thanks, @rwkyyy, for reaching out! 🙌 We won't be incorporating any new functionalities into the shortcode Checkout. Instead, you can utilize the default Checkout Block, which is our standard checkout option. It already has this feature. you can input distinct numbers for both the shipping and billing addresses.

**Comment by rrennick** [comment]
> We won't be incorporating any new functionalities into the shortcode Checkout. Instead, you can utilize the default Checkout Block, which is our standard checkout option. It already has this feature. you can input distinct numbers for both the shipping and billing addresses.

cc @rwkyyy

**Comment by rwkyyy** [comment]
@rrennick thx for the ping, but I already read it. 
In conclusion: migrate to blocks or do it yourself.
