### ISSUE TITLE
Update Attributes tooltip copy

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#41786]
**Description:** The copy displayed in the Attributes tooltip needs to be more accurate, as customers can't use custom attributes to filter or find products. This is only possible with global attributes.

<img width="743" alt="Captura de ecrã 2023-11-29, às 11 11 48" src="https://github.com/woocommerce/woocommerce/assets/3380168/ce89c979-3150-4b0d-b8c1-467495cc1cab">

We should include this in 8.5 (code freeze: Dec 20).

**Acceptance criteria:**

- [ ]  Change the copy tooltip to align it with the advantages of custom attributes and establish clear expectations.

**Comment by pmcpinto** [comment]
cc @jarekmorawski @lauroraa for copy feedback. Thanks.

**Comment by louwie17** [comment]
> cc @jarekmorawski @lauroraa for copy feedback. Thanks.

Please move the status over to `Todo` once the copy has been checked.

**Comment by pmcpinto** [comment]
@j111q can you review the copy? Thanks

**Comment by j111q** [comment]
Hi 😊 Thanks @octaedro for the ping. 

Revised copy:`Use global attributes to allow shoppers to filter and search for this product. Use custom attributes to provide detailed product information.`

Image:
<img width="598" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/7a53753a-4274-4631-99b4-45118156bebc">.
