### ISSUE TITLE
REST API POST Customers, returns internal_server_error Cannot access offset of type string on string in

### ISSUE THREAD

**Issue by davidhealey** [woothemes/woocommerce#41791]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using hoppscotch.io to test my requests.

I'm POSTing to https://my_domain.xyz/wp-json/wc/v3/customers?consumer_key=xxxx&consumer_secret=xxxx

I'm passing an `email` parameter with a valid email address.

### Expected behavior

I expect a new user to be created with the passed email address

### Actual behavior
```
{
  "code": "internal_server_error",
  "message": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/documentation/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>",
  "data": {
    "status": 500
  },
  "additional_errors": []
}
```
### Steps to reproduce

Fresh Wordpress site running on CyberPanel (Open Lite Speed). The only plugin active is WooCommerce. I am using the Storefront theme. I have tested this one two different websites.

Go to hoppscotch (or other service of your choice).

Make a POST request to: https://my_domain.xyz/wp-json/wc/v3/customers?consumer_key=xxxx&consumer_secret=xxxx

Pass an email address as the parameter.

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total Database Size: 6.55MB
Database Data Size: 4.55MB
Database Index Size: 2.00MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mwb_mautic_cf7_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.09MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_shopmagic_automation_outcome: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_automation_outcome_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_guest: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_guest_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_marketing_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_optin_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_tracked_emails: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shopmagic_tracked_emails_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 9
post: 2
product: 18
product_variation: 7
revision: 20
shop_coupon: 2
shop_order: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.3.0

### Inactive Plugins (4) ###

Gutenberg: by Gutenberg Team – 17.1.3
LiteSpeed Cache: by LiteSpeed Technologies – 5.7.0.1
Mautic Integration For WooCommerce: by WP Swings – 1.3.0
WP Crontrol: by John Blackbourn & crontributors – 1.16.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child Theme
Version: 1.0
Author URL: http://woothemes.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/email-footer.php
storefront-child/woocommerce/emails/email-header.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-29 21:53:58 +00:00
Options: ✔
Notes: 86
Onboarding: skipped

### Action Scheduler ###

Complete: 33
Oldest: 2023-10-30 13:59:17 +0000
Newest: 2023-11-29 18:16:00 +0000

Pending: 2
Oldest: 2023-11-29 18:35:31 +0000
Newest: 2023-11-30 06:00:49 +0000

Failed: 4
Oldest: 2023-08-30 22:00:22 +0000
Newest: 2023-11-01 12:56:11 +0000

### Status report information ###

Generated at: 2023-11-29 18:35:16 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by davidhealey** [comment]
Additional information from error log

```
2023-11-30 00:19:02.419626 [NOTICE] [451444] [146.70.197.187:46928:HTTP2-15#my_domain.xyz] [STDERR] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-request.php:456
Stack trace:
#0 /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-request.php(999): WP_REST_Request->set_param()
#1 /home/my_domain.xyz/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-customers-v1-controller.php(331): WP_REST_Request->offsetSet()
#2 /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(1193): WC_REST_Customers_V1_Controller->create_item()
#3 /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#4 /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#5 /home/my_domain.xyz/public_html/wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#6 /home/my_domain.xyz/public_html/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#7 /home/my_domain.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#8 /home/my_domain.xyz/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#9 /home/my_domain.xyz/public_html/wp-includes/class-wp.php(418): do_action_ref_array()
#10 /home/my_domain.xyz/public_html/wp-includes/class-wp.php(813): WP->parse_request()
#11 /home/my_domain.xyz/public_html/wp-includes/functions.php(1336): WP->main()
#12 /home/my_domain.xyz/public_html/wp-blog-header.php(16): wp()
#13 /home/my_domain.xyz/public_html/index.php(17): require('...')
#14 {main}
  thrown in /home/my_domain.xyz/public_html/wp-includes/rest-api/class-wp-rest-request.php on line 456
```

Why is it going to `class-wc-rest-customers-v1-controller.php` instead of v3?

**Comment by barryhughes** [comment]
> Why is it going to class-wc-rest-customers-v1-controller.php instead of v3?

Though V1 is deprecated and its endpoints should not be used *directly,* much of its underlying code is perfectly solid. To varying degrees, both V2 and V3 build on top of and reuse elements of its code, which is why you see references to V1 in the trace.

**Comment by davidhealey** [comment]
@barryhughes Thanks Barry, that clears up that mystery for me. Now if I could only get it to work :)

**Comment by barryhughes** [comment]
In my initial testing it works ok, I either successfully create a new customer record or else, if I deliberately make an error (such as by changing the consumer key to something invalid), I get back:

```json
{
  "code": "woocommerce_rest_cannot_create",
  "message": "Sorry, you are not allowed to create resources.",
  "data": {
    "status": 401
  }
}
```

Thinking of the error you are facing:

`Uncaught TypeError: Cannot access offset of type string on string`

The code is trying to retrieve data from an array-like object (specifically, it expects an instance of `WP_REST_Request`) but it appears it is unexpectedly operating on a string instead.

I realize you noted disabling other plugins, etc, but is it possible some rogue debug code is impacting things, or anything like that?

**Comment by davidhealey** [comment]
@barryhughes 
The only thing I can think that is non-standard is I'm using a LiteSpeed server, so maybe something there is causing an issue, but then I would expect the GET to fail too.

This is a bare site I just setup for testing. I can share the login details with you if you have time to look into it?

**Comment by barryhughes** [comment]
So first I should call out that my earlier diagnosis wasn't correct. The problem here is not that we don't have a valid `WP_REST_Request` object, it is more that some internal state within the object is set to an unexpected value.

> This is a bare site I just setup for testing. I can share the login details with you if you have time to look into it?

We don't have the bandwidth to do that, I'm afraid (and, right now, it doesn't seem like a general bug lots of people are facing).

> The only thing I can think that is non-standard is I'm using a LiteSpeed server

This is a possibility. Do you have other, non-Litespeed based environments you can test in? 

However, before trying that, I think I'd suggest starting by examining actual request you are making. Are you familiar with and can you make your request from a command line tool such as [CURL](https://curl.se/)? Does that work, or do you see the same problem? If it does not work, can you share the full details of the command you are using?

Our [REST API docs](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-customer) have examples of using CURL for this purpose, that might help you get started (and the reason I'm suggesting this is that it will become far easier for us to see what you are using for things like the *content type* header, and various other details).

Alternatively, if Hoppscotch can convert your saved requests into CURL format, feel free to share that with us.

**Comment by davidhealey** [comment]
Hey well that's interesting. Making the request via CURL works! So I guess this is a me problem and something to do with how I'm making the request from my app.

I think I have enough info now to work out a solution so I'll close this issue.

@barryhughes Thanks for the pointers!

**Comment by barryhughes** [comment]
No problem, glad we have a sense of where the problem might lie!

Fwiw, I noticed that, within the request object, the [set of JSON parameters](https://github.com/WordPress/wordpress-develop/blob/6.4.2/src/wp-includes/rest-api/class-wp-rest-request.php#L659-L706) (in your case, we'd expect to find the email address here) will not actually be defined if the [content type is set incorrectly](https://github.com/WordPress/wordpress-develop/blob/6.4.2/src/wp-includes/rest-api/class-wp-rest-request.php#L676-L678) (which is what got me wondering about the request itself).

Anyway ... good luck, I hope you find the answer 💪🏼
