### ISSUE TITLE
Improve coupon-usage-by-user query performance

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#41827]
In a similar spirit to https://github.com/woocommerce/woocommerce/issues/41798, we should take a look at the query in [`WC_Coupon_Data_Store_CPT::get_usage_by_user_id()`](https://github.com/woocommerce/woocommerce/blob/8.3.0/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L439):

```php
$wpdb->prepare(
	"SELECT COUNT( meta_id ) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = '_used_by' AND meta_value = %d;",
	$coupon->get_id(),
	$user_id
)
```

The type mismatch (`%d` for a longtext field) apparently leading to performance issues in some cases/at certain scales.

**Comment by glagonikas** [comment]
until this is resolved in core, a fix can be hardcoded as follows

in [wp-content\plugins\woocommerce\includes\data-stores\class-wc-coupon-data-store-cpt.php](https://github.com/woocommerce/woocommerce/blob/8.5.1/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L444) at line 444 please change from

`"SELECT COUNT( meta_id ) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = '_used_by' AND meta_value = %d;",`

to

`"SELECT COUNT( meta_id ) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = '_used_by' AND meta_value = %s;",`

so literarily one character change from "d" to "s" can make a big difference in query performance. more info here https://shatteredsilicon.net/mariadb-mysql-performance-tuning-optimization-data-types/
