### ISSUE TITLE
[8.3.X] Free Shipping not selected by default when it becomes available

### ISSUE THREAD

**Issue by shaunkuschel** [woothemes/woocommerce#41831]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using WC version `8.3.0`+, Free Shipping is not automatically selected as the default method when it is at the top of the list and becomes available after another method is offered first (such as Flat Rate).

I confirmed this with a fresh install and only WooCommerce active.

This issue does not occur with version `8.2.2`.

**Shipping Zone setup:**

![Markup 2023-11-30 at 20 56 17](https://github.com/woocommerce/woocommerce/assets/10855013/406c4f5b-1780-45a1-b2a6-8602b3d8846a)

**Free Shipping settings:**

![Markup 2023-11-30 at 20 54 09](https://github.com/woocommerce/woocommerce/assets/10855013/811d6f1d-117c-4bc5-a713-731d84fd13aa)

**Flat Rate settings:**

![Markup 2023-11-30 at 20 55 17](https://github.com/woocommerce/woocommerce/assets/10855013/3d8f44a3-0bea-4361-a61e-ea0d167ed4ae)

The GIF below shows the behavior on the Cart page using both version `8.2.2` and `8.3.0` (but this also seems to occur with `8.3.1`).

![Screen Capture on 2023-11-30 at 20-39-53](https://github.com/woocommerce/woocommerce/assets/10855013/1056103e-17bc-4e5c-ae64-de91b815fdf7)

Internal: Reported on 7388682-zen

### Expected behavior

When Free Shipping is at the top of the shipping methods list and becomes available, it should be selected as the default.

### Actual behavior

When Free Shipping is at the top of the shipping methods list and becomes available, the initially-offered method is still selected as the default, rather than Free Shipping.

### Steps to reproduce

1. Using WC 8.3.0+, create a Shipping Zone with Free Shipping at the top with a minimum amount requirement and another method below (such as Flat Rate) that will always be offered.
2. Create a product that does not meet the Free Shipping required amount with a single quantity.
3. Add the product to the cart with a quantity of 1 and notice the other shipping method being offered (i.e. Flat Rate).
4. Increase the quantity of the product to meet/exceed the Free Shipping required amount and notice that Free Shipping is offered at the top but not selected by default after the re-calculation on the Cart page.
5. Clear the cart and downgrade WC to version 8.2.2.
6. Perform the same test as above and notice that Free Shipping is selected by default when it becomes available.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://homeless-kestrel.jurassic.ninja
Site address (URL): https://homeless-kestrel.jurassic.ninja
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total Database Size: 4.24MB
Database Data Size: 2.54MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/users/user79ad5500/apps/user79ad5500/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/users/user79ad5500/apps/user79ad5500/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/users/user79ad5500/apps/user79ad5500/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-02 02:02:46 +00:00
Options: ✔
Notes: 62
Onboarding: -

### Action Scheduler ###

Complete: 10
Oldest: 2023-12-01 02:02:57 +0000
Newest: 2023-12-01 02:40:17 +0000

Failed: 1
Oldest: 2023-12-01 02:15:23 +0000
Newest: 2023-12-01 02:15:23 +0000

Pending: 1
Oldest: 2023-12-02 02:02:57 +0000
Newest: 2023-12-02 02:02:57 +0000

### Status report information ###

Generated at: 2023-12-01 02:40:24 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shaunkuschel** [comment]
[Internal: Another report on 7404553-zen]

The code snippet in the [Hide other shipping methods when “Free Shipping” is available](https://woo.com/document/hide-other-shipping-methods-when-free-shipping-is-available/) doc is another possible workaround for sites experiencing this issue if they want to force Free Shipping to be used when available.

**Comment by AashikP** [comment]
Another report in 7432591-zd-a8c

I went as far as WooCommerce 6.0.0 where free shipping is indeed offered as the default option when it is available. For example, a free shipping coupon.

**Comment by jamesmarko** [comment]
Another report here for this bug, URGENT fix needed as it's confusing customers. Unfortunately I can't hide other shipping options as we only offer free shipping for standard post and they can select Express etc

**Comment by darcie** [comment]
7426755-zen

**Comment by carolframen** [comment]
7605241-zen
7587013-zen

**Comment by maplemouse2** [comment]
Is this going to be fixed soon?
