### ISSUE TITLE
Error while a variation stock quantity has been finished 

### ISSUE THREAD

**Issue by AghaFarokh** [woothemes/woocommerce#41848]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hey
I'm not 100% sure but I'm 99% sure that this error occurs while first user added a product to the card and that product has a limited quantity and second user has bought the product and when the first user comes back to the website due it's woocommerce_persistent_cart it will throw an error due to cant update the quantity in the first user cart
I don't know exactly this makes it throw this error bcs I didn't have enough time to reproduce the error but while I've searched for the id in the database and do a little investigate I've guessed it maybe bcs of this

Error : 

> [01-Dec-2023 09:19:39 UTC] PHP Notice:  Undefined index: aab68c100a3f354c75d3f50be890598f in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 1361
[01-Dec-2023 09:19:39 UTC] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 1361
[01-Dec-2023 09:19:39 UTC] PHP Notice:  Undefined index: data in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php on line 232
[01-Dec-2023 09:19:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_tax_class() on null in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php:232
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(658): WC_Cart_Totals->get_items_from_cart()
#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(150): WC_Cart_Totals->calculate_item_totals()
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(141): WC_Cart_Totals->calculate()
#3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1408): WC_Cart_Totals->__construct()
#4 /var/www/html/wp-content/themes/woodmart/inc/integrations/woocommerce/modules/quantity.php(57): WC_Cart->calculate_totals()
#5 /var/www/html/wp-includes/class-wp-hook.php(324): woodmart_update_cart_item()
#6 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/html/wp-admi in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php on line 232

### Expected behavior

remove the product from the cart and don't throw errors

### Actual behavior

dont throw errors

### Steps to reproduce

1. user A add a variation with 1 stock quantity to the cart and exit from the site
2. user B comes and buy that variation and make that quantity 0
3. user A returnt to the website and it will throw an error

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by AghaFarokh** [comment]
Any update ??

**Comment by ralucaStan** [comment]
Hello @AghaFarokh,
thank you for your patience, looks like this ticket slipped us.

I followed the steps you provided and I am not able to reproduce the bug. 

I tested with WooCommerce 8.6 and using both checkout shortcodes and blocks. 

> user A returnt to the website and it will throw an error
In this step I actually see  a warning in the Cart and the site works for me.
<img width="1048" alt="Screenshot 2024-02-28 at 19 37 29" src="https://github.com/woocommerce/woocommerce/assets/1628454/b67e4834-5a1b-42ae-8e2c-e543f51f13b0">

Can you still reproduce this bug? Can you reproduce it when disabling other plugins or custom themes? 

Let us know.
