### ISSUE TITLE
Add a check for experiment name format in ExPlat clients

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#41854]
### Issue description

In our profiler email marketing opt-in experiment, the experiment name was invalid and we did not realise this post code-freeze (p1700120655161389-slack-C7HH3V5AS).

In order to catch this issue earlier, our ExPlat clients should produce error when an experiment name is invalid.

The current pattern for the experiment name validation is:  `'^[a-z0-9_,]*$'`

### Acceptance criteria

1. Assignment APIs in [ExPlat JS client](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/explat/src/index.ts) for WooCommerce should throw error on invalid experiment name.
    - Currently, we utilize the ExPlat client package which [has an existing validation](https://github.com/Automattic/wp-calypso/blob/25c4163616012705a6a22644701c0d946e0571b3/packages/explat-client/src/internal/validations.ts#L7-L14), however, it's incomplete. Ideally, we implement the validation in the package and WC inherits naturally. cc @jessie-ross since you mentioned this here p1700148035420219/1700120655.161389-slack-C7HH3V5AS
3.  Assignment APIs in [ExPlat PHP client](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php) for WooCommerce should throw error on invalid experiment name.

**Comment by jessie-ross** [comment]
Feel free to improve the variation in the ExPlat client :)

**Comment by rjchow** [comment]
@ilyasfoo it seems like the WC Core explat PHP client [already throws an error, but the regex is slightly different](https://github.com/woocommerce/woocommerce/blob/abc699367844161b05ea63aeb43998db3edf7f11/plugins/woocommerce/includes/react-admin/class-experimental-abtest.php#L197). 

So we just need to adjust that regex to match, am I understanding it correctly?

**Comment by ilyasfoo** [comment]
Yes! Seems like your PRs done that, thanks!

**Comment by ilyasfoo** [comment]
@rjchow Is there any other follow-ups? Otherwise, I think we can close this as completed

**Comment by rjchow** [comment]
Let's close it! 🚀
