### ISSUE TITLE
Blocks Translations not showing up

### ISSUE THREAD

**Issue by mdca** [woothemes/woocommerce#41887]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Some string within the Gutenberg Blocks do not show up translated in cs_CZ even though they are translated in the PO/MO files. This applies both to some translations provided by the default translation that comes with WC and custom translations.

I tried translating both using Loco Translaslate and POEdit.

For example on the Checkout page there's an email field. The EN label is Email address and is translated in the default translation files, however is still shows up in EN instead of cs_CZ.

On the Checkout page the same issue applies for:

- Email address (field label)
- Phone (field label)
- Order summary (block heading)
- Total (order total line)
- Including XY... (tax details under the order total) 

### Expected behavior

 Texts show up translated based on what's in the MO files.

### Actual behavior

Texts do not show up translated according to what's in the MO files.

### Steps to reproduce

1. Add a product to cart
2. Go to checkout page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://vanoce.afm.local/cms
Site address (URL): http://vanoce.afm.local
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) PHP/7.4.21 mod_fcgid/2.3.10-dev
PHP Version: 7.4.21
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Celková velikost databáze: 9.63MB
Velikost dat databáze: 9.07MB
Velikost indexu databáze: 0.56MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_eum_logs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_notes_users_relations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_submissions_actions_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_submissions_values: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_budget_recommendations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
wp_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_jet_post_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_jet_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.77MB + Index: 0.07MB + Engine MyISAM
wp_postmeta: Data: 1.72MB + Index: 0.07MB + Engine MyISAM
wp_posts: Data: 4.29MB + Index: 0.03MB + Engine MyISAM
wp_rank_math_404_logs: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_rank_math_analytics_keyword_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_analytics_objects: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rank_math_internal_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_wc_orders_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_addresses: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

acf-post-type: 1
afm-review: 5
attachment: 31
customize_changeset: 1
elementor_library: 4
jet-engine: 2
jet-woo-builder: 1
nav_menu_item: 3
page: 13
post: 2
product: 4
revision: 190
shop_order_placehold: 3
wp_global_styles: 1
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ❌
					Váš obchod nepoužívá HTTPS. Zjistěte více o HTTPS a SSL certifikátech.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: Autor: Automattic – 8.3.1

### Inactive Plugins (13) ###

Advanced Custom Fields PRO: Autor: WP Engine – 6.2.4
All-in-One WP Migration: Autor: ServMask – 7.79
All-in-One WP Migration URL Extension: Autor: ServMask – 2.65
Easy Updates Manager: Autor: Easy Updates Manager Team – 9.0.17
Ecomail: Autor: ECOMAIL.CZ – 2.1.6
Elementor: Autor: Elementor.com – 3.18.0
Elementor Pro: Autor: Elementor.com – 3.18.0
Filenames to latin: Autor: webvitaly – 2.7
Google Listings and Ads: Autor: WooCommerce – 2.5.12
JetEngine: Autor: Crocoblock – 3.3.1
Loco Translate: Autor: Tim Whitlock – 2.6.6
Rank Math SEO: Autor: Rank Math – 1.0.207
Rank Math SEO PRO: Autor: Rank Math – 3.0.29

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Obchod: #10 - /shop/
Košík: #11 - /cart/
Pokladna: #12 - /checkout/
Můj účet: #13 - /my-account/
Obchodní podmínky: #184 - /obchodni-podminky/

### Theme ###

Name: Twenty Twenty-Three
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-06 13:12:33 +01:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Dokončeno: 106
Oldest: 2023-12-04 00:28:30 +0100
Newest: 2023-12-05 16:15:01 +0100

Čekající: 3
Oldest: 2023-12-05 16:23:09 +0100
Newest: 2023-12-08 13:56:21 +0100

Selhalo: 3
Oldest: 2023-12-04 00:34:58 +0100
Newest: 2023-12-05 12:31:23 +0100

### Status report information ###

Generated at: 2023-12-05 16:22:31 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Some string within the Gutenberg Blocks do not show up translated in cs_CZ even though they are translated in the PO/MO files.

@mdca Thanks for reporting the issue. Block translations are stored in json files under `wp-content/languages`. You can use [make-pot](https://developer.wordpress.org/cli/commands/i18n/make-pot/) to generate the json files. Then edit the files to provide the translations. I'll close this as a question.
