### ISSUE TITLE
[CYS on Core] Ensure the fonts selected in the Assembler are displayed on the frontend

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#41924]
**Issue Description:**

Whenever running the CYS flow and selecting a font for the site, it is not correctly displayed on the front-end:

https://github.com/woocommerce/woocommerce/assets/15730971/9fa56b45-1212-4232-9ef4-ace4033200af

### Steps to Reproduce

- Ensure you have a WordPress install with WooCommerce, WooCommerce Beta Tester, woo-ai, and WooCommerce Blocks plugins installed (latest and greatest versions).
- Ensure your site has Jetpack installed and that your site is connected with JetPack
- Go to Tools > WCA Test Helper > Features and enable the `customize-store` feature.
- Head over to WooCommerce > Home > Customize your store
- Go through the CYS flow as demonstrated in the video above and select a font.
- Save your changes and go to the front end: notice how your selected font is not being correctly picked up/displayed.

### Expected outcome

Whenever a new font is selected in the CYS flow, it should also be rendered on the frontend.

**Comment by gigitux** [comment]
I tried to reproduce the issue on `.com` env and JN without success:

### .COM 


https://github.com/woocommerce/woocommerce/assets/4463174/3eb32800-7076-47b8-93ca-660b0d949fae




### JN


https://github.com/woocommerce/woocommerce/assets/4463174/18cab2be-8819-4075-97d0-6c84b55f10aa

**Comment by nefeline** [comment]
> I tried to reproduce the issue on .com env and JN without success:

Thanks @gigitux: I can reproduce this on JN exclusively, on WooExpress things are working as expected: still couldn't find the culprit, though. Will keep monitoring and share any updates here.

**Comment by chihsuan** [comment]
Hey @gigitux, I noticed the font looks different in your JN video and I could also reproduce it in JN.

![Screenshot 2023-12-08 at 13 30 57](https://github.com/woocommerce/woocommerce/assets/4344253/0c85b33b-77bb-44a9-b3dc-b28a8b7dc86b)

![Screenshot 2023-12-08 at 13 31 08](https://github.com/woocommerce/woocommerce/assets/4344253/7f6945bc-ab8a-4ddc-bf90-82a38ecff8f2)

**Comment by chihsuan** [comment]
@nefeline @gigitux  I think this is related to whether there is a registered google font provider. Dotcom has a module to register Google Fonts.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qcyhtva%2Sfha%2Szbqhyrf%2Stbbtyr%2Qsbagf%2Sjbeqcerff%2Q6.3%2Sybnq%2Qtbbtyr%2Qsbagf.cuc%3Se%3Q42n09s2q%2318-og

**Comment by gigitux** [comment]
> @nefeline @gigitux I think this is related to whether there is a registered google font provider. Dotcom has a module to register Google Fonts.
> 
> uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qcyhtva%2Sfha%2Szbqhyrf%2Stbbtyr%2Qsbagf%2Sjbeqcerff%2Q6.3%2Sybnq%2Qtbbtyr%2Qsbagf.cuc%3Se%3Q42n09s2q%2318-og

Oh, nice catch! Thanks for giving me the context. Should we register Google Fonts on Core? Or should we hide the fonts option? 🤔

**Comment by nefeline** [comment]
> Should we register Google Fonts on Core? Or should we hide the fonts option? 🤔

Let's ping the design team to confirm. Cc: @j111q @verofasulo @jarekmorawski TLDR: should we add Google Fonts to the open-source plugin? They are being used in the CYS flow on WooExpress.

**Comment by chihsuan** [comment]
We had some related discussions in this thread p1696414489903779/1696411326.058159-slack-C053716F2H2

> We should investigate to see if we could programmatically download the required fonts using it to the host

**Comment by nefeline** [comment]
Thanks for finding and sharing the link to that previous discussion @chihsuan! The Fonts feature was punted to WordPress 6.5 https://github.com/WordPress/wordpress-develop/pull/5285, which is planned to be released next year. 

With that said, a good next step would be to check the status for the development/addition of this feature: if, for some reason, fonts don't make it to WP 6.5 either, it would be worth investigating an alternative implementation (even if temporary) so we don't risk significantly delaying the release of CYS on core.
