### ISSUE TITLE
Calender and gift form not displaying

### ISSUE THREAD

**Issue by IanBJ1** [woothemes/woocommerce#41930]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've created a bookable event and a gift item.
On the bookable product the calender shows when I build it, but doesn't show after it is published online
And for the gift token the form doesn't show of who it should be sent to

### Expected behavior

Calender and gift form to be displayed when published

### Actual behavior

I've created a bookable event and a gift item.
On the bookable product the calender shows when I build it, but doesn't show after it is published online
And for the gift token the form doesn't show of who it should be sent to
[wordpress bookings.pdf](https://github.com/woocommerce/woocommerce/files/13591345/wordpress.bookings.pdf)

### Steps to reproduce

[wordpress bookings.pdf](https://github.com/woocommerce/woocommerce/files/13591354/wordpress.bookings.pdf)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://jojosvineyard.co.uk
Site address (URL): https://jojosvineyard.co.uk
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.26
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 8.1.2
OpenSSL/1.1.1t-fips

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: a7_
Total Database Size: 87.23MB
Database Data Size: 81.87MB
Database Index Size: 5.36MB
a7_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
a7_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
a7_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_actionscheduler_actions: Data: 0.28MB + Index: 0.19MB + Engine InnoDB
a7_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
a7_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_arm_dripped_contents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
a7_defender_audit_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
a7_defender_email_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_defender_lockout: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_defender_lockout_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_defender_quarantine: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_defender_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_defender_scan_item: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_fc_campaigns: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
a7_fc_campaign_emails: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
a7_fc_campaign_url_metrics: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_fc_contact_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
a7_fc_contact_relation_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
a7_fc_funnels: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
a7_fc_funnel_metrics: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_fc_funnel_sequences: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
a7_fc_funnel_subscribers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
a7_fc_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fc_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
a7_fc_sequence_tracker: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
a7_fc_smart_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_fc_subscribers: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
a7_fc_subscriber_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_fc_subscriber_notes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
a7_fc_subscriber_pivot: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
a7_fc_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fc_url_stores: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_draft_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_entry_details: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_logs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_submissions: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_subscriptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fluentform_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_fsmpt_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_ju_queue: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
a7_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_nextend2_smartslider3_slides: Data: 0.03MB + Index: 0.11MB + Engine InnoDB
a7_options: Data: 4.36MB + Index: 0.17MB + Engine InnoDB
a7_postmeta: Data: 59.52MB + Index: 0.73MB + Engine InnoDB
a7_posts: Data: 2.52MB + Index: 0.19MB + Engine InnoDB
a7_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_snapshot_action_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_usermeta: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
a7_users: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
a7_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
a7_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
a7_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
a7_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
a7_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
a7_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
a7_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
a7_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
a7_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
a7_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
a7_wpml_mails: Data: 10.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
apto_sort: 2
attachment: 242
bookable_person: 23
bookable_resource: 1
bsf_custom_fonts: 2
cptm: 1
custom_css: 1
events: 1
fc_template: 1
fl-builder-template: 12
fl-theme-layout: 9
nav_menu_item: 9
page: 59
post: 12
product: 23
revision: 322
shop_coupon: 6
shop_order: 89
shop_order_refund: 21
wc_booking: 7
wc_membership_plan: 2
wc_user_membership: 2
yaymail_template: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Advanced Custom Fields: by WP Engine – 6.2.4
Advanced Post Types Order: by Nsp Code – 5.1.6
Age Gate: by Phil Baker – 3.3.1
Astra Pro: by Brainstorm Force – 4.5.1
Beaver Builder Plugin (Agency Version): by The Beaver Builder Team – 2.7.3.2
Beaver Themer: by The Beaver Builder Team – 1.4.8
Ultimate Addons for Beaver Builder: by Brainstorm Force – 1.35.17
Custom Fonts: by Brainstorm Force – 2.1.1
Custom Post Type Maker: by Graffino – 1.2.0
Disable Gutenberg: by Jeff Starr – 3.1
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
YayMail Pro - WooCommerce Email Customizer: by YayCommerce – 3.1.3
Exo Toolkit: by WordPress Doctor / Exo UK Ltd – 2.1
FluentCRM - Marketing Automation For WordPress: by WP Email Newsletter Team - FluentCRM – 2.8.34
FluentCRM Pro: by Fluent CRM – 2.8.20
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.1.5
Fluent Forms Pro Add On Pack: by Fluent Forms – 5.1.6
Fluent Forms PDF Generator: by WPManageNinja LLC – 1.1.7
Flying Pages: by WP Speed Matters – 2.4.6
If Menu - Visibility control for menus: by Layered – 0.17.0
Image Editor by Pixo: by  – 2.3.1
Jetpack: by Automattic – 12.9
MainWP Child: by MainWP – 4.5.3
More Visibility Rules: by Layered – 0.4
Smart Slider 3 Pro: by Nextend – 3.5.1.21
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.14.26

User Switching: by John Blackbourn & contributors – 1.7.2
WooCommerce Bookings: by WooCommerce – 1.15.48
WooCommerce Gift Cards: by WooCommerce – 1.16.6
WooCommerce Memberships: by SkyVerge – 1.22.2
WooCommerce PayPal Payments: by WooCommerce – 2.4.1 (update to version 2.4.2 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce Square: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 8.3.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Media folder: by Joomunited – 5.7.3
WP-Optimize Premium - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.22

SEOPress: by The SEO Guys at SEOPress – 7.2
YayMail Addon for WooCommerce Bookings: by YayCommerce – 1.5

### Inactive Plugins (8) ###

FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.6
Media Library Folders: by Max Foundry – 8.1.6
Media Library Folders Reset: by Max Foundry – 8.1.6
Post Types Order: by Nsp Code – 2.1.1
Simple Page Ordering: by 10up – 2.6.3
Snapshot Pro: by WPMU DEV – 4.21.1
Wicked Folders: by Wicked Plugins – 2.18.19
WooCommerce Stripe Gateway: by WooCommerce – 7.7.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

StackCache: by Stack CP –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #44 - /shop/
Basket: #45 - /basket/
Checkout: #46 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #48 - /refund_returns/

### Theme ###

Name: Astra
Version: 1.0
Author URL: https://exo.uk
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.5.0 – 4.5.1 is available
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: Products: 1 item
Excluded from discounts:: 2 products
Membership plans:: 2 (0 published)				❌ No published plans
Hattie Membership (draft):: Members: 0Access method: Manual assignment onlyAccess length: Specific length (1 years)
Gold (draft):: Members: 2Access method: Product(s) purchaseAccess length: Specific length (1 years)

### Gift Cards ###

Database Version: 1.16.6
Loopback Test: ✔
Task Queueing Test: ✔

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-07 10:46:52 +00:00
Options: ✔
Notes: 167
Onboarding: completed

### Action Scheduler ###

Complete: 714
Oldest: 2023-11-05 21:50:16 +0000
Newest: 2023-12-06 20:21:15 +0000

Failed: 9
Oldest: 2022-08-25 08:05:52 +0100
Newest: 2023-12-04 22:41:29 +0000

Pending: 5
Oldest: 2023-12-06 20:39:14 +0000
Newest: 2023-12-25 14:26:19 +0000

### Status report information ###

Generated at: 2023-12-06 20:36:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> I've created a bookable event and a gift item.

@IanBJ1 You need to contact support for issues with extensions. I'll mark this as a support request which will post links and instructions for accessing support.
