### ISSUE TITLE
Fix Migrated WooCommerce Blocks Text Domains

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#41996]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

With the migration we're going to need to edit the various files merged to convert the text domain from `'woo-gutenberg-products-block'` to `'woocommerce'`. Some of these would be:

- `plugins/woocommerce-blocks`
- `plugins/woocommerce/src/Blocks`
- `plugins/woocommerce/src/StoreApi`
- `plugins/woocommerce/patterns`
- `plugins/woocommerce/templates`

There may be more so we need to make sure to look into it thoroughly. In addition, we should make sure that the linting checks for the correct text domain. Lastly, I _think_ (correct me if I'm wrong) there's some work to do in making sure that the translations are loaded correctly. There's some existing functionality here that exists from WooCommerce Admin that we might be able to make use of, otherwise, I think there's some code in `plugins/woocommerce-blocks/woocommerce-gutenberg-products-block.php` to steal.

**Comment by rrennick** [comment]
@ObliviousHarmony Can we close this one?

**Comment by ObliviousHarmony** [comment]
Yeah, looks like it! Thanks for taking care of this @rrennick.
