### ISSUE TITLE
WordPress Urgrade caused site to crash requesting a ridiculous amount of memory

### ISSUE THREAD

**Issue by Larmour86** [woothemes/woocommerce#41998]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Upon upgrade to the 6.3 version everything completely crashes the website goes to a white page, requesting a extremely large amount of space needed

### Expected behavior

It's Wilmer so I don't expect it to do anything other than what Wilmer is supposed to do. I don't expect it to change my entire site.

### Actual behavior

Hello I'm in the middle of editing out the website for a company and when I went to login it was completely crashed. I have talked to the site ground tech-support. I have also talked to WooCommerce  support in both were baffled. I've been working on this for weeks now and once I follow the steps, we discovered that it was the word press plug-in upgrade. All plug-ins were disabled. All plug-ins were reenable one at a time, but once I got to the main commerce plug-in, everything kept crashing and it will go to a page requesting a extremely large amount of space. I have never had issues with this app until this upgrade the only solution what's the downgrade back to the 6.2 version and everything is working just fine. However, I wanted to purchase a particular set of things that your website offers and apparently it's included in the new upgrade. Well I cannot upgrade because of the continuous problem. So I thought well let me report this to you all the Walkers tech-support told me to just wait for the next upgrade, but I thought maybe I should let you all know as well. The thing that I use is NEVE pro as well in case you needed to know.

### Steps to reproduce

I have gone through the steps several times for hours from both the commerce tech-support people, as well as the site, ground tech-support people and have did the steps were disable and plug-ins, even using a different thing and everything kept crashing

### WordPress Environment

I'm not entirely sure how to use This  site.  only to let you all know what's going on what happened and ask when the next upgrade will happen hoping that this newer upgrade will not cause the same issue I'm currently having

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> I have also talked to WooCommerce support in both were baffled.

Hi @Larmour86 Sorry to hear you are having an issue with your customer's web site. However, we do not provide support via Github. I'll mark this as a support request which will provide links to options for obtaining support.
