### ISSUE TITLE
[Enhancement]: Add a `totalValue` Checkout Block filter to modify total value

### ISSUE THREAD

**Issue by Sidsector9** [woothemes/woocommerce#42004]
## Is your feature request related to a problem? Please describe.

Woo blocks provides the [totalLabel](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md#totallabel) filter to customise the label.

There are plugins such as [Pre-Orders](https://woo.com/products/woocommerce-pre-orders/) that filter the total value.
Currently, there is no way to filter this value for the Cart and Checkout blocks.

<img width="1553" alt="Screenshot 2023-12-11 at 2 03 48 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/17757960/3395d18a-22b6-4187-a225-74ba34d835b4">

## Describe the solution you'd like

I propose the addition of the `totalValue` filter to modify the total value.

**Comment by mikejolley** [comment]
This might be useful, but on the other hand the wording could be refactored on pre-orders side to use `totalLabel` instead e.g. 

```
Total (charged on xx.xx.xx): Amount
```

This should probably be investigated. cc @senadir We can move this to pre-orders issue tracker if more appropriate but moving to backlog for now.

**Comment by Sidsector9** [comment]
@mikejolley thanks for the reply. There's a problem with using the label. When using the placeholder `{order_total}`, the amount is printed twice. Once in the label and another in the totalValue field.

At the moment, in Pre-Orders, the Block Checkout doesn't use these 2 settings for this reason.

**Comment by Sidsector9** [comment]
@diegocurbelo can you assign this issue to me please?

**Comment by Sidsector9** [comment]
I attempted to add a new `totalValue` checkout filter but the blocker is that the value received is of type number, and we want the filter to return a React Node as the `TotalsItemValue` component accepts a React element for a value:

https://github.com/woocommerce/woocommerce/blob/a6210ba312c2fdd343ff5df892e1a43f9bfb22cd/plugins/woocommerce-blocks/packages/components/totals/item/index.tsx#L24-L43

This is currently not possible as `applyCheckoutFilter` performs a type check between the initial and filtered value:

https://github.com/woocommerce/woocommerce/blob/a6210ba312c2fdd343ff5df892e1a43f9bfb22cd/plugins/woocommerce-blocks/packages/checkout/filter-registry/index.ts#L231-L243

I am sure the type checking is done for a reason and removing it wouldn't be the best solution, wondering if you guys have any thoughts on this?

**Comment by nielslange** [comment]
Hello @Sidsector9 👋 While looking into this issue, I noticed that by default, the due date is already visible behind the totals label both on the Cart and the Checkout block. 

## Cart

<table>
<tr>
<td valign="top" width="50%">Shortcode-based cart:
<br><br>
<img width="527" alt="Screenshot 2024-02-16 at 15 39 32" src="https://github.com/woocommerce/woocommerce/assets/3323310/441a0eb1-48fd-4f52-9f27-1565e2ac590d">
</td>
<td valign="top" width="50%">Cart block:
<br><br>
<img width="415" alt="Screenshot 2024-02-16 at 15 39 07" src="https://github.com/woocommerce/woocommerce/assets/3323310/20974bfd-8921-4c98-a462-2ca911bbc39e">
</td>
</tr>
</table>

## Checkout

<table>
<tr>
<td valign="top" width="50%">Shortcode-based checkout:
<br><br>
<img width="762" alt="Screenshot 2024-02-16 at 15 40 04" src="https://github.com/woocommerce/woocommerce/assets/3323310/3b3c6784-52e5-4ed6-9f32-a243b475dbee">
</td>
<td valign="top" width="50%">Checkout block:
<br><br>
<img width="434" alt="Screenshot 2024-02-16 at 15 40 17" src="https://github.com/woocommerce/woocommerce/assets/3323310/f1de2897-80ce-4fe5-9d0a-29964df7a786">
</td>
</tr>
</table>

While introducing a `totalValue` filter could be an option, may I ask what exactly you have in mind. In the example above, I haven't used any filter, though.

**Comment by Sidsector9** [comment]
@nielslange thanks for the ping.

The issue is that the admin setting **Charged upfront order total format** affects the shortcode and block checkout differently.

### Setting

<img width="650" alt="Screenshot 2024-02-19 at 10 08 06 AM" src="https://github.com/woocommerce/woocommerce/assets/17757960/02dfb981-fa11-4c08-8213-75ab6a46f0b0">

### Shortcode checkout

<img width="354" alt="Screenshot 2024-02-19 at 10 07 18 AM" src="https://github.com/woocommerce/woocommerce/assets/17757960/570b2fd0-2dfb-4ef4-8d4a-43f489f176a1">

### Block checkout

<img width="285" alt="Screenshot 2024-02-19 at 10 07 46 AM" src="https://github.com/woocommerce/woocommerce/assets/17757960/2d4ebd0e-df18-4291-a91f-371aed3c35ba">

In the shortcode checkout, the total value field is filtered but in the block checkout, the _label_ field is filtered. So even if I add support for the setting in block checkout, it will display **You'll have to pay €15 right away** in the label and **€15** again in the total value field.

**Comment by nielslange** [comment]
Thanks for clarifying this use case, @Sidsector9. That's very helpful.

**Comment by nielslange** [comment]
Hello @Sidsector9, I went ahead and created https://github.com/woocommerce/woocommerce/pull/45170. Would you mind checking if this PR solves the specific issue you're currently facing regarding filtering the totals value?

**Comment by Sidsector9** [comment]
Thanks for working on this @nielslange!

It's functioning as expected, only minor issue is that for a longer string, there's a text overflow.

<img width="445" alt="Screenshot 2024-02-28 at 3 25 23 PM" src="https://github.com/woocommerce/woocommerce/assets/17757960/e4339678-a67f-4027-a7ec-a41e3d643247">

**Comment by nielslange** [comment]
Thanks for checking the PR, @Sidsector9. I'll take care of the text overflow in the PR as well.
