### ISSUE TITLE
Allow adjusting forced block template

### ISSUE THREAD

**Issue by dennisnissle** [woothemes/woocommerce#42026]
Hi there,

I'm currently testing different ways to adjust/extend the current checkout block. When registering/rendering checkout blocks, the block's lock attribute `attributes.lock.default.remove` is evaluated to determine whether to force-render the lazily registered component within its parent or not. 

I'm trying to adjust the current checkout markup which leads to the (inner) blocks having another parent block (additional hierarchy, e.g. checkout-block -> checkout-fields-block -> custom block -> inner block, e.g.: checkout-contact-information-block). Now the forced-block logic fails and adds an additional/duplicate block at the end of the field block. That's bad :( 

The WP Core offers the `blocks.registerBlockType` filter to adjust block registration. It would be nice to have a filter to adjust the component registration via `registerCheckoutBlock` to prevent blocks from being enforced. Another nice way would be to recursively check for all child nodes of a parent block. Currently only [first-level children](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/utils/render-parent-block.tsx#L253C26-L253C26) are evaluated. I could provide a pull request to do just that, if you want me to.

Best,
Dennis

**Comment by mikejolley** [comment]
Hi @dennisnissle 

The forced block logic is in place to prevent a merchant removing essential sections that would cause checkout to fail. You're saying you shifting it deeper into the hierarchy, but not removing it? 

> I could provide a pull request to do just that, if you want me to.

We could take a look into how looking deeper into the hierarchy would work, so feel free to do this so it can be reviewed. I assume if your parent block was removed, this would then kick the forcing back in to insert it at the first-level again.

Would also be keen to hear more about this use case and what you're doing here that requires the hierarchy to change.

Thanks

**Comment by dennisnissle** [comment]
Hi @mikejolley,

thanks for your feedback. For now I've found a workaround to the issue by replacing the fields block with my own block implementation which removes the (forced) duplicate children. 

Best,
Dennis

**Comment by ralucaStan** [comment]
I'll close the issue for now as there is nothing actionable on our end.
