### ISSUE TITLE
Shipping rate not synced with cart totals

### ISSUE THREAD

**Issue by passatgt** [woothemes/woocommerce#42034]
## Describe the bug

I have a shipping method that should change it's rate based on the selected payment method. Since the checkout block does not persist the selected payment method, i have some custom code to store the selection in session and use that value to calculate the shipping cost. With extensionCartUpdate, i refresh the cart when the payment method is changed. After this, the shipping rate does change correctly, but cart totals is not and it gets out of sync. You can see it in this video:

https://github.com/woocommerce/woocommerce-blocks/assets/43415/2b054b9c-d984-40ef-9633-e076bdaac934

## To reproduce

1. Created a sample plugin to reproduce the problem, install this: https://gist.github.com/passatgt/66699b10d1326a44eededecb67aae2bf
2. Add the shipping rate to a zone
3. Make sure COD and BACS payment method is activated
4. Go to checkout and switch between the payment methods to see the issue

## Expected behavior

I think cart totals should be in sync with shipping rates.

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks version: 11.7.0

## Additional context

Checking the cart details response after extensionCartUpdate, indicates that the shippingRates are set correctly, but totals show "outdated" values. And interestingly, in shipping debug mode, it works.

**Comment by mikejolley** [comment]
Can you explain more about this use case? It seems a bit strange to update costs in a previous step when changing payment gateways and I wonder if the fees API would be more appropriate.

Thanks

**Comment by passatgt** [comment]
Hi! I have a shipping rate plugin that lets you configure shipping rates based on various conditions and one of them is payment method. To give you a real world example, one of my client makes the cost higher if the customer selects Cash On Delivery(and adding a COD fee is not suitable because of some random invoicing issue).

**Comment by mikejolley** [comment]
Hm you mention debug mode. This prevents the shipping rate cache, so I wonder if the issue here is that the cache is never cleared because the payment method selection is only held in local state and is not used to invalidate caches.

Doing that would require filtering `woocommerce_cart_shipping_packages` and adding some key for the selected gateway to prevent the cache. I'm not sure this is specific to block checkout however; did you have the same issue with shortcode checkout?

**Comment by opr** [comment]
@passatgt hi there! I just checked out your example code and I could reproduce this. I'm not sure if this is the correct approach, but recalculating the totals just before we send the cart response back does fix this, however if you recalculate totals in the `extensionCartUpdate` callback it doesn't work, it has to be in the cart schema.

I don't have the shipping debug mode on.

I'll move this to our backlog, I _think_ this indicates an issue with the way we get shipping totals on cart routes, but can be investigated further when someone works on this.

Thanks for the report!

**Comment by senadir** [comment]
I did review the code again and reviewed the `calculate_shipping_for_pacakges` logic and it seems correct for me, as totals shouldn't change if the package info didn't change. Yet it's not clear to me why cache is being used in one place but not the others, this is to me, lack of consistent cache usage.

While I can dig deeper, I moved to other things for now, however, to unblock you @passatgt, you can clear the shipping hash to force recalculation, using this code in your existing callback:

```php
add_action(
	'woocommerce_blocks_loaded',
	function () {
		woocommerce_store_api_register_update_callback(
			array(
				'namespace' => 'test_shipping_rate',
				'callback'  => function ( $data ) {
					if ( isset( $data['payment_method'] ) ) {
						WC()->session->set( 'custom_chosen_payment_method', $data['payment_method'] );
						foreach ( array_keys( WC()->cart->get_shipping_packages() ) as $package_key ) {
							$wc_session_key = 'shipping_for_package_' . $package_key;
							WC()->session->set( $wc_session_key, '' );
						}
					}
				},
			)
		);
	}
);
```
