### ISSUE TITLE
Add To Cart Button - Non-valid HTML

### ISSUE THREAD

**Issue by tsvetkokrastev** [woothemes/woocommerce#42031]
## Describe the bug
The Add To Cart Button block is outputting non-valid HTML. As per the specifications of HTML5 ( https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element ) you can not nest `<button>` element inside `<a>` element. Also a `<buttton>` element can not have `href` attribute.

`The a element:
Content model: Transparent, but there must be no interactive content descendant, a element descendant, or descendant with the tabindex attribute specified.`

## To reproduce
Using Site Editor, edit template for Product Catalog, inside Products (Beta) block nest a Product Template block containing Add To Cart Button.

## Expected behavior

This should only output `<a>` element with `href` attribute. Drop the `<button>` inside. The block should have an option to either directly add the product to the cart or go the product single page.

## Screenshots
One screenshot from DevTools and one screenshot from w3.org validator:

<img width="374" alt="Screenshot 2023-12-06 at 13 01 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/129384779/fc2483db-c332-4c7d-9a33-8776ac0b0945">

<img width="1352" alt="Screenshot 2023-12-06 at 16 07 38" src="https://github.com/woocommerce/woocommerce-blocks/assets/129384779/c0449874-cc7a-499b-83da-16cc2039d2d9">

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks package: 11.4.9 (no additional plugin installed, this is from WooCommerce Core)

**Comment by kmanijak** [comment]
Hi @tsvetkokrastev!

Thanks for taking the time to report this issue. Obviously, non-valid HTML is not expected and it should be fixed. However, I can't reproduce it.


Below is the screenshot of a single product (`li`) markup with the Add to Cart Button (`button`) inside. `button` is nested in `div` and `li` elements.
<img width="1388" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/ee6bd828-e649-41d0-8b27-cafcc133a98c">

I'm using "Add to Cart Button" block:
<img width="338" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/26f43cc3-29a1-4e70-849c-4cb0754129fb">


Do you change some settings in blocks inspector controls to achieve this effect? Any additional information will help us reproducing it 🙌

**Comment by tsvetkokrastev** [comment]
Tested with default Storefront theme and there was no issue. Sorry for this, making it as resolved.
