### ISSUE TITLE
Link cross-sells product images to corresponding product pages

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42032]
## Is your feature request related to a problem? Please describe.

Currently, the product images of the cross-sells products are not linked to the product page, while the product images within the cart line items section and various other blocks, are linked to the product page. Apart from that, when using the shortcode-based cart, the product images of the cross-sells products are also linked.

## Describe the solution you'd like

I expect that the product images within the cross-sells products on the Cart block are linked to the corresponding product page.

**Comment by daotw** [comment]
+1
