### ISSUE TITLE
Texts occasionally overlap cart and checkout sidebar

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42040]
## Is your feature request related to a problem? Please describe.

Currently, the values within the cart and checkout sidebar occasionally exceed the width. This problem is caused due to the CSS definition `white-space: nowrap;`:

https://github.com/woocommerce/woocommerce-blocks/blob/5aa4f55036ab19d207311bf23d530cad53b5d88d/packages/components/totals/item/style.scss#L14

## Describe the solution you'd like

I propose removing this CSS definition to ensure that the text does not overlap.

## Steps to reproduce

1. Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` and activate the option `Enable the shipping calculator on the cart page`.
2. Create a test page and add the Cart block.
3. Create another test page and add the Checkout block.
4. Open the frontend in an incognito window.
5. Add a product to the cart and visit the test page with the Cart block.
6. Set the browser width to 840px.
7. See that the link `Add an address for shipping options` overlaps the cart sidebar.
8. Go to the test page with the Checkout block.
9. See that the text `No shipping options available` overlaps the checkout sidebar.

## Screenshots

<img width="988" alt="Screenshot 2023-12-04 at 12 09 17" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/f8b29f4e-6ddb-48d1-8c10-877717917816">

<img width="989" alt="Screenshot 2023-12-04 at 12 09 37" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/4f8f7f9a-fe98-4411-8608-da3cf5538b7e">

cc: @elizaan36

**Comment by niharikamahajan02** [comment]
Do i need to have pnpm install command here only ?
![image](https://github.com/woocommerce/woocommerce/assets/72392580/df79d011-e6ce-47dc-b7ef-6adef3c3ea93)

**Comment by nielslange** [comment]
Thanks for reaching out, @niharikamahajan02 .

> Do i need to have pnpm install command here only ?

Yes, you only need to run `pnpm install` when you fork the repo. Once you've done that, you can run one of the following commands, depending on what you're working on:
```sh
// Build the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce build
 
// Build and watch the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce watch:build
 
// Add a changelog entry to the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce changelog add
 
// Build the Woo Blocks folder
pnpm --filter='@woocommerce/block-library' build
 
// Build and watch the Woo Blocks folder
pnpm --filter='@woocommerce/block-library' watch:build
 
// PHPUnit: Run a specific PHP test file
pnpm --filter="@woocommerce/plugin-woocommerce" test:php:env -- tests/php/src/Blocks/StoreApi/Routes/Cart.php
 
// Playwright: Run normal tests
pnpm playwright test --config=tests/e2e/playwright.config.ts
 
// Playwright: Run normal tests in UI mode
pnpm playwright test --config=tests/e2e/playwright.config.ts --ui
 
// Playwright: Run classic tests
pnpm playwright test --config=tests/e2e/playwright.classic-theme.config.ts
 
// Playwright: Run classic tests in UI mode
pnpm playwright test --config=tests/e2e/playwright.classic-theme.config.ts --ui
 
// Playwright: Run side effects tests
pnpm playwright test --config=tests/e2e/playwright.side-effects.config.ts
 
// Playwright: Run side effects tests in UI mode
pnpm playwright test --config=tests/e2e/playwright.side-effects.config.ts --ui
```

I hope that helps. If you have any further questions, please don't hesitate to reach out.

**Comment by niharikamahajan02** [comment]
@nielslange Thanks!
Yes I had forked the repo and following is what I am getting after running pnpm install . So to solve the provided issue do I need to  run the command pnpm --filter='@woocommerce/block-library' watch:build  . as I am unable to know from where can I see this issue in my local env (either by using wampp or something else) . Also I have installed all the pre-requisites as mentioned in readme file.
![image](https://github.com/woocommerce/woocommerce/assets/72392580/3506de23-d600-4026-976f-21e88e7bdfb9)
![image](https://github.com/woocommerce/woocommerce/assets/72392580/bcf756ed-ea9d-43d9-b9c3-65910abb5535)

**Comment by nielslange** [comment]
When running `pnpm i`, does the command actually finish? You should see something similar to this:

<img width="1512" alt="Screenshot 2023-12-30 at 16 45 05" src="https://github.com/woocommerce/woocommerce/assets/3323310/96bd6112-2b13-4a50-802e-4b1fdc116507">

**Comment by nielslange** [comment]
> Yes I had forked the repo and following is what I am getting after running pnpm install . So to solve the provided issue do I need to run the command pnpm --filter='@woocommerce/block-library' watch:build .

Based on your screenshot, it appears that `pnpm install` does not finish. Could you try to delete the current local repo, fork it again, and then run `pnpm install` one more time? 

> as I am unable to know from where can I see this issue in my local env (either by using wampp or something else) . 

I'm afraid, I don't understand what you mean by that. Can you clarify that?

> Also I have installed all the pre-requisites as mentioned in readme file.

You're talking about the prerequisites as listed on https://github.com/woocommerce/woocommerce?tab=readme-ov-file#getting-started, right? What versions have you installed? These are the versions that I'm using on my end:

<img width="524" alt="Screenshot 2023-12-30 at 17 08 06" src="https://github.com/woocommerce/woocommerce/assets/3323310/5341176d-49b5-4372-ac58-0437321b2f4b">

**Comment by niharikamahajan02** [comment]
> Based on your screenshot, it appears that `pnpm install` does not finish. Could you try to delete the current local repo, fork it again, and then run `pnpm install` one more time?
>
ok sure . I'll try once again


> You're talking about the prerequisites as listed on https://github.com/woocommerce/woocommerce?tab=readme-ov-file#getting-started, right? What versions have you installed? These are the versions that I'm using on my end:
> 
yes following are versions at my end
![image](https://github.com/woocommerce/woocommerce/assets/72392580/dbd7fd5e-f0f0-4397-b96a-014aaef07aad)

**Comment by niharikamahajan02** [comment]
@nielslange 
Following is what I am getting again after running pnpm install . Do I also need to have python ?
![image](https://github.com/woocommerce/woocommerce/assets/72392580/380bffe1-7adb-45e2-86e5-cc9606f470a0)
![image](https://github.com/woocommerce/woocommerce/assets/72392580/0805a42f-32ce-43a5-ac66-5812f0320f3e)
![image](https://github.com/woocommerce/woocommerce/assets/72392580/50213b73-6b43-4e53-9384-b11af27d9469)

After cloning the repo in my local system I wrote pnpm install . This is the step which has to be followed or its something else bcoz I am following instructions given in https://github.com/woocommerce/woocommerce?tab=readme-ov-file#getting-started

**Comment by nielslange** [comment]
> [...] Do I also need to have python ?

No, this repo does not require Python. As for the current issue, I'm afraid I cannot assist in this case, as I'm using macOS instead of Windows. Maybe someone, that's using Windows, is able to assist.

**Comment by niharikamahajan02** [comment]
I managed to find why it was not working  , now pnpm install command is finally working ..next I wrote pnpm --filter='@woocommerce/block-library' watch:build comand to work for the above issue but it seems like 'WIREIT_LOGGER' is some kind of env. variable or something else ..if u could tell any prblm 
![image](https://github.com/woocommerce/woocommerce/assets/72392580/18850518-7fe2-417d-befd-bef7283ed307)

**Comment by niharikamahajan02** [comment]
@nielslange does this work?

**Comment by nielslange** [comment]
> @nielslange does this work?

Hello @niharikamahajan02, are you referring to this issue or to #43369?

**Comment by niharikamahajan02** [comment]
> Hello @niharikamahajan02, are you referring to this issue or to #43369?

ya I was referring to #43369 PR that would resolve the above issue.

**Comment by nielslange** [comment]
Thanks for clarifying this, @niharikamahajan02, and thanks for your contribution. 🙌

**Comment by ralucaStan** [comment]
This will be fixed via https://github.com/woocommerce/woocommerce/issues/46948
