### ISSUE TITLE
Need a way to modify the cart subtotal price in the WC Block

### ISSUE THREAD

**Issue by mohammaddanish-cedcoss** [woothemes/woocommerce#42042]
const modifySubtotalPriceFormat = ( defaultValue, extensions, args ) => {
	const isCartContext = args?.context === 'cart';

	if ( ! isCartContext ) {
	    return defaultValue;
	}
	return 'My Price';
};

I am using this code but getting this error
Returned value must include <price/> or Returned value must include default value

Is there any way to modify the full price format without including the default value

**Comment by nielslange** [comment]
Thanks for reaching out, @mohammaddanish-cedcoss. The return value of the `subtotalPriceFormat` filter must contain the substring `<price/>`, which is a placeholder to display the corresponding subtotal price. You can find the documentation and code examples on https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters/cart-line-items.md#subtotalpriceformat.

> Is there any way to modify the full price format without including the default value

May I ask what you are aiming for? How should the expected result look like?

**Comment by mikejolley** [comment]
@mohammaddanish-cedcoss any feedback on the above? Otherwise this issue will be closed.

Thanks

**Comment by opr** [comment]
@mohammaddanish-cedcoss thanks for submitting this issue.

> Is there any way to modify the full price format without including the default value

Right now the answer to this is: no.

As Niels asked above, could you share a screenshot/mockup of what you're trying to achieve, and why you want to hide the price? There might be another solution that works better for your use case.

I'll close this issue as there was no response earlier, however please feel free to reopen it if you can provide the requested information.

Thanks!
