### ISSUE TITLE
Product Gallery: Investigate how we will surface this new block to users

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#42043]
We want to maximize our efforts here by surfacing this block to users. So this issue is to investigate what paths can we take to do that.

Some initial thoughts:

- Block transform: can we allow legacy Product Image Gallery block to transform to the new block?
- Show a notice somewhere in the Single Product Template?
- A big block transform button like how we do with the Classic block transform?

Deliverable:

- Investigate the best way to surface this new block to users. (there can be many different paths).

**Comment by thealexandrelara** [comment]
Considering our decision to release the Beta version of this block, I believe we can safely close this issue. The block will not be included by default in the Single Product template. Merchants can choose to use it by clicking "Transform To" on the Product Gallery Image block or adding it anywhere they wish.

Please reopen this issue if you think there are any other tasks related to this issue that we should address.
