### ISSUE TITLE
[Checkout Block] Improve Local Pickup colors 

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42054]
## Current problem
There are currently a lot of different grays being used, for borders, form fields, text, and backgrounds. To reduce the visual noise we can define a subtle background color for the shipping method hover and active states that aligns with the new color system we’ve created. Any areas that require a background, such as the local pickup address details will use the consistent background color.
<img width="444" alt="Screenshot 2023-11-27 at 17 25 00" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/472261b8-cfc2-4d25-a57d-5fa754e200f6">

## Solution
Rather than using the darker gray for hover states we can define the following variable for universal backgrounds: `$universal-background: rgba 17, 17, 17, .2`

The transparency will allow the hover state to appear on most themes without feeling too heavy-handed.

This update reduces the 2px border on active shipping method selection to 1px, and the background color also appears for the local pickup details area.

Expected result https://www.loom.com/share/78c5c0ec02874077859ee099823a0914?sid=bd1605e8-92db-4043-9828-1ee5b0726186

## New design 

<img width="1708" alt="Checkout clean up - Pickup 2" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/cc075d8c-e8b9-4636-815d-19b38ee569d0">
<img width="1440" alt="Checkout clean up - Pickup" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/a2604b02-3c31-44ca-91e1-52a24a54a3e5">

Figma file: Xcn9ZirCFwU451IQZxMAcb-fi cc @elizaan36

**Comment by elizaan36** [comment]
Thank you for creating the issue! Added the Figma file and specified the hover and active states.
