### ISSUE TITLE
Warning messages using update funtion from TGM Plugin Updater

### ISSUE THREAD

**Issue by BackuPs** [woothemes/woocommerce#42050]
Hi

When using the TGM plugin updater to update plugins that ship with a theme. I get these warning messages because the plugins fires a action hook which then passes by woocommerce BlockPatterns.php

Could you please check in your code for  array exists and type of array in your code so these messages disappear?

Thank you.

Warning: Undefined array key "plugins" in /var/docs/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php on line 254

Warning: foreach() argument must be of type array|object, null given in /var/docs/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php on line 254

**Comment by bobbingwide** [comment]
Same problem with my plugin updater built into oik.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/2474435/297bf4ef-b356-4730-9ef6-f4dcec791248)

I do wonder why block patterns are being prepared on a wp-admin update page.

**Comment by BrianBosma** [comment]
I have those same exact warnings, almost every time the Wordpress auto-update runs at night:

PHP Warning:  Undefined array key "plugins" in /wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php on line 254

PHP Warning:  foreach() argument must be of type array|object, null given in /wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php on line 254

**Comment by albarin** [comment]
Hi, thanks for reporting it!
This issue was recently fixed in https://github.com/woocommerce/woocommerce/commit/7a1d9bfc60197555d2a31ef7894e2ca18f8317d7
