### ISSUE TITLE
Product Gallery: Investigate the Thumbnails editor animation when changing the position setting

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#42061]
## Describe the bug

When changing the `Thumbnails` position from the `Bottom` position to `Left` there's an odd animation:

https://github.com/woocommerce/woocommerce-blocks/assets/905781/da9abfbd-7cf9-49e5-9cba-43d4a4fd759e

This animation comes from Gutenberg. I suspect that it's a result of the `Stack` group block changing into a `Row` and the blocks moving up and down at the same time. Not sure if there's a way to suppress it. 

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Test with thumbnails `Position` set to `bottom` then switch to `left`.
6. Notice the strange animation.

**Comment by roykho** [comment]
Looking into this, it appears we're internally using this method to move blocks to position https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#moveblocktoposition

This method does not have any parameters to remove the animation. There is some JS magic to apply CSS transform to get those animation. So unless we use something else, I am not sure if we can remove them.

**Comment by roykho** [comment]
Based on the above findings, I don't think there is anything we could do for now and it is not a bad user experience by any means so closing this issue for now.
