### ISSUE TITLE
Incompatibility notice: update generic message

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#42072]
**Description:** we display a notice in the editor when at least one extension is marked as incompatible. However, most incompatible extensions aren’t marked as incompatible and there’s no easy path to revert to shortcodes without the notice. We should update the generic notice and include the call to action to switch to shortcodes

<img width="294" alt="Captura de ecrã 2023-11-30, às 18 20 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/a8a10283-4b8a-4eae-a72a-aacacee0e592">

**Acceptance criteria:**
- [ ] Update the copy to: Some extensions don't yet support this block, which may impact the shopper experience. To make sure this feature is right for your store, [review the list of compatible extensions](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-3).
- [ ] Add the button to switch to shortcode and implement the same flow.
- [ ] Replicate this in the Cart page
- [ ] Add a new property to the following events to distinguish when the flow was triggered by the generic notification or the one that outlines the incompatible extensions: wcadmin_switch_to_classic_shortcode_click, wcadmin_switch_to_classic_shortcode_confirm, wcadmin_switch_to_classic_shortcode_undo, wcadmin_switch_to_classic_shortcode_cancel.

**Comment by pmcpinto** [comment]
cc @elizaan36 @jarekmorawski for feedback.

**Comment by elizaan36** [comment]
We already have this one.
<img width="282" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/d1a89d3f-7af2-4e85-848a-2372309b80b3">

Maybe adding the "Switch to classic checkout" button to this notice would make sense.

**Comment by pmcpinto** [comment]
> We already have this one.

@elizaan36 nice catch. I forgot that message. Should we keep that copy? I think it would be helpful to include the "Switch."

**Comment by elizaan36** [comment]
Good question, I think the copy could align more with the more specific notice.

> Some active extensions don't yet support this block, which may impact the shopper experience. _Learn more_
[Switch to classic checkout]

**Comment by ralucaStan** [comment]
So the goal of the ticket is to add the button to the notice and refactor the copy?
![image](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/24ad4a8f-fddd-4f01-a5de-fb96322622bc)

**Comment by pmcpinto** [comment]
Yes. I'll update the issue description.
