### ISSUE TITLE
Product Collection - Offer (recommendation- and archive-oriented) patterns in the collection creation flow

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42085]
### Background
With the Collections coming in https://github.com/woocommerce/woocommerce-blocks/pull/10952 there's an idea to create patterns per Collection.
That's based on the assumption that not every pattern make sense for every Collection.

### Goal
Prepare the list and definition of patterns per Collection. Available Collection:
- New Arrivals
- Top Rated
- Best Selling
- On Sale
- Featured 

Once defined, the new set of issues will be created to implement them

**Comment by manospsyx** [comment]
- How are we going to associate collections with patterns? 

The idea to allow individual collections to be associated with different patterns is neat. How implementable is it? Are there pattern "taxonomies"? In its simplest form, I would imagine having a way to optionally mark a custom collection as a "recommendation" or "catalog" type collection. This would imply that the collection will surface "recommendation" patterns or "catalog" patterns. In its most tedious form, I would imagine being able to programmatically define specific patterns to surface with each collection.

A couple questions around extensibility here:

- Can we allow 3PDs who want to register custom collections to define which patterns they want to surface? 
- Will 3PDs / theme vendors be able to define custom patterns for use with Core and/or their own collections?

**Comment by kmanijak** [comment]
It's in progress but not worth to keep track of it in GitHub. Hence I'm closing this issue.
