### ISSUE TITLE
Combining `type=variation` with `attributes` for Store API `/products` endpoint doesn't work

### ISSUE THREAD

**Issue by jelledruut** [woothemes/woocommerce#42093]
## Describe the bug

The `/products` endpoint accepts the parameter `type=variation`, which returns product variations, instead of products. 

An example request:
`/wp-json/wc/store/v1/products?type=variation&parent=24958&attributes[0][attribute]=pa_size&attributes[0][slug]=44`

However, when combining `type=variation` with the `attributes` parameter, the query becomes incorrect. The example I provided should return all variations that have the product attribute term `pa_size` `44`, with parent product ID `24958`.

However, instead it returns no variations when using the `attributes` parameter in combination with `type=variation`, since the resulting query is incorrect.

[https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md#product-variations](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md#product-variations)
[https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md#list-products](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md#list-products)

## Expected behavior

When using `type=variation` and the `attributes` parameter, it should return all variations that have those attribute terms.

For example, this query would work (for the example URL provided) - since attribute terms linked to variations are stored in the `wp_postmeta` table for variations:

````php
...
'meta_query' => [
    [
        'key' => 'attribute_pa_size',
        'value' => ['44'],
        'compare' => 'IN',
    ],
],
````

While it currently results in this query (which only works for products, not variations):
````php
...
'tax_query' => [
    [
        'taxonomy' => 'pa_size',
        'field' => 'slug',
        'terms' => ['44'],
        'operator' => 'IN',
    ],
],
````

Though an issue that arises is that only the `slug` is stored for variation attribute terms in `wp_postmeta` as `meta_value`, and not the `term_id`, which is supported for the `attributes` parameter.

My knowledge of the internals of WooCommerce isn't good enough to figure out a better solution. E.g. maybe the `wc_product_attributes_lookup` table?

## Screenshots
<img width="411" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/99323745/b88370c4-6a40-4d6d-bb81-9df933791509">

<img width="499" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/99323745/daa27f42-318a-4425-8f67-6e86d33da839">

<img width="375" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/99323745/94dfb6a5-8aa1-47cd-af28-6f719da16ba0">

<img width="309" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/99323745/2ed0d38a-4ea9-4313-b3f1-72c7491f11a4">

<img width="535" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/99323745/02fdf2cc-7e89-41e9-b744-b0f6a44a291a">

### WordPress:

-   WordPress version: 6.4.1
-   WooCommerce version: 8.2.2
-   Site language: EN

**Comment by roykho** [comment]
Thanks for reporting this. The endpoint documentation mentioned indeed seems to suggest it should be possible. We'll have a look at this.
