### ISSUE TITLE
Review payment and shipping options empty states

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#42090]
**Description:** currently, we have two different approaches for the payment and shipping options empty states in the editor, which can create a confusing experience:

Payment: display what the shopper will see in the front-end (shopper-focused)
Shipping: display a prompt to configure shipping options in the admin (merchant-focused)

We should evaluate whether it makes sense to keep this approach or make them more consistent (both merchant-focused)

<img width="1003" alt="Captura de ecrã 2023-11-17, às 07 15 28" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/4c8613ba-5ca0-4e78-a713-6b48de0b7b0e">

**Acceptance criteria:**
TBD

**Comment by pmcpinto** [comment]
cc @elizaan36 for feedback

**Comment by dominique-vias** [comment]
Hi @ralucaStan my initial thought is that I don’t think we need to differentiate the solution already implemented for Shipping. Would you agree?

**Comment by ralucaStan** [comment]
For people who don't have context, the current experience is to show this for both logged in merchants and shoppers.
<img width="547" alt="Screenshot 2024-09-06 at 12 26 08" src="https://github.com/user-attachments/assets/576a0036-45c1-483c-89ad-502e9881f34f">

Like Beau suggested we should improve the experience, and go the extra step for logged-in merchants by changing the message and providing the link to the payments setting text.

**Comment by opr** [comment]
> Hi @ralucaStan my initial thought is that I don’t think we need to differentiate the solution already implemented for Shipping. Would you agree?

I agree @nikkivias, implementing the below just with "shipping options" changed to "payment methods" should be fine, right? The existing notice should be kept for logged-out users.

![image](https://github.com/user-attachments/assets/b5d26467-f10b-4b53-931f-66dac2d0b1a6)
