### ISSUE TITLE
Product Gallery block: Remove Experimental Flag from Product Gallery Block 

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#42095]
**Description:**
The Product Gallery block in our project has been marked as experimental for a while. Now that all the planned tasks are almost complete we need to prepare to have the experimental flag removed. This issue is to track the process of removing the flag and ensuring that the block is officially released.

**Desired Outcome:**
We want to remove the experimental flag from the Product Gallery block and consider it a stable and supported block.

**Acceptance Criteria:**

- The experimental flag has been removed from the Product Gallery block.
- Documentation has been updated to reflect the change (https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- The block is confirmed to work as expected in the project.

**Comment by paaljoachim** [comment]
I look forward to trying out the new Product Gallery block. I am not able to see it Settings -> Advanced -> Features and test out the new block (I assume because it is not experimental any longer). As it would be nice to test out the new block and give additional feedback. Let me know how I can at this time check it out. 

Btw
In Gutenberg one can also use: http://gutenberg.run/ to test out PR's. It would be nice if something similar could also be done with WooCommerce PRs being developed.

**Comment by thealexandrelara** [comment]
> I look forward to trying out the new Product Gallery block. I am not able to see it Settings -> Advanced -> Features and test out the new block (I assume because it is not experimental any longer). As it would be nice to test out the new block and give additional feedback. Let me know how I can at this time check it out.
> 
> Btw In Gutenberg one can also use: http://gutenberg.run/ to test out PR's. It would be nice if something similar could also be done with WooCommerce PRs being developed.

Hey @paaljoachim, I'm really sorry that I missed your message.

Currently, the block is behind an experimental flag, so it's only available in the development build. We'll soon remove the flag and launch a beta version of the block, which will then be available in the production build.

The WooCommerce Blocks repository was recently merged into the WooCommerce monorepo. Once we remove the flag, we expect to launch the block in the next WooCommerce version.

Thank you for your comment and suggestion regarding the Gutenberg tool to test out PRs, I agree it would be a great feature to have. For now, one way to test the block is by cloning the WooCommerce project and using the development build. We'd greatly appreciate any feedback and suggestions you have!

**Comment by paaljoachim** [comment]
Hey @thealexandrelara 

I have earlier been testing Gutenberg using the method outlined here:
https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/
(As I need an easy method to test out PR's be it gutenberg.run or the above method.)

Btw
Add me to the test list of users whom are ready to test out and give feedback to new features that have just been added or features that need extra attention.

**Comment by thealexandrelara** [comment]
> Hey @thealexandrelara
> 
> I have earlier been testing Gutenberg using the method outlined here: https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/ (As I need an easy method to test out PR's be it gutenberg.run or the above method.)
> 
> Btw Add me to the test list of users whom are ready to test out and give feedback to new features that have just been added or features that need extra attention.

Thank you for sharing this! We will soon be releasing the block as Beta, so soon it will be available inside the Single Product template to be tested and your input would be really valuable in this phase. Thank you once again for your readiness to contribute!
