### ISSUE TITLE
Incompatibility flow - instrumentation: add prop to identify the number of incompatible extensions

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#42101]
**Description:** we need an easy way to identify how many extensions are listed in the notification that prompts the user to switch to the shortcode experience. We should introduce an event property in the existing Tracks events to track the number of incompatible extensions displayed in the UI.

![image_720](https://github.com/woocommerce/woocommerce-blocks/assets/3380168/4771a59b-3cae-473a-a80d-2208845d6312)

**Acceptance criteria:**

- [ ] Add an event property called `extension_number` (feel free to pick a more intuitive name) to track the number of incompatible extensions in the following Tracks events: `wcadmin_switch_to_classic_shortcode_click`, `wcadmin_switch_to_classic_shortcode_confirm`, `wcadmin_switch_to_classic_shortcode_undo`, `wcadmin_switch_to_classic_shortcode_cancel`.
- [ ] Bonus: add another event property to track the extensions' name.

**Comment by pmcpinto** [comment]
Is this issue still blocked?

**Comment by nielslange** [comment]
> Is this issue still blocked?

Yes and no, @pmcpinto. Adding the tracking and verifying that it gets called using the code snippet on https://www.npmjs.com/package/@woocommerce/tracks#debugging is no problem. However, as we moved tracking from Woo to Jetpack, we cannot test the PR using [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension), and we cannot test that recorded events show up internally. 

I could finalise this issue and create a separate issue to test that the tracked events show up internally after Jetpack 13.0 has been released, which is [scheduled for January 9, 2024](https://github.com/Automattic/jetpack/milestone/380). Alternatively, we'll await the Jetpack release and then proceed with this issue. To be on the safe side, I'm leaning towards the second approach, and that's the reason I marked this issue as blocked. That said, what are your thoughts on the best approach?

**Comment by pmcpinto** [comment]
Thanks for the clarification! I also agree that the 2nd approach is the best option.

**Comment by nielslange** [comment]
Thanks for confirming this, @pmcpinto. In this case, I'll proceed with this issue after the Jetpack 13.0 release.

**Comment by nielslange** [comment]
@pmcpinto As the Jetpack 13.0 release is online, I picked up this issue and finalised the corresponding PR, which can be found on #42816.

**Comment by pmcpinto** [comment]
Thanks for the heads up!
