### ISSUE TITLE
Gutenberg 17 overrides Checkout styles in the editor

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42110]
## Describe the bug

When Gutenberg 17 is enabled, certain Checkout block styles aren't loading, causing the textareas to show the resize handler, and the Shipping Toggle to lose its styling.

## To reproduce

1. Enable GB and any block theme.
2. Go to the editor, see the missing styles.
3. Disable GB.
4. See the correct styles.

## Screenshots

Expected:
<img width="614" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/08ea72b2-fd64-4d47-ac01-bfbd11398853">

Current:
<img width="605" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/647ba295-0165-4bfc-846f-4593e4d4e901">

### WordPress (please complete the following information):

-   WordPress version: 6.4.1.
-   Gutenberg version (if installed): 17.0.0
-   WooCommerce version: 8.3.0 RC and also 8.2.2
-   WooCommerce Blocks version: whatever is bundled with WooCommerce.
-   Site language: French
-   Any other plugins installed: nothing else.

### Desktop (please complete the following information):

-   OS: MacOS
-   Browser Safari, Arc.

## Additional context

Tested on both TT3 and TT4

**Comment by pmcpinto** [comment]
Nadir, is it worth fixing this, considering that 6.5 is coming soon? Or should we close the issue?

**Comment by pmcpinto** [comment]
> Nadir, is it worth fixing this, considering that 6.5 is coming soon? Or should we close the issue?

@senadir can you confirm if it still makes sense to fix this? Thanks

**Comment by senadir** [comment]
@pmcpinto Yes this issue is still valid, and not limited to a specific version, it happens when you have Gutenberg installed.

**Comment by senadir** [comment]
This was fixed when we updated everything to Block API V3
