### ISSUE TITLE
Update to WooCommerce Sniffs 1.0.0

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42114]
We are currently using WooCommerce Sniffs 0.1.3, which supports up to PHP 8.0. However, the newly released [WooCommerce Sniffs 1.0.0](https://github.com/woocommerce/woocommerce-sniffs/releases/tag/1.0.0), utilizing [WordPress Coding Standards 3.0.0](https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/3.0.0), extends support to PHP 8.2. This upgrade not only enhances PHP compatibility but also aligns us with the latest WordPress and WooCommerce coding best practices.

I propose we upgrade to these newer versions to ensure our codebase remains up-to-date and maintainable. The plan involves evaluating our codebase for compatibility, conducting tests with PHP 8.1 and 8.2, reviewing changes in the new coding standards, and planning necessary code refactoring. This step will position us well for future developments and ensure compliance with the latest coding standards. When updating the dependency, we need to keep an eye on the CI pipeline to ensure that this change does not break existing tests.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce/pull/45533
