### ISSUE TITLE
Local pickup box renders without the correct height in Firefox

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#42111]
In Firefox the Local pickup selector on the Checkout block does not render correctly for a brief moment on load.

<img width="500" src="https://github.com/woocommerce/woocommerce-blocks/assets/5656702/1c2d9c01-ca00-48c6-a4eb-623049799bec" />

Video: https://www.loom.com/share/2fe49da87db84acc846aa728466eb931

The cause is most likely to do with this component rendering before the `getCartData` selector has finished resolution [see a similar issue here](https://github.com/woocommerce/woocommerce-blocks/pull/11714/files#diff-a179bab4f09a902704a5b37694116f9e25d38f621cbae295e0ab3dc2cfe0ab09R86-R103)

As well as addressing the bug, we should look into this behaviour and figure out why Firefox is rendering before the selector finishes resolving, but chrome seems to render _after_ it's done resolving. This may require a fix upstream to address.

**Comment by samueljseay** [comment]
I cannot reproduce this any more in latest Firefox. We did remove the usage of wordpress components for this piece of the UI so that could be the reason.
