### ISSUE TITLE
Rating count of Filter by Rating block is misaligned

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42118]
## Describe the bug

While testing https://github.com/woocommerce/woocommerce-blocks/pull/11672, I noticed that the rating count of the Filter by Rating block is misaligned. This issue is a regression that was introduced due to a combination of woocommerce/woocommerce-blocks#11468 and woocommerce/woocommerce-blocks#11644.

cc: @gigitux 

## To reproduce

1. Create a test page and add the Filter by Rating block.
2. Select the filter in the page editor and select the option `Display product count` in the sidebar:

<img width="279" alt="Screenshot 2023-11-08 at 16 07 36" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/88db1466-1a90-4ca7-bb36-61678e265678">

3. Go to the frontend and add a rating to one of the test products.
4. Open the test page with the Filter by Rating block.
5. See that the rating count is misaligned.

## Expected behavior

The rating count should be vertically centred with the stars.

## Screenshots

<img width="264" alt="Screenshot 2023-11-08 at 16 09 13" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/2e1a1642-07fe-44dc-85f0-337a66a6e161">

**Comment by roykho** [comment]
Is this still an issue on your end? I am looking at the latest trunk and it seems to align correctly for me. I tested in Tsubaki and TT4 theme.

![file.png](https://github.com/woocommerce/woocommerce/assets/2132595/8f7b69d8-2915-4962-8457-47ae6873c3e1)

**Comment by nielslange** [comment]
I created a fresh JN site, and I'm still seeing this issue, @roykho. You can access the site via https://unabashedly-certain-milkshake.jurassic.ninja/products-beta/. I'll DM you the credentials.

**Comment by roykho** [comment]
Leaving a note that my testing was with the beta filters. The issue reported is only with the current non beta filters.
