### ISSUE TITLE
Add custom fields to the store weekly snapshot

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42116]
Once Custom Fields API ships, we want to track what custom fields a store is using and how many of there are. This is to be done either from our codebase via a hook, or directly in core.

**Comment by pmcpinto** [comment]
In an ideal scenario, we should have the following data points:

- Number/name of extensions that create custom fields
- Number of stores using extensions that create custom fields
- Number of checkout views where a custom field was displayed
- Custom field typology (checkout views): type, location, required, content
- Number of product purchases where a custom field was used
- Custom field typology (product purchase): type, location, required, content

**Comment by senadir** [comment]
Okay, so 1 and 2 can be snapshots.
3 and 4 can be done in the shopper events.
5 and 6 is similar to product purchase and will be done in it as well.

**Comment by senadir** [comment]
This should be merged via #44310
