### ISSUE TITLE
Consider renaming `Collection Filters` to `Product Collection Filters`

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#42121]
Raised originally in by @samueljseay  https://github.com/woocommerce/woocommerce-blocks/pull/11476#discussion_r1384448586

> Should this still have the word product in it? i have to admit the vagueness caught me a few times. I think for the way we're organizing the code this would always be just for product data? Not fussed since its still experimental but thought I'd mention it.

**Comment by sunyatasattva** [comment]
I'm adding the `needs feedback` label. When consensus has been reached on this renaming (or if no consensus is required) feel free to remove the label and change the issue name.

**Comment by dinhtungdu** [comment]
What about just `Product Filters`? Then for inner filter blocks:
- `Product Filter: Active Filters`
- `Product Filter: Price`
- `Product Filter: Stock status`
- `Product Filter: Attribute`
- `Product Filter: Rating`
