### ISSUE TITLE
Checkout block: "no shipping options available" shouldn't be the default message for guest checkout

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42124]
With the new checkout block, when a logged out shopper goes to checkout, and hasn't yet entered his shipping details, the message he sees is "no shipping option available", which doesn't really make sense.
Instead, the message shown should be "Add shipping details to view shipping options" or something like that.

<img width="1424" alt="Screenshot 2023-11-06 at 4 12 20 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/c54a4573-e7d3-4d4a-9b4c-d22b8bfa7db2">

**Comment by nielslange** [comment]
Thanks for reaching out, @tomxygen. I was able to reproduce this issue in incognito mode when only regular shipping methods are available. With local pickup enabled, this issue no longer appears. That said, I agree that the wording _"No shipping options available"_ is misleading and should be optimised. I move this issue to our backlog for now. Thanks again for bringing it to our attention.

**Comment by tomxygen** [comment]
thank you @nielslange 
do you have any ETA?

**Comment by pmcpinto** [comment]
@nikkivias do you have a copy suggestion for this use case?

**Comment by dominique-vias** [comment]
Thank you for tagging me.

To keep it short for the Order summary, we can write _Calculated on shipping address_

Does this affect the tax line item too? (Which we would write _Calculated on billing address_)?

Are we also looking to improve the messaging for the shipping options area?

![image](https://github.com/woocommerce/woocommerce/assets/99638528/88afd00b-1053-4f47-8bcd-1030dba97a1c)

**Comment by pmcpinto** [comment]
> Does this affect the tax line item too? (Which we would write Calculated on billing address)?

I think so.

> Are we also looking to improve the messaging for the shipping options area?

Yes. We should make it consistent.

**Comment by ralucaStan** [comment]
We need to be consistent with what we show in the Cart block. 
I made some comments on this issue  https://github.com/woocommerce/woocommerce/issues/42422 that should be considered before making a decision on this ticket.

**Comment by ResponsiveFlow** [comment]
Thanks @ralucaStan 

I saw your comment on #42422 

> My proposal is to align the states of the Order summary shipping section in all cases:
> Empty addresses
> Cart block: Show link to add "Add an address for shipping options" that shows the Shipping calculator text
> Checkout block: Add the same text, maybe in a notice? @elizaan36
> Address outside of shipping areas:
> Cart block: keep as is: show the address and warning notice
> Checkout block: align with the Cart and show the address and warning notice

I completely agree on that.

**Comment by ralucaStan** [comment]
Closing, this will be handled in https://github.com/woocommerce/woocommerce/issues/46951
