### ISSUE TITLE
Add support for attributes in custom fields API

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42137]
Initially this issue only included adding support for a regex (pattern) attribute, but over thinking about it, there are several useful rules that aren't only the pattern one, like maxlegnth and such, so I think it would make sense to support adding all field attribute.

Ideally, values should be cross-compatible with Android and iOS, [see this table.](https://chat.openai.com/share/adb0150e-2bfd-49d4-9b79-fe5c5a869697)

**Comment by ralucaStan** [comment]
Highlighting this comment p3btAN-2sq-p2#comment-19436

**Comment by opr** [comment]
I've started with this list of attributes:

```php
$allowed_attributes       = array(
				'placeholder',
				'maxLength',
				'disabled',
				'readOnly',
				'pattern',
			);
```

When you say

> I think it would make sense to support adding all field attribute.

were you thinking of just allowing all/most attributes onto the fields? I don't think we should do that and should only allow hand-picked ones. If a use-case arrives where it makes sense to add a new attribute we can add it, or we could make this list filterable.

For now I'll open the PR with this setup but do let me know your thoughts, it can be easily changed.

**Comment by senadir** [comment]
Hey Thomas! We should handpick in a sense that we remove things that doesn't make sense, like `focus` and `size`, but leave the others fine.

The list you added is a good start, can you also move `autocapitalize` and `autocomplete` to it? so that we simplify the main registration body?

**Comment by opr** [comment]
> The list you added is a good start, can you also move autocapitalize and autocomplete to it? so that we simplify the main registration body?

Yes will do.

It also make sense to allow `aria-` attributes onto the field, but I am hesitant to hand-pick the list of allowed ones. Instead I would allow them all in case there are use-cases we didn't foresee.

**Comment by senadir** [comment]
Do we also allow `data-` attributes?

**Comment by opr** [comment]
Yes, they should.

I noticed that these additional attributes can't be applied to `select` fields due to the `ComboboxControl` we're using. It doesn't accept additional props, so we can only accept additional attributes on tex or for checkbox inputs.

Add this to the list of reasons that we need to switch to our own implementation of `Combobox`.
