### ISSUE TITLE
Mini-cart block doesn't apply filters on quantity field

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#42158]
## Describe the bug

Minimum/maximum/step control plugins for item quantity use filters, like `woocommerce_loop_add_to_cart_args`, `woocommerce_quantity_input_args`, `woocommerce_quantity_input_step`, `woocommerce_quantity_input_min`, `woocommerce_quantity_input_max` and `woocommerce_update_cart_validation` to render qantity fields with the correct markup and/or validate their input.

The mini-cart block seems to be ignoring these filters.

## To reproduce

1. Go to https://pacificsprings.com.au/product/15litre-spring-water-bottle/ - the default quantity is 4
2. Try to reduce it - it's impossible, even with JS disabled
3. Click "Add to Cart"
4. Go back to the product page and open the mini-cart widget - the quantity is >= 4
6. Try to reduce it - it's possible all the way down to 1

## Expected behavior

The quantity field should have the `min` attribute set to a value filtered by `woocommerce_quantity_input_min`, instead of 1.

When the quantity changes to a number lower than the minimum, there should be a validation error from `woocommerce_update_cart_validation`.

### WordPress (please complete the following information):

-   WordPress version: 6.2.3
-   Gutenberg version (if installed):
-   WooCommerce version: 8.2.111.3.1[e.g. 7.0.0]
-   Site language: EN-AU
-   Any other plugins installed: [Min Max Control – Min Max Quantity & Step Control for WooCommerce](https://wordpress.org/plugins/woo-min-max-quantity-step-control-single/)

**Comment by albarin** [comment]
Hi @galbaras, thanks a lot for reporting this! 
We have been able to reproduce the issue you mentioned, we'll add it to our backlog.
Thanks! 🙌

**Comment by JUVOJustin** [comment]
Is this the case for the rest api in general? When using the cart block, the errors are visually added, but changing amounts is not blocked. The cart updates always went through despite the error shown. 

`woocommerce_update_cart_validation` <- not triggered during quantity update in cart block
`woocommerce_check_cart_items` <- Triggered and my logic is able to add error notices, but they do not prevent further logic

Thanks to the url @galbaras provided i could check and it is the same endpoint used for the mini cart and normal cart. I think this i related.

**Comment by mikejolley** [comment]
@senadir This is under our responsibility now and concerns extensibility. Is it correct that we won't support these filters in favour of the parameters that come back from the Store API? (like on cart page)

**Comment by opr** [comment]
> This is under our responsibility now and concerns extensibility. Is it correct that we won't support these filters in favour of the parameters that come back from the Store API? (like on cart page)

Yes we have the store API args now to affect the quantity limits.

https://github.com/woocommerce/woocommerce/blob/4199533688c7200b00f87110cb5a34e95e40c852/plugins/woocommerce-blocks/bin/hook-docs/data/filters.json#L1423

I just tested and can confirm these are working in the mini cart block.

**Comment by galbaras** [comment]
I'm confused. Is this a new thing that solves the problem or not? Is there anything I need to do for my site to work as expected?

**Comment by opr** [comment]
> I'm confused. Is this a new thing that solves the problem or not?

The hooks I've linked to are used to to change the quantity limits of cart items when they are returned as part of a Store API response. This is what drives the blocks-based Cart and Checkout.

> Is there anything I need to do for my site to work as expected?

Yep, you'll need to add code that uses these hooks. The code you'll need to add to change these quantities will probably look very similar to what's already in place for the shortcode hooks, however the arguments to these new hooks are:

| Argument | Type | Description |
| -------- | ---- | ----------- |
| $value | mixed | The value being filtered. |
| $product | \WC_Product | The product object. |
| $cart_item | array, null | The cart item if the product exists in the cart, or null. |

As mentioned in the docs, the suffix of the hook will vary depending on the value being filtered. For example, minimum, maximum, multiple_of, editable.

e.g.

- `woocommerce_store_api_product_quantity_minimum`
- `woocommerce_store_api_product_quantity_maximum`
- `woocommerce_store_api_product_quantity_multiple_of`
- `woocommerce_store_api_product_quantity_editable`

**Comment by galbaras** [comment]
I really don't see why you wouldn't apply the existing filter (as well), at least for backward compatibility, and to save extension developers the headache. Seems almost trivial to me.

**Comment by opr** [comment]
As I understand it, those filters you mentioned in the initial post specifically control the limits on the _input boxes_ for the cart items' quantities. The ones I mentioned control quantity limits in the Store API, which is what drives the Cart/Checkout blocks. If we solely relied on the old filters to control the input boxes only, then users would be able to change the quantities of items in the cart by making requests to the store API directly bypassing the input limitations.

So, if we did implement the old filter as well, like you suggest, it would not really be a useful fix for stores as it could easily be circumvented if the shopper wanted to.

**Comment by galbaras** [comment]
I honestly don't know how all this works. All I know is that plugins out there are now providing an inconsistent experience between the mini cart and the regular cart, and my clients are having some issues with this, because their site visitors can bypass the limits by using the mini cart.

**Comment by catwithlover** [comment]
I think plugin developer can limit user update product quantitiy in block cart by two hook: 

- woocommerce_store_api_cart_errors
- woocommerce_store_api_product_quantity_limit

You can use "woocommerce_store_api_cart_errors" to check new cart content, then update product quantity if user update quantitiy more than max limit, then add error message to notice user. And develper can use "woocommerce_store_api_product_quantity_limit" to offer frontend script max limit of input, prevent user update quantity exceed max limit.

**Comment by galbaras** [comment]
> For example, minimum, maximum, multiple_of, editable.

@opr Is there a full list of these somewhere?

**Comment by opr** [comment]
Hi @galbaras - yep there is it's here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/bin/hook-docs/data/filters.json hope that helps 🙂

**Comment by galbaras** [comment]
That file also uses the phrase "for example", but I couldn't find a list of values for `$value`. Where does the code get this information to apply the filter?

**Comment by opr** [comment]
> That file also uses the phrase "for example", but I couldn't find a list of values for `$value`. Where does the code get this information to apply the filter?

I think "for example" is bad phrasing in the documentation there, the "examples" listed there is the set of values it can be.

Here is the code where those filters are called:

https://github.com/woocommerce/woocommerce/blob/d1498d45f2804eede99538d13717c4e2cf602308/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L33-L36

**Comment by codersaiful** [comment]
Thanks a lot. It's working. Sample code:
```php
add_filter('woocommerce_store_api_product_quantity_minimum','return_20_for_now', 10, 2);
add_filter('woocommerce_store_api_product_quantity_multiple_of','return_20_for_now', 10, 2);
function return_20_for_now($qty, $cartItemData){
    $product_id = $cartItemData->get_id();
    return 20;
}
```
Thanks to @opr

**Comment by galbaras** [comment]
FYI, I don't consider the use of another set of filters to be a good solution. WooCommerce's handling of carts should be consistent, regardless of presentation, so I still think the old filters should take effect. I can't actually think of a use case for separate filters.
