### ISSUE TITLE
LocalWP, cart block and widget failing to translate?

### ISSUE THREAD

**Issue by madjedo** [woothemes/woocommerce#42163]
What Issue or Error Are You Experiencing?

I’m currently encountering an issue with my newly installed WordPress + WooCommerce setup. I am building the site currently on a localhost (**localwp**) and using a basic theme and configured for the Swedish language. Despite having all translations updated, I’ve noticed that when I utilize the cart block and cart widget, certain elements remain in English, failing to get translated as expected.

Replicating the Issue
To replicate the problem, you can follow these steps:

Begin by setting up a fresh WooCommerce site in a localWP environment.
Add the cart block to the cart page.
Change site language from English to Swedish (or any other language).
Proceed to the front-end, and add items to your cart.
Visit the cart page.

Background and Potential Solutions
It’s worth noting that I’ve already reached out to WooCommerce support regarding this issue. However, I have previously encountered a similar problem on another website I worked on. Strangely, the issue resolved itself when I later published the site from my local WordPress environment to a live host. After this transition, the cart block correctly displayed in the site’s chosen language.

It appears that there may be a specific issue related to the local localWP environment that is preventing WooCommerce from fully translating the cart and checkout blocks. If anyone has encountered a similar problem or has insights into resolving this issue, your assistance would be greatly appreciated.

Link to screenshot: https://ibb.co/SQRj7M2
Link to screenshot 2: https://ibb.co/xsywpTP

**Comment by mikejolley** [comment]
It seems to be working with the blocks extension active:

![Screenshot 2023-10-23 at 11 12 26](https://github.com/woocommerce/woocommerce-blocks/assets/90977/cf4ad83b-5554-47f3-9e74-6002a023e103)

Sometimes it just takes an update using this under Admin > Dashboard > Updates:

![Screenshot 2023-10-23 at 11 09 52](https://github.com/woocommerce/woocommerce-blocks/assets/90977/294938ca-721e-42ce-9861-91543b34ae1f)

However I was missing the translations with just Woo core active. This will need further investigation.

**Comment by mikejolley** [comment]
This should be fixed in the next core release. The names of some of the JS files have changed so translations are "missing".

If you run the WooCommerce Blocks feature plugin, its not affected by this issue.

**Comment by madjedo** [comment]
Actually I am using the blocks plugin.

My localwp setup is like this:

PHP version: 8.1.23
Database: MySQL 8.0.16
nginx

On the wordpress install I am using a classic theme (very basic at the moment). Did you test with a classic theme?

And like I said earlier, I do remember experiencing this before, and the issue resolved itself when I later published the site from my local WordPress environment to a live host.

**Comment by mikejolley** [comment]
Theme does not affect these strings. I'm using Twenty Twenty Three. Did you try the dashboard update I screenshot?

**Comment by madjedo** [comment]
Yes I have, says I have latest translations. I have also downloaded the latest stable language package from https://translate.wordpress.org/locale/sv/default/wp-plugins/woocommerce/. Placed this in \wp-content\languages\woocommerce.

Also did I say that the cart block is properly translated in the back-end (gutenberg editor) but not front-end?

Could you test with TT1 theme?

**Comment by mikejolley** [comment]
![Screenshot 2023-10-24 at 10 47 47](https://github.com/woocommerce/woocommerce-blocks/assets/90977/2171026e-11da-4e84-91dc-0cf26d5240f9)

TT1, blocks plugin active, editor and front identical. As I said, it breaks with those strings when using core but not the feature plugin, because the translations for core are not up to date yet.

**Comment by madjedo** [comment]
> ![Screenshot 2023-10-24 at 10 47 47](https://user-images.githubusercontent.com/90977/277618929-2171026e-11da-4e84-91dc-0cf26d5240f9.png)
> 
> TT1, blocks plugin active, editor and front identical. As I said, it breaks with those strings when using core but not the feature plugin, because the translations for core are not up to date yet.

I will re-report if issue still persists after the core update. Thank you for your assistance.

**Comment by senadir** [comment]
Hey! Do let us know if you're still seeing this problem. It actually happens when you're running WooCommerce Blocks, and that language is not fully translated, we would default to translation from WooCommerce. The strings would sometimes up to a month to reach WooCommerce files and be translated.

This should be permanently fixed around next year.

**Comment by madjedo** [comment]
Hello @senadir , thank you for replying.

I am still having the same issues when using the cart block in my local environment (local wp). The proof in the pudding:

**Screenshot from local server (localWP):**

![screen_local](https://github.com/woocommerce/woocommerce-blocks/assets/25926337/0f09a942-a5c7-46f9-8c8e-bf0d79846b06)

**Screenshot from live server:**

![screen_live](https://github.com/woocommerce/woocommerce-blocks/assets/25926337/054ae5cc-3409-4a24-9215-dc50778d7e98)

I don't know why this is happening. But I remember having the same issue in a previous site I was building. Maybe it's specific to my localwp environment. But to my knowledge I haven't done anything to my local environment.

**Comment by senadir** [comment]
I'm still unable to reproduce this locally on LocalWP.

After switching languages, I made sure to install them:
<img width="240" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/807e94f6-f02c-4271-b938-0ea479376092">

I tested with a block theme and a classic theme, running latest WooCommerce and WooCommerce Blocks (with it enabled and disabled):
<img width="1125" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/fcaa1978-07c4-4d58-ab59-5aba196fa911">

<img width="857" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/175ac24f-e13c-4c84-a0b4-0411f2533592">

**Comment by mikejolley** [comment]
Same here. I think since this is not reproducible our side and doesn't affect the production/live build it doesn't warrant further investigation, but if you do find the cause please let us know.

Thanks
