### ISSUE TITLE
TT4: List style in the editor override Search List Control style

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#42174]
## To reproduce

1. Add block using Search List Control like Filter by Attribute, Hand-picked Products to a page.
2. See the bullet

## Expected behavior

List bullet shouldn't visible in Search List Control.

## Screenshots

<img width="468" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/ec2eeda5-2fc6-47b5-a895-ec6aec15f172">

<img src="https://user-images.githubusercontent.com/16707866/276137960-92cb16b8-2565-4378-9061-d264b9b76891.png">

## Additional context

Relates woocommerce/woocommerce-blocks#11299 woocommerce/woocommerce-blocks#11302

**Comment by albarin** [comment]
This was fixed by https://github.com/woocommerce/woocommerce-blocks/pull/11444
I'm no longer able to reproduce.
