### ISSUE TITLE
Product Collection block: Display less numbers at pagination or choose how many to display

### ISSUE THREAD

**Issue by gfarma** [woothemes/woocommerce#42193]
## Is your feature request related to a problem? Please describe.
I think the current display of numbers at pagination is a bit confusing. 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/aba49aa7-924e-4ac4-9aa6-b58674ca3f57)
5 numbers maybe are too many.

## Describe the solution you'd like
I think something like this is better
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/faa99788-61bd-4da0-9662-de74599bf805)

## Describe alternatives you've considered
Or maybe to let the user choose what type to display front end.

## Additional context
Btw with the current style at mobiles sometimes the pagination block needs 3 rows to diplay.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/5d1bb840-fce5-4b4e-8ef2-4d06aeeee58d)

**Comment by kmanijak** [comment]
Hi @gfarma!

Thanks for taking the time and raising this issue!

> I think the current display of numbers at pagination is a bit confusing. 5 numbers maybe are too many.

I like this suggestion and we may take a look into that at some point. But please keep in mind, Product Collection uses the Query Pagination block from Gutenberg ([block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/query-pagination-numbers)). That means it requires contribution to and acceptance from Gutenberg as it would influence Query Loop block as well.

I'll keep this issue in our backlog but please be aware we have limited capacity and don’t be alarmed if you don’t see any activity on this issue for a while.

You may also raise the issue in the [Gutenberg repository ](https://github.com/WordPress/gutenberg/tree/trunk).

> Btw with the current style at mobiles sometimes the pagination block needs 3 rows to display.

There's "Allow to wrap to multiple lines" option that you can disable in Pagination block's Inspector Controls:
<img width="285" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/4e93a3f9-9b8a-4f9f-881b-5a2bb0c7aa45">

But I must agree even then it doesn't look great on mobile:
<img width="385" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/f7c30d73-0c22-4444-9bd2-debef280201a">

**Comment by gfarma** [comment]
Hi @kmanijak, thanks for the response. FYI I raised the same issue here https://github.com/WordPress/gutenberg/issues/55146

**Comment by kmanijak** [comment]
This has been addressed in Gutenberg: https://github.com/WordPress/gutenberg/issues/55146. Closing.
