### ISSUE TITLE
Product Collection block: Allow top/bottom pagination blocks to be added

### ISSUE THREAD

**Issue by gfarma** [woothemes/woocommerce#42194]
## Is your feature request related to a problem? Please describe.
Currently you are able to have 1 pagination block. But sometimes it is a good ux to have 1 at the top and 1 at the bottom.

## Describe the solution you'd like
It could be nice to have 2 pagination blocks inside the same product collection block.

## Additional context
It is nice for the users that are familiar with your site and they want to browse it quickly (top pagination). And for the ones that browsing normally the bottom is needed. So I think 2 will be great.

**Comment by kmanijak** [comment]
Hi @gfarma !

Thanks for raising this! It seems like a bug.

As I mentioned in https://github.com/woocommerce/woocommerce-blocks/issues/11154 we're reusing Gutenberg's Query Pagination block. I compared the behaviours with Query Loop block and it's possible to add more than one Pagination blocks to Query Loop and Products (Beta) block, but it's impossible to do in Product Collection.

Hence I consider it a bug and add it to our backlog. Please follow this issue for further updates! 🙌
