### ISSUE TITLE
Mini Cart template part isn't visible on the 11.2.0 release

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#42199]
## Describe the bug

A user reports that the Mini Cart Template Part isn't available on the 11.2.0 release.

## To reproduce

*Ensure that you are using WooCommerce Blocks 11.2.0*

1. Open the Site Editor.
2. Click on Pattern.
3. Check in the template-parts section the Mini Cart template part.
4. The template part is not visible.

## Expected behavior

The Mini Cart template part should be visible.

## Screenshots

In this video, you can check that:

- the Mini Cart template part is visible when ONLY WooCommerce Core is visible.
- the Mini Cart template part is not visible when WooCommerce Blocks is installed.

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/4a2f8856-69d9-4660-baa7-3da8447bc9df

### WordPress (please complete the following information):

-   WordPress version: [e.g. 5.9]
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by gigitux** [comment]
If I generate a production build (`npm run package-plugin:deploy`), I’m able to replicate it with the trunk codebase.

**Comment by tjcafferkey** [comment]
I tested this in the following env:

WP 6.3.1
WC: 8.1.1
WCB: 11.2.0
PHP version: 8.0

(Same versions as the video)

**WooCommerce Blocks enabled**: Mini Cart is visible under Patterns > Template Parts
**WooCommerce Blocks disabled**: Same as the above. Still available.

I also then did a build of WooCommerce Blocks `trunk` (11.3.0-dev) and I was still unable to replicate this issue. Mini Cart was still present under Patterns > Template Parts.

**Comment by gigitux** [comment]
It seems that the issue is replicable only on a specific configuration that we still haven't figured out. The problem can easily be replicable on https://tastewp.com/ generating a temporary website.

With only WooCommerce Core installed, the Mini Cart template is visible under Patterns > Template Parts.
With WooCommerce Blocks installed, the Mini Cart isn't visible.

**Comment by mikejolley** [comment]
Closing this as the feature plugin won't be updated further so as long as it works in core, we should be ok!
