### ISSUE TITLE
Product Collection: Reorganize Inspector Controls to improve usability

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42206]
### Background

There's more and more settings available in Inspector Controls. To increase usability they should be reorganized into tabs as per designs:

### Designs
Left: Current
Right: Design
![image](https://github.com/woocommerce/woocommerce-blocks/assets/20098064/42d6fb74-5e49-46f7-975f-657446ae82a1)

### Goal:
Split Inspector Controls into tabs as per designs. For now they can be just two tabs but explore possibility of adding custom ones.

**Comment by manospsyx** [comment]
A dedicated Filters/Rules tab makes sense when filters and collection options are optional, which is true for most collection types other than the Custom Collection. The Custom Collection type must guide/onboard/allow users to choose filters and select an order-by rule. Something to think about if we take this path.

**Comment by kmanijak** [comment]
Closing as the designs are going to be changed. The new issue will be created once confirmed.
