### ISSUE TITLE
Pagination block > padding conconsistencies (Editor vs Front) & missing padding/margin settings

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#42204]
## Describe the bug

The padding is different between Editor and Front view for the new Pagination Block

## To reproduce

1. Use the Product Collection Query (ex: from Product Catalog Template)
2. Set background on Pagination block to see how the padding 
3. Observe the Editor view vs Front View Pagination block : 
   * it is not centered on front, bottom padding is more important

NB : we can also here see that the View Product button color is not the same also, but that's another issue :-)

## Expected behavior

Must be aligned
There are also no margin/padding settings on this block, neither on Product Collection Block

## Screenshots

**On Front**

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/dbb47e4d-d436-49bf-97ae-e83a332b4640)

**From Editor**

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/a057cc8c-d770-4f41-b84e-9fe19d0ce06a)

**The block's settings are poor**

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/da6f7df0-46fa-4f60-8a87-0c5e387387da)

## Environment

- WP 6.3.1
- Woo 8.1.1
- Woo Blocks 11.1.0
- Gutenberg 16.6.0
- TT3 theme

**Comment by roykho** [comment]
Hi @Marc-pi - thanks for raising this issue. We'll have a look.

**Comment by tjcafferkey** [comment]
Since the pagination block is from Gutenberg I have a draft PR for this here https://github.com/WordPress/gutenberg/pull/64874 but there remains a specificity issue which I've commented [here](https://github.com/WordPress/gutenberg/pull/64874#issuecomment-2317102436) if anyone's any suggestions.

**Comment by Marc-pi** [comment]
thx for this PR, waiting to be valided in GB

**Comment by tjcafferkey** [comment]
For reference the block settings issue raised here is being discussed/addressed in this issue https://github.com/WordPress/gutenberg/issues/43248 but since my GB has been accepted and merged it does fix the inconsistent margin/padding issue.
