### ISSUE TITLE
Mini Cart: wrong redirected when clicking "Edit Mini-Cart Drawer Template"

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42210]
### Steps to reproduce

1. Go to Editor
2. Add Mini Cart block
3. In the Inspector Controls click "Edit Mini-Cart Drawer template"

**Expected:** You're redirected to Mini Cart template edit page
<img width="1131" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/5162e32b-7df6-4889-8775-64f1ee3e4c04">

**Actual:** There's redirect to some weird state as on the screenshot:
<img width="995" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/69fac0fd-5ab1-416f-a3b5-aeb9704ff4cc">

### Additional context
The URI is defined in [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/MiniCart.php#L179), may be related to escaping.

**Comment by mikejolley** [comment]
I just retested this on trunk and I had the expected result.
