### ISSUE TITLE
Product Gallery - Full view mode: Create a default template part 

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#42217]
With woocommerce/woocommerce-blocks#10823, we introduced a new template part to allow merchants to customize the Product Gallery in full-view mode.  We need to work on a polished default version.

Futhermore, there is some polishing to do the Style (copy-pasted) from: https://github.com/woocommerce/woocommerce-blocks/pull/10947#pullrequestreview-1627634286):

### Padding and Thumbnails block on mobile sizes

When using the tablet view, the padding is missing at the top. For the mobile view, there is a lack of padding at the top and at the bottom, and it seems there is an excessive padding at the sides.

Regarding the thumbnails they are occupying too much space on these smaller screens, but I believe it would be better to address this in a separate PR, probably the solution would be to move the thumbnails block to the bottom of the Large Image block when on mobile, what do you think?

| Laptop | Tablet | iPhone SE |
|--------|--------|--------|
| <img width="1026" alt="CleanShot 2023-09-14 at 17 07 20@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/20469356/b55a2365-efa5-41e6-bf9e-9c1f41b8c4f8"> | <img width="770" alt="CleanShot 2023-09-14 at 17 08 21@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/20469356/02d6fc5f-171c-4419-aa03-de59ca94b6ef"> | <img width="376" alt="CleanShot 2023-09-14 at 17 09 29@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/20469356/3b6f7177-40f5-4914-bf9f-b9f713d8af3c"> | 

### Blank space

I'm using a 5k monitor and it seems there is too much blank space around the block:

<img width="2025" alt="CleanShot 2023-09-14 at 17 36 27@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/20469356/baaac38c-0442-40ef-9831-c750aac3ca48">

I was looking how Amazon handled this scenario, and it seems that basically they make the image occupy 100% of the dialog height and also center the image:
<img width="2021" alt="CleanShot 2023-09-14 at 17 39 27@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/20469356/32f6e7bc-bb54-4017-8ed6-bc5e141c7c5f">

**Comment by danieldudzic** [comment]
With https://github.com/woocommerce/woocommerce/pull/42797 merged, this issue is no longer relevant for this phase. The Pop-up template part will receive dedicated attention as part of a broader redesign effort.
