### ISSUE TITLE
Add a high-level overview documenting the steps needed to extend WooCommerce Blocks

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#42263]
We need a high level document or set of documents outlining the whole flow of extending WC Blocks, specifically we need to document the following:

- The build processes required, we should provide examples based on our `webpack.config.js` and explain in detail what steps _we_ take for code splitting and aliasing externals etc.
- Explain our `frontend.js` file and how it works (used to replace blocks with React components) - ensure developers understand what will happen when they use `registerCheckoutBlock` and when they should/shouldn't use it.
- Add examples of the correct way to use `IntegrationInterface`. Be sure we explain the role of `IntegrationInterface` and how it works in the Cart/Checkout blocks lifecycle. Explain when things are run, and show examples of registering scripts to ensure they’re enqueued at the right time.
- ~Explain what the asset data registry is and what is it used for. Show an example of adding data to the registry and how a front-end JS file can get that data (using `window.wc.wcSettings.getSetting`)~ - solved in https://github.com/woocommerce/woocommerce/pull/53512

**Comment by opr** [comment]
Please review https://github.com/woocommerce/woocommerce/issues/42956 when working on this issue.

**Comment by ralucaStan** [comment]
This should be worked on as part of the developer documentation effort with a focus on the checkout flow, and the shift towards modern block-based development. pdzGYk-1AJ-p2

**Comment by opr** [comment]
> The build processes required, we should provide examples based on our webpack.config.js and explain in detail what steps we take for code splitting and aliasing externals etc.

Is this actually useful? Our webpack config is very customised and complex, I doubt developers would get any benefit from us describing how it works.

**Comment by ralucaStan** [comment]
If I remember corectly this request was more internally driven. So I think we can remove it from that epic.

**Comment by leewillis77** [comment]
@opr I'm tracking this as I think it was raised at least in part of the back of some Slack discussions (now expired unfortunately) that we had when looking at block development. My need wasn't necessarily to document *your* process, but rather how the 'commonly' needed webpack configs can be achieved for those who perhaps aren't webpack experts. Particular issues we hit:

- How to configure & use WooCommerceDependencyExtractionWebpackPlugin
- How to correctly import Woo components
- How to handle de-duping where (for example) you might want to access a single data-store in multiple blocks
