### ISSUE TITLE
Extensibility documentation improvements

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#42264]
This epic will track the issues relating to improving documentation for extensibility.

**Comment by ralucaStan** [comment]
closing this; documentation tickets would be handled individually

**Comment by ralucaStan** [comment]
closing this, open tickets can be

**Comment by opr** [comment]
> closing this; documentation tickets would be handled individually

No problem, think this was the epic Zenhub created, which is why it is empty for us now!

**Comment by ralucaStan** [comment]
Yes, that's also a reason for closing this.
