### ISSUE TITLE
Product Collection - remove the code that enables automatic migration

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42270]
**Issue repurposed**

We won't be enabling automatic migration hence it's worth to remove the code that covers that functionality to decrease a tech debt.

**Previous description:**
After allowing Product Collection block to be used (https://github.com/woocommerce/woocommerce-blocks/issues/10430), we should enable automatic migration from Products (Beta) block to Product Collection block couple of WC Blocks versions later.

That includes:
- write E2E tests covering the migration
- enable automatic migration https://github.com/woocommerce/woocommerce-blocks/pull/10267/files#diff-e9517b2fd3bcc6d45a42d1f2eea15b221e8d7285a41c4f3df6fa2eb8db2de3acR6
- if migration was not reverted, don't include Products (Beta) block in the inserter

**Comment by Marc-pi** [comment]
yep, that would be cool. For now, we have to edit our templates each by each
but there's a need to enhance the block's options, there are few at this time

**Comment by kmanijak** [comment]
> yep, that would be cool.

Thanks for the feedback @Marc-pi! The idea is to gather some early feedback about Product Collection block before enabling auto migration.

> but there's a need to enhance the block's options, there are few at this time

Do you mind providing more details? Do you mean Product Collection block? What enhancements would you like to see? Your feedback is valuable to us so we can make the block better! :)

cc: @imanish003 for visibility 🙌

**Comment by Marc-pi** [comment]
yep, 
* add product type as option https://github.com/woocommerce/woocommerce/issues/42213
* display out of stock badge https://github.com/woocommerce/woocommerce/issues/42621
* dynamic filter's : playing yesterday with filter blocks and product collection, i stuck to this need https://github.com/woocommerce/woocommerce-blocks/issues/10985#issuecomment-1722872497 (new Collection Filter block used in conjunction with the Product Collection query block)
* price display type also https://github.com/woocommerce/woocommerce/issues/42504 (ex/incl VAT), can be usefull in BtoB context

**Comment by kmanijak** [comment]
We agreed not to enable automatic migration, while manual one is still available.

I'm repurposing this issue into a removal of a code responsible for automatic migration.
