### ISSUE TITLE
Convert `editor-block.js` to `editor-block.tsx` and replace propTypes with TypeScript definitions

### ISSUE THREAD

**Issue by hritikchaudhary** [woothemes/woocommerce#42294]
## Problem
[assets/js/blocks/reviews/editor-block.js](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/reviews/editor-block.js) is a JS file and uses propTypes definitions.

## Expected outcome
Convert the file from editor-block.js to editor-block.tsx.
Replace propTypes with TypeScript definitions.

**Comment by hritikchaudhary** [comment]
@nielslange  Can you please add it to woocommerce/woocommerce#42364

**Comment by opr** [comment]
Hi @hritikchaudhary  thank you - I have added this to woocommerce/woocommerce#42364!
