### ISSUE TITLE
improve styling for quantity selector and variation - single product template

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42299]
The blockified single product template should get a styled quantity selector.

There should be a + and – symbol to allow shoppers to edit the quantity added to the cart and to allow merchants to use quantity discounts.

Also, a better styling for variation selector is needed.
I see that something like that was included in the WooCommerce Blocks Roadmap Update – Q1/Q2 – 2022 but never implemented 

https://developer.woocommerce.com/2022/04/11/woocommerce-blocks-roadmap-update-q1-q2-2022/

**Comment by nefeline** [comment]
Hi there @tomxygen ! Thanks for reaching out to us. Regarding:

> There should be a + and – symbol to allow shoppers to edit the quantity added to the cart and to allow merchants to use quantity discounts.

That's a great suggestion; in fact, we already have the designs for modernizing not only the quantity selector, but the add-to-cart button for the single product template as well. We still don't have an estimate of when we will be working on this project, but I'm moving this issue to our backlog so we can update it as soon as we start making progress.

**Comment by Marc-pi** [comment]
yep, we need a -/+ quantity selector with 2 buttons

Actually there is only a simplified one, with default value to 0

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/bf8f99b5-714a-4a6a-ae65-1da5dbd4978b)


The need is to be able to choose between the compact and improved one, and set the default value

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/5224ed5a-4d1d-44fa-ad7a-8c8995d65e84)

**Comment by Marc-pi** [comment]
* it's already in the mini-cart >must not be difficult to add the feature in simple product template (add to cart with options), as ... option, in the new paradigm (blocks)
* it is documented there https://github.com/woocommerce/woocommerce-blocks/pull/5406 (for now > see https://github.com/woocommerce/woocommerce/issues/42601)
* for now, there are also display issues on mobile for the actual standard "collapsed" quantity selector : https://github.com/woocommerce/woocommerce/issues/42205 >> it has to be improved as well
;-)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/2747507e-cb4b-4906-9f96-35d6a21b6580)

**Comment by Marc-pi** [comment]
One alternative can be @nielslange plugin https://fr.wordpress.org/plugins/smntcs-woocommerce-quantity-buttons/
we have to take care in case of grouped products display.

**Comment by jarekmorawski** [comment]
Everything looks good to me. No further changes are needed at this stage. Well done, Luigi!

**Comment by ResponsiveFlow** [comment]
I tested the #47664 PR and I can see four issues: cc. @jarekmorawski @gigitux 

1. In a variable product, if no variation is selected, the stepper is smaller than the ATC button
https://github.com/woocommerce/woocommerce/assets/47855768/b5874745-16f4-4d3f-806f-d3c37a2969b5

2. In a variable product, the arrow of the dropdown menu is misaligned.
<img width="581" alt="Screenshot 2024-05-23 at 7 06 42 PM" src="https://github.com/woocommerce/woocommerce/assets/47855768/ef624de4-1202-4f77-8b2f-92bf84be5a01">

3. It is possible to decrease the quantity to 0, and then if I add to the cart, a notice is shown saying that the quantity must be >0.
Why not setting 1 as the minimum value?
<img width="543" alt="Screenshot 2024-05-23 at 7 09 30 PM" src="https://github.com/woocommerce/woocommerce/assets/47855768/50db6b47-cdad-4a2a-ba37-f6b6b3811056">

4. The variation drop-down menu is not styles in Safari (macOS).

<img width="424" alt="Screenshot 2024-05-23 at 7 27 09 PM" src="https://github.com/woocommerce/woocommerce/assets/47855768/bad84252-edf1-43e1-8b74-8f8d527da4dd">

**Comment by jarekmorawski** [comment]
Thanks for the review, @tomxygen! It tested well for me for variable products, but it could be a CSS issue.

@gigitux, can you take a second look at the stepper's size on non-simple product pages?

> Why not setting 1 as the minimum value?

It's the minimum value. 🤔 I can't reproduce, it always goes back to 1 for me. We should investigate because there's no point in letting shoppers add 0 products to the cart.

> In a variable product, the arrow of the dropdown menu is misaligned.
> The variation drop-down menu is not styles in Safari (macOS).

Created a separate issue for that: https://github.com/woocommerce/woocommerce/issues/47794

**Comment by gigitux** [comment]
The fix has been reverted with https://github.com/woocommerce/woocommerce/pull/48624. I'm opening this issue again!

**Comment by ResponsiveFlow** [comment]
are there any plans to include it in WC 9.1 or 9.2?

**Comment by gigitux** [comment]
I can't provide any ETA. It mostly depends on how our tests go against payment extensions.

**Comment by ResponsiveFlow** [comment]
I noticed another visual bug.
If the "limit to one item per customer" is turned on, this is what happens on the front end
<img width="471" alt="Screenshot 2024-06-22 at 10 57 28 PM" src="https://github.com/woocommerce/woocommerce/assets/47855768/ebafad07-40de-40e8-8693-ea76baa02cfc">

**Comment by gigitux** [comment]
Thanks @tomxygen! We will take a look when we will work on it!

**Comment by ResponsiveFlow** [comment]
hey @gigitux are there any updates on this issue?
I can help if you need to speed up testing with other payment gateways

**Comment by gigitux** [comment]
Thanks for your help, @tomxygen! Currently, we put this issue on hold because we decided to explore the `Add to Cart Form blockification`: we expect `Add to Cart Form blockification` will cover this feature as well. In the following weeks, we will create several GitHub discussions around this project. Feedback is crucial for the success of this project, so I invite you to follow the discussions and share your thoughts! 🙇

**Comment by CIPURTA** [comment]
Hi everyone, is there any update in question?

**Comment by ResponsiveFlow** [comment]
@gigitux I've encountered an issue:

If the product is set to not allow more than one unit to be purchased the stepper is still shown:
![Image](https://github.com/user-attachments/assets/10b741f2-5bc5-499c-a699-300c4fcb7b3f)

**Comment by gigitux** [comment]
> [@gigitux](https://github.com/gigitux) I've encountered an issue:
> 
> If the product is set to not allow more than one unit to be purchased the stepper is still shown: ![Image](https://github.com/user-attachments/assets/10b741f2-5bc5-499c-a699-300c4fcb7b3f)

Thanks! Nice catch! ❤️

I just opened a PR to fix this issue: #52193. Feel free to ping me if you find other issues on this feature! We are planning to release into WooCommerce 9.5 🤞

**Comment by ResponsiveFlow** [comment]
thank you @gigitux for the quick fix!
I also noticed an incompatibility with the product add-ons official plugin.
the add to cart button (when the stepper is turned on) and the add-ons are placed in a container wi th flex visibility, so they’re shown side by side rather than one on top of the other
