### ISSUE TITLE
Reduce the order summary height on mobile

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42296]
On mobile, the order summary block is too tall, preventing shoppers to see the first fields unless they scroll down.
I think it's important to have some checkout fields "above the fold", because older or less tech-savvy shoppers may not understand that they have to scroll down to show shipping fields.
<img width="1440" alt="Screenshot 2023-07-17 at 12 02 27 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/fb1613cf-0277-4f99-b976-b0f8d3b3dfec">

For example, it could be possibile to collapse the order subtotal, commissions, shipping, sale tax, all inside the order summary row, giving more space to other fields.
Also, some of that space could be filled with a checkout upsell.

[Blendjet](blendjet.com), which is on Shopify, does a great job by showing a checkout upsell and still manages to show the first field above the fold.
<img width="304" alt="Screenshot 2023-07-17 at 12 09 55 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/dcf3b411-4869-40bc-a6a3-ca9e8fa9fe74">

**Comment by opr** [comment]
Thanks for creating the issue @tomxygen - @pmcpinto what do you think of this idea, something we should set some time aside for? I personally really like the idea of a fully collapsed order summary with a clearly labeled way of expanding it on mobile.

**Comment by tomxygen** [comment]
That's great!
As seen in the screenshot above of the [Blendjet](https://github.com/woocommerce/woocommerce-blocks/issues/blendjet.com) website, it could be possible to add checkout upsell.

I've currently placed them inside the mini cart using the Products (beta) block, but the same could be done in the checkout page.
![IMG_77A86CBD4A87-1](https://github.com/woocommerce/woocommerce-blocks/assets/47855768/f4e42c26-feea-42bc-bc7e-7f6d11b9b312)

**Comment by ralucaStan** [comment]
We will have an overview of our mobile experience in the future; so I'll add this ticket to our backlog so we can look at it when the time comes. 

Thank you @tomxygen for the proposal

**Comment by tomxygen** [comment]
Hey @ralucaStan do you have any update on this issue?

with a little bit of CSS I placed the order summary at the bottom of the page: 
```
.is-medium.wc-block-components-sidebar-layout, .is-mobile.wc-block-components-sidebar-layout, .is-small.wc-block-components-sidebar-layout {
flex-direction: column-reverse;
}

.is-mobile .wc-block-checkout__actions .wc-block-components-checkout-place-order-button {
margin-bottom: 20px;
}
```

but this isn't ideal either, because shoppers need to scroll all the way to the bottom to see their total.

**Comment by brentmackinnon** [comment]
@tomxygen We have a [new ticket](https://github.com/woocommerce/woocommerce/issues/44839) to improve the Order summary section planned for this cycle.

**Comment by ralucaStan** [comment]
The proposal from the new ticket should also collapse the Shipping and tax prices. That should be an improvement to the current height of the section. 

@tomxygen I am going to close this ticket for now, thank you so much for your suggestion.

**Comment by ResponsiveFlow** [comment]
Thank you! 
I'll add my comments in #44839
