### ISSUE TITLE
Product Collection - Display list of available taxonomies/authors on focus in taxonomies/author filters

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42298]
### Description
When you use "Taxonomies" or "Authors" filter list of available options doesn't appear on focus, but instead, you must start typing to find some taxonomies/authors

### Steps to reproduce
1. Go to Editor and edit Product Catalog template
2. Insert Product Collection and Products (Beta) blocks
3. Disable "Inherit query from template" option
4. Enable FIlters -> Three dots ->Taxonomies/Author
5. Focus on the input
6. Nothing appears

### Expected outcome
A list of available options should appear on focus.

**Comment by manospsyx** [comment]
In the past we've tacked this by showing a different component depending on the options count. If the available options are only a few, there's no need for a full-fledged search-enabled input.

**Comment by kmanijak** [comment]
Not planned for now.
