### ISSUE TITLE
flex alignment for express checkout on mobile

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42297]
Currently, on mobile devices, express checkout payment options are organized in a grid layout.
Organizing them in a flex layout (at least two per row) would make the express checkout banner shorter, allowing the first checkout field to be visible without scrolling, for those customers who don't want to use the express checkout.

| BEFORE | AFTER |
|--------|--------|
| <img width="301" alt="Screenshot 2023-07-17 at 11 29 34 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/e1c27da4-110c-4729-8fb8-2ed929c667fb"> | <img width="301" alt="Screenshot 2023-07-17 at 11 33 32 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/5a636aeb-f4f9-46e2-8c35-e2b0fed71b41">
 | 

Also, it would be great if it was possible to reduce the size of the elements before the express checkout in order to show the first fields of the checkout without scrolling.
Some shoppers, especially older people and not tech-savvy people expect to see the shipping fields when they go to checkout, and may not understand that they have to scroll in order to reveal them.

**Comment by opr** [comment]
Thanks @tomxygen - we're actually looking into these express buttons right now so we will take your suggestion into account, I'll ping @pmcpinto to make him aware of this. I can't provide a timeline on when we'll have an actual solution in either direction on this but I'll leave the ticket open until we do.

**Comment by mikejolley** [comment]
This should be covered by https://github.com/woocommerce/woocommerce/issues/42464

Thanks

**Comment by ResponsiveFlow** [comment]
Hi @mikejolley thanks for your reply.
I don't think however that in #42464 the issue fixes the appearance on mobile.

**Comment by mikejolley** [comment]
Testing on mobile is part of the process so should be worked on when https://github.com/woocommerce/woocommerce/issues/42464 is done.
