### ISSUE TITLE
Storefront: Hand-picked products selected products list visual bug in the editor

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#42292]
With Storefront active, when adding the **Hand-picked Products** block to a page, and selecting products to display, the selected products display the list dot.

## Screenshots

<img width="1124" alt="Add_New_Page_‹_productgallery_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/632c7fcd-c2d1-4276-9afa-56e3ab995c8e">

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 7.9.0

**Comment by danielwrobert** [comment]
Potentially related: I'm also seeing similar list styling issues on the Product Collection block (in the Editor only).

![CleanShot 2023-08-16 at 12 56 54@2x](https://github.com/woocommerce/woocommerce-blocks/assets/481776/3eb79023-a860-4e4f-b2c2-6cfeb1035cdf)

**Comment by danielwrobert** [comment]
As reported in woocommerce/woocommerce-blocks#10556 (_closed in favor of this Issue_), the styling for the selected products are also incorrect for all of the **Products by \*** blocks.

**Comment by danielwrobert** [comment]
I can't replicate this anymore so I'm going to close it out.

I'm also wondering if this would have been better suited to be reported in the Storefront repo because it seems specific to that theme?

In either case, feel free to re-open if I'm missing anything or it re-surfaces!
