### ISSUE TITLE
Product Collection Telemetry: Convert Product to Product Collection and revert to Products

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42301]
### Background

There are at least two aspects that we would like to track:
- Products block switching to Product Collection
- Revert Product Collection to Products (Beta)

**Comment by manospsyx** [comment]
@kmanijak could you please add some more detail here to help me understand what this is about?

**Comment by kmanijak** [comment]
> @kmanijak could you please add some more detail here to help me understand what this is about?

This issue is about adding telemetry regarding manual (and automatic) upgrades of Products (Beta) block to Product Collection block and potential reverts.

This is happening through the button in inpsector controls of Products (Beta) block:

<img width="285" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/e9e7163d-0c96-4980-9403-6e529a76ace0">

and after the upgrade you can revert it for limited period of time:

<img width="283" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/76d23c9c-fdc5-4f60-a5b4-e3fa592b4f42">
