### ISSUE TITLE
JS warning in the editor: "[stylesheet] was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe."

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#42306]
Issue discovered by @gigitux in https://github.com/woocommerce/woocommerce/pull/38769#issuecomment-1600628702.

## To reproduce

1. With Gutenberg 16.1 or later, go to the post or page editor.
2. Notice there are two warnings:

```
woocommerce-general-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe.
woocommerce-blocktheme-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe.
```

## Expected behavior

There should be no warning.

## Screenshots

<img src="https://github.com/woocommerce/woocommerce-blocks/assets/3616980/630444c5-1cb0-4076-be27-633aeadff0a1" alt="" width="497" />

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 16.1
-   WooCommerce version: 8.0.0-dev
-   WooCommerce Blocks version: 10.7.0-dev

**Comment by danieldudzic** [comment]
I remember that error, but I have now trouble replicating it with `trunk` and WordPress 6.3 beta.

@Aljullu would you mind re-checking this?

**Comment by Aljullu** [comment]
Oh, my bad, I can't reproduce with WP 6.3 without Gutenberg installed. I updated the testing steps. :+1:

**Comment by tarhi-saad** [comment]
I can reproduce the issue with Gutenberg!

**Comment by Aljullu** [comment]
Closing as I just tested with WP 6.6 with Gutenberg 19.0 and without it, and I'm no longer able to reproduce.
