### ISSUE TITLE
Enable merchants to filter cross-sells products by stock level

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42326]
## Is your feature request related to a problem? Please describe.

In https://woocommercecommunity.slack.com/archives/C03MCL9RTAR/p1687880187885559, we received the following question:
> _"Am I correct in saying that it's not yet possible to filter the cross-sell products displayed in the cart block? I don't want to display products that are out of stock in the basket, BUT I want them to remain visible on the archive pages as a waitlist plugin allows customers to be notified when the stock is modified."_

## Describe the solution you'd like

This issue aims to enable merchants to filter cross-sells products by stock level (`In stock`, `Out of stock`, and `On backorder`).

**Comment by mikejolley** [comment]
Another report here: https://github.com/woocommerce/woocommerce-blocks/issues/11809

Since out of stock items are not filtered out, you get "read more" links instead of add to cart.

**Comment by ralucaStan** [comment]
closing this as we're going to work on using the Product collection block instead. see https://github.com/woocommerce/woocommerce/issues/52589
