### ISSUE TITLE
Blocks plugin forces Google Analytics to load Synchronously, penalising Core Web Vitals score

### ISSUE THREAD

**Issue by WiredWonder** [woothemes/woocommerce#42338]
## Describe the bug

In https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/Domain/Services/GoogleAnalytics.php on line 70 the plugin does a check for tag manager, and if not found by an arbitrary name (not compatible with most GA plugins, including older versions of the official one), inserts it *synchronously*.

This causes a big penalty to page load etc.

## To reproduce

1. Enable Woocommerce & official WooCommerce Google Analytics Integration plugin. 
2. Visit site, view source
3. Note gtag.js is loaded without async tag

## Expected behavior

It is best practice to load gtag asynchronously to avoid performance penalties.

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/1524468/57472e2a-4dc1-453d-bf51-a406938459b3)

### WordPress (please complete the following information):

-   WordPress version: Present in current
-   Gutenberg version (if installed): Present in current
-   WooCommerce version: Present in current
-   WooCommerce Blocks version: Present in current
-   Site language:
-   Any other plugins installed:

**Comment by nielslange** [comment]
Thanks for reaching out, @galapogos01. I'll move this issue to our backlog. If you have time to work on it, we'd appreciate your contribution. 😀
