### ISSUE TITLE
Product Collection block: Force two columns on mobile

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42333]
## Is your feature request related to a problem? Please describe.
Currently, you can set any number of columns on desktop but regardless of that, on mobile it will always be one column.

https://github.com/woocommerce/woocommerce-blocks/assets/47855768/61428975-7350-454d-95d8-e11bf91dd21d

## Describe the solution you'd like

I'd like to be able to set the number of columns on mobile (Ideally be able to choose between one or two columns. More than 2 don't look good on mobile).

**Comment by Aljullu** [comment]
Thanks for opening this issue, @tomxygen!

@kmanijak do you think it would be possible to implement something like this in the Product Collection block? Or it should be fixed upstream in Gutenberg instead? Asking because the Query Loop block doesn't have anything similar.

**Comment by kmanijak** [comment]
> @kmanijak do you think it would be possible to implement something like this in the Product Collection block? Or it should be fixed upstream in Gutenberg instead? Asking because the Query Loop block doesn't have anything similar.

Regarding Products (Beta) block that would definitely require implementing upstream (in Gutenberg's Query Loop block). But considering we have better control over Product Collection block we could definitely explore this and I created an issue for that: https://github.com/woocommerce/woocommerce-blocks/issues/9971. This block is still in an experimental phase but should be available to use in a couple of weeks/months. Please be aware that this feature may not be included in the first release of Product Collection block, but it's included in the backlog. The progress can be tracked in this epic: https://github.com/woocommerce/woocommerce/issues/42389.

BTW - personally, I really like this feature request!

**Comment by shaunandrews** [comment]
I wonder if this responsive "shrink columns" solution might resolve this issue as well: https://github.com/woocommerce/woocommerce-blocks/discussions/10708

Basically, you'd define a maximum number of columns, and then products would wrap when the container is too small. This could let you have 2 columns on some larger mobile devices.

**Comment by manospsyx** [comment]
@kmanijak @imanish003 the idea to allow developers (and ultimately users) to customize the min-width embedded in the "shrink cols" logic could be the answer here.

**Comment by imanish003** [comment]
@manospsyx, I'm with you on this! 🤝 This topic(min-width) has indeed surfaced before. 
I believe we may seek some design input to determine the best UI for the "min-width". What are your thoughts?

**Comment by manospsyx** [comment]
@imanish003 I think I would initially provide a programmatic solution, not a UI option. It could be a PHP filter somewhere, a theme parameter, or something similar. If this comes up too often, we can consider a UI option later.

**Comment by imanish003** [comment]
@manospsyx Sounds good to me 🤝

**Comment by kmanijak** [comment]
Considering we implemented a responsive mode that allows for two column layout the only thing that left is to expose a way to override the opinionated minimum column width. I created a dedicated issue for that: https://github.com/woocommerce/woocommerce/issues/45362.

Having said that, I'll go ahead and close this issue. Please note closed issues can still be commented on. 🙌
