### ISSUE TITLE
Disable nonce checks when using Cart Tokens in Store API

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#42341]
It took me a while to understand the issue, but after reading @asumaran's posts about auth I think I understand the problem being encountered. To summarise:

1. Nonces are required to make some POST requests to the Store API
2. Cart Tokens can be used to "auth" and get a user cart/session
3. [wp_create_nonce](https://developer.wordpress.org/reference/functions/wp_create_nonce/) uses a token creation function when logged in. [This uses cookie based auth.](https://developer.wordpress.org/reference/functions/wp_get_session_token/)
4. Without a cookie, the nonce changes with each request making it difficult for the client to track.

Does this sound correct @wavvves?

> Passing the WP auth cookie would fix this issue. But we want to solve this issue without cookies which leaves us with a few options:
> 
> Pass the WP session token using the StoreAPI via header and somehow put it on the nonce validator (I don’t think this is feasible. > Maybe we could hijack the $_COOKIE superglobal).
> Implement a new cookieless nonce creation/verification system.

We should investigate:

1. If its possible to support a consistent nonce when using cart tokens
2. -or- if we really need to use nonces for API requests

cc @ralucaStan

**Comment by sanskritkm** [comment]
wp_create_nonce( 'wc_store_api' ) this code is run only on Wordpress but it is too difficult to do it if we use Flutter to create mobile app by just call API to Store API woocommerce.

how to get Nonce when I built flutter mobile app using API?

**Comment by asumaran** [comment]
@mikejolley is there any news on this? any plans to implement this soon?

**Comment by jkohlbach** [comment]
Hey @mikejolley we're integrating Advanced Coupons with Cart and Checkout blocks on a deep level now as well, we also ran into this during our research.

As far as the utility of nonce in this case, I would argue that it doesn't belong on the Store API at all.

For example a person should be able, without loading any sort of front end UI from WordPress at all, programmatically create a new cart session, add products to cart, and checkout all via API. This is the intent of having a universal store API right?

Forcing a nonce on these endpoints doesn't make sense in light of that as they're really just designed to ensure requests are coming from the same domain. The Cart token is really what we're needing to rely on for subsequent calls.

**Comment by mikejolley** [comment]
@jkohlbach noted. We're discussing the ramifications of removing the nonce when a token is in use. I don't have a timeline for this yet. cc @ralucaStan

**Comment by mpskovvang** [comment]
I would also prefer omitting a nonce when providing a valid cart token for any route related to cart/checkout. In my case, the Store API is "proxied" from another server framework protected by CSRF.

In the code, I noticed the `woocommerce_store_api_disable_nonce_check` filter. If the filter included the `$request` variable, it would be easier to support different conditions.

https://github.com/woocommerce/woocommerce-blocks/blob/2973d4278e99d75b41a0c8011fd37e3ec7699bcf/src/StoreApi/Routes/V1/AbstractCartRoute.php#L299-L301

Please let me know your thoughts. In the meantime, I'll just use the native `$_SERVER` variable to perform the checks.

**Comment by fazary** [comment]
any updates ?

**Comment by lsinger** [comment]
Also see #38936 -- might be the same issue?

**Comment by mikejolley** [comment]
@lsinger Yeah same issue. cc @ralucaStan

**Comment by senadir** [comment]
Renamed this to better reflect the outcome. To my understanding, the cart token is in itself an enhanced nonce, it's sent as a header, and only belongs to single customer, so it can't be used in a CSRF attack. It can be replayed thou but we have time limitations on the token, and I think we should reduce them even more.
