### ISSUE TITLE
WooCommerce block patterns can not be disabled and/or do not respect WordPress pattern supports/hooks

### ISSUE THREAD

**Issue by ninetyninew** [woothemes/woocommerce#42342]
## Describe the bug

I am looking to disable WooCommerce block patterns (well actually all block patterns) entirely, but WooCommerce blocks do not seem to respect the following:

In the theme I can set:

`remove_theme_support( 'core-block-patterns' );`

Elsewhere I can also return this filter as false:

`should_load_remote_block_patterns`

I have also attempted to remove the block type `core/pattern` via the `block_editor_settings_all` filter hook (I am unsure if this bears any relation to the blocks being available, but guessing it does)

When applying all the above, all other patterns are removed, but WooCommerce product blocks remain:

<img width="638" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/56840277/689a5deb-393d-4fd0-ae93-533455c73351">

## To reproduce

1. Login to WordPress as an administrator
2. In your theme add `remove_theme_support( 'core-block-patterns' );` to functions.php
3. Add this code to a plugin, or theme functions.php file:

```
add_filter( 'should_load_remote_block_patterns', '__return_false', 9999 );
add_action( 'allowed_block_types_all', 'restrict_block_editor_block_types', 20, 2 );

function restrict_block_editor_block_types( $allowed_block_types, $block_editor_context ) {

	// Get registered blocks, note that $allowed_block_types is not an array of all block types, it's just 1, so we have to get all blocks as below

	$registered_blocks = WP_Block_Type_Registry::get_instance()->get_all_registered();

	// Setup allowed block types array for return

	$allowed_block_types = array_keys( $registered_blocks );

	if ( null !== $block_editor_context ) {

		foreach( $allowed_block_types as $allowed_block_type_key => $allowed_block_type_value ) {

			if ( 'core/pattern' == $allowed_block_type_value ) {

				unset( $allowed_block_types[$allowed_block_type_key] );

			}

		}

	}

	return $allowed_block_types;

}
```

4. Edit a post in WordPress and click patterns, you'll see only the WooCommerce patterns remain

## Expected behavior

This potentially may be the expected behaviour right now as we are stopping core patterns and remotely loaded patterns - WooCommerce's patterns are not core WP and I assume not remotely loaded. But therefore there should there be a way of disabling them? Potentially this is a WordPress issue that it doesn't seem possible to disable all patterns entirely: https://github.com/WordPress/gutenberg/issues/51370 - but even then there might be use cases where someone just wants to disable the WooCommerce patterns only...?

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   WooCommerce version: 7.7.2

**Comment by kmanijak** [comment]
Hi @ninetyninew,

Thanks for opening that issue! It's a nice enhancement suggestion, I created a draft of such a solution at https://github.com/woocommerce/woocommerce-blocks/pull/9807, but there are still some parts to cover before finalizing. Please keep in mind though, this enhancement doesn’t fit in with our current priorities for the project and we have limited time to work on various projects. So finalizing this PR is not the highest priority and may take a while to finish. 

Meanwhile, don’t be alarmed if you don’t see any activity on this issue for a while. 🙏

**Comment by gregbob13** [comment]
@ninetyninew,
Thanks for bringing this into the light of day. I, too, would like to be able to completely disable patterns for sites running WC.

**Comment by miksansegundo** [comment]
Please have a look at this snippet: https://github.com/Automattic/wp-calypso/issues/88027#issuecomment-1978097148. It could also work to unregister WooCommerce patterns.

**Comment by nerrad** [comment]
Thanks @miksansegundo for the snippet. @ninetyninew, the above snippet shared by Miguel should work for unregistering patterns. I see you also opened an issue in the Gutenberg repository for enhancing GB to provide a more straightforward way to register all patterns which is where this level of change should live. 

Let us know if you have any additional questions/comments.

**Comment by ninetyninew** [comment]
@nerrad yes, since this was posted I did something similar to the calypso snippet

**Comment by bradhogan** [comment]
Why is this closed?  There is still no resolution..

**Comment by melcarthus** [comment]
Have you been working on a resolution yet? This is kind of a big deal for bespoke agency website that don't need this bloat.

**Comment by miksansegundo** [comment]
It should be possible to disable all kind of patterns with a script like [this](https://github.com/Automattic/wp-calypso/issues/88027#issuecomment-2295823138).

Have a look also to this [documentation](https://developer.wordpress.com/docs/developer-tools/block-patterns/#a8c-docs-toc-content).
