### ISSUE TITLE
All templates page: Author temporarily changes after editing a template added by WooCommerce

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#42378]
## Describe the bug

When customizing and saving a templated added by WooCommerce (for example: Product by Category, Product by Tag, Single Product, etc.) and visiting the All Templates page, the author is temporarily changed to the current logged in user.

## To reproduce

1. Log in to your WordPress dashboard;
2. Go to Appearance > Themes, and select a block theme (for example: Twenty-twenty three);
3. Go to Appearance > Editor;
4. Go to Templates > Single Product (or any template added by WooCommerce);
5. Click the Edit button;
6. Click on the "+" icon to add a new block and select any block that you want, for example: Paragraph;
7. Edit the block if needed to include some text or information;
8. When you finish, click on Save (on the top right of the page);
9. On the top center of the page, click on the arrow icon (besides the template name) and click on Manage All Templates;
11. When the page is loaded with the list of templates check that the template you customized has your username in the Added by column;
12. Wait a few seconds and notice that the author in the Added by column was replaced back to WooCommerce;

## Expected behavior

The expected behavior is that after customizing a template, the author should always remains the same, in this case, the WooCommerce should always appear in the Added by column

## Screenshots

https://user-images.githubusercontent.com/20469356/235955793-94a81772-5085-4e00-af52-6db67b717b64.mov

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.6.0-rc.2
-   WooCommerce version: 7.8.0-dev
-   WooCommerce Blocks version: 10.2.0-dev
-   Site language: en-US
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: MacOS Ventura
-   Browser: Chrome
-   Version: 112.0.5615.137

**Comment by Aljullu** [comment]
@thealexandrelara thanks for opening this issue! I tested this with WP 6.4 and 6.5 and with WooCommerce `trunk` and 8.6 and I'm unable to reproduce. Wondering if it might have been fixed in a another PR or upstream in Gutenberg/WordPress. :thinking:  Would you mind trying if you can still reproduce?

**Comment by thealexandrelara** [comment]
> @thealexandrelara thanks for opening this issue! I tested this with WP 6.4 and 6.5 and with WooCommerce `trunk` and 8.6 and I'm unable to reproduce. Wondering if it might have been fixed in a another PR or upstream in Gutenberg/WordPress. 🤔 Would you mind trying if you can still reproduce?

I double-checked this and the issue is not occurring anymore. Considering that, I'm closing this issue. Thank you for pinging me, @Aljullu!
