### ISSUE TITLE
The title of category (slug) `WooCommerce Product Elements` it is not displayed translated

### ISSUE THREAD

**Issue by DAnn2012** [woothemes/woocommerce#42373]
## Describe the bug

`WooCommerce Product Elements` category (slug) title is not displayed translated in block inserter.

## Screenshots

Example 1 (Italian):

![woo-it](https://github.com/woocommerce/woocommerce-blocks/assets/1197819/77eef787-5513-42bc-90ab-1d479ccd06a3)

[Permalink to translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10345059&filters%5Btranslation_id%5D=75587594)

<hr>

Example 2 (Spanish):

![woo-es](https://github.com/woocommerce/woocommerce-blocks/assets/1197819/d287bf23-f6ba-40f2-8ccc-8227faf25176)

[Permalink to translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10345059&filters%5Btranslation_id%5D=75581409)

### WordPress:

-   WordPress version: 6.2
-   WooCommerce version: 7.7.0
-   WooCommerce Blocks version: 10.0.4 (included in WooCommerce)
-   Site language: Italian or Spanish (for example)

### Desktop:

-   OS: macOS
-   Browser Safari
-   Version 16.4.1 (17615.1.26.101.10, 17615)

**Comment by imanish003** [comment]
@DAnn2012 Thank you for taking the time to report this issue. Your feedback is valuable to us. We have added it to our backlog for prioritization. Rest assured, we are committed to resolving this issue promptly and will keep you updated on our progress.

**Comment by DAnn2012** [comment]
Hello @imanish003 , @nerrad and @ObliviousHarmony 

I did a new test with **WooCommerce 9.1.4** and now the string is displayed translated.

Example 1 (Italian):
![wcpe-italian](https://github.com/user-attachments/assets/2972c62d-99d3-45e8-ab32-2733b6c7c389)

Example 2 (Spanish):
![wcpe-spanish](https://github.com/user-attachments/assets/17c291de-762c-4e6d-8485-36e56b5bcc2a)

Thanks.
