### ISSUE TITLE
[on Hold] Checkout block: Improve the Express Checkout section in the post editor

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42384]
## Is your feature request related to a problem? Please describe.
In the editor, the Express Checkout section from the Checkout block needs to be improved.
The section appears when the merchant has enabled in a payment gateway to enable express payments. 

For example, Stripe can be used to enable Google Pay and Apple Pay.
<img width="933" alt="Screenshot 2023-04-28 at 12 09 08" src="https://user-images.githubusercontent.com/1628454/235120000-3fe8f402-7df6-40a2-bdb7-62a877da2e3d.png">

### Current issues

<img width="927" alt="Screenshot 2023-04-28 at 12 05 04" src="https://user-images.githubusercontent.com/1628454/235119484-d5f6bdf4-e6ed-47df-99df-5e932fa672bb.png">

- If express payments are enabled, a default placeholder is used in the editor that shows the ApplePay button. This appears even if the merchant hasn't enabled the ApplePay option.
- If no express payments option is enabled, there is no inner block 

## Describe the solution you'd like 
**No Express Payments set up** (this is the current behavior)
If no express methods are set up hide the inner block, and don't display any placeholder. If the merchant hasn’t enabled any express methods yet, or has chosen not to enable them for business reasons, there’s no “empty state” for express payment methods in the post editor.

**Express Payments are set up**
![checkout-express-methods-notice (1)](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/42a0b24d-530e-461f-8b44-85204ac00b96)
- If there are express payments defined then those should be visible in the post editor, as they appear in the front-end for the shopper. The shopper sees the express payments if they are registered and the website is using https.
Some options like Apple Pay and Google Pay need to be correctly set up in the browser in order to appear.
- The buttons that appear in this section should be disabled. Clicking on them should not be possible. The buttons should come from the `editor` property of the registered express payment option https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#edit-required
- The list of enabled express payment methods should appear in the Express Checkout block's sidebar (similar to the list shown for the Payment options block). 
- After the enabled express payment methods list a link Manage in settings should appear, that sends the merchant to the `/wp-admin/admin.php?page=wc-settings&tab=checkout` page

pdFofs-10g-p2

**Comment by mikejolley** [comment]
Gutenberg uses placeholders when a block has no content:

![Screenshot 2023-04-28 at 12 47 48](https://user-images.githubusercontent.com/90977/235139636-fd5c0b56-998a-4160-822e-8f22cccfa222.png)

Maybe we could do something similar, but more fancy :)

**Comment by ralucaStan** [comment]
> Gutenberg uses placeholders when a block has no content:

Heads-up to @shaunandrews about this, we'll need your help designing the solution for this ticket

**Comment by ralucaStan** [comment]
Internal discussion pdFofs-10g-p2

**Comment by ralucaStan** [comment]
@pmcpinto Moving this to the Next column as we don't have a final design to work on.

**Comment by pmcpinto** [comment]
> If no express payments option is enabled, there is no inner block

This approach makes sense.

> If express payments are enabled, a default placeholder is used in the editor that shows the ApplePay button. This appears even if the merchant hasn't enabled the ApplePay option.

Is anything blocking us from displaying the enabled express payments rather than a placeholder? Similar to the logic implemented in the Payments option list.

**Comment by elizaan36** [comment]
+1 to Pedro's comment and question. The thinking is that the page view of the checkout block should represent as close as possible 1-1 what the shopper will see. This will allow merchant to customize it exactly to their preferences all in the editor. This includes the ability to see which express payment methods will appear to the shopper at checkout in case any tweaks are needed to get the display looking right.

I shared a comment on P2 `pdFofs-10g#comment-1234` with more context.

**Comment by ralucaStan** [comment]
@elizaan36 I've added the needs design label to this, based on the remarks from this comment pdFofs-10g-p2#comment-1258
I've updated the ticket description as well

**Comment by ralucaStan** [comment]
I've created https://github.com/woocommerce/woocommerce/issues/42353 to work on until we have a final decision on the sidebar updates for the inner block; we'll handle that in another ticket. I am keeping this ticket to track the effort.

**Comment by elizaan36** [comment]
Noting here that @shaunandrews is working through designs for this on p2 here - 
pdnLyh-3L2.

**Comment by ralucaStan** [comment]
impacted also by decision on https://github.com/woocommerce/woocommerce/issues/42464

**Comment by pmcpinto** [comment]
Hey @ralucaStan I think we can close this issue as it will be solved by what Alex described in the following post, correct? pdFofs-2mC-p2

**Comment by ralucaStan** [comment]
Sure thing. @alexflorisca just posted https://developer.woocommerce.com/2024/10/28/more-options-coming-to-the-express-checkout/ to summarize his work
