### ISSUE TITLE
Editor Guide: More contextual information for WooCommerce stores

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#42392]
## Is your feature request related to a problem? Please describe.
During our recent product walkthrough session, we created a new store as a merchant and when we landed in the editor we got the welcome/quick start guide on our store homepage but all the information was in the context of a blog rather than a store.

Is this something we have previously looked into/thought about? Any additional information around this would be great.

**Comment by nerrad** [comment]
Work on CYS is primarily fulfilling this need for now.
