### ISSUE TITLE
Playwright: Migrate `shopper/cart-checkout/cart.test.js`

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42405]
This issue aims to migrate  `shopper/cart-checkout/cart.test.js` from Puppeteer to Playwright and is part of the [Migrate E2E tests to Playwright project](#9001).

**Comment by nielslange** [comment]
Closing due to pca54o-6Dz-p2

**Comment by opr** [comment]
This should not be closed, the tests need to be migrated to playwright still.

**Comment by nielslange** [comment]
> This should not be closed, the tests need to be migrated to playwright still.

Thanks for catching this. I closed this one too fast. I might have closed another similar issue as well. 🤔
