### ISSUE TITLE
Validate data coming from "woocommerce_cart_shipping_packages" filter

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#42410]
## Describe the bug

A Warning/ TypeError (depending on PHP version used) is displayed on the front end when [Multiple Packages for WooCommerce](https://wordpress.org/plugins/multiple-packages-for-woocommerce/) is activated but not yet configured, while [WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) is enabled and configured.

## To reproduce

1. Install and activate [Multiple Packages for WooCommerce](https://wordpress.org/plugins/multiple-packages-for-woocommerce/) without setting it up
2. Install, activate, and set Test Keys for [WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/)
3. Add an item to the cart and visit the Cart Block page
4. See Warning/TypeError:

![image](https://user-images.githubusercontent.com/17236129/231445108-d792e325-938c-413d-9e22-571bc2240c15.png)

```shell
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php:604 
Stack trace: 
#0 woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php(879): WC_Stripe_Payment_Request->allowed_items_in_cart() 
#1 woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php(757): WC_Stripe_Payment_Request->should_show_payment_request_button() 
#2 wp-includes/class-wp-hook.php(308): WC_Stripe_Payment_Request->scripts('') 
#3 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#4 wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#5 wp-includes/script-loader.php(2194): do_action('wp_enqueue_scri...') 
#6 wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('') 
#7 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#8 wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#9 wp-includes/general-template.php(3049): do_action('wp_head') 
#10 wp-content/themes/storefront/header.php(18): wp_head() 
#11 wp-includes/template.php(783): require_once('...') 
#12 wp-includes/template.php(718): load_template('...', true, Array) 
#13 wp-includes/general-template.php(48): locate_template(Array, true, true, Array) 
#14 wp-content/themes/storefront/page.php(13): get_header() 
#15 wp-includes/template-loader.php(106): include('...') 
#16 wp-blog-header.php(19): require_once('...') 
#17 index.php(17): require('...') 
#18 {main} 
thrown in woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php on line 604
```

## Expected behavior

**No Warning/Error should be displayed**.

## Additional context

The problem seems to be the output of "woocommerce_cart_shipping_packages" filter, as it is expecting an array explicitly (L828 rules out object implementing Countable).

_Note: This could be a good opportunity to revisit the TODO comment and address the duplicate code present there._

**Comment by opr** [comment]
@wavvves please could you provide more information on this issue? There are no reproduction steps or even an explanation of the issue.

**Comment by wavvves** [comment]
I copied the description over from the original issue https://github.com/woocommerce/woocommerce-blocks/issues/9016
It seems it failed to import the description during the monorepo merge, we might need to keep our eyes open to see if this affects other issues 🙄

**Comment by opr** [comment]
@wavvves are you able to reproduce this? I am not able to. The instructions are a little unclear, too. What does:

> Install and activate [Multiple Packages for WooCommerce](https://wordpress.org/plugins/multiple-packages-for-woocommerce/) without setting it up 

mean? What should the settings look like to count as it "not being set up"?

**Comment by wavvves** [comment]
Indeed, this does not seem reproducible anymore. 

My best guess is that the Multiple Packages plugin was making use of `woocommerce_cart_shipping_packages` filter, and after first activation without further configuration, was probably outputting an object that did not implement `Countable` causing `count()` to throw a warning.

So even though this seems to be fixed on the Multiple Packages extension, I believe it should still need some safe handling on our side so it makes sure is countable before calling `count()` here:

<img width="564" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/32cfd54b-ecbf-48a2-bf02-7e681cc8a033">

I will open a PR with that safeguard quickly to close this, to ensure this won't happen again when 3rd parties misuse the filter 👍🏼 
Also, this throws a fatal on PHP 8+ so priority is a bit higher after all.
