### ISSUE TITLE
Playwright migration: Integrate the flaky E2E test reporter

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#42411]
With woocommerce/woocommerce-blocks#6639, we introduced a flaky E2E test reporter. We should add support to Playwright.

**Comment by WunderBart** [comment]
Looks like this one can be closed? @gigitux @imanish003

**Comment by imanish003** [comment]
@WunderBart Yup, I think so.

**Comment by gigitux** [comment]
Thanks for working on this, @imanish003!
