### ISSUE TITLE
Products (Beta) block. Same size images

### ISSUE THREAD

**Issue by paaljoachim** [woothemes/woocommerce#42415]
Using the Products (Beta) block for a site I see this:
![Screenshot 2023-04-10 at 14 00 16](https://user-images.githubusercontent.com/5323259/230897929-83536e9b-2276-4ed3-94a0-72938ad3a834.jpg)

Notice how uneven this is. We might need to bring this into the Query Loop block in Gutenberg and then it would show up in the Products block in WooCommerce.

**Comment by albarin** [comment]
@paaljoachim Thanks a lot for reporting this! We have added the issue to our backlog. We'll let you know of any updates.

**Comment by paaljoachim** [comment]
Hey @albarin 

This might also be a Query Loop block issue.
I just checked the Query Loop block and noticed this:
![Screenshot 2023-04-12 at 13 14 16](https://user-images.githubusercontent.com/5323259/231441369-b699c42b-32d4-4c79-8462-f27347d4bf9d.jpg)

It uses the Post Featured Image block and that adds various options which make it possible to have various images the same size. For instance I used cover so that an image fills out the space.

While the Product Image block uses this:
![Screenshot 2023-04-12 at 13 18 38](https://user-images.githubusercontent.com/5323259/231442144-5324016a-5abf-4adf-ad78-e150d7e1d9d3.jpg)

I believe it just needs to add the various Query Loop block Post Featured Image settings.

**Comment by imanish003** [comment]
Hi @paaljoachim, thank you for taking the time to submit an issue. Your contribution is greatly appreciated! 🙌🏻

It does make sense to add width, height, and scale controls for the Product Image. That way, we can ensure consistent width and height for product images. Currently, we are using our own block, the Product Image, instead of the Post Featured Image. As a result, they don't share the same controls. One reason for using our own Product Image block is the need to display the Sale badge on the image.

**Comment by paaljoachim** [comment]
Hi @imanish003 

Perhaps it would be better to use a custom Post Featured Image block to where one can also display the Sale badge. Adding a panel named Sale Badge which include the needed controls.

**Comment by imanish003** [comment]
Hi @paaljoachim, 👋

That makes sense. 💡 We've had internal discussions about replacing the Product Image with a more versatile block, such as the Cover block or Post Featured Image block, and incorporating the On-Sale badge as an inner block. Our goal is to enhance customization options for the Product Image and Sale badge. 

Your input is greatly appreciated. 🙏 Upon reviewing the issues, I found woocommerce/woocommerce#42478, which appears to address the same topic. Consequently, I've resumed the discussion there. 💬

**Comment by kmanijak** [comment]
Providing additional information from another issue (https://github.com/woocommerce/woocommerce-blocks/issues/8338) about the same topic:

> For reference, Gutenberg has a similar issue for the Image block: https://github.com/WordPress/gutenberg/issues/38990.

> Also, aspect ratio has been added to the Post Featured Image block (https://github.com/WordPress/gutenberg/pull/47854) with design follow-ups here (https://github.com/WordPress/gutenberg/issues/47963). 🚀

**Comment by paaljoachim** [comment]
Btw I am going to add the comment I made into the other issue here:
https://github.com/woocommerce/woocommerce/issues/42478

We should probably keep discussions in the 8355 issue.

Bottom line is that a block is needed that can add an image and inner block so the user can add a sales badge. Currently that is only the Cover block which can handle. Group block can not handle adding an image directly.

**Comment by paaljoachim** [comment]
I will close this issue. Because of this followup.
https://github.com/woocommerce/woocommerce/issues/44387
