### ISSUE TITLE
Segmented Control: Missing border in resting state

### ISSUE THREAD

**Issue by shaunandrews** [woothemes/woocommerce#42419]
In the sidebar Inspector its common to use Segmented Controls for toggling different settings. Normally these controls have a default border that appears in the control's resting state. However, I'm noticing that these controls don't have their standard border:

<img width="272" alt="CleanShot 2023-04-03 at 17 25 38@2x" src="https://user-images.githubusercontent.com/191598/229631051-6fde41be-0c1b-4aab-8522-156013f79168.png">

I'm testing this on a demo site setup by @nerrad, so perhaps this is specific to that demo site: https://storeeditingdemo.wpcomstaging.com/

**Comment by mikejolley** [comment]
This control does not exist any more and the others appear to have the border, so Im closing this issue.
