### ISSUE TITLE
Field to create account password not present at Checkout

### ISSUE THREAD

**Issue by shevene** [woothemes/woocommerce#42430]
## Describe the bug

New users do not get the option to create a password at checkout when using WooCommerce Blocks. 

## To reproduce

1. Go to **WooCommerce →  Settings →  Accounts & Privacy**.
2. Disable the setting for `When creating an account, send the new user a link to set their password`.
3. Attempt to place an order as a new user, and you'll notice that there is no option to create a password.

## Expected behavior

There should be an option to `Create account password` as there is with the`[woocommerce_checkout]` shortcode.

### WordPress (please complete the following information):

- WordPress version: 6.1.1
- WooCommerce version: 7.5.0
- WooCommerce Blocks version: 9.8.1
- Site language: English
- Any other plugins installed: WooCommerce Subscriptions, WooCommerce Stripe

## Additional context

6042831-zen

**Comment by mikejolley** [comment]
Thanks for the report. We'll need to look into this. I know there are some improvements to the account creation flow being planned so we'll see if this needs adding in the interim. I've moved the issue to the backlog.

**Comment by ralucaStan** [comment]
woocommerce/woocommerce#42529 is related. @mikejolley it would help to have a screenshot of the shortcode behavior.

**Comment by mikejolley** [comment]
With this config in WooCommerce core:

![Screenshot 2023-03-23 at 10 40 35](https://user-images.githubusercontent.com/90977/227178910-427151bd-3daf-4137-988f-ea2a57a4cd52.png)

Shortcode gives you:

![Screenshot 2023-03-23 at 10 40 42](https://user-images.githubusercontent.com/90977/227179001-9dc39108-499b-4ebe-960a-e9047cd24fc0.png)

Block gives you:

![Screenshot 2023-03-23 at 10 40 58](https://user-images.githubusercontent.com/90977/227179054-c56cd177-aada-4483-a008-44f821d21f68.png)

This is not necessarily a bug because the functionality may not be desirable, but there is a mismatch between settings UI and Block Checkout.

**Comment by brnhrst** [comment]
Are you still planning to implement this important feature in Block Checkout?

We sell digital goods that we make available to our customers in their user accounts. We are also trying to build a community of our customers, i.e. support forum, comments etc. The free choice of username and/or password is essential for this and it is a pity that this option has been completely omitted from the block checkout, although the WooCommerce settings still suggest this functionality.

**Comment by ralucaStan** [comment]
Hello @brnhrst, thank you for reaching out and explaining your use case.
This work is in the immediate pipeline for the Checkout blocks.

**Comment by fredperes** [comment]
This is sooo important! The workflow has a big flaw. The user finishes the purchase, receives an e-mail but don't know his password.

**Comment by chrism245** [comment]
8044717-hc

**Comment by dominique-vias** [comment]
Linking the [working public file](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=424%3A1612&t=IfzlZ1kuZa0kijQ6-1) here that aims to address this and more

**Comment by ResponsiveFlow** [comment]
@nikkivias the mockups look brilliant, especially the ones found in Sections > Account/Contact.
Both for the login/register page before checkout, and for the possibility to sign up after checkout.
Has any work already begun to implement that?

**Comment by ralucaStan** [comment]
The work was not yet started, but it's something we're going to pick up soon. We'll create issues on the repo as soon as we start
