### ISSUE TITLE
Add to cart form block > Ensure the button style in the editor preview matches the frontend

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#42462]
On https://github.com/woocommerce/woocommerce-blocks/pull/8582#pullrequestreview-1319382952, @Aljullu made a suggestion to ensure the button style in the editor preview for the add to cart form block matches the frontend, which is a great idea. Porting over the original convo here:

> we could add classes like `wp-element-button` to the button, that would ensure the button styles are more similar to the frontend as it will inherit theme styling. Currently, they look quite different:

Editor (with Pixl) | Frontend (with Pixl)
--- | ---
![imatge](https://user-images.githubusercontent.com/3616980/222096500-d8f19fc3-9440-40f1-a011-78327de3c991.png) | ![imatge](https://user-images.githubusercontent.com/3616980/222096420-050f90ca-fff3-43ab-9539-9c771eadecf9.png)

**Comment by imanish003** [comment]
There is one more similar issue reported by @albarin i.e. woocommerce/woocommerce-blocks#8587

**Comment by gigitux** [comment]
I will remove this issue from the scope of Blockified Single Product template. We could fix this in the next iteration of this block!

**Comment by Aljullu** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/11614.
