### ISSUE TITLE
Widget Page: Snackbar notice is in the wrong position

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#42479]
## Describe the bug

When the user saves the changes on the widget page the snack bar notice is in the wrong position. From a quick look, it seems that we apply some CSS to that. We should not do that.

## To reproduce

1. Go to Appearance> Widget.
2. Make some changes to the Widget Page.
3. Save.
4. See the snack bar in the wrong position.

## Expected behavior

The notice should appear as appear when WC isn't installed. 
## Screenshots

| Without WC installed | With WC installed |
|----------------------|-------------------|
|![image](https://user-images.githubusercontent.com/4463174/215715704-f1bad16e-c073-4559-aa13-0b934a38465f.png)|                   ![image](https://user-images.githubusercontent.com/4463174/215715882-e6f5d891-0a08-497f-a5fc-5191986ed1ce.png)|

**Comment by roykho** [comment]
I believe this issue no longer exists? I was not able to replicate.

See ref:

![Google Chrome - Widgets ‹ woo-blocks-dev — WordPress 2024-08-16 at 11 23 12 AM](https://github.com/user-attachments/assets/c74dee95-0b13-40fe-aa10-78199127ca42)

**Comment by gigitux** [comment]
Thanks for checking this issue! 

> I believe this issue no longer exists? I was not able to replicate.

I tried to replicate the issue but was unable to do so. Therefore, I’ll go ahead and close it.
