### ISSUE TITLE
After editing the Product Catalog template, editing another WC template starts empty

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#42499]
## To reproduce

1. On the `Site Editor` (`/wp-admin/site-editor.php?postType=wp_template`), remove all customizations you might have.
2. Now, make some customizations to the _Product Catalog_ template.
3. Without reloading, go to customize another WC template, like _Products by Category_.
4. Notice you start from an empty template.

![Empty template editor when editing the Products by Category template](https://user-images.githubusercontent.com/3616980/208446478-ff6fa49a-1c58-4816-8040-828b2a4a2222.png)

## Expected behavior

It should use the Product Catalog template as the starting template.

**Comment by metabreakr** [comment]
I've also experienced an issue (using TT3, not sure if relevant) in pdEkSe-2eD-p2 where editing the Product Catalog template and then another (e.g. Home) will wipe out any changes I made to the Product Catalog. So while working in FSE, I had to ensure that Product Catalog was the last template edited to keep the changes.

**Comment by Aljullu** [comment]
Closing as I'm not able to reproduce anymore. Tested on WP 6.4 and 6.5, and WC 8.5 and `update/BlockTemplatesController-refactor` and wasn't able to reproduce in any of them.
