### ISSUE TITLE
New Products block (ex Query Loop) > don't use H3 to size Product's title

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#42518]
## Describe the bug

H3 is used to decorate the Product's title within results.
Same as https://github.com/woocommerce/woocommerce-blocks/issues/7869

## To reproduce

Just add the block and observe if a Hn tag is used.

## Expected behavior

Hn tag is not intended to be used to size content
see W3C html, it has a semantic value.
Please remove and add a proper css class instead.

## Screenshots

![image](https://user-images.githubusercontent.com/919332/206168467-9ad89bd5-831b-4f44-a5c6-f52400346026.png)

### WordPress (please complete the following information):

WP6.1.1
Woo Blocks 9.1
Gutenberg plugin 14.6.1
WC 7.1
TT2 Theme

**Comment by albarin** [comment]
Hi, thanks for reaching out!
I think the same reasoning from https://github.com/woocommerce/woocommerce-blocks/issues/7869#issuecomment-1365822631 applies also here.

**Comment by Marc-pi** [comment]
@albarin it would be fine, but we are not able to set the product title as simple paragraph block !!!
so there is no way to unset H3 !!!!
please fix correctly the issue, it makes no sense to use Hn semantic tag in the product grid loop context.
Hn is not intended to make a decorative choice, no in all cases.
tested on the Product Collection block
