### ISSUE TITLE
Reorganize starting Woocommerce templates

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#42532]
### Discussed in https://github.com/woocommerce/woocommerce-blocks/discussions/6919

<div type='discussions-op-text'>

<sup>Originally posted by **Aljullu** August 18, 2022</sup>
Currently, WooCommerce allows users to modify these templates:

* Single Product
* Product Catalog
* Products by Category
* Products by Tag
* Product Search Results

![imatge](https://user-images.githubusercontent.com/3616980/185339351-3e992522-cc77-4396-9870-8870af7cebe8.png)

That allows a good level of customizability for store owners and block theme authors. However, it has some drawbacks:

* There is no way to modify the Product Catalog, Products by Category and Products by Tag templates at once.
* There is no way to customize the Products by Attribute template.
* Having five (or more) templates in the templates list by default can be overwhelming. Specially as more might be added in the future.
* WooCommerce is not making use of the _Add New_ button in the templates list page, which might be a better location for some templates that hadn't been customized by the user/theme and inherit from another template.

<img src="https://user-images.githubusercontent.com/3616980/185338360-3b6de621-4cea-408f-8de6-88594f842977.png" width="359" alt="Screenshot of the Add New button in Gutenberg" />

Based on that, we are planning to make several changes to the way WooCommerce templates work in block themes:

* We will create a Products by Attribute template so it can be customized (currently, [it always defaults to the Product Catalog template](https://github.com/woocommerce/woocommerce-blocks/pull/6776)).
* We will make the Products by Category, Products by Tag and Products by Attribute templates to “fallback” to the Product Catalog one. That means that if the theme neither the user have customized one of those three templates, it will look like the Product Catalog one. For reference, that’s issue [#5520](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/issues/5520).
* We will hide those three templates from the list of templates by default. Instead, they will appear under the _Add New_ button menu. However, if the theme or the user has customized one of those three templates, it will appear in the templates list. The tl;dr is that they will behave as the Category and Tag templates from WP core.
* Product Search Results will remain as-is, meaning it will always be shown in the list of templates (no matter whether it has been customized or not) and will never fallback to another template. Same for Single Product template.
* Internally, we discussed whether a Product Taxonomy template would be necessary. For now, we aren't planning to create it, but if you know of a good use case for why it should be added, please let us know!

We don't have an ETA for this, but we are sharing this plan with the community to gather early feedback in case you see issues in this approach or have any suggestions. You can also leave a :+1: to mark that you read this and you agree with the proposed changes.

PD: While not mentioned, there are some other changes to templates coming in future versions of WC and WP. An example is setting custom templates for specific products or categories, which is already possible in recent versions of Gutenberg.</div>

**Comment by Aljullu** [comment]
I'm going to mark this as duplicate, as everything that is defined in this issue has either been fixed already or it's detailed in https://github.com/woocommerce/woocommerce/issues/42531. This way we have a single source of truth there.
