### ISSUE TITLE
Respect out of stock option in Cross sell block

### ISSUE THREAD

**Issue by grapefishflu** [woothemes/woocommerce#42530]
## What do you like about the Cart & Checkout blocks?
Big visual improvement. Using the block editor I have been able to add things to my cart page.
## What do you think is missing from the Cart & Checkout blocks?
The Cart Upsell block needs the option to hide out of stock products.

**Comment by nielslange** [comment]
Hello @grapefishflu 👋

> The Cart Upsell block needs the option to hide out of stock products.

Thanks for taking the time to report this. The current Cross-Sells block is using the same logic as the Cross-Sells block in the shortcode-based cart. That said, I see a valid case for hiding out of stock products from the Cross-Sells product list. I linked this issue to the list of potential improvements of the Cross-Sells block on https://github.com/woocommerce/woocommerce/issues/42558.

Unfortunately, I cannot give you an estimate when or if we're working on this change. For the time-being, if you want to hide out of stock products from the Cross-Sells products list, you'll manually have to remove them within the products in which they are listed as Cross-Sells products.

**Comment by grapefishflu** [comment]
Much appreciated.

**Comment by mikejolley** [comment]
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/42326 so I'm closing this one. Thanks.
