### ISSUE TITLE
Enable merchants to adjust the sorting of the products within the Cross-Sells block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42549]
With woocommerce/woocommerce-blocks#6554, we implemented the Cross-Sells block. Currently, it's not possible to adjust the order of the Cross-Sells products. This issue aims to enable merchants to adjust the order of the Cross-Sells products similar to the All Products block:

<img width="1438" alt="Screenshot 2022-10-24 at 19 05 55" src="https://user-images.githubusercontent.com/3323310/197521721-875c20d0-9ac7-480b-8f59-bc36fa2183eb.png">

## Potential order options:

- Default sorting (menu order)
- Popularity
- Average rating
- Latest
- Price: low to high
- Price: high to low

## Dependencies

To remain backwards compatibility, this issue might required upstream changed within the WooCommerce core.

**Comment by ralucaStan** [comment]
closing this as we're going to work on using the Product collection block instead. see https://github.com/woocommerce/woocommerce/issues/52589
