### ISSUE TITLE
Enable merchants to adjust the visibility of individual elements of the Cross-Sells block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42550]
With woocommerce/woocommerce-blocks#6554, we implemented the Cross-Sells block. Currently, it's not possible to adjust the visibility of individual elements of the Cross-Sells block. This issue aims to adjust the visibility of individual elements, as used with the All Products block:

<img width="1438" alt="Screenshot 2022-10-24 at 18 18 32" src="https://user-images.githubusercontent.com/3323310/197514192-a5755211-251a-4047-a3be-5900d3912561.png">

**Comment by ralucaStan** [comment]
closing this as we're going to work on using the Product collection block instead. see https://github.com/woocommerce/woocommerce/issues/52589
