### ISSUE TITLE
Enable merchants to adjust rows and columns of the Cross-Sells block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42551]
With woocommerce/woocommerce-blocks#6554, we implemented the Cross-Sells block. Currently, it's only possible to select the number of visible Cross-Sells products. A merchant can choose between 1 and 6 visible Cross-Sells products. Independent of the selection, the products are always visible in a 3-column grid. This issue aims to implement the column and row selector, as used with the All Products block:

<img width="1440" alt="Screenshot 2022-10-24 at 18 11 57" src="https://user-images.githubusercontent.com/3323310/197513155-b73b3e1e-084d-40cd-9ceb-4f28c1e04a80.png">

**Comment by ralucaStan** [comment]
closing this as we're going to work on using the Product collection block instead. see https://github.com/woocommerce/woocommerce/issues/52589
