### ISSUE TITLE
CheckboxList and CheckboxControl: Label htmlFor and Input id should be unique

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#42579]
At the moment the `CheckboxControl` component (used by the `CheckboxList` component, that's utilized by filter blocks) sets the label `for` and input `id` to `option.value` - this results in the oversimplified markup, which has high potential for conflicts.

To quote @Aljullu from https://github.com/woocommerce/woocommerce-blocks/pull/7048:

> I noticed that some elements get a numeric id (ie: id="5"). I think that's problematic because ids need to be unique in the page and it's easy to introduce a clash at some point if we only use a number as the id. Ideally we should make sure those ids are really unique, either in the form of wc-blocks-products-by-rating-5 (or something along these lines) or [using uuid() as in GB](https://github.com/WordPress/gutenberg/blob/c4787412eef5959d8f2e519375352b8f4fed231a/test/native/integration-test-helpers/initialize-editor.js#L28). I know this is something that is inherited from the Filter by Attribute so it probably makes sense working on both blocks at the same time.

![191306720-82c7a791-fd52-49e3-baf0-a88b40e15296](https://user-images.githubusercontent.com/905781/191754687-49303c99-f32a-4341-8638-f376447113d2.png)

**Comment by samueljseay** [comment]
Looking at this I think it's already been solved, `useInstanceId` is used here to provide a unique ID: https://github.com/woocommerce/woocommerce-blocks/blob/064ec4793237daf76743ba6e95d42f03feecd1bd/packages/checkout/components/checkbox-control/index.tsx#L37-L38

**Comment by Aljullu** [comment]
I think we should also concatenate `instanceId` after `id` just to be safe.

Ie, a store that sells shoes might have "Shoe color" and "Shoe lace color" filters and if one color (ie: `red`) is available in both filters, the `id` of the checkbox will be duplicated, right?

**Comment by samueljseay** [comment]
@Aljullu can we just leave that up to the consumer of the component. If they want to pass ID they can be responsible to generate something unique?

They may want to override to a specific ID for some specific purpose. We could add some code comment documentation like "make sure its unique"

**Comment by Aljullu** [comment]
@samueljseay good point. You're right, it probably makes more sense to handle that from the consumer. This way `CheckboxControl` would not modify the `id` received from the props.

In the case of filter blocks, the consumer seems to be here:

https://github.com/woocommerce/woocommerce/blob/de774715bc5c161e7e6d223e9086e703876bd67d/plugins/woocommerce-blocks/packages/components/checkbox-list/index.tsx#L135-L137

So we should make so the `id` we pass to the component is unique at this point. Is that what you had in mind?

**Comment by samueljseay** [comment]
@Aljullu yup exactly 👍🏻
