### ISSUE TITLE
Explore prominent spots for the Cross-Sells block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#42570]
In pca54o-44z-p2#comment-4497, @pierorocca raised the idea of showing the Cross-Sells block in other prominent spots. This issue aims to experiment with this. 

## Examples

<img width="491" alt="Screenshot 2022-10-14 at 10 12 51" src="https://user-images.githubusercontent.com/3323310/195753846-16c2d194-cb87-4ca6-8b13-c452dc2adfc6.png">

Source: [https://www.amazon.com/Allen-Heath-32-Bit-Soundcards-AH-XONE/](https://www.amazon.com/Allen-Heath-32-Bit-Soundcards-AH-XONE/dp/B07DP9V3T5/ref=sr_1_1?crid=2HWHRA97KY7IR&keywords=xone+96&qid=1665717150&qu=eyJxc2MiOiIzLjA0IiwicXNhIjoiMi41NyIsInFzcCI6IjIuMDIifQ%3D%3D&sprefix=xone+9%2Caps%2C302&sr=8-1)
Spot: Product page

<img width="1102" alt="Screenshot 2022-10-14 at 10 18 55" src="https://user-images.githubusercontent.com/3323310/195754595-2523ad4b-b61d-4767-bc6e-ccb28e7b4dbc.png">

Source: https://www.apple.com/shop/bag
Spot: Cart page

<img width="974" alt="Screenshot 2022-10-14 at 10 23 51" src="https://user-images.githubusercontent.com/3323310/195755201-608f39af-69a5-474a-9e19-1337f4694f9e.png">

Source: [https://www.adidas.com/us/mexico-22-away-jersey/](https://www.adidas.com/us/mexico-22-away-jersey/HE8857.html)
Spot: Product page

**Comment by ralucaStan** [comment]
closing this as we're going to work on using the Product collection block instead. see https://github.com/woocommerce/woocommerce/issues/52589
