### ISSUE TITLE
[WooCommerce default styles] Sale prices are still underlined in the store homepage and grouped product page

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#42585]
## Describe the bug

As part of [Add WooCommerce default styles for block themes #33518](https://github.com/woocommerce/woocommerce/pull/33518), and as mentioned in pdnLyh-1uW-p2 (_"Ensure discounted prices aren’t underlined"_ section), the discounted prices should not be underlined in block themes. This is true in the single product page and the `/shop` page. However, the discounted prices are still underlined in two places:

- the homepage
- the grouped product page

I encountered this during pre-release testing of WooCommerce 6.9. Internal discussion here: pb22l9-1u6-p2#comment-1544

## To reproduce

1. Install WooCommerce 6.9 (currently in RC1)
2. Complete the setup wizard.
    - Make sure to create a homepage in the "Personalize your store" task.
    - When adding products, upload the sample products CSV file that comes with WooCommerce.
4. Install and activate a block theme other than Twenty Twenty-Two. In my tests, I observed this issue to be happening in Blockbase, Clove, and Archeo.
5. Go to the store's homepage.
6. Scroll down until you see the on-sale items. Notice that their sale prices are underlined. They shouldn't be.
7. Look for the "Logo Collection" product (which is a grouped product)  and click on it.
8. Notice that the sale price for "Beanie" was also underlined.

## Expected behavior

Sale prices aren't underlined in the homepage and grouped product page, as mentioned in pdnLyh-1uW-p2 (_"Ensure discounted prices aren’t underlined"_ section)

## Screenshots

**Homepage**
<img width="670" alt="Screen Shot 2022-09-13 at 3 55 38 PM" src="https://user-images.githubusercontent.com/4509348/189844263-e21edae4-0ffe-4de1-95c1-d44f4e8b10b7.png">

**Grouped product page**
<img width="1057" alt="Screen Shot 2022-09-13 at 3 56 14 PM" src="https://user-images.githubusercontent.com/4509348/189844343-3b4bd9b4-e9d7-40eb-9c48-9f8be5af2e2c.png">

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.9 RC1
-   WooCommerce Blocks version: None
-   Site language: English
-   Any other plugins installed: None

**Comment by ralucaStan** [comment]
still a valid issue, this needs to be fixed in the `woocommerce-blocktheme.scss`
