### ISSUE TITLE
Single product templates that have been edited by the merchant can't be selected in the edit product screen 

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#42630]
This issue might require changes in WC core or Gutenberg repos, but I'm creating this in WC Blocks repo for ease of tracking it.

## To reproduce

1. In Twenty Twenty Two, create a new template, ie: `/themes/twentytwentytwo/templates/another-single-product.html`

```HTML
<!-- wp:template-part {"slug":"header"} /-->
<!-- wp:group {"layout":{"inherit":true}} -->
<div class="wp-block-group"><!-- wp:woocommerce/legacy-template {"template":"single-product"} /--></div>
<!-- /wp:group -->
<!-- wp:template-part {"slug":"footer"} /-->
```

2. Add it to `customTemplates` in `theme.json`:

```JSON
{
	"version": 2,
	"customTemplates": [
		...
		{
			"name": "another-single-product",
			"title": "Another Single Product Template",
			"postTypes": [
				"product"
			]
		}
	],
	...
}
```

3. Go to WooCommerce > Products and edit one of the products.
4. Notice you can select between the default template and _Another Single Product Template_.

<img src="https://user-images.githubusercontent.com/3616980/171038454-f6593997-0cac-4f1a-ae06-c18b1a3e75ae.png" alt="Screenshot showing the select to choose the template." width="304" />

5. Go to Appearance > Editor > Templates > Another Single Product Template, make an edit and save the edited template.
6. Now, go back to editing a product.
7. Notice _Another Single Product Template_ is no longer listed as an available template.

## Expected behavior

If the merchant makes an edit to a template that has `postTypes: [ 'product' ]`, it should still be available when editing or creating products.

## More info
I think the issue comes from the fact that [WC uses](https://github.com/woocommerce/woocommerce/blob/61d9d0043fe4fe9c0355194e7856619b3d6cb76c/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php#L274-L276) [`get_block_template()`](https://github.com/WordPress/wordpress-develop/blob/91dc2d1b42d8208f257947b9379a37d4df514747/src/wp-includes/block-template-utils.php#L750), which internally calls [`_build_block_template_result_from_post()`](https://github.com/WordPress/wordpress-develop/blob/91dc2d1b42d8208f257947b9379a37d4df514747/src/wp-includes/block-template-utils.php#L550). And the latter, doesn't add a `post_types` attribute to templates returned.

**Comment by Aljullu** [comment]
I created an issue in trac, I think that should ideally be fixed upstream:

https://core.trac.wordpress.org/ticket/55881#ticket

**Comment by tjcafferkey** [comment]
Can confirm this has been fixed.
