### ISSUE TITLE
Edits to Product Archive template are not visible in the Product Category and Product Tag pages

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#42656]
I might be understanding this wrong, but I think that if Product Category and Product Tag templates haven't been customized and don't have a custom template set by the theme, but the Product Archive has been customized by the user, the Product Archive template should take priority.

## To reproduce
1. With WP 5.9 and a Twenty Twenty Two, go to Appearance > Editor > Templates.
2. Edit the Product Archive template.
3. Now, go to a product category or product tag page in the frontend (ie: `/product-category/clothing/`).
4. Notice changes are not applied in that page.

## Expected behavior
Any change in the Product Archive template should be applied to the Product Category and Product Tag pages if they hadn't been customized or the theme doesn't have a specific template for them.

## Screenshots
_Editor:_
![imatge](https://user-images.githubusercontent.com/3616980/148247074-254a4366-85ae-4dde-9c94-d70c5149d6ac.png)

_Frontend:_
![imatge](https://user-images.githubusercontent.com/3616980/148247112-1946023b-e3c0-47c1-aa4a-c2c71e5bc8ab.png)

### WordPress (please complete the following information):
* Core version: tested in WP 5.9 beta 4 and RC 1
* Gutenberg version (if installed): tested with GB 12.3.0 and disabled
* WooCommerce version: `trunk` and 6.1 RC1
* WooCommerce Blocks version: `trunk` and disabled

**Comment by tjcafferkey** [comment]
I can see an argument for it working the way you've described in this PR _and_ the way it currently works. It's worth noting as well that if we decide it should behave the way you've outlined above then this should also apply to themes who only have the `archive-product.html` file. Should they edit this file from the theme in the Site Editor it should also be applied to Category and Tag pages if they haven't already been customised.

We just need to come to a decision of the correct behaviour before moving forward with this I think.

**Comment by Aljullu** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/7712.
