### ISSUE TITLE
Optimistic Updates for Cart

### ISSUE THREAD

**Issue by alexflorisca** [woothemes/woocommerce#42650]
I noticed while changing the quantity on items in the Cart, the totals don't update straight away. They wait for the store api fetch to return before the UI is updated. I think this could be improved with an optimistic update to the UI.

## Describe the solution you'd like
I'm not sure of how we could implement this technically with @wordpress/data, but I wanted to record it here and open it for discussion and for this to be fleshed out if people think it's worth doing.

https://user-images.githubusercontent.com/3966773/155382425-396eabce-2705-4a76-95f3-077b670e2809.mov

(Don't ask why I've got a £50 tennis court and a fridge in my cart!)

**Comment by opr** [comment]
Related (old) issue https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1876

**Comment by mikejolley** [comment]
I think we can close this (stale) issue as we've kinda gone in a different direction with this, and due to past issues discovered attempting this in the client.
