### ISSUE TITLE
Export of checkout UI base components

### ISSUE THREAD

**Issue by frosso** [woothemes/woocommerce#42660]
## Is your feature request related to a problem? Please describe.
It would be awesome if some of the base UI components on the checkout page were exported/exposed to be available for consumers.
This way consumers can leverage them in custom UC flows, ensuring that their behavior matches the one of the "default" elements.

![Screen Shot 2021-12-10 at 3 24 26 PM](https://user-images.githubusercontent.com/273592/145643167-d7434ca9-91b8-4b5b-baff-d0aa50f4d291.png)

## Describe the solution you'd like
Ideally, the following components would be exposed:
- `input[type="text"]`
- `input[type="checkbox"]`
- `input[type="radio"]`
- `textarea`
- `select` (although I noticed that a select element (for country/state) is really just an input component with additional options)

Also ideally, the API to add/show error messages would be available.

I'm not sure if the best solution is to:
- Add these exported components to one of the existing scripts
- Creating a new independent script handle (and "package") for these components

It would be great if the components could work both as "controlled" and ["uncontrolled" components](https://reactjs.org/docs/uncontrolled-components.html) (via a `defaultValue` prop, for example).

## Describe alternatives you've considered
I considered both:
- Creating custom versions of the UI components (but there's a risk that the behavior wouldn't match, as updates/fixes come in)
- Copy/pasting the code from the repository (same risk as above + code duplication)

## Additional context
pca54o-2mQ-p2#comment-3278

**Comment by ralucaStan** [comment]
At the moment we export these components https://github.com/woocommerce/woocommerce-blocks/blob/trunk/packages/checkout/components/index.js. Some are connected to the data store, like ValidatedTextInput and ValidationInputError, and some are presentational components.

They are implemented with Gutenberg's `@wordpress-components` and we recently found out that those are not intended for usage in the front-end https://github.com/woocommerce/woocommerce-blocks/issues/8452

So we might need to wait for replacing those before we prepare our components for export.

**Comment by passatgt** [comment]
Is there any update on this?

**Comment by ralucaStan** [comment]
@passatgt we are exporting some [components](https://github.com/woocommerce/woocommerce-blocks/tree/ac77781122a3d064baee1f00e56493735c1cf05a/packages/checkout/components) but we still need to revisit the list of exports. Is there any component, in particular, you are interested in?

**Comment by passatgt** [comment]
> @passatgt we are exporting some [components](https://github.com/woocommerce/woocommerce-blocks/tree/ac77781122a3d064baee1f00e56493735c1cf05a/packages/checkout/components) but we still need to revisit the list of exports. Is there any component, in particular, you are interested in?

Thanks! I was able to use ValidatedTextInput, and i'm missing some radio inputs, like you have for the payment and shipping selector.

**Comment by ralucaStan** [comment]
Recently we've worked on exporting some components https://github.com/woocommerce/woocommerce-blocks/discussions/11238.

If there are components still needed @frosso please open separate tickets.
