### ISSUE TITLE
No payment methods available

### ISSUE THREAD

**Issue by ashvinistspl** [woothemes/woocommerce#42699]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have installed WordPress 6.4.2 and WooCommerce version 8.3.1. I want to integrate a payment gateway, but it is giving an error: 'No payment method available,' even though Razorpay is installed.

### Expected behavior

Want payment gateway integration

### Actual behavior

Giving error: No payment method available

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/153623274/e5adec50-29e5-447e-8ab5-fcc43ff6dfcd)

### WordPress Environment

Wordpress 6.4.2
Woocommerce 8.3.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by fullstack1995** [comment]
i have the same issus
just installed new wordpress and woocommerce and a custom plugin for payment
wordpress version: 6.4.2
woocommerce version: 8.4.0
