### ISSUE TITLE
Changelog Update for 8.4.0

### ISSUE THREAD

**Issue by MichaelHabib** [woothemes/woocommerce#42734]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.
https://github.com/woocommerce/woocommerce/blob/8.4.0/changelog.txt

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.
8.4 change log doesn't seem to have been updated. 

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?
Important for debugging and upgrade planning.

## Additional Context

> Add any other context, references, or screenshots that support your suggestion.

**Comment by rrennick** [comment]
@woocommerce/solaris Also seeing this in `trunk`.

**Comment by jonathansadowski** [comment]
Noting here that we don't currently update the release branch after a final release, but trunk should have been updated. I've linked a PR that was created last week to update it: #42732
