### ISSUE TITLE
[Enhancement]: Switching lightbox products images from PhotoSwipe - v4.1.3 - 2019-01-08 to default block images lightbox anounced in WordPress 6.4.

### ISSUE THREAD

**Issue by Felix-Kiz** [woothemes/woocommerce#42749]
### Describe the solution you'd like

For this moment WooCommerce using PhotoSwipe - v4.1.3 - 2019-01-08 library for lightbox functionality. At the same time WordPress since version 6.4 use another "default" lightbox, for now only for image blocks, in block editor. It could be a good idea to unify user experience and use one "default" lightbox for all images, including WooCommerce products images.

### Describe alternatives you've considered

In WooCommerce it could be as switcher from PhotoSwipe - v4.1.3 - 2019-01-08 to "default" lightbox, for backward compatibility.
Currently **to unify lightbox for all images on WordPress site** it is possible to use [Lightbox with PhotoSwipe plugin](https://wordpress.org/plugins/lightbox-photoswipe/) with settings: PhotoSwipe version to use > version 4, wich makes all images use PhotoSwipe - v4.x.x library.
Attached are images of Lightbox with PhotoSwipe plugin settings, also the PhotoSwipe v4.x.x lightbox (black background), "default" lightbox (white background).
![default_lightbox_image_launched](https://github.com/woocommerce/woocommerce/assets/153593890/9eb941dd-1abe-4c40-b429-f5e667f7d754)
![default_lightbox_image_ready](https://github.com/woocommerce/woocommerce/assets/153593890/f758002c-f5e2-4772-9f79-4555b02e91a5)
![lightbox_PhotoSwipe_settings](https://github.com/woocommerce/woocommerce/assets/153593890/1dba607f-69c5-4b34-8974-db76e0531b8d)
![PhotoSwipe_lightbox_image_launched](https://github.com/woocommerce/woocommerce/assets/153593890/0c62ca79-8b7d-4321-b60b-2fe784e180d7)

**Comment by tjcafferkey** [comment]
Thanks for submitting this issue @Felix-Kiz!

We are currently in the final stages of creating a new Product Gallery block which does not rely on dependencies such as PhotoSwipe. You can follow its progress here https://github.com/woocommerce/woocommerce/issues/42335

I'm going to go ahead and close this issue but feel free to reopen it if there's anything further 😄
