### ISSUE TITLE
Block Hooks API: Check if block isn't already present before auto-inserting.

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#42756]
When [auto-inserting the Mini Cart into approved themes](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php#L591) we first need to check whether the theme already has the Mini Cart block there so we don't auto-insert a duplicate.

This should be possible for us to do since it was [included in WP 6.4.2](https://core.trac.wordpress.org/ticket/59882)

**Comment by tjcafferkey** [comment]
@nerrad regarding this issue, [I see you've already accounted for this logic](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php#L649-L660). Do you mean when I start abstracting this logic for other blocks (e.g. Customer block https://github.com/woocommerce/woocommerce/issues/42757) to implement this more broadly as part of that task?

**Comment by nerrad** [comment]
Oh yea! I guess it should be confirmed that the PR I submitted for WP worked. I tested similar logic for filtering there so what I added to Woo Blocks _should_ work. If it does then the attached comment block can be removed.

> Do you mean when I start abstracting this logic for other blocks (e.g. Customer block https://github.com/woocommerce/woocommerce/issues/42757) to implement this more broadly as part of that task?

Yes, that would be a good followup. This spot would also be a good place to experiment with using the `HTML API` to detect/handle cases in template parts or patterns where the layout isn't that great and injecting the block after the navigation block is problematic.

**Comment by tjcafferkey** [comment]
>I guess it should be confirmed that the PR I submitted for WP worked.

Yep, as part of enabling it for TT3/TT2 I checked that the logic works as expected and it does! I'll remove the comment block when I come to this task.

>This spot would also be a good place to experiment with using the HTML API to detect/handle cases in template parts or patterns where the layout isn't that great and injecting the block after the navigation block is problematic.

Good thinking! I'll make sure to do that too.
