### ISSUE TITLE
Introduce API to register basic text field and render it in Checkout Address Block and Editor

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42771]
Introduce a PHP-only API that would allow a third-party developer to register a custom field in Checkout Block.
The API should handle rendering the field in Checkout (by adding it to the locale list), and handle receiving them on the backend level and saving them to meta fields.

Instead of having the work be in a feature branch and risk making it outdated, it should be behind a feature flag instead.

- [ ] API can be called from a direct function (no need for developer to load the DI container).
- [ ] Render within the form in both editor and frontend.
- [ ] Should be passed automatically to Store API request.
- [ ] Should be passed after typing and on order placement.
- [ ] Should accept errors from the server (maybe follow up).
- [ ] Be saved to meta data of an order.

**Comment by ralucaStan** [comment]
In my opinion, we should be splitting this ticket even further to ensure smooth testing and a better understanding of the expected result.

The way I see this we might need:
- 1 Ticket per input type we'll support with a full breakdown of the API and customization options it presents. Automated testing should be included in each PR
- 1 ticket per checkout section listing the allowed custom input types and positions, surface area etc.  Automated testing should be included in each PR

I'll leave it up to you @senadir to make the best call here, but I think we should strive to define tickets that offer a complete overview of the expected result. The goal is to have smaller, atomic PRs, that are easier to review and test and could pe worked on in parallel as much as possible

**Comment by senadir** [comment]
For now, this only support a single field type (text and text like fields). It also only support adding the field to address area for now (the most complex case) and also recently added support to saving the field to user meta.

I will limit it to this for now. I would appreciate if we move the automated tests ticket to after a couple of main issues are done (and make it an explicit issue that's required to graduate this project).

This is the only large issue out of the rest, because it sets the foundation, and my goal is that each PR merged should work as is, and given this is a foundation PR, it does cover a lot of ground, mainly:

- The class that would accept registration from developers.
- The functionality to transform what the developer added to meaningful data.
- Passing that data to Checkout.
- Accepting and rendering those fields.
- Passing those fields back to Store API.
- Accepting them in Store API, validating them, and saving them.
- Passing them back to Checkout in subsequent requests.

**Comment by senadir** [comment]
@ralucaStan for sake for completion, I added those 2 issues to separate them from this one

https://github.com/woocommerce/woocommerce/issues/42082
https://github.com/woocommerce/woocommerce/issues/42081

**Comment by ralucaStan** [comment]
Thank you Nadir. 

> I will limit it to this for now. I would appreciate if we move the automated tests ticket to after a couple of main issues are done (and make it an explicit issue that's required to graduate this project).

Could you also create the tickets for testing? I still recommend attaching to the original PR some unit tests. I understand that the experience might evolve so E2E tests might need refactoring, but I think that when it comes to the API we should strive to make tests complementary to the work, as a way of also validating the expected result.
