### ISSUE TITLE
Surface custom fields values in Admin order page.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42777]
Custom fields should be visible in the WooCommerce admin order page. Ideally on the correct section (Billing, Shipping). We might need to introduce a new section for additional fields.

<img width="744" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/6c4c2941-3d9a-43b8-aa21-0582f72f853c">

**Comment by elizaan36** [comment]
hey @senadir Let me know if this makes sense. Not all fields would appear at the same time obviously, but this is the thinking. There are separate locations for content coming from each of the following sections with custom fields:

- Shipping
- Billing
- Contact info
- Additional information

![Order details custom fields](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/88e1cf58-ff2d-46c4-821b-673221b6337a)

It makes sense for the additional information to appear here after the order notes.
