### ISSUE TITLE
Surface custom fields in Emails

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42775]
Custom fields should be visible in the emails sent to merchants and customers.

**Comment by elizaan36** [comment]
We can include any custom content in the same placement that it's included in the order confirmation. 

For Custom shipping and billing fields, these can be added directly to the addresses as a new line. For Contact information fields, this information can be added as part of the Shipping and Billing address summary on the email as well.
![Surface custom fields in emails - Merchant - Contact Shipping Billing](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/08514b01-eae6-4806-b12f-c048f704b329)

For Additional information, a new bounding container could be created to include the info.
![Surface custom fields in emails - Merchant](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/20e8f3ce-ede7-457a-929b-ef9042fb3da2)

In the mockups the text is larger for illustration purposes. Text styles, size, colors, and spacing of custom fields content should align with the rest of the content on the page.
