### ISSUE TITLE
Add backward-compatibility with existing woocommerce_checkout_fields

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42774]
WooCommerce offers a `woocommerce_checkout_fields` that allows people to add new fields, additional fields from that API should be respected and translated into new API registrations with sane defaults for missing properties.

It's unclear yet how we should do server-side handling of fields, and what kind of APIs people are using, we will look into adding a compatibility layer that would mimic $_POST but this is up to consideration first.

**Comment by wvega** [comment]
Will this compatibility layer allow marking the standard billing and shipping phone fields as required?

We can currently use the `woocommerce_checkout_fields` filter to make those fields required in the checkout experience provided by the shortcode. However, the blocks experience have the phone field not required by default and there doesn't seem to be a way to change that programatically, at least not from the backend.

**Comment by senadir** [comment]
You can still use `woocommerce_get_country_locale` to make them required. It's unlikely to support editing core fields via the `woocommerce_checkout_fields` at all. 

Fields shouldn't be required on general, as it's a country by country settings.
