### ISSUE TITLE
Surface custom fields in Order Confirmation page.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42776]
Custom fields should be visible in the Order Confirmation page shown to customers after placing an order.

**Comment by elizaan36** [comment]
Similar to the [email](https://github.com/woocommerce/woocommerce/issues/42775), the order confirmation can include custom content in the following ways.

Shopper view
- For Custom shipping and billing fields, these can be added directly to the addresses as a new line. For Contact information fields, this information can be added as part of the Shipping and Billing address summary on the email as well.
- For Additional information, a new bounding container could be created to include the info.

![Shopper - Additional info](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/b7097cd1-e13f-4ace-ac2c-4e861e680023)

Merchant/editor view
Also discussed [here](https://github.com/woocommerce/woocommerce/issues/42092), the editor view can present the additional information section separately from the rest of the content. However it's unclear how much of the custom fields content can be previewed in these views.

<img width="1440" alt="Surface custom fields in the order confirmation - Additional information" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/b745e0df-ace5-4c13-9a2b-b2a33ebff5c6">
