### ISSUE TITLE
Add the ability to edit custom fields from the WC Order page.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42778]
Fields that are now visible after https://github.com/woocommerce/woocommerce/issues/42777 is done should also be edited from that screen.

Ideally the fields would show up there like the rest of them. If the field is still registered, it should have its metadata visible otherwise the key and value should be used.

<img width="747" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/dfda2b7f-6b3f-4b98-a3c0-7cf79f3cb825">

**Comment by elizaan36** [comment]
The content from custom fields can be edited in the same order as the placement of the display [as shown here](https://github.com/woocommerce/woocommerce/issues/42777). I don't see any reason why this would need to change but let me know if I'm missing something.
