### ISSUE TITLE
Notices in a session aren't being hydrated into checkout block on entry

### ISSUE THREAD

**Issue by brettshumaker** [woothemes/woocommerce#42787]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If the user's session contains a notice, that notice isn't displayed on the checkout block or cart block page on page load. It is, however, shown in the `Store Notices` block if it exists on the page.

### Expected behavior

Store notices in the session are displayed when the block checkout or cart pages are loaded.

### Actual behavior

A store notice in the user session is not displayed when the block checkout or cart pages are loaded

### Steps to reproduce

```php
add_action('template_redirect', 'add_wc_notice_and_redirect_to_checkout');

function add_wc_notice_and_redirect_to_checkout() {
    if ( isset( $_GET['debug_notice'] ) ) {
        wc_add_notice( 'This is a debug notice!', 'error' );

        // Redirect to the checkout page
        wp_safe_redirect( wc_get_checkout_url() );
        exit;
    }
}
```

1. Add the code snippet above to your test site. It will add a notice and redirect you to the checkout page when the `debug_notice` URL parameter is present.
2. Visit `yoursite.com/?debug_notice`
3. You'll be redirected to the checkout page with no notice being displayed.

### WordPress Environment

-   WordPress version: 6.4.2
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks version: 11.7.0 (Also present on 11.4.9)

-   OS: MacOS
-   Browser Brave
-   Version 1.60.125

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
@opr Since this issue is related to checkout block, could you please review it and let me know if I should replace the label "team: Kirigami & Origami" with "team: Rubik"?

**Comment by opr** [comment]
@imanish003 yes this is a Rubik issue! I've updated the label. Thanks 🤟🏻

**Comment by wavvves** [comment]
Verified on non-block theme's checkout block and block-based theme's cart and checkout templates.
Seems to be a regression from work done in https://github.com/woocommerce/woocommerce-blocks/pull/10151
On the template side we probably need to re-add the block:
`<!-- wp:woocommerce/store-notices /-->`

**Comment by wjrosa** [comment]
Hi @woocommerce/rubik ! 👋  This issue is happening again for us (@woocommerce/quark) in https://github.com/woocommerce/woocommerce-gateway-stripe . You can test it on the `develop` branch (with Giropay again, which raised this issue, or any new BNPL method such as Klarna or Affirm). Did something change on how we should add notices? Our current code is:
```
			/* translators: localized exception message */
			$order->update_status( 'failed', sprintf( __( 'UPE payment failed: %s', 'woocommerce-gateway-stripe' ), $e->getMessage() ) );

			wc_add_notice( $e->getMessage(), 'error' );
			wp_safe_redirect( wc_get_checkout_url() );
			exit;
```

**Comment by opr** [comment]
@wjrosa are you using a classic theme or a block theme? Looks like notices don't get shown in classic themes (e.g. Storefront), but they do in block themes (e.g. TT4).

If you can confirm this I think we should create a new issue to ensure store notices are shown in classic themes. Thanks!

**Comment by wjrosa** [comment]
Hi @opr ! Sorry for the delay. I haven't changed any themes, so I believe it is the default block theme. Did you test it with a current version of https://github.com/woocommerce/woocommerce-gateway-stripe?

**Comment by opr** [comment]
@senadir as porter could you take a look at this and assess if we should open a new issue? Thanks

**Comment by annemirasol** [comment]
> @wjrosa are you using a classic theme or a block theme? Looks like notices don't get shown in classic themes (e.g. Storefront), but they do in block themes (e.g. TT4).
> 
> If you can confirm this I think we should create a new issue to ensure store notices are shown in classic themes. Thanks!

@opr Confirming the issue affects classic themes, e.g. Storefront, and not block themes, e.g. TT4. Likely related to https://github.com/woocommerce/woocommerce/issues/51272
