### ISSUE TITLE
How to add additional fee for specific payment method on checkout page with Woocommerce Gutenberg block? [DOC-REQ]

### ISSUE THREAD

**Issue by poragraihan** [woothemes/woocommerce#42809]
When the checkout page is generated by 'woocommerce_checkout' shortcode, we can use 'woocommerce_cart_calculate_fees' hook to add an additional fee for any specific payment method with this js code to add the fee and change the total amount.

$("body").trigger("update_checkout");

But if the checkout page is generated by Woocommerce Gutenberg block, this code doesn't work.

**Comment by opr** [comment]
Hi, thanks for your question, I added it, and an answer to https://github.com/woocommerce/woocommerce/issues/42185#issuecomment-1862769537

To achieve this you will need to:

1. Add a callback for [`extensionCartUpdate`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md) on the server.
2. Add a hook to listen for the payment method changing - this should then call `extensionCartUpdate` with your namespace.

```js
wp.hooks.addAction(
	'experimental__woocommerce_blocks-checkout-set-active-payment-method',
	YOUR_NAMESPACE, function( payment_method ) {
		window.wc.blocksCheckout.extensionCartUpdate( {
	    	namespace: YOUR_NAMESPACE
	   		data: {
	        	payment_method: payment_method.value
	    	}
		} );
	}
);
```

I'll close this issue as I believe there's nothing actionable from our side, but feel free to reopen it if things aren't working as expected.
