### ISSUE TITLE
Product Editor: SlotFill for header items

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#42805]
## Description

A SlotFill should be implemented to allow for the header to be extended by extensions, with popovers and modals.

**Note:**
We may want to make use of `PinnedItems` from GB instead, see comment below: https://github.com/woocommerce/woocommerce/issues/42805#issuecomment-1877196495

<img width="1254" alt="Screenshot 2023-12-13 at 19 54 21" src="https://github.com/woocommerce/woocommerce/assets/2098816/6151318f-9802-4b64-b815-391ade928699">

There currently exists an experimental SlotFill `WooHeaderItem` that can be used to add items:

```jsx
<WooHeaderItem name="product">
    <Button>Hi there</Button>
</WooHeaderItem>
```

However, this SlotFill is very unopinionated, and it places the burden of ensuring that the UX is correct on the extension developer. A more opinionated SlotFill should be created that allows only specific types of items, namely popovers and modals, to be added to a specific "plugins" section, that auto-collapses.

See the "Top bar (header)" section of the extensibility guidelines: 

https://github.com/woocommerce/woocommerce/blob/trunk/docs/product-editor-development/product-editor-extensibility-guidelines.md#top-bar-header-future-feature

## API

```jsx
<PluginHeaderItemPopover
    label={}
    icon={}
    order={}
>
    <div>Popover content</div>
</PluginHeaderItemPopover>

<PluginHeaderItemModal
    label={}
    icon={}
    order={}
>
  <div>Modal content</div>
</PluginHeaderItemModal>
```

```[tasklist]
### Development tasks
- [ ] Implement `PluginHeaderItemPopover`
- [ ] Implement `PluginHeaderItemModal`
```

## Acceptance criteria

- [ ] Popovers can be added to the header
- [ ] Modals can be added to the header
- [ ] Documentation exists
- [ ] The `WooHeaderItem` SlotFill still exists, for lower-level extensibility (we use it internally; in the future perhaps it will be deprecated in favor of other more specific SlotFills)

**Comment by louwie17** [comment]
**Note**
We may want to make use of the `PinnedItems.Slot` in this area that WordPress also follows in its header items for the post and site editor: https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20PinnedItems.Slot&type=code

It looks to be pretty easy for use

**Comment by octaedro** [comment]
Hi there 👋

I have a couple of questions related to this issue.

What should we use when there is no `icon`? Should the icon be required?

This issue aims to  create a couple of `slotFills` for header items, but there are a few things we should think of in follow-up issues, regarding [the extensibility guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/docs/product-editor-development/product-editor-extensibility-guidelines.md#top-bar-header-future-feature):

> Each top bar extension has its unique icon in the top navigation bar.

This could be challenging since we're receiving icons without identifiers. Maybe we should require an `id` for the extension and compare that.

> Note that when the number of extensions exceeds 4, they're truncated in a dropdown menu.

We will need an icon for when we decide to present the dropdown menu.

Besides I can envision two ways to accomplish this restriction:
- Record the registered fills, and depending on the number of registered fills, we either render the icons directly or display the dropdown.
- Create our own slotFill (untying our slotFill from `PinnedItems`) to control the fill number and render the dropdown when there are more than 4.

I'm inclined to favor the second approach, as the first one seems to somewhat misuse the purpose of slotFills.

**Comment by louwie17** [comment]
Thanks for the questions @octaedro, here are my thoughts, but @mattsherman might have some additional ones ( also feel free to disagree with my input Matt :) )

> What should we use when there is no `icon`? Should the icon be required?

This one I am not sure, it appears that GB gets folks to use the `ComplementaryArea` component which in turn uses the `PinnedItems`. It tends to only use icons by looks of it in the header area.
It doesn't look like an icon is required for the `ComplementaryArea`.
If `ComplementaryArea` doesn't fit our use case btw, we should just create a wrapper ProductHeaderItem component that makes use of `PinnedItems.Slot` under the hood.

> This issue aims to create a couple of `slotFills` for header items, but there are a few things we should think of in follow-up issues, regarding [the extensibility guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/docs/product-editor-development/product-editor-extensibility-guidelines.md#top-bar-header-future-feature):
> 
> > Each top bar extension has its unique icon in the top navigation bar.
> This could be challenging since we're receiving icons without identifiers. Maybe we should require an `id` for the extension and compare that.

Do we have wireframes of examples of this? In my mind it would be up to the plugin developer to pass in the `icon` into the slot fill component we provide, so we don't have to do any `id` matching on our end.

> > Note that when the number of extensions exceeds 4, they're truncated in a dropdown menu.

Hmm could we push back on this guideline? I would say we should follow GB approach. They only push the icons into a dropdown if its displayed on a small screen size ( [more menu logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/more-menu/index.js#L34-L38), [header logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/index.js#L188C1-L190) ).

It may actually come across strange if we hide some items in the dropdown, unless we have a good way of showing the overflow state. In this case, it may make more sense to render them and hide some with CSS and on hover they are all being shown ( or something to that affect ).

> We will need an icon for when we decide to present the dropdown menu.
> 
> Besides I can envision two ways to accomplish this restriction:
> 
> * Record the registered fills, and depending on the number of registered fills, we either render the icons directly or display the dropdown.

This is usually pretty easily doable by the use of the `useSlotFills` hook, so I don't think it goes against a slot fill approach. The only caveat as mentioned above is that it seems strange to render some in the more menu and some not.

> * Create our own slotFill (untying our slotFill from `PinnedItems`) to control the fill number and render the dropdown when there are more than 4.
> 
> I'm inclined to favor the second approach, as the first one seems to somewhat misuse the purpose of slotFills.

I would only be in favour of the second approach if we still use `PinnedItems` under the hood, I don't think we want to create to many more custom Slots for areas that already have them within the GB world and can be identifiable with the scope. Of-course we can/should write wrapper components so folks don't have to worry about the `scope`.

**Comment by octaedro** [comment]
Thank you @louwie17 for answering my questions.

> It doesn't look like an icon is required for the ComplementaryArea.
> If ComplementaryArea doesn't fit our use case btw, we should just create a wrapper ProductHeaderItem component that makes use of PinnedItems.Slot under the hood.

Yes, I think that `ComplementaryArea` was thought for sidebars, this is why I created a wrapper to use PinnedItems inside  [in my PR](https://github.com/woocommerce/woocommerce/pull/43687). I was just concern about the other requirements from the extensibility guidelines.

> In this case, it may make more sense to render them and hide some with CSS and on hover they are all being shown ( or something to that affect ).

I like this approach! I prefer to continue using the `PinnedItems` too.

> Hmm could we push back on this guideline? I would say we should follow GB approach. They only push the icons into a dropdown if its displayed on a small screen size ( [more menu logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/more-menu/index.js#L34-L38), [header logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/index.js#L188C1-L190) ).

Yeah, I noticed the same and I concur with you.

> I would only be in favour of the second approach if we still use PinnedItems under the hood, I don't think we want to create to many more custom Slots for areas that already have them within the GB world and can be identifiable with the scope. Of-course we can/should write wrapper components so folks don't have to worry about the scope.

Yes, the approach I took in my PR was a wrapper component to make everything easier for 3PDs.

Another small caveat of `PinnedItems` (that I mentioned in my PR) is that it seems like [PinnedItems doesn't order the `fills`](https://github.com/WordPress/gutenberg/blob/trunk/packages/interface/src/components/pinned-items/index.js) items. The first to arrive is the first to be shown. I think that not ordering the fills is not a big deal though.

**Comment by mattsherman** [comment]
> What should we use when there is no icon? Should the icon be required?

We should use a default icon. That makes it easy for extensions to start playing around and building out things.

> Each top bar extension has its unique icon in the top navigation bar.

We can't really enforce this, unless we graphically compare icons. It is just a guideline.

> Hmm could we push back on this guideline? I would say we should follow GB approach. They only push the icons into a dropdown if its displayed on a small screen size ( [more menu logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/more-menu/index.js#L34-L38), [header logic](https://github.com/WordPress/gutenberg/blob/cdd6cecbc5bbf5ce5f55da0301246acfcf56c426/packages/edit-post/src/components/header/index.js#L188C1-L190) ).

> It may actually come across strange if we hide some items in the dropdown, unless we have a good way of showing the overflow state. In this case, it may make more sense to render them and hide some with CSS and on hover they are all being shown ( or something to that affect ).

Agreed.

> I don't think we want to create to many more custom Slots for areas that already have them within the GB world and can be identifiable with the scope. Of-course we can/should write wrapper components so folks don't have to worry about the scope.

As long as we have wrappers, I think that is fine.

> Another small caveat of PinnedItems (that I mentioned in my PR) is that it seems like [PinnedItems doesn't order the fills](https://github.com/WordPress/gutenberg/blob/trunk/packages/interface/src/components/pinned-items/index.js) items. The first to arrive is the first to be shown. I think that not ordering the fills is not a big deal though.

I'd argue that if non-ordered fills for these are fine in GB currently, that is a reasonable limitation for us now too.

All this said, I don't think it buys us a ton to reuse GB slots... SlotFills are just thin wrappers that direct renders to the correct place in the DOM. They don't have complex UX interactions. I'm mildly concerned that by tying our implementation to GB SlotFills we may see breakage in the future if they make non-backwards compatible changes.
