### ISSUE TITLE
HPOS -- PHP Fatal error:  Uncaught Exception: The authoritative table for orders storage can't be changed while there are orders out of sync in .../plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:312

### ISSUE THREAD

**Issue by pranavmtn** [woothemes/woocommerce#42826]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP Fatal error: Uncaught Exception: The authoritative table for orders storage can't be changed while there are orders out of sync in /.../public_html/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:312

### Expected behavior

There should NOT be any critical errors.

### Actual behavior

Showing Critical Error : There has been a critical error on this website. https://prnt.sc/BWn6hymOD8Hq

### Steps to reproduce

1.Open : www.yourwebsite.com/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features
2.Enable Compatibility mode turn ON then after sync done, turn off.
3.Choose any Legacy or HPOS settings(say we selected legacy option) .
4.Place a new order.
5. I kept the settings page as not refreshed.It will look this https://prnt.sc/pIbymbJy8g3B
6. Select Legacy Option
7. Site shows the critical Error

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://plugintest.storepro.dev
Site address (URL): https://plugintest.storepro.dev
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58 (Debian)
PHP Version: 8.0.30
PHP Post Max Size: 500 MB
PHP Time Limit: 900
PHP Max Input Vars: 12500
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.6.3-MariaDB-1:10.6.3+maria~buster-log
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 10.44MB
Database Data Size: 7.32MB
Database Index Size: 3.12MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.47MB + Index: 0.50MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_renewal_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_action_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_api_log_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_recipe_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uap_tokens_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_trigger_log_meta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_avatax_tax_codes: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.09MB + Index: 0.20MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
page: 8
post: 3
product: 27
product_variation: 7
revision: 1
shop_order: 97
shop_order_refund: 6
shop_subscription: 9
uo-recipe: 1
uo-trigger: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Disable Emails: by WebAware – 1.8.1
WooFunding Toolkit: by Unique Web Marketers – 3.0
Avalara AvaTax: by Avalara – 2.6.1
WooCommerce PayPal Payments: by WooCommerce – 2.4.1 (update to version 2.4.2 is available)
WooCommerce Square: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 8.4.0
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (11) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Buy X Get Y Free by StorePro: by StorePro – 1.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2
Misha Update Checker: by Misha Rudrastyh – 1.5
Subscriptions Renewal Reminders: by StorePro – 1.1.9
Subscriptions Renewal Reminders Premium: by StorePro – 1.0.1
Super Fast Side Cart for WooCommerce: by StorePro – 1.0.7
Uncanny Automator: by Uncanny Automator
Uncanny Owl – 5.2.0.1

WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.3
Woo Subscriptions: by WooCommerce – 5.6.0
WP Rollback: by GiveWP.com – 1.7.3

### Must Use Plugins (1) ###

Disable Emails Must Use: by WebAware – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Square ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Save to Log

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-15 13:52:19 -07:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Complete: 264
Oldest: 2023-11-14 00:00:24 -0700
Newest: 2023-12-07 22:53:58 -0700

Failed: 4
Oldest: 2023-10-30 08:04:22 -0600
Newest: 2023-12-09 06:41:18 -0700

Pending: 11
Oldest: 2023-12-15 04:06:34 -0700
Newest: 2024-01-07 22:53:00 -0700

### Status report information ###

Generated at: 2023-12-14 08:01:52 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @pranavmtn!

This is working as intended. To prevent data loss of any kind, switching datastores while orders are pending sync is not supported.
For example, as part of your testing instructions you've mentioned the placing of a new order. This order is living in whatever the current datastore is, so if you were allowed to change the datastore _before_ performing the sync, this new order would be missing.

If you need to speed up the sync process before switching, you can always use the WP-CLI command `wp wc cot sync`.

Feel free to re-open this issue if I've missed something.

**Comment by rwkyyy** [comment]
I also get this error when I want to modify features (Ex. disable order attribution) and I can't disable it without syncing first.
