### ISSUE TITLE
[Product Block  Editor]: Media Library not available in the Modal Editor 

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#42822]
## Description

It isn't possible to access the Media Library from the Media editor.

## How to reproduce it

- Go to the Product Editor
- Edit the _description_ by using the Modal editor

<img width="687" alt="Screenshot 2023-12-14 at 10 22 56" src="https://github.com/woocommerce/woocommerce/assets/77539/53abde4f-6d9f-42c2-a74f-9bbd718b62c2">

- Create a block that should have access to the Media Library, for instance, a Block Image instance
- Confirm the `Media Library` button is not shown

<img width="1042" alt="Screenshot 2023-12-14 at 10 20 46" src="https://github.com/woocommerce/woocommerce/assets/77539/6e1bd56b-f3e4-46b8-9e6c-dff0dea0f027">

**Comment by mattsherman** [comment]
Closing this... media library is available in the modal editor now...



https://github.com/woocommerce/woocommerce/assets/2098816/0c961643-2b2e-4245-970b-ec2f5a5983b5
