### ISSUE TITLE
Wrong order of postcode input form on changing country

### ISSUE THREAD

**Issue by mkimont** [woothemes/woocommerce#42835]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Postcode order is taking data from JQuery instead of dataset

### Expected behavior

Taking priority from dataset 

### Actual behavior

Taking data from jQuery data
![image](https://github.com/woocommerce/woocommerce/assets/6627821/304cf4fc-86a5-45ef-954b-b032d9c00cf7)
![image](https://github.com/woocommerce/woocommerce/assets/6627821/5c734e37-51f9-4ffc-8a53-dd70374420eb)
https://api.jquery.com/data/#data2

I am not sure if this is the issue of jQuery now or this code... 

### Steps to reproduce

1. Pass this function in function.php
```
add_filter( 'woocommerce_default_address_fields','custom_override_default_locale_fields', 100);
function custom_override_default_locale_fields( $fields ) {
	$fields['postcode']['priority'] = 300;
	return $fields;
}
```
2. Go to checkout with any product
3. Change country from UK to Poland ( or any which have priority in woocommerce/includes
/class-wc-countries.php )

4. Postcode order is changing

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://xx
Site address (URL): https://xx
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 6.3.2 - There is a newer version of WordPress available (6.4.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.24
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.6.7-MariaDB-1:10.6.7+maria~focal
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_
Total Database Size: 350.45MB
Database Data Size: 208.16MB
Database Index Size: 142.29MB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Theme ###

Name: xx
Version: 1.9.2
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Admin ###

Daily Cron: ✔ Next scheduled: 2023-12-15 09:54:45 +00:00
Options: ✔
Notes: 78
Onboarding: completed

### Status report information ###

Generated at: 2023-12-14 15:58:11 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
I believe this is because your filter is being applied to the _default_ locale, which is then overridden by country-specific locale data.

You'll need to update the postcode priority for each locale you want it updated in, e.g.

```php
add_filter(
	'woocommerce_get_country_locale',
	function( $locale ) {
		$locale['PL']['postcode']['priority'] = 300;
		return $locale;
	}
);
```

Feel free to reopen the issue if this doesn't solve it, thank you!
