### ISSUE TITLE
Post a discussion on the blocks repo about the repository merge

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42870]
People visiting the old discussion board should be informed about the migration and the new GitHub board they should use.

## Expected result

- on the[ Blocks Discussions board](https://github.com/woocommerce/woocommerce-blocks/discussions), create a new discussion in the Announcements category and [pin it](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#pinning-a-discussion-globally) to the general board
- encourage people to use the Discussions board from the WooCommerce repo
- share this quick link for people who want to start discussions about the checkout block https://github.com/woocommerce/woocommerce/discussions/new?category=checkout-flow&labels=type%3A+product%20feedback
- mention that existing discussions will be moved and GH will take care of redirects

**Comment by opr** [comment]
Done https://github.com/woocommerce/woocommerce-blocks/discussions/12130
