### ISSUE TITLE
Text in description field disappears when Full Editor is opened

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#42898]
**Describe the bug**

- When I type in the Product Description field (eg. "Description XYZ"), and then click `Full editor`, the Full editor is empty -- whatever I previously typed ("Description XYZ") does not appear in the Full editor. 

- Subsequently, if I delete all my content in the Full editor, my previous content ("Description XYZ") reappears in the product description field.

**Expected behaviour**
- Whatever I typed in the Product Description field should appear in the Full editor. 
- If I delete all content from the Full editor, and then exit the Full editor, the Product Description field should be empty.

![Screen Capture on 2023-12-18 at 15-58-49](https://github.com/woocommerce/woocommerce/assets/65582817/03b333ea-ca1f-40d8-bcec-90745c5b0d0f)

**Comment by louwie17** [comment]
Closing this, as it has been fixed by: https://github.com/woocommerce/woocommerce/pull/42768
