### ISSUE TITLE
CYS - Make sure patterns are not reset to default if AI is down and the store already has AI-generated content

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#42906]
On the very first attempt, whenever AI is down, all products and patterns are reset to their default content:

https://github.com/woocommerce/woocommerce/assets/15730971/1813f66c-12be-4cb1-af51-09a102a713aa

Currently, on the second failed attempt, patterns are updated to their default content, while products are unchanged. We need to change this logic to ensure that if the store already has AI-generated content, both patterns and products **do not** have their content changed to the default (the user should keep the previously AI-generated content for their store), while still displaying the "AI is offline" modal (to be worked on as part of https://github.com/woocommerce/woocommerce/issues/42905).

**Comment by nefeline** [comment]
@SamratBiswas1 @verofasulo  could you please confirm if this issue correctly describes the expected implementation? Is there anything else you'd like to add/change?

**Comment by SamratBiswas1** [comment]
Looks right to me. Thanks!

However, in the 2nd attempt only the AI offline modal will be displayed and not the entire tour.
