### ISSUE TITLE
Hook `Packages::on_init` to `init` instead of `plugins_loaded`

### ISSUE THREAD

**Issue by renventura** [woothemes/woocommerce#42918]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello! A mutual customer of ours reported issues with updating WooCommerce. The Woo team referred her to us with an explanation that it was a conflict with our MU plugin. After some digging, we discovered the issue, and patched it on our end. Here's a full report and fix for consideration.

WooCommerce 8.3.0 introduced a block migration that programmatically updates the checkout page. [Refactor Cart and Checkout Page Templates by mikejolley · Pull Request #10773 · woocommerce/woocommerce-blocks](https://github.com/woocommerce/woocommerce-blocks/pull/10773/files#diff-7a149914e4cec2dfd6fd142ebb3653fb186d871e694aea733ed1a14d1ec0b7f9) When this happens, it triggers Cache Enabler, and very likely other caching solutions, to flush page caches. The problem lies in this happening at a time when the `global $wp_rewrite` object is not available, thus throwing an error. For our customers running the Cache Enabler plugin, updating WooCommerce was failing as a result. 

### Expected behavior

Because the block migrations can and do programmatically update posts, it's reasonable to expect that all post-related core functionality should be loaded, including the global `$wp_rewrite` object. 

### Actual behavior

Specifically, Cache Enabler hooks into when posts are saved and flushes caches, including taxonomies. To flush the cache for a taxonomy, it calls the core `get_term_link()` function. This function looks at `global $wp_rewrite`. However, the block migrations run on `plugins_loaded`, and the `$wp_rewrite` object is not available at this time. It produces an error that looks like:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_extra_permastruct() on null in .../wp-includes/taxonomy.php:4625
```

We patched this on our end by unhooking `Automattic\WooCommerce\Packages::on_init()` from `plugins_loaded`, and hooking it into `init`. 

### Steps to reproduce

Upgrade an eligible site to WooCommerce >= 8.3, where the `11.2.0` block migrations will run. 

### WordPress Environment

This is happening in various environments. 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
Hi @renventura thanks for posting the issue and providing an excellent writeup about what's happening.

I wonder if changing `Packages::on_init` to `init` instead of `plugins_loaded` will have a negative effect on backward compatibility, specifically for plugins that might be doing stuff on `plugins_loaded` and expect a specific state of the site at that point.

I think we should add this to the backlog and try to think of a way to solve it without changing the hook used. One solutions would be to only run migrations on or after `init`, for example.

**Comment by senadir** [comment]
Hey @renventura

I'm revisiting this but I'm unable to fully reproduce it. I setup [Cache Enabler](https://wordpress.org/plugins/cache-enabler/). Enabled its settings:
<img width="957" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/71f0d48c-5c65-4fb1-9c2d-8a408896b90c">

Installed WooCommerce 8.2.2 and updated it to 8.6.1 but couldn't reproduce the error.

**Comment by ralucaStan** [comment]
@renventura was this issue fixed on your customer's end? Do reach out if you have more feedback. I am going to close this ticket as we need some help replicating it.
