### ISSUE TITLE
Checkout Block - customerPaymentMethods types should be an array but can be an object leading to JS errors on checkout page

### ISSUE THREAD

**Issue by paymentplugins** [woothemes/woocommerce#42936]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In class `Automattic\WooCommerce\Blocks\BlockTypes\Checkout::hydrate_customer_payment_methods` a property named `customerPaymentMethods` is added to the data registry. This property contains payment method types as keys and the value of each key is expected to be an array of saved payment methods.

However, on line 424, the saved payment methods are filtered based on whether or not the gateway is active. Here is that code:

<img width="976" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17156041/57ff35bd-5aeb-41a7-9a5f-89241e698baa">

This section of code uses `array_filter` which preserves keys. That means you can end up with a list containing non-sequential keys. That gets interpreted by the browser as an object. In file `woocommerce/packages/woocommerce-blocks/assets/js/data/payment/utils/set-default-payment-method.ts`, the customer's saved payment methods are flattened using `flatMap` which expects an array. If an object is passed, the result is a Javascript error. Here is the problematic code:

<img width="659" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17156041/cfbb6203-5b6e-42f2-a1ed-50d0395c4b95">

The Javascript error is triggers when the `const token = savedPaymentMethod.tokenId.toString();` is executed since the **savedPaymentMethod.tokenId** is undefined.

### Expected behavior

The customer's payment methods should always be an array, rather than an object. 

### Actual behavior

If a payment gateway that has saved payment methods is inactive, the filtering code in `Automattic\WooCommerce\Blocks\BlockTypes\Checkout::hydrate_customer_payment_methods` results in an object rather than an array. This causes the frontend Javascript to throw an error.

<img width="1481" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17156041/ad0c60b5-e732-458b-b322-37d38b89d52f">

In this example, a payment gateway was deactivated, resulting in a non-sequential array that's interpreted as an object by the browser:
<img width="487" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17156041/50d10cd0-bda0-4cf7-bb18-b2d08303af14">

### Steps to reproduce

1. Install a WooCommerce payment plugin that allows payment methods to be saved. This plugin should support multiple payment method types
2. Go to My Account > Payment Methods > Add Payment Method
3. Add 3 or more payment methods, all using different payment methods
4. Deactivate one of the payment methods provided by the gateway.
5. Add an item to cart and proceed to checkout page. The checkout page should use the Checkout Block.
6. Observe the error caused by the `wcSettings.customerPaymentMethods` object.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/paymentplugins
Site address (URL): http://localhost:8888/paymentplugins
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/8.0.8 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 8.0.8
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.34
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 8556.67MB
Database Data Size: 5038.83MB
Database Index Size: 3517.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.34MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.94MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3249.53MB + Index: 2326.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1761.53MB + Index: 1173.02MB + Engine InnoDB
wp_brizy_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_visits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cfw_acr_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.02MB + Index: 0.20MB + Engine InnoDB
wp_postmeta: Data: 8.47MB + Index: 5.89MB + Engine InnoDB
wp_posts: Data: 2.45MB + Index: 0.39MB + Engine InnoDB
wp_sheerid_programs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sheerid_verifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_framemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_frames: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders: Data: 0.36MB + Index: 0.52MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.41MB + Index: 2.92MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.22MB + Index: 0.31MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 14
bfwc_subscription: 29
brizy-project: 1
cartflows_flow: 1
cartflows_step: 2
customize_changeset: 1
e-landing-page: 1
elementor_library: 6
page: 15
post: 1
product: 9
product_variation: 3
revision: 160
shop_coupon: 4
shop_order: 1240
shop_order_placehold: 583
shop_order_refund: 63
shop_subscription: 112
wfacp_checkout: 1
wffn_ty: 1
wfocu_funnel: 3
wfocu_offer: 3
wp_global_styles: 3
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Code Snippets: by Code Snippets Pro – 3.6.2
Heartbeat Control by WP Rocket: by WP Rocket – 2.0.1
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.53

WooCommerce Subscriptions: by WooCommerce – 5.1.2
WooCommerce: by Automattic – 8.4.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: braintree-subscription (braintree-subscription)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #16 - /checkout-block/
My account: #9 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Blocksy
Version: 2.0.9 (update to version 2.0.11 is available)
Author URL: https://creativethemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: blocksy/woocommerce/cart/cart.php
blocksy/woocommerce/cart/mini-cart.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy/woocommerce/myaccount/my-account.php
/Applications/MAMP/htdocs/paymentplugins/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Applications/MAMP/htdocs/paymentplugins/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Applications/MAMP/htdocs/paymentplugins/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php
blocksy/woocommerce/product-searchform.php
blocksy/woocommerce/single-product/tabs/tabs.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://localhost:8888/paymentplugins
Subscriptions-core Library Version: 5.7.1
Subscription Statuses: wc-active: 10
wc-cancelled: 3
wc-on-hold: 31

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-19 05:22:54 +00:00
Options: ✔
Notes: 148
Onboarding: skipped

### Action Scheduler ###

Complete: 8,517,407
Oldest: 2023-04-04 04:02:16 +0000
Newest: 2023-12-18 22:23:33 +0000

Failed: 228
Oldest: 2023-02-17 21:27:35 +0000
Newest: 2023-12-12 19:04:00 +0000

Pending: 17
Oldest: 2023-12-18 22:46:37 +0000
Newest: 2024-01-17 02:25:52 +0000

### Status report information ###

Generated at: 2023-12-18 22:23:38 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
Hi there @paymentplugins thanks for taking the time to report this issue - looks like it was solved in https://github.com/woocommerce/woocommerce-blocks/pull/11070 - and the [current code is here](https://github.com/woocommerce/woocommerce/blob/d1498d45f2804eede99538d13717c4e2cf602308/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php#L424-L432) - looks like we are correctly using `array_values` now. I expect this will be included in WooCommerce 8.5.0

Thanks!
