### ISSUE TITLE
[CYS] Default fonts - Flow without AI

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#42941]
Can we please have a look into the default fonts based on the user's selection in the Look and Feel step when AI is not available?

Please let's default users to the following font pairings:

- Contemporary: Inter, Inter
- Classic: Bodoni Moda, Overpass
- Bold: Rubik, Inter

Thank you!

**Comment by nefeline** [comment]
All fonts are correct, except for Bold:

https://github.com/woocommerce/woocommerce/blob/6b77f71ea7312a18ac35047cce38ffa5574eece4/plugins/woocommerce-admin/client/customize-store/design-with-ai/actions.ts#L133

This needs to be changed to **Rubik, Inter**

**Comment by verofasulo** [comment]
I think you're looking at the flow with AI 😊 

In that case, it's correct. In the flow without AI, we don't have that font pairing (we limited the font pairing to eight and Plus Jakarta Sans is not included), so it needs to be replaced. 

But in the no-AI flow, there's no logic implemented. I tested all the options (contemporary, classic, and bold), and the outcome was Rubik, Inter for all of them. 🤔 Do you see the same?

**Comment by gigitux** [comment]
I think that the errors are two. When the user selects `Bold`, the default font should be the `Rubik, Inter`: for both flows. Furthermore, currently, when the AI is offline, the default font isn't set. I created a PR to fix both issues: #42973.
