### ISSUE TITLE
[CYS] Color palette - Create your own

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#42940]
Could we please investigate why I can't change the color for the Heading in the Create your own functionality (Change your color palette section)? Thank you!  

![image](https://github.com/woocommerce/woocommerce/assets/98944206/c52cc98c-9117-4e28-bec9-cef984e99e98)

**Comment by gigitux** [comment]
Hi @verofasulo!

I was able to update the heading color. Can you try again?
![Screen Capture Dec 19 from Droplr](https://github.com/woocommerce/woocommerce/assets/4463174/8ffdbefd-6e45-4d91-a45a-ba2308c594e6)


EDIT: I understand the issue, I'm going to do another check!

**Comment by verofasulo** [comment]
Thanks, @gigitux! 🙏
