### ISSUE TITLE
[DOC-REQ] Process for using WooCommerce components in custom blocks unclear.

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#42956]
## Description of the Document Requested

I've been trying to expand the behaviour of some of our WooCommerce extensions with custom blocks that can be used to control the output from our extension. This works well up until a point, using standard WordPress block development practices. However I've struggled to come up with a working solution to utilise WooCommerce components cleanly in my custom blocks. 

As an example, take the following flow which, as I understand it, should create a working result. 

1. Create an example block : `npx @wordpress/create-block --variant dynamic example-dynamic-block`
2. Enter the plugin folder
3. Add `@woocommerce/dependency-extraction-webpack-plugin` : `npm i --save @woocommerce/dependency-extraction-webpack-plugin`
4. Drop in a webpack.config.js file to ensure that the plugin is used:

```const defaultConfig                                = require( '@wordpress/scripts/config/webpack.config' );
   const WooCommerceDependencyExtractionWebpackPlugin = require( '@woocommerce/dependency-extraction-webpack-plugin' );

   module.exports = {
           ...defaultConfig,
           plugins: [
                   ...defaultConfig.plugins.filter(
                           ( plugin ) =>
                                   plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
                   ),
                   new WooCommerceDependencyExtractionWebpackPlugin(),
           ],

   };
```

5. Activate the plugin, and confirm that you can add the generated block to a page - all good so far.
6. Amend the `src/edit.js` and add: `import { FormattedMonetaryAmount } from '@woocommerce/blocks-components';`
7. Amend the component output to include a FormattedMonetaryAmount component, e.g.

```
/**
 * Retrieves the translation of text.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/
 */
import { __ } from '@wordpress/i18n';
import { FormattedMonetaryAmount } from '@woocommerce/blocks-components';

/**
 * React hook that is used to mark the block wrapper element.
 * It provides all the necessary props like the class name.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockprops
 */
import { useBlockProps } from '@wordpress/block-editor';

/**
 * Lets webpack process CSS, SASS or SCSS files referenced in JavaScript files.
 * Those files can contain any CSS code that gets applied to the editor.
 *
 * @see https://www.npmjs.com/package/@wordpress/scripts#using-css
 */
import './editor.scss';

/**
 * The edit function describes the structure of your block in the context of the
 * editor. This represents what the editor will render when the block is used.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#edit
 *
 * @return {Element} Element to render.
 */
export default function Edit() {
        return (
                <p { ...useBlockProps() }>
                        <FormattedMonetaryAmount
                                                        currency={{
                                                                code: 'USD',
                                                                decimalSeparator: '.',
                                                                minorUnit: 2,
                                                                prefix: '$ ',
                                                                suffix: '',
                                                                symbol: '$ ',
                                                                thousandSeparator: ','
                                                        }}
                                                        displayType="text"
                                                        value={101}
                                                />
                        { __(
                                    'Example Dynamic Block – hello from the editor!',
                                    'example-dynamic-block'
                            ) }

                </p>
        );
}
```

8. Rebuild the component with `npm run build`
9. Reload the edit page of the page containing the component
10. Note that the inclusion of the component results in many javascript errors (see attachment)
[wc.test-1702994584413.log](https://github.com/woocommerce/woocommerce/files/13716547/wc.test-1702994584413.log)

## Why is this Document Important?

With WordPress' & WooCommerce's move to blocks for managing sites it is important that plugins can also be used through the block mechanism. At the minute this process is complicated, and error-prone with limited documentation (that I've found), and often conflicting documentation. A single point that shows how to have a plugin create its own custom blocks, including reusing components provided by WooCommerce would be a helpful place to point people to.

**Comment by leewillis77** [comment]
[example-dynamic-block.zip](https://github.com/woocommerce/woocommerce/files/13716598/example-dynamic-block.zip)

**Comment by opr** [comment]
Hi @leewillis77 and thank you for the detailed report and reproduction steps. I confirm that I get this error too.

To solve it, I added `wc-blocks-checkout` to the dependencies array in `build/index.asset.php`

The next steps will be to figure out how we can make sure that importing from `@woocommerce/blocks-components` adds the dependency.

As for the document request, we have https://github.com/woocommerce/woocommerce/issues/42263 open already which is similar, and should cover the request from this issue. What I propose is:
- Add the information in this issue to https://github.com/woocommerce/woocommerce/issues/42263 to ensure that the person writing that documentation covers everything you mentioned here.
- Close this issue in favour of the above.
- Open a new issue for tracking the missing `wc-blocks-checkout` dependency.

I'll take care of that and add the relevant links here.

Closed in favour of https://github.com/woocommerce/woocommerce/issues/42263
Follow up issue created: https://github.com/woocommerce/woocommerce/issues/43298
