### ISSUE TITLE
[Product Block Editor] Not possible to add Storybook stories

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#42954]
It doesn't seem to be possible to add Storybook stories in the Product Block Editor package. What I do:

* Add an story to a component (https://github.com/woocommerce/woocommerce/pull/42953)
* Locally, run the Storybook app:

```cli
pnpm --filter=storybook run storybook
```

It shows a bunch of TS issues:

<img width="1211" alt="image" src="https://github.com/woocommerce/woocommerce/assets/77539/de4f6089-a348-425c-b461-29ce9bccd46e">

**Comment by jonathansadowski** [comment]
Hi @retrofox. I've added the `team: Mothra` label to this issue. When creating issues for your team, please remember to add this label (along with `type: task` if it applies). This keeps the issue out of the triage queue.

**Comment by retrofox** [comment]
Thanks, Jonathan. I'll do it for the next ones.
Also, let's close the issue since it has been fixed.
