### ISSUE TITLE
Output a currency object similar to `wc.wcSettings.allSettings.currency` but in the format expected by `FormattedMonetaryComponent`

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#42989]
`wc.wcSettings.allSettings.currency` is an object with the following shape:

```ts
{
	code: string
	decimalSeparator: string
	precision: number
	priceFormat: string
	symbol: string
	symbolPosition: "left" | "right"
	thousandSeparator: string
}
```

`FormattedMonetaryAmount` and various other components that use the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) consume currency in a different format.

Third party developers using these components now have to construct their own [`Currency`](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) object as there is no way for them to get one easily.

---

We should either: update the current object to have the same shape as the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) or output a new object.

Before working on this issue, we should investigate how currencies are converted into the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) as that might offer some alternative solutions.

**Comment by helgatheviking** [comment]
Could we also explore having the store currency settings as defaults? Ideally I would like to just say `<Price value={10} />` and have that automatically be `$10.00` or `10,00 €` depending on the store. Similar to how `wc_price()` works.

In a truly ideal scenario, we could have a component that accepts regular and sale prices and generates the exact same markup as woo. there's no need for every plugin dev to have to duplicate this when it already exists in woo... just needs to be published in a way we can import.

**Comment by helgatheviking** [comment]
@opr could we look at increasing the priority on this? 

(I think there is a related issue with `<FormatMonetaryComponent>` not exporting properly... And `formatPrice` neither). 

Every plugin that needs to integrate with woo's new react components needs a way to display a **price** and right now it's so much more complicated than it ought to be. 

I still vote for `FormatMonetaryComponent` falling back to some wc.Settings values if that's defined.

**Comment by opr** [comment]
@pmcpinto highlighting this issue to you, do you think the normal priority here is OK or should we increase it? As Helga states, extensions wanting to show prices are struggling to do so at the moment, and the current `FormattedMonetaryComponent` is a little tricky to use without a currency object.

> I still vote for FormatMonetaryComponent falling back to some wc.Settings values if that's defined.

I like the idea, but it does reduce portability of the component and tightly couples it to that value being set, I am not super worried about that really, but I'm not sure what the fallback would be if it's not set. Just don't show anything? 🤔 Maybe a wrapper component as you say might be a good idea instead.

**Comment by helgatheviking** [comment]
>I'm not sure what the fallback would be if it's not set

What happens now if you try to use `<FormattedMonetaryComponent>` without a currency params object? I think nothing renders right? So if if you are using it _outside_ of Woo, there's no `wc.Settings` and don't pass your own currency params object, you'd be in the same boat.. there's no change to current behavior.

**Comment by pmcpinto** [comment]
> @pmcpinto highlighting this issue to you, do you think the normal priority here is OK or should we increase it?

Sorry, I missed this ping. Would you happen to have a sense of the effort required to make this change?

**Comment by opr** [comment]
@pmcpinto I would give it an estimate of 1, i.e. less than a day

**Comment by pmcpinto** [comment]
Thanks. In that case, I think we should try to handle it in the upcoming weeks.

**Comment by nielslange** [comment]
I haven't had time to work on this issue yet, so I'll unassign myself and move it back to the backlog to ensure others can take it on.
