### ISSUE TITLE
issue since last update: PHP Warning:  Undefined array key "post_type" in /home/a/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php on line 649

### ISSUE THREAD

**Issue by or128** [woothemes/woocommerce#42998]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have no idea what causes this, but it happens while paying using the payment gateway.
I tried a diffrent gateway, and this line also appears:

[20-Dec-2023 12:15:05 UTC] PHP Warning:  Undefined array key "post_type" in /home/japaneseknives/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php on line 649

It sometimes appears with several of these line around the same time before i in the log:
[20-Dec-2023 08:20:13 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/japaneseknives/public_html/wp-includes/kses.php on line 1744

Like so:
[18-Dec-2023 13:58:55 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/japaneseknives/public_html/wp-includes/kses.php on line 1744
[18-Dec-2023 13:58:56 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/japaneseknives/public_html/wp-includes/kses.php on line 1744
[18-Dec-2023 14:23:09 UTC] PHP Warning:  Undefined array key "post_type" in /home/japaneseknives/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php on line 649
[18-Dec-2023 15:39:29 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/japaneseknives/public_html/wp-includes/kses.php on line 1744
[18-Dec-2023 15:57:45 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/japaneseknives/public_html/wp-includes/kses.php on line 1744

It is always appearing during payment\checkout.

### Expected behavior

I do not know how this impact the user's experience. 

### Actual behavior

I do not know how this impact the user's experience. 

### Steps to reproduce

1. checking out \ Paying.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.japanese-knives.co.il
Site address (URL): https://www.japanese-knives.co.il
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: he_IL
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.26
PHP Post Max Size: 2 GB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: hks_
Total Database Size: 2825.65MB
Database Data Size: 2469.21MB
Database Index Size: 356.44MB
hks_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_order_items: Data: 5.52MB + Index: 1.52MB + Engine InnoDB
hks_woocommerce_order_itemmeta: Data: 40.56MB + Index: 24.06MB + Engine InnoDB
hks_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 2.52MB + Index: 1.02MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 2091.98MB + Index: 7.52MB + Engine InnoDB
hks_actionscheduler_actions: Data: 2.03MB + Index: 0.23MB + Engine InnoDB
hks_actionscheduler_claims: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
hks_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_logs: Data: 127.67MB + Index: 95.20MB + Engine InnoDB
hks_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_atum_product_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_cerber_sets: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
hks_cerber_uss: Data: 0.33MB + Index: 0.06MB + Engine InnoDB
hks_commentmeta: Data: 0.08MB + Index: 0.19MB + Engine InnoDB
hks_comments: Data: 15.55MB + Index: 17.61MB + Engine InnoDB
hks_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_detail_new: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_enquiry_quotation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_enquiry_thread: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_gcb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_huge_itgallery_gallerys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_huge_itgallery_images: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_huge_itgallery_like_dislike: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_huge_itgallery_params: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_imagify_files: Data: 0.36MB + Index: 0.39MB + Engine InnoDB
hks_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_itbbc_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_itbbc_history_items: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
hks_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_mclean_scan: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
hks_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_slides: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_options: Data: 31.23MB + Index: 0.42MB + Engine InnoDB
hks_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_post_smtp_logs: Data: 8.02MB + Index: 0.00MB + Engine InnoDB
hks_postmeta: Data: 98.80MB + Index: 172.36MB + Engine InnoDB
hks_posts: Data: 10.47MB + Index: 6.06MB + Engine InnoDB
hks_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
hks_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
hks_revslider_sliders_bkp: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides: Data: 0.41MB + Index: 0.02MB + Engine InnoDB
hks_revslider_slides_bkp: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_term_relationships: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
hks_term_taxonomy: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
hks_termmeta: Data: 0.27MB + Index: 0.55MB + Engine InnoDB
hks_terms: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
hks_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tqb_event_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_users: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_variations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
hks_ukuu_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_usermeta: Data: 7.50MB + Index: 15.53MB + Engine InnoDB
hks_users: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
hks_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wc_customer_lookup: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
hks_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_wc_order_bundle_lookup: Data: 0.17MB + Index: 0.30MB + Engine InnoDB
hks_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_product_lookup: Data: 2.52MB + Index: 2.64MB + Engine InnoDB
hks_wc_order_stats: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
hks_wc_order_tax_lookup: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
hks_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
hks_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_product_attributes_lookup: Data: 0.34MB + Index: 0.33MB + Engine InnoDB
hks_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_product_meta_lookup: Data: 0.14MB + Index: 0.30MB + Engine InnoDB
hks_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wcsc_logs: Data: 0.22MB + Index: 0.30MB + Engine InnoDB
hks_wd_fb_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_theme: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_bundled_itemmeta: Data: 2.52MB + Index: 2.56MB + Engine InnoDB
hks_woocommerce_bundled_items: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
hks_wpr_rocket_cache: Data: 0.17MB + Index: 0.25MB + Engine InnoDB
hks_wpr_rucss_used_css: Data: 0.33MB + Index: 0.61MB + Engine InnoDB
hks_yoast_indexable: Data: 2.52MB + Index: 0.36MB + Engine InnoDB
hks_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
hks_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_yoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
hks_yoast_prominent_words: Data: 0.52MB + Index: 0.73MB + Engine InnoDB
hks_yoast_seo_links: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
hks_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_smtp: 1
attachment: 5627
clients: 1
content_block: 195
decision_tree: 1
follow_up_email: 8
klaviyo_shop_cart: 1
nav_menu_item: 406
oembed_cache: 67
optionsframework: 12
page: 61
post: 61
product: 749
product_variation: 388
pys_event: 6
revision: 338
shop_coupon: 641
shop_order: 12688
shop_order_refund: 12
slide: 1
sp_wpsp_shortcodes: 1
thrive_image: 5
tqb_quiz: 4
tqb_results: 3
tqb_splash: 1
vc_grid_item: 1
wcct-deal-shortcode: 2
wcct_countdown: 44
wcst_trigger: 11
wc_zapier_feed: 2
wp-type-contacts: 2
wpb-rs-global: 7
wpcf7_contact_form: 1
wp_quiz: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (61) ###

Query Monitor: by John Blackbourn – 3.15.0
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.4.2
Add Admin CSS: by Scott Reilly – 2.0.1
Cargo Shipping Location for WooCommerce: by Astraverdes – 3.8
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.8.5
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.2.7
Disable Cart Fragments: by Optimocha – 2.3
Duplicate Menu: by Jonathan Christopher – 0.2.2
GTM4WP: by Thomas Geiger – 1.19.1
Envato Market: by Envato – 2.0.11
Finale WooCommerce Deal Pages: by XLPlugins – 1.4.1.beta.fix.10
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.20.2.beta.fix.199
Global Content Blocks: by Dave Liske – 2.1.5
WhatsApp Chat for WordPress / WooCommerce: by idnovate.com – 1.4.3
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.3
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.14

Klaviyo: by Klaviyo
Inc. – 3.3.3

Loco Translate: by Tim Whitlock – 2.6.6
Object Cache 4 everyone: by fpuenteonline – 2.2
One Time Login: by Daniel Bachhuber – 0.4.0
Perfmatters: by forgemedia – 2.2.0
PixelYourSite PRO: by PixelYourSite – 9.11.1.1
PixelYourSite Super Pack: by PixelYourSite – 5.0.0
plugin load filter: by enomoto@celtislab – 4.1.0
Post SMTP: by Post SMTP – 2.8.7
Product Filter for WooCommerce: by XforWooCommerce – 8.3.0
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 5.4.1
RD Order Modifier for WooCommerce: by Robot Dwarf – 1.0.13
Slider Revolution: by ThemePunch – 6.6.19
snip pro - Structured Data: by floriansimeth – 2.31.6
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.7.2

Shortcode Empty Paragraph Fix: by  – 0.2
Hide SEO Bloat: by SO WP – 4.0.1
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.2.15
WooCommerce Thank You Page - NextMove: by XLPlugins – 1.17.2.beta.fix.122
TWB Woocommerce Reviews: by Abu Bakar – 1.7.5
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.8.1

CardCom Payment Gateway: by CardCom LTD – 3.4.8.2
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.8
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.5.5
WooCommerce - Pipedrive CRM - Integration: by itgalaxycompany – 1.33.1
WooCommerce Product Bundles: by WooCommerce – 6.22.5
WooCommerce Product Primary Category: by BeoCode.d.o.o. – 0.1.2
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4
WooCommerce: by Automattic – 8.4.0
Yoast SEO Premium: by Team Yoast – 21.7
Yoast SEO: by Team Yoast – 21.7
WP Accessibility Helper: by Alex Volkov – 0.6.2.5
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 9.6
WP-Cron Status Checker: by Webhead LLC – 1.2.5
WP Rocket | Ignore Query Strings: by WP Rocket Support Team –
WP Rocket | Set Tablets As Mobile: by WP Rocket Support Team –
WP Rocket | Change Preload Parameters: by WP Rocket Support Team –
WP Rocket | Change Remove Unused CSS Parameters: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.15.6
WP-RTL: by Fahad Alduraibi – 1.0
WP User Avatars: by Triple J Software
Inc. – 1.4.1

WPX Cron Manager Light: by Giovambattista Fazioli – 2.4.0
XL WooCommerce Sales Triggers: by XLPlugins – 2.12.1.beta.fix.74
YouTube WordPress Plugin Pro by Embed Plus: by Embed Plus for YouTube Team – 14.2.1

### Inactive Plugins (29) ###

Cargo Express Shipping method for WooCommerce: by WebSolution – 1.0.9.1
Duplicator: by Duplicator – 1.5.7.1
Enable Media Replace: by ShortPixel – 4.1.5
Finale Email Countdown Timer: by XLPlugins – 1.2.0
iThemeland bulk bundle core: by iThemelandco – 1.6.1
iThemeland WooCommerce Bulk Product Editing: by iThemelandco – 2.9.2
Media Cleaner: by Jordy Meow – 6.6.9
PayPlus Payment Gateway: by PayPlus LTD – 6.5.5
Redis Object Cache: by Till Krüss – 2.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Search & Replace: by Inpsyde GmbH – 3.2.1
SOFT79 Cart Links for WooCommerce: by Soft79 – 1.1.4
Stock Exporter for WooCommerce: by PT Woo Plugins (by Webdados) – 1.2.0
ThumbPress: by Codexpert
Inc – 4.1.1

What The File: by Never5 – 1.6.0
Widget CSS Classes: by Jory Hogeveen – 1.5.4.1
Widget Options: by Widget Options Team – 3.9.6
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
WooCommerce - Frontend Inventory: by Mirko Grewing – 0.7
Woocommerce Baldar Delivery: by Amit Matat – 1.5.0
WooCommerce Blocks: by Automattic – 11.7.0
WooSidebars: by WooCommerce – 1.4.6
Woo Zap Mirror: by Ido Friedlander – 1.4.6
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.22

WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.8
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Rocket | WooCommerce Recently Viewed Products Widget Integration: by WP Rocket Support Team –
WP Server Stats: by Saumya Majumder – 1.7.3
Yoast Test Helper: by Team Yoast – 1.17

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Object Cache 4 everyone - Memcached

### Must Use Plugins (3) ###

aaa-wp-cerber.php: by Cerber Tech Inc. – 1.0
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.14
plugin load filter [plf-filter]: by enomoto@celtislab – 4.0.17

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1812 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /order/
My account: #7 - /my-account/
Terms and conditions: #605 - /legal/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.18.2
Parent Theme Author URL: https://uxthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/mini-cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/order-received.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.22.5
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-21 06:39:43 +02:00
Options: ✔
Notes: 20
Onboarding: completed

### Action Scheduler ###

Complete: 260
Oldest: 2023-12-20 01:24:13 +0200
Newest: 2023-12-20 17:06:47 +0200

Failed: 280
Oldest: 2022-10-03 08:51:30 +0300
Newest: 2023-12-20 16:36:43 +0200

Pending: 3
Oldest: 2023-12-20 20:05:55 +0200
Newest: 2023-12-22 19:31:47 +0200

### Status report information ###

Generated at: 2023-12-20 17:34:12 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @or128,

Thanks for the report. Are there any additional steps that you must take to reproduce this, or does the error always show up on the payment / checkout page? Can you confirm that you're able to reproduce this issue if WooCommerce is the only plugin active?

**Comment by praggmatica** [comment]
Hi, wanted to chime in as I'm seeing the same bug. I disabled all plugins except woocommerce and used a twentytwentyfour theme.

I see the error on the Orders page in the admin.
website.com/wp-admin/edit.php?post_type=shop_order

**Comment by or128** [comment]
> Hi, wanted to chime in as I'm seeing the same bug. I disabled all plugins except woocommerce and used a twentytwentyfour theme.
> 
> I see the error on the Orders page in the admin. website.com/wp-admin/edit.php?post_type=shop_order

Thank you for the help, I couldn't find time to do that with the end of the year sale pressure. 
What steps did you use to recreate the line in the log?

**Comment by rrennick** [comment]
> Hi, wanted to chime in as I'm seeing the same bug. I disabled all plugins except woocommerce and used a twentytwentyfour theme.

> I see the error on the Orders page in the admin. website.com/wp-admin/edit.php?post_type=shop_order

@praggmatica I'm not able to reproduce this with the information you provided. Can you provide more details on the steps to reproduce? Eg. WP, theme & WC versions active.

**Comment by praggmatica** [comment]
> > Hi, wanted to chime in as I'm seeing the same bug. I disabled all plugins except woocommerce and used a twentytwentyfour theme.
> 
> > I see the error on the Orders page in the admin. website.com/wp-admin/edit.php?post_type=shop_order
> 
> @praggmatica I'm not able to reproduce this with the information you provided. Can you provide more details on the steps to reproduce? Eg. WP, theme & WC versions active.

Hi, here's some more context, I noticed when WooPayments was enabled with WooCommerce, this issue was not present. WooPayments recently updated to 7.0.0, and after updating to that version, the error mentioned in this issue was gone.
