### ISSUE TITLE
Product Gallery: Close popover overlay when a click is outside of the popover overlay

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#43000]
When the popover overlay is opened, the only way to close it is by clicking on the close button or by pressing ESC key. It is a common practice and good UX when clicking outside of the popover overlay to close as well.

While the popover overlay current is quite large and fills almost all of the screen, there could come a time where the popover overlay size can be adjusted by the user so adding the close on clickoff would be useful.

**Comment by thealexandrelara** [comment]
Closing this PR considering the feedback received https://github.com/woocommerce/woocommerce/pull/43292#issuecomment-1895322656.
