### ISSUE TITLE
Variation table isn't updated until a full refresh

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#43004]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the user updates a variation through the individual variation flow, the changes aren't reflected in the variations table until the window is refreshed.

https://github.com/woocommerce/woocommerce/assets/3380168/54b6dc80-3bc1-4740-a744-e6c30ee86ace

### Expected behavior

The variation's data in the table should be updated without a full page refresh.

### Actual behavior

The variations table isn't updated until the page is refreshed. 

### Steps to reproduce

1. Install WC 8.4 and enable the new product form
2. Create some variations in the Variations tab
3. Edit the variation price through the individual variation flow
4. Return to the main product and confirm that the price wasn't updated in the variations table

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
This has been fixed.
