### ISSUE TITLE
Investigate compatibility with popular block themes

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#43029]
@dinhtungdu saw some styling breakages with the recent dropdown work when using the `Blockbase` theme. We should spend some time testing compatibility of frontend filters with a number of popular block themes.

![Image](https://github.com/woocommerce/woocommerce/assets/1281828/0ebd9543-6ea0-4a34-a1c2-3663aef9bea5)

**Comment by dinhtungdu** [comment]
I can't reproduce the issue above anymore, with various block themes:

Blockbase
![image](https://github.com/woocommerce/woocommerce/assets/5423135/0b35af4b-4d6c-47d0-ad92-d3d4f76e541f)

Tsubaki
![image](https://github.com/woocommerce/woocommerce/assets/5423135/207d2ca5-5545-4d6a-8819-263b0bc4c0b7)

2024
![image](https://github.com/woocommerce/woocommerce/assets/5423135/4664d27c-7940-471e-8d13-e42610b284a9)

2023
![image](https://github.com/woocommerce/woocommerce/assets/5423135/05ad8bca-7ea0-46b3-8907-d4e1cc825ce4)

Zaino
![image](https://github.com/woocommerce/woocommerce/assets/5423135/3fa99003-c8ee-4656-a0fb-a4704692f301)
