### ISSUE TITLE
dependency-extraction-webpack-plugin node dependency incompatible with WordPress core

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#43034]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[dependency-extraction-webpack-plugin](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/dependency-extraction-webpack-plugin) currently requires node v16, whereas WordPress core / gutenburg development now requires a minimum of node v20 (https://make.wordpress.org/core/2023/12/20/updating-wordpress-to-use-more-modern-versions-of-node-js-npm-2/). 

While we can use nvm to work around this it seems like the two should be aligned for developer ease-of-use if nothing else. 

### Expected behavior

dependency-extraction-webpack-plugin can be installed and used with the same version of node/npm required by core WordPress development

### Actual behavior

The plugin cannot currently be installed with WordPress core's recommended version of node:
```
$ npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@woocommerce/dependency-extraction-webpack-plugin@2.3.0',
npm WARN EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.6.7' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
```

### Steps to reproduce

1. Ensure your are running node v20
2. Attempt to install the package `npm i @woocommerce/dependency-extraction-webpack-plugin`

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by leewillis77** [comment]
#39345 mentions this in passing, but is broader in scope than just this

**Comment by helgatheviking** [comment]
I'm having trouble using the dependency extraction plugin... it won't inject WordPress core packages like @wordpress/icons for me at the moment. ooops...  editing to add that it's possibly not related, but still seeing the above warnings and want to follow along.

**Comment by leewillis77** [comment]
Hey @rrennick;

Thanks for your work on this. It looks like this was fixed in the woocommerce monorepo, but I'm unclear what that means for releases. Will there not be an updated release of @woocommerce/dependency-extraction-webpack-plugin until the next WooCommerce release? or should we expect to see an updated release of that package before then?

**Comment by rrennick** [comment]
@leewillis77 Thanks for the reminder. I'll look into how/when the release is handled.

**Comment by rrennick** [comment]
> Thanks for the reminder. I'll look into how/when the release is handled.

@leewillis77 I forgot to post yesterday that this has been published.

**Comment by leewillis77** [comment]
Perfect - thank you!

**Comment by leewillis77** [comment]
@rrennick Looks like I spoke too soon. Although the dependency plugin got an update it seems that the other packages are still stuck requiring v16:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@woocommerce/components@12.2.0',
npm WARN EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.6.7' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@woocommerce/onboarding@3.4.0',
npm WARN EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.3.1' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
```

**Comment by rrennick** [comment]
@leewillis77 Thanks, I'll look into getting updates to those published.

**Comment by leewillis77** [comment]
There seems to have been progress on this, but looks like some packages (looks like this is a dependency of `@woocommerce/onboarding` as it's not a package I'm requiring directly - there may be others I guess) are still locked to v16...

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@woocommerce/csv-export@1.8.0',
npm WARN EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.6.7' },
npm WARN EBADENGINE   current: { node: 'v20.13.0', npm: '10.5.2' }
npm WARN EBADENGINE }
```

**Comment by rrennick** [comment]
@leewillis77 Thanks for the follow up. I created https://github.com/woocommerce/woocommerce/issues/47733 to address updating the remaining packages.
