### ISSUE TITLE
Prevent multiple repeat warnings being shown for incorrectly registered fields

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#43043]
As noted in p1703132883414589-slack-C05JQBR78RW extensions incorrectly registering fields with `woocommerce_blocks_register_checkout_field` trigger repeat warnings on every page load.

Currently we are catching issues with field registration and logging it to the WC Debug log, however changing to [`_doing_it_wrong`](https://developer.wordpress.org/reference/functions/_doing_it_wrong/) would probably be a better approach.

**Comment by tarunvijwani** [comment]
@opr Could you please confirm if https://github.com/woocommerce/woocommerce/pull/43283 PR addresses this issue as well? I think this is duplicate ticket of https://github.com/woocommerce/woocommerce/issues/43277.

**Comment by opr** [comment]
🤦🏼 yes thanks for spotting Tarun, I was sure I made an issue before Christmas but couldn't find it when I came back.
