### ISSUE TITLE
Add menu item to publish button with copy to draft

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#43046]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We want to allow the user to copy the product to a new draft.

**Design**
Link to Figma: AkVNGImLgSqCObTQ3idVn7-fi-3359%3A33948 

<img width="614" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/d4fa79b9-cf8c-4911-9adb-1021f49ec82f">

**Acceptance criteria**

When the user clicks the arrow in the split button and reveals the menu:
- [ ]  Create another draft product with the values from the current one and redirect the user to the new product
- [ ]  We don't save the current changes, if a user does have changes the `Changes you made may not be saved` alert should popup ( this may already happen by default ).

**Comment by mattsherman** [comment]
@j111q When we duplicate the product, should the new product use the same product template as the original one, or should it just use the default product template?

If it should use the same product template, is it acceptable as a first iteration to use the default product template?

**Comment by louwie17** [comment]
Closing this now in favour of https://github.com/woocommerce/woocommerce/issues/43062
Given we removed some options
