### ISSUE TITLE
[DOC-BUG] Docs titles are appearing in a post_title table

### ISSUE THREAD

**Issue by elizaan36** [woothemes/woocommerce#43059]
## Link to the Page/Section

I think there's a formatting issue on all docs pages where the title appears in a `post_title` table.

<img width="1001" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5121465/7462783d-0349-4879-83aa-82c13b6637c5">

## Description of the Suggestion

The title should appear as an H1 not in a table.

**Comment by rrennick** [comment]
@elizaan36 This was intentional. See https://github.com/woocommerce/woocommerce/pull/41794. I'll close the issue.
