### ISSUE TITLE
Unable to track events in woocommerce blocks

### ISSUE THREAD

**Issue by tarunvijwani** [woothemes/woocommerce#43075]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

@nielslange, and I noticed that the events are not visible in [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension).  

We tested the events on the woocommerce 8.4.0 version and the latest trunk. Tracks are getting recorded in woocommerce 8.4.0 but not in the latest trunk.  

Assumption: It could be the side effects of blocks merged to mono repo

### Expected behavior

Tracks must be recorded in [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension) on the latest trunk. 

### Actual behavior

Tracks are not getting recorded in [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension) on the latest trunk. 

### Steps to reproduce

1. Create a site on JN with the latest trunk
2. Connect Jetpack.
3. Install [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension) extension in your browser.
4. Go to all products block, click on any product, and open a product page.
5. Add the product to the Cart. 
6. Go to Cart and then Checkout, place the order. 
7. Go to my account -> orders-> click the order number.
8. Notice none of these tracks are recorded in [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension).
9. Repeat the steps with woocommerce 8.4.0 version and notice tracks are recorded in woocommerce 8.4.0 version. 

### WordPress Environment

woocommerce latest trunk

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
In p1703253652933169/1703244265.910119-slack-C8X6Q7XQU, @senadir clarified that it's currently expected that we're not seeing any events tracking. Events tracking has been moved to Jetpack, and will be launched with version 13.0.0.

**Comment by tarunvijwani** [comment]
Closing the ticket as per our conversation on slack: p1703244265910119-slack-C8X6Q7XQU
