### ISSUE TITLE
Remove "Optional" label in Variation details

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#43128]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The "Optional" label for the Note field in Variation Details isn't showing as expected: NOTE <OPTIONAL /> 

### Expected behavior

<img width="669" alt="Captura de ecrã 2023-12-27, às 06 57 31" src="https://github.com/woocommerce/woocommerce/assets/3380168/edfa89da-3645-4e1a-b21c-05227fddde50">

### Actual behavior

<img width="678" alt="Captura de ecrã 2023-12-27, às 06 58 51" src="https://github.com/woocommerce/woocommerce/assets/3380168/50f86b15-2092-4b21-b186-1a0c85bcbc56">

### Steps to reproduce

1. Install 8.5 beta
2. Enable the new product creation form
3. Create a product with at least one variation
4. Edit the individual variation
5. See NOTE <OPTIONAL /> in Variation Details

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by retrofox** [comment]
We decided to remove the `(OPTIONAL)` part from the label. p1706636840560769-slack-C06C7C3AQHL
