### ISSUE TITLE
Logging: Update the developer docs to reflect enhancements to the logging system and the log file handler

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#43147]
[This document](https://github.com/woocommerce/woocommerce/blob/trunk/docs/utilities/logging.md) should be reviewed and updated in conjunction with the release of the logging enhancements.

**Comment by brentmackinnon** [comment]
@coreymckrill FYI this doc has been moved, this is the link you'll need now: https://github.com/woocommerce/woocommerce/blob/trunk/docs/extension-development/logging.md
