### ISSUE TITLE
Flat rate shipping strips out calculations

### ISSUE THREAD

**Issue by m7adam** [woothemes/woocommerce#43165]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This applies to Flat Rate Shipping. When entering a calculation ( i.e. [qty] * 10 ) in the flat rate shipping, the calculation is stripped. 

### Expected behavior

Calculation is expected to be saved and function.

### Actual behavior

If you enter a calculation with a value listed first (i.e. 10 * [qty] ), the value is saved, but the rest of the calculation is stripped. Otherwise, nothing is saved in these fields. I've tested this on multiple existing sites in addition to a clean install with WooCommerce the only plugin installed. None of them can save calculations. Sites that I know had calculations set up no longer have them.

### Steps to reproduce

1. Go to WooCommerce->Settings
2. Click on the Shipping tab
3. Edit a Shipping zone
4. Edit Flat rate shipping method
5. Attempt to enter a calculation in any cost field

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://temp.m7ws.com
Site address (URL): https://temp.m7ws.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.1.26
PHP Post Max Size: 16 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.5.23-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: WyTcy_
Total Database Size: 5.24MB
Database Data Size: 3.57MB
Database Index Size: 1.67MB
WyTcy_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
WyTcy_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
WyTcy_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
WyTcy_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
WyTcy_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
WyTcy_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
WyTcy_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_options: Data: 2.48MB + Index: 0.03MB + Engine InnoDB
WyTcy_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
WyTcy_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
WyTcy_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
WyTcy_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
WyTcy_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
WyTcy_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
WyTcy_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
WyTcy_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
WyTcy_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
WyTcy_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
WyTcy_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
WyTcy_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
WyTcy_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
WyTcy_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.4.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /index.php/shop/
Cart: #8 - /index.php/cart/
Checkout: #9 - /index.php/checkout/
My account: #10 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/vhosts/m7ws.com/temp.m7ws.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/var/www/vhosts/m7ws.com/temp.m7ws.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/var/www/vhosts/m7ws.com/temp.m7ws.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-29 20:19:36 +00:00
Options: ✔
Notes: 62
Onboarding: skipped

### Action Scheduler ###

Complete: 2
Oldest: 2023-12-28 20:20:46 +0000
Newest: 2023-12-28 20:20:46 +0000

Pending: 1
Oldest: 2023-12-29 20:20:46 +0000
Newest: 2023-12-29 20:20:46 +0000

### Status report information ###

Generated at: 2023-12-28 20:28:39 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shameemreza** [comment]
Related to #42759 and #42795, which have already been resolved and [merged in the beta version](https://github.com/woocommerce/woocommerce/releases/tag/8.5.0-rc.1).

You can either start using the beta version or wait until a new version gets released that includes this fix.

**Comment by jonathansadowski** [comment]
Thanks for the report. I'm going to close this as a duplicate, as this was resolved by the PR addressing the mentioned related issues.
