### ISSUE TITLE
Product description is not display in featured product block backend if short description not available.

### ISSUE THREAD

**Issue by VipulUpadala** [woothemes/woocommerce#43160]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have tested the featured product block with the latest WooCommerce version and found the product short description is not available then backend side description is not displayed in the featured product block. Please check the provided recording video below for how to reproduce the issues.

Video Recording: https://share.cleanshot.com/L6hfCPmYxSYlgZlyDZ2W

### Expected behavior

Need to display product description on backend side as well.

### Actual behavior

Do not display product description on backend side for featured product block( if short description not available).

### Steps to reproduce

1. Create a new page and take the featured product block.
2. After, Select the product( short description not available ).
3. Checked, Backend side description are not showing and frontend side showing.

### WordPress Environment

WordPress Version: WordPress 6.4.2 running
WooCommerce Version: 8.4.0
PHP Version: 8.0.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hi @VipulUpadala, thanks for creating this issue.
Unfortunately, the link you provided with the video no longer works (gives a 404 error).
I'm not sure I understand your issue, according to the tests I've done, when I insert a `Featured Product` block it shows the product's short description. If that one is empty, it shows the product description (the long one). It's working on the editor side and the front-end as well.
Could you confirm you are still having this issue, and maybe re-upload that video so we can assist you further?
Thanks a lot!
