### ISSUE TITLE
Shipping by quantity problem

### ISSUE THREAD

**Issue by katrinahadjimichael** [woothemes/woocommerce#43181]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am trying to allocate shipping costs per quantity of items and my website is not letting me do that.  When customers order multiple items it is only assigning one single postage cost.  I used to have it set up using [qty] but this is now not working.
Can you please advise what to do?

### Expected behavior

I want the website to assign postage to each item in the one order

### Actual behavior

When a customer orders multiple items it is just assigning one shipping cost

### Steps to reproduce

Assign postage by using [qty]

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://katrinahadjimichael.com.au
Site address (URL): https://katrinahadjimichael.com.au
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.7.0
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.16-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wpj2_
Total Database Size: 29.60MB
Database Data Size: 22.73MB
Database Index Size: 6.87MB
wpj2_woocommerce_sessions: Data: 7.35MB + Index: 0.22MB + Engine MyISAM
wpj2_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_downloadable_product_permissions: Data: 0.10MB + Index: 0.14MB + Engine MyISAM
wpj2_woocommerce_order_items: Data: 0.21MB + Index: 0.11MB + Engine MyISAM
wpj2_woocommerce_order_itemmeta: Data: 1.32MB + Index: 0.95MB + Engine MyISAM
wpj2_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_actionscheduler_actions: Data: 0.35MB + Index: 0.18MB + Engine MyISAM
wpj2_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_actionscheduler_logs: Data: 0.34MB + Index: 0.23MB + Engine MyISAM
wpj2_commentmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpj2_comments: Data: 0.78MB + Index: 0.34MB + Engine MyISAM
wpj2_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpj2_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_mailchimp_carts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpj2_mailchimp_jobs: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wpj2_options: Data: 1.73MB + Index: 0.14MB + Engine MyISAM
wpj2_postmeta: Data: 8.09MB + Index: 3.46MB + Engine MyISAM
wpj2_posts: Data: 1.59MB + Index: 0.40MB + Engine MyISAM
wpj2_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpj2_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpj2_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wpj2_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_usermeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpj2_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_admin_note_actions: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wpj2_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_customer_lookup: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
wpj2_wc_download_log: Data: 0.07MB + Index: 0.08MB + Engine MyISAM
wpj2_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_order_product_lookup: Data: 0.21MB + Index: 0.19MB + Engine MyISAM
wpj2_wc_order_stats: Data: 0.14MB + Index: 0.10MB + Engine MyISAM
wpj2_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpj2_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpj2_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpj2_yoast_seo_links: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpj2_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1203
custom_css: 2
jetpack_migration: 2
nav_menu_item: 30
page: 28
post: 1
product: 153
product_variation: 253
revision: 254
shop_coupon: 3
shop_order: 1673
shop_order_refund: 183

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Classic Editor: by WordPress Contributors – 1.6.3
Disable Gutenberg: by Jeff Starr – 3.1
Facebook for WooCommerce: by Facebook – 3.1.6
Genesis Connect for WooCommerce: by StudioPress – 1.1.2
Genesis eNews Extended: by Brandon Kraft – 2.2.0
Genesis Simple Edits: by StudioPress – 2.3.1
Mailchimp for WooCommerce: by Mailchimp – 3.5
Simple Social Icons: by OsomPress – 3.2.2
Six/Ten Press Featured Content: by Robin Cornett – 1.6.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.23.16

WooCommerce Blocks: by Automattic – 11.7.0
WP Menu Cart: by WP Overnight – 2.14.2
WooCommerce: by Automattic – 8.4.0
WP Instagram Widget: by Scott Evans – 2.0.3

### Inactive Plugins (1) ###

PixelYourSite: by PixelYourSite – 9.4.7

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #38 - /shop/
Cart: #39 - /cart/
Checkout: #40 - /checkout/
My account: #41 - /my-account/
Terms and conditions: #330 - /terms-conditions/

### Theme ###

Name: Foodie Pro
Version: 3.1.0
Author URL: https://feastdesignco.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-30 09:57:27 +11:00
Options: ✔
Notes: 126
Onboarding: completed

### Action Scheduler ###

Complete: 1,037
Oldest: 2023-11-29 15:08:19 +1100
Newest: 2023-12-30 14:02:01 +1100

Failed: 9
Oldest: 2023-02-20 18:45:52 +1100
Newest: 2023-06-05 12:41:43 +1000

Pending: 3
Oldest: 2023-12-30 17:17:34 +1100
Newest: 2024-01-05 11:34:30 +1100

### Status report information ###

Generated at: 2023-12-30 14:10:30 +11:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks fopr reaching out, @katrinahadjimichael.

> I am trying to allocate shipping costs per quantity of items and my website is not letting me do that. When customers order multiple items it is only assigning one single postage cost. I used to have it set up using [qty] but this is now not working.
Can you please advise what to do?

Can you share screenshots of how you've set up the shipping costs? On https://katrinahadjimichael.com.au/cart/, I indeed see that the shipping costs are assigned globally and not per cart item. 

I tried to reproduce this issue on my end using WooCommerce 8.4.0 and WooCommerce Blocks 11.7.0, as listed in your system status report. I've then added the shipping class `Flat rate` with the costs `10 * [qty]`. When adding products to the cart, I see shipping costs being charged per cart item. Below, I've added screenshots of my settings and the corresponding results.

### Shipping costs settings

<img width="1512" alt="Screenshot 2024-01-02 at 16 21 12" src="https://github.com/woocommerce/woocommerce/assets/3323310/b8a18fc8-6905-4e86-85cc-a64807182146">

### One product with a quantity of 1 → 10 € shipping costs

<img width="1512" alt="Screenshot 2024-01-02 at 16 24 15" src="https://github.com/woocommerce/woocommerce/assets/3323310/056af396-7fcf-4de0-9f09-01438f7c4cc0">

### One product with a quantity of 2 → 20 € shipping costs 

<img width="1512" alt="Screenshot 2024-01-02 at 16 24 50" src="https://github.com/woocommerce/woocommerce/assets/3323310/59e51803-c81d-4656-aa4b-4b05b49c4e23">

### Two products with a quantity of 1 each → 20 € shipping costs 

<img width="1512" alt="Screenshot 2024-01-02 at 16 25 38" src="https://github.com/woocommerce/woocommerce/assets/3323310/18e55eb1-753d-46c8-ac89-4b1e9d2a6b29">

**Comment by katrinahadjimichael** [comment]
Hi Niels thank you for responding

I have tried to charge by quanity by adding * [qty] as shown in the screen shoot below. 
![Screenshot 2024-01-04 115423](https://github.com/woocommerce/woocommerce/assets/155209602/b6c46fe7-c12d-437d-8db9-002a01dcedc1)

But when I click save it reverts to looking like this. 
![Screenshot 2024-01-04 115702](https://github.com/woocommerce/woocommerce/assets/155209602/23f713ac-e147-489a-b320-6973c01449b0)

I can change the prices but no other changes seem to be implemented when I press save.

**Comment by senadir** [comment]
Hey! this was also reported here https://github.com/woocommerce/woocommerce/issues/42892 and fixed here https://github.com/woocommerce/woocommerce/pull/42916 which shipped on WooCommerce 8.5.0 (released today).

**Comment by cannglass** [comment]
> Hey! this was also reported here #42892 and fixed here #42916 which shipped on WooCommerce 8.5.0 (released today).

Thanks. You indicate the problem was fixed today but I'm still experiencing exactly the same problem as explained by katrinahadjimichael Will I automatically be updated with WooCommerce 8.5.0 or is there someway I have to do this manually? This problem is causing me a great deal of anxiety. I would be very grateful for any help as communicating directly through Wordpress/WooCommerce is proving very slow - I don't think they are taking this seriously.

Richard
https://leadedstainedglass.com/

**Comment by senadir** [comment]
Hey @cannglass ! You're still running WooCommerce 8.4.0 in your website, it doesn't seem like you're running on a [managed Woo hosting](https://woo.com/express/), but on the regular WordPress hosting, in that case, you have to update the plugin yourself.
