### ISSUE TITLE
Translation Issue on Frontend for Cart, Checkout, and Mini-Cart Pages

### ISSUE THREAD

**Issue by sdelon** [woothemes/woocommerce#43185]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've encountered a translation problem on my WordPress site using WooCommerce. The pages for cart, checkout, and mini-cart are not displaying the correct French translation on the frontend, despite being correctly translated in the WooCommerce back office.

### Expected behavior

The pages mentioned above should display the translated content in French on the frontend, consistent with the translations set in the WooCommerce back office.

### Actual behavior

On each of the mentioned pages, only the term 'sous-total' is in French. Everything else is in English.

### Steps to reproduce

1. Set the site language to French in the WordPress settings.
2. Download the woocommerce plugin.
3. Ensure that the cart, checkout, and mini-cart pages are correctly translated in the WooCommerce back office.
4. View the frontend of the website and navigate to the cart, checkout, or mini-cart pages all in english.
[screen-capture.webm](https://github.com/woocommerce/woocommerce/assets/53929569/2c120569-2195-492d-a326-74dfe5183555)

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): http://devcreasite-bienetre.local
Site address (URL): http://devcreasite-bienetre.local
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1 000 Mo
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Taille totale de la base de données: 6.32MB
Taille de la base de données: 4.63MB
Taille de l’index: 1.69MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 3.48MB + Index : 0.06MB + Moteur InnoDB
wp_postmeta: Données : 0.08MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.06MB + Index : 0.06MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 18
page: 7
post: 2
product: 11
revision: 2
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: par Automattic – 8.4.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #7 - /boutique/
Panier: #8 - /panier/
Commander: #9 - /commander/
Mon compte: #10 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://fr.wordpress.org
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-31 08:25:48 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Terminé: 14
Oldest: 2023-12-30 08:26:48 +0000
Newest: 2023-12-30 08:33:48 +0000

Échoué: 1
Oldest: 2023-12-30 08:31:49 +0000
Newest: 2023-12-30 08:31:49 +0000

En attente: 1
Oldest: 2023-12-31 08:26:48 +0000
Newest: 2023-12-31 08:26:48 +0000


### Status report information ###

Generated at: 2023-12-30 08:34:03 +00:00```

<details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Hello @sdelon 👋

Thanks for reaching out. Some translations might be missing, as the translation pack hasn't been fetched yet. After switching the site language to French, could you go to `/wp-admin/update-core.php` and scroll down to the section `Traductions`. If you see a button called `Mettre à jour les traductions`, then please press that button to fetch the latest translations. For the different blocks, it's also possible that you need to remove and re-add the blocks again so that they fetch the French translations. Doing so should show the expected translations.

## Mini-Cart block

<img width="1512" alt="Screenshot 2024-01-02 at 15 54 16" src="https://github.com/woocommerce/woocommerce/assets/3323310/c0235c03-6f07-486a-b394-2da65246af33">

## Cart block

<img width="1512" alt="Screenshot 2024-01-02 at 15 54 41" src="https://github.com/woocommerce/woocommerce/assets/3323310/cee458fd-70bc-4755-a7c2-a3b5cfc43e85">

## Checkout block

<img width="1512" alt="Screenshot 2024-01-02 at 15 54 57" src="https://github.com/woocommerce/woocommerce/assets/3323310/81d3df72-04b5-4e62-b9b5-7245d872132b">

**Comment by sdelon** [comment]
Thanks @nielslange for your response !

Simply, when I am on the `/wp-admin/update-core.php` page, I see the message that all translations are up to date. 
Nevertheless, I tried to remove the "cart" block on the cart page and add it again, but the translation issue remains the same. 
The page is in French in the back office, but in English on the front end.

**Comment by nielslange** [comment]
@sdelon When you're on the `/wp-admin/update-core.php` page, have you also clicked on the `Vérifier à nouveau.` link at the top to check if new translations appear? The system status report, that you shared above, is accurate, right? Thus, the only plugin, you have installed, is WooCommerce 8.4.0, and you are using `fr_FR` (`Français`) as locale? I'm asking, as with this plugin and this local, I do see French translations for the corresponding blocks.

**Comment by sdelon** [comment]
@nielslange No new translations available even after clicking on `Vérifier à nouveau` .
I'm not sure though if the issue is related to the translations, as indeed, the page displays correctly in French in the editor. However, on the website, the page is in English.

![Capture d'écran 2024-01-03 125536](https://github.com/woocommerce/woocommerce/assets/53929569/d29be27c-b63a-4528-a9ab-449aace6d35a)
![Capture d'écran 2024-01-03 125553](https://github.com/woocommerce/woocommerce/assets/53929569/04e94dd4-f9ee-4ef3-80d4-88423980a752)

**Comment by nielslange** [comment]
On your screenshot, I see the frontend of the Mini-Cart block, but the backend of the Cart block. You mentioned that you replaced the Cart block. Is it possible that you haven't replaced the Mini-Cart block yet? If the Mini-Cart block had been added before the site language has been changed to French, that block would still appear in English.

**Comment by sdelon** [comment]
@nielslange The first thing I do when I create a wp site is change the language. But to make sure the problem wasn't synchronization, I removed the mini-cart block from my header and added it back. But the result is the same. I made a short video to make sure I hadn't missed a step. Thanks !

https://github.com/woocommerce/woocommerce/assets/53929569/53ff44fb-130e-4c62-b095-9f29afa9445d

**Comment by senadir** [comment]
I'm not able to reproduce this



![Image](https://github.com/woocommerce/woocommerce/assets/6165348/43165ddb-9bec-4432-aedd-d3adccc03f11)



![Image](https://github.com/woocommerce/woocommerce/assets/6165348/dd590935-d403-4191-8803-a8fd5df9b80d)

**Comment by mikejolley** [comment]
These are also template parts @sjeden. Go to Appearance > Patterns > Template Parts > General and you'll find the "mini cart" template. The heading can be customised there. Does changing that solve the issue?

I'm wondering if those parts were created and saved before the translation files were updated.

**Comment by nielslange** [comment]
Hello @sjeden, have you tried the steps @mikejolley suggested in https://github.com/woocommerce/woocommerce/issues/43185#issuecomment-1904345282?

**Comment by wavvves** [comment]
@sjeden I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Comment by lernerValeriy** [comment]
Good day! 
I have the same issue with Ukrainian Translation.
Downloads https://uk.wordpress.org/.
Language is set automatic to Ukrainian.
Then install Woocommerce.

Translation works perfect in admin editor! But on user frontend site translation from child blocks (inner blocks of checkout block) like "woocommerce/checkout-shipping-address-block" does not append to script with id="wc-blocks-checkout-js-translations".

Very strange behavior! Any suggestion how to force load translation to user frontend?

User fronend:
![image](https://github.com/woocommerce/woocommerce/assets/18212394/4d2f2442-f313-4265-b9b0-c51fd61db7c8)

Admin editor frontend:
![image](https://github.com/woocommerce/woocommerce/assets/18212394/165b8cce-0b3d-4dab-a1fd-5c3c186eb60a)

**Comment by senadir** [comment]
Hey @lernerValeriy , this could be a cache issue (I'm not fully sure).
You can remove the `woocommerce_blocks_asset_api_script_data` and `woocommerce_blocks_asset_api_script_data_ssl` transients (using WP CLI or a transient manager)?

**Comment by lernerValeriy** [comment]
Done with no luck. Thanks for reply!

**Comment by danielxreis** [comment]
Save behaviour for brazilian translation. On the admin backend, it shows translated, but in frontEnd it doesn't. Refreshed cache, new installation, no matter what

**Comment by ElementMedia** [comment]
Also happends to me with a dutch translation. Backend shows the right translations, but the frontend won't.

**Comment by onursro** [comment]
Also happend to me with a dutch translation. Backend shows the right translations, but the frontend won't.

**Comment by nielslange** [comment]
@lernerValeriy, @danielxreis, @ElementMedia and @Vuox Does the translation issue happen on online sites or on local sites, e.g. using XAMPP, Local WP, etc.? If the issue happens online, could you share the link to the site or a screenshot that shows which strings are not translated? This helps to investigate this issue better.

**Comment by onursro** [comment]
> @lernerValeriy, @danielxreis, @ElementMedia and @Vuox Does the translation issue happen on online sites or on local sites, e.g. using XAMPP, Local WP, etc.? If the issue happens online, could you share the link to the site or a screenshot that shows which strings are not translated? This helps to investigate this issue better.

The strings are already all being correctly translated, when switching from the new block editor to the shortcode classic editor the translation becomes correct. But wanna use the new editor

**Comment by ElementMedia** [comment]
> @lernerValeriy, @danielxreis, @ElementMedia and @Vuox Does the translation issue happen on online sites or on local sites, e.g. using XAMPP, Local WP, etc.? If the issue happens online, could you share the link to the site or a screenshot that shows which strings are not translated? This helps to investigate this issue better.

Both online and on my local Local Flywheel environment. Unfortunately I don't have a live URL to show, because:

> The strings are already all being correctly translated, when switching from the new block editor to the shortcode classic editor the translation becomes correct. But wanna use the new editor

I did the switch to the classic editor and added some basic styling for now.

**Comment by lernerValeriy** [comment]
https://gakhak.autos/
http://biowe.beauty/

Running on Windows Laragon environment without crontab. Without ftp.
I can provide you with admin pass to email. My email lerwebdev@gmail.com

**Comment by onursro** [comment]
> https://gakhak.autos/ http://biowe.beauty/
> 
> Running on Windows Laragon environment without crontab. Without ftp. I can provide you with admin pass to email. My email [lerwebdev@gmail.com](mailto:lerwebdev@gmail.com)

The exact same words are for me not translating this is probably a bug of Woocommerce, they need to fix this asap.

**Comment by nielslange** [comment]
Thanks for your replies. I've created some general troubleshooting steps. While not all steps might apply to you, please execute the ones that apply to you, to see if that solves the issue. 

- Check if the string is actually translated in GlotPress.
- Ensure to fetch all translations via [`[/wp-admin/update-core.php?force-check=1](https://store.test/wp-admin/update-core.php?force-check=1)`](https://store.test/wp-admin/update-core.php?force-check=1).
- Delete the Cart and Checkout blocks and re-add them again.
- Delete the Cart and Checkout pages and re-create them via `WooCommerce » Status » Tools » Create Pages.`
- Delete all transients using the [[Transients Manager](https://en-gb.wordpress.org/plugins/transients-manager/)](https://en-gb.wordpress.org/plugins/transients-manager/).
- Output the PHP constant `WP_LANG_DIR` to check the path of loaded translations.
- Output the PHP constants `WP_CONTENT_FOLDERNAME`, `WP_CONTENT_DIR`  and `WP_CONTENT_URL` to check where WordPress is installed.
- Check if the translation file (HASH.json) contains the translated string.

If you have tried any steps that are not mentioned on the list, it would be great if you could mention these extra steps.

**Comment by onursro** [comment]
> Thanks for your replies. I've created some general troubleshooting steps. While not all steps might apply to you, please execute the ones that apply to you, to see if that solves the issue.
> 
> * Check if the string is actually translated in GlotPress.
> * Ensure to fetch all translations via [`[/wp-admin/update-core.php?force-check=1](https://store.test/wp-admin/update-core.php?force-check=1)`](https://store.test/wp-admin/update-core.php?force-check=1).
> * Delete the Cart and Checkout blocks and re-add them again.
> * Delete the Cart and Checkout pages and re-create them via `WooCommerce » Status » Tools » Create Pages.`
> * Delete all transients using the [[Transients Manager](https://en-gb.wordpress.org/plugins/transients-manager/)](https://en-gb.wordpress.org/plugins/transients-manager/).
> * Output the PHP constant `WP_LANG_DIR` to check the path of loaded translations.
> * Output the PHP constants `WP_CONTENT_FOLDERNAME`, `WP_CONTENT_DIR`  and `WP_CONTENT_URL` to check where WordPress is installed.
> * Check if the translation file (HASH.json) contains the translated string.
> 
> If you have tried any steps that are not mentioned on the list, it would be great if you could mention these extra steps.

None of what you mentioned helps, i have tried this on different enviroments and multiple clean starts also. Somehow everytime the Gutenberg blocks of Woocommerce are showing up correct at the back-end but half translated on the front-end. Funny because the exact same parts are for the other people not translated like for me. 

must be a woocommerce issue

**Comment by senadir** [comment]
Opening this issue because it's valid and we have a fix for it here https://github.com/woocommerce/woocommerce/pull/47625.

**Comment by stephane31git** [comment]
Hello
I had the same problem with a French site.
English and French mixed in the shopping cart pages.
In fact this site was in development with Wamp in a localhost, when I put the site on classic hosting, everything is ok

**Comment by adrianratajczak** [comment]
I am occurring same issue. When WP is installed with English and then changed to my language. woo blocks are still displaying in English. No way to change it.

**Comment by baselvadmin** [comment]
Yesterday lost 4 hours debugging this issue. Backend shows translated version, but frontend does not. 

So for me the issue was minifying javascript in my optimization plugin. As soon as I disabled this option translation works! 

Hope this saves someones nerves.
