### ISSUE TITLE
No Save/Update Option/Button in Edit Product

### ISSUE THREAD

**Issue by dec-mail** [woothemes/woocommerce#43188]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

No Save/Update Option/Button in Edit Product

### Expected behavior

A Save/Update Button/Option

### Actual behavior

No Save/Update Option

### Steps to reproduce

Edit a Product
![blossom-products- no-save-2-29-12-2023 6-54-52 PM](https://github.com/woocommerce/woocommerce/assets/149738734/6036e233-6a00-42ca-8090-3b459b99a9bc)
![blossom-products- no-save-29-12-2023 6-54-52 PM](https://github.com/woocommerce/woocommerce/assets/149738734/9e918f08-20e5-4973-869d-e75df6fdebd0)
![blossom-prodicts-29-12-2023 7-19-58 PM](https://github.com/woocommerce/woocommerce/assets/149738734/41f27e5f-38ff-43db-9f04-a574f58db813)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://redcat-tees.shop
Site address (URL): https://redcat-tees.shop
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.13
PHP Post Max Size: 2 GB
PHP Time Limit: 3000
PHP Max Input Vars: 100000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.23-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wpqu_
Total Database Size: 53.05MB
Database Data Size: 45.36MB
Database Index Size: 7.69MB
wpqu_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_actionscheduler_actions: Data: 2.42MB + Index: 0.80MB + Engine InnoDB
wpqu_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_actionscheduler_logs: Data: 1.48MB + Index: 0.44MB + Engine InnoDB
wpqu_aioseo_cache: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wpqu_aioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wpqu_aioseo_posts: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wpqu_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_blc_instances: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_blc_links: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpqu_blc_synch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpqu_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_frmt_form_entry: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_frmt_form_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_frmt_form_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_frmt_form_views: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wpqu_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_iqblock_logging: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_newsletters: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpqu_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wpqu_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_omnisend_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_options: Data: 6.44MB + Index: 0.16MB + Engine InnoDB
wpqu_postmeta: Data: 0.48MB + Index: 0.17MB + Engine InnoDB
wpqu_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wpqu_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wpqu_prli_links: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wpqu_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_trp_dictionary_en_au_vi: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_gettext_en_au: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wpqu_trp_gettext_en_us: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_gettext_original_strings: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_gettext_vi: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpqu_uap_action_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpqu_uap_api_log_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_uap_recipe_count: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpqu_uap_recipe_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_uap_tokens_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wpqu_uap_trigger_log_meta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpqu_userfeedback_surveys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_userfeedback_survey_responses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpqu_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpqu_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpqu_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpqu_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_wfconfig: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wpqu_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wffilemods: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
wpqu_wfhits: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wpqu_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_wfknownfilelist: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wpqu_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqu_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wpqu_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqu_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_wfstatus: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wpqu_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wpqu_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqu_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqu_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqu_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 70
customize_changeset: 56
elementor_library: 1
forminator_forms: 1
is_search_form: 4
language_switcher: 4
mailpoet_page: 1
modula-gallery: 4
nav_menu_item: 13
page: 12
post: 2
product: 4
product_variation: 32
revision: 9
sp_easy_accordion: 1
uo-recipe: 1
wp_navigation: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.26.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Breadcrumb NavXT: by John Havlik – 7.2.0
Broken Link Checker: by WPMU DEV – 2.2.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.13
Customer Reviews for WooCommerce: by CusRev – 5.38.8
Easy Accordion: by ShapedPlugin LLC – 2.2.5
Elementor: by Elementor.com – 3.18.3
File Manager Advanced: by modalweb – 5.2
FileBird Lite: by Ninja Team – 5.5.8.1
Forminator: by WPMU DEV – 1.28.1
Google Listings and Ads: by WooCommerce – 2.5.14
XML Sitemap Generator for Google: by Auctollo – 4.1.16
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.3
Smash Balloon Instagram Feed: by Smash Balloon – 6.2.6
iQ Block Country: by Pascal – 1.2.21
LiteSpeed Cache: by LiteSpeed Technologies – 6.0.0.1
MailPoet: by MailPoet – 4.40.0
Modula: by WPChill – 2.7.9
Nifty Coming Soon & Maintenance Page: by WP Hait – 3.0.9
Omnisend for Woocommerce: by Omnisend – 1.13.12
Pinterest for WooCommerce: by WooCommerce – 1.3.18
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.41

Really Simple SSL: by Really Simple Plugins – 7.2.1
SureTriggers: by SureTriggers – 1.0.32
Temporary Login Without Password: by StoreApps – 1.8.3
Tidio Chat: by Tidio Ltd. – 6.0.11
TrustPulse API: by  – 1.1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.23.16

UserFeedback Lite: by UserFeedback Team – 1.0.13
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.54

WooCommerce Stripe Gateway: by WooCommerce – 7.8.1
WooCommerce PayPal Payments: by WooCommerce – 2.4.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.5
WooCommerce: by Automattic – 8.4.0
Wordfence Assistant: by Wordfence – 1.0.9
Wordfence Security: by Wordfence – 7.11.0
WP Mail SMTP: by WP Mail SMTP – 3.11.0
YITH WooCommerce Compare: by YITH – 2.34.0
YITH WooCommerce Quick View: by YITH – 1.34.0
YITH WooCommerce Wishlist: by YITH – 3.28.0

### Inactive Plugins (12) ###

Admin Menu Editor: by Janis Elsts – 1.12
All in One SEO: by All in One SEO Team – 4.5.3.1
Duplicator: by Duplicator – 1.5.7.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.23.1
OptinMonster: by OptinMonster Popup Builder Team – 2.15.1
PushEngage: by PushEngage – 4.0.7.1
RafflePress Lite: by RafflePress – 1.12.4
Redirection: by John Godley – 5.3.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Shared Counts: by Bill Erickson & Jared Atchison – 1.4.1
Uncanny Automator: by Uncanny Automator
Uncanny Owl – 5.4

WPCode Lite: by WPCode – 2.1.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #24 - /shop/
Cart: #25 - /cart/
Checkout: #26 - /checkout/
My account: #27 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: /home/decsites/redcat-tees.shop/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/decsites/redcat-tees.shop/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/decsites/redcat-tees.shop/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: VN
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-01 04:55:20 +07:00
Options: ✔
Notes: 71
Onboarding: completed

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://redcat-tees.shop?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 2,529
Oldest: 2023-12-12 11:56:25 +0700
Newest: 2023-12-31 19:21:13 +0700

Failed: 15
Oldest: 2023-12-12 11:57:32 +0700
Newest: 2023-12-31 04:39:14 +0700

Pending: 14
Oldest: 2023-12-31 19:22:13 +0700
Newest: 2024-01-01 14:00:00 +0700

### Status report information ###

Generated at: 2023-12-31 19:22:00 +07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @dec-mail,

It looks like you might have several plugins active, as well as possibly customizations to your theme. Can you verify that you're still able to reproduce this issue when _only_ WooCommerce is active, and if so, can you provide a list of steps that we can use to reproduce?

**Comment by dec-mail** [comment]
Hi Jon.

Well, of course, i have several plug-ins active! 39 active at the moment. i would have more except i have several turned off because they are not needed until the site goes live.

WP runs on plug-ins. There are heaps of functions you need for any site, and for an ecommerce site, and a plug-in for each.

A question: one problem is i do not know what/how the Save Product Edit option/function actually looks or appears on the Edit Product form,
 so i do not know what i am looking for if it was there.

In the Quick Edit form, there is an UPDATE button/function. - which is NOT there in the full Edit Product form.

Just now, i see a Save/Update button when i edited Variations. which appears to be ONLY for Variations.

(and i discovered another kludge - it does NOT display ALL saved Attribute values - UNLESS i click 'Select All', and then it add al the missing vales. like, who knew!!)

![6-01-2024 11-15-06 AM](https://github.com/woocommerce/woocommerce/assets/149738734/44833e03-7151-4253-9030-e69278c9664c)
![6-01-2024 11-22-35 AM](https://github.com/woocommerce/woocommerce/assets/149738734/32e81953-edd8-4e8e-a472-13a99a6e7652)
![6-01-2024 11-21-12 AM](https://github.com/woocommerce/woocommerce/assets/149738734/390d525b-2378-42a0-b3fc-9ae4d8579787)
![6-01-2024 11-22-35 AM](https://github.com/woocommerce/woocommerce/assets/149738734/a35cdb95-0ef1-45bd-b921-b0f15f6887ab)

**Comment by dec-mail** [comment]
and just WHERE is Woocommerce SUPPORT?

**Comment by dec-mail** [comment]
it is clearly NOT a 'support' issue: it is clearly a BUG. 
what nonesense is that?
do you just close Issues that you can't fix to get rid of them???
and why is actual Support apparently hidden away so no-one can find????

**Comment by dec-mail** [comment]
Addendum
i have actually found the fix for this problem myself!

i almost inadvertently discovered a (closed) sub-menu drop-down on the far right of the page (12" in my case) called Publish - which when i opened it, included the UPDATE option i had been looking for all this time!

1. for some reason this critical drop-down located on the far right defaulted to closed ie hidden
2. 'Update' is really NOT a Publish option - it s a separate discrete thing that SHOULD be on the edited form itself!!! which is what every other edited form in the world does,

this was all obvious, if you knew, in the screen-shot i included

thanks a lot for all your help. NOT.

cheers
