### ISSUE TITLE
[DOC-BUG]Slack link no longer active

### ISSUE THREAD

**Issue by niharikamahajan02** [woothemes/woocommerce#43184]
## Description of the Suggestion

Please update the slack link for new contributors to interact

![image](https://github.com/woocommerce/woocommerce/assets/72392580/c53b71ae-3fb5-4751-95fd-29c86456f902)

**Comment by nielslange** [comment]
Hello @niharikamahajan02,

Thanks for reaching out. Can you tell me how to reproduce this issue? Where can I find the Slack link you're referring to?

**Comment by niharikamahajan02** [comment]
It's in the readme file https://github.com/woocommerce/woocommerce/blob/trunk/README.md
under the community section

**Comment by nielslange** [comment]
> It's in the readme file https://github.com/woocommerce/woocommerce/blob/trunk/README.md
under the community section

Thanks for clarifying this, @niharikamahajan02. I've reached out internally and will get back to you as soon as I have further information on this. Thanks again for reporting this.

**Comment by nielslange** [comment]
@niharikamahajan02 My colleagues updated the Slack link on https://woo.com/community-slack/. You should now be able to join the Slack channel.
