### ISSUE TITLE
[Analysis] Run report code as a pipeline script from a TeamCity deployment

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#43192]
This has been requested by David Newman (p1702946828761489/1702766361.393019-slack-C05DJ3J7D3Q)
> For the overall architecture, it isn't optimal to allocate resources permanently for an expected one-a-month service request cadence. We should rather be running it as a pipeline script from a TeamCity deployment so that the resources are allocated only for the duration of the report generation run.

It's currently an unknown how we can best support this task, so reaching out to David would be the first step.

**Comment by nima-karimi** [comment]
We've set up the script to run on a bi-weekly schedule every 2 weeks on Tuesdays, which generates the report and uploads it to Google Drive (ai-services#964). The on-demand report generation no longer works and requires further script changes. I've disabled the Airtable script for now (https://github.com/woocommerce/woocommerce/issues/41985) until we implement the on-demand report generation feature.
