### ISSUE TITLE
[Output] Create continual async job on WPCOM to generate report on a schedule

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#43191]
If this is still desired (talk to Rania ), we may want to generate a report on all FSOR data on a schedule. 

This may be coupled with an effort to automatically post a p2 by inserting the markdown report into a Markdown block.

**Comment by nima-karimi** [comment]
This is done in ai-services#964. The report is generated every two weeks on Tuesdays and the result is stored in Google Drive.
