### ISSUE TITLE
Deprecated: Function WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead. in /home/asapchip/public_html/wp-includes/functions.php on line 6031

### ISSUE THREAD

**Issue by asap-chiptunngfiles** [woothemes/woocommerce#43200]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Deprecated: Function WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead. in /home/asapchip/public_html/wp-includes/functions.php on line 6031

### Expected behavior

Problems on my checkout

### Actual behavior

Notice: Function id was called incorrectly. Product properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), include(‘/plugins/elementor/modules/page-templates/templates/canvas.php’), Elementor\Modules\PageTemplates\Module->print_content, call_user_func, Elementor\Modules\PageTemplates\Module->print_callback, the_content, apply_filters(‘the_content’), WP_Hook->apply_filters, Elementor\Frontend->apply_builder_in_content, Elementor\Frontend->get_builder_content, Elementor\Core\Base\Documen

### Steps to reproduce

buy a product on asap-chiptuningfiles.com

On the checkoutpage with credits is the problem.
https://asap-chiptuningfiles.com/dashboard/credits/

### WordPress Environment

Deprecated: Function WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead. in /home/asapchip/public_html/wp-includes/functions.php on line 6031

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks for reaching out, @asap-chiptunngfiles.

> Deprecated: Function WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead. in /home/asapchip/public_html/wp-includes/functions.php on line 6031

> Notice: Function id was called incorrectly. Product properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), include(‘/plugins/elementor/modules/page-templates/templates/canvas.php’), Elementor\Modules\PageTemplates\Module->print_content, call_user_func, Elementor\Modules\PageTemplates\Module->print_callback, the_content, apply_filters(‘the_content’), WP_Hook->apply_filters, Elementor\Frontend->apply_builder_in_content, Elementor\Frontend->get_builder_content, Elementor\Core\Base\Documen

These messages indicate that you're using Elemenetor and that Elementor is using a function that was deprecated with WooCommerce 4.4.0. The most recent version is WooCommerce 8.4.0. I suggest reaching out to the Elementor support to clarify why the deprecated function is used.

**Comment by asap-chiptunngfiles** [comment]
The word support does not exist at elementor!!

**Comment by nielslange** [comment]
I'm afraid, there's nothing we can do on our end, as the message you shared indicates that the issue lies within the Elementor plugin.

**Comment by luissimo** [comment]
This error occurs on the REST API aswell:

`2024/03/19 11:13:50 [error] 29492#29492: *2104978 FastCGI sent in stderr: "PHP message: The WC_Abstract_Legacy_Order::get_product_from_item function is deprecated since version 4.4.0. Replace with $item->get_product()" while reading response header from upstream, client: 54.211.198.197, server: xx.com, request: "PUT /wp-json/wc/v3/orders/102041 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.3-fpm-xx.sock:", host: "xx:27006"`
