### ISSUE TITLE
WooCommerce API V3 failing to retrieve complete product list after 12/31/2023 11:40 PM

### ISSUE THREAD

**Issue by Kerry688** [woothemes/woocommerce#43213]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WooCommerce API V3 failing to retrieve complete product list after 12/31/2023 11:40 PM

I'm using the following API URL to get the product list from my website, but It suddenly not retrieving the whole list.
https://Domain.com/wp-json/wc/v3/products?consumer_key=****&consumer_secret=******&per_page=100&page=2

Now it's retrieving only 12/928 products. 

### Expected behavior

It is expected to fetch all simple products within 10 pages, totaling 928 products.

### Actual behavior

Currently, it is only fetching 12 products on the initial page.

### Steps to reproduce

Open the following URL using Postman / browser
https://Domain.com/wp-json/wc/v3/products?consumer_key=****&consumer_secret=******&per_page=100&page=2

### WordPress Environment

[SystemStatusReport_fotoexpresseg.com_2024-01-02T09-33-56.txt](https://github.com/woocommerce/woocommerce/files/13808636/SystemStatusReport_fotoexpresseg.com_2024-01-02T09-33-56.txt)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Kerry688,

Thanks for the report. Can you confirm that you're able to reproduce this issue with one WooCommerce active? If so, are there any set of steps that we could take to be able to reproduce?

Did you update anything on your site (such as WooCommerce) around 12/31? If so, does rolling back to the previous version resolve the issue?
