### ISSUE TITLE
Introduce pagination on the Product Collection Chooser component

### ISSUE THREAD

**Issue by xristos3490** [woothemes/woocommerce#43215]
### Description

Currently, the component is facing display issues as the core and custom collection types are expanding in number, leading to a significant increase in its height. To overcome this problem, pagination is suggested. 

Introducing pagination will help in efficiently managing the items and avoid any potential display issues that may arise due to an increase in the number of items. It will also ensure a better user experience and make the component more manageable and organized. 

Related: 
- https://github.com/woocommerce/woocommerce/issues/43214

cc @kmanijak @imanish003

**Comment by imanish003** [comment]
IMO, It will need design input. CC: @manospsyx

**Comment by xristos3490** [comment]
@imanish003 Agreed! Let's wait for some design input here. 

@kmanijak also mentioned that a new, more compact design might be applied to this component, making this request less relevant (at least for now.)

**Comment by kmanijak** [comment]
Considering we already have designs to solve that problem I'm closing this issue and we'll create a new one with the specific designs.
