### ISSUE TITLE
[Analysis] Resolve OpenAI API timeouts in production

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#43222]
An issue has emerged where our [lengthy request to OpenAI to summarize the clusters](https://github.com/Automattic/ai-services/blob/18816ba4c8cf00bc02472213c23e045db8291f28/fsor-report/openai_agent.py#L60) is timing out. This doesn't seem to happen when running on my local machine, but it does in production, and @nima-karimi  has mentioned (p1704160758229029/1704132526.791259-slack-C056QSJJQ91) that it's happening for him while testing.

[Logs of the error happening while generating a report.](https://logstash.a8c.com/logstash/app/discover#/?_g=h@f4940cf&_a=h@9a901cf)
[Log of proxy request with a duration of 116](https://logstash.a8c.com/logstash/app/discover#/?_g=h@b9ce74e&_a=h@61942e4) (just shy of 2 minutes)

I believe this _does_ involve our use of the proxy, as I saw it resolve on my local when we moved the timeout in the proxy up to 2 minutes, which the proxy timeout ( D132403-code). 

I've reached out (p1703954113573189/1702766361.393019-slack-C05DJ3J7D3Q) , although holiday AFKs have made it difficult to get traction on so far. 

@dereksmart  and @darthhexx are good people to connect with for resolve this.

**Comment by nima-karimi** [comment]
This is resolved for now by reducing the sample size sent to OpenAI: ai-services#913
