### ISSUE TITLE
[New Product Editor] Handle taxes not being enabled and customized tax classes

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#43232]
## Description

The new product editor does not currently support customized tax classes. It hardcodes tax classes and always shows the "charge sales tax on" field. 

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/68312aab-911b-4337-9286-5e709913e42f)

### Do not show tax fields if taxes are not enabled

If taxes are not enabled (**WooCommerce** > **Settings** > **General** > **Enable taxes**):

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/1369e0c2-eb0c-47f6-862e-776861d52edf)

then the tax fields should not be shown:

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/4c682cc8-ea2a-49d6-878f-eddbef8b1bd7)

Incorrect behavior in new product editor:

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/5f819291-feeb-4f00-be6f-79d18498db99)

### Show customized tax classes

The tax classes can be customized (**WooCommerce** > **Settings** > **Tax** > **Tax options**):

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/ac2e6102-6a6d-4eab-9d2b-1232423af501)

They should be be selectable:

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/615da932-623c-44e0-a598-e483a2823b65)

(Note: If no additional tax classes are configured, only the "Standard" tax class should be selectable)

Incorrect behavior in new product editor:

![Image](https://github.com/woocommerce/woocommerce/assets/2098816/fc2df31a-861e-45c8-a57f-36e7468bb057)

## Dev considerations

- We can check if "tax rates and calculations" is enabled and hide the tax fields in the layout template if they are not enabled

## UX considerations

- We could dynamically add the "additional tax classes" to the new product editor radio button group, but general UX design best practices frowns upon a large number of options in a radio button group. A simple dropdown is probably a better option.

## Acceptance criteria

- [ ] If "tax rates and calculations" is not enabled, tax fields should not be shown
- [ ] If "tax rates and calculations" is enabled, tax fields should be shown
- [ ] If "additional tax classes" are configured, they should be selectable, in addition to the "Standard" tax class
- [ ] If no "additional tax classes" are configured, only the "Standard" tax class should be selectable

## References

- [WC REST API endpoint for tax classes](https://woocommerce.github.io/woocommerce-rest-api-docs/#tax-classes)
- [Community Slack thread where issue was first raised](https://woocommercecommunity.slack.com/archives/C1KAZ91E3/p1703748357580039)

**Comment by j111q** [comment]
Thanks for the clear issue, @mattsherman!

1. I've changed the Tax Class field to a dropdown as suggested -- agreed that a radio group doesn't scale well here. Here's the updated screen in Figma: AkVNGImLgSqCObTQ3idVn7-fi-3359%3A289343
<img width="687" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/37a6b33c-ab86-485f-b9be-19d2144700f8">

2. I also added a state that shows all Tax options hidden, when `Enable taxes` is not checked in Settings. Here's the updated screen in Figma: AkVNGImLgSqCObTQ3idVn7-fi-13759%3A244820
<img width="649" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/8cdc43ed-6612-424a-881f-1e50839a4543">

cc @pmcpinto

**Comment by pmcpinto** [comment]
@j111q the changes look good to me. I'm just not sure if we should have the "Per your store settings, tax is included in the price." copy when taxes aren't enabled, as it doesn't necessarily mean that they're included in the price. I think it would be safer to change it to something like: Per your store settings, Taxes are disabled. 
What do you think?

**Comment by mattsherman** [comment]
> @j111q the changes look good to me. I'm just not sure if we should have the "Per your store settings, tax is included in the price." copy when taxes aren't enabled, as it doesn't necessarily mean that they're included in the price. I think it would be safer to change it to something like: Per your store settings, Taxes are disabled. What do you think?

@pmcpinto @j111q I agree. Taxes not being enabled does not mean taxes are included in the price. There might not be any taxes for what is being sold.

**Comment by pmcpinto** [comment]
> I think it would be safer to change it to something like: Per your store settings, Taxes are disabled.
What do you think?

@j111q can you review this suggestion? Thanks!

**Comment by j111q** [comment]
I tweaked this to `Per your store settings, taxes are not enabled`. to be most accurate since they didn't actively disable it, they just didn't enable it, if that makes sense. 

<img width="714" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/5d184f2d-0d6e-4c1e-8678-3b0ff74a54a4">

LMK if that works!

**Comment by pmcpinto** [comment]
It looks good to me. Thanks!
