### ISSUE TITLE
Broken link for StoreApi documentation [DOC-BUG]

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woothemes/woocommerce#43246]
## Link to the Page/Section
https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/src/StoreApi

## Description of the Suggestion
When you click on the section named [Store API (REST API)](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/src/StoreApi/README.md) 
there is no further documentation. 

## Reason for the Suggestion
Well, we are missing basic documentation for cart and product responses from Store API. Maybe there are somewhere else to be found but it would be nice to have an option to find them easily.

**Comment by nielslange** [comment]
Hello @TatjanaDjurdjevic, 

Thanks for reaching out. When I open https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/src/StoreApi, I get an error 404. Could you please double-check the URL of the docs you're referring to?

**Comment by TatjanaDjurdjevic** [comment]
Hello @nielslange,
Thanks for the quick response. 

When from this page https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/ 
I click on STORE API (REST API) there is an error 404.

So I am not sure where to find the documentation that is up to date for STORE API (REST API).

**Comment by nielslange** [comment]
Thanks for providing the link to the page on which you noticed the broken link. I've created a fix for this issue in #43261. Meanwhile, you can directly access the desired docs page via https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/StoreApi. Thanks again for bringing this to our attention. 🙌
