### ISSUE TITLE
Reduce repetitive error logging when registering checkout fields

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#43277]
In p1703132883414589-slack-C05JQBR78RW we found that there is error logging when registering checkout fields incorrectly.

We are currently using the WC logger, but the fields are registered on every page load so the errors are reported every page load too.

We spoke about this and decided that `_doing_it_wrong` is a better approach to handling these types of errors.

**Comment by ralucaStan** [comment]
@opr mind adding this to the Epic as well? #43043 was part of the epic, but was closed as duplicate
