### ISSUE TITLE
Product Collection block: add to cart adds two products to the cart

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#43288]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When click on the _Add to cart_ button of the Product Collection block, it looks like the product is added twice to the cart. However, on the first instance it's only in fact added once.

### Expected behavior

Clicking on _Add to cart_ should only add one item.

### Actual behavior

Clicking on _Add to cart_ should adds two items if the product is already in the cart. If the product is not yet in the cart, it's only added once but the button shows it as if it was added twice.

### Steps to reproduce

1. Switch your theme to Storefront.
2. Create a new page and add the Product Collection or the Products block.
3. In the frontend, add a product to your cart.
4. Notice the button shows `2 in cart` and the Mini-Cart shows 1 product in the cart.
5. Add the same product again to the cart.
6. Notice the button shows `4 in cart` and the Mini-Cart shows 3 products in the cart.

### WordPress Environment

- WordPress 6.4.2
- WooCommerce `trunk`.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Aljullu** [comment]
cc @imanish003 and @kmanijak as you might want to prioritize this one. However, I remember this issue appearing some time ago in a PR (https://github.com/woocommerce/woocommerce-blocks/pull/10006#pullrequestreview-1528084584), so maybe it has always been there?

**Comment by Aljullu** [comment]
* Blocks affected: Product Collection, Products and Single Product (with the Add to Cart button inside it).
* Blocks not affected: All Products, other legacy product grid blocks.

By the way, kudos to @veljkho for finding this bug!

**Comment by imanish003** [comment]
This issue appears to be associated with the Product Button rather than the Product Collection block itself. I'll investigate further shortly. CC: @gigitux

**Comment by gigitux** [comment]
Thanks for the ping, @imanish003!
Looks like a regression: https://github.com/woocommerce/woocommerce-blocks/pull/10006#issuecomment-1649503669 👀
