### ISSUE TITLE
Update highlight tooltip `anchorRect` usage

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#43297]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The `anchorRect` prop in the `Popover` component is deprecated since WP 6.1, we are still making use of this in the highlight tooltip shown when a user visits any unfinished task twice. We should remove its usage and make use of `anchor` instead.

```
`anchorRect` prop in wp.components.Popover is deprecated since version 6.1. Please use `anchor` prop instead.
```

**To reproduce:**

1. Create a new WordPress site
2. Finish the onboarding and go to **WooCommerce > Home**
3. Go to the **Add products** task but do nothing, instead hit the back button in the top left
4. Go back to the **Add products** task again
5. A `We're here for help` popup should appear.
6. Open your console and notice the ```deprecated.min.js?ver=73ad3591e7bc95f4777a:2 `anchorRect` prop in wp.components.Popover is deprecated since version 6.1. Please use `anchor` prop instead.``` warning

**Acceptance criteria**

- [ ] Helper popup should show up without a `anchorRect` warning.

**Comment by louwie17** [comment]
@adrianduffell I assigned Ghidorah to this given the component is used predominantly in the setup task list, let me know if you prefer us to handle this or if you have the bandwidth ( should be relatively simple ).

**Comment by adrianduffell** [comment]
Thanks @louwie17 , looks like you worked on it anyway but also would have been happy for Ghidorah to take it 👍
