### ISSUE TITLE
Remove the 'Need help?' spotlight

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#43300]
We currently display a spotlight pointing to the help section in Woo's top bar after the user enters the store setup flow. It wasn't implemented properly because it's being shown more than once and there are some visual issues.

The top bar will be removed or redesigned shortly, so I don't think the spotlight is needed anymore. It's best to delete it.

<img width="163" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/a046741c-9281-425a-bd5a-57bfdf1a1102">

**Acceptance criteria**

- [ ] Remove use of `We're here for help` highlight tooltip
- [ ] Remove the `help_panel_highlight_shown` user preference
- [ ] (optional ) We may also want to remove `task_list_tracked_started_tasks` user preference, this will depend if it is used for anything else or if we use it for tracking still.

**Comment by adrianduffell** [comment]
Re-opening so that a clean-up of user meta can be done as a follow-up. See https://github.com/woocommerce/woocommerce/pull/47812#pullrequestreview-2247051324

**Comment by adrianduffell** [comment]
Some prior art for updating user meta: https://github.com/woocommerce/woocommerce/pull/50664/files#diff-ef66873bc65699d07994f8ac9621c771df9f9e63ce74c94b70defac87aab52d1R2831-R2854

**Comment by adrianduffell** [comment]
Also: https://github.com/woocommerce/woocommerce/pull/50583#issuecomment-2288044628
