### ISSUE TITLE
Template version bump CI should explain the expected version on failure

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#43327]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
When a template bump is required, the messaging should indicate the expected version to remove confusion around expectations and help the contributor resolve the template versioning issue. p1704440691310709-slack-C03CPM3UXDJ

**Comment by rrennick** [comment]
Addressed in #46021.
