### ISSUE TITLE
wc_get_product_ids_on_sale doesn't return onsale product ids if start_sale_date is today

### ISSUE THREAD

**Issue by hardweb-it** [woothemes/woocommerce#43322]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Calling wc_get_product_ids_on_sale() function doesn't return the product ids if the product start_sale_date is today.

### Expected behavior

If a variable product have onsale price and the start_sale_date is today or in the past, the function should return the product id in array.

### Actual behavior

If a variable product have onsale price and the start_sale_date is equal to today, the function doesn't return the product id in array.

### Steps to reproduce

- today is 2024-01-05, the start_sale_date for all the product variations is set to 2024-01-05
- Calling wc_get_product_ids_on_sale() doesn't return the product id in array.
- If I edit the start_sale_date to 2024-01-04, the function return correctly an array with the product id as expected.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hideforprivacy.it
Site address (URL): https://hideforprivacy.it
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.23-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: bbbwp_
Dimensione totale database: 115.01MB
Dimensione dati database: 85.85MB
Dimensione indice database: 29.16MB
bbbwp_woocommerce_sessions: Dati: 1.02MB + indice: 0.02MB + motore InnoDB
bbbwp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_woocommerce_order_items: Dati: 0.22MB + indice: 0.08MB + motore InnoDB
bbbwp_woocommerce_order_itemmeta: Dati: 1.52MB + indice: 2.94MB + motore InnoDB
bbbwp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_actionscheduler_actions: Dati: 1.03MB + indice: 0.67MB + motore InnoDB
bbbwp_actionscheduler_claims: Dati: 0.08MB + indice: 0.05MB + motore InnoDB
bbbwp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_actionscheduler_logs: Dati: 1.03MB + indice: 1.16MB + motore InnoDB
bbbwp_berocket_termmeta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_cartflows_ca_cart_abandonment: Dati: 0.16MB + indice: 0.02MB + motore InnoDB
bbbwp_cartflows_ca_email_history: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_cartflows_ca_email_templates_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_comments: Dati: 1.52MB + indice: 0.50MB + motore InnoDB
bbbwp_ee_products_sync_list: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_ee_product_feed: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_ee_product_sync_call: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_ee_product_sync_data: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_ee_tiktok_catalog: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_ewwwio_images: Dati: 3.52MB + indice: 3.03MB + motore InnoDB
bbbwp_ewwwio_queue: Dati: 0.06MB + indice: 0.05MB + motore InnoDB
bbbwp_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_e_notes: Dati: 0.02MB + indice: 0.17MB + motore InnoDB
bbbwp_e_notes_users_relations: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
bbbwp_e_submissions: Dati: 0.02MB + indice: 0.27MB + motore InnoDB
bbbwp_e_submissions_actions_log: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
bbbwp_e_submissions_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_jetpack_sync_queue: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_litespeed_avatar: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_litespeed_crawler: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
bbbwp_litespeed_crawler_blacklist: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_litespeed_img_optming: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
bbbwp_litespeed_url: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
bbbwp_litespeed_url_file: Dati: 1.22MB + indice: 0.77MB + motore InnoDB
bbbwp_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_mailchimp_jobs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_options: Dati: 15.28MB + indice: 1.23MB + motore InnoDB
bbbwp_postmeta: Dati: 17.52MB + indice: 7.78MB + motore InnoDB
bbbwp_posts: Dati: 4.52MB + indice: 0.66MB + motore InnoDB
bbbwp_rank_math_404_logs: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_rank_math_analytics_gsc: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_rank_math_analytics_inspections: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
bbbwp_rank_math_analytics_keyword_manager: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_rank_math_analytics_objects: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
bbbwp_rank_math_internal_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_rank_math_internal_meta: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
bbbwp_rank_math_redirections: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_rank_math_redirections_cache: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_sos_dqc_logs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_sos_dqc_otkeys: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_sos_dqc_qrcodes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_termmeta: Dati: 0.08MB + indice: 0.06MB + motore InnoDB
bbbwp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_term_relationships: Dati: 0.13MB + indice: 0.06MB + motore InnoDB
bbbwp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_usermeta: Dati: 2.52MB + indice: 1.94MB + motore InnoDB
bbbwp_users: Dati: 0.11MB + indice: 0.08MB + motore InnoDB
bbbwp_wc_admin_notes: Dati: 0.08MB + indice: 0.00MB + motore InnoDB
bbbwp_wc_admin_note_actions: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
bbbwp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wc_customer_lookup: Dati: 0.13MB + indice: 0.09MB + motore InnoDB
bbbwp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_wc_orders: Dati: 0.41MB + indice: 0.50MB + motore InnoDB
bbbwp_wc_orders_meta: Dati: 1.47MB + indice: 2.95MB + motore InnoDB
bbbwp_wc_order_addresses: Dati: 0.30MB + indice: 0.31MB + motore InnoDB
bbbwp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_wc_order_operational_data: Dati: 0.17MB + indice: 0.09MB + motore InnoDB
bbbwp_wc_order_product_lookup: Dati: 0.36MB + indice: 0.36MB + motore InnoDB
bbbwp_wc_order_stats: Dati: 0.20MB + indice: 0.16MB + motore InnoDB
bbbwp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
bbbwp_wc_product_attributes_lookup: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
bbbwp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wc_product_meta_lookup: Dati: 0.11MB + indice: 0.20MB + motore InnoDB
bbbwp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wfblockediplog: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfblocks7: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
bbbwp_wfconfig: Dati: 1.48MB + indice: 0.00MB + motore InnoDB
bbbwp_wfcrawlers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wffilechanges: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wffilemods: Dati: 13.55MB + indice: 0.00MB + motore InnoDB
bbbwp_wfhits: Dati: 2.02MB + indice: 0.30MB + motore InnoDB
bbbwp_wfhoover: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wfissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_wfknownfilelist: Dati: 9.52MB + indice: 0.00MB + motore InnoDB
bbbwp_wflivetraffichuman: Dati: 0.08MB + indice: 0.06MB + motore InnoDB
bbbwp_wflocs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wflogins: Dati: 0.09MB + indice: 0.03MB + motore InnoDB
bbbwp_wfls_2fa_secrets: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_wfls_role_counts: Dati: 0.00MB + indice: 0.00MB + motore MEMORY
bbbwp_wfls_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfnotifications: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfpendingissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
bbbwp_wfreversecache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfsecurityevents: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfsnipcache: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
bbbwp_wfstatus: Dati: 0.13MB + indice: 0.09MB + motore InnoDB
bbbwp_wftrafficrates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wfwaffailures: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wpmailsmtp_debug_events: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wpmailsmtp_tasks_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wsal_metadata: Dati: 1.52MB + indice: 0.61MB + motore InnoDB
bbbwp_wsal_occurrences: Dati: 0.42MB + indice: 0.14MB + motore InnoDB
bbbwp_wt_iew_action_history: Dati: 0.25MB + indice: 0.00MB + motore InnoDB
bbbwp_wt_iew_cron: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wt_iew_ftp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_wt_iew_mapping_template: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
bbbwp_yith_wcwl: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
bbbwp_yith_wcwl_lists: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstgbak_cartflows_ca_cart_abandonment: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wpstgbak_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB

### Post Type Counts ###

acf-field: 64
acf-field-group: 5
attachment: 937
br_labels: 3
custom_css: 1
customize_changeset: 1
e-landing-page: 1
elementor_font: 1
elementor_library: 45
ep-synonym: 1
gift_card: 1
nav_menu_item: 91
page: 22
post: 10
product: 181
product_variation: 427
qrcode: 1
revision: 399
shop_coupon: 21
shop_order: 973
shop_order_refund: 25
size-chart: 13
wp_global_styles: 2
wpcf7_contact_form: 3
yith-wcpsc-wc-chart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Admin Menu Editor: by Janis Elsts – 1.12
Advanced Custom Fields PRO: by WP Engine – 6.2.4
Advanced Custom Fields: Table Field: by Johann Heyne – 1.3.20
Classic Editor: by Contributori WordPress – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.8.5
Joinchat: by Creame – 5.0.15
Disable Cart Fragments: by Optimocha – 2.3
Disable Comments: by WPDeveloper – 2.4.5
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Elementor Pro: by Elementor.com – 3.18.2
Elementor: by Elementor.com – 3.18.3
EWWW Image Optimizer: by Exactly WWW – 7.2.2
Facebook for WooCommerce: by Facebook – 3.1.8
Site Kit by Google: by Google – 1.116.0
Jetpack: by Automattic – 12.9.3
Klaviyo: by Klaviyo Inc. – 3.3.3
MainWP Child: by MainWP – 4.6
PixelYourSite: by PixelYourSite – 9.4.7.1
Post Types Order: by Codice Nsp – 2.1.2
PW WooCommerce Bulk Edit Pro: by Pimwick LLC – 2.358
QR Redirector: by Nikki Blight  – 2.0.2
Rank Math SEO PRO: by Rank Math – 3.0.53
Rank Math SEO: by Rank Math – 1.0.210
SMX - Feeds generator: by Smartmix – 1.0.0
SVG Support: by Benbodhi – 2.5.5
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.8
Temporary Login Without Password: by StoreApps – 1.8.3
Product Size Charts Plugin for WooCommerce: by theDotstore – 2.4.3.2
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.26
WooCommerce Advanced Product Labels: by BeRocket – 3.2.6.4
WooCommerce Stripe Gateway: by WooCommerce – 7.8.1
WooCommerce PayPal Payments: by WooCommerce – 2.4.3
WooCommerce: by Automattic – 8.4.0
Wordfence Security: by Wordfence – 7.11.1
WP Crontrol: by John Blackbourn e collaboratori – 1.16.1
WP Mail SMTP: by WP Mail SMTP – 3.11.0
Product Import Export for WooCommerce Add-on: by WebToffee – 1.2.1
Import Export for WooCommerce Wrapper: by WebToffee – 1.2.4
YITH WooCommerce Frequently Bought Together Premium: by YITH – 1.32.0
YITH WooCommerce Gift Cards Premium: by YITH – 4.7.0
YITH WooCommerce Wishlist Premium: by YITH – 3.28.0

### Dropin Plugins (2) ###

maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #54529 - /shop/
Carrello: ❌ La pagina non contiene lo shortcode [woocommerce_cart] o il blocco woocommerce/cart.
Pagamento: ❌ La pagina non contiene lo shortcode [woocommerce_checkout] o il blocco woocommerce/checkout.
Il mio account: ❌ La pagina non contiene lo shortcode [woocommerce_my_account].
Termini e condizioni: #674 - /termini-e-condizioni-di-vendita/

### Theme ###

Name: hideforprivacy Shop
Version: 2.4.16
Author URL: https://hideforprivacy.it
Child Theme: ✔
Parent Theme Name: The7
Parent Theme Version: 11.10.1.1
Parent Theme Author URL: https://dream-theme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/cart/mini-cart.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-widget-product.php
dt-the7/woocommerce/content-widget-reviews.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php
dt-the7/woocommerce/content-product_cat.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-06 09:43:55 +01:00
Options: ✔
Notes: 126
Onboarding: completed

### Action Scheduler ###

Complete: 1.950
Oldest: 2023-12-05 15:00:30 +0100
Newest: 2024-01-05 14:00:08 +0100

Pending: 5
Oldest: 2024-01-05 14:44:07 +0100
Newest: 2024-01-09 12:40:02 +0100

### Status report information ###

Generated at: 2024-01-05 14:30:37 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Aljullu** [comment]
Thanks for opening this issue, @hardweb-it! Unfortunately, I'm not able to reproduce.

1. I updated a product (ID 46) to have a sale starting today:
![imatge](https://github.com/user-attachments/assets/7ecc0395-cea6-47d3-ab36-f6d3f6436862)
2. I did the same with a variation (ID 66):
![imatge](https://github.com/user-attachments/assets/b2a385f7-80e4-4549-a884-ab901e9ef538)
3. Then, I added this code snippet to my site:
```PHP
add_action( 'init', function() {
	var_dump( wc_get_product_ids_on_sale() );
} );
```
4. This is the output: array(9) { [0]=> int(**46**) [1]=> int(47) [2]=> int(48) [3]=> int(50) [4]=> int(55) [5]=> int(59) [6]=> int(63) [7]=> int(**66**) [8]=> int(43) }.

So it seems to be working as expected on my end. @hardweb-it could you check what's your site's timezone and whether there is a mismatch somewhere? Thanks in advance!

**Comment by imanish003** [comment]
I was also not able to reproduce this issue on my local site as well.

For what it's worth, If product is on sale or not is decided by `onsale` column in `wp_wc_product_meta_lookup` table. If `onsale` is 1 then product is on sale. In code, [here](https://github.com/woocommerce/woocommerce/blob/5ea603a6d9bac7759fc7a869104c1615ee02ac03/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L2293) this is decided.

Although, I noticed that `wc_get_product_ids_on_sale` function isn't returning any product ids for grouped products. For grouped products:
- `onsale` column in `wp_wc_product_meta_lookup` table is not updated, because:
	- `_sale_price` and `_regular_price` meta keys are not saved in the `postmeta` table, but these are required while updating the `onsale` column [here](https://github.com/woocommerce/woocommerce/blob/a59d3f2c6ffadd836ece4efc41b22defc0b00833/plugins/woocommerce/includes/wc-product-functions.php#L1633-L1659).
-  'on sale' status for grouped products is determined at Application level instead of database level. See code [here](https://github.com/woocommerce/woocommerce/blob/a59d3f2c6ffadd836ece4efc41b22defc0b00833/plugins/woocommerce/includes/class-wc-product-grouped.php#L62-L74)

I think we should fix this issue for grouped products. @Aljullu What do you think? Are you able to reproduce this issue?

**Comment by hardweb-it** [comment]
@imanish003 @Aljullu 
I don't know what happened, but starting from WC 9.0.0 the issue disappeared.
Thanks

**Comment by imanish003** [comment]
@hardweb-it I'm glad to hear that the issue has been resolved. This is great news 🙌🏻

Given that the problem is no longer reproducible in the latest version, I think we can consider this issue closed. 

@Aljullu Should we create a new issue for grouped products? 🤔

**Comment by Aljullu** [comment]
> @Aljullu Should we create a new issue for grouped products? 🤔

Good catch, I was able to reproduce as well. Yes, I would open a new issue. It seems related to this one: https://github.com/woocommerce/woocommerce/issues/25808, but I'm not sure if they are exactly the same.

**Comment by imanish003** [comment]
@Aljullu Great! I will create a new issue for grouped products.

> It seems related to this one: [#25808](https://github.com/woocommerce/woocommerce/issues/25808), but I'm not sure if they are exactly the same.

Indeed, this issue appears to be related to the one you mentioned. While they are not identical, likely, addressing one could potentially resolve the other. Nevertheless, creating a separate issue is still valuable to ensure thorough tracking and resolution of both problems 🙂

**Comment by imanish003** [comment]
This issue appears to have been resolved in the latest version of WooCommerce for Variable products. Therefore, I am closing this issue.

**Comment by imanish003** [comment]
New issue for Grouped Products: #51370
