### ISSUE TITLE
8.5 RC notice templates

### ISSUE THREAD

**Issue by JimmyAppelt** [woothemes/woocommerce#43342]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With PR #42692

- There is something wrong with the notice template overriding now, likely due to the implementation and how templates are called in the `Automattic\WooCommerce\Blocks\Domain\Services\Notices` class.
- Is the `woo-gutenberg-products-block` domain name correct here?
- The template versions are still on `-dev`

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

WooCommerce 8.5 RC

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks for reaching out and reporting this issue, @JimmyAppelt. I do see the issues regarding the incorrect textdomain and the `-dev` suffix. As for the first point you mentioned, regarding the `Automattic\WooCommerce\Blocks\Domain\Services\Notices` class, can you provide further information what the issue is and how to reproduce it?

**Comment by JimmyAppelt** [comment]
> Thanks for reaching out and reporting this issue, @JimmyAppelt. I do see the issues regarding the incorrect textdomain and the `-dev` suffix. As for the first point you mentioned, regarding the `Automattic\WooCommerce\Blocks\Domain\Services\Notices` class, can you provide further information what the issue is and how to reproduce it?

@nielslange Template overriding in a theme doesn't work (and also the outdated template versioning does not function correctly in WC Status panel for these notice templates) 🙂 

Disabling `add_filter( 'wc_get_template', [ $this, 'get_notices_template' ], 10, 5 );` in the blocks `Notice` class seems to correct the issue.

**Comment by LordSimal** [comment]
I can confirm that our custom notice templates in the theme are not being used with 8.5 (which were fine previously)
We tried to remove that filter via a hook in the theme but weren't able to do so

**Comment by nielslange** [comment]
@JimmyAppelt and @LordSimal Thanks for adding additional information. I was able to reproduce this issue and addressed it in https://github.com/woocommerce/woocommerce/pull/43506. The fix should be shipped with the next patch release.
