### ISSUE TITLE
Deleting shipping zone method needs its own post-fire hook

### ISSUE THREAD

**Issue by bakkbone** [woothemes/woocommerce#43346]
### Describe the solution you'd like

Referring to [this line](https://github.com/woocommerce/woocommerce/blob/60b3aa8ed85d97569d594da548f2cefcc21686b4/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-shipping-zone-methods-v2-controller.php#L240C15-L240C41), when deleting a shipping zone method via REST, the action `rest_delete_product_review` fires. Thinking this should be updated to something like `rest_delete_shipping_zone_method`?

**Comment by lsinger** [comment]
Pretty sure that's a bug so I'm switching labels to reflect.
