### ISSUE TITLE
[CYS - Woo Express] Theme Showcase, My custom theme active - The Edit button doesn't work

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#43359]
The Edit button appears on hover and is supposed to send users to the editor.

Currently, it doesn't work — Please watch the recording:

https://github.com/woocommerce/woocommerce/assets/98944206/b974c8a3-7576-429e-be70-e9ca2b818adc

Also, please remove that tooltip that shouldn't appear. Thank you 🙏

@nefeline @albarin @gigitux

**Comment by gigitux** [comment]
It seems that https://github.com/Automattic/wp-calypso/pull/86236 fixed this issue. Can we close it? @albarin
