### ISSUE TITLE
Adding 'wp-editor' as a dependency disables payment gateway filtering on Checkout Block page

### ISSUE THREAD

**Issue by Sidsector9** [woothemes/woocommerce#43362]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have a plugin that does the following:

1. Registers its own gateway, let's say X.
2. Renders only X if a particular condition is met (in both shortcode and Block checkout)

However, when we enqueue a script that has `wp-editor` as one of its dependency, then all the gateways are listed.

### Expected behavior

Payment gateways, if filtered should remain filtered in Checkout Block even after adding `wp-editor` to the dependency array of an enqueued script.

### Actual behavior

All gateways are visible.

### Steps to reproduce

1. Enable all gateways.
2. Hide all but one gateway of your choice by referring to [this document](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/filtering-payment-methods.md).
3. Verify in the Checkout block that only the allowed gateway is visible.
4. Create a blank JS file and enqueue it on the frontend, for example:

```php
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_script(
		'yolo-script',
		YOLO_PLUGIN_URL . '/yolo.js',
		[],
		'1.0.0',
		true
	);
} );
```

5. Verify that still the only allowed gateway is visible.
6. Now add `wp-editor` as a dependency to the script enqueued in step (4).
7. Observe that all gateways are visible.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wcblocks.mylocal
Site address (URL): https://wcblocks.mylocal
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 21.17MB
Database Data Size: 14.05MB
Database Index Size: 7.12MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp1895d7actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp1895d7links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp1895d7postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp1895d7posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp1895d7term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp1895d7wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp1895d7wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp1895d7wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp1895d7wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp1895d7wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp1895d7wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp1895d7wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp1895d7wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp1895d7wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp1895d7wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp1895d7woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp1895d7woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp1895d7woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp1895d7woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp1895d7woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp5e3a70actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp5e3a70actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp5e3a70commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp5e3a70links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp5e3a70postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp5e3a70posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp5e3a70term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp5e3a70wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp5e3a70wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp5e3a70wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp5e3a70wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp5e3a70wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp5e3a70wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp5e3a70wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp5e3a70wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp5e3a70wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp5e3a70wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp5e3a70woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp5e3a70woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp5e3a70woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp5e3a70woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp5e3a70woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cactionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wpbf224cactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cactionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224ccommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224ccomments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbf224clinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224coptions: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
wpbf224cpostmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wpbf224cposts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpbf224cterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224ctermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cusermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbf224cwc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpbf224cwc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpbf224cwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbf224cwc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbf224cwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbf224cwc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbf224cwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpbf224cwc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbf224cwc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbf224cwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbf224cwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbf224cwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbf224cwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbf224cwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbf224cwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
bookable_resource: 12
event_ticket: 7
event_ticket_email: 41
page: 12
post: 3
product: 26
product_variation: 7
revision: 77
shop_order_placehold: 12
wc_booking: 9
wp_global_styles: 1
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Sid Gateway: by  –
WooCommerce Bookings: by WooCommerce – 2.0.7
WooCommerce: by Automattic – 8.4.0
WP Crontrol: by John Blackbourn & crontributors – 1.16.1

### Inactive Plugins (16) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.2.2
WooCommerce Bookings Availability: by WooCommerce – 1.2.2
WooCommerce Box Office: by WooCommerce – 1.2.2
WooCommerce Deposits: by WooCommerce – 2.2.3
WooCommerce EU VAT Number: by WooCommerce – 2.8.9
WooCommerce GoCardless Gateway: by WooCommerce – 2.6.0
WooCommerce Payfast Gateway: by WooCommerce – 1.6.0
WooCommerce Pre-Orders: by WooCommerce – 2.0.7
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.66
WooCommerce Product Vendors: by WooCommerce – 2.2.4
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.5
WooCommerce Stripe Gateway: by WooCommerce – 7.8.1
WooCommerce Xero Integration: by WooCommerce – 1.8.2
WP Debugging: by Andy Fragen – 2.11.22
WPvivid Database Snapshots: by wpvivid.com – 0.9.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/siddharth/Sites/wcblocks/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/siddharth/Sites/wcblocks/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/siddharth/Sites/wcblocks/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 71
Onboarding: completed

### Action Scheduler ###

Complete: 253
Oldest: 2023-12-08 12:14:23 +0000
Newest: 2024-01-08 12:05:42 +0000

Failed: 2
Oldest: 2023-11-22 17:44:53 +0000
Newest: 2024-01-07 19:40:10 +0000

Pending: 2
Oldest: 2024-01-08 19:40:10 +0000
Newest: 2024-02-06 19:40:10 +0000

### Status report information ###

Generated at: 2024-01-08 12:13:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Thanks for reporting! Currently filtering is disabled on the editor so that a merchant can see all gateways regardless of the current Cart state, when you load `wp-editor` in frontend, which is a red flag on its own, Checkout would assume it's running in the editor mode and end up removing the filtering logic.

**Comment by Sidsector9** [comment]
That makes sense. I've updated our dependencies and it is working now, thanks @senadir 👍

**Comment by jeffpaul** [comment]
@Sidsector9 are we good to close this out then with that info or is more help needed here?

**Comment by ralucaStan** [comment]
I am going to close this issue considering, seems like things should be fine now.
