### ISSUE TITLE
Orders / checkout: reserve stock setting is ignored in some cases

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#43361]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `create_or_update_draft_order` method in `src/StoreApi/Routes/V1/Checkout.php` sometimes ignores the setting from `woocommerce_hold_stock_minutes`, leading to stock being held even though the setting says otherwise. 

### Expected behavior

The setting is always taken into account. 

### Actual behavior

This `try` block ignores the setting in the non-`POST` case and sets it to 10 minutes: 

https://github.com/woocommerce/woocommerce/blob/c159e8a858b917223eb9760f10339a1df828ee8b/plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php#L397

We should check the setting and not even run the `try` block if it isn't larger than zero. 

### Steps to reproduce

Unclear, so far we have only seen this on WordPress.com infrastructure -- writing a failing test case will be part of solving the issue. Some internal context: p1704225171561689-slack-C7U3Y3VMY

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by hagedigital** [comment]
I finally found someone else having this issue! It's been a nightmare to figure out 

I have a ton of draft orders not reversing, checked over the crons, switched to defaults (storefront + WC only) and I can't pin point the issue 

I'm using .org though

**Comment by kaushikasomaiya** [comment]
Possibly affected ticket 7882629-zen

**Comment by kaushikasomaiya** [comment]
This I believe affects users using cart and checkout blocks since it creates draft orders. I am also wondering if there should be a check that Blank stock hold values should not at all reserve the stock? Or simply pass the blank value to $duration.

**Comment by senadir** [comment]
This has been fixed in https://github.com/woocommerce/woocommerce/pull/49446
