### ISSUE TITLE
Spike: Identify locations or conditions where Woo Payments is recommended

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#43386]
Related P2: pdibGW-2H4-p2

Identify locations or conditions where Woo Payments is recommended in order to control its visibility.l

### Acceptance Criteria

List links to the codebase where Woo Payments is recommended in the Core.

**Comment by moon0326** [comment]
**Note**: I'm reviewing the contents of https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json and noticed that we have notes for Google Ads, PayPal, and Stripe. Depending on our partnerships, it may be necessary to review and remove some notes in addition to Woo Payments notes.


**Note**: We should also consider removing `Recommended payment providers` from the settings page.

![Screen Shot 2024-01-09 at 4 45 32 PM](https://github.com/woocommerce/woocommerce/assets/4723145/b1f90696-bfef-436a-a1ec-fcea53450950)

**Comment by moon0326** [comment]
WIP

Inbox Notification:
Feed: https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json
Filter: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/DataSourcePoller.php#L116
Slugs
- wc-payments-qualitative-feedback
- wcpay-promo-2020-11
- wcpay-promo-2020-12
- woocommerce-payments-august-2022-need-to-update
- woocommerce-payments-august-2022-store-patched
- woopay-beta-merchantrecruitment-04MAY23
- woocommerce-wcpay-march-2023-update-needed
- woopay-beta-merchantrecruitment-update-04MAY23
- woopay-beta-existingmerchants-noaction-27APR23
- woopay-beta-existingmerchants-update-27APR23
- woopay-beta-existingmerchants-update-27APR23
- woopay-beta-merchantrecruitment-short-update-04MAY23
- woopay-beta-merchantrecruitment-short-06MAY23-TESTA
- woopay-beta-merchantrecruitment-short-06MAY23-TESTB
- woopay-beta-merchantrecruitment-short-06MAY23-TESTC
- woopay-beta-merchantrecruitment-short-06MAY23-TESTD
- woopay-beta-merchantrecruitment-short-09MAY23
- woopay-beta-merchantrecruitment-short-update-09MAY23
- woocommerce-WCPayments-June-2023-updated-needed

**Comment by moon0326** [comment]
WooCommerce Payments promotion

This won't show up unless Woo Payments is installed.

**Location**: `WooCommerce -> Settings -> Payments`

**Filter**: It can be disabled by setting `woocommerce_pre_install_woocommerce_payments_promotion_settings` option to `yes` 

**Code**: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php#L66

![Image](https://github.com/woocommerce/woocommerce/assets/4723145/a1667cd8-23ba-4307-9ef9-19715dfe0b28)

**Comment by moon0326** [comment]
WooCommerce Payment Task

**Note**: The task doesn't show up unless WooCommerce Payments plugin is already installed. However, we still render WooCommerce Payments promotion from the regular Payments task.

**Location**: WooCommerce -> Home

**Filter**: We can remove both `woocommerce_payments:with-in-person-payments` and `woocommerce_payments` keys from the spec.

**Code**: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/Init.php#L80

**Screenshot**
![Screen Shot 2024-01-09 at 5 19 34 PM](https://github.com/woocommerce/woocommerce/assets/4723145/b852fc94-16ea-4e65-ae27-d2a6d5b6f6db)

**Comment by moon0326** [comment]
Onboarding Plugins list

**Location**: Onboarding

**API Endpoint**: /wp-json/wc-admin/onboarding/free-extensions

**Filter**: The data comes from a datasource. The same filter we use for the Inbox Notification can be used to control this data.

**Code**: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/DataSourcePoller.php#L116

**Comment by moon0326** [comment]
Woo Payments menu with badge.

This won't show up if we don't install Woo Payments during the provision. 

![Screen Shot 2024-01-10 at 3 29 20 PM](https://github.com/woocommerce/woocommerce/assets/4723145/bce69658-8208-41e2-85d1-cc8dae8c2d4f)

**Comment by adrianduffell** [comment]
Nice work on this @moon0326 ! I'll close it out but please re-open if needed.
