### ISSUE TITLE
Product Collection: Interactivity API - JavaScript and styles of the blocks that are inside the Post Template aren’t loaded if you render a page with “no results”

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#43396]
**Background:**
If the "No Results" page is rendered as the first Product Collection content then after client-side navigation (without refresh) if the products are shown, the javascript scripts and CSS styles are not loaded.

**Goal:**
Find a way to force fetching inner blocks resources.

**Comment by sunyatasattva** [comment]
Hey @kmanijak! This is something that was discussed in here: peCmuQ-1W-p2. In a nutshell, the proposed solutions are:

1. Disabling client-side navigation when rendering the “no results” if it's the first render.
2. Always rendering the “no results” blocks but hiding them from the DOM.

**Comment by kmanijak** [comment]
The issue was created as a problem raised in Query Loop block. But apparently, that's not the case in Product Collection block because of this bug: https://github.com/woocommerce/woocommerce/issues/42075 which eventually serves us as a feature.

Considering these options:

> Disabling client-side navigation when rendering the “no results” if it's the first render.
> Always rendering the “no results” blocks but hiding them from the DOM.

I think simply fetching the product element resources with the Product Collection render is a good alternative:
- requires no additional effort from us at the moment,
- these resources are small (55kB and that includes 25kB Interactivity Product Button script) and we considered https://github.com/woocommerce/woocommerce/issues/42075 a low-priority

![Image](https://github.com/woocommerce/woocommerce/assets/20098064/a49638b0-06c0-48eb-a2ae-8d0a1996a2a9)

Before closing the issue, I'd love to hear your opinion @imanish003. Do you agree with this approach?

If so I'd close this issue and https://github.com/woocommerce/woocommerce/issues/42075.

**Comment by imanish003** [comment]
@kmanijak Good point!

> I think simply fetching the product element resources with the Product Collection render is a good alternative:

I agree! It makes sense to fetch all Product Elements which are there in Product Collection block. I verified that if we remove product elements from Product Collection block then CSS & JS doesn’t load. 

Also, For No results block, there is no CSS (as it doesn’t require any custom styling) & JS file. Therefore, This problem doesn’t exist for No results block. If I am not missing anything, then we can close this issue as well as https://github.com/woocommerce/woocommerce/issues/42075 🙂

**Comment by kmanijak** [comment]
Thanks for confirmation @imanish003 🙏
