### ISSUE TITLE
Product Collection: Add missing PHP Unit tests for recent filters

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#43394]
Add unit tests to Product Collection Editor filters:
- [x] https://github.com/woocommerce/woocommerce/pull/45359
- [x] https://github.com/woocommerce/woocommerce/pull/45365
- [x] https://github.com/woocommerce/woocommerce/pull/45363

**Comment by ObliviousHarmony** [comment]
I _may_ be wrong but I think that "Price Range" filters were added [with the original PR that added unit tests](https://github.com/woocommerce/woocommerce-blocks/pull/10289/).
