### ISSUE TITLE
[DOC-BUG] API (V2 and V3) webhook header correction

### ISSUE THREAD

**Issue by Munch98** [woothemes/woocommerce#43400]
## Link to the Page/Section

> [Link](https://woocommerce.github.io/woocommerce-rest-api-docs/#delivery-payload)

## Description of the Suggestion

> The header "X-WC-Delivery-ID" should be renamed to "X-WC-Webhook-Delivery-ID" in the documentation as the header provided in the API is named "X-WC-Webhook-Delivery-ID"

## Reason for the Suggestion

> The documentation is misleading.

**Comment by lsinger** [comment]
Fixed in https://github.com/woocommerce/woocommerce-rest-api-docs/pull/238. ☺️
