### ISSUE TITLE
The changelog for WooCommerce version 8.5.0 is missing

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#43409]
## Link to the Page/Section

> (https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt)

## Description of the Suggestion

> Hi, I noticed that the update to the latest version of WooCommerce (v 8.5.0) is available but the changelog of this version has not yet been created

**Comment by bigretromike** [comment]
looks like they rollback 8.5.0 because of the fatal errors.

**Comment by ghost** [comment]
I am closing this issue as the changelog for WooCommerce version 8.5.0 has been created; I think WooCommerce 8.5.0 is still in development
