### ISSUE TITLE
Missing "Addresses" Label on My Account Page in Hebrew Translation

### ISSUE THREAD

**Issue by mNemir** [woothemes/woocommerce#43443]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On "My account" page, the addresses label is missing, after checking Loco Translate, the Plural was non existant, after adding it, the label appeared again.

### Expected behavior

The Addresses label should be present.

### Actual behavior

Addresses label on My Account page doesn't show.

### Steps to reproduce

1. Log in
2. Go to /my-account
3. The sidebar menu should have "Addresses" but instead it is blank.

### WordPress Environment

Doesn't matter, but Hebrew must be set as the language. 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
<img width="273" alt="Screenshot 2024-06-06 at 10 48 57" src="https://github.com/woocommerce/woocommerce/assets/1628454/661cf975-da4c-4479-989a-54f8792988a3">

closing, no longer aplicable
