### ISSUE TITLE
WC Block - subscribe function not executing on page load in chrome

### ISSUE THREAD

**Issue by agung2001** [woothemes/woocommerce#43440]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

wp.data.subscribe() function is not executing on the page load
for instance, if we execute this js code 
```javascript
const { subscribe } = wp.data;

subscribe(() => {
  console.log('TEST')
});
```

the code only runs on page load in firefox but not in chrome

### Expected behavior

the subscribe function is executed on page load on whatever the browser

### Actual behavior

the subscribe function is only executed in firefox but not in chrome

### Steps to reproduce

1. Create JS file as follow : 
```javascript
const { subscribe } = wp.data;

subscribe(() => {
  console.log('TEST')
});
```
2. Enqueue the js file using wp_enqueue_script
3. Open cart/checkout block page
4. **PROBLEM** : The subscribe function not executed on page load in chrome

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://acfwp.local
Site address (URL): http://acfwp.local
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 120
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 503.55MB
Database Data Size: 488.22MB
Database Index Size: 15.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 24.55MB + Index: 9.94MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_gift_cards: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_loyalprog_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_virtual_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_fields: Data: 0.02MB + Index: 0.22MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_broadcast: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_bulk_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_contact_note: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_conversions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_engagement_tracking: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_bwfan_engagement_trackingmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_field_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_fields: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_form_feeds: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_import_export: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_link_triggers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_message: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bwfan_templates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cfw_acr_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fk_cart_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 456.03MB + Index: 0.27MB + Engine InnoDB
wp_postmeta: Data: 1.31MB + Index: 0.25MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rs_expiredpoints_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rs_templates_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsgiftvoucher: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rspointexpiry: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsrecordpoints: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sumo_reward_encashing_submitted_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sumo_reward_send_point_submitted_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_action_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_trigger_log_meta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_usermeta: Data: 0.47MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
coupon_template: 3
elementor_library: 1
nav_menu_item: 4
order_form: 1
page: 24
post: 16
product: 41
product_variation: 17
revision: 37
shop_coupon: 36
shop_order: 5
wfacp_checkout: 1
wffn_ty: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.9.1
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 3.5.8.1
Cypress Helper Plugin: by Rymera QAs – 1.1.0
JSON Help Content Editor: by Rymera Web Co – 1.0.0
WooCommerce: by Automattic – 8.4.0

### Inactive Plugins (40) ###

Advanced Gift Cards for WooCommerce: by Rymera Web Co – 1.3.5
Aelia Currency Switcher for WooCommerce: by Aelia – 4.13.12.220704
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.15.230905
Aelia Prices by Country for WooCommerce: by Aelia – 1.12.9.220124
CheckoutWC: by Objectiv – 8.2.14
CheckoutWC Lite: by CheckoutWC – 1.1.4
Elementor: by Elementor.com – 3.15.3
FakerPress: by Gustavo Bordoni – 0.6.1
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.0
FunnelKit Automations: by FunnelKit – 2.5.1
FunnelKit Automations Pro: by FunnelKit – 2.5.0
FunnelKit Cart for WooCommerce: by FunnelKit – 1.1.0
FunnelKit Funnel Builder: by FunnelKit – 2.12.0
FunnelKit Funnel Builder Pro: by FunnelKit – 2.12.0
Invoice Gateway For WooCommerce: by Rymera Web Co – 1.1.1
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.0.5

Loyalty Program for WooCommerce: by Rymera Web Co – 1.8.4
Ocean Extra: by OceanWP – 2.1.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.3.2
Rymera WooCommerce Block Test Plugin: by Agung Sundoro – 0.0.1
Shipping Workshop: by Thomas Roberts and Niels Lange – 1.0
Stripe Payment Gateway for WooCommerce: by FunnelKit – 1.4.1
SUMO Reward Points: by Fantastic Plugins – 28.9.0
Uncanny Automator: by Uncanny Automator
Uncanny Owl – 4.14.0.1

WC Vendors Marketplace: by WC Vendors – 2.4.6
WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free ): by WebToffee – 1.7.8
Woocommerce Blocks Test Extended: by The WordPress Contributors – 0.1.0
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.2.0
WooCommerce Points and Rewards: by WooCommerce – 1.7.32
WooCommerce Subscriptions: by WooCommerce – 4.8.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.17.1
WooCommerce Wholesale Order Form: by Rymera Web Co – 2.1.1.1
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.6.1
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.30.1
WP Mail Logging: by SendLayer – 1.10.5
WPML Media: by OnTheGoSystems – 2.7.1
WPML Multilingual CMS: by OnTheGoSystems – 4.5.13
WPML String Translation: by OnTheGoSystems – 3.2.3
YITH WooCommerce Points and Rewards Premium: by YITH – 3.23.0

### Must Use Plugins (1) ###

Rymera Web Co: by Agung Sundoro – 0.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: advanced_gift_card (advanced_gift_card)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.4.1 (update to version 4.5.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-10 23:41:37 +11:00
Options: ✔
Notes: 127
Onboarding: skipped

### Action Scheduler ###

Complete: 138
Oldest: 2024-01-03 11:45:59 +1100
Newest: 2024-01-10 10:44:37 +1100

Failed: 15
Oldest: 2023-02-15 09:40:17 +1100
Newest: 2023-10-19 09:41:30 +1100

Pending: 2
Oldest: 2024-01-10 14:02:07 +1100
Newest: 2024-02-02 04:00:00 +1100

### Status report information ###

Generated at: 2024-01-10 11:00:13 +11:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @agung2001,

Thanks for the report. I just wanted to verify that I'm understanding the issue correctly, as at first glance this appears to be a bug report about the subscribe method of `@wordpress/data`. Is this an issue that's specific to WooCommerce's use of that package? If so, please let us know and I'll send this off to our developers to look at, and if not could you please [file an issue in core](https://make.wordpress.org/core/handbook/testing/reporting-bugs/)?
