### ISSUE TITLE
[CYS on Core] Switch to TT4 when the `NoAI` flow starts

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#43459]
At least for now, we want to support only TT4 (or another block theme); when the flow starts, we have to switch to this specific theme.

**Comment by nefeline** [comment]
Thanks for creating the issue @gigitux ! For reference, theme switching in the Assembler is controlled via:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/design-with-ai/services.ts#L489

The following PR can be used as a reference for implementation: in practice, we should ensure theme switching is detached and doesn't have AI as a dependency:

https://github.com/woocommerce/woocommerce/pull/40486

Also registering here for future reference that in this first moment, we are using the TT4 theme as the default (same as on WooExpress), with an upcoming investigation for switching to Assembler V2.
