### ISSUE TITLE
[CYS on Core] Create dummy products if the store doesn't have any product

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#43462]
If the store doesn't have any products, we have to create dummy products before loading the assembler.

**Comment by nefeline** [comment]
Thanks for creating the issue @gigitux , additional context for implementation:

Currently, the creation of new products is controlled via `fetch_dummy_products_to_update`, which is invoked on https://github.com/woocommerce/woocommerce/blob/589617a41d93daa069d90b7c27a89d2139d77223/plugins/woocommerce/src/Blocks/AIContent/UpdateProducts.php#L79

In this case, our main goal is to detach the dummy product creation process from the JP connection and the `$token` validation.
