### ISSUE TITLE
Wordpress auth cookies are removed by WooCommerce 8.5.0

### ISSUE THREAD

**Issue by steffans** [woothemes/woocommerce#43463]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WooCommerce 8.5.0 introduced a `WC_Cart_Session::dedupe_cookies()` method which will also dedupe all Wordpress cookies. The method only checks the cookie name and not the path. Now any duplicate cookie is removed even though it uses a different path. See [wp_set_auth_cookie](https://github.com/WordPress/wordpress-develop/blob/eff1a3d24bc5308604992c11effc26ef2a6c6cbf/src/wp-includes/pluggable.php#L1093) function which sets auth cookies with the same name but on different paths.

### Expected behavior

Keep all Wordpress cookies as they are set.

### Actual behavior

All Wordpress cookies with the same name are removed even if they have a different path.

### Steps to reproduce

Login to Wordpress and inspect the cookies.

### WordPress Environment

Wordpress 6.4.2
WooCommerce 8.5.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adam-ainsworth** [comment]
We are seeing the same issue, with the same versions of WP and WC.

~~It seems to only happen on sites where we are running [Bedrock](https://roots.io/bedrock/), which does use a subfolder (/wp) for wp-admin ~~

We've now seen this in a site that runs a standard WP set up, so I think this note can be disregarded

**Comment by matgargano** [comment]
Yes I am seeing the same thing cuzzo

**Comment by dmpinder** [comment]
Having this issue also, on at least 2 Bedrock based sites. Disabling WooCommerce resolves the auth issue. 

This is a pretty serious issue, our clients are faced with either not being able to add or edit any content on their sites, or disable WooCommerce.

Any idea on when it will get patched?

**Comment by michaelbragg** [comment]
If you are using [WPackagist](https://wpackagist.org/), 8.5.0 is still showing as the current version due to the 8.5.0 tag still being present in SVN: https://plugins.svn.wordpress.org/woocommerce/tags/8.5.0/

> We have rolled back the stable tag to version 8.4.0. This temporary measure is to halt further updates to version 8.5.0 until we implement a necessary fix. As a result, the option to update to 8.5.0 will not be available during this period.
– https://developer.woo.com/2024/01/09/woocommerce-8-5-0-released/

This could be the reason why Bedrock sites are affected as they default to loading plugins from WPackagist.

**Comment by adam-ainsworth** [comment]
> Having this issue also, on at least 2 Bedrock based sites. Disabling WooCommerce resolves the auth issue.
> 
> This is a pretty serious issue, our clients are faced with either not being able to add or edit any content on their sites, or disable WooCommerce.
> 
> Any idea on when it will get patched?

We have noticed that you do actually get logged in even though it appears you haven't.

If you go to /wp-admin or /wp/wp-admin after being returned to the login screen, you should be able to get to your dashbaord. We've had less success with customers getting to the /my-account page, but it is at least a workaround for site admins

**Comment by dmpinder** [comment]
> > Having this issue also, on at least 2 Bedrock based sites. Disabling WooCommerce resolves the auth issue.
> > This is a pretty serious issue, our clients are faced with either not being able to add or edit any content on their sites, or disable WooCommerce.
> > Any idea on when it will get patched?
> 
> We have noticed that you do actually get logged in even though it appears you haven't.
> 
> If you go to /wp-admin or /wp/wp-admin after being returned to the login screen, you should be able to get to your dashbaord. We've had less success with customers getting to the /my-account page, but it is at least a workaround for site admins

Thanks

Our main client issue so far has been doing anything else that requires auth, like updating posts, etc. But we're currently rolling back to 8.4.0.

**Comment by alopezari** [comment]
Hi!

We are sorry for the inconveniences caused by this issue. We are currently looking into this and we will release a fix for it as soon as it is ready and properly tested.

Thank you for your patience.
