### ISSUE TITLE
[CYS on Core] Pattern Assembler > Ensure the patterns are displayed and not the default theme homepage

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43486]
Whenever the Pattern Assembler is accessed on core (via: `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub`), we are greeted with the default theme homepage:

<img width="1237" alt="Screenshot 2024-01-10 at 16 23 31" src="https://github.com/woocommerce/woocommerce/assets/15730971/530a8144-79ca-4263-a70d-3c472bb52eeb">

This should be changed, ensuring that patterns with the default content are displayed instead, mimicking the same behavior we have for the AI-offline flow:

<img width="1237" alt="Screenshot 2024-01-10 at 16 38 48" src="https://github.com/woocommerce/woocommerce/assets/15730971/9e371649-0ddc-4a14-ba3f-ab2ae9463091">

The following PR can be used as an inspiration to achieve this goal:

https://github.com/woocommerce/woocommerce/pull/41233

In that case, we had the exact same problem on WooExpress, with the initial screen always displaying the default for TT3 (which used to be the default theme for the CYS before we changed it to TT4 very recently).

**Comment by gigitux** [comment]
This issue has been fixed by https://github.com/woocommerce/woocommerce/pull/43457
