### ISSUE TITLE
[CYS on Core] Update the copy for the Assembler tour - intro

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43485]
Ensure the copy for the assembler tour - intro is conditionally changed depending on the environment:

| Expected Implementation on Core | Current view on WooExpress (should not be changed) |
| -------- | ------- |
| <img width="431" alt="Screenshot 2024-01-10 at 16 18 13" src="https://github.com/woocommerce/woocommerce/assets/15730971/6fe686e3-0d9b-4079-8d48-3e378602c746"> |<img width="346" alt="Screenshot 2024-01-10 at 16 14 52" src="https://github.com/woocommerce/woocommerce/assets/15730971/e533fd47-a4de-403c-adb5-ed25c3bc9195"> |

## How to identify the environment

Thanks to the great work from @gigitux on https://github.com/woocommerce/woocommerce/pull/43368 , we can rely on `FlowType.noAI` to quickly identify the environment.

## Design

Figma: FlPl7fHaGv9mpu8Nfl0joH-fi-702_60193

**Comment by albarin** [comment]
@nefeline Closing this issue because it was already addressed in https://github.com/woocommerce/woocommerce/blame/ec2a3f839fc713336627ac21707db1c64f668e4e/plugins/woocommerce-admin/client/customize-store/assembler-hub/onboarding-tour/index.tsx#L24 by @gigitux
