### ISSUE TITLE
Product type selector and linked products: introduce a new ExPlat experiment in 8.6

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#43483]
**Description:** As we prepare to release the product type selector and linked products, we'll keep the incremental approach and include a new experiment in 8.6 to introduce the features to a small subset of users. 

**Acceptance criteria:**

- [x] Replicate the experiment running in 8.5. In sum, we should expose users who choose one of the following options in the "Add products" task: Physical product, Variable product, Digital product, Grouped product, and External product. 
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.
- [x] Consider that the experiment will be released in the Atomic weekly release a few days before.

**Comment by louwie17** [comment]
Done
