### ISSUE TITLE
[CYS on Core] Update the copy for the Intro Screen sidebar

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43482]
Ensure the copy for the intro screen sidebar is conditionally changed depending on the environment:

| Expected Implementation on Core | Current view on WooExpress (should not be changed) |
| -------- | ------- |
| <img width="342" alt="Screenshot 2024-01-10 at 15 49 17" src="https://github.com/woocommerce/woocommerce/assets/15730971/1f51bbea-4b06-443c-a27b-27269c48b7bf"> | <img width="275" alt="Screenshot 2024-01-10 at 15 49 33" src="https://github.com/woocommerce/woocommerce/assets/15730971/79a54b3a-727d-4c0b-b4d3-176de3d92d5b">|

## How to identify the environment

Thanks to the great work from @gigitux on https://github.com/woocommerce/woocommerce/pull/43368 , we can rely on `FlowType.noAI` to quickly identify the environment.

## Design

Figma: FlPl7fHaGv9mpu8Nfl0joH-fi-702_59946

**Comment by nefeline** [comment]
@verofasulo @lauroraa  could you please take a quick look and confirm the copies are correct? Thanks!

**Comment by lauroraa** [comment]
I just checked Figma, and this looks correct!
