### ISSUE TITLE
Synchronize Appearance > Customize > WooCommerce > Checkout Settings with Checkout Blocks Settings

### ISSUE THREAD

**Issue by EjayhanFernandes** [woothemes/woocommerce#43496]
### Describe the solution you'd like

The settings under `Appearance > Customize > WooCommerce > Checkout` have no effect on Checkout blocks. Checkout blocks has its own configurations. Ideally, both settings should synchronize

- Appearance > Customize > WooCommerce > Checkout
![T3cTPe.png](https://github.com/woocommerce/woocommerce/assets/81605775/3ee0a6fd-dc4c-411d-bdd2-d897f80bd33e)
- Checkout block:
![ZfqFtK.png](https://github.com/woocommerce/woocommerce/assets/81605775/f9527b48-ae0c-43c3-9bbb-629ea23a234d)

### Describe alternatives you've considered

Alternatively, we can add a notice under `Appearance > Customize > WooCommerce > Checkout`, indicating something like:

>_Checkout Block detected; configurations here don’t affect the checkout block. The checkout block has its own settings. Learn more here._

### Additional context

7567647-zd-a8c

**Comment by tarunvijwani** [comment]
@EjayhanFernandes Thank you for letting us know about the issue. I was able to reproduce it and have moved the ticket to our backlog for future development.

**Comment by tarunvijwani** [comment]
Internal discussion: p1705064975370399-slack-C8X6Q7XQU

**Comment by ralucaStan** [comment]
Closing based on https://github.com/woocommerce/woocommerce/issues/44120
