### ISSUE TITLE
[CYS on Core] Pattern Assembler - Update the copy for the "choose fonts" section

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43491]
Similar to the work made with the AI-offline flow on WooExpress, we need to make sure the copy for the "choose fonts" section is also conditionally changed depending on the environment:

| Expected Implementation on Core | Current view on WooExpress (should not be changed) |
| -------- | ------- |
| <img width="380" alt="Screenshot 2024-01-10 at 23 13 22" src="https://github.com/woocommerce/woocommerce/assets/15730971/dcf4efeb-cff6-421d-99d3-3f97c6fe51ef"> |<img width="314" alt="Screenshot 2024-01-10 at 23 13 43" src="https://github.com/woocommerce/woocommerce/assets/15730971/6d899b23-9d79-41ef-942f-902ec7187930">|

## How to identify the environment

Thanks to the great work from @gigitux on https://github.com/woocommerce/woocommerce/pull/43368 , we can rely on `FlowType.noAI` to quickly identify the environment.

## Design

Figma: FlPl7fHaGv9mpu8Nfl0joH-fi-702_61791

**Comment by albarin** [comment]
@nefeline Closing this one as it was already implemented by @gigitux, see https://github.com/woocommerce/woocommerce/blob/145359740030bf7ef5c85c55637f54450e93da8d/plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-typography.tsx#L24
