### ISSUE TITLE
Name order not respected by the address card block on the checkout page

### ISSUE THREAD

**Issue by passatgt** [woothemes/woocommerce#43500]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In Hungary and Japan, we use a different name order. This is already handled here:

https://github.com/woocommerce/woocommerce/blob/c487c84778b02946ce811f89368f369d282f1d3e/plugins/woocommerce/includes/class-wc-countries.php#L574

And here:

https://github.com/woocommerce/woocommerce/blob/c487c84778b02946ce811f89368f369d282f1d3e/plugins/woocommerce/includes/class-wc-countries.php#L1154-L1161

(same with Japan).

### Expected behavior

Based on this, the name on the address card should be reversed too if the customer has a hungarian or japanese address.

### Actual behavior

However at the moment this name order is only respected on the checkout form, non on the address card.

On the form the order is correct:
<img width="654" alt="Screenshot 2024-01-11 at 10 54 48" src="https://github.com/woocommerce/woocommerce/assets/43415/144d3872-0105-4c2e-9008-888b799b1e8d">

On the address card, the name is reversed:
<img width="649" alt="Screenshot 2024-01-11 at 10 55 11" src="https://github.com/woocommerce/woocommerce/assets/43415/7e9602b7-051c-4742-a240-fbad0445140f">

Because it is hard coded to a fixed format:

https://github.com/woocommerce/woocommerce/blob/c487c84778b02946ce811f89368f369d282f1d3e/plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx#L32

### Steps to reproduce

1. Go to the checkout page and select Hungary as the billing country
2. Notice that the first name and last name fields will switch order automatically
3. Refresh the page to see the address card and the name will be in the wrong order

### WordPress Environment

_Not relevant_

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by frosso** [comment]
I was also going to report the same issue - the same is also valid for Italy: 
![Screenshot 2024-01-12 at 4 39 09 PM](https://github.com/woocommerce/woocommerce/assets/273592/a8f947d4-a916-4b8a-89cf-352641946a5f)

Also worth mentioning that the "company" field is not displayed for any of the countries, despite it being entered
![Screenshot 2024-01-12 at 4 40 31 PM](https://github.com/woocommerce/woocommerce/assets/273592/5c09732b-c446-4c94-9607-4dc4b6df7ea0)

**Comment by tarunvijwani** [comment]
@passatgt Thank you for letting us know about the issue. I was able to reproduce it and have moved the ticket to our backlog for future development.

**Comment by ralucaStan** [comment]
I'm adding this as unplanned in the 2nd Cycle
