### ISSUE TITLE
cart_item data changes do not persist past place order on Cart/Checkout Blocks, but do on Shortcode experience

### ISSUE THREAD

**Issue by ninetyninew** [woothemes/woocommerce#43516]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Summary of issue

There appears to be an issue that cart/checkout blocks take some cart item data changes into account only up until the point of clicking the place order button, then forgets about it.

We have tested running a custom function off of both the `woocommerce_before_calculate_totals` and `woocommerce_cart_updated` action hooks which loops through cart items and updates data on them.

In this example we are overriding the `tax_status` of all cart items from what they are set to by default (in our scenario this is taxable) to none, and expecting a placed order to not have tax applied.

### Function code

```
function test_tax_status_override() {

    $cart = WC()->cart;

    if ( !empty( $cart ) ) {

        if ( isset( $cart->cart_contents ) ) {

            if ( !empty( $cart->cart_contents ) ) {

                foreach ( $cart->cart_contents as $cart_content_key => $cart_content_value ) {

			$cart_content_value['data']->set_tax_status( 'none' );

                }

            }

        }

    }

}
add_action( 'woocommerce_before_calculate_totals', 'test_tax_status_override', 20 );
add_action( 'woocommerce_cart_updated', 'test_tax_status_override', 20 );
```

### On the block cart/checkout experience

**1. No tax shown on cart (good!)**

<img width="1297" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/6440c50a-0225-4973-8709-db4981b96198">

**2. No tax shown on checkout (good!)**

<img width="1276" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/13a981c1-232e-4114-bcb5-8d5ba95d8c16">

**3. Tax shown on order completion (bad!)**

<img width="1058" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/334f7fa7-7b64-4680-a8d9-74e6246b0f1e">

**4. Tax included on order (bad!)**

<img width="1525" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/56189408-2503-46ad-ac0a-e3e937b641c9">

### Compared to the shortcode cart/checkout experience

**1. No tax shown on cart (good!)**

<img width="1275" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/5cbf8cff-9fc1-4cad-ba5c-c2d7857c4908">

**2. No tax shown on checkout (good!)**

<img width="1262" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/2b1529dd-afc6-445c-b159-804be2abdfc9">

**3. No tax shown on order completion (good!)**

<img width="1061" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/3d5988c0-2f57-401c-bca9-e28a20312264">

**4. No tax included on order (good!)**

<img width="1523" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/f79f6386-cb26-4f5d-99a5-3acca42d32f5">

### Expected behavior

Changes to cart item data persist on cart/checkout blocks during cart/checkout and through to order confirmation and the final order data.

### Actual behavior

Cart/checkout blocks take cart item data changes into account up until the point of place order, then the changes don't persist through to order confirmation and the order itself.

### Steps to reproduce

1. Create a new WP/WC install
2. Enable taxes and set a tax rate, e.g. 20% on all
3. Import sample products, ensure the tax status for test product set to taxable
4. Add the function code provided in this issue
5. Enable cart/checkout block experience
6. Reproduce issue based on description
7. Enable cart/checkout shortcode experience
8. Reproduce no issue for shortcode based cart/checkout based on description

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://powerfulplastic.s3-tastewp.com
Site address (URL): https://powerfulplastic.s3-tastewp.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: TasteWP-S3 Official/3.0.0
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 100
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.32-0ubuntu0.20.04.2
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 5.11MB
Database Data Size: 3.35MB
Database Index Size: 1.76MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 19
product_variation: 7
revision: 2
shop_order_placehold: 3
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Code Snippets: by Code Snippets Pro – 3.6.2
WooCommerce: by Automattic – 8.4.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /s3-powerfulplastic/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/s3-powerfulplastic/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/s3-powerfulplastic/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-12 09:14:50 +00:00
Options: ✔
Notes: 66
Onboarding: skipped

### Action Scheduler ###

Complete: 57
Oldest: 2024-01-08 09:15:56 +0000
Newest: 2024-01-11 14:09:16 +0000

Failed: 1
Oldest: 2024-01-08 09:15:56 +0000
Newest: 2024-01-08 09:15:56 +0000

Pending: 1
Oldest: 2024-01-12 13:51:03 +0000
Newest: 2024-01-12 13:51:03 +0000

### Status report information ###

Generated at: 2024-01-11 14:17:41 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@ninetyninew Thank you for letting us know about the issue. I was able to reproduce it and have moved the ticket to our backlog for future development.

**Comment by ninetyninew** [comment]
Just to mention, I now think this is purely in relation to set stock status, rather than other cart item data, and it may be related to: https://github.com/woocommerce/woocommerce/issues/44356 (in regards to how the tax status isn't being got correctly there)

**Comment by senadir** [comment]
Hey @ninetyninew I'm not sure if you solved this yet or not, but Checkout block would use the order's calculate_totals once you place the order, hence why the data you're seeing is wrong, I suggest you try and filter into `woocommerce_order_before_calculate_totals` and `woocommerce_order_after_calculate_totals`.

I did filter `woocommerce_order_before_calculate_totals` and tried to change the tax status, but that didn't work well for me, it's most likely that you need to interact directly with the saved line item or hook slightly earlier the tax status is correct, something like `woocommerce_order_item_product`.
