### ISSUE TITLE
Output select field labels rather than values in order confirmation page and emails

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#43525]
When rendering a custom field of type `select` it requires a `value` and `label` the `label` is what the user sees when using the input.

We should ensure the label is displayed on order confirmation emails and on the order confirmation page to avoid showing IDs which may not make sense to the end user (e.g.if a select box is shown with ID numbers for each option, the shopper doesn't care they chose an option with ID 5, they care that they chose the option "Don't leave with a neighbour".

**Comment by mikejolley** [comment]
This is taken care of.
