### ISSUE TITLE
Remove the Product Filters block

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#43545]
Currently, we wrap all filter blocks in a wrapper block called `Product Filters` (`Collection Filters` previously), there are serveral reason why we do it:
- Initially, we tried to enhance the existing React filter blocks, which use Store API to get filter data.
- We want to improve the performance of the filter blocks, so we don't want to make multiple requests. We create the `Product Filters` block to make a single aggregated request to Store API there and then pass the result down to inner filter blocks.
- We need to convert the WP_Query query variables to Store API `products` params in order to use Store API, that's a complex logic and the `Product Filters` block is the good place to execute that just one time.

But, the block doesn't make a lot of sense now:
- We're no longer use Store API anymore, instead, we have `QueryFilters` class to handle the filter data, which can be used directly without making internal REST request.
- We're no longer need to convert the query param because we now use `WP_Query` variables directly.

So, we can make get the filter data in each filter block with ease and the `Product Filters` block with the following operations becomes unnecessary:
- To make aggregated request in `Product Filters`, each filter block need to defines a default attribute, and `Product Filters` collect those attribute of its inner blocks to decide which data is needed.
- After getting the data, we pass it to inner filter blocks through context.
- In each inner block, we get the filter data from the context and use the relevant part.

**Comment by nerrad** [comment]
Are there any implications here for hiding inner blocks if there are no results for a given filter?

**Comment by dinhtungdu** [comment]
> Are there any implications here for hiding inner blocks if there are no results for a given filter?

@nerrad This is under #43544 scope and will be implemented there.

**Comment by dinhtungdu** [comment]
Closed by #43688
