### ISSUE TITLE
Filter Wrapper block

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#43544]
We need to create a `Filter Wrapper` block to fills the needs for:
- Hiding block heading when there is no filter available.
- Handling more complex layout like horizontal filters, where we need to hide not only heading, but also the dropdown containing the filter. Having a dedicate wrapper is most flexible solution.

Previously, we solves the heading issue in #42055, but having the heading as inner block of new filter blocks make users confused as the order of block tree doesn't match with actual block order. That solution is also limit us from implementing complex layout.

We was afraid of the complexity of the block tree but in practice, we want to drive user to use filter blocks through patterns instead of manually adding blocks, so one more block won't add much overhead to users.

Thank you so much @nerrad and @jarekmorawski for your feedback on this.

**Comment by samueljseay** [comment]
Just listing some things that we need to check still work as part of this, so they don't slip through the cracks

- [ ] Ensure that block migration still works
- [ ] Support headers not showing when there is nothing to filter
- [ ] Ensure to update the e2e tests
