### ISSUE TITLE
Translate block content

### ISSUE THREAD

**Issue by rogmauri** [woothemes/woocommerce#43556]
### Discussed in https://github.com/woocommerce/woocommerce/discussions/43542

<div type='discussions-op-text'>

<sup>Originally posted by **rogmauri** January 11, 2024</sup>
How to translate the content of blocks, such as titles, subtitles and details into Portuguese (Brazil).
![Capturar](https://github.com/woocommerce/woocommerce/assets/42703799/7b2e13ca-23e4-4593-89c7-8166c24f25be)
</div>

**Comment by rrennick** [comment]
Closing as a duplicate. I responded in the discussion thread.
