### ISSUE TITLE
[Enhancement]: Allow applying coupon to an empty order

### ISSUE THREAD

**Issue by samiuelson** [woothemes/woocommerce#43554]
### Describe the solution you'd like

Coupons cannot be applied to an empty order and to an order containing custom amounts only (fees). We want the possibility to apply a coupon as a first thing when creating an order and to apply a coupon to an order containing fees.

### Describe alternatives you've considered
Currently, we're disabling the "add coupon" button in the mobile app in case there are no products in the order. However, being able to allow entering coupons all the time would be a useful possibility.

### Additional context

The enhancement is requested for the Woo mobile apps, that focus on supporting in-person sales. Allowing merchants to enter a coupon first, before selecting products or applying coupons to custom amounts, would greatly enhance sales in physical stores. I imagine the web-based checkout could also benefit from this extra flexibility.

**Comment by Konamiman** [comment]
Hi @samiuelson, I understand that you are requesting an enhancement for the Woo mobile apps, right? May I ask why you have created the issue in the WooCommerce core repository, as opposed to the repositories of the mobile apps? I might be missing some context here.

**Comment by samiuelson** [comment]
Hi, @Konamiman 👋🏼 

To give you more context, I'm mobile wrangler in [woocommerce-android](https://github.com/woocommerce/woocommerce-android), and Woo mobile apps rely on the WooCommerce core as their backend.

> Why you have created the issue in the WooCommerce core repository, as opposed to the repositories of the mobile apps?

The described issue appears to be a backend (woocommerce core) behavior – when coupon code is sent in the [`order update`](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order) REST call, the backend ignores the coupon in case there are no items in the order. We can't work around this behavior in mobile apps.

#### Why this is important for merchants using mobile apps? 
We allow creating orders containing "custom amounts" (fees), optionally without products, and collecting payments for them in the mobile apps.

Let me know if this sheds more light on the context. Let me know if you need more information!

**Comment by Konamiman** [comment]
@samiuelson Ok, it's clear now, thanks. Yes, that's definitely something to fix in Woo core.

**Comment by coreymckrill** [comment]
@samiuelson I was just digging into this a bit, and I was able to create an order via `wc/v3/orders` with `auto-draft` status that had nothing but a coupon code. It successfully returned an order object that still contained a `coupon_lines` property with the coupon code I had submitted. I also tried creating a completely empty order, and then updating the order with a coupon code, but nothing else, and that also worked. Interestingly, though, if I then add some other line item to the order (e.g. a product), the order total reflects the price of the item, but does not include the discount from the coupon code. 🤔 So it looks like we might need a way to force a recalculation of the order totals, unless there's already a way to do this that I've missed...

**Comment by coreymckrill** [comment]
Ok, I figured out that if you keep the `coupon_lines` item in subsequent requests while building the order, it will correctly recalculate the order total (while still only "using" the coupon once). We could also potentially update the behavior of the update order endpoint so that it will always recalculate the coupons on an order regardless of whether you include `coupon_lines` in the request, but this would have the potential to cause unintended side effects...

@samiuelson what do you think?

**Comment by samiuelson** [comment]
Thanks for researching and testing the endpoint, @coreymckrill. It seems we could work around the current endpoint's behavior by adding the coupon manually to order update requests. 

I think the answer – whether to update the current behavior on the backend or not – should focus on what are the merchant's expectations for this feature. I would opt for persisting the coupon in the order rather than making applying a coupon a one-shot action. Looking at this from the IPP/POS perspective, I imagine the merchant adds an item to the order, applies a coupon (e.g. 10% total discount), and then possibly wants to add more items to that order. AFAICS, coupons work the same way in web stores – a customer can add a coupon to the cart first, and a discount is recalculated automatically when they add items to the cart 🤔 

Let me know what you think or if I'm missing something!

**Comment by coreymckrill** [comment]
I _think_ we're on the same page here, but just to reiterate, if you're building an order in the mobile app, and you add a coupon (regardless of whether it was added first or not), then if you keep including the coupon in subsequent requests that further change the order, the value of the coupon will keep getting recalculated. Sort of like how if you add a product to an order, and then in a separate request you want to add another product, you have to include both products in the request to ensure the the second product doesn't replace the first product.

It seems like this approach solves the issue of being able to apply a coupon to an empty order, so I'm going to close this, but if you think there's more here to discuss, or I've misunderstood something, please reopen!
