### ISSUE TITLE
Shipping Rates not Allowing Formulas to Adjust for Quantity

### ISSUE THREAD

**Issue by SSOLIVIA** [woothemes/woocommerce#43577]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating flat rate shipping rates the platform is not accepting formulas. I am trying to create a flat rate that varies based on quantity. This was working a month ago and all the sudden has stopped resulting in my company losing on shipping costs when people are addding more than 1 quantity of an item to cart since the shipping is not cumulative. The formula $19.99 * [qty] was previously used and has been tested and each time I save and check again, this defaults out to just $19.99 and does not account for the formula.

### Expected behavior

I expected that the formulas inputted would save properly resulting in shipping then applied to each quantity of the item that is added to cart. 

### Actual behavior

The formula is not being accepted and shipping based on quantities added to cart is not occurring resulting in a loss of money to shipping costs when multiple items of the same product are added to cart since the shipping is not cumulative.

### Steps to reproduce

https://github.com/woocommerce/woocommerce/assets/156458524/bafc86a1-7cd1-466f-8593-eaec96eceaaf

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://thesportscreen.com
Site address (URL): https://thesportscreen.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: kfy_
Total Database Size: 239.05MB
Database Data Size: 186.96MB
Database Index Size: 52.09MB
kfy_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
kfy_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
kfy_woocommerce_order_items: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
kfy_woocommerce_order_itemmeta: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
kfy_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
kfy_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_acfw_virtual_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_actionscheduler_actions: Data: 6.02MB + Index: 8.05MB + Engine InnoDB
kfy_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_actionscheduler_logs: Data: 5.02MB + Index: 4.53MB + Engine InnoDB
kfy_aioseo_cache: Data: 0.22MB + Index: 0.03MB + Engine InnoDB
kfy_aioseo_notifications: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
kfy_aioseo_posts: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
kfy_commentmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
kfy_comments: Data: 5.52MB + Index: 8.03MB + Engine InnoDB
kfy_cr_local_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_db7_forms: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
kfy_eopa_global_rule_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_eopa_poptions_table: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_eopa_rowoption_table: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_eopa_temp_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_fusion_form_entries: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
kfy_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
kfy_gla_merchant_issues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
kfy_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_ifso_daily_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_ifso_local_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
kfy_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
kfy_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
kfy_options: Data: 34.41MB + Index: 2.11MB + Engine InnoDB
kfy_postmeta: Data: 17.50MB + Index: 17.06MB + Engine InnoDB
kfy_posts: Data: 101.11MB + Index: 1.08MB + Engine InnoDB
kfy_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_reviewx_criterias: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_reviewx_import_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_reviewx_process_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_reviewx_reminder_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_sbi_feed_caches: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
kfy_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_sbi_instagram_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
kfy_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_snp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_snp_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
kfy_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
kfy_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
kfy_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
kfy_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
kfy_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
kfy_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
kfy_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wc_customer_lookup: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
kfy_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
kfy_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
kfy_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_wc_order_product_lookup: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
kfy_wc_order_stats: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
kfy_wc_order_tax_lookup: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
kfy_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
kfy_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
kfy_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
kfy_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
kfy_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_admin_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_image_overlays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_point_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wpr_rocket_cache: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
kfy_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
kfy_wt_iew_action_history: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
kfy_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
kfy_wt_sc_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_yoast_indexable: Data: 0.27MB + Index: 0.25MB + Engine InnoDB
kfy_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
kfy_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kfy_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
kfy_yoast_seo_links: Data: 0.13MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 323
elementor_library: 1
fusion_element: 127
fusion_form: 5
fusion_icons: 1
fusion_tb_layout: 18
fusion_tb_section: 24
jb_store_css: 10
nav_menu_item: 15
page: 55
post: 6
product: 69
product_variation: 30
revision: 2027
shop_coupon: 46
shop_order: 4864
shop_order_refund: 79
slide: 2
wcs_ruleset: 3
wpcode: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.9.2
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 3.5.8.1
Afterpay Gateway for WooCommerce: by Afterpay – 3.7.3
All in One SEO: by All in One SEO Team – 4.5.3.1
ClickShip: by ClickShip – 1.0.1
Conditional Shipping for WooCommerce: by Lauri Karisola / WP Trio – 3.1.2
Customer Reviews for WooCommerce: by CusRev – 5.38.10
Duplicate Page: by mndpsingh287 – 4.5.3
GTM4WP: by Thomas Geiger – 1.19.1
301 Redirects: by WebFactory Ltd – 2.73
Facebook for WooCommerce: by Facebook – 3.1.9
Flexible Product Fields: by WP Desk – 2.3.14
Avada Builder: by ThemeFusion – 3.11.3
Avada Core: by ThemeFusion – 5.11.3
Avada Custom Branding: by ThemeFusion – 1.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.23.1
Google Listings and Ads: by WooCommerce – 2.5.15
Site Kit by Google: by Google – 1.116.0
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.3.1
Smash Balloon Instagram Feed: by Smash Balloon – 6.2.7
Jetpack Boost: by Automattic - Jetpack Site Speed team – 2.2.1
Jetpack: by Automattic – 13.0
Klaviyo: by Klaviyo
Inc. – 3.3.3

HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 10.2.17
LiteSpeed Cache: by LiteSpeed Technologies – 6.0.0.1
OptinMonster: by OptinMonster Popup Builder Team – 2.15.3
Order Export & Order Import for WooCommerce: by WebToffee – 2.4.6
Password Protected: by Password Protected – 2.6.6
Slider Revolution: by ThemePunch – 6.6.18
Tawk.to Live Chat: by Tawkto – 0.8.2
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.0
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.2.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.5
WooCommerce Checkout Manager: by QuadLayers – 7.4.2
WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.9
WooCommerce: by Automattic – 8.4.0

### Inactive Plugins (15) ###

Conditional Payments for WooCommerce: by Lauri Karisola / WP Trio – 3.0.2
Contact Form 7: by Takayuki Miyoshi – 5.8.6
Contact Form 7 Captcha: by 247wd – 0.1.2
Contact Form CFDB7: by Arshid – 1.2.6.7
If-So: by If So Plugin – 1.7.1
If-So Geolocation: by If So Plugin – 1.3
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: by Retainful – 2.6.26
SiteGround Central: by SiteGround – 2.0.9
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.5.2
Speed Optimizer: by SiteGround – 7.4.6
Woocommerce Advanced Ordernumbers: by Open Tools – 1.4.4
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WPCode Lite: by WPCode – 2.1.7
WPC Product Bundles for WooCommerce: by WPClever – 7.3.5
WP File Manager: by mndpsingh287 – 7.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #17 - /shop-2/
Cart: #18 - /cart-2/
Checkout: #19 - /checkout-2/
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 7.11.3
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-12 22:31:06 +00:00
Options: ✔
Notes: 113
Onboarding: completed

### Action Scheduler ###

Complete: 3,420
Oldest: 2023-12-12 17:30:18 +0000
Newest: 2024-01-12 17:21:20 +0000

Failed: 15
Oldest: 2023-04-01 22:32:10 +0000
Newest: 2024-01-12 17:07:59 +0000

Pending: 7
Oldest: 2024-01-12 17:36:20 +0000
Newest: 2024-01-18 22:08:28 +0000

### Status report information ###

Generated at: 2024-01-12 17:23:55 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
This was fixed in WooCommerce 8.5 which will be released today.

**Comment by SSOLIVIA** [comment]
Hi there,When is this being released today? We do not have any updates showing on our end. Thanks,Olivia On Jan 15, 2024, at 11:45, Seghir Nadir ***@***.***> wrote:﻿
Closed #43577 as completed.

**Comment by senadir** [comment]
Hey @SSOLIVIA 
It's still not out yet, as the team is still testing it and making sure all bugs are solved

https://developer.woo.com/2024/01/11/update-on-the-woocommerce-8-5-known-issue/
