### ISSUE TITLE
[CYS] Add a transient with an expiration of 50 seconds whenever the CYS flow is triggered

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43579]
In order to prevent simultaneous requests for generating AI content for the exact same store, let's make sure a transient is set whenever the CYS flow is initiated with an expiration of ~50 seconds (which is the average amount of time that the onboarding flow takes to conclude AI content generation). 

Next, we should check for the existence of this transient before allowing the user to proceed with the AI content generation on their store: if the transient exists, we should display an error message: for now, we could stick with the default error message we already have in place, but perhaps it would be helpful to come up with a dedicated copy instead: 

@lauroraa could you help us with coming up with a dedicated error message to be displayed whenever the user tries to generate AI content for their site on multiple different windows in parallel? Maybe something like: "You already have an AI content generation in progress for your store, please wait for a few seconds and try again later."

**Comment by lauroraa** [comment]
Thanks for checking @nefeline! 

Just a minor tweak to your suggested copy from me:

"Our AI tool is already generating content for your store! Please try again later."

**Comment by gigitux** [comment]
I'm going to close this issue, given that the AI flow isn't a focus anymore.
