### ISSUE TITLE
Can't reprint shipping label

### ISSUE THREAD

**Issue by fayena** [woothemes/woocommerce#43598]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Bought shipping label and received email receipt.    Printed, but the printer errored out, and I'd already closed the label window.    It was a first class label, so no tracking.   
![Screenshot 2024-01-13 150937](https://github.com/woocommerce/woocommerce/assets/3398711/f5265a96-44ea-4fa8-a0b8-fc0ed8a53545)
![Screenshot 2024-01-13 150957](https://github.com/woocommerce/woocommerce/assets/3398711/9bd56343-ba94-4af8-9e91-8caea7f1ff0a)
The theme is twenty twenty-four, and I tried both firefox and chrome

### Expected behavior

There should be a way to reprint shipping labels incase of an error.   

### Actual behavior

No way to reprint shipping label

### Steps to reproduce

1. buy first class shipping label
2. need to reprint it
3. no way to reprint it

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://choctawcreations.com
Site address (URL): https://choctawcreations.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.2.14
PHP Post Max Size: 25 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.35-0ubuntu0.20.04.1
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 12.01MB
Database Data Size: 9.23MB
Database Index Size: 2.78MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.44MB + Index: 0.38MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
wp_alp_pickup_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.16MB + Engine InnoDB
wp_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_post_smtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.38MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 1.45MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 81
page: 13
post: 3
product: 49
revision: 88
shop_coupon: 1
shop_order_placehold: 1
wp_global_styles: 2
wp_navigation: 5
wp_template: 2
wp_template_part: 4
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Advanced Local Pickup for WooCommerce: by zorem – 1.6.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.6
Image Watermark: by dFactory – 1.7.3
Jetpack: by Automattic – 13.0
Redirection: by John Godley – 5.4.1
MWW Scheduled Post Trigger: by Moss Web Works – 3.2
Simple Lightbox: by Archetyped – 2.9.3
TikTok: by TikTok – 1.2.3
USPS Simple Shipping for Woocommerce: by dangoodman – 1.10.1
WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooPayments: by Automattic – 7.0.0
WooCommerce PayPal Payments: by WooCommerce – 2.4.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.6
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce: by Automattic – 8.4.0
WP Mail SMTP: by WP Mail SMTP – 3.11.0
WPForms Lite: by WPForms – 1.8.5.4

### Inactive Plugins (11) ###

Creative Mail by Newfold Digital: by Newfold Digital – 1.6.7
Cryout Serious Slider: by Cryout Creations – 1.2.4
Google Listings and Ads: by WooCommerce – 2.5.15
Mailchimp for WooCommerce: by Mailchimp – 3.5
MailPoet: by MailPoet – 4.41.2
Pinterest for WooCommerce: by WooCommerce – 1.3.20
Sales Tax Reports For WooCommerce: by mystyleplatform – 1.0.6
Spam Master: by TechGasp – 7.2.4
WooCommerce Accounting Report: by BjornTech – 3.0.2
WooCommerce Square: by WooCommerce – 4.4.0
Yoast SEO: by Team Yoast – 21.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /usr/share/nginx/choctawcreations/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/usr/share/nginx/choctawcreations/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/usr/share/nginx/choctawcreations/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### WooPayments ###

Version: 7.0.0
Connected to WPCOM: Yes
WPCOM Blog ID: 225701650
Account ID: acct_1OB4mMFsqpr3DS4x
Payment Gateway: ❌ Needs setup
Test Mode: Disabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-13 22:27:12 -06:00
Options: ✔
Notes: 76
Onboarding: completed

### Action Scheduler ###

Complete: 620
Oldest: 2023-12-13 16:15:01 -0600
Newest: 2024-01-13 15:09:53 -0600

Failed: 366
Oldest: 2023-11-10 19:05:48 -0600
Newest: 2024-01-13 14:27:56 -0600

Pending: 10
Oldest: 2024-01-13 15:27:56 -0600
Newest: 2024-01-19 21:14:15 -0600

### Status report information ###

Generated at: 2024-01-13 15:17:29 -06:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Hi @fayena, apologies for the late reply.

Label printing functionality is not part of WooCommerce but rather through extensions. If you are using WooCommerce Shipping & Tax for your label printing, please [contact WooCommerce support](https://woocommerce.com/contact-us/) for assistance in resolving your issue.
