### ISSUE TITLE
Product Gallery: Incorrect image gets loaded in the pop-up when triggered the first time

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#43610]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On first load if you scroll through to the next gallery image (once or more) and click on the Large Image it will load up the **first/Product Image** image in the Pop-up.

When you then close the Pop-up and repeat the same actions it will load up the correct image (the same one as clicked).

![Izr04iJBrt](https://github.com/woocommerce/woocommerce/assets/905781/52984d26-0899-40be-bd83-a56376450db3)

### Expected behavior

The Pop-up should always load the selected image.

### Actual behavior

The image being loaded in the Pop-up varies.

### Steps to reproduce

1. Go to Appearance > Editor > Templates > Single Product (clear customizations)
2. Click on the editor and you should see "Transform into blocks" action button.
3. Add the Product Gallery block.
4. Make sure the `Open pop-up when clicked` setting is enabled.
5. Make sure the `Next/Previous Buttons` are **not** set to `Off`.
6. Open a Product that has multiple images in its gallery.
7. Scroll through to the next gallery image (once or more) and click on the Large Image it will load up the **first/Product Image** image in the Pop-up.
8. When you then close the Pop-up and repeat the same actions it will load up the correct image (the same one as clicked).

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thealexandrelara** [comment]
Hey Danny, thank you for reporting this issue. I was trying to reproduce it on my end but unfortunately I wasn't able to. Which WordPress version and theme are you using?

https://github.com/woocommerce/woocommerce/assets/20469356/f6ba312a-a68b-4c2d-aa2b-2f7def9f1f0c

**Comment by thealexandrelara** [comment]
I'm closing this issue as I haven't been able to reproduce it. It's possible a fix was introduced after the issue was reported 🤔 . Please feel free to reopen it if it occurs again.
