### ISSUE TITLE
[Enhancement]: Accessibility: Add aria-label clarifying view order link purpose in orders table

### ISSUE THREAD

**Issue by amberhinds** [woothemes/woocommerce#43627]
### Describe the solution you'd like

The orders table contains a linked order number that goes to the view order page for that number.
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/orders.php#L48

This it is unclear where this link goes and it could be made more clear for screen reader users if there was an aria-label. For example:
`<a href="https://shop.equalizedigital.com/my-account/view-order/518/" aria-label="View order number 518.">#518</a>`

### Describe alternatives you've considered

Possibly I would just remove the link on the order number completely since there is also one in the "Actions" column and the two links seem redundant.

### Additional context

This is marked as an enhancement rather than a bug as it's unclear for sighted people where this link goes as well, so it's not technically something that uniquely impacts screen reader users.

**Comment by frosso** [comment]
Closed by mistake due to a reference in another subscriptions core PR. Will close once https://github.com/woocommerce/woocommerce/pull/48374 is merged.
