### ISSUE TITLE
[CYS on core] Create a dedicated survey and tracking events for the CYS flow on core.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#43667]
On https://github.com/woocommerce/woocommerce/issues/41637 we temporarily removed the Survey button whenever the AI service is unavailable. This was a temporary change as we still didn't have the new survey for such cases ready by the time the CYS feature was released on WooExpress, but now we do.

With that said, the goal is to conditionally change the survey content depending on the environment the store owner is creating their site on (whether on WooExpress or Core) and also depending on the availability of AI on WooExpress: if AI is down, the survey should be the same as the one displayed on core.

## Designs

Figma: FlPl7fHaGv9mpu8Nfl0joH-fi-625_44310

### Updated Initial Transitional Page

* Ensure the survey button is displayed on core and also whenever AI is down on WooExpress.
* Update the copy for the body text (copy for the title and buttons remain the same):

| Initial Transitional Page > Expected Implementation on Core | Initial Transitional Page > Current view on WooExpress (should not be changed) |
|--------|--------|
|![image](https://github.com/woocommerce/woocommerce/assets/15730971/327e04b6-d833-467f-89f1-c933aa975e6f) | <img width="588" alt="Screenshot 2024-01-15 at 13 34 38" src="https://github.com/woocommerce/woocommerce/assets/15730971/8a1ad9ff-5a43-4496-a851-fcab131a6779"> |

### Updated Survey Form

| Survey Form > Expected Implementation on Core | Survey Form > Current view on WooExpress (should not be changed) |
|--------|--------|
| <img width="449" alt="Screenshot 2024-01-15 at 11 41 34" src="https://github.com/woocommerce/woocommerce/assets/15730971/5d798e48-2d7c-4eb9-b265-8ea282780a73"> | <img width="566" alt="Screenshot 2024-01-15 at 11 38 18" src="https://github.com/woocommerce/woocommerce/assets/15730971/a0e89b0c-6114-4c19-b8a0-6ce1b000a2d0"> |   

* Conditionally change the form content based on the environment, keeping the survey as-is on WooExpress and updated on Core.
* Open the designs on Figma to verify how the survey modal should look whenever filled.

### Updated tracking events

Currently, there are two events associated with the survey form:

* [`'customize_your_store_transitional_survey_click'`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/transitional/index.tsx#L106)
* [`'customize_your_store_transitional_survey_complete'`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/transitional/survey-form/index.tsx#L79)

For the implementation on core, we need to create new dedicated events to be triggered whenever the survey button is clicked, and feedback is given. Suggestion:

* `'customize_your_store_on_core_transitional_survey_click'`
* `'customize_your_store_on_core_transitional_survey_complete'`

Next, we need to also conditionally change the `recordEvent` based on the environment, keeping the events as-is on WooExpress and updated on Core.

### Updated transitional Page after survey complete

* Update the copy for the body text (copy for the title and buttons remain the same).

| Transitional Page after survey complete > Expected Implementation on Core | Transitional Page after survey complete > Current view on WooExpress (should not be changed) |
|--------|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/15730971/163b7c41-ded1-45b6-ac16-ac51dc0e9f0c) | <img width="1238" alt="Screenshot 2024-01-15 at 14 52 12" src="https://github.com/woocommerce/woocommerce/assets/15730971/c94f433e-d981-46a3-8245-739e4bca9428">|

**Comment by nefeline** [comment]
Hi @verofasulo and @lauroraa. Could you please take a look at the scope of this issue and confirm if it aligns with the expected design and copy? Thanks!

**Comment by verofasulo** [comment]
Thanks for double-checking, @nefeline! 

> Updated transitional Page after survey complete
Update the copy for the body text (copy for the title and buttons remain the same).

I'm not sure what you're referring to here. After the survey has been submitted:

- We close the modal.
- We don't display the `Share feedback` button.
- We display a time-controlled snackbar to provide feedback to users.  

Other than that, everything looks good to me! 🙂

**Comment by nefeline** [comment]
Thanks!

> I'm not sure what you're referring to here. After the survey has been submitted:
>
> We close the modal.
> We don't display the Share feedback button.
> We display a time-controlled snackbar to provide feedback to users.
>
> Other than that, everything looks good to me! 🙂

By remaining the same, I meant this has already been implemented on WooExpress and will remain the same on core (no extra engineering work required).
