### ISSUE TITLE
8.5.1 Update Causes Fatal Error (500 Server)

### ISSUE THREAD

**Issue by emperor42** [woothemes/woocommerce#43684]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After 8.5.1 Update entire website is inaccessible, including WP Admin

WordPress Error Page: "There has been a critical error on this website."

Resolution mentioned in 8.5.0 attempted, does not resolve. 

### Expected behavior

A seamless bugfix update 

### Actual behavior

Website crashed

### Steps to reproduce

1. Update Using Wp-Admin
2. Update Failed -> No Reasons Given
3. Wp-Admin Inaccessible, Website Down.

### WordPress Environment

TBC

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by unsamwill** [comment]
just rollback to 8.4.0 version,  and clean datebase, reinstall wordpress core, all issue should be fine, hope to help you.

**Comment by rodelgc** [comment]
Hi @Emperor42. Thanks for reporting this. Would you be able to share the console and network logs from your browser? Hopefully that would give us more details to work with.

**Comment by emperor42** [comment]
> just rollback to 8.4.0 version, and clean datebase, reinstall wordpress core, all issue should be fine, hope to help you.

Found Rollback solution already and had completed that more reporting to show the visibility into the issue

**Comment by emperor42** [comment]
> Hi @Emperor42. Thanks for reporting this. Would you be able to share the console and network logs from your browser? Hopefully that would give us more details to work with.

Apologies as I was not completely clear in my initial post, the ONLY error which came up on network and console was 500 Internal Server Error, the response was a WordPress error page.
No Error tracking on host nor anything helpful from Jet-pack just an unknown error after attempting the update.

**Comment by emperor42** [comment]
To further add context the Known issue from 8.5.0 workaround involving Activating Marketplace DOES NOT apply as our site already had marketplace enabled BEFORE the update attempt

**Comment by XGhozt** [comment]
This is likely related to #43681 . Your server admin can configure security blocks to be a 403, or a 500.

**Comment by emperor42** [comment]
> This is likely related to #43681 . Your server admin can configure security blocks to be a 403, or a 500.

There seems to be a fix of sorts in the associated issues which I can try out to confirm if related, I however would have had an event logged if it was in fact a security block on the server regardless of the error type returned. Thank you for linking the tickets

**Comment by lanej0** [comment]
Going to mark this as a duplicate of https://github.com/woocommerce/woocommerce/issues/43681 for now (as we're not seeing others with the same issue).  That issue is assigned and triaged.
