### ISSUE TITLE
When uploading images from the mobile phone, when the screen goes black, the upload stops. That wasnt the case before

### ISSUE THREAD

**Issue by callanerd** [woothemes/woocommerce#43721]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When uploading images from the mobile phone, when the screen goes black, the upload stops. That wasnt the case before

### Expected behavior

Upload should continue

### Actual behavior

The image upload stops when the screen become black

### Steps to reproduce

upload images with the mobile phone, screen become black, upload stop

### WordPress Environment ###

WordPress address (URL): https://www..de
Site address (URL): https://www..de
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 7200
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.42
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 9711.19MB
Datenbank-Datengröße: 5982.88MB
Datenbank-Indexgröße: 3728.31MB
wp_woocommerce_sessions: Daten: 17.02MB + Index: 1.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.13MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 136.66MB + Index: 37.58MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 1079.00MB + Index: 982.83MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 8.36MB + Index: 13.17MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 13.02MB + Index: 7.03MB + Engine InnoDB
wp_adtribes_my_conversions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aryo_activity_log: Daten: 11.52MB + Index: 0.00MB + Engine InnoDB
wp_as3cf_items: Daten: 13.52MB + Index: 21.16MB + Engine InnoDB
wp_borlabs_cookie_consent_log: Daten: 280.28MB + Index: 66.47MB + Engine InnoDB
wp_borlabs_cookie_content_blocker: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_cookies: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_borlabs_cookie_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_script_blocker: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_statistics: Daten: 17.05MB + Index: 30.09MB + Engine InnoDB
wp_commentmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 334.89MB + Index: 199.50MB + Engine InnoDB
wp_ewwwio_images: Daten: 16.52MB + Index: 15.11MB + Engine InnoDB
wp_ewwwio_queue: Daten: 7.02MB + Index: 4.02MB + Engine InnoDB
wp_gm_invoice_pdf_order_meta: Daten: 74.52MB + Index: 0.08MB + Engine InnoDB
wp_jtl_connector_link_crossselling_group: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_currency: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_customer_group: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jtl_connector_link_language: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_manufacturer: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_measurement_unit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_shipping_class: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_shipping_method: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_specific: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jtl_connector_link_specific_value: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 25.50MB + Index: 4.09MB + Engine InnoDB
wp_postmeta: Daten: 2126.98MB + Index: 1094.78MB + Engine InnoDB
wp_posts: Daten: 228.84MB + Index: 116.33MB + Engine InnoDB
wp_redirection_404: Daten: 9.52MB + Index: 7.88MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.38MB + Index: 0.23MB + Engine InnoDB
wp_sc_delivery_methods: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sc_delivery_zones: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_smush_dir_images: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_storeabill_documentmeta: Daten: 8.52MB + Index: 7.03MB + Engine InnoDB
wp_storeabill_documents: Daten: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_storeabill_document_itemmeta: Daten: 13.52MB + Index: 11.03MB + Engine InnoDB
wp_storeabill_document_items: Daten: 2.52MB + Index: 2.48MB + Engine InnoDB
wp_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_notices: Daten: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Daten: 7.36MB + Index: 4.33MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_tinvwl_analytics: Daten: 14.58MB + Index: 7.56MB + Engine InnoDB
wp_tinvwl_items: Daten: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Daten: 116.67MB + Index: 76.19MB + Engine InnoDB
wp_users: Daten: 2.52MB + Index: 2.55MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 12.52MB + Index: 10.00MB + Engine InnoDB
wp_wc_download_log: Daten: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders: Daten: 125.67MB + Index: 121.48MB + Engine InnoDB
wp_wc_orders_meta: Daten: 562.98MB + Index: 525.97MB + Engine InnoDB
wp_wc_order_addresses: Daten: 74.61MB + Index: 69.17MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_wc_order_operational_data: Daten: 61.59MB + Index: 21.06MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 111.66MB + Index: 100.25MB + Engine InnoDB
wp_wc_order_stats: Daten: 48.58MB + Index: 34.61MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 23.56MB + Index: 16.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 5.52MB + Index: 9.61MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Daten: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Daten: 2.27MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Daten: 14.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Daten: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Daten: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Daten: 1.02MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Daten: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Daten: 1.02MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wirecard_payment_gateway_tx: Daten: 219.70MB + Index: 2.52MB + Engine InnoDB
wp_wirecard_payment_gateway_vault: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wirecard_payment_general_information: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 18.55MB + Index: 17.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 7.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 33.56MB + Index: 24.09MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 10.52MB + Index: 4.55MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 23.56MB + Index: 24.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 12.52MB + Index: 16.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfm_backup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_admin_theme_cd_license_data: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Daten: 7.05MB + Index: 1.86MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 1.02MB + Index: 3.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 4.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 8
acf-field-group: 3
attachment: 168551
blocks: 1
custom-css-js: 3
customize_changeset: 53
custom_css: 3
document_template: 46
elementor_font: 3
elementor_library: 17
ep-synonym: 1
export_template: 1
faq: 24
ff-options: 8
invoice: 97593
nav_menu_item: 78
oembed_cache: 12
page: 30
post: 14
product: 6783
product-feed: 1
product_variation: 20209
revision: 11652
shop_coupon: 795
shop_order: 266861
shop_order_refund: 96826
wppopups: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Advanced Custom Fields: von WP Engine – 6.2.4
Angell EYE Updater: von Angell EYE – 2.0.18
Borlabs Cookie - Cookie Opt-in: von Borlabs GmbH – 2.2.67
Breeze: von Cloudways – 2.1.3
Code Snippets: von Code Snippets Pro – 3.6.2
Custom Sidebars: von WebFactory Ltd – 3.36
Disable Gutenberg: von Jeff Starr – 3.1
ElasticPress: von 10up – 5.0.1
EWWW Image Optimizer: von Exactly WWW – 7.2.3
Just Custom Fields for Wordpress: von JustCoded / Alex Prokopenko – 3.3.2
Local Google Fonts: von EverPress – 0.22.0
Order Export & Order Import for WooCommerce: von WebToffee – 2.4.6
Perfect Brands for WooCommerce: von QuadLayers – 3.3.2
Product Sales Report for WooCommerce: von WP Zone – 1.5.6
Seitlicher WooCommerce-Warenkorb: von XootiX – 2.4.7
Product Gallery Slider for WooCommerce PRO: von Codeixer – 3.4
UpdraftPlus – Sichern/Wiederherstellen: von UpdraftPlus.Com
DavidAnderson – 1.23.16

User Role Editor Pro: von Vladimir Garagulia – 4.64.1
Minicart for WooCommerce: von Ahmad Shyk – 2.0.5
Advanced Order Export For WooCommerce: von AlgolPlus – 3.4.5
Product Feed PRO for WooCommerce: von AdTribes.io – 13.1.9
Payment Plugins for Stripe WooCommerce: von Payment Plugins
support@paymentplugins.com – 3.3.55

Print Invoice & Delivery Notes for WooCommerce: von Tyche Softwares – 4.8.1
German Market: von MarketPress – 3.31
WooCommerce PayPal Payments: von WooCommerce – 2.4.3
Woocommerce Backend Attributes Selection Fix: von Call a nerd – 1.0
Brevo - WooCommerce Email Marketing: von Brevo – 4.0.9
WooCommerce: von Automattic – 8.4.0 (Update auf Version 8.5.1 ist verfügbar)
Wordfence Security: von Wordfence – 7.11.1
Yoast SEO: von Team Yoast – 21.8
WP Mail SMTP: von WP Mail SMTP – 3.11.0
WP Popups Lite: von timersys – 2.1.5.5
WP Rollback: von WP Rollback – 2.0.5
YITH WooCommerce Sequential Order Number Premium: von YITH – 1.31.0

### Inactive Plugins (21) ###

Debug Bar: von wordpressdotorg – 1.1.4
ElasticPress Debugging Add-On: von 10up – 3.1.0
Germanized for WooCommerce: von vendidero – 3.15.5
Germanized for WooCommerce Pro: von vendidero – 2.1.0
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.9.0

Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 3.2.4

Mollie Payments for WooCommerce: von Mollie – 7.4.1
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: von Brevo – 3.1.72
Payment Gateway Plugin for PayPal WooCommerce ( Free ): von WebToffee – 1.8.2
PayPal for WooCommerce: von Angell EYE – 4.4.13
PayPal Plus for WooCommerce: von Angell EYE – 1.2.15
Product Gallery Slider for WooCommerce PRO: von Codeixer – 3.3.6.2
Product Import Export for WooCommerce: von WebToffee – 2.3.9
Query Monitor: von John Blackbourn – 3.15.0
Sendcloud | Smart Shipping Service: von Sendcloud B.V. – 2.3.0
Stock Export and Import for WooCommerce: von WP Zone – 1.0.6
Storefront Top Bar: von Wooassist – 1.1.1
TI WooCommerce Wishlist: von TemplateInvaders – 2.8.0
Under Construction: von WebFactory Ltd – 3.97
WP File Manager: von mndpsingh287 – 7.2.1
YITH PayPal Express Checkout for WooCommerce: von YITH – 1.34.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop-Basis: #22 - /shop/
Warenkorb: #23 - /warenkorb/
Kasse: #24 - /kasse/
Mein Konto: #25 - /mein-konto/
Allgemeine Geschäftsbedingungen: #28 - /agb/

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: https://callanerd.help
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.5.2 – 4.5.4 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme-master/woocommerce/archive-product.php Version - ist veraltet. Die Hauptversion ist 3.4.0
storefront-child-theme-master/woocommerce/cart/cart-shipping.php
storefront-child-theme-master/woocommerce/content-product.php
storefront-child-theme-master/woocommerce/content-single-product.php
storefront-child-theme-master/woocommerce/single-product/add-to-cart/variable.php Version 3.5.5 ist veraltet. Die Hauptversion ist 6.1.0
storefront-child-theme-master/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php Version 3.4.0 ist veraltet. Die Hauptversion ist 7.0.1
storefront-child-theme-master/woocommerce/single-product/add-to-cart/variation.php
storefront-child-theme-master/woocommerce/single-product/photoswipe.php
storefront-child-theme-master/woocommerce/single-product/price.php
/var/www/share/www.luckyme-online.de/htdocs/wp-content/plugins/twist/inc/public/templates/default.php
storefront-child-theme-master/woocommerce/single-product/product-thumbnails.php
storefront-child-theme-master/woocommerce/single-product/related.php
storefront-child-theme-master/woocommerce/single-product.php
storefront-child-theme-master/woocommerce/content-product_cat.php Version 2.6.1 ist veraltet. Die Hauptversion ist 4.7.0

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-17 21:03:12 +01:00
Options: ✔
Notes: 6
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 23.486
Oldest: 2023-12-16 22:40:45 +0100
Newest: 2024-01-16 22:35:57 +0100

Fehlgeschlagen: 841
Oldest: 2020-01-31 22:48:56 +0100
Newest: 2023-12-08 14:04:50 +0100

Ausstehend: 2
Oldest: 2024-01-17 18:35:55 +0100
Newest: 2024-01-17 19:11:55 +0100

### Status report information ###

Generated at: 2024-01-16 22:38:18 +01:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @callanerd -- are you having issues with the iOS app or the Android app?

This isn't really an issue with WooCommerce, but would be more with the client app.  I can transfer this issue to the right team, just need to know a bit more about the device you're working with!
