### ISSUE TITLE
Ineffective Registration of Payment Method using registerPaymentMethod

### ISSUE THREAD

**Issue by hoythan** [woothemes/woocommerce#43724]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am currently developing a payment feature and attempting to use registerPaymentMethod to register support for blocks.

However, it fails to appear on the checkout page, only displaying on the checkout edit page.

Are there any particular points I should be aware of?

I can confirm that my payment method has been successfully added, as I can see it listed when using wc.wcBlocksRegistry.getPaymentMethods() in the console.

```javascript
(() => {
	const { wcSettings, wcBlocksRegistry } = window.wc;

	const data = wcSettings.getSetting("myPay_data");

    const myPayTitle = wp.htmlEntities.decodeEntities(data.title || "");
	const decodeDescription = () => wp.htmlEntities.decodeEntities(data.description || "");

	const myPayPaymentMethod = {
		name: "myPay",
		ariaLabel: myPayTitle,
		label: window.React.createElement(
			() => {
				return window.React.createElement(() => myPayTitle);
			},
			null
		),
		content: window.React.createElement(decodeDescription, null),
		edit: window.React.createElement(decodeDescription, null),
		canMakePayment: () => {
			console.log("canMakePaymentcanMakePayment");
			console.log("canMakePayment");
			return true;
		},
		supports: {
			showSavedCards: false,
			showSaveOption: false,
			features: data.supports,
		},
	};

	wcBlocksRegistry.registerPaymentMethod(myPayPaymentMethod);
})();
```
```php
<?php

use Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType;
use Automattic\WooCommerce\StoreApi\Payments\PaymentContext;
use Automattic\WooCommerce\StoreApi\Payments\PaymentResult;

final class WC_Gateway_MYPAY_Blocks_Support extends AbstractPaymentMethodType {
	/**
	 * Payment method name/id/slug.
	 *
	 * @var string
	 */
	protected $name = 'mypay';


	/**
	 * Initializes the payment method type.
	 */
	public function initialize() {
		$this->settings = get_option( 'woocommerce_mypay_settings', array() );

		add_action( 'woocommerce_rest_checkout_process_payment_with_context', array( $this, 'failed_payment_notice' ), 8, 2 );
	}

	/**
	 * Returns if this payment method should be active. If false, the scripts will not be enqueued.
	 *
	 * @return boolean
	 */
	public function is_active() {
		// $payment_gateways_class = WC()->payment_gateways();
		// $payment_gateways       = $payment_gateways_class->payment_gateways();
		// if ( ! isset( $payment_gateways[ $this->name ] ) ) {
		// 	return false;
		// }

		// return $payment_gateways[ $this->name ]->is_available();

        return true;
	}

	/**
	 * Returns an array of scripts/handles to be registered for this payment method.
	 *
	 * @return array
	 */
	public function get_payment_method_script_handles() {
		$script_url = plugins_url( "/assets/js/blocks/mypay.js", MYPAY_MAIN_FILE );

		wp_register_script(
			"wc-mypay-blocks",
			$script_url,
			array('wc-blocks-checkout', 'react', 'wc-blocks-registry', 'wc-settings', 'wp-html-entities', 'wp-i18n'),
			'1.2',
			true
		);
		wp_set_script_translations( 'wc-mypay-blocks', 'mypay' );
		return array( "wc-mypay-blocks" );
	}

	/**
	 * Returns an array of key=>value pairs of data made available to the payment methods script.
	 *
	 * @return array
	 */
	public function get_payment_method_data() {
		$payment_gateways_class = WC()->payment_gateways();
		$payment_gateways       = $payment_gateways_class->payment_gateways();
		$gateway                = $payment_gateways[ $this->name ];
		return array(
			'title'             => $this->get_setting( 'title' ),
			'description'       => $this->get_setting( 'description' ),
			'supports'          => array_filter( $gateway->supports, array( $gateway, 'supports' ) ),
			'allow_saved_cards' => is_user_logged_in(),
		);
	}

	/**
	 * Add failed payment notice to the payment details.
	 *
	 * @param PaymentContext $context Holds context for the payment.
	 * @param PaymentResult  $result  Result object for the payment.
	 */
	public function failed_payment_notice( PaymentContext $context, PaymentResult &$result ) {
		if ( 'mypay' === $context->payment_method ) {
		}
	}
}
```

![image](https://github.com/woocommerce/woocommerce/assets/12378108/b653bb85-414f-40fb-8e98-b14dad758172)

![image](https://github.com/woocommerce/woocommerce/assets/12378108/d073971d-5a15-4a12-90fc-d7dcf89da908)

### Expected behavior

https://github.com/woocommerce/woocommerce/discussions/43644

### Actual behavior

https://github.com/woocommerce/woocommerce/discussions/43644

### Steps to reproduce

https://github.com/woocommerce/woocommerce/discussions/43644

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://demo.wc.doofox.cn
Site address (URL): https://demo.wc.doofox.cn
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 8.1.13
PHP Post Max Size: 500 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 8.0.24
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 6.00MB
Database Data Size: 4.30MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 3
shop_order: 7
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

MugglePay: by MugglePay – 1.0.1
Paystack WooCommerce Payment Gateway: by Tunbosun Ayinla – 5.8.1
WooCommerce: by Automattic – 8.4.0 (update to version 8.5.1 is available)

### Inactive Plugins (2) ###

Coinbase Commerce: by Coinbase Commerce – 1.3
Dintero Checkout for WooCommerce Payment Methods: by Dintero
Krokedil – 1.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /www/wwwroot/demo.wc.doofox.cn/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/www/wwwroot/demo.wc.doofox.cn/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/www/wwwroot/demo.wc.doofox.cn/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-18 02:04:57 +00:00
Options: ✔
Notes: 71
Onboarding: -

### Action Scheduler ###

Canceled: 1
Oldest: 2024-01-08 02:06:34 +0000
Newest: 2024-01-08 02:06:34 +0000

Complete: 167
Oldest: 2024-01-03 03:20:20 +0000
Newest: 2024-01-17 00:15:06 +0000

Failed: 3
Oldest: 2024-01-03 03:23:15 +0000
Newest: 2024-01-07 14:41:07 +0000

Pending: 1
Oldest: 2024-01-18 00:15:06 +0000
Newest: 2024-01-18 00:15:06 +0000

### Status report information ###

Generated at: 2024-01-17 02:25:30 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
This is likely a problem with your `supports` value, can you try using this instead `'supports'    => $this->get_supported_features(),` and adding a regular item to your cart?

**Comment by nielslange** [comment]
Hello @hoythan, have you had time to try the suggestion @senadir shared in https://github.com/woocommerce/woocommerce/issues/43724#issuecomment-1898315784?
