### ISSUE TITLE
[Enhancement]: What is the patterns_ai_data CPT for? Can it be unregistered safely?

### ISSUE THREAD

**Issue by superbmario** [woothemes/woocommerce#43738]
### Describe the solution you'd like

I see a new patterns_ai_data CPT which looks like it is for the Block Editor. Is it safe to unregister this CPT or is it essential for WooCommerce even if not using the Block Editor? If it is not essential, it would be nice to have a filter/option to disable it in an official way.

### Describe alternatives you've considered

`unregister_post_type('patterns_ai_data');`

**Comment by Aljullu** [comment]
Hi there @superbmario, that CPT is used by the _Customize Your Store_ flow during the onboarding, so it should be safe to unregister it if you aren't planning to go through the onboarding tasks.

Having said that, I opened a separate issue for this: https://github.com/woocommerce/woocommerce/issues/52153. Ideally we shouldn't register this CPT at all on sites we know it's not going to be used. So hopefully you don't have to do anything and in a future version of WooCommerce we will fix it and the CPT won't be registered if not needed.

**Comment by Aljullu** [comment]
Given that we have now a separate issue to investigate how to optimize it (#52513) and this one is a question, I will proceed closing it. But feel free to reopen if you think otherwise. Thanks for raising this to us, @superbmario!
