### ISSUE TITLE
Steep increase in JavaScript (JS) files, when upgrading from 8.4.0 to 8.5.1?

### ISSUE THREAD

**Issue by anastas10s-afk** [woothemes/woocommerce#43743]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When testing, after seeing reports in the forums, it appears that the JS files increase in numbers after upgrading to WooCommerce 8.5.1.

Reports:
- https://wordpress.org/support/topic/bloated-wc-30-js-added-to-website/
- 7589550-zen

### Expected behavior

Some questions, instead. If so, how do we optimize this? Which files are non-essential? What's feasible to disable (and how)? Is there a developer's blog post we can point to?

### Actual behavior

Kindly see the numbers in the bottom left corner.

With WooCommerce version 8.4.0

<img width="1210" alt="Screenshot 2024-01-17 at 15 36 16" src="https://github.com/woocommerce/woocommerce/assets/73900974/9519e60a-3a35-405a-9ed4-5d2251d4a781">

With WooCommerce version 8.5.1

<img width="1211" alt="Screenshot 2024-01-17 at 15 36 29" src="https://github.com/woocommerce/woocommerce/assets/73900974/f1c43c46-8a4b-4f2e-8db5-cc92040dbe26">

### Steps to reproduce

1. Start with a WordPress 6.4.2 installation, and activate WooCommerce on it
2. First WooCommerce version 8.4.0
3. See the metrics in Network, via browser's tools
4. Then WooCommerce version 8.5.1
5. See the increased metrics in Network, via browser's tools

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://employtrouble.s2-tastewp.com
Site address (URL): https://employtrouble.s2-tastewp.com
WC Version: 8.5.1
REST API Version: ✔ 8.5.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: TasteWP-S2 Official/3.0.0
PHP Version: 8.2.10
PHP Post Max Size: 60 MB
PHP Time Limit: 100
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.32-0ubuntu0.20.04.2
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1
WC Database Prefix: wp_
Total Database Size: 4.89MB
Database Data Size: 3.20MB
Database Index Size: 1.69MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 3
shop_order_placehold: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.5.1

### Inactive Plugins (1) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-18 10:42:10 +00:00
Options: ✔
Notes: 64
Onboarding: skipped

### Action Scheduler ###

Complete: 10
Oldest: 2024-01-16 10:42:13 +0000
Newest: 2024-01-17 14:25:27 +0000

Failed: 1
Oldest: 2024-01-16 10:43:12 +0000
Newest: 2024-01-16 10:43:12 +0000

Pending: 1
Oldest: 2024-01-18 14:22:54 +0000
Newest: 2024-01-18 14:22:54 +0000

### Status report information ###

Generated at: 2024-01-17 14:39:18 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lkraav** [comment]
Potential connection https://github.com/woocommerce/woocommerce-blocks/issues/9040

**Comment by lanej0** [comment]
Is this causing a performance issue for you?  The number of files will fluctuate because WooCommerce is an active project.  If you could let us know what (if any) issue this is causing, I can better triage this report!

**Comment by lkraav** [comment]
This is one example why https://www.avivasolutions.nl/en/techblog/javascript-the-main-culprit-of-slow-websites (and countless other articles on "why websites should load minimal js").

This belongs in further triage, because like I've linked here earlier, WooCommerce dev team has made JS payload mistakes before. A massive payload difference is pointed out here, and at minimum, it becomes a documentation target.

**Comment by cometto277** [comment]
are you blind? after all, this is the worst thing I have encountered in years of using WooCommerce. When optimizing a website, you fight for every asset, and here it gets +20 more every day.
this is absolutely unacceptable and looks like sabotage to me. I'm also shocked that you don't see the problem

**Comment by cometto277** [comment]
> Is this causing a performance issue for you? The number of files will fluctuate because WooCommerce is an active project. If you could let us know what (if any) issue this is causing, I can better triage this report!

of course yes.
Try scan by GPSI and compare results from 8.4 and 8.5.1

**Comment by lkraav** [comment]
> are you blind? after all, this is the worst thing I have encountered in years of using WooCommerce. When optimizing a website, you fight for every asset, and here it gets +20 more every day.

Pump the brake pedal some, maybe. Not everybody has the technical skills to evaluate all issue types.

> here it gets +20 more every day

This is not true, and throwing such around doesn't help the case.

Bigger underlying problem here is likely that Blocks Cart and Checkout have become frontend React apps (a separate class of a problem all on its own), and dev team is having trouble keeping all the added script dependencies under control.

**Comment by anastas10s-afk** [comment]
Hey folks 👋 

Just a quick update, as I went ahead with investigating this further, and the findings turn things upside-down. 🎉 

For some further testing, I compared the `shortcode` version and the `block-based` version of the **Cart** page, in WooCommerce version 8.4.0, and 8.5.1.
The findings: WooCommerce version 8.5.1 loaded considerably **less** JS files, in both cases, during my testing. The newly released version outperformed the previous, that is.
Below, I am attaching screenshots, for reference.

### `Shortcode` version of the **Cart** page, in WooCommerce version 8.4.0 (a bit over 100 JS requests):
<img width="1680" alt="Screenshot 2024-01-17 at 23 07 05" src="https://github.com/woocommerce/woocommerce/assets/73900974/d0729a64-ad52-4846-a3af-653fc34232c0">

### `Shortcode` version of the **Cart** page, in WooCommerce version 8.5.1 (just above 70 JS requests):
<img width="1680" alt="Screenshot 2024-01-17 at 23 07 24" src="https://github.com/woocommerce/woocommerce/assets/73900974/13d78837-143a-4129-902e-e6b8a4399134">

### `Block-based` version of the **Cart** page, in WooCommerce version 8.4.0 (a bit over 170 JS requests):
<img width="1680" alt="Screenshot 2024-01-17 at 23 09 17" src="https://github.com/woocommerce/woocommerce/assets/73900974/c7a7eb3a-9532-4ab2-9672-833824184be9">

### `Block-based` version of the **Cart** page, in WooCommerce version 8.5.1 (under 100 JS requests):
<img width="1680" alt="Screenshot 2024-01-17 at 23 10 05" src="https://github.com/woocommerce/woocommerce/assets/73900974/530b3e22-ab66-45f6-a8e9-d55620e29584">

I stand corrected, as it appears, @lanej0, thanks for chiming-in.
Could you verify the new findings on your end, and clarify if it is the `shortcode` version or the `block-based` version of the **Cart** page in use at your installations, @lkraav @cometto277? Cheers!

**Comment by or128** [comment]
Increasing the amount of JS is a serious concern, I hope it will be addressed ASAP.

**Comment by lkraav** [comment]
Uh... @anastas10s-afk why is Shortcode-based checkout loading the full React-based blocks payload in the first place?

**Comment by sackadelic** [comment]
I'm following this as I had to roll back to 8.4.0 due to my Lighthouse score getting _crushed_ by 8.5.1. There should be a method to turn the blocks "off" if you're not using a block based theme.

**Comment by lanej0** [comment]
I'm going to shut down this thread just because there aren't any specific issues that are being discussed.  @sackadelic please feel free to open a new issue (with numbers from Lighthouse if at all possible) so that we can look more into possible performance issues.

**Comment by Aljullu** [comment]
Heads-up that [WooCommerce 8.5](https://developer.woo.com/2024/01/09/woocommerce-8-5-0-released/) has introduced a new feature named 'Order Attribution' which loads some additional scripts in the frontend, and that might be the reason some of you are experiencing an increase in JS files loaded on some pages.

Our team is currently investigating if we can reduce the scripts loaded in the frontend for this feature to work in https://github.com/woocommerce/woocommerce/issues/43829.

In the meanwhile, if you don't need it, you can disable it from WooCommerce > Settings > Advanced > Order Attribution.
