### ISSUE TITLE
[Enhancement]: Allow retaining of cart items when users log in and out of their account

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#43744]
### Describe the solution you'd like

When a shopper is in a logged out state and adds items to their cart, proceeds to checkout, and the store allows logging into their account during checkout, logging in will reset the cart and empty it of its items. The same occurs if a shopper were to log in via the My account link. This can make for a high friction and frustrating experience with a risk of abandonment. 

Conversely, when adding items IN a logged in state, logging out will also empty the cart of its items.

![CleanShot 2024-01-17 at 22 30 48@2x](https://github.com/woocommerce/woocommerce/assets/99638528/ea74d5a4-8829-498a-a541-683b274f2b40)

https://github.com/woocommerce/woocommerce/assets/99638528/6639d2fc-af3f-4cc7-88ce-c67528db46a6

Ideally, the following should occur when you log in after adding items to their cart:

- The items you added to your cart as a guest should remain in your cart after you log in
- Potential merging of carts: If you had items in your cart from a previous session under your account, the site might merge these with the current cart contents. This behavior can vary: ask if you want to merge carts, do it automatically

**Comment by tarunvijwani** [comment]
This seems to be a duplicate issue. Closing it in favor of https://github.com/woocommerce/woocommerce/issues/34464
