### ISSUE TITLE
[Enhancement]: Allow Disable Postcode field on Checkout >8.3

### ISSUE THREAD

**Issue by PabloLombriz** [woothemes/woocommerce#43742]
### Describe the solution you'd like

Allow to Disable the Postcode field on Checkout for >8.3 versions (block checkout)

### Additional context

All custom php codes that worked on <8.3 versions dont't work anymore. So the only solution is to revert to shortcode

**Comment by senadir** [comment]
Are you looking to disable post code for a specific country or all countries?

**Comment by PabloLombriz** [comment]
I'm looking to disable post code for a specific country because all shops I
create are for an specific country, but if a global configuration can be
done so it can works too.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by senadir** [comment]
Hey! Assuming your country code XX, this code would do it

```php
add_filter('woocommerce_get_country_locale', function( $locale ) {
		$locale['XX']['postcode']['required'] = false;
		$locale['XX']['postcode']['hidden'] = true;
		return $locale;
});
```

**Comment by senadir** [comment]
Disabling a field for all countries is not supported because each country has its own spec.

**Comment by PabloLombriz** [comment]
Cool, it works!
Thanks a lot

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tarunvijwani** [comment]
As this issue has been resolved, I will close this ticket. However, please feel free to leave a comment if you have any further questions.
