### ISSUE TITLE
[Enhancement]: Convert My Account page to load different tabs via AJAX instead of reloading the page

### ISSUE THREAD

**Issue by lynnjat7** [woothemes/woocommerce#43755]
### Describe the solution you'd like

Right now on the customer's My Account page on a shop owner's website, each tab - Payment Details, Account Info, Orders, etc. - reloads the entire page.

At least one shop owner has been in touch saying that he has a requirement to load these tabs via AJAX instead, and that this change is not difficult. The reason is that he is customizing the My Account page to add additional information specific to the user, including Membership-restricted content, and this information is being lost / not loading properly with the full page reloads.

He's actually modified his site (using the Twenty Twenty-Four theme) already to make this happen with a small amount of code and would like to submit it to the dev team for their consideration.

### Describe alternatives you've considered

Code that you'd need to add to make this happen.

First, add to the theme:
AJAX URL Script to support WooCommerce End Point loads: 

```
function enqueue_ajax_url_script() {
    ?>
    <script>
        var ajaxurl = '<?php echo esc_url(admin_url('admin-ajax.php', 'https')); ?>';
    </script>
    <?php
}
add_action('wp_footer', 'enqueue_ajax_url_script');
```

JavaScript to enable woocommerce ajax endpoints: 

```
// JavaScript
jQuery(document).ready(function($) {
    // Attach click event to tabs
    $('body').on('click', '.woocommerce-MyAccount-navigation-link', function(e) {
        e.preventDefault();

        // Get the endpoint and anchor from the tab link
        var endpointWithAnchor = $(this).attr('href').replace('#', '');

        // Extract the endpoint and anchor separately
        var endpoint = endpointWithAnchor.split('#')[0];
        var anchor = endpointWithAnchor.split('#')[1];

        // Trigger AJAX request
        $.ajax({
            url: ajaxurl,
            type: 'POST',
            data: {
                action: 'load_account_tab_content',
                endpoint: endpoint,
            },
            success: function(response) {
                // Update the tab content with the response
                $('#your-tab-content-container').html(response);

                // Scroll to the anchor if available
                if (anchor) {
                    $('html, body').animate({
                        scrollTop: $('#' + anchor).offset().top
                    }, 500);
                }
            },
        });
    });
});
```

### Additional context

7599580-zen
7599929-zen

**Comment by lkraav** [comment]
Considering WP is not naturally SPA at this time, this looks like pure site-specific customization territory to my eye.

**Comment by chiefbirch** [comment]
Thanks for posting this @lynnjat7

**Comment by jorgeatorres** [comment]
Hi @lynnjat7!

Thanks for reaching out. We discussed this with the team, and our take is that this is more of a customization issue. We're currently not working on making _My Account_ work via AJAX, and there are also some concerns about compatibility with other plugins or 3rd party code, as those might be adding tabs/links to this page in a way that is not compatible with AJAX loading.

I'm going to close this issue now, but feel free to re-open if I've misrepresented anything.

**Comment by ripmurdock** [comment]
Hi @lynnjat7!

I'm interested in implementing a solution like this.  Does this action: load_account_tab_content require a custom ajax handler?  If so, can you post one, or direct me to an example?

Thanks!
