### ISSUE TITLE
[Enhancement]: reduce calls to `wp_count_posts( 'product' )` from OnboardingTasks

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#43768]
### Describe the solution you'd like

I was looking at https://github.com/woocommerce/woocommerce/issues/36652, which complained we are calling `wp_count_posts( 'product' )` on each admin request. That particular issue was specifically interested in the call stemming from some `WC_Install` code, but there are other sources too, one of which is the following chain:

- `Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::menu_task_count()`
- `Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::setup_tasks_remaining()`
- `Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList::is_complete()`
- `Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Products::is_complete()`
- `Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Products::has_products()`
- `wp_count_posts()`

I wonder if this (the number of requests in which we need to call `wp_count_posts()`) could be reduced via transient caching or similar? Post counts *are* already cached by WP, but only on a per-request basis (unless persistent object caching is present).

### Describe alternatives you've considered

Instead of using transient based caching, perhaps other heuristics are available? Mostly wanted to flag since it's a complaint that's cropped up in other contexts, too, like https://github.com/woocommerce/woocommerce/issues/31029 (which complains about essentially the same thing, but via WC Tracker).

### Additional context

I wonder if it would make sense to address in tandem with https://github.com/woocommerce/woocommerce/issues/36195?

**Comment by adrianduffell** [comment]
I think `menu_tasks_count()` might be a good candidate to be cached in a transient. It seems like it would be generating multiple queries on every page load 🤔 

For `wp_count_posts()`, I'd prefer to rely on the native persistent object caching and encourage sites to use this to solve bad performance. I understand many hosts have this enabled?

**Comment by barryhughes** [comment]
> I understand many hosts have this enabled?

Well, I don't know. It would be nice to assume so, but I also don't think we capture this via Tracker, though perhaps there are other sources we could look at. Mostly, just wanted to get this on your radar so you could make an assessment 🙌🏼
