### ISSUE TITLE
Make custom columns in Analytics sortable [Enhancement]: 

### ISSUE THREAD

**Issue by photogenic89** [woothemes/woocommerce#43776]
### Describe the solution you'd like

While creating custom columns for Analytics/Customers I noticed that it is not possible to make them sortable. It returns an error when trying to do so, because the Analytics Rest api does not provide adding custom parameters like the custom column to the "orderby" parameter. 
When giving developers the possibility to create custom columns for Analytics, those columns should be able to have all the features like default columns, like sorting.

### Describe alternatives you've considered

WooCommerce customer support suggested using the backend filter woocommerce_analytics_customers_query_args. 
Adding a specific column key to "orderby" unfortunately makes it impossible to switch sorting between different columns.

### Additional context

When adding custom column to the table header through the js filter woocommerce_admin_report_table, you can give the new column header object the property isSortable: true. Once this has been done, and one tries to sort by the custom column, it shows the error "There was an error getting your stats. Please try again.". The api fetch returns a 400 because the "orderby" parameter for Customers only allows the defaults: username, name, country, city, state, postcode, date_registered, date_last_active, orders_count, total_spend, and avg_order_value.
Those defaults are defined in Automattic\WooCommerce\Admin\API\Reports\Customers\Controller->get_collection_params(). There is no filter at any point in the request chain to change those parameters, making it impossible to alter the data.

**Comment by photogenic89** [comment]
No one? WooCommerce provides the javascript filter woocommerce_admin_report_table, which gives developers the possibility to add their own columns. isSortable is one of the properties one can use when adding a column header object in this filter. Then WooCommerce also provides filters to alter the MySQL query in the backend.

So I’m wondering, if I’m missing something in the source code. Maybe a filter somewhere. Because why would you give users this customisability while not providing entry points for one of the most basic adjustments like sorting?

**Comment by ianlin** [comment]
Hi @photogenic89, thanks for the suggestion. There's a similar issue #46275 and it's already addressed in the PR #49722, it will be included in the next version of WooCommerce `9.4.0`.
