### ISSUE TITLE
[Product Editor] Implement throttling on the Save/Update button

### ISSUE THREAD

**Issue by xristos3490** [woothemes/woocommerce#43774]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It seems that every time I click on the Update button I get a toast message.

### Expected behavior

Perhaps we need to introduce some throttling into that action.

### Actual behavior

A screencast:

https://github.com/woocommerce/woocommerce/assets/1105590/df7d4543-0d8e-46d0-bea8-bc74dba0b516

### Steps to reproduce

1. Navigate to the product editor
2. Make any changes to the product 
3. Click on the Update button multiple times.
4. Observe the toast messages.

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by octaedro** [comment]
Closing this bug report since it has been fixed.
