### ISSUE TITLE
Hide the product type selector dropdown when click outside

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#43785]
**Description**

The product type selector dropdown remains visible when clicking outside of it when that should hide it.

**ACs**

```[tasklist]
### Tasks
- [x] Hide the product type selector dropdown when click outside
```

**Comment by nigeljamesstevenson** [comment]
Related https://github.com/woocommerce/woocommerce/issues/43787 raised by GlobalStep
