### ISSUE TITLE
[Product Gallery] Overlay sizing issue

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#43826]
I am seeing in certain circumstances, the overlay container is sometimes full size and sometimes resized to the image. This make it look inconsistent. It would probably be cleaner if it was always full size regardless. WDYT?

![file.png](https://github.com/woocommerce/woocommerce/assets/2132595/a5ac9874-21e2-42b5-8876-07095fbbc7fd)
![file.png](https://github.com/woocommerce/woocommerce/assets/2132595/5cb1f692-0cc8-4c99-a502-e9755cb02703)

- There is currently an overlay container. This container can be removed as we no longer need it because we want a fullscreen experience with just the dialog.
- We need to position the Close dialog button to the top right regardless of the resolution/scale.
- We need to position the left/right arrow buttons to the left most edge and right most edge respectively regardless of the resolution/scale.

**Comment by jarekmorawski** [comment]
It should always be full-screen. Do we know what makes it shrink sometimes? Based on the screenshot, it looks like it's defaulting to mobile for some reason.

**Comment by roykho** [comment]
~~My hunch is that when there are only one image the issue arises because it is the left/right arrow navigation that is making it full screen.~~

It's because when multiple images exists, it is able to push the container to stretch 100%. When you have less images, it doesn't.
