### ISSUE TITLE
[DOC-REQ] How can i hide place order button in WooCommerce Blocks?

### ISSUE THREAD

**Issue by 0xBeycan** [woothemes/woocommerce#43839]
## Description of the Document Requested

I am integrating our existing payment method application into blocks checkout, but optionally express payment style is available on the checkout page. On the Classic WooCommerce checkout page, we hide the button with the "woocommerce_order_button_html" hook. But I couldn't find a method for blocks. Can you help?

## Why is this Document Important?

To make it easier for people to integrate

## Potential Content

I think you can mention it on the current integration page

**Comment by mikejolley** [comment]
Hi @BeycanDeveloper 

Could I have more details about what you're attempting to accomplish? Why does the place order button need to be hidden for this particular gateway?

Thanks!

**Comment by 0xBeycan** [comment]
Hello, because the paying process takes place at the front with the user's action. In other words, instead of clicking on the place order button, he should follow our paying process in the content section. That's why, as I mentioned, I can do this on the classic Woo checkout page, but I couldn't find a source for Blocks.

**Comment by mikejolley** [comment]
Perhaps you can share details about the gateway flow. It sounds as though its an express payment method?

**Comment by 0xBeycan** [comment]
Actually, all I want is for the button to be hidden when my pay gateway is selected. I'm saying that I've already done this with a hook of normal Woo standards. I want to do the same for Blocks. There is nothing related to my plugin here.

And yes, this is a crypto pay gateway, so it connects directly to wallets. For this reason, the process proceeds in the front part of our plugin, we create the order from cart data with endoint according to the situation.

**Comment by mikejolley** [comment]
The reason we're asking is to understand your current requirements and see if there are existing or alternative solutions. I don't think it would make sense to just add the ability to straight up hide hide the button without first understanding the reasoning for doing so, and if other extensions may or may not need this functionality.

I believe there are ways to disable or block the button, but not hide it. We do not allow extensions to take control over order creation. That could be problematic for existing checkout flows or other extensions that tie functionality for that button or other extensibility hooks in block checkout.

cc @opr

**Comment by 0xBeycan** [comment]
Yes, I already know this, but that button should not be there because the direct user action will go through our application.

I already do this on the normal checkout page with the "woocommerce_order_button_html" hook. Something similar is needed for Blocks.

I also don't create the order, I still use the standard WooCommerce processes, but I do it based on the responses in our app. I do or don't send a request to wc_checkout.

**Comment by 0xBeycan** [comment]
@mikejolley 

We also cannot directly include html in content. Is there a way to do this? Or do I need to create it separately for the js side with React elements?

For example this is classic checkout.

![image](https://github.com/woocommerce/woocommerce/assets/50718965/57a80176-a667-46a2-a86c-46d1d01f0974)

This is blocks:

![image](https://github.com/woocommerce/woocommerce/assets/50718965/e6fe60a0-2dee-4d98-b8c8-ee90c022f022)

**Comment by opr** [comment]
Thanks @BeycanDeveloper for letting us know about your use-case!

> I believe there are ways to disable or block the button, but not hide it. We do not allow extensions to take control over order creation.

Kind of, but it also blocks other elements of the Checkout form too, e.g. the shipping selectors, so it's not really appropriate.

I _think_ this is a duplicate of https://github.com/woocommerce/woocommerce-blocks/discussions/9432 but that only involves replacing it with a custom component, not removing it entirely.

This is something we know we have to tackle but feel free to add a comment to that discussion outlining your use case @BeycanDeveloper !

**Comment by 0xBeycan** [comment]
@opr 

I think you really don't understand what I mean. I think PayPal knows how payment gateways work. It doesn't use any "place order" button. There is an html in the description section, that is, in the content section, you take action from there, you connect to PayPal and this is how the process works. This is exactly what I want to do, but the only problem is that while I can hide the "order place" button in classic checkout, I cannot do this for blocks.

Also, in my previous question I mentioned that it adds html as a text. How do I prevent this? I also think that the following source is very inadequate.

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#payment-methods---registerpaymentmethod-options-

**Comment by 0xBeycan** [comment]
Yes, normally the PayPal plugin hides the "order place" button in the classic checkout. But I guess they couldn't do that in Blocks.

![image](https://github.com/woocommerce/woocommerce/assets/50718965/3f33bc16-b8df-4718-92f9-41f7edf19643)

![image](https://github.com/woocommerce/woocommerce/assets/50718965/101f408d-c13a-4d34-8546-7eaa17018191)

**Comment by opr** [comment]
> Also, in my previous question I mentioned that it adds html as a text. How do I prevent this? I also think that the following source is very inadequate.
> 
> [woocommerce/woocommerce-blocks@trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#payment-methods---registerpaymentmethod-options-](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md?rgh-link-date=2024-01-23T12%3A36%3A36Z#payment-methods---registerpaymentmethod-options-)

Thanks for the feedback, please can you help us understand how the document is inadequate? The `content` prop is documented fairly clearly I thought, but if you have feedback on how we could improve that it would be great to hear.

> content (required)
This should be a React node that will output in the express payment method area when the block is rendered in the frontend. It will be cloned in the rendering process. When cloned, this React node will receive props passed in from the checkout payment method interface that will allow your component to interact with checkout data (more on [these props later](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes)).

> Yes, normally the PayPal plugin hides the "order place" button in the classic checkout. But I guess they couldn't do that in Blocks.

Exactly, which is why the discussion was started. It's a complex thing for us to implement this while ensuring the shopper experience is not affected.

> I think you really don't understand what I mean. I think PayPal knows how payment gateways work. It doesn't use any "place order" button. There is an html in the description section, that is, in the content section, you take action from there, you connect to PayPal and this is how the process works. This is exactly what I want to do, but the only problem is that while I can hide the "order place" button in classic checkout, I cannot do this for blocks.

I understand that you want to remove the "Place order" button and instead have your own "Place order" button (or equivalent) in the content area of your payment method.

I linked the discussion as it covers a similar topic though I concede your request is not exactly the same. That said, why is showing the button in the payment method better than replacing the actual "Place order" button with the one for your method? What if there are additional steps below the payments section that the shopper needs to complete, it'd require them to scroll down then scroll back up to complete payment. Seems like a continuous top-to-bottom flow is better than that no?

**Comment by 0xBeycan** [comment]
> Thanks for the feedback, please can you help us understand how the document is inadequate? The content prop is documented fairly clearly I thought, but if you have feedback on how we could improve that it would be great to hear.

Now when I use "registerPaymentMethod", I do not show the html in the description, that is, in the content section, it always appears as a string, and when I use "registerExpressPaymentMethod", no payment module like this does not appear.

So far, we have not received any feedback from any of our customers that they received an error in the express checkout process in the checkout section. Because I even read the source code of WooCommerce's checkout process line by line. I can expect that. I subscribed to the discussion you sent the link to, until this issue is resolved, our customers can use classic checkout or go to the "order-pay" page with the "order place" button and complete the payment process there. There is no rush for me right now.

However, my latest Binance Pay Gateway is a separate plugin that is independent of this topic, we add Blocks support to all our payment gateways. The user selects the currency they want to pay with a "select" element. We provide this html part with the "payment_fields" method in the gateway. However, in the Blocks section, it adds this as a string, not as html.

**Comment by 0xBeycan** [comment]
@opr The only thing I actually need urgently right now is to add the html added as a string in the picture below as a real html code.

![image](https://github.com/woocommerce/woocommerce/assets/50718965/ac9384b7-b8b2-417f-83ab-ec30de210e63)

**Comment by opr** [comment]
@BeycanDeveloper what is preventing you from creating this HTML as a React element?

**Comment by 0xBeycan** [comment]
@opr 

I figured out how to do this while going through the code for the PayPal plugin. I can now add html. 

The only problem now is to hide the "order place" button for my future goals. I can actually do this with css and javascript but I don't want to. I want to do it in a logical way that you guys offer.

![image](https://github.com/woocommerce/woocommerce/assets/50718965/93028fdf-3d3b-4b3a-a652-3a395d27ff10)

**Comment by opr** [comment]
> The only problem now is to hide the "order place" button for my future goals. I can actually do this with css and javascript but I don't want to. I want to do it in a logical way that you guys offer.

OK, we will continue to look into the replacing/removing the place order button functionality, I expect there will be updates to that discussion or a new one will be posted when we make a decision on how to proceed.

**Comment by ralucaStan** [comment]
@BeycanDeveloper It's not currently possible to hide programatically this button and we are collecting feedback on another discussion about replacing it with another component: https://github.com/woocommerce/woocommerce/discussions/45064. If that solution works for your case feel free to add input in the discussion, else you can open another one for removing the button. 

 I am going to close this ticket so that we can use discussions instead.
