### ISSUE TITLE
"Choose Products for Me" should show skeleton loading whenever button is pressed

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#43845]
When the `Choose products for me` button is pressed more than once, there should be a skeleton loading state _even if_ the products it suggests are exactly the same. 

I noticed that when I tried it in my Draft, Uncategorized product `Rainbow Sweater`, there wasn't any user feedback via a loading state, when I pressed the button multiple times. 

It looked like this -- nothing happened when I clicked the button:
![Screen Capture on 2024-01-22 at 17-22-00](https://github.com/woocommerce/woocommerce/assets/65582817/96f79356-146f-49b6-b509-3c3c6ad0f285)

Compared to when I clicked the button on a Published, Categorized product `Green Wool Sweater`, then the button behaved as I expected it to 👍 
![Screen Capture on 2024-01-22 at 17-22-29](https://github.com/woocommerce/woocommerce/assets/65582817/56de1089-6e61-4549-b8a7-aa1a7abaabbf)

**Comment by retrofox** [comment]
Addressed by this PR: https://github.com/woocommerce/woocommerce/pull/44053

When the client (the browser) does request the data, the app still shows the "loading" state with a random delay (2s - 200ms)
 
https://github.com/woocommerce/woocommerce/assets/77539/fbba2310-b5dc-4c8f-8706-f2afc4595d5b
