### ISSUE TITLE
Cross-reference HPOS and non-HPOS hook versions with each other

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#43846]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In [this discussion](https://github.com/woocommerce/woocommerce/discussions/43179) the author is not aware of there existing different hooks for the HPOS and non-HPOS cases (also see the forum discussion). A good first improvement would be to, in each comment, reference the other hook (e.g., by filename and method name). The author states:

> I think it would be best if they were added in this part as a message for the user explaining that if you have custom columns in WooCommerce orders it is necessary to make the adjustment to HPOS and perhaps an example of the use of the Hook and what parameters the function has.

**Comment by jorgeatorres** [comment]
Merging with #40699.
