### ISSUE TITLE
Order Success page lacks critical shipping and billing information

### ISSUE THREAD

**Issue by pierorocca** [woothemes/woocommerce#43987]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I understand that core recently plugged a security hole by requiring shoppers to be authenticated in order to access order details. That impacted guest checkout by requiring a guest shopper without an account to sign-in to view the order success page. 

My understanding was that a workaround was implemented so that a one time, short lived 10 minutes access token was provided to guest checkout shoppers, so they could confirm their order details and see the order success page.

Over the last few weeks I've seen the billing address disappear, and now the shipping address in gone too. While shoppers should get an email confirmation of the order, it cannot be solely relied upon as a receipt. [Per Baymard:](https://baymard.com/premium/guideline-collections/echwd2/596)

> The order confirmation page serves as a vital signal to users that their order has been successfully completed. While many participants in testing admitted that they only looked to the confirmation page to confirm their purchase had been submitted, relying instead on the order confirmation email as the full accounting of their order (see [#597](https://baymard.com/premium/guideline-collections/jg0yod/597)), we observed two smaller subgroups for whom this step and its information became highly important: those who are were especially meticulous (e.g., users who’ve just placed a very expensive order, and who typically will be more concerned about double-checking the order details at the confirmation step), and those who never received the order confirmation email, or receive it only after a long delay. For these users — as well as for those who are naturally more detail-oriented — confirmation pages that lack sufficient detail fail to provide key reference information on their order, increasing their anxiety and the need to contact the site’s customer service to recall key details.

### Expected behavior

Guest checkout shoppers, when the payment has been completed and the shoppers is redirected to the order success page, that page must contain the billing and shipping (when applicable) information. 

### Actual behavior

Guest checkout shoppers, when the payment has been completed and the shoppers is redirected to the order success page, that page does not contain the billing and shipping information. It is an incomplete receipt record.

### Steps to reproduce

1. Launch a test store with a short code theme, running WooPayments
2. Make a purchase as a guest checkout user
3. Successfully place an order
4. Observe that the order success page lack critical billing and shipping info, thus does not serve as a receipt record

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
@pierorocca what version of WooCommerce were you testing with? As of WooCommerce 8.5+ (via https://github.com/woocommerce/woocommerce-blocks/pull/12072).

**Comment by csmcneill** [comment]
Tested this with 8.4.0 / 8.5.1 and Storefront / Blockbase themes.

With Storefront, the shipping address, billing address, and email information is not shown on the `/checkout/order-received/` page — regardless of which version of Woo I am using.

With the Blockbase theme and 8.4.0, the shipping address is shown, but no billing address or email:

![840 typ](https://github.com/woocommerce/woocommerce/assets/82999806/e80d6ec9-5e8d-492d-95c0-151aa90cef9d)

With the Blockbase theme and 8.5.1, the shipping address, billing address, and email are shown:

![851 typ](https://github.com/woocommerce/woocommerce/assets/82999806/4c45fd3c-0652-41bf-9b31-573736834467)

**Comment by pmcpinto** [comment]
I'm closing this as we already have another one about this topic: #31990

**Comment by pierorocca** [comment]
Thanks @pmcpinto! I had looked for an open ticket before submitting and didn't find one with my search terms.

**Comment by pmcpinto** [comment]
Sometimes, it's hard to find tickets on the same topic. The same thing happened to me a few weeks ago :) Thanks for reporting this issue. It was a good reminder that we still need to address this on the shortcode.

**Comment by pierorocca** [comment]
Compared to other repositories, the sheer number of labels in core made it hard to search based on labels, which was my backup approach when "Thank you" and "Order success" didn't return a hit. And opening this ticket, it was daunting to try and figure out what label if any to apply to help facilitate triaging and/or automated workflows. Something we've been thinking about as we've moved over to using GH Project Boards.

**Comment by nerrad** [comment]
I think at least part of the problem is a lack of alignment and consistency around how we name these things... Order Confirmation, Thank you page, Order success etc. - I don't think GH labels help much with that part of the problem.

**Comment by pierorocca** [comment]
>  I don't think GH labels help much with that part of the problem.

Maybe not. A short list embedded in the instructions in new bug issues could serve as a sort of cheat sheet for the reporter?
