### ISSUE TITLE
Mini cart block second icon type have an html typo.

### ISSUE THREAD

**Issue by dlyr** [woothemes/woocommerce#44006]
Woocommerce 8.4, but still present in current trunk

I noticed an html code problem with the second mini-cart block icon, comes from
`fill="' . $icon_color . '""/>`
Should be
`fill="' . $icon_color . '"/>`

here 
https://github.com/woocommerce/woocommerce/blob/2acbb3d3fb7496bea7a6ad56cc25900430aa2e29/plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php#L440C9-L440C669

**Comment by mikejolley** [comment]
Well spotted. I'll check your PR. Thanks.
