### ISSUE TITLE
Since 8.5.1 in the admin console, going into a guest customer order is much slower

### ISSUE THREAD

**Issue by psHA5** [woothemes/woocommerce#44018]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since the upgrade to 8.5.1, when we are in the admin page - we see the list of orders. If we click into the order of a registered customer, the order page load is very fast. However, if we click into the order of a guest customer, the order page load is approximately 4-5 seconds.

### Expected behavior

Prior to this update, clicking into the orders of either type of customer was fast and the same.

### Actual behavior

if we click into the order of a guest customer, the order page load is approximately 4-5 seconds.

### Steps to reproduce

In admin, we go to Woocommerce - processing orders.
If we click into the order of a guest customer, it is significantly slower than previously - typically 4-5 seconds.
If we click into the order of a registered customer, it is very fast, almost instant.
We suspect it is the new functionality within the customer order showing  their history - presumably it is much harder to compute this since a guest customer doesn't have a customer id

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 8.5.1
REST API Version: ✔ 8.5.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 10 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 512 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1
WC Database Prefix: wp_
Total Database Size: 961.43MB
Database Data Size: 557.56MB
Database Index Size: 403.87MB
wp_woocommerce_sessions: Data: 10.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 10.52MB + Index: 5.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 71.61MB + Index: 65.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
legacy: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
orders: Data: 0.00MB + Index: 0.00MB + Engine
preorders: Data: 0.00MB + Index: 0.00MB + Engine
vw_duplicate_preorder_lines: Data: 0.00MB + Index: 0.00MB + Engine
vw_join: Data: 0.00MB + Index: 0.00MB + Engine
vw_shipped: Data: 0.00MB + Index: 0.00MB + Engine
wp_acfw_store_credits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 2.16MB + Index: 1.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 7.66MB + Index: 6.81MB + Engine MyISAM
wp_aioseo_notifications: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_aioseo_posts: Data: 1.20MB + Index: 0.10MB + Engine MyISAM
wp_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_atum_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_atum_product_data: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 79.61MB + Index: 54.13MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_entries_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_hustle_modules_meta: Data: 0.16MB + Index: 0.01MB + Engine MyISAM
wp_hustle_tracking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 6.47MB + Index: 0.27MB + Engine InnoDB
wp_postmeta: Data: 273.84MB + Index: 213.58MB + Engine InnoDB
wp_posts: Data: 23.55MB + Index: 13.00MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Catalogues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Catalogue_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Custom_Fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Fields_Meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Item_Images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_SubCategories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Tagged_Items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Tag_Groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_UPCP_Videos: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 30.56MB + Index: 24.05MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.91MB + Engine InnoDB
wp_vtprd_purchase_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtprd_purchase_log_product: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtprd_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wccs_conditions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wccs_condition_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_credit_note_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_packing_slip_number: Data: 1.24MB + Index: 0.71MB + Engine MyISAM
wp_wcpdf_proforma_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 1.30MB + Index: 1.10MB + Engine MyISAM
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 8.79MB + Index: 7.24MB + Engine MyISAM
wp_wc_order_stats: Data: 4.01MB + Index: 2.61MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 2.19MB + Index: 0.87MB + Engine MyISAM
wp_wdp_order_items: Data: 3.76MB + Index: 2.98MB + Engine MyISAM
wp_wdp_persistent_rules_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdp_rules: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.99MB + Index: 0.75MB + Engine MyISAM
wp_wfblocks7: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_wfconfig: Data: 1.96MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 4.53MB + Index: 0.53MB + Engine MyISAM
wp_wfhits: Data: 3.02MB + Index: 0.91MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 3.29MB + Index: 0.17MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.21MB + Index: 0.32MB + Engine MyISAM
wp_wflocs: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wflogins: Data: 0.43MB + Index: 0.09MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfreversecache: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfsecurityevents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.14MB + Index: 0.06MB + Engine MyISAM
wp_wftrafficrates: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wfwaffailures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_preoder_split: Data: 1.76MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_preorder_release_prereq: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_preorder_release_prereq_order: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_preorder_split_prereq: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_reporting_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

acf-field: 54
acf-field-group: 8
attachment: 1096
custom_css: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
movie: 482
nav_menu_item: 5
o-discount: 1
o-list: 1
page: 29
post: 216
product: 509
revision: 702
shop_coupon: 3
shop_order: 54116
shop_order_refund: 937
vtprd-rule: 1
woo_discount: 1
woo_discount_cart: 1
wpcf7_contact_form: 1
ywdpd_discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

ACF: Better Search: by Mateusz Gbiorczyk – 4.2.0
Additional Order Filters for WooCommerce: by Anton Bond – 1.12
Admin Menu Editor: by Janis Elsts – 1.12.1
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.9.2
Advanced Custom Fields PRO: by WP Engine – 6.2.5
Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.6.0
Contact Form 7 iContact Extension: by Renzo Johnson – 0.5.25
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.8.6
WooCommerce Discontinued Products: by Leon @ 211J – 1.1.5
GDPR Cookie Compliance: by Moove Agency – 4.13.0
reCAPTCHA for WooCommerce: by Elliot Sowersby
RelyWP – 1.3.2

Responsive Lightbox & Gallery: by dFactory – 2.4.6
WooCommerce WorldPay Gateway: by Andrew Benbow – 5.0.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.6
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 2.2.11
WooCommerce: by Automattic – 8.5.1
Wordfence Security: by Wordfence – 7.11.1
Hustle: by WPMU DEV – 7.8.3
WP Crontrol: by John Blackbourn & contributors – 1.16.1
WP Mail SMTP: by WP Mail SMTP – 3.11.1
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.9
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.13.2

YITH Pre-Order for WooCommerce Premium: by YITH – 2.22.0

### Inactive Plugins (6) ###

LiteSpeed Cache: by LiteSpeed Technologies – 6.0.0.1
Login No Captcha reCAPTCHA (Google): by Robert Peake and Contributors – 1.7.2
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.3.3
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce Social Login: by SkyVerge – 2.11.0
Worldpay Online Payments: by Worldpay
WooCommerce
Andrew Benbow – 2.0.3

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #36 - /shop/
Basket: #37 - /basket/
Checkout: #38 - /checkout/
My account: #39 - /my-account/
Terms and conditions: #9 - /terms-of-use/

### Theme ###

Name: E-2018
Version: (update to version 0 is available)
Author URL: http://twitter.com/duckbox
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: E-2018/woocommerce/cart/cart.php
E-2018/woocommerce/checkout/form-billing.php
E-2018/woocommerce/checkout/terms.php
E-2018/woocommerce/emails/customer-completed-order.php
E-2018/woocommerce/emails/customer-invoice.php
E-2018/woocommerce/emails/customer-new-account.php
E-2018/woocommerce/emails/customer-note.php
E-2018/woocommerce/emails/customer-on-hold-order.php
E-2018/woocommerce/emails/customer-processing-order.php
E-2018/woocommerce/emails/customer-reset-password.php
E-2018/woocommerce/emails/email-header.php
E-2018/woocommerce/emails/email-styles.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-24 11:51:17 +00:00
Options: ✔
Notes: 43
Onboarding: completed

### Action Scheduler ###

Complete: 8,775
Oldest: 2023-12-23 20:09:39 +0000
Newest: 2024-01-23 19:42:48 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 2
Oldest: 2024-01-24 09:01:49 +0000
Newest: 2024-01-24 09:01:50 +0000

### Status report information ###

Generated at: 2024-01-23 20:02:07 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psHA5** [comment]
Disabling Order Attribution, a new feature with 8.5, in Settings made a significant positive difference to performance! Closing  issue

**Comment by lkraav** [comment]
> Disabling Order Attribution, a new feature with 8.5, in Settings made a significant positive difference to performance! Closing issue

With the number of web-braking bugs found by today, OA feature seems to have single-handedly made 8.5 the most fragile release in months, if not a few years.

Woo team definitely has things to discuss in 8.5 post-mortem.

**Comment by E1NSER** [comment]
@psHA5 What about the performance on a huge amout of orders? Disabling the new feature is not the best solution imho

**Comment by psHA5** [comment]
You need to test what works for you
