### ISSUE TITLE
Add/edit coupon codes applied to pre-existing orders

### ISSUE THREAD

**Issue by tenkabuto** [woothemes/woocommerce#4404]
At my company, we use coupons in a manner similar to Tags (described below), so having the ability to add/edit coupons on pre-existing orders would help very much.

"Tags": Customers apply $0 Discount coupons that correspond to a certain non-profit, then we later add up the amounts of all orders with the corresponding coupon and give 50% of the total to the non-profit.

**Comment by mikejolley** [comment]
https://trello.com/c/OPEAzgIw/4-allow-coupons-to-be-added-edited-from-orders-with-discount-calc-4404

**Comment by mikejolley** [comment]
@claudiosmweb suggested adding an abstraction layer to handle discount calculation for CART and backend.

**Comment by mikejolley** [comment]
Closed in favour of #11889
