### ISSUE TITLE
[CYS - Core] Handling the Font Picker when the Font Library isn't available

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#44074]
The Font Picker will be empowered by the Font Library API thanks to #44004  The Font Library will be available on WordPress 6.5 and on the WordPress site with the Gutenberg version that includes the Font Library API. The scenarios are:
- WordPress 6.5 - Font Library available
- WordPress 6.4 + Gutenberg - Font Library available
- WordPress 6.4 without Gutenberg - Font Library not available

When the Font Library isn't available, the default font of the theme will be used. The Font Picker should look like this:

![image](https://github.com/woocommerce/woocommerce/assets/4463174/9594be8a-6fc3-49f8-858c-652d3fbeb9cb)

Instead of the `Inter` font, we have to render the default font of the used theme.

**NB: The copy is still WIP.**

**Comment by nefeline** [comment]
> The default font of the theme will be used

FYI, the TT4 theme has five different fonts; we might need to come up with at least one pairing based on 2 of these options: https://wordpress.org/documentation/article/twenty-twenty-four/#design-specifications

cc: @verofasulo

**Comment by nefeline** [comment]
> WordPress 6.4 without Gutenberg - Font Library not available

This scenario is also valid for when Gutenberg is installed but outdated. FYI, currently, in this scenario the following PHP notice is triggered:

`PHP Notice: Undefined index: paged in /Local Sites/woo/app/public/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php on line 394`

We should ensure this notice is cleared out too.

**Comment by gigitux** [comment]
Closed in favor of #44187.
