### ISSUE TITLE
Debug notice when updating to 8.5.2: Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by henrywright** [woothemes/woocommerce#44103]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

> Deprecated: Automatic conversion of false to array is deprecated in wp-content/plugins/woocommerce/src/Admin/DataSourcePoller.php on line 138

### Expected behavior

I shouldn't get a debug notice appear.

### Actual behavior

I updated to version 8.5.2 and on the wp-admin/plugin-install.php page I got a debug notice. I then navigated away from the page. When I visited the page again I no longer get the message.

### Steps to reproduce

1. Install 8.5.2

### WordPress Environment

Local

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adrianduffell** [comment]
This was fixed in https://github.com/woocommerce/woocommerce/pull/44384 and now released in WooCommerce 8.7.

**Comment by henrywright** [comment]
Thank you @adrianduffell
