### ISSUE TITLE
When "Shipping locations" and "Default customer location" are disabled, the "Country" combobox in Checkout's billing address is replaced by a text entry field that can sometimes fail to validate and block the customer

### ISSUE THREAD

**Issue by nekohayo** [woothemes/woocommerce#44138]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Mostly as the title says. A non-profit I'm volunteering for contacted me because their customers suddenly could not make purchases/transactions anymore. They sent me this screenshot (more details/explanation below):

<img width="532" alt="2024-01-24" src="https://github.com/woocommerce/woocommerce/assets/479401/0a22505b-7e62-4f46-b7ab-dd8409736707">

### Expected behavior

The Country field should:
* Not fail to validate in this situation when the combination of settings (as detailed further below) makes it so that only a single country is possible
* Probably remain a comboboxentry at all times, not convert to a plain textentry
* Probably not appear at all when the combination of settings (as detailed further below) makes it so that only a single country is possible

### Actual behavior

I could reproduce the problem myself too, and it looked like this:

![Screenshot from 2024-01-27 - the bug, ajusté](https://github.com/woocommerce/woocommerce/assets/479401/552b5dc5-0976-41b8-8905-b298c2d01b2e)

As you can see in the above screenshot, the Country field (in the billing address section of the Checkout page, running on the WordPress Gutenberg TwentyTwentyThree theme) is somehow a text entry field instead of a comboboxentry, and in this particular case it blocked the user from doing a checkout because it refuses the blank input, or any input (it will clear any text you write in there).

### Steps to reproduce

While investigating, I determined this to be caused by a specific combination of three settings in `admin.php?page=wc-settings&tab=general`:

* Selling locations: **"Sell to specific countries",** and specify only one country (ex: "Canada")
* Shipping locations: **"Disable shipping & shipping calculations"** (because in my case, no shipping is involved, it's a non-profit that only offers services to the general public, so the notion of "shipping" made no sense)
* Default customer location: **"No location by default"** (I think this was the default setting? In any case, it shouldn't have mattered because only one country was possible)

When all three settings are set this way, in _some_ unknown circumstances, the form can block as shown in the screenshot above. However, once you change those settings to something else (as I was doing in the screenshots further below), the form starts working without blocking again, and then even if you re-set those settings to this combo of values that originally triggered the bug... then the bug doesn't happen anymore, as if there was an erroneous database entry that got overwritten by resetting the trio of settings back and forth (so unfortunately that means I can not reproduce the bug consistently after reporting this). In any case, it shouldn't block, or the UI should force at least one or two of those settings to be valid in relationship with the others.

This is how I made it work, in phases (the settings are on the left, and the results are on the right).

First, again, this was the problematic combination and its consequences:

![Screenshot from 2024-01-27 - bug report 1 - faulty status](https://github.com/woocommerce/woocommerce/assets/479401/6c2b19a8-89a5-4be1-990d-7f7e54b044d1)

Then, I changed "Default customer location" to "Shop country/region", which made the resulting Checkout form not block anymore, but it was still a weird result because it was prepopulating the "Province" (sub-state) section (shown here with "AB") but not the country (Pays/Région remained blank, not a combobox, and would still clear anything you type in there):

![Screenshot from 2024-01-27 - bug report 2 - non-blocking but strange status](https://github.com/woocommerce/woocommerce/assets/479401/64db0f8a-8fcb-4182-bcfa-7c6e9f9a002c)

Then, I changed "Shipping locations" to "Ship to all countries you sell to", and then suddenly everything worked:
* It was prepopulating the Country ("Canada") too, not just the province ("AB / Alberta" or others)
* It no longer failed form validation
* It was using comboboxentry widgets again, instead of text entry widgets (as you can see in the screenshot below)

![Screenshot from 2024-01-27 - bug report 3 - corrected status where comboboxes are shown again](https://github.com/woocommerce/woocommerce/assets/479401/56d81054-bdba-4601-94a5-e6deb5bd3f45)

…but this shouldn't have failed in the first place. If the shop only serves one country and has no shipping, the Checkout page's billing address form shouldn't transform the Country comboboxentry to a text entry, and it should not block/fail on the value of that Country field.

At least I had a workaround, but it took a lot of digging and troubleshooting on my end, and I think bulletproofing your code's logic here would be beneficial to WooCommerce's customers, avoiding a lot of confusion. I hope this bug report helps.

### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.21-MariaDB-0+deb11u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 141.92MB
Database Data Size: 130.55MB
Database Index Size: 11.37MB
wp_woocommerce_sessions: Data: 1.14MB + Index: 0.06MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.19MB + Index: 0.13MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 1.56MB + Index: 1.09MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.22MB + Index: 0.14MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.17MB + Index: 0.15MB + Engine MyISAM
wp_ai1ec_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ai1ec_event_category_colors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ai1ec_event_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ai1ec_event_instances: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 1.23MB + Index: 0.50MB + Engine MyISAM
wp_contact_form_7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cpappbk_forms: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_cpappbk_messages: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_email_log: Data: 56.89MB + Index: 0.06MB + Engine MyISAM
wp_eo_events: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_eo_venuemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fsevents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fsevents_cats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_optimizer: Data: 8.55MB + Index: 0.17MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_menuitems: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_menus: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mystickymenu_contact_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 7.44MB + Index: 0.14MB + Engine MyISAM
wp_p2p: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_p2pmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 13.60MB + Index: 5.30MB + Engine MyISAM
wp_posts: Data: 31.69MB + Index: 1.21MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tec_events: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_tec_occurrences: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.08MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.71MB + Index: 0.42MB + Engine MyISAM
wp_users: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.24MB + Index: 0.17MB + Engine MyISAM
wp_wfBlocks7: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wp_wfConfig: Data: 1.08MB + Index: 0.02MB + Engine MyISAM
wp_wfCrawlers: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfHits: Data: 1.12MB + Index: 0.21MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfKnownFileList: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfLogins: Data: 0.34MB + Index: 0.08MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSecurityEvents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfWafFailures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wp_rp_tags: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email: Data: 2.65MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.20MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

acf: 1
attachment: 1093
audiotheme_archive: 3
audiotheme_gig: 1
custom_css: 2
customize_changeset: 1
ec-template: 1
event: 69
mc4wp-form: 1
ml-slide: 31
ml-slider: 55
nav_menu_item: 77
op-set: 1
page: 52
post: 127
product: 61
revision: 4680
shop_coupon: 3
shop_order: 1517
shop_order_refund: 161
ticket-meta-fieldset: 3
tinymcetemplates: 2
tribe_events: 211
tribe_organizer: 25
tribe_tpp_orders: 1
tribe_venue: 289
tribe_wooticket: 1357
wp_block: 15
wp_global_styles: 1
wp_navigation: 5
wp_template: 2888
wp_template_part: 5
wpcf7_contact_form: 2
wpplugin_don_button: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Block Visibility: by Nick Diego – 3.3.0
Debug Bar: by wordpressdotorg – 1.1.4
Disk Usage Sunburst: by raidboxes.io – 1.1.8
Potent Donations for WooCommerce: by WP Zone – 1.1.11
Email Log: by Sudar – 2.4.8
Enable Media Replace: by ShortPixel – 4.1.5
Event Tickets: by The Events Calendar – 5.8.0
Imsanity: by Exactly WWW – 2.8.3
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.11
Media Library File Size: by SS88 LLC – 1.6.1
MetaSlider: by MetaSlider – 3.60.1
Meta pixel for WordPress: by Facebook – 3.0.14
Product Open Pricing (Name Your Price) for WooCommerce: by WP Wham – 1.7.1
Simple Custom CSS: by John Regan – 4.0.6
Sticky Block: by Senff – 1.11
The Events Calendar: by The Events Calendar – 6.3.1
Use Any Font: by Dnesscarkey – 6.3.05
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.13
WooPayments: by Automattic – 7.1.0
WooCommerce: by Automattic – 8.5.2
Wordfence Security: by Wordfence – 7.11.1
Yoast SEO: by Team Yoast – 21.9.1
WP Mail SMTP: by WP Mail SMTP – 3.11.1
Connect Matomo: by André Bräkling – 1.0.30
WP Super Cache: by Automattic – 1.11.0

### Inactive Plugins (11) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Appointment Hour Booking: by CodePeople – 1.4.49
Contact Form 7: by Takayuki Miyoshi – 5.8.6
Custom Fonts: by Brainstorm Force – 2.1.3
Extra product options For WooCommerce | Custom Product Addons and Fields: by ThemeHigh – 3.2.4
Fonts Plugin | Google Fonts Typography: by Fonts Plugin – 3.5.1
Media Deduper: by Cornershop Creative – 1.5.5
Memory Meter: by 99w – 1.3.5
Query Monitor: by John Blackbourn – 3.15.0
Smush: by WPMU DEV – 3.15.4
The Events Calendar: Remove QR Codes: by Modern Tribe – 0.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: donation (donation)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #16486 - /boutique/
Cart: #16487 - /panier/
Checkout: #16488 - /commande/
My account: #16489 - /mon-compte/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.1.0
Connected to WPCOM: Yes
WPCOM Blog ID: 218834944
Account ID: acct_1N5xPmCBeF1gIKz1
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Product Open Pricing Settings ###

Product Open Pricing (Name Your Price): yes
Frontend template: Name Your Price %open_price_input% %currency_symbol%
Input field position: woocommerce_before_add_to_cart_button
Position priority.: 9999
Hide price: yes
Disable quantity selector: yes
Display on loop: no
Frontend loop template: Name Your Price %open_price_input% %currency_symbol%
Input field loop position: woocommerce_after_shop_loop_item
Position priority.: 9
Hide price: yes
Input style: width:75px;text-align:center;
Input pattern: 
Enable step ticker: yes
Price step: 1
Force number of decimals: no
Number of decimals.: 2
Add To Cart button text: 
Message on empty price: Indiquez le montant de votre don
Message on price too low: Veuillez respecter le montant de don minimum
Message on price too high: Veuillez respecter le montant de don maximum
Add "Open Pricing" column: no
Fix mini cart: no

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-27 21:23:50 -05:00
Options: ✔
Notes: 121
Onboarding: completed

### Action Scheduler ###

Canceled: 37
Oldest: 2023-12-28 16:30:12 -0500
Newest: 2024-01-23 20:47:52 -0500

Complete: 682
Oldest: 2023-12-27 14:52:27 -0500
Newest: 2024-01-27 13:14:10 -0500

Failed: 7
Oldest: 2023-05-01 17:24:15 -0400
Newest: 2023-09-09 14:17:49 -0400

Pending: 1
Oldest: 2024-01-27 15:25:54 -0500
Newest: 2024-01-27 15:25:54 -0500

### Status report information ###

Generated at: 2024-01-27 13:48:01 -05:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nekohayo** [comment]
Additionally, I am told now by the non-profit staffers that the problem flew under the radar in previous months, because they only noticed it this month and it happened "Sometimes, not all the time… but it started happening increasingly often recently, this week this seemed like many visitors were blocked by this"... I don't know if that anecdotal information helps, but if true, there might be another component to triggering this in practice, maybe there's a race condition somewhere in the code? Or maybe the shop users that were not encountering problems were existing users in the system? Just throwing out potential hypotheses here.

**Comment by daniyalahmadk** [comment]
7620127-zen

**Comment by nielslange** [comment]
Hello @nekohayo and @daniyalahmadk 👋

@opr just created a fix for this issue in #44388. We hope that the fix will be shipped with the next patch release, WooCommerce 8.5.3. 

Meanwhile, could you try if the following workaround is working for you:

1. Set this option: WooCommerce → Settings → Shipping location(s): Ship to specific countries only
2. In the next box: Ship to specific countries set the countries you want to sell to.
3. Save the settings.
4.  Set this option: WooCommerce → Settings → Shipping location(s): Disable shipping & shipping calculations
5. The countries you set in step 2 will now show in the billing form.

**Comment by stoltzrx** [comment]
7712794-zen

**Comment by nielslange** [comment]
> 7712794-zen

@stoltzrx Have you suggested the workaround as mentioned in https://github.com/woocommerce/woocommerce/issues/44138#issuecomment-1929599551?

**Comment by stoltzrx** [comment]
> > 7712794-zen
> 
> @stoltzrx Have you suggested the workaround as mentioned in [#44138 (comment)](https://github.com/woocommerce/woocommerce/issues/44138#issuecomment-1929599551)?

@nielslange - Yes, and the merchant has confirmed that the workaround is working for them.

**Comment by ralucaStan** [comment]
I am closing this as a fix for this will land this week in WooCommerce 8.6. Keep an eye on https://developer.woo.com/blog/ for the release announcement.
