### ISSUE TITLE
[Enhancement]: Change Product Image block to use some of the Cover block properties.

### ISSUE THREAD

**Issue by paaljoachim** [woothemes/woocommerce#44146]
### Describe the solution you'd like

The Query Loop in Gutenberg. Usually contains a featured image block. Changing this to a Cover block gives the user the chance to add a block on top of the Cover block and use the default placement to add what is needed.
I made a tutorial here: https://easywebdesigntutorials.com/how-to-add-category-labels-on-top-of-the-featured-images-in-the-post-preview-query-loop-in-gutenberg/

That means adjusting the Product Image block to contain Cover block properties and defining the block to automatically use the featured image (just like the Cover block). As it gives the opportunity for the user to add blocks onto the Cover block / Product Image block and place these as I have done in the tutorial.

@Marc-pi @gigitux @Aljullu 

### Describe alternatives you've considered

Not sure how customizable the Sale label on top of the Product Image is....

### Additional context

I came across this comment in the WooCommerce Facebook group:
https://www.facebook.com/groups/1645148442367656?multi_permalinks=3751862241696255&hoisted_section_header_type=recently_seen

It said:
How would you fix this Energy Labeling on the WooCommerce products? An example from the electric shop. no under.
The size and height of the energy label MUST be higher/higher than the price and visible both when browsing and inside a single product.
Tips? Is there a WooCommerce default or a plugin to show it? The state has started handing out daily fines for not having this, so this needs to be fixed as soon as possible.

--> It made me think of the tutorial I made in relation to the Query Loop in the Site Editor which would be helpful to also have added to the Query Loop in WooCommerce.

**Comment by Aljullu** [comment]
Thanks for opening this issue, @paaljoachim! Currently, it's possible to add the Cover block inside the Product Collection block, and set it to display the _Featured Image_ of products. This allows adding any blocks "on top" of the product image:

![image](https://github.com/woocommerce/woocommerce/assets/3616980/bb28c5d2-756d-4386-82bf-5cdfc9e00315)

Do you think this workflow is not enough or it could be improved?

**Comment by paaljoachim** [comment]
Hey @Aljullu 

Of course! I made a mistake while exploring but it is the same process as the Query Loop!
Thank you!

I am exploring and the following showed up.

![Screenshot 2024-01-29 at 13 11 56](https://github.com/woocommerce/woocommerce/assets/5323259/713ed965-0ba0-4b89-b96d-29307061e455)

TypeError: Cannot read properties of null (reading 'addEventListener')
    at https://bluewinddesign.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=18effea5fc56a2b44e5e:50:4153
    at https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:23334
    at K (https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:26611)
    at https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:27100
    at K (https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:26611)
    at https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:27100
    at K (https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:26611)
    at https://bluewinddesign.com/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6d15dcf0451c750ce999:1:27100
    at Ar (https://bluewinddesign.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:73517)
    at el (https://bluewinddesign.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:81535)

---

I have never seen the above error before. I might just have to create a Github Gutenberg issue for it. Something happening between Gutenberg and WooCommerce.

Reloading the Site Editor (Product Catalog template)

I am continuing to explore.
I believe the issue as it is can be closed. I will need to add the error to a bug issue. Closing for now.

**Comment by Aljullu** [comment]
Huh, that's weird. Are you testing with a released version of Gutenberg or `trunk`?

**Comment by paaljoachim** [comment]
Newest version of Gutenberg. 17.5.2
WordPress 6.4.2

**Comment by Aljullu** [comment]
Thanks! I wasn't able to reproduce, unfortunately, but I will keep an eye in case we get more reports like that. And if you happen to figure out what are the steps to reproduce, please let us know!

**Comment by paaljoachim** [comment]
Hey @Aljullu Albert

I just reopened this issue.

Some brainstorming...

What if the Featured Image block in the Product Collection block was switched out with...
the Cover block that contained an inner top middle Sales badge block. The Sales badge block would contain Image block properties along with the Sales badge settings.

Adding a Sales Badge block could then contain the default Sales image that can be switched out with another sales badge the users decides on.
Sales Badge block could be aligned different based on the grid placement in the Cover block.

**Comment by Aljullu** [comment]
Thanks for all the feedback and ideas, @paaljoachim! @kmanijak just created a new issue to focus specifically on doing an exploration to replace the Product Image with a Cover block here: https://github.com/woocommerce/woocommerce/issues/44387.

Does it sound good if we close this issue in favor of the newer one?

**Comment by paaljoachim** [comment]
That is awesome! I am glad to see the suggestion got traction! As it seems like an obvious win situation. User can switch the sales badge to any image and they can then also adjust the placement. I am happy to close this issue and focus on the other issue.
