### ISSUE TITLE
Missing HPOS placeholder posts not handled gracefully

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#44177]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When purging the HPOS placeholder posts (post type `shop_order_placehold`) and then visiting `/wp-admin/post.php?post=123&action=edit`, instead of the redirect to the HPOS order `/wp-admin/admin.php?page=wc-orders&action=edit&id=123` WooCommerce fails with a 500 server error. (`123` being an order ID.)

_(Note that purging these posts is not officially supported yet. Once it is, WooCommerce will provide a user interface for purging this data. However, WooCommerce should handle the absence of these posts more gracefully.)_

**Comment by jorgeatorres** [comment]
Relates to #42746, where placeholder posts deleted (even by our own code) can then result in some issues.
