### ISSUE TITLE
[CYS on Core] Conditionally change the default fonts available based on user consent.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#44187]
Currently, on WooCommerce, whenever the user accepts the initial terms, this information is saved in the database as an option, the [`'woocommerce_allow_tracking'`](https://github.com/woocommerce/woocommerce/blob/4df15fe948d8a5f85b68879e57652772bf013425/plugins/woocommerce-admin/client/core-profiler/index.tsx#L209).

## Fonts

Currently, two main factors may influence the number of default fonts available to the users on core:

- Whether the user did accept the initial terms of service
- Whether the user has the latest version of WordPress - 6.5, which will be the newest version of WP by the time this feature is released on Woo - or the newest version of the Gutenberg Plugin installed. Originally reported by @gigitux on https://github.com/woocommerce/woocommerce/issues/44074

Based on a previous internal discussion ( p1706181065907309/1706115718.528339-slack-C053716F2H2 ), we have established that whenever the user did not accept the terms, [only the default fonts available on TT4](https://wordpress.org/documentation/article/twenty-twenty-four/#design-specifications) should be displayed, with the following pairing being selected by @verofasulo : 

> Cardo Font for headlines.
> Sans-serif System font for paragraphs.

Considering these, we have the following scenarios:

| Scenario  | Displayed copy on the sidebar  |  Available font pairings  |
|---|---|---|
| User gave consent but has an outdated version of WordPress/Gutenberg or Gutenberg is not installed  | "Upgrade to the latest version of WordPress or install Gutenberg to get access to more fonts" (Figma: FlPl7fHaGv9mpu8Nfl0joH-fi-1553_39763)  | **Cardo Font** for headlines. **Sans-serif System** font for paragraphs.  |
| User did not give us consent and also has an outdated version of WordPress |  Upgrade to the [latest version of WordPress](link) and [opt in to usage tracking](link) to get access to more fonts. |  **Cardo Font** for headlines. **Sans-serif System** font for paragraphs.  |
| User did not give us consent and has the latest version of WP/GB installed | Opt in to [usage tracking](link) to get access to more fonts. | **Cardo Font** for headlines. **Sans-serif System** font for paragraphs.  |
| User gave consent and has the latest version of WordPress and/or GB plugin installed | N/A | All font pairings as currently available on WooExpress  |

Figma Design : FlPl7fHaGv9mpu8Nfl0joH-fi-1678_46869

## Opt-in to usage tracking

Whenever the user clicks on "opt-in to usage tracking", the following modal should be displayed:

<img width="666" alt="Screenshot 2024-02-01 at 12 02 10" src="https://github.com/woocommerce/woocommerce/assets/15730971/1efd133b-76d2-469b-ac16-7bdec45dc15a">

Whenever the user clicks on the "Opt in" button, the [`'woocommerce_allow_tracking'`](https://github.com/woocommerce/woocommerce/blob/4df15fe948d8a5f85b68879e57652772bf013425/plugins/woocommerce-admin/client/core-profiler/index.tsx#L209) option should be updated in the database to 'yes'

<img width="905" alt="Screenshot 2024-02-01 at 12 03 48" src="https://github.com/woocommerce/woocommerce/assets/15730971/45b4672f-7f1a-454f-a815-e8e841a58bef">

**Comment by nefeline** [comment]
@laurajohnsonwoo, could you please review and help us define the copy for the two scenarios that are still pending?

@verofasulo, could you please review and confirm if the defined font pairings make sense and are aligned with the expected designs? Considering that TT4 comes with [five different fonts available](https://wordpress.org/documentation/article/twenty-twenty-four/#design-specifications), should we consider having more pairing options available instead of just one font pairing (Cardo Font for headlines & Sans-serif System font for paragraphs.)?

cc: @SamratBiswas1 @danielwrobert @gigitux @albarin in case there's anything, in particular, you believe is missing and should be taken into consideration here as well.

**Comment by verofasulo** [comment]
> could you please review and help us define the copy for the two scenarios that are still pending?

@nefeline I guess you wanted to tag @lauroraa, right? 😅

You can find the designs with the updated copy in [this Figma file](https://www.figma.com/file/FlPl7fHaGv9mpu8Nfl0joH/CYS-with-Assembler---Core?type=design&node-id=1678-46869&mode=design&t=1KRhQXTjVcGhOeXb-4). Let us know if you have any further questions.

> @verofasulo, could you please review and confirm if the defined font pairings make sense and are aligned with the expected designs? Considering that TT4 comes with [five different fonts available](https://wordpress.org/documentation/article/twenty-twenty-four/#design-specifications), should we consider having more pairing options available instead of just one font pairing (Cardo Font for headlines & Sans-serif System font for paragraphs.)?

If it's possible, of course. The designs display only one font pairing, as that's the bare minimum, but if we can have more font combinations by default, it's great. Re TT4, do we already have some default combinations as per the Cardo & Sans-serif System, or should we create them?

**Comment by nefeline** [comment]
> I guess you wanted to tag @lauroraa, right? 😅

Yes :) She was already aware, though, as I pinged her prior to the creation of this issue on GH.

> You can find the designs with the updated copy in FlPl7fHaGv9mpu8Nfl0joH-fi-1678_46869. Let us know if you have any further questions.

Thanks @verofasulo, issue has been updated to account for the new copy and designs.

> If it's possible, of course. The designs display only one font pairing, as that's the bare minimum, but if we can have more font combinations by default, it's great. Re TT4, do we already have some default combinations as per the Cardo & Sans-serif System, or should we create them?

There are a few predefined styles that include font families, such as `Jost` for the heading and `Instrument Sans` for the body: https://github.com/WordPress/twentytwentyfour/blob/trunk/styles/ember.json#L123-L146

Each style has its combination of fonts for the header and the body (as in the example shared above); the complete list of styles is available here, in case you wanna use those combinations as inspiration:

https://github.com/WordPress/twentytwentyfour/tree/trunk/styles
