### ISSUE TITLE
Create means to clean up wireit cache

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#44203]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
The wireit cache in the monorepo can grow to a really large size. We've seen reports of hundreds of gigs. We should create a mechanism to clean up this cache.

See https://github.com/google/wireit/issues/71

**Comment by kalessil** [comment]
Related:
- https://github.com/woocommerce/woocommerce/pull/53241 (wireit cache retention 28 days)
- https://github.com/woocommerce/woocommerce/pull/53503 (wireit cache retention 14 days + build tweaks)
- https://github.com/woocommerce/woocommerce/pull/53509 (refined cleanup approach)

**Comment by kalessil** [comment]
Closing the issue as we have a cleanup solution in place. A possible follow-up is to reduce the cache folders retention period to 7 days.
