### ISSUE TITLE
At checkout (Woocommerce) the Stripe payment methodes are not working

### ISSUE THREAD

**Issue by BConscious** [woothemes/woocommerce#44217]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Stripe payment methodes are popping up however immediately dissapear again. Only remaining payment option is payment via creditcard. 

Contacted Stripe with call ref. number: 11146760. They requested to contact Woocommerce support for this one as they had no issues on their side.
[Recoding Checkout page error_2024-01-31 095749.zip](https://github.com/woocommerce/woocommerce/files/14109433/Recoding.Checkout.page.error_2024-01-31.095749.zip)

### Expected behavior

That all payment options stay visible and usable for our consumers.

### Actual behavior

The pop-up of all payment options appear (slightly) and immediately dissapear. Only remaining payment option is credit card. See previous added video snapshot.

### Steps to reproduce

1. Go to https://bconscious.nl
2. Click on "Ik wil ze bestellen"
3. Choose a product
4. Click on "Toevoegen aan winkelwagen"
5. Click on "Afrekenen" in the chart pop-up, once redirected to the checkout page you see the pop up appearing with all the normal payment options like Ideal, BanContact, Sepa etc. and immediately dissapearing and credit card option is the only remaining payment option.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bconscious.nl
Site address (URL): https://bconscious.nl
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 8.1.14
PHP Post Max Size: 2 GB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.4.27-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Totale database grootte: 76.24MB
Database gegevens grootte: 59.87MB
Database index grootte: 16.37MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.31MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 13.50MB + Index: 6.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 3.52MB + Index: 0.53MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.13MB + Index: 0.23MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.06MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 9.36MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 2.89MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.22MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.48MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trustindex_google_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 286
custom-css-js: 15
customize_changeset: 1
itsec-dash-card: 8
itsec-dashboard: 1
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 135
nf_sub: 31
oembed_cache: 1
page: 19
portfolio: 6
post: 13
product: 7
product_variation: 62
revision: 120
shop_coupon: 10
shop_order: 294
shop_order_refund: 9
wp_global_styles: 1
wp_navigation: 1
wpclv: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

ManageWP - Worker: door GoDaddy – 4.9.18
Add-on WooCommerce MailPoet 3: door Tikweb – 1.1.9
Autoptimize: door Frank Goossens (futtta) – 3.1.10
Avahojuza: door Lane Neville – 2.7.6
AVIF Support [GrandPlugins]: door GrandPlugins – 1.0.5
CookieYes | GDPR Cookie Consent: door CookieYes – 3.1.7
Simple Custom CSS and JS: door SilkyPress.com – 3.45
DHL eCommerce for WooCommmerce: door DHL Parcel – 2.0.18
GTM4WP: door Thomas Geiger – 1.19.1
Facebook for WooCommerce: door Facebook – 3.1.8
Goya Core: door Everthemes – 1.0.8.2
iThemes Security Pro: door iThemes – 7.1.0
Jetpack: door Automattic – 12.9.3
WPBakery Page Builder: door Michael M - WPBakery.com – 7.0
Judge.me Product Reviews for WooCommerce: door Judge.me – 1.3.22
Kirki Customizer Framework: door Themeum – 5.0.0
Loco Translate: door Tim Whitlock – 2.6.6
MailPoet: door MailPoet – 4.40.0
Meta Box: door MetaBox.io – 5.9.1
Ninja Forms: door Saturday Drive – 3.7.0
Stripe Payment Plugin for WooCommerce: door WebToffee – 3.9.4
WooCommerce PDF-facturen, pakbonnen, leveringsbonnen en verzendlabels: door WebToffee – 4.3.1
Rank Math SEO: door Rank Math – 1.0.210
WooCommerce - Show only lowest prices in variable products: door Fernando Tellado – 1.0.5
WC Ajax Product Filters: door Shamim Al Mamun – 4.2.1
Weglot Translate: door Weglot Translate team – 4.2.4
Woocommerce autocomplete checkout address: door Acespritech Solutions Pvt. Ltd. – 1.1.0
WooCommerce Cart Abandonment Recovery: door CartFlows Inc – 1.2.26
Premmerce Permalink Manager for WooCommerce: door Premmerce – 2.3.10
Product Feed PRO for WooCommerce: door AdTribes.io – 13.1.8
Variation Swatches for WooCommerce - Pro: door Emran Ahmed – 2.0.27
Variation Swatches for WooCommerce: door Emran Ahmed – 2.0.29
WooCommerce Stripe Gateway: door WooCommerce – 7.8.1
Woocommerce Google Merchant Center Customer Reviews: door WebPerfect.com – 1.1.8
WooCommerce: door Automattic – 8.4.0 (update naar versie 8.5.2 is beschikbaar)
Widgets for Google Reviews: door Trustindex.io  – 11.3
WP-Sweep: door Lester 'GaMerZ' Chan – 1.1.8
DeepL for WordPress : translation plugin: door Fluenx – 2.4.2.2
Custom Product Tabs for WooCommerce: door Code Parrots – 1.8.5
YITH WooCommerce Wishlist: door YITH – 3.28.0

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Winkelbasis: #3172 - /shop/
Winkelwagen: #3173 - /cart/
Afrekenen: #3174 - /checkout/
Mijn account: #3175 - /my-account/
Algemene voorwaarden: #72 - /terms-conditions/

### Theme ###

Name: Goya Child Theme
Version: 1.0.8
Author URL: 
Child Theme: ✔
Parent Theme Name: Goya
Parent Theme Version: 1.0.8.8
Parent Theme Author URL: https://themeforest.net/user/everthemess
WooCommerce Support: ✔

### Templates ###

Overrides: goya/woocommerce/archive-product.php
goya/woocommerce/cart/cart-empty.php
goya/woocommerce/cart/cart-shipping.php
goya/woocommerce/cart/cart.php
goya/woocommerce/cart/mini-cart.php
goya/woocommerce/cart/shipping-calculator.php
goya/woocommerce/checkout/form-checkout.php
goya/woocommerce/checkout/form-coupon.php
goya/woocommerce/checkout/form-login.php
goya/woocommerce/content-product.php
goya/woocommerce/content-single-product.php
goya/woocommerce/global/form-login.php
goya/woocommerce/global/quantity-input.php
goya/woocommerce/global/wrapper-end.php
goya/woocommerce/global/wrapper-start.php
goya/woocommerce/loop/add-to-cart.php
goya/woocommerce/loop/loop-start.php
goya/woocommerce/loop/pagination.php
goya/woocommerce/myaccount/form-login.php
goya/woocommerce/myaccount/navigation.php
goya/woocommerce/order/tracking.php
goya/woocommerce/product-searchform.php
goya/woocommerce/single-product/photoswipe.php
goya/woocommerce/single-product/related.php
goya/woocommerce/single-product/tabs/tabs.php
goya/woocommerce/single-product/up-sells.php
goya/woocommerce/single-product-reviews.php
goya/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-31 13:18:58 +00:00
Options: ✔
Notes: 141
Onboarding: completed

### MailPoet ###

Sending Method: SMTP
Send all site's emails with: Huidige verzendmethode
Task Scheduler method: Action Scheduler
Cron ping URL: https://bconscious.nl?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 16.658
Oldest: 2023-12-31 09:06:49 +0000
Newest: 2024-01-31 09:06:06 +0000

Failed: 25
Oldest: 2023-12-18 17:57:39 +0000
Newest: 2024-01-30 20:52:00 +0000

Pending: 5
Oldest: 2024-01-31 09:08:06 +0000
Newest: 2024-02-01 13:17:18 +0000

### Status report information ###

Generated at: 2024-01-31 09:06:15 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
```[tasklist]
### Tasks
```

**Comment by rrennick** [comment]
> They requested to contact Woocommerce support for this one as they had no issues on their side.

@BConscious I'll close this issue and it will post a comment with instructions for contacting support.
