### ISSUE TITLE
block editor product -> Schedule sale -> BUG

### ISSUE THREAD

**Issue by 2551654928** [woothemes/woocommerce#44216]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

![BUG](https://github.com/woocommerce/woocommerce/assets/45090255/0089ab79-56af-4d55-8224-c5ba6e9202e2)

### Expected behavior

请看VCR

### Actual behavior

请看VCR

### Steps to reproduce

请看VCR

1. Enable the new product editor on a WooCommerce site
2. Change the site language to 简体中文
3. Go to **Dashboard > Updates** and update the translations
4. Go to **Product > Add New**
5. Add name, and go to the pricing tab
6. Enter a list price and a sale price
7. Toggle on the schedule sale and select a date
8. Notice how there is an error -> invalid date 

### WordPress Environment

请看VCR

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@louwie17 can someone from the team check if this bug is happening?

**Comment by louwie17** [comment]
yes, I was able to reproduce this when changing the language to 简体中文

**Comment by 2551654928** [comment]
Thank you.
