### ISSUE TITLE
[Enhancement]: WC_Order_Query include parameter

### ISSUE THREAD

**Issue by danielbarenkamp** [woothemes/woocommerce#44220]
### Describe the solution you'd like

We need to use the WC_Order_Query to fetch only some orders by an array of IDs. This is not possible right now. Please add an "include" parameter (https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query)

### Describe alternatives you've considered

Loop through ALL orders or get them manually via wc_get_order (resource consuming)

**Comment by rrennick** [comment]
> We need to use the WC_Order_Query to fetch only some orders by an array of IDs. This is not possible right now.

@danielbarenkamp You can use the `post__in` parameter to select orders by ID.

```
# wp shell
wp> wc_get_orders( [ 'post__in' => [5734,5702] ] );
=> array(2) {
  [0]=>
  object(Automattic\WooCommerce\Admin\Overrides\Order)#25401 (18) {
    ["id":protected]=>
    int(5734)
    ["data":protected]=>
    array(33) {
....
  }
  [1]=>
  object(Automattic\WooCommerce\Admin\Overrides\Order)#25288 (18) {
    ["id":protected]=>
    int(5702)
    ["data":protected]=>
    array(33) {
....
  }
```

I'll close the issue as a question.
