### ISSUE TITLE
Advanced settings > Features: remove Navigation setting when store isn't using it

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#44224]
**Description:** this is a follow-up of #35157. Currently, we still show the Navigation setting when the store isn't using it. This can confuse users, as they may never have heard of the new experience and we don't give much information. The setting should be removed if the store doesn't have the navigation enabled.

<img width="1039" alt="Captura de ecrã 2024-01-31, às 12 14 44" src="https://github.com/woocommerce/woocommerce/assets/3380168/13b54aad-1001-478f-8147-f7b505ffd462">

For now, stores with the new navigation enabled can keep using it unless they disable the setting. We'll sunset this feature when WP phase 3 is deployed more broadly.

**Acceptance criteria:**

- [ ] Remove Navigation in Settings > Advanced > Features if the store doesn't have the new navigation enabled.

**Comment by pmcpinto** [comment]
@louwie17 is it possible to make this quick change in the upcoming days and include it in WC 8.7? Thanks

**Comment by louwie17** [comment]
> @louwie17 is it possible to make this quick change in the upcoming days and include it in WC 8.7? Thanks

Sorry, I had missed this ping. We can certainly get it done for the next release.

**Comment by pmcpinto** [comment]
Thanks. I added the Cycle 45 label.
