### ISSUE TITLE
WooCommerce Variation swatch gallery not working properly 

### ISSUE THREAD

**Issue by uzumakiAgam** [woothemes/woocommerce#44276]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Please help me i am a new devloper don't hold much knowledge, but i can explain what problem i am facing right now,

I created a wordpress e-commerce website with variation product, ( Clothing website)

Now i uploaded a Product t(shirt) available in different colours and size,

I created variation with different Colour-Any size attributes, ( i use product gallery wich means using a product gallery for perticular veriation , like black tshirt image shown when black colour selected and hide other variation inage) but in website when i tap black colour variation, black tshirt image not showing as i want, i have to select any size variation ( from s to xl wich available ) than product gallery start refreshing and show correctly

Here you can check in my live website - https://reyzma.com/reymas-full-sleeve-v-neck-t-shirts/

I want to show image according to selected colour, ( size options are just for users i don't want to show image according to size ) please help me i littrealy beg you

### Expected behavior

I expect when i tap colour variation, image change accordingly 

### Actual behavior

I have to select colour and size both to change  images 

### Steps to reproduce

Open link and try your self https://reyzma.com/reymas-full-sleeve-v-neck-t-shirts/

### WordPress Environment

...

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shameemreza** [comment]
This should be a support request rather than a bug report, perhaps on the forum [here](https://wordpress.org/support/plugin/woocommerce/). By the way, here are some resources that could assist you in reaching your goal:

* https://rudrastyh.com/woocommerce/trigger-event-after-change-of-variation.html
* https://www.jclabs.co.uk/update-woocommerce-variable-product-images-when-any-attribute-is-selected/
* https://stackoverflow.com/questions/63525264/woocommerce-change-product-image-when-only-one-attribute-is-selected
* https://gist.github.com/BHare1985/f9c409c825822b769c06397bfc8b84cc

**Comment by smartinbound** [comment]
This is actually expected Woo behavior, not a bug. Think of it this way: Woo doesn't know what colors or sizes means, it just knows attributes. So, you might be selling a watch, and the user would need to select "Face: Silver" and "Band: Leather" before they would be able to see a specific variation image. The easiest way around this is to set a "Default Attribute" for each variable product size. So when the user loads the page, "Medium" is already selected. So when they choose a color, it will switch the image immediately like you want.

**Comment by uzumakiAgam** [comment]
This is what I am doing right now, i selected m size to default but there is any other option? Please suggest me, and thanks for your support
