### ISSUE TITLE
Replacement for wc_get_log_file_path?

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#44278]
### Describe the solution you'd like

Sorry, this is not a bug neither an enhancement request, but I wasn't sure where I could reach Woo developers directly, in a written/organised way.

Since 6.8.0-beta.1 I'm getting the deprecation notice for wc_get_log_file_path.

I'm using this on one of my plugins, a payment gateway, to show the shop owner where the logs are stored.

What's the rationale behind having no alternative? Are the text logs going to be discontinued in favor of only the database logs?

**Comment by tammullen** [comment]
Thanks for your question and feedback @webdados about the logging updates upcoming in 8.6.

As you note this isn't a bug or an enhancement request so I'm going to convert this issue into a discussion and the team working on logging can give you an answer there.
