### ISSUE TITLE
WooCommerce Variation Swatch Gallery Load isuue 

### ISSUE THREAD

**Issue by uzumakiAgam** [woothemes/woocommerce#44291]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Please help me :
I am facing an issue, when i select a variation and change it , it reset for a second,

Here i explain more->
I am creating a clothing site using WooCommerce, i am using Innovativewp's variation swatch, when i switch in colour the image should change accordingly colour and it's working fine✓ but there is a issue, 

- Suppose i select balck colour and all black tshirt image showing perfectly, but when i shift to green variation all image start showing for 1 second and automatically load only green tshirt at the end it make my job done but it's look so wired any bug website

Check my website:- https://reyzma.com/reymas-full-sleeve-v-neck-t-shirts

Please help me github is my last option for help

### Expected behavior

To show image accordingly 

### Actual behavior

Show all image first than auto reload to selected product 

### Steps to reproduce

Check my website:- https://reyzma.com/reymas-full-sleeve-v-neck-t-shirts

Switch between colour variation and see the bug yourself 

### WordPress Environment

Check my website:- https://reyzma.com/reymas-full-sleeve-v-neck-t-shirts

Switch between colour variation and see the bug yourself 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adimoldovan** [comment]
Hi there @uzumakiAgam! This looks like an issue with Variation Swatches plugin, and it should be addressed to their developers, InnovativeWP. This is a repository for WooCommerce core.
