### ISSUE TITLE
[Enhancement]: Add "Origin" report to WooCommerce Analytics

### ISSUE THREAD

**Issue by maxlaf** [woothemes/woocommerce#44329]
### Describe the solution you'd like

Users are finding the "Origin" from order attribution to be helpful, but there's currently no way to see a report of order per origin. There's no Origin report under WooCommerce analytics, nor is there a filter for that or a column that can be enabled for other reporting sections.

This enhancement is to explore adding an "Origin" report section, or provide a filter or column for Origin that can be used on existing report sections.

### Additional context

7663153-zen

**Comment by fishtankmike** [comment]
@maxlaf 100% agree with you on this.

Our digital marketing team would kill to have that kind of data in a report, as would the countless other Woocommerce store owners I imagine.

Hope this is on the roadmap for the WooCommerce dev team...?

**Comment by BurksNysor** [comment]
Created an account just to come say, please do this!!!! I would love to see revenue totals per source to make better informed marketing decisions.

**Comment by NathalyaVides** [comment]
7796757- zen looking for the same functionality

**Comment by jswolcott** [comment]
yeah I third that or whatever

**Comment by layoutd** [comment]
Thanks everyone for the feedback, we've added this feature to the epic for including order attribution data in WooCommerce Analytics that is currently in active development. See:
- https://github.com/woocommerce/woocommerce/issues/46054
- https://github.com/woocommerce/woocommerce/issues/46383

**Comment by SimonBo505** [comment]
We are working on an Origin report as screens below.

It groups all the origins so you can see where people are visiting from, these groups can be filtered using a select field and or dates.

The table displays the LTV that can be ordered, it also has two columns to show the first and last orders' origin. The client’s name is clickable so you can see all the orders.
 
![LTV Origin-1](https://github.com/woocommerce/woocommerce/assets/98884016/8d446e51-ffc3-4f48-b470-e513196e0bde)

We are also adding a chart to display the data in percentages 
 
![LTV Origin-2](https://github.com/woocommerce/woocommerce/assets/98884016/3e45065d-7305-4c9c-8db5-6faff93bd7d2)

If interested let us know

**Comment by BurksNysor** [comment]
Looks great for a high level overview, I'm very interested. Would it be possible to list them by order number as well or display the order numbers in a column comma separated vs clicking through to it?  With that, I would be able to do a quick calculation or create a program to the API on how much Margin I'm getting from Google Pay Per Click vs something like Microsoft ads to help drive my marketing decisions and where I invest my development time on the websites I manage.
