### ISSUE TITLE
[Enhancement]: Make quotes used in frontend notices consistent

### ISSUE THREAD

**Issue by ninetyninew** [woothemes/woocommerce#44348]
### Describe the solution you'd like

We have found that on the added to cart notice (and potentially others) the quotes around the product name are curly:

<img width="334" alt="image" src="https://github.com/woocommerce/woocommerce/assets/56840277/a6f909eb-9b05-4d35-ae8c-95063c7f0732">

This comes from the use of `woocommerce_add_to_cart_item_name_in_quotes` which generates the notice in the `wc_add_to_cart_message` function of `wc-cart-functions.php`, it has a default of: `&ldquo;%s&rdquo;`.

However, there are other notices which use straight quotes, e.g. `Sorry, "%s" is not in stock. Please edit your cart and try again. We apologize for any inconvenience caused.`

Should these all be consistent? The above was discovered when we wanted to add custom notices and we were trying to determine the format to use, we went for straight quotes as there are more notices using this than not.

### Describe alternatives you've considered

None.

**Comment by nielslange** [comment]
Thanks for reaching out, @ninetyninew. I briefly checked our codebase and noticed that we're currently using the following quote types:
- `&quot;`: Neutral double quotation mark (")
- `&ldquo;`: Left double quotation mark (“)
- `&rdquo;`: Right double quotation mark (”)
- `&apos;`: Neutral single quotation mark (')
- `&lsquo;`: Left single quotation mark (‘)
- `&rsquo;`: Right single quotation mark (’)

I'll have to raise this issue internally and will get back to you once I have further information on how to proceed in this case. That said, thanks for bringing this to our attention.

**Comment by nielslange** [comment]
Internal discussion: p6q8Tx-4kJ-p2

**Comment by ralucaStan** [comment]
@nielslange I recommend closing this ticket and opening a new one that applies to all quote styles, based on the results from your RFCs.

**Comment by nielslange** [comment]
> @nielslange I recommend closing this ticket and opening a new one that applies to all quote styles, based on the results from your RFCs.

@ralucaStan I've already created #45137 three weeks ago. That said, I'm happy to close this issue, given that the newly created issue is a superset of this one.
