### ISSUE TITLE
WooCommerce 8.5x email title problems 8.5.2 specially

### ISSUE THREAD

**Issue by paulvek** [woothemes/woocommerce#44341]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

email title for canceled orders is wrong and doesn’t work correctly for cancel orders in woocommerce 8.5x maybe, especially on 8.5.2 (I see the problem in this version)

i recived a email for canceled order with this (below) title

It looks as if the variables are shown in the title!

`[{site_title]: سفارش # {order_number Order لغو شد

translate to english for you

[{site_title]: Order # {order_number Order cancelled`

![LojyLJG](https://github.com/woocommerce/woocommerce/assets/153482922/1dff0158-5188-4c77-8878-0a0d1460de2d)
received

### Expected behavior

I explained in the text

### Actual behavior

I explained in the text

### Steps to reproduce

I explained in the text

### WordPress Environment

I explained in the text

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shameemreza** [comment]
Ref Ticket: 7684907-zen
Thread link: https://wordpress.org/support/topic/woocommerce-8-5x-email-title-problems-8-5-2-specially/

**Comment by paulvek** [comment]
@shameemreza Thank you for your time. I will take the test again in another situation and announce the result.

**Comment by nielslange** [comment]
Closing this issue as in https://wordpress.org/support/topic/woocommerce-8-5x-email-title-problems-8-5-2-specially/#post-17398102 the reporter mentioned that it can be closed.
