### ISSUE TITLE
Add "Is using Checkout block/shortcode" to system report

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#44357]
The system report right now doesn't include a check to see if a store is using Checkout block or Checkout shortcode, ideally it should be included.

**Comment by lsinger** [comment]
@ralucaStan can you give some context why you added Proton here? Is this just for awareness or is this something you need our help with?

**Comment by senadir** [comment]
It's not clear which team own the system report tool maybe?

**Comment by ralucaStan** [comment]
@rrennick could you help us identify the best team to handle this ticket? Some context where the assignment originated p1708078835410869/1708078523.493379-slack-C03CPM3UXDJ

**Comment by ralucaStan** [comment]
The Monorepo triage spreadsheet mentions team Proton as responsible for the system report tool.

**Comment by rrennick** [comment]
> @rrennick could you help us identify the best team to handle this ticket?

@ralucaStan In the case of the SSR, various teams add entries to the report if the team feels it should be added but should request a review from Proton. I've updated the spreadsheet to reflect this.

**Comment by ralucaStan** [comment]
@pmcpinto, we have this planned for this cycle, but I'm removing the high-priority label.
