### ISSUE TITLE
woocommerce-variation-description totally wrong

### ISSUE THREAD

**Issue by issimissimo** [woothemes/woocommerce#44381]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've created an attribute with more than 10 terms, with their own description.
When I click on a term I see the description of another term. or nothing.

### Expected behavior

I should see the the description of the term that I've cklicked

### Actual behavior

I see the the decription of another term, or nothing

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/41523122/c52ebc6f-f50a-40a3-806b-938dd02bde73)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.shop.vanesi.it
Site address (URL): https://www.shop.vanesi.it
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.27
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wpxa_
Dimensione totale database: 28.21MB
Dimensione dati database: 24.74MB
Dimensione indice database: 3.47MB
wpxa_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpxa_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpxa_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_actionscheduler_actions: Dati: 0.19MB + indice: 0.19MB + motore InnoDB
wpxa_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_actionscheduler_logs: Dati: 0.13MB + indice: 0.14MB + motore InnoDB
wpxa_cky_banners: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wpxa_cky_cookies: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_cky_cookie_categories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wpxa_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_e_submissions: Dati: 0.02MB + indice: 0.27MB + motore InnoDB
wpxa_e_submissions_actions_log: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wpxa_e_submissions_values: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_fbv: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_fbv_attachment_folder: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_jetpack_sync_queue: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpxa_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_litespeed_avatar: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_litespeed_img_optming: Dati: 0.06MB + indice: 0.08MB + motore InnoDB
wpxa_litespeed_url: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_litespeed_url_file: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wpxa_options: Dati: 5.30MB + indice: 0.16MB + motore InnoDB
wpxa_pmr_status: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_postmeta: Dati: 10.31MB + indice: 0.55MB + motore InnoDB
wpxa_posts: Dati: 7.42MB + indice: 0.22MB + motore InnoDB
wpxa_snippets: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpxa_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wpxa_wc_admin_note_actions: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
wpxa_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wpxa_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpxa_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpxa_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpxa_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpxa_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wpxa_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpxa_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpxa_wpml_mails: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 44
custom_css: 1
customize_changeset: 176
elementor_library: 8
jet-woo-builder: 10
nav_menu_item: 4
page: 11
post: 3
product: 15
product_variation: 42
revision: 826
rmp_menu: 1
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Colorize Mobile Browser Bar: di Worda Themes – 1.1.0
CookieYes | GDPR Cookie Consent: di CookieYes – 3.1.8
Disable Gutenberg: di Jeff Starr – 3.1
Duplica pagina: di mndpsingh287 – 4.5.3
Elementor Pro: di Elementor.com – 3.19.0
Elementor: di Elementor.com – 3.19.0
Enable Media Replace: di ShortPixel – 4.1.5
Facebook for WooCommerce: di Facebook – 3.1.9
FileBird: di Ninja Team – 5.1.6
JetWooBuilder For Elementor: di Crocoblock – 2.1.8
Phoenix Media Rename: di crossi72 – 3.11.6
Premium Addons for Elementor: di Leap13 – 4.10.18
Premium Addons PRO: di Leap13 – 2.9.10
Resize Image After Upload: di ShortPixel – 1.8.6
Responsive Menu Pro: di ExpressTech – 4.3.0
Side Cart WooCommerce: di XootiX – 2.4.9
SMNTCS Image Dimensions: di Niels Lange – 1.5
UpdraftPlus - Backup/Ripristino: di UpdraftPlus.Com
DavidAnderson – 1.23.16

WooCommerce Custom Add To Cart Button: di Barn2 Plugins – 1.2.2
WooPayments: di Automattic – 7.1.0
WooCommerce PayPal Payments: di WooCommerce – 2.5.2
WooCommerce: di Automattic – 8.5.2
WP Mail Logging: di WP Mail Logging Team – 1.12.0
YITH WooCommerce Color, Image & Label Variation Swatches: di YITH – 2.4.0

### Inactive Plugins (1) ###

LiteSpeed Cache: di LiteSpeed Technologies – 6.0.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ La visibilità della pagina dovrebbe essere pubblica
Carrello: ❌ La pagina non contiene lo shortcode [woocommerce_cart] o il blocco woocommerce/cart.
Pagamento: ❌ La pagina non contiene lo shortcode [woocommerce_checkout] o il blocco woocommerce/checkout.
Il mio account: #22 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Hello Elementor
Version: 3.0.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.1.0
Connected to WPCOM: Sì
WPCOM Blog ID: 226701284
Account ID: acct_1OK1vwFk1IGUD8Kt
Payment Gateway: Abilitato
Test Mode: Disabilitato
Enabled APMs: card
WooPay: Non idoneo
Apple Pay / Google Pay: Disabilitato
Fraud Protection Level: basic
Multi-currency: Abilitato
Public Key Encryption: Disabilitato
Auth and Capture: Abilitato
Documents: Abilitato
Logging: Disabilitato

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-06 15:48:14 +01:00
Options: ✔
Notes: 72
Onboarding: completed

### Action Scheduler ###

Operazione annullata: 1
Oldest: 2024-01-30 13:45:21 +0000
Newest: 2024-01-30 13:45:21 +0000

Completato: 531
Oldest: 2024-01-06 11:28:35 +0000
Newest: 2024-02-06 03:32:10 +0000

Operazione non riuscita: 12
Oldest: 2023-12-05 15:51:23 +0000
Newest: 2024-02-05 13:15:35 +0000

In attesa: 2
Oldest: 2024-02-06 17:36:37 +0000
Newest: 2024-02-06 21:32:58 +0000

### Status report information ###

Generated at: 2024-02-06 04:35:39 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hi @issimissimo, thanks for reporting this.
If I understand correctly, you are expecting term attribute descriptions to appear on product variations on the product page.
However, the description that is shown on the product page is the one written on the product variation (not the one in the term):
<img width="1030" alt="Screenshot 2024-08-19 at 16 01 04" src="https://github.com/user-attachments/assets/6127ab6d-f15c-40f1-941b-129183e521ad">

I hope this helps, let us know if you need further assistance.
Thanks you!
