### ISSUE TITLE
Add E2E to test Checkout flow for a digital only store

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#44400]
This PR https://github.com/woocommerce/woocommerce/pull/44388 fixed a regression in an important flow that we missed, which is a fully virtual store.

There's a slight difference between checking out a virtual item (which we already test) and checking out any item on a digital only store (shipping is disabled), the later we don't test for.

We should test the following flow:

- Disable shipping and shipping calculation from "Shipping Locations" option.
- Checkout any product.

**Comment by ralucaStan** [comment]
@nielslange would you mind sharing in a comment the reason why this ticket is blocked?

**Comment by nielslange** [comment]
> @nielslange would you mind sharing in a comment the reason why this ticket is blocked?

This issue was blocked by #44405. Now that the other issue is solved, this issue is no longer blocked, @ralucaStan.
