### ISSUE TITLE
total prix sur commande a payer incorrect , 2 bugs en 1 ..

### ISSUE THREAD

**Issue by francoisbdr13** [woothemes/woocommerce#44408]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Bonjour , un BUG aujourd'hui improbable ( après 18 mois d'existence , jamais vu ) parmi une dizaine de commande aujourd'hui sans problèmes , une d'un total de 105,19 e est facturée 10,51e ( et payé par carte bleue 10,51 e ) ! , et en plus un article est facturé 00,00 e , alors qu' il n 'affiche aucun problème dans sa fiche produit . Heureusement mes clientes sont honnètes . 
Si vous pouvez corriger ce bug qui j'espère ne va pas se reproduire !!

### Expected behavior

essayez de regler ce bug ? 
![prix a zero](https://github.com/woocommerce/woocommerce/assets/159164934/8230a318-563c-4475-a0f6-4bb6f301d195)

### Actual behavior

![total erroné](https://github.com/woocommerce/woocommerce/assets/159164934/adcfc7d4-d540-4be4-be49-72e3b5eb9748)

### Steps to reproduce

![total erroné](https://github.com/woocommerce/woocommerce/assets/159164934/780575a9-12c4-4c58-9739-e3a34ef931bc)

### WordPress Environment

aucun probleme d 'état ! , je n 'ai pas desactivé d 'autes plugins car une seule commande au milieu d 'autres sasn soucis , sans mise à jour entre 2 , il ne s'est passé que quelques minutes entre la commande avec mauvaise adittion et autres commandes sans problemes

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Hey! What Checkout are you using? Shortcode Checkout or Block Checkout?

If you try to recalculate the totals for the order (by changing the status to pending payment and hitting recalculate), is the total correct?

**Comment by francoisbdr13** [comment]
Hey !
 i use shortcode check out , today the total has been recalculate and is now good , but before i change the status by recalculate !!
But by clicking  on recalculate the item at wrong price doesn' t change and always at zero Euro !
In product sheet the price is really good , and i have sold many others before without any problem .
Very strange problem . Thanks for your help , we are waiting for the customer's bank statement to know the the amount really debited , but one product is for sure already  free !

**Comment by nielslange** [comment]
Hello @francoisbdr13 👋

- Have you ever seen this issue before?
- What kind of product is the one with the zero-price? A simple product, a variable product, etc.?
- Are you using any extensions or custom code that might have interfered with the product price?

**Comment by francoisbdr13** [comment]
Non , depuis 18 mois environ d'utilisation de ma boutique , c'est la première fois que je vois ce problème, c'est un produit simple , pas de code specifique ou d'extensions ajoutée récemment .
Il a déja été facturé auparavant à son prix ce n 'est pas un nouveau produit . Le client m 'a bien montré un extrait de son compte bancaire ( paiement cb ) , il a été  débité de 105,19 e , donc produit non facturé .

**Comment by nielslange** [comment]
To allow others to following this conversation, I translated your reply into English.

> No, in about 18 months of using my store, this is the first time I have seen this problem, it is a simple product, no specific code or extensions added recently.
It has already been invoiced before at its price, it is not a new product. The customer showed me an extract from his bank account (cb payment), it was debited with 105.19 e, therefore product not invoiced.

Thanks for answering my questions. At this time, I have no explanation what might have caused this issue. Therefore, it's difficult to reproduce this case. I'll close this issue for now, but please reopen it, if the problem should happen again. If it does, the please create a [system status report](https://woo.com/document/understanding-the-woocommerce-system-status-report/) immediately so that we can see how your store is set up and which extensions you're using.
