### ISSUE TITLE
Virtual/ Downloadable checkbox not visible in the product page.

### ISSUE THREAD

**Issue by nefelikaranikola** [woothemes/woocommerce#44409]
The Virtual/ Downloadable checkbox not visible in the product page. I checked previous threads regarding woo not being updated to the latest version but in my case this is not the issue. How can I resolve this? I had this before and I solved it by updating woo.

**Comment by lanej0** [comment]
Can you provide us a little more information around this issue?  Are you using any additional plugins?  If you could provide a System Report (WooCommerce > Status > Get system report), it might help us narrow down the issue.

**Comment by nefelikaranikola** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://wineunplugged.nl
Site address (URL): https://wineunplugged.nl
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: ctb_
Total Database Size: 95.70MB
Database Data Size: 82.87MB
Database Index Size: 12.83MB
ctb_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
ctb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ctb_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
ctb_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
ctb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ctb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_actionscheduler_actions: Data: 1.02MB + Index: 0.44MB + Engine InnoDB
ctb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_actionscheduler_logs: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
ctb_aryo_activity_log: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
ctb_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_cartflows_ca_cart_abandonment: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
ctb_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_comments: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
ctb_dpdconnect_batches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_dpdconnect_jobs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_dpdconnect_labels: Data: 2.52MB + Index: 0.02MB + Engine InnoDB
ctb_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
ctb_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ctb_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
ctb_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ctb_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
ctb_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ctb_jet_smart_filters_indexer: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
ctb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_options: Data: 6.03MB + Index: 0.33MB + Engine InnoDB
ctb_postmeta: Data: 37.45MB + Index: 3.89MB + Engine InnoDB
ctb_posts: Data: 26.52MB + Index: 0.39MB + Engine InnoDB
ctb_rank_math_internal_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
ctb_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
ctb_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_relevanssi: Data: 3.27MB + Index: 3.83MB + Engine InnoDB
ctb_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
ctb_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
ctb_term_relationships: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
ctb_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
ctb_usermeta: Data: 0.47MB + Index: 0.28MB + Engine InnoDB
ctb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ctb_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ctb_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
ctb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
ctb_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ctb_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ctb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ctb_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
ctb_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ctb_wc_product_attributes_lookup: Data: 0.22MB + Index: 0.17MB + Engine InnoDB
ctb_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
ctb_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ctb_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wf301_404_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wf301_linkhero: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ctb_wf301_redirect_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wf301_redirect_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ctb_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 22
acf-field-group: 3
attachment: 471
br_product_filter: 1
custom_css: 1
elementor_font: 2
elementor_library: 29
elementor_snippet: 12
jet-menu: 1
jet-smart-filters: 12
nav_menu_item: 45
oembed_cache: 1
page: 19
post: 28
product: 302
revision: 2456
shop_coupon: 12
shop_order: 300
shop_order_refund: 5
shop_subscription: 4
sp_post_carousel: 1
sp_wps_shortcodes: 3
wp_global_styles: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Advanced Custom Fields: by WP Engine – 6.2.6
All-in-One WP Migration: by ServMask – 7.79
Activity Log: by Activity Log Team – 2.9.0
Beautiful and responsive cookie consent: by Beautiful Cookie Banner – 3.2.4
Joinchat: by Creame – 5.0.16
DPD Connect for WooCommerce: by DPD / X-Interactive.nl – 1.4.4
Easy WP SMTP: by Easy WP SMTP – 2.2.0
Ele Custom Skin Pro: by Dudaster.com – 3.2.4
Ele Custom Skin: by Dudaster.com – 3.1.7
Elementor Pro: by Elementor.com – 3.19.1
Elementor: by Elementor.com – 3.19.1
301 Redirects: by WebFactory Ltd – 2.73
Firebase Authentication | The Brink | SOS Do Not Update! SOS: by miniOrange – 999.5.9
Include Klaviyo for Elementor pro: by Thong Nguyen – 2.1
JetMenu: by Crocoblock – 2.2.4
JetSmartFilters: by Crocoblock – 3.2.3
Jetpack: by Automattic – 13.0
Klaviyo: by Klaviyo
Inc. – 3.3.3

Make Column Clickable Elementor: by Fernando Acosta – 1.4.0
Mollie Payments for WooCommerce: by Mollie – 7.4.1
PW WooCommerce Exclude Free Shipping: by Pimwick
LLC – 1.35

Real-Time Find and Replace: by Marios Alexandrou – 4.0.3
Relevanssi: by Mikko Saari – 4.22.0
Rank Math SEO: by Rank Math – 1.0.212
Speed Optimizer: by SiteGround – 7.4.6
Wine Unplugged: by The Brink Agency – 1.0
Woo Discount Rules: by Flycart – 2.6.2
Product Slider Pro for WooCommerce: by ShapedPlugin – 3.2.1
WooCommerce Subscriptions: by WooCommerce – 5.1.2
WooCommerce: by Automattic – 8.5.2
WPIDE - File Manager & Code Editor: by XplodedThemes – 3.4.8

### Inactive Plugins (2) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.16

WP File Manager: by mndpsingh287 – 7.2.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
fatal-error-handler.php: fatal-error-handler.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #223 - /shop/
Cart: #224 - /winkelwagen/
Checkout: #225 - /afrekenen/
My account: #226 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor Child
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 3.0.0 – 3.0.1 is available
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: hello-theme-child-master/woocommerce/global/quantity-input.php version 7.4.0 is out of date. The core version is 7.8.0
hello-theme-child-master/woocommerce/myaccount/form-login.php
hello-theme-child-master/woocommerce/myaccount/form-lost-password.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://wineunplugged.nl
Subscriptions-core Library Version: 5.7.1
Subscription Statuses: wc-cancelled: 4
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Netherlands

### Subscriptions by Payment Gateway ###

Mollie - iDEAL: wc-cancelled: 4

### Payment Gateway Support ###

Mollie - iDEAL: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Mollie - PayPal: products
refunds

Mollie - Apple Pay: products
refunds
subscriptions
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Mollie - Card: products
refunds
subscriptions
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Mollie - Pay later.: products
refunds


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-09 10:16:27 +01:00
Options: ✔
Notes: 144
Onboarding: completed

### Action Scheduler ###

Complete: 1,055
Oldest: 2024-01-08 17:09:17 +0100
Newest: 2024-02-08 13:12:50 +0100

Failed: 61
Oldest: 2022-11-01 15:10:52 +0100
Newest: 2024-02-06 08:56:36 +0100

Pending: 1
Oldest: 2024-02-09 03:27:24 +0100
Newest: 2024-02-09 03:27:24 +0100


### Status report information ###

Generated at: 2024-02-08 16:30:09 +01:00
`

**Comment by lanej0** [comment]
Hi @nefelikaranikola -- I can't reproduce this:

![Screenshot 2024-02-08 at 2 06 10 PM](https://github.com/woocommerce/woocommerce/assets/80276/203c98ba-e479-43c1-8d94-b8d109addb78)

My guess is that you've likely got a plugin that's causing a conflict here.  Your best bet is to try deactivating your plugins to see if that helps.
