### ISSUE TITLE
Create read-only production repo for publishing PHP package to packagist

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#44417]
### Issue description

Project thread: pdibGW-2Mv-p2

Follow-up from https://github.com/woocommerce/woocommerce/issues/44262

Publish remote API test package to packagist.com from monorepo. This package should be able to be imported by Woo.com to run tests against the output to ensure expected results.

Discussions:

1. https://github.com/woocommerce/woocommerce/issues/44262#issuecomment-1928576879
2. p1707181201700819-slack-C03CPM3UXDJ (internal)

### Acceptance criteria

1. Set up GitHub repository with necessary permissions 
2. Register and set up packagist package
1. Implement pnpm script, CI/CD, or other automations to build and publish package
3. Add documentation on how to publish test package

**Comment by psealock** [comment]
### Updates

* A new package repo has been created here: https://github.com/woocommerce/package-remote-specs-validation
* Monorepo team Vortex will be responsible for creating a syncing mechanism between the monorepo and the above production repo. In the meantime, manual syncing will be sufficient to get this package released.
* Once the first version has been synced to the production repo, pointing WooCommerce's [Packagist](https://packagist.org/) organisation to the new repo will be sufficient to automatically keep the distribution up to date.

**Comment by ilyasfoo** [comment]
Thanks for the updates, @psealock!

> Once the first version has been synced to the production repo, pointing WooCommerce's [Packagist](https://packagist.org/) organisation to the new repo will be sufficient to automatically keep the distribution up to date.

Since the test suite package is now done in this PR (https://github.com/woocommerce/woocommerce/pull/44484), are we able to sync the first version to production?

**Comment by psealock** [comment]
Yes!

Production repo manually updated https://github.com/woocommerce/package-remote-specs-validation
Packagist distribution available https://packagist.org/packages/woocommerce/remote-specs-validation

This satisfies the criteria for this issue and we can track the creation of the sync automation separately @jonathansadowski
