### ISSUE TITLE
[Enhancement]: Please improve `woocommerce_blocks_hook_compatibility_additional_data` filter hook

### ISSUE THREAD

**Issue by webmandesign** [woothemes/woocommerce#44447]
### Describe the solution you'd like

I'm currently using [`woocommerce_blocks_hook_compatibility_additional_data` hook](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/src/Blocks/Templates/AbstractTemplateCompatibility.php#L165) in my plugin and I've stumbled upon an issue.

The hook provides no context I can use to set up the returned array.

As an example, you can see there are different sets of hooks set up in [`ArchiveProductTemplatesCompatibility`](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/src/Blocks/Templates/ArchiveProductTemplatesCompatibility.php#L180) and [`SingleProductTemplateCompatibility`](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/src/Blocks/Templates/SingleProductTemplateCompatibility.php#L166) class.

However, using the `woocommerce_blocks_hook_compatibility_additional_data` filter hook currently does not allow me to distinguish between the two usecases as it is in those classes.

For example, when I alter shop archive page with custom hooks, and want to use a different set of hooks for products list on single product page (affecting upsells products list), I can not seem to do so currently.

**Suggested solution:**

To resolve, could you please pass additional attribute to `woocommerce_blocks_hook_compatibility_additional_data`, maybe `$this`?
So it becomes:
[`$additional_hook_data = apply_filters( 'woocommerce_blocks_hook_compatibility_additional_data', array(), $this );`](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/src/Blocks/Templates/AbstractTemplateCompatibility.php#L165)

**Comment by kmanijak** [comment]
Hi, thanks for raising it!

I think it's a valid point. I prepared a draft PR in which I passed a class name in which the filter was called: https://github.com/woocommerce/woocommerce/pull/45156. Please follow the PR for further updates on this issue and also, feel free to comment and leave feedback :)
