### ISSUE TITLE
Disabling Order Attribution causes critical error. 

### ISSUE THREAD

**Issue by StenderIternum** [woothemes/woocommerce#44443]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you have the legacy order storage, and have not syncronized orders yet, and try to disable order attribution (which is on by default) the site gets a critical error : 

Only way to get rid of order attribution was to use a php function instead : update_option('woocommerce_feature_order_attribution_enabled','');

An error of type E_ERROR occurred on line 312 in the file /home/royalgra/public_html/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php. Error message: Uncaught Exception: The authoritative table for orders storage can't be changed while there are orders out of sync in /home/royalgra/public_html/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:312
Stack trace:
#0 [internal function]: Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController->process_pre_update_option('', 'woocommerce_cus...', 'no')
#1 /home/royalgra/public_html/wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php(158): call_user_func_array(Array, Array)
#2 /home/royalgra/public_html/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController->__call('process_pre_upd...', Array)
#3 /home/royalgra/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#4 /home/royalgra/public_html/wp-includes/option.php(784): apply_filters('pre_update_opti...', '', 'woocommerce_cus...', 'no')
#5 /home/royalgra/public_html/wp-content/plugins/woocom

### Expected behavior

I would expect that it would just save the option to not have order attribution, and stop enqueuing sourcebuster.js

### Actual behavior

It crashes

### Steps to reproduce

go into the WP Admin -> Woocommerce -> Settings -> Advanced tab -> Features sub-tab, and then uncheck the Order Attribution box, while not having syncronized orders and is using legacy order storage. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): xxx
Site address (URL): xxx
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: ❌ 6.4.2 - Der findes en nyere version af WordPress (6.4.3)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 8.5.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.17-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: nka6_
Total databasestørrelse: 508.89MB
Database datastørrelse: 315.45MB
Database indexstørrelse: 193.44MB
nka6_woocommerce_sessions: Data: 4.02MB + Index: 0.02MB + Engine InnoDB
nka6_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nka6_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
nka6_woocommerce_order_itemmeta: Data: 34.56MB + Index: 29.09MB + Engine InnoDB
nka6_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nka6_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_actionscheduler_actions: Data: 5.06MB + Index: 7.72MB + Engine InnoDB
nka6_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_actionscheduler_logs: Data: 5.11MB + Index: 3.03MB + Engine InnoDB
nka6_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_cartflows_ca_cart_abandonment: Data: 6.52MB + Index: 0.08MB + Engine InnoDB
nka6_cartflows_ca_email_history: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
nka6_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
nka6_comments: Data: 19.55MB + Index: 11.09MB + Engine InnoDB
nka6_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
nka6_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nka6_e_submissions: Data: 0.16MB + Index: 0.27MB + Engine InnoDB
nka6_e_submissions_actions_log: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
nka6_e_submissions_values: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
nka6_jetpack_sync_queue: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
nka6_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_litespeed_img_optm: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
nka6_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nka6_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_notification_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_options: Data: 10.45MB + Index: 0.34MB + Engine InnoDB
nka6_pmxe_exports: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
nka6_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
nka6_pmxe_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
nka6_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_postmeta: Data: 126.55MB + Index: 66.16MB + Engine InnoDB
nka6_posts: Data: 13.52MB + Index: 3.73MB + Engine InnoDB
nka6_po_plugins: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nka6_rank_math_analytics_gsc: Data: 39.08MB + Index: 52.19MB + Engine InnoDB
nka6_rank_math_analytics_inspections: Data: 0.44MB + Index: 0.31MB + Engine InnoDB
nka6_rank_math_analytics_objects: Data: 0.23MB + Index: 0.08MB + Engine InnoDB
nka6_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_sbi_feed_caches: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
nka6_sbi_instagram_feeds_posts: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
nka6_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_sbi_instagram_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
nka6_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_search_filter_cache: Data: 3.47MB + Index: 3.27MB + Engine InnoDB
nka6_search_filter_term_results: Data: 0.20MB + Index: 0.05MB + Engine InnoDB
nka6_termmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
nka6_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
nka6_term_taxonomy: Data: 0.25MB + Index: 0.03MB + Engine InnoDB
nka6_tinvwl_analytics: Data: 0.20MB + Index: 0.09MB + Engine InnoDB
nka6_tinvwl_items: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
nka6_tinvwl_lists: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
nka6_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
nka6_users: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
nka6_wcpdf_invoice_number: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
nka6_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
nka6_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
nka6_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wc_customer_lookup: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
nka6_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
nka6_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nka6_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
nka6_wc_order_product_lookup: Data: 2.52MB + Index: 2.61MB + Engine InnoDB
nka6_wc_order_stats: Data: 2.52MB + Index: 1.06MB + Engine InnoDB
nka6_wc_order_tax_lookup: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
nka6_wc_product_attributes_lookup: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
nka6_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wc_product_meta_lookup: Data: 0.13MB + Index: 0.20MB + Engine InnoDB
nka6_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nka6_wfconfig: Data: 2.41MB + Index: 0.00MB + Engine InnoDB
nka6_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wffilemods: Data: 14.55MB + Index: 0.00MB + Engine InnoDB
nka6_wfhits: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
nka6_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wfissues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
nka6_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
nka6_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wflogins: Data: 0.45MB + Index: 0.16MB + Engine InnoDB
nka6_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
nka6_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
nka6_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nka6_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
nka6_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
nka6_wpr_rocket_cache: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
nka6_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
nka6_yoast_indexable: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
nka6_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
nka6_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
nka6_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
attachment: 2812
custom_css: 1
elementor_font: 2
elementor_icons: 1
elementor_library: 42
envato_tk_import: 5
nav_menu_item: 133
notification: 1
page: 32
post: 3
product: 923
product_variation: 1
revision: 1351
search-filter-widget: 10
shop_coupon: 39
shop_order: 10720
shop_order_refund: 87
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

ManageWP - Worker: af GoDaddy – 4.9.19
Advanced Coupons for WooCommerce Free: af Rymera Web Co – 4.5.9.2
Advanced Custom Fields PRO: af WP Engine – 6.2.5
FiboSearch - AJAX Search for WooCommerce: af FiboSearch Team – 1.26.1
Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: af Usercentrics A/S – 4.3.4
Yoast Duplicate Post: af Enrico Battocchi & Team Yoast – 4.5
GTM4WP: af Thomas Geiger – 1.19.1
Dynamic.ooo - Dynamic Content for Elementor: af Dynamic.ooo – 2.12.7
DynamicConditions: af RTO GmbH – 1.6.2
Ele Custom Skin: af Dudaster.com – 3.1.7
Elementor Pro: af Elementor.com – 3.18.2
Elementor: af Elementor.com – 3.19.0
Include Klaviyo for Elementor pro: af Thong Nguyen – 2.1
Smash Balloon Instagram Feed: af Smash Balloon – 6.2.7
Klaviyo: af Klaviyo
Inc. – 3.3.3

Max Mega Menu: af megamenu.com – 3.3
Notification: af BracketSpace – 8.0.15
ITM Ønskeskyen: af Jesper Stender – 0.4
PixelYourSite: af PixelYourSite – 9.4.7.1
Post Types Order: af Nsp Code – 2.1.2
Billwerk+ Payments for WooCommerce: af Billwerk+ – 1.6.3
Search & Filter - Elementor Extension: af Code Amp – 1.2.3
Search & Filter Pro: af Code Amp – 2.5.17
Rank Math SEO: af Rank Math – 1.0.211
Filesizes in library: af Jesper Stender – 1.2
Smart Send Shipping til WooCommerce: af Smart Send ApS – 8.0.27
TI WooCommerce Wishlist: af TemplateInvaders – 2.8.0
UpdraftPlus - Backup/Restore: af UpdraftPlus.Com
DavidAnderson – 1.23.16

Product Feed PRO for WooCommerce: af AdTribes.io – 13.2.3
PDF Invoices & Packing Slips for WooCommerce: af WP Overnight – 3.7.7
PPOM for WooCommerce: af Themeisle – 32.0.9
WooCommerce Shipment Tracking: af WooCommerce – 2.4.4
WooCommerce: af Automattic – 8.5.2
Wordfence Security: af Wordfence – 7.11.1
WP All Export Pro: af Soflyy – 1.8.6
WP Mail SMTP: af WP Mail SMTP – 3.11.1
WP All Export - WooCommerce Export Add-On Pro: af Soflyy – 1.0.9

### Inactive Plugins (5) ###

Asset CleanUp: Page Speed Booster: af Gabe Livan – 1.3.9.3
Envato Elements: af Envato – 2.0.12
Jetpack: af Automattic – 13.0
MC4WP: Mailchimp for WordPress: af ibericode – 4.9.11
WP Rocket: af WP Media – 3.15.7

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: af GoDaddy –

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop basisside: #52 - /shop/
Kurv: ❌ Siden indeholder ikke [woocommerce_cart] shortcode eller woocommerce/cart blokken.
Checkout: #54 - /kasse/
Min konto: #55 - /min-konto/
Vilkår og betingelser: #2105 - /handelsbetingelser/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.6.4
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-08 14:17:41 +00:00
Options: ✔
Notes: 196
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 64
Oldest: 2024-01-08 10:24:41 +0000
Newest: 2024-02-01 08:33:37 +0000

Complete: 11.145
Oldest: 2024-01-11 08:30:16 +0000
Newest: 2024-02-08 05:09:26 +0000

Failed: 152
Oldest: 2022-09-15 11:58:21 +0000
Newest: 2024-01-23 09:19:42 +0000

Pending: 3
Oldest: 2024-02-08 08:30:42 +0000
Newest: 2024-02-08 19:01:46 +0000

### Status report information ###

Generated at: 2024-02-08 07:04:13 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by layoutd** [comment]
Hi @StenderIternum, thanks for the report. I was unable to reproduce the error:
![lwHe3Z.gif](https://github.com/woocommerce/woocommerce/assets/228780/79dd150f-abdd-4138-96c0-27699747a9e7)

Do you have any more information, or were you able to reproduce it the error more than once? If so, can you confirm the error doesn't occur when just saving that settings screen without any changes?

**Comment by StenderIternum** [comment]
It happened again on a different website - 


2024-02-22T14:16:30+00:00 CRITICAL Uncaught Exception: The authoritative table for orders storage can't be changed while there are orders out of sync in /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:312
Stack trace:
#0 [internal function]: Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController->process_pre_update_option()
#1 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php(158): call_user_func_array()
#2 /var/www/www.emofabrik.dk/www/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController->__call()
#3 /var/www/www.emofabrik.dk/www/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/www.emofabrik.dk/www/wp-includes/option.php(784): apply_filters()
#5 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(951): update_option()
#6 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php(233): WC_Admin_Settings::save_fields()
#7 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-advanced.php(492): WC_Settings_Page->save_settings_for_current_section()
#8 /var/www/www.emofabrik.dk/www/wp-includes/class-wp-hook.php(324): WC_Settings_Advanced->save()
#9 /var/www/www.emofabrik.dk/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /var/www/www.emofabrik.dk/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(77): do_action()
#12 /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(179): WC_Admin_Settings::save()
#13 /var/www/www.emofabrik.dk/www/wp-includes/class-wp-hook.php(324): WC_Admin_Menus->save_settings()
#14 /var/www/www.emofabrik.dk/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#15 /var/www/www.emofabrik.dk/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /var/www/www.emofabrik.dk/www/wp-settings.php(665): do_action()
#17 /var/www/www.emofabrik.dk/www/wp-config.php(122): require_once('/var/www/www.em...')
#18 /var/www/www.emofabrik.dk/www/wp-load.php(50): require_once('/var/www/www.em...')
#19 /var/www/www.emofabrik.dk/www/wp-admin/admin.php(34): require_once('/var/www/www.em...')
#20 {main}
  thrown i /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php på linje 312

**Comment by layoutd** [comment]
Thanks for the followup @StenderIternum. Can you try just saving that settings page without any changes to see if it works?

**Comment by StenderIternum** [comment]
Hi @layoutd - Yes I just tried that, and you are right, there was a critical error. 

2024-02-23T08:00:52+00:00 CRITICAL Uncaught Exception: The authoritative table for orders storage can't be changed while there are orders out of sync in /var/www/www.emofabrik.dk/www/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php:312

**Comment by StenderIternum** [comment]
Any Idea on what it could be then?

**Comment by layoutd** [comment]
This error usually indicates that the merchant is trying to change the order data storage method without synchronizing order information between the two methods first:
![image](https://github.com/woocommerce/woocommerce/assets/228780/2e5de68b-9100-4ebe-80fe-123471ff2b9a)

If you're not changing that setting, then the error shouldn't be raised. I'll see if we've had any other cases like this, but in the meantime, if you need to save those settings, you may try synchronizing the pending orders and trying again once they are synchronized.

Or, if you'd just like to disable Order Attribution, you can do using the `wp-cli` command I mentioned here: https://github.com/woocommerce/woocommerce/issues/43681#issuecomment-1955194195

**Comment by StenderIternum** [comment]
I used `update_option('woocommerce_feature_order_attribution_enabled','');` to update it

**Comment by layoutd** [comment]
> I used `update_option('woocommerce_feature_order_attribution_enabled','');` to update it

👍🏻  Do you need to use that settings form any further right now?

**Comment by StenderIternum** [comment]
Well no, I just needed to get the new scripts from woocommerce removed, since it was not GDPR compliant (and it was really weird that it was auto enabled, since it is illegal for all EU users) - But it is still a bug report - since it it happening on two different sites, with different setups.

**Comment by layoutd** [comment]
Thanks for the details. I'll leave the issue open while I wait to hear about whether this is a known issue  or for other instances.

There was some informative discussion about compliance on this [support forum post](https://wordpress.org/support/topic/woocommerce-8-5-1-order-attribution-gdpr-compliance/). Additionally, the feature is fully compatible with WP Consent API from 8.6 onwards (#43012), so enabling any compatible plugin will allow visitors to consent (or not) to the feature.

**Comment by layoutd** [comment]
@StenderIternum, I haven't heard any definitive word on whether this issue has been reported before but issue https://github.com/woocommerce/woocommerce/issues/45225 looks related (if not the same). I'll close this issue in favor of that one, and when it is resolved you can confirm that your issue no longer occurs, as well.
