### ISSUE TITLE
[Product editor block]: The Publish button should remain disabled if there is no change in the new form

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#44469]
Mimicking the `Publish` post button behavior in the new editor. When there is no change in the form, the `Publish` button should remain disabled, and nothing should happen if the user clicks on it.

Currently, the form validation is triggered if the user clicks `Products > Add New` and then clicks the `Publish` button.

**Comment by octaedro** [comment]
@j111q Could you confirm this is the behavior we want for that button?

**Comment by mattsherman** [comment]
Closing - fixed previously
