### ISSUE TITLE
Product Gallery (beta) thumbnails disappear after add to cart on mobile

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#44483]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Only on mobile, after adding a product to the cart, the photo thumbnails disappear, and only the main product image is showing.
This happens only if the thumbnails are placed **below** the main product image.
<img width="279" alt="Screenshot 2024-02-08 at 11 15 37 PM" src="https://github.com/woocommerce/woocommerce/assets/47855768/1265f7fc-1253-4d51-80c0-f3197f245927">
I can reproduce the issue on iPhone 13 Pro and iPhone Xs Max. I **can't** reproduce it in the Google Chrome Developer tools. Only use real mobile devices.
As shown in the attached screen recording, the thumbnails reappear if I close Safari and reopen it.

https://github.com/woocommerce/woocommerce/assets/47855768/ee1ccbbc-486b-45a9-8157-74a38e4678b8

Example product page: https://k6scjuogs6.onrocket.site/product/hat/

### Expected behavior

The product thumbnails should always be visible.

### Actual behavior

On mobile, when the thumbnails are placed **below** the main product image, product thumbnails disappear after adding a product to the cart.

### Steps to reproduce

1. in the single product template, add the Product Gallery (beta) block
2. Place the thumbnails **below** the main product image
3. Open the product page from a mobile device (not the developer tools in Google Chrome)
4. The product thumbnails should be visible at this point
5. Add the product to the cart. The page reloads with the green notice that the product has been added to the cart
6. The product thumbnails are missing and only the main product image is shown.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://k6scjuogs6.onrocket.site
Site address (URL): https://k6scjuogs6.onrocket.site
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 100000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0
WC Database Prefix: wp_
Total Database Size: 8.37MB
Database Data Size: 6.51MB
Database Index Size: 1.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_options: Data: 5.11MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 21
page: 7
post: 3
product: 12
product_variation: 2
revision: 70
shop_order_placehold: 6
wp_font_face: 1
wp_font_family: 1
wp_global_styles: 2
wp_navigation: 2
wp_template: 4
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Gutenberg: by Gutenberg Team – 17.6.5
WooCommerce: by Automattic – 8.6.0-rc.1

### Inactive Plugins (6) ###

Ajax add to cart for WooCommerce: by QuadLayers – 2.2.9
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Hello Dolly: by Matt Mullenweg – 1.7.2
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
WooCommerce Beta Tester: by WooCommerce – 2.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: CrafterCommerce
Version: 1.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/k6scbxm/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/k6scbxm/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/k6scbxm/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php
craftercommerce/parts/checkout-header.html
craftercommerce/parts/mini-cart.html
craftercommerce/templates/archive-product.html
craftercommerce/templates/order-confirmation.html
craftercommerce/templates/page-cart.html
craftercommerce/templates/page-checkout.html
craftercommerce/templates/product-search-results.html
craftercommerce/templates/single-product.html
craftercommerce/templates/taxonomy-product_attribute.html
craftercommerce/templates/taxonomy-product_cat.html
craftercommerce/templates/taxonomy-product_tag.html

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-09 01:54:39 +00:00
Options: ✔
Notes: 72
Onboarding: skipped

### Action Scheduler ###

Complete: 49
Oldest: 2024-01-31 01:55:40 +0000
Newest: 2024-02-08 21:53:23 +0000

Failed: 1
Oldest: 2024-01-31 01:56:44 +0000
Newest: 2024-01-31 01:56:44 +0000

Pending: 1
Oldest: 2024-02-09 12:07:36 +0000
Newest: 2024-02-09 12:07:36 +0000

### Status report information ###

Generated at: 2024-02-08 22:24:18 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ResponsiveFlow** [comment]
Hi @moon0326, I just tested the latest WooCommerce nightly which should include the merged PR, but the issue hasn't been fixed.

**Comment by ilyasfoo** [comment]
Re-opening since it was mistakenly tagged from #44484

**Comment by ilyasfoo** [comment]
I was able to reproduce this issue with iPhone 11, iOS 17.2.1, with both Safari 17.2 and Chrome 121.

**Comment by thealexandrelara** [comment]
Thank you for opening this issue and providing clear instructions on reproducing it, @tomxygen! I can reproduce it in Safari and Chromium-based browsers on iPhone and iPad.

The "Add to Cart" button triggers a page reload. When that happens and the elements on the page are reloaded, the height of the thumbnails is, for some reason, computed as almost zero (2px). Essentially, if you visit the product page and tap to reload, the issue also occurs.

This issue is included in our backlog, and we will have to investigate it further, as it seems to be affecting iOS and iPadOS devices.

Also, thanks @ilyasfoo for double-checking and confirming this issue is also happening to you.

**Comment by ResponsiveFlow** [comment]
hey @thealexandrelara 
any updates on the issue?

**Comment by thealexandrelara** [comment]
> hey @thealexandrelara any updates on the issue?

Hey, thanks for checking in!

We're currently prioritizing our backlog, and this issue is definitely on our radar. While we haven't begun development work on a fix yet, we aim to tackle it as soon as possible. I'll comment again if anything changes; hopefully, I'll have better news 😅.
