### ISSUE TITLE
[Enhancement] Link home payments task to Payments Connect page for WooPayments-eligible countries

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#44499]
### Describe the solution you'd like

For WooPayments-eligible store countries, we should direct merchants straight from the "Set up payments" home task to the Payments Connect page (under the Payments main menu item) and avoid the Set up payments screens:

![Screenshot 2024-02-09 at 14 42 37](https://github.com/woocommerce/woocommerce/assets/8830539/85cdf0f8-82e2-4d9b-93a5-84bdb4994988)

The Payments Connect page is capable of installing WooPayments (if not installed), activating it, and starting the onboarding. 

The benefits are:
- consolidate WooPayments flows
- reduce complexity in our flows
- reduce maintenance burden and the likelihood of disjointed experiences

cc @elizaan36

**Comment by vladolaru** [comment]
Updated the issue after @elizaan36 pointed out the scenario where the store country is in a non-eligible country.

**Comment by elizaan36** [comment]
sounds good to me! This will make it more important to surface the APM discovery on the payments connect so we should focus on those details next.

**Comment by vladolaru** [comment]
TODO: When this is closed, our FigJam onboarding flows (tvclrJLW8LJHhOojcKZGy6-fi-0_1) should be updated

**Comment by elazzabi** [comment]
@vladolaru The Connect page isn't available if WooPayments isn't installed, should we add another check for that? (In addition to the supported country)

EDIT: Added the check to my PR

**Comment by vladolaru** [comment]
I've created a follow-up issue https://github.com/woocommerce/woocommerce/issues/45625 to tackle other areas that should funnel to the Connect page.
