### ISSUE TITLE
[Enhancement]: Order attribution "Origin" - Handle source type `mobile_app`

### ISSUE THREAD

**Issue by selanthiraiyan** [woothemes/woocommerce#44490]
### Describe the solution you'd like

For orders created from the Web, we set the `source_type` as `admin`, and we display the order attribution as below.

![image](https://github.com/woocommerce/woocommerce/assets/524475/730158d8-7d34-4440-a2bf-24f54b1bc88b)

For orders created from the Woo Mobile App, the `source_type` `meta_data` value will be set as `mobile_app`. 

While calculating the value for "Origin", we should start handling the `source_type` value `mobile_data` and display the "Origin" as "Mobile App".

### Additional context

https://github.com/woocommerce/woocommerce-ios/pull/11966 - PR in which the Woo Mobile App starts setting the `source_type` as `mobile_app` for new orders

**Comment by Brianmitchtay** [comment]
Looks like this covers the issue I opened several weeks ago too #44167

Closing that as well with this cross reference
