### ISSUE TITLE
Remove experimental "Add to Cart" block

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#44503]
### Description
Remove the "Add to Cart" Product Element: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/atomic/blocks/product-elements/add-to-cart

### Rationale
- it’s [experimental](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/add-to-cart/index.ts#L26)
- it seems untouched for ~3 years
- there’s new "Add to Cart Form" block which serves the same purpose

### Tech notes
It's been done once in https://github.com/woocommerce/woocommerce-blocks/pull/11948. For some reason it caused some incompatibility between the All Products block and the Mini-Cart block and it was reverted in https://github.com/woocommerce/woocommerce-blocks/pull/12033.

**Comment by gigitux** [comment]
Thanks for opening this issue! I agree with you!
It seems that the Cross Sell Product block uses this block ([source code](https://github.com/woocommerce/woocommerce-blocks/blob/321b3d7043b1619a469a3c22e053e336a1a0b5ea/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx)), but this latter isn’t under the experimental flag. 🤔 
 
Shouldn’t we remove the Add to Cart block? But how does it works currently if the Add to Cart block is available only on the experimental build? 

cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.

**Comment by nielslange** [comment]
> cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.

Thanks for your ping, @gigitux! The Cross-Sell Product block indeed uses the Add to Cart block. Before removing the Add to Cart block, we should adjust the Cross-Sell Product block to use the Add to Cart Form block instead.

@kmanijak I guess removing the Add to Cart block is not urgent, isn't it? I'm asking to know how [Cross-Sells Products block: Replace Add to Cart block with Add to Cart Form block](https://github.com/woocommerce/woocommerce-blocks/issues/8858) should be prioritised.

**Comment by gigitux** [comment]
> > cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.
> 
> Thanks for your ping, @gigitux! The Cross-Sell Product block indeed uses the Add to Cart block. Before removing the Add to Cart block, we should adjust the Cross-Sell Product block to use the Add to Cart Form block instead.
> 
> @kmanijak I guess removing the Add to Cart block is not urgent, isn't it? I'm asking to know how [Cross-Sells Products block: Replace Add to Cart block with Add to Cart Form block](https://github.com/woocommerce/woocommerce-blocks/issues/8858) should be prioritised.

Absolutely! It isn't urgent! Also, I don't know if the Add to Cart Form block can replace the Add to Cart block currently.

But how does it works currently if the Add to Cart block is available only on the experimental build? Should we double-check this?

**Comment by nielslange** [comment]
> But how does it works currently if the Add to Cart block is available only on the experimental build? Should we double-check this?

Currently, the Cross-Sells block is registered as core element:

https://github.com/woocommerce/woocommerce-blocks/blob/84d5e951d8bb3f9f533e2f9df0e1efeb9771f4f1/assets/js/blocks/cart/inner-blocks/cart-cross-sells-block/index.tsx#L12-L23

I just created a https://jurassic.ninja/ site with the WooCommerce plugin only, and the Cross-Sells block is visible in the editor:

<img width="2876" alt="Screenshot 2023-03-27 at 14 43 55" src="https://user-images.githubusercontent.com/3323310/227874375-05e36672-1db7-4e2d-b07a-5258a9e484ff.png">

When viewing the Cart block in the frontend, the Cross-Sells block is also visible:

<img width="2877" alt="Screenshot 2023-03-27 at 14 49 47" src="https://user-images.githubusercontent.com/3323310/227875687-2e42d5dc-c6ab-4610-9c24-e3edfc52f252.png">

You can reproduce this with the following steps:

- Head over to https://splendid-nazca.jurassic.ninja/product/cap/.
- Add that product to your cart.
- Go to https://splendid-nazca.jurassic.ninja/cart/.
- Verify that the Cross-Sells block is visible.

**Comment by kmanijak** [comment]
> But how does it works currently if the Add to Cart block is available only on the experimental build? Should we double-check this?

I was checking for a potential bug in the feature flag, but I realized what's going on.

Add to Cart block is registered as an experimental block, so the block is not available in the inserter nor the block storage. But nothing prevents a developer to [import the block directly and use it](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx#L19).

@nielslange, keep in mind, the case for Grouped product was never covered and `<p>This is a placeholder for the grouped products form element.</p>` will be displayed ([source](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/add-to-cart/product-types/grouped.tsx))

**Comment by gigitux** [comment]
> Add to Cart block is registered as an experimental block, so the block is not available in the inserter nor the block storage. But nothing prevents a developer to [import the block directly and use it](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx#L19).

TIL :D I was convinced that a block must be registered for use by other blocks.

We could check how the add-to-cart form block inside the Cross-Sell Product block works, but it is a very low-priority issue. Could we handle this issue as a cooldown issue?

**Comment by nielslange** [comment]
> @nielslange, keep in mind, the case for Grouped product was never covered and <p>This is a placeholder for the grouped products form element.</p> will be displayed ([source](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/add-to-cart/product-types/grouped.tsx))

@kmanijak That would be a problem, as it would mean that a grouped product cannot be a Cross-Sells product, right? What Add to Cart buttons do grouped products currently have?

**Comment by wavvves** [comment]
It seems this block uses the SelectControl imported from `wordpress-components` alias which should be removed, and is the only thing consuming it. Removing this block should include work to cleanup that dependency 👍🏼
