### ISSUE TITLE
[Enhancement]: WooCommerce Order Listing Custom Sortable column

### ISSUE THREAD

**Issue by kuldeep3** [woothemes/woocommerce#44501]
### Describe the solution you'd like

Before upgrading to WooCommerce HPOS, I utilized custom columns in the order listing, specifically **"Shipping Location"** and **"Delivery Date,"** which were also sortable. Since the upgrade, I've managed to display these columns and their data by updating certain hooks, such as replacing `manage_edit-shop_order_columns` with `manage_woocommerce_page_wc-orders_columns`, and `manage_shop_order_posts_custom_column` with `manage_woocommerce_page_wc-orders_custom_column`. However, I've encountered difficulty in making these custom columns sortable.

I attempted to address this by using the `add_filter( "manage_edit-wc_orders_sortable_columns", array( $this, 'sort_columns' ) );` with a callback function as follows:

```
public function sort_columns( $columns ) {
    $columns['delivery_date']     = 'Delivery Date';
    $columns['shipping_location'] = 'Shipping Location';
    return $columns;
}

```

For retrieving results, I employed `add_action( 'pre_get_posts', array( $this, 'slice_orderby' ) );` with the following callback function:

```
public function slice_orderby( $query ) {
    $orderby = $query->get( 'orderby' );
    
    if ( 'Delivery Date' === $orderby ) {
        $order = $_GET['order'];
        $query->set( 'meta_key', 'delivery_date' );
        $query->set( 'orderby', 'meta_value' );
        $query->set( 'order', $order );
        $query->set( 'type', 'DATETIME' );
    }
    
    if ( 'Shipping Location' === $orderby ) {
        $order = $_GET['order'];
        $query->set( 'meta_key', '_shipping_location' );
        $query->set( 'orderby', 'meta_value' );
        $query->set( 'order', $order );
        $query->set( 'type', 'STRING' );
    }
}

```

However, the generated query does not align properly with the sortable column values in terms of order and orderby, leading to inaccurate data representation.

Despite researching various articles and documentation, I couldn't find any mention of sortable columns in the order listing; most examples focus on product listing.

Sortable columns in the order listing significantly facilitate our store's day-to-day operations. Any assistance in addressing this matter promptly would be greatly appreciated.

**Comment by jorgeatorres** [comment]
Hi @kuldeep3!

Thanks for reaching out.

> However, the generated query does not align properly with the sortable column values in terms of order and orderby, leading to inaccurate data representation.

Could you clarify what you mean by that? Even though HPOS uses other hooks, it should be possible to re-create what you had before.

I recently answered a similar question [in the community Slack](https://woocommercecommunity.slack.com/archives/C4TNYTR28/p1707490617248699):

> The `meta_query` argument is meant to be used to filter things, not for sorting/ordering purposes. That's why it removes orders that don't match. There are two ways to go about this: you could alter the SQL query itself using the `woocommerce_orders_table_query_clauses` filter ([see in code](https://github.com/woocommerce/woocommerce/blob/a6210ba312c2fdd343ff5df892e1a43f9bfb22cd/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php#L859-L878)) to join with the meta table and also modify the `orderby`. The other alternative would be to write a more complex `meta_query` that captures both orders with the key and those without it and then use `orderby => 'meta_value_num'` (assuming the value is numeric) to do the sorting. Something along these lines:
> 
> ```php
> $orders = wc_get_orders(
>             array(
>                 'return' => 'ids',
>                 'limit'  => 5,
>                 'meta_query' => array(
>                     'relation' => 'OR',
>                     array(
>                         'key' => 'my_meta',
>                         'compare' => 'EXISTS',
>                     ),
>                     array(
>                         'key' => 'my_meta',
>                         'compare' => 'NOT EXISTS',
>                     )
>                     ),
>                 'orderby' => 'meta_value_num',
>                 'order'   => 'DESC',
>             )
>         );
> ```
> 
> This might or might not be exactly what you want, so you might need to adjust.

Please let me know if that helps. If we are indeed missing some customizability on our end, we'll be happy to add it.

**Comment by jorgeatorres** [comment]
There hasn't been any movement here since we last replied (~4 months ago). Closing as stale.
