### ISSUE TITLE
woocommerce_after_order_notes action doesn't work

### ISSUE THREAD

**Issue by farhadsakhaei** [woothemes/woocommerce#44521]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

I am developing a plugin that inserts some fields to woocommerce checkout fields,
But seems this action doesn’t work at all from plugin:
```
add_action( 'woocommerce_after_order_notes', 'hello', 10, 1 );
function hello(){
     echo 'hello';
}
```
I tested to check if the funtion calls or not, but the function doesn’t call at all
What’s the problem?
Thank you

### Expected behavior

fire the action

### Actual behavior

Doesn't fire

### Steps to reproduce

Create a function and add action

### WordPress Environment

Latest WP and WooCommerce

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@farhadsakhaei Github is for reporting issues with WooCommerce. For custom coding questions we suggest you ask in the [WooCommerce Community Slack](https://woo.com/community-slack/). I'll mark this issue as a question.

**Comment by farhadsakhaei** [comment]
@rrennick 
Thank you for your reply,
I Clicked on Slack page "Let's go" But got the following error:

This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by rrennick** [comment]
@farhadsakhaei Thanks for letting us know. I passed this on to folks who will look into it.

**Comment by brentmackinnon** [comment]
Fixing! @farhadsakhaei here's a better link: https://join.slack.com/t/woocommercecommunity/shared_invite/zt-2cmtfj2xc-TrZyE5fkTI17Nkg2yZC22A
