### ISSUE TITLE
[Enhancement]: Add a hook-able custom JavaScript event for when a new paginated Product Collection page is loaded (using a fetch request)

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#44525]
### Describe the solution you'd like

My scenario:

- I'm using the WooCommerce Product Collection block.
- I'm using a wishlist plugin (YITH WooCommerce Wishlist).
- I'm using an option on the wishlist plugin to add the wishlist buttons with Ajax after the page loads (to prevent cache issues).
- **When using the pagination to load more Product Collection pages - they are missing the Add to Wishlist buttons.**
- I assume that every time a paginated page has finished loading, the Ajax for adding the buttons needs to be called again.
- I've tried to hook to a native event, but couldn't find a suitable one (maybe I missed something).
- While I opened a support ticket with the plugin, I think this might be a wider issue, and that more plugins and use cases can benefit from a JS event to hook to.

### Describe alternatives you've considered

Adding a custom JavaScript event to hook to.

### Additional context

This is a solution suggested by the plugin authors:

```   
function yith_wcwl_reload_fragments() {
        $jquery = 'jQuery(".wp-block-query-pagination a").click(function () {
            setTimeout(function() {
                jQuery(document).trigger("yith_wcwl_reload_fragments");
            }, 2000);
        });';

        wp_add_inline_script('jquery-yith-wcwl', $jquery);
        wp_add_inline_script('jquery-yith-wcwl-user', $jquery);
}

add_action('wp_enqueue_scripts', 'yith_wcwl_reload_fragments', 999);
``` 

The 2 second assumption does not feel like a solid solution. Anyway, it doesn't work when going back in the pagination (maybe because of `preventDefault()`?). It feels like for a good solution there is no way around adding a custom event.

**Comment by asafm7** [comment]
Another use-case might be analytics events (Google Analytics etc.)

**Comment by kmanijak** [comment]
Hi @asafm7!

Thanks for raising this issue!

Can I confirm it's based on the change from pagination that required a full page reload to client-side navigation that doesn't require reload?

We have this issue https://github.com/woocommerce/woocommerce/issues/43395 in which we want to resolve the problem of interactive blocks inside Product Collection. But my understanding is YITH WooCommerce Wishlist is not block-based so it's different.

The suggestion to expose a custom JavaScript events makes sense. Give us some time to rethink it as it should be a future-proof solution aligned with the rest of WooCommerce but I'm moving the issue to the backlog and we'll think about it soon. Thanks for raising this!

**Comment by asafm7** [comment]
Thanks @kmanijak for your reply.

> Can I confirm it's based on the change from pagination that required a full page reload to client-side navigation that doesn't require reload?

I'm not sure I understand the question.

I will better describe the scenario:

- YITH has an Add to Wishlist block.
- This block is placed inside the Product Template block (inside the Product Collection block): 
![image](https://github.com/woocommerce/woocommerce/assets/14274769/243739de-2de6-444d-a660-4906fb0b2540)
- The YITH plugin has an Ajax option for loading the buttons (to bypass potential cache issues).
- When the Ajax option is activated, the YITH Add to Wishlist block only outputs a placeholder HTML (invisible to the user).
- The placeholder is being replaced with the actual button via Ajax on page load (or another event).
- When loading a new paginated Product Collection page, the event that triggers the Ajax isn't being dispatched so the placeholders aren't being replaced, and the Add to Wishlist buttons aren't being added.
- A custom event will allow easily calling Ajax to add the buttons on each paginated page load.

While a full page reload (mentioned in the ticket you referred to) can solve it, it feels like an overkill that will compromise user experience.

Please let me know if this is clear enough, or if more information is required.

Thanks again.

**Comment by kmanijak** [comment]
Thanks for the further explanation, that's helpful. It's exactly the case we want to resolve in https://github.com/woocommerce/woocommerce/issues/43395. We may consider your suggestion to emit some events in addition to page change.

In the meantime, let's stick to https://github.com/woocommerce/woocommerce/issues/43395 as a central point to discuss the problem you raised and we're planning to tackle that issue in upcoming weeks.

Having said that, I'll go ahead and close this issue to keep the backlog organized but please note the closed issues can still be commented on. 🙌

**Comment by asafm7** [comment]
Thanks @kmanijak. I will follow the other thread.
