### ISSUE TITLE
[Enhancement]: Allow the use of block notices when using classic themes

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#44538]
### Describe the solution you'd like

When using block themes, block notices are displayed. When using classic themes, classic notices are displayed. It's also possible to display classic notices when using block themes. However, it's currently not possible to display block notices when using classic themes. 

This issue aims to enable merchants to display block notices even when using classic themes.

### Describe alternatives you've considered

n/a

### Additional context

While the text of block notices is visible when using classic themes, the SVG and the styles are missing. This is related to the following section:

https://github.com/woocommerce/woocommerce/blob/4ae60196eaf9d0abf93297a8d83d9f5a2e541c39/plugins/woocommerce/src/Blocks/Domain/Services/Notices.php#L44-L48

The SVG and the styles are displayed correctly, when changing this part as follows:

```php
if ( wp_is_block_theme() ) {
	add_filter( 'wc_get_template', [ $this, 'get_notices_template' ], 10, 5 );
}

add_filter( 'woocommerce_kses_notice_allowed_tags', [ $this, 'add_kses_notice_allowed_tags' ] );
add_action( 'wp_head', [ $this, 'enqueue_notice_styles' ] );
```

**Comment by wavvves** [comment]
Hi @nielslange, while looking at this, abstracting from classic theme vs block theme, I thought about a different angle. Should we be always enqueing notices styles even when there are none to be displayed? Page views without notices account for the majority of views across WC 🤔

**Comment by nielslange** [comment]
Thanks for raising this point, @wavvves. It's my understanding that we need to load the notices styles first so that when a notice appears that the expected styles can be applied. And I was under the impression that the loaded styles are cached, meaning their performance impact should be minimal. 

May I ask what your solution would look like? Would you enqueue the notice styles as soon as a notice appears? And would you dequeue the notice styles after it, or keep them enqueued?

**Comment by tiago-sartor** [comment]
Yes this feature would be great, the classic notices look sooo outdated.

**Comment by wavvves** [comment]
> Thanks for raising this point, @wavvves. It's my understanding that we need to load the notices styles first so that when a notice appears that the expected styles can be applied. And I was under the impression that the loaded styles are cached, meaning their performance impact should be minimal.
> 
> May I ask what your solution would look like? Would you enqueue the notice styles as soon as a notice appears? And would you dequeue the notice styles after it, or keep them enqueued?

I was thinking of something more simple like enqueing styles only if the notices array is not empty. But we might bump into problems around the timing of the used hooks, and the optimization benefits might be negligible as the CSS payload is minimal.

**Comment by wpexplorer** [comment]
Would be great if the conditional was changed to include a filter.

So for example the following:

`if ( wp_is_block_theme() ) { `

Becomes:

`if ( apply_filters( 'woocommerce_notices_use_block_templates', wp_is_block_theme() ) ) {`

This will make it easy for classic themes to opt-in to using blocks for notices.

- AJ

**Comment by nielslange** [comment]
Thanks for reaching out, @wpexplorer. This is a great suggestion and I've discussed this internally. We believe this is very helpful for classic theme developers. I'll add your suggestion to #45164.

**Comment by MKV-Rob** [comment]
I am working on 2 shops now and one is running with WC 8.5.1 and Block-Notices are used there automatically even for non-block theme. In the other shop with WC 8.6.1 it uses Classic-Notices for non-block theme.

I believe there is more to look into since we are able to use WC Blocks in non-block theme but we are not able to customize specific blocks without Site Editor (FSE) - for example Mini-Cart Drawer.

**Comment by nielslange** [comment]
Thanks for reaching out, @MKV-Rob.

> I am working on 2 shops now and one is running with WC 8.5.1 and Block-Notices are used there automatically even for non-block theme. In the other shop with WC 8.6.1 it uses Classic-Notices for non-block theme.

With WC 8.5.x, we've enabled block notices for all themes (https://github.com/woocommerce/woocommerce/pull/43506/). That's why you're seeing them, even when using a non-block theme. With WC 8.6.x, we're reverted that change (https://github.com/woocommerce/woocommerce/pull/44283).

> I believe there is more to look into since we are able to use WC Blocks in non-block theme but we are not able to customize specific blocks without Site Editor (FSE) - for example Mini-Cart Drawer.

Can you clarify this part further? Do you mean there's more to look into in terms of notices? I'm asking, as I don't understand how customising the Mini-Cart drawer is related to this particular issue.

**Comment by MKV-Rob** [comment]
Thanks for getting back to me @nielslange and sorry for piggybacking this topic - I feel like these issues are related even though it might not seem like it.

> With WC 8.5.x, we've enabled block notices for all themes (https://github.com/woocommerce/woocommerce/pull/43506). That's why you're seeing them, even when using a non-block theme. With WC 8.6.x, we're reverted that change (https://github.com/woocommerce/woocommerce/pull/44283).

This is what concerns me - the shop I am preparing with WC 8.5.x is about to be launched and if I want to update WC there, I am gonna be forced to manually override some WC code so I can keep the Block-Notices functionality. If I could suggest anything it would be that instead of completely reverting changes, add an option to WC settings to have that functionality on or off.

There is section for it in the Advanced tab already - Experimental features:

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/2740c436-6c2d-4a57-8547-9ed67e68ea6a)

I know it is much more demanding this way but I believe it would be appreciated by the devs.

> Can you clarify this part further? Do you mean there's more to look into in terms of notices? I'm asking, as I don't understand how customising the Mini-Cart drawer is related to this particular issue.

No, this is not 100% related to the Block-Notices and sorry again for hijacking this topic. It is more about the issue between Block vs. Non-block themes and use of WC Blocks. The Mini-Cart drawer is an example of it - with the Non-block theme I am still able to use Mini-Cart Block in the widgets area but I am not able to fully customize it since there is no FSE enabled for non-block theme:

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/1e7cce96-0068-4130-8c0c-b2c04874227f)

Once I use Block theme _(or pretend to be using it by adding certain template parts)_ and have FSE enabled, further customizations are available:

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/e334ebf7-e587-4ab7-b715-2123f0f2985c)

_Once I turn off the certain template parts and change back to Non-block theme, the customizations of the widget are still present._ So it kind of works but it is not a smooth work.

If there would be a way to customize WC Blocks without need of FSE for non-block themes it would be helpful!

I hope it makes any sense?

**Comment by nielslange** [comment]
> Thanks for getting back to me @nielslange and sorry for piggybacking this topic - I feel like these issues are related even though it might not seem like it.
> 
> > With WC 8.5.x, we've enabled block notices for all themes (#43506). That's why you're seeing them, even when using a non-block theme. With WC 8.6.x, we're reverted that change (#44283).
> 
> This is what concerns me - the shop I am preparing with WC 8.5.x is about to be launched and if I want to update WC there, I am gonna be forced to manually override some WC code so I can keep the Block-Notices functionality. If I could suggest anything it would be that instead of completely reverting changes, add an option to WC settings to have that functionality on or off.
> 
> There is section for it in the Advanced tab already - Experimental features:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/21360633/311716632-2740c436-6c2d-4a57-8547-9ed67e68ea6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjQ5MzQsIm5iZiI6MTcxMDMyNDYzNCwicGF0aCI6Ii8yMTM2MDYzMy8zMTE3MTY2MzItMjc0MGM0MzYtNmMyZC00YTU3LTg1NDctOWVkNjdlNjhlYTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzkzN2Q4NzkwZGZhMjFkZGFhZTI1ZTg0NmI3N2MzMjczYjc1ODgwOWUxMDU4MjVmYzQxOGU2MmUzNDE0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrLr-Zd6vNoXWGsuS06dLofFOyCcEDFP_q5jCz-mO00)
> 
> I know it is much more demanding this way but I believe it would be appreciated by the devs.

Thanks for clarifying this, @MKV-Rob. In #45164, I've implemented the following filter:
```php
add_filter( 'woocommerce_use_block_notices_in_classic_theme', '__return_true' );
```
This filter allows using the block notices when using a classic theme. We've discussed the possibility of adding an option instead of a filter, but decided against it, as this is mainly a theme developer decision. 

> > Can you clarify this part further? Do you mean there's more to look into in terms of notices? I'm asking, as I don't understand how customising the Mini-Cart drawer is related to this particular issue.
> 
> No, this is not 100% related to the Block-Notices and sorry again for hijacking this topic. It is more about the issue between Block vs. Non-block themes and use of WC Blocks. The Mini-Cart drawer is an example of it - with the Non-block theme I am still able to use Mini-Cart Block in the widgets area but I am not able to fully customize it since there is no FSE enabled for non-block theme:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/21360633/311720935-1e7cce96-0068-4130-8c0c-b2c04874227f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjQ5MzQsIm5iZiI6MTcxMDMyNDYzNCwicGF0aCI6Ii8yMTM2MDYzMy8zMTE3MjA5MzUtMWU3Y2NlOTYtMDA2OC00MTMwLThjMGMtYjJjMDQ4NzQyMjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Yjg2N2M5NmNjMTkxMDQ4MzI5ZWU1ZTUwOWUxNzYwZDZkOWZjNGUxNjkwYThjNjUzYTg2ODg2NGNlYzk1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X87i9glooJo1HkifI61qTw4cSj8zI_NMs_f86YJDy_8)
> 
> Once I use Block theme _(or pretend to be using it by adding certain template parts)_ and have FSE enabled, further customizations are available:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/21360633/311718822-e334ebf7-e587-4ab7-b715-2123f0f2985c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjQ5MzQsIm5iZiI6MTcxMDMyNDYzNCwicGF0aCI6Ii8yMTM2MDYzMy8zMTE3MTg4MjItZTMzNGViZjctZTU4Ny00YWI3LWI3MTUtMjEyM2YwZjI5ODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMmY3ZjExYWI1OTMyOTkxMWQ1YzJjNjgzNzkxZGQyMTM3NDE0MjRjODA2NmNjZDI0ZmRhNzFjZTdjYTE1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BhjZfzGu7t9kPCRa1gnV7qJKp78MTK76c3DE1HkKUDQ)
> 
> _Once I turn off the certain template parts and change back to Non-block theme, the customizations of the widget are still present._ So it kind of works but it is not a smooth work.
> 
> If there would be a way to customize WC Blocks without need of FSE for non-block themes it would be helpful!
> 
> I hope it makes any sense?

Your second issue is a tough one, as modifying the cart drawer requires the site editor, which is not available when using a classic theme. I'm afraid there's not much we can do in this case, as classic themes and blocks themes are fundamentally different from each other. That said, it might be possible to create some presets, which could be selected when using a classic theme. Of course, this does not have the same level of flexibility as the site editor, but this might be an option. If that's something that would be helpful for you, I would appreciate it if you could create a separate issue for that. Just a heads-up for next time: let's try to stick to one topic per issue. It really helps keep the conversation clear and easy to follow. Thanks!
