### ISSUE TITLE
[Performance]: In REST API, WooCommerce should only load the controllers that are going to serve the request 

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#44539]
### Describe the solution you'd like

When loading REST API, WooCommerce generally initializes all the controllers that are provided by the REST API. However, this cause performance degradation because of the sheer number of controllers that are needed to be loaded in wc core alone. This performance further degrades when there are multiple 3PD plugins who also provide REST API routes and follow the same (anti)pattern of loading all the controllers.

Instead, WooCommerce should only load the controllers that are going to serve the request. This will provide extensive performance improvements, especially since few controllers does a `wp_count_post` to generate pagination info just on the load.

### Describe alternatives you've considered

n/a

### Additional context

Towards #43879

**Comment by bwafels** [comment]
@vedanshujain Any update in what release this improvement would come? I am on a shared host so any perfo improvement is super welcome

**Comment by kriss145** [comment]
Would be great to have it! We are using now Woccomerce as Wordpress Headless CMS and Woccomerce plugin load all files to the REST API. Is any update of that?

**Comment by vedanshujain** [comment]
hey, while I don't have an ETA at this time, it is pretty much the next thing I am hoping to pick up.

**Comment by Konamiman** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/29707
