### ISSUE TITLE
[GlobalStep] For Mobile viewport, Dropdown fails to renders properly with checkboxes for "Which platform(s) are you currently using? (optional)" field.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#44536]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For Mobile viewport, Dropdown fails to renders properly with checkboxes for "Which platform(s) are you currently using? (optional)" field.

### Expected behavior

For Mobile viewport, Dropdown should render properly with checkboxes for "Which platform(s) are you currently using? (optional)" field.

### Actual behavior

For Mobile viewport, Dropdown fails to renders properly with checkboxes for "Which platform(s) are you currently using? (optional)" field.

### Steps to reproduce

1. In a new private window, open browser console window and set viewport to mobile device (e.g Galaxy S10).
2. Open https://woocommerce.com/start
3. Observe that you’re on "Which one of these best describes you?" screen.
4. Tap on I'm already selling online.
5. Tap on "Which platform(s) are you currently using? (optional)" dropdown.
6. Observe that for mobile viewport, Dropdown fails to renders properly with checkboxes.

### Screenshot:

![#44536](https://github.com/woocommerce/woocommerce/assets/41110392/b278ae02-b272-46ae-8db2-0baa3bdc9fe7)

### WordPress Environment

PC:
Windows 10
Chrome (Version 121.0.6167.161)
Firefox (Version 122.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
This was noted in a review of a PR working on this screen and fixed in https://github.com/Automattic/woocommerce.com/pull/19424#pullrequestreview-1876788067
