### ISSUE TITLE
Payment method not get selected when we refresh page.

### ISSUE THREAD

**Issue by nidhitatosaniya** [woothemes/woocommerce#44557]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using latest version of woocommerce. and also use wc cart and checkout block pages. on checkout block page when i referesh page payment method not get selected it always selected first one.

### Expected behavior

Payment method should get selected on page refresh

### Actual behavior

Payment method not get selected on page refresh

### Steps to reproduce

add checkout and cart block page
select second payment method
refresh page

### WordPress Environment

Wordpress version - 6.4.3
woocommerce version 8.5.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks for reaching out, @nidhitatosaniya.

> I am using latest version of woocommerce. and also use wc cart and checkout block pages. on checkout block page when i referesh page payment method not get selected it always selected first one.

The selected payment method does not get saved before the order is placed. Both the shortcode-based checkout and the Checkout block are showing the same behaviour. May I ask why losing the selected payment method on refresh is an issue for you? I'm trying to understand why a seller would want to refresh the checkout page during the checkout process.

**Comment by nidhitatosaniya** [comment]
In normal checkout page select second payment method and refresh page then selected payment method is second but in checkout block page not same as normal.
I need to add custom fees based on payment method but when I refresh checkout block page automatically first payment method selected.

**Comment by nielslange** [comment]
> In normal checkout page select second payment method and refresh page then selected payment method is second but in checkout block page not same as normal. I need to add custom fees based on payment method but when I refresh checkout block page automatically first payment method selected.

I'm unable to reproduce this on my end. When selecting the second payment method and refreshing the page, the first payment method is selected again. This happens both when using the classic checkout and the checkout block. 

You mentioned that you need to add custom fees. Can you explain how adding custom fees is related to having the payment method selected when refreshing the page? I do not understand how these two things are related. I also wonder why a seller would want to refresh the page when viewing the checkout.
