### ISSUE TITLE
[New Product Editor]: The 'Add' button gets disabled after the product is switched to draft

### ISSUE THREAD

**Issue by jimjasson** [woothemes/woocommerce#44572]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the new Product Editor on a published product, and click on "Switch to draft", then the "Add" button (which can be used to publish the product) gets disabled. If you switch to another product tab, then the "Add" button becomes active again. 

![Markup on 2024-02-09 at 09_21_04 (1)](https://github.com/woocommerce/woocommerce/assets/25955483/a6325f12-22eb-4f26-a467-75aa8d121534)

### Expected behavior

The "Add" button should always be active if the product's configuration is valid. 

### Actual behavior

The "Add" button gets disabled after clicking "Switch to draft".

### Steps to reproduce

1. Use the new Product Editor (enable it under WooCommerce > Settings > Advanced > Features). 
2. Edit a published product. 
3. Click "Switch to draft".
4. Notice that the "Add" button is disabled.

### WordPress Environment

Latest WP, Woo + Storefront active.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by retrofox** [comment]
I'd say it gets disable also after saving the (draft) product.
