### ISSUE TITLE
Deprecated: strpos(): Passing null to parameter

### ISSUE THREAD

**Issue by Kerfred** [woothemes/woocommerce#44598]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With PHP 8.2, on all the subpages of Tools > Import (for instance /wp-admin/admin.php?import=fgj2wp), I get this message:

`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146`

After investigation, I have found that in the file wp-content\plugins\woocommerce\src\Internal\Admin\Orders\PageController.php on line 134, we see:

`global $plugin_page`

The problem is that the variable `$plugin_page` isn’t defined on the Tools > Import pages.

### Expected behavior

No "deprecated" message should be displayed.

### Actual behavior

The message
`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146`
is displayed at the top of the page /wp-admin/admin.php?import=fgj2wp.

### Steps to reproduce

It happens only with PHP 8.2 when HPOS is enabled.

Steps to reproduce the issue:

1. Set define(‘WP_DEBUG’, true); in wp-config.php
2. Install and activate WooCommerce
3. Install and activate FG Joomla to WordPress https://wordpress.org/plugins/fg-joomla-to-wordpress/
4. Enable HPOS in the WooCommerce Advanced settings
5. Go to Tools > Import > Joomla (FG)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/test/wordpresstest
Site address (URL): http://localhost/test/wordpresstest
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 2 Go
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2u PHP/8.2.0 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 8.2.0
PHP Post Max Size: 8 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 8 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Taille totale de la base de données: 4.25MB
Taille de la base de données: 2.56MB
Taille de l’index: 1.69MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 1.47MB + Index : 0.05MB + Moteur InnoDB
wp_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.06MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (2) ###

FG Joomla to WordPress: par Frédéric GILLES – 4.20.0
WooCommerce: par Automattic – 8.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #7 - /boutique/
Panier: #8 - /panier/
Commander: #9 - /commander/
Mon compte: #10 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://fr.wordpress.org
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-06 12:18:55 +01:00
Options: ✔
Notes: 63
Onboarding: skipped

### Action Scheduler ###

Terminé: 2
Oldest: 2024-02-05 13:19:58 +0100
Newest: 2024-02-05 13:19:58 +0100

En attente: 1
Oldest: 2024-02-06 13:19:58 +0100
Newest: 2024-02-06 13:19:58 +0100

### Status report information ###

Generated at: 2024-02-05 13:21:15 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Kerfred** [comment]
Here is a patch to fix this issue:

In the file wp-content\plugins\woocommerce\src\Internal\Admin\Orders\PageController.php line 146, replace:

`if ( 'admin.php' !== $pagenow || 0 !== strpos( $plugin_page, 'wc-orders' ) ) {`

by:

`if ( !isset($plugin_page) || 'admin.php' !== $pagenow || 0 !== strpos( $plugin_page, 'wc-orders' ) ) {`

**Comment by Kerfred** [comment]
When will the patch be available in WooCommerce?

**Comment by Kerfred** [comment]
When will the patch be available?
Do you need other things from me?

**Comment by olsonpm** [comment]
I reached this same error when attempting to connect my store.  Had to turn off hpos to get it working.  Please merge this in so others don't waste time stumbling across this bug

**Comment by nerrad** [comment]
I met @Kerfred at WCEU :) - it looks like an easy fix. I'll look at getting PR up for this (just leaving this comment so I remember it).

**Comment by olsonpm** [comment]
@nerrad thanks for offering - if a PR was all that was needed, [here it is for review](https://github.com/woocommerce/woocommerce/pull/48476)

**Comment by Kerfred** [comment]
Thanks. I'm looking forward to seeing it in the next WooCommerce release.
Thanks @nerrad for having boosted it up. And see you at the next WordCamp EU.

**Comment by Kerfred** [comment]
WooCommerce has released a few versions since the PR has been done.
But the bug still exists in the latest version.

Does anyone know when the fix will be included in the stable version of WooCommerce?

**Comment by olsonpm** [comment]
Looks like the patches released since v9 are cherry-picked commits.  I assume it'l go out once v9 settles
