### ISSUE TITLE
 WooCommerce Subscriptions - unable to edit user accounts on the /wp-admin/user.php

### ISSUE THREAD

**Issue by justcalljarold** [woothemes/woocommerce#44649]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

when I try to update the customer or any user accounts on the admin pages I keep getting an error message stating that it has something to do with my woocommerce, woocommerce subscription 

### Expected behavior

Fatal error: Uncaught Error: Call to undefined function wc_notice_count() in /[url]/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-addresses.php:147 Stack trace: 
#0 /[url]/public_html/wp-includes/class-wp-hook.php(324): WC_Subscriptions_Addresses::maybe_update_subscription_addresses(148, 'billing') 
#1 /[url]/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) 
#2 /[url]/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#3 /[url]/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-profile.php(243): do_action('woocommerce_cus...', 148, 'billing') 
#4 /[url]/public_html/wp-includes/class-wp-hook.php(324): WC_Admin_Profile->save_customer_meta_fields(148) 
#5 /[url]/public_html/wp-includes/class-wp-hook.php(348): WP_Hoo in /[url]/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-addresses.php on line 147

### Actual behavior

![error](https://github.com/woocommerce/woocommerce/assets/148115004/025edeb7-37a2-44ff-9c6d-0832a7e8ade3)

### Steps to reproduce

1. Go to Users
2. Select a user
3. Click on edit 
4. Update user details
5. Save Changes

### WordPress Environment

WordPress version 6.4.3
WooCommerce Version (8.5.2)
WooCommerce Subscriptions (version 4.1.0)
PHP version 7.4.33

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by dcx15** [comment]
Does the error remain after updating WooCommerce Subscriptions to the latest version 6.0.0?

**Comment by justcalljarold** [comment]
is there a newer version of the plugin?

**Comment by dcx15** [comment]
Looking at the WordPress Environment the site currently uses WooCommerce Subscriptions version 4.1.0. I think that is quite old so probably causing the issue.

**Comment by lanej0** [comment]
I'm going to close this out for now pending hearing back if a plugin update fixes the issue.
