### ISSUE TITLE
Variations empty state changes: introduce a new ExPlat experiment in 8.7

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#44643]
**Description:** As we prepare to release a batch of improvements targeting the empty state of the Variations tab, we'll keep the incremental approach and include a new experiment in 8.7.

**Acceptance criteria:**

- [x] Replicate the experiment running in 8.6. In sum, we should expose users who choose one of the following options in the "Add products" task: Physical product, Variable product, Digital product, Grouped product, and External product. 
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.
- [x] Consider that the experiment will be released in the Atomic weekly release a few days before.

**Comment by louwie17** [comment]
Closing this, all that is needed is enabling the experiment on March 12th
