### ISSUE TITLE
Post image gallery elementor duplicating same images on "load more"

### ISSUE THREAD

**Issue by irrrrrrrene** [woothemes/woocommerce#44648]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Within a post with image grid / and layout "fit rows equal heights", I inserted 30 images, but when pressing "loading more" it shows over and over again the same first pictures. 

### Expected behavior

When pressing load more it should show the following images

### Actual behavior

Within a post with image grid / and layout "fit rows equal heights", I inserted 30 images, but when pressing "loading more" it shows over and over again the same first pictures. 

### Steps to reproduce

<img width="299" alt="Screenshot 2024-02-15 alle 17 17 26" src="https://github.com/woocommerce/woocommerce/assets/160155451/d690a058-55c5-4263-b053-40ee9cd874f3">
<img width="296" alt="Screenshot 2024-02-15 alle 17 17 44" src="https://github.com/woocommerce/woocommerce/assets/160155451/bfdb78d3-69a4-4f08-b904-dc1754e9754f">
<img width="291" alt="Screenshot 2024-02-15 alle 17 18 03" src="https://github.com/woocommerce/woocommerce/assets/160155451/fed52527-c9ea-434c-b427-eb5e35cc55ab">

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.irenebeltrame.com
Site address (URL): https://www.irenebeltrame.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.3.0
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-38.14-log - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wpoh_
Total Database Size: 29.38MB
Database Data Size: 27.67MB
Database Index Size: 1.71MB
wpoh_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpoh_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpoh_cmplz_cookiebanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_cmplz_cookies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_cmplz_services: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_options: Data: 3.44MB + Index: 0.07MB + Engine MyISAM
wpoh_postmeta: Data: 10.28MB + Index: 0.47MB + Engine MyISAM
wpoh_posts: Data: 6.09MB + Index: 0.23MB + Engine MyISAM
wpoh_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpoh_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpoh_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_orders_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfblockediplog: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpoh_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfconfig: Data: 1.24MB + Index: 0.02MB + Engine MyISAM
wpoh_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wffilemods: Data: 2.24MB + Index: 0.30MB + Engine MyISAM
wpoh_wfhits: Data: 1.87MB + Index: 0.13MB + Engine MyISAM
wpoh_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfissues: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpoh_wfknownfilelist: Data: 1.55MB + Index: 0.09MB + Engine MyISAM
wpoh_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wflocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wflogins: Data: 0.54MB + Index: 0.12MB + Engine MyISAM
wpoh_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoh_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wpoh_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoh_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfpendingissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpoh_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpoh_wfstatus: Data: 0.27MB + Index: 0.10MB + Engine MyISAM
wpoh_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 928
custom_css: 2
elementor_library: 1
elementor-hf: 2
fwp_portfolio: 91
nav_menu_item: 5
page: 14
post: 44
revision: 1101

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Royal Elementor Addons: by WP Royal – 1.3.84
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.6
Complianz - Terms and Conditions: by Really Simple Plugins – 1.2.7
Elementor: by Elementor.com – 3.18.3
Essential Addons for Elementor: by WPDeveloper – 5.9.3
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.23

WooCommerce: by Automattic – 8.4.0 (update to version 8.5.2 is available)

### Inactive Plugins (1) ###

WooCommerce Blocks: by Automattic – 11.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1410 - /negozio/
Cart: #1411 - /carrello/
Checkout: #1412 - /pagamento/
My account: #1413 - /mio-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 2.9.0 (update to version 3.0.1 is available)
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /web/htdocs/www.irenebeltrame.com/home/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/cart/cart.php
/web/htdocs/www.irenebeltrame.com/home/wp-content/plugins/royal-elementor-addons/includes/woocommerce/templates/cart/mini-cart.php
/web/htdocs/www.irenebeltrame.com/home/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/web/htdocs/www.irenebeltrame.com/home/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/web/htdocs/www.irenebeltrame.com/home/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-15 16:24:13 +00:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Complete: 31
Oldest: 2024-01-15 23:10:36 +0000
Newest: 2024-02-15 09:51:22 +0000

Failed: 1
Oldest: 2023-12-21 16:27:10 +0000
Newest: 2023-12-21 16:27:10 +0000

Pending: 1
Oldest: 2024-02-16 09:51:22 +0000
Newest: 2024-02-16 09:51:22 +0000

### Status report information ###

Generated at: 2024-02-15 16:20:17 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Hello @irrrrrrrene 👋

Thanks for reaching out. In the title, you mentioned "post image gallery elementor". This sounds like your issue sounds more related to Elementor and less related to WooCommerce. 

Have you tried deactivating Elementor to see if the expected images are loaded then? If that's the case, I suggest reaching out to the Elementor support via https://elementor.com/help/.

**Comment by irrrrrrrene** [comment]
Oh gosh... I'm sorry it's the first time I reported an issue and I guess I
addressed the wrong party.
Thanks for reaching out anyway!
Have a nice day!

**Comment by nielslange** [comment]
No problem, @irrrrrrrene. I'll close this issue now and hope that you're able to sort out the issue you're currently facing. Have a pleasant day as well. 👋
