### ISSUE TITLE
Google Autofill Causes State and Country Combo Boxes to Overlap on WooCommerce Checkout Page

### ISSUE THREAD

**Issue by jnelson614** [woothemes/woocommerce#44653]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the Google Autofill feature to populate information on the checkout page that utilizes WooCommerce Checkout Blocks, the state and country combo boxes remain visible and overlap each other. This issue persists even after the autofill has completed, leading to a confusing and potentially error-prone user experience. The overlap makes it difficult for users to manually correct, verify,  or change the autofilled information.

### Expected behavior

Combo box should be correctly selected, but the drop down menu should not be present.

### Actual behavior

Combo boxes after autofill show the drop down menu and overlap eachother.

### Steps to reproduce

1. Go to my new test store: http://44.204.132.116/
2. Put the t-shirt in the cart and go to the checkout page.
3. Use Google Chrome Autofill to enter your details.

![image](https://github.com/woocommerce/woocommerce/assets/15662702/47664330-d732-40c5-a1f0-ae1670927704)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://44.204.132.116
Site address (URL): http://44.204.132.116
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.15
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 11.2.2-MariaDB
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 5.26MB
Database Data Size: 3.56MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack: by Automattic – 12.9.3
WooCommerce: by Automattic – 8.5.2

### Inactive Plugins (9) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
All-in-One WP Migration: by ServMask – 7.79
All in One SEO: by All in One SEO Team – 4.5.5
AMP: by AMP Project Contributors – 2.5.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.23.1
Hello Dolly: by Matt Mullenweg – 1.7.2
TaxoPress: by TaxoPress – 3.11.1
W3 Total Cache: by BoldGrid – 2.6.1
WP Mail SMTP: by WP Mail SMTP – 3.11.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-16 17:01:26 +00:00
Options: ✔
Notes: 65
Onboarding: completed

### Action Scheduler ###

Complete: 7
Oldest: 2024-02-15 17:02:33 +0000
Newest: 2024-02-15 17:13:37 +0000

Failed: 1
Oldest: 2024-02-15 17:03:57 +0000
Newest: 2024-02-15 17:03:57 +0000

Pending: 1
Oldest: 2024-02-16 17:02:33 +0000
Newest: 2024-02-16 17:02:33 +0000

### Status report information ###

Generated at: 2024-02-15 17:13:58 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @jnelson614, thank you for reporting this.

There's current planning that involves changes to the affected components that can ultimately solve this. We will update this issue once we have more information.

**Comment by jnelson614** [comment]
It looks like this (which i reported recently and got fixed) https://github.com/woocommerce/woocommerce-blocks/issues/11322 is broken again due to this issue.

Any idea on when this may get fixed? We have been wanting to deploy checkout blocks to our live store but we keep hitting a few roadblocks, this being one of them, that has prevented us from going live.

**Comment by ralucaStan** [comment]
@jnelson614 Thank you for bringing this to our attention. We'll work on this issue soon.
I am curious to hear what other roadblocks you hit, maybe there are ways we can assist you.

**Comment by jnelson614** [comment]
@ralucaStan We had 1 issue where our warehouse connection wasnt picking up some orders that were made with Woo Checkout Blocks. We had another issue where our software that syncs our inventory to quickbooks also wasnt throwing errors trying to sync orders.

**Comment by ralucaStan** [comment]
If these issues are still there please open separate tickets for them with details that help us replicate them on our end.

**Comment by jnelson614** [comment]
@ralucaStan I think the issues were more on our custom solutions, rather then a Woo issue, but thank you!

**Comment by jnelson614** [comment]
I do have one question, is the order stored differently in the DB from Woo Checkout Blocks vs. Classic Checkout?

**Comment by ralucaStan** [comment]
While the order processing happens differently in the Checkout Blocks, the order is stored in a compatible way. Is there anything in particular that interests you?

**Comment by senadir** [comment]
I'm revisiting this issue and I can't seem to reproduce it. I'm testing with 1Password autofill. I'm wondering if it's solved for you? I don't think we changed anything from our side yet.

**Comment by ralucaStan** [comment]
@senadir I was able to replicate it with the Chrome autocomplete. You need to add an address to your browser and when filling in the form it will appear.

**Comment by jnelson614** [comment]
> While the order processing happens differently in the Checkout Blocks, the order is stored in a compatible way. Is there anything in particular that interests you?

I was just making sure that some downstream tools wont be affected. Thanks!

**Comment by opr** [comment]
I can reproduce this, but it seems like a bug with the combobox from `wordpress-components`.

I'm wondering if we should put it in the backlog and re-review as part of https://github.com/woocommerce/woocommerce/issues/45571 when the combobox has been replaced.

**Comment by tyxla** [comment]
> I can reproduce this, but it seems like a bug with the combobox from wordpress-components.

@mirka @DaniGuardiola @fullofcaffeine could you take a look if this is something we need to address in the component itself?

**Comment by pierorocca** [comment]
@pmcpinto this serious bug has been open since February and remains un-prioritized. 

https://github.com/woocommerce/woocommerce/assets/109928953/7c332db7-4810-4ccb-a95f-4f5f31d46ae8

 On WooPay ~70% of addresses are browser auto-filled. Its high usage makes it critical it is optimized. Note on WooPay we've built AriaKit component for the country field if that's of any help.

**Comment by opr** [comment]
@pierorocca we are working on this in https://github.com/woocommerce/woocommerce/pull/48180

**Comment by pierorocca** [comment]
Awesome thanks @opr. Happy to test against Chrome, Edge, Safari, and 1Password once ready. Safari especially is temperamental and doesn't fully follow autocomplete standards.
