### ISSUE TITLE
Investigate CI passing with changes that cause api tests to fail

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#44654]
**Issue Description:**

#41769 added states to Morocco without updating the api tests and passed CI. PRs based on trunk after it was merged failed the api tests due to the tests configuration not having those states. #44650 updates the api tests configuration for this.

We should investigate how CI passed on the first PR.

**Comment by adimoldovan** [comment]
CI passed on #41769  because the PR only changed a file in `plugins/woocommerce/i18n`, a path included in the ignore list for e2e tests workflow (which also runs the API tests) - introduced by #44316 . It was reverted in the meantime with #44645

**Comment by adimoldovan** [comment]
This was [answered](https://github.com/woocommerce/woocommerce/issues/44654#issuecomment-1947332961), it was a wrong configuration issue, solved.
