### ISSUE TITLE
8.6.0. causes fatal error with Woo Subscriptions's subscription details area

### ISSUE THREAD

**Issue by namiokuzono** [woothemes/woocommerce#44677]
**For visibility:** For this issue, you can disable Order Attributes setting and the fatal error should go away. “WooCommerce > Settings > Advanced > Features > Order Attributes”

![7XbQvVC3mMJJhi4Ye67KxxGReJmdZK5Pyn6PH6kU.jpg](https://github.com/woocommerce/woocommerce/assets/85893744/5a49c024-6db3-48bb-a79e-cb4906037ab3)

More here: https://woo.com/document/order-attribution-tracking/#section-2

### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you update to the WC version 8.6.0 and you have Woo Subscriptions extension, then you see the fatal error when trying to check subscription order: 

![OYAB7V9L3ySupOWv77qia0soX12pbfT7aDeSTjpq.jpg](https://github.com/woocommerce/woocommerce/assets/85893744/ef6dbee6-1c8a-432e-8049-ecba0ee4a53f)

Fatal error recorded:

> 2024-02-16T01:04:13+00:00 Critical Uncaught Error: Call to undefined method WC_Subscription::get_report_customer_id() in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php:28 CONTEXT: {"error":{"type":1,"file":"\/srv\/htdocs\/wp-content\/plugins\/woocommerce\/src\/Internal\/Admin\/Orders\/MetaBoxes\/CustomerHistory.php","line":28},"backtrace":["","#0 \/srv\/htdocs\/wp-content\/plugins\/woocommerce\/src\/Internal\/Admin\/Orders\/Edit.php(271): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\MetaBoxes\\CustomerHistory->output(Object(WC_Subscription))","#1 \/wordpress\/core\/6.4.3\/wp-admin\/includes\/template.php(1456): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\Edit::Automattic\\WooCommerce\\Internal\\Admin\\Orders\\{closure}(Object(WP_Post), Array)","#2 \/wordpress\/core\/6.4.3\/wp-admin\/edit-form-advanced.php(707): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))","#3 \/wordpress\/core\/6.4.3\/wp-admin\/post.php(206): require('\/wordpress\/core...')","#4 {main}","thrown"]}

### Expected behavior

You should be able to view the subscription order in admin page.

### Actual behavior

You are not able to view the subscription order details. 

### Steps to reproduce

- Have WC 8.6.0
- Have Woo Subscriptions active

Does not matter if you have HPOS enabled or not enabled. 
Does not matter which version of Woo Subscriptions.

**Comment by namiokuzono** [comment]
7747314-zd-a8c 
7746854-zd-a8c
7746951-zd-a8c 
7740543-zd-a8c 
7747111-zd-a8c

**Comment by EjayhanFernandes** [comment]
7747338-zd-a8c - Rolling back to 8.5.2 resolved this issue.

`Update:` A temporary workaround is turning off `Order Attribution` which fixes the issue on `WooCommerce 8.6.0`.
- **Navigate to WooCommerce > Settings > Advanced > Features > disable Order Attribution**
![BDp6kT.png](https://github.com/woocommerce/woocommerce/assets/81605775/0c18bd73-9709-4d14-b269-5b7a3ce5bf32)

**Comment by raifd** [comment]
7747862-zen

**Comment by raifd** [comment]
7747906-zen

**Comment by kgeorgee** [comment]
7748888-zen
7748499-zen
7748859-zen

**Comment by rossviviano** [comment]
7749674 - zen

**Comment by senadir** [comment]
Also reported here https://github.com/woocommerce/woocommerce/issues/44693

**Comment by kdingsa8c** [comment]
7748918-zd-a8c
7749800-zd-a8c

**Comment by kgeorgee** [comment]
7749796-zen

**Comment by kgeorgee** [comment]
Another one here: 7749722-zen

**Comment by marzianixie** [comment]
Another one here: 7750262-zd-a8c

**Comment by marzianixie** [comment]
Another chatter with the same issue: 7750450-zen

**Comment by marzianixie** [comment]
Similar issue. Turning off Order Attributions worked for them: 7750553-zen

**Comment by battouly** [comment]
Another one here: 7750675-Zen

**Comment by jaxr** [comment]
7750659-zen

**Comment by battouly** [comment]
In chat 7750837-Zen

**Comment by chrism245** [comment]
7750945-zen

**Comment by battouly** [comment]
In chat 7750967 - zen

**Comment by NathalyaVides** [comment]
7751144-zen

**Comment by kdingsa8c** [comment]
7750361-zd-a8c

**Comment by NathalyaVides** [comment]
7751369-zen

**Comment by marzianixie** [comment]
7751207-zen
7751218-zen
7751420-zen
7751503-zen

**Comment by NathalyaVides** [comment]
7751985-zen

**Comment by NathalyaVides** [comment]
7752003-zen

**Comment by Snaacks** [comment]
7752246-zen

**Comment by Snaacks** [comment]
752269-zen

**Comment by namiokuzono** [comment]
7752586-zd-a8c

**Comment by namiokuzono** [comment]
7752613-zd-a8c

**Comment by namiokuzono** [comment]
7752827-zd-a8c

**Comment by AbhinavSakalle** [comment]
Reported in chat: 7752791-zen

**Comment by sverleis** [comment]
7749336-zen
7752731-zen 
7751944-zen
7752829-zen
7752303-zen
7749912-zen
7752650-zen
7752817-zen
7752854-zen

**Comment by AbhinavSakalle** [comment]
7705472-zen

**Comment by solstudioim** [comment]
[7754903-zen](https://a8c.zendesk.com/agent/tickets/7754903)

**Comment by solstudioim** [comment]
https://a8c.zendesk.com/agent/tickets/7756156

**Comment by dsmithweb-a8c** [comment]
7757051-zen
7756981-zen

**Comment by Brianmitchtay** [comment]
7758166-zen
7758119-zen

One merchant specifically asked:

> By the way, If there's such known bug, Why don't you send an email to all Woo Subscriptions customers to notify them?

We've been discussing that on P2 here p6q7sZ-fUF-p2#comment-34609 and it seems this would be a good case for such proactive comms.

**Comment by imodouglas** [comment]
7760266-zen

**Comment by AbhinavSakalle** [comment]
7747512-zen

**Comment by wyter** [comment]
7760383-zen

**Comment by wyter** [comment]
7760428-zen

**Comment by imodouglas** [comment]
7760776-zen

**Comment by wyter** [comment]
7759796-zen

**Comment by imodouglas** [comment]
7760831-zen

**Comment by vedanshujain** [comment]
Note that the fix for this will be included in the upcoming fix release : https://developer.woo.com/2024/02/16/woocommerce-8-6-upcoming-fixes-checkout-page-product-page-and-compatibility-with-woo-subscriptions/

**Comment by NathalyaVides** [comment]
7762309-zen
7762640-zen

**Comment by devvnawaz** [comment]
7762587-zen
7756650-zen
7762409-zen

**Comment by Brianmitchtay** [comment]
7763310-zd-a8c
7763395-zd-a8c

**Comment by ldr2273** [comment]
7763721-zen
7763638-zen

**Comment by Brianmitchtay** [comment]
7764696-zd-a8c
7764796-zd-a8c

**Comment by namiokuzono** [comment]
7761385-zd-a8c
7764944-zd-a8c
7764978-zd-a8c
7764774-zd-a8c
7759133-zd-a8c
7761040-zd-a8c
7754291-zd-a8c
7752523-zd-a8c
7763835-zd-a8c
7758059-zd-a8c
7759080-zd-a8c
7761885-zd-a8c
7761255-zd-a8c
https://wordpress.org/support/topic/subscription-page-with-critical-error/
7763691-zd-a8c
7753713-zd-a8c
7764679-zd-a8c
7760817-zd-a8c
7757886-zd-a8c atomic
7751033-zd-a8c atomic
7753226-zd-a8c
7764652-zd-a8c
7761049-zd-a8c

**Comment by solstudioim** [comment]
7765458-zen
7765726-zen

**Comment by AbhinavSakalle** [comment]
7765639-zen

**Comment by wyter** [comment]
7765909-zen

**Comment by Prin-S** [comment]
7747988-zd-a8c

**Comment by sukafia** [comment]
7766284-zen

**Comment by stoltzrx** [comment]
7766304-zen

**Comment by daniyalahmadk** [comment]
7766526-zen

**Comment by sverleis** [comment]
7766616-zen
7766813-zen

**Comment by grig-23** [comment]
In 7767526-zen the merchant was unable to disable the order attribution - they were seeing fatal errors. Nothing in the logs besides the same exact error message. Suggested they roll back to 8.5.2

**Comment by namiokuzono** [comment]
Letting users know that we've released 8.6.1 which includes the fix for this issue. 
7760477-zd-a8c
7768300-zd-a8c

**Comment by Snaacks** [comment]
Zen-7770046
