### ISSUE TITLE
Filter by Attribute > Update the order of the filter conditions

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#44678]
Porting over Jarek's request from https://github.com/woocommerce/woocommerce-blocks/discussions/9023#discussioncomment-8450521, we need to make sure the "Any" Filter condition is displayed on the left and the "All" filter condition needs to be displayed on the right side in the display settings:

<img width="285" alt="Screenshot 2024-02-15 at 22 47 33" src="https://github.com/woocommerce/woocommerce/assets/15730971/51a869b0-cea5-4d83-bf4c-e2b9f64b427b">

**Comment by SpaceSurfer1** [comment]
@nefeline , PR https://github.com/woocommerce/woocommerce/pull/44799 created for the requested change. Now, the order of filter by attribute filter options "ALL" and "ANY" are reversed. Kindly review and merge it. Thanks.

![Screenshot 2024-02-20 at 5 38 35 PM](https://github.com/woocommerce/woocommerce/assets/99202999/42928633-ab51-452a-a30d-775e69ef2bff)

**Comment by nefeline** [comment]
Hey @SpaceSurfer1 ! Thanks for your work here, I'm reviewing your PR shortly.
