### ISSUE TITLE
Filter Block: Set the default filter condition as the first (left) option

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#44683]
As @jarekmorawski mentioned in https://github.com/woocommerce/woocommerce-blocks/discussions/9023#discussioncomment-8450521

> Can we reverse the button order, then? "All" is on the left, which may suggest to people that it's the recommended setting.

**Comment by SpaceSurfer1** [comment]
Hi @dinhtungdu , this issue is duplicate of https://github.com/woocommerce/woocommerce/issues/44678 , I have created PR https://github.com/woocommerce/woocommerce/pull/44799 for the requested update. Thanks.

**Comment by dinhtungdu** [comment]
Oh, I see. It's funny that both are open on the same day. I'm closing this issue in favor of https://github.com/woocommerce/woocommerce/issues/44678
