### ISSUE TITLE
Audit use of WooCommerce Blocks version in the codebase

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#44688]
Before merging to the monorepo, WooCommerce block had a version (that stopped at 11.8.0) that was used in various parts of the codebase, including for example this cache mechanism [that caused this PR.](https://github.com/woocommerce/woocommerce/pull/44676)

The `API` class was one place where it was used and we replaced it with the WooCommerce core version. A quick scan of the code shows that other uses also include loading assets (which is fine to fix), but things like feature gating and database migration are also risky to fix.

The package can also be used externally, [for example this usage.](https://github.com/Automattic/jetpack/blob/993c35582cd01d22614be64105da4b0a4ea61d2b/projects/plugins/jetpack/modules/woocommerce-analytics/class-jetpack-woocommerce-analytics.php#L96-L98)

So updating the version directly in Package to reflect that would be hugely damaging.

What we can do is to issue a warning (when in dev mode) about the usage of that and suggest a path forward, including replacing it with the equivalent WooCommerce core version.

We also need to update all of our internal code to move away from it.

**Comment by nerrad** [comment]
I've given this a high priority given the potential impact lingering dependencies on this version number have across the codebase.

**Comment by Aljullu** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/44804 and https://github.com/woocommerce/woocommerce/pull/44806.
