### ISSUE TITLE
Problem after upgrade to 8.6.0

### ISSUE THREAD

**Issue by johnwwweissberg** [woothemes/woocommerce#44693]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading to v8.6.0, we see this error in order_edit pages as shown below: wp-admin/post.php?post=20556&action=edit

The issue was solved by downgrading to v8.5.2

---- PHP ERROR MESSAGE ----
Fatal error: Uncaught Error: Call to undefined method WC_Order::get_report_customer_id()
in /home/[facimprimeur2.printsafe.net/public_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php](http://facimprimeur2.printsafe.net/public_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php) on line 28

Call stack:

Automattic\W\I\A\O\M\CustomerHistory::output()
wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:271
Automattic\W\I\A\O\Edit::Automattic\W\I\A\O\{closure}()
wp-admin/includes/template.php:1456
do_meta_boxes()
wp-admin/edit-form-advanced.php:707
require()
wp-admin/post.php:206

### Expected behavior

No error message

### Actual behavior

PHP FATAL ERROR:
Fatal error: Uncaught Error: Call to undefined method WC_Order::get_report_customer_id()
in /home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php on line 28

Call stack:

Automattic\W\I\A\O\M\CustomerHistory::output()
wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:271
Automattic\W\I\A\O\Edit::Automattic\W\I\A\O\{closure}()
wp-admin/includes/template.php:1456
do_meta_boxes()
wp-admin/edit-form-advanced.php:707
require()
wp-admin/post.php:206

### Steps to reproduce

This error is not reproduced on all sites with v8.6.0

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://facimprimeur.fr
Site address (URL): https://facimprimeur.fr
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: –
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.25
PHP Post Max Size: 16 Mo
PHP Time Limit: 7200
PHP Max Input Vars: 20000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.3.28-MariaDB
Max Upload Size: 16 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Taille totale de la base de données: 871.87MB
Taille de la base de données: 701.75MB
Taille de l’index: 170.12MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.02MB + Index: 1.13MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 30.56MB + Index: 25.08MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
backup_postmeta: Data: 75.64MB + Index: 39.13MB + Engine InnoDB
backup_posts: Data: 4.52MB + Index: 1.44MB + Engine InnoDB
backup_print_products_order_items: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
backup_woocommerce_order_itemmeta: Data: 29.56MB + Index: 18.06MB + Engine InnoDB
backup_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_api_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cart_data: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_cdi: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 10.52MB + Index: 9.97MB + Engine InnoDB
wp_EWD_OTP_Customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Custom_Fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Fields_Meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Order_Statuses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_EWD_OTP_Sales_Reps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_kbp_form_entry: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_kbp_form_entrymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ksp_layers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ksp_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ksp_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_litespeed_optimizer: Data: 29.56MB + Index: 0.58MB + Engine InnoDB
wp_litespeed_url: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_login_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lpc_bordereau: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lpc_inward_label: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lpc_label: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_lpc_outward_label: Data: 368.52MB + Index: 0.28MB + Engine InnoDB
wp_options: Data: 7.25MB + Index: 0.28MB + Engine InnoDB
wp_postmeta: Data: 59.59MB + Index: 42.03MB + Engine InnoDB
wp_posts: Data: 6.47MB + Index: 2.67MB + Engine InnoDB
wp_print_products_aec_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_print_products_cart_data: Data: 1.03MB + Index: 0.10MB + Engine MyISAM
wp_print_products_matrix_prices: Data: 1.27MB + Index: 0.81MB + Engine MyISAM
wp_print_products_matrix_sku: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_print_products_matrix_types: Data: 0.12MB + Index: 0.03MB + Engine MyISAM
wp_print_products_order_items: Data: 10.16MB + Index: 0.20MB + Engine MyISAM
wp_print_products_quotes: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_print_products_quotes_items: Data: 0.10MB + Index: 0.00MB + Engine MyISAM
wp_print_products_quote_orders: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_print_products_request_payments: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_print_products_users_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_print_products_user_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pts_tables: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_saved_projects: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 1.34MB + Index: 0.13MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 23.20MB + Index: 20.23MB + Engine InnoDB
wp_users: Data: 2.22MB + Index: 0.84MB + Engine InnoDB
wp_wcj_track_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.36MB + Index: 0.39MB + Engine InnoDB
wp_wc_order_stats: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_wc_paybox_payment: Data: 3.52MB + Index: 0.08MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfconfig: Data: 0.42MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfhits: Data: 0.98MB + Index: 0.12MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Data: 0.37MB + Index: 0.08MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.09MB + Index: 0.04MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wow_side_menu_pro: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppusher_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.31MB + Index: 0.61MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

3d-flip-book: 1
acf: 2
acf-field: 6
acf-field-group: 6
attachment: 1371
br_labels: 6
custom_css: 5
ele-product-template: 2
elementor_library: 5
kadslider: 4
nav_menu_item: 268
oembed_cache: 1
page: 75
popup: 1
popup_theme: 6
portfolio: 10
post: 69
product: 330
product_variation: 1
shop_coupon: 11
shop_order: 4792
shop_order_refund: 133
staff: 4
tablepress_table: 2
testimonial: 6
uni_cpo_option: 1
wafs: 1
wp_block: 4
wp_global_styles: 1
wpcf7_contact_form: 17
wpforms: 16
wplc_quick_response: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Query Monitor: par John Blackbourn – 3.15.0
Advanced Custom Fields: par WP Engine – 6.2.6.1
FiboSearch - AJAX Search for WooCommerce: par L’équipe FiboSearch – 1.27.0
Colissimo shipping methods for WooCommerce: par Colissimo – 1.9.4
Contact Form 7: par Takayuki Miyoshi – 5.8.7
Disable Woo Analytics: par Print Science – 1.0.2
WP Armour - Honeypot Anti Spam: par Dnesscarkey – 2.1.15
Kadence Slider: par Kadence WP – 2.3.6
Kadence WooCommerce Email Designer: par Kadence WP – 1.5.12
Limit Login Attempts Reloaded: par Limit Login Attempts Reloaded – 2.26.4
LiteSpeed Cache: par Technologies LiteSpeed – 6.1
Loco Translate: par Tim Whitlock – 2.6.6
Max Mega Menu - Pro Addon: par megamenu.com – 2.3.1.1
Max Mega Menu: par megamenu.com – 3.3.1
mes shortcodes: par Fred – 1.0.4
Perfmatters: par forgemedia – 2.2.4
Print Science Designer Google API: par Print Science – 1.1.0
Print Science Designer: par Print Science – 1.3.145
Payment Plugins for PayPal WooCommerce: par Payment Plugins
support@paymentplugins.com – 1.0.43

Trustpilot-reviews: par Trustpilot – 2.5.925
User Role Editor: par Vladimir Garagulya – 4.64.1
Import Export WordPress Users and WooCommerce Customers: par WebToffee – 2.5.2
Payment Plugins for Stripe WooCommerce: par Payment Plugins
support@paymentplugins.com – 3.3.57

PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.7.7
WooCommerce: par Automattic – 8.5.2 (update to version 8.6.0 is available)
Wordfence Security: par Wordfence – 7.11.3
Yoast SEO Premium: par L’équipe Yoast – 22.0
Yoast SEO: par L’équipe Yoast – 22.0
wp2print: par Print Science – 3.7.398
WP Pusher: par WP Pusher – 3.0.13
WPS Hide Login: par WPServeur
NicolasKulka
wpformation – 1.9.13.2

### Inactive Plugins (1) ###

Fotovender Image Editor: par Print Science – 1.0.17

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: sticker (sticker)
simple (simple)
grouped (grouped)
variable (variable)
external (external)
fixed (fixed)
area (area)
book (book)
paybill (paybill)
box (box)
quote (quote)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base boutique: #1068 - /shop/
Panier: #1069 - /cart/
Commande: #1070 - /checkout/
Mon compte: #1071 - /my-account/
Conditions générales de vente et d’utilisation: #6 - /conditions-of-sale/

### Theme ###

Name: Virtue_premium Enfant
Version: 1.0
Author URL: https://facimprimeur.fr
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.10.13
Parent Theme Author URL: https://www.kadencewp.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium-1538421511-via-wpmarmite/woocommerce/archive-product.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/print-science-designer/templates/cart.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/review-order.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-single-product.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/email-addresses.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/email-order-items.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/empty.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/view-order.php
/home/facimprimeur2.printsafe.net/public_html/wp-content/plugins/wp2print/templates/order-details-item.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-17 11:19:25 +01:00
Options: ✔
Notes: 28
Onboarding: completed

### Action Scheduler ###

Terminer: 386
Oldest: 2024-01-16 15:07:52 +0100
Newest: 2024-02-16 12:20:33 +0100

Failed: 7
Oldest: 2023-03-28 00:00:09 +0200
Newest: 2024-02-16 09:56:26 +0100

Pending: 3
Oldest: 2024-02-17 09:53:09 +0100
Newest: 2024-02-20 10:30:03 +0100

### Status report information ###

Generated at: 2024-02-16 12:37:40 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by gleb-pineparks** [comment]
+1 
Same error in order edit screen.

**Comment by gustafhalldor** [comment]
+1 
Same error for me

**Comment by senadir** [comment]
Hey! this issue is [being tracked here](https://github.com/woocommerce/woocommerce/issues/44677), [fixed here](https://github.com/woocommerce/woocommerce/pull/44680), and will go out as soon as possible in 8.6.1.

[The issue provide a workaround for now.](https://github.com/woocommerce/woocommerce/issues/44677#issuecomment-1947614537)

I'm closing this because it's duplicate, and ideally, we would track this in a single place.
