### ISSUE TITLE
Allow the usage of meta_data values while evaluating expressions

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#44705]
# Description

We should allow the usage of expressions that use post meta values in attributes like `hideConditions` and `disableConditions` E.g. `editedProduct.meta_data.allow_combination === 'yes'`. These are evaluated with the [expression-evaluation library](https://www.npmjs.com/package/@woocommerce/expression-evaluation). Implementing this will allow extensions to use these attributes combined with post-meta values, which are commonly used.

**Comment by louwie17** [comment]
@nathanss has this not already been implemented in this PR: https://github.com/woocommerce/woocommerce/pull/41594 ?

**Comment by nathanss** [comment]
@louwie17 It has! Good catch. Closing the issue.
