### ISSUE TITLE
Explore using ExPlat to validate the impact of shopper changes

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#44710]
**Description:** as mentioned in this post (pdFofs-1Bi-p2) we want to explore the possibility of using our internal experimentation platform to implement a reliable testing strategy to evaluate the impact on our checkout changes and identify areas for further enhancement.

The best starting point is the Field Guide page about our internal tool:  PCYsg-tdK-p2

**Acceptance criteria:**
- [ ] Explore the best option to target specific stores and test checkout changes using ExPlat: can we use the exposure event feature to target pre-selected stores?
- [ ] Identify the right technical conditions to partner with stores to test checkout changes: data sharing, should we take advantage of Atomic's weekly releases and thus focus on Atomic stores, or is there an alternative way to test the checkout changes without waiting for the Core monthly release?

**Comment by senadir** [comment]
We explored the technical feasibility of using ExPlat on frontend and it's generally doable once this PR is merged.

https://github.com/woocommerce/woocommerce/pull/45131

> Explore the best option to target specific stores and test checkout changes using ExPlat: can we use the exposure event feature to target pre-selected stores?

Yes, filtering an experiment per store URL should be enough here. You still need to create an experiment per store.

>  Identify the right technical conditions to partner with stores to test checkout changes: data sharing, should we take advantage of Atomic's weekly releases and thus focus on Atomic stores, or is there an alternative way to test the checkout changes without waiting for the Core monthly release?

If we feel stores on Atomic weekly releases have enough volume to have conclusive results, then yeah.

I shared an internal P2 that answers those questions pcShBQ-1tb-p2, if you feel like it answered most of them, feel free to close this.

**Comment by ralucaStan** [comment]
I'm closing this ticket as I don't see any actionable item. Great work on this @senadir and @wavvves
