### ISSUE TITLE
[CYS - Core] Customize your store button doesn't work when the active theme isn't TT4

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#44725]
The `Customize your store` button doesn't work when the active theme isn't TT4:

https://github.com/woocommerce/woocommerce/assets/4463174/17776ac7-0d98-4fb0-ae89-c9122352c8c8

1. Create a new WooCommerce installation with this version.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Install this build of Gutenberg: [gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14236920/gutenberg.zip)
5. Enable the TT4 theme.
6. Switch to another block theme.
7. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`.
8. Click on the `Customize your store` button.
9. The flow to land in the assembler isn't loaded.

**Comment by albarin** [comment]
Check the discussion: p1708422021312919/1708338464.866509-slack-C053716F2H2
