### ISSUE TITLE
Origin column unavailable on the Orders Table on 8.6.0.50

### ISSUE THREAD

**Issue by csmcneill** [woothemes/woocommerce#44732]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using version 8.6.0.50 of WooCommerce while Order Attribution is enabled, the `Origin` column is not visible on the Orders Table at **WooCommerce > Orders**. It also doesn't appear under the `Screen Options`. However, the order attribution metabox is visible when looking at the order details.

### Expected behavior

The "Origin" column is visible (or can at least be enabled/disabled via the Screen Options section) on the Orders Table when order attribution is enabled.

### Actual behavior

The "Origin" column is not visible on the orders table and cannot be enabled while 8.6.0.50 is active. Reverting to 8.5.2 resolves the issue.

### Steps to reproduce

1. Install `woocommerce-accelerated-frequency` 8.6.0.50
2. Ensure order attribution is enabled.
3. Navigate to WooCommerce > Orders.
4. Notice there is no "Origin" column.
5. Check the screen options.
6. Notice that there is no "Origin" option.
7. Revert to 8.5.2.
8. Navigate to WooCommerce > Orders.
9. Check the screen options.
10. Note that there is an option to enable/disable the "Origin" column.
11. Enabling the "Origin" column allows it to appear in the Orders Table.

### WordPress Environment

[SystemStatusReport_justfortestingwcpay.com_2024-02-16T22-58-02.txt](https://github.com/woocommerce/woocommerce/files/14316693/SystemStatusReport_justfortestingwcpay.com_2024-02-16T22-58-02.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by layoutd** [comment]
Thanks @csmcneill. This is a known regression in 8.6.0.50 and was addressed in https://github.com/woocommerce/woocommerce/pull/44496
