### ISSUE TITLE
WC 8.6.0 breaks single product display for logged out users on non supported themes

### ISSUE THREAD

**Issue by webmandesign** [woothemes/woocommerce#44744]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've had this [issue reported by my theme user](https://wordpress.org/support/topic/woocommerce-product-single-blank-for-logged-out-users-as-of-woo-version-8-6-0/) originally.

The issue is that since WooCommerce 8.6.0 single product pages stopped rendering **for logged out users** when **using a theme with no WooCommerce support**.

I've traced the issue to this:
1. For themes with no WC support WC displays the single product content [using `[product_page id="##" show_title=0 status="any"]` shortcode](https://github.com/woocommerce/woocommerce/blob/8.6.0/plugins/woocommerce/includes/class-wc-template-loader.php#L634).
2. However, as there is `status="any"` parameter set for the shortcode, it does not pass through [a conditional check within shortcode render method](https://github.com/woocommerce/woocommerce/blob/8.6.0/plugins/woocommerce/includes/class-wc-shortcodes.php#L542).
3. The issue seems to be introduced by pull request #44659

### Expected behavior

Single product page should render even for logged-out users even on themes that do not declare WC support.

### Actual behavior

In WC 8.6.0 single product page content is empty when user is logged out and we use a theme with no WC support declared.

### Steps to reproduce

1. Install a theme with no WC support declaration, such as [Chaplin](https://wordpress.org/themes/chaplin/) or my [Auberge](https://wordpress.org/themes/auberge/).
2. Install WooCommerce plugin and create a product.
3. Preview the single product page when user is logged in. ⇒ Single product page displays OK.
4. Now log out and preview the single product page again. (Or simply open the single product page in incognito window of the browser.) ⇒ There is no content rendered for the single product page.

### WordPress Environment

WordPress 6.4.3
WooCommerce 8.6.0
Theme: [Auberge](https://wordpress.org/themes/auberge/)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by webmandesign** [comment]
**Important requirement for the issue:**
You need to use a theme with no support declaration for WooCommerce.

_Do not use WordPress default themes, nor Storefront theme._

**Comment by isitgeorge** [comment]
+1 caused us downtime using a custom theme

**Comment by capitalisticblonde** [comment]
I'm having this same issue. Any resolve?

**Comment by tammullen** [comment]
Hi, Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/44679. We are closing your issue in favor of the previously submitted. You can find more details there including that a fix has been implemented and [will be released soon](https://developer.woo.com/2024/02/16/woocommerce-8-6-upcoming-fixes-checkout-page-product-page-and-compatibility-with-woo-subscriptions/).
