### ISSUE TITLE
WooCommerce Status Widget Wrong data (HPOS)

### ISSUE THREAD

**Issue by majidempire** [woothemes/woocommerce#44745]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After enabling HPOS data tables and keep sync disabled, the WooCommerce Status widget in WP dashboard shows 0 new & on hold orders, but under orders menu I have some new (Processing) and on Hold orders.

### Expected behavior

The WooCommerce Status widget in WC dashboard must show correct order data including Processing and On-hold 

### Actual behavior

After enanbling and using just HPOS data table structure the above widget shows wrong numbers of orders

### Steps to reproduce

1. Enable  High-performance order storage under WC settings > Advanced > Features
2. After all orders synced keep "Enable compatibility mode" unchecked

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): ######
Site address (URL): ######
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.27
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-0ubuntu0.22.04.1-log
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (xx) ###

Action Scheduler - Disable Default Queue Runner: by Prospress Inc. – 1.0.0
Action Scheduler: by Automattic – 3.7.2
Contact Form 7: by Takayuki Miyoshi – 5.8.7
Contact Form CFDB7: by Arshid – 1.2.6.7
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
WooCommerce: by Automattic – 8.6.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Settings ###

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 1402-11-29 12:42:07
Options: ✔
Notes: 26
Onboarding: completed

### Action Scheduler ###

Complete: 2,202
Oldest: 2024-02-18 12:02:02 +0330
Newest: 2024-02-18 13:58:02 +0330

Pending: 14
Oldest: 2024-02-18 14:00:02 +0330
Newest: 2024-02-19 02:56:01 +0330

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 7
Valid order status for auto-generating coupon: processing
completed

### Status report information ###

Generated at: 2024-02-18 14:01:58 +03:30
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi, 
Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/40382. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
