### ISSUE TITLE
WooCommerce 8.6.0 breaks Woo Subscriptions

### ISSUE THREAD

**Issue by slapic** [woothemes/woocommerce#44742]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Updating WooCommerce to 8.6.0 breaks Woo Subscription (tried 6.0.0 and earlier versions).

Downgrading WooCommerce to 8.5.2 solves the issue.

```
PHP Fatal error:  Uncaught Error: Call to undefined method WC_Subscription::get_report_customer_id() in /home/.../publi
c_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php:28
Stack trace:
#0 /home/.../public_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(271): Automattic\WooCommerce\Internal\Admin\Orders\Meta
Boxes\CustomerHistory->output()
#1 /home/.../public_html/wp-admin/includes/template.php(1456): Automattic\WooCommerce\Internal\Admin\Orders\Edit::Automattic\WooCommerce\Internal\
Admin\Orders\{closure}()
#2 /home/.../public_html/wp-admin/edit-form-advanced.php(707): do_meta_boxes()
#3 /home/.../public_html/wp-admin/post.php(206): require('/home/.../p...')
#4 {main}
  thrown in /home/.../public_html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomerHistory.php on line 28
```

### Expected behavior

Editin a subscription works, no PHP fatal error.

### Actual behavior

Editin a subscription doesn't work, and the website throws a PHP fatal error.

### Steps to reproduce

1. Update WooCommerce to 8.6.0
2. Go to WooCommerce / Subscriptions
3. Edit an active subscription with payment history OR add a new subscription manually

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://....onrocket.site
Site address (URL): https://....onrocket.site
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: zh_TW
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.27
PHP Post Max Size: 300 MB
PHP Time Limit: 300
PHP Max Input Vars: 100000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0
WC Database Prefix: wp_
Total Database Size: 107.95MB
Database Data Size: 70.38MB
Database Index Size: 37.57MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwp_db_sent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwp_files_sent: Data: 5.52MB + Index: 18.20MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_asenha_failed_logins: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_fields: Data: 0.02MB + Index: 0.22MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.20MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_broadcast: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_bulk_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_contact_note: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_conversions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_engagement_tracking: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_bwfan_engagement_trackingmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_field_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_fields: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_form_feeds: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_import_export: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_link_triggers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_message: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bwfan_templates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cmap_endpoints: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_comments: Data: 0.30MB + Index: 0.36MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_csshero5: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eb_form_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eb_form_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_eb_search_keywords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ewwwio_images: Data: 1.52MB + Index: 1.70MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fk_cart_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_fluentform_draft_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_subscriptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_instawp_event_sites: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_instawp_event_sync_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_instawp_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_instawp_sync_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lifterlms_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_assignments_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lifterlms_events: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_events_open_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lifterlms_notifications: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lifterlms_product_to_voucher: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_quiz_attempts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lifterlms_sl_stories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lifterlms_sl_story_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lifterlms_user_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_voucher_code_redemptions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_vouchers_codes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lifterlms_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_maxi_blocks_custom_data_blocks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_maxi_blocks_general: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_maxi_blocks_styles_blocks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mxp_pixnet_post_log: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 10.30MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 6.52MB + Index: 4.55MB + Engine InnoDB
wp_posts: Data: 21.22MB + Index: 0.84MB + Engine InnoDB
wp_prm_custom_folder_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_prm_custom_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_qss: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sp_domain_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_comments_subscription: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_feedback_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_follow_users: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_phrases: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_users_rated: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_users_voted: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforo_accesses: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_activity: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wpforo_boards: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforo_bookmarks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforo_follows: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforo_forums: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wpforo_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_phrases: Data: 0.06MB + Index: 0.10MB + Engine MyISAM
wp_wpforo_post_revisions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_postmeta: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wpforo_posts: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
wp_wpforo_profiles: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wpforo_reactions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_subscribes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforo_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforo_topics: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_wpforo_usergroups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_visits: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wptc_activity_log: Data: 8.02MB + Index: 1.58MB + Engine InnoDB
wp_wptc_backups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wptc_current_process: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wptc_inc_exc_contents: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wptc_options: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wptc_processed_files: Data: 2.52MB + Index: 3.45MB + Engine InnoDB
wp_wptc_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wptc_processed_restored_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wptc_query_recorder: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_options: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wpvivid_scan_result: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wpvivid_unused_uploads_files: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_yarpp_related_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 3
asenha_cpt: 1
asenha_ctax: 3
attachment: 1406
bsf_custom_fonts: 1
course: 6
filter-field: 8
filter-set: 5
lesson: 283
llms_access_plan: 14
llms_form: 3
llms_membership: 1
llms_question: 1
llms_quiz: 1
membership_post: 1
nav_menu_item: 61
oembed_cache: 10
page: 24
post: 368
product: 5
product_variation: 6
revision: 159
section: 60
seedprod: 1
shop_order_placehold: 2
spectra-popup: 1
wfacp_checkout: 1
wffn_ty: 1
wfocu_funnel: 1
wfocu_offer: 1
wp_block: 14
wp_global_styles: 2
wp_navigation: 11
wp_template: 22
wp_template_part: 4
wpdiscuz_form: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Backup and Staging by WP Time Capsule: by Revmakx – 1.22.19
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.71
Admin and Site Enhancements (ASE) Pro: by wpase.com – 6.8.2
Advanced Custom Fields: by WP Engine – 6.2.6.1
Advanced Database Cleaner PRO: by Younes JFR. – 3.2.8
FunnelKit Cart for WooCommerce: by FunnelKit – 1.4.0
Custom Fonts: by Brainstorm Force – 2.1.3
Customize My Account Page For Woocommerce: by WPEverest – 0.4.8
Meta Field Block: by Phi Phan – 1.2.3
Fluent Snippets: by Fluent Snippets – 10.33
Login/Signup Popup: by XootiX – 2.5.1
Envato Market: by Envato – 2.0.11
Essential Blocks Pro: by WPDeveloper – 1.5.2
Essential Blocks: by WPDeveloper – 4.5.1
Filter Everything PRO: by Andrii Stepasiuk – 1.8.3
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.8.2
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.1.9
Fluent Forms Pro Add On Pack: by Fluent Forms – 5.1.7
Folders Pro: by Premio – 3.0.2
FunnelKit Funnel Builder Pro: by FunnelKit – 3.2.3
FunnelKit Funnel Builder: by FunnelKit – 3.2.2
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.15

LifterLMS Advanced Quizzes: by LifterLMS – 3.2.0
LifterLMS Assignments: by LifterLMS – 2.1.0
LifterLMS Helper: by LifterLMS – 3.5.0
LifterLMS WooCommerce: by Team LifterLMS – 2.5.0
LifterLMS: by LifterLMS – 7.5.2
List Categories: by Fernando Briano – 0.4
Loco Translate: by Tim Whitlock – 2.6.6
Custom Login Page Customizer: by Hardeep Asrani – 2.3.2
Manage Notification E-mails: by Virgial Berveling – 1.8.6
Object Cache Pro: by Rhubarb Group – 1.20.2
RY WooCommerce Tools: by Richer Yang – 3.2.1
Local customisation: by Krisztian Czako – 1.0.0
SeedProd Pro: by SeedProd – 6.15.23
Rank Math SEO PRO: by Rank Math – 3.0.55
Rank Math SEO: by Rank Math – 1.0.212.1
SlingBlocks – Gutenberg Blocks by FunnelKit (Formerly WooFunnels): by FunnelKit (formerly WooFunnels) – 1.3.0
Spectra Pro: by Brainstorm Force – 1.1.2
Templately: by Templately – 3.0.1
Spectra: by Brainstorm Force – 2.12.2
WooCommerce Smart Coupons: by StoreApps – 8.16.0 (update to version 8.17.0 is available)
Woo Subscriptions: by WooCommerce – 6.0.0
WooCommerce: by Automattic – 8.6.0
FunnelKit Automations Connectors: by FunnelKit – 2.7.0
FunnelKit Automations Pro: by FunnelKit – 2.8.2
FunnelKit Automations: by FunnelKit – 2.8.2
WP-WebAuthn: by Axton – 1.3.1
wpDiscuz: by gVectors Team – 7.6.15
wpForo: by gVectors Team – 2.3.1
Yet Another Related Posts Plugin (YARPP): by YARPP – 5.30.9

### Inactive Plugins (14) ###

Atarim: Visual Website Collaboration, Feedback & Workflow Management: by Atarim – 3.18
Block Visibility: by Nick Diego – 3.3.0
CSS Hero: by The CSS Hero Team – 5.0.6
EWWW Image Optimizer: by Exactly WWW – 7.2.3
Extendons: Woocommerce Customize My Account Page Plugin: by Extendons – 1.0.6
LifterLMS Social Learning: by LifterLMS – 1.6.0
Load More Anything: by AddonMaster – 3.3.4
Media Cleaner: by Jordy Meow – 6.7.2
Media File Renamer: Rename Files (Manual, Auto, AI): by Jordy Meow – 5.8.3
Pixnet 痞客邦部落格搬家匯入工具 - Mxp.TW: by Chun – 2.2.2
Publitio: by Publitio – 2.1.7
SS WooCommerce Myaccount Ajax Tabs: by SaurabhSharma – 2.7.0
WP Fusion: by Very Good Plugins – 3.42.5
WP Fusion - Logins Addon: by Very Good Plugins – 1.3.3

### Dropin Plugins (1) ###

object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (4) ###

Activity Log Plugin: by  – 1.0.0
CDN Cache Plugin: by  – 1.1.3
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.14
WP Time Capsule: by Revmakx –

### Settings ###

API Enabled: –
Force SSL: –
Currency: TWD (NT$)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Basket: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Spectra One
Version: 1.0.9
Author URL: https://brainstormforce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/.../public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php
/home/.../public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php
/home/.../public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/.../public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/.../public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://....onrocket.site
Subscriptions-core Library Version: 6.8.0
Subscription Statuses: wc-pending: 1
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Taiwan

### Payment Gateway Support ###

藍新信用卡: products
藍新 ATM 櫃員機: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-17 10:23:06 +08:00
Options: ✔
Notes: 123
Onboarding: completed

### Action Scheduler ###

Complete: 115
Oldest: 2024-01-18 02:41:24 +0800
Newest: 2024-02-17 16:04:05 +0800

Failed: 15
Oldest: 2023-04-27 22:16:58 +0800
Newest: 2024-01-26 14:12:31 +0800

Pending: 2
Oldest: 2024-02-18 15:45:42 +0800
Newest: 2024-02-19 02:35:25 +0800

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: 
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: 
Combine emails: 
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: no
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2024-02-17 16:04:48 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by e4eric22** [comment]
Same issue here as the woo subscriptions crashed when clicking on edit a single subscription. 
The downgrade to 8.5.2 worked for now.

**Comment by nicholasjeberlin** [comment]
Hi there!

This is the same issue as https://github.com/woocommerce/woocommerce/issues/44677

Until the fix is released, you can disable Order Attribution at WooCommerce > Settings > Advanced > Features to resolve this.

**Comment by julinedossantos** [comment]
Hi there!
Another customer with the same problem: 7835093-zd-a8c
