### ISSUE TITLE
After Variations are created, disable the fields that don’t do anything

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#44761]
In the classic editor, certain fields are hidden once a Variable product is selected.

Currently in our new product editor, those fields are still visible and editable, even after variations have already been created, meaning that they don’t impact anything even if the user adds a value to the field.

For example, once Variations have been created, adding a List Price on the parent product doesn’t actually do anything, because Pricing needs to be managed at the individual level.

Through user research, we know that this is very confusing — if a field is active and editable, then the user reasonably expects that they can actually edit something.

Thus, we should **disable all fields that are currently hidden in the classic editor for Variable products.**

Link to relevant P2 post for additional context: peCask-Ey-p2

Reasoning for using disabled instead of hiding:
_I chatted about this with Jarek and Pedro and basically if we hide fields, it might create some awkward situations where the entire page is empty… which then raises the question of, should we just hide the whole tab… but if we do that, then it might be confusing for tabs to disappear unexpectedly, and also extensions might want to add fields to those tabs… So the conclusion was to just disable it for now as a simple approach._

**Acceptance criteria**

- [ ] All fields that are currently hidden in the classic editor for Variable products should likewise be disabled in the new product editor. 
     - General:
       - [x] Price
       - [x] List price
       - [x] Downloads
     - Pricing:
       - [x] Price
       - [x] List price
       - [x] Schedule sale
       - [ ] Tax class (depends if "same as main product" is selected at the variation level) 
     - Inventory:
       - [x] SKU
       - [x] Track stock quantity toggle
       - [x] Stock status 
     - Shipping:
       - [x] Digital toggle
       - [x] Shipping Class
       - [x] Shipping Dimensions

**Comment by nathanss** [comment]
@j111q 

Hi Jill!

Can we get a complete list of the fields that need to be disabled? 

Is there a reason for disabling them instead of hiding them?

**Comment by pmcpinto** [comment]
> Can we get a complete list of the fields that need to be disabled?

Here's the list:

- General:
Price
List price
Downloads

- Pricing:
Price
List price
Schedule sale
Tax class (depends if "same as main product" is selected at the variation level)

- Inventory:
SKU
Track stock quantity toggle
Stock status

- Shipping:
Digital toggle
Shipping Class
Shipping Dimensions

Can someone from the team check if I'm not missing anything? Thanks.

**Comment by mdperez86** [comment]
@pmcpinto @j111q  

> Tax class (depends if "same as main product" is selected at the variation level)

I think this is an AC that will impact performance since to do that I'll need to get all variations and then check if all of them have `same as main product` class selected, which will be heavy if the amount of variations is big.
