### ISSUE TITLE
Nonce verification error when creating new account during checkout

### ISSUE THREAD

**Issue by ts-mz** [woothemes/woocommerce#44779]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am trying to add line item meta entered into custom fields in the checkout form to order items using the hook `woocommerce_checkout_create_order_line_item`. I'm using the following code to validate the checkout nonce `woocommerce-process-checkout-nonce` at the beginning of the function adding the line item meta values.

`if ( ! isset( $_POST['woocommerce-process-checkout-nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['woocommerce-process-checkout-nonce'] ) ), 'woocommerce-process_checkout' ) ) {
   return;
}`

The nonce-validation works correctly when a user clicking the submit button is either logged in or ordering as a guest. 
I will fail when the option to create a new account during logout is used.

### Expected behavior

The `woocommerce-process-checkout-nonce` validation should work irrespective of a new user creation during checkout.

### Actual behavior

The nonce-validation works correctly when a user clicking the submit button is either logged in or ordering as a guest. 
I will fail when the option to create a new account during logout is used.

### Steps to reproduce

1. Create additional form fields for cart-/order-items on the checkout page.
2. Create a function adding these to the db using the hook `woocommerce_checkout_create_order_line_item`
3. Attempt to verify the `woocommerce-process-checkout-nonce` at the beginning of said function when a new user is created during checkout.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://domain.local/shop-3
Site address (URL): http://domain.local/shop-3
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 6.4.2 - Es ist eine neuere Version von WordPress verfügbar (6.4.3)
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 16.62MB
Datenbank-Datengröße: 12.33MB
Datenbank-Indexgröße: 4.29MB
wp_2_woocommerce_sessions: Daten: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Daten: 0.39MB + Index: 0.45MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Daten: 0.42MB + Index: 0.31MB + Engine InnoDB
wp_2_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Daten: 0.31MB + Index: 0.16MB + Engine InnoDB
wp_2_admin_columns: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Daten: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_2_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 5.09MB + Index: 0.14MB + Engine InnoDB
wp_2_postmeta: Daten: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_2_posts: Daten: 1.41MB + Index: 0.06MB + Engine InnoDB
wp_2_storeabill_document_itemmeta: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_2_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_storeabill_documentmeta: Daten: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_2_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Daten: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_order_stats: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_2_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_itemmeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipmentmeta: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_xoo_wl_list: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_xoo_wl_list_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Daten: 1.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 31
custom_css: 1
document_template: 5
nav_menu_item: 22
page: 17
post: 1
product: 32
product_variation: 13
revision: 63
shop_coupon: 3
shop_order: 188
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Ihr Shop benutzt kein HTTPS. Erfahren Sie mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (20) ###

CMB2: von CMB2 team – 2.10.1
Germanized für WooCommerce Pro: von vendidero – 3.8.1
WooCommerce PayPal Payments: von WooCommerce – 2.4.1 (Update auf Version 2.5.3 ist verfügbar)
Query Monitor: von John Blackbourn – 3.15.0
Germanized für WooCommerce: von vendidero – 3.14.1
Germanized für WooCommerce Pro: von vendidero – 3.8.1
Safe SVG: von 10up – 2.2.2
WooCommerce: von Automattic – 8.3.1 (Update auf Version 8.6.0 ist verfügbar)
Loco Translate: von Tim Whitlock – 2.6.6
FakerPress: von Gustavo Bordoni – 0.6.1
Disable XML-RPC: von Philip Erb – 1.0.1
Payment Methods by Product & Country for WooCommerce: von WPFactory – 1.7.8
WooCommerce Cash On Pickup: von Marian Kadanka – 1.7.0
vendidero Helper: von vendidero – 2.2.1
CMB2: von CMB2 team – 2.10.1
WP Migrate Lite: von WP Engine – 2.6.9
Waitlist Woocommerce Premium ( Back in stock notifier ): von  – 3.1.1
Debug Bar: von wordpressdotorg – 1.1.4

### Inactive Plugins (19) ###

Admin Columns: von AdminColumns.com – 4.6.1
Advance Waitlist: von CedCommerce – 2.0.2
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: von codewoogeek – 5.0.1
Change Quantity on Checkout for WooCommerce: von Bhavik Kiri – 3.0
Checkout Field Editor for WooCommerce: von ThemeHigh – 2.0.0
CMB2 Admin Extension: von twoelevenjay – 0.2.3
Debug Log Manager: von Bowo – 2.2.0
Disable Comments: von WPDeveloper – 2.4.5
Disable Emojis (GDPR friendly): von Ryan Hellyer – 1.7.6
Discontinued Product Stock Status for WooCommerce: von SaffireTech – 1.1.4
Extra product options For WooCommerce | Custom Product Addons and Fields: von ThemeHigh – 3.2.4
Plugin Check: von Plugin Review Team – 0.2.1
Subscriptions For WooCommerce: von WP Swings – 1.5.7
WooCommerce Checkout Manager: von QuadLayers – 7.3.1
WPC Show Single Variations for WooCommerce: von WPClever – 2.3.5
WP Custom Status Manager: von Hardweb.it – 1.0.4
WP Hooks Finder: von Muhammad Rehman – 1.2.3
YITH WooCommerce Subscription: von YITH – 3.0.1
YITH WooCommerce Waitlist: von YITH – 2.9.0

### Must Use Plugins (1) ###

WP Migrate Lite Compatibility: von Delicious Brains – 1.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Ihr Konto: #7 - /mein-konto/
Allgemeine Geschäftsbedingungen: #69 - /agb/

### Theme ###

Name: _s
Version: 1.0.0
Author URL: https://automattic.com/
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: theme-folder/woocommerce/content-widget-product.php
theme-folder/woocommerce/single-product\add-to-cart\variation.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-20 14:57:58 +01:00
Options: ✔
Notes: 59
Onboarding: -

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Action Scheduler ###

Abgeschlossen: 130
Oldest: 2024-01-22 11:10:13 +0100
Newest: 2024-02-19 17:08:19 +0100

Fehlgeschlagen: 654
Oldest: 2023-09-06 18:11:00 +0200
Newest: 2023-10-19 19:33:34 +0200

Ausstehend: 4
Oldest: 2024-02-20 17:08:06 +0100
Newest: 2024-02-20 17:08:06 +0100

### Status report information ###

Generated at: 2024-02-19 17:36:51 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hello @ts-mz, thanks for reaching out.

Have you tried a similar approach for getting and verifying the nonce, as detailed in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-checkout.php#L1222

Sorry about the naive question, just making sure the condition vars are valid, while I check if a different action is used to generate a nonce when creating a user on checkout.

**Comment by senadir** [comment]
Hey @ts-mz Nonce validation will of course fail because you're using a logged-out/guest nonce and validating it against a logged in customer. Not the same session was used to create the nonce and it will fail.

By the time `woocommerce_checkout_create_order_line_item` runs, the nonce would have been validated already, so you don't need to do any more validation yourself. Validation happens in here https://github.com/woocommerce/woocommerce//blob/f730e4edb78059913fcde7d63b418dcec7659b44/plugins/woocommerce/includes/class-wc-checkout.php#L1229-L1237

**Comment by ts-mz** [comment]
Thanks @senadir for the clarification!
