### ISSUE TITLE
Remove the API/E2e test summary GitHub comment

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#44773]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
After the E2E / API tests complete, we generate a summary comment. Example: https://github.com/woocommerce/woocommerce/pull/44735#issuecomment-1949514244.

This comment reproduces information that is already available by viewing the CI results at the bottom of the page, and adds a lot of noise to the PR process... for example: emails / notifications for every PR from this comment make it more likely that you'll miss a more important notification.

/cc @rodelgc as you originally added these comments, in case there's anything you'd like to note
/cc @coreymckrill for raising this issue

**Comment by adimoldovan** [comment]
The comment was implicitly removed when e2e workflows were migrated to ci.yml with https://github.com/woocommerce/woocommerce/issues/41489 and the summary comment was left out.
