### ISSUE TITLE
Database error in upgrade function react-admin

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#44793]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

```
WordPress database error Can't DROP 'is_primary'; check that column/key exists for query ALTER TABLE foowc_admin_note_actions DROP COLUMN `is_primary`
```

Caused by https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/react-admin/wc-admin-update-functions.php#L277

Related https://github.com/woocommerce/woocommerce/issues/44792

It seems there is a general issue in wc-admin-update-functions.php when upgrading from a very old WooCommerce before the react-admin was added to a newer WooCommerce.

### Expected behavior

No error

### Actual behavior

Error

### Steps to reproduce

See above

### WordPress Environment

WooCommerce 8.6

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @kkmuffme,

Can you please include the system status report? You can copy and paste the system status report from WooCommerce > System Status in WordPress admin.

**Comment by kkmuffme** [comment]
It's irrelevant - since I would need the status report BEFORE the update, but I don't have that anymore obviously.
Since after the update it works fine.
