### ISSUE TITLE
[Enhancement]: Low-hanging, quick win fixes in Block-based checkout

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#44835]
> [!IMPORTANT]
> This issue is currently blocked as the last open sub issue #46582 is blocked.

As part of our ongoing efforts to pdFofs-1Pu-p2, we have identified the following opportunities as quick win UX improvements. cc: @pmcpinto

```[tasklist]
## General fixes 
- [ ] https://github.com/woocommerce/woocommerce/issues/46004
- [ ] https://github.com/woocommerce/woocommerce/issues/46008
- [ ] https://github.com/woocommerce/woocommerce/issues/46014
```

```[tasklist]
## Shipping section changes
- [ ] https://github.com/woocommerce/woocommerce/issues/46014
- [ ] https://github.com/woocommerce/woocommerce/issues/46013
- [ ] https://github.com/woocommerce/woocommerce/issues/46012
- [ ] https://github.com/woocommerce/woocommerce/issues/46512
- [ ] https://github.com/woocommerce/woocommerce/issues/46513
```

```[tasklist]
## Other
- [ ] https://github.com/woocommerce/woocommerce/issues/46010
```

**Comment by dominique-vias** [comment]
## March 04 update:
Updated the issue above to include additional low-hanging improvement opportunities:

- Restyling of input fields
- Add chevron icon to dropdown fields

### Shipping
- Rename the main section as Delivery
- "Country" field should be first in the address form
- Hide address line 2 behind link
- Rename and restyle tabs from “Shipping” and “Local pickup” to “Ship” & “Pickup”

### Pickup
- Rename “Local pickup options” to “Pickup points”
- Show addresses by default, not just on selection
- Truncate sub text after two lines and end with a  'Read more' link which opens a pop up modal (explore if feasible)

**Comment by pmcpinto** [comment]
@nikkivias I think we can close this epic, as there's only one item left and we have a separate GH issue.
