### ISSUE TITLE
[Enhancement]: add filter for shipping methods in cart-shipping.php

### ISSUE THREAD

**Issue by yglik** [woothemes/woocommerce#44872]
### Describe the solution you'd like

i want to be able to filter the html of the shipping methods outputed in review-order.php, in my checkout page.
it can be achieved through adding a filter to cart-shipping.php
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart-shipping.php
wrapping the printf() in add_filter should be ok
`							printf( '<input type="radio" name="shipping_method[%1$d]" data-index="%1$d" id="shipping_method_%1$d_%2$s" value="%3$s" class="shipping_method" %4$s />', $index, esc_attr( sanitize_title( $method->id ) ), esc_attr( $method->id ), checked( $method->id, $chosen_method, false ) ); // WPCS: XSS ok.
`

my use case is that i want to add a disabled attribute to some of the shipping methods

### Describe alternatives you've considered

i manipulate the shipping methods html using js dom, but its only client side

i can replace the entire template, but i want it to keep updates from wc in the future

**Comment by opr** [comment]
Thank you for taking the time to share this idea. We appreciate your suggestion.

While this is a useful suggestion, it doesn’t fit our current priorities. We're going to close the issue, and at some point, we may revisit our priorities and review the list of suggestions like this one. Don’t be alarmed if you don’t see any activity on this issue for a while.
