### ISSUE TITLE
Investigate automated posting of FSOR reports to p2

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#44885]
[wpcom has REST API](https://href.li/?https://developer.wordpress.com/docs/api/) and there are [ways to render Markdown](https://wordpress.com/support/markdown-quick-reference/), so it seems plausible we could make it work.

**Comment by nima-karimi** [comment]
- [x] As discussed on ai-services#1010, let's add a link to the generated P2 post to the Slack message (implemented in #44886).

**Comment by tommyshellberg** [comment]
Link to P2 post in Slack notifications has been completed:
https://github.com/Automattic/ai-services/pull/1030
