### ISSUE TITLE
Post to a slack channel whenever a FSOR report has been generated (or if it hit a problem)

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#44886]

**Comment by nima-karimi** [comment]
@peterfabian Do we know what channel we want these notifications in? Is it going to be a new channel dedicated to these reports, or do we already have a place in mind?

**Comment by jamesckemp** [comment]
@nima-karimi I vote for a new dedicated channel, but might be worth asking Rania for confirmation. For the Slack post, is it possible to also summarise the segments that were generated? I.e. "A new report was published. The segments include feedback on 'something', 'something else', 'etc'"

**Comment by nima-karimi** [comment]
>  For the Slack post, is it possible to also summarise the segments that were generated?

@jamesckemp I think that's a good idea. It requires some post-processing to get that summary (i.e., more requests to the LLM). We can certainly add it if that will make the Slack message more helpful.
