### ISSUE TITLE
Deprecation message when adding a coupon to the cart

### ISSUE THREAD

**Issue by superbmario** [woothemes/woocommerce#44882]
### Describe the bug

When adding a valid coupon via the cart, the message is displayed:

`Deprecated: Creation of dynamic property WC_Coupon::$sort is deprecated in /woocommerce/includes/class-wc-cart-totals.php on line 378`

https://imgur.com/a/eeVBXti

When adding non-valid coupon to the cart:

`Deprecated: Creation of dynamic property WC_Coupon::$error_message is deprecated in /woocommerce/includes/class-wc-coupon.php on line 869`

Possibly related to https://github.com/woocommerce/woocommerce/issues/38857

### Expected behavior

No depreciation

### Actual behavior

Depreciation...

### Steps to reproduce

1. Enable WP_DEBUG
2. Add a product to cart
3. Try entering a coupon code

### WordPress Environment

WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Memory Limit: 512 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment

Server Info: LiteSpeed
PHP Version: 8.2.15
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 8000
cURL Version: 7.87.0
OpenSSL/1.1.1w

**Comment by lipemat** [comment]
This issue appears to be resolved on trunk 
https://github.com/woocommerce/woocommerce/blob/d581512171ec82c670f3fae634f339f594a28896/plugins/woocommerce/includes/class-wc-coupon.php#L84-L91

**Comment by opr** [comment]
Hi - this was fixed in https://github.com/woocommerce/woocommerce/pull/40998

Thanks for reporting it, the fix should land in WooCommerce 8.7.0 🥳
