### ISSUE TITLE
[CYS] Override the header template part when saving in the assembler

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#44889]
Currently, when the user clicks on `Done` to save the result of the CYS flow, we override **only** the homepage template.
This means the homepage template will have a different header than the rest of the pages.
To solve this we need to override also the `header` template part.

![Screenshot 2024-02-22 at 13 35 45](https://github.com/woocommerce/woocommerce/assets/186112/611e7183-e6e2-4c1c-afb7-e8a56f50d912)

**Comment by gigitux** [comment]
Currently, CYS works only on the homepage template ([source code](https://github.com/woocommerce/woocommerce/blob/63f66507598fa670fb6517c6debcf22bb502321e/plugins/woocommerce-admin/client/customize-store/data/homepageTemplates.ts)).
There isn't any logic to work with template parts. We have the same issue with the footer.
