### ISSUE TITLE
The shipping cost price and label are moved down when setting up the shipping as a new customer (Firefox only)

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#44893]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When going through the home checklist and setting up the shipping option, I see that the shipping cost and label are moved down a bit so it looks like they are going out of the box.

### Expected behavior

Properly aligned to the center of the box so the bottom border is finally visible properly
![Screenshot%202024-02-22%20at%2010 41 58](https://github.com/woocommerce/woocommerce/assets/21279898/2a9d2958-9049-41ac-8bfd-32c264bb6121)

### Actual behavior

Shipping cost and label moved down a bit and they hide the bottom border

### Steps to reproduce

[on a fresh new WooCommerce site]
1. Make sure you are on the Home page
2. Click to set up Shipping option (should be 4th option or somewhere near)
3. When on the second step of the setup observe issue

### WordPress Environment

The issue is present in Firefox but not in Chrome

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
@veljkho Is this still reproducible?

I wasn't able to reproduce it on both Chrome and Safari. I used the latest WooCommerce.



![Image](https://github.com/woocommerce/woocommerce/assets/4723145/9d277775-5f64-44a8-8f9a-680bd31bda61)

**Comment by veljkho** [comment]
Hi @moon0326 
I could still reproduce it using 8.8.0.10 build on JN site: https://d.pr/i/Tcja8H I have the site details if you want to reproduce it, just ping me via DM.

**Comment by moon0326** [comment]
> Hi @moon0326 I could still reproduce it using 8.8.0.10 build on JN site: ![Tcja8H.png](https://github.com/woocommerce/woocommerce/assets/4723145/9bbe7c78-5235-49c7-bc84-0d675400d5d6) I have the site details if you want to reproduce it, just ping me via DM.


I missed your note "The issue is present in Firefox but not in Chrome". I'll re-check it in Firefox.

**Comment by moon0326** [comment]
@veljkho I was able to reproduce it with the latest Firefox. I'll work on it. Thank you for the details.
