### ISSUE TITLE
Inaktív a kosárba teszem gomb variálható termékeknél

### ISSUE THREAD

**Issue by Filceim** [woothemes/woocommerce#44903]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

December elején feltettem több olyan terméket, amit 3 féle méretben lehet megvásárolni, közülük - opciók választása - módon ki lehetett választani, amit szeretne. Teljesen jól is működött. Ennek a mintájára február elején további termékeket is feltettem: Ezek is jól működtek. 
Majd néhány napja azt vettem észre, hogy a decemberben feltett termékek elromlottak, az újak jól működnek. 
Ha rámegyek a termék oldalra elhalványodik a kosárba teszem gomb. Ki tudom választani az opciót, de nem tudom kosárba helyezni. Kiírja, hogy kosárba helyezés előtt válasszunk termékopciót.  
Pl: ezen az oldalon megnézhető a hiba: https://filceim.hu/termek/koreai-filclap-901-sotet-szurke-filctekercs/
Sajnos sok ilyen termék van, ami rossz.

### Expected behavior

Arra számítottam, hogy kivánt opciójú termék betehető legyen a kosárba:
Úgy mint ezen az oldalon:
Ez az oldal meg jól működik: https://filceim.hu/termek/koreai-filctekercs-898-kozep-szurke-filclap/

### Actual behavior

Nem helyezhető a hibás oldalon a kosárba, a kosár inaktív és nem érzékeli, hogy opció kiválasztásra került.

### Steps to reproduce

![hiba foto-filceim hu](https://github.com/woocommerce/woocommerce/assets/160939194/daaa781b-e15d-4823-bd1b-3cf6ba664415)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://filceim.hu
Site address (URL): https://filceim.hu
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: hu_HU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.79.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 10.4.31-MariaDB-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Teljes adatbázis mérete: 70.26MB
Adatbázis adatok mérete: 62.07MB
Adatbázis index mérete: 8.19MB
wp_woocommerce_sessions: Adat: 3.33MB + Index: 0.06MB + Engine MyISAM
wp_woocommerce_api_keys: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Adat: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Adat: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_tax_rates: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Adat: 6.34MB + Index: 1.64MB + Engine MyISAM
wp_actionscheduler_claims: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Adat: 3.35MB + Index: 2.58MB + Engine MyISAM
wp_cartflows_ca_cart_abandonment: Adat: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_cartflows_ca_email_history: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_cartflows_ca_email_templates: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cartflows_ca_email_templates_meta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ce4wp_abandoned_checkout: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ce4wp_contacts: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cky_banners: Adat: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_cky_cookies: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cky_cookie_categories: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Adat: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_easywpsmtp_debug_events: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_events: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_attribute_mapping_rules: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_budget_recommendations: Adat: 0.11MB + Index: 0.12MB + Engine MyISAM
wp_gla_merchant_issues: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_rates: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_shipping_times: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_bans: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_dashboard_events: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_itsec_dashboard_lockouts: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_distributed_storage: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_fingerprints: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_firewall_rules: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_geolocation_cache: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_lockouts: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_logs: Adat: 0.40MB + Index: 0.08MB + Engine MyISAM
wp_itsec_mutexes: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_opaque_tokens: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_temp: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_user_groups: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_vulnerabilities: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_jetpack_sync_queue: Adat: 0.19MB + Index: 0.01MB + Engine MyISAM
wp_links: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailerlite_checkouts: Adat: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailerlite_forms: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automations: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_runs: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_run_logs: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_run_subjects: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_triggers: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_automation_versions: Adat: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_custom_fields: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_dynamic_segment_filters: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_feature_flags: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_forms: Adat: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_log: Adat: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_migrations: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletters: Adat: 0.12MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_links: Adat: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_option: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option_fields: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_posts: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_segment: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_templates: Adat: 2.02MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_scheduled_tasks: Adat: 0.43MB + Index: 0.13MB + Engine MyISAM
wp_mailpoet_scheduled_task_subscribers: Adat: 0.10MB + Index: 0.10MB + Engine MyISAM
wp_mailpoet_segments: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_sending_queues: Adat: 0.55MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_settings: Adat: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_bounces: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_clicks: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_forms: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_newsletters: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_opens: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_statistics_unsubscribes: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_stats_notifications: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscribers: Adat: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_mailpoet_subscriber_custom_field: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_ips: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_segment: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_tag: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_tags: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_user_agents: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_user_flags: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ml_data: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Adat: 28.67MB + Index: 0.54MB + Engine MyISAM
wp_postmeta: Adat: 5.83MB + Index: 0.58MB + Engine MyISAM
wp_posts: Adat: 8.35MB + Index: 0.19MB + Engine MyISAM
wp_rank_math_404_logs: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rank_math_analytics_gsc: Adat: 0.85MB + Index: 0.59MB + Engine MyISAM
wp_rank_math_analytics_inspections: Adat: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_rank_math_analytics_objects: Adat: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_rank_math_internal_links: Adat: 0.05MB + Index: 0.01MB + Engine MyISAM
wp_rank_math_internal_meta: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rank_math_redirections: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rank_math_redirections_cache: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_swift3_warmup: Adat: 0.04MB + Index: 0.07MB + Engine MyISAM
wp_termmeta: Adat: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_terms: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Adat: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_taxonomy: Adat: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Adat: 0.22MB + Index: 0.03MB + Engine MyISAM
wp_users: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_vp_woo_pont_mpl_shipments: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Adat: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Adat: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Adat: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_orders_meta: Adat: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_order_addresses: Adat: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_coupon_lookup: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_product_lookup: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Adat: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_rate_limits: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_webhooks: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfm_backup: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_logs: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_payments: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_payment_meta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_tasks_meta: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zbscrm_api_keys: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_admlog: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_companies: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_customfields: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_dbmigration_meta: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_events: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_externalsources: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_forms: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Adat: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_meta: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_notifications: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_quotes: Adat: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_security_log: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tags: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_tax_table: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Adat: 0.02MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

astra-advanced-hook: 1
attachment: 692
custom_css: 2
customize_changeset: 120
elementor_library: 1
itsec-dash-card: 6
itsec-dashboard: 1
mailpoet_page: 1
nav_menu_item: 25
oembed_cache: 3
page: 20
post: 17
product: 99
product_variation: 150
revision: 786
rm_content_editor: 1
shop_coupon: 10
shop_order: 23
shop_order_refund: 1
spectra-popup: 3
wp_block: 1
wp_global_styles: 3
wp_navigation: 1
wp_template_part: 1
wpforms: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Astra Pro: írta Brainstorm Force – 4.6.4
Starter Templates: írta Brainstorm Force – 4.0.13
Astra Widgets: írta Brainstorm Force – 1.2.12
Solid Security Basic: írta SolidWP – 9.3.1
Checkout Plugins - Stripe for WooCommerce: írta Checkout Plugins – 1.7.0
Code Snippets: írta Code Snippets Pro – 3.6.2
CookieYes | GDPR Cookie Consent: írta CookieYes – 3.2.0
Easy WP SMTP: írta Easy WP SMTP – 2.2.0
Site Kit by Google: írta Google – 1.120.0
WooCommerce Csomagpontok és Címkék: írta Viszt Péter – 3.1.2
Jetpack: írta Automattic – 13.1.3
MailPoet: írta MailPoet – 4.44.0
MailerLite - Signup forms (official): írta MailerLite – 1.7.5
Rearrange Woocommerce Products: írta Aslam Doctor – 4.2.0
Rank Math SEO: írta Rank Math – 1.0.213
Swift Performance AI: írta SWTE – 0.5.8.19
Spectra: írta Brainstorm Force – 2.12.3
Under Construction (Fejlesztés alatt): írta WebFactory Ltd – 3.99
WooCommerce Cart Abandonment Recovery: írta CartFlows Inc – 1.2.26
MailerLite - WooCommerce integration: írta MailerLite – 2.1.2
WooCommerce PayPal Payments: írta WooCommerce – 2.5.3
WooCommerce Shipping & Tax: írta WooCommerce – 2.5.1
WooCommerce: írta Automattic – 8.6.1
WP Rollback: írta WP Rollback – 2.0.6
WPForms Lite: írta WPForms – 1.8.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Webshop főoldal: #394 - /shop-filceim-termekek/
Kosár: #28 - /kosar/
Pénztár: #395 - /checkout/
Fiókom: ❌ Az oldal nincs beállítva
Általános Szerződési Feltételek: #1338 - /altalanos-szerzodesi-feltetelek/

### Theme ###

Name: Astra
Version: 4.6.5
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Amennyiben a WooCommerce-t egy olyan szülősablonban módosítunk
amelyet nem saját magunk készítettünk
akkor javasoljuk a származtatott sablon használatát. Hogyan készítsünk származtatott sablonokat

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: HU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-23 19:49:48 +01:00
Options: ✔
Notes: 128
Onboarding: completed

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://filceim.hu?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 91
Oldest: 2024-01-23 07:58:55 +0100
Newest: 2024-02-20 07:35:05 +0100

Complete: 20 155
Oldest: 2024-01-23 07:19:37 +0100
Newest: 2024-02-22 20:50:23 +0100

Failed: 54
Oldest: 2023-02-20 06:55:13 +0100
Newest: 2024-02-21 16:32:53 +0100

Pending: 20
Oldest: 2024-02-22 20:51:28 +0100
Newest: 2024-02-27 19:37:10 +0100

### Status report information ###

Generated at: 2024-02-22 20:50:43 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@Filceim I used Google translate to translate your description into English

> At the beginning of December, I posted several products that can be purchased in 3 different sizes. It worked perfectly fine. At the beginning of February, I added other products based on this model: They also worked well.
Then a few days ago I noticed that the products posted in December were broken, the new ones work fine.
When I go to the product page, the add to cart button fades out. I can select the option, but I can't add it to the cart. It says to select a product option before placing it in the cart.
For example: the error can be viewed on this page: https://filceim.hu/termek/koreai-filclap-901-sotet-szurke-filctekercs/
Unfortunately, there are many such products that are bad.

This looks like a support request. I will mark this as a support request which will post instructions for accessing support.
