### ISSUE TITLE
[CYS] Investigate issue preventing users to proceed to the pattern assembler

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#44916]
Initially reported by @roykho on p1708547880400059-slack-C02FL3X7KR6

> When I click on Start Designing button I eventually get a console error. ![file.png](https://github.com/woocommerce/woocommerce/assets/15730971/ae815694-70cf-42c0-8d48-d2027ea7920f)

> This is in core. And looking further, I am seeing this PHP error Fatal error: Uncaught InvalidArgumentException: Overriding existing data with an already registered key is not allowed in /Users/ro/projects/woocommerce-monorepo/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:431

Additional information:

- Active theme: Tsubaki
- Active Plugins:

![file.png](https://github.com/woocommerce/woocommerce/assets/15730971/da5ab3f6-e8f8-44a9-a2ce-7c5f8584a0d0)

@albarin and I were not able to reproduce with the TT4 theme + Gutenberg/Jetpack/Woo AI/Woo Beta Tester plugins enabled.

Note: while I did find one occurrence of the `PHP Fatal error:  Uncaught InvalidArgumentException: Overriding existing data with an already registered key is not allowed in /Users/patriciahillebrandt/Woo/plugins/woocommerce/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:431` in my error log, I wasn't able to trigger it via Start Designing button, so additonal investigation is needed.

Opening this issue so we can investigate Roy's setup and identify any possible conflicts.

**Comment by roykho** [comment]
Thanks for opening this issue up. I want to add additional notes. I tried deactivating all non-essential plugins and I still get the same error. I also tried switching theme (T24) and same result.

I then error logged the point where it fails (https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php#L429) for both the themes I've tested and here is the following:

Tsubaki:
http://woo-blocks-dev.test/wp-admin/site-editor.php?canvas=edit&path=%2Ftemplate-parts%2Fsingle&postId=tsubaki//mini-cart&postType=wp_template_part

T24:
http://woo-blocks-dev.test/wp-admin/site-editor.php?canvas=edit&path=%2Ftemplate-parts%2Fsingle&postId=woocommerce/woocommerce//mini-cart&postType=wp_template_part

**Comment by nefeline** [comment]
Marking this issue as complete as it has been addressed via https://github.com/woocommerce/woocommerce/pull/46139
