### ISSUE TITLE
Add support for optional tests to `ci.yml`

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#45097]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
The `ci` configuration and `ci.yml` do not currently support optional tests. We should add support for optional tests so that they can be used for things like unit tests against the nightly WP build. The tests against the nightly build were disabled in #45096, and should be re-introduced once this support is added.

@ObliviousHarmony  suggests:

> Currently ci.yml does not support optional tests. I think it might make sense to add an optional config option to the package.json CI config for jobs. Unfortunately, GitHub doesn't currently provide a way for us to implement this in an easy way. [There's some backend work they have to ship](https://github.com/actions/runner/pull/2477) before it can be supported as cleanly as it should be.

> I think [this action](https://github.com/marketplace/actions/matrix-outputs-write) might be a good candidate in the interim since it is a workaround for the matrix outputs problem. I'd say:

> * Add an optional setting to [config.ci](http://config.ci/) for lint and test job types. This is relatively easy to add in the ci-jobs command's parser and have it bubble up to the JSON output to the matrix.
> * Add the "write" action above to the CI job that runs if: always() and writes the result of the job based on the ID of the job.
> * Add the "read" action to the evaluate step and replace the flat pass/fail with something that checks the content of the outputs generated in the "write" action.
> * For "optional" failures, log it and don't consider it a failure for the evaluation.
> * Otherwise, failures should mark the job as failed.

**Comment by adimoldovan** [comment]
The first part adding an optional setting to config.ci was implemented with https://github.com/woocommerce/woocommerce/issues/47223
