### ISSUE TITLE
[Launch Your Store] Settings Screen

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#45107]
### Issue description

Settings to be added under WooCommerce > Settings > General

- Coming Soon vs Live
- Toggle for store pages only
- Toggle for private link

figma: 0BWMerqRR1f468EwC7g5tg-fi-858_54360

<img width="750" alt="WooCommerce → Settings → General - Coming soon store pages only" src="https://github.com/woocommerce/woocommerce/assets/4344253/09bd3eb2-bc07-4bd6-8323-85edc4a9eef8">

<img width="750" alt="WooCommerce → Settings → General - Coming soon store pages only-2" src="https://github.com/woocommerce/woocommerce/assets/4344253/ccaae162-a86a-4164-abbf-f822a2ca622c">

<img width="750" alt="WooCommerce → Settings → General - Coming soon store pages only-1" src="https://github.com/woocommerce/woocommerce/assets/4344253/617ce262-b178-4db7-89ac-c2888ffe1278">

### Accept criteria

- Users can manage their store visibility by heading to `WooCommerce -> Settings -> General`
- The “Store visibility” section should be shown between “Store address” and “Currency option”.
- When the “Coming soon” mode is active, display additional settings: hide store pages only and share the site with a private link.
- The Private URL should be in the format:
  - **If coming soon pages only** is **yes**: [shop url]?woo-share=[share-key]
  - **If coming soon pages only** is **no**: [home url]?woo-share=[share-key]
- The Private URL has a "copy link" button to copy the private link to clipboard.

**Comment by chihsuan** [comment]
> hide store pages only and share the site with a private link.

I think we can generate a secret query parameter like in Google Docs. However, when users navigate to other pages, we need to ensure that the parameters still be attached. Perhaps we can store them temporarily in a cookie or session storage. 🤔

**Comment by adrianduffell** [comment]
> Perhaps we can store them temporarily in a cookie or session storage

This sounds like the way to go 👍

**Comment by adrianduffell** [comment]
I think this could be stored in the following WordPress options:

`woocommerce_coming_soon`, with values of:
 * `yes` Coming soon mode is active.
 * `no` | `<null>`  Live mode is active.

`woocommerce_coming_soon_store_only`, with values of:
* `yes` Coming soon mode is restricted to store pages only
* `no` | `<null>` Coming soon mode applies to the whole site

`woocommerce_coming_soon_private_link`, with values of:
* `yes` Coming soon mode can be bypassed with a private link. 
* `no` | `<null>` Coming soon mode can not be bypassed with a private link

`woocommerce_coming_soon_share_key`, where the value is an autogenerated URL-friendly 32 character string.

These options should be autoloaded because they will need to be accessed on every front-end request.

**Comment by moon0326** [comment]
@chihsuan @adrianduffell Could you please elaborate on the requirements for `private link` feature?

With this link, which page can be accessed? Is it limited to just the frontend?

**Comment by adrianduffell** [comment]
> Could you please elaborate on the requirements for `private link` feature?
> 
> With this link, which page can be accessed? Is it limited to just the frontend?

Hey @moon0326 , we can handle the front-end requirements for the private link in a separate issue -- it is still a bit dependent on the spike in https://github.com/woocommerce/team-ghidorah/issues/289. The goal is to allow merchants to pass the private link to colleagues/friends/family so they can see the store and bypass the coming soon screen.

On the settings screen, I think we might need to use either the Home url or  "Shop Page" url depending whether the `store pages only` restriction is in place. We'll also need the "Copy link" functionality. I'll update the acceptance criteria with this info.
