### ISSUE TITLE
[Launch Your Store] Add function for determining if site is fresh

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#45109]
### Issue description

For Launch Your Store and other onboarding concerns, it would be useful to cater for different use-cases depending on whether WooCommerce is being installed on a fresh site vs existing site (such as a blog).

### Accept criteria

Create a function that should return if the site is fresh. This can be determined if both the following heuristics are true:

* The current user was registered less than 1 month ago.
* The WordPress option `fresh_site` has a value of `1`.

**Comment by moon0326** [comment]
As this issue depends on https://github.com/woocommerce/woocommerce/issues/45219 and simple enough, I've worked on the function in https://github.com/woocommerce/woocommerce/pull/45232

**Comment by moon0326** [comment]
Closing it as https://github.com/woocommerce/woocommerce/pull/45232 has been merged with the change required for this issue.
