### ISSUE TITLE
[Enhancement]: Woocommerce Block does not create a on change event when payment method is changed on checkout page

### ISSUE THREAD

**Issue by rajeshsingh520** [woothemes/woocommerce#45102]
### Describe the solution you'd like

One basic thing that most people do in WooCommerce is to apply some extra fees based on the different payment method selected by the customer in the checkout page. this was easily possible in the checkout page made using shortcode 

but now with this Block based checkout page this is not possible as it does not pass on the payment method selected detail to the backend and this creates the issue 

### Describe alternatives you've considered

When payment method is changed in the woocommerce block you should send the payment changed request to the backend so cart subtotal can be reprocessed based on the selected payment method

**Comment by opr** [comment]
@rajeshsingh520 hi and thank you for creating this issue! We do have something in place that could help you here, though it's a different paradigm to the shortcode checkout and admittedly a little convoluted.

- Register a server-side callback to update the cart with the additional fee. You'll need to use [`extensionCartUpdate`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md) to do this. I would also recommend setting a value in the session to store the currently selected method.
- Use the [`addAction`](https://github.com/WordPress/gutenberg/tree/trunk/packages/hooks) JS function with the `experimental__woocommerce_blocks-checkout-set-active-payment-method` hook. This will fire when the active payment method is changed. When this action fires, you can use the `extensionCartUpdate` method above to update the server side.

The docs for `extensionCartUpdate` give a pretty thorough overview of what you need to do, so I'll close this issue. If you encounter any issues then please don't hesitate to reach out.

We are aware that there's a gap in documentation for the action hooks, so we will create an issue to track that.

Thanks again for your contribution!

**Comment by rajeshsingh520** [comment]
Thanks for the help

**Comment by Crypto2099** [comment]
Hi, I'd like to re-open this as this action hook does not fire for the "default" payment method in the Gutenberg Blocks checkout method. It works as a great solution when users toggle between payment methods but if the payment method with the "additional fee" is the default option, then this action never fires.

This is the only point in the codebase where I can find this hook registered and it is only on the "onUpdate" event of a payment method so it makes sense that it is being skipped because a "default" payment is checked during render.

https://github.com/woocommerce/woocommerce/blob/7a70a93773691a6ea9ae12a9f8724ee8879a3cc0/plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/payment-method-options.js#L75

**Comment by opr** [comment]
@Crypto2099 thanks - let's hold off on reopening for now until I understand your use case better. The original use case is:

> When payment method is changed in the woocommerce block you should send the payment changed request to the backend so cart subtotal can be reprocessed based on the selected payment method

Is yours similar? If so, you can do something like this `wp.data.select( 'wc/store/payment' ).getActivePaymentMethod()` to check if your method is the one selected.

**Comment by Crypto2099** [comment]
@opr Thanks for the speedy reply!

This does work. However, I have been mashing my head against the wall attempting to review all of the newer WC documentation around this blocks-based checkout in order to solve this situation and getting nowhere for about the past week which is what finally led me to commenting on this similar issue that was as close as I could get to the end of my "troubleshooting".

This has now become a "two hook" feature due to this which isn't the end of the world but would have been a lot simpler to implement and get my custom payment method working would it have been properly documented prior to becoming the de facto option for new installs.

Now, to add a processing fee or discount depending upon payment method:

## Legacy Code

**plugin.php**
```php
add_action('woocommerce_cart_calculate_fees', [
        WC_Gateway_Cardano_Mercury::class,
        'maybe_add_fees',
], 20);
```

## New Code

**plugin_index.js**
```javascript
wp.hooks.addAction('experimental__woocommerce_blocks-checkout-render-checkout-form', 'cardano-mercury', () => {
	console.log(`Rendered checkout...`);
	const payment_method = wp.data.select('wc/store/payment').getActivePaymentMethod();
	window.wc.blocksCheckout.extensionCartUpdate({
		namespace: 'cardano-mercury',
		data: {
			payment_method: payment_method,
		},
	});
});

wp.hooks.addAction('experimental__woocommerce_blocks-checkout-set-active-payment-method', 'cardano-mercury', (payment_method) => {
	console.log(`Set active payment method...`, payment_method);
	window.wc.blocksCheckout.extensionCartUpdate({
		namespace: 'cardano-mercury',
		data: {
			payment_method: payment_method.value,
		},
	});
});
```

**plugin.php**
```php
add_action('woocommerce_cart_calculate_fees', [
        WC_Gateway_Cardano_Mercury::class,
        'maybe_add_fees',
], 20);

woocommerce_store_api_register_update_callback([
	'namespace' => 'cardano-mercury',
	'callback'  => 'cardano_mercury_update_payment_method',
]);
```

**Comment by opr** [comment]
@Crypto2099 Thanks for the feedback. We know there's a documentation gap for the actions, https://github.com/woocommerce/woocommerce/issues/45191 tracks this. This may have helped you get on track faster.

As for this part of your feedback please could you share a little more what your expectation was around documentation? We'd love to be able to improve this so understanding why you struggled with this would be helpful.

> would have been a lot simpler to implement and get my custom payment method working would it have been properly documented prior to becoming the de facto option for new installs.

We do have documentation for [`extensionCartUpdate`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md) and the [`wc/store/payment` data store](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/payment.md#selectors) but perhaps it was unclear where to find these, or there weren't enough examples?

Any feedback would be really great, thank you!

**Comment by Crypto2099** [comment]
Hey @opr lack of clear documentation about how/when to use the data stores played a role but also the lack of hooks documentation (I realize they're still flagged as experimental for now but lack of clarity about when they are called and what values are available at that time, good spot for a cross-reference to data stores there 😄).

When looking through the documentation a lot of it kept pointing back to the deprecated and outdated standalone woocommerce/woocommerce-blocks repository and the handful of functional examples are either too simplistic (cheques payment method) or too complex (Stripe).

If only I had more time aside from all my other projects to try and help write up some documentation

**Comment by rajeshsingh520** [comment]
There is a serious issue in the block, when we are changing the payment method it does not disable the "Place order" button and due to that if any one quickly click on place order after changing the payment type the order goes through without changing the payment method and applying the payment method fees.

Do you have some code to disable the "Place order" button while the request to change the payment method is done by wc.blocksCheckout.extensionCartUpdate()
