### ISSUE TITLE
[Launch Your Store] Add Task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#45108]
### Issue description

Add Launch Your Store to the task list.

Figma: 0BWMerqRR1f468EwC7g5tg-fi-835_27872

![Image](https://github.com/woocommerce/woocommerce/assets/4344253/a3bcd9e6-2b92-4a5d-ae8a-5bbf3d2b8c40)

### Accept criteria

- "Launch Your Store" task should be shown when LYS feature flag is enabled.
- Completes when the status is "launched"

**Comment by ilyasfoo** [comment]
Keep in mind there's already a `Launch your store` task in bridge. We'll need to make sure it's not conflicted when we launch
