### ISSUE TITLE
Order is not creating Using wc rest api on migrating order data from one website to the other

### ISSUE THREAD

**Issue by mohitgusain** [woothemes/woocommerce#45117]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using WC rest Api to migrate my **site_one** one order data to **site_two** by using WooCommerce API - PHP Client. So i am getting orders from site_one and trying to create that site_two with the same data, that I have in site_one. See below.

```
$orders = $site_one->get('orders', [
    'after' => $start_date,
    'before' => $end_date,
    'orderby' => 'date',
    'order' => 'desc',
    'type' => 'shop_order',
]);
```

After fetching orders, try to create an order into site_two like below

```
foreach ($orders as $order) {
    $site_two->post('orders', $order);
}
```

I

### Expected behavior

So expecting, that orders should be created in site_two, with the order data that is getting passed

### Actual behavior

But the order is not getting created and throwing the below error

> Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Cannot create existing shop_order. [woocommerce_rest_shop_order_exists

Even in my site_two there is no order with that order id or not even any post with that post id.

### Steps to reproduce

<img width="1440" alt="image" src="https://github.com/woocommerce/woocommerce/assets/30264862/e4de228b-462b-49a1-a23b-5972461bc571">

### WordPress Environment

In WC  Rest API.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Error indicates that you cannot create an order with a predefined ID. If you're looking to preserve IDs, consider using a different system to managing ids like [custom order number.](https://woo.com/products/custom-order-number/) Otherwise, try using an order migration tool.
