### ISSUE TITLE
verify_known_shoppers filter not triggered in the block based Order confirmation page

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#45136]
WooCommerce 8.4.0 introduced `woocommerce_order_received_verify_known_shoppers` filter for Order received page, but that was not ported to the blockfied one.

### Testing steps:

- Add the following code somewhere:
```php
add_filter( 'woocommerce_order_received_verify_known_shoppers', '__return_false' );
```
- Log in.
- Using a block theme and Checkout block, place an order.
- Get the confirmation page url.
- Open a new incognito page, paste the url.
- You should not be able to see the order.
- Change to a regular theme and shortcode checkout.
- Refresh the page on the incognito page, you should be able to see the order.

**Comment by wavvves** [comment]
@ralucaStan I'm adding the high priority label as I believe the blockified Order Received is lagging a bit for this filter.
In the meantime, we could probably discuss internally how to catch this cases within a proper timeframe.
