### ISSUE TITLE
Product get saved through Rest API even if errors happen later when inserting/updating an image

### ISSUE THREAD

**Issue by axi** [woothemes/woocommerce#45147]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using the REST api, I want to update one of my products. 
prepare_object_for_database() is called and set all the properties from request to the product. Nice.
Let's say the request has an image so method ```set_product_images()``` is called and because it's the main image, ```wc_product_attach_featured_image()``` is also called.
Within ```wc_product_attach_featured_image()```, $product is saved (line 1692)...
This should be the Controller responsibility (and it is but for this case).

In my case, I later do some checks in one of the subclass controller and trigger an error, but that's too late, many properties has already been saved to db...

### Expected behavior

Affect correct value, register for later saving (=commit) but not saving right away

### Actual behavior

Product already affected values get saved even if a later (validation for example) error happens.

### Steps to reproduce

Please check bug description

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://locum.local
Site address (URL): https://locum.local
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1

WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.1.2-1ubuntu2.14
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.16-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 23.90MB
Database Data Size: 18.28MB
Database Index Size: 5.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.03MB + Engine InnoDB
wp_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_doctrine_migration_versions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fep_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fep_messagemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fep_messages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fep_participants: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_moneris_monerischeckout_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.45MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 7.52MB + Index: 2.80MB + Engine InnoDB
wp_posts: Data: 2.38MB + Index: 0.38MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tmd_cat_link: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tmd_gst: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tmd_gst_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tmd_gst_rate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tmd_pd_link: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woof_sd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woof_sd_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpheka_moneris_checkout_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 50
acf-field-group: 9
acf-ui-options-page: 1
attachment: 1335
bookable_person: 5
custom_css: 1
customize_changeset: 5
elementor_library: 10
estate_agent: 3
estate_property: 14
membership_package: 6
nav_menu_item: 18
page: 17
post: 2
product: 80
revision: 161
shop_order: 37
wc_booking: 73
wc_conditional_fee: 2
wp_global_styles: 2
wp_navigation: 1
wp_template: 2
wpestate_booking: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (10) ###

Advanced Custom Fields PRO: by WP Engine – 6.2.6.1
Customer Email Verification for WooCommerce: by zorem – 1.8
Import and export users and customers: by codection – 1.25.1
Locum Plugin: by Bekatec Online Solutions – 1.0
Search & Filter: by Code Amp – 1.2.16
WC Moneris Payment Gateway Pro: by WPHEKA – 3.6
WooCommerce Accommodation Bookings: by WooCommerce – 1.2.4
WooCommerce Bookings: by WooCommerce – 2.0.9
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.7
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (1) ###

Check & Log Email: by WPOmnia – 1.0.8

### Must Use Plugins (2) ###

Bedrock Autoloader: by Roots – 1.0.3
PHPMailer SMTP: by Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #40235 - /listings-map-search/
Cart: #40236 - /cart/
Checkout: #40237 - /checkout/
My account: #40238 - /dashboard/
Terms and conditions: #40440 - /terms-conditions/

### Theme ###

Name: Locum Home
Version: 1.2.0
Author URL: https://bekatec.ca
Child Theme: ✔
Parent Theme Name: Understrap
Parent Theme Version: 1.2.2
Parent Theme Author URL: https://howarddc.com
WooCommerce Support: ✔

### Templates ###

Overrides: understrap/woocommerce/cart/cart-empty.php
locum/woocommerce/cart/cart.php
understrap/woocommerce/cart/proceed-to-checkout-button.php
understrap/woocommerce/checkout/form-checkout.php
understrap/woocommerce/checkout/form-coupon.php
locum/woocommerce/checkout/form-pay.php
locum/woocommerce/checkout/payment.php
understrap/woocommerce/global/form-login.php
understrap/woocommerce/loop/orderby.php
locum/woocommerce/myaccount/downloads.php
understrap/woocommerce/myaccount/form-edit-account.php
locum/woocommerce/myaccount/form-edit-address.php
understrap/woocommerce/myaccount/form-login.php
understrap/woocommerce/myaccount/form-lost-password.php
understrap/woocommerce/myaccount/form-reset-password.php
locum/woocommerce/myaccount/my-account.php
understrap/woocommerce/myaccount/my-address.php
understrap/woocommerce/myaccount/my-orders.php
locum/woocommerce/myaccount/navigation.php
locum/woocommerce/myaccount/orders.php
understrap/woocommerce/product-searchform.php
understrap/woocommerce/single-product/add-to-cart/simple.php
understrap/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-27 10:28:02 -07:00
Options: ✔
Notes: 86
Onboarding: completed

### Action Scheduler ###

Complete: 99
Oldest: 2024-01-29 16:05:34 +0000
Newest: 2024-02-26 17:52:25 +0000

Failed: 11
Oldest: 2023-09-21 10:28:34 +0000
Newest: 2024-02-07 17:26:12 +0000

Pending: 2
Oldest: 2024-02-27 16:35:31 +0000
Newest: 2024-03-21 16:21:32 +0000

### Status report information ###

Generated at: 2024-02-26 11:14:03 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by axi** [comment]
And here is what happened:  #40076 
2 months ago

**Comment by Konamiman** [comment]
Hi @axi, you say:

> In my case, I later do some checks in one of the subclass controller and trigger an error

Could you please provide a sample code snippet showing how you do this? I guess it's inside an inherited controller, or inside a hook handler?

**Comment by axi** [comment]
Yes, I created my own Controller that extends ```WC_Bookings_REST_Products_Controller``` (itself extending ```WC_REST_Products_Controller```). 

But in this case, I'm doing my custom checks in  ```woocommerce_rest_pre_insert_product_object``` hook filter (the hook called at the end of the ```WC_REST_Products_V2_Controller::prepare_object_for_database()``` method).

```php
        add_filter(
            hook_name: 'woocommerce_rest_pre_insert_product_object',
            callback: [$this, 'checkPreInsertUpdateProduct'],
            accepted_args: 3
        );
  ```
  
  ```php
    public function checkPreInsertUpdateProduct(
        WC_Data $product,
        WP_REST_Request $request,
        bool $creating
    ): WP_Error|WC_Data {
        $params = $request->get_params();

        // ... check and maybe return WP_Error
        
        return $product;
}

**Comment by axi** [comment]
Any news on this ?

**Comment by Konamiman** [comment]
Hi @axi, that's indeed a bug and I'm trying to figure out how to fix it without introducing breaking changes or turning the code completely upside down. Since you have probably spent some time debugging the `prepare_object_for_database` method I'd like to ask you: is the call to `set_product_images` the first point where the product is prematurely saved? I mean, no database updates happen before this call?

**Comment by axi** [comment]
I haven't noticed any other saving happening before no.
