### ISSUE TITLE
_wc_order_attribution_* and HPOS

### ISSUE THREAD

**Issue by AlchemyUnited** [woothemes/woocommerce#45169]
### Describe the solution you'd like

The order I'm looking at has eight order meta rows associated with: _wc_order_attribution_*

This seems like write-once-never-update (or close) data. It also seems like data that doesn't have major operational implications. That is, direct queries of any single _wc_order_attribution_* key is rare-ish.  

If this is the case, why wasn't this addressed with HPOS? Wouldn't it have been wise to reduce such rows to less? 

At the very least, it seems this could be stored as a single row of meta with the value being an array of all the _wc_order_attribution_* meta key value pairs. .

**Comment by layoutd** [comment]
Hi @AlchemyUnited, thanks for the feedback. You're correct that at the moment, the data is only displayed on the Order Edit and Orders tables, so combining it into one `wc_order_attribution*` meta would make sense. However, moving forward, this data should start to be included in some analytics dashboards so being able to differentiate values will be useful. 

We'll add this suggestion to the list of changes under consideration for future iterations of the feature.

**Comment by AlchemyUnited** [comment]
@layoutd  - Sure some of the fields need to be query-able directly but certainly not all. Other than those, the rest of the pairs could be stored as an array in a single option row. 

Of course, another possibility would be a custom table. 

Better these could have / should have been added to one of the HPOS tables, especially if they are something that's captured with every order.

**Comment by layoutd** [comment]
Very good points, @AlchemyUnited, thanks for the reply. I'll look into it and see if we can add streamlining the data storage in a coming iteration/release.

**Comment by AlchemyUnited** [comment]
@layoutd  - btw, I opened a similar ticket for the WooComm Stripe plugin. That one had 15+ rows of order meta, most of which didn't appear to need to be query-able. 

In short, after running the HPOS migration, more than half the remaining order meta rows were from two WooComm authored plugins. It feels like there's a lack of communication across the WooComm platform and that is having a significant not-so-positive impact on performance. 

Well, I hope this helps :)

Thanks again for the prompt and friendly replies.

**Comment by layoutd** [comment]
Thank you! One of the principal benefits of working on open source software like this is getting great feedback and input from the community of users. We can review the Woo operating procedure to see if there are improvements to make to avoid issues like the ones you've point out. Cheers!
