### ISSUE TITLE
Checkout Block's local pickup style is incorrect in the editor

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#45183]
When viewing the Checkout block in the editor, the style for the shipping method (Shipping or local pickup) UI is incorrect:

<img width="743" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/2f9d347d-da51-4824-b75c-23547a33918b">

1. Go to WooCommerce -> Settings -> Shipping -> Local Pickup
2. Enable local pickup and add a location
3. Go to Appearance -> Editor -> Templates -> Page: Checkout and see the error

**Comment by SpaceSurfer1** [comment]
Hi @opr , Just checked it on my side and it seems ok. 

![Screenshot 2024-02-29 at 6 09 19 PM](https://github.com/woocommerce/woocommerce/assets/99202999/c8697b64-aa13-4f9d-a502-f6db6cf586f5)

**Comment by opr** [comment]
Thanks for checking @SpaceSurfer1! Can you go to Appearance -> Editor -> Templates -> Page: Checkout and see the issue there? I just checked on multiple different sites with different themes and I can see it in all cases.

**Comment by SpaceSurfer1** [comment]
@opr , Yes, Going to Appearance -> Editor -> Templates -> Page and adding checkout block, I can see the issue.

![Screenshot 2024-02-29 at 9 57 53 PM](https://github.com/woocommerce/woocommerce/assets/99202999/3328acb5-14cb-430e-94fb-bf9a54965755)

I'll look into it.

**Comment by senadir** [comment]
This has been fixed by https://github.com/woocommerce/woocommerce/pull/51375
