### ISSUE TITLE
Price Filter block: Filter is not applied when using the numeric inputs

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#45228]
### Describe the bug

While using the numeric inputs in the Price Filter block, the products are not updated to reflect the applied filters, and the URL also doesn't change to reflect the applied filters.

### Expected behavior

Filters should be applied when the shopper uses the price slider and/or numeric inputs.

### Actual behavior

The price filter only applies when using the price slider range. Entering values in the numeric inputs currently does not trigger the filter.

### Steps to reproduce

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. In the block inserter, search for "Product Filter: Price (Beta)" or browse the available blocks until you find them.
5. Click on the "Product Filter: Price (Beta)" block to add it to your content.
6. Click on Save to save the changes.
7. Visit the Shop page (https://linktoyourstore.com/shop/).
8. Move the price slider and make sure the filters are being applied to the products.
9. Try inputting any number in the Max or Min inputs and check that the filters are not applied to the page/products.

https://github.com/woocommerce/woocommerce/assets/20469356/9e3b28c9-9545-43b0-a3a3-fb59f1880cd2

**Comment by dinhtungdu** [comment]
Good catch! There is an issue with the way we handle the price update in `updateProducts`, it only works for the slider now, but not the input field. I think it's a good issue to get familiar with the codebase, can you work on this @thealexandrelara ?

**Comment by thealexandrelara** [comment]
> Good catch! There is an issue with the way we handle the price update in `updateProducts`, it only works for the slider now, but not the input field. I think it's a good issue to get familiar with the codebase, can you work on this @thealexandrelara ?

Sounds good! I'll start working on this probably today. Thank you for sharing the location where the price is updated; that will help a lot.
