### ISSUE TITLE
CYS - Core: `Cannot read properties of undefined (reading 'activeThemeHasMods')` 

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#45221]
With these steps, it is possible to crash the Assembler:

1. Enable the WooCommerce Beta Tester plugin if you don't have it enabled yet.
2. On your Dashboard, head over to Tools > WCA Test Helper > Features and enable the `customize-store`.
3. Ensure you have the Gutenberg plugin installed from the latest trunk (or install it from this zip file: [gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14384613/gutenberg.zip)
4. Visit the `/wp-admin/admin.php?page=wc-admin&path=/customize-store`.
5. Follow the process.
6. Click on the arrow on the top left near the "Let's get creative" label.
7. Click on "exit and lose changes".
8. Open the console.
9. Click on "Start Designing"
10. See the error in the console: `Cannot read properties of undefined (reading 'activeThemeHasMods')` 

https://github.com/woocommerce/woocommerce/assets/4463174/db6ffa42-1f4d-422a-8507-3a1f12e2a7c8

**Comment by albarin** [comment]
Just noting that I'm getting this error instead when following the steps:
<img width="564" alt="Screenshot 2024-02-29 at 17 14 44" src="https://github.com/woocommerce/woocommerce/assets/186112/8abe4a6e-e67c-4c9c-b4d8-362534f789a9">
