### ISSUE TITLE
"No shipping options available" does not display on Shortcode checkout

### ISSUE THREAD

**Issue by ncsramona** [woothemes/woocommerce#45243]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you have a shipping zone with no shipping method and you try to checkout with a shipping address from that zone, instead of displaying the "No shipping options available" nothing is displayed on the shortcode checkout. Block checkout works as expected.

### Shipping zones
<img width="3504" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/389d30e0-9fc7-46c7-aecd-7f9c4c625c01">

### Shortcode checkout
US address
<img width="600" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/20da96b6-55e0-4c09-af24-680d548ebdd0">

UK address:
<img width="600" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/b35378bf-cfae-4ea2-ada3-589b383402c5">

### Block checkout
US address
<img width="600" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/62d88d40-6f86-4ac0-b5ea-79f18c736fb4">

UK address:
<img width="600" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/20e3ccb9-22ba-4b9b-b6a7-b40fb4f1da14">

### Expected behavior

Display the "No shipping options available" even when the shortcode checkout is used.

### Actual behavior

The Shipping option stays empty in shortcode checkout, as opposed to displaying a message about not having available shipping methods.

### Steps to reproduce

1. Go to WooCommerce > Settings > Shipping > Shipping zones
2. Set up a shipping zone (e.g. to the US) and add a shipping method
3. Leave the "Rest of the world" zone without any shipping method
4. Make sure your checkout page uses the `[woocommerce_checkout]` shortcode
5. Try to check out a product using a US address and see the shipping method you added
6. Change the address to something outside the US and notice how the "no shipping options available" does not show up

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://shipping.local
Site address (URL): http://shipping.local
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 7.61MB
Database Data Size: 5.73MB
Database Index Size: 1.88MB
wp_woocommerce_sessions: Data: 0.36MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 9
post: 2
product: 22
product_variation: 3
revision: 4
shipping_package: 2
shop_order: 20
shop_order_placehold: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (17) ###

Custom codes: by your-name – 0.1
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.11
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.4
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.15.4
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.4
WooCommerce FedEx Shipping: by WooCommerce – 3.8.7
WooCommerce Local Pickup Plus: by SkyVerge – 2.11.1
WooCommerce Royal Mail: by WooCommerce – 3.0.2
WooCommerce Shipment Tracking: by WooCommerce – 2.4.3
WooCommerce Shipping & Tax: by WooCommerce – 2.5.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.5.5
WooCommerce Stripe Gateway: by WooCommerce – 8.0.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.1
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.8.0
WooPayments: by Automattic – 7.2.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-02 11:49:09 +01:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 33
Oldest: 2024-01-31 07:53:39 +0100
Newest: 2024-03-01 15:00:43 +0100

Failed: 1
Oldest: 2023-11-09 12:58:09 +0100
Newest: 2023-11-09 12:58:09 +0100

Pending: 1
Oldest: 2024-03-02 14:42:54 +0100
Newest: 2024-03-02 14:42:54 +0100

### Status report information ###

Generated at: 2024-03-01 15:02:04 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ncsramona** [comment]
Reported by 7820600-zen

**Comment by opr** [comment]
Hi thank you for reporting. This issue is the same as https://github.com/woocommerce/woocommerce/issues/44920 so I will close it. Please follow https://github.com/woocommerce/woocommerce/issues/44920 for further updates.
