### ISSUE TITLE
orders with custom status code disappears from order list

### ISSUE THREAD

**Issue by hanifw** [woothemes/woocommerce#45266]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We use the update_status('wc-ready-to-collect') function but woocommerce removes 'wc-' and saves the order status as 'ready-to-collect' causing the order to disappear from the order list.

...

We tried this
- $order->update_status('ready-to-collect') -- supposed woocommerce will add 'wc- to make it 'wc-ready-to-collect' but it did not happen and store order status as 'ready-to-collect' causes the order to disappear from the order list.

-we changed to $order->update_status('wc-ready-to-collect') -- woocommerce somehow deleted 'wc-' to save order status as 'ready-to-collect' causing the order to disappear from the order list.

---

### Expected behavior

Function $order->update_status('wc-ready-to-collect') to save order status as 'wc-ready-to-collect'.

### Actual behavior

Woocommerce somehow deleted 'wc-' and saved the order status as 'ready-to-collect' causing the order to disappear from the order list.

### Steps to reproduce

It is a shipping plugin - https://github.com/delyva/wp-delyvax

We've added a few custom statuses.- Refer: https://github.com/delyva/wp-delyvax/blob/master/functions.php

function delyvax_register_order_statuses() {

    register_post_status( 'wc-preparing', array(
        'label'                     => _x('Preparing', 'Order status', 'default' ),
        'public'                    => true,
        'exclude_from_search'       => false,
        'show_in_admin_all_list'    => true,
        'show_in_admin_status_list' => true,
        'label_count'               => _n_noop( 'Preparing (%s)', 'Preparing (%s)' )
    ) );
..
}
add_action( 'init', 'delyvax_register_order_statuses',20,0);

Once customer make payment on woocommerce, a shipment is created as draft on our portal.

Once the merchant book a shipment on our portal, our system will send a webhook to woocommerce.

On woocommerce, we process the webhook and on woocommerce to change the order status to ready-to-collect.

Refer: https://github.com/delyva/wp-delyvax/blob/master/includes/delyvax-webhook.php

add_action( 'woocommerce_after_register_post_type', 'delyvax_webhook_order_created',10,0);

function delyvax_webhook_order_created()
{
....
if (!empty($order))
                          {
                              //on the way to pick up
                              if( !$order->has_status('wc-ready-to-collect') )
                              {
                                  $order->update_status('wc-ready-to-collect', 'Delivery order number: '.$consignmentNo.' - <a href="https://api.delyva.app/v1.0/order/'.$shipmentId.'/label?companyId='.$company_id.'" target="_blank">Print label</a> - <a href="https://'.$company_code.'.delyva.app/customer/strack?trackingNo='.$consignmentNo.'" target="_blank">Track</a>.', false);
                                  
                                  // wp_update_post(['ID' => $order->get_id(), 'post_status' => 'wc-ready-to-collect']);
                                  //end update sub orders
                              }
                          }

}

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): http://wc-demo.jwqkqu1td1-v1p3zergj3ye.p.temp-site.link
Site address (URL): http://wc-demo.jwqkqu1td1-v1p3zergj3ye.p.temp-site.link
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.3
PHP Version: 8.2.15
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.11.7-MariaDB-1:10.11.7+maria~ubu2204
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 5.40MB
Database Data Size: 3.70MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 2
shop_order_placehold: 8
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Delyva: by Delyva – 1.1.52
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/runcloud/webapps/wc-demo/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/runcloud/webapps/wc-demo/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/runcloud/webapps/wc-demo/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-04 03:56:48 +08:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 86
Oldest: 2024-03-03 11:58:54 +0800
Newest: 2024-03-03 16:01:47 +0800

Failed: 1
Oldest: 2024-03-03 12:02:59 +0800
Newest: 2024-03-03 12:02:59 +0800

Pending: 1
Oldest: 2024-03-04 11:58:54 +0800
Newest: 2024-03-04 11:58:54 +0800


### Status report information ###

Generated at: 2024-03-03 16:24:55 +08:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @hanifw!

Thanks for reaching out. We were not able to reproduce this. As long as the status is registered with WP and also via the `wc_order_statuses` filter, things work correctly.

For example, with the following setup we're able to do `$order->set_status( 'wc-processing' ); $order->save();` and the order status gets updated correctly (no stripping or extraneous prepending of the `wc-` prefix).

```php
add_action(
	'init',
	function() {
		register_post_status( 'wc-preparing', array(
			'label'                     => _x('Preparing', 'Order status', 'default' ),
			'public'                    => true,
			'exclude_from_search'       => false,
			'show_in_admin_all_list'    => true,
			'show_in_admin_status_list' => true,
			'label_count'               => _n_noop( 'Preparing (%s)', 'Preparing (%s)' )
		) );
	},
	50
);


add_filter(
	'wc_order_statuses',
	function( $order_statuses ) {
		$order_statuses['wc-preparing'] = __( 'Preparing', 'default' );
		return $order_statuses;
	}
);
```

Could you give the above a try? Please let us know.

**Comment by hanifw** [comment]
> Hi @hanifw!
> 
> Thanks for reaching out. We were not able to reproduce this. As long as the status is registered with WP and also via the `wc_order_statuses` filter, things work correctly.
> 
> For example, with the following setup we're able to do `$order->set_status( 'wc-processing' ); $order->save();` and the order status gets updated correctly (no stripping or extraneous prepending of the `wc-` prefix).
> 
> ```
> add_action(
> 	'init',
> 	function() {
> 		register_post_status( 'wc-preparing', array(
> 			'label'                     => _x('Preparing', 'Order status', 'default' ),
> 			'public'                    => true,
> 			'exclude_from_search'       => false,
> 			'show_in_admin_all_list'    => true,
> 			'show_in_admin_status_list' => true,
> 			'label_count'               => _n_noop( 'Preparing (%s)', 'Preparing (%s)' )
> 		) );
> 	},
> 	50
> );
> 
> 
> add_filter(
> 	'wc_order_statuses',
> 	function( $order_statuses ) {
> 		$order_statuses['wc-preparing'] = __( 'Preparing', 'default' );
> 		return $order_statuses;
> 	}
> );
> ```
> 
> Could you give the above a try? Please let us know.

Yes. In other parts of the code, its gets updated correctly. 

This one gets updated correctly:

Reference: https://github.com/delyva/wp-delyvax/blob/master/functions.php

$main_order->update_status('wc-ready-to-collect', 'Delivery order number: '.$trackingNo.' - <a href="https://api.delyva.app/v1.0/order/'.$shipmentId.'/label?companyId='.$company_id.'" target="_blank">Print label</a> - <a href="https://'.$company_code.'.delyva.app/customer/strack?trackingNo='.$trackingNo.'" target="_blank">Track</a>.', false);

However, when we put in this part of the code it does not on action after woocommerce_after_register_post_type, it does not.

Reference: https://github.com/delyva/wp-delyvax/blob/master/includes/delyvax-webhook.php

add_action( 'woocommerce_after_register_post_type', 'delyvax_webhook_order_created',10,0);

$order->update_status('wc-ready-to-collect', 'Order status changed to Ready.', false); // order note is optional, if you want to  add a note to order
                                    
- it is the same code, but at a different place, gets executed differently.

**Comment by jorgeatorres** [comment]
@hanifw: Thanks for getting back to me. Could you please provide some _minimal_ example code that showcases the problem?

Also, something worth checking: under normal circumstances `woocommerce_after_register_post_type` is triggered _before_ `init`, which is the hook you're using to register the new post statuses with `register_post_status()`. That means that those are not available when updating orders inside the `woocommerce_after_register_post_type` callback, which might explain the issue you're seeing. Is there any reason you need to use `woocommerce_after_register_post_type` to process orders? There might be a better alternative depending on what you need.
In any case, post statuses need to be already registered _before_ they can be used.

**Comment by hanifw** [comment]
Can you recommend which hook /action we should use instead ofwoocommerce_after_register_post_type?

**Comment by jorgeatorres** [comment]
Hi @hanifw!

I'm not entirely sure what to recommend as I'm not sure what kind of processing you need to do, but `woocommerce_after_register_post_type` is part of the initialization of WooCommerce. It seems to me your code is meant to respond to a request from an outside service. If that's correct, I'd suggest you use `parse_request` or `template_redirect`.

Let us know if that works.
