### ISSUE TITLE
Shipping cost changed at checkout

### ISSUE THREAD

**Issue by GabyDinka** [woothemes/woocommerce#45267]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Shipping cost are correct in settings, and when clients go to cheout, it is changed (from 4.900 to 5. I have been having big trouble with coustumers... 
any way to solve this? I canceled temporal shipping cost, but it complicate me.
It was working ok yesterday, today it just started working like this.

### Expected behavior

shipping price should be the one in settings. 

### Actual behavior

I write $4.900 shipping priec in settings and in checkout it is automatically changed to $5.  (And from $3.300 to $3), while in settings still unchenged correctly cost...

### Steps to reproduce

![settings](https://github.com/woocommerce/woocommerce/assets/162043120/6f935dfd-bab6-4ddb-9fc6-c5a447854fce)
![checkout](https://github.com/woocommerce/woocommerce/assets/162043120/695057cd-8f4a-40a4-9c7e-26a2e05f8de0)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://dinkos-semillas.com
Site address (URL): https://dinkos-semillas.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.16
PHP Post Max Size: 516 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.6.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: dcf_
Total Database Size: 198.61MB
Database Data Size: 151.60MB
Database Index Size: 47.01MB
dcf_woocommerce_sessions: Data: 51.65MB + Index: 0.96MB + Engine MyISAM
dcf_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
dcf_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_order_items: Data: 2.99MB + Index: 1.64MB + Engine MyISAM
dcf_woocommerce_order_itemmeta: Data: 26.28MB + Index: 20.36MB + Engine MyISAM
dcf_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_actionscheduler_actions: Data: 0.28MB + Index: 0.16MB + Engine MyISAM
dcf_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
dcf_actionscheduler_logs: Data: 0.24MB + Index: 0.16MB + Engine MyISAM
dcf_aioseo_cache: Data: 0.31MB + Index: 0.03MB + Engine InnoDB
dcf_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dcf_aioseo_posts: Data: 0.34MB + Index: 0.02MB + Engine InnoDB
dcf_aiowps_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_aiowps_failed_logins: Data: 0.08MB + Index: 0.02MB + Engine MyISAM
dcf_aiowps_global_meta: Data: 1.66MB + Index: 0.00MB + Engine MyISAM
dcf_aiowps_login_activity: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
dcf_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_cartflows_ca_cart_abandonment: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
dcf_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dcf_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_commentmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
dcf_comments: Data: 4.55MB + Index: 1.13MB + Engine MyISAM
dcf_duplicator_packages: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
dcf_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dcf_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_newsletter: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
dcf_newsletter_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_newsletter_sent: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_newsletter_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_newsletter_user_logs: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
dcf_nrp_accounts: Data: 0.22MB + Index: 0.08MB + Engine InnoDB
dcf_nrp_points_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_options: Data: 25.37MB + Index: 0.33MB + Engine MyISAM
dcf_postmeta: Data: 15.75MB + Index: 8.37MB + Engine MyISAM
dcf_posts: Data: 2.73MB + Index: 0.70MB + Engine MyISAM
dcf_scconn_cache_en_US: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_sc_cache_en_US: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_stock_log: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
dcf_termmeta: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
dcf_terms: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
dcf_term_relationships: Data: 0.07MB + Index: 0.17MB + Engine MyISAM
dcf_term_taxonomy: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
dcf_tm_taskmeta: Data: 0.11MB + Index: 0.03MB + Engine MyISAM
dcf_tm_tasks: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
dcf_usermeta: Data: 6.50MB + Index: 2.78MB + Engine MyISAM
dcf_users: Data: 0.30MB + Index: 0.26MB + Engine MyISAM
dcf_wc_admin_notes: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
dcf_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
dcf_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_wc_customer_lookup: Data: 0.34MB + Index: 0.31MB + Engine MyISAM
dcf_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
dcf_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dcf_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
dcf_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
dcf_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
dcf_wc_order_product_lookup: Data: 4.96MB + Index: 4.30MB + Engine MyISAM
dcf_wc_order_stats: Data: 0.35MB + Index: 0.24MB + Engine MyISAM
dcf_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_wc_product_meta_lookup: Data: 0.05MB + Index: 0.07MB + Engine MyISAM
dcf_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
dcf_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
dcf_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
dcf_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
dcf_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
dcf_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
dcf_wpmailsmtp_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
dcf_yith_wcas_data_index_lookup: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
dcf_yith_wcas_index_relationship: Data: 3.47MB + Index: 3.59MB + Engine InnoDB
dcf_yith_wcas_index_token: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
dcf_yith_wcas_query_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
amn_om: 1
amn_wpforms-lite: 1
attachment: 1237
custom_css: 1
elementor_library: 1
jb_store_css: 7
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 39
oembed_cache: 13
omapi: 1
page: 17
product: 641
revision: 96
shop_coupon: 11
shop_order: 4557
shop_order_refund: 2
wp_global_styles: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

VaultPress: by Automattic – 3.0.0
AddToAny Share Buttons: by AddToAny – 1.8.9
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.9.2
Disable Blogging: by Fact Maven – 2.1.0
Duplicator: by Duplicator – 1.5.8.1
Easy Loyalty Points and Rewards for WooCommerce: by Nujo Plugins – 1.4.0
Elementor: by Elementor.com – 3.19.4
Excel-Like Product Manager for WooCommerce and WP E-commerce: by Holest Engineering – 2.1.71
GA Google Analytics: by Jeff Starr – 20231101
Site Kit by Google: by Google – 1.121.0
XML Sitemap Generator for Google: by Auctollo – 4.1.19
Excel-like product manager for wooCommerce multi-import addon: by Holest – 1.0.8
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.0.2
Jetpack: by Automattic – 13.1.3
Points and Rewards for WooCommerce: by WP Swings – 2.1.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.1

Customizer for WooCommerce: by SkyVerge – 2.8.0
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

Stock Manager for WooCommerce: by StoreApps – 3.0.0
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.12
WooCommerce: by Automattic – 8.6.1
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.3.0

WPForms Lite: by WPForms – 1.8.7.2
YITH WooCommerce Ajax Search: by YITH – 2.1.0
YITH WooCommerce Product Bundles: by YITH – 2.4.0

### Inactive Plugins (5) ###

GTranslate: by Translate AI Multilingual Solutions – 3.0.5
Mercado Pago payments for WooCommerce: by Mercado Pago – 7.2.1
OnSale Page for WooCommerce: by wpgenie – 1.1.3
Selling Commander Connector https://sellingcommander.com/: by Holest Engineering – 1.2.31
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.26

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (4) ###

Elementor Safe Mode: by Elementor.com – 1.0.0
Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.2
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: ARS ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /mi-cuenta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: NEW CHILD THEME
Version: 1.3.0.1540660417
Author URL: https://www.themegrill.com
Child Theme: ✔
Parent Theme Name: eStore
Parent Theme Version: 1.6.2
Parent Theme Author URL: https://www.themegrill.com
WooCommerce Support: ✔

### Templates ###

Overrides: estore/woocommerce/archive-product.php
estore/woocommerce/cart/cart-totals.php
estore/woocommerce/cart/cross-sells.php
estore/woocommerce/checkout/form-billing.php
estore/woocommerce/checkout/form-checkout.php
/home1/semillb2/public_html/wp-content/plugins/points-and-rewards-for-woocommerce/public/woocommerce/checkout/form-coupon.php
estore/woocommerce/checkout/form-login.php
estore/woocommerce/content-product.php
estore/woocommerce/content-single-product.php
estore/woocommerce/global/wrapper-end.php
estore/woocommerce/global/wrapper-start.php
estore/woocommerce/loop/add-to-cart.php
estore/woocommerce/loop/price.php
estore/woocommerce/loop/rating.php
estore/woocommerce/single-product/price.php
estore/woocommerce/single-product/related.php
estore/woocommerce/single-product.php
estore/woocommerce/taxonomy-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-04 10:51:31 +00:00
Options: ✔
Notes: 210
Onboarding: completed

### Action Scheduler ###

Complete: 1,108
Oldest: 2024-02-01 21:14:31 +0000
Newest: 2024-03-03 15:50:39 +0000

Failed: 49
Oldest: 2023-02-15 02:12:03 +0000
Newest: 2023-06-06 21:21:08 +0000

Pending: 8
Oldest: 2024-03-03 18:41:55 +0000
Newest: 2024-03-07 21:17:14 +0000

### Status report information ###

Generated at: 2024-03-03 16:48:02 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by GabyDinka** [comment]
it is my first time having an issue with woocommerce... please help me solve it...

**Comment by senadir** [comment]
Make sure your currency rounding options are leaving space for 1 or 2 places after dicimal

<img width="727" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/f21ac044-7a37-49dc-a688-609d1e7e3e0c">

**Comment by senadir** [comment]
From your system settings, you have 0 Decimals, which will cause the numbers to round up/down `Number of Decimals: 0`, please change that for this to work.
