### ISSUE TITLE
[Enhancement]: Product categories display in a grid, using WooCommerce blocks

### ISSUE THREAD

**Issue by anastas10s-afk** [woothemes/woocommerce#45269]
### Describe the solution you'd like

While there are options to display product categories in a list, on the front-end of a website, there is currently no option to display Product categories in a grid, using WooCommerce blocks, from what I gather.

### Describe alternatives you've considered

Currently the grid display has to be created manually, I'm afraid.

### Additional context

<img width="993" alt="Screenshot 2024-03-03 at 22 35 49" src="https://github.com/woocommerce/woocommerce/assets/73900974/a67ef80b-c8d6-4e41-ad20-a3ac9be3392a">

**Comment by shameemreza** [comment]
Another request here: 8252258-zen

**Comment by albarin** [comment]
Hi @anastas10s-afk, thanks for creating this issue!
Good news! We have plans to create a new block that displays product categories in a grid on our near roadmap, we don’t have a specific timeframe for when the project will kick off, so stay tuned!
Thanks!

**Comment by anastas10s-afk** [comment]
Sounds great, thank you for the update @albarin!
