### ISSUE TITLE
Actions are not removed in Blocks in the editor

### ISSUE THREAD

**Issue by tombroucke** [woothemes/woocommerce#45272]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When rendering woocommerce templates from a custom block, actions and filters are not removed in the editor on the first load.

The block:
```php
<div>
<?php
	/**
	 * Hook: woocommerce_before_shop_loop_item.
	 *
	 * @hooked woocommerce_template_loop_product_link_open - 10
	 */
	do_action( 'woocommerce_before_shop_loop_item' );

	/**
	 * Hook: woocommerce_before_shop_loop_item_title.
	 *
	 * @hooked woocommerce_show_product_loop_sale_flash - 10
	 * @hooked woocommerce_template_loop_product_thumbnail - 10
	 */
	do_action( 'woocommerce_before_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_shop_loop_item_title.
	 *
	 * @hooked woocommerce_template_loop_product_title - 10
	 */
	do_action( 'woocommerce_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_after_shop_loop_item_title.
	 *
	 * @hooked woocommerce_template_loop_rating - 5
	 * @hooked woocommerce_template_loop_price - 10
	 */
	do_action( 'woocommerce_after_shop_loop_item_title' );

	/**
	 * Hook: woocommerce_after_shop_loop_item.
	 *
	 * @hooked woocommerce_template_loop_product_link_close - 5
	 * @hooked woocommerce_template_loop_add_to_cart - 10
	 */
	do_action( 'woocommerce_after_shop_loop_item' );
	?>
</div>
```

If we add
```
remove_action('woocommerce_before_shop_loop_item_title`, `woocommerce_template_loop_product_thumbnail`, 10);
```

To functions.php, the product thumbnail will not be removed in the editor.

The code in https://github.com/woocommerce/woocommerce/pull/40648 calls the includes method from the `'load-post.php'` hook. But this hook runs very late. By the time this hook runs, all reasonable actions to call `remove_action` of `remove_filter` have already run. 

A temporary solution is to add an additional `remove_action` on the `'load-post.php'` hook, but now we have duplicate code:

```php
add_action('load-post.php', function() {
    remove_action('woocommerce_before_shop_loop_item_title`, `woocommerce_template_loop_product_thumbnail`, 10);
}, 11);
```

### Expected behavior

The thumbnail should be removed.

### Actual behavior

The thumbnail is not removed in the editor. If we switch from preview mode to edit mode and back to preview mode, the block is rendered just fine.

### Steps to reproduce

1. Clean install
2. Register custom block
3. Render a product using WooCommerce hooks (`do_action( 'woocommerce_before_shop_loop_item_title' );` etc)
4. Preview the block in the editor.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://acf-cache.test
Site address (URL): https://acf-cache.test
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.3
PHP Version: 8.2.15
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.6.0
(SecureTransport) OpenSSL/3.2.1

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_frsh_
Total Database Size: 4.81MB
Database Data Size: 3.15MB
Database Index Size: 1.66MB
wp_frsh_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_frsh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_frsh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frsh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frsh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_frsh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frsh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_options: Data: 2.05MB + Index: 0.03MB + Engine InnoDB
wp_frsh_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_frsh_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_frsh_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_frsh_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_frsh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frsh_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_frsh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_frsh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_frsh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_frsh_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frsh_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_frsh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frsh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frsh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 9
post: 2
product: 1
revision: 13
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Advanced Custom Fields PRO: by WP Engine – 6.2.7
Spatie Ray: by Spatie – 1.7.5
Test: by  –
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-04 19:46:53 +00:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Complete: 6
Oldest: 2024-03-01 19:48:25 +0000
Newest: 2024-03-03 19:53:10 +0000

Failed: 1
Oldest: 2024-03-01 19:48:25 +0000
Newest: 2024-03-01 19:48:25 +0000

Pending: 1
Oldest: 2024-03-04 19:53:10 +0000
Newest: 2024-03-04 19:53:10 +0000

### Status report information ###

Generated at: 2024-03-04 07:58:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Hi @tombroucke,
the hooks in question are specifically designed to run on the frontend, and it's advisable to avoid executing them on the editor side to prevent potential unexpected errors.

For WooCommerce, we've implemented a "placeholder" block to circumvent running these hooks on the editor side. Here's a visual representation:


| Editor | Frontend |
|--------|--------|
|![Image](https://github.com/woocommerce/woocommerce/assets/4463174/92e5f304-c827-4efd-acba-f8e6188de600)| ![Image](https://github.com/woocommerce/woocommerce/assets/4463174/ab1371db-e32e-44d8-a281-9f871d481780)| 


If you're interested in the implementation details, you can review the code on both the editor and frontend sides:

- [editor side code](https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce-blocks/assets/js/blocks/classic-template/index.tsx)
- [frontend side code ](https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce/src/Blocks/BlockTypes/ClassicTemplate.php)


I will proceed to close the issue since it appears to be unrelated to a specific problem. However, should you have additional questions or concerns, please don't hesitate to reopen this issue or create a new one.
