### ISSUE TITLE
Woocommerce Shipping Validation error

### ISSUE THREAD

**Issue by jeremyqbutler** [woothemes/woocommerce#45271]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We've consistently had a state and zip code validation issue that we can't seem to fix. It's intermittent. Sometimes when we're calculating shipping we'll get an error that says cant calculate even if the state and zip code are correct.

<img width="1867" alt="Screenshot 2024-02-16 at 12 42 02 AM" src="https://github.com/woocommerce/woocommerce/assets/21996854/66d32eed-0b5e-48a8-8c17-5880bc9f7781">

### Expected behavior

It needs to work all of the time. It's inconsistent.

### Actual behavior

Calcualated shipping It gives us a random error message at the top of the page sometimes, even if the shipping info is correct.

### Steps to reproduce

1. Add an item to the cart
2. Calculate shipping (add State with any correct zip code)
3. Wait to see if it gives you an error
4. Do this a few times using different browsers and Incognito Mode

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.hirisecamera.com
Site address (URL): https://www.hirisecamera.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33.4
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35-27
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 237.22MB
Database Data Size: 170.19MB
Database Index Size: 67.03MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.33MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 0.95MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.52MB + Index: 0.33MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ilightbox: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iqblock_logging: Data: 0.31MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_layerslider: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mw_wc_qbo_sync_customer_pairs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_payment_id_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_paymentmethod_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_product_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_customers: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_history: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_mw_wc_qbo_sync_shipping_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_tax_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_variation_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_wq_cf_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.25MB + Index: 0.17MB + Engine InnoDB
wp_origincode_videogallery_galleries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_origincode_videoorigincode_gallery_videos: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pantheon_sessions: Data: 56.58MB + Index: 39.16MB + Engine InnoDB
wp_pfhub_portfolio_grids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pfhub_portfolio_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 23.55MB + Index: 9.03MB + Engine InnoDB
wp_posts: Data: 8.50MB + Index: 0.64MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.50MB + Index: 0.16MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.20MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sdm_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_spbc_auth_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_backuped_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_backups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_bfp_blocked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_cure_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall__personal_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_firewall__personal_ips_v4: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_firewall__personal_ips_v6: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_firewall_data_v4: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_spbc_firewall_data_v6: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_firewall_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_important_file_snapshots: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_important_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_monitoring_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_spbc_scan_frontend: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_links_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_spbc_scan_results: Data: 6.02MB + Index: 1.38MB + Engine InnoDB
wp_spbc_scan_results_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_scan_signatures: Data: 0.28MB + Index: 0.09MB + Engine InnoDB
wp_spbc_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_spbc_traffic_control_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_users: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_vimeography_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vimeography_gallery_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.28MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_stats: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 4.47MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 22.56MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.44MB + Index: 0.13MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwafconfig: Data: 1.50MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_entries: Data: 0.47MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 1
acoplw_prod_list: 1
amn_mi-lite: 1
attachment: 1060
carousels: 16
chch-pop-up-pro: 1
cp_queue: 107
customize_changeset: 115
custom_css: 3
elementor-hf: 2
elementor_library: 38
evideo: 7
ml-slider: 1
nav_menu_item: 11
page: 141
post: 174
product: 60
revision: 6
ridez-breadcrumb: 2
schema: 3
sdm_downloads: 2
shop_coupon: 18
shop_order: 1409
shop_order_refund: 84
slides: 1
smart_offers: 3
testimonials: 1
wobd-badge-designer: 3
wpcode: 4
wpforms: 2
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Health Check - Troubleshooting: by Team Yoast – 23.42
WP Engine Smart Plugin Manager: by WP Engine – 5.17.7
Elementor: by Elementor.com – 3.19.4
Lottie Player - Block: by bPlugins LLC – 1.1.5
WooCommerce FedEx Shipping Plugin with Print Label: by PluginHive – 5.0.7
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.25

WooCommerce Sync for QuickBooks Online - by MyWorks: by MyWorks – 2.9.0
Premium Addons for Elementor: by Leap13 – 4.10.22
Redirection: by John Godley – 5.4.2
Slider Revolution: by ThemePunch – 6.6.19
Security by CleanTalk: by CleanTalk Security – 2.129
String Locator: by InstaWP – 2.6.3
Stripe WooCommerce Addon: by Syed Nazrul Hassan – 1.0.8
TWB Woocommerce Reviews: by Abu Bakar – 1.7.5
WooCommerce PayPal Payments: by WooCommerce – 2.5.4
WooCommerce Table Rate Shipping Pro: by PluginHive – 3.2.2
WooCommerce: by Automattic – 8.6.1
Wordfence Security: by Wordfence – 7.11.3
Yoast SEO: by Team Yoast – 19.13
WP File Manager: by mndpsingh287 – 7.2.4
WP Mail SMTP Pro: by WP Mail SMTP – 4.0.1
WPForms: by WPForms – 1.8.6.4
Yoast SEO: WooCommerce: by Team Yoast – 12.2

### Inactive Plugins (12) ###

Classic Editor: by WordPress Contributors – 1.6.3
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
Theme Customisations: by WooThemes – 1.0.0
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.3.3
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Product Videos Gallery: by Perception System Pvt. Ltd. – 1.0.0
WooPayments: by Automattic – 7.2.0
WPC Smart Compare for WooCommerce: by WPClever – 6.2.1
WPC Smart Quick View for WooCommerce: by WPClever – 4.0.0
WPC Smart Wishlist for WooCommerce: by WPClever – 4.8.3
WP Func Control: by WordPress – 12.7.5
WP Memory Defender: by WordPress – 26.2.9

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (7) ###

Elementor Safe Mode: by Elementor.com – 1.0.0
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
Security by CleanTalk: Must-Use Module: by CleanTalk Security – 2.0
WP Engine Cache Plugin: by WP Engine – 1.2.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #12061 - /shop/
Cart: #12062 - /cart/
Checkout: #12063 - /checkout/
My account: #12064 - /my-account/
Terms and conditions: #12864 - /terms-and-conditions/

### Theme ###

Name: Ridez Child
Version: 1.0.8
Author URL: 
Child Theme: ✔
Parent Theme Name: Ridez
Parent Theme Version: 1.0.9
Parent Theme Author URL: https://themelexus.com/
WooCommerce Support: ✔

### Templates ###

Overrides: ridez-child/woocommerce/cart/cart-shipping.php version 7.3.0 is out of date. The core version is 8.6.0
ridez-child/woocommerce/cart/cart-totals.php
ridez-child/woocommerce/cart/cart.php
ridez/woocommerce/cart/mini-cart.php
ridez-child/woocommerce/cart/proceed-to-checkout-button.php
ridez-child/woocommerce/cart/shipping-calculator.php
ridez-child/woocommerce/checkout/form-billing.php
ridez-child/woocommerce/checkout/form-checkout.php
ridez-child/woocommerce/checkout/form-coupon.php
ridez-child/woocommerce/checkout/form-login.php
ridez-child/woocommerce/checkout/form-shipping.php
ridez-child/woocommerce/checkout/payment.php
ridez-child/woocommerce/checkout/review-order.php
ridez-child/woocommerce/checkout/thankyou.php
ridez/woocommerce/content-single-product.php
ridez/woocommerce/content-widget-product.php
ridez/woocommerce/content-widget-reviews.php
ridez-child/woocommerce/emails/plain/admin-new-order.php
ridez-child/woocommerce/emails/plain/email-addresses.php
ridez-child/woocommerce/emails/plain/email-order-details.php
ridez/woocommerce/loop/loop-start.php
ridez-child/woocommerce/myaccount/dashboard.php
ridez-child/woocommerce/myaccount/downloads.php
ridez-child/woocommerce/myaccount/form-add-payment-method.php
ridez-child/woocommerce/myaccount/form-edit-account.php
ridez-child/woocommerce/myaccount/form-edit-address.php
ridez-child/woocommerce/myaccount/form-login.php
ridez-child/woocommerce/myaccount/form-lost-password.php
ridez-child/woocommerce/myaccount/form-reset-password.php
ridez-child/woocommerce/myaccount/lost-password-confirmation.php
ridez-child/woocommerce/myaccount/my-account.php
ridez-child/woocommerce/myaccount/my-address.php
ridez-child/woocommerce/myaccount/my-downloads.php
ridez-child/woocommerce/myaccount/my-orders.php
ridez-child/woocommerce/myaccount/navigation.php
ridez-child/woocommerce/myaccount/orders.php version 7.8.0 is out of date. The core version is 8.5.0
ridez-child/woocommerce/myaccount/payment-methods.php
ridez-child/woocommerce/myaccount/view-order.php
ridez/woocommerce/order/form-tracking.php
ridez/woocommerce/product-searchform.php
ridez/woocommerce/single-product/meta.php
ridez/woocommerce/single-product/product-image.php
ridez-child/woocommerce/single-product/rating.php
ridez/woocommerce/single-product/tabs/tabs.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-04 17:19:23 -06:00
Options: ✔
Notes: 202
Onboarding: completed

### Action Scheduler ###

Complete: 322
Oldest: 2024-02-03 03:58:58 +0000
Newest: 2024-03-04 06:56:28 +0000

Failed: 16
Oldest: 2024-02-03 23:07:01 +0000
Newest: 2024-02-13 04:42:50 +0000

Pending: 10
Oldest: 2024-03-04 14:36:43 +0000
Newest: 2024-03-09 05:44:10 +0000

### Status report information ###

Generated at: 2024-03-04 01:41:25 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @jeremyqbutler,

Thanks for your report. Are you able to reproduce this issue using a default WordPress theme or Storefront? If so, are there any other steps that we'd need to take to be able to reproduce this issue?
