### ISSUE TITLE
[Enhancement]: wc_get_orders not support ids or includes parametr

### ISSUE THREAD

**Issue by mehdiraized** [woothemes/woocommerce#45287]
### Describe the solution you'd like

i need to get orders by id but this function wc_get_orders not supported
please add parameter includes to this function for return orders filtred by ids like this
```
$orders = wc_get_orders(array(
  'includes' => array (50, 51),
));
```

**Comment by jorgeatorres** [comment]
Hi @mehdiraized!

Thanks for the report. We implemented a similar approach in the HPOS datastore, where you can use the `id` argument to query only a specific set of orders, just like you want. This is, sadly, an HPOS-only feature and it's not supported in the posts datastore.

In that case, you could use `post__in` instead, though we don't recommend it as it's not a documented feature and might not work correctly on all existing datastores (even post-based ones).

Hope that helps. Ideally you'd be using HPOS now, but if you're still using the posts datastore for backwards compatibility reasons, at least there's a workaround that should do the trick in that case.
