### ISSUE TITLE
Replace attribute dropdown with Gutenberg Combobox component

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#45294]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As part of https://github.com/woocommerce/woocommerce/issues/35851 we need to enable keyboard support to the dropdowns, this has already been largely supported by the Gutenberg Combobox and Formtoken field components.
This issue specifically addresses the replacement of the Attribute/Variation dropdown in the attribute/variation addition modal.

**Acceptance criteria**

- [x] [AttributeInputField](https://github.com/woocommerce/woocommerce/blob/e684ae348b4b3f0a6b09ae2f8478009e0ce9c668/packages/js/product-editor/src/components/attribute-input-field/attribute-input-field.tsx#L149) component should make use of GB ComboboxControl component: https://wordpress.github.io/gutenberg/?path=/docs/components-comboboxcontrol--docs
- [x] Attribute field should work the same way ( only exception being the post fix icon, which is not supported in GB, please create an issue for this in GB ).

## Current issues

```[tasklist]
### UI/UX issues
- [ ] https://github.com/woocommerce/woocommerce/issues/46586
- [ ] https://github.com/woocommerce/woocommerce/issues/46587
- [ ] https://github.com/woocommerce/woocommerce/issues/46590
- [ ] https://github.com/woocommerce/woocommerce/issues/46603
- [ ] https://github.com/woocommerce/woocommerce/issues/46641
- [ ] https://github.com/woocommerce/woocommerce/issues/46712
- [ ] https://github.com/woocommerce/woocommerce/issues/47057
- [ ] https://github.com/woocommerce/woocommerce/issues/47059
```

```[tasklist]
### Enhancements
- [ ] https://github.com/woocommerce/woocommerce/issues/46716
- [ ] https://github.com/woocommerce/woocommerce/issues/46913
- [ ] https://github.com/woocommerce/woocommerce/issues/46954
- [ ] https://github.com/woocommerce/woocommerce/pull/46655
- [ ] https://github.com/woocommerce/woocommerce/pull/47058
- [ ] https://github.com/woocommerce/woocommerce/issues/47263
```

```[tasklist]
### Janitorial
- [ ] https://github.com/woocommerce/woocommerce/issues/46636
- [ ] https://github.com/woocommerce/woocommerce/issues/46908
- [ ] https://github.com/woocommerce/woocommerce/pull/46998
```

```[tasklist]
### Upstream ComboboxControl
- [ ] https://github.com/WordPress/gutenberg/issues/60969
- [ ] https://github.com/WordPress/gutenberg/pull/61705
```

**Comment by retrofox** [comment]
Although there is room to improve and polish the implementation, I think we can close this one.
