### ISSUE TITLE
[Enhancement]: Product Results Count block should be interactive

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#45301]
### Describe the solution you'd like

The `Product Results Count` block isn't powered by Interactivity API, creating a mismatch issue when using the `Product Collection (Beta)` block in the product archives templates in some scenarios:

- Navigating to the next page. 
- Filtering with new filter blocks.

In both cases, the `Product Results Count` still shows the result of the first page.

We should make that block interactive to have the count match with current displayed products.

### Additional context

This is raised by @roykho and @thealexandrelara in testing #43772.

cc @kmanijak @imanish003

**Comment by ObliviousHarmony** [comment]
Hello @dinhtungdu,

Would you be able to provide more information about how to replicate this? I have a collection block paired with the (beta) Price and Attribute filters and the count block updates as expected. I tried this out on the "Products By Category" template as well as the product catalog and had no problems.

**Comment by ObliviousHarmony** [comment]
Ahh @dinhtungdu, it looks like this happens if the "Product Results Count" block is not nested within the collection block. Since it isn't nested, the partial page refresh from the collection block doesn't refresh the content. I'll have to take a look and see if I can figure out a way to make that happen.

**Comment by kmanijak** [comment]
> Ahh @dinhtungdu, it looks like this happens if the "Product Results Count" block is not nested within the collection block. Since it isn't nested, the partial page refresh from the collection block doesn't refresh the content. I'll have to take a look and see if I can figure out a way to make that happen.

@ObliviousHarmony, you were faster in figuring it out 😅 I wanted to give more context: it's going to be a default case in archive templates. We're going to replace Products (Beta) with Product Collection (Beta) in product archive templates soon preserving the current blocks structure. If you clear the customisations in product archive template Product Result Count is placed outside of Products (Beta) and eventually Product Collection block.

**Comment by ObliviousHarmony** [comment]
Sounds good, I'll take a swing at it tomorrow but I think I have an easy solution that's already supported in our version of the interactivity API.
