### ISSUE TITLE
New Attribute Filter: Additional option is selected unexpectedly

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#45300]
This is discovered by @roykho and @thealexandrelara in testing #43772 

Here is the test result by @thealexandrelara 

> #### ⚠️ Test 1: Product Catalog template - Check if the counter is correctly updated when selecting a color attribute
> 
> ```
> Conditions:
> - Filter blocks added to the template
> - Product Collection (Beta) - With Sync with Current Query setting enabled
> - Filter by Attribute (Size) - AND
> - Filter by Attribute (Color) - AND
> ```
> 
> For some reason, the `Red` color is also selected when I select the ` Green` color. If I deselect the Green color, the Active Filters block is correctly updated, but the Filter by Attribute (Color) block still shows the Green color as selected.
> 
> https://github.com/woocommerce/woocommerce/assets/20469356/49a66abe-3220-42eb-8867-09b65e5cbe57

**Comment by samueljseay** [comment]
I can reproduce this and initial investigations point to this being an issue with diffing in interactivity API. Will try investigate this with folks working on that.
