### ISSUE TITLE
[CYS - Core] E2E tests: add coverage for the assember hub

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#45344]
We need to add E2E tests for all the features of the assembler hub:
- [x] fonts @gigitux WIP -> https://github.com/woocommerce/woocommerce/pull/45959
- [x] color @gigitux https://github.com/woocommerce/woocommerce/pull/45926
- [x] footer @albarin  https://github.com/woocommerce/woocommerce/pull/45984
- [x] header @albarin  https://github.com/woocommerce/woocommerce/pull/46011 
- [x] homepage @gigitux https://github.com/woocommerce/woocommerce/pull/46127
- [x] add your logo @gigitux https://github.com/woocommerce/woocommerce/pull/45999
- [x]  color picker -> `Create your own` section -> https://github.com/woocommerce/woocommerce/pull/46337

This task can be divided into smaller issues for each section.

**Comment by gigitux** [comment]
I updated the description of this issue so we can split the tasks if needed. For now, I assigned myself color and fonts

**Comment by gigitux** [comment]
I just realized that we forgot about the `Add your Logo` feature! I updated the description 😁

**Comment by gigitux** [comment]
I added another item to the list: `color picker -> Create your own` section!
