### ISSUE TITLE
Woocommerce REST API reports/orders/totals is not showing correct data when HPOS is enabled

### ISSUE THREAD

**Issue by vanushwashere** [woothemes/woocommerce#45354]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When HPOS is enabled and sync(Compatibility mode) is disabled, the [reports/orders/totals](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-orders-totals) endpoint doesn't show correct information: the newly added orders are not counted here.

Probably because of the using `wp_count_posts()` [here](https://github.com/woocommerce/woocommerce/blob/55c1bec4900137bb69405ae9d714ed5288ae2939/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-report-orders-totals-controller.php#L42)

After running HPOS sync numbers are correct

![image](https://github.com/woocommerce/woocommerce/assets/24995381/c5fdbd7d-18d4-47c2-89d9-fc74fb038bce)
![image](https://github.com/woocommerce/woocommerce/assets/24995381/12cc50a0-6663-48d5-bbc3-d55d6394af4a)
![image](https://github.com/woocommerce/woocommerce/assets/24995381/4ae148b5-5c51-4255-b2cb-39efe4f6f33e)

### Expected behavior

Show correct numbers via the REST API 

### Actual behavior

Orders that are made when HPOS is enabled and sync is disabled are not counted in the REST API orders total report

### Steps to reproduce

1 Make sure that HPOS is enabled and Legacy sync is disabled
2 Make a request to the https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-orders-totals, and fix the numbers 
3 Add an order 
4 Make another call, numbers are not changed

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://sure-marlin.10web.club
Site address (URL): https://sure-marlin.10web.club
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.6
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.34
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 18.12MB
Database Data Size: 11.67MB
Database Index Size: 6.45MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.39MB + Index: 0.52MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.27MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 281
elementor_font: 1
elementor_library: 1
page: 9
post: 3
product: 261
product_variation: 791
revision: 22
shop_order: 19
shop_order_placehold: 1
tww_filter: 3
tww_filter_item: 5
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.15.0
Elementor: by Elementor.com – 3.19.2
10Web Builder: by 10Web – 1.13.13
10Web Booster: by 10Web - Website speed optimization team – 2.27.0
WooCommerce: by Automattic – 8.6.1
WP File Manager: by mndpsingh287 – 7.2.2

### Inactive Plugins (8) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Form Maker Export/Import: by Form Builder Team – 2.1.14
Form Maker Pro: by 10Web Form Builder Team – 2.14.6
Hello Dolly: by Matt Mullenweg – 1.7.2
PG Export/Import: by Photo Gallery Team – 1.1.7
Photo Gallery: by Photo Gallery Team – 2.8.8
Slider by 10Web: by 10Web – 2.2.47
WooCommerce Product Generator: by itthinx – 2.1.0

### Must Use Plugins (1) ###

10WEB: by 10WEB – 1.10.29

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #31 - /shop/
Cart: #32 - /cart/
Checkout: #33 - /checkout/
My account: #34 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Builder Theme
Version: 2.0.16
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-07 14:32:17 +00:00
Options: ✔
Notes: 72
Onboarding: skipped

### Action Scheduler ###

Complete: 1,239
Oldest: 2024-02-26 14:32:21 +0000
Newest: 2024-03-06 15:04:25 +0000

Failed: 2
Oldest: 2024-02-26 14:37:41 +0000
Newest: 2024-02-26 15:21:35 +0000

Pending: 1
Oldest: 2024-03-07 00:37:34 +0000
Newest: 2024-03-07 00:37:34 +0000

### Status report information ###

Generated at: 2024-03-06 15:08:29 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by martinfeuillet** [comment]
same problem here, any update ?

**Comment by tristaningenius** [comment]
I have same issue so all our datas for our accounting is not correct please fix it fast please

**Comment by jshah4517** [comment]
I am finding the /orders endpoint (retrieving all orders) doesn't work with HPOS enabled.

**Comment by jorgeatorres** [comment]
This was addressed in #46715. Feel free to re-open if it's still a problem. Thanks for the report everyone!
