### ISSUE TITLE
Product Filter: Price (Beta) - Invalid Price Range Selection

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#45361]
### Describe the bug

Shoppers can select a maximum price lower than the minimum price (or vice-versa) through both the slider and input fields.

This issue was initially mentioned by @imanish003 in https://github.com/woocommerce/woocommerce/pull/45327#pullrequestreview-1919489433

### Expected behavior

When using the "Product Filter: Price (Beta)" block, the user should only be able to select a valid price range where the minimum price is less than or equal to the maximum price. This applies to both the slider and input field interactions.

### Actual behavior

Currently, shoppers can choose a maximum price value that is lower than the minimum price selected.

### Steps to reproduce

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Product Filter: Price (Beta)" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Click on Save to save the changes.
6. Visit the Shop page (`/shop`).
7. Move the max price to somewhere in the middle of the price slider. Move the min price past the selected max price.
8. Check that this invalid price range is accepted and the products are filtered according to this range.

cc: @dinhtungdu

**Comment by dinhtungdu** [comment]
I remember I covered this case before, not sure why it happens again :/
