### ISSUE TITLE
Product Collection: expose a way to define minimum column width

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#45362]
**Background:**

Product Collection is now responsive which allows for a two-column layout on mobile devices. However the minimum column width is hardcoded and opinionated.

**Goal:**
Provide a programmatic solution to override that value. It could be a PHP filter somewhere, a theme parameter, or something similar.

**Comment by ObliviousHarmony** [comment]
Merging https://github.com/woocommerce/woocommerce/pull/46255 gives us this for free :smile:

**Comment by kmanijak** [comment]
> Merging https://github.com/woocommerce/woocommerce/pull/46255 gives us this for free 😄

Yep! Let's see how https://github.com/woocommerce/woocommerce/discussions/47437 goes!

**Comment by kmanijak** [comment]
Closing this issue as it will be addressed in https://github.com/woocommerce/woocommerce/issues/43307. I'm adding it to the requirements of https://github.com/woocommerce/woocommerce/issues/43307 so we won't forget about it!
