### ISSUE TITLE
Application requesting product "-1" while loading

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#45401]
## Description

While opening any product on the new product editor, the application is wrongfully requesting `/wp-json/wc/v3/products/-1?context=edit&_locale=user`, alongside the correct product id. 

This is a bug and needs to be fixed. This request is not necessary.

Spike #46446

**Comment by octaedro** [comment]
**Aditional information**
- URL -> `/wp-json/wc/v3/products/-1`
- Duration -> 674.815ms
- We set the product ID as `-1` [here](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/product-editor/src/components/editor/editor.tsx#L46).
- We should avoid calling the endpoint with `-1` as the product ID.
