### ISSUE TITLE
Translations to other languages when using Blocks - Cart drawer, Cart page, Checkout (local installations issue)

### ISSUE THREAD

**Issue by MKV-Rob** [woothemes/woocommerce#45438]
### **UPDATE 22. 3. 2024:**
Apparently the issue is present only with local WP installations (XAMPP, WampServer, WP Engine). Once uploaded to testing/production server, translations are being applied correctly. **How do we fix the translations for local installations?**

### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am not able to translate all of the texts in the blocks related to checkout - Cart drawer, Cart and Checkout. There is probably more - I just did not find out yet.

### Expected behavior

Translations of texts should be loaded from .PO/.MO files. Currently it works only partially.

### Actual behavior

Translations of texts are not fully loaded from .PO/.MO files - for some reason lot of texts get ignored and stay in the English language. It is possible to translate some of the texts within the Gutenberg editor but I don't think it is ideal.

![translation_checkout](https://github.com/woocommerce/woocommerce/assets/21360633/f53e6b65-6da7-46f5-a531-5567c1c9cff9)

### For example:
**Field label/placeholder "Email address" gets translated properly.** Text is placed for example here: _\plugins\woocommerce\src\Blocks\Domain\Services\CheckoutFields.php_

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/eeb2ae69-b844-40e5-b8e7-841a6fdd45d7)

**Button/link "Add a coupon" does not get translated properly.** Translation is present in the .PO/.MO file but does not get applied. Original text is placed for example here: _\plugins\woocommerce\assets\client\blocks\checkout.js_

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/09800a5a-eb3c-4684-b39f-21e9bb49eee7)

### Steps to reproduce

1. Use non-english WooCommerce and have localization .PO/.MO files in the _/languages/plugins/_ folder.
2. Use WC Block for Cart Drawer/Cart/Checkout.
3. Check translations - only some texts are translated.

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): http://localhost/shop
Site address (URL): http://localhost/shop
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.2.0
PHP Version: 8.2.0
PHP Post Max Size: 1 GB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.7

SUHOSIN Installed: –
MySQL Version: 10.4.27-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Váš server nemá povolenou SoapClient třídu - některé platební brány
které používají SOAP
nebudou možná fungovat.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Celková velikost databáze: 7.62MB
Velikost dat databáze: 5.09MB
Velikost indexu databáze: 2.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_db7_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 22
acf-field-group: 2
attachment: 9
customize_changeset: 1
nav_menu_item: 36
page: 14
post: 2
product: 1
revision: 22
shop_order_placehold: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 2
wp_template_part: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
Váš obchod nepoužívá HTTPS. Zjistěte více o HTTPS a SSL certifikátech.
Hide errors from visitors: ❌Chybová hlášení by neměla být zobrazována návštěvníkům.

### Active Plugins (17) ###

Advanced Custom Fields PRO: Autor: WP Engine – 6.2.7
Klasický editor: Autor: WordPress Contributors – 1.6.3
Contact Form 7: Autor: Takayuki Miyoshi – 5.9
Contact Form CFDB7: Autor: Arshid – 1.2.6.8
Custom Upload Dir: Autor: Ulf Benjaminsson – 3.4.6
Duplikovat stránku: Autor: mndpsingh287 – 4.5.3
Easy WP SMTP: Autor: Easy WP SMTP – 2.2.0
Enable Media Replace: Autor: ShortPixel – 4.1.5
Images to WebP: Autor: KubiQ – 4.6
Regenerate Thumbnails: Autor: Alex Mills (Viper007Bond) – 3.1.6
SVG Podpora: Autor: Benbodhi – 2.5.5
Editor uživatelských rolí: Autor: Vladimir Garagulya – 4.64.2
WooCommerce Doprava a Daně: Autor: WooCommerce – 2.5.2
WooCommerce: Autor: Automattic – 8.6.1
Yoast SEO: Autor: Tým Yoast – 22.2
WP Migrate Lite: Autor: WP Engine – 2.6.10
WPS Hide Login: Autor: WPServeur
NicolasKulka
wpformation – 1.9.13.2


### Inactive Plugins (1) ###

WP Fastest Cache: Autor: Emre Vona – 1.2.3

### Must Use Plugins (1) ###

WP Migrate Lite Compatibility: Autor: Delicious Brains – 1.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Obchod: #8 - /produkty/
Košík: #9 - /kosik/
Pokladna: #10 - /pokladna/
Můj účet: #11 - /muj-ucet/
Obchodní podmínky: #23 - /obchodni-podminky/

### Theme ###

Name: E-shop
Version: 1.0
Author URL: 
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Overrides: 2k24/woocommerce/archive-product.php
2k24/woocommerce/checkout\form-verify-email.php
2k24/woocommerce/checkout\order-receipt.php
2k24/woocommerce/checkout\order-received.php
2k24/woocommerce/checkout\thankyou.php
2k24/woocommerce/content-product-cat.php
2k24/woocommerce/content-product.php
2k24/woocommerce/content-single-product.php
2k24/woocommerce/emails\email-header.php
2k24/woocommerce/global\breadcrumb.php
2k24/woocommerce/global\form-login.php
2k24/woocommerce/global\wrapper-end.php
2k24/woocommerce/global\wrapper-start.php
2k24/woocommerce/loop\add-to-cart.php
2k24/woocommerce/loop\loop-end.php
2k24/woocommerce/loop\loop-start.php
2k24/woocommerce/loop\no-products-found.php
2k24/woocommerce/loop\orderby.php
2k24/woocommerce/loop\pagination.php
2k24/woocommerce/loop\price.php
2k24/woocommerce/loop\rating.php
2k24/woocommerce/loop\result-count.php
2k24/woocommerce/loop\sale-flash.php
2k24/woocommerce/order\order-details-item.php
2k24/woocommerce/order\order-details.php
2k24/woocommerce/single-product\add-to-cart\external.php
2k24/woocommerce/single-product\add-to-cart\grouped.php
2k24/woocommerce/single-product\add-to-cart\simple.php
2k24/woocommerce/single-product\add-to-cart\variable.php
2k24/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
2k24/woocommerce/single-product\add-to-cart\variation.php
2k24/woocommerce/single-product\meta.php
2k24/woocommerce/single-product\photoswipe.php
2k24/woocommerce/single-product\price.php
2k24/woocommerce/single-product\product-attributes.php
2k24/woocommerce/single-product\product-image.php
2k24/woocommerce/single-product\product-thumbnails.php
2k24/woocommerce/single-product\rating.php
2k24/woocommerce/single-product\related.php
2k24/woocommerce/single-product\review-meta.php
2k24/woocommerce/single-product\review-rating.php
2k24/woocommerce/single-product\review.php
2k24/woocommerce/single-product\sale-flash.php
2k24/woocommerce/single-product\share.php
2k24/woocommerce/single-product\short-description.php
2k24/woocommerce/single-product\stock.php
2k24/woocommerce/single-product\tabs\additional-information.php
2k24/woocommerce/single-product\tabs\description.php
2k24/woocommerce/single-product\tabs\tabs.php
2k24/woocommerce/single-product\title.php
2k24/woocommerce/single-product\up-sells.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-09 11:05:14 +01:00
Options: ✔
Notes: 73
Onboarding: -

### Action Scheduler ###

Dokončeno: 47
Oldest: 2024-02-21 12:07:18 +0100
Newest: 2024-03-08 14:59:07 +0100

Selhalo: 1
Oldest: 2024-03-07 18:42:07 +0100
Newest: 2024-03-07 18:42:07 +0100

Čekající: 3
Oldest: 2024-03-08 14:59:26 +0100
Newest: 2024-03-09 13:30:07 +0100


### Status report information ###

Generated at: 2024-03-08 15:00:11 +01:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @MKV-Rob, thanks for reaching out.

To rule out saved template content, can you navigate to `Appearance` > `Editor` > `Templates` > `Manage All Templates` and make sure there is no saved content? If there is, can you please try reset the templates and post results?

Not saying that translations shouldn't occur on saved content, but I'm having a bit of trouble replicating this. Having this information would make the next steps clearer. Thank you

**Comment by MKV-Rob** [comment]
**Hello @wavvves **,

thanks for getting to me! I had some changes but only regarding what fields to show and whatnot. I reverted it and the issue still persists.

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/3cee1d5e-e2cc-4848-a571-e8f37cec30c8)

Please give me couple of days, I am gonna do more of a testing - I will try completely clean install WP + WC only and so on. Then I will report again.

**Comment by senadir** [comment]
Hey @MKV-Rob 

I assume you're editing the PO/MO files and looking to see results? this won't work most parts of Cart/Checkout because their translation is loaded from a JSON file.

So you need to either:
- Generate the JSON files from a PO/MO file using [`make-json`](https://developer.wordpress.org/cli/commands/i18n/make-json/) command.
- Use a translation plugin that supports JSON files, like LOCO Translate.

**Comment by MKV-Rob** [comment]
Hello @senadir!

so I have tried LOCO Translate to regenerate language JSON files but no luck. All files are inside "/languages/plugins/" but not all of the translations are being applied.

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/0f7f7f7b-e0ba-4304-823e-9949e7434a85)

Tomorrow I will test further. Thanks for your time!

**Comment by MKV-Rob** [comment]
**Hello @wavvves & @senadir**,

so I have tested clean install of Wordpress without any modifications/customizations on local XAMPP server _(the system report is in the main post above)_. Only Wordpress + latest WooCommerce but not all translations are present. 

**Then** I have added plugin Loco Translate to check if the translations are present + to update JSON files and again - not all translations are applied:

![translations-not-applied](https://github.com/woocommerce/woocommerce/assets/21360633/685202f6-686b-4046-9e6a-c966adf5eef8)

![translations-not-complete](https://github.com/woocommerce/woocommerce/assets/21360633/dc136c11-cef0-40c5-9071-d7ffdd48d560)

**Afterwards** I tried to upload the clean installation on production server and the translations are being applied correctly - hooray!

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/1941827f-b33f-4ac2-a237-846fc3e16219)

...but why?

**There is something wrong with the local installations but I have no clue what it is. Do you have any ideas?**

**Comment by FlorentNL** [comment]
I'm facing the same issue (french translations this time) on my local installation using Local by wp engine.

**Comment by GuillaumeChatelain** [comment]
I had the exact same problem (in french) and thanks to you i could resolve it.
It was a local installation problem. When put the website on my server every block translations works fine.
(I was using Wampserver to run my local installation).

There is something wrong with the local installations but I have no clue what it is either.
Anyway thanks for posting this solution!

**Comment by MKV-Rob** [comment]
Apparently the issue is present only with local WP installations (XAMPP, WampServer, WP Engine). Once uploaded to testing/production server, translations are being applied correctly. How do we fix the translations for local installations?

**Comment by opr** [comment]
Hey folks, one other thing I would like to ask is if you can try deleting all transients [Transients Manager](https://en-gb.wordpress.org/plugins/transients-manager/) and seeing if this works. We store script data in a transient, so I'm wondering if the translations are not loading due to a cache issue, though I find it unlikely since you mentioned you set up fresh sites.

Can you also check and confirm you went to Dashboard -> Updates and click the `Update translations` button?

**Comment by FlorentNL** [comment]
Hello @opr! Thanks for your reply. I've tried deleting all transients without success. Also, translations are up-to-date, the button doesn't show up.

**Comment by MKV-Rob** [comment]
@opr Hi,

I have tried to delete transients, template cache of WC etc. before posting this issue. Could have mentioned that - sorry.

**Comment by nielslange** [comment]
Hello @MKV-Rob,

Thanks for letting us know that you deleted the transients, the template cache, etc. already. I just looked up this issue, and I could not spot any missing translations on my end.

<table>
<tr>
<td valign="top">Empty Mini-Cart block:
<br><br>
<img width="480" alt="Screenshot 2024-04-02 at 19 48 18" src="https://github.com/woocommerce/woocommerce/assets/3323310/4207bbbf-005d-47a2-ae7b-20804c4d9147">
</td>
<td valign="top">Filled Mini-Cart block:
<br><br>
<img width="480" alt="Screenshot 2024-04-02 at 19 40 48" src="https://github.com/woocommerce/woocommerce/assets/3323310/64882425-f9e2-40c2-a26c-85daf2ea8add">
</td>
</tr>
</table>

> [!NOTE]
> The strings `Beanie with Logo` and `This is a simple product.` are coming directly from the product. 

Looking at the cart and the checkout page, I cannot see any missing translations, apart from the product data, which had been created in English:

<table>
<tr>
<td valign="top">Cart block:
<br><br>
<img width="1280" alt="Screenshot 2024-04-02 at 19 43 45" src="https://github.com/woocommerce/woocommerce/assets/3323310/97a2d698-2e39-4b18-aa39-bf04873de33b">
</td>
<td valign="top">Checkout block:
<br><br>
<img width="1283" alt="Screenshot 2024-04-02 at 19 43 57" src="https://github.com/woocommerce/woocommerce/assets/3323310/ead9f2d8-2402-454f-9743-f609e688eb30">
</td>
</tr>
</table>

Here are the steps I've taken to see these results:

1. Go to `/wp-admin/options-general.php`.
2. Select `čeština` as the site language.
3. Go to `/wp-admin/update-core.php?force-check=1`.
4. Click on `Aktualizovat překlady` to fetch the translation pack.
5. Delete the Cart and Checkout blocks and re-add them.

Would you mind repeating these steps on your end and share the screenshots of what you are seeing then?

**Comment by MKV-Rob** [comment]
**Hello @nielslange**,

thanks for getting back to us! :-) Did you test it on the local server? I have tried to reproduce your steps:

**1-2.** Language is Čeština:
![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/0b5cb2b8-623e-465a-9e6e-dcdc4e086711)

**3-4.** It says all my translations are up to date:
![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/d4dbf900-fe0b-405f-a042-489a48c7b923)

**5.** I have tried to delete Cart block on the Cart page and add it again. I can see the Czech translations in the admin but not on front-end. It is weird.

![obrazek](https://github.com/woocommerce/woocommerce/assets/21360633/7672214f-556b-4045-80fc-d91c513c816b)

Then again - translations work fine on the online server.

**Comment by nielslange** [comment]
> thanks for getting back to us! :-) Did you test it on the local server? I have tried to reproduce your steps:

I did try it locally using [Laravel Valet](https://github.com/laravel/valet) and on my end, it works as expected.

>  I have tried to delete Cart block on the Cart page and add it again. I can see the Czech translations in the admin but not on front-end. It is weird.

@senadir Do you have an explanation why some translations are visible on the backend, but not on the frontend and only when using certain local environments such as XAMPP? I do not see this issue locally when using Laravel Valet.

**Comment by senadir** [comment]
I don't really know, it's most likely a path/cache issue, we know it exists, but we can't fully reproduce it.

Has anyone tried with:

`WP_DEBUG` enabled and disabled
`SCRIPT_DEBUG` enabled and disabled

**Comment by nielslange** [comment]
Thanks for sharing these suggestions, @senadir.

**Comment by MKV-Rob** [comment]
@senadir Have tried disabling/enabling local debugging and no change. In the admin translations work - on front end it does not.

Caching disabled locally so it should now be an issue?

I was thinking it might be pathing issue as well. Is there a way how to print out translation paths on front-end so I can compare live server vs. local?

**Comment by wavvves** [comment]
Hi @MKV-Rob, can you please delete the Cart/Checkout pages, reset `Page: Cart` and `Page: Checkout` template modifications, and recreate the Cart and Checkout pages via `WooCommerce` > `Status` > `Tools` > `Create Pages` locally? To rule out any related problem on your dev environment.
Another thing, do you have any build process that might interfere with this? Or maybe something different on during the deployment process?

You can output the PHP constant `WP_LANG_DIR` to check the path of loaded translations.

**Comment by MKV-Rob** [comment]
**Hello @wavvves**,

so I have followed these steps:

1. Activated Full Site Editor and reseted all customizations on Cart/Checkout page.
2. Deleted these pages completely.
3. Re-created these pages via _WooCommerce > Status > Tools > Create Pages_

And tanslations are still incomplete.

I have also tried to delete all WC translations with Loco Translate and re-create it with the "_Dashboard -> Updates -> Update translations_". No change.

Then I have tried to delete translations again and re-import .PO file with Loco Translate to _Languages > Loco > Plugins_ folder. No change either.

> Another thing, do you have any build process that might interfere with this? Or maybe something different on during the deployment process?

Only thing that I can think of is that I am using custom folder paths:

_define( 'WP_CONTENT_FOLDERNAME', 'data');
define( 'WP_CONTENT_DIR', ABSPATH . 'data');
define( 'WP_CONTENT_URL', WP_SITEURL . WP_CONTENT_FOLDERNAME );
define( 'UPLOADS', WP_CONTENT_FOLDERNAME . '/files' );_

**But then again** - translations work on the live server + the issue was present on completely fresh and vanilla WP + WC installation.

It must be something related to XAMPP/Wamp server/WP Engine - maybe PHP settings or something. I will try to compare PHP settings between local and live server when I find a moment.

**Comment by nielslange** [comment]
> It must be something related to XAMPP/Wamp server/WP Engine - maybe PHP settings or something. I will try to compare PHP settings between local and live server when I find a moment.

@MKV-Rob That would be great if you could share your findings, as I'm unable to reproduce this issue in my local environment using Laravel Valet.

**Comment by MKV-Rob** [comment]
**Hi @nielslange**,

I was trying to pinpoint where the difference _(that causes the translations to be not fully working locally)_ between production and XAMPP server might be -- and so far no luck.

Can you think of specific WooCommerce/Wordpress PHP/Apache/MySQL related settings/modules/extensions that are required to make website 100% functional?

**Comment by nielslange** [comment]
> Can you think of specific WooCommerce/Wordpress PHP/Apache/MySQL related settings/modules/extensions that are required to make website 100% functional?

@MKV-Rob Apologise for my delayed response. In https://github.com/woocommerce/woocommerce/issues/45438#issuecomment-2051943622, you mentioned that you are using custom paths. Could you run a test with the default WordPress paths to see if the translation issues are caused by that?

**Comment by MKV-Rob** [comment]
**Hello @nielslange**,

please see the https://github.com/woocommerce/woocommerce/issues/45438#issuecomment-2013124319 - I have tested even the clean install of WP + WC without any extensions/modifications and the issue was the same.

**Comment by nielslange** [comment]
@MKV-Rob In that case, I'm afraid I'm running out of ideas and as I'm unable to reproduce this issue in my local environment, it's hard to say what's causing this. Maybe someone else has a good idea of what this issue might be causing.

**Comment by MKV-Rob** [comment]
@nielslange - is there a chance that you would try to use XAMPP, WampServer or WP Engine to replicate the problem? You might be able to figure something out?

**Comment by nielslange** [comment]
I'm afraid not, @MKV-Rob, as I've carefully set up my local environment. Installing a different local environment might have a negative impact on my local environment. Apart from that, I'm running macOS and cannot install XAMPP or WampServer.

**Comment by senadir** [comment]
@MKV-Rob When you say WP Engine, you mean [Local](https://localwp.com/)?

**Comment by senadir** [comment]
Thank you for the report, we managed to reproduce and issued a fix here https://github.com/woocommerce/woocommerce/pull/47625

**Comment by ralucaStan** [comment]
Congrats on getting to the bottom of this @senadir !

**Comment by MKV-Rob** [comment]
**Hi,**

sorry for responding late.

@senadir - I think so - yes - @FlorentNL said "Local by wp engine". Good job on reproducing and fixing this issue. 

Thank you!

**Comment by baselvadmin** [comment]
Yesterday lost 4 hours debugging this issue. Backend shows translated version, but frontend does not.

So for me the issue was minifying javascript in my optimization plugin. As soon as I disabled this option translation works!

Hope this saves someones nerves.
