### ISSUE TITLE
Cart-token header cannot be used along request GET /wp-json/wc/store/v1/cart

### ISSUE THREAD

**Issue by zuryx** [woothemes/woocommerce#45457]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I want to achieve the functionality described here: https://github.com/woocommerce/woocommerce-blocks/pull/5953 but sadly I'm getting the getting same error: "Call to undefined method Automattic\WooCommerce\StoreApi\SessionHandler::get_session_cookie()"
when I'm trying to call GET /wp-json/wc/store/v1/cart endpoint with a Cart-Token header

The error I'm getting has been already reported here https://github.com/woocommerce/woocommerce-blocks/pull/9163 but was closed at that time.

 @wavvves I would like to know if there is hope to get a fix for this issue soon. I really feel that the Store API must provide a way to query any Cart by token

### Expected behavior

I would like to be able to call GET endpoint " /wp-json/wc/store/v1/cart" along with Cart-Token header in order to get any cart.

### Actual behavior

I got the following response:

![image](https://github.com/woocommerce/woocommerce/assets/20054168/cd717184-cd8d-494c-ba5a-ffdda5b72045)

and the following error in the WP logs:

Uncaught Error: Call to undefined method Automattic\WooCommerce\StoreApi\SessionHandler::get_session_cookie()

[fatal-errors-2024-03-08.log](https://github.com/woocommerce/woocommerce/files/14541832/fatal-errors-2024-03-08.log)

### Steps to reproduce

1. Call endpoint GET wp-json/wc/store/v1/cart to get a new cart token, extract the value from Cart-Token header
3. Clean session/cookies
4. Call again endpoint GET wp-json/wc/store/v1/cart to get another Cart-Token
5. Call endpoint GET wp-json/wc/store/v1/cart including Cart-Token header and switching between both Card tokens
6. Error happens

Note: I make sure that no cookies were stored on my client (Postman), I always used a clean session

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://store.stokkur.is
Site address (URL): https://store.stokkur.is
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 13.87MB
Database Data Size: 8.18MB
Database Index Size: 5.69MB
wp_woocommerce_sessions: Data: 0.27MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_cocart_carts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_dropp_consignments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mstore_checkout: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.09MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_posts: Data: 1.17MB + Index: 0.09MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_en_gb_en_us: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_dictionary_en_gb_is_is: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_en_gb: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 0.19MB + Index: 0.25MB + Engine InnoDB
wp_trp_gettext_is_is: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 0.42MB + Index: 0.30MB + Engine InnoDB
wp_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 62
jetpack_migration: 2
jp_img_sitemap: 7
jp_sitemap: 7
jp_sitemap_master: 7
language_switcher: 4
nav_menu_item: 9
page: 13
post: 3
product: 15
product_variation: 10
revision: 27
shop_coupon: 1
shop_order: 249
wp_global_styles: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
CoCart API - Decoupling WooCommerce Made Easy: by CoCart Headless
LLC – 3.11.2

CoBlocks: by GoDaddy – 3.1.6
Crowdsignal Forms: by Automattic – 1.7.0
Dropp for WooCommerce: by Cove AS – 2.1.1
Filester - File Manager Pro: by Ninja Team – 1.8.2
WordPress.com Editing Toolkit: by Automattic – 4.15561
Google Listings and Ads: by WooCommerce – 2.6.1
Gutenberg: by Gutenberg Team – 17.8.2
Jetpack: by Automattic – 13.2-beta
Layout Grid: by Automattic – 1.8.4
MStore API: by InspireUI – 4.11.9
WP Options Importer: by Matthew Boynes – 7
Page Optimize: by Automattic – 0.5.5
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Pósturinn's Shipping with WooCommerce: by Pósturinn – 1.1.7
Simple-JWT-Login: by Nicu Micle – 3.5.3
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.7.3

Payment Gateway via ValitorPay for WooCommerce: by Tactica – 1.2.16
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.30
WooCommerce: by Automattic – 8.6.1
WP Crontrol: by John Blackbourn & crontributors – 1.16.1

### Inactive Plugins (5) ###

Avalara AvaTax: by Avalara – 2.7.0 (update to version 2.7.1 is available)
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.3
Classic Editor: by WordPress Contributors – 1.6.3
WooCommerce Payments: by Automattic – 6.2.1 (update to version 7.3.0 is available)
WooCommerce PayPal Payments: by WooCommerce – 2.5.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ISK (kr.)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #39 - /checkout/
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hever
Version: 1.5.28
Author URL: https://automattic.com/
Child Theme: ✔
Parent Theme Name: Varia
Parent Theme Version: 1.6.30
Parent Theme Author URL: https://automattic.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-09 03:01:37 +00:00
Options: ✔
Notes: 160
Onboarding: completed

### Action Scheduler ###

Complete: 277
Oldest: 2024-02-06 23:49:44 +0000
Newest: 2024-03-08 15:55:50 +0000

Failed: 24
Oldest: 2023-02-20 16:25:55 +0000
Newest: 2024-03-08 16:22:35 +0000

Pending: 4
Oldest: 2024-03-09 15:55:50 +0000
Newest: 2024-03-09 17:32:28 +0000

### CoCart ###

Version: 3.11.2
Database Version: 3.11.2
Install Date: February 8
2024

Carts in Session: 6
Carts Active: 4 out of 6 in session.
Carts Expiring Soon: 0 out of 6 in session.
Carts Expired: 2 out of 6 in session.
Carts Source (by CoCart): 0
Carts Source (by Web): 0
Carts Source (by Other): 6

### Status report information ###

Generated at: 2024-03-08 18:43:25 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @zuryx, thanks for reaching out. We are [still aware of that issue](https://github.com/woocommerce/woocommerce/discussions/44947), it was closed since we moved now to this repo and are not using the woocommerce-blocks repo anymore.

Nevertheless, what you are trying to achieve should work, I have replicated the flow with no problems. I know really disabling cookies on Postman is tricky, can you please try again just sending the Cart-Token header and disabling the other ones, and specially, disabling the Cookie Jar for the requests:



![Image](https://github.com/woocommerce/woocommerce/assets/17236129/16f2da98-3dea-47a0-8218-dc2f725b7862)
