### ISSUE TITLE
[Enhancement]: update Dependency Extraction Webpack Plugin for Node 20

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#45456]
### Describe the solution you'd like

Update the required node version engine. GitHub actions is deprecating Node 16 so to run this as part of a deploy action it will need to update the Node to 20. 

### Describe alternatives you've considered

n/a

**Comment by rrennick** [comment]
@helgatheviking Thanks for reporting the issue. It was reported earlier in #43034. Closing this as a duplicate.
