### ISSUE TITLE
Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void

### ISSUE THREAD

**Issue by johanmolen** [woothemes/woocommerce#45465]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Im getting the following error when using a newer version of `psr/log` (3.0.0) in my WordPress theme as the one used in this plugin.

```
Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = [])
```

I wonder why `psr/log` is not prefixed in this plugin.

### Expected behavior

The possibility to use this version of `psr/log`

### Actual behavior

A 500 error 

### Steps to reproduce

1.  Install `psr/log` 3.0.0  and load it
2.  Refresh the WooCommerce admin page and watch the error log

### WordPress Environment ###

WordPress address (URL): http://test.nl.test/wp
Site address (URL): http://test.nl.test
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.25.4
PHP Version: 8.3.3
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.6.0
(SecureTransport) OpenSSL/3.2.1

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Totale database grootte: 6.59MB
Database gegevens grootte: 4.51MB
Database index grootte: 2.08MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_posts: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
nav_menu_item: 32
page: 14
post: 2
revision: 55

### Security ###

Secure connection (HTTPS): ❌
					Je winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (14) ###

Query Monitor: door John Blackbourn – 3.15.0
Advanced Custom Fields: Editor Palette Field: door Brandon Nifong – 1.1.6
Advanced Custom Fields PRO: door WP Engine – 6.2.7
Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: door Usercentrics A/S – 4.3.7.1
Site Kit by Google: door Google – 1.121.0
Index WP MySQL For Speed: door Oliver Jones
Rick James – 1.4.15

MailerSend - Official SMTP Integration: door MailerSend – 1.0.3
MailerSend - Transactional emails for WooCommerce: door MailerSend – 1.2.3
Mollie Payments for WooCommerce: door Mollie – 7.5.1
Redis Object Cache: door Till Krüss – 2.5.1
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.7.7
WooCommerce: door Automattic – 8.6.1
WordPress Sentry: door Alex Bouma – 7.9.0
Stage Switcher: door Roots – 2.2.0

### Inactive Plugins (1) ###

Yoast SEO: door Team Yoast – 22.2

### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (3) ###

00-acorn-boot.php: door  –
Bedrock Autoloader: door Roots – 1.0.3
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: door  – 1.4.15

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Winkelbasis: #7 - /shop/
Winkelwagen: #8 - /cart/
Afrekenen: #9 - /checkout/
Mijn account: #10 - /my-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

WooCommerce Support: ❌ Niet aangegeven

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-10 15:30:21 +00:00
Options: ✔
Notes: 71
Onboarding: -

### Action Scheduler ###

Afgerond: 35
Oldest: 2024-02-08 13:00:00 +0000
Newest: 2024-03-09 17:03:56 +0000

In afwachting: 4
Oldest: 2024-03-10 16:43:20 +0000
Newest: 2024-03-11 14:03:45 +0000

Mislukt: 22
Oldest: 2024-02-12 14:00:14 +0000
Newest: 2024-03-09 16:43:20 +0000

### Status report information ###

Generated at: 2024-03-09 17:03:58 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
We do prefix the dependency via mozart, so, interestingly, this is still happening. We will need to investigate where this is being loaded from, maybe it's dependency of an dependency that is not prefixed.

**Comment by barryhughes** [comment]
@vedanshujain do we use `psr/log` or `monolog/monolog`? I don't see either listed anywhere, and neither come up if I run `composer show` (I also cannot replicate the problem, so am wondering if this is valid). Could easily be missing something, though, so wanted to check-in first 🤔

**Comment by johanmolen** [comment]
Im closing this issue, the issue was related to a combination of WooCommerce and WooCommerce Mollie. But in the end it is caused by Mollie. Sorry for the inconvenience.

**Comment by barryhughes** [comment]
No problem (and thank you for taking the time to check back in).
