### ISSUE TITLE
[DOC-BUG] Explain how to trigger cart update using react/store

### ISSUE THREAD

**Issue by dingo-d** [woothemes/woocommerce#45469]
## Description of the Suggestion

I recently started to go through the docs about [slot fills](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/slot-fills.md), [available slot fills](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-slot-fills.md) and [cart store](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/cart.md) in order to add my own plugin to the cart page.

And while I've kinda gotten around adding what I needed there are few things that are missing.

In terms of features, there needs to be more slots. Just having `ExperimentalOrderMeta` is not enough. We need a slot for above the cart totals, below, etc. Basically what we had with classic PHP template filters.

In terms of documentation: more concrete examples of how to modify the behavior using the store.

Currently I'm trying to trigger cart update (like what happens when I click to add more product, or remove it) from my plugin.
I am trying the code from the cart data store

```js
const { dispatch } = useDispatch( CART_STORE_KEY );
dispatch( receiveCartContents( newCartContents ) );
```

But I keep getting `ReferenceError: receiveCartContents is not defined` in my console, and I don't know what I'm doing wrong. There is no real documentation about using this, so that would be amazing to add.

**Comment by opr** [comment]
Hi there @dingo-d, thanks for the feedback about slot fills. We're aware of this and are investigating the block hooks API to see if it can help us. We'll open public discussions and post on the blog post when we have more to share on that.

Please take a look at the [`extensionCartUpdate`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md) documentation, it seems like this is a good solution to the problem you're facing.

Side note, it also looks like you aren't using `useDispatch` correctly [(`useDispatch` docs)](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#usedispatch)) as the code example you provided seems wrong, it would be more like this but I'd recommend checking out `extensionCartUpdate` first.

```js
const { receiveCartContents } = useDispatch( CART_STORE_KEY );
receiveCartContents( newCartContents );
```

I'll close this issue as I don't believe there's anything actionable for now but please reopen it if you have anything new to add!

Many thanks.

**Comment by dingo-d** [comment]
Thanks for the explanation, I'm looking forward to the updated docs. I'll try to use the suggested code for reacting to store change 👍🏼
