### ISSUE TITLE
WooCommerce Blocks: Notifications with the same type stack up as the list inside the same element

### ISSUE THREAD

**Issue by agung2001** [woothemes/woocommerce#45472]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we create a notification with the same type in WooCommerce blocks it'll stack up as a list instead of creating a new element. You can see the screenshot : 
![Screenshot 2024-03-11 at 08 51 16](https://github.com/woocommerce/woocommerce/assets/4479106/d3ebfa13-2ca4-4bc2-bf26-2e4b9525db8a)

### Expected behavior

We expect that the notification with the same type will have a different element, this is due to if it stacks together we can't put an HTML element into it. there are some cases where we want to modify the notification by adding HTML elements to it such as adding buttons, links, etc.

### Actual behavior

currently, the notification is stacked up together as a list

### Steps to reproduce

1. Create a new Cart / Checkout block page
2. Go to the newly created page
3. Open your dev console
4. Run this command to create the first notification
```javascript
wp.data.dispatch('core/notices').createSuccessNotice( 'This is a success message, it should show in green!', { context: 'wc/cart' } )
```
5. Run this command to create the second notification
```javascript
wp.data.dispatch('core/notices').createSuccessNotice( 'This is a success message, it should show in green 2!', { context: 'wc/cart' } )
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://acfwp.local
Site address (URL): http://acfwp.local
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1
WC Database Prefix: wp_
Total Database Size: 507.83MB
Database Data Size: 492.38MB
Database Index Size: 15.45MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 24.55MB + Index: 9.94MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_gift_cards: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_loyalprog_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_acfw_virtual_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_fields: Data: 0.02MB + Index: 0.22MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_broadcast: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_bulk_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_contact_note: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_conversions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_engagement_tracking: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_bwfan_engagement_trackingmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_field_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_fields: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_form_feeds: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_import_export: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_link_triggers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_message: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bwfan_templates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cfw_acr_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fk_cart_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 459.03MB + Index: 0.25MB + Engine InnoDB
wp_postmeta: Data: 1.31MB + Index: 0.36MB + Engine InnoDB
wp_posts: Data: 0.25MB + Index: 0.06MB + Engine InnoDB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rs_expiredpoints_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rs_templates_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsgiftvoucher: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rspointexpiry: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsrecordpoints: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sumo_reward_encashing_submitted_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sumo_reward_send_point_submitted_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uap_action_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_action_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_api_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uap_api_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_closure_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uap_closure_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_uap_trigger_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_trigger_log_meta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
wp_usermeta: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
coupon_template: 2
elementor_library: 1
nav_menu_item: 4
order_form: 1
page: 24
post: 14
product: 43
product_variation: 20
revision: 37
shop_coupon: 39
shop_order: 46
shop_order_refund: 9
wfacp_checkout: 1
wffn_ty: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (47) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.9.2
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 3.5.8.1
Advanced Gift Cards for WooCommerce: by Rymera Web Co – 1.3.6
Aelia Currency Switcher for WooCommerce: by Aelia – 4.13.12.220704
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.15.230905
Aelia Prices by Country for WooCommerce: by Aelia – 1.12.9.220124
CheckoutWC: by Objectiv – 8.2.14
CheckoutWC Lite: by CheckoutWC – 1.1.4
Cypress Helper Plugin: by Rymera QAs – 1.1.0
Elementor: by Elementor.com – 3.15.3
FakerPress: by Gustavo Bordoni – 0.6.1
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.1.7
FunnelKit Automations: by FunnelKit – 2.5.1
FunnelKit Automations Pro: by FunnelKit – 2.5.0
FunnelKit Cart for WooCommerce: by FunnelKit – 1.1.0
FunnelKit Funnel Builder: by FunnelKit – 2.12.0
FunnelKit Funnel Builder Pro: by FunnelKit – 2.12.0
Gutenberg: by Gutenberg Team – 17.6.0
Invoice Gateway For WooCommerce: by Rymera Web Co – 1.1.1
JSON Help Content Editor: by Rymera Web Co – 1.1.0
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.0.5

Loyalty Program for WooCommerce: by Rymera Web Co – 1.8.5
My Extension Name: by The WordPress Contributors – 0.1.0
Ocean Extra: by OceanWP – 2.1.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.3.2
Rymera WooCommerce Block Test Plugin: by Agung Sundoro – 0.0.1
Rymera WooCommerce Product Editor Test Plugin: by Agung Sundoro – 0.0.1
Shipping Workshop: by Thomas Roberts and Niels Lange – 1.0
Stripe Payment Gateway for WooCommerce: by FunnelKit – 1.4.1
SUMO Reward Points: by Fantastic Plugins – 28.9.0
Uncanny Automator: by Uncanny Automator
Uncanny Owl – 4.14.0.1

WC Vendors Marketplace: by WC Vendors – 2.4.6
WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free ): by WebToffee – 1.7.8
Woocommerce Blocks Test Extended: by The WordPress Contributors – 0.1.0
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.2.0
WooCommerce Points and Rewards: by WooCommerce – 1.7.32
WooCommerce Subscriptions: by WooCommerce – 4.8.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.17.1
WooCommerce Wholesale Order Form: by Rymera Web Co – 2.1.1.1
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.11.2
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.30.1
WP Mail Logging: by SendLayer – 1.10.5
WPML Media: by OnTheGoSystems – 2.7.1
WPML Multilingual CMS: by OnTheGoSystems – 4.5.13
WPML String Translation: by OnTheGoSystems – 3.2.3
YITH WooCommerce Points and Rewards Premium: by YITH – 3.23.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: advanced_gift_card (advanced_gift_card)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-11 23:41:37 +07:00
Options: ✔
Notes: 133
Onboarding: skipped

### Action Scheduler ###

Complete: 183
Oldest: 2024-02-12 14:52:55 +0700
Newest: 2024-03-11 08:40:27 +0700

Pending: 5
Oldest: 2024-03-11 09:07:55 +0700
Newest: 2024-04-01 04:00:00 +0700

Failed: 31
Oldest: 2023-02-15 05:40:17 +0700
Newest: 2024-03-11 08:36:53 +0700

### Status report information ###

Generated at: 2024-03-11 09:06:57 +07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hello @agung2001, thanks for reaching out. After testing this, this is indeed a valid use case. I am adding this to our backlog, suggesting that this would be added into the options object, empowering devs to specify if the created Notice should have it's own element.

**Comment by wavvves** [comment]
Internal discussion: p1710509845755759-slack-C8X6Q7XQU

**Comment by wavvves** [comment]
@agung2001 after a bit of internal discussion, there is a workaround to unblock your work: to force a notice to be individual, make it not dismissible, eg:

```
wp.data.dispatch('core/notices').createSuccessNotice( 'Hello I\'m not dismissable', { isDismissible: false, context: 'wc/cart' } )
wp.data.dispatch('core/notices').createSuccessNotice( 'Hello I\'m not dismissable too', { isDismissible: false, context: 'wc/cart' } )
wp.data.dispatch('core/notices').createSuccessNotice( 'But we are', { isDismissible: true, context: 'wc/cart' } )
wp.data.dispatch('core/notices').createSuccessNotice( 'Yeah we are', { isDismissible: true, context: 'wc/cart' } )
```

<img width="447" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/05233b2c-969e-40c6-9bdf-1667665ee909">

**Comment by wavvves** [comment]
Closing this issue,as the behavior is the expected one for dismissible notifications.
