### ISSUE TITLE
[CYS on core] Ensure the URL for the transitional page is correct whenever accessing it for the very first time

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45488]
**Issue Description:**

This is a spin-off from https://github.com/woocommerce/woocommerce/issues/45448

While the original issue has been partially fixed on https://github.com/woocommerce/woocommerce/pull/45458, we still have the following implementation pending:

We need to ensure that whenever the user clicks on Done when going through the CYS flow for the very first time, they are led to wp-admin/admin.php?page=wc-admin&customizing=true&path=%2Fcustomize-store%2Ftransitional instead of keeping the URL unchanged wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub.

### Steps to reproduce

1. Make sure you have the WooCommerce Beta Tester plugin installed and activated
2. Under Tools > WCA Test Helper > Features, make sure customize-store is enabled
3. Under Tools > WCA Test Helper > Tools, click on Reset Customize Your Store
4. Head over to WooCommerce > Home > Customize your store
5. Click on "Start designing" and proceed to the Pattern Assembler
6. Make your changes and click on Done
7. Verify that even though you are led to the transitional page, the URL still corresponds to the Pattern Assembler:

<img width="1997" alt="311637292-4d56bf9d-510a-4b00-b511-066c7528475f" src="https://github.com/woocommerce/woocommerce/assets/15730971/f90e4ea4-7796-4513-a015-a2aeae05b318">

**Comment by Aljullu** [comment]
This is still reproducible as per WC 9.3:

![image](https://github.com/user-attachments/assets/ea2d42dd-e690-4e64-af72-6dc2dd99223e)
