### ISSUE TITLE
Discount Rules not working properly across all currencies

### ISSUE THREAD

**Issue by ClayandKelsy** [woothemes/woocommerce#45494]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi! 
So I think I found a bug.. 
I am trying to use discount rules to apply a % off when X amount of products are reached.

The rule works in USD. But its starts to get funky when you try and purchase in another currencies. its just straight up wrong in the calculation.. Also when I check: [ ] Show discount in cart as coupon instead of changing the product price ?
Its is wrong but in a different way. 
The price should be 45,00 € discounted to 34,71 €, with 5 products that should be 173,55 €. But when the "show discount as coupon" is NOT checked, it lowers the per item cost to 32 € & the total is 160 €.  And when it is, it changes out product prices to 42 € and makes the total 158,57 €...

I'll attach pictures of whats going on- The picture in USD is how it should look in the other currencies. This is actually affecting sales so I would love to get this sorted quickly! :)

Clay

@
<img width="774" alt="Screenshot 2024-03-11 at 1 11 06 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/1e30d66f-52c6-40b3-a3e4-3161e8534d1a">

<img width="869" alt="Screenshot 2024-03-11 at 12 36 44 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/0fe54472-b0f4-4bc8-859d-d1d004b7b3c7">

<img width="845" alt="Screenshot 2024-03-11 at 1 17 21 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/9e7ff4ea-efcf-4ded-849e-29a2eeb94ded">

### Expected behavior

The discounts apple correctly across all currencies. 

### Actual behavior

The math is just wrong.

The price should be 45,00 € discounted to 34,71 €, with 5 products that should be 173,55 €. But when the "show discount as coupon" is NOT checked, it lowers the per item cost to 32 € & the total is 160 €.  And when it is, it changes out product prices to 42 € and makes the total 158,57 €...

### Steps to reproduce

<img width="774" alt="Screenshot 2024-03-11 at 1 11 06 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/6077ee74-5450-4dda-a0a6-b5c7dad980d7">
<img width="845" alt="Screenshot 2024-03-11 at 1 17 21 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/b6db2ca5-6c11-4d28-bb9b-e9348a5025de">
<img width="869" alt="Screenshot 2024-03-11 at 12 36 44 PM" src="https://github.com/woocommerce/woocommerce/assets/163046171/c22e6aa2-d85a-4842-9d37-96a5780cb030">

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://clayandkelsy.com
Site address (URL): https://clayandkelsy.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.33-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 65.22MB
Database Data Size: 50.82MB
Database Index Size: 14.40MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.02MB + Index: 3.83MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.22MB + Index: 2.89MB + Engine InnoDB
wp_aioseo_cache: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_crawl_cleanup_blocked_args: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_crawl_cleanup_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_cr_local_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.25MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.22MB + Index: 0.11MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 3.52MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.08MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.25MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 1.47MB + Index: 0.11MB + Engine InnoDB
wp_options: Data: 2.13MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 12.19MB + Index: 0.64MB + Engine InnoDB
wp_posts: Data: 13.11MB + Index: 0.30MB + Engine InnoDB
wp_presto_player_audio_presets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_email_collection: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_presets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_videos: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_presto_player_visits: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_presto_player_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_serial_numbers: Data: 1.52MB + Index: 1.27MB + Engine InnoDB
wp_serial_numbers_activations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

ai_playlist: 12
amp_validated_url: 7
attachment: 343
customize_changeset: 107
custom_css: 1
feedback: 41
jetpack_migration: 2
jp_img_sitemap: 1
jp_pay_product: 23
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
mailpoet_page: 1
nav_menu_item: 23
page: 34
post: 1
pp_video_block: 1
product: 8
revision: 743
safecss: 1
shop_coupon: 13
shop_order: 209
wp_global_styles: 3
wp_navigation: 1
wp_template_part: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Afterpay Gateway for WooCommerce: by Afterpay – 3.8.5
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
All in One SEO: by All in One SEO Team – 4.5.8
Typing Effect: by 93digital – 1.3.7
Code Snippets: by Code Snippets Pro – 3.6.2
Crowdsignal Forms: by Automattic – 1.7.0
Customer Reviews for WooCommerce: by CusRev – 5.42.0
Direct Checkout for WooCommerce: by JEM Plugins – 1.3
Duplicate Page: by mndpsingh287 – 4.5.3
WordPress.com Editing Toolkit: by Automattic – 4.15561
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.25.0
Google Listings and Ads: by WooCommerce – 2.6.1
Site Kit by Google: by Google – 1.121.0
Gutenberg: by Gutenberg Team – 17.8.2
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Image Hover Effects Block: by Blocksera – 1.4.5
Smash Balloon Instagram Feed: by Smash Balloon – 6.2.9
Jetpack: by Automattic – 13.2-beta
Klarna Payments for WooCommerce: by klarna – 3.4.0
Layout Grid: by Automattic – 1.8.4
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
MailPoet: by MailPoet – 4.45.0
Meta Tag Manager: by Marcus Sykes – 3.0.2
Music Player for Easy Digital Downloads: by CodePeople – 1.1.5
Meta pixel for WordPress: by Facebook – 3.0.15
OptinMonster: by OptinMonster Popup Builder Team – 2.16.0
Page Optimize: by Automattic – 0.5.5
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Redirection: by John Godley – 5.4.2
Smart Slider 3: by Nextend – 3.5.1.21
Title Remover: by WPGurus – 1.2.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.1

WC Serial Numbers Pro: by PluginEver – 1.3.3
WC Serial Numbers: by PluginEver – 1.6.9
Discount Rules Core: by Flycart – 2.6.3
WooCommerce Amazon Pay: by WooCommerce – 2.5.1
WooPayments: by Automattic – 7.3.0
WooCommerce PayPal Payments: by WooCommerce – 2.5.4
WooCommerce Shipping & Tax: by WooCommerce – 2.5.2
WooCommerce: by Automattic – 8.6.1
Yoast SEO: by Team Yoast – 22.2
Smush: by WPMU DEV – 3.15.5
WPFront Notification Bar: by Syam Mohan – 3.4

### Inactive Plugins (5) ###

AMP: by AMP Project Contributors – 2.5.2
AudioIgniter: by The CSSIgniter Team – 2.0.0
Classic Editor: by WordPress Contributors – 1.6.3
Music Player for Elementor: by SmartWPress – 1.9
WP Mail SMTP: by WP Mail SMTP – 4.0.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.9.1
WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #982 - /shop/
Cart: #983 - /cart/
Checkout: #984 - /checkout/
My account: #985 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Maywood
Version: 1.5.26
Author URL: https://automattic.com/
Child Theme: ✔
Parent Theme Name: Varia
Parent Theme Version: 1.6.30
Parent Theme Author URL: https://automattic.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.3.0
Connected to WPCOM: Yes
WPCOM Blog ID: 199354713
Account ID: acct_1LZRfm2HdIP0ofVy
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Enabled (cart,checkout,product)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Klarna Payments Request Log ###

No Klarna Payment errors: 

### Klarna Countries ###

Production Countries: No countries selected
Test Countries: No countries selected

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-11 21:13:53 -07:00
Options: ✔
Notes: 177
Onboarding: completed

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Current sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://clayandkelsy.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 4
Oldest: 2024-02-26 11:47:11 -0800
Newest: 2024-03-11 06:32:22 -0700

Complete: 8,274
Oldest: 2024-02-09 12:24:39 -0800
Newest: 2024-03-11 13:21:23 -0700

Failed: 29
Oldest: 2022-11-02 14:19:39 -0700
Newest: 2024-03-04 14:00:53 -0800

Pending: 7
Oldest: 2024-03-11 13:23:23 -0700
Newest: 2024-03-11 22:28:03 -0700

### Status report information ###

Generated at: 2024-03-11 13:23:34 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ClayandKelsy** [comment]
Hi, so this is still ongoing and starting to affect sales. I would love some assistance please! 

Thanks,
Clay

**Comment by rrennick** [comment]
> Discount Rules Core: by Flycart – 2.6.3

@ClayandKelsy This repository is for issues with WooCommerce. Please contact the folks at Flycart for support on their extension.
