### ISSUE TITLE
[GlobalStep] "I'm already selling", "platform" and "POS" choices fail to record the URL parameter.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#45505]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"I'm already selling", "platform" and "POS" choices fail to record the URL parameter.

### Expected behavior

"I'm already selling", "platform" and "POS" choices should be recorded in the URL parameter.

### Actual behavior

"I'm already selling", "platform" and "POS" choices fail to record the URL parameter.

### Steps to reproduce

1. In a new private window, open https://woocommerce.com/start
2. Observe you’re on the page Which one of these best describes you?
3. Click on I'm already selling online
4. Observe Which platform(s) are you currently using? (optional) field appears.
5. Click Continue – Note the choices you have selected, we will check these later
6. Observe that you’re redirected to a page with Tell us a bit about your store
7. Observe the expected location is discovered for the Where is your business located? field
8. Click Continue – Note the choices you have selected, we will check these later
9. Observe you’re on the page Launch in days, grow for years
10. When you click on Try for Woo Express free, you should be redirected to sign up screen with the heading Let's get started
11. Fill in your email, username, and password, and click on Get started
12. You should be redirected to a wordpress.com URL with a profilerdata=<xx> URL parameter. 
13. Copy this and decode it in [CyberChef](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)) or any other base64 decoder.
14. Observe that the data in the decoded JSON fails to record "I'm already selling", "platform" and "POS" choices fail to record the URL parameter.

### Screenshots:

![#45505 1](https://github.com/woocommerce/woocommerce/assets/41110392/fdb7213a-2194-4f66-8cdd-dd06e3400a90)

![#45505 2](https://github.com/woocommerce/woocommerce/assets/41110392/50e91492-4808-4a23-8d18-a6d114b0f8bc)

![#45505 3](https://github.com/woocommerce/woocommerce/assets/41110392/e34c059a-3757-4077-ab57-e6cbecd0af0f)

### WordPress Environment

PC:
Windows 10
Chrome (Version 122.0.6261.112)
Firefox (Version 123.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Closing this issue because it had to be created in another repository. I created a new issue in the right place and copy pasted the bug report: https://github.com/Automattic/woocommerce.com/issues/20065.
