### ISSUE TITLE
[GlobalStep] For Mobile viewport, "Use a different email address. This email provider blocks some of our emails." notice is displayed after filling new email with "+" incrementor on "Create an account" page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#45502]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For Mobile viewport, "Use a different email address. This email provider blocks some of our emails." notice is displayed after filling new email with "+" incrementor on "Create an account" page.

### Expected behavior

No notice should be displayed after filling new email with "+" incrementor on "Create an account" page.

### Actual behavior

"Use a different email address. This email provider blocks some of our emails." notice is displayed after filling new email with "+" incrementor on "Create an account" page.

### Steps to reproduce

1. In a new private window, open browser console window and set viewport to mobile device (e.g Galaxy S10).
2. In a new private window, open https://woocommerce.com/start
3. Observe you’re on the page Which one of these best describes you?
4. Click on I'm already selling online
5. Observe Which platform(s) are you currently using? (optional) field appears.
6. Click Continue
7. Observe that you’re redirected to a page with Tell us a bit about your store
8. Observe the expected location is discovered for the Where is your business located? field
9. Click Continue
10. Observe you’re on the page Launch in days, grow for years
11. When you click on Try for Woo Express free, you should be redirected to sign up screen with the heading Let's get started
12. Fill in your email with "+1", it’s recommended to use an email provider that supports aliases, such as Gmail.
13. For example, if your base email is globalsteptesting@gmail.com, you could use globalsteptesting+1@gmail.com, where +1 is a running number that you can just increment for every new account.
14. Observe that "Use a different email address. This email provider blocks some of our emails." notice is displayed after filling new email with "+" incrementor.

### Video:

https://github.com/woocommerce/woocommerce/assets/41110392/4a899cac-a71e-486c-8a0d-8bb5ad77b2ab

### Screenshot;

![#45502 1](https://github.com/woocommerce/woocommerce/assets/41110392/c4534c77-5164-4657-8f34-85863b118547)

### WordPress Environment

PC:
Windows 10
Chrome (Version 122.0.6261.112)
Firefox (Version 123.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Closing this issue because it had to be created in another repository. I created a new issue in the right place and copy pasted the bug report: https://github.com/Automattic/wc-calypso-bridge/issues/1453.
