### ISSUE TITLE
Maxmind R2 presigned URLs - API changes

### ISSUE THREAD

**Issue by strarsis** [woothemes/woocommerce#45514]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

As I am using Maxmind features on the WooCommerce shop site, I have a Maxmind user account (for the required API access).

Today I received an email from Maxmind, announcing that for May 1st 2024, Maxmind will have transitioned to R2 presigned URLs, including changes to the download URLs (see https://meta.discourse.org/t/maxmind-r2-presigned-urls/298941).

Does WooCommerce core require adjustments for using this updated API?

### Expected behavior

WooCommerce should still be able to use the Maxmind API after the announced API transitions.

### Actual behavior

Unsure whether WooCommerce will be compatible with the announced changes to Maxmind API.

### Steps to reproduce

Receive Maxmind email announcement.

### WordPress Environment

WooCommerce latest (8.6.1)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @strarsis,

Thank you for bringing this to our attention. We have done some internal testing and can confirm that a) the redirects are already happening and b) WooCommerce is handling them just fine. Based on this I will close this issue. Please reach out again in the future if you're seeing or suspecting anything not working.
