### ISSUE TITLE
No feedback on Cart Block when shipping options are not available for the provided address.

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#45525]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On Cart block, after entering an address without available shipping options, no feedback is provided.

### Expected behavior

It should display the `There are no shipping options available.` message.

### Actual behavior

No message is displayed, only the option to add an address to display shipping options.

<img width="350" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/d8ffaff0-31ec-49c4-80d8-d0542314044c">

### Steps to reproduce

1. Set up shipping zones on your site, but ensure there's a country with no shipping zones covering it.
2. Enable the shipping calculator (WooCommerce -> Settings -> Shipping -> Shipping Settings -> Enable the shipping calculator on the cart page)
3. Add an item to your cart and go to the (blocks) Cart page.
4. Using the shipping calculator, enter an address for a country with no shipping zones.
5. Verify no feedback is given, only the option to enter the address again.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Adding `priority: high` since there is a high probability this has been a recent regression, I'm currently investigating where this started happening.

**Comment by ralucaStan** [comment]
This will be handled this cycle, we're going to create a new issue for it and close this one.

**Comment by pmcpinto** [comment]
> This will be handled this cycle, we're going to create a new issue for it and close this one.

@ralucaStan  should we close this issue?

**Comment by ralucaStan** [comment]
closing. this will be handled in https://github.com/woocommerce/woocommerce/issues/46949
