### ISSUE TITLE
Adding Cart Icon Block to Navigtion results in wp-json/wc/store/ requests on each Page

### ISSUE THREAD

**Issue by swissky** [woothemes/woocommerce#45543]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hey, we had the issue that the /wp-json/wc/store/v1/cart?_locale=user url is each time requested on a page, when we add the Mini-Cart Block to the Navigation. This issue doesn't let us cache the website right. This can`t be the right solution.

### Expected behavior

Fix this block, so there is no API request all the time.

### Actual behavior

see above

### Steps to reproduce

No way untile you log in to our website. Maybe you can repoduce the problem on your own website with that block https://share.cleanshot.com/8SYs3RG8CLdQpHPMJShd

### WordPress Environment

Staging Area
`
### WordPress Environment ###

WordPress address (URL): https://cardcollectors.thismatters.cloud
Site address (URL): https://cardcollectors.thismatters.cloud
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 8.1.23
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.82.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 573.35MB
Database Data Size: 342.01MB
Database Index Size: 231.34MB
wp_woocommerce_sessions: Data: 48.58MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 20.55MB + Index: 21.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iwp_db_sent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iwp_files_sent: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.45MB + Index: 0.55MB + Engine InnoDB
wp_actionscheduler_claims: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.27MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_ip_store: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_comments: Data: 13.52MB + Index: 11.09MB + Engine InnoDB
wp_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Data: 19.55MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_logs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_user_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gamipress_user_earnings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_mlp_content_relations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mlp_languages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mlp_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mlp_site_relations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.05MB + Index: 0.14MB + Engine InnoDB
wp_options: Data: 5.38MB + Index: 3.45MB + Engine InnoDB
wp_postmeta: Data: 107.63MB + Index: 93.80MB + Engine InnoDB
wp_posts: Data: 32.52MB + Index: 4.84MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sb_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 8.52MB + Index: 10.58MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.52MB + Index: 0.42MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 15.52MB + Index: 16.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 1.22MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_orders: Data: 3.52MB + Index: 5.22MB + Engine InnoDB
wp_wc_orders_meta: Data: 18.55MB + Index: 37.28MB + Engine InnoDB
wp_wc_order_addresses: Data: 3.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_operational_data: Data: 2.52MB + Index: 0.78MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.52MB + Index: 3.95MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.92MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.44MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wl_mapping_property: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_mapping_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_mapping_rule_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpjf3_mr_access_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpjf3_mr_unrestricted_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 11.52MB + Index: 1.69MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcmc_register: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 0.75MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.13MB + Index: 0.23MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.33MB + Index: 0.67MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
acf-taxonomy: 5
attachment: 3021
bricks_template: 7
custom_css: 3
customize_changeset: 66
et_pb_layout: 1
filter-field: 6
filter-set: 1
gp_elements: 12
mgmlp_media_folder: 16
ml-slide: 9
ml-slider: 1
nav_menu_item: 66
oembed_cache: 207
page: 70
post: 133
product: 1547
product_variation: 10
revision: 446
shop_coupon: 952
shop_order: 10650
shop_order_refund: 138
wafs: 2
wcpf_item: 4
wcpf_project: 1
wp_global_styles: 1
wp_navigation: 1
wp_show_posts: 6
wpforms: 1
yith_wcan_preset: 1
yith-wcgpf-feed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

weLaunch Framework: by weLaunch.io – 1.1.1
Advanced Custom Fields PRO: by WP Engine – 6.2.7
Antispam Bee: by pluginkollektiv – 2.11.5
Code Snippets: by Code Snippets Pro – 3.6.2
Disable User Login: by Saint Systems – 1.3.9
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Filter Everything PRO: by Andrii Stepasiuk – 1.7.15
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.8.2
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.1.11
GenerateBlocks Pro: by Tom Usborne – 1.5.2
GenerateBlocks: by Tom Usborne – 1.8.3
GP Premium: by Tom Usborne – 2.4.0
mame TWINT for WooCommerce: by mame software development hüttig – 5.5.1
Smart Slider 3 Pro: by Nextend – 3.5.1.22
Perfmatters: by forgemedia – 2.2.3
ProductX Pro - Gutenberg Product Blocks for WooCommerce: by wpxpo – 1.3.5
ProductX – Gutenberg WooCommerce Blocks: by wpxpo – 3.1.10
Safe SVG: by 10up – 2.2.2
Servebolt Optimizer: by Servebolt – 3.5.32
Stop Emails: by Sal Ferrarello – 1.2.1
WooCommerce Direct Checkout: by QuadLayers – 3.3.2
WooCommerce Stripe Gateway: by WooCommerce – 8.0.0
WooCommerce Single Variations: by weLaunch – 1.4.2
WooCommerce Waitlist: by Neil Pie – 2.4.2
WooCommerce: by Automattic – 8.6.1
Yoast SEO Premium: by Team Yoast – 21.8
Yoast SEO: by Team Yoast – 22.2
Hide Dashboard Notifications: by WP Republic – 1.3
WP Search with Algolia: by WebDevStudios – 2.7.1
WP Show Posts: by Tom Usborne – 1.1.5
WPForms Lite: by WPForms – 1.8.7.2
Yoast SEO: WooCommerce: by Team Yoast – 16.1

### Inactive Plugins (7) ###

Loco Translate: by Tim Whitlock – 2.6.6
Offload Media to Cloudflare Images: by Anton Vanyukov – 1.8.0
Query Monitor: by John Blackbourn – 3.15.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Slim Maintenance Mode: by Johannes Ries – 1.4.3
Smart Slider 3: by Nextend – 3.5.1.21
WP Mail SMTP Pro: by WPForms – 3.7.0

### Must Use Plugins (1) ###

Perfmatters MU: by forgemedia – 2.2.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #48056 - /tcg-card-shop/
Cart: #8651 - /cart/
Checkout: #8652 - /checkout/
My account: #8653 - /mein-konto/
Terms and conditions: #8657 - /agb-allgemeine-geschaeftsbedingungen/

### Theme ###

Name: GeneratePress Child
Version: 0.3
Author URL: https://thismatters.agency
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.4.0
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-02 14:35:13 +01:00
Options: ✔
Notes: 80
Onboarding: completed

### Action Scheduler ###

Complete: 1,108
Oldest: 2024-01-17 15:03:00 +0100
Newest: 2024-03-13 12:58:30 +0100

Failed: 40
Oldest: 2023-03-06 16:37:12 +0100
Newest: 2024-03-07 16:21:12 +0100

Pending: 5
Oldest: 2024-03-14 12:52:20 +0100
Newest: 2024-03-15 08:53:14 +0100

### Status report information ###

Generated at: 2024-03-13 13:29:57 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swissky** [comment]
Update: This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).

With Storefront i can reproduce this bug, if i add the Mini Cart Block as a Widget Below the Header.

**Comment by wavvves** [comment]
Hello @swissky, thank you for reaching out. 

Actually the purpose of that request is to allow caching of webpages containing the mini-cart, in an optimistic approach.

It will try to fill the mini-cart info from the browser saved while in the background verifying with the server and updating it with the received information (in case both match, this will be invisible to the user).

To use cache properly, you just need to make sure `/wp-json/wc/store/v1/cart` is not cached (or cached correctly, with a different cache object per session, purging when modified).

**Comment by opr** [comment]
@swissky I'm going to close this issue as I don't think there's anything actionable. The requests are expected and are required to make the mini cart work correctly with caches. Thanks a lot for taking the time to report this though!
