### ISSUE TITLE
[Enhancement]: Mini-cart block: Ability to open the cart page directly when clicking on the icon

### ISSUE THREAD

**Issue by Gustavo-Hilario** [woothemes/woocommerce#45552]
### Describe the solution you'd like

Add the ability to access the cart page directly when clicking on the mini-cart block. As of now, when clicking on the icon, we will see the mini-cart sidebar, and there is no option to change the behavior.

### Describe alternatives you've considered

An option for this is to add a simple link to the cart page on the site's menu, but having that link and the mini-cart icon can be confusing. Also, it's great that the mini-cart can calculate the total amount on the user's cart and display the products counter on the icon. This is not something achievable with a simple link.

### Additional context

Let's take an example of a user who enabled the option to show the mini-cart sidebar whenever the user adds a product to their cart. If the user continues navigating on the site and wants to complete the checkout, they must click on the mini-cart icon and then "View my cart". But since that has been opened whenever the user added a product, it could be nice to have an option to disable that sidebar and just navigate to the cart page by clicking on the icon. The idea here is to remove friction and allow users to go to the cart page faster while keeping the nice design and features of the mini-cart block.

Customer Request here: 7862260-zen

**Comment by opr** [comment]
Hi @Gustavo-Hilario, thanks!

I've added this to our backlog. Personally I think this would be a great enhancement to the block.
