### ISSUE TITLE
Benchmark performance of cart and checkout pages for comparison with alternatives

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#45573]
**Issue Description:**

To benchmark impact of removing `@wordpress/components` from the cart and checkout pages we need to measure the baseline performance. To determine this baseline we need the following metrics for both cart and checkout page:

1. Total kb css payload of css that is only loaded by the page
2. Total kb js payload of js that is only loaded by the page
3. A lighthouse metrics report

**Comment by samueljseay** [comment]
### JS payloads - production

JS scripts unique to the cart page: 89.8KB BR
JS scripts unique to the checkout page: 31.5 KB BR
JS scripts shared just by cart/checkout: 71.5KB BR

### CSS payload

Across cart and checkout: 20.8KB of blocks styles that could possibly be impacted. includes:

* wc-blocks.min.css - 2.8KB
* packages-style.min.css - 6.2KB
* checkout.min.css - 9.2KB
* style.min.css - 2.6KB

Dashicons is also an additional 35kb and its not used on the page at all. could be worth exploring if it can be dequeued.






Note that for comparison after removing wp.components, I will also indicate any scripts that *were loaded on cart or checkout as well as other pages* but are now not loaded by cart or checkout pages. (I suspect lodash could fall in this category for example).

**Comment by samueljseay** [comment]
Take these lighthouse reports with a large grain of salt, not sure how much we'll actually be able to move the needle on these. Especially for example, most of the unused css or js is enqueued on every page by default (could be solved separately such as in https://github.com/woocommerce/woocommerce/issues/45595 )

[Archive.zip](https://github.com/woocommerce/woocommerce/files/14612093/Archive.zip)

**Comment by ralucaStan** [comment]
@samueljseay should this ticket also be closed? Considering it's in the Done column?

**Comment by samueljseay** [comment]
Yep, I'll close it thanks
