### ISSUE TITLE
CYS not working on Woo Express when Gutenberg plugin is deactivated

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#45599]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The CYS is not working on Woo Express when Gutenberg is deactivated. It doesn't seem to be related to any particular WooCommerce or WordPress version, and it affects Woo Express sites.

### Expected behavior

The CYS should success and you should see your new design made with AI.

### Actual behavior

The loading page gets stuck at the end and you see the following error in the browser console:

```
VM3300 react-dom.min.js:10 Error: You tried to opt-in to unstable APIs as module "@wordpress/edit-site" which is already registered. This feature is only for JavaScript modules shipped with WordPress core. Please do not use it in plugins and themes as the unstable APIs will be removed without a warning. If you ignore this error and depend on unstable features, your product will inevitably break on one of the next WordPress releases.
    at s (VM3331 private-apis.min.js:2:1333)
    at 86537 (VM3771 customize-store.js:1:637)
    at r (VM3301 index.js:2:430429)
    at 86165 (VM3768 9890.js:2:6478)
    at r (VM3301 index.js:2:430429)
    at 56861 (VM3771 customize-store.js:1:60216)
    at Function.r (VM3301 index.js:2:430429)
```

Please check the video below:
<video src="https://github.com/woocommerce/woocommerce/assets/45979455/19458a4c-503d-4627-862a-3392fbb9af0c" controls="controls" style="max-width: 730px;">
</video>

### Steps to reproduce

1. Create a Woo Express site.
2. Upgrade to the essential or performance plan.
3. Deactivate the `Gutenberg` plugin.
4. Go to `WooCommerce > Home` and click `Start customizing`.
5. On the `Customize your store` page, click `Design with AI`, proceed if any confirmation modal appears.
6. In the `Tell us a bit more about your business` page, enter any description and click `Continue`.
7. In the `How would you like your store to look?` page, select any option and click `Continue`.
8. In the `Which writing style do you prefer?` page, select any option and click `Continue`.
9. Wait until the loading page ends.

### WordPress Environment

N/A.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
@moon0326 mentioned it's likely related to https://github.com/woocommerce/woocommerce/pull/40884

**Comment by chihsuan** [comment]
Just took a quick look. This is different from the issue we solved before. Previously, the error was due to [different consent strings](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L110-L118), but now it’s because [registration isn’t allowed](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L95-L109).

I think we'll need to see what's causing [this logic](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L96-L97) to be true and then address it accordingly.

**Comment by moon0326** [comment]
It looks like we use a slightly different version of private-api package.



Gutenberg deactivated: `private-api.min.js` is used
Gutenberg activated: `private-api/index.min.js` is used

When Gutenberg is activated, [allowReRegistration](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L68) is always set to true.

When Gutenberg is deactivated and core's private-api is used, `allowReRegistration` is always false. The code [comment](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L63) implies that it is supposed to be `true`, but I'm not sure why it's not. Does anyone have any idea, or am I misinterpreting it?



There isn't anything we can do in WooCommerce side as we can't modify the var from our end as far as I understand.

I have three not-so-nice suggestions/workarounds at the moment.

1. Add `forceReRegistration` param to [__dangerousOptInToUnstableAPIsOnlyForCoreModules](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L82) function.
2. Manually remove all registered APIs and re-register them without `@wordpress/edit-site` so we can register it again. I would like to avoid this approach as we need to manually copy the allowed APIs and re-register them using [functions](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/src/implementation.js#L221) intended for tests.

3. Render a warning message and ask user to activate Gutenberg.

**Comment by adrianduffell** [comment]
> Render a warning message and ask user to activate Gutenberg.

This would be my vote. I think it will be rare scenario for Gutenberg to be de-activated on Woo Express when CYS is used. I think it's reasonable to show the warning message in the cases where it happens, and it saves us making deeper code changes.

**Comment by moon0326** [comment]
@adrianduffell If we've decided to move forward with option #3, I think we need a design. Should we ping Veronica? A modal popup would be nice in my opinion.

**Comment by vbelolapotkov** [comment]
@albarin @lanej0 could you please explain why it was routed from Kirigami to Transact team? I checked the comments, and don't understand the connection here.

**Comment by lanej0** [comment]
Apologies on my end.  I saw that Alex created it and figured it was a todo that was created and the team label was forgotten (when going through triage). It looks like it should be Kirigami & Origami because it's CYS... not sure why that tag was removed @albarin?

**Comment by albarin** [comment]
Hey, I removed the label based on this conversation p1716282509525839-slack-C053716F2H2, I think Apex team is going to take care of it.
(cc @nefeline)

**Comment by alopezari** [comment]
Thanks for the explanation @albarin!

@lanej0, do you think we should add a new label for that team considering they might recurrently contribute to this repository?

**Comment by lanej0** [comment]
@alopezari -- I'll check in with the team, but if there are going to be ongoing contributions, it makes sense to me to add one!

**Comment by alopezari** [comment]
Thanks @lanej0!

Not 100% sure if they will contribute consistently to this repo, but new Woo Express features might require changes in WooCommerce Core so I think it's worth checking with them.

**Comment by lanej0** [comment]
They weren't one of the teams mentioned in the Woo Express post here: https://hostedwoo.wordpress.com/2024/05/09/maintenance-for-the-woo-express-and-entrepreneur-ecommerce-experience/ -- so I'm thinking it might be a one-time thing, or maybe that work isn't going to be done here but rather somewhere upstream?  

Regardless, we'll create the team label.  The only concern is that if they're not working in the repo, that the issue will just get lost/abandoned. 

From a triage point of view, if a team is going to start working more in Core, we'll need to find out what their focus is and get them added to our triage documentation so that we know when to route them a particular issue.

**Comment by alopezari** [comment]
> Regardless, we'll create the team label. The only concern is that if they're not working in the repo, that the issue will just get lost/abandoned.

Well, other teams that focused in Woo Express in the past eventually contributed to the monorepo, just like teams that contributed to other projects/plugins that depend or work closely with WooCommerce Core, but that might change at any time so I think it's worth clarifying this with them. Thanks for handling this!

**Comment by gigitux** [comment]
I'm not able to replicate this issue anymore. I'm going to close this issue!
