### ISSUE TITLE
[CYS on Core] Product rating block not rendering

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45593]
**Issue Description:**

This is a spinoff of https://github.com/woocommerce/woocommerce/issues/45475 : while that issue ended up being a regression on WP 6.5, this one is focused on investigating a problem that is preventing the Product Rating block from working as expected:

## Steps to reproduce

1. Make sure you have the WooCommerce Beta Tester plugin installed and activated
2. Under Tools > WCA Test Helper > Features, make sure customize-store is enabled
3. Under Tools > WCA Test Helper > Tools, click on **Reset Customize Your Store** and **Delete all products**
4. Head over to WooCommerce > Home > Customize your store
5. Click on "Start designing" and proceed to the Pattern Assembler
6. On the initial screen, scroll down and notice how the Product Rating block is throwing the following error:

<img width="1998" alt="Screenshot 2024-03-14 at 15 51 55" src="https://github.com/woocommerce/woocommerce/assets/15730971/0cbd066a-0cd2-4cee-9fd1-22638bdfb055">

**Comment by gigitux** [comment]
It looks like in some cases (I'm still not able to define them), the JS related to the Product Rating block is not enqueued:

| Bug | No Bug |
|--------|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/4463174/4ec93d5e-685a-443c-8134-73d35af7d5ef) | ![image](https://github.com/woocommerce/woocommerce/assets/4463174/a1283977-7da4-4682-9ece-53b188b7ed7f) | 

I'm continuing to investigate.

**Comment by gigitux** [comment]
The issue is replicable when jetpack is installed

**Comment by gigitux** [comment]
I was able to narrow the issue. It is reproducible with Jetpack installed. The PR that introduced this regression is: https://github.com/woocommerce/woocommerce/pull/45196
