### ISSUE TITLE
Variable Product Import Issue

### ISSUE THREAD

**Issue by moumitahalder** [woothemes/woocommerce#45611]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

- I have exported variable product from WP-admin >> Products >> Export : https://www.awesomescreenshot.com/video/25841293?key=dfd1af22d419fd10586bef53a02615c1
- Then deleted that exported product permanently from the site https://snipboard.io/Gu1ESi.jpg
- Now imported that product using the exported csv
- As you can see here , the variable product s created with no variation attached with it https://www.awesomescreenshot.com/video/25841395?key=82d220f1822c6e6ece446e059e4e0267

This is the CSV exported from WooCommerce : 
[wc-product-export-15-3-2024-1710490082974.csv](https://github.com/woocommerce/woocommerce/files/14612704/wc-product-export-15-3-2024-1710490082974.csv)

### Expected behavior

The variation should have been created with the variation. 

### Actual behavior

Currently this is not creating any variation.

### Steps to reproduce

- I have exported variable product from WP-admin >> Products >> Export : https://www.awesomescreenshot.com/video/25841293?key=dfd1af22d419fd10586bef53a02615c1
- Then deleted that exported product permanently from the site https://snipboard.io/Gu1ESi.jpg
- Now imported that product using the exported csv
- As you can see here , the variable product s created with no variation attached with it https://www.awesomescreenshot.com/video/25841395?key=82d220f1822c6e6ece446e059e4e0267

This is the CSV exported from WooCommerce : 
[wc-product-export-15-3-2024-1710490082974.csv](https://github.com/woocommerce/woocommerce/files/14612704/wc-product-export-15-3-2024-1710490082974.csv)

### WordPress Environment

There is no error in the log https://snipboard.io/2q7OtY.jpg

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @moumitahalder,

Thanks for the report. Would you be able to include a copy of your system status report? The System Status Report is found in your WordPress admin under **WooCommerce > Status**.  Please select “Get system report”, then “Copy for support”, and then paste it in reply.

**Comment by moumitahalder** [comment]
here is the system report screenshot https://tinyurl.com/25qkf8ux

`
### WordPress Environment ###

WordPress address (URL): http://localhost/mvx
Site address (URL): http://localhost/mvx
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.0.30
PHP Version: 8.0.30
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 10.4.32-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 6.25MB
Database Data Size: 4.42MB
Database Index Size: 1.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mvx_cust_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mvx_cust_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mvx_products_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mvx_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mvx_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mvx_vendor_ledger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mvx_vendor_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mvx_visitors_stats: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 10
post: 2
product: 18
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Loco Translate: by Tim Whitlock – 2.6.6
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Hello Dolly: by Matt Mullenweg – 1.7.2
MultiVendorX: by MultiVendorX – 4.1.3
Product Stock Manager & Notifier for WooCommerce: by MultiVendorX – 2.4.2
WooCommerce Stock Manager & Notifier Pro: by  – 1.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-17 06:56:40 +00:00
Options: ✔
Notes: 67
Onboarding: completed

### Action Scheduler ###

Complete: 62
Oldest: 2024-02-23 06:57:39 +0000
Newest: 2024-03-16 08:29:24 +0000

Failed: 1
Oldest: 2024-02-23 07:50:02 +0000
Newest: 2024-02-23 07:50:02 +0000

Pending: 1
Oldest: 2024-03-17 08:29:24 +0000
Newest: 2024-03-17 08:29:24 +0000


### Status report information ###

Generated at: 2024-03-16 13:52:02 +00:00
`

**Comment by moumitahalder** [comment]
Hi team, any update?

**Comment by rrennick** [comment]
@moumitahalder The export file only contains the variable product records. It doesn't include any variations. You need to include the variations in your export file

<img width="755" alt="Screenshot 2024-03-21 at 11 07 35 AM" src="https://github.com/woocommerce/woocommerce/assets/343847/4b9b031d-4009-4545-8b54-0e26ef1ec25c">

Closing this as a question.
