### ISSUE TITLE
[Enhancement] Link WooPayments Payments Settings CTAs to Connect page

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#45625]
### Describe the solution you'd like

For WooPayments-eligible store countries, we should direct merchants from the Payments Settings page to the Payments Connect page (under the Payments main menu item) and avoid opening the onboarding flow directly.

1. When in a WooPayments-eligible country, we show a "Install" button:
![WooPayments Onboarding Flows (1)](https://github.com/woocommerce/woocommerce/assets/8830539/53a6212d-df4f-4222-831d-4d4da59c5073)
Let the logic there install and activate the plugin and then link to the Connect page (that becomes available with the activation).

2. When WooPayments is installed and activated, and the payment gateway is enabled, but there is no WooPayments account linked, we show a "Manage" button:
![WooPayments Onboarding Flows](https://github.com/woocommerce/woocommerce/assets/8830539/46b76996-6ad5-47dd-8dd7-48ddf69a3a9f)
Link the Manage button to the Connect page.

3. When WooPayments is installed and activated, but the payment gateway is not enabled and there is no WooPayments account linked, we show a "Finish set up" button and marketplace promo banner:
![WooPayments Onboarding Flows (2)](https://github.com/woocommerce/woocommerce/assets/8830539/95f42239-0f34-446f-a2f5-cf5b618e4265)
Link the "Finish set up" button to the Connect page.
Link the marketplace "Get started" CTA to the Connect page (this change might need to be done on the remote source).

The benefits are:
- consolidate WooPayments flows
- reduce complexity in our flows
- reduce maintenance burden and the likelihood of disjointed experiences

cc @elizaan36 @timmy5685

**Comment by vladolaru** [comment]
@elizaan36 Thinking on a couple of additional enhancements that we could make since we are here:
- Change the "Manage" button label for scenario 2 to the same "Finish set up" label
- Remove the TOS copy from all 3 scenarios since we have it on our current Connect page and we will have it in our MOX (regardless of WooPayments client version, we are covered).

WDYT?

**Comment by elizaan36** [comment]
> Scenario 1 - Let the logic there install and activate the plugin and then link to the Connect page (that becomes available with the activation).

Makes sense.

> Scenario 2 - Link the Manage button to the Connect page.

This isn't correct. The gateway is enabled so "Manage" goes to the WooPayments settings page. There's no change here except the TOS shouldn't be there.

> Scenario 3 - Link the "Finish set up" button to the Connect page.
> Link the marketplace "Get started" CTA to the Connect page (this change might need to be done on the remote source).

Makes sense.

> Change the "Manage" button label for scenario 2 to the same "Finish set up" label

No, this label shouldn't change. "Manage" is correct for the enabled extension.

> Remove the TOS copy from all 3 scenarios since we have it on our current Connect page and we will have it in our MOX (regardless of WooPayments client version, we are covered).

YES. +1 to this. There's also the TOS copy on the Marketplace banner. Let's get rid of it!

**Comment by vladolaru** [comment]
@elizaan36 

Regarding scenario 2 and `"Change the "Manage" button label for scenario 2 to the same "Finish set up" label"`: I failed to specify that **there is no WooPayments account linked** (so there is no Settings page). That Manage button goes to onboarding flow, not Settings page, in this scenario.
So we can have the payment gateway enabled/disabled without having a proper account. That is why I proposed treating this scenario the same as when the gateway is disabled and doesn't have an account.

I agree that if WooPayments is properly setup, the CTA should be Manage and link to Settings (as it already does).

**Comment by elizaan36** [comment]
I'm not familiar with that scenario. How can the gateway be enabled if no
WooPayments account is linked? How would the user get to this state?

**Comment by vbelolapotkov** [comment]
Marking this one as triaged, assuming that @timmy5685 and the team will prioritize it.

**Comment by vladolaru** [comment]
> I'm not familiar with that scenario. How can the gateway be enabled if no
WooPayments account is linked? How would the user get to this state?

@elizaan36 I guess this is more of an edge case that we devs end up in because we are disconnecting/deleting our test accounts. So if WooPayments was enabled and fully capable, but the account got disconnected from the blog (or deleted straight up), you would end up in that state.

Come to think of it; maybe we should fine-tune our payment gateway-based behavior about determining enablement. It might be tricky since this is also something merchants can control via the toggle.

**Comment by elizaan36** [comment]
Got it! Yes, this is an edge case that the merchant wouldn't see. I'd lean towards separating this use case into another issue, considering the potential for confusion with the connected state.

**Comment by timmy5685** [comment]
@vladolaru - thanks for documenting this. Regarding scenario 2 - is there any reason why we wouldn't just flip the switch on enabled back to disabled? If we did - then it could treat it like scenario 3 and prompt "finish set-up"?

**Comment by vladolaru** [comment]
@timmy5685 You are right, we probably should tie the payment gateway enabled/disabled status to having or not having a WooPayments connected/linked account.

**Comment by anu-rock** [comment]
@vladolaru @timmy5685 Given our directional changes in https://github.com/woocommerce/woocommerce/issues/51443, do we still need this issue?

**Comment by vladolaru** [comment]
True. I don't think we need it anymore if we haven't acted on it by now.
