### ISSUE TITLE
Cannot create variation options when viewport width is small

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#45641]
## Description

When the viewport width is small, the UI to add variation option disappears, leaving no option to create new variation options.

![Image](https://github.com/woocommerce/woocommerce/assets/13437655/23290a3c-bba1-44fe-8147-6910d6da34a9)

There should be a way to create variation options when the viewport is small. Maybe we can show an 'Add options' button in the section header, similar to how it's done on the Attributes section:

![Image](https://github.com/woocommerce/woocommerce/assets/13437655/e2ba0eed-2196-463e-84e9-4f3589748fc0)

**Comment by mattsherman** [comment]
@pmcpinto @j111q Any details on what we should do for the UX of this, or should we go with "developer's choice"? 😄

**Comment by pmcpinto** [comment]
Why don't we keep the same placeholder with some adjustments to ensure it works well with this viewport?

**Comment by j111q** [comment]
+1 with @pmcpinto's suggestion to make the empty state more responsive. I'd imagine it something like this, quick mock-up

<img width="858" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/077f71cb-a7e9-40d1-b915-6974c6d0ad98">

If there are technical constraints that make this too difficult then I'm okay with the idea of just using the `Add new` in the top right though. 😊
