### ISSUE TITLE
woocommerce_variation_has_changed javascript event not triggered upon variable product page load

### ISSUE THREAD

**Issue by ecv80** [woothemes/woocommerce#45643]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Because input.variation_id is fired twice, once with an empty value and the second time with the right value, one should use instead woocommerce_variation_has_changed event. However, as opposed to input.variation_id, woocommerce_variation_has_changed is not triggered when a variation product page is loaded directly, as in from the cart page.

I'm trying to wrap my head around some state system to keep track of these two events in order to handle all this, but it's just too in over my head.

Shouldn't woocommerce_variation_has_changed also trigger upon page load when it autoselects a given variation too? If not, what other events or ways could be used to handle this?

### Expected behavior

woocommerce_variation_has_changed should trigger upon variation autoselection on page load

### Actual behavior

it doesn't

### Steps to reproduce

1. Go to variable product
2. Select variation and add to cart
3. Go to cart
4. Select variation
5. Product page loads with variation selected
6. woocommerce_variation_has_changed isn't triggered, therefore it's not apparent how to make automatic adjustments upon the autoselected variation

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://localhost
Site address (URL): https://localhost
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4
PHP Version: 8.2.4
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient activada - puede que algunos plugins de pasarela de pago que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 5.98MB
Tamaño de los datos de la base de datos: 4.26MB
Tamaño del índice de la base de datos: 1.72MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.05MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 3.03MB + Índice: 0.06MB + Motor InnoDB
wp_postmeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_posts: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpml_mails: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 7
customize_changeset: 3
nav_menu_item: 9
page: 11
post: 2
product: 1
product_variation: 4
revision: 34
shop_coupon: 1
shop_order_placehold: 3
wp_global_styles: 5
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (5) ###

Clear Cache For Me: por Webhead LLC – 2.1.1
Customizer Reset: por WPZOOM – 1.1.1
Simply Show Hooks: por Stuart O'Brien
cxThemes – 1.2.1

Theme Check: por Theme Review Team – 20230417
WooCommerce: por Automattic – 8.3.1 (la actualización a la versión 8.6.1 está disponible)

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: por Automattic - Anti-spam Team – 5.3
Hello Dolly: por Matt Mullenweg – 1.7.2
WP Mail Logging: por WP Mail Logging Team – 1.12.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #7 - /productos/
Carrito: #8 - /carrito/
Finalizar compra: #9 - /finalizar-compra/
Mi cuenta: #10 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: LAMI
Version: 1.0.0
Author URL: https://www.ecvarts.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: lami/woocommerce/single-product\add-to-cart\variable.php
lami/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
lami/woocommerce/single-product\add-to-cart\variation.php
lami/woocommerce/single-product\product-attributes.php
lami/woocommerce/single-product\tabs\additional-information.php
lami/woocommerce/single-product\tabs\description.php
lami/woocommerce/single-product\tabs\tabs.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-17 00:05:30 +01:00
Options: ✔
Notes: 75
Onboarding: completed

### Action Scheduler ###

Completo: 45
Oldest: 2024-02-14 23:16:06 +0100
Newest: 2024-03-15 07:43:02 +0100

Fallida: 1
Oldest: 2023-11-03 01:17:54 +0100
Newest: 2023-11-03 01:17:54 +0100

Pendiente: 1
Oldest: 2024-03-16 07:43:02 +0100
Newest: 2024-03-16 07:43:02 +0100

### Status report information ###

Generated at: 2024-03-16 05:36:08 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
@ecv80 - Thanks for opening up this issue. I am unclear on your testing steps. You mentioned on step 3 to go to the cart and step 4 to selection a variation. How do you select the variation in the cart?

**Comment by ecv80** [comment]
> @ecv80 - Thanks for opening up this issue. I am unclear on your testing steps. You mentioned on step 3 to go to the cart and step 4 to selection a variation. How do you select the variation in the cart?

It's been over 6 months... I'm no longer working on that project. I have read the issue and I think what I meant is clicking on a variation product in the cart list, not choosing a variation there. From there the product page for that specific variation would open up, but unfortunately that event would not trigger like when one manually selects the variation in the product page. I hope this makes sense. I will check later on the project to confirm this as my memory could be wrong.

**Comment by roykho** [comment]
@ecv80 - sorry for the late reply.

> If not, what other events or ways could be used to handle this?

Perhaps give this one a try https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L305-L307

This trigger is fired when a valid variation (when a variation has been found which matches all attributes) is shown.
