### ISSUE TITLE
A simple mistake in the notation of the wc_get_customer_default_location function.

### ISSUE THREAD

**Issue by oginomizuho** [woothemes/woocommerce#45648]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In includes/wc-core-functions.php, line 1330,  the code  `! empty( $location['country'] )` is incorrect and should be `empty( $location['country'] )`.

### Expected behavior

When the customer's default location is not set, the first key obtained from `WC()->countries->get_allowed_countries()` is its replacement.

### Actual behavior

The above behavior is not operational even though the customer's default location is not set.

### Steps to reproduce

Call the `wc_get_customer_default_location()` function with the `woocommerce_specific_allowed_countries` option set, without the `woocommerce_default_customer_address` option set.

### WordPress Environment

woocoommerce 8.6.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
The code in question is actually correct -- please see the test added in #45810 on how to use this option (`woocommerce_allowed_countries` needs to be set to `specific`).
