### ISSUE TITLE
[DOC-BUG] process_payment return on failure

### ISSUE THREAD

**Issue by mesiarm** [woothemes/woocommerce#45652]
## Link to the Page/Section

https://github.com/woocommerce/woocommerce/blob/trunk/docs/payments/payment-gateway-api.md#process_payment-order_id-

## Description of the Suggestion

Docs suggests returning null on payment failure, but process_payment method should return array. Automattic\WooCommerce\StoreApi\Legacy::process_legacy_payment throws error because parameter is not expected to be null. Docs should suggest to return code like here (https://stackoverflow.com/questions/64317894/how-to-reload-checkout-page-if-payment-failed-in-woocommerce)
```
 return array(
        'result'   => 'failure',
        'redirect' => WC()->cart->get_checkout_url()
    );
```

## Reason for the Suggestion

Returning null throws error when using woocommerce blocks (https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md)

**Comment by vbelolapotkov** [comment]
Thanks for you report and suggestion @mesiarm . @deepakpathania @mjdeacon routing this one to you for further prioritization and decision on the best way forward here since it matches your team expertise.
