### ISSUE TITLE
Warning REST API V3: The WC_Abstract_Legacy_Order::get_product_from_item function is deprecated since version 4.4.0. Replace with $item->get_product()

### ISSUE THREAD

**Issue by luissimo** [woothemes/woocommerce#45707]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Retrieving an order through the V3 Rest api gives out a deprecation warning:

`2024/03/19 11:13:50 [error] 29492#29492: *2104978 FastCGI sent in stderr: "PHP message: The WC_Abstract_Legacy_Order::get_product_from_item function is deprecated since version 4.4.0. Replace with $item->get_product()" while reading response header from upstream, client: 54.211.198.197, server: xx.com, request: "PUT /wp-json/wc/v3/orders/102041 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.3-fpm-xx.sock:", host: "xx:27006"`

URL: `/wp-json/wc/v3/orders/<id>`

### Expected behavior

No deprecation warning.

### Actual behavior

Deprecation warning.

### Steps to reproduce

Use the Rest API V3 retrieve an order endpoint: [https://woocommerce.github.io/woocommerce-rest-api-docs/?ruby#retrieve-an-order](url)

### WordPress Environment

WooCommerce version: 8.6.1
WooCommerce REST: 8.6.1
WordPress version:  6.4.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @luissimo,

Thanks for reaching out. We couldn't find any uses of this deprecated method in WC core. Are you able to reproduce in other contexts or with other WooCommerce-related plugins disabled?
Do you have any other details you could share?

**Comment by luissimo** [comment]
It was indeed coming from PDF Invoices & Packing Slips plugin still using that deprecated function. It triggers when using the wc REST API. We contacted their support to fix it in the next update. This is solved.
