### ISSUE TITLE
Remove WooCommerce Blocks version from system report

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#45718]
System report still includes the WooCommerce Blocks version, but it's no longer being updated, it should be removed.

**Comment by ralucaStan** [comment]
Some websites might still use the plugin. Won't we want to know if that is the case? I think the ticket needs to be rephrased.

**Comment by senadir** [comment]
The version is read from WooCommerce, even if they’re running the plugin, the code won’t execute, and it will always show 11.8.0-dev.

For older Woo versions (8.3 and earlier) it might matter, but this change will only apply to the version it’s shipped with.

**Comment by mikejolley** [comment]
This was done in https://github.com/woocommerce/woocommerce/commit/c8f8299f023c8860bf0b276185e9c93a8c26b6b5
