### ISSUE TITLE
Translations of cart, cart page, and checkout blocks not working 

### ISSUE THREAD

**Issue by GuillaumeChatelain** [woothemes/woocommerce#45712]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

French translations of cart, cart page, and checkout blocks not working on a clean Wordpress/Woocommerce installation.
Translations works when editing the page in back-office but not in front-office.

Every translations works if switch to "classic" cart/checkout

### Expected behavior

Those blocks should be translated in front-office.

### Actual behavior

Everything is translated when editing the page in back-office but not in front-office.

![back](https://github.com/woocommerce/woocommerce/assets/159782260/037e9d6c-f55d-4952-bb67-b25b386c8335)

![front](https://github.com/woocommerce/woocommerce/assets/159782260/5c01687c-2c74-48f1-8992-e40bda16a22f)

### Steps to reproduce

New French Wordpress installation
Storefront Theme 
Install WooCommerce 8.6.1

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://devwordpress.test
Site address (URL): http://devwordpress.test
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58 (Win64) PHP/7.4.33 mod_fcgid/2.3.10-dev
PHP Version: 7.4.33
PHP Post Max Size: 8 Mo
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.70.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 8.2.0
Max Upload Size: 8 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Taille totale de la base de données: 1.90MB
Taille de la base de données: 1.64MB
Taille de l’index: 0.26MB
wp_woocommerce_sessions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_api_keys: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_order_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_order_itemmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_tax_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_actions: Données : 0.00MB + Index : 0.02MB + Moteur MyISAM
wp_actionscheduler_claims: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_groups: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_actionscheduler_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_commentmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_comments: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_links: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_options: Données : 1.56MB + Index : 0.04MB + Moteur MyISAM
wp_postmeta: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_posts: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_term_relationships: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_term_taxonomy: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_termmeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_terms: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_usermeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_users: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_wc_admin_notes: Données : 0.03MB + Index : 0.00MB + Moteur MyISAM
wp_wc_category_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_customer_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_order_addresses: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_coupon_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_order_operational_data: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_product_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_stats: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_tax_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_orders: Données : 0.00MB + Index : 0.02MB + Moteur MyISAM
wp_wc_orders_meta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_product_attributes_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_product_download_directories: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_product_meta_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_rate_limits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_reserved_stock: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 3
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: par Automattic – 8.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #8 - /boutique/
Panier: #9 - /panier/
Commander: #10 - /commander/
Mon compte: #11 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-20 14:31:23 +01:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Terminé: 7
Oldest: 2024-03-19 15:32:24 +0100
Newest: 2024-03-19 15:48:21 +0100

Échoué: 1
Oldest: 2024-03-19 15:34:48 +0100
Newest: 2024-03-19 15:34:48 +0100

En attente: 1
Oldest: 2024-03-20 15:32:24 +0100
Newest: 2024-03-20 15:32:24 +0100

### Status report information ###

Generated at: 2024-03-19 15:54:02 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by GuillaumeChatelain** [comment]
Tested on multiple themes, always the same translations fail

**Comment by rrennick** [comment]
@GuillaumeChatelain The translations for WooCommerce are maintained at WordPress.org. Could you check the [France french](https://translate.wordpress.org/locale/fr/default/wp-plugins/woocommerce/) translations for the version of WooCommerce you are using to see if the strings are translated?

**Comment by GuillaumeChatelain** [comment]
@rrennick Yes, the strings are translated in french.
As you can see in my screenshots when editing the checkout page in Back-office everything is translated.

But in front-office somes strings are missings.
Tested with Storefront to be sure it's not a theme issue.

And this probleme only affect woocommerce blocks.
On a "classic" checkout page everything is well translated.

**Comment by GuillaumeChatelain** [comment]
It was a local installation problem (Wampserver).
Once I put the website on my server every translations of the blocks work fine.

**Comment by rrennick** [comment]
@GuillaumeChatelain Thanks for the follow up.
