### ISSUE TITLE
Add phone number to My Account -> Addresses -> Edit Shipping Address form

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#45717]
We added phone number to the shipping address sometime ago for Checkout block, but this isn't reflected in My Account -> Addresses -> Edit Shipping Address form.
 The field is already present in the billing form and should be copied from there 
![image](https://github.com/woocommerce/woocommerce/assets/6165348/2524dfa6-8e49-47f7-b6ee-b4e12e021bba)

## Expected results

It should behave exactly like the billing address phone field.

<img width="735" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/22b5ef92-e3d7-43ce-a308-4276144bbcfe">

**Comment by ralucaStan** [comment]
@senadir as the author of this ticket could you present the expected result? Can you mention any field properties we should be aware of (required, visibility etc).

**Comment by senadir** [comment]
>  as the author of this ticket could you present the expected result?

Added a screenshot.

>  Can you mention any field properties we should be aware of (required, visibility etc).

It should behave like the billing phone field, so copy paste.

**Comment by nielslange** [comment]
@wavvves I see that you've assigned this issue to you. We also have https://github.com/woocommerce/woocommerce/issues/46582, which not only covers the `Phone number` field, but also the `Conmany name` and `Address line 2` fields. Worth mentioning that https://github.com/woocommerce/woocommerce/issues/46582 replies on https://github.com/woocommerce/woocommerce/issues/46581. I wonder if we should close this issue in benefit of https://github.com/woocommerce/woocommerce/issues/46582? 

cc: @ralucaStan & @senadir

**Comment by wavvves** [comment]
> @wavvves I see that you've assigned this issue to you. We also have https://github.com/woocommerce/woocommerce/issues/46582, which not only covers the `Phone number` field, but also the `Conmany name` and `Address line 2` fields. Worth mentioning that https://github.com/woocommerce/woocommerce/issues/46582 replies on https://github.com/woocommerce/woocommerce/issues/46581. I wonder if we should close this issue in benefit of https://github.com/woocommerce/woocommerce/issues/46582? 
> 
> 
> 
> cc: @ralucaStan & @senadir 

Hi Niels, I already have the changes in place to open a PR to address the phone number, refactoring the logic to avoid duplicate code with billing address. I'd say remove the phone field from #46582 and proceed with the remaining fields 👍

**Comment by nielslange** [comment]
> Hi Niels, I already have the changes in place to open a PR to address the phone number, refactoring the logic to avoid duplicate code with billing address. I'd say remove the phone field from https://github.com/woocommerce/woocommerce/issues/46582 and proceed with the remaining fields 👍

In this case, just open your PR and get it shipped. I'd leave the `Phone number` field in #46582, as that PR is not only about displaying the field, but to ensure that we're using the same display logic as when using a classic theme and the classic checkout process, e.g. when the `Phone number` field is hidden, it should not appear in the `My Account` address forms. When it's required in the checkout process, it should also be required in the `My Account` address forms.

**Comment by senadir** [comment]
As we discussed in our call, this issue is separate from the one you're working on. This is for now just to make sure the work we did some years ago to introduce a shipping phone number is feature complete.

See: https://github.com/woocommerce/woocommerce/pull/30097
https://github.com/woocommerce/woocommerce/pull/45788

**Comment by nielslange** [comment]
Thanks for pointing this out, @senadir. As discussed in p1714471829971759-slack-C8X6Q7XQU, this particular issue ensures to show the `Phone number` field in the shipping address form, as it's currently only displayed in the billing address form. I missed that (crucial) part initially.
